### ISSUE TITLE
Dartfix non-nullable should add `late` to local variables where necessary

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#39699] opened 2019-12-06 19:20 UTC
There is a common pattern in tests where you have a local or top level variable which gets assigned late in a `setUp` method, typically because you need a new instance to be created for each test.

In most cases the right thing here would probably be to make those variables `late`, although changing the type to be nullable would also be valid. But the tool doesn't do either of those so you are left with a lot of static errors in tests.

Example:

```dart
import 'package:test/test.dart';

main() {
  String thing;

  setUp(() {
    thing = 'hello';
  });

  test('basic test', () {
    // Error: The non-nullable local variable 'thing' must be assigned before it can be used.
    expect(thing.substring(1, 3), equals('el'));
  });
}
```

**Comment by srawlins** [comment] 2019-12-08 22:42
Duplicate of https://github.com/dart-lang/sdk/issues/38291

**Closed by srawlins** 2019-12-08 22:42 UTC
Labels: analyzer-nnbd-migration, area-analyzer, nnbd-migration-correctness-example
