### ISSUE TITLE
Static getter or setter declaration doesn't add an instance one to the Type object

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#23721] opened 2015-06-26 09:37 UTC
According Dart specification (2-n Edition, December 2014) p. 10.2

"The effect of a static getter declaration in class C is to add an instance getter with the same name and signature to the Type object for class C that forwards (9.1) to the static getter."

But in fact no getter/setter instance added to the Type object. The following code demonstrates the issue:

``` dart
class C {
  static get g => 1;
}

main() {
  C c = new C();
  Type t = c.runtimeType;
  var x = t.g;  //throws NoSuchMethodError
}
```

**Comment by munificent** [comment] 2016-12-14 00:39
Yes, the spec does indeed seem to imply that static members on classes become instance members on result of calling `runtimeType` on an instance of that class.

That's something we've talked about forever, but as far as I know, we did not decide to do that. The implementations certainly don't, so I don't see why the spec says they should. As far as I know, this should be removed from the spec.

**Comment by lrhn** [comment] 2016-12-14 14:00
The spec also goes out of its way to make those getters and setters invisible again.
From section 16.18.1 (Getter Access and Method Extraction):
> Otherwise, *i* is a getter invocation. Let *f* be the result of looking up (16.15.2)  getter (10.2) *m* in *o* with respect to *L*. If *o* is an instance of `Type` but *e* is not a constant type literal, then if *f* is a getter that forwards to a static getter, getter lookup fails.

That's a roundabout way of saying that the getter on the `Type` object introduced by a static declaration cannot be looked up on the `Type` object in general. It only works if you do a static access directly on the type as a literal.

So, working as intended, but we might want to streamline the spec a little at some point in the future.

**Comment by eernstg** [comment] 2018-02-06 17:52
No milestone now: This clarification should be considered and possibly performed, but this will not block Dart 2.

**Comment by eernstg** [comment] 2018-08-24 16:06
All these sentences that amount to a specification of a kind of "meta classes" (where each `Type` instance _t_ would have instance members corresponding to the static members of the class represented by _t_) will be deleted, because that feature is no longer planned. We will then, of course, also need to remove the twisted wording which annihilates those instance methods again (that's all those `if .. forwards to a static .. lookup fails`).

**Comment by eernstg** [comment] 2019-01-18 11:34
Closing: All text concerned with "meta classes" has been removed from the language specification as of 614ae7f362ac2df8500c050862e76c4fc66b8822, in particular the text which gave rise to this issue.

**Closed by eernstg** 2019-01-18 11:34 UTC
Labels: area-specification
