### ISSUE TITLE
Prevent running Fix-All on-save from removing unused imports

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#52046] opened 2023-04-14 23:14 UTC
## Problem
Users feel pestered by having to add and remove the `const` keyword when iterating on Flutter code. This seems like something their IDE should handle for them and while there are automated fixes that still feels like too much work for something that should be as seamless as formatting code on save.
There is an existing fixAll on save option in VSCode but it isn't for all users as some fixes are harmful to run on save. For example, remove unused import. 

## Proposal
Add an enabled by default option in the Dart VSCode plugin that only applies a safe subset of Dart fixes on file save.
Subset:

- prefer_const_constructors
- fix for removing invalid const
- prefer_generic_function_type_aliases <has dartfmt fix>
- avoid_init_to_null
- avoid_return_types_on_setters
- avoid_returning_null_for_void <has dartfmt fix>
- avoid_single_cascade_in_expression_statements <has dartfmt fix>
- prefer_collection_literals
- slash_for_doc_comments <has dartfmt fix>
- unnecessary_new <has dartfmt fix>
- unnecessary_string_escapes
- use_function_type_syntax_for_parameters
- sort_child_properties_last (?)
- use_full_hex_values_for_flutter_colors
- unnecessary_parenthesis (?)

### Prior art
Enable fix on save for Dart in VSCode:
```
"[dart]": {
        "editor.codeActionsOnSave": {
            "source.fixAll": true
        },
       // ...
    }
```
Fyi @DanTup @bwilkerson

**Comment by gspencergoog** [comment] 2023-04-14 23:30
One thing I noticed with `source.fixAll` on, is that it isn't recursive: If I have this:

```dart
Foo foo = const Bar();
```

And I hit save, it converts it to:
```dart
final Foo foo = const Bar();
```
(and I'm not sure why it picked final instead of const)

And it still has a warning about the extra const.  Then if I hit save again, it converts it to:

```dart
const Foo foo = Bar();
```

It should go straight to the end.

**Comment by DanTup** [comment] 2023-04-15 09:21
@jacob314 

> Add an enabled by default option in the Dart VSCode plugin

Do we really want to do this by default? We don't enable format-on-save by default, so something that alters code on-save would be surprising to me. I also think it might also not be obvious to users what's happening or how to disable it (especially since VS Code does a terrible job with language-specific configuration defaults - they're almost invisible to users which often causes complaints that we're ignoring a users preferences).


>  that only applies a safe subset of Dart fixes on file save.

My understanding was that the `fixAll` command (which is the same as "dart fix") was intended to be "safe". If we don't think it is, I wonder if we should remove fixes like "remove unused import" from it rather than adding another fix-all-like action. VS Code/LSP have first-class support for "fix all" but there is only one, so we may end up with a well-known "fix all" and then another "fix all" that is Dart-specific which I think would be confusing - something discussed a bit in https://github.com/Dart-Code/Dart-Code/issues/4446).

If "remove unused imports" is the _only_ problematic fix, it's already another well-known action in VS Code, and the user can explicitly add it to run on-save (like `fixAll`). So if we removed it from `fixAll` users that want it could still opt-in to it.


@gspencergoog 

> One thing I noticed with `source.fixAll` on, is that it isn't recursive

That's correct, there's an open issue about this at https://github.com/dart-lang/sdk/issues/47968. It's a little more complex supporting here than in `dart fix` because we need to produce edits that can be applied in a single step (we can't give VS Code a _sequence_ of edits).

**Comment by DanTup** [comment] 2023-04-15 09:28
An alternative to enabling by default ("configurationDefaults" - which is fairly invisible) is to add it to our [recommended settings](https://dartcode.org/docs/recommended-settings/) that we prompt to write on first run. These settings are written into the users settings JSON which is more visible than configuration defaults. We could re-trigger the settings prompt for existing users when we make significant changes to it like this.

**Comment by jacob314** [comment] 2023-04-16 19:53
Do we know what our adoption rate is for the recommended settings?
I'm not advocating making this as more of a default than formatOnSave but instead aligning adoption with existing adoption of formatOnSave as much as practical.

**Comment by DanTup** [comment] 2023-04-16 22:19
> Do we know what our adoption rate is for the recommended settings?

I don't, although around 65% of users have format-on-save enabled and I suspect a good number got it from accepting the recommended settings. Although, "accepting" recommended settings is just a one-time copy, so making changes wouldn't automatically apply them to those users.

> but instead aligning adoption with existing adoption of formatOnSave as much as practical.

Would it be reasonable to include some of these things in the Format operation (so it also runs with format-on-save)? I think it would be confusing to have some other "set" of changes that can be run on save ("format" and "fix all") but perhaps some of the very obvious things (like removing unnecessary const) wouldn't be completely out of place as part of formatting?


Or perhaps some configurability for Fix All would help here? I know some users would like to apply some fixes on-save that might not be the single obvious fix (which I believe is the current intention of `dart fix`), and perhaps having the option to control this would also allow for suppressing some fixes (such as removing unused imports)?

I don't know if it's useful, but we also know when code actions are running on-save, so if we wanted to skip "remove unused imports" for a fix-all-on-save but include it for a manual invocation, we could (although, I think this could also be confusing unless it was something the user specifically opted-in to by choosing some fixes to be applied only when run manually).


> There is an existing fixAll on save option in VSCode but it isn't for all users as some fixes are harmful to run on save. For example, remove unused import.

Do we have an idea of how many fixes are currently included in fix-all-on-save that users might not like? Is it only removing unused imports, or are there others?

**Comment by DanTup** [comment] 2023-04-17 16:45
Chatted briefly with @jacob314 about this and I think we should avoid adding some third on-save mechanism (which would be Dart-specific, unlike the current format-on-save/fix-on-save) but instead make the existing "fix all" command work better here with some configurability.

For example we could add something to `analysis_options.yaml` allowing fixes to be configured to always run, never run, or run only when manually invoked (or on-save):

```yaml
fixes:
  "quickfix.convert.toSuperParameters": true # ("always"?) - always fix with "fix all"
  "quickfix.convert.toSuperParameters": false # ("never"?) - never fix with "fix all"
  "quickfix.convert.toSuperParameters": command # (?) -  fix only when "fix all" is manually invoked
  "quickfix.convert.toSuperParameters": save # (?) - fix only when "fix all" is invoked on-save
```

We could default things like removing unused imports to `on-command` (or some better name) so that running fix-all-on-save is a "safer" than just running all fixes we support, but users could still opt-in to running the others.

This could also eventually support enabling specific fixes users want that aren't part of the "safe dart fix" set (it's possible to do this today by just listing each of them as code-actions-on-save in VS Code, but it's much slower because each fix is its own round-trip to the server).

Once we have what we think are a safe set to run on-save, we could consider adding fix-all-on-save to Recommended Settings, and re-prompting users about them. We could also prompt them (from the server) the first time they explicitly run "Fix All" about being able to run it on-save with a link to a page on the Dart website about these options.

Interested in others thoughts on this.

**Comment by bwilkerson** [comment] 2023-04-17 22:54
I have a concern here. I believe that files are saved for several different reasons. Sometimes is automatic (either by preference setting or because the run command saves everything), sometimes it's because a user feels more comfortable having changes saved to disk, and sometimes because the user is done making edits. Some users will be happy to have fixes applied in all of those cases, some one subset of cases or another, and some never.

I'm not advocating for any particular solution (and I'd actively advocate against any solution that was complex enough to handle all possible combinations). Whatever solution we come up with, I want users to have just enough control without having too many controls.

What I _am_ saying is that 'save' might not always mean 'ready to have fixes applied'. As a result, I'm skeptical that associating this behavior (a large scale fix operation) with save is the right thing to do.

I'm just speculating, but I wonder whether it might not be better to have some kind of 'cleanup' command that will apply fixes, sort members, format files, and any other kind of cleanup operations that we come up with in the future as a single command. I wouldn't mind having a keyboard shortcut for cleanup (or cleanup and save) that was distinct from the save command. I wonder whether that would satisfy the need we're trying to solve here.

**Comment by DanTup** [comment] 2023-04-18 09:38
> I'm just speculating, but I wonder whether it might not be better to have some kind of 'cleanup' command that will apply fixes, sort members, format files, and any other kind of cleanup operations that we come up with in the future as a single command. I wouldn't mind having a keyboard shortcut for cleanup (or cleanup and save) that was distinct from the save command. I wonder whether that would satisfy the need we're trying to solve here.

To me, this doesn't seem a long way from what we have today with the "Fix All" command, if we added some configurability. If we had config for fixes as described above and format + sort members were options you could enable, then we could use the built-in "Fix All" command in VS Code (and VS Code's existing functionality for running it on save _if you wanted_) rather than introducing some new Dart-specific command (which I suspect if we did without configurability, users might quickly ask for customised versions of that cleanup).

If we really don't want to use "fix all" (eg. because we want that to do "everything", but users want to fix trivial things like `const`s on-save), we could also consider including some of those trivial fixes as part of formatting. I'm sure there are already formatters that do things like inserting semicolons during format, so I wonder if us adding/removing `const`s and other trivial things would be that surprising?

**Comment by bwilkerson** [comment] 2023-04-18 20:23
> ... we could also consider including some of those trivial fixes as part of formatting.

The formatter can't adjust the use of `const` because doing so requires semantic information that the formatter doesn't have.

But even if it could, I'm not convinced that it would be the right thing to do. While I understand the convenience argument, I believe that it's confusing to users to have multiple tools that all perform some subset of fixing code. Having a tool that applies multiple smaller tools is fine (for example, to satisfy the "fix everything in one step" journey), but users shouldn't have to ask themselves a question like "Which tool do I use to apply this kind of fix?". There should be one tool that fixes problems in the code and a different one that makes non-whitespace changes. (There's a school of thought that says that some changes, like adding or removing trailing commas, is equivalent to a whitespace change. Not sure how I feel about that one.)

**Comment by jacob314** [comment] 2023-04-21 04:40
The key problem I want us to solve is to get to a state where most users automatically run fixes to add and remove `const` and sort imports on save. For everything else I'm happy with the path that will confuse users least. 
I would be ok with this is branded as "code cleanup on save", "safe fixes on save", or just a default filtered list of fixes to apply on save.

Some prior art is this feature is referred to as "code cleanup on save" in Visual Studio.
https://devblogs.microsoft.com/visualstudio/bringing-code-cleanup-on-save-to-visual-studio-2022-17-1-preview-2/
Note that for this feature users can customize which fixes are applied on save and that code formatting isn't treated as anything more than just another one of the categories of fixes that can be applied.
I do worry we think of dart format as being more separate from dart fix due to the org chart of the Dart team. Yes it provides 100% safe fixes but we have other 100% safe fixes as well.

**Comment by bwilkerson** [comment] 2023-04-21 16:00
> Some prior art is this feature is referred to as "code cleanup on save" in Visual Studio.

VS Code has the equivalent (using `editor.codeActionsOnSave`), though the UI for settings in VS Code is primitive by comparison, which is somewhat concerning.

One of the differences between "code cleanup on save" and what we're talking about is that `dart fix` is much coarser grained than what "code cleanup on save" supports. We've been discussing various approaches to allow the finer-grained control, but I'm not sure we know what granularity users want to have.

@InMatrix I wonder whether you might have some feedback on what granularity is optimal here?

> I do worry we think of dart format as being more separate from dart fix due to the org chart of the Dart team. Yes it provides 100% safe fixes but we have other 100% safe fixes as well.

We have a goal to increase the separation of the two by removing the fix support from the formatter and moving it into `dart fix`. The reason for that goal isn't the org chart, it's usability. I (and others, I think) believe that it will be easier for users if there's one tool that fixes their code rather than having to learn multiple tools to run in order to get all of the fixes.

**Comment by InMatrix** [comment] 2023-04-21 18:28
This question has probably been discussed elsewhere, but I was wondering how much adding those `const` keyword actually helps improve performance. If `dart fix` can reliably inserting or removing `const` for the user, why can't the complier do that under the hood? 

> Note that for this feature users can customize which fixes are applied on save and that code formatting isn't treated as anything more than just another one of the categories of fixes that can be applied.

Giving users sufficient control is important, since modifying the substance of the code on each save can make users more nervous than modifying its formatting, which won't alter what the code gets compiled into. We might also need to check how undo would work in this case. If that works well, it would allow users to slowly build confidence in this feature and eventually let it be part of their workflow.

**Comment by bwilkerson** [comment] 2023-04-21 18:55
> We might also need to check how undo would work in this case.

I tried an experiment, and it appears that there's a separate entry on the undo stack for each of the actions enabled by `editor.codeActionsOnSave`. That means that the user has to undo the last action before undoing the next to last actions, etc. all the way back to the first.

Not sure what that means in terms of having finer-grained or coarser-grained actions on the list.

**Comment by jacob314** [comment] 2023-04-21 19:58
The compiler doesn't do it under the hood because we are worried it would be surprising to users as it isn't obvious which things are const or not. If all users used IDEs for everything we should have the IDEs show the implicit const keywords in the IDE making the behavior clear. Essentially the motivation for a auto fix based workflow is to get that same experience where const is automatically added and removed while preserving clarity outside of IDEs and in code review tools.

**Comment by gspencergoog** [comment] 2023-04-21 20:15
But if adding const when possible is always safe, and can only result in performance improvements, why can't the compiler convert things to const when possible the way it inlines things?  Basically: why would I care if something were "automatically" const or not if it can only result in improvements? I can see the case for explicit const still existing, so I can have the compiler complain if something can no longer be const, but an implicit const seems fine to me.

If there are cases where adding const can cause performance regressions, then of course the current setup makes sense, but also makes me doubt whether turning on the lint or automatically applying the fix is a good idea.

**Comment by DanTup** [comment] 2023-04-24 16:40
I don't have an opinion on the `const` issue, but even if we solved that another way there are a number of other fixes noted at the top of this issue that we'd probably still want to address (so perhaps it's worth splitting the `const` question into its own issue?).

Another possibility I thought of while discussing with @jacob314 today was:

- add a new fix `source.fixAll.simple` - "Fix Simple Issues" (or some other name.. trivial? something that indicates it's a small subset of the main one)
- document clearly on the website how "simple fixes" differs from "fix all" (either by noting the things excluded from "simple fixes" that are in the full set, or an explicit list of what's included in simple fixes)
- when guiding users to enable fix-all-on-save, use `source.fixAll.simple`

Unlike one of my earlier suggestions, I think we could do this without having to let the user configure them (between on-save/explicit invocations) and without any of the behaviour being surprising.

I'm not totally stoked about a second "fix all" command, but given all the other options considered, it feels like the simplest (both in terms of implementation, and ability for the user to understand it).

I think users still have a desire to run additional fixes on-save that aren't in the normal "dart fix" set and this doesn't address that, but they _can_ already do that today by listing them explicitly in "codeActionsOnSave" even if it does have some slight quirks (multiple undo steps, slightly worse perf from many server round trips).

Thoughts?

**Comment by gspencergoog** [comment] 2023-04-24 18:14
I kind of liked the idea of a separate configuration that defined the set of fixes that `fixAll` applied. It felt like the equivalent to being able to define your own `analysis_options.yaml` for your project that customizes how you liked to be guided. And it also scales better to more fixes, since it wouldn't have the multiple undo/round trip problems.

You could still have the `source.fixAll.simple`, though: it would just use a predefined set instead of a configured set, similar to the way we have defined the `flutter_lints` package to have a set of recommended lints.

**Comment by DanTup** [comment] 2023-04-25 09:15
I do like the idea of allowing users to configure this, but:

1. I don't know if the additional complexity is justified (I don't know how many people would use it) - although I do know that some users would like to choose fixes to include that `dart fix` currently doesn't include (because the bar for being on by default for `dart fix` may be more strict and users own preferences)
2. I feel like it might not be obvious to users why the default behaviour of fix-all-on-save and fix-all-from-palette are different. We can certainly document this, but it might not be an obvious/easy thing for users to find and it might just seem like a bug (whereas a command named "Fix simple issues" or similar is self-describing, and gives the user terms to search for to find the exact list if they'd like).

I think if we're going to let users configure them, the previous suggestion of just using the single command and configuring whether fixes run never/always/only-manual-invocations is probably better than introducing a second command though, because having two commands that can be configured makes the names/distinction a little less clear.

I _think_ we could always start with the simpler option and later "upgrade" if it's clear there's demand (by making the on-save version match what we had in "simple" by default, and then either aliasing `source.fixAll.simple` to do the same, or having Dart-Code detect when users are using that and prompt them to change it to `source.fixAll` and a link to some notes about the change).

**Comment by InMatrix** [comment] 2023-04-25 20:00
Re: configurability. We can create a sensible default list of fixes and then allow the user to customize that list. One thing that can help communicating what happens on save is to print messages when fixes are auto-applied on save, just like what we do for hot reload on save. The message can potentially include a link to a configuration file/UI.

**Comment by bwilkerson** [comment] 2023-04-25 21:02
We do need to be careful about "upgrading". For example, if we decide to have a default list of fixes that are run when there's no configuration, and adding a configuration would override the defaults, then users could lose functionality when they're trying to add new fixes to the list if they don't know all of the default values that need to be included in order to achieve parity. That could be frustrating.

And there's another aspect to configurability that we haven't discussed: discoverability. There isn't currently any user friendly list of the fixes that they could potentially add to the list. We would need to have a way for users to know what they can add to the list and what specifically each item will actually do, but that list might be large. If we limit the list to the 15 in the original comment, then that's not too bad. If we open it up to everything then we'd likely have on the order of 250-300 items for users to choose between. I'm not arguing against doing something to solve this problem, just pointing out another consideration.

> ... some users would like to choose fixes to include that `dart fix` currently doesn't include ...

Just curious, but do we have concrete asks, or is this more of a general request?

**Comment by DanTup** [comment] 2023-04-26 10:48
> We do need to be careful about "upgrading". For example, if we decide to have a default list of fixes that are run when there's no configuration, and adding a configuration would override the defaults, then users could lose functionality when they're trying to add new fixes to the list if they don't know all of the default values that need to be included in order to achieve parity. That could be frustrating.

I had in my mind that the user configuration would just layer on top. I think this is how lints work. For example if the defaults were:

```
fixes:
  - fix_one: never
  - fix_two: always
  - fix_three: manual
```

Then if the user configured:

```
fixes:
  fix_one: always
```

Then they should still have the same defaults from fix_two/fix_three.

> And there's another aspect to configurability that we haven't discussed: discoverability. There isn't currently any user friendly list of the fixes that they could potentially add to the list.

Also similar to lints, I think we could have auto-complete of the available fixes. We could also complete them with their default values (eg. insert `- "fix_one: never"` when the user completes the `fix_one` option). This is what VS Code does with its settings and I find it quite useful.


> and what specifically each item will actually do

If we have some descriptions in the server, we could expose these in hovers and/or the documentation shown with completions.

(note: I'm not specifically arguing for the configuration option over something simple, but I think we could probably provide a decent experience if we did).


> > ... some users would like to choose fixes to include that dart fix currently doesn't include ...
> 
> Just curious, but do we have concrete asks, or is this more of a general request?

A bit of both. I recall responding to quite a few requests for specific fixes not working in codeActionsOnSave, and also comments about how it doesn't run "all fixes". Generally I direct people to open issues in the SDK with specific fixes that are not currently included in "dart fix").

I have generally assumed that the items missing from that set are usually because they're subjective (or there are multiple possible fixes and we don't know what the user would want), but it's certainly possible that in most cases they're just not implemented but could be.

I had a quick search in the Dart-Code repo and couldn't find many (it's possible some requests were in the Dart-Code Discord, or also possible I'm just failing to find the because GitHub search isn't brilliant), but here are some:

- https://github.com/Dart-Code/Dart-Code/issues/4458 - add all missing imports (this one is a little tricky because there could be multiple)
- https://github.com/Dart-Code/Dart-Code/issues/4009 - sort pub packages in pubspec (this one has a lint so probably is just missing a fix implementation rather than being deliberately excluded)
- https://github.com/Dart-Code/Dart-Code/issues/3696 - this one is quite general ("I applied flutter_lints to an old project and more than 200 problems appeared. dart fix didn't fix them for me") but has a few examples
- https://github.com/Dart-Code/Dart-Code/issues/3575 - fixes from plugins (this one also likely also more complex)

**Comment by DanTup** [comment] 2023-05-11 17:03
It seems like the only contentious fix might be "remove unused imports" in which case full configurability might be necessary. To keep things simple for now, I propose we:

- exclude "remove unused imports" from running when the `source.fixAll` command is trigged by save
  (manually running the "Fix All" command from the VS Code command palette will still include it)
- document how you can have both "fix all" and "remove unused imports" run on-save if you'd like to keep the same behaviour that you get today (this will be done by explicitly listing the "remove unused import" fix ID in `editor.codeActionsOnSave`)
- once this has shipped in stable SDKs, add fix-all-on-save to the [recommend settings](https://dartcode.org/docs/recommended-settings/) we prompt users about on first run
- add a flag that allows us to re-prompt to use recommend settings when there are significant changes (such as this one)

Any other opinions or objections/concerns? (if not, I may proceed in this way)

**Closed** 2023-05-25 17:24 UTC
Labels: area-analyzer, P3, type-enhancement, analyzer-lsp

**Comment by DanTup** [comment] 2023-05-25 17:52
This change has landed, so using fix-all-on-save will no longer strip unused imports.

If you want the original behaviour (to fix up imports on save), the best way is to additionally run `source.organizeImports` on save:

```
"editor.codeActionsOnSave": {
	"source.fixAll": true,
	"source.organizeImports": true
}
```

**Comment by Mayb3Nots** [comment] 2023-08-03 07:18
@DanTup What about the `unused_element` lint? When I create a widget via vscode snippet it always include the `key` parameter however when I save it removes the `key` parameter because its currently not in used (which is expected because I am just creating the widget) but I will later need to use it which is very annoying to have to go back and forth.

Is there no way to disable auto fix for a certain lint?

**Comment by DanTup** [comment] 2023-08-03 10:09
@Mayb3Nots there isn't, however this was reported in https://github.com/Dart-Code/Dart-Code/issues/4655 and I have an open change to exclude the remove-unused-parameter fix when running on-save too.
