### ISSUE TITLE
The analyzer no-longer produces "ignore <code> for this line" quick-fixes for analyzer_plugins

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#51959] opened 2023-04-05 09:12 UTC
Hello!

This issue is related to analyzer_plugins. When plugins emit diagnostics, the analyzer used to natively include the quick fixes for ignoring a lint ("ignore code for this line").

It appears that on the current master branch of Dart,  those fixes no longer appear.   
Dart SDK version: 3.0.0-405.0.dev (dev) (Mon Apr 3 19:37:36 2023 -0700) on "macos_arm64"

**Comment by pq** [comment] 2023-04-05 17:40
Confirmed locally.

**Comment by bwilkerson** [comment] 2023-04-05 20:41
Which IDE are you using?

I don't know why the behavior might have changed, but I'll record some information that might be useful for debugging the problem.

As far as I can see, the `FixProcessor` is only ever called when there is a diagnostic that was produced by the analyzer. I have no memory of it having ever been used on diagnostics returned by the plugin, and I find it hard to imagine that it was, given that diagnostics returned by plugins are represented by a class that's unrelated (in a type sense) to the representation of diagnostics passed to the `FixProcessor`. So, I'm skeptical that the server has ever produced these fixes for diagnostics from plugins. But, assuming I'm wrong ...

The ability for the analysis server to produce 'ignore' fixes was added in https://dart-review.googlesource.com/c/sdk/+/203760. That code hasn't changed (other than being reformatted at some point), so it seems unlikely that that could be the problem.

Prior to that the 'add ignore' fixes were being added by the IDE plugins. I suppose it's possible that the IDE plugin you're using changed so that it no longer adds these suggestions, and that that's the reason for the changed behavior, but I have no evidence of that, so I'm not saying that that's what happened.

It is, of course, quite possible that the fixes were being added in the server by some code I'm not aware of and that something broke that code recently.

**Comment by rrousselGit** [comment] 2023-04-06 10:33
Hello! Thanks for the detailed reply.
I'm using vscode

**Comment by rrousselGit** [comment] 2023-04-06 10:38
I just switched back to the stable channel and it is true that the quick-fix isn't available there either.

So it is probable that it was indeed vscode that added this quickfix instead of the analyzer.

**Comment by DanTup** [comment] 2023-04-06 13:14
Yeah, this is likely because of the issue we discussed in https://github.com/Dart-Code/Dart-Code/issues/4421 (which spawned https://github.com/Dart-Code/Dart-Code/issues/4455). Dart-Code was previously contributing these, but there were races in the code that were sometimes causing errors. It was assumed that because the server was producing these, that it wouldn't really change anything.

If I'm understanding correctly, ignoring diagnostics for plugins is handled by plugins themselves and not the server? This presumably means there's no guarantee that plugins support ignore comments, or that the format matches that used by the Dart server (I noticed that DCM supports `type=lint` that server might append onto the end of, instead of inserting before it, for example).

Assuming that's the case, I think it may be better for the plugin to contribute the actions directly. Having the server include ignore actions for a plugin that might not implement ignore could be confusing.

The server implementation is relatively straight forward (although if for DCM `type=lint` should always be at the end, it might need some additional tweaks):

https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/correction/dart/ignore_diagnostic.dart#L32-L63

**Comment by incendial** [comment] 2023-04-06 13:39
> If I'm understanding correctly, ignoring diagnostics for plugins is handled by plugins themselves and not the server?

Yes.

> This presumably means there's no guarantee that plugins support ignore comments, or that the format matches that used by the Dart server (I noticed that DCM supports type=lint that server might append onto the end of, instead of inserting before it, for example).

Agree, especially if there is some additional logic like unignorable severity or something. But if I'm not mistaken, the plugin version of DCM does not support `type=lint` at all (and probably won't).

**Comment by rrousselGit** [comment] 2023-04-06 13:50
Technically there's an issue related to having the analyzer server deal with //ignore for plugins.

But for now, I'm happy to have plugins manually add the quick-fix.

**Comment by DanTup** [comment] 2023-04-06 14:32
Shall we close this then? I think we're agreed it probably doesn't make sense to handle this in server unless we also handled the ignores (which I have no opinion on personally, but suspect plugins would prefer to do themselves?).

**Closed** 2023-04-06 14:43 UTC
Labels: area-analyzer, analyzer-quick-fix, P2, type-bug, analyzer-plugin

**Comment by rrousselGit** [comment] 2023-06-01 07:51
@DanTup Did VScode someone added the quick-fix back?

In the meantime, I had my analyzer_plugin manually provide the `add // ignore` quick fix. But now the IDE shows two of them because of it:

![Screenshot 2023-06-01 at 09 51 47](https://github.com/dart-lang/sdk/assets/20165741/f11f51dd-4862-40ab-9915-9f28ee658780)

**Comment by rrousselGit** [comment] 2023-06-01 07:53
Wait no, ignore me, I'm an idiot 🙈 

These aren't duplicates, but rather "for line" vs "for file". Ha

**Comment by bwilkerson** [comment] 2023-06-01 15:12
I think so. It's too easy to confuse them.

**Comment by DanTup** [comment] 2023-06-01 18:39
I think the screenshot above is actually from @rrousselGit's code as servers already contain the word "this". The issue is the same though, so I've opened https://dart-review.googlesource.com/c/sdk/+/306940 which adds the word "whole" so they're different lengths now too:

- Ignore 'foo' for this line
- Ignore 'foo' for this whole file

@rrousselGit if you want yours to be more consistent, you should change to single quotes and add the word "this" (and "whole" for the file one - pending any other suggestions on the CL)

**Comment by DanTup** [comment] 2023-06-01 20:20
@rrousselGit minor tweak from when I wrote my original comment - it's now "this line" and "the whole file".
