### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Could not load dart file /I:/street_crisis/lib/profile_tabs/account/components/account_menu.dart

### ISSUE THREAD

**Issue by junade47** [dart-lang/sdk#45424] opened 2021-03-23 13:37 UTC
Could not load dart file /I:/street_crisis/lib/profile_tabs/account/components/account_menu.dart

Error: Error reaching migration preview server.

Please fill in the following:

**Name of package being migrated (if public)**:
**What I was doing when this issue occurred**:
**Is it possible to work around this issue**:
**Has this issue happened before, and if so, how often**:
**Dart SDK version**: 2.12.2
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
Error reaching migration preview server.
    at Object.b (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:311:3)
    at http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:3133:9
    at Gs.a (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:1572:72)
    at Gs.$2 (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:4670:23)
    at SX.$2 (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:4665:25)
    at Ji.rp (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:4942:25)
    at Fe.Kw (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:4727:27)
    at RW.$0 (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:4875:42)
    at Object.HZ (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:1620:76)
    at vs.ZL (http://127.0.0.1:33254/I:/street_crisis?authToken=c_hfnaSpiX0%3D:4788:3)
```

**Comment by vsmenon** [comment] 2021-03-23 20:35
Can you please provide the requested info?

**Comment by stereotype441** [comment] 2021-03-24 17:41
Duplicate of #45202

**Closed by stereotype441** 2021-03-24 17:41 UTC
Labels: P1, area-migration, needs-info
