### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31154] opened 2017-10-19 10:50 UTC
Crash in fasta
@peter-ahe-google
id: 030e4a918c765b9fbd3ce36478ef537b5186cd87

```
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
#1      Procedure.setterType (package:kernel/ast.dart:1402:40)
#2      ForwardingNode._resolve (package:front_end/src/fasta/type_inference/interface_resolver.dart:448:33)
#3      ForwardingNode.resolve (package:front_end/src/fasta/type_inference/interface_resolver.dart:142:39)
#4      InterfaceResolver.finalizeCovariance (package:front_end/src/fasta/type_inference/interface_resolver.dart:666:45)
#5      ShadowClass.finalizeCovariance (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:320:23)
#6      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:523:14)
#7      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:264:14)
<asynchronous suspension>
#8      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:96:28)
<asynchronous suspension>
#9      BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:51:37)
<asynchronous suspension>
#10     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#11     _rootRun (dart:async/zone.dart:1124)
#12     _CustomZone.run (dart:async/zone.dart:1021)
#13     runZoned (dart:async/zone.dart:1499)
#14     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#15     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#16     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#17     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:60:27)
<asynchronous suspension>
#18     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:39:9)
<asynchronous suspension>
#19     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:112:3)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by stereotype441** [comment] 2017-10-19 13:56
@lukechurch I'm not sure what is causing this.  Is it possible to get repro steps?

**Comment by peter-ahe-google** [comment] 2017-10-19 14:05
Actually, I thought @askeksa-google fixed this already.

**Comment by peter-ahe-google** [comment] 2017-10-19 14:06
Now that I took a closer look, that is.

**Comment by lukechurch** [comment] 2017-10-20 02:14
@peter-ahe-google -- Do you mean that I need to update my local check out of the SDK to pickup @askeksa-google most recent fixes?

**Comment by lukechurch** [comment] 2017-10-20 02:15
@stereotype441 I'll email shortly

**Comment by lukechurch** [comment] 2017-10-20 03:39
@peter-ahe-google FWIW, I have just updated to HEAD of the SDK, and I still see this issue occurring, so I don't think it's fixed. PLMK if you need additional repro cases.

**Comment by stereotype441** [comment] 2017-10-20 10:16
This should fix it: https://dart-review.googlesource.com/c/sdk/+/15500

**Comment by peter-ahe-google** [comment] 2017-10-20 11:52
This CL is similar to Paul's solution, but preserves the recovery node on abstract methods: https://dart-review.googlesource.com/15540

**Comment by peter-ahe-google** [comment] 2017-10-20 12:08
@lukechurch, I didn't mean that you need to update your repo. I meant this wasn't a problem in Paul's type inference implementation, and potentially a duplicate of a know issue.

**Closed** 2017-10-24 11:04 UTC
Labels: area-front-end, front-end-fasta
