### ISSUE TITLE
Front end does not bounds check constructor generic arguments

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31472] opened 2017-11-28 21:49 UTC
Consider the following code:

```dart
class A<T extends int> {}
dynamic foo<T>() {
  return new A<T>(); // (1)
}
dynamic bar() {
  return new A<String>(); // (2)
}
```

A compile-time error should be reported at both (1) and (2) (in strong mode), because neither `T` nor `String` is a subtype of `int`.  The front end does not currently report the necessary errors.

**Comment by stereotype441** [comment] 2017-11-28 21:49
@sjindel-google FYI

**Comment by askeksa-google** [comment] 2018-08-14 08:53
Closing as duplicate of https://github.com/dart-lang/sdk/issues/33308

**Closed by askeksa-google** 2018-08-14 08:53 UTC
Labels: area-front-end, front-end-missing-error, p2-medium
