### ISSUE TITLE
Type inference for get methods

### ISSUE THREAD

**Issue by ogierm** [dart-lang/sdk#40227] opened 2020-01-18 16:50 UTC
using Dart 2.7.0

It's kind of bugging me that there is no type inference for `get` methods?
Atleast
```dart
get bla => _bla;
Duration _bla;
```
infers `bla` to be of the type `dynamic`.

**Comment by bwilkerson** [comment] 2020-01-18 16:54
The lint `recursive_getters` should catch such cases.

**Comment by ogierm** [comment] 2020-01-18 17:02
@bwilkerson oh, I didn't know about the linters

**Comment by mit-mit** [comment] 2020-01-20 08:44
Closing as by design

**Closed by mit-mit** 2020-01-20 08:44 UTC
