### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by xuexin** [dart-lang/sdk#35088] opened 2018-11-07 02:18 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900, 2560x1440  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/r_/_9bs4t6n7wd680stmrm0yk8m0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/block_widget/block_layout.dart context: exception_20181107_101730_249
Exception: Element not found in summary: package:flutter/src/widgets/basic.dart;package:flutter/src/widgets/basic.dart;Widget
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:983:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:929:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:954:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:28)
#8      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#9      ExecutableElementImpl.returnType (package:analyzer/src/dart/element/element.dart:4008:64)
#10     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/declaration_resolver.dart:364:54)
#11     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#13     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#14     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#15     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#16     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#17     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#21     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#22     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#23     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#24     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#25     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#26     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#27     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#28     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#29     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#30     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#31     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#32     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#33     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#34     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#37     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#38     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#39     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#40     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#46     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#47     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#48     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#49     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#50     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1541557046643 started analysis server:
  /Users/liaoyuhao/flutter/bin/cache/dart-sdk/bin/dart /Users/liaoyuhao/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-181.5540.7
1541557047176 <= {"event":"server.connected","params":{"version":"1.20.5","pid":22458,"sessionId":""}}
1541557047191 <= {"id":"0","result":{"version":"1.20.5"}}
1541557047191 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1541557046655}
1541557047191 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1541557047191 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/liaoyuhao/scratch_demo/scratch_flutter_test"],"excluded":["/Users/liaoyuhao/scratch_demo/scratch_flutter_t
1541557047191 => {"id":"4","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1541557047058}
1541557047191 <= {"id":"1"}
1541557047196 <= {"id":"2"}
1541557047288 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/pubspec.yaml","errors":[]}}
1541557047347 <= {"id":"3"}
1541557047351 <= {"id":"4","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1541557047352 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1541557049424 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/test/widget_test.dart","errors":[]}}
1541557049445 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/a_page.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/
1541557049447 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/bean/project.dart","errors":[]}}
1541557049459 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/large_child_scroll_view.dart","errors":[]}}
1541557049472 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/main.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/li
1541557049473 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/drag_playground.dart","errors":[]}}
1541557049480 <= {"event":"analysis.errors","params":{"file":"/Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/block_widget/block_wrapper.dart","errors":[{"severity":"INFO","type":"HINT","locati
1541557050461 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/block_widget/block_layout.dart context: exception_
```
```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/liaoyuhao/scratch_demo/scratch_flutter_test/lib/block_widget/block_layout.dart context: exception_20181107_101730_249
Exception: Element not found in summary: package:flutter/src/widgets/basic.dart

**Comment by stereotype441** [comment] 2018-11-07 16:19
Duplicate of #34555

**Closed by stereotype441** 2018-11-07 16:19 UTC
Labels: area-analyzer
