### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by rgavelino** [dart-lang/sdk#34949] opened 2018-10-27 05:19 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\rodri\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\Projetos Profissionais\FlutterProjects\AppRendaFixaFlutter\lib\ui\account\basic_profile.dart context: exception_20181026_165800_891
RangeError (index): Invalid value: Not in range 0..14, inclusive: 15
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#6      _ParameterElementImpl

**Comment by stereotype441** [comment] 2018-10-29 16:29
Duplicate of #34534

**Closed by stereotype441** 2018-10-29 16:29 UTC
Labels: area-analyzer
