### ISSUE TITLE
VM does back-to-back GCs

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#29415] opened 2017-04-21 09:37 UTC
The VM sometimes does two old-space GCs back to back. The second one is a waste of time and battery as no garbage is ever found.

Here's what I think is happening:

    Mutator thread                      Compiler thread
    Wants to do scavenge
         or full GC
    Waits for safepoint
                                                  Tries to do old-space alloc
                                                  No more space in old-space
                                                  Waits for sweeper threads - this is a safe point
    Does new-space-GC
    Exits safe-point
                                                  Wakes up, retries old-space alloc which still fails
    Decides to do oldspace GC
         because we have hit limit
                                                  Decides to do full GC, starting with newspace
    Starts old-space GC
    Waits for safe point
                                                   Wants to start newspace GC - this is a safe point
    Completes old-space GC
                                                   Does new-space GC
                                                   Does old-space GC

**Comment by ErikCorryGoogle** [comment] 2017-04-21 09:56
I can trigger this about half the time with:

/out/ReleaseX64/dart --verbose-gc --log-growth pkg/front_end/tool/_fasta/compile.dart pkg/compiler/bin/dart2js.dart

It doesn't happen for me in Debug mode due to timing issues.

**Comment by a-siva** [comment] 2017-04-27 01:41
Is there an interleaving in your comment that the issue tracker messed up? looks like you were trying to outline the sequence for the mutator thread and the compiler thread separately.

**Comment by ErikCorryGoogle** [comment] 2017-05-09 14:37
Sorry about that - fixed the formatting.

**Comment by liamappelbe** [comment] 2018-12-13 18:06
@ErikCorryGoogle is this still reproducible? I'm not seeing anything too suspicious in the logs from that command. I ran it a bunch and didn't see any back to back full GCs, and every GC seems to collect a reasonable amount.

**Comment by liamappelbe** [comment] 2018-12-13 22:16
Ok, it sounds like it's a non-issue now. So I'll close it until there are solid repro steps

**Comment by mraleph** [comment] 2018-12-13 22:56
It's a concurrency issue - so obviously reproducing it reliably is hard - but it does not mean that it can't happen. As I mentioned before the code did not get fixed - and it's pretty obvious that it can cause behavior that is described in the original comment by Erik. 

Here is the repro. Add the following test and then run it with 

```
$ out/ReleaseX64/run_vm_tests --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --verbose-gc --no-concurrent-mark --old-gen-heap-size=10 Bug29415Test
```

You will get the following output:

```
[                  |                      |     |       |      | new gen     | new gen     | new gen | old gen       | old gen       | old gen     | sweep | safe- | roots/| stbuf/| tospc/| weaks/|               ]
[ GC isolate       | space (reason)       | GC# | start | time | used (kB)   | capacity kB | external| used (kB)     | capacity (kB) | external kB | thread| point |marking| reset | sweep |swplrge| data          ]
[                  |                      |     |  (s)  | (ms) |before| after|before| after| b4 |aftr| before| after | before| after |before| after| (ms)  | (ms)  | (ms)  | (ms)  | (ms)  | (ms)  |               ]
[ isolate       {M},  MarkSweep(     full),  881,   2.60,   2.5,     0,     0,  2048,  2048,   0,   0,   6565,   1812,   6912,   6912,     0,     0,   0.00,   0.00,   2.49,   0.00,   0.02,   0.00, 100, 37, 0, 0, ]
[ isolate       {M},   Scavenge(     full),  882,   2.61,   1.6,     0,     0,  2048,  2048,   0,   0,   8573,   8573,   8960,   8960,     0,     0,   0.00,   0.01,   1.55,   0.01,   0.00,   0.00, 0, 0, 0, 0, ]
[ isolate       {M},  MarkSweep(     full),  883,   2.61,   2.1,     0,     0,  2048,  2048,   0,   0,   8573,   1812,   8960,   8960,     0,     0,   0.00,   0.00,   2.06,   0.00,   0.01,   0.00, 100, 30, 0, 0, ]
[ isolate       {M},   Scavenge(     full),  884,   2.62,   1.6,     0,     0,  2048,  2048,   0,   0,  10079,  10079,  10496,  10496,     0,     0,   0.00,   0.01,   1.56,   0.01,   0.00,   0.00, 0, 0, 0, 0, ]
[ isolate       {M},  MarkSweep(     full),  885,   2.62,   2.1,     0,     0,  2048,  2048,   0,   0,  10079,   1812,  10496,  10496,     0,     0,   0.00,   0.00,   2.10,   0.00,   0.01,   0.00, 100, 25, 0, 0, ]
[ isolate       {M},   Scavenge(     full),  886,   2.63,   1.6,     0,     0,  2048,  2048,   0,   0,  10079,  10079,  10496,  10496,     0,     0,   0.00,   0.01,   1.53,   0.01,   0.00,   0.00, 0, 0, 0, 0, ]
[ isolate       {M},  MarkSweep(     full),  887,   2.63,   2.1,     0,     0,  2048,  2048,   0,   0,  10079,   1812,  10496,  10496,     0,     0,   0.00,   0.00,   2.04,   0.00,   0.01,   0.00, 100, 22, 0, 0, ]
[ isolate       {H},   Scavenge(     full),  888,   2.63,   1.6,     0,     0,  2048,  2048,   0,   0,   1812,   1812,  10496,  10496,     0,     0,   0.00,   0.00,   1.51,   0.01,   0.00,   0.01, 0, 0, 0, 0, ]
[ isolate       {H},  MarkSweep(     full),  889,   2.64,   5.5,     0,     0,  2048,  2048,   0,   0,   1812,   1812,  10496,  10240,     0,     0,   0.65,   3.16,   1.64,   0.00,   0.02,   0.00, 100, 21, 0, 0, ]
[ isolate       {M},   Scavenge(     full),  890,   2.64,   1.8,     0,     0,  2048,  2048,   0,   0,   9828,   9828,  10240,  10240,     0,     0,   0.00,   0.01,   1.70,   0.01,   0.00,   0.00, 0, 0, 0, 0, ]
[ isolate       {M},  MarkSweep(     full),  891,   2.65,   1.6,     0,     0,  2048,  2048,   0,   0,   9828,   1812,  10240,  10240,     0,     0,   0.00,   0.00,   1.59,   0.00,   0.02,   0.00, 100, 19, 0, 0, ]
[ isolate       {H},  MarkSweep(     full),  892,   2.65,   3.1,     0,     0,  2048,  2048,   0,   0,   1812,   1812,  10240,   2816,     0,     0,   1.00,   0.00,   2.06,   0.00,   0.02,   0.00, 100, 26, 0, 0, ]
[ isolate       {M},   Scavenge(     full),  893,   2.65,   1.6,     0,     0,  2048,  2048,   0,   0,   4557,   4557,   4864,   4864,     0,     0,   0.00,   0.01,   1.52,   0.01,   0.00,   0.00, 0, 0, 0, 0, ]
[ isolate       {M},  MarkSweep(     full),  894,   2.65,   1.6,     0,     0,  2048,  2048,   0,   0,   4557,   1812,   4864,   4864,     0,     0,   0.00,   0.00,   1.54,   0.00,   0.02,   0.01, 100, 30, 0, 0, ]
[ isolate       {M},   Scavenge(     full),  895,   2.66,   1.9,     0,     0,  2048,  2048,   0,   0,   6565,   6565,   6912,   6912,     0,     0,   0.00,   0.00,   1.86,   0.01,   0.00,   0.00, 0, 0, 0, 0, ]
[ isolate       {M},  MarkSweep(     full),  896,   2.66,   2.6,     0,     0,  2048,  2048,   0,   0,   6565,   1812,   6912,   6912,     0,     0,   0.00,   0.00,   2.52,   0.00,   0.03,   0.00, 100, 40, 0, 0, ]
```

in this output GCs number 886 to 889 are the GCs described in this issue. 

You can see that MarkSweep GC number 889 is pathological: old space used size is 1812 while capacity is 10496 - so GC should not actually happen. However it happens for the reasons described in the issue. 

```diff
diff --git a/runtime/vm/heap/heap.cc b/runtime/vm/heap/heap.cc
index ecfcceeee2..20aec3928d 100644
--- a/runtime/vm/heap/heap.cc
+++ b/runtime/vm/heap/heap.cc
@@ -852,15 +852,15 @@ void Heap::PrintStats() {
   if ((FLAG_verbose_gc_hdr != 0) &&
       (((stats_.num_ - 1) % FLAG_verbose_gc_hdr) == 0)) {
     OS::PrintErr(
-        "[              |                      |     |       |      "
+        "[                  |                      |     |       |      "
         "| new gen     | new gen     | new gen "
         "| old gen       | old gen       | old gen     "
         "| sweep | safe- | roots/| stbuf/| tospc/| weaks/|               ]\n"
-        "[ GC isolate   | space (reason)       | GC# | start | time "
+        "[ GC isolate       | space (reason)       | GC# | start | time "
         "| used (kB)   | capacity kB | external"
         "| used (kB)     | capacity (kB) | external kB "
         "| thread| point |marking| reset | sweep |swplrge| data          ]\n"
-        "[              |                      |     |  (s)  | (ms) "
+        "[                  |                      |     |  (s)  | (ms) "
         "|before| after|before| after| b4 |aftr"
         "| before| after | before| after |before| after"
         "| (ms)  | (ms)  | (ms)  | (ms)  | (ms)  | (ms)  |               ]\n");
@@ -868,7 +868,7 @@ void Heap::PrintStats() {
 
   // clang-format off
   OS::PrintErr(
-    "[ %-13.13s, %10s(%9s), "  // GC(isolate), type(reason)
+    "[ %-13.13s {%s}, %10s(%9s), "  // GC(isolate), type(reason)
     "%4" Pd ", "  // count
     "%6.2f, "  // start time
     "%5.1f, "  // total time
@@ -882,6 +882,7 @@ void Heap::PrintStats() {
     "%" Pd ", %" Pd ", %" Pd ", %" Pd ", "  // data
     "]\n",  // End with a comma to make it easier to import in spreadsheets.
     isolate()->name(),
+    Thread::Current()->IsMutatorThread() ? "M" : "H",
     GCTypeToString(stats_.type_),
     GCReasonToString(stats_.reason_),
     stats_.num_,
diff --git a/runtime/vm/thread_test.cc b/runtime/vm/thread_test.cc
index 48df45915b..b9eb0d0d5a 100644
--- a/runtime/vm/thread_test.cc
+++ b/runtime/vm/thread_test.cc
@@ -388,6 +388,80 @@ TEST_CASE(ThreadRegistry) {
   EXPECT_STREQ("foo", orig_str);
 }
 
+// A helper thread that repeatedly reads ICData
+class Bug29415TestTask : public ThreadPool::Task {
+ public:
+  static const intptr_t kTaskCount;
+
+ Bug29415TestTask(Isolate* isolate,
+                 Monitor* monitor,
+                 intptr_t* exited,
+                 bool* done)
+      : isolate_(isolate),
+        monitor_(monitor),
+        exited_(exited),
+        done_(done) {}
+
+  virtual void Run() {
+    Thread::EnterIsolateAsHelper(isolate_, Thread::kUnknownTask);
+
+    Thread* thread = Thread::Current();
+
+    {
+      StackZone stack_zone(thread);
+      HANDLESCOPE(thread);
+
+      Array& arr = Array::Handle();
+      while (true) {
+        arr = Array::New(1000, Heap::kOld);
+
+        if (AtomicOperations::LoadAcquire(done_)) {
+          break;
+        }
+
+        //TransitionVMToBlocked blocked(thread);
+      }
+    }
+
+    Thread::ExitIsolateAsHelper();
+    {
+      MonitorLocker ml(monitor_);
+      ++*exited_;
+      ml.Notify();
+    }
+  }
+
+ private:
+  Isolate* isolate_;
+  Monitor* monitor_;
+  intptr_t* exited_;  // # tasks that are no longer running.
+  bool* done_;        // Signal that helper threads can stop working.
+};
+
+const intptr_t Bug29415TestTask::kTaskCount = 1;
+
+// Test that checks that other threads only see a fully initialized ICData
+// whenever ICData is updated.
+ISOLATE_UNIT_TEST_CASE(Bug29415Test) {
+  Isolate* isolate = thread->isolate();
+  USE(isolate);
+  Monitor monitor;
+  intptr_t exited = 0;
+  bool done = false;
+
+  for (int i = 0; i < Bug29415TestTask::kTaskCount; i++) {
+    Dart::thread_pool()->Run(
+        new Bug29415TestTask(isolate, &monitor, &exited, &done));
+  }
+
+  Array& array = Array::Handle();
+
+  while (true) {
+    array = Array::New(1000, Heap::kOld);
+  }
+}
+
+
 // A helper thread that repeatedly reads ICData
 class ICDataTestTask : public ThreadPool::Task {
  public:
```

**Comment by liamappelbe** [comment] 2018-12-13 23:02
Ok, I'll look into it. Thanks for the repro steps.

**Comment by mraleph** [comment] 2018-12-14 13:38
FWIW I am not sure this is a very high priority issue - it would be great to fix it, but it might not make any noticeable difference on anything. 

I suggest discussing with @rmacnak-google to get his feeling about it.

**Comment by rmacnak-google** [comment] 2023-01-18 21:45
I think this was partially fixed when locks were added around, i.e., invoking minor gc and holding the lock through deciding whether promotion warranted a follow-up major gc. But fully avoiding duplicated GCs probably requires something like a last allocation attempt under that lock. In practice, this appears to be a rare occurrence.

**Closed** 2023-05-10 23:39 UTC
Labels: area-vm, P4, vm-gc
