### ISSUE TITLE
Incorrect type inference int is unnecessarily and incorrectly inferred Object

### ISSUE THREAD

**Issue by gothamgasworks** [dart-lang/sdk#39361] opened 2019-11-13 08:58 UTC
The code is:

```dart
void main() {
  List<int> ints = [1, 2, 3];
  print(ints.fold(0, (int a, int b) => a + b));
}
```

Expected result:
```6```

Actual result:
```
test.dart:3:22: Error: The argument type 'int Function(int, int)' can't be assigned to the parameter type 'Object Function(Object, int)'.
 - 'Object' is from 'dart:core'.
  print(ints.fold(0, (int a, int b) => a + b));
```

This is the result I get on both of these versions:

* Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "macos_x64"
* Dart VM version: 2.7.0-dev.0.0 (Tue Nov 5 12:57:33 2019 +0100) on "macos_x64"

**Comment by gothamgasworks** [comment] 2019-11-13 09:25
As for the web, I've only tried on DartPad (2.6.0), same result. And it's not just `int`s, and it's a bit different when I don't define the types for the function:
```dart
void main() {
  List<String> strs = ["a", "b", "c"];
  print(strs.fold("", (a, b) => a + b));
}
```

Output on DartPad (2.6.0):
```
error
The operator '+' isn't defined for the class 'Object'.
```

Dart VM (2.6.0):
```
test.dart:3:35: Error: The method '+' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named '+'.
  print(strs.fold("", (a, b) => a + b));
```

Btw. the workaround is easy, just add the type parameters:
```dart
void main() {
  List<String> strs = ["a", "b", "c"];
  print(strs.fold<String>("", (a, b) => a + b));
}
```

**Comment by eernstg** [comment] 2019-11-13 09:49
First, note that issue #25490 is concerned with the ability to transfer information from one actual argument to another one during type inference. Dart type inference doesn't do that (at least not yet), and this tends to make inference difficult for functions like `fold`. As you mention, the workaround is to pass suitable type arguments explicitly.

However, the other force that influences inference in this situation is the context type. You just need to adjust the code slightly to get the desired typing:

```dart
void main() {
  List<int> ints = [1, 2, 3];
  var i = ints.fold(0, (int a, int b) => a + b);
  print(i);
}
```

The point is that `var i` provides an unknown context type for the invocation of `fold`, and this allows the actual arguments to determine the outcome (`int`). In contrast, when the result from `fold` is passed to `print` the context type is `Object`. This matters because Dart inference gives priority to the type expected by the context. For example, with `List<num> xs = [1];` the list literal should yield a `List<num>` even though local inference on `[1]` could make it a `List<int>`.

**Comment by eernstg** [comment] 2019-11-13 10:09
The core of this issue is covered by #25490, and the fact that context types are given a high priority during inference is a deliberate choice for Dart, so I'll close this issue with 'working as intended'.

**Closed by eernstg** 2019-11-13 10:09 UTC
Labels: closed-as-intended

**Comment by gothamgasworks** [comment] 2019-11-13 10:12
My problem was that it used to work and now it doesn't. And it looks kind of dangerous to me, because it can lead to runtime errors in some cases.

I'll take a look at #25490.

**Comment by eernstg** [comment] 2019-11-13 10:16
> it used to work and now it doesn't

That is surprising. Do you have more data on when this change occurred?

**Comment by gothamgasworks** [comment] 2019-11-13 10:22
Hang on, I have to figure out what's going on. Our regressions started to fail (during analysis) when we switched over to 2.6.0, but now that I try with older versions it still fails the same way.

I think I have oversimplified the example.

**Comment by gothamgasworks** [comment] 2019-11-13 10:28
Got it, shall I rewrite this issue, or open a new one?

```dart
void main() {
  List<int> ints = [1, 2, 3];
  int sum = 0;
  sum += ints.fold(0, (int a, int b) => a + b);
  print(sum);
}
```

Actual output on 2.5.0:
```
6
```

Actual output on 2.6.0 (and 2.7.0-dev.0.0):
```
test.dart:4:23: Error: The argument type 'int Function(int, int)' can't be assigned to the parameter type 'num Function(num, int)'.
  sum += ints.fold(0, (int a, int b) => a + b);
                      ^
```

**Comment by eernstg** [comment] 2019-11-13 10:32
I think it would be good for readability to create a new issue, such that nobody needs to discover that the current topic is described a couple of pages below the top entry.

**Comment by gothamgasworks** [comment] 2019-11-13 10:52
Created #39363
