### ISSUE TITLE
Bulk fix for `diagnostic_describe_all_properties` needs to coalesce properties in the same class

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#47418] opened 2021-10-08 22:18 UTC
I'm astounded that `diagnostic_describe_all_properties` has a bulk fix, that's amazing. Truly, I was not expecting that.

That said, I would like to request two improvements to that bulk fix:

1. When it adds the `debugFillProperties` function, it would be great if it could add it with a blank line before it, separating it from the previous method.
2. More importantly, when there are multiple fields in a class that need it adding all at once, the methods need to be coalesced rather than adding a new method for each property.

cc @a14n @jacob314

**Comment by mbfakourii** [comment] 2023-09-23 17:03
@pq 

By running the quick fix, the codes are as follows
```dart
  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty<bool>('select', select));
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty<Part?>('name', name));
  }

```
If it should be like below
```dart
  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(DiagnosticsProperty<bool>('select', select));
    properties.add(DiagnosticsProperty<Part?>('name', name));
  }

```

**Comment by keertip** [comment] 2024-06-27 20:47
Duplicate of #55772

**Closed by keertip** 2024-06-27 20:47 UTC
Labels: area-analyzer, P2, type-bug, analyzer-bulk-fix
