### ISSUE TITLE
Destructuring of records doesn't work in lambda parameters

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#54182] opened 2023-11-29 11:19 UTC
This works:

```dart
List<(int, int)> vals = [];
for (var (a, b) in vals) {
  print(a+b);
}
```

but this fails with error `The argument type 'InvalidType Function(dynamic Function(int, int))' can't be assigned to the parameter type 'dynamic Function((int, int))'`:

```dart
List<(int, int)> vals = [];
final sums = vals.map(((int a, int b)) => a + b).toList();  // Error
```

I assumed destructuring should work in lambda parameters.

Actually it doesn't work even in function definitions -- this fails with a very strange syntax error, `Use the generic function type syntax to declare the parameter ''. Try using the generic function type syntax.`

```dart
void sum((int a, int b)) => a + b;  // Error
```

The following works (by not using destructuring at all). You can't use `v.a` or `v.b`, since the field names are ignored in the type:

```dart
void sum((int a, int b) v) => v.$1 + v.$2;
```

**Comment by mraleph** [comment] 2023-11-29 11:20
Duplicate of https://github.com/dart-lang/language/issues/3001

(On which you have already commented few weeks ago by the way. So no need to file new issues).

**Closed by mraleph** 2023-11-29 11:20 UTC

**Comment by lukehutch** [comment] 2023-11-29 11:22
Face-palm :-D  Thanks for pointing that out, I totally forgot that I found that issue. I went looking for it again, and didn't find it this time...

Before I go file another dup, is there an issue for allowing `v.a` and `v.b` to be used instead of `v.$1` and `v.$2`, in the last example I gave?

**Comment by mraleph** [comment] 2023-11-29 11:34
> is there an issue for allowing `v.a` and `v.b` to be used instead of `v.$1` and `v.$2`, in the last example I gave?

I don't think so. Please file it at dart-lang/language repo (that's the place for all language feature requests).

The choice of names not having any meaning was deliberate, but I don't see any reason why it would not work to just allow this in a statically typed context (i.e. ignoring dynamic invocations entirely).
