### ISSUE TITLE
dart2js throws an error for List.$index with records

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#52933] opened 2023-07-14 02:47 UTC
I haven't found an obvious minimal reproduction for this, unfortunately. If any dart2js folks can point me towards likely culprits that may help me narrow it down. But here's the reproduction:

1. [Install Node.js](https://nodejs.org/en)
2. [Install the Buf CLI](https://buf.build/docs/installation/)
3.  ```shellsession
    $ git clone git://github.com/sass/dart-sass -b dart3
    $ cd dart-sass
    $ dart pub get
    $ dart run grinder protobuf pkg-npm-dev
    $ echo '@use "sass:math"; @debug math.sqrt(10)' > test.scss
    $ node build/npm/sass.js --trace test.scss
    Error: NoSuchMethodError: method not found: '$index' (type$.List_Value._as(...).$index is not a function)
      ╷
    1 │ @use "sass:math"; @debug math.sqrt(10)
      │                          ^^^^^^^^^^^^^
      ╵
      test.scss 1:26  root stylesheet
    
    build/npm/sass.dart.js 50207:53  _sqrt_closure.call$1
    build/npm/sass.dart.js 73151:35  _EvaluateVisitor__runBuiltInCallable_closure0.call$0
    build/npm/sass.dart.js 71669:23  _EvaluateVisitor._addExceptionSpan$1$3$addStackFrame
    build/npm/sass.dart.js 71683:19  _EvaluateVisitor._addExceptionSpan$1$2
    build/npm/sass.dart.js 71094:24  _EvaluateVisitor._runBuiltInCallable$3
    build/npm/sass.dart.js 71016:44  _EvaluateVisitor._runFunctionCallable$3
    build/npm/sass.dart.js 73030:25  _EvaluateVisitor_visitFunctionExpression_closure0.call$0
    build/npm/sass.dart.js 71709:23  _EvaluateVisitor._addErrorSpan$1$2
    build/npm/sass.dart.js 70979:22  _EvaluateVisitor.visitFunctionExpression$1
    build/npm/sass.dart.js 41372:62  FunctionExpression.accept$1$1
    ```

This is definitely a dart2js-specific issue. It doesn't reproduce with the VM. I thought the culprit might be changing the return type of `_EvaluateVisitor._evaluateArguments()` to return a record instead of an object, but changing it back didn't fix the issue so now I'm stumped. Nevertheless, it was _definitely_ triggered by our migration to Dart 3 functionality.

Tested on Dart 3.0.6.

**Comment by fishythefish** [comment] 2023-07-20 18:33
This appears to have the same root cause as https://github.com/dart-lang/sdk/issues/52968. The issue no longer reproduces with that fix landed. We have a cherry pick request open; I'll amend it to note that it fixes this issue as well.

**Closed by fishythefish** 2023-07-20 18:33 UTC
Labels: web-dart2js, area-web

**Comment by nex3** [comment] 2023-07-20 20:03
Is there a way we can work around this in the short term?

**Comment by sigmundch** [comment] 2023-07-20 20:14
My guess is that this only affects uses of tuples where one of the entries in the tuple is a closure. So I believe the workaround would be to reverting to use the Tuple class in BuiltInCallable here https://github.com/sass/dart-sass/compare/main...dart3#diff-9c29d49f44f4a56fa0b07d87dcdbb2db96ffcaf666960b4eca28e8f2085e4b07R18 and other places where the tuple takes a callback.

**Comment by nex3** [comment] 2023-07-20 20:16
I see, thanks for the tip!

**Comment by sigmundch** [comment] 2023-07-20 20:17
BTW, the cherry-pick for the fix was approved, so it will be in the next patch release of Dart 3 stable.

**Comment by fishythefish** [comment] 2023-07-20 20:29
Yeah, I think using a user-defined `Tuple` class instead of a record when it contains a closure is the best fix.

I wouldn't recommend it, but one other workaround is mentioned in https://github.com/dart-lang/sdk/issues/52968. Basically, type inference doesn't "see" function calls when the function is reached through a record. However, if the function is also invoked directly*, the parameter types will be inferred. The tricky thing is that the inferred parameter types are only based on the direct calls, so those need to cover the same range of possibilities as the calls through the record.

\* This can be on a code path that isn't actually reachable, although if it's too obviously unreachable, dart2js might optimize it away early.
