### ISSUE TITLE
Sort Analyzer autocomplete suggestions by applicable types

### ISSUE THREAD

**Issue by alechenninger** [dart-lang/sdk#23937] opened 2015-07-31 18:49 UTC
The first results should be types which are most relevant to the current assignment.

For example, if I'm passing an argument which annotated with type `Foo` to a function, and I type `new ` and ask for suggestions from the analyzer, I should first see suggestions for constructors of types which will implement `Foo`.

Originally filed as https://github.com/dart-atom/dartlang/issues/143

**Comment by jwren** [comment] 2016-04-28 21:19
Duplicate of https://github.com/dart-lang/sdk/issues/26254 which is now fixed.

**Closed by jwren** 2016-04-28 21:19 UTC
Labels: analyzer-completion, area-analyzer, P2 medium, Type: enhancement
