### ISSUE TITLE
Dart / Flutter thrown exception location opens in read-only ("Preview") mode in IntelliJ

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#57025] opened 2024-11-05 08:58 UTC
Note: The following issue was first [filed](https://youtrack.jetbrains.com/issue/WEB-68867) in IntelliJ's YouTrack bug tracker, but there it was rejected with "[Flutter](https://plugins.jetbrains.com/plugin/9212-flutter) is a third-party plugin maintained by Google, please try reporting the issue to the plugin vendor." I then filed the bug over at https://github.com/flutter/flutter-intellij/issues/7646 but since realized the bug is probably not specific to Flutter. Also, that bug was not touched since it was filed on September 11 and the tracker seems half-abandoned.

If you think I'm just filing a duplicate, feel free to close it as such, and I'm sorry for wasting your time. But I was seeing a bunch of [`label:area-intellij`](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-intellij) issues on this repo issue tracker so I thought maybe it belongs here. The original issue follows, and I'm happy to elaborate.

## Steps to Reproduce

1. Install the Flutter IntelliJ plugin
2. Create a new Flutter project
3. Introduce a thrown exception (e.g. put `throw "test";` anywhere inside the `_incrementCounter()` method)
4. Run the app on any target (e.g. macOS)
5. Hit the exception (e.g. press the `+` button)

### Expected

The code location (e.g. `lib/main.dart`) is opened in the editor.

### Actual

The location is open, BUT it's open in Preview mode (filename in italics).

![Screenshot 2024-08-19 at 10 18 49-1](https://github.com/user-attachments/assets/83aacbd0-dee1-4bb7-997e-ca22ae7dccf9)

This means code analysis doesn't work in the file:

![Screenshot 2024-08-19 at 10 21 17-1](https://github.com/user-attachments/assets/e4fc1152-5fea-4576-b70f-c7e0e9635f11)

(Note the "No usages found" callout, although the method is clearly used in the code.)

Therefore, there's no "Go to definition", which is incredibly frustrating. There's also no syntax highlighting beyond the basics.

And when one wants to change the file where the problem happened (a common occurrence), the IDE refuses with "Failed to make ___ writable":

![Screenshot 2024-08-19 at 10 24 00-1](https://github.com/user-attachments/assets/35be5a51-6260-4055-90c9-129e187c3c3d)

The one workaround is to find the same file in the Project toolbar and open it, then find the same location manually.

It looks as though the file that the IDE opens on exception is some temp/memory copy of the real file, and the linkage to the original file is lost on the IDE. I hypothesize that this might be an analyzer issue?

## Version info

```
flutter doctor --verbose
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/filiph/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (7 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Users/filiph/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 78.4.2
    • Dart plugin version 233.15271

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0
```

**Comment by devoncarew** [comment] 2024-11-06 18:05
Thanks for the report @filiph!

From reading this, the problem is likely that the debugger in the Flutter plugin has some trouble resolving the uri in the exception's stack trace back to the correct file in the project (this seems like the actual bug - the debugger's resolution logic). The debugger then opens a temp file with just the source downloaded from the vm, in order to have something to display at that location.

The resolution for this _is_ likely in the flutter/flutter-intellij repo. I'm hesitant to close this however as it sounds like this is the 3rd time you've filed this bug; cc @jwren for advice.

**Comment by jwren** [comment] 2024-11-06 18:18
Thanks @filiph!  Yes, this is definitely the issue.  Unfortunately, with other issues this will not be fixed in the short short term, but I do appreciate you filing and escalating.

**Comment by jwren** [comment] 2024-11-15 19:23
Please attach a PR or an issue replacing it in a different repo.

**Comment by devoncarew** [comment] 2024-11-15 20:17
Jaime, see the issue at https://github.com/flutter/flutter-intellij/issues/7646 - I think that's a better place to track this.

**Closed** 2024-11-15 20:20 UTC
Labels: type-bug, area-intellij, triage-automation
