### ISSUE TITLE
Type inference not working for metadata

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#34998] opened 2018-10-31 12:00 UTC
Type inference is not inferring type arguments for generic metadata in the Analyzer:

```dart
class Box<T> {
  final T value;
  const Box(this.value);
}

@Box("rain")
class Hukairs {}

main() {}
```
Compiles fine with the CFE but Analyzer reports:
```
  error • The argument type 'String' can't be assigned to the parameter type 'T' at generic-metadata.dart:6:6 • argument_type_not_assignable```
```
This is especially painful because the language doesn't let you write the type arguments there.

**Comment by stereotype441** [comment] 2018-10-31 16:29
Duplicate of #34367

**Closed by stereotype441** 2018-10-31 16:29 UTC
Labels: area-analyzer
