### ISSUE TITLE
Moving some files to another directory does not work.

### ISSUE THREAD

**Issue by jffiorillo** [dart-lang/sdk#38234] opened 2019-09-06 10:34 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6262.58`
- `2.6.0-edge.be661765345f62fa4212b76f897fdd3e66e8aa54`
- `IU-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.be661765345f62fa4212b76f897fdd3e66e8aa54, server version 1.27.3, error: Invalid argument(s): Is a part: package:dart_countries_states/src/models/serializers.g.dart
#0      AnalysisDriver.getResolvedLibraryByUri (package:analyzer/src/dart/analysis/driver.dart:749:7)
#1      AnalysisSessionImpl.getResolvedLibraryByElement (package:analyzer/src/dart/analysis/session.dart:151:20)
#2      MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:86:12)
<asynchronous suspension>
#3      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _runZoned (dart:async/zone.dart:1516:10)
#7      runZoned (dart:async/zone.dart:1500:12)
#8      _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#9      EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#10     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1500:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#19     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#22     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#54     _StreamController._add (dart:async/stream_controller.dart:640:7)
#55     _StreamController.add (dart:async/stream_controller.dart:586:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#57     _rootRunUnary (dart:async/zone.dart:1136:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#60     _BufferingStr...
```

For additional log information, please append the contents of
file:///private/var/folders/50/mwmvrrdj27s89thbfm_v19wr0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-06 15:51
Thanks for reporting this issue! This has been previously been reported in #36566; follow along there.

**Comment by srawlins** [comment] 2019-09-06 15:51
Duplicate of #36566

**Closed by srawlins** 2019-09-06 15:51 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
