### ISSUE TITLE
FileSystemException in _WindowsDirectoryWatcher when running analysis server

### ISSUE THREAD

**Issue by akash1223** [dart-lang/sdk#34523] opened 2018-09-20 14:14 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\m3\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [E:\Flutter Project\footware], excluded: [E:\Flutter Project\footware\.idea, E:\Flutter Project\footware\.dart_tool, E:\Flutter Project\footware\.pub, E:\Flutter Project\footware\build]}, clientRequestTime: 1537418691795}
FileSystemException: Exists failed, path = 'E:\Flutter Project\footware\build\app\intermediates\transforms\dexBuilder\debug\30\footwear\appcreater\com' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-23 03:50
Duplicate of #34294

**Closed by stereotype441** 2018-10-23 03:50 UTC
Labels: analyzer-server, area-analyzer, type-bug
