### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#36203] opened 2019-03-13 23:00 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 191.6014.17`
- `2.2.0`
- `WS-191.6014.17, JRE 1.8.0_202-release-1483-b31x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 2560x1440, 1200x1920`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [/Users/rayk/critprojects/repo], excluded: [/Users/rayk/critprojects/repo/.idea, /Users/rayk/critprojects/repo/.gtm, /Users/rayk/critprojects/repo/.idea, /Users/rayk/critprojects/repo/.tmp, /Users/rayk/critprojects/repo/app/.dart_tool, /Users/rayk/critprojects/repo/app/.pub, /Users/rayk/critprojects/repo/app/build, /Users/rayk/critprojects/repo/calcs/.dart_tool, /Users/rayk/critprojects/repo/calcs/.pub, /Users/rayk/critprojects/repo/calcs/build, /Users/rayk/critprojects/repo/chanworker/.dart_tool, /Users/rayk/critprojects/repo/chanworker/.pub, /Users/rayk/critprojects/repo/chanworker/build, /Users/rayk/critprojects/repo/drapht/.dart_tool, /Users/rayk/critprojects/repo/drapht/.pub, /Users/rayk/critprojects/repo/drapht/build, /Users/rayk/critprojects/repo/drapht/example/.dart_tool, /Users/rayk/critprojects/repo/drapht/example/.pub, /Users/rayk/critprojects/repo/drapht/example/build, /Users/rayk/critprojects/repo/drapht/out/.dart_tool, /Users/rayk/critprojects/repo/drapht/out/.pub, /Users/rayk/critprojects/repo/drapht/out/build, /Users/rayk/critprojects/repo/drapht/out/packages, /Users/rayk/critprojects/repo/drapht/out/test/packages, /Users/rayk/critprojects/repo/drapht/out/tool/packages, /Users/rayk/critprojects/repo/example/.dart_tool, /Users/rayk/critprojects/repo/example/.pub, /Users/rayk/critprojects/repo/example/build, /Users/rayk/critprojects/repo/fetch/.pub, /Users/rayk/critprojects/repo/fetch/build, /Users/rayk/critprojects/repo/fetcher/.dart_tool, /Users/rayk/critprojects/repo/fetcher/.pub, /Users/rayk/critprojects/repo/fetcher/build, /Users/rayk/critprojects/repo/formfunc/.dart_tool, /Users/rayk/critprojects/repo/formfunc/.pub, /Users/rayk/critprojects/repo/formfunc/build, /Users/rayk/critprojects/repo/herder/.dart_tool, /Users/rayk/critprojects/repo/herder/.pub, /Users/rayk/critprojects/repo/herder/build, /Users/rayk/critprojects/repo/instro/.dart_tool, /Users/rayk/critprojects/repo/instro/.pub, /Users/rayk/critprojects/repo/instro/build, /Users/rayk/critprojects/repo/knocon/.dart_tool, /Users/rayk/critprojects/repo/knocon/.pub, /Users/rayk/critprojects/repo/knocon/build, /Users/rayk/critprojects/repo/lokistore/.dart_tool, /Users/rayk/critprojects/repo/lokistore/.pub, /Users/rayk/critprojects/repo/lokistore/build, /Users/rayk/critprojects/repo/model/.pub, /Users/rayk/critprojects/repo/model/build, /Users/rayk/critprojects/repo/sim/.dart_tool, /Users/rayk/critprojects/repo/sim/.pub, /Users/rayk/critprojects/repo/sim/build, /Users/rayk/critprojects/repo/simulate/.dart_tool, /Users/rayk/critprojects/repo/simulate/.pub, /Users/rayk/critprojects/repo/simulate/build, /Users/rayk/critprojects/repo/sled/.dart_tool, /Users/rayk/critprojects/repo/sled/.pub, /Users/rayk/critprojects/repo/sled/build, /Users/rayk/critprojects/repo/sled/example/.dart_tool, /Users/rayk/critprojects/repo/sled/example/.pub, /Users/rayk/critprojects/repo/sled/example/build, /Users/rayk/critprojects/repo/temp, /Users/rayk/critprojects/repo/tmp]}, clientRequestTime: 1552514560166}
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _DartNavigationComputerVisitor._addUriDirectiveRegion (package:analysis_server/src/domains/analysis/navigation_dart.dart:361:47)
#2      _DartNavigationComputerVisitor.visitPartDirective (package:analysis_server/src/domains/analysis/navigation_dart.dart:232:5)
#3      PartDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:9453:49)
#4      _DartNavigationComputerVisitor.visitCompilationUnit (package:analysis_server/src/domains/analysis/navigation_dart.dart:149:12)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439:49)
#6      computeDartNavigation (package:analysis_server/src/domains/analysis/navigation_dart.dart:28:10)
#7      ServerContextManagerCallbacks._computeNavigationParams (package:analysis_server/src/analysis_server.dart:1034:5)
#8      ServerContextManagerCallbacks.addAnalysisDriver.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:843:19)
#9      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#10     _rootRun (dart:async/zone.dart:1120:38)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/k3/rpf30xp576gd3b7wdpvvyg2r0000gn/T/report7.txt.

**Comment by kevmoo** [comment] 2019-04-09 03:42
Duplicate of #36182

**Closed by kevmoo** 2019-04-09 03:42 UTC
Labels: area-analyzer
