### ISSUE TITLE
Can't use const constructors with mixins

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29396] opened 2017-04-19 23:03 UTC
Consider this code:
```dart
class Superclass {
  const Superclass(this.foo);
  final int foo;
}

abstract class Mixin {
  factory Mixin.fixed(int baz) = _FixedMixin;
}

class _FixedMixin extends Object with Mixin {
  _FixedMixin(this.baz);
  final int baz;
}

class Subclass extends Superclass with Mixin {
  Subclass(int foo, this.bar) : super(foo);
  final int bar;
}
```

I want the `Mixin.fixed` and `Subclass` constructors to be const, but today that isn't possible. It's not clear why.

**Comment by eernstg** [comment] 2017-04-21 08:54
The main reason why these constructors cannot be const is that certain constructors are omitted when mixin application occurs. For example:

In order for `_FixedMixin(this.baz);` to be a correct constructor, it must include a superinitializer (that is, a clause that causes a constructor in the superclass to be invoked during instance creation). In your example that superinitializer is implicit because there is no explicit superinitializer, but it corresponds to having `_FixedMixin(this.baz): super();`.

The superclass of `_FixedMixin` is `Object with Mixin`, i.e., it is a class which is introduced by mixin application rather than a class which is introduced by a regular class definition. Such a class is implicitly equipped with some constructors (spec section 'Mixin Application'):

```LaTeX
For each generative constructor named $q_i(T_{i1}$ $ a_{i1}, \ldots , T_{ik_i}$ $ a_{ik_i}),
i \in 1..n$ of $S$ that is accessible to $L_M$, $C$ has an implicitly declared 
constructor named $q'_i = [C/S]q_i$ of the form

  $q'_i(a_{i1}, \ldots , a_{ik_i}):\SUPER(a_{i1}, \ldots , a_{ik_i});$.
```
Decrypting the LaTeX and considering the same example, what we get is `_owm(): super()`, where `_owm` is the actual (generated) name for the class that I previously called `Object with Mixin`.

There is a problem here: The implicitly declared constructor is non-const, even in the case where its superinitializer invokes a const constructor (in which case the implicitly generated constructor could itself also have been const).

So, unfortunately, there is no way to obtain a complete chain of const constructors up to `Object` when some (direct or indirect) superclass is created by mixin application.

This is a known problem, and the overly simple implicit generation of constructors creates some other problems as well (see #9745, #15101). The problem has been known for a long time, and it hasn't had enough urgency to be fixed so far (and the fix isn't necessarily trivial), but it is certainly on the agenda at this point and this issue helps pushing it upwards.

I'll close this issue as a duplicate of #9745, and refer to this issue from there.

**Closed by eernstg** 2017-04-21 08:54 UTC
Labels: area-language

**Comment by eernstg** [comment] 2018-04-09 12:04
You're looking for #32223, which is a request for implementation of this feature (this is `area-language`). You might say that we should have had a meta-bug for keeping track of these connections, but that didn't happen because the original request is so old.

**Comment by lrhn** [comment] 2018-04-09 12:16
The current specification for Dart 2 says that a mixin application of a mixin derived from a class with no field declarations, on top of a class with a const constructor, should make the forwarding constructor const.

That might not be implemented yet, but it should be eventually.

**Comment by eernstg** [comment] 2018-04-09 12:41
> might not be implemented yet ..

Right, but it is requested in #32223, so that's the place to check out the current implementation status (and also to advocate for getting it done, if the current priority assigned to this task appears to be too low).
