### ISSUE TITLE
dartdoc is broken

### ISSUE THREAD

**Issue by pylaligand** [dart-lang/sdk#26562] opened 2016-05-27 21:11 UTC
```
$ dart --version
Dart VM version: 1.17.0-dev.6.0 (Thu May 26 19:29:29 2016) on "linux_x64"

$ dartdoc --version
dartdoc version: 0.9.0

$ dartdoc --input my_package/ --output out/
Generating documentation for 'my_package' into /path/to/out/

Generation failed: Class '_HashMap<Folder, YamlMap>' has no instance getter 'urlMappings'.

NoSuchMethodError: method not found: 'urlMappings'
Receiver: Instance of '_HashMap<Folder, YamlMap>'
Arguments: []
dart:core                                                                                 Object.noSuchMethod
package:analyzer/source/embedder.dart 222                                                 EmbedderUriResolver.length
package:dartdoc/dartdoc.dart 148                                                          DartDoc._parseLibraries
package:dartdoc/dartdoc.dart 88                                                           DartDoc.generateDocs.<async>
===== asynchronous gap ===========================
dart:async                                                                                _Completer.completeError
package:dartdoc/dartdoc.dart 129                                                          DartDoc.generateDocs.<async>
===== asynchronous gap ===========================
dart:async                                                                                Future.Future.microtask
package:dartdoc/dartdoc.dart                                                              DartDoc.generateDocs
/b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 130  main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                                                       Chain.capture
/b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 129  main.<async>
dart:async                                                                                _SyncCompleter.complete
package:dartdoc/dartdoc.dart 49                                                           initGenerators.<async>
dart:async                                                                                _SyncCompleter.complete
package:dartdoc/src/html/html_generator.dart 62                                           HtmlGenerator.create.<async>
dart:async                                                                                _SyncCompleter.complete
package:dartdoc/src/html/templates.dart 108                                               Templates.create.<async>
dart:async                                                                                _SyncCompleter.complete
package:dartdoc/src/html/templates.dart 91                                                Templates.create.<async>._loadTemplate.<async>
dart:async                                                                                _SyncCompleter.complete
package:dartdoc/src/html/resource_loader.dart 22                                          loadAsString.<async>
dart:async                                                                                _SyncCompleter.complete
package:dartdoc/src/html/resource_loader.dart 33                                          loadAsBytes.<async>
```

The analyzer library was updated in https://github.com/dart-lang/sdk/commit/53fe39137fb7601d2ea3596a8a6407815c383e8f where EmbeddedUriResolver now takes an `EmbeddedSdk` in its constructor instead of `Map<Folder, YamlMap>`, but dartdoc.dart still passes the latter at https://github.com/dart-lang/dartdoc/blob/d801824e747826508f5d76af422e2e09b8472613/lib/dartdoc.dart#L158.

(Note: line numbers appear a bit off, not sure why)

**Comment by pq** [comment] 2016-05-27 23:46
Ah!  Sorry.  I made that change in the `0.27.4-alpha.8` and didn't think it would break dartdoc. :(.

**Comment by pq** [comment] 2016-05-28 00:04
Sorry again for this.  Assuming the right thing to do is roll forward and update to the new API, I opened a PR with the required changes: https://github.com/dart-lang/dartdoc/pull/1167.

I note that there are some failing tests but I think they're unrelated?

**Comment by pq** [comment] 2016-05-28 13:52
Actually the break precedes the push.  The issue is that the `dartdoc` shipped with the SDK is not up to date with the changed API.  (I'm assuming you're testing on the latest dev build?)

Moving forward I think it's probably best that  I

1. restore the broken API (deprecate it and add a parallel path forward)
2. not merge this proposed PR
3. not merge the correlary PR over on flutter (https://github.com/flutter/flutter/pull/4253)
4. push a new alpha

That should get dartdoc back on the rails without any changes.  I can come back and clean up when we have a neater path forward.

Unfortunately, this means that dartdoc will remain broken on the dev SDK until we push again next week...

Sorry again for that!

cc @keertip @bwilkerson for thoughts on this proposal (and ideas as to why this wasn't caught by tests --- or maybe this is just a symptom of the very noisy tree?)

**Comment by pq** [comment] 2016-05-28 14:34
> restore the broken API

Assuming this is the way we want to go: https://codereview.chromium.org/2021453003/

**Comment by pq** [comment] 2016-05-29 14:09
Fix landed in https://github.com/dart-lang/sdk/commit/fba5cbc425e54b015d9ffefac4e0789d5502846c.  `dartdoc` will be good again in the next dev build.  In the meantime, the previous dev SDK should be fine or alternatively, `dartdoc` can be run from `pub`.

```
pub global activate dartdoc
pub global run dartdoc
```

**Closed by pq** 2016-05-29 14:09 UTC
Labels: area-analyzer, bug, P1 high

**Comment by mit-mit** [comment] 2016-05-30 12:27
@pq do we need a merge request to get this fixed in 1.17, or is the fix already there?

**Comment by pq** [comment] 2016-05-30 13:23
@mit-mit : the fix landed in https://github.com/dart-lang/sdk/commit/fba5cbc425e54b015d9ffefac4e0789d5502846c.  Am I right that we haven't done the final push to trunk yet?  Or does this need to be cherry-picked?

**Comment by mit-mit** [comment] 2016-05-30 13:25
@pq the last full push was last week, so if we need this in 1.17 (scheduled for this week) please file a cherry pick request.

**Comment by pq** [comment] 2016-05-30 13:53
Great, thanks.  Cherry pick request filed here: https://github.com/dart-lang/sdk/issues/26572.

**Comment by whesse** [comment] 2016-05-31 21:33
We have another important cherry-pick coming within a day or two, so since we seem quite certain of the reliability of this cherry-pick, I propose we do it at the same time as the other one.  I don't think we need to make a new version of dev today, with just this change.

**Comment by pq** [comment] 2016-05-31 22:39
Works for me.  As long as this gets into `1.17`, a day or two won't matter.

**Comment by pq** [comment] 2016-06-02 13:50
@pylaligand : FYI `1.17.0-dev.6.1` is [up](https://www.dartlang.org/downloads/archive/) with this fix.
