### ISSUE TITLE
Two analysis server tests failing on Windows

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#32355] opened 2018-02-28 15:36 UTC
After re-enabling windows testing of the analysis server unit tests, and fixing most of them (thanks @DanTup), two failures are showing on the builder (but not locally?).

FAILED: none-vm-checked release_x64 pkg/analysis_server/test/integration/analysis/set_general_subscriptions_test
Expected: Pass
Actual: RuntimeError

FAILED: none-vm-checked release_x64 pkg/analysis_server/test/benchmarks_test
Expected: Pass
Actual: RuntimeError

The builder with the log showing the failures is at
https://ci.chromium.org/buildbot/client.dart/pkg-win7-release-be/10093

Suppressing the failures in pkg/pkg.status on Windows.

@bwilkerson

**Comment by DanTup** [comment] 2018-02-28 15:43
@whesse Thanks for this; I wasn't aware of the benchmarks so hadn't been running them locally (I'd just run `test_all.dart`). These are failing because they use `curl`.

Moving my comment from #32226 so we can close that one off.

@bwilkerson PowerShell does have an invoke-webrequest (aliased to `curl` in fact) that might allow these to work. Let me know if you think it's worthwhile me taking a stab at them.

**Comment by DanTup** [comment] 2018-02-28 15:47
Also, non-benchmark test failing in the bots is this one:

<details>
<summary>SetGeneralSubscriptionsTest | test_options</summary>
<code><pre>
  Expected: <true>
    Actual: <false>
  
  package:test/src/frontend/expect.dart 165:30                                             fail
  package:test/src/frontend/expect.dart 159:3                                              _expect
  package:test/src/frontend/expect.dart 69:3                                               expect
  pkg\analysis_server\test\integration\analysis\set_general_subscriptions_test.dart 37:5   SetGeneralSubscriptionsTest.test_options
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22                                                           _Completer.completeError
  pkg\analysis_server\test\integration\analysis\set_general_subscriptions_test.dart        SetGeneralSubscriptionsTest.test_options
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                                                _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77                                          _asyncThenWrapperHelper
  pkg\analysis_server\test\integration\analysis\set_general_subscriptions_test.dart 21:24  SetGeneralSubscriptionsTest.test_options
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 531                                    _LocalInstanceMirror._invoke
  dart:mirrors-patch/dart:mirrors/mirrors_impl.dart 527                                    _LocalInstanceMirror.invoke
  package:test_reflective_loader/test_reflective_loader.dart 253:35                        _runTest.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26                             StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15                             StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14                             StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134                                                                _rootRunUnary
  dart:async/zone.dart 1031                                                                _CustomZone.runUnary
  dart:async/future_impl.dart 129                                                          _FutureListener.handleValue
  dart:async/future_impl.dart 633                                                          _Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 662                                                          _Future._propagateToListeners
  dart:async/future_impl.dart 477                                                          _Future._completeWithValue
  dart:async/future_impl.dart 507                                                          _Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15                             StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48                             StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 925                                                                 _CustomZone.runGuarded
  dart:async/zone.dart 965                                                                 _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                                                    _microtaskLoop
  dart:async/schedule_microtask.dart 50                                                    _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113                                   _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166                                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                                                _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 238                                                          _Future.then
  package:test_reflective_loader/test_reflective_loader.dart 253:8                         _runTest
  package:test_reflective_loader/test_reflective_loader.dart 126:18                        defineReflectiveTests.<fn>.<fn>
  package:test/src/backend/declarer.dart 161:27                                            Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                                                _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77                                          _asyncThenWrapperHelper
  package:test/src/backend/declarer.dart 159:70                                            Declarer.test.<fn>.<fn>.<fn>
  package:test/src/backend/invoker.dart 250:15                                             Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                                                _CustomZone.registerCallback
  dart:async/zone.dart 964                                                                 _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                                                   scheduleMicrotask
  dart:async/future.dart 198                                                               new Future.microtask
  package:test/src/backend/invoker.dart 247:23                                             Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 1501                                                                runZoned
  package:test/src/backend/invoker.dart 247:5                                              Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 159:33                                            Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 1501                                                                runZoned
  package:test/src/backend/declarer.dart 158:13                                            Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                                                _CustomZone.registerCallback
  dart:async/zone.dart 964                                                                 _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                                                   scheduleMicrotask
  dart:async/future.dart 198                                                               new Future.microtask
  package:test/src/backend/declarer.dart 143:66                                            Declarer.test.<fn>
  package:test/src/backend/invoker.dart 404:25                                             Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                                                _CustomZone.registerCallback
  dart:async/zone.dart 964                                                                 _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                                                   scheduleMicrotask
  dart:async/future.dart 198                                                               new Future.microtask
  package:test/src/backend/invoker.dart 403:31                                             Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                                               new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15                             StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48                             StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 925                                                                 _CustomZone.runGuarded
  dart:async/zone.dart 965                                                                 _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15                             StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48                             StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 949                                                                 _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21                                          Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382                                      _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416                                      _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165                                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                                                _CustomZone.registerCallback
  dart:async/zone.dart 964                                                                 _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                                                 new Timer
  dart:async/timer.dart 87                                                                 Timer.run
  dart:async/future.dart 172                                                               new Future
  package:test/src/backend/invoker.dart 403:15                                             Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                                                _CustomZone.registerCallback
  dart:async/zone.dart 964                                                                 _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                                                   scheduleMicrotask
  dart:async/future.dart 198                                                               new Future.microtask
  package:test/src/backend/invoker.dart 390:27                                             Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 1501                                                                runZoned
  package:test/src/backend/invoker.dart 390:9                                              Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 444:15                                             Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 389:7                                              Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                                                Chain.capture.<fn>
  dart:async/zone.dart 1126                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 1501                                                                runZoned
  package:stack_trace/src/chain.dart 99:12                                                 Chain.capture
  package:test/src/backend/invoker.dart 388:11                                             Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11                                LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31                                 _LiveTest.run
  dart:async/future.dart 200                                                               new Future.microtask.<fn>
  dart:async/zone.dart 1122                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 925                                                                 _CustomZone.runGuarded
  dart:async/zone.dart 965                                                                 _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126                                                                _rootRun
  dart:async/zone.dart 1023                                                                _CustomZone.run
  dart:async/zone.dart 925                                                                 _CustomZone.runGuarded
  dart:async/zone.dart 965                                                                 _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                                                    _microtaskLoop
  dart:async/schedule_microtask.dart 50                                                    _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113                                   _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166                                   _RawReceivePortImpl._handleMessage
<pre></code>
</details>

**Comment by DanTup** [comment] 2018-02-28 16:23
@bwilkerson Actually, I can repro `set_general_subscriptions_test` failure locally too - I guess it's not being run as part of `test_all` either. What's the correct thing to run to execute all the same tests the buildbots do?

I've fixed it now. I also have a fix for the benchmarks to just call to PowerShell - this works locally but I don't know whether all Windows buildbots are versions that have PowerShell (I presume so?). Let me know if you think it's a good fix (if we can commit it and see the result of it while it's still marked as skip, that would be perfect?).

## old
```dart
    ProcessResult result = _run('curl', <String>[
      'localhost:$vmServicePort/_getAllocationProfile\?isolateId=isolates/root\&gc=full'
    ]);
```

## new
```dart
    String vmService =
        'http://localhost:$vmServicePort/_getAllocationProfile\?isolateId=isolates/root\&gc=full';
    ProcessResult result;
    if (Platform.isWindows) {
      result = _run(
          'powershell', <String>['-Command', '(curl "$vmService").Content']);
    } else {
      result = _run('curl', <String>[vmService]);
    }
```

**Comment by bwilkerson** [comment] 2018-02-28 16:37
> Actually, I can repro set_general_subscriptions_test failure locally too - I guess it's not being run as part of test_all either.

We should add `set_general_subscriptions_test` to the `test_all` in it's directory.

> What's the correct thing to run to execute all the same tests the buildbots do?

You'd need to run `test.py` to duplicate the bots. On my Mac, I use the following script (run from the root of the sdk repo):
```
#!/usr/bin/env bash

options="--arch x64 --mode release --progress color --report"
./tools/test.py $options --checked pkg/analyzer/
./tools/test.py $options --checked pkg/analysis_server
./tools/test.py $options --compiler dart2analyzer --runtime none --tasks=2
```
This doesn't quite run everything. The bots also run the 'pkg/analyzer_cli' tests, and run all of the tests in non-checked mode as well. But I find that it's very rare that I don't catch potential bot failures by running this subset.

**Comment by DanTup** [comment] 2018-02-28 16:53
@bwilkerson Great, thanks! My python is messed up right now (as is VS - I have two preview versions that have expired) so I'll try and get it all sorted at the weekend so I can run these.

Looks like there are some integration tests timing out:

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fanalyzer-win7-release-be%2F10444%2F%2B%2Frecipes%2Fsteps%2Fanalysis_server_unit_tests%2F0%2Fstdout

They are slow on my machine (13 secs for one that hit a 30sec timeout on the build bot) so I don't know how best to update the status file - can someone advise? (unfortunately because of Python issues I also can't run the gardening scripts that look like they'd update the file locally for me!)

**Comment by DanTup** [comment] 2018-02-28 17:02
> We should add `set_general_subscriptions_test` to the test_all in it's directory.

Turns out it's in the `test_all` in it's directory, but it's directory is `integration` and I presume it's deliberately missing from the parent file.

There are actually a bunch of test failures for me in the `integration` folder that we'll need to deal with. As far as I can tell, they're not breaking any builds though? (The one failing bot is the one I linked above caused by two timeouts?)

**Comment by DanTup** [comment] 2018-02-28 17:34
I've opened #32356 about time timeouts (and pushed a CL to suppress them them) to keep this one on-topic.

I'll push these changes in the morning (when I can keep a better eye on the build since it's almost end of my day here) https://dart-review.googlesource.com/c/sdk/+/44240 and see if they do the job.

**Comment by bwilkerson** [comment] 2018-02-28 18:25
> Turns out it's in the test_all in it's directory, but it's directory is integration and I presume it's deliberately missing from the parent file.

Yes, not including the integration tests is intentional (they can take a long time to run). They should all be run on the bots, though, so I don't know why the bots aren't failing (unless they're being skipped for a different reason).

**Comment by DanTup** [comment] 2018-02-28 18:36
I don't remember seeing them being skipped on the status file (and `set_general_subscriptions_test` mentioned above is actually in the integration folder) so my guess is that it's something specific to my machine. I've made a note to come back to them once I've deal with the open issues.

**Comment by DanTup** [comment] 2018-03-01 08:56
I've landed a fix for at least one of these not realising it would result in a failure (expected RuntimeError, actual Pass). I've got a CL to update the status on a couple of tests that needs reviewing:

https://dart-review.googlesource.com/c/sdk/+/44260

**Comment by keertip** [comment] 2023-04-27 21:50
Closing as this has most likely been fixed.

**Closed by keertip** 2023-04-27 21:50 UTC
Labels: area-analyzer, analyzer-server, type-bug, P4, analyzer-technical-debt
