### ISSUE TITLE
Please cache Dart-Analyzer results

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25046] opened 2015-11-26 10:22 UTC
Here https://github.com/MikeMitterer/dart-material-design-lite-site/tree/master/samples I have a few samples for MDL/Dart Each sample demonstrates one mdl feature. Every sample has its own pubspec and includes a few libraries. If DA analyzes the samples it reanalyzes for example the mdl-package over and over again. Means in this case 52 times!!!!!

**Comment by alexander-doroshko** [comment] 2015-11-26 10:24
looks like a duplicate of #24611

**Comment by MikeMitterer** [comment] 2015-11-26 10:47
> Analysis server absolutely re-analyzes code multiple times if it's referenced from multiple packages. This is, unfortunately, *a long-standing known issue.*

Yes - sorry but I'm struggling with this problem again and again.
I thought it was solved but the issue was just closed - not solved.

**Comment by alexander-doroshko** [comment] 2015-11-26 10:59
#24611 is open, but no assignee and no milestone set.

**Comment by devoncarew** [comment] 2018-06-27 12:03
I believe this was addressed with the analysis driver re-write.

**Closed by devoncarew** 2018-06-27 12:03 UTC
Labels: P2 medium, Type: bug, Type: performance, analyzer-server, area-analyzer
