### ISSUE TITLE
findSystemLocale in Browser returns de in Chrome+FF but de_DE in Safari (Mac)

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#31175] opened 2017-10-20 14:02 UTC
`final String locale = await findSystemLocale(); print(locale)`

Dartium: de
Chrome 61.03: de
FF 56.0: de
Safari 11.0: de_DE

Cmdline locale:
```bash
LANG="de_AT.UTF-8"
LC_COLLATE="de_AT.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_AT.UTF-8"
LC_MONETARY="de_AT.UTF-8"
LC_NUMERIC="de_AT.UTF-8"
LC_TIME="de_AT.UTF-8"
LC_ALL=
``` 

// OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1611
Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

// Software installed -----------------------------------------------------------
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
Pub 1.24.2

NPM: 5.3.0

**Comment by alan-knight** [comment] 2017-10-20 18:30
@MikeMitterer 

What does `window.navigator.language` in JS return in each of those cases?
What does  `defaults read -g AppleLanguages` print when run from a shell?

All findSystemLocale is doing is making the form of window.navigator.language canonical. But the Apple information is more complicated, and Safari may be interpreting it differently than Chrome.

**Comment by MikeMitterer** [comment] 2017-10-20 23:00
```
defaults read -g AppleLanguages
(
    de,
    en
)
```
window.navigator.language: "de-DE"

**Comment by alan-knight** [comment] 2017-10-23 19:45
Oops, closed in the wrong direction.  Moved to https://github.com/dart-lang/intl/issues/150

**Closed by alan-knight** 2017-10-23 19:45 UTC

**Comment by alan-knight** [comment] 2017-10-23 20:16
Is the window.navigator.language listed for Safari or for Chrome? I'm guessing Safari.

I'm curious how you get unqualified locales for the apple preferences, I can't get anything that doesn't have a country suffix. e.g. 

`
(
    "de-DE",
    "en-DE",
    "fr-DE"
)
`

But with that setting in the OS, in Safari I get 

> window.navigator.language
< "de-DE"
> window.navigator.languages
< ["de-DE"] (1)

and in Chrome

      window.navigator.language
      "de"
      window.navigator.languages
      (2) ["en-US", "en"]

This is all JS, no Dart involved. So basically this seems to be the browser behavior, so working as intended. Or at least working in a way that there isn't much we can do about it.

There is a Chrome setting for languages. But its interaction with the Mac language settings is not obvious to me. It tells me that my language settings are only for English, even while it's presenting me the UI in German.

> Ordnen Sie Sprachen in der gewünschten Reihenfolge an
> Englisch (Vereinigte Staaten)
> 
> Englisch

If I add a de-LI there, then I also get de-LI and de showing up in navigator.languages. So it's picking up some information from the OS, but not as much as if the value is directly set in Chrome.

**Comment by alan-knight** [comment] 2017-10-23 20:22
There's also going to be some interaction with what was sent as the accept-languages to the server and what comes back to the browser.
