### ISSUE TITLE
Dart Analyzer Error ('DynamicTypeImpl' is not a subtype of type 'InterfaceType')

### ISSUE THREAD

**Issue by tadly** [dart-lang/sdk#39257] opened 2019-11-06 09:02 UTC
While there are many **Dart Analyzer Error** getting reported, they are different from what I can tell and so is this one.

I've created a new Project with no changes made whatsoever and this is what I'm getting.

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v5.3.8-arch1-1, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /home/tadly/Development/workspaces/Flutter/tmp/test/widget_test.dart context: exception_20191106_095601_099
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5568:5)
#1      TypeProviderForLink.stringType (package:analyzer/src/summary/link.dart:5553:23)
#2      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:1092:56)
#3      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9141:49)
#4      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4260:10)
#5      UnifyingAstVisitor.visitSimpleStringLiteral (package:analyzer/dart/ast/visitor.dart:3413:59)
#6      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9141:49)
#7      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2564:16)
#8      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5387:36)
#9      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5230:7)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#11     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#12     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5666:47)
#13     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2647:22)
#14     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:908:20)
#15     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1645:20)
#16     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3870:12)
#17     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3570:15)
#18     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3510:7)
#19     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#20     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#21     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#23     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#24     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3543:42)
#25     Linker.link (package:analyzer/src/summary/link.dart:4075:35)
#26     _relink (package:analyzer/src/summary/link.dart:312:74)
#27     link (package:analyzer/src/summary/link.dart:126:3)
#28     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#31     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#32     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1429:29)
#33     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1245:30)
#34     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#35     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#38     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#39     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#40     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#41     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#42     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#48     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#50     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#52     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#53     new Future.syn...
```

For additional log information, please append the contents of
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /home/tadly/Development/workspaces/Flutter/tmp/test/widget_test.dart context: exception_20191106_095601_099
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5568:5)
#1      TypeProviderForLink.stringType (package:analyzer/src/summary/link.dart:5553:23)
#2      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:1092:56)
#3      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9141:49)
#4      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4260:10)
#5      UnifyingAstVisitor.visitSimpleStringLiteral (package:analyzer/dart/ast/visitor.dart:3413:59)
#6      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9141:49)
#7      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2564:16)
#8      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5387:36)
#9      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5230:7)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#11     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#12     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5666:47)
#13     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2647:22)
#14     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:908:20)
#15     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1645:20)
#16     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3870:12)
#17     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3570:15)
#18     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3510:7)
#19     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#20     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#21     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#23     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#24     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3543:42)
#25     Linker.link (package:analyzer/src/summary/link.dart:4075:35)
#26     _relink (package:analyzer/src/summary/link.dart:312:74)
#27     link (package:analyzer/src/summary/link.dart:126:3)
#28     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#31     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#32     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1429:29)
#33     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1245:30)
#34     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#35     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#38     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#39     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#40     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#41     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#42     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#48     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#50     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#52     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#53     new Future.sync (dart:async/future.dart:224:31)
#54     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#55     _rootRun (dart:async/zone.dart:1124:13)
#56     _CustomZone.run (dart:async/zone.dart:1021:19)
#57     _runZoned (dart:async/zone.dart:1516:10)
#58     runZoned (dart:async/zone.dart:1463:12)
#59     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#60     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#61     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#62     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#63     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#64     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#65     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

1573030557556 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":183,"uri":"package:flutter/rendering.dart","items":[{"label":"DecorationPosition","declaringLibraryUri":
1573030557897 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":68,"uri":"package:flutter/widgets.dart","items":[{"label":"DecorationPosition","declaringLibraryUri":"pa
1573030558063 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":349,"uri":"package:vector_math/hash.dart","items":[{"label":"hashObjects","declaringLibraryUri":"package
1573030558100 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":69,"uri":"package:vector_math/vector_math_64.dart","items":[{"label":"cross2A","declaringLibraryUri":"pa
1573030558147 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":192,"uri":"package:flutter/gestures.dart","items":[{"label":"kPressTimeout","declaringLibraryUri":"packa
1573030558190 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":23,"uri":"package:flutter/services.dart","items":[{"label":"HapticFeedback","declaringLibraryUri":"packa
1573030558227 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":350,"uri":"package:collection/collection.dart","items":[{"label":"maxBy","declaringLibraryUri":"package:
1573030558236 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":108,"uri":"package:flutter/scheduler.dart","items":[{"label":"AppLifecycleState","declaringLibraryUri":"
1573030558243 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":382,"uri":"package:typed_data/typed_buffers.dart","items":[{"label":"Int8Buffer","declaringLibraryUri":"
1573030558252 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":383,"uri":"dart:nativewrappers","items":[]}],"removedLibraries":[]}}
1573030558279 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":45,"uri":"dart:ui","items":[{"label":"TextBaseline","declaringLibraryUri":"dart:ui","element":{"kind":"E
1573030558287 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":119,"uri":"package:meta/meta.dart","items":[{"label":"Immutable","declaringLibraryUri":"package:meta/met
1573030558302 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":118,"uri":"package:flutter/foundation.dart","items":[{"label":"debugPrintDone","declaringLibraryUri":"pa
1573030558481 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":420,"uri":"dart:_http","items":[{"label":"HttpOverrides","declaringLibraryUri":"dart:_http","element":{"
1573030558528 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":430,"uri":"dart:io","items":[{"label":"Stdout","declaringLibraryUri":"dart:io","element":{"kind":"CLASS"
1573030558546 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":445,"uri":"dart:isolate","items":[{"label":"Capability","declaringLibraryUri":"dart:isolate","element":{
1573030558554 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":446,"uri":"dart:developer","items":[{"label":"TimelineSyncFunction","declaringLibraryUri":"dart:develope
1573030558645 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":485,"uri":"dart:math","items":[{"label":"atan2","declaringLibraryUri":"dart:math","element":{"kind":"FUN
1573030558782 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":32,"uri":"dart:typed_data","items":[{"label":"UnmodifiableUint32ListView","declaringLibraryUri":"dart:ty
1573030558783 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":503,"uri":"dart:convert","items":[{"label":"Codec","declaringLibraryUri":"dart:convert","element":{"kind
1573030558871 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":517,"uri":"dart:async","items":[{"label":"ControllerCancelCallback","declaringLibraryUri":"dart:async","
1573030558928 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":431,"uri":"dart:_internal","items":[{"label":"UnmodifiableListMixin","declaringLibraryUri":"dart:_intern
1573030558971 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":367,"uri":"dart:collection","items":[{"label":"MapView","declaringLibraryUri":"dart:collection","element
1573030559037 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":518,"uri":"dart:core","items":[{"label":"","declaringLibraryUri":"dart:core","element":{"kind":"CLASS","
1573030559428 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":553,"uri":"package:flutter/material.dart","items":[{"label":"DecorationPosition","declaringLibraryUri":"
1573030559471 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":679,"uri":"package:tmp/main.dart","items":[{"label":"MyHomePage","declaringLibraryUri":"package:tmp/main
1573030559555 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":680,"uri":"package:flutter_test/flutter_test.dart","items":[{"label":"throwsAssertionError","declaringLi
1573030559636 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":732,"uri":"dart:ffi","items":[{"label":"Unsized","declaringLibraryUri":"dart:ffi","element":{"kind":"CLA
1573030559636 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":737,"uri":"file:///home/tadly/Development/workspaces/Flutter/tmp/test/widget_test.dart","items":[{"label
1573030561173 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /home/tadly/Development/workspaces/Flutter/tmp/test/widget_test.dart context: exception_20191106_095601_0
```

**Comment by keertip** [comment] 2019-11-06 09:06
Thanks for the report. This appears to be a duplicate of #35437, please follow that issue.

**Comment by keertip** [comment] 2019-11-06 09:06
Duplicate of #35437

**Closed by keertip** 2019-11-06 09:06 UTC
Labels: area-analyzer

**Comment by tadly** [comment] 2019-11-06 09:12
I did find this issue previously given it's age I dismissed it as the "solution" was to upgrade the analyzer.

Anyways, I delete `<flutter-sdk>/bin/cache`, run `flutter packages get` and things are looking better again.

Maybe this helps some other poor soul in the future :)

**Comment by keertip** [comment] 2019-11-06 09:43
Glad you found a workaround, as was able to get back to a working state. Thanks for letting us know!
