### ISSUE TITLE
FileSystemException in _WindowsDirectoryWatcher when running analysis server

### ISSUE THREAD

**Issue by Pareshoct7** [dart-lang/sdk#34791] opened 2018-10-15 14:17 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\iqor\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\Android\Flutter\kaledate\flutter_app], excluded: [D:\Android\Flutter\kaledate\flutter_app\.idea, D:\Android\Flutter\kaledate\flutter_app\.dart_tool, D:\Android\Flutter\kaledate\flutter_app\.pub, D:\Android\Flutter\kaledate\flutter_app\build]}, clientRequestTime: 1539580548522}
FileSystemException: Exists failed, path = 'D:\Android\Flutter\kaledate\flutter_app\build\app\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\facebook\core' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-23 03:51
Duplicate of #34294

**Closed by stereotype441** 2018-10-23 03:51 UTC
Labels: area-analyzer
