### ISSUE TITLE
VM assertion failure on win64 with service/smart_next_test

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#24439] opened 2015-09-25 12:07 UTC
I have not seen this one before, @johnmccutchan @rmacnak-google .

vm\scopes.cc:352: error: expected: var->is_captured()

See output from the buildbot below:

=== Failure summary:

FAILED: none-vm-checked debug_x64 service/smart_next_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching build\DebugX64\dart.exe --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=build/DebugX64/packages/ --enable-vm-service:0 E:\b\build\slave\vm-win64-debug-be\build\sdk\runtime\observatory\tests\service\smart_next_test.dart --testee-mode
Observatory listening on http://127.0.0.1:61989
** Signaled to run test queries on 61989

Running smart_next_test.dart [1/27]
Breakpoint reached
Running smart_next_test.dart [2/27]
Checking we are at line 16
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(57))
Running smart_next_test.dart [3/27]
next-sync
Running smart_next_test.dart [4/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [5/27]
Checking we are at line 16
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(55))
Running smart_next_test.dart [6/27]
next-async
Running smart_next_test.dart [7/27]
Breakpoint reached
Running smart_next_test.dart [8/27]
Checking we are at line 17
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(62))
Running smart_next_test.dart [9/27]
next-sync
Running smart_next_test.dart [10/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [11/27]
Checking we are at line 18
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(67))
Running smart_next_test.dart [12/27]
next-sync
Running smart_next_test.dart [13/27]
Breakpoint reached
Running smart_next_test.dart [14/27]
Checking we are at line 19
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(74))
Running smart_next_test.dart [15/27]
next-sync
Running smart_next_test.dart [16/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [17/27]
Checking we are at line 19
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(72))
Running smart_next_test.dart [18/27]
next-async
Running smart_next_test.dart [19/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [20/27]
Checking we are at line 20
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(81))
Running smart_next_test.dart [21/27]
next-sync
Running smart_next_test.dart [22/27]
vm\scopes.cc:352: error: expected: var->is_captured()
** Killing script

stderr:
Unhandled exception:
Uncaught Error: Testee exited with 3
Stack Trace:
#0      _TestLauncher.launch.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/vm-win64-debug-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:79:11)
#1      _RootZone.runUnary (dart:async/zone.dart:1165)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#4      _Future._completeWithValue (dart:async/future_impl.dart:376)
#5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#7      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:894)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Command[vm]: set DART_CONFIGURATION=DebugX64 & build\DebugX64\dart.exe --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=build/DebugX64/packages/ E:\b\build\slave\vm-win64-debug-be\build\sdk\runtime\observatory\tests\service\smart_next_test.dart
Took 0:00:08.939000

Short reproduction command (experimental):
    python tools/test.py -ax64 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t120 service/smart_next_test

**Comment by fsc8000** [comment] 2015-09-25 12:08
http://build.chromium.org/p/client.dart/builders/vm-win64-debug-be/builds/1687/steps/checked_tests/logs/stdio

**Comment by iposva-google** [comment] 2015-09-25 12:30
cc @crelier 

Note that with a recent optimization not all variables are being captured in an async/await method.

**Comment by crelier** [comment] 2015-09-25 17:29
I am not able to reproduce this on my machine (see below).
Note that variables are marked as captured at compile time in a deterministic fashion. So I do not think this has anything to do with my recent optimization. Ryan is looking into it.

out/DebugX64/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ runtime/observatory/tests/service/smart_next_test.dart
** Launching out/DebugX64/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ --enable-vm-service:0 /usr/local/google/home/regis/ssd/dart1/sdk/runtime/observatory/tests/service/smart_next_test.dart --testee-mode
Observatory listening on http://127.0.0.1:56767
** Signaled to run test queries on 56767

Running smart_next_test.dart [1/27]
Breakpoint reached
Running smart_next_test.dart [2/27]
Checking we are at line 16
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(57))
Running smart_next_test.dart [3/27]
next-sync
Running smart_next_test.dart [4/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [5/27]
Checking we are at line 16
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(55))
Running smart_next_test.dart [6/27]
next-async
Running smart_next_test.dart [7/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [8/27]
Checking we are at line 17
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(62))
Running smart_next_test.dart [9/27]
next-sync
Running smart_next_test.dart [10/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [11/27]
Checking we are at line 18
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(67))
Running smart_next_test.dart [12/27]
next-sync
Running smart_next_test.dart [13/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [14/27]
Checking we are at line 19
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(74))
Running smart_next_test.dart [15/27]
next-sync
Running smart_next_test.dart [16/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [17/27]
Checking we are at line 19
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(72))
Running smart_next_test.dart [18/27]
next-async
Running smart_next_test.dart [19/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [20/27]
Checking we are at line 20
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(81))
Running smart_next_test.dart [21/27]
next-sync
Running smart_next_test.dart [22/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [23/27]
Checking we are at line 20
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(79))
Running smart_next_test.dart [24/27]
next-async
Running smart_next_test.dart [25/27]
Breakpoint reached
Breakpoint reached
Running smart_next_test.dart [26/27]
Checking we are at line 21
We are at Frame(doAsync.<doAsync_async_body> smart_next_test.dart:token(86))
Running smart_next_test.dart [27/27]
** Killing script
** Process exited

**Comment by rmacnak-google** [comment] 2015-09-25 23:05
There was a real bug with the var descriptor handling for :async_op, which happened if you synchronously stepped into an async function without an await. This test is flaky for other reasons, and sometimes happens to step at the wrong time and hit this.

Broken: 1abc4ce8e91def90e642fe7bf6ffa4668acd3c83
Fixed: d7b46bf5c1a0f1287a41435bf1856c994054a836

**Closed by rmacnak-google** 2015-09-25 23:05 UTC
Labels: Area-VM, Priority-High
