### ISSUE TITLE
pkg-mac-release pkg/analysis_server/test/src/plugin/plugin_manager_test times out flakily

### ISSUE THREAD

**Issue by sortie** [dart-lang/sdk#34146] opened 2018-08-15 11:04 UTC
https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/pkg-mac-release/1761
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8938135623423805280/+/steps/package_unit_tests/0/stdout

    FAILED: dartk-vm release_x64 pkg/analysis_server/test/src/plugin/plugin_manager_test
    Expected: Pass Slow
    Actual: RuntimeError
    --- Command "vm" (took 03:29.000163s):
    DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable_asserts --    ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages     /b/s/w/ir/cache/builder/sdk/pkg/analysis_server/test/src/plugin/plugin_manager_test.dart
    exit code:
    255
    stdout:
    === Snip: See end of https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8938135623423805280/+/steps/package_unit_tests/0/stdout ===
    TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
    === Snip: See end of https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8938135623423805280/+/steps/package_unit_tests/0/stdout ===
    stderr:
    Unhandled exception:
    Dummy exception to set exit code.
    #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
    #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    #3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
    #4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
    --- Re-run this test:
    python tools/test.py -m release -c dartk -r vm -n unittest-asserts-mac --enable-asserts -t 240 --use-sdk pkg/analysis_server/test/src/plugin/plugin_manager_test

The commit in question only changed an unrelated file permission and couldn't have caused this issue. The preceding commit worked, thus I conclude this test outcome is a flake.

**Comment by bwilkerson** [comment] 2018-08-28 19:55
Duplicate of https://github.com/dart-lang/sdk/issues/34231.

**Closed by bwilkerson** 2018-08-28 19:55 UTC
Labels: area-analyzer
