### ISSUE TITLE
please add an option to `File.writeAsBytes` to avoid overwriting.

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#59587] opened 2024-11-22 10:09 UTC
``` Dart
var outputFile = File("a.jpg");
if (!outputFile.exist()) {
    // another program creates a.jpg
    await outputFile.writeAsBytes(jpegData); // boom overwrite!!!
}
```
please add an option to `File.writeAsBytes` to avoid overwriting.

maybe something like `await outputFile.writeAsBytes(jpegData, exclusive: true);`

**Comment by julemand101** [comment] 2024-11-22 11:18
What behavior do you expect in case the file already exists? Throw exception?

**Comment by gintominto5329** [comment] 2024-11-22 13:54
this problem has no solution ,its related to concurrency ,

its design issue of the dart-app

even if c++ adds a special atomic procedure/function

**Comment by stephane-archer** [comment] 2024-11-22 14:21
@julemand101 yes

**Comment by stephane-archer** [comment] 2024-11-22 23:42
```
var file = await File("a.txt").create(recursive : false,
exclusive: true,
});
// someone write to a.txt
file.white(data); // overwrite!
```
From my understanding create guarantee you to create the file, but from my understanding File is not a file descriptor so now that the file is created overwrite can still happens

**Comment by mraleph** [comment] 2024-11-23 00:44
@stephane-archer AFAIK there is no way to prevent that in POSIX though - if the other program does not take precautions (e.g. does not use `O_EXCL` with `O_CREAT`) then you can't stop it from writing something into the same file you have opened.

**Comment by mraleph** [comment] 2024-11-23 19:00
@stephane-archer not to the best of my knowledge. there are file locks by they are _advisory_ (so writers should all cooperate and use them - write operations themselves don't check locks). Mandatory locks API kinda sorta exists - but not really, see [`man fcntl`](https://man7.org/linux/man-pages/man2/fcntl.2.html), section "Mandatory locking".

**Comment by stephane-archer** [comment] 2024-11-23 19:27
Thanks for your answers

So the best we have right know in Dart to write data without overwrite is:
```` Dart
var file = await File("a.txt").create(recursive : false,
exclusive: true,
})
file.writeAsBytes(data);
````
I think it would be still nice to have a short version for this:
```` Dart
await File("a.txt").writeAsBytes(data, exclusive: true);
// or 

File("a.txt", exclusive: true).writeAsBytes(data);

````

**Comment by a-siva** [comment] 2024-12-04 21:53
I don't think the short version makes it any easier.
Closing issue as 'works as intended'

**Closed** 2024-12-04 22:05 UTC
Labels: area-vm, closed-as-intended, library-io, type-enhancement
