### ISSUE TITLE
Core lib Symbol factory does not validate argument

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#25804] opened 2016-02-18 00:21 UTC
The core lib const Symbol(String name) factory does not validate the argument and even accepts null.
See co19 test LibTest/core/Symbol/Symbol_A01_t04

**Comment by floitschG** [comment] 2016-02-18 19:21
The problem is, that this is a const constructor and therefore can't do any computations.

Dart2js checks that the const Symbols are correct, but doesn't do anything about the `new` instances.

**Comment by crelier** [comment] 2016-02-18 22:26
Good point.
Since throw is considered an expression, we could expand the spec to say that it is a const expression if it throws a constant expression.

In a const constructor, you could then write something like
_name = name is String ? name : throw const ArgumentError("name is not a String");

Something similar could be done with assert, if assert was an expression (always evaluating to true in production mode).

I talked to Gilad about this, but this is not going to change immediately, if ever. I guess we will leave this issue opened for now.

**Comment by floitschG** [comment] 2016-02-19 12:17
Actually I was wrong.
dart2js does already verify the input by redirecting calls to `new Symbol` to `new Symbol.validated`.
It just doesn't explicitly check for string or null (as is the guideline for runtime methods).

The comment in `symbol.dart` states that this is currently done for dart2js, but I guess it wouldn't be too hard to do the same thing for the VM.

**Comment by floitschG** [comment] 2017-08-22 11:21
Dart2js and the VM will have unified semantics once we have a unified frontend.

**Comment by sjindel-google** [comment] 2017-11-08 14:39
It is currently the case that the unified semantics will be incorrect. I don't see how that solves the problem of ensuring the const constructor can perform the necessary checks.

**Comment by lrhn** [comment] 2021-08-03 09:18
No longer necessary since we removed the validation from everyone else.

**Closed by lrhn** 2021-08-03 09:18 UTC
Labels: area-library, library-core, type-bug
