### ISSUE TITLE
prefer_final_fields is too eager

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29197] opened 2017-03-29 22:15 UTC
```
class Test {
  int _x = 0;
  void test() {
    final int y = _x++;
    print(y);
  }
}

void main() {
  new Test()
    ..test()
    ..test();
}
```

```
[lint] Private field could be final at test.dart:3:7 (prefer_final_fields).
```

...but `_x` can't actually be final.

**Comment by a14n** [comment] 2017-03-30 09:38
I can't reproduce this lint.

Running `pub run test -N prefer_final_fields` in https://github.com/dart-lang/linter with the following change does not fail:

```diff
diff --git a/test/rules/prefer_final_fields.dart b/test/rules/prefer_final_fields.dart
index c45ffa6..26b100b 100644
--- a/test/rules/prefer_final_fields.dart
+++ b/test/rules/prefer_final_fields.dart
@@ -80,3 +80,12 @@ class F{
     _array[0] = 3;
   }
 }
+
+class G{
+  int _x = 0; // OK
+
+  void test() {
+    final int y = _x++;
+    print(y);
+  }
+}
```

(`Pub 1.23.0-dev.10.0` and `Dart VM version: 1.23.0-dev.10.0 (Fri Mar 24 05:37:20 2017) on "linux_x64"`)

**Comment by Hixie** [comment] 2017-03-30 14:18
Maybe Flutter is behind and this was fixed recently?

**Comment by a14n** [comment] 2017-03-30 16:50
It seems to have been fixed by dart-lang/linter#508

**Comment by bwilkerson** [comment] 2017-03-30 17:08
I'm going to close this under the assumption that it's been fixed. If it still appears after updating Flutter, please re-open or file a new issue.

**Closed by bwilkerson** 2017-03-30 17:08 UTC
Labels: analyzer-linter, area-analyzer, P2 medium, Type: bug

**Comment by dnfield** [comment] 2019-01-11 07:09
I can reproduce this when `part` is used, but TBH I'm not really sure how critical it is to fix that.

ui.dart:

```dart
library dart.ui

import 'hooks.dart'
import 'window.dart'
```

hooks.dart:

```dart
part of dart.ui;

window._devicePixelRatio = 3.0;
```

window.dart:
```dart
part of dart.ui

class Window {
  Window._();
  double _devicePixelRatio = 1.0;
}

Window window = Window._();
```
