### ISSUE TITLE
Import, export default file

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51573] opened 2023-02-28 17:44 UTC
I can assume that many libraries have one file with a public interface in the lib directory (to say for sure, you need to analyze the packages on dart.dev for example). All other library files are located in lib/src and are not used by the user of the library.

With that said, I think it's not always necessary to write lines like ```import 'package:json_annotation/json_annotation.dart';``` in your code.

Is it possible to make it so that if a filename is not specified after the package name, then some file from the lib directory would be imported by default. You can make this name depend on the package name and match it. But it will be more convenient to use a file with a fixed name: index.dart, main.dart, ...

In this case, it will also be possible to specify a specific file name.

**Comment by lrhn** [comment] 2023-02-28 20:33
That is part of the shorthand suggested in https://github.com/dart-lang/language/issues/649, and is *probably* a language feature. (Unless we choose that interpreting `dart:` URIs is part of the tools instead.)

**Comment by gmb119943** [comment] 2023-02-28 21:16
Perhaps I didn't read it in detail. I just thought it would be nice to have that option. There is something similar in javascript.

Additionally, I note that for relative paths one could always require a prefix: ./src/filename, .src/filename
../src/filename
..src/filename.
If a prefix is ​​used, then when working with the IDE, prompts are displayed that are required.

**Comment by lrhn** [comment] 2023-03-01 18:51
I believe the original proposal in https://github.com/dart-lang/language/issues/649 suggested using a leading `./` or `../` for relative paths. (People did not like that.)

Closing this issue as a duplicate of the language repo issue, so put suggestions there instead. This is a language change.

**Closed by lrhn** 2023-03-01 18:51 UTC
