### ISSUE TITLE
Incorrect inlining in language/if_null/precedence_runtime_test.dart

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#41918] opened 2020-05-15 17:32 UTC
I'm migrating language_2/if_null/precedence_runtime_test.dart to NNBD [here](https://dart-review.googlesource.com/c/sdk/+/148204). When the bot runs precedence_runtime_test.dart on dart2js, [it fails here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8880277670258038160/+/steps/test_results/0/logs/new_test_failures__logs_/0):

```dart
  Expect.equals(3, null ?? null ?? 3);
```

Looking at the generated JS, that line has been compiled to:

```js
      K.Expect_equals(3, null);
```

That's clearly wrong.

**Comment by fishythefish** [comment] 2020-05-15 18:59
Haven't looked into this at all, but I suspect this may have a similar cause to #41867.

**Comment by fishythefish** [comment] 2020-05-15 20:02
Actually, let me close this as a duplicate of #41867 and provide all the updates there.

**Closed by fishythefish** 2020-05-15 20:02 UTC
Labels: NNBD, area-web, dart2js-compile-time, web-dart2js
