### ISSUE TITLE
RuntimeError: lib/convert/json_test

### ISSUE THREAD

**Issue by sgmitrovic** [dart-lang/sdk#24908] opened 2015-11-12 22:17 UTC
Windows, ia32, release mode only:

python tools/test.py -mrelease -aia32 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t60 lib/convert/json_test

FAILED: none-vm release_ia32 lib/convert/json_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stderr:
Unhandled exception:
Expect.isTrue(false, '-9.999e+203: Expected: NaN, was: -9.999e+203') fails.
#0      Expect._fail (package:expect/expect.dart:385:5)
#1      Expect.isTrue (package:expect/expect.dart:111:5)
#2      testJson.compare (file:///E:/b/build/slave/vm-win32-release-be/build/sdk/tests/lib/convert/json_test.dart:29:14)
#3      testJson.<anonymous closure> (file:///E:/b/build/slave/vm-win32-release-be/build/sdk/tests/lib/convert/json_test.dart:41:16)
#4      _SimpleCallbackSink.close (dart:convert/chunked_conversion.dart:54)
#5      _JsonStringDecoderSink.close (dart:convert-patch/convert_patch.dart:1422)
#6      testJson (file:///E:/b/build/slave/vm-win32-release-be/build/sdk/tests/lib/convert/json_test.dart:49:23)
#7      testNumbers (file:///E:/b/build/slave/vm-win32-release-be/build/sdk/tests/lib/convert/json_test.dart:117:13)
#8      main (file:///E:/b/build/slave/vm-win32-release-be/build/sdk/tests/lib/convert/json_test.dart:320:3)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

**Comment by sgmitrovic** [comment] 2015-11-12 22:25
Failure allegedly introduced with: https://codereview.chromium.org/1434213005

**Comment by fsc8000** [comment] 2015-11-13 21:25
Unable to reproduce locally, but only on the builder in release builds. The builder runs a slightly older version of MSVC than my machine. That's the only difference I could identify so far.

**Comment by fsc8000** [comment] 2016-04-12 01:10
Started passing on the buildbot. Closing as not reproducible via https://github.com/dart-lang/sdk/commit/ee510ff0856cfdd1dbf3e40f57e5971b46ce5ef5

**Closed by fsc8000** 2016-04-12 01:10 UTC
Labels: area-vm
