### ISSUE TITLE
Flaky standalone/io/regress_7191_test: Timeout

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#28374] opened 2017-01-13 00:39 UTC
standalone/io/regress_7191_test seems to sometimes timeout on vm-win-release-x64-be.

```
FAILED: none-vm release_x64 standalone/io/regress_7191_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


Command[vm]: set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart.exe --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-release-x64-be\build\sdk\.packages E:\b\build\slave\vm-win-release-x64-be\build\sdk\tests\standalone\io\regress_7191_test.dart
Took 0:01:00.019001

Short reproduction command (experimental):
    python tools/test.py -mrelease -t60 standalone/io/regress_7191_test
```

**Comment by mraleph** [comment] 2017-11-16 12:03
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Closed** 2019-02-07 16:49 UTC
Labels: area-vm, gardening
