### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#36437] opened 2019-04-02 17:33 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6183.87`
- `2.2.0`
- `IU-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 2560x1440, 1200x1920`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, error: Captured exception
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _HashSet.addAll (dart:collection/runtime/libcollection_patch.dart:628:22)
#2      _LibraryWalker.evaluate (package:analyzer/src/services/available_declarations.dart:1416:15)
#3      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#4      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#5      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#6      _LibraryWalker.walkLibrary (package:analyzer/src/services/available_declarations.dart:1462:5)
#7      DeclarationsTracker._computeExportedDeclarations (package:analyzer/src/services/available_declarations.dart:540:16)
#8      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:626:5)
#9      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:483:7)
#10     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:171:13)
<asynchronous suspension>
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#12     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#13     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#14     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#15     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#16     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#22     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#23     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#24     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#25     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#26     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#27     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/k3/rpf30xp576gd3b7wdpvvyg2r0000gn/T/report1.txt.

**Comment by a-siva** [comment] 2019-08-12 17:13
appears to be a duplicate of https://github.com/dart-lang/sdk/issues/36638

**Closed by a-siva** 2019-08-12 17:13 UTC
Labels: area-analyzer, closed-duplicate
