### ISSUE TITLE
Analayzer crash

### ISSUE THREAD

**Issue by ibanezn04** [dart-lang/sdk#35706] opened 2019-01-19 18:40 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-183.4588.61`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IU-183.4588.61, JRE 1.8.0_152-release-1343-b16x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

# Exception

Please append the contents of:
file://C:\Users\Evgenii\AppData\Local\Temp\report.txt

````
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\Evgenii\IdeaProjects\tindog\lib\main.dart context: exception_20190119_213820_930
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart;package:flutter/src/widgets/framework.dart;Key
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:983:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:929:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:954:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:28)
#8      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#9      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#10     ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#11     DeclarationResolver.visitDefaultFormalParameter (package:analyzer/src/generated/declaration_resolver.dart:127:61)
#12     DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3447:15)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#14     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4858:17)
#15     RecursiveAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:852:10)
#16     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4854:49)
#17     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2953:18)
#18     RecursiveAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:732:10)
#19     DeclarationResolver.visitConstructorDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:109:13)
#20     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#21     DeclarationResolver.visitConstructorDeclaration (package:analyzer/src/generated/declaration_resolver.dart:107:5)
#22     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2946:15)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#24     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#25     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#26     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#27     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#28     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
#29     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#30     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#31     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#32     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#33     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#34     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#35     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#36     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#37     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#38     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#39     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#40     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#41     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#42     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#43     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#44     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#45     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1025:23)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#48     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#49     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#50     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#52     _rootRun (dart:async/zone.dart:1124:13)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _runZoned (dart:async/zone.dart:1516:10)
#55     runZoned (dart:async/zone.dart:1463:12)
#56     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#57     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#58     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#59     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#60     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#61     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1547923098280 <= {"id":"11188","result":{"assists":[]}}
1547923098281 <= {"event":"analysis.highlights","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN","o
1547923098282 <= {"event":"analysis.navigation","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":29,"length":31,"
1547923098282 <= {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","labels":[{"offset":321,"length":704,"label":"MaterialApp"},{"offset":382
1547923098283 <= {"event":"analysis.outline","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>
1547923098283 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","overrides":[{"offset":280,"length":5,"superclassMember":{"element":{"kind":"
1547923098290 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547923098290 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","classes":[],"members":[]}}
1547923099186 => {"id":"11189","method":"edit.getAssists","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","offset":171,"length":0},"clientRequestTime":1547923099186}
1547923099204 <= {"id":"11189","result":{"assists":[{"message":"Convert to StatefulWidget","edits":[{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","fileStamp":0,"edits":[{"offset":
1547923099668 => {"id":"11190","method":"edit.getAssists","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","offset":206,"length":0},"clientRequestTime":1547923099668}
1547923099670 <= {"id":"11190","result":{"assists":[]}}
1547923100080 => {"id":"11191","method":"analysis.updateContent","params":{"files":{"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart":{"type":"add","content":"import 'dart:async';\n\nimport '
1547923100086 <= {"id":"11191","result":{}}
1547923100086 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547923100128 => {"id":"11192","method":"edit.getAssists","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","offset":207,"length":0},"clientRequestTime":1547923100128}
1547923100146 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","errors":[]}}
1547923100149 <= {"id":"11192","result":{"assists":[]}}
1547923100150 <= {"event":"analysis.highlights","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN","o
1547923100152 <= {"event":"analysis.navigation","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":29,"length":31,"
1547923100152 <= {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","labels":[{"offset":322,"length":704,"label":"MaterialApp"},{"offset":383
1547923100153 <= {"event":"analysis.outline","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>
1547923100154 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","overrides":[{"offset":281,"length":5,"superclassMember":{"element":{"kind":"
1547923100157 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547923100157 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","classes":[],"members":[]}}
1547923100452 => {"id":"11193","method":"analysis.updateContent","params":{"files":{"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart":{"type":"add","content":"import 'dart:async';\n\nimport '
1547923100454 <= {"id":"11193","result":{}}
1547923100457 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547923100496 => {"id":"11194","method":"edit.getAssists","params":{"file":"C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart","offset":209,"length":0},"clientRequestTime":1547923100496}
1547923101074 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: C:\\Users\\Evgenii\\IdeaProjects\\tindog\\lib\\main.dart context: exception_20190119_213820_930","stackTr
```
`

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\Evgenii\IdeaProjects\tindog\lib\main.dart context: exception_20190119_213820_930
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart

**Comment by stereotype441** [comment] 2019-01-23 18:07
Duplicate of #34555

**Closed by stereotype441** 2019-01-23 18:07 UTC
Labels: area-analyzer
