### ISSUE TITLE
use Dart analyze in Intelij error

### ISSUE THREAD

**Issue by rookielord** [dart-lang/sdk#37758] opened 2019-08-06 16:09 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4323.46`
- `2.4.0`
- `IC-182.4323.46, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

# Exception

Please append the contents of:
file://C:\Users\51042\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Could not initialize the library map from [C:\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart, C:\sdk\lib\_internal\libraries.dart]

FileSystemException(path=C:\sdk\lib\_internal\libraries.dart

**Comment by srawlins** [comment] 2019-10-16 13:28
Thanks for opening this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/34931; please follow along there.

**Comment by srawlins** [comment] 2019-10-16 13:28
Duplicate of https://github.com/dart-lang/sdk/issues/34931

**Closed by srawlins** 2019-10-16 13:28 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
