### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by humazed** [dart-lang/sdk#39365] opened 2019-11-13 13:10 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: D:\AS\ASP\Prod\FL\1FP\hilwa_water\lib\screens\checkout\payment.dart context: exception_20191113_150935_040
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:475:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#13     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#14     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#15     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#16     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#20     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#22     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:669:24)
#23     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#24     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3585:18)
#25     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#26     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#27     GeneralizingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:268:7)
#28     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3581:15)
#29     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5085:12)
#30     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#31     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#32     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#33     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#34     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:332:57)
#35     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5079:49)
#36     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#37     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#38     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#39     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#40     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#41     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#42     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#43     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#44     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#45     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#46     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#47     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#48     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#49     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#50     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#51     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#52     _IndexContrib...
```

For additional log information, please append the contents of
file://C:\Users\Dell\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-11-18 04:18
This is a duplicate of https://github.com/dart-lang/sdk/issues/38488 which has been fixed. Please update to Dart 2.6.0 or newer.

**Comment by srawlins** [comment] 2019-11-18 04:18
Duplicate of #38488

**Closed by srawlins** 2019-11-18 04:18 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
