### ISSUE TITLE
FileSystemException: Getting current working directory failed

### ISSUE THREAD

**Issue by moesaif** [dart-lang/sdk#39465] opened 2019-11-20 14:42 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.a61c775db81ef2a389d5aee6236176362b082d58`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.a61c775db81ef2a389d5aee6236176362b082d58, server version 1.27.3, error: FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files in system, errno = 23)
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:64:5)
#1      Uri.base (dart:core-patch/uri_patch.dart:21:41)
#2      current (package:path/path.dart:84:17)
#3      Context.current (package:path/src/context.dart:62:57)
#4      Context.toUri (package:path/src/context.dart:1008:43)
#5      _OverlayFile.createSource (package:analyzer/file_system/overlay_file_system.dart:222:57)
#6      FileSystemState.hasUri (package:analyzer/src/dart/analysis/file_state.dart:893:36)
#7      AnalysisDriver.getResult (package:analyzer/src/dart/analysis/driver.dart:786:19)
#8      AbstractAnalysisServer.getResolvedUnit (package:analysis_server/src/analysis_server_abstract.dart:284:10)
#9      AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:532:9)
#10     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:443:12)
#11     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:325:16)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#55     _StreamController._add (dart:async/stream_controller.dart:640:7)
#56     _StreamController.add (dart:async/stream_controller.dart:586:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7...
```

For additional log information, please append the contents of
file:///private/var/folders/x5/20z09r4x5pq2kww1qd0vsk0h0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-11-20 18:15
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/39381; please follow along there.

**Comment by srawlins** [comment] 2019-11-20 18:15
Duplicate of https://github.com/dart-lang/sdk/issues/39381

**Closed by srawlins** 2019-11-20 18:15 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
