### ISSUE TITLE
Dart Analyzer Terminated

### ISSUE THREAD

**Issue by akshaygupta1996** [dart-lang/sdk#39499] opened 2019-11-23 07:14 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.7.0-edge.521b168441143861d928c9315c9830469617028b`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.521b168441143861d928c9315c9830469617028b, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\AGS\AppData\Local\Temp\report.txt.

**Comment by akshaygupta1996** [comment] 2019-11-23 07:15
Dart analysis server, SDK version 2.7.0-edge.521b168441143861d928c9315c9830469617028b, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```
1574493242152 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1454,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/widget_test.dart","i
1574493242162 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1455,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/welcome/welcome_w
1574493242175 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1456,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/test.dart","items
1574493242178 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1457,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/successfulsignup/
1574493242180 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1458,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/signuppage/signup
1574493242182 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1459,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/signupdetails/sig
1574493242183 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1460,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/setpassword/setpa
1574493242185 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1461,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/resetpassword/res
1574493242187 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1462,"uri":"file:///C:/Users/AGS/AndroidStudioProjects/planbim-prod-mobile-app/test/ui/checkuserexists/c
1574493242189 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1463,"uri":"package:planbim/widgets/planbim_grey_button.dart","items":[{"label":"PlanBIMRowGreyButton","
1574493242191 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1464,"uri":"package:planbim/widgets/loading.dart","items":[{"label":"LoadingWidget","declaringLibraryUri
1574493242194 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1465,"uri":"package:planbim/widgets/bullet.dart","items":[{"label":"MyBullet","declaringLibraryUri":"pac
1574493242212 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1466,"uri":"package:planbim/widgets/backarrow.dart","items":[{"label":"BackArrow","declaringLibraryUri":
1574493242217 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1467,"uri":"package:planbim/screens/workspacesettings/widgets/inviteusers/bloc.dart","items":[{"label":"
1574493242221 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1468,"uri":"package:planbim/screens/workspacesettings/widgets/addremoveadmin/bloc.dart","items":[{"label
1574493242225 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1469,"uri":"package:planbim/screens/welcome/welcome_page_bloc.dart","items":[{"label":"InitialWelcomePag
1574493242228 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1470,"uri":"package:planbim/screens/welcome/bloc.dart","items":[{"label":"WelcomePageBloc","declaringLib
1574493242230 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1471,"uri":"package:planbim/screens/userdetails/userdetails_page.dart","items":[{"label":"UserDetails","
1574493242234 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1472,"uri":"package:planbim/screens/tracker/settings/bloc.dart","items":[{"label":"GetBenefitCategoryfor
1574493242236 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1473,"uri":"package:planbim/screens/tracker/roiform/bloc.dart","items":[{"label":"RoiFormBlocState","dec
1574493242238 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1474,"uri":"package:planbim/screens/tracker/roidetails/widgets/stakeholder_popup.dart","items":[{"label"
1574493242240 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1475,"uri":"package:planbim/screens/tracker/roidetails/widgets/comments_popup.dart","items":[{"label":"C
1574493242243 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1476,"uri":"package:planbim/screens/tracker/rfiform/bloc.dart","items":[{"label":"RfiFormBloc","declarin
1574493242245 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1477,"uri":"package:planbim/screens/tracker/rfi/widgets/rfi_form_widget.dart","items":[{"label":"Stakeho
1574493242332 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1478,"uri":"package:planbim/screens/tracker/rfi/bloc.dart","items":[{"label":"DataRetrievedListRFIBlocSt
1574493242335 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1479,"uri":"package:planbim/screens/tracker/issue_details/bloc.dart","items":[{"label":"DeleteIssueBlocS
1574493242337 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1480,"uri":"package:planbim/screens/tracker/issueform/bloc.dart","items":[{"label":"CreateIssuesInitialE
1574493242340 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1481,"uri":"package:planbim/screens/tracker/issue/bloc.dart","items":[{"label":"FailureIssueDetailsBlocS
1574493242341 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1482,"uri":"package:planbim/screens/successfulsignup/widgets/emailverified.dart","items":[{"label":"Emai
1574493242344 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1483,"uri":"package:planbim/screens/signupdetails/dropdownsearch.dart","items":[{"label":"YourPageState"
```

**Comment by akshaygupta1996** [comment] 2019-11-26 10:57
@dgrove Any workaround to avoid this issue. ?

**Comment by akshaygupta1996** [comment] 2019-11-28 10:53
@srawlins any workaround to avoid this issue?

**Comment by srawlins** [comment] 2019-11-30 01:10
Sorry this has not been investigated yet. You can paste a small snippet of Dart code that you think may be causing the crash. That might help understand the issue.

**Comment by akshaygupta1996** [comment] 2019-12-17 06:47
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.0
Platform: win
HTTP_PROXY: undefined
NO_PROXY: undefined

Tue Dec 17 2019 [12:15:53 GMT+0530 (India Standard Time)] Log file started
[12:15:53 pm] [General] [Info] Searching for SDKs...
[12:15:53 pm] [General] [Info] Environment PATH:
[12:15:53 pm] [General] [Info]     C:\ProgramData\DockerDesktop\version-bin
[12:15:53 pm] [General] [Info]     C:\Program Files\Docker\Docker\Resources\bin
[12:15:53 pm] [General] [Info]     C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
[12:15:53 pm] [General] [Info]     C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
[12:15:53 pm] [General] [Info]     C:\WINDOWS\system32
[12:15:53 pm] [General] [Info]     C:\WINDOWS
[12:15:53 pm] [General] [Info]     C:\WINDOWS\System32\Wbem
[12:15:53 pm] [General] [Info]     C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[12:15:53 pm] [General] [Info]     C:\WINDOWS\System32\OpenSSH\
[12:15:53 pm] [General] [Info]     C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
[12:15:53 pm] [General] [Info]     C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
[12:15:53 pm] [General] [Info]     C:\Program Files\Git\cmd
[12:15:53 pm] [General] [Info]     C:\Users\AGS\AppData\Local\Android\Sdk\platform-tools
[12:15:53 pm] [General] [Info]     C:\Program Files\dotnet\
[12:15:53 pm] [General] [Info]     C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
[12:15:53 pm] [General] [Info]     C:\Python27
[12:15:53 pm] [General] [Info]     C:\Python27\Scripts
[12:15:53 pm] [General] [Info]     C:\Program Files\Java\jdk-13.0.1\bin
[12:15:53 pm] [General] [Info]     C:\flutter\bin
[12:15:53 pm] [General] [Info]     C:\Program Files\nodejs\
[12:15:53 pm] [General] [Info]     C:\Users\AGS\AppData\Local\Microsoft\WindowsApps
[12:15:53 pm] [General] [Info]     C:\Users\AGS\AppData\Local\atom\bin
[12:15:53 pm] [General] [Info]     C:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\bin
[12:15:53 pm] [General] [Info]     C:\Users\AGS\AppData\Local\Microsoft\WindowsApps
[12:15:53 pm] [General] [Info]     C:\Users\AGS\AppData\Local\Programs\Fiddler
[12:15:53 pm] [General] [Info]     C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\bin
[12:15:53 pm] [General] [Info]     C:\Program Files\heroku\bin
[12:15:53 pm] [General] [Info]     C:\Program Files (x86)\PostgreSQL\9.6\bin
[12:15:53 pm] [General] [Info]     C:\flutter
[12:15:53 pm] [General] [Info]     C:\flutter\bin
[12:15:53 pm] [General] [Info]     C:\Users\AGS\AppData\Roaming\npm
[12:15:53 pm] [General] [Info] Found Flutter project at C:\Users\AGS\AndroidStudioProjects\planbim-prod-mobile-app:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[12:15:53 pm] [General] [Info] Searching for flutter.bat
[12:15:53 pm] [General] [Info]     Looking for flutter.bat in:
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AndroidStudioProjects\planbim-prod-mobile-app
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AndroidStudioProjects\planbim-prod-mobile-app\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin\
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AndroidStudioProjects\planbim-prod-mobile-app\.flutter
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AndroidStudioProjects\planbim-prod-mobile-app\.flutter\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AndroidStudioProjects\planbim-prod-mobile-app\vendor\flutter
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AndroidStudioProjects\planbim-prod-mobile-app\vendor\flutter\bin
[12:15:53 pm] [General] [Info]         C:\ProgramData\DockerDesktop\version-bin
[12:15:53 pm] [General] [Info]         C:\ProgramData\DockerDesktop\version-bin\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Docker\Docker\Resources\bin
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\system32
[12:15:53 pm] [General] [Info]         C:\WINDOWS\system32\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS
[12:15:53 pm] [General] [Info]         C:\WINDOWS\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\Wbem
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Git\cmd
[12:15:53 pm] [General] [Info]         C:\Program Files\Git\cmd\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Android\Sdk\platform-tools
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Android\Sdk\platform-tools\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\dotnet\
[12:15:53 pm] [General] [Info]         C:\Program Files\dotnet\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
[12:15:53 pm] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\bin
[12:15:53 pm] [General] [Info]         C:\Python27
[12:15:53 pm] [General] [Info]         C:\Python27\bin
[12:15:53 pm] [General] [Info]         C:\Python27\Scripts
[12:15:53 pm] [General] [Info]         C:\Python27\Scripts\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Java\jdk-13.0.1\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\nodejs\
[12:15:53 pm] [General] [Info]         C:\Program Files\nodejs\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\atom\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Programs\Fiddler
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Programs\Fiddler\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\heroku\bin
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\PostgreSQL\9.6\bin
[12:15:53 pm] [General] [Info]         C:\flutter
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Roaming\npm
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Roaming\npm\bin
[12:15:53 pm] [General] [Info]     Found at:
[12:15:53 pm] [General] [Info]         C:\flutter\bin\
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]     Candidate paths to be post-filtered:
[12:15:53 pm] [General] [Info]         C:\flutter
[12:15:53 pm] [General] [Info]         C:\flutter
[12:15:53 pm] [General] [Info]         C:\flutter
[12:15:53 pm] [General] [Info]         C:\flutter
[12:15:53 pm] [General] [Info]     Found at C:\flutter
[12:15:53 pm] [General] [Info]     Returning SDK path C:\flutter for flutter.bat
[12:15:53 pm] [General] [Info] Searching for dart.exe
[12:15:53 pm] [General] [Info]     Looking for dart.exe in:
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[12:15:53 pm] [General] [Info]         C:\ProgramData\DockerDesktop\version-bin
[12:15:53 pm] [General] [Info]         C:\ProgramData\DockerDesktop\version-bin\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Docker\Docker\Resources\bin
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\system32
[12:15:53 pm] [General] [Info]         C:\WINDOWS\system32\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS
[12:15:53 pm] [General] [Info]         C:\WINDOWS\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\Wbem
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[12:15:53 pm] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
[12:15:53 pm] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Git\cmd
[12:15:53 pm] [General] [Info]         C:\Program Files\Git\cmd\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Android\Sdk\platform-tools
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Android\Sdk\platform-tools\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\dotnet\
[12:15:53 pm] [General] [Info]         C:\Program Files\dotnet\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
[12:15:53 pm] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\bin
[12:15:53 pm] [General] [Info]         C:\Python27
[12:15:53 pm] [General] [Info]         C:\Python27\bin
[12:15:53 pm] [General] [Info]         C:\Python27\Scripts
[12:15:53 pm] [General] [Info]         C:\Python27\Scripts\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\Java\jdk-13.0.1\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\nodejs\
[12:15:53 pm] [General] [Info]         C:\Program Files\nodejs\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\atom\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Microsoft\WindowsApps\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Programs\Fiddler
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Local\Programs\Fiddler\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\bin
[12:15:53 pm] [General] [Info]         C:\Program Files\heroku\bin
[12:15:53 pm] [General] [Info]         C:\Program Files (x86)\PostgreSQL\9.6\bin
[12:15:53 pm] [General] [Info]         C:\flutter
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Roaming\npm
[12:15:53 pm] [General] [Info]         C:\Users\AGS\AppData\Roaming\npm\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[12:15:53 pm] [General] [Info]     Found at:
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[12:15:53 pm] [General] [Info]     Candidate paths to be post-filtered:
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[12:15:53 pm] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[12:15:53 pm] [General] [Info]     Found at C:\flutter\bin\cache\dart-sdk
[12:15:53 pm] [General] [Info]     Returning SDK path C:\flutter\bin\cache\dart-sdk for dart.exe
[12:15:53 pm] [General] [Info] Activating Flutter extension for Flutter project...
[12:15:53 pm] [General] [Info] Extension:Startup timing: 212ms
[12:15:53 pm] [General] [Info] Analyzer:Startup timing: 440ms
[12:16:02 pm] [Analyzer] [Error] Unhandled ex
[12:16:02 pm] [Analyzer] [Error] ception:
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927
[12:16:02 pm] [Analyzer] [Error] :7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_micr
[12:16:02 pm] [Analyzer] [Error] otask.dart:43:21)
#5      _startMicrotask
[12:16:02 pm] [Analyzer] [Error] Loop (dart:async/schedule_microtask.dart:52:5)
#6      _Time
[12:16:02 pm] [Analyzer] [Error] r._runTimers (dart:isolate-patch/timer_impl.dar
[12:16:02 pm] [Analyzer] [Error] t:393:30)
#7      _Timer._handleMessage (dart:isolat
[12:16:02 pm] [Analyzer] [Error] e-patch/timer_impl.dart:418:5)
#8      _RawReceive
[12:16:02 pm] [Analyzer] [Error] PortImpl._handleMessage (dart:isolat
[12:16:02 pm] [Analyzer] [Error] e-patch/isolate_patch.dart:174:12)
[12:16:20 pm] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:226)
	at c:\Users\AGS\AppData\Local\Programs\Microsoft VS…
[12:16:21 pm] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\AGS\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\AGS\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:226)
	at c:\Users\AGS\AppData\Local\Programs\Microsoft VS…

**Comment by akshaygupta1996** [comment] 2019-12-17 06:48
Will this help to find the issue @srawlins

**Comment by devoncarew** [comment] 2019-12-29 19:33
We're seeing a lot of reports of this issue; I'm going to use this report to de-dupe the others.

**Comment by devoncarew** [comment] 2019-12-29 19:37
Possibly a dupe of https://github.com/dart-lang/sdk/issues/38405?

**Comment by stereotype441** [comment] 2020-01-28 18:28
This looks like a likely duplicate of https://github.com/flutter/flutter/issues/46616 (that bug affected a lot of people, and it manifested the same way, namely, on Windows, users see the message "Cannot call write after a stream was destroyed" with no useful Dart stack trace).

Now that https://github.com/flutter/flutter/issues/46616 has been closed, I think we should wait and see whether this issue continues to come up.

**Comment by jcollins-g** [comment] 2020-02-10 16:35
https://github.com/flutter/flutter/issues/43620 seems related, but is probably a duplicate (Windows, "stream was destroyed" message, no useful trace).

**Comment by jcollins-g** [comment] 2020-02-14 16:24
Closing as we believe we've solved the underlying issue and no further reports seem to have come in.

**Closed by jcollins-g** 2020-02-14 16:24 UTC
Labels: P1, analyzer-crash-report, analyzer-server, area-analyzer
