### ISSUE TITLE
Nested class declaration

### ISSUE THREAD

**Issue by feduke-nukem** [dart-lang/sdk#56625] opened 2024-09-02 06:39 UTC
Proposal: Opportunity to declare classes inside other classes like in Kotlin:

```kotlin
sealed class SomeState<T>{
    class Loading<T> : SomeState<T>()

    data class Success<T>(val value:T) : SomeState<T>()

    data class Error<T>(val error: Throwable) : SomeState<T>()
}

fun handle(state: SomeState<Int>){
    when(state){
        is SomeState.Error -> TODO()
        is SomeState.Loading -> TODO()
        is SomeState.Success -> TODO()
    }
}
```

Dart:

```dart
sealed class SomeState<T> {
  class Loading<T> extends SomeState<T> {}

  class Success<T> extends SomeState<T> {
    final T value;

    Success(this.value);
  }

  class Error<T> extends SomeState<T> {
    final Object error;

    Error(this.error);
  }
}

void handle(SomeState<int> state) {
  switch (state) {
    case SomeState.Loading():
    case SomeState.Success():
    case SomeState.Error():
  }
}
```

Use case: to increase readability especially for sealed classes

Without such syntax we should always add "noisy" prefix/suffix to sealed subclasses' names especially when super class has long name:

```dart
sealed class SomeVeryVeryVeryLongNamedState<T> {}

class SomeVeryVeryVeryLongNamedStateLoading<T>
    extends SomeVeryVeryVeryLongNamedState<T> {}

class SomeVeryVeryVeryLongNamedStateSuccess<T>
    extends SomeVeryVeryVeryLongNamedState<T> {
  final T value;

  SomeVeryVeryVeryLongNamedStateSuccess(this.value);
}

class SomeVeryVeryVeryLongNamedStateError<T>
    extends SomeVeryVeryVeryLongNamedState<T> {
  final Object error;

  SomeVeryVeryVeryLongNamedStateError(this.error);
}

void handle(SomeVeryVeryVeryLongNamedState<int> state) {
  switch (state) {
    case SomeVeryVeryVeryLongNamedStateLoading():
    case SomeVeryVeryVeryLongNamedStateSuccess():
    case SomeVeryVeryVeryLongNamedStateError():
  }
}
```

**Comment by julemand101** [comment] 2024-09-02 07:10
This is not a Dart SDK issue but instead an issue for the Dart Specification issue tracker which can be found at: https://github.com/dart-lang/language/issues

Your issue looks like a duplicate of: https://github.com/dart-lang/language/issues/336

**Closed** 2024-09-02 07:25 UTC
Labels: area-language, type-enhancement, triage-automation
