### ISSUE TITLE
Exception from Uri constructor when a file path contains a '#'

### ISSUE THREAD

**Issue by ivancarras** [dart-lang/sdk#35134] opened 2018-11-11 18:30 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\ivi-8\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\ivi-8\Desktop\#Proyectos_Wembley_Studios\flutter_app\test\widget_test.dart
FormatException: Invalid character (at character 24)
C:/Users/ivi-8/Desktop/#Proyectos_Wembley_Studios/flutter_app/test/widget_t...
                       ^

#0      _Uri._fail (dart:core/uri.dart:1614:5)
#1      _Uri._normalize (dart:core/uri.dart:2309:11)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2265:12)
#3      _Uri._makePath (dart:core/uri.dart:2113:16)
#4      new _Uri (dart:core/uri.dart:1514:12)
#5      FileSystemState._absolutePathToFileUri (package:analyzer/src/dart/analysis/file_state.dart:980:18)
#6      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:860:28)
#7      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1185:31)
<asynchronous suspension>
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#10     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#11     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)

**Comment by srawlins** [comment] 2019-09-09 20:22
Thanks for reporting this  issue! This was previously reported at https://github.com/dart-lang/sdk/issues/34800; please follow along there.

**Comment by srawlins** [comment] 2019-09-09 20:22
Duplicate of https://github.com/dart-lang/sdk/issues/34800

**Closed by srawlins** 2019-09-09 20:22 UTC
Labels: P2, analyzer-crash-report, analyzer-server, area-analyzer, crash, type-bug
