### ISSUE TITLE
Failures on Migrator: Check dependencies with pub outdated

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#42049] opened 2020-05-26 08:30 UTC
There are new test failures on [Migrator: Check dependencies with pub outdated](https://github.com/dart-lang/sdk/commit/16b90d2085878c587ad9e60e535c6fccf16a6d3f).

The tests
```
pkg/dartdev/test/commands/migrate_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-win
```

Assigning to @srawlins and temporarily approving for now.

**Comment by srawlins** [comment] 2020-05-26 23:25
Hi @sstrickl how do I see these new failures?

**Comment by sstrickl** [comment] 2020-05-27 07:58
Sorry. The log for the failure is [here](https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win/11150/pkg/dartdev/test/commands/migrate_test). The results feed that show newly passing/failing tests per build (with links to logs by hovering over failing tests) is [here](https://dart-ci.firebaseapp.com/) for future use. :)

**Comment by athomas** [comment] 2020-05-28 10:43
I commented on the CL that landed the tests. I believe the root cause for the windows failures is the the tests assumed the executable is called `pub` on all platforms but it is `pub.bat` on Windows.

My comment is visible here:
https://dart-review.googlesource.com/c/sdk/+/148789/3/pkg/nnbd_migration/lib/migration_cli.dart

**Comment by srawlins** [comment] 2020-05-28 20:38
I've filed https://github.com/dart-lang/sdk/issues/42102.

**Closed by srawlins** 2020-05-28 20:38 UTC
Labels: analyzer-nnbd-migration, area-analyzer, gardening
