### ISSUE TITLE
Please merge 6bc1cdb5b149036f6610605921e28215fabe3d84 into dev channel

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33942] opened 2018-07-23 06:00 UTC
**commit(s) to merge**:  6bc1cdb5b149036f6610605921e28215fabe3d84

**merge instructions**: clean merge 

**reason**: This CL provides an interim workaround for the performance degradation we are seeing running internal Dart tools. Please see issues https://github.com/dart-lang/sdk/issues/33257 and https://github.com/dart-lang/sdk/issues/33915 for more context.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

**Comment by whesse** [comment] 2018-07-23 15:08
Duplicate of #33941

**Closed by whesse** 2018-07-23 15:08 UTC
Labels: area-vm, merge-to-dev
