### ISSUE TITLE
Unnecessarily cast is not unnecessarily

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/sdk#23872] opened 2015-07-20 15:01 UTC
```dart
if (hval is HNum) return (hval as HNum).val;
```

I guess it's important cast here. It's serve for refactoring purposes. What if I want to rename 'val' property? Without this cast error appears (No getter "val" on HNum class).

![screen shot 2015-07-20 at 5 58 39 pm](https://cloud.githubusercontent.com/assets/479866/8778917/23cd7a52-2f09-11e5-917e-ec719bc9f84c.png)

This issue on [JetBrains bag tracker](https://youtrack.jetbrains.com/issue/WEB-17319)

**Comment by bwilkerson** [comment] 2015-07-20 15:51
Can you send a larger code sample? The rules for when the cast is necessary depends on how the variable `hval` is declared and used in the rest of the method, and that is not shown. We need that information in order to be able to reproduce and fix the problem.

**Comment by kelegorm** [comment] 2015-07-20 15:59
```dart
Object hvalToNative(HVal hval) {
  if (hval is HNum) return (hval as HNum).val;
  if (hval is HBool) return (hval as HBool).val;
  if (hval is HStr) return (hval as HStr).val;
  if (hval is HDateTime) return new DateTime.fromMillisecondsSinceEpoch((hval as HDateTime).millis());
  //FIXME need to have null here. But Charted lib can't digest null values
  return 0;
}
```

**Comment by bwilkerson** [comment] 2015-07-20 16:11
Thanks!

I'm guessing a class structure like the following:

    class HVal {}
    class HNum extends HVal {}
    class HBool extends HVal {}
    class HStr extends HVal {}
    class HDateTime extends HVal {}

But I don't know where to define `val` or `millis()`. (Without defining them I get a warning either with or without the casts.) Can you tell me where these are declared?

**Comment by kelegorm** [comment] 2015-07-20 16:21
Yes, ti's correct class relationship. `val` is defined:
- in HNum class as num,
- in HBool class as bool,
- in HStr class as String.

`millis()` is defined in HDateTime class.

**Comment by bwilkerson** [comment] 2015-07-20 16:37
If I remove the casts (as below), then I don't see any errors, warnings or hints:

    class HVal {}
    class HNum extends HVal {
      num get val => 0;
    }
    class HBool extends HVal {
      bool get val => false;
    }
    class HStr extends HVal {
      String get val => '';
    }
    class HDateTime extends HVal {
      int millis() => 0;
    }

    Object hvalToNative(HVal hval) {
      if (hval is HNum) return hval.val;
      if (hval is HBool) return hval.val;
      if (hval is HStr) return hval.val;
      if (hval is HDateTime) return new DateTime.fromMillisecondsSinceEpoch(hval.millis());
      //FIXME need to have null here. But Charted lib can't digest null values
      return 0;
    }

What am I missing?

**Comment by kelegorm** [comment] 2015-07-20 17:05
'if'. You missed 'if' in first message. 

Yes, there are some improvements in code checking and now there is not warnings like 'class HVal has not property with name "val"'.

But there is ready-for-refactirng problem. Try make refactoring: rename 'val' property (to 'value') in any class and you get error: "class HNum has not 'val' property" because refactoring tool skips places without casting.

**Comment by bwilkerson** [comment] 2015-07-20 17:27
Ah! Now I understand, thanks!

**Comment by alexander-doroshko** [comment] 2015-07-20 17:34
That's probably a problem at refactoring side, but not at analysis side. Analysis in WebStorm uses data from Analysis Server. Refactorings for now are implemented at WebStorm side. First we should see how DAS suggests to perform refactoring. If DAS doesn't need explicit cast to rename correct val then warning about unnecessary cast is valid and refactoring should be fixed at WebStorm side.

**Comment by kelegorm** [comment] 2015-07-20 17:35
It's problem for WebStorm or for Dart Analysis: WebStorm should see property usage without casing and make refactoring properly or casting should not to be warning.

**Comment by bwilkerson** [comment] 2015-07-20 17:39
> First we should see how DAS suggests to perform refactoring.

DAS correctly renames the one reference to the getter without updating the others. I believe the problem is that the WebStorm resolver doesn't do type promotion, and hence has the wrong type for `val`.

**Comment by alexander-doroshko** [comment] 2015-07-20 17:41
Thanks for the update.
Yes, WebStorm should resolve and rename field based on type check in surrounding code (if (hval is HNum)...). At some point we are going to try to switch WebStorm from its own resolution and refactorings to ones provided by the Dart Analysis Server. When it's done all questions disappear.
Looks like this issue can be closed. The real request is to improve rename at WebStorm side.

**Comment by bwilkerson** [comment] 2015-07-20 17:45
Thanks, Alex!

**Closed by bwilkerson** 2015-07-20 17:45 UTC
Labels: Analyzer-Hint, Area-Analyzer, Priority-High, Type-Defect
