### ISSUE TITLE
[vm/ffi] Error in analyzer when argument of Array.multi() is not a literal

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#45537] opened 2021-03-31 07:44 UTC
The following code works in CFE but produces an error in analyzer

```dart
import "dart:ffi";

const arr = [3, 1];

class MyStruct extends Struct {
  @Array.multi(arr) // in analyzer "error - 'Array's must have an 'Array' annotation that matches the dimensions."
  external Array<Array<Int8>> a0; 

  @Array.multi([3, 1]) // no issue
  external Array<Array<Int8>> a1; 

}

void main() {
  MyStruct? ms = null;
}
```

`Dart SDK version: 2.13.0-165.0.dev (dev) (Thu Mar 25 02:53:52 2021 -0700) on "windows_x64" `

What tool behaves in a right way here?

cc @dcharkes

**Comment by dcharkes** [comment] 2021-03-31 08:19
Duplicate of https://github.com/dart-lang/sdk/issues/45507.

The analyzer did not evaluate the constants and expected literals.

This was fixed in https://github.com/dart-lang/sdk/commit/4ba4fd3f1d2448cb8e3ef8788d5c079d2c5fea93 yesterday.

Thanks for reporting!

**Closed by dcharkes** 2021-03-31 08:19 UTC
Labels: area-vm, library-ffi
