### ISSUE TITLE
Function type issue with --preview-dart-2

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32195] opened 2018-02-16 13:05 UTC
```
class RxStore extends Store<RxApp, RxAppBuilder, RxAppActions> {
  RxStore(
      {Reducer reducer,
      RxApp defaultState,
      RxAppActions actions,
      Iterable<Middleware<RxApp, RxAppBuilder, RxAppActions>> middleware})
      : super((reducer ?? RxApp.reducer().build()) as Reducer,
            defaultState ?? new RxApp(), actions ?? new RxAppActions(),
            middleware:
                middleware ?? [loggingMiddleware, errorReporterMiddleware]);
}
```

From the `built_redux` package https://github.com/davidmarne/built_redux/blob/d1e8e381be0d36b13d82af0403e26e30d4ed7b6d/lib/src/store.dart#L13

```dart
 Actions extends ReduxActions> {
  // stream used to dispatch changes to the state
  final StreamController<StoreChange<State, StateBuilder, dynamic>>
      _stateController = new StreamController.broadcast();

  // the current state
  State _state;
  Actions _actions;

  Store(
    Reducer<State, StateBuilder, dynamic> reducer,
    State defaultState,
    Actions actions, {
    Iterable<Middleware<State, StateBuilder, Actions>> middleware: const [],
  }) {
```

causes 
```
error: type '(RxApp, Action, RxAppBuilder) => Null' is not a subtype of type '(Built<Built<Built, Builder>, Builder<Built, Builder>>, Action, Builder<Built<Built, Builder>, Builder<Built, Builder>>) => void' in type cast
```
at 
```dart
: super((reducer ?? RxApp
```

```
 $ flutter doctor -v
[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-AT, channel dev)
    • Flutter version 0.1.2 at /Users/zoechi/flutter/flutter
    • Framework revision 8a65872ef9 (2 days ago), 2018-02-13 23:32:28 -0800
    • Engine revision 05c5f817eb
    • Tools Dart version 2.0.0-dev.22.0
    • Engine Dart version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c
```
Nothing urgent. I was just trying `--preview-dart-2`

**Comment by mraleph** [comment] 2018-02-16 13:17
@zoechi can you post completely reproduction? some of your code seems to be cut off (e.g. ` Actions extends ReduxActions> {`).

In general I suspect that the error is an absolutely correct Dart 2 error and the code needs to be updated. If you post the whole code we can figure out how to update it.

Right now I see the same type `Reducer` is used with and without type arguments. In Dart 1 you had `Reducer reducer` treated as `Reducer<dynamic, dynamic, dynamic>` and fuzzy arrows would allow you to put any concrete reducer into such a variable. However in Dart 2 you can't treat function taking something concrete (i.e. `(Something) -> ...`) as a function taking anything (i.e. `(dynamic) -> ...`). Furthermore `Reducer` is no longer treated as a `Reducer<dynamic, dynamic, dynamic>`, but instead it is instantiated to bounds.

**Comment by mraleph** [comment] 2018-02-16 13:55
Note: [`Reducer`](https://github.com/davidmarne/built_redux/blob/master/lib/src/typedefs.dart#L8-L11
) is a recursive type. 

```dart
/// [Reducer] is a function that given a state of type V, an Action of type Action<P>, and a
/// builder of type B builds the next state
typedef void Reducer<
    State extends Built<State, StateBuilder>,
    StateBuilder extends Builder<State, StateBuilder>,
    Payload>(State state, Action<Payload> action, StateBuilder builder);
```

@leafpetersen can you help clarify what instantiate to bounds supposed to yield for such a type?

Currently it seems to be yielding `(Built<Built<Built, Builder>, Builder<Built, Builder>>, Action, Builder<Built<Built, Builder>, Builder<Built, Builder>>) => void` which hardly seems correct.

**Comment by eernstg** [comment] 2018-02-16 14:26
The algorithm used to instantiate-to-bound for a type alias should be the same as the one used for a generic class. Checking a class with the same structure:
```dart
class A<X> {}
class B<X, Y> {}
class C<X, Y> {}

class R<X extends B<X, Y>, Y extends C<X, Y>, D> {}

main() {
  print(new R().runtimeType);
}
```
we get the following error:
```
Analyzing n019.dart...
  error • Couldn't infer type parameter 'X'.

Tried to infer 'B<dynamic, dynamic>' for 'X' which doesn't work:
  Type parameter 'X' declared to extend 'B<B<dynamic, dynamic>, C<B<dynamic, dynamic>, dynamic>>'.

Consider passing explicit type argument(s) to the generic.

 at n019.dart:10:13 • strong_mode_could_not_infer
1 error found.
```
So that's already one data point.

**Comment by mraleph** [comment] 2018-02-16 15:40
I talked to @eernstg and his analysis indicates that there is a bug in the instantiate to bounds for recursive types. Can you take a look @kmillikin @stefantsov?

**Comment by stefantsov** [comment] 2018-02-16 16:06
It may be due to https://github.com/dart-lang/sdk/issues/31778.

**Comment by zoechi** [comment] 2018-02-16 18:42
@mraleph thanks! Adding the type parameters to the `Reducer...` parameter fixed it.

**Comment by leafpetersen** [comment] 2018-02-16 18:48
Yowzer, that's quite  type.

The correct default instantiation for:
```
typedef void Reducer<
    State extends Built<State, StateBuilder>,
    StateBuilder extends Builder<State, StateBuilder>,
    Payload>(State state, Action<Payload> action, StateBuilder builder);
```

should be:

```
Reducer<Built<dynamic, dynamic>, Builder<dynamic, dynamic>, Payload>
```

Because `State` and `StateBuilder` form a connected component, so they each get replaced with `dynamic` in each other's bounds.

**Comment by mraleph** [comment] 2018-02-17 13:14
Moving to area-front-end and assigning to @stefantsov to fix the instantiate to bounds algorithm.

**Comment by eernstg** [comment] 2018-02-19 10:15
> .. instantiation .. should be:
```dart
Reducer<Built<dynamic, dynamic>, Builder<dynamic, dynamic>, Payload>
```

I guess that would be `dynamic` rather than `Payload` at the end, but that is actually not exactly what the feature specification says: It breaks each cycle by replacing _one_ variable by `dynamic`/`Null` in all bounds in the cycle, it does not replace all variables in the cycle by `dynamic`/`Null`, and it does not replace occurrences in bounds outside the cycle (check the first bullet point after the only occurrence of the word 'determined' in the [feature spec](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md): it only replaces `Xj`).

We did go back and forth on this several times&mdash;I actually started out specifying an approach that would insert `dynamic`/`Null` even more aggressively. When I made the insertion of `dynamic`/`Null` less aggressive, the purpose was to preserve more typing information (cf. the examples in the feature spec [super-bounded-types.md](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/super-bounded-types.md) where `c0.next.unknown(42)` is accepted because `c0.next` is `dynamic`, but `c1.next.unknown(43)` is a compile-time error, and the only difference is that the type of `c1` is unfolded one level deeper than the type of `c0`).

But if ddc "breaks cycles everywhere" rather than "breaks each cycle at one point" then this would also be the expectations embedded in the existing software (which may be taken as a hint that, in practice, it isn't too aggressive in "making everything too `dynamic`"), so we might then want to amend the feature spec rather than the implementation in ddc. It does also ensure a greater degree of symmetry when we treat every point in a connected component identically.

WDYT?

**Comment by eernstg** [comment] 2018-02-19 10:23
PS: Here's one strong hint that things have changed in this particular area: The feature spec contains the following 'commentary' sentence right after the more formal specification in the above-mentioned bullet point: 'That is, we update the bounds of type variables in the dependency cycle such that the type variables in the dependency cycle are replaced by `Null` or `dynamic`, depending on the variance of the location'. That sounds a lot like all variables in the cycle are replaced. ;-)

**Comment by leafpetersen** [comment] 2018-02-21 00:47
Yes, it was definitely my intention and understanding that we would replace all simultaneously, but agreed that the feature spec doesn't say that.  Clearly I didn't read closely enough.  :(  I do think this is the right thing to do - it's a much simpler mental model, and I think less brittle.  Getting a different answer because of the order of declaration of otherwise unordered things seems bad to me.

**Comment by stefantsov** [comment] 2018-03-14 10:35
I believe the issue is resolved by https://github.com/dart-lang/sdk/commit/8c82c3b5fe80f2870ad9780b06d84fa35f35257c.

**Closed by stefantsov** 2018-03-14 10:35 UTC
Labels: Customer-Flutter, area-front-end
