### ISSUE TITLE
Unable to pass a method with a down-cast parameter

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#29064] opened 2017-03-14 04:13 UTC
For example, the following code doesn't work:  
*The function 'foo1' has type '(B) → void' that isn't of expected type '(A) → void'.*

```
class A {
}
class B extends A {
}
typedef void Foo<T extends A>(T t);

void foo1(B b) => null;

const list = const <Foo> [foo1];
```

Dart version: 1.22.1

On the other hand, the following code is ok:

```
class A {
}
class B extends A {
}
typedef void Foo<T extends A>(T t);

class C {
  void on<T extends A>(void handle(T t)) {}
}

void foo1(B b) => null;

void f(C c) {
  c.on(foo1);
}
```

**Comment by lrhn** [comment] 2017-03-14 06:48
I'm guessing you are using strong mode.

The expression `const<Foo>[foo1]` tries to figure out what you mean by `Foo`. Since `Foo` is a generic typedef, it has to instantiate it to get an actual type. 
It chooses to instantiate that to the bound, so the expression has type `List<Foo<A>>`. In strong mode, the `foo1` function has type `Foo<B>` (aka `(B)->void`), which is not assignable to `Foo<A>` (aka. `(A)->void`).

One question to ask is whether it should/could have inferred `Foo<B>` as the type, based on the element of the list. It doesn't currently, it just instantiated to bounds, so a solution would be to write `const<Foo<B>>[foo1]`.


The other example is different because the `C.on` method is actually a generic function. A generic typedef like the one for `Foo` does not define a generic function type, just a generic typedef - you have to instantiate the typedef to get a (non-generice) function type. (There is new syntax that allows you to define a typedef of a generic function, if you need that, but you don't for these examples).

That means that when you call `c.on(foo1)` you do infer the method's type parameter, so you are effectively calling `c.on<B>(foo1)`, which is appropriately safe. It knows not to call the argument function with an instance of `A` since it needs a `T`.

**Comment by tomyeh** [comment] 2017-03-14 07:49
Yes, I'm using strong mode. Thanks for your quick response and clear explanation.

The real problem is that I'd like to implement a pluggable mechanism that the handler can take a subclass of the declared one (after all, it is common that we know, say, it must be MouseEvent for the click type).

Here is sample code,

```
class A {
}
class B extends A {
}
typedef void Foo<T extends A>(T t);

class C {
  final _map = <String, Foo<A>> {};
  void on<T extends A>(String type, void handler(T t)) {
    _map[type] = handler; //error
  }
}

void f(C c) {
  c..on("a", (A a) {})
   ..on("b", (B b) {});
}
```

The only way to get it around seems to ignore STRONG_MODE_DOWN_CAST_COMPOSITE, but is it safe? Any better way?

**Comment by lrhn** [comment] 2017-03-14 09:41
What if you change the assignment to:
```dart
_map[type] = (A x) => handler(x as T);
```
?
It *can* fail at runtime, but that's what you are asking for by passing a `B` handler to something that doesn't have solely `B` events. There must be some runtime logic to prevent the incorrect use since you are disabling the static checks.

Try not to ignore any strong mode errors. That's a stop-gap solution during transition, but one day, when strong mode becomes the only mode, those ignores will probably go away too. Then your code will just be broken.

I can't say what the flag actually turns off, which is another reason (at least for myself) to try to avoid it :)

**Comment by tomyeh** [comment] 2017-03-14 09:49
Yes, but it is a bit tedious since, in many cases, we do know the class shall be. For example, it is more convenient if we can do:

```
elem
   ..on('keypress', (KeyboardEvent e) {
      if (e.altKey) ...
   })
   ..on('click', (MouseEvent e) {
     if (e.button == 1) ...
```

Sure, we can cast it explicitly but really redundant if we know the type at compile time.

**Comment by lrhn** [comment] 2017-03-14 12:49
True, but then you need runtime checks, and the system can't help you because it does not know that "keypress" and `KeyboardEvent` are related, so you need to add the checks, e.g., like a wrote above with the wrapper.

**Comment by tomyeh** [comment] 2017-03-14 14:19
Understand, but possible to have some sugar syntax, like `covariant` does, to avoid the wrapping?

`e.on('keypress', (covariant KeyboardEvent e) {...`

**Comment by lrhn** [comment] 2017-03-14 14:34
We considered something like this when we introduced the `covariant` keyword, but decided against it.
Also "covariant" doesn't really match the intent when there is no variance :)

In practice, I hope our type promotion will get to the point where you can write:
```dart
e.on('keypress', (Object e) { 
  e as KeyboardEvent;
  ...
});
```
and actually have `e` be promoted to KeyboardEvent in the rest of the body.

**Comment by tomyeh** [comment] 2017-03-14 14:53
Yes, it will be very helpful (and more *accurate*). Looking forward to it:)

Thanks again for your kindly explanation.

**Comment by bwilkerson** [comment] 2017-03-15 14:12
I believe that analyzer is currently working as intended, so I'm closing this. Please re-open if you think it's worth having as a reminder of possible future enhancements to inference.

**Closed by bwilkerson** 2017-03-15 14:12 UTC
Labels: analyzer-strong-mode, area-analyzer
