### ISSUE TITLE
Converting a StatefulWidget to a StatelessWidget, then hot reloading, crashes the kernel compiler

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#36838] opened 2019-05-03 16:16 UTC
#### 1) Run the following app:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Stateless to Stateful Hot Reload Crashes App',
    home: Scaffold(
      body: SafeArea(
        child: Home(),
      ),
    ),
  ));
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Text('foo');
  }
}
```

#### 2) Once the app is started, change `Home` to be a `StatelessWidget`, like so:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Stateless to Stateful Hot Reload Crashes App',
    home: Scaffold(
      body: SafeArea(
        child: Home(),
      ),
    ),
  ));
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text('foo');
  }
}
```

## Expected behavior

You expect the app to reload, or at least if unable to reload, you expect the app to keep running and be forced to hot restart.

## Actual behavior

The Flutter engine crashes, and the app is killed.  The following log message indicates the source of the error:

```
E/Dart    ( 5164): ../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.cc: 1869: error: Unexpected tag 224 (Unknown) in ?, expected a procedure, a constructor or a function node
```

This was observed on https://github.com/flutter/engine/commit/30639ee7b6a3c0ea6afa7ffcdbd11254b069431f (running Dart version https://github.com/dart-lang/sdk/commit/1577b95c93823339150736e8c54f4524da4339be)

**Comment by aam** [comment] 2019-05-04 00:22
I believe until https://dart-review.googlesource.com/c/sdk/+/97561 landed this used to produce "CompileTimeError":
```
[   +2 ms] Sending to VM service: ext.flutter.reassemble({isolateId: isolates/120905974})
[ +283 ms] I/flutter (28105): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +20 ms] I/flutter (28105): The following _CompileTimeError was thrown building Home(dirty, state: _HomeState#fd1e4):
[        ] I/flutter (28105): 'package:a/main.dart': error: Unexpected tag 0 (Nothing) in ?, expected a procedure, a constructor
[        ] I/flutter (28105): or a function node
[        ] I/flutter (28105): 
[        ] I/flutter (28105): When the exception was thrown, this was the stack:
[  +15 ms] I/flutter (28105): #0      StatefulElement.build (package:flutter/src/widgets/framework.dart:3824:27)
[        ] I/flutter (28105): #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3735:15)
[        ] I/flutter (28105): #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3558:5)
[        ] I/flutter (28105): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2271:33)
[        ] I/flutter (28105): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:700:20)
[        ] I/flutter (28105): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:275:5)
[   +1 ms] I/flutter (28105): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1008:15)
[        ] I/flutter (28105): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:948:9)
[        ] I/flutter (28105): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:769:7)
[        ] I/flutter (28105): #10     _Timer._runTimers (dart:isolate/runtime/lib/timer_impl.dart:382:19)
[        ] I/flutter (28105): #11     _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:416:5)
[        ] I/flutter (28105): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
[        ] I/flutter (28105): (elided one frame from package dart:async)
[        ] I/flutter (28105): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +115 ms] Result: {type: _extensionType, method: ext.flutter.reassemble}
[   +4 ms] Initializing hot reload... (completed in 962ms)
[        ] Reloaded 1 of 438 libraries in 966ms.
```

The fact that this was 'CompileTimeError' I believe was misleading because it is actually internal vm problem that needs to be fixed. I will look back at when it regressed(I assume it is a regression).

**Comment by aam** [comment] 2019-05-07 23:13
https://dart-review.googlesource.com/c/sdk/+/101625 with the fix.

**Closed** 2019-05-07 23:16 UTC
Labels: customer-flutter
