### ISSUE TITLE
VM dart:io connection failed SocketException reports unhelpful port number

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#47660] opened 2021-11-09 13:10 UTC
Dart SDK version: HEAD/google3

```
import 'dart:io';

void main() {
  Socket.connect('localhost', 55432);
}
```

Expected: SocketException with port 55432
Actual behaviour: looks like it reports the _send_ port, not the _target_ port; so we get a SocketException with random port.

In debugging some end to end tests this send us on a long detour where we couldn't figure out why the test was trying to connect to a seemingly random port--when in fact it was trying to connect _from_ a random port, and knowing the _target_ port would have helped a lot :)

Thanks.

**Comment by sortie** [comment] 2021-11-09 14:33
This is a duplicate of #12693, quite the old bug. I began fixing it in https://dart-review.googlesource.com/c/sdk/+/127465 but never found the cycles to get over the finish line with the breaking change request.

**Comment by a-siva** [comment] 2021-11-12 23:44
@sortie do you have cycles to take your CL thru the review and breaking change process and land it or do you want somebody else to takeover and work on it ?

**Comment by a-siva** [comment] 2021-11-12 23:45
closing this as a duplicate of #12693

**Closed** 2021-11-12 23:45 UTC
Labels: area-library, closed-duplicate, library-io, type-enhancement
