### ISSUE TITLE
Intellij cannot autocomplete the dart syntaxes

### ISSUE THREAD

**Issue by mposada** [dart-lang/sdk#35023] opened 2018-11-01 21:03 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4892.20`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.4892.20, JRE 1.8.0_152-release-1248-b19x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/rodmi3h/Documents/miguel/flutter/miguel_demos/lib/main.dart context: exception_20181101_160132_299
Exception: Element not found in summary: dart:core

**Comment by stereotype441** [comment] 2018-11-06 20:32
Duplicate of #34555

**Closed by stereotype441** 2018-11-06 20:32 UTC
Labels: area-analyzer
