### ISSUE TITLE
Dart Analysis Error Flutter

### ISSUE THREAD

**Issue by meruavinash** [dart-lang/sdk#39255] opened 2019-11-06 06:29 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, error: Captured exception
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      scannerRecovery (package:front_end/src/fasta/scanner/recover.dart:31:17)
#2      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:103:14)
#3      scanString (package:front_end/src/fasta/scanner.dart:95:10)
#4      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:146:34)
#5      _File._parse (package:analyzer/src/services/available_declarations.dart:1838:25)
#6      _File.refresh (package:analyzer/src/services/available_declarations.dart:1163:30)
#7      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:660:14)
#8      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:695:16)
#9      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#10     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:281:13)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#12     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:280:27)
#13     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#23     Monitor.signal (package:analyzer/src/dart/analysis/status.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#30     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\merua\AppData\Local\Temp\report.txt.

**Comment by keertip** [comment] 2019-11-06 09:12
Thanks for reporting this issue! This was previously reported at #38405, please follow along there

**Comment by keertip** [comment] 2019-11-06 09:12
Duplicate of #38405

**Closed** 2019-11-06 09:12 UTC
Labels: analyzer-crash-report, area-analyzer, area-front-end
