### ISSUE TITLE
Unfortunate rendering of hover text

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#46788] opened 2021-08-02 18:13 UTC
I just saw the following unfortunate rendering of hover text

![image](https://user-images.githubusercontent.com/5840555/127905193-d0f5429c-dfaa-4065-a739-5f8310aac388.png)

The response from the analysis server contains the following (note the `elementDescription`
```
1627927502451:Res:{"id"::"1190","result"::{"hovers"::[{
  "offset"::33199,
  "length"::10,
  "containingLibraryPath"::".../sdk/pkg/analysis_server/tool/code_completion/completion_metrics.dart",
  "containingLibraryName"::"tool/code_completion/completion_metrics.dart",
  "containingClassDescription"::"CompletionMetrics",
  "elementDescription"::"Map<String, Map<int, int>> placeCount",
  "elementKind"::"field","isDeprecated"::false,"staticType"::"Map<String, Map<int, int>>"
}]}}
```

(Part of the `containingLibraryPath` was removed by me so that it would format better, but the full path was in the actual response.)

**Comment by jwren** [comment] 2021-08-16 22:45
@bwilkerson 

Hover text support forks at `2.14`, see https://github.com/Dart-Code/Dart-Code/issues/3357, and the associated PRs for the Dart Plugin.  Which version of the Dart SDK did this come from, does it come from the latest, `2.14+`?

**Comment by bwilkerson** [comment] 2021-08-16 22:51
Sorry, I should have captured that information. I was likely an SDK built from head within a couple of days of the original report. The code that triggered the behavior was on a branch. I'll see whether I can reproduce it.

**Comment by bwilkerson** [comment] 2021-08-18 15:25
I was using the following version on Linux:

```
IntelliJ IDEA 2021.1.3 (Community Edition)
Build #IC-211.7628.21, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.40-1rodete2-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 5011M
Cores: 16
Registry: caches.indexerThreadsCount=24, ide.index.image.max.size=0, ide.old.project.model=true
Non-Bundled Plugins: Dart (211.7727)
Kotlin: 211-1.4.32-release-IJ7628.19
Current Desktop: X-Cinnamon
```

I have not reproduced it on my Mac, but I'm using the same version:

```
IntelliJ IDEA 2021.1.3 (Community Edition)
Build #IC-211.7628.21, built on June 29, 2021
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: dart.server.additional.arguments=--port=10010 --instrumentation-log-file=/Users/brianwilkerson/temp/serverLog/instrumentation.log, debugger.watches.in.variables=false, dart.server.vm.options=--observe=8181 --enable-vm-service --pause_isolates_on_unhandled_exceptions=true --disable-service-auth-codes, max.suggested.heap.size=4096
Non-Bundled Plugins: Dart (211.7727)
Kotlin: 211-1.4.32-release-IJ7628.19
```

**Comment by jwren** [comment] 2021-12-20 23:28
Closing-- can't reproduce with latest Dart Plugin and Dart SDK.

**Closed** 2021-12-20 23:29 UTC
Labels: area-intellij
