### ISSUE TITLE
Analyzer-Server does not recognize a file rename

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28097] opened 2016-12-14 11:51 UTC
I had a file WebAppConfig_test, I renamed it to AbstractConfig_test - Analyzer-Server still shows an error in WebAppConfig_test although it's not there anymore

![capturfiles-20161214_124618](https://cloud.githubusercontent.com/assets/116654/21180991/f0e2c67e-c1fb-11e6-96a6-65f22f4cd867.png)

**Comment by bwilkerson** [comment] 2016-12-14 15:05
There are two possible reasons for this that I can think of: either server is not telling the client to flush errors for the file, or the client is not correctly flushing them. Do you have an instrumentation log file showing the communications between client and server that you could send us so that we can figure out which of those is happening?

**Comment by natebosch** [comment] 2018-08-24 00:17
Closing as not reproducible since we don't have the instrumentation log. If this is still happening please add a comment and we can reopen.

**Closed by natebosch** 2018-08-24 00:17 UTC
Labels: analyzer-server, area-analyzer, p2-medium, type-bug
