### ISSUE TITLE
num.remainder static type

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#32645] opened 2018-03-22 21:17 UTC
```
Dart VM version: 2.0.0-edge.8abeb56ebb35896754a1014da4415d570fd7c474 (Tue Mar 20 21:24:56 2018 +0000) on "linux_x64"
```

**foo.dart**
```dart
void main() {
  final a = 5 % 2;
  final b = 5.remainder(2);

  new List<Object>(a); // <- fine
  new List<Object>(b); // <- analyzer implicit cast error
}
```

```
$  ~/dart-sdk/sdk/out/ReleaseX64/dart-sdk/bin/dartanalyzer --no-implicit-casts --strong foo.dart
Analyzing foo.dart...
  error • The argument type 'num' can't be assigned to the parameter type 'int' at foo.dart:6:20 • argument_type_not_assignable
1 error found.
```

Declarations look alike (from `num.dart`):
```dart
abstract class num implements Comparable<num> {
  num remainder(num other);

  num operator %(num other);
}
```

Probably related: https://github.com/dart-lang/sdk/issues/15650.

**Comment by lrhn** [comment] 2018-03-23 15:37
The static type of `5 % 2` is special-cased in the specification to be `int`. There is no special-casing for `5.remainder(2)`, so its static type is `num`.

Your `--no-implicit-casts` flag makes the implicit down-cast from `num` to `int` an error (it would have succeeded otherwise).

So, this is currently working as intended.

I don't know if we want to special case `intValue.remainder(intValue)` to have static type `int`. It's more palatable with special cases on operators than on general methods (not that it's actually different, just easier to specify since there is already a section about `%`.

**Comment by eernstg** [comment] 2018-03-23 16:53
This is a funny little typing twist. You could say that `%` is handled as if it had an intersection type. Let us consider a regular function and assume that it gets the same treatment:

```dart
Object f(Object o) {
  if (o is int) return "Hello!";
  if (o is String) return true;
  return <Symbol, double>{};
}
```

Obviously, `f` can soundly be given the type `Object Function(Object)`, but it will also reliably satisfy the expectations for `String Function(int)` and `bool Function(String)`, so if only the type checker could understand it then we could allow stuff like the following (`--no-implicit-casts` included):

```dart
Object o = f(<Future<void>>[null]);
String s = f(42);
bool b = f(s);
Object Function(Object) g1 = f;
String Function(int) g2 = f;
bool Function(String) g3 = f;
```

The point is that the intersection type allows us to detect that "we know more than the required minimum" at the type level, so we may be able to conclude more about the returned value because we know that we can choose a particular operand from that intersection (when an object `o` has an intersection type `T1 & T2 .. & Tk` then it is safe to consider that object to have type `Tj` for any `j` that we might find useful).

In a similar way, we could consider `a % b` to be a function taking 2 arguments and returning a result, with the following type:
```dart
num Function(num, num) & int Function(int, int) & double Function(double, double)
```
so when we have two `int` operands then we can conclude that the result is an `int`, etc.

What we need in order to establish this kind of typing is the ability to promise that a certain instance method will live up to these expectations (that could be a declaration of an intersection type for that instance method), and some checks which are applied to every overriding declaration of the method.

It's not very likely that we'll ever add such a beast to the Dart type system, but it is, at least, a useful line of thinking for me when I'm trying to understand what it is that we are doing with `%`. ;-)

**Comment by lexaknyazev** [comment] 2018-03-23 17:08
Given that the first operand is always non-negative integer and the second operand is always positive integer in my case, what approach should I use (implying that static return type will remain `num`)?

**JS native remainder but with declaration cast**
```dart
final int rem = x.remainder(y); 
var byte = data[rem];
```

**No cast but modulo instead of %**
```dart
final rem = x % y;
var byte = data[rem];
```

**Comment by eernstg** [comment] 2018-03-23 17:27
I'm not quite sure I understand this (how did JS native stuff enter the picture, and what is a declaration cast?). I'll have to run now, but I'll take a look on Monday.

**Comment by lexaknyazev** [comment] 2018-03-23 17:39
`num.remainder` is being compiled to JS `%` operator:
https://github.com/dart-lang/sdk/blob/96b76aa4fb0a5290193f14de14f0cc087e02cf32/sdk/lib/_internal/js_runtime/lib/js_number.dart#L53-L56

while `num operator %` results in:
https://github.com/dart-lang/sdk/blob/96b76aa4fb0a5290193f14de14f0cc087e02cf32/sdk/lib/_internal/js_runtime/lib/js_number.dart#L268-L279

[Declaration cast](https://github.com/dart-lang/sdk/commit/1eb480d2667fa3abe3d290dbceca268f73e078c1) means that type of `rem` is being set explicitly:
```dart
final rem = x.remainder(y); // static type num
final int rem = x.remainder(y); // static type int
```
I'm not sure about runtime implications.

**Comment by lexaknyazev** [comment] 2018-03-26 08:46
Probably related: https://github.com/dart-lang/sdk/issues/28249.

**Comment by eernstg** [comment] 2018-03-26 12:35
Thanks for the extra explanations! I don't know the concrete details about the performance implications of this choice (and your explanations seem to imply that the context is the web), but there is a top-down argument which should apply on all platforms: Given that `x % y` is specified to have type `int` when both operands are of type `int`, it's already a given that there is no need for a dynamic type check when that result is assigned to an `int` variable. This means that the dynamic type check associated with a downcast from `num` to `int` is avoided altogether.

It's possible for an implementation to treat `remainder` in the same way, even though it is not specified that it must be done that way (at least, I can't see why a correct implementation of Dart would be _forced to not_ use that optimization), but since it isn't specified we cannot know for sure that this optimization is applied.

I suspect that the raw computational content of `%` and `remainder` is comparable.

With that, `x % y` would be the safe bet, though the difference might be small or non-existent.

**Comment by lrhn** [comment] 2020-09-30 21:17
Will be fixed with null safety.

**Closed by lrhn** 2020-09-30 21:17 UTC
Labels: area-library, library-core
