### ISSUE TITLE
VM service protocol returns null for the Script.source field

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#34666] opened 2018-10-03 20:18 UTC
Starting between version  dart-sdk_2.1.0-dev.6.0 and the current master (878779e1a291110d7543fae5a8cca721a3b00c44) of the Dart SDK, Dart debugging has stopped working with the Dart Plugin for IntelliJ.

![screenshot from 2018-10-03 13-11-07](https://user-images.githubusercontent.com/1533520/46436678-4c65a700-c70e-11e8-8040-5c0af0521a9b.png)

To reproduce it
- Build the Dart SDK from sources, from master
- point the Dart Plugin for IJ at the built SDK
- Attempt to debug, even with a simple (Console App sample) dart application, debugging will fail
- To see the exception below locally, select Help > Show Log in Files

The source/ stack trace from the Intellij source is:

https://github.com/JetBrains/intellij-plugins/blob/1cc378a9a8559b3d7c7e1a8ae22213ba9189bd00/Dart/thirdPartySrc/vmServiceDrivers/org/dartlang/vm/service/element/Script.java#L43

```
java.lang.NullPointerException
	at org.dartlang.vm.service.element.Script.getSource(Script.java:43)
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcess.getSourcePosition(DartVmServiceDebugProcess.java:547)
	at com.jetbrains.lang.dart.ide.runner.server.vmService.frame.DartVmServiceStackFrame.<init>(DartVmServiceStackFrame.java:46)
	at com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$9.lambda$received$0(VmServiceWrapper.java:424)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment] 2018-10-03 20:50
For this to happen, the service protocol `Script` `source` field must be null; we don't handle that case (we assume that all scripts return populated with their source).

**Comment by a-siva** [comment] 2018-10-03 20:55
In Dart1 we used to generate sources for dart core libraries using the TokenStream but in Dart 2 we do not have the notion of a TokenStream and hence it returns null for Source. The caller should handle this and not try to display the source in this case.

**Comment by mraleph** [comment] 2018-10-04 06:43
@a-siva should not the source still be embedded into the Kernel binary? or do we strip it now? This (debugging core libraries in Dart 2 mode) used to work at some point.

**Comment by a-siva** [comment] 2018-10-05 01:30
Need to investigate what changed recently in this regard, I don't believe anything changed with regards to compilation of platform file, will check tomorrow.

**Comment by devoncarew** [comment] 2018-10-08 00:02
@a-siva, I haven't tested exhaustively, but it could be that the `Script.source` field always returns `null` now. I didn't notice this initially as we generally don't ask for the source for files we can locate on disk.

If this is the case, we should raise the priority of this issue (and bisect to find when it regressed).

**Comment by devoncarew** [comment] 2018-10-08 00:03
Bumping in priority w/ the assumption that this field is no longer populated.

**Comment by jwren** [comment] 2018-10-08 18:46
@stereotype441 just reported this issue to me, mentioned that it looks like the issue started with commit 76470aca476c40e1e7a7ee50037e85f0a20945d2:

Author: asiva <asiva@google.com>
Date:   Thu Sep 27 00:55:07 2018 +0000

    [VM] use coresnapshot when initializing an Isolate
    
    - use core snapshot when initializing an isolate (CorelibIsolateStartup benchmark moves from 39s to 2s)
    - remove use_dart_frontend flag from the isolate specific flags
    - the script snapshot API functions now return an error
    
    Change-Id: Ia562e007fdbfd1d3ebd8e1a0c8feee238bada00b
    Reviewed-on: https://dart-review.googlesource.com/76709
    Commit-Queue: Siva Annamalai <asiva@google.com>
    Reviewed-by: Ryan Macnak <rmacnak@google.com>

**Comment by a-siva** [comment] 2018-10-08 19:49
Is the query for sources of core library files or sources of application files?

**Comment by devoncarew** [comment] 2018-10-08 22:33
Removing the P1 label; I do see the source field populated for application code in a running Flutter app.

For the case above, I was testing against a running Dart CLI app, but running from an AppJIT snapshot. In that trained snapshot case, it's not expected to be able to retrieve the source.

**Comment by stereotype441** [comment] 2018-10-09 15:31
@devoncarew If this is only happening for you with an AppJIT snapshot, then it's different from the problem I saw.  The problem I saw affects an ordinary program run from source using IntelliJ, and it manifests as the stacktrace completely failing to appear when the user hits a breakpoint.  IMO that's a P1 issue, and required for 2.1.  Let's confer in person to see if we're looking at the same bug--if we're not, I can file a separate issue for what I'm seeing.

**Comment by a-siva** [comment] 2018-10-09 15:33
Is this still a problem?

**Comment by stereotype441** [comment] 2018-10-09 15:44
@a-siva As of 3d064270750a935d464a93339a83577dc606e80c, I'm still seeing a problem viewing a stacktrace in the IntelliJ debugger.  I'll confer with @devoncarew or @jwren as soon as one of them is free to see if the bug I'm seeing should be tracked as a separate issue.

**Comment by devoncarew** [comment] 2018-10-09 15:51
> Is this still a problem?

Yes, in that both the Dart debugger and Flutter debuggers are currently broken as a result of this change. We're now handling nulls for `Script.source` upstream in the Dart plugin and Flutter plugin, but need to release new versions of each with the fix.

pinging @alexander-doroshko for the Dart plugin; I'll file a tracking issue on the flutter-intellij repo for the Flutter plugin

**Comment by stereotype441** [comment] 2018-10-09 16:58
Update after an in-person conversation with @devoncarew, @jwren, and @bwilkerson: this is a blocker for 2.1, because debugging with IntelliJ/Android Studio is currently broken.  We believe this can be addressed by releasing new versions of the Dart and Flutter plug-ins.  Assuming that can be done quickly, there is no need to revert the VM change.  If it can't be done quickly for some reason, we may need to consider hacking in a VM change that causes dummy script contents to be returned; hopefully that won't be necessary.

Accordingly, I'm re-adding the P1 label.  Once new plugins are released, this will no longer be a release blocker and we can remove the label again.

**Comment by devoncarew** [comment] 2018-10-09 20:44
An update: we've released a new version of the Flutter plugin w/ the fix for this. We still need to release a new version of the Dart plugin.

**Comment by a-siva** [comment] 2018-10-09 20:49
assigning to Devon to track the release of a new Dart plugin.

**Comment by yjbanov** [comment] 2018-10-09 21:00
This issue is transitively blocking the new `mixin` syntax rollout because it's blocking the internal Dart SDK release.

**Comment by devoncarew** [comment] 2018-10-10 14:53
Alex has release new versions of the Dart plugin (thanks @alexander-doroshko !); closing this issue.

**Closed by devoncarew** 2018-10-10 14:53 UTC
Labels: area-intellij, p1-high, vm-debugger

**Comment by mraleph** [comment] 2018-10-10 15:56
Are we fine that people can no longer step into core libraries or do we consider this to be an UX regression?

**Comment by devoncarew** [comment] 2018-10-10 16:01
There is a lot of room for improvement in terms of debugging `dart:` libraries. It would be nice to have a clear mapping of the `dart:` libraries running on the VM and those in the sdk, so that we can have breakpoints persist across sessions. It would also be nice to be able to retrieve source for appjit snapshot apps.

In this case, we can retrieve source for most `dart:` libraries, but have regressed for some specific libraries; I haven't dug into which ones specifically.

**Comment by Christian-AT** [comment] 2018-10-11 10:39
This issue also appears to affect dart sdk 2.1.0-dev.7.0 with WebStorm (vers 2018.2.4, build #WS-182.4505.50).

Same java.lang.NullPointerException thrown as reported by @jwren .

![debugger_hangs](https://user-images.githubusercontent.com/39693721/46798228-a4755c80-cd51-11e8-9e89-6a023f0ee160.PNG)

**Comment by devoncarew** [comment] 2018-11-08 16:36
> In this case, we can retrieve source for most dart: libraries, but have regressed for some specific libraries; I haven't dug into which ones.

This may not be true anymore -

> Are we fine that people can no longer step into core libraries or do we consider this to be an UX regression?

Definitely a UX regression - we should figure out a way to restore this (either by retrieving source from the VM, or by being better able to map to dart: sources in the sdk on disk.
