### ISSUE TITLE
Dart Analyzer Error 

### ISSUE THREAD

**Issue by khan-shahzad** [dart-lang/sdk#37658] opened 2019-07-29 05:36 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1080x1920`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version , FATAL error: NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:760:9)
#2      Driver.start (package:analysis_server/src/server/driver.dart:394:28)
#3      main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\skha436\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment] 2019-09-05 03:47
Thanks for reporting this issue! It was previously reported at #35226; please follow along there.

**Comment by srawlins** [comment] 2019-09-05 03:47
Duplicate of #35226

**Closed by srawlins** 2019-09-05 03:47 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
