### ISSUE TITLE
SocketException: Reading from a closed socket

### ISSUE THREAD

**Issue by huangsir0** [dart-lang/sdk#47018] opened 2021-08-26 01:07 UTC
## Steps to Reproduce

I don't know how to reproduce this SocketException，it suddenly report an error during the application.

## flutter doctor 
``` dart
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/huangsir/flutter-2.0.6/flutter
    • Framework revision b22742018b (3 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

## error stack

```dart
flutter: content: Caught error: SocketException: Reading from a closed socket
flutter: content: #0      _RawSecureSocket.read (dart:io/secure_socket.dart:662:7)
dart-lang/http#1      _Socket._onData (dart:io-patch/socket_patch.dart:2159:28)
dart-lang/http#2      _rootRunUnary (dart:async/zone.dart:1362:47)
dart-lang/http#3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
dart-lang/http#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
dart-lang/http#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
dart-lang/http#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
dart-lang/http#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
dart-lang/http#8      _StreamController._add (dart:async/stream_controller.dart:607:7)
dart-lang/http#9      _StreamController.add (dart:async/stream_controller.dart:554:5)
dart-lang/http#10     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
dart-lang/http#11     _rootRun (dart:async/zone.dart:1346:47)
dart-lang/http#12     _CustomZone.run (dart:async/zone.dart:1258:19)
dart-lang/http#13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
dart-lang/http#14     _CustomZone.bindCallbackGuarded.<an<…>
```

**Comment by alaatm** [comment] 2022-09-29 09:45
I am having similar crash reports:

```
SocketException: Reading from a closed socket

[
  "_RawSecureSocket.read (dart:io/secure_socket.dart:770)",
  "_Socket._onData (dart:io-patch/socket_patch.dart:2323)",
  "_RootZone.runUnaryGuarded (dart:async/zone.dart:1586)",
  "_BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)",
  "_BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)",
  "_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)",
  "_StreamController._add (dart:async/stream_controller.dart:648)",
  "_StreamController.add (dart:async/stream_controller.dart:596)",
  "_RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1107)",
  "Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)",
  "_Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)",
  "_Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)",
  "_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)"
]
```

I am unable to reproduce this as well, this crash is reported from some devices and the app state is always in the `paused` state when this happens. It happens after interacting with a chat page (using sockets with signalR client) then minimizing the app.

**Comment by JimmyHuang454** [comment] 2022-10-02 20:10
Same thing happens to me too. This crash really confuse me, It seem this crash comes from `.../io/secure_socket.dart`, when a TLS socket closed, it raw socket keep sending data to TLS handler, then tigger this crash.

**Comment by a-siva** [comment] 2023-04-28 23:50
Bumping priority as folks seem to run into this frequently

**Comment by a-siva** [comment] 2023-04-28 23:51
//cc @brianquinlan

**Comment by bagedevimo** [comment] 2023-04-30 00:02
Happy to have a go at a fix for this, if it's on the less-tricky side of hard. My suggestion in #52210 was to change from a exception to returning nil, like the other conditional checks in that method (a few lines below). 

If someone can provide a steer on writing a test and/or a fix, very happy to have a go.

**Comment by a-siva** [comment] 2023-05-01 16:59
I was looking at adding the suggested fix, I am in the process of trying to add a regression test that will work with our test harness.

**Comment by afl-dev** [comment] 2024-04-24 22:47
up

**Comment by ZaneCode6574** [comment] 2024-04-27 04:14
I met this problem too. Have no idea.

**Comment by AntonMenshickov** [comment] 2024-06-04 14:39
I have the same error

**Comment by brianquinlan** [comment] 2024-06-04 18:15
What platforms are people seeing this on?

**Closed** 2024-06-25 08:05 UTC
Labels: area-vm, library-io, needs-info

**Comment by vynguyenbao28** [comment] 2024-12-30 02:17
I have the same error
