### ISSUE TITLE
"Failed host lookup" caught exception when using http.openUrl()

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52615] opened 2023-06-05 09:59 UTC
This is related to https://github.com/flutter/flutter/issues/126650 / https://github.com/dart-lang/sdk/issues/52423. Dart 3 changed some code that resulted in a _caught_ exception when doing HTTP requests. Many users are currently running with "break on all exceptions" (something I recommend against, but still seems very common).

That issue was fixed and subsequently cherry-picked in https://github.com/dart-lang/sdk/issues/52487. However, running the same code has the same behaviour with the fix, because there is another caught exception.

Example code:

```dart
import 'dart:io';

import 'package:flutter/material.dart';

main() async {
  var client = HttpClient();
  var req = await client.openUrl("get", Uri.parse("https://www.bbc.co.uk"));
  var resp = await req.close();
  print(resp.statusCode);

  return runApp(const MaterialApp(
      home: Scaffold(
    body: Center(child: Text("Hello")),
  )));
}
```

![image](https://github.com/dart-lang/sdk/assets/1078012/38dffc7f-978e-459c-9512-665cf7796dbf)

The error suggests it failed to resolve www.bbc.co.uk, although that's definitely a valid host that resolves. Not pausing on caught exceptions works fine and the request completes (I see a 200 status code printed).

This isn't the same problem as the original (it's a different exception), but the cherry-pick here unfortunately hasn't changed anything as far users see - there is still a caught exception here, it just happens to be a slightly different one.

**Comment by milindgoel15** [comment] 2023-06-05 10:39
https://github.com/dart-lang/sdk/issues/52487#issuecomment-1576530549

So what do you think about this?

**Comment by brianquinlan** [comment] 2023-06-05 19:42
This was caused by the fix for https://github.com/dart-lang/sdk/issues/50868

**Comment by brianquinlan** [comment] 2023-06-06 18:16
I think that the best approach is probably to change the way the debugger works. I have a proposal here: https://github.com/flutter/devtools/issues/5883

**Comment by brianquinlan** [comment] 2023-06-08 01:25
I'm closing this in favor of the devtools issue.

**Closed by brianquinlan** 2023-06-08 01:25 UTC
Labels: area-sdk
