### ISSUE TITLE
android studio bug report

### ISSUE THREAD

**Issue by dongzhixuanyuan** [dart-lang/sdk#41492] opened 2020-04-15 02:44 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6308749`
- `2.4.1`
- `AI-192.7142.36.36.6308749, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.4, screens 1920x1080, 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.1, server version 1.27.1, error: Analysis failed: /Users/liudong/android/code/netease/YDNativeFlutterBridge/Embed/flutter_module/Business/yd_exam/lib/exam_card/utils/exam_questions_model_util.dart context: exception_20200415_104359_701
type 'CompilationUnitElementImpl' is not a subtype of type 'ClassElement'
#0      ErrorVerifier._findOverriddenMemberThatMustCallSuper (package:analyzer/src/generated/error_verifier.dart:6112:18)
#1      ErrorVerifier._checkForMustCallSuper (package:analyzer/src/generated/error_verifier.dart:4449:29)
#2      ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:1054:7)
#3      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#5      ExtensionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3923:14)
#6      RecursiveAstVisitor.visitExtensionDeclaration (package:analyzer/dart/ast/visitor.dart:847:10)
#7      ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3916:49)
#8      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2173:15)
#9      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:727:10)
#10     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:572:11)
#11     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#12     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:410:10)
#13     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:169:9)
#14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#15     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:168:13)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:167:34)
#18     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#20     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#21     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#22     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#23     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#25     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#26     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#27     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#28     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#29     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#30     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#36     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#37     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#38     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#39     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#40     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#41     new Future.sync (dart:async/future.dart:224:31)
#42     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#48     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#49     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#50     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#...
```

For additional log information, please append the contents of
file:///private/var/folders/xg/20m3ywmn4s5f2303k928syt40000gn/T/report.txt.

**Comment by srawlins** [comment] 2020-06-13 20:37
Thanks for reporting this issue! This was also reported at https://github.com/dart-lang/sdk/issues/41492.

**Comment by srawlins** [comment] 2020-06-13 20:37
Duplicate of https://github.com/dart-lang/sdk/issues/41492

**Comment by srawlins** [comment] 2021-01-27 00:11
This has not been reported again since Dart 2.4; please re-open if you see this in a recent version of Dart/Flutter.

**Closed by srawlins** 2021-01-27 00:11 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
