### ISSUE TITLE
Analysis Server gives no error if 'part' file doesn't have matching main library file

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24446] opened 2015-09-25 20:03 UTC
I have a `part.dart` file with content:

```
part of fooLib;
...
```

If `fooLib` library doesn't exist or doesn't contain matching `part 'part.dart'` directive then Analysis Server gives no information for the `part.dart` file: no hints/warnings/errors (may be only syntax errors), no highlighting info, etc.
At minimum I expect server to report error (or warning or hint, what spec allows) for unresolved `fooLib` reference in `part.dart` file. If `fooLib` actually exists but doesn't contain matching `part 'part.dart'` directive then corresponding quick fix would be great.

P.S. I guess some highlighting info can also be calculated without having main library file (though I think it is less important for clients). As mentioned in #24441 client expects all `com.google.dart.server.AnalysisServerListener#computedXXX` to be notified at least with empty list.

**Comment by srawlins** [comment] 2023-01-05 17:58
Thanks for filing; duplicate of https://github.com/dart-lang/sdk/issues/29593

**Closed by srawlins** 2023-01-05 17:58 UTC
Labels: area-analyzer, analyzer-server, P2, type-bug
