### ISSUE TITLE
Dartdocgen - problem with old style named constants

### ISSUE THREAD

**Issue by Janamou** [dart-lang/sdk#23883] opened 2015-07-21 17:02 UTC
I found an interesting bug in dartdocgen. 

When I use `dartdocgen --serve .` to generate documentation with this script:

```dart
const String TYPE_NICE = "nice";
const String TYPE_VERY_NICE = "very_nice";

/// Main function uses [TYPE_NICE] and [TYPE_VERY_NICE].
main(List<String> args) {
}
```

Then there is a problem with referencing the constant with name `TYPE_VERY_NICE`. The constant `TYPE_NICE` is referenced normally and I can click through it. I found out that the reason is that when I use more than one **underscore**, the constant is not referenced.

Output of the comment in the documentation looks like this:

Main function uses [TYPE_NICE](#) and [TYPE_VERY_NICE].

Note 1: I know that according to the Dart style guide I should use `typeVeryNice` style of naming for constants, but this is OLD project where constants are named in this (Java) style.

Note 2: I know that you are working on new nice doc generator. I tried to run it through the `dartdoc` and there are no links in the text for the constants at all (probably you are working on this).

**Comment by sethladd** [comment] 2015-07-21 17:54
Let us know if this problem exists in the new dartdoc, too. Thanks!

**Comment by Janamou** [comment] 2015-07-22 11:34
@sethladd the new dartdoc (I am on 0.2.0) generates output without links for any type but the output is something similar:

Main function uses TYPE_NICE and [TYPE_VERY_NICE].

But without any links to constants like dartdocgen. Is this bug or feature of the new generator?

**Comment by sethladd** [comment] 2015-07-22 14:54
> But without any links to constants like dartdocgen. Is this bug or feature of the new generator?

This is probably a bug. The new dartdoc uses the analyzer to get doc comments from the raw comments. Please open an issue on dartdoc and we'll take a look. Thanks!

**Comment by sethladd** [comment] 2015-07-23 16:04
I'm not sure we're going to fix this with the dartdocgen tool. I'm going to close this issue, but thanks for opening it over in dartdoc!

**Closed by sethladd** 2015-07-23 16:04 UTC

**Comment by alan-knight** [comment] 2015-07-23 16:22
I suspect the issue is a conflict with markdown. When you have more than one underscore that's markdown for emphasis and that gets applied before it tries to interpret the string. I've run into other issues like that. Probably something to be careful of in the new dartdoc as well. Might be fixed by doing things in the correct order, assuming there is a universally correct order.
