### ISSUE TITLE
analyzer does not see an error when calling class as a function

### ISSUE THREAD

**Issue by 0xff00ff** [dart-lang/sdk#33243] opened 2018-05-25 23:12 UTC
I have a simple code:
```
import 'dart:math';

void main() {
  Random().nextInt(2);
}
```

I use: Dart VM version: 2.0.0-dev.53.0 (Unknown timestamp) on "linux_x64"

this code throws an error on runtime:
```
Unhandled exception:
NoSuchMethodError: Attempted to use type 'Random' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the Random constructor and forget the 'new' operator?
Receiver: Random
Tried calling: Random()
```

But dartanalyzer says that "No issues found!"

I think this is an analyzer issue. This issue should be checked on compile time.

Dart knows that i want to call Random as function, and it knows that Random does not have call method.

**Comment by eernstg** [comment] 2018-05-28 08:35
I'm closing this with 'works as intended' because you're reporting exactly the behavior that would be expected for checking according to Dart 2 rules and then running with Dart 1 semantics. Please create a new issue if additional issues arise.

**Closed by eernstg** 2018-05-28 08:35 UTC
Labels: Resolution: works as intended, area-analyzer
