### ISSUE TITLE
error: Mixin can only be applied to class. (mixin_with_non_class_superclass at [flutter_app09] lib\main.dart:28)

### ISSUE THREAD

**Issue by tiankun** [dart-lang/sdk#36973] opened 2019-05-15 03:54 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.5429.30.34.5452501`
- `1.24.3`
- `AI-183.5429.30.34.5452501, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1680x1050`

## Exception
```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      FileState.isPart (package:analyzer/src/dart/analysis/file_state.dart:243)
#3      _TopLevelNameDeclarationsTask.perform (package:analyzer/src/dart/analysis/driver.dart:1991)
<asynchronous suspension>
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:821)
<asynchronous suspension>
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#6      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#7      new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#8      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#9      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#10     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     runZoned (dart:async/zone.dart:1467)
#14     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#15     Driver.start (package:analysis_server/src/server/driver.dart:473)
#16     main (file:///D:/src/sdk1/sdk/pkg/analysis_server/bin/server.dart:12)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

For additional log information, please append the contents of
file://C:\Users\11725\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment] 2019-09-06 04:44
Thanks for filing this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/35606; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 04:44
Duplicate of https://github.com/dart-lang/sdk/issues/35606

**Closed by srawlins** 2019-09-06 04:44 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
