### ISSUE TITLE
handle empty typemasks for intercepted types (dart2js crash)

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#24860] opened 2015-11-09 12:03 UTC
The compiler is crashing in the tests
dart2js_extra/deferred_fail_and_retry_test
and
dart2js_extra/deferred_fail_and_retry_worker_test
when the cps-ir and host_checked flags are set.

This is happening after https://github.com/dart-lang/sdk/commit/7b458eb1d62fe2ef896ed60e0a463f95bf0b0890
and the failure is in the code changed by this commit.

  See:
https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-linux-release-cps-be/builds/426/steps/dart2js_extra-d8%20tests%20--dart2js-batch%20--cps-ir%20--host-checked%20failures/logs/stdio

**Comment by asgerf** [comment] 2015-11-18 12:05
Should be resolved as of 44a200b88de6.

**Comment by johnniwinther** [comment] 2015-11-20 09:37
There is still problems in swarm.

**Comment by sigmundch** [comment] 2015-12-10 03:08
@johnniwinther - can you say more about what problems you are seeing in swarm? Do you mean you see the same crash in cps-ir when compiling swarm?

**Comment by johnniwinther** [comment] 2015-12-10 09:07
The problem is that we try to create a non-null subclass typemask for an intercepted class that isn't live (GlobalEventHandlers as far as I remember). This causes an assertion error because such typemask is actually [empty].

The underlying problem is that we are not careful about the semantics of the intercepted ClassElement objects that we collect.

**Comment by sigmundch** [comment] 2015-12-10 17:06
Thanks for the clarification - I updated the title & label to reflect the issue.

**Comment by vsmenon** [comment] 2019-07-22 20:36
obsolete?

**Comment by johnniwinther** [comment] 2019-07-23 07:46
We still have weird semantics with how we model the equivalence classes of intercepted classes using class elements that might not be live. I think we have since added the notion of abstract liveness which might prevent the kind of crash. So obsolete-ish.

Let @sigmundch decide when he is back.

**Comment by sigmundch** [comment] 2019-09-09 18:21
I'll close it then. I also feel there is not much left on this issue to help us in investigate and that we'll need to revisit the problem from scratch if we encounter it again.

**Closed by sigmundch** 2019-09-09 18:21 UTC
Labels: P3, area-web, dart2js-crash, type-bug, web-dart2js
