### ISSUE TITLE
[ffi] How to add native code?

### ISSUE THREAD

**Issue by medz** [dart-lang/sdk#53959] opened 2023-11-05 14:27 UTC
I have a unique requirement, I usually develop dylibs in Rust and I always have to inject something into dylib specific functions.

When I saw napi I thought it was amazing and I spent many days studying it.

Let me first talk about my ffi needs. I want to use dart to develop a library. This library defines many functions such as `a`.
I develop a dylib using Rust, and then I write in rust:
```rust
extern "C" {
     fn a(value: *mut c_char);
}

#[no_mangle]
pub extern "C" b() {
     let hi = "hello";
     a(hi.into_raw());
}
```

Then I do this in Dart:
```dart
void a(String value) => print(value);

final lib = DynamicLibrary('b.dylib');

final b = lib.lookupFunction('b');
b();
```

I know of course that I can pass dart 's a function to b (from dylib), but that's inconvenient, and I'd like to develop some other language compatible libraries to dart.

When I researched napi I found that they implement this.

I tried using C and Rust, and after compiling Rust to a dylib, I can declare `extern "C"` in Rust to have the dylib call functions written in C code!

So the question is, how to declare native functions written in Dart to dylib in Dart FFI?

**Comment by medz** [comment] 2023-11-05 14:43
I want to add some defined constants or functions to the Dart native for Dylib to call.

**Comment by mraleph** [comment] 2023-11-07 08:49
There is currently no functionality to achieve what you want beyond that way you have already discovered, i.e. you can manually pass pointers to Dart functions to the native code.

We have discussed adding something like `@ffi.Export()` annotation to `dart:ffi` to facilitate exporting of Dart functions - but we have not gotten to it so far (@dcharkes do we have an issue tracking `ffi.Export` functionality somewhere?).

There is one subtle problem that makes such functionality complicated: Dart has isolates and native languages don't have them. So if you want to expose Dart functions to native code like C or Rust a big question arises: when native code calls a Dart function which isolate does it use? 

Unfortunately so far we did not find a good answer to this question and that makes reverse binding (e.g. calling Dart from native side) more complicated.

**Comment by dcharkes** [comment] 2023-11-07 09:08
> We have discussed adding something like `@ffi.Export()` annotation to `dart:ffi` to facilitate exporting of Dart functions - but we have not gotten to it so far (@dcharkes do we have an issue tracking `ffi.Export` functionality somewhere?).

* https://github.com/dart-lang/sdk/issues/51383

**Comment by mraleph** [comment] 2023-11-10 07:52
Duplicate of https://github.com/dart-lang/sdk/issues/51383

**Closed by mraleph** 2023-11-10 07:52 UTC
Labels: area-vm, type-question, library-ffi
