### ISSUE TITLE
Failed to handle request: analysis.setAnalysisRoots

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#39173] opened 2019-10-29 23:04 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.6817.13`
- `2.6.0-dev.6.0`
- `WS-192.6817.13, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1440, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.6.0-dev.6.0, server version 1.27.3, FATAL error: Failed to handle request: {id: 5, method: analysis.setAnalysisRoots, params: {included: [/Users/filiph/dev/flutter-website], excluded: [/Users/filiph/dev/flutter-website/.idea, /Users/filiph/dev/flutter-website/.pub, /Users/filiph/dev/flutter-website/.tmp, /Users/filiph/dev/flutter-website/build, /Users/filiph/dev/flutter-website/example.g/.pub, /Users/filiph/dev/flutter-website/example.g/build, /Users/filiph/dev/flutter-website/example/.pub, /Users/filiph/dev/flutter-website/example/build, /Users/filiph/dev/flutter-website/examples/_animation/basic_hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/basic_hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/basic_radial_hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/basic_radial_hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/basic_staggered_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/basic_staggered_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation_animate_rectclip/.pub, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation_animate_rectclip/build, /Users/filiph/dev/flutter-website/examples/_animation/staggered_pic_selection/.pub, /Users/filiph/dev/flutter-website/examples/_animation/staggered_pic_selection/build, /Users/filiph/dev/flutter-website/examples/animation/animate0/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate0/build, /Users/filiph/dev/flutter-website/examples/animation/animate1/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate1/build, /Users/filiph/dev/flutter-website/examples/animation/animate2/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate2/build, /Users/filiph/dev/flutter-website/examples/animation/animate3/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate3/build, /Users/filiph/dev/flutter-website/examples/animation/animate4/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate4/build, /Users/filiph/dev/flutter-website/examples/animation/animate5/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate5/build, /Users/filiph/dev/flutter-website/examples/codelabs/add_flutter_to_android_app/flutter/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/add_flutter_to_android_app/flutter/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step1_base/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step1_base/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step2_use_package/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step2_use_package/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step3_stateful_widget/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step3_stateful_widget/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step4_infinite_list/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step4_infinite_list/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step5_add_icons/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step5_add_icons/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step6_add_interactivity/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step6_add_interactivity/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step7_navigate_route/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step7_navigate_route/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step8_themes/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step8_themes/build, /Users/filiph/dev/flutter-website/examples/internationalization/add_language/.pub, /Users/filiph/dev/flutter-website/examples/internationalization/add_language/build, /Users/filiph/dev/flutter-website/examples/internationalization/intl_example/.pub, /Users/filiph/dev/flutter-website/examples/internationalization/intl_example/build, /Users/filiph/dev/flutter-website/examples/internationalization/minimal/.pub, /Users/filiph/dev/flutter-website/examples/internationalization/minimal/build, /Users/filiph/dev/flutter-website/examples/layout/base/.pub, /Users/filiph/dev/flutter-website/examples/layout/base/build, /Users/filiph/dev/flutter-website/examples/layout/card_and_stack/.pub, /Users/filiph/dev/flutter-website/examples/layout/card_and_stack/build, /Users/filiph/dev/flutter-website/examples/layout/container/.pub, /Users/filiph/dev/flutter-website/examples/layout/contai...
```

For additional log information, please append the contents of
file:///private/var/folders/np/gmysjh1j2159hv7wssjzrw440028jd/T/report.txt.

```
Dart analysis server, SDK version 2.6.0-dev.6.0, server version 1.27.3, FATAL error: Failed to handle request: {id: 5, method: analysis.setAnalysisRoots, params: {included: [/Users/filiph/dev/flutter-website], excluded: [/Users/filiph/dev/flutter-website/.idea, /Users/filiph/dev/flutter-website/.pub, /Users/filiph/dev/flutter-website/.tmp, /Users/filiph/dev/flutter-website/build, /Users/filiph/dev/flutter-website/example.g/.pub, /Users/filiph/dev/flutter-website/example.g/build, /Users/filiph/dev/flutter-website/example/.pub, /Users/filiph/dev/flutter-website/example/build, /Users/filiph/dev/flutter-website/examples/_animation/basic_hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/basic_hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/basic_radial_hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/basic_radial_hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/basic_staggered_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/basic_staggered_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation/.pub, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation/build, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation_animate_rectclip/.pub, /Users/filiph/dev/flutter-website/examples/_animation/radial_hero_animation_animate_rectclip/build, /Users/filiph/dev/flutter-website/examples/_animation/staggered_pic_selection/.pub, /Users/filiph/dev/flutter-website/examples/_animation/staggered_pic_selection/build, /Users/filiph/dev/flutter-website/examples/animation/animate0/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate0/build, /Users/filiph/dev/flutter-website/examples/animation/animate1/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate1/build, /Users/filiph/dev/flutter-website/examples/animation/animate2/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate2/build, /Users/filiph/dev/flutter-website/examples/animation/animate3/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate3/build, /Users/filiph/dev/flutter-website/examples/animation/animate4/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate4/build, /Users/filiph/dev/flutter-website/examples/animation/animate5/.pub, /Users/filiph/dev/flutter-website/examples/animation/animate5/build, /Users/filiph/dev/flutter-website/examples/codelabs/add_flutter_to_android_app/flutter/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/add_flutter_to_android_app/flutter/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step1_base/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step1_base/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step2_use_package/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step2_use_package/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step3_stateful_widget/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step3_stateful_widget/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step4_infinite_list/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step4_infinite_list/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step5_add_icons/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step5_add_icons/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step6_add_interactivity/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step6_add_interactivity/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step7_navigate_route/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step7_navigate_route/build, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step8_themes/.pub, /Users/filiph/dev/flutter-website/examples/codelabs/startup_namer/step8_themes/build, /Users/filiph/dev/flutter-website/examples/internationalization/add_language/.pub, /Users/filiph/dev/flutter-website/examples/internationalization/add_language/build, /Users/filiph/dev/flutter-website/examples/internationalization/intl_example/.pub, /Users/filiph/dev/flutter-website/examples/internationalization/intl_example/build, /Users/filiph/dev/flutter-website/examples/internationalization/minimal/.pub, /Users/filiph/dev/flutter-website/examples/internationalization/minimal/build, /Users/filiph/dev/flutter-website/examples/layout/base/.pub, /Users/filiph/dev/flutter-website/examples/layout/base/build, /Users/filiph/dev/flutter-website/examples/layout/card_and_stack/.pub, /Users/filiph/dev/flutter-website/examples/layout/card_and_stack/build, /Users/filiph/dev/flutter-website/examples/layout/container/.pub, /Users/filiph/dev/flutter-website/examples/layout/container/build, /Users/filiph/dev/flutter-website/examples/layout/grid_and_list/.pub, /Users/filiph/dev/flutter-website/examples/layout/grid_and_list/build, /Users/filiph/dev/flutter-website/examples/layout/lakes/interactive/.pub, /Users/filiph/dev/flutter-website/examples/layout/lakes/interactive/build, /Users/filiph/dev/flutter-website/examples/layout/lakes/step2/.pub, /Users/filiph/dev/flutter-website/examples/layout/lakes/step2/build, /Users/filiph/dev/flutter-website/examples/layout/lakes/step3/.pub, /Users/filiph/dev/flutter-website/examples/layout/lakes/step3/build, /Users/filiph/dev/flutter-website/examples/layout/lakes/step4/.pub, /Users/filiph/dev/flutter-website/examples/layout/lakes/step4/build, /Users/filiph/dev/flutter-website/examples/layout/lakes/step5/.pub, /Users/filiph/dev/flutter-website/examples/layout/lakes/step5/build, /Users/filiph/dev/flutter-website/examples/layout/lakes/step6/.pub, /Users/filiph/dev/flutter-website/examples/layout/lakes/step6/build, /Users/filiph/dev/flutter-website/examples/layout/non_material/.pub, /Users/filiph/dev/flutter-website/examples/layout/non_material/build, /Users/filiph/dev/flutter-website/examples/layout/pavlova/.pub, /Users/filiph/dev/flutter-website/examples/layout/pavlova/build, /Users/filiph/dev/flutter-website/examples/layout/row_column/.pub, /Users/filiph/dev/flutter-website/examples/layout/row_column/build, /Users/filiph/dev/flutter-website/examples/layout/sizing/.pub, /Users/filiph/dev/flutter-website/examples/layout/sizing/build, /Users/filiph/dev/flutter-website/examples/state_mgmt/simple/.pub, /Users/filiph/dev/flutter-website/examples/state_mgmt/simple/build, /Users/filiph/dev/flutter-website/flutter/bin/cache/dart-sdk/lib/_internal/js_runtime/.pub, /Users/filiph/dev/flutter-website/flutter/bin/cache/dart-sdk/lib/_internal/js_runtime/build, /Users/filiph/dev/flutter-website/flutter/bin/cache/dart-sdk/lib/_internal/sdk_library_metadata/.pub, /Users/filiph/dev/flutter-website/flutter/bin/cache/dart-sdk/lib/_internal/sdk_library_metadata/build, /Users/filiph/dev/flutter-website/flutter/bin/cache/pkg/sky_engine/.pub, /Users/filiph/dev/flutter-website/flutter/bin/cache/pkg/sky_engine/build, /Users/filiph/dev/flutter-website/flutter/dev/automated_tests/.pub, /Users/filiph/dev/flutter-website/flutter/dev/automated_tests/build, /Users/filiph/dev/flutter-website/flutter/dev/benchmarks/complex_layout/.pub, /Users/filiph/dev/flutter-website/flutter/dev/benchmarks/complex_layout/build, /Users/filiph/dev/flutter-website/flutter/dev/benchmarks/macrobenchmarks/.pub, /Users/filiph/dev/flutter-website/flutter/dev/benchmarks/macrobenchmarks/build, /Users/filiph/dev/flutter-website/flutter/dev/benchmarks/microbenchmarks/.pub, /Users/filiph/dev/flutter-website/flutter/dev/benchmarks/microbenchmarks/build, /Users/filiph/dev/flutter-website/flutter/dev/bots/.pub, /Users/filiph/dev/flutter-website/flutter/dev/bots/build, /Users/filiph/dev/flutter-website/flutter/dev/customer_testing/.pub, /Users/filiph/dev/flutter-website/flutter/dev/customer_testing/build, /Users/filiph/dev/flutter-website/flutter/dev/devicelab/.pub, /Users/filiph/dev/flutter-website/flutter/dev/devicelab/build, /Users/filiph/dev/flutter-website/flutter/dev/docs/platform_integration/.pub, /Users/filiph/dev/flutter-website/flutter/dev/docs/platform_integration/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_semantics_testing/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_semantics_testing/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_splash_screens/splash_screen_kitchen_sink/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_splash_screens/splash_screen_kitchen_sink/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_splash_screens/splash_screen_load_rotate/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_splash_screens/splash_screen_load_rotate/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_splash_screens/splash_screen_trans_rotate/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_splash_screens/splash_screen_trans_rotate/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_views/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/android_views/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/channels/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/channels/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/codegen/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/codegen/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/external_ui/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/external_ui/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/flavors/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/flavors/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/image_loading/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/image_loading/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/ios_add2app/flutterapp/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/ios_add2app/flutterapp/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/named_isolates/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/named_isolates/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/platform_interaction/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/platform_interaction/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/release_smoke_test/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/release_smoke_test/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/simple_codegen/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/simple_codegen/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/ui/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/ui/build, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/web/.pub, /Users/filiph/dev/flutter-website/flutter/dev/integration_tests/web/build, /Users/filiph/dev/flutter-website/flutter/dev/manual_tests/.pub, /Users/filiph/dev/flutter-website/flutter/dev/manual_tests/build, /Users/filiph/dev/flutter-website/flutter/dev/missing_dependency_tests/.pub, /Users/filiph/dev/flutter-website/flutter/dev/missing_dependency_tests/build, /Users/filiph/dev/flutter-website/flutter/dev/snippets/.pub, /Users/filiph/dev/flutter-website/flutter/dev/snippets/build, /Users/filiph/dev/flutter-website/flutter/dev/tools/.pub, /Users/filiph/dev/flutter-website/flutter/dev/tools/build, /Users/filiph/dev/flutter-website/flutter/dev/tools/gen_keycodes/.pub, /Users/filiph/dev/flutter-website/flutter/dev/tools/gen_keycodes/build, /Users/filiph/dev/flutter-website/flutter/dev/tools/vitool/.pub, /Users/filiph/dev/flutter-website/flutter/dev/tools/vitool/build, /Users/filiph/dev/flutter-website/flutter/examples/catalog/.pub, /Users/filiph/dev/flutter-website/flutter/examples/catalog/build, /Users/filiph/dev/flutter-website/flutter/examples/flutter_gallery/.pub, /Users/filiph/dev/flutter-website/flutter/examples/flutter_gallery/build, /Users/filiph/dev/flutter-website/flutter/examples/flutter_view/.pub, /Users/filiph/dev/flutter-website/flutter/examples/flutter_view/build, /Users/filiph/dev/flutter-website/flutter/examples/hello_world/.pub, /Users/filiph/dev/flutter-website/flutter/examples/hello_world/build, /Users/filiph/dev/flutter-website/flutter/examples/image_list/.pub, /Users/filiph/dev/flutter-website/flutter/examples/image_list/build, /Users/filiph/dev/flutter-website/flutter/examples/layers/.pub, /Users/filiph/dev/flutter-website/flutter/examples/layers/build, /Users/filiph/dev/flutter-website/flutter/examples/platform_channel/.pub, /Users/filiph/dev/flutter-website/flutter/examples/platform_channel/build, /Users/filiph/dev/flutter-website/flutter/examples/platform_channel_swift/.pub, /Users/filiph/dev/flutter-website/flutter/examples/platform_channel_swift/build, /Users/filiph/dev/flutter-website/flutter/examples/platform_view/.pub, /Users/filiph/dev/flutter-website/flutter/examples/platform_view/build, /Users/filiph/dev/flutter-website/flutter/examples/stocks/.pub, /Users/filiph/dev/flutter-website/flutter/examples/stocks/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_build/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_build/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_driver/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_driver/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_goldens/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_goldens/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_goldens_client/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_goldens_client/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_localizations/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_localizations/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_test/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_test/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_test/test/test_config/project_root/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_test/test/test_config/project_root/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/asset_test/font/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/asset_test/font/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/asset_test/main/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/asset_test/main/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/asci_casing/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/asci_casing/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_import/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_import/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_package/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_package/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_path/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/bad_path/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/changed_sdk_location/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/changed_sdk_location/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/good/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/good/build, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/syntax_error/.pub, /Users/filiph/dev/flutter-website/flutter/packages/flutter_tools/test/data/dart_dependencies_test/syntax_error/build, /Users/filiph/dev/flutter-website/flutter/packages/fuchsia_remote_debug_protocol/.pub, /Users/filiph/dev/flutter-website/flutter/packages/fuchsia_remote_debug_protocol/build, /Users/filiph/dev/flutter-website/site-shared/src/tools/sdk/archive/.pub, /Users/filiph/dev/flutter-website/site-shared/src/tools/sdk/archive/build, /Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/.pub, /Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/build, /Users/filiph/dev/flutter-website/src/_shared/tools/sdk/archive/.pub, /Users/filiph/dev/flutter-website/src/_shared/tools/sdk/archive/build, /Users/filiph/dev/flutter-website/temp, /Users/filiph/dev/flutter-website/tmp]}, clientRequestTime: 1572390122921}
Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:220:5)
#1      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:206:23)
#2      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:786:48)
#3      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1154:19)
#4      ContextManagerImpl._extractContext (package:analysis_server/src/context_manager.dart:1267:9)
#5      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:1428:17)
#6      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1371:5)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#13     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#21     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#26     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#28     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#29     _rootRun (dart:async/zone.dart:1120:38)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

```
1572390234939 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","regions":[{"type":"DIRECTIVE","offset":1
1572390234940 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","regions":[{"offset":177,"length":11,"tar
1572390234940 <= {"event":"analysis.outline","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","kind":"LIBRARY","outline":{"element":{"kind
1572390234940 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","overrides":[]}}
1572390234951 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1572390234952 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","classes":[],"members":[]}}
1572390235109 => {"id":"24","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart":{"type":"remove"}}},"clie
1572390235109 => {"id":"25","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","offset":2748,"length":0},"clientR
1572390235110 <= {"id":"24","result":{}}
1572390235110 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1572390235126 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","errors":[{"severity":"ERROR","type":"STATIC_
1572390235128 <= {"id":"25","result":{"assists":[]}}
1572390235129 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","regions":[{"type":"DIRECTIVE","offset":1
1572390235129 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","regions":[{"offset":177,"length":11,"tar
1572390235130 <= {"event":"analysis.outline","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","kind":"LIBRARY","outline":{"element":{"kind
1572390235130 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","overrides":[]}}
1572390235142 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1572390235142 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","classes":[],"members":[]}}
1572390235441 => {"id":"26","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","offset":2748,"length":0},"clientR
1572390235444 <= {"id":"26","result":{"assists":[]}}
1572390257645 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1572390257662 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","errors":[{"severity":"ERROR","type":"STATIC_
1572390257663 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","regions":[{"type":"DIRECTIVE","offset":1
1572390257663 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","regions":[{"offset":177,"length":11,"tar
1572390257663 <= {"event":"analysis.outline","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","kind":"LIBRARY","outline":{"element":{"kind
1572390257663 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","overrides":[]}}
1572390257879 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1572390257880 <= {"event":"analysis.implemented","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/web/dartpad_picker_main.dart","classes":[],"members":[]}}
1572390262046 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/flutter-website/src/_packages/dartpad_picker/out/web/packages/pedantic/analysis_options.yaml","errors":[]}}
1572390263489 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 5, method: analysis.setAnalysisRoots, params: {included: [/Users/filiph/dev/flutter-website]
```

**Comment by srawlins** [comment] 2019-11-05 17:30
Duplicate of https://github.com/dart-lang/sdk/issues/38318

**Closed by srawlins** 2019-11-05 17:30 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
