### ISSUE TITLE
Unable Hor Reload

### ISSUE THREAD

**Issue by Kelique76** [dart-lang/sdk#35201] opened 2018-11-17 03:25 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.2`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

# Exception

Please append the contents of:
file://C:\Users\keliq\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.2, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [F:\AS3\FlutterTrainee\EcommerceAmagust\ecomm_amagoust], excluded: [F:\AS3\FlutterTrainee\EcommerceAmagust\ecomm_amagoust\.idea, F:\AS3\FlutterTrainee\EcommerceAmagust\ecomm_amagoust\.dart_tool, F:\AS3\FlutterTrainee\EcommerceAmagust\ecomm_amagoust\.idea, F:\AS3\FlutterTrainee\EcommerceAmagust\ecomm_amagoust\.pub, F:\AS3\FlutterTrainee\EcommerceAmagust\ecomm_amagoust\build]}, clientRequestTime: 1542424743171}
FileSystemException: Exists failed, path = 'F:\AS3\FlutterTrainee\EcommerceAmagust\ecomm_amagoust\build\app\generated\source\r\debug\com\google\android\gms\flags' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-11-29 17:50
Duplicate of #34294

**Closed by stereotype441** 2018-11-29 17:50 UTC
Labels: area-analyzer
