### ISSUE TITLE
Expression compilation breaks after failed Hot-Reload

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32341] opened 2018-02-27 14:26 UTC
Update `bad_hot_reload.dart` after fixing.

**Comment by JekCharlsonYu** [comment] 2018-06-15 20:22
Siva, do you mind triaging and assigning a person to work on this?

**Comment by a-siva** [comment] 2018-06-21 16:14
I believe there are set of issues against expression evaluation that are being tracked in the flutter/flutter issue list and this might be a duplicate of that

**Comment by aam** [comment] 2018-06-21 16:48
I don't believe there is an issue in flutter tracker for this yet.

**Comment by dgrove** [comment] 2018-07-04 01:57
Is there something actionable here?

**Comment by aam** [comment] 2018-07-04 04:28
@dgrove wrote:
> Is there something actionable here?

It turns out that not much. https://dart-review.googlesource.com/c/sdk/+/63721 should fix the test.

**Comment by mit-mit** [comment] 2018-07-09 13:22
Closing, we believe this was resolved

**Closed by mit-mit** 2018-07-09 13:22 UTC
Labels: Customer-VM, P2 medium, area-front-end, area-vm, expression-compilation
