### ISSUE TITLE
Allow conflicting top-level variable/function names when compiling in browser

### ISSUE THREAD

**Issue by priscilla-lee** [dart-lang/sdk#27042] opened 2016-08-09 19:24 UTC
The [Dart Dev Compiler Debugger](https://github.com/dart-lang/dev_compiler_debugger)  runs the dev compiler in the browser. It compiles and evaluates expressions one at a time by piggybacking imports to all previous expressions. A user may declare and define variables and functions, but the compiler crashes when it encounters conflicting top level names. Add a flag to dev compiler or analyzer to allow permissive compiling in the browser.

**Comment by bwilkerson** [comment] 2016-08-09 21:11
Using imports is an interesting approach.

Analyzer doesn't have any problem dealing with multiply defined names, even within the same file. If you're using import directives, then I'm surprised DDC does either, because locally defined names should hide imported names.

Can you provide a small piece of code that reproduces the problem you're seeing?

**Comment by kevmoo** [comment] 2016-08-09 23:23
Is this a `dev_compiler` or an analyzer issue?

**Comment by priscilla-lee** [comment] 2016-08-11 17:20
Because we chain imports, we treat all variables and functions as top level. The problem comes up when a user wants to do something like this:

`var x = 100; ` --> 100
`var x = 200;` --> 200
`var y = x * 2; ` --> [error] The name 'x' is defined in the libraries 'expression1.dart' and 'expression2.dart' (file:///expression3.dart, line 1, col 61)

Note that this is fine (because x isn't re-declared):
`var x = 100; ` --> 100
`x = 200;` --> 200
`var y = x * 2; ` --> 400

**Comment by bwilkerson** [comment] 2016-08-11 17:29
This is an interesting use case, but I have to wonder whether we really need a flag in analyzer (which we can do if need be) or whether there might be other ways to solve the problem.

Is there a single variable declaration in each file? Could you keep track of the file containing the most recent assignment to each variable and only import those when building the file for the current expression?

As a bigger change, could you define a Map containing the values of all the variables and produce code similar to `variables['x'] = 100;` for each expression rather than using a top-level variable for each?

**Comment by jacob314** [comment] 2018-06-27 16:16
Closing as this can be handled on the ddc side.

**Closed by jacob314** 2018-06-27 16:16 UTC
Labels: P2 medium, area-analyzer
