### ISSUE TITLE
Equivalent API to Java's Pattern.quote()

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28784] opened 2017-02-15 22:53 UTC
We should provide an API method that takes a string and returns the string safe for inclusion in a `RegExp` (as a literal value).  This is the functional equivalent of Java's `Pattern.quote()` method -- http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#quote(java.lang.String)

**Proposal**

```
class RegExp {
  static String quote(String input);
}
```

**Comment by tvolkert** [comment] 2017-02-15 22:54
`RegExp.escape(String)` would work as a name too.

**Comment by nex3** [comment] 2017-02-15 23:44
Duplicate of #4706 :confused:.

**Closed by nex3** 2017-02-15 23:44 UTC
