### ISSUE TITLE
We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by akassharjun** [dart-lang/sdk#38401] opened 2019-09-15 11:34 UTC
* Dart SDK Version - Dart VM version: 2.5.0
* OS - macos_x64
* Browser - Chrome
* Error - Bug in Web-Dev-Compiler

How did it occur? 
Well I don't know to be honest, tried to added an AlertDialog to my website. When I ran the code, it showed me this error. Now even after removing the AlertDialog, it still shows me the same error.

We're sorry, you've found a bug in our compiler.

You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
```
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.5.0/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/akassharjun_me/pages/home.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/flutter_web_ui/ui.ddc.dill=packages/flutter_web_ui/ui --summary=packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --summary=packages/flutter_web/physics.ddc.dill=packages/flutter_web/physics --summary=packages/flutter_web/io.ddc.dill=packages/flutter_web/io --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/flutter_web/src/foundation/assertions.ddc.dill=packages/flutter_web/src/foundation/assertions --summary=packages/flutter_web/foundation.ddc.dill=packages/flutter_web/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64 --summary=packages/flutter_web/src/animation/animation.ddc.dill=packages/flutter_web/src/animation/animation --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/flutter_web/animation.ddc.dill=packages/flutter_web/animation --summary=packages/flutter_web/src/cupertino/action_sheet.ddc.dill=packages/flutter_web/src/cupertino/action_sheet --summary=packages/flutter_web/cupertino.ddc.dill=packages/flutter_web/cupertino --summary=packages/flutter_web/material.ddc.dill=packages/flutter_web/material --summary=packages/akassharjun_me/widgets/skill_tag.ddc.dill=packages/akassharjun_me/widgets/skill_tag --summary=packages/akassharjun_me/pages/skills.ddc.dill=packages/akassharjun_me/pages/skills --summary=packages/akassharjun_me/widgets/social_media_icon.ddc.dill=packages/akassharjun_me/widgets/social_media_icon --summary=packages/akassharjun_me/pages/profile.ddc.dill=packages/akassharjun_me/pages/profile --packages=file:///var/folders/gy/k2fc2rnn2nlcybj6szgl8yqw0000gn/T/kernel_builder_jb1I5p/.packages --module-name=packages/akassharjun_me/pages/home --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/local/Cellar/dart/2.5.0/libexec/lib/libraries.json package:akassharjun_me/pages/home.dart
    dart --version: 2.5.0 (Fri Sep 6 20:39:27 2019 +0200) on "macos_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:393:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:271:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:259:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE] Failed after 207ms

```

**Comment by vsmenon** [comment] 2019-10-08 03:36
Duplicate of https://github.com/dart-lang/sdk/issues/38102

**Closed by vsmenon** 2019-10-08 03:36 UTC
Labels: area-web
