### ISSUE TITLE
DDC missing error on forEach invocation

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29705] opened 2017-05-24 13:21 UTC
The following results in a runtime error in checked mode (`bar` is invoked with no args).  In DDC, there is no runtime error.  `bar` is incorrectly called with one arg.

```dart
void foo() {
  print('foo');
}

void bar(int x) {
  print('bar $x');
}

List list = <dynamic>[ foo, bar ];

void main() {
  list.forEach((void init()) => init());
}
```

**Comment by vsmenon** [comment] 2017-05-24 13:24
@leafpetersen I think this is ultimately a fuzzy arrow problem.  

`List<dynamic>.forEach` takes a `bottom->void`.  The `forEach` implementation would have to use a `dcall` in this case, but it's not.

If we eliminate fuzzy, the above is a static error, right?

**Comment by leafpetersen** [comment] 2017-05-24 16:50
Yes, this is the fuzzy arrow issue.  Duplicate of https://github.com/dart-lang/sdk/issues/29295 .

https://github.com/dart-lang/sdk/issues/29630 is the issue for eliminating fuzzy arrows.

**Closed by leafpetersen** 2017-05-24 16:50 UTC
Labels: area-dev-compiler, soundness, Type: bug
