### ISSUE TITLE
vm/dart/isolates/reload_many_isolates_live_and_die_test Pass -> RTE on TSAN

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#53454] opened 2023-09-07 10:28 UTC
There are new test failures on [[dart2js] SSA Control flow instructions don't have types...[analyzer] Slimmer _StringTable](https://github.com/dart-lang/sdk/compare/f28d4a5e1d8899b7344c1c79e2eb9017a70f1677~...d7048e410b96f3a29e32fb651879e4f5c8463c04).

The tests
```
vm/dart/isolates/reload_many_isolates_live_and_die_test RuntimeError (expected Pass)
```
are failing on configurations
```
vm-tsan-linux-release-x64
```

Excerpt from [log](https://dart-ci.appspot.com/log/vm-tsan-linux-release-x64/vm-tsan-linux-release-x64/209/vm/dart/isolates/reload_many_isolates_live_and_die_test):
```
stdout:  -> Still waiting ...
stderr: /b/s/w/ir/buildtools/linux-x64/clang/bin/llvm-symbolizer: error: '/memfd:dart-code (deleted)': No such file or directory
stderr: ==================
stderr: WARNING: ThreadSanitizer: data race (pid=48118)
stderr:   Write of size 8 at 0x7b7c0003fe48 by thread T14:
stderr:     #0 dart::Thread::set_top(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread.h:698:34 (dart+0x25204d6)
stderr:     #1 dart::Scavenger::TryAllocateFromTLAB(dart::Thread*, long) out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:256:13 (dart+0x25204d6)
stderr:     #2 dart::Scavenger::TryAllocate(dart::Thread*, long) out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:134:18 (dart+0x25204d6)
stderr:     #3 dart::Heap::AllocateNew(dart::Thread*, long) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:84:27 (dart+0x25204d6)
stderr:     #4 dart::Heap::Allocate(dart::Thread*, long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/heap/heap.h:87:16 (dart+0x231534b)
stderr:     #5 dart::Object::Allocate(long, long, dart::Heap::Space, bool, unsigned long, unsigned long) out/ReleaseTSANX64/../../runtime/vm/object.cc:2837:25 (dart+0x2339428)
stderr:     #6 dart::OneByteString::ObjectPtrType dart::Object::Allocate<dart::OneByteString>(dart::Heap::Space, long) out/ReleaseTSANX64/../../runtime/vm/object.h:729:9 (dart+0x23a7a54)
stderr:     #7 dart::OneByteString::New(long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/object.cc:24515:17 (dart+0x23a7a54)
stderr:     #8 dart::String::FromUTF8(unsigned char const*, long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/object.cc:23758:43 (dart+0x23a7a54)
stderr:     #9 dart::String::New(char const*, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/object.cc:23749:10 (dart+0x2323129)
stderr:     #10 Dart_NewStringFromCString out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:2907:28 (dart+0x2882103)
stderr:     #11 dart::bin::OnIsolateInitialize(void**, char**) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:228:39 (dart+0x200daf0)
stderr:     #12 dart::SpawnIsolateTask::RunLightweight(char const*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:703:26 (dart+0x21dffa2)
stderr:     #13 dart::SpawnIsolateTask::Run() out/ReleaseTSANX64/../../runtime/lib/isolate.cc:645:7 (dart+0x21dfcec)
stderr:     #14 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x24ed9f9)
stderr:     #15 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x24edf27)
stderr:     #16 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x2411133)
stderr: 
stderr:   Previous read of size 8 at 0x7b7c0003fe48 by thread T8 (mutexes: write M0):
stderr:     #0 dart::Page::object_end() const out/ReleaseTSANX64/../../runtime/vm/heap/page.h (dart+0x24ac473)
stderr:     #1 dart::Page::used() const out/ReleaseTSANX64/../../runtime/vm/heap/page.h:107:34 (dart+0x24ac473)
stderr:     #2 dart::SemiSpace::used_in_words() const out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:46:18 (dart+0x24ac473)
stderr:     #3 dart::Scavenger::UsedInWords() const out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:157:17 (dart+0x24ac473)
stderr:     #4 dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0::operator()(dart::IsolateGroup*) const out/ReleaseTSANX64/../../runtime/vm/service.cc:4716:50 (dart+0x24ac473)
stderr:     #5 decltype(std::declval<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&>()(std::declval<dart::IsolateGroup*>())) std::_LIBCPP_ABI_NAMESPACE::__invoke[abi:v15000]<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*>(dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/invoke.h:403:23 (dart+0x24ac473)
stderr:     #6 void std::_LIBCPP_ABI_NAMESPACE::__invoke_void_return_wrapper<void, true>::__call<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*>(dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/invoke.h:488:9 (dart+0x24ac473)
stderr:     #7 std::_LIBCPP_ABI_NAMESPACE::__function::__alloc_func<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0, std::_LIBCPP_ABI_NAMESPACE::allocator<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0>, void (dart::IsolateGroup*)>::operator()[abi:v15000](dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:185:16 (dart+0x24ac473)
stderr:     #8 std::_LIBCPP_ABI_NAMESPACE::__function::__func<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0, std::_LIBCPP_ABI_NAMESPACE::allocator<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0>, void (dart::IsolateGroup*)>::operator()(dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:359:12 (dart+0x24ac473)
stderr:     #9 std::_LIBCPP_ABI_NAMESPACE::__function::__value_func<void (dart::IsolateGroup*)>::operator()[abi:v15000](dart::IsolateGroup*&&) const out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:512:16 (dart+0x22b1213)
stderr:     #10 std::_LIBCPP_ABI_NAMESPACE::function<void (dart::IsolateGroup*)>::operator()(dart::IsolateGroup*) const out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:1187:12 (dart+0x22b1213)
stderr:     #11 dart::IsolateGroup::ForEach(std::_LIBCPP_ABI_NAMESPACE::function<void (dart::IsolateGroup*)>) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:673:5 (dart+0x22b1213)
stderr:     #12 dart::GetProcessMemoryUsageHelper(dart::JSONStream*) out/ReleaseTSANX64/../../runtime/vm/service.cc:4711:7 (dart+0x24aad11)
stderr:     #13 dart::Service::PrintJSONForVM(dart::JSONStream*, bool) out/ReleaseTSANX64/../../runtime/vm/service.cc:5273:26 (dart+0x24aa443)
stderr:     #14 dart::GetVM(dart::Thread*, dart::JSONStream*) out/ReleaseTSANX64/../../runtime/vm/service.cc:5279:3 (dart+0x24b511b)
stderr:     #15 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool) out/ReleaseTSANX64/../../runtime/vm/service.cc:1036:7 (dart+0x24a7fab)
stderr:     #16 dart::Service::HandleRootMessage(dart::Array const&) out/ReleaseTSANX64/../../runtime/vm/service.cc:1070:10 (dart+0x24a878a)
stderr:     #17 dart::DN_HelperVMService_SendRootServiceMessage(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments*) out/ReleaseTSANX64/../../runtime/lib/vmservice.cc:76:10 (dart+0x220155b)
stderr:     #18 dart::BootstrapNatives::DN_VMService_SendRootServiceMessage(dart::Thread*, dart::Zone*, dart::NativeArguments*) out/ReleaseTSANX64/../../runtime/lib/vmservice.cc:73:1 (dart+0x220155b)
stderr:     #19 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) out/ReleaseTSANX64/../../runtime/vm/native_entry.cc:140:37 (dart+0x23121c4)
stderr:     #20 <null> <null> (memfd:dart-code (deleted)+0x2bda)
stderr:     #21 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:37:10 (dart+0x2280ee1)
stderr:     #22 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&) out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:718:28 (dart+0x2280ee1)
stderr:     #23 dart::IsolateMessageHandler::HandleMessage(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message>>) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:1393:15 (dart+0x22b67b0)
stderr:     #24 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:238:16 (dart+0x22f6e96)
stderr:     #25 dart::MessageHandler::TaskCallback() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:457:18 (dart+0x22f7ad4)
stderr:     #26 dart::MessageHandlerTask::Run() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:31:15 (dart+0x22f8043)
stderr:     #27 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x24ed9f9)
stderr:     #28 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x24edf27)
stderr:     #29 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x2411133)
stderr: 
stderr:   Location is heap block of size 3360 at 0x7b7c0003fe00 allocated by thread T5:
stderr:     #0 operator new(unsigned long) ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp:64:3 (dart+0x2000b57)
stderr:     #1 dart::ThreadRegistry::GetFromFreelistLocked(bool) out/ReleaseTSANX64/../../runtime/vm/thread_registry.cc:141:14 (dart+0x24ee0e9)
stderr:     #2 dart::ThreadRegistry::GetFreeThreadLocked(bool) out/ReleaseTSANX64/../../runtime/vm/thread_registry.cc:30:20 (dart+0x24ee0e9)
stderr:     #3 dart::Thread::AddActiveThread(dart::IsolateGroup*, dart::Isolate*, bool, bool) out/ReleaseTSANX64/../../runtime/vm/thread.cc:607:37 (dart+0x24e68c1)
stderr:     #4 dart::Thread::EnterIsolateGroupAsHelper(dart::IsolateGroup*, dart::Thread::TaskKind, bool) out/ReleaseTSANX64/../../runtime/vm/thread.cc:479:20 (dart+0x24e72a9)
stderr:     #5 dart::ConcurrentMarkTask::Run() out/ReleaseTSANX64/../../runtime/vm/heap/marker.cc:828:19 (dart+0x252b058)
stderr:     #6 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x24ed9f9)
stderr:     #7 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x24edf27)
stderr:     #8 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x2411133)
stderr: 
stderr:   Mutex M0 (0x7b6800000858) created at:
stderr:     #0 pthread_mutex_init ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1341:3 (dart+0x1f7d000)
stderr:     #1 dart::Mutex::Mutex(char const*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:308:12 (dart+0x24114f7)
stderr:     #2 dart::Scavenger::Scavenger(dart::Heap*, long) out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.cc:798:12 (dart+0x253bb47)
stderr:     #3 dart::Heap::Heap(dart::IsolateGroup*, bool, long, long) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:49:7 (dart+0x251fcdf)
stderr:     #4 dart::Heap::Init(dart::IsolateGroup*, bool, long, long) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:716:34 (dart+0x2523b43)
stderr:     #5 dart::IsolateGroup::CreateHeap(bool, bool) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:472:3 (dart+0x22b015f)
stderr:     #6 Dart_CreateIsolateGroup out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1367:10 (dart+0x286e58d)
stderr:     #7 dart::bin::CreateIsolateGroupAndSetupHelper(bool, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**, int*, bool) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:815:15 (dart+0x200bead)
stderr:     #8 dart::bin::RunMainIsolate(char const*, char const*, bool, dart::bin::CommandLineOptions*) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1031:26 (dart+0x200b642)
stderr:     #9 dart::bin::main(int, char**) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1427:9 (dart+0x200cbdb)
stderr:     #10 main out/ReleaseTSANX64/../../runtime/bin/main.cc:9:3 (dart+0x200b4f4)
stderr: 
stderr:   Thread T14 'DartWorker' (tid=48154, running) created by thread T12 at:
stderr:     #0 pthread_create ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1048:3 (dart+0x1f7b68b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:173:12 (dart+0x2410ff3)
stderr:     #2 dart::ThreadPool::Worker::StartThread() out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296:16 (dart+0x24ed151)
stderr:     #3 dart::ThreadPool::RunImpl(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::ThreadPool::Task, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::ThreadPool::Task>>) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94:17 (dart+0x24ed151)
stderr:     #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46:12 (dart+0x22f6916)
stderr:     #5 dart::MessageHandler::Run(dart::ThreadPool*, dart::MessageHandler::MessageStatus (*)(unsigned long), void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:119:24 (dart+0x22f6916)
stderr:     #6 dart::Isolate::Run() out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2331:22 (dart+0x22ba07c)
stderr:     #7 Dart_RunLoopAsync out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:2095:12 (dart+0x287303d)
stderr:     #8 dart::SpawnIsolateTask::Run(dart::Isolate*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:747:10 (dart+0x21e057d)
stderr:     #9 dart::SpawnIsolateTask::RunLightweight(char const*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:712:5 (dart+0x21dffd4)
stderr:     #10 dart::SpawnIsolateTask::Run() out/ReleaseTSANX64/../../runtime/lib/isolate.cc:645:7 (dart+0x21dfcec)
stderr:     #11 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x24ed9f9)
stderr:     #12 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x24edf27)
stderr:     #13 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x2411133)
stderr: 
stderr:   Thread T8 'DartWorker' (tid=48144, running) created by thread T2 at:
stderr:     #0 pthread_create ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1048:3 (dart+0x1f7b68b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:173:12 (dart+0x2410ff3)
stderr:     #2 dart::ThreadPool::Worker::StartThread() out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296:16 (dart+0x24ed151)
stderr:     #3 dart::ThreadPool::RunImpl(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::ThreadPool::Task, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::ThreadPool::Task>>) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94:17 (dart+0x24ed151)
stderr:     #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46:12 (dart+0x22f6916)
stderr:     #5 dart::MessageHandler::Run(dart::ThreadPool*, dart::MessageHandler::MessageStatus (*)(unsigned long), void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:119:24 (dart+0x22f6916)
stderr:     #6 dart::RunServiceTask::Run() out/ReleaseTSANX64/../../runtime/vm/service_isolate.cc:409:33 (dart+0x24c7b5f)
stderr:     #7 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x24ed9f9)
stderr:     #8 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x24edf27)
stderr:     #9 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x2411133)
stderr: 
stderr:   Thread T5 'DartWorker' (tid=48132, running) created by main thread at:
stderr:     #0 pthread_create ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1048:3 (dart+0x1f7b68b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:173:12 (dart+0x2410ff3)
stderr:     #2 dart::ThreadPool::Worker::StartThread() out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296:16 (dart+0x24ed151)
stderr:     #3 dart::ThreadPool::RunImpl(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::ThreadPool::Task, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::ThreadPool::Task>>) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94:17 (dart+0x24ed151)
stderr:     #4 bool dart::ThreadPool::Run<dart::ConcurrentMarkTask, dart::GCMarker*, dart::IsolateGroup* const&, dart::PageSpace*&, dart::MarkingVisitorBase<true>*&>(dart::GCMarker*&&, dart::IsolateGroup* const&, dart::PageSpace*&, dart::MarkingVisitorBase<true>*&) out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46:12 (dart+0x2527034)
stderr:     #5 dart::GCMarker::StartConcurrentMark(dart::PageSpace*) out/ReleaseTSANX64/../../runtime/vm/heap/marker.cc:947:42 (dart+0x2527034)
stderr:     #6 dart::PageSpace::CollectGarbageHelper(dart::Thread*, bool, bool) out/ReleaseTSANX64/../../runtime/vm/heap/pages.cc:1039:14 (dart+0x25339dc)
stderr:     #7 dart::PageSpace::CollectGarbage(dart::Thread*, bool, bool) out/ReleaseTSANX64/../../runtime/vm/heap/pages.cc:984:3 (dart+0x2533416)
stderr:     #8 dart::Heap::StartConcurrentMarking(dart::Thread*, dart::GCReason) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:655:14 (dart+0x2522670)
stderr:     #9 dart::Heap::CheckConcurrentMarking(dart::Thread*, dart::GCReason, long) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:640:9 (dart+0x25217ee)
stderr:     #10 dart::PageSpace::TryAllocateInFreshPage(long, dart::FreeList*, bool, dart::PageSpace::GrowthPolicy, bool) out/ReleaseTSANX64/../../runtime/vm/heap/pages.cc:331:12 (dart+0x252fc03)
stderr:     #11 dart::PageSpace::TryAllocateInternal(long, dart::FreeList*, bool, dart::PageSpace::GrowthPolicy, bool, bool) out/ReleaseTSANX64/../../runtime/vm/heap/pages.cc:412:16 (dart+0x25301a7)
stderr:     #12 dart::PageSpace::TryAllocate(long, bool, dart::PageSpace::GrowthPolicy) out/ReleaseTSANX64/../../runtime/vm/heap/pages.h:146:12 (dart+0x2520af2)
stderr:     #13 dart::Heap::AllocateOld(dart::Thread*, long, bool) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:123:29 (dart+0x2520af2)
stderr:     #14 dart::Heap::Allocate(dart::Thread*, long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/heap/heap.h (dart+0x231536d)
stderr:     #15 dart::Object::Allocate(long, long, dart::Heap::Space, bool, unsigned long, unsigned long) out/ReleaseTSANX64/../../runtime/vm/object.cc:2837:25 (dart+0x2339428)
stderr:     #16 dart::ICData::ObjectPtrType dart::Object::Allocate<dart::ICData>(dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/object.h:720:51 (dart+0x238afb4)
stderr:     #17 dart::ICData::NewDescriptor(dart::Zone*, dart::Function const&, dart::String const&, dart::Array const&, long, long, dart::ICData::RebindRule, dart::AbstractType const&) out/ReleaseTSANX64/../../runtime/vm/object.cc:17227:28 (dart+0x238afb4)
stderr:     #18 dart::ICData::New(dart::Function const&, dart::String const&, dart::Array const&, long, long, dart::ICData::RebindRule, dart::AbstractType const&) out/ReleaseTSANX64/../../runtime/vm/object.cc:17261:7 (dart+0x238b1fd)
stderr:     #19 dart::FlowGraphCompiler::GetOrAddInstanceCallICData(long, dart::String const&, dart::Array const&, long, dart::AbstractType const&, dart::Function const&) out/ReleaseTSANX64/../../runtime/vm/compiler/backend/flow_graph_compiler.cc:1881:15 (dart+0x26375a1)
stderr:     #20 dart::InstanceCallInstr::EmitNativeCode(dart::FlowGraphCompiler*) out/ReleaseTSANX64/../../runtime/vm/compiler/backend/il.cc:5074:30 (dart+0x265dcee)
stderr:     #21 dart::FlowGraphCompiler::VisitBlocks() out/ReleaseTSANX64/../../runtime/vm/compiler/backend/flow_graph_compiler.cc:745:14 (dart+0x263341b)
stderr:     #22 dart::FlowGraphCompiler::CompileGraph() out/ReleaseTSANX64/../../runtime/vm/compiler/backend/flow_graph_compiler.cc:635:3 (dart+0x2632ad6)
stderr:     #23 dart::CompilerPass_GenerateCode::DoBody(dart::CompilerPassState*) const out/ReleaseTSANX64/../../runtime/vm/compiler/compiler_pass.cc:612:1 (dart+0x276b7a9)
stderr:     #24 dart::CompilerPass::Run(dart::CompilerPassState*) const out/ReleaseTSANX64/../../runtime/vm/compiler/compiler_pass.cc:229:18 (dart+0x2768fd3)
stderr:     #25 dart::CompilerPass::GenerateCode(dart::CompilerPassState*) out/ReleaseTSANX64/../../runtime/vm/compiler/compiler_pass.h:158:53 (dart+0x250a580)
stderr:     #26 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*) out/ReleaseTSANX64/../../runtime/vm/compiler/jit/compiler.cc:596:7 (dart+0x250a580)
stderr:     #27 dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long) out/ReleaseTSANX64/../../runtime/vm/compiler/jit/compiler.cc:729:46 (dart+0x250b1ea)
stderr:     #28 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&) out/ReleaseTSANX64/../../runtime/vm/compiler/jit/compiler.cc:860:10 (dart+0x250ab6a)
stderr:     #29 dart::Function::EnsureHasCode() const out/ReleaseTSANX64/../../runtime/vm/object.cc:11269:28 (dart+0x236c5de)
stderr:     #30 dart::TrySwitchInstanceCall(dart::Thread*, dart::StackFrame*, dart::Code const&, dart::Function const&, dart::ICData const&, dart::Function const&) out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:1659:61 (dart+0x249552a)
stderr:     #31 dart::PatchableCallHandler::DoICDataMissJIT(dart::ICData const&, dart::Object const&, dart::Function const&) out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2322:7 (dart+0x2495756)
stderr:     #32 dart::PatchableCallHandler::HandleMissJIT(dart::Object const&, dart::Code const&, dart::Function const&) out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2607:7 (dart+0x24962c3)
stderr:     #33 dart::PatchableCallHandler::ResolveSwitchAndReturn(dart::Object const&) out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2555:3 (dart+0x24962c3)
stderr:     #34 dart::InlineCacheMissHandler(dart::Thread*, dart::Zone*, dart::GrowableArray<dart::Instance const*> const&, dart::ICData const&, dart::NativeArguments) out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2637:11 (dart+0x249e088)
stderr:     #35 dart::DRT_HelperInlineCacheMissHandlerOneArg(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments) out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2654:3 (dart+0x24965f7)
stderr:     #36 dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments) out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2648:1 (dart+0x24965f7)
stderr:     #37 <null> <null> (memfd:dart-code (deleted)+0x2a69)
stderr:     #38 dart::Library::Invoke(dart::String const&, dart::Array const&, dart::Array const&, bool, bool) const out/ReleaseTSANX64/../../runtime/vm/object.cc:14413:10 (dart+0x237dbaf)
stderr:     #39 Dart_Invoke out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:4722:16 (dart+0x28935a9)
stderr:     #40 dart::bin::SingleArgDart_Invoke(_Dart_Handle*, char const*, _Dart_Handle*) out/ReleaseTSANX64/../../runtime/bin/dartutils.cc:305:10 (dart+0x21a87d8)
stderr:     #41 dart::bin::DartUtils::SetWorkingDirectory() out/ReleaseTSANX64/../../runtime/bin/dartutils.cc:369:10 (dart+0x21a87d8)
stderr:     #42 dart::bin::DartUtils::PrepareBuiltinLibrary(_Dart_Handle*, _Dart_Handle*, bool, bool) out/ReleaseTSANX64/../../runtime/bin/dartutils.cc:463:14 (dart+0x21a87d8)
stderr:     #43 dart::bin::DartUtils::PrepareForScriptLoading(bool, bool) out/ReleaseTSANX64/../../runtime/bin/dartutils.cc:562:12 (dart+0x21a8cfc)
stderr:     #44 dart::bin::SetupCoreLibraries(_Dart_Isolate*, dart::bin::IsolateData*, bool, char const**) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:166:12 (dart+0x200e7f1)
stderr:     #45 dart::bin::IsolateSetupHelper(_Dart_Isolate*, bool, char const*, char const*, bool, Dart_IsolateFlags*, char**, int*) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:273:12 (dart+0x200e1d8)
stderr:     #46 dart::bin::CreateIsolateGroupAndSetupHelper(bool, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**, int*, bool) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:831:23 (dart+0x200bed2)
stderr:     #47 dart::bin::RunMainIsolate(char const*, char const*, bool, dart::bin::CommandLineOptions*) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1031:26 (dart+0x200b642)
stderr:     #48 dart::bin::main(int, char**) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1427:9 (dart+0x200cbdb)
stderr:     #49 main out/ReleaseTSANX64/../../runtime/bin/main.cc:9:3 (dart+0x200b4f4)
stderr: 
stderr: SUMMARY: ThreadSanitizer: data race out/ReleaseTSANX64/../../runtime/vm/thread.h:698:34 in dart::Thread::set_top(unsigned long)
stderr: ==================

stderr:
Unhandled exception:
Bad state: The client closed with pending request "getVM".

--- Re-run this test:
python3 tools/test.py -n vm-tsan-linux-release-x64 vm/dart/isolates/reload_many_isolates_live_and_die_test
```

/cc @mkustermann

**Comment by mkustermann** [comment] 2023-09-07 10:48
This seems more GC related. I think @rmacnak-google has this already tracked in another issue.

**Comment by rmacnak-google** [comment] 2023-09-07 17:16
Duplicate of #52862

**Closed by rmacnak-google** 2023-09-07 17:16 UTC
Labels: area-vm, gardening
