### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by HiroyukTamura** [dart-lang/sdk#39239] opened 2019-11-05 17:16 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in VariableDeclarationImpl in VariableDeclarationListImpl in FieldDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#6      VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10523:19)
#7      RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1302:10)
#8      LinterVisitor.visitVariableDeclaration (package:analyzer/src/lint/linter_visitor.dart:673:11)
#9      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10517:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#11     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10619:16)
#12     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1308:10)
#13     LinterVisitor.visitVariableDeclarationList (package:analyzer/src/lint/linter_visitor.dart:679:11)
#14     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10613:15)
#15     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4097:17)
#16     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:857:10)
#17     LinterVisitor.visitFieldDeclaration (package:analyzer/src/lint/linter_visitor.dart:246:11)
#18     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4092:49)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#20     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#21     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#22     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#23     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#25     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#26     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#27     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#28     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#29     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:353:10)
#30     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:206:11)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#32     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:201:35)
#33     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#34     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#35     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#36     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#37     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#38     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#39     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:927:33)
<asynchronous suspension>
#40     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#41     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#42     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#43     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#44     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#45     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     Driver._captureEx...
```

For additional log information, please append the contents of
file:///private/var/folders/yv/znk7l5z91bn4w9h21nzq2ydw0000gp/T/report.txt.

**Comment by keertip** [comment] 2019-11-06 09:33
Thanks for the report! This was previously reported in #39234, please follow there.

**Comment by keertip** [comment] 2019-11-06 09:33
Duplicate of #39234

**Closed by keertip** 2019-11-06 09:33 UTC
Labels: analyzer-crash-report, area-analyzer
