### ISSUE TITLE
IntelliJ: Flutter "closing tags" show up on non-Flutter projects

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32118] opened 2018-02-10 21:16 UTC
This is with the latest dev SDK.

Dart Plugin v173.3942.31

```
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018
```

<img width="573" alt="screen shot 2018-02-10 at 1 15 11 pm" src="https://user-images.githubusercontent.com/168174/36066759-785afe54-0e64-11e8-802e-9679639db576.png">

**Comment by zoechi** [comment] 2018-02-11 13:57
You can disable it in 

![image](https://user-images.githubusercontent.com/405837/36074123-d96e8206-0f3b-11e8-9f04-6bc0c8bea4b5.png)
(last option)

**Comment by devoncarew** [comment] 2018-02-15 14:54
This is not specifically a flutter feature; it will show closing labels for when there are nested, multi-line constructor calls, flutter code or no. It just tends to e most valuable in large flutter build() methods.

We have made tweaks to the heuristic for when to show labels in order to make them less noisy; feel free to file issues if you think they're showing up in more places than they should. Closing this as intended behavior.

@jwren

**Closed by devoncarew** 2018-02-15 14:54 UTC
Labels: area-intellij
