### ISSUE TITLE
Analysis server error causes WebStorm to stop analyzing sources

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/sdk#25035] opened 2015-11-24 19:40 UTC
This may contain some info for hunting down what's been described in https://groups.google.com/a/dartlang.org/forum/#!topic/misc/pQCl_cGA_q0. Also see #24856

Whenever I encounter this WebStorm needs to be restarted to get back any analysis. Below is the event log from WebStorm. Platform is Windows with 1.14.0-dev.1.0.

```
Throwable
Dart analysis server, SDK version 1.14.0-dev.1.0, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor Cannot compute RESOLVED_UNIT for C:\xxx\xxx.dart in C:\xxx\xxx.dart 

#0 AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679)
#1 AnalysisContextImpl.resolveCompilationUnit2(package:analyzer/src/context/context.dart:1214)
#2 DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:30)
#3 computeAssists (package:analysis_server/src/services/correction/assist.dart:26)
#4 EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140)
#5 EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191)
#6 AnalysisServer.handleRequest. .  (package:analysis_server/src/analysis_server.dart:685)
#7 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#8 AnalysisServer.handleRequest.  (package:analysis_server/src/analysis_server.dart:681)
#9 _rootRun (dart:async/zone.dart:907)
#10 _CustomZone.run (dart:async/zone.dart:802)
#11 _CustomZone.runGuarded (dart:async/zone.dart:708)
#12 runZoned (dart:async/zone.dart:1243)
#13 AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:680)
#14 ByteStreamServerChannel._readRequest.  (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#15 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#16 ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#17 ByteStreamServerChannel.listen.  (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#18 _rootRunUnary (dart:async/zone.dart:914)
#19 _CustomZone.runUnary (dart:async/zone.dart:810)
#20 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#21 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#22 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#23 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#24 _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#25 _StringAdapterSink.add (dart:convert/string_conversion.dart:256) 
#26 _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127) 
#27 _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102) 
#28 StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180) 
#29 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80) 
#30 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119) 
#31 _rootRunUnary (dart:async/zone.dart:914) 
#32 _CustomZone.runUnary (dart:async/zone.dart:810) 
#33 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#34 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#35 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#36 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67) 
#37 _EventSinkWrapper.add (dart:async/stream_transformers.dart:14) 
#38 _StringAdapterSink.add (dart:convert/string_conversion.dart:256) 
#39 _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260) 
#40 _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336) 
#41 _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329) 
#42 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80) 
#43 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119) 
#44 _rootRunUnary (dart:async/zone.dart:914) 
#45 _CustomZone.runUnary (dart:async/zone.dart:810) 
#46 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#47 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#48 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#49 _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744) 
#50 _StreamController._add (dart:async/stream_controller.dart:616) 
#51 _StreamController.add (dart:async/stream_controller.dart:562) 
#52 _Socket._onData (dart:io-patch/socket_patch.dart:1646) 
#53 _rootRunUnary (dart:async/zone.dart:918) 
#54 _CustomZone.runUnary (dart:async/zone.dart:810) 
#55 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#56 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#57 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#58 _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744) 
#59 _StreamController._add (dart:async/stream_controller.dart:616) 
#60 _StreamController.add (dart:async/stream_controller.dart:562) 
#61 _RawSocket._RawSocket.  (dart:io-patch/socket_patch.dart:1215) 
#62 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749) 
#63 _microtaskLoop (dart:async/schedule_microtask.dart:43) 
#64 _microtaskLoopEntry (dart:async/schedule_microtask.dart:52) 
#65 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96) 
#66 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149) Caused by Infinite loop while performing task InferInstanceMembersInUnitTask for C:\xxx\xxx.dart in C:\xxx\xxx.dart 
#0 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:307) 
#1 AnalysisTask.perform (package:analyzer/task/model.dart:210) 
#2 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272) 
#3 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247) 
#4 AnalysisContextImpl.performAnalysisTask.  (package:analyzer/src/context/context.dart:1116) 
#5 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188) 
#6 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114) 
#7 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367) 
#8 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797) 
#9 Future.Future.  (dart:async/future.dart:118) 
#10 _rootRun (dart:async/zone.dart:903) 
#11 _CustomZone.run (dart:async/zone.dart:802) 
#12 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#13 _CustomZone.bindCallback.  (dart:async/zone.dart:733) 
#14 _rootRun (dart:async/zone.dart:907) 
#15 _CustomZone.run (dart:async/zone.dart:802) 
#16 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#17 _CustomZone.bindCallback.  (dart:async/zone.dart:733) 
#18 Timer._createTimer.  (dart:async-patch/timer_patch.dart:16) 
#19 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385) 
#20 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148) 
#0 AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679) 
#1 AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1214) 
#2 DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:30) 
#3 computeAssists (package:analysis_server/src/services/correction/assist.dart:26) 
#4 EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140) 
#5 EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191) 
#6 AnalysisServer.handleRequest. .  (package:analysis_server/src/analysis_server.dart:685) 
#7 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188) 
#8 AnalysisServer.handleRequest.  (package:analysis_server/src/analysis_server.dart:681) 
#9 _rootRun (dart:async/zone.dart:907) 
#10 _CustomZone.run (dart:async/zone.dart:802) 
#11 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#12 runZoned (dart:async/zone.dart:1243) 
#13 AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:680) 
#14 ByteStreamServerChannel._readRequest.  (package:analysis_server/src/channel/byte_stream_channel.dart:169) 
#15 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188) 
#16 ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160) 
#17 ByteStreamServerChannel.listen.  (package:analysis_server/src/channel/byte_stream_channel.dart:109) 
#18 _rootRunUnary (dart:async/zone.dart:914) 
#19 _CustomZone.runUnary (dart:async/zone.dart:810) 
#20 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#21 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#22 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#23 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67) 
#24 _EventSinkWrapper.add (dart:async/stream_transformers.dart:14) 
#25 _StringAdapterSink.add (dart:convert/string_conversion.dart:256) 
#26 _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127) 
#27 _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102) 
#28 StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180) 
#29 _ConverterStr ...
```

**Comment by donny-dont** [comment] 2015-11-24 19:42
Only way to get analysis back to working is to restart WebStorm.

**Comment by donny-dont** [comment] 2015-11-24 19:45
#24856 might be related.

**Comment by zoechi** [comment] 2015-11-25 17:31
#25012 also seems related.

I worked a while on https://github.com/bwu-dart/bwu_datagrid/tree/polymer1 today and didn't have any issues at all anymore.
Then I switched to https://github.com/bwu-dart/bwu_docker and since then I get lots of these exceptions.

In bwu_datagrid I burned down all reported issues (incl. strong mode hints) and was mostly done (I wasn't able to fix about 10). 
In bwu_docker I just enabled strong-mode, and get tons of issues reported by the analyzer.

**Comment by scheglov** [comment] 2015-11-25 17:44
Do you have `strong-mode: true` in the `.analysis_options` file?

**Comment by zoechi** [comment] 2015-11-25 18:02
yes, strong-mode always enabled

**Comment by donny-dont** [comment] 2015-11-25 18:03
@scheglov yep this is with strong mode as well.

**Comment by donny-dont** [comment] 2015-11-25 23:34
I tried setting strong_mode to false in .analysis_options and then I'm getting issues with `GenerateLintsTask`. If I just remove the contents of the file I'm not seeing anything in the event log within WebStorm.

**Comment by scheglov** [comment] 2015-11-25 23:40
@jmesserly @leafpetersen Could you please check the `Caused by Infinite loop while performing task InferInstanceMembersInUnitTask for C:\xxx\xxx.dart in C:\xxx\xxx.dart` exception?

@pq Are the linter issues fixes fixed in this version?

@donny-dont Hm... `I'm not seeing anything in the event log within WebStorm` - is it good or bad? :-)

**Comment by donny-dont** [comment] 2015-11-25 23:41
@scheglov that's good if I'm not using the linter or strong mode. Bad otherwise :wink:

**Comment by MikeMitterer** [comment] 2015-11-26 09:53
I just got the following Exception in IJ/Dart plugin:
No chance to bring DA back to live - I had to restart IJ
```
Dart analysis server, SDK version 1.13.0, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor RangeError (index): Invalid value: Not in range 0..2159, inclusive: 2167 
#0 _StringBase.codeUnitAt (dart:core-patch/string_patch.dart:233) 
#1 CorrectionUtils.getLineContentStart (package:analysis_server/src/services/correction/util.dart:861) 
#2 CorrectionUtils.getPrefix (package:analysis_server/src/services/correction/util.dart:1021) 
#3 CorrectionUtils.getNodePrefix (package:analysis_server/src/services/correction/util.dart:964) 
#4 AssistProcessor._addProposal_replaceConditionalWithIfElse (package:analysis_server/src/services/correction/assist_internal.dart:1436) 
#5 AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:102) 
#6 DefaultAssistContributor.internalComputeAssists (package:analysis_server/src/services/correction/assist_internal.dart:2053) 
#7 DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:34) 
#8 computeAssists (package:analysis_server/src/services/correction/assist.dart:26) 
#9 EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140) 
#10 EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191) 
#11 AnalysisServer.handleRequest. .  (package:analysis_server/src/analysis_server.dart:690) 
#12 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170) 
#13 AnalysisServer.handleRequest.  (package:analysis_server/src/analysis_server.dart:686) 
#14 _rootRun (dart:async/zone.dart:907) 
#15 _CustomZone.run (dart:async/zone.dart:802) 
#16 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#17 runZoned (dart:async/zone.dart:1243) 
#18 AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:685) 
#19 ByteStreamServerChannel._readRequest.  (package:analysis_server/src/channel/byte_stream_channel.dart:169) 
#20 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170) 
#21 ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160) 
#22 ByteStreamServerChannel.listen.  (package:analysis_server/src/channel/byte_stream_channel.dart:109) 
#23 _rootRunUnary (dart:async/zone.dart:914) 
#24 _CustomZone.runUnary (dart:async/zone.dart:810) 
#25 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#26 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#27 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#28 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67) 
#29 _EventSinkWrapper.add (dart:async/stream_transformers.dart:14) 
#30 _StringAdapterSink.add (dart:convert/string_conversion.dart:256) 
#31 _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127) 
#32 _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102) 
#33 StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180) 
#34 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80) 
#35 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119) 
#36 _rootRunUnary (dart:async/zone.dart:914) 
#37 _CustomZone.runUnary (dart:async/zone.dart:810) 
#38 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#39 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#40 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#41 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67) 
#42 _EventSinkWrapper.add (dart:async/stream_transformers.dart:14) 
#43 _StringAdapterSink.add (dart:convert/string_conversion.dart:256) 
#44 _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260) 
#45 _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336) 
#46 _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329) 
#47 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80) 
#48 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119) 
#49 _rootRunUnary (dart:async/zone.dart:914) 
#50 _CustomZone.runUnary (dart:async/zone.dart:810) 
#51 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#52 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#53 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#54 _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744) 
#55 _StreamController._add (dart:async/stream_controller.dart:616) 
#56 _StreamController.add (dart:async/stream_controller.dart:562) 
#57 _Socket._onData (dart:io-patch/socket_patch.dart:1646) 
#58 _rootRunUnary (dart:async/zone.dart:918) 
#59 _CustomZone.runUnary (dart:async/zone.dart:810) 
#60 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#61 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#62 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#63 _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744) 
#64 _StreamController._add (dart:async/stream_controller.dart:616) 
#65 _StreamController.add (dart:async/stream_controller.dart:562) 
#66 _RawSocket._RawSocket.  (dart:io-patch/socket_patch.dart:1215) 
#67 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749) 
#68 _microtaskLoop (dart:async/schedule_microtask.dart:43) 
#69 _microtaskLoopEntry (dart:async/schedule_microtask.dart:52) 
#70 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96) 
#71 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151) 
#0 _StringBase.codeUnitAt (dart:core-patch/string_patch.dart:233) 
#1 CorrectionUtils.getLineContentStart (package:analysis_server/src/services/correction/util.dart:861) 
#2 CorrectionUtils.getPrefix (package:analysis_server/src/services/correction/util.dart:1021) 
#3 CorrectionUtils.getNodePrefix (package:analysis_server/src/services/correction/util.dart:964) 
#4 AssistProcessor._addProposal_replaceConditionalWithIfElse (package:analysis_server/src/services/correction/assist_internal.dart:1436) 
#5 AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:102) 
#6 DefaultAssistContributor.internalComputeAssists (package:analysis_server/src/services/correction/assist_internal.dart:2053) 
#7 DartAssistContributor.computeAssists (package:analysis_server/plugin/edit/assist/assist_dart.dart:34) 
#8 computeAssists (package:analysis_server/src/services/correction/assist.dart:26) 
#9 EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:140) 
#10 EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:191) 
#11 AnalysisServer.handleRequest. .  (package:analysis_server/src/analysis_server.dart:690) 
#12 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170) 
#13 AnalysisServer.handleRequest.  (package:analysis_server/src/analysis_server.dart:686) 
#14 _rootRun (dart:async/zone.dart:907) 
#15 _CustomZone.run (dart:async/zone.dart:802) 
#16 _CustomZone.runGuarded (dart:async/zone.dart:708) 
#17 runZoned (dart:async/zone.dart:1243) 
#18 AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:685) 
#19 ByteStreamServerChannel._readRequest.  (package:analysis_server/src/channel/byte_stream_channel.dart:169) 
#20 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170) 
#21 ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160) 
#22 ByteStreamServerChannel.listen.  (package:analysis_server/src/channel/byte_stream_channel.dart:109) 
#23 _rootRunUnary (dart:async/zone.dart:914) 
#24 _CustomZone.runUnary (dart:async/zone.dart:810) 
#25 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#26 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#27 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#28 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67) 
#29 _EventSinkWrapper.add (dart:async/stream_transformers.dart:14) 
#30 _StringAdapterSink.add (dart:convert/string_conversion.dart:256) 
#31 _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127) 
#32 _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102) 
#33 StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180) 
#34 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80) 
#35 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119) 
#36 _rootRunUnary (dart:async/zone.dart:914) 
#37 _CustomZone.runUnary (dart:async/zone.dart:810) 
#38 _CustomZone.runUnaryGuarded (dart:async/zone.dart:716) 
#39 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341) 
#40 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270) 
#41 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67) 
#42 _EventSinkWrapper.add (dart:async/stream_transformers.dart:14) 
#43 _StringAdapterSink.add (dart:convert/string_conversion.dart:256) 
#44 _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260) 
#45 _Utf8ConversionSink.addSlice (dart:convert/string_con ...
```

**Comment by leafpetersen** [comment] 2015-12-03 22:29
I pulled down bwu_docker and spent some time poking at it in Intellij trying to reproduce the InfiniteLoop exception.  I haven't seen any errors yet.  @zoechi @donny-dont @MikeMitterer are there any specific combinations of repo/files/edits that you can point me at to reproduce?

**Comment by donny-dont** [comment] 2015-12-03 22:31
@leafpetersen its all around having .analysis_options and turning on strong mode or really any of the lints. I don't see .analysis_options in bwu_docker.

**Comment by leafpetersen** [comment] 2015-12-03 22:38
@donny-dont Sorry, should have mentioned that I added my own .analysis_options with strong mode on it.  What else is in your .analysis_options?  You're on WebStorm?  I'm currently using Intellij, so I can try downloading WebStorm if needed, but I'd be a little surprised if that made the difference.

**Comment by jmesserly** [comment] 2015-12-03 22:43
@leafpetersen -- I use WebStorm and haven't ever noticed any difference w.r.t. IntelliJ. What matters is the Dart plugin version & the SDK version.

**Comment by donny-dont** [comment] 2015-12-03 22:58
Dart version for me has always been latest dev. Think @zoechi does bleeding edge.

**Comment by zoechi** [comment] 2015-12-04 08:13
I didn't get analysis server exceptions today so far as well. (latest bleeding edge).

**Comment by MikeMitterer** [comment] 2015-12-04 08:13
I'm sure DA works for most single dart-module projects. It has problems with larger projects. Here is mine...
You know that if you include the same library in multiple projects that DA analyses the same file over and over again? In my case the init-analyses takes about 30 to 40 min!!!! (2 month ago it took about 2h - big improvement but still a bit annoying...) DA does not cache - another problem.   
![screenshot-1949](https://cloud.githubusercontent.com/assets/116654/11584707/5af29ec2-9a66-11e5-86d4-f00c0c9341d2.png)

**Comment by MikeMitterer** [comment] 2015-12-04 09:33
If I "pub update" on one of my Dart-Modules it pushes DA up to 100% for about 12mins!!!!
I'm working on a i7 3.5GHZ, 16 GB RAM and Samsung SSD Pro BTW - so 12mins is quite long!
cc: @scheglov 

![screenshot-1951](https://cloud.githubusercontent.com/assets/116654/11586227/e8b89eae-9a71-11e5-86a0-44507e3fac82.png)

**Comment by MikeMitterer** [comment] 2015-12-04 09:54
E.g. If DA is on 100% it takes ~30secs until IntelliJ shows an error or a warning already reported in the DA-Tab

**Comment by jmesserly** [comment] 2015-12-11 23:49
I just saw this one: https://github.com/dart-lang/sdk/issues/25239
Not sure if it's the same issue, but similar "infinite loop in InferInstanceMembersInUnitTask" message

**Comment by jmesserly** [comment] 2015-12-11 23:51
p.s. y'all are brave! :) ... I'm trying to use strong-mode in IntelliJ to get analyzer itself strong-mode clean. Definitely has some rough edges. Now that we're dogfooding, hopefully we can get them smoothed out.

**Comment by zoechi** [comment] 2015-12-12 09:06
I didn't have any serious issues the last ~3 days with bleeding_edge but I it might be related what projects I'm working on and what other projects are opened at the same time. This changes frequently.

**Comment by jmesserly** [comment] 2016-01-05 00:13
We just fixed a few bugs that might help, definitely give it a try when the next dev build lands (something later than 1.14.0-dev.5.0)

**Comment by jmesserly** [comment] 2016-02-18 00:55
And we just fixed a few more -- if you had a strong mode and a non-strong mode project open, confusion happened in the SDK.

Once the next dev build lands, give it another shot and let us know if this reoccurs. Tentatively I'm going to assume it's been fixed. But we can always reopen (or open a new bug, as needed). Cheers.

**Closed by jmesserly** 2016-02-18 00:55 UTC
Labels: analyzer-stability, analyzer-strong-mode, area-analyzer, priority-high, Type-Defect
