### ISSUE TITLE
Error instead of warning in analyzer when two libraries with the same name are imported

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42481] opened 2020-06-25 09:40 UTC
According to the Dart Language [specification](https://spec.dart.dev/DartLangSpecDraft.pdf) (18.1 Imports)

> It is a static warning to import two different libraries with the same name
> unless their name is the empty string

But analyzer produces an error in this case instead of warning
```dart
// file library_name_t01_lib1.dart
library duplicate_name;

var foo = 1;

// file library_name_t01_lib2.dart
library duplicate_name;

var bar = 2;

// file library_name_t01.dart
import "library_name_t01_lib1.dart";
import "library_name_t01_lib2.dart";

main() {
  foo == 1;
  bar == 2;
}
```
Analyzer produces
```
Analyzing library_name_t01.dart...
error - The imported libraries 'file:///co19/Language/Libraries_and_Scripts/Imports/library_name_t01_lib1.dart' and 'file:///co19/Language/Libraries_and_Scripts/Imports/library_name_t01_lib2.dart' can't have the same name 'duplicate_name'. - library_name_t01.dart:17:1 - import_duplicated_library_named                                                                                                              
1 error found.
```
There must be a static warning instead of error here
`dartanalyzer version 2.9.0-18.0.dev `

**Comment by lrhn** [comment] 2020-06-25 10:25
@eernstg Is this one of our known "warning"/"error" discrepancies.

(There were some problems that we intended to be errors, but where it turned out that our tools had only made them warnings. To avoid breaking people, we specified them as warnings instead, but in parallel with that, the analyzer made some of them errors anyway. We now have to decide whether to keep them errors, as originally intended, or not.)

**Comment by sgrekhov** [comment] 2020-06-25 12:50
Forgot to add that this is a warning in CFE and dart2js. It's an error in Analyzer only

**Comment by eernstg** [comment] 2020-07-20 12:17
Please note that the specification was changed (https://github.com/dart-lang/language/pull/1083, https://github.com/dart-lang/language/pull/1096) to eliminate the error caused by an import or export of two libraries with the same name.

Implementation issues are https://github.com/dart-lang/sdk/issues/42700 and https://github.com/dart-lang/sdk/issues/42699.

**Comment by eernstg** [comment] 2020-07-20 12:26
Commit https://github.com/dart-lang/sdk/commit/ef147c0a95bc345fbfca99946434745bf484ca08 implies that the analyzer implements the new behavior. So given that the CFE is covered by #42700, I'll close this issue.

**Closed by eernstg** 2020-07-20 12:26 UTC
Labels: analyzer-spec, area-analyzer
