### ISSUE TITLE
JSON_Serializable 1.5.1 nested objects compiler error

### ISSUE THREAD

**Issue by deaitch** [dart-lang/sdk#34860] opened 2018-10-19 02:51 UTC
When trying to use json_serializable 1.5.1 for an object that had  the following structure I got the below error message:
Customer{...List<Order>...}
Order{...List<Product>...}
Product{String}

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
    dartdevc arguments: --dart-sdk=/usr/local/Cellar/dart/2.0.0/libexec --dart-sdk-summary=/usr/local/Cellar/dart/2.0.0/libexec/lib/_internal/ddc_sdk.sum --modules=amd -o packages/components_codelab/src/product/product.ddc.js --module-root=. --library-root=/lib --summary-extension=linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/json_annotation/json_annotation.linked.sum --url-mapping=package:components_codelab/src/product/product.g.dart,packages/components_codelab/src/product/product.g.dart --url-mapping=package:components_codelab/src/product/product.dart,packages/components_codelab/src/product/product.dart package:components_codelab/src/product/product.g.dart package:components_codelab/src/product/product.dart
    dart --version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data/runtime/libtyped_data_patch.dart:4228:7)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:front_end/src/base/flat_buffers.dart:54:21)
#3      TableReader.read (package:front_end/src/base/flat_buffers.dart:694:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:4174:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:939:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:502:32)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:405:43)
#8      List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:405:18)
#10     new ModuleCompiler (package:dev_compiler/src/analyzer/module_compiler.dart:92:21)
#11     _compile (package:dev_compiler/src/analyzer/command.dart:131:18)
#12     compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#13     _CompilerWorker.performRequest (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#14     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#20     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#21     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by srawlins** [comment] 2019-09-06 05:01
This was also reported at https://github.com/dart-lang/sdk/issues/35968 and marked as fixed.

**Comment by srawlins** [comment] 2019-09-06 05:01
Duplicate of https://github.com/dart-lang/sdk/issues/35968

**Closed by srawlins** 2019-09-06 05:01 UTC
Labels: area-web, type-bug, web-dev-compiler
