### ISSUE TITLE
[Analysis Server] Does not recognize extension methods from not-yet-imported dependencies.

### ISSUE THREAD

**Issue by johnsonmh** [dart-lang/sdk#42023] opened 2020-05-22 15:02 UTC
Reproducible steps:

1. Create a new dart library.
1. In `pubspec.yaml`, add a dependency on `basics: ^0.4.0`.
1. Run `pub get`.
1. In your dart file, create an int, and attempt to call one of the extension methods from basics on it (for example, `range`).
1. Notice that the analyzer does not suggest `range` as an auto complete option.

![giphy](https://user-images.githubusercontent.com/4229329/82681311-9a009180-9c1b-11ea-8f64-7bdfab0e2a73.gif)

Only when you _manually_ add the import for `basics` do you get the proper auto-complete options. 

![giphy-1](https://user-images.githubusercontent.com/4229329/82681316-9cfb8200-9c1b-11ea-944a-33657a4ab13e.gif)

This is different from typical dependency behavior, where you will see auto-complete suggestions from dependent libraries, and if you select them, import statements will be automatically added.

### Version
 `Dart VM version: 2.9.0-3.0.dev.flutter-726d3c7725 (be) (Mon Apr 27 05:00:10 2020 +0000) on "macos_x64"`

**Comment by kuhnroyal** [comment] 2020-05-26 06:20
Probably a duplicate of https://github.com/dart-lang/sdk/issues/38894

**Comment by srawlins** [comment] 2020-06-06 23:12
duplicate of #38894

**Closed by srawlins** 2020-06-06 23:12 UTC
Labels: analyzer-completion, area-analyzer
