### ISSUE TITLE
built_value generator breaks dart analyzer in IDEA

### ISSUE THREAD

**Issue by maksimr** [dart-lang/sdk#35599] opened 2019-01-08 18:29 UTC
STR:

- `cd /tmp/`
- `flutter create foo`
- Add [*built_value*](https://pub.dartlang.org/packages/built_value) to pubspec.yml
```yml
dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value: 6.2.0
  built_value_generator: 6.2.0
  build_runner: 1.1.2
```
- Run "Packages get"
- Create file *foo.dart* `touch lib/foo.dart`
- Add this code to *foo.dart*
```dart
import 'package:built_value/built_value.dart';
part 'foo.g.dart';
abstract class Foo implements Built<Foo, FooBuilder> {
  Foo._();
  factory Foo([updates(FooBuilder b)]) = _$Foo;
}
```
- Open terminal and run `flutter packages pub run build_runner build`

[patch.txt](https://github.com/dart-lang/sdk/files/2738018/patch.txt)

Flutter (Channel master, v1.1.6-pre.43, on Mac OS X 10.14.2 18C54, locale en-RU)
 
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-183.5153.8`
- `2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b`
- `IU-183.5153.8, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b, server version 1.21.1, error: Analysis failed: /private/tmp/foo/lib/foo.dart context: exception_20190108_211602_030
RangeError (index): Invalid value: Only valid value is 0: 2
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1461:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7152:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7059:5)
#6      _ParameterElementImpl&VariableElementImpl&ParameterElementMixin.appendToWithoutDelimiters (package:analyzer/src/dart/element/element.dart:7263:18)
#7      ExecutableElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:3885:19)
#8      ConstructorElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:2197:11)
#9      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:3164:5)
#10     _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:836:19)
#11     new _ElementMismatchException (package:analyzer/src/generated/declaration_resolver.dart:971:65)
#12     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52:17)
#13     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:597:31)
#14     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#15     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#16     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#17     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#25     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#26     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#27     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#28     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#29     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#35     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#36     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#37     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#39     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
[file:///private/var/folders/2m/m3k8dkxx5zz523f76rbr19hh0000gn/T/report5.txt.](https://github.com/dart-lang/sdk/files/2737998/report5.txt)

**Comment by stereotype441** [comment] 2019-01-10 20:01
Duplicate of #35551

**Closed by stereotype441** 2019-01-10 20:01 UTC
Labels: area-analyzer
