### ISSUE TITLE
BinaryInt64Op can deopt for MUL on 32-bit architectures

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#33984] opened 2018-07-25 22:31 UTC
The BinaryInt64OpInstr can deopt for 64-bit multiplications on 32-bit architectures, viz. the code below.
```C++
  virtual bool ComputeCanDeoptimize() const {
    ASSERT(!can_overflow());
#if defined(TARGET_ARCH_IA32) || defined(TARGET_ARCH_ARM)
    if (op_kind() == Token::kMUL) {
      return true;  // Deopt if inputs are not int32.
    }
#endif
    return false;
  }
```
The reason is that our code generators on arm32 and ia32 only implement the 64-bit multiplications when the inputs are 32-bit, and deopt in all other cases. However, with the new arithmetic wrap-around semantics of Dart2 (viz. mod 2^64 behavior), we could also support 64-bit multiplication on 32-bit CPUs without deopting, but using slightly more elaborate sequences instead. Probably important moving for AOT, which can never accept deopt in its code.

**Comment by aartbik** [comment] 2018-07-25 22:33
@mraleph @alexmarkov

**Comment by alexmarkov** [comment] 2018-07-25 22:59
Duplicate of #31878

**Closed by alexmarkov** 2018-07-25 22:59 UTC
