### ISSUE TITLE
Package assets and AOT compilation

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#53569] opened 2023-09-20 09:20 UTC
When I build a web application, all assets from packages are stored in `outputDir/packages/_package_name_/*`. When I need the same files in a VM application, I use `Isolate.resolvePackageUri` and `File.fromUri`.

What about AOT compilation?
Why not use the same logic as the web build system for AOT compilation to store all asset files in `outputDir/packages/_packageName_`, with Isolate.resolvePackageUri resolving to this folder.

I share many common files in shared packages.

**Comment by a-siva** [comment] 2023-09-20 15:04
This is being tracked in https://github.com/dart-lang/sdk/issues/39576.

**Comment by a-siva** [comment] 2023-09-25 20:48
Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/39576

**Closed** 2023-10-03 04:46 UTC
Labels: area-vm, closed-duplicate, type-question
