### ISSUE TITLE
Fasta/Kernel don't support tear-offs of generic methods specialized for use context

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31586] opened 2017-12-08 14:57 UTC
According my sources the code below should be legal in Dart 2.0:

```dart
import 'dart:math' as math;

main() {
  print(<int>[1, 2, 3].fold(0, math.max));
}
```

However it does not run:

```
$ pkg/vm/tool/dart2 t/l.dart
t/l.dart:5:37: Error: A value of type '<T extends dart.core::num>(dart.math::max::T, dart.math::max::T) → dart.math::max::T' can't be assigned to a variable of type '(dart.core::Object, dart.core::int) → dart.core::Object'.
Try changing the type of the left hand side, or casting the right hand side to '(dart.core::Object, dart.core::int) → dart.core::Object'.
  print(<int>[1, 2, 3].fold(0, math.max));
                                    ^
A value of type '<T extends dart.core::num>(dart.math::max::T, dart.math::max::T) → dart.math::max::T' can't be assigned to a variable of type '(dart.core::Object, dart.core::int) → dart.core::Object'.
```

/cc @leafpetersen @stereotype441 @kmillikin

**Comment by stereotype441** [comment] 2017-12-08 16:35
Is this a duplicate of #31550?

**Comment by mraleph** [comment] 2017-12-08 16:56
Looks like it.

**Comment by stereotype441** [comment] 2017-12-13 22:22
Marking as P1 since this issue has now been independently discovered by 3 different people.

This bug is blocked waiting for #31550.  I'll mark that as P1 as well.

**Comment by stereotype441** [comment] 2017-12-14 16:35
I'm working on this now.

**Comment by leafpetersen** [comment] 2017-12-14 16:38
cc @vsmenon

**Closed** 2017-12-15 20:44 UTC
Labels: area-front-end, area-kernel, P1 high
