### ISSUE TITLE
Strengthening of types not working in extension methods on `this`

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#54825] opened 2024-02-05 12:25 UTC
It seems it's not possible to strengthen the type of `this` via `is` / `as` checks in extension methods:
```dart
main() {
  print(Sub1().foobar());
  print(Sub2().foobar());
}

extension on Base {
  String foobar() {
    if (this is Sub1) return this.foo();
    if (this is Sub2) return this.bar();
    return 'unknown';
  }
}

class Base {}

class Sub1 extends Base {
  String foo() => 'Sub1.foo';
}

class Sub2 extends Base {
  String bar() => 'Sub2.bar';
}
```
results in 
```
test.dart:8:35: Error: The method 'foo' isn't defined for the class 'Base'.
 - 'Base' is from 'test.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'foo'.
    if (this is Sub1) return this.foo();
                                  ^^^
test.dart:9:35: Error: The method 'bar' isn't defined for the class 'Base'.
 - 'Base' is from 'test.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'bar'.
    if (this is Sub2) return this.bar();
                                  ^^^
```
Capturing `this` into a final variable solves the problem
```dart
extension on Base {
  String foobar() {
    final value = this;
    if (value is Sub1) return value.foo();
    if (value is Sub2) return value.bar();
    return 'unknown';
  }
}
```

@lrhn @eernstg is this a language restriction? Could we make the existing strengthening work with `this` just as with other variables?

**Comment by halildurmus** [comment] 2024-02-05 12:35
I believe this issue is not specific to extension methods. See https://github.com/dart-lang/language/issues/1397.

**Comment by mraleph** [comment] 2024-02-05 12:39
Duplicate of https://github.com/dart-lang/language/issues/1397

**Closed by mraleph** 2024-02-05 12:39 UTC
