### ISSUE TITLE
Add strong mode warning for overriding void methods with Future- or FutureOr-returning methods

### ISSUE THREAD

**Issue by krisgiesing** [dart-lang/sdk#30159] opened 2017-07-13 19:57 UTC
I ran into a case where a method returning void was overridden with a method declared async and returning Future<Null>. Clients working with the base class have no way to trap errors generated in such methods, because exceptions are trapped by the Future and the Future itself is dropped.

So I think this is never a good thing to do, and it would be nice if strong mode would warn about such cases.

There is a dartpad showing the pattern here: https://dartpad.dartlang.org/95c750a7e09eb339e8776b48e1c8cb94

**Comment by lrhn** [comment] 2017-07-13 20:15
Be sure that you don't want the warnings where the platform libraries do exactly that.

It can be problematic, but we do allow overriding a `void` function with a non-`void` function because you can always ignore the result. 
That's not always completely true, because a returned future can be ignored at your own peril, but ignoring a future with an error it's not much different from just having the function throw synchronously and not be prepared for it.

**Comment by srawlins** [comment] 2023-01-08 04:35
I'm going to mark this a duplicate of https://github.com/dart-lang/linter/issues/1882. While this issue is older, I believe this would be implemented as a lint rule, so we'll keep that request.

**Closed by srawlins** 2023-01-08 04:35 UTC
Labels: area-analyzer, analyzer-hint, P2, type-enhancement
