### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by lkho** [dart-lang/sdk#36065] opened 2019-02-28 11:00 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version , FATAL error: NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:733:9)
#2      Driver.start (package:analysis_server/src/server/driver.dart:378:28)
#3      main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

rest of report.txt:
```
1551351311633 started analysis server:
  M:\flutter\bin\cache\dart-sdk\bin\dart.exe M:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-182.5107.16 --useAnalysisHighlight
1551351345616 started analysis server:
  M:\flutter\bin\cache\dart-sdk\bin\dart.exe M:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-182.5107.16 --useAnalysisHighlight
1551351350264 started analysis server:
  M:\flutter\bin\cache\dart-sdk\bin\dart.exe M:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-182.5107.16 --useAnalysisHighlight
1551351362070 started analysis server:
  M:\flutter\bin\cache\dart-sdk\bin\dart.exe M:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot --client-id=Android-Studio --client-version=AI-182.5107.16 --useAnalysisHighlight
```

**Comment by lkho** [comment] 2019-02-28 11:19
this error only occurs if dart-sdk/flutter is in a network drive
if installed in C: drive as the doc says, it works.

**Comment by lkho** [comment] 2019-02-28 11:21
seems this problem also exist for flutter:
flutter will throw error "could not ensure the target project location exists and is accessible" when creating projects under a network drive.

**Comment by stereotype441** [comment] 2019-03-01 22:55
Duplicate of #35226

**Closed by stereotype441** 2019-03-01 22:55 UTC
Labels: area-analyzer
