### ISSUE TITLE
dartanalyzer NPE: "NoSuchMethodError: The getter 'isSynthetic' was called on null."

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#29812] opened 2017-06-07 15:20 UTC
To reproduce, run the `dartanalyzer` on https://github.com/dart-lang/glob/blob/master/test/list_test.dart

```
Unhandled exception:
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:448)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:413)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:683)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9413)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6938)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:386)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6934)
```

**Comment by bwilkerson** [comment] 2017-06-07 15:34
@scheglov The only labels in the source are for named arguments. Any idea what might be causing this?

**Comment by kevmoo** [comment] 2017-06-07 15:55
@isoos – which version of the SDK?

**Comment by scheglov** [comment] 2017-06-07 15:56
I cannot reproduce it.
I suspect this might have been fixed in https://github.com/dart-lang/sdk/commit/a73c8d0de14d003ec02250b55f09505891edf375.

**Comment by bwilkerson** [comment] 2017-06-07 15:58
I thought that might be the case.

@isoos Please let us know if you continue to see this after upgrading to the next dev or stable release.

**Closed by bwilkerson** 2017-06-07 15:58 UTC
Labels: area-analyzer, P1 high, Type: bug

**Comment by kevmoo** [comment] 2017-06-07 15:59
@isoos I haven't seen this is my runs, either – and I'm on 1.24-latest-dev

**Comment by isoos** [comment] 2017-06-07 16:00
FWIW it was in SDK 1.23.
