### ISSUE TITLE
Improve compile error message for await inside synchronous function

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24533] opened 2015-10-09 11:19 UTC
The Dart Programming Language Speciﬁcation version 1.9 reads

> 16.30 Await Expressions
> ...
> It is a compile-time error if the function immediately enclosing a is not declared
> asynchronous. However, this error is simply a syntax error, because in the context
> of a normal function, await has no special meaning.

the following function

```
test() {
  await f();
}
```

produce error message

> error: line 24 pos 9: semicolon expected
>  await f();
>  -------^

While the function 

```
test() sync* {
  await f();
}
```

produce more meaningful error:

> error: line 24 pos 3: await operator is only allowed in an asynchronous function
>  await f();
>  ^

Please, make the error message for the first case as meaningful as in second case.

**Comment by sgjesse** [comment] 2015-10-13 07:37
Labeled with both the VM and dart2js - not sure if it is an issue in both.

**Comment by sigurdm** [comment] 2015-10-13 07:53
I think the current behavior lives up to the wording of the spec - but could be improved.

The error message has to be carefully worded I think.

`await` has no special meaning outside async context according to the spec, so the error message is the same as if there had been any other unrecognized identifier.

The more detailed error-message might be misleading if the user had wanted to write this program, but forgotten the braces:

```dart
await(p) => foo(p);

test() {
  await(f(x));
}
```
It might be possible to reparse the function in an async context and if that succeeds prompt the user if she/he forgot an async modifier.

/cc @johnniwinther

**Comment by sigmundch** [comment] 2015-10-13 15:01
> It might be possible to reparse the function in an async context and if that succeeds prompt the user if she/he forgot an async modifier.

In dart2js we actually already produce a hint to the user. We try to make sense of the await symbol after parsing, and since we know that it is not resolved, we produce a warning suggesting to add `async` to the function.

Given the program program above, we would produce this output:
```
bug.dart:2:3:
Error: Expected ';' after this.
  await f();
  ^^^^^
bug.dart:2:3:
Warning: Cannot resolve 'await'.
Did you mean to add the 'async' marker to 'main'?
  await f();
  ^^^^^
```

**Comment by sigmundch** [comment] 2015-10-13 15:04
btw, I believe this is a duplicate of https://github.com/dart-lang/sdk/issues/23234 and https://github.com/dart-lang/sdk/issues/22625, but I realize that they are not tracking the area-VM, so we can use this bug for that purpose if you like.

**Comment by srawlins** [comment] 2018-06-22 00:11
No worries! Using `--preview-dart-2` you will get 4 times the errors! 😉 

```dart
main() {
  await f();
}

f() => print('hey');
```

```none
$ dart --version
Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "macos_x64"
$ dart --preview-dart-2 24533.dart 
24533.dart:2:3: Error: 'await' isn't a type.
  await f();
  ^^^^^
24533.dart:2:10: Error: Expected ';' before this.
  await f();
         ^
24533.dart:2:11: Error: Expected an identifier, but got ')'.
  await f();
          ^
24533.dart:2:11: Error: Getter not found: ''.
  await f();
          ^
```

**Comment by srawlins** [comment] 2020-02-23 04:10
`await` in a non-`async` method now has good error recovery:

```dart
main() {
  await f();
}

f() => print('hey');
```

```none
24533.dart:2:3: Error: 'await' can only be used in 'async' or 'async*' methods.
  await f();
  ^^^^^
```

**Closed by srawlins** 2020-02-23 04:10 UTC
Labels: area-vm
