### ISSUE TITLE
Timeout on http_big_header_test

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#54655] opened 2024-01-17 22:11 UTC
There are new test failures on [[VM/vm_service] Fix for https://github.com/dart-lang/sdk/issues/54641](https://github.com/dart-lang/sdk/commit/c539f57b0029f60a9385f63bedab7e1a4d8da48f).

The tests
```
standalone/io/http_big_header_test Timeout (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-simarm_x64
```

**Comment by a-siva** [comment] 2024-01-17 23:18
This is a duplicate of https://github.com/dart-lang/sdk/issues/52110

**Closed by a-siva** 2024-01-17 23:18 UTC
Labels: area-vm, closed-duplicate, library-io, gardening
