### ISSUE TITLE
Migrated NNBD typed_data package tests crash VM

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#41085] opened 2020-03-17 22:59 UTC
I just [ported the typed_data package to null safety](https://github.com/dart-lang/typed_data/tree/null_safety). I've got it static error free. When I try to run the tests, it crashes the VM. To repro:

1. Clone the package and checkout the null safety branch.
2. Uncomment out the `dependency_overrides` section in the pubspec.
3. Run `pub get`.
4. Run any of the tests. Here's one:

    ```sh
    $ ~/dart/sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/bin/dart --enable-experiment=non-nullable --null-safety test/queue_test.dart
    ```

On my machine, this produces:

```
===== CRASH =====
si_signo=Bus error: 10(10), si_code=2, si_addr=0x10ef8b138
version=2.8.0-edge.80503ef26fbecc120b8d5f4dce8a8c86484fbe43 (Tue Mar 17 21:19:35 2020 +0000) on "macos_x64"
pid=60520, thread=9987, isolate=kernel-service(0x7ff028807800)
isolate_instructions=111f80000, vm_instructions=10ebbc580
  pc 0x000000010ef791dd fp 0x000070000d40d880 dart::Instruction::AppendInstruction(dart::Instruction*)
  pc 0x000000010efdcdb7 fp 0x000070000d40d8f0 dart::FlowGraphInliner::TryReplaceStaticCallWithInline(dart::FlowGraph*, dart::ForwardInstructionIterator*, dart::StaticCallInstr*, dart::SpeculativeInliningPolicy*)
  pc 0x000000010efd5703 fp 0x000070000d40d960 dart::FlowGraphInliner::TryReplaceStaticCallWithInline(dart::FlowGraph*, dart::ForwardInstructionIterator*, dart::StaticCallInstr*, dart::SpeculativeInliningPolicy*)
  pc 0x000000010efd038e fp 0x000070000d40da00 dart::FlowGraphInliner::TryInlineRecognizedMethod(dart::FlowGraph*, long, dart::Function const&, dart::Definition*, dart::Definition*, dart::TokenPosition, dart::ICData const*, dart::GraphEntryInstr*, dart::FunctionEntryInstr**, dart::Instruction**, dart::Definition**, dart::SpeculativeInliningPolicy*, dart::FlowGraphInliner::ExactnessInfo*)
  pc 0x000000010efd506a fp 0x000070000d40dad0 dart::FlowGraphInliner::TryReplaceInstanceCallWithInline(dart::FlowGraph*, dart::ForwardInstructionIterator*, dart::InstanceCallInstr*, dart::SpeculativeInliningPolicy*)
  pc 0x000000010f0a0ad1 fp 0x000070000d40db00 dart::JitCallSpecializer::VisitInstanceCall(dart::InstanceCallInstr*)
  pc 0x000000010ef79359 fp 0x000070000d40db40 dart::FlowGraphVisitor::VisitBlocks()
  pc 0x000000010f02a8f0 fp 0x000070000d40db50 dart::CompilerPass::RunPipelineWithPasses(dart::CompilerPassState*, std::initializer_list<dart::CompilerPass::Id>)
  pc 0x000000010f029ea9 fp 0x000070000d40dbd0 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x000000010f02a153 fp 0x000070000d40dbf0 dart::CompilerPass::RunInliningPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x000000010efcf752 fp 0x000070000d40e090 dart::PolymorphicInliner::TryInlineRecognizedMethod(long, dart::Function const&)
  pc 0x000000010efce3f9 fp 0x000070000d40e140 dart::PolymorphicInliner::TryInliningPoly(dart::TargetInfo const&)
  pc 0x000000010efd38ed fp 0x000070000d40e1c0 dart::PolymorphicInliner::Inline()
  pc 0x000000010efdbccf fp 0x000070000d40e290 dart::FlowGraphInliner::TryReplaceStaticCallWithInline(dart::FlowGraph*, dart::ForwardInstructionIterator*, dart::StaticCallInstr*, dart::SpeculativeInliningPolicy*)
  pc 0x000000010efd4adb fp 0x000070000d40e3a0 dart::FlowGraphInliner::Inline()
  pc 0x000000010efd470a fp 0x000070000d40e490 dart::FlowGraphInliner::Inline()
  pc 0x000000010f02a9b4 fp 0x000070000d40e4f0 dart::CompilerPass::RunPipelineWithPasses(dart::CompilerPassState*, std::initializer_list<dart::CompilerPass::Id>)
  pc 0x000000010f029ea9 fp 0x000070000d40e570 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x000000010f02a387 fp 0x000070000d40e590 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x000000010f09e6a5 fp 0x000070000d40ec30 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x000000010f09efac fp 0x000070000d40edf0 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)
  pc 0x000000010f09f51f fp 0x000070000d40ee80 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  pc 0x000000010f09fe99 fp 0x000070000d40ef20 dart::BackgroundCompiler::Run()
  pc 0x000000010ef09136 fp 0x000070000d40ef50 dart::ThreadPool::Worker::Loop()
  pc 0x000000010ef08fc2 fp 0x000070000d40ef80 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x000000010ee7c97f fp 0x000070000d40efb0 dart::OSThread::GetMaxStackSize()
  pc 0x00007fff6b9ece65 fp 0x000070000d40efd0 _pthread_start
  pc 0x00007fff6b9e883b fp 0x000070000d40eff0 thread_start
-- End of DumpStackTrace
Abort trap: 6
```

**Comment by crelier** [comment] 2020-03-18 19:27
Thanks for the detailed reproduction steps. However, I am not sure how to pass step 3 after getting  this error:
```
regis@belenos:~/issue41085/typed_data$ pub get
Resolving dependencies... (1.3s)
The current Dart SDK version is 2.8.0-edge.8d308cc30eed6bae20a27b830320c170a15e85ef.

Because test >=1.3.0 depends on typed_data ^1.0.0 and test >=0.12.0-beta.3 <1.3.0 requires SDK version >=1.8.0 <2.0.0-∞, test >=0.12.0-beta.3 requires typed_data ^1.0.0.
So, because typed_data depends on test ^1.0.0 and typed_data is 2.0.0-dev, version solving failed.

```
Here is my pubspec:
```
regis@belenos:~/issue41085/typed_data$ cat pubspec.yaml
name: typed_data
version: 2.0.0-dev

description: >-
  Utility functions and classes related to the dart:typed_data library.
homepage: https://github.com/dart-lang/typed_data

environment:
  sdk: '>=2.8.0-dev.0 <3.0.0'

dependencies:
  collection: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0

dependency_overrides:
  collection:
    git:
      url: git://github.com/dart-lang/collection.git
      ref: null_safety

```

**Comment by munificent** [comment] 2020-03-18 22:20
Oops, sorry about that. Try changing the version in the pubspec.yaml file to:

```yaml
version: 1.3.0-dev
```

**Comment by crelier** [comment] 2020-03-18 23:23
That worked, thanks!
The test of step 4 passes in weak mode, but I am getting an error launching it with --null-safety:
```
regis@belenos:~/issue41085/typed_data$ ~/dart4/sdk/out/DebugX64NNBD/dart --enable-experiment=non-nullable --null-safety test/queue_test.dart
error: Library 'org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart' was compiled without null safety (in weak mode) and it cannot be used with --null-safety at runtime
Error while initializing Kernel isolate
```

@a-siva Are we able to run the kernel isolate in strong mode? Is the error message pointing to a different version than the one in the sdk? Any idea about the correct incantation here?

**Comment by a-siva** [comment] 2020-03-19 00:32
No we are not in a position to run the kernel isolate is strong mode. I am not sure why the kernel isolate is running in strong mode.

**Comment by natebosch** [comment] 2020-03-19 16:48
You don't specifically need to be in `typed_data` to reproduce this. The minimal requirements seem to be:

- Be in a migrated package.
- Use the `null_safety` branch git overrides.
- Have a file which imports `package:test/test.dart` or `package:test_core/test_core.dart`.

I have been playing around with deleting code from `test_core` to see what conditions cause this and it feels a bit arbitrary. I remove a whole bunch of stuff, and what remains has static errors, but it crashes before they are reported. It's also not completely deterministic. I can rerun with code in the same state and sometimes get static errors reported, sometimes get the segfault.

**Comment by crelier** [comment] 2020-03-19 17:37
@a-siva It looks like approved https://dart-review.googlesource.com/c/sdk/+/139029 is not committed yet. I think it could help with this issue.

**Comment by crelier** [comment] 2020-03-19 17:51
Never mind about the error reported while initializing Kernel isolate. This is due to setting create_kernel_service_snapshot to false while debugging with -O0. We will need to address that, because only x64 is setting it to false by default. We will run into that issue on other platforms.

I am seeing the same stack trace now.

**Comment by crelier** [comment] 2020-03-19 18:11
If I compile the VM with -O0, I get these Dart type errors instead of a crash:
```
../../.pub-cache/git/collection-70029441c9246f3aae851a18bdcc9b199b9888a2/lib/src/algorithms.dart:176:20: Error: The argument type 'int Function(T, T)' can't be assigned to the parameter type 'int Function(T?, T?)'.
  _mergeSort(list, compare, middle, end, scratchSpace, 0);
                   ^
../../.pub-cache/git/collection-70029441c9246f3aae851a18bdcc9b199b9888a2/lib/src/algorithms.dart:179:10: Error: The argument type 'int Function(T, T)' can't be assigned to the parameter type 'int Function(T?, T?)'.
  _merge(compare, list, firstTarget, end, scratchSpace, 0, secondLength, list,
         ^
../../.pub-cache/git/collection-70029441c9246f3aae851a18bdcc9b199b9888a2/lib/src/algorithms.dart:220:32: Error: The argument type 'int Function(T, T)' can't be assigned to the parameter type 'int Function(T?, T?)'.
    _movingInsertionSort(list, compare, start, end, target, targetOffset);
                               ^
../../.pub-cache/git/collection-70029441c9246f3aae851a18bdcc9b199b9888a2/lib/src/algorithms.dart:229:20: Error: The argument type 'int Function(T, T)' can't be assigned to the parameter type 'int Function(T?, T?)'.
  _mergeSort(list, compare, middle, end, target, targetMiddle);
                   ^
../../.pub-cache/git/collection-70029441c9246f3aae851a18bdcc9b199b9888a2/lib/src/algorithms.dart:233:10: Error: The argument type 'int Function(T, T)' can't be assigned to the parameter type 'int Function(T?, T?)'.
  _merge(compare, list, middle, middle + firstLength, target, targetMiddle,
         ^

```

**Comment by natebosch** [comment] 2020-03-19 18:27
Those errors are incorrect, the issue for them is https://github.com/dart-lang/sdk/issues/41105

We did make a commit that should have resolved those particular ones: https://github.com/dart-lang/collection/commit/0e5c80e914a9448be90558030b8bb47e1cbe1011

If you `pub upgrade` I think you should pick them up since they are on the `null_safety` branch.

**Comment by crelier** [comment] 2020-03-19 18:40
Indeed, they disappeared after pub upgrade. Thanks!
I suppose they are on a timing dependent code path, as I was not getting them when compiling with -O2. I am back to the original stack trace, with -O0.

It looks like the signature of ObjectArrayGetIndexed (i.e. `_List[]`) has changed and the inliner is using the previous pre-nnbd version. We use fingerprinting of source to protect against such mismatches, but having 2 different sdk (prior to unforking) to support, we had to disable fingerprinting for the nnbd version.

Let me check what has changed...

**Comment by crelier** [comment] 2020-03-19 19:17
@alexmarkov The inliner accesses argument 1 of the flow graph instruction `InstanceCallInstr` for a call to `_List[]`. The instruction returns nullptr for `GetPushArguments()`, so we access `InputAt(1)` directly. However, the instruction has only one input, which cannot be correct for `_List[]`.

I see that you [modified](https://dart-review.googlesource.com/c/sdk/+/130935) this InstanceCallInstr recently and are more familiar than me with this code. Would you mind having a look? Thanks.

**Comment by alexmarkov** [comment] 2020-03-19 19:54
Sure, I can take a look.

**Comment by crelier** [comment] 2020-03-19 20:03
Thanks Alex!

So it does not look like the signature of `_List[]` has changed. Maybe another one has. This result in this inliner crash.
Interestingly, if I disable inlining with --inlining-depth-threshold=-1, the VM does not crash, but reports several times the same type error, which is probably legit: 
```
00:00 +66 -1: length= grows for a queue that's below capacity with contiguous elements [E]

  type 'Null' is not a subtype of type 'int' in type cast

  dart:core-patch/growable_array.dart 127:12                    List.length=
  dart:collection/list.dart 362:25                              ListMixin.+
  ../../issue41085/typed_data/test/queue_test.dart 160:45       main.<fn>.<fn>.<fn>
  ../../issue41085/typed_data/test/queue_test.dart 273:15       forEachInternalRepresentation.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 172:27             Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
...

```

**Comment by kevmoo** [comment] 2020-03-19 20:05
Easy fix?

**Comment by crelier** [comment] 2020-03-19 20:14
We do not know yet about the inliner bug. @alexmarkov is looking at it.
In the meantime, @munificent could look at the type error in typed_data/test/queue_test.dart:160.
You cannot increase the length of a list of non-nullable elements.

**Comment by alexmarkov** [comment] 2020-03-19 21:11
I think there is a mismatch in deopt ids / ICData between unoptimized code and optimized code.

It happens in the kernel service. Unoptimized code comes from kernel service app-jit snapshot, which was generated in NNBD weak mode. However, at run time VM is running in the NNBD strong mode and optimized code is generated in NNBD strong mode, which causes a slightly different flow graph and skewed deopt ids. So ICData objects, which were populated while running unoptimized code do not match deopt ids in optimized code, hence the invalid ICData in the instruction

```
v508 <- InstanceCall:112( get:_offset@3220832<0>, v476 IC[1: _List@0150898 cnt:14899 trgt:'_List@0150898.[]']) T{int?}
```

@a-siva's CL for running each isolate in its own NNBD weak/strong mode could help, along with setting NNBD mode for kernel service to weak.

**Comment by alexmarkov** [comment] 2020-03-19 21:33
The crash disappears if you patch in https://dart-review.googlesource.com/c/sdk/+/139029 and apply the following small change:

```patch
diff --git a/runtime/vm/kernel_isolate.cc b/runtime/vm/kernel_isolate.cc
index 5931cc5a15..a3268206fb 100644
--- a/runtime/vm/kernel_isolate.cc
+++ b/runtime/vm/kernel_isolate.cc
@@ -93,6 +93,7 @@ class RunKernelTask : public ThreadPool::Task {
 #if !defined(DART_PRECOMPILER)
     api_flags.use_osr = true;
 #endif
+    api_flags.null_safety = false;
 
     isolate = reinterpret_cast<Isolate*>(
         create_group_callback(KernelIsolate::kName, KernelIsolate::kName, NULL,
```

**Comment by crelier** [comment] 2020-03-19 22:14
@alexmarkov Great findings! Thanks!

So we need @a-siva to commit his pending CL with your patch.

I still do not quite understand why we do not get the strong/weak mismatch error I was getting above when setting `create_kernel_service_snapshot = false` in runtime/runtime_args.gni. This error was actually accurate.

**Comment by alexmarkov** [comment] 2020-03-19 22:28
@crelier We're currently checking dill files when loading them, but it looks like we're not checking snapshots for consistency with current mode.

**Comment by crelier** [comment] 2020-03-19 22:34
@alexmarkov I see. The error was coming from the platform dill, since we did not have a kernel service snapshot. We should definitely check snapshots as well. Thanks!

**Comment by alexmarkov** [comment] 2020-03-20 02:37
@a-siva landed his CL. https://dart-review.googlesource.com/c/sdk/+/140240 should fix the problem.

**Closed** 2020-03-20 17:52 UTC
Labels: NNBD, area-vm, crash

**Comment by kevmoo** [comment] 2020-03-20 19:03
Confirmed this is fixed (well, no CRASH) with 4c1eaf727c5fb96a58f69690afbcc80b4490eb4d

Thanks!

**Comment by kevmoo** [comment] 2020-03-20 19:13
The test in question now has 4 failures, all in the form

```
  type 'Null' is not a subtype of type 'int' in type cast

  dart:core-patch/growable_array.dart 127:12                    List.length=
  dart:collection/list.dart 362:25                              ListMixin.+
  test/queue_test.dart 160:45                                   main.<fn>.<fn>.<fn>
  test/queue_test.dart 286:15                                   forEachInternalRepresentation.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 172:27             Declarer.test.<fn>.<fn>.<fn>
```

**Comment by crelier** [comment] 2020-03-20 20:11
When looking at the type error more closely, the issue (increasing the length of a list of non-nullable elements) is not in queue.dart as I first assumed, but in the core library.

typed_data/test/queue_test.dart:160:45 is calling the List operator '+', which increases the list length in sdk_nnbd/lib/collection/list.dart:362:25

The operator '+' should work properly on lists of non-nullable elements and needs to be fixed. I can have a look.

**Comment by kevmoo** [comment] 2020-03-20 20:19
> When looking at the type error more closely, the issue (increasing the length of a list of non-nullable elements) is not in queue.dart as I first assumed, but in the core library.
> 
> typed_data/test/queue_test.dart:160:45 is calling the List operator '+', which increases the list length in sdk_nnbd/lib/collection/list.dart:362:25
> 
> The operator '+' should work properly on lists of non-nullable elements and needs to be fixed. I can have a look.

Yup. See https://github.com/dart-lang/sdk/issues/41129

And https://dart-review.googlesource.com/c/sdk/+/140256

**Comment by crelier** [comment] 2020-03-20 20:32
Cool! And elegant fix!
Instead of growing the receiver, it returns a new List. I guess it's fine, but I will let the experts review the change. The test passes now.
