### ISSUE TITLE
Inline `let <assignment> in <expr>` syntax

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#52603] opened 2023-06-03 06:00 UTC
I often need to reuse a computed value twice while constructing a widget hierarchy in Flutter. To save duplicating work, I always have to go back up to the top of the `build` method, compute the value once, store it in a local variable, then use that value multiple times in the widget hierarchy that is being built.

It would be great if Dart supported Haskell's `let...in...` syntax: https://wiki.haskell.org/Let_vs._Where

Basically in the middle of a widget tree you could do `let <assignment> where <Widget expression that uses assignment multiple times>`, e.g.:

```dart
Container(
  child:
    let user = getUser()
    in Column(
      children: [
        Text('Name: ${user.name}'),
        Text('Age: ${user.age}'),
      ],
  ),
),  
```

I assume only one assignment could be accommodated per `let...in...` expression, because of parsing ambiguity around a comma-separated list of assignments?

* Dart SDK Version (`dart --version`): 3.0.2

**Comment by lrhn** [comment] 2023-06-03 08:07
This sounds like a language request, and then it's a duplicate of https://github.com/dart-lang/language/issues/2197

**Closed by lrhn** 2023-06-03 08:07 UTC
