### ISSUE TITLE
Dartium doesn't load Dart application

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26260] opened 2016-04-14 11:17 UTC
Since a few days it gets harder and harder to make Dartium load an application.
It keeps loading but `pub serve` seems ideling and it's unclear what Dartium is waiting for.
A combination of killing `pub serve`, closing and restarting Dartium, force reloading (<kbd>Ctrl</kbd>+<kbd>F5</kbd>) the page eventually might get rendered.

If I open the same URL in Chrome it works.

Dartiums browser console doesn't show errors it just keeps spinning the loading indicator. 

When I click [ x ] (Stop loading this page) the console prints

> An error occurred loading file: package:angular2/src/core/metadata.dart
package:angular2/src/core/platform_common_providers.dart:1 An error occurred loading file: package:angular2/src/core/platform_common_providers.dart
package:angular2/common.dart:1 An error occurred loading file: package:angular2/common.dart
package:angular2/src/router/router_providers.dart:1 An error occurred loading file: package:angular2/src/router/router_providers.dart
package:angular2/src/router/location/platform_location.dart:1 An error occurred loading file: package:angular2/src/router/location/platform_location.dart
package:stream_transformers/stream_transformers.dart:1 An error occurred loading file: package:stream_transformers/stream_transformers.dart
package:angular2/src/platform/dom/events/event_manager.dart:1 An error occurred loading file: package:angular2/src/platform/dom/events/event_manager.dart
package:angular2/src/core/application_common_providers.dart:1 An error occurred loading file: package:angular2/src/core/application_common_providers.dart
package:angular2/src/router/lifecycle/lifecycle_annotations_impl.dart:1 An error occurred loading file: package:angular2/src/router/lifecycle/lifecycle_annotations_impl.dart
package:angular2/src/core/reflection/reflection.dart:1 An error occurred loading file: package:angular2/src/core/reflection/reflection.dart
package:angular2/src/router/instruction.dart:1 An error occurred loading file: package:angular2/src/router/instruction.dart
package:angular2/src/core/render.dart:1 An error occurred loading file: package:angular2/src/core/render.dart
package:angular2/src/core/debug/debug_node.dart:1 An error occurred loading file: package:angular2/src/core/debug/debug_node.dart
package:angular2/src/facade/exceptions.dart:1 An error occurred loading file: package:angular2/src/facade/exceptions.dart
package:angular2/src/router/router_providers_common.dart:1 An error occurred loading file: package:angular2/src/router/router_providers_common.dart
package:angular2/src/core/angular_entrypoint.dart:1 An error occurred loading file: package:angular2/src/core/angular_entrypoint.dart
package:angular2/src/core/change_detection.dart:1 An error occurred loading file: package:angular2/src/core/change_detection.dart
package:angular2/src/facade/facade.dart:1 An error occurred loading file: package:angular2/src/facade/facade.dart
package:angular2/src/compiler/url_resolver.dart:1 An error occurred loading file: package:angular2/src/compiler/url_resolver.dart
package:angular2/src/facade/lang.dart:1 An error occurred loading file: package:angular2/src/facade/lang.dart
package:angular2/src/platform/dom/dom_tokens.dart:1 An error occurred loading file: package:angular2/src/platform/dom/dom_tokens.dart
package:angular2/src/core/linker.dart:1 An error occurred loading file: package:angular2/src/core/linker.dart
package:angular2/src/core/util.dart:1 An error occurred loading file: package:angular2/src/core/util.dart
package:angular2/src/router/route_config/route_config_impl.dart:1 An error occurred loading file: package:angular2/src/router/route_config/route_config_impl.dart
package:angular2/src/core/platform_directives_and_pipes.dart:1 An error occurred loading file: package:angular2/src/core/platform_directives_and_pipes.dart
package:angular2/src/core/application_ref.dart:1 An error occurred loading file: package:angular2/src/core/application_ref.dart
package:angular2/src/router/rules/rules.dart:1 An error occurred loading file: package:angular2/src/router/rules/rules.dart
package:angular2/src/router/location/location.dart:1 An error occurred loading file: package:angular2/src/router/location/location.dart
package:angular2/src/platform/dom/dom_adapter.dart:1 An error occurred loading file: package:angular2/src/platform/dom/dom_adapter.dart
package:angular2/src/router/lifecycle/route_lifecycle_reflector.dart:1 An error occurred loading file: package:angular2/src/router/lifecycle/route_lifecycle_reflector.dart
package:angular2/src/core/application_tokens.dart:1 An error occurred loading file: package:angular2/src/core/application_tokens.dart
package:angular2/src/platform/browser_common.dart:1 An error occurred loading file: package:angular2/src/platform/browser_common.dart
main.template.dart:1 An error occurred loading file: http://localhost:63342/angular2%20playground/autocomplete/web/main.template.dart
package:angular2/src/router/rules/rule_set.dart:1 An error occurred loading file: package:angular2/src/router/rules/rule_set.dart
package:angular2/src/router/route_config/route_config_normalizer.dart:1 An error occurred loading file: package:angular2/src/router/route_config/route_config_normalizer.dart
package:angular2/src/core/di.dart:1 An error occurred loading file: package:angular2/src/core/di.dart
package:angular2/src/router/rules/route_paths/route_path.dart:1 An error occurred loading file: package:angular2/src/router/rules/route_paths/route_path.dart
package:angular2/instrumentation.dart:1 An error occurred loading file: package:angular2/instrumentation.dart
package:angular2/src/core/zone.dart:1 An error occurred loading file: package:angular2/src/core/zone.dart
package:angular2/src/facade/collection.dart:1 An error occurred loading file: package:angular2/src/facade/collection.dart
package:angular2/src/core/testability/testability.dart:1 An error occurred loading file: package:angular2/src/core/testability/testability.dart
package:angular2/src/router/route_config/route_config_decorator.dart:1 An error occurred loading file: package:angular2/src/router/route_config/route_config_decorator.dart
package:angular2/src/router/url_parser.dart:1 An error occurred loading file: package:angular2/src/router/url_parser.dart
package:angular2/src/facade/async.dart:1 An error occurred loading file: package:angular2/src/facade/async.dart

Clearing the profile directory didn't change anything.

Dart VM version: 1.16.0-edge.898aa67b430efa9da1dba1010d3146409666ea86 (Wed Apr 13 19:45:57 2016) on "linux_x64"

(same with the version from Friday)

Currently it's impossible to work with Dartium.

**Comment by kwalrath** [comment] 2016-04-14 17:02
I've seen this, too (on Mac).

**Comment by novabyte** [comment] 2016-04-16 09:51
+1 seen this problem as well on Mac.

**Comment by mit-mit** [comment] 2016-04-19 10:30
@kevmoo, known issue? Does this impact 1.16 RC?

**Comment by mit-mit** [comment] 2016-04-19 12:36
CC @whesse

**Comment by kevmoo** [comment] 2016-04-19 16:37
@zoechi @kwalrath @novabyte Which SDK version are you seeing this on?

Can any of your get a reliable repro? On a project we can look at?

**Comment by zoechi** [comment] 2016-04-19 16:45
I just tried with https://github.com/bwu-dart-playground/route-example-for-ie10 and it doesn't load. Not even <kbd>Ctrl</kbd>+<kbd>F5</kbd> makes it work.

**Comment by kwalrath** [comment] 2016-04-19 17:55
@kevmoo I don't have anything reproduceable. I think I was using 1.16.0-dev.4.0 and earlier dev versions. I noticed intermittent trouble loading the last two times (at least) that I updated the angular.io/dart site to reflect new [angular2 releases](https://pub.dartlang.org/packages/angular2).

For each release I update all the dart samples, which live in [public/docs/_examples/*/dart](https://github.com/angular/angular.io/tree/master/public/docs/_examples), and I make sure they run in Dartium checked mode without any new warnings. Eventually they all did.

**Comment by terrylucas** [comment] 2016-04-19 18:17
Gunter,

Seems to work you'll need to use:

pub get
pub serve

Then the URL in Dartium should be localhost:8080

**Comment by zoechi** [comment] 2016-04-19 18:22
Thanks @terrylucas, I know how to load a Dart client application :D but Dartium doesn't, at least not here.

**Comment by kevmoo** [comment] 2016-04-19 18:26
@zoechi I just tried 1.16.0-dev.5.1 on Mac with no issue. Could you try with the latest dev build?

**Comment by denniskaselow** [comment] 2016-04-19 18:49
@zoechi Are you starting the application using WebStorm? I can reproduce the behavior most of the time if I use Webstorm via `Run 'index.html'` but it works if I start `pub serve` via terminal in Webstorm or command line.

WebStorm 2016.1.1
Build #WS-145.597, built on March 30, 2016
JRE: 1.8.0_45-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Dart VM version: 1.16.0-dev.5.1 (Mon Apr 18 01:40:24 2016) on "windows_x64"

**Comment by zoechi** [comment] 2016-04-19 18:55
@denniskaselow yes I tried with WebStorm

**Comment by kevmoo** [comment] 2016-04-19 21:26
Is this a behavior that has changes since Dart 1.15? – or is it a change since updating the pkg/angular2 version you're using?

**Comment by denniskaselow** [comment] 2016-04-20 04:49
Can't speak for @zoechi or anyone else, but I think I've pinned down the reason a bit more after fiddling around with different versions of everything etc.

First of all: It's not only happening to angular applications. And I couldn't reproduce it with Dart 1.15.

Did caching of pub served resources get added in 1.16? Cause that's where I'm seeing the issue but I did not get anything cached in 1.15.

What I'm seeing is this:
If I start the application using WebStorm it runs `pub serve web --port=60554` (or whatever other random port).
Then WebStorm opens `http://localhost:63342/route-example-for-ie10/web/index.html`.
If no resources are cached (e.g. open console with `Disable cache (while DevTools is open)` checked), pub serve just outputs: `[web] GET Served 484 assets.` and everything works just fine
If resources are getting cached, it's outputting things like:
```
[web] GET Served 8 cached assets.
[web] GET Served 5 cached assets.
[web] GET Served 3 cached assets.
[web] GET Served 4 cached assets.
[web] GET Served 3 cached assets.
[web] GET packages/angular2/src/compiler/url_resolver.dart => (cached) angular2|lib/src/compiler/url_resolver.dart
[web] GET packages/angular2/core.template.dart => (cached) angular2|lib/core.template.dart
[web] GET Served 2 cached assets.
```
In Dartium those resources remain pending (not all resources though, some get a status code of 200, some 304) , when viewing in the Network-tab. On canceling the errors posted in @zoechi report happen.

Now.. if I use the port used by pub when WebStorm executed `pub serve` and open `localhost:60554` I'm getting `[web] GET Served 484 cached assets.` and everything works just fine. Important: These are still cached resources, so the caching just isn't working correctly when using WebStorms URL with port 63342.

Hope this helps and @zoechi or @kwalrath can confirm this.

**Comment by zoechi** [comment] 2016-04-20 07:13
@denniskaselow  See also https://groups.google.com/a/dartlang.org/forum/#!topic/web/kkwtCScfPEg

**Comment by alexander-doroshko** [comment] 2016-04-20 10:41
@denniskaselow @zoechi 
WebStorm works as a transparent proxy for Pub Serve. Inside IDE URLs like `http://localhost:63342/route-example-for-ie10/web/index.html` are simply redirected to URLs like `http://localhost:60554/index.html` (where 60554 is a random port used to start Pub Serve, see its tool window).

If you observe different app behavior if you change WebStorm's `http://localhost:63342/...` URL to direct Pub Serve's URL right in the browser, then it may be a bug in the IDE. If so then I'd ask you to file a bug in [https://youtrack.jetbrains.com/issues/Web WebStorm's issue tracker] with the following information: IDE build number (Help | About), Dart SDK and Dartium versions configured in the IDE, sample project and steps to reproduce.

**Comment by zoechi** [comment] 2016-04-20 11:16
@alexander-doroshko  Done https://youtrack.jetbrains.com/issue/WEB-21355

**Comment by kwalrath** [comment] 2016-04-20 16:55
@kevmoo I just tried with 1.16.0-dev.5.1 on Mac, and the issue was still there. (The first command-reload worked, though, so it wasn't as frustrating as it sometimes is.)

I was testing using the beta.15 template-syntax example: https://github.com/angular/angular.io/tree/master/public/docs/_examples/template-syntax/dart

**Comment by alexander-doroshko** [comment] 2016-04-20 17:19
@kwalrath This may be an issue at IDE side as well. Are you using WebStorm / IntelliJ IDEA (which build number if so)? If yes, will the issue go away if you change URL to access Pub Serve directly (see Pub Serve tool window to find port number)?

**Comment by alexander-doroshko** [comment] 2016-04-20 17:23
@kevmoo Am I right that in SDK 1.16 Pub Serve has a new feature related to assets caching?
WebStorm seems to have problems with it. We are investigating the problem.

**Comment by lexaknyazev** [comment] 2016-04-20 17:32
@alexander-doroshko 
Same behavior (direct URL works, `:63342` hangs)
IntelliJ IDEA 2016.1, Build #IU-145.970, Win10
Dart plugin 145.597.6
Dart SDK 1.16.0-dev.5.1

**Comment by kwalrath** [comment] 2016-04-20 17:41
@munificent is looking at this right now. It might be related to his pub caching changes.

**Comment by frankpepermans** [comment] 2016-04-21 13:30
Also seeing this issue, and only in 1.16.x

**Comment by mit-mit** [comment] 2016-04-21 13:34
Are you also seeing this in the latest dev build, 1.16 RC0, build number 1.16.0-dev.5.4?

**Comment by alexander-doroshko** [comment] 2016-04-21 13:49
WebStorm doesn't work well with Pub Serve from SDK 1.16, including 1.16.0-dev.5.4. The issue seems to be at IDE side as there are no problems using Pub Serve directly without WebStorm (at least for me). We are investigating the issue.

**Comment by kwalrath** [comment] 2016-04-21 16:56
I had been seeing this problem with `pub serve` from the command line, but I don't see the problem any more with 1.16.0-dev.5.4. (I've run 3 or 4 apps, and they all loaded quickly the first time.)

@alexander-doroshko is there a bug # for the WebStorm issue with pub serve?

**Comment by alexander-doroshko** [comment] 2016-04-21 17:07
[Bob wrote](https://groups.google.com/a/dartlang.org/forum/#!topic/web/kkwtCScfPEg) that there was a problem with Pub Serve that is fixed in 1.16.0-dev.5.4. I do not know if there are more bugs with it.

WebStorm's issue is tracked as https://youtrack.jetbrains.com/issue/WEB-21355

**Comment by munificent** [comment] 2016-04-21 22:25
@alexander-doroshko, that's right. I did indeed recently break and then fix some stuff around caching in pub. My guess is that's what's going on here.

I'm going to speculatively close because, as far as I know, I fixed the two issues around this in pub serve. If you still run into issues if you test with a build that includes bf62fde1a92f618db0e17ebb291c2b9f5c96be41, then let me know and I'll reopen.

**Closed by munificent** 2016-04-21 22:25 UTC
Labels: area-dartium, S1 high

**Comment by alexander-doroshko** [comment] 2016-04-22 13:18
We've fixed the issue at WebStorm side. Bugfix update is planned for the next week.

@munificent Playing with Dartium + Pub Serve (without IDE) I noticed that if you quickly do Refresh (F5) in browser several times (without waiting for the page to load) Dartium hangs or crashes. Pub Serve seems to be alive but according to its output it hasn't served all the assets N times (may be it was not asked to). 

Reproduced with SDK+Dartium both 1.15.0 and 1.16.0-dev.5.4 (Windows 8.1, x64) and [this]( https://github.com/bwu-dart-playground/route-example-for-ie10) project where each Refresh asks for 484 assets. Is this a known limitation or not a real use case or do you want me to file a separate issue?

**Comment by munificent** [comment] 2016-04-24 17:50
> Is this a known limitation or not a real use case or do you want me to file a separate issue?

Definitely not a known issue. Please do file a bug. Thanks!
