### ISSUE TITLE
Allow abstract classes to be instantiated given definitions of all abstract methods

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#55544] opened 2024-04-22 23:19 UTC
Dart does not currently support anonymous classes, and does not allow for abstract classes to be instantiated.

Without necessarily going all the way to supporting anonymous classes, it would be nice to be able to at least instantiate abstract classes by providing definitions for all abstract methods:

```dart
abstract class Point {
  int x();
  int y();
}

final origin = Point() {
  int x() => 0;
  int y() => 0;
};
```

Right now the only alternative is to use function-typed fields.

**Comment by mraleph** [comment] 2024-04-24 06:56
> Without necessarily going all the way to supporting anonymous classes

What you are asking is pretty much the same as an anonymous class. 

So this is duplicate of https://github.com/dart-lang/language/issues/2927

**Closed by mraleph** 2024-04-24 06:56 UTC
