### ISSUE TITLE
[test runner] Missing info on failure reason?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46203] opened 2021-06-01 09:58 UTC
Consider the following buildbot [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8846085033945477680/+/u/test_results/new_test_failures__logs_):

Here is a snippet from that log:

```
/========================================================================================================================\
| analyzer-asserts-strong-linux:corelib/symbol_arbitrary_string_test is new and failed (CompileTimeError, expected Pass) |
\========================================================================================================================/

--- Command "dart2analyzer" (took 291ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=json --no-hints /b/s/w/ir/cache/builder/sdk/tests/corelib/symbol_arbitrary_string_test.dart

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-strong-linux corelib/symbol_arbitrary_string_test

/=====================================================================================================================\
| analyzer-asserts-strong-linux:corelib/symbol_reserved_word_test is new and failed (CompileTimeError, expected Pass) |
\=====================================================================================================================/

--- Command "dart2analyzer" (took 211ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=json --no-hints /b/s/w/ir/cache/builder/sdk/tests/corelib/symbol_reserved_word_test.dart

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-strong-linux corelib/symbol_reserved_word_test

/======================================================================================================================\
| analyzer-asserts-weak-linux:corelib/symbol_arbitrary_string_test is new and failed (CompileTimeError, expected Pass) |
\======================================================================================================================/

--- Command "dart2analyzer" (took 121ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --format=json --no-hints /b/s/w/ir/cache/builder/sdk/tests/corelib/symbol_arbitrary_string_test.dart

--- Re-run this test:
python3 tools/test.py -n analyzer-asserts-weak-linux corelib/symbol_arbitrary_string_test
```

This kind of logging is quite inconvenient, because it mentions that there was a compile-time error, and the expected outcome is a 'Pass' status, but there is no information about which compile-time error that was, or where it occurred.

I don't have hard evidence for this, but it is my impression that this kind of "thin" logs started occurring recently, perhaps a couple of months ago.

Usually, I can extract the data from the log and run the command locally, and I can use `--verbose` on `test.py` in order to get more information, but I would expect the log to contain more specific information, such that those local steps won't be necessary in a typical case.

Is it true that these "thin" logs is a new thing? Can't we enhance them to get the information about which error occurred where? Is it just because I'm looking in the wrong place? ;-)

@munificent, WDYT?

@athomas, you mentioned that there could be a connection to the use of JSON formatted results, do you have any further comments on this?

**Comment by whesse** [comment] 2021-06-01 10:45
The link in the issue does not work - could you add a link to the build?  I also looked at a typical analyzer build, and see that all the logs in logs.json have no detail either, so the problem is reproducible.

Every tool, like dart2js or the analyzer, has its own code for running it and grabbing the output from stderr and stdout.  I looked at logs from the vm, and they do have detailed stack traces.

I suspect that either the analyzer does not produce error information in the mode we are running it in, or that the code to process analyzer results is dropping it, and not adding it to the log.  In either case, I suspect it is specific to the analyzer runtime, and not to other tools tested, so that is where to start looking.

**Comment by athomas** [comment] 2021-06-01 10:50
I fixed the link in the original description, it was just github that ate the trailing `_`.

**Comment by athomas** [comment] 2021-06-01 10:53
As far as I understand, these "CompileTimeErrors" are surfaced by the analyzer but the test framework does not print them because they are in an imported library rather than the test itself.

So at least, the static error test framework should log unhandled errors from the analyzer so that it's possible to understand why the test failed and especially in which file the errors occured.

**Comment by eernstg** [comment] 2021-06-01 11:42
@athomas wrote:
> ate the trailing `_`.

Ah, it probably thought that the underscore was an 'italic' marker. Thanks!

> test framework does not print them because they are in an
> imported library rather than the test itself

That should not be the case here. When I `git checkout` to the branch for the [relevant CL](https://dart-review.googlesource.com/195503) and run the test runner with `--verbose` and run the actual command locally (but removing `--format=json`) then I get a good handful of error messages, and they are all associated with the entry point `symbol_arbitrary_string_test.dart`:

```
> DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/usr/local/google/home/eernst/devel/dart/work/sdk/.packages --no-hints /usr/local/google/home/eernst/devel/dart/work/sdk/tests/corelib/symbol_arbitrary_string_test.dart

Analyzing /usr/local/google/home/eernst/devel/dart/work/sdk/tests/corelib/symbol_arbitrary_string_test.dart...
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:64:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:65:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:68:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:69:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:70:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:71:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:72:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:73:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:74:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:75:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:76:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:77:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:78:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:81:16 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:87:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:88:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:91:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:92:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:93:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:94:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:95:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:96:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:97:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:98:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:99:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:100:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:101:33 • const_eval_throws_exception
  error • Evaluation of this constant expression throws an exception. • tests/corelib/symbol_arbitrary_string_test.dart:106:7 • const_eval_throws_exception
28 errors found.
```

**Comment by athomas** [comment] 2021-06-01 13:54
Note, the test is a plain new test (no static errors, no multitest markers) added in https://dart-review.googlesource.com/c/sdk/+/195503.

**Comment by munificent** [comment] 2021-06-09 01:14
Your suspicion is correct @eernstg. When we moved the test runner to use analyzer's new JSON output instead of the old machine format, this was accidentally broken. The test runner silently stopped actually printing the analysis errors on a test failure. Oops. :(

It should be fixed now: https://dart-review.googlesource.com/c/sdk/+/201382

**Closed by munificent** 2021-06-09 01:14 UTC
Labels: area-test
