### ISSUE TITLE
Make [known length].map(...).toList() smarter

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#26495] opened 2016-05-19 19:24 UTC
Imagine if the left side of a `map` function has a known length.

The iterable returned from it could be some private `_AssumedCapacityIterable`.

If `toList` is called on such an iterable, it could initialize its capacity to the assumed value before populating.

See https://codereview.chromium.org/1995043002/ for an example where this would/could be useful

**Comment by kevmoo** [comment] 2016-05-19 19:24
CC @floitschG @lrhn @scheglov

**Comment by rakudrama** [comment] 2016-05-19 19:43
I think the compilers should all do a better job here, using heuristics to
recognize common idioms if it cannot be accomplished from first principles.

**Comment by lrhn** [comment] 2016-05-19 20:51
I think we do that optimization in some case (anything based on `ListIterable`), but we might be able to do it in more cases.

**Comment by lrhn** [comment] 2016-05-20 14:44
Checking more, I think we actually do make the optimization in all the cases where we know that the `Iterable` has an efficient length. 

The `toList` of the `Iterable` class in `dart:core` calls `new List<E>.from(this)`. The `List.from` constructor checks whether the argument is known to have an efficient length getter, and if so, it allocates the target list in one go.

Also, the default `map` method creates an iterable that is marked as having an efficient length if the original iterable had that. 

In the linked example, I *think* the `serializedExecutable.parameters` value is `List`, and the `map(..).toList()` should be efficient at allocating the list.

**Comment by scheglov** [comment] 2016-05-20 16:05
@bwilkerson @stereotype441 

If nothing else, this application should print `true`.
Otherwise we penalize clients that attempt to do transformations of (often) empty lists by creating a lot of empty, immutable lists.

```
main() {
  var r1 = [].map((e) => e).toList(growable: false);
  var r2 = [].map((e) => e).toList(growable: false);
  print(identical(r1, r2));
}
```

Other than that:

1. I don't know how expensive it is to create closures `(e) => e` or `(e) => something(data, e)` and whether it still costs something when `map` is applied to an empty target.

2. The same question is applied to creating any new `Iterable` or `Iterator` instances to iterate over empty targets.

3. Whether any of this `map().toList()` processing causes MegamorphicLookup(s). AFAIK it does not in case of inlined `for-index` loops, and I don't want to pay anything to `map().toList()` convenience.

**Comment by lrhn** [comment] 2016-05-20 16:48
You likely won't get identical lists. The problem is that `toList` preserves the type parameter of the iterable, so `<int>[].toList(growable:false)` must differ from `<String>[].toList(growable:false)`. Currently the `map` function always generate an `Iterable<dynamic>`, but that'll change with generic methods and has already changed in strong mode. That means that even for an empty input, we can't just return `const[]`.

Creating closures costs, at least by creating a new object. We should have some standard functions available so you don't have to create a new one (identity is a good example, I'm sure there are others). A top-level/static function is canonicalized so you don't create a new object every time you use it. 

Creating an iterator costs, again at least by creating the object, and again we can't just reuse an empty iterator because of type parameters.

I'd expect `map().toList()` to cause some polymorphism since the `toList` isn't special for `map` - it's the same `toList` used by most iterables. It may get specialized to `MappedIterable` and `EfficientLengthMappedIterable` (I'm guessing, I have no idea what we do about specializing inherited methods).

**Comment by scheglov** [comment] 2016-05-20 17:05
@bwilkerson @stereotype441 

Why not return `const <T>[]` from `toList()`? I know that it's not allowed by the language specification, but I don't care much about this as a user. If this should work magically to make the language feature working, it should be done one way or another.

Basically this is my impression from the whole Dart situation - a lot of nice features that you **cannot use** because they will kill performance. So, I get back to writing old-style Java code. Damn, I think with Java 8 even Java code would look nicer and still work faster.

**Comment by lrhn** [comment] 2016-05-20 18:05
Not being allowed by the language is a pretty good reason to me.

We could introduce a magical factory constructor on List which returns a canonicalized empty unmodifiable list per type parameter. That would require some tricky implementation that caches (weakly referenced) instances as long as they are live, but when all empty lists of a particular type are dead, it can be removed from the cache. We can't do that in Dart code, it requires interaction with garbage collection.

That's a lot of complexity to require from an implementation in order to not create more empty unmodifable list objects.

I can see that it would be great if transformation of empty lists was as efficient as not doing anything.
It'll never be completely free since you do create the intermediate iterables. The compiler can only optimize that away if it knows the underlying iterable, but I guess a fast-case for `List` operations is possible - `listOfT.skip(2).map<S>(f).toList()` could be inlined and compiled directly to an efficient allocation and loop.

**Comment by scheglov** [comment] 2016-05-20 23:16
Why do we need a weak cache? There is always a finite number of types in the VM instance. So, there is always a finite number of empty lists.

Yes, it would be awesome to inline and compile to loop simple `List` transformations!

**Comment by lrhn** [comment] 2016-05-20 23:21
The number of types seen in a running program isn't bounded and can grow arbitrarily. Keeping all the empty lists you have ever seen alive is a potential memory leak. It *probably* won't happen, but it shouldn't be possible.

Example:
```dart:
class C<T> {
    List create(int depth) => depth == 0 ? new List<C<T>>(0) : new C<C<T>>().create(depth - 1);
}
```

**Comment by scheglov** [comment] 2016-05-21 02:13
You're right.

**Comment by lrhn** [comment] 2016-05-23 14:44
In other words, I don't think there is any more we can do here right now
.

**Closed by lrhn** 2016-05-23 14:44 UTC
Labels: area-library, library-core, Resolution: fixed, Type: enhancement, Type: performance

**Comment by lrhn** [comment] 2016-05-23 14:47
I'm not sure there is anything fundamental we can do better here. There's probably a few pin-hole optimizations for the empty cast that we can do, but the general case of not using growing lists when the length is known to be efficient, is already handled.
