### ISSUE TITLE
string mode says that I need to cast, sdk says unnecessary cast

### ISSUE THREAD

**Issue by pstjvn** [dart-lang/sdk#26308] opened 2016-04-20 21:28 UTC
I have defined a typedef and it uses an abstract class
``` dart
abstract class IState {
  num timestamp;
  void clear();
}
typedef void AnimationCallback(IState state);
//and a default implementation: 
class State implements IState {
  num timestamp = 0;
  State();
  void clear() {}
}
//And then I extend that:
class MyState extends State implements IState {
  num previousTimestamp = 0;
  MyState() : super();
}
//And I try to use it...
AnimationCallback _mutate = (MyState state) {
    if (counter < 5) anim();
  } 
//as AnimationCallback;
```
The problem is that if I do not cast (using 'as AnimationCallback') strong mode says that my function is not of correct type, but if I use the cast it says 'unnecessary cast'.

I think it might be a bug but I am not sure which way is correct.

**Comment by bwilkerson** [comment] 2016-04-20 21:39
It's a bug. In strong mode you need the cast.

**Comment by jmesserly** [comment] 2016-04-20 21:41
I believe this is an SDK issue ... @jacob314 was just looking into a fix for dart:html. Did we get those changes landed into the SDK? I saw the DDC change go by

**Comment by jmesserly** [comment] 2016-04-20 21:42
Oh sorry, I misread the example, we had a similar issue with one of the HTML types. My bad!

**Comment by jmesserly** [comment] 2016-04-20 21:45
but: that is not valid strong mode code. AnimationCallback says it can accept any IState. However you are requiring "MyState" in your callback. How do you know it will be passed a MyState?

Suggestions:
* Make your callback accept "IState" and cast inside the method.
* or make AnimationCallback require MyState.

Note that cast would fail at runtime in strong mode, because it is not safe.

**Comment by jmesserly** [comment] 2016-04-20 21:46
Closing because I don't think this is a strong mode bug. Let me know if I've missed something.

**Comment by bwilkerson** [comment] 2016-04-20 22:04
He's running strong mode and it's giving him one error if he doesn't include the cast and a different error if he doesn't. The second error shouldn't be getting produced, hence the bug. And it's fairly obnoxious because he can't make the code error free.

**Comment by jmesserly** [comment] 2016-04-21 01:06
The cast is not correct though. It is unnecessary (it is already implied by the type on the left), and it will fail at runtime (either written explicitly or not). The way to make the code correct is what I described above.

**Comment by jmesserly** [comment] 2016-04-21 01:06
all you are doing with the explicit cast is silencing the more useful message: that the parameter type is wrong.

**Comment by bwilkerson** [comment] 2016-04-21 04:25
Sorry, I misunderstood what you said. You're right, it's not a bug (except in his code).

**Closed by bwilkerson** 2016-04-21 04:25 UTC
Labels: analyzer-strong-mode, area-analyzer, P2 medium, Type: bug

**Comment by pstjvn** [comment] 2016-04-21 07:59
I understand now. What I rally wanted to express with the code is generic in a way:
* the type passed in as 'state' must implement IState and will be passed as argument to measure and mutate
Is there a way to express that in Dart.
In closure type system I would use generics (@template) and type T will be required for the two callbacks passed in.
Thanks

**Comment by eernstg** [comment] 2016-04-21 11:17
Generic classes are available in Dart, and generic methods are coming (try `dartanalyzer` in a package where you have a '.analysis_options' file in the package root containing
```
analyzer:
  language:
    enableGenericMethods: true
```
which will allow you to check them --- but, e.g., dart2js doesn't yet compile them). But it is not obvious how any of those two kinds of genericity would help you use a type like `MyState` for the argument `state` in the function literal. Any call site for an `AnimationCallback` would need to be equipped with the right type parameter in order to know how to satisfy the requirements for its parameter, and that would take at least some machinery to get right.

**Comment by pstjvn** [comment] 2016-04-21 11:23
I am sorry, maybe it is not clear, I am coming from closure where I would write it like this:
``` javascript
/** 
 * @param {T} state
 * @param {function(T): void} measure
 * @param {function(T): void} mutate
 * @template T
 */
function Animation(state, measure, mutate) {...}
```
Where the compiler would enforce that the measure and mutate will accept the template type T which is used for state. The pattern is used in several places in the library. The one thing missing here is that the template T must be a sub-type of another type or implement a certain interface. Is this behavior possible in Dart?

**Comment by jmesserly** [comment] 2016-04-21 16:39
@pstjvn -- thanks that is a great description!

> Where the compiler would enforce that the measure and mutate will accept the template type T which is used for state. The pattern is used in several places in the library. The one thing missing here is that the template T must be a sub-type of another type or implement a certain interface. Is this behavior possible in Dart?

Maybe like this?
```dart
typedef void AnimationCallback<T extends IState>(T state);
```

That would allow `AnimationCallback<MyState>`

For this signature in particular:
```js
/** 
 * @param {T} state
 * @param {function(T): void} measure
 * @param {function(T): void} mutate
 * @template T
 */
function Animation(state, measure, mutate) {...}
```
I presume from the upper case name, it is a constructor function called like `new Animation(...)` ?

In that case I would write it as a class in Dart:
```dart
typedef void AnimateCallback<T extends IState>(T value);

class Animation<T extends IState> {
  AnimateCallback<T> _measure; // if you want to store it a field for later
  Animation(T state, AnimateCallback<T> measure, AnimateCallback<T> mutate) {
    _measure = measure;
    // ...
  }
}
```

If it is just a generic function it could be like this:
```dart
typedef void AnimateCallback<T extends IState>(T value);

// Note: comments are needed because we aren't quite done with the generic methods.
// But you can use it in IDE/Analyzer.
void animation/*<T extends IState>*/(T state, AnimateCallback<T> measure, AnimateCallback<T> mutate) { ... }
```

**Comment by pstjvn** [comment] 2016-04-21 16:57
That's what I was looking for, one final question:
<T extends IState> - IState is an abstract class, does any class that implements it can be considered to 'extend' it?

**Comment by jmesserly** [comment] 2016-04-21 17:00
> - IState is an abstract class, does any class that implements it can be considered to 'extend' it?

yes, exactly.

BTW, there is a related "unnecessary cast" bug: https://github.com/dart-lang/sdk/issues/26027
(In that one, once the cast is added, we know enough information to do inference, and infer the right type... which makes things really confusing)

We've been discussing this further, I'm going to file a few other issues related to this. I think we can make our errors a lot more helpful in cases like this.

**Comment by jmesserly** [comment] 2016-04-21 17:18
Filed: https://github.com/dart-lang/sdk/issues/26317 (explicit casts silence errors about casts that can't work) and https://github.com/dart-lang/sdk/issues/26318 (ideas for improving our error messages)
