### ISSUE TITLE
Dart Analyzer error on two vars in one string

### ISSUE THREAD

**Issue by rostopira** [dart-lang/sdk#37114] opened 2019-05-29 15:56 UTC
Sample code to reproduce:
```dart
var firstVar = 1;
var secondVar = false;
final someStr = "blabla$firstVar$secondVar";
```
Error appears when you type second `$` character

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7141.44`
- `2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e`
- `IU-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 1920x1080, 1600x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e, server version 1.26.1, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:389:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1298:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4806:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4731:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4151:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4084:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3880:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3852:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4921:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4893:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4874:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4853:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4589:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4145:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4084:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3880:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3852:13)
#18     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4921:15)
#19     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4893:12)
#20     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4874:14)
#21     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4853:13)
#22     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4589:12)
#23     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4145:14)
#24     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4084:12)
#25     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3880:13)
#26     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3852:13)
#27     Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3759:13)
#28     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3642:14)
#29     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3625:20)
#30     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3530:15)
#31     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3179:15)
#32     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3042:15)
#33     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2818:15)
#34     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1781:13)
#35     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1741:14)
#36     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:575:14)
#37     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#38     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#39     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#40     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#41     _File._parse (package:analyzer/src/services/available_declarations.dart:1633:23)
#42     _File.refresh (package:analyzer/src/services/available_declarations.dart:1071:30)
#43     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:639:10)
#44     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:505:7)
#45     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:225:13)
<asynchronous suspension>
#46     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2142:35)
<asynchronous suspension>
#47     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2092:5)
#48     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#49     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#50     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#51     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:532:21)
#52     _rootRun (dart:async/zone.dart:1124:13)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _runZoned (dart:async/zone.dart:1516:10)
#55     runZoned (dart:async/zone.dart:1463:12)
#56     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:617:12)
#57     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:530:7)
#58     Driver.start (package:analysis_server/src/server/driver.dart:435:7)
#59     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#60     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#61     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#62     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by vsmenon** [comment] 2019-05-29 19:30
@danrubel - should this be marked front-end or analyzer?

**Comment by danrubel** [comment] 2019-06-04 13:55
area-analyzer makes sense to me. I'll dig and see what I can figure out.

**Comment by danrubel** [comment] 2019-06-18 17:26
I loaded version e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e and tried the following but failed to recreate the parser exception.
```
final someStr = "blabla\$firstVar\$
final someStr = "blabla\$firstVar\$"
final someStr = "blabla\$firstVar\$""
```
Can you give me some more guidance on how to recreate the problem?

**Comment by srawlins** [comment] 2019-08-29 05:39
Note this was again reported 3 days ago with Dart 2.4.0.

**Comment by srawlins** [comment] 2019-10-22 04:45
This has been reproduced in fuzz testing; please follow https://github.com/dart-lang/sdk/issues/39035.

**Comment by srawlins** [comment] 2019-10-22 04:46
Duplicate of https://github.com/dart-lang/sdk/issues/39035

**Closed by srawlins** 2019-10-22 04:46 UTC
Labels: analyzer-crash-report, area-analyzer, front-end-fasta, needs-info, type-bug
