### ISSUE TITLE
Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#42786] opened 2020-07-21 23:15 UTC
While editing code, got multiple codeAction errors:

```
[Error - 4:08:32 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:08:32 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'getMethod' was called on null.
Receiver: null
Tried calling: getMethod("debugFillProperties")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AddDiagnosticPropertyReference.compute (package:analysis_server/src/services/correction/dart/add_diagnostic_property_reference.dart:103:26)
#2      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:252:24)
#3      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:172:11)
#4      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:174:39)
#5      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:204:7)
#6      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:74:18)
#7      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:71:26)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#10     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:70:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#12     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:17)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[Error - 4:11:44 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:11:44 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'getMethod' was called on null.
Receiver: null
Tried calling: getMethod("debugFillProperties")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AddDiagnosticPropertyReference.compute (package:analysis_server/src/services/correction/dart/add_diagnostic_property_reference.dart:103:26)
#2      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:252:24)
#3      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:172:11)
#4      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:174:39)
#5      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:204:7)
#6      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:74:18)
#7      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:71:26)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#10     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:70:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#12     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:17)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[Error - 4:13:32 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:13:32 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'getMethod' was called on null.
Receiver: null
Tried calling: getMethod("debugFillProperties")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AddDiagnosticPropertyReference.compute (package:analysis_server/src/services/correction/dart/add_diagnostic_property_reference.dart:103:26)
#2      AssistProcessor._addFromProducers (package:analysis_server/src/services/correction/assist_internal.dart:252:24)
#3      AssistProcessor.compute (package:analysis_server/src/services/correction/assist_internal.dart:172:11)
#4      CodeActionHandler._getAssistActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:174:39)
#5      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:204:7)
#6      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:74:18)
#7      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:71:26)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#10     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:70:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#12     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:17)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## Dart Version
```
[C:\src\win32] dart --version
Dart SDK version: 2.9.0-21.0.dev.flutter-9dca49e71e (be) (Fri Jul 17 13:26:08 2020 +0000) on "windows_x64"
```

**Comment by bwilkerson** [comment] 2020-07-21 23:49
This is a known issue, and I believe that @pq is working on a fix.

**Comment by bwilkerson** [comment] 2021-04-30 22:10
@DanTup The line and offset information are outdated, but the method appears to have not been changed since 11/20.

**Comment by DanTup** [comment] 2021-05-01 09:50
@bwilkerson strange - I can't figure out how we'd end up with a double here. Although the types were previously `num` for `Position.line` and `Position.col` as they were mapped from the LSP spec in TS. They've recently been overridden to `int` in the Dart types:

https://github.com/dart-lang/sdk/commit/77466f2b83e9c8467b2711c906770658759062ad#diff-e5f878eb3b982e6ce6990868f00e1429427e1c9063821475fc4c2ef5071b8013L19502

I don't know whether that would resolve the issue, or just push the error earlier though.

@wondertalik can you reliably reproduce the issue? Are you using VS Code or another LSP client?

**Comment by wondertalik** [comment] 2021-05-01 12:35
@DanTup 

I found a reason probably, maybe it is a problem an [extension](https://marketplace.visualstudio.com/items?itemName=markis.code-coverage)  of vscode. When it is activated and I go to the widget not covered by tests, I get this message. Is it extension or sdk problem? I can try to provide an example of code if needed.

**Comment by bwilkerson** [comment] 2021-05-01 15:18
> They've recently been overridden to int in the Dart types:

As far as I can tell, that change didn't make it into a build until 2.14.0-18.0.dev, so it isn't in the version that @wondertalik is using.

That said, if we're really getting a double from the protocol then the change from `num` to `int` might not be safe in all cases.

**Comment by DanTup** [comment] 2021-05-01 16:49
@wondertalik I wasn't able to reproduce it with those instructions. If you can, could you try the following:

- Get to the point of being able to reproduce
- Run the **Dart: Capture Analysis Logs** command from the VS Code command palette
- Move the cursor away, then back to the code that triggers the error
- Click the **Cancel** button on the Logging notification to stop logging and open the log

Ensure the log doesn't contain anything sensitive (it's best to repro on a sample app) and provide here in an attachment (or [gist](https://gist.github.com/)).

@bwilkerson 

> As far as I can tell, that change didn't make it into a build until 2.14.0-18.0.dev, so it isn't in the version that @wondertalik is using.

Yep, I was wondering if that change might _fix_ it. I wondered if something was infererred as a `double` somewhere previously, and this may prevent it (I thought I'd made this change because I saw a similar error running tests - but had assumed it was caused by some of the null-safety changes, although that wouldn't explain this).

> That said, if we're really getting a double from the protocol then the change from `num` to `int` might not be safe in all cases.

The types are `num` in the spec (because it's TS/JS with no ints), but I don't think it's _valid_ to send a double for them (they're line/column numbers). Rejecting them at the protocol probably makes sense (I'd expect the JSON parse to fail, and the request to be rejected as having invalid params), although this would probably mean rejecting ints formatted as doubles like "2.0" - I don't know if that's a real concern (and I did wonder if it was that, but since it's VS Code I think that's unlikely).

**Comment by wondertalik** [comment] 2021-05-01 20:32
@DanTup , as you said.

```
[Error - 10:28:12 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 10:28:12 PM] An error occurred while handling textDocument/codeAction request: type 'double' is not a subtype of type 'int'
#0      toOffset (package:analysis_server/src/lsp/mapping.dart:1108:42)
#1      CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:75:25)
#2      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#3      CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:73:17)
<asynchronous suspension>
#4      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#5      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>
```
[Dart-Code-Log-2021-04-06 22-28-00.txt](https://github.com/dart-lang/sdk/files/6410252/Dart-Code-Log-2021-04-06.22-28-00.txt)

**Comment by DanTup** [comment] 2021-05-03 16:44
@wondertalik thanks! The log shows the problem:

```js
{
	"jsonrpc": "2.0",
	"id": 134,
	"method": "textDocument/codeAction",
	"params": {
		"textDocument": {
			"uri": "file:///Users/wn/Works/study/code_action_bug_handler/lib/main.dart"
		},
		"range": {
			"start": {
				"line": 3,
				"character": 2
			},
			"end": {
				"line": 3,
				"character": 1.7976931348623157e+308
			}
		},
		"context": {
			"diagnostics": [
				{
					"range": {
						"start": {
							"line": 3,
							"character": 0
						},
						"end": {
							"line": 3,
							"character": 1.7976931348623157e+308
						}
					},
					"message": "[code-coverage] line not covered",
					"severity": 3
				}
			],
			"only": [
				"quickfix"
			]
		}
	}
}
```

I suspect you have an extension installed that is producing diagnostic messages for missing code coverage (which VS Code is using as the range for code actions requests when your caret is within that range). However, the value for `character` is not valid, so there's likely a bug in that extension (or the coverage data that's been generated).

I checked the LSP spec again, and this field is typed as `uinteger` and not `number` as I thought further up. `uinteger` is defined like this:

```typescript
/**
 * Defines an unsigned integer number in the range of 0 to 2^31 - 1.
 */
export type uinteger = number;
```

So although the TypeScript definitions do map it onto `number`, the comment suggest it's _not_ valid to send non-integers. The error is not reported as it should be here, although that should be fixed by my change noted above, as it'll now be rejected by the parsing of the requests `params` rather than getting through to the code actions handler.

If the coverage data that's been collected looks good, I'd recommend filing an issue with the coverage extension you're using (feel free to CC me if I may be able to help explaining the issue).

**Comment by wondertalik** [comment] 2021-05-03 22:53
@DanTup thanks for you time. Maybe it was my mistake use this extension for dart code. I have asked in the repo extension if it has support of dart.

**Comment by DanTup** [comment] 2021-05-04 09:35
@wondertalik no mistake, it should all work together - we just need to figure out where it needs to be fixed :-)

I looked again, and realised the number above wasn't actually a decimal, it was just a _very large_ integer. I looked through the code for that extension and found the cause:

https://github.com/markis/vscode-code-coverage/blob/bb8cdae9cb243f1514da7af2e9960f3fa87ccd56/src/extension.ts#L160

This is `Number.MAX_VALUE` in JavaScript. As far as I can tell, that's actually valid for the VS Code API, however LSP only allows numbers up to 2^31. I'm not sure whose responsibility it should be to handle this, but I've filed https://github.com/microsoft/vscode-languageserver-node/issues/761 in the VS Code LSP client as I think perhaps it should be there.

It also makes mo wonder why we're parsing it as a double though, as my understanding was that Dart ints in the VM could handle 2^1024. I'll do some more testing, as if we can parse that correctly as an int then the error should disappear even if the number isn't strictly within the LSP spec.

**Comment by DanTup** [comment] 2021-05-04 10:20
I was mistaken - the Dart VM appears to only support ints up to around 2^53. This is larger than the LSP spec allows, but smaller than the number here (which is why it was parsed as a double).

With the changes I mentioned above, we'll now _only_ parse the value as an int, so although the request will still fail (because the number is both invalid according to the spec and does not fit within a Dart int), it will now fail earlier (during parsing of params) and with a more specific message:

> Invalid params for textDocument/codeAction:
> params.range.end.character must be of type int

I've added a test at https://dart-review.googlesource.com/c/sdk/+/198041/ to ensure this is the error returned. I think the real fix should come from the LSP Client (the issue I've raised above), or if they deem VS Code shouldn't be passing this on, there. In the meantime I'll add a note to the coverage extension's issue about suggesting the look up the real end point of the line rather than using `Number.MAX_VALUE`.

I won't close this issue, as I think this was actually unrelated to the original reported issue here (although if @pq was working on a fix, perhaps that's also done and this can be closed anyway?).

**Comment by DanTup** [comment] 2022-02-14 10:49
This was fixed in the LSP client by https://github.com/microsoft/vscode-languageserver-node/issues/761.

**Closed by DanTup** 2022-02-14 10:49 UTC
Labels: area-analyzer, P3, type-bug, analyzer-crash-report

**Comment by DanTup** [comment] 2022-02-14 10:55
Sorry, I misread the last comment here - the issue that was resolved was not the original one, just the one hit by @wondertalik which was specific to some behaviour from another VS code extension. Although looking  again, this was resolved by https://github.com/dart-lang/sdk/commit/2e6dd678594750b41d2f1ae799a0c505bf07d619 (via #42749).
