### ISSUE TITLE
Analyzer feedback

### ISSUE THREAD

**Issue by vainas-brazdeikis** [dart-lang/sdk#41201] opened 2020-03-25 19:38 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.8.0-edge.9983424a3c50c623730fd43b4ce263df660eb455`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.9983424a3c50c623730fd43b4ce263df660eb455, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:657:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

For additional log information, please append the contents of
file://C:\Users\vaina\AppData\Local\Temp\report2.txt.

**Comment by srawlins** [comment] 2020-06-12 22:47
Thanks for reporting this issue! This was previously reported in #40223. Please follow along there.

**Comment by srawlins** [comment] 2020-06-12 22:47
Duplicate of #40223

**Closed by srawlins** 2020-06-12 22:47 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
