### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zyonehangao** [dart-lang/sdk#36903] opened 2019-05-09 06:06 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1440x900`

# Exception

Please append the contents of:
file:///private/var/folders/hq/rkkhz6px66j4blqrn_jn6ygm0000gn/T/report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Found element with null library: WidgetTester
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:848:31)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44:12)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:252:16)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2234:49)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:5300:10)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2234:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2157:17)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5968:10)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4628:18)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:2990:35)
#11     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:5290:11)
#12     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:2153:49)

**Comment by srawlins** [comment] 2019-09-06 04:50
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/34554; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 04:50
Duplicate of https://github.com/dart-lang/sdk/issues/34554

**Closed by srawlins** 2019-09-06 04:50 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
