### ISSUE TITLE
dead_null_aware_expression missed by analyzer

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#42791] opened 2020-07-22 08:50 UTC
Migrating some code to nullsafety I face different behaviour between CFE and analyzer. The CFE triggers the following warning but the analyzer didn't show any warning.

```
../lib/src/rendering/proxy_box.dart:1847:7: Warning: Operand of null-aware operation '??=' has type 'PhysicalModelLayer' which excludes null.
 - 'PhysicalModelLayer' is from 'package:flutter/src/rendering/layer.dart' ('../lib/src/rendering/layer.dart').
      layer ??= PhysicalModelLayer();
      ^
```

It looks like the CFE is correct and here is a smaller repro:

```dart
class A {
  num? get value => null;
  set value(num? value) {}
}

class B extends A {
  int get value => super.value as int;
  void m() {
    value ??= 1; // the value getter in B being non-nullable there should be a "dead_null_aware_expression" warning
  }
}
```

> Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 84e5eeaea4)

**Comment by scheglov** [comment] 2020-07-26 22:19
This is caused by a mess we have now with read/write type, to be fixed as https://github.com/dart-lang/sdk/issues/42269

**Comment by scheglov** [comment] 2020-09-29 06:08
The referenced about issue with read/write types has been fixed enough that this issue is now fixed - the analyzer does report the hint.

The technical debt issue is still open because I have not finished migrating all the clients and removing old APIs yet.
But this one can be closed now.

**Closed by scheglov** 2020-09-29 06:08 UTC
Labels: NNBD, area-analyzer, type-bug
