### ISSUE TITLE
 Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by ossama0808** [dart-lang/sdk#38999] opened 2019-10-20 05:55 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6817.14`
- `2.6.0-edge.a61c775db81ef2a389d5aee6236176362b082d58`
- `IU-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1600x900`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.a61c775db81ef2a389d5aee6236176362b082d58, server version 1.27.3, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [D:\Projects\Shopping_Zone], excluded: [D:\Projects\Shopping_Zone\.idea, D:\Projects\Shopping_Zone\.dart_tool, D:\Projects\Shopping_Zone\.pub, D:\Projects\Shopping_Zone\build]}, clientRequestTime: 1571550822526}
FileSystemException: Directory watcher closed unexpectedly, path = 'D:\Projects\Shopping_Zone'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:307:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file://C:\Users\samsu\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-10-21 14:43
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38853; please follow along there.

**Comment by srawlins** [comment] 2019-10-21 14:43
Duplicate of https://github.com/dart-lang/sdk/issues/38853

**Closed by srawlins** 2019-10-21 14:43 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
