### ISSUE TITLE
analyzer won't promote type arguments in "is"?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#27838] opened 2016-11-16 20:41 UTC
```dart
class A<T> {
  void aaa(T item) {
    if (item is B) {
      var thing = item;
      fn(thing);  // WARNING
    }
  }
}

class B {}

void fn(B b) {
  print(b);
}
```

([dartpad](https://dartpad.dartlang.org/8fbdfb4c33a10f53155e0efa8c54a4af))

yields: _"The argument type 'T' cannot be assigned to the parameter type 'B'."_ (INFO on normal mode; WARNING on strong mode) on line 5.

But shouldn't `item` have been promoted from a T to a B at this point?

**Comment by bwilkerson** [comment] 2016-11-16 20:58
Not according to the current version of the specification. Type promotion only occurs if the right operand of the is-expression (in this case `B`) is more specific than the static type of the left operand (in this case `T`). But `B` is not more specific than `T`, so type promotion doesn't occur here.

**Comment by srawlins** [comment] 2016-11-16 21:01
Ah, interesting. You say "current version", like maybe this concept will change for Strong Mode? Or no?

**Comment by leafpetersen** [comment] 2016-11-16 21:42
I believe that @jmesserly landed an improvement to strong mode promotion that makes this work, but this hasn't rolled to dartpad yet.

**Comment by jmesserly** [comment] 2016-11-17 00:48
indeed, this example appears to work when I try it out in a local build.

**Comment by bwilkerson** [comment] 2016-11-17 00:49
> You say "current version" ...

I only mean that the language is still evolving and I don't know what the future will hold.

> I believe that @jmesserly landed an improvement to strong mode promotion that makes this work ...

Is promotion different in strong mode, or is it just the notion of "more specific than" that's changed?

**Comment by jmesserly** [comment] 2016-11-17 00:54
> Is promotion different in strong mode, or is it just the notion of "more specific than" that's changed?

promotion is different in strong mode. See tryPromoteToType in type_system.dart. In this example, we can promote "item" from "T" to "T extends B". We also removed the exclusion about promoting from dynamic. I don't remember if there were other improvements.

**Comment by bwilkerson** [comment] 2016-11-17 00:57
@leafpetersen I assume you'll work with the language team to get those differences into the strong mode spec.

**Comment by jmesserly** [comment] 2016-11-17 00:58
that's the plan, yes :)

**Comment by leafpetersen** [comment] 2016-11-17 09:30
Yes, I am working on getting all of the details of strong mode specified.  Priority so far this quarter has been resolving all of the issues that still require implementation work, but I'm hoping to be able to spend more time on this soon.

**Comment by bwilkerson** [comment] 2016-11-22 19:42
As this appears to be working on bleeding edge, I'm closing the issue. If the problem is still there after the next release, please re-open the issue.

**Closed by bwilkerson** 2016-11-22 19:42 UTC
Labels: area-analyzer
