### ISSUE TITLE
Hang when publishing package

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#26104] opened 2016-03-28 19:38 UTC
With pub running on the bleeding edge Dart VM, pub hangs when attempting to publish a package. I have confirmed that the latest pub code can successfully publish fine when run against an older Dart SDK, so I believe this is *not* a bug in pub. See [https://github.com/dart-lang/pub/issues/1399] for more.

**Comment by zanderso** [comment] 2016-03-28 20:09
Is this on Mac? We recently switched out BoringSSL for SecureTransport there and the bug may be related to that.

**Comment by kevmoo** [comment] 2016-03-28 20:16
@zanderso Yup – hitting on my mac, too

**Comment by zanderso** [comment] 2016-03-28 20:18
Okay, thanks. I'll take a look.

**Comment by munificent** [comment] 2016-03-28 20:25
On my Mac too. Thanks, @zanderso!

**Comment by jmesserly** [comment] 2016-03-28 21:59
This also happens in `pub get` for recent Analyzer packages. `pub cache add analyzer --all` will reproduce, each time it will successfully download one version then hang on the second. At some version it can't even download one.

**Comment by zanderso** [comment] 2016-03-28 22:18
Thanks. I have reproduced the hang, and I'm working on finding the cause.

**Comment by zanderso** [comment] 2016-03-29 16:54
https://codereview.chromium.org/1842703003/

**Comment by zanderso** [comment] 2016-03-29 17:32
I've landed a fix. The hang in pub is gone for me. Please check on your end, and I'll close the issue. Thanks for the bug report!

**Comment by kevmoo** [comment] 2016-03-29 17:44
Just tried 5cee7ff634e715f6b2b0c8bfa3980206545d6916 - seem to work now!

**Comment by zanderso** [comment] 2016-03-29 17:46
Great!

**Closed by zanderso** 2016-03-29 17:46 UTC
Labels: area-library, library-io
