### ISSUE TITLE
[Bug] Analyzer Feedback from IntelliJ: Invalid range in LanguageModel

### ISSUE THREAD

**Issue by NathanaelA** [dart-lang/sdk#39340] opened 2019-11-12 07:14 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.7.0-edge.bdd9e74afc1681ca7e43945e3547641321486ab7`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v5.0.0-32-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.bdd9e74afc1681ca7e43945e3547641321486ab7, server version 1.27.4, FATAL error: RangeError (end): Invalid value: Not in range 0..50, inclusive: 100
#0      RangeError.checkValidRange (dart:core/errors.dart:333:9)
#1      _TypedDoubleListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart:754:18)
#2      _DoubleListMixin.setAll (dart:typed_data-patch/typed_data_patch.dart:735:5)
#3      LanguageModel._transformInput (package:analysis_server/src/services/completion/dart/language_model.dart:97:9)
#4      LanguageModel.predictWithScores (package:analysis_server/src/services/completion/dart/language_model.dart:74:21)
#5      entrypoint.<anonymous closure> (package:analysis_server/src/services/completion/dart/completion_ranking.dart:39:34)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#10     _StreamController._add (dart:async/stream_controller.dart:640:7)
#11     _StreamController.add (dart:async/stream_controller.dart:586:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment] 2019-11-13 16:50
Thanks for reporting this issue! This has also been reported at https://github.com/dart-lang/sdk/issues/39352; please follow along there.

**Comment by srawlins** [comment] 2019-11-13 16:51
Duplicate of https://github.com/dart-lang/sdk/issues/39352

**Closed by srawlins** 2019-11-13 16:51 UTC
Labels: P1, analyzer-crash-report, area-analyzer, type-bug
