### ISSUE TITLE
Analyzer: Missing promotion?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42707] opened 2020-07-15 16:26 UTC
[Edit: Removed the `!` from `return x!;`]

Consider the following function:

```dart
T foo<T>(T Function() fun) {
  T? x = null;
  x = fun();
  return x;
}
```

The analyzer (commit a48bebea1ed8dd0d3950e6120057a3a5bdae5518) reports the following error for this:

```
ERROR|STATIC_TYPE_WARNING|RETURN_OF_INVALID_TYPE|/usr/local/google/home/eernst/lang/dart/scratch/202007/n016.dart|4|10|1|A value of type 'T?' can't be returned from function 'foo' because it has a return type of 'T'.
```

Similarly, the common front end reports this:

```
n016.dart:4:10: Error: A value of type 'T?' can't be returned from a function with return type 'T'.
  return x;
         ^
```

I would expect the assignment to `x` in line 3 to promote `x` to type `T`: It is a type of interest because `T?` is the declared type and `T` is the non-nullable version of `T?`, but the error implies that this promotion didn't occur. Shouldn't it?

(I'm only creating a single issue because I suspect that this behavior is in code that is shared among the analyzer and the CFE.)

**Comment by scheglov** [comment] 2020-07-16 03:03
Hm...
I cannot reproduce this.
```console
scheglov@scheglov-macbookpro2:~/Source/Dart/sdk.git/sdk (master)$ dartanalyzer --version
dartanalyzer version 2.9.0-edge.86087261006af6f71021fc1b7979b1e90d1d13e3
scheglov@scheglov-macbookpro2:~/Source/Dart/sdk.git/sdk (master)$ dartanalyzer --enable-experiment=non-nullable /Users/scheglov/dart/test/bin/test.dart
Analyzing /Users/scheglov/dart/test/bin/test.dart...
No issues found!
```

**Comment by johnniwinther** [comment] 2020-07-16 07:01
Shouldn't the code example have been 
```Dart
T foo<T>(T Function() fun) {
  T? x = null;
  x = fun();
  return x;
}
```
without the bang in the return statement expression?

**Comment by eernstg** [comment] 2020-07-16 07:18
True, the `!` shouldn't be there: I put it in to check the situation, forgot to delete it again. Thanks!

**Comment by leafpetersen** [comment] 2020-09-11 01:29
This is working as currently specified.  We specify that the types of interest for `x` are `T?` and `**NonNull**(T?)`, and the latter is defined to be `T & Object`.  When assigning `fun()` to `x`, we check whether the return type `T` is a type of interest, which it is not, and so we do not promote.  If we wanted to fix this, we would probably need to have `**NonNull**` return a set of types, including all of the intermediate steps taken along the way.  There's something to be said for this, but I  think this is out of scope for fixing now.

**Closed by leafpetersen** 2020-09-11 01:29 UTC
Labels: NNBD, area-analyzer, area-front-end, type-bug
