### ISSUE TITLE
Continuously getting errors in IntelliJ Dart Plugin's Analyzer

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#35892] opened 2019-02-09 09:39 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-183.5429.30`
- `2.1.0`
- `IC-183.5429.30, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-139-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.1.0, server version 1.21.1, FATAL error: Failed to handle request: {id: 12476, method: edit.getFixes, params: {file: /home/renato/programming/projects/webdart-example/lib/src/reflect.dart, offset: 1148}, clientRequestTime: 1549705016232}
type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'
#0      FixProcessor._addFix_undefinedMethod_create (package:analysis_server/src/services/correction/fix_internal.dart:3315:9)
<asynchronous suspension>
#1      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:535:13)
<asynchronous suspension>
#2      DefaultFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart:134:53)
<asynchronous suspension>
#3      DefaultFixContributor.internalComputeFixes (package:analysis_server/src/services/correction/fix_internal.dart:90:37)
<asynchronous...... 

_URI_TOO_LARGE_ so I had to cut off the rest.

**Comment by stereotype441** [comment] 2019-02-12 00:52
Duplicate of #35857

**Closed by stereotype441** 2019-02-12 00:52 UTC
Labels: area-analyzer
