### ISSUE TITLE
flutter.bat --no-color clean

### ISSUE THREAD

**Issue by twovs** [dart-lang/sdk#36398] opened 2019-03-30 11:32 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.1.0-dev.9.4`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1600x900`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [G:\flutterapps\twovv_programmer_english], excluded: [G:\flutterapps\twovv_programmer_english\.idea, G:\flutterapps\twovv_programmer_english\.dart_tool, G:\flutterapps\twovv_programmer_english\.idea, G:\flutterapps\twovv_programmer_english\.pub, G:\flutterapps\twovv_programmer_english\build]}, clientRequestTime: 1553942778182}
FileSystemException: Exists failed, path = 'G:\flutterapps\twovv_programmer_english\build\app\intermediates\javac\debug\compileDebugJavaWithJavac\classes\xyz\luan' (OS Error: 拒绝访问。
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#4      _WindowsDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/windows.dart:163:24)
#5      _WindowsDirectoryWatcher._onEvent.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:157:7)
#6      _rootRun (dart:a

**Comment by srawlins** [comment] 2019-09-06 15:54
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/33106; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 15:54
Duplicate of https://github.com/dart-lang/sdk/issues/33106

**Closed by srawlins** 2019-09-06 15:54 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
