### ISSUE TITLE
optimize _memCopy from dart:ffi

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#48139] opened 2022-01-13 09:14 UTC
`dart:ffi` uses the [`_memCopy`](https://github.com/dart-lang/sdk/blob/6051eff032cba952f0235c1ec574afa1f76df21c/sdk/lib/_internal/vm/lib/ffi_patch.dart#L248-L288) helper when working with structs. 

We should make sure to 

- [ ] Provide fast recognized implementation for this method (probably bottoming in `MemoryCopyInstr`. 
- [ ] Small constant size copies and unroll the copying loop in place.

**Comment by dcharkes** [comment] 2022-12-19 20:34
Duplicate of:

* https://github.com/dart-lang/sdk/issues/43967

**Closed by dcharkes** 2022-12-19 20:34 UTC
Labels: area-vm, type-performance, library-ffi
