### ISSUE TITLE
[gardening] pkg/dds/test/dap/integration/debug_attach_test is meta-flaking with timeout

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53721] opened 2023-10-10 13:49 UTC
The tests
```
pkg/dds/test/dap/integration/debug_attach_test Timeout (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
```

The test used to be flaky, and now consistently times out.

Previous issue, which complains about flakiness being lost:

* https://github.com/dart-lang/sdk/issues/48530

**Comment by whesse** [comment] 2024-01-22 14:06
This test has been flaky since the day it was added.  We should remove this test, and only add it back if it can be made stable.  It was added in CL https://dart-review.googlesource.com/c/sdk/+/210724

![image](https://github.com/dart-lang/sdk/assets/4905639/da4226a0-8045-4722-9402-dada7e3854df)

@DanTup

**Comment by DanTup** [comment] 2024-01-22 14:36
Sorry, hadn't seen this - taking a look.

For reference, test results can be found here:

https://dart-ci.web.app/#showLatestFailures=false&test=pkg/dds/test/dap/integration/debug_attach_test

An example failure is:

```
00:01 [32m+0[0m[31m -1[0m: debug mode can attach to a simple script using vmServiceUri [1m[31m[E][0m[0m

  Expected: ['Hello!World!args: [one, two]', 'Exited.']
    Actual: ['Exited.']
     Which: at location [0] is 'Exited.' instead of 'Hello!World!args: [one, two]'
```

My guess is that there's a race here because we `print()` something and then the app completes, but because the stdout output when attached is async (it comes via events through the VM Service) the termination can occur before we get the output.

The best solution might just be to add a small delay to the script after the prints, since there's nothing we can do in side the debug adapter to prevent the application terminating if it completes before output made it through the VM Service to a connected client.

**Comment by DanTup** [comment] 2024-01-22 14:37
@bkonyi I think the way we handle this for non-attach is actually be using `--pause-isolates-on-exit`. Is there anything like this we can use an attached client (eg. could we enable pause-on-exit if it wasn't already enabled, and then auto-resume later)?

**Comment by DanTup** [comment] 2024-01-22 14:45
@bkonyi is it possible you can tun the above bot (`unittest-asserts-release-mac-arm64`) on https://dart-review.googlesource.com/c/sdk/+/347660 a few times to see if this seems stable with this change?

**Comment by whesse** [comment] 2024-01-22 14:58
I started all 6 flaking try builders on the CL. Because try builders are built to not report flaking tests, you won't be able to see the logs easily on them. The results can be seen by clicking on the step 40. add fields to result records. Then click on the results.json link, and search the json for the test name.
The logs would be in a logs.json file from a shard, but I don't know which shard.

Example link to a previous try build, so you can see the step and link.
https://ci.chromium.org/ui/p/dart/builders/try/pkg-linux-debug-try/852/overview

**Comment by DanTup** [comment] 2024-01-22 15:08
@whesse thanks!

> From the "current counter", it can be seen that something has made them more consistently have the runtime error recently 

That's probably the fix for https://github.com/dart-lang/sdk/issues/54582. The tests were written to pass against the old behaviour (that's why they failed for me today locally). My change above fixes that as well as tries to fix the race (something I can't reproduce locally, but I think I understand).

I'll check back shortly and review the results on the bots.

**Comment by DanTup** [comment] 2024-01-22 15:34
The `pkg-mac-release-arm64-try` bot finished.. I did:

- Go to https://ci.chromium.org/ui/p/dart/builders/try/pkg-mac-release-arm64-try/509/overview
- Expand step 48 "add fields to result records"
- Click "results.json"

In there, I see the test like this:

```js
{
	"name": "pkg/dds/test/dap/integration/debug_attach_test",
	"configuration": "unittest-asserts-release-mac-arm64",
	"suite": "pkg",
	"test_name": "dds/test/dap/integration/debug_attach_test",
	"time_ms": 13718,
	"result": "Pass",
	"expected": "Pass",
	"matches": true,
	"bot_name": "mac-304-e505",
	"commit_hash": "refs/changes/347660/1",
	"commit_time": 1705929419,
	"build_number": "509",
	"builder_name": "pkg-mac-release-arm64-try",
	"flaky": true,
	"previous_flaky": true,
	"previous_commit_hash": "46853586f17227124efdbc3cf669159c4727eb5d",
	"previous_commit_time": 1705929419,
	"previous_build_number": "11233",
	"previous_result": "RuntimeError",
	"changed": true
}
```

So it seems like it passed this time at least. Once it's approved and landed, I'll keep an eye on https://dart-ci.web.app/#showLatestFailures=false&test=pkg/dds/test/dap/integration/debug_attach_test in the next few days to see whether there's still any flakiness.

**Comment by aam** [comment] 2024-01-22 23:44
failed again on [unittest-asserts-release-mac-arm64](https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/11248/pkg/dds/test/dap/integration/debug_attach_test) 

```
--- Command "vm" (took 04.000261s):
DART_CONFIGURATION=ReleaseARM64 CHROME_PATH="/Volumes/Work/s/w/ir/cache/builder/sdk/third_party/browsers/chrome/Google Chrome.app/Contents/MacOS/Google Chrome" xcodebuild/ReleaseARM64/dart-sdk/bin/dart --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-mac-arm64 --ignore-unrecognized-flags --packages=/Volumes/Work/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /Volumes/Work/s/w/ir/cache/builder/sdk/pkg/dds/test/dap/integration/debug_attach_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: debug mode can attach to a simple script using vmServiceUri[0m

00:00 [32m+0[0m[31m -1[0m: debug mode can attach to a simple script using vmServiceUri [1m[31m[E][0m[0m

  Expected: ['Hello!World!args: [one, two]', 'Exited.']
    Actual: ['Hello!', 'World!', 'args: [one, two]', '', 'Exited.']
     Which: at location [0] is 'Hello!' instead of 'Hello!World!args: [one, two]'
  

  package:matcher/src/expect/expect.dart 149:31             fail
  package:matcher/src/expect/expect.dart 144:3              _expect
  package:matcher/src/expect/expect.dart 56:3               expect
  pkg/dds/test/dap/integration/test_support.dart 53:3       expectLines
  pkg/dds/test/dap/integration/debug_attach_test.dart 58:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9          Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7          Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9           Invoker._waitForOutstandingCallbacks.<fn>
  

00:00 [32m+0[0m[31m -1[0m: debug mode can attach to a simple script using vmServiceInfoFile[0m

00:01 [32m+0[0m[31m -2[0m: debug mode can attach to a simple script using vmServiceInfoFile [1m[31m[E][0m[0m

  Expected: ['Hello!World!args: [one, two]', 'Exited.']
    Actual: ['Hello!', 'World!', 'args: [one, two]', '', 'Exited.']
     Which: at location [0] is 'Hello!' instead of 'Hello!World!args: [one, two]'
  

  package:matcher/src/expect/expect.dart 149:31              fail
  package:matcher/src/expect/expect.dart 144:3               _expect
  package:matcher/src/expect/expect.dart 56:3                expect
  pkg/dds/test/dap/integration/test_support.dart 53:3        expectLines
  pkg/dds/test/dap/integration/debug_attach_test.dart 108:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9           Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7           Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9            Invoker._waitForOutstandingCallbacks.<fn>
  

00:01 [32m+0[0m[31m -2[0m: debug mode removes breakpoints/pause and resumes on detach[0m

00:01 [32m+1[0m[31m -2[0m: [31mSome tests failed.[0m



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-mac-arm64 pkg/dds/test/dap/integration/debug_attach_test
```

**Comment by DanTup** [comment] 2024-01-23 00:15
> ```
>   Expected: ['Hello!World!args: [one, two]', 'Exited.']
>     Actual: ['Hello!', 'World!', 'args: [one, two]', '', 'Exited.']
> ```

This difference is from the fix for https://github.com/dart-lang/sdk/issues/54582. A fix is included in my CL above (https://dart-review.googlesource.com/c/sdk/+/347660) which hasn't landed yet. I think once that lands, it'll fix both the original flake (where there's no output at all) and this difference (when the output does arrive, it now has the extra newlines that were peviously missing).

**Comment by alexmarkov** [comment] 2024-01-23 14:56
Turned from flaky to RuntimeError on `unittest-asserts-release-linux-x64` configuration:

```
--- Command "vm" (took 16.000002s):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/cache/builder/sdk/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --sound-null-safety -Dtest_runner.configuration=unittest-asserts-release-linux-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /b/s/w/ir/cache/builder/sdk/pkg/dds/test/dap/integration/debug_attach_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: debug mode can attach to a simple script using vmServiceUri[0m

00:02 [32m+0[0m[31m -1[0m: debug mode can attach to a simple script using vmServiceUri [1m[31m[E][0m[0m

  Expected: ['Hello!World!args: [one, two]', 'Exited.']
    Actual: ['Hello!', 'World!', 'args: [one, two]', '', 'Exited.']
     Which: at location [0] is 'Hello!' instead of 'Hello!World!args: [one, two]'
  

  package:matcher/src/expect/expect.dart 149:31             fail
  package:matcher/src/expect/expect.dart 144:3              _expect
  package:matcher/src/expect/expect.dart 56:3               expect
  pkg/dds/test/dap/integration/test_support.dart 53:3       expectLines
  pkg/dds/test/dap/integration/debug_attach_test.dart 58:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9          Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7          Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9           Invoker._waitForOutstandingCallbacks.<fn>
  

00:02 [32m+0[0m[31m -1[0m: debug mode can attach to a simple script using vmServiceInfoFile[0m

00:05 [32m+0[0m[31m -2[0m: debug mode can attach to a simple script using vmServiceInfoFile [1m[31m[E][0m[0m

  Expected: ['Hello!World!args: [one, two]', 'Exited.']
    Actual: ['Hello!', 'World!', 'args: [one, two]', '', 'Exited.']
     Which: at location [0] is 'Hello!' instead of 'Hello!World!args: [one, two]'
  

  package:matcher/src/expect/expect.dart 149:31              fail
  package:matcher/src/expect/expect.dart 144:3               _expect
  package:matcher/src/expect/expect.dart 56:3                expect
  pkg/dds/test/dap/integration/test_support.dart 53:3        expectLines
  pkg/dds/test/dap/integration/debug_attach_test.dart 108:7  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9           Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7           Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9            Invoker._waitForOutstandingCallbacks.<fn>
  

00:05 [32m+0[0m[31m -2[0m: debug mode removes breakpoints/pause and resumes on detach[0m

00:07 [32m+1[0m[31m -2[0m: [31mSome tests failed.[0m



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n unittest-asserts-release-linux-x64 pkg/dds/test/dap/integration/debug_attach_test
```

**Comment by DanTup** [comment] 2024-01-23 18:14
My fix above has landed so hopefully this will go green. I'll check on https://dart-ci.web.app/#showLatestFailures=false&test=pkg/dds/test/dap/integration/debug_attach_test tomorrow, but if you notice it still failing in the meantime please let me know.

**Comment by DanTup** [comment] 2024-01-24 11:54
Looks like there's another flaky test in this same file - taking a look.

Windows ([log](https://dart-ci.appspot.com/log/pkg-win-release/unittest-asserts-release-win-x64/27309/pkg/dds/test/dap/integration/debug_attach_test)):

```
00:09 [32m+2[0m[31m -1[0m: debug mode removes breakpoints/pause and resumes on detach [1m[31m[E][0m[0m

  Expected: should emit an event that 'Detached.'
    Actual: <Instance of '_MapStream<OutputEventBody, String>'>
     Which: emitted • Hello!
                    • Detached.
                    x Stream closed.
              which emitted an event that is different.
                    Expected: Detached.
                      Actual: Hello!
                              ^
                     Differ at offset 0
  

  package:matcher/src/expect/expect.dart 149:31  fail
  package:matcher/src/expect/expect.dart 125:9   _expect.<fn>
  dart:async/zone.dart 1407:47                   _rootRunUnary
  dart:async/zone.dart 1308:19                   _CustomZone.runUnary
  ===== asynchronous gap ===========================
  package:test_api/hooks.dart 75:3               OutstandingWork.complete
```

Linux ([log](https://dart-ci.appspot.com/log/pkg-linux-release/unittest-asserts-release-linux-x64/25493/pkg/dds/test/dap/integration/debug_attach_test)): 

```
00:09 [32m+2[0m[31m -1[0m: debug mode removes breakpoints/pause and resumes on detach [1m[31m[E][0m[0m

  Expected: should emit an event that 'Detached.'
    Actual: <Instance of '_MapStream<OutputEventBody, String>'>
     Which: emitted • Hello!
                    • Detached.
                    x Stream closed.
              which emitted an event that is different.
                    Expected: Detached.
                      Actual: Hello!
                              ^
                     Differ at offset 0
  

  package:matcher/src/expect/expect.dart 149:31  fail
  package:matcher/src/expect/expect.dart 125:9   _expect.<fn>
  dart:async/zone.dart 1407:47                   _rootRunUnary
  dart:async/zone.dart 1308:19                   _CustomZone.runUnary
  ===== asynchronous gap ===========================
  package:test_api/hooks.dart 75:3               OutstandingWork.complete
  

00:10 [32m+2[0m[31m -1[0m: [31mSome tests failed.[0m
```

**Closed** 2024-01-24 20:40 UTC
Labels: area-vm, gardening, pkg-dartdev

**Comment by DanTup** [comment] 2024-01-25 10:22
Test changed to passing on https://dart-ci.web.app/#showLatestFailures=false&test=pkg/dds/test/dap/integration/debug_attach_test with the last fix above "[dds/dap] Fix flaky detach test" (728e8f). Hopefully this means it's resolved. I'll check back on it tomorrow, but let me know if anyone sees it flake again.

Thanks!
