### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by NarHakobyan** [dart-lang/sdk#36596] opened 2019-04-12 12:38 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.6707.34`
- `2.2.0`
- `WS-191.6707.34, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1440x900`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, error: Analysis failed: /Users/narek/Desktop/projects/untitled/test/app_test.dart context: exception_20190412_163530_970
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#19     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#20     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#21     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#23     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#24     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#25     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#26     _relink (package:analyzer/src/summary/link.dart:305:57)
#27     link (package:analyzer/src/summary/link.dart:123:3)
#28     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#31     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#32     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#33     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#34     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#35     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#38     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#39     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#40     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#41     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#42     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#48     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#49     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#50     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#51     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#52     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#53     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#54     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/__/8516kt2x2cq1jy8f97fgv3680000gp/T/report.txt.

**Comment by devoncarew** [comment] 2019-04-30 15:10
dupe of https://github.com/dart-lang/sdk/issues/36767

**Closed by devoncarew** 2019-04-30 15:10 UTC
Labels: area-analyzer
