### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by enjoy597** [dart-lang/sdk#37002] opened 2019-05-18 15:44 UTC
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

(please describe what you were doing when this exception occurred)

### Versions

- Flutter SDK 1.5.4-hotfix.2
- Visual Studio Code 1.34.0
- Dart Code 3.0.2

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\flutter\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.0.2
```

### Exception (fatal)

Failed to handle request: {id: 24, method: edit.getAvailableRefactorings, params: {file: D:\My work\flutter\catbox\lib\main.dart, length: 4480, offset: 0}, clientRequestTime: 1558193805943}

```text
RangeError: Value not in range: 4480
#0      _StringBase.substring (dart:core-patch/string_patch.dart:386:7)
#1      StatementAnalyzer._hasTokens (package:analysis_server/src/services/correction/statement_analyzer.dart:226:33)
#2      StatementAnalyzer._checkSelectedNodes (package:analysis_server/src/services/correction/statement_analyzer.dart:212:11)
#3      StatementAnalyzer.visitCompilationUnit (package:analysis_server/src/services/correction/statement_analyzer.dart:91:7)
#4      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2147:49)
#5      StatementAnalyzer.analyze (package:analysis_server/src/services/correction/statement_analyzer.dart:56:24)
#6      ExtractMethodRefactoringImpl._checkSelection (package:analysis_server/src/services/refactoring/extract_method.dart:478:14)
#7      ExtractMethodRefactoringImpl.isAvailable (package:analysis_server/src/services/refactoring/extract_method.dart:401:13)
#8      EditDomainHandler._getAvailableRefactoringsImpl (package:analysis_server/src/edit/edit_domain.dart:782:14)
<asynchronous suspension>
#9      EditDomainHandler._getAvailableRefactorings (package:analysis_server/src/edit/edit_domain.dart:754:5)
#10     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:376:16)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1500:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#19     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#22     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#54     _StreamController._add (dart:async/stream_controller.dart:640:7)
#55     _StreamController.add (dart:async/stream_controller.dart:586:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#57     _rootRunUnary (dart:async/zone.dart:1136:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#62     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#63     _StreamController._add (dart:async/stream_controller.dart:640:7)
#64     _StreamController.add (dart:async/stream_controller.dart:586:5)
#65     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#66     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "D:\\My work\\flutter\\catbox",
        "explicitFileCount": 2,
        "implicitFileCount": 815,
        "workItemQueueLength": 3,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment] 2019-07-08 16:29
Dupe of #36682.

**Closed by DanTup** 2019-07-08 16:29 UTC
Labels: area-analyzer, type-bug
