### ISSUE TITLE
Analyzer: type 'KeywordToken' is not a subtype of type 'List<Annotation>'

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#41640] opened 2020-04-23 19:09 UTC
## Dart analysis issue

I received this error stack when typing in a new typedef into IntelliJ:
`typedef ListVariantValueToString<T> = String Function(T value);`
(which may be unrelated, but that's when it happened). I don't have any other information.

type 'KeywordToken' is not a subtype of type 'List<Annotation>'

## Version information

- Dart SDK 2.9.0-edge.64b8ded48b0d68a795ab41a6205f8889c2351378
- Dart IntelliJ 201.7223.43
- IntelliJ IDEA 2020.1
- Mac OS X 10.15.4

## Details

type 'KeywordToken' is not a subtype of type 'List<Annotation>'

```
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Closure.call (dart:core-patch/function.dart)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## Debug log

```
1587668624768 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache/pkg/sky_engine/lib/ui/semantics.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","lo...
1587668624769 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache/pkg/sky_engine/lib/ui/window.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/...
1587668624770 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.beta/dart-sdk/lib/internal/patch.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file...
1587668624770 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/internal/patch.dart","errors":[{"severity":"INFO","type":"LINT","location":{"fi...
1587668624772 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.stable/dart-sdk/lib/internal/patch.dart","errors":[{"severity":"INFO","type":"LINT","location":{"fi...
1587668624773 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.dev/dart-sdk/lib/internal/patch.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file"...
1587668624773 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.other/dart-sdk/lib/internal/patch.dart","errors":[{"severity":"INFO","type":"LINT","location":{"fil...
1587668624791 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/regexp_helper.dart","errors":[{"severity":"INFO","type...
1587668624805 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/js_array.dart","errors":[{"severity":"INFO","type":"LI...
1587668624815 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/js_number.dart","errors":[{"severity":"INFO","type":"L...
1587668624818 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/annotations.dart","errors":[{"severity":"INFO","type":...
1587668624825 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/string_helper.dart","errors":[{"severity":"INFO","type...
1587668624834 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/js_string.dart","errors":[{"severity":"ERROR","type":"...
1587668624843 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/linked_hash_map.dart","errors":[{"severity":"INFO","ty...
1587668624849 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/constant_map.dart","errors":[{"severity":"INFO","type"...
1587668624855 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/instantiation.dart","errors":[{"severity":"INFO","type...
1587668624877 => {"id":"7025","method":"analysis.updateContent","params":{"files":{"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart":{"type":"add","content":"// Copyright...
1587668624877 => {"id":"7026","method":"completion.getSuggestions","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","offset":8319},"clientRequestTime":1...
1587668624879 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/bin/cache.master/dart-sdk/lib/_internal/js_runtime/lib/js_rti.dart","errors":[{"severity":"ERROR","type":"COM...
1587668624880 <= {"id":"7025","result":{}}
1587668624889 <= {"id":"7026","result":{"id":"1446"}}
1587668624889 <= {"event":"analysis.errors","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","loc...
1587668624890 <= {"event":"completion.existingImports","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","imports":{"elements":{"strings":["dart:core","D...
1587668624892 <= {"event":"completion.results","params":{"id":"1446","replacementOffset":8319,"replacementLength":0,"results":[{"kind":"KEYWORD","relevance":2000,"completion":"library","selectionOffse...
1587668624892 <= {"event":"analysis.highlights","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","regions":[]}}
1587668624892 <= {"event":"analysis.navigation","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","regions":[],"targets":[],"files":[]}}
1587668624892 <= {"event":"analysis.closingLabels","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","labels":[]}}
1587668624892 <= {"event":"analysis.outline","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION...
1587668624892 <= {"event":"analysis.overrides","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","overrides":[]}}
1587668624892 <= {"event":"flutter.outline","params":{"file":"/Users/gspencer/code/flutter/packages/flutter_test/lib/src/widget_tester.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":0,"cod...
```

**Comment by srawlins** [comment] 2020-06-14 18:35
Thanks for reporting this issue! A duplicate of this issue has been filed, which has more discussion. Please follow along there. #41267

**Comment by srawlins** [comment] 2020-06-14 18:35
Duplicate of #41267

**Closed by srawlins** 2020-06-14 18:35 UTC
Labels: area-analyzer
