### ISSUE TITLE
Crash on Flutter CI in fasta when compiling package:http

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#37712] opened 2019-08-01 14:32 UTC
This happened on Flutter's Windows CI bot

Top frames:
```
C:\Windows\Temp\flutter sdk>call dart --enable-asserts dev\bots\test.dart 
Crash when compiling file:///C:/Users/ContainerAdministrator/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_request.dart,
at character offset 3931:
file:///C:/Users/ContainerAdministrator/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_request.dart:116:40: Internal problem: Unsupported operation: 'this.plainNameForRead'.
      var response = await client.send(this);
                                       ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unsupported (package:front_end/src/fasta/problems.dart:72:10)
#2      ThisAccessGenerator._plainNameForRead (package:front_end/src/fasta/kernel/expression_generator.dart:2706:12)
#3      Generator._makeInvalidRead (package:front_end/src/fasta/kernel/expression_generator.dart:312:13)
#4      Generator._makeRead (package:front_end/src/fasta/kernel/expression_generator.dart:352:23)
#5      Generator._makeSimpleRead (package:front_end/src/fasta/kernel/expression_generator.dart:189:35)
#6      Generator.buildSimpleRead (package:front_end/src/fasta/kernel/expression_generator.dart:175:20)
#7      BodyBuilder.toValue (package:front_end/src/fasta/kernel/body_builder.dart:378:19)
#8      BodyBuilder.endArguments (package:front_end/src/fasta/kernel/body_builder.dart:1319:31)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5030:14)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4976:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4957:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4936:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4672:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4243:14)
#15     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4014:21)
#16     Parser.parseAwaitExpression (package:front_end/src/fasta/parser/parser.dart:5749:13)
#17     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4135:14)
#18     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3970:13)
#19     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3942:13)
#20     Parser.parseVariableInitializerOpt (package:front_end/src/fasta/parser/parser.dart:2511:15)
```

Full dump: https://api.cirrus-ci.com/v1/task/5477017162612736/logs/test_all.log

Please let me know if any additional information would be helpful.

**Comment by mraleph** [comment] 2019-08-01 16:29
Duplicate of #37595

**Closed by mraleph** 2019-08-01 16:29 UTC
Labels: area-front-end, crash, customer-flutter

**Comment by mraleph** [comment] 2019-08-01 16:30
Long story short this seems like a bug in the VM (incorrect method resolution of some sort, potentially due to incorrect optimization). We would really like to be able to reproduce this locally.
