### ISSUE TITLE
Parsing ambiguity related to records.

### ISSUE THREAD

**Issue by cgrand** [dart-lang/sdk#52904] opened 2023-07-11 12:46 UTC
* Dart SDK Version (`dart --version`)
3.0.5

This program doesn't compile: 
```dart
void main() {
  final x = 42;
  (x) >= 0; // ok
  (x) > 0; // ko
  (x) >> 0; // ko
}
```

Error:
```
A record type with exactly one positional field requires a trailing comma.
```

It seems to interpret `(x)` (before `>>` or `>`) as some kind of 1-item record type.

(This is not handwritten code but code generated by ClojureDart.)

**Comment by lrhn** [comment] 2023-07-11 14:48
Looks like something that should work. Possibly the parser committed to an interpretation of `(x)` being a type a little too soon.

**Comment by jensjoha** [comment] 2023-07-12 08:47
Duplicate of https://github.com/dart-lang/sdk/issues/52365.
@johnniwinther as I recall we talked about if the fix should be cherry-picked and decided it wasn't necessary. Is this still the thouht?

**Comment by johnniwinther** [comment] 2023-07-12 09:44
The fix is in the current beta so I don't think it is necessary.

@cgrand Are you blocked on this or do you have a work-around?

**Comment by cgrand** [comment] 2023-07-13 05:29
@johnniwinther I have a workaround

**Closed** 2023-07-13 08:50 UTC
Labels: P2, front-end-fasta, area-front-end
