### ISSUE TITLE
Bug in compiler sdk 2.5.0-dev.1.0: Expected to get sdk digest at null

### ISSUE THREAD

**Issue by stephan-gruen** [dart-lang/sdk#37614] opened 2019-07-24 09:38 UTC
Works with dart-sdk 2.5.0-dev.0.0
Works in build mode:
"D:\dart-sdk\dart-sdk 2.5.0-dev.1.0\bin\pub.bat" global run webdev build --output=web:build

But webdev serve fails:

pubspec:
```
dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  
dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.6.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.4
  test: ^1.5.1
  stream_channel: ^2.0.0  
```
```
"D:\dart-sdk\dart-sdk 2.5.0-dev.1.0\bin\pub.bat" global run webdev serve web:53322
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] Cleaning up outputs from previous builds. completed, took 1.4s
[INFO] Building new asset graph completed, took 2.3s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Serving `web` on http://127.0.0.1:53322
[SEVERE]build_web_compilers:ddc on package:meta/dart2js.ddc.module: Error compiling dartdevc module:meta|lib/dart2js.ddc.js
```
```
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler  <-- URL DOES NOT EXIST!
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=D:\dart-sdk\dart-sdk 2.5.0-dev.1.0/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\Stephan\AppData\Local\Temp\scratch_spacefff4af8f-adf2-11e9-920f-f01faf42001c\packages/meta/dart2js.ddc.js --source-map --packages=file:///C:/Users/Stephan/AppData/Local/Temp/kernel_builder_fff4afa6-adf2-11e9-920f-f01faf42001c/.packages --module-name=packages/meta/dart2js --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:meta/dart2js.dart
    dart --version: 2.5.0-dev.1.0 (Tue Jul 9 15:27:01 2019 +0200) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
#4      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
This error then repeats for:
```
[SEVERE]build_web_compilers:ddc on package:logging/logging.ddc.module: Error compiling dartdevc module:logging|lib/logging.ddc.js
[WARNING]build_web_compilers:entrypoint on web/main.dart: Unable to read logging|lib/logging.ddc.js, check your console or the `.dart_tool/build/generated/logging/lib/logging.ddc.js.errors` log file.
[SEVERE]build_web_compilers:ddc on package:meta/meta.ddc.module: Error compiling dartdevc module:meta|lib/meta.ddc.js
[SEVERE]build_web_compilers:ddc on package:collection/src/comparators.ddc.module: Error compiling dartdevc module:collection|lib/src/comparators.ddc.js
[WARNING]build_web_compilers:entrypoint on web/main.dart: Unable to read meta|lib/dart2js.ddc.js, check your console or the `.dart_tool/build/generated/meta/lib/dart2js.ddc.js.errors` log file.
[WARNING]build_web_compilers:entrypoint on web/main.dart: Unable to read meta|lib/meta.ddc.js, check your console or the `.dart_tool/build/generated/meta/lib/meta.ddc.js.errors` log file.
[SEVERE]build_web_compilers:ddc on package:collection/src/utils.ddc.module: Error compiling dartdevc module:collection|lib/src/utils.ddc.js
```

plus a few dozen more...

**Comment by nshahan** [comment] 2019-07-24 18:04
A change has landed that should fix and will be included in the next dev release.

Duplicate of #37490.

**Closed by nshahan** 2019-07-24 18:04 UTC
