### ISSUE TITLE
Specification is not clear about metadata before enums

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24425] opened 2015-09-24 10:44 UTC
The Dart Programming Language Speciﬁcation version 1.9 is not clear about metadata for enums.
Chapter '13 Enums' reads:

> An enumerated type, or enum, is used to represent a ﬁxed number of constant values.
> enumType:
>        metadata enum id ‘{’ id [‘, ’ id]\* [‘, ’] ‘}’
> ;

Metadata is allowed. But chapter '15 Metadata' reads:

> Metadata can appear before a library, part header, class, typedef, type pa-
> rameter, constructor, factory, function, ﬁeld, parameter, or variable declaration
> and before an import, export or part directive.

Enums are not mentioned here, i.e. not allowed for enums.
So it is not clear whether metadata can appear before enum or not.

**Comment by eernstg** [comment] 2018-02-06 16:47
No milestone now: Said correction should be performed (add enums in ch. 15), but this does not block Dart 2.

**Comment by eernstg** [comment] 2018-02-06 18:46
Noted that this had been reported already in https://github.com/dart-lang/sdk/issues/22311. Closing this issue as a duplicate of that one.

**Closed by eernstg** 2018-02-06 18:46 UTC
Labels: Resolution: duplicate, Type: bug, area-specification
