### ISSUE TITLE
Dart Analysis Server don't work well with nest parameter type

### ISSUE THREAD

**Issue by AiHMin** [dart-lang/sdk#34976] opened 2018-10-30 07:02 UTC
Dart SDK Version 2.1.0-dev.5.0.flutter-a2eb050044
Using macOS 10.14

When I was writing a flutter project with dart stream and rxdart by Android Studio 3.2.1
I got a problem with dart analysis server 
Here is the sample code:
if I code list this
``` dart
Observable _list = Observable.empty();
```
every thing is fun.
but when I want to add the parameter type like this
``` dart
Observable<List<Something>> _list = Observable.empty();
```
the dart analysis server is stuck in analysis...... I try to restart server by using Android Studio, but it's not work.
And I tried other class like `Future<T>` , the same thing will happen.

**Comment by AiHMin** [comment] 2018-11-01 00:56
@stereotype441 Yes, I checked and it was consuming large amounts of memory. I noticed that the more type parameters nested, the more memory it may consume.
I also checked #35001. I think we got the same condition.

**Comment by stereotype441** [comment] 2018-11-01 22:44
Ok, thanks.  I'm going to mark as a duplicate then.  Feel free to open if you find out more and realize it's not a duplicate.

Duplicate of #35001

**Closed by stereotype441** 2018-11-01 22:44 UTC
Labels: area-analyzer, needs-info
