### ISSUE TITLE
[CP] Fix numbering of SSA values during inlining

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51223] opened 2023-02-01 19:36 UTC
### Commit(s) to merge

f2304f9ec0bc08191bc0019c82814a5a6c98875a

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/280240

### Issue Description

Compiler crashes when trying to inline a method with a lot of optional parameters with distinct default values into a tiny method. Users reported crashes on Dart code generated by `freezed` packages.

### What is the fix

The compiler is fixed to account for number of constants in parameters exceeding number of SSA values of the caller during inlining.

### Why cherry-pick

Affects users - they cannot build their apps. Reported multiple times: https://github.com/flutter/flutter/issues/119220, https://github.com/flutter/flutter/issues/119354, https://github.com/flutter/flutter/issues/119607.

### Risk

low

### Issue link(s)

https://github.com/flutter/flutter/issues/119220

**Comment by alexmarkov** [comment] 2023-02-01 19:36
@mraleph @a-siva

**Comment by mraleph** [comment] 2023-02-01 19:58
lgtm

**Comment by mit-mit** [comment] 2023-02-01 20:11
lgtm

**Comment by alexmarkov** [comment] 2023-02-03 16:59
Cherry-pick landed on stable branch.

**Comment by ixsans** [comment] 2023-02-06 02:42
In which version can I get this fix? Because I'm still facing the issue in 3.7.1

**Comment by itsjustkevin** [comment] 2023-02-06 04:58
@aam Keeping this open until the issue has landed in a stable release.

**Comment by aam** [comment] 2023-02-06 04:59
> @aam Keeping this open until the issue has landed in a stable release.

@alexmarkov

**Comment by a-siva** [comment] 2023-02-07 18:41
> In which version can I get this fix? Because I'm still facing the issue in 3.7.1

@ixsans this fix should be available in the next hot fix release (Flutter 3.7.2 / Dart 2.19.2) which I believe is slated for tomorrow 2/8.

**Comment by crasowas** [comment] 2023-02-11 10:31
The issue is still not fixed when I upgraded Flutter to 3.7.3 (Dart 2.19.2). What happened?

**Comment by mraleph** [comment] 2023-02-11 10:41
@crasowas that means it is not the same issue. file a separate bug report and provide all the information you can.

**Closed by mraleph** 2023-02-11 10:41 UTC
Labels: area-vm, merge-to-stable, cherry-pick-review, cherry-pick-approved
