### ISSUE TITLE
DartPad did not work and the gitter is not active。

### ISSUE THREAD

**Issue by guogailee** [dart-lang/sdk#29674] opened 2017-05-20 03:54 UTC
![image](https://cloud.githubusercontent.com/assets/12292895/26272737/d9e4fece-3d52-11e7-9a2b-6bab8fde79b8.png)

**Comment by athomas** [comment] 2017-11-11 04:29
Closing, can't reproduce; the code in the screenshot works for me.

**Closed by athomas** 2017-11-11 04:29 UTC
Labels: area-infrastructure
