### ISSUE TITLE
Poor explanation of change to a parameter in the type of a function typed parameter

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#40034] opened 2020-01-09 17:28 UTC
In the collections package, in `lib/src/canonicalized_map.dart` on line 37:

```
CanonicalizedMap(C Function(K? key) canonicalize,
    {bool Function(Object? key)? isValidKey})
    : _canonicalize = canonicalize,
      _isValidKeyFn = isValidKey;
```

The parameter `key` (for the function `canonicalize`) is marked as being nullable. This is a valid migration, but the reason given is bogus. The explanation says "A nullable value is assigned in the default constructor of 'CanonicalizedMap' " and points to the initializer two lines below (`_canonicalize = canonicalize`). That initializer isn't an assignment to the parameter `key`. The real assignment is in the places where `_canonicalize` is invoked.

**Comment by bwilkerson** [comment] 2020-01-09 17:29
@MichaelRFairhurst @srawlins

**Comment by srawlins** [comment] 2020-01-09 17:46
Smells like something I may have written. I can take this one.

**Comment by srawlins** [comment] 2020-01-09 18:35
I am unable to reproduce this. My SDK is at 894d318b33faae371b980a213aeeae706aeaaaaa. I build two SDKs with:

* `./tools/build.py --mode release --arch x64 runtime create_sdk`
* `./tools/build.py --nnbd --mode release --arch x64 runtime create_sdk`

I checkout collection at HEAD (7e9f730511b124d1173ea7b9c609a0c683c8f8e9), and `pub get`.

I migrate the collection package with:

```
/Users/srawlins/code/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/dart \
    ~/code/dart-sdk/sdk/pkg/dartfix/bin/dartfix.dart upgrade sdk \
    --sdk /Users/srawlins/code/dart-sdk/sdk/xcodebuild/ReleaseX64NNBD/dart-sdk
```

In lib/src/canonicalized_map.dart, I do not see a change in the CanonicalizedMap constructors, nor `containsKey`.

**Comment by bwilkerson** [comment] 2020-01-09 19:46
Did you modify `analysis_options.yaml` to enable the non-nullable experiment? It should start with the following:
```
analyzer:
  enable-experiment:
    - non-nullable
```

**Comment by srawlins** [comment] 2020-01-10 05:34
Ah, I see, thank you! I can reproduce.

This is tricky:  this is the first case I've seen of the function parameter contravariance bit. A slightly simpler example is:

```dart
typedef Fn = void Function(int x);
void main(void f(int x)) {
  Fn g = f;
  g(null);
}
```

which is migrated to:

```dart
typedef Fn = void Function(int x);
void main(void f(int? x)) {
  Fn g = f;
  g(null);
}
```

The edge origin for `int? x`'s nullability points to the `f` in `Fn g = f;`. This is correct, I think: `x` is nullable because `f` is assigned to another `Fn`, called `g`, which is called with `null` for `x`.

It would be nice if instead the edge pointed to `null`, but I'm not sure that is the right way for the  nullability engine to work.

Alternatively, there is a second bug in that the typedef is not changed; it should be `typedef Fn = void Function(int? x);`, no? The detail on _that_ change would point to `null`, and the edge origin on `x` in `void f(int? x)` would still point to the `f` in `Fn g = f`. The explanation becomes clearer then; `int x` must be made nullable because the function in which `int x`  is a parameter, is assigned to a `Fn`, whose parameter is nullable.

**Comment by bwilkerson** [comment] 2020-01-10 05:54
Yes, I think the definition of `Fn` should have been updated because of the invocation of `g(null)`. That definitely looks like a bug in the case you introduced. I don't know whether these two cases are related or whether they should be separate issues.

**Comment by srawlins** [comment] 2020-01-29 19:03
I think the preview tool needs more instrumentation information to fix this. Now that typedef parameters can be made nullable, we're one step closer, but we're still stuck on the direction of the reasoning. Let's take two migration examples, `a.dart`:

```dart
class C {
  f(void Function(int) cb1) {
    cb1(null);
  }
  g(void Function(int) cb2) {
    f(cb2);
  }
}
```

is migrated to:

```dart
class C {
  f(void Function(int?) cb1) {
    cb1(null);
  }
  g(void Function(int?) cb2) {
    f(cb2);
  }
}
```

 and `b.dart`:

```dart
class C {
  f(void Function(int) cb1) {}
  g(void Function(int) cb2) {
    f(cb2);
  }
  h() => g(null);
}
```

is migrated to:

```dart
class C {
  f(void Function(int)? cb1) {}
  g(void Function(int)? cb2) {
    f(cb2);
  }
  h() => g(null);
}
```

* In the `a.dart` preview, when a `?` is added to the parameter of `cb2`, the Edge Origin points to `cb2` in `f(cb2)`. We _should_ write the broad explanation "This parameter of `cb2` is made nullable" with a Detail (for the Edge Origin) saying "The function is assigned to a function type with a nullable parameter."
* In the `b.dart` preview, when `?` is added to the type of `cb1`, the Edge Origin again points to `cb2` in `f(cb2)`. We correctly write today a Detail, for that Edge Origin, that a nullable value is passed to `f` as the parameter `cb1`.

The problem is how to distinguish between the two situations. In most cases that the preview tool has considered so far, we're assuming that a parameter is made nullable because an argument is nullable. But with function parameters, the nullability flows the opposite direction: the parameter on the argument's type, a function type, should be made nullable because the parameter on the parameter's type, a function type, is nullable. Right now I don't believe enough information exists in the EdgeOriginInfo. In both cases, the EdgeOriginKind is `EdgeOriginKind.expressionChecks`.

**Comment by stereotype441** [comment] 2020-04-10 18:56
We've replaced the old explanations with a new stacktrace-like functionality, so this bug no longer applies.

**Closed by stereotype441** 2020-04-10 18:56 UTC
Labels: analyzer-nnbd-migration, area-analyzer
