### ISSUE TITLE
NNBD: Default type bound of the generic type parameter is incorrect in runtime: it's dynamic instead of Object?

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40367] opened 2020-01-29 08:39 UTC
Dart VM version: 2.8.0-edge.40f23c735f04433e4fc334fbd674474bd3de0f8b (Tue Jan 28 01:14:48 2020 +0000) on "linux_x64"

NNBD Spec reads:
> The default bound of generic type parameters is treated as Object?.
However, currently this is not so.
Please run the following code:
``` dart
class A<T> {}
main() {
  print(A);
}
```
It prints `A<dynamic>` whereas it should be A<Object?>:
> iarkh@med:~/dart/dart-sdk/sdk/tests/co191/src/LanguageFeatures/nnbd$  dart --enable-experiment=non-nullable test.dart
> A<dynamic>

**Comment by eernstg** [comment] 2020-01-31 16:55
I2b should actually still compute the value `dynamic` for such type arguments, cf. https://github.com/dart-lang/sdk/issues/40368#issuecomment-579909728.

**Comment by crelier** [comment] 2020-02-25 21:50
Closing as working as intended.

**Closed by crelier** 2020-02-25 21:50 UTC
Labels: NNBD, area-vm
