### ISSUE TITLE
Consider growing heap more aggressively in Dart VM to improve performance

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#30604] opened 2017-09-01 17:40 UTC
In certain cases we can improve performance by growing heap (new generation) more aggressively. For example, performance of velocity tracker Flutter microbenchmark running in profile mode improves if new generation grows to 16MB - see https://github.com/dart-lang/sdk/issues/30521.

This is a trade-off between performance and memory usage. So, at the same time, we should be careful about how much memory we're trading for performance.

**Comment by a-siva** [comment] 2023-07-26 21:49
I am going to mark this as a duplicate of https://github.com/dart-lang/sdk/issues/47574 as this is a subset of the overall goal in the other issue.

**Closed by a-siva** 2023-07-26 21:49 UTC
Labels: area-vm, type-performance, type-enhancement
