### ISSUE TITLE
Analysis failing on `static const` initialization of double with an int literal.

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#36013] opened 2019-02-23 17:39 UTC
Unfortunately, this doesn't seem to reproduce with a smaller example, e.g. 

```dart
import 'dart:core';

class DoubleConst {
  static const DoubleConst foo = DoubleConst(d: 0);
  const DoubleConst({this.d});
  final double d;
}
```

analyzes fine.

However, https://github.com/flutter/flutter/commit/7b5a769b3188e648ab22585a88d24ced290cd689#diff-3b7968aa7e1d049c00fc215882d6919c causes analysis issues.  Changing the `0` on lines 334 and 335 in there to `0.0` fixes it.

```
dnfield@mbp:flutter (master)$ flutter analyze --flutter-repo
Analyzing 3 directories...                                              

  error • A value of type 'int' can't be assigned to a parameter of type 'double' • packages/flutter/lib/src/painting/strut_style.dart:1:1 •
         const_constructor_param_type_mismatch

1 issue found. (ran in 55.6s)
```

It reproduces even after deleting the `~/.dartServer` folder.

/cc @garyqian @stereotype441

**Comment by stereotype441** [comment] 2019-02-25 17:50
@dnfield this is another manifestation of a known issue that several folks have run into recently (#33441).  I landed a band-aid fix this morning in 3dfa610694f624913abea2ff5be9909380eb931d that should address your particular use case.  Can you retry using a version of the analyzer that includes this CL?

**Comment by dnfield** [comment] 2019-03-08 00:17
Sorry I just noticed this again - did you still need more input from me on this?  It looks like ther eare some more reproductions now.

**Comment by stereotype441** [comment] 2020-01-29 17:33
The underlying issue (https://github.com/dart-lang/sdk/issues/33441) was fixed in October via https://github.com/dart-lang/sdk/commit/58c70b8e555d334a0676d89e5abcd6a9b08dfecd.  Based on that, and the fact that no further discussion has happened on this bug in nearly a year, I'm presuming this issue has been fixed.

@dnfield, if you are still seeing this issue let us know.

**Comment by stereotype441** [comment] 2020-01-29 17:33
Duplicate of #33441

**Closed by stereotype441** 2020-01-29 17:33 UTC
Labels: P1, area-analyzer, type-bug
