### ISSUE TITLE
Dart analysis NoSuchMethodError: The getter 'imports' was called on null.

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#39585] opened 2019-11-29 19:35 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.7142.36`
- `2.6.1`
- `IC-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-166-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.1, server version 1.27.3, error: Analysis failed: /home/renato/programming/projects/wasm2dart/bin/wasmin.dart context: exception_20191129_203231_129
NoSuchMethodError: The getter 'imports' was called on null.
Receiver: null
Tried calling: imports
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:509:52)
#2      new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:403:5)
#3      new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:619:19)
#4      LibraryBuilder.buildElement (package:analyzer/src/summary2/library_builder.dart:212:13)
#5      Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:170:15)
#6      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:97:5)
#7      Linker.link (package:analyzer/src/summary2/link.dart:83:5)
#8      link (package:analyzer/src/summary2/link.dart:35:10)
#9      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:183:26)
#10     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:235:17)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:233:12)
#13     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1451:23)
#14     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:30)
#15     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#16     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#17     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1067:33)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1926:24)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:575:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:694:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:573:7)
#30     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#32     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#33     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#41     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#42     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#43     main (file:///tmp/tmprglXUK/dart-2.6.1/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#45     main (file:///tmp/tmprglXUK/dart-2.6.1/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

```
Dart analysis server, SDK version 2.6.1, server version 1.27.3, error: Analysis failed: /home/renato/programming/projects/wasm2dart/bin/wasmin.dart context: exception_20191129_203231_129
NoSuchMethodError: The getter 'imports' was called on null.
Receiver: null
Tried calling: imports
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:509:52)
#2      new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:403:5)
#3      new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:619:19)
#4      LibraryBuilder.buildElement (package:analyzer/src/summary2/library_builder.dart:212:13)
#5      Linker._computeLibraryScopes (package:analyzer/src/summary2/link.dart:170:15)
#6      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:97:5)
#7      Linker.link (package:analyzer/src/summary2/link.dart:83:5)
#8      link (package:analyzer/src/summary2/link.dart:35:10)
#9      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:183:26)
#10     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:235:17)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:233:12)
#13     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1451:23)
#14     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:30)
#15     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#16     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#17     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1067:33)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1926:24)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:575:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:694:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:573:7)
#30     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#32     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#33     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#41     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#42     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#43     main (file:///tmp/tmprglXUK/dart-2.6.1/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#45     main (file:///tmp/tmprglXUK/dart-2.6.1/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


1575055945403 <= {"id":"33283","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055947245 => {"id":"33284","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055947246 <= {"id":"33284","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055947465 => {"id":"33285","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055947467 <= {"id":"33285","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055947669 => {"id":"33286","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055947670 <= {"id":"33286","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055948184 => {"id":"33287","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055948185 <= {"id":"33287","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055949523 => {"id":"33288","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055949524 <= {"id":"33288","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055949647 => {"id":"33289","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055949648 <= {"id":"33289","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055949820 => {"id":"33290","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055949822 <= {"id":"33290","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055949951 => {"id":"33291","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055949952 <= {"id":"33291","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055949994 => {"id":"33292","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055949995 <= {"id":"33292","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"}}}
1575055950953 => {"id":"33293","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","offset":243,"length":0,"validateOnly"
1575055950974 <= {"id":"33293","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":233,"length":10,"elementKindName":"function","oldName":"compileWat"},"change"
1575055951031 <= {"event":"analysis.flushResults","params":{"files":["/home/renato/programming/projects/wasm2dart/lib/src/compile.dart~"]}}
1575055951059 <= {"event":"analysis.errors","params":{"file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","errors":[]}}
1575055951060 <= {"event":"analysis.highlights","params":{"file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUIL
1575055951060 <= {"event":"analysis.navigation","params":{"file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"leng
1575055951061 <= {"event":"analysis.closingLabels","params":{"file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","labels":[]}}
1575055951061 <= {"event":"analysis.outline","params":{"file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name"
1575055951061 <= {"event":"analysis.overrides","params":{"file":"/home/renato/programming/projects/wasm2dart/lib/src/compile.dart","overrides":[]}}
1575055951065 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":247,"uri":"package:wasm2dart/src/compile.dart","items":[{"label":"compileWasmin","declaringLibraryUri":"
1575055951144 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /home/renato/programming/projects/wasm2dart/bin/wasmin.dart context: exception_20191129_203231_129","stac
```

**Comment by srawlins** [comment] 2019-11-30 01:00
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/39162; please follow along there.

**Comment by srawlins** [comment] 2019-11-30 01:01
Duplicate of https://github.com/dart-lang/sdk/issues/39162

**Closed by srawlins** 2019-11-30 01:01 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
