### ISSUE TITLE
Dart: can't figure out autocomplete for method

### ISSUE THREAD

**Issue by lookfirst** [dart-lang/sdk#37626] opened 2019-07-25 03:35 UTC
Originally filed here: https://youtrack.jetbrains.com/issue/WEB-40090

Tried to make as simple of a test case as possible. It compiles and works fine, but autocomplete isn't smart enough to figure it out. It should look at <T extends Has> and figure out that Has has foo(). Even doing class WidgetModel<T extends Has> extends Has doesn't work.

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

abstract class Has  {
  Has();

  @protected
  void foo() async {}
}

class WidgetModel<T extends Has> {
  final T _parent;

  WidgetModel({
    @required T parent,
  }) : _parent = parent;

  void bar() {
    _parent.foo();
  }
}
```

![image](https://user-images.githubusercontent.com/85355/61843918-c5b1ce80-aec7-11e9-87b3-1d8ff634f003.png)

![image](https://user-images.githubusercontent.com/85355/61843928-ccd8dc80-aec7-11e9-83d2-e4642e16af61.png)

**Comment by bwilkerson** [comment] 2021-01-23 17:24
I believe that this is a duplicate of https://github.com/dart-lang/sdk/issues/24255.

**Closed by bwilkerson** 2021-01-23 17:24 UTC
Labels: P4, analyzer-completion, area-analyzer
