### ISSUE TITLE
CFE/Analyzer inconsistent behavior of instantiate to bounds

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#32483] opened 2018-03-10 02:57 UTC
Instantiate to bounds works differently if a bound is omitted in DDC depending on the front-end. Analyzer fills in `dynamic`, CFE/Kernel fills in `Object`. Inference behavior is different as well:
```dart
void f<T>() => print(T);
void g<T extends dynamic>() => print(T);
void h<T extends Object>() => print(T);
main() {
  print('Runtime behavior:');
  (f as dynamic)(); // DDC: dynamic, DDK: Object
  (g as dynamic)(); // both: dynamic
  (h as dynamic)(); // both: Object
  print('\nStatic behavior:');
  f(); // both: dynamic
  g(); // both: dynamic
  h(); // DDC: Object, DDK: dynamic
}

```
DDC and DDK both use the same runtime. The reason it behaves differently is the compile time bound is recorded differently. CFE/Kernel fills it in like this:
```
  static method f<T extends core::Object>() → void
    return core::print(test::f::T);
```
Statically, I'm not totally sure what's going on, in particular, why front_end chooses `dynamic` for `T` in `h()`. It appears the inference algorithms are slightly different in how they treat the bound.

I like that DDC/Analyzer's behavior is consistent: both runtime and compile time give the same results. But regardless we need the two implementations to be more consistent.

Thoughts? @leafpetersen @lrhn @eernstg 

My reading of https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md suggests that `dynamic` is the correct answer for omitted bounds, but that informal spec covers generic classes rather than generic methods. (The Dart 1 spec said that omitted bounds were Object, but that had little practical effect, as raw types were instantiated with dynamic, and they're both top types for the purposes of checking whether the type argument is legal w.r.t. the bound.)

**Comment by jmesserly** [comment] 2018-03-10 02:59
Note: bug title is about DDC/K but in reality, this is more of an inconsistency between analyzer and front_end

**Comment by eernstg** [comment] 2018-03-12 10:19
Right, the "default default" (that is, the top type chosen by [instantiate-to-bound](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/instantiate-to-bound.md) as the type argument when there is no bound) is `dynamic` and not `Object`, and when there is an explicit bound it will be used.

For `(f as dynamic)()`, `f` is a generic function which is invoked dynamically with no type arguments, and in that situation the feature spec says 'instantiate to bound ... is used to provide type arguments to dynamic invocations of generic functions when no actual type arguments are passed'. So it should print `dynamic`. So should `(g as dynamic)()`, because `dynamic` is explicitly specified as the bound, and `(h as dynamic)()` should print `Object`. So DDC is right so far.

For `f()`, the missing type argument is provided at compile-time by inference, and it should again be chosen using instantiate-to-bound. Note that instantiate-to-bound relies on the declaration of the given entity (here: the generic function that we're calling), which means that there is no difference between the results obtained dynamically and statically.  Inference might use other sources of information for a given invocation, but when there is no additional information at the call site it relies exclusively on instantiate-to-bound. This means that the dynamic and static case use the same algorithm on the same data, hence producing the same result. DDC is right again.

If the CFE fills in `Object` as the bound for every type variable that has no explicit bound (and it doesn't preserve the information anywhere that this bound was synthetic) then I can't see how various back-ends using CFE could make the necessary distinction.

It would be nice if the CFE could simply fill in missing type variable bounds with `dynamic`, but this would have other effects that we probably do not want (and that we would certainly need to discuss rather than just having them happen by accident). In particular, it would mean that the source code in bodies of generic classes and functions would be subject to more forgiving static checking (`foo<T>(T t) { t.whatever(42); }` would be OK). There might be other unintended effects, but this is already enough for me to conclude that we shouldn't do that.

It looks like the CFE would need to somehow remember that these `Object` bounds are synthetic. Alternatively, if possible, all the work that needs to make this distinction (like computation of instantiate-to-bound) must be done and recorded in the kernel code, such that back-ends can do their job without knowing that some of these `Object` bounds are synthetic.

**Comment by jmesserly** [comment] 2018-03-13 22:35
Edited the subject, as this sounds like a CFE bug.

**Comment by efortuna** [comment] 2018-03-24 01:07
Yes, this is definitely a CFE bug. I just ran into a more obvious failure of the same thing:

    foo<T extends num>(T bar, int p) {
      return bar + p;
    }

    confuse(x) {
      return x;
      return x;
    }

    main() {
      dynamic r = 4;
      r = confuse(r);
      print(foo(r, 5));
      print(foo<double>(2.0, 4));
    }

Then if you dump the produced IR, you get:

```
 pkg/front_end/tool/fasta compile  --dump-ir foo.dartlibrary;
import self as self;
import "dart:core" as core;

static method foo<T extends core::num>(self::foo::T bar, core::int p) → dynamic {
  return bar.+(p);
}
static method confuse(dynamic x) → dynamic {
  return x;
  return x;
}
static method main() → dynamic {
  dynamic r = 4;
  r = self::confuse(r);
  core::print(self::foo<dynamic>(r, 5));
  core::print(self::foo<core::double>(2.0, 4));
}
```

Instead, that first invocation of `self::foo` should read:

    core::print(self::foo<num>(r, 5));

because num is the lower bound in this case. 

adding @kmillikin so he can assign to the proper person to fix this.

**Comment by stefantsov** [comment] 2018-05-01 13:28
Yep, sorry for that.  I'm working on a fix in [CL 53212](https://dart-review.googlesource.com/c/sdk/+/53212).

Also, the following program that is currently rejected by the CFE should be compiled correctly after the fix:

```dart
class A<T extends num> {
  final T t;
  A(this.t);
}

dynamic foo(dynamic x) => x;

main() {
  var a = A(foo(42));
}
```

**Comment by leafpetersen** [comment] 2018-05-02 21:35
> @leafpetersen could you please take a look at these examples?

Yes, both of those examples should be inference failure errors (as the analyzer reports) since `dynamic` is not a valid instantiation.

```
T foo<T extends num>([T x]) => x;

class A<T extends num> {
  final T t;
  A([this.t]);
}

dynamic bar(dynamic x) => x;

void main() {
  dynamic r;
  var a = foo(r); // Failed inference
  var b = new A(bar(42)); // Failed inference
  var c = foo();  // Inferred as foo<num>
  var d = A(); // Inferred as A<num>
}
```

**Comment by stefantsov** [comment] 2018-05-18 14:09
Small status update.  https://github.com/dart-lang/sdk/issues/31581 is resolved, and the programs are now compiled into the form that allows backends to retrieve the default types (that is, the results from instantiate-to-bound) from type parameters and use them in place of the missing type arguments in dynamic invocations of generic functions.

The example script from the original message by @jmesserly is now compiled into the following representation in kernel:

```kernel
library;
import self as self;
import "dart:core" as core;

static method f<T extends core::Object = dynamic>() → void
  return core::print(self::f::T);
static method g<T extends dynamic = dynamic>() → void
  return core::print(self::g::T);
static method h<T extends core::Object = core::Object>() → void
  return core::print(self::h::T);
static method main() → dynamic {
  core::print("Runtime behavior:");
  (self::f as dynamic).call();
  (self::g as dynamic).call();
  (self::h as dynamic).call();
  core::print("\nStatic behavior:");
  self::f<dynamic>();
  self::g<dynamic>();
  self::h<dynamic>();
}
```

In the listing above, `h` receives `core::Object` as the default type of its type parameter.  Backends should pass it as the type argument in the dynamic invocations of `h`.  The VM already does so:

```bash
$ out/ReleaseX64/dart --preview-dart-2 example.dart
Runtime behavior:
dynamic
dynamic
Object

Static behavior:
dynamic
dynamic
dynamic
```

Note that the static invocation still receives `dynamic`.  This is addressed in [CL 55897](https://dart-review.googlesource.com/c/sdk/+/55897).  I hope to get it reviewed and landed in the next week.

**Comment by stefantsov** [comment] 2018-05-22 13:40
Ok, the static part of the fix has just landed: https://github.com/dart-lang/sdk/commit/2c9d8924e316bf821a746993e6d1adc2c25709b4.  With that patch in place, the original example is compiled into the following in strong mode:

```kernel
library;
import self as self;
import "dart:core" as core;

static method f<T extends core::Object = dynamic>() → void
  return core::print(self::f::T);
static method g<T extends dynamic = dynamic>() → void
  return core::print(self::g::T);
static method h<T extends core::Object = core::Object>() → void
  return core::print(self::h::T);
static method main() → dynamic {
  core::print("Runtime behavior:");
  (self::f as dynamic).call();
  (self::g as dynamic).call();
  (self::h as dynamic).call();
  core::print("\nStatic behavior:");
  self::f<dynamic>();
  self::g<dynamic>();
  self::h<core::Object>();
}
```

And here is the output from running the script with the VM in Dart 2 mode:

```bash
$ out/ReleaseX64/dart --preview-dart-2 example.dart
Runtime behavior:
dynamic
dynamic
Object

Static behavior:
dynamic
dynamic
Object
```

The remaining part of the issue is to produce a compile-time error for the code from Emily's comment as suggested by Leaf.

**Comment by stefantsov** [comment] 2018-06-01 09:44
Ok, I guess when you consider the title of this issue and the remaining issues discussed in the thread, you may see that they are slightly different.  The issue in the code from Emily's comment is actually about checking the type arguments against their bounds after type inference is done, and is not about instantiate-to-bound.

So, I'm closing this issue and will be tracking the progress on the remaining in a new one: https://github.com/dart-lang/sdk/issues/33308.

**Closed by stefantsov** 2018-06-01 09:44 UTC
Labels: P2 medium, area-front-end, moved-from-dart2beta4, strong-mode-polish
