### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by stonerich** [dart-lang/sdk#38463] opened 2019-09-18 19:15 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: RangeError: Value not in range: 1
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:677:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/5r/2fmxxp450p90nl_q29nfrn5w0000gn/T/report.txt.

Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: RangeError: Value not in range: 1
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:677:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
1568833873720 => {"id":"46","method":"analysis.updateContent","params":{"files":{"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart":{"type":"add","content":"import 'dart:math';
1568833873720 => {"id":"47","method":"completion.getSuggestions","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","offset":294},"clientRequestTime":156883387
1568833873730 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":730,"uri":"package:vector_math/vector_math.dart","items":[{"label":"cross2A","declaringLibraryUri":"pack
1568833873731 <= {"id":"46","result":{}}
1568833873753 <= {"id":"47","result":{"id":"3"}}
1568833873753 <= {"event":"analysis.errors","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","errors":[{"severity":"INFO","type":"LINT","location":{"file":"/
1568833873755 <= {"event":"completion.existingImports","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","imports":{"elements":{"strings":["dart:math","atan2"
1568833873757 <= {"event":"completion.results","params":{"id":"3","replacementOffset":293,"replacementLength":1,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"hashCode","selectionOffse
1568833873759 <= {"event":"analysis.highlights","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":19},{"typ
1568833873762 <= {"event":"analysis.navigation","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","regions":[{"offset":7,"length":11,"targets":[0]},{"offset":
1568833873762 <= {"event":"analysis.closingLabels","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","labels":[]}}
1568833873763 <= {"event":"analysis.outline","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT
1568833873764 <= {"event":"analysis.overrides","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","overrides":[{"offset":246,"length":8,"superclassMember":{"el
1568833873768 <= {"event":"flutter.outline","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":1635,"codeO
1568833873770 => {"id":"48","method":"analysis.updateContent","params":{"files":{"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart":{"type":"add","content":"import 'dart:math';
1568833873770 => {"id":"49","method":"completion.getSuggestions","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","offset":295},"clientRequestTime":156883387
1568833873770 <= {"id":"48","result":{}}
1568833873787 <= {"id":"49","result":{"id":"4"}}
1568833873787 <= {"event":"analysis.errors","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location
1568833873790 <= {"event":"completion.existingImports","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","imports":{"elements":{"strings":["dart:core","TypeEr
1568833873795 <= {"event":"completion.results","params":{"id":"4","replacementOffset":295,"replacementLength":0,"results":[{"kind":"KEYWORD","relevance":2000,"completion":"library","selectionOffset":7
1568833873795 <= {"event":"analysis.highlights","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","regions":[]}}
1568833873795 <= {"event":"analysis.navigation","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","regions":[],"targets":[],"files":[]}}
1568833873795 <= {"event":"analysis.closingLabels","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","labels":[]}}
1568833873796 <= {"event":"analysis.outline","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT
1568833873796 <= {"event":"analysis.overrides","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","overrides":[]}}
1568833873796 <= {"event":"flutter.outline","params":{"file":"/Users/mikael/AndroidStudioProjects/math_trainer/lib/model/question.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":0,"codeOffs
1568833873802 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"RangeError: Value not in range: 1\n#0      _StringBase.substring (dart:core-patch/string
1568833874139 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"RangeError: Value not in range: 1\n#0      _StringBase.substring (dart:core-patch/string
1568833874139 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"RangeError: Value not in range: 1\n#0      Driver._captureExceptions.errorFunction (pack
```

**Comment by srawlins** [comment] 2019-09-19 15:30
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37276; please follow along there.

**Comment by srawlins** [comment] 2019-09-19 15:31
Duplicate of https://github.com/dart-lang/sdk/issues/37276

**Closed by srawlins** 2019-09-19 15:31 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
