### ISSUE TITLE
The behavior of `if...else...` and `? :` is inconsistent.

### ISSUE THREAD

**Issue by YowFung** [dart-lang/sdk#49921] opened 2022-09-08 02:30 UTC
**Phenomena:**
<img width="985" alt="image" src="https://user-images.githubusercontent.com/26346560/189020585-7dcac65c-6592-45cf-846d-e58327dd4657.png">

**Expected:** 
Both `Case 1` and `Case 2` conform to static check.
**Actual:** 
Only `Case 2` conforms to static check.

**Complete sample code:**
```dart
abstract class IUnit {}
abstract class IGroupableUnit extends IUnit {}
abstract class ILayoutableUnit extends IGroupableUnit {}
abstract class IGroup extends IUnit {}
abstract class IDevice extends IGroupableUnit {}
abstract class IRxDevice extends IDevice {}

abstract class IRepository<E> {}
abstract class IUnitRepository<E extends IUnit> extends IRepository<E> {}
abstract class IGroupableRepository<E extends IGroupableUnit, G extends IGroupRepository> extends IUnitRepository<E> {}
mixin ILayoutableRepository<E extends ILayoutableUnit, G extends IGroupRepository> on IGroupableRepository<E, G> {}
abstract class IGroupRepository<E extends IGroup> extends IUnitRepository<E> {}
abstract class IDeviceRepository<E extends IDevice, G extends IGroupRepository> extends IGroupableRepository<E, G> {}
abstract class IRxDeviceRepository<E extends IRxDevice, G extends IGroupRepository> extends IDeviceRepository<E, G> {}
abstract class IMRxRepository<E extends MRxDevice, G extends IGroupRepository> extends IRxDeviceRepository<E, G> with ILayoutableRepository<E, G> {}

class RxDevice extends IRxDevice {}
class MRxDevice extends IRxDevice implements ILayoutableUnit {}

class OutputGroup extends IGroup {}

class GroupRepository<E extends IGroup> extends IGroupRepository<E> {}
class RxRepository<E extends IRxDevice> extends IRxDeviceRepository<E, GroupRepository<OutputGroup>> {}
class MRxRepository<E extends MRxDevice> extends IMRxRepository<E, GroupRepository<OutputGroup>> {}

void main() {
  RxRepository rxRepository = RxRepository();
  MRxRepository mRxRepository = MRxRepository();
  IRxDevice device = RxDevice();

  // Case 1
  IRxDeviceRepository repository;
  repository = device is MRxDevice ? mRxRepository : rxRepository;
  print(repository.runtimeType);

  // Case 2
  if (device is MRxDevice) {
    repository = mRxRepository;
  } else {
    repository = rxRepository;
  }
  print(repository.runtimeType);
}
```

**Comment by mraleph** [comment] 2022-09-08 08:07
I think that's a consequence of how LUB is defined. /cc @eernstg to confirm. Tentantively closing as working as intended.

Note that these two pieces of code are very different. When you write `x ? a : b` compiler has to find some static type for this expression which both `a` and `b` are assignable to. Currently if inheritance is too complex or involves unrelated generics the compiler will give up and infer `Object`. When you write: `if (x) { v = a; } else { v = b; }` compiler just has to check if `a` and `b` are both assignable to `v` which is a different (simpler) problem.

**Closed by mraleph** 2022-09-08 08:07 UTC

**Comment by eernstg** [comment] 2022-09-19 09:53
(Sorry about the delay, I was on vacation ;-).

@mraleph already explained what's going on, but I could add a couple of words about the background:

The conditional expression needs to have a type (for instance, `var x = b ? e1 : e2;` will use the type of `b ? e1 : e2` as the inferred type of `x`), and that type is computed using the type function [**UP**](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#upper-bounds). **UP** cannot compute a least upper bound of the two operands in all cases; that's not because it's hard, it's because the least upper bound does not exist:

```dart
abstract class I {}
abstract class J {}
class A implements I, J {}
class B implements I, J {}
```

In this example, `A` is a subtype of both `I` and `J`, and so is `B`. The least upper bound `T` of `A` and `B` must be a supertype of both (that is, we must have `A <: T` and `B <: T`), and it must be the least among such supertypes (that is, if `A <: T2` and `B <: T2` then it must be true that `T <: T2`). But `I` and `J` are both the immediate supertypes of both `A` and `B`, and they are not related (so we don't have `I <: J` and we don't have `J <: I`), and hence there is no type which is the least upper bound of `A` and `B`.

So **UP** has to compute something which is _not always_ the least upper bound of its operands (even though we'd want to compute the least upper bound whenever possible). This means that there will be a slack, that is, we will have some situations where the type of `b ? e1 : e2` is not a subtype of some of the shared upper bounds of the type of `e1` and `e2`.

Your example shows such a case: **UP**(`MRxRepository`, `RxRepository`) (where `MRxRepository` means `MRxRepository<MRxDevice>` and `RxRepository` means `RxRepository<IRxDevice>`) is `Object`, even though `IRxDeviceRepository` (meaning `IRxDeviceRepository<IRxDevice, IGroupRepository<IGroup>>`) is a supertype of both.

In this case the slack is particularly large (we jump up to `Object`), because the computation of **UP** uses a Dart 1 algorithm when the operands are distinct interface types (that is, types of the form `C1<...>` and `C2<...>`, where `C1` and `C2` are not the same class).

We considered changing the algorithm when switching to Dart 2.0, but it was considered to be too much of a breaking change. This Dart 1 algorithm is special in that it does not call itself recursively on type arguments (so `UP(C1<T1>, C2<T2>)` will find a common supertype of `C1<T1>` and `C2<T2>` _without_ computing `UP(T1, T2)`). This in turn was done because the algorithm in other languages (in particular, Java) was known to have termination problems in a similar situation.

In any case, you can actually come up with examples where the **UP** function computes a surprisingly suboptimal result (often `Object`), and it is not something for which we have a good, non-breaking solution, even though we've had a rather large number of discussions and proposals about it.

In contrast, the if-statement doesn't ever need to find a shared supertype of `MRxRepository<MRxDevice>` and `RxRepository<IRxDevice>`, it just needs to check that each of them is a subtype of `IRxDeviceRepository<IRxDevice, IGroupRepository<IGroup>>`.

If you do encounter this kind of issue (that is, the type of a `b ? e1 : e2` expression is not a subtype of a given type `S` ever though both the type of `e1` and the type of `e2` is a subtype of `S`), then you can always tell **UP** which way to go by casting one of the branches to the desired type `S`:

```dart
class I {}
class J {}
class A implements I, J {}
class B implements I, J {}

var b = true;

void main() {
  var i = b ? A() : B() as I;
}
```
