### ISSUE TITLE
Analyser fails to recognise function's return type

### ISSUE THREAD

**Issue by AlexandrFarkas** [dart-lang/sdk#46678] opened 2021-07-21 10:23 UTC
```
void doSomething() => {
    setState(() {}),
    widget.callback,
  };
```

Analyser doesn't even bother.

But if I reformat it like this:
```
void doSomething() {
      return {
         setState(() {}),
         widget.callback,
    };
  }
```

It says both:
1. Don't assign to void.dart(void_checks)
2. A value of type 'Set<void>' can't be returned from the method 'doSomething' because it has a return type of 'void' dart(return_of_invalid_type)

P.S.
widget.callback is 'Function()' closure type.
setState(() {}) is void.

**Comment by srawlins** [comment] 2021-07-26 14:02
What  function type do you think the analyzer is failing to recognize? The type of elements in the Set are not relevant; the analyzer is saying you should not assign a Set to void.

**Comment by AlexandrFarkas** [comment] 2021-07-27 07:45
@srawlins Analyzer doesn't say anything at all. It says only when I reformat code to 2nd variant.

**Comment by AlexandrFarkas** [comment] 2021-07-27 07:48
@srawlins  Also, I have null-safety enabled, 2.12 version. Why would analyzer allow me to return Set from function with void return type? Does it behave like sound type system (which it should be)?

**Comment by eernstg** [comment] 2021-07-27 10:28
For a function returning `void`, the treatment of an arrow function differs from the treatment of a block function: The expression which is the body of the former is allowed to have any type whatsoever, but a `return e;` in the latter can incur compile-time errors as specified [here](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#return-statements). The basic rule is that we can only return an expression of type `void` or `dynamic` in a block function whose return type is `void`.

So that's weird, why did we do that? ;-)

First note that there is no soundness issue in returning an arbitrary object in a function whose return type is `void`. The type `void` is a top type (so the value of an expression of type `void` can have any type whatsoever), but the type `void` has an associated property that says "You should not use this object, please discard it!". It's never a soundness problem if the caller makes the choice to get access to that object (like `var mystery = print('Hello') as dynamic;`), but it could break the "business rules" of an application (i.e., some conventions that the type checker doesn't know about), because some developer made the specific choice to tell you "Don't use this object!".

The error in `void f() { return 1; }` arises because it is likely that it is a mistake to return a "non-voidy" expression when the return type indicates that the caller should ignore the returned object: "Why do you return something seemingly meaningful here, it will just be ignored!".

In the arrow variant, `void f() => 1;`, we made the decision to omit that kind of error, because (1) it allows void functions to be concise, and (2) these functions are short (usually 1-2 lines of code), and this means that the developer who is reading or editing this function is actually looking at the return type. In a block function, the return type might well be scrolled out of the current window, because the function is more than a dozen lines of code long, and we're looking at the end of it.

**Comment by eernstg** [comment] 2021-07-27 10:54
I don't see anything here which isn't working as intended, so I'll close the issue.

@AlexandrFarkas, one issue may still exist, but it's a linter issue: The situation is reported twice (as a compile-time error, and also as the lint `void_checks`). I created https://github.com/dart-lang/linter/issues/2813 to notify the linter folks about this.

**Closed by eernstg** 2021-07-27 10:54 UTC
Labels: P3, area-analyzer
