### ISSUE TITLE
@protected elements are not hidden the in tab completion outside their scope

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#49273] opened 2022-06-16 13:38 UTC
```dart
// package:a/a.dart
import 'package:meta/meta.dart';

Class A {
  @protected
  foo();
}

// package:b/b.dart
import 'package:a/a.dart

main() {
  A(). // Would not expect autocompletion to `foo()` here.
}
```

Same thing for `@internal` and `@visibleForTesting`... perhaps others.

**Comment by pq** [comment] 2022-06-17 16:29
@bwilkerson @srawlins

**Comment by leisim** [comment] 2022-06-22 11:08
I think this is a duplicate of #35449 and I would argue that it is much higher than P5

**Comment by srawlins** [comment] 2023-04-19 20:03
Duplicate of https://github.com/dart-lang/sdk/issues/35449

**Closed by srawlins** 2023-04-19 20:03 UTC
Labels: area-analyzer, analyzer-completion, P4
