### ISSUE TITLE
Crash during dart2js compilation on 2.0.0-dev.68.0

### ISSUE THREAD

**Issue by Lisenish** [dart-lang/sdk#33833] opened 2018-07-12 12:33 UTC
* Linux (Ubuntu 17.04)

* the Dart SDK build number (2.0.0-dev.68.0), and

The compiler crashed: Internal Error: Generic function instantiation not implemented for 8 type arguments
#0      CompilerDiagnosticReporter.internalError (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:825:5)
#1      KernelSsaGraphBuilder.visitInstantiation (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:4368:16)
#2      Instantiation.accept (package:kernel/ast.dart:2959:36)
#3      KernelSsaGraphBuilder.visitConditionalExpression.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2616:25)
#4      SsaBranchBuilder.buildBranch (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:91:16)
#5      SsaBranchBuilder._handleDiamondBranch (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:202:9)
#6      SsaBranchBuilder.handleConditional (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/ssa_branch_builder.dart:122:5)
#7      KernelSsaGraphBuilder.visitConditionalExpression (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:2615:14)
#8      ConditionalExpression.accept (package:kernel/ast.dart:3055:36)
#9      KernelSsaGraphBuilder.visitLet (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:3084:15)
#10     Let.accept (package:kernel/ast.dart:3503:36)
#11     KernelSsaGraphBuilder.visitMethodInvocation (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:4396:19)
#12     MethodInvocation.accept (package:kernel/ast.dart:2759:36)
#13     KernelSsaGraphBuilder.visitVariableDeclaration (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:3049:24)
#14     VariableDeclaration.accept (package:kernel/ast.dart:4497:35)
#15     KernelSsaGraphBuilder.visitBlock (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:1404:17)
#16     Block.accept (package:kernel/ast.dart:3791:35)
#17     KernelSsaGraphBuilder.buildFunctionNode (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:1024:23)
#18     KernelSsaGraphBuilder.build.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:203:15)
#19     CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:750:15)
#20     KernelSsaGraphBuilder.build (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/builder_kernel.dart:188:21)
#21     KernelSsaBuilder.build.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:116:22)
#22     CompilerTask.measure (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/common/tasks.dart:63:51)
#23     KernelSsaBuilder.build (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:102:17)
#24     SsaBuilderTask.build (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/ssa.dart:96:21)
#25     SsaFunctionCompiler.compile (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/ssa/ssa.dart:44:29)
#26     JavaScriptBackend.codegen (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/js_backend/backend.dart:700:26)
#27     KernelCodegenWorkItem.run (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:85:21)
#28     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:428:70)
#29     CompilerTask.measureSubtask (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#30     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:428:32)
#31     CompilerTask.measureSubtask (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#32     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:426:28)
#33     CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:750:15)
#34     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:424:18)
#35     EnqueuerStrategy.processWorkItem (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/enqueue.dart:500:6)
#36     CodegenEnqueuer._forEach (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/js_backend/enqueuer.dart:244:20)
#37     CodegenEnqueuer.forEach (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/js_backend/enqueuer.dart:259:5)
#38     Compiler.emptyQueue.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:420:16)
#39     CompilerTask.measureSubtask (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#40     Compiler.emptyQueue (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:419:14)
#41     Compiler.processQueue.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:441:7)
#42     CompilerTask.measureSubtask (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#43     Compiler.processQueue (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:438:14)
#44     Compiler.generateJavaScriptCode (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:359:5)
#45     Compiler.compileLoadedLibraries.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:386:15)
#46     CompilerTask.measureSubtask (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#47     Compiler.compileLoadedLibraries (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:379:16)
#48     Compiler.runInternal (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:278:5)
<asynchronous suspension>
#49     Compiler.run.<anonymous closure>.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:216:38)
#50     new Future.sync (dart:async/future.dart:222:31)
#51     Compiler.run.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:216:20)
#52     CompilerTask.measureSubtask (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/common/tasks.dart:178:35)
#53     Compiler.run (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/compiler.dart:213:41)
#54     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///tmp/tmpbQgdfX/dart-2.0.0-dev.68.0/dart/pkg/compiler/lib/src/apiimpl.dart:148:22)
#55     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:482:5)
#60     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512:7)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

**Comment by sigmundch** [comment] 2018-07-12 17:00
Thanks for filing the bug!

Closing to merge with as a duplicate of #33819

**Closed by sigmundch** 2018-07-12 17:00 UTC
Labels: area-dart2js, closed-duplicate
