### ISSUE TITLE
Changed language version in pubspec.yaml isn't picked up by vscode

### ISSUE THREAD

**Issue by athomas** [dart-lang/sdk#44139] opened 2020-11-10 14:41 UTC
When the language version is changed by adding an SDK constraint, vscode doesn't update it's analysis results to match the language version but instead seems stuck on the old version until reloaded. I'm not sure if this is an analysis server or vscode bug.

To reproduce:
1. Setup vscode to use a `2.12.0` dev release.
2. Open a project with a Dart package without an SDK constraint and add some code that isn't migrated to null safety.
3. Notice that vscode correctly adds errors for the unmigrated code (language version defaults to `2.12`).
4. Add an SDK constraint to the pubspec.yaml: `sdk: '>=2.10.0 <3.0.0'`.
5. pub get (vscode does this automatically).
6. Even though the language version should now be `2.10`, the null-safety errors still show and null-safety syntax is accepted.
7. Restart vscode, and observe how the editor flips to `2.10` mode an no longer accepts null-safety syntax.

**Comment by mit-mit** [comment] 2020-11-10 14:48
Sounds similar to https://github.com/dart-lang/sdk/issues/44131

**Comment by mit-mit** [comment] 2020-11-10 16:22
Closing as a dupe of https://github.com/dart-lang/sdk/issues/44131

**Comment by franklinyow** [comment] 2020-11-12 17:21
close as dup

**Closed by franklinyow** 2020-11-12 17:21 UTC
Labels: area-analyzer
