### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by jeanluc243** [dart-lang/sdk#36937] opened 2019-05-12 00:26 UTC
### What I was doing

(please describe what you were doing when this exception occurred)

### Versions

- Flutter SDK 1.5.4-hotfix.2
- Visual Studio Code 1.33.1
- Dart Code 3.0.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/home/jeanluckabulu/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.0.1
```

### Exception

Failed to handle completion domain request: {id: 7, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1557618572571}

```text
FileSystemException(path=/media/jeanluckabulu/STORAGE/ikalaweb/partener/malix/malix_app/build/app/intermediates/res/merged/release/; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextRootImpl._includedFilesInFolder (package:analyzer/src/dart/analysis/context_root.dart:79:38)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
#5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
#6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
#7      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
#8      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
#9      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
#10     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:145:32)
#11     DeclarationsContext._scheduleContextFiles (package:analyzer/src/services/available_declarations.dart:351:22)
#12     DeclarationsTracker.addContext (package:analyzer/src/services/available_declarations.dart:457:25)
#13     AnalysisServer._addContextsToDeclarationsTracker (package:analysis_server/src/analysis_server.dart:707:29)
#14     AnalysisServer.createDeclarationsTracker (package:analysis_server/src/analysis_server.dart:285:5)
#15     CompletionDomainHandler.setSubscriptions (package:analysis_server/src/domain_completion.dart:480:14)
#16     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:280:16)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:267:12)
#22     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#30     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#32     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#33     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#42     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#43     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#44     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#52     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#53     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#54     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#55     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#56     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#57     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#58     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#59     _rootRunUnary (dart:async/zone.dart:1132:38)
#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#64     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#65     _StreamController._add (dart:async/stream_controller.dart:640:7)
#66     _StreamController.add (dart:async/stream_controller.dart:586:5)
#67     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#68     _rootRunUnary (dart:async/zone.dart:1136:13)
#69     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#70     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#73     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#74     _StreamController._add (dart:async/stream_controller.dart:640:7)
#75     _StreamController.add (dart:async/stream_controller.dart:586:5)
#76     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#77     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#78     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#79     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#80     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#81     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/media/jeanluckabulu/STORAGE/ikalaweb/partener/malix/malix_app",
        "explicitFileCount": 1,
        "implicitFileCount": -1,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment] 2019-09-05 22:28
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/36785; please follow along there.

**Comment by srawlins** [comment] 2019-09-05 22:29
Duplicate of https://github.com/dart-lang/sdk/issues/36785

**Closed by srawlins** 2019-09-05 22:29 UTC
Labels: analyzer-server, area-analyzer, type-bug
