### ISSUE TITLE
Flutter Widget Inspector doesn't work with new kernel const format

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#36640] opened 2019-04-15 21:16 UTC
The flutter widget inspector transform expects to be able to access the original const constructors.  It can't do that with new consts.

Per @mraleph : Flutter 3xHEAD started failing exactly at the enabling commit. [https://ci.chromium.org/p/dart/builders/ci.sandbox/flutter-engine-linux/2068] 

@jacob314 is investigating if there is a way to proceed.

**Comment by askeksa-google** [comment] 2019-05-03 15:24
We discussed this on the front-end team, and here's our proposal for fixing it:

- Add a flag to the front-end `CompilerOptions` which will make the constant evaluator leave constructor invocations unevaluated (as constructor invocations, rather than the `InstanceCreation` nodes they are usually translated into when unevaluated).
- Enable the flag when compiling code that is to be transformed by the Wdiget transformer.
- Instantiate a constant evaluator in the Widget transformer.
- Make the Widget transformer recurse into unevaluated constants to find (and transform) the constructor invocations inside. When it comes back out, it will call its constant evaluator to evaluate the constant. It needs to do so for all constants (not just the unevaluated ones) to do correct canonicalization of all constants.
- Also explicitly evaluate all new constants created by the Widget transformer (if they are not already inside a constant).

@jacob314 what do you think of this plan? It means the front-end run will need to know whether this transformation is happening later, so those two steps can't run independently. Does this fit how the compilation process in the Widget Inspector works already?

**Comment by jacob314** [comment] 2019-05-03 21:29
Can you describe the benefits of this plan relative to running the Widget Inspector transform before any const evaluation?

What do you expect the performance impact of this proposal will be? The kernel transformer tracking widget creation locations needs to be fast as it is run as part of all debugging runs of flutter applications initiated by IDEs.

If I'm understanding it correctly consts like
```
const [1,2,3]
const {'a': 3, 'b': 5}
```
would still be evaluated before the widget transformer
but consts such as
```dart
const Text('foo')
```
and
```dart
const [Text('foo'), Text('bar)]
```
would not be evaluated. Is that correct?

**Comment by askeksa-google** [comment] 2019-05-06 12:19
The overall issue with running the transformer before constant evaluation is that the CFE is, by design, a black-box translation from Dart to Kernel, and running external transformations in the middle of the translation exposes internal implementation details that are not meant to be part of the public API, which constrains the ability of the CFE to change its implementation in the future.

Specifically, in this case:
- The fact that constant evaluation runs as a separate transformation is just an implementation detail. This is not the most efficient way to do it (mostly for cache reasons), and we would like to optimize this going forward.
- Constant evaluation is responsible for some internal desugarings (e.g. for UI-as-code constructs), which means that before constant evaluation, there will be nodes in the tree that are internal to the CFE and not understandable by any external transformations.
- In a separate compilation scenario (i.e. Flutter Web), some component might not refer to the `Widget` class at all, which means it does not show up in the `ClassHierarchy`. As I understand it, this was the issue that was hit during the flag flip just before Easter. It might be possible to work around this somehow, but that will put even more constraints on the internal workings of the CFE.

As for the performance: the constant evaluations themselves will be work that is just shifted from the first constant evaluation, so those on their own should not make much difference.

What could make a difference is that the constants need to be re-canonicalized. The constants produced by the constructor invocations (transformed or not) can never hit constants not containing constructor invocations, but the Widget transformer creates some new constants (representing the positions) that might collide with existing constants. Thus, all constants must be revisited to be considered for canonicalization.

We have plans to make the canonicalization more flexible, for instance to support re-use of the canonicalization cache, which would negate this overhead, canonicalizing every constant just once in any case.

Your examples of evaluated and not evaluated constants are correct. The unevaluated ones will still be wrapped in `ConstantExpression` nodes with `UnevaluatedConstant` children. This makes the points at which to do perform constant evaluation easy to recognize.

**Comment by jacob314** [comment] 2019-05-07 17:07
Ok this seems workable. Let me know when you have it working enough end to end to test the performance. If there are performance issues, another option is to use a simpler scheme for the location ids. For example, I suspect we would get a performance win by switching to integer ids and potentially providing a separate server side API to convert between the integer ids and actual locations instead of storing the complex const Location objects. If need to go that route we will need some lead time as it will require non-trivial changes to Flutter.

**Comment by jacob314** [comment] 2019-05-08 15:11
High level, the existing tests in package:flutter will validate correctness and the time delta running
```
flutter test
vs
flutter test --track-widget-creation
```
will gate whether the performance is good enough to ship. In general the time running with --track-widget-creation should be no more than 20% slower than without the flag and it would be very valuable if we could reduce the slowdown further.

**Comment by jacob314** [comment] 2019-05-08 17:24
To follow up based on offline discussions:
The main blocker to running the transform earlier in the pipline is the ClassHierarchy. The good news is that we want to stop using the ClassHierachy in the Kernel transformer anyway to improve performance.

Prototype CL removing the class hierarchy.
https://dart-review.googlesource.com/c/sdk/+/100408

**Comment by kmillikin** [comment] 2019-05-09 12:47
Another blocker for running the widget inspector transformation before constant evaluation is that unevaluated constants contain Fasta-internal syntax that the Kernel transformation APIs can't handle.  I've marked this as blocked on solving that isssue.

**Comment by askeksa-google** [comment] 2019-05-10 12:54
Support for running the widget transformer before constant evaluation has landed in https://dart-review.googlesource.com/c/sdk/+/101987. It is already enabled for Flutter Web in DDC (and the old calls to the transformer removed).

For Flutter, it is controlled by the new `trackWidgetCreation` named parameter to the `FlutterTarget` constructor. This is off by default and currently not enabled by any callers. Flutter should set this flag to `true` where appropriate and remove existing calls to the transformer.

**Comment by devoncarew** [comment] 2019-05-21 15:52
A CL is out for review here: https://dart-review.googlesource.com/c/sdk/+/102920.

@jacob314 may be OOO now; if so, I believe that @terrylucas will take over that CL. I'll confirm.

**Comment by jacob314** [comment] 2019-05-21 19:13
That CL will fix the issue with a performance improvement instead of a
regression.

**Comment by askeksa-google** [comment] 2019-05-22 08:47
This PR enables the new transformation in Flutter: https://github.com/flutter/engine/pull/8994

**Comment by aadilmaan** [comment] 2019-05-23 17:09
@terrylucas Assign this to you for completing the remaining work.

**Comment by dgrove** [comment] 2019-05-28 15:38
@terrylucas - can you please update?

**Comment by terrylucas** [comment] 2019-05-28 15:44
I committed Jacobs [CL](https://github.com/flutter/engine/pull/8994) and updated

**Comment by dgrove** [comment] 2019-05-28 15:45
Is there anything remaining on this issue, @terrylucas ?

**Comment by terrylucas** [comment] 2019-05-28 15:47
Not that I'm aware of Travis tests passed, Flutter engine works and
DevTools inspector works as well.

**Comment by terrylucas** [comment] 2019-05-28 20:05
Jacob's CLs are committed to Dart SDK and Flutter.

**Comment by askeksa-google** [comment] 2019-06-04 15:16
Reopening since the Flutter change was reverted due to a test failure (most likely an error in the test): https://github.com/flutter/engine/pull/9134

**Comment by dgrove** [comment] 2019-06-05 15:24
@terrylucas any updates on this?

**Comment by terrylucas** [comment] 2019-06-05 16:17
Aske is there anything in the CFE/kernel transformer AST that might be in
the dill file (or something that's not computed until there is a dill file?
As I run the failing test (first time the dill file is deleted) the tests
will fail. After this failure all tests pass. As I debug the tests, when
there's success, the location object is the file name of the widget that
was created.

Vijay mentioned there a dill dump tool - I'm going to look at the dump. If
you think it's interesting to see this dill file I'll attach it too.

**Comment by terrylucas** [comment] 2019-06-06 14:16
====================================
Run #1

Flutter test run w/o --track-widget-creation
cd flutter/packages/flutter
flutter test

inside of widget_inspector_test.dart the WidgetInspectorService's isWidgetCreationTracked() is false therefore this test is not compiled w/ track-widget-creation from the kernel transformer point of view.

====================================
Run #2

flutter test --track-widget-creation

inside of the widget_inspector_test.dart the WidgetInspectorService's isWidgetCreationTracked() is true so this test should have been compiled w/ track-widget-creation

There is a dill file generated testfile.dill.track.dill however the test fails because no creationLocation entry can be found (at the top-level same level as children) the getSelectedWidget JSON payload is:

```
  description: Text,
  type: _DiagnosticableTreeNode,
  style: dense,
  hasChildren: true,
  allowWrap: false,
  objectId: inspector-0,
  valueId: inspector-1,
  widgetRuntimeType: Text,
  children: [
    {description: RichText,
    type: _DiagnosticableTreeNode,
    style: dense,
    allowWrap: false,
    objectId: inspector-2,
    valueId: inspector-3,
    widgetRuntimeType: RichText,
    locationId: 1,
    creationLocation: {
      file: file:///Users/terry/flutter-engine2-git/flutter/packages/flutter/lib/src/widgets/text.dart,
      line: 386,
      column: 21,
      parameterLocations: [
        {file: null, line: 387, column: 7, name: textAlign},
        {file: null, line: 388, column: 7, name: textDirection},
        {file: null, line: 389, column: 7, name: locale},
        {file: null, line: 390, column: 7, name: softWrap},
        {file: null, line: 391, column: 7, name: overflow},
        {file: null, line: 392, column: 7, name: textScaleFactor},
        {file: null, line: 393, column: 7, name: maxLines},
        {file: null, line: 394, column: 7, name: strutStyle},
        {file: null, line: 395, column: 7, name: textWidthBasis},
        {file: null, line: 396, column: 7, name: text}]},
        children: []}
      ]}

```

====================================
Run #3

When the dill file is generated all run with --track-widget-creation works, a dump of the dill file shows that creationLocation field exist so the tests all run successfully e.g.,

      final wid::_Location creationLocation = wid::_getCreationLocation(value);

Notice after the dill is generated there is a creationLocation (at the same level as children prefix with **)

```
description: Text,
type: _DiagnosticableTreeNode,
style: dense,
hasChildren: true,
allowWrap: false,
objectId: inspector-0, 
valueId: inspector-1, 
widgetRuntimeType: Text, 
locationId: 10, 
```
```
** creationLocation: {file: file:///Users/terry/flutter-engine2-git/flutter/packages/flutter/test/widgets/widget_inspector_test.dart,
  line: 803,
  column: 15, 
  parameterLocations: [
    {file: null,
     line: 803, 
     column: 20, 
     name: data}
  ]
},
```
```
children: [
  {description: RichText, 
  type: _DiagnosticableTreeNode,
  style: dense,
  allowWrap: false,
  objectId: inspector-2,
  valueId: inspector-3,
  widgetRuntimeType: RichText,
  locationId: 4,
  creationLocation: {
    file: file:///Users/terry/flutter-engine2-git/flutter/packages/flutter/lib/src/widgets/text.dart,
    line: 386,
    column: 21,
    parameterLocations: [
      {file: null, line: 387, column: 7, name: textAlign},
      {file: null, line: 388, column: 7, name: textDirection},
      {file: null, line: 389, column: 7, name: locale},
      {file: null, line: 390, column: 7, name: softWrap},
      {file: null, line: 391, column: 7, name: overflow},
      {file: null, line: 392, column: 7, name: textScaleFactor},
      {file: null, line: 393, column: 7, name: maxLines},
      {file: null, line: 394, column: 7, name: strutStyle},
      {file: null, line: 395, column: 7, name: textWidthBasis},
      {file: null, line: 396, column: 7, name: text}]}, children: []}
    ]}
```

**Comment by terrylucas** [comment] 2019-06-06 14:17
Aske seems like an issue with the CFE either race condition of some fixup of the in memory data is not the same until after a dill is generated.  The ** creationLocation doesn't exist first time test if run.

**Comment by terrylucas** [comment] 2019-06-06 16:07
Talked to Aske he suggested - ” Dmitry found a bug in the transformer which resulted in an invalid override.  It showed in connection with the new top-level type inference that he is working on landing, but it could have implications for the old one as well. Try patching in this CL (without its dependencies) and see if that changes anything: https://dart-review.googlesource.com/c/sdk/+/105245”.

I try patching Dart and rolling a new Flutter with patched Dart (will bring in Ben on how to do).

**Comment by askeksa-google** [comment] 2019-06-07 09:25
@stefantsov's transformer fix has now landed i the SDK, so it should be sufficient to just use the newest SDK head to test it against the Flutter change.

**Comment by aadilmaan** [comment] 2019-06-07 18:32
I presume Terry will verify this transformer fix.

**Comment by terrylucas** [comment] 2019-06-07 20:18
Tried Dmitry's Dart [PR](https://github.com/dart-lang/sdk/commit/40ef0c6d9f) re-built the flutter engine This didn't fix the problem same results.  Sent mail to Aske on other suggestions or areas where I should look?  I’ll drill into Widget Inspector Transformer in kernel to see if I can locate the problem.

**Comment by terrylucas** [comment] 2019-06-11 22:15
Found the problem, with Jacob's help, [CL](https://dart-review.googlesource.com/c/sdk/+/105661/1)

**Comment by aadilmaan** [comment] 2019-06-11 22:23
We are picking up the current dev release as release candidate to begin align with Flutter. We are out of time for D24. This will have to move to D25.

**Comment by terrylucas** [comment] 2019-06-12 11:20
Fix is checked into tip of Dart.  Rebuilding Flutter engine, applying Jacob's engine change.  If all works will have Ben roll Dart into Flutter.

**Comment by terrylucas** [comment] 2019-07-09 12:53
Flutter transformer [PR](https://github.com/flutter/engine/commit/4abf1d8a4d15302744f4d55dfa0f20b98780cd2f) is checked in to use the new kernel transformer and the Flutter bots remained green.

**Closed by terrylucas** 2019-07-09 12:53 UTC
Labels: area-front-end, customer-flutter, p1-high
