### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by niravrmc28** [dart-lang/sdk#36078] opened 2019-03-01 08:25 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.1.0-dev.9.4`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [F:\FlutterWorkspace\rmc_mobile_app], excluded: [F:\FlutterWorkspace\rmc_mobile_app\.idea, F:\FlutterWorkspace\rmc_mobile_app\.dart_tool, F:\FlutterWorkspace\rmc_mobile_app\.idea, F:\FlutterWorkspace\rmc_mobile_app\.pub, F:\FlutterWorkspace\rmc_mobile_app\build]}, clientRequestTime: 1551428329616}
FileSystemException: Exists failed, path = 'F:\FlutterWorkspace\rmc_mobile_app\build\shared_preferences\generated\res\resValues' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#4      _WindowsDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/windows.dart:163:24)
#5      _WindowsDirectoryWatcher._onEvent.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:157:7)
#6      _rootRun (dart:async/zone.dart:1120:38)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#13     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#14     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#15     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\Admin\AppData\Local\Temp\report.txt.

**Comment by stereotype441** [comment] 2019-03-01 22:54
Duplicate of #34294

**Closed by stereotype441** 2019-03-01 22:54 UTC
Labels: area-analyzer
