### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Could not load dart file /Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#45163] opened 2021-03-02 18:36 UTC
Could not load dart file /Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart

Error: NoSuchMethodError: method not found: 'length' on null

Please fill in the following:

**Name of package being migrated (if public)**: https://github.com/flutter/samples/tree/master/provider_shopper
**What I was doing when this issue occurred**: I was migrating the Flutter app and everything went fine. Then, almost at the end of the migration, I "rerun from sources" and saw this error in the web-based migration tool.
**Is it possible to work around this issue**: Yes. I just closed the error window and continued working, applying the migration.
**Has this issue happened before, and if so, how often**: No
**Dart SDK version**: 2.12.0-259.16.beta
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
TypeError: Cannot read property 'length' of null
    at Object.mH (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:3637:9)
    at Object.BX (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:3459:5)
    at http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:3265:3
    at Gs.a (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:1572:72)
    at Gs.$2 (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:4670:23)
    at WM.$1 (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:4662:30)
    at Ji.bv (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:4937:25)
    at rq.$0 (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:4865:11)
    at Object.HZ (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:1620:39)
    at vs.X2 (http://127.0.0.1:63301/Users/filiph/dev/flutter-samples/provider_shopper/test/login_widget_test.dart?offset=758&line=18&authToken=JBIkyT8C8Yc%3D:4781:3)
```

**Comment by stereotype441** [comment] 2021-03-03 13:51
This is a duplicate of internal bug https://buganizer.corp.google.com/issues/181067935.  For those without access to the internal bug tracker, the problem is that sometimes the migration tool's `loadFile` function gets called before `loadNavigationTree` has completed; as a result, the global variable `navigationTree` hasn't been initialized yet, so `loadFile`'s call to `updatePage` crashes when trying to find the navigation tree entry corresponding to the file path.

I made a fix yesterday (32255a579bdf04efaa26108fa405ca2cdcf433f6).  Note that the commit message for that fix implies that the bug only happens if the user clicks around in the web UI before the navigation tree has finished loading, however after further discussion on the internal bug, it seems that it can also happen after a "rerun from sources" even with no further clicks.  The fix addresses the problem in either case.

To get the fix you'll need to upgrade to 2.13.0-96.0.dev or later.  Note that the fix is small and low risk, so it could conceivably be cherry-picked to stable or beta if needed, however the change involves rebuilding a .js file so the cherry-pick would have to be done by hand.

**Closed by stereotype441** 2021-03-03 13:51 UTC
Labels: area-analyzer, type-bug
