### ISSUE TITLE
unused_element is not emitted for the first unused private constructor

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#50128] opened 2022-10-04 21:29 UTC
Reproducible on DartPad, `Based on Flutter 3.3.3 Dart SDK 2.18.2`.

---

My understanding is `unused_element` triggers from a constructor if:

1. The constructor is private.
2. Within the same library, the constructor is not invoked.

(There may be other conditions, but I'm only evaluating _private_ constructors)

However in practice, that doesn't seem to be so. Observe below:

## 🛑  Single class with a single private constructor

No hint is triggered, but I expect one.

```dart
abstract class Node {
  Node._fromA(Object a);
}
```

## ✅ Single class with multiple private constructors

Hints are triggered as expected.

```dart
abstract class Node {
  // HINT: unused_element
  Node._fromA(Object a);

  // HINT: unused_element
  Node._fromB(Object b);
}
```

## 🛑  Single class with a single private constructor that extends a class with multiple

One hint is triggered as expected (`Node._fromB`), but not the other (`SuperNode._fromA`).

```dart
abstract class Node {
  Node._fromA(Object a);

  // HINT: unused_element
  Node._fromB(Object b);
}

class SuperNode extends Node {
  SuperNode._fromA(super.a) : super._fromA();
}
```

**Comment by bwilkerson** [comment] 2022-10-04 22:00
@srawlins

**Comment by srawlins** [comment] 2022-10-04 22:15
This is intentional, to allow subclass-extension prevention by private constructor.

**Comment by matanlurey** [comment] 2022-10-04 22:21
Makes sense... Should the hint only be elided with a private constructor with no parameters?

```dart
abstract class Node1 {
  // HINT
  Node1._fromA(Object a);
}

abstract class Node2 {
  // OK
  Node2._doNotExtend();
}
```

**Comment by srawlins** [comment] 2022-10-04 22:29
Ooh not a bad idea. The "feature" should be documented as well.

**Comment by matanlurey** [comment] 2022-10-04 22:34
Yay! Let me know how I can help.

**Comment by srawlins** [comment] 2023-04-04 22:29
You opened this same bug in August 🤣 

Duplicate of https://github.com/dart-lang/sdk/issues/49654

**Closed by srawlins** 2023-04-04 22:29 UTC
Labels: area-analyzer, P3, analyzer-hint
