### ISSUE TITLE
AOT snapshots built with --enable_asserts should retain the token stream for assert().

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#34110] opened 2018-08-09 18:09 UTC
Otherwise we get assertion failure error messages like:

```
'foo.dart': Failed assertion: line -1: '<optimized out>': is not true.
```

/cc @rmacnak-google @mraleph

**Comment by a-siva** [comment] 2018-08-14 21:13
How is this going to work in the Dart 2 world, we do not have token streams. Are you suggesting they include the source code? That would explode the size of AOT snapshots.

**Comment by a-siva** [comment] 2018-11-19 07:53
No we do not have any token streams in the 2.0 world, we would have to figure out an alternative scheme.

**Comment by a-siva** [comment] 2024-03-27 21:13
Marking this as a duplicate of https://github.com/dart-lang/sdk/issues/53343

**Comment by a-siva** [comment] 2024-04-10 23:46
Reopening issue as we will use this to track the functionality of ensuring messages from asserts are handled correctly in AOT.

**Closed** 2024-04-12 19:42 UTC
Labels: area-vm, customer-flutter, type-bug
