### ISSUE TITLE
some unused imports not detected when AST_CACHING_POLICY limit reached

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#26096] opened 2016-03-26 01:43 UTC
In a very large project that uses dartanalyzer with --show-package-warnings, after bumping up AST_CACHING_POLICY and recompiling, it increases performance and more "Unused import" hints appear than before.

Reducing the limit causes the hints to disappear again (and the command to run slower).

It may be hard to reproduce with a smaller app. I suggest temporarily reducing AST_CACHING_POLICY to a smaller limit.

**Comment by bwilkerson** [comment] 2016-03-31 17:57
It's quite disturbing if changing the cache limit changes the behavior.

**Comment by scheglov** [comment] 2016-03-31 22:00
I was able to reproduce this by reducing `AST_CACHING_POLICY` to `163`.

At the moment when fill list of imported libraries in `GenerateHintsTask` none of the import directives has element. I suspect that this is because of the way `BuildDirectiveElementsTask` is implemented - it updates the defining unit, but does not produce it as an output. So, I think this should be fixed. I have not tried to do this yet.

**Comment by scheglov** [comment] 2016-04-01 18:53
https://codereview.chromium.org/1854863002

**Comment by scheglov** [comment] 2016-04-01 21:01
https://github.com/dart-lang/sdk/commit/d1104de8db33cdfe0de1e73999ae0331350a51d0

**Closed by scheglov** 2016-04-01 21:01 UTC
Labels: analyzer-stability, area-analyzer, P1 high, Type: bug
