### ISSUE TITLE
unable to install app to android

### ISSUE THREAD

**Issue by hexolabs** [dart-lang/sdk#35357] opened 2018-12-07 10:02 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.1 unknown, screens 1280x800, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/ls/f2f38v7x1k1f__bj0mwc6wgc0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: /Users/venkat/flutterProjects/atrak/lib/widgets/item_navigation_drawer.dart context: exception_20181207_132000_324
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
#2      ConstantVisitor.visitSimpleIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1435:12)
#3      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9679:49)
#4      ConstantVisitor.visitBinaryExpression (package:analyzer/src/dart/constant/evaluation.dart:1142:52)
#5      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1102:49)
#6      ConstantVisitor._valueOf (package:analyzer/src/dart/constant/evaluation.dart:1568:49)
#7      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:464:29)
#8      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:134:27)
#9      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6513:15)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8043:18)

**Comment by stereotype441** [comment] 2018-12-12 17:21
Duplicate of #35241

**Closed by stereotype441** 2018-12-12 17:21 UTC
Labels: area-analyzer
