### ISSUE TITLE
Exhaustive enum switch results in "missing end return" diagnostic

### ISSUE THREAD

**Issue by ChristianKienle** [dart-lang/sdk#41568] opened 2020-04-18 18:36 UTC
- Dart SDK Version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"
- OS: macOS
- Browser: not applicable

This has previously been discussed (#32433) but was closed. My case is slightly different:

```dart
enum X {
  A,
  B,
  C
}

extension HumanReadable on X {
   String get toHumanReadableString {
      switch (this) {
        case X.A: return "A";
        case X.B: return "B";
        case X.C: return "C";
     }
   }
}
```
This results in:

> [dart] This function declares a return type of 'String', but doesn't end with a return statement.

In my case, the function/property is defined by using an extension as opposed to a global function (see 
 example in #32433).

`this` can never be `null`. So why is the warning coming up? Do we need a default case for binary/source code compatibility or is this a bug as #32433 suggests?

**Comment by srawlins** [comment] 2020-04-18 19:58
In your example, the value of the enum may be null, which would fall off the end of the method, without a return statement. Duplicate of #38790.

**Comment by srawlins** [comment] 2020-04-18 20:00
I think `this` can be null. This program compiles and executes.

```dart
void main() {
  X x;
  print(x.toHumanReadableString);
}
```

**Comment by mraleph** [comment] 2020-04-18 20:23
It's an extension  - so dispatch is done based on the static type, rather than based on the receiver type, so `this` can indeed be `null` within extension methods.

**Closed by mraleph** 2020-04-18 20:23 UTC

**Comment by ChristianKienle** [comment] 2020-04-21 14:31
First of all thank you @mraleph and @srawlins - I was not aware about this. Still learning Dart/Flutter. :)

This total explains why the compiler complains about my code. As a developer coming from a different language I would have expected the following code to work in that case:

```dart
extension HumanReadable on X {
   String get toHumanReadableString {
      switch (this) {
        case X.A: return "A";
        case X.B: return "B";
        case X.C: return "C";
        case null: return "invalid - maybe even throw something useful";
     }
   }
}
```
But this does not work because I am getting: 

> :x: Case expressions must have the same types

Or even this:

```dart
extension HumanReadable on X {
   String get toHumanReadableString {
      if(this == null) { return "invalid - maybe even throw something useful"; }
      switch (this) {
        case X.A: return "A";
        case X.B: return "B";
        case X.C: return "C";
     }
   }
}
```

The latter fails with the same warning as described initially.

I think `case null` is a matter of taste or experience as to whether or not you expect this to work. But the latter should be safe in any case - right? `this` can't suddenly change between the null-check (using `if`) and the following lines. Or am I mistaken?

Please don't take my questions or confusion as critiquing or nit-picking. :) I just would love to understand it fully.  So far my experience with dart/flutter has fantastic. Like it a lot.
