### ISSUE TITLE
Captured exception

### ISSUE THREAD

**Issue by MiichaelD** [dart-lang/sdk#36379] opened 2019-03-29 05:43 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, error: Captured exception
Invalid argument(s)
#0      _TypedList._setUint32 (dart:typed_data/runtime/lib/typed_data_patch.dart:2066:77)
#1      _ByteDataView.setUint32 (dart:typed_data/runtime/lib/typed_data_patch.dart:4264:16)
#2      ApiSignature.addInt (package:analyzer/src/summary/api_signature.dart:95:11)
#3      UnlinkedExprBuilder.collectApiSignature (package:analyzer/src/summary/format.dart:22389:19)
#4      UnlinkedExecutableBuilder.collectApiSignature (package:analyzer/src/summary/format.dart:21432:21)
#5      UnlinkedClassBuilder.collectApiSignature (package:analyzer/src/summary/format.dart:19482:12)
#6      UnlinkedUnitBuilder.collectApiSignature (package:analyzer/src/summary/format.dart:25511:12)
#7      _SummarizeAstVisitor._computeApiSignature (package:analyzer/src/summary/summarize_ast.dart:1401:7)
#8      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:478:5)
#9      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#10     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:476:46)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:475:26)
#13     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:231:32)
#14     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#15     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:227:20)
#16     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:300:9)
#17     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1080:22)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:511:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:594:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:509:7)
#30     Driver.start (package:analysis_server/src/server/driver.dart:412:7)
#31     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#32     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#33     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#34     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\micha\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-09-06 15:59
Thanks for reporting this issue! The analyzer team has found a minimal reproduction at https://github.com/dart-lang/sdk/issues/38061; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 15:59
Duplicate of https://github.com/dart-lang/sdk/issues/38061

**Closed by srawlins** 2019-09-06 15:59 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
