### ISSUE TITLE
[NNBD] No error if void is returned from the function which return type is Null

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#44676] opened 2021-01-15 07:29 UTC
Accordint to the [NNBD specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#return-statements)

> At this location about synchronous non-generator functions, the text is changed as follows:
> 
> It is a compile-time error if $s$ is \code{\RETURN{} $e$;},
> $T$ is neither \VOID{} nor \DYNAMIC,
> and $S$ is \VOID.
> Comparing to Dart before null-safety, this means that it is no longer allowed to return a void expression in a regular function if the return type is Null.

But in fact there is no error nor in analyzer nor in CFE
```dart
Null foo() {
  return; // No error
}

void g() {}
Null bar() => g(); // Error. Ok

main() {
  foo();
  bar();
}
```

`Dart SDK version: 2.12.0-223.0.dev (dev) (Wed Jan 13 03:24:39 2021 -0800) on "windows_x64" `

**Comment by eernstg** [comment] 2021-01-15 09:00
`foo` is not an error: https://github.com/dart-lang/language/blob/6df1612f667f7fdd28dd3b66a89e06b75ea98d2a/specification/dartLangSpec.tex#L15632 allows `return;` with return type `Null`.

`bar` is an error, as stated in the [given rule](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#return-statements), but I do get the error message. For example, here's the response from the common front end in dartpad.dev (the analyzer reports the error as well):

```
Error compiling to JavaScript:
main.dart:6:15:
Error: A value of type 'void' can't be returned from a function with return type 'Null'.
Null bar() => g(); // Error. Ok
              ^
Error: Compilation failed.
```

`bar` is not an error if the library is legacy (`// @dart = 2.9`), could that be the reason?

**Comment by sgrekhov** [comment] 2021-01-15 09:39
> foo is not an error: https://github.com/dart-lang/language/blob/6df1612f667f7fdd28dd3b66a89e06b75ea98d2a/specification/dartLangSpec.tex#L15632 allows return; with return type Null.

@eernstg  But [NNBD spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#return-statements) reads

> Comparing to Dart before null-safety, this means that it is no longer allowed to return a void expression in a regular function if the return type is Null.

According to this statement `foo` must be an error. Is this an issue with NNBD spec?

**Comment by eernstg** [comment] 2021-01-15 10:15
No, `foo` is still not an error: This particular sentence .. 

> Comparing to Dart before null-safety, this means that it is no longer allowed to return
> a void expression in a regular function if the return type is Null.

.. is commentary so it's a bit more loose in the terminology than the actual rule, but "to return a void expression" means to have `return e;` where the static type of `e` is `void`, and that doesn't match the situation in `foo`.

The part that doesn't match the actual rule is `\RETURN{} $e$;` and `$S$ is \VOID`: We don't have `\RETURN{} $e$;`, we have `\RETURN;`; also, `$S$` is undefined because there is no `$e$`, so it can't be `\VOID`.

**Comment by sgrekhov** [comment] 2021-01-18 08:40
@eernstg what about the following code?
```dart
void g() {}

dynamic foo() {
  return g();
}

bar() => g();

main() {
  print(foo().runtimeType); // prints Null
  print(bar().runtimeType); // prints Null
}
```
Is it ok to have `Null` ryntime type here in a sound null safety mode?

**Comment by eernstg** [comment] 2021-01-18 09:03
`g` returns the null object, which is fine (the type `void` contains every object, including null).

`foo` is [OK](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#return-statements), we _can_ "return `void` to `dynamic`". So is `bar`, whose return type is implicitly `dynamic`.

At run time, `foo()` as well as `bar()` evaluates to the null object (because that's what we get when execution reaches the end of a function body and completes normally), which is sound (because `Null <: dynamic`), and hence it is allowed with sound null checking. Unsound null checking generally allows everything that sound null checking allows (plus a number of extra things), so they both succeed.

The main point here is that an expression of type `dynamic` is allowed to evaluate to null, no matter which null checking mode we have.

**Comment by devoncarew** [comment] 2021-01-19 18:59
From the above discussion, I'm going to close this issue as working as intended.

**Closed by devoncarew** 2021-01-19 18:59 UTC
