### ISSUE TITLE
Remove the need to repeat names in package imports

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#25773] opened 2016-02-12 17:28 UTC
:disappointed: 

``` dart
import 'package:angular2/angular2.dart';
import 'package:path/path.dart';
import 'package:logging/logging.dart';
import 'package:test/test.dart';
import 'package:mockito/mockito.dart';
```

:smile: :+1: 

``` dart
import 'package:angular2';
import 'package:path';
import 'package:logging';
import 'package:test';
import 'package:mockito';
```

The convention is `package:PACKAGE_NAME` is a shorthand for `package:PACKAGE_NAME/PACKAGE_NAME.dart`.

The format is unambiguous and should be a non-breaking change as this format is not valid in Dart today. Also, it should be widely useful today with so many packages whose package names match their main library files.

**Comment by matanlurey** [comment] 2016-02-12 17:32
+1

**Comment by zoechi** [comment] 2016-02-12 18:03
https://github.com/sigmundch/DEP-nonuri-imports/blob/master/proposal.md

**Comment by yjbanov** [comment] 2016-02-12 18:18
@zoechi thanks for the very relevant link! I think this proposal gives us 80% of the value for 20% of work that would need to be done to support @sigmundch's DEP.

If we have to continue to support relative imports via strings, might as well use strings for everything for consistency sake. I have written many a migration tool, and to write regex against a consistent syntax is a hell of a lot easier :)

**Comment by zoechi** [comment] 2016-02-12 21:06
I have no doubt something like that will land in not too far future, but there are just lots of high prio tasks.   
It doesn't bother me as much as in the past anyeay since quick fixes are available for imports.

**Comment by munificent** [comment] 2016-12-13 23:12
Duplicate of the venerable #10018.

**Closed by munificent** 2016-12-13 23:12 UTC
Labels: area-language, Type: enhancement
