### ISSUE TITLE
Analysis server suggests Constructors for abstract classes

### ISSUE THREAD

**Issue by Lootwig** [dart-lang/sdk#47370] opened 2021-10-04 19:43 UTC
`ClassName()` should not be an option for abstract classes, especially not listed _before_ the plain type reference that is usually intended.

Observed in IntelliJ 2021.2.2 with flutter stable 2.5.2.

**Comment by asashour** [comment] 2022-04-23 19:35
I am not able to reproduce using

```dart
abstract class B {
  void boo() {
    B|
  }
}
```

with 

`Dart SDK version: 2.18.0-43.0.dev (dev) (Thu Apr 21 10:35:29 2022 -0700) on "windows_x64"`

**Comment by srawlins** [comment] 2022-04-30 17:49
I can reproduce this with a slightly different repro:
<img width="468" alt="Screen Shot 2022-04-30 at 10 48 20 AM" src="https://user-images.githubusercontent.com/103167/166116659-db3e259a-6c3e-4b7b-803c-13f1de6bd357.png">

**Comment by asashour** [comment] 2022-04-30 17:54
With me, still not able.

I also changed B to long time, to remove the potential long list (which don't have `B()`


![image](https://user-images.githubusercontent.com/2410127/166116798-ae69c88c-9c43-4d18-a934-68f46bee91b2.png)

![image](https://user-images.githubusercontent.com/2410127/166116823-6caedc7a-9a78-428b-90f3-8779c183a135.png)

**Comment by srawlins** [comment] 2022-04-30 18:39
My repro was in VS Code, with Dart ~2.16. The original report was for IntelliJ, but I think we should not close if it is still reproducible under VS Code.

**Comment by asashour** [comment] 2022-04-30 18:44
I think it is fixed, since I tested with the edge Dat version.

**Comment by Lootwig** [comment] 2022-04-30 19:14
<img width="932" alt="Screenshot 2022-04-30 at 21 12 24" src="https://user-images.githubusercontent.com/39827040/166119480-77205933-ed6d-45ac-832d-afc75f999455.png">

just took this in IntelliJ 2021.3.2 in flutter stable 2.10.3

**Comment by asashour** [comment] 2022-04-30 19:18
I am not questioning that it exists with the `stable` branch. The question is more, if this is fixed in `HEAD`, should it be closed, or something else to be done?

**Comment by Lootwig** [comment] 2022-04-30 19:27
is the flutter master channel always set to use the dart-sdk master as well?

**Comment by asashour** [comment] 2022-04-30 19:30
Yes, and sometimes with a delay of some days of `dart-sdk` update.

**Comment by bwilkerson** [comment] 2022-04-30 20:19
> The question is more, if this is fixed in HEAD, should it be closed, or something else to be done?

If we confirm that it's fixed in HEAD, then we close the issue, sometimes with a reminder that it might take a while for the fix to ship.

**Comment by keertip** [comment] 2024-03-08 19:14
Confirmed this is fixed at HEAD, constructors for abstract classes are not suggested in completions.

**Closed by keertip** 2024-03-08 19:14 UTC
Labels: area-analyzer, analyzer-completion, P3, analyzer-server, type-bug, analyzer-completion-correctness
