### ISSUE TITLE
Angular plugin failing

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#38547] opened 2019-09-24 17:10 UTC
I know that this has been reported before, but I can't find the original issue.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6603.28`
- `2.6.0-edge.c0549d28dc6d7f267056c7111c957ff2f4c7b55b`
- `IC-192.6603.28, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.c0549d28dc6d7f267056c7111c957ff2f4c7b55b, server version 1.27.3, error: Bad state: Cannot stop a plugin that is not running.
#0      PluginInfo.stop (package:analysis_server/src/plugin/plugin_manager.dart:267:7)
#1      PluginManager.removedContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:572:16)
#2      PluginWatcher.removedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:95:13)
#3      AnalysisDriverScheduler.remove (package:analyzer/src/dart/analysis/driver.dart:1852:22)
#4      AnalysisDriver.dispose (package:analyzer/src/dart/analysis/driver.dart:512:16)
#5      ServerContextManagerCallbacks.removeContext (package:analysis_server/src/analysis_server.dart:979:12)
#6      ContextManagerImpl._destroyContext (package:analysis_server/src/context_manager.dart:1256:15)
#7      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:737:9)
#8      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:510:22)
#9      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#10     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:319:16)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1500:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#19     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#22     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#31     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#32     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#33     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#54     _StreamController._add (dart:async/stream_controller.dart:640:7)
#55     _StreamController.add (dart:async/stream_controller.dart:586:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#57     _rootRunUnary (dart:async/zone.dart:1136:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59     _CustomZone.runUnaryGuarded (dart:async/z...
```

For additional log information, please append the contents of
file:///private/var/folders/_z/xg4j4cl517zc6rm212d2pjsc003j4q/T/report.txt.

**Comment by MichaelRFairhurst** [comment] 2019-09-24 19:51
The underlying issue seems to be on our side:

```
Could not resolve "package:angular/angular.dart" in /home/mfairhurst/dart/angular/examples/registration_form.
#0      PluginManager.recordPluginFailure (package:analysis_server/src/plugin/plugin_manager.dart:552:7)
#1      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:65:17)
#2      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:2084:22)
#3      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:384:16)
#4      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:187:33)
#5      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:766:48)
#6      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1154:19)
#7      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1216:16)
#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1224:13)
#9      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1224:13)
#10     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:756:9)
#11     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:496:22)
#12     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:389:14)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:323:16)
#14     AnalysisServer.handleRequest.. (package:analysis_server/src/analysis_server.dart:321:45)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     AnalysisServer.handleRequest. (package:analysis_server/src/analysis_server.dart:317:50)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
```

The plugin should not be stopped from running in all workspaces just because one workspace can't resolve the package

**Comment by MichaelRFairhurst** [comment] 2019-09-24 19:52
This is also specific to the angular package, and other complex nested packages perhaps

**Comment by srawlins** [comment] 2019-11-05 17:32
Duplicate of https://github.com/dart-lang/sdk/issues/36352

**Closed by srawlins** 2019-11-05 17:32 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
