### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by HudsonAfonso** [dart-lang/sdk#39216] opened 2019-11-03 23:17 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.7142.36`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080, 1680x1050, 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#7      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#8      RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#9      ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#10     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6186:20)
#11     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#12     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#13     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#14     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#15     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1164:10)
#16     LinterVisitor.visitReturnStatement (package:analyzer/src/lint/linter_visitor.dart:541:11)
#17     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#19     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#20     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#21     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#22     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#23     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#24     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#25     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#28     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#29     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:450:11)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#33     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#34     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#38     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#39     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#40     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#41     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:353:10)
#42     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:206:11)
#43     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#44     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:201:35)
#45     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#47     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#48     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#49     PerformanceLog.run (package:analyzer/src...
```

For additional log information, please append the contents of
file:///private/var/folders/fv/ybc1939142v07032hw4k8tw00000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-11-08 05:45
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38881; please follow along there.

**Comment by srawlins** [comment] 2019-11-08 05:45
Duplicate of https://github.com/dart-lang/sdk/issues/38881

**Closed by srawlins** 2019-11-08 05:45 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
