### ISSUE TITLE
Analyzer highlights wrong span for "must be initialized"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#43709] opened 2020-10-07 18:50 UTC
![Screen Shot 2020-10-07 at 11 50 17 AM](https://user-images.githubusercontent.com/168174/95374520-496c9680-0893-11eb-88b2-13e03b1d2a80.png)

The field `String message`, I think should be highlighted, not the constructor.

**Comment by bwilkerson** [comment] 2020-10-07 19:52
We actually put a fair bit of thought into this, so I'll start by describing some of those thoughts.

One principle we considered is that _diagnostics should be reported as close to the point at which the corrective change should be applied as possible_. In this case, there are two places where a change could be applied--at the declaration of the field and in the constructor--and both are equally likely given what the analyzer knows about your intent (which is virtually nothing). So, that didn't really help us make a choice between the two locations.

Another principle is that _diagnostics should be reported consistently_. In this context that means that the same problem shouldn't be highlighted in different locations under different conditions unless there is a really compelling reason to do so. Users use the context of the message as much as (maybe more than) the actual wording of the message when understanding what the problem is and how to fix it. Consistency helps users learn responses to diagnostics making them more productive. When we considered the fact that sometimes there are multiple constructors and only one of them is missing the initialization of a field, we concluded that consistently highlighting the constructor(s) when there are constructors, and highlighting the field when there are no constructors, was a good tradeoff.

It's definitely a tradeoff, though. It's possible that we should always highlight the field unless there is at least one constructor that initializes the field. It would be interesting to measure some production code to see how common it is for a field to have an initializer versus how common it is for the constructors to initialize the field. I don't think we had a large enough body of code at the time this decision was first made, but we probably do now.

**Comment by srawlins** [comment] 2021-07-27 16:53
Closing this as per Brian's comment. If someone has more thoughts, feel free to comment, re-open, or open anew.

**Closed by srawlins** 2021-07-27 16:53 UTC
Labels: NNBD, P2, area-analyzer, customer-google3
