### ISSUE TITLE
API doc issue:

### ISSUE THREAD

**Issue by joes0451** [dart-lang/sdk#35486] opened 2018-12-22 22:16 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/sdk

-----

**Comment by joes0451** [comment] 2018-12-22 22:32
Problem with WebSocket handshake Connection: Upgrade
server returns 'HTTP/1.1 200 OK' 

Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
On Windows 7

First, on the command line I run:
C:\Android\Dev\Bicycle>dart --observe --pause_isolates_on_start bicycle.dart

Then through my WebSocket client, tries to connect with ws://127.0.0.1:8181
with the firewall turned off.

     [java] (Full)bui: 'GET / HTTP/1.1
     [java] Connection: Upgrade
     [java] Host: 127.0.0.1:8181
     [java] Sec-WebSocket-Key: o6XOKOYWvunzSK3oVWLUsA==
     [java] Sec-WebSocket-Version: 13
     [java] Upgrade: websocket
     [java]
     [java] '
     [java] WebSocketImpl write() 2
     [java] WebSocketImpl write() 1
     [java] WebSocketImpl decode()
     [java] WebSocketImpl decodeHandshake()
     [java] Draft setParseMode()
     [java] Draft translateHandshake()
     [java] Draft translateHandshakeHttp()
     [java] Draft readStringLine()
     [java] Draft readLine()
     [java] line: 'HTTP/1.1 200 OK'
     [java] Draft translateHandshakeHttpClient()
     [java] line: 'HTTP/1.1 200 OK'

With the same client I can connect to ws://echo.websocket.org:80

     [java] (Full)bui: 'GET / HTTP/1.1
     [java] Connection: Upgrade
     [java] Host: echo.websocket.org
     [java] Sec-WebSocket-Key: 4sqybG3QTjIXWJ78BETqFA==
     [java] Sec-WebSocket-Version: 13
     [java] Upgrade: websocket
     [java]
     [java] '
     [java] WebSocketImpl write() 2
     [java] WebSocketImpl write() 1
     [java] WebSocketImpl decode()
     [java] WebSocketImpl decodeHandshake()
     [java] Draft setParseMode()
     [java] Draft translateHandshake()
     [java] Draft translateHandshakeHttp()
     [java] Draft readStringLine()
     [java] Draft readLine()
     [java] line: 'HTTP/1.1 101 Web Socket Protocol Handshake'
     [java] Draft translateHandshakeHttpClient()
     [java] line: 'HTTP/1.1 101 Web Socket Protocol Handshake'

Thanks

**Comment by a-siva** [comment] 2019-01-02 18:41
I presume the issue is referring to documentation in
https://dart-lang.github.io/observatory/get-started.html

We should update this page, references to Dartium should also be removed.
We also have a document
https://github.com/dart-lang/sdk/blob/master/runtime/observatory/HACKING.md
which recommends using Dartium to develop observatory, this should also be updated.

**Comment by joes0451** [comment] 2019-01-02 20:53
I did not want to talk to the Observatory,  I wanted to try to connect
to the Dart VM service directly.  I finally was able to, using a
WebSocket client, send a request and finally got a rely
from the VM service, so I think my issue was resolved, thanks.

**Comment by bkonyi** [comment] 2019-01-04 21:37
Glad to hear your issue is resolved @joes0451. I'll close this issue for now, but feel free to reopen if there's still something that requires action.

**Closed by bkonyi** 2019-01-04 21:37 UTC
Labels: area-documentation, area-vm
