### ISSUE TITLE
VM: MegamorphicLookup #5: default visitor pattern

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#26221] opened 2016-04-07 21:21 UTC
This issue is split out from https://github.com/dart-lang/sdk/issues/26017

In dart2js there are 11 subclasses of HInstruction visitor class, HBaseVisitor
The visitor has defaults visitXXX methods that call the visit method for the superclass of the argument.

```
class HBaseVisitor {
  visitReturn(HReturn node) => visitControlFlow(node);
  visitControlFlow(HControlFlow node) => visitInstruction(node);
  visitInstruction(HInstruction instruction) {}
}

class SsaInstructionSimplifier extends HBaseVisitor {
  visitGraph(HGraph graph) {
    ....  instruction.accept(this);
  }
  
  HInstruction visitInstruction(HInstruction node) { 
    return node;
  }
  // Visitor is mostly concerned with constant-folding expressions.
  // Does not override visitReturn, visitControlFlow
}

class HReturn extends HControlFlow {
  accept(visitor) => visitor.visitReturn(this);
}
```

`instruction.accept(this)` and `visitor.visitReturn(this)` are megamorphic. This is expected.

The target for on HReturn is HBaseVisitor.visitReturn, which in turn has a megamorphic call up the chain. This is an additional two MegamorphicLookup calls.
I can improve this manually by copying the default behaviour into each visitor, but that defeats the point of having the default behaviour.

The compiler could do this for me by cloning the methods from the base class to the instantiated classes.

I think this can happen dynamically: At the time it is determined that HBaseVisitor.visitReturn is to be entered in the MegamorphicCache for receiver=SsaInstructionSimplifier, we can decide if a specialization should be generated to replace HBaseVisitor.visitReturn. A specialization should be generated if (1) the target is 'small' and (2) if the target has an ICData or MegamorphicCache that is used on the receiver.  If these conditions hold, HBaseVisitor.visitReturn would be compiled with this=SsaInstructionSimplifier, making inlining decisions based on dataflow of the receiver rather than ICData.

**Comment by fsc8000** [comment] 2016-07-11 19:50
Duplicate of #26858

**Closed by fsc8000** 2016-07-11 19:50 UTC
Labels: area-vm, Resolution: duplicate, Type: 2016Q1 CY, Type: performance
