### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'null' after compiling code to js

### ISSUE THREAD

**Issue by TrGiLong** [dart-lang/sdk#49336] opened 2022-06-26 10:40 UTC
This tracker is for issues related to **dart2js**.

Version:
```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (5 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

### Problem

Wrong parsing dart code to js code.

There is unknown reason, that the `null.dart` file has been parser as: `var null = Object.create(dart.library);`. The `null` keyword is reversed for js. Renaming this file to something else allow to run compiled application fine.

Error: `Uncaught SyntaxError: Unexpected token 'null' (at header_formatter.dart.lib.js:229:7)`

Compiled code in js:
``` 
  var byte = Object.create(dart.library);
  var expression_meta_data = Object.create(dart.library);
  var bool_value_builder_widget = Object.create(dart.library);
  var bool = Object.create(dart.library);
  var list_value_actions = Object.create(dart.library);
  var list_value_builder_widget = Object.create(dart.library);
  var list = Object.create(dart.library);
  var null_value_builder_widget = Object.create(dart.library);
  var null = Object.create(dart.library); // <---------- Uncaught SyntaxError: Unexpected token 'null'
  var int_value_builder_widget = Object.create(dart.library);
  var int = Object.create(dart.library);
  var conditional_wrapper_value_builder_widget = Object.create(dart.library);
  var conditional_wrapper = Object.create(dart.library);
  var conditional_value_builder_widget = Object.create(dart.library);
  var conditional = Object.create(dart.library);
  var hex_value_builder_widget = Object.create(dart.library);
```

### Step to reproduce

1. Clone `https://github.com/Solana-Playground-Labs/solana-playground-app`
2. Checkout [6120406](https://github.com/Solana-Playground-Labs/solana-playground-app/commit/6120406051315493fc0ff38c5e1b745995f089a8) commit.
3. Run `flutter pub get`
4. Start application in Chrome.
5. (Optional) Rename `lib/scene/editor_v2/solana_playground/expression_builder/value/basic_value/null/null.dart` to something else to make application work.

**Comment by nshahan** [comment] 2022-06-27 16:48
Duplicate of https://github.com/dart-lang/sdk/issues/39595.

**Closed** 2022-06-27 16:48 UTC
Labels: web-dev-compiler, area-web
