### ISSUE TITLE
FileSystemException while moving files

### ISSUE THREAD

**Issue by pedromassango** [dart-lang/sdk#37865] opened 2019-08-14 19:04 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.5728.98`
- `2.4.0`
- `IC-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: FileSystemException(path=C:\IdeaProjects\box\lib\daos\jsonconverters\room_json_converter.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:147:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:128:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:114:25)
#9      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:55:20)
#10     ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#11     DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:52:18)
#12     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:113:27)
<asynchronous suspension>
#13     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1017:41)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1500:12)
#18     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:973:5)
#19     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:851:24)
#20     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:387:16)
#21     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1500:12)
#28     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#29     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#31     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#32     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#41     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#42     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#43     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#50     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#51     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#52     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#53     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#54     _Ut...
```

For additional log information, please append the contents of
file://C:\Users\PEDROM~1\AppData\Local\Temp\report2.txt.

**Comment by srawlins** [comment] 2019-08-30 18:45
Thanks for reporting this issue! It looks like this has been previously reported at https://github.com/dart-lang/sdk/issues/36204; please follow along there.

**Comment by srawlins** [comment] 2019-08-30 18:45
Duplicate of #36204

**Closed by srawlins** 2019-08-30 18:45 UTC
Labels: P2, analyzer-crash-report, area-analyzer, type-bug
