### ISSUE TITLE
Unknown analyzer problem

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51330] opened 2023-02-08 23:26 UTC
This file cannot be analyzed.
```dart
import 'dart:async';
// switch expression precedence
void f14(int n, Future<int> a, Future<int> b, Future<int> c) async {
  await switch (n) {
    1 => a,
    2 => b,
    _ => c
  };
}
void f15(int n, Object a, Object b, Object c) {
  var x = switch (n) {
    1 => a,
    2 => b,
    _ => c
  }.toString();
  print('$x');
}
```
I see this in the IntelliJ log:
```
2023-02-08 15:15:51,897 [96329685]   INFO - #c.j.l.d.a.DartAnalysisServerService - Error from unknown, SDK version = 3.0.0-edge.ec6712542c1eb71fde152f8aba1eeca1e309cc03, server version = 1.33.4, error code = FILE_NOT_ANALYZED: File is not analyzed: .../IdeaProjects/experiments/lib/tmp.dart.
```
cc @scheglov

**Comment by scheglov** [comment] 2023-02-09 18:52
I believe this is duplicate of https://github.com/dart-lang/sdk/issues/51335

**Closed by scheglov** 2023-02-09 18:52 UTC
Labels: P1, area-analyzer, analyzer-crash-report
