### ISSUE TITLE
Process should be able to give its subprocess a tty for its standard output

### ISSUE THREAD

**Issue by kulakowski** [dart-lang/sdk#24716] opened 2015-10-23 20:17 UTC
Without this facility, certain kinds of tools are problematic to write in Dart. Anything that wants to be a better shell script, essentially, falls down, as all the invoked processes behave poorly and format their output differently.

**Comment by sethladd** [comment] 2015-11-06 18:41
cc @nex3

**Comment by nex3** [comment] 2015-11-06 20:20
Signal-handling in nested processes is also impossible to get right in general.

One possible general solution for these issues would be to provide a wrapper for the POSIX `exec()` function (and whatever the Windows equivalent is). This *replaces* the current process with a different one, which ensures that the nested process behaves just like the parent (since it's not actually nested).

**Comment by sgjesse** [comment] 2015-11-09 14:53
It the issue here that the subprocess see a pipe device for its stdout/stderr instead of a terminal device - and therefore might behave differently? Do you have a concrete example of a program where this can be reproduced?

So instead of always using pipes to child processed we should also have an option for allocating a pty and use its master/slave fds for connecting the processes?

**Comment by kulakowski** [comment] 2015-11-09 23:43
@sgjesse Yes that's precisely the issue.

A good example for us is invoking [ninja](https://github.com/martine/ninja/blob/a48434493d69085aa6fc0c002180ace555cad592/src/line_printer.cc#L33), in which link you can see the |isatty| check to configure line pretty printing. On a tty, it overwrites progress lines. Not on a tty, it prints everything on a fresh line.

We previously had a mix of Makefile wrappers and python subprocess.call()s for this which were correctly handling this.

**Comment by sgjesse** [comment] 2015-11-12 22:28
I experimented a bit with this, and providing a pty to a spawned process is not that complicated. However, the pty master file descriptor is not supported by either `epoll` on Linux nor `kqueue` on Mac OS. This means that the current eventhandler cannot be used for waiting on events on the pty master fd. As far as I can a separate eventhandler thread using `select` will have to be added somehow to give access to the pty.

**Comment by natebosch** [comment] 2017-12-11 20:57
Should we consider this a dup of https://github.com/dart-lang/sdk/issues/23165 or vice-versa?

**Comment by zanderso** [comment] 2018-01-24 06:45
As stated, this issue is resolved by https://github.com/dart-lang/sdk/commit/6523896c6fb27a7ead2ced038da4d15164d894d4. Some of the discussion in this issue overlaps with https://github.com/dart-lang/sdk/issues/23165, but the change doesn't address ptys, so I'll close this one, and leave the other open. We probably need a separate issue for the signals/execve use-case.

**Closed by zanderso** 2018-01-24 06:45 UTC
Labels: Type: enhancement, area-library, library-io

**Comment by kevmoo** [comment] 2018-01-24 16:24
Thanks, @zanderso !!

**Comment by kevmoo** [comment] 2018-01-30 21:07
The change to add ProcessStartMode.INHERIT_STDIO is now in 2.0.0-dev.20.0 https://github.com/dart-lang/sdk/commit/6523896c6fb27a7ead2ced038da4d15164d894d4
