### ISSUE TITLE
拒绝访问 (Access denied)

### ISSUE THREAD

**Issue by Lillls** [dart-lang/sdk#35397] opened 2018-12-13 04:07 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\cm\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\AndroidProjects\Daily_Horoscope], excluded: [D:\AndroidProjects\Daily_Horoscope\.idea, D:\AndroidProjects\Daily_Horoscope\.dart_tool, D:\AndroidProjects\Daily_Horoscope\.pub, D:\AndroidProjects\Daily_Horoscope\build, D:\AndroidProjects\Daily_Horoscope\firebase\functions\.dart_tool, D:\AndroidProjects\Daily_Horoscope\firebase\functions\.pub, D:\AndroidProjects\Daily_Horoscope\firebase\functions\build, D:\AndroidProjects\Daily_Horoscope\out]}, clientRequestTime: 1544666619232}
FileSystemException: Exists failed, path = 'D:\AndroidProjects\Daily_Horoscope\build\app\intermediates\transforms\dexBuilder\debug\79\io\flutter\plugins\connectivity' (OS Error: 拒绝访问。
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-12-13 20:51
Duplicate of #34294

**Closed by stereotype441** 2018-12-13 20:51 UTC
Labels: analyzer-server, area-analyzer, type-bug
