### ISSUE TITLE
ASSERT failure in FixCallersTarget

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#26927] opened 2016-07-20 17:52 UTC
FAILED: none-vm-checked debug_x64 standalone/io/http_shutdown_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stderr:
runtime/vm/code_generator.cc: 1576: error: expected: caller_code.is_optimized()

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --enable_type_checks --hot-reload-test-mode --short_socket_write --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /b/build/slave/vm-linux-debug-x64-live-reload-be/build/sdk/tests/standalone/io/http_shutdown_test.dart
Took 0:00:11.158243

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --hot-reload --builder-tag no_ipv6 --checked -t120 standalone/io/http_shutdown_test

**Comment by johnmccutchan** [comment] 2016-07-20 17:52
@fsc8000 Any idea?

**Comment by rmacnak-google** [comment] 2016-07-21 23:28
Failed once outside of hot reload:

https://chromegw.corp.google.com/i/client.dart/builders/vm-linux-debug-x64-be/builds/10390/steps/checked%20vm%20tests/logs/stdio

**Comment by johnmccutchan** [comment] 2016-07-22 13:43
```
FAILED: none-vm-checked debug_x64 service/get_allocation_profile_rpc_test
Expected: Pass 
Actual: Crash
CommandOutput[vm]:

stdout:
** Launching out/DebugX64/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ --enable-vm-service:0 /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/get_allocation_profile_rpc_test.dart
Observatory listening on http://127.0.0.1:52439
** Signaled to run test queries on 52439

Loading VM...
Done loading VM
Running get_allocation_profile_rpc_test.dart [1/3]


stderr:
runtime/vm/code_generator.cc: 1576: error: expected: caller_code.is_optimized()


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --package-root=out/DebugX64/packages/ /mnt/data/b/build/slave/vm-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/get_allocation_profile_rpc_test.dart
Took 0:00:03.236806

Short reproduction command (experimental):
    python tools/test.py --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t120 service/get_allocation_profile_rpc_test
```

**Comment by fsc8000** [comment] 2016-08-15 21:19
Can't reproduce locally, and have not seen this crash on the buildbot either in a while. Closing as not-reproducible for now.

**Comment by rmacnak-google** [comment] 2016-10-11 22:04
With --verify-on-transition, I see this a lot. It disappears again if I also run with --no-background-compilation. This might be because --verify-on-transition slows down the mutator a lot, or because it causes more safepoint operations.

**Closed** 2016-10-14 17:01 UTC
Labels: area-vm, Resolution: cannot reproduce
