### ISSUE TITLE
stack trace from an analysis server crash

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25961] opened 2016-03-09 16:05 UTC
I saw this stack trace in my logs after an analysis server crash (`Dart VM version: 1.15.0-dev.5.0 (Wed Mar  2 04:28:16 2016) on "macos_x64"`):

```
info • analysis-server:   AnalysisException: Cannot create work order to build PROPAGATED_VARIABLE for Parser _parser
Caused by The null object does not have a getter 'source'.

NoSuchMethodError: method not found: 'source'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      PropagateVariableTypeTask.buildInputs (package:analyzer/src/task/dart.dart:3871)
#3      WorkItem.WorkItem (package:analyzer/src/task/driver.dart:611)
#4      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:719)
#5      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:834)
#6      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:398)
#7      WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:800)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#9      WorkOrder.moveNext (package:analyzer/src/task/driver.dart:792)
#10     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:248)
#11     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1132)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#13     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1130)
#14     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#15     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:864)
#16     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#17     _rootRun (dart:async/zone.dart:891)
#18     _CustomZone.run (dart:async/zone.dart:790)
#19     _CustomZone.runGuarded (dart:async/zone.dart:696)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#21     _rootRun (dart:async/zone.dart:895)
#22     _CustomZone.run (dart:async/zone.dart:790)
#23     _CustomZone.runGuarded (dart:async/zone.dart:696)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:726)
#1      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:834)
#2      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:398)
#3      WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:800)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#5      WorkOrder.moveNext (package:analyzer/src/task/driver.dart:792)
#6      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:248)
#7      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1132)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#9      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1130)
#10     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#11     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:864)
#12     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#13     _rootRun (dart:async/zone.dart:891)
#14     _CustomZone.run (dart:async/zone.dart:790)
#15     _CustomZone.runGuarded (dart:async/zone.dart:696)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#17     _rootRun (dart:async/zone.dart:895)
#18     _CustomZone.run (dart:async/zone.dart:790)
#19     _CustomZone.runGuarded (dart:async/zone.dart:696)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment] 2016-03-09 21:33
The error appears to be in this statement:

    LibrarySpecificUnit unit =
        new LibrarySpecificUnit(variable.library.source, variable.source);

specifically `variable.library` appears to be `null`.

**Comment by devoncarew** [comment] 2016-03-10 01:08
one more, don't know if it's related (Dart VM version: 1.15.0-dev.5.1):

```
AnalysisException: Cannot create work order to build INFERRED_STATIC_VARIABLE for dynamic _MASK_8
Caused by The null object does not have a getter 'source'.

NoSuchMethodError: method not found: 'source'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      InferStaticVariableTypeTask.buildInputs (package:analyzer/src/task/dart.dart:3101)
#3      WorkItem.WorkItem (package:analyzer/src/task/driver.dart:611)
#4      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:719)
#5      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:834)
#6      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:398)
```

**Comment by bwilkerson** [comment] 2016-03-10 15:43
Yes, it appears to be exactly the same cause.

**Comment by bwilkerson** [comment] 2016-03-11 18:00
This appears to be a duplicate of #25663.

**Closed by bwilkerson** 2016-03-11 18:00 UTC
Labels: analyzer-server, analyzer-stability, area-analyzer, P1 high, Type: bug
