### ISSUE TITLE
VM flow graph checker runs in quadratic time

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#50421] opened 2022-11-09 22:38 UTC
In tests/co19/co19-runtime.status

```
[ $mode == debug && $runtime == dart_precompiled ]
LibTest/collection/ListBase/ListBase_class_A01_t03: SkipSlow # Very slow compilation in debug mode.
LibTest/collection/ListBase/ListBase_class_A01_t04: SkipSlow # Very slow compilation in debug mode.
LibTest/collection/ListBase/ListBase_class_A01_t05: SkipSlow # Very slow compilation in debug mode.
LibTest/collection/ListBase/ListBase_class_A01_t06: SkipSlow # Very slow compilation in debug mode.
LibTest/collection/ListMixin/ListMixin_class_A01_t03: SkipSlow # Very slow compilation in debug mode.
LibTest/collection/ListMixin/ListMixin_class_A01_t04: SkipSlow # Very slow compilation in debug mode.
LibTest/collection/ListMixin/ListMixin_class_A01_t05: SkipSlow # Very slow compilation in debug mode.
LibTest/collection/ListMixin/ListMixin_class_A01_t06: SkipSlow # Very slow compilation in debug mode.
LibTest/core/List/List_all_t03: SkipSlow # Very slow compilation in debug mode.
LibTest/core/List/List_all_t04: SkipSlow # Very slow compilation in debug mode.
LibTest/core/List/List_all_t05: SkipSlow # Very slow compilation in debug mode.
LibTest/core/List/List_all_t06: SkipSlow # Very slow compilation in debug mode.
```

The flow graph checker is running in quadratic time by using the linear `instruction->GetBlock()` for each instruction.

@alexmarkov

**Comment by alexmarkov** [comment] 2022-11-10 15:53
Probably duplicate to https://github.com/dart-lang/sdk/issues/21708.

**Comment by mkustermann** [comment] 2024-02-28 12:41
Let's mark this as duplicate of https://github.com/dart-lang/sdk/issues/21708

**Closed by mkustermann** 2024-02-28 12:41 UTC
Labels: area-vm, type-performance, triaged
