### ISSUE TITLE
Three analyzer bots timing out on analyzer_status_test

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38548] opened 2019-09-24 18:38 UTC
3x bots started failing on `pkg/analysis_server/test/integration/lsp_server/analyzer_status_test.dart`, at three different points:

* analyzer-linux-release went red on 0e8b94feb876d429d1cd2bd4cf91128c88c052b9, 
* analyzer-mac-release went red on the previous commit, dccbb236a947c7b3d92b2ff5f176e35ffcfd461c
* analyzer-windows-release went red much earlier, at 0b7a78d0a611c3b5e2f9e1dc2e85579d4f6f2562.

These tests are expected to be `Slow`, but when they timeout after 30 seconds with a TimeoutException, that counts as a `RuntimeError`.

Both dccbb236a947c7b3d92b2ff5f176e35ffcfd461c and 0e8b94feb876d429d1cd2bd4cf91128c88c052b9 sound like they could be performance-related, but neither sound particularly analyzer-related.

The test hasn't been touched since May: https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/test/integration/lsp_server/analyzer_status_test.dart

**Comment by srawlins** [comment] 2019-09-24 18:38
CC @bwilkerson @stereotype441

**Comment by bwilkerson** [comment] 2019-09-24 18:41
The windows bot started failing at https://dart.googlesource.com/sdk/+/0b7a78d0a611c3b5e2f9e1dc2e85579d4f6f2562.

**Comment by bwilkerson** [comment] 2019-09-24 19:59
@stereotype441 Here's the issue we discussed.

I believe the decision is to approve the failures in order to get the bots green again, but that we need to address the test failures soon.

@DanTup Based on our reading of the bot output, it appears that the bots started failing because a couple of the LSP tests went from being flaky to consistently failing (see https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8901420967886168112/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0). Can you take a look at them to see whether there's a way to fix them?

**Comment by DanTup** [comment] 2019-09-30 11:04
Sorry for the delay, I was OOO. These tests do seem quite slow locally (though not slow enough to time out):

```
00:00 +0: AnalyzerStatusTest | test_afterInitialize
00:17 +1: AnalyzerStatusTest | test_afterDocumentEdits
00:31 +2: All tests passed!
```

I'll take a look at what's going on to see where all the time is going. They are firing up instances of the analysis server and doing some analysis, but this still seems quite long for the size of the test code.

**Comment by DanTup** [comment] 2019-09-30 11:26
I had a quick look, and the time all seems to be spent between the process being spawned, and it logging anything in the instrumentation file. At a guess, I'd say it's related to this TODO:

https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/test/integration/lsp_server/integration_tests.dart#L147-L148

Currently we run the server in the integration tests just from source - but the non-LSP integration tests have a `useSnapshot` flag that lets them use a snapshot (and the comment "The integration tests run 3x faster when run from snapshots"). My guess is that startup when running from source is slow.

I'm not actually sure why I didn't reproduce this logic now - it's running the same server file so the same snapshot should just work. Possibly it's because I tend not to build the SDK locally so it was hard to verify it was working. I'll have a go this afternoon and trying to fix this up.

**Comment by DanTup** [comment] 2019-09-30 12:21
Ok, using the snapshot seemed trivial - as it falls back to the SDK you're running if there isn't a locally built one. The only caveat is that if you don't set `useSnapshot=false` when running locally, you'll be running the tests against the last built version (not the source).

The difference in performance is significant:

```
00:00 +0: AnalyzerStatusTest | test_afterInitialize
00:01 +1: AnalyzerStatusTest | test_afterDocumentEdits
00:02 +2: All tests passed!
```

https://dart-review.googlesource.com/c/sdk/+/119330/

**Comment by DanTup** [comment] 2019-09-30 13:50
Landed this change - I don't know if you may need to approve test status changes (assuming the pass). If things still seem broken, please let me know!

**Comment by DanTup** [comment] 2019-09-30 14:54
Actually, I leave this open till someone actually confirms it solves the reported issue 😏

**Comment by DanTup** [comment] 2019-10-02 09:16
@bwilkerson @srawlins can anyone confirm if this fixed the issue? I'm not sure how to check/where to look. Thanks!

**Comment by bwilkerson** [comment] 2019-10-02 15:44
It does appear to be fixed. I confirmed that by
- opening the build waterfall (https://ci.chromium.org/p/dart/g/alt/console),
- clicking on a recent build on the windows bot (https://ci.chromium.org/p/dart/builders/ci.sandbox/analyzer-win-release/7260), and
- clicking on "unapproved passing tests" under "Test Results" (https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8900710064645054496/+/steps/test_results/0/logs/unapproved_passing_tests/0).

The list includes the `analyzer_status_test`.

**Closed by bwilkerson** 2019-10-02 15:44 UTC
Labels: P2, analyzer-lsp, area-analyzer, type-performance

**Comment by DanTup** [comment] 2019-10-02 15:48
Great! Seems like the first place I should've looked in hindsight 🙈 Thanks for the info + confirmation!
