### ISSUE TITLE
Memory Leak when handling WebSocket at server side

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#27414] opened 2016-09-22 03:53 UTC
## Simple test case

```
import "dart:io";
import "dart:async";

void main() {
  HttpServer
  .bind(InternetAddress.ANY_IP_V4, 8081)
  .then((server) {
    server.autoCompress = true;
    server.listen((HttpRequest request) async {
      if (request.uri.path == "/q") {
        await socket(request);
      } else {
        request
        ..response.headers.contentType = ContentType.HTML
        ..response.write('<html><body>Hello, world!'
          '<script type="text/javascript">'
          'var ws = new WebSocket("ws://"+window.location.host+"/q");'
          'ws.onopen = function() {console.log("open");};'
          '</script>'
          '</body></html>');
      }
      request.response.close();
    });
  });
}

Future socket(HttpRequest request) async {
  return WebSocketTransformer.upgrade(request)
  .then(handleWebSocket);
}


void handleWebSocket(WebSocket socket){
  print('handleWebSocket');
  socket.listen(_onSocketData, onDone: _onSocketDone);
}

void _onSocketData(data) {print(data);}
void _onSocketDone() {print('_onSocketDone');}
```
#### Server RES

66080
133060
147224
193972
193932
224692
245348
256536
278660
259632
261072
281472
261316
263444
266912
266896
287424
287484
288996
304852
345812
347388
358788
![screen shot 2016-09-22 at 11 49 33 am](https://cloud.githubusercontent.com/assets/1056469/18736579/f32b4c12-80ba-11e6-94b0-811ff245c87a.png)

At each run, I opened 100 browser tabs and then close them all. Also, before checking memory use, I ran GC first.

**Comment by jimmyshiau** [comment] 2016-09-22 03:54
## Dart Observatory

Uint8List Instances
23
1282
1798

![screen shot 2016-09-22 at 10 58 22 am](https://cloud.githubusercontent.com/assets/1056469/18736427/75e72a06-80b9-11e6-8751-6742fd65de4d.png)
![screen shot 2016-09-22 at 11 07 21 am](https://cloud.githubusercontent.com/assets/1056469/18736428/75e83b76-80b9-11e6-9d9a-906914ce3a45.png)
![screen shot 2016-09-22 at 11 39 15 am](https://cloud.githubusercontent.com/assets/1056469/18736426/75e6f1ee-80b9-11e6-94ff-eb5dc5af5db5.png)

**Comment by johnmccutchan** [comment] 2016-09-22 15:51
@zanderso

**Comment by zanderso** [comment] 2016-09-22 16:03
@jimmyshiau Could you say what version of the VM and what OS you're running on? Thanks!

**Comment by tomyeh** [comment] 2016-09-22 16:21
Dart 1.19.1 and Linux (Jimmy is out of the office)

**Comment by jimmyshiau** [comment] 2016-09-26 03:05
Hi @zanderso 

1.20.0-dev.7.0 is better
```
Dart VM version: 1.20.0-dev.7.0 (Tue Sep 20 14:27:56 2016) on "linux_x64"
```

http://screencast.com/t/RHy2EGpO
http://screencast.com/t/BliLRjpmA

#### RES 
67652
71780
86164
95600
80064
93920
95140
95596
96196
96712
97516
97748
98556
99776
100296
101068
102068
102640
103416
103660
104436
105220
![screen shot 2016-09-26 at 10 57 45 am](https://cloud.githubusercontent.com/assets/1056469/18821458/d9ac72e0-83d8-11e6-820a-d2dccf39e04b.png)


### Dart Observatory

Uint8List Instances
853 > 1859
Stackmap Instances
455 > 1093

![screen shot 2016-09-26 at 10 27 13 am](https://cloud.githubusercontent.com/assets/1056469/18821453/d3421a7c-83d8-11e6-8e65-9d2edccddf45.png)
![screen shot 2016-09-26 at 10 45 34 am](https://cloud.githubusercontent.com/assets/1056469/18821454/d344187c-83d8-11e6-8c8e-8f16e8d68e08.png)

**Comment by tomyeh** [comment] 2016-10-11 10:43
Hi, any update? Can you reproduce it? Or, we mis-interpreted something here?

**Comment by zanderso** [comment] 2016-10-12 06:25
When I tried at top-of-tree a couple of weeks ago, RSS stabilized eventually, but I can take another look. If there is any script you are using to drive the browser, that may help me carry out the exact same steps that you are following.

**Comment by jimmyshiau** [comment] 2016-10-12 06:39
You  can save your page link as a bookmark, then put it in a bookmark folder and make 100 copies

![screen shot 2016-10-12 at 2 38 23 pm](https://cloud.githubusercontent.com/assets/1056469/19299882/8f759720-9089-11e6-8cd6-632aaaa5ba72.png)

right click on the folder and select open all bookmarks
![screen shot 2016-10-12 at 2 37 29 pm](https://cloud.githubusercontent.com/assets/1056469/19299865/7556120c-9089-11e6-84d0-5b07df968755.png)

http://screencast.com/t/RHy2EGpO

**Comment by tomyeh** [comment] 2016-12-30 02:05
Some background information:
In [our production environment](https://quire.io), the memory usage of one VM grows from 200M to over 1GB within a week (on Dart 1.20/1.21 -- much better than 1.19). And, we can observe a similar pattern in our test environment. If we turned off WebSocket and used periodic Ajax polling instead (in our test environ), the problem was gone. It is why this tiny program is created.

Please tell us know if anything we can help to clarify the issue. Thanks.

**Comment by mraleph** [comment] 2018-04-24 21:25
I am assuming this issue is stale. Please reopen if more work need to happen in this area.

**Comment by tomyeh** [comment] 2018-04-25 01:29
No, the problem is still there. We're forced to restart the server if exceeding a limit. Please look at it. Thanks.

**Comment by mraleph** [comment] 2018-04-25 04:02
@zanderso is this something you might have free cycles to look into?

@tomyeh is the program from the first comment representative of the memory leak you are seeing?

**Comment by tomyeh** [comment] 2018-04-25 04:29
The program in the first comment is what we tried to reproduce with a simple case. The real program is of course much more complicated. Here is what we have done. Hope it helps.

1. We found memory leak in the production environment
2. We reproduced it with a stress test locally
3. Once tracking down, we suspected it was caused by WebSocket, so we ran the stress test again by turning off WebSocket (i.e., we use Ajax to pull periodically). There was no memory leak found in this test.
4. So, we created a very simple case as shown in the first comment to reproduce the issue. And, it did.

**Comment by tomyeh** [comment] 2018-06-20 10:35
I made another simplified test code as follows. From server's log, you'll find RSS keeps growing. You can run the client code multiples time or adjust the loop to magnify the growing memory use.

```
//server
import "dart:io";

void main() {
  HttpServer
  .bind(InternetAddress.ANY_IP_V4, 8081)
  .then((server) {
    server.listen((request) {
      int count = 0;
      WebSocketTransformer.upgrade(request)
      .then((socket){
        socket.listen((data) {
          count += data.length;
        }, onDone: () {print('Done: $count; rss=${ProcessInfo.currentRss~/(1024*1024)}');});
        return socket.done;
      });
    });
  });
}
```

and

```
//client
import "dart:io";

main() async {
  for (int i = 0; i++ < 1000;)
    await WebSocket.connect("ws://localhost:8081")
    .then((socket) {
      for (int j = 0; j++ < 1000;)
        socket.add("data: $i,$j".codeUnits);
      socket.close();
    });
}
```

**Comment by tomyeh** [comment] 2018-07-20 01:15
I found a workaround: cancel subscription when the WebSocket connection is closing.

```
var subpt
subpt = socket.listen(..., onDone: subpt.cancel);
```

Not sure if memory consumption is stabilised (I just watched it a day), but at least the growth of memory consumption is reduced from 900M to 400M after online 20 hours.

It seems be cyclic reference issue. Hope this information helps.

**Comment by sgehrman** [comment] 2020-06-04 11:51
I'm on the latest flutter beta and latest dart.

Flutter (Channel beta, 1.18.0-11.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-11.1.pre at /home/steve/google/flutter
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

I'm seeing a massive memory leak using websockets.  I'm sending a 1gb file to my shelf server and I dart observatory shows 3gb of _Uint8Lists leaking.  If I close the server, a ton of ram is released, but the server runs all the time, I can't close it everytime someone uploads a file. What can I do?

**Comment by tomyeh** [comment] 2020-06-04 14:24
Did you try Dart 2.8 at server side? Based on our experiences, the memory usage is much better than older versions. Our server can run days under heavy load without significant memory surge. However, we don't use Dart 2.9 in production system yet, so no sure if any difference.

**Comment by zanderso** [comment] 2020-06-04 15:05
@sgehrman can you share a small code example for the situation you describe that causes that much memory to be retained. (for example like the one in https://github.com/dart-lang/sdk/issues/27414#issuecomment-398703983)

@zichangg @a-siva

**Comment by sgehrman** [comment] 2020-06-04 23:19
@tomyeh The server is running in my flutter mobile app.  I have a feature where my app hosts a web page locally and uses can view and drag and drop files from their browser on the desktop.  The files are send with websockets sendBlob.  So, I don't know how easy it is to downgrade dart.  I read Dart version is tied to the Flutter SDK? 

@zanderso I'm using all these packages like shelf, shelf_web_socket, web_socket_channel. It's not super easy to make a small code example.  The code is very simplistic.

The browser side:

 ```
 final html.WebSocket webSocket =
        html.WebSocket('ws://${hostUri.host}:8764');
   
     // after socket opens
    _transferSocket.sendBlob(File(path));
```

The server side:

```
import 'package:shelf/shelf_io.dart' as io;
import 'package:web_socket_channel/web_socket_channel.dart';

Future<void> _serve() async {
    final wsh = webSocketHandler(_webSocketHandler);

    final cascade = shelf.Cascade().add(wsh);

    _server = await io.serve(cascade.handler, InternetAddress.anyIPv4, port);
  }

  void _webSocketHandler(WebSocketChannel webSocket) {
    webSocket.stream.listen((dynamic message) {
      if (message is Uint8List) {
       File(path).writeAsBytesSync(content);
    }
}

```

If I posted an apk would that be enough to debug it on your end?

I could also add you as a github collaborator if you wanted to get the code and run the app.  The code is private.  Hoping to release it in a few weeks.

**Comment by zichangg** [comment] 2020-06-08 05:12
@sgehrman Hi, I'd like to help!
Unfortunately, I don't have a mobile device to test with my WFH environment. What platform your app is running? And can you also try not to write into a file? It is possible that file.writeAsBytesSync() is leaking.

If you can also try your code with Http? [Package_http](https://pub.dev/packages/http) is very easy to use. I just wanna make sure the websocket is indeed the culprit.

**Comment by Isakdl** [comment] 2024-11-12 16:00
I have similar problems as reported here, after extensive testing, I found no issues running locally while monitoring with Dart DevTools. However, in a Docker container, memory issues arise if the client does not explicitly call `socket.close()` before disconnecting. In such cases, memory usage on the server increases to about 50% of the allocated 1 GB. Performance degrades with the server handling requests very slowly, ultimately leading to an out-of-memory (OOM) kill by Docker, despite reported memory usage remaining at ~50%. 

Note that it also seems like the docker container keeps the reported memory usage relatively constant after new allocations. E.g. I'm not seeing big reductions in memory usage. But when running locally both in JIT and AOT mode I observe that the process gets a big reduction of memory usage now and then.

Another peculiar fact is that the size of the data sent on the socket also seems to impact how fast I can reach the problems.

Dart version: 3.5

I used the code by @sgehrman for my testing, and the official docker example (https://hub.docker.com/_/dart):
**Server code**
```dart
import "dart:async";
import "dart:io";

void main() {
  HttpServer.bind(InternetAddress.anyIPv4, 8081).then((server) {
    server.listen((request) {
      int count = 0;
      late StreamSubscription subscription;
      WebSocketTransformer.upgrade(request).then((socket) {
        socket.pingInterval = const Duration(seconds: 1);
        subscription = socket.listen(
          (dynamic data) {
            count += (data as List).length;
          },
          onDone: () async {
            print(
              'Done: $count; rss=${ProcessInfo.currentRss ~/ (1024 * 1024)}',
            );
            await subscription.cancel(); //This solution does not help
          },
        );
        return socket.done;
      });
    });
  });
}
```

**Client code**
```dart
import "dart:io";
import "dart:async";

final String data = '<a long string>';

main() async {
  for (int i = 0; i++ < 100;) {
    final ops = <Future>[];
    for (int j = 0; j++ < 100;) {
      ops.add(WebSocket.connect("ws://localhost:8081").then((socket) {
        for (int k = 0; k++ < 100;) {
          socket.add(data.codeUnits);
        }
        //socket.close(); // If this call is not done we get memory problems
      }));
    }
    print('awaiting ops');
    await Future.wait(ops);
  }

  exit(0);
}
```

**Dockerfile**
```Dockerfile
FROM dart:stable AS build

WORKDIR /app
COPY pubspec.* ./
RUN dart pub get

COPY . .
RUN dart pub get --offline
RUN dart compile exe lib/websocket_server.dart -o bin/server

FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/bin/

EXPOSE 8081
CMD ["/app/bin/server"]
```

**Comment by mraleph** [comment] 2024-11-18 13:07
I took a look at this today using the code provided by @Isakdl above. It clear was leaking inside and outside of the Docker container: what I saw is `_NativeSocket` objects leaking. This seems to be happening because something is wrong with shutdown sequence: we shutdown read direction on the socket first, and then we shutdown write direction - but then we don't actually recognize that both directions are now shutdown and we need to close and destroy the socket. And the socket left lingering in the zombie state.

The code in `shutdownWrite` says:

```dart
   void shutdownWrite() {
    if (!isClosing && !isClosed) {
      if (closedReadEventSent) {
        close();
      } else {
        sendToEventHandler(1 << shutdownWriteCommand);
      }
      isClosedWrite = true;
    }
  }
```

We arrive here with `isClosedRead` but `!closedReadEventSent` - which I think happens because we have also disabled read events by that time. Because `readEventsEnabled` is `false` we will never set `closedReadEventSent` to `true` and as a result we will never fully close the socket in this case. This seems wrong. 

It immediately jumps to me that `shutdownWrite` is markedly asymmetric with `shutdownRead` which simply does:

```dart
  void shutdownRead() {
    if (!isClosing && !isClosed) {
      if (isClosedWrite) {
        close();
      } else {
        sendToEventHandler(1 << shutdownReadCommand);
      }
      isClosedRead = true;
    }
  }
``` 

This makes me immediately suspicious of the code. 

I have tried bringing `shutdownWrite` to parity with `shutdownRead` and that does fix `_NativeSocket` leak, but I think `closedReadEventSent` was introduced to fix some other problem (see 1d928984a3bd75d0a3656e9b6476073e831d5c23), so I would need to dig deeper to figure out what exactly do I need to change here.

**Comment by mraleph** [comment] 2024-11-20 13:30
[This CL](https://dart-review.googlesource.com/c/sdk/+/396340) should fix the leak of `_NativeSocket` objects. My previous analysis was slightly incorrect, I have amended the comment above for posterity. 

While the leak seems to be fixed with my CL, I still observe somewhat suboptimal behavior from the GC - we don't seem to trigger mark sweep GC often enough which means we keep accumulating some external memory (IO buffers?) which causes RSS to grow. 

@rmacnak-google could you take a look if we could tweak our GC heuristics here? You would need to apply my CL to fix the leak and then just run the code from the comment [above](https://github.com/dart-lang/sdk/issues/27414#issuecomment-2470922509) (no Docker is needed to reproduce this).

**Closed** 2024-11-27 21:27 UTC
Labels: area-vm, library-io, type-bug

**Comment by Isakdl** [comment] 2024-11-29 16:01
@mraleph Good job! Thank you so much for this! 😀 👍 👏
