### ISSUE TITLE
Nullsafety: The flow analisys failed

### ISSUE THREAD

**Issue by vi-k** [dart-lang/sdk#45015] opened 2021-02-16 02:49 UTC
```
void main() {
  final today = DateTime.now();
  DateTime? userDate;
  DateTime firstDate = (userDate?.isBefore(today) ?? false) ? userDate : today;
}

Error: A value of type 'DateTime?' can't be assigned to a variable of type 'DateTime' because 'DateTime?' is nullable and 'DateTime' isn't.
  DateTime firstDate = (userDate?.isBefore(today) ?? false) ? userDate : today;
                                                            ^
Error: Compilation failed.
```

Of course I can write `userDate!`. But everything is obvious there.

**Comment by mit-mit** [comment] 2021-02-25 10:39
Sorry, it's not obvious how the uninitialized `userDate` would be non-nullable. Please provide more information.

**Comment by eernstg** [comment] 2021-02-25 10:49
This is essentially an instance of the topic discussed in https://github.com/dart-lang/language/issues/1224: The comment https://github.com/dart-lang/language/issues/1224#issuecomment-694353803 has this example:

```dart
if (x?.hasSomeField ?? false) {
  doSomething(x.someField);
}
```

**Comment by eernstg** [comment] 2021-02-25 10:55
Given that the discussion in dart-lang/language#1224 already covers the request here (so it is an active language discussion), and given that the example [here](https://github.com/dart-lang/sdk/issues/45015#issue-808941191) is working as intended (unless and until we change the language as proposed in dart-lang/language#1224), I think we can close this issue.

**Closed by eernstg** 2021-02-25 10:55 UTC
