### ISSUE TITLE
the dart analyzer keep has terminated any time i start coding and i did not get any code feedback from messages view 

### ISSUE THREAD

**Issue by abodrak** [dart-lang/sdk#38020] opened 2019-08-27 08:12 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[categoryName]
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1333:9)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2578:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2515:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3241:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#15     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:514:18)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#30     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#32     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#33     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#41     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#42     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#43     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#45     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[categoryName]
#0      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1333:9)
#1      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2578:14)
#2      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2515:14)
#3      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3241:13)
#4      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#5      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#6      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#7      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#8      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#11     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#12     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#13     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#14     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#15     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#16     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:514:18)
#17     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#18     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#19     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#20     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#21     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#22     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#23     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#29     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#30     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#32     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#33     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#41     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#42     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#43     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#45     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
  /Users/abdullah/Documents/flutter/bin/cache/dart-sdk/bin/dart /Users/abdullah/Documents/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=Android-Studio --client-ver
1566893263713 <= {"event":"server.connected","params":{"version":"1.27.1","pid":93498,"sessionId":""}}
1566893263747 <= {"id":"0","result":{"version":"1.27.1"}}
1566893263748 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1566893262736}
1566893263748 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1566893263748 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop"],"excluded":["/Users/abdullah/Desktop/dailyUIFlutter/mo
1566893263748 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart"]},"clientRequestTime":156689326
1566893263748 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart"],"CLOSING_
1566893263748 => {"id":"6","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1566893263165}
1566893263748 => {"id":"7","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart"]}}}
1566893263758 <= {"id":"1"}
1566893263769 <= {"id":"2"}
1566893264637 <= {"event":"analysis.errors","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/pubspec.yaml","errors":[]}}
1566893264709 <= {"event":"analysis.errors","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/android/app/src/profile/AndroidManifest.xml","errors":[]}}
1566893264714 <= {"event":"analysis.errors","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/android/app/src/main/AndroidManifest.xml","errors":[]}}
1566893264715 <= {"event":"analysis.errors","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/android/app/src/debug/AndroidManifest.xml","errors":[]}}
1566893266191 <= {"id":"3"}
1566893266195 <= {"id":"4"}
1566893266220 <= {"id":"5"}
1566893266231 <= {"id":"7"}
1566893266254 <= {"id":"6","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1566893266262 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1566893267290 <= {"event":"analysis.errors","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR
1566893267321 <= {"event":"analysis.highlights","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart","regions":[]}}
1566893267338 <= {"event":"analysis.navigation","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart","regions":[],"targets":[],"files":[]}}
1566893267344 <= {"event":"analysis.closingLabels","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart","labels":[]}}
1566893267362 <= {"event":"analysis.outline","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPI
1566893267364 <= {"event":"analysis.overrides","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart","overrides":[]}}
1566893267380 <= {"event":"flutter.outline","params":{"file":"/Users/abdullah/Desktop/dailyUIFlutter/mobile/fruit_shop/lib/testdata/category.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":
1566893268240 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Unsupported operation: unsupported initializer: IndexExpressionImpl :: super()[categoryN
```
``` 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-AE)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[!] VS Code (version 1.37.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

**Comment by srawlins** [comment] 2019-08-30 19:52
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38009; please follow along there.

**Comment by srawlins** [comment] 2019-08-30 19:52
Duplicate of #38009

**Closed by srawlins** 2019-08-30 19:52 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
