### ISSUE TITLE
Missing warning for duplicate parameters

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#27174] opened 2016-08-27 16:56 UTC
The following code doesn't generate any warnings:

```dart
class MyClass {
  String name;
  String doc;

  MyClass(String name, String doc, this.doc);
}

main() {
  var a = new MyClass("test", "test", "test");
  print(a.name);
}
```

However it gives this error when run:

```shell
c:\Users\danny\Desktop\DartSample>dart test.dart
'file:///c:/Users/danny/Desktop/DartSample/test.dart': error: line 5 pos 41: duplicate formal parameter 'doc'
  MyClass(String name, String doc, this.doc);
```

Presumably there should be a warning about the duplicate parameters.

**Comment by eernstg** [comment] 2016-08-27 17:19
Thanks for the report! However, this issue is currently being resolved:

As per https://github.com/dart-lang/sdk/issues/26655, we are introducing the ability to access initializing formal parameters (like the third parameter `this.doc` in your example) in the initializer list. This makes the behavior of `dart` correct (there will be a name clash), and the analyzer will be updated to diagnose this kind of name clash as a compile time error.

**Comment by lrhn** [comment] 2016-08-27 17:19
So this issue is effectively a duplicate of #26658.

**Closed by eernstg** 2016-08-27 17:19 UTC
