### ISSUE TITLE
Generic has wrong runtimeType if compiled to JS

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#24666] opened 2015-10-21 12:31 UTC
*How you can reproduce it:*
Take this sample: http://samples.material-design-lite.pub/mdld_repeat_data-table/index.html
Open the console and click on EVGA... (price 110.12)
You can see the result of this line:
```dart
_logger.fine("Input-Value: '$val' (${val.runtimeType}) -> '${_value}' (${_value.runtimeType})");
```

I use OvservableProperty for setting the value (https://goo.gl/ZoVsMe) 
I take the untyped input value, check against the generic runtimeType and convert if necessary. In the above sample the input value (double) 110.12 should stay the same. This works fine with the DartVM but fails if compiled to JS. 
**The JS-Version returns int as runtimeType for a generic defined as double.**

Here is the definition (main.dart where I define `final ObservableProperty<double> total`: https://goo.gl/c4QTtE 
If you tick the checkbox then this line sets the value https://goo.gl/plF0sX and produces the log output.

Output in Dartium/Chromium:
![screenshot-1877](https://cloud.githubusercontent.com/assets/116654/10636253/ceb8b0c4-77fe-11e5-964a-9f3061e9a7c6.png)

An here is Chrome:
![screenshot-1878](https://cloud.githubusercontent.com/assets/116654/10636256/d84e47ac-77fe-11e5-8bc5-9aa604d82029.png)

**Comment by sigmundch** [comment] 2015-10-21 21:28
This is one of those few cases where the vm and dart2js differ by design. Dart2js'  runtime types of numbers is derived from the numeric representation we get in JavaScript, where `0.0` and `0` are equivalent.

In your example, this means that an initial value of 0.0 will set initial type as int, not double.

Here is a small example that also illustrates the situation:
```dart
main() {
  var x = 1.0;
  print(x.runtimeType);
  print(x.toDouble().runtimeType);
  print(x.toInt().runtimeType);
}
```

This will print `double` `double` `int` in the VM, but `int` `int` `int` in dart2js.

Making as a duplicate of https://github.com/dart-lang/sdk/issues/1533

**Closed by sigmundch** 2015-10-21 21:28 UTC
Labels: Area-Dart2JS
