### ISSUE TITLE
Compiler check for the nullability of condition cases

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#47106] opened 2021-09-03 20:12 UTC
In the below case, the compiler hints that `child` could be null, however it can't, since it is either `B` or `C`.

```dart
class A {
  A? parent;
}

class B extends A {}
class C extends A {}

void f(A a) {
  A? child = a;
  while (child is B || child is C) {
    child = child.parent; // The property 'parent' can't be unconditionally accessed because the receiver can be 'null'.
  }
  while (child is B) {
    child = child.parent; // this is fine
  }
  while (child is C) {
    child = child.parent; // this is fine
  }
}
```

Please change the title to be better understood. Any hint of where this check should be implemented is highly appreciated.

**Comment by bwilkerson** [comment] 2021-09-03 20:52
That's also part of flow analysis.

@leafpetersen @stereotype441

**Comment by stereotype441** [comment] 2021-09-07 13:29
Duplicate of https://github.com/dart-lang/language/issues/1377

**Closed by stereotype441** 2021-09-07 13:29 UTC
