### ISSUE TITLE
resource does not support package URI in the browser

### ISSUE THREAD

**Issue by kseo** [dart-lang/sdk#25594] opened 2016-01-27 05:51 UTC
`readAsString()` throws the following error when I pass a package URI to the `Resource` constructor in the browser:

Uncaught Unhandled exception:
Unsupported operation: Isolate.resolvePackageUri
#0      Isolate.resolvePackageUri (dart:isolate-patch/isolate_patch.dart:296)
#1      resolveUri.<resolveUri_async_body> (package:resource/src/resolve.dart:11:20)
#2      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#3      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#5      _ScheduleImmediateHelper._handleMutation (dart:html:49254)
#6      MutationObserver._create.<anonymous closure> (dart:html:27525)

**Comment by lrhn** [comment] 2016-01-27 09:13
It seems the dart2js implementation of `resolvePackageUri` wasn't part of the 1.14 release. 
@sigmundch Is there an implementation we can add? (I believe the packages directory default to Uri.base.resolve("packages/"), or something similar)

**Comment by kevmoo** [comment] 2016-02-01 16:47
@lrhn Should @kseo look at the resource package?

**Comment by floitschG** [comment] 2016-02-01 17:19
The stacktrace seems to indicate that the code is already using the resource package.

**Comment by dynaxis** [comment] 2016-02-01 23:06
Yes, we found the isssue in the course of trying the `resource` package.

**Comment by sigmundch** [comment] 2016-02-04 23:24
/cc @hterkelsen 

@lrhn - good question. I'm not sure if defaulting to `packages/` would be the right thing for dart2js - it makes sense for dartium because the goal there is to match the code layout used for development. But for deployment, I'm not sure how much that matches the location customers want.

I've seen many apps where they need to have a different layout, for example, to keep internal code organization private in production apps. To support that, one idea we've discussed in the past is to provide dart2js with a mapping from package-uris to specific deployment urls, so we can use it when generating code. This requires that those resources are loaded using const-constructors, so dart2js can statically determine where the rewrites are needed.

Thoughts?

**Comment by dynaxis** [comment] 2016-02-06 10:20
@sigmundch I also thought that there must be such requirements of hiding some codes. Your idea of requiring users to specify explicit mappings is good. But as an alternative way of resolving the issue, `dart2js` can just set a rule of its own simple and users do the hard part:

1. `dart2js` sets URL for the root location where the package contents will be available. There are, for instance, the following possibilities:
    * A fixed location relative to the HTML page or the Dart script
    * A location encoded to an attribute in the HTML page containing the Dart script
2. As a deployment procedure, users may prepare what to expose the Dart script running on browsers and place them at the location determined in the item 1 above.

I usually prefer a simpler solution. ;)

**Comment by dynaxis** [comment] 2016-02-06 10:41
@sigmundch I also have some concerns on the idea you outlined:

1. `dart2js` recognizing `Resource` constructurs seems defeats the original intention of separating it as a separate package.
2. Only `const Resource` working properly may not fulfill some use cases.

**Comment by smithtrenton** [comment] 2016-03-29 17:43
Confirming this is still an issue in 1.15.0
Using a relative path works in browser but "package:" still throws an exception.
I have issues with running coverage on my tests when I use the relative path, and was hoping that using a package URI would be the solution.

**Comment by dentra** [comment] 2016-10-25 10:03
I have the same problem with 1.20.1

**Comment by kingkazuma** [comment] 2016-11-13 15:00
I have the same problem with 1.20.1

**Comment by sigmundch** [comment] 2016-11-14 23:24
I just made a change to make this work with dart2js: as suggested earlier by default you get `packages/` from the initial base url (location.href), but there is a hook to override this by setting the property `defaultPackagesBase` in JS. That should hopefully provide enough flexibility in production.

Note however that this is only implemented in dart2js and it is not yet available in Dartium. So I'm keeping the bug open to track that.

**Comment by terrylucas** [comment] 2016-11-29 18:26
Could change the VM's runtime/lib/isolate_patch.dart file to match what Siggi did (sans the JS defaultPackagesBase override).  But this is really owned by the VM team.  Talked to Siggi he suggest we only do the packages/ from the initial base url (not sure what location.href means in VM only context).

I could make a change suggestion and send it to Siva and let him make the real change (there maybe other implications from the VMs point of view).

**Comment by terrylucas** [comment] 2016-11-29 18:56
In particular how would standalone VM want to resolve URI's would the VM always call an API (callback) were we can return the base URI?  Should talk to Siva.

**Comment by terrylucas** [comment] 2016-11-29 19:11
Dartium does call the VM API Dart_CreateIsolate passing in the domData (in parameter callback_data) which contains the packageRoot - it could be used by the isolate_patch.dart file?

**Comment by mit-mit** [comment] 2016-12-16 12:25
@terrylucas @a-siva did you resolve this?

**Comment by a-siva** [comment] 2016-12-23 06:10
Terry I can make the corresponding change in the VM's runtime/lib/isolate_patch.dart, do you have a test to reproduce and verify the fix?

**Comment by a-siva** [comment] 2016-12-28 01:11
Terry, There seems to be an issue with the way dartium implements the resolvePackageUri functionality. If you see the VM's runtime/lib/isolate_patch.dart file the function resolvePackageUri is implemented as
  @patch static Future<Uri> resolvePackageUri(Uri packageUri) {
    var hook = VMLibraryHooks.resolvePackageUriFuture;
    if (hook == null) {
      throw new UnsupportedError("Isolate.resolvePackageUri");
    }
    return hook(packageUri);
  }
It looks like dartium does not setup the VMLibraryHooks at all as a result of which it is null and you get the error message 'Unsupported operation: Isolate.resolvePackageUri'

In standalone VM we setup the hooks in builtin.dart (see setupHooks()).

I tried the test that Siggi had on the stand alone VM and it works.

**Comment by terrylucas** [comment] 2017-01-06 17:46
Have a change to support resolvePackageUri in Dartium by setting up the VMLibraryHooks.  Dartium will only support resolvePackageUri it will not support the defaultPackagesBase so only package: is resolved.

**Comment by terrylucas** [comment] 2017-01-10 15:28
Committed CL 2611353002 and CL 2543703003

**Closed by terrylucas** 2017-01-10 15:28 UTC
Labels: area-dartium, area-library, library-isolate
