### ISSUE TITLE
Compilation error on OneLiner

### ISSUE THREAD

**Issue by Segebre** [dart-lang/sdk#36405] opened 2019-04-01 05:14 UTC
When using `fold` inside a `print()` we get a compilation error for the `+` inside the combine function. This happens on DartPad and can be shown [here](https://dartpad.dartlang.org/6f8ed5d68bf05f116a31c224078b0e90).

**Comment by lrhn** [comment] 2019-04-01 05:50
The code in question is
```dart
var nums = [1, 4, 2, 3, 5];
print(nums.fold(-10, (p, i) => p + i)); // Uncommenting this causes a compilation error.
```
And the error is that `+` is not defined on `Object`.
I'm guessing downards inference pushes down `Object` as the return type of `fold`, which then means that type `Object`. 

This is technically working as intended,  because the downwards inference wins. It's just a useless inference here, and a place where upwards would give the correct result.

**Comment by eernstg** [comment] 2019-04-01 07:16
Also note #25490 and #34118, where it is discussed that `fold` in particular tends to create situations where the current approach to inference does not route the available information far enough to produce the best outcome. Changes in this area need to be made cautiously because they are likely to be pervasively but subtly breaking, but it is certainly on the radar.

I believe the consistent approach would be to close this issue as a duplicate of #25490. I've added a reference to this issue in #25490 in order to preserve the information that it came up again, and how.

**Closed by eernstg** 2019-04-01 07:16 UTC
Labels: area-language
