### ISSUE TITLE
Cannot serialize an instance of GenericFunctionTypeImpl

### ISSUE THREAD

**Issue by mylaimani** [dart-lang/sdk#37752] opened 2019-08-06 06:23 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.5728.87`
- `1.24.3`
- `WS-192.5728.87, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: D:\test\test.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:550)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:356)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:472)
#11     _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1076)
#12     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#14     _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:525)
#15     serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22)
#16     FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:473)
#17     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#18     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:472)
#19     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#20     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#21     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:531)
#22     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#23     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#24     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:536)
#25     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:805)
#26     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:593)
#27     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:531)
#28     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:766)
#29     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:954)
#30     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#32     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#33     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#34     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#35     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#36     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#37     _rootRun (dart:async/zone.dart:1120)
#38     _CustomZone.run (dart:async/zone.dart:1001)
#39     runZoned (dart:async/zone.dart:1467)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#41     Driver.start (package:analysis_server/src/server/driver.dart:473)
#42     main (file:///D:/src/sdk1/sdk/pkg/analysis_server/bin/server.dart:12)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

For additional log information, please append the contents of
file://C:\Users\mylai\AppData\Local\Temp\report.txt.

**Comment by a-siva** [comment] 2019-08-12 17:24
appears to be a duplicate of https://github.com/dart-lang/sdk/issues/37703

**Closed by a-siva** 2019-08-12 17:24 UTC
Labels: area-analyzer, closed-duplicate
