### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by Manoj-Perumarath** [dart-lang/sdk#35498] opened 2018-12-26 08:11 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

# Exception

Please append the contents of:
file://C:\Users\manoj.rajan\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\futsal-android-ios-app], excluded: [D:\futsal-android-ios-app\.idea, D:\futsal-android-ios-app\.dart_tool, D:\futsal-android-ios-app\.pub, D:\futsal-android-ios-app\build]}, clientRequestTime: 1545805232540}
FileSystemException: Exists failed, path = 'D:\futsal-android-ios-app\build\app\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\google\firebase\storage\common' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2019-01-02 18:16
Duplicate of #34294

**Closed by stereotype441** 2019-01-02 18:16 UTC
Labels: area-analyzer
