### ISSUE TITLE
Isolate.spawnUri does not support spawning from http urls

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#33741] opened 2018-07-03 09:08 UTC
It appears that with the introduction of the new front-end we no longer support spawning from http URIs:

Launching a server which serves `hello.dart`:
```
% echo 'main() => print("hello world");' > hello.dart
% python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

Testing it with:
```
% cat test.dart
import 'dart:async';
import 'dart:isolate';

main() async {
  await Isolate.spawnUri(Uri.parse('http://localhost:8000/hello.dart'), null, null);
  await new Future.delayed(const Duration(seconds: 10));
}
```

Running with dev.63
```
% dart-sdk-63/bin/dart test.dart
hello world
```

Running with dev.66
```
% dart-sdk-66/bin/dart test.dart
Unhandled exception:
IsolateSpawnException: Unable to spawn isolate: http://localhost:8000/hello.dart:1: Error: File http://localhost:8000/hello.dart does not exist.
#0      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:450:14)
<asynchronous suspension>
#1      main (.../test.dart:5:17)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

@lrhn I assume this functionality has not been removed intentionally?

@kmillikin / @mraleph Guess the CFE needs to be implemented ?

**Comment by mkustermann** [comment] 2018-07-03 09:11
This is blocking upgrading `package:rpc` to Dart 2.0

**Comment by lrhn** [comment] 2018-07-03 09:19
I'm not aware of any plan to remove the functionality. I'm guessing the front-end just doesn't have a way to load sources from HTTP URIs.

With a little luck, file loading in the front-end can be overridden by the VM, so they can add HTTP loading as well.

**Comment by mkustermann** [comment] 2018-07-03 11:03
> Should this be marked as blocking Dart 2 stable release? @mkustermann

Since @lrhn says we should have this functionality working and we own packages which need it (as might other 3rd party packages) to be Dart 2.0 compliant, I would think so.

**Comment by mraleph** [comment] 2018-07-03 16:19
Duplicate of #33388

**Closed by mraleph** 2018-07-03 16:19 UTC
Labels: P1 high, Type: bug, area-front-end
