### ISSUE TITLE
Pub Serve doesn't work in 1.22.0-dev.7.0

### ISSUE THREAD

**Issue by ksdboasit** [dart-lang/sdk#28381] opened 2017-01-13 14:00 UTC
Summary:
I was trying to run the simple web application from the sample content, but "pub serve" doesn't appear to work properly.
After the line: "Loading dart_to_js_script_rewriter transformers...", I just get a list of global options and available commands for pub.

What steps will reproduce the problem?

Create a new project with the sample content named: "Simple Web Application". After resolving dependencies, run web/index.html

What is the expected output? What do you see instead?
Expected:
The following text in the Pub Serve window (likely using a different port):
```
"C:\....\dart-sdk\bin\pub.bat" serve web --port=57064
Loading source assets...
Loading dart_to_js_script_rewriter transformers...
Serving Test7 web on http://localhost:57064
Build completed successfully
[web] GET Served 4 assets.
```

as well as the web app launching in Chromium

Actual:
```
"C:\....\dart-sdk\bin\pub.bat" serve web --port=57258
Loading source assets...
Loading dart_to_js_script_rewriter transformers...
Pub is a package manager for Dart.

Usage: pub <command> [arguments]

Global options:
-h, --help             Print this usage information.
    --version          Print pub version.
```

etc.
ending with
```
Run "pub help <command>" for more information about a command.
See http://dartlang.org/tools/pub for detailed documentation.
Pub Serve terminated
```

and Chromium only showing a 502 Bad Gateway error

What version of the product are you using?
Dart 1.22.0-dev.7.0
WebStorm 2016.3 (but also the case for IntelliJ 2016.3)

On what operating system?
Windows 10(64bit) (in the above example, but the same was the case on OS X Sierra)

Please provide any additional information below.
Also tried to run pub serve from the terminal, with the same result.
Running pub get in WebStorm I get this message:
```
Resolving dependencies...
Got dependencies!
Process finished with exit code 0
```

While in IntelliJ I get:
```
Resolving dependencies...
Got dependencies!
Precompiling dependencies...
Loading source assets...
Loading dart_to_js_script_rewriter transformers...

```
followed by the pub help information.

**Comment by alexander-doroshko** [comment] 2017-01-13 14:18
https://github.com/dart-lang/sdk/issues/28346

**Comment by munificent** [comment] 2017-01-13 19:30
Like @alexander-doroshko notes, this is a duplicate of https://github.com/dart-lang/sdk/issues/28346.

**Closed by munificent** 2017-01-13 19:30 UTC
Labels: Resolution: duplicate
