### ISSUE TITLE
CFE/Analyzer inconsistent errors

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#42519] opened 2020-06-29 22:42 UTC
I have a few questions around the following two functions:

```dart
Future<int> fn() async => 'Not an int' as dynamic;
Future<Object> gn() async => null as dynamic;
```

1) Should there be any static errors?
  * The analyzer produces no errors.
  * The CFE produces one error:
```
org-dartlang-app:/test_07.dart:12:40: Error: A value of type 'Future<dynamic>' can't be assigned to a variable of type 'FutureOr<int>'.
 - 'Future' is from 'dart:async'.
Future<int> fn() async => 'Not an int' as dynamic;
                                       ^
```

2) If the CFE is correct, is there some explanation in the nnbd spec as to why one is allowed and the other is rejected?

cc @leafpetersen @johnniwinther @stereotype441

**Comment by leafpetersen** [comment] 2020-06-30 00:36
@eernstg I think this is the issue you landed a clarification for in the spec a few months ago.  Off the top of my head I think the CFE is in error here, but can you verify, and verify that we have a (presumably failing) test that covers this?

**Comment by eernstg** [comment] 2020-06-30 07:28
Right, there are no compile-time errors in the two examples [here](https://github.com/dart-lang/sdk/issues/42519#issue-647718273). The future value type of the two functions are `int` resp. `Object`, and `dynamic` is assignable to both, with and without null-safety.

This has been reported in https://github.com/dart-lang/sdk/issues/41800 for the CFE, with a specific reference to language/invalid_returns/async_valid_returns_test where this situation arises and causes a test failure, So I'll close this one as a duplicate of #41800.

**Closed by eernstg** 2020-06-30 07:28 UTC
Labels: NNBD, area-front-end, closed-duplicate, type-bug
