### ISSUE TITLE
VS code exception

### ISSUE THREAD

**Issue by keshava19** [dart-lang/sdk#39992] opened 2020-01-06 11:26 UTC
Using Windows 10
Editor - VSCode

<details>
  <summary>Dart analyzer crash report</summary>
  !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.1
Platform: win
HTTP_PROXY: undefined
NO_PROXY: undefined

Mon Jan 06 2020 [16:18:03 GMT+0530 (India Standard Time)] Log file started
[4:18:03 PM] [General] [Info] Searching for SDKs...
[4:18:03 PM] [General] [Info] Environment PATH:
[4:18:03 PM] [General] [Info]     C:\Windows\system32
[4:18:03 PM] [General] [Info]     C:\Windows
[4:18:03 PM] [General] [Info]     C:\Windows\System32\Wbem
[4:18:03 PM] [General] [Info]     C:\Windows\System32\WindowsPowerShell\v1.0\
[4:18:03 PM] [General] [Info]     C:\Program Files\Git\cmd
[4:18:03 PM] [General] [Info]     C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps
[4:18:03 PM] [General] [Info]     C:\flutter\bin
[4:18:03 PM] [General] [Info]     C:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\bin
[4:18:03 PM] [General] [Info]     C:\adb
[4:18:03 PM] [General] [Info]     %SystemRoot%\system32
[4:18:03 PM] [General] [Info]     %SystemRoot%
[4:18:03 PM] [General] [Info]     %SystemRoot%\System32\Wbem
[4:18:03 PM] [General] [Info]     %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
[4:18:03 PM] [General] [Info]     %SYSTEMROOT%\System32\OpenSSH\
[4:18:03 PM] [General] [Info]     C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps
[4:18:03 PM] [General] [Info]     C:\flutter\bin
[4:18:03 PM] [General] [Info]     C:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\bin
[4:18:04 PM] [General] [Info] Found Flutter project at C:\Users\keshava.m\Documents\Project:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[4:18:04 PM] [General] [Info] Searching for flutter.bat
[4:18:04 PM] [General] [Info]     Looking for flutter.bat in:
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin\
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\.flutter
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\.flutter\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\vendor\flutter
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\vendor\flutter\bin
[4:18:04 PM] [General] [Info]         C:\Windows\system32
[4:18:04 PM] [General] [Info]         C:\Windows\system32\bin
[4:18:04 PM] [General] [Info]         C:\Windows
[4:18:04 PM] [General] [Info]         C:\Windows\bin
[4:18:04 PM] [General] [Info]         C:\Windows\System32\Wbem
[4:18:04 PM] [General] [Info]         C:\Windows\System32\Wbem\bin
[4:18:04 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[4:18:04 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[4:18:04 PM] [General] [Info]         C:\Program Files\Git\cmd
[4:18:04 PM] [General] [Info]         C:\Program Files\Git\cmd\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\bin
[4:18:04 PM] [General] [Info]         C:\adb
[4:18:04 PM] [General] [Info]         C:\adb\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\system32
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\system32\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\System32\Wbem
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\System32\Wbem\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\OpenSSH\
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\OpenSSH\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\bin
[4:18:04 PM] [General] [Info]     Found at:
[4:18:04 PM] [General] [Info]         C:\flutter\bin\
[4:18:04 PM] [General] [Info]         C:\flutter\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin
[4:18:04 PM] [General] [Info]     Candidate paths to be post-filtered:
[4:18:04 PM] [General] [Info]         C:\flutter
[4:18:04 PM] [General] [Info]         C:\flutter
[4:18:04 PM] [General] [Info]         C:\flutter
[4:18:04 PM] [General] [Info]     Found at C:\flutter
[4:18:04 PM] [General] [Info]     Returning SDK path C:\flutter for flutter.bat
[4:18:04 PM] [General] [Info] Searching for dart.exe
[4:18:04 PM] [General] [Info]     Looking for dart.exe in:
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[4:18:04 PM] [General] [Info]         C:\Windows\system32
[4:18:04 PM] [General] [Info]         C:\Windows\system32\bin
[4:18:04 PM] [General] [Info]         C:\Windows
[4:18:04 PM] [General] [Info]         C:\Windows\bin
[4:18:04 PM] [General] [Info]         C:\Windows\System32\Wbem
[4:18:04 PM] [General] [Info]         C:\Windows\System32\Wbem\bin
[4:18:04 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[4:18:04 PM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[4:18:04 PM] [General] [Info]         C:\Program Files\Git\cmd
[4:18:04 PM] [General] [Info]         C:\Program Files\Git\cmd\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\bin
[4:18:04 PM] [General] [Info]         C:\adb
[4:18:04 PM] [General] [Info]         C:\adb\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\system32
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\system32\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\System32\Wbem
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SystemRoot%\System32\Wbem\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\OpenSSH\
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\Documents\Project\%SYSTEMROOT%\System32\OpenSSH\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Microsoft\WindowsApps\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin
[4:18:04 PM] [General] [Info]         C:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[4:18:04 PM] [General] [Info]     Found at:
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk\bin
[4:18:04 PM] [General] [Info]     Candidate paths to be post-filtered:
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[4:18:04 PM] [General] [Info]         C:\flutter\bin\cache\dart-sdk
[4:18:04 PM] [General] [Info]     Found at C:\flutter\bin\cache\dart-sdk
[4:18:04 PM] [General] [Info]     Returning SDK path C:\flutter\bin\cache\dart-sdk for dart.exe
[4:18:04 PM] [General] [Info] Activating Flutter extension for Flutter project...
[4:18:04 PM] [General] [Info] Extension:Startup timing: 305ms
[4:18:05 PM] [General] [Info] Analyzer:Startup timing: 1030ms
[4:18:12 PM] [General] [Info] Checking 1 projects for supported platforms
[4:18:12 PM] [General] [Info] Supported platforms for the workspace are ios, android
[4:18:23 PM] [General] [Info] Analyzer:FirstAnalysis timing: 8494ms
[4:18:28 PM] [General] [Info] Starting debug session...
[4:18:28 PM] [General] [Info]     workspace: C:\Users\keshava.m\Documents\Project
[4:18:28 PM] [General] [Info] Using found common entry point: C:\Users\keshava.m\Documents\Project\lib\main.dart
[4:18:28 PM] [General] [Info] Using workspace as cwd: C:\Users\keshava.m\Documents\Project
[4:18:28 PM] [General] [Info] Detected launch project as Flutter
[4:18:28 PM] [General] [Info] Using Flutter debug adapter for this session
[4:18:28 PM] [General] [Info] Checking for errors before launching
[4:18:28 PM] [General] [Info] Spawning a new flutter debugger
[4:18:28 PM] [General] [Info] Debug session starting...
    {
        "name": "Flutter",
        "request": "launch",
        "type": "dart",
        "args": [
            "--flavor",
            "development"
        ],
        "program": "C:\\Users\\keshava.m\\Documents\\Project\\lib\\main.dart",
        "cwd": "C:\\Users\\keshava.m\\Documents\\Project",
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "C:\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe",
        "maxLogLineLength": 2000,
        "pubPath": "C:\\flutter\\bin\\cache\\dart-sdk\\bin\\pub.bat",
        "pubSnapshotPath": "C:\\flutter\\bin\\cache\\dart-sdk\\bin\\snapshots\\pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "debuggerHandlesPathsEverywhereForBreakpoints": true,
        "evaluateGettersInDebugViews": true,
        "previewDebuggerStepBack": false,
        "forceFlutterVerboseMode": false,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "C:\\flutter\\bin\\flutter.bat",
        "deviceId": "3201ac757a0b2695",
        "deviceName": "SM M205F (android-arm64)",
        "showMemoryUsage": false,
        "debugServer": 58922,
        "debuggerType": 2
    }
[4:18:28 PM] [General] [Warn] Did not find session 1f2a09cf-6409-4f2a-afa8-b1c00440ac5f to handle dart.launching. There were 0 sessions:
[4:18:28 PM] [General] [Warn] Event will be queued and processed when the session start event fires
[4:18:28 PM] [General] [Info] Processing delayed event dart.launching for session 1f2a09cf-6409-4f2a-afa8-b1c00440ac5f
[4:20:25 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensi…
[4:20:25 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensi…
[4:27:33 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensi…
[4:27:33 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensi…
[4:27:45 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensi…
[4:27:52 PM] [General] [Info] Debugger:SessionDuration timing: 563925ms (Flutter)
[4:27:52 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\keshava.m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensi…
[4:34:19 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.editGetFixes (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:290549)
	at t.FixCodeActionProvider.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:436166)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:435700
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:435445)
	at t.FixCodeActionProvider.provideCodeActions (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:436006)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441239
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441230)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440679
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440424)
	at t.RankingCodeActionProvider.provideCodeActions (c:\Users\keshava.…
[4:34:19 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.editGetAssists (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:290272)
	at t.AssistCodeActionProvider.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:397337)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:396876
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:396621)
	at t.AssistCodeActionProvider.provideCodeActions (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:397178)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441239
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:441230)
	at Generator.next (<anonymous>)
	at c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440679
	at new Promise (<anonymous>)
	at r (c:\Users\keshava.m\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:440424)
	at t.RankingCodeActionProvider.provideCodeActions (c:\Users\…
</details>  

#### Dart Version  

```
PS C:\flutter\bin\cache\dart-sdk\bin> ./dart --version
Dart VM version: 2.7.0 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"
```

**Comment by keertip** [comment] 2020-01-06 16:38
@DanTup, could you take a look? Is this analyzer related?

**Comment by DanTup** [comment] 2020-01-06 16:48
This seems like it may be the same as https://github.com/flutter/flutter/issues/46616 - from the log it seems like the analyzer may have terminated after a Flutter app was run. I've had no luck in reproducing it yet to understand what's going on.

**Comment by keertip** [comment] 2020-01-06 17:10
Thanks Danny!

**Comment by keertip** [comment] 2020-01-06 17:10
Duplicate of  flutter/flutter#46616

**Closed** 2020-01-06 17:10 UTC
Labels: area-analyzer
