### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by vietnguyen312** [dart-lang/sdk#39039] opened 2019-10-22 04:24 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#23     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3452:13)
#24     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3384:13)
#25     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4314:16)
#26     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4286:14)
#27     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#28     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#29     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#30     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#31     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#32     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#33     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#34     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#35     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#36     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#37     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#38     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#39     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#40     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#41     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#42     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#43     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#44     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3452:13)
#45     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3384:13)
#46     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4314:16)
#47     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4286:14)
#48     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#49     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#50     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#51     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#52     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#53     Parser.parseArgumentsOpt (package:front_e...
```

For additional log information, please append the contents of
file://C:\Users\nnguyen\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-10-22 04:48
Thanks for reporting this issue. This was previously discovered in fuzz testing; please follow https://github.com/dart-lang/sdk/issues/39035.

**Comment by srawlins** [comment] 2019-10-22 04:48
Duplicate of https://github.com/dart-lang/sdk/issues/39035

**Closed by srawlins** 2019-10-22 04:48 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
