### ISSUE TITLE
Encountered a Dart Analysis Server error1.

### ISSUE THREAD

**Issue by guduge** [dart-lang/sdk#36430] opened 2019-04-02 02:27 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.1 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/vl/5f81333j365dy743y4xch1yr0000gn/T/report.txt

```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: /Users/tianxiaotian/Documents/flutterLearn/flutterDemo/secondflutter_app/test/widget_test.dart context: exception_20190402_102609_075
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5464:5)
#1      TypeProviderForLink.objectType (package:analyzer/src/summary/link.dart:5429:23)
#2      ClassElementForLink_Class._computeInterfaceType (package:analyzer/src/summary/link.dart:938:67)
#3      ClassElementForLink_Class.supertype (package:analyzer/src/summary/link.dart:836:27)
#4      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:294:33)
#5      InstanceMemberInferrer._inferType (package:analyzer/src/task/strong_mode.dart:458:9)
#6      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:294:9)
#7      InstanceMemberInferrer._inferType (package:analyzer/src/task/strong_mode.dart:458:9)
#8      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:294:9)
#9      InstanceMemberInferrer._inferType (package:analyzer/src/task/strong_mode.dart:458:9)
#10     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:294:9)

**Comment by srawlins** [comment] 2019-08-29 05:52
Duplicate of #34576

**Closed by srawlins** 2019-08-29 05:52 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
