### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by ahmedgamal298** [dart-lang/sdk#39955] opened 2019-12-31 16:39 UTC
## Version information

- `IDEA IC-191.8026.42`
- `2.3.0-edge.a0290f823c53df70643a8e46bf946020d2bbe37d`
- `IC-191.8026.42, JRE 1.8.0_212-release-1586-b4x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a0290f823c53df70643a8e46bf946020d2bbe37d, server version 1.26.1, FATAL error: Failed to handle request: {id: 5937, method: edit.getFixes, params: {file: C:\Users\Gemy\Documents\GitHub\HealthyFoodApp\lib\HomePage.dart, offset: 866}, clientRequestTime: 1577810039490}
NoSuchMethodError: The method 'endsWith' was called on null.
Receiver: null
Tried calling: endsWith("es")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      DartEditBuilderImpl._getBaseNameFromUnwrappedExpression (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:869:16)
#2      DartEditBuilderImpl._getBaseNameFromExpression (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:815:12)
#3      DartEditBuilderImpl._getVariableNameSuggestionsForExpression (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:935:11)
#4      DartEditBuilderImpl._getParameterNameSuggestions (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:917:9)
#5      DartEditBuilderImpl.writeParameterMatchingArgument (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:605:11)
#6      FixProcessor._addFix_addMissingParameter.addParameter.<anonymous closure>.<anonymous closure> (package:analysis_server/src/services/correction/fix_internal.dart:886:21)
#7      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1185:41)
#8      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:312:16)
#9      DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1184:13)
#10     FixProcessor._addFix_addMissingParameter.addParameter.<anonymous closure> (package:analysis_server/src/services/correction/fix_internal.dart:884:19)
#11     DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:55:20)
#12     ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#13     DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:52:18)
#14     FixProcessor._addFix_addMissingParameter.addParameter (package:analysis_server/src/services/correction/fix_internal.dart:883:29)
<asynchronous suspension>
#15     FixProcessor._addFix_addMissingParameter (package:analysis_server/src/services/correction/fix_internal.dart:900:27)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:420:13)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#18     EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:639:46)
<asynchronous suspension>
#19     EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:741:14)
<asynchronous suspension>
#20     EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:277:32)
<asynchronous suspension>
#21     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:380:9)
#22     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#30     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#32     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#33     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41...
```

For additional log information, please append the contents of
file://C:\Users\Gemy\AppData\Local\Temp\report.txt.

**Comment by keertip** [comment] 2020-01-02 16:55
Thanks for the report. This issue has been reported previously in #39635, please follow status there.

**Comment by keertip** [comment] 2020-01-02 16:55
Duplicate of #39635

**Closed by keertip** 2020-01-02 16:55 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
