### ISSUE TITLE
Dart2js errors out when it encounters `const Map<Type, AnyThing>`

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#28337] opened 2017-01-11 16:38 UTC
When Dart2Js encounters `const Map<Type, AnyThing>`, it throws the following error:

```dart
[Error from Dart2JS on web/panel/main.dart]: packages/....dart:14:21: Const-map key type 'TypeImpl' overrides 'operator =='. @ProvideSerializers(const <Type, Type>{ Establishment: EstablishmentSerializer, Speciality: SpecialitySerializer })
```

Analyzer doesn't have a problem with it. DartVM executes the code pretty fine. source_gen and analyzer package seems to handle them pretty well.

**Comment by sigmundch** [comment] 2017-01-20 18:32
Thanks for reporting this bug, we have run into this in the past but apparently we haven't resolved it.  I agree they should be allowed. I'll close this entry to mark it as a duplicate of https://github.com/dart-lang/sdk/issues/17207.

Meanwhile, there is something you can try to work around this limitation. I believe you can define a const class like:
```dart
const TypeWrapper {
  final Type type;
  const TypeWrapper(this.type);
}
```

and use that in a key of a const-map.

Cheers!

**Closed by sigmundch** 2017-01-20 18:32 UTC
Labels: area-dart2js
