### ISSUE TITLE
AOT compilation selects imports as if dart:mirrors exists but then fails to build

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#48057] opened 2022-01-04 20:56 UTC
## Repro steps

Create a `main.dart` like so:

```dart
import 'a.dart' if (dart.library.mirrors) 'b.dart';

main() {}
```

Then create an empty `a.dart` file and a `b.dart` file with just one line `import 'dart:mirrors';`.

This results in the following error:

```
Info: Compiling with sound null safety

error: import of dart:mirrors is not supported in the current Dart runtime

Error: AOT compilation failed
Generating AOT snapshot failed!
```

## Impact

This is blocking work on the macro prototype, as we need conditional imports to work properly for AOT builds of kernel internally (see b/211377847).

**Comment by jakemac53** [comment] 2022-01-04 20:59
I can take a quick peek into fixing this as I think I have a good idea of where these variables are defined.

**Comment by a-siva** [comment] 2022-01-05 00:17
//cc @alexmarkov (I tried forcing '`dart.library.mirrors`' to false in `pkg/vm/lib/target/vm.dart` and still see `b.dart `being imported).
A print of the environment variable 
`  print(const bool.fromEnvironment("dart.library.mirrors"));
`
does print false though.

**Comment by johnniwinther** [comment] 2022-01-05 17:18
This area is generally broken (or at least potentially inconsistent) in the CFE. 

The choice made in a conditional import is based on the data found in the libraries_specification.json file, if provided. Unfortunately, when it is not provided it falls back to returning `true` on all queries. Given that the libraries specification file is only required when building the platform, it might be omitted in many cases - I don't have an overview of which, though.

The `const bool.fromEnvironment` value is based on the `environmentDefines` passed through the `CompilerOptions` so it might give a different result.

**Comment by jakemac53** [comment] 2022-01-05 17:43
Would it be possible to validate the libraries specification file and the environment agree?

**Comment by jakemac53** [comment] 2022-01-05 17:46
Fwiw this is the only libraries.json that I see, https://github.com/dart-lang/sdk/blob/main/sdk/lib/libraries.json. That only has a general entrypoint for the `vm`, and no AOT specific entry. We probably need a special one for AOT mode?

**Comment by johnniwinther** [comment] 2022-01-05 18:00
> Would it be possible to validate the libraries specification file and the environment agree?

The problem is that in the faulty scenario, the libraries specification file isn't even available, so there is nothing to check against.

> Fwiw this is the only libraries.json that I see, https://github.com/dart-lang/sdk/blob/main/sdk/lib/libraries.json. That only has a general entrypoint for the `vm`, and no AOT specific entry. We probably need a special one for AOT mode?

Yes, for the current scheme we would need a target for the AOT mode. This wouldn't solve the underlying problem of the specification file not being available, though.

**Comment by jakemac53** [comment] 2022-01-05 18:09
> The problem is that in the faulty scenario, the libraries specification file isn't even available, so there is nothing to check against.

Is there a reason we can't just fail to compile in this scenario? We know pretty much for sure the result will be incorrect?

**Comment by jakemac53** [comment] 2022-01-05 20:02
I tried adding a target which omits the mirrors library in the libraries.json, and fixed up gen_kernel.dart to also pass the libraries.json file, but I still see this issue. For reference here is a branch with the changes I tried making https://github.com/dart-lang/sdk/compare/main...jakemac53:aot-target.

**Comment by alexmarkov** [comment] 2022-01-06 16:08
Currently we have a single platform.dill file both for JIT and AOT, with the same set of libraries. `dart:mirrors` library is somewhat special because it's available in platform.dill file but cannot be used in AOT, so AOT compiler complaints about it later.

Also, currently we don't necessarily know that we're compiling something in AOT mode when the front-end is working because we have 2-step kernel generation, where the first step runs the front-end in non-AOT (or even modular) mode, and the 2nd step consumes intermediate dill file produced on the first step (or a concatenation of dill files produced on the first step) and then runs AOT-specific transformations such as TFA and tree-shaking during the 2nd step. We would need to change that if we would like to have different behavior of the front-end in AOT mode.

Another thing to consider is that we have in fact 4 different targets for the VM (`vm`, `flutter`, `dart_runner` and `flutter_runner`). If we need to introduce separate targets for AOT we will end up with 8 different targets. So maybe we can express that with `TargetFlags` instead of separate target classes.

@johnniwinther Is it possible to rely on the environment defines in the front-end when resolving conditional imports? It might be cleaner to use defines as we can specify them at the build time as we like (for example, we could have a separate define for AOT mode when building a macro library).

**Comment by jakemac53** [comment] 2022-01-06 16:49
> the first step runs the front-end in non-AOT (or even modular) mode, and the 2nd step consumes intermediate dill file produced on the first step (or a concatenation of dill files produced on the first step) and then runs AOT-specific transformations such as TFA and tree-shaking during the 2nd step.

We already handle this for other platforms, and I think even dart2js/ddc have totally different kernel files (due to different transformations). So it seems reasonable to me to not attempt to share any kernel files between AOT and JIT modes. Especially if that is the only way we can properly support the language features we claim to have...

**Comment by sigmundch** [comment] 2022-01-06 17:09
> @johnniwinther Is it possible to rely on the environment defines in the front-end when resolving conditional imports? It might be cleaner to use defines as we can specify them at the build time as we like (for example, we could have a separate define for AOT mode when building a macro library).

Small bit of historical context - we have tried to avoid using general environment variables for conditional imports to ensure we keep a known/fixed number of configurations in our build systems like blaze. Currently we have a limit of one configuration per "target". If we were to use environment variables, we'd need to be very strict about which combination of environment variables are supported, so we don't end up with an unbounded set of configurations.

In doing this, would you still be able to share .dill files, or will you anyways need to have separate .dill files with different environment definitions? If you still need separate dill files, it seems reasonable to have separate platform.dill files from the beginning.

>  Given that the libraries specification file is only required when building the platform, it might be omitted in many cases

@johnniwinther - would it be worth to do embed in the platform file the data from libraries.json, basically what @alexmarkov suggested in https://github.com/dart-lang/sdk/issues/36460 ?

Having that (and together with having extra .dill files to distinguish JIT vs AOT) would potentially also address this issue.

**Comment by alexmarkov** [comment] 2022-01-06 17:18
We won't need separate platform.dill files if we won't use those defines / conditional imports in the platform itself.
When building application we can define `dart.library.mirrors` or make conditional imports work depending on the mode even when using the same platform.dill.

@jakemac53 Do you really need to use `dart.library.mirrors` conditional import in the platform or in a separate package?

**Comment by jakemac53** [comment] 2022-01-06 17:20
> @jakemac53 Do you really need to use `dart.library.mirrors` conditional import in the platform or in a separate package?

This is for macro expansion, so it needs to be in the platform.

**Comment by jakemac53** [comment] 2022-01-06 17:31
Actually nevermind, the platform doesn't include kernel/analyzer right? So it probably doesn't need to be in the platform.

**Closed** 2022-01-11 14:53 UTC
Labels: P1, type-bug, area-front-end
