### ISSUE TITLE
Exception in flow analysis

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#38177] opened 2019-09-02 18:45 UTC
@stereotype441 

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 193.SNAPSHOT`
- `2.6.0-edge.6fa5b31fcc2bb80454a5cef040645d0f97f47651`
- `IC-193.SNAPSHOT, JRE 1.8.0_211-b12x64 Oracle Corporation, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.6fa5b31fcc2bb80454a5cef040645d0f97f47651, server version 1.27.3, error: Analysis failed: /Users/scheglov/dart/test/bin/find_primes.dart context: exception_20190902_113819_801
NoSuchMethodError: The getter 'promotedType' was called on null.
Receiver: null
Tried calling: promotedType
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FlowModel._removePromotedAll (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:1070:16)
#2      FlowModel.removePromotedAll (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:913:9)
#3      FlowAnalysis.for_conditionBegin (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:390:25)
#4      FlowAnalysisHelper.for_conditionBegin (package:analyzer/src/dart/resolver/flow_analysis_visitor.dart:157:10)
#5      ResolverVisitor.visitForStatementInScope (package:analyzer/src/generated/resolver.dart:3924:22)
#6      ScopedVisitor.visitForStatement (package:analyzer/src/generated/resolver.dart:5469:7)
#7      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4771:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#9      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#11     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#12     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5179:13)
#13     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#14     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#16     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#17     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5190:13)
#18     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3512:13)
#19     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#20     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5087:12)
#21     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#22     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#23     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5516:13)
#24     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:4035:13)
#25     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5081:49)
#26     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4940:26)
#27     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#28     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3256:59)
#29     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5509:11)
#30     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:4010:11)
#31     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5502:7)
#32     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:4001:13)
#33     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4933:49)
#34     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3598:23)
#35     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#36     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:698:10)
#37     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#38     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#39     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#40     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#41     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#42     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#43     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1260:63)
#44     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#45     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#46     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#47     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#48     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1...
```

For additional log information, please append the contents of
file:///private/var/folders/5_/801pkmkn457fzp_twzmc2g88003ky_/T/report.txt.

```
Dart analysis server, SDK version 2.6.0-edge.6fa5b31fcc2bb80454a5cef040645d0f97f47651, server version 1.27.3, error: Analysis failed: /Users/scheglov/dart/test/bin/find_primes.dart context: exception_20190902_113819_801
NoSuchMethodError: The getter 'promotedType' was called on null.
Receiver: null
Tried calling: promotedType
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FlowModel._removePromotedAll (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:1070:16)
#2      FlowModel.removePromotedAll (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:913:9)
#3      FlowAnalysis.for_conditionBegin (package:front_end/src/fasta/flow_analysis/flow_analysis.dart:390:25)
#4      FlowAnalysisHelper.for_conditionBegin (package:analyzer/src/dart/resolver/flow_analysis_visitor.dart:157:10)
#5      ResolverVisitor.visitForStatementInScope (package:analyzer/src/generated/resolver.dart:3924:22)
#6      ScopedVisitor.visitForStatement (package:analyzer/src/generated/resolver.dart:5469:7)
#7      ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4771:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7672:20)
#9      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#11     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#12     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5179:13)
#13     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#14     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#16     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#17     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5190:13)
#18     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3512:13)
#19     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#20     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5087:12)
#21     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#22     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#23     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5516:13)
#24     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:4035:13)
#25     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5081:49)
#26     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4940:26)
#27     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4272:10)
#28     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3256:59)
#29     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5509:11)
#30     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:4010:11)
#31     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5502:7)
#32     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:4001:13)
#33     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4933:49)
#34     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3598:23)
#35     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#36     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:698:10)
#37     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#38     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#39     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#40     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#41     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#42     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#43     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1260:63)
#44     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#45     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#46     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#47     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#48     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#49     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#50     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#51     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#52     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:576:21)
#53     _rootRun (dart:async/zone.dart:1124:13)
#54     _CustomZone.run (dart:async/zone.dart:1021:19)
#55     _runZoned (dart:async/zone.dart:1516:10)
#56     runZoned (dart:async/zone.dart:1463:12)
#57     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:693:12)
#58     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:574:7)
#59     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:475:9)
#60     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#61     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:470:43)
#62     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#63     new Future.sync (dart:async/future.dart:224:31)
#64     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#65     _rootRun (dart:async/zone.dart:1124:13)
#66     _CustomZone.run (dart:async/zone.dart:1021:19)
#67     _runZoned (dart:async/zone.dart:1516:10)
#68     runZoned (dart:async/zone.dart:1463:12)
#69     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#70     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#71     Driver.start (package:analysis_server/src/server/driver.dart:470:21)
#72     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:12:11)
#73     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#74     main (file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart:10:10)
#75     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
1567449499694 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4173,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/class_hierarchy_membench.dart
1567449499694 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4174,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/class_hierarchy_test.dart","i
1567449499694 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4175,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/verify_bench.dart","items":[{
1567449499694 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4176,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/round_trip_self_check.dart","
1567449499694 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4177,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/class_hierarchy_basic.dart","
1567449499695 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4178,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/round_trip.dart","items":[{"l
1567449499696 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4179,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/graph_test.dart","items":[{"l
1567449499697 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4180,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/import_table_test.dart","item
1567449499700 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4181,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/type_substitution_identity_te
1567449499702 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4182,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/verify_test.dart","items":[{"
1567449499705 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4183,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/metadata_test.dart","items":[
1567449499708 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4184,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/type_parser.dart","items":[{"
1567449499710 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4185,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/text_serializer_test.dart","i
1567449499711 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4186,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/ast_membench.dart","items":[{
1567449499712 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4187,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/serialize_bench.dart","items"
1567449499714 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4188,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/type_hashcode_quality.dart","
1567449499715 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4189,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/type_hashcode_test.dart","ite
1567449499716 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4190,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/verify_self_check.dart","item
1567449499718 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4191,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/class_hierarchy_bench.dart","
1567449499720 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4192,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/class_hierarchy_test_disabled
1567449499721 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":4193,"uri":"file:///Users/scheglov/Source/Dart/sdk.git/sdk/pkg/kernel/test/self_check_util.dart","items"
1567449499747 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/dart/test/bin/test2.dart","errors":[]}}
1567449499748 <=     +++ Compute analysis result for /Users/scheglov/dart/test/bin/find_primes.dart.
1567449499748 <=         Work in /Users/scheglov/dart/test
1567449499748 <=         +++ Prepare linked bundles.
1567449499756 <=             [librariesTotal: 8][librariesLoaded: 8][inputsTimer: 0 ms][librariesLinked: 0][librariesLinkedTimer: 0 ms][bytesGet: 1236072][bytesPut: 0]
1567449499756 <=         --- Prepare linked bundles in 8 ms.
1567449499808 <=     --- Compute analysis result for /Users/scheglov/dart/test/bin/find_primes.dart in 59 ms.
1567449499813 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/scheglov/dart/test/bin/find_primes.dart context: exception_20190902_113819_801","stackTrace":"NoSu
1567449499813 <= NOTI {"event":"server.error"}
```

```dart
main() {
  for (int i = 0; i < 20; i++) {
    var timer = new Stopwatch();
    timer.start();
    List<int> primes = findPrimes(1000000);
    timer.stop();
    print('[$i] ${timer.elapsedMilliseconds} ms.');
    primes; // print?
  }
}

List<int> findPrimes(int last) {
  List<int> primes = [];
  for (int x = 2; x < last; x++) {
    bool isPrime = true;
    for (int i = 0; i < primes.length; i++) {
      int p = primes[i];
      if (p * p > x) {
        break;
      }
      if (x % p == 0) {
        isPrime = false;
        break;
      }
    }
    if (isPrime) {
      primes.add(x);
    }
  }
  return primes;
}
```

**Comment by srawlins** [comment] 2019-09-03 07:21
Duplicate of https://github.com/dart-lang/sdk/issues/37983 perhaps?

**Comment by stereotype441** [comment] 2019-09-03 15:47
Duplicate of #37983

**Closed by stereotype441** 2019-09-03 15:47 UTC
Labels: area-analyzer
