### ISSUE TITLE
runtime constructor error??

### ISSUE THREAD

**Issue by drpond1** [dart-lang/sdk#47698] opened 2021-11-15 13:27 UTC
Perhaps I simply do not understand something.

[Using latest IntellliJ CE  running in chrome.. dart 2.12]
(currently webdev is not working for me with 2.14.4  so it is an older version)

If I do:

class ChordLike {
List\<Note\> list;
}
class Arpeggio extends ChordLike {
Arpeggio(List\<Note\> list):super(list) {
for (Note n in super.list) {
}
}

I get a runtime error at the "for" statement  saying list is not iterable,  although the chrome debugger shows it as an array of three items.   If I use list instead of super.list it works. 

  It is true super.list is not needed in the constructor call, but I do not understand the cause of the error.

**Comment by eernstg** [comment] 2021-11-15 14:38
You're using the identifier `Note` at the beginning of the `<forLoopParts>` which must be of the form `<declaredIdentifier> 'in' <expression>` or `<identifier> 'in' <expression>`, so it must be the second variant, and this means that `Note` must be a variable which is in scope (or a getter plus a setter). You probably meant `Note note in super.list`.

Next, you can't have `super(list)` in `Arpeggio`, because that is an attempt to call a constructor `ChordLike(T t)`, and there is no declaration of any such constructor. You have an implicitly induced constructor `ChordLike();` but that one does not accept a parameter.

If you add an identifier to the for-statement as described and add a constructor `ChordLike(this.list);` then the code has no compile-time errors.

I'll close this issue because it reports on behavior which is correct. Please create a new issue if other issues come up.

**Comment by drpond1** [comment] 2021-11-15 14:49
The code is very long,  so I just represented the situation.
Note is a declared class. It is irrelevant what it is.

Secondly,   in my comment it is List<Note>  but github shows it as List.   I don't know how to get github to show what I typed.  If I edit the text,  it shows what I want... it just doesn't show it to you.

The code compiles and run without error when super.list is replaced with list in the for loop.

I

**Comment by eernstg** [comment] 2021-11-15 14:58
> Note is a declared class. It is irrelevant what it is.

But it does matter whether your code says `Note in super.list` or it says `Note note in super.list`. Only the latter form declares a variable of type `Note`.

You can use triple-backquote to enclose snippets of code, and a single backquote to enclose an small term in running text, `<backquote>a.b()<backquote>`: `a.b`. You can use `<triple-backquote>dart` at the beginning of a snippet of code in order to get Dart specific highlighting.

```dart
void main() {}
```

> The code compiles and run without error when super.list is replaced with list in the for loop.

I only saw the snippet you included in this issue, but if there is no _variable_ in scope named `Note` then `Note in e` will be a compile-time error, no matter which type `e` has.

**Comment by drpond1** [comment] 2021-11-15 15:04
II am sorry about the \<  problem.   I have not encountered this before ith github.

**Comment by drpond1** [comment] 2021-11-16 16:04
Another  variation of the error is with:
super.noteList = new List\<Note\>.from(noteList.reversed);  
in the constructor.

It works as written.   But if the first noteList does not have super it does not update the super variable.
If the second variable is written with super,  it fails at runtime because the type checker cannot find information.

However,   everything works as I originally wanted it to when I use webdev  from the yaml file and directly run the webpage from the build directory.

Yet another instance of this problem occured when the pub package 
CodeMirror was being updated  for null safety about 6 months ago.   Someone else filed the issue on this.   CodemIrror now works,  but this related issue apparently is still active as of   version 2.12.2

THUS it is like the  case that:
Either the debug compilation for the web is not producing the right information or the runtime type checker isn't getting it.

So there are plenty of examples of the problem that I have seen and it is likely an  issue under some other issue number.

**Comment by drpond1** [comment] 2021-11-17 18:37
This issue belongs in something other than the  sdk.
Furthermore, it is likely an unresolved or recently resolved issue that is already being tracked.  

I have a good enough solution for my project so I will only bother to construct a complete example if its requested and I know where it should be posted.

David

**Comment by eernstg** [comment] 2021-11-17 20:02
If you encounter a situation where you think one or more language tools (like the vm or the analyzer) are not working correctly then the most effective thing you can do is to create a standalone program that demonstrates the behavior.

Here's some code that is obtained from your examples and adjusted a bit. I fixed the issues I mentioned, and the remaining code works as expected. 

```dart
class Note {
  int i;
  Note(this.i);
  String toString() => 'Note($i)';
}

class ChordLike {
  List<Note> list;
  ChordLike(this.list);
}

class Arpeggio extends ChordLike {
  Arpeggio(List<Note> list) : super(list) {
    this.list = List<Note>.from(this.list.reversed);
    for (Note n in this.list) {}
  }
}

void main() {
  print(Arpeggio([Note(1), Note(2), Note(3)]).list); // Prints '[Note(3), Note(2), Note(1)]'.
}
```

The code couldn't possibly be as shown [here](https://github.com/dart-lang/sdk/issues/47698#issue-1053666913), because there is no constructor in `ChordLike` accepting a single parameter (and `super(list)` is an invocation of a such a constructor).

But perhaps the real issue was that you used `super.list` in the body of the constructor rather than `this.list`? You can't access the instance variable by using `list`, because there is a constructor parameter with the same name, and that's in a scope which is encountered on the way out to the body scope of the class (so the parameter shadows the instance variable). When that happens, you should use `this.list` (or just give that parameter a different name).

You can use `super.list` in this particular example, but as I explained, that's likely to become a bug as your program gets developed and grows.

In any case, please use complete, runnable code to illustrate any language issues that you encounter!

**Comment by drpond1** [comment] 2021-11-17 22:52
I have not yet heard back on my problem with getting the current version of Dart sdk to work.  (I posted this to webdev)  .   So I can't construct an up to date working example.    (One bit of good news,  is that the versioning system made it incredibly easy to roll the system back to a good state.   )

The issue of this thread has been discussed in other contexts.   I am not even sure you need yet another example to work on.    Code that works with build,  may cause run-time type checking errors with dev-debug.   I have tried to locate  this as a specific issue,  but did not find it.

I am willing to produce an example of the behaviour with super using the sdk 2.12.2 if you want.  I don't need any help getting things to work for my project  (the system plays up and down arpeggio's just fine).  It is just a case of what I should provide for you.   You might not need need another example, you may prefer me to wait to use an up to date version of the sdk, or you might want something now.
 I will follow your preference.

**Comment by eernstg** [comment] 2021-11-18 11:08
> I can't construct an up to date working example

If there is a bug in the implementation of the language as such then it's rarely necessary to have more than a handful of lines to create a situation where it arises.

> The issue of this thread has been discussed in other contexts. I am not even
> sure you need yet another example to work on.

If you wish to report a behavior which is already reported as a github issue (on this repository, or on the Dart language repository), then it's better if you add a comment to that other issue, rather than creating a new issue.

So far I haven't seen any actual bugs reported in this issue, everything is working as expected (which is also the reason why I closed it). But we do need an example that actually demonstrates something&mdash;currently there is no evidence suggesting that there is a problem at all.

> Code that works with build, may cause run-time type checking errors with dev-debug

The dart2js compiler has various settings and it is possible to turn off a number of run-time checks. This could create a situation where different compilations do respectively do not perform a check that causes this run-time error to arise. Also if DDC is used for development there could be inconsistencies in the compilation performed by DDC and the compilation performed by dart2js. If you encounter concrete issues of this nature then it would be very helpful if you could report them as an issue. But the information available in this issue is far from being sufficiently specific and complete to allow anyone to explore the issue and try to resolve it.

Sorry about being a bit harsh here, but you really need to be much more specific if you want anyone to do actual work on anything. ;-)

**Comment by drpond1** [comment] 2021-11-18 22:05
I was wrong.  My code is actually not yet correct.   
Here is  what I have so far.

```

/  Test example for DART team
//unused global for motivating the user of super
List<int> thePitches=[];
// for showing how super works for teseting
abstract class ChordLikeTest {
  List<int> thePitches;
  ChordLikeTest(this.thePitches);
}
// sort of an arpeggio class for testin
// lots of dead code,  because use the same code
// for different cases.
class ArpeggioTest extends ChordLikeTest {


  ArpeggioTest(int version, List<int> pitches)
      : super(pitches) {
    //Expect pitch list to start with middle C for testing
    //  of lenth 2.
    try {
      if ((pitches.length != 3) || (pitches[0] != 60)) {
        print("invalid test example");
      }
      print("Version Test: $version");
      bool up = true;
      //Version 1 -- desired  code for up
      if (version == 1) {
        up = true;
        if (!up) {
          super.thePitches = new List<int>.from(super.thePitches.reversed);
        }
        // this code was for adjusting articulations.
        //   Here just do something non-tirival
        int index = -1;
        for (int i in super.thePitches) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok:");
      } else
        // version 2  desired code for down
      if (version == 2) {
        up = false;
        if (!up) {
          super.thePitches = new List<int>.from(super.thePitches.reversed);
        }

        // this code was for adjusting articulations.
        //   Here just do something non-tirival
        int index = -1;
        for (int i in super.thePitches) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok:");
      } else
        //version  still not fixed
      if (version == 3) {
        up = false;
        List<int> temp=super.thePitches;
        if (!up) {
          temp = new List<int>.from(temp);
        }
        super.thePitches =temp;
        // this code was for adjusting articulations.
        //   Here just do something non-tirival

        int index = -1;
        for (int i in temp) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok:");
      } else
        // version  not fixed
      if (version == 4) {
        up = false;
        if (!up) {
          super.thePitches = new List<int>.from(thePitches.reversed);
        }
        // this code was for adjusting articulations.
        //   Here just do something non-tirival
        int index = -1;
        for (int i in super.thePitches) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok:");
      }
    } catch(e) {
      print('$e');
    }
  }
  exec() {

  }

  }

void main() {
  print('Using DrPond Version 0.132+11.18.21');
  // for producing output for DART team
  new ArpeggioTest(1,[60,64,67]);
  new ArpeggioTest(2,[60,64,67]);
  new ArpeggioTest(3,[60,64,67]);
  new ArpeggioTest(4,[60,64,67]);
}

output is:

Version Test: 1
js_primitives.dart:30 TypeError: this[thePitches] is not iterable
js_primitives.dart:30 Version Test: 2
js_primitives.dart:30 TypeError: Cannot read properties of undefined (reading 'Symbol(dartx.reversed)')
js_primitives.dart:30 Version Test: 3
js_primitives.dart:30 TypeError: elements is not iterable
js_primitives.dart:30 Version Test: 4
js_primitives.dart:30 TypeError: this[thePitches] is not iterable

```

```

**Comment by eernstg** [comment] 2021-11-19 10:54
Running the example now, I get the following output:

```
Using DrPond Version 0.132+11.18.21
Version Test: 1
ordered correctly true:
Version Test: 2
ordered correctly true:
Version Test: 3
ordered correctly false:
Version Test: 4
ordered correctly false:
```

Here's a slightly adjusted version of the program (just changing a couple of things that looked like a bug, and including the list in the output). It prints `true` in all tests:

```dart
//unused global for motivating the user of super [changed to `this`]
List<int> thePitches = [];

// for showing how super works for testing
abstract class ChordLikeTest {
  List<int> thePitches;
  ChordLikeTest(this.thePitches);
}

// sort of an arpeggio class for testing
// lots of dead code,  because use the same code
// for different cases.
class ArpeggioTest extends ChordLikeTest {
  ArpeggioTest(int version, List<int> pitches) : super(pitches) {
    //Expect pitch list to start with middle C for testing
    //  of lenth 2.
    try {
      if ((pitches.length != 3) || (pitches[0] != 60)) {
        print("invalid test example");
      }
      print("Version Test: $version");
      bool up = true;
      //Version 1 -- desired  code for up
      if (version == 1) {
        up = true;
        if (!up) {
          super.thePitches = new List<int>.from(super.thePitches.reversed);
        }
        // this code was for adjusting articulations.
        //   Here just do something non-tirival
        int index = -1;
        for (int i in super.thePitches) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok: ${super.thePitches}");
      } else
      // version 2  desired code for down
      if (version == 2) {
        up = false;
        if (!up) {
          super.thePitches = new List<int>.from(super.thePitches.reversed);
        }

        // this code was for adjusting articulations.
        //   Here just do something non-tirival
        int index = -1;
        for (int i in super.thePitches) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok: ${super.thePitches}");
      } else
      //version  still not fixed
      if (version == 3) {
        up = true; // Changed false --> true, isn't that the intention?
        List<int> temp = super.thePitches;
        if (!up) {
          temp = new List<int>.from(temp);
        }
        super.thePitches = temp;
        // this code was for adjusting articulations.
        //   Here just do something non-trivial

        int index = -1;
        for (int i in temp) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok: ${super.thePitches}");
      } else
      // version  not fixed
      if (version == 4) {
        up = false;
        if (!up) {
          super.thePitches = new List<int>.from(super.thePitches.reversed);
        }
        // this code was for adjusting articulations.
        //   Here just do something non-tirival
        int index = -1;
        for (int i in super.thePitches) {
          index++;
          if (i == 60) {
            break;
          }
        }
        bool ok = (up) ? index == 0 : index == 2;
        print("ordered correctly $ok: ${super.thePitches}");
      }
    } catch (e) {
      print('$e');
    }
  }
  exec() {}
}

void main() {
  print('Using DrPond Version 0.132+11.18.21');
  // for producing output for DART team
  new ArpeggioTest(1, [60, 64, 67]);
  new ArpeggioTest(2, [60, 64, 67]);
  new ArpeggioTest(3, [60, 64, 67]);
  new ArpeggioTest(4, [60, 64, 67]);
}
```

However, I would still **strongly recommend avoiding the use of `super` in locations where it is not justified**. That is, the program should use `this.thePitches` to access the instance variable `thePitches` rather than `super.thePitches`. I tried to perform that change as well, and the resulting program still prints true in all tests, as expected. That's how it should be.

The use of `super` is a very special mechanism which is intended to _violate_ object-oriented method dispatch: It specifies that the lookup for this particular method call should ignore the actual run-time type of `this`, and instead search through the list of superclasses of the enclosing class declaration (which is known statically), and then it should call the method implementation which is found as the first one with the right name in that list of superclasses.

It makes sense to call `super.m(...)` in a method `m` if you intend to implement the method `m` by "doing whatever my superclass  does already" as part of the implementation of `m` in the current class. But it is very rarely meaningful to call `super.m` anywhere outside the implementation of `m` in the current class.

For example, if you try to call `super.thePitches` _anywhere_ in `ArpeggioTest` which is not inside a declaration of a getter named `thePitches` that overrides the getter of the variable in `ChordLikeTest` then you should immediately know that it's wrong (or, at least, it is one of those very rare situations where this kind of thing is actually meaningful, for some twisted reason).

**Comment by drpond1** [comment] 2021-11-19 14:24
.1.   'corrrections'
a. version 3 was supposed to be the fixed version and I only discovered a problem after I started posting it.    However,  i used up=false  in order to execute more of the code.    The error occurs with the for-loop not the  list reversing.
b.   super.thePitches = new List\<int\>.from(thePitches.reversed) worked.
    so that correlation is not "right" for versions 3 and 4 which are supposed to point out problems with the for loop.   
   My application does play up and down arpeggios with this coding
  (I used a different incorrect instance of the for-loop code that does
     not use the reversed list.
    You have supplied a correction that will work).
   
The example is for you,  so you can change it  however you like.

2.   I used super,  because the implicit getter and setters seem to naturally belong with the superclass.       I had a misconception about how super worked in DART and did not expect your explanation.   ( For other languages without the lexical scoping rules that could cause access of globals,  I have simply used "a" instead of "super.a" or "this.a" when there was no class ambiguity,  )
 I  will update my code.

3.  Thank you for providing the explanation.  

4.  There is still the issue of the runtime errors for the debug version of the compiler.

**Comment by eernstg** [comment] 2021-11-19 18:06
Thank you!

> b. `super.thePitches = new List<int>.from(thePitches.reversed)` worked.
> so that correction is not "right" for versions 3 and 4 which are supposed
> to point out problems with the for loop.

Do you really mean to use the top level variable (the empty list), reversed, to set the instance variable `thePitches`? In any case, iterating over an empty list shouldn't be a problem for a `for` loop.

I guess the 

> debug version of the compiler 

would be DDC, but I cannot see any run-time errors (with `dart`, with `dart2js`, or with DDC). There may be a bug in an older version of DDC, but they will not be fixed (Dart does not have branches where older versions receive bug fixes, you need to use a newer version).

In any case, I think the [webdev issue tracker](https://github.com/dart-lang/webdev/issues) is the best place to proceed with this, possibly by adding more concrete information to the issue on webdev that you mentioned earlier.

**Comment by drpond1** [comment] 2021-11-19 20:59
1.   I added in the global definition at some point to clarify why i was using super.   I just removed it from the test case and I get the same output.    
Since the the type definition is not iterable at runtime in both cases, there is no output difference.    So it doesn't matter if the list is empty or not.  

(Originally,  example 3 was supposed to be the fixed example... but it was not fixed.  I changed versions 3 and 4 to typing problems with the for loop.)

2. There is no reason to post anything on a new thread if it works with the updated DDC compiler.     I cannot find any reference to the previous issues on github.
 So currently the issue is truly closed.

3.  Thanks again for your help.

**Comment by drpond1** [comment] 2021-11-19 22:32
A little late,  but I now remember that I discovered that List was not iterable because  it  did not implement all of the methods for Iterable.    At least I think this was the case.
Not really sure what caused the error to appear in only some cases.
  I guess this got fixed.

**Comment by eernstg** [comment] 2021-11-22 17:33
@drpond1, in order to make progress on webdev issues, please report them on the webdev repo! (I'm working on the language as such, not on any particular tool, but the folks who know about webdev would see it there.)

**Comment by annagrin** [comment] 2021-11-29 21:05
There are compilation errors in the code so I wouldn't expect it to work correctly at runtime. Anyway, after I fixed the compilation errors, minimized the sample, the behavior is still strange - looks like a ddc bug:

*code*
```
abstract class ChordLikeTest {
  List<int> thePitches;
  ChordLikeTest(this.thePitches);
}
// sort of an arpeggio class for testing
// lots of dead code,  because use the same code
// for different cases.
class ArpeggioTest extends ChordLikeTest {

  ArpeggioTest(List<int> pitches)
      : super(pitches) {
    try {
      super.thePitches = List<int>.from(thePitches.reversed);

        // this code was for adjusting articulations.
        //   Here just do something non-tirival
        var index = -1;
        for (var i in super.thePitches) {
          index++;
          if (i == 60) {
            break;
          }
        }
        var ok  = index == 2;
        print('ordered correctly $ok:"');
    } catch(e) {
      print('$e');
    }
  }
 }

void main() {
  print('Using DrPond Version 0.132+11.18.21');
  ArpeggioTest(<int>[60,64,67]);
}
```

*Results using ddc*
```
Using DrPond Version 0.132+11.18.21
TypeError: this[thePitches] is not iterable
Lost connection to device.
```

*Results using VM*

```Using DrPond Version 0.132+11.18.21
ordered correctly true:"
```

This is not related to webdev, so I am reopening this bug.
/cc @nshahan

**Comment by annagrin** [comment] 2021-11-29 21:51
Just a note, in case it is helpful - seems like the issue is caused by the following statement (commenting it out does not show the bug)

```dart
super.thePitches = List<int>.from(thePitches.reversed);
```

**Comment by eernstg** [comment] 2021-11-29 23:57
Interesting! I don't get any errors with this configuration and the program from [here](https://github.com/dart-lang/sdk/issues/47698#issuecomment-982022069), at commit 9c8f51f538f3f3a56873f43c0f610176f0315776:

```
> python3 tools/test.py --host-checked -mrelease -cdartdevk -t960 -j32 language/scratch_test
Test configuration:
    custom-configuration-1(architecture: x64, compiler: dartdevk, mode: release, runtime: chrome, system: linux, timeout: 960, host-checked)
Suites tested: language
[00:09 | 100% | +    1 | -    0]

=== All 1 test passed ===
```

**Comment by nshahan** [comment] 2021-11-30 00:22
@drpond1 Thanks for filing the issue! This was a confusing one to reproduce and diagnose. I see there is definitely a bug in the way DDC compiles getters and setters for use by super calls in a constructor. It looks like the compiler is failing to recognize that we need to add the getter and setter combination. Instead whichever one is used in the constructor first will be available but the other isn't. 

1) Missing setter in the compiled Javascript code:
```dart
class A {
  int i;
  A(this.i);
}

class B extends A {
  B(int val) : super(val) {
    print(super.i);
    super.i = 99; // Boom! Missing setter.
  }
}

void main() {
  B(2);
}
```

2) Missing getter in the compiled Javascript code:

```dart
class A {
  int i;
  A(this.i);
}

class C extends A {
  C(int val) : super(val) {
    super.i = 99;
    print(super.i); // Silent boom. Missing getter but returns undefined/null.
    print(super.i.isEven); // Boom! "Cannot read properties of undefined"
  }
}

void main() {
  C(2);
}
```

I recently touched some code that detects these when we need to compile super getters and setters when applying mixins https://github.com/dart-lang/sdk/commit/5b3cadc7e6d7be94ef959e3733357980ff69c684 so I'm familiar with our approach. I'll work on a fix.

**Closed** 2021-12-02 22:14 UTC
Labels: web-dev-compiler, area-web

**Comment by annagrin** [comment] 2021-12-03 21:49
> Interesting! I don't get any errors with this configuration and the program from [here](https://github.com/dart-lang/sdk/issues/47698#issuecomment-982022069), at commit [9c8f51f](https://github.com/dart-lang/sdk/commit/9c8f51f538f3f3a56873f43c0f610176f0315776):

I am not really familiar with how the  test.py works - Does it run the program in chrome, and how does it check that the execution didn't produce any exceptions (they would show in chrome console)? Could it be some silent failure? 

I just run the program in chrome using webdev and VScode.

**Comment by nshahan** [comment] 2021-12-03 22:13
> I am not really familiar with how the test.py works - Does it run the program in chrome, and how does it check that the execution didn't produce any exceptions (they would show in chrome console)?

The test.py script does run tests for that configuration in chrome and if exceptions bubble up they will be reported as test failures. In this case the code catches the exception and just prints something. I suspect this was an issue with interpreting what is correct expected behavior from the provided example code.

I did add regression tests that you can see failed in DDC (running with test.py) and have since been fixed.
https://dart-review.googlesource.com/c/sdk/+/221742

**Comment by eernstg** [comment] 2021-12-04 11:25
Great, thanks! Sorry about more or less derailing this issue along the way. 😄
