### ISSUE TITLE
Null-aware conditional return value inconsitency

### ISSUE THREAD

**Issue by meMuszr** [dart-lang/sdk#33526] opened 2018-06-20 16:50 UTC
Dart SDK 2.0.0-dev.63.0 / MacOSX / Firefox Developer Edition
[demo](https://dartpad.dartlang.org/0ac9412aad3d34898b98aaf34c1a65ba)
Properly evaluates for a `null` String but generates unexpected result on a String with value.

**Comment by sigmundch** [comment] 2018-06-26 16:55
@meMuszr - just to make sure I understand. Do you believe the problem is that 
```
  print(testObj?.TestPopulatedString?.length ?? 0 > 0);  
```

prints 17 instead of printing "true"?

I believe this is actually intended, the issue is that the ?? operator has lower precedence than >, so by default `x?.y?.length ?? 0 > 0` is interpreted as `x?.y?.length ?? (0 > 0)`. 

We have the same semantics in other runtimes (e.g. on the VM).

I'm tentatively closing this bug assuming this is the case, but if I misunderstood the bug, please reopen and let me know.

**Closed by sigmundch** 2018-06-26 16:55 UTC
Labels: area-dart2js
