### ISSUE TITLE
Occasionally can't refresh

### ISSUE THREAD

**Issue by EightMinuteYouth** [dart-lang/sdk#37524] opened 2019-07-13 04:03 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.5.0-edge.09fc76bc51274e91b76d8a9030a236a678311392`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.09fc76bc51274e91b76d8a9030a236a678311392, server version 1.27.1, error: Captured exception
Can't find ')' to match '('.
#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:75:24)
#1      _withArgumentsExpectedIdentifier (package:front_end/src/fasta/fasta_codes_generated.dart:3145:25)
#2      Parser.reportRecoverableErrorWithToken (package:front_end/src/fasta/parser/parser.dart:6367:18)
#3      ExpressionIdentifierContext.ensureIdentifier (package:front_end/src/fasta/parser/identifier_context_impl.dart:292:12)
#4      Parser.ensureIdentifier (package:front_end/src/fasta/parser/parser.dart:2167:28)
#5      Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4929:32)
#6      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4300:12)
#7      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4182:12)
#8      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3970:13)
#9      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3942:13)
#10     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3907:13)
#11     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5304:16)
#12     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5215:12)
#13     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3812:14)
#14     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3714:20)
#15     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3619:15)
#16     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3267:15)
#17     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3128:15)
#18     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2904:15)
#19     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1795:13)
#20     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1755:14)
#21     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#22     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#23     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#24     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#25     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#26     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#27     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#28     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:642:10)
#29     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#30     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2168:35)
<asynchronous suspension>
#32     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#33     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#34     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#35     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#36     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#42     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#43     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#44     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#45     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#46     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#47     new Future.sync (dart:async/future.dart:224:31)
#48     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#49     _rootRun (dart:async/zone.dart:1124:13)
#50     _CustomZone.run (dart:async/zone.dart:1021:19)
#51     _runZoned (dart:async/zone.dart:1516:10)
#52     runZoned (dart:async/zone.dart:1463:12)
#53     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#54     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#55     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#56     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#57     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#58     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#59     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/m9/0_dplgcj1q780jctqpc9tvz80000gn/T/report.txt.

**Comment by kevmoo** [comment] 2019-07-18 17:09
Duplicate of https://github.com/dart-lang/sdk/issues/37491

**Closed by kevmoo** 2019-07-18 17:09 UTC
Labels: area-analyzer
