### ISSUE TITLE
Bug in DateTime operations

### ISSUE THREAD

**Issue by erichorlait** [dart-lang/sdk#51818] opened 2023-03-22 15:13 UTC
Adding one day to a DateTime return incorrect information. The code to reproduce:

`void main() {
  DateTime dt = DateTime.now();
  
  DateTime debut = DateTime(dt.year, dt.month, dt.day, 22, 0);
  
  for (int i=0; i<10; i++) {
    debut = debut.add(Duration(days:1));
    print("$debut");
  }
}`

The result obtained:

`2023-03-23 22:00:00.000
2023-03-24 22:00:00.000
2023-03-25 22:00:00.000
2023-03-26 23:00:00.000
2023-03-27 23:00:00.000
2023-03-28 23:00:00.000
2023-03-29 23:00:00.000
2023-03-30 23:00:00.000
2023-03-31 23:00:00.000
2023-04-01 23:00:00.000`

**Comment by julemand101** [comment] 2023-03-22 16:00
Please read the documentation: https://api.dart.dev/stable/2.19.5/dart-core/DateTime/add.html
```dart
final today = DateTime.now();
final fiftyDaysFromNow = today.add(const Duration(days: 50));
```
> Notice that the duration being added is actually 50 * 24 * 60 * 60 seconds. If the resulting DateTime has a different daylight saving offset than this, then the result won't have the same time-of-day as this, and may not even hit the calendar date 50 days later.
>
> Be careful when working with dates in local time.

In short, what your code is doing is adding 24 hours to the `debut` date but since `debut` is based on localtime, it is getting hit by DST (Daylight Saving Time) which makes one of the day to have another length than 24 hours.

In general, you should work with `DateTime` objects in DST which is not affected by DST.

**Comment by julemand101** [comment] 2023-03-22 16:02
Duplicate of: https://github.com/dart-lang/sdk/issues/37449

**Closed** 2023-03-22 16:14 UTC
