### ISSUE TITLE
Pausing debugger when not in user-code and then clicking Resume/Step causes program to terminate

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#30240] opened 2017-07-23 11:28 UTC
Given the following program:

```dart
import 'dart:async';

main() async {
  while (true) {
    print("Hello, world!");
    await new Future.delayed(new Duration(seconds: 1));
  }
}
```

If I start running and then `Pause` the debugger (which will very likely pause outside of my own code) and then `Resume` the process terminates.

Output (the `Exited` line is added by me with the error code from the process).

```text
Hello, world!
Hello, world!
Hello, world!
Hello, world!
Hello, world!
Exited (3221225477)
```

Here's the log from Observatory:

```text
[12:21:32]: ==> {"id":"21","method":"pause","params":{"isolateId":"isolates/404148052"}}
[12:21:32]: <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"21"}
[12:21:32]: <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseInterrupted","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/404148052","name":"main.dart$main","number":"404148052"},"timestamp":1500808892642}}}
[12:21:32]: ==> {"id":"22","method":"getStack","params":{"isolateId":"isolates/404148052"}}
[12:21:32]: <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[],"messages":[]},"id":"22"}
[12:21:32]: ==> {"id":"23","method":"getStack","params":{"isolateId":"isolates/404148052"}}
[12:21:32]: <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[],"messages":[]},"id":"23"}
[12:21:35]: ==> {"id":"24","method":"resume","params":{"isolateId":"isolates/404148052","step":"Over"}}
[12:21:35]: <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"24"}
[12:21:35]: <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/404148052","name":"main.dart$main","number":"404148052"},"timestamp":1500808895998}}}
```

**Comment by sivachandra** [comment] 2017-07-31 09:34
I am unable to reproduce with ToT SDK. This is what I am doing:

1. dart --observe hello_world.dart # hello_world.dart has the code as in the OP
2. On observatory UI, I am clicking "Pause Isolate".
3. When the isolate pauses, I am typing "continue" in the command box. This successfully resumes the isolate.

@DanTup - If you are following a different set of steps, can you please list them here. Also, the subject line says "when not in user-code". How did you deduce this?

**Comment by sivachandra** [comment] 2017-07-31 09:36
One more question: which version of the SDK are you using?

**Comment by DanTup** [comment] 2017-07-31 09:54
@sivachandra Sorry, I just re-tested this and it only occurs when I sent a Step Over, not when I just resume.

> Also, the subject line says "when not in user-code". How did you deduce this?

The code is only running every second, so in order to break in my code I'd have to time things really well. I'm just hitting Pause after a print, so when there's almost a second before it's back in my code. Additionally, the Call Stack doesn't show anything (which seems strange, I'm sure when I raised this it just showed a load of framework stuff - that might be my bug though) but it does show if I stop inside my code (eg. using a breakpoint).

I'll see if I can repro using Observatory directly and post back.

**Comment by DanTup** [comment] 2017-07-31 09:55
Oh, and I'm using latest stable SDK today (v1.24.2).

**Comment by DanTup** [comment] 2017-07-31 10:01
I can't repro using break/step in the Observatory web app so I'll have to do some digging to find out how what I'm doing it different (apologies for not trying this in the first place!).

**Comment by sivachandra** [comment] 2017-07-31 10:06
I am able to reproduce the VM crash if I replace "continue" with "step" in step #3 of what I am doing (see above). I think that is a bug good enough :)

**Comment by DanTup** [comment] 2017-07-31 10:12
Great, the saves me some effort! I'm not sure why I can't repro it via the web app, it seems to pause fine (and show no stack - which I guess is why I see the same in Dart Code) but when I stepped, it just moved back into `main`.

![Pause](https://user-images.githubusercontent.com/1078012/28773335-0c08f3e4-75e1-11e7-9177-37bd8fdde394.png)

Could just be timing; but as long as you can repro I guess you can fix. Thanks!

**Comment by DanTup** [comment] 2017-07-31 10:13
I'm also slightly confused why it says it's now paused at 3:5; surely it should be inside the while loop?

**Comment by sivachandra** [comment] 2017-08-28 11:12
This issue has been fixed on ToT but I am not sure it is available in a dev release yet.

**Closed by sivachandra** 2017-08-28 11:12 UTC
Labels: area-observatory, area-vm
