### ISSUE TITLE
static List variable is passing reference;

### ISSUE THREAD

**Issue by vinaykumarrock986612** [dart-lang/sdk#50037] opened 2022-09-23 06:35 UTC
Dart SDK: 2.18.1

```
class Test{
  static List<List<bool>> data = [
    [false, false],
    [false, false],
  ];
}

void main(){
  var foo = Test.data;
  foo[0][0] = true;
  
  print(foo);
  print(Test.data); // Supposed to print everthing false
} 
```

Expected output:
[[true, false], [false, false]]
[[false, false], [false, false]]

Results:
[[true, false], [false, false]]
[[true, false], [false, false]]

When you assign a static variable to a local variable, it is passing thatreference of the static variable.

**Comment by vinaykumarrock986612** [comment] 2022-09-23 06:37
![Screenshot 2022-09-23 120706](https://user-images.githubusercontent.com/58293111/191904476-2ba7f06a-e8aa-42d3-a872-f58b3273062b.png)

**Comment by eernstg** [comment] 2022-09-23 07:47
This is working as intended: Every expression in Dart that evaluates to an object will actually yield a reference to said object rather than a copy. (For simple things like `int` you may get things like an SMI, a 'small integer', which is an inlined version of this scenario. But the semantics is still the same. E.g., you don't need to "box" the `int` when you assign it to a variable of type `Object`, it already works as a proper reference even though it's inlined, because it is an object that has no state.)

Languages like C and C++ that enable-and-require developers to keep track of allocation details typically support direct as well as indirect access (indirect: use a pointer or a reference, `int *pi;` or `int &i;`, direct: use the underlying type directly), but most mainstream imperative/OO languages use indirect access (references).

Swift uses a kind of copy-on-write for certain kinds of objects (collections, in particular), but I don't think any other language does a similar thing.

So it shouldn't be a surprise, and it is certainly intended, that expressions in Dart yield a reference, and subsequent updates to an object will be visible for all references to that object.

**Closed by eernstg** 2022-09-23 07:47 UTC
Labels: closed-as-intended
