### ISSUE TITLE
Analyzer crashing on WebStorm IDEA WS-171.3780.79

### ISSUE THREAD

**Issue by avstudios** [dart-lang/sdk#29212] opened 2017-03-31 13:48 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 2560x1440`

#

**Comment by devoncarew** [comment] 2017-03-31 16:38
@avstudios, do you have any more info? These crash reports often contain a stack trace.

**Comment by avstudios** [comment] 2017-04-10 13:39
If I click a link I have this:
```
Analyzer%20Feedback%20from%20IntelliJ%0A%0A%23%23%20Version%20information%0A%0A-%20%60IDEA%20WS-171.3780.79%60%0A-%20%601.22.1%60%0A-%20%60WS-171.3780.79,%20JRE%201.8.0_112-release-736-b13x64%20JetBrains%20s.r.o,%20OS%20Mac%20OS%20X(x86_64)%20v10.11.6%20unknown,%20screens%202560x1440%60%0A%0A%23%23%20Exception%0A%0APlease%20append%20the%20contents%20of:%0Afile:///private/var/folders/1q/1gx3tc2d677_49ykbsv4xrfr0000gn/T/report.txt%0A%0A%60%60%60%0ADart%20analysis%20server,%20SDK%20version%201.22.1,%20server%20version%201.17.0,%20error:%20Task%20failed:%20GatherUsedLocalElementsTask%20for%20source%20/Users/marcinsydor/Repos/questgame/lib/components/game/game_component.dart%0AUnexpected%20exception%20while%20performing%20GatherUsedLocalElementsTask%20for%20source%20/Users/marcinsydor/Repos/questgame/lib/components/game/game_component.dart%0A%230%20%20%20%20%20%20AnalysisTask._safelyPerform%20(package:analyzer/task/model.dart:333)%0A%231%20%20%20%20%20%20AnalysisTask.perform%20(package:analyzer/task/model.dart:220)%0A%232%20%20%20%20%20%20AnalysisDriver.performWorkItem%20(package:analyzer/src/task/driver.dart:284)%0A%233%20%20%20%20%20%20AnalysisDriver.performAnalysisTask%20(package:analyzer/src/task/driver.dart:255)%0A%234%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask.%3Canonymous%20closure%3E%20(package:analyzer/src/context/context.dart:1199)%0A%235%20%20%20%20%20%20_PerformanceTagImpl.makeCurrentWhile%20(package:analyzer/src/generated/utilities_general.dart:189)%0A%236%20%20%20%20%20%20AnalysisContextImpl.performAnalysisTask%20(package:analyzer/src/context/context.dart:1197)%0A%237%20%20%20%20%20%20PerformAnalysisOperation.perform%20(package:analysis_server/src/operation/operation_analysis.dart:369)%0A%238%20%20%20%20%20%20AnalysisServer.performOperation%20(package:analysis_server/src/analysis_server.dart:997)%0A%239%20%20%20%20%20%20Future.Future.%3Canonymous%20closure%3E%20(dart:async/future.dart:158)%0A%2310%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1146)%0A%2311%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2312%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2313%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2314%20%20%20%20%20_rootRun%20(dart:async/zone.dart:1150)%0A%2315%20%20%20%20%20_CustomZone.run%20(dart:async/zone.dart:1026)%0A%2316%20%20%20%20%20_CustomZone.runGuarded%20(dart:async/zone.dart:924)%0A%2317%20%20%20%20%20_CustomZone.bindCallback.%3Canonymous%20closure%3E%20(dart:async/zone.dart:951)%0A%2318%20%20%20%20%20Timer._createTimer.%3Canonymous%20closure%3E%20(dart:async-patch/timer_patch.dart:16)%0A%2319%20%20%20%20%20_Timer._runTimers%20(dart:isolate-patch/timer_impl.dart:385)%0A%2320%20%20%20%20%20_Timer._handleMessage%20(dart:isolate-patch/timer_impl.dart:414)%0A%2321%20%20%20%20%20_RawReceivePortImpl._handleMessage%20(dart:isolate-patch/isolate_patch.dart:148)%0A%0ACaused%20by%20Bad%20state:%20Unable%20to%20find%20(String%20id,%20PersonData%20personData)%20→%20Null%20in%20[(null%20id,%20null%20personData)%20→%20dynamic]%0A%230%20%20%20%20%20%20ElementImpl.findElementIndexUsingIdentical%20(package:analyzer/src/dart/element/element.dart:3162)%0A%231%20%20%20%20%20%20FunctionElementImpl.identifier%20(package:analyzer/src/dart/element/element.dart:4425)%0A%232%20%20%20%20%20%20ElementLocationImpl.ElementLocationImpl.con1%20(package:analyzer/src/dart/element/element.dart:3202)%0A%233%20%20%20%20%20%20ElementImpl.location%20(package:analyzer/src/dart/element/element.dart:2920)%0A%234%20%20%20%20%20%20ElementImpl.hashCode%20(package:analyzer/src/dart/element/element.dart:2809)%0A%235%20%20%20%20%20%20_HashSet._hashCode%20(dart:collection-patch/collection_patch.dart:564)%0A%236%20%20%20%20%20%20_HashSet.add%20(dart:collection-patch/collection_patch.dart:600)%0A%237%20%20%20%20%20%20UsedLocalElements.addElement%20(package:analyzer/src/generated/resolver.dart:10562)%0A%238%20%20%20%20%20%20GatherUsedLocalElementsVisitor.visitFunctionExpression%20(package:analyzer/src/generated/resolver.dart:3522)%0A%239%20%20%20%20%20%20FunctionExpressionImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:5347)%0A%2310%20%20%20%20%20NodeListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:8044)%0A%2311%20%20%20%20%20ArgumentListImpl.visitChildren%20(package:analyzer/src/dart/ast/ast.dart:431)%0A%2312%20%20%20%20%20RecursiveAstVisitor.visitArgumentList%20(package:analyzer/dart/ast/visitor.dart:605)%0A%2313%20%20%20%20%20ArgumentListImpl.accept%20(package:analyzer/src/dart/ast/ast.dart:427)%0A%2314%20%20%20%20%20MethodInvocationImpl.visitChildren%20(package:analyzer/src/dart/ast/ast.dart:7656)%0A%2315%20%20%20%20%20RecursiveAstVisitor.visitMethodInvocation%20(package:analyzer/dart/ast/visitor.dart:1013)%0A#16%20%20%20%20%20MethodInvocationImpl
```
Does it help?

**Comment by bwilkerson** [comment] 2017-04-10 13:54
@stevemessick Another example of a URL that didn't correctly populate the issue.

**Comment by devoncarew** [comment] 2017-04-10 14:08
url decoded, that's:

## Version information

- `IDEA WS-171.3780.79`
- `1.22.1`
- `WS-171.3780.79, JRE 1.8.0_112-release-736-b13x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 2560x1440`

## Exception

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Task failed: GatherUsedLocalElementsTask for source /Users/marcinsydor/Repos/questgame/lib/components/game/game_component.dart
Unexpected exception while performing GatherUsedLocalElementsTask for source /Users/marcinsydor/Repos/questgame/lib/components/game/game_component.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find (String id, PersonData personData) → Null in [(null id, null personData) → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4425)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10562)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3522)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5347)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8044)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7656)
#15     RecursiveAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:1013)
#16     MethodInvocationImpl
```

**Comment by jwren** [comment] 2017-08-04 17:24
Closing as we were not able to reproduce.  Please reopen if seen again.

**Closed by jwren** 2017-08-04 17:24 UTC
Labels: area-intellij, State: needs info
