### ISSUE TITLE
Async for-in loop question

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#49504] opened 2022-07-22 13:36 UTC
I'm not sure if this is an issue or not. At least the behavior of the following Dart program looks strange for me.
```dart
import "dart:async";

Stream<int> generator() async* {
  for (int i = 1; i < 5; i++)
    yield i;
}

main() async {
  StreamController sc = StreamController();
  Stream<int> stream = generator();
  sc.addStream(stream);

  await for(var i in sc.stream) {
    print(i);
  }
  print("Now we are here!"); // this part is not executed!
  throw Exception("Bomb!!!");
}
```
This program prints `1 - 4` and finishes. I do understand why code after `await for(...) {...}` is not executed. Stream, controlled by `StreamController`, is not closed and `await for` waits for it. If we want this code to be executed we should change the program to be like the following
```dart
import "dart:async";

Stream<int> generator() async* {
  for (int i = 1; i < 5; i++)
    yield i;
}

main() async {
  StreamController sc = StreamController();
  Stream<int> stream = generator();
  sc.addStream(stream).then((_) async {
    print("IsClosed: ${sc.isClosed}");
    sc.add(42);
    await Future.delayed(Duration(milliseconds: 100));
    sc.close();
    print("Closed");
  });
  await for(var i in sc.stream) {
    print(i);
  }
  print("Now we are here!");
  //throw Exception("Bomb!!!");
}
```
The program above prints
```
1
2
3
4
IsClosed: false
42
Closed
Now we are here!
```
This is Ok, but what is not clear for me is why the first version of the program successfully finishes? I'd expect it to hung, endlessly waiting for the new events from a stream which is not closed. But instead of this it successfully finishes with exit code `0`. Why?

Tested on `Dart SDK version: 2.19.0-13.0.dev (dev) (Tue Jul 19 17:04:51 2022 -0700) on "windows_x64"  `

**Comment by eernstg** [comment] 2022-07-22 15:43
I think there's no problem. The situation is similar to the following, and the point is that it is possible for an asynchronous Dart program to have computations that are not complete because they are waiting for something. But there is no more work to do, and hence it is guaranteed that they won't ever proceed.

```dart
import 'dart:async';

void main() async {
  Completer<void> completer = Completer();
  print('Started!');
  await completer.future; // Will never be completed.
  print("Not reached, no problem!");
}
```

**Comment by lrhn** [comment] 2022-07-22 23:03
As @eernstg says, the first example is a classical example of a stuck/deadlocked asynchronous program.

The `await for` waits for the stream to close. The stream does not close. So the `await for` never completes.

The program stops doing things, because there is nothing left to do, and that's the definition of a program terminating.
It just exits, like any other program which has no scheduled events or timers or open ports, and no code running. Nothing is happening, and nothing can ever happen again, so the main isolate terminates.

The `await for` looks like straight-line code, but it's actually based on callbacks, and if that callback is never invoked, nobody will complain.

It is rather surprising, though, and it has been suggested before that keeping the isolate alive, with an option to see it hanging at the `await for` in the debugger, would be better than just silently terminating without even running `finally` blocks.

This is basically a duplicate of https://github.com/dart-lang/sdk/issues/24895. which itself refers to the general issue https://github.com/dart-lang/sdk/issues/23797.

**Closed** 2022-07-23 19:43 UTC
Labels: closed-duplicate, type-question
