### ISSUE TITLE
Dart Analyze error.

### ISSUE THREAD

**Issue by dooboolab** [dart-lang/sdk#35131] opened 2018-11-11 02:44 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/jg/z0qjj9cx5vnblrhdksv7p_4m0000gn/T/report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/hyochan/Documents/SourceCode/FlutterProjects/flutter_calendar_carousel/lib/flutter_calendar_carousel.dart
Exception: Element not found in summary: dart:core

**Comment by stereotype441** [comment] 2018-11-13 23:49
Duplicate of #34555

**Closed by stereotype441** 2018-11-13 23:49 UTC
Labels: analyzer-crash-report, analyzer-server, area-analyzer, crash
