### ISSUE TITLE
Type inference does not work for generic function type alias

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#45320] opened 2021-03-15 13:57 UTC
Dart SDK version: 2.13.0-114.0.dev (dev) (Sat Mar 6 18:27:50 2021 -0800) on "windows_x64"

Here is a source code example:
``` dart
typedef void TEST<T>();
typedef TEST1<T> = void Function<TT extends T>();
typedef TEST2<T> = void Function<T>();

void testme<T extends int>() {}

main() {
  TEST t = testme;
  TEST1 t1 =  testme;
  TEST2 t2 =  testme;
}
```
It expectedly throws a compile errors for the lines #9 (`TEST1 t1 =  testme;`) and #10 (`TEST2 t2 =  testme;`).

Seems like it should throw a error for the line #8 (`TEST t =  testme;`) too.

Sample output is:
```
$> dart --enable-experiment=generic-metadata test.dart 
test.dart:9:15: Error: A value of type 'void Function<T extends int>()' can't be assigned to a variable of type 'void Function<TT extends dynamic>()'.
  TEST1 t1 =  testme;
              ^
test.dart:10:15: Error: A value of type 'void Function<T extends int>()' can't be assigned to a variable of type 'void Function<T>()'.
  TEST2 t2 =  testme;
              ^
```

**Comment by eernstg** [comment] 2021-03-15 15:25
The example program needs to be adjusted: `TEST<S>` denotes the type `void Function()` for any type `S` (in particular, a raw `TEST` also denotes `void Function()`). `TEST1<S>` denotes the type `void Function<X extends S>()`, so the raw `TEST1` denotes `void Function<X extends dynamic>()`. Finally `TEST2<S>` denotes `void Function<X>()` for any `S`.

`testme` has type `void Function<X extends int>()`, so it's not assignable to `TEST1` nor `TEST2`. No type inference takes place, just i2b.

When assigning it to `TEST` we get a generic function instantiation so `testme` is replaced by a function object of type `void Function()` (no matter which value is chosen for the actual type argument), so there's no error in line 8. We usually don't include generic function instantiation as part of type inference, it's a separate thing (similar to the transformation from `e` to `e.call` for an instance of a "callable class").

So I actually think it's all working as intended here.

**Closed** 2021-03-15 17:07 UTC
Labels: closed-as-intended
