### ISSUE TITLE
Add function to the Dart Embedder API to prevent GC from running

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#49034] opened 2022-05-17 00:52 UTC
I would like to request an addition to the embedder API (https://github.com/dart-lang/sdk/blob/main/runtime/include/dart_api.h) to allow embedder's to disable GC (prevent GC from running) and then to allow it again.

This would essentially be a counterpart to the existing `Dart_NotifyIdle()` so something like `Dart_NotifyBusy()` perhaps, to tell the VM that it should not run GC until after it receives a subsequent `Dart_NotifyIdle()`. It would be fine to have the new function also take a deadlike parameter, as long as it was possible to call it again to extend the deadline, before the deadline ran out, though I think it would be nicer just to use a call to NotifyIdle to signal that the "busy" period was over.

The reason for this request is that there are specific use cases, such as low-latency audio/music synthesis, games, etc, where the application needs to prevent GC for latency reasons during some **specific** period of time and then trigger GC to occur at other specific points of time.

By asking for this to be part of the the embedder API, I believe would both address all the concerns raised by @dnfield in a [related issue](https://github.com/dart-lang/sdk/issues/45458#issuecomment-845263515) while still allowing application code to make use of it via FFI as well as embedders such as Flutter.

Note that this is not the same as https://github.com/dart-lang/sdk/issues/45458, since I would like this be available for production (release) app usage, not just for debugging via eg. VmServices or `dart:developer`.

**Comment by dnfield** [comment] 2022-05-17 01:11
Fwiw, the framework would generally like to avoid GC during animation as well (@iskakaushik)

What should the vm do if you start running out of memory?  What should it do if you've made a critical section too long, or allocate too much?

**Comment by maks** [comment] 2022-05-17 01:21
@dnfield  yes, thats a very good point! I would expect that animations could benefit from this too, though from what I've found so far, things like audio seem to be much more timing sensitive since the deadlines are much shorter than 16ms and the user perception of missing it (audio pops) seems to be more severe than a dropped frame.

With running out of memory, I would expect this to be handled in exactly the same way as happens now without it when memory is exhausted: a crash. Its a problem for the application developer to deal with, especially as in this case, they have to very explicitly *opt in* to disabling GC.

Eg. same as in the case of too high memory usage that you previously worked on, where too many large images exhausted memory, as application developers we need to be aware of memory constraints.

But currently, without this in the API, there is no way to prevent GC happening in critical latency sensitive parts of an application, as @mraleph has previously told me that even if I as an app dev were to try to pre-allocate all my memory usage up front, there could still be memory allocation occurring withing core Dart lib code that could cause a GC and as I understand it, GC is shared across all Isolates, so I can't avoid this by just running my latency sensitive code in its own Isolate.

**Comment by mraleph** [comment] 2022-05-17 08:38
I think it is fair to say that we are unlikely to add such a method. While it is _kinda_ possible to implement this it goes contrary to the overall idea that a GC managed language can run GC at arbitrary points in time. Also just delaying GC is hardly a proper solution - in many cases you are just going to hit a very long pause at a later point which will mess up with your timings anyway.

There are real-time GCs that could provide soft/hard real-time guarantees (most well know is probably [Metronome](https://dl.acm.org/doi/abs/10.1145/640128.604155)): ensuring that GC never pauses the mutator for longer than 100-200 microseconds, but these GCs come with high cost in terms of memory and impact on the mutator throughput. 

Ultimately if you want soft or hard real-time guarantees then maybe Dart is not the language that you should be using.

/cc @rmacnak-google @a-siva

**Comment by maks** [comment] 2022-05-17 09:53
@mraleph thanks for taking a look at this!

I agree Dart is probably not the right tool for anything that needs real-time GC or soft or hard real-time guarantees, but I don't think that's what I am asking for here. I'm specifically *not* asking for a time limit on how long GC runs for.

Rather only the ability to control *when* GC can possibly happen. `Dart_NotifyIdle()` exists, so that embedders can already hint to the VM when it should do GC. All I'm really suggesting is to extend this to allow having periods of time when GC **cannot** happen. 

I've thought about this and I think the use cases that motivated me to request this would benefit from this solution.
Take for example a FM synthesizer app, there are long periods of time when no audio is being played as the user changes settings, inputs the musical score etc versus actually triggering playback of musical notes. Likewise often before entering a score in "live" a user will often have a 4 beat "count in" lasting several seconds before having a period of continuous audio playback. Just as in the "loading screens" within games, all these parts of the apps usage would give the app developer opportunities to request GC in between periods (of eg. low-latency audio playback) when GC would be prevented. 

I would argue no of the above would mess up timings as the GC simply is deferred instead of being able to be triggered by whatever heuristics currently trigger it within the VM.

As I mentioned in my reply to Dan, I don't think this would be any different to the considerations app developers currently need to make in regards to memory usage (eg. large images, loading large data files etc), if anything I would argue that the dev's who would want to make use of this facility for low-latency audio or some types of games would be more aware of memory usage constraints than developers working on other types of apps with Dart or Flutter.

**Comment by dnfield** [comment] 2022-05-17 15:47
I don't think `Dart_NotifyIdle` works very well compared to its intention TBH.

Embedders call `Dart_NotifyIdle` to say "I have this much deadline left before I know I have to do work again." Dart looks at that and tries to estimate some "small" task. It has no real idea of whether it actually has enough time to complete that task or not. And sometimes that small amount of work ends up kicking off some larger workload on additional threads that then contend with the mutator thread for core time.  On top of that, I have frequently observed traces where Flutter provided a large `Dart_NotifyIdle`  with a large deadline _right before_ going into a period of heavy animation (oops!).

One though that's come up a few times with @rmacnak-google is the idea of having different modes for something like [Chromium's RAIL model](https://docs.google.com/presentation/d/15EQ603eZWAnrf4i6QjPP7S3KF3NaL3aAaKhNUEatVzY/edit#slide=id.g146e10bf57_4_145), where the GC might be hinted about what phase an application is in and behave differently based on that.

Another topic, perhaps related to that, is the idea of pretenuring certain allocations that you know will be longer lived into old space. That could make the scavenges cheaper for a time.

**Comment by dnfield** [comment] 2022-05-17 15:48
Another topic we've discussed on GC performance is incremental GC. @a-siva did an experiment that was a bit disheartening on lower end devices (performance got worse because just requesting a page from the OS was taking too long), but maybe ignoring lower end devices it could still help...

**Comment by slightfoot** [comment] 2022-05-17 19:27
I've been chatting with @maks around similar topics before. And a type of Critical Section would be good. Perhaps this is more about allowing GC per isolate. So that GC on a specific isolate can be paused.

I also see what @mraleph is saying. I can see the idea of just stopping GC for a period cannot work. Imagine GC comes along just before you want to go into your critical section and lasts as long as 3 frames. Bam. There's your audio pops. I wonder if its possible other solutions. Like asking for a scheduled critical callback at specific periods that any don't allow alloc. So GC can be paused yet whilst the code continues.

I'm sure there's lots of options. But not knowing the inner workings of Dart to the n-th degree its hard to suggest what might be possible.

**Comment by a-siva** [comment] 2022-09-19 22:36
Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/47574

**Closed by a-siva** 2022-09-19 22:36 UTC
Labels: area-vm
