### ISSUE TITLE
Error while compiling the project. 

### ISSUE THREAD

**Issue by sanketwarule** [dart-lang/sdk#36381] opened 2019-03-29 08:18 UTC
Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but couldn't. Error message was 'null:3705664: unexpected variable index: 29 at '. This might be a bug. The Dart team would greatly appreciate if you would take a moment to report this problem at http://dartbug.com/new.

file:///Users/ganesh/Documents/flutterSdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.3/lib/src/webview_scaffold.dart:110:7: Error: No named parameter with the name 'resizeToAvoidBottomInset'.
      resizeToAvoidBottomInset: widget.resizeToAvoidBottomInset,
      ^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/ganesh/Documents/flutterSdk/flutter/packages/flutter/lib/src/material/scaffold.dart:725:9: Context: Found this candidate, but the arguments don't match.
  const Scaffold({
        ^
Compiler failed on /Users/ganesh/Desktop/FlutterApp/lib/main.dart

Flutter doctor :

[[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G5019, locale en-IN)
    • Flutter version 1.0.0 at /Users/ganesh/Documents/flutterSdk/flutter
    • Framework revision 5391447fae (4 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ganesh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Pixel                     • FA6AJ0301424  • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by kevmoo** [comment] 2019-04-03 21:28
Looks like you have a mismatched package.

Did you try rerunning `flutter packages upgrade` ?

**Comment by far11ven** [comment] 2019-04-08 18:28
I too have tried creating new project, as well as running "flutter packages upgrade", always the same result, app launches with following screen.
 I've added following "flutter_webview_plugin: ^0.3.3" as dependency.

![8e57a030-34fe-4f7b-8cce-eed332a0022d](https://user-images.githubusercontent.com/26922130/55747480-fde8ea80-5a59-11e9-937d-6beddc9091c9.jpg)

**Comment by a-siva** [comment] 2019-05-24 23:02
This appears to be a duplicate of #37043

**Comment by a-siva** [comment] 2019-07-02 16:41
Closing as duplicate.

**Closed by a-siva** 2019-07-02 16:41 UTC
Labels: area-front-end, closed-duplicate, needs-info, p2-medium, type-bug
