### ISSUE TITLE
Type inference doesn't work nicely with function types

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30822] opened 2017-09-20 11:38 UTC
/cc @leafpetersen 

I just ran into the following bug in the type inference:
``` dart
// Wants a function that takes a function and returns a same-typed function.
void foo(T Function() Function<T>(T Function() f) parameterName) {}

// Using a function literal. -> the return type needs to be inferred.
foo(<T>(T Function() f) {
  if (true) return f;
  return () => f();
});
```
Clearly, the return type of the function literal is `T Function()`.
Removing either `return` makes the whole thing work. But having both at the same time leads to an error.

**Comment by lrhn** [comment] 2017-09-20 15:05
A runnable example: https://dartpad.dartlang.org/43bb3ebec177b1008f5c9308b53f5959
The error message that you get is the cryptic:

>The argument type '<T₀>(() → T₀) → () → T' can't be assigned to the parameter type '<T>(() → T) → () → T'.

(But you do get bonus points for the non-ASCII chars, it's *looking* good!)

**Comment by leafpetersen** [comment] 2017-09-20 20:41
Simplified example, that also changes the type variable name to check that it's not a dup of https://github.com/dart-lang/sdk/issues/30379:

```dart
main() {
  T Function() Function<T>() g =
      <S>() {
    S Function() f;
    if (f != null) return f;
    return () => f();
  };
}
```

**Comment by jmesserly** [comment] 2017-09-22 20:41
possibly related bug: https://github.com/dart-lang/sdk/issues/29778#issuecomment-317149157

**Comment by jmesserly** [comment] 2017-09-22 20:44
Looking at this more, I'm pretty sure it's a dupe of #29778. I'll make sure these test cases are over there as well.

**Closed by jmesserly** 2017-09-22 20:44 UTC
Labels: analyzer-strong-mode, area-analyzer, Resolution: duplicate, strong-mode-polish
