### ISSUE TITLE
CFE bug inferring / instantiating universal functions

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#31643] opened 2017-12-13 19:20 UTC
The following prints '3' in DDC:

```
import 'dart:math' as math;

void main() {
  var list = [1, 2, 3];
  var val = list.fold(0, math.max);
  print(val);
}
```

but fails in the new CFE with:
```
max.dart:5:31: Error: A value of type '<T extends dart.core::num>(dart.math::max::T, dart.math::max::T) → dart.math::max::T' can't be assigned to a variable of type '(dart.core::int, dart.core::int) → dart.core::int'.
Try changing the type of the left hand side, or casting the right hand side to '(dart.core::int, dart.core::int) → dart.core::int'.
```

Note, the old FE is instantiating `math.max` as `math.max<int>` based on context.

@kmillikin @leafpetersen @a-siva

**Comment by vsmenon** [comment] 2017-12-13 19:23
If `math.max` is replaced with `(x, y) => math.max(x, y)`, it appears to infer the correct instantiation.

**Comment by vsmenon** [comment] 2017-12-13 19:24
@stereotype441 @crelier @sigmundch

**Comment by stereotype441** [comment] 2017-12-13 22:21
Duplicate of issue #31586.

**Closed by stereotype441** 2017-12-13 22:21 UTC
Labels: area-front-end, Customer-VM
