### ISSUE TITLE
Debugger ignores a breakpoint

### ISSUE THREAD

**Issue by osaxma** [dart-lang/sdk#53376] opened 2023-08-29 11:32 UTC
_the issue was originally filed at https://github.com/Dart-Code/Dart-Code/issues/4707_

**Describe the bug**

The breakpoint at line 382 is ignored as shown in the screen recording below (it's taking several seconds because the setup prepares a database):

https://github.com/Dart-Code/Dart-Code/assets/46427323/4db671b9-2635-4d6e-b6b8-45aff9c84e84

**To Reproduce**
<s>I could not reproduce outside of the project that I was working on, but I made a branch in my fork to reproduce:
1. Checkout the `debugger_breakpoint_issue` branch
    - link: https://github.com/osaxma/postgresql-dart/tree/debugger_breakpoint_issue
2. Make sure Docker is available -- the tests will pull the latest postgres image so first run may be slow. 
3. Go to `tests/v3_test.dart` to line 382 and set a breakpoint as shown in the video
4. Click `debug` above the test and the debugger skips the breakpoint </s>

[Update] this is a minimal code sample  to reproduce
```dart
void main() {
  final int y = 0;
  /* breakpoint here would hit */ final yd = y.toDouble();

  late final int x = 1; // late initialization causes the issue
  /* breakpoint here would miss */ final xd = x.toDouble();
}
```

**Expected behavior**
I expect the debugger to hit the breakpoint.

**Please complete the following information:**
- Operating System and version: 12.6 (21G115)
- VS Code version: 1.81.1
- Dart extension version: v3.70.0
- Dart/Flutter SDK version: Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_x64"

--- 

Additional context from see @DanTup:

> 
> Nothing looks wrong in the log until the debugger pauses at the wrong place. A new isolate starts paused, we send breakpoints, the VM responds. We then resume the isolate and both breakpoints resolve, but then we hit the second breakpoint.
> 
>
> from: https://github.com/Dart-Code/Dart-Code/issues/4707#issuecomment-1697223235

**Comment by osaxma** [comment] 2023-09-28 12:19
It turns out the issue was happening because of the late initialization in the `setup` function.

Here's the absolute minimal code sample to reproduce:

```dart
import 'package:test/test.dart';

class Obj {
  Object get() => Object();
}

void main() {
  group('Breakpoints issue', () {
    late final Obj obj = Obj(); // "late final" initilization causes the issue

    test('test break points', () {
      /* breakpoint miss */ final res = obj.get();
      /* breakpoint hit */ expect(res, isA<Object>());
    });
  });

  group('No Breakpoints Issue', () {
    final obj = Obj(); // no issue
    test('test break points', () {
      /* breakpoint hit */ final res = obj.get();
      /* breakpoint hit */ expect(res, isA<Object>());
    });
  });
}
```

**Comment by virmundi** [comment] 2023-10-20 01:13
I have the same issue. While this might not be reproducible, hopefully it helps a bit.
```
import 'package:flutter_test/flutter_test.dart';
import 'package:my_home/db/all.dart';
import 'package:my_home/domain/all.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

void main() {
  Database db;
  const accountID = "a123";
  late final DBPropertiesReader reader;

  test("work with properties", () async {
    getDBPath = () async => inMemoryDatabasePath;
    databaseFactory = databaseFactoryFfi;
    db = await getDB();
    reader = DBPropertiesReader(db);

    // Removes any temp data used for UI development.
    await db.delete(accountTable);
    await db.delete(propertyTable);

    await db.insert(accountTable, {
      "id": accountID,
    });

    var properties = await reader.read();
    expect(properties.isEmpty, isTrue);

    await db.insert(propertyTable, {
      "id": "p123",
      "account": accountID,
      "name": "VB Farm",
      "kind": PropertyKind.storage.string,
    });

    final huh = await db.query(propertyTable);

    properties = await reader.read();
    expect(properties.length, 1);
    final [prop] = properties;
    expect(prop.accountID, accountID);
    expect(prop.id, "p123");
    expect(prop.name, "VB Farm");
    expect(prop.kind, PropertyKind.storage);
  });
}

```
If the variable `Database db` is marked as late, the debugger will only stop on lines before the initialization of the db variable. Removing final allows breakpoints to stop anywhere in that file and other invocation points.

**Comment by derekxu16** [comment] 2023-10-26 16:03
I investigated @osaxma's example above, and here's what I've found:

When setting a breakpoint on the `final xd = x.toDouble();` line, `ResolveBreakpointPos` wants to set the breakpoint at the safepoint that is closest to the start of the line:

https://github.com/dart-lang/sdk/blob/ed1842480c966b93ecf80627178dc2238d6f0e2a/runtime/vm/debugger.cc#L2018-L2019

It picks the token corresponding to `x`, but it looks like it should really be picking the token two positions to the right, which corresponds to the `t` in `toDouble()`.

@aam, do you have any thoughts about how we can fix this?

**Comment by aam** [comment] 2023-10-26 18:01
It might be that the issue is with kernel->flowgraph construction around final variables initialization - I would check what is going on with https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#L2067

**Comment by aam** [comment] 2023-10-26 21:43
Splitting the line in two ```
/* breakpoint here would miss */ final xd = x
  .toDouble();``` and setting a breakpoing at `.toDouble()` works.
The reason for this is that late variables uses (use of `x`) have hidden exception-path logic that makes debugger to set a code  breakpoint at that exception-path (https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc#L2087).

**Comment by a-siva** [comment] 2023-11-09 17:54
@liamappelbe can you create issues for the synthetic statement tagging that you are working on and link it to this issue.

**Comment by liamappelbe** [comment] 2023-11-09 20:51
https://github.com/dart-lang/sdk/issues/54005

**Comment by aam** [comment] 2023-11-09 21:31
> #54005

It would be nice to confirm whether that issue talks about ignoring code for breakpoints at the same level of granularity as this issue.
This issue is about "We prefer the lowest compiled code address" coded in https://github.com/dart-lang/sdk/blob/282bbced093ead9ef060a969764cde03257fabe8/runtime/vm/debugger.cc#L1998. not being applicable to late vars initialization,

**Closed** 2024-02-28 20:07 UTC
Labels: area-vm, vm-debugger, P2, triaged
