### ISSUE TITLE
Inconsistent compile-time errors for const keys that override == with Object's ==.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36552] opened 2019-04-10 03:49 UTC
Example: 
```
class A {
  bool operator ==(Object o);
  
  const A();
  int get hashCode => 42;
}

main() {
  const map = const {A() : 43};
}
```
Experimental flags: constant-update-2018

This emits an error in dart2js and DDK but not in the VM or DDC. 

The issue here is that, though `A` overrides '==', it overrides '==' with Object's '=='. The spec says that merely overriding '==' (even with Object's '==') is enough to make this a compile-time error, so it seems CFE is correct here. But we've been letting this case slide until now. This pattern occurs somewhat frequently (e.g., `third_party/dart/protobuf/lib/src/protobuf/protobuf_enum.dart`).

**Comment by sigmundch** [comment] 2019-04-10 05:12
Interesting bug @Markzipan!

@leafp @lrhn - I'm honestly not sure what is the intended behavior here.

Adding milestone 2.3 in case we need to take some action, in particular:
* If this is not allowed - we probably need to message a breaking change
* If we want to allow it - we need to ask the CFE team to remove the compile-time error (please reassign the area in that case)

**Comment by kmillikin** [comment] 2019-04-10 06:40
The spec is careful to talk about having an implementation different than that of Object.==, not overriding. 

This is just a bug in the CFE that should have been fixed by d75a49a44f3140c6bddc60afa774c335b581d397.

**Comment by eernstg** [comment] 2019-04-10 07:02
@kmillikin wrote:
> The spec is careful to talk about having an implementation different
> than that of Object.==, not overriding

Right, I made that very explicit.

**Comment by askeksa-google** [comment] 2019-04-10 08:36
Latest front end (after d75a49a44f3140c6bddc60afa774c335b581d397) doesn't produce an error.

@Markzipan can you verify that d75a49a44f3140c6bddc60afa774c335b581d397 works for you?

**Comment by Markzipan** [comment] 2019-04-10 15:49
@askeksa-google Yes, the newest update works! I suppose we should update that in g3 roll.

**Closed** 2019-04-10 19:51 UTC
Labels: area-front-end, p1-high, type-bug
