### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by vckkk** [dart-lang/sdk#35504] opened 2018-12-27 07:04 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\wb-hbz437868\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\hbz\app0_1\lib\model\test.dart context: exception_20181227_144813_536
RangeError (index): Invalid value: Not in range 0..5, inclusive: 6
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer._getConstructorForEntry (package:analyzer/src/summary/resynthesize.dart:1612:27)
#3      SummaryResynthesizerContext.resolveConstructorRef (package:analyzer/src/summary/resynthesize.dart:446:30)
#4      ConstructorElementImpl.redirectedConstructor (package:analyzer/src/dart/element/element.dart:2175:18)
#5      ErrorVerifier._hasRedirectingFactoryConstructorCycle (package:analyzer/src/generated/error_verifier.dart:6206:35)
#6      ErrorVerifier._checkForRecursiveFactoryRedirect (package:analyzer/src/generated/error_verifier.dart:4899:10)
#7      ErrorVerifier.visitConstructorDeclaration (package:analyzer/src/generated/error_verifier.dart:577:12)
#8      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2946:15)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#

**Comment by stereotype441** [comment] 2018-12-27 16:34
Duplicate of #34534

**Closed by stereotype441** 2018-12-27 16:34 UTC
Labels: analyzer-server, area-analyzer
