### ISSUE TITLE
2.6 > dartdevc : Bad state: Empty input given.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [dart-lang/sdk#39300] opened 2019-11-08 17:31 UTC
I have a project running fine in 2.5.2, after a brew update to 2.6, I now see miles of issues while attempting to run webbed serve. 
**OS, SDK:** 
- Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "macos_x64"
- macOS Mojave 10.14.6

**Error**:

> We're sorry, you've found a bug in our compiler.
> You can report this bug at:
>     https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
> Please include the information below in your report, along with
> any other information that may help us track it down. Thanks!
> -------------------- %< --------------------
>     dartdevc -k arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.6.0/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/tw_portal_framework/login/event.template.ddc.js --source-map --summary=packages/tw_util/util.ddc.dill=packages/tw_util/util --summary=packages/rational/rational.ddc.dill=packages/rational/rational --summary=packages/decimal/decimal.ddc.dill=packages/decimal/decimal --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=packages/quiver/pattern.ddc.dill=packages/quiver/pattern --summary=packages/stomp/impl/plugin.ddc.dill=packages/stomp/impl/plugin --summary=packages/stomp/impl/util.ddc.dill=packages/stomp/impl/util --summary=packages/stomp/websocket.ddc.dill=packages/stomp/websocket --summary=packages/quiver/core.ddc.dill=packages/quiver/core --summary=packages/tw_annotation/annotation.ddc.dill=packages/tw_annotation/annotation --summary=packages/logging/logging.ddc.dill=packages/logging/logging --summary=packages/uuid/uuid_util.ddc.dill=packages/uuid/uuid_util --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/uuid/uuid.ddc.dill=packages/uuid/uuid --summary=packages/tw_core/core.ddc.dill=packages/tw_core/core --summary=packages/tw_portal/portal.ddc.dill=packages/tw_portal/portal --summary=packages/tw_portal_framework/login/event.ddc.dill=packages/tw_portal_framework/login/event --packages=file:///var/folders/fx/8bxfj9lj1mb4sz9vzh1h1qsdvn1gnt/T/kernel_builder_HVaxZc/.packages --module-name=packages/tw_portal_framework/login/event.template --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/local/Cellar/dart/2.6.0/libexec/lib/libraries.json --used-inputs-file=/var/folders/fx/8bxfj9lj1mb4sz9vzh1h1qsdvn1gnt/T/ddk_builder_i2LxOF/used_inputs.txt package:tw_portal_framework/login/event.template.dart
>     dart --version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "macos_x64"
> 
> Bad state: Empty input given.
> #0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:457:29)
> #1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:474:7)
> #2      Timeline.timeSync (dart:developer/timeline.dart:161:22)
> #3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:472:21)
> #4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
> #5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:207:29)
> <asynchronous suspension>
> #6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:153:10)
> <asynchronous suspension>
> #7      _compile (package:dev_compiler/src/kernel/command.dart:277:27)
> <asynchronous suspension>
> #8      compile (package:dev_compiler/src/kernel/command.dart:42:18)
> <asynchronous suspension>
> #9      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
> #10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:64:13)
> #11     _rootRun (dart:async/zone.dart:1124:13)
> #12     _CustomZone.run (dart:async/zone.dart:1021:19)
> #13     _runZoned (dart:async/zone.dart:1516:10)
> #14     runZoned (dart:async/zone.dart:1463:12)
> #15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:24)
> <asynchronous suspension>
> #16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
> #17     _rootRun (dart:async/zone.dart:1124:13)
> #18     _CustomZone.run (dart:async/zone.dart:1021:19)
> #19     _runZoned (dart:async/zone.dart:1516:10)
> #20     runZoned (dart:async/zone.dart:1463:12)
> #21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
> <asynchronous suspension>
> #22     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
> <asynchronous suspension>
> #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
> #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by sigmundch** [comment] 2019-11-11 19:29
Thanks for reporting the issue!

Marking as a duplicate of #38102 (note the first entry in that bug gives a different error message, but we are believe errors of like yours also fall into the same issue). This has been a hard bug to reproduce locally, so we are still investigating the underlying issue.

**Closed by sigmundch** 2019-11-11 19:29 UTC
Labels: area-web
