### ISSUE TITLE
Collect benchmarks and improve FFI performance

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#36719] opened 2019-04-23 17:56 UTC
https://github.com/santetis/libsodium.dart contains a crypto benchmark

**Comment by sjindel-google** [comment] 2019-04-23 17:58
duplicate of https://github.com/dart-lang/sdk/issues/36247

**Comment by mraleph** [comment] 2019-04-24 13:33
Duplicate of #36247

**Closed by mraleph** 2019-04-24 13:33 UTC
Labels: area-vm, library-ffi
