### ISSUE TITLE
dart2js: Implement initializer assertions

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#37881] opened 2019-08-15 20:16 UTC
As of 78ce916d8219457c872183ce89c594b045891b48 of the Dart SDK the DDK does not seem to implement `assert` statements in the constructor initializer list.

We have the following code in Flutter for web:

```dart
  PersistentTextEditingElement(
    html.HtmlElement domElement, {
    @required html.VoidCallback onDomElementSwap,
  })  : _onDomElementSwap = onDomElementSwap,
        // Make sure the dom element is of a type that we support for text editing.
        assert(_getTypeFromElement(domElement) != null) {
    this.domElement = domElement;
  }
```

It currently does not throw the expected assertion error. For non-const constructors, a workaround is to move the assert into the body of the constructor. There is no workaround for const constructors.

/cc @vsmenon @Markzipan

**Comment by vsmenon** [comment] 2019-08-15 20:57
Hmm, this is asserting correctly in DDK.  
```
class A {
  final int x;
  final int y;
  const A(this.x, this.y) : assert(x < y);
}

void main() {
  print(A(1,2));
  print(A(2,1));
}
```

@yjbanov - does the above throw for you?  Trying to figure out if this is a configuration thing somewhere or something more subtle (i.e., it doesn't work in certain cases).

**Comment by Markzipan** [comment] 2019-08-15 21:00
I can confirm that DDK does generate constructor asserts. Is there a repro you can point us towards?

**Comment by vsmenon** [comment] 2019-08-15 21:41
Reassigning to @yjbanov for more info.

**Comment by yjbanov** [comment] 2019-08-17 00:18
@vsmenon in the following test file, test "A" fails while test "B" succeeds:

```dart
import 'package:test/test.dart';
import 'matchers.dart';

class A {
  final int x;
  final int y;
  const A(this.x, this.y) : assert(x < y);
}

class B {
  final int x;
  final int y;
  B(this.x, this.y) {
    assert(x < y);
  }
}

void main() {
  test('A', () {
    expect(() => A(2,1), throwsAssertionError);
  });

  test('B', () {
    expect(() => B(2, 1), throwsAssertionError);
  });
}
```

Command used to run the test:

```
pub run test --platform=chrome  test/path/to/the_test.dart
```

**Comment by yjbanov** [comment] 2019-08-17 00:19
Failure message is:

```
00:07 +0 -1: A [E]                                                                        
  Expected: throws <Instance of 'AssertionError'>
    Actual: <Closure 'main__closure0'>
     Which: returned <Instance of 'A'>
```

**Comment by Markzipan** [comment] 2019-08-18 15:21
That's odd - the test works when I compile and run locally (on module systems: AMD, common, node, es6). Jake suspects there might be some assert-enabling flag that hasn't been set somewhere. Slightly modified snippet I tested:

```
class A {
  final int x;
  final int y;
  const A(this.x, this.y) : assert(x < y);
}

class B {
  final int x;
  final int y;
  B(this.x, this.y) {
    assert(x < y);
  }
}

void main() {
  try {
    A(2, 1);
  } on AssertionError catch (e) {
    print(e);
    print(e.runtimeType);
  }
  try {
    B(2, 1);
  } on AssertionError catch (e) {
    print(e);
    print(e.runtimeType);
  }
}
```
Outputs:
```
'Failed assertion: line 4 pos 36: 'x < y': is not true.
_AssertionError
'Failed assertion: line 11 pos 12: 'x < y': is not true.
_AssertionError
```

**Comment by yjbanov** [comment] 2019-08-18 23:20
@Markzipan What command do you use to run the test?

> Jake suspects there might be some assert-enabling flag that hasn't been set somewhere

If that were the case wouldn't "B" in my example also fail?

**Comment by Markzipan** [comment] 2019-08-19 05:41
I'm using the `ddc` and `ddb` tools in: https://github.com/dart-lang/sdk/tree/master/pkg/dev_compiler/tool

Command: `ddc -k $DARTFILE --dart-sdk-summary $DART_SDK/xcodebuild/ReleaseX64/gen/utils/dartdevc/kernel/ddc_sdk.dill`

Other command: `ddb -k -r [node|d8|chrome|common|legacy] $DARTFILE`

However, when I run that file above with `pub run test --platform=chrome $DARTFILE` as you've described, I see your behavior. The Dart being run seems to be compiled with Dart2js. Is it possible that the first part throws, then the second part is tree-shaken out? 

Generated code looks like:
```
    main0: function() {
      var e, e0, exception, t1;
      try {
      } catch (exception) {
        t1 = H.unwrapException(exception);
        if (!!J.getInterceptor$(t1).$isAssertionError) {
          e = t1;
          P.print(e);
          P.print(H.getRuntimeType(e));
        } else
          throw exception;
      }
      try {
        H.assertHelper(false);
      } catch (exception) {
        t1 = H.unwrapException(exception);
        if (!!J.getInterceptor$(t1).$isAssertionError) {
          e0 = t1;
          P.print(e0);
          P.print(H.getRuntimeType(e0));
        } else
          throw exception;
      }
    },
    B: function B(t0, t1) {
      this.x = t0;
      this.y = t1;
    }
```

**Comment by vsmenon** [comment] 2019-08-19 12:52
@grouma - shouldn't `pub run test --platform=chrome` use DDC?  

What flags are given to dart2js by default?  If `O3` or greater, it's actually sort of working as intended.

**Comment by yjbanov** [comment] 2019-08-19 15:38
> If O3 or greater, it's actually sort of working as intended.

Are failing in-body asserts and non-failing initializer list asserts intended behavior in O3?

**Comment by yjbanov** [comment] 2019-08-19 15:40
But also, I expected `pub run test` to use DDC, not dart2js. We may have two issues here:

1. `pub run test` should use DDC, not dart2js.
1. Whatever it is `pub run test` uses today has a bug described above.

**Comment by vsmenon** [comment] 2019-08-19 15:53
> Are failing in-body asserts and non-failing initializer list asserts intended behavior in O3?

`O3`+ is basically a blank check for dart2js to assume that / optimize as if `Error`s aren't thrown.  An assert throws a subtype of `Error`.  (Note, it handles `Exception`s and other thrown types more conservatively.):

    -O3
       Enables optimizations that respect the language semantics only on
       programs that don't ever throw any subtype of `Error`.  These
       optimizations improve the generated code, but they may cause programs to
       behave unexpectedly if this assumption is not met.

**Comment by vsmenon** [comment] 2019-08-19 15:55
@jakemac53 - can you triage from here?  Possibly multiple issues:

- What should @yjbanov be using?  E.g., `build_runner`?
- Is `flutter test` wired to use the right thing?
- May want need `dart2js` issue: disallow `O3+` and `enable-asserts`?  Or if the above is with less than `O3`, it's seems like a bug.

**Comment by jakemac53** [comment] 2019-08-19 16:04
> * What should @yjbanov be using?  E.g., `build_runner`?

You can use `pub run build_runner test -- <test-args-here>` to test with ddc today.
  - Now that we have the build_daemon we could look into adding support for using DDC in package:test through that (it would only need a build_daemon dependency).
  - This would actually work really nicely with some of the build filter changes we are looking into, since only the test package knows what tests it should actually compile (and for what platforms).

> * Is `flutter test` wired to use the right thing?

cc @jonahwilliams I don't know how/where this is wired up.

> * May want need `dart2js` issue: disallow `O3+` and `enable-asserts`?  Or if the above is with less than `O3`, it's seems like a bug.

The test package doesn't expose dart2js options to the user. It does dart2js compilation [here](https://github.com/dart-lang/test/blob/48a0d09e1b77e5e80e6b18eca6cf32626c6b59b9/pkgs/test_core/lib/src/runner/compiler_pool.dart#L55), but I don't see any `O*` flags. It is passing `--enable-asserts`. So it sounds like a dart2js bug possibly?

**Comment by yjbanov** [comment] 2019-08-19 16:10
To be clear, `flutter test` is not related to this issue. I'm trying to get engine tests running in the flutter/engine repository. `flutter test` is not available there, which is why I was using `pub run test` instead. I will try @jakemac53's `pub run build_runner test` suggestion asap and report back.

**Comment by vsmenon** [comment] 2019-08-19 16:13
Thanks!  I've repurposed this issue for dart2js as I think there is an underlying SDK issue there.

We may want to open a `test` issue as well.

**Comment by rakudrama** [comment] 2019-08-19 16:21
From `ssa/builder_kernel.dart`:

```dart
      } else if (initializer is ir.AssertInitializer) {
        // Assert in initializer is currently not supported in dart2js.
        // TODO(johnniwinther): Support assert in initializer.
      } else if (initializer is ir.InvalidInitializer) {
```

**Comment by jakemac53** [comment] 2019-08-19 16:25
That looks likely :D

**Comment by yjbanov** [comment] 2020-03-26 01:39
Looks like I forgot to report back. This is still affect engine code. We have code that relies on these assertions, e.g.:

```dart
  EngineLineMetrics.withText(
    this.displayText, {
    @required this.startIndex,
    @required this.endIndex,
    @required this.endIndexWithoutNewlines,
    @required this.hardBreak,
    this.ascent,
    this.descent,
    this.unscaledAscent,
    this.height,
    @required this.width,
    @required this.left,
    this.baseline,
    @required this.lineNumber,
  })  : assert(displayText != null),
        assert(startIndex != null),
        assert(endIndex != null),
        assert(endIndexWithoutNewlines != null),
        assert(hardBreak != null),
        assert(width != null),
        assert(left != null),
        assert(lineNumber != null && lineNumber >= 0);
```

Today I was surprised by a test passing despite analysis warnings and found that these assertions never trigger.

We use `pub run build_runner build test`, which seems to be using `dart2js`.

**Comment by jakemac53** [comment] 2020-03-26 16:23
Note that by default `pub run build_runner build test` uses ddc - I would check your `build.yaml` for `compiler: dart2js` as it is likely being overridden somewhere.

**Comment by lrhn** [comment] 2021-03-04 13:30
This appears to still be an issue. Running just with `dart2js --enable-asserts` (no `-o` flag), my initializer asserts still do not trigger.
Example:
```dart
void main() {
  // assert(false, "works");
  C(C.limit + 1);
}
class C {
  static const limit = 100000000;
  final int x;
  const C(int x) : assert(-limit <= x && x <= limit, "Bad arg!"), x = x;
}
```
Compiling with a freshly built tip-of-tree:
```
> out/ReleaseX64/dart-sdk/bin/dart2js --enable-asserts --out=assert.dart.out assert.dart
Compiled 8,640,749 characters Dart to 13,019 characters JavaScript in 0.43 seconds
Dart file assert.dart compiled to JavaScript: assert.dart.out

> third_party/d8/linux/d8 assert.dart.out
```
No error.

**Comment by natebosch** [comment] 2021-03-04 20:59
@rakudrama @johnniwinther - How hard would these be to implement?

**Comment by johnniwinther** [comment] 2021-03-04 21:38
30 min to figure out why (apparently) - it's a one line fix. I'll make a CL.

**Closed** 2021-03-05 09:15 UTC
Labels: P3, area-web, customer-flutter, web-dart2js
