### ISSUE TITLE
It would be better if dart2js generates the same JS file if none of source is changed

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#24721] opened 2015-10-24 15:44 UTC
In the recent version (1.11-1.12), the generated JS file varies from one to another even if none of Dart source is changed. It introduced unwanted conflicts when committing into a version control repos.

**Comment by rakudrama** [comment] 2015-11-14 02:48
Tom, this is not intentional.
I have found one issue that would explain the differences.
If you have examples you can send me, that would be helpful.
Send them by email if you want to limit visibility.
Or you could confirm all the differences are on lines beginning with `C.`.

**Comment by tomyeh** [comment] 2015-11-16 01:37
Thanks for looking into it. Attached are JS files generated from the same source code. Yes, they seem all begins with `C.`.

[test.dart.js.txt](https://github.com/dart-lang/sdk/files/35103/test.dart.js.txt)
[test.dart.js-2.txt](https://github.com/dart-lang/sdk/files/35104/test.dart.js-2.txt)

**Comment by rakudrama** [comment] 2015-11-16 17:47
Thanks for the files. That is exactly the difference I see on some examples of my own.
The actual cause is: https://github.com/dart-lang/sdk/issues/24920

**Comment by srawlins** [comment] 2019-08-14 03:39
@rakudrama tagged the cause as "closed-obsolete", and I think the issue has been fixed, as we have deterministic builds internally.

**Comment by joshualitt** [comment] 2021-11-15 19:49
Marking as closed per last update.

**Closed by joshualitt** 2021-11-15 19:49 UTC
Labels: web-dart2js, type-bug, area-web
