### ISSUE TITLE
assignment within block changes analyzed type

### ISSUE THREAD

**Issue by SteveAlexander** [dart-lang/sdk#44137] opened 2020-11-10 14:18 UTC
Not sure I've really captured this in the issue's title. The following example should clarify.

The following is considered an error by the analyzer, but I think it should not be an error.

```dart
class Base {}

class Subclass extends Base {
  Base method() {
    return this;
  }
}

void function(Base b) {
  if (b is Subclass) {
    b = b.method();
  }
}
```

![image](https://user-images.githubusercontent.com/4321921/98685081-3b64d680-2367-11eb-977d-b9f34e57b936.png)

However, this works fine:

```dart
class Base {}

class Subclass extends Base {
  Base method() {
    return this;
  }
}

void function(Base b) {
  if (b is Subclass) {
    b.method();
  }
}
```

Maybe related to https://github.com/dart-lang/sdk/issues/39363

**Comment by eernstg** [comment] 2020-11-10 15:09
In the first example, when running the program without null safety, you get an error at `b.method()` because `b` is mutated in the body of the `if`: This implies that `b` is not promoted to `Subclass`, and `Base` does not have a `method`.

The example has no error when it is considered as a library with null safety, because the new promotion machinery is smarter. In particular, it allows for a variable to be promoted for a while and then 'demoted' by an assignment.

I'll close this because it is working as intended.

**Closed by eernstg** 2020-11-10 15:09 UTC
Labels: closed-as-intended
