### ISSUE TITLE
Segmentation fault(11) when running a building a Docker container on an M1 MacBook

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#45625] opened 2021-04-08 06:12 UTC
I have a Docker container that builds okay on Linux and Mac.

But when on an M1 (Apple Silicon) mac, I get this:

```text
#5 5.303 ===== CRASH =====
#5 5.303 si_signo=Segmentation fault(11), si_code=1, si_addr=0x400c1b5590
#5 5.303 version=2.12.2 (stable) (Unknown timestamp) on "linux_x64"
#5 5.303 pid=8, thread=21, isolate_group=main(0x4002c09c00), isolate=main(0x4002be8800)
#5 5.303 isolate_instructions=4004d00000, vm_instructions=4001a0f020
#5 5.304   pc 0x0000004006108047 fp 0x00000040089f6230 Unknown symbol
[ ... ]
#5 5.304   pc 0x000000400630265f fp 0x00000040089f68f8 Unknown symbol
#5 5.308   pc 0x0000004001ba7690 fp 0x00000040089f6990 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x110
[ ... ]
```

Please note: Docker on M1 is currently in Tech Preview (RC3), and uses QEMU. So it's not like I'm expecting this to work smoothly out of the box.

Steps to reproduce:

* Install Docker for Apple Silicon [tech preview](https://docs.docker.com/docker-for-mac/apple-m1/) ([file](https://desktop.docker.com/mac/stable/arm64/62632/Docker.dmg))
* `git clone https://github.com/filiph/linkcheck.git`
* `cd linkcheck`
* `docker build -t linkcheck .`

Expected:

* Container builds

Actual:

* The process fails.

Full logs:

```text
% docker build -t linkcheck .
[+] Building 32.0s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 141B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/google/dart:latest              1.9s
 => [1/2] FROM docker.io/google/dart@sha256:96f0640de237910dea316e74ef0c  24.7s
 => => resolve docker.io/google/dart@sha256:96f0640de237910dea316e74ef0c7  0.0s
 => => sha256:c962ca5799c43454136aba227b6b852e9ac195 236.37MB / 236.37MB  18.5s
 => => sha256:96f0640de237910dea316e74ef0c74f2e57e71abf683627 742B / 742B  0.0s
 => => sha256:2832300a42e99984b0fa8a299194c7c12b431a788e0 3.07kB / 3.07kB  0.0s
 => => sha256:0c966859c8717ed77037b3d3d5b10f216e3439493 52.66MB / 52.66MB  7.2s
 => => extracting sha256:0c966859c8717ed77037b3d3d5b10f216e343949312028ba  1.3s
 => => extracting sha256:c962ca5799c43454136aba227b6b852e9ac195915437879b  5.2s
 => ERROR [2/2] RUN pub global activate linkcheck                          5.4s
------
 > [2/2] RUN pub global activate linkcheck:
#5 0.933 Resolving dependencies...
#5 4.597 + args 1.6.0 (2.0.0 available)
#5 4.597 + async 2.5.0
#5 4.597 + charcode 1.2.0
#5 4.597 + clock 1.1.0
#5 4.597 + collection 1.15.0
#5 4.597 + console 3.1.0 (4.0.0 available)
#5 4.597 + csslib 0.16.2 (0.17.0 available)
#5 4.598 + file 5.2.1 (6.1.0 available)
#5 4.598 + glob 1.2.0 (2.0.1 available)
#5 4.598 + html 0.14.0+4 (0.15.0 available)
#5 4.598 + intl 0.17.0
#5 4.598 + js 0.6.3
#5 4.598 + linkcheck 2.0.16
#5 4.598 + logging 0.11.4 (1.0.1 available)
#5 4.598 + meta 1.3.0
#5 4.598 + node_interop 1.2.1
#5 4.598 + node_io 1.2.0
#5 4.598 + path 1.8.0
#5 4.598 + pedantic 1.11.0
#5 4.599 + source_span 1.8.1
#5 4.599 + stream_channel 2.1.0
#5 4.599 + string_scanner 1.1.0
#5 4.599 + term_glyph 1.2.0
#5 4.599 + vector_math 2.1.0
#5 4.624 Downloading linkcheck 2.0.16...
#5 4.629 Downloading console 3.1.0...
#5 4.629 Downloading logging 0.11.4...
#5 4.630 Downloading html 0.14.0+4...
#5 4.630 Downloading glob 1.2.0...
#5 4.631 Downloading csslib 0.16.2...
#5 4.631 Downloading args 1.6.0...
#5 4.632 Downloading stream_channel 2.1.0...
#5 4.633 Downloading async 2.5.0...
#5 4.633 Downloading collection 1.15.0...
#5 4.634 Downloading node_io 1.2.0...
#5 4.634 Downloading node_interop 1.2.1...
#5 4.634 Downloading js 0.6.3...
#5 4.635 Downloading path 1.8.0...
#5 4.635 Downloading vector_math 2.1.0...
#5 4.636 Downloading source_span 1.8.1...
#5 4.636 Downloading term_glyph 1.2.0...
#5 4.637 Downloading file 5.2.1...
#5 4.637 Downloading intl 0.17.0...
#5 4.638 Downloading clock 1.1.0...
#5 4.638 Downloading pedantic 1.11.0...
#5 4.639 Downloading meta 1.3.0...
#5 4.639 Downloading string_scanner 1.1.0...
#5 4.639 Downloading charcode 1.2.0...
#5 5.303
#5 5.303 ===== CRASH =====
#5 5.303 si_signo=Segmentation fault(11), si_code=1, si_addr=0x400c1b5590
#5 5.303 version=2.12.2 (stable) (Unknown timestamp) on "linux_x64"
#5 5.303 pid=8, thread=21, isolate_group=main(0x4002c09c00), isolate=main(0x4002be8800)
#5 5.303 isolate_instructions=4004d00000, vm_instructions=4001a0f020
#5 5.304   pc 0x0000004006108047 fp 0x00000040089f6230 Unknown symbol
#5 5.304   pc 0x000000400844f56c fp 0x00000040089f62a8 Unknown symbol
#5 5.304   pc 0x000000400844f40c fp 0x00000040089f6310 Unknown symbol
#5 5.304   pc 0x000000400844f0cc fp 0x00000040089f63b0 Unknown symbol
#5 5.304   pc 0x0000004004d6291e fp 0x00000040089f6400 Unknown symbol
#5 5.304   pc 0x0000004004d59fae fp 0x00000040089f6460 Unknown symbol
#5 5.304   pc 0x000000400c1dd673 fp 0x00000040089f64c8 Unknown symbol
#5 5.304   pc 0x0000004004d5a52b fp 0x00000040089f6510 Unknown symbol
#5 5.304   pc 0x0000004004d72c7d fp 0x00000040089f6550 Unknown symbol
#5 5.304   pc 0x000000400842d9ad fp 0x00000040089f65c0 Unknown symbol
#5 5.304   pc 0x000000400842d729 fp 0x00000040089f6620 Unknown symbol
#5 5.304   pc 0x000000400842d049 fp 0x00000040089f66b8 Unknown symbol
#5 5.304   pc 0x000000400846f16f fp 0x00000040089f6728 Unknown symbol
#5 5.304   pc 0x000000400846f06d fp 0x00000040089f6768 Unknown symbol
#5 5.304   pc 0x0000004004d71287 fp 0x00000040089f67b0 Unknown symbol
#5 5.304   pc 0x0000004004d717fe fp 0x00000040089f67f0 Unknown symbol
#5 5.304   pc 0x0000004004d71a29 fp 0x00000040089f6818 Unknown symbol
#5 5.304   pc 0x0000004004d77d1d fp 0x00000040089f6858 Unknown symbol
#5 5.304   pc 0x0000004004d78237 fp 0x00000040089f6880 Unknown symbol
#5 5.304   pc 0x000000400630265f fp 0x00000040089f68f8 Unknown symbol
#5 5.308   pc 0x0000004001ba7690 fp 0x00000040089f6990 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x110
#5 5.309   pc 0x0000004001ba74c5 fp 0x00000040089f69f0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x175
#5 5.309   pc 0x0000004001ba9e1e fp 0x00000040089f6a40 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x1ee
#5 5.309   pc 0x0000004001bd1d42 fp 0x00000040089f6c30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x4d2
#5 5.310   pc 0x0000004001bfe106 fp 0x00000040089f6ca0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x146
#5 5.310   pc 0x0000004001bfe7ba fp 0x00000040089f6d00 dart::MessageHandler::TaskCallback()+0x1da
#5 5.310   pc 0x0000004001d0c708 fp 0x00000040089f6d80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
#5 5.311   pc 0x0000004001d0cbdc fp 0x00000040089f6db0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
#5 5.311   pc 0x0000004001c8421d fp 0x00000040089f6e70 /usr/lib/dart/bin/dart+0x1c8421d
#5 5.311 -- End of DumpStackTrace
#5 5.311 qemu: uncaught target signal 6 (Aborted) - core dumped
#5 5.329 Aborted
------
executor failed running [/bin/sh -c pub global activate linkcheck]: exit code: 134
```

The `Dockerfile` contents:

```text
FROM google/dart

RUN pub global activate linkcheck

ENTRYPOINT ["/root/.pub-cache/bin/linkcheck"]
```

**Comment by mraleph** [comment] 2022-08-12 12:15
Duplicate of #48420

**Closed by mraleph** 2022-08-12 12:15 UTC
Labels: area-vm
