### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by CrazyStoneJy** [dart-lang/sdk#39656] opened 2019-12-05 03:42 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/crazystone/company_code/sight_merchant/lib/page/home/home.dart context: exception_20191205_114157_806
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5568:5)
#1      TypeProviderForLink.listType (package:analyzer/src/summary/link.dart:5504:21)
#2      ExprBuilder._pushList (package:analyzer/src/summary/expr_builder.dart:898:49)
#3      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:213:11)
#4      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2546:29)
#5      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5387:36)
#6      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5230:7)
#7      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#9      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5666:47)
#10     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5215:48)
#11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1642:16)
#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3870:12)
#13     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3570:15)
#14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3510:7)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3543:42)
#20     Linker.link (package:analyzer/src/summary/link.dart:4075:35)
#21     _relink (package:analyzer/src/summary/link.dart:312:74)
#22     link (package:analyzer/src/summary/link.dart:126:3)
#23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1429:29)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1245:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#48     new Future.sync (dart:async/future.dart:224:31)
#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#55     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#56     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#57     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#58     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#59     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#60     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/h3/wzzkbgsd7rb993f7hftnxp0w0000gp/T/report1.txt.

**Comment by a-siva** [comment] 2019-12-05 16:40
Duplicate of #35437

**Closed by a-siva** 2019-12-05 16:40 UTC
Labels: analyzer-crash-report, area-analyzer, closed-duplicate, type-bug
