### ISSUE TITLE
Server Error - Dart Analyzer Terminated

### ISSUE THREAD

**Issue by Dokotela** [dart-lang/sdk#41312] opened 2020-04-02 17:46 UTC
This just started happening to me in the last week. It did it to me on a windows machine, which was an issue here [#39499](https://github.com/dart-lang/sdk/issues/39499), but has been closed. 

I'm currently running Ubuntu 18.04 and it's also started happening on this machine. There were no specific upgrades or changes I have made that I'm aware of. It does it in both VS Code and Android Studio. I've tried uninstalling dart, flutter, VS Code and AS, reinstalling everything, and as soon as I begin to edit a dart file, I get the same error message. 

So, it has something to do with this file, I think. When I delete it, the error stops. I'll go through it and see if I can figure it out, but in case anyone else has a similar problem, maybe it will help. I've included it below.

[log-8297.txt](https://github.com/dart-lang/sdk/files/4422633/log-8297.txt)
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6308749`
- `2.7.2`
- `AI-192.7142.36.36.6308749, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Linux(amd64) v5.3.0-45-generic, screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.2, server version 1.27.4, FATAL error: UnimplementedError: name is an instance of PrefixedIdentifierImpl in endClassMethod
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.
```
import 'supportingData/supportingData.dart';

import 'recommendedDose.dart';
import 'vaxDate.dart';

class GroupForecast {
  List<String> seriesName;
  List<String> targetDisease;
  String seriesVaccineGroup;
  String groupStatus;
  VaxDate groupEarliestDate;
  VaxDate groupAdjRecDate;
  VaxDate groupAdjPastDueDate;
  VaxDate groupLatestDate;
  VaxDate groupUnadjRecDate;
  VaxDate gropuUnadjPastDueDate;
  String groupForecastReason;
  List<String> groupForecastAgNeeded;
  String groupName;
  List<Vaccine> groupRecVaccines;
  RecommendedDose recommendedDose;

  GroupForecast({
    this.seriesName,
    this.targetDisease,
    this.seriesVaccineGroup,
    this.groupStatus,
    groupEarliestDate,
    groupAdjRecDate,
    groupAdjPastDueDate,
    groupLatestDate,
    groupUnadjRecDate,
    gropuUnadjPastDueDate,
    this.groupForecastReason,
    this.groupForecastAgNeeded,
    this.groupName,
    this.groupRecVaccines,
    this.recommendedDose,
  }) {
    this.groupEarliestDate = VaxDate.min();
    this.groupAdjRecDate = VaxDate.min();
    this.groupAdjPastDueDate = VaxDate.min();
    this.groupLatestDate = VaxDate.max();
    this.groupUnadjRecDate = VaxDate.max();
    this.gropuUnadjPastDueDate = VaxDate.max();
  }
```

The above code doesn't seem to be the problem. Obviously the code below is not something I've finished, but just copying it over seems to have caused the error.
```

  getEarliest(RecommendedDose recommendedDose) {
    groupEarliestDate = groupEarliestDAte > recommendedDose.earliestDate
    ? groupEarliestDate
    : recommendedDose.earliestDate;
  }
  
  getAdjRecDate() {}
  getAdjPastDueDate() {}

  getLatestDate() {}
  getUnadjRecDate() {}
  getUnadjPastDueDate() {}

        newGroupForecast.groupEarliestDate =
                    newGroupForecast.groupEarliestDate >
                            curSeries.recommendedDose.earliestDate
                        ? newGroupForecast.groupEarliestDate
                        : curSeries.recommendedDose.earliestDate;

                newGroupForecast.groupAdjRecDate =
                    newGroupForecast.groupAdjRecDate >
                            curSeries.recommendedDose.adjustedRecommendedDate
                        ? newGroupForecast.groupAdjRecDate
                        : curSeries.recommendedDose.adjustedRecommendedDate;

                newGroupForecast.groupAdjPastDueDate =
                    newGroupForecast.groupAdjPastDueDate <
                            curSeries.recommendedDose.adjustedPastDueDate
                        ? newGroupForecast.groupAdjPastDueDate
                        : curSeries.recommendedDose.adjustedPastDueDate;
}
```

**Comment by srawlins** [comment] 2020-06-13 20:43
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/41274; please follow along there.

**Comment by srawlins** [comment] 2020-06-13 20:43
Duplicate of https://github.com/dart-lang/sdk/issues/41274

**Closed by srawlins** 2020-06-13 20:43 UTC
Labels: analyzer-crash-report, area-analyzer
