### ISSUE TITLE
Writing to existing files on Windows causes the SDK to crash

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#31760] opened 2018-01-03 23:28 UTC
Using Dart VM version: 2.0.0-dev.15.0 on "windows_x64"

Discovered while updating package:watcher to make use of package:test.

On windows calling

`new File(fullPath).writeAsStringSync(contents);`

where `fullPath` is an existing file causes the SDK to crash.

See:
https://github.com/dart-lang/watcher/blob/master/test/utils.dart#L285

**Comment by bkonyi** [comment] 2018-06-01 19:51
@grouma, are you still seeing this? I can't reproduce a crash locally.

**Comment by bkonyi** [comment] 2018-06-22 21:46
Closing for now. Feel free to reopen if there's still an issue.

**Closed by bkonyi** 2018-06-22 21:46 UTC
Labels: area-vm
