### ISSUE TITLE
Nesting Generics doesn't work as expected.

### ISSUE THREAD

**Issue by eximius313** [dart-lang/sdk#53327] opened 2023-08-23 22:52 UTC
While having sucha a class with Generics is perfectly fine:
```dart
abstract class Response<TYPE extends Enum> {
  TYPE get type;
}
```
the compiler does not allow for "catching" the argument. Neither this:
```dart
class Processor<R extends Response<TYPE>> {
  TYPE handle(R response) => response.type;
}
```
nor this:
```dart
class Processor<R extends Response<TYPE extends Enum>> {
  TYPE handle(R response) => response.type;
}
```
works.

----
In your issue, please include:
* Dart version and tooling diagnostic info (`dart info`) -> `- Dart 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "windows_x64"`
* Whether you are using Windows, macOS, or Linux (if applicable) -> Windows 10
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) -> N/A

**Comment by julemand101** [comment] 2023-08-24 00:11
Would the following work for you?
```dart
class Processor<TYPE extends Enum, R extends Response<TYPE>> {
  TYPE handle(R response) => response.type;
}
```

**Comment by eximius313** [comment] 2023-08-24 08:13
> Would the following work for you?
> 
> ```dart
> class Processor<TYPE extends Enum, R extends Response<TYPE>> {
>   TYPE handle(R response) => response.type;
> }
> ```

I know that this compiles, but this is a workaround. `Processor` should be able to take one param. The `TYPE` is nested in `Response`

**Comment by eernstg** [comment] 2023-08-24 21:23
Cf. https://github.com/dart-lang/language/issues/620.

**Comment by lrhn** [comment] 2023-08-25 07:48
Correct, Dart does not allow you to nest generics, meaning declaring a new type variable inside the bound of another.
That would be nice, either as the language issue mentioned above, or as an extension to patterns (`case List<var T>(...):`,  and treating type parameter bounds as type patterns: `<E extends Foo<var T>>`.

It's not a bug in the implementation, and I believe there are issues for the possible language changes, so closing this.

**Closed by lrhn** 2023-08-25 07:48 UTC
