### ISSUE TITLE
Element 'String' from SDK library 'core.dart' is implicitly hidden by 'core.dart

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#28226] opened 2017-01-01 01:13 UTC
file: 'file:///Stuff/Projects/lol_duel/bin/duel.dart'
severity: 'Error'
message: 'Element 'String' from SDK library 'core.dart' is implicitly hidden by 'core.dart'.'
at: '8,11'
source: 'dart'

I'm repeatedly getting these bogus analyzer errors until I force kill the analyzer.

I think they're starting after crashes like https://github.com/dart-lang/sdk/issues/28224 or https://github.com/dart-lang/sdk/issues/28225.  Same dart version, setup, etc as in those bugs.

Previously the type it was complaining about was `Map` now it's `String`.  When I force-kill the analyzer (by finding the pid and killing it) the errors go away.

**Comment by eseidel** [comment] 2017-01-02 18:38
I'm hitting this repeatedly with my project. https://github.com/eseidel/lolsim is the code.

**Comment by eseidel** [comment] 2017-01-02 18:42
I'm using:
`Dart VM version: 1.21.0 (Wed Dec  7 06:44:15 2016) on "macos_x64"`

The command vscode is using to run the analyzer:
```
/usr/local/Cellar/dart/1.21.0/libexec/bin/dart /usr/local/Cellar/dart/1.21.0/libexec/bin/snapshots/analysis_server.dart.snapshot --client-id=DanTup.dart-code --client-version=0.14.7
```

**Comment by bwilkerson** [comment] 2017-01-02 23:11
Duplicate of #28023.

**Closed by bwilkerson** 2017-01-02 23:11 UTC
Labels: area-analyzer, Type: bug
