### ISSUE TITLE
DDC should reify tear-off covariant parameter types as Object

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30423] opened 2017-08-11 17:38 UTC
The following code is free of strong mode errors and is compiled without complaint by DDC:

```dart
typedef void F<T>(T x);
class C<T> {
  void f(T x) {}
}
F<num> g(C<num> c) {
  return c.f; // (2)
}
dynamic h() {
  return new List<F<num>>();
}
main() {
  var x = g(new C<int>()); // (1)
  var y = h();
  y.add(x); // (3)
  x(1.5); // (4)
}
```

I believe this is correct--there are no static errors in the above code.

I can think of two possible ways for this code to behave:

* When `g` tears off `c.f`, it tears off a function whose runtime type is `(int) -> void`.  Since `(int) -> void` is not a subtype of `g`'s declared return type (`(num) -> void`) this causes a runtime error either at (1) or (2) (depending whether the check is done inside `g` or at the call site).
* When `g` tears off `c.f`, it tears off a function containing a hidden run-time check of its argument; therefore its runtime type is either `(num) -> void` or `(Object) -> void`.  Hence no runtime error occurs at (1), (2), or (3).  A runtime error occurs at (4) when we try to pass a `double` to the tear-off.

(I prefer the former, but I think either behavior would be sound and consistent--it all comes down to a question of what you think the runtime type of a tearoff should be).

However, neither of these two things occurs.  What actually happens is that at (3), the following exception occurs: `Type '(int) -> void' is not a subtype of type 'F((num) -> void)'`

This seems unsound: if the tear-off's runtime type really is `(int) -> void`, it should never have been returned from `g` in the first place.  Conversely, anything returned by `g` should be possible to add to the list returned by `h`, since `g`'s return type is `F<num>` and the list's runtime type is `List<F<num>>`.

**Comment by jmesserly** [comment] 2017-08-11 17:55
CC @leafpetersen -- yeah now that I'm reading this, I think this has been a known issue for a while. The runtime type of a tear off can be a different type than what it's assigned to. It's still sound, because while the runtime type claims `int -> void`, it's actually sound to be used as `Object -> void` (because the `int` is callee side checked). Arguably, the problem is that the RTTI is too restrictive. For `covariant` keyword parameters, we actually use `Object` as the RTTI (tho the spec may require us to use the LUB instead of jumping straight to Object, I'm not sure).

I'll see if I can dig up any issues related to this.

**Comment by jmesserly** [comment] 2017-08-11 17:58
I suspect we don't want to do a caller side check for every generic tear-off. So my guess is we should either: A) change the tearoff RTTI to be `Object -> void` (or the instantiateToBounds result for that type param, rather than `Object`), or B) keep the current behavior.

**Comment by stereotype441** [comment] 2017-08-11 19:11
I would be fine with A.

I'm really uncomfortable with B (keep the current behavior) because it breaks an assumption that back ends are likely to make use of for purposes of optimization: the assumption that `x as A` always succeeds if `x`'s static type is `A` (and similarly for `is`, neglecting the case of `null`).  We think we are justified in making that assumption because the type system is sound; that's why I think of this bug as a soundness bug, even though the tear-off contains a runtime type check.

Here is an example of the kind of problem that could occur:

```dart
typedef void F<T>(T x);
class C<T> {
  void f(T x) {}
}
F<num> g(C<num> c) {
  return c.f; // (2)
}
void h(F<int> callback) {
  if (callback is F<num>) {
    callback(1.5);
  } else {
    callback(1);
  }
}
main() {
  F<num> x = g(new C<int>());
  h(x);
}
```

When I run this program using DDC, the value passed to the callback is `1`, because the RTTI of the callback indicates that its type is `int -> void`, which is not a subtype of `num -> void`.

Now what happens when I run it through an optimizing compiler?  The optimizing compiler inlines `h`, producing:

```dart
main() {
  F<num> x = g(new C<int>());
  if (x is F<num>) {
    x(1.5);
  } else {
    x(1);
  }
}
```

Then it optimizes `x is F<num>` to `x != null` (reasoning that `x`'s static type is `F<num>`, so the only way the `is` check could fail is if `x` is `null`), and as a result my optimized program tries to pass `1.5` to the callback, leading to a runtime error.

That seems really bad.

**Comment by jmesserly** [comment] 2017-08-11 19:41
right, currently, you can't optimize away `is` checks for function types like that. If we want that optimization to be possible, then we'll need to fix the RTTI of tear offs.

**Comment by stereotype441** [comment] 2017-08-11 20:20
Not wanting to be a broken record, but I thought of another argument against the status quo: in our discussions about how to add runtime checks to preserve soundness in the face of contravariant uses of generics, we've tried to leave some freedom to the implementation as to how to implement the runtime checks.  The arguments we make to justify this implementation freedom also make soundness assumptions.

For instance, building on my previous example, if `h` were replaced with:

```dart
abstract class I<U> {
  void foo(U x);
}
class D extends I<F<int>> {
  void foo(F<num> x) {
    x(1);
  }
}
void h(F<num> x) {
  new D().foo(x);
}
```

When `D.foo` is called via interface `I`, a runtime check is needed to guard against the possibility that the caller is calling through a more general type like `I<Object>`.  But no check is needed when `D.foo` is called via `D`, as it is in `h`.

We are currently contemplating an implementation that would allow performance-critical back ends like dart2js to skip the unnecessary check when calling `D.foo` via `D`, but would allow non-performance-critical back ends like DDC to go ahead and do the check anyway.  Our intuition for why this is ok is that the check seems like a no-op when calling via `D`.  But if we don't fix this bug, it's not a no-op.  Which means that the behavior of this code would now depend on the back end; it would succeed with dart2js and fail with DDC.

**Comment by jmesserly** [comment] 2017-08-11 20:33
yeah, sorry if I sounded like I was arguing for the status quo :). I am not & would prefer either fixing RTTI or checks on tearoffs, or fixing the RTTI.

Mostly just wanted to point out that the current implementation will not allow, say, an `int` method to be called on a `String`, like the typical soundness hole does. It does have the problem that you can fail at different points. It will fail when called with a non-int, or it will fail earlier if you try to runtime check it as something that accepts a non-int.

**Comment by stereotype441** [comment] 2017-08-11 20:41
Fair enough--I'm glad to hear we would both prefer to have this fixed :)

**Comment by jmesserly** [comment] 2017-08-11 22:57
aha, I found the informal spec & read through the language team discussion:
https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-overrides.md#dynamic-semantics
https://github.com/dart-lang/sdk/blob/master/docs/language/informal/covariant-from-class.md#reified-types

the reified type should be Object. I will fix this in DDC.

**Comment by jmesserly** [comment] 2017-08-12 00:11
https://codereview.chromium.org/2995813002/

**Comment by leafpetersen** [comment] 2017-08-15 21:02
Yes, agreed with the resolution, and the reasoning.   We decided to go with `Object` for the RTTI for tearoffs in large part to avoid the awkwardness of having things for which the dynamic RTTI is not a subtype of the static type.

**Comment by jmesserly** [comment] 2017-08-16 21:58
reopen because there were some additional tests that need status fixes & CL needs to re-land

**Comment by jmesserly** [comment] 2017-08-17 04:12
https://codereview.chromium.org/3001053002/ -- just needed some status fixes.

**Closed** 2017-08-17 06:23 UTC
Labels: area-dev-compiler, P1 high
