### ISSUE TITLE
WebSockets remain on open in hot restart of flutter web

### ISSUE THREAD

**Issue by pcrady** [dart-lang/sdk#48270] opened 2021-11-17 03:15 UTC
```main.dart```
```dart
import 'package:flutter/material.dart';
import 'package:web_socket_channel/web_socket_channel.dart';
import 'dart:convert';
import 'dart:math';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var test = 0;
  late int randomInt;
  var random = Random();
  var uri = Uri.parse('wss://ws-feed-public.sandbox.pro.coinbase.com');
  late WebSocketChannel channel;
  String request = json.encode({
    "type": "subscribe",
    "product_ids": ["BTC-USD"],
    "channels": ["heartbeat"],
  });

  @override
  void initState() {
    randomInt = random.nextInt(1000);
    channel = WebSocketChannel.connect(uri);
    channel.sink.add(request);
    channel.stream.listen((event) {
      print('$randomInt: $test');
      test = test + 1;
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) => Container();
}
```
```pubspec.yaml```
```yaml
name: echowebsocket
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
When I run the above code in flutter web and I do a hot restart (the green play button in android studio) the stream .listen() function survives the restart leaving two listening functions running.
An example output after running from cold (Chrome closed):
```
This application is not configured to build on the web.
To add web support to a project, run `flutter create .`.
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:56738/yLBcQjxMep4=/ws
Debug service listening on ws://127.0.0.1:56738/yLBcQjxMep4=/ws

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:56738/yLBcQjxMep4=/ws
582: 0
582: 1
582: 2
582: 3
582: 4
582: 5
582: 6
582: 7
582: 8
```
Then after a hot restart:
```
Performing hot restart...
Waiting for connection from debug service on Chrome...
582: 30
Restarted application in 155ms.
876: 0
876: 1
582: 31
876: 2
582: 32
876: 3
582: 33
582: 34
876: 4
582: 35
876: 5
582: 36
876: 6
582: 37
876: 7
876: 8
```
As you can see there are now two listen functions being executed. I was under the impression that no state is supposed to survive a hot restart. I have sometimes been able to recreate this problem on emulators but it seems to work every time on web. Here is the output of flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by nshahan** [comment] 2022-02-01 21:45
@ditman Did we come to a conclusion about if the Flutter Web bootstrap/embedding of a DDC app already provides a callback hook for apps to do necessary cleanup on a hot restart?

**Comment by ditman** [comment] 2022-02-01 22:06
@nshahan I tried to `registerExtension` on `ext.flutter.disassemble` from a Flutter web app, but since the engine does this for [its internal cleanup](https://github.com/flutter/engine/blob/5b67a7d338f2fcecb8f65142352dbbda7e13d95a/lib/web_ui/lib/src/engine/initialization.dart#L81-L94), all I get is the following error:

```
Error: Invalid argument(s): Extension already registered:
ext.flutter.disassemble
    at Object.throw_ [as throw] (http://localhost:39725/dart_sdk.js:5069:11)
    at Object.registerExtension$ [as registerExtension]
    (http://localhost:39725/dart_sdk.js:52087:17)
    at Object.main$ [as main]
   ...
```

(A solution for this might be for the engine to expose a web-only API to let flutter apps add code to the `_hotRestartListeners` List?)

**Comment by nshahan** [comment] 2022-02-01 22:21
@annagrin From the webdev, dwds, devtools perspective is there already a way for Flutter Web applications to register a cleanup callback that will be invoked on a hot restart?

**Comment by natebosch** [comment] 2022-02-01 23:11
Is this something we should expect users to do themselves? Should we explore whether we DDC can handle this automatically?

**Comment by annagrin** [comment] 2022-10-26 20:01
I suspect that to solve this we (as in dart and Flutter) would need to provide a library that allows to register extensions that are run during hot restart. @yjbanov is it something that flutter web users would need in general?

**Comment by ditman** [comment] 2022-10-27 17:58
@annagrin from a plugins standpoint, I can remember of one case (at least) where I'd like to register an extension that runs during hot restart. If a Flutter app/plugin does something like:

```
var mySubscription = window.globalEvent.listen((evt) {
  // Code that listens to an event in window...
});
```

There's no signal that lets me unsubscribe from `mySubscription` when Flutter hot reloads. And there's no way to detect if my subscription is already added (so on every hot reload I get a new subscription to the event, with multiple handlers running).

I've worked around this in the past, [but the solution is not the most graceful](https://github.com/fluttercommunity/connectivity_plus/blob/356e120fa1bdf6911ec93d72819adeac3ded20ff/connectivity_for_web/lib/src/network_information_api_connectivity_plugin.dart#L41-L51).

I created an issue for the above a while back: https://github.com/dart-lang/sdk/issues/42679

**Comment by sigmundch** [comment] 2024-07-03 16:38
I believe we are unlikely to have a solution specific to websockets, but that we are more likely going to need a general purpose mechanism to do cleanup when a hot restart happens. Since https://github.com/dart-lang/sdk/issues/42679 tracks that, I think we can close this as a duplicate of that.

**Closed by sigmundch** 2024-07-03 16:38 UTC
Labels: closed-duplicate, web-dev-compiler, area-web
