### ISSUE TITLE
`dev_compiler` generates incorrect code when breaking to outer label in switch

### ISSUE THREAD

**Issue by simolus3** [dart-lang/sdk#49063] opened 2022-05-19 18:23 UTC
Consider this Dart program:

```dart
void main() {
  for (var i = 1; i < 5; i++) {
    var k = i;
    outer:
    while (k > 0) {
      print('i = $i, k = $k');
      switch (k) {
        case 2:
          break outer;
        default:
          k--;
      }
    }
  }
}
```

Compiled with dart2js, or when running in the VM, it prints these expected values:

```
i = 1, k = 1
i = 2, k = 2
i = 3, k = 3
i = 3, k = 2
i = 4, k = 4
i = 4, k = 3
i = 4, k = 2
```

Compiled with dartdevc however, it reaches an infinite loop at `i = 2, k = 2` because the break statement isn't compiled properly:

```js
  test.main = function main() {
    for (let i = 1; i < 5; i = i + 1) {
      let k = i;
      while (k > 0) {
        core.print("i = " + dart.str(i) + ", k = " + dart.str(k));
        switch (k) {
          case 2:
            {
              break;
            }
          default:
            {
              k = k - 1;
            }
        }
      }
    }
  };
```

I'm using Dart 2.17 stable.

**Comment by nshahan** [comment] 2022-05-19 22:18
Looks like a duplicate of https://github.com/dart-lang/sdk/issues/42824.

**Closed by nshahan** 2022-05-19 22:18 UTC
Labels: type-bug, web-dev-compiler, area-web
