### ISSUE TITLE
DartAnalyzer stops working from time to time / autocompletion in IntelliJ fails

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#24812] opened 2015-11-03 16:03 UTC
I know the subject sound weird but thats how it is. The IDEA Team is really helpful but I'm almost sure this is not their fault but it's a "Analyzer Server problem" https://youtrack.jetbrains.com/issue/WEB-18020

*THIS REALLY DRIVES ME CRAZY* 
I know my project is big and has quite a few modules but Dart is almost 4 years old, I'm working with one of the best IDEs and at the moment it's like working with Notepad+syntax highlighting. 

It costs me about one hour per day restarting the IDE, waiting for DartAnalyzer, restarting again, writing ISSUE-reports and so on. It's like being in a Beta-Program...

**Comment by MikeMitterer** [comment] 2015-11-03 16:13
As you can see - no problem for cmdline dartanalyzer but the IDE is not even able to resolve the path!
It would be a workaround if Dart-Analysis-Server would start to rescan the current file but it does nothing. And there is no way to trigger the analysis!!!

![screenshot-1894](https://cloud.githubusercontent.com/assets/116654/10913306/a4871a9e-824d-11e5-9c0d-618c23e89c11.png)

**Comment by MikeMitterer** [comment] 2015-11-03 16:20
Another point is that Analysis-Server doesn't cache anything - it always starts from zero. In my case it takes about 30 to 40mins until it has scanned my project.

**Comment by MikeMitterer** [comment] 2015-11-03 16:26
I took the "turn it off / turn it on" approach and restarted the IDE. After a while autocompletion works again. Maybe I ran into this problem: https://youtrack.jetbrains.com/issue/WEB-18833 - don't know but as said - it's very frustrating at the moment to work with Dart/IntelliJ

**Comment by alexander-doroshko** [comment] 2015-11-03 16:38
According to the screenshot semantic highlighting works in the file on the right side. It means that you didn't have WEB-18833 problem, otherwise you'd have nothing at all working for the whole project (and no 'Dart Analysis' progress on startup).

**Comment by kevmoo** [comment] 2015-11-03 16:51
@MikeMitterer What version of Dart are you on? 1.13 dev, right? Would you please include the full output of `dart --version`.

We've made some BIG fixes in the last couple of dev releases – `1.13.0-dev.7.5` and `1.13.0-dev.7.6`

**Comment by MikeMitterer** [comment] 2015-11-03 16:55
Dart VM version: 1.13.0-dev.7.6 (Fri Oct 30 15:14:38 2015) on "macos_x64"

**Comment by scheglov** [comment] 2015-11-03 21:21
What specifically does not work?
Code completion?
Can you name one more feature that suddenly stops working?

We need to have more information.
Dart Analysis Server has so named "instrumentation".
Let's see if it can provide any hints for us.

You can enable it in IDEA by following these steps:

1. 
![image](https://cloud.githubusercontent.com/assets/384794/10921964/66a6302c-822d-11e5-80e9-3b004e40ee16.png)

2. 
![image](https://cloud.githubusercontent.com/assets/384794/10921966/704dca18-822d-11e5-9398-69f0971e5531.png)

![image](https://cloud.githubusercontent.com/assets/384794/10921982/80664eb6-822d-11e5-8f89-4d300728006a.png)


3. Add ` --instrumentation-log-file=/Users/scheglov/tmp/das_log.txt` to the end.
4. Restart.

 **NB** the file is really huge.
**NB** the file will include complete contents of all the file you edit. If you edit any source you don't want to make public *do not* attach the file to the issue. Send it directly to scheglov@google.com (me).

**Comment by MikeMitterer** [comment] 2015-11-03 21:59
As I am aware of it's "just" code completion. Here it's almost 11pm. I'll send the log tomorrow. Thanks so far!

**Comment by MikeMitterer** [comment] 2015-11-04 10:21
Mail is on the way to you - please keep me informed what you found out.

**Comment by scheglov** [comment] 2015-11-04 16:34
Unfortunately the logs are all after restart on IDEA, so we don't see the reason WHY it was started.
There must be an exception in DAS.
Could you please check the IDEA's Event Log?

**Comment by scheglov** [comment] 2015-11-04 16:34
I also noticed that DAS uses a lot of heap.

Unfortunately until the VM team (@johnmccutchan @iposva-google @rmacnak-google) fixes https://github.com/dart-lang/sdk/issues/24749 we're basically blind and cannot analyze heap problems we don't see on our computers.

**Comment by MikeMitterer** [comment] 2015-11-05 08:17
OK, I've added #com.jetbrains.lang.dart.analyzer  to Help | Configure Debug Log Settings and restarted the IDE...

**Comment by alexander-doroshko** [comment] 2015-11-05 09:58
According to Mike's screenshot code completion is not the only thing that doesn't work for the file on the left side. Navigation to declaration doesn't work as well. I guess for each file either all or none DAS-driven features work.

**Comment by Pacane** [comment] 2015-11-07 12:30
@MikeMitterer Hey, I've got this issue as well. It used to drive me crazy as well. But now instead of restarting intellij, if you have the latest version of the plugin, you can click on the "Reanalyze sources" button in the analyzer tab. This will get your autocompletion + analyzing stuff to work again.

Hope this helps you

![image](https://cloud.githubusercontent.com/assets/2762440/11015170/6d709afe-8521-11e5-9b8f-3d86daf9ddd1.png)

**Comment by mit-mit** [comment] 2015-11-09 08:49
Tagging as an 1.13 candidate.

**Comment by scheglov** [comment] 2015-11-09 19:43
@MikeMitterer sent the log that shows the following exceptions.
DAS stops sending navigation and completion information after these exceptions.

```
Exceptions
Unexpected exception while performing ComputeConstantValueTask for element dynamic _BYTES_PER_WORD in
source /Users/mikemitterer/.pub-cache/hosted/pub.dartlang.org/crypto-0.9.0/lib/src/hash_utils.dart
#0 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#5 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#8 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#9 Future.Future. (dart:async/future.dart:118)
#10 _rootRun (dart:async/zone.dart:903)
#11 _CustomZone.run (dart:async/zone.dart:802)
#12 _CustomZone.runGuarded (dart:async/zone.dart:708)
#13 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#14 _rootRun (dart:async/zone.dart:907)
#15 _CustomZone.run (dart:async/zone.dart:802)
#16 _CustomZone.runGuarded (dart:async/zone.dart:708)
#17 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#18 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#19 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
Caused by The null object does not have a getter 'declaredVariables'. NoSuchMethodError: method not found:
'declaredVariables' Receiver: null Arguments: []
#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2 ComputeConstantValueTask.internalPerform (package:analyzer/src/task/dart.dart:1705)
#3 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#4 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#5 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#6 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#7 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#8 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#9 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#10 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#11 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#12 Future.Future. (dart:async/future.dart:118)
#13 _rootRun (dart:async/zone.dart:903)
#14 _CustomZone.run (dart:async/zone.dart:802)
#15 _CustomZone.runGuarded (dart:async/zone.dart:708)
#16 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#17 _rootRun (dart:async/zone.dart:907)
#18 _CustomZone.run (dart:async/zone.dart:802)
#19 _CustomZone.runGuarded (dart:async/zone.dart:708)
#20 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#21 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#22 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)


Unexpected exception while performing VerifyUnitTask for source /Users/mikemitterer/.pub-
cache/hosted/pub.dartlang.org/intl-0.11.12/lib/src/intl/bidi_formatter.dart
#0 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#5 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#8 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#9 Future.Future. (dart:async/future.dart:118)
#10 _rootRun (dart:async/zone.dart:903)
#11 _CustomZone.run (dart:async/zone.dart:802)
#12 _CustomZone.runGuarded (dart:async/zone.dart:708)
#13 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#14 _rootRun (dart:async/zone.dart:907)
#15 _CustomZone.run (dart:async/zone.dart:802)
#16 _CustomZone.runGuarded (dart:async/zone.dart:708)
#17 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#18 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#19 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
Caused by The null object does not have a getter 'context'. NoSuchMethodError: method not found: 'context'
Receiver: null Arguments: []
#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2 ConstantVerifier.ConstantVerifier (package:analyzer/src/generated/resolver.dart:896)
#3 VerifyUnitTask.internalPerform (package:analyzer/src/task/dart.dart:4603)
#4 AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#5 AnalysisTask.perform (package:analyzer/task/model.dart:210)
#6 AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#7 AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#8 AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1098)
#9 _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#10 AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#11 PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:366)
#12 AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:793)
#13 Future.Future. (dart:async/future.dart:118)
#14 _rootRun (dart:async/zone.dart:903)
#15 _CustomZone.run (dart:async/zone.dart:802)
#16 _CustomZone.runGuarded (dart:async/zone.dart:708)
#17 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#18 _rootRun (dart:async/zone.dart:907)
#19 _CustomZone.run (dart:async/zone.dart:802)
#20 _CustomZone.runGuarded (dart:async/zone.dart:708)
#21 _CustomZone.bindCallback. (dart:async/zone.dart:733)
#22 Timer._createTimer. (dart:async-patch/timer_patch.dart:16)
#23 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#24 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by scheglov** [comment] 2015-11-09 20:48
It seems that it both cases we have a `CompilationUnitElement` which is not attached to its `LibraryElement`.

We attempt to create a new instance of `ConstantVerifier` at https://github.com/dart-lang/sdk/blob/4db460ec48bfd82c370d99d9d816b2b45181c943/pkg/analyzer/lib/src/task/dart.dart#L4603 and pass in `null` as `libraryElement`. So `unitElement.library` is `null`. So, this `UnitElement` does not have an enclosing `LibraryElement`.

**Comment by whesse** [comment] 2015-11-11 00:31
Is this a blocking issue for releasing 1.13 stable?  Do we have an estimate on a fix for this?  Until we hear otherwise,  we can't release 1.13.

**Comment by dgrove** [comment] 2015-11-12 00:20
Any updates on this issue?

**Comment by bwilkerson** [comment] 2015-11-12 01:46
We have not been able to reproduce the exceptions, but we did find one problem that might account for part of the slowness being reported by our users.

@MikeMitterer a couple of questions. Have you re-run `pub` so that there are .packages files and/or is server still running `pub list-package-dirs`? Also, do you have large numbers of HTML files in the `doc` directory (such as are produced by running `dartdoc`)?

**Comment by MikeMitterer** [comment] 2015-11-12 07:17
Almost all of my projects have packages AND .packages. Most of my doc-folders are empty.

**Comment by scheglov** [comment] 2015-11-12 21:06
https://codereview.chromium.org/1441013003

**Comment by scheglov** [comment] 2015-11-12 21:26
We have fixed the problem that caused @MikeMitterer exceptions in https://github.com/dart-lang/sdk/commit/a21e3a5a7f954649434c1edfa6cba5c0e99f8bc9.
This may or may not be the only problem causing losing completion and navigation.

This requires more testing with this fix applied.

**Comment by dgrove** [comment] 2015-11-13 05:33
@MikeMitterer - we have a new build of the SDK available (it hasn't been promoted to dev channel yet, but hopefully you can try it and give us feedback):

https://storage.googleapis.com/dart-archive/channels/dev/raw/1.13.0-dev.7.11/sdk/dartsdk-{macos,linux,windows}-x64-release.zip

We're really hoping to get feedback ASAP from you on this - thanks so much for your help.

**Comment by MikeMitterer** [comment] 2015-11-13 06:58
@dgrove Your link does not work... I've just sent the logs from yesterday to @scheglov

**Comment by MikeMitterer** [comment] 2015-11-13 07:05
...sorry - got it. (https://storage.googleapis.com/dart-archive/channels/dev/raw/1.13.0-dev.7.11/sdk/dartsdk-macos-x64-release.zip)

**Comment by MikeMitterer** [comment] 2015-11-13 09:57
It became worse. While preparing a sample for another bug I made the attached SS
cmdline analyzer is right (it is always right btw.!!!!) To me, the DA-Server-Version is always confused about where the project-root (the dir with pubspec.yaml) is. I'm sure it works great for single module, single project, projects but it fails for bigger, more complex projects. As said several times before - my IntelliJ project has several Dart-Modules each with a bunch of samples. Every sample has it's own pubspec.yaml, its own lib aso.


![screenshot-1929](https://cloud.githubusercontent.com/assets/116654/11143244/fabf8fec-89f3-11e5-8d52-ab7fee0566ab.png)

Project-Structure:
![screenshot-1930](https://cloud.githubusercontent.com/assets/116654/11143382/f32893a4-89f4-11e5-99b9-0756933882c6.png)

**Comment by MikeMitterer** [comment] 2015-11-13 11:47
Did you ever try what happens if DA is working and git changes the dir structure? (I was working within the IDE but changed the branch on the cmdline)

I was just working in a branch "jsCompileBug" committed my changes and went back to the master branch - during this time DA was analyzing... a few secs after changing back to "master" DA immediately stopped... For sure - could also be coincidence...
Here are the last few lines from the log:

```bash
1447414502672:Task:/Volumes/Daten/DevLocal/DevDart/SiteGen:ParseHtmlTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/samples/mdl_button/.sitegen/html/_content/index.html
1447414502673:Task:/Volumes/Daten/DevLocal/DevDart/SiteGen:DartScriptsTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/samples/mdl_button/.sitegen/html/_content/index.html
1447414502673:Task:/Volumes/Daten/DevLocal/DevDart/SiteGen:HtmlErrorsTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/samples/mdl_button/.sitegen/html/_content/index.html
1447414502690:Task:/Volumes/Daten/DevLocal/DevDart/WskAngular/example/wsk_icon_toggle:GetContentTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/samples/mdl_button/.sitegen/html/_content/index.html
1447414502690:Task:/Volumes/Daten/DevLocal/DevDart/WskAngular/example/wsk_icon_toggle:ParseHtmlTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/samples/mdl_button/.sitegen/html/_content/index.html
1447414502692:Task:/Volumes/Daten/DevLocal/DevDart/WskAngular/example/wsk_icon_toggle:DartScriptsTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/samples/mdl_button/.sitegen/html/_content/index.html
1447414502692:Task:/Volumes/Daten/DevLocal/DevDart/WskAngular/example/wsk_icon_toggle:HtmlErrorsTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite/samples/mdl_button/.sitegen/html/_content/index.html
1447414502714:Noti:{"event"::"server.status","params"::{"analysis"::{"isAnalyzing"::false}}}
```

**Comment by dgrove** [comment] 2015-11-13 21:26
We're working hard on this - in the meantime, if you are having issues with the analyzer, here's a document to help you help us by gathering as much info as possible:

https://docs.google.com/document/d/1s4PTof1x7RyxXYX1yO31ByvZsQoDMM7edFIW1SKP25U/edit?pli=1

**Comment by bwilkerson** [comment] 2015-11-13 22:38
As Dan mentioned, we’re working hard on resolving these issues. One of the things we’ve discovered is that there can be a significant performance improvement if `packages` folders are removed (these folders contain a lot of symlinks which can sometimes cause performance problems). Before you remove them, though, we’d like to gather some information to get a better understanding of how big this issue is. We would appreciate it if you could send us the results of running these two commands (from the root of your repository):

    ls -lR | wc -l
    ls -LlR | wc -l

The first counts the number of files reachable from your root directory without following symlinks, the second counts the number of files reachable from your root directory by following symlinks.

Then, you can remove all of the `packages` folders by running the following script:

    find . -name pubspec.yaml -execdir pwd \; -execdir pub get --no-package-symlinks \;

Please let us know whether running the second script improves server’s performance for you.

**Comment by bwilkerson** [comment] 2015-11-13 22:44
@MikeMitterer 

> Did you ever try what happens if DA is working and git changes the dir structure?

Yes. We run analysis server all the time as we're developing it, and we regularly (multiple times per day) switch branches, pull in changes from others, perform rebases, etc. We don't change the directory structure every day, but we do change it periodically. I don't know when the last significant directory structure change was, though, so it's possible there's been some kind of regression.

**Comment by zoechi** [comment] 2015-11-15 15:10
```bash
ls -lR | wc -l
ls -LlR | wc -l
```
> 9773
247843

**Comment by MikeMitterer** [comment] 2015-11-16 08:16
My "project" consists of several modules (this is how IJ organizes a project)
So e.g. MaterialDesignLite for Dart:
```bash
ls -lR | wc -l 82692
ls -LlR | wc -l 860835
```

![screenshot-1931](https://cloud.githubusercontent.com/assets/116654/11177017/a1d3c58c-8c42-11e5-9876-4cdb2096c110.png)

**Comment by zoechi** [comment] 2015-11-16 16:40
I haven't worked too much yet, but after deleting the packages directories I didn't experience slowdowns.

**Comment by keertip** [comment] 2015-11-16 16:46
@MikeMitterer , could you try this build http://gsdview.appspot.com/dart-archive/channels/dev/raw/1.13.0-dev.7.12/sdk/. It should fix the issues you were seeing with the -dev.7.11 sdk.

**Comment by bwilkerson** [comment] 2015-11-16 17:11
@MikeMitterer Did you try deleting the packages directories? If so, was there any change in performance?

**Comment by MikeMitterer** [comment] 2015-11-16 17:41
@keertip Thanks I'll give it a try tomorrow! 

@bwilkerson I can't delete all the packages. I thought you gonna come up with a final solution for the package problem - removing all of them is not the best one... what, and in my case that's the case, if one package referenz assets from another package? Then you need at least one package-folder in web or in project-root... 

To be more precise:
Something like this:

sample.scss in dart-application X: 
```css
@import "packages/mdl/assets/styles/animation/animation";
```

**Comment by bwilkerson** [comment] 2015-11-16 18:00
Sorry, I guess I was unclear. The `pub` command currently produces a `packages` directory unless you explicitly ask it not to (using the --no-package-symlinks argument). It also creates a `.packages` file. We are moving toward getting rid of the `packages` directory altogether and using the file in its place. So, if you delete the directory we will still be able to resolve your `package:` URI's. The concept of packages is not going away, we're just changing how we implement it.

**Comment by bwilkerson** [comment] 2015-11-16 18:27
Oh, I just re-read you question and I think I understand better what you were asking. The VM also understands `.package` files, and I would guess that it will be able to load assets by using the files rather than the directories.

@munificent Can you confirm this?

**Comment by zoechi** [comment] 2015-11-16 18:39
The sass transformer calls out to the sass command line tool which doesn't know about Dart and the `.packages` file. If the files aren't actually there it fails.

**Comment by bwilkerson** [comment] 2015-11-16 18:56
> The sass transformer ...

That's a problem. My understanding is that both the directory and the file are produced by default in 1.13. In 1.14 and later only the file will be produced by default. In 1.14 you'll still be able to explicitly ask `pub` to produce the directory, but as of 1.15 even that won't be possible.

I think the transformer will need to be updated to follow the package spec DEP (https://github.com/lrhn/dep-pkgspec).

**Comment by bwilkerson** [comment] 2015-11-16 19:41
I created an issue for the transformer (https://github.com/EvidentSolutions/dart-sass/issues/1) in case they were not aware of the changes that are coming.

**Comment by zoechi** [comment] 2015-11-16 19:44
You can update the transformers, but that won't happen for non-Dart related 3rd party tools like the sass tool called by the transformer. That's a known problem. I haven't seen any discussions how to deal with such tools yet though.

**Comment by MikeMitterer** [comment] 2015-11-17 08:36
I tried the new version with latest IJ Dart plugin and it's really much faster now - Cool! But there are still a few issues:
- It takes about 4 minutes or so until DA starts to analyze (check my mp4)
- I crashed the Analyzer by enabling a module while it was analyzing ~ 07:46 in mp4 or 14:50 (error message lower right corner!) It shows the server-version 12 - is this correct?

Here you can see the whole process:
http://www.mikemitterer.at/fileadmin/_temp_/dart_analyzer.mp4

@scheglov I've sent you the log via mail...

**Comment by bwilkerson** [comment] 2015-11-17 15:29
@MikeMitterer Excellent! I'm glad we're starting to make progress. We'll take a look at the log files and see what we can learn.

**Comment by scheglov** [comment] 2015-11-17 17:52
There are two reasons why in your video it too 4 minutes:

1. Dart Plugin for IntelliJ (DPI) does not start DAS until you open a Dart file.
2. DAS spends 2.5 minutes doing `pub list-package-dirs`.

Usually DAS uses `.packages` files, so avoids calling `pub list-package-dirs`, so works much faster.
But I suspect that many of `pubspec.yaml` files are in templates, so they have invalid `name:` and in this case `.packages` file cannot be generated. Unfortunately unless we validate `pubspec.yaml` files in DAS, we don't know whether the file is valid or not. And `Pub` generates `pubspec.lock` anyway, so we cannot use its absence as an indicator, that the package should not be analyzed.

The easy solution would be to exclude these templates from analysis.
We will talk to the `Pub` authors to see if something can be done to optimize.
```
analyzer:
  exclude:
    - 'samples/**'
    - 'lib/_templates/**'
```

The crash (actually not a crash - just a non-fatal exception) must be easy to fix.

**Comment by scheglov** [comment] 2015-11-17 18:26
The fix for the exception.
https://codereview.chromium.org/1445283003/

**Comment by MikeMitterer** [comment] 2015-11-18 07:20
Sorry - but I have another one.
I few days ago I've moved all the MDL/Dart samples to https://goo.gl/UM9hsN
As you can see in the SS DA ist not able to resolve an Object defined in it's own lib *LoginDialog*
And again - it's DA-Server. The cmdline-version works.
![screenshot-1934](https://cloud.githubusercontent.com/assets/116654/11234951/352ef6e0-8dcd-11e5-8ef7-7b6d238e412d.png)

**Comment by bwilkerson** [comment] 2015-11-18 17:42
> Sorry - but I have another one.

We're not. You're being extremely helpful, and we're grateful.

What was the error message associated with those two uses of the class name?
Which library defines LoginDialog?

**Comment by scheglov** [comment] 2015-11-18 18:13
@MikeMitterer, you see the error because your `samples` folder is excluded from analysis by the `.analysis_options` file in the root of the `dart-material-design-lite-site` project. 

```
analyzer:
  exclude:
    - 'samples/**'
```

This mean that when you open a Dart file, it is analyzed as an independent file, not a part of the `template_spa` package, just because there are no such analysis context from the DAS point of view. Note, that if you open the `template_spa` separately, it also works in DAS, just like it works with `dartanalyzer`.

**Comment by zoechi** [comment] 2015-11-18 18:55
Why is it analyzed at all, when it is excluded?

**Comment by scheglov** [comment] 2015-11-18 19:04
Good point, @zoechi.
We will fix it.

**Comment by mit-mit** [comment] 2015-11-18 20:03
@zoechi, @scheglov, I would like to move the tracking of that .analysis_options problem to a new github issue. We are getting ready to ship 1.13, and it does not sound like that new issue is a blocker.

Let me know if that is OK. Thanks!

**Comment by scheglov** [comment] 2015-11-18 20:08
Yes, a separate issue for `exclude` handling in `.analysis_options` would be nice.

**Comment by zoechi** [comment] 2015-11-18 21:01
I worked quite some time and can confirm that without the `packages` folders it works quite well. I would see #24910 as blocker. Otherwise I'm fine.

**Comment by mit-mit** [comment] 2015-11-19 08:41
Closing this bug as 1.13 was promoted to stable.

@zoechi, we will follow up on #24910 in that issue.

**Closed by mit-mit** 2015-11-19 08:41 UTC
Labels: area-analyzer, priority-high, Type-Defect

**Comment by MikeMitterer** [comment] 2015-11-19 08:46
@scheglov It's to bad but there is still somewhere a bug in how IJ or DA handles analysis / reanalyzing.
I've added to files mdlanimation.dart and animation.dart and as you can see here www.mikemitterer.at/fileadmin/_temp_/da_bug.mp4 I had no chance to reanimate DA. I clicked around tried several thing - nothing happened! The weird this is that when I stopped the recording of the screencast, maybe because the app focus changed, DA started to analyze...

I've sent you the log via mail
@mit-mit I think this is still open

Here the SS after I stopped recording - (DA is still analyzing...)
![screenshot-1936](https://cloud.githubusercontent.com/assets/116654/11266114/54fea6f2-8ea2-11e5-87fe-ad37e972b9d3.png)

**Comment by mit-mit** [comment] 2015-11-19 08:51
@MikeMitterer, can you please open a new issue(s) to track any remaining problems? I'd like to close this one out so that we can easier tell what was resolved, and what is still not working.

**Comment by scheglov** [comment] 2015-11-19 16:33
@MikeMitterer It might be the same problem as before - we spend about `150` seconds doing `pub list-package-dirs`. Until it's done, DAS cannot respond to the client.

This is something we can optimize in DAS after `Pub` fixes its issue.
https://github.com/dart-lang/pub/issues/1361
