### ISSUE TITLE
Strong mode allows iterable to be assigned to list

### ISSUE THREAD

**Issue by manuelF** [dart-lang/sdk#26619] opened 2016-06-04 07:40 UTC
```dart
void main() {
  List<String> f = ['a', 'b']
  List<String> res = f.map((x) => x + 'aa');
  print(res)
}
```

`$ dartanalyzer --strong file.dart`
No issues found

`$ dart file.dart`
(aaa, baa)

`$ dart --checked file.dart`
type 'MappedListIterable' is not a subtype of type 'List<String>' of 'res'

Shouldn't this at least produce a strong mode warning? Types are clearly not assignable.

**Comment by zoechi** [comment] 2016-06-04 11:48
It **does** complain about missing semicolons though ;-) https://dartpad.dartlang.org/926c7d2430072eb7eacf72ea907a1f1f (including missing `;`)

**Comment by leafpetersen** [comment] 2016-06-06 22:55
This is potentially a valid downcast given the existing variance rules, and so we allow it.  I hope to get an opt in flag for disabling these implicit downcasts implemented shortly.  Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/26583 which tracks that feature request.

**Closed by leafpetersen** 2016-06-06 22:55 UTC
