### ISSUE TITLE
Support for TLSv1.3?

### ISSUE THREAD

**Issue by Blykam** [dart-lang/sdk#45034] opened 2020-07-14 14:53 UTC
I'm fairly new to Dart & Flutter.
I wanted to perforn a HTTP Request, but it failed because of a HandshakeException (HandshakeException: Handshake error in client (OS Error: TLSV1_ALERT_PROTOCOL_VERSION(tls_record.cc:587))). I use Cloudflare with TLSv1.3. When I switch the min. version of TLS to 1.2, it works just fine.
So is there basically no TLSv1.3 support at the moment?

**Comment by gustav3d** [comment] 2021-02-17 20:15
That's correct.
And all the tickets regarding this topic are without any sign of progress.
Instead its silence as anwer when you ask for a status update / ETA..

**Comment by mraleph** [comment] 2021-02-18 11:18
Duplicate of #41061

**Closed by mraleph** 2021-02-18 11:18 UTC
