### ISSUE TITLE
SIMD datatypes can't be `const`

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#48940] opened 2022-05-02 17:36 UTC
This tracker is for issues related to:

* Dart core libraries ("dart:async", "dart:io", etc.)

## Description

I looked into migrating Flutter's `BoxConstraint`s from storing 4 `double`s to 2 `Float64x2` but I cannot do that because `Float64x2` doesn't offer a const constructor.

This is related to `customer:money` and the fact that ~450ms of startup time on low end devices is in layout which heavily uses `Double.clamp`.

## Code
```diff
--- a/packages/flutter/lib/src/rendering/box.dart
+++ b/packages/flutter/lib/src/rendering/box.dart
@@ -4,6 +4,7 @@
 
 import 'dart:developer' show Timeline;
 import 'dart:math' as math;
+import 'dart:typed_data' show Float64x2;
 import 'dart:ui' as ui show lerpDouble;
 
 import 'package:flutter/foundation.dart';
@@ -128,10 +129,10 @@ class BoxConstraints extends Constraints {
   const BoxConstraints.tightForFinite({
     double width = double.infinity,
     double height = double.infinity,
-  }) : minWidth = width != double.infinity ? width : 0.0,
-       maxWidth = width != double.infinity ? width : double.infinity,
-       minHeight = height != double.infinity ? height : 0.0,
-       maxHeight = height != double.infinity ? height : double.infinity;
+  })  : _widthRange = Float64x2(width != double.infinity ? width : 0.0,
+            width != double.infinity ? width : double.infinity),
+        _heightRange = Float64x2(height != double.infinity ? height : 0.0,
+            height != double.infinity ? height : double.infinity);
 
   /// Creates box constraints that forbid sizes larger than the given size.
   BoxConstraints.loose(Size size)
@@ -152,21 +153,25 @@ class BoxConstraints extends Constraints {
        minHeight = height ?? double.infinity,
        maxHeight = height ?? double.infinity;
 
+  final Float64x2 _widthRange;
+
+  final Float64x2 _heightRange;
+
   /// The minimum width that satisfies the constraints.
-  final double minWidth;
+  double get minWidth => _widthRange.x;
 
   /// The maximum width that satisfies the constraints.
   ///
   /// Might be [double.infinity].
-  final double maxWidth;
+  double get maxWidth => _widthRange.y;
 
   /// The minimum height that satisfies the constraints.
-  final double minHeight;
+  double get minHeight => _heightRange.x;
 
   /// The maximum height that satisfies the constraints.
   ///
   /// Might be [double.infinity].
-  final double maxHeight;
+  double get maxHeight => _heightRange.y;
```

## Expected result
The SIMD datatypes should be able to be `const`.

**Comment by mraleph** [comment] 2022-05-02 18:38
Duplicate of https://github.com/dart-lang/sdk/issues/31487

**Closed by mraleph** 2022-05-02 18:38 UTC
