### ISSUE TITLE
Migration tool doesn't handle compound assignment well

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40305] opened 2020-01-24 01:55 UTC
Running the migration tool on the following code:

```dart
class A {
  int _tail;
  A() : _tail = 0;
  A._();
  void foo() {
    _tail + 1;
    _tail += 1;
  }
}
```

Produces the following code:

```dart
class A {
  int? _tail;
  A() : _tail = 0;
  A._();
  void foo() {
    _tail! + 1;
    _tail += 1;
  }
}
```

Note that the compound assignment still has an invalid reference to `_tail`.  I don't know that there is a good migration here that's guaranteed to preserve semantics without introducing temporary variables, but it feels like at least leaving a hint to the user that there is a known problem to fix up might be good?

cc @stereotype441 @MichaelRFairhurst 

cc @lrhn @munificent for thoughts on how this code should be migrated

**Comment by lrhn** [comment] 2020-01-24 06:29
The "good" migration would be `_tail = _tail! + 1;`. That works in this particularly simple case.
It's enough for more complex assignable expressions like `e1[e2] += 1;` where you will need temporary variables `var tmp1 = e1, tmp2 = e2; tmp1[tmp2] = tmp1[tmp2]! + 1;`.

The `!` operator creates an expression which is not assignable, so it doesn't work with compound read/write operations that both read and write, like `+=` or `++`.

Maybe we could make `e!` an assignable expression when `e` is one, with the meaning that reading `e!` does a null check and writing does not. That would be somewhat more complicated than the current simple "read, check for null" semantics, but it would allow `x!++` and `e1[e2]! += 1`.

**Comment by stereotype441** [comment] 2020-01-24 16:52
Duplicate of #38676

**Closed by stereotype441** 2020-01-24 16:52 UTC
Labels: NNBD, area-analyzer
