### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by zfy1988** [dart-lang/sdk#37781] opened 2019-08-08 02:00 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: NoSuchMethodError: The setter 'previous=' was called on null.
Receiver: null
Tried calling: previous=Instance of 'SimpleToken'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:615:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\Admin\AppData\Local\Temp\report7904.txt.

**Comment by srawlins** [comment] 2019-08-11 21:40
Duplicate of https://github.com/dart-lang/sdk/issues/37096 which has more context (regarding NUL character)

**Closed** 2019-08-12 01:53 UTC
Labels: P1-High, analyzer-crash-report, area-analyzer, type-bug
