### ISSUE TITLE
Even though the types match, the analyzer still reports a type mismatch, but there are no errors at runtime

### ISSUE THREAD

**Issue by lushangkan** [dart-lang/sdk#56275] opened 2024-07-18 05:26 UTC
Dart Analyzer keeps reporting an error type inconsistency, but it runs fine

e.g.:
```
The argument type 'ReminderType (where ReminderType is defined in C:\Users\11490\OneDrive - Student\Flutter\pomotimer\lib\common\enum\reminder_type.dart)' can't be assigned to the parameter type 'ReminderType (where ReminderType is defined in C:\Users\11490\OneDrive - Student\Flutter\PomoTimer\lib\common\enum\reminder_type.dart)'. (文档) 
ReminderType is defined in C:\Users\11490\OneDrive - Student\Flutter\pomotimer\lib\common\enum\reminder_type.dart (reminder_type.dart:3).
ReminderType is defined in C:\Users\11490\OneDrive - Student\Flutter\PomoTimer\lib\common\enum\reminder_type.dart (reminder_type.dart:3).
```

```
A value of type 'Map<Phase, int> (where Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\PomoTimer\lib\common\enum\attribute.dart)' can't be assigned to a variable of type 'Map<Phase, int> (where Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\pomotimer\lib\common\enum\attribute.dart)'. (文档) 
Map is defined in C:\Users\11490\flutter\bin\cache\pkg\sky_engine\lib\core\map.dart (map.dart:43).
Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\PomoTimer\lib\common\enum\attribute.dart (attribute.dart:1).
int is defined in C:\Users\11490\flutter\bin\cache\pkg\sky_engine\lib\core\int.dart (int.dart:39).
Map is defined in C:\Users\11490\flutter\bin\cache\pkg\sky_engine\lib\core\map.dart (map.dart:43).
Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\pomotimer\lib\common\enum\attribute.dart (attribute.dart:1).
int is defined in C:\Users\11490\flutter\bin\cache\pkg\sky_engine\lib\core\int.dart (int.dart:39).
 Try changing the type of the variable, or casting the right-hand type to 'Map<Phase, int> (where Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\pomotimer\lib\common\enum\attribute.dart)'.
```

```
The argument type 'Phase (where Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\pomotimer\lib\common\enum\attribute.dart)' can't be assigned to the parameter type 'Phase (where Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\PomoTimer\lib\common\enum\attribute.dart)'. (文档) 
Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\pomotimer\lib\common\enum\attribute.dart (attribute.dart:1).
Phase is defined in C:\Users\11490\OneDrive - Student\Flutter\PomoTimer\lib\common\enum\attribute.dart (attribute.dart:1).
```

Dart info: 
```
#### General info

- Dart 3.5.0-180.3.beta (beta) (Wed Jun 5 15:06:15 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro for Workstations" 10.0 (Build 22621)
- locale is zh-CN

#### Project info

- sdk constraint: '>=3.2.3 <4.0.0'
- dependencies: boxy, cupertino_icons, device_info_plus, drop_shadow, english_words, event_bus, flex_color_scheme, flutter, flutter_launcher_icons, flutter_local_notifications, flutter_localizations, flutter_lucide, from_css_color, go_router, intl, json_annotation, kotlin_flavor, logger, modal_bottom_sheet, permission_handler, provider, quiver, reflectable, shared_preferences
- dev_dependencies: build_runner, flutter_lints, flutter_test, json_serializable, test
- elided dependencies: 1
```
Platform: Windows 11 -> Android
IDE: IDEA 2024.1.4
Code: https://github.com/lushangkan/PomoTimer

Please comment if you need more information

**Comment by lushangkan** [comment] 2024-07-18 05:42
After observing the case difference in the project path, I tried to revert the project path to "PomoTimer", and reopened the IDE without any error.

**Comment by eernstg** [comment] 2024-07-18 07:42
The [interpretation of an import/export URI is implementation specific](https://github.com/dart-lang/language/blob/a3a7c1ddc4f197abd0d5911b41525a9ca62f7e95/specification/dartLangSpec.tex#L20898). In particular, due to the fact that Windows platforms ignore the case of characters in the names of files and directories, URIs that are identical except that some characters are lowercase in one URI and uppercase in the other will denote the same file, but they are different as URIs according to Dart.

So you get two copies of the given library, and they are considered different, so a type like `ReminderType`-from-the-first-library is unrelated to `ReminderType`-from-the-other-library, in spite of the fact that they came from the same disk file.

The only way to avoid this kind of spurious duplication of types is to ensure that distinct paths do not denote the same library. On Windows (and MacOS) this means keeping the capitalization consistent. On systems where paths are case sensitive you may still encounter a similar phenomenon if distinct URIs denote the same disk file because of links (symlinks or hard links).

It's inconvenient, but it's not really Dart's fault, and it is all working as intended. So I'll close the issue.

**Closed by eernstg** 2024-07-18 07:42 UTC
Labels: area-analyzer, type-bug, triage-automation
