### ISSUE TITLE
Some javascript error are caught with an opaque JavascriptError type when using wasm

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/sdk#56048] opened 2024-06-19 13:18 UTC
Using dart 3.4.4 on Ubuntu 22.04.

Consider the following unit test:

```dart
import 'package:test/test.dart';
import 'package:web/web.dart';

void main() {
  test('raw_idb_exp', () async {
    var dbName = 'test_raw.db';

    // Delete the database
    await EventStreamProviders.successEvent
        .forTarget(window.indexedDB.deleteDatabase(dbName))
        .first;

    late Object createObjectStoreError;
    // Open the database and create an object store
    var openRequest = window.indexedDB.open(dbName, 1);
    EventStreamProviders.upgradeNeededEvent
        .forTarget(openRequest)
        .listen((IDBVersionChangeEvent event) {
      var db = openRequest.result as IDBDatabase;
      db.createObjectStore('test');

      // Create it again, an error should be thrown
      try {
        db.createObjectStore('test');
      } catch (e) {
        createObjectStoreError = e;
      }
    });
    await EventStreamProviders.successEvent.forTarget(openRequest).first;

    print(createObjectStoreError.runtimeType);
    print(createObjectStoreError);

    var db = openRequest.result as IDBDatabase;

    db.close();
  });
}
```

If you run using

```
dart test --platform chrome --compiler dart2js
```
It displays
```
JSObject
ConstraintError: Failed to execute 'createObjectStore' on 'IDBDatabase': An object store with the specified name already exists.
```

If you run using

```
dart test --platform chrome --compiler dart2wasm
```

It displays
```
_JavaScriptError
JavaScriptError
```

which makes it impossible to parse and analyse to know what is going wrong. It seems the error detail is lost.
The same happens using dart 3.5.0-269.0.dev

**Comment by kevmoo** [comment] 2024-06-19 20:01
CC @srujzs @mkustermann

**Comment by srujzs** [comment] 2024-06-25 17:41
Duplicate of https://github.com/dart-lang/sdk/issues/55481

We do want to tackle this, but it might require a versioning strategy and browser/Wasm support to catch JS errors and do something with them. Also see https://github.com/dart-lang/sdk/issues/55496.

**Closed** 2024-06-25 17:42 UTC
Labels: type-bug, area-dart2wasm, triage-automation
