### ISSUE TITLE
Dart analyzer: patchy inference of a `String` type

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#39333] opened 2019-11-12 01:40 UTC
In this example, which takes two `Object` values `left` and `right`:
<img width="424" alt="left-right-string" src="https://user-images.githubusercontent.com/2319867/68634291-c6d42f00-04a9-11ea-9be3-c5a71af1c405.png">

I'm hovering my mouse over `right`. Dart is able to infer that this expression isn't an error (that is, `left + right` will succeed), but in the IDE it still is unable to infer that its type is `String`. Curious -- why does that type inference work in one place and not in another?

## dart --version
```
Dart VM version: 2.6.1 (Mon Nov 11 13:12:24 2019 +0100) on "macos_x64"
```

**Comment by lrhn** [comment] 2019-11-12 08:28
Most likely it's because the IDE (I'm guessing VS-Code) displays the declared type of the variable, not the promoted type. The `right` variable has two types of interest at this point, the declared type of `Object` and the promoted type of `String`.
I can't say whether which type to show is an IDE choice, a DartCode plugin choice or an analyzer choice. According to https://github.com/Dart-Code/Dart-Code/issues/1160, it might be a combination of the last two.

(On a side note, at least one of the `double.parse` calls on the next line is going to fail because one of `left` and `right` is not a `String`).

**Comment by timsneath** [comment] 2019-11-12 15:25
Thanks Lasse. Adding @DanTup as well for interest then. 

And yes, on the side note, what you saw was midstream in development, but thanks for spotting it!  The code still looks rather weird though. This is what I now have:
```dart
  case TokenType.plus:
    if (left is String && right is String) {
      return left + right;
    }
    if (left is double && right is double) {
      return left + right;
    }
    throw new RuntimeError(
        expr.op, 'Operands must be two numbers or two strings.');
```
but not this, which is what I would prefer to express:
```dart
  case TokenType.plus:
    if ((left is String && right is String) || (left is double && right is double)) {
      return left + right;
    }
        throw new RuntimeError(
            expr.op, 'Operands must be two numbers or two strings.');
```

In the latter sample, Dart treats left and right as `Object` rather than of either `String` or `double`.

**Comment by eernstg** [comment] 2019-11-12 15:41
It does look somewhat redundant, but the duplication of the code `left + right` is actually quite meaningful in this case: It compiles to an operation that takes a `String` argument in the first copy, and an operation that takes a `double` in the second.

In contrast, if we were to promote `left` and `right` based on the combined test `... || ...` then we would have a rather complicated typing situation:

Either `left` is a `String` and `right` is a `String`; or `left` is a `double` and `right` is a `double`.

This is not just a union type, where we would have known something like `left` is either a `String` or a `double`; and `right` is either a `String` or a `double`. In that case we can't rule out the combinations where `left` is a `String` and `right` is a `double`, or vice versa.

So we couldn't promote to a useful typing situation unless we'd add the ability to conclude that a number of "situations" could exist, and each situation would describe the type of several variables as a group.

That's fancy and interesting. It is somewhat similar to a Haskell typeclass typing where we'd know that the type of `left` and `right` are instances of a class `Addable`, but the concrete instance like `String` or `double` isn't known statically. However, Haskell wouldn't support using dynamic type tests to detect that this situation exists, so it's a new and fancy thing even in that perspective. So we probably won't add it to Dart any time soon. ;-)

**Comment by timsneath** [comment] 2019-11-12 15:55
Yeah, that makes sense -- it's an interesting edge case. It would not look
so weird if we had a different concatenation operator, obviously.

**Comment by DanTup** [comment] 2019-11-12 16:17
Yeah, unfortunately I think this is the same as https://github.com/Dart-Code/Dart-Code/issues/1160 / https://github.com/dart-lang/sdk/issues/34196 so it'd need additional work from the analyzer. This is what we get back in this case (which has `Object` in both places):

```js
{
	"id": "365",
	"result": {
		"hovers": [
			{
				"offset": 89,
				"length": 5,
				"elementDescription": "Object right",
				"elementKind": "parameter",
				"isDeprecated": false,
				"staticType": "Object"
			}
		]
	}
}
```

**Comment by timsneath** [comment] 2019-11-12 16:32
Ah, that's the one. Thanks for linking the dots, Danny!

**Comment by keertip** [comment] 2019-11-12 17:55
Duplicate of #34196

**Closed by keertip** 2019-11-12 17:55 UTC
Labels: area-analyzer, type-enhancement
