### ISSUE TITLE
Variable not promoted to Null after null-check

### ISSUE THREAD

**Issue by julemand101** [dart-lang/sdk#48504] opened 2022-03-03 10:19 UTC
Tested against the following Dart versions:
```
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"
Dart SDK version: 2.17.0-150.0.dev (dev) (Fri Feb 25 22:29:59 2022 -0800) on "windows_x64"
```

The following program shows some "interesting" behavior when it comes to promote a variable to `Null` when doing a null-check:
```dart
extension NullExtension on Null {
  void someMethod() {
    print("Called Null.someMethod");
  }
}

String? getString() => null;

void main() {
  final string = getString();

  if (string == null) {
    //(string as Null).someMethod();
    string.someMethod();
  }
}
```
This fails by the analyzer with:
```
The method 'someMethod' can't be unconditionally invoked because the receiver can be 'null'. (Documentation)
Try making the call conditional (using '?.') or adding a null check to the target ('!').
```
And when running the program:
```
bin/test.dart:14:12: Error: The method 'someMethod' isn't defined for the class 'String?'.
Try correcting the name to the name of an existing method, or defining a method named 'someMethod'.
    string.someMethod();
           ^^^^^^^^^^
```

If I uncomment `(string as Null).someMethod();` as:
```dart
extension NullExtension on Null {
  void someMethod() {
    print("Called Null.someMethod");
  }
}

String? getString() => null;

void main() {
  final string = getString();

  if (string == null) {
    (string as Null).someMethod();
    string.someMethod();
  }
}
```
The program does no longer have any warning or error from the analyzer and runs with the following result:
```
Called Null.someMethod
Called Null.someMethod
```

This behavior seems kinda weird since the promotion to `Null` seems to happen based on a local type-cast that should not affect the rest of the program.

This might also explain why auto-completion is not that smart (tested with IntelliJ) when it comes to showing what methods can be called on the value. If I use auto-complete before `(string as Null).someMethod();` I will get the full list of methods as if the `string` variable was a `String`:
![image](https://user-images.githubusercontent.com/116227/156544508-e6c0cd0c-5e9e-4661-bc4b-884c6545e85e.png)

While if I do the same after `(string as Null).someMethod();` I will get the possible methods for `Null`:
![image](https://user-images.githubusercontent.com/116227/156544774-27576cf0-bc53-4132-8746-140a1d2fa2aa.png)

**Comment by eernstg** [comment] 2022-03-03 10:48
We do have the following in the [null safety spec](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md#null-promotion):

> A check of the form `e == null` or of the form `e is Null` where `e` has static
> type `T` promotes the type of `e` to `Null` in the `true` continuation, and to
> **NonNull**(`T`) in the
> `false` continuation.

I think we've discussed not performing this particular promotion (because of the rather low value of having an expression of type `Null`), but I can't find any evidence that we shouldn't promote.

@scheglov, @johnniwinther, WDYT?

**Comment by johnniwinther** [comment] 2022-03-03 11:19
I can recall some late changes to how we handle `null` in the promotion (something to do with unsound mode) but can't recall the details. @stereotype441 might remember more since he did most of the implementation.

**Comment by stereotype441** [comment] 2022-03-03 14:20
I don't recall whether there was a deliberate decision at the time we implemented it, but sometime later, we did consider adding this functionality, in response to https://github.com/dart-lang/language/issues/1505.  I did some analysis back in November, and IMHO, enough code would be broken by the change that it's not worth it (you can see my analysis here: https://github.com/dart-lang/language/issues/1505#issuecomment-975706918).  But the question hasn't risen to a high enough priority for the language team to discuss it and make a firm yes/no decision, so the issue remains open.

(@johnniwinther I think you may have been thinking of https://github.com/dart-lang/language/issues/1143, which is a different issue).

I'm going to close this issue on the grounds that it's a duplicate of https://github.com/dart-lang/language/issues/1505.  If folks want to discuss it further, let's have the discussion there so that all the information is in one place.

**Closed by stereotype441** 2022-03-03 14:20 UTC
Labels: area-meta, type-bug
