### ISSUE TITLE
[analyzer] `@deprecated` is not triggered for required positional parameters

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50164] opened 2022-10-08 18:51 UTC
```dart
class A {
  void m1([@Deprecated('') int x = 1]) {}

  void m2(@Deprecated('') int x) {}
}

void f() {
  var a = A();
  a.m1(1); // there is a warning here
  a.m2(2); // 🔥 but not here
}
```

In `m1(1)`, there is a warning because an optional positional parameter is being used, however I wonder if this also should happen for the required one.

**Comment by matanlurey** [comment] 2022-10-09 01:10
Semantically this makes sense, `@Deprecated` is supposed to indicate "you need to stop using this soon".

For `m1`, there is a clear option, stop providing `x`.
For `m2`, there is no clear option, what are you supposed to stop doing?

I imagine for `m2`, you would be intended to annotate the _method_ instead:

```dart
class A {
  void m1([@deprecated int x = 1]) {}

  @deprecated
  void m2(int x) {}
}
```

That being said, if that's the intention, perhaps `@Deprecated` should trigger a _hint_ that you've made the deprecation itself is not valid, for example:

```dart
class A {
  void m1([@deprecated int x = 1]) {}

  // HINT: This deprecated annotation has no effect.
  //
  // Only optional (positional or named) parameters can be deprecated.
  // See <Dart SDK Error URL> for details.
  void m2(@deprecated int x) {}
}
```

**Comment by lrhn** [comment] 2022-10-09 09:18
Any parameter can be deprecates. Anything can be deprecated. It's just not all of them which have a nice migration path.

You can remove anything in a major version increment of a package, and therefore you can annotate any part of a public API as deprecated.

It's *nice* when the current users can migrate off the deprecated functionality before the break happens.
That's why marking entire libraries, classes or methods is OK. You should stop using them. Maybe there is an alternative, maybe you just need to go somewhere else for that functionality.
Optional parameters are easy too, because you can just stop passing them.

A required parameter is trickier, because you can't stop passing *some* value, which means that when the break happens, you still have to go back and manually remove those arguments.

*If* you can make the parameter optional at the same time you make it deprecated, then you are providing a nice migration path, and we should encourage that.

If you are removing the first positional argument of several, then there is no way to make that optional.
In that case, it still makes sense to mark the parameter deprecated, as a warning that a breaking change will happen.
(Maybe you should consider deprecating the entire method, and adding a new one, but I know all the good names are taken.)

All in all: Deprecation means deprecation, whether it's actionable or not. We should still give a warning that your current code will stop working in the future, even if there is nothing you can do about it. (Or nothing *we* can see that you can do about it, maybe you need to switch to an entirely different package by the same author.)

**Comment by bwilkerson** [comment] 2022-10-10 13:59
> ... perhaps `@Deprecated` should trigger a hint that you've made the deprecation itself is not valid ...

As Lasse said, the deprecation is valid. Deprecation doesn't require that there be a migration path.

> We should still give a warning that your current code will stop working in the future ...

The lack of a warning here is intentional. If the code was guaranteed to result in a runtime exception (for example), then I would agree that we should provide a warning to help users find the source of their bugs. But in this particular case, the code isn't wrong and a warning is likely to be noise rather than a valuable signal for most users precisely because the warning is likely to be non-actionable.

That said, there might be some value to some users, and it would be good to have a way to surface the issue. The analyzer team has talked several times about providing some form of analysis / feedback that can be run on demand but that doesn't impact users while they're typing. I think this would be a good candidate for such a mechanism.

Whether or not the choice we made was the right one, the product is currently working as intended, so I'm going to close the issue.

**Closed by bwilkerson** 2022-10-10 13:59 UTC
Labels: area-analyzer, P3, analyzer-hint

**Comment by srawlins** [comment] 2022-10-10 18:10
> The lack of a warning here is intentional.

That is surprising to me. If I were a developer writing `@deprecated` on a required positional parameter, I would be surprised that (A) no user will see this (apparently intentionally on the part of the analyzer), and (B) nor will _I_ be informed that I've just written a toothless annotation which will be intentionally hidden from (or if we prefer, "not shown to") the user.

It seems really inconsistent. I can see some logical reasoning that leads us to "we must suppress a deprecated-use diagnostic in this case," but then we should really report back to the owner of the annotation that they've written an annotation that has no effect on static analysis, just like when you mis-use another annotation like `@sealed int x = 1;`.

Additionally, if we are going to not show diagnostics which aren't actionable, we're not being consistent (maybe just bugs). For example, we _do_ show a diagnostic here:

```dart
class C {
  @deprecated C();
}

var c = C();
```

> line 5 • 'C.C' is deprecated and shouldn't be used.

(Let's ignore the question, "What on earth is `C.C`??" for now.) But this is similarly an un-actionable diagnostic. The class `C` is not deprecated, merely its only constructor is. To be consistent with "don't report `@deprecated` required parameters, it seems we should not report deprecated required constructor calls.

I think this also calls for some changes to the [Deprecated docs](https://api.dart.dev/stable/2.18.2/dart-core/Deprecated-class.html). These sentences don't seem to apply universally now:

> Deprecation is an early warning that the deprecated feature is scheduled to be removed at a later time

> A deprecated feature should no longer be used, code using it will break at some point in the future. If existing code is using the feature, that code should be rewritten to no longer use the deprecated feature.

> The @Deprecated annotation applies to [...] named optional parameters and trailing optional positional parameters.

---

If we're in favor of retaining the current "suppressing" behavior (which I'm not in favor of), I think we need to report an invalid annotation on the required positional parameter, at a minimum. If the developer wants to write a note to themself, they can write a comment. A `// TODO` comment can show up in their IDE. If we choose not to do that, we need to change each of the quoted bits of documentation. And I can open a bug about the singular `@deprecated` constructor usage.

If, on the other hand, we want to allow marking a required parameter as `@deprecated`, so that it is shown to the user, we should make said change. We can use a new code if we like so that it can be suppressed separately, something like `DEPRECATED_MEMBER_USE_REQUIRED`. And apply it to my singular `@deprecated` constructor case, and any others we think of.

**Comment by bwilkerson** [comment] 2022-10-11 14:47
For the original discussion see https://github.com/dart-lang/sdk/issues/48206.

I'm not sure I still agree with everything I said on that issue, but that's where we discussed the idea of not reporting required parameters that are deprecated. I'm not sure why that issue is still open.
