### ISSUE TITLE
improve analyzer hint when (incorrectly) using relative paths to reach out of the lib folder

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24372] opened 2015-09-17 21:07 UTC
I was going to request that we warn people if they try to import something outside of the lib/ folder in a package. For example:

```dart
// this is lib/foo.dart
import '../bar.dart'; // hint a problem here
```

I was pleasantly surprised that we are already giving an error in this case, the error however is not entirely clear. This is what we currently get: 
```
Analyzing [foo.dart]...
[error] Target of URI does not exist: '../bar.dart' (/path/to/foo.dart, line 8, col 8)
1 error found.
```

Could we adjust the error message to say why? For example:
```
Analyzing [foo.dart]...
[error] Target of URI '../bar.dart' cannot be accessed from within your `lib` folder.
This relative import will fail if you ever import `foo.dart` from a package-URI
(/path/to/foo.dart, line 8, col 8)

1 error found.
```

**Comment by bwilkerson** [comment] 2015-09-18 16:09
I just created a test project of the form:

    testProject
      bar.dart
      lib
        foo.dart

And added the import above in foo.dart. I don't see any error, warning or hint. Are you sure the file bar.dart really exists?

In any case, I think this is a duplicate of https://github.com/dart-lang/sdk/issues/22079.

**Closed by bwilkerson** 2015-09-18 16:09 UTC
Labels: Analyzer-Hint, Area-Analyzer, Type-Defect

**Comment by sigmundch** [comment] 2015-09-18 19:47
mmm, strange. I was using the analyzer_cli, but I agree - seems to match exactly that bug. Thanks for deduping :).
