### ISSUE TITLE
'Invalid argument(s): Failed to load dynamic library' error on Flutter FFI

### ISSUE THREAD

**Issue by ganeshrvel** [dart-lang/sdk#42781] opened 2020-07-21 11:26 UTC
I am trying to access a native function which was written in Golang on Flutter but unfortunately it throws the error:

```
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library
(dlopen(/path/to/libhello_ffi.dylib, 1):
no suitable image found.  Did find:
	file system sandbox blocked open() of
'/path/to/libhello_ffi.dylib')
```

It works fine if I just directly execute the dart file instead of flutter run.

Am I missing something here?

Usage: Flutter for Desktop (macOS)
OS: macOS catalina 10.15.6

code:
```dart
import 'dart:ffi' as ffi;

typedef PrintHello_func = ffi.Void Function();
typedef PrintHello = void Function();

void ffi_test() {
  var path =
      '/path/to/libhello_ffi.dylib';

  final ffi.DynamicLibrary dylib = ffi.DynamicLibrary.open(path);

  final PrintHello hello = dylib
      .lookup<ffi.NativeFunction<PrintHello_func>>('PrintHello')
      .asFunction();

  hello();
}

```

**Comment by stuartmorgan** [comment] 2020-07-25 21:38
Duplicate of https://github.com/flutter/flutter/issues/61950 (and explained there, not a bug).

**Closed** 2020-07-26 04:13 UTC
Labels: area-library, library-ffi
