### ISSUE TITLE
DDC generic functions map to obscure JS names in traces

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#30634] opened 2017-09-06 16:01 UTC
Here's a simple example:
```dart
void foo<T>(T x) {
  throw 'error in foo';
}

void main() {
  foo(42);
}
```

The exception shows as:
```
    at dart.throw (/Users/vsm/dart/sdk/pkg/dev_compiler/lib/js/common/dart_sdk.js:5062:27)
    at x (/Users/vsm/ddctest/stacktest.js:11:15)
    at stacktest.main (/Users/vsm/ddctest/stacktest.js:16:26)
```

Note, the user expects `foo` but sees `x` in the trace.

**Comment by vsmenon** [comment] 2017-09-06 16:04
It appears JS / V8 is using the name of the param for an anonymous function:

```
stacktest.foo = function(T) {
  return x => {
    dart.throw('error in foo');
  };
};
```

@jmesserly @jacob314 - any ideas here?

**Comment by leafpetersen** [comment] 2017-09-06 16:12
I've seen this a lot with anonymous functions in general (as well as the ones we generate in codegen).  Very annoying.  Can we use a reasonably named local function instead of an anonymous lambda?

**Comment by matanlurey** [comment] 2017-09-06 16:14
FWIW it's valid in JS to give anonymous functions a name:

```js
stacktest.foo = function foo(T) {
  return x => {
    dart.throw('error in foo');
  };
};
```

Would that work?

**Comment by vsmenon** [comment] 2017-09-06 16:17
Not in this case (that also shows as `x`).  We need to name the arrow function itself.

**Comment by vsmenon** [comment] 2017-09-06 16:21
The behavior we're seeing appears to be part of the JS spec:

http://www.ecma-international.org/ecma-262/6.0/index.html#sec-setfunctionname

**Comment by matanlurey** [comment] 2017-09-06 16:22
Ah I missed that, awful.

**Comment by vsmenon** [comment] 2017-09-06 16:36
More on names:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

**Comment by jmesserly** [comment] 2017-09-06 17:22
So I think this one is pretty different from #30636 (naming an anonymous closure). Here the problem is our generic functions are getting bad names.

My suggestion to fix this would be to remove the closure and double call we currently do for generic functions/methods. I was already looking into this for performance reasons. So the generic type arguments will become normal arguments on the JS side, that should both improve speed and also fix the function/method name in stack traces.

**Comment by leafpetersen** [comment] 2017-09-06 17:43
> My suggestion to fix this would be to remove the closure and double call we currently do for generic

Sounds reasonable to me.  I've been having similar thoughts about some of our uses of generic types.  For example, I see code that looks like:

```
var a =  GenericType$(T).as(someObject);
```

It's kind of a shame to go to all of the trouble of creating and/or looking up the class for `GenericType$(T)` just to then presumably deconstruct it.  One option there would be to use a similar pattern for direct generic instantiations:

```
var a = GenericType$.as(T, someObject);
``

**Comment by jmesserly** [comment] 2017-09-06 18:07
Regarding:

> `var a = GenericType$.as(T, someObject);`

Note that still requires the ability to construct types e.g. if `T` was a generic type like `Iterable<T>`. But removing one level would still help. For example, may of JSArray's covariance checks are of the form `param as Iterable<E>` ... so if we could generate `Iterable._check(E, param)` vs `IterableOfE()._check(param)` that seems like an improvement.

> I've been having similar thoughts about some of our uses of generic types. 

oh, definitely. There's a ton of room to optimize generic classes. I wonder if we should start a design doc. I've been thinking about getting rid of the closing-over-type-parameter thing in general. It might help performance. It's a much deeper change though :). And while it might speed up construction and reduce all of the type caching we do, it might make covariance checks more expensive (we'd have to extract the type `E` from the instance type somehow)

**Comment by jmesserly** [comment] 2017-09-07 07:59
https://dart-review.googlesource.com/c/sdk/+/3745

**Closed** 2017-09-07 18:08 UTC
Labels: area-dev-compiler, P1 high, Type: bug
