### ISSUE TITLE
Packages with example apps opted-in for null safety fail the null safety checks

### ISSUE THREAD

**Issue by amirh** [dart-lang/sdk#44013] opened 2020-10-31 23:26 UTC
This came up in https://github.com/flutter/flutter/pull/69440#issuecomment-719877525 where a bunch of `flutter/plugins` packages started failing on CI.

@zanderso and @leafpetersen pointed out that the failing packages included example apps with no Dart SDK constraints which means they are treated as opted-in for null safety.

While the `flutter/plugins` packages are fixed in https://github.com/flutter/plugins/pull/3240 it's somewhat worrying that many other packages in the ecosystem will take a similar hit.

I counted the affected packages across pub and there are currently 725 packages with example apps that are opted-in for null safety (most likely unintentionally as null safety isn't launched yet).

698 of these packages are actually not opted-in for null safety (e.g the root `pubspec.yaml` isn't opted-in while `example/pubspec.yaml` is opted in).
For these 698 packages I believe it should be safe to assume that the sdk constraint in `example/pubspec.yaml` should be intersected with the sdk constraints of the root `pubspec.yaml`. So it's fairly easy to automate the fix.

The list of the 698 "fixable" packages is available [in this sheet](https://docs.google.com/spreadsheets/d/1eh-wBnOzgx4lMCPVnJmQs_h_9F9jRXgthdmZtjRyRvs/edit?usp=sharing).

I'm happy to send PRs using [dart_lsc](https://github.com/amirh/dart_lsc/tree/master/packages/dart_lsc) to fix `example/pubspec.yaml` for as many of these 698 packages as possible.
I guess another alternative to consider would be to somehow teach the analyzer that the example app's sdk constraint cannot be wider than the package's sdk constraint.

cc @mit-mit @csells

**Comment by mit-mit** [comment] 2020-11-02 13:14
The root cause here is that when a project doesn't have an SDK lower bound, no language version is written into `.dart_tool/package_config.json`. 

Proposal: Make a change to the `pub` command to make it a warning not to have a Dart SDK constraint, and to default to a lower-bound of `2.0.0`:

```
Warning: pubspec.yaml has no SDK constraint lower bound; defaulting to 2.0.0.
You should edit pubspec.yaml to contain an SDK constraint:

environment:
  sdk: '>= 2.0.0 <3.0.0'
```

**Comment by mit-mit** [comment] 2020-11-02 13:29
Jonas logged https://github.com/dart-lang/pub-dev/issues/4208 for the potential pub change. Please thumbs up/down/comment there for that proposal.

**Comment by leafpetersen** [comment] 2020-11-10 18:26
We have reports of users downstream of packages that have no lower sdk constraint getting broken on master.  For example, [these](https://github.com/flutter-webrtc/dart-sdp-transform/blob/master/pubspec.yaml) [two](https://github.com/cloudwebrtc/dart-events/blob/master/pubspec.yaml) packages are broken on master.  I see two options here:
  - Manually fix up the broken packages on pub (may be difficult to get PRs landed)
  - Change the interpretation of missing lower bounds to mean "2.7" instead of "latest".

I think we likely need to do one or the other for beta.  cc @franklinyow @jonasfj @natebosch @lrhn @jakemac53 @munificent

**Comment by franklinyow** [comment] 2020-11-10 18:54
@leafpetersen 
Are you saying that we need additional work in additional to https://github.com/dart-lang/pub/issues/2707?

**Comment by amirh** [comment] 2020-11-10 19:01
List of affected packages: https://docs.google.com/spreadsheets/d/1b3zD8TGfl6yxSJF-ZXjzg0hKluY-kXWcIPVF-5hUiME/edit#gid=513901545

**Comment by mit-mit** [comment] 2020-11-11 16:27
Discussed in language team, and agreed that:
  * Keep the current ERROR when resolving a pubspec that itself is missing one or more parts of the upper/lower Dart SDK constraint
  * Add new logic in `pub get` that _for dependencies_ which do not have a lower constraint in their pubspec, defaults the language version to 2.7, and write that to the package config

**Comment by leafpetersen** [comment] 2020-11-12 03:25
I filed issues for the known tools that need to change here:
  - https://github.com/dart-lang/sdk/issues/44159
  - https://github.com/dart-lang/sdk/issues/44160
  - https://github.com/flutter/flutter/issues/70349

I'm assuming this issue will cover the pub work - if not @jonasfj can you file one there?

**Comment by mit-mit** [comment] 2020-11-12 13:46
Pub was updated in https://github.com/dart-lang/pub/pull/2748

**Comment by jonasfj** [comment] 2020-11-12 13:57
Rolled in https://dart-review.googlesource.com/c/sdk/+/171720

**Closed** 2020-11-12 15:14 UTC
Labels: NNBD, P1, area-language

**Comment by jonasfj** [comment] 2020-11-12 15:56
@pcsosinski @franklinyow, have beta been cut yet? If so we would like to cherry-pick: 4b3840d01ddfed57374b872927a03921077614b0
(I can't seem to find a branch that looks like it is beta for 2.12 -- maybe I'm just missing something obvious :D)

**Comment by jonasfj** [comment] 2020-11-12 16:09
Filed cherrypick request: https://github.com/dart-lang/sdk/issues/44176

**Comment by timsneath** [comment] 2020-11-12 17:14
@mit-mit Will this behavior (default for packages missing SDK constraint) be documented somewhere on dart.dev?

**Comment by mit-mit** [comment] 2020-11-13 10:33
We weren't planning on documenting this particular change. Note that we didn't change the behavoir for running `pub get` in a directory with a pubspec not containing an SDK constraint. That continues to be an error (as described in the breaking change).

But this makes a small tweak to the behavoir when you run pub get on a pubspec that contains a dependency, and the pubspec of that dependency doesn't have an SDK constraint. In that case, we default the dependency to be 2.7. The owner of the dependency will get the error when they pub get, so they already have the needed message (and docs for that).

**Comment by leafpetersen** [comment] 2020-11-13 16:16
> We weren't planning on documenting this particular change

Agreed.  This change just makes existing packages continue to work, all new packages will be required to have an sdk constraint.
