### ISSUE TITLE
Auto import (or quickfix?) for Extensions

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#38894] opened 2019-10-15 14:58 UTC
_I am opening this issue as @scheglov  asked for at https://github.com/dart-lang/sdk/issues/25820#issuecomment-541972606_

I am having problem with auto completing the new Extension Functions from dart 2.6.0. I have added a new file called "time.dart" with some extensions, like this:

![image](https://user-images.githubusercontent.com/1146982/66782397-f93f3c00-eeab-11e9-8b8e-80d778631993.png)

My main file just can't auto complete it. If I try to **quickfix** the error I get the following:

![image](https://user-images.githubusercontent.com/1146982/66782446-0fe59300-eeac-11e9-9c72-d6170f408416.png)

As soon as I move the extensions to the same file as main, everything works:

![image](https://user-images.githubusercontent.com/1146982/66782486-2855ad80-eeac-11e9-8510-3cb5b424fd3c.png)

If I add the import manually, it also works:

![image](https://user-images.githubusercontent.com/1146982/66782625-7ff41900-eeac-11e9-8280-eba82d565524.png)

My Dart for Intellij plugin version is **192.6817.14**

**Comment by ThinkDigitalSoftware** [comment] 2020-03-07 21:01
Looks like this is fixed now in the latest master

**Comment by DanTup** [comment] 2020-05-06 11:15
@bwilkerson @ThinkDigitalSoftware as far as I can see, this isn't working (in the most recently nightly build):

### Shows up if imported

<img width="400" alt="Screenshot 2020-05-06 at 12 12 40" src="https://user-images.githubusercontent.com/1078012/81170683-02504180-8f93-11ea-90cd-978489c6ae88.png">

### No completion if not imported

<img width="388" alt="Screenshot 2020-05-06 at 12 12 20" src="https://user-images.githubusercontent.com/1078012/81170721-0f6d3080-8f93-11ea-9147-7450acb008df.png">

### No quickfix

<img width="378" alt="Screenshot 2020-05-06 at 12 12 30" src="https://user-images.githubusercontent.com/1078012/81170725-1136f400-8f93-11ea-85cb-025a821e7d5f.png">

**Comment by bwilkerson** [comment] 2020-05-06 14:24
@jwren Using a build from yesterday morning (and IntelliJ), I'm seeing the completion when the library has been imported, but I am not seeing a completion when it has not been imported, nor any kind of quick fix (I'm not even getting 'Extract Method').

**Comment by scheglov** [comment] 2020-05-06 20:09
I don't think this can work when the extension is not imported.

Available declarations don't have enough type information to support type matching in general case.

One thought that I had recently is that I like how completion in Cider works, with limiting the number of suggestions transferred, an ability to transfer more if necessary, server-side initial filtering, and re-request if the filter changes. This keep amount of data transferred limited, and still allows full power of types in the server.

**Comment by bwilkerson** [comment] 2020-05-06 20:43
> I don't think this can work when the extension is not imported.

What if we cached (either in available declarations or elsewhere) a map from the names of extended types (without type arguments) to the (paths of) libraries containing extensions of those types. I'm guessing that for any given type name the list of library paths would be fairly small and that we could then access the elements for those libraries, checking that the actual types match the target type, and add suggestions for the members of the extension.

> One thought that I had recently is that I like how completion in Cider works ...

That's valid, but I don't think it's necessary in order to make completion work in this case. Nor can we force our clients to adopt the Cider model.

If necessary I suppose we could implement this functionality only for Cider-like clients, but I'd rather try to find a more general solution first.

**Comment by scheglov** [comment] 2020-05-06 22:43
Ah, I'm sorry, I was thinking about free standing identifiers when stated that it will not work because of available declarations. Here we do have the target.

Yes, I think this could be done with caching of potentially applicable extensions.

**Comment by DanTup** [comment] 2020-05-07 07:50
> One thought that I had recently is that I like how completion in Cider works, with limiting the number of suggestions transferred, an ability to transfer more if necessary, server-side initial filtering, and re-request if the filter changes

Slightly off-topic, but this is something I often think about for VS Code/LSP (in the context of performance, esp. for LSP where we can't preload all the available suggestions onto the client). There's support for going back to the server as the user types in both LSP and VS Code's APIs (though not adding more to the list asynchronously if the user didn't type) but I worry a little about:

1. Increased latency because the filtering now has round trips (including JSON serialisation/deserialisation of potentially large numbers of items)
2. Increase resource usage because of transferring a lot of the same items repeatedly

It might be something worth testing out though (though VS Code currently does fuzzy matching and accounting for transposed letters, so to keep the same behaviour that would need to be done on the server too).

**Comment by vanlooverenkoen** [comment] 2020-07-23 21:22
Any update on this?

**Comment by bwilkerson** [comment] 2020-07-23 22:37
Not yet, but it's definitely something we would like to have working.

**Comment by vanlooverenkoen** [comment] 2020-07-24 05:49
Any idea of a timeframe?

**Comment by devoncarew** [comment] 2020-07-24 15:28
@vanlooverenkoen, thanks for the ping; watching this issue is the best way to know about any progress.

**Comment by vanlooverenkoen** [comment] 2020-07-24 15:30
Yes indeed. Because we are using a lot of extensions in our projects. But it also takes a lot of time to manually import them every time you need them. :( it would be nice to have a timeframe.

**Comment by m-Skolnick** [comment] 2020-08-03 15:53
> As a dirty workaround, you can declare a fake type in the extensions' library. Like
> 
> ```
> const ext = 0;
> ```
> 
> Then in your target file, start typing "ext" - to auto-import the library needed.
> All its extensions are visible then in suggestions.
> 
> At least, this saves a lot of time now.

This same effect can be achieved by using a named extension. 

    extension StringExtensions on String {
        // Your extensions
    }

Typing the name of the extension will show the import suggestions. 

This is still not a solid solution. I'm personally sticking with Utils classes until Extensions are usable without manually adding the imports.

**Comment by gbaldeck** [comment] 2020-09-18 20:29
Guys, it's been almost a year now and this is still not working in IDE's. Autocomplete is what makes extension functions useful. Without that you might as well use a Util class since you will at least get some autocomplete.

Not having tooling support around a major feature like this cripples the feature. Might as well have not added it as a language feature.

**Comment by JulianBissekkou** [comment] 2020-11-04 07:12
Any updates on this issue? 🧐

**Comment by i-show** [comment] 2020-11-04 08:15
Following

**Comment by pedromassango** [comment] 2020-11-04 11:58
Hi @JulianBissekkou @i-show and anyone seeing this.

Using "add reaction" on the initial comment would increase priority while +1 comments are rather pointless and cause lots of people to get notified for no reason.

To get notified yourself, use the [Subscribe] button to the top right instead.

**Comment by vanlooverenkoen** [comment] 2020-11-04 12:04
@pedromassango Indeed +1 should be used increase priority. 

that said. this ticket is in the top 10 issues on github. But there is no activity on this ticket. Is there a reason why this ticket is already open for more than a year? and still in the top 10?

**Comment by shinayser** [comment] 2020-11-04 13:49
> @pedromassango Indeed +1 should be used increase priority. 
> 
> that said. this ticket is in the top 10 issues on github. But there is no activity on this ticket. Is there a reason why this ticket is already open for more than a year? and still in the top 10?

My I ask how can we see the top 10 most up voted?

**Comment by vanlooverenkoen** [comment] 2020-11-04 13:50
> > @pedromassango Indeed +1 should be used increase priority.
> > that said. this ticket is in the top 10 issues on github. But there is no activity on this ticket. Is there a reason why this ticket is already open for more than a year? and still in the top 10?
> 
> My I ask how can we see the top 10 most up voted?

https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

![image](https://user-images.githubusercontent.com/21172855/98119610-21318100-1ead-11eb-8d51-7c5fd03b9895.png)

**Comment by pedromassango** [comment] 2020-11-04 14:39
> @pedromassango Indeed +1 should be used increase priority.
> 
> that said. this ticket is in the top 10 issues on github. But there is no activity on this ticket. Is there a reason why this ticket is already open for more than a year? and still in the top 10?

The Dart team is focused on other important features such as Null-Safety, they may get back into this once they are done with other important tasks.
I really want this as well because I own a [package](https://github.com/pedromassango/build_context) that is useless without this but all we can do is to wait.

**Comment by hpoul** [comment] 2020-11-04 14:45
@pedromassango 
> but all we can do is to wait.

or create a PR 😅️ - but a stupid question: Which code is actually affected by this? I think the actual [intellij plugin is provided by jetbrains](https://github.com/JetBrains/intellij-plugins/tree/master/Dart)? But this would probably be mostly in the analyzer (or lsp server?) to provide auto completion?

**Comment by bwilkerson** [comment] 2020-11-04 16:17
> Is there a reason why this ticket is already open for more than a year?

Primarily because of resource constraints. We appreciate both the importance of and demand for this feature, and yes, I too hope that we can address it after Null Safety has shipped.

> ... I own a package that is useless without this ...

I believe that you mean that the lack of this feature significantly reduces the discoverability of the extensions in your package, but if there's a different meaning that I missed, please let us know.

> Which code is actually affected by this?

The fixes for both requests would be in the [`analysis_server`](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server) package.

**Comment by esDotDev** [comment] 2020-12-01 23:10
Since extensions tend to be used project-wide, what we do to make them 'usable' is group one file that is something like this:
```export 'package:provider/provider.dart';
export 'package:sized_context/sized_context.dart';
export 'package:time/time.dart';```

Name it something like 'extensions' and it's easy to import. 

Having first class support for this would be great. Seems like you should be able to use the type of the thing, to lookup any members/fields on the class, as well as any extensions that exist in the project? 

For example, using `context.` why would auto-complete not be able to find the Context extensions from Provider?

**Comment by MatrixDev** [comment] 2021-01-18 13:17
one and a half years have passed... and... still no progress/comments. nice work, Dart team.

**Comment by devoncarew** [comment] 2021-01-19 17:07
@MatrixDev, the tone of your comment is not appropriate. Please review the Dart and Flutter team's code of conducts:

- https://dart.dev/code-of-conduct
- https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

In particular, discussions here need to be respectful and courteous.

**Comment by vishalrao8** [comment] 2021-01-19 19:07
+1 This issue needs to be resolved.

**Comment by shinayser** [comment] 2021-01-19 19:14
The MatrixDev comment was very indelicate, but I understand his deasapointment.

I know Dart Team is now 100% focused on solving the biggest update since 2.0, which is NNDB. But I hope that after that the developers could give some love to the completion area, which is by far, the worst area of the language.

**Comment by vishnuagbly** [comment] 2021-03-19 15:35
really looking forward to this update, will be most helpful

**Comment by dagba** [comment] 2021-03-29 18:32
omg, still no steps to resolve this problem...

**Comment by joelbrostrom** [comment] 2021-04-01 08:54
<details>
<summary>
> Since extensions tend to be used project-wide, what we do to make them 'usable' is group one file that is something like this:
</summary>
> 
> ```
> export 'package:provider/provider.dart';
> export 'package:sized_context/sized_context.dart';
> export 'package:time/time.dart';
> ```
> 
> Name it something like 'extensions' and it's easy to manually import. You can go a step further and make a little mixin to do this import too, making it even easier:
> 
> ```
> export 'package:provider/provider.dart';
> export 'package:sized_context/sized_context.dart';
> export 'package:time/time.dart';
> 
> mixin ExtensionsMixin {}
> ```
> 
> Having first class support for this would be great. Seems like you should be able to use the type of the thing, to lookup any members/fields on the class, as well as any extensions that exist in the project?
> 
> For example, using `context.` why would auto-complete not be able to find the Context extensions from Provider?
</details>

Brilliant!
I'll definitely git it a try.
Thanks.

**Comment by TheWCKD** [comment] 2021-04-20 07:26
With all due respect to Dart devs and community, I really love Dart and have a ton of appreciation for everyone involved in this. 

However, this issue is the kind of issue that drags down every other amazing aspect of Dart, and to be honest, this is not the right way of doing it. 

People should have questions and issues on more delicate problems for more advanced packages and not for a literally basic and critic feature like this one reported here. 

What is this "importing the file in which the extension is located" feature so different from "importing the material.dart file in which the MaterialApp widget is located"? 

Why is this so difficult to implement? Instead of focusing on huge breaking changes like null safety, you should've focused in the first place in getting the entire language stable and functional. People wouldn't leave the language if they had to double check nullability, but they could leave really fast if simple features like this one aren't available. 

This is not an ordinary issue, with 1-2 likes. It's really, really requested and it is a really huge drawback of Dart language and yet not a single developer from your team didn't had the time to work on it. It simply defeats the purpose of extensions at all to he honest. 

If someone could really point me the file in the static analyzer where Dart searches for a library or file containing an extension, I'd be happy to take a look and try to implement a fix and maybe make a PR. It shouldn't be so hart since all the analyzer has to do is to search for the right extension extending the right class.

**Comment by bwilkerson** [comment] 2021-04-20 18:41
I understand your frustration and appreciate the fact that you're still talking to us. I can't address the resource allocation question (because I don't have any information about it other to say that this support is something we hope to address soon), but I can take a stab at discussing the technical side.

> Why is this so difficult to implement?

It isn't difficult in the sense of being technically challenging. We know what needs to be done, but it's a non-trivial amount of work to make the necessary changes.

It boils down to the fact that portions of our code completion support were designed before there were extension members and it was designed in a way that doesn't support the requirements we have when supporting extension members. We just need to update the underlying code so that it does support those requirement. Not an uncommon experience in software development.

For more details, read on.

When the analysis server computes completion suggestions it does so by looking in the current library, the type hierarchy of the target (if there is a target) and the libraries that are imported by the current library. That gets most of the suggestions, but doesn't help with declarations that have not yet been imported.

Awhile back (before extension methods) we added support for declarations that could be imported but are not yet imported. Our first attempt was to look at all of the libraries that could be imported in the same way that we look at the already imported libraries. Unfortunately, that made code completion too slow, which significantly degraded the user experience. There were multiple reasons for the poor performance, but I'll skip over those details for now.

Our solution was to cache information about those libraries up-front. We're limited in the kind of information we can cache because of memory constraints. So what we cache is the information that a given name is defined in a given library and what kind of thing it's declared to be (class, top-level function, etc.). The cache only includes the names of top-level and static declarations. Because we look at the type hierarchy when there's a target there was no need to store instance members; we find them through the type hierarchy.

Unfortunately, that structure doesn't provide enough information to allow us to know which extension methods can be applied to a given target. The same limitations on the kind of information we can cache make it impossible for us to cache the data we really need, so we're going to have to cache enough information to tell us when there might be extension members to suggest and we'll have to do some extra work when computing the actual suggestions to determine whether the suggestions are valid.

**Comment by TheWCKD** [comment] 2021-04-20 19:06
> I understand your frustration and appreciate the fact that you're still talking to us. I can't address the resource allocation question (because I don't have any information about it other to say that this support is something we hope to address soon), but I can take a stab at discussing the technical side.
> 
> > Why is this so difficult to implement?
> 
> It isn't difficult in the sense of being technically challenging. We know what needs to be done, but it's a non-trivial amount of work to make the necessary changes.
> 
> It boils down to the fact that portions of our code completion support were designed before there were extension members and it was designed in a way that doesn't support the requirements we have when supporting extension members. We just need to update the underlying code so that it does support those requirement. Not an uncommon experience in software development.
> 
> For more details, read on.
> 
> When the analysis server computes completion suggestions it does so by looking in the current library, the type hierarchy of the target (if there is a target) and the libraries that are imported by the current library. That gets most of the suggestions, but doesn't help with declarations that have not yet been imported.
> 
> Awhile back (before extension methods) we added support for declarations that could be imported but are not yet imported. Our first attempt was to look at all of the libraries that could be imported in the same way that we look at the already imported libraries. Unfortunately, that made code completion too slow, which significantly degraded the user experience. There were multiple reasons for the poor performance, but I'll skip over those details for now.
> 
> Our solution was to cache information about those libraries up-front. We're limited in the kind of information we can cache because of memory constraints. So what we cache is the information that a given name is defined in a given library and what kind of thing it's declared to be (class, top-level function, etc.). The cache only includes the names of top-level and static declarations. Because we look at the type hierarchy when there's a target there was no need to store instance members; we find them through the type hierarchy.
> 
> Unfortunately, that structure doesn't provide enough information to allow us to know which extension methods can be applied to a given target. The same limitations on the kind of information we can cache make it impossible for us to cache the data we really need, so we're going to have to cache enough information to tell us when there might be extension members to suggest and we'll have to do some extra work when computing the actual suggestions to determine whether the suggestions are valid.

Thank you so much for your kind words and really, really detailed explanation. I understood why this is a limitation currently, I don't know why I believed that the analyzer works by scanning all libraries, the performance issue would be indeed a huge drawback. 

Anyways, I hope you'll make progress on this issue soon, of course, when you'll have more time for it. Cheers!

**Comment by webstoreportal** [comment] 2021-05-14 00:10
+1 for explicit show/hide combinator support 

_context: coming from_
```dart
import 'package:flutter_bloc/flutter_bloc.dart' 
    show ReadContext, SelectContext;

BuildContext context = ...;
context.select()
context.read()

/// provider-5.0.0 provider.dart
extension ReadContext on BuildContext {
...
}
/// provider-5.0.0 inherited_provider.dart
extension SelectContext on BuildContext {
...
}
```
---
_tangential: exacerbates issues when using dart library part / part of importing explicit show/hide combinators for extensions_
https://pub.dev/documentation/analyzer/latest/dart_ast_ast/Combinator-class.html

**Comment by lty5240** [comment] 2021-05-23 12:02
I think  , we can use yaml to import custom extensions , just like assets ??, It’s easy

**Comment by atreeon** [comment] 2021-06-01 13:41
Possible Intellij workaround: for extension String_Extension on String

type String_Ext and when autocomplete offers the full extension name press enter; that will include the extension reference at the top of your code.

_(this is a workaround and not a proper solution but I think this is the best work around I've found and I hope it helps you a little bit)_

https://user-images.githubusercontent.com/4139336/120333071-3eb1b680-c2e7-11eb-8790-a9daed5606cd.mov

**Comment by kuhnroyal** [comment] 2021-06-01 14:16
> type String_Ext and when autocomplete offers the full extension name press enter; that will include the extension reference at the top of your code.

Yea sure, when you know that `String_Extension` exists and that it contains the function you are looking for.
But the main idea for an IDE autocomplete is more like: "Hey IntelliJ, I have a property here, show me what I can do with this!".

**Comment by firatcetiner** [comment] 2021-06-01 14:19
> > type String_Ext and when autocomplete offers the full extension name press enter; that will include the extension reference at the top of your code.
> 
> Yea sure, when you know that `String_Extension` exists and that it contains the function you are looking for.
> But the main idea for an IDE autocomplete is more like: "Hey IntelliJ, I have a property here, show me what I can do with this!".

Well, it's a workaround not a fix. Its also better than manually importing the file.

**Comment by atreeon** [comment] 2021-06-01 15:39
@kuhnroyal if your extension names follow a good naming conventions then it should be fairly easy to identify the name of the extension.

**Comment by jodinathan** [comment] 2021-06-01 17:46
> @kuhnroyal if your extension names follow a good naming conventions then it should be fairly easy to identify the name of the extension.

what if I added some extension packages to my project and would like that the autocomplete show me the methods that the packages add to my variables and functions?

**Comment by atreeon** [comment] 2021-06-02 21:39
@jodinathan as I say, it is just a work around to import your extension more easily. It is not a solution, just a way to make the import of the extensions easier (although maybe I should stay quiet in future!)

**Comment by bwilkerson** [comment] 2021-06-02 22:06
I should have been a bit more diligent about providing updates, but there are a couple of improvements that I can share. I don't know when these changes will make it into a release, but they are on master and will roll out as soon as possible.

The first was in https://dart-review.googlesource.com/c/sdk/+/201021. This CL causes server to stop using the available suggestion support for already imported libraries. The impact of this is that server should now suggest extension methods if they are defined in libraries that are already being imported. It obviously won't help with discovering extension methods that are not yet imported, but it's at least one part of the issue.

The second was in https://dart-review.googlesource.com/c/sdk/+/201800 in which we added support for a quick fix to add an import when there's a reference to an extension method in an extension that isn't yet imported. If you type (or paste) code that references `Iterable.lastWhereOrNull` and it isn't found, we can fix the reference by adding an import of `package:collection/collection.dart`. Again, it doesn't help with discovery, but hopefully it will occasionally be useful.

**Comment by kasperpeulen** [comment] 2021-09-05 19:19
@bwilkerson 

> If you type (or paste) code that references Iterable.lastWhereOrNull and it isn't found, we can fix the reference by adding an import of package:collection/collection.dart.

If which version of Dart should this work?

I tried typing, `2.seconds`, but it didn't suggest an import.

![image](https://user-images.githubusercontent.com/1035299/132138831-46533d59-169e-4864-a84c-aaa8bd71179e.png)

**Comment by bwilkerson** [comment] 2021-09-07 19:35
> If which version of Dart should this work?

I don't know. I used to know a way to figure which release a CL was first shipped in, but it doesn't appear to work anymore. @devoncarew How would I (or anyone) figure this out?

> I tried typing, `2.seconds`, but it didn't suggest an import, while I have the time package in my pub installed.

Is the library that defines `seconds` imported into any library? It seems plausible that the analyzer might not have seen (and hence indexed) it if not, but I'm just making a guess at this point as I haven't had time yet to try to reproduce the issue.

**Comment by DanTup** [comment] 2021-09-08 08:36
> I used to know a way to figure which release a CL was first shipped in, but it doesn't appear to work anymore. @devoncarew How would I (or anyone) figure this out?

The way I usually check this is to grab the git hashes shown in Gerrit ("Change has been successfully rebased and submitted as xyz") and then find them on GitHub:

3cc518b3cce843be20a76111151a63c8d224b05e
25b71e07e7c724933e6bbcec7ca0a5050ed57da3

That shows the tags the change is in (I think it shows the earliest and latest tags by default, though you can expand to see them all):

![Screenshot 2021-09-08 at 09 29 22](https://user-images.githubusercontent.com/1078012/132474657-a8fb1e6b-9cfd-4906-8cd5-f74fb6ce611c.png)

If there's a vX.Y.Z-some-release-version listed (and the change wasn't reverted), I think the change usually ships in the following version. Both the CLs above are in v2.14.0-x.dev tags, so I think it's likely v2.14.0 of the Dart SDK would include them.

> Is the library that defines `seconds` imported into any library? It seems plausible that the analyzer might not have seen (and hence indexed) it if not, but I'm just making a guess at this point as I haven't had time yet to try to reproduce the issue.

I just tried this, and this does seem to be the case. If I have the package in `pubspec.yaml`, have run `pub get` and restart the anlaysis server, the fix still isn't present. If I import anything from that package into another file, then the fix to import it shows up.

**Comment by scheglov** [comment] 2021-09-08 15:20
We can "discover" all available files from all packages, and then resolve / index them as necessary. See `test_subtypes_discover`, which does not import 'package:bbb', but its subtype results become available because there is a dependency on this package. Note that we resolve in `Search.subtypes()` after doing pre-filtering by name, using `getFilesSubtypingName` (which is based on parsed / unresolved AST).

**Comment by Tasen-pro** [comment] 2021-09-10 10:10
Two years have passed

**Comment by Bringoff** [comment] 2021-09-21 14:36
Intellij supports "extended" auto-completion on second ctrl+space press for some languages. Dart plugin doesn't seem to leverage this. If scanning extensions is too extensive (pun intended), why not to hide it behind this "extended" autocomplete?

**Comment by qbait** [comment] 2021-09-22 07:59
That's the biggest productivity killer in Dart / Flutter.
(BTW I love Flutter <3)

**Comment by Andreigr0** [comment] 2021-09-22 08:02
It seems to be working in IntelliJ IDEA (Flutter plugin 60.1.4) with Stable Flutter 2.5.0 🤔

**Comment by Andreigr0** [comment] 2021-09-22 09:28
Hm, strange, a couple days ago I've noticed that IntelliJ suggests to import extensions, but now it doesn't work🤔

**Comment by alexander-shustanov** [comment] 2021-09-27 14:41
Without this feature, the extensions are completely useless! Do you have any plans to implement it?

**Comment by selcukguvel** [comment] 2021-11-03 19:37
As a workaround, we decided to put all extensions into a file and import it using a simple IntelliJ-based plugin we implemented. Basically, these are the steps: 
- Create a `.dart` file (let's say `extensions.dart`) and `export` all of your extension files in it like:
    - `export 'an_extension.dart';`
    - ...
- You need to import `extensions.dart` in the file where you want to access the extension methods of an object.
- You can import this file in two ways: (Other than copying and pasting the path of the `extensions.dart` each time tediously)
     - Defining an empty class inside `extensions.dart` and write the name of the class to import `extensions.dart`.
     - If you are using a IntelliJ-based IDE, download the **[Fast Import](https://github.com/selcukguvel/fast-import)** plugin, specify the path of the `extensions.dart` using **Fast Import -> Edit Path** and import it with the help of a shortcut easily.

**Comment by esDotDev** [comment] 2021-11-03 20:24
You can also just start typing a class you know is in the extensions file, and then choose it from the list of suggested imports. I do this constantly with `Provider` for example.

**Comment by Afur** [comment] 2021-11-04 09:38
![image](https://user-images.githubusercontent.com/14007961/140290975-b56f4de0-c2a3-4cab-a96a-b9bf4ef90794.png)

That's my temporary solution for that issue. The only think that I need to do is just start typing `Ext...` and IntelliSense provides this stub class which holds reference to every extension file in my project.

**Comment by 0ttik** [comment] 2021-11-04 20:06
> @Afur and how much refactoring will you need to do in order to change your code after code assist will start working as intended?

Don't see any problem with this. Basically, it's even usefull to have all extensions collected together. Also, you can refactor incrementally. Anyway, after code completion is working as intended, you can just remove this abstract class and go through all errors in project and add correct imports using IDEA hints with hotkeys if you want to refactor all at once, but I don't see real necessity in it.

**Comment by ipowell** [comment] 2022-02-04 21:41
This is working for me now. I just upgraded to 2.10.0, the current stable channel.

**Comment by bwilkerson** [comment] 2022-02-04 21:48
Excellent! Glad to hear it, and thanks for letting us know.

**Comment by esDotDev** [comment] 2022-02-04 22:01
I have seen this working in beta for a while, but it seems only when I write the entire method name perfectly, then I can import. Is that what everyone else is seeing?

```
extension Foo on String {
  blah() => print(this);
}
```

![image](https://user-images.githubusercontent.com/736973/152609019-24c9f013-c406-45f0-83f6-2e48e131ad94.png)

Works with `blah` though.

**Comment by m-skolnick** [comment] 2022-02-04 22:04
@esDotDev That is what I'm seeing as well. It's not very helpful. 

When I saw the comment from @ipowell I was hoping that the extension would show in the autocomplete options. For example, in the below pic I would expect that `myExtensionMethod` would show in the options window even though the file with the extension is not imported. 

![Screen Shot 2022-02-04 at 5 01 58 PM](https://user-images.githubusercontent.com/24857258/152609312-a9aed1d7-7175-4f88-bffd-cd744e41f5cc.png)

**Comment by bwilkerson** [comment] 2022-02-04 22:07
Yes, the piece to get extension members from extensions in libraries that are not yet imported still isn't complete.

**Comment by shinayser** [comment] 2022-02-04 22:17
Hey @bwilkerson this sounds a very important feature to add to the language, but considering the time I've opened the issue and it isn't fixed, I can assume that definitely is not an easy task.

Perhaps you can explain to us the difficulty of that issue? Maybe we can try to find a workaround and open an PR :)

**Comment by bwilkerson** [comment] 2022-02-04 23:38
It's definitely an important feature. The delay is primarily a result of (a) the current architecture of the code completion support and (b) limited resources.

When we first decided to start suggesting completions from libraries that weren't imported (about three years ago), we first tried the simple tactic of just adding the suggestions to the completion results. Unfortunately, this had some performance issues due to (a) having to process all of the elements from these un-imported libraries in order to create suggestions, and (b) the large amount of data that was being sent from the the server to the client (the IDE). These issues led to an unusable code completion experience.

So we designed a new protocol. The new protocol, which we're still using today, allowed the server to send all of the suggestions from un-imported libraries during the initial analysis and to keep it updated if the user changed which packages were available to a given package. That protocol was designed before extensions were introduced into the language and isn't flexible enough to support extension members.

We have considered changes to the protocol, and that's still an option that we're discussing, but we're currently looking at other approaches.

We changed our use of the protocol slightly, which is what allows us to suggest extension members if the package defining the extension is already imported. Initially we decided to use the same ahead-of-time computation of suggestions for imported libraries as for un-imported libraries. Now we're back to computing and sending suggestions from imported libraries at the time that completion suggestions are requested.

Recently we've seen some performance problems in code completion, and after some investigation we're now looking into a more radical change to the protocol. We're basically investigating using a protocol similar to the one LSP defines. The new protocol would allow the server to send back a small portion of the total list, allowing the client to control how much of the list should be returned.

If that work is successful, not only should it improve performance, but it should also allow us to compute suggestions from un-imported libraries when completions are requested, which should then allow us to include suggestions for extension members.

Thanks for the offer to help. I'm not the primary developer working on the new protocol, so I'm not sure how you could best contribute. I think that most of the work in the analysis server is completed and now we're working on finishing the work on the client side so that we can start testing it end-to-end.

**Comment by shinayser** [comment] 2022-02-05 00:04
Those are amazing news @bwilkerson. We're very excited to see the result of all your efforts!

I am a completion maniac myself, so if you fold need some guy like me to test that stuff, just call me :)

**Comment by srawlins** [comment] 2022-07-20 22:05
@scheglov can you confirm you implemented this?

**Comment by scheglov** [comment] 2022-07-20 22:12
Works for me.

1. Completion.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/384794/180091130-aa348f26-aeb6-4e0a-bda9-e80bc20d330a.png">

2. Quick fix.
<img width="541" alt="image" src="https://user-images.githubusercontent.com/384794/180091183-fe493dde-8395-4ffe-bd99-a95593a04057.png">

**Closed** 2022-07-20 22:12 UTC
Labels: area-analyzer, analyzer-completion, analyzer-server, analyzer-quick-fix, P2, type-enhancement

**Comment by JulianBissekkou** [comment] 2022-07-21 05:08
Thanks to everybody that was involved in this feature. It works really smooth 👍🏽

**Comment by naamapps** [comment] 2022-07-22 15:41
Hi,
How can get to use this feature?
I'm using vscode with latest flutter and Dart plug-in versions but this doesn't seem to work for me. 
Do I need to set a setting or update something?
Thanks

**Comment by scheglov** [comment] 2022-07-22 15:43
As you can see, I use IntelliJ, but at least quick fix should work in VS Code as well.
Does it work for you?

**Comment by naamapps** [comment] 2022-07-22 15:45
Sorry, I must have missed that.
Yes the quick fix is working, but autocomplete doesn't work.
Can we expect autocomplete to arrive to vscode soon?

**Comment by scheglov** [comment] 2022-07-22 15:46
@DanTup for VS Code completion insides :-)

**Comment by shinayser** [comment] 2022-07-22 15:51
@scheglov do we need to update dart to some specific version to get this working?

**Comment by scheglov** [comment] 2022-07-22 15:56
The changes, at least for quick fixes, were done in 979f3ea79ee188ec2e0c039a3186ebd28e0f636c.
And for code completions about the same time.
So, I expect that these are available in 2.17 Dart.

**Comment by shinayser** [comment] 2022-07-22 16:40
Ok I tested and it worked on some scenarios.

I believe I know why I haven't realized that change before and that is because our dependencies are transient.

I have a module that imports a dependencies module, and because of that the extensions doesn't work. Was it an intended behavior?

**Comment by DanTup** [comment] 2022-07-25 09:42
@shinayser my understanding is that this is intended. Any packages you directly depend on should be listed in your `pubspec.yaml` (so you can set constraints and ensure they're always available even if other dependencies stop depending on them). As a result, completion/fixes/etc. will only suggest from those packages (if it didn't, code completion would contain a large number of classes from transient dependencies that not be wanted).

There's a related lint at https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html.

**Comment by naamapps** [comment] 2022-07-25 09:45
@DanTup Any news about this feature arriving to vscode? :)

**Comment by DanTup** [comment] 2022-07-25 10:40
@naamapps the quick-fix should already work today. Showing up in the completion list and auto-importing requires using a new completion API so isn't available in stable yet, although it is working behind a flag in the latest bleeding-edge/master SDK builds:

<img width="681" alt="Screenshot 2022-07-25 at 11 30 30" src="https://user-images.githubusercontent.com/1078012/180756757-b2f609b3-5ed9-48e5-8043-3455a2321ebd.png">

I'm not ready to make it default/remove the flag yet (I've still been fixing some issues fairly recently), but it's getting there.

**Comment by naamapps** [comment] 2022-07-25 10:45
Thanks for the quick reply @DanTup.
Looking forward to use this feature 👍

**Comment by Adrian-Samoticha** [comment] 2022-07-25 12:51
> @naamapps the quick-fix should already work today. Showing up in the completion list and auto-importing requires using a new completion API so isn't available in stable yet, although it is working behind a flag in the latest bleeding-edge/master SDK builds:
> 
> ---
> 
> I'm not ready to make it default/remove the flag yet (I've still been fixing some issues fairly recently), but it's getting there.

This is great to hear. I'm looking forward to using this feature as well.

**Comment by DanTup** [comment] 2022-07-25 13:26
@shinayser there's some similar discussion at https://github.com/dart-lang/sdk/issues/43678#issuecomment-847782349. The suggestion was allowing the "common dependencies module" to record which of its dependencies it exposes to packages that depend on it. The response was that this should be filed against Pub, although I can't see any obvious issue that was raised about this, so perhaps it's worth filing one there to start a discussion.

**Comment by shinayser** [comment] 2022-07-25 13:36
> @shinayser my understanding is that this is intended. Any packages you directly depend on should be listed in your `pubspec.yaml` (so you can set constraints and ensure they're always available even if other dependencies stop depending on them). As a result, completion/fixes/etc. will only suggest from those packages (if it didn't, code completion would contain a large number of classes from transient dependencies that not be wanted).
> 
> There's a related lint at https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html.

Thanks for your reply!
I understand your point but it is a common pattern on some monorepo architectures to concentrate all the dependencies on a common "dependencies" module. So we would never get code completion on larger products because of this limitation.

You think I should open another issue to report that? Maybe we could think on a different solution. Maybe adding s tag to the pubspec to include those dependencies to the auto complete algorithm?
