### ISSUE TITLE
identical() for strings is not transitive

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27681] opened 2016-10-27 22:48 UTC
``` dart
void main() {
  String ab = 'ab';
  print(identical('a' + 'b', 'ab')); // true, compile-time constant evaluation                                                                                                 
  print(identical('ab',       ab)); // true, compile-time constant de-duplication                                                                                              
  print(identical('a' + 'b',  ab)); // false??                                                                                                                                 
}
```

**Comment by lrhn** [comment] 2016-10-28 09:23
I assume this is the VM.

All of the expressions are compile-time constants, so the results should all be `true`.

**Comment by lrhn** [comment] 2016-11-01 16:24
There actually does seem to be a bug in the VM:
```dart
var r = [];
for (var i = 0; i < r; i++) r.add("a" + "b");
print(identical(r[0], r[1]));
```
This prints `false`, and it must print `true`. The expression `"a" + "b"` is a compile-time constant expression and the spec says:
> A constant expression is an expression whose value can never change, and that can be evaluated entirely at compile time.

This example shows the value of  the constant expression `"a" + "b"` changing.

Arguably, the spec saying:
> The predefined Dart function identical() is defined such that identical(c1, c2) iff:
> ...
> • c1 and c2 are constant strings and c1 == c2, OR

does require that the `identical` function cannot distinguish constant strings (the problem is that "constant string" isn't a formally defined term - being constant is a property of syntax and evaluation time, not of the resulting value).

**Comment by eernstg** [comment] 2016-11-02 09:50
I think this confirms that the vm ought to consistently detect constant expressions of type `String` and generate code to return the canonicalized result for every such expression every time, in stead of, say, returning a fresh string each time for `"a" + "b"` in that `for` loop. It does require a bottom-up propagated bit in the abstract syntax: for instance, `myRuntimeString + "a" + "b"` associates to the left, so there's no canonical string `"ab"` inside that expression, only the two canonical strings `"a"` and `"b"`. The spec needs a clarification to state unambiguously that all constant expressions of type `String` must yield a canonicalized result, but I don't think it is reasonable to interpret it differently even with the current wording.

About the invocations of `identical`: Assuming the strict approach I just described, all three of them should return true. The first one is a constant expression; the second one is a dynamic invocation of `identical` with two arguments which are both a reference to the canonical string 'ab', and so is the third.

**Comment by mhausner** [comment] 2016-11-07 22:11
See also issue #25024.

Back when Dart was still Dash, I remember discussions that the language shall not require all expressions that can be compile-time constants to be canonicalized, due to the runt-time cost. You don't want to spend the time to canonicalize every "a"+"b" (xyz+"b", "a"+X.c, ...) for the rare case where it's needed.

**Comment by lrhn** [comment] 2016-11-08 07:35
If we don't canonicalize all compile-time constant string expressions, then we need to make it predictable for users when they are canonicalized and when they are not. Is the VM following a rule or is it more ad-hoc which compile-time string expressions are canonicalized and which are not?
I'm guessing that string literals are always canonicalized, and likely also string interpolations and juxtapositions. I guess that only leaves string `+` operations.

I wouldn't mind if `string constant expression + string constant expression` was also always canonicalized. It would at least be a simple rule to explain. On the other hand, I expect the Kernel to do that for you, so it might not be worth it to change the VM just now.

**Comment by mhausner** [comment] 2017-03-20 16:38
I suspect this will be obsolete with the new front-end, but it needs to be verified.

**Comment by liamappelbe** [comment] 2022-05-03 20:57
I tried to verify that this was fixed, and write a regression test. It seems that the behavior has changed since this bug was opened, but `'a' + 'b'` is not being canonicalized:

```dart
void main() {
  String ab = 'ab';
  print(identical('a' + 'b', 'ab'));  // false
  print(identical('ab',       ab));   // true
  print(identical('a' + 'b',  ab));   // false

  var x = "a" + "b";
  print(identical("a" + "b", x));     // false

  var r = [];
  for (var i = 0; i < 10; i++) r.add("a" + "b");
  print(identical(r[0], r[1]));       // false
}
```

Note that the first print has switched from true to false. Is this the intended behavior now?

**Comment by eernstg** [comment] 2022-05-04 09:39
We don't specify that every constant expression must be evaluated at compile time, only that an expression must satisfy a very strict set of rules in order to be a constant expression, and a compiler is then _allowed_ to evaluate it at compile time. So it's OK for Dart compilers to postpone the evaluation of `'a' + 'b'` to run time.

With specific expressions we have a more strict rule: A `<constObjectExpression>` _must_ be canonicalized (which is currently only possible when it is also evaluated at compile-time). That's a constant expression whose top-level construct invokes a constant constructor, e.g., `const C('a' + 'b')`. In that case, and with the following declaration of `C`, the instance of `C` must be the same as the instance yielded by evaluating `const C('ab')`, because canonicalization only relies on the type of object (`C`) and the values of its instance variables:

```dart
class C {
  final String s;
  const C(this.s);
}

void main() => print(identical(const C('a' + 'b'), const C('ab'))); // 'true'.
```

I'll close this issue because the transitivity discrepancy has been resolved, and because the more general issue about canonicalization of strings is handled in https://github.com/dart-lang/language/issues/985.

**Closed by eernstg** 2022-05-04 09:39 UTC
Labels: area-vm, P2, type-bug, area-front-end, front-end-kernel
