### ISSUE TITLE
Inferred generic type appears to fallback to dynamic/Object, prevents constraining types

### ISSUE THREAD

**Issue by joeconwaystk** [dart-lang/sdk#28762] opened 2017-02-13 20:25 UTC
Consider the following function:

```
void f<T>(T t, T u) { }
```

I would expect that I'd receive an analyzer warning at the following call site:

```
f(1, "string");
```

But the analyzer and runtime are both happy to comply. The reason I'd expect this is I'd like `T` to constrain `t` and `u` to the same type. I imagine it does constrain them to their shared super type or to `dynamic`. In which case, there isn't much value - the function parameters could be declared as `dynamic` or `Object`.

**Comment by leafpetersen** [comment] 2017-02-14 18:50
There is an experimental flag (`--no-implicit-dynamic`) that I believe will stop this from happening, but it also prevents dynamic in a number of other places that you may or may not want.  I'd like to revisit this at some point.  @pq I wonder whether this would be a good candidate for an opt in lint?

**Comment by jmesserly** [comment] 2017-02-17 18:14
I think this is a dupe of https://github.com/dart-lang/sdk/issues/27917

**Comment by jmesserly** [comment] 2017-02-17 18:15
very similar example: https://github.com/dart-lang/sdk/issues/27917#issuecomment-273655204

**Closed by jmesserly** 2017-02-17 18:14 UTC
Labels: analyzer-strong-mode, area-analyzer

**Comment by leafpetersen** [comment] 2017-02-17 22:43
I was thinking about this a bit more.  @joeconwaystk, two questions

1. Can you elaborate on the actual code behind this?  Why do you care whether the types are constrained to be equal (since they don't appear in the return type)? Just curious about the underlying pattern: is the body of the function doing something non-parametric (that is, "is" checks, or casts)? 

2.  What would you want to happen with `f(1.0, 1)`?   What about `[1, 1.0]`?

**Comment by pq** [comment] 2017-02-17 22:50
> @pq I wonder whether this would be a good candidate for an opt in lint?

Late to the party, sorry!  Happy to chat about transitioning this to a lint if that's the direction people want to take...

**Comment by joeconwaystk** [comment] 2017-02-18 00:24
Hey Leaf. Thanks for your questions. Specific use case is for building matcher objects in Aqueduct on the VM.

```dart
whereBetween(1, 5);
whereBetween(1.0, 5.0);
whereBetween("a", "e");
```

This method is really just implemented something like:

```dart
dynamic whereBetween<T>(T lhs, T rhs) {
  return new BetweenMatcher(lhs, rhs);
}
```

In this particular case, the values will just get sent to a database - the database driver gets type information elsewhere, so `T` is unused. The constraints would help a user recognize incorrect types - especially if the values are coming from variables - at analysis time instead of runtime.

`f(1.0, 1)` is an interesting case, because `T` = `num` becomes legitimate. On that thought, I plugged this into Dartpad in Strong mode and got the appropriate checks:

```dart
T f<T, U extends T>(T t, U u) {
  
}
```

Both `f(1.0, 1)` and `f(1, "a")` fail as expected and the desired effect is achieved.

There's a bit more context in the email chain with Bob and I that you got cc'ed into. The net result from that discussion was to remove generics from methods like this because some of the type-system-abusing would eventually create issues as generics evolve. The goal was to do some fudging of the type system to enable a really user-friendly API.  To quickly recap, users build queries like:

```dart
var query = new Query<Employee>()
  ..where.salary = whereGreaterThan(20000);
```

`where` is of type `Employee`, from `Query<T>`'s parametrized type. `salary` is an unimplemented `int` accessor that gets routed through `noSuchMethod`, which stores the return of `whereGreaterThan()` in a `Map`. So, the goal was to lie to the type system for a short period of time, knowing that the return value of `whereGreaterThan` is definitely not an `int`. In fact it was declared like:

```dart
T whereGreaterThan(T value) => new ComparisonMatcher(MatcherOperator.greaterThan, value) as dynamic;
```

Which is currently valid, even in checked mode. I've since moved methods like `whereGreaterThan` back to `(dynamic) => dynamic`, but the message was this may also cause issues in the future.

**Comment by jmesserly** [comment] 2017-02-18 00:39
yeah, matchers were also the example I got from Natalie (https://github.com/dart-lang/sdk/issues/27917#issuecomment-273655204).

@leafpetersen it reminds me of similar discussions in Dart at one point about `==`, where folks were saying this often doesn't make sense unless the two operands are the same static type. (in fact given "class D extends C", it's very difficult to implement both C's and D's `operator ==` so they correctly reject the other type at runtime. Typically if an instance of C is on the left side of `==` it will incorrectly match an instance of D that should not be considered equal)

**Comment by leafpetersen** [comment] 2017-02-28 02:24
Belated thanks for the additional context.  Unifying the types via least-upper-bound vs requiring equality is an interesting question for us.  Allowing the least-upper-bound makes inference much more flexible, at the cost of not catching as many errors (particularly when combined with implicit downcasts).  I still don't know what the right answer is.
