### ISSUE TITLE
Analyzer Error

### ISSUE THREAD

**Issue by KOGI** [dart-lang/sdk#38727] opened 2019-10-04 21:03 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6817.14`
- `2.5.1`
- `IU-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1680x1050, 1680x1050`

## Exception
```
Dart analysis server, SDK version 2.5.1, server version 1.27.2, error: Failed to handle completion domain request: {id: 1749, method: completion.getSuggestions, params: {file: D:\code\cstep\nats.dart\lib\dart_nats.dart, offset: 974}, clientRequestTime: 1570222911497}
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _OpTypeAstVisitor.visitSimpleFormalParameter (package:analyzer_plugin/src/utilities/completion/optype.dart:1059:30)
#2      _OpTypeAstVisitor.visitFormalParameterList (package:analyzer_plugin/src/utilities/completion/optype.dart:713:7)
#3      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4551:49)
#4      new OpType.forCompletion (package:analyzer_plugin/src/utilities/completion/optype.dart:152:16)
#5      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:377:21)
#6      DartCompletionManager._addIncludedElementKinds (package:analysis_server/src/services/completion/dart/completion_manager.dart:198:26)
#7      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:133:7)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#17     DartCompletionRequestImpl.from (package:analysis_server/src/services/completion/dart/completion_manager.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#24     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\bob.jackman\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment] 2019-11-04 16:29
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38513; please follow along there.

**Comment by srawlins** [comment] 2019-11-04 16:29
Duplicate of https://github.com/dart-lang/sdk/issues/38513

**Closed by srawlins** 2019-11-04 16:29 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
