### ISSUE TITLE
Wrong "invalid override" reported by analyzer with a class named Zone

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#34595] opened 2018-09-26 14:01 UTC
I get an error on `B.f` from analyzer with the 3 following files:

```dart
// ------------------ a1.dart
class Zone {}
// ------------------ a2.dart
import 'dart:async';
import 'a1.dart';
export 'a1.dart';
abstract class A {
  f(Zone z);
}
// ------------------ a3.dart
import 'a2.dart';

class B implements A {
  @override
  f(Zone z) => 1;
}

main() {
  print(B().f(null));
}
```

The error is:

>Invalid override. The type of 'B.f' ('(Zone) → dynamic') isn't a subtype of 'A.f' ('(dynamic) → dynamic').

The error occurs on _SDK-2.0.0_ and _SDK-2.1.0-dev.5.0_
 
/cc @bwilkerson @scheglov

**Comment by scheglov** [comment] 2018-09-26 14:23
This is not what it looks like :-)

The problem is that `Zone` in `a2.dart` is considered by as ambiguous during linking - there is `dart:async` and `a1.dart` libraries that provide it. This is an error in Analyzer for sure - the import for `dart:async` should implicitly have `hide Zone` according to the spec. We will fix this.

**Comment by devoncarew** [comment] 2018-10-01 21:15
At a high level, this is a summary linking issues.

@stereotype441 will take this if no one else does before then.

**Comment by stereotype441** [comment] 2023-04-13 17:41
Unassigning myself because I’m not actively working on this issue right now.

**Comment by bwilkerson** [comment] 2024-06-14 18:39
After cleaning up the example to work with the latest version of the language, the only diagnostic produced is a warning that the import of `dart:async` is unused, which I believe is correct. I'm closing the issue because the problem appears to have been fixed.

**Closed by bwilkerson** 2024-06-14 18:39 UTC
Labels: area-analyzer, analyzer-ux, P2, type-bug
