### ISSUE TITLE
stock_layout_iteration and hot reload regressions

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30388] opened 2017-08-10 00:27 UTC
Since rolling Flutter's engine to include the Dart roll from 69817eea182384b40ef658d578fd49cac00c5874 to 21eddc429e9c7260de00a9af7cad94baba830f59, the microbenchmarks stock_layout_iteration benchmark has regressed by 2x and the hot reload benchmarks have regressed by about 20% (eyeballing the chart).

**Comment by zanderso** [comment] 2017-08-14 17:53
@a-siva @alexmarkov Is this due to the same cause as https://github.com/dart-lang/sdk/issues/30371#issuecomment-321087982 ?

**Comment by alexmarkov** [comment] 2017-08-14 18:14
It looks like the stock_layout_iteration regression is different from #30371, as it appears during the next engine rollout. Also, it seems like it is fixed by now as the stock_layout_iteration benchmark is back to normal.

**Comment by a-siva** [comment] 2017-10-17 22:35
closing as fixed.

**Closed by a-siva** 2017-10-17 22:35 UTC
Labels: area-vm, vm-regression
