### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by kirobass** [dart-lang/sdk#38862] opened 2019-10-14 11:26 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.965b8cb1d8e84a5e45be52eada3d547749d91107`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.965b8cb1d8e84a5e45be52eada3d547749d91107, server version 1.27.3, error: Analysis failed: /Users/ehabbassilli/AndroidStudioProjects/booga_fitness_app/lib/BoogaPages/WorkoutClass.dart
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      StaticTypeAnalyzer._inferMethodInvocationInlineJS (package:analyzer/src/generated/static_type_analyzer.dart:1814:19)
#2      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:787:9)
#3      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7245:49)
#4      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:4296:12)
#5      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7245:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#7      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#9      UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3107:45)
#10     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:3388:11)
#11     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#12     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:4295:26)
#13     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7245:49)
#14     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3772:18)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#16     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3214:59)
#17     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3768:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#19     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#21     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#22     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5256:13)
#23     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:5799:7)
#24     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:4183:7)
#25     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5771:49)
#26     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#27     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#28     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#29     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#30     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5256:13)
#31     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#32     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#33     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#34     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#35     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5267:13)
#36     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3528:13)
#37     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#38     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5088:12)
#39     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#40     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#41     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5618:15)
#42     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:4086:13)
#43     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5082:49)
#44     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7441:18)
#45     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#46     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3345:51)
#47     ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:4327:11)
#48     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7436:49)
#49     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#50     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#51     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4333:10)
#52     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dar...
```

For additional log information, please append the contents of
file:///private/var/folders/xm/d8rh4pd94pg248n9hmj687_h0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-10-15 04:36
Thanks for reporting this issue! This was previously detected by fuzz testing at https://github.com/dart-lang/sdk/issues/38048; please follow along there.

**Comment by srawlins** [comment] 2019-10-15 04:36
Duplicate of https://github.com/dart-lang/sdk/issues/38048

**Closed by srawlins** 2019-10-15 04:36 UTC
Labels: analyzer-crash-report, area-analyzer, crash
