### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by fabryx92** [dart-lang/sdk#35474] opened 2018-12-21 16:45 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/0q/jh77wwcx1cs989k89kv79mqr0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: /Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart context: exception_20181221_174137_917
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      _ClassVerifier._checkForMismatchedAccessorTypes (package:analyzer/src/error/inheritance_override.dart:357:45)
#2      _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:173:5)
#3      InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:44:11)
#4      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:332:33)
#5      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#7      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:15)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:36)
#10     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#11     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#12     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#13     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#14     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#15     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1029:23)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#19     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#20     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#21     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#22     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#28     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#29     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#30     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#31     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#32     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1545410497353 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/additional_info_bloc.dart","errors":[]}}
1545410497354 => {"id":"3820","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart","offset":1928,"length":14},"clientRequestTime":154541
1545410497355 <= {"id":"3820","result":{"assists":[]}}
1545410497367 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/checkout_bloc.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":
1545410497406 => {"id":"3821","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart","offset":1928,"length":14},"clientRequestTime":154541
1545410497439 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info_screen.dart","errors":[]}}
1545410497441 <= {"id":"3821","result":{"assists":[]}}
1545410497444 => {"id":"3822","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart","offset":1928,"length":14},"clientRequestTime":154541
1545410497460 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/additional_info_screen.dart","errors":[]}}
1545410497461 <= {"id":"3822","result":{"assists":[]}}
1545410497472 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/new_request_bloc.dart","errors":[{"severity":"INFO","type":"HINT","location":{"fil
1545410497492 => {"id":"3823","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart","offset":1928,"length":14},"clientRequestTime":154541
1545410497496 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/checkout_screen.dart","errors":[]}}
1545410497497 <= {"id":"3823","result":{"assists":[]}}
1545410497537 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info_bloc.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","locati
1545410497573 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/test/widget_test.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/fabry
1545410497586 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/home.dart","errors":[]}}
1545410497593 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/main.dart","errors":[]}}
1545410497600 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/new_request_screen.dart","errors":[]}}
1545410497614 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/categories_screen.dart","errors":[]}}
1545410497640 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/services_screen.dart","errors":[]}}
1545410497647 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/new_request_routes.dart","errors":[]}}
1545410497658 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/app.dart","errors":[]}}
1545410497659 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1545410497659 <= {"event":"analysis.implemented","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart","classes":[],"members":[]}}
1545410497784 => {"id":"3824","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart":{"type":"add","content":"import 'package:mob
1545410497785 <= {"id":"3824","result":{}}
1545410497785 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1545410497813 => {"id":"3825","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart","offset":1928,"length":14},"clientRequestTime":154541
1545410497938 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart context: exception_20181221_174137
```

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: /Users/fabryx/Work/TiAssisto/mobile_app/lib/common/models/request.dart context: exception_20181221_174137_917
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      _ClassVerifier._checkForMismatchedAccessorTypes (package:analyzer/src/error/inheritance_override.dart:357:45)
#2      _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:173:5)
#3      InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:44:11)
#4      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:332:33)
#5      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#6      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-12-21 17:12
Duplicate of #35223

**Closed by stereotype441** 2018-12-21 17:12 UTC
Labels: analyzer-server, area-analyzer
