### ISSUE TITLE
Visual Studio is super slow on dart 

### ISSUE THREAD

**Issue by tazik561** [dart-lang/sdk#46269] opened 2021-06-05 16:55 UTC
I am using vscode to developing flutter application But I don't know why when I want to use wrap a widget almost 10 second I have to waiting:
this part:

https://media.discordapp.net/attachments/421445316617961502/850775657697116180/Screenshot_2021-06-05_21-08-07.png

More that 50% of my ram is free and more than 70% of cpu is not used and I am using ssd.

```
alt@mx:~
$ dart --version
Dart SDK version: 2.13.1 (stable) (Unknown timestamp) on "linux_x64"
alt@mx:~
```

I am using FVM to manage flutter SDK:

```
⣽alt@mx:~
$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /home/alt/fvm/versions/2.0.6
    • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /mnt/SSDP/Sdk/android/
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /mnt/SSDP/Sdk/android
    • ANDROID_SDK_ROOT = /mnt/SSDP/Sdk/android/
    • Java binary at: /mnt/SSDP/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /mnt/SSDP/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /mnt/SSDP/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • SM A315G (mobile) • RR8R107K94E • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

**Comment by bwilkerson** [comment] 2021-06-05 17:11
@DanTup

**Comment by DanTup** [comment] 2021-06-05 18:07
@tazik561 can you reliably reproduce this and does it happen always, or only the first time you use it since opening VS code?

There are some performance improvements in Flutter 2.2, so I'd recommed upgrading to see if that solves the problem too.

If it still occurs on Flutter v2.2, a log file might help:

- Run the **Dart: Capture Analysis Logs** command from the VS Code command palette
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log file

Note: The log may contain parts from your source code, so it's best to reproduce using a sample/public project.

Thanks!

**Comment by tazik561** [comment] 2021-06-06 08:19
Unfortunately my project not support Flutter 2.2 yet , I am using 2.0.6  . I run  Dart: Capture Analysis server Logs  ,and its results:
 ```

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.23.0
Flutter extension: 3.23.0 (activated)

App: Visual Studio Code
Version: 1.56.2
Platform: linux

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /home/alt/fvm/versions/2.0.6/bin/cache/dart-sdk
    Ver: 2.12.3
Flutter SDK:
    Loc: /home/alt/fvm/versions/2.0.6
    Ver: 2.0.6

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses

Sun Jun 06 2021 [12:43:10 GMT+0430 (Iran Daylight Time)] Log file started
[12:43:11 PM] [Analyzer] [Info] ==> Content-Length: 226
[12:43:11 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":63,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"position":{"line":754,"character":15}}}
[12:43:11 PM] [Analyzer] [Info] <== Content-Length: 1121
Content-Type: application/vscode-jsonrpc; charset=utf-8
[12:43:11 PM] [Analyzer] [Info] <== {"id":63,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"```dart\n(new) Column Column({Key key, MainAxisAlignment mainAxisAlignment = MainAxisAlignment.start, MainAxisSize mainAxisSize = MainAxisSize.max, CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.center, TextDirection textDirection, VerticalDirection verticalDirection = VerticalDirection.down, TextBaseline textBaseline, List<Widget> children = const <Widget>[]})\n```\n*package:flutter/src/widgets/basic.dart*\n\n---\nCreates a vertical array of children.\n\nThe [mainAxisAlignment], [mainAxisSize], [crossAxisAlignment], and\n[verticalDirection] arguments must not be null.\nIf [crossAxisAlignment] is [CrossAxisAlignment.baseline], then\n[textBaseline] must not be null.\n\nThe [textDirection] argument defaults to the ambient [Directionality], if\nany. If there is no ambient directionality, and a text direction is going\nto be necessary to disambiguate `start` or `end` values for the\n[crossAxisAlignment], the [textDirection] must not be null."},"range":{"start":{"line":754,"character":15},"end":{"line":754,"character":21}}}}
[12:43:12 PM] [Analyzer] [Info] ==> Content-Length: 226
[12:43:12 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":64,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"position":{"line":760,"character":14}}}
[12:43:12 PM] [Analyzer] [Info] <== Content-Length: 255
Content-Type: application/vscode-jsonrpc; charset=utf-8
[12:43:12 PM] [Analyzer] [Info] <== {"id":64,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"```dart\n{EdgeInsetsGeometry padding}\n```\n---\nThe amount of space by which to inset the child."},"range":{"start":{"line":760,"character":14},"end":{"line":760,"character":21}}}}
[12:43:12 PM] [Analyzer] [Info] ==> Content-Length: 226
[12:43:12 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":65,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"position":{"line":759,"character":14}}}
[12:43:12 PM] [Analyzer] [Info] <== Content-Length: 380
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":65,"jsonrpc":"2.0","result":{"contents":{"kind":"markdown","value":"```dart\n(new) Padding Padding({Key key, EdgeInsetsGeometry padding, Widget child})\n```\n*package:flutter/src/widgets/basic.dart*\n\n---\nCreates a widget that insets its child.\n\nThe [padding] argument must not be null."},"range":{"start":{"line":759,"character":12},"end":{"line":759,"character":19}}}}
[12:43:12 PM] [Analyzer] [Info] ==> Content-Length: 238
[12:43:12 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":66,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"position":{"line":759,"character":15}}}
[12:43:12 PM] [Analyzer] [Info] <== Content-Length: 284
Content-Type: application/vscode-jsonrpc; charset=utf-8
[12:43:12 PM] [Analyzer] [Info] <== {"id":66,"jsonrpc":"2.0","result":[{"range":{"start":{"line":759,"character":12},"end":{"line":759,"character":19}}},{"range":{"start":{"line":799,"character":12},"end":{"line":799,"character":19}}},{"range":{"start":{"line":1053,"character":14},"end":{"line":1053,"character":21}}}]}
[12:43:12 PM] [Analyzer] [Info] ==> Content-Length: 231
[12:43:12 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":67,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"position":{"line":759,"character":15}}}
[12:43:12 PM] [Analyzer] [Info] ==> Content-Length: 301
[12:43:12 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":68,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"range":{"start":{"line":759,"character":15},"end":{"line":759,"character":15}},"context":{"diagnostics":[]}}}
[12:43:12 PM] [Analyzer] [Info] <== Content-Length: 409
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":67,"jsonrpc":"2.0","result":[{"originSelectionRange":{"start":{"line":759,"character":12},"end":{"line":759,"character":19}},"targetUri":"file:///home/alt/fvm/versions/2.0.6/packages/flutter/lib/src/widgets/basic.dart","targetRange":{"start":{"line":1722,"character":0},"end":{"line":1756,"character":1}},"targetSelectionRange":{"start":{"line":1722,"character":6},"end":{"line":1722,"character":13}}}]}Content-Length: 9009
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":68,"jsonrpc":"2.0","result":[{"title":"Sort Members","kind":"source.sortMembers","command":{"title":"Sort Members","command":"edit.sortMembers","arguments":["/mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"]}},{"title":"Organize Imports","kind":"source.organizeImports","command":{"title":"Organize Imports","command":"edit.organizeImports","arguments":["/mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"]}},{"title":"Wrap with widget...","kind":"refactor.flutter.wrap.generic","diagnostics":[],"edit":{"documentChanges":[{"textDocument":{"version":1,"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"edits":[{"range":{"start":{"line":759,"character":12},"end":{"line":767,"character":13}},"newText":"widget(\n              child: Padding(\n                padding: EdgeInsets.symmetric(\n                  horizontal: getResponsiveDefaultWidth(thirtySize),\n                ),\n                child: Text(\n                  S.of(context).new_user_guide_login_body,\n                  style: getPageManualTextStyle().copyWith(fontSize: 14),\n                ),\n              ),\n            )"}]}]}},{"title":"Wrap with Center","kind":"refactor.flutter.wrap.center","diagnostics":[],"edit":{"documentChanges":[{"textDocument":{"version":1,"uri":"file:///mnt/SSDP/Project/Cas/p…
[12:43:12 PM] [Analyzer] [Info] ==> Content-Length: 294465
[12:43:12 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///home/alt/fvm/versions/2.0.6/packages/flutter/lib/src/widgets/basic.dart","languageId":"dart","version":1,"text":"// Copyright 2014 The Flutter Authors. All rights reserved.\n// Use of this source code is governed by a BSD-style license that can be\n// found in the LICENSE file.\n\nimport 'dart:ui' as ui show Image, ImageFilter, TextHeightBehavior;\n\nimport 'package:flutter/foundation.dart';\nimport 'package:flutter/gestures.dart';\nimport 'package:flutter/rendering.dart';\nimport 'package:flutter/services.dart';\n\nimport 'binding.dart';\nimport 'debug.dart';\nimport 'framework.dart';\nimport 'localizations.dart';\nimport 'widget_span.dart';\n\nexport 'package:flutter/animation.dart';\nexport 'package:flutter/foundation.dart' show\n  ChangeNotifier,\n  FlutterErrorDetails,\n  Listenable,\n  TargetPlatform,\n  ValueNotifier;\nexport 'package:flutter/painting.dart';\nexport 'package:flutter/rendering.dart' show\n  AlignmentTween,\n  AlignmentGeometryTween,\n  Axis,\n  BoxConstraints,\n  CrossAxisAlignment,\n  CustomClipper,\n  CustomPainter,\n  CustomPainterSemantics,\n  DecorationPosition,\n  FlexFit,\n  FlowDelegate,\n  FlowPaintingContext,\n  FractionalOffsetTween,\n  HitTestBehavior,\n  LayerLink,\n  MainAxisAlignment,\n  MainAxisSize,\n  MultiChildLayoutDelegate,\n  Overflow,\n  PaintingContext,\n  PointerCancelEvent,\n  PointerCancelEventListener,\n  PointerDownEvent,\n  PointerDownEventListener,\n  PointerEvent,\n  PointerMoveEvent,\n  PointerMoveEventListener,\n  PointerUpEvent,\n  PointerUpEventListener,\n  RelativeRect,\n  SemanticsBuilderCallback,\n  ShaderCallback,\n  ShapeBorderClipper,\n  SingleChildLayoutDelegate,\n  StackFit,\n  TextOverflow,\n  ValueChanged,\n  ValueGetter,\n  WrapAlignment,\n  WrapCrossAlignment;\n\n// Examples can assume:\n// class TestWidget extends StatelessWidget { @override Widget build(BuildContext context) => const Placeholder(); }\n…
[12:43:12 PM] [Analyzer] [Info] ==> Content-Length: 166
[12:43:12 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didClose","params":{"textDocument":{"uri":"file:///home/alt/fvm/versions/2.0.6/packages/flutter/lib/src/widgets/basic.dart"}}}
[12:43:13 PM] [Analyzer] [Info] ==> Content-Length: 301
[12:43:13 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":69,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"range":{"start":{"line":759,"character":15},"end":{"line":759,"character":15}},"context":{"diagnostics":[]}}}
[12:43:22 PM] [Analyzer] [Info] <== Content-Length: 98
Content-Type: application/vscode-jsonrpc; charset=utf-8
[12:43:22 PM] [Analyzer] [Info] <== {"id":12,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[12:43:22 PM] [Analyzer] [Info] ==> Content-Length: 39
[12:43:22 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":12,"result":null}
[12:43:22 PM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}
[12:43:23 PM] [Analyzer] [Info] <== Content-Length: 2899
Content-Type: application/vscode-jsonrpc; charset=utf-8
[12:43:23 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart","diagnostics":[{"range":{"start":{"line":1231,"character":7},"end":{"line":1231,"character":31}},"severity":3,"code":"unused_element","source":"dart","message":"The declaration '_doLoginlessLoginProcess' isn't referenced.\nTry removing the declaration of '_doLoginlessLoginProcess'."},{"range":{"start":{"line":1101,"character":15},"end":{"line":1101,"character":27}},"severity":3,"code":"missing_return","source":"dart","message":"This function has a return type of 'FutureOr<bool>', but doesn't end with a return statement.\nTry adding a return statement, or changing the return type to 'void'."},{"range":{"start":{"line":6,"character":7},"end":{"line":6,"character":76}},"severity":3,"code":"unused_import","source":"dart","message":"Unused import: 'package:iparsian_flutter/ui/dialogs/contact_cart_delete_dialog.dart'.\nTry removing the import directive."},{"range":{"start":{"line":1233,"character":9},"end":{"line":1233,"character":22}},"severity":3,"code":"unused_local_variable","source":"dart","message":"The value of the local variable 'successResult' isn't used.\nTry removing the variable, or using it."},{"range":{"start":{"line":1038,"character":11},"end":{"line":1038,"character":21}},"severity":3,"code":"deprecated_member_use","source":"dart","message":"'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre..\nTry replacing the use of the deprecated member with the replacement.","tags":[2]},{"range":{"start":{"line":1109,"character":28},"end":{"line":1109,"character":32}},"severity":3,"code":"deprecated_member_use","source":"dart","message":"'List' is deprecated and shouldn't be used. Use a list literal, [], or the List.filled constructor instead.\nTry replacing the …
[12:43:23 PM] [Analyzer] [Info] <== Content-Length: 73184
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"dart/textDocument/publishOutline","params":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart","outline":{"element":{"range":{"start":{"line":0,"character":0},"end":{"line":1324,"character":0}},"name":"<unit>","kind":"COMPILATION_UNIT"},"range":{"start":{"line":0,"character":0},"end":{"line":1324,"character":0}},"codeRange":{"start":{"line":0,"character":0},"end":{"line":1324,"character":0}},"children":[{"element":{"range":{"start":{"line":64,"character":10},"end":{"line":64,"character":32}},"name":"PARSIAN_USER_TAB_INDEX","kind":"TOP_LEVEL_VARIABLE","returnType":"int"},"range":{"start":{"line":64,"character":0},"end":{"line":64,"character":37}},"codeRange":{"start":{"line":64,"character":10},"end":{"line":64,"character":36}}},{"element":{"range":{"start":{"line":65,"character":10},"end":{"line":65,"character":23}},"name":"KYC_TAB_INDEX","kind":"TOP_LEVEL_VARIABLE","returnType":"int"},"range":{"start":{"line":65,"character":0},"end":{"line":65,"character":28}},"codeRange":{"start":{"line":65,"character":10},"end":{"line":65,"character":27}}},{"element":{"range":{"start":{"line":66,"character":10},"end":{"line":66,"character":29}},"name":"LOGINLESS_TAB_INDEX","kind":"TOP_LEVEL_VARIABLE","returnType":"int"},"range":{"start":{"line":66,"character":0},"end":{"line":66,"character":34}},"codeRange":{"start":{"line":66,"character":10},"end":{"line":66,"character":33}}},{"element":{"range":{"start":{"line":68,"character":6},"end":{"line":68,"character":22}},"name":"LoginPageWithKYC","kind":"CLASS"},"range":{"start":{"line":68,"character":0},"end":{"line":77,"character":1}},"codeRange":{"start":{"line":68,"character":0},"end":{"line":77,"character":1}},"children":[{"element":{"range":{"start":{"line":69,"character":13},"end":{"line":69,"character":21}},"name":"checkKyc","kind":"FIELD","returnType":"bool"},"range":{"start":{"lin…
[12:43:23 PM] [Analyzer] [Info] <== meters":"(UserProvider viewModel)","returnType":"void"},"range":{"start":{"line":1171,"character":2},"end":{"line":1194,"character":3}},"codeRange":{"start":{"line":1171,"character":2},"end":{"line":1194,"character":3}},"children":[{"element":{"range":{"start":{"line":1185,"character":18},"end":{"line":1185,"character":18}},"name":"Loading","kind":"CONSTRUCTOR_INVOCATION"},"range":{"start":{"line":1185,"character":18},"end":{"line":1185,"character":27}},"codeRange":{"start":{"line":1185,"character":18},"end":{"line":1185,"character":27}}}]},{"element":{"range":{"start":{"line":1196,"character":7},"end":{"line":1196,"character":20}},"name":"_doKycProcess","kind":"METHOD","parameters":"(UserProvider viewModel)","returnType":"void"},"range":{"start":{"line":1196,"character":2},"end":{"line":1229,"character":3}},"codeRange":{"start":{"line":1196,"character":2},"end":{"line":1229,"character":3}},"children":[{"element":{"range":{"start":{"line":1213,"character":26},"end":{"line":1213,"character":26}},"name":"WelcomePage","kind":"CONSTRUCTOR_INVOCATION"},"range":{"start":{"line":1213,"character":26},"end":{"line":1213,"character":59}},"codeRange":{"start":{"line":1213,"character":26},"end":{"line":1213,"character":59}}},{"element":{"range":{"start":{"line":1217,"character":20},"end":{"line":1217,"character":20}},"name":"Loading","kind":"CONSTRUCTOR_INVOCATION"},"range":{"start":{"line":1217,"character":20},"end":{"line":1217,"character":29}},"codeRange":{"start":{"line":1217,"character":20},"end":{"line":1217,"character":29}}}]},{"element":{"range":{"start":{"line":1231,"character":7},"end":{"line":1231,"character":31}},"name":"_doLoginlessLoginProcess","kind":"METHOD","parameters":"(UserProvider viewModel)","returnType":"void"},"range":{"start":{"line":1231,"character":2},"end":{"line":1269,"character":3}},"codeRange":{"start":{"line":1231,"character":2},"end":{"line":1269,"character":3}},"children":[{"element":{"range":{"start":{"line":1240,"character":20},"end":{"li…
[12:43:23 PM] [Analyzer] [Info] <== ame":"Text","attributes":[{"name":"data","label":"S.of(context).login_page_contact_us","valueRange":{"start":{"line":687,"character":26},"end":{"line":687,"character":61}}},{"name":"style","label":"…","valueRange":{"start":{"line":688,"character":33},"end":{"line":689,"character":60}}}],"range":{"start":{"line":686,"character":31},"end":{"line":690,"character":25}},"codeRange":{"start":{"line":686,"character":31},"end":{"line":690,"character":25}},"children":[]}]}]}]}]},{"kind":"NEW_INSTANCE","className":"GestureDetector","attributes":[],"range":{"start":{"line":696,"character":16},"end":{"line":718,"character":17}},"codeRange":{"start":{"line":696,"character":16},"end":{"line":718,"character":17}},"children":[{"kind":"NEW_INSTANCE","className":"NationalIdPage","attributes":[],"range":{"start":{"line":700,"character":44},"end":{"line":700,"character":60}},"codeRange":{"start":{"line":700,"character":44},"end":{"line":700,"character":60}},"children":[]},{"kind":"NEW_INSTANCE","className":"Container","attributes":[{"name":"margin","label":"new EdgeInsets.only(left: 30)","valueRange":{"start":{"line":704,"character":28},"end":{"line":704,"character":57}}}],"range":{"start":{"line":703,"character":25},"end":{"line":717,"character":19}},"codeRange":{"start":{"line":703,"character":25},"end":{"line":717,"character":19}},"children":[{"kind":"NEW_INSTANCE","className":"Align","attributes":[{"name":"alignment","label":"Alignment.centerLeft","valueRange":{"start":{"line":706,"character":33},"end":{"line":706,"character":53}}}],"range":{"start":{"line":705,"character":27},"end":{"line":716,"character":21}},"codeRange":{"start":{"line":705,"character":27},"end":{"line":716,"character":21}},"children":[{"kind":"NEW_INSTANCE","className":"Container","attributes":[{"name":"margin","label":"new EdgeInsets.only(top: 20)","valueRange":{"start":{"line":708,"character":32},"end":{"line":708,"character":60}}},{"name":"height","label":"50","valueRange":{"start":{"line":714,"character…
[12:43:23 PM] [Analyzer] [Info] <== Content-Length: 201
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"textDocument/publishDiagnostics","params":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/new_user/new_user_guide_page.dart","diagnostics":[]},"jsonrpc":"2.0"}Content-Length: 1415
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"dart/textDocument/publishClosingLabels","params":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/new_user/new_user_guide_page.dart","labels":[{"range":{"start":{"line":48,"character":11},"end":{"line":89,"character":5}},"label":"CasBaseScaffold"},{"range":{"start":{"line":50,"character":14},"end":{"line":52,"character":7}},"label":"CasHeader"},{"range":{"start":{"line":53,"character":12},"end":{"line":88,"character":7}},"label":"Center"},{"range":{"start":{"line":54,"character":15},"end":{"line":87,"character":9}},"label":"Column"},{"range":{"start":{"line":59,"character":12},"end":{"line":61,"character":13}},"label":"CasText"},{"range":{"start":{"line":62,"character":12},"end":{"line":85,"character":13}},"label":"Padding"},{"range":{"start":{"line":63,"character":23},"end":{"line":65,"character":15}},"label":"EdgeInsets.symmetric"},{"range":{"start":{"line":66,"character":21},"end":{"line":84,"character":15}},"label":"Stack"},{"range":{"start":{"line":68,"character":18},"end":{"line":73,"character":19}},"label":"Padding"},{"range":{"start":{"line":70,"character":27},"end":{"line":72,"character":74}},"label":"Align"},{"range":{"start":{"line":74,"character":18},"end":{"line":82,"character":19}},"label":"Positioned"},{"range":{"start":{"line":77,"character":27},"end":{"line":81,"character":21}},"label":"SvgPicture.asset"}]},"jsonrpc":"2.0"}Content-Length: 5234
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"dart/textDocument/publishOutline","params":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/new_u…
[12:43:23 PM] [Analyzer] [Info] ==> Content-Length: 301
[12:43:23 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":70,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"range":{"start":{"line":759,"character":15},"end":{"line":759,"character":15}},"context":{"diagnostics":[]}}}
[12:43:23 PM] [Analyzer] [Info] <== Content-Length: 9009
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":70,"jsonrpc":"2.0","result":[{"title":"Sort Members","kind":"source.sortMembers","command":{"title":"Sort Members","command":"edit.sortMembers","arguments":["/mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"]}},{"title":"Organize Imports","kind":"source.organizeImports","command":{"title":"Organize Imports","command":"edit.organizeImports","arguments":["/mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"]}},{"title":"Wrap with widget...","kind":"refactor.flutter.wrap.generic","diagnostics":[],"edit":{"documentChanges":[{"textDocument":{"version":1,"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"edits":[{"range":{"start":{"line":759,"character":12},"end":{"line":767,"character":13}},"newText":"widget(\n              child: Padding(\n                padding: EdgeInsets.symmetric(\n                  horizontal: getResponsiveDefaultWidth(thirtySize),\n                ),\n                child: Text(\n                  S.of(context).new_user_guide_login_body,\n                  style: getPageManualTextStyle().copyWith(fontSize: 14),\n                ),\n              ),\n            )"}]}]}},{"title":"Wrap with Center","kind":"refactor.flutter.wrap.center","diagnostics":[],"edit":{"documentChanges":[{"textDocument":{"version":1,"uri":"file:///mnt/SSDP/Project/Cas/mobileapplication/lib/ui/login/login_page_with_kyc.dart"},"edits":[{"range":{"start":{"line":759,"character":12},"end":{"line":767,"character":13}},"newText":"Center(\n              child: Padding(\n                padding: EdgeInsets.symmetric(\n                  horizontal: getResponsiveDefaultWidth(thirtySize),\n                ),\n                child: Text(\n                  S.of(context).new_user_guide_login_body,\n                  style: getPageManualTextStyle().copyWi…
Sun Jun 06 2021 [12:43:24 GMT+0430 (Iran Daylight Time)] Log file ended

```

**Comment by DanTup** [comment] 2021-06-07 15:22
Thanks for the log! It appears you're hitting #45632. The log shows that VS Code sent an open/close request (possibly as a result of pressing Ctrl while your mouse was hovered over a symbol), which (due to a bug in the LSP server) triggered some unnecessary expensive work that stopped the server responding to other requests until it completed.

The issue is fixed and the fix [was picked](https://github.com/dart-lang/sdk/commit/94162a28126443d4c3f1a7c9267ec1d69d38b330) into the Flutter 2.2 release, but you'll need to upgrade to get it. I understand that might not be ideal, though the same would be true for any additional fixes made (I don't believe there are any plans to hot-fix back to Flutter 2.0 now that 2.2 is out).

I'll close this as I don't think there's anything to do, but if you do still encounter issues after upgrading to Flutter 2.2, please capture a new log and post back (or file a new issue). Thanks!

**Closed by DanTup** 2021-06-07 15:22 UTC

**Comment by tazik561** [comment] 2021-06-07 18:42
> u do still encounter issues after upgrading to Flutter 2.2, please capture a new log and post back (or file a new issue). Thanks!

Thanks for answer but there is a problem , My production is not support null safety so It is not possible to upgrade my project to 2.2 , because I use `2.7.0` and flutter 2.2 I think use 2.10.0 !!!
What can I do?

**Comment by DanTup** [comment] 2021-06-07 18:54
I'm not certain, though I think it should still be possible to use Flutter 2.2 without having migrated (possibly by having an SDK constraint lower than v2.12 or by adding `// @dart=2.9` to the top of your unmigrated files). You may ned to add `--no-sound-null-safety` to your `launch.json`'s `args` field when running though. There's some info on running partially-migrated code at https://dart.dev/null-safety/unsound-null-safety.

**Comment by tazik561** [comment] 2021-06-07 18:59
I got this error when I am trying to use 2.2 
`SLVR:   fact: no versions of mockito match >4.1.4 <5.0.0
SLVR:   conflict: no versions of mockito match >4.1.4 <5.0.0
SLVR:   ! mockito >4.1.4 <5.0.0 is partially satisfied by not mockito 4.1.4
SLVR:   ! which is caused by "mockito 4.1.4 depends on test_api ^0.2.19-nullsafety"
SLVR:   ! thus: mockito ^4.1.4 requires test_api ^0.2.19-nullsafety
SLVR:   ! not test_api ^0.2.19-nullsafety is satisfied by test_api 0.3.0
SLVR:   ! which is caused by "every version of flutter_test from sdk depends on test_api 0.3.0"
SLVR:   ! thus: mockito ^4.1.4 is incompatible with flutter_test from sdk
SLVR:   ! flutter_test any from sdk is satisfied by flutter_test any from sdk
SLVR:   ! which is caused by "iparsian_flutter depends on flutter_test any from sdk"
SLVR:   ! thus: mockito ^4.1.4 is forbidden
SLVR:   ! mockito ^4.1.4 is satisfied by mockito ^4.1.4
SLVR:   ! which is caused by "iparsian_flutter depends on mockito ^4.1.4"
SLVR:   ! thus: version solving failed
SLVR: Version solving took 0:00:01.374131 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (1.4s).
ERR : Because no versions of mockito match >4.1.4 <5.0.0 and mockito 4.1.4 depends on test_api ^0.2.19-nullsafety, mockito ^4.1.4 requires test_api ^0.2.19-nullsafety.
    | And because every version of flutter_test from sdk depends on test_api 0.3.0, mockito ^4.1.4 is incompatible with flutter_test from sdk.
    | So, because iparsian_flutter depends on both flutter_test any from sdk and mockito ^4.1.4, version solving failed.
FINE: Exception type: SolveFailure`
and this is my dev_depandancies:

```
dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: 1.10.4
  hive_generator: ^0.8.1
  http_mock_adapter: ^0.1.6
  json_serializable: ^3.5.0
  mockito: ^4.1.4
  retrofit_generator: ^1.4.0+1
```

**Comment by tazik561** [comment] 2021-06-07 19:19
It is not possible to use flutter 2.2 !!!! why you didn't make a hot fix!!!!! What are you doing !!!!!

**Comment by DanTup** [comment] 2021-06-08 15:19
@tazik561 it's not something I'm personally involved in, but it's not really realistic to hotfix all bugs back into previous stable versions. There is both a cost and risk associated with back-porting them. If you need the latest bug fixes, you'll need to use the latest versions.

As for your dependency issue, it seems like you have a hard constraint of `^4.1.4` for `mockito` but Flutter v2.2 requires a new version of Mockito. Perhaps you can try updating your constraint to allow a higher version of Mockito?
