### ISSUE TITLE
asserts in initializer list shouldn't have access to object members

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#29784] opened 2017-06-02 07:30 UTC
With _Dart VM version: 1.24.0-dev.3.0_ the following code runs and the analyzer triggers no issue.

```dart
class A {
//  A.ok() : b = a;           // issue : Only static members can be accessed in initializers.
  A.ko() : assert(a != null); // no issue
  var a, b;
}

main() => print(new A.ko());
```

IMO the `ko` constructor should have the same issue and should not run (`$ dart --assert_initializer --checked test.dart`).

**Comment by crelier** [comment] 2017-10-06 18:43
Fixed in the VM by https://dart-review.googlesource.com/c/sdk/+/11247

**Closed by crelier** 2017-10-06 18:43 UTC
Labels: area-vm, P2 medium, Type: bug

**Comment by whesse** [comment] 2017-10-09 15:09
The regression test regress_27984_test is failing on dart2js with --dart2js-with-kernel --minified:
It crashes on multitests /01 and /02.

Logs are at https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-linux-d8-minified-4-5-be%2F8221%2F%2B%2Frecipes%2Fsteps%2Fdart2js-with-kernel-d8_tests%2F0%2Fstdout

FAILED: dart2js-d8 release_x64 language_2/regress_29784_test/01
Expected: Pass 
Actual: Crash
Compile-time error expected.
CommandOutput[dart2js]:

stdout:
out/ReleaseX64/generated_tests/language_2/regress_29784_test_01.dart:13:3:
Internal Error: Cannot find value Instance of 'ThisLocal' in () for j:constructor(A.ok).
  A.ok() : b = a; //# 01: compile-time error
  ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0-edge.90587a6837c5ad4a64d571397a8ba65a7cc3f44f), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Assertion failure: Cannot find value Instance of 'ThisLocal' in () for j:constructor(A.ok).
#0      failedAt (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/diagnostics/invariant.dart:55)
#1      LocalsHandler.readLocal (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:327)
#2      LocalsHandler.readThis (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/locals_handler.dart:380)
#3      KernelSsaGraphBuilder.visitThisExpression (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3538)
#4      ThisExpression.accept (package:kernel/ast.dart:2936)
#5      KernelSsaGraphBuilder.visitPropertyGet (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:2319)
#6      PropertyGet.accept (package:kernel/ast.dart:1911)
#7      KernelSsaGraphBuilder._buildInitializers (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:518)
#8      KernelSsaGraphBuilder.buildConstructor (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:332)
#9      KernelSsaGraphBuilder.build.<anonymous closure> (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:175)
#10     CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1119)
#11     KernelSsaGraphBuilder.build (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:135)
#12     KernelSsaBuilder.build (file:///b/build/slave/dart-sdk-linux-be/build/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:113)
