### ISSUE TITLE
Non-intrusive Union types

### ISSUE THREAD

**Issue by tejainece** [dart-lang/sdk#34380] opened 2018-09-05 09:15 UTC
Union types are a great complement to Dart's Strongly typed nature. It avoids people from declaring their variables, members and parameters as `dynamic` just to allow variables that can be a few different types based on the context.

```
class MyUser {
  void addAddress(dynamic /* Address | Iterable<Address> */ address) { ... }
}
```

This could be elegantly done with union types:

```
class MyUser {
  void addAddress(Address | Iterable<Address> address) { ... }
}
```

The proposal is that, this does not need changing type system of Dart. This can be syntactic sugar handled by the analyzer. To the analyzer and the compiler, `address` parameter is just `dynamic`. In addition, analyzer knows `address` can be either `Address` or `Iterable<Address>`. So it can complain on assignment of any type other than what is specified. Basically, `address`, is of type `dynamic` that can only be either `Address` or `Iterable<Address>`. One has to type assert it (`if(address is Address)`, etc) or type cast it to use it (`address as Iterable<Address>`).

```
class MyUser {
  void addAddress(final Address | Iterable<Address> address) {
    if(address is Address) {
      // address is of type Address here
    } else {
      doSomething(address as Iterable<Address>);
    }
  }
}
```

Additionally, when it is not type asserted yet, one could still call common methods with same signature. This is nothing different than calling a method on `dynamic` object. Analyzer just checks that the method with same signature exists in all possible types of the union.

```
void printName(final Person | Employee user) {
  print(user.name);
}
```

`typedef` or `typealias` for union types would be useful to write concise code.

```
typedef Union User = Person | Employee;
```

or

```
typealias User = Person | Employee;
```

I feel this is very non-intrusive way to add Union types to Dart without changing the existing type system.

**Comment by lrhn** [comment] 2018-09-05 09:39
It's not clear how deep this would need to go in the analyzer type system.
I'm guessing that the analyzer would have a full type system with union types, but that the remaining tools will just use `dynamic` everywhere a union-type occurs.
That would allow the analyzer to use unions in all places, including in function types, and would let it flow through type inference as well.

Without that, it's a very limited feature that only really applies to methods.

There will be some cases where the analyzer has to reject a program even if it can see that it's well-typed, because the program with `dynamic` won't work.

```dart
var id = (int | num x) => x;  // inferred type of `id`:  (int | num) Function(int | num) 
```

If you try to then treat `id` *itself* as anything more specific than `dynamic Function(dynamic)`, then the program must be rejected:
```dart
Object Function(Object) foo = id;  // Allowed.
num Function(int) bar = id;  // Error, returns dynamic, not a subtype of num.
```

Likewise, a `List<int | double>` is not a `List<num>`, because it *is* a `List<dynamic>`. 

I agree that this might be able to give users some hints. It also might seem like it's more permissive than it actually is. The assignment to `foo` above is problematic, because it will *not* be allowed if we ever introduce real union types. Allowing the syntax and then breaking it later might be doing users a disservice. In that perspective, it's actually better to use union-types in comments or annotations, than to introduce syntax and then change its meaning later.

If aliases are purely structural (and they likely has to be), then we can't define:
```dart
typedef Json = int | bool | String | List<Json> | Map<Symbol, Json>;
```
so that's at least one use-case we just cannot handle with this restricted approach. Then again, maybe we never will handle infinite structural recursion, even if we get real union types.

**Comment by tejainece** [comment] 2018-09-05 10:30
```dart
num Function(int) bar = id as (num Function(int));  // Allowed using type assertion or type casting before assignment
```

> Likewise, a List<int | double> is not a List<num>, because it is a List<dynamic>.

This could probably be easily casted `list.cast<num>()`.

> The assignment to foo above is problematic

That need not be allowed without type assertion or casting.

> it's actually better to use union-types in comments or annotations

I really dislike dealing with `dynamic`. People can pass anything into a dynamic argument. There are no type checks.

> typedef Json = int | bool | String | List<Json> | Map<Symbol, Json>;

Recursion should be possible, i think?

**Comment by lrhn** [comment] 2018-09-05 12:13
The explicit cast would still fail since `id` returns `dynamic`, so it's not a type-safe value for a function type that only returns `num`.

I understand the dislike for `dynamic`, but this idea doesn't remove `dynamic`, it just adds some *more* type checks to the analyzer which allows you to reject some programs, but the actual type in the program will still be `dynamic` until the language itself starts understanding union types.

As for recursion being possible, I do hope we can make it so, but then `Json` above would no longer be just an alias, because you would need to expand infinitely to know the actual type.
(We could introduce lazy expansion, but we'd still run into problems. If we define `typedef RecList<T> = T | List<T>;`, would `RecList<String>` be assignable to `Json`? And how would you prove that without risking infinite recursion at compile-time).

**Comment by tejainece** [comment] 2018-09-05 13:08
> The explicit cast would still fail since id returns dynamic, so it's not a type-safe value for a function type that only returns num.

`id` returns `dynamic` that could only be either `int` or `num` (Analyzer guarantees this). 

```
var id = (int | num x) => "five";  // This is analyze time and compile time error
```

Since, `int` is also a `num`. This expression is very strong.

```dart
num Function(int) bar = id;
```

However, this is not possible, since `num` is not `int`:

```dart
int Function(int) bar = id;   // This is analyze time and compile time error
```

This will have to be written as:

```dart
int Function(int) bar = (x) => id(x)?.toInt();
```

**Comment by matanlurey** [comment] 2018-09-06 19:42
Duplicate of https://github.com/dart-lang/sdk/issues/4938.

**Closed by matanlurey** 2018-09-06 19:42 UTC
