### ISSUE TITLE
Analysis server out of memory

### ISSUE THREAD

**Issue by daanvandenhoek** [dart-lang/sdk#34929] opened 2018-10-25 15:29 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\user\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68, server version 1.20.5, error: Captured exception
Out of Memory
#0      new Uint8List (dart:typed_data/runtime/libtyped_data_patch.dart:2169:66)
#1      new ByteData (dart:typed_data/runtime/libtyped_data_patch.dart:41:22)
#2      ApiSignature._makeRoom (package:analyzer/src/summary/api_signature.dart:145:30)
#3      ApiSignature.addInt (package:analyzer/src/summary/api_signature.dart:94:5)
#4      _UnitApiSignatureComputer.addTokens (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:96:39)
#5      _UnitApiSignatureComputer.addClassOrMixin (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:48:9)
#6      _UnitApiSignatureComputer.compute (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:110:9)
#7      computeUnlinkedApiSignature (package:analyzer/src/dart/analysis/unlinked_api_signature.dart:15:12)
#8      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:431:31)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:429:24)
#11     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#12     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#13     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218:20)
#14     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291:9)
#15     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:903:22)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:778:12521)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:351:9)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1021:19)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:115:13)
```

```
1540477495856 => {"id":"8591","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":906,"length":0},"clientReq
1540477496530 => {"id":"8592","method":"analysis.updateContent","params":{"files":{"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart":{"type":"add","content":"i
1540477496533 => {"id":"8593","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":908,"length":0},"clientReq
1540477497536 => {"id":"8594","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":907,"length":0},"clientReq
1540477498201 => {"id":"8595","method":"analysis.updateContent","params":{"files":{"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart":{"type":"add","content":"i
1540477498205 => {"id":"8596","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":911,"length":0},"clientReq
1540477499298 => {"id":"8597","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":909,"length":0},"clientReq
1540477500193 => {"id":"8598","method":"analysis.updateContent","params":{"files":{"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart":{"type":"add","content":"i
1540477500197 => {"id":"8599","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":910,"length":0},"clientReq
1540477503949 => {"id":"8600","method":"edit.getFixes","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":873},"clientRequestTime":154
1540477504063 => {"id":"8601","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":875,"length":0},"clientReq
1540477507156 => {"id":"8602","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":893,"length":0},"clientReq
1540477509777 => {"id":"8603","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":876,"length":0},"clientReq
1540477512320 => {"id":"8604","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":913,"length":0},"clientReq
1540477512924 => {"id":"8605","method":"analysis.updateContent","params":{"files":{"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart":{"type":"add","content":"i
1540477512927 => {"id":"8606","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":914,"length":0},"clientReq
1540477514212 => {"id":"8607","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":873,"length":41},"clientRe
1540477514642 => {"id":"8608","method":"analysis.getImportedElements","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":873,"length":
1540477514780 => {"id":"8609","method":"analysis.updateContent","params":{"files":{"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart":{"type":"add","content":"i
1540477514781 => {"id":"8610","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":873,"length":0},"clientReq
1540477515520 => {"id":"8611","method":"analysis.updateContent","params":{"files":{"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart":{"type":"add","content":"i
1540477515523 => {"id":"8612","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":867,"length":0},"clientReq
1540477523756 => {"id":"8613","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":863,"length":0},"clientReq
1540477525248 => {"id":"8614","method":"analysis.updateContent","params":{"files":{"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart":{"type":"add","content":"i
1540477525248 => {"id":"8615","method":"edit.format","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","selectionOffset":0,"selectionLength":0
1540477528600 => {"id":"8616","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":840,"length":0},"clientReq
1540477529365 => {"id":"8617","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":807,"length":0},"clientReq
1540477531776 => {"id":"8618","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":587,"length":0},"clientReq
1540477537656 => {"id":"8619","method":"edit.getAssists","params":{"file":"D:\\Daan van den Hoek\\Documents\\ranzijn_prijskaart_maker\\lib\\SearchScreenWidget.dart","offset":4775,"length":0},"clientRe
1540477539463 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Out of Memory\n#0      new Uint8List (dart:typed_data/runtime/libtyped_data_patch.dart:2
```

**Comment by DanTup** [comment] 2019-02-22 16:45
Maybe same as #34851/#34850?

**Comment by srawlins** [comment] 2019-09-09 21:06
Agreed; duplicate, and should be fixed now.

**Comment by srawlins** [comment] 2019-09-09 21:06
Duplicate of https://github.com/dart-lang/sdk/issues/34851

**Closed by srawlins** 2019-09-09 21:06 UTC
Labels: P2, analyzer-crash-report, area-analyzer, customer-flutter, type-bug
