### ISSUE TITLE
json macro throws when there is a colliding member

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#55696] opened 2024-05-12 10:56 UTC
Repro:
```dart
@JsonCodable()
class Vehicle {
  final int wheels;
  final String description;
  Vehicle(this.wheels, this.description);
  Vehicle.fromJson(Map m) : this(2, 'foo');
}
```

Expected result: Just the error "Cannot generate a fromJson constructor due to this existing one."

Actual result: That error + a throw:

```
Invalid argument(s): [typeParameters.length: 2][typeArguments.length: 0][element: abstract interface class Map<K, V>][typeParameters: [K, V]][typeArguments: []] #0      new InterfaceTypeImpl (package:analyzer/src/dart/element/type.dart:487:7)
#1      InterfaceElementImpl.instantiate (package:analyzer/src/dart/element/element.dart:3709:18)
#2      DeclarationBuilder._resolveTypeCodeNamed (package:analyzer/src/summary2/macro_declarations.dart:519:24)
#3      DeclarationBuilder.resolveType (package:analyzer/src/summary2/macro_declarations.dart:321:16)
#4      _DeclarationPhaseIntrospector.resolve (package:analyzer/src/summary2/macro_application.dart:1130:35)
#5      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:89:22)
#6      _rootRun (dart:async/zone.dart:1399:13)
#7      _CustomZone.run (dart:async/zone.dart:1301:19)
#8      withRemoteInstanceZone (package:_macros/src/executor/remote_instance.dart:172:15)
#9      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:45:9)
#10     _rootRunUnary (dart:async/zone.dart:1415:13)
#11     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#16     _StreamController._add (dart:async/stream_controller.dart:658:7)
#17     _StreamController.add (dart:async/stream_controller.dart:606:5)
#18     _SingleIsolatedMacroExecutor.start.<anonymous closure> (package:_macros/src/executor/isolated_executor.dart:64:33)
#19     _rootRunUnary (dart:async/zone.dart:1415:13)
#20     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#25     _StreamController._add (dart:async/stream_controller.dart:658:7)
#26     _StreamController.add (dart:async/stream_controller.dart:606:5)
#27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by bwilkerson** [comment] 2024-05-22 20:46
Any progress?

**Comment by jakemac53** [comment] 2024-05-22 21:38
Sorry, didn't realize I was assigned here. I am pretty sure this is an analyzer error due to the missing type arguments on `Map`.

**Comment by jakemac53** [comment] 2024-05-22 21:41
Specifically, the macro is asking to resolve the type `Map`. Currently that analyzer will throw if you ask to resolve a type which has type parameters, but no explicit type arguments.

**Comment by mit-mit** [comment] 2024-06-11 10:59
@jakemac53 looks like this was resolved?

```
mit-macbookpro7:repro mit$ dart run --enable-experiment=macros bin/repro.dart
bin/repro.dart:8:3: Error: Cannot generate a fromJson constructor due to this existing one.
  Vehicle.fromJson(Map m) : this(2, 'foo');
  ^
```

**Comment by jakemac53** [comment] 2024-06-11 16:19
I see both the nice error message and the stack trace, so there is still some work to do here for supporting types without explicit generics, but it is better than it was.

**Comment by srawlins** [comment] 2024-06-14 15:16
Reducing from P1 to P2; @scheglov is this on your radar?

**Comment by scheglov** [comment] 2024-06-14 15:35
I can reproduce it.
However it looks that we were given an invalid type annotation.
`Map` requires exactly two type arguments.
<img width="496" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/f5f0f467-a523-433b-bd8c-5d515f49ea97">

**Comment by jakemac53** [comment] 2024-06-14 15:38
> However it looks that we were given an invalid type annotation.

Yes exactly, but I don't think users should be expected to provide explicit type parameters. They should be able to take any type provided to them and ask for the static type of it, without manually filling in any missing type parameters.

I am not sure where on the chain exactly these type parameters should be filled in, but it should be automatic. A macro would require several async calls to even do it.

**Comment by scheglov** [comment] 2024-06-14 15:44
Hm... I think the reason is that we return the syntactic representation of `TypeAnnotation`s when they come from AST. At some point I was thinking that this is a feature. But it looks that it is not helpful. Here `Map` gets no type arguments.

I will try to switch it to actual type arguments.
It might have some interaction with using these not existing type arguments as diagnostic targets.

**Comment by scheglov** [comment] 2024-06-14 16:15
We will return `Map<dynamic, dynamic>` for `Map`, after the types phase, so when we have default types applied.
But this causes an exception in the JSON macro.

I patched the original code a bit to have just one (I thought) problem in it.
```dart
@JsonCodable()
class Vehicle {
  final Map foo;
  Vehicle(this.foo);
}
```

```
[failWithException][MacroImplementationException: element: (DynamicElementImpl) dynamic

#0      DeclarationBuilderFromElement.typeDeclarationOf (package:analyzer/src/summary2/macro_declarations.dart:789:34)
#1      DeclarationBuilder.typeDeclarationOf (package:analyzer/src/summary2/macro_declarations.dart:387:26)
#2      _DeclarationPhaseIntrospector.typeDeclarationOf (package:analyzer/src/summary2/macro_application.dart:1164:31)
#3      new ExternalMacroExecutorBase.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:_macros/src/executor/executor_base.dart:133:41)
```

However there is no `macro.TypeDeclarationImpl` that corresponds to `dynamic`.
So, the analyzer throws an exception.
```dart
  /// See [macro.DeclarationPhaseIntrospector.typeDeclarationOf].
  macro.TypeDeclarationImpl typeDeclarationOf(Element element) {
    switch (element) {
      case ClassElementImpl():
        return classElement(element);
      case EnumElementImpl():
        return enumElement(element);
      case ExtensionElementImpl():
        return extensionElement(element);
      case ExtensionTypeElementImpl():
        return extensionTypeElement(element);
      case MixinElementImpl():
        return mixinElement(element);
      case TypeAliasElementImpl():
        return typeAliasElement(element);
      default:
        // TODO(scheglov): other elements
        throw macro.MacroImplementationExceptionImpl(
          'element: (${element.runtimeType}) $element',
          stackTrace: StackTrace.current.toString(),
        );
    }
  }
```

**Comment by scheglov** [comment] 2024-06-14 16:54
https://dart-review.googlesource.com/c/sdk/+/371561

**Comment by jakemac53** [comment] 2024-06-14 17:14
I am not sure it is obvious whether or not we should provide the inferred type parameters to the users when introspecting, in general we try to give them exactly what was written.

At a minimum I think it would often result in different code being output on the analyzer versus the CFE so we would need to make this change very deliberately and uniformly?

Instead it probably makes sense to handle this when a user actually asks for static types?

**Comment by scheglov** [comment] 2024-06-14 18:09
FWIW, JSON macro asks the `NamedTypeAnnotation` for type arguments, and expects that they are always present.
```dart
    if (classDecl.library.uri == _dartCore) {
      switch (classDecl.identifier.name) {
        case 'List' || 'Set':
          return RawCode.fromParts([
            if (nullCheck != null) nullCheck,
            '[ for (final item in ',
            valueReference,
            ') ',
            await _convertTypeToJson(type.typeArguments.single,
                RawCode.fromString('item'), builder, introspectionData),
            ']',
          ]);
```

**Comment by jakemac53** [comment] 2024-06-17 16:09
> FWIW, JSON macro asks the `NamedTypeAnnotation` for type arguments, and expects that they are always present.

Yes, it requires type arguments for field types, because it uses them to know how to deserialize things. I am pretty sure it would always error out prior to reaching this code, it validates the types before it gets here.

**Comment by scheglov** [comment] 2024-06-17 18:21
When we are asked for `DartType resolveType(macro.TypeAnnotationCode typeCode)`, is there a way to get from `TypeAnnotationCode` to the original `macro.NamedTypeAnnotationImpl`? We could store `NamedType node` in these, and so return the resolved `type` even for `Map` (without type arguments). But I only see that `OmittedTypeAnnotationCode` has `OmittedTypeAnnotation typeAnnotation`.

**Comment by jakemac53** [comment] 2024-06-17 18:51
There is no way to get back to it, no. Can type inference ever fill in just the generics (I assume this is why this would be needed?). Or does it always just get the bounds for the type parameters if the type name is specified but with no generics?

**Comment by scheglov** [comment] 2024-06-17 18:56
I don't understand the distinction. When the analyzer resolves named type annotations, it will use correct type arguments (will the generics), and a way to do it is to use bounds for type parameters. Or `dynamic` if wrong number of type arguments.

However I don't like a possible implication of your question :-)
It would be not nice if we had to replicate this logic in macros.

**Comment by jakemac53** [comment] 2024-06-17 19:51
> I don't understand the distinction. When the analyzer resolves named type annotations, it will use correct type arguments (will the generics), and a way to do it is to use bounds for type parameters. Or dynamic if wrong number of type arguments.

I was trying to understand why you would need to get back to the NamedTypeAnnotation - I was guessing that you wanted to know the surrounding context to do type inference. But, I don't think that is needed in this case.  

> It would be not nice if we had to replicate this logic in macros.

The general expectation today is that you should not need to ever fill in the explicit type arguments. There should be no difference in terms of the APIs you are using, whether or not you do that?

Obviously there is a difference today, which this issue is related to. But, we are trying to fix that :).

**Comment by scheglov** [comment] 2024-06-17 20:04
> > I don't understand the distinction. When the analyzer resolves named type annotations, it will use correct type arguments (will the generics), and a way to do it is to use bounds for type parameters. Or dynamic if wrong number of type arguments.
> 
> I was trying to understand why you would need to get back to the NamedTypeAnnotation - I was guessing that you wanted to know the surrounding context to do type inference. But, I don't think that is needed in this case.

Correct, not for any context, just convert incomplete / invalid `TypeAnnotation` in the analyzer into `DartType`.
And if we can get `NamedTypeAnnotation`, we can store `TypeAnnotation` node there, and get the type from it.
But apparently we cannot.


> > It would be not nice if we had to replicate this logic in macros.
> 
> The general expectation today is that you should not need to ever fill in the explicit type arguments. There should be no difference in terms of the APIs you are using, whether or not you do that?

I don't understand. We have API `DartType resolveType(macro.TypeAnnotationCode typeCode)`. What is the expectation for its behavior is the macro gives us `Map` (without type arguments)? Or `Map<int>`? We can:
1. Throw as in the initial message of this issue.
2. Say that if this code was produced from `macro.TypeAnnotation` in AST, we will make this `macro.TypeAnnotation` right after resolving types, so we will not get wrong `macro.TypeAnnotationCode` into `resolveType`, as I done in https://github.com/dart-lang/sdk/commit/ad54e9b224f4f8a8b7f06bae4d58176723952dff.
3. Say that if this code was produced by the macro manually, it is up to the macro, and `resolveType` still will throw, again this is what happens with my previous fix.
4. Say that we will try to recover during `resolveType`, and if there is wrong number of type arguments, we will replace them by repeating the logic that the analyzer uses during `NamedType` resolution. Which would be sad to duplicate.
5. Provide access from `macro.TypeAnnotationCode` to `macro.TypeAnnotation`, if it was created this way; if not - throw. So, kind of (2), but only for `StaticType`.

**Comment by jakemac53** [comment] 2024-06-17 20:23
> I don't understand. We have API `DartType resolveType(macro.TypeAnnotationCode typeCode)`. What is the expectation for its behavior is the macro gives us `Map` (without type arguments)? Or `Map<int>`? We can:

Without any type arguments, I would expect it to use the type parameter bounds.

With incorrect type arguments I would expect it to throw.

In other words, it should give you exactly the same type that a user would be given, if they wrote the same exact code.

**Comment by scheglov** [comment] 2024-06-17 22:36
OK, it makes sense to instantiate to bounds inside `resolveType()`.
https://dart-review.googlesource.com/c/sdk/+/371942

This CL partially reverts the previous one, so that we don't try to provide absent `NamedTypeAnnotation` type arguments, and just return the right type from `resolveType()`.

**Closed** 2024-06-21 17:47 UTC
Labels: area-analyzer, P2, type-bug, feature-macros
