### ISSUE TITLE
BigInt division returns a wrong number

### ISSUE THREAD

**Issue by darkstarx** [dart-lang/sdk#49963] opened 2022-09-14 08:26 UTC
```
void main()
{
  final n = BigInt.parse('384756799019237345524733441357250782524158781938895052432432661329344633563960814723340715083517478888382006127959558768524838998145197001063083531927877631732256921273752488536731551381226406089385905715658348653914413244840864018239896561892381479584376339096643850442385315984103085577289672584227662791680511348566144195397788221529333710420202711501065754632026285489788253243587707660905524113386056048939378774280391240566913358166557569773137040775847133685319178274169');
  final d = BigInt.parse('384756799019237345524733441357250782524158781938895052432432661289941311925710192259692766123246419827592698185201880786704287165891800960504963282412222885663145453152827881999346769073098115326030582950768174711995246300402876880114660627767835445000319532209168542107802862525281404824372705019957925157644934510477074186429540575979906229555270917297985919106646868960380311587689147233622611844793453739347772048869723655505485506742202366754233857684105900837357976314169');
  print(n ~/ d);
  print(n / d);
}
```

It prints
```
1
NaN
```

Obviously, the result must be a double between `1.0` and `2.0` but the actual result is `NaN`. This is incorrect behavior.

`Dart SDK 2.18.0`

**Comment by julemand101** [comment] 2022-09-14 08:58
Be aware of the following detail in the documentation of the `/` operator for `BigInt`:

> Matching the similar operator on [int](https://api.dart.dev/stable/2.18.1/dart-core/int-class.html), this operation first performs [toDouble](https://api.dart.dev/stable/2.18.1/dart-core/BigInt/toDouble.html) on both this big integer and other, then does [double.operator/](https://api.dart.dev/stable/2.18.1/dart-core/double/operator_divide.html) on those values and returns the result.
>
> **Note**: The initial [toDouble](https://api.dart.dev/stable/2.18.1/dart-core/BigInt/toDouble.html) conversion may lose precision.

https://api.dart.dev/stable/2.18.1/dart-core/BigInt/operator_divide.html

In your case, the two `BigInt` results in the following after calling `toDouble()`:
```dart
  print(n.toDouble()); // Infinity
  print(d.toDouble()); // Infinity
```

**Comment by darkstarx** [comment] 2022-09-14 09:27
> Be aware of the following detail in the documentation of the `/` operator for `BigInt`:
> 
> > Matching the similar operator on [int](https://api.dart.dev/stable/2.18.1/dart-core/int-class.html), this operation first performs [toDouble](https://api.dart.dev/stable/2.18.1/dart-core/BigInt/toDouble.html) on both this big integer and other, then does [double.operator/](https://api.dart.dev/stable/2.18.1/dart-core/double/operator_divide.html) on those values and returns the result.
> > Note: The initial [toDouble](https://api.dart.dev/stable/2.18.1/dart-core/BigInt/toDouble.html) conversion may lose precision.
> 
> https://api.dart.dev/stable/2.18.1/dart-core/BigInt/operator_divide.html
> 
> In your case, the two `BigInt` results in the following after calling `toDouble()`:
> 
> ```dart
>   print(n.toDouble()); // Infinity
>   print(d.toDouble()); // Infinity
> ```

I believe this is incorrect implementation of the division operator for `BigInt` type. The implementation must be corrected in such a way that it satisfies the correct result which is definitely not a `NaN`.

**Comment by julemand101** [comment] 2022-09-14 09:33
The issue seems to have been discussed before: https://github.com/dart-lang/sdk/issues/46578

**Comment by darkstarx** [comment] 2022-09-14 09:39
> The issue seems to have been discussed before: #46578

It must be corrected and not discussed. There is nothing to discuss, it obviously must be fixed.

**Comment by mraleph** [comment] 2022-09-14 11:20
Duplicate of https://github.com/dart-lang/sdk/issues/46578

**Comment by mraleph** [comment] 2022-09-14 11:32
This is currently working as intended, the behaviour is documented and we have no plans to change this. /cc @lrhn

**Closed by mraleph** 2022-09-14 11:32 UTC

**Comment by darkstarx** [comment] 2022-09-14 13:15
> This is currently working as intended, the behaviour is documented and we have no plans to change this. /cc @lrhn

Your intention is wrong. It makes the Dart language useless.

**Comment by lrhn** [comment] 2022-09-14 13:31
@darkstarx I can see the arguments for having a different behavior. It would likely give a more precise value in most cases, only at the cost of being much more expensive too.

The current behavior of `BigInt.operator/` matches the behavior of `int.operator/`, so the libraries are internally consistent.

The `BigInt` class is there to support *integer* operations. Doing a `double`-division does not produce a new `BigInt`, not even if the value is an integer. It moves you from integer/big-integer operations into `double` operations, which are defined only for `double` operands. 
The Dart libraries consistently do `.toDouble()` conversion for operands that are used together with a `double` value.
There is no way to get a `double` result where any of the operands has more than 53 bits of precision, no matter where you start from.
