### ISSUE TITLE
No SIMD support for arm64 `Float64x2.clamp`

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#48941] opened 2022-05-02 18:20 UTC
This tracker is for issues related to:

* Dart VM

It appears that Dart isn't generating SIMD code for `Float64x2.clamp` despite it being [supported by neon](https://developer.arm.com/architectures/instruction-sets/intrinsics/vminq_f64).

See the lack of Float64x2 in https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/backend/il_arm64.cc

**Comment by zanderso** [comment] 2022-05-02 18:51
@a-siva @rmacnak-google

**Comment by mraleph** [comment] 2022-05-02 18:59
Duplicate of #40427

**Closed by mraleph** 2022-05-02 18:59 UTC
Labels: area-vm, type-performance, customer-flutter, type-enhancement

**Comment by gaaclarke** [comment] 2022-05-02 19:08
Sorry, I should have looked these up first.  I could have found them.
