### ISSUE TITLE
[CP] Please cherry-pick 2472741ba02a3d8b08ddab024124fc3a8fddb67e into stable/beta

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#41908] opened 2020-05-15 11:15 UTC
**commit(s) to merge**: 2472741ba02a3d8b08ddab024124fc3a8fddb67e

**merge instructions**:   https://dart-review.googlesource.com/c/sdk/+/148133 (original comit doesn't merge quite cleanly)

**reason**: This change addresses a bug where sending constants between isolates might not correctly get re-canoncialized if those constants have unboxed fields.
Original bug: #41824  ,  [flutter/#57190](https://github.com/flutter/flutter/issues/57190)

/cc @athomas  @franklinyow

**Comment by franklinyow** [comment] 2020-05-19 16:04
Denied base on low use feature

**Comment by mraleph** [comment] 2020-05-20 07:19
I don't see an appeal process for CP review. How does one appeal the decision @pcsosinski?

- We have three separate reports about this issue and an author a moderately popular package had to rewrite their code to work around the issue. 
- It is a regression from the previous behaviour
- For a user it is rather hard to figure out why this does not work - because behaviour violates language specification
- It is a simple low risk fix

Based on this factors I think this should be approved.

**Comment by a-siva** [comment] 2020-05-20 20:42
The original rationale for considering that this change does not meet the bar for cherry picking into Flutter was based on the intuition of low usage of Isolates by Flutter apps, we have some additional data
- the same issue was reported by an external flutter user
- standalone Dart is also effected and use of Isolates in standalone Dart is high
So I think we should approve it from the Dart side and then see if Flutter rolls it into the next hot fix release.

**Comment by franklinyow** [comment] 2020-05-20 20:46
Based on new information, I'm marking this one as approved

**Comment by tvolkert** [comment] 2020-05-20 21:04
flutter eng approval +1

**Comment by franklinyow** [comment] 2020-06-01 20:59
closing

**Closed** 2020-06-01 20:59 UTC
Labels: area-infrastructure, cherry-pick-review, cp-approved, merge-to-beta, merge-to-stable
