### ISSUE TITLE
Inconsistent errors for covariant noSuchMethod dispatches.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#37871] opened 2019-08-14 22:34 UTC
```dart
class A {}

abstract class Accessor<T> {
  dynamic getValueForChild(T value);
}

abstract class BaseAccessor extends Accessor<A> {
  @override
  dynamic getValueForChild(A a) {}
}

class Mock {
  dynamic noSuchMethod(Invocation i) {}
}

class MockAccessor extends Mock implements BaseAccessor {}

class B<T> {
  T value;
  final Accessor<T> accessor;

  B(this.accessor, this.value);

  doStuff() {
    accessor.getValueForChild(value);
  }
}

main() {
  B(MockAccessor(), "any").doStuff();
}
```

The test case passes in DDC but errors with `Expected a value of type 'A', but got one of type 'String'` in DDK. The VM errors with `type 'String' is not a subtype of type 'A' of 'a'`. 

Looking at the JS, DDK inserts typechecks before dispatching to noSuchMethod, while DDC does not. What's the intended behavior here?

cc: @leafpetersen @vsmenon

**Comment by leafpetersen** [comment] 2019-08-14 23:38
Shorter repro:

```dart
abstract class A<T> {
  void foo(T value);
}

class Mock {
  dynamic noSuchMethod(Invocation i) {
    print(i);
  }
}

class MockA extends Mock implements A<int> {}

main() {
  A<Object> a = MockA();
  a.foo("hello");
}
```

The intended behavior is the DDK/VM behavior.

**Comment by vsmenon** [comment] 2019-08-14 23:50
@Markzipan - what's your take on how hard this is to fix internally?

**Comment by Markzipan** [comment] 2019-08-15 00:10
This particular case doesn't look too bad - simply changing whatever's emitting "any" to an empty instance of T would probably do the trick. I'll accumulate a list of tests that need to be updated in google3 as I triage.

**Comment by vsmenon** [comment] 2019-08-15 17:11
Mark - can you open an internal bug to track fixing tests?  Closing this one as we are planning no SDK changes.

**Closed by vsmenon** 2019-08-15 17:11 UTC
Labels: area-web, web-dev-compiler
