### ISSUE TITLE
VmService access to annotations

### ISSUE THREAD

**Issue by pithuene** [dart-lang/sdk#51942] opened 2023-04-04 13:18 UTC
There seems to be no way to access annotations on classes, functions, etc. through the `VmService` class.
As far as I can see this is also not included in the [Service Protocol Spec](https://github.com/dart-lang/sdk/blob/main/runtime/vm/service/service.md).

For some function with an annotation:
``` dart
class MyClass {
  @MyAnnotation()
  void myFunction() { ... }
}
```
I would like a way to access the `MyAnnotation` instance through a `FuncRef` to `myFunction`.
Is there some way to achieve this?

**Comment by a-siva** [comment] 2023-04-04 21:05
//cc @derekxu16 @bkonyi

**Comment by bkonyi** [comment] 2023-04-05 15:20
Duplicate of https://github.com/dart-lang/sdk/issues/41302.

**Closed by bkonyi** 2023-04-05 15:20 UTC
Labels: area-vm, type-enhancement, vm-service
