### ISSUE TITLE
Closured constants as default argument values don't work on functions with modifiers in the VM

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#27719] opened 2016-11-01 16:56 UTC
Default values for optional arguments that come from closured `const` variables don't work on functions with modifiers (`async`, `async*`, `sync*`).

This bug seems to be new in Dart `1.20`, as it was working in `1.19.1`.

This is not an issue for normal functions without modifiers, and not an issue for `const` variables that are top-level or within a class.

It also only occurs on the VM, and not dart2js.

This issue applies for both named and positional optional arguments.

##### Reduced test case
```dart
const topLevelConst = 'topLevelConst';

main() {
  const closureConst = 'closureConst';

  test({
    defaultFromTopLevelConst: topLevelConst,
    defaultFromClosureConst: closureConst
  }) async {
    print('Success!');
  }

  test();
}
```
```
error: line 8 pos 30: expression is not a valid compile-time constant
    defaultFromClosureConst: closureConst
                             ^

#0      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by crelier** [comment] 2016-11-09 19:10
This issue is a duplicate of #27659, which was fixed on Oct 25.

**Closed by crelier** 2016-11-09 19:10 UTC
Labels: area-vm

**Comment by greglittlefield-wf** [comment] 2016-11-09 19:18
@crelier Is this a duplicate? The names don't have to be the same for this issue to occur.

**Comment by crelier** [comment] 2016-11-09 19:26
@greglittlefield-wf If I run your test case, I get "Success!". The error was due to a side effect of parsing the signature twice.

**Comment by greglittlefield-wf** [comment] 2016-11-09 19:26
Awesome, just wanted to make sure. Thanks for double-checking!
