### ISSUE TITLE
standalone/io/http_big_header_test broke Pass -> Timeout on vm-aot-linux-release-simarm_x64

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#54690] opened 2024-01-22 16:50 UTC
from [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8758186315176569601/+/u/test_results/new_test_failures__logs_)

/===========================================================================\
| standalone/io/http_big_header_test broke (Pass -> Timeout, expected Pass) |
\===========================================================================/

--- Command "vm_compile_to_kernel" (took 03.000909s):
DART_CONFIGURATION=ReleaseSIMARM_X64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseSIMARM_X64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMARM_X64/generated_compilations/vm-aot-linux-release-simarm_x64/tests_standalone_io_http_big_header_test/out.dill /b/s/w/ir/tests/standalone/io/http_big_header_test.dart -Dtest_runner.configuration=vm-aot-linux-release-simarm_x64 --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 04.000563s):
DART_CONFIGURATION=ReleaseSIMARM_X64 out/ReleaseSIMARM_X64/gen_snapshot --snapshot-kind=app-aot-elf --elf=/b/s/w/ir/out/ReleaseSIMARM_X64/generated_compilations/vm-aot-linux-release-simarm_x64/tests_standalone_io_http_big_header_test/out.aotsnapshot --loading-unit-manifest=/b/s/w/ir/out/ReleaseSIMARM_X64/generated_compilations/vm-aot-linux-release-simarm_x64/tests_standalone_io_http_big_header_test/ignored.json --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-simarm_x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseSIMARM_X64/generated_compilations/vm-aot-linux-release-simarm_x64/tests_standalone_io_http_big_header_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 53ms):
DART_CONFIGURATION=ReleaseSIMARM_X64 rm /b/s/w/ir/out/ReleaseSIMARM_X64/generated_compilations/vm-aot-linux-release-simarm_x64/tests_standalone_io_http_big_header_test/out.dill

exit code:
0

--- Command "vm" (took 02:00.000176s):
DART_CONFIGURATION=ReleaseSIMARM_X64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseSIMARM_X64/generated_compilations/vm-aot-linux-release-simarm_x64/tests_standalone_io_http_big_header_test out/ReleaseSIMARM/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-simarm_x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseSIMARM_X64/generated_compilations/vm-aot-linux-release-simarm_x64/tests_standalone_io_http_big_header_test/out.aotsnapshot

exit code:
1

diagnostics:
Process list including children: [443537]
Trying to capture stack trace for pid 443537
PID 443537 - process
TID 443537:
#0  0xf7f15549 __kernel_vsyscall
#1  0xf7ee15c4 pthread_cond_wait@@GLIBC_2.3.2
#2  0x569f9773 dart::Monitor::WaitMicros(long long)
#3  0x569f96b4 dart::Monitor::Wait(long long)
#4  0x56afa378 Dart_RunLoop
#5  0x5682992b dart::bin::RunMainIsolate(char const*, char const*, bool, dart::bin::CommandLineOptions*)
#6  0x5682a514 dart::bin::main(int, char**)
#7  0x568296d4 main
#8  0xf7bf9ed5 __libc_start_main
#9  0x56824f71 _start
TID 443538:
#0  0xf7f15549 __kernel_vsyscall
#1  0xf7ce3fab epoll_wait
#2  0x568336ef dart::bin::EventHandlerImplementation::Poll(unsigned int)
#3  0x5692d4b8 dart::bin::ThreadStart(void*)
#4  0xf7eda635 start_thread
#5  0xf7ce3b4a __clone
TID 443545:
#0  0x56a4b65f dart::Simulator::ExecuteNoTrace()
#1  0x56a4c767 dart::Simulator::Call(int, int, int, int, int, bool, bool)
#2  0x56964a19 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)
#3  0x56966876 dart::DartLibraryCalls::HandleMessage(long long, dart::Instance const&)
#4  0x56979e45 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)
#5  0x56984985 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
#6  0x56985057 dart::MessageHandler::TaskCallback()
#7  0x569854e4 dart::MessageHandlerTask::Run()
#8  0x56a5a53d dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)
#9  0x56a5a84e dart::ThreadPool::Worker::Main(unsigned int)
#10 0x569f8f57 dart::ThreadStart(void*)
#11 0xf7eda635 start_thread
#12 0xf7ce3b4a __clone

eu-stack: dwfl_thread_getframes tid 443537 at 0x56824f70 in /b/s/w/ir/out/ReleaseSIMARM/dart_precompiled_runtime: no matching address range

stdout:
64
6400
640000
64000000

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-release-simarm_x64 standalone/io/http_big_header_test

**Comment by a-siva** [comment] 2024-01-22 17:18
This is a duplicate of https://github.com/dart-lang/sdk/issues/52110

**Closed by a-siva** 2024-01-22 17:18 UTC
Labels: area-vm, gardening
