### ISSUE TITLE
VM crash during garbage collection

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28958] opened 2017-03-02 18:17 UTC
This occurred while running on one of the bots (https://build.chromium.org/p/client.dart/builders/analyzer_experimental-linux-release-be/builds/12029/steps/tests%20--host-checked/logs/stdio). In case the file is not accessible, the stack trace from the file follows:

FAILED: dart2analyzer-none release_ia32 lib/js/null_test
Expected: Pass 
Actual: Crash
CommandOutput[dart2analyzer]:

stderr:
Dumping native stack trace for thread 4488
  [0x085838ac] Unknown symbol
  [0x085838ac] Unknown symbol
  [0x08541ec4] dart::RawObject::VisitPointers(dart::ObjectPointerVisitor*)
  [0x08584651] dart::Scavenger::ProcessToSpace(dart::ScavengerVisitor*)
  [0x085851f9] dart::Scavenger::Scavenge(bool)
  [0x083bca07] dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::ApiCallbacks, dart::Heap::GCReason)
  [0x083bcf76] dart::Heap::AllocateOld(int, dart::HeapPage::PageType)
  [0x08455653] Unknown symbol
  [0x0847a8e8] dart::Type::New(dart::Object const&, dart::TypeArguments const&, dart::TokenPosition, dart::Heap::Space)
  [0x084e4619] dart::Parser::ParseType(dart::ClassFinalizer::FinalizationKind, bool, bool, dart::LibraryPrefix*)
  [0x084e53de] Unknown symbol
  [0x084e4067] Unknown symbol
  [0x084f7db5] dart::Parser::ParseVariableDeclarationList()
  [0x084f9a45] dart::Parser::ParseStatement()
  [0x084fa04f] dart::Parser::ParseStatementSequence()
  [0x084ffa00] Unknown symbol
  [0x084ffadf] dart::Parser::ParseIfStatement(dart::String*)
  [0x084f9da7] dart::Parser::ParseStatement()
  [0x084fa04f] dart::Parser::ParseStatementSequence()
  [0x084fb7dc] dart::Parser::ParseFunc(dart::Function const&, bool)
  [0x084fbdda] dart::Parser::ParseFunction(dart::ParsedFunction*)
  [0x083949b0] Unknown symbol
  [0x0839e5e8] Unknown symbol
  [0x083a0762] Unknown symbol
  [0x083a1775] dart::FlowGraphInliner::Inline()
  [0x0830a00e] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x0830a50c] Unknown symbol
  [0x0830bc16] dart::BackgroundCompiler::Run()
-- End of DumpStackTrace

Command[dart2analyzer]: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dartanalyzer_developer --ignore-unrecognized-flags --packages=/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/.packages --format=machine --no-hints /b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/lib/js/null_test.dart
Took 0:00:01.737963

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2analyzer -rnone -aia32 --host-checked -t240 lib/js/null_test

**Comment by fsc8000** [comment] 2017-03-02 19:17
Was there a core dump archived on the buildbot?

**Comment by mraleph** [comment] 2017-03-02 22:00
These bots don't have `--copy-coredumps` enabled. 

It's a duplicate of #28858.

**Closed by mraleph** 2017-03-02 22:00 UTC
Labels: area-vm
