### ISSUE TITLE
Invalid completion: package: is suggested after a package:

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23920] opened 2015-07-30 15:52 UTC
![screen shot 2015-07-30 at 8 52 02 am](https://cloud.githubusercontent.com/assets/5479/8987916/4c4b17c8-3698-11e5-922b-9d7996af7afc.png)

Thanks for taking a look!

**Comment by sethladd** [comment] 2015-07-30 15:52
@devoncarew might this be specific to Atom?

**Comment by devoncarew** [comment] 2015-07-30 15:56
I don't think that's likely. Polling @danrubel to see if this sounds familiar.

**Comment by sethladd** [comment] 2015-07-30 15:56
cc @lukechurch maybe he's seen it?

**Comment by kasperpeulen** [comment] 2015-08-06 01:06
in Webstorm + DAS I also get some interesting results:

![image](https://cloud.githubusercontent.com/assets/1035299/9101506/efc44722-3be7-11e5-880d-27783c217cb5.png)

However that specific example, I can't reproduce, I get no completions there in Webstorm:
![image](https://cloud.githubusercontent.com/assets/1035299/9101520/198124d6-3be8-11e5-8563-fef0041fa770.png)

Seems to do with the colon, before the colon I get this:
![image](https://cloud.githubusercontent.com/assets/1035299/9101525/2b12ec8e-3be8-11e5-8b5c-7fe024551727.png)

**Comment by devoncarew** [comment] 2015-08-06 02:13
On the atom side I _think_ this is a bug fixed in (`0.3.11`). I can't speak to the IntelliJ issue -

**Comment by alexander-doroshko** [comment] 2015-08-06 08:45
This might be an IntelliJ issue - incorrect handling of variants provided by DAS.

**Comment by danrubel** [comment] 2015-08-06 16:34
This is working as intended in Dart Plugins for Eclipse. Is IntelliJ using the replacementOffset and replacementLength to determine what characters should be used to filter the suggestion list?

![2015-08-05_21-50-34](https://cloud.githubusercontent.com/assets/2891888/9117335/3ace7bc6-3c1e-11e5-820b-b49df077ab1c.png)

**Comment by alexander-doroshko** [comment] 2015-08-06 16:39
I've fixed the issue at IntelliJ side, will push in minutes.

**Closed** 2015-08-06 16:53 UTC
Labels: Analyzer-Completion, Area-Analyzer, Priority-Medium, Type-Defect
