### ISSUE TITLE
dart test --coverage=coverage hangs

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/sdk#50771] opened 2022-12-19 13:14 UTC
When I run `dart test --coverage=coverage` on [fluttercommunity/get_it](https://github.com/fluttercommunity/get_it), it hangs and will not complete.

However, `flutter test --coverage` works as expected

`Dart SDK version: 2.18.5 (stable) (Tue Nov 22 15:47:29 2022 +0000) on "macos_arm64"`

**Comment by mraleph** [comment] 2022-12-19 13:30
Duplicate of https://github.com/dart-lang/sdk/issues/50389

**Closed by mraleph** 2022-12-19 13:30 UTC
