### ISSUE TITLE
NPE from LibraryImportScope._lookupInImportedNamespaces, 2.5.0-edge.1ef83b86ae6

### ISSUE THREAD

**Issue by SwissCheese5** [dart-lang/sdk#39110] opened 2019-10-25 11:45 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 193.4697.15`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-193.4697.15, JRE 11.0.4+10-b520.2x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: <<<path>>>  context: exception_20191025_144503_311
NoSuchMethodError: The getter 'isInSdk' was called on null.
Receiver: null
Tried calling: isInSdk
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:578:62)
#2      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:446:15)
#3      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#4      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#6      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#7      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#8      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#9      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#10     EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#11     EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#12     EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:138:27)
#13     Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1132:12)
#14     TypeNameResolver.resolveTypeName (package:analyzer/src/generated/resolver.dart:5920:33)
#15     TypeResolverVisitor.visitTypeName (package:analyzer/src/generated/resolver.dart:7629:23)
#16     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10177:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     TypeArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10064:16)
#19     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#20     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7598:11)
#21     UnifyingAstVisitor.visitTypeArgumentList (package:analyzer/dart/ast/visitor.dart:3454:53)
#22     TypeArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10060:49)
#23     TypeNameImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10182:21)
#24     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#25     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7598:11)
#26     UnifyingAstVisitor.visitTypeName (package:analyzer/dart/ast/visitor.dart:3457:37)
#27     TypeResolverVisitor.visitTypeName (package:analyzer/src/generated/resolver.dart:7627:11)
#28     TypeNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:10177:49)
#29     SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8881:12)
#30     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#31     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7598:11)
#32     UnifyingAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:3407:63)
#33     TypeResolverVisitor.visitSimpleFormalParameter (package:analyzer/src/generated/resolver.dart:7603:11)
#34     SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:8876:15)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#36     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4555:17)
#37     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#38     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7598:11)
#39     UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3243:59)
#40     ScopedVisitor.visitFormalParameterList (package:analyzer/src/generated/resolver.dart:5440:11)
#41     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4551:49)
#42     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5084:18)
#43     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#44     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7598:11)
#45     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3263:57)
#46     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5533:15)
#47     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5079:49)
#48     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7429:18)
#49     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3354:10)
#50     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:7598:11)
#51     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3345:51)
#52     N...
```

**Comment by SwissCheese5** [comment] 2019-10-25 11:46
I did the following:
![2019-10-25_14-45-52](https://user-images.githubusercontent.com/7407478/67568909-2efae500-f736-11e9-9efe-d74ac26300c6.gif)
I can't reproduce the error though.

**Comment by srawlins** [comment] 2021-02-22 17:12
Thanks for reporting this issue. This was previously reported at https://github.com/dart-lang/sdk/issues/38267. Please follow along there.

**Comment by srawlins** [comment] 2021-02-22 17:12
Duplicate of https://github.com/dart-lang/sdk/issues/38267

**Closed by srawlins** 2021-02-22 17:12 UTC
Labels: analyzer-crash-report, area-analyzer
