### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by Anujtiwary69** [dart-lang/sdk#39503] opened 2019-11-24 05:05 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/anujtiwary/AndroidStudioProjects/flutter_app/lib/screens/main_screen.dart
Element mismatch in /Users/anujtiwary/AndroidStudioProjects/flutter_app/lib/screens/main_screen.dart at class _MainScreenState extends State<MainScreen>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:657:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#14     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#15     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#16     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#17     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#23     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#24     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#25     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#27     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#35     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#36     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#37     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#39     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Caused by NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("FirebaseMessaging")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:312:39)
#2      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:359:42)
#3      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#4      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:116:29)
#5      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1030:24)
#6      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:976:15)
#7      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1001:15)
#8      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1397:30)
#9      SummaryResynthesizerContext.resolveTypeRef (package:analyzer...
```

For additional log information, please append the contents of
file:///private/var/folders/b9/ry03c8nd7jg1bmtnlq411qrw0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-11-27 04:59
Thanks for filing this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37979; please follow along there.

**Comment by srawlins** [comment] 2019-11-27 05:00
Duplicate of https://github.com/dart-lang/sdk/issues/37979

**Closed by srawlins** 2019-11-27 05:00 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
