### ISSUE TITLE
./../runtime/vm/thread_pool.cc: 341: error: Could not start worker thread: result = 11.

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#37155] opened 2019-06-04 02:51 UTC
**Dart version**: 2.1.0
**OS Ubuntu**: 18.04.1

**Stack trace**:
```
./../runtime/vm/thread_pool.cc: 341: error: Could not start worker thread: result = 11.
Dumping native stack trace for thread 26e3
  [0x000055d7c03cea2f] dart::Profiler::DumpStackTrace(void*)
  [0x000055d7c03cea2f] dart::Profiler::DumpStackTrace(void*)
  [0x000055d7c06043b2] dart::Assert::Fail(char const*, ...)
  [0x000055d7c046f6f1] Unknown symbol
  [0x000055d7c0321f25] dart::MessageHandler::PostMessage(dart::Message*, bool)
  [0x000055d7c03cd1a5] dart::PortMap::PostMessage(dart::Message*)
  [0x000055d7c0602e06] Dart_PostCObject
  [0x000055d7c00a706b] dart::bin::DartUtils::PostInt32(long, int)
  [0x000055d7c0093b2e] dart::bin::EventHandlerImplementation::HandleEvents(epoll_event*, int)
  [0x000055d7c0093c6b] dart::bin::EventHandlerImplementation::Poll(unsigned long)
  [0x000055d7c00b340e] Unknown symbol
-- End of DumpStackTrace
```

We just found the strange error log in our Dart server (vm) recently, and the dart process has killed already.

Does anyone know about what's wrong with this?

**Comment by jumperchen** [comment] 2019-06-11 08:56
more info:
```
===== CRASH =====
version=2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "linux_x64"
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
Aborting re-entrant request for stack trace.
```

**Comment by jumperchen** [comment] 2019-06-13 02:08
after upgrade to dart 2.3.1, it still causes this error.
```
../../runtime/vm/thread_pool.cc: 341: error: Could not start worker thread: result = 11.
version=2.3.1 (Tue May 21 19:28:38 2019 +0200) on "linux_x64"
thread=2987, isolate=(null)((nil))
  pc 0x000055ed13d08a2c fp 0x00007f1af4a949b0 dart::Profiler::DumpStackTrace(void*)
  pc 0x000055ed13f4fa42 fp 0x00007f1af4a94a90 dart::Assert::Fail(char const*, ...)
  pc 0x000055ed13d97a6f fp 0x00007f1af4a94ad0 /usr/bin/dart231+0x1661a6f
  pc 0x000055ed13c66d65 fp 0x00007f1af4a94b10 dart::MessageHandler::PostMessage(dart::Message*, bool)
  pc 0x000055ed13d072b1 fp 0x00007f1af4a94b40 dart::PortMap::PostMessage(dart::Message*)
  pc 0x000055ed13f4e547 fp 0x00007f1af4a94bf0 Dart_PostCObject
  pc 0x000055ed139f8dcb fp 0x00007f1af4a94c30 dart::bin::DartUtils::PostInt32(long, int)
  pc 0x000055ed139e62a6 fp 0x00007f1af4a94cd0 dart::bin::EventHandlerImplementation::HandleEvents(epoll_event*, int)
  pc 0x000055ed139e63db fp 0x00007f1af4a94e40 dart::bin::EventHandlerImplementation::Poll(unsigned long)
  pc 0x000055ed13a04f25 fp 0x00007f1af4a94e70 /usr/bin/dart231+0x12cef25
-- End of DumpStackTrace
```

**Comment by a-siva** [comment] 2019-06-14 17:11
Can you provide us with some instructions or steps to reproduce the problem you are encountering

**Comment by jumperchen** [comment] 2019-06-17 07:05
@a-siva 
We don't know how it happens yet and it appears this error log in our production server.
After we enabled the debugging logger level in our production server last weekend, we can see a command before the crash log is to send a data (`3` in the log info) to [dart websocket](https://api.dartlang.org/stable/2.1.0/dart-io/WebSocket/add.html).

For example,
https://github.com/rikulo/socket.io-dart/blob/559fafef0f73b2b1b7f9621982ecaa6c9882c51c/lib/src/engine/transport/websocket_transport.dart#L49

And then, the crash log appears again as follows:
```
05:35:11.469535Z:socket_io:transport.WebSocketTransport:3200410
FINE: writing "3"../../runtime/vm/thread_pool.cc: 341: error: Could not start worker thread: result = 11.
version=2.3.1 (Tue May 21 19:28:38 2019 +0200) on "linux_x64"
thread=7051, isolate=main(0x562ccbaebb00)
  pc 0x0000562cc97dea2c fp 0x00007f4773e7d060 dart::Profiler::DumpStackTrace(void*)
  pc 0x0000562cc9a25a42 fp 0x00007f4773e7d140 dart::Assert::Fail(char const*, ...)
  pc 0x0000562cc986da6f fp 0x00007f4773e7d180 /usr/bin/dart231+0x1661a6f
  pc 0x0000562cc973cd65 fp 0x00007f4773e7d1c0 dart::MessageHandler::PostMessage(dart::Message*, bool)
  pc 0x0000562cc97dd2b1 fp 0x00007f4773e7d1f0 dart::PortMap::PostMessage(dart::Message*)
  pc 0x0000562cc965db04 fp 0x00007f4773e7dba0 dart::BootstrapNatives::DN_SendPortImpl_sendInternal_(_Dart_NativeArguments*)
  pc 0x00007f47775c129f fp 0x00007f4773e7dbe0 Unknown symbol
  pc 0x00007f47765a8b31 fp 0x00007f4773e7dc28 Unknown symbol
  pc 0x00007f476ec70071 fp 0x00007f4773e7dcb8 Unknown symbol
  pc 0x00007f476ec72cfc fp 0x00007f4773e7dd18 Unknown symbol
  pc 0x00007f4772b7ed4c fp 0x00007f4773e7de08 Unknown symbol
  pc 0x00007f476ab14c2e fp 0x00007f4773e7def8 Unknown symbol
  pc 0x00007f476ab15aa3 fp 0x00007f4773e7df88 Unknown symbol
  pc 0x00007f4772d8799c fp 0x00007f4773e7dfd8 Unknown symbol
  pc 0x00007f476ab1523e fp 0x00007f4773e7e028 Unknown symbol
  pc 0x00007f4773ca976e fp 0x00007f4773e7e088 Unknown symbol
  pc 0x00007f477452052f fp 0x00007f4773e7e0a8 Unknown symbol
  pc 0x00007f476ec71dd1 fp 0x00007f4773e7e0d8 Unknown symbol
  pc 0x00007f47775c15cc fp 0x00007f4773e7e148 Unknown symbol
  pc 0x0000562cc96d5631 fp 0x00007f4773e7e1f0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x0000562cc96d8af6 fp 0x00007f4773e7e250 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x0000562cc970a7be fp 0x00007f4773e7eca0 dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  pc 0x0000562cc973cece fp 0x00007f4773e7ecf0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x0000562cc973d516 fp 0x00007f4773e7ed50 dart::MessageHandler::TaskCallback()
  pc 0x0000562cc986e207 fp 0x00007f4773e7ed80 dart::ThreadPool::Worker::Loop()
  pc 0x0000562cc986e0c2 fp 0x00007f4773e7edc0 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x0000562cc97db1b9 fp 0x00007f4773e7ee70 /usr/bin/dart231+0x15cf1b9
-- End of DumpStackTrace
```

Note: our code is a snapshot with Dart 2.1.0 version and run it on Dart 2.3.1 VM. (run on Dart 2.1.0 version has the same error)

Another info: 
* the implementation of [eventhandler_linux.cc](https://github.com/dart-lang/sdk/blob/master/runtime/bin/eventhandler_linux.cc#L412) has not changed for long time, so upgrading Dart version might not be useful.
* someone's suggestion on stackoverflow - https://stackoverflow.com/a/13563543

**Comment by rmacnak-google** [comment] 2019-06-18 17:51
This error may be because the process hit the limit for the number of threads it can start.

Does your server use async IO from multiple isolates?

**Comment by jumperchen** [comment] 2019-06-19 01:50
No, we don't use multiple isolates.

**Comment by jumperchen** [comment] 2019-06-19 03:03
But from the `htop` command, the dart process will fork so many child process, does any API in dart cause the fork child process?

**Comment by jumperchen** [comment] 2019-06-19 04:00
We observe that the system process may not be consumed by Dart but Java, we run Dart server and Java server at the same machine. Anyway, we are doing some testing to see which one is the root cause, and we will let you know if it's not related to Dart.

**Comment by a-siva** [comment] 2019-07-02 17:30
Any updates on this, if it is not a Dart issue can you please close this issue.

**Comment by jumperchen** [comment] 2019-07-03 01:46
@a-siva 
Strange!! I think I already commented it 8 days ago, but it seems my comment is disappeared somehow.

Yes, it's okay to close this issue, the root cause is caused by Java execution service, which consumes all the system threads limit.

A suggestion to dart is that you may consider to throw a more readable or distinguishable dart exception error, rather than the `thread_pool.cc` error or kill the dart process directly.

**Comment by a-siva** [comment] 2019-07-03 18:29
Thanks for the update, closing issue.

**Closed by a-siva** 2019-07-03 18:29 UTC
Labels: area-library, area-vm, crash, library-io

**Comment by bubnenkoff** [comment] 2021-07-29 06:48
```
../../runtime/vm/thread_pool.cc: 299: error: Could not start worker thread: result = 22.
version=2.13.0-59.0.dev (dev) (Sun Feb 21 18:06:58 2021 -0800) on "windows_x64"
pid=5908, thread=6956, isolate_group=(nil)(0000000000000000), isolate=(nil)(0000000000000000)
isolate_instructions=0, vm_instructions=7ff654d753e0
  pc 0x00007ff654f84962 fp 0x000000bef1bbfa90 Dart_IsPrecompiledRuntime+0x223f22
-- End of DumpStackTrace
```
I do not have any Java on PC, but got this error on http webserver.

**Comment by a-siva** [comment] 2021-07-29 17:40
errno 22 indicates EINVAL (invalid parameter passed to the thread start function  _beginthreadex
Is the error reproducible and can you give us instructions on how to reproduce ?
Also could you open a fresh issue instead of tagging on an already closed issue, Thanks.

**Comment by AlexV525** [comment] 2022-01-02 11:27
I'm also facing this on a specific Windows device. When it's running the compile command, you can see the sharp increase woth the memory usage too.
![IMG_20220102_192427](https://user-images.githubusercontent.com/15884415/147874266-9b9c0a62-8efa-40cd-b6c3-9ce6b928cb13.jpg)

Platform and version: Windows 10 19042.
Dart: 2.15.1 (stable).
