### ISSUE TITLE
Failures on [kernel] Add some missing default visit methods to visitors

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#51132] opened 2023-01-26 11:07 UTC
There are new test failures on [[kernel] Add some missing default visit methods to visitors](https://github.com/dart-lang/sdk/commit/1d4e6f329c128472b4aae147c0bb0a6708ce3491).

The tests
```
lib/async/stream_periodic3_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-hostasserts-linux-x64-d8
```

Example error ([log](https://dart-ci.appspot.com/log/dart2wasm-linux-x64-d8/dart2wasm-hostasserts-linux-x64-d8/494/lib/async/stream_periodic3_test)):
```
In test "stream-periodic3" Expect.fail('4 is not greater than 10')
    at Expect._fail (wasm://wasm/0011272e:wasm-function[914]:0x2d96f)
    at Expect.fail (wasm://wasm/0011272e:wasm-function[913]:0x2d951)
    at greaterThanOrEqualTo closure at file:///b/s/w/ir/pkg/async_helper/lib/async_minitest.dart:172:40 (wasm://wasm/0011272e:wasm-function[907]:0x2d858)
    at closure wrapper at file:///b/s/w/ir/pkg/async_helper/lib/async_minitest.dart:172:40 (wasm://wasm/0011272e:wasm-function[909]:0x2d881)
    at expect (wasm://wasm/0011272e:wasm-function[905]:0x2d781)
    at main closure at file:///b/s/w/ir/tests/lib/async/stream_periodic3_test.dart:23:56 (wasm://wasm/0011272e:wasm-function[887]:0x2d3aa)
    at dynamic call entry (wasm://wasm/0011272e:wasm-function[901]:0x2d713)
    at method forwarder for 'call' (wasm://wasm/0011272e:wasm-function[619]:0x27ccd)
undefined:0: [object WebAssembly.Exception]
```

/cc @askeksa-google

**Comment by askeksa-google** [comment] 2023-01-26 14:36
Duplicate of https://github.com/dart-lang/sdk/issues/50901

**Closed by askeksa-google** 2023-01-26 14:36 UTC
Labels: gardening, area-dart2wasm
