### ISSUE TITLE
missing // ignore: avoid_types_on_closure_parameters quick fix

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#30735] opened 2017-09-15 10:14 UTC
![image](https://user-images.githubusercontent.com/405837/30477686-5163302a-9a0e-11e7-95a1-367806dcd2c4.png)

If I use the suggested quick fix I get

![image](https://user-images.githubusercontent.com/405837/30477730-74b6208c-9a0e-11e7-8ac5-7798d5135bb0.png)

I get a quick fix to ignore this error, but that doesn't help me with `mw` not being recognized.

The `request()` call is made to

```
ActionDispatcher<Thunk<RxApp, RxAppBuilder, RxAppActions>> get request;
```

which returns

```dart
class ActionDispatcher<P> {
  Dispatcher _dispatcher;
  final String _name;

  String get name => _name;

  void call(P payload) => _dispatcher(new Action<P>(_name, payload));

  ActionDispatcher(this._name);

  void syncWithStore(dispatcher) {
    _dispatcher = dispatcher;
  }
}
```

I'm not sure if this is an analyzer bug as well.
AFAIR there are discussions about changing/removing `call()`.

**Comment by bwilkerson** [comment] 2018-02-07 22:08
@leafpetersen The second error is a strong mode error (StrongModeCode.IMPLICIT_DYNAMIC_PARAMETER) that appears to conflict with a lint rule. Is the strong mode error still valid?

**Comment by leafpetersen** [comment] 2018-02-07 22:16
Implicit dynamic is essentially a lint, turned on by --no-implicit-dynamic.  I believe that we may revisit some warnings that it gives, such as this one: that is, treat an inferred dynamic which is inferred from context as not implicit.

But currently, this is working as intended: there is a variable which is not marked as dynamic, but is inferred as dynamic.

I don't know anything about the other lint, and when it's designed to fire.

**Comment by bwilkerson** [comment] 2018-02-07 22:21
It was written a year ago and is based on the style guide. It triggers whenever a closure is being passed as an argument and recommends removing the type annotations from the closure's parameters. Clearly, it needs to be updated.

**Comment by pq** [comment] 2018-06-27 15:13
So much has changed here (and is still changing), I'm inclined to close this issue and open a fresh one (if needed) when the dust settles.  (If anyone disagrees feel free to re-open as is!)

**Closed by pq** 2018-06-27 15:13 UTC
Labels: P2 medium, Type: bug, analyzer-linter, analyzer-quick-fix, analyzer-server, area-analyzer
