### ISSUE TITLE
analyzer should not support ignore: for error level issues

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#35738] opened 2019-01-23 17:35 UTC
The analyzer shouldn't support using the `// ignore:` syntax for error level issues (just warnings, hints, and lints).

```
    // ignore: invalid_assignment
    int foo = '';
```

**Comment by devoncarew** [comment] 2019-01-23 17:37
Specifically, the above shouldn't suppress the reported issue, and it may cause an issue to be reported for the `ignore: invalid_assignment` line itself.

**Comment by srawlins** [comment] 2019-06-14 15:25
Dupe of https://github.com/dart-lang/sdk/issues/27218

**Closed** 2019-11-18 04:06 UTC
Labels: P2, area-analyzer, type-bug
