### ISSUE TITLE
VM Soundness issue - casting to `Function` can skip argument type checks

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#45428] opened 2021-03-23 17:26 UTC
I can get an `int` into a variable with the static type `String` on the VM with the following:

```
void main() {
  checkAndInvoke(something);
}

void something(List<String> l) {
  String s = l.first;
  print(s);
  print(s.runtimeType);
}

void checkAndInvoke(Function f) {
  var l = <int>[1];
  if (f is Function(List<Never>)) {
    (f as Function)(l);
  }
}
```

The analyzer tells me that the `(f as Function)` is an unnecessary cast (at the info level), but without it there is a static error. If I use `(f as dynamic)` gives the expected runtime error, and no static analysis diagnostics at any level.

**Comment by crelier** [comment] 2021-03-24 17:30
This looks like an issue with code generation. The closure call is made to the unchecked entry point.
Reassigning to @sstrickl who made recent changes to closure calls.

**Comment by sstrickl** [comment] 2021-03-25 08:02
Thanks for the heads up, looking into this now.

**Comment by sstrickl** [comment] 2021-03-25 08:35
So the problem is that we _only_ add dynamic closure call dispatchers if the type of the called object is dynamic, but this is case where we're downcasting and, because of the removal of closure checks when not dynamically called (that is, closures only _have_ one entry point now), things go through unchecked.

Same holds for non-tearoffs:

```
  ((List<String> l) {
    String s = l.first;
    print(s);
    print(s.runtimeType);
  } as Function)(l);
```

has the same issues.

For this case, what we want is to introduce a wrapper of sorts on downcasts that, on being invoked, invokes a function that first checks the parts of the type not covered by the downcasted type before invoking the wrapped closure. (Since we have the original type and downcasted type at compile time, the compiler can make this more efficient than the original checks in closures that checked all of the type information on any such call). This wrapper could even take the place of dynamic closure call dispatchers, since you need to first cast to dynamic before they're invoked, and the wrapper would already do the appropriate checking.

So yeah, I see how to go forward here, and a side benefit is that it'll generalize to the dynamic closure call case so it'll just replace the existing way of handling those.

(And if we wanted to eventually.... we could even use this as a basis for a more general contract system for functions, but that's future work if desired. 😉)

/cc @mkustermann @mraleph

**Comment by mkustermann** [comment] 2021-03-25 08:50
We should only call the closure directly if we have an actual function type at the call site - then we know it's either `kClosureCid` or `kNullCid`.

If the call site is `dynamic` or `Function` the actual receiver can be also a user-defined class with a `call()` method. We should therefore use a normal instance call. It might make sense in this case to modify the selector to use `.dyn:call()` instead of `.call()`, since for both closure targets as well as user-defined classes with `call()` method the signature (as well as types) has to be checked.

**Comment by mraleph** [comment] 2021-03-25 08:51
@sstrickl maybe I am missing soimething, but would not it be simplest to simply treat calls through `Function` type as if it was a `dynamic` call? I know it is going to be slower, but we can address that later if it becomes a problem.

**Comment by sstrickl** [comment] 2021-03-25 08:53
That'll be a quick patch for this particular issue, but I think with more complicated downcasting you can still end up in a situation where you might need a more general solution.

I'll go ahead and do the quick patch for now, though, so this particular version of the problem is fixed, and see if I can come up with a more complicated program that shows it's still not a complete one.

**Comment by mraleph** [comment] 2021-03-25 08:54
@mkustermann note though that you can no longer have user defined types which implement `Function`. This has been prohibited by Dart 2. So `Function` does give us a bit more information than `dynamic` (e.g. that it is a closure call for sure), but you still need to do all the argument checks anyway.

**Comment by mkustermann** [comment] 2021-03-25 08:57
@mraleph Ah, yes, the CFE will auto-tearoff the `.call()` method now.

**Comment by sstrickl** [comment] 2021-03-25 09:00
Also, note this is an interesting interplay between type refinement and downcasting:

```
import 'package:expect/expect.dart';

void main() {
  checkAndInvoke(something);
}

void something(List<String> l) {
  String s = l.first;
}

void checkAndInvoke(Function f) {
  f(["foo"]);
  var l = <int>[1];
  Expect.throwsTypeError(() => f(l));
  if (f is Function(List<Never>)) {
    Expect.throwsTypeError(() => (f as Function)(l));
  }
}
```

The first `Expect.throwsTypeError` fails appropriately, but the second does not.

**Comment by sstrickl** [comment] 2021-03-25 09:15
So yes, we do appropriately insert dyn:calls on the first two calls to `f` (where `f`'s type is `Function`), but not in the latter case (where `f`'s type is `Function(List<Never>)`).

The `(f as Function)` cast does get thrown away as expected, since a `Function(List<Never>)` is always a `Function`, but the promotion keeps the function from being called through a dynamic closure call dispatcher.

**Comment by sstrickl** [comment] 2021-03-25 13:07
So I'd say the problem here is in the front end. Looking at the kernel, the call is being annotated with the type `Function(List<Never>)` despite the cast to `Function` first. So the cast, guaranteed to succeed, is thrown away, but the more specific type information is then used at the call site without further static checking (which would show that it would fail, like how the non-casted call fails at type checking time) and the VM trusts that the appropriate static checking has been done so it does an unchecked call. Alternatively, the widened information from the cast could be used instead, which would cause it to be dynamically checked appropriately by the VM.

@johnniwinther , what do you think about either of those two solutions?

**Comment by sstrickl** [comment] 2021-03-25 13:48
Or maybe this is more appropriately asked of @alexmarkov, since this is VM-specific metadata in the front end.

**Comment by alexmarkov** [comment] 2021-03-30 21:32
Fix: https://dart-review.googlesource.com/c/sdk/+/193524.

**Closed** 2021-03-31 15:58 UTC
Labels: area-vm, soundness
