### ISSUE TITLE
Conditional export won't work in DDC mode only when upgrading to 2.1.1

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#36029] opened 2019-02-26 03:56 UTC
Dart version: 2.1.1 and 2.2.0-dev.2.1

The following example can reproduce this error.
* `main.dart`
```
import 'foo.dart';

void main() {
  print(Foo().sayHi());
}
```
* `foo.dart`
```
// ignore: uri_does_not_exist
export 'foo_impl.dart'
// ignore: uri_does_not_exist
if (dart.library.html) 'html_foo_impl.dart'
// ignore: uri_does_not_exist
if (dart.library.io) 'io_foo_impl.dart';
```

* `foo_impl.dart`
```
class Foo {
  String sayHi() => 'foo';
}
```

* `html_foo_impl.dart`
```
class Foo {
  String sayHi() => 'html_foo';
}
```

* `io_foo_impl.dart`
```
class Foo {
  String sayHi() => 'io_foo';
}
```

And then run with the command 

```$ pub run build_runner serve test```

The error messages:
```
[SEVERE] build_web_compilers|ddc on test/main.dartdevc.module (cached):
Error compiling dartdevc module:foo|test/main.ddc.js

[error] The function 'Foo' isn't defined. (/test/main.dart, line 4, col 9)

Please fix all errors before compiling (warnings are okay).
}

```

**Note:** If we run with `$ pub run build_runner serve test -r` or `$  pub run test test/main.dart` no error at all.

**Comment by jumperchen** [comment] 2019-02-26 04:16
FYI: won't work starting from 2.1.1-dev.0.0

**Comment by natebosch** [comment] 2019-02-26 21:14
I think this is a duplicate of #34179 

Please track that issue for updates.

**Closed by natebosch** 2019-02-26 21:14 UTC
Labels: area-dev-compiler, type-bug
