### ISSUE TITLE
Refactoring to convert params/args between positional and named

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#56280] opened 2024-07-18 19:59 UTC
It would be great if the Dart tooling supported a quick fix that converted functions between positional and named argument types (in either direction).

If the function already has a mix of parameter types, then only the applicable parameters would be converted.

Before:

```dart
  Widget _endorsementWidget(
    Profile profile,
    EndorsementView endorsementView,
    bool isOwnProfile,
    bool hideIfApproved,
  ) { ... }
```

After:

```dart
  Widget _endorsementWidget({
    required Profile profile,
    required EndorsementView endorsementView,
    required bool isOwnProfile,
    required bool hideIfApproved,
  }) { ... }
```

or vice versa.

All invocation site args should also be fixed to correspond to the change in the definition of the function parameters.

(Dart version 3.5.0-180.3.beta)

**Comment by bwilkerson** [comment] 2024-07-18 21:37
We have an experimental refactoring for this. If you're using VS Code you can enable it by checking the "Dart: Experimental Refactors" option.

**Comment by bwilkerson** [comment] 2024-10-07 14:27
I'm closing this as a duplicate of https://github.com/dart-lang/sdk/issues/45675.

**Closed by bwilkerson** 2024-10-07 14:27 UTC
Labels: area-analyzer, P3, analyzer-refactoring, type-enhancement
