### ISSUE TITLE
Dart Analyzer Error: Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by reply-1988** [dart-lang/sdk#35265] opened 2018-11-27 06:57 UTC
[report.txt](https://github.com/dart-lang/sdk/files/2618670/report.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\myaxj\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\projects\flutter_work_schedule\workschedule], excluded: [D:\projects\flutter_work_schedule\workschedule\.idea, D:\projects\flutter_work_schedule\workschedule\.dart_tool, D:\projects\flutter_work_schedule\workschedule\.pub, D:\projects\flutter_work_schedule\workschedule\build]}, clientRequestTime: 1543300665895}
FileSystemException: Exists failed, path = 'D:\projects\flutter_work_schedule\workschedule\build\app\intermediates\javac\debug\compileDebugJavaWithJavac\classes\com\yangyxd\flutterpicker' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-11-30 18:06
Duplicate of #34294

**Closed by stereotype441** 2018-11-30 18:06 UTC
Labels: area-analyzer
