### ISSUE TITLE
dart CI: LateInitializationError: Field 'userProperty' has not been initialized

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#55056] opened 2024-02-28 23:34 UTC
While trying to generate the Flutter docs locally (by running `./dev/bots/docs.sh` from https://github.com/flutter/flutter) I encountered this error:

```
dartdoc:stderr: An unexpected error was encountered by the Dart CLI.
dartdoc:stderr: Please file an issue at https://github.com/dart-lang/sdk/issues/new with the following details:
dartdoc:stderr:
dartdoc:stderr: Invocation: 'dart pub global run snippets --output-directory=doc/snippets --type=dartpad'
dartdoc:stderr: Exception: 'LateInitializationError: Field 'userProperty' has not been initialized.'
dartdoc:stderr: Stack Trace:
dartdoc:stderr: #0      AnalyticsImpl.userProperty (package:unified_analytics/src/analytics.dart)
dartdoc:stderr: #1      AnalyticsImpl.send (package:unified_analytics/src/analytics.dart:613:21)
dartdoc:stderr: #2      ErrorHandler.log (package:unified_analytics/src/error_handler.dart:29:18)
dartdoc:stderr: #3      Session._refreshSessionData (package:unified_analytics/src/session.dart:102:21)
dartdoc:stderr: #4      new Session (package:unified_analytics/src/session.dart:37:27)
dartdoc:stderr: #5      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:429:23)
dartdoc:stderr: #6      new Analytics (package:unified_analytics/src/analytics.dart:87:12)
dartdoc:stderr: #7      createUnifiedAnalytics (package:dartdev/src/unified_analytics.dart:23:10)
dartdoc:stderr: #8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:165:27)
dartdoc:stderr: #9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
dartdoc:stderr: #10     new Future.sync (dart:async/future.dart:306:31)
dartdoc:stderr: #11     CommandRunner.run (package:args/command_runner.dart:122:14)
dartdoc:stderr: #12     runDartdev (package:dartdev/dartdev.dart:46:29)
dartdoc:stderr: #13     main (file:///b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
dartdoc:stderr: #14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)
dartdoc:stderr: #15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by goderbauer** [comment] 2024-02-28 23:37
The error goes away after running `dart --disable-analytics`.

**Comment by parlough** [comment] 2024-02-28 23:38
Duplicate of https://github.com/dart-lang/tools/issues/238 and fixed by https://github.com/dart-lang/tools/pull/239, (pulled in to the SDK by https://github.com/dart-lang/sdk/commit/e0e6231b9e04a4a734c7d3eef5f17924d800952d). I guess it just needs to flow through to `flutter/flutter` still.

**Closed by parlough** 2024-02-28 23:38 UTC
