### ISSUE TITLE
the service protocol field Instance.closureContext is typed as a ContextRef but returns InstanceRefs

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#35897] opened 2019-02-10 18:42 UTC
See https://github.com/dart-lang/vm_service_drivers/pull/203/files#r249177795 for more context.

The field `Instance.closureContext` is spec'd to return a ContextRef. The VM implementation returns InstanceRefs here however. This causes issues in client libraries when we try and deserialize `Instance` objects.

cc @bkonyi

**Comment by bkonyi** [comment] 2019-02-27 21:41
It looks like when an object is null we short circuit and return `Instance(null)`. I'm guessing this is the same cause for #35896. Do you recall whether this has ever come up for a non-null `closureContext`?

**Comment by bkonyi** [comment] 2019-02-27 22:46
Just chatted with @rmacnak-google and I'm not sure what the best thing to do here is. Basically, `null` is technically an instance of `Instance` and `Context` is a subclass of `Object`, not `Instance`, so there's no way to fix the return type in the specification without generalizing to `Object`.

@rmacnak-google was also saying that the service protocol specification was not intended to be used as an IDL, and all RPCs which return a subclass of `Object` can basically be assumed to return a null `Instance`.

cc @a-siva to see if he has any opinion on this.

**Comment by a-siva** [comment] 2019-02-28 01:09
@devoncarew do you have a case where Instance.closureContext returns an InstanceRef which is not null ?

**Comment by devoncarew** [comment] 2019-03-05 23:51
I'll do some quick investigation.

**Comment by devoncarew** [comment] 2019-03-06 00:10
I was not able to reproduce the issue - all the `closureContext`s I saw were types as `@Context`.

> and all RPCs which return a subclass of Object can basically be assumed to return a null Instance

We haven't run into this before - the `closureContext` field is the first time we've seen this, so I'm not sure it's a general problem.

Without finding the repro, I can't say that the problem is related to returning null via `Instance(null)`. I do see plenty of `Instance`s with null `closureContext` fields however. Perhaps for the cases where closureContext might be assigned `Instance(null)`, we instead just use `null` in the json stream?

**Comment by rmacnak-google** [comment] 2019-03-06 00:47
Most fields in the VM are nullable. Fields with a null value have a service response of Instance(null) not JSON null. JSON null would mean the field does not exist or does not have a value. If the type system of your service client cannot handle this, that is a weakness of your client not a bug in the service, and you should consider systematically replacing Instance(null) with host null in your unmarshalling code.

**Comment by bkonyi** [comment] 2019-04-29 22:11
Is this something you're still concerned about @devoncarew? I'm still not sure what the best way forward is for this issue at this point.

**Comment by bkonyi** [comment] 2019-05-22 19:39
Bump, @devoncarew

**Comment by bkonyi** [comment] 2019-07-23 14:57
This case is handled in `package:vm_service_lib`, so we can close this.

**Closed by bkonyi** 2019-07-23 14:57 UTC
Labels: area-vm, vm-debugger
