### ISSUE TITLE
[CP] Fix DevTools failure to load in VS Code side panel

### ISSUE THREAD

**Issue by elliette** [dart-lang/sdk#55327] opened 2024-03-28 16:59 UTC
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/360281

### Target

beta

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/360301

### Issue Description

DevTools switched to compiling with unminified JS. This caused a type error preventing the VS Code DevTools side panel from loading: https://github.com/Dart-Code/Dart-Code/issues/5049

### What is the fix

We reverted to how we normally compile DevTools, with the default minified JS settings. 

### Why cherry-pick

Prevents Flutter VS Code side panel from loading, affecting all users of the side panel. 

### Risk

Low

### Issue link(s)

https://github.com/Dart-Code/Dart-Code/issues/5049

**Comment by kenzieschmoll** [comment] 2024-03-28 17:50
@elliette have you confirmed the PR you landed on main has the right version number for DevTools? According to the commit history, a commit snuck in before your commit that bumped the version to 2.35.0-dev.0: https://github.com/flutter/devtools/commits/master/

**Comment by kenzieschmoll** [comment] 2024-03-28 18:43
I think we will need to do a full cherry-pick release then.
https://github.com/flutter/devtools/blob/master/tool/RELEASE_INSTRUCTIONS.md#cherry-pick-releases

Since DevTools 2.34.1 has not yet been tagged and the DevTools master branch hasn't had any updates since your fix, here's what I would do:
1) open a PR on DevTools to change the version back to 2.34.1
2) once this PR is merged and the build has been uploaded to CIPD, create the Dart SDK cherry pick CL against the SDK beta branch using this hash.

**Comment by elliette** [comment] 2024-03-28 20:57
I've updated this CP request to point to the correct CL, which contains the correct DevTools version.

**Comment by sigmundch** [comment] 2024-03-28 21:53
:heavy_plus_sign: - LGTM to include this cherry-pick. It brings back devtools to use the same optimization level as it had in the past and addresses a visible regression.

cc @jacob314

**Comment by kenzieschmoll** [comment] 2024-03-29 19:01
This cherry-pick request should be closed in favor of https://github.com/dart-lang/sdk/issues/55338, which includes the changes in this CP + one more critical fix for the Deep link tool.

**Comment by itsjustkevin** [comment] 2024-03-29 19:28
Thanks, closing this request @kenzieschmoll

**Closed by itsjustkevin** 2024-03-29 19:28 UTC
Labels: cherry-pick-review, area-tools
