### ISSUE TITLE
Add dart analyze argument for specific path/name analysis_options.yaml

### ISSUE THREAD

**Issue by AlekseyMelikov** [dart-lang/sdk#47650] opened 2021-10-22 10:16 UTC
For more flexibility, it would be great to add an argument for `dart analyze` command, like -o (options file) or -f, to define a specific path to the analysis_options.yaml
```
$ dart analyze -o path/to/options.yaml .
```

**Comment by srawlins** [comment] 2022-01-31 20:46
Duplicate of https://github.com/dart-lang/sdk/issues/45286

**Closed by srawlins** 2022-01-31 20:46 UTC
Labels: area-dart-cli
