### ISSUE TITLE
Can't implicitly assign subclass of specialized generic type to variable of type of subclass

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#32541] opened 2018-03-14 23:07 UTC
```dart
class A<T> { }

class B extends A<int> { }

void test<T>(A<T> foo) {
  if (foo is B) {
    final B fooCast = foo;
  }
}

void main() {
  test(new B());
}
```
Analyzer:
```
  error • A value of type 'A<T>' can't be assigned to a variable of type 'B' at test.dart:7:23 • invalid_assignment
```
Runtime with `--preview-dart-2`:
```
test.dart:7:23: Error: A value of type '#libnull::A<#libnull::test::T>' can't be assigned to a variable of type '#libnull::B'.
Try changing the type of the left hand side, or casting the right hand side to '#libnull::B'.
    final B fooCast = foo;
                      ^
test.dart:7:23: Error: A value of type '#libnull::A<#libnull::test::T>' can't be assigned to a variable of type '#libnull::B'.
Try changing the type of the left hand side, or casting the right hand side to '#libnull::B'.
    final B fooCast = foo;
```

**Comment by matanlurey** [comment] 2018-03-14 23:11
Interesting. I tried the following:

```dart
class A<T> { }

class B extends A<int> { }

void test<T extends int>(A<T> foo) {
  final fooCast = foo as A<int>;
  if (fooCast is B) {
    final B fooCast2 = fooCast;
  }
}

void main() {
  test(new B());
}
```

... which gets farther, at least with the analyzer (it just marks `as` as an unnecessary cast) but there are no warnings or errors, just that hint.

**Comment by eernstg** [comment] 2018-03-15 10:29
In the original example, `if (foo is B) {...}` does not promote `foo`, because `B` is not a subtype of `A<T>` (it's a subtype of `A<T>` for _some_ `T`, but it should be a subtype for _all_ `T` for that subtype relation to hold). So the initialization expression for `fooCast` is simply of an unrelated type, which is an error.

One might come up with some tricky extra rules for assignability that would allow us to "downcast and then upcast" or "upcast and then downcast" (as long as "one of them is a short cast" ;-), so we might then allow `Iterable<int> --> Iterable<num> --> List<num>` or `A<Null> --> A<int> --> B`. But I'm not convinced that the added convenience will be so helpful that it pays for the added complexity. (It's not necessarily good that it's a little bit easier to write the code if it gets a lot harder to understand it.)

But `A<T> --> A<int> --> B` isn't even covered by this kind of rule, because `A<T>` and `A<int>` are unrelated, none is a subtype of the other.

So I think the given situation justifies some more verbosity, e.g., as in @matanlurey's version.

We ought to fix the problem with the "unnecessary cast" hint, though, because it does flag some casts which aren't unnecessary.

**Comment by Hixie** [comment] 2018-03-15 16:45
This would also be fixed by allowing type intersections (or whatever it is that we call the ability for the analyzer to simultaneously believe that a variable implements two unrelated interfaces). I guess I've filed bugs about that before.

**Comment by eernstg** [comment] 2018-03-26 13:38
> This would also be fixed by allowing type intersections

Right, we can always promote to a subtype if we have a variable `x` of type `T` and check `if (x is S) {...}` and then simply check the body of that if-statement under the assumption that both `x is T` and `x is S` are true. (We may not even need to introduce an explicit notion of intersection types like `S & T` in order to do that).

However, that's a separate proposal.

@Hixie, I'll close this issue with 'working as intended'; please create separate 'area-language' issues as needed on the relevant language design issues that came up. We already have an issue on [union types](https://github.com/dart-lang/sdk/issues/4938), and they almost inevitably carry intersection types along with them (and vice versa), but there might be other things that I overlooked.

**Closed by eernstg** 2018-03-26 13:38 UTC
Labels: Resolution: works as intended, area-front-end
