### ISSUE TITLE
Analyzer accepts calls on `Object`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31294] opened 2017-11-07 13:25 UTC
Example:
```dart
confuse(x) => new DateTime.now().microsecondsSinceEpoch > 0 ? x : [x];
main() {
  Object o = confuse((int x) => x);
  print(o(2)); 
}
```
In this expression, the `o(2)` should cause a warning, and it doesn't. Also no error in strong mode.

**Comment by MichaelRFairhurst** [comment] 2017-11-07 16:31
Duplicate of #30987

**Closed** 2017-11-07 16:43 UTC
Labels: area-analyzer, Type: bug
