### ISSUE TITLE
dart:io, address getter of Socket returns wrong address

### ISSUE THREAD

**Issue by zichangg** [dart-lang/sdk#39674] opened 2019-12-06 00:29 UTC
Here is the definition in class `Socket`:
``` dart
  /**
   * Returns the [InternetAddress] used to connect this socket.
   */
  InternetAddress get address;

  /**
   * Returns the remote [InternetAddress] connected to by this socket.
   */
  InternetAddress get remoteAddress;
```

`address` should return the local address of socket and `remoteAddress` will return remote address.

However, running the following program
```dart
import 'dart:io';
import 'dart:async';

main() async {
  var socket = await Socket.connect('www.google.com', 80);
  print('address, ${socket.address}'); // InternetAddress('2607:f8b0:4005:80a::2004', IPv6)
  print('remoteaddress, ${socket.remoteAddress}'); //InternetAddress('2607:f8b0:4005:80a::2004', IPv6)

  await socket.destroy();
}
```
The `address` and `remoteAddress` will print the same address. Actually, they refer to the same address. Check it out here:
https://github.com/dart-lang/sdk/blob/eee20b4e6065f0e3710353a122ee516ff228e4df/sdk/lib/_internal/vm/bin/socket_patch.dart#L501

This is contradictory to the description and need to be fixed.
However, this change has been made many years(at least 3 years), I would assume many users rely on this wrong `address`. Therefore, changing the `address` to return local address may be "breaking".

An alternative is to update the description of `address` and add another getter to return actual `localaddress`. This will be a breaking change.

Any idea?

**Comment by sortie** [comment] 2019-12-06 16:11
I have a proposed fix at <https://dart-review.googlesource.com/c/sdk/+/127465>.

**Comment by brianquinlan** [comment] 2022-12-27 23:26
I'm going to call this a dupe of https://github.com/dart-lang/sdk/issues/39674

**Closed by brianquinlan** 2022-12-27 23:26 UTC
Labels: area-library, library-io, P2, type-bug

**Comment by KagonKhan** [comment] 2024-02-09 10:10
> I'm going to call this a dupe of #39674

Do you mean a duplicate of #50576 ?
