### ISSUE TITLE
Analysis server crashes with the message "The null object does not have a getter 'isInSystemLibrary'"

### ISSUE THREAD

**Issue by christophhermann** [dart-lang/sdk#24755] opened 2015-10-29 18:08 UTC
When using the dart analyses server from the emacs dart-mode, the analysis server crashes with the message:

```
{
   "event":"server.error",
   "params":{
      "isFatal":true,
      "message":"The null object does not have a getter 'isInSystemLibrary'.\n\nNoSuchMethodError: method not found: 'isInSystemLibrary'\nReceiver: null\nArguments: []",
      "stackTrace":"#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)\n#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)\n#2      SdkCachePartition.contains (package:analyzer/src/generated/engine.dart:11128)\n#3      AnalysisCache.get (package:analyzer/src/generated/engine.dart:134)\n#4      AnalysisContextImpl_CycleBuilder._createLibraryOrNull (package:analyzer/src/generated/engine.dart:5232)\n#5      AnalysisContextImpl_CycleBuilder._addDependency (package:analyzer/src/generated/engine.dart:5050)\n#6      AnalysisContextImpl_CycleBuilder._computeLibraryDependenciesFromDirectives (package:analyzer/src/generated/engine.dart:5121)\n#7      AnalysisContextImpl_CycleBuilder._computeLibraryDependencies (package:analyzer/src/generated/engine.dart:5089)\n#8      AnalysisContextImpl_CycleBuilder._addDependency (package:analyzer/src/generated/engine.dart:5052)\n#9      AnalysisContextImpl_CycleBuilder._computeLibraryDependenciesFromDirectives (package:analyzer/src/generated/engine.dart:5115)\n#10     AnalysisContextImpl_CycleBuilder._computeLibraryDependencies (package:analyzer/src/generated/engine.dart:5089)\n#11     AnalysisContextImpl_CycleBuilder._addDependency (package:analyzer/src/generated/engine.dart:5052)\n#12     AnalysisContextImpl_CycleBuilder._computeLibraryDependenciesFromDirectives (package:analyzer/src/generated/engine.dart:5115)\n#13     AnalysisContextImpl_CycleBuilder._computeLibraryDependencies (package:analyzer/src/generated/engine.dart:5089)\n#14     AnalysisContextImpl_CycleBuilder.computeCycleContaining (package:analyzer/src/generated/engine.dart:5012)\n#15     AnalysisContextImpl._createResolveDartLibraryTask.<anonymous closure> (package:analyzer/src/generated/engine.dart:3353)\n#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:152)\n#17     AnalysisContextImpl._createResolveDartLibraryTask (package:analyzer/src/generated/engine.dart:3352)\n#18     AnalysisContextImpl._getNextAnalysisTaskForSource (package:analyzer/src/generated/engine.dart:3773)\n#19     AnalysisContextImpl.nextAnalysisTask (package:analyzer/src/generated/engine.dart:1379)\n#20     AnalysisContextImpl.performAnalysisTask.<anonymous closure>.<anonymous closure> (package:analyzer/src/generated/engine.dart:2312)\n#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:152)\n#22     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/generated/engine.dart:2312)\n#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:152)\n#24     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/generated/engine.dart:2309)\n#25     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:272)\n#26     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:770)\n#27     Future.Future.<anonymous closure> (dart:async/future.dart:118)\n#28     _rootRun (dart:async/zone.dart:900)\n#29     _CustomZone.run (dart:async/zone.dart:803)\n#30     _CustomZone.runGuarded (dart:async/zone.dart:709)\n#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)\n#32     _rootRun (dart:async/zone.dart:904)\n#33     _CustomZone.run (dart:async/zone.dart:803)\n#34     _CustomZone.runGuarded (dart:async/zone.dart:709)\n#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)\n#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)\n#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)\n#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)\n#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)\n"
   }
}
```

The stack trace reminds me of the one in https://github.com/dart-lang/pub-dartlang-dart/issues/44#issuecomment-151277794. 
I conclude the problem is also caused by the analyzer package like mentioned in https://github.com/dart-lang/pub-dartlang-dart/issues/44#issuecomment-151280359 

My platform is Mac and I am running dart version 1.12.2 installed with homebrew.

**Comment by zoechi** [comment] 2015-10-29 18:10
dup of #24735?

**Comment by christophhermann** [comment] 2015-10-29 18:16
Yes, I think #24735 has the same cause.

Is there a way to force the analysis server or dart in general to use the analyzer in version `analyzer: 0.26.1+14`? Or is this dependency compiled into the `dartanalyzer.dart.snapshot`?

**Comment by kevmoo** [comment] 2015-10-30 18:26
Closing as dupe of https://github.com/dart-lang/sdk/issues/24735

**Comment by kevmoo** [comment] 2015-10-30 18:27
@christophhermann analysis server + analyzer version is baked into the SDK. You'll have to upgrade the SDK to get any fixes

**Closed by kevmoo** 2015-10-30 18:27 UTC
Labels: Area-Analyzer
