### ISSUE TITLE
_JenkinsSmiHash should be exposed by SDK

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#25553] opened 2016-01-21 21:19 UTC
The `_JenkinsSmiHash` class (`sdk/lib/math/jenkins_smi_hash.dart`) is useful enough that it has now been duplicated in 6 places:

    pkg/analysis_server/lib/src/protocol/protocol_internal.dart (*)
    pkg/analyzer/lib/src/generated/utilities_general.dart
    runtime/observatory/lib/object_graph.dart
    sdk/lib/html/dart2js/html_dart2js.dart
    sdk/lib/html/dart2js/html_dartium.dart
    tools/dom/templates/html/impl/imtl_ClientRect.darttemplate

(*Note that the implementation in analysis_server is could be replaced with a reference to the one in analyzer).

We should expose the SDK's implementation of `_JenkinsSmiHash` so that all the duplicate definitions can be eliminated.

This would also allow us to synthesize better code when generating default implementations of `hashCode` (an IntelliJ feature @jwren is currently working on).

**Comment by floitschG** [comment] 2016-01-22 13:07
Duplicate of #11617.

**Closed by floitschG** 2016-01-22 13:07 UTC
Labels: area-library
