### ISSUE TITLE
Analyzer start consuming 100% CPU core each time with specific declaration

### ISSUE THREAD

**Issue by woprandi** [dart-lang/sdk#45662] opened 2021-04-12 15:59 UTC
The dart analyzer starts using 100% of a CPU core and will never stops until I restart or kill it. 
I'm able to reproduce the problem every time by opening an empty dart file and write this piece of code (do not copy/paste).

```
class Foo {
  final List<List<int>> p;
}
```
After a restart/kill of the analyzer. Just clear and re-write this code and the problem will reappear. It doesn't like the List of List

![dartanalyzer](https://user-images.githubusercontent.com/1449422/114425131-13e59480-9bb9-11eb-894a-9d79af068ada.png)

`Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "linux_x64"`
`IntellJ IDEA 2021.1`

**Comment by bwilkerson** [comment] 2021-04-12 16:25
@scheglov

**Comment by leonardoprc** [comment] 2021-04-12 17:11
Unhandled exception:
NoSuchMethodError: Class 'ApplicationCtrl' has no instance getter 'loadSession'.
Receiver: Instance of 'ApplicationCtrl'
Tried calling: loadSession









Future<SessionControl> connectToSession() async {
  var control = SessionControl<Login>(
      deserializer: ApplicationCtrl.loadSession,
      serializer: ApplicationCtrl.saveSession);
  return control;
}
/// Handles sessions and cookies within an Angel application.
class ApplicationCtrl {
...
  static loadSession(RequestContext req, Login login) async {
...
  static saveSession(RequestContext req, Login login, Map cookies) async {
...


How to make this interface?

--
Leonardo Costa
leonardoprc # gmail dot com

**Comment by woprandi** [comment] 2021-04-12 19:46
I don't know if there are analyzer logs somewhere to help you

**Comment by jensjoha** [comment] 2021-04-13 07:32
> I was not able to reproduce this, but from history this sometimes happens when the parser cannot make progress. @jensjoha Is this something that might have been fixed recently?

Not that I know of.

**Comment by scheglov** [comment] 2021-04-13 23:10
@woprandi Logs might be not enough here. Could you try to look into Observatory and CPU profile there (for `main` isolate)?
See https://github.com/dart-lang/sdk/issues/44501#issuecomment-784487099 for some description. As usually with profiling it might require creative looking :-)

**Comment by woprandi** [comment] 2021-04-14 07:48
@scheglov I did and there is two screenshots, I don't know if you can see something strange. 

![Screenshot_2021-04-14 Dart VM Observatory](https://user-images.githubusercontent.com/1449422/114673262-48b33200-9d06-11eb-988f-737f590d7f36.png)
![Screenshot_2021-04-14 Dart VM Observatory](https://user-images.githubusercontent.com/1449422/114673310-55378a80-9d06-11eb-8f6c-0fc2e7a199ba.png)

**Comment by scheglov** [comment] 2021-04-14 16:31
It looks that it cycles in `ignoreComments` of `extension on CompilationUnit`.
It does not look that there were recently any changes to this code. @bwilkerson 

Try to remove `~/.dartServer/.analysis-driver` and see if this helps.

**Comment by bwilkerson** [comment] 2021-04-14 17:18
There are two loops, but they both look like they should always terminate, assuming that the token stream produced by the scanner hasn't changed recently. It's possible that the stream is malformed in some cases where recovery kicks in. We could try parsing successively longer prefixes of the code above and invoke this method to see which state causes the infinite loop.

**Comment by woprandi** [comment] 2021-04-14 19:31
@scheglov I removed the folder, without any difference

**Comment by bwilkerson** [comment] 2021-04-15 18:24
I tried the experiment I suggested (successively longer prefixes), and it completed quickly. I also tried removing each individual character, and that also ran quickly. It's possible that we need partial code that doesn't match one of those patterns, but I don't know of any reasonable way to test all possible permutations of the code, so I don't know how to reproduce the bug at this point.

**Comment by tatumizer** [comment] 2021-04-15 23:40
I reproduced the problem in VSCode. The culprit is NOT `<List<List<int>> p;` 
The analyzer becomes unresponsive for other reasons that precede your typing of  `<List<List<int>> p;` 
What I did was this: I played with absurd declarations, appending suffixes to "int", like `<List<List<int.hashCode>> p;` - tried different things. Analyzer starts showing the signs of trouble right away: the suggestion box is saying it's "Looking" for something, but the process of "looking" never ends. And then, after a number of equally absurd modifications (`int.toString`, `int+1`) it goes totally insane - it doesn't follow the cursor any longer, the bottom panel saying "Analyzing...". At this point, you can enter anything - including `<List<List<int>> p;` - with no effect on the analyzer. If you close VSCode and then restart it, the problem is still there, the analyzer is still "Analyzing...". I had to resort to googling to find out how to restart the analyzer.

Unfortunately, I don't have a record of modifications I tried for `int.xxx`, but it wasn't too many - 2 or 3.

**Comment by woprandi** [comment] 2021-04-16 10:06
I tested with the latest dart dev version (2.14) but it didn't help

**Comment by tatumizer** [comment] 2021-04-18 02:56
I can't say what the minimal example is, but I reached 100% reproducibility on VSCode with the following program:
```dart
class A {
  List<List<List<int>>> p;
}
```
Now I just add dot to int:
```dart
class A {
  List<List<List<int.>>> p; // added dot!
}
```
That's it. Analyzer goes into a permanent state of "Analyzing...". And it's not so easy to put it out of this state.

**Comment by bwilkerson** [comment] 2021-04-19 16:29
Excellent! Thanks!

@jensjoha It looks like this is a bug in the parser. I wrote a small script (using a utility function in `analyzer`) to parse the text to see what AST was being produced:

```
import 'package:analyzer/dart/analysis/utilities.dart';

void main() {
  parseString(content: '''
class A {
  List<List<List<int.>>> p; // added dot!
}
''');
}
```

Running this script, with asserts enabled, produced the following output:

```
Unhandled exception:
'package:analyzer/src/fasta/ast_builder.dart': Failed assertion: line 2256 pos 12: 'optional('>', rightBracket)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AstBuilder.endTypeArguments (package:analyzer/src/fasta/ast_builder.dart:2256:12)
#3      ComplexTypeParamOrArgInfo.parseArguments (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:1044:21)
#4      ComplexTypeInfo.parseType (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:553:31)
#5      ComplexTypeInfo.ensureTypeOrVoid (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:505:7)
#6      ComplexTypeParamOrArgInfo.parseArguments (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:1026:24)
#7      ComplexTypeInfo.parseType (package:_fe_analyzer_shared/src/parser/type_info_impl.dart:553:31)
#8      Parser.parseFields (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2743:28)
#9      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3743:15)
#10     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3382:15)
#11     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1999:13)
#12     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1957:14)
#13     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#14     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#15     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#16     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:195:32)
#17     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:191:12)
#18     parseString (package:analyzer/dart/analysis/utilities.dart:90:21)
#19     main (package:nnbd_test_package/test.dart:7:3)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Looking in the debugger, the `rightBracket` is an EOF token.

**Comment by woprandi** [comment] 2021-04-21 13:46
Not really related to this specific issue but after some rest days, I'm working again on some flutter code since today and I have many issues with the analyzer which frequently stop working (without necessarily consuming CPU-core as here) and I'm forced to restart it manually in IntelliJ. Few times since this morning. It seems to have some regressions since before

**Comment by srawlins** [comment] 2021-07-20 05:21
I'll throw this over to CFE.

**Comment by johnniwinther** [comment] 2021-07-20 05:24
I think this is related to #46505 and might have been fixed by recent changes.

**Comment by jensjoha** [comment] 2022-02-02 10:01
I don't reproduce this anymore, so I'll assume it's fixed and will close this issue.

**Closed by jensjoha** 2022-02-02 10:01 UTC
Labels: front-end-fasta, area-front-end
