### ISSUE TITLE
Retaining path and _GrowableList.remove

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#27054] opened 2016-08-11 09:29 UTC
Below is a bug report with a lot of speculation. I may be completely wrong about how I diagnose the problem, but I did observe a problem. So please apply critical thinking :-)

I've been using the Observatory to track down memory leaks. At first it looks like _GrowableList is holding on to deleted elements. For example:

```
class LeakyMcLeakFace {}

var leak = new LeakyMcLeakFace();

var noLeak;

main() {
  noLeak = []..add(leak);
  noLeak.remove(leak);
  // Pause isolate here and find retaining path to strongly reachable
  // instances of [LeakyMcLeakFace].
}
```

In this situation, it may look as if `noLeak` is holding on to the instance of `LeakyMcLeakFace`.

I don't know if this problem reproduces in this simple example. This illustrates what I think was wrong in my more complicated real example.

After writing my own version of `remove` that explicit nulls out the array entry, I could find the real cause of the leak (in the simple example, that is `leak`).

My guess is that the garbage collector knows that the backing array of _GrowableList only `length` entries, but that the retaining path algorithm thinks it has `capacity` entries.

**Comment by rakudrama** [comment] 2016-08-11 11:27
The length setter nulls out freshly unused elements of the backing _List when the length is decreased.

https://github.com/dart-lang/sdk/blob/master/runtime/lib/growable_array.dart#L132

Could you find an example that demonstrates the leak?

The problem might be your methodology and how observatory supports it.
Does hitting the GC button do a full GC? I don't think so because it takes two presses to vacate new-space. If the GC is a new-space GC, 'remove' replaces the backing list (see _shrink) and the old backing _List is in old-space, and the reachability information is single-link rather than from-roots, then an uncollected garbage backing array would reference the uncollected garbage element.

Try following the references backwards to see if this is what is happening.

**Comment by peter-ahe-google** [comment] 2016-08-11 14:56
As you can see from the screen shot below, I have an instance of LeakyMcLeakFace that's referenced by the backing list of a _GrowableList of size 0.

![screen shot 2016-08-11 at 16 50 37](https://cloud.githubusercontent.com/assets/5689005/17592757/c5e51e74-5fe3-11e6-8a91-25e01b3e48ba.png)

And I was wrong. This is the leak. This isn't the observatory finding the wrong path to the object. When I use my own version of remove the leak goes completely away. So this isn't an observatory bug.

**Comment by peter-ahe-google** [comment] 2016-08-11 14:57
I'll make a repro.

**Comment by johnmccutchan** [comment] 2016-08-11 14:57
@rmacnak-google

**Comment by peter-ahe-google** [comment] 2016-08-11 15:03
@johnmccutchan I don't think this is an observatory bug after all. See my second comment.

**Comment by peter-ahe-google** [comment] 2016-08-11 15:14
Here's a repro that requires access to Git on Borg:

```
mkdir repro
cd repro/
git clone sso://user/ahe/rasta
cd rasta
git checkout repro
git submodule update --init
./bin/rastak --batch --pattern '\.dart$' co19/
```

`./bin/rastak` requires that you have dart in your path.

I'm using this version: `Dart VM version: 1.17.0-dev.1.0 (Wed Apr 27 06:07:12 2016) on "macos_ia32"`.

The program will print:

```
...
=== Summary ===
Total: 9
Failures: 0
Average time per test: 125.000ms
Success rate: 100.00%
```

Once this happens hit Ctrl-\ and navigate to the allocation profile of the observatory. There find LeakyMcLeakFace. Under instances look for "strongly reachable" click `[find]`. Then there should be one instance of LeakyMcLeakFace. Click on that and find its retaining path. It will be similar to the screen shot above.

**Comment by peter-ahe-google** [comment] 2016-08-11 15:17
You can remove the leak by uncommenting the code in `removeSubtype` in `third_party/dart-sdk/pkg/compiler/lib/src/universe/class_set.dart`.

**Comment by johnmccutchan** [comment] 2016-08-11 16:06
@B3rn475 FYI

**Comment by a-siva** [comment] 2016-08-11 16:33
Nice catch Peter, thanks for the repro.
a 0 sized array is of size 24 and with object alignment it becomes 32 (one word padding).
In this case the 'remove' removed the last element and made it a 0 sized element but the reference
was retained in the padding area leading to the leak.

**Comment by mraleph** [comment] 2016-08-12 12:03
@a-siva I don't think padding should ever be scanned. `RawArray::VisitArrayPointers` scans only meaningful part of the array. 

I think the issue is actually in `_GrowableList.set:length`:

```dart
  void set length(int new_length) {
    int new_capacity = (new_length == 0) ? _kDefaultCapacity : new_length;
    if (new_capacity > _capacity) {
      _grow(new_capacity);
      _setLength(new_length);
      return;
    }
```

There is a corner case in this code. If `new_length` is 1 and `_capacity` is 1, then we actually increase `_capacity` from 1 to 2 instead of shrinking. As a result we will not `null` out storage content. 

 It's easy to reproduce by writing code like this:

```dart
main() {
  var list = [1];
  list.remove(1);
}
```

if you look at `list` backing store you will see it has capacity of 2 and first element is still 1.

**Comment by a-siva** [comment] 2016-08-12 23:22
Yes, I saw that Slava and a fix has been submitted.

**Comment by a-siva** [comment] 2016-08-12 23:23
https://github.com/dart-lang/sdk/commit/cb36467568ed3af7da53c10447d17c05339422bf

**Closed by a-siva** 2016-08-12 23:23 UTC
Labels: area-observatory, area-vm
