### ISSUE TITLE
Error when Open IntelliJ Project #Unknown #HELP

### ISSUE THREAD

**Issue by MagicDemonn** [dart-lang/sdk#37801] opened 2019-08-10 05:36 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.7479.19`
- `2.4.0`
- `IU-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-55-generic, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:615:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment] 2019-08-10 23:14
Thanks for the report! This looks like a duplicate of https://github.com/dart-lang/sdk/issues/36943.

**Closed by srawlins** 2019-08-10 23:14 UTC
