### ISSUE TITLE
[breaking change] Extend function definition with "throws exception"

### ISSUE THREAD

**Issue by Mirko607** [dart-lang/sdk#56926] opened 2024-10-21 08:33 UTC
### Change Intent

Enable an optional way for communicating that exceptions can happen by extending the function definition with the phrase "throws exception": 

```dart
// Signaling that this function might throw an exception. 
// Tooltips in IDEs coudl be extended to highlight this. 
void myFunc() throws exception { 
    throw Exception("something went wrong");
}
```

Currently:
```dart
void myFunc() { //no signaling whatsoever that this function might throw an exception
    throw Exception("something went wrong");
}
```

An IDE might propose a Quick-Fix when "throws exception" is not present in the function definition although the function might throw an exception.

(Though I personally prefer the sound of "raises exception" but "throws exception" is probably better suited since the keyword `throw` is used in the dart language.)

### Justification

Without any digging there is no way of knowing whether a function might throw an error or not. Having (1) a program running unexpectedly into an error or (2) encapsule "just in case" everything in a try-catch block and say "sorry, an unexpected error has occured" is fatal in the first case and is at least no good practice in the second case. 

Especially for new programmers or even experienced ones using new packages this would be really helpful. 

### Impact

Anyone could see at a glance if a function might throw an exception. Having this information would massively improve stability and usabilty of programs in general. Making this feature optional also means that any progammer can decide to use it. I would suggest to make the IDE point out a missing "throws exception" and offer a quick fix.

**Comment by mraleph** [comment] 2024-10-21 09:53
Duplicate of https://github.com/dart-lang/language/issues/984

**Closed by mraleph** 2024-10-21 09:53 UTC
Labels: area-language, closed-duplicate, type-enhancement

**Comment by lrhn** [comment] 2024-10-21 10:07
This would only work for exceptions, not `Error`s, since every function might throw an error (if you include `StackOverflowError`). So the syntax is fitting, if verbose. Just `throws` would be enough. 

That's also a problem. Knowing that a function may throw an exception does not tell you _which_ reception it throws. 
You're discouraged from just catching `Exception`, since the purpose of exceptions is to be caught and handled, and you can't properly handle an exception if you don't know what it represents.
Satisfying a `throws` by catching the wrong exception doesn't actually provide any safety.

All in all, Java-stole "checked exceptions" has been suggested before (fx #984). It's unlikely that Dart will go that way, for the same reasons that no post-Java language has cooled that particular feature. It's not worth the overhead it causes.

**Comment by Mirko607** [comment] 2024-10-21 10:56
I read through the mentioned issues and I agree that it may not become a feature of the dart language. But the issue remains. Is there some work going on to adress it? If not maybe at least some smaller things could be done? https://github.com/dart-lang/linter/issues/2246#issuecomment-2426292063
