### ISSUE TITLE
[cfe] Missing error message for type alias with non-well-bounded type in body

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42434] opened 2020-06-22 11:47 UTC
Dart VM version: 2.9.0-17.0.dev (dev) (Thu Jun 18 10:22:39 2020 +0200) on "windows_x64"

Analyzer throws a error whereas dart passes with the following source code example:
``` dart
class A<X extends A<X>> {}
typedef AAlias<X> = Function<X1 extends A<X>> ();
main() {}
```

Sample output is:
> $> dart test.dart
> 
> $> dartanalyzer test.dart
> Analyzing test.dart...
>   error - 'X' doesn't extend 'A\<X>'. - test.dart:2:43 - type_argument_not_matching_bounds
> 1 error found.

Please note that this is very similar with the case described in the Issue #36870, however the result is opposit: there dart fails where analyzer does not throw any errors.

**Comment by lrhn** [comment] 2021-01-25 21:19
I'd say the analyzer is right here.

The `X` of `typedef AAlias<X> = Function<X1 extends A<X>> ();` is not bounded to satisfy `X extends A<X>`, so it's not a valid type argument to `class A<X extends A<X>> {}` in `X1 extends A<X>`. That makes `A<X>` malbounded - exactly where the analyzer complains.
Am I missing something @eernst?

**Comment by eernstg** [comment] 2021-01-27 18:09
I agree, all types in the body of a type alias [must be well-bounded](https://github.com/dart-lang/language/blob/75d7d473c582931c7ccd6c01bc2fedbb0172a568/specification/dartLangSpec.tex#L5139).

It's confusing that the error message is shown as `'X' doesn't extend 'A'` [here](https://github.com/dart-lang/sdk/issues/42434#issue-643001051), but the message that I see from the analyzer today is `'X' doesn't extend 'A<X>'`. So the analyzer is working as intended.

However, the CFE does _not_ detect this error, so I'll change the title and labels accordingly.

@johnniwinther, I suspect this is a duplicate of another CFE issue, but I couldn't easily find it. WDYT?

**Comment by johnniwinther** [comment] 2021-01-28 09:19
cc @stefantsov 

We have (had?) other errors of this kind but I don't think this case is duplicate.

**Comment by stefantsov** [comment] 2021-01-28 13:20
There are some related issues.  I'm working on solving them together at https://dart-review.googlesource.com/c/sdk/+/181402.

**Closed** 2021-02-01 18:49 UTC
Labels: area-front-end, front-end-missing-error, type-bug
