### ISSUE TITLE
language_2/script2_test is failing

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#39472] opened 2019-11-20 23:39 UTC
language_2/script2_test started failing as of https://dart-review.googlesource.com/c/sdk/+/125727 and wasn't fixed by the follow up CL https://dart-review.googlesource.com/c/sdk/+/125768.

It seems that the test is passing when it should be a compile error:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8896232071813148464/+/steps/test_results/0/logs/unapproved_failing_tests/0
https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-ast-linux-release-x64/268

**Comment by munificent** [comment] 2019-11-22 01:09
Dupe of #39454.

The test has been incorrectly passing for ages. (It was a negative test that used to only inadvertently be testing that a part file without a `part of` directive reported an error.) I fixed and renamed the test, which exposed that the implementations are in fact not behaving as they should.

**Closed by munificent** 2019-11-22 01:09 UTC
Labels: area-test
