### ISSUE TITLE
Dart Analyzer Server crash

### ISSUE THREAD

**Issue by Zazo032** [dart-lang/sdk#38809] opened 2019-10-10 09:58 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.48e93d3d3b38ec87a02a7f8743eae08aaa597965`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.48e93d3d3b38ec87a02a7f8743eae08aaa597965, server version 1.27.3, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Cristian\Desktop\com.airhopping.app], excluded: [C:\Users\Cristian\Desktop\com.airhopping.app\.idea, C:\Users\Cristian\Desktop\com.airhopping.app\.dart_tool, C:\Users\Cristian\Desktop\com.airhopping.app\.pub, C:\Users\Cristian\Desktop\com.airhopping.app\build]}, clientRequestTime: 1570701093195}
FileSystemException: Directory watcher closed unexpectedly, path = 'C:\Users\Cristian\Desktop\com.airhopping.app'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:307:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file://C:\Users\Cristian\AppData\Local\Temp\report.txt.

[report.txt](https://github.com/dart-lang/sdk/files/3711699/report.txt)

**Comment by srawlins** [comment] 2019-10-16 13:34
Thanks for reporting this issue! This was also reported at https://github.com/dart-lang/sdk/issues/38853, which now has more information, so I'll close this issue in favor of that one; please follow along there.

**Comment by srawlins** [comment] 2019-10-16 13:34
Duplicate of https://github.com/dart-lang/sdk/issues/38853

**Closed by srawlins** 2019-10-16 13:34 UTC
Labels: analyzer-crash-report, area-analyzer, crash
