### ISSUE TITLE
Kernel: VM Crash after compile-time error

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#29245] opened 2017-04-04 12:45 UTC
This shouldn't happen, Fasta has reported compile-time errors so we shouldn't be reading the source code. Also, it looks like this is the VM parser, not kernel that's reading the code.

```
FAILED: dartk-vm debug_x64 co19/Language/Classes/Constructors/Generative_Constructors/initializers_t09
Expected: Pass 
Actual: Crash
Compile-time error expected.
CommandOutput[vm]:

stdout:
tests/co19/src/Language/Classes/Constructors/Generative_Constructors/initializers_t09.dart:25:9: Error: Can't use x here.
tests/co19/src/Language/Classes/Constructors/Generative_Constructors/initializers_t09.dart:26:3: Error: Expected a function body, but got 'var'.


stderr:
../../runtime/vm/object.h: 7020: error: expected: raw() != null()
Dumping native stack trace for thread 16fb
  [0x00000000009bf363] dart::Profiler::DumpStackTrace()
  [0x00000000009bf363] dart::Profiler::DumpStackTrace()
tests/co19/src/Language/Classes/Constructors/Generative_Constructors/initializers_t09.dart:26:3: Error: Expected a function body, but got 'var'.
  [0x0000000000695f91] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x0000000000692480] Unknown symbol
  [0x00000000008b989b] dart::String::StartsWith(dart::String const&) const
  [0x00000000008ccf33] dart::Library::LookupReExport(dart::String const&, dart::ZoneGrowableArray<long>*) const
  [0x00000000008cd35d] dart::Namespace::Lookup(dart::String const&, dart::ZoneGrowableArray<long>*) const
  [0x00000000008cb595] dart::Library::LookupImportedObject(dart::String const&) const
  [0x00000000008cad74] dart::Library::ResolveName(dart::String const&) const
  [0x00000000008a3d20] dart::Library::LookupClass(dart::String const&) const
  [0x000000000069f585] dart::ClassFinalizer::ResolveClass(dart::Class const&, dart::UnresolvedClass const&)
  [0x00000000006a19a4] dart::ClassFinalizer::ResolveTypeClass(dart::Class const&, dart::Type const&)
  [0x00000000006a1ef5] dart::ClassFinalizer::ResolveType(dart::Class const&, dart::AbstractType const&)
  [0x00000000006a0da4] dart::ClassFinalizer::FinalizeType(dart::Class const&, dart::AbstractType const&, dart::ClassFinalizer::FinalizationKind, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)
  [0x000000000094a466] dart::Parser::ParseTypeOrFunctionType(bool, dart::ClassFinalizer::FinalizationKind)
  [0x00000000009613b2] dart::Parser::ParseTypeArguments(dart::ClassFinalizer::FinalizationKind)
  [0x00000000009818ad] dart::Parser::ParseCompoundLiteral()
  [0x0000000000944547] dart::Parser::ParsePrimary()
  [0x000000000097a02c] dart::Parser::ParsePostfixExpr()
  [0x0000000000977852] dart::Parser::ParseUnaryExpr()
  [0x000000000094e43d] dart::Parser::ParseBinaryExpr(int)
  [0x0000000000950436] dart::Parser::ParseConditionalExpr()
  [0x0000000000945fe8] dart::Parser::ParseExpr(bool, bool)
  [0x000000000095189d] dart::Parser::ParseInitializedInstanceFields(dart::Class const&, dart::LocalVariable*, dart::GrowableArray<dart::Field*>*)
  [0x00000000009539a2] dart::Parser::ParseConstructor(dart::Function const&)
  [0x000000000093e224] dart::Parser::ParseFunc(dart::Function const&, bool)
  [0x000000000093c80c] dart::Parser::ParseFunction(dart::ParsedFunction*)
  [0x0000000000795a4d] Unknown symbol
  [0x000000000078a358] Unknown symbol
  [0x0000000000799405] Unknown symbol
  [0x0000000000792a3d] Unknown symbol
  [0x00000000007925db] dart::FlowGraphInliner::Inline()
  [0x00000000006fe313] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x0000000000700472] Unknown symbol
  [0x0000000000701439] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  [0x00000000007033ab] dart::BackgroundCompiler::Run()
-- End of DumpStackTrace


Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart --dfe=out/DebugX64/gen/kernel-service.dart.snapshot --no-enable-malloc-hooks --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/tests/co19/src/Language/Classes/Constructors/Generative_Constructors/initializers_t09.dart
Took 0:00:02.053081

Short reproduction command (experimental):
    python tools/test.py -cdartk -t120 --builder-tag no_ipv6 --vm-options --no-enable-malloc-hooks co19/Language/Classes/Constructors/Generative_Constructors/initializers_t09

```

**Comment by peter-ahe-google** [comment] 2017-04-04 12:45
Seen on [vm-kernel-linux-debug-x64-be build 1218](https://build.chromium.org/p/client.dart/builders/vm-kernel-linux-debug-x64-be/builds/1218/steps/vm%20tests/logs/stdio).

**Comment by peter-ahe-google** [comment] 2017-04-04 12:57
One theory is that this is a crash in the kernel-service isolate. That would make more sense.

**Comment by mkustermann** [comment] 2017-04-04 13:25
So far, I didn't manage to reproduce this issue locally. We didn't get a coredump, though [cl/467149](https://chromium-review.googlesource.com/c/467149/) enabled this now. If we see the issue again, we'll get a dump.

The issue seems to be happening in the kernel isolate (because the main isolate should not invoke `dart::Parser`, it's using fasta/dartk to compile the sources). From the kernel isolate, it seems that a spawned background compiler hits some issue.

**Comment by peter-ahe-google** [comment] 2017-04-04 13:26
We're using app-jit, right? So should this even be possible?

**Comment by mkustermann** [comment] 2017-04-04 13:56
"app-jit" is not a precompiler: If the training run of fasta did not execute some code (e.g. compile-time error code paths) then fasta will JIT new methods (which parses methods again and compiles them), the same happens on deoptimizations.

**Comment by mkustermann** [comment] 2017-10-11 08:07
@peter-ahe-google  Have we ever seen this problem re-appear?
 
I would tend to close this issue if not, since there have been so many changes in the kernel -> vm integration in the last half year: The underlying issue might long be gone and there is little I can do without a way of reproducing it.

**Closed** 2017-10-12 15:14 UTC
Labels: area-kernel, Resolution: cannot reproduce
