### ISSUE TITLE
Use $XDG_CONFIG_HOME for configuration, not $HOME/.dart

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#42557] opened 2020-07-02 09:30 UTC
I just noticed `$HOME/.dart/`. I think it might be better to use [`$XDG_CONFIG_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), which defaults to `$HOME/.config/`, instead of using `$HOME`.

In this case we would create config files in:
 * `$XDG_CONFIG_HOME/dart/`,

And default `$XDG_CONFIG_HOME` to `$HOME/.config/` if it is not defined.
I suspect using `$APPDATA` instead of `$XDG_CONFIG_HOME` on Windows is fine.

I'm not sure what to do on Mac, maybe [stackoverflow](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x) has a suggestion.

Not polluting the `$HOME` folder is generally nice, afaik `~/.config/` is also used by Chrome, spotify, discord, gcloud and many other judging by my `~/.config/` folder.

CC @jwren

**Comment by julemand101** [comment] 2020-07-02 09:59
Looks related to:
https://github.com/dart-lang/sdk/issues/41560

**Comment by mraleph** [comment] 2020-07-02 10:14
Duplicate of #41560

**Closed by mraleph** 2020-07-02 10:14 UTC
Labels: area-dart-cli
