### ISSUE TITLE
Compiler crash while building for Web

### ISSUE THREAD

**Issue by SimonInman** [dart-lang/sdk#49641] opened 2022-08-11 09:29 UTC
I updated my (quite old) Flutter app to point at a different backend URL. When autodeploy was attempted on Netlify (the host), I got a compiler crash (output below):

> 0:20:06 AM: Please include the following information:
> 10:20:06 AM: * the name and version of your operating system,

I'm unsure as it's not my machine. It appears to be ubuntu, but not sure of version. 

> 10:20:06 AM: * the Dart SDK build number (2.19.0-81.0.dev), and
> 10:20:06 AM: * the entire message you see here (including the full stack trace
> 10:20:06 AM:   below as well as the source location above).

Full output:
```

10:19:55 AM: Setting "enable-web" value to "true".
10:19:55 AM: You may need to restart any open editors for them to read new settings.
10:19:57 AM: Downloading Material fonts...                                      774ms
10:19:57 AM: Downloading Gradle Wrapper...                                       30ms
10:19:57 AM: Downloading package sky_engine...                                  282ms
10:19:57 AM: Downloading flutter_patched_sdk tools...                           473ms
10:19:58 AM: Downloading flutter_patched_sdk_product tools...                   357ms
10:19:59 AM: Downloading linux-x64 tools...                                   1,006ms
10:20:00 AM: Downloading linux-x64/font-subset tools...                         109ms
10:20:01 AM: Downloading Web SDK...                                             953ms
10:20:02 AM: Downloading CanvasKit...                                           393ms
10:20:04 AM: Running "flutter pub get" in repo...                             1,624ms
10:20:04 AM: This app is using a deprecated version of the Android embedding.
10:20:04 AM: To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
10:20:04 AM: Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
10:20:04 AM: 💪 Building with sound null safety 💪
10:20:04 AM: Upgrading .gitignore
10:20:06 AM: Compiling lib/main.dart for the Web...
10:20:06 AM: Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/ui/geometry.dart:37:16:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   const Offset(super.dx, super.dy);
10:20:06 AM:                ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/ui/geometry.dart:37:26:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   const Offset(super.dx, super.dy);
10:20:06 AM:                          ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/ui/geometry.dart:91:14:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   const Size(super.width, super.height);
10:20:06 AM:              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/ui/geometry.dart:91:27:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   const Size(super.width, super.height);
10:20:06 AM:                           ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/ui/semantics.dart:300:14:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     required super.range,
10:20:06 AM:              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/ui/semantics.dart:316:14:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     required super.range,
10:20:06 AM:              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/canvaskit/canvas.dart:323:21:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   RecordingCkCanvas(super.skCanvas, ui.Rect bounds)
10:20:06 AM:                     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/canvaskit/path.dart:21:28:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   CkPath.fromSkPath(SkPath super.skPath, this._fillType) {
10:20:06 AM:                            ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/canvaskit/picture.dart:14:23:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   CkPicture(SkPicture super.picture, this.cullRect, this._snapshot) :
10:20:06 AM:                       ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/backdrop_filter.dart:11:52:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedBackdropFilter(PersistedBackdropFilter? super.oldLayer, this.filter);
10:20:06 AM:                                                    ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/clip.dart:71:40:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedClipRect(PersistedClipRect? super.oldLayer, this.rect, this.clipBehavior);
10:20:06 AM:                                        ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/clip.dart:186:50:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedPhysicalShape(PersistedPhysicalShape? super.oldLayer, this.path,
10:20:06 AM:                                                  ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/clip.dart:447:26:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:       PersistedClipPath? super.oldLayer, this.clipPath, this.clipBehavior);
10:20:06 AM:                          ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/color_filter.dart:11:46:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedColorFilter(PersistedColorFilter? super.oldLayer, this.filter);
10:20:06 AM:                                              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/image_filter.dart:11:46:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedImageFilter(PersistedImageFilter? super.oldLayer, this.filter);
10:20:06 AM:                                              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/offset.dart:11:36:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedOffset(PersistedOffset? super.oldLayer, this.dx, this.dy);
10:20:06 AM:                                    ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/opacity.dart:11:38:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedOpacity(PersistedOpacity? super.oldLayer, this.alpha, this.offset);
10:20:06 AM:                                      ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/path/path_metrics.dart:601:25:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   const _SurfaceTangent(super.position, super.vector, this.t);
10:20:06 AM:                         ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/path/path_metrics.dart:601:41:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   const _SurfaceTangent(super.position, super.vector, this.t);
10:20:06 AM:                                         ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/scene.dart:38:34:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedScene(PersistedScene? super.oldLayer) {
10:20:06 AM:                                  ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/shader_mask.dart:22:26:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     PersistedShaderMask? super.oldLayer,
10:20:06 AM:                          ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/html/transform.dart:12:42:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   PersistedTransform(PersistedTransform? super.oldLayer, this._matrixStorage);
10:20:06 AM:                                          ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:556:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.callback,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:557:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.glassPaneElement,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:558:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.pointerDataConverter
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:753:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.callback,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:754:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.glassPaneElement,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:755:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.pointerDataConverter
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:896:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.callback,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:897:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.glassPaneElement,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart:898:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.pointerDataConverter
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/semantics/text_field.dart:21:32:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   SemanticsTextEditingStrategy(super.owner);
10:20:06 AM:                                ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/services/buffers.dart:328:14:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   _IntBuffer(super.buffer);
10:20:06 AM:              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text/canvas_paragraph.dart:310:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.width,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text/canvas_paragraph.dart:311:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.height,
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text/canvas_paragraph.dart:312:5:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     super.alignment, {
10:20:06 AM:     ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text/canvas_paragraph.dart:313:14:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     required super.baselineOffset,
10:20:06 AM:              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text/canvas_paragraph.dart:314:14:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:     required super.baseline,
10:20:06 AM:              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:963:41:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   GloballyPositionedTextEditingStrategy(super.owner);
10:20:06 AM:                                         ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:1002:36:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   SafariDesktopTextEditingStrategy(super.owner);
10:20:06 AM:                                    ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:1407:26:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   IOSTextEditingStrategy(super.owner);
10:20:06 AM:                          ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:1604:30:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   AndroidTextEditingStrategy(super.owner);
10:20:06 AM:                              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/text_editing/text_editing.dart:1675:30:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:   FirefoxTextEditingStrategy(super.owner);
10:20:06 AM:                              ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/window.dart:351:7:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:       super.windowId, super.platformDispatcher);
10:20:06 AM:       ^^^^^
10:20:06 AM: flutter/bin/cache/flutter_web_sdk/lib/_engine/engine/window.dart:351:23:
10:20:06 AM: Error: The 'super-parameters' language feature is disabled for this library.
10:20:06 AM:       super.windowId, super.platformDispatcher);
10:20:06 AM:                       ^^^^^
10:20:06 AM: .dart_tool/flutter_build/c82948ed5ee71e1b5750ea9f08214b62/main.dart:
10:20:06 AM: Internal Error: The compiler crashed when compiling this element.
10:20:06 AM: The compiler is broken.
10:20:06 AM: When compiling the above element, the compiler crashed. It is not
10:20:06 AM: possible to tell if this is caused by a problem in your program or
10:20:06 AM: not. Regardless, the compiler should not crash.
10:20:06 AM: The Dart team would greatly appreciate if you would take a moment to
10:20:06 AM: report this problem at http://dartbug.com/new.
10:20:06 AM: Please include the following information:
10:20:06 AM: * the name and version of your operating system,
10:20:06 AM: * the Dart SDK build number (2.19.0-81.0.dev), and
10:20:06 AM: * the entire message you see here (including the full stack trace
10:20:06 AM:   below as well as the source location above).
10:20:06 AM: The compiler crashed: Crash when compiling null,
10:20:06 AM: at character offset null:
10:20:06 AM: Null check operator used on a null value
10:20:06 AM: #0      InferableTypeBuilderMixin.type (package:front_end/src/fasta/builder/type_builder.dart:392:29)
10:20:06 AM: #1      InferableTypeBuilder.inferType (package:front_end/src/fasta/builder/omitted_type_builder.dart:155:12)
10:20:06 AM: #2      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2358:19)
10:20:06 AM: #3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:532:14)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #4      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #5      _buildInternal (package:front_end/src/kernel_generator_impl.dart:139:7)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #7      compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:195:37)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #8      compile (package:front_end/src/api_unstable/dart2js.dart:193:36)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #9      _loadFromSource (package:compiler/src/phase/load_kernel.dart:292:29)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #10     run (package:compiler/src/phase/load_kernel.dart:393:36)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #11     Compiler.loadKernel (package:compiler/src/compiler.dart:392:9)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #12     Compiler.produceKernel (package:compiler/src/compiler.dart:399:35)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #13     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:663:33)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #14     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #15     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #16     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #17     main (package:compiler/src/dart2js.dart:1423:3)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #0      InferableTypeBuilderMixin.type (package:front_end/src/fasta/builder/type_builder.dart:392:29)
10:20:06 AM: #1      InferableTypeBuilder.inferType (package:front_end/src/fasta/builder/omitted_type_builder.dart:155:12)
10:20:06 AM: #2      SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2358:19)
10:20:06 AM: #3      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:532:14)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #4      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #5      _buildInternal (package:front_end/src/kernel_generator_impl.dart:139:7)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #7      compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:195:37)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #8      compile (package:front_end/src/api_unstable/dart2js.dart:193:36)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #9      _loadFromSource (package:compiler/src/phase/load_kernel.dart:292:29)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #10     run (package:compiler/src/phase/load_kernel.dart:393:36)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #11     Compiler.loadKernel (package:compiler/src/compiler.dart:392:9)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #12     Compiler.produceKernel (package:compiler/src/compiler.dart:399:35)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #13     Compiler.runSequentialPhases (package:compiler/src/compiler.dart:663:33)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #14     Compiler.runInternal.<anonymous closure> (package:compiler/src/compiler.dart:315:7)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #15     Compiler.runInternal (package:compiler/src/compiler.dart:314:5)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #16     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:235:11)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: #17     main (package:compiler/src/dart2js.dart:1423:3)
10:20:06 AM: <asynchronous suspension>
10:20:06 AM: Compiling lib/main.dart for the Web...                           1,847ms
10:20:06 AM: Exception: Failed to compile application for the Web.
10:20:06 AM: 
```

**Comment by SimonInman** [comment] 2022-08-11 11:36
Also if you have any ideas how to fix my actual issue

```
Error: The 'super-parameters' language feature is disabled for this library.
```

that would be greatly appreciated!

**Comment by srawlins** [comment] 2022-08-11 16:24
@SimonInman as for the super-parameter quertsion, debugging questions like this are better asked on a user forum like StackOverflow with lots of eyes.

I'll pass on the null-check exception to the front-end team.

**Comment by blaugold** [comment] 2022-09-13 14:59
For me, any import of a Flutter library (e.g. `package:flutter/widgets.dart`) into a library that is later compiled as part of a build_runner build script causes this error.

**Comment by mraleph** [comment] 2022-09-16 14:08
Similar crash reported when using grpc-dart library with a reproduction provided, see https://github.com/grpc/grpc-dart/issues/578

Could you investigate @chloestefantsova?

**Comment by mraleph** [comment] 2022-09-19 07:35
Bumping priority to P1 because more and more reports of this are coming in, see 

* https://github.com/flutter/flutter/issues/111833
* https://github.com/dart-lang/sdk/issues/47470#issuecomment-1250232084

**Comment by chloestefantsova** [comment] 2022-09-19 11:34
I can't reproduce it at the current top of `main`. It's likely fixed in https://github.com/dart-lang/sdk/commit/bbdb9e43608a33313ec4a057225204d2b69dabf5, and I'm working on verifying that.

**Comment by mraleph** [comment] 2022-09-20 11:57
@chloestefantsova @johnniwinther do we think this needs a CP request?

**Comment by johnniwinther** [comment] 2022-09-21 05:46
I think we need a CP request for this.

**Comment by mraleph** [comment] 2022-09-21 07:47
I am waiting for Chloe to confirm that CPing fixes the issue if it does I will file one.

**Comment by chloestefantsova** [comment] 2022-09-21 10:46
@johnniwinther @mraleph I can confirm that CPing that CL fixes this particular crash. I'm investigating the issue further though because the crash happens due to fragile handling of an erroneous case, and as far as I can tell that erroneous case should not exist.

**Comment by vsmenon** [comment] 2022-10-31 16:12
Is this fixed now?  CP landed.  Anything else to do?

**Closed** 2023-01-10 15:20 UTC
Labels: P1, area-front-end
