### ISSUE TITLE
Segfault (in MarkingVisitorBase<true>::VisitPointers?) in Flutter etst run on Chromium macOS

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#35388] opened 2018-12-12 11:54 UTC
In this run of Flutter tests:

https://build.chromium.org/p/client.flutter/builders/Mac/builds/7424

There was this crash:

```
00:18 +28 -1: test/run_test.dart: run.dart script exits with code 1 when task throws [E]                                                                                                               
  Expected: <1>
    Actual: <-6>
  [ stderr from test process ]
  
  [smoke_test_throws] [STDERR] Task failed: failed
  [smoke_test_throws] [STDERR] 
  [smoke_test_throws] [STDERR] Stack trace:
  [smoke_test_throws] [STDERR] bin/tasks/smoke_test_throws.dart 12:5  main.<fn>
  [smoke_test_throws] [STDERR] ===== asynchronous gap ===========================
  [smoke_test_throws] [STDERR] dart:async                             _AsyncAwaitCompleter.completeError
  [smoke_test_throws] [STDERR] bin/tasks/smoke_test_throws.dart       main.<fn>
  [smoke_test_throws] [STDERR] 
  
  ===== CRASH =====
  version=2.1.0-dev.9.4.flutter-f9ebf21297 (Thu Nov 8 23:00:07 2018 +0100) on "macos_x64"
  si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
  Dumping native stack trace for thread 1403
    [0x0000000104f9edcf] dart::MarkingVisitorBase<true>::VisitPointers(dart::RawObject**, dart::RawObject**)
    [0x0000000104f9edcf] dart::MarkingVisitorBase<true>::VisitPointers(dart::RawObject**, dart::RawObject**)
    [0x0000000104d909e5] dart::RawObject::VisitPointersPredefined(dart::ObjectPointerVisitor*, long)
    [0x0000000104f9eb38] dart::MarkingVisitorBase<true>::DrainMarkingStack()
    [0x0000000104f9f09d] dart::MarkTask::Run()
    [0x0000000104e2983d] dart::ThreadPool::Worker::Loop()
    [0x0000000104e29689] dart::ThreadPool::Worker::Main(unsigned long)
    [0x0000000104d799e9] dart::ThreadStart(void*)
    [0x00007fffe5cff93b] _pthread_body
    [0x00007fffe5cff887] _pthread_body
    [0x00007fffe5cff08d] thread_start
  -- End of DumpStackTrace
  
  
  [ end of stderr ]
  
  [ stdout from test process ]
```

There are a few other issues in the tracker with similar messages, though some of them closed over a month ago so I don't know if this is the same issue or another - feel free to close if it's likely a dupe of closed after `2.1.0-dev.9.4.flutter-f9ebf21297`.

**Comment by mraleph** [comment] 2018-12-12 12:07
Thanks for the report. We currently think that this was recently fixed by @rmacnak-google 

Duplicate of #34934

**Comment by mraleph** [comment] 2018-12-12 12:07
Duplicate of #34934

**Closed by mraleph** 2018-12-12 12:07 UTC
