### ISSUE TITLE
Converter needs type cast in strong mode

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#25497] opened 2016-01-15 12:49 UTC
I have this code:

![image](https://cloud.githubusercontent.com/assets/1035299/12353347/a45aed78-bb8e-11e5-9819-4eea09d6cb9c.png)

I don't understand why I need the typecast, as I think that Converter implements StreamTransformer.

This silences the error:

![image](https://cloud.githubusercontent.com/assets/1035299/12353359/c8eb8260-bb8e-11e5-8ad0-3d1664100149.png)

**Comment by lrhn** [comment] 2016-01-15 15:43
`SYSTEM_ENCODING` is typed as `SystemEncoding`, which extends `Encoding`, which extends `Codec<String, List<int>>` which has a getter `Converter<List<int>, String> get decoder`.
The only difference I can see is that you use `dynamic` as the output type of the decoder instead of `String`.

**Comment by jmesserly** [comment] 2016-01-15 17:44
> I don't know if it's the last lack of type parameters that confuses the analyzer in strong mode - it shouldn't be a problem in normal Dart.

Yup, that would be it. `StreamTransfomer<dynamic, dynamic>` to `StreamTransfomer<List<int>, dynamic>` is not a safe cast.

**Comment by munificent** [comment] 2016-02-18 22:51
Duplicate of #25698.

**Closed by munificent** 2016-02-18 22:51 UTC
Labels: analyzer-strong-mode, area-analyzer, Priority-Medium, Type-Defect
