### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by Skyost** [dart-lang/sdk#35912] opened 2019-02-11 18:46 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.1.0-dev.9.4`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: D:\Hugo\Projets\Flutter\alcoolum\lib\game\screen_loader.dart
type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration' in type cast
#0      ConstantVerifier.visitConstructorDeclaration (package:analyzer/src/dart/constant/constant_verifier.dart:109:46)
#1      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2932:15)
#2      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#3      MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7939:13)
#4      RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1024:10)
#5      MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7930:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#7      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2423:21)
#8      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:712:10)
#9      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
#10     LibraryAnalyzer._computeConstantErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:172:10)
#11     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:325:5)
#12     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#13     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#14     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:15)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:36)
#17     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#18     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#21     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1050:39)
<asynchronous suspension>
#24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#25     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#26     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#27     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#28     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#29     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#35     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#36     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#37     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#38     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#39     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\Hugo\AppData\Local\Temp\report.txt.

**Comment by stereotype441** [comment] 2019-02-12 18:18
Duplicate of #35857

**Closed by stereotype441** 2019-02-12 18:18 UTC
Labels: area-analyzer
