### ISSUE TITLE
bare instructions mode should not emit RawInstruction headers

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#38451] opened 2019-09-18 11:11 UTC
That should save 32-bytes per instruction object.

/cc @mkustermann

**Comment by mkustermann** [comment] 2019-09-18 11:19
Notice that we first need to move the `RawInstructions::unchecked_entrypoint_pc_offset_` out of the instructions object before we can do this.

**Comment by mraleph** [comment] 2019-10-24 10:53
@rmacnak-google Hi Ryan, we wanted to check if you have already started to look at this?

**Comment by rmacnak-google** [comment] 2019-10-24 21:56
I've have made this change in the past (b2f3e8efe1f32bacad99ddbedbc434a6102d8be2) and reverted it. We should not make this change. The savings in space are not worth the lost of information from Instructions not being part of the heap, which includes lost of heap verification and allocation stats.

**Comment by mkustermann** [comment] 2019-10-25 10:24
Right now we have the following overhead on armv8:

    * `RawObject::tags_` - 4 bytes
    * `RawObject::hash_` - 4 bytes
    * `RawInstructions::size_and_flags` - 4 bytes
    * `RawInstructions::unchecked_entrypoint_pc_offset_` - 4 bytes

Since those are actual heap objects, they are also subject to `kObjectAlignment = 2 * kWordSize = 16 bytes`. On average `8 bytes` might be wasted.

In AOT we don't necessarily need any of those (even the unchecked entry is not needed, it's already cached in the Code objects).

The potential savings in the AOT snapshot are therefore `24 bytes` per instruction object. The gallery seems to have around `18030` `Precompiled_*` symbols, which would make this `24 * 18030 = 422 kb`, representing `3.8%` of flutter_gallery_total_size (and `5.9%` of RX).

**Comment by mraleph** [comment] 2019-10-25 10:30
> The savings in space are not worth the lost of information from Instructions not being part of the heap.

I am not sure I understand this argument. Could you expand it? In AOT Instructions are anyway not a really part of the heap: they are immovable, immutable and for all intents and purposes immortal. So I am not sure things like allocation stats are meaningful for them. 

As @mkustermann expands it quite a significant saving in code size and it will only become more prominent as we squeeze more and more air from the snapshot.

**Comment by aartbik** [comment] 2019-11-08 18:24
@sstrickl per our compiler performance meeting, I believe you were volunteered for this :-)

**Comment by Hixie** [comment] 2019-11-20 00:06
Status update FYI - last week @sstrickl told me "I have two CLs that are either in review or soon to be: one that allows users to split out debugging information like that used for stack traces into a separate file when stripping it from the main output, similar to how obfuscation maps can be saved when obfuscating, and another CL that is a tool for reading in a stream of text (like adb logcat) and replacing stacktraces generated without the debugging information (so basically just PC offsets) with the more informative version by using that split-out debugging information (on the developer side of things, so that the target side can have just the stripped version)."

**Comment by sstrickl** [comment] 2019-11-20 08:50
Note: that was about #35851, not this one :)

**Comment by Hixie** [comment] 2019-12-04 00:07
Ah, my bad. What's the status on this one?

**Comment by mkustermann** [comment] 2019-12-04 08:51
The work has started with a prerequisite - the refactoring in [cl/125400](https://dart-review.googlesource.com/c/sdk/+/125400) - which is almost ready to land.

Once this has landed we can start removing the header of `RawInstructions`.

**Comment by Hixie** [comment] 2020-01-15 00:08
Hello, just checking in. What's the status of this bug?

**Comment by sstrickl** [comment] 2020-01-15 09:26
I've got a CL that's mostly ready for this, there's just some issues on ARM I'm chasing down (all other architectures, including ARM64, are working just fine). Hope to have it out for review in the next day or two.

**Comment by Hixie** [comment] 2020-01-29 00:24
Any luck? :-)

**Comment by sstrickl** [comment] 2020-01-29 14:40
I have a [CL](https://dart-review.googlesource.com/c/sdk/+/131067) that is ready to go, but has had some major work since the last review cycle and so I want to make sure that work is signed off on first, so hopefully will land in the next day or so. But we're looking at a ~3.5% drop on arm8 (~1.6% drop on arm7) once this lands.

**Comment by sstrickl** [comment] 2020-02-04 17:35
Reverted in bb24f98, going to look at what was uncovered tomorrow.

**Comment by sstrickl** [comment] 2020-02-07 09:09
Just as a quick update, the failures on the CI that caused me to revert this were actually spurious, but while preparing [the reland CL](https://dart-review.googlesource.com/c/sdk/+/134325), I noticed an issue (run failures) that's cropping up only on flutter-release on arm7. That is, on our internal benchmarking system, benchmarking runs were failing on arm7 in the release runtime mode, but not on arm8 or in the profile runtime mode.

Given that, I'm currently looking into what we do with Instructions that only happen in full-on Dart product mode and/or whether I can reproduce in any other modes for easier debugging.

**Comment by sstrickl** [comment] 2020-02-10 08:46
Problem found: the length of the instruction payloads were being incorrectly calculated when there were deduplicated instructions, which then impacted the reverse PC lookup cache which uses the payload start + size to determine the end of a payload.

Previously deduplication could only happen in product mode, despite the existence of a flag to turn it on, but fixed the code to use the flag in non-product mode (submitted as a separate CL) and then could recreate the issue in all modes and thus debug it more easily.

 Fix added to relanding CL, will submit after review.

**Closed** 2020-02-10 15:08 UTC
Labels: area-vm, type-performance
