### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by ztz0223** [dart-lang/sdk#34862] opened 2018-10-19 10:36 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\tianzuoz\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\tianzuoz\AndroidStudioProjects\myapp\lib\main.dart context: exception_20181019_175016_778
Exception: Element not found in summary: dart:core

**Comment by stereotype441** [comment] 2018-10-25 13:39
Duplicate of #34555

**Closed by stereotype441** 2018-10-25 13:39 UTC
Labels: area-analyzer
