### ISSUE TITLE
Incorrect code generated by shadowing a method parameter with a for-in loop.

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#30195] opened 2017-07-18 22:59 UTC
@vsmenon showed me an issue similar to #29733

A method parameter that is shadowed by a var in a for-in loop inside the function body does not get scoped correctly and there is a name collision when building with the dartdevc.

Repro example:
```dart
int foo(int bar) {
  var bars = [1,2,3];
  var sum = 0;
  for (var bar in bars) {
    sum += bar;
  }
  return sum;
}
```

Dartdevc produces:
```js
main.foo = function(bar) {
    let bars = JSArrayOfint().of([1, 2, 3]);
    let sum = 0;
    for (let bar of bars) {
      sum = sum + dart.notNull(bar);
    }
    return sum;
  };
```

Chrome doesn't complain about the shadowing at the moment but Safari does with the error:
`Cannot declare a let variable twice: 'bar'.`

**Comment by jmesserly** [comment] 2017-07-18 23:18
Hmm. FYI this may be a Safari bug in that case. I'll have to check what the ES spec says. I thought that `for of` should be introducing a new scope, thus no error. It may be that they haven't finished implementing something too. Do you know with what Safari version this was, and if it happens in other browsers?

**Comment by nshahan** [comment] 2017-07-18 23:30
Yes, could be a Safari issue. I am not sure with the ES spec either.

No errors in 
Chrome: 59.0.3071.115 (Official Build) (64-bit)
Firefox: 54.0.1 (64-bit)

Error in
Safari: 10.1.1 (12603.2.4)

**Comment by jmesserly** [comment] 2017-07-18 23:42
thanks! I just confirmed this reproduces in Safari but not in WebKit nightly (219478) so it looks like they fixed the bug. going to close this out as it's been fixed on the browser side.

**Closed by jmesserly** 2017-07-18 23:42 UTC
Labels: area-dev-compiler
