### ISSUE TITLE
Dart Analysis Server error.

### ISSUE THREAD

**Issue by kkdroidgit** [dart-lang/sdk#33250] opened 2018-05-27 08:32 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\karti\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-dev.16.0, server version 1.18.4, error: Analysis failed: H:\Flutter_Projects\flutter_intro\test\widget_test.dart context: exception_20180527_135552_672
NoSuchMethodError: Class 'DynamicElementImpl' has no instance getter 'supertype'.
Receiver: Instance of 'DynamicElementImpl'
Tried calling: supertype
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:478)
#2      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:450)
#3      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:496)
#4      InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205)
#5      InstanceMemberInferrer._computeFieldOverrideType (package:analyzer/src/task/strong_mode.dart:114)
#6      InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:403)
#7      InstanceMemberInferrer._inferClass.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:308)
#8      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:307)
#10     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:88)

**Comment by bwilkerson** [comment] 2018-05-27 15:19
Duplicate of #32037.

**Closed by bwilkerson** 2018-05-27 15:19 UTC
