### ISSUE TITLE
Segmentation fault in dart::bin::EventHandlerImplementation

### ISSUE THREAD

**Issue by ailabs-software** [dart-lang/sdk#52865] opened 2023-07-06 18:39 UTC
dart --version:
Dart SDK version: 3.0.1 (stable) (None) on "linux_x64"

The server is run with:
dart run server.dill

Occasionally (like once every day or once every 3 days), our server is crashing with a stack trace:

2023-07-06 11:25:48.457545 ===== CRASH =====
2023-07-06 11:25:48.457545 si_signo=Segmentation fault(11), si_code=1, si_addr=0x8
2023-07-06 11:25:48.457728 version=3.0.1 (stable) (None) on "linux_x64"
2023-07-06 11:25:48.457728 pid=4078394, thread=4078395, isolate_group=(nil)((nil)), isolate=(nil)((nil))
2023-07-06 11:25:48.457728 os=linux, arch=x64, comp=no, sim=no
2023-07-06 11:25:48.457728 isolate_instructions=0, vm_instructions=560a237c1420
2023-07-06 11:25:48.457728 fp=7f116dfd9c10, sp=7f116dfd9940, pc=560a237acca4
2023-07-06 11:25:48.459176   pc 0x0000560a237acca4 fp 0x00007f116dfd9c10 dart::bin::EventHandlerImplementation::HandleInterruptFd()+0x414
2023-07-06 11:25:48.459424   pc 0x0000560a237ad06e fp 0x00007f116dfd9cc0 dart::bin::EventHandlerImplementation::HandleEvents(epoll_event*, int)+0x23e
2023-07-06 11:25:48.459583   pc 0x0000560a237ad10d fp 0x00007f116dfd9e30 dart::bin::EventHandlerImplementation::Poll(unsigned long)+0x8d
2023-07-06 11:25:48.460177   pc 0x0000560a238d0c22 fp 0x00007f116dfd9e70 dart+0x2220c22
2023-07-06 11:25:48.460177 -- End of DumpStackTrace

2023-07-05 12:11:57.804119 ===== CRASH =====
2023-07-05 12:11:57.804119 si_signo=Segmentation fault(11), si_code=1, si_addr=(nil)
2023-07-05 12:11:57.804119 version=3.0.1 (stable) (None) on "linux_x64"
2023-07-05 12:11:57.804119 pid=3863964, thread=3863965, isolate_group=(nil)((nil)), isolate=(nil)((nil))
2023-07-05 12:11:57.804119 os=linux, arch=x64, comp=no, sim=no
2023-07-05 12:11:57.804119 isolate_instructions=0, vm_instructions=55ad2d42b420
2023-07-05 12:11:57.804119 fp=7fbd9cc49c10, sp=7fbd9cc49938, pc=0
2023-07-05 12:11:57.804488   pc 0x0000000000000000 fp 0x00007fbd9cc49c10 Unknown symbol
2023-07-05 12:11:57.806039   pc 0x000055ad2d41706e fp 0x00007fbd9cc49cc0 dart::bin::EventHandlerImplementation::HandleEvents(epoll_event*, int)+0x23e
2023-07-05 12:11:57.806442   pc 0x000055ad2d41710d fp 0x00007fbd9cc49e30 dart::bin::EventHandlerImplementation::Poll(unsigned long)+0x8d
2023-07-05 12:11:57.807345   pc 0x000055ad2d53ac22 fp 0x00007fbd9cc49e70 dart+0x2220c22
2023-07-05 12:11:57.807345 -- End of DumpStackTrace

2023-07-02 16:41:59.133473 ===== CRASH =====
2023-07-02 16:41:59.133473 si_signo=Segmentation fault(11), si_code=1, si_addr=0xffffffffffffffff
2023-07-02 16:41:59.133473 version=3.0.1 (stable) (None) on "linux_x64"
2023-07-02 16:41:59.133473 pid=3108962, thread=3108981, isolate_group=main(0x55a329d10000), isolate=main(0x55a329d71800)
2023-07-02 16:41:59.133473 os=linux, arch=x64, comp=no, sim=no
2023-07-02 16:41:59.133473 isolate_instructions=55a327d6e420, vm_instructions=55a327d6e420
2023-07-02 16:41:59.133473 fp=7f3d65d7e550, sp=7f3d65d7e500, pc=55a327f215b0
2023-07-02 16:41:59.134421   pc 0x000055a327f215b0 fp 0x00007f3d65d7e550 dart::MessageDeserializer::Deserialize()+0x20
2023-07-02 16:41:59.134661   pc 0x000055a327f22358 fp 0x00007f3d65d7e6b0 dart::ReadMessage(dart::Thread*, dart::Message*)+0x118
2023-07-02 16:41:59.134873   pc 0x000055a327ef974d fp 0x00007f3d65d7ec40 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>)+0xad
2023-07-02 16:41:59.135121   pc 0x000055a327f1e487 fp 0x00007f3d65d7ecb0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x127
2023-07-02 16:41:59.135331   pc 0x000055a327f1eab4 fp 0x00007f3d65d7ed00 dart::MessageHandler::TaskCallback()+0x1e4
2023-07-02 16:41:59.135591   pc 0x000055a32802c03b fp 0x00007f3d65d7ed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14b
2023-07-02 16:41:59.135854   pc 0x000055a32802c488 fp 0x00007f3d65d7edb0 dart::ThreadPool::Worker::Main(unsigned long)+0x78
2023-07-02 16:41:59.136356   pc 0x000055a327faf936 fp 0x00007f3d65d7ee70 dart+0x2352936
2023-07-02 16:41:59.136356 -- End of DumpStackTrace

**Comment by bpilot** [comment] 2023-07-06 18:58
A possibility I am wondering is whether the application is running out of file descriptors, and somehow this is the result.

This has been happening (Too many file open error is usually the result, though).

ulimit -n reports:
1024

**Comment by a-siva** [comment] 2023-07-06 20:20
@bpilot is it possible to provide us some reproduction instructions for this crash, also is this a regression you are seeing in Dart 3.0.1 ?

**Comment by bpilot** [comment] 2023-07-06 20:42
Thanks for taking a look at this bug report.

This particular application has never run on anything other than Dart 3.0.1, so I am not sure it's a regression or not.

I have not been able to reproduce this error outside of production.

Do you have any suggestions of what I can do to narrow this down or get more insight into what's going on?

**Comment by mraleph** [comment] 2023-07-07 07:33
@bpilot you could try enabling core dumps on your system (e.g. by doing `ulimit -c unlimited` in the shell session where you run the server and making sure that `/proc/sys/kernel/core_pattern` to something useful, e.g. you can do `echo "core.%p" | sudo tee /proc/sys/kernel/core_pattern`). Then you start the server and wait for it to crash - this should yield `core.$pid` file in the working directory where you launched the server.

Once the server crashes you can inspect the dump (do *not* upload it anywhere! it will contains all the memory of your crashed application - so it might contains sensitive data). We can start by doing: 

```
$ gdb `which dart` core.$pid
...
(gdb) thread apply all bt
```

Then you can go to the frame that crashed (e.g. `HandleInterruptFd`) and do `disassemble` there.

**Comment by bpilot** [comment] 2023-07-09 18:39
After a few days, I'm pretty certain this is happening because unlimit -n is being exceeded & the segfault a symptom of that.

Determining why open file descriptors are accumulating is now my main focus as this affects the application's stability in production.

Once I have a handle on that, I will look at trying to reproduce this with an artificially low ulimit -n setting on linux_x64 (didn't reproduce on my local macos_arm64 machine, btw).

**Comment by mraleph** [comment] 2023-07-10 07:18
@bpilot FWIW Mac and Linux have completely different IO event loop implementations (we use `kqueue` on Mac, but `epoll` on Linux) so it is not surprising it does not reproduce on Mac.

**Comment by bpilot** [comment] 2023-07-10 21:49
That could explain why I couldn't reproduce the seg fault on my Mac.

I have now found the source of the file descriptor leak, so reproducing the seg fault now should be as simple as opening connections until ulimit -n is exceeded.

**Comment by bpilot** [comment] 2023-07-10 23:38
I have determined that this seg fault is the result of the program leaking file descriptors (which has been fixed, fortunately).

There is a bug in the source I've provided here intentionally to replicate what triggers the seg fault. Because the root problem is an error in application code (not closing a connection -- found thanks to julemand101), perhaps this isn't a very high priority bug. Still, I think it'd be nice if it crashed a little more cleanly. 

Okay, here's how to reproduce this seg fault (this can be simplified most probably, but this is what I have now):

This was run on Linux x64:
dart --version
Dart SDK version: 3.0.1 (stable) (None) on "linux_x64"

Create this file as repro.dart:
`import "package:http/http.dart" as http;

Future<void> main() async
{
  for (int i = 0; i < 100; i++)
  {
    Uri uri = Uri.parse("https://www.google.com/");
    http.MultipartRequest request = new http.MultipartRequest("POST", uri);
    request.persistentConnection = false;
    http.StreamedResponse response = await request.send();
    print(response);
  }
}`

ulimit -n 10 # This is necessary so it runs into the limit here.

dart run repro.dart

Usually results in this output, but not always:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10000
version=3.0.1 (stable) (None) on "linux_x64"
pid=926949, thread=926950, isolate_group=(nil)((nil)), isolate=(nil)((nil))
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=0, vm_instructions=55cc63561420
fp=7f24d2d8fc10, sp=7f24d2d8f938, pc=10000
  pc 0x0000000000010000 fp 0x00007f24d2d8fc10 Unknown symbol
  pc 0x000055cc6354d06e fp 0x00007f24d2d8fcc0 dart::bin::EventHandlerImplementation::HandleEvents(epoll_event*, int)+0x23e
  pc 0x000055cc6354d10d fp 0x00007f24d2d8fe30 dart::bin::EventHandlerImplementation::Poll(unsigned long)+0x8d
  pc 0x000055cc63670c22 fp 0x00007f24d2d8fe70 dart+0x2220c22
-- End of DumpStackTrace
Aborted

Sometimes, it will print out "../../runtime/vm/zone.cc: 96: error: Out of memory..." out of memory instead.

Thank you for all the help. :-)

**Comment by a-siva** [comment] 2023-11-10 22:29
I tried the above test on the latest version of Dart with the file descriptor limit set to 12 (setting it to 10 causes VM initialization to file as  memfd_create to fail) and it fails correctly with the following exception
```
Unhandled exception:
ClientException with SocketException: Failed host lookup: 'lorde.co.nz' (OS Error: System error, errno = -11), uri=https://lorde.co.nz/
#0      IOClient.send (package:http/src/io_client.dart:119:7)
<asynchronous suspension>
#1      BaseRequest.send (package:http/src/base_request.dart:133:22)
<asynchronous suspension>
#2      main (file:///usr/local/google/home/asiva/tmp/regression/issue52865.dart:10:38)
<asynchronous suspension>

```

Closing issue.

**Closed by a-siva** 2023-11-10 22:29 UTC
Labels: area-vm, type-bug, crash
