### ISSUE TITLE
The app's image icon will turn into a black block

### ISSUE THREAD

**Issue by ignoracenfly** [dart-lang/sdk#35821] opened 2019-01-31 07:47 UTC
Latest dart version
The app's image icon will turn into a black block.
1. Run your app
2. Switch the app to the background
3. Enter the app again

![_20190131154554](https://user-images.githubusercontent.com/1384626/52039450-808f8e00-256f-11e9-87c4-8630ce07960c.jpg)

**Comment by zoechi** [comment] 2019-01-31 09:43
This is a duplicate of https://github.com/flutter/flutter/issues/27109
and fixed in `master` channel (not sure it's in `dev` channel already)

**Closed** 2019-01-31 13:52 UTC
