### ISSUE TITLE
Dart analysis server errir

### ISSUE THREAD

**Issue by GroovinChip** [dart-lang/sdk#35117] opened 2018-11-09 14:49 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\groov\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\groov\Flutter_Projects\modal_drawer_handle\example\lib\main.dart context: exception_20181109_094943_798
Exception: Element not found in summary: package:flutter/src/material/colors.dart

**Comment by stereotype441** [comment] 2018-11-13 23:51
Duplicate of #34555

**Closed by stereotype441** 2018-11-13 23:51 UTC
Labels: analyzer-crash-report, analyzer-server, area-analyzer, crash
