### ISSUE TITLE
package:charcode null safety (package was downgraded from 2.10 to 2.9)

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#43004] opened 2020-08-10 14:16 UTC
I'm seeing NNBD errors on the CQ that do not show up on the CI.

There have not been any NNBD builds the two days on the CI, did we change something in the CI setup today?

```
/=====================================================================================================================================\
| dartk-strong-linux-release-x64:vm/dart/causal_stacks/sync_async_start_pkg_test_test broke (Pass -> CompileTimeError, expected Pass) |
\=====================================================================================================================================/

--- Command "vm" (took 03.000690s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --sound-null-safety --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/runtime/tests/vm/dart/causal_stacks/sync_async_start_pkg_test_test.dart

exit code:
254

stderr:
Error: Cannot run with sound null safety as one or more dependencies do not
support null safety:

 - package:charcode

Run 'pub outdated --mode=null-safety' to determine if versions of your
dependencies supporting null safety are available.

--- Re-run this test:
python tools/test.py -n dartk-strong-linux-release-x64 vm/dart/causal_stacks/sync_async_start_pkg_test_test
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8872348795932024560/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by dcharkes** [comment] 2020-08-10 14:18
Oh, there was a commit which caused this, but it was not flagged as impacting the VM: https://dart-review.googlesource.com/c/sdk/+/156908/5/.dart_tool/package_config.json

**Comment by sortie** [comment] 2020-08-10 14:31
@athomas Sounds like this confusion was caused by .dart_tool/package_config.json not triggering the VM builders.

**Comment by athomas** [comment] 2020-08-11 06:59
@dcharkes The infra aspect of this is fixed by https://dart-review.googlesource.com/c/sdk/+/158004.

Can this be closed or does this issue also track a fix for the downgrade which isn't an infra issue?

**Comment by dcharkes** [comment] 2020-08-11 07:04
Thanks. No, please keep it open, I approved the failures caused by this, and those should be addressed.

@johnniwinther was there a reason for downgrading the `package:charcode`?

**Comment by johnniwinther** [comment] 2020-08-11 07:07
@whesse @athomas `.dart_tool/package_config.json` was generate by `tools/generate_package_config.dart` which pulls the language version from the `pubspec.yaml` in the `third_party/pkg/charcode` folder. This has an sdk version of `2.9` and not `2.10`. Do we have the wrong version of `package:charcode` in `third_party`?

**Comment by whesse** [comment] 2020-08-11 08:36
Yes, we do have the wrong version.  We needed to increase the language version of some packages to 2.10 in order to create a 2.10 SDK, before we had published versions of those packages with a minimum SDK constraint of 2.10.  We have since published new versions of these packages, but apparently did not update charcode.

**Comment by whesse** [comment] 2020-08-11 09:12
Fixed by https://dart-review.googlesource.com/c/sdk/+/158008

**Closed by whesse** 2020-08-11 09:12 UTC
Labels: area-infrastructure
