### ISSUE TITLE
VM coverage is unreliable

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#43405] opened 2020-09-14 08:38 UTC
I have the following test program:
```
main(List<String> args) {
  int count = 10000;
  for(int i = 0; i < count; i++) {
    print("Hello $i");
    if (i > 10000000) {
      foo();
    }
  }
  print("Hello $count!");
}

foo() {
  print("hello from foo!");
}
```

If I run this like `out/ReleaseX64/dart --observe=0 t.dart` and go to observatory I can see which lines have executed. Most often it claims that the line `print("Hello $count!");` has not executed (but it has --- I am looking at the line it printed in the terminal!).

If I run it through this helper program so I can try more times faster:
```
import 'dart:convert';
import 'dart:io';

import 'package:coverage/coverage.dart' as coverage;

main(List<String> args) async {
  List<String> allArgs = ["--observe=0"];
  allArgs.addAll(args);
  Uri uri;
  bool probablyDone = false;
  Process.start(Platform.resolvedExecutable, allArgs).then((Process process) {
    process.stdout
        .transform(utf8.decoder)
        .transform(new LineSplitter())
        .listen((line) {
      const kObservatoryListening = 'Observatory listening on ';
      if (line.startsWith(kObservatoryListening)) {
        uri = Uri.parse(line.substring(kObservatoryListening.length));
        if (probablyDone) {
          collectStuff(uri);
        }
      } else {
        stdout.writeln("> $line");
      }
    });
    process.stderr
        .transform(utf8.decoder)
        .transform(new LineSplitter())
        .listen((line) {
      if (line.startsWith("vm-service: ")) {
        if (uri != null)
          collectStuff(uri);
        else
          probablyDone = true;
      } else {
        stderr.writeln(line);
      }
    });
    process.exitCode.then((i) => exitCode = i);
  });
}

void collectStuff(Uri uri) async {
  print("------------------");
  print("Starting to collect stuff");
  Stopwatch stopwatch = new Stopwatch()..start();
  Map<String, dynamic> data = await coverage.collect(uri, true, false, false, null);
  for(MapEntry<String, dynamic> entry in data.entries) {
    if (entry.key == "coverage") {
      List value = entry.value;
      for(Map listEntry in value) {
        String source = listEntry["source"];
        if (source.startsWith("file:")) {
          print("$source:");
          print(listEntry["hits"]);
        }
      }
    }
  }
  print("Collected and created hit map in "
      "${stopwatch.elapsedMilliseconds} ms.");
  print("------------------");
}
```

(and have modified the coverage package slightly to print out the raw hits and misses) I mostly get a result like this:
```
hitt: 0 -> line 1
hitt: 66 -> line 3
hitt: 76 -> line 3
hitt: 86 -> line 4
hitt: 102 -> line 4
hitt: 115 -> line 5
miss: 135 -> line 6
miss: 154 -> line 9
miss: 175 -> line 9
miss: 181 -> line 12
miss: 191 -> line 13
t.dart:
[1, 1, 3, 2, 4, 2, 5, 1, 6, 0, 9, 0, 12, 0, 13, 0]
```

but sometimes get a (correct) result like this:
```
hitt: 0 -> line 1
hitt: 66 -> line 3
hitt: 76 -> line 3
hitt: 86 -> line 4
hitt: 102 -> line 4
hitt: 115 -> line 5
hitt: 154 -> line 9
hitt: 175 -> line 9
miss: 135 -> line 6
miss: 181 -> line 12
miss: 191 -> line 13
t.dart:
[1, 1, 3, 2, 4, 2, 5, 1, 9, 2, 6, 0, 12, 0, 13, 0]
```

Trying to run it 10 times I get 8 wrong runs and 2 good runs.

In https://github.com/dart-lang/sdk/issues/42061 I can read that I should use `--optimization_counter_threshold=-1` to get accurate coverage data --- but that makes it much worse: Now it claims that only line 5 (tokenpos 115) has executed and the rest are misses:

```
hitt: 115 -> line 5
miss: 0 -> line 1
miss: 66 -> line 3
miss: 76 -> line 3
miss: 86 -> line 4
miss: 102 -> line 4
miss: 135 -> line 6
miss: 154 -> line 9
miss: 175 -> line 9
miss: 181 -> line 12
miss: 191 -> line 13
t.dart:
[5, 1, 1, 0, 3, 0, 4, 0, 6, 0, 9, 0, 12, 0, 13, 0]
```

/cc @mraleph @rmacnak-google

**Comment by rmacnak-google** [comment] 2023-01-18 21:01
Duplicate of https://github.com/dart-lang/sdk/issues/42061

**Closed by rmacnak-google** 2023-01-18 21:01 UTC
Labels: area-vm
