### ISSUE TITLE
IntelliJ Feedback

### ISSUE THREAD

**Issue by andesappal** [dart-lang/sdk#39329] opened 2019-11-11 15:26 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.7142.35`
- `2.6.0-dev.0.0`
- `WS-192.7142.35, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 1280x800`

## Exception
```
Dart analysis server, SDK version 2.6.0-dev.0.0, server version 1.27.3, error: Analysis failed: /Users/johnappleseed/WebstormProjects/universal_html/test/reflection_test.dart context: exception_20191111_122620_434
Bad state: The type parameter K (in dart:core;dart:core/map.dart;Map;K) is out of scope.
#0      _createLinkedType (package:analyzer/src/summary/link.dart:217:7)
#1      _storeTypeArguments (package:analyzer/src/summary/link.dart:408:31)
#2      _createLinkedType (package:analyzer/src/summary/link.dart:199:5)
#3      CompilationUnitElementInBuildUnit._storeLinkedType (package:analyzer/src/summary/link.dart:1687:31)
#4      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5327:25)
#5      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1646:16)
#6      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3986:12)
#7      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3686:15)
#8      LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3626:7)
#9      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2231:13)
#10     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2250:18)
#11     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3659:42)
#12     Linker.link (package:analyzer/src/summary/link.dart:4191:35)
#13     _relink (package:analyzer/src/summary/link.dart:313:74)
#14     link (package:analyzer/src/summary/link.dart:127:3)
#15     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#17     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#18     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1454:23)
#19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1246:30)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#24     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#25     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#26     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#27     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#28     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:576:21)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:693:12)
#34     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:574:7)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:475:9)
#36     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#37     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:470:43)
#38     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#39     new Future.sync (dart:async/future.dart:224:31)
#40     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#46     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#47     Driver.start (package:analysis_server/src/server/driver.dart:470:21)
#48     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#50     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/51/h377tw1x4plf6mxbd6pn_1yr0000gn/T/report.txt.

**Comment by keertip** [comment] 2019-11-11 17:25
Thanks for the report! This was previously reported in #36506, please follow along there.

**Comment by keertip** [comment] 2019-11-11 17:25
Duplicate of #36506

**Closed by keertip** 2019-11-11 17:25 UTC
Labels: analyzer-crash-report, area-analyzer
