### ISSUE TITLE
"Name non-constant identifiers using lowerCamelCase" lint has crazy location at end of file

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25876] opened 2016-02-26 23:35 UTC
```dart
void main() { }
x
```
=>
```
[lint] Name non-constant identifiers using lowerCamelCase. (test.dart, line 3, col 2)
```

There's no line 3 column 2.

(This causes problems in the flutter analyze command because it tries to look up the given location and crashes because the location is outside the file.)

**Comment by bwilkerson** [comment] 2016-03-01 17:28
I believe that most users want the maximum amount of information (not noise) available, and don't want things hidden (in other words, I agree with Ian). If we can recognize when a lint is noise because it's being caused by an earlier error, then it would make sense to suppress it.

In this particular case, I'm guessing that `x` on the second line is being parsed as a TypeName and that whatever node it has as a parent contains a synthetic identifier (which doesn't start with a lower case letter). We should definitely not produce the lint for synthetic identifiers, which might reduce the noise in this case.

It's interesting that Atom reports the line number as being `2` rather than `3`. We should check the command-line analyzer to see what it's behavior is. It's possible this was fixed but the fix hasn't rolled forward yet.

**Comment by pq** [comment] 2016-03-01 21:16
Verified that offsets are funky in bleeding edge:

![screen shot 2016-03-01 at 1 14 13 pm](https://cloud.githubusercontent.com/assets/67586/13442124/954e763e-dfaf-11e5-9b00-c52128842cbc.png)

**Comment by pq** [comment] 2016-03-01 21:27
Looking closer I'm pretty sure that this will not bite us if we aren't reporting lints on synthetic nodes.  

![screen shot 2016-03-01 at 1 24 43 pm](https://cloud.githubusercontent.com/assets/67586/13442433/04630548-dfb1-11e5-8246-848d015c9944.png)

The synthetic node that we're actually reporting on is the synthesized simple identifier that should come after `XXX`.  It's reasonable to speculate that its offset will come after XXX. Unless of course, we've reached the end of the file...

The fix for reporting on synthetic nodes is up for review (https://codereview.chromium.org/1754813003/).

**Comment by pq** [comment] 2016-03-03 21:53
Fix landed in https://github.com/dart-lang/linter/commit/f90572f9be203a0ec9744aa3fb3b9509e3ca143d.  Should be resolved in next stable.

**Closed by pq** 2016-03-03 21:53 UTC
Labels: analyzer-linter, area-analyzer, P2 medium, Type: bug
