### ISSUE TITLE
dart:io - is there a support for memory-mapped files?

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#35070] opened 2018-11-06 16:16 UTC
Is there any plan to support memory-mapped files in dart:io? It would be nice for server apps that want to keep an index on disk but still access it efficiently.

**Comment by kevmoo** [comment] 2018-11-06 16:35
@a-siva ?

**Comment by a-siva** [comment] 2018-11-06 16:55
At this point we don't have any plans for supporting memory-mapped files in dart:io, we can consider adding it at sometime depending on use case and requirements.

**Comment by jwinarske** [comment] 2022-11-27 17:33
@a-siva This would be useful when dealing with Isolate/FFI and zero copy.  I could use this right now.

**Comment by mraleph** [comment] 2022-11-28 14:01
Duplicate of https://github.com/dart-lang/sdk/issues/35070

**Closed by mraleph** 2022-11-28 14:01 UTC
Labels: area-vm, type-enhancement

**Comment by mraleph** [comment] 2022-11-28 14:03
Duplicate of https://github.com/dart-lang/sdk/issues/49810

**Comment by jwinarske** [comment] 2022-11-29 15:28
@mraleph the example references:
```
Regenerate by running dart mmap.dart gen
```
Where do I find mmap.dart?

**Comment by mraleph** [comment] 2022-11-30 13:47
@jwinarske you can find this code here: https://gist.github.com/mraleph/d8ffb32cd419e08e15b8fc245dbbeff7#file-test-dart-L214

**Comment by jwinarske** [comment] 2022-11-30 14:32
@mraleph Thank you!

**Comment by renatoathaydes** [comment] 2024-08-15 20:01
The link that was supposed to show an example of using FFI for mmap unfortunately linked to the main branch which currently uses the `mmap` package instead of FFI.
The mmap package does use FFI and only works on Unix: https://github.com/farshed/mmap/blob/main/lib/src/unix.dart

**Comment by mraleph** [comment] 2024-08-16 08:14
@renatoathaydes `mmap` package is here (and it is not published): https://github.com/dart-lang/sdk/tree/main/pkg/mmap, and yes it currently only supports Linux, though it would be fairly trivial to update it to support Windows and Mac.
