### ISSUE TITLE
Dart analysis server: RangeError: Value not in range: 1

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/sdk#36527] opened 2019-04-08 20:05 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6183.87`
- `2.2.0`
- `IC-191.6183.87, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-141-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:390:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:234:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4797:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4722:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#9      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3679:13)
#10     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5191:16)
#11     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5112:12)
#12     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3584:14)
#13     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#14     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#15     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3062:15)
#16     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:2932:15)
#17     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2737:15)
#18     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1761:13)
#19     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1721:14)
#20     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:573:14)
#21     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:465:14)
#22     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#23     ParserAdapter.parseCompilationUnit2 (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/analyzer/lib/src/generated/parser_fasta.dart:189:32)
#24     ParserAdapter.parseCompilationUnit (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/analyzer/lib/src/generated/parser_fasta.dart:184:12)
#25     _File._parse (package:analyzer/src/services/available_declarations.dart:1368:23)
#26     _File.refresh (package:analyzer/src/services/available_declarations.dart:998:30)
#27     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:618:12)
#28     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:483:7)
#29     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:171:13)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#42     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#43     main (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#45     main (file:///tmp/tmpyaVT9t/dart-2.2.0/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///tmp/report1.txt.

**Comment by srawlins** [comment] 2019-08-29 05:36
Duplicate of #37114

Thanks for reporting this issue! It looks like https://github.com/dart-lang/sdk/issues/37114 has more context, so please follow along there.

**Closed by srawlins** 2019-08-29 05:36 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
