### ISSUE TITLE
FileLock.exclusive lock mode doesn't prevent from truncating a file to zero length

### ISSUE THREAD

**Issue by alexgoussev** [dart-lang/sdk#41011] opened 2020-03-12 09:17 UTC
Open a file with [openSync](https://api.dart.dev/stable/dart-io/File/openSync.html) method in any of modes: FileMode.read, FileMode.write, FileMode.writeOnly or FileMode.writeOnlyAppend. Then lock it with [lockSync](https://api.dart.dev/stable/dart-io/RandomAccessFile/lockSync.html) using FileLock.exclusive mode, write something to it and then open it again somewhere in a code in FileMode.write or FileMode.writeOnly mode. You'll get zero length file.
Please use this code to reproduce the problem:
```
import 'dart:io';
void main() {
  String fpath = 'testfile.txt';

  File file1 = File(fpath);
  file1.createSync();

  RandomAccessFile raf1 = file1.openSync(mode: FileMode.write);
  raf1.lockSync(FileLock.exclusive);
  raf1.writeFromSync([1, 2, 3]);
  raf1.flushSync();
  raf1.setPositionSync(0);
  print(raf1.readSync(3));

  File file2 = File(fpath);
  RandomAccessFile raf2 = file2.openSync(mode: FileMode.write);
  raf1.unlockSync();
  print(raf2.readSync(3));

  raf1.closeSync();
  raf2.closeSync();
}
```

I suppose such behaviour is wrong. An exclusive lock should not allow to remove whole content of a file and truncate its length to zero.

_Windows 7 x64, Dart SDK 2.8.0-dev.13.0_

**Comment by sortie** [comment] 2020-03-13 19:41
Thank you for filing this issue. Allow me explain what I believe is happening:

`RandomAccessFile.lockSync()` locks are advisory and not mandatory. Advisory locks means all code accessing the file must voluntarily cooperate. However, the `File.openSync(mode: FileMode.write)` call will open the file and truncate it, without any locking (since it's unaware of locking and it is not a mandatory lock). There does not appear to be a way to open a RandomAccessFile for both reading and writing without truncating it (unless in append mode), although the documentation does not make that clear. Dart does offer not mandatory locks, and they're not portable even if it did.

As far as I can tell, the file locking is working as intended due to the semantics of advisory file locking and the truncation behavior of `openSync` in the requested file mode. I'm closing this issue for that reason since the behavior is what is intended. I've made a note to look into the design of `File.open` as the design is overly restrictive.

**Closed by sortie** 2020-03-13 19:41 UTC
Labels: P2, area-library, library-io, type-bug

**Comment by alexgoussev** [comment] 2020-03-14 05:08
@sortie, 
may I add a note to lockSync() documentation using your explanation?

**Comment by sortie** [comment] 2020-03-16 10:36
That's up to you. This is an open source project, so feel free to contribute a documentation improvement, although it will likely take a few tries to get the description exactly correct. Otherwise I can add improving the documentation to my task list and get it done at some point in the future.
