### ISSUE TITLE
DartAPI_TypeGetParameterized fails due to inability to lookup core types

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#33042] opened 2018-05-03 20:51 UTC
```
FAILED: dartk-vm debug_x64 vm/cc/DartAPI_TypeGetParameterizedTypes
Expected: Pass
Actual: Crash

--- Command "run_vm_unittest" (took 01.000199s):
DART_CONFIGURATION=DebugX64 out/DebugX64/run_vm_tests --dfe=out/DebugX64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags --use-dart-frontend --strong DartAPI_TypeGetParameterizedTypes

exit code:
-6

stdout:
Running test: DartAPI_TypeGetParameterizedTypes

stderr:
../../runtime/vm/dart_api_impl_test.cc: 3627: error: expected 'int_type' to be a valid handle but found an error handle:
    'Type 'int' not found in library ''.'

../../runtime/vm/dart_api_impl_test.cc: 3629: error: expected 'double_type' to be a valid handle but found an error handle:
    'Type 'double' not found in library ''.'

../../runtime/vm/dart_api_impl_test.cc: 3631: error: expected 'list_type' to be a valid handle but found an error handle:
    'Type 'List' not found in library ''.'

../../runtime/vm/dart_api_impl_test.cc: 3633: error: expected 'Dart_ListSetAt(type_args, 0, int_type)' to be a valid handle but found an error handle:
    'Type 'int' not found in library ''.'

../../runtime/vm/dart_api_impl_test.cc: 3636: error: expected 'list_int_type' to be a valid handle but found an error handle:
    'Type 'List' not found in library ''.'

../../runtime/vm/dart_api_impl_test.cc: 3641: error: expected 'Dart_ListSetAt(type_args, 0, int_type)' to be a valid handle but found an error handle:
    'Type 'int' not found in library ''.'

../../runtime/vm/dart_api_impl_test.cc: 3642: error: expected 'Dart_ListSetAt(type_args, 1, double_type)' to be a valid handle but found an error handle:
    'Type 'double' not found in library ''.'

../../runtime/vm/object.cc: 16361: error: unreachable code
Dumping native stack trace for thread c32d
  [0x0000000002ccb3af] dart::Profiler::DumpStackTrace(void*)
  [0x0000000002ccb3af] dart::Profiler::DumpStackTrace(void*)
  [0x0000000002f5f852] dart::Assert::Fail(char const*, ...)
  [0x0000000002c1ee2c] Unknown symbol
  [0x0000000002adf823] dart::ClassFinalizer::ResolveType(dart::Class const&, dart::AbstractType const&)
  [0x0000000002adfa11] dart::ClassFinalizer::ResolveType(dart::Class const&, dart::AbstractType const&)
  [0x0000000002ade35c] dart::ClassFinalizer::FinalizeType(dart::Class const&, dart::AbstractType const&, dart::ClassFinalizer::FinalizationKind, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)
  [0x0000000002f4e590] Dart_GetType
  [0x0000000002725805] dart::Dart_TestDartAPI_TypeGetParameterizedTypes()
  [0x00000000026dc58c] dart::TestCase::Run()
  [0x00000000026dc63b] dart::TestCaseBase::RunTest()
  [0x0000000002852a37] dart::TestCaseBase::RunAll()
  [0x00000000026dc82c] Unknown symbol
  [0x00000000026dc6d9] main
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -m debug -c dartk -r vm --strong vm/cc/DartAPI_TypeGetParameterizedTypes
```

**Comment by peter-ahe-google** [comment] 2018-06-01 07:44
@bkonyi the frontend is supposed to implicitly import `dart:core` (if it isn't explicitly imported).

However, it is obvious that it isn't working correctly in your situation. Can you help guide me to how you invoke the frontend?

**Comment by peter-ahe-google** [comment] 2018-06-01 09:12
Never mind. @mkustermann helped me debug it, and it seems like he identified the root cause of the problem.

**Comment by mkustermann** [comment] 2018-06-04 11:01
This issue should be fixed now.

**Closed by mkustermann** 2018-06-04 11:01 UTC
Labels: area-vm
