### ISSUE TITLE
Debug isn't working (optimized out)

### ISSUE THREAD

**Issue by ozalisky** [dart-lang/sdk#53654] opened 2023-09-29 07:00 UTC
I will copy the description from the original issue https://github.com/Dart-Code/Dart-Code/issues/4555#issue-1717588919

**Describe the bug**
During debug, hovering a value doesn't show its value anymore.

**To Reproduce**

1. Run some code
2. Break in a breakpoint then hover some variable
3. Most of the times it happens inside of a builder

**Expected behavior**
To show the value of the variable.

![image](https://github.com/dart-lang/sdk/assets/40992789/06a827c1-f66f-460f-81fb-96fa3fbfe1eb)
![image](https://github.com/dart-lang/sdk/assets/40992789/b62109fb-67e5-486e-abbe-511d4473f27e)

**Please complete the following information:**

Operating System and version: MacOS 13.5.2
VS Code version: 1.82.2
Flutter 3.13.4 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (2 weeks ago) •
2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

It appeared in Dart 3.0.1, Flutter 3.10.1

**Comment by a-siva** [comment] 2023-09-29 16:35
//cc @derekxu16

**Comment by lirantzairi** [comment] 2023-10-02 19:50
Sample code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(
          builder: (context) {
            return Center(
              child: Text('Hello World!'),
            );
          },
        ),
      ),
    );
  }
}
```
Put a breakpoint in `return Center(` and try to watch or print the inner context

**Comment by bahadirarslan** [comment] 2023-10-02 21:43
> Sample code:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MainApp());
> }
> 
> class MainApp extends StatelessWidget {
>   const MainApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         body: Builder(
>           builder: (context) {
>             return Center(
>               child: Text('Hello World!'),
>             );
>           },
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Put a breakpoint in `return Center(` and try to watch or print the inner context

I can reproduce the bug with this code. Also, I noticed generally if there is a kind of loop, breakpoints in the loop cause this bug but if you add a breakpoint before loop operation problem doesn't occur.

**Comment by derekxu16** [comment] 2023-10-10 18:39
The problem is that my fix did not make it into the current stable Flutter release. The information above shows that Flutter 3.13.4 uses Dart 3.1.2. Dart 3.1.2's hash is https://github.com/dart-lang/sdk/commit/9bf2f88a8ba82fcfdc5960ac9c92e0e03fc0acef, and my change to `debugger.cc` (https://github.com/dart-lang/sdk/commit/f5080bedb38c77bd99b5caa0bc012007ab7158e3) does not appear when looking at the history of `debugger.cc` up to `9bf2f88` (https://github.com/dart-lang/sdk/commits/9bf2f88a8ba82fcfdc5960ac9c92e0e03fc0acef/runtime/vm/debugger.cc).

So, one solution is to use a newer release of Flutter that uses Dart 3.2.0. If this is not possible, please leave a 👍 on this comment to indicate that you would like us to cherry-pick the fix into a stable Flutter release.

**Comment by a-siva** [comment] 2023-10-12 22:18
We have a planned release of the next Flutter stable release (3.16) which has the above change on November 15th, but I figure folks would like to get a fix sooner?

**Comment by lirantzairi** [comment] 2023-10-13 07:03
> We have a planned release of the next Flutter stable release (3.16) which has the above change on November 15th, but I figure folks would like to get a fix sooner?

Preferably yes because we need to use `print()`s instead of proper variable inspection

**Comment by bahadirarslan** [comment] 2023-10-13 20:01
> We have a planned release of the next Flutter stable release (3.16) which has the above change on November 15th, but I figure folks would like to get a fix sooner?

This bug really slows down debugging and sometimes this may take days. No one wants to waste time so please make it available sooner.

**Comment by a-siva** [comment] 2023-10-13 20:15
A hot fix request has been filed here https://github.com/dart-lang/sdk/issues/53747 and can be used to track progress.

**Comment by ozalisky** [comment] 2023-10-24 18:04
So, I'm on latest stable flutter (3.13.8) and optimized out message is gone for me, but there is the new strange behavior for debug:

![image](https://github.com/dart-lang/sdk/assets/40992789/0ec10d95-48f3-4104-bd90-3cfd0a21bd41)


When trying to view the value of variable - IDE shows the type and location of class, not the value. The value is not available in the `Watch` section too. But it's possible to see the value in the `Variables` section through the `this._widget`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale uk-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] Network resources
```

**Comment by derekxu16** [comment] 2023-10-24 18:49
Can you please share a minimal reproducible example? I tried writing similar code to the one in your screenshot and wasn't able to reproduce the problem.

**Comment by a-siva** [comment] 2023-11-16 18:58
@ozalisky any updates on the reproduction example request from @derekxu16 above.
It would be ideal if we opened a new issue for the strange behavior under debug that you are seeing

**Comment by ozalisky** [comment] 2023-11-16 19:09
> @ozalisky any updates on the reproduction example request from @derekxu16 above.
> 
> It would be ideal if we opened a new issue for the strange behavior under debug that you are seeing

Sorry, was busy with work. You can close this issue and I will try to create reproducible example for it next week. Still seeing the problem almost every day 😞

**Comment by a-siva** [comment] 2023-11-16 21:34
Ok, will close this issue and wait for you to open a new one for the other issue.

**Closed by a-siva** 2023-11-16 21:34 UTC
Labels: area-vm, needs-info, vm-debugger, P2, cherry-pick-candidate, triaged
