### ISSUE TITLE
Installed Flutter and Dart, but now...why?

### ISSUE THREAD

**Issue by englekk** [dart-lang/sdk#36320] opened 2019-03-23 08:00 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `<NO SDK>`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3 unknown, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.5e9df35a5794413202fbcaf0c41f6d4c5d2e7b81, server version , FATAL error: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:707:14)
#2      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:694:26)
#3      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:716:33)
#4      Driver.start (package:analysis_server/src/server/driver.dart:362:28)
#5      main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/0x/b6hz29_x5_jd8lm8hqs4dq6c0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-06 16:03
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/33875; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 16:03
Duplicate of https://github.com/dart-lang/sdk/issues/33875

**Closed by srawlins** 2019-09-06 16:03 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
