### ISSUE TITLE
kernel/parser: portability issues with 64 bit ints

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#33160] opened 2018-05-17 18:44 UTC
The literal `0xffffffff00000000` has the value `-4294967296` on the 64-bit VM.
```dart
const int big = 0xffffffff00000000;
```
The kernel ast.IntLiteral has no indication that the value has been truncated to fit in 64-bits.

I believe on the web platform we need to either to reject the literal, or honor the original value.
If `0xffffffff00000000` is permitted, it should have the same value as `0xffffffff * 0x100000000`, i.e. `big > 0` should be `true`.

1. Depending on what is decided, either fasta could be configured to reject the literal, or, if the kernel IR is seen as platform agnostic, the kernel ast.IntLiteral needs to be augmented so that it can be handled downstream.

2. The fasta error message mentions '64-bits'. This does not fit the web platform.

**Error: The integer literal 0xffffffdff00000000 can't be represented in 64 bits.
Try using the BigInt class if you need an integer larger than 9,223,372,036,854,775,807 or less than -9,223,372,036,854,775,808.**

3. If we plan to have libraries that can be used on both web and Flutter, we should reject literals that are not portable. I believe this should be the default (i.e. opt-out, not opt-in).

4. Messages that are generated downstream should be able to include the literal text, like the error message quoted above.

@vsmenon

**Comment by anders-sandholm** [comment] 2018-05-22 13:21
For context, notes from the language meeting on Feb 6, 2018 say "64-bit int literals limited to 64-bit for now. May need escape clause for web."

**Comment by leafpetersen** [comment] 2018-05-24 23:02
Summarizing some discussion:

**Const evaluation**

I think there's broad agreement that any const evaluation has to be done using platform specific semantics.  Anything else is extremely confusing, since then `new Foo().x` and `const Foo().x` may have completely different integer values.

** Hexadecimal literals **

Hexadecimal literals represent unsigned 64 bit numbers.  The question at hand is what process to follow to get from the unsigned 64 bit value to the platform number that it denotes.  Options:
  1) unsigned int64 -> signed int64 -> platform int
  2) unsigned int64 -> platform int

The former is what is currently implemented.

Option 1 has the positive effect of making the interpretation of the same literal on different platforms be closer.  If the signed 64 bit integer representation can be represented exactly on all platforms, then all platforms will see the same result. 

```
void main() {
  const int small = 0xffffffff00000000;
  // True on all platforms under option 1
  assert(small == -4294967296);
}
```

On the other hand, option 1 has the unfortunate effect that the interpretation function for literals does not distribute over arithmetic: that is, on JS platforms, `interpretation(a) * interpretation(b) != interpretation(a*b)`.

```
void main() {
  const int small = 0xffffffff00000000;
  const int bigOrSmall = 0xffffffff000000 * 100;
  // Succeeds on the VM, fails on JS under option 1
  assert(small == bigOrSmall);
}
```

Option 2 has the inverse properties.  Interpretation of literals distributes over arithmetic (at least within the set of representable numbers), but literals have (more) different interpretations on the VM vs JS.

```
void main() {
  const int small = 0xffffffff00000000;
  // True on the VM, fails on JS under option 2
  assert(small == -4294967296);
}
```

```
void main() {
  const int small = 0xffffffff00000000;
  const int bigOrSmall = 0xffffffff000000 * 100;
  // True on all platforms under option 2
  assert(small == bigOrSmall);
}
```

On balance, I am inclined towards option 2, and would like to propose that we move forward with that.  @lrhn WDYT?

cc @vsmenon @rakudrama @munificent

**Comment by lrhn** [comment] 2018-05-25 22:13
The reason for allowing unsigned 64-bit integer hex-literals is to allow you to represent the individual bits, and nothing else.
If you don't actually preserve the individual bits, then the result will likely be wrong. But then again, any bit-wise operation over 32 bits is wrong in JS anyway, so if representing 64 bits is your goal, you should not compile to JavaScript at all.

So, I would pick option 1. It's less useful when compiling to JS, but you shouldn't be using it at all when compiling to JS. I don't want to make hexadecimal numbers *more useful* when compiling to JS.
If/when JS compilation switches to using JS `BigInt` to represent 64-bit integers, I don't want existing web code literals to change meaning.
So, if you want a number outside the signed 64-bit range, don't use a literal.

Compilation to JS should probably still warn if any literal is not representable as a double.

**Comment by leafpetersen** [comment] 2018-05-25 22:19
> So, I would pick option 1. It's less useful when compiling to JS, but you shouldn't be using it at all when compiling to JS.

This is an odd argument.  Option 1 and Option 2 are identical when not compiling to JS.  So if Option 1 is less useful when compiling to JS, why not use Option 2?

> If/when JS compilation switches to using JS BigInt to represent 64-bit integers, I don't want existing web code literals to change meaning.

They already will, regardless of what we decide here.

**Comment by lrhn** [comment] 2018-05-26 10:27
When I say "less useful" I mean that we don't introduce an unintended feature that people might use and that we might want to remove again at a later time. If hex-numbers are allowed to be unsigned and represent signed 64-bit numbers elsewhere, allowing them to represent (some) unsigned 64-bit numbers when compiling to the web will cause an extra incompatibility. 

If we move the web integers to actually be 64-bit at some point, then we will break that feature again.
I'd prefer not to introduce it to being with. Allowing one extra bit (on positive numbers only, and in magnitude only, not precision) isn't worth that.

**Comment by jmesserly** [comment] 2018-05-29 19:40
> Requires no further work from the analyzer (modulo existing bugs in platform correct constant evaluation)

I don't think DDC+Analyzer can reliably issue these errors, because of the existing bugs in constant evaluation (https://github.com/dart-lang/sdk/issues/32964). DDC+Kernel will be able to issue them reliably. (If it's high priority, we can fix #32964, but it involves copying Analyzer's constant eval code into DDC so we can fix it, that also gives us a place to issue these errors.)

**Comment by lrhn** [comment] 2018-05-29 20:45
I agree that if we aim for having each platform provide its own complete `int` implementation, then it's best if it's carried out throughout the entire system, including the parsing of literals. Until then, we should ensure that the integer literals we do allow will keep their meaning in the future, which means that large positive hexadecimal literals should stay positive when compiled to JS doubles, and not wrap to negative like they do for native int64s.

It will be consistent with the intended behavior of "integer literals in a double context" implicit conversion, where we allow any mathematical integer that can be exactly represented as a double. For compiling integers to JS, we would just use the same semantics in non-double contexts as well, so the work will need to be done anyway.

I think it's the best long-term plan, and short term strategy for being forwards compatible.

**Comment by vsmenon** [comment] 2018-05-29 23:01
@kmillikin - is it easy to just do this in CFE (when configured to do so)?
- Requires DDC and dart2js to warn if a literal is not exactly representable in JS

**Comment by leafpetersen** [comment] 2018-05-30 23:55
Ok, I think we have a resolution.  Closing this in favor of the tracking issue here: https://github.com/dart-lang/sdk/issues/33282 .

**Closed by leafpetersen** 2018-05-30 23:55 UTC
Labels: P1 high, area-language
