### ISSUE TITLE
VM crash running build_runner

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#35432] opened 2018-12-17 21:45 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)  
Dart version 2.2.0-edge.80412dcf6aa81968a4fcf8862c822a341d95488c
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A

This doesn't happen the first time I run after upgrading, but quite consistently happens after that.

Also happens on Travis builds.  https://travis-ci.org/dart-lang/build/jobs/468777197

```
pub run build_runner serve
[INFO] Generating build script completed, took 1.1s
[INFO] Setting up file watchers completed, took 63ms
[INFO] Waiting for all file watchers to be ready completed, took 833ms
[INFO] Reading cached asset graph completed, took 971ms
[INFO] Checking for updates since last build completed, took 1.5s
[INFO] Running build completed, took 781ms
[INFO] Caching finalized dependency graph completed, took 574ms
[INFO] Succeeded after 1.4s with 0 outputs (0 actions)
Serving `test` on http://localhost:8080
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 13ms
[INFO] Running build...../../runtime/vm/object.cc: 16432: error: unreachable code
thread=115902, isolate=build.dart.snapshot:main()(0x557ceff22900)
  [0x0000557ceccacfac] dart::Profiler::DumpStackTrace(void*)
  [0x0000557ceccacfac] dart::Profiler::DumpStackTrace(void*)
  [0x0000557cecf62f52] dart::Assert::Fail(char const*, ...)
  [0x0000557cecc5ce53] Unknown symbol
  [0x0000557cecbf3815] dart::TypeArguments::Canonicalize(dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*) const
  [0x0000557cecc5ffd5] dart::Type::Canonicalize(dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*) const
  [0x0000557cecdd7449] dart::AssertAssignableInstr::Canonicalize(dart::FlowGraph*)
  [0x0000557cecdb466b] dart::FlowGraph::Canonicalize()
  [0x0000557cece723f2] Unknown symbol
  [0x0000557cece71dcf] dart::CompilerPass::Run(dart::CompilerPassState*) const
  [0x0000557cece72040] dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  [0x0000557cecef15ed] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x0000557cecef27e3] Unknown symbol
  [0x0000557cecef3ab8] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  [0x0000557cecef5b86] dart::BackgroundCompiler::Run()
  [0x0000557cecd6d48c] dart::ThreadPool::Worker::Loop()
  [0x0000557cecd6cf6a] dart::ThreadPool::Worker::Main(unsigned long)
  [0x0000557cecca6c65] Unknown symbol
-- End of DumpStackTrace
```

**Comment by mraleph** [comment] 2018-12-17 23:05
This is caused by 5f36c5f9d82306e0f4d2b34430b0b3beca415911. We don't properly propagate instantiation error back to the optimizing compiler, instead we produce "broken" type that has `null` values inside. 

To reproduce:

```shell
$ git clone https://github.com/dart-lang/build.git
$ cd build/_test
$ pub get
$ pub run build_runner test --verbose --config=dart2js --output=dart2js_test -- -p chrome
```

**Comment by mraleph** [comment] 2018-12-17 23:05
Assigning to @crelier as the author of the original CL - I have also added a comment to the original CL that explains what is going wrong in more details.

**Comment by crelier** [comment] 2018-12-18 00:18
I have uploaded a [CL](https://dart-review.googlesource.com/c/sdk/+/87500) that should propagate the error, but I was not able to test it, as the build target create_sdk is currently broken.

**Comment by crelier** [comment] 2018-12-18 18:43
This is fixed by https://dart-review.googlesource.com/c/sdk/+/87500

**Closed by crelier** 2018-12-18 18:43 UTC
Labels: area-vm
