### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by cosminstoinescu** [dart-lang/sdk#35746] opened 2019-01-24 16:12 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Cosmin\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\WORKSPACE\MOBILE\flutter_app_test_release\lib\home_widget.dart
Exception: Element not found in summary: package:flutter_app_test_release/home_widget.dart

**Comment by kevmoo** [comment] 2019-01-24 18:20
@cosminstoinescu - Please include the details from `C:\Users\Cosmin\AppData\Local\Temp\report1.txt`

**Comment by cosminstoinescu** [comment] 2019-01-24 18:23
[report1.txt](https://github.com/dart-lang/sdk/files/2793001/report1.txt)

**Comment by stereotype441** [comment] 2019-01-25 20:41
Duplicate of #34555

**Closed by stereotype441** 2019-01-25 20:41 UTC
Labels: analyzer-server, area-analyzer
