### ISSUE TITLE
Failures on [cfe] Handle potentially constant type expression in is expression

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#41528] opened 2020-04-16 07:10 UTC
There are new test failures on [[cfe] Handle potentially constant type expression in is expression](https://dart-review.googlesource.com/c/sdk/+/142860).

The tests
```
dart2js_extra/interceptor_named_arguments_test RuntimeError (expected Pass)
dart2js_extra/js_interop_optional_arg_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2js-hostasserts-strong-linux-x64-chrome
dart2js-hostasserts-strong-linux-x64-d8
```

**Comment by fishythefish** [comment] 2020-04-16 09:52
Hmm, I can't reproduce these locally on master, so closing for now. It's possible they were also fixed by 1ac89cd5b3ed6dde5830fc3c3b8c14a07ee79916. We're just starting the burndown process for NNBD strong mode test regressions, so feel free to approve such failures for now and expect them to show up in our regression queries.

**Closed by fishythefish** 2020-04-16 09:52 UTC
Labels: area-web, web-dart2js
