### ISSUE TITLE
Document what's changed in dart:html/webgl/etc with 1.16

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#26045] opened 2016-03-18 21:36 UTC
There are a lot of changes due to changed IDL. We should produce at least some sort of listing for people. @kevmoo @jacob314 @terrylucas

**Comment by mit-mit** [comment] 2016-04-21 14:48
1.16 is about to ship, please get this quickly!

**Comment by kevmoo** [comment] 2016-04-21 22:53
Closed as dupe of https://github.com/dart-lang/sdk/issues/25970

**Closed by kevmoo** 2016-04-21 22:53 UTC
Labels: area-html, library-indexeddb, library-svg, library-webAudio, library-webgl, P1 high
