### ISSUE TITLE
Can no longer compile our app due to OOM compiler crash on Dart 2.5.x

### ISSUE THREAD

**Issue by olesiathoms-wk** [dart-lang/sdk#38797] opened 2019-10-09 18:11 UTC
### This tracker is for issues related to `dev_compiler`
- Dart SDK Version  - 2.5.2
- Using  MacOS Mojave version 10.14.4

#### How to recreate:
When running `pub global run webdev build --output web:build/web -- --delete-conflicting-outputs` build fails with error:
```[SEVERE]build_web_compilers:entrypoint on web/main.dart: Dart2Js finished with:

Exhausted heap space, trying to allocate 524320 bytes.
web/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.5.2), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Out of Memory
#0      _LinkedHashMapMixin._init (dart:collection-patch/compact_hash.dart)
#1      _LinkedHashMapMixin._rehash (dart:collection-patch/compact_hash.dart:183:7)
#2      _LinkedHashMapMixin._insert (dart:collection-patch/compact_hash.dart:227:7)
#3      _LinkedHashMapMixin.[]= (dart:collection-patch/compact_hash.dart:276:7)
#4      TypeInformation.addAssignment (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/type_graph_nodes.dart:287:18)
#5      InferrerEngineImpl.updateParameterAssignments.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:982:16)
#6      KernelTypeSystemStrategy.forEachParameter.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:1340:8)
#7      forEachOrderedParameterAsLocal.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/locals.dart:642:6)
#8      forEachOrderedParameter.handleParameter (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/element_map.dart:560:6)
#9      forEachOrderedParameterByFunctionNode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/element_map.dart:532:6)
#10     forEachOrderedParameter (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/element_map.dart:568:9)
#11     InferrerEngineImpl.updateParameterAssignments (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:558:32)
#12     DynamicCallSiteTypeInformation.computeType.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/type_graph_nodes.dart:1221:18)
#13     DynamicCallSiteTypeInformation.computeType (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/type_graph_nodes.dart:345:15)
#14     InferrerEngineImpl.refine (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:128:6)
#15     InferrerEngineImpl.runOverAllElements (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:624:5)
#16     TypeGraphInferrer.analyzeMain (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/type_graph_inferrer.dart:68:14)
#17     GlobalTypeInferenceTask.runGlobalTypeInference.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/types.dart:181:41)
#18     CompilerTask.measure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#19     GlobalTypeInferenceTask.runGlobalTypeInference (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/inferrer/types.dart:174:12)
#20     Compiler.performGlobalTypeInference (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:377:28)
#21     Compiler.compileFromKernel.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:420:13)
#22     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#23     Compiler.compileFromKernel (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:414:14)
#24     Compiler.runInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:255:13)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:814:22158)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:313:7343)
#29     KernelLoaderTask.load.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/kernel/loader.dart)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:814:22158)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:313:7343)
#34     compile (package:front_end/src/api_unstable/dart2js.dart)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:814:22158)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:313:7343)
#39     compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart)
#40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:814:10681)
...
...
#57     _FutureListener.handleValue (dart:async/future_impl.dart:814:10681)
#58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#59     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#60     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:313:7343)
#61     withCrashReporting (package:front_end/src/fasta/crash.dart)
#62     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart)
#63     _rootRunUnary (dart:async/zone.dart:1132:38)
#64     _FutureListener.handleValue (dart:async/future_impl.dart:814:10681)
#65     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#66     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#67     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:313:7343)
#68     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
#69     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart)
#70     _rootRunUnary (dart:async/zone.dart:1132:38)
#71     _FutureListener.handleValue (dart:async/future_impl.dart:814:10681)
#72     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#73     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#74     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:313:7343)
#75     Loader.buildBodies (package:front_end/src/fasta/loader.dart)
#76     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart)
#77     _rootRunUnary (dart:async/zone.dart:1132:38)
#78     _FutureListener.handleValue (dart:async/future_impl.dart:814:10681)
#79     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#80     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#81     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:313:7343)
#82     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart)
#83     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart)
#84     _rootRunUnary (dart:async/zone.dart:1132:38)
#85     _FutureListener.handleValue (dart:async/future_impl.dart:814:10681)
#86     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#87     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#88     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:522:5)
#89     _rootRun (dart:async/zone.dart:1124:13)
#90     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:19)
#91     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#92     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#93     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#94     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


[INFO] 17m 17s elapsed, 1706/1706 actions complete
[INFO] 17m 21s elapsed, 1706/1706 actions complete
[INFO] 17m 23s elapsed, 20342/20344 actions comple
[INFO] Running build completed, took 17m 24s
[INFO] 17m 26s elapsed, 24004/24004 actions comple
[INFO] Caching finalized dependency graph completed, took 2.5s
[SEVERE] Failed after 17m 27s
[SEVERE] FailureType: 1
```
DDC working correctly on `2.5.2`.
The same thing happening on `dart2.5.1`, while `2.4.0` works as expected.

I also tried using:
- `pub run build_runner build --release`
- `pub global run webdev build -- --delete-conflicting-outputs` 

In both ^^ cases build failing with the same error, but with smaller amount of memory:
`Exhausted heap space, trying to allocate 65552 bytes.`
Also tried to lower number of build workers to 1 and 2, but that didn't help either.

**Comment by dotdoom** [comment] 2019-10-12 16:06
I am having a similar issue with flutter / dart 2.6 since today -- building intl_translation and build_runner takes >4GB.  Tried using `PUB_MAX_WORKERS_PER_TASK=1` but it didn't change the fact that everything is being built in parallel (total 5 scripts).

**Comment by sigmundch** [comment] 2019-10-14 23:00
There is possibly a lot of overlap with the discussion in #27883. The phase where the crash occurs is a very expensive phase. We have plans to improve it, but it will take some time to get ther.

Meanwhile, I wonder if there are things we can do to reduce the heap pressure (e.g. due to other proceses running concurrently).

@jakemac53 - when using PUB_MAX_WORKERS... does that limit the number of concurrent jobs of different tasks too? Is there a way to limit that dart2js runs only when nothing else is running?

If there is no way to do that, is there a way to ask webdev to build the source-tree that will be the input to dart2js, but let developers invoke dart2js separately on the command line (basically leaving out dart2js from webdev entirely)?

**Comment by jakemac53** [comment] 2019-10-15 14:16
> @jakemac53 - when using PUB_MAX_WORKERS... does that limit the number of concurrent jobs of different tasks too? Is there a way to limit that dart2js runs only when nothing else is running?

That does limit all workers (ddk, kernel, dart2js). We don't have separate variables for each.

> If there is no way to do that, is there a way to ask webdev to build the source-tree that will be the input to dart2js, but let developers invoke dart2js separately on the command line (basically leaving out dart2js from webdev entirely)?

You would have to remove the `build_web_compilers` dependency, which means you won't get ddc builds either. If using build_runner directly you could use the `--build-filter` argument to do this for angular apps in a hacky way. Basically you could ask for the root `.template.dart` file which would for the rest of the app to also be built, but not build any js or anything else. Something like` --build-filter=web/main.template.dart`.

**Comment by olesiathoms-wk** [comment] 2019-10-15 16:17
>You would have to remove the build_web_compilers dependency, which means you won't get ddc builds either. If using build_runner directly you could use the --build-filter argument to do this for angular apps in a hacky way. Basically you could ask for the root .template.dart file which would for the rest of the app to also be built, but not build any js or anything else. Something like `pub run build_runner build --build-filter=web/main.template.dart`.

Unfortunately this is not an option for us since it's not an angular app.
I also tried setting `BUILD_MAX_WORKERS_PER_TASK=1` and that didn't work.

**Comment by travissanderson-wf** [comment] 2019-10-16 16:18
I have PUB_MAX_WORKERS_PER_TASK set to 1 and webdev serve still happily spins up 11 tasks and brings my laptop to its knees.  I am still on Dart 2.4.1 since regressions were introduced in Dart 2.5.x that are preventing us from upgrading.  Is it expected that PUB_MAX_WORKERS_PER_TASK would work on Dart 2.4.1?

**Comment by jakemac53** [comment] 2019-10-16 16:22
@travissanderson-wf you need to use `BUILD_MAX_WORKERS_PER_TASK` - the old environment variable was only for Dart 1 (pre-build_runner).

**Comment by travissanderson-wf** [comment] 2019-10-16 16:32
thanks Jake, that did the trick, not sure how we started passing around the old environment variable internally but I'll share that info with the rest of the team

**Comment by sigmundch** [comment] 2019-10-16 16:50
@travissanderson-wf did that make it possible to build the app? @olesiathoms-wk message above seems to indicate that `BUILD_MAX_WORKERS_PER_TASK` didn't address the OOM issue

**Comment by travissanderson-wf** [comment] 2019-10-16 16:52
Olesia is looking into a specific issue that I'm not familiar with, I was just experiencing very bad local development.

**Comment by olesiathoms-wk** [comment] 2019-10-16 17:01
@sigmundch yes, that is correct. Using `BUILD_MAX_WORKERS_PER_TASK=1` didn't solve OOM issue for me. Also me and Travis running different apps.

**Comment by robbecker-wf** [comment] 2019-10-25 20:49
Discussion and solutions are happening on https://github.com/dart-lang/sdk/issues/27883 .. we can probably close this issue.

**Comment by sigmundch** [comment] 2019-10-25 20:51
Thanks! Yes

**Closed by sigmundch** 2019-10-25 20:51 UTC
Labels: area-web, web-dart2js
