### ISSUE TITLE
flutter build issue

### ISSUE THREAD

**Issue by RajesMca008** [dart-lang/sdk#35156] opened 2018-11-13 13:51 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\rrallabandi\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [F:\Flutter_work\iOS_BMG\bmg], excluded: [F:\Flutter_work\iOS_BMG\bmg\.idea, F:\Flutter_work\iOS_BMG\bmg\.dart_tool, F:\Flutter_work\iOS_BMG\bmg\.idea, F:\Flutter_work\iOS_BMG\bmg\.pub, F:\Flutter_work\iOS_BMG\bmg\build]}, clientRequestTime: 1542006352244}
FileSystemException: Exists failed, path = 'F:\Flutter_work\iOS_BMG\bmg\build\app\generated\source\r\debug\com\kscf' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by kevmoo** [comment] 2018-11-14 21:56
Duplicate of #35156

**Closed by kevmoo** 2018-11-14 21:56 UTC
