### ISSUE TITLE
Unexpected tag 0 (Nothing) in ?, expected a procedure, a constructor or a function node

### ISSUE THREAD

**Issue by MahdiPishguy** [dart-lang/sdk#38479] opened 2019-09-19 08:46 UTC
```dart
E/Dart    (25968): ../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.cc: 1882: error: Unexpected tag 0 (Nothing) in ?, expected a procedure, a constructor or a function node
E/DartVM  (25968): version=2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "android_arm64"
E/DartVM  (25968): thread=25993, isolate=main(0x7230edf400)
E/DartVM  (25968):   pc 0x0000007224cd3d7c fp 0x0000007223b3c370 /data/app/com.example.sample-IryQrI-plL8BVqDv7Tm2OQ==/lib/arm64/libflutter.so+0x1192d7c
E/DartVM  (25968): -- End of DumpStackTrace
F/libc    (25968): Fatal signal 6 (SIGABRT), code -6 in tid 25993 (Thread-6)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/WAS-LX1A/HWWAS-H:8.0.0/HUAWEIWAS-LX1A/371(C185):user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 25968, tid: 25993, name: Thread-6  >>> com.example.sample<<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0   0000000000000000  x1   0000000000006589  x2   0000000000000006  x3   0000000000000008
    x4   6700000000000000  x5   6700000000000000  x6   6700000000000000  x7   00000000000080e7
    x8   0000000000000083  x9   7297d6913dd1cff0  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000002  x14  ffffffffffffffff  x15  6700000000000000
    x16  00000072427ec2d0  x17  000000724278d800  x18  0000000000000031  x19  0000000000006570
    x20  0000000000006589  x21  000000721c5b4600  x22  0000007223b3c778  x23  0000000000000000
    x24  000000000001001f  x25  0000007223b3cf20  x26  0000007225084718  x27  0000000000000000
    x28  0000007225049a88  x29  0000007223b3c370  x30  0000007242740b54
    sp   0000007223b3c330  pc   000000724278d808  pstate 0000000060000000
backtrace:
    #00 pc 000000000006a808  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000001db50  /system/lib64/libc.so (abort+88)
```

**Comment by jcollins-g** [comment] 2019-11-12 22:30
I have a way to reliably reproduce a crash that looks very much like this, now, on MacOS with IntelliJ 2019.2.4 and Dart 2.7.0-dev.0.0.

`git clone -b crash-branch git@github.com:dart-lang/dartdoc.git`

Run pub get, open in Intellij, set a breakpoint on lib/src/model/library.dart line 107, and run bin/dartdoc.dart on any non-empty project.  Something very bad happens here, as we never seem able to run the given map function.  If we try, we can crash in the debugger -- otherwise the program continues as though the entries list is empty. (The crash does _not_ occur when setting the breakpoints and so forth manually in the observatory -- only in IntelliJ for some reason).

After you are stopped at the breakpoint, try to add a watch in intellij to do something with the entry list.  That will crash.

e.g.:  `_compilationUnitToElement.entries.map((e) => 3)`

Example console output:

```
/Users/jcollins/dart/all_sdks/current/bin/dart --enable-asserts --pause_isolates_on_start --enable-vm-service:51382 /Users/jcollins/dart/dartdoc/bin/dartdoc.dart --output /tmp/sdkdocs --sdk-docs --pretty-index-json
Observatory listening on http://127.0.0.1:51382/5V_9VvfoOuI=/

Documenting Dart...
parsing /Users/jcollins/dart/all_sdks/2.7.0-dev.0.0/lib/async/async.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.0-dev.0.0/lib/collection/collection.dart...
../../runtime/vm/compiler/frontend/kernel_translation_helper.cc: 1946: error: Unexpected tag 0 (Nothing) in ?, expected a procedure, a constructor or a function node
version=2.7.0-dev.0.0 (Tue Nov 5 12:57:33 2019 +0100) on "macos_x64"
thread=6147, isolate=main(0x7fce9480be00)
  pc 0x000000010b99c814 fp 0x000070000387f630 dart::Profiler::DumpStackTrace(void*)
  pc 0x000000010b6b9cd2 fp 0x000070000387f710 dart::Assert::Fail(char const*, ...)
  pc 0x000000010bb96523 fp 0x000070000387f740 dart::kernel::KernelReaderHelper::ReportUnexpectedTag(char const*, dart::kernel::Tag)
  pc 0x000000010bb96620 fp 0x000070000387f7b0 dart::kernel::KernelReaderHelper::ReadUntilFunctionNode()
  pc 0x000000010bb9c774 fp 0x000070000387f900 dart::kernel::ScopeBuilder::BuildScopes()
  pc 0x000000010b99a1a8 fp 0x000070000387fb60 dart::ParsedFunction::EnsureKernelScopes()
  pc 0x000000010bb6f140 fp 0x000070000387fb90 dart::kernel::StreamingFlowGraphBuilder::ParseKernelASTFunction()
  pc 0x000000010bb6ec56 fp 0x000070000387fda0 dart::kernel::StreamingFlowGraphBuilder::BuildGraph()
  pc 0x000000010bb815c6 fp 0x0000700003880020 dart::kernel::FlowGraphBuilder::BuildGraph()
  pc 0x000000010bbad074 fp 0x0000700003880220 dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool)
  pc 0x000000010bbae1c4 fp 0x0000700003880890 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x000000010bbaf148 fp 0x0000700003880a50 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)
  pc 0x000000010bbaed2f fp 0x0000700003880af0 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)
  pc 0x000000010bbad44e fp 0x0000700003880b90 dart::DRT_CompileFunction(dart::NativeArguments)
  pc 0x000000010d880ff8 fp 0x0000700003880bd0 Unknown symbol
  pc 0x000000010d881054 fp 0x0000700003880c00 Unknown symbol
  pc 0x000000011352f7f1 fp 0x0000700003880c30 Unknown symbol
  pc 0x0000000112e5b604 fp 0x0000700003880c70 Unknown symbol
  pc 0x0000000112e5a4e5 fp 0x0000700003880cc0 Unknown symbol
  pc 0x000000011f300aa5 fp 0x0000700003880d40 Unknown symbol
  pc 0x000000011f30053b fp 0x0000700003880dd8 Unknown symbol
  pc 0x00000001148ffcde fp 0x0000700003880e20 Unknown symbol
  pc 0x000000010d88147c fp 0x0000700003880e88 Unknown symbol
  pc 0x000000010b8ae12f fp 0x0000700003880f20 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x000000010b9674d1 fp 0x0000700003880f70 dart::Instance::InvokeGetter(dart::String const&, bool, bool) const
  pc 0x000000010b967a0e fp 0x0000700003880fe0 dart::Instance::Invoke(dart::String const&, dart::Array const&, dart::Array const&, bool, bool) const
  pc 0x000000010b9ffe3a fp 0x0000700003881080 dart::Service::PrintJSONForVM(dart::JSONStream*, bool)
  pc 0x000000010b9f8d9d fp 0x00007000038811e0 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
  pc 0x000000010b9f9411 fp 0x0000700003881200 dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
  pc 0x000000010b8e564b fp 0x0000700003881400 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)
  pc 0x000000010b90ee7e fp 0x0000700003881470 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x000000010b90f24a fp 0x00007000038814b0 dart::MessageHandler::HandleOOBMessages()
  pc 0x000000010be8750c fp 0x0000700003881550 Dart_HandleServiceMessages
  pc 0x000000010b8eae06 fp 0x0000700003881590 dart::Isolate::PauseEventHandler()
  pc 0x000000010b8b3027 fp 0x0000700003881720 dart::Debugger::Pause(dart::ServiceEvent*)
  pc 0x000000010b8be355 fp 0x0000700003881840 dart::Debugger::SignalPausedEvent(dart::ActivationFrame*, dart::Breakpoint*)
  pc 0x000000010b8bebff fp 0x00007000038818b0 dart::Debugger::PauseBreakpoint()
  pc 0x000000010b9ecdb7 fp 0x0000700003881a40 dart::DRT_BreakpointRuntimeHandler(dart::NativeArguments)
  pc 0x000000010d880ff8 fp 0x0000700003881a80 Unknown symbol
  pc 0x000000010d881e12 fp 0x0000700003881ab8 Unknown symbol
  pc 0x000000011486e194 fp 0x0000700003881b08 Unknown symbol
  pc 0x000000011486d63d fp 0x0000700003881b78 Unknown symbol
  pc 0x000000011486d35d fp 0x0000700003881bc8 Unknown symbol
  pc 0x000000011352f7f1 fp 0x0000700003881bf8 Unknown symbol
  pc 0x000000013c13ee14 fp 0x0000700003881c90 Unknown symbol
  pc 0x0000000113519f20 fp 0x0000700003881ce0 Unknown symbol
  pc 0x00000001365636b4 fp 0x0000700003881d40 Unknown symbol
  pc 0x0000000113e4c24f fp 0x0000700003881dc0 Unknown symbol
  pc 0x000000013656352b fp 0x0000700003881e38 Unknown symbol
  pc 0x0000000136562e3b fp 0x0000700003881ee0 Unknown symbol
  pc 0x0000000112e7b134 fp 0x0000700003881f30 Unknown symbol
  pc 0x0000000112e7ad21 fp 0x0000700003881fa8 Unknown symbol
  pc 0x0000000112e79ddb fp 0x0000700003882028 Unknown symbol
  pc 0x0000000112e788b4 fp 0x0000700003882070 Unknown symbol
  pc 0x0000000112e74214 fp 0x00007000038820d0 Unknown symbol
  pc 0x0000000112e73cb5 fp 0x0000700003882108 Unknown symbol
  pc 0x000000012b53fb6c fp 0x00007000038821a0 Unknown symbol
  pc 0x0000000113519f20 fp 0x00007000038821f0 Unknown symbol
  pc 0x00000001365636b4 fp 0x0000700003882250 Unknown symbol
  pc 0x0000000113e4c24f fp 0x00007000038822d0 Unknown symbol
  pc 0x000000013656352b fp 0x0000700003882348 Unknown symbol
  pc 0x0000000136562e3b fp 0x00007000038823f0 Unknown symbol
  pc 0x0000000112e7b134 fp 0x0000700003882440 Unknown symbol
  pc 0x0000000112e7ad21 fp 0x00007000038824b8 Unknown symbol
  pc 0x0000000112e79ddb fp 0x0000700003882538 Unknown symbol
  pc 0x0000000112e788b4 fp 0x0000700003882580 Unknown symbol
  pc 0x0000000112e78478 fp 0x00007000038825d0 Unknown symbol
  pc 0x0000000113e409e5 fp 0x0000700003882648 Unknown symbol
  pc 0x0000000113e40773 fp 0x00007000038826b8 Unknown symbol
  pc 0x000000011353fd38 fp 0x0000700003882758 Unknown symbol
  pc 0x0000000136562935 fp 0x00007000038827c8 Unknown symbol
  pc 0x00000001365627ec fp 0x0000700003882818 Unknown symbol
  pc 0x0000000112e780e1 fp 0x0000700003882858 Unknown symbol
  pc 0x0000000112e77cab fp 0x0000700003882898 Unknown symbol
  pc 0x0000000112e77ba7 fp 0x00007000038828d8 Unknown symbol
  pc 0x000000013c12d8e2 fp 0x0000700003882970 Unknown symbol
  pc 0x000000013c12baeb fp 0x00007000038829a8 Unknown symbol
  pc 0x000000013c12b6aa fp 0x00007000038829f0 Unknown symbol
  pc 0x000000011352f7f1 fp 0x0000700003882a20 Unknown symbol
  pc 0x000000010e368bae fp 0x0000700003882a58 Unknown symbol
  pc 0x000000010d88147c fp 0x0000700003882ac8 Unknown symbol
  pc 0x000000010b8ae12f fp 0x0000700003882b60 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x000000010b8aff9b fp 0x0000700003882bb0 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x000000010b8e54be fp 0x0000700003882db0 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)
  pc 0x000000010b90ed1d fp 0x0000700003882e20 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x000000010b90f596 fp 0x0000700003882e80 dart::MessageHandler::TaskCallback()
  pc 0x000000010ba2568f fp 0x0000700003882eb0 dart::ThreadPool::Worker::Loop()
  pc 0x000000010ba25522 fp 0x0000700003882ee0 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x000000010b998e7f fp 0x0000700003882f10 dart::OSThread::GetMaxStackSize()
  pc 0x00007fff6c5422eb fp 0x0000700003882f30 _pthread_body
  pc 0x00007fff6c545249 fp 0x0000700003882f50 _pthread_start
  pc 0x00007fff6c54140d fp 0x0000700003882f78 thread_start
-- End of DumpStackTrace

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by a-siva** [comment] 2020-10-02 00:46
This is a duplicate of https://github.com/dart-lang/sdk/issues/40916

**Closed** 2020-10-02 00:48 UTC
Labels: area-vm, closed-duplicate, crash, type-bug
