### ISSUE TITLE
SocketException sometimes reports the incorrect port

### ISSUE THREAD

**Issue by Deftness** [dart-lang/sdk#37303] opened 2019-02-27 19:07 UTC
Hello, I am trying to make a http get request with the following code:

```
        var uri = new Uri.http('10.125.32.128:10000', '/keyboard');
        print("Targeting " + uri.toString());
        http.get(uri).then((response) {
          print(response);
        });
```
In the console error, I unfortunately get this response:

```
flutter: Targeting http://10.125.32.128:10000/keyboard
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
SocketException: OS Error: Operation timed out, errno = 60, address = 10.125.32.128, port = 56325
```

I have assigned port `10000`, but the error message says port `56325` is rejected. I have specified and seems to change the port number randomly that it's targeting. Is there a different way I should be specifying the port #?

Note: I am using:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+1
```

**Comment by natebosch** [comment] 2019-06-18 16:35
Moved to the SDK repo since it's not specific to `package:http`. I wonder if the issue is strictly in the error message...

**Comment by georgeherby** [comment] 2019-06-19 16:58
So I agree with @natebosch I believe this is just an issue with the error message.

This code works fine with custom ports (yes its a bit dirty but proves the SDK is fine) 
```
import 'dart:async';
import 'dart:convert';
import 'dart:io';

readResponse(HttpClientResponse response) async {
  var completer = Completer();
  var contents = StringBuffer();
  response.transform(utf8.decoder).listen((data) {
    contents.write(data);
  }, onDone: () => completer.complete(contents.toString()));
  return await completer.future;
}

main() async {
  var uri = Uri.parse("http://10.0.0.1:6100/get_status");
  print(uri.host); // 10.0.0.1
  print(uri.port); // 6100
  print(uri.path); // get_status

  HttpClient client = new HttpClient();
  HttpClientRequest request = await client.getUrl(uri);
  HttpClientResponse response = await request.close();
  print(readResponse(response));

  var uri2 = Uri.http('10.0.0.1:5100', 'get_status');
  print(uri2.host); //10.0.0.1
  print(uri2.port); // 5100
  print(uri2.path); // get_status

  HttpClientRequest request2 = await client.getUrl(uri2);
  HttpClientResponse response2 = await request2.close();
  print(readResponse(response2));
}
```

However, if I change the port to something that does not have anything on it I get an error with the correct IP but the port is not the correct one
`SocketException: OS Error: Connection refused, errno = 61, address = 10.0.0.1, port = 54044`

I am not opposed to changing the title of this issue?

**Comment by georgeherby** [comment] 2019-06-19 17:02
Looks like there are few reporting the same issue under different situations
#36674 #12693

**Comment by natebosch** [comment] 2019-06-19 17:05
Thanks @georgeherby !  Will close as a duplicate of #12693 which has the most context.

**Closed by natebosch** 2019-06-19 17:05 UTC
Labels: area-library, library-io, type-bug

**Comment by AbeerSul** [comment] 2020-03-18 11:32
none of this actually worked for me :/
this command worked like magic "adb reverse tcp:5000 tcp:5000" 💯

**Comment by kamilk91** [comment] 2020-03-25 15:01
I tried to find how to resolve this issue. Nothing worked for me. Just turned on my wifi.

**Comment by Kushagrasri** [comment] 2020-05-21 17:23
i tried everything, working on emulator, android, but the same issue appeared all the time. 
then i used an application called **_ngrok_** which redirects to your _localhost:port_. still, i was getting the same error. then, i **disabled** **windows firewall** and eureka!!!!
hope this helps someone.

**Comment by compazizo** [comment] 2020-05-24 03:30
I have also got same problem. I get normally api data from browser (localhost, myPort).  When tried to call api from flutter, I got error that details are "Connection timeout .. address=right IpAddress, but port= incorrected(randomly set port number)". Any help?

**Comment by Kushagrasri** [comment] 2020-05-28 05:04
> I have also got same problem. I get normally api data from browser (localhost, myPort). When tried to call api from flutter, I got error that details are "Connection timeout .. address=right IpAddress, but port= incorrected(randomly set port number)". Any help?

Try disabling the windows firewall completely. It worked for me.

**Comment by RAHEYO** [comment] 2021-04-27 01:31
> > I have also got same problem. I get normally api data from browser (localhost, myPort). When tried to call api from flutter, I got error that details are "Connection timeout .. address=right IpAddress, but port= incorrected(randomly set port number)". Any help?
> 
> Try disabling the windows firewall completely. It worked for me.

Sorry, it does not work for me, I'm using Mac, and I did went to System Preference and turn off the Firewall COMPLETELY, but I still get the wrong port..

**Comment by RAHEYO** [comment] 2021-04-27 01:32
> I have also got same problem. I get normally api data from browser (localhost, myPort). When tried to call api from flutter, I got error that details are "Connection timeout .. address=right IpAddress, but port= incorrected(randomly set port number)". Any help?

Sorry bother, but did you get a good solution for solving this issue? Or it's the issue on the Framework itself?
