### ISSUE TITLE
Support blank `library` directives

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#32738] opened 2018-04-02 17:52 UTC
We've effectively retired all uses of the library name.

`part of` syntax supports URIs – and we should recommend that.
dartdoc should be using URIs, too - https://github.com/dart-lang/dartdoc/issues/1658

The only usage left is as a place to hang doc comments.

```dart
/// This library is nice
library nice;
```

We should be able to just drop the library name entirely.

```dart
/// This library is nice
library;
```

`pkg/test` has a hack now to find the first annotation in a file to support his for `TestOn`

**Comment by lrhn** [comment] 2018-04-02 17:56
Duplicate of #30394
(And yes, we should just do it ASAP).

**Closed by lrhn** 2018-04-02 17:56 UTC
Labels: Resolution: duplicate, area-language, language-discussion
