### ISSUE TITLE
Dart2JS compiled version shows "Unsupported operation: Cannot find class for ..."

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28915] opened 2017-02-28 08:13 UTC
This sample: https://github.com/MikeMitterer/dart-bug-demo shows the above error when compiled to JS - it works fine in Dartium. It seems to crash on `alertDialog("Alert Message").show();`

MaterialAlertDialog: https://github.com/MikeMitterer/dart-material-design-lite/blob/master/lib/src/dialog/MaterialAlertDialog.dart

```dart
@MdlComponentModel
@di.Injectable()
class App extends MaterialApplication {

    App() {
    }

    void run() {

        this._bind();
    }

    //- private -----------------------------------------------------------------------------------

    void _bind() async {

        final MaterialButton button = MaterialButton.widget(querySelector("#alert-button"));
        final MaterialAlertDialog alertDialog = new MaterialAlertDialog();

        button.onClick.listen((MouseEvent event) {
            alertDialog("Alert Message").show();
        });
    }
}
```

It shows the following error (in Chrome)
```
Uncaught Error: Unsupported operation: Cannot find class for: (String, {String okButton, String title}) => MaterialAlertDialog
    at Object.wrapException (js_helper.dart:1742)
    at Object.reflectClassByName (js_mirrors.dart:637)
    at Object.reflectClassByMangledName (js_mirrors.dart:610)
    at Object.reflectType (js_mirrors.dart:602)
    at JsInstanceMirror.get$type (js_mirrors.dart:948)
    at Renderer._getNamedProperty$2 (renderer.dart:242)
    at Renderer.resolveValue$1 (renderer.dart:215)
    at Renderer._renderSection$1 (renderer.dart:117)
    at SectionNode.accept$1 (renderer.dart:112)
```

Another thing is that I find it still hard (it became better) to find out what's going on if a bug occurs in in the compiled JS version. Stacktrace points to renderer.dart:242 but the bug happens in main:xxx - confusing but maybe it's just a "mirrors" problem...

**Comment by anders-sandholm** [comment] 2017-02-28 08:44
Thanks for filing this. 
@MikeMitterer, what version of the SDK are you using?

**Comment by MikeMitterer** [comment] 2017-02-28 08:51
Sorry - I'm using the latest version: 

- OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217
Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

- Software installed -----------------------------------------------------------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Dart VM version: 1.22.1 (Tue Feb 21 14:24:37 2017) on "macos_x64"
Pub 1.22.1

NPM: 4.1.2

**Comment by jacehensley-wf** [comment] 2017-02-28 22:42
Is this related to https://github.com/dart-lang/sdk/issues/28864?

**Comment by MikeMitterer** [comment] 2017-03-06 16:46
Looks very similar

**Comment by sigmundch** [comment] 2017-03-07 00:38
indeed they seem related. I'll close this bug as duplicate of #288864

FYI @johnniwinther - here is another test case where the `call` has a signature with more than 0 args.

**Closed by sigmundch** 2017-03-07 00:38 UTC
Labels: area-dart2js
