### ISSUE TITLE
Strong mode analyzer doesn't like subtype-overridden subclass members 

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#24753] opened 2015-10-29 17:41 UTC
`Dart VM version: 1.13.0-dev.7.4 (Tue Oct 27 15:05:26 2015) on "windows_x64"`

```dart
import 'dart:async';

abstract class Foo {
  EventSink<int> sink;
}

class BarSink implements EventSink<int> {
  void add(int event) {}
  void addError(errorEvent, [StackTrace stackTrace]) {}
  void close() {}
}

class Bar extends Foo {
  BarSink sink;
}
```
gives 
`Error:(14, 3) Invalid override. The type of Bar.sink= ((BarSink) → void) is not a subtype of Foo.sink= ((EventSink<int>) → void).`

**Comment by vsmenon** [comment] 2015-10-29 18:17
This is intentional, though we really need to improve the message here.  The problem is that overriding the setter with a more specific type isn't sound.  Code that is just setting the `sink` field of a `Foo` with a different `EventSink<int>` type could inadvertently violate the contract of `Bar`.

```dart
EventSink<int> sink = ...;
Foo f = ...;
f.sink = sink; // Can this ever fail?
```

Note, this is not a problem with getters.  If you declared `sink` as a getter, you should be fine:

```dart
abstract class Foo {
  EventSink<int> get sink;
}
```

**Comment by munificent** [comment] 2016-02-18 23:11
Duplicate of #24928.

**Closed by munificent** 2016-02-18 23:11 UTC
Labels: analyzer-strong-mode, area-analyzer, Priority-Medium, Type-Defect
