### ISSUE TITLE
dart2js compiler crashing using `-O0`

### ISSUE THREAD

**Issue by JakeChampion** [dart-lang/sdk#38125] opened 2019-08-29 20:49 UTC
My project compiles under every optimisation setting except for `0`, which is when the compiler crashes. Below is the information that I was advised to send here :)

* Dart SDK Version: Dart VM version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "macos_x64"
* Operating System: MacOSX 10.14.6 (18G87)

```
org-dartlang-sdk:///sdk/lib/async/future.dart@13297+1:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.4.1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Unhandled exception:
type 'HTypeConversion' is not a subtype of type 'HLocalValue'
#0      HLocalGet.local (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2252:28)
#1      SsaInstructionMerger.isEffectivelyPure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:672:71)
#2      SsaInstructionMerger.analyzeInputs (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:639:13)
#3      SsaInstructionMerger.visitInstruction (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:691:5)
#4      HBaseVisitor.visitCreate (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:451:32)
#5      HCreate.accept (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:1695:39)
#6      SsaInstructionMerger.analyzeInputs (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:659:19)
#7      SsaInstructionMerger.visitInstruction (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:691:5)
#8      HBaseVisitor.visitLocalAccess (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:514:42)
#9      HBaseVisitor.visitLocalSet (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:518:36)
#10     HLocalSet.accept (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:2261:39)
#11     SsaInstructionMerger.tryMergingExpressions (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:874:23)
#12     SsaInstructionMerger.tryMergingExpressions (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:899:7)
#13     SsaInstructionMerger.visitBasicBlock (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:783:5)
#14     HGraphVisitor.visitDominatorTree (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/nodes.dart:143:9)
#15     SsaInstructionMerger.visitGraph (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen_helpers.dart:626:5)
#16     SsaCodeGenerator.preGenerateMethod.runPhase.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:372:59)
#17     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#18     SsaCodeGenerator.preGenerateMethod.runPhase (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:372:20)
#19     SsaCodeGenerator.preGenerateMethod (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:384:13)
#20     SsaCodeGenerator.visitGraph (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:453:5)
#21     SsaCodeGeneratorTask.generateMethod.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:150:21)
#22     CompilerTask.measure (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:64:51)
#23     SsaCodeGeneratorTask.generateMethod (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:135:12)
#24     SsaCodeGeneratorTask.generateCode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/codegen.dart:92:14)
#25     SsaFunctionCompiler.compile (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/ssa/ssa.dart:85:38)
#26     OnDemandCodegenResults.getCodegenResults (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/codegen.dart:443:30)
#27     JavaScriptBackend.generateCode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/backend.dart:591:43)
#28     KernelCodegenWorkItem.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_model/js_strategy.dart:210:21)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:474:70)
#30     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:474:32)
#32     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#33     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:472:28)
#34     CompilerDiagnosticReporter.withCurrentElement (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:757:15)
#35     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:470:18)
#36     CodegenEnqueuer._forEach (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:257:12)
#37     CodegenEnqueuer.forEach (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:273:5)
#38     Compiler.emptyQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:466:16)
#39     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#40     Compiler.emptyQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:465:14)
#41     Compiler.processQueue.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:491:7)
#42     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#43     Compiler.processQueue (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:484:14)
#44     Compiler.runCodegenEnqueuer (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:397:5)
#45     Compiler.generateJavaScriptCode (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:290:9)
<asynchronous suspension>
#46     Compiler.compileFromKernel.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:447:9)
#47     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#48     Compiler.compileFromKernel (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:420:14)
#49     Compiler.runInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:265:13)
<asynchronous suspension>
#50     Compiler.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:215:38)
#51     new Future.sync (dart:async/future.dart:224:31)
#52     Compiler.run.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:215:20)
#53     CompilerTask.measureSubtask (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/common/tasks.dart:179:35)
#54     Compiler.run (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/compiler.dart:212:41)
#55     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/compiler/lib/src/apiimpl.dart:91:22)
#56     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#57     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#59     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#60     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#61     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#64     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by sigmundch** [comment] 2019-09-09 21:58
Thanks for reporting the issue!

Indeed, -O0 has some problems and we have been a bit behind on fixing it. Note that it is mostly meant to be used for the compiler team to debug the internals of dart2js and not for for production use, so we hope this shouldn't affect your day to day work.

I'm marking this as a duplicate of https://github.com/dart-lang/sdk/issues/35963

**Closed by sigmundch** 2019-09-09 21:58 UTC
Labels: P3, area-web, web-dart2js

**Comment by JakeChampion** [comment] 2019-09-10 09:17
I was wanting to do some debugging of the internals of dart2js. I'll subscribe to #35963 :)
