### ISSUE TITLE
Dart runtime does not allow declare a class with typed function parameter if it's parametrized contravariant or invariant.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#35115] opened 2018-11-09 09:56 UTC
Dart SDK Version: 2.1.0-dev.9.3
OS: Windows 10

This issue described a case which is the same as in #35114, but it's against runtime and #35114 describe analyzer problem.

Here is a source code example:
``` dart
typedef G<X> = X Function(X);
class A<X extends G> {}

main() {
  G<dynamic> b;
  G<Null> a;
  G<int> c;

  A<G<dynamic>> b1;
  A<G<Null>> a1;
  A<G<int>> c1;
}

```
Seems like all the source lines are valid and should pass.
However, dart throws a compile error for the line 11 (`A<G> c1;`) here.

Dart sample output is:

> test.dart:11:13: Error: Type argument '(dart.core::int) -> ’ dart.core::int' violates the corresponding type variable bound of 'A'.
> Try changing type arguments so that they conform to the bounds.
>   A<G<int>> c1;
>             ^
> test.dart:2:9: Context: Bound of this variable is violated.
> class A<X extends G> {}
>         ^

This happens for both contravariant (typedef G<X> = void Function(X);) and invariant (typedef G<X> = void Function(X);) cases.

The test passes for invariant (typedef G<X> = X Function();) and unused parameter (typedef G<X> = void Function();).

Please note that analyzer throws error for two lines - 10 and 11 with the same code, it's issue #35114).

**Comment by eernstg** [comment] 2018-11-09 11:07
I added [a comment](https://github.com/dart-lang/sdk/issues/35114#issuecomment-437313004) about the status of the specification on this topic.

**Comment by eernstg** [comment] 2021-08-31 08:55
The situation here is the same as in #35114, and I'm closing it for [the same reason](https://github.com/dart-lang/sdk/issues/35114#issuecomment-909036200).

Note that this issue was intended to have `area-front-end`, reporting the same situation for the front end as #35114 does for the analyzer. It doesn't really matter now because I'm closing the issue, but I'll change the label anyway to clarify the situation, should anyone ever look at it again. ;-)

**Closed by eernstg** 2021-08-31 08:55 UTC
Labels: area-analyzer, P2, type-bug, analyzer-spec
