### ISSUE TITLE
Bump up this thread must be alive, the dart2js is till not part of the latest release for ARM

### ISSUE THREAD

**Issue by asmodat** [dart-lang/sdk#44722] opened 2021-01-20 17:26 UTC
Bump up this thread must be alive, the dart2js is till not part of the latest release for ARM

_Originally posted by @asmodat in https://github.com/dart-lang/sdk/issues/43776#issuecomment-763808057_

**Comment by sigmundch** [comment] 2021-01-20 17:34
close as duplicate of #43776

**Closed by sigmundch** 2021-01-20 17:34 UTC
