### ISSUE TITLE
tsan data race around Function kernel_offset

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#45800] opened 2021-04-22 19:07 UTC
```
$ out/ReleaseTSANX64/dart --ignore-unrecognized-flags --packages=$DH/sdk/.packages $DH/sdk/runtime/tests/vm/dart_2/isolates/reload_many_isolates_test.dart

stderr: SUMMARY: ThreadSanitizer: data race ../../out/ReleaseTSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/atomic:977 in dart::ObjectPtr std::__2::__cxx_atomic_load<dart::ObjectPtr>(std::__2::__cxx_atomic_base_impl<dart::ObjectPtr> const*, std::__2::memory_order)
stderr: ==================
stderr: ==================
stderr: WARNING: ThreadSanitizer: data race (pid=747938)
stderr:   Read of size 4 at 0x7ff8490c1850 by thread T10 (mutexes: write M1426):
stderr:     #0 dart::Function::kernel_offset() const ../../out/ReleaseTSANX64/../../runtime/vm/object.h:3038 (dart+0x26e0285)
stderr:     #1 dart::kernel::StreamingFlowGraphBuilder::ParseKernelASTFunction() ../../out/ReleaseTSANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:1040 (dart+0x26e0285)
stderr:     #2 dart::kernel::StreamingFlowGraphBuilder::BuildGraph() ../../out/ReleaseTSANX64/../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc:998 (dart+0x26e000c)
stderr:     #3 dart::kernel::FlowGraphBuilder::BuildGraph() ../../out/ReleaseTSANX64/../../runtime/vm/compiler/frontend/kernel_to_il.cc:767 (dart+0x26ff892)
stderr:     #4 dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool) ../../out/ReleaseTSANX64/../../runtime/vm/compiler/jit/compiler.cc:138 (dart+0x210cd61)
stderr:     #5 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*) ../../out/ReleaseTSANX64/../../runtime/vm/compiler/jit/compiler.cc:549 (dart+0x210e6ff)
stderr:     #6 dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long) ../../out/ReleaseTSANX64/../../runtime/vm/compiler/jit/compiler.cc:729 (dart+0x210f76c)
stderr:     #7 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&) ../../out/ReleaseTSANX64/../../runtime/vm/compiler/jit/compiler.cc:859 (dart+0x210f2b1)
stderr:     #8 dart::Function::EnsureHasCode() const ../../out/ReleaseTSANX64/../../runtime/vm/object.cc:9758 (dart+0x1f563b7)
stderr:     #9 dart::TrySwitchInstanceCall(dart::Thread*, dart::StackFrame*, dart::Code const&, dart::Function const&, dart::ICData const&, dart::Function const&) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:1295 (dart+0x208f186)
stderr:     #10 dart::PatchableCallHandler::DoICDataMissJIT(dart::ICData const&, dart::Object const&, dart::Function const&) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:1955 (dart+0x208f44e)
stderr:     #11 dart::PatchableCallHandler::HandleMissJIT(dart::Object const&, dart::Code const&, dart::Function const&) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2232 (dart+0x2090414)
stderr:     #12 dart::PatchableCallHandler::ResolveSwitchAndReturn(dart::Object const&) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2180 (dart+0x2090414)
stderr:     #13 dart::InlineCacheMissHandler(dart::Thread*, dart::Zone*, dart::GrowableArray<dart::Instance const*> const&, dart::ICData const&, dart::NativeArguments) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2262 (dart+0x2090921)
stderr:     #14 dart::DRT_HelperInlineCacheMissHandlerOneArg(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2279 (dart+0x2090921)
stderr:     #15 dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2273 (dart+0x2090921)
stderr:     #16 <null> <null> (memfd:dart-codespace (deleted)+0x2162)
stderr:     #17 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:147 (dart+0x1e4f037)
stderr:     #18 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:37 (dart+0x1e533e2)
stderr:     #19 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:816 (dart+0x1e533e2)
stderr:     #20 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:1443 (dart+0x1ea23d7)
stderr:     #21 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:233 (dart+0x1eee780)
stderr:     #22 dart::MessageHandler::TaskCallback() ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:443 (dart+0x1eef180)
stderr:     #23 dart::MessageHandlerTask::Run() ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:31 (dart+0x1eefc03)
stderr:     #24 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158 (dart+0x20ec14c)
stderr:     #25 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x20ecb35)
stderr:     #26 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1fefe02)
stderr: 
stderr:   Previous write of size 4 at 0x7ff8490c1850 by thread T7:
stderr:     #0 void dart::Object::StoreNonPointer<unsigned int, unsigned int>(unsigned int const*, unsigned int) const ../../out/ReleaseTSANX64/../../runtime/vm/object.h:682 (dart+0x1f2dfb3)
stderr:     #1 dart::Function::InheritKernelOffsetFrom(dart::Function const&) const ../../out/ReleaseTSANX64/../../runtime/vm/object.cc:9300 (dart+0x1f2dfb3)
stderr:     #2 dart::Function::CreateDynamicInvocationForwarder(dart::String const&) const ../../out/ReleaseTSANX64/../../runtime/vm/object.cc:3858 (dart+0x1f2dfb3)
stderr:     #3 dart::Function::GetDynamicInvocationForwarder(dart::String const&, bool) const ../../out/ReleaseTSANX64/../../runtime/vm/object.cc:3900 (dart+0x1f2e77a)
stderr:     #4 dart::ResolveDynamicAnyArgsWithCustomLookup(dart::Zone*, dart::Class const&, dart::String const&, bool, std::__2::function<dart::FunctionPtr (dart::Class&, dart::String const&)>) ../../out/ReleaseTSANX64/../../runtime/vm/resolver.cc:81 (dart+0x20889c4)
stderr:     #5 dart::ResolveDynamicForReceiverClassWithCustomLookup(dart::Class const&, dart::String const&, dart::ArgumentsDescriptor const&, bool, std::__2::function<dart::FunctionPtr (dart::Class&, dart::String const&)>) ../../out/ReleaseTSANX64/../../runtime/vm/resolver.cc:121 (dart+0x2088361)
stderr:     #6 dart::Resolver::ResolveDynamicForReceiverClass(dart::Class const&, dart::String const&, dart::ArgumentsDescriptor const&, bool) ../../out/ReleaseTSANX64/../../runtime/vm/resolver.cc:147 (dart+0x2088281)
stderr:     #7 dart::Resolve(dart::Thread*, dart::Zone*, dart::GrowableArray<dart::Instance const*> const&, dart::Class const&, dart::String const&, dart::Array const&) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:1353 (dart+0x208ffda)
stderr:     #8 dart::PatchableCallHandler::ResolveTargetFunction(dart::Object const&) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2144 (dart+0x208ffda)
stderr:     #9 dart::PatchableCallHandler::ResolveSwitchAndReturn(dart::Object const&) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2152 (dart+0x2090210)
stderr:     #10 dart::InlineCacheMissHandler(dart::Thread*, dart::Zone*, dart::GrowableArray<dart::Instance const*> const&, dart::ICData const&, dart::NativeArguments) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2262 (dart+0x2090921)
stderr:     #11 dart::DRT_HelperInlineCacheMissHandlerOneArg(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2279 (dart+0x2090921)
stderr:     #12 dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments) ../../out/ReleaseTSANX64/../../runtime/vm/runtime_entry.cc:2273 (dart+0x2090921)
stderr:     #13 <null> <null> (memfd:dart-codespace (deleted)+0x2162)
stderr:     #14 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:147 (dart+0x1e4f037)
stderr:     #15 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:37 (dart+0x1e533e2)
stderr:     #16 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&) ../../out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:816 (dart+0x1e533e2)
stderr:     #17 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:1443 (dart+0x1ea23d7)
stderr:     #18 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:233 (dart+0x1eee780)
stderr:     #19 dart::MessageHandler::TaskCallback() ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:443 (dart+0x1eef180)
stderr:     #20 dart::MessageHandlerTask::Run() ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:31 (dart+0x1eefc03)
stderr:     #21 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158 (dart+0x20ec14c)
stderr:     #22 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x20ecb35)
stderr:     #23 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1fefe02)
stderr: 
stderr:   Location is global '<null>' at 0x000000000000 (memfd:dart-oldspace (deleted)+0x000000041850)
stderr: 
stderr:   Mutex M1426 (0x7b6c00002850) created at:
stderr:     #0 pthread_mutex_init ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1220 (dart+0x1b4dbcd)
stderr:     #1 Mutex ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:300 (dart+0x1ff0237)
stderr:     #2 IsolateGroup ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:375 (dart+0x1e9aeb6)
stderr:     #3 IsolateGroup ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:412 (dart+0x1e9b50a)
stderr:     #4 Dart_CreateIsolateGroup ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1388 (dart+0x278a2cc)
stderr:     #5 dart::bin::CreateIsolateGroupAndSetupHelper(bool, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**, int*) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:795 (dart+0x1bc4ac6)
stderr:     #6 dart::bin::RunMainIsolate(char const*, char const*, dart::bin::CommandLineOptions*) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:965 (dart+0x1bc3ed1)
stderr:     #7 dart::bin::main(int, char**) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:1370 (dart+0x1bc57c5)
stderr:     #8 main ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:1408 (dart+0x1bc6ad2)
stderr: 
stderr:   Thread T10 'DartWorker' (tid=748364, running) created by thread T8 at:
stderr:     #0 pthread_create ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:962 (dart+0x1b4c75b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:172 (dart+0x1fefc8c)
stderr:     #2 dart::ThreadPool::Worker::StartThread() ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296 (dart+0x20eb809)
stderr:     #3 dart::ThreadPool::RunImpl(std::__2::unique_ptr<dart::ThreadPool::Task, std::__2::default_delete<dart::ThreadPool::Task> >) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94 (dart+0x20eb809)
stderr:     #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46 (dart+0x1eee29d)
stderr:     #5 dart::MessageHandler::Run(dart::ThreadPool*, dart::MessageHandler::MessageStatus (*)(unsigned long), void (*)(unsigned long), unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:121 (dart+0x1eee29d)
stderr:     #6 dart::Isolate::Run() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2385 (dart+0x1ea6e9c)
stderr:     #7 Dart_RunLoopAsync ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:2049 (dart+0x278db01)
stderr:     #8 dart::SpawnIsolateTask::Run(dart::Isolate*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:699 (dart+0x1d9adca)
stderr:     #9 dart::SpawnIsolateTask::RunLightweight(char const*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:669 (dart+0x1d9a9f5)
stderr:     #10 dart::SpawnIsolateTask::Run() ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:604 (dart+0x1d9a699)
stderr:     #11 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158 (dart+0x20ec14c)
stderr:     #12 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x20ecb35)
stderr:     #13 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1fefe02)
stderr: 
stderr:   Thread T7 'DartWorker' (tid=748199, running) created by thread T6 at:
stderr:     #0 pthread_create ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:962 (dart+0x1b4c75b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:172 (dart+0x1fefc8c)
stderr:     #2 dart::ThreadPool::Worker::StartThread() ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296 (dart+0x20eb809)
stderr:     #3 dart::ThreadPool::RunImpl(std::__2::unique_ptr<dart::ThreadPool::Task, std::__2::default_delete<dart::ThreadPool::Task> >) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94 (dart+0x20eb809)
stderr:     #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46 (dart+0x1eee29d)
stderr:     #5 dart::MessageHandler::Run(dart::ThreadPool*, dart::MessageHandler::MessageStatus (*)(unsigned long), void (*)(unsigned long), unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:121 (dart+0x1eee29d)
stderr:     #6 dart::Isolate::Run() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2385 (dart+0x1ea6e9c)
stderr:     #7 Dart_RunLoopAsync ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:2049 (dart+0x278db01)
stderr:     #8 dart::SpawnIsolateTask::Run(dart::Isolate*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:699 (dart+0x1d9adca)
stderr:     #9 dart::SpawnIsolateTask::RunLightweight(char const*) ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:669 (dart+0x1d9a9f5)
stderr:     #10 dart::SpawnIsolateTask::Run() ../../out/ReleaseTSANX64/../../runtime/lib/isolate.cc:604 (dart+0x1d9a699)
stderr:     #11 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158 (dart+0x20ec14c)
stderr:     #12 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x20ecb35)
stderr:     #13 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1fefe02)
stderr: 
stderr: SUMMARY: ThreadSanitizer: data race ../../out/ReleaseTSANX64/../../runtime/vm/object.h:3038 in dart::Function::kernel_offset() const
```

**Comment by mkustermann** [comment] 2021-07-14 17:46
This was most likely caused by the same issue as https://github.com/dart-lang/sdk/issues/45170 and was fixed by ab9ccf1e4e685efcb2ab8b82fc37eac131fbc4c6

The dynamic invocation forwarder function should only be visible on other threads (via store-release barrier) after it's fields, including the kernel offset were initialized.

**Closed by mkustermann** 2021-07-14 17:46 UTC
Labels: area-vm, library-isolate
