### ISSUE TITLE
docker run dart cmd crash

### ISSUE THREAD

**Issue by xxzj990** [dart-lang/sdk#54086] opened 2023-11-18 01:18 UTC
dart info:

```
docker run -it --rm dart:3.2.0 dart --version
Dart SDK version: 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "linux_x64"
```

system info:

```
linux
docker 19.03.14
```

error:

run
`docker run -it --rm dart:3.2.0 dart pub get`

get crash
```
../../runtime/bin/eventhandler_linux.cc: 420: error: Failed to start event handler thread 1

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
Aborting reentrant request for stack trace.
```

**Comment by xxzj990** [comment] 2023-11-18 01:37
The latest version of docker has no problem. It seems that there is something wrong with the old version of 19.

If you use dart:3.0.6, there is no problem

**Comment by mraleph** [comment] 2023-11-20 07:11
Given that this works on newer Docker I would assume some sort of Docker problem (other possibility is resource limits 
/ resource exhaustion?) so I am going to close this. 

The code in question did not change for 10+ years - so it's unclear why 3.0.6 vs 3.1.0 would make a difference.

If you really want to know what failed you can `strace` `dart` under Docker and see if we can identify the failed syscall.

**Closed by mraleph** 2023-11-20 07:11 UTC
Labels: area-vm

**Comment by whesse** [comment] 2023-12-14 15:19
I have found the cause of the problem, and there is nothing that Dart can do to make older docker versions (20.10.9 and earlier) work again.

The crash is in glibc version 2.34 or higher, which started using the clone3 syscall.  A workaround is to start the docker dart  container with the --security-opt seccomp=unconfined option.  This makes the clone3 syscall return unsupported rather than failed, so the fallback to clone works.

I don't think it is practical to start building Dart with a much older version of glibc, especially with this workaround available.

Details of the underlying failure are at https://pascalroeleven.nl/2021/09/09/ubuntu-21-10-and-fedora-35-in-docker/

**Comment by whesse** [comment] 2023-12-14 15:39
The libc library is dynamically linked to the dart executable, so the failing higher glibc version is coming from the sysroot (libraries) in the docker image, not the Dart files in that docker image.

Copying the just the dart directories from the official Dart docker image into an older Ubuntu docker image might also be a workaround.

**Comment by xxzj990** [comment] 2023-12-15 00:31
> The libc library is dynamically linked to the dart executable, so the failing higher glibc version is coming from the sysroot (libraries) in the docker image, not the Dart files in that docker image.
> 
> Copying the just the dart directories from the official Dart docker image into an older Ubuntu docker image might also be a workaround.

Thank you very much. I'm already using the latest version of docker.
