### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by danieldotse** [dart-lang/sdk#46145] opened 2021-05-26 12:37 UTC
error: The return type 'bool' isn't a 'KeyEventResult', as required by the closure's context. (return_of_invalid_type_from_closure at [fstore] lib\widgets\layout\highlight_focus.dart:81)

**Comment by vsmenon** [comment] 2021-05-26 12:43
Same q as #46146 : Is this a bug or working as intended? It appears that Flutter deprecated this recently. Did something not work correctly?

**Comment by vsmenon** [comment] 2021-05-26 13:03
Closing as dup of #46146

**Closed by vsmenon** 2021-05-26 13:03 UTC
Labels: area-analyzer, needs-info
