### ISSUE TITLE
Analyzer doesn't warn when you export a non-existent symbol

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25154] opened 2015-12-07 17:13 UTC
This has no warnings or anything:
```dart
export 'dart:core' show	HaHaYouAreFunny;
void main() { }
```

Having at least a hint here would greatly help when we do refactorings and renamings.

**Comment by bwilkerson** [comment] 2015-12-07 17:36
Duplicate of #21030

**Comment by Hixie** [comment] 2015-12-07 18:39
I don't think #21030 is the same bug as this. That bug is about not warning when the imported symbols aren't used. This bug is about exported symbols being non-existent.

**Comment by bwilkerson** [comment] 2015-12-07 18:55
Ok, that makes sense.

**Comment by srawlins** [comment] 2016-04-18 22:40
CR out for review: https://codereview.chromium.org/1901923002/

**Comment by srawlins** [comment] 2016-04-20 22:53
New analyzer hints UNDEFINED_SHOWN_NAME in 53bf36acdb4a6a12addf15eba06eacdab7552f22.

**Closed by srawlins** 2016-04-20 22:53 UTC
Labels: analyzer-hint, area-analyzer, P2 medium, Type: enhancement
