### ISSUE TITLE
dart format hangs when reading from stdin

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#46636] opened 2021-07-15 21:26 UTC
```
echo 'main() {}' | dart format
```

This will print `main() {}` and then hang.

cc @bkonyi @munificent 

This is with the latest dev release `Dart SDK version: 2.14.0-312.0.dev (dev) (Tue Jul 13 15:32:06 2021 -0700) on "linux_x64"`

**Comment by fishythefish** [comment] 2021-07-15 21:30
FWIW this seems to be working on master.

**Comment by mraleph** [comment] 2021-07-16 08:07
Duplicate of #46600

**Closed by mraleph** 2021-07-16 08:07 UTC
