### ISSUE TITLE
Stack trace from Analysis Server: Could not resolve URI

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#25168] opened 2015-12-08 16:09 UTC
SessionID: 1447959453882.2659, release: 1.13.0-dev.7.12

> 100 occurrences in the same session.

```
~1447960117032:Noti:{"event"::"server.error","params"::{"isFatal"::false,"message"::"Could not resolve URI (package.dart) relative to source (___.dart)
UnsupportedOperationException:: ___.dart does not exist. null
#0      NonExistingSource.resolveRelativeUri (package::analyzer/src/generated/source.dart::375)
#1      SourceFactory._internalResolveUri (package::analyzer/src/generated/source.dart::816)
#2      SourceFactory.resolveUri (package::analyzer/src/generated/source.dart::741)
#3      ParseDartTask.resolveDirective (package::analyzer/src/task/dart.dart::3366)
#4      ParseDartTask.internalPerform (package::analyzer/src/task/dart.dart::3269)
#5      AnalysisTask._safelyPerform (package::analyzer/task/model.dart::310)
#6      AnalysisTask.perform (package::analyzer/task/model.dart::210)
#7      AnalysisDriver.performWorkItem (package::analyzer/src/task/driver.dart::271)
#8      AnalysisDriver.performAnalysisTask (package::analyzer/src/task/driver.dart::246)
#9      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1098)
#10     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::170)
#11     AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1096)
#12     PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::367)
#13     AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::798)
#14     Future.Future.<anonymous closure> (dart::async/future.dart::118)
#15     _rootRun (dart::async/zone.dart::903)
#16     _CustomZone.run (dart::async/zone.dart::802)
#17     _CustomZone.runGuarded (dart::async/zone.dart::708)
#18     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#19     _rootRun (dart::async/zone.dart::907)
#20     _CustomZone.run (dart::async/zone.dart::802)
#21     _CustomZone.runGuarded (dart::async/zone.dart::708)
#22     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#23     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#24     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#25     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::150)

","stackTrace"::"#0      NonExistingSource.resolveRelativeUri (package::analyzer/src/generated/source.dart::375)
#1      SourceFactory._internalResolveUri (package::analyzer/src/generated/source.dart::816)
#2      SourceFactory.resolveUri (package::analyzer/src/generated/source.dart::741)
#3      ParseDartTask.resolveDirective (package::analyzer/src/task/dart.dart::3366)
#4      ParseDartTask.internalPerform (package::analyzer/src/task/dart.dart::3269)
#5      AnalysisTask._safelyPerform (package::analyzer/task/model.dart::310)
#6      AnalysisTask.perform (package::analyzer/task/model.dart::210)
#7      AnalysisDriver.performWorkItem (package::analyzer/src/task/driver.dart::271)
#8      AnalysisDriver.performAnalysisTask (package::analyzer/src/task/driver.dart::246)
#9      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1098)
#10     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::170)
#11     AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1096)
#12     PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::367)
#13     AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::798)
#14     Future.Future.<anonymous closure> (dart::async/future.dart::118)
#15     _rootRun (dart::async/zone.dart::903)
#16     _CustomZone.run (dart::async/zone.dart::802)
#17     _CustomZone.runGuarded (dart::async/zone.dart::708)
#18     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#19     _rootRun (dart::async/zone.dart::907)
#20     _CustomZone.run (dart::async/zone.dart::802)
#21     _CustomZone.runGuarded (dart::async/zone.dart::708)
#22     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#23     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#24     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#25     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::150)
"}}
```

**Comment by bwilkerson** [comment] 2015-12-08 20:47
Duplicate of #25164.

**Closed by bwilkerson** 2015-12-08 20:47 UTC
Labels: analyzer-server, area-analyzer, Priority-Medium, Type-Defect
