### ISSUE TITLE
Failed to handle completion domain request

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#25027] opened 2015-11-23 21:00 UTC
```
Dart analysis server, SDK version 1.13.0, server version 1.12.0, error: Failed to handle completion domain request: {clientRequestTime: 1448266345988, params: {file: /Volumes/skip/test/unit/simple/simple_test.dart, offset: 1456}, method: completion.getSuggestions, id: 142}
Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package:analyzer/src/context/context.dart:2113)
#1      AnalysisContextImpl.dispose (package:analyzer/src/context/context.dart:694)
#2      ServerContextManagerCallbacks.removeContext (package:analysis_server/src/analysis_server.dart:1496)
#3      ContextManagerImpl._destroyContext (package:analysis_server/src/context_manager.dart:955)
#4      List.forEach (dart:core-patch/growable_array.dart:233)
#5      ContextManagerImpl.refresh (package:analysis_server/src/context_manager.dart:535)
#6      AnalysisServer.reanalyze (package:analysis_server/src/analysis_server.dart:847)
#7      AnalysisDomainHandler.reanalyze (package:analysis_server/src/domain_analysis.dart:219)
#8      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:180)
#9      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:690)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#11     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:686)
#12     _rootRun (dart:async/zone.dart:907)
#13     _CustomZone.run (dart:async/zone.dart:802)
#14     _CustomZone.runGuarded (dart:async/zone.dart:708)
#15     runZoned (dart:async/zone.dart:1243)
#16     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:685)
#17     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#20     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#21     _rootRunUnary (dart:async/zone.dart:914)
#22     _CustomZone.runUnary (dart:async/zone.dart:810)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#32     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#34     _rootRunUnary (dart:async/zone.dart:914)
#35     _CustomZone.runUnary (dart:async/zone.dart:810)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#47     _rootRunUnary (dart:async/zone.dart:914)
#48     _CustomZone.runUnary (dart:async/zone.dart:810)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#52 _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#53     _StreamController._add (dart:async/stream_controller.dart:616)
#54     _StreamController.add (dart:async/stream_controller.dart:562)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#56     _rootRunUnary (dart:async/zone.dart:918)
#57     _CustomZone.runUnary (dart:async/zone.dart:810)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:716)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#61 _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:744)
#62     _StreamController._add (dart:async/stream_controller.dart:616)
#63     _StreamController.add (dart:async/stream_controller.dart:562)
#64     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#67     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:196)
    at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
    at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
    at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)

```

**Comment by bwilkerson** [comment] 2016-02-04 22:29
Duplicate of #24271

**Closed by bwilkerson** 2016-02-04 22:29 UTC
Labels: analyzer-completion, analyzer-server, area-analyzer, Priority-Medium, Type-Defect
