### ISSUE TITLE
Just reporting the error

### ISSUE THREAD

**Issue by hoornet** [dart-lang/sdk#36283] opened 2019-03-20 19:11 UTC
Analyzer Feedback from IntelliJ

Don't know much about this beyond the fact IntelliJ asked me to report this.

## Version information

- `IDEA IU-183.5912.21`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `IU-183.5912.21, JRE 1.8.0_152-release-1343-b28x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, FATAL error: Failed to handle request: {id: 4240, method: edit.getFixes, params: {file: C:\Users\hoorn\FlutterProjects\DirDev\somedir\lib\bottom_nav\first_tab.dart, offset: 1483}, clientRequestTime: 1553106497697}
NoSuchMethodError: The getter 'namedNames' was called on null.
Receiver: null
Tried calling: namedNames
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      FixProcessor._addFix_changeArgumentName.getNamedParameterNames (package:analysis_server/src/services/correction/fix_internal.dart:1043:27)
#2      FixProcessor._addFix_changeArgumentName (package:analysis_server/src/services/correction/fix_internal.dart:1059:48)
<asynchronous suspension>
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:473:13)
<asynchronous suspension>
#4      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#5      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:589:46)
<asynchronous suspension>
#6      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:264:32)
<asynchronous suspension>
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:367:9)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:349:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:345:50)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1500:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:344:5)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#50     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#51     _StreamController._add (dart:async/stream_controller.dart:640:7)
#52     _StreamController.add (dart:async/stream_controller.dart:586:5)
#53     _Socket._onData (dart:io/runtime/bin/socket_patch.dart:1774:41)
#54     _rootRunUnary (dart:async/zone.dart:1136:13)
#55     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#59     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#60     _StreamController._add (dart:async/stream_controller.dart:640:7)
#61     _StreamController.add (dart:async/stream_controller.dart:586:5)
#62     new _RawSocket.<anonymous closure> (dart:io/runtime/bin/socket_patch.dart:1323:33)
#63     _NativeSocket.issueReadEvent.issue (dart:io/runtime/bin/socket_patch.dart:844:14)
#64     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#65     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#66     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
```

For additional log information, please append the contents of
file://C:\Users\hoorn\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-04-08 16:43
Duplicate of #36271.

**Comment by devoncarew** [comment] 2019-04-30 15:05
fixed in https://github.com/dart-lang/sdk/commit/9f59f46650a4098698c24e1dceafaa326123911f

**Closed by devoncarew** 2019-04-30 15:05 UTC
Labels: area-analyzer
