### ISSUE TITLE
Android Studio: Dart Analyzer fails repeatedly

### ISSUE THREAD

**Issue by kika** [dart-lang/sdk#35671] opened 2019-01-16 03:25 UTC
Here's how my experience writing Flutter app looks like lately:
![image](https://user-images.githubusercontent.com/207889/51224189-a83cf000-18f9-11e9-8a91-1933a51d355b.png)

It happens usually during autocomplete operation. Sometimes when I just write code and it _tries_ to show the autocomplete.

I don't believe it could be that bad (it's barely usable and it's enough people using Flutter already), but I can't figure what could possibly be wrong with my setup. I'm on 3.3RC AS because of the bug in AS3.2/IntelliJ related to Dart formatting which causes loss of code while editing. 

I'll paste a few last errors, maybe someone has a clue on what's going on.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5183351`
- `2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4`
- `AI-182.5107.16.33.5183351, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1024x1280, 2560x1440, 1024x1280`

```
Dart analysis server, SDK version 2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4, server version 1.21.1, error: Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:161:52)
#1      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:728:53)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:362:53)
#3      __InternalLinkedHashMap```
Dart analysis server, SDK version 2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4, server version 1.21.1, error: Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:161:52)
#1      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:728:53)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:362:53)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:327:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:219:14)
#6      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:353:42)
#7      LibraryElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:882:45)
#8      LibraryElementHandle.exportNamespace (package:analyzer/src/dart/element/handle.dart:895:36)
#9      NamespaceBuilder._getExportMapping (package:analyzer/src/dart/resolver/scope.dart:840:17)
#10     NamespaceBuilder.createImportNamespaceForDirective (package:analyzer/src/dart/resolver/scope.dart:702:42)
#11     ImportElementImpl.namespace (package:analyzer/src/dart/element/element.dart:5028:32)
#12     LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:462:43)
#13     new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:371:5)
#14     new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:566:19)
#15     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:113:25)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#19     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#21     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1223:33)
<asynchronous suspension>
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#24     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#25     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#26     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#27     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#28     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#34     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#35     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#36     main (file:///b/rr/tmpeKZXk6/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#37     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#38     main (file:///b/rr/tmpeKZXk6/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#39     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1547608295438 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/user.dart","errors":[]}}
1547608295438 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/address.dart","errors":[]}}
1547608295439 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/documents.dart","errors":[]}}
1547608295439 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/validators.dart","errors":[]}}
1547608295439 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/image_pick.dart","errors":[]}}
1547608295439 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/rating.dart","errors":[]}}
1547608295439 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/rate.dart","errors":[]}}
1547608295439 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/chips_input.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file"
1547608295440 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/banking.dart","errors":[]}}
1547608295440 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/secrets.dart","errors":[]}}
1547608295442 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/edit_ok_cancel.dart","errors":[]}}
1547608295442 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/loading.dart","errors":[]}}
1547608295442 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/spacers.dart","errors":[]}}
1547608295442 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/language.dart","errors":[]}}
1547608295442 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/profile_page.dart","errors":[]}}
1547608295443 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/user_type_page.dart","errors":[]}}
1547608295443 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608295443 <= {"event":"analysis.implemented","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart","classes":[],"members":[]}}
1547608296144 => {"id":"408","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart","offset":0,"length":1296},"clientRequestTime":1
1547608296145 <= {"id":"408","result":{"assists":[]}}
1547608296428 => {"id":"409","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart":{"type":"add","content":"library project
1547608296428 <= {"id":"409","result":{}}
1547608296429 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608296429 => {"id":"410","method":"edit.getFixes","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart","offset":720},"clientRequestTime":1547608296429}
1547608296437 => {"id":"411","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart","offset":758,"length":0},"clientRequestTime":15
1547608296463 <= {"id":"410","result":{"fixes":[]}}
1547608296472 <= {"id":"411","result":{"assists":[]}}
1547608296566 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/project_ui.dart","errors":[]}}
1547608296582 <= {"event":"analysis.errors","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/main.dart","errors":[]}}
1547608296608 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","stackTrace":"RangeError (index):
```

```
Dart analysis server, SDK version 2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4, server version 1.21.1, error: Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart```
Dart analysis server, SDK version 2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4, server version 1.21.1, error: Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart;package:flutter/src/widgets/framework.dart;DateTime
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:314:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:353:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:113:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1006:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:952:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:977:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1372:28)
#8      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#9      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:6744:12)
#10     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:7629:18)
#11     DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:475:56)
#12     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11616:15)
#13     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4401:17)
#14     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:835:10)
#15     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:195:11)
#16     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4396:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#18     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#19     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:691:10)
#20     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:87:13)
#21     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:542:13)
#22     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:86:5)
#23     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#25     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2443:21)
#26     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:715:10)
#27     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2436:49)
#28     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:12)
#29     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:597:31)
#30     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#31     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#32     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#33     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#34     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#35     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#36     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#37     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#38     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#39     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#40     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#41     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#42     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#43     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#44     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#45     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#51     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#52     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#53     main (file:///b/rr/tmpeKZXk6/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#54     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#55     main (file:///b/rr/tmpeKZXk6/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#56     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#57     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1547608167102 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608167167 <= {"id":"1203","result":{"hovers":[]}}
1547608167169 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608167714 => {"id":"1204","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":251,"length":12},"clientRequestTime":1547608
1547608167715 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608167787 <= {"id":"1204","result":{"assists":[]}}
1547608167789 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608168015 => {"id":"1205","method":"edit.getFixes","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":251},"clientRequestTime":1547608168015}
1547608168016 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608168095 <= {"id":"1205","result":{"fixes":[]}}
1547608168095 => {"id":"1206","method":"edit.getFixes","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":251},"clientRequestTime":1547608168095}
1547608168142 <= {"id":"1206","result":{"fixes":[]}}
1547608168144 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608168144 => {"id":"1207","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":254,"length":0},"clientRequestTime":15476081
1547608168145 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608168223 <= {"id":"1207","result":{"assists":[]}}
1547608168225 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608169035 => {"id":"1208","method":"analysis.getHover","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":251},"clientRequestTime":1547608169035}
1547608169035 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608169107 <= {"id":"1208","result":{"hovers":[]}}
1547608169110 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608179303 => {"id":"1209","method":"analysis.getHover","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":544},"clientRequestTime":1547608179303}
1547608179304 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608179380 <= {"id":"1209","result":{"hovers":[]}}
1547608179382 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608182555 => {"id":"1210","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart":{"type":"remove"},"/Users/kika/Projec
1547608182556 <= {"id":"1210","result":{}}
1547608182556 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608182560 => {"id":"1211","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart":{"type":"remove"}}},"clientRequestTime":1547
1547608182645 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","stackTrace":"Exception: Element 
```

```
Dart analysis server, SDK version 2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4, server version 1.21.1, error: Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart```
Dart analysis server, SDK version 2.2.0-edge.2cb346bd0cce075a5b7988cedb678e822a1d50f4, server version 1.21.1, error: Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart;package:flutter/src/widgets/framework.dart;Set
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:314:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:353:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:113:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1006:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:952:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:977:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1372:28)
#8      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#9      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:6744:12)
#10     PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:7629:18)
#11     DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:475:56)
#12     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11616:15)
#13     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4401:17)
#14     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:835:10)
#15     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:195:11)
#16     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4396:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#18     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#19     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:691:10)
#20     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:87:13)
#21     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:542:13)
#22     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:86:5)
#23     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#25     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2443:21)
#26     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:715:10)
#27     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2436:49)
#28     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:12)
#29     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:597:31)
#30     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#31     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#32     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#33     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#34     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#35     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#36     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#37     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#38     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#39     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1223:33)
<asynchronous suspension>
#40     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#41     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#42     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#43     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#44     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#45     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#51     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#52     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#53     main (file:///b/rr/tmpeKZXk6/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#54     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#55     main (file:///b/rr/tmpeKZXk6/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#56     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#57     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1547608071738 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608071814 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","stackTrace":"Exception: Element 
1547608071818 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608071920 => {"id":"1026","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart":{"type":"add","content":"part of project_widge
1547608071921 <= {"id":"1026","result":{}}
1547608071921 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608071999 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","stackTrace":"Exception: Element 
1547608072001 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608088827 => {"id":"1027","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":310,"length":3062},"clientRequestTime":15476
1547608088828 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608088907 => {"id":"1028","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","offset":310,"length":3062},"clientRequestTime":15476
1547608088909 <= {"id":"1027","result":{"assists":[]}}
1547608088956 <= {"id":"1028","result":{"assists":[]}}
1547608088958 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608093055 => {"id":"1029","method":"analysis.setPriorityFiles","params":{"files":["/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart"]},"clientRequestTime":154760809305
1547608093055 => {"id":"1030","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart"],"CLOSING_LAB
1547608093055 => {"id":"1031","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":[]}}}
1547608093056 => {"id":"1032","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart"]}}}
1547608093057 <= {"id":"1029"}
1547608093059 <= {"id":"1030"}
1547608093060 <= {"id":"1031"}
1547608093060 <= {"id":"1032"}
1547608093062 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608093129 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547608093320 => {"id":"1033","method":"analysis.updateContent","params":{"files":{"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart":{"type":"remove"}}},"clientRequestTime":1547
1547608093321 <= {"id":"1033","result":{}}
1547608093321 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547608093321 => {"id":"1034","method":"edit.getAssists","params":{"file":"/Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/project_widgets.dart","offset":594,"length":0},"clientRequestTime":1
1547608093395 <= {"id":"1034","result":{"assists":[]}}
1547608093442 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kika/Projects/Project/FlutterApp/project/lib/ui/widgets/search.dart","stackTrace":"Exception: Element 
```

**Comment by kika** [comment] 2019-01-16 03:31
I've upgraded to AS 3.3 release and the first thing that happened after I opened a fresh version was the same `RangeError (index): Invalid value: Valid value range is empty: 0`.

**Comment by stereotype441** [comment] 2019-01-23 18:22
Duplicate of #35621

**Closed by stereotype441** 2019-01-23 18:22 UTC
Labels: area-analyzer

**Comment by mlenger** [comment] 2020-10-30 20:37
Running `flutter pub upgrade ` in my project fixed it for me
