### ISSUE TITLE
Verify that migration tooling works reasonably well on Windows

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#40381] opened 2020-01-29 19:26 UTC
So far we've been developing the migration tool on Linux.  We need to verify that it doesn't crash and burn on Windows (e.g. links in the preview tool work properly, files get properly found and updated on disk).

**Comment by mnordine** [comment] 2020-04-06 14:36
Just tried it out on Windows and it doesn't work because the url is malformed.

**Comment by stereotype441** [comment] 2020-04-28 16:35
I'm working on this as part of fixing #41678

**Comment by stereotype441** [comment] 2020-05-04 14:39
I believe things are now working, however I expect my work on #41604 to cause enough churn that I want to leave this open until that work is finished; once that happens we can verify Windows support

**Comment by stereotype441** [comment] 2020-05-12 17:00
As of 383e75e5deefe3032b27895810d496f68106ba36, I believe that Windows support is now functional, and adequately unit tested.  I'm seeking out someone with a Windows machine who can help me verify this.

**Comment by mnordine** [comment] 2020-05-12 17:37
Still doesn't work for me. I tried to apply it to StageXL on my Windows machine.

I get:

```
C:\Users\Mark\code\dart\StageXL>dart migrate .
Migrating .

Analyzing project...
No analysis issues found.

Generating migration suggestions...
Found 7286 suggested changes in 202 files.

View migration results:
Visit:

  http://localhost:50598/c:/users/mark/code/dart/stagexl?authToken=sp1pRctWPTs%3D

to see the migration results. Use the interactive web view to review, improve, or apply
the results (alternatively, to apply the results without using the web preview, re-run
the tool with --apply-changes).

When finished with the preview, hit ctrl-c to terminate this process.
```

When I visit that page, it displays ok. But when I try to click on a file in the left sidebar, I get an error that shows as a browser alert:

```
Could not load /users/mark/code/dart/stagexl/lib/src/animation/animation_chain.dart (Instance of 'minified:ew').
```

**Comment by jcollins-g** [comment] 2020-05-12 22:21
confirmed, @mnordine's bug is still an issue.  Clicking on any file results in a broken link:

![image](https://user-images.githubusercontent.com/14116827/81751431-3e3c4880-9464-11ea-8203-2e1951adda32.png)

**Comment by jcollins-g** [comment] 2020-05-12 22:26
A similar issue occurs when clicking on proposed changes in the center pane (assuming you work around the issue above), this time attempting to load paths with drive letters directly.

Could not load c:\users\moby1\dart\dartdoc\bin\dartdoc.dart (Instance of 'minified:ew').

![image](https://user-images.githubusercontent.com/14116827/81751704-d3d7d800-9464-11ea-8e03-aa05d529f942.png)

**Comment by jcollins-g** [comment] 2020-05-12 22:38
Things that work:  Proposed Edits line number links in the right hand column, the Add Hint button, the Rerun Migration button, Report a Problem button, the path at the top of the Edit Details window.

Other things that do not work:  all other clickables except the add hint button in the Edit Details pane.  The edit details pane fails in a variety of ways having to do with path mangling.

From the stack view:  

```
Could not load c:\users\moby1\dart\dartdoc\bin\dartdoc.dart/..\lib\src\dartdoc_options.dart (Instance of 'minified:ew').`

Could not load c:\users\moby1\dart\dartdoc\bin\dartdoc.dart/dartdoc.dart (Instance of 'minified:ew').
```

I am also not having success with apply migration, but I'll try it on a simpler package I know works to make sure it is something having to do with Windows.

**Comment by jcollins-g** [comment] 2020-05-12 23:20
Apply migration works, just in the UI it just wasn't clear to me that it had done something and was finished.

**Comment by mnordine** [comment] 2020-05-12 23:37
@jcollins-g 

> get past that

What do you mean by that? Are you modifying the source and using local overrides or something?

**Comment by jcollins-g** [comment] 2020-05-14 16:17
@mnordine Nothing that extensive -- just manually rewriting the URI in the browser as though the links on the left hand side were generated correctly.

**Comment by lrhn** [comment] 2020-05-29 10:43
Agree. The web-interface does not work. 
If I manually edit the HTML and add the missing `/c:` prefix to the links, then I can use that link, but that's not a solution which scales.

**Comment by MichaelRFairhurst** [comment] 2020-05-29 15:42
Lasse, was this using the latest, and which links exactly were broken?

**Comment by mnordine** [comment] 2020-05-29 16:47
It certainly works better than before on Windows, I'm able to click most links, but not question marks to get more info on why it was made nullable. I filed an issue using the built-in link that comes up on an error here: https://github.com/dart-lang/sdk/issues/42117

**Comment by MichaelRFairhurst** [comment] 2020-06-03 22:07
This is ready for another review. The regions link issue is fixed.

**Comment by mnordine** [comment] 2020-06-03 22:14
Seems to work well for me now.

**Comment by MichaelRFairhurst** [comment] 2020-06-03 23:24
Awesome! I'm going to close this. We can address further windows issues as they come up.

**Closed by MichaelRFairhurst** 2020-06-03 23:24 UTC
Labels: NNBD, analyzer-nnbd-migration, area-analyzer
