### ISSUE TITLE
Type promotion issue with FutureOr

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28768] opened 2017-02-14 22:03 UTC
I'd expect the following code to be strong-mode clean:

```dart
import 'dart:async';

FutureOr<int> foo() => new Future.value();

void main() {
  var result = foo();
  if (result is Future) result.then((_) => print("did it"));
}
```

In fact it produces an error that `The method 'then' isn't defined for the class 'FutureOr<int>'.`

Note that if `foo()` returns `FutureOr` without type parameters, or if I write `is Future<int>` instead of `is Future`, this works as expected.

Tested with 7e9f4ba34c7aa4de65312b943b8f0ff6a4aec37a.

**Comment by lrhn** [comment] 2017-02-15 09:58
You are definitely running into a type promotion problem.

The test `result is Future` doesn't cause type promotion because `Future<dynamic>` isn't more specific than `FutureOr<int>`. 

That's not specific to `FutureOr`, you get the same problem with:
```dart
Iterable<int> foo() => [];
main() {
  var result = foo();
  if (result is List) {
    result.add(42);
  }
}
```
(https://dartpad.dartlang.org/ff43c19b22be84f2d407d4ab99dc8e16)

Should we infer a type parameter on `Future` in the test, and effectively get `is Future<int>`?
It's a hard problem - effectively trying to find a greatest lower bound of `Future<dynamic>` and `FutureOr<int>` (this case is somewhat easy, the general problem ... not so much).

**Comment by nex3** [comment] 2017-02-15 19:51
I would expect `A a; if (a is B) { ... }` to always give `a` the type `B` within the block, regardless of the relationship between `A` and `B`. If we had intersection types, `A & B` would be even better, but falling back to `A` rather than `B` surprises me.

**Comment by lrhn** [comment] 2017-02-16 09:12
Either choice is surprising - if `A` and `B` are unrelated, I'm sure it would also be surprising for 
```dart
A a = ...;
if (a is B) {
  return a.methodFromB() + a.methodFromA();
}
```
to warn (fail in strong mode) because `a` doesn't have `methodFromA` any more. I mean, it's declared to be an `A` *right there*.

The current type promotion says that a variable has its declared type. We can, in some restricted cases, promote it to a *more specific* type, but we never lose information. 
That is, in some cases, when the intersection type is simple, we do promote to the intersection type. 
If it's not simple, we don't promote. If the variable might be assigned to (that is, we can't rule it out based on a very primitive analysis), then we don't promote. 
If the syntax isn't on the right form, we don't promote (e.g., not along the negative edge of an `is! B` check). 

It's so incredibly primitive that it's actually amazing that it ever works :)

**Comment by nex3** [comment] 2017-02-16 21:14
> to warn (fail in strong mode) because `a` doesn't have `methodFromA` any more. I mean, it's declared to be an `A` *right there*.

The same is true for `B` though, and the `B` type is lexically closer/inner which leads to my expectation that it would take precedence.

**Comment by leafpetersen** [comment] 2017-02-23 00:24
I think we've discussed before that promotion should be made better for union types (specifically `FutureOr`).  From memory, I think our thinking was that the right rule for promoting from `A | B` to `C` is that if `C <: A` or `C <: B`, then allow promotion to `C`.  The interesting case is what the `else` branch (or equivalently what `x is! C`) is allowed to prove.  I think the right thing is to essentially filter out all of the arms of the union that are subtypes of `C`.  So switching to n-ary unions, `x is! C` proves that `x`  has type `Union[T in {A, B} | C </: T]`.

**Comment by lrhn** [comment] 2017-02-23 07:51
If we have full union types, then we probably also have intersection types, and then type promotion is always just the intersection of the test type with the previously known type. There won't be cases where we can't promote because the types are unrelated because the intersection always exists (it might be known to be empty, but that's just an optimization where we know the test will always fail - and given our ability to use noSuchMethod to implement arbitrary interfaces, that might not even be decidable).

And it's true that then the else-branch of the `is C` test would be `currentType \ C` (if you look at types as sets) or the union you wrote.

**Comment by bwilkerson** [comment] 2017-02-23 15:10
> ... it might be known to be empty ...

Only if you can make a closed world assumption, which isn't the case with either dartanalyzer or analysis server.

**Comment by lrhn** [comment] 2017-02-23 15:19
... or if one of the types is sealed. There is definitely no common subtype of `int` and `Iterable`. 
That's probably not very useful in practice, though.

The case I was thinking of was two incompatible interfaces, one with a getter and one with a method of the same name. The spec says:
> It is a compile-time error if a class has both a getter and a method with the
same name. This restriction holds regardless of whether the getter is defined
explicitly or implicitly, or whether the getter or the method are inherited or not.

So, if you `x` of a type `Foo` with a getter `foo` (and you trust the type, like in strong mode) and then does `x is Bar` where `Bar` has a method `foo`, then we know that there is no class (and therefore definitely no instance) that satisfy the type constraint `Foo & Bar`. That type is guaranteed to be empty, no closed world analysis needed. 
(Having incompatible method signatures isn't enough, that can be implemented with `noSuchMethod`, but getter/method conflict is one of the few structure-based compile-time errors in Dart 1).

**Comment by leafpetersen** [comment] 2017-02-23 17:34
Just to be clear, I was dropping down to the underlying union type formulation because I think that tells us what the type promotion rules for FutureOr should (or could) be.  We don't actually need to have union types to support it.  `Union[T in {A, Future<A>} | C <:/T]` is either `Null`, `A`, `Future<A>`, or `FutureOr<A>`.

**Comment by jmesserly** [comment] 2018-06-27 22:55
I checked and this program is working as expected:
```dart
import 'dart:async';

FutureOr<int> foo() => new Future.value(123);
FutureOr<int> bar() => 456;

void main() {
  checkEven(int x) => print('$x is even? ${x.isEven}');
  var result = foo();
  if (result is Future<int>) result.then(checkEven);
  result = bar();
  if (result is int) checkEven(result);
}
```
... we could probably handle the else branch a little better though. Moving to area-language for triage.

**Comment by jmesserly** [comment] 2018-06-28 00:36
ah, I see we already have https://github.com/dart-lang/sdk/issues/28783. marking this a dupe of that one

**Closed by jmesserly** 2018-06-28 00:36 UTC
Labels: Type: enhancement, area-language
