### ISSUE TITLE
Annotation throw error in compile time

### ISSUE THREAD

**Issue by LuoJimmy** [dart-lang/sdk#45864] opened 2021-04-29 15:05 UTC
@Teach(9.0)
  int mm = 9; // ok, so annotation is check const obj not const ref

  var t = const Teach(9.0);
  @t
  int mmm = 9; // error, but i think this should be ok, because t ref's obj is const

  const list3 = const [99, 8];

  //list3 = [9];
  @list3
  int m = 9;
  var list4 = const [99, 8];

  print(identical(list3, list4));  // true, so list3 and list4 is ref to a same obj
  list4 = [99, 8];
  print(identical(list3, list4));  // false, so list3 and list4 is not same ref,

**Comment by eernstg** [comment] 2021-04-29 16:08
You just need a few adjustments:

```dart
class Teach { const Teach(_); }

@Teach(9.0)
int mm = 9;

const t = Teach(9.0); // Not `var`!
@t
int mmm = 9;

const list3 = [99, 8];

@list3
int m = 9;
var list4 = const [99, 8];
```

**Comment by eernstg** [comment] 2021-04-29 16:15
@LuoJimmy, I'll close this issue because it is all working as intended. But don't hesitate creating a new issue if you encounter something that doesn't!

**Closed by eernstg** 2021-04-29 16:15 UTC
Labels: closed-as-intended
