### ISSUE TITLE
Dynamically-spawned isolates should include their entrypoint in the service protocol

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24141] opened 2015-08-19 23:32 UTC
When an isolate is newly-spawned and reported via an `IsolateStart` event, loading the isolate won't return a value for the `entry` field. The documentation does say that this field is optional, but it seems like it should be included for these isolates, since it's well-defined.

See also #24140

**Comment by johnmccutchan** [comment] 2015-08-20 00:41
IsolateStart is sent very early on and what you are seeing is consistent. We probably need another event that signals the isolate is 'runnable'.

**Comment by johnmccutchan** [comment] 2015-08-20 00:43
Duplicate of #24140

**Closed by johnmccutchan** 2015-08-20 00:43 UTC
Labels: Area-Observatory, Type-Enhancement
