### ISSUE TITLE
when i run my code i found this issue.

### ISSUE THREAD

**Issue by Pdagre** [dart-lang/sdk#39008] opened 2019-10-21 07:28 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: FileSystemException: Directory listing failed, path = 'C:\Users\HaanBaba\AppData\Local\.dartServer\.analysis-driver\09\' (OS Error: The file or directory is corrupted and unreadable.
```

**Comment by srawlins** [comment] 2019-10-21 15:10
Thanks for reporting this issue. This is likely a duplicate of https://github.com/dart-lang/sdk/issues/37059 but impossible to tell without a stack trace.

**Comment by srawlins** [comment] 2019-10-21 15:11
Duplicate of https://github.com/dart-lang/sdk/issues/37059

**Closed by srawlins** 2019-10-21 15:11 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
