### ISSUE TITLE
Getting "NoSuchMethodError: The getter 'nullabilitySuffix' was called on null." when dart migrate is run.

### ISSUE THREAD

**Issue by SametSahin10** [dart-lang/sdk#45316] opened 2021-03-15 09:50 UTC
I've got an exception when I run `dart migrate` to migrate a Flutter package to null safety.

Dart SDK Version: 2.12.0

I'm using GNU/Linux Ubuntu.

Steps to reproduce:
1. Clone the repository of [this](https://github.com/SametSahin10/maps_toolkit) package to local.
2. Run `dart migrate` while on the root directory of the repository.

Output of `dart migrate`:
```
Migrating /home/sametsahin/work/flutter-projects/flutter-mobile-projects/packages/maps_toolkit

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|]No analysis issues found.

Generating migration suggestions...
[---------------------------------------------------------------------------------------------------------------------------------------------|                                                                   ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
Please include the SDK version (2.12.0) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.
Receiver: null
Tried calling: nullabilitySuffix at offset 0 in /home/sametsahin/work/flutter-projects/flutter-mobile-projects/packages/maps_toolkit/lib/src/polygon_util.dart (import 'dart:collection'; import 'dart:math'; import 'package:maps_toolkit/src/spherical_util.dart'; import 'latlng.dart'; import 'math_util.dart'; class PolygonUtil {static const num earthRadius = 6371009.0; static num _tanLatGC(num lat1, num lat2, num lng2, num lng3) => (tan(lat1) * sin(lng2 - lng3) + tan(lat2) * sin(lng3)) / sin(lng2); static num _mercatorLatRhumb(num lat1, num lat2, num lng2, num lng3) => (MathUtil.mercator(lat1) * (lng2 - lng3) + MathUtil.mercator(lat2) * lng3) / lng2; static bool _intersects(num lat1, num lat2, num lng2, num lat3, num lng3, bool geodesic) {if ((lng3 >= 0 && lng3 >= lng2) || (lng3 < 0 && lng3 < lng2)) {return false;} if (lat3 <= -pi / 2) {return false;} if (lat1 <= -pi / 2 || lat2 <= -pi / 2 || lat1 >= pi / 2 || lat2 >= pi / 2) {return false;} if (lng2 <= -pi) {return false;} final linearLat = (lat1 * (lng2 - lng3) + lat2 * lng3) / lng2; if (lat1 >= 0 && lat2 >= 0 && lat3 < linearLat) {return false;} if (lat1 <= 0 && lat2 <= 0 && lat3 >= linearLat) {return true;} if (lat3 >= pi / 2) {return true;} return geodesic ? tan(lat3) >= _tanLatGC(lat1, lat2, lng2, lng3) : MathUtil.mercator(lat3) >= _mercatorLatRhumb(lat1, lat2, lng2, lng3);} static bool containsLocation(LatLng point, List<LatLng> polygon, bool geodesic) => containsLocationAtLatLng(point.latitude, point.longitude, polygon, geodesic); static bool containsLocationAtLatLng(num latitude, num longitude, List<LatLng> polygon, bool geodesic) {if (polygon.isEmpty) {return false;} final lat3 = MathUtil.toRadians(latitude); final lng3 = MathUtil.toRadians(longitude); final prev = polygon.last; var lat1 = MathUtil.toRadians(prev.latitude); var lng1 = MathUtil.toRadians(prev.longitude); var nIntersect = 0; for (final point2 in polygon) {final dLng3 = MathUtil.wrap(lng3 - lng1, -pi, pi); if (lat3 == lat1 && dLng3 == 0) {return true;} final lat2 = MathUtil.toRadians(point2.latitude); final lng2 = MathUtil.toRadians(point2.longitude); if (_intersects(lat1, lat2, MathUtil.wrap(lng2 - lng1, -pi, pi), lat3, dLng3, geodesic)) {++nIntersect;} lat1 = lat2; lng1 = lng2;} return (nIntersect & 1) != 0;} static const num DEFAULT_TOLERANCE = 0.1; static bool isLocationOnEdge(LatLng point, List<LatLng> polygon, bool geodesic, {num tolerance = DEFAULT_TOLERANCE}) => _isLocationOnEdgeOrPath(point, polygon, true, geodesic, tolerance); static bool isLocationOnPath(LatLng point, List<LatLng> polyline, bool geodesic, {num tolerance = DEFAULT_TOLERANCE}) => _isLocationOnEdgeOrPath(point, polyline, false, geodesic, tolerance); static bool _isLocationOnEdgeOrPath(LatLng point, List<LatLng> poly, bool closed, bool geodesic, num toleranceEarth) {final idx = locationIndexOnEdgeOrPath(point, poly, closed, geodesic, toleranceEarth); return idx >= 0;} static int locationIndexOnPath(LatLng point, List<LatLng> poly, bool geodesic, {num tolerance = DEFAULT_TOLERANCE}) => locationIndexOnEdgeOrPath(point, poly, false, geodesic, tolerance); static int locationIndexOnEdgeOrPath(LatLng point, List<LatLng> poly, bool closed, bool geodesic, num toleranceEarth) {if (poly.isEmpty) {return -1;} final tolerance = toleranceEarth / earthRadius; final havTolerance = MathUtil.hav(tolerance); final lat3 = MathUtil.toRadians(point.latitude); final lng3 = MathUtil.toRadians(point.longitude); final prev = closed ? poly.last : poly.first; var lat1 = MathUtil.toRadians(prev.latitude); var lng1 = MathUtil.toRadians(prev.longitude); var idx = 0; if (geodesic) {for (final point2 in poly) {final lat2 = MathUtil.toRadians(point2.latitude); final lng2 = MathUtil.toRadians(point2.longitude); if (_isOnSegmentGC(lat1, lng1, lat2, lng2, lat3, lng3, havTolerance)) {return max(0, idx - 1);} lat1 = lat2; lng1 = lng2; idx++;}} else {final minAcceptable = lat3 - tolerance; final maxAcceptable = lat3 + tolerance; var y1 = MathUtil.mercator(lat1); final y3 = MathUtil.mercator(lat3); final xTry = List<num>(3); for (final point2 in poly) {final lat2 = MathUtil.toRadians(point2.latitude); final y2 = MathUtil.mercator(lat2); final lng2 = MathUtil.toRadians(point2.longitude); if (max(lat1, lat2) >= minAcceptable && min(lat1, lat2) <= maxAcceptable) {final x2 = MathUtil.wrap(lng2 - lng1, -pi, pi); final x3Base = MathUtil.wrap(lng3 - lng1, -pi, pi); xTry[0] = x3Base; xTry[1] = x3Base + 2 * pi; xTry[2] = x3Base - 2 * pi; for (final x3 in xTry) {final dy = y2 - y1; final len2 = x2 * x2 + dy * dy; final t = len2 <= 0 ? 0 : MathUtil.clamp((x3 * x2 + (y3 - y1) * dy) / len2, 0, 1); final xClosest = t * x2; final yClosest = y1 + t * dy; final latClosest = MathUtil.inverseMercator(yClosest); final havDist = MathUtil.havDistance(lat3, latClosest, x3 - xClosest); if (havDist < havTolerance) {return max(0, idx - 1);}}} lat1 = lat2; lng1 = lng2; y1 = y2; idx++;}} return -1;} static num _sinDeltaBearing(num lat1, num lng1, num lat2, num lng2, num lat3, num lng3) {final sinLat1 = sin(lat1); final cosLat2 = cos(lat2); final cosLat3 = cos(lat3); final lat31 = lat3 - lat1; final lng31 = lng3 - lng1; final lat21 = lat2 - lat1; final lng21 = lng2 - lng1; final a = sin(lng31) * cosLat3; final c = sin(lng21) * cosLat2; final b = sin(lat31) + 2 * sinLat1 * cosLat3 * MathUtil.hav(lng31); final d = sin(lat21) + 2 * sinLat1 * cosLat2 * MathUtil.hav(lng21); final denom = (a * a + b * b) * (c * c + d * d); return denom <= 0 ? 1 : (a * d - b * c) / sqrt(denom);} static bool _isOnSegmentGC(num lat1, num lng1, num lat2, num lng2, num lat3, num lng3, num havTolerance) {final havDist13 = MathUtil.havDistance(lat1, lat3, lng1 - lng3); if (havDist13 <= havTolerance) {return true;} final havDist23 = MathUtil.havDistance(lat2, lat3, lng2 - lng3); if (havDist23 <= havTolerance) {return true;} final sinBearing = _sinDeltaBearing(lat1, lng1, lat2, lng2, lat3, lng3); final sinDist13 = MathUtil.sinFromHav(havDist13); final havCrossTrack = MathUtil.havFromSin(sinDist13 * sinBearing); if (havCrossTrack > havTolerance) {return false;} final havDist12 = MathUtil.havDistance(lat1, lat2, lng1 - lng2); final term = havDist12 + havCrossTrack * (1 - 2 * havDist12); if (havDist13 > term || havDist23 > term) {return false;} if (havDist12 < 0.74) {return true;} final cosCrossTrack = 1 - 2 * havCrossTrack; final havAlongTrack13 = (havDist13 - havCrossTrack) / cosCrossTrack; final havAlongTrack23 = (havDist23 - havCrossTrack) / cosCrossTrack; final sinSumAlongTrack = MathUtil.sinSumFromHav(havAlongTrack13, havAlongTrack23); return sinSumAlongTrack > 0;} static List<LatLng> simplify(List<LatLng> poly, num tolerance) {final n = poly.length; if (n < 1) {throw const FormatException('Polyline must have at least 1 point');} if (tolerance <= 0) {throw const FormatException('Tolerance must be greater than zero');} final closedPolygon = isClosedPolygon(poly); LatLng lastPoint; if (closedPolygon) {const OFFSET = 0.00000000001; lastPoint = poly.last; poly.removeLast(); poly.add(LatLng(lastPoint.latitude + OFFSET, lastPoint.longitude + OFFSET));} int idx; var maxIdx = 0; final stack = Queue<List<int>>(); final dists = List<num>.filled(n, 0); dists[0] = 1; dists[n - 1] = 1; num maxDist; num dist = 0.0; List<int> current; if (n > 2) {final stackVal = [0, (n - 1)]; stack.add(stackVal); while (stack.isNotEmpty) {current = stack.removeLast(); maxDist = 0; for (idx = current[0] + 1; idx < current[1]; ++idx) {dist = distanceToLine(poly[idx], poly[current[0]], poly[current[1]]); if (dist > maxDist) {maxDist = dist; maxIdx = idx;}} if (maxDist > tolerance) {dists[maxIdx] = maxDist; final stackValCurMax = [current[0], maxIdx]; stack.add(stackValCurMax); final stackValMaxCur = [maxIdx, current[1]]; stack.add(stackValMaxCur);}}} if (closedPolygon) {poly.removeLast(); poly.add(lastPoint);} idx = 0; final simplifiedLine = <LatLng>[]; for (final l in poly) {if (dists[idx] != 0) {simplifiedLine.add(l);} idx++;} return simplifiedLine;} static bool isClosedPolygon(List<LatLng> poly) => poly.first == poly.last; static num distanceToLine(final LatLng p, final LatLng start, final LatLng end) {if (start == end) {return SphericalUtil.computeDistanceBetween(end, p);} final s0lat = MathUtil.toRadians(p.latitude); final s0lng = MathUtil.toRadians(p.longitude); final s1lat = MathUtil.toRadians(start.latitude); final s1lng = MathUtil.toRadians(start.longitude); final s2lat = MathUtil.toRadians(end.latitude); final s2lng = MathUtil.toRadians(end.longitude); final s2s1lat = s2lat - s1lat; final s2s1lng = s2lng - s1lng; final u = ((s0lat - s1lat) * s2s1lat + (s0lng - s1lng) * s2s1lng) / (s2s1lat * s2s1lat + s2s1lng * s2s1lng); if (u <= 0) {return SphericalUtil.computeDistanceBetween(p, start);} if (u >= 1) {return SphericalUtil.computeDistanceBetween(p, end);} final su = LatLng(start.latitude + u * (end.latitude - start.latitude), start.longitude + u * (end.longitude - start.longitude)); return SphericalUtil.computeDistanceBetween(p, su);} static List<LatLng> decode(final String encodedPath) {final len = encodedPath.length; final path = <LatLng>[]; var index = 0; var lat = 0; var lng = 0; while (index < len) {var result = 1; var shift = 0; int b1; do {b1 = encodedPath.codeUnitAt(index++) - 63 - 1; result += b1 << shift; shift += 5;} while (b1 >= 0x1f); lat += (result & 1) != 0 ? ~(result >> 1) : (result >> 1); result = 1; shift = 0; int b2; do {b2 = encodedPath.codeUnitAt(index++) - 63 - 1; result += b2 << shift; shift += 5;} while (b2 >= 0x1f); lng += (result & 1) != 0 ? ~(result >> 1) : (result >> 1); path.add(LatLng(lat * 1e-5, lng * 1e-5));} return path;} static String encode(final List<LatLng> path) {var lastLat = 0; var lastLng = 0; final result = StringBuffer(); for (final point in path) {final lat = (point.latitude * 1e5).round(); final lng = (point.longitude * 1e5).round(); _encode(lat - lastLat, result); _encode(lng - lastLng, result); lastLat = lat; lastLng = lng;} return result.toString();} static void _encode(int v, StringBuffer result) {v = v < 0 ? ~(v << 1) : v << 1; while (v >= 0x20) {result.write(String.fromCharCode((0x20 | (v & 0x1f)) + 63)); v >>= 5;} result.write(String.fromCharCode(v + 63));}})

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:51:29)
#2      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1162:27)
#3      TypeSystemImpl.isSubtypeOf (package:analyzer/src/dart/element/type_system.dart:1158:12)
#4      TypeSystemImpl._refineNumericInvocationContextNullSafe (package:analyzer/src/dart/element/type_system.dart:1713:11)
#5      TypeSystemImpl.refineNumericInvocationContext (package:analyzer/src/dart/element/type_system.dart:1402:14)
#6      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:862:24)
#7      InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:326:15)
#8      InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:367:7)
#9      InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:345:7)
#10     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:239:5)
#11     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:811:24)
#12     MethodInvocationResolver._resolveReceiverTypeLiteral (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:712:9)
#13     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:127:9)
#14     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:394:31)
#15     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#16     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1706:10)
#17     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#18     ResolverVisitor.visitConditionalExpression (package:analyzer/src/generated/resolver.dart:1134:22)
#19     ResolverVisitorForMigration.visitConditionalExpression (package:analyzer/src/generated/resolver.dart:2354:13)
#20     ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2265:15)
#21     VariableDeclarationResolver.resolve (package:analyzer/src/dart/resolver/variable_declaration_resolver.dart:58:17)
#22     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2016:34)
#23     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10555:49)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#25     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10661:16)
#26     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#27     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3485:7)
#28     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:2048:11)
#29     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10655:15)
#30     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10709:20)
#31     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#32     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3489:7)
#33     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10705:15)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#35     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#36     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#37     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#38     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#39     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#40     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#41     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#42     ForResolver._resolveBody (package:analyzer/src/dart/resolver/for_resolver.dart:181:17)
#43     ForResolver._forEachParts (package:analyzer/src/dart/resolver/for_resolver.dart:148:5)
#44     ForResolver.resolveStatement (package:analyzer/src/dart/resolver/for_resolver.dart:45:7)
#45     ResolverVisitor.visitForStatementInScope (package:analyzer/src/generated/resolver.dart:1377:18)
#46     ScopedVisitor.visitForStatement (package:analyzer/src/generated/resolver.dart:2764:7)
#47     ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4707:49)
#48     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#49     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#50     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#51     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#52     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#53     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#54     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#55     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#56     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:1561:7)
#57     ResolverVisitorForMigration.visitIfStatement (package:analyzer/src/generated/resolver.dart:2382:13)
#58     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#59     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#60     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#61     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#62     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#63     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#64     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#65     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#66     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#67     ForResolver._resolveBody (package:analyzer/src/dart/resolver/for_resolver.dart:181:17)
#68     ForResolver._forEachParts (package:analyzer/src/dart/resolver/for_resolver.dart:148:5)
#69     ForResolver.resolveStatement (package:analyzer/src/dart/resolver/for_resolver.dart:45:7)
#70     ResolverVisitor.visitForStatementInScope (package:analyzer/src/generated/resolver.dart:1377:18)
#71     ScopedVisitor.visitForStatement (package:analyzer/src/generated/resolver.dart:2764:7)
#72     ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4707:49)
#73     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#74     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#75     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#76     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#77     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#78     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#79     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#80     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#81     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:1576:7)
#82     ResolverVisitorForMigration.visitIfStatement (package:analyzer/src/generated/resolver.dart:2382:13)
#83     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#84     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#85     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#86     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#87     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#88     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#89     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#90     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#91     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#92     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#93     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#94     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#95     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2489:13)
#96     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:957:13)
#97     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#98     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7042:12)
#99     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#100    UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3351:55)
#101    ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:2926:11)
#102    ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2919:7)
#103    ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1666:11)
#104    MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#105    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#106    ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:2550:18)
#107    ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2531:7)
#108    ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:1015:13)
#109    ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#110    ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1091:23)
#111    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#112    FixBuilder.visitAll.<anonymous closure> (package:nnbd_migration/src/fix_builder.dart:212:14)
#113    _rootRun (dart:async/zone.dart:1354:13)
#114    _CustomZone.run (dart:async/zone.dart:1258:19)
#115    _runZoned (dart:async/zone.dart:1788:10)
#116    runZoned (dart:async/zone.dart:1710:10)
#117    NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#118    FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:209:35)
#119    NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:169:18)
#120    NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:115:15)
#121    _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1159:21)
#122    _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1156:28)
#123    _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1081:30)
<asynchronous suspension>
#124    _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1156:5)
<asynchronous suspension>
#125    MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:749:24)
<asynchronous suspension>
#126    MigrateCommand.run (package:nnbd_migration/migration_cli.dart:185:7)
<asynchronous suspension>
#127    CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#128    DartdevRunner.runCommand (package:dartdev/dartdev.dart:199:18)
<asynchronous suspension>
#129    runDartdev (package:dartdev/dartdev.dart:53:16)
<asynchronous suspension>
#130    main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by stereotype441** [comment] 2021-03-15 16:19
@SametSahin10 Thanks for the bug report! Did you try the tool's suggestion of running with `--ignore-exceptions`? If so, did that work?

**Comment by SametSahin10** [comment] 2021-03-16 13:41
> @SametSahin10 Thanks for the bug report! Did you try the tool's suggestion of running with `--ignore-exceptions`? If so, did that work?

I've just tried it and it worked without any errors.

**Comment by stereotype441** [comment] 2021-03-16 13:49
> > @SametSahin10 Thanks for the bug report! Did you try the tool's suggestion of running with `--ignore-exceptions`? If so, did that work?
> 
> I've just tried it and it worked without any errors.

Great, thanks!  That helps in assigning this bug a priority.

**Comment by stereotype441** [comment] 2021-03-17 17:27
Duplicate of #45052

**Closed by stereotype441** 2021-03-17 17:27 UTC
Labels: P1, area-migration
