### ISSUE TITLE
Angular code generator needs to be verified to work with optional new and const

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33221] opened 2018-05-24 00:47 UTC
This is the angular specific issue for https://github.com/dart-lang/sdk/issues/30921 .

**Comment by leafpetersen** [comment] 2018-05-24 00:47
We don't seem to have an area-frameworks flag to triage with, should we?

cc @matanlurey

**Comment by matanlurey** [comment] 2018-05-24 01:48
Probably an `Customer: Frameworks` is probably fine, or similar.

**Comment by dgrove** [comment] 2018-05-29 15:19
any updates here?

**Comment by MichaelRFairhurst** [comment] 2018-05-29 15:26
I have a repro that I've been stepping through, I had at one point thought
I'd pinned down the cause but that turned out to be a dead end. Still
looking but I'm feeling good about it.

>

**Comment by matanlurey** [comment] 2018-05-30 02:42
I saw this on the `dart-lang/build` gitter:

> Source_gen problem...
> This work as expected:
> 
> ```
> @Propagate(const ['id', 'name', 'enabled', 'sex'], const {
>     'items': const Propagate(['id', 'type', 'index', 'insertType.id',
>     'insertType.name', 'video.id', 'video.name'])
>   })
> ```
> Becomes this ```DartObject```
> ```
> Propagate (fields = List ([String ('id'), String ('name'), String ('enabled'), String ('sex')]); relationships = Map ({String ('items') = Propagate (fields = List ([String ('id'), String ('type'), String ('index'), String ('insertType.id'), String ('insertType.name'), String ('video.id'), String ('video.name')]); relationships = Null (null); when = Null (null))}); when = Null (null))
> ```
> 
> When I remove the *const* keyword from the *relationships* property 
> ```
> const {
>     'items': ...
> ```
> 
> It becomes this ```DartObject```: 
> 
> ```
> Propagate (fields = List ([String ('id'), String ('name'), String ('enabled'), String ('sex')]); relationships = Null (null); when = Null (null))
> ```
> 
> The relatshionps property becomes null 
>

**Comment by MichaelRFairhurst** [comment] 2018-05-30 18:34
I believe this is fixed with https://dart-review.googlesource.com/c/sdk/+/57000. Going to do my best to try to confirm that, with that fix, there are no remaining issues.

**Comment by dgrove** [comment] 2018-06-05 16:17
Any updates?

**Comment by MichaelRFairhurst** [comment] 2018-06-05 17:01
I do have some issues I've seen, I thought I had reproed them correctly but found out I was debugging the wrong issue. So I am still working on that.

There's also a DDC issue which may be the same, or different (inside DDC or analyzer).

**Comment by MichaelRFairhurst** [comment] 2018-06-06 17:39
the second analyzer issue I found was fixed: https://dart-review.googlesource.com/c/sdk/+/58800

the DDC issue is still outstanding

**Comment by leafpetersen** [comment] 2018-06-08 20:47
cc @munificent 

@MichaelRFairhurst What's the status on this?

**Comment by MichaelRFairhurst** [comment] 2018-06-08 22:54
Have been working on #30384 which has dragged on more than I expected. I should have either a fix for, or repro of, the DDC issue in a few days (hopefully, some point this weekend)

**Comment by MichaelRFairhurst** [comment] 2018-06-11 22:51
The DDC issue here seems to be the original issue which prompted this. It merely reared its head at different times, and internally, required a patch to dart_lang in addition to third_party/ analyzer.

It seems from my tests that this is now working perfectly. Will keep straining the system a bit longer to increase my certainty in this.

**Comment by MichaelRFairhurst** [comment] 2018-06-14 19:45
Glad I ran further tests.

Found yet another issue related to type parameters. Haven't yet distilled the error I'm seeing, but I'm getting `A value of type 'OpaqueToken<T>' can't be assigned to a variable of type 'OpaqueToken<String>'` in something like the following case:

```
// a.dart:
const x = OpaqueToken<String>(...);

// b.dart:
import 'a.dart' as a;
const x = a.x; // assignment error here!
```

Which is very, very strange. Working to distill this now.

**Comment by matanlurey** [comment] 2018-06-14 19:46
Thanks!

**Comment by MichaelRFairhurst** [comment] 2018-06-14 20:34
OK, digging further, that was a false alarm.

I am not extremely confident that this will work -- assuming you use --preview-dart-2 of course!

**Closed by MichaelRFairhurst** 2018-06-14 20:34 UTC
Labels: area-multi
