### ISSUE TITLE
Const constructor can't be declared for a class with a mixin that declares an instance field

### ISSUE THREAD

**Issue by vr19860507** [dart-lang/sdk#42218] opened 2020-06-07 21:24 UTC
Is it a bug or a feature?

```
mixin A {
  int get prop => 1;
}

class B with A {
  const B();
}
```
_-> Const constructor can't be declared for a class with a mixin that declares an instance field_

But this works!

```
class A {
  const A();
  int get prop => 1;
}

class B extends A {
  const B();
}
```

**Comment by eernstg** [comment] 2020-06-08 07:57
This is a bug, `int get prop => 1;` does not declare an instance field.

**Comment by srawlins** [comment] 2020-06-11 22:00
Thanks for reporting this issue! This is a duplicate of https://github.com/dart-lang/sdk/issues/37810

**Comment by srawlins** [comment] 2020-06-11 22:01
Duplicate of https://github.com/dart-lang/sdk/issues/37810

**Closed by srawlins** 2020-06-11 22:01 UTC
Labels: area-analyzer, type-bug
