### ISSUE TITLE
Analysis painfully slow in IntelliJ after update

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#28383] opened 2017-01-13 15:07 UTC
Having updated IntelliJ to version 2016.3.2, Dart plugin to version 163.11306 and Dart SDK to 1.22.0-dev.6.0
analysis has become painfully slow.

Changes like signature changes or removing/added interface members trigger reanalysis of a huge number of (sometimes completely unaffected) files often taking ~15 seconds, sometimes up to ~1 minute.

**Comment by dgrove** [comment] 2017-01-13 20:49
@bwilkerson is the analysis driver on in this version?

**Comment by bwilkerson** [comment] 2017-01-13 21:47
The analysis driver was enabled by https://github.com/dart-lang/sdk/commit/7e560a612f7e66fd5986c4a663618e45b95f8060. As far as I can see, that means that it was enabled in dev.6.0.

**Comment by scheglov** [comment] 2017-01-13 23:25
Could you please provide more details - project, example of a change, what you see.

**Comment by johnniwinther** [comment] 2017-01-16 09:41
I have pkg/compiler and tests/compiler/dart2js/ open in one "dart2js+unittests" project. 

Remove/reinserting 'MemberEntity.isAssignable' in pkg/compiler/lib/src/elements/entities.dart trigger reanalysis of pkg/compiler/lib/src/util/setlet.dart and tests/compiler/dart2js/sha1_test.dart (none of the files opened in the editor when doing the change).

I normally have two "dart2js+unittests" projects open for two different checkouts of the repository. This sometime confuses the analyser (thinking files from one repo is used in the other). The observations above were made both with one and two projects open at a time.

**Comment by scheglov** [comment] 2017-01-16 20:18
Unfortunately I cannot reproduce the performance problem.
Here is some statistics that I observe:

Start cold: 33242 ms
Start cached: 3157 ms
Remove 'MemberEntity.isAssignable': 20766 ms
Restore: 198 ms
Remove again: 188 ms
Restore again: 194 ms

The new analysis server keeps results of analysis cached on disk, in ~/.dartServer/.analysis-driver folder. So, when you rollback some changes to already seen state, analysis results are quickly restored. Could you verify that you have this folder and it has files?

Actually pkg/compiler/lib/src/util/setlet.dart and tests/compiler/dart2js/sha1_test.dart DOES depend on the file pkg/compiler/lib/src/elements/entities.dart, see the attach with the transitive closure of files - all 388 of them.


What would happen if you try to ignore the fact that analysis is performed in background?
Do you see that some features don't work for you?


[sha1_test_transitive.txt](https://github.com/dart-lang/sdk/files/709317/sha1_test_transitive.txt)

**Comment by johnniwinther** [comment] 2017-01-19 08:40
The .analysis-driver folder exists, currently holding 1.6Mb in 235344 files.

Regarding features, some are no longer working; must annoyingly the link from class to subclasses is gone (so I have to search for 'extends ClassName') and the link to overriding methods is also gone.

**Comment by scheglov** [comment] 2017-01-19 16:49
Hm... 1.6Mb is way too low for such number of files. Are the most of the files empty?

Yes, subclass and implementation indicators are not implemented. This feature require multiple search requests, which might be too expensive. Do you have other problems with features and their performance in an open file?

For subclasses and method implementations there is an explicit action Navigate | Implementation(s). Explicit actions are OK, because when the user explicitly request something, she can wait a bit.
![image](https://cloud.githubusercontent.com/assets/384794/22115840/62800fba-de23-11e6-97b3-0161f84665c8.png)

**Comment by bwilkerson** [comment] 2017-01-19 16:54
FWIW, I really think we need to restore these indicators. I think it's a major usability regression (it certainly is for me).

**Comment by dgrove** [comment] 2017-01-19 16:58
Is it worth tarring up this directory so that that Konstantin can take a
look?

**Comment by johnniwinther** [comment] 2017-01-24 13:37
Do you need more information from me? I'm still seeing these minute long analyses - seriously degrading my work flow.

**Comment by scheglov** [comment] 2017-01-24 15:09
If features - errors, semantic highlighting, navigation, completion, search and refactoring work in the current file fast enough, then no. We think that it's OK for background analysis to take time.

If features don't work in the current file, then yes, it's a problem.

Could you please clarify which is your situation regarding to the current file editing?

**Comment by johnniwinther** [comment] 2017-01-25 09:02
As soon as I start editing it fires of a huge analysis leaving the current file with no assistance - and often with errors "hanging" with a message like "FooMix is not a class..." when long after I have typed the full  word "FooMixin".

**Comment by johnniwinther** [comment] 2017-01-30 09:43
Where should I add the --instrumentation-log-file and --new-analysis-driver-log options?

**Comment by bwilkerson** [comment] 2017-01-30 14:42
Also in `dart.server.additional.arguments`.

**Comment by johnniwinther** [comment] 2017-01-30 14:47
If I set `dart.server.addition.arguments` to

```--enable-new-analysis-driver --instrumentation-log-file=c:/Users/johnniwinther/tmp/server-logs/instrumentation.log --new-analysis-driver-log=file:///C:/Users/johnniwinther/tmp/analysis-logs/analysis-driver.log```

the 'Dart Analysis' view remain empty (crashed perhaps?)

**Comment by johnniwinther** [comment] 2017-01-30 14:50
No.

**Comment by bwilkerson** [comment] 2017-01-30 14:57
Then I'd try running the server from the command-line to see what output does get produced.

**Comment by johnniwinther** [comment] 2017-01-30 14:58
How? We're the executable?

**Comment by bwilkerson** [comment] 2017-01-30 15:54
You can run server from the command line using
```
<sdk>/bin/dart <sdk>/bin/snapshots/analysis_server.dart.snapshot
```
(where `<sdk>` is the path to your sdk).

I tried the arguments you gave on my machine (modified to match my directory structure) and it worked fine. But I noticed that you passed in a path for the instrumentation log that uses forward slashes rather than backward slashes, even though it appears that you're running on Windows. I suspect that this path is used as a path rather than a URI, so we might well be getting an exception when we try to open that file.

**Comment by johnniwinther** [comment] 2017-01-31 08:47
Apparently both paths have to be of the form `c:\dir\file` and `c:\dir` must exist.

**Comment by bwilkerson** [comment] 2017-01-31 14:50
Does that mean that you got it running? Was there any output?

**Comment by johnniwinther** [comment] 2017-01-31 15:43
I get some output in the `instrumentation.log` file but only when I exit IntelliJ (until then the file size is 0). No `analysis-driver.log` is created.

**Comment by bwilkerson** [comment] 2017-01-31 15:58
Great, can you send it to us in a private e-mail?

**Comment by zoechi** [comment] 2017-02-23 09:05
It's now super fast, at least for me.

**Comment by johnniwinther** [comment] 2017-02-23 10:54
Not here. I'm now seeing >10 min re-analysis times here. I've sent some instrumentation logs - are they of any use?

**Comment by zoechi** [comment] 2017-02-23 13:22
In case this is relevant

```
Dart VM version: 1.23.0-edge.5af03687cfff197d970c3fe289b78232d1ed5ae0 (Wed Feb 22 10:00:05 2017) on "linux_x64"
```

**Comment by bwilkerson** [comment] 2017-02-23 17:41
@johnniwinther Thanks for the log files! While they don't really answer the question of *why* you're seeing an issue, they do make the nature of the issue clear. There are periods when server is performing well, intermixed with periods where it's slow. The longer server is running the worse the slowdown becomes. For example, a normal response time for getHover is 2-3 ms. When it first starts showing signs of slowness it starts taking 10 ms. Then it reverts to the 2-3 ms rate. The next time is starts being slow it's more like 30 ms, then it gets fast again. This goes on until it's well past my tolerance level and eventually takes 40 seconds. Clearly not reasonable (to say the least). We will continue to look at this.

**Comment by devoncarew** [comment] 2017-02-24 00:59
From a brief conversation with Brian, it sounds like the log files showed up two IntelliJ issues:

- it is sometimes requesting hover information for the same location dozens of times at the same timestamp (within a millisecond)
- when initially setting up analysis roots, it adds them one at a time (setRoots a, setRoots a+b, setRoots a+b+c, ...) instead of doing a single call with all initial roots.

@bwilkerson, is that the above accurate? Do you have a bit more info so @jwren could dig in or we could open more specific issues against the Dart plugin?

**Comment by bwilkerson** [comment] 2017-02-24 01:07
Two amendments.

First, the repeated request problem was seen for both getHover and getAssists. I'm not sure whether it happened for other requests; those are just the ones that I noticed.

Second, it wasn't quite adding analysis roots one at a time, but each call to setAnalysisRoots was incrementally larger than the previous one by 1 - 3 directories.

I'm happy to help dig out any more information anyone looking at this might need, but at this point I don't know what information that would be.

**Comment by devoncarew** [comment] 2017-02-25 00:25
@bwilkerson, can you quantify a bit what you were seeing, and file (likely separate) issues at https://youtrack.jetbrains.com/issues?q=%23Dart%20%23Unresolved%20? Thanks! Both of these are things we should address during the IntelliJ cherry-pick window.

**Comment by bwilkerson** [comment] 2017-02-25 00:56
What data would you like? I still have the log file (and so does Jaime), and can try to get any data you want out of it.

But, no, I don't have permissions to create issues in the Jetbrains isue tracker.

**Comment by jwren** [comment] 2017-02-27 19:49
I have been unsuccessful in trying to reproduce the getHover/ getAssists or the setAnalysisRoots behavior described above.

@johnniwinther how long does it take before things slow down?  Make sure any symlinks are removed from your roots, as they can be expensive, especially on Windows.

Are you seeing this issue still with the latest Dart Plugin (163.13137)?
( To update the Plugin:
File > Settings > Plugins > Dart > Update, then Restart
New version of the Dart plugin should be version 163.13137)

Any steps to help repro would be very helpful.

**Comment by johnniwinther** [comment] 2017-03-01 11:43
At startup it takes about 10-15 minutes for the system to obtain full analysis data. After this I see slow re-analysis for the next 5-10 minutes and then fast results for the next 15-30 minutes. Then it starts to become slow again.

I've deleted some old symlinks from out/packages - don't know yet if it has any effect.

I am using version 163.13137

For repro: My setup is: Two checkouts of the dart repo. For each repo I have an IntelliJ project containing `pkg/compiler` and `tests/compiler/dart2js/` plus `pkg/js_ast` in one of them. I always have both projects open (different windows) at the same time. I know that this sometimes confuses the analysis; finding class Foo from the project for repo 1 when searching in the project for repo 2 - which should not at all be possible (doesn't the analyzer know that nothing from repo 1 can reach repo 2 and vice versa?)

**Comment by alexander-doroshko** [comment] 2017-03-01 15:01
FWIW in IntelliJ IDEA 2016.3- there was a single Analysis Server that served all open projects. Starting from 2017.1 (in EAP now, will be released this month) there's a separate server per project, so there will be no more references found from a different project.

**Comment by scheglov** [comment] 2017-03-01 17:51
The file byte cache will provide results independently whether they are requested in the same process or across several processes. Performance might be different, because we will not able to share the same in-memory cache, but not drastically. And, unless we have a bug, we should get the result only when there is one for the key. We use case-insensitive keys, so it should work the same for Windows or Mac.

**Comment by bwilkerson** [comment] 2017-03-01 18:22
The performance issue remains an open question, but I think we now understand the confusion caused by having two repositories open.

Analyzer correctly handles the case where two (or more) distinct URI's resolve to the same file (a many-to-one relationship) by defining library equivalence to be based on the URI rather than the resulting file path. This matches the behavior of the VM. However, it doesn't take into account the possibility that the same URI might resolve to two (or more) different files in different contexts (a one-to-many relationship). We believe that this is what's causing the confusion.

The good news is that in the next version of IntelliJ this will be worked around as long as you open each repository in a separate window (which you do). The same problem would occur if you opened both directories in the same window, and this will continue to be broken until we fix in in server.

The bad news is that this (the possibility of confusion) seems to be a fairly rarely occurring problem, so we aren't going to give solving it a high priority at this point. (The performance issue is still something we'd like to resolve.)

**Comment by johnniwinther** [comment] 2017-03-27 12:50
I just updated to IntelliJ IDEA 2017.1 and Dart plugin version 171.4006. The slowness is *not* solved (in effect): The status indicating an ongoing analysis is removed so I can't tell if it is working or not - regardless, the results are *very* late. It takes forever to update the warnings/errors view for the currently edited file and it doesn't seem to find problems in other files before these are opened.

**Comment by alexander-doroshko** [comment] 2017-03-27 13:15
> The status indicating an ongoing analysis is removed

It is not removed but made less visible in order not to irritate users. Green dot on the 'Dart Analysis' tool window icon indicates analysis progress.
![image](https://cloud.githubusercontent.com/assets/4499789/24358004/4f167468-1308-11e7-99c5-8fb6abc314f0.png)

I guess SDK version is more important for your issue than the IDE version.

**Comment by johnniwinther** [comment] 2017-05-04 08:57
The analyzer is still painfully slow and it seem to worsen with every update. 

Besides the slowness it now also misses in-project uses when refactoring and failing to see new files: continuing to show 'Target of URI doesn't exist' even when it is open in an editor. This seem to happen when a new file is checked out through git.

**Comment by johnniwinther** [comment] 2017-05-04 09:01
And it can no longer jump to a declaration outside the project (i.e. from a package). This is very unfortunate since having the source file open was sort of last resort when it when the content assistant doesn't work (or is just too slow).

**Comment by karlklose** [comment] 2017-05-04 09:14
I can observe extreme pauses with the analyzer during typing (tens of
secons) too, but only on Windows (10).

**Comment by johnniwinther** [comment] 2017-05-04 09:22
I'm Windows 7

**Comment by dgrove** [comment] 2017-05-04 15:25
Bumping to P1, given the number of Windows users we have.

**Comment by KOGI** [comment] 2017-09-26 16:23
Any updates on this? I'm still experiencing similar slowness on Windows 10 (only a single repo inside a single project)

**Comment by johnniwinther** [comment] 2017-09-27 07:02
I'm a bit concerned about the approach of storing analysis in a lot of (small) files (in `AppData\Local\.dartServer\.analysis-driver` on Windows). Current my folder contains 190084 files and just loading the directory content in Windows Explorer or Total Commander takes a couple of seconds. In practice I often see the harddrive as the bottle-neck of my system and `dart.exe` is often one of the top images in the 'Disk Activity' in 'Resource Monitor'.

**Comment by scheglov** [comment] 2017-09-27 16:46
At least on Mac and Linux speed of listing many files in the command line, or the more so in UI tool (which would do a lot more processing, like fetching icons, associations, creating widgets) does not correlate with the speed of opening individual files for writing or reading. So, while it would be possible to implement our own file system in single physical file, I think that the file system service is one of the main tasks for operating systems, and it is not wise to compete with them.

The fact that there is a lot of IO might be a sing that there is a lot of analysis done, and results are written to disk. Can you see whether this is mostly read or write? How much bytes are read and how much is written. Analysis Server has in-memory cache for reading, so for not too large projects almost everything what current analysis roots need gets eventually read into memory and we don't perform a lot of reads from disk. OTOH, when we analyze, we have to write new results in order to be able to reuse them between restarts and if in-memory cache overflows.

**Comment by bwilkerson** [comment] 2018-08-27 21:54
Assumed stale.

**Comment by supermuka** [comment] 2018-12-03 23:41
This problem on Windows occurs yet. The workaround is delete frequently all files on AppData\Local\.dartServer\.analysis-driver

**Comment by KOGI** [comment] 2018-12-04 19:34
+1 still slow for me on windows10 as well

**Comment by gctommy** [comment] 2018-12-13 06:59
> Originally Posted by @supermuka
> 
> _This problem on Windows occurs yet. The workaround is delete frequently all files on AppData\Local.dartServer.analysis-driver_

Thanks for mentioning this. That folder for me was more than a gigabyte, cleared it out and now the dart analyzing takes about **5 seconds** instead **10-15 minutes** stalling on a few files. No more slow dart analysis!

Added this to my clean command:

    flutter packages get && flutter packages upgrade && flutter clean && del /q "C:\Users\Tommy\AppData\Local\.dartServer\.analysis-driver\*"

**Comment by dgrove** [comment] 2018-12-13 16:43
Reopening.

**Comment by scheglov** [comment] 2018-12-13 16:54
That's interesting information.

Where is your `AppData\Local\.dartServer\.analysis-driver` located?
Is it on local disk? Or somewhere on network?

The whole point of this file system cache is to provide results reasonably fast. Is it a know problem on Windows, that large directories cause problems with opening and reading files from them and / or writing new files? I myself don't see problems with reading / writing / deleting files in large directories under Windows 7. However I don't have Windows 10 to try.

**Comment by supermuka** [comment] 2018-12-13 17:35
The directory is on local disk. The full path is: `D:\Users\MyUser\AppData\Local\.dartServer\.analysis-driver`
Using Windows 7 (6.1.7601).

**Comment by scheglov** [comment] 2018-12-13 17:51
I don't know what's going on.
We need more information.

Open `Registry...` action in your IDEA.
In this dialog find `dart.server.vm.options` option and give it the following value: `--observe --max_profile_depth=256 --collect_code=false --code_comments=true --old_gen_growth_rate=2800 --pause_isolates_on_unhandled_exceptions=false`. This will start Observatory profiler, at `127.0.0.1:8181`. Open it, after the slow down go to `cpu profile (table)` and try to find what happens, and why. Post here data that you find interesting. This is exploratory process, it is hard to say what exactly to look for. Maybe I/O, maybe some analysis parts.

**Comment by supermuka** [comment] 2018-12-16 15:42
When IntelliJ is opened and the process `Analyzing` is running, a snapshopt of the  partial `cpu profile (table)` on Observatory: 

![analyzing - main](https://user-images.githubusercontent.com/8823569/50055090-2195c700-0131-11e9-8c1f-abc6137b2c31.png)

![analyzing - cachecleanupfunction](https://user-images.githubusercontent.com/8823569/50055095-29ee0200-0131-11e9-9fe0-8f3c9e86059a.png)

Directory `D:\Users\MyUser\AppData\Local\.dartServer\.analysis-driver` information (pt-BR):

![analysis-driver](https://user-images.githubusercontent.com/8823569/50055145-d7f9ac00-0131-11e9-9739-368eb226a867.PNG)

**Timeline (hh:mm:ss) on IntelliJ**:

13:13:00 started IntelliJ

_OPEN PROJECT 1 (default)_
13:13:45 loading project started 
13:14:45 analyzing... started 
13:16:45 analyzing finished (# 2:00).

_OPEN PROJECT 2_
13:17:15 loading project started 
13:17:45 analyzing... started 
13:21:00 analyzing finished (# 3:15).

**Environment**:
Windows 7 (6.1.7601) x64 .
Dart 2.1
Analyzer 0.34.0
Intel i7
RAM 8GB

**Important**: The analyzer is slow when IntelliJ is first opened after Windows restarts. If IntelliJ is closed and reopened (without restarting Windows), the parser runs quickly.

**Comment by scheglov** [comment] 2018-12-18 17:17
I landed the change that uses one-level, two-characters sharding.
I tested it on Windows, and it seems to work.
But I had never had the performance problem that you see.

Could you download the bleeding edge build of Dart VM and give it a try?
https://storage.googleapis.com/dart-archive/channels/be/raw/latest/sdk/dartsdk-windows-x64-release.zip

**Comment by zanderso** [comment] 2018-12-18 17:46
Yes, in general file IO is slow on Windows, especially in a directory with lots of files. Out of curiosity, though it probably doesn't make a difference, is this directory populated with regular files or symlinks?

**Comment by scheglov** [comment] 2018-12-18 17:47
@zanderso Good to know, thanks! The directory has only regular files.

**Comment by scheglov** [comment] 2019-01-03 18:58
@supermuka @johnniwinther @KOGI Have you tried a bleeding edge build, with sharding analysis cache into multiple directories? Does it make things better?

**Comment by zanderso** [comment] 2019-01-03 19:06
More details: https://github.com/Microsoft/WSL/issues/873#issuecomment-425272829

**Comment by scheglov** [comment] 2019-01-03 19:15
Thanks, this link has interesting information.
It was sent to me several days ago, because of this issue, and I read it.

Not sure what conclusions I should make from this, and what actions.
Yes, the file system in Windows is slower, and sometimes unpredictably.
Maybe if the sharding approach does not help, we would have to try something else.

For example using single cache file with database like page managing in it, so that we don't have to open and close files often, make access time requests, etc. It was really easy to use file system to ensure that read/write operation are atomic, but then I don't work on Windows, so don't feel if it causes any pain.

**Comment by KOGI** [comment] 2019-01-03 19:20
I've been away for the holidays and haven't had a chance to test with your
bleeding edge build, yet. However, I checked the cache directory and
confirmed what @gctommy reported. The cache directory was at 1.2+ gigs and
after deleting it, analysis in my project is lightning fast again! It
hasn't slowed down, yet, but when it does, I'll give the bleeding edge
build you posted.

>

**Comment by supermuka** [comment] 2019-01-08 16:57
@scheglov, with ~ 88k files in `..\AppData\Local\.dartServer\.analysis-driver`, before with just this folder the analizer took 3m15s. Now using the above build, with similar number of files distributed in 256 sub-folders that were created, is taking 40 seconds all the process analyzer since start and finish (based on the messages displayed in IntelliJ). It's fast now.

**Comment by kinex** [comment] 2019-01-10 10:58
I had similar issue with VS Code, it was painfully slow. After each hot reload the whole UI hanged for tens of seconds. It was practically unusable. Deleting all files in `..\AppData\Local\.dartServer\.analysis-driver` fixed the issue.

**Closed** 2019-01-10 16:37 UTC
Labels: area-analyzer, os-windows, p1-high, type-performance
