### ISSUE TITLE
Flutter engine const finder tests fail with NNBD flag flip

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#43938] opened 2020-10-27 15:59 UTC
See the log here https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865278440977658192/+/steps/test_engine/0/stdout, ([here is the test itself](https://github.com/flutter/engine/blob/master/tools/const_finder/test/const_finder_test.dart)).

These consts [here](https://github.com/flutter/engine/blob/master/tools/const_finder/test/fixtures/lib/consts.dart#L23) appear to be missing from the dill file, or at least aren't visited by the visitor any longer (the ones numbers 7, 8, and 9). Note that these are const constructor invocations nested inside a non-const constructor invocation, so maybe the visitor doesn't properly crawl those in NNBD mode somehow?

**Comment by jakemac53** [comment] 2020-10-27 16:03
Part of https://github.com/dart-lang/sdk/issues/43872

**Comment by johnniwinther** [comment] 2020-10-27 16:31
Is this only observed when `non-nullable` is enabled by default?

**Comment by jakemac53** [comment] 2020-10-27 16:32
It is observed in the change to flip the flag, it could in theory be related to something else in that PR?

**Comment by johnniwinther** [comment] 2020-10-27 16:47
@alexmarkov This tests runs frontend server with `--tfa` so the problem might be the tree-shaking.

**Comment by jakemac53** [comment] 2020-10-27 16:50
Ah, I wonder if just adding a reference to the `target` in the `toString` method of the `IgnoreMe` class would resolve this?

**Comment by alexmarkov** [comment] 2020-10-27 17:27
@jakemac53 How can I reproduce this problem? I tried getting and building the latest flutter engine, and then running

```
out/host_debug_unopt/dart-sdk/bin/dart --enable-experiment=non-nullable flutter/tools/const_finder/test/const_finder_test.dart out/host_debug_unopt/gen/frontend_server.dart.snapshot out/host_debug_unopt/flutter_patched_sdk
```

but the test works. Do I need to patch additional changes?

**Comment by jakemac53** [comment] 2020-10-27 17:32
This fails with the flag flip cl here https://dart-review.googlesource.com/c/sdk/+/168220

**Comment by alexmarkov** [comment] 2020-10-27 18:01
I patched that CL into `third_party/dart` in the engine build, but still wasn't able to reproduce the problem.
Using engine https://github.com/flutter/engine/commit/53d5d6853193b68ae0e0753bcb1ba6eee86713d5.

**Comment by jakemac53** [comment] 2020-10-27 18:04
Ya, I also haven't been able to repro locally. It seems like possibly my earlier attempt to fix these bots did actually fix it but the bot didn't pick up those changes maybe? I can't really explain why that would happen though it landed a while ago.

**Comment by alexmarkov** [comment] 2020-10-27 18:30
This difference could be caused by signature shaking. It was recently reworked in https://github.com/dart-lang/sdk/commit/23ee425de7533bab8e55957377dbf9e407609df6 (cc @askeksa-google). We should probably make sure that `targetValue` is used in this test to avoid tree shaking.

It is not clear how this is related to null safety...

**Comment by alexmarkov** [comment] 2020-10-27 18:36
Correction: it's `IgnoreMe.target` which is tree-shaken.

@dnfield What would be a correct way to modify this test to avoid inadvertent tree-shaking of unused field and parameter `IgnoreMe.target`, so it would still reflect how const finder is used in Flutter?

**Comment by johnniwinther** [comment] 2020-10-27 18:44
Whether `non-nullable` was enabled by default didn't affect outcome I found in the comment above.

**Comment by alexmarkov** [comment] 2020-10-27 18:44
This test started failing on Flutter HHH since https://github.com/dart-lang/sdk/commit/23ee425de7533bab8e55957377dbf9e407609df6 landed:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865375079288857072/+/steps/test_engine/0/stdout

So it is not really related to NNBD flag flip.
We should probably adjust test to be more resilient against improved signature shaking.

**Comment by alexmarkov** [comment] 2020-10-27 18:49
https://github.com/dart-lang/sdk/commit/23ee425de7533bab8e55957377dbf9e407609df6 is not rolled into Flutter engine yet, so I was not able to reproduce the problem on Flutter/engine checkout, with or without NNBD flag flip CL.

**Comment by alexmarkov** [comment] 2020-10-27 19:11
It looks like @mkustermann is adjusting the const finder test in the manual roll https://github.com/flutter/engine/pull/22153.

**Comment by jakemac53** [comment] 2020-10-27 19:14
Sounds good, thanks for the investigations here!

**Comment by dnfield** [comment] 2020-10-27 19:53
The proposed change sounds fine to me, it should not actually break any usage in flutter for icon shaking.

**Comment by askeksa-google** [comment] 2020-10-28 09:44
[The fix](https://github.com/flutter/engine/pull/22149) was landed in [this roll](https://github.com/flutter/engine/pull/22153).

**Closed by askeksa-google** 2020-10-28 09:44 UTC
Labels: NNBD, P1, area-front-end
