### ISSUE TITLE
Incorrect propagated type hint in strong mode for Future.then (Future<Future<String>>)

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#25482] opened 2016-01-14 21:29 UTC
The code below produces this hint:

```
hint] A value of type 'Future<String>' cannot be assigned to a variable of type 'Future<Future<String>>' (/Users/leafp/tmp/scratch.dart, line 5, col 11)
```

This is broadly connected to https://github.com/dart-lang/dev_compiler/issues/228 , but I think this specific issue looks like we're just missing some code with propagated types when instantiating generic methods, since it is only a hint that is emitted (and hence it seems that that the main static type code is doing the right thing).

```dart
import 'dart:async';

void main() {
  Future<String> p;
  var m = p.then((r) => new Future<String>.value(3));
}
```

cc @alan-knight

**Comment by jmesserly** [comment] 2016-01-14 22:03
> but I think this specific issue looks like we're just missing some code with propagated types when instantiating generic methods

That's fixed now, see #25340 :)

Just a guess. StaticTypeAnalyzer.visitMethodInvocation has a very suspicious `if (methodName == "then") {`  :)

I bet you can reproduce other oddities with these method names (if you put them in the right type):
* then
* $dom_createEvent
* query
* $dom_createElement
* JS
* getContext

**Comment by jmesserly** [comment] 2016-01-14 22:04
In other words, it's happens because the generic "Future.then" (enabled by turning on generic method comments) collides with the hard coded pseudo-generic path.

**Comment by jmesserly** [comment] 2016-01-16 01:21
Oh, wow. Crazy interaction of things going on here.

1. Given `Future<T>.then<S>(S onValue(T t), ...)`, strong mode correctly infers `S` as `Future<String>`
2. Instantiating the return type `Future<S>` yields `Future<Future<String>>`
3. the staticType of `m` is inferred to be `Future<Future<String>>`
4. the propagatedType is inferred using psuedo-generic logic, correctly flattens to `Future<String>`
5. it unconditionally records propagatedType (it does't use the "if better" logic) leading to a staticType and propagatedType
6. when checking the assignment, it uses bestType which uses propagatedType, and sees that `Future<String>` cannot be assigned to `Future<Future<String>>` from step 3.

Several bugs here:
* we should've flattened the Future in Step 2.
* we shouldn't go down the psuedo-generic "then" code path in strong mode in Step 4
* we shouldn't record propagatedType if it is not better in Step 5

**Comment by jmesserly** [comment] 2016-01-20 01:22
https://codereview.chromium.org/1609093003/

**Comment by lrhn** [comment] 2016-01-20 07:03
The generification `Future<T>.then<S>(S onValue(T t), ...)` isn't correct - the correct return type of `onValue` is the union type `S|Future<S>`. I don't think we can represent that yet. That might also be part of the problematic inference - if the actual `onValue` function does return `Future<Something>` then inferring that `S` must be `Future<S>` seems a direct conclusion .

**Comment by jmesserly** [comment] 2016-01-20 17:37
Yeah, for this example a union type would work.

There are other cases where I think you may need flatten(T) to be part of the type system. Here's an example adapted from https://github.com/dart-lang/dev_compiler/issues/228. This blows up inside dart:async in Dart VM checked mode:

$ cat ~/scratch/test.dart
```dart
import 'dart:async';
main() {
  Future<int> f = new Future<int>.value(42);
  Completer<Future<int>> c = new Completer<Future<int>>();
  Future<Future<int>> f2 = c.future;
  c.complete(f);
  f2.then((Future<int> x) {
    print(x);
  });
}
```
$ dart -c ~/scratch/test.dart
```
Unhandled exception:
type '_Future<int>' is not a subtype of type 'Future<Future<int>>' of 'typedFuture'.
#0      _Future._asyncComplete (dart:async/future_impl.dart:452)
#1      _AsyncCompleter.complete (dart:async/future_impl.dart:41)
#2      main (file:///Users/jmesserly/scratch/test.dart:6:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

For strong mode, we were thinking that treating `Future<T>` more like a type operator, equivalent to `Future< flatten(T) >`. That approach is used in the spec to help async/await typing. In the above example `c.future` would be typed `Future<int>`. It has the benefit of fixing `Future<Future>` consistently & matches the always-flatten behavior of futures. But definitely, we're open to other ideas here.

**Comment by jmesserly** [comment] 2016-01-20 19:04
Maybe another way to say this ... if we could type `T | Future<T>` everything that might end up in a Future (via some code path) then union types will work. In general it seems hard to ensure that, e.g.:
```dart
abstract class Stream<T> {
  Future<T> get first;
  // ...
}
main() {
  Stream<Future<int>> s;
  Future<int> f = s.first;
}
```
Without it, it seems like anywhere Future< T > occurs it's potentially problematic. We could rewrite above as `T | Future<T> get first;` which solves the typing problem, but now I can't rely on getting a Future out.

We could add a generic constraint on T, e.g. `class Stream<T !extends Future>` ... that constraint sort-of exists already in checked mode (depending on whether you use ".first")

I guess the benefit of the Future< flatten(T) > interpretation is that all of the problematic cases just work.

**Comment by jmesserly** [comment] 2016-01-20 19:18
here's a complete example for the Stream issue:
```dart
import 'dart:async';
main() {
  StreamController<Future<int>> sc = new StreamController<Future<int>>();
  Stream<Future<int>> s = sc.stream;
  Future<Future<int>> f = s.first;
  sc.add(new Future<int>.value(42));

  // works in production & checked mode, prints 42.
  //f.then((x) { print(x); });

  // works in production, fails in checked mode:
  //
  // Unhandled exception:
  // type 'int' is not a subtype of type 'Future<int>' of 'x'.
  //f.then((Future<int> x) { print(x); });

  // works in production, fails in checked mode:
  // Unhandled exception:
  // type '(int) => dynamic' is not a subtype of type '(Future<int>) => dynamic' of 'f'.
  f.then((int x) { print(x); });
}
```

The static type is Future< int > but the runtime value is always going to be the flattened int.

**Comment by vsmenon** [comment] 2016-01-20 21:50
@jmesserly's `Stream` example is great.  There is no way to type-annotate the parameter (other than `dynamic` or `Object`) for the closure passed to `then` and have it pass checked mode.  It'll either fail when `then` is invoked or when the actual closure is invoked.

That's unfortunate as the parameter *is* always an `int` at runtime.  

Ignoring generic methods for the moment, I think we would need something like *flatten* from the spec to actually type this:

```dart
class Future<T> {
  then(dynamic onValue(FLATTEN(T) value), {Function onError});
}
```

Of course, we could type `onValue` as `Function` (or `value` as `dynamic`), but we lose static checking.

**Comment by lrhn** [comment] 2016-01-21 08:41
> For strong mode, we were thinking that treating `Future<T>` more like a type operator, equivalent to `Future< flatten(T) >`. 

I think that's probably a good idea. Futures are special and ubiquitous, so preventing the user from ever writing `Future<Future<T>>` is a good goal. It won't help the parameter to `Future.then` - that's still a union type. Anything typed as either `T -> S` or `T -> Future<S>` must be accepted. I guess the constraint is that T->X is accepted if FLATTEN(X) is S.


I would also like to prevent `Stream<Future<T>>` and `Future<Stream<T>>`, but those are harder because they actually occur in the intermediate steps used to implement the features that makes those types unnecessary. It's still bad style.

**Closed** 2016-01-22 21:30 UTC
Labels: analyzer-strong-mode, area-analyzer, priority-high, Type-Defect
