### ISSUE TITLE
Crash in dart::Type::IsEquivalent on macos

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#35953] opened 2019-02-14 18:05 UTC
Happened at the end of CI run on the chromebots.

```
version=2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "macos_x64"
si_signo=Segmentation fault: 11(11), si_code=0, si_addr=0x0
thread=4103, isolate=test.dart.snapshot.dart2:main()(0x7fd176013000)
  [0x000000010edc1e3d] dart::Type::IsEquivalent(dart::Instance const&, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*) const
  [0x000000010edc1e3d] dart::Type::IsEquivalent(dart::Instance const&, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*) const
  [0x000000010edc2394] dart::Type::Canonicalize(dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*) const
  [0x000000010ed774a7] dart::Function::ImplicitClosureFunction() const
  [0x000000010ed7a35e] dart::Function::CreateMethodExtractor(dart::String const&) const
  [0x000000010ee4d266] dart::Resolver::ResolveDynamicAnyArgs(dart::Zone*, dart::Class const&, dart::String const&, bool)
  [0x000000010ee4ccd5] dart::Resolver::ResolveDynamicForReceiverClass(dart::Class const&, dart::String const&, dart::ArgumentsDescriptor const&, bool)
  [0x000000010ee5c36d] dart::InlineCacheMissHandler(dart::GrowableArray<dart::Instance const*> const&, dart::ICData const&)
  [0x000000010ee533c2] dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments)
  [0x0000000111ac0fa8] Unknown symbol
  [0x0000000111ac2158] Unknown symbol
  [0x0000000121d5a5b9] Unknown symbol
  [0x0000000121d5a2f8] Unknown symbol
  [0x0000000121d59f8c] Unknown symbol
  [0x0000000119cc6ea2] Unknown symbol
  [0x0000000119cc6c69] Unknown symbol
  [0x0000000119cc677f] Unknown symbol
  [0x0000000119cc45e1] Unknown symbol
  [0x0000000119cc402f] Unknown symbol
  [0x0000000119cc3ee2] Unknown symbol
  [0x0000000121d59ca4] Unknown symbol
  [0x0000000121d597f5] Unknown symbol
  [0x0000000120ac5b5d] Unknown symbol
  [0x0000000120ac573b] Unknown symbol
  [0x0000000120ac5b5d] Unknown symbol
  [0x0000000120ac573b] Unknown symbol
  [0x0000000121d56b58] Unknown symbol
  [0x0000000119ce361f] Unknown symbol
  [0x0000000121d56680] Unknown symbol
  [0x0000000121d5646b] Unknown symbol
  [0x0000000121d55e9e] Unknown symbol
  [0x0000000121d55a83] Unknown symbol
  [0x0000000121d4fce6] Unknown symbol
  [0x0000000116e32b35] Unknown symbol
  [0x0000000121d46f58] Unknown symbol
  [0x000000011a65b5e5] Unknown symbol
  [0x000000011a65b1e8] Unknown symbol
  [0x000000011a65a296] Unknown symbol
  [0x000000011a6591f2] Unknown symbol
  [0x000000011a7f1041] Unknown symbol
  [0x000000011a7ee849] Unknown symbol
  [0x000000011a7ee3aa] Unknown symbol
  [0x0000000116e35501] Unknown symbol
  [0x0000000121d46f58] Unknown symbol
  [0x000000011a65b5e5] Unknown symbol
  [0x000000011a65b1e8] Unknown symbol
  [0x000000011a65a296] Unknown symbol
  [0x000000011a6591f2] Unknown symbol
  [0x000000011a7f1041] Unknown symbol
  [0x000000011a7ee849] Unknown symbol
  [0x000000011a7ee3aa] Unknown symbol
  [0x0000000121d4856d] Unknown symbol
  [0x0000000121d46f58] Unknown symbol
  [0x000000011a65b5e5] Unknown symbol
  [0x000000011a65b1e8] Unknown symbol
  [0x000000011a65a296] Unknown symbol
  [0x000000011a6591f2] Unknown symbol
  [0x000000011a7f1041] Unknown symbol
  [0x000000011a7ee849] Unknown symbol
  [0x000000011a7ee3aa] Unknown symbol
  [0x0000000121d4de08] Unknown symbol
  [0x0000000121d46f58] Unknown symbol
  [0x000000011a65b5e5] Unknown symbol
  [0x000000011a65b1e8] Unknown symbol
  [0x000000011a65a296] Unknown symbol
  [0x000000011a65c866] Unknown symbol
  [0x000000011a65c05d] Unknown symbol
  [0x0000000121d46f58] Unknown symbol
  [0x000000011a65b5e5] Unknown symbol
  [0x000000011a65b1e8] Unknown symbol
  [0x000000011a65a296] Unknown symbol
  [0x000000011a65c866] Unknown symbol
  [0x000000011a65c05d] Unknown symbol
  [0x0000000121d46f58] Unknown symbol
  [0x000000011a65b5e5] Unknown symbol
  [0x000000011a65b1e8] Unknown symbol
  [0x000000011a65a296] Unknown symbol
  [0x000000011a6591f2] Unknown symbol
  [0x000000011a7f1041] Unknown symbol
  [0x000000011a7ee849] Unknown symbol
  [0x000000011a7ee3aa] Unknown symbol
  [0x0000000121d4ecec] Unknown symbol
  [0x0000000121d46f58] Unknown symbol
  [0x000000011a65b5e5] Unknown symbol
  [0x000000011a65b1e8] Unknown symbol
  [0x000000011a65a296] Unknown symbol
  [0x000000011a6591f2] Unknown symbol
  [0x000000011a7f1041] Unknown symbol
  [0x000000011a7f0bd2] Unknown symbol
  [0x0000000119fe4cdb] Unknown symbol
  [0x0000000119fe4885] Unknown symbol
  [0x0000000119fe475d] Unknown symbol
  [0x000000011a7d5e3c] Unknown symbol
  [0x000000011a7d4ac4] Unknown symbol
  [0x000000011a7d4820] Unknown symbol
  [0x0000000116e09a3c] Unknown symbol
  [0x0000000116e271b3] Unknown symbol
  [0x0000000111ac146c] Unknown symbol
  [0x000000010ecf6af0] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  [0x000000010ecf9eb0] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x000000010ed285cc] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x000000010ed587ce] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x000000010ed58da6] dart::MessageHandler::TaskCallback()
  [0x000000010eea115d] dart::ThreadPool::Worker::Loop()
  [0x000000010eea0faa] dart::ThreadPool::Worker::Main(unsigned long)
  [0x000000010edf7f69] dart::ThreadStart(void*)
  [0x00007fffce3c893b] _pthread_body
  [0x00007fffce3c8887] _pthread_body
  [0x00007fffce3c808d] thread_start
-- End of DumpStackTrace
🕐 ELAPSED TIME: 0:00:28.144037 for ../../bin/cache/dart-sdk/bin/pub run test -rcompact -j1 --no-color in dev/bots: 
-----

**Comment by a-siva** [comment] 2019-02-19 04:07
Seems like a duplicate of https://github.com/dart-lang/sdk/issues/35974

**Closed by a-siva** 2019-02-19 04:07 UTC
Labels: area-vm
