### ISSUE TITLE
Dart Analyze tool error during deployment

### ISSUE THREAD

**Issue by seblaa** [dart-lang/sdk#39430] opened 2019-11-18 19:23 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.7142.36`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `IU-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 2560x1440, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, FATAL error: Failed to handle request: {id: 6224, method: edit.getFixes, params: {file: C:\APPS\PROJECTS\flutter-poc\lib\startserver.dart, offset: 4801}, clientRequestTime: 1574104529040}
type 'ListLiteralImpl' is not a subtype of type 'SimpleIdentifier' in type cast
#0      FixProcessor._addFix_importLibrary_withExtension (package:analysis_server/src/services/correction/fix_internal.dart:2805:34)
#1      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#2      FixProcessor._addFix_importLibrary_withExtension (package:analysis_server/src/services/correction/fix_internal.dart:2804:51)
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:474:13)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\***\AppData\Local\Temp\1\report.txt.

**Comment by srawlins** [comment] 2019-11-28 04:21
This was previously reported at https://github.com/dart-lang/sdk/issues/38437 and subsequently fixed. Please upgrade to Dart 2.6.0 final, or newer, and re-open if you see this again.

**Comment by srawlins** [comment] 2019-11-28 04:21
Duplicate of https://github.com/dart-lang/sdk/issues/38437

**Closed by srawlins** 2019-11-28 04:21 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
