### ISSUE TITLE
Error in compiler

### ISSUE THREAD

**Issue by gabulsavul** [dart-lang/sdk#35160] opened 2018-11-13 20:06 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.2`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1080`

# Exception

Please append the contents of:
file://C:\Users\gabul\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.2, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\gabul\Desenvolvedor\Mobile\Projetos\ClubPetro\clubpetro_revendedor], excluded: [C:\Users\gabul\Desenvolvedor\Mobile\Projetos\ClubPetro\clubpetro_revendedor\.idea, C:\Users\gabul\Desenvolvedor\Mobile\Projetos\ClubPetro\clubpetro_revendedor\.dart_tool, C:\Users\gabul\Desenvolvedor\Mobile\Projetos\ClubPetro\clubpetro_revendedor\.pub, C:\Users\gabul\Desenvolvedor\Mobile\Projetos\ClubPetro\clubpetro_revendedor\build]}, clientRequestTime: 1542136489074}
FileSystemException: Exists failed, path = 'C:\Users\gabul\Desenvolvedor\Mobile\Projetos\ClubPetro\clubpetro_revendedor\build\firebase_analytics\generated\source\r\debug\android\arch\lifecycle' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by kevmoo** [comment] 2018-11-14 21:55
Please include the info in `C:\Users\gabul\AppData\Local\Temp\report.txt`

**Comment by stereotype441** [comment] 2018-11-15 18:45
Duplicate of #34294

**Closed by stereotype441** 2018-11-15 18:45 UTC
Labels: area-analyzer, needs-info
