### ISSUE TITLE
Infinite loop in dart2js

### ISSUE THREAD

**Issue by fsc8000** [dart-lang/sdk#26493] opened 2016-05-19 15:37 UTC
Repro:
```
python tools/test.py -mrelease -aia32 -cdart2js --dart2js-batch -rd8 --clear_browser_cache --write-debug-log --write-test-outcome-log --copy-coredumps --host-checked -t960 pkg/analyzer/tool/task_dependency_graph/check_test
```

It seems to have started with commit 144294fb2e8dee6a0b551473645c83286e95c39c which did not change anything in dart2js, but changed the input (analyzer)

**Comment by fsc8000** [comment] 2016-05-19 15:51
@sigmundch @johnniwinther

**Comment by johnniwinther** [comment] 2016-05-23 08:19
The infinite does not occur with a newer vm build. Closing assuming that this was caused by the reason problems in the vm.

**Closed by johnniwinther** 2016-05-23 08:19 UTC
Labels: area-dart2js

**Comment by fsc8000** [comment] 2016-05-23 08:21
Yes, it is possible that this is related to my fix baaea63e0a4b0e18dc423f967920b0bd42b5ea8a.

Did you re-enable the test again?

**Comment by johnniwinther** [comment] 2016-05-23 08:30
Will do shortly.
