### ISSUE TITLE
FileSystemException in _WindowsDirectoryWatcher when running analysis server

### ISSUE THREAD

**Issue by seancondev** [dart-lang/sdk#34550] opened 2018-09-22 23:16 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\XXXXX\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.be6309690fd60284a87f3258a740c7c30efb1092, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\XXXXX\OneDrive\Documents\AndroidStudioProjects\cc], excluded: [C:\Users\XXXXX\OneDrive\Documents\AndroidStudioProjects\cc\.idea, C:\Users\XXXXX\OneDrive\Documents\AndroidStudioProjects\cc\.dart_tool, C:\Users\XXXXX\OneDrive\Documents\AndroidStudioProjects\cc\.idea, C:\Users\XXXXX\OneDrive\Documents\AndroidStudioProjects\cc\.pub, C:\Users\XXXXX\OneDrive\Documents\AndroidStudioProjects\cc\build]}, clientRequestTime: 1537654011884}
FileSystemException: Exists failed, path = 'C:\Users\XXXXX\OneDrive\Documents\AndroidStudioProjects\cc\build\app\intermediates\transforms\dexBuilder\debug\6\com\google\firebase\analytics' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap
[report.txt](https://github.com/dart-lang/sdk/files/2408246/report.txt)

**Comment by stereotype441** [comment] 2018-10-23 03:50
Duplicate of #34294

**Closed by stereotype441** 2018-10-23 03:50 UTC
Labels: area-analyzer
