### ISSUE TITLE
DDC strong mode and exact types

### ISSUE THREAD

**Issue by mkj-gram** [dart-lang/sdk#30546] opened 2017-08-25 11:39 UTC
In strong-mode the following test fails (from compile_time_constant_static5_test):

class A {
  const A();
}
class Test3<U extends A, V extends B> {
  final U x = const A(); //# 11: ok
}

because the result is a compile-time warning. 

This is changed behavior from earlier. Is the current behavior expected, then the test should be updated.

**Comment by eernstg** [comment] 2017-08-25 12:05
Adding a bit of context: We need to specify if/when the strong mode static analysis determines that a given expression has an exact type, and what that knowledge is used for. A typical case would be constant expressions, where the exact type is known at compile-time, but `new A()` could also be given an exact type when it is known statically that it invokes a generative constructor.

In the given context, a downcast from "exactly `A`" to `B` could be rejected because it is guaranteed to fail at run time. A downcast from "exactly `A`" to `U` would not be guaranteed to fail at run time (the value of `U` could be `A`), so it would be consistent with the approach taken elsewhere in Dart to allow that (except when `--no-implicit-casts` is specified, of course).

When we have a clear model for which expressions have exact types, and when that's used for what, we can adjust the tests to have the correct expectations.

**Comment by leafpetersen** [comment] 2017-08-25 17:18
The intention is that the error only be issued on casts that are guaranteed to fail.  A reasonable approximation of this is to only issue this error when the target type of the implicit cast is a ground type.  That would allow this cast.

**Comment by kmillikin** [comment] 2017-11-27 14:20
Related:

```dart
class A {
  const A();
}

class B extends A {
  const B();
}

// Snip...

// Will be instantiated with U=dynamic and V=dynamic.
class Test5<U extends A, V extends B> {
  final U x = const A(); //# 21: ok
  final U x = const B(); //# 22: compile-time error
  final V x = const A(); //# 23: ok
  final V x = const C(); //# 24: compile-time error
  final V x = const C.d(); //# 25: compile-time error
  const Test5();
}

use(x) => x;

main() {
  use(const Test1());
  use(const Test2<A, B>());
  use(const Test3<A, B>());
  use(const Test4<A, B>());
  use(const Test5());
}
```
#23 is a compile-time error in DDC, but a run-time error in DDK (DDC with the new common front end).

**Comment by lrhn** [comment] 2017-11-27 15:25
```dart
// Will be instantiated with U=dynamic and V=dynamic.
class Test5<U extends A, V extends B> {
```
This comment is incorrect for Dart 2, `dynamic` is not a valid type argument for `U` or `V`.
Most likely the class will be instantated to bounds: `Test5<A, B>`, otherwise the instantiation itself will be an error.

The assignment `final V x = const A();` should be a valid implicit down-cast. The static type of `const A()` is `A`, which is a supertype of the parameterized type `V` with bound `B`. A type variable is a subtype of its bounds, so `V` <: `B`, and `B` is a subclass of `A`.

(The static type system does *not* have a notion of "exact type", so it can't say for sure that `const A()` is not assignable to `V` - so it must follow the usual implicit downcast rules, and `A` *is* a supertype of `V`).

**Comment by eernstg** [comment] 2017-11-27 16:13
There are even more surprises in [this test](https://github.com/dart-lang/sdk/issues/30546#issuecomment-347194985): `const Test5()` is the only use of `Test5` that we can see, and it should be invoked with type arguments `<A, B>` based on the feature instantiate-to-bound (where we have had no disagreement at all on what instantiate-to-bound means for simple types like `A` and `B`).

But subtest 22 would then (during compile-time construction of the `Test5` for that subtest) initialize `x` whose type annotation has the value `A` with an instance of type `B`: That should succeed, but it is marked as `compile-time error`. So it isn't even a run-time failure which is guaranteed to occur, it's simply surprising. ;)

**Comment by eernstg** [comment] 2017-11-27 16:59
Trying to actually run it, I can see that the use of exact types in DDC _does_ play a role in Kevin's example after all, because DDC emits a compile-time error for subtest 21 (which is marked `ok`):
```
[error] The constructor returns type 'A' that isn't of expected type 'U'. (out/ReleaseX64/generated_tests/language_2/scratch_test_21.dart, line 13, col 15)
```
We may check the initialization of `final U x ... //# 21..` locally (that is, in a way that should be valid for both `const` and `new` invocations of the constructor): The initializer has type `A`, and the variable has a type `U` which is less-equal-than `A` according to the bound. So that's a plain downcast, and the only way we can make it a compile-time error is by considering `const A()` to have an exact type and then concluding that the downcast to `U` "will never succeed". That, again, is not quite true because `U` could be `A` (as it actually is in the invocation of `const Test5()` in `main`).

So this means that Kevin's example shows an issue with DDK in relation to const expressions (23), and it again shows the issue with DDC and exact types that gave rise to this issue in the first place.

**Comment by lrhn** [comment] 2017-11-28 14:14
I agree that `#21` should not be a compile-time error. 
The static types are `U extends A` and `A`, which is an implicit downcast, and the run-time types are `A` and `A`, so assignment succeeds.

And `#22`, `#24` and `#25` are strong-mode compile-time errors because the static types do not form a valid up- or down-cast. The 22 case is the most surprising because `U extends A` and `B` are unrelated subtypes of `A`  (statically, the parameterized type `U` is not the type `A`, it's an unknown subtype of `A`).
Likewise the static type `C` is not a related to `V extends B`.

**Comment by jmesserly** [comment] 2018-06-27 18:14
this still reproduces. should be a quick fix

**Comment by fishythefish** [comment] 2019-09-07 02:01
Closing since both CFE and analyzer seem to agree on disallowing these casts: https://dart-review.googlesource.com/c/sdk/+/115778

Feel free to re-open if this is premature.

**Closed by fishythefish** 2019-09-07 02:01 UTC
Labels: P2, analyzer-strong-mode, area-analyzer, language-strong-mode-polish, type-bug
