### ISSUE TITLE
apt-get fails on repository

### ISSUE THREAD

**Issue by Munchotaur** [dart-lang/sdk#31042] opened 2017-10-09 11:07 UTC
On running 'sudo apt-get upgrade' on my Mint 17.3 system I see the following error:

W: Failed to fetch https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

I think there have been recent certificate package updates in Mint so I went back to the Dart install instructions and tried to reimport the server certificate, just in case. That threw this error:

sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
[sudo] password for <myusername>: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
gpg: no valid OpenPGP data found.

Have I missed out on something along the way or is the certificate actually missing from the server?

**Comment by whesse** [comment] 2017-10-19 11:50
This is a duplicate of #30512

The repository we create is old-fashioned, and only has a Release file, not an InRelease file.  I am contacting the owner of the creator tool, to see how this can be fixed.

**Closed by whesse** 2017-10-19 11:50 UTC
Labels: area-infrastructure
