### ISSUE TITLE
"No published analyzer available for language version 2.12.0".   |   This requires the 'non-nullable' language feature to be enabled.

### ISSUE THREAD

**Issue by xSuperMu** [dart-lang/sdk#44418] opened 2020-12-07 22:13 UTC
my   pub spec.yaml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  json_serializable: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^7.1.0
  pedantic: ^1.4.0
  quiver: '>=0.21.0 <3.0.0'
  flutter_launcher_icons: ^0.8.1

I'm using both built_value & json_serializable in my app
and when I run:
flutter pub run build_runner build

I get this error:

**flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:166:25 - This requires the 'non-nullable' language feature to be enabled.**

Here's a screen shot
![Screen Shot 2020-12-08 at 12 12 49 AM](https://user-images.githubusercontent.com/17935590/101411735-28074580-38ea-11eb-9d8d-8d3d98cbf266.png)

Any help?

**Comment by emsaints** [comment] 2020-12-08 06:08
Seeing the same issue on latest Master branch.

**Comment by maks** [comment] 2020-12-24 07:08
This looks like a dupe of #44421, though I guess this one was technically filed first.

**Comment by acoutts** [comment] 2021-01-10 10:43
I was able to make build_runner work again with this dependency override in my pubspec.yaml:

```yaml
dependency_overrides:
  analyzer: ^0.41.1
```

**Comment by srawlins** [comment] 2021-03-18 14:49
An analyzer version has since been published.

**Closed by srawlins** 2021-03-18 14:49 UTC
Labels: area-analyzer
