### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by daoshud1** [dart-lang/sdk#34556] opened 2018-09-24 07:59 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

# Exception

Please append the contents of:
file://C:\Users\ws010\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\workspace\flutter\runhuawork], excluded: [D:\workspace\flutter\runhuawork\.idea, D:\workspace\flutter\runhuawork\.dart_tool, D:\workspace\flutter\runhuawork\.idea, D:\workspace\flutter\runhuawork\.pub, D:\workspace\flutter\runhuawork\build]}, clientRequestTime: 1537604560730}
FileSystemException: Exists failed, path = 'D:\workspace\flutter\runhuawork\build\app\intermediates\assets\debug\flutter_assets\fonts' (OS Error: 拒绝访问。
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by bwilkerson** [comment] 2018-10-03 21:55
I don't believe that `existsSync` is expected to throw an exception.

**Comment by srawlins** [comment] 2019-09-06 15:55
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/33106; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 15:55
Duplicate of https://github.com/dart-lang/sdk/issues/33106

**Closed by srawlins** 2019-09-06 15:55 UTC
Labels: analyzer-crash-report, area-library, type-bug
