### ISSUE TITLE
Misleading warning for `?? throw`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#24892] opened 2015-11-12 08:14 UTC
The code `x ?? throw 0` gives the following errors:

```
ERROR|SYNTACTIC_ERROR|...file.dart|3|8|Expected to find ';'
ERROR|SYNTACTIC_ERROR|...file.dart|3|8|Expected an identifier
```

This is misleading since the real solution to the errors is to add parentheses around the `throw 0` expression. 
Listing what you expect to find is great, but it should be complete then, and '(' is also possible here.

**Comment by askeksa-google** [comment] 2018-06-22 14:12
Will become a duplicate of https://github.com/dart-lang/sdk/issues/24891 when the analyzer integrates with the CFE.

**Comment by srawlins** [comment] 2020-06-08 21:00
And so it is done. Duplicate of #24891.

**Closed by srawlins** 2020-06-08 21:00 UTC
Labels: P2, analyzer-recovery, area-analyzer, type-enhancement
