### ISSUE TITLE
Weird error when running dart test

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#44114] opened 2020-11-09 03:35 UTC
Working against this null safe migrated code:
   https://github.com/timsneath/win32/tree/eb810f9e196282ef198beab3d2245300bae8f18a

```
[C:\src\win32] dart test
The `pub` command is deprecated. Run `dart pub` instead.
Dart 2.12.0-27.0.dev is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

[C:\src\win32] dart --version
Dart SDK version: 2.12.0-27.0.dev (dev) (Fri Nov 6 06:09:09 2020 -0800) on "windows_x64"
```

This is a weird message (why the warning message about deprecation)? /cc @mit-mit

**Comment by mit-mit** [comment] 2020-11-09 07:11
Duplicate of https://github.com/dart-lang/sdk/issues/44105

**Closed by mit-mit** 2020-11-09 07:11 UTC
Labels: NNBD, analyzer-nnbd-migration, type-bug
