### ISSUE TITLE
Misleading error when trying to spawn an isolate from a function which accesses local variables

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#48346] opened 2022-02-08 18:40 UTC
Repro program:

```dart
import 'dart:async';
import 'dart:isolate';

void main() async {
  var i = 0;
  void childIsolateFn(SendPort sendPort) {
    sendPort.send(i);
  }

  var receivePort = ReceivePort();
  var isolate = await Isolate.spawn(childIsolateFn, receivePort.sendPort);
}
```

This fails with the error `Invalid argument(s): Illegal argument in isolate message: (object is aReceivePort)`.

It seems valid that you can't refer to local variables in this case - but the error is very misleading and doesn't help you to diagnose the actual problem.

**Comment by mraleph** [comment] 2022-02-08 18:54
I think the error is correct. The closure ends up capturing ReceivePort due to current async/await implementation. The limitation on closures should have been lifted as the part of light weight isolates work.

**Comment by natebosch** [comment] 2022-02-08 19:19
> I think the error is correct.

It's correct, but I don't think it's very useful. The message was misleading for me - my interpretation was that the `message` argument to `isolate.spawn` was a `RecievePort`.

Can we add more context to the message?

Could we make it say something closer to:

```
Invalid `entrypoint` argument: Illegal value in state captured by closure: (object is a ReceivePort)
```

**Comment by jakemac53** [comment] 2022-02-08 22:34
> The message was misleading for me - my interpretation was that the `message` argument to `isolate.spawn` was a `RecievePort`.

Especially since you only see this fail on your call to `Isolate.spawn` but you can't inspect the actual implementation which is throwing. So it looks to you like you sent a `RecievePort` based on the but you didn't.

So the request here is just to throw a better error (if possible) - something that tells you that you passed a closure which is capturing some local variables which isn't allowed.

**Comment by mraleph** [comment] 2023-01-26 09:12
Duplicate of https://github.com/dart-lang/sdk/issues/48346

**Closed by mraleph** 2023-01-26 09:12 UTC
Labels: area-vm, library-isolate

**Comment by natebosch** [comment] 2023-01-26 16:53
@mraleph - did you intend to close as a duplicate of a different issue?

**Comment by mraleph** [comment] 2023-01-27 08:55
Duplicate of #51115

**Comment by mraleph** [comment] 2023-01-27 08:55
Good catch @natebosch! Thanks.
