### ISSUE TITLE
Analyzer: can't restore Function param of method from cache

### ISSUE THREAD

**Issue by yury-yufimov** [dart-lang/sdk#33889] opened 2018-07-17 17:21 UTC
DartSDK: 2.0.0-dev.67.0
build_runner: 0.9.1
analyzer: 0.32.3

Issue: when our large project receives some changes, build_runner tries to rebuild it's entry point and fails with error
```
type 'DynamicElementImpl' is not a subtype of type 'GenericFunctionTypeElementImpl'

#0      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:10121:64)
#1      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5849:20)
#2      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11442:12)
#3      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121:10)
#4      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10285:18)
#5      UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228:7)
#6      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11437:15)
#7      FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4468:17)
#8      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121:10)
#9      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10285:18)
#10     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3011:53)
#11     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4463:49)
#12     TypeResolverVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:9985:16)
#13     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7457:11)
#14     TypeResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:9931:11)
#15     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1914:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8264:20)
#17     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2513:21)
#18     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121:10)
#19     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10285:18)
#20     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949:51)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2506:49)
#22     ResolveUnitTypeNamesTask.internalPerform (package:analyzer/src/task/dart.dart:5123:10)
#23     AnalysisTask._safelyPerform (package:analyzer/src/task/api/model.dart:323:9)
#24     AnalysisTask.perform (package:analyzer/src/task/api/model.dart:222:7)
#25     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:285:10)
#26     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:22)
#27     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:722:14)
#28     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:690:12)
#29     AnalyzerResolver.libraryFor (package:build_resolvers/src/resolver.dart:108:21)
<asynchronous suspension>
```

Some digging showed, that errors are always caused by pieces of code like
```
T Function(S0) pureProxy1<T, S0>(T Function(S0) fn) {
...
```
which have Function literal as parameter.

Unfortunately, I couldn't reproduce that on synthetic project. 
But I've found difference in our project and test one:
when analyzer resolves library for buildStep, it calls
https://github.com/dart-lang/sdk/blob/analyzer-0.32.1/pkg/analyzer/lib/src/task/dart.dart#L1071
(uses context cache) in our project.
Somewhy I couldn't reproduce this in test-project.
Then code executes as follows (stackTrace):
```
DeclarationResolver.visitFunctionDeclaration (declaration_resolver.dart:324)
FunctionDeclarationImpl.accept (ast.dart:5279)
NodeListImpl.accept (ast.dart:8264)
CompilationUnitImpl.visitChildren (ast.dart:2513)
RecursiveAstVisitor.visitCompilationUnit (visitor.dart:707)
CompilationUnitImpl.accept (ast.dart:2506)
DeclarationResolver.resolve (declaration_resolver.dart:71)
BuildCompilationUnitElementTask.internalPerform (dart.dart:1071)
AnalysisTask._safelyPerform (model.dart:323)
AnalysisTask.perform (model.dart:222)
AnalysisDriver.performWorkItem (driver.dart:285)
AnalysisDriver.computeResult (driver.dart:110)
AnalysisContextImpl.computeResult (context.dart:722)
AnalysisContextImpl.computeLibraryElement (context.dart:690)
AnalyzerResolver.libraryFor (resolver.dart:108)
<asynchronous gap>
```
And it occurs, that found `ExecutableElement element`'s parameter has null type

**Comment by kevmoo** [comment] 2018-07-17 20:07
CC @natebosch @jakemac53 @grouma RE pkg:build issue

**Comment by natebosch** [comment] 2018-07-30 22:47
I'm not sure if or how the build system is involved.

**Comment by bunopus** [comment] 2018-08-09 21:55
In addition to what Yuri wrote about, we dug out a few details.
I recorded video with reproduce in the synthetic environment, [YouTube](https://youtu.be/-HEk3C_yVmY), [Test Repo](https://github.com/bunopus/analyzer_test)

----
### Text explanation:

We have some file, called `tmp_class.dart`. And there is one line in it that looks like this
```dart
    String Function(dynamic, String) prop;
    ...
```
The analyzer goes through this file like this:

1) Run **TASK_1** `BuildCompilationUnitElementTask` ([code](https://github.com/dart-lang/sdk/blob/analyzer-0.32.1/pkg/analyzer/lib/src/task/dart.dart#L1002)) for the first time. Code looks like [this](https://github.com/dart-lang/sdk/blob/analyzer-0.32.1/pkg/analyzer/lib/src/task/dart.dart#L1044):
```dart
    //...
    CompilationUnit unit = getRequiredInput(PARSED_UNIT_INPUT_NAME);
    //...
    //
    // Try to get the existing CompilationUnitElement.
    //
    CompilationUnitElement element;
    {
      //...
      element = analysisCache.getValue(target, COMPILATION_UNIT_ELEMENT);
      if (element == null &&
          internalContext.aboutToComputeResult(
              cacheEntry, COMPILATION_UNIT_ELEMENT)) {
        element = analysisCache.getValue(target, COMPILATION_UNIT_ELEMENT);
      }
    }
    //
    // Build or reuse CompilationUnitElement.
    //
    if (element == null) {
        // if there is no element in cache - build it
        //...
    } else {
      new DeclarationResolver().resolve(unit, element);
    }
```  
After this task we check our expression type, and it's looks something like this:  

>unit.declarations[0].members[1].fields.type.type -> **_FunctionImplLazy**  
>element.fields..._declaredType -> **null**  

So we have both _unit_ and _element_ in cache, but _unit_ contains type information for our field and _element_ not. But it's okay (for now).  

2) Other tasks are running, and some of them cause `CacheFlushManager.flushToSize` execution ([code](https://github.com/dart-lang/sdk/blob/analyzer-0.32.1/pkg/analyzer/lib/src/context/cache.dart#L949)). For our big project this code starts to flush items from cache, and it flushes out _unit_. And it's okay too (for now).  

3) After that **TASK_1** (`BuildCompilationUnitElementTask`) runs again. It starts because some other tasks require our _unit_ by _gatherInputs_, but it's already flushed. And it starts to get smelly, because we don't have _unit_ in cache, so it's creating again, BUT without type information. So as a result we have  

>unit.declarations[0].members[1].fields.type.type -> **null**  
>element.fields..._declaredType -> **null**

4) Then **TASK_2** `ResolveUnitTypeNamesTask` ([code](https://github.com/dart-lang/sdk/blob/analyzer-0.32.1/pkg/analyzer/lib/src/task/dart.dart#L5074)) starts. It tries to get type information from _element_ -> fails, and it sets type to _unit_ as `UndefinedTypeImpl`.  

5) Then **TASK_1** runs third time. It takes type information from _unit_ and sets type to _element_ as as `UndefinedTypeImpl`  

8) **TASK_2** runs for the last time. It sees `UndefinedTypeImpl` everywhere and goes crazy -> we get Exception.  

As a result. We think that there is some interference between runs of `BuildCompilationUnitElementTask` for the first and the second time. And the problems that we have something in cache, that is not processed by `ResolveUnitTypeNamesTask`. And cache flushing leads to some problems with that.

**Comment by yury-yufimov** [comment] 2018-08-10 10:32
@bwilkerson , I think, your TODO in ResolveUnitTypeNamesTask#buildInputs describes the same problem, that causes our bug

>    // TODO(brianwilkerson) This task updates the element model to have type
    // information and updates the class hierarchy. It should produce a new
    // version of the element model in order to record those changes.

**Comment by bwilkerson** [comment] 2018-08-10 14:57
I had missed several of the comments above.

@natebosch wrote:

> I'm not sure if or how the build system is involved.

The issue appears to exist when using the old task model approach to analysis. I would guess, then, that the build system uses the task model.

The task model was superseded by the analysis driver approach, and the analysis driver approach is going to be replaced by the new analyzer API, which will be used when analysis is implemented by the CFE.

Given how old it is, there are currently no plans to fix bugs in the task model. I'd suggest moving package:build to the new analyzer API, but as we've discussed before I don't think the new API is quite mature enough. (I hesitate to suggest moving to the analysis driver as an intermediate state because of the extra work involved in re-writing code twice.)

We need to determine the priority of this bug compared to other work and consider possible paths forward.

**Comment by yury-yufimov** [comment] 2018-08-10 15:09
@bwilkerson , what do you think about this fast hack-fix?

Mark CompilationUnitElement, was it handled by ResolveUnitTypeNamesTask or not. 
If not - do not use it as cache in BuildCompilationUnitElementTask.

**Comment by bwilkerson** [comment] 2018-08-10 16:18
Talk about a leaky abstraction! Even from a perspective of being expedient, I can't say that I'm fond of the idea of adding a deprecated member to `CompilationUnitElement` to fix a bug in code that shouldn't be used. :-)

That said, if the code in `BuildCompilationUnitElementTask` is being executed, then I think it's safe to assume that the `CompilationUnitElement` was produced by `ResolveUnitTypeNamesTask`, so there isn't any need to mark the element.

But honestly, the task model has bigger issues that this one bug. It does not correctly support Dart 2 semantics in some potentially important ways. Fixing it would require way more effort than it's worth, given that it's already been replaced and its replacement is about to be replaced.

**Comment by yury-yufimov** [comment] 2018-08-10 16:38
Just for clarification: 
`CompilationUnitElement` is produced by `BuildCompilationUnitElementTask` itself. `ResolveUnitTypeNamesTask` only updates type information in it. 

But I understand your arguments. The question is, what should we do to be able to use build_system and Dart2.0 in our project?

**Comment by bwilkerson** [comment] 2018-08-10 16:46
> ... what should we do to be able to use build_system and Dart2.0 in our project?

So to be clear, the task model support the syntax and most of the semantics of Dart 2, but is missing some portions (IIRC, for example, it doesn't perform type inference correctly). That's why I said "potentially important". Whether this will impact your use depends on what information you're depending on.

The only way that I can think of to get full Dart 2 support is for package:build to move to the driver implementation, preferably via the new API. I don't know whether that's feasible at this point in time.

**Comment by bunopus** [comment] 2018-08-10 21:39
Sorry to interrupt, but let me clear this out: our team is trying to migrate our huge codebase to Dart 2. We spent already something about 30 human-months to do that, and this bug is one of the few blockers that we have.
Why this is important for us? It takes something about 12 minutes to build our project without build cache. which is a lot for average user. Imagine if it happens three times in an hour. So we created cache machine, so users don't have to build whole project, only parts that they changed. With this bug they get an error in random moments of time (depends on what they changed) and they have to rebuild whole project and wait for twelve minutes. 
Unfortunately i don't know analyzer or builder code well and i'm unable to discuss possible fix here. Maybe solution is in the complete migration of the build system, i don't know.
But we have two options: wait for the fix (and we don't know any time estimations) or fork analyzer and put a dirty hacks there (bad way).
Sorry, i don't want to sound angry or what, but this migration added many gray hair to our heads :-)
Thank you in advance.
СС @kevmoo

**Comment by bwilkerson** [comment] 2018-08-10 22:13
@bunopus: I sincerely apologize if I gave you the impression that I do not care about your pain. Quite the opposite! I wish that we had made the migration process much smoother, both for you and others. I am merely attempting to figure out the best path forward to address this issue.

I know something of what the options are from the analyzer side, but I do not know what the options are from the build side. Hopefully @natebosch can provide some information.

**Comment by matanlurey** [comment] 2018-08-13 21:37
Hi @bunopus @yury-yufimov:

Could you help answer some questions so we can help guide you and the analyzer folks?

* [ ] What version of the Dart SDK are you using today?
* [ ] Are you able to start using 2.0.0-stable (or newer) if it has analyzer fixes in it?
* [ ] Are you planning on keeping your fork of the build system indefinitely?
  - If so, how will it stay/become compatible with newer fixes and Dart 2.0.0?

**Comment by yury-yufimov** [comment] 2018-08-14 10:16
Hi @matanlurey ,
- Issue is actual for us with DartSDK 2.0.0-dev.69.5, build_runner 0.10.0, build_runner_core 0.3.0, analyzer 0.32.4
- We are going to upgrade to 2.0.0-stable. I think it'll happen within a month
- Our fork of build system quite small optimizational changes. I don't think merge of the upstream will be difficult.
- We'll be able to reject our changes in build system when it's performance will be suitable for our project. It's not the case now. For example, now we are working on "scratch-space via symlinks" decision

**Comment by matanlurey** [comment] 2018-08-14 14:04
Thanks @yury-yufimov! That helps a lot.

So it sounds like potential fixes using the new analyzer frontend might automatically solve this issue, but I don't know how long in the tooth that problem is. The good news if we _did_ back-port a fix it would be applicable to you.

**Comment by yury-yufimov** [comment] 2018-08-14 18:02
Thank you, @matanlurey .
Let me know when there will be any certainty in plans

**Comment by matanlurey** [comment] 2018-08-14 19:00
Ultimately it is not up to me unfortunately.

**Comment by yury-yufimov** [comment] 2018-08-18 14:47
@kevmoo , @matanlurey , @natebosch , @bwilkerson , here are some news from our side:
It seems, that we've managed to create dirty hack-fix for described situation. So far, bug isn't reproduced anymore (but it still requires deeper testing ).
I understand these changes won't probably be merged into master any way, but I share this with 2 purposes:
1) Could you please review pull-request and tell, whether it's safe to use it in daily-development / production, or it's very bad idea? 
We are on a crossroad now - whether to continue migration to Dart2.0, or to suspend that work, until you migrate build system to newer analyzer API /  frontend / etc
2) Someone with project of similar size can face same problem - may be these fixes will be an option for him...

**Comment by matanlurey** [comment] 2018-08-18 18:03
So like you guessed I think it's unlikely we'd merge this patch. Ultimately whether it is (temporarily) safe to rely on would be up to Brian - I know the analyser is changing quite a bit right now to start using the common front-end for parsing - and potentially new language features (mixin syntax) could mean even more challenges to keep in sync.

I also don't know exactly how close (or not) we are to using the "new" driver/front-end _for_ the build system - last I heard there might be a compatibility shim created for the time being.

Obviously if this patch works for you right now and you are comfortable with a dependency override for your developers do it - I guess worst case you fall back to the mainline branch and deal with worse build times until everything is up to date.

**Comment by bwilkerson** [comment] 2018-09-27 20:55
I'm closing this as stale. We've been off the task model for quite a while.

**Closed by bwilkerson** 2018-09-27 20:55 UTC
Labels: analyzer-package, area-analyzer, p1-high

**Comment by yury-yufimov** [comment] 2018-10-18 09:32
@bwilkerson , am I right, that this bug is fixed in analyzer 0.33.0 and build_runner 1.0.0?

**Comment by bwilkerson** [comment] 2018-10-18 14:00
I'm fairly certain that the bug has been fixed, but I don't know which version of the package first contained the fix.

**Comment by natebosch** [comment] 2018-10-18 22:19
Tracking the build migration to AnalysisDriver at https://github.com/dart-lang/build/issues/1886
