### ISSUE TITLE
O(1) send/recv data across isolates, possibly by "move" semantics, in more general cases

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#50278] opened 2022-10-23 05:44 UTC
I am considering whether this is possible (and may be related to https://github.com/dart-lang/sdk/issues/49468).

Surely, we should not *share* mutable objects across isolates otherwise we need locks - violating Dart fundamentals. But if we move from one isolate to another, looks possible?

Just very draft idea and want to post here in case someone have some other ideas :)

**Comment by aam** [comment] 2022-10-24 02:42
https://api.flutter.dev/flutter/dart-isolate/Isolate/exit.html provides one solution to the problem of "moving" data between isolates.
Sender isolate exiting provides a solution to the problem of ensuring that sender doesn't access "moved" data.

**Comment by fzyzcjy** [comment] 2022-10-24 02:45
@aam I agree (and that is O(1)). Just thinking about whether we can do something more general indeed.

**Comment by mraleph** [comment] 2022-10-24 06:47
Duplicate of #49587

**Comment by mraleph** [comment] 2022-10-24 06:47
Let's keep just one issue open for this.

**Closed by mraleph** 2022-10-24 06:47 UTC
Labels: area-vm, library-isolate

**Comment by fzyzcjy** [comment] 2022-10-24 06:49
Ah great to see that discussion!
