### ISSUE TITLE
unnecessary_import hint is not reported with single element import

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#49505] opened 2022-07-22 13:49 UTC
```dart
import 'a.dart' show A1;
import 'a.dart';

A1? a1 = null;
// A2? a2 = null;
```

In the code above, there should be an _unnecessary_import_ warning on one of the 2 imports (likely the second line because the first line is more tighten). 

Note that if we uncomment the last line a _unnecessary_import_ warning appears on the first line.

```
$ dart --version
Dart SDK version: 2.17.5 (stable) (Tue Jun 21 11:05:10 2022 +0200) on "linux_x64"
```

**Comment by bwilkerson** [comment] 2022-07-22 15:37
@srawlins

**Comment by srawlins** [comment] 2022-07-22 15:43
Those two imports provide the same set of used elements. In this case one is redundant. The issue for reporting redundant imports is https://github.com/dart-lang/sdk/issues/44569.

**Comment by srawlins** [comment] 2022-07-22 15:43
Duplicate of https://github.com/dart-lang/sdk/issues/44569

**Closed by srawlins** 2022-07-22 15:43 UTC
Labels: area-analyzer, P3, analyzer-hint
