### ISSUE TITLE
Analyzer Feedback from IntelliJ: Could not initialize the library map

### ISSUE THREAD

**Issue by Masksam** [dart-lang/sdk#33602] opened 2018-06-25 00:49 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `1.24.2`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\Endeavor\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Could not initialize the library map from [E:\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart, E:\sdk\lib\_internal\libraries.dart]

FileSystemException(path=E:\sdk\lib\_internal\libraries.dart

**Comment by devoncarew** [comment] 2018-09-04 20:10
Thanks for the report! Closing due to the older sdk version.

**Comment by lambdabaa** [comment] 2019-08-12 17:13
Analyzer Feedback from IntelliJ
Version information
- IDEA IU-191.7141.44
- Dart SDK 2.5.0-dev.2.0
- IU-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Linux(amd64) v4.19.37-5+deb10u1rodete1-amd64, screens 3840x2160

Exception
Dart analysis server, SDK version 2.5.0-dev.2.0, server version 1.27.2, error: Could not initialize the library map from [/usr/local/google/home/ariaye/sdk/lib/_internal/sdk_library_metadata/lib/libraries.dart, /usr/local/google/home/ariaye/sdk/lib/_internal/libraries.dart]

FileSystemException(path=/usr/local/google/home/ariaye/sdk/lib/_internal/libraries.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:623:41)
#3      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:493:18)
#4      ContextBuilder.findSdk. (package:analyzer/src/context/builder.dart:411:36)
#5      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
#6      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:146:19)
#7      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:410:23)
#8      ContextBuilder.createSourceFactory (package:analyzer/src/context/builder.dart:288:19)
#9      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:185:16)
#10     ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:773:48)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1154:19)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1216:16)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:756:9)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:500:22)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:319:16)
#17     AnalysisServer.handleRequest.. (package:analysis_server/src/analysis_server.dart:325:45)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     AnalysisServer.handleRequest. (package:analysis_server/src/analysis_server.dart:321:50)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1500:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#25     ByteStreamServerChannel._readRequest. (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#28     ByteStreamServerChannel.listen. (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#54     _rootRunUnary (dart:async/zone.dart:1132:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#59     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#60     _StreamController._add (dart:async/stream_controller.dart:640:7)
#61     _StreamController.add (dart:async/stream_controller.dart:586:5)
#62     _Socket._onData (dart:io-patch/socket_patch.dart:1789:41)
#63     _rootRunUnary (dart:async/zone.dart:1136:13)
#64     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#68     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#69     _StreamController._add (dart:async/stream_controller.dart:640:7)
#70     _StreamController.add (dart:async/stream_controller.dart:586:5)
#71     new _RawSocket. (dart:io-patch/socket_patch.dart:1337:33)
#72     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:858:14)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#75     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)



Server log
```
1565629870871 <= {"event":"analysis.implemented","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","classes":[],"members":[]}}
1565629903935 => {"id":"10","method":"server.shutdown","clientRequestTime":1565629903934}
1565629903940 <= {"id":"10"}
1565629903996 started analysis server:
  /usr/local/google/home/ariaye/dart-sdk/bin/dart /usr/local/google/home/ariaye/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=IntelliJ-IDEA --client-version=IU-191.7141.44 --useAnal
1565629904439 <= {"event":"server.connected","params":{"version":"1.27.2","pid":43413,"sessionId":""}}
1565629904462 <= {"id":"0","result":{"version":"1.27.2"}}
1565629904463 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1565629904167}
1565629904463 => {"id":"2","method":"completion.setSubscriptions","params":{"subscriptions":["AVAILABLE_SUGGESTION_SETS"]},"clientRequestTime":1565629904167}
1565629904463 => {"id":"3","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1565629904463 => {"id":"4","method":"edit.listPostfixCompletionTemplates","clientRequestTime":1565629904167}
1565629904463 => {"id":"5","method":"analysis.setAnalysisRoots","params":{"included":["/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart","/google/src/cloud/ariaye/ar
1565629904463 => {"id":"6","method":"analysis.setPriorityFiles","params":{"files":["/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart"]},"clientRequ
1565629904463 => {"id":"7","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/mai
1565629904463 => {"id":"8","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":51,"length":0},"
1565629904463 => {"id":"9","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},"
1565629904463 => {"id":"10","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904463 => {"id":"11","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904463 => {"id":"12","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904463 => {"id":"13","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904463 => {"id":"14","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904463 => {"id":"15","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904463 => {"id":"16","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904478 <= {"id":"1"}
1565629904483 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[]}}
1565629904483 <= {"id":"2"}
1565629904485 <= {"id":"3"}
1565629904490 <= {"id":"4","result":{"templates":[{"name":"assert","key":".assert","example":"expr.assert -> assert(expr);"},{"name":"fori","key":".fori","example":"limit.fori -> for(var i = 0; i < li
1565629904597 => {"id":"17","method":"edit.getAssists","params":{"file":"/google/src/cloud/ariaye/ariaye-test-removing-statistician/google3/dart/tools/gdart/lib/src/main.dart","offset":20,"length":0},
1565629904671 <= {"event":"server.error","params":{"isFatal":false,"message":"Could not initialize the library map from [/usr/local/google/home/ariaye/sdk/lib/_internal/sdk_library_metadata/lib/librar

**Comment by lambdabaa** [comment] 2019-08-13 18:06
I can no longer reproduce but will reopen if I see this again.

**Closed by lambdabaa** 2019-08-13 18:06 UTC
Labels: P1-High, analyzer-crash-report, area-analyzer, type-bug
