### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by NarHakobyan** [dart-lang/sdk#38830] opened 2019-10-11 11:15 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.6ff8d2199da265e0aa2e3ca0b677956db3d42231`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.6ff8d2199da265e0aa2e3ca0b677956db3d42231, server version 1.27.3, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in ListLiteralImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ExpressionFunctionBodyImpl in FunctionExpressionImpl in ArgumentListImpl in MethodInvocationImpl in MethodInvocationImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:76:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6187:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:725:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:395:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6187:15)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#7      ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6832:15)
#8      RecursiveAstVisitor.visitListLiteral (package:analyzer/dart/ast/visitor.dart:1049:10)
#9      LinterVisitor.visitListLiteral (package:analyzer/src/lint/linter_visitor.dart:450:11)
#10     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6827:49)
#11     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7441:18)
#12     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#13     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:480:11)
#14     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7436:49)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#16     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#17     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#18     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#19     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6193:20)
#20     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#21     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:396:11)
#22     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6187:15)
#23     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7441:18)
#24     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#25     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:480:11)
#26     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7436:49)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#28     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#29     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#30     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#31     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6193:20)
#32     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#33     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:396:11)
#34     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6187:15)
#35     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7441:18)
#36     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1079:10)
#37     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:480:11)
#38     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7436:49)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#40     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#41     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:623:10)
#42     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#43     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6193:20)
#44     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:995:10)
#45     LinterVisitor.visitInstanceCreation...
```

For additional log information, please append the contents of
file:///private/var/folders/1j/yf_j0nsj1jl_1wl9y4683qg40000gn/T/report.txt.

**Comment by a-siva** [comment] 2019-10-11 15:55
Looks like a duplicate of https://github.com/dart-lang/sdk/issues/37879

**Closed** 2019-10-14 19:21 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
