### ISSUE TITLE
can not tip

### ISSUE THREAD

**Issue by mlch12333** [dart-lang/sdk#35428] opened 2018-12-17 09:27 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2 unknown, screens 1440x900, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/jb/nwygyk8n62gbr8wkb73bk2ym0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Failed to handle completion domain request: {id: 30, method: completion.getSuggestions, params: {file: /Users/mlch/Desktop/ZW/app_we_wedding/lib/pages/category/shop_detail.dart, offset: 17172}, clientRequestTime: 1545038784454}
NoSuchMethodError: The method 'substitute2' was called on null.
Receiver: null
Tried calling: substitute2(_List len:1, _List len:1)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      InterfaceTypeImpl.isDirectSupertypeOf (package:analyzer/src/dart/element/type.dart:1508:27)
#2      InterfaceTypeImpl.isMoreSpecificThan (package:analyzer/src/dart/element/type.dart:1591:16)
#3      TypeImpl.isSubtypeOf (package:analyzer/src/dart/element/type.dart:2583:12)
#4      OpType._computeRequiredTypeAndFilters.<anonymous closure> (package:analyzer_plugin/src/utilities/completion/optype.dart:217:29)
#5      LibraryElementSuggestionBuilder.visitClassElement (package:analysis_server/src/services/completion/dart/local_library_contributor.dart:58:30)
#6      AbstractClassElementImpl.accept (package:analyzer/src/dart/element/element.dart:126:53)
#7      ElementHandle.accept (package:analyzer/src/dart/element/handle.dart:467:59)

**Comment by stereotype441** [comment] 2018-12-20 17:32
Duplicate of #35233

**Closed by stereotype441** 2018-12-20 17:32 UTC
Labels: analyzer-server, area-analyzer
