### ISSUE TITLE
Analyzer+VSCode macro surprising caching

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#55028] opened 2024-02-27 10:47 UTC
I ran this one by Konstantin and he suggested that it looks like an analyzer plugin issue. @scheglov 

@DanTup what do you think, please?

Long story follows ;)

---

I am experimenting with making changes to

pkg/_fe_analyzer_shared/lib/src/macros/api/exceptions.dart

and viewing the JSON macro in VSCode

tests/language/macros/json

--I make a change to inject a string into all diagnostics

```
  DiagnosticException(Diagnostic diagnostic)
      : diagnostic = Diagnostic(
            DiagnosticMessage(diagnostic.message.message + '***10***'),
            diagnostic.severity);
```

then check the diagnostics in json_serializable_diagnostic_test.dart, so it's easy to see if the macro was rebuilt or not.

The symptom I am able to get to is that if I make an edit (outside VSCode!) to change the string, e.g. '10' -> '11', the diagnostic in VSCode does not change, even if I force the macro to rerun by changing json_serializable_diagnostic_test.dart.

To "unstick" it I tried removing ~/.dartServer and killing all dart processes, but that didn't work. It only worked to restart VSCode.

Then I find it hard to get into the "stuck" state again :) ... normally it reacts fine to my external changes. But, I think I found the trigger.

It's when I have pkg/_fe_analyzer_shared also opened in the same VSCode project, then make a change there to exceptions.dart, then close it, then make changes to the file outside VSCode.

My guess is that for the macro build exceptions.dart then gets pinned at the version of the file that was opened in VSCode, ignoring my external changes to it, until I restart VSCode.

**Comment by DanTup** [comment] 2024-02-27 10:59
@davidmorgan are you able to give precise steps for me to repro this? Starting with exactly which folders you have open and exactly what files you're modifying? (if the code isn't committed, you could send me a patch or push to Gerrit/GH and I'll pull from there).

Can you also confirm whether the file you're modifying outside of VS Code is still open in VS Code, and if so whether you see it reload the updated contents after the external modification?

**Comment by DanTup** [comment] 2024-02-27 12:31
I think I understood what you were doing, but I was unable to reproduce the issue. I opened the file in notepad and made changes and saved, and both the file and the diagnostics updated immediately in VS Code.

https://github.com/dart-lang/sdk/assets/1078012/41ce63ce-2a19-4504-b114-0a4d18dca3a7

I tried various combinations (updating in VS Code first, having the file closed, etc.) but nothing seemed to trigger the issue you're seeing **except** for having unsaved changes in the file in VS Code, but that's expected (since when you have an unsaved file in VS Code, VS Codes buffer is what the analyzer is using, and not what is on disk).

Am I doing something differently to you? Could you provide detailed steps that I can use to try to repro?

I was testing with the following SDK (this is the version of the analyzer that's running):

Dart SDK version: 3.4.0-edge.94e653fe0e26d5a4fd4b905517ec38d0b44d122e (main) (Tue Feb 27 08:07:00 2024 +0000) on "windows_x64"

And I was opening `pkg/_fe_analyzer_shared` and `tests/language/macros/json` in the workspace from SDK commit 94e653fe0e2

**Closed** 2024-02-27 14:19 UTC
Labels: area-analyzer

**Comment by DanTup** [comment] 2024-02-27 14:28
Odd.. Please do let me know if you see it again (ideally with steps to repro if you can)! :)

**Comment by davidmorgan** [comment] 2024-02-27 14:45
👍
