### ISSUE TITLE
NPE in CompletionDomainHandler.processRequest

### ISSUE THREAD

**Issue by padiamayur** [dart-lang/sdk#34811] opened 2018-10-16 11:19 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900`

# Exception

Please append the contents of:
file:///private/var/folders/rj/jhpwcsn14zs8_wgzjjzq0k1w0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Failed to handle completion domain request: {id: 20, method: completion.getSuggestions, params: {file: /Users/mayur/Documents/flutterprojects/category_widget/lib/category_route.dart, offset: 273}, clientRequestTime: 1539688695192}
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:185:49)
<asynchronous suspension>
#2      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:143:9)
#3      _rootRun (dart:async/zone.dart:1124:13)
#4      _CustomZone.run (dart:async/zone.dart:1021:19)
#5      _runZoned (dart:async/zone.dart:1516:10)
#6      runZoned (dart:async/zone.dart:1500:12)
#7      CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:140:12)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:750:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:746:50)

**Comment by padiamayur** [comment] 2018-10-16 11:20
Dart Analyzer Error
Encountered a Dart Analysis Server error.
Open issue submission form?

**Comment by stereotype441** [comment] 2018-10-23 04:12
Duplicate of #34298

**Closed by stereotype441** 2018-10-23 04:12 UTC
Labels: analyzer-server, area-analyzer, type-bug
