### ISSUE TITLE
WebStorm becomes entirely unresponsible if there are a lot of analyzer errors

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#28990] opened 2017-03-08 17:25 UTC
I just copied a few dozen smallish java files into my project and renamed them to *.dart, now WebStorm is entirely unresponsible since > 5 minutes. 
I think the analyzer should analyzing files if there are too many errors and only try to analyze them again after they are modified.
After about 10min WebStorm died with an out-of-memory error.

**Comment by alexander-doroshko** [comment] 2017-03-08 20:01
Hung WebStorm is more likely a WebStorm problem than the SDK's. Logs and auto-saved thread dumps may help (Help | Show Log).

**Comment by zoechi** [comment] 2017-03-09 08:19
Not sure if this contains all relevant files.
[idea_logs.zip](https://github.com/dart-lang/sdk/files/830166/idea_logs.zip)

**Comment by alexander-doroshko** [comment] 2017-03-09 09:39
Do you remember how many errors were generated by the Analysis Server? How many files with errors did you have? How many errors per file?

**Comment by alexander-doroshko** [comment] 2017-03-09 10:34
Maybe you can share a project to reproduce?

**Comment by zoechi** [comment] 2017-03-28 21:26
I wasn't able to work on this project again. It might be related with some general analyzer slowness that happened with Dart versions I used back then. I'll still try if I can reproduce.

**Comment by alexander-doroshko** [comment] 2017-03-29 09:57
@zoechi We have found one problem that could cause slowness when there are thousands of errors. It is already fixed in IntelliJ IDEA 2017.1 (171.3780.107), but unfortunately not yet fixed in WebStorm 2017.1 (171.3780.79). Dart plugin version doesn't matter, the problem was in the IntelliJ Platform. WebStorm 2017.1.1 EAP with the fix is expected later this week.

Also, as I can guess from your logs, you were working with more than one projects open and at some point got OutOfMemory and increased heap size to 2Gb. Not sure about this case, but in some cases too large heap decreases non-heap memory and may cause OOM or other memory problems as well. Normally heap within 1Gb is enough even for large projects. If you continue getting memory problems try to get memory snapshot and report it to JetBrains. In case of general slowness CPU snapshot may be of help as well. See also our [Reporting Performance Problems](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems) document.

I'm going to close this issue here. IDE should remain responsive regardless of the Analysis Server. If you face the problem again please report it to YouTrack with logs/thread dumps/maybe CPU or memory snapshots.

**Closed by alexander-doroshko** 2017-03-29 09:57 UTC
Labels: area-intellij

**Comment by zoechi** [comment] 2017-03-29 13:23
@alexander-doroshko The default memory settings always caused problems, therefore changed it to what I have now. My machine has plenty of RAM and there shouldn't be any OOM.
Any hints for optimizations are welcome though.
