### ISSUE TITLE
Closing stdin during cleanup of isolate is crashing Flutter Tests

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#29229] opened 2017-04-03 17:46 UTC
For stack trace see:

- [Windows](https://ci.appveyor.com/project/flutter/flutter/build/1.0.1265)
- [Linux](https://gist.github.com/goderbauer/10dee26d6cc56fdb2a1907f389219293)

This is blocking Flutter's roll to the newest Dart version (see https://github.com/flutter/flutter/pull/9151)

/cc @zanderso

**Comment by kevmoo** [comment] 2017-04-03 18:09
@goderbauer does this seem to be a new issue (regression) since your roll to dev.10.0?

CC @pq

**Comment by zanderso** [comment] 2017-04-03 18:14
This issue is happening as a result of https://github.com/dart-lang/sdk/commit/89dba57bcf6b5c6a28f9adee4b3f86195f64f6ae, which closed a socket leak.

The socket finalizer for one isolate is closing stdio handles. When the next isolate comes along and tries to use stdio handles, it fails because they are closed. I am working on a fix that will stop socket finalizers for stdio handles from closing the handles.

**Comment by zanderso** [comment] 2017-04-03 21:19
I have posted https://codereview.chromium.org/2791423002/ for review to address this. It appears as though there may also be an issue with the test package: https://github.com/dart-lang/test/issues/583.

**Closed** 2017-04-04 20:57 UTC
Labels: area-library, Customer-Flutter, library-io, S0 critical, Type: bug
