### ISSUE TITLE
VM seg faulting on co19/LanguageFeatures/Generic-functions-as-type-args/class_A03_t01

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#45480] opened 2021-03-26 00:19 UTC
The VM is currently exiting with exit code 11 and a segmentation fault on this test.

cc @a-siva

**Comment by a-siva** [comment] 2021-03-26 04:24
This is a duplicate of https://github.com/dart-lang/sdk/issues/45443

**Closed by a-siva** 2021-03-26 04:24 UTC
Labels: area-vm, closed-duplicate
