### ISSUE TITLE
Allow transfer of `Pointer` objects across isolates

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#50715] opened 2022-12-14 11:58 UTC
Our `Pointer` objects are no longer reified. We won't allow attaching finalizers to them. We may just represent them as unboxed integers in Dart.

Given that, it does seem reasonable we allow sending `Pointer` objects across isolates (since they are immutable, they can also be shared). If the message that is being sent includes a `Finalizable` we disallow sending the message anyway.

Currently people can still achieve it by taking `pointer.address` before sending and then re-construct the pointer on the other side.

(There's one caveat: If a message got sent but receiver dies or doesn't handle them, any messages are dropped. This dropping will not cause freeing of any memory (we have support on C side to do that, but not in `SendPort` api). But this problem seems orthogonal.)

/cc @mraleph @dcharkes

**Comment by dcharkes** [comment] 2022-12-14 13:15
Duplicate of:

* https://github.com/dart-lang/sdk/issues/50457

**Closed by dcharkes** 2022-12-14 13:15 UTC
Labels: area-vm, library-ffi
