### ISSUE TITLE
Cannot parse generic function expression call

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31059] opened 2017-10-10 18:07 UTC
```dart
main() {
  var lambdaCall = (<E>(E e) => e)<int>(3);
}
```

```kernel
library;
import self as self;

static method #main() → dynamic {
  throw "file:///test.dart:2:39: Error: Expected ';' before this.\n  var lambdaCall = (<E>(E e) => e)<int>(3);\n                                      ^";
}
```

Works fine in Analyzer and VM.
![image](https://user-images.githubusercontent.com/384794/31402533-1b97e8b8-adab-11e7-9781-50b503344bdd.png)

**Comment by peter-ahe-google** [comment] 2017-10-12 15:21
@scheglov do you have a specification for this?

**Comment by peter-ahe-google** [comment] 2017-10-12 15:22
This is a duplicate of #30208.

**Closed** 2017-10-12 15:22 UTC
Labels: area-front-end
