### ISSUE TITLE
Printing of single-element lists containing empty strings

### ISSUE THREAD

**Issue by jiahaog** [dart-lang/sdk#44143] opened 2020-11-11 00:26 UTC
We cannot differentiate between lists that are empty, and lists that contain a single element empty string. Illustrating with a quick example:

```dart
void main() {
  print([]); // []

  // Looks the same as the former.
  print(['']); // []
  
  // This is ok
  print(['', 'a']); // [, a]
  print(['a', '']); // [a, ]
}
```

**Comment by mraleph** [comment] 2020-11-11 08:30
Duplicate of #39798

**Closed by mraleph** 2020-11-11 08:30 UTC
