### ISSUE TITLE
const_eval_throws_exception error

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#36511] opened 2019-04-07 16:50 UTC
Consider the work-in-progress changes in https://github.com/flutter/flutter/pull/30646 in which I change Flutter's `Row` widget to have a `const` constructor.

In the associated test, I have the following code:

```dart
testWidgets('Row is const constructable', (WidgetTester tester) async {
  const Row(
    children: <Widget>[
      Text('Billable Hours'),
    ],
  );
});
```

When run over that code, the analyzer produces the following error:

```
  error • Evaluation of this constant expression throws an exception • test/widgets/row_test.dart:32:5 • const_eval_throws_exception
```

Yet when I run the test, it passes:

```
$ flutter test test/widgets/row_test.dart 
00:05 +28: All tests passed!                                  
```

* Dart VM version: 2.2.1-dev.3.0.flutter-None (Tue Apr 2 13:54:28 2019 +0000) on "macos_x64"

**Comment by vsmenon** [comment] 2019-04-08 14:42
Do we know if this is a regression?  (2.3 is already past due.)

**Comment by stereotype441** [comment] 2019-04-08 18:38
Found the problem.  It is not a regression.  Explanation to follow.

**Comment by stereotype441** [comment] 2019-04-08 19:51
Ok, there *is* an error in @tvolkert's code, which the analyzer successfully detects.  Unfortunately, the analyzer does a pretty horrible job of reporting *where* the error is (which is why I had to spend a few hours this morning sleuthing to even figure it out).  To make matters worse, the VM *fails to detect* the error at all, making it seem like the analyzer is at fault.

The error in @tvolkert's code is located here, in the constructor for the class `Flex`:

```
class Flex extends MultiChildRenderObjectWidget {
  const Flex({
    Key key,
    @required this.direction,
    this.mainAxisAlignment = MainAxisAlignment.start,
    this.mainAxisSize = MainAxisSize.max,
    this.crossAxisAlignment = CrossAxisAlignment.center,
    this.textDirection,
    this.verticalDirection = VerticalDirection.down,
    this.textBaseline,
    List<Widget> children = const <Widget>[],
  }) : assert(direction != null),
       assert(mainAxisAlignment != null),
       assert(mainAxisSize != null),
       assert(crossAxisAlignment != null),
       assert(verticalDirection != null),
       assert(crossAxisAlignment != CrossAxisAlignment.baseline || textBaseline != null), // ERROR
       super(key: key, children: children);
```
The line marked `// ERROR` is problematic because it attempts to compare two values of type `CrossAxisAlignment`.  You can't do this safely in a const constructor because that assertion has to be able to be evaluated as part of constant evaluation, and constant evaluation won't allow you to do equality comparison on values of non-primitive types.  (Note that once "constant update 2018" is enabled, the rules will be relaxed slightly: you'll be able to compare a value of a non-primitive type to `null`, but you still won't be able to compare two non-primitive values).

The reason the error is being reported at the site of the evaluation of `const Row(...)` is because `Row` extends `Flex`.  Unfortunately, the analyzer doesn't report anywhere near enough information to help the user understand what went wrong.  It just unhelpfully says that an exception was thrown.  I'll file a separate bug report to track that.

The other problem that's happening here is that the VM *does not* properly detect the bug.  It is allowing two enumerated values to be equality compared during constant evaluation without complaint.  I'll file a separate bug report to track that.

**Comment by stereotype441** [comment] 2019-04-08 20:09
Ok, I've filed #36526 to track the problem of the analyzer not giving enough information about the location of the error, and #36528 to track the problem of the VM failing to detect the error.  Since the analyzer is correct in reporting an error, I'm closing this bug.

**Closed by stereotype441** 2019-04-08 20:09 UTC
Labels: analyzer-constants, area-analyzer, customer-flutter, p1-high, type-bug

**Comment by dnfield** [comment] 2019-04-09 04:35
Is this a case where if we used `identical` it would work? e.g. `!(identical(crossAxisAlignment, CrossAxisAlignment.baseline))`?

**Comment by stereotype441** [comment] 2019-04-09 11:57
> Is this a case where if we used `identical` it would work? e.g. `!(identical(crossAxisAlignment, CrossAxisAlignment.baseline))`?

@dnfield Yes!  Sorry, I should have mentioned that.  Switching to `identical` eliminates the error.

**Comment by dnfield** [comment] 2019-04-09 16:58
Thanks!  This seems relatedto https://github.com/dart-lang/sdk/issues/29278
