### ISSUE TITLE
Failed to handle completion domain request

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#25281] opened 2015-12-17 01:02 UTC
```
Dart analysis server, SDK version 1.14.0-edge.a0e0ac78cbb063582ff2a36dbf79dde90d4c6154, server version 1.14.0, error: Failed to handle completion domain request: {clientRequestTime: 1450314027019, params: {file: /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/generated/resolver.dart, offset: 299414}, method: completion.getSuggestions, id: 1198}
Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package:analyzer/src/context/context.dart:1999:7)
#1      AnalysisContextImpl._evaluatePendingFutures (package:analyzer/src/context/context.dart:1402:29)
#2      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1052:7)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188:15)
#4      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1051:49)
#5      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371:37)
#6      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:807:17)
#7      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#8      _rootRun (dart:async/zone.dart:903)
#9      _CustomZone.run (dart:async/zone.dart:802)
#10     _CustomZone.runGuarded (dart:async/zone.dart:708)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#12     _rootRun (dart:async/zone.dart:907)
#13     _CustomZone.run (dart:async/zone.dart:802)
#14     _CustomZone.runGuarded (dart:async/zone.dart:708)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:203)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
```

**Comment by alexander-doroshko** [comment] 2015-12-17 09:42
100% reproducible for me when running [DartServerCompletionTest#testFunctionAsArgument](https://github.com/JetBrains/intellij-plugins/blob/1ef831788f150cca78774cce83adbba4776565f7/Dart/testSrc/com/jetbrains/dart/analysisServer/DartServerCompletionTest.java#L78) test. Strange thing is that this test passes and DAS exception doesn't occur when the test is run individually. Neither it fails if the whole DartServerCompletionTest test class runs. But 100% failure if several test classes are run in a bunch.
I can attach server instrumentation log if needed.

**Comment by bwilkerson** [comment] 2016-02-04 22:30
Duplicate of #24271

**Closed by bwilkerson** 2016-02-04 22:30 UTC
Labels: area-analyzer, priority-high, Type-Defect
