### ISSUE TITLE
kernel code missing token location: crashes VM StackTrack toString in debug mode

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31287] opened 2017-11-06 19:13 UTC
test-crash.dart:
```
class D {
	bar() => throw 1;
}

main() {
	new D().bar();
}
```

compile (type `c`, then `q`):
```
─➤  out/DebugX64/dart --packages=.packages pkg/front_end/example/incremental_reload/run.dart --sdk-root=out/DebugX64/ test-crash.dart out.dill
Press a key to trigger a command:
   r:  incremental compile + reload
   c:  incremental compile w/o reload
   l:  reload w/o recompile
   q:  quit
#    Files     Files %      ------- Time -------------------------  Binary
     Modified  Sent  Total      Check Compile   Reload    Total      Avg   Size  
  1:        0      1  100%      0 ms  1293 ms     0 ms  1293 ms  1293 ms   364b
```

run produced out.dill
```
─➤  out/DebugX64/dart  --kernel-binaries=`pwd`/out/DebugX64 out.dill                                                                   1 ↵
../../runtime/vm/object.cc: 9494: error: expected: line_starts_array.Length() > 0
Dumping native stack trace for thread c47f
  [0x0000000000ac9527] dart::Profiler::DumpStackTrace(bool)
  [0x0000000000ac9527] dart::Profiler::DumpStackTrace(bool)
  [0x0000000000d94536] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x00000000009e3b47] dart::Script::GetTokenLocation(dart::TokenPosition, long*, long*, long*) const
  [0x0000000000a352ce] Unknown symbol
  [0x0000000000a34e9d] dart::StackTrace::ToDartCString(dart::StackTrace const&)
  [0x000000000082aad1] dart::BootstrapNatives::DN_Object_toString(_Dart_NativeArguments*)
  [0x00007f9f5c2c076c] Unknown symbol
  [0x00007f9f589e4ab0] Unknown symbol
  [0x00007f9f5c2c0b0c] Unknown symbol
  [0x000000000092b8df] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  [0x000000000092b566] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  [0x000000000092e088] dart::DartLibraryCalls::ToString(dart::Instance const&)
  [0x0000000000969fc2] dart::IsolateMessageHandler::ProcessUnhandledException(dart::Error const&)
  [0x0000000000969a2d] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x000000000099dc09] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x000000000099e393] dart::MessageHandler::TaskCallback()
  [0x000000000099ef63] Unknown symbol
  [0x0000000000b9fe9c] dart::ThreadPool::Worker::Loop()
  [0x0000000000b9fcf1] dart::ThreadPool::Worker::Main(unsigned long)
  [0x0000000000a65151] Unknown symbol
-- End of DumpStackTrace
[1]    50301 abort (core dumped)  out/DebugX64/dart --kernel-binaries=`pwd`/out/DebugX64 out.dill
```

**Comment by sigmundch** [comment] 2017-11-07 01:08
Note - this seems to only occur with the incremental compiler. In particular:

```
out/DebugX64/dart --dfe=utils/kernel-service/kernel-service.dart --kernel-binaries=out/DebugX64/ test-crash.dart 
```

works fine, but if you modify utils/kernel-service/kernel-service.dart and mark incremental as true, then the same command above will fail.

**Comment by sivachandra** [comment] 2017-11-22 20:58
Closing this issue as I am unable to reproduce this anymore.

**Closed by sivachandra** 2017-11-22 20:58 UTC
Labels: area-front-end, area-vm
