### ISSUE TITLE
Taking a snapshot of code that uses the new function syntax with annotations fails

### ISSUE THREAD

**Issue by apwilson** [dart-lang/sdk#33169] opened 2018-05-18 23:08 UTC
This works:

```dart
class Required {
  const Required();
}

const required = Required();

typedef void Fooo({
  @required int a,
  @required int b,
  @required int c,
});
```

This doesn't work:

```dart
class Required {
  const Required();
}

const required = Required();

typedef Fooo = void Function({
  @required int a,
  @required int b,
  @required int c,
});
```

I get a "type name expected" error on the first line that has an annotation.  If I remove annotations it works fine.

**Comment by leafpetersen** [comment] 2018-05-18 23:43
Note that both versions are accepted by the analyzer and by bleeding edge command line dart.  cc @zanderso

**Comment by zanderso** [comment] 2018-05-21 18:11
@apwilson you should be on a version of Dart that is only 5 days old: 6c3a861f8f8fb4f21510d2d934317ce1d7c72661, but can you CC me on a CL that I can patch in to see if the problem is fixed in a newer revision?

/cc @rmacnak-google

**Closed** 2019-02-20 23:52 UTC
Labels: area-vm
