### ISSUE TITLE
[Analyzer] Missing static error on an indirect implementation of a base class.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#52160] opened 2023-04-24 23:36 UTC
The static analysis section of the [class modifiers spec](https://github.com/dart-lang/language/blob/main/accepted/future-releases/class-modifiers/feature-specification.md#basic-restrictions) specifies that the error around implementing a base class from another library extends through the transitive closure of the super-declarations:

```
    A declaration implements another declaration, and the other
    declaration itself, or any of its super-declarations,
    are marked `base` or `final` and are not from the first declaration's
    library _(with some exceptions for platform libraries)_.

    _(You can only implement an interface if *all* `base` or `final`
    superdeclarations are inside your own library. Or if you're in
    a pre-feature library and all `base` or `final` superdeclarations
    are in platform libraries.)_

    More formally:
    A declaration *C* in library *L* has a declared interface *P*,
    and *P* has any superdeclaration *S*, from a library *K*,
    which is marked `base` or `final` _(including *S* being *P* itself)_,
    and neither:
    * *K* and *L* is the same library, mor
    * *K* is a platform library and *L* is a pre-feature library.
 ```

The analyzer does not seem to report this error, the following code produces no error when tested at current HEAD:

```
// lib.dart
base class C {}

// test.dart
import "lib.dart";
base class Base extends C {}
base class Nefarious implements Base  {}
```

We seem to currently have no test coverage for this error (and the related errors for final, and for the mixin and mixin class cases).

@munificent is working on adding tests, @dart-lang/language-team please help expedite reviews and landing here.

cc @kallentu @srawlins @bwilkerson @scheglov @itsjustkevin 

Tentatively marking this as a blocker for stable, let's plan on a cherry pick if at all possible.  If the fix looks like it will be hard to land in that time frame, we can discuss alternatives and possibly aim for the first patch release.

**Comment by sgrekhov** [comment] 2023-04-25 08:30
Duplicate of https://github.com/dart-lang/sdk/issues/52056 ?

**Comment by scheglov** [comment] 2023-04-25 18:21
I see that https://github.com/dart-lang/sdk/issues/52056 is assigned to @kallentu, so it looks to me that she is working on fixing it in the analyzer as well.
Correct me if this is not so.

**Comment by stereotype441** [comment] 2023-04-25 18:26
Kallen's on vacation this week so given that this is a blocker for stable, we probably shouldn't wait for her return 😃

**Comment by scheglov** [comment] 2023-04-25 19:34
https://dart-review.googlesource.com/c/sdk/+/298320

**Comment by leafpetersen** [comment] 2023-04-25 19:41
cc @goderbauer @zanderso as a heads up - this is a missing static error in both CFE and analyzer, there's a chance that we will need to do some fixup in flutter to roll this.

**Comment by zanderso** [comment] 2023-04-25 19:58
cc @jason-simmons the engine sheriff
cc @brianquinlan who I think is the VM gardener today.

**Closed** 2023-04-25 20:19 UTC
Labels: P1, area-analyzer
