### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by danasugu** [dart-lang/sdk#35246] opened 2018-11-22 16:05 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900, 1366x768`

# Exception

Please append the contents of:
file://C:\Users\DS\AppData\Local\Temp\report474.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [H:\FLUTERAPPS\firebasesandbox], excluded: [H:\FLUTERAPPS\firebasesandbox\.idea, H:\FLUTERAPPS\firebasesandbox\.dart_tool, H:\FLUTERAPPS\firebasesandbox\.idea, H:\FLUTERAPPS\firebasesandbox\.pub, H:\FLUTERAPPS\firebasesandbox\build]}, clientRequestTime: 1542902595709}
FileSystemException: Exists failed, path = 'H:\FLUTERAPPS\firebasesandbox\build\app\intermediates\transforms\dexBuilder\debug\52\com\google\firebase' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-11-30 18:09
Duplicate of #34294

**Closed by stereotype441** 2018-11-30 18:09 UTC
Labels: area-analyzer
