### ISSUE TITLE
No error reported for an invalid code

### ISSUE THREAD

**Issue by kinex** [dart-lang/sdk#44750] opened 2021-01-22 13:09 UTC
I wrote this by accident (extra parenthesis):

```dart
final homeViewModel = context.read()<HomeViewModel>();
```

The correct code is:
```dart
final homeViewModel = context.read<HomeViewModel>();
```
The `read` method is this https://pub.dev/documentation/provider/latest/provider/ReadContext.html

I would expect the first version results an error, but it compiles. If that is valid code, what does it mean?

Dart SDK version: 2.10.4 (stable)

**Comment by eernstg** [comment] 2021-01-22 14:15
The signature of `read` is `T read<T>()`, the invocation has no constraints (it is the receiver of a method invocation, and they get inferred in the empty context), so you get `context.read<dynamic>()<HomeViewModel>()`, so you're invoking an expression of type `dynamic` (which is allowed, no errors, but may be linted with [avoid_dynamic_calls](https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html)), and that will presumably fail at run time.

**Comment by eernstg** [comment] 2021-01-22 15:03
I'll close this issue because it is working as intended.

**Closed by eernstg** 2021-01-22 15:03 UTC
Labels: closed-as-intended

**Comment by kinex** [comment] 2021-01-22 15:55
Thanks for the clarification. It seems that whenever I find a strange behavior in Dart, there is always an explanation and a related lint to "fix" it.
