### ISSUE TITLE
Analyzer: no error for iterating over a final var in an outer scope

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#31942] opened 2018-01-18 23:25 UTC
This passes on bleeding edge:

```
main() {                                                                         
  final x = null;                                                                
  for (x in []) {                                                                
    x;                                                                           
  }                                                                              
} 
```

Should be an error, because it will reassign x, right?

**Comment by MichaelRFairhurst** [comment] 2018-01-18 23:27
Running this on the VM with some values in the array, we get

```
NoSuchMethodError: Cannot assign to final variable 'x='
#0      NoSuchMethodError._throwNew (dart:core-patch/dart:core/errors_patch.dart:192)
#1      main (file:///home/mfairhurst/dart/sdk/sdk/test.dart:3:8)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

which seems to confirm this should not be allowed.

**Comment by leafpetersen** [comment] 2018-01-18 23:43
I think a duplicate of https://github.com/dart-lang/sdk/issues/30483

**Closed by leafpetersen** 2018-01-18 23:43 UTC
Labels: Type: bug, area-analyzer, bug
