### ISSUE TITLE
same key get different value from a map

### ISSUE THREAD

**Issue by tcking** [dart-lang/sdk#59600] opened 2024-11-25 12:01 UTC
dart info

```
- Dart 3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "macos_arm64"
- on macos / Version 14.5 (Build 23F79)
- locale is zh-Hans-CN
```

Same key but different value from a map 

```dart
main() {
  Map<Function,Function?> mapper={};
  Map<String,String> cache={};
  String key = 'hello';
  String key2 = key.substring(0, 2) + key.substring(2);

  mapper[key2.compareTo]; // same as call key2.toString.hashCode,Key2.contains.hashCode

  cache[key] = 'Dart';


  print(key==key2); // True
  print(cache[key] == cache[key2]); // False

}
```

**Comment by mraleph** [comment] 2024-11-25 12:03
You have reported this before and it was fixed.

Duplicate of https://github.com/dart-lang/sdk/issues/56749

**Closed by mraleph** 2024-11-25 12:03 UTC
Labels: area-vm
