### ISSUE TITLE
Strong mode generic parameter's type not being propagated properly

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/sdk#29250] opened 2017-04-04 17:46 UTC
Dart Version: 1.22.1

It seems like the lower bound of a generic parameter is not being handled correctly.

https://dartpad.dartlang.org/71d1162ae99b73107e504b66a2029502

Locally I get a slightly more in depth warning message: 'Unsafe implicit cast from 'Component' to 'T'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime.'

**Comment by vsmenon** [comment] 2017-04-05 13:08
I believe this has been downgraded from a warning to a hint in 1.23. 

```dart
class A<T extends B> {
  T getBase() => getB();
}

class B {}

B getB() => new B();
```

Note, though, the hint is still meaningful is this code.  If you ever have a `class C extends B {}`, then any invocation of `getB` on `A<C>` will throw a runtime cast failure.  I think this is better typed as:
```
  B getBase() => getB();
```

**Comment by vsmenon** [comment] 2017-04-05 13:10
E.g., 
```dart
class A<T extends B> {
  T getBase() => getB();
}

class B {}

B getB() => new B();

class C extends B {}

void main() {
  var a = new A<C>();
  print(a.getBase());
}
```

Run the above in checked mode (`dart -c`).

**Comment by vsmenon** [comment] 2017-04-06 13:01
@jacehensley-wf what behavior are you expecting?  I think this is working as intended.

**Comment by jacehensley-wf** [comment] 2017-04-06 18:28
Hmm yeah, that makes sense to me now that you put it like that. Thanks for the explanation!

**Comment by vsmenon** [comment] 2017-04-06 19:11
Thanks for the feedback!  Closing this.

**Closed by vsmenon** 2017-04-06 19:11 UTC
Labels: area-language, Resolution: works as intended
