### ISSUE TITLE
`pub serve` throws with latest bleeding edge

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26282] opened 2016-04-17 11:29 UTC
dart-lang/pub#1407

**Comment by mit-mit** [comment] 2016-04-19 10:27
@whesse does this repro in 1.16 RC?

**Comment by zoechi** [comment] 2016-04-19 12:08
I can't reproduce with

> Dart VM version: 1.16.0-edge.dacf846df0447de2d4809a4f619f3ef00cbc1830 (Tue Apr 12 16:31:03 2016) on "linux_x64"

With the newest bleeding edge I get dart-lang/sdk#26295

**Comment by whesse** [comment] 2016-04-19 12:13
I don't know what package you are running pub serve on.  I run pub get and pub serve on sample_pop-pop-win, without a problem, for example, from version 1.16.0-dev.5.1.  But this may be because the error is not in that version, which branched from bleeding-edge on Wed Apr 13.

Please tell us what package to run this in, to reproduce the problem.

**Comment by whesse** [comment] 2016-04-19 12:14
We especially need to know if it reproduces in the dev channel build, which you can get from https://www.dartlang.org/downloads/archive/

**Comment by zoechi** [comment] 2016-04-19 15:08
I wasn't able to reproduce with

> Dart VM version: 1.16.0-dev.5.1 (Mon Apr 18 01:36:53 2016) on "linux_x64"

**Comment by mit-mit** [comment] 2016-04-25 17:56
Closing this again as it seems like handled this in https://github.com/dart-lang/sdk/issues/26295. @zoechi re-open with more details if not.

**Closed by mit-mit** 2016-04-25 17:56 UTC
Labels: pub-serve, S1 high
