### ISSUE TITLE
A function with a generic parameter does not accept a type that itself contains multiple generic parameters

### ISSUE THREAD

**Issue by ajrcarey** [dart-lang/sdk#28458] opened 2017-01-20 19:05 UTC
I'm sure there's a better way of describing it but easiest just to show the problem:

```
class Y<A, B> {}

class Z {

  void foo/*<T>*/(final int a) {
    print(a);
  }

  void bar() {
    this.foo<Y<int, int>>(5); // <=== compile time error here: ; expected, got ,
  }

}
```

An error is indicated by dart analyzer on the commented line. The type `Y<int, int>` is not accepted as a type parameter for function `foo<T>`. This is using SDK 1.22.0-dev.9.0 with strong mode on.

Possibly related is the problem that I cannot use the syntax

`void foo<T>(final int a) ...`

as this is also marked as a syntax error. I must always use the old pre-1.21 syntax with the generics in comments, i.e.

`void foo/*<T>*/(final int a) ...`

Are any changes to the analysis options file required in order to "switch on" the new `foo<T>` syntax? I'm wondering if it's just a configuration thing at my end.

**Comment by lrhn** [comment] 2017-01-23 06:54
This doesn't reproduce with tip-of-tree, so my best guess is that you are using a version of Dart from before the new syntax was introduced. Not being able to use `foo<T>(..)` matches this.

How are you analyzing the program? I can see that dartpad isn't up-to-date yet.

**Comment by floitschG** [comment] 2017-01-23 12:28
I downloaded 1.22.0-dev.9.0 and couldn't reproduce with that one either.

I tried to compile with dartdevc and to check it with the dartanalyzer.

Closing while waiting for more information.

**Closed by floitschG** 2017-01-23 12:28 UTC

**Comment by ajrcarey** [comment] 2017-01-23 12:33
Ok, sounds like it's something at my end. I'm going to do a complete purge and reinstall of Intellij. Thanks for taking the time to look into this!

**Comment by floitschG** [comment] 2017-01-23 15:16
If you run into this again, please do reopen the bug. If this is something on our end we really want to fix it. thanks.
