### ISSUE TITLE
Allow enum comparisons in const asserts

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#51199] opened 2023-02-01 08:04 UTC
The following code produces a static error because of the `bar != Moo.n2` in the assert:

```dart
void main() {
  const Foo(); // 🔥 error: Evaluation of this constant expression throws an exception. (const_eval_throws_exception)
}

@immutable
class Foo {
  const Foo({this.bar = Moo.n1}) : assert(bar != Moo.n2);
  final Moo bar;
}
enum Moo { n1, n2, }
```

If I change the assert to `assert(!identical(bar, Moo.n2))` the error goes away and everything seems to work as expected.

Is there any reason that comparisons with enum values are not allowed here? Seems like it should be allowed?

Also, if it isn't allowed, why am I getting the error when I try to const-construct the object instead of when I declare that the constructor is const? Giving the error on the const constructor would have been more helpful since (if the limitation regarding enum comparisons is intended) this class can never be const constructed and the const constructor is just misleading.

**Comment by goderbauer** [comment] 2023-02-01 08:04
We ran into this problem in Flutter: https://github.com/flutter/flutter/issues/119664

**Comment by eernstg** [comment] 2023-02-01 10:30
This is working as intended: Invocations of operator `==` in a potentially constant expression like `bar != Moo.n2` must turn into a constant expression after substitution of actual arguments for formal parameters (which in the given example yields `Moo.n1 != Moo.n2` which means `!(Moo.n1 == Moo.n2)`), and that operator can only be invoked on a special set of objects in a constant expression:

> either `e1` evaluates to an object that is an instance of
`int`, `double`, `String`, `bool` or `Null`, or if `e2` evaluates to the null object

There is a proposal that we should generalize `==` to handle all the cases which are supported for members of constant sets and keys of constant maps, cf. https://github.com/dart-lang/language/issues/1811, but that proposal has not yet been accepted into the language, and hence it hasn't been implemented.

So for now it must be done using `identical`.

**Comment by eernstg** [comment] 2023-02-01 10:36
I think the next step here would be to close the issue, given that the observed behavior follows the specification.

@goderbauer, please comment on https://github.com/dart-lang/language/issues/1811 in order to discuss or support the change proposed there, or open a new issue if something else hasn't been resolved.

**Closed by eernstg** 2023-02-01 10:36 UTC
Labels: closed-as-intended
