### ISSUE TITLE
Timeout for dev_fs_weird_char_test

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#31349] opened 2017-11-10 12:38 UTC
The buildbot ran into a timeout for `service/dev_fs_weird_char_test`:

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-kernel-linux-debug-x64-be%2F2458%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout

```
=== Failure summary:
FAILED: dartk-vm debug_x64 service/dev_fs_weird_char_test
Expected: Pass
Actual: Timeout
--- Command "vm" (took 02:00.000316s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --dfe=out/DebugX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/DebugX64 --no-background-compilation --error_on_bad_type --error_on_bad_override --no-enable-malloc-hooks --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/.packages /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/dev_fs_weird_char_test.dart
diagnostics:
Process list including children: [19425, 19475]
Trying to capture stack trace for pid 19425
PID 19425 - process
TID 19425:
#0  0x00007fac90cc1404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000000000a67279 dart::Monitor::WaitMicros(long)
#2  0x0000000000d6b97b Dart_RunLoop
#3  0x00000000006dedf5 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#4  0x00000000006df7e1 dart::bin::main(int, char**)
#5  0x00000000006dff79 main
#6  0x00007fac8fee5f45 __libc_start_main
#7  0x00000000006de029 _start
TID 19426:
#0  0x00007fac8ffc2693 epoll_wait
#1  0x00000000006e8cf5 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x000000000071243e dart::bin::ThreadStart(void*)
#3  0x00007fac90cbd184 start_thread
#4  0x00007fac8ffc1ffd __clone
TID 19427:
#0  0x00007fac90cc1404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000000000a67279 dart::Monitor::WaitMicros(long)
#2  0x000000000095ae1b dart::ThreadBarrier::Sync()
#3  0x000000000095a2bc dart::GCMarker::MarkObjects(dart::Isolate*, dart::PageSpace*, bool)
#4  0x0000000000a6b285 dart::PageSpace::MarkSweep()
#5  0x0000000000963103 dart::Heap::CollectOldSpaceGarbage(dart::Thread*, dart::Heap::GCReason)
#6  0x0000000000961e21 dart::Heap::AllocateOld(long, dart::HeapPage::PageType)
#7  0x00000000009a50df dart::Heap::Allocate(long, dart::Heap::Space)
#8  0x00000000009a90a3 dart::Object::Allocate(long, long, dart::Heap::Space)
#9  0x0000000000a31810 dart::Array::New(long, long, dart::Heap::Space)
#10 0x00000000009c1415 dart::Array::Grow(dart::Array const&, long, dart::Heap::Space)
#11 0x0000000000a07683 dart::ICData::FindFreeIndex(long*) const
#12 0x0000000000a06de5 dart::ICData::AddReceiverCheck(long, dart::Function const&, long) const
#13 0x0000000000b5088f dart::InlineCacheMissHandler(dart::GrowableArray<dart::Instance const*> const&, dart::ICData const&)
#14 0x0000000000b4625a dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments)
#15 0x00007fac9110064e
TID 19476:
#0  0x00007fac90cc4e44 wait
#1  0x00000000006f2548 dart::bin::ExitCodeHandler::ExitCodeHandlerEntry(unsigned long)
#2  0x000000000071243e dart::bin::ThreadStart(void*)
#3  0x00007fac90cbd184 start_thread
#4  0x00007fac8ffc1ffd __clone
TID 19543:
#0  0x00007fac90cc1404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000000000a67279 dart::Monitor::WaitMicros(long)
#2  0x000000000099933c dart::MonitorLocker::WaitWithSafepointCheck(dart::Thread*, long)
#3  0x000000000096259d dart::HeapIterationScope::HeapIterationScope(dart::Thread*, bool)
#4  0x0000000000a0d64d dart::Code::LookupCodeInIsolate(dart::Isolate*, unsigned long)
#5  0x0000000000acd8e5 dart::ProfilerStackWalker::Append(unsigned long)
#6  0x0000000000aca75a dart::ProfilerNativeStackWalker::walk()
#7  0x0000000000aca65c dart::Profiler::DumpStackTrace(unsigned long, unsigned long, unsigned long, bool)
#8  0x0000000000aca3f9 dart::Profiler::DumpStackTrace(void*)
#9  0x00000000006ecc1c dart::bin::segv_handler(int, siginfo_t*, void*)
#10 0x00007fac90cc5330 __restore_rt
#11 0x000000000095d3e7 dart::MarkingVisitorBase<true>::MarkObject(dart::RawObject*, dart::RawObject**)
#12 0x000000000095d2de dart::MarkingVisitorBase<true>::VisitPointers(dart::RawObject**, dart::RawObject**)
#13 0x0000000000b7ff61 dart::StackFrame::VisitObjectPointers(dart::ObjectPointerVisitor*)
#14 0x0000000000b9de0c dart::Thread::VisitObjectPointers(dart::ObjectPointerVisitor*, bool)
#15 0x0000000000ba194e dart::ThreadRegistry::VisitObjectPointers(dart::ObjectPointerVisitor*, bool)
#16 0x0000000000971016 dart::Isolate::VisitObjectPointers(dart::ObjectPointerVisitor*, bool)
#17 0x000000000095c287 dart::MarkTask::Run()
#18 0x0000000000ba101c dart::ThreadPool::Worker::Loop()
#19 0x0000000000ba0e71 dart::ThreadPool::Worker::Main(unsigned long)
#20 0x0000000000a66311 dart::ThreadStart(void*)
#21 0x00007fac90cbd184 start_thread
#22 0x00007fac8ffc1ffd __clone
TID 19544:
#0  0x000000000095c395 dart::MarkTask::Run()
#1  0x0000000000ba101c dart::ThreadPool::Worker::Loop()
#2  0x0000000000ba0e71 dart::ThreadPool::Worker::Main(unsigned long)
#3  0x0000000000a66311 dart::ThreadStart(void*)
#4  0x00007fac90cbd184 start_thread
#5  0x00007fac8ffc1ffd __clone
eu-stack: dwfl_thread_getframes tid 19427 at 0x7fac9110064d in /lib/x86_64-linux-gnu/ld-2.19.so: no matching address range
Trying to capture stack trace for pid 19475
PID 19475 - process
TID 19475:
#0  0x00007fcbf5a39404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000000000a67279 dart::Monitor::WaitMicros(long)
#2  0x0000000000d6b97b Dart_RunLoop
#3  0x00000000006dedf5 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#4  0x00000000006df7e1 dart::bin::main(int, char**)
#5  0x00000000006dff79 main
#6  0x00007fcbf4c5df45 __libc_start_main
#7  0x00000000006de029 _start
TID 19477:
#0  0x00007fcbf4d3a693 epoll_wait
#1  0x00000000006e8cf5 dart::bin::EventHandlerImplementation::Poll(unsigned long)
#2  0x000000000071243e dart::bin::ThreadStart(void*)
#3  0x00007fcbf5a35184 start_thread
#4  0x00007fcbf4d39ffd __clone
TID 19478:
#0  0x00007fcbf5a39404 pthread_cond_wait@@GLIBC_2.3.2
#1  0x0000000000a67279 dart::Monitor::WaitMicros(long)
#2  0x0000000000b9f9c9 dart::ThreadInterrupter::ThreadMain(unsigned long)
#3  0x0000000000a66311 dart::ThreadStart(void*)
#4  0x00007fcbf5a35184 start_thread
#5  0x00007fcbf4d39ffd __clone
stdout:
** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart -DDART_SERVICE_USE_AUTH=false --profiler --dfe=out/DebugX64/gen/kernel-service.dart.snapshot --kernel-binaries=out/DebugX64 --no-background-compilation --error_on_bad_type --error_on_bad_override --no-enable-malloc-hooks --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/vm-kernel-linux-debug-x64-be/build/sdk/runtime/observatory/tests/service/dev_fs_weird_char_test.dart
>testee>out> Observatory listening on http://127.0.0.1:54287/
** Signaled to run test queries on http://127.0.0.1:54287/
>testee>out> 
Loading VM...
stderr:
Dumping native stack trace for thread 4c57
--- Re-run this test:
python tools/test.py -c dartk -r vm --vm-options --no-enable-malloc-hooks service/dev_fs_weird_char_test
```

**Comment by a-siva** [comment] 2021-04-22 17:29
I looked at the current test results page for this test, it appears to be marked as flaky for the dartkp-weak-asserts-linux-debug-x64 configuration the last failure was for a different reason
```
../../runtime/vm/tagged_pointer.h: 32: error: expected: IsWellFormed()
version=2.12.0-edge.3bd63a4d529d21792300ae7dd3a32c239976089e (be) (Wed Jan 20 01:10:26 2021 +0000) on "linux_x64"
pid=4244, thread=4247, isolate_group=main(0x561f8ca47c00), isolate=main(0x561f8ca25000)
isolate_instructions=7fd84e57e000, vm_instructions=7fd84e57a000
  pc 0x0000561f8a61954c fp 0x00007fd84d57d8f0 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x0000561f8a2efd92 fp 0x00007fd84d57d9d0 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x0000561f8a55dba2 fp 0x00007fd84d57da10 dart::Object::CheckHandle() const+0x1a2
  pc 0x0000561f8a68e707 fp 0x00007fd84d57dad0 dart::StackTraceUtils::UnwindAwaiterChain(dart::Zone*, dart::GrowableObjectArray const&, dart::GrowableObjectArray const&, dart::CallerClosureFinder*, dart::ClosurePtr)+0x197
  pc 0x0000561f8a68ec07 fp 0x00007fd84d57dd00 dart::StackTraceUtils::CollectFramesLazy(dart::Thread*, dart::GrowableObjectArray const&, dart::GrowableObjectArray const&, int, std::__2::function<void (dart::StackFrame*)>*, bool*)+0x257
  pc 0x0000561f8a480fd6 fp 0x00007fd84d57dd50 out/DebugX64/dart_precompiled_runtime+0x792fd6
  pc 0x0000561f8a543d65 fp 0x00007fd84d57ddc0 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))+0xc5
  pc 0x00007fd84e57be27 fp 0x00007fd84d57ddf0 /b/s/w/ir/out/DebugX64/generated_compilations/dartkp-weak-asserts-linux-debug-x64/runtime_observatory_tests_service_dev_fs_weird_char_test/out.aotsnapshot+0x2e27
```

**Comment by a-siva** [comment] 2021-04-22 17:29
//cc @cskau-g

**Comment by cskau-g** [comment] 2021-05-11 11:30
I've looked into this, but I'm unable to reproduce or locate logs showing the issue happening.

@a-siva, where did pull the above snippet from?

**Comment by alexmarkov** [comment] 2022-11-11 18:48
Both `service/dev_fs_weird_char_test` and `service_2/dev_fs_weird_char_test` are currently passing on all configurations and not flaky.

**Closed by alexmarkov** 2022-11-11 18:48 UTC
Labels: area-vm, gardening
