### ISSUE TITLE
Flow analysis doesn't work after break in C-style for and while loops

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42039] opened 2020-05-25 08:33 UTC
The code examples are following
```dart
main() {
  late int i;
  for (int j = 0; j < 42; j++) {
    break;
    i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
This code must produce a compile-time error but it really produces only a hint about dead code in analyzer and runtime `LateInitializationError` in CFE

Another example that doesn't work is

```dart
main() {
  late int i;
  while (true) {
    break;
    i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
The above also produces only a hit and runtime error.

It's an interesting, that for-in and do-while loops work as expected (produce an expected error). Switch also works well.
So, the following code samples WORK well.

```dart
main() {
  late int i;
  var collection = [3, 1, 4, 1, 5];
  for (var j in collection) {
    break;
    i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
```dart
main() {
  late int i;
  do {
    break;
    i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
  } while (false);
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
```dart
main() {
  late int i;
  int j = 42;
  switch (j) {
    case 42:
      break;
      i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
    case 43:
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}

```
`Dart VM version: 2.9.0-10.0.dev (dev) (Tue May 19 15:16:48 2020 +0200) on "windows_x64" `

**Comment by leafpetersen** [comment] 2020-09-03 18:12
@eernstg I think this is a duplicate of a discussion happening elsewhere, yes?  If not please re-open.

**Closed by leafpetersen** 2020-09-03 18:12 UTC
Labels: area-front-end, type-bug

**Comment by sgrekhov** [comment] 2020-09-04 03:39
Cf. #42232
