### ISSUE TITLE
Collection code coverage (on Travis-CI, at least) now causes OOM exceptions

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#42819] opened 2020-07-23 18:29 UTC
2.10.0-0.0.dev – Linux

See

https://travis-ci.org/github/dart-lang/coverage/jobs/710959706#L244-L259
https://travis-ci.org/github/google/quiver-dart/jobs/710959371#L278-L293

```
../../runtime/platform/text_buffer.cc: 141: error: Out of memory.
version=2.10.0-0.0.dev (dev) (Wed Jul 22 19:58:38 2020 +0200) on "linux_x64"
pid=4514, thread=4519, isolate_group=vm-service(0x5646b827e580), isolate=vm-service(0x5646b826db00)
isolate_instructions=5646b5de1e60, vm_instructions=5646b5de1e60
  pc 0x00005646b6070efc fp 0x00007f8c93afd380 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x00005646b5de1f92 fp 0x00007f8c93afd460 dart::Assert::Fail(char const*, ...)+0x82
  pc 0x00005646b5de3012 fp 0x00007f8c93afd4a0 dart+0x1919012
  pc 0x00005646b5fd41d8 fp 0x00007f8c93afd4e0 dart::JSONWriter::PrintValue(char const*)+0xa8
  pc 0x00005646b5fb7f93 fp 0x00007f8c93afd510 dart::IsolateGroup::PrintToJSONObject(dart::JSONObject*, bool)+0x73
  pc 0x00005646b5fb7eff fp 0x00007f8c93afd540 dart::IsolateGroup::PrintJSON(dart::JSONStream*, bool)+0x2f
  pc 0x00005646b60d7909 fp 0x00007f8c93afd590 dart+0x1c0d909
  pc 0x00005646b5fb81fa fp 0x00007f8c93afd5e0 dart::IsolateGroup::ForEach(std::__2::function<void (dart::IsolateGroup*)>)+0xda
  pc 0x00005646b60cc812 fp 0x00007f8c93afd6e0 dart::Service::PrintJSONForVM(dart::JSONStream*, bool)+0x2b2
  pc 0x00005646b60d1e1e fp 0x00007f8c93afd6f0 dart+0x1c07e1e
  pc 0x00005646b60cae82 fp 0x00007f8c93afd850 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)+0x3a2
  pc 0x00005646b5fe9f10 fp 0x00007f8c93afd8c0 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))+0xa0
```

**Comment by kevmoo** [comment] 2020-07-23 18:30
@a-siva – seems a recent break

**Comment by bkonyi** [comment] 2020-07-24 00:03
Looks like it was probably caused by an invalid memory access causing us to read off the end of a buffer. Should be fixed by [this](https://dart-review.googlesource.com/c/sdk/+/155740).

**Closed** 2020-07-27 20:32 UTC
Labels: P2, area-observatory, area-vm
