### ISSUE TITLE
co19/Language/Classes/definition_t23 test fails (to compile with frontend)

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31624] opened 2017-12-13 03:36 UTC
```
FAILED: dartk-vm release_x64 co19/Language/Classes/definition_t23
Expected: Pass
Actual: CompileTimeError

--- Command "vm" (took 571ms):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --dfe=xcodebuild/ReleaseX64/gen/kernel-service.dart.snapshot --kernel-binaries=xcodebuild/ReleaseX64 --ignore-unrecognized-flags --packages=/Users/aam/projects/dart/sdk/.packages /Users/aam/projects/dart/sdk/tests/co19/src/Language/Classes/definition_t23.dart

exit code:
254

stderr:
'file:///Users/aam/projects/dart/sdk/tests/co19/src/Language/Classes/definition_t23.dart': error: line 28 pos 21: super type 'A1' may not be listed in implements clause of class 'I3'
@A() abstract class I3<T> = A1 with B1 implements A1;
                    ^

--- Re-run this test:
python tools/test.py -m release -c dartk co19/Language/Classes/definition_t23
```

It sounds like a legitimate compilation error though.

**Comment by lrhn** [comment] 2017-12-13 20:06
The supertype of `I3<T>` is `A1`, and the class also implements `A1`.  The spec does indeed say:

> It is a compile-time error if the superclass of a class *C* is specified as a superinterface of *C*.

(It should just say "as an interface of *C*", but otherwise it's pretty clear).

**Comment by kmillikin** [comment] 2018-01-04 10:42
So there's a bug in the source-based VM because it's missing the compile time error, and there's a bug in the co19 test itself.  But this is not a bug in the front end (nor Analyzer nor dart2js, judging from their co19 status files which all have CompileTimeError).

I filed https://github.com/dart-lang/co19/issues/129 against co19.  I assume the issue in the source-based VM will be won't fixed, so I'm not going to file it.  (Feel free to file an issue if you disagree.)

**Closed by kmillikin** 2018-01-04 10:42 UTC
Labels: area-front-end

**Comment by sgrekhov** [comment] 2018-01-09 09:03
@kmillikin I've tested Language/Classes/definition_t23 on dartanalyzer and dart2js under windows and Linux and there were no compile time error (SDK 2.0.0-dev.15.0 under Windows and 2.0.0-dev.14.0 under Linux). How can it be a compile error on a buildbot?
