### ISSUE TITLE
runtime/vm/profiler.cc: 1063: error: expected: fp_ != nullptr

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#53387] opened 2023-08-30 16:50 UTC
There are new test failures on [[vm/test] Avoid temporary changes to disassemble_optimized under TSAN....[analyzer] Change final locals to var in const evaluator.](https://github.com/dart-lang/sdk/compare/a193e7422d58712fd41b162a07d7ac90d96c136f~...d6e0590255f33eecc52f286162118a4e278698c8).

The tests
```
service/valid_source_locations_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
vm-win-debug-arm64
```

The test was flaky (so the failure is probably unrelated to the changes above) but recently started failing consistently.

Log:
```
--- Command "vm" (took 46.000818s):
set DART_CONFIGURATION=DebugARM64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=c:\opt\s\w\ir\cache\builder\sdk\out\DebugARM64\crashpad_handler.exe & out\DebugARM64\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\valid_source_locations_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: valid_source_locations_test.dart (VM Service)[0m

** Launching SERVICE_TEST_TESTEE=true out\DebugARM64\dart.exe --disable-dart-dev --write-service-info=file:///c:/opt/s/w/ir/x/t/dart_servicee69fc298/service_info.json --profiler --sound-null-safety -Dtest_runner.configuration=vm-win-debug-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json --enable-vm-service:0 C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\valid_source_locations_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:50920/fiVWqanAFzA=/

>testee>out> 

** Signaled to run test queries on http://127.0.0.1:50920/fiVWqanAFzA= (VM Service)

Loading VM...

Done loading VM

Running valid_source_locations_test.dart [1/2]

Paused with PauseBreakpoint

Running valid_source_locations_test.dart [2/2]

>testee>err> ../../runtime/vm/profiler.cc: 1063: error: expected: fp_ != nullptr

>testee>err> 

>testee>err> ===== CRASH =====

>testee>err> ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF79426050C

>testee>err> Aborting reentrant request for stack trace.

00:33 [32m+0[0m[31m -1[0m: valid_source_locations_test.dart (VM Service) [1m[31m[E][0m[0m

  NetworkRpcException(Canceling request: WebSocket closed(id: 1029 method: getObject params: {objectId: classes/1141/functions/set%3AmaxConnectionsPerHost, count: 100, isolateId: isolates/1242590195370515, _includePrivateMembers: true}))

  

** Killing script

00:33 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-arm64 service/valid_source_locations_test/service
```

https://dart-ci.appspot.com/log/vm-win-debug-arm64/vm-win-debug-arm64/245/service/valid_source_locations_test/service

/cc @bkonyi @rmacnak-google

**Comment by rmacnak-google** [comment] 2023-08-31 21:56
Duplicate of #52969

**Closed by rmacnak-google** 2023-08-31 21:56 UTC
Labels: area-vm, gardening
