### ISSUE TITLE
[CP][stable channel][beta channel] Fix handling of named parameter types in CFE when initialising from Kernel

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43797] opened 2020-10-15 08:11 UTC
**commit(s) to merge**: aa329dc0d05b398ce57057a0d2842b7167130845

**merge instructions**: clean merge

**What is the issue**: When initialising from Kernel binary CFE incorrectly handles types of named parameters when handling function types, leading it to use types of positional parameters at corresponding positions instead.

**What is the fix**: Fix the typo in the code to make it refer to the named parameters.

**Why cherrypick**: Fundamental bug, has potential to impact large number of users. 

**Risk**: Low, the fix is 1 line correction of a typo.

**Link to original  issue(s)**: https://github.com/flutter/flutter/issues/65324, https://github.com/flutter/flutter/issues/68092

/cc @dgrove @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @johnniwinther

**Comment by franklinyow** [comment] 2020-10-15 16:42
FYI @pcsosinski

**Comment by franklinyow** [comment] 2020-10-15 18:18
Approved in SCRUM

**Comment by athomas** [comment] 2020-10-22 15:17
Merged to beta in bba1aeca3a6062bbedb0147a39c093a9ff7291b2 (2.11.0-213.4.beta). The issue will be left open until merged to stable (there is no separate tracking issue for the merge-to-beta).

**Comment by llucax** [comment] 2020-10-22 20:45
Cool! So this is just the Dart side, right? It is still not shipped in any flutter channel yet or am I missing something (I just tried to verify if the fix works but it is still failing with the current flutter dev channe using Flutter 1.23.xl).

**Comment by athomas** [comment] 2020-10-22 20:54
Yes, it means Flutter could now cherry-pick that hash to Flutter. It will appear on Dart's standalone release channels tomorrow morning.

@pcsosinski I'm not sure how to answer the if/when this will reach Flutter users question.

**Comment by athomas** [comment] 2020-10-27 13:48
Merged to stable for 2.10.3 (ecf9ce8ef42de11033801b2870e8b310c3722902).

**Closed by athomas** 2020-10-27 13:48 UTC
Labels: area-front-end, cherry-pick-review, cp-approved, merge-to-beta, merge-to-stable

**Comment by llucax** [comment] 2020-11-02 12:16
This is fixed now in the [stable (using dart 2.10.3)](https://github.com/llucax/flutter-bug-65324/runs/1341905544?check_suite_focus=true#step:5:12) and [dev (using dart 2.11.0 build 2.11.0-260.0.dev)](https://github.com/llucax/flutter-bug-65324/runs/1341905580?check_suite_focus=true#step:5:12) channels.

The [beta channel (using dart 2.11.0 build 2.11.0-213.1.beta) seems to be still broken](https://github.com/llucax/flutter-bug-65324/runs/1341905567?check_suite_focus=true#step:5:12) though, not sure if that's an overlook or if it takes more time for changes in 2.11 to land there...

Thanks!

**Comment by llucax** [comment] 2020-11-02 12:17
And I can confirm this also fixes https://github.com/flutter/flutter/issues/65324.

**Comment by athomas** [comment] 2020-11-02 13:04
Re: Flutter beta: It's released in Dart `2.11.0-213.4.beta`,  Dart `2.11.0-213.1.beta` does not have the fix.
