### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by 55555Mohit55555** [dart-lang/sdk#31732] opened 2017-12-28 19:16 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `1.25.0-dev.11.0`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\mohit\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, error: Analysis failed: C:\Users\mohit\Desktop\what_hacker_knows\lib\main.dart
NoSuchMethodError: The getter 'lineStarts' was called on null.
Receiver: null
Tried calling: lineStarts
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:471)
#3      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:856)
#4      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:569)
#5      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:518)
#6      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:856)
#7      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:569)
#8      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:507)
#9      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:856)
#10     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:569)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:507)
#12     FileSystemSta

**Comment by matanlurey** [comment] 2017-12-29 18:59
Duplicate of https://github.com/dart-lang/sdk/issues/31734.

**Closed by matanlurey** 2017-12-29 18:59 UTC
Labels: Resolution: duplicate
