### ISSUE TITLE
Isolate/spawn_A04_t04 is failing

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#43454] opened 2020-09-16 20:03 UTC
co19/LibTest/isolate/Isolate/spawn_A04_t04 went from flaky to consistently failing on [vm-dartkb-linux-release-x64](https://dart-ci.appspot.com/log/vm-dartkb-linux-release-x64/dartkb-mixed-linux-release-x64/8732/co19_2/LibTest/isolate/Isolate/spawn_A04_t04). It's also failing on [other configurations](https://dart-ci.appspot.com/log/vm-kernel-nnbd-linux-debug-x64/dartk-weak-asserts-linux-debug-x64/2295/co19/LibTest/isolate/Isolate/spawn_A04_t04).

Due to flakiness, the culprit CL is not clear.

**Comment by aam** [comment] 2021-02-25 01:39
Duplicate of https://github.com/dart-lang/co19/issues/1003

**Closed by aam** 2021-02-25 01:39 UTC
Labels: area-library, library-isolate
