### ISSUE TITLE
Unfriendly error: "Write failed, port = 0"

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#25342] opened 2016-01-05 02:44 UTC
On a number of occasions, I've run into the error "Write failed, port = 0". It seems to have a number of causes, but one simple reproduction is to run the following code using `pub run` and then press Enter a few times (sending newlines on stdin):

``` dart
import 'dart:async';
import 'dart:io';

main() async {
  stdin.listen(print).cancel();

  await new Future.delayed(new Duration(seconds: 5));
}
```

The issue here isn't necessarily that there is an error, but that the error provides no information and is consequently very difficult to debug. Wherever this is coming from, would it be possible to add a stack trace? If this is indeed coming from low-level socket code, could higher-level code intercept it and add additional context? Currently Observatory seems completely unable to detect this—could we add some way for that to work?

I marked this as Area-IO because I've only seen this with IO APIs, but it's possible that it's a VM issue.

**Comment by lrhn** [comment] 2016-01-05 08:37
The reproduction does not work for me on Windows or Linux. What platform are you running on?

**Comment by nex3** [comment] 2016-01-05 21:10
This is on Linux with pub 1.14.0-edge.26af34a1b3a912f16f52c69723ca99789d88153b. However, I've reduced it further in #25348—the reproduction there doesn't require pub.

**Comment by skybrian** [comment] 2016-01-05 21:28
I just ran into this while trying out an analyzer stress test that launches a subprocess (which may have died; haven't figured it out yet).

**Comment by munificent** [comment] 2017-01-03 23:48
Ran into this today trying to run a simple "pub lish" on my Mac.

**Comment by pq** [comment] 2017-01-06 14:30
I hit this yesterday as well when trying to `pub lish` on OS X with `HEAD` and the latest dev build (`1.22.0-dev.5.0`).  Rolling back to 1.21 worked for me.

**Comment by munificent** [comment] 2017-01-06 17:02
Just to note, yes using an older version of Dart (I don't recall which one) fixed this for me too. I was getting the error on bleeding edge.

**Comment by bwilkerson** [comment] 2017-01-09 22:55
I am also seeing this on my Mac. Extra carriage returns are not required.

**Comment by floitschG** [comment] 2017-01-10 15:54
Does somebody have a repro for this?
For me the given example doesn't trigger either, and I believe the small example in #25348 got fixed, too.

@zanderso : do you know of any change that could cause this?

**Comment by bwilkerson** [comment] 2017-01-10 15:57
I reliably see it on my Mac. Just build an SDK from bleeding edge and try to use the version of 'pub' in the built SDK to publish a package.

**Comment by zanderso** [comment] 2017-01-10 16:48
One recent change is that we make sure that close() doesn't clobber errno if there was some previous error. The new code isn't on the codepath that generates this error message. Otherwise there hasn't been a change to this code (at least on Mac) since last April.

In the code path that can generate "Write failed" there should be a SocketException that contains a field osError, which should have been non-null, and should have contained the errno from the OS. This information should have been printed along with "Write failed".

**Comment by zanderso** [comment] 2017-01-12 21:39
I did a tiny bit more digging. This error string is only generated when a low-level write() syscall on a "socket" fails, where a socket could be a pipe like stdin. See _NativeSocket.write() in socket_patch.dart:

https://github.com/dart-lang/sdk/blob/master/runtime/bin/socket_patch.dart#L672

which is bubbled up from, e.g.:

https://github.com/dart-lang/sdk/blob/master/runtime/bin/socket_macos.cc#L152

The stack trace where we generate that error message after the write fails is:

```
_NativeSocket.write failed: OS Error: Broken pipe, errno = 32
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:672)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1317)
#2      _Socket._write (dart:io-patch/socket_patch.dart:1711)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:1482)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:1454)
#5      _rootRunUnary (dart:async/zone.dart:1158)
#6      _CustomZone.runUnary (dart:async/zone.dart:1037)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#11     _StreamController._add (dart:async/stream_controller.dart:635)
#12     _StreamController.add (dart:async/stream_controller.dart:581)
#13     _StreamSinkWrapper.add (dart:async/stream_controller.dart:868)
#14     createTarGz.<anonymous closure>.<<anonymous closure>_async_body> (package:pub/src/io.dart:1042)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#16     _rootRunUnary (dart:async/zone.dart:1158)
#17     _CustomZone.runUnary (dart:async/zone.dart:1037)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#20     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#21     _Future._complete (dart:async/future_impl.dart:467)
#22     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#23     startProcess.<anonymous closure>.<<anonymous closure>_async_body> (package:pub/src/io.dart:717)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#25     _rootRunUnary (dart:async/zone.dart:1158)
#26     _CustomZone.runUnary (dart:async/zone.dart:1037)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#28     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#29     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#30     _Future._completeWithValue (dart:async/future_impl.dart:477)
#31     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#32     _rootRun (dart:async/zone.dart:1150)
#33     _CustomZone.run (dart:async/zone.dart:1026)
#34     _CustomZone.runGuarded (dart:async/zone.dart:924)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#38     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#39     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

I'll keep looking, but maybe someone can update with some information about what's going on at this point in the program.

**Comment by zanderso** [comment] 2017-01-12 21:57
This appears to be running some sort of tar command. When I copy it and run it on a command line, I get:

```
zra-macbookpro2:quiver-dart zra$ tar --format=ustar --create --gzip --directory /Users/zra/dart/test_package/quiver-dart/. --files-from /dev/stdin --uname=pub --gname=pub
tar: Option --uname=pub is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
```

This looks like it could be a bug in the way that pub is calling tar.

**Comment by nex3** [comment] 2017-01-12 22:38
@zanderso What version of tar are you using?

In general, my understanding is that we shouldn't get sink errors unless our code writes to the sink after closing it. If the remote endpoint closes the sink, it should silently ignore writes. So if this *is* happening because the sink is closed due to a flag it doesn't understand, dart:io is still handling it incorrectly.

**Comment by zanderso** [comment] 2017-01-12 22:46
```
zra-macbookpro2:quiver-dart zra$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

**Comment by munificent** [comment] 2017-01-12 22:50
I'll take a look, thanks for the pointer!

**Comment by nex3** [comment] 2017-01-12 22:52
According to [the BSD `tar` man page](https://www.freebsd.org/cgi/man.cgi?query=bsdtar&apropos=0&sektion=1&manpath=FreeBSD+8.4-RELEASE&arch=default&format=html), it's had a `--uname` parameter since at least 2009. Maybe Mac OS has a really outdated version or something though?

**Comment by a-siva** [comment] 2017-01-12 23:03
@nex3 looks like this bug has been hijacked for a number of other issues, can we track the 'better error reporting' on this bug and move the API issue of not reporting an error when writes are done after a sink is closed to https://github.com/dart-lang/sdk/issues/25348

**Comment by a-siva** [comment] 2017-01-13 19:12
@munificent has the 'potential tar issue' been moved to another new issue? Can we close this, it was opened for the 'Unfriendly error' problem which has been fixed by @zanderso

**Comment by munificent** [comment] 2017-01-13 20:11
No, I didn't bother filing a separate bug for the tar issue. If the unfriendly error message is fixed, we can probably close this.

**Closed** 2017-01-13 22:16 UTC
Labels: area-sdk, P1 high, S1 high, Type: bug

**Comment by pq** [comment] 2017-01-13 23:55
\o/
