### ISSUE TITLE
dart:html and customElements

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#36568] opened 2019-04-11 09:43 UTC
How is one supposed to invoke customElements.define correctly?

```
import 'dart:html';

void main() {
 window.customElements.define("la-la", Foo);
}

class Foo {
 Foo() {
   print("hello from foo");
 }
}
```

yields
```
Uncaught exception:
Failed to execute 'define' on 'CustomElementRegistry': The callback provided as parameter 2 is not a function.
```

so does
```
void main() {
 window.customElements.define("la-la", () => new Foo());
}
```

and anything else I can come up with.

It seems that whatever is given to `customElements.define` is just passed directly to javascript, but that whatever you write there is actually a dart thing (e.g. a class with a call method or a type or whatever).

I *think* this is going to block #34107.

**Comment by sigmundch** [comment] 2019-04-11 17:59
Thanks for your question.

I'm marking as a duplicate of #27445 

My understanding is that custom-elements v1 is not supported by `dart:html` and it was decided that it was not a goal to add support for it at this time. (see @kevmoo's last comment on the other issue).

**Closed by sigmundch** 2019-04-11 17:59 UTC
Labels: area-html

**Comment by jensjoha** [comment] 2019-04-12 07:29
Am I then correct in understanding this as us having an api that cannot possibly be used correctly and however you call it you will get an error at runtime?

**Comment by sigmundch** [comment] 2019-04-12 16:33
I'm not 100% sure (some of this was autogenerated from an IDL and I have to look more closely). IMO, there is some cleanup to do: we have code for the old v0.5 API and we might be automatically exposing portions of the unsupported v1 API. My guess is that we should remove the latter, and deprecate and eventually remove the former?

@terrylucas
