### ISSUE TITLE
Dart socket.listen() ignores messages sent too fast

### ISSUE THREAD

**Issue by csmpv** [dart-lang/sdk#36871] opened 2019-05-07 12:33 UTC
Same as here:
https://github.com/dart-lang/sdk/issues/35313

Using a socket to receive string data. And it seems like the transmission is incomplete. The server sends around 80 KB and the dart socket receives sometimes 1 KB and sometimes around 10 KB.

Tried the onDone() handler and it's the same. It's called before the whole data is received.

I also tried breaking the data into multiple pieces. And I get the first and the last packet, but lose everything between.

Here is my code:

```
String globalData;

Future<String> getNetworkData() async {
  String rawData;
  await Socket.connect(ipAddr, port).then((Socket socket) {
    socket.add(utf8.encode(request));
    socket.listen((var data) {
      rawData = utf8.decode(data);
    });

  globalData += rawData;
  return rawData;
}
```

If I send the data into 1 KB chunks and make the server sleep 50 milliseconds between them, it works.

To reproduce use a simple socket server which returns around 80 KB of text on request (around 150 lorem ipsum paragraphs).

**Comment by fdakgg** [comment] 2019-05-18 10:13
Fixed by reading the entire stream:

```
Socket  socket = await Socket.connect(ipAddr, port);
globalData = socket.transform(utf8.decoder).join();
```

**Comment by sortie** [comment] 2019-06-07 13:44
Hi @csmpv,

Can you produce a full program that reproduces the issue? That would be very helpful.

You omitted some of the information requested by the bug template. What Dart SDK version and operating system (+ version) are you using? That would help me a lot in tracking it down, since it could well be a platform specific bug.

**Comment by csmpv** [comment] 2019-06-07 14:08
Hi @sortie,

Unfortunately I don't have the source code anymore. But here are some details:
- Dart SDK 2.3.0
- Windows 7 server app (using Windows TCP sockets)
- Android 6.0 client

My server would close and destroy the socket after send.

After trying multiple fixes, I added a disconnect() call on server before closing the socket. And this solved a lot of problems. Most likely makes the socket wait before final close and destruction. Could be a fix.

**Comment by sortie** [comment] 2019-06-07 14:11
Sounds like you were destroying the socket on the server side before it was done transmitting. That could explain the truncated results. 

Without a reproduction, I don't think there's more I can do right now.

**Closed by sortie** 2019-06-07 14:11 UTC
Labels: area-library, library-io, type-bug
