### ISSUE TITLE
Abstract Class Named Paramenter not showing proper error

### ISSUE THREAD

**Issue by faizabdillah** [dart-lang/sdk#54634] opened 2024-01-16 08:13 UTC
This tracker is for issues related to: Dart analyzer and linter

why the linter not giving error when we type the named constructor in the wrong way?
![image](https://github.com/dart-lang/sdk/assets/36881303/f8641f9d-458a-4434-b886-4b2b8c1f4384)

Expected Behavior
![image](https://github.com/dart-lang/sdk/assets/36881303/477e2d31-cb3f-432b-b26d-fe3da3ac740e)

<details>
  <summary><strong>General info</strong></summary>

- Dart 3.2.2 (stable) (Tue Nov 28 11:22:54 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Home Single Language" 10.0 (Build 22635)
- locale is en-US

</details>

<details>
  <summary><strong>Project info</strong></summary>

- sdk constraint: '>=3.2.1 <4.0.0'
- dev_dependencies: build_runner, chopper_generator, envied_generator, flutter_launcher_icons, flutter_lints, flutter_native_splash, flutter_test, freezed, hive_generator, json_serializable

</details>

<details>
  <summary><strong>Process info</strong></summary>

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|  48 MB |  -- |              | dart.exe     |
|  99 MB |  -- |              | dart.exe     |
| 410 MB |  -- |              | dart.exe     |
| 642 MB |  -- |              | dart.exe     |
|  91 MB |  -- |              | dart.exe     |
|  98 MB |  -- |              | dart.exe     |
|  85 MB |  -- |              | dart.exe     |

</details>

**Comment by eernstg** [comment] 2024-01-16 08:34
> why the linter not giving error when we type the named constructor in the wrong way?

The snippets of source code that you include do not declare any constructors, so there's no way the behavior of tools could be specific to constructor declarations. A constructor has a name that is or includes the name of the enclosing class-like declaration:

```dart
class A {
  A(); // A constructor whose name is `A`.
  A.named(int some, {String arguments = 'Hello!'}); // A constructor whose name is `A.named`.
}
```

Your first snippet does not have any compile-time errors, but the second one has one:

```dart
abstract class SomeAbstractClass {
  // No errors: This is an abstract method declaration, it accepts one named
  // optional parameter whose name is `whyNoError`, of type `String`. No problem!
  void name({String whyNoError});
}

class RegularClass {
  // Error: A concrete class must have an implementation of every member
  // in its interface, but `name` isn't implemented.
  void name({String correctError});
}
```

I'll close this issue because it is all working as intended. @faizabdillah, you're very welcome to file other issues if you encounter something that seems to be malfunctioning. Note also that there are various foras where Dart matters can be discussed and questions posed: https://dart.dev/community.

**Closed by eernstg** 2024-01-16 08:34 UTC

**Comment by mraleph** [comment] 2024-01-16 09:34
I think what @faizabdillah is confused about is why an optional named _parameter_ without a default value is causing an error in the second case and not in the first.

The reason for that is that the first one is an abstract method declaration and not an actual implementation of the method. The implementation (which overrides `name`) will need to specify default value for `whyNoError` - and it will be an error there.
