### ISSUE TITLE
Support the "Remove this widget" assist on Sliver widgets

### ISSUE THREAD

**Issue by tenhobi** [dart-lang/sdk#56637] opened 2024-09-02 21:34 UTC
Similarly to analyzer assist for `child` and `children` to `Remove this widget`, I would like to add the same also for Slivers, aka expand the suggestion to also detect `sliver` or `slivers` parameters. 

Right now I can "make it work" by i.e. changing `sliver` to `child` which then adds the option, but that is not the best.

This would make possible to see "Remove this widget" suggestion i.e. on `SliverPadding` here in the example and more:

```dart
const SliverPadding(
  padding: EdgeInsets.all(42),
  sliver: SliverToBoxAdapter(child: Text('aaa')),
),
```

**Comment by FMorschel** [comment] 2024-10-02 12:57
The CL was merged. We can close this now @bwilkerson or @tenhobi.

FYI, @tenhobi: If you click to edit the description at Gerrit and add lines like "Fixes _url_"  when the CL is merged, the issue is closed as well.

**Closed** 2024-10-02 14:14 UTC
Labels: area-analyzer, P3, type-enhancement, analyzer-assist
