### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by double-headed-eagle** [dart-lang/sdk#39559] opened 2019-11-28 08:29 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseLiteralListSuffix (package:front_end/src/fasta/parser/parser.dart:4437:19)
#10     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4290:14)
#11     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#12     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#13     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#14     Parser.parseVariableInitializerOpt (package:front_end/src/fasta/parser/parser.dart:2513:15)
#15     Parser.parseOptionallyInitializedIdentifier (package:front_end/src/fasta/parser/parser.dart:5389:13)
#16     Parser.parseVariablesDeclarationRest (package:front_end/src/fasta/parser/parser.dart:5370:13)
#17     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5363:15)
#18     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3738:16)
#19     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#20     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#21     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2460:13)
#22     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2340:14)
#23     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#24     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#25     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#26     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#27     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#28     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#29     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#30     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#31     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#48     new Future.sync (dart:async/future.dart:224:31)
#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#55     CompilerConte...
```

For additional log information, please append the contents of
file://C:\Users\phoenix\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-12-02 19:00
Thanks for the report! This was previously reported in #39092 and has been fixed. Please upgrade to the latest version, reopen if you still see the failure.

**Comment by srawlins** [comment] 2019-12-02 19:00
Duplicate of #39092

**Closed by srawlins** 2019-12-02 19:00 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
