### ISSUE TITLE
Debugger stopped working

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#48459] opened 2022-02-23 13:37 UTC
With commit [[ Service ] Update VM service message to not reference Observatory](https://dart-review.googlesource.com/c/sdk/+/233504) debug stopped working on my machine. I use `IntelliJ IDEA 2021.3.2 (Community Edition) IntelliJ IDEA 2021.3.2 (Community Edition) Build #IC-213.6777.52, built on January 28, 2022` on Windows.

The console prints something like
```
out/ReleaseX64/dart-sdk/bin/dart.exe --enable-asserts --pause_isolates_on_start --enable-vm-service:65357 pkg\front_end\tool\_fasta\compile.dart -o out.dill pkg\front_end\testcases\general\issue48242.dart
The Dart VM service is listening on http://127.0.0.1:65357/rIeKevcnfsw=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:65357/rIeKevcnfsw=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A65357%2FrIeKevcnfsw%3D%2Fws
```
and then just hangs.

**Comment by jwren** [comment] 2022-02-23 20:56
This is a duplicate of https://youtrack.jetbrains.com/issue/WEB-54727 which was closed with https://github.com/JetBrains/intellij-plugins/pull/855

The new version of the Dart plugin will be pushed out soon.  Note that users won't hit this issue as they don't build the latest Dart SDK by source.

Apologies for the breakage, I didn't know the change had landed until this issue.

**Closed by jwren** 2022-02-23 20:56 UTC
Labels: area-intellij

**Comment by jmagman** [comment] 2022-02-24 01:00
> Note that users won't hit this issue as they don't build the latest Dart SDK by source.

I'm seeing this in the Flutter master channel as of https://github.com/flutter/flutter/pull/98940.
