### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by git-maspaad** [dart-lang/sdk#38689] opened 2019-10-02 10:04 UTC
### What I was doing

When I type new dart file, it always got error. Please fix this bug.

### Versions

- Flutter SDK 1.10.4-pre.8
- Visual Studio Code 1.38.1
- Dart Code 3.5.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/macosx/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.5.0
```

### Exception

Failed to handle completion domain request: {id: 30, method: completion.getSuggestionDetails, params: {file: /Users/macosx/FlutterProjects/partaiperindo_appsandroid/lib/pages/generalsettings.dart, id: 486, label: MaterialPageRoute, offset: 10}, clientRequestTime: 1570010493766}

```text
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DartFileEditBuilderImpl.importLibraryElement (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1298:34)
#2      CompletionDomainHandler.getSuggestionDetails.<anonymous closure> (package:analysis_server/src/domain_completion.dart:204:32)
#3      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:54:20)
#4      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#5      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:51:18)
#6      CompletionDomainHandler.getSuggestionDetails (package:analysis_server/src/domain_completion.dart:203:23)
<asynchronous suspension>
#7      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:242:9)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1500:12)
#12     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:238:12)
#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:335:45)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:331:50)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1500:12)
#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:330:5)
#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#56     _StreamController._add (dart:async/stream_controller.dart:640:7)
#57     _StreamController.add (dart:async/stream_controller.dart:586:5)
#58     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#59     _rootRunUnary (dart:async/zone.dart:1136:13)
#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#65     _StreamController._add (dart:async/stream_controller.dart:640:7)
#66     _StreamController.add (dart:async/stream_controller.dart:586:5)
#67     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#68     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#69     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#71     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/macosx/FlutterProjects/partaiperindo_appsandroid",
        "explicitFileCount": 39,
        "implicitFileCount": 1403,
        "workItemQueueLength": 38,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment] 2019-11-05 05:21
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38476; please follow along there.

**Comment by srawlins** [comment] 2019-11-05 05:21
Duplicate of https://github.com/dart-lang/sdk/issues/38476

**Closed by srawlins** 2019-11-05 05:21 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
