### ISSUE TITLE
Compiler warning app.dll.track.dll

### ISSUE THREAD

**Issue by nalinkumarz** [dart-lang/sdk#36988] opened 2019-05-17 02:00 UTC
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* dev_compiler

Some other pieces of the Dart ecosystem are maintained elsewhere. Please
file issues in their repository:

* Dart language: https://github.com/dart-lang/language
* Dart website: https://github.com/dart-lang/site-www
* Flutter: https://github.com/flutter/flutter
* Linter: https://github.com/dart-lang/linter
* dartfmt: https://github.com/dart-lang/dart_style

If you aren't sure, file the issue here and we'll find the right home for it.
In your issue, please include:

Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

* Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"

**Comment by a-siva** [comment] 2019-05-24 23:15
This appears to be a duplicate of #37043

**Closed** 2019-05-28 23:30 UTC
Labels: closed-duplicate
