### ISSUE TITLE
"is" check doesn't infer type in some cases

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#28428] opened 2017-01-17 23:46 UTC
"is" checks don't result in the type being inferred as expected when they occur on either:
* top-level variables
* closure variables that happen to be set in nested closures

Reduced test case from Dartpad (https://dartpad.dartlang.org/3b84030c5ee2b77d144ff5f73f6d7100):
```dart
Base topLevelVar = new Sub();

main() {
  Base closureVar = new Sub();
  Base closureVarSetInNestedFunction = new Sub();
  
  nestedFunction() {
    // Setting in localFunction has the same effect.
    closureVarSetInNestedFunction = null;
  }
  
  localFunction() {
    Base localVar = new Sub();
    
    // Works as expected
    if (closureVar is Sub) closureVar.boom();
    if (localVar is Sub) localVar.boom();

    // Warning: The method 'boom' is not defined for the class 'Base'.
    if (topLevelVar is Sub) topLevelVar.boom();
    if (closureVarSetInOtherFunction is Sub) closureVarSetInNestedFunction.boom();
  }
}

class Base {}

class Sub extends Base {
  void boom() {}
}
```

I would expect to not have to cast `topLevelVar` and `closureVarSetInOtherFunction` to `Sub` within the if-statement body.

**Comment by eernstg** [comment] 2017-01-19 09:53
This is by design: Testing that an expression `e` has a value of a given type `T` will imply nothing about future values of `e`, unless we can somehow predict the possible changes. The general case is of course undecidable, so the spec points out specific circumstances where it is known that the value will not change, and in such cases the tested type can be assumed in a certain scope.

For instance, a local variable which is never assigned is subject to type promotion. In contrast, top-level variables and closure variables that happen to be set in a nested closure are not promoted, because there are many ways to change their value (any method invocation which might invoke a user-written method implementation might change them).

It would be possible to extend the set of cases where promotion is supported (and we are working on that), but there is no hope that all the situations where promotion is sound can be detected statically, and there's no realistic hope that even all the "obvious" situations ones can be detected. So this issue isn't going to go away. 

We could of course use a different design: Promote the type for every expression whenever we encounter an `is` check (such as `if (e is T) {..}`), and then generate code for a dynamic check in all the cases where soundness is not guaranteed. That would be possible, easy, and convenient, but obviously it would also introduce a new set of locations where runtime type errors may arise.

I usually argue that we should go a different way: allow for naming the value whose type we wish to capture, as in `e is T v`. This would introduce a new final variable `v` and initialize it with the value of `e`. That variable can safely be used with the tested type, without exceptions. This is reasonably concise and obviously sound, and it instantly extends the promotion support to all expressions, including global variables, function calls, etc.

**Comment by greglittlefield-wf** [comment] 2017-01-19 17:03
Excellent response, thank you for going into so much detail! I can see now how much more complicated this problem is than I initially thought.

I'm satisfied with that answer, but would also be very excited to use the `e is T v` syntax you mentioned, were it to be implemented!

**Comment by travissanderson-wf** [comment] 2017-01-19 17:12
I think something like that syntax would probably be adequate and most devs running into this would be satisfied given that option, especially if the analyzer can suggest using that syntax when it can't guarantee the type inside the body.

**Comment by eernstg** [comment] 2017-01-19 17:39
@greglittlefield-wf Thanks! We've had the `e is T v` syntax on the table for a while, as well as several other type promotion generalizations, so I'm sure we will have some improvements in this area soon. Can't promise any specific time frame, though, nor give any firm guarantees that it will happen at all.

@travissanderson-wf It could be a good idea to enhance the analyzer to perform a local transformation that introduces type promotion, but it might also be tricky to come up with anything that's more convenient than just writing the code yourself---there are so many ways to fix a given piece of code that doesn't type check. ;-)  If you come up with an idea that really nails it then please create a new issue with an enhancement request and area-analyzer.

With that, I'll close this one.

**Closed by eernstg** 2017-01-19 17:39 UTC
Labels: area-language
