### ISSUE TITLE
No error if deferred library members are called before loadLibrary() call

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#36020] opened 2019-02-25 11:30 UTC
```dart
import "lib.dart" deferred as p;

main() {
  print(p.foo()); // prints 1
}
```

Where `foo()` is defined in `lib.dart` as `int foo() => 1;`

There should be a dynamic error if deferred library member is called before` loadLibrary()` call but there isn't

Dart VM version: 2.1.2-dev.0.0 (Mon Feb 4 18:01:56 2019 +0100) on "windows_x64"

**Comment by a-siva** [comment] 2019-03-01 02:18
This is a duplicate of https://github.com/dart-lang/sdk/issues/33118

**Closed by a-siva** 2019-03-01 02:18 UTC
Labels: area-vm, type-bug
