### ISSUE TITLE
When I start writing a variable name after $ in quotes. Happens regularly if variable name starts from "is"

### ISSUE THREAD

**Issue by Yahhi** [dart-lang/sdk#39291] opened 2019-11-08 09:33 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#15     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4016:21)
#16     Parser.parseAwaitExpression (package:front_end/src/fasta/parser/parser.dart:5760:13)
#17     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4137:14)
#18     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#19     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#20     Parser.parseVariableInitializerOpt (package:front_end/src/fasta/parser/parser.dart:2513:15)
#21     Parser.parseOptionallyInitializedIdentifier (package:front_end/src/fasta/parser/parser.dart:5389:13)
#22     Parser.parseVariablesDeclarationRest (package:front_end/src/fasta/parser/parser.dart:5370:13)
#23     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5363:15)
#24     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#25     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#26     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#27     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#28     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#29     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#30     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#31     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#32     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#33     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#34     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#35     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#36     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#37     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#38     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#39     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#40     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#41     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#47     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#53     Driver.startAnalysisServer (package:analysis_serv...
```

For additional log information, please append the contents of
file:///private/var/folders/57/0lqqvjp92010n51840l4f7200000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-11-08 13:33
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/39092; please follow along there.

**Comment by srawlins** [comment] 2019-11-08 13:33
Duplicate of https://github.com/dart-lang/sdk/issues/39092

**Closed by srawlins** 2019-11-08 13:33 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
