### ISSUE TITLE
Expression evaluation results in CFE compile time error if accessing variables that were optimized out

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#53087] opened 2023-08-01 18:12 UTC
When breaking on a line that's inside a closure which is contained in an instance method, one may access enclosing variables in the expression evaluation. This works as expected if those enclosing variables were captured. Though if they were not captured one gets a confusing CFE compile-time error (as if the variables don't exist - which they clearly do).

I think it makes much more sense to report a "<optimized out>" in this case instead of a CFE compilation error.

See part of the `service/evaluate_activation_test` test.

**Comment by mkustermann** [comment] 2023-08-01 18:52
A simple repo:
```dart                                                                                                                                                 
import 'dart:async';                                                                                                                                               
                                                                                                                                                                   
import 'package:observatory/service_io.dart';                                                                                                                      
import 'package:test/test.dart';                                                                                                                                   
                                                                                                                                                                   
import 'test_helper.dart';                                                                                                                                         
                                                                                                                                                                   
breakHere() {}   

class C {                     
  var instVar = 1;                      
  static var classVar = 2;                                                                                                                                         
                                                                                                                                                                   
  void method(methodParam) {                                                     
    void foo() {                                                                                                                                                   
      breakHere();                                                                                                                                                 
    }                                                                            
                                                                                 
    foo();                                                                       
  }                                     
}                                       
                                        
Future testMethod(Isolate isolate) async {                                       
  final rootLib = await isolate.rootLibrary.load() as Library;                   
  final function = rootLib.functions.singleWhere((f) => f.name == 'breakHere');  
  await isolate.addBreakpointAtEntry(function);                                                                                                                    
                                                                                 
  final stream = await isolate.vm.getEventStream(VM.kDebugStream);               
  stream.firstWhere((event) {           
    print("Event $event");
    return event.kind == ServiceEvent.kPauseBreakpoint;                          
  }).then((event) async {                                                        
    dynamic frameNumber = 1;            
    final dynamic r = await isolate.evalFrame(frameNumber, 'methodParam');       
    print('Expression Evaluation Result: $r');                                   
    expect(r.valueAsString, equals('<optimized out>'));                                                                                                            
  }).whenComplete(isolate.resume);                                                                                                                                 
                                                                                                                                                                   
  await rootLib.evaluate('new C().method(3)');                                                                                                                     
}                                                                                                                                                                  
                                                                                                                                                                   
final tests = <IsolateTest>[                                                                                                                                       
  testMethod,                                                                                                                                                      
];                                                                                                                                                                 
                                                                                                                                                                   
main(args) => runIsolateTests(args, tests);              
```

Running this will result in
```
% out/ReleaseX64/dart runtime/observatory/tests/service/repro.dart
...
Expression Evaluation Result: DartError(org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'methodParam' isn't defined for the class 'C'.
 - 'C' is from 'runtime/observatory/tests/service/evaluate_activation_test.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'methodParam'.
methodParam
^^^^^^^^^^^)
...
```

**Comment by a-siva** [comment] 2023-11-16 17:33
//cc @derekxu16

**Comment by a-siva** [comment] 2023-11-20 18:02
Is this a duplicate of https://github.com/dart-lang/sdk/issues/53996, in other words will the solution proposed in it will also take care of this issue ?

**Comment by derekxu16** [comment] 2023-11-21 16:02
> Is this a duplicate of #53996, in other words will the solution proposed in it will also take care of this issue ?

Yes, the proposed solution will also take care of this issue.

**Comment by a-siva** [comment] 2023-11-21 18:36
Marking as duplicate of https://github.com/dart-lang/sdk/issues/53996

**Closed** 2023-11-21 18:36 UTC
Labels: area-vm, closed-duplicate, P2, triaged
