### ISSUE TITLE
Bots are not turning green after the failing test is fixed

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41243] opened 2020-03-27 21:26 UTC
`pkg-mac-release` and `pkg-win-release` bots are still red after the test `pkg/dds/test/smoke_test` was fixed.

See [build1](https://ci.chromium.org/p/dart/builders/ci.sandbox/pkg-mac-release/10901), [build2](https://ci.chromium.org/p/dart/builders/ci.sandbox/pkg-win-release/10172).

These bots fail at `test results` step with the following message:

```
No unapproved new failures
There are unapproved failures from previous builds
(unittest-asserts-release-mac):
    pkg/dds/test/smoke_test   (Pass -> RuntimeError, expected Pass) at fe6f3e

Failures link: https://dart-ci.firebaseapp.com/#showLatestFailures=true&showUnapprovedOnly=true&configurationGroups=unittest
```

However, `results.json` shows that this test is now passing:

```
{"name":"pkg/dds/test/smoke_test","configuration":"unittest-asserts-release-mac","suite":"pkg","test_name":"dds/test/smoke_test","time_ms":4647,"result":"Pass","expected":"Pass","matches":true,"bot_name":"vm19-m9","commit_hash":"0d0ca56eaa9402df1615e251125e843f05ce39bc","commit_time":1585342524,"build_number":"10901","builder_name":"pkg-mac-release","flaky":true,"previous_flaky":true,"previous_commit_hash":"b42c2857f854d4c21ca59146ac88bb7727b58777","previous_commit_time":1585340266,"previous_build_number":"10900","previous_result":"Pass","changed":false}
```

@athomas @whesse  Could you please take a look?

/cc @bkonyi

**Comment by whesse** [comment] 2020-03-30 08:27
On all three platforms (mac, windows, and linux), the test became flaky after failing with a runtime error.
When it got fixed, the test remained marked failing, and will not appear on the results feed until the flakiness expires.  I'll look more into how this test was flaky.  But we don't have a general strategy or design that can avoid this.  This indicates that we need to make flaky tests more visible, perhaps show when a test becomes flaky.  When working on the test-centered view, that shows the current status of one test on all platforms, and its history, we will need to show the flakiness info as well.

**Comment by athomas** [comment] 2020-03-30 09:49
Sounds similar to this:
https://github.com/dart-lang/dart_ci/issues/64

**Comment by a-siva** [comment] 2020-03-30 20:13
This test has been passing for the last 30 runs, how many more runs are needed before it loses the 'flaky' tag.

**Comment by athomas** [comment] 2020-03-30 20:19
100 runs is the current limit.

**Comment by a-siva** [comment] 2020-03-30 20:19
Shouldn't we turn the bot green, even if the test is flaking at least that is how we treat all flaky tests

**Comment by athomas** [comment] 2020-03-30 20:20
Yes, that's what we should do. This is a bug. The workaround would be to approve the failures that currently keep it red.

**Comment by a-siva** [comment] 2020-03-30 20:33
Ok I will go ahead and approve the failure.

**Comment by a-siva** [comment] 2020-03-30 20:38
I have approved the tests, removing gardenning label and leaving this issue open to track the infra issue mentioned above.

**Comment by athomas** [comment] 2020-03-31 06:41
Dupe of dart-lang/dart_ci#64.

**Closed by athomas** 2020-03-31 06:41 UTC
Labels: area-infrastructure
