### ISSUE TITLE
Difference in DartVM behavior regarding generic types

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#27041] opened 2016-08-09 15:43 UTC
This program:

```dart
import 'dart:async';
import 'dart:io';

main() {
  Stream<FileSystemEntity> fses = new Directory('/tmp').list();
  Stream<Directory> directories = fses.where((FileSystemEntity e) => e is Directory);
  directories.listen(print);
}
```

Works fine in unchecked mode. In checked mode there is a difference in behavior between

Old DartVM:
```
$ dart-sdk_old/bin/dart  --version
Dart VM version: 1.16.0 (Tue Apr 26 07:07:57 2016) on "linux_ia32"

$ dart-sdk_old/bin/dart -c test.dart
Directory: '/tmp/.com.google.Chrome.sJRnRh'

```

New DartVM:
```
$ dart-sdk/bin/dart --version
Dart VM version: 1.17.0-dev.6.4 (Fri Jun  3 12:47:59 2016) on "linux_x64"

$ dart-sdk/bin/dart -c test.dart
Unhandled exception:
type '_WhereStream<FileSystemEntity>' is not a subtype of type 'Stream<Directory>' of 'directories' where
  _WhereStream is from dart:async
  FileSystemEntity is from dart:io
  FileSystemEntity is from dart:io
  FileSystemEntity is from dart:io
  Stream is from dart:async
  Directory is from dart:io

#0      main (file:///usr/local/google/home/kustermann/repositories/sdk-gclient/sdk/test.dart:6:40)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

How is one supposed to do this correctly?

/cc language team @floitschG @lrhn @eernstg 

@mraleph

**Comment by lrhn** [comment] 2016-08-09 16:30
The problem is, exactly as written, that `_WhereStream<FileSystemEntity>` is not a a `Stream<Directory>`. It's just a `Stream<FileSystemEntity>`. The fact that it will only contain `Directory` objects doesn't change its actual type parameter, which is what is checked in checked mode.

Strong mode fixes this (I think!) by making `where` generic and using its type parameter in the return type, and then inferring that type parameter from the right-hand side type declaration. That won't help you in spec-Dart.

Solutions are: 

1. Use `var` for local variables.
2. Don't type `directories` as `Stream<Directory>`. Make it `Stream<FileSystemEntity>`, `Stream` or `dynamic`.
3. Wrap the stream using `new DelegatingStream<Directory>.typed(theStreamOfFSEs)` from `package:async`.

**Comment by floitschG** [comment] 2016-08-09 18:14
No. `where` is not generic in strong mode, and I don't think that it should be.
We should, probably, add a `cast` method, though.

**Comment by a-siva** [comment] 2016-08-11 15:34
@kevmoo why does this have the area-vm label ? Can you remove it and use an appropriate label.

**Comment by lrhn** [comment] 2016-08-12 07:08
So, basically, it's working as intended, it's probably just that we used to lose a type somewhere.

**Closed by lrhn** 2016-08-12 07:08 UTC
Labels: area-language, Type: SDK libraries strong

**Comment by mkustermann** [comment] 2016-08-12 07:18
@lrhn / @floitschG  Consider filing an issue about adding a `cast()` method then?

**Comment by lrhn** [comment] 2016-08-13 12:37
Adding a method to `Iterable` is at least a Dart 2.0 change, and still something to be wary of. There are lots of existing implementations of `Iterable` that won't have that method.

**Comment by floitschG** [comment] 2016-08-15 14:40
The `cast` method is already on our list of methods we are considering adding for Dart 2.0.
