### ISSUE TITLE
main() method that returns a Future should be guaranteed to be awaited

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#28769] opened 2017-02-15 00:47 UTC
Use case:

```
import 'dart:async';

Future<Null> main() async {
  try {
    print('before');
    await new Completer().future;
    print('after');
  } catch (_) {
    print('error');
  } finally {
    print('finally');
  }
}
```

This produces the following output:

```
before
```

... and then the process completes successfully (exit code 0).

And yet... if you add a timeout, like so:

```
await new Completer().future.timeout(const Duration(seconds: 2));
```

... then it prints `before`, then waits 2 seconds, and prints `error` and `finally`.

This is highly counterintuitive! Can the VM guarantee that the future returned by main() is always awaited?

**Comment by tvolkert** [comment] 2017-02-15 00:47
@cbracken @goderbauer

**Comment by rmacnak-google** [comment] 2017-02-15 00:59
The first future, `await new Completer().future;`, will never be completed. Duplicate of https://github.com/dart-lang/sdk/issues/23797

**Closed by rmacnak-google** 2017-02-15 00:59 UTC

**Comment by Hixie** [comment] 2017-02-15 01:48
What do you think should happen with this code?:

```dart
import 'dart:async';

main() {
  print('before');
  var f = new Completer().future;
  print('after');
  return f;
}
```

**Comment by tvolkert** [comment] 2017-02-15 01:49
I think the process shouldn't die until it's killed via a signal.

**Comment by lrhn** [comment] 2017-02-15 09:51
I actually think Hixie's example should terminate, and the one using `await` shouldn't.
The two examples are *similar*, and will have the same runtime behavior up to the point where no further computation will happen. The only question is what happens then.

The difference between the two is that the `async`/`await` example *looks* like straight-line code, and users are likely to expect it to work that way. That makes "hanging" more *understandable* than exiting and skipping the finally block.

For the `whenComplete` example, it's clear that control has run to the end of the `main` function. You can't wait in a non-`async` method, so when main completes, you are waiting for callbacks, which may or may not happen.

So, it's all about user perception. You expect straight-line code to either throw, complete or hang. Just exiting in the middle isn't even considered an option, which is why we get bug reports like this when it happens anyway. For non-`await` code, the user won't think they are in the middle of it, so there is no perception conflict.

So, I still suggest that the VM should *hang* if an isolate runs out of things to execute while waiting at an await. (You should still be able to kill the isolate explicitly in that case, if that's what you want). It should be possible to implement this using a single counter that is incremented on await and decremented when the await completes, and checked in the "about to exit" code.


It is *not* practically possible to hang the program if there is *any* uncompleted future. That happens far too easily, and such futures are just ignored and nobody notices. That's a good thing.

Looking at a future returned by `main` is a red herring. There are many ways to have a program run asynchronously without returning a future from `main`.

**Comment by tvolkert** [comment] 2017-02-15 14:43
That makes perfect sense - I'm sold.

**Comment by Hixie** [comment] 2017-02-15 21:46
FWIW, I frequently change code from using async to using explicit features and back. I think it would be very confusing if the semantics were different. I also think it'll be confusing that this code will hang or not hang depending on the implementation details of the function `foo()`:

```dart
void main() {
  foo().whenComplete(() { print('done'); });
}
```

```dart
// if this is the implementation, the program terminates
Future foo() {
  return new Completer().future;
}
```

```dart
// if this is the implementation, the program hangs
Future foo() async {
  return await new Completer().future;
}
```

**Comment by lrhn** [comment] 2017-02-16 10:34
It might be slightly confusing that the program hangs in one case and terminates in the other, but nothing near as confusing as a program terminating in the middle of a try/finally.

I would hope that the observatory could point you to the await that is hanging. That should aid debugging much more than just terminating.

That said, it's a change, and I don't know if there is someone out there who is using an `() async { handle(await somethingThatMightHappen); }()` as a kind of single-event handler, and those programs would start hanging when "something" didn't happen anyway. It's valid code now, so I can't rule it out.

**Comment by tvolkert** [comment] 2017-02-16 18:48
> I don't know if there is someone out there who is using ...

Philosophical question: if 99 developers cheer this change, and 1 curses it, did we do the right thing?
