### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by robbysoerya** [dart-lang/sdk#39987] opened 2020-01-05 12:06 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, FATAL error: FileSystemException: Directory listing failed, path = '/Users/bandregracing/.dartServer/.analysis-driver/be' (OS Error: No such file or directory, errno = 2)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:39:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:251:5)
#2      EvictingFileByteStore._cleanUpFolder (package:analyzer/src/dart/analysis/file_byte_store.dart:114:34)
#3      EvictingFileByteStore._cacheCleanUpFunction.<anonymous closure> (package:analyzer/src/dart/analysis/file_byte_store.dart:101:9)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#8      _StreamController._add (dart:async/stream_controller.dart:642:7)
#9      _StreamController.add (dart:async/stream_controller.dart:588:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file:///private/var/folders/tl/4_461d017hx32_fpy11wj7740000gn/T/report.txt.

**Comment by keertip** [comment] 2020-01-06 16:47
Thanks for the report. This was previously reported in #37059, you can follow progress there.

**Comment by keertip** [comment] 2020-01-06 16:47
Duplicate of #37059

**Closed by keertip** 2020-01-06 16:47 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
