### ISSUE TITLE
JS Interop no longer working dynamically (Dart 2.1.0)

### ISSUE THREAD

**Issue by mayorbyrne** [dart-lang/sdk#35737] opened 2019-01-23 17:27 UTC
I used to be able to load a javascript file dynamically, and utilize it via js interop when necessary (Dart 1.24.3).

interop:
```js
@JS('myJS')
abstract class MyJSContructor
{
  external factory MyJSContructor(String id, MyJSOptions options);
}
```
```js
MyJSContructor_jsObj;

void init()
{
  ScriptElement myJS = new ScriptElement()
    ..src = "assets/myJS-4.0.0.js"
    ..onLoad.listen(_continueLoadingPage);

  document.head.append(myJS);
}

void _continueLoadingPage(Event e)
{
  _jsObj = new MyJSContructor("#someID", _options);
}
```

This functionality no longer works, citing an error similar to

```
TypeError: dart.global.myJS is not a constructor at
...
```

Putting the js file in the `<head>` of the `index.html` file alleviates this issue, but I'd prefer not to load in a huge js file until it's necessary.  Am I doing something wrong?

Running Windows 10, Chrome 71.0.3578.98

**Comment by kevmoo** [comment] 2019-01-23 20:44
@jmesserly – thoughts?

**Comment by jmesserly** [comment] 2019-01-28 23:16
We'll need to fix this so the JS class is referenced lazily. (The development compiler already does this, IIRC.)

**Comment by nmrony** [comment] 2020-05-30 13:54
@kevmoo @jmesserly , I am trying to interop JS using `js` library in Flutter Web. I have a JS file as follows 
```js
export class HelloWorld {
  sayHello() {
      return "HelloWorld"
  }
}
```
In Dart file the content is like below 
```dart
@JS()
library js_in_flutter_web;

import 'package:js/js.dart';

@JS("HelloWorld")
class HelloWorld {
  external factory HelloWorld();
  external String sayHello();
}

```

main.dart
```
import 'package:flutter/material.dart';
import 'package:meta/meta.dart';

import 'from_js.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'JS Interop in Flutter Web'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  MyHomePage({Key key, @required this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Container(
        child: Center(
          child: Text(HelloWorld().sayHello()),
        ),
      ),
    );
  }
}

```
But getting this same error 
```
TypeError: dart.global.HelloWorld is not a constructor
```

**Comment by kevmoo** [comment] 2020-05-31 17:45
CC @natebosch

**Comment by natebosch** [comment] 2020-06-12 00:13
I think this looks like #39995 - @sigmundch should we dedup them?

**Comment by sigmundch** [comment] 2020-06-12 00:23
Good point @natebosch, yes!

**Comment by natebosch** [comment] 2020-06-12 00:26
Closing as a duplicate of #39995 which has more detailed information.

**Closed by natebosch** 2020-06-12 00:26 UTC
Labels: area-web, web-dart2js, web-js-interop
