### ISSUE TITLE
dart:svg doesn't found

### ISSUE THREAD

**Issue by bhangun** [dart-lang/sdk#39086] opened 2019-10-24 10:42 UTC
I'm trying using dart:svg in my library but not found. 
But tried in dart.dev was running.

Dart VM version: 2.5.2 

Sample:
```
import 'dart:svg';
main() {
  SvgSvgElement canvas = SvgSvgElement();
  canvas.createSvgRect();
  print("Hello, World!" + canvas.toString());
}
```

Result:
```
coba.dart:1:8: Error: Not found: 'dart:svg'
import 'dart:svg';
       ^
coba.dart:6:3: Error: 'SvgSvgElement' isn't a type.
  SvgSvgElement canvas = SvgSvgElement();
  ^^^^^^^^^^^^^
coba.dart:6:26: Error: Method not found: 'SvgSvgElement'.
  SvgSvgElement canvas = SvgSvgElement();
```

**Comment by lrhn** [comment] 2019-10-24 10:52
The `dart:svg` library is only available on the web, so you can't import it when running on the VM.

**Comment by devoncarew** [comment] 2019-10-24 21:27
@bhangun, thanks for the report! Closing this as working as intended.

**Closed by devoncarew** 2019-10-24 21:27 UTC

**Comment by bhangun** [comment] 2019-10-25 00:35
@lrhn Oo i c,
 ok then thanks, sorry for my ignorance.

**Comment by bhangun** [comment] 2019-10-28 23:32
sorry to raise this issue again,
is there any workaround which dart:svg library to be run on VM/ Flutter ?
because i plan to use it on Flutter (Mobile/Web/Desktop).
Thanks

**Comment by MarkOSullivan94** [comment] 2019-11-01 13:57
@bhangun have you looked at https://github.com/dnfield/flutter_svg ?

Not sure if it has desktop support 🤔
