### ISSUE TITLE
Analyzer: Missing promotion to non-nullable type by assignment?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#40312] opened 2020-01-24 14:35 UTC
Thanks to @sortie for noticing this behavior. This issue may be a 'type-question' or a 'type-bug', depending on the exact [promotion](https://github.com/dart-lang/language/blob/master/working/enhanced-type-promotion/feature-specification.md) [rules](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md) (I assume that they can still develop a bit).

Consider the following function:

```dart
int bar(int? end) {
  end = 0;
  return end;
}
```

As of bc9348829ef833c8dc91d6f13f847afa51c63947, the response from `dartanalyzer --enable-experiment=non-nullable` is as follows:

```
ERROR|STATIC_TYPE_WARNING|RETURN_OF_INVALID_TYPE|/usr/local/google/home/eernst/lang/dart/scratch/202001/n025.dart|3|10|3|A value of type 'int?' can't be returned from function 'bar' because it has a return type of 'int'.
```

However, it seems intuitively obvious that it can be known that the value of `end` at the return statement is a non-nullable `int`.

With respect to the [rules](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md#promotion), **NonNull**(`S`) is a type of interest when `S` is a tested type. I cannot immediately find a location where it is specified explicitly, but I'd assume that the declared type of a variable is also a 'tested type'.

In that case it seems to me that the 'promotable via assignment' step should be taken, and `end` should be promoted to have type `int` rather than `int?`.

I noted that 'promotion by initialization' doesn't apply for a local variable which is a formal parameter, but that shouldn't matter when we can argue that the parameter is promotable via assignment.

So isn't it the intention that it should be ok to `return end;`?

**Comment by stereotype441** [comment] 2020-01-24 16:06
Duplicate of #39562

**Closed by stereotype441** 2020-01-24 16:06 UTC
Labels: NNBD, area-analyzer, type-question
