### ISSUE TITLE
Switch case for `bool?` incorrectly flagged with body_might_complete_normally

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#50470] opened 2022-11-15 08:43 UTC
A switch case on a nullable boolean is not seen as exhaustive even when providing returns for true + false + null.

I have to add a default case to remove the warning, even though I shouldn't have to.

Example:
```
String foo(bool? value) {
  switch(value) {
    case true:
       return 'yay';
    case false:
      return 'nay';
    case null:
      return 'meh';
  }
}
```

gets flagged with `body_might_complete_normally`.

This reproduces on 
2.19.0-382.0.dev (master channel) and 2.18.4 (stable)

**Comment by asashour** [comment] 2022-11-15 09:28
This is not relevant to only `bool?`. I recall `bool` are not exhaustive, because they are not specified in the specs.

```dart
String foo(bool value) {
  switch (value) {
    case true:
      return 'yay';
    case false:
      return 'nay';
  }
}
```

**Comment by vsmenon** [comment] 2022-11-15 13:23
@eernstg - is this the intended behavior per spec?  Both the analyzer and cfe produce an error here.

**Comment by asashour** [comment] 2022-11-15 13:38
Duplicate of https://github.com/dart-lang/sdk/issues/47387

**Comment by eernstg** [comment] 2022-11-15 17:26
I wrote a comment about this, and I think it's still relevant: https://github.com/dart-lang/sdk/issues/47387#issuecomment-935824954.

You could say that we might as well consider `bool`/`bool?` to be types with exhaustiveness (they do provide the required guarantees). It was just considered unimportant because `true`/`false` are usually handled using `if` rather than `switch`, and the language team thought `true`/`false`/`null` would be rare.

I'll close the issue because we already have #47387.

**Closed by eernstg** 2022-11-15 17:26 UTC
Labels: closed-duplicate
