### ISSUE TITLE
VM: Corrupt object (illegal cid) encountered during scavenge

### ISSUE THREAD

**Issue by diocore** [dart-lang/sdk#29799] opened 2017-06-05 20:12 UTC
I was refereed from the dart-lang/pub to here, since it "looks like a VM error".

I'm using Windows Ubuntu subsystem and everything works fine except when I want to use 'pub'.
First of all, every time i close the console i need to add 'pub' to my path, 'dart' works fine though without the need to repeatedly add it to the path.
And when i wan't to use 'pub global activate' i get the following error: 

[pub global activate.txt](https://github.com/dart-lang/sdk/files/1053065/pub.global.activate.txt)

and if I try to use 'pub global activate ...  -v' i get the following:

[pub global activate -v.txt](https://github.com/dart-lang/sdk/files/1053068/pub.global.activate.-v.txt)

I'm also unable to use 'sudo pub global activate ...' since this results in 
"sudo: pub: command not found"

I tried getting help from aqueduct and then from dart-lang/pub. Just as a reference

(sorry for the attached files, but it looked really terrible if i pasted it in here using code or standard text)

**Comment by rmacnak-google** [comment] 2017-06-05 20:20
What version of the SDK were you using?

**Comment by diocore** [comment] 2017-06-05 20:23
Oh sorry. Tried the 1.23.0 stable and the newest branch 1.24.*
Problem occurred with both versions

**Comment by rmacnak-google** [comment] 2017-06-05 22:52
I'm unable to reproduce this on Linux. Does this fail reliably for you? Are you able to collect a core dump?

**Comment by diocore** [comment] 2017-06-06 20:21
It reliable fails by resolving dependencies. 
I'm unable to reproduce the 'unreachable code' error, but i had it like 4 times.

**Comment by diocore** [comment] 2017-06-06 20:22
It reliable fails by resolving dependencies.
I'm unable to reproduce the 'unreachable code' error, but i had it like 4 times.

**Comment by mraleph** [comment] 2017-06-13 09:14
@diocore how do you install Dart SDK on your machine? 

I tried reproducing this on my Windows 10 laptop - `pub global activate aqueduct` just hangs on me and never finishes.

**Comment by a-siva** [comment] 2017-10-17 22:41
Closing as we are unable to reproduce, please feel free to reopen if you have a way to reproduce the crash.

**Closed by a-siva** 2017-10-17 22:41 UTC
Labels: area-vm, Type: bug

**Comment by MikeMitterer** [comment] 2017-11-10 09:08
I have the same problem here to. If I delete either .packages or pubspec.lock then it works. This bug only occurs frequently. I also tried to reproduce the bug - no chance, but the bug is there.
