### ISSUE TITLE
Include `errors` in `ParallelWaitError.toString` somehow

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#53472] opened 2023-09-09 12:06 UTC
This tracker is for issues related to:

* Dart core libraries (`dart:async`, `dart:io`, etc.)

`ParallelWaitError.toString` currently only returns the string `"ParallelWaitError"`. This makes it hard to understand what the problem is when `ParallelWaitError` is not explicitly caught and inspected.

**Comment by blaugold** [comment] 2023-09-11 15:08
Another potential issue that makes `ParallelWaitError` hard to diagnose is that they are thrown without a `StackTrace`. 

How things work right now, I feel like the only advisable usages of the `wait` extensions are (1) without a `try/catch` if you are certain that the involved Futures with never complete with an error (which seems unrealistic in most cases) or (2) with a `try/catch` where you inspect the errors. It's also easy to get option 2 wrong by not matching the shape of the awaited record properly in the on clause of the `try/catch`.

**Comment by blaugold** [comment] 2023-10-05 10:05
@lrhn I see https://dart-review.googlesource.com/c/sdk/+/326644 is "Ready to submit". Thanks for working on this! Any idea when this CL will land?

**Comment by Albert221** [comment] 2024-04-07 09:16
Hey, it's been more than six months since the above Dart PR was submitted. Are there plans to merge it? :) @lrhn

**Comment by lrhn** [comment] 2024-04-09 15:02
That CL was replaced by https://dart-review.googlesource.com/c/sdk/+/353080 (which did less work on the success branch, in return for more work if an error occurred, which is a good trade-off).
It landed in February (just!).

**Closed by lrhn** 2024-04-09 15:02 UTC
Labels: area-library, library-async, type-enhancement

**Comment by asaarnak** [comment] 2024-04-12 17:57
Tested this out with an sample below.

Is it possible to get the `ParallelWaitError.stackTrace` also for the `await (runA(), runB()).wait;` in `main` method?

In this sample the `ParallelWaitError.stackTrace` doesn't show that the `.wait` was executed from `main` only `runA` method is shown. See comments in sample.

The problem is that when `runA` is reusable and also called from somewhere else, then i don't which code called it.

```dart
import 'dart:async';

void main() async {
  try {
    final (a, b) = await (
      runA(),
      runB(),
    ).wait;
  } on ParallelWaitError<
      (
        void,
        void,
      ),
      (
        AsyncError?,
        AsyncError?,
      )> catch (exception) {
    final stackTrace = exception.stackTrace;
    // The stackTrace is equal to:
    // #0      runA (package:my_app/main.dart:29:3)
    // <asynchronous suspension>
    // #1      _FutureResult._onValue (dart:async/future_extensions.dart:584:3)
    // <asynchronous suspension>
  }
}

Future<void> runA() async {
  await Future.delayed(Duration(seconds: 1));
  throw Exception('error A');
}

Future<void> runB() async {
  await Future.delayed(Duration(seconds: 1));
  throw Exception('error B');
}
```

**Comment by lrhn** [comment] 2024-04-12 18:30
I don't see any easy way to give you a stack trace that contains the `wait`, since the `wait` never throws. 
The only stack traces you get are for actual `throw`s. There is no `throw` in the `wait` code, it doesn't fail, and the code that does fail was `runA()` which was called *before* `wait`, not during the execution of `wait`.

**Comment by mkustermann** [comment] 2024-04-16 08:25
> `. @mkustermann Is there something here that might allow a better stack trace?)

Delegating to @mraleph who recently reworked this logic - with support of a `@pragma('vm:awaiter-link')` that guides unwinding for stack trace purposes (see a52f2b96179ebdf29c38cab47e73dd1c6ec6bdff and following CLs)
