### ISSUE TITLE
No compile time error for invalid metadata

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#24280] opened 2015-09-03 08:08 UTC
According to Dart Programming Language Speciﬁcation version 1.9, chapter 15 'Metadata':
>It is a compile time error if the expression is not one of the following:
>• A reference to a compile-time constant variable.
>• A call to a constant constructor.

However the following sample code does not produce expected compile error:
test1.dart
```dart
import "syntax_lib2.dart" as syntax_lib2;

@syntax_lib2()
class B{}

main() {
}
```
syntax_lib2.dart
```dart
library syntax_lib2;
```

>dart.exe --version
>Dart VM version: 1.12.0 (Mon Aug 31 03:21:50 2015) on "windows_x64"
>dart.exe  --checked  test1.dart
> *no output*

**Comment by lrhn** [comment] 2015-09-03 11:25
Duplicate of #24281 - same argument applies.

**Closed by lrhn** 2015-09-03 11:25 UTC
