### ISSUE TITLE
produce a hint if a factory has no return statement

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#23019] opened 2015-03-27 18:33 UTC
It would be great to provide a hint on this program:
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;class A {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;factory A() {}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;
indicating that the factory method is missing a return statement.

This is similar to what the analyzer does today in this code:

&nbsp;&nbsp;&nbsp;&nbsp;class A {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;int m() {}
&nbsp;&nbsp;&nbsp;&nbsp;}

**Comment by Fox32** [comment] 2015-09-19 11:35
Just came along this issue. Looks like a correct warning is already emittet if I return the wrong type, e.g ```return 0;```. 

But if I return ```null```, should there also be a warning? [DartPad](https://dartpad.dartlang.org/1a385d6d12702a4ae078) seems to run the code but I think it's problematic that a new expression can return ```null```?

By the way, I think this is a duplicate of issue #17121

**Comment by bwilkerson** [comment] 2015-09-19 15:47
Yes, it is a duplicate. Thanks for letting us know!

**Closed by bwilkerson** 2015-09-19 15:47 UTC
Labels: Analyzer-Hint, Area-Analyzer, Priority-Medium, Triaged, Type-Enhancement
