### ISSUE TITLE
Need core dump support on windows slaves, support archiving them on buildbot

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28735] opened 2017-02-10 12:54 UTC
Similar to our linux buildbot slave setup we need support for archiving coredumps/minidumps/... on test failure crashes on windows. Then we need to change our core dump archiving code to upload them to GCS (to the gs://dart-temp-crash-archive iirc)

/cc @fsc8000 @mraleph

**Comment by mkustermann** [comment] 2017-02-10 12:55
Here is an [example crash](https://build.chromium.org/p/client.dart/builders/vm-win-release-ia32-be/builds/5427/steps/vm%20tests/logs/stdio).

**Comment by mraleph** [comment] 2017-02-10 13:11
Duplicate of #28648

**Closed by mraleph** 2017-02-10 13:11 UTC
Labels: area-infrastructure, gardening
