### ISSUE TITLE
1.24.1 + test with content_shell hangs forever

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#29965] opened 2017-06-21 12:27 UTC
I tried it on the cmdline and with  IJ - always the same result - it hangs forever with error message

After downgrading to 1.23.0 it works.

- OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1510
Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

- Software installed -----------------------------------------------------------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Dart VM version: 1.23.0 (Fri Apr 21 03:07:31 2017) on "macos_x64"
Pub 1.23.0

**Comment by a-siva** [comment] 2017-06-21 17:30
Can you provide instructions on how to reproduce the problem, the subject line "1.24.1 + test with content shell hangs forever" does not convey much.

**Comment by clairesarsam-wf** [comment] 2017-06-21 18:29
I can reproduce this on https://github.com/cleandart/react-dart with the following:

Dart VM version: 1.24.1
`test` version: 0.12.22+1

```sh
$ git clone git@github.com:cleandart/react-dart.git
$ cd react-dart
$ pub get
$ pub run test -p content-shell
```

The result is that the process hangs outputting loading logs until you kill it, or, if you wait around 5 minutes, it times out.

**Comment by MikeMitterer** [comment] 2017-06-23 08:30
In my daily work I'm using Java (Server + Android) and Dart for the Browser part. For scripting Python. 
All my apps are running smoothly but if a problem occurs it is quite often Dart related! Compatibility problems, Analyzer problems, Dartium crashes after a few hours with memory problems (no idea if it's my app or if it's Dartium...) 

It's getting better - no doubt but after 4 years of Dart it is still feels a bit like a Beta version

**Comment by aaronlademann-wf** [comment] 2017-06-30 01:40
I can reproduce exactly the same as @clairesarsam-wf.

**Comment by aaronlademann-wf** [comment] 2017-07-05 15:04
Also - https://github.com/dart-lang/test/pull/640 seems to have been aimed at resolving the issue, but the issue is still present for myself as well as a handful of colleagues.  I've even tried completely uninstalling / re-installing the SDK with no luck.

**Comment by robbecker-wf** [comment] 2017-07-11 16:30
A few devs inside Workiva have verified that upgrading macOS to Sierra has resolved the tests hanging issue. (I'm on 10.12.5)

**Comment by latos** [comment] 2017-07-20 01:25
Hanging is a problem for us.  Were already on Sierra previously with no problem, now after updating the SDK, it's broken.

(Aside, there also seem to be internal breaking changes in the SDK that we had to work around with custom package versions - this release seems rather problematic in general :( )

**Comment by robbecker-wf** [comment] 2017-07-20 15:09
@latos and you're updated to 1.24.2 (not just 1.24.1) ?

**Comment by MikeMitterer** [comment] 2017-07-21 06:43
@robbecker-wf I'm also on 1.24.2 - same problem! Mac OS is El Captain 10.11.6

**Comment by latos** [comment] 2017-07-27 23:48
@robbecker-wf 1.24.2 is what I had with the problem

**Comment by MikeMitterer** [comment] 2017-08-21 11:02
Exactly two moth and and it still doesn't work!!!

**Comment by anders-sandholm** [comment] 2017-09-11 08:57
@MikeMitterer , sorry that this is still an unresolved issue. 
@a-siva , wondering if we were ever able to reproduce?

**Comment by MikeMitterer** [comment] 2017-09-12 08:24
@anders-sandholm Can I help to reproduce the problem?

**Comment by kevmoo** [comment] 2018-03-26 19:54
content-shell is no longer supported

**Closed by kevmoo** 2018-03-26 19:54 UTC
Labels: P1 high, area-test, area-vm, os-osx

**Comment by latos** [comment] 2018-04-22 01:46
@kevmoo What are we supposed to use now?

**Comment by zoechi** [comment] 2018-04-22 10:45
@latos `build` package with Chrome
