### ISSUE TITLE
Error: The argument type 'int' can't be assigned to the parameter type 'double'.

### ISSUE THREAD

**Issue by mingodad** [dart-lang/sdk#51405] opened 2023-02-14 10:15 UTC
While testing dart with tests adapted from https://github.com/ArashPartow/exprtk I found this weird error from dart, notice that `equal((1+2),3.0);` is accepted but `equal(-(1+2),-3.0);` is not.
```
dart --version
Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "linux_x64"

dart bug.dart
bug.dart:20:8: Error: The argument type 'int' can't be assigned to the parameter type 'double'.
	equal(-(1+2),-3.0);
	      ^
bug.dart:23:8: Error: The argument type 'int' can't be assigned to the parameter type 'double'.
	equal(-(1-2),1.0);
	      ^
```
bug.dart:
```
int total_count = 0;
int total_eq = 0;

void equal(double a, double b) {
	++total_count;
	if(a == b) {
		++total_eq;
	}
}

int main()
{
	double x, y, z, w;

	x=11.12345678910737373;
	y=22.12345678910737373;
	z=33.12345678910737373;
	w=44.12345678910737373;

	equal(-(1+2),-3.0);
	equal((1+2),3.0);
	equal((1-2),-1.0);
	equal(-(1-2),1.0);

	print("$total_count\t$total_eq\n");

	return 0;
}
```

**Comment by eernstg** [comment] 2023-02-14 18:47
This is actually working as intended. The ability to provide an integer literal in situations where a `double` is expected is very specifically limited to integer literals:

```dart
void main() {
  double d1 = 42; // OK, means `42.0`.
  double d2 = -42; // OK, special casing `unary-`, means `-42.0`.
  double d3 = 1 + 2; // OK, both `1` and `2` are in a context that makes them `1.0` resp. `2.0`.
  double d4 = -(1 + 2); // Error, moving outside the special casing.
}
```

The requirement is that the integer literal must be plain or negated (so we can have `-42`, and even though that `<unaryMinus> <integerLiteral>` it is covered and becomes `-42.0`), and `double` must be assignable to the context type, and `int` must _not_ be assignable to the context type, and then the integer literal becomes a value of type `double`.

Anything outside this very special domain means that an integer literal has type `int`, and you have to call `toDouble()` explicitly if you want a `double`.

I'll close the issue because it is all working as intended.

We do recognize, however, that the support for int-to-double coercion is a somewhat quirky corner of the language. :smile:

**Closed by eernstg** 2023-02-14 18:47 UTC

**Comment by eernstg** [comment] 2023-02-14 18:56
Here's a reference to the special casing of number operations that explains the treatment of `double d3 = 1 + 2;`: https://github.com/dart-lang/language/blob/728258382216e33592857017eeee98b982ce4d59/accepted/2.12/nnbd/number-operation-typing.md

**Comment by mingodad** [comment] 2023-02-14 18:58
Thanks for reply/help !
As you said:
>> We do recognize, however, that the support for int-to-double coercion is a somewhat quirky corner of the language. smile
