### ISSUE TITLE
Analyzer: high memory consumption, "Too many files open" errors

### ISSUE THREAD

**Issue by johnbland-wf** [dart-lang/sdk#30493] opened 2017-08-18 18:15 UTC
Versions
```
Dart SDK: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
Analysis server version: 1.18.0
```

I've seen this issue while using VS Code. It seems to not be an issue with WebStorm/IntelliJ or Atom users, but I cannot definitively say it is [Dart Code](https://github.com/Dart-Code/Dart-Code) at fault.

I've seen memory spike when I run do things like:

- Nuke all packages: `rm -rf .pub .packages && find . -name packages | xargs rm -rf`
- `pub get --packages-dir` (in this case w/ packages)
- Memory jumps and the plugin is useless; `Analyzing...` shows in the footer and never goes away

If I try to run anything in Terminal, it fails until I quit VS Code or use `Reload Window`. It will definitely happen again.

Here is the `dart` (`Code Helper`) process (from `/usr/local/Cellar/dart/1.24.2/libexec/bin/snapshots/analysis_server.dart.snapshot`) chewing up 
<img width="411" alt="screen shot 2017-08-18 at 12 56 30 pm" src="https://user-images.githubusercontent.com/2642946/29471570-1db08ce0-8416-11e7-8faa-fe65d7d7eb19.png">

Here are some shots from the analysis server:

![screen shot 2017-08-18 at 1 04 10 pm](https://user-images.githubusercontent.com/2642946/29471491-cc7466b2-8415-11e7-9913-4a27eba17120.png)

It currently notes `Added Files (1134)` and `Priority Files (2)` on the server status page for the main `lib/` project in this project. Since this repo has a `lib/` and `app/` folder, you also have `Implicitly Analyzed Files (6280)`, `Added Files (3)`, and the same Priority Files in the other context.

Analysis Domain info:
```
Subscriptions
FOLDING
HIGHLIGHTS
[project]/lib/src/components/single_edge_select.dart
[project]/lib/src/form/edge_form_item.dart
IMPLEMENTED
INVALIDATE
NAVIGATION
OCCURRENCES
[project]/lib/src/components/single_edge_select.dart
[project]/lib/src/form/edge_form_item.dart
OUTLINE
[project]/lib/src/components/single_edge_select.dart
[project]/lib/src/form/edge_form_item.dart
OVERRIDES
```

**Comment by johnbland-wf** [comment] 2017-08-18 18:15
Let me know if there is anything else I can provide for more information.

**Comment by johnbland-wf** [comment] 2017-08-18 18:18
@devoncarew @wmleler @matanlurey FYI

**Comment by devoncarew** [comment] 2017-08-18 18:40
@johnbland-wf, I see that you're using `1.24.2`. Can you try this out with a 1.25 dev release? The analysis server's diagnostics page has been overhauled since 1.24.

**Comment by devoncarew** [comment] 2017-08-18 18:40
And, thanks for investigation, and the detailed info above!

**Comment by johnbland-wf** [comment] 2017-08-18 18:41
Ah, nice to know. Yes. I can try 1.25.

Is there anything else I can pull before switching? I'm getting the error right now.

**Comment by johnbland-wf** [comment] 2017-08-18 18:55
Whoa...that is much better.

**Comment by johnbland-wf** [comment] 2017-08-18 20:12
From the Observatory, I noticed these files are taking up the majority of the memory.

![screen shot 2017-08-18 at 3 01 51 pm](https://user-images.githubusercontent.com/2642946/29475962-7ff2f76a-8427-11e7-993d-25e723df8844.png)

__Note__: this is after an IDE restart so the #'s are much lower.

**Comment by bwilkerson** [comment] 2017-08-18 20:14
See https://github.com/Dart-Code/Dart-Code/issues/317 for more context.

**Comment by bwilkerson** [comment] 2017-08-18 20:14
@scheglov

**Comment by DanTup** [comment] 2017-08-18 20:27
Based on https://github.com/Dart-Code/Dart-Code/issues/317#issuecomment-323441109 I think the "too many open files" error might be a VS Code issue (@johnbland-wf I think it's worth raising a new issue against vscode if you haven't, and include the output from [that comment](https://github.com/Dart-Code/Dart-Code/issues/317#issuecomment-323441109)).

It's curious that this issue is isolated to Dart Code; I can't think of anything I'd be doing that's significantly different here (maybe @devoncarew has ideas, being familiar with both the Atom and Dart Code implementations?).

**Comment by scheglov** [comment] 2017-08-22 17:06
I'm afraid that until https://github.com/dart-lang/sdk/issues/24749 is fixed, any screenshots about heap usage will be shots in the dark. Specifically in this issue, I don't know why memory is hold - there are several sets in `FileState` - with various names and transitive files, and whether it is OK or not. Moreover, I cannot tell you what else I need - this is exploratory work, and need either be able to reproduce it locally, or the aforementioned issue is fixed so that you can provide enough information for me.

**Comment by johnbland-wf** [comment] 2017-08-23 00:57
@scheglov is there anything I could provide to help give more information on the issue? As Dan mentioned, this is only an issue with VS Code + Dart Code extension, for me, but I definitely see analyzer memory growing significantly over time.

I hit the issue several times a day so I'm open to debug more. Just let me know.

**Comment by scheglov** [comment] 2017-08-23 16:46
As I said, this is exploratory work, try to look around the heap snapshot, look also on not merged dominator tree, into specific instances. It is very hard to say anything concrete.

FYI, does not look related to your issue, but I found [another leak](https://codereview.chromium.org/3003753002) in Analysis Server, which was accidentally introduced recently.

**Comment by johnbland-wf** [comment] 2017-08-23 18:53
Good find.

**Comment by bwilkerson** [comment] 2018-01-29 22:31
@scheglov Is this still an active issue, or should we close it?

**Comment by scheglov** [comment] 2018-01-30 18:52
That's old, we don't get similar reports from internally users, so probably it was a single instance problem.

**Closed by scheglov** 2018-01-30 18:52 UTC
Labels: P2 medium, Type: performance, area-analyzer
