### ISSUE TITLE
type inference seems to be confused by repeated type checks

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31983] opened 2018-01-26 18:06 UTC
Extracted from #31975, the code snipped below works, but when you uncomment commented lines, it fails.

```
abstract class Element {}

abstract class RenderObject {}

class WidgetInspector {
  Element _currentElement;

  bool setSelection(Object object, [String groupName]) {
    // if (object is Element || object is RenderObject) {
      if (object is Element) {
        _currentElement = object;
      }
    // }
  }
}

main() {}
```

failure:
```
╰─➤  $DH/pkg/vm/tool/dart2 $DH/type_inference.dart
file://$DH/type_inference.dart:11:27: Error: A value of type '#lib1::RenderObject' can't be assigned to a variable of type '#lib1::Element'.
Try changing the type of the left hand side, or casting the right hand side to '#lib1::Element'.
        _currentElement = object;
                          ^
file://$DH/type_inference.dart:11:27: Error: A value of type '#lib1::RenderObject' can't be assigned to a variable of type '#lib1::Element'.
Try changing the type of the left hand side, or casting the right hand side to '#lib1::Element'.
        _currentElement = object;
                          ^
```

cc: @peter-ahe-google

**Comment by mraleph** [comment] 2018-01-26 18:11
I am marking this as a P1 because it makes Flutter Gallery build "spammy" and confusing. 

/cc @leafpetersen @lrhn @eernstg - could you confirm that promotion should happen in this example?

**Comment by leafpetersen** [comment] 2018-01-26 18:20
Yes.  No promotion should happen based on the outer conditional, and the inner conditional should promote to `Element`.  It looks like the outer conditional is incorrectly promoting to `RenderObject`?

**Comment by mraleph** [comment] 2018-01-26 18:30
Yeah, it does look like that indeed.

**Comment by leafpetersen** [comment] 2018-01-26 18:58
Just to be clear, this is CFE, not analyzer, right?  I don't see this on fairly recent analyzer build.

**Comment by aam** [comment] 2018-01-26 18:59
Yes, it's CFE.

**Comment by stereotype441** [comment] 2018-01-26 20:28
I've reproduced the bug and I'm investigating.

**Comment by stereotype441** [comment] 2018-01-26 21:26
Found the problem: `||` was being erroneously handled (in part) like `&&`.  Fix is here: https://dart-review.googlesource.com/c/sdk/+/37081

**Closed** 2018-01-27 16:08 UTC
Labels: P1 high
