### ISSUE TITLE
NPE in DefaultFixContributor

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#26015] opened 2016-03-16 18:45 UTC
1.15.0-dev.5.0
```
1457558717490.9236.json
Exception from fix contributor:: DefaultFixContributor","stackTrace"::"The null object does not have a getter 'kind'.

NoSuchMethodError:: method not found:: 'kind'
Receiver:: null
Arguments:: []
#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::42)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::45)
#2      FixProcessor._addFix_createGetter (package::analysis_server/src/services/correction/fix_internal.dart::1098)
#3      FixProcessor.compute.<compute_async_body> (package::analysis_server/src/services/correction/fix_internal.dart::210)
#4      Future.Future.microtask.<anonymous closure> (dart::async/future.dart::144)
#5      _rootRun (dart::async/zone.dart::891)
#6      _CustomZone.run (dart::async/zone.dart::790)
#7      _CustomZone.runGuarded (dart::async/zone.dart::696)
#8      _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#9      _rootRun (dart::async/zone.dart::895)
#10     _CustomZone.run (dart::async/zone.dart::790)
#11     _CustomZone.runGuarded (dart::async/zone.dart::696)
#12     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#13     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#14     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#15     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::96)
#16     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart
Original message:
{"event"::"server.error","params"::{"isFatal"::false,"message"::"Exception from fix contributor:: DefaultFixContributor","stackTrace"::"The null object does not have a getter 'kind'.

NoSuchMethodError:: method not found:: 'kind'
Receiver:: null
Arguments:: []
#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::42)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::45)
#2      FixProcessor._addFix_createGetter (package::analysis_server/src/services/correction/fix_internal.dart::1098)
#3      FixProcessor.compute.<compute_async_body> (package::analysis_server/src/services/correction/fix_internal.dart::210)
#4      Future.Future.microtask.<anonymous closure> (dart::async/future.dart::144)
#5      _rootRun (dart::async/zone.dart::891)
#6      _CustomZone.run (dart::async/zone.dart::790)
#7      _CustomZone.runGuarded (dart::async/zone.dart::696)
#8      _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#9      _rootRun (dart::async/zone.dart::895)
#10     _CustomZone.run (dart::async/zone.dart::790)
#11     _CustomZone.runGuarded (dart::async/zone.dart::696)
#12     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#13     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#14     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#15     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::96)
#16     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::149)

"}}
```

**Comment by bwilkerson** [comment] 2016-03-16 20:26
Duplicate of #25691

**Closed by bwilkerson** 2016-03-16 20:26 UTC
Labels: analyzer-stability, area-analyzer, P1 high, Type: bug
