### ISSUE TITLE
False positive on "unnecessary cast" in assignment

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#46582] opened 2021-07-07 20:48 UTC
If I write:

```dart
void main() {
  int? i = null;
  var j = 1 as int?; // 1
  j = i; // 2
}
```

I get "Unnecessary cast" on the line `1`. But that cast is necessary in order to upcast the inferred type of the variable. If I remove the cast, then I get a compile error on `2`.

In this case, the idiomatic fix is to annotate the variable instead of casting, but in general, it seems like fixing an unnecessary cast should never cause a compile error to appear.

**Comment by devoncarew** [comment] 2021-07-14 17:57
cc @scheglov

**Comment by scheglov** [comment] 2021-07-15 01:02
I think we will leave it as is.

As I understand, the issue is that every time when we can get a different type, the hint potentially directs you toward a semantic change. This happens in your example when a variable type changes, or it could be an invocation of a generic function `void f<T>(T _) {} void g() { f(1 as int?); }`.

In both cases you are using a type cast to force some specific type - declared, or a type argument. But there already is a canonical way to do this - write the corresponding type annotation, or a type argument. Not reporting a hint when it might change a type might be a too big hammer, I think it is still not a good code. But the explanation of the hint might direct the user to considering adding explicit type annotations instead.

@bwilkerson

**Comment by bwilkerson** [comment] 2021-07-15 15:58
I agree with @munificent that this is a false positive.

The analyzer produces several hints whose names start with either 'unnecessary_' or 'unused_'. In all of those cases the original intent of the hint was to point out places where code could be removed because it did not have any semantic impact on the overall program. For example, an unused import or an unnecessary `catch` clause. My opinion is that if code has a semantic impact on the program then it shouldn't be marked as being unnecessary. The question is how we define "semantic impact".

For this particular hint, in cases where a type cast changes the inferred type of a variable or an inferred type argument, I think there's a clear semantic impact.

More generally, the introduction of a diagnostic seems to me like a clear indication that there was a semantic impact. While I can kind of see an argument for flagging cases where no errors would be introduced by the removal of the code, it isn't clear to me that diagnostics are the only kind of impact that we should include in the general guideline. I'd be more comfortable having a very broad definition of "semantic impact" because doing so will reduce the number of false positives.

That doesn't mean that there isn't value in catching cases where the semantic impact is benign, but those seem more like style preferences rather than likely bugs, so I would think that a lint was more appropriate.

**Comment by lrhn** [comment] 2021-07-15 20:04
I also agree that this feels like false positive.

Is there a quick-fix for the lint? (And if there isn't a fix yet, would it be what is would do if it existed?) Does it just remove the cast?

In that case, the fix is wrong, and either it should be changed, or the lint should not apply.

**Comment by bwilkerson** [comment] 2021-07-15 20:07
> Is there a quick-fix for the lint?

Yes.

> Does it just remove the cast?

Yes.

> ... or the lint should not apply.

Agreed.

**Comment by srawlins** [comment] 2021-11-01 22:01
This one would be so tricky to get right for every case, I think we should maybe restrict this check to _only_  report when the static type of the as-expression's expression is _exactly_ the type being cast, (`1 as int`). Casting an expression to a super-type may seem silly, but this example (the type is used in upwards inference) isn't the only one. Consider this:

```
extension on num {
  void x() => print('x on num');
}

extension on int {
  void x() => print('x on int');
}

void main() {
  (1 as num).x();
}
```

This cast is necessary in the presence of the first extension. The code is legal with or without the first extension, but has different meanings.

I think there are numerous cases which would be too hard to tell whether the cast is unnecessary.

If we change this code to only report "unnecessary cast" from `T` to `T`, we can add opt-in lints to back up the old behavior:

* a lint that reports on `var a = 1 as int?;` saying it is more idiomatic to write `int? a = 1;`.
* a lint that reports on `f(1 as int?)` (using @scheglov's example) saying it is more idiomatic to write `f<int?>(1)`.
* a lint that reports on `1 as int?` in other cases as "likely unnecessary." (with better wording)

**Comment by srawlins** [comment] 2024-03-14 19:53
No longer reported. 🎉

**Closed by srawlins** 2024-03-14 19:53 UTC
Labels: area-analyzer, analyzer-warning, P2
