### ISSUE TITLE
DartVM crashes on RawDatagramSocket.receive

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#24426] opened 2015-09-24 10:57 UTC
The following code crashes DartVM on Windows with 0xC0000005 after receiving couple datagrams. Tested both x86 and x64 archs, stable (1.12.1) and dev (1.13.0-dev.3.1).

```dart
import 'dart:async';
import 'dart:io';

RawDatagramSocket socket;

main() async {
  socket = await RawDatagramSocket.bind(InternetAddress.ANY_IP_V4, 5000);
  socket.writeEventsEnabled = false;
  socket.listen(onData);
}

void onData(RawSocketEvent e) {
  Datagram d = socket.receive();
  if (d != null)
    print('Datagram from ${d.address.address}:${d.port} ${d.data.length} bytes');
}
```

**Comment by sgjesse** [comment] 2015-10-02 11:38
I cannot reproduce this crash. Can you provide more information on the data being transmitted?

Using a simple Dart client like works.
```
import 'dart:async';
import 'dart:io';

String ip = 'xxx.xxx.xxx.xxx'; // Change to the IP of the receiver.

RawDatagramSocket socket;

main() async {
  socket = await RawDatagramSocket.bind(InternetAddress.ANY_IP_V4, 5000);
  socket.writeEventsEnabled = true;
  socket.listen(onData);
}

void onData(RawSocketEvent e) {
  var addr = new InternetAddress(ip);
  socket.send(new List.filled(200, 1), addr, 5000);
  socket.writeEventsEnabled = true;
}

**Comment by lexaknyazev** [comment] 2015-10-02 13:10
There is something with packets greater than 1024 bytes.
Change client's `onData` to this
```dart
void onData(RawSocketEvent e) {
  var addr = new InternetAddress(ip);
  socket.send(new List.filled(1025, 1), addr, 5000);
  socket.writeEventsEnabled = true;
}
```

**Comment by sgjesse** [comment] 2015-10-02 15:19
Thanks, I found the issue. Proposed fix: https://codereview.chromium.org/1381233003/.

**Comment by sgjesse** [comment] 2015-10-06 13:54
Fixed by https://github.com/dart-lang/sdk/commit/33e2d9cd7e3d6191194bee1f93e33de53f3e5b05, and follow-up test fix in https://github.com/dart-lang/sdk/commit/e0daf8dd9368d8260ded38d251e98e0c09a55c9a.

**Closed by sgjesse** 2015-10-06 13:54 UTC
Labels: Area-VM, Library-IO
