### ISSUE TITLE
Debugger stepping test flakily hitting assertion, local var descriptors having possibly wrong token position encoding

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#44192] opened 2020-11-13 11:02 UTC
Flaky crash from [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8863806709526232144/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0):
```


/===========================================================================================\
| service_2/next_through_is_and_as_test/service broke (Pass -> RuntimeError, expected Pass) |
\===========================================================================================/

--- Command "app_jit" (took 39.000721s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/s/w/ir/out/DebugX64/generated_compilations/app_jitk/runtime_observatory_2_tests_service_2_next_through_is_and_as_test/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/observatory_2/tests/service_2/next_through_is_and_as_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: next_through_is_and_as_test.dart (VM Service)[0m

** Launching SERVICE_TEST_TESTEE=true out/DebugX64/dart --disable-dart-dev --pause-isolates-on-start --pause-isolates-on-exit --write-service-info=file:///b/s/w/it_Egiwy/dart_serviceBAHTBO/service_info.json --profiler --snapshot=/b/s/w/ir/out/DebugX64/generated_compilations/app_jitk/runtime_observatory_2_tests_service_2_next_through_is_and_as_test/out.jitsnapshot --snapshot-kind=app-jit --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages --enable-vm-service:0 /b/s/w/ir/runtime/observatory_2/tests/service_2/next_through_is_and_as_test.dart

>testee>out> Observatory listening on http://127.0.0.1:35823/vdSBZ8-suts=/

** Signaled to run test queries on http://127.0.0.1:35823/vdSBZ8-suts= (VM Service)

Loading VM...

Done loading VM

>testee>err> ../../runtime/vm/scopes.cc: 386: error: expected: desc.info.begin_pos <= desc.info.end_pos

>testee>err> version=2.12.0-edge.f63bb7acf4edc9c96aece5108f1ba6a768b4a73c (be) (Thu Nov 12 19:44:46 2020 +0000) on "linux_x64"

>testee>err> pid=27255, thread=27262, isolate_group=kernel-service(0x55be2dd26b00), isolate=kernel-service(0x55be2dd8a000)

>testee>err> isolate_instructions=7fdde4a91000, vm_instructions=55be2bd38fe0

>testee>err> pc 0x000055be2c10dcec fp 0x00007fdde26fba80 dart::Profiler::DumpStackTrace(void*)+0x7c

>testee>err> pc 0x000055be2bd39112 fp 0x00007fdde26fbb60 dart::Assert::Fail(char const*, ...)+0x82

>testee>err> pc 0x000055be2c18c1bf fp 0x00007fdde26fbbf0 dart::LocalScope::GetVarDescriptors(dart::Function const&, dart::ZoneGrowableArray<long>*)+0x32f

>testee>err> pc 0x000055be2c1eb22f fp 0x00007fdde26fbfa0 dart::Compiler::ComputeLocalVarDescriptors(dart::Code const&)+0x30f

>testee>err> pc 0x000055be2c09fa5a fp 0x00007fdde26fbfd0 dart::Code::GetLocalVarDescriptors() const+0x8a

>testee>err> pc 0x000055be2bf9376d fp 0x00007fdde26fc010 dart::ActivationFrame::GetVarDescriptors()+0x10d

>testee>err> pc 0x000055be2bf95926 fp 0x00007fdde26fc0d0 dart::ActivationFrame::GetDescIndices()+0x26

>testee>err> pc 0x000055be2bf9759e fp 0x00007fdde26fc150 dart::ActivationFrame::PrintToJSONObjectRegular(dart::JSONObject*)+0x15e

>testee>err> pc 0x000055be2c1a0040 fp 0x00007fdde26fc1a0 dart::ServiceEvent::PrintJSON(dart::JSONStream*) const+0x1a0

>testee>err> pc 0x000055be2bfd28dd fp 0x00007fdde26fc300 dart::Isolate::PrintJSON(dart::JSONStream*, bool)+0x66d

>testee>err> pc 0x000055be2c194d5f fp 0x00007fdde26fc310 out/DebugX64/dart+0x1f89d5f

>testee>err> pc 0x000055be2c18f402 fp 0x00007fdde26fc480 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)+0x5d2

>testee>err> pc 0x000055be2c18fffe fp 0x00007fdde26fc4b0 dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)+0x1e

>testee>err> pc 0x000055be2bfcaf38 fp 0x00007fdde26fc6a0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x3b8

>testee>err> pc 0x000055be2c011731 fp 0x00007fdde26fc730 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x221

>testee>err> pc 0x000055be2c011f6f fp 0x00007fdde26fc790 dart::MessageHandler::HandleOOBMessages()+0xaf

>testee>err> pc 0x000055be2c1c6eb3 fp 0x00007fdde26fc7e0 dart::Thread::HandleInterrupts()+0xa3

>testee>err> pc 0x000055be2c181ead fp 0x00007fdde26fc9b0 dart::DRT_StackOverflow(dart::NativeArguments)+0x71d

>testee>err> pc 0x00007fdde70023e2 fp 0x00007fdde26fc9f0 Unknown symbol

>testee>err> pc 0x00007fdde12a8fd7 fp 0x00007fdde26fca28 Unknown symbol

>testee>err> pc 0x00007fdde12a8d18 fp 0x00007fdde26fca78 Unknown symbol

>testee>err> pc 0x00007fdde12a08ca fp 0x00007fdde26fcb38 Unknown symbol

>testee>err> pc 0x00007fdde12989a0 fp 0x00007fdde26fcb98 Unknown symbol

>testee>err> pc 0x00007fdde128cbe7 fp 0x00007fdde26fcc00 Unknown symbol

>testee>err> pc 0x00007fdde128ca9e fp 0x00007fdde26fcc70 Unknown symbol

>testee>err> pc 0x00007fdde1970db3 fp 0x00007fdde26fcd20 Unknown symbol

>testee>err> pc 0x00007fdde196dcc6 fp 0x00007fdde26fcda0 Unknown symbol

>testee>err> pc 0x00007fdde196db3b fp 0x00007fdde26fce18 Unknown symbol

>testee>err> pc 0x00007fdde196d6c6 fp 0x00007fdde26fcec0 Unknown symbol

>testee>err> pc 0x00007fdde193874a fp 0x00007fdde26fcf10 Unknown symbol

>testee>err> pc 0x00007fdde1938448 fp 0x00007fdde26fcf78 Unknown symbol

>testee>err> pc 0x00007fdde193771e fp 0x00007fdde26fd000 Unknown symbol

>testee>err> pc 0x00007fdde19364b7 fp 0x00007fdde26fd048 Unknown symbol

>testee>err> pc 0x00007fdde1933464 fp 0x00007fdde26fd088 Unknown symbol

>testee>err> pc 0x00007fdde1972622 fp 0x00007fdde26fd140 Unknown symbol

>testee>err> pc 0x00007fdde196dcc6 fp 0x00007fdde26fd1c0 Unknown symbol

>testee>err> pc 0x00007fdde196db3b fp 0x00007fdde26fd238 Unknown symbol

>testee>err> pc 0x00007fdde196d6c6 fp 0x00007fdde26fd2e0 Unknown symbol

>testee>err> pc 0x00007fdde193874a fp 0x00007fdde26fd330 Unknown symbol

>testee>err> pc 0x00007fdde1938448 fp 0x00007fdde26fd398 Unknown symbol

>testee>err> pc 0x00007fdde193771e fp 0x00007fdde26fd420 Unknown symbol

>testee>err> pc 0x00007fdde19364b7 fp 0x00007fdde26fd468 Unknown symbol

>testee>err> pc 0x00007fdde19362b3 fp 0x00007fdde26fd4a8 Unknown symbol

>testee>err> pc 0x00007fdde1949334 fp 0x00007fdde26fd520 Unknown symbol

>testee>err> pc 0x00007fdde1948f9a fp 0x00007fdde26fd590 Unknown symbol

>testee>err> pc 0x00007fdde19486e3 fp 0x00007fdde26fd630 Unknown symbol

>testee>err> pc 0x00007fdde194fdc6 fp 0x00007fdde26fd680 Unknown symbol

>testee>err> pc 0x00007fdde1935ff3 fp 0x00007fdde26fd6c8 Unknown symbol

>testee>err> pc 0x00007fdde1935c44 fp 0x00007fdde26fd708 Unknown symbol

>testee>err> pc 0x00007fdde1935b3b fp 0x00007fdde26fd738 Unknown symbol

>testee>err> pc 0x00007fdde19359d3 fp 0x00007fdde26fd778 Unknown symbol

>testee>err> pc 0x00007fdde19061ed fp 0x00007fdde26fd7a0 Unknown symbol

>testee>err> pc 0x00007fdde700286d fp 0x00007fdde26fd818 Unknown symbol

>testee>err> pc 0x000055be2bf8a593 fp 0x00007fdde26fd8b0 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x113

>testee>err> pc 0x000055be2bf8a185 fp 0x00007fdde26fd920 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x135

>testee>err> pc 0x000055be2bf8df23 fp 0x00007fdde26fd990 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x233

>testee>err> pc 0x000055be2bfcb15a fp 0x00007fdde26fdb80 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x5da

>testee>err> pc 0x000055be2c011731 fp 0x00007fdde26fdc10 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x221

>testee>err> pc 0x000055be2c012659 fp 0x00007fdde26fdc90 dart::MessageHandler::TaskCallback()+0x359

>testee>err> pc 0x000055be2c1ccefb fp 0x00007fdde26fdd30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1cb

>testee>err> pc 0x000055be2c1cd939 fp 0x00007fdde26fdd80 dart::ThreadPool::Worker::Main(unsigned long)+0x179

>testee>err> pc 0x000055be2c106919 fp 0x00007fdde26fded0 out/DebugX64/dart+0x1efb919

>testee>err> -- End of DumpStackTrace

>testee>err> [exit     : sp(0) fp(0x7fdde26fc9f0) pc(0)]

>testee>err> [dart     : sp(0x7fdde26fca00) fp(0x7fdde26fca28) pc(0x7fdde12a8fd7) package:package_config/src/package_config_impl.dart_MutablePackageTree_get_allPackages__sync_op_gen ]

>testee>err> [dart     : sp(0x7fdde26fca38) fp(0x7fdde26fca78) pc(0x7fdde12a8d18) dart:core__SyncIterable@0150898_get_iterator ]

>testee>err> [dart     : sp(0x7fdde26fca88) fp(0x7fdde26fcb38) pc(0x7fdde12a08ca) package:package_config/src/package_config_impl.dart_SimplePackageConfig_SimplePackageConfig. ]

>testee>err> [dart     : sp(0x7fdde26fcb48) fp(0x7fdde26fcb98) pc(0x7fdde12989a0) package:package_config/src/package_config_json.dart_::_parsePackageConfigJson ]

>testee>err> [dart     : sp(0x7fdde26fcba8) fp(0x7fdde26fcc00) pc(0x7fdde128cbe7) package:package_config/src/package_config_json.dart_::_parsePackageConfigBytes ]

>testee>err> [dart     : sp(0x7fdde26fcc10) fp(0x7fdde26fcc70) pc(0x7fdde128ca9e) package:package_config/src/package_config.dart_PackageConfig_parseBytes ]

>testee>err> [dart     : sp(0x7fdde26fcc80) fp(0x7fdde26fcd20) pc(0x7fdde1970db3) package:front_end/src/base/processed_options.dart_ProcessedOptions__createPackagesFromFile@45081600__async_op ]

>testee>err> [dart     : sp(0x7fdde26fcd30) fp(0x7fdde26fcda0) pc(0x7fdde196dcc6) dart:async_::__rootRunUnary@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fcdb0) fp(0x7fdde26fce18) pc(0x7fdde196db3b) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fce28) fp(0x7fdde26fcec0) pc(0x7fdde196d6c6) dart:async__CustomZone@4048458_runUnary ]

>testee>err> [dart     : sp(0x7fdde26fced0) fp(0x7fdde26fcf10) pc(0x7fdde193874a) dart:async__FutureListener@4048458_handleValue ]

>testee>err> [dart     : sp(0x7fdde26fcf20) fp(0x7fdde26fcf78) pc(0x7fdde1938448) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]

>testee>err> [dart     : sp(0x7fdde26fcf88) fp(0x7fdde26fd000) pc(0x7fdde193771e) dart:async__Future@4048458__propagateToListeners@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd010) fp(0x7fdde26fd048) pc(0x7fdde19364b7) dart:async__Future@4048458__completeWithValue@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd058) fp(0x7fdde26fd088) pc(0x7fdde1933464) dart:async_::__completeOnAsyncReturn@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd098) fp(0x7fdde26fd140) pc(0x7fdde1972622) package:front_end/src/base/processed_options.dart_ProcessedOptions__readFile@45081600__async_op ]

>testee>err> [dart     : sp(0x7fdde26fd150) fp(0x7fdde26fd1c0) pc(0x7fdde196dcc6) dart:async_::__rootRunUnary@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd1d0) fp(0x7fdde26fd238) pc(0x7fdde196db3b) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd248) fp(0x7fdde26fd2e0) pc(0x7fdde196d6c6) dart:async__CustomZone@4048458_runUnary ]

>testee>err> [dart     : sp(0x7fdde26fd2f0) fp(0x7fdde26fd330) pc(0x7fdde193874a) dart:async__FutureListener@4048458_handleValue ]

>testee>err> [dart     : sp(0x7fdde26fd340) fp(0x7fdde26fd398) pc(0x7fdde1938448) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]

>testee>err> [dart     : sp(0x7fdde26fd3a8) fp(0x7fdde26fd420) pc(0x7fdde193771e) dart:async__Future@4048458__propagateToListeners@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd430) fp(0x7fdde26fd468) pc(0x7fdde19364b7) dart:async__Future@4048458__completeWithValue@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd478) fp(0x7fdde26fd4a8) pc(0x7fdde19362b3) dart:async__Future@4048458__asyncCompleteWithValue@4048458_<anonymous closure> ]

>testee>err> [dart     : sp(0x7fdde26fd4b8) fp(0x7fdde26fd520) pc(0x7fdde1949334) dart:async_::__rootRun@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd530) fp(0x7fdde26fd590) pc(0x7fdde1948f9a) dart:async_::__rootRun@4048458__rootRun@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd5a0) fp(0x7fdde26fd630) pc(0x7fdde19486e3) dart:async__CustomZone@4048458_run ]

>testee>err> [dart     : sp(0x7fdde26fd640) fp(0x7fdde26fd680) pc(0x7fdde194fdc6) dart:async__CustomZone@4048458_bindCallback_<anonymous closure> ]

>testee>err> [dart     : sp(0x7fdde26fd690) fp(0x7fdde26fd6c8) pc(0x7fdde1935ff3) dart:async_::__microtaskLoop@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd6d8) fp(0x7fdde26fd708) pc(0x7fdde1935c44) dart:async_::__startMicrotaskLoop@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd718) fp(0x7fdde26fd738) pc(0x7fdde1935b3b) dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]

>testee>err> [dart     : sp(0x7fdde26fd748) fp(0x7fdde26fd778) pc(0x7fdde19359d3) dart:isolate_::__runPendingImmediateCallback@1026248 ]

>testee>err> [dart     : sp(0x7fdde26fd788) fp(0x7fdde26fd7a0) pc(0x7fdde19061ed) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]

>testee>err> [entry    : sp(0x7fdde26fd7b0) fp(0x7fdde26fd818) pc(0x7fdde700286d)]

00:03 [32m+0[0m[31m -1[0m: next_through_is_and_as_test.dart (VM Service) [1m[31m[E][0m[0m

  NetworkRpcException(Canceling request: WebSocket closed(id: 6 method: getIsolate params: {isolateId: isolates/2627365169080299}))

  dart:async/future.dart 280:46                                  new Future.error
  package:observatory_2/src/service/object.dart 905:18           VM.invokeRpcNoUpgrade.<fn>
  package:stack_trace/src/stack_zone_specification.dart 126:26   StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 208:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 126:14   StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1194:47                                   _rootRunUnary
  dart:async/zone.dart 1097:19                                   _CustomZone.runUnary
  dart:async/future_impl.dart 160:20                             _FutureListener.handleError
  dart:async/future_impl.dart 708:47                             Future._propagateToListeners.handleError
  dart:async/future_impl.dart 729:24                             Future._propagateToListeners
  dart:async/future_impl.dart 537:5                              Future._completeError
  dart:async/future_impl.dart 593:7                              Future._asyncCompleteError.<fn>
  package:stack_trace/src/stack_zone_specification.dart 208:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 116:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 994:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1034:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 120:13                   _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 185:5                    _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                   _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 829:17                             _registerErrorHandler
  dart:async/future_impl.dart 308:17                             Future.catchError
  package:observatory_2/src/service/object.dart 903:8            VM.invokeRpcNoUpgrade
  package:observatory_2/src/service/object.dart 1575:15          Isolate.invokeRpcNoUpgrade
  package:observatory_2/src/service/object.dart 1609:12          Isolate._fetchDirect
  package:observatory_2/src/service/object.dart 346:7            ServiceObject.reload
  package:observatory_2/src/service/object.dart 316:12           ServiceObject.load
  package:observatory_2/src/service/object.dart 815:19           VM.getFromMap
  package:observatory_2/src/service/object.dart 4834:23          _upgradeList
  package:observatory_2/src/service/object.dart 4817:7           _upgradeMap.<fn>
  dart:collection-patch/compact_hash.dart 377:8                  _LinkedHashMapMixin.forEach
  package:observatory_2/src/service/object.dart 4813:7           _upgradeMap
  package:observatory_2/src/service/object.dart 4806:5           _upgradeCollection
  package:observatory_2/src/service/object.dart 1036:5           VM._update
  package:observatory_2/src/service/object.dart 396:5            ServiceObject.updateFromServiceMap
  package:observatory_2/src/service/object.dart 354:11           ServiceObject.reload.<fn>
  package:stack_trace/src/stack_zone_specification.dart 126:26   StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 208:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 126:14   StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1194:47                                   _rootRunUnary
  dart:async/zone.dart 1097:19                                   _CustomZone.runUnary
  dart:async/future_impl.dart 143:18                             _FutureListener.handleValue
  dart:async/future_impl.dart 696:45                             Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 725:32                             Future._propagateToListeners
  dart:async/future_impl.dart 529:5                              Future._completeWithValue
  dart:async-patch/async_patch.dart 254:13                       _completeOnAsyncReturn
  package:observatory_2/src/service/object.dart                  VM._fetchDirect
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                   _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 280:23                             Future.then
  package:observatory_2/src/service/object.dart 346:34           ServiceObject.reload
  package:observatory_2/src/service/object.dart 316:12           ServiceObject.load
  runtime/observatory_2/tests/service_2/test_helper.dart 404:22  _ServiceTesterRunner.run.<fn>.<fn>.<fn>
  runtime/observatory_2/tests/service_2/test_helper.dart 385:21  _ServiceTesterRunner.run.<fn>.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 126:26   StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 208:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 126:14   StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1194:47                                   _rootRunUnary
  dart:async/zone.dart 1097:19                                   _CustomZone.runUnary
  dart:async/future_impl.dart 143:18                             _FutureListener.handleValue
  dart:async/future_impl.dart 696:45                             Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 725:32                             Future._propagateToListeners
  dart:async/future_impl.dart 529:5                              Future._completeWithValue
  dart:async/future_impl.dart 567:7                              Future._asyncCompleteWithValue.<fn>
  package:stack_trace/src/stack_zone_specification.dart 208:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 116:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 994:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1034:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 120:13                   _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 185:5                    _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                   _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 280:23                             Future.then
  runtime/observatory_2/tests/service_2/test_helper.dart 385:16  _ServiceTesterRunner.run.<fn>.<fn>
  runtime/observatory_2/tests/service_2/test_helper.dart 373:9   _ServiceTesterRunner.run.<fn>.<fn>
  runtime/observatory_2/tests/service_2/test_helper.dart 360:16  _ServiceTesterRunner.run.ignoreLateException
  runtime/observatory_2/tests/service_2/test_helper.dart 358:24  _ServiceTesterRunner.run.ignoreLateException
  runtime/observatory_2/tests/service_2/test_helper.dart 372:32  _ServiceTesterRunner.run.<fn>
  package:test_api/src/backend/declarer.dart 300:61              Declarer._runSetUps.<fn>
  dart:async/future.dart 512:26                                  Future.forEach.<fn>
  dart:async/future.dart 554:26                                  Future.doWhile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 126:26   StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 208:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 126:14   StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1194:47                                   _rootRunUnary
  dart:async/zone.dart 1097:19                                   _CustomZone.runUnary
  dart:async/zone.dart 1002:7                                    _CustomZone.runUnaryGuarded
  dart:async/zone.dart 1039:26                                   _CustomZone.bindUnaryCallbackGuarded.<fn>
  dart:async/future.dart 570:18                                  Future.doWhile
  dart:async/future.dart 510:12                                  Future.forEach
  package:test_api/src/backend/declarer.dart 300:18              Declarer._runSetUps
  package:test_api/src/backend/declarer.dart 174:15              Declarer.test.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 173:22              Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 1626:10                                   _runZoned
  dart:async/zone.dart 1546:10                                   runZoned
  package:test_api/src/backend/declarer.dart 173:13              Declarer.test.<fn>
  package:test_api/src/backend/declarer.dart 156:53              Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 231:15               Invoker.waitForOutstandingCallbacks.<fn>
  package:test_api/src/backend/invoker.dart 228:14               Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 1626:10                                   _runZoned
  dart:async/zone.dart 1546:10                                   runZoned
  package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                   _CustomZone.registerUnaryCallback
  dart:async/zone.dart 1038:22                                   _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 550:34                                  Future.doWhile
  dart:async/future.dart 510:12                                  Future.forEach
  package:test_api/src/backend/declarer.dart 300:18              Declarer._runSetUps
  package:test_api/src/backend/declarer.dart 174:15              Declarer.test.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 173:22              Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 1626:10                                   _runZoned
  dart:async/zone.dart 1546:10                                   runZoned
  package:test_api/src/backend/declarer.dart 173:13              Declarer.test.<fn>
  package:test_api/src/backend/declarer.dart 156:53              Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 231:15               Invoker.waitForOutstandingCallbacks.<fn>
  package:test_api/src/backend/invoker.dart 228:14               Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 1626:10                                   _runZoned
  dart:async/zone.dart 1546:10                                   runZoned
  package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 40:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 1626:10                                   _runZoned
  dart:async/zone.dart 1546:10                                   runZoned
  package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 415:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 94:24                       Chain.capture.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 1626:10                                   _runZoned
  dart:async/zone.dart 1546:10                                   runZoned
  package:stack_trace/src/chain.dart 92:12                       Chain.capture
  package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1178:47                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 994:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1034:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1186:13                                   _rootRun
  dart:async/zone.dart 1090:19                                   _CustomZone.run
  dart:async/zone.dart 994:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1034:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 120:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 402:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 426:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12                   _RawReceivePortImpl._handleMessage


** Killing script

00:03 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python tools/test.py -n app_jitk-linux-debug-x64 service_2/next_through_is_and_as_test/service
```

**Comment by bkonyi** [comment] 2020-11-16 22:11
@cskau-g is this possibly related to the issues you've been investigating?

**Comment by cskau-g** [comment] 2020-11-17 07:59
Looks like a `getIsolate` VM Service request that's triggering an assert at `runtime/vm/scopes.cc:386`, so I'd say it is likely not related to any of the stack trace work I've been doing. Sorry.

**Comment by bkonyi** [comment] 2020-11-17 16:43
No worries! I'll take a look.

**Comment by bkonyi** [comment] 2020-12-22 21:08
I'm unable to reproduce as of 4245ca05a9d1c4851b7accc080624b48f5e9fc4f. Closing for now.

**Closed by bkonyi** 2020-12-22 21:08 UTC
Labels: P2, area-vm, gardening
