### ISSUE TITLE
Analyzer warnings produced when SDK lower bound is too low are hard to read

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#40164] opened 2020-01-15 15:45 UTC
It seems like the `extension` keyword isn't being recognized. See https://github.com/dart-lang/site-www/issues/2214 for details.

**Comment by bwilkerson** [comment] 2020-01-15 16:23
I believe that the issue is the SDK constraints in the `pubspec.yaml`. The lower bound is currently `2.0.0`, but it needs to be at least `2.6.0` in order to enable extensions. If you update the SDK constraints it should make the errors go away.

**Comment by kwalrath** [comment] 2020-01-15 16:47
I think those constraints are only for tools, rather than tests, but I'll check on that. These tests are supposed to be conducted with the latest dev channel (and that's what `dart --version` shows), but it's possible there's an interaction somewhere. The fact that the test failure is happening now, and only with dev channel, makes me think it's a change in Travis or in the SDK.

**Comment by bwilkerson** [comment] 2020-01-15 16:54
My understanding is that those constraints now control how analyzer (at least, possibly other tools as well) decide which features are enabled. The lower bound basically says "this code is expected to run on a 2.0.0 VM", which didn't support extensions, so that feature is disabled as a result. So if the tests are running analyzer, then it now matters for the tests. (This might be the first dev version to implement those semantics.)

**Comment by kwalrath** [comment] 2020-01-15 23:44
@johnpryan found the pubspec file that needed to be updated. (It had a lower bound of 2.5.) Soon the build will be fixed, whew!

It would've helped us diagnose this problem if we'd gotten a clear message about the SDK lower bound. Would something like the following be possible?

> The file `path/to/something.dart` uses a keyword (extension) that was introduced in 2.7.0, but the pubspec file file (`path/to/pubspec.yaml`) has a lower SDK bound of 2.5.0. Update the lower bound to at least 2.7.0.`

**Comment by bwilkerson** [comment] 2020-01-16 00:09
I think so. It would certainly be a good goal.

**Comment by mit-mit** [comment] 2020-01-16 09:57
Current error (grabbed from the linked bug:

```console
Analyzing analysis_options.yaml, bin, lib, test...
  error â€¢ Undefined class 'extension'. â€¢ lib/effective_dart/style_good.dart:108:1 â€¢ undefined_class
...
10 errors and 4 lints found.
```

**Comment by greglittlefield-wf** [comment] 2020-07-09 14:37
It's worth noting that the error messages used to be helpful, and this issue was introduced between Dart 2.7.2 and 2.8.1. See https://github.com/dart-lang/sdk/issues/42148 for more info

**Comment by srawlins** [comment] 2023-02-01 21:33
Strange regression, but I'll note that we can close this with Dart 3.0, in which 2.12 is the lowest valid language version.

**Comment by bwilkerson** [comment] 2023-02-01 21:39
That will prevent this specific diagnostic, but won't prevent similar diagnostics for other language features. If the problem was with this one message, then great. If this message was one example of a class of messages, then the problem still needs to be addressed.

**Comment by srawlins** [comment] 2023-02-01 21:42
Agreed. If it is reported again, we can prioritize that report.

**Closed** 2024-10-01 21:33 UTC
Labels: area-analyzer, analyzer-ux, type-enhancement, P4
