### ISSUE TITLE
invalid_assignment false positive with mixed migrated files

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#42706] opened 2020-07-15 14:41 UTC
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev cfeb1d647a)

In the following code an `invalid_assignment` is triggeredfor `value` assignment.

```dart
//-------------------- a.dart

// @dart = 2.8
import 'b.dart';
class _BottomAppBarClipper extends CustomClipper<int> {}
void main() {
  // A value of type 'Listenable' can't be assigned to a variable of type 'CustomClipper<Path>'.
  // Try changing the type of the variable, or casting the right-hand type to 'CustomClipper<Path>'.
  CustomClipper<int> value = true ? _BottomAppBarClipper() : ShapeBorderClipper();
}

//-------------------- b.dart

// @dart = 2.9
abstract class Listenable {}
abstract class CustomClipper<T> extends Listenable {}
class ShapeBorderClipper extends CustomClipper<int> {}
```

**Comment by scheglov** [comment] 2020-07-15 17:09
@leafpetersen Are there any spec changes necessary for Null Safety and LUB?

[The spec](https://spec.dart.dev/DartLangSpecDraft.pdf) says in `19.10.2 Least Upper Bounds` says:
![image](https://user-images.githubusercontent.com/384794/87573955-835a4200-c682-11ea-8c74-ab32a07cdb3c.png)
Here two sets of types are `{CustomClipper<int*>*, Listenable*, Object*, _BottomAppBarClipper*}` and `{CustomClipper<int>, Listenable, Object, ShapeBorderClipper}`. But `CustomClipper<int*>*` and `CustomClipper<int>` are not the same type, so we exclude it from the intersection.

[The upper / lower bounds spec](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md) does not change rules for interface types.

When we started working on Null Safety in analyzer we found that nullability suffixes are problematic for LUB, so @stereotype441  suggested stripping them off, and apply after LUB, which makes sense because supertypes cannot be `?`. But their type arguments can be. So, I think we need some clarification of LUB of interface types for Null Safety.

**Comment by scheglov** [comment] 2020-07-17 15:35
@eernstg @leafpetersen

**Comment by leafpetersen** [comment] 2020-07-22 03:53
I can't reproduce this in either the analyzer or the CFE.  Interestingly, if I remove the type annotation on `value` though, I do see an inferred type of `Listenable` in both implementations:

```dart
//-------------------- a.dart

// @dart = 2.8
import 'b.dart';
class _BottomAppBarClipper extends CustomClipper<int> {}
void main() {
  // A value of type 'Listenable' can't be assigned to a variable of type 'CustomClipper<Path>'.
  // Try changing the type of the variable, or casting the right-hand type to 'CustomClipper<Path>'.
  var value = true ? _BottomAppBarClipper() : ShapeBorderClipper();
  int z = value; // Error indicates value is inferred as Listenable
}
```

@scheglov @johnniwinther I'll spec up the expected behavior for LUB here, but I don't understand why I'm seeing different behavior with and without the type annotation.

**Comment by leafpetersen** [comment] 2020-07-22 04:32
Spec proposal here:  https://github.com/dart-lang/language/pull/1109 .

**Comment by eernstg** [comment] 2020-07-23 08:38
@scheglov wrote:
> Here two sets of types are `{CustomClipper<int*>*, Listenable*, Object*, _BottomAppBarClipper*}`
> and `{CustomClipper<int>, Listenable, Object, ShapeBorderClipper}`. But
> `CustomClipper<int*>*` and `CustomClipper<int>` are not the same type, so we exclude it
> from the intersection.

Prior to any computations on these sets, I think it's worth considering the elements: I would expect that a superinterface relation does not introduce the legacy marker `*` at the top level: For example, with legacy classes `class A {}` and `class B extends A {}`, `B` has `A` as a superinterface, not `A*`. In contrast, with legacy classes `class C<X> {}` and `class D extends C<int> {}`, `D` has `C<int*>` as a superinterface. The point is that if an expression has type `B` then it can also be considered to have type `A`, and this transition does not introduce a different nullability; but with type arguments in superinterfaces specified in legacy libraries, we must add `*` (because the legacy code can override inherited members without nullability related constraints).

This would make the two sets (with depths) `{CustomClipper<int*>/2, Listenable/1, Object/0, _BottomAppBarClipper/3}` and `{CustomClipper<int>/2, Listenable/1, Object/0, ShapeBorderClipper/3}`, which yields `Listenable`.

So isn't that what the analyzer actually does already?

In comments on https://github.com/dart-lang/language/pull/1109 I'm suggesting that we might want to reduce the sets at each depth (e.g., the set at depth 2: `{CustomClipper<int>, CustomClipper<int*>}`) using `NNBD_TOP_MERGE` where possible (yielding `{CustomClipper<int>}`), which would yield the LUB `CustomClipper<int>`.

**Comment by scheglov** [comment] 2020-07-23 20:29
@leafpetersen You need to disable implicit casts to get this error. In legacy libraries it is allowed by the spec.
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

@eernstg Yes, as I described in my first comment, we do remove top-level `*` suffixes from the super-interfaces. And yes, we get `Listenable` as the result of `LUB` now. But I guess this is not perfect :-)

**Comment by eernstg** [comment] 2020-07-24 13:41
> we do remove top-level `*` suffixes

Right; I was thinking about not having them in the first place, cf. the text [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#classes-defined-in-legacy-libraries):

> A direct super-interface of a class defined in a legacy library (...)
> has all generic arguments (...) marked as legacy types.

It doesn't say that the type which is the super-interface as a whole is marked as legacy, only its type arguments and down. But it shouldn't make much difference. ;)

**Comment by scheglov** [comment] 2020-08-01 18:05
This was fixed by adapting Least Upper Bound implementation for null safety, as requested in https://github.com/dart-lang/sdk/issues/42837.

**Closed by scheglov** 2020-08-01 18:05 UTC
Labels: NNBD, P1, area-analyzer, needs-info
