### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sinxiao** [dart-lang/sdk#38137] opened 2019-08-30 09:46 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Exception while using a UseFullHexValuesForFlutterColors to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
Bad state: No element
#0      _NodeListImpl&Object&ListMixin.first (dart:collection/list.dart:75:22)
#1      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/use_full_hex_values_for_flutter_colors.dart:58:52)
#2      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#3      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#4      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#5      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#6      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#7      RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#8      LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#9      NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#16     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#17     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#18     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#19     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#20     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#21     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#23     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#24     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#25     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#26     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#27     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#28     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#29     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#30     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#31     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#32     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#33     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#35     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#36     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:625:10)
#37     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#38     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#39     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:991:10)
#40     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:384:11)
#41     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#42     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#43     RecursiveAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:1075:10)
#44     LinterVisitor.visitNamedExpression (package:analyzer/src/lint/linter_visitor.dart:468:11)
#45     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#46     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#47     ArgumentListImpl.visitChildren (package:analyzer/src/dart/as...
```

For additional log information, please append the contents of
file:///private/var/folders/g7/5mnnksfx62sgcvl_29nvjpvc0000gn/T/report1.txt.

**Comment by srawlins** [comment] 2019-08-30 18:29
Thanks for reporting this issue! This was previously reported at #37879; please follow along there.

**Comment by srawlins** [comment] 2019-08-30 18:29
Duplicate of #37879

**Closed by srawlins** 2019-08-30 18:29 UTC
Labels: analyzer-crash-report, analyzer-server, area-analyzer, type-bug
