### ISSUE TITLE
We don't need labels for instantiations that use just one line

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30979] opened 2017-10-03 20:19 UTC
```dart
class RecursiveContinuationRewriter extends Transformer {
  final HelperNodes helper;
  final VariableDeclaration asyncJumpVariable = new VariableDeclaration(
      ":await_jump_var",
      initializer: new IntLiteral(0));
```

produces:
![image](https://user-images.githubusercontent.com/384794/31146918-0442f78e-a83d-11e7-8e91-286aa81c2512.png)

But I think we don't need `IntLiteral`.

**Comment by devoncarew** [comment] 2017-10-03 20:20
In case a short repro doesn't reproduce, can you add the path to the file in the sdk where you're seeing this?

**Comment by scheglov** [comment] 2017-10-03 20:24
A slightly clean up code
```dart
class C  {
  final f = new A(
      0,
      new B());
}

class A {
  A(_, __);
}

class B {}
```
![image](https://user-images.githubusercontent.com/384794/31147279-335de6e0-a83e-11e7-985e-1f0b2859c644.png)

**Comment by devoncarew** [comment] 2017-10-03 22:54
This is occurring because both A and B terminate on the same line. If you introduce a newline you only see the closing label for A:

<img width="204" alt="screen shot 2017-10-03 at 3 53 29 pm" src="https://user-images.githubusercontent.com/1269969/31152930-2024af40-a853-11e7-9d46-02b0803384b5.png">

**Comment by devoncarew** [comment] 2017-10-03 22:55
I guess, from visual inspection about, that the closing label for B doesn't add value, even for consistency (that we're showing one for the A ctor, we so choose to show all closing labels on that line, even one-line ctors).

**Comment by devoncarew** [comment] 2017-10-03 22:57
Or to re-state: we shouldn't ever show a closing label for an item that doesn't span multiple lines.

**Comment by devoncarew** [comment] 2017-10-06 19:20
fixed

**Closed by devoncarew** 2017-10-06 19:20 UTC
Labels: area-intellij
