### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Could not load dart file /Users/ukasz.apps/projects/private/fairbid_flutter/example/lib/banner_ads.dart

### ISSUE THREAD

**Issue by ukasz123** [dart-lang/sdk#45281] opened 2021-03-11 04:32 UTC
Could not load dart file /Users/ukasz.apps/projects/private/fairbid_flutter/example/lib/banner_ads.dart

Error: Error reaching migration preview server.

Please fill in the following:

**Name of package being migrated (if public)**: fairbid_flutter
**What I was doing when this issue occurred**: 
I tried to migrate example app for plugin and I selected first file (`banner_ads.dart`). This does not happen for any other file.
**Is it possible to work around this issue**: No. I just skipped problematic file(s) and did migration by hand.
**Has this issue happened before, and if so, how often**:
When I migrated library implementation for that plugin it occurred when I tapped first and second(!) file. Then I unselected them and proceeded with other files
**Dart SDK version**: 2.12.0
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
Error reaching migration preview server.
    at Object.b (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:311:3)
    at http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:3133:9
    at Gs.a (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:1572:72)
    at Gs.$2 (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:4670:23)
    at SX.$2 (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:4665:25)
    at Ji.rp (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:4942:25)
    at Fe.Kw (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:4727:27)
    at RW.$0 (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:4875:42)
    at Object.HZ (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:1620:76)
    at vs.ZL (http://127.0.0.1:54163/Users/ukasz.apps/projects/private/fairbid_flutter/example?authToken=iMVbqmDoEmI%3D:4788:3)
```

**Comment by stereotype441** [comment] 2021-03-22 11:04
Duplicate of #45202

**Closed by stereotype441** 2021-03-22 11:04 UTC
Labels: P1, area-migration
