### ISSUE TITLE
Multiplying two double values giving wrong and negative result

### ISSUE THREAD

**Issue by MohanaSync** [dart-lang/sdk#39962] opened 2020-01-02 09:38 UTC
I need to multiply two large numbers for example,

 ```
double x = 318191400000;
 double result =x*x;
```

But i am getting negative value for this when building in flutter .

Please help me on this.

![image](https://user-images.githubusercontent.com/58970457/71660644-bb96d480-2d71-11ea-8acf-3c1ad6d16a8b.png)

**Comment by lrhn** [comment] 2020-01-02 10:46
This is an interesting bug. It does not reproduce locally on Linux, so it seems like it's an effect of the way the code is compiled or run. As if the back-end treats double values like integers.

**Comment by MohanaSync** [comment] 2020-01-02 10:49
Any possible solution for this right now?

**Comment by mkustermann** [comment] 2020-01-02 12:28
@MohanaSync From the screenshot above it says `xValues[index] * xValues[index]`. What is the type of `xValues`?

Could it be that there is a `.toDouble()` missing, i.e. `xValues[index].toDouble()`?

**Comment by MohanaSync** [comment] 2020-01-02 12:31
@mkustermann  u got it.. I have resolved this already by adding `.toDouble()`.

Now its fine (y)

**Comment by mkustermann** [comment] 2020-01-02 12:33
Let's close the issue then, since it is working as intended?

**Closed by mkustermann** 2020-01-02 12:33 UTC
Labels: area-vm, type-bug
