### ISSUE TITLE
2.0.0-dev.0.0 Getting an error when creating a web-app.

### ISSUE THREAD

**Issue by ksdboasit** [dart-lang/sdk#30803] opened 2017-09-19 15:16 UTC
Summary: I'm getting an error during pub get for the sample bare-bones web app, with 

What steps will reproduce the problem?
Create a new project with generated sample content. Select Bare-bones Web App.
Wait for dependancies to be resolved.
Look in the tab labeled messages.

What is the expected output? What do you see instead?
Expected:
Nothing special.

Actual:
Getting the following error:
`Loading dart_to_js_script_rewriter transformers...
Failed to compile a snapshot to .pub\transformers\transformers.snapshot:
Unhandled exception:
NoSuchMethodError: The method 'send' was called on null.
Receiver: null
Tried calling: send(SendPort)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      loadTransformers (package:$pub/transformer_isolate.dart:21:11)
#3      main (file:///C:/Users/ksd/AppData/Local/Temp/pub_b93bf5e4-9d4c-11e7-90f3-4ccc6a0124ac/runInIsolate.dart:4:35)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Precompiled dart_to_js_script_rewriter.
Process finished with exit code 0`

What version of the product are you using?
Dart SDK 2.0.0-dev.0.0
WebStorm 2017.2.4

On what operating system?
Windows 10 and Mac OS (Sierra)

Please provide any additional information below.

The error doesn't seem to do anything critical.

**Comment by kevmoo** [comment] 2017-09-19 15:21
Duplicate of https://github.com/dart-lang/sdk/issues/30790

**Closed by kevmoo** 2017-09-19 15:21 UTC
