### ISSUE TITLE
Analyzer crash: `isEoF` called on null

### ISSUE THREAD

**Issue by daneraguilar** [dart-lang/sdk#38405] opened 2019-09-15 23:52 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0, server version 1.27.2, error: Captured exception
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      scannerRecovery (package:front_end/src/fasta/scanner/recover.dart:31:17)
#2      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:103:14)
#3      scanString (package:front_end/src/fasta/scanner.dart:95:10)
#4      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:146:34)
#5      _File._parse (package:analyzer/src/services/available_declarations.dart:1835:25)
#6      _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#7      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#8      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#9      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#12     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#15     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#21     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#22     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#23     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#24     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#33     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#34     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#35     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#36     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#37     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\daner\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-09-16 17:34
Thanks for reporting this issue! This looks similar to https://github.com/dart-lang/sdk/issues/37878, but the top of the stack is different enough that I'll let @scheglov or @danrubel decide if it's the same issue.

**Comment by scheglov** [comment] 2019-09-16 17:53
Looks like a parser / scanner issue.
Does not look like https://github.com/dart-lang/sdk/issues/37878 though.

**Comment by kw2019ltd** [comment] 2020-05-16 14:11
## Dart analysis issue

NoSuchMethodError: The getter 'isEof' was called on null.

## Version information

- Dart SDK 2.8.2
- Dart IntelliJ 192.8052
- Android Studio 3.6.3
- Windows 10 10.0

## Details

NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof

```
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## Debug log

```
1589638020811 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":447,"uri":"package:sunny_dart/time.dart","items":[{"label":"parseTimeSpans","declaringLibraryUri":"packa...
1589638020811 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":448,"uri":"package:flutter_contact/contact.dart","items":[{"label":"Contact","declaringLibraryUri":"pack...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":449,"uri":"package:logging_config/console_interface.dart","items":[{"label":"logToConsole","declaringLib...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":450,"uri":"package:worker_service/worker_service_interface.dart","items":[{"label":"getErrorsForRunner",...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":451,"uri":"package:isolate/runner.dart","items":[{"label":"Runner","declaringLibraryUri":"package:isolat...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":452,"uri":"package:isolate/load_balancer.dart","items":[{"label":"LoadBalancer","declaringLibraryUri":"p...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":453,"uri":"package:worker_service/common.dart","items":[{"label":"InitializerWithParam","declaringLibrar...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":454,"uri":"package:worker_service/worker_service.dart","items":[{"label":"killRunner","declaringLibraryU...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":455,"uri":"package:logging_config/logging_config.dart","items":[{"label":"onLogConfigured","declaringLib...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":456,"uri":"package:logging/logging.dart","items":[{"label":"hierarchicalLoggingEnabled","declaringLibrar...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":460,"uri":"package:flutter_contact/paging_iterable.dart","items":[{"label":"PagingStream","declaringLibr...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":461,"uri":"package:equatable/equatable.dart","items":[{"label":"EquatableMixin","declaringLibraryUri":"p...
1589638020842 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":464,"uri":"package:flutter_contact/contacts.dart","items":[{"label":"parseTimeSpans","declaringLibraryUr...
1589638020842 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":465,"uri":"package:firebase_ml_vision/firebase_ml_vision.dart","items":[{"label":"RecognizedLanguage","d...
1589638020842 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":471,"uri":"package:qr_flutter/qr_flutter.dart","items":[{"label":"QrEmbeddedImageException","declaringLi...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":483,"uri":"package:barcodeapp/generated/intl/messages_ru.dart","items":[{"label":"MessageLookup","declar...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":484,"uri":"package:barcodeapp/generated/intl/messages_he.dart","items":[{"label":"MessageLookup","declar...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":485,"uri":"package:barcodeapp/generated/intl/messages_en.dart","items":[{"label":"MessageLookup","declar...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":486,"uri":"package:barcodeapp/generated/intl/messages_ar.dart","items":[{"label":"MessageLookup","declar...
1589638020864 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":487,"uri":"package:nested/nested.dart","items":[{"label":"Nested","declaringLibraryUri":"package:nested/...
1589638020864 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":488,"uri":"package:provider/provider.dart","items":[{"label":"Selector","declaringLibraryUri":"package:p...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":499,"uri":"package:smooth_star_rating/smooth_star_rating.dart","items":[{"label":"SmoothStarRating","dec...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":500,"uri":"package:shared_preferences_platform_interface/method_channel_shared_preferences.dart","items"...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":501,"uri":"package:shared_preferences_platform_interface/shared_preferences_platform_interface.dart","it...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":502,"uri":"package:shared_preferences/shared_preferences.dart","items":[{"label":"SharedPreferences","de...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":503,"uri":"package:rate_my_app/rate_my_app.dart","items":[{"label":"DialogStyle","declaringLibraryUri":"...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":509,"uri":"package:package_info/package_info.dart","items":[{"label":"PackageInfo","declaringLibraryUri"...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":510,"uri":"package:barcodeapp/utils/package_Info.dart","items":[{"label":"initPackageInfo","declaringLib...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":511,"uri":"package:intl/message_lookup_by_library.dart","items":[{"label":"CompositeMessageLookup","decl...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":512,"uri":"package:barcodeapp/generated/intl/messages_all.dart","items":[{"label":"LibraryLoader","decla...
```

**Comment by srawlins** [comment] 2021-01-26 23:25
Duplicate of https://github.com/dart-lang/sdk/issues/41658

**Comment by srawlins** [comment] 2021-01-26 23:25
While this issue is older, there is more discussion at https://github.com/dart-lang/sdk/issues/41658.

**Closed by srawlins** 2021-01-26 23:25 UTC
Labels: analyzer-crash-report, area-analyzer, area-front-end, front-end-fasta-recovery, type-bug
