### ISSUE TITLE
Migration tool null safety detection fails when tests use path imports

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#44394] opened 2020-12-04 10:23 UTC
If a test imports the library under test with a path dependency, then the migration tool fails to identify it as the library being migrated, and fails. While these is not the recommended style for imports in tests, seems like we shouldn't fail though? cc @stereotype441 

`<package>/test/<package>_test.dart`:
```
import '../lib/lix.dart';

...
```

Try to migrate:
```
$ dart migrate
...
Analyzing project...
[-----------------------------------------------------------------------------------------------------------------------------------------|]Bad state: Error: package has unmigrated dependencies.

Before migrating your package, we recommend ensuring that every library it
imports (either directly or indirectly) has been migrated to null safety, so
that you will be able to run your unit tests in sound null checking mode.  You
are currently importing the following non-null-safe libraries:

  file:///Users/mit/dev/null_safety_demos/calculate_lix/lib/lix.dart
```

**Comment by stereotype441** [comment] 2022-09-14 16:05
I'm unable to reproduce this.  I believe there have been changes made to the analyzer to address this sort of problem since the sisue was filed in December of 2020, so I think it's most likely that the issue was fixed by those changes.

I'm adding a unit test to the migration tool to ensure that the fix doesn't regress (https://dart-review.googlesource.com/c/sdk/+/259200).  Once that lands I'll close the issue.  I see that a lot of people have given this bug a "thumbs up".  If any of you are still experiencing this problem, please feel free to re-open.

**Comment by stereotype441** [comment] 2022-09-14 16:12
Unit test has landed, so closing this issue as irreproducible.  Once again, please feel free to re-open if you're still experiencing this problem.

**Closed by stereotype441** 2022-09-14 16:12 UTC
Labels: P3, NNBD, area-migration
