### ISSUE TITLE
JavaScript compilers support for `--native-null-assertions` in Dart 3.0

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#50710] opened 2022-12-13 22:59 UTC
Regarding the `--native-null-assertions` flag. It provides non-null assertions on values returned from browser APIs when the dart:html library specifies the API should be non-nullable. For each compiler we should consider if this is enabled by default, and if so can it be disabled? 

For DDC this is a question of what flags are supported when you try to run a debug app with package:webdev or flutter web. For dart2js it includes those and what flags are available through `dart compile js`.

cc @sigmundch @srujzs @mit-mit @itsjustkevin

**Comment by nshahan** [comment] 2022-12-13 23:15
cc @jakemac53

**Comment by jakemac53** [comment] 2022-12-13 23:27
I would probably have it on by default, with the flag to disable it. And dart2js may choose to disable it by default at certain optimization levels also.

**Comment by srujzs** [comment] 2022-12-13 23:35
My preference and summarizing my previous comments:

- If we're running in sound null-safety and SDK version is > 3.0.0, we have it on by default in both compilers to ensure soundness.
- If dart2js specifies O3 or higher, we disable these assertions for performance.

We could have it so that you can't disable it (% optimization flags), but maybe that's too restrictive. The problem, though, is google3 and possibly even Flutter have it disabled by default. We'd want to change that if we're saying you can still disable it. Eventually, we want to remove this flag/option altogether, but that's further in the future.

**Comment by nshahan** [comment] 2023-02-06 20:31
@srujzs
> * If we're running in sound null-safety and SDK version is > 3.0.0, we have it on by default in both compilers to ensure soundness.
> * If dart2js specifies O3 or higher, we disable these assertions for performance.

Does this accurately describe the combination space for these flags that you would like to see?

| | `--native-null-assertions` | `--no-native-null-assertions` |
| --- | --- | --- |
| **`-o2` and below** | no-op (already enabled by default) | disable the native assertions | 
| **`-o3` and above** | no-op (checks get removed at these optimization levels) | no-op (checks are already removed at these optimization levels) |

**Comment by srujzs** [comment] 2023-02-06 23:47
Yes, but there was the open question of whether we want to ignore `--no-native-null-assertions` (or even better, warn that this isn't supported > 3.0.0), and still assert except for optimization reasons.

This may prove to be a bigger change to plumb through, and I expect the need to use `--no-native-null-assertions` will be very low, so I think that table is probably the best idea going forward.

**Comment by nshahan** [comment] 2023-02-15 00:20
@jakemac53
What is the status of this flag in the release of build_web_compilers we did for Dart 3.0? On by default with the ability to disable?

**Comment by jakemac53** [comment] 2023-02-15 00:37
Correct, it is currently enabled by default and you can disable it in build.yaml (or with a --define flag).

**Comment by nshahan** [comment] 2023-02-15 19:05
@srujzs 
In a conversation with @sigmundch he said we should investigate allowing the checks to be manually enabled in `-o3` and above when you pass the flag. Other options do allow for them the values prescribed by the `-o` flag to be overridden manually at those levels.

**Comment by srujzs** [comment] 2023-02-15 21:39
How can we differentiate that versus a default? If by default, they are enabled, and then the user uses `-o3`, how can we tell whether `--native-null-assertions` was a "default yes" versus a "manual yes"?

**Comment by jakemac53** [comment] 2023-02-15 21:50
With the args package you can ask if something was actually provided as an argument with [wasParsed](https://pub.dev/documentation/args/latest/args/ArgResults/wasParsed.html)

**Comment by jakemac53** [comment] 2023-02-15 21:52
Note though that build_web_compilers will always pass the argument with an explicit value. We could change that behavior, but we do it to make things more explicit, and avoid having to make changes when a compiler changes its default.

**Comment by srujzs** [comment] 2023-02-15 21:55
Yeah, I think the issue is that dart2js always gets some value from the different platforms. I'm not sure if it can know whether a google3 user manually passed in `--native-null-assertions`, or if it's getting it from the google3 defaults.

**Comment by srujzs** [comment] 2023-02-15 23:29
Talked briefly offline, but it seems like to support this, we should just remove the default values that the different platforms set if any (Flutter, build_web_compilers, and google3 are the only ones I can think of). Then the only other new thing to do is that for dart2js, if `--native-null-assertions` was explicitly passed in, we check even if `-O3` is enabled. The behavior of DDC is unchanged.

**Comment by jakemac53** [comment] 2023-02-16 01:51
I would be fine with changing the setting to nullable in build_web_compilers and then only passing an argument if we received actual explicit config.

**Comment by itsjustkevin** [comment] 2023-03-20 19:42
@nshahan are we still expecting to have this and the associated changes in by Beta 3?

**Comment by srujzs** [comment] 2023-03-20 19:59
> @nshahan are we still expecting to have this and the associated changes in by Beta 3?

Yes. Nick landed the DDC changes a while ago and I have the dart2js changes in review.

**Comment by itsjustkevin** [comment] 2023-03-20 20:23
Thank you @srujzs

**Comment by srujzs** [comment] 2023-03-20 23:16
@itsjustkevin We chatted earlier and noticed that this change introduces a (small) breaking change. I went through the [process](https://github.com/dart-lang/sdk/blob/main/docs/process/breaking-changes.md) of filing an issue and sending an announcement: https://github.com/dart-lang/sdk/issues/51799. Let me know if there's anything else I should do for the approval process. Thanks!

**Comment by itsjustkevin** [comment] 2023-03-21 00:00
@srujzs I have noted this in an issue to track, tomorrow, could you send me the announcement you would like to send out?

**Comment by srujzs** [comment] 2023-03-21 00:08
Thanks! This was my email I tried to send out:

Subject:

Breaking change [#51799]: Dart web libraries will null assert web library APIs in Dart 3

Body:

Native web library APIs, like the ones in `dart:html`, will have their return values be null-asserted if they are non-nullable. We have compiler flags, `nativeNonNullAsserts` and `--native-null-assertions` in DDC and dart2js, respectively, to check this already. However, the default values of these flags were false. For Dart 3, the defaults will now be true.

For more information and details on how to turn this off if needed, see https://github.com/dart-lang/sdk/issues/51799.

Please comment on the bug if you have any questions or concerns. Thanks!

**Comment by itsjustkevin** [comment] 2023-03-21 14:36
@srujzs the rules were adjusted for the email group.  Could you try sending the email again as a final test before I update the docs?

**Comment by srujzs** [comment] 2023-03-21 16:08
Looks like it didn't bounce this time, done!

**Comment by sigmundch** [comment] 2023-04-03 16:55
Note that https://dart-review.googlesource.com/c/sdk/+/289451, which finishes work related to this issue is in the CQ. We expect this issue to be closed shortly after.

**Comment by srujzs** [comment] 2023-04-03 20:28
Waited until I got the go ahead to land, but the CL is in now, so I'm closing this issue.

**Closed by srujzs** 2023-04-03 20:28 UTC
Labels: web-dart2js, web-libraries, P2, web-dev-compiler, area-web
