### ISSUE TITLE
Ternary operator between enums implementing the same interface fails to infer common type

### ISSUE THREAD

**Issue by Thurler** [dart-lang/sdk#51996] opened 2023-04-09 04:55 UTC
I have two enhanced enums, `A` and `B`, both implementing the same interface `C`. A ternary operator that tries to assign a value of each enum to a variable of type `C` gives me a `argument_type_not_assignable` error. A sample code, along with the full error message:

```dart
abstract class C {
  final int c;
  C(this.c);
}
enum A implements C {
  v(0);
  @override
  final int c;
  const A(this.c);
}
enum B implements C {
  v(10);
  @override
  final int c;
  const B(this.c);
}
C getV(bool foo) => foo ? A.v : B.v;
// (Compiler) A value of type '_Enum' can't be returned from a function with return type 'C'
// (Analyze) A value of type 'Object' can't be returned from the function 'getV' because it has a return type of 'C'.
```
Note that the compiler and the analyzer disagree on the upper bound. I can see why the inference would end up at `_Enum`, but there should be some way to infer the resulting type is `C` without an explicit cast, in my opinion. Casting either operand or the result solves the issue (though the analyzer gives me an uneccesary cast warning for the first case):
```dart
C getV(bool foo) => foo ? (A.v as C) : B.v; // warning: unnecessary cast
C getV(bool foo) => foo ? A.v : (B.v as C); // warning: unnecessary cast
C getV(bool foo) => (foo ? A.v : B.v) as C; // no issues
```
Similar to dart-lang/language#2432, dart-lang/language#2577, dart-lang/language#1904, dart-lang/language#1877, and dart-lang/language#2216. Those are all issues regarding this ternary upper bound logic, but because this case I ran into involves extended enums I figured it could at least become a test case when trying to resolve the root problem.

**Comment by lrhn** [comment] 2023-04-09 21:05
Seems to be a duplicate of #51730.

I wish we'd define LUB to not include private declarations that are not accessible where the operation happens.

**Closed by lrhn** 2023-04-09 21:05 UTC

**Comment by eernstg** [comment] 2023-04-11 10:07
@Thurler, you might want to take a look at this [language issue topic](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aleast-upper-bound), where improvements to the upper-bound algorithm are discussed.
