### ISSUE TITLE
Isolate spawn tests failing in unchecked mode on vm, d8, and chrome

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#27185] opened 2016-08-29 14:46 UTC
The two tests:
  co19/LibTest/isolate/Isolate/spawn_A02_t04: RuntimeError
  co19/LibTest/isolate/Isolate/spawn_A02_t05: RuntimeError

are failing on the vm, d8, and chrome in unchecked mode, but not in checked mode on vm and d8, or on dartium.

If the tests are wrong, please file a co19 issue on them, otherwise, there is an error in isolate.
These tests are marked as RuntimeError in the co19-runtime and co19-dart2js status files.

**Comment by floitschG** [comment] 2016-08-29 14:47
I will have a look.

**Comment by floitschG** [comment] 2016-08-29 15:22
Filed https://github.com/dart-lang/co19/issues/75

**Comment by whesse** [comment] 2016-09-01 17:30
We have now seen a crash on the vm when running this test:
FAILED: none-vm release_x64 co19/LibTest/isolate/Isolate/spawn_A02_t05
Expected: RuntimeError 
Actual: Crash
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.fail('Isolate.spawn(entryPointNoArgs, 'hello') is expected to fail')
#0 _fail (file:///b/build/slave/vm-mac-release-x64-be/build/sdk/tests/co19/src/Utils/expect.dart:17:5)
#1 Expect.fail (file:///b/build/slave/vm-mac-release-x64-be/build/sdk/tests/co19/src/Utils/expect_common.dart:79:5)
#2 main. (file:///b/build/slave/vm-mac-release-x64-be/build/sdk/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t05.dart:44:18)
#3 _RootZone.runUnary (dart:async/zone.dart:1404)
#4 _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5 _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6 _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7 _Future._complete (dart:async/future_impl.dart:467)
#8 _SyncCompleter.complete (dart:async/future_impl.dart:52)
#9 Isolate.spawn. (dart:isolate-patch/isolate_patch.dart:334)
#10 _RootZone.runUnary (dart:async/zone.dart:1404)
#11 _FutureListener.handleValue (dart:async/future_impl.dart:131)
#12 _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#13 _Future._propagateToListeners (dart:async/future_impl.dart:667)
#14 _Future._complete (dart:async/future_impl.dart:467)
#15 _SyncCompleter.complete (dart:async/future_impl.dart:52)
#16 Isolate._spawnCommon. (dart:isolate-patch/isolate_patch.dart:433)
#17 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
./vm/object.h: 5459: error: Handle check failed: saw UnwindError expected Instance
Dumping native stack trace for thread 1003
[0x00000001100c9173] dart::Profiler::DumpStackTrace(bool)
[0x00000001100c9173] dart::Profiler::DumpStackTrace(bool)
[0x000000010fdc9d66] dart::DynamicAssertionHelper::Fail(char const, ...)
[0x000000010fecb879] dart::Instance::CheckedHandle(dart::RawObject)
[0x000000010fec04bb] dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments)
[0x0000000111baa4c7] Unknown symbol
[0x0000000111bab8b8] Unknown symbol
[0x0000000112cbd893] Unknown symbol
[0x0000000111baa982] Unknown symbol
[0x000000010fee802f] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)
[0x000000010fee92a1] dart::DartEntry::InvokeNoSuchMethod(dart::Instance const&, dart::String const&, dart::Array const&, dart::Array const&)
[0x000000010fec51fc] dart::DRT_InvokeClosureNoSuchMethod(dart::NativeArguments)
[0x0000000111baa4c7] Unknown symbol
[0x0000000111bacc2c] Unknown symbol
[0x0000000112ca21cf] Unknown symbol
[0x0000000112cbcaa2] Unknown symbol
[0x0000000112ca21cf] Unknown symbol
[0x0000000112cbc793] Unknown symbol
[0x0000000111baa982] Unknown symbol
[0x000000010fee802f] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)
[0x000000010feeb4c3] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
[0x000000010ffb274f] dart::IsolateMessageHandler::HandleMessage(dart::Message)
[0x000000010ffd9c26] dart::MessageHandler::HandleMessages(dart::MonitorLocker, bool, bool)
[0x000000010ffda095] dart::MessageHandler::TaskCallback()
-- End of DumpStackTrace

**Comment by alsemenov** [comment] 2016-09-02 10:16
I think the crash is already reported as separate issue https://github.com/dart-lang/sdk/issues/26588

**Comment by alsemenov** [comment] 2016-09-04 15:00
https://github.com/dart-lang/co19/issues/75#issuecomment-244342413

**Comment by fsc8000** [comment] 2016-09-28 21:26
Closed as duplicate of #26588

**Closed by fsc8000** 2016-09-28 21:26 UTC
Labels: area-library, library-isolate, Resolution: duplicate, Type: bug
