### ISSUE TITLE
Instance of an extension method is created every time it is used

### ISSUE THREAD

**Issue by kaboc** [dart-lang/sdk#53246] opened 2023-08-17 11:45 UTC
I'm not sure if there is the notion of an instance in a method, so please correct the title if it is wrong.

<details>
<summary>Code sample</summary>

```dart
void main() {
  final myClass = MyClass();
  print('method1');
  print(myClass.method1.hashCode);
  print(myClass.method1.hashCode);

  print('method2');
  print(myClass.method2.hashCode);
  print(myClass.method2.hashCode);
}

class MyClass {
  void method1() {}
}

extension on MyClass {
  void method2() {}
}
```
</details>

<img src="https://github.com/dart-lang/sdk/assets/20254485/d72a12b4-d166-4247-ac0b-3df87e8c86e6">

As shown above, an extension method of an object has a different hash code every time, whereas an instance method always has the same hash code. I guess from this that the instance of an extension method is not shared between uses. Is the behaviour intentional?

### Example

In Listenable (e.g. ChangeNotifier or ValueNotifier) in Flutter, the same listener function needs to be passed to `addListener()` and `removeListener()`. Otherwise the latter cannot remove the listener. The issue related to this actually happened to me.

<details>
<summary>Example code</summary>

```dart
import 'dart:async';

class TimeNotifier extends ValueNotifier<DateTime> {
  TimeNotifier() : super(DateTime.now()) {
    Timer.periodic(
      const Duration(seconds: 1),
      (_) => value = DateTime.now(),
    );
  }
}
```

```dart
class TimeStringNotifier extends ValueNotifier<({bool active, String time})> {
  TimeStringNotifier(this.timeNotifier) : super((active: false, time: ''));

  final TimeNotifier timeNotifier;

  void toggleListener() {
    if (value.active) {
      timeNotifier.removeListener(_listener);
      value = (active: false, time: '');
    } else {
      timeNotifier.addListener(_listener);
      value = (active: true, time: value.time);
    }
    notifyListeners();
  }

  void _listener() {
    value = (active: true, time: DateFormat().format(timeNotifier.value));
  }
}
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App();

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage();

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late final TimeNotifier _timeNotifier;
  late TimeStringNotifier _timeStringNotifier;

  @override
  void initState() {
    super.initState();
    _timeNotifier = TimeNotifier();
    _timeStringNotifier = TimeStringNotifier(_timeNotifier);
  }

  @override
  void dispose() {
    _timeNotifier.dispose();
    _timeStringNotifier.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ValueListenableBuilder(
          valueListenable: _timeStringNotifier,
          builder: (context, value, _) => Text(value.time),
        ),
      ),
      floatingActionButton: ValueListenableBuilder(
        valueListenable: _timeStringNotifier,
        builder: (context, value, _) {
          return FloatingActionButton(
            onPressed: _timeStringNotifier.toggleListener,
            child: Icon(value.active ? Icons.stop : Icons.play_arrow),
          );
        },
      ),
    );
  }
}
```
</details>

This is not the same as the actual code but is a simplified version that shows a similar situation.

Outline of the example:

- TimeNotifier
    - Timer ticks at 1 sec interval, updating the value of the notifier with the current time.
- TimeStringNotifier
    - The listener is added or removed when the FAB is pressed.
    - Every tick of the timer triggers the listener.
        - The time is formatted, and the value of TimeStringNotifier is updated with the formatted time, causing it to be displayed.
    - After the listener is removed, the time should not be shown until the listener is added again.

However, if the `_listener()` method is separated as an extension, `removeListener()` cannot remove the already added listener since the instance(?) of `_listener` is different from the one previously passed to `addListener()`.

<details>
<summary>Separated method</summary>

```dart
extension on TimeStringNotifier {
  void _listener() {
    value = (active: true, time: DateFormat().format(timeNotifier.value));
  }
}
```
</details>

The reason I separated the listener (and more methods actually) from the notifier class to an extension was because I wanted to reduce the number of methods in the class to make it easier to read. I didn't expect it to cause the issue, and it was hard to realise what was causing it.

**Comment by eernstg** [comment] 2023-08-17 12:48
This is working as specified, and as intended. Still, I understand that it can be surprising and/or frustrating:

> it was hard to realise what was causing it.

First, the language specification says that extension method tear-offs are equivalent to function literals. So if you tear off `e.foo` where `foo` is an extension method then it works like evaluating `(parameters) => v.foo(arguments)` where the `parameters` are the same list of formal parameters as in the declaration of `foo`, and `v` is a fresh final variable whose value is the value of `e` at the time of the tear-off.

The same thing is specified more precisely and in more detail in the language specification [here](https://github.com/dart-lang/language/blob/e77118e1720a77826731b6e6adf0c6aa0966f693/specification/dartLangSpec.tex#L6875).

This implies that if we tear off the same method with the same receiver then we may get two distinct function objects, even though they might actually behave identically in all other ways than wrt object identity.

Class instance methods are different: If we tear off the same class instance method from the same receiver twice then we _will_ get two function objects that are `==` (but they may or may not be `identical`, depending on the optimization).

It works in this manner because it isn't always correct to consider a tear-off of the same method with the same receiver as "the same" function object:

```dart
extension<X> on List<X> {
  void foo() => print(X);
}

void main() {
  List<int> xs = [];
  List<num> ys = xs;
  var f1 = xs.foo;
  var f2 = ys.foo;
  f1(); // 'int'.
  f2(); // `num`.
  // So `f1 == f2` cannot possibly be true, even though `identical(xs, ys)` is true.
}
```

So we decided that we would have a simple rule: A new tear-off can be a new function object, and `==` is not guaranteed even for the same receiver (because we couldn't use the other simple rule, which was to do the same thing as we do for torn-off class instance methods).

The best advice is probably to make sure that you don't use an extension method as a listener if you need to register/deregister them.

**Comment by kaboc** [comment] 2023-08-17 14:55
Thank you for clarifying. I'm always impressed to see you explaining things in great detail for us in every issue page.

I'm still concerned that I may forget the rule and make the same mistake again sometime, but I understand the design decision. I'll follow your advice and choose either of the options you gave me.

**Comment by eernstg** [comment] 2023-08-18 08:14
Thanks for the kind words, @kaboc!

Perhaps you could test at the point where a listener is removed that the removal actually took place? `Set.remove` returns a boolean result which is true if and only if the element was present. Another idea which would allow the situation to be detected up front is described here: https://github.com/dart-lang/sdk/issues/53266.

**Comment by kaboc** [comment] 2023-08-18 08:57
> `Set.remove` returns a boolean result which is true if and only if the element was present.

Sounds like a good idea to test the removal making use of Set. Thanks!

> Another idea which would allow the situation to be detected up front

It would reduce the possibility of related bugs and also remove concerns about the danger. I'm glad you've took my report seriously.

**Comment by mit-mit** [comment] 2023-08-18 09:09
Closing this for now

**Closed by mit-mit** 2023-08-18 09:09 UTC
