### ISSUE TITLE
Inconsistent behavior when using List.last as setter

### ISSUE THREAD

**Issue by Lengjunyi** [dart-lang/sdk#53944] opened 2023-11-03 10:38 UTC
When run on dartpad.dev:
```void main() {
  List<bool> a = [true, true];
  print(a.last); //=> "true"
  a.last = false;
  print(a.last); //=> this still prints "true"
  
  List<int> b = [1, 2];
  print(b.last); //=> "2"
  b.last = 3;
  print(b.last); //=> "3"
}
```

Also, when using development build in flutter, this inconsistency was not shown and both updates were successful. However, in production build, this problem start to appear.

**Comment by julemand101** [comment] 2023-11-03 12:30
Same issue seems to be the case when doing it with `.first`:
```dart
void main() {
  List<bool> a = [true, true];
  
  print(a.first); //=> "true"
  a.first = false;
  
  print(a.first); //=> this still prints "true"
  print(a); // [false, true]
  print(a[0]); // true
}
```
Tested with DartPad on Master with Firefox.

**Comment by lrhn** [comment] 2023-11-03 12:31
Reproduces readily. 

Consistent for any read that is statically detectable as being on the same list with the same index, even in a nother function, as long as it's only called with the same list as argument (probably because it's inlined).

Works for `print(a[a.length - 1])` as well, while `print(a);` shows the `false` value.

Over-optimistic value caching.

**Comment by biggs0125** [comment] 2023-11-07 16:18
Looked into this and found its caused by a bug in Dart2js's global inference algorithm. We assume that when we see the first/last selectors that they can't modify the "type" of the List. This isn't true for dynamic Lists (where any modification will pass the implicit covariance check) and it isn't true for Lists where Dart2js is representing the values in the list as part of the type (as is the case in the above example where we have `true` as part of the type of the literal list). We got lucky with a later conservative check in our SSA process that meant this bug only shows up for bool lists. But technically the bug applies to many other types as well.

**Comment by biggs0125** [comment] 2023-11-08 18:26
A fix to Dart2js's type inference has been landed in the SDK.

The criteria to trigger this bug is fairly specific but if you're encountering this issue on a version of the SDK without the fix and need a workaround: The simplest solution is to replace `a.first = someBool` with `a[0] = someBool` and `a.last = someBool` with `a[a.length - 1] = someBool`. This should properly update the type of the list.

**Closed by biggs0125** 2023-11-08 18:26 UTC
Labels: web-dart2js, P2, type-bug, area-web
