### ISSUE TITLE
standalone/io/http_bind_test causes an assertion in precompiled mode

### ISSUE THREAD

**Issue by DmitryOlshansky-google** [dart-lang/sdk#28857] opened 2017-02-22 12:59 UTC
It's not seen on the buildbot because the test is disabled for non-IPv6 builders.

```
FAILED: precompiler-dart_precompiled debug_x64 standalone/io/http_bind_test
Expected: Pass 
Actual: Crash
CommandOutput[precompiler]:
CommandOutput[assemble]:
CommandOutput[remove_assembly]:
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
../../runtime/vm/stack_trace.cc: 107: error: expected: async_function->IsAsyncFunction() || async_function->IsAsyncGenerator()
Dumping native stack trace for thread 2fc36
  [0x0000000000798db3] dart::Profiler::DumpStackTrace()
  [0x0000000000798db3] dart::Profiler::DumpStackTrace()
  [0x00000000006695e1] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x00000000007d04aa] dart::StackTraceUtils::ExtractAsyncStackTraceInfo(dart::Thread*, dart::Function*, dart::StackTrace*, dart::Array*, dart::Array*)
  [0x000000000066aacb] Unknown symbol
  [0x000000000066b397] dart::BootstrapNatives::DN_StackTrace_asyncStackTraceHelper(_Dart_NativeArguments*)
  [0x00007ff3cf13da2e] [Stub] CallBootstrapCFunction
  [0x00007ff3cf198e15] _asyncStackTraceHelper
  [0x00007ff3cf30f160] testBindShared.singleRequest
  [0x00007ff3cf3b8e09] _Closure.call
  [0x00007ff3cf30d85a] testBindShared
  [0x00007ff3cf3b8fc3] _Closure.call
  [0x00007ff3cf2db97f] _RootZone.runUnary
  [0x00007ff3cf19022a] _FutureListener.handleValue
  [0x00007ff3cf191f35] _Future._propagateToListeners.handleValueCallback
  [0x00007ff3cf3b8d20] _Closure.call
  [0x00007ff3cf191484] _Future._propagateToListeners
  [0x00007ff3cf196ab9] _Future._completeWithValue
  [0x00007ff3cf18ec85] _Future._asyncComplete.<anonymous closure>
  [0x00007ff3cf3b8d20] _Closure.call
  [0x00007ff3cf18dce8] _microtaskLoop
  [0x00007ff3cf18d938] _startMicrotaskLoop
  [0x00007ff3cf18d873] _startMicrotaskLoop
  [0x00007ff3cf3b8d20] _Closure.call
  [0x00007ff3cf19ae5a] _RawReceivePortImpl._handleMessage
  [0x00007ff3cf13d76e] [Stub] InvokeDartCode
  [0x00000000006a4968] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  [0x00000000006a4704] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  [0x00000000006a7a30] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x00000000006b483d] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x00000000006db959] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x00000000006dc012] dart::MessageHandler::TaskCallback()
  [0x00000000006dca83] Unknown symbol
-- End of DumpStackTrace


Command[precompiler]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart_bootstrap --snapshot-kind=app-aot --snapshot=/usr/local/google/home/dmitryolsh/dart-sdk/sdk/out/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.S --ignore-unrecognized-flags --packages=/usr/local/google/home/dmitryolsh/dart-sdk/sdk/.packages /usr/local/google/home/dmitryolsh/dart-sdk/sdk/tests/standalone/io/http_bind_test.dart
Took 0:00:08.192739

Command[assemble]: DART_CONFIGURATION=DebugX64 gcc -shared -m64 -o /usr/local/google/home/dmitryolsh/dart-sdk/sdk/out/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.aotsnapshot /usr/local/google/home/dmitryolsh/dart-sdk/sdk/out/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.S
Took 0:00:01.404901

Command[remove_assembly]: DART_CONFIGURATION=DebugX64 rm /usr/local/google/home/dmitryolsh/dart-sdk/sdk/out/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.S
Took 0:00:00.007803

Command[vm]: DART_CONFIGURATION=DebugX64 out/DebugX64/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/usr/local/google/home/dmitryolsh/dart-sdk/sdk/.packages /usr/local/google/home/dmitryolsh/dart-sdk/sdk/out/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.aotsnapshot
Took 0:00:00.472485

Short reproduction command (experimental):
    python tools/test.py -cprecompiler -rdart_precompiled -t960 standalone/io/http_bind_test

```

Assigning to @johnmccutchan as I think he authored async stacktrace which is where the assert fails.

**Comment by johnmccutchan** [comment] 2017-02-23 18:46
I can't reproduce this:

```
$ python tools/test.py -cprecompiler -rdart_precompiled -t960 standalone/io/http_bind_test -v
Test configuration: precompiler_dart_precompiled_debug_x64
Running "precompiler" command: DART_CONFIGURATION=DebugX64 xcodebuild/DebugX64/dart_bootstrap --snapshot-kind=app-aot --snapshot=/Users/johnmccutchan/workspace/dart/sdk/xcodebuild/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.S --ignore-unrecognized-flags --packages=/Users/johnmccutchan/workspace/dart/sdk/.packages /Users/johnmccutchan/workspace/dart/sdk/tests/standalone/io/http_bind_test.dart
Running "assemble" command: DART_CONFIGURATION=DebugX64 clang -dynamiclib -m64 -o /Users/johnmccutchan/workspace/dart/sdk/xcodebuild/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.aotsnapshot /Users/johnmccutchan/workspace/dart/sdk/xcodebuild/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.S
Running "remove_assembly" command: DART_CONFIGURATION=DebugX64 rm /Users/johnmccutchan/workspace/dart/sdk/xcodebuild/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.S
Running "vm" command: DART_CONFIGURATION=DebugX64 xcodebuild/DebugX64/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/Users/johnmccutchan/workspace/dart/sdk/.packages /Users/johnmccutchan/workspace/dart/sdk/xcodebuild/DebugX64/generated_compilations/precompiler/tests_standalone_io_http_bind_test/out.aotsnapshot
Done precompiler-dart_precompiled debug_x64 standalone/io/http_bind_test: pass
```

**Comment by DmitryOlshansky-google** [comment] 2017-02-23 19:11
> I can't reproduce this:

Well obviously build bots CAN reproduce it - look at the new status file, it says Crash.
It might be Linux only issue though.

**Comment by johnmccutchan** [comment] 2017-02-23 19:22
@DmitryOlshansky-google Thanks for pointing out that the test was marked as 'Crash' in the status file. After removing that the from the status file, I can now reproduce.

**Comment by johnmccutchan** [comment] 2017-02-23 20:10
https://codereview.chromium.org/2713593004

**Closed** 2017-02-23 20:32 UTC
