### ISSUE TITLE
js-interop: Uncaught Error: Expected a value of type 'MyElement', but got one of type 'UnknownElement'

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/sdk#43350] opened 2020-09-08 02:57 UTC
# Environment

Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart core libraries ("**dart:html**")

In your issue, please include:

* Dart SDK Version (`dart --version`)
**Dart SDK version: 2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "windows_x64"**

* Whether you are using Windows, MacOSX, or Linux (if applicable)
**Windows 10**

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
**Chrome & Edge(Chromium)**

# Code

Following code in a stagehand web-simple project will result in `UnknownElement` error

```dart
import 'dart:html';
import 'dart:js';
import 'dart:math' show Random;

void main() {
  window.customElements.define('my-element', allowInterop(() => MyElement()));
  final content = querySelector('#output');
  content.append(MyElement());
}

class MyElement extends HtmlElement {
  static final String _templateId = Random().nextDouble().toString();

  MyElement.created() : super.created() {
    TemplateElement template = document.getElementById(_templateId);

    if (template == null) {
      template = Element.tag('template')
        ..id = _templateId
        ..innerHtml = '<div>hello world</div>';
      document.append(template);
    }

    attachShadow({'mode': 'open'}).append(template.content.clone(true));
  }

  factory MyElement() => Element.tag('my-element');
}
```

# Error

```
Uncaught Error: Expected a value of type 'MyElement', but got one of type 'UnknownElement'
    at Object.throw_ [as throw] (dart_sdk.js:4028)
    at Object.castError (dart_sdk.js:3999)
    at Object.cast [as as] (dart_sdk.js:4315)
    at dart.LegacyType.new.as (dart_sdk.js:5857)
    at Function.new (main.dart:27)
    at main$ (main.dart:8)
    at main.dart.bootstrap.js:265
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (main.dart.bootstrap.js:264)
    at <anonymous>:1:8
    at Object.runMain (client.js:8787)
    at client.js:22487
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3834)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:11028)
    at Object._asyncStartSync (client.js:3798)
    at main__closure1.$call$body$main__closure (client.js:22499)
    at main__closure1.call$1 (client.js:22426)
    at StaticClosure._rootRunUnary [as call$2$5] (client.js:4168)
    at _CustomZone.runUnary$2$2 (client.js:12334)
    at _CustomZone.runUnaryGuarded$1$2 (client.js:12266)
    at _ControllerSubscription._sendData$1 (client.js:11817)
    at _DelayedData.perform$1 (client.js:11969)
    at _PendingEvents_schedule_closure.call$0 (client.js:12018)
    at Object._microtaskLoop (client.js:4001)
    at StaticClosure._startMicrotaskLoop (client.js:4007)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:10897)
    at invokeClosure (client.js:1205)
    at MutationObserver.<anonymous> (client.js:1224)
```

# Reference

https://github.com/dart-lang/sdk/issues/35829

https://stackoverflow.com/questions/25295022/dart-custom-elements-vanilla-dart-without-polymer/63684036

https://stackoverflow.com/questions/60910687/could-web-components-javascript-native-be-registered-in-the-end-of-htmls-body

**Comment by sigmundch** [comment] 2020-09-09 15:51
@Sunbreak thanks for your interest and for filing this issue. Especially thank you for including as many useful details and references!

I'm sorry to say but web components are currently not supported in Dart.

For context, long ago, CustomElements were implemented for Dart when the spec was at version 0.5. It was later noticed that the newer APIs required defining ES6 classes in a way that was not easily compatible with Dart, and it would require a heavy investment on our end. For that reason, we are not fully supporting the new APIs (like `window.customElements.define`) in Dart at this time.

See also https://github.com/dart-lang/sdk/issues/27445.

It is still surprising that the API is exposed in `dart:html`, so it is worth for us to look into excluding the API for now.

/cc @srujzs

**Comment by sigmundch** [comment] 2020-09-09 15:55
closing as a duplicate of #35829

**Closed by sigmundch** 2020-09-09 15:55 UTC
Labels: P2, area-web, closed-duplicate, web-libraries

**Comment by Sunbreak** [comment] 2020-09-09 22:56
> @sigmundch 
> See also #27445.
> 
> It is still surprising that the API is exposed in `dart:html`, so it is worth for us to look into excluding the API for now.

According to https://github.com/dart-lang/sdk/issues/27445, we are not going to support Web Components v1 in in the short term, are we?

As commented in https://github.com/dart-lang/sdk/issues/35084#issuecomment-684760236, it is very useful to use already-made `Web Components` in our company, or even build a cross-platform Design System beyond `Web Components`
