### ISSUE TITLE
Quick fix 'Create missing override' importing implementation files.

### ISSUE THREAD

**Issue by hamsbrar** [dart-lang/sdk#53189] opened 2023-08-11 07:21 UTC
`file_1.dart`
```dart
import 'package:other/file_where_type_r_is_exported.dart';

abstract class T {
  void f(PkgExportedR r);
}
```
`file_2.dart`
```dart
class ImplT extends T {
//    ~~~~~ 
//    Missing concrete implementation of 'T.f'.
//    - Quick fix: Create missing overrides 
}
```

Applying the suggested quick fix results in:

```dart
// file_2.dart

import 'package:other/src/file_where_type_r_is_declared.dart';
//                   ~~~~~

class ImplT extends T {
  @override
  void f(PkgExportedR r) { }
}
```
```sh
> dart --version
Dart SDK version: 3.0.7 (stable) (Mon Jul 24 13:17:56 2023 +0000) on "linux_x64"

> code --list-extensions --show-versions | grep dart-code
Dart-Code.dart-code@3.68.1
```

**Comment by srawlins** [comment] 2023-10-17 18:51
CC @bwilkerson an interesting library-canonicalization case.

**Comment by Reprevise** [comment] 2023-11-20 23:21
Curious as to how this could be solved. How would Dart choose the file to import the members from? How would it pick between `flutter/material.dart`, `flutter/cupertino.dart`, and `flutter/widgets.dart`, for example.

**Comment by srawlins** [comment] 2023-11-20 23:43
Dartdoc has heuristic code. I think if the element is declared in `package:x/src/foo.dart`, it will prefer `package:x/foo.dart` over `package:x/bar.dart`. It also prefers libraries that are not deprecated.

**Comment by keertip** [comment] 2024-04-04 23:29
Duplicate of #52711 .

**Closed by keertip** 2024-04-04 23:29 UTC
Labels: area-analyzer, P3, analyzer-server, analyzer-quick-fix, type-bug
