### ISSUE TITLE
microbenchmarks velocity_tracker_iteration regression

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31071] opened 2017-10-11 16:53 UTC
microbenchmarks velocity_tracker_iteration regressed:
![screen shot 2017-10-11 at 9 45 23 am](https://user-images.githubusercontent.com/551196/31454023-f10f6ef4-ae68-11e7-82c2-a3d22d96ed07.png)

The Flutter engine roll in https://github.com/flutter/flutter/pull/12400 contained two engine commits, https://github.com/flutter/engine/commit/6388e928801dece14033b9ca99421f473e1d2fd0 and https://github.com/flutter/engine/commit/f7685ddf16ccf9e5f6c4386c23061b02ed0e37d4. The second one there is a Dart roll from 3d21a46b726c24ded2d3cb3cce4f43aeed875dbc to 4b64a835b9c10480063739d1e73847dcc4d8bfb6.

**Comment by aam** [comment] 2017-10-11 17:17
It also looks like velocity_tracker_iteration 10% regression originated at dart roll back on Aug, 16th https://github.com/flutter/flutter/commit/2e57189aa47285b191552efe845446236ade6093. That is when it went up from ~3000ms to ~3300ms. It has been hovering within 1% of 3300ms goal mark since then
![fd027naeloq](https://user-images.githubusercontent.com/381137/31455586-faaf93c2-ae6c-11e7-8ff6-2b44feb747fa.png)

**Comment by Hixie** [comment] 2017-10-13 04:16
That was https://github.com/dart-lang/sdk/issues/30521, which we decided was acceptable. This new regression is a separate issue.

We should probably revert the roll if it's not possible to quickly figure out the fix because otherwise it'll make it really hard to notice additional regressions that we get while we're trying to pin down this one.

**Comment by aam** [comment] 2017-10-16 20:00
Running bisect seems to point to 5efa08b663, cc @rmacnak-google 


flutter tools | engine | dart rev |  rev timestamp | run 1  | run 2   |  run 3 |  run 4  | run 5   | run 6   |  run 7
-- | -- | -- |  -- | -- | -- | -- | -- | -- | -- | --
dfa13a14f | 6388e928801dece14033b9ca99421f473e1d2fd0 | 0bb41de8ff | 9/27 2:45:15 | 1257.02 | 1242.5 | 1241.76 | 1245.174 | 1251.01 | 1262.09 | 1237.95
dfa13a14f | 6388e928801dece14033b9ca99421f473e1d2fd0 | 5efa08b663 | 9/27 2:50:35 | 1286.63 | 1282.25 | 1281.21 | 1303.34 | 1299.88 | 1269.73 | 1282.29

**Comment by rmacnak-google** [comment] 2017-10-16 23:18
Hm, I don't see significant change on my Nexus 4

before 3736.0 3744.8 3692.6 3708.0 3718.1
after 3710.8 3724.6 3691.6 3694.7 3858.1
(-0.43%)

and the top functions are the same in the profiler before and after.

The change should only affect hot reload; even the additional member in Field doesn't change the allocation size because it doesn't cross the next double-word boundary.

**Comment by rmacnak-google** [comment] 2017-10-16 23:41
To clarify, I mean before and after 4b64a83. I'll try to see if I get a different commit when bisecting.

**Comment by aam** [comment] 2017-10-17 03:16
Sorry, why 4b64a83 ?  Did you mean 5efa08b ?

**Comment by aam** [comment] 2017-10-18 17:12
From what I can see single line from 5efa08b that adds `end_token_pos_` to `RawField` drops performance of the benchmark by about nine tenth of a percent. Considering that we need that field for better hot reload diagnostic not sure if anything can be done about this.

avg | run1 | run2 | run3 | run4 | run5
-- | -- | -- | -- | -- | --
_1268.62_ | 1258.52 | 1259.45 | 1278.44 | 1278.28 | 1268.41
_1280.52_ | 1272.04 | 1276.02 | 1282.94 | 1291.59 | 1280.03

```
diff --git a/runtime/vm/raw_object.h b/runtime/vm/raw_object.h
index fc4150b3f5..402064f184 100644
--- a/runtime/vm/raw_object.h
+++ b/runtime/vm/raw_object.h
@@ -1000,6 +1000,7 @@ class RawField : public RawObject {
   }
 
   TokenPosition token_pos_;
+  TokenPosition end_token_pos_;
   classid_t guarded_cid_;
   classid_t is_nullable_;  // kNullCid if field can contain null value and
                            // any other value otherwise.
```

**Comment by Hixie** [comment] 2017-10-18 17:18
Can we exclude this (and maybe others!) in release builds, if it has such a large impact?

**Comment by mraleph** [comment] 2017-10-18 18:13
We need to understand how adding a field to a `Field` that is neither accessed from generated code on the hot path nor scanned by the GC impacts the performance. 

Have you looked at the profiles? 

What happens on Golem when you submit your patch? Does any benchmarks there show similar regression?

**Comment by aam** [comment] 2017-10-18 18:24
@mraleph , no I haven't. 
Regarding Golem - since 5efa08b is already submitted how do I check impact of adding just one line from that patch? Do I need to submit and compare two patches - one with full revert of 5efa08b and another with full revert less that line?

**Comment by mraleph** [comment] 2017-10-18 18:41
@aam I think two patch approach is the best bet. Alternatively you can submit patch with adding a single field against revision prior to 5efa08b

**Comment by aam** [comment] 2017-10-18 19:54
The patches are running on the dart-vm golem under rev 64071.

The profiles look very similar the one on the left is on 0bb41de8ff(`"velocity_tracker_iteration": 1243.1414`), the one on the right is 0bb41de8ff with `TokenPosition end_token_pos_;` (`"velocity_tracker_iteration": 1358.8443`). Faster run has `VelocityTracker.getVelocity`  under top `_Float64List.[]`. Not sure what to make of this, whether this relevant or not.

![screenshot from 2017-10-18 12 53 42](https://user-images.githubusercontent.com/381137/31739641-65df0948-b403-11e7-8e79-4be706115466.png)

**Comment by aam** [comment] 2017-10-19 19:57
cc @alexmarkov

**Comment by aam** [comment] 2017-10-19 21:03
@alexmarkov attached are dumps of microbenchmark runs with `--verbose-gc` vm option. 
It seems that at least number of gc were the same between slow and fast runs.

[out-fast.txt](https://github.com/dart-lang/sdk/files/1399967/out-fast.txt)
[out-slow.txt](https://github.com/dart-lang/sdk/files/1399968/out-slow.txt)

**Comment by aam** [comment] 2017-10-19 22:29
when running this benchmark in release mode, performance difference between two versions disappears(within margin of error).

  | release run1 | release run2 | 
-- | -- | -- | 
original | 1109.3568 | 1128.546 |  
with new field | 1062.4998 | 1144.4327 |

**Comment by aam** [comment] 2017-10-20 18:07
So far we know that addition of `end_token_pos_` expanded the size of `RawField` from 48 bytes to 52 bytes, that led to increase of size of GC heap for the test by 2k. The test running in aot mode does large number of collections(due to large number of temp floats objects being used in the code) - 5652 collections in 13 seconds of app runtime, taking roughly 1 second doing the collections.

There seems to be no performance issues with release mode. So the issue seems to be specific to allocation profiling that is done as part of profile mode. @alexmarkov mentioned he has some thoughts how to speed allocation profiling up.

It's not clear though whether it makes to continue to run performance benchmarks on profile build, perhaps instead we really should switch to release mode. There is even a bug for that already https://github.com/flutter/flutter/issues/11885.

**Comment by Hixie** [comment] 2017-10-20 18:11
The point of profile mode is to test and debug performance issues, it would be sad if profile mode couldn't be used for benchmarks...

**Comment by Hixie** [comment] 2017-10-20 18:11
(Having said that, please do feel free to address this by just moving the benchmarks to release mode.)

**Comment by alexmarkov** [comment] 2017-10-20 18:14
The change https://github.com/dart-lang/sdk/commit/841b1ad814dd865ce19bef783e977dea281c6089 may offset this regression a little bit.

Still, we don't know the root cause of the regression for sure...

**Comment by aam** [comment] 2017-10-20 20:10
@yjbanov https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/microbenchmarks.dart#L36 indicates that switching away from `profile` to `release` will break running benchmarks on ios . Is that still  a concern(do we, for example, run benchmarks on ios)?

**Comment by yjbanov** [comment] 2017-10-20 20:59
The iOS benchmarks were disabled temporarily. We should reenable them. The issue around our ability to run in `release` mode might have been resolved since then.

**Comment by kasperl** [comment] 2017-10-25 13:25
Was this fixed through this engine roll?

    https://github.com/flutter/engine/commit/59f7f5038d4af72b0b2d66944c7b4784b5b0b646

**Comment by aam** [comment] 2017-10-25 14:22
Yes, the benchmark was brought done back to green by @alexmarkov's 841b1ad.
Ideally we still follow-up with
 - moving the microbenchmarks to release;
 - confirm how slightly larger heap (due to 8 bytes bigger vm `Field`) contributed to regression.

**Comment by a-siva** [comment] 2017-12-18 22:03
Any updates on follow-ups proposed above, If not we can close the bug?

**Comment by yjbanov** [comment] 2017-12-19 18:00
This has improved and now hovering around 3100, which is better than before the regression. So I'm closing.

**Closed by yjbanov** 2017-12-19 18:00 UTC
Labels: area-vm, Customer-Flutter, P1 high
