### ISSUE TITLE
Analyzer crash during code-generation (2)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#35653] opened 2019-01-14 18:04 UTC
Analyzer Feedback from IntelliJ

Likely related to https://github.com/dart-lang/sdk/issues/35643

# Version information

- `IDEA IU-183.4886.37`
- `2.1.1-dev.1.0`
- `IU-183.4886.37, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 3840x2160`

# Exception

Please append the contents of:
file:///private/var/folders/53/wcg58s8n72b4thbmd7mhqjyc0071_k/T/report1.txt

```
Dart analysis server, SDK version 2.1.1-dev.1.0, server version 1.21.1, error: Analysis failed: /Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.dart context: exception_20190114_100231_478
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1461:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#4      ExecutableElementImpl.returnType (package:analyzer/src/dart/element/element.dart:3806:64)
#5      _FunctionTypeImplLazy.baseReturnType (package:analyzer/src/dart/element/type.dart:3162:57)
#6      _FunctionTypeImplLazy.returnType (package:analyzer/src/dart/element/type.dart:3250:36)
#7      MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:585:42)
#8      MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:389:16)
#9      MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:70:7)
#10     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:516:31)
#11     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7877:49)
#12     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:5275:10)
#13     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7877:49)
#14     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4065:18)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5313:10)
#16     UnifyingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:3070:65)
#17     ResolverVisitor.visitExpressionFunctionBody (package:analyzer/src/generated/resolver.dart:4867:13)
#18     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:4061:15)
#19     ScopedVisitor.visitConstructorDeclarationInScope (package:analyzer/src/generated/resolver.dart:6350:16)
#20     ResolverVisitor.visitConstructorDeclarationInScope (package:analyzer/src/generated/resolver.dart:4746:11)
#21     ScopedVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:6343:7)
#22     ResolverVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:4734:13)
#23     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2956:15)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8372:20)
#25     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:6290:18)
#26     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:6268:11)
#27     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:4605:13)
#28     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#29     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:4666:25)
#30     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2436:49)
#31     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:623:10)
#32     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#33     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#34     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#35     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#36     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#37     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#38     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#39     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#40     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#41     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#47     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#53     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#54     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#55     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#56     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#57     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#58     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1547488926952 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink_test.dart","errors":[{"severity":"ERROR","t
1547488926969 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/example/example.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_WA
1547488926982 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/src/generic_test_input.dart","errors":[]}}
1547488926982 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/src/setter_test_input.dart","errors":[]}}
1547488926982 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/src/checked_test_input.dart","errors":[]}}
1547488926983 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/src/field_namer_input.dart","errors":[]}}
1547488926983 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/src/inheritance_test_input.dart","errors":[]}}
1547488926983 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/src/to_from_json_test_input.dart","errors":[]}}
1547488926983 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547488940419 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547488940449 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/default_value/default_value.checked.dart","errors":[{"severity":"ERRO
1547488940456 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.non_nullable.dart","errors":[]}}
1547488940473 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/default_value/default_value_test.dart","errors":[]}}
1547488940518 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/integration/json_test_example.non_nullable.dart","errors":[{"severity
1547488940583 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.dart","errors":[{"severity":"ERROR"
1547488940585 <= {"event":"analysis.highlights","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.dart","regions":[{"type":"DIREC
1547488940588 <= {"event":"analysis.navigation","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.dart","regions":[{"offset":500,
1547488940588 <= {"event":"analysis.closingLabels","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.dart","labels":[]}}
1547488940591 <= {"event":"analysis.outline","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.dart","kind":"LIBRARY","outline":{
1547488940593 <= {"event":"analysis.overrides","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.dart","overrides":[{"offset":230
1547488940658 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink_test.dart","errors":[{"severity":"ERROR","t
1547488940699 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/integration/json_test_example.wrapped.dart","errors":[{"severity":"ER
1547488940730 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/generic_files/generic_class.wrapped.dart","errors":[{"severity":"ERRO
1547488940770 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/test/integration/json_test_example.non_nullable.wrapped.dart","errors":[{"
1547488940776 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547488951289 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547488951322 <= {"event":"analysis.errors","params":{"file":"/Users/kevmoo/source/github/json_serializable/json_serializable/example/example.g.dart","errors":[]}}
1547488951328 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1547488951389 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1547488951488 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/kevmoo/source/github/json_serializable/json_serializable/test/kitchen_sink/kitchen_sink.wrapped.da
```

**Comment by kevmoo** [comment] 2019-01-14 18:09
@scheglov – I emailed you the `exception_20190114_100231_478` file

Also: this was during a fresh rebuild after upgrading my SDK

**Comment by scheglov** [comment] 2019-01-14 18:16
Thank you!

Interesting, there are no SDK files in this dump, just two files - the library `kitchen_sink.wrapped.dart` and its part `kitchen_sink.wrapped.g.dart`. I wonder if (1) this is what causes the exception; (2) it might be related to other exceptions that happen because we suddenly miss SDK libraries, like #35226.

**Comment by stereotype441** [comment] 2019-01-14 19:03
Duplicate of #35551

**Closed by stereotype441** 2019-01-14 19:03 UTC
Labels: area-analyzer
