### ISSUE TITLE
Analyzer: null.foo reports no warning

### ISSUE THREAD

**Issue by xvrh** [dart-lang/sdk#27273] opened 2016-09-07 20:28 UTC
The dart analyzer reports no warnings with this code:

``` dart
main() {
  null.foo;
}
```

I would expect: "The getter 'foo' is not defined for the class 'Null'."

**Comment by zoechi** [comment] 2016-09-08 05:37
I guess you want to enable strong mode https://www.dartlang.org/guides/language/analysis-options

**Comment by zoechi** [comment] 2016-09-08 05:51
See also #27276

**Comment by lrhn** [comment] 2016-09-08 05:52
I'm guessing this is what triggered #27276
The problem is that the specification special-cases `null` to the synthetic bottom type at the type level, so the type `Null` isn't even part of the analysis here. There is no definition of the capabilities of the bottom type because it doesn't really exist. We need to fix that.

**Comment by leafpetersen** [comment] 2017-05-12 23:37
cc @lrhn @eernstg @munificent @floitschG 

Should Null allow all methods, or should we forbid this?

**Comment by lrhn** [comment] 2017-05-12 23:42
The `Null` class is a class, it has the same methods as `Object`.
If this is about the `null` expression, we have changed that, and it's type is now `Null`, not bottom.

That doesn't completely avoid the problem because `(throw 42).method()` tries to call `method` on the bottom type, but it's unlikely to happen much in practice.

**Comment by leafpetersen** [comment] 2017-05-12 23:54
Currently both strong and non-strong mode allow this code with no errors:

```dart
import 'dart:async';

main() {
  Future<Null> f;
  f.then((x) => x.length);
}
```

Do we view this as an implementation bug?  WAI?  Or something we need to sort out?

**Comment by lrhn** [comment] 2017-05-13 10:07
Non-strong-mode is unsurprising, the static type of `(x) => x.length` is `dynamic->dynamic`, so it can't trigger any warnings.

Strong mode is wrong. Inference should make `x` have type `Null` and `Null` doesn't have a `length` getter. The behavior is not even matching original Dart 1 + inference, because in Dart 1, `Null` was not bottom. The `null` literal had static type bottom, but the `Null` type itself was just a class. If you write:
```dart
import 'dart:async';

main() {
  Future<Null> f;
  f.then((Null x) => x.length);
}
```
you should get a warning in non-strong mode (and probably an error in strong mode).

A quick check in dartpad shows that there is no warning, not even in non-strong mode, so yes, I think we do have an analyzer bug here.

**Comment by leafpetersen** [comment] 2018-06-05 16:57
The new front end implements the correct behavior for this.  Re-assigning this as an analyzer bug.

**Comment by leafpetersen** [comment] 2019-07-04 00:04
This seems to be fixed.

**Comment by leafpetersen** [comment] 2019-07-04 00:22
Correction, the original issue still reproduces on recent bleeding edge.  Calling a method on something of type `Null` seems to have been fixed, but in at least some cases, calling a method on the `null` literal succeeds.

**Comment by srawlins** [comment] 2019-10-15 05:12
This was fixed at some point recently; Dart analyzer 2.5.0 reports:

> The getter 'foo' isn't defined for the class 'Null'.

**Closed by srawlins** 2019-10-15 05:12 UTC
Labels: area-analyzer, language-strong-mode-polish, type-bug
