### ISSUE TITLE
standalone/io/process_stdin_transform_unsubscribe_test timeout on Windows

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28707] opened 2017-02-09 20:52 UTC
See [this](https://build.chromium.org/p/client.dart/builders/vm-win-debug-x64-be/builds/3113/steps/checked%20vm%20tests/logs/stdio), [this](https://build.chromium.org/p/client.dart/builders/vm-win-release-ia32-be/builds/5402/steps/checked%20vm%20tests/logs/stdio), and [this](https://build.chromium.org/p/client.dart/builders/vm-win-release-x64-be/builds/5149/steps/checked%20vm%20tests/logs/stdio) log. Output looks like:

```
FAILED: none-vm-checked release_x64 standalone/io/process_stdin_transform_unsubscribe_test
Expected: Pass 
Actual: Timeout
CommandOutput[vm]:
diagnostics: Using E:\b\depot_tools\win_toolchain\vs_files\d5dc33b15d1b2c086f2f6632e2fd15882f80dbd3\win_sdk\Debuggers\x64\cdb.exe to print stack traces
    
    Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
    Copyright (c) Microsoft Corporation. All rights reserved.
    
    *** wait with pending attach
    Symbol search path is: srv*
    Executable search path is: 
    ModLoad: 00000001`3f670000 00000001`3fd91000   E:\b\build\slave\vm-win-release-x64-be\build\sdk\out\ReleaseX64\dart.exe
    ModLoad: 00000000`76f60000 00000000`77108000   C:\Windows\SYSTEM32\ntdll.dll
    ModLoad: 00000000`76d40000 00000000`76e5f000   C:\Windows\system32\kernel32.dll
    ModLoad: 000007fe`fcd80000 000007fe`fcdec000   C:\Windows\system32\KERNELBASE.dll
    ModLoad: 000007fe`fa580000 000007fe`fa5a7000   C:\Windows\system32\IPHLPAPI.DLL
    ModLoad: 000007fe`fded0000 000007fe`fdf6f000   C:\Windows\system32\msvcrt.dll
    ModLoad: 000007fe`fd8e0000 000007fe`fd8e8000   C:\Windows\system32\NSI.dll
    ModLoad: 000007fe`fa560000 000007fe`fa56b000   C:\Windows\system32\WINNSI.DLL
    ModLoad: 000007fe`fd7a0000 000007fe`fd8cd000   C:\Windows\system32\RPCRT4.dll
    ModLoad: 00000000`77120000 00000000`77127000   C:\Windows\system32\PSAPI.DLL
    ModLoad: 000007fe`fd750000 000007fe`fd79d000   C:\Windows\system32\WS2_32.dll
    ModLoad: 000007fe`fddc0000 000007fe`fde9b000   C:\Windows\system32\ADVAPI32.dll
    ModLoad: 000007fe`fd360000 000007fe`fd37f000   C:\Windows\SYSTEM32\sechost.dll
    ModLoad: 000007fe`fe4e0000 000007fe`ff269000   C:\Windows\system32\SHELL32.dll
    ModLoad: 000007fe`fe3e0000 000007fe`fe451000   C:\Windows\system32\SHLWAPI.dll
    ModLoad: 000007fe`fd950000 000007fe`fd9b7000   C:\Windows\system32\GDI32.dll
    ModLoad: 00000000`76e60000 00000000`76f5a000   C:\Windows\system32\USER32.dll
    ModLoad: 000007fe`fd8d0000 000007fe`fd8de000   C:\Windows\system32\LPK.dll
    ModLoad: 000007fe`fe310000 000007fe`fe3d9000   C:\Windows\system32\USP10.dll
    ModLoad: 000007fe`fdea0000 000007fe`fdece000   C:\Windows\system32\IMM32.DLL
    ModLoad: 000007fe`fdcb0000 000007fe`fddb9000   C:\Windows\system32\MSCTF.dll
    ModLoad: 000007fe`f6ba0000 000007fe`f6ba3000   C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
    ModLoad: 000007fe`fcb20000 000007fe`fcb2f000   C:\Windows\system32\cryptbase.dll
    ModLoad: 000007fe`fcc10000 000007fe`fcc67000   C:\Windows\system32\apphelp.dll
    (1410.1748): Break instruction exception - code 80000003 (first chance)
    ntdll!DbgBreakPoint:
    00000000`76face10 cc              int     3
    0:006> cdb: Reading initial command '!uniqstack;qd'
    Processing 7 threads, please wait
    *** WARNING: Unable to verify checksum for E:\b\build\slave\vm-win-release-x64-be\build\sdk\out\ReleaseX64\dart.exe
    
    .  0  Id: 1410.48c Suspend: 1 Teb: 000007ff`fffde000 Unfrozen
          Start: dart!mainCRTStartup (00000001`3f98d57c)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`001bf1d8 000007fe`fcd810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`001bf1e0 00000001`3f74313f KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`001bf280 00000001`3f73ae2c dart!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart!dart::MonitorLocker::Wait+0xc
    00000000`001bf2c0 00000001`3f67aa33 dart!Dart_RunLoop+0x1ac
    00000000`001bf3e0 00000001`3f67b7e5 dart!dart::bin::RunMainIsolate+0x753
    00000000`001bf7d0 00000001`3f67b9e9 dart!dart::bin::main+0x3b5
    00000000`001bf8e0 00000001`3f98d521 dart!main+0x9
    (Inline Function) --------`-------- dart!invoke_main+0x22
    00000000`001bf910 00000000`76d559cd dart!__scrt_common_main_seh+0x11d
    00000000`001bf950 00000000`76f8b891 kernel32!BaseThreadInitThunk+0xd
    00000000`001bf980 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  1  Id: 1410.10cc Suspend: 1 Teb: 000007ff`fffda000 Unfrozen
          Start: dart!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f996918)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`01dbfc68 000007fe`fcd816ad ntdll!NtRemoveIoCompletion+0xa
    00000000`01dbfc70 00000000`76d49981 KERNELBASE!GetQueuedCompletionStatus+0x39
    00000000`01dbfcd0 00000001`3f67d6c8 kernel32!GetQueuedCompletionStatusStub+0x11
    00000000`01dbfd10 00000001`3f698665 dart!dart::bin::EventHandlerImplementation::EventHandlerEntry+0xb8
    00000000`01dbfd80 00000001`3f996975 dart!dart::bin::ThreadEntry+0x25
    (Inline Function) --------`-------- dart!invoke_thread_procedure+0xe
    00000000`01dbfdb0 00000000`76d559cd dart!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`01dbfde0 00000000`76f8b891 kernel32!BaseThreadInitThunk+0xd
    00000000`01dbfe10 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  2  Id: 1410.1578 Suspend: 1 Teb: 000007ff`fffd8000 Unfrozen
          Start: dart!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f996918)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`0369f808 000007fe`fcd810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`0369f810 00000001`3f74313f KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`0369f8b0 00000001`3f83431b dart!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart!dart::MonitorLocker::WaitMicros+0xb
    00000000`0369f8f0 00000001`3f742f44 dart!dart::ThreadInterrupter::ThreadMain+0xbb
    00000000`0369f920 00000001`3f996975 dart!dart::ThreadEntry+0x54
    (Inline Function) --------`-------- dart!invoke_thread_procedure+0xe
    00000000`0369f950 00000000`76d559cd dart!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`0369f980 00000000`76f8b891 kernel32!BaseThreadInitThunk+0xd
    00000000`0369f9b0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  3  Id: 1410.14b4 Suspend: 1 Teb: 000007ff`fffae000 Unfrozen
          Start: dart!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f996918)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`0464f218 000007fe`fcd810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`0464f220 00000001`3f74313f KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`0464f2c0 00000001`3f7e02fe dart!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart!dart::MonitorLocker::Wait+0xa
    00000000`0464f300 00000001`3f8874a9 dart!dart::BackgroundCompiler::Run+0x37e
    00000000`0464fbf0 00000001`3f8875dd dart!dart::ThreadPool::Worker::Loop+0x39
    00000000`0464fc20 00000001`3f742f44 dart!dart::ThreadPool::Worker::Main+0x6d
    00000000`0464fc50 00000001`3f996975 dart!dart::ThreadEntry+0x54
    (Inline Function) --------`-------- dart!invoke_thread_procedure+0xe
    00000000`0464fc80 00000000`76d559cd dart!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`0464fcb0 00000000`76f8b891 kernel32!BaseThreadInitThunk+0xd
    00000000`0464fce0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  5  Id: 1410.d74 Suspend: 1 Teb: 000007ff`fffa8000 Unfrozen
          Start: ntdll!TppWaiterpThread (00000000`76f7a7e0)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`04b0fa98 00000000`76f7a927 ntdll!NtWaitForMultipleObjects+0xa
    00000000`04b0faa0 00000000`76d559cd ntdll!TppWaiterpThread+0x14d
    00000000`04b0fd40 00000000`76f8b891 kernel32!BaseThreadInitThunk+0xd
    00000000`04b0fd70 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  6  Id: 1410.1748 Suspend: 1 Teb: 000007ff`fffd6000 Unfrozen
          Start: ntdll!DbgUiRemoteBreakin (00000000`77053760)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`04e2f958 00000000`77053798 ntdll!DbgBreakPoint
    00000000`04e2f960 00000000`76d559cd ntdll!DbgUiRemoteBreakin+0x38
    00000000`04e2f990 00000000`76f8b891 kernel32!BaseThreadInitThunk+0xd
    00000000`04e2f9c0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    Total threads: 7
    Duplicate callstacks: 1 (windbg thread #s follow):
    4
    quit:
    
    

Command[vm]: set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\dart.exe --enable_asserts --enable_type_checks --short_socket_read --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-win-release-x64-be\build\sdk\.packages E:\b\build\slave\vm-win-release-x64-be\build\sdk\tests\standalone\io\process_stdin_transform_unsubscribe_test.dart
Took 0:01:01.950000

Short reproduction command (experimental):
    python tools/test.py -mrelease --checked -t60 standalone/io/process_stdin_transform_unsubscribe_test
```

**Comment by fsc8000** [comment] 2017-02-09 22:18
Duplicate of #28558.
The stack trace are not conclusive and there is no local repro for this failure. Since this tests spawns child processes, we need a backtrace of the child process as well to get more information.

**Closed by fsc8000** 2017-02-09 22:18 UTC
Labels: area-vm, gardening, Resolution: duplicate
