### ISSUE TITLE
Initializing formal in parameter function type does not raise an error.

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#26854] opened 2016-07-11 11:04 UTC
The language specification (15 Aug 2015, p29) specifies that 'It is a compile-time error if an initializing formal is used by a function other than a non-redirecting generative constructor'. However, `dartanalyzer` (1.18.0-dev.4.0) does not emit any error messages on the following class:
```dart
class C {
  var x;
  C(int g(this.x));
}
```
The initializing formal, `this.x`, is used to indicate that the function typed argument `g` takes one argument, so there is probably no way it could be given a meaningful semantics to allow this.

**Comment by scheglov** [comment] 2016-07-25 21:18
duplicate of #26860

Should be fixed in  https://codereview.chromium.org/2178123003

**Closed by scheglov** 2016-07-25 21:18 UTC
Labels: area-analyzer, P2 medium, Type: bug
