### ISSUE TITLE
Internal problem: Unhandled  String tags;, ' in analyzeQuote.

### ISSUE THREAD

**Issue by gnusagit** [dart-lang/sdk#39514] opened 2019-11-25 12:29 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
Internal problem: Unhandled  String tags;, ' in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#11     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#13     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5226:12)
#14     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3814:14)
#15     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#16     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#17     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#18     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#19     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#20     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#21     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#22     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#23     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#24     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#25     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#26     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#27     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#28     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#29     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#30     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#31     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#48     new Future.sync (dart:async/future.dart:224:31)
#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#55     CompilerContext.runWithDefaul...
```

For additional log information, please append the contents of
file:///private/var/folders/rd/v9qvb_nx1y3c7b2pq5vq51f40000gn/T/report1.txt.

**Comment by srawlins** [comment] 2019-11-30 00:59
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38160; please follow along there.

**Comment by srawlins** [comment] 2019-11-30 00:59
Duplicate of https://github.com/dart-lang/sdk/issues/38160

**Closed by srawlins** 2019-11-30 00:59 UTC
Labels: area-front-end, front-end-fasta
