### ISSUE TITLE
dart2native under Linux produces *.exe files

### ISSUE THREAD

**Issue by pycebs** [dart-lang/sdk#39282] opened 2019-11-07 20:43 UTC
I was really looking forward to dart2native and so I experimented with it a little bit today. I use Linux and when I run dart2native, the resulting binary is an *.exe file. I know I can just change the name of the binary with the -o flag, but producing *.exe files on Linux is still a pretty weird standard behaviour.

**Comment by agilob** [comment] 2019-11-09 11:29
Just wanted to report the same thing, looks like code attempts to name it correctly but fails somewhere:

https://github.com/dart-lang/sdk/blob/6f5aee9f7fd6519cac17e2326a13df1b13499e02/pkg/dart2native/bin/dart2native.dart

**Comment by sedlund** [comment] 2019-11-19 22:51
I tried to `strip` the resultant binary on linux and running it now gives the dart usage info, and does not run the program at all.

**Comment by hukendo** [comment] 2019-11-25 20:39
```
~/D/t/dart » dart2native hello.dart                                                                                                                                                                               
Generated: /Users/hukendo/Documents/tmp/dart/hello.exe
------------------------------------------------------------
~/D/t/dart » ll                                                                                                                                                                                                   
total 6,7M
-rw-r--r-- 1 hukendo staff   38 ноя 26 03:28 hello.dart
-rwxr-xr-x 1 hukendo staff 6,7M ноя 26 03:29 hello.exe
------------------------------------------------------------
~/D/t/dart » ./hello.exe                                                                                                                                                                                          
Hello, World!
------------------------------------------------------------
~/D/t/dart » file hello.exe                                                                                                                                                                                       
hello.exe: Mach-O 64-bit executable x86_64
------------------------------------------------------------
~/D/t/dart » dart --version                                                                                                                                                                                       
Dart VM version: 2.6.1 (Mon Nov 11 13:12:24 2019 +0100) on "macos_x64"
```

**Comment by dkorzhevin** [comment] 2019-12-02 22:00
@sedlund 

Afaik, generated file already stripped:

```
$ file test.exe 
test.exe: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
```

**Comment by sedlund** [comment] 2019-12-08 19:17
> @sedlund
> 
> Afaik, generated file already stripped:
> 
> ```
> $ file test.exe 
> test.exe: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
> ```

Yes, it shows the same on mine.  In all circumstances before this =strip= will refuse to run a file that already has been.  On these dart binaries, it doesn't seem to recognize they are and will break them.

**Comment by mkustermann** [comment] 2020-12-29 15:38
The default `.exe` postfix used on all platforms might've been not the best choice, though since it is the default now and users have started relying on this, I don't think we can change the default. As mentioned on this thread, the existing `-o` option lets users choose a different output filename if wanted.

The resulting binary is as small as it can be and should not be modified (also not by calling `strip` on it). The reason why calling `strip` changes the binary in an incompatible way (and therefore causes change in behavior) is that the standalone AOT runtime binary is concatenated with the AOT compiled Dart application - `strip` will get rid of the latter. It is possible that we'd decide sometime in the future to use a different mechanism for `dart2native` - but for now that's intentional.

Given this, I hope it's all right if I close this issue.

**Closed by mkustermann** 2020-12-29 15:38 UTC
Labels: area-vm, vm-native

**Comment by agilob** [comment] 2020-12-29 16:24
>though since it is the default now and users have started relying on this, I don't think we can change the default

A bug that lives long enough becomes a feature?

It's still unexpected behaviour, non-standard and unpleasant output to see on non-windows platforms. When we get cross-compilation to different platforms, how will I know if the produced file is Windows executable or Linux without using `file` command or running the program?

**Comment by mkustermann** [comment] 2020-12-29 16:52
> A bug that lives long enough becomes a feature?

It's not a real bug, is it? `dart2native` produces self-contained binaries that run just fine - even on linux one can execute a file with `.exe` extension.

> When we get cross-compilation to different platforms, how will I know if the produced file is Windows executable or Linux
> without using file command or running the program? I won't because it's all .exe.

How would you distinguish Linux vs MacOS binary (both of which don't use extensions for binaries)?

The tool that produces binaries always knows which platform the compiled file will be for and can choose whatever name it sees fit.

I understand your frustration, but the bar for doing breaking changes is high and in this case there's an easy way out by specifying `-o <my-filename>`.

**Comment by agilob** [comment] 2020-12-29 16:56
>I understand your frustration, but the bar for doing breaking changes is high and in this case there's an easy way out by specifying -o <my-filename>.

The volume of work to fix the breaking change is super low too. 

> in this case there's an easy way out by specifying -o <my-filename>.

Like on stackoverflow:

- X doesn't work, how do I do X?
- Don't do X, do Y
