### ISSUE TITLE
Unexpected Generic Behavior

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/sdk#44554] opened 2020-12-27 01:05 UTC
I'm confused why the compiler can't infer the error here, and wondering if there are any analysis options I can use to enable it.

```
class Thing<T> {}

void main() {
  // useThing should be able to infer that the 2nd param here _must_ be a bool
  useThing(Thing<bool>(), 1);
}

T useThing<T>(Thing<T> t, T value) {}
```
I guess the issue is that this is somewhat of a tie? What I want to do is indicate that `T value` and `Thing<T>` have to match, but `Thing<T>` sets the type.

`useThing<bool>(Thing<bool>(), 1)` breaks the tie, but I'd like to omit the boilerplate, especially when a method has 2 or more types generics, so having to write out one, means writing out the others (unless there is some optional generic?)

**Comment by srawlins** [comment] 2020-12-28 18:51
> I guess the issue is that this is somewhat of a tie?

That's correct. Inference cannot flow upwards from one argument to assign a value to T in `useThing`, and then flow back down to the second argument.

**Comment by srawlins** [comment] 2020-12-28 18:52
@leafpetersen I think this would be solved by our analysis idea to report any time inference LUB arrives at `Object`. If LUB arrived at Object, and neither argument to LUB was Object, then the user has likely done something wrong.

**Comment by esDotDev** [comment] 2020-12-28 19:04
Ya that sounds like what I would expect. Its not that it matters who wins over the other, just that the mis-match is flagged as an error. Thanks!

**Comment by eernstg** [comment] 2021-01-06 10:31
The signature `T useThing<T>(Thing<T>, T)` doesn't actually specify that when the first argument has type `Thing<bool>`, the second argument must have type `bool`. It specifies that `useThing` can be used as a function with type `T Function(Thing<T>, T)` for any type `T`. In particular, we can choose `T == Object`, making it `Object Function(Thing<Object>, Object)`, which makes it perfectly OK to pass a `Thing<bool>` as the first actual argument and an `int` as the second one.

The inference algorithm could have used equality constraints (hence insisting that `T == bool` and `T == int`, and reporting failure), but this would cause a lot of inference tasks to fail even though there is a solution. So Dart type inference satisfies subtype constraints, not equality constraints.

However, the real issue might actually arise at a different point: We have the subtyping relation `Thing<bool> <: Thing<Object>` because Dart class type parameters are covariant. This is not always sound, i.e., the type correctness of the heap is maintained for some method invocations by inserting dynamic type checks at specific locations in the compiled program, and this means that some operations may incur a run-time error. A well-known example is when an element is added to a list: `myList.add(1)` may fail even if `myList` has static type `List<num>`, because it could have run-time type `List<double>`. The same kind of unsoundness is known from Java and C# where you can have an `ArrayStoreException`.

Dart is rather likely to be extended with support for sound declaration-site variance, and if you have that you can specify the variance of each type parameter explicitly. This ensures that no such dynamic error will occur, and in particular you could design the `Thing` class such that only `T == bool` will be a solution in the above situation:

```dart
class Thing<inout T> {}

void main() {
  useThing(Thing<bool>(), true); // OK.
  useThing(Thing<bool>(), 1); // Compile-time error.
}

T useThing<T>(Thing<T> t, T value) {
  // ... use it ...
  return value;
}
```

This makes the type parameter of `Thing` invariant, which means that there is no subtype relation `Thing<bool> <: Thing<S>` for any other value of `S` than `bool` itself, and in particular, `Thing<bool>` is not a subtype of `Thing<Object>`.

This will yield the desired type inference result, by changing the subtype relationship rather than by changing type inference itself.

**Comment by srawlins** [comment] 2021-01-12 05:14
This is a duplicate of https://github.com/dart-lang/sdk/issues/37863 (an eerily similar one, haha)

**Closed by srawlins** 2021-01-12 05:14 UTC
Labels: area-language
