### ISSUE TITLE
Invalid const object field: Closure: (int) => int from Function 'defaultBar': static.

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/sdk#31066] opened 2017-10-11 10:41 UTC
This code:

```dart
typedef int Bar(int value);

int defaultBar(int value) => value + 1;

class Foo {
  final Bar bar;

  const Foo._(Bar bar) : bar = bar ?? defaultBar;

  const Foo.baz({Bar bar}) : this._(bar); // <-- here
}

void main() {
  final foo = const Foo.baz();
  print(foo.bar(1));
}
```

fails with `error: line 14 pos 30: Invalid const object field: Closure: (int) => int from Function 'defaultBar': static.`

If I change line 10 to

```dart
  const Foo.baz({Bar bar = defaultBar}) : this._(bar);
```

then everybody's happy. If I instead change `Bar` to be a class (with a const constructor), and defaultBar to a const instance of `Bar`, then there are also no complaints.

I would've liked the the code above to work. Should it?

**Comment by a-siva** [comment] 2017-10-17 23:33
This looks like a duplicate of https://github.com/dart-lang/sdk/issues/31106
Marking as duplicate and closing, we will track this bug in the other issue.

**Comment by crelier** [comment] 2017-10-23 22:52
This is not a duplicate of #31106. I will have a look.

**Comment by crelier** [comment] 2017-10-24 22:39
This was almost a duplicate of 31106, but not quite. The right-hand side of operator ?? was not canonicalized when a constant. I find the handling of const (and potentially const) expressions in the parser quite fragile. This is probably not the last "duplicate" issue.
CL on its way.

**Closed** 2017-10-24 23:52 UTC
Labels: area-vm, Type: bug
