### ISSUE TITLE
Optional new combined with generic constructor fails

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32802] opened 2018-04-06 01:58 UTC
(Marking as P0 because this will show up a lot for optional new/const)

My current build: 2.0.0-edge.f5da30ef13b9272c0c4a8996e387978765b949eb

Code: 
```
main() {
    final List<Object> children = List<Object>.from([]);
}
```
yields this error:

./repo/dart-sdk/sdk/out/ReleaseX64/dart --preview-dart-2  ~/tmp/x.dart
 
tmp/x.dart:2:46: Error: An equality expression can't be an operand of another equality expression.
Try re-writing the expression.
    final List<Object> children = List<Object>.from([]);
                                             ^
tmp/x.dart:2:47: Error: Expected an identifier, but got '.'.
    final List<Object> children = List<Object>.from([]);
                                              ^
tmp/x.dart:2:47: Error: Getter not found: ''.
    final List<Object> children = List<Object>.from([]);
                                              ^
tmp/x.dart:2:39: Error: The method '<' isn't defined for the class 'dart.core::Type'.
Try correcting the name to the name of an existing method, or defining a method named '<'.
    final List<Object> children = List<Object>.from([]);
                                      ^
tmp/x.dart:2:46: Error: An equality expression can't be an operand of another equality expression.
Try re-writing the expression.
    final List<Object> children = List<Object>.from([]);
                                             ^
tmp/x.dart:2:47: Error: Expected an identifier, but got '.'.
    final List<Object> children = List<Object>.from([]);
                                              ^
tmp/x.dart:2:47: Error: Getter not found: ''.
    final List<Object> children = List<Object>.from([]);
                                              ^
tmp/x.dart:2:39: Error: The method '<' isn't defined for the class 'dart.core::Type'.
Try correcting the name to the name of an existing method, or defining a method named '<'.
    final List<Object> children = List<Object>.from([]);

**Comment by peter-ahe-google** [comment] 2018-04-06 08:38
This is a duplicate of 30922.

**Closed by peter-ahe-google** 2018-04-06 08:38 UTC
Labels: P0 critical, area-front-end
