### ISSUE TITLE
Terse Enums (when type is known)

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#25831] opened 2016-02-20 21:51 UTC
Enhancment request: When dealing with well known, enumerated types (e.g. below), it would be nice to not have to type out the type name over and over and over. It feels redundant and burdensome.

Bad:

``` dart
enum Action { left, right, up, down }
foo(Action action) {
  switch(action) {
    case Action.left:
    case Action.right:
    case Action.up:
    case Action.down:
  }
}
```

Good:

``` dart
enum Action { left, right, up, down }
foo(Action action) {
  switch(action) {
    case left:
    case right:
    case up:
    case down:
  }
}
```

**Comment by mezoni** [comment] 2016-02-21 14:45
>> When dealing with well known, enumerated types

Question for better understanding.
What means a `well known, enumerated types`?
What is opposite to `well known`? Unknown, not well known, barely recognizable?
It seems to me that you have to think in terms of subject area but not in the the degree of superiority.

**Comment by jtmcdole** [comment] 2016-02-21 22:25
I could see something like:
```dart
foo(bar) {
  switch(bar) {
    case Action.left:...
  }
}
```
not being well known unless you can prove every callsite of foo() passes in the same values.

**Comment by jtmcdole** [comment] 2016-02-21 22:27
What I'm basically asking is; if I know the type, don't make me type the type again and again. It is cumbersome and redundant. :)

**Comment by zoechi** [comment] 2016-02-22 05:48
A quick-fix provided by the analyzer would be another another: add all enum cases.

**Comment by jtmcdole** [comment] 2016-02-22 18:49
That would be a nice addition as well, however I think it would still be ugly to have a 20 entry enum that ends up with 20 "case Action.foo:"

**Comment by mezoni** [comment] 2016-02-23 15:15
>> That would be a nice addition as well, however I think it would still be ugly to have a 20 entry enum that ends up with 20 "case Action.foo:"

But what's wrong with that?
This is the essence of enums (name of enumeration and element of enumeration).

Your version looks better, but the original version can not be `ugly` because it is the correct version.

**Comment by jtmcdole** [comment] 2016-02-24 00:24
Dart has always favored terseness (e.g. leaving off types of parameters, dynamic, var). Anything other than that looks like forced Java.

**Comment by srawlins** [comment] 2018-06-22 05:57
I like this, and I was just reading that [Crystal 0.25 just added this feature](https://crystal-lang.org/2018/06/15/crystal-0.25.0-released.html#automatic-casts-for-literal-values).

Dart already allows shadowing of every variety, so this wouldn't be a dramatic change in the language's style (the feature would define `left`, `right`, `up`, and `down` in scope, shadowing any already existing variables of the same names).

**Comment by jkmathew** [comment] 2019-05-07 18:54
I would also like to have this style for enums in dart language. This make very easy while coding.
One more enhancement to @jtmcdole's proposal, adding a prefix `.` enum value to avoid conflict from previously defined variable/constant/keyword (Borrowing from [Swift](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html#ID147) ).
For example
```dart
enum Action { left, right, up, down }
foo(Action action) {
  switch(action) {
    case .left:
    case .right:
    case .up:
    case .down:
  }
}
//Function foo can be called like
foo(.left); //since type of parameter is known here.
```
Apart from @jtmcdole's example adding one few more examples.

```dart
enum Action { left, right, up, down }
Action theAction = .left; // Good
Action theAction = Action.left; // Bad

if (theAction == .left) {} // Good
if (theAction == Action.left) {} // Bad

foo(.left); // Good
foo(Action.left);  // Bad
//etc
```

**Comment by jtmcdole** [comment] 2019-07-27 00:17
So, is this still listed as a future enhancement? :)

**Comment by KagurazakaHanabi** [comment] 2019-11-29 14:38
if has this feature then some flutter code can be simplified...

**Comment by lrhn** [comment] 2021-09-29 07:49
Duplicate of https://github.com/dart-lang/language/issues/357

**Closed by lrhn** 2021-09-29 07:49 UTC
Labels: area-language, type-enhancement
