### ISSUE TITLE
pkg/analyzer 0.27.2 breaks source_gen

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#25822] opened 2016-02-19 22:16 UTC
Specifically the json_serializable tests

`pub run test test/json_serializable_test.dart`

```
  ScheduleError:
  | AnalysisException: Cannot compute LIBRARY_ELEMENT for StringSource (test content)
  | Caused by Unexpected exception while performing PartiallyResolveUnitReferencesTask for source test content
  | #0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:328:7)
  | #1      AnalysisTask.perform (package:analyzer/task/model.dart:218:7)
  | #2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274:10)
  | #3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109:18)
  | #4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:657:14)
  | #5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:630:12)
  | #6      _getCompilationUnitForString.<_getCompilationUnitForString_async_body> (file:///Users/kevmoo/source/github/source_gen.dart/test/json_serializable_test.dart:138:39)
```

**Comment by bwilkerson** [comment] 2016-02-21 15:56
You omitted the important part of the stack trace:

    | Caused by Unsupported operation: StringSource doesn't support encoding.
    | #0      StringSource.encoding (package:analyzer/src/string_source.dart:34:7)
    | #1      CompilationUnitElementImpl.identifier (package:analyzer/src/dart/element/element.dart:1031:35)
    | #2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:2115:54)
    | #3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:1855:29)
    | #4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:1799:25)

This should be fixed by https://codereview.chromium.org/1718803002/

**Closed by bwilkerson** 2016-02-21 15:56 UTC
Labels: area-analyzer
