### ISSUE TITLE
Analyzer incorrectly flags mixin usage

### ISSUE THREAD

**Issue by jimbeveridge** [dart-lang/sdk#26731] opened 2016-06-20 14:45 UTC
<i>This issue is blocking me</i>

I am receiving these two errors from the Dart Analyzer:

```
[error] The class 'StoreWatcherMixin' cannot be used as a mixin because it extends a
class other than Object (/home/travis/build/abcd/app/src/flutter/lib/main.dart, line 60, col 54)
[error] The class 'StoreWatcherMixin' cannot be used as a mixin because it references
'super' (/media/jimbe/abcd/src/flutter/lib/main.dart, line 60, col 54)
```

However, according to https://www.dartlang.org/articles/mixins/, these errors are no longer true (and the code runs correctly):

```
Dart 1.13 and greater supports mixins that can extend from classes other than
Object, and can call super().
```

Please contact me directly if you need to see the code generating the error.
#### Dart version

```
Dart VM version: 1.17.1 (Fri Jun 10 04:55:46 2016) on "linux_x64"
```

**Comment by bwilkerson** [comment] 2016-06-20 16:05
As far as I know, dart2js still isn't supporting this either, so the support in analyzer is still behind a flag (https://github.com/dart-lang/sdk/issues/24478). You can enable the support by including `--supermixin` on the command-line. You can also enable this support by including `enableSuperMixins : true` under `analyzer` in the analysis options file.

**Comment by stereotype441** [comment] 2019-07-25 18:19
We had to back out these features because of implementation difficulties, so now all the implementations agree that a mixed-in class can't extend non-Object or reference super.  However, you can do both of these things under all implementations using the new `mixin` syntax.

So I'm closing this bug--the implementations are working as intended.

**Closed by stereotype441** 2019-07-25 18:19 UTC
Labels: area-analyzer, p2-medium, type-enhancement
