### ISSUE TITLE
yield* does not terminate enclosing function on stream cancellation

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#25748] opened 2016-02-10 11:10 UTC
The Dart Programming Language Speciﬁcation (4th edition draft) version 1.11, chapter 17.16.2 Yield-Each reads:

> If m is marked async\* (9), then:
> • It is a dynamic error if the class of o does not implement Stream. Otherwise
> • For each element x of o:
>     – If the stream u associated with m has been paused, then execution
> of m is suspended until u is resumed or canceled.
>    – **If the stream u associated with m has been canceled**, then let c be
> the ﬁnally clause (17.11) of the innermost enclosing try-ﬁnally state-
> ment, if any. If c is deﬁned, let h be the handler induced by c. If h is
> deﬁned, control is transferred to h. If h is undeﬁned, **the immediately
> enclosing function terminates**.
>    – Otherwise, x is added to the stream associated with m in the order
> it appears in o. The function m may suspend.
> • If the stream o is done, execution of s is complete.

The following code demonstrates, that execution of immediately enclosing function continues after `yield*` statement even if the associated stream subscription is cancelled.

```
import 'dart:async';

Stream<int> generator(Stream<int> input) async* {
  yield* input;
  print("Error!!! Code after yield* should not be executed");
}

main() async {
  StreamController<int> sc = new StreamController<int>();
  Stream<int> s = generator(sc.stream);
  StreamSubscription<int> ss = s.listen(
      (int i){
        print(i);
      }
  );
  sc.add(1);
  sc.add(2);
  sc.add(3);
  await new Future.delayed(new Duration(milliseconds: 100));
  await ss.cancel();
  sc.add(4);
  sc.add(5);
  await new Future.delayed(new Duration(milliseconds: 100));
  await sc.close();
}
```

Output:

> 1
> 2
> 3
> Error!!! Code after yield\* should not be executed

Expected output:

> 1
> 2
> 3

Dart VM version: 1.14.1 (Wed Feb 03 11:59:06 2016) on "windows_x64"

**Comment by kevmoo** [comment] 2016-02-10 20:44
@floitschG thoughts?

**Comment by floitschG** [comment] 2016-02-10 21:02
Looks like a bug in the VM.
Dart2js has the expected output.

**Comment by mhausner** [comment] 2017-03-20 16:39
Still reproduces on the VM.

**Comment by natebosch** [comment] 2018-11-07 22:33
Closing in favor of https://github.com/dart-lang/sdk/issues/34775 which has more specifics around both pausing and cancelling.

**Closed by natebosch** 2018-11-07 22:33 UTC
Labels: area-vm
