### ISSUE TITLE
IntelliJ server error

### ISSUE THREAD

**Issue by chrisdrobison** [dart-lang/sdk#34941] opened 2018-10-26 13:22 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/_b/tqw7kvvs54l32qrfdwnf80bx9g_zhy/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/i52017/dev/recovery_flutter/lib/screens/home-screen.dart
RangeError (index): Invalid value: Not in range 0..10, inclusive: 11
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#6      _ParameterElementImpl

**Comment by chrisdrobison** [comment] 2018-10-26 13:29
This error occured when I was trying to declare a `final List<Widget> = []`

**Comment by stereotype441** [comment] 2018-10-29 16:29
Duplicate of #34941

**Closed by stereotype441** 2018-10-29 16:29 UTC
Labels: area-analyzer
