### ISSUE TITLE
crash in dart::TypeParameter::set_parameterized_class

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28072] opened 2016-12-12 03:01 UTC
Trying to run the Flutter tool after all the generic type parameter comments have been turned into real type parameters crashes:

```
Dumping native stack trace for thread 94d
  [0x000000000078e7f1] dart::TypeParameter::set_parameterized_class(dart::Class const&) const
  [0x000000000078e7f1] dart::TypeParameter::set_parameterized_class(dart::Class const&) const
  [0x00000000009605c8] dart::TypeParameter::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c89a7] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x00000000009609b8] dart::TypeArguments::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c84d6] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x0000000000964cac] dart::Function::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c851a] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x00000000008cb8bd] dart::SnapshotReader::ArrayReadFrom(long, dart::Array const&, long, long)
  [0x0000000000963438] dart::Array::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c8cff] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x00000000008cb4d7] dart::SnapshotReader::ReadObject()
  [0x00000000008cb628] dart::SnapshotReader::ReadScriptSnapshot()
-- End of DumpStackTrace
```

See also the logs here: https://travis-ci.org/flutter/flutter/builds/183108649

**Comment by sethladd** [comment] 2016-12-12 18:27
cc @a-siva

**Comment by fsc8000** [comment] 2016-12-12 18:56
@crelier

**Comment by crelier** [comment] 2016-12-12 19:22
It looks like `RawTypeParameter::WriteTo()` and `TypeParameter::ReadFrom()` in raw_object_snapshot.cc do not support function type parameters yet. Oops.
Working on it.

**Comment by crelier** [comment] 2016-12-12 19:54
Never mind. These functions should work as long as the `parameterized_class_id_` field of a generic function type parameter is properly initialized to `kIllegalCid`. Reading the source, I cannot find a place where we would not initialize it. And from the stack trace, I cannot see if this is really the problem.
Is there a way to reproduce the crash locally?

**Comment by Hixie** [comment] 2016-12-12 19:56
Apply the patch from https://github.com/flutter/flutter/pull/7235 to a local Flutter checkout and run the `flutter` tool (no arguments needed).

**Comment by crelier** [comment] 2016-12-12 22:21
Apparently, the snapshot reader/writer does not like kIllegalCid. I replaced it with kFunctionCid. There is a good chance that this landed CL fixes this issue:
https://codereview.chromium.org/2567163002/
Please, let me know.

**Comment by eseidelGoogle** [comment] 2017-01-07 00:12
This was hit internally as 34087655 (standalone vm) and 34131149 (flutter) if anyone is following along at home.

**Comment by eseidelGoogle** [comment] 2017-01-07 00:29
Attempting to verify, I did pull'd hixie's PR:
```
git remote add hixie https://github.com/Hixie/flutter.git 
git fetch hixie
git checkout -b hixie_methods hixie/methods
```

Ran `flutter` and verified that it crashed.

Then moved to 1.22.0.-dev.4.0:
```
diff --git a/bin/internal/dart-sdk.version b/bin/internal/dart-sdk.version
index 3500250..bdf20f6 100644
--- a/bin/internal/dart-sdk.version
+++ b/bin/internal/dart-sdk.version
@@ -1 +1 @@
-1.21.0
+1.22.0-dev.4.0
```
But now failed differently (likely due to this being based on a 20+ day old copy of flutter):
```
/src/flutter %./bin/internal/update_dart_sdk.sh
Downloading Dart SDK 1.22.0-dev.4.0...
######################################################################## 100.0%
/src/flutter %flutter doctor
Wrong script snapshot version, expected 'f232e903ba1a12e5502847d136c98505' found '2a315fe0946b69aeb0f3255b2ab2828e'
'package:linter/src/config.dart': malformed type: line 35 pos 40: cannot resolve class 'OptionsProcessor' from 'AnalysisOptionsProcessor'
class AnalysisOptionsProcessor extends OptionsProcessor {
                                       ^
```

**Comment by eseidelGoogle** [comment] 2017-01-07 00:31
`Wrong script snapshot version, expected 'f232e903ba1a12e5502847d136c98505' found '2a315fe0946b69aeb0f3255b2ab2828e'` above is a red herring.  It's because I hadn't changed the git hash (by committing locally) yet, to cause the `flutter` snapshot to rebuild.  Once I did, same error.

**Comment by Hixie** [comment] 2017-01-07 00:31
I think the AnalysisOptionsProcess thing is a question for @pq .

**Comment by Hixie** [comment] 2017-01-07 00:32
Are you changing to a new version of the engine? Or of the local dart SDK?

**Comment by eseidelGoogle** [comment] 2017-01-07 00:33
@Hixie I've only changed the local flutter/flutter dart_sdk.  Here is my repo:
https://github.com/eseidelGoogle/flutter/tree/hixie_methods

**Comment by pq** [comment] 2017-01-07 00:38
That error looks like a mismatch between the version of analyzer API used in the flutter source and what's in the summary/SDK.  IRC `OptionsProcessor` was removed by @bwilkerson.  This PR brings flutter to `1.22.0-dev.5.0` and is updated to the new analyzer API: https://github.com/flutter/flutter/pull/7382.

**Comment by crelier** [comment] 2017-01-09 22:44
Since the new failure is not related to the subject of this issue, and since this issue has now been verified, I am closing it.

**Closed by crelier** 2017-01-09 22:44 UTC
Labels: area-vm, Customer-Flutter, Type: bug
