### ISSUE TITLE
Type of invocation.typeArguments is not 'List<Type>' as expected

### ISSUE THREAD

**Issue by zjuwjf** [dart-lang/sdk#39175] opened 2019-10-30 02:05 UTC
```dart
typedef ProxyMethod<Environ> = dynamic Function(
  Environ environ,
  String name, {
  Map<String, dynamic> namedArguments,
  List<dynamic> positionalArguments,
  List<Type> typeArguments,
});

typedef ProxyGetter<Environ> = dynamic Function(Environ environ, String name);

typedef ProxySetter<Environ> = dynamic Function(
    Environ environ, String name, dynamic value);

class ProxyInvocation<Environ> {
  final Environ environ;
  final ProxyMethod<Environ> method;
  final ProxyGetter<Environ> getter;
  final ProxySetter<Environ> setter;

  const ProxyInvocation({
    this.environ,
    this.method,
    this.getter,
    this.setter,
  });

  dynamic invoke(Invocation invocation) {
    if (invocation.isGetter) {
      assert(getter != null);
      return getter?.call(environ, _getName(invocation.memberName));
    } else if (invocation.isSetter) {
      assert(setter != null);
      return setter?.call(
        environ,
        _getName(invocation.memberName),
        invocation.positionalArguments[0],
      );
    } else if (invocation.isMethod) {
      assert(method != null);
      return method?.call(
        environ,
        _getName(invocation.memberName),
        namedArguments: invocation.namedArguments?.map<String, dynamic>(
            (Symbol symbol, dynamic value) =>
                MapEntry<String, dynamic>(_getName(symbol), value)),
        positionalArguments: invocation.positionalArguments,
        typeArguments: invocation.typeArguments,
      );
    }
  }

  String _getName(Symbol symbol) {
    /// get:Symbol("name") set:Symbol("name=") method:Symbol("test")
    final String symbolStr = symbol.toString();
    const int startIndex = 'Symbol("'.length;
    final int index = symbolStr.indexOf('=');
    final int endIndex = index > 0 ? index : symbolStr.length - 2;
    return symbolStr.substring(startIndex, endIndex);
  }
}

class Proxy {
  final ProxyInvocation<dynamic> _handler;
  const Proxy(ProxyInvocation<dynamic> handler) : _handler = handler;
  @override
  dynamic noSuchMethod(Invocation invocation) => _handler?.invoke(invocation);
}

class MyInvocation extends ProxyInvocation<int> {
  MyInvocation()
      : super(
          environ: 2,
          method: (
            int environ,
            String name, {
            Map<String, dynamic> namedArguments,
            List<dynamic> positionalArguments,
            List<Type> typeArguments,
          }) =>
              print(
                  'environ=$environ invoke $name $namedArguments $positionalArguments $typeArguments'),
          getter: (int environ, String name) =>
              print('environ=$environ getter $name'),
          setter: (int environ, String name, dynamic value) =>
              print('environ=$environ setter $name $value'),
        );
}

class Imp {
  String name = 'hello';
  int age;
  void test<T>() {}
}

class MyProxy extends Proxy implements Imp {
  MyProxy() : super(MyInvocation());
}

void main() {
  final MyProxy imp = MyProxy();
  final String name = imp.name;
  print(name);
  imp.age = 0;
  imp.test<String>();
}
```

Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<Type>' of 'typeArguments'
#0      new MyInvocation.<anonymous closure> (package:fish_diff/src/proxy.dart)

** It seems that the type of [invocation.typeArguments] is 'List\<dynamic\>' not 'List\<Type\>' as Invocation declared.**

Dart VM version: 2.6.0-dev.8.2 (Thu Oct 24 09:35:58 2019 +0200) on "macos_x64".

**Comment by eernstg** [comment] 2019-10-30 08:56
This is a bug in the VM (btw, `dart2js` does not have it, so it is not a front end issue). Here is a reduced example:

```dart
abstract class A {
  void f<X>() {}
}

class B implements A {
  noSuchMethod(Invocation i) => print(i.typeArguments.runtimeType);
}

main() {
  A a = B();
  a.f(); // Prints 'List<dynamic>', should be `List<Type>`.
  (a as dynamic).f(); // Ditto.
}
```

It only occurs when the invocation targets a generic method; it is independent of whether any actual type arguments are provided, so presumably it is caused by the code generated for a noSuchMethod forwarder for generic methods.

The specification is slightly ambiguous about `Invocation.typeArguments` because it [says that](https://github.com/dart-lang/language/blob/62c036cc41b10fb543102d2f73ee132d1e2b2a0e/specification/dartLangSpec.tex#L11291)

```
\code{$im$.typeArguments} evaluates to an unmodifiable list
  containing the objects resulting from the evaluation of
  \code{<Type>[$A_1, \ldots,\ A_r$]}.
```

So it could be claimed that there are no constraints on the type argument of that list (if it's empty we could get a `List<AbsolutelyAnyType<You, Might, Want>>`!), but the only reasonable interpretation of this text is that the type argument should be `Type`.

**Comment by eernstg** [comment] 2019-10-30 09:28
Created https://github.com/dart-lang/language/pull/654 in order to make it absolutely explicit that `Invocation.typeArguments` must be a `List<Type>`.

Note that it is a soundness violation to deliver a `List<dynamic>` in this situation, because `Invocation.typeArguments` [has](https://api.dartlang.org/stable/2.6.0/dart-core/Invocation-class.html) the type annotation `List<Type>`. So there is no way we could allow that.

**Comment by crelier** [comment] 2019-11-15 18:40
The kernel file produced by the front-end contains a noSuchMethod forwarder with the incorrect type for the list of type arguments:
```
    no-such-method-forwarder method f<X extends core::Object* = dynamic>() → void
      return this.{bug::B::noSuchMethod}(new core::_InvocationMirror::_withType(#C1, 0, core::List::unmodifiable<dynamic>(<core::Type*>[bug::B::f::X*]), #C2, core::Map::unmodifiable<core::Symbol*, dynamic>(#C3)));

```
This call used to be generated in the VM, but it is now generated in the front-end.
I think that instead of
`core::List::unmodifiable<dynamic>(<core::Type*>[bug::B::f::X*])
`
it should be
`core::List::unmodifiable<core::Type*>(<core::Type*>[bug::B::f::X*])
`
I am reassigning to front-end area.

**Comment by eernstg** [comment] 2019-11-15 18:45
Thanks! Also, https://github.com/dart-lang/language/pull/654 has been landed, so the spec is now unambiguous that it should be an instance of a class that implements `List<Type>`.

**Comment by crelier** [comment] 2020-05-06 22:43
I verify now that this issue has been fixed in CFE (not sure when).

**Closed by crelier** 2020-05-06 22:43 UTC
Labels: area-front-end, type-bug
