### ISSUE TITLE
Program triggers segfault in JIT mode, runs fine on AOT/exe 

### ISSUE THREAD

**Issue by tamcy** [dart-lang/sdk#50622] opened 2022-12-04 09:33 UTC
Dart SDK Version (`dart --version`):
```Dart SDK version: 2.19.0-374.1.beta (beta) (Tue Nov 15 07:44:30 2022 -0800) on "windows_x64"```

I encontoured a rather confusing issue when running a Dart command line program. When running with `dart run` in the terminal the program just stops prematurely without any error message. I then tried running in debug mode using Android Studio, and while there is still no error nor exception, the following message emitted in the middle of the execution:

`Process finished with exit code -2147483645`

At first, I was unable to find out where the program ends with breakpoints (the program finishes successfully). Then I tried removing the breakpoints and insert various print messages here and there. After that I am quite sure there's something wrong with the execution because the program can stop at a very strange place, like after the `if` statement and before the `for` statement. The program processes a set of data in a loop, but it isn't any particular data that causes the program to stop - the data that fails runs fine if I move it to the first of the loop.

Some additional observations:

* I sometimes cannot reproduce the issue when running line by line using breakpoint. 
* Sometimes the termination can be reproduced when breakpoint is in effect but the line of the termination point is different from when running without the breakpoint. Still no error message, just a `Process finished with exit code -2147483645`.
* The program runs normally when it is compiled to an executable, or to an aot snapshot and run it with `dartaotruntime`. But it fails similarly when compiled to `jit` and execute.

I am willing to contribute the code privately for reproducting this issue, but I need some time to remove the unnecessary noises (it's still under development). The code is about detecting overlapping curves by using the [intersectionsWithCurve()](https://github.com/aab29/bezier.dart/blob/ef56c97e19dabebc3e9356f30300fc4e053139e0/lib/src/bezier.dart#L652) function in the `beizer` package. The function will be called multiple times in a loop. While I suppose this is a relatively heavy computation, memory should not be a program (I have over 30GB free memory), and the program stops very early.

I know there isn't very much useful information provided, please see if you can provide any suggestion on the issue I encountered. Thank you!

**Comment by srawlins** [comment] 2022-12-06 17:00
Loosely triaging this to VM...

**Comment by tamcy** [comment] 2022-12-07 03:30
Here is an update to the issue I have reported. The code that reproduces this issue can be found at https://github.com/tamcy/dart-issue-50622.

When running on Docker, I can see the following crash message emitted in the middle:

```
===== CRASH =====
si_signo=Trace/breakpoint trap(5), si_code=128, si_addr=(nil)
version=2.19.0-374.2.beta (beta) (Wed Nov 23 12:15:38 2022 +0000) on "linux_x64"
pid=1, thread=16, isolate_group=main(0x55b312372000), isolate=main(0x55b312465000)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=55b30fb16360, vm_instructions=55b30fb16360
  pc 0x00007fde15b4d947 fp 0x00007fde1137e050 Unknown symbol
  pc 0x00007fde15b38ad8 fp 0x00007fde1137e0e8 Unknown symbol
  pc 0x00007fde15b37e5b fp 0x00007fde1137e178 Unknown symbol
  pc 0x00007fde15b2d9af fp 0x00007fde1137e1e8 Unknown symbol
  pc 0x00007fde15b2d7f7 fp 0x00007fde1137e260 Unknown symbol
  pc 0x00007fde15b2d34c fp 0x00007fde1137e2c0 Unknown symbol
  pc 0x00007fde15b2c32b fp 0x00007fde1137e310 Unknown symbol
  pc 0x00007fde15b23dd2 fp 0x00007fde1137e350 Unknown symbol
  pc 0x00007fde15b23c0c fp 0x00007fde1137e380 Unknown symbol
  pc 0x00007fde15b22d9f fp 0x00007fde1137e3e8 Unknown symbol
  pc 0x00007fde15b2303b fp 0x00007fde1137e428 Unknown symbol
  pc 0x00007fde15b22d9f fp 0x00007fde1137e490 Unknown symbol
  pc 0x00007fde15b225e1 fp 0x00007fde1137e4e8 Unknown symbol
  pc 0x00007fde1c402ffc fp 0x00007fde1137e560 Unknown symbol
  pc 0x000055b30fc8a949 fp 0x00007fde1137e600 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x139
  pc 0x000055b30fc8a7c5 fp 0x00007fde1137e660 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x145
  pc 0x000055b30fc8cb24 fp 0x00007fde1137e6a0 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&)+0x144
  pc 0x000055b30fcafe58 fp 0x00007fde1137ec30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message>>)+0x348
  pc 0x000055b30fcd808a fp 0x00007fde1137ecb0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x15a
  pc 0x000055b30fcd87ab fp 0x00007fde1137ed00 dart::MessageHandler::TaskCallback()+0x1db
  pc 0x000055b30fdfdb9b fp 0x00007fde1137ed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x13b
  pc 0x000055b30fdfdfe8 fp 0x00007fde1137edb0 dart::ThreadPool::Worker::Main(unsigned long)+0x78
  pc 0x000055b30fd74906 fp 0x00007fde1137ee70 dart+0x21b4906
-- End of DumpStackTrace
```

When running on Windows in debug mode, the code terminates with exit code `-2147483645`. No error
message is printed. But occasionally a message similar to the following is emitted (yet I counter the message just once in tens of the executions):

```
Error: Failed to send request: {"jsonrpc":"2.0","id":"9","method":"setExceptionPauseMode","params":{"isolateId":"isolates/3021199231267163","mode":"Unhandled"}}
```

I have tested the code against several versions on Docker. The code crashes on `dart:2.19.0-374.2.beta`, `dart:2.19.0-374.1.beta`, `dart:2.19.0-255.2.beta` and `dart:2.19.0-146.1.beta`. It runs fine on `dart:2.18.5`.

**Comment by mraleph** [comment] 2022-12-12 09:26
@tamcy please add some open-source license of your choice to the repo, otherwise we can't look at it. (e.g. MIT, BSD, GPL, LGPL, Apache, etc.).

**Comment by tamcy** [comment] 2022-12-12 09:51
@mraleph No problem, MIT license file added to the repo.

**Comment by mraleph** [comment] 2022-12-12 10:14
Would you have some free cycles to take a look at this @aam?

**Comment by aam** [comment] 2022-12-12 19:22
`dart --optimization-counter-threshold=2 bin/demo.dart` seems to reliably reproduce the breakpoint trap which is inserted by https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/backend/flow_graph.cc#L1950.
There somehow seems to be a  confusion whlie optimizing/inlining package:bezier/src/bezier.dart_Bezier__nonOverlappingNormalVectorAt where UnboxedFloat is attempted to be converted to UnboxedDouble

**Comment by aam** [comment] 2022-12-13 06:39
Problem seems to be with https://github.com/dart-lang/sdk/blob/main/runtime/vm/compiler/backend/flow_graph.cc#L2056 where PhiInstruction gets unboxed double representation even if incoming values are unboxed floats.
Something like https://dart-review.googlesource.com/c/sdk/+/275180 seems to fix the crash.

**Comment by mraleph** [comment] 2022-12-13 08:10
Makes sense. The fix should be fixed-point based, because you can have float phis flowing into other phis. So it should likely follow the same template that `HasUnboxedIncomingValue` has.

**Closed** 2022-12-15 15:54 UTC
Labels: area-vm
