### ISSUE TITLE
Webdev serve reports compiler error

### ISSUE THREAD

**Issue by elayabharath** [dart-lang/sdk#38756] opened 2019-10-08 02:41 UTC
I do not really understand the error to try to reproduce this with a small example code. Filing it without an example anyway, in case it may be useful for the team.

```
dart --version
Dart VM version: 2.5.0 (Fri Sep 6 20:39:27 2019 +0200) on "macos_x64"
```

```
Serving at localhost:3000
Using chrome 77.0.3865.90 (Official Build) (64-bit) / macos mojave 10.14.6 (18G95) to view the webapp
```

```
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/local/Cellar/dart/2.5.0/libexec/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o packages/cobuild_template/app.ddc.js --source-map --summary=packages/uuid/uuid_util.ddc.dill=packages/uuid/uuid_util --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/uuid/uuid.ddc.dill=packages/uuid/uuid --summary=packages/cobuild_template/logger.ddc.dill=packages/cobuild_template/logger --summary=packages/cobuild_template/model/model.ddc.dill=packages/cobuild_template/model/model --summary=packages/cobuild_template/plans/single_family.ddc.dill=packages/cobuild_template/plans/single_family --summary=packages/cobuild_template/constants.ddc.dill=packages/cobuild_template/constants --summary=packages/cobuild_template/app_state.ddc.dill=packages/cobuild_template/app_state --summary=packages/cobuild_template/geom_utils.ddc.dill=packages/cobuild_template/geom_utils --summary=packages/cobuild_template/draw_wall_vm.ddc.dill=packages/cobuild_template/draw_wall_vm --summary=packages/cobuild_template/wall_view_model.ddc.dill=packages/cobuild_template/wall_view_model --summary=packages/cobuild_template/siteboundary_view_model.ddc.dill=packages/cobuild_template/siteboundary_view_model --summary=packages/cobuild_template/door_view_model.ddc.dill=packages/cobuild_template/door_view_model --summary=packages/cobuild_template/room_label_chooser.ddc.dill=packages/cobuild_template/room_label_chooser --summary=packages/cobuild_template/draw_site_boundary_vm.ddc.dill=packages/cobuild_template/draw_site_boundary_vm --summary=packages/cobuild_template/level_chooser.ddc.dill=packages/cobuild_template/level_chooser --summary=packages/cobuild_template/canvas.ddc.dill=packages/cobuild_template/canvas --packages=file:///var/folders/q_/8ds3pp15403db1lfhw6_2c4r0000gn/T/kernel_builder_htq26h/.packages --module-name=packages/cobuild_template/app --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/local/Cellar/dart/2.5.0/libexec/lib/libraries.json package:cobuild_template/app.dart
    dart --version: 2.5.0 (Fri Sep 6 20:39:27 2019 +0200) on "macos_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:393:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:271:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:259:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by vsmenon** [comment] 2019-10-08 03:36
Duplicate of https://github.com/dart-lang/sdk/issues/38102

**Closed by vsmenon** 2019-10-08 03:36 UTC
