### ISSUE TITLE
Many analyzer failures seem to arise and disappear spontaneously

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30025] opened 2017-06-27 08:27 UTC
The buildbot analyzer-linux-release-be fails in 354 co19 tests after commit 020241b0 from Jun 27 2:43am CEST, almost all of them with 'Actual: CompileTimeError' and expected 'Pass' or 'Static warning', and with error messages like "The argument type '..' can't be assigned to the parameter type '..'" or "The getter '..' isn't defined for ..".

Presumably, that CL introduced a bug in the analysis (or, less likely, an intended change that breaks all those tests). I haven't rolled back the CL because it seems likely that this won't affect many developers.

**Comment by eernstg** [comment] 2017-06-27 08:54
Turns out that this problem disappeared completely on analyzer-linux-release-be in the next build, but a few minutes later it arose in almost exactly the same form on analyzer-mac10.11-release-be in build 5583, and several older builds.

Changing the title of this issue and assignee accordingly: This seems to be an analyzer issue in general, not just one specific recent commit, which causes hundreds of co19 tests to fail with 'CompileTimeError' in one build and then (typically) going all green in the next build.

**Comment by mraleph** [comment] 2017-06-27 11:45
This is a duplicate of:

https://github.com/dart-lang/sdk/issues/29960

I suspect VM issue (e.g. misoptimization)

**Closed** 2017-06-27 11:45 UTC
Labels: area-analyzer, gardening, Resolution: duplicate
