### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by davidaimes077** [dart-lang/sdk#37786] opened 2019-08-08 15:15 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.5728.87`
- `2.5.0-dev.1.0`
- `WS-192.5728.87, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.5.0-dev.1.0, server version 1.27.1, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [/Users/davidaimes/WebstormProjects/lottery-master], excluded: [/Users/kevinliu/WebstormProjects/lottery-master/.idea, /Users/kevinliu/WebstormProjects/lottery-master/.tmp, /Users/davidaimes/WebstormProjects/lottery-master/1-base/.dart_tool, /Users/kevinliu/WebstormProjects/lottery-master/1-base/.pub, /Users/kevinliu/WebstormProjects/lottery-master/1-base/build, /Users/kevinliu/WebstormProjects/lottery-master/2-starteasy/.pub, /Users/kevinliu/WebstormProjects/lottery-master/2-starteasy/build, /Users/kevinliu/WebstormProjects/lottery-master/3-usebuttons/.pub, /Users/kevinliu/WebstormProjects/lottery-master/3-usebuttons/build, /Users/kevinliu/WebstormProjects/lottery-master/4-final/.dart_tool, /Users/kevinliu/WebstormProjects/lottery-master/4-final/.pub, /Users/kevinliu/WebstormProjects/lottery-master/4-final/build, /Users/kevinliu/WebstormProjects/lottery-master/temp, /Users/kevinliu/WebstormProjects/lottery-master/tmp]}, clientRequestTime: 1565269357261}
Bad state: Cannot stop a plugin that is not running.
#0      PluginInfo.stop (package:analysis_server/src/plugin/plugin_manager.dart:267:7)
#1      PluginManager.removedContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:572:16)
#2      PluginWatcher.removedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:95:13)
#3      AnalysisDriverScheduler.remove (package:analyzer/src/dart/analysis/driver.dart:2103:22)
#4      AnalysisDriver.dispose (package:analyzer/src/dart/analysis/driver.dart:636:16)
#5      ServerContextManagerCallbacks.removeContext (package:analysis_server/src/analysis_server.dart:964:12)
#6      ContextManagerImpl._destroyContext (package:analysis_server/src/context_manager.dart:1256:15)
#7      ContextManagerImpl._mergeContext (package:analysis_server/src/context_manager.dart:1563:5)
#8      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:1476:17)
#9      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1371:5)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#16     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#24     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#30     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#31     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#32     _rootRun (dart:async/zone.dart:1120:38)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#42     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#43     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/d2/fvp3pdj96h55gg8wsc99vmrc0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-03 07:38
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/36352; please follow along there.

**Comment by srawlins** [comment] 2019-09-03 07:39
Duplicate of https://github.com/dart-lang/sdk/issues/36352

**Closed by srawlins** 2019-09-03 07:39 UTC
Labels: P1-High, analyzer-crash-report, area-analyzer, type-bug
