### ISSUE TITLE
dartdevc crash

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#35968] opened 2019-02-16 22:41 UTC
Error while using `webdev serve web:8002` with Dart 2.2.0-dev.1.1 on Debian.

dartdevc arguments: --dart-sdk=/usr/lib/dart --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.sum --modules=amd -o packages/cfa_ape/ape.ddc.js --module-root=. --library-root=/lib --summary-extension=dartdevc.linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/meta/meta.dartdevc.linked.sum -s packages/quiver/core.dartdevc.linked.sum -s packages/quiver/iterables.dartdevc.linked.sum -s packages/quiver/collection.dartdevc.linked.sum -s packages/hash_compare/hash_compare.dartdevc.linked.sum -s packages/cfa/core.dartdevc.linked.sum -s packages/cfa/src/io/reader.dartdevc.linked.sum -s packages/cfa/io.dartdevc.linked.sum -s packages/cfa/rule.dartdevc.linked.sum -s packages/cfa/src/patterns/tuples.dartdevc.linked.sum -s packages/cfa/patterns.dartdevc.linked.sum -s packages/cfa/src/infer/rule_builder.dartdevc.linked.sum -s packages/cfa/infer.dartdevc.linked.sum -s packages/cfa/state.dartdevc.linked.sum -s packages/cfa/script.dartdevc.linked.sum -s packages/cfa/cast.dartdevc.linked.sum --url-mapping=package:cfa_ape/ape.dart,packages/cfa_ape/ape.dart --url-mapping=package:cfa_ape/ape.g.dart,packages/cfa_ape/ape.g.dart package:cfa_ape/ape.dart package:cfa_ape/ape.g.dart
    dart --version: 2.2.0-dev.1.1 (Unknown timestamp) on "linux_x64"
```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data/runtime/libtyped_data_patch.dart:4251:7)
#1      BufferContext._getUint32 (package:analyzer/src/summary/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:analyzer/src/summary/flat_buffers.dart:54:21)
#3      TableReader.read (package:analyzer/src/summary/flat_buffers.dart:694:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:4000:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:707:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:501:32)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:404:43)
#8      List.forEach (dart:core/runtime/libgrowable_array.dart:277:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:404:18)
#10     new CompilerAnalysisDriver (package:dev_compiler/src/analyzer/driver.dart:86:21)
#11     _compile (package:dev_compiler/src/analyzer/command.dart:135:9)
#12     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#13     compile (package:dev_compiler/src/compiler/shared_command.dart:360:18)
#14     _CompilerWorker.performRequest.<anonymous closure> (file:///tmp/tmpgPuD9A/dart-2.2.0-dev.1.1/dart/pkg/dev_compiler/bin/dartdevc.dart:49:39)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     _CompilerWorker.performRequest (file:///tmp/tmpgPuD9A/dart-2.2.0-dev.1.1/dart/pkg/dev_compiler/bin/dartdevc.dart:49:24)
<asynchronous suspension>
#20     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#26     main (file:///tmp/tmpgPuD9A/dart-2.2.0-dev.1.1/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#27     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:285:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
}

**Comment by stereotype441** [comment] 2019-02-19 16:16
The proximal cause of the problem was that the analyzer was given an empty (or possibly non-existent) summary file, causing it to crash.  In general any kind of summary corruption can lead to undefined analyzer behavior, but it would be nice if we generated a helpful error message for the case of an empty summary file.  I've filed #35986 to track this.

Not sure what the root cause is, though; someone familiar with webdev will have to look into why an empty summary got passed into dartdevc.

**Comment by stereotype441** [comment] 2019-02-19 16:17
@jakemac53 can you (or someone on the bat team) look into this?

**Comment by jakemac53** [comment] 2019-02-19 16:27
@bergwerf is it possible for you to provide a repro?

**Comment by bergwerf** [comment] 2019-02-19 17:21
Unfortunately not, it seems to have been a stateful error since it disappeared at some point (I might have restarted the whole build process, but I cannot remember exactly). I had a look at the different calls mentioned in the trace but I think it will actually be quite difficult to figure out what generated the empty data buffer. This issue happened to me once and I thought I should report it but it is not critical.

I really have no idea how this huge interconnected system works but perhaps a few additional checks can be added to throw a clearer error earlier on.

**Comment by jakemac53** [comment] 2019-02-19 17:37
My best guess here is there was a race condition where the file wasn't actually written to the file system yet, potentially we could just add a `flush: true` [here](https://github.com/dart-lang/build/blob/master/scratch_space/lib/src/scratch_space.dart#L106), but that might have performance implications.

**Comment by vsmenon** [comment] 2019-04-24 23:35
The latest webdev is off analyzer-ddc, so this should be fixed / avoided.

**Closed by vsmenon** 2019-04-24 23:35 UTC
Labels: area-dev-compiler
