### ISSUE TITLE
 Failed to handle completion domain request

### ISSUE THREAD

**Issue by dasher** [dart-lang/sdk#39235] opened 2019-11-05 11:17 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 193.4932.9`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `IU-193.4932.9, JRE 11.0.4+10-b520.2x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, error: Failed to handle completion domain request: {id: 2733, method: completion.getSuggestionDetails, params: {file: M:\flutter_firebase_login\lib\panels\daily_summary.dart, id: 702, label: Color, offset: 2716}, clientRequestTime: 1572952454606}
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DartFileEditBuilderImpl.importLibraryElement (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1298:34)
#2      CompletionDomainHandler.getSuggestionDetails.<anonymous closure> (package:analysis_server/src/domain_completion.dart:204:32)
#3      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:54:20)
#4      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#14     DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#22     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file://C:\Users\Dasher\AppData\Local\Temp\report.txt.

**Comment by bernaferrari** [comment] 2019-11-05 21:06
Same here.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.7142.36`
- `2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35`
- `IU-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35, server version 1.27.3, error: Failed to handle completion domain request: {id: 9992, method: completion.getSuggestions, params: {file: /Users/bernardoferrari/Documents/material/lib/colors_repository.dart, offset: 5832}, clientRequestTime: 1572978843171}
NoSuchMethodError: The getter 'staticElement' was called on null.
Receiver: null
Tried calling: staticElement
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _LocalVisitor._staticTypeOfIdentifier (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:572:12)
#2      _LocalVisitor._addLocalSuggestion_includeReturnValueSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:443:9)
#3      _LocalVisitor.declaredExtension (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:167:7)
#4      LocalDeclarationVisitor.visitCompilationUnit.<anonymous closure> (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:113:9)
#5      ListMixin.forEach (dart:collection/list.dart:63:13)
#6      LocalDeclarationVisitor.visitCompilationUnit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:106:23)
#7      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#8      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#9      GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#10     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#11     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:202:7)
#12     GeneralizingAstVisitor.visitExtensionDeclaration (package:analyzer/dart/ast/visitor.dart:278:7)
#13     ExtensionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:3928:49)
#14     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#15     LocalDeclarationVisitor.visitMethodDeclaration (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:211:5)
#16     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7108:49)
#17     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:218:18)
#18     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#19     GeneralizingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:268:7)
#20     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3583:15)
#21     LocalDeclarationVisitor.visit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:72:12)
#22     LocalReferenceContributor.computeSuggestions (package:analysis_server/src/services/completion/dart/local_reference_contributor.dart:67:17)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

[report.txt](https://github.com/dart-lang/sdk/files/3811218/report.txt)
[report1.txt](https://github.com/dart-lang/sdk/files/3811219/report1.txt)

**Comment by keertip** [comment] 2019-11-06 09:38
Thanks for reporting this issue. This was previously reported at #38476,  please follow along there.

**Comment by keertip** [comment] 2019-11-06 09:39
Duplicate of #38476

**Closed by keertip** 2019-11-06 09:39 UTC
Labels: analyzer-crash-report, area-analyzer
