### ISSUE TITLE
Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

### ISSUE THREAD

**Issue by aksharma-net** [dart-lang/sdk#37021] opened 2019-05-20 19:57 UTC
Thank you for taking the time to file an issue!

This tracker is for issues related to:

Running "flutter packages get" in abs_password_manager...           1.9s

Launching lib\main.dart on Moto G 5S Plus in debug mode...

Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.

If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///C:/Users/ABHI/AppData/Local/Temp/initialize_from.dill3c36269c-7b39-11e9-9c56-8c1645d4415d/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Built build\app\outputs\apk\debug\app-debug.apk.

**Comment by a-siva** [comment] 2019-05-24 22:54
@abhishekwebd can you provide us with more details on how you ran into this issue, a sequence of steps that you did to get this error would be a good first step, Thanks.

**Comment by a-siva** [comment] 2019-05-24 22:59
This appears to be a duplicate of #37043

**Comment by abhishekwebd** [comment] 2019-05-25 19:49
I dont know why it came!
But i was doing the same as i had previously used. Somehow i got this error
to submit so i did that.
But now i had fixed it on my end. No problem for now.
Thanks

**Comment by Q14** [comment] 2019-05-27 10:43
+1

**Comment by jensjoha** [comment] 2019-06-12 12:47
This post unfortunately doesn't contain anything to go on.
We get these reports once in a while -- it is basically always caused by either
a) An updated version of flutter where the flutter sdk changed, or
b) Trying to initialize from an empty file

While both are unfortunate, they are also both harmless: The compile that reported this will be slower, but the output will be perfectly fine.

If, however, this happens every time we have a different issue.
For now I'll assume that's not the case, though, and close this issue.

**Closed by jensjoha** 2019-06-12 12:47 UTC
Labels: area-front-end, p2-medium, type-bug
