### ISSUE TITLE
False dead code

### ISSUE THREAD

**Issue by tlserver** [dart-lang/sdk#35982] opened 2019-02-19 11:29 UTC
The following code incorrectly gives a 'dead code' warning on `b?.isEmpty`:
```
void main() {
  String a = 'a';
  String b = 'b';
  print(a?.isEmpty ?? true || b?.isEmpty ?? true);
}
```
Try on DartPad: https://dartpad.dartlang.org/87b7ff36eeeda2bc00705adc35b55182

**Comment by eernstg** [comment] 2019-02-19 11:52
Maybe you're assuming that it means `(a?.isEmpty ?? true) || (b?.isEmpty ?? true)`?

The precedence of operators in Dart is not specified explicitly, it is a built-in property of the grammar rules. And we have `<ifNullExpression> ::= <logicalOrExpression> (‘??’ <logicalOrExpression>)*` which immediately indicates that the grouping is `a?.isEmpty ?? ((true || b?.isEmpty) ?? true)`.

With that, it's easy to see that `b?.isEmpty` is indeed dead code.

It might be a good rule of thumb to note that `??` is a "larger scale" operator than most others, in the sense that it is intended to be used with "big expressions": We have a very short derivation `<expression> --> <conditionalExpression> --> <ifNullExpression>` and there's your `??`, and the operands are `<logicalOrExpression>` (which are capable of deriving almost all other forms of expression).

**Comment by eernstg** [comment] 2019-02-19 12:03
I'll close this issue indicating that the tools are already working as intended.

**Closed by eernstg** 2019-02-19 12:03 UTC
Labels: closed-as-intended
