### ISSUE TITLE
Performance issue during the debug process

### ISSUE THREAD

**Issue by krkboasit** [dart-lang/sdk#25188] opened 2015-12-09 11:32 UTC
## Summary:

There seems to be an issue related to debugging web applications using dartium. 
When resuming program execution after triggering a break-point, performance becomes significantly worse under specific curcumstances.
When execution is resumed by stepping out of the event-function (i.e. we do specifically not click 'resume program'), the application becomes noticeably slower from that point on and forward.
Repeating the process further degrades the perceived performance each time.
## What steps will reproduce the problem?
1. Create a new project by cloning the link: https://github.com/dart-lang/sample-pop_pop_win.
2. Open lib/src/stage/square_element.dart.
3. Place a break-point at line 82, this should be the closing brace of the onClick() function.
4. Run the application in debug-mode.
5. Click on a balloon.
6. Press F7 or F8 to perform a step into or step over action and out of the debug process.
7. Repeat step 5-6 until the application starts to perform noticeably worse.
8. Remove the break-point and repeat step 5.
## What is the expected output? What do you see instead?

**Expected:**
The application will run smoothly throughout the debug process.

**Actual:**
The application starts running slower and slower the more times you exit the debug process
by performing a step into or step over action.
The issue remains even if the break-point is removed.
## What version of the product are you using?

Dartium dartium-win-full-dev-1.14.0-dev.3.0.0

WebStorm 11.0.1
Dart 14.0-dev.3.0

On what operating system?
Windows 7 SP1(64bit)
## Please provide any additional information below.

The issue has been reproduced using dartium-win-full-stable-1.13.0.0

Removing the break-point will not fix the issue, but restarting the debug process will reset the performance.

Performance seems ok if the debug process is exited by pressing F9 to perform the resume action,
however this does not reset the performance and exiting the debug process with F7 or F8 afterwards will not have improved performance.

Additionally we have observed the application crashing on several occations during this process.

**Comment by zoechi** [comment] 2015-12-09 13:16
Could be related #/25014

**Comment by alan-knight** [comment] 2015-12-11 22:12
This is about the Intellij debugger integration, which is using the deprecated VM debug protocol. This should be replaced with the observatory protocol before long, which would presumably make this obsolete. @jwren @rmacnak-google

**Comment by alexander-doroshko** [comment] 2015-12-14 11:22
@alan-knight Since SDK 1.14 IntelliJ IDEA uses VM Service protocol for debugging. krkboasit says that 14.0-dev.3.0 is used, so unlikely it is an IDE issue.

**Comment by johnmccutchan** [comment] 2015-12-15 00:02
@turnidge

**Comment by johnmccutchan** [comment] 2015-12-15 00:02
@mhausner

**Comment by johnmccutchan** [comment] 2015-12-15 00:03
Does IntelliJ use the VM service protocol for Dartium debugging? I would have expected it to use the Chrome DevTools protocol.

**Comment by alexander-doroshko** [comment] 2015-12-15 09:56
@johnmccutchan Sorry, I overlooked the description. Indeed, IntelliJ IDEA uses Chrome's debugger protocol both for Chrome and Dartium regardless of the SDK version.

**Comment by alexander-doroshko** [comment] 2015-12-15 14:20
@krkboasit I tried to reproduce the issue with WebStorm 11.0.2, Windows 8.1, Dart SDK 1.14-dev.4.0 and corresponding Dartium.
- Failed to reproduce with F7 (Step Into) because it doesn't resume the program, but goes to this state:
![image](https://cloud.githubusercontent.com/assets/4499789/11812677/4b853b98-a34e-11e5-8144-8dbcf7361572.png)
- F8 (Step Over) indeed resumes the app. I repeated it 15 times and then removed the breakpoint. After that the app still works smoothly, I do not see any slowness.

**Comment by jwren** [comment] 2015-12-15 17:27
@alexander-doroshko thanks for trying to reproduce.  Closing out the issue.

**Comment by alexander-doroshko** [comment] 2015-12-16 16:30
@krkboasit Can you please check if this issue is still reproducible in your environment? I failed to reproduce both with dartium-win-full-stable-1.13.0.0 and dartium-win-full-dev-1.14.0-dev.4.0, see my comment above.

**Comment by boasjls** [comment] 2015-12-18 08:53
We're still seeing this issue, and have now reproduced it on MacOS and Win10, using the dev4.0 build of the sdk and dartium.

We're seeing the same issue on all platforms. Usually the animations will run smoothly, and if we trigger a breakpoint and resume the program with the webstorm action 'Resume program', the animations continue to run smoothly.
However if we perform the 'step over' action at the previously specified location (thus indirectly resuming the program) the animations will become very choppy, and they will continue as such until the application is restarted.

It was however a mistake when we wrote that 'step into' also trigger this (we also enter the 'wrap_jso_no_SerializedScriptvalue' when doing so).

**Comment by alexander-doroshko** [comment] 2015-12-18 12:07
@boasjls Thank you for the update! I have found an issue at IDE side. Will be tracked as https://youtrack.jetbrains.com/issue/WEB-19534, please watch/vote.

Workaround: Disable ''Do not step into library script' in Settings (Preferences) | Build, Execution, Deployment | Debugger | Stepping

**Comment by alexander-doroshko** [comment] 2015-12-18 14:09
@boasjls I spent more time on the issue and finally I think that it is not at IDE side. I came to the situation when Dartium is doing nothing but eating my CPU.

Attaching full log of IDE <-> browser communication: [wip.log.zip](https://github.com/dart-lang/sdk/files/66669/wip.log.zip)
Used SDK and Dartium from  http://gsdview.appspot.com/dart-archive/channels/dev/release/1.14.0-dev.5.0/

Technical details (you'll actually see all this info in attached logs as well):
- Browser is suspended on a breakpoint with the following stack
![image](https://cloud.githubusercontent.com/assets/4499789/11898334/2602c514-a5a8-11e5-8a13-831304eb6eff.png)
- Step over is invoked ~50 times
- Finally application resumes (although Resume command was not sent, only StepOver), the last stack before the app resumes contains a single frame:
![image](https://cloud.githubusercontent.com/assets/4499789/11898419/c477f80e-a5a8-11e5-8072-0fd532d80bd5.png)
- After that application execution continues, but Dartium process is eating my CPU, performance is becoming worse.

Wild guess is that event cycle is done, Dartium is still trying to suspend VM after StepOver, may be doing numerous supend/resume internally, but in fact never suspends again even when user triggers next event cycle, for example by mouse click.

I think from user point of view StepOver always should suspend somewhere and never just resume the app.

**Comment by alexander-doroshko** [comment] 2015-12-18 14:27
Experiments with debugging JavaScript in Chrome show that Chrome's behavior is better. When you stand on the last instruction for current event in the Event Loop and ask to StepOver it starts handling the next event and suspends there.

**Comment by terrylucas** [comment] 2017-07-05 20:24
Please re-try with Dart 1.24.2 Stable (Dartium 50).

**Closed by terrylucas** 2017-07-05 20:24 UTC
Labels: area-dartium
