### ISSUE TITLE
Analyzer does not recognize conditional property checks to be null safe

### ISSUE THREAD

**Issue by crtl** [dart-lang/sdk#47697] opened 2021-11-15 13:19 UTC
This tracker is for issues related to:

* Analyzer

If you aren't sure, file the issue here and we'll find the right home for it.
In your issue, please include:

* Dart SDK Version : 2.14.2 (stable) (Wed Sep 15 12:32:06 2021 +0200) on "windows_x64"
* Windows 10

Before null safety you could use conditional properties to check for null and the desired value like the following:

```
final list = null;

if (list != null && list.isNotEmpty)
// Using conditional property, does not work with null-safety because analyzer still thinks list is nullable
if (list?.isNotEmpty == true)
```

Using the conditional property you can check for empty and null with one statement and its null safe.
But after migrating to null safety the analyzer does not recognize this as nullsafe and instead i have to convert these statements back to classical null checks or use `!` or `?` modifiers.

**Comment by eernstg** [comment] 2021-11-15 14:46
This is a duplicate of dart-lang/language#1224, please follow/discuss the feature on that issue.

**Closed by eernstg** 2021-11-15 14:46 UTC
Labels: closed-duplicate
