### ISSUE TITLE
dart2js with NNBD doesn't allow read of variable during its initialization

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42642] opened 2020-07-09 11:43 UTC
With NNBD enabled it's not an error to read variable or getter during its initialization. For example the following code works in CFE with NNBD turned on but failed on dart2js
```dart
int count = 0;

int f() {
  return count++ < 20 ? C.sTyped : count;
}

class C {
  static int sTyped = f();
}

main() {
  print(C.sTyped); // 21
}
```
In dart2js it produces
```
Runtime error:
Reading static variable 'C_sTyped' during its initialization
```

**Comment by sigmundch** [comment] 2020-07-09 15:48
thanks for the bug report! I'm marking it as a duplicate of #42419

**Closed by sigmundch** 2020-07-09 15:48 UTC
Labels: area-web, type-bug, web-dart2js
