### ISSUE TITLE
"dart2js" crashes

### ISSUE THREAD

**Issue by yuanzhaowei** [dart-lang/sdk#38428] opened 2019-09-17 02:23 UTC
* Dart SDK Version
   Dart VM version: 2.6.0-edge.e6887536aadc7fbd1990448989601cee0224958d (Thu Sep 12 01:20:05 2019 +0000) on "linux_arm"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
   Linux (Raspberry Pi3)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
   None

Hi, I'm building flutter on arm platform which calls dart2js to compile something
Before doing this, I built dart for arm according to the guide from https://github.com/dart-lang/sdk/wiki/Building, and then copy "sdk/out/ReleaseXARM/dart-sdk" to the directory "/home/pi/work/flutter/engine/src/third_party/dart/tools/sdks" of target board (Raspberry Pi3)
but it looks like dart2js crashes, here is the whole log:

 sudo ninja -C out/linux_debug_unopt_arm/ -k 0
ninja: Entering directory `out/linux_debug_unopt_arm/'
[1/200] ACTION //third_party/dart/runtime/observatory:build_observatory(//build/toolchain/linux:clang_arm)
FAILED: gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js.map
python ../../third_party/dart/build/gn_run_binary.py compiled_action /home/pi/work/flutter/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart2js /home/pi/work/flutter/engine/src/third_party/dart/runtime/observatory/web/main.dart -DOBS_VER=2.6.0-edge -o /home/pi/work/flutter/engine/src/out/linux_debug_unopt_arm/gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js --packages=/home/pi/work/flutter/engine/src/third_party/dart/runtime/observatory/.packages
Command failed: /home/pi/work/flutter/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart2js /home/pi/work/flutter/engine/src/third_party/dart/runtime/observatory/web/main.dart -DOBS_VER=2.6.0-edge -o /home/pi/work/flutter/engine/src/out/linux_debug_unopt_arm/gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js --packages=/home/pi/work/flutter/engine/src/third_party/dart/runtime/observatory/.packages
output: ../../third_party/dart/runtime/observatory/web/main.dart:
Internal Error: The compiler crashed when compiling this element.

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: Crash when compiling file:///home/pi/work/flutter/engine/src/third_party/dart/runtime/observatory/web/main.dart,
at character offset null:
Unexpected Kernel version 29 (expected 31).
#0      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:7)
#1      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:398:10)
#2      ProcessedOptions.loadLinkDependencies.<anonymous closure> (package:front_end/src/base/processed_options.dart:382:35)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      ProcessedOptions.loadLinkDependencies (package:front_end/src/base/processed_options.dart:382:67)
<asynchronous suspension>
#6      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:109:48)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#8      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#9      compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:166:43)
<asynchronous suspension>
#10     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:136:20)
<asynchronous suspension>
#11     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#12     new Future.sync (dart:async/future.dart:224:31)
#13     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:134:10)
#20     compile (package:front_end/src/api_unstable/dart2js.dart:164:57)
<asynchronous suspension>
#21     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:109:27)
<asynchronous suspension>
#22     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#23     KernelLoaderTask.load (package:compiler/src/kernel/loader.dart:59:12)
#24     Compiler.runInternal (package:compiler/src/compiler.dart:236:48)
<asynchronous suspension>
#25     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:210:38)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:210:20)
#28     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#29     Compiler.run (package:compiler/src/compiler.dart:207:41)
#30     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#31     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

#0      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:457:7)
#1      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:398:10)
#2      ProcessedOptions.loadLinkDependencies.<anonymous closure> (package:front_end/src/base/processed_options.dart:382:35)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      ProcessedOptions.loadLinkDependencies (package:front_end/src/base/processed_options.dart:382:67)
<asynchronous suspension>
#6      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:109:48)
<asynchronous suspension>
#7      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#8      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:69:10)
<asynchronous suspension>
#9      compile.<anonymous closure> (package:front_end/src/api_unstable/dart2js.dart:166:43)
<asynchronous suspension>
#10     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:136:20)
<asynchronous suspension>
#11     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#12     new Future.sync (dart:async/future.dart:224:31)
#13     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:134:10)
#20     compile (package:front_end/src/api_unstable/dart2js.dart:164:57)
<asynchronous suspension>
#21     KernelLoaderTask.load.<anonymous closure> (package:compiler/src/kernel/loader.dart:109:27)
<asynchronous suspension>
#22     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#23     KernelLoaderTask.load (package:compiler/src/kernel/loader.dart:59:12)
#24     Compiler.runInternal (package:compiler/src/compiler.dart:236:48)
<asynchronous suspension>
#25     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:210:38)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:210:20)
#28     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#29     Compiler.run (package:compiler/src/compiler.dart:207:41)
#30     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#31     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

ninja: build stopped: cannot make progress due to previous errors.

**Comment by sigmundch** [comment] 2019-09-18 04:26
The error above seems to indicate a version inconsistency.

It seems dart2js is trying to load a .dill file (aka kernel, a binary representation of Dart) that uses a different version than the version accepted by the dart2js parser. Normally we read a .dill file for the SDK sources, and then compile the program directly.

I'm not sure what is causing the inconsistency, but some theories are:
 * dart2js is reading the sdk .dill file from the wrong location
 * the copy of the sdk you created has the new binaries, but may still have old files in the dart-sdk/lib/ folder?


@aam @a-siva @rmacnak-google - do you or others in the VM team have experience in building flutter for arm and can assist this user on this issue? Is it possible for example to workaround this (e.g. by skipping the observatory build step)?

**Comment by aam** [comment] 2019-09-18 13:58
> I built dart for arm ... and then copy "sdk/out/ReleaseXARM/dart-sdk" to the directory "/home/pi/work/flutter/engine/src/third_party/dart/tools/sdks" of target board (Raspberry Pi3)

Immediate problem you are hitting it seems is caused by the fact that dart sdk you built for arm is newer, not compatible with dart sdk that is built as part of flutter/flutter engine you are building. Check dart revision that flutter engine uses `cat $FH/engine/src/flutter/DEPS | grep dart_rev`, then build dart for arm that revision.

**Comment by yuanzhaowei** [comment] 2019-09-27 09:10
Thanks,
I've checked drat version described in file  $FH/engine/src/flutter/DEPS, that is:
36985859e421a9fbbdfc56379506b2a367c7d4e9

I used following command to set dart version as asked:
git reset --hard  36985859e421a9fbbdfc56379506b2a367c7d4e9
and re-built it:
./tools/build.py --mode release --arch arm create_sdk
Am I right? 

If I'm right, how can I use new built dart to replace the one under flutter engine, I mean which files I should copy to flutter engine? and to where?

**Comment by yuanzhaowei** [comment] 2019-09-27 12:06
I've tried 2 ways:
1. cd engine/src/third_party/
   mv dart dart-backup
   ln -s ../../../dart-sdk/sdk dart (../../../dart-sdk/sdk is the root directory of dart-sdk )
   compile...
gives following error: 
ERROR at //flutter/BUILD.gn:46:9: Can't load input file.
[    3s]         "//third_party/dart:create_sdk"

2. cd engine/src/third_party/dart
    cp -r ../../../dart-sdk/sdk/out/ReleaseXARM/dart-sdk/ ./tools/sdks/
gives following error:
ERROR at //flutter/shell/version/version.gni:15:7: Script returned non-zero exit code.
[   10s]       exec_script("$flutter_root/build/git_revision.py",

I don't know what to do next

**Comment by yuanzhaowei** [comment] 2019-09-28 09:25
Hi，it can work now when I take following way:
cp -r ../../../dart-sdk/sdk/out/ReleaseXARM/dart-sdk/ xxx/engine/src/third_party/dart/tools/sdks/
It seems because my environment lack some library which cause  "xxx/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart" doesn't work correctly

now, my situation is:
1. "gn" works successfully
2. compilers outputs following error log and stop compiling:
Binary not found: third_party/dart/tools/sdks/dart-sdk/bin/dart2js

So I checked dart-sdk building directory, "out/ReleaseXARM/dart-sdk/bin" doesn't has a file names "dart2js", but "out/ReleaseX64/dart-sdk/bin/" does. 
How can I make a "dart2js" file for arm?

By the way:
I'm building flutter for arm platform on a arm host
(e.g. host_cpu is arm and target_cpu is arm too.)

**Comment by yuanzhaowei** [comment] 2019-10-12 08:40
@aam Could you please check my problem?
I can find bin file "dart2js" under directory: ./out/ReleaseXARM/, so I have to do following:
cp .../dart-sdk/sdk/sdk/bin/dart2js  .../flutter/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/

I'm not sure if this operation is correct, because it crashes again during compiling flutter, error log:
[  217s] [28/2064] ACTION //third_party/dart/runtime/observatory:build_observatory(//build/toolchain/linux:arm)
[  217s] FAILED: gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js.map
[  217s] python ../../third_party/dart/build/gn_run_binary.py compiled_action /home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/third_party/dart/tools/sdks/dart-sdk/bin/dart2js /home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/third_party/dart/runtime/observatory/web/main.dart -DOBS_VER=2.6.0-edge -o /home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/out/linux_debug_unopt_arm/gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js --packages=/home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/third_party/dart/runtime/observatory/.packages
[  217s] Command failed: /home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/third_party/dart/tools/sdks/dart-sdk/bin/dart2js /home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/third_party/dart/runtime/observatory/web/main.dart -DOBS_VER=2.6.0-edge -o /home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/out/linux_debug_unopt_arm/gen/third_party/dart/runtime/observatory/observatory/web/main.dart.js --packages=/home/abuild/rpmbuild/BUILD/flutter-1.0.0.1/third_party/dart/runtime/observatory/.packages
[  217s] output: Error: Input file not found: ../../third_party/dart/tools/sdks/dart-sdk/lib/_internal/dart2js_platform.dill.
[  217s] Error: Error when reading '../../third_party/dart/tools/sdks/dart-sdk/lib/_internal/dart2js_platform.dill': Error reading '../../third_party/dart/tools/sdks/dart-sdk/lib/_internal/dart2js_platform.dill'  (No such file or directory)
[  217s] ../../third_party/dart/runtime/observatory/web/main.dart:
[  217s] Internal Error: The compiler crashed when compiling this element.
[  217s]
[  217s] The compiler is broken.

**Comment by sigmundch** [comment] 2019-10-28 23:17
I believe this is now the same issue as https://github.com/dart-lang/sdk/issues/38910

Closing this in favor of the other bug.

**Comment by franklinyow** [comment] 2021-05-11 22:56
Closing

**Closed by franklinyow** 2021-05-11 22:56 UTC
Labels: area-build, closed-duplicate, type-bug
