### ISSUE TITLE
dart2js null operator + cascade operator error

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#28367] opened 2017-01-12 19:43 UTC
The following code will produce an error when compiled with `dart2js`:

```dart
main()
{
  new Item()
      ..blah = false
      ..userData?.cancel()
      ..userData = null;
  
  print('ok');
}

class Item
{
  bool blah = false;
  UserData userData;
}

class UserData
{
  cancel(){}
}
```

It produces the error:

Error compiling to JavaScript:
[error on line 5] Expected ';' after this.

Same code works fine on vm.

Dartpad here: https://dartpad.dartlang.org/afbc0983fef1444a0609565e117c44c0

SDK version 1.21.0

**Comment by sigmundch** [comment] 2017-01-23 21:20
seems like our parser is not handling this correctly - @peter-ahe-google I'm adding the area-fasta here since this is most likely going to need to be fixed in the code base that you are currently working on, but feel free to change the label if you prefer

**Comment by peter-ahe-google** [comment] 2017-01-24 08:24
I can reproduce this with package:dart_parser.

**Comment by lrhn** [comment] 2017-01-24 08:39
Just for completeness, the grammar for cascade sections is:
```
cascadeSection:
    ‘..’ (cascadeSelector arguments*) (assignableSelector arguments*)*
          (assignmentOperator expressionWithoutCascade)?
    ;
```
so ` ..userData?.cancel()` should be allowed. 
`userData` is a `cascadeSelector`, `?. cancel` is an `assignableSelector` and `()` is an `arguments.


Hmm, it also allows `..foo() = 42`, which shouldn't be possible. Might need a little tweaking.

**Comment by eernstg** [comment] 2017-01-24 09:34
> .. `..foo() = 42` ..

That shouldn't be a problem as long as it is detected as being a compile time error (which it is). For instance, `dart2js` clearly treats one and only one of the following snippets as a syntax error:
```
Error: Unexpected token '!'.
  1..! = 42;
     ^
Error: Compilation failed.
...
Error: Not assignable.
  1..foo() = 42;
  ^^^^^^^^
Error: Compilation failed.
```
Looking closely at the output from the analyzer you can see that it uses a similar approach. So let's just keep the grammar simple and catch this kind of error after parsing.

**Comment by peter-ahe-google** [comment] 2017-01-24 09:41
I would be more comfortable if one could quote the specification instead of implementations.

**Comment by eernstg** [comment] 2017-01-24 10:55
Indeed.

The point I made was that we should not put a lot of complexity into the grammar in cases where a simple grammar and some simple static semantic checks will yield the same (and the intended) set of valid programs. It may not be so complex to fix in the grammar, but I haven't looked into that in any detail.

But it's of course completely fair that you raise the following issue: "Where does the language specification say that these constructs are compile-time errors?". That wasn't immediately obvious to me, so thanks for insisting on it. ;-)

The spec (current version, Sect. 16.19 Assignment) describes the semantics of assignment in a large number of cases (where the left hand side is a local variable, a library variable, getter, or setter, etc.etc.). I cannot see that it explicitly states that missing cases are errors (nor, of course, whether they are compile time errors etc.), so we need to ensure that this is mentioned explicitly.

As far as I can see, the spec does not make it explicit what an assignment _is_, so we need to add the assumption that the rules in Sect. 16.19 are applicable to expressions on the form `assignableExpression assignmentOperator expression` as wall as a number of other forms that we consider to be assignments, including the ones that may arise in a `cascadeSection`. Surely Sect. 16.19 will need to be inspected carefully in order to ensure that it covers all those forms as intended.

With those two assumptions I believe we can claim that the unwanted forms mentioned above are compile-time errors. 

I created a language-team issue to follow up on this.

**Comment by peter-ahe-google** [comment] 2017-01-24 14:45
Thank you, @eernstg. I want to be clear that I'm not blocked by waiting for the specification. In this case, it's obvious what the right thing to do is, and if I discover anything when fixing this bug, I'll update the specification bug.

**Comment by natebosch** [comment] 2018-08-23 23:12
This example is working fine in dart2js, and vm in the latest SDK. I think CFE is handling it correctly.

**Closed by natebosch** 2018-08-23 23:12 UTC
Labels: area-front-end, front-end-fasta, p2-medium
