### ISSUE TITLE
auto compiling turning off for Dart intermittently(Android Studio)

### ISSUE THREAD

**Issue by horgag1** [dart-lang/sdk#35166] opened 2018-11-14 12:43 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/x5/_0cyvynn4j79zf_gc5h01l5w0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/gerardhorgan/AndroidStudioProjects/json_practice/lib/main.dart context: exception_20181114_124135_342
Exception: Element not found in summary: dart:core

**Comment by kevmoo** [comment] 2018-11-14 21:54
Please paste the information from `/private/var/folders/x5/_0cyvynn4j79zf_gc5h01l5w0000gn/T/report.txt` or there's not much we can do!

**Comment by stereotype441** [comment] 2018-11-15 18:44
Duplicate of #34555

**Closed by stereotype441** 2018-11-15 18:44 UTC
Labels: area-analyzer, needs-info
