### ISSUE TITLE
dart2 prints error messages twice

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32962] opened 2018-04-24 22:23 UTC
--- bug1a2c.dart ---
```dart
main() {
  var a = true;
  a &&= a;
}
```

```
$ pkg/vm/tool/dart2 bug1a2c.dart
bug1a2c.dart:3:7: Error: Expected an identifier, but got '='.
  a &&= a;
      ^
bug1a2c.dart:3:7: Error: Getter not found: ''.
  a &&= a;
      ^
bug1a2c.dart:3:7: Error: Can't assign to this.
  a &&= a;
      ^
bug1a2c.dart:3:7: Error: Expected an identifier, but got '='.
  a &&= a;
      ^
bug1a2c.dart:3:7: Error: Getter not found: ''.
  a &&= a;
      ^
bug1a2c.dart:3:7: Error: Can't assign to this.
  a &&= a;
      ^
$ 
```

The messages are not very helpful - perhaps the parser should recognize and treat `&&=` like an assignment operator even if &&= is not implemented.
I find `Getter not found: ''` especially confusing.

**Comment by a-siva** [comment] 2018-04-25 18:12
marking this as a duplicate of https://github.com/dart-lang/sdk/issues/32976

**Closed by a-siva** 2018-04-25 18:12 UTC
Labels: area-front-end
