### ISSUE TITLE
Unused package import adds 5 seconds to execution time of empty script

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#34049] opened 2018-08-01 10:32 UTC
I don't know if this is expected, but it seems like it should be avoidable.

Given this script that does nothing, it executes really fast:

```dart
main() {}
```

```
dantup-macbookpro:flutter_tools dantup$ time dart test.dart 

real	0m0.273s
user	0m0.387s
sys	0m0.086s
```

If I add an unused import to the analyzer package, it's not so fast:

```dart
import 'package:analyzer/dart/ast/ast.dart';

main() {}
```

```
dantup-macbookpro:flutter_tools dantup$ time dart test.dart 

real	0m4.986s
user	0m6.882s
sys	0m0.529s
```

I wonder if this could be optimised - as I understand it, no code should execute from the import, so maybe it shouldn't cause any negative performance hit?

I don't know if there's much real world code that'd benefit from fixing this or whether it's dependant on the package, I just noticed it while timing some tests - a lot of time was being spend loading test files that were not being executed.

```
dantup-macbookpro:flutter_tools dantup$ dart --version
Dart VM version: 2.0.0-dev.69.4.flutter-08f59e5de3 (Sat Jul 28 00:01:50 2018 +0000) on "macos_x64"
```

**Comment by jakemac53** [comment] 2018-08-01 21:58
With Dart 2 all reachable code is processed by the common frontend first, regardless of whether or not it is used. There will be ongoing efforts to speed that up for probably a long time.

In the meantime the edit/refresh experience can be improved using modular/incremental builds, for instance we now have the `build_vm_compilers` package which works with `build_runner` and `build_test` to do just that, although it really only supports running tests well today. To run the generated kernel files directly otherwise you have to dive into the build cache which isn't ideal.

I am going to close this as "working as intended" for now.

**Closed by jakemac53** 2018-08-01 21:58 UTC
