### ISSUE TITLE
Test co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01 crashes on CFE

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46900] opened 2021-08-13 08:33 UTC
Test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01.dart produces the following output

```
C:/dart-sdk/bin/dart.exe --enable-experiment=nonfunction-type-aliases,triple-shift,constructor-tearoffs --enable-asserts C:\Users\sgrek\Work\Google\co19\LanguageFeatures\Constructor-tear-offs\named_constructor_A08_t01.dart
Unhandled exception:
'file:///C:/Users/sgrek/Work/Google/co19/LanguageFeatures/Constructor-tear-offs/named_constructor_A08_t01.dart': error: function invocation
#0      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

Process finished with exit code 254
```

Tested on `Dart SDK version: 2.15.0-edge.b2b8e59b2863ef02709dfdb750e9ae8e3732389c (be) (Fri Aug 13 01:08:51 2021 +0000) on "windows_x64" `

**Comment by johnniwinther** [comment] 2021-08-17 13:37
Duplicate of #46925

**Closed by johnniwinther** 2021-08-17 13:37 UTC
Labels: area-front-end
