### ISSUE TITLE
analysis_issue

### ISSUE THREAD

**Issue by Wuchiwei** [dart-lang/sdk#35038] opened 2018-11-02 17:43 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/2y/sy9fgd2x6zq0jq75kpgkjlp80000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/wuchihwei/Documents/GoodJob/goodjob-app/goodjob/lib/ui/main/main_tab.dart
Exception: Element not found in summary: dart:core

**Comment by srawlins** [comment] 2018-11-03 22:33
Duplicate of #35023.

**Closed by srawlins** 2018-11-03 22:33 UTC
