### ISSUE TITLE
Failures on Prepare to publish analyzer 1.6.0 and _fe_analyzer_shared 22.0.0

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46137] opened 2021-05-25 22:30 UTC
There are new test failures on [Prepare to publish analyzer 1.6.0 and _fe_analyzer_shared 22.0.0](https://github.com/dart-lang/sdk/commit/d696ca2f2bf27199d2178e27e45631a510ca4145).

The tests
```
pkg/dartdev/test/commands/test_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-debug-linux
unittest-asserts-release-linux
unittest-asserts-release-win
```

```
00:52 [32m+2[0m[31m -2[0m: test runs test [1m[31m[E][0m[0m

  Expected: empty
    Actual: 'Failed to precompile test:test:\n'
              '/home/chrome-bot/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:1600:40: Error: Getter not found: \'topLevelVariable\'.\n'
              '      return kinds.contains(TargetKind.topLevelVariable);\n'
              '                                       ^^^^^^^^^^^^^^^^\n'
              '/home/chrome-bot/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Getter not found: \'topLevelVariable\'.\n'
              '      case TargetKind.topLevelVariable:\n'
              '                      ^^^^^^^^^^^^^^^^\n'
              '/home/chrome-bot/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Type \'dynamic\' of the case expression is not a subtype of type \'TargetKind\' of this switch expression.\n'
              ' - \'TargetKind\' is from \'package:meta/meta_meta.dart\' (\'/home/chrome-bot/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/meta_meta.dart\').\n'
              '      case TargetKind.topLevelVariable:\n'
              '                      ^\n'
              '/home/chrome-bot/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2001:13: Context: The switch expression is here.\n'
              '    switch (this) {\n'
              '            ^\n'
              ''
  

  package:test_api/src/expect/expect.dart 137:31     fail
  package:test_api/src/expect/expect.dart 132:3      _expect
  package:test_api/src/expect/expect.dart 46:3       expect
  pkg/dartdev/test/commands/test_test.dart 91:5      defineTest.<fn>
  package:test_api/src/backend/declarer.dart 199:19  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 197:7   Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 257:7    Invoker._waitForOutstandingCallbacks.<fn>
```
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8846226472649531648/+/u/test_results/new_test_failures__logs_

/cc @scheglov

**Comment by bwilkerson** [comment] 2021-05-25 22:31
I believe this is a duplicate of https://github.com/dart-lang/sdk/issues/46136.

**Closed by bwilkerson** 2021-05-25 22:31 UTC
Labels: area-analyzer, gardening
