### ISSUE TITLE
compiler error & error on webdev serve

### ISSUE THREAD

**Issue by HassanEm** [dart-lang/sdk#37497] opened 2019-07-11 09:54 UTC
_f0d33bdb-a3c0-11e9-814d-00acb06ff407/.packages --module-name=packages/vector_math/vector_math_64 --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:vector_math/src/vector_math_64/matrix3.dart package:vector_math/src/vector_math_64/quaternion.dart package:vector_math/src/vector_math_64/triangle.dart package:vector_math/src/vector_math_64/plane.dart package:vector_math/src/vector_math_64/matrix4.dart package:vector_math/src/vector_math_64/vector2.dart package:vector_math/src/vector_math_64/obb3.dart package:vector_math/src/vector_math_64/opengl.dart package:vector_math/src/vector_math_64/intersection_result.dart package:vector_math/src/vector_math_64/third_party/noise.dart package:vector_math/src/vector_math_64/vector4.dart package:vector_math/src/vector_math_64/vector3.dart package:vector_math/src/vector_math_64/matrix2.dart package:vector_math/src/vector_math_64/aabb3.dart package:vector_math/src/vector_math_64/constants.dart package:vector_math/src/vector_math_64/frustum.dart package:vector_math/vector_math_64.dart package:vector_math/src/vector_math_64/error_helpers.dart package:vector_math/src/vector_math_64/utilities.dart package:vector_math/src/vector_math_64/ray.dart package:vector_math/src/vector_math_64/aabb2.dart package:vector_math/src/vector_math_64/quad.dart package:vector_math/src/vector_math_64/vector.dart package:vector_math/src/vector_math_64/colors.dart package:vector_math/src/vector_math_64/sphere.dart
    dart --version: 2.5.0-dev.1.0 (Tue Jul 9 15:27:01 2019 +0200) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
#4      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by mraleph** [comment] 2019-07-11 10:07
Duplicate of #37490

**Closed by mraleph** 2019-07-11 10:07 UTC

**Comment by jrbhat-g** [comment] 2019-09-12 05:23
U
nhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aurl_launcher%2Furl_launcher.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (
package:front_end/src/api_prototype/standard_file
_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:601:37)
<asynchronous suspension>
#2      FrontendCompiler._outputDependenciesDelta (package:vm/frontend_server.dart:401:39)
<asynchronous suspension>
#
3      FrontendCompiler.compile (package:vm/frontend_server.dart:375:13)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
<asynchronous suspension>

#5      starter (package:frontend_server/server.dart:128:27)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/k/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#7      _startIsolate.<a
nonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
