### ISSUE TITLE
IndexedDB openCursor very slow in Chromium 45

### ISSUE THREAD

**Issue by lymp** [dart-lang/sdk#25995] opened 2016-03-14 18:06 UTC
First described here:[DartLang forum](https://groups.google.com/a/dartlang.org/forum/#!topic/web/vrmQGOXmZH0l)
```
var request = store.openCursor(autoAdvance: true).listen((cursor) {
  callbackMaps(cursor.value,optionalArg);}, onError: _onError);

```
and callbackMaps takes 8-12 seconds. In Chrome and Chromium 39 it takes a fraction of a second.

**Comment by alan-knight** [comment] 2016-03-14 23:23
Also from the forum. 

So, when I run the following code, adapted from tests/html/indexeddb_3_test.dart, on a Mac, in Dartium 1.14.2 I get roughly 175 ms, and in 1.15.0 I get roughly 250ms. So there's a slowdown, but it's not nearly as large as you're seeing. Do you have an example that exhibits the larger slowdown? 

```
import 'dart:html' hide Notification;
import 'dart:indexed_db';
import 'dart:async';

var db;
var completer = new Completer();

main() async {
  var start = new DateTime.now().millisecondsSinceEpoch;
  db = await setupDb();
  readAllViaCursor(db);
  await completer.future;
  print("Time in milliseconds: ${new DateTime.now().millisecondsSinceEpoch - start}");
}

// Read with cursor.

const String DB_NAME = 'Test3';
const String STORE_NAME = 'TEST';
const int VERSION = 1;


Future<Database> createAndOpenDb() {
  return window.indexedDB.deleteDatabase(DB_NAME).then((_) {
    return window.indexedDB.open(DB_NAME, version: VERSION,
    onUpgradeNeeded: (e) {
      var db = e.target.result;
      db.createObjectStore(STORE_NAME);
    });
  });
}

Future<Database> writeItems(Database db) {
  Future<Object> write(index) {
    var transaction = db.transaction(STORE_NAME, 'readwrite');
    transaction.objectStore(STORE_NAME).put('Item $index', index);
    return transaction.completed;
  }

  var future = write(0);
  for (var i = 1; i < 100; ++i) {
    future = future.then((_) => write(i));
  }

  // Chain on the DB so we return it at the end.
  return future.then((_) => db);
}

Future<Database> setupDb() {
  return createAndOpenDb().then(writeItems);
}

void readAllViaCursor(Database db) {
  Transaction txn = db.transaction(STORE_NAME, 'readonly');
  ObjectStore objectStore = txn.objectStore(STORE_NAME);
  int itemCount = 0;
  int sumKeys = 0;
  var lastKey = null;

  var cursors = objectStore.openCursor(autoAdvance: true);
  cursors.listen(
          (cursor) {
        ++itemCount;
        lastKey = cursor.key;
        sumKeys += cursor.key;
        expect(cursor.value, 'Item ${cursor.key}');
        if ((cursor.key % 10) == 0) print(cursor.value);
        if (cursor.key == 99) completer.complete();
      });
}

expect(a, b) {
  if (a != b) throw "Expect $a = $b failed";
}
```

**Comment by lymp** [comment] 2016-03-14 23:30
Hi, 

No, I only have my app I'm afraid. 

Please give me a  couple of days, and I'll rip out my class that uses IndexedDb, in a small project. Hopefully it will reproduce it. 


Many thanks - and for the code 
Cheers 

Steve 
 


-----Original Message-----

**Comment by alan-knight** [comment] 2016-03-15 18:28
Thanks. I appreciate the effort on your part.

**Comment by alan-knight** [comment] 2016-03-15 21:47
Oh, two other thoughts. First is try downloading a current dev channel Dartium and see if it might be an issue that's already addressed. https://www.dartlang.org/downloads/archive/

If I were to guess at the reason for the slowness, two things I can think of. One is the conversion of serialized script values. If your database values are more complicated that would be more expensive, and there might be something that's doing an O(n^2) operation in deserializing them or in the number of deserializations. The other is if you have typed arrays. I think we are copying those in some circumstances where we used to share, so lots of those might cause a problem. But that's just guessing without evidence.

**Comment by lymp** [comment] 2016-03-17 11:05
Hi, 
Sorry, this was stuck in my outbox.. Should have been posted before my last post. 

I have reported the datetime map problem I had. This does not impact on the performance of opening the indexeddb. 

I can see no other reason for performance apart from the size of the map ie the number of items. In my debug mode, my map keys are long and descriptive (15 chars and more). In production  I switch to terse 3 char ones. It made no difference in opening speed. Still 25 seconds. 

I also tried it in chromium 1.16 dev. No change. 

Cheers 

Steve 

M: 0777 196 0074 


-----Original Message-----

**Comment by alan-knight** [comment] 2016-03-18 19:15
OK, if we can't reproduce it outside your app, maybe try profiling your app.

I'd say try both profiling it with Observatory and with the devtools. One
will, with luck, indicate time spent in Dart, and the other in JavaScript.
If we're lucky, we'll see some ridiculous amount of time spent in an
obvious method.

**Comment by alan-knight** [comment] 2016-03-22 00:35
https://codereview.chromium.org/1817343002/

**Comment by alan-knight** [comment] 2016-03-22 20:43
Should be fixed now in bleeding edge

**Closed by alan-knight** 2016-03-22 20:43 UTC
Labels: area-dartium
