### ISSUE TITLE
Can't run tests on Intellij

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#42972] opened 2020-08-06 19:52 UTC
Everything was working fine until I updated my Dart SDK to 2.10.0-3.0.dev (it was working with 2.9).

Everytime I right click on my dart tests folder e click Run tests, I get an error:

![image](https://user-images.githubusercontent.com/1146982/89576104-2bd46f80-d805-11ea-958b-3d1cac3463ad.png)

```
Testing started at 16:50 ...
C:\Users\shina\Desenvolvimento\Dart\dart-sdk\bin\pub.bat run test -r json C:/Users/shina/Desenvolvimento/dart_projects/maxpb_dart
Could not find an option or flag "-r".

Usage: dart run [arguments] <dart file | package target>
-h, --help                                             Print this usage information.

Debugging options:
    --observe=<[<port>[/<bind-address>]]>              The observe flag is a convenience flag used to run a program with a set of common options useful for debugging.

Options implied by --observe are currently:
    --enable-vm-service=<[<port>[/<bind-address>]]>    Enables the VM service and listens on the specified port for connections (default port number is 8181, default bind address is localhost).
    --[no-]pause-isolates-on-exit                      Pause isolates on exit when running with --enable-vm-service.
    --[no-]pause-isolates-on-unhandled-exceptions      Pause isolates when an unhandled exception is encountered when running with --enable-vm-service.
    --[no-]warn-on-pause-with-no-debugger              Print a warning when an isolate pauses with no attached debugger when running with --enable-vm-service.

Other debugging options include:
    --[no-]pause-isolates-on-start                     Pause isolates on start when running with --enable-vm-service.
    --[no-]enable-asserts                              Enable assert statements.

Run "dart help" to see global options.
Observatory listening on http://127.0.0.1:63370/lk2goeQl21A=/


Process finished with exit code 64
```

**Comment by alexander-doroshko** [comment] 2020-12-09 09:36
@shinayser Sorry for delay with this issue. Bugs in the Dart plugin are usually tracked in the [JetBrains issue tracker](https://youtrack.jetbrains.com/issues?q=project:%20WEB%20subsystem:%20Dart) (project: WEB, subsystem: Dart).

But in this case it could also be a problem with `test` package. Its issues are tracked in https://github.com/dart-lang/test/issues.

Anyway, I can't reproduce the issue with the latest tools (Dart SDK 2.10.4 and test package 1.15.7). I guess it's been fixed. Please confirm and close the issue if so. Thanks!

**Comment by shinayser** [comment] 2020-12-24 03:59
I was using the fluitter SDK instead of DART sdk =P

**Closed** 2020-12-24 03:58 UTC
Labels: area-intellij
