### ISSUE TITLE
Deprecate old DDC pub page

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#29911] opened 2017-06-16 15:09 UTC
Can we remove / deprecate / repoint this:

https://pub.dartlang.org/packages/dev_compiler

?  Note sure this should be filed here or elsewhere.

@kevmoo @kwalrath

**Comment by kevmoo** [comment] 2017-06-16 15:11
Until we have explicit support for deprecation, we should publish another +1 version that calls it out as explicitly deprecated.

See what @nex3 did here – https://github.com/dart-lang/scheduled_test/commit/05d1d3999516a6c3230580edf9a1bed391c6f002

**Comment by kwalrath** [comment] 2017-06-16 17:32
I could do a PR for the README & CHANGELOG.

**Comment by matanlurey** [comment] 2017-06-16 17:38
Should we also link to the Gitter chatroom? It's ~sort of used.

**Comment by kwalrath** [comment] 2017-06-16 17:58
https://webdev.dartlang.org/tools/dartdevc/faq links to the chatroom.

**Comment by matanlurey** [comment] 2017-06-16 17:59
Oh I meant with a gitter badge similar to https://github.com/dart-lang/angular2.

So when we publish it for the last time, folks can click on it. Just an idea.

**Comment by kwalrath** [comment] 2017-06-16 18:01
I'm good with that. @vsmenon & @kevmoo, what do you think?

**Comment by vsmenon** [comment] 2017-06-16 18:03
sgtm

**Comment by kwalrath** [comment] 2017-06-16 18:08
OK, I'll start a PR.

**Comment by kwalrath** [comment] 2017-06-16 19:35
The CHANGELOG currently says:

## next release
- add support for AMD modules and make it the default.
- precompile the SDK in AMD, CommonJS, and ES6 flavors.
- legacy module format is deprecated.

Does that mean there's new functionality in this release, and the number should go up to 0.1.25?

**Comment by kwalrath** [comment] 2017-07-17 17:35
So... Now I think @vsmenon (or someone else with permissions, could be me if you use https://www.dartlang.org/tools/pub/cmd/pub-uploader to give me access) needs to publish a +1 version, like what @nex3 did here – dart-lang/scheduled_test@05d1d39.

**Comment by kwalrath** [comment] 2017-07-31 20:38
Looking at https://pub.dartlang.org/packages/dev_compiler, it looks like @vsmenon, @jmesserly, or @leafpetersen can publish this package.

**Comment by vsmenon** [comment] 2017-07-31 20:42
Kathy - just added you to the uploader list as well.

**Comment by kwalrath** [comment] 2017-07-31 22:10
I tried to publish, but I ran into issues and eventually gave up.

For example, I saw tons of errors referring to the test code using package:expect, which doesn't seem to exist. I tried a few obvious fixes (go back to Dart 1.15, delete the test directory, ...) but it just seemed to uncover more issues.

**Comment by kwalrath** [comment] 2018-03-15 17:50
Just confirmed that https://pub.dartlang.org/packages/dev_compiler is marked as DISCONTINUED. It does not show up in site search results.

**Closed by kwalrath** 2018-03-15 17:50 UTC
Labels: area-pkg
