### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JastAir** [dart-lang/sdk#37204] opened 2019-06-08 23:31 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-183.4886.37`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `IU-183.4886.37, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1440x900, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/09/ktq4zlh92750f4bgz4hrt20h0000gn/T/report.txt

```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, FATAL error: Failed to handle request: {id: 15, method: edit.getFixes, params: {file: /Users/s.neiko/Web Projects/B2B/b2b/lib/main.dart, offset: 52}, clientRequestTime: 1560036667414}
AnalysisException: Cannot analyze "/Users/s.neiko/Web Projects/B2B/b2b/lib/Pages/Products%20list/ProductsListPage.dart"

#0      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:72:7)
<asynchronous suspension>
#1      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:82:23)
<asynchronous suspension>
#2      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:52:18)
#3      FixProcessor._addFix_createImportUri (package:analysis_server/src/services/correction/fix_internal.dart:2057:31)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:277:13)
<asynchronous suspension>
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#6      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:639:46)
<asynchronous suspension>

**Comment by devoncarew** [comment] 2019-06-09 22:07
Thanks for the report! Marking as a duplicate of https://github.com/dart-lang/sdk/issues/37058.

**Closed by devoncarew** 2019-06-09 22:07 UTC
