### ISSUE TITLE
The setter 'previous=' was called on null

### ISSUE THREAD

**Issue by GaoJiHu** [dart-lang/sdk#39632] opened 2019-12-04 07:43 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.4.0`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
NoSuchMethodError: The setter 'previous=' was called on null.
Receiver: null
Tried calling: previous=Instance of 'SimpleToken'
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      SimpleToken.setNext (package:front_end/src/scanner/token.dart:599:11)
#2      scannerRecovery (package:front_end/src/fasta/scanner/recover.dart:205:16)
#3      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:103:14)
#4      scanString (package:front_end/src/fasta/scanner.dart:95:10)
#5      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:146:34)
#6      _File._parse (package:analyzer/src/services/available_declarations.dart:1652:25)
#7      _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#8      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#9      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:514:18)
#10     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#12     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/

**Comment by srawlins** [comment] 2019-12-13 05:50
Recently reported at #38447; user reports that the problem may be fixed by upgrading Flutter, so that the Dart version is at 2.5.0. Please re-open if you encounter this crash on Dart 2.5.0 or later.

**Comment by srawlins** [comment] 2019-12-13 05:50
Duplicate of #38447

**Closed by srawlins** 2019-12-13 05:50 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
