### ISSUE TITLE
Enum factory constructor is omitted from code suggestions

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#51844] opened 2023-03-24 14:52 UTC
When using enums which have a factory constructor, the factory constructor does not show up in the code suggestions.

Methods and fields on the enum values are suggested correctly.
Switching out the enum for a class makes the factory constructor show up in the suggestions.

### Steps to reproduce

1. Given the following code sample
```
enum Foo {
  bar;

  factory Foo.fromValue(int value) {
    return bar;
  }
}

void main() {
    // final Foo foo = Foo.
}
```
2. In the main function type `final Foo foo = Foo.`
3. The factory constructor should show up as a suggestion after the dot, but it is not.

https://user-images.githubusercontent.com/23480364/227558499-7c3535ad-aa55-4f79-b8b7-027a9e1b4b0b.mov

Dart SDK version: 3.0.0-218.1.beta (beta) (Mon Feb 13 13:02:03 2023 -0800) on "macos_x64"

**Comment by keertip** [comment] 2024-03-07 18:24
Duplicate of #55014

**Closed by keertip** 2024-03-07 18:24 UTC
Labels: area-analyzer, analyzer-completion, P3, analyzer-server, analyzer-completion-correctness
