### ISSUE TITLE
warning: The value of the 'flutter' field is expected to be a map. (flutter_field_not_map at [rituals] pubspec.yaml:18)

### ISSUE THREAD

**Issue by zarub2k** [dart-lang/sdk#32475] opened 2018-03-09 11:58 UTC
After the freshly created package, i am getting this warning once it is imported into IDEA

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-173.4548.28`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `IC-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1200`

**Comment by zoechi** [comment] 2018-03-09 18:34
Looks like there is some wrong indentation in `pubspec.yaml`
Can you please post the content?

**Comment by bwilkerson** [comment] 2018-03-14 13:57
@zarub2k

**Comment by dgrove** [comment] 2018-03-16 16:01
Closing - please file a new bug if there are reproduction steps.

**Closed by dgrove** 2018-03-16 16:01 UTC
