### ISSUE TITLE
@required doesn't catch that a constructor isn't being called at all

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30261] opened 2017-07-26 00:01 UTC
When you have a constructor with only named arguments, subclasses that don't have any constructors or don't call the constructor explicitly are defined to implicitly call the constructor with no arguments. However, `@required` isn't catching those cases.

```dart
class A { A({ @required this.foo }); final int foo; }
class B extends A { } // no error here
```

**Comment by srawlins** [comment] 2020-06-20 17:56
Thanks for reporting this issue. This was previously reported at https://github.com/dart-lang/sdk/issues/30117; please follow along there.

**Comment by srawlins** [comment] 2020-06-20 17:57
Duplicate of #30117

**Closed by srawlins** 2020-06-20 17:57 UTC
Labels: P2, analyzer-hint, area-analyzer, type-bug
