### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by WayneSimon** [dart-lang/sdk#34342] opened 2018-09-01 03:20 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4129.33`
- `2.0.0`
- `IU-182.4129.33, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Wayne\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.0.0, server version 1.20.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\Programmer\codes\Dart\MyDart], excluded: [D:\Programmer\codes\Dart\MyDart\.idea, D:\Programmer\codes\Dart\MyDart\.dart_tool, D:\Programmer\codes\Dart\MyDart\.pub, D:\Programmer\codes\Dart\MyDart\build, D:\Programmer\codes\Dart\MyDart\out]}, clientRequestTime: 1535764955887}
NoSuchMethodError: The method 'removeFile' was called on null.
Receiver: null
Tried calling: removeFile("D:\\Programmer\\codes\\Dart\\MyDart\\bin\\main.dart___jb_tmp___")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      ServerContextManagerCallbacks.applyFileRemoved (package:analysis_server/src/analysis_server.dart:1401:12)
#2      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:1447:19)
#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1334:5)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#10     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)

**Comment by scheglov** [comment] 2018-09-04 19:31
Duplicate of https://github.com/dart-lang/sdk/issues/33600 (which I don't understand how to fix)

**Closed by scheglov** 2018-09-04 19:31 UTC
Labels: analyzer-server, analyzer-untriaged, area-analyzer, type-bug
