### ISSUE TITLE
Dart does not throw error when type parameter is a supertype of its upper bound.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33421] opened 2018-06-12 05:54 UTC
* Dart SDK Version: 2.0.0-dev.60.0
* OS: Windows 10

The following source code example tries to create an object of the class where type parameter is a supertype of the class upper bound:
``` dart
class C<X extends X1, X1 extends X> {}
main() {
    C c = new C();
    print("I am OK!");
}
```
When run in --preview-dart-2 mode, dartanalyzer reports expected compile error:
```
D:\DART\sdk\tests\co19\src\LanguageFeatures\Instantiate-to-bound>dartanalyzer --preview-dart-2 test.dart
Analyzing test.dart...
  error - 'X' can't be a supertype of its upper bound at test.dart:1:9 - type_parameter_supertype_of_its_bound
  error - 'X1' can't be a supertype of its upper bound at test.dart:1:23 - type_parameter_supertype_of_its_bound
  hint - The value of the local variable 'c' isn't used at test.dart:3:7 - unused_local_variable
2 errors and 1 hint found.

D:\DART\sdk\tests\co19\src\LanguageFeatures\Instantiate-to-bound>
```
However, if I run the same with dart - no errors appear:
```
D:\DART\sdk\tests\co19\src\LanguageFeatures\Instantiate-to-bound>dart --preview-dart-2 test.dart
I am OK!

D:\DART\sdk\tests\co19\src\LanguageFeatures\Instantiate-to-bound>
```
I believe this is a bug and either dart should throw exception here or dartanalyzer should not raise compile error,

**Comment by askeksa-google** [comment] 2018-08-14 09:15
Duplicate of https://github.com/dart-lang/sdk/issues/32989

**Closed by askeksa-google** 2018-08-14 09:15 UTC
Labels: area-front-end, type-bug
