### ISSUE TITLE
Sending an arbitrary type literal across isolate group boundaries crashes VM

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#50243] opened 2022-10-18 12:08 UTC
```dart
// main.dart

import 'dart:isolate';

class Foo {
  String message = '';
}

void main() {
  Isolate.spawnUri(Uri.parse('isolate.dart'), ['a'], [<Foo>[]]);
}
```

```dart
// isolate.dart

void main(List<String> args) {
  print(args);
}
```

```dart
$ dart bin/main.dart
../../runtime/vm/message_snapshot.cc: 579: error: Not found: file:///Users/vegorov/src/temp/test-app/bin/main.dart Foo

version=2.19.0-287.0.dev (dev) (Thu Oct 6 16:17:13 2022 -0700) on "macos_arm64"
pid=60322, thread=19971, isolate_group=main(0x127011200), isolate=main(0x127112200)
os=macos, arch=arm64, comp=no, sim=no
isolate_instructions=1045842a0, vm_instructions=1045842a0
  pc 0x000000010478e9b0 fp 0x000000016c27a560 dart::Profiler::DumpStackTrace(void*)+0x68
  pc 0x0000000104584468 fp 0x000000016c27a580 dart::Assert::Fail(char const*, ...) const+0x28
  pc 0x00000001046f8bb4 fp 0x000000016c27a600 dart::ReadApiMessage(dart::Zone*, dart::Message*)+0x7b84
  pc 0x00000001046f00a4 fp 0x000000016c27a680 dart::MessageDeserializer::Deserialize()+0x244
  pc 0x00000001046f0fbc fp 0x000000016c27a7f0 dart::ReadMessage(dart::Thread*, dart::Message*)+0x148
  pc 0x000000010464ea34 fp 0x000000016c27a820 dart::IsolateSpawnState::BuildMessage(dart::Thread*)+0x30
  pc 0x0000000104651300 fp 0x000000016c27a8b0 dart::BootstrapNatives::DN_TransferableTypedData_materialize(dart::Thread*, dart::Zone*, dart::NativeArguments*)+0xbc4
  pc 0x0000000104650fcc fp 0x000000016c27ae10 dart::BootstrapNatives::DN_TransferableTypedData_materialize(dart::Thread*, dart::Zone*, dart::NativeArguments*)+0x890
  pc 0x0000000104650c44 fp 0x000000016c27ae70 dart::BootstrapNatives::DN_TransferableTypedData_materialize(dart::Thread*, dart::Zone*, dart::NativeArguments*)+0x508
  pc 0x0000000104812ccc fp 0x000000016c27af30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14c
  pc 0x00000001048130ac fp 0x000000016c27af60 dart::ThreadPool::Worker::Main(unsigned long)+0x78
  pc 0x000000010478b04c fp 0x000000016c27afc0 dart::OSThread::GetMaxStackSize()+0xac
  pc 0x0000000194cb026c fp 0x000000016c27afe0 _pthread_start+0x94
-- End of DumpStackTrace
fish: Job 1, 'dart bin/main.dart' terminated by signal SIGABRT (Abort)
```

`MessageSerializer::Trace` rejects arbitrary instances but does not reject arbitrary types which can also refer to arbitrary instances.

/cc @aam @rmacnak-google @mkustermann

**Comment by rmacnak-google** [comment] 2022-10-18 22:09
https://dart-review.googlesource.com/c/sdk/+/264725, though there does seem to be a fair amount of existing code running afoul of this rule via list type arguments.

**Comment by mraleph** [comment] 2022-10-20 08:49
We also need to normalise TAVs when we send types through the port, because prefix sharing optimisation might cause message to contain non-sendable but actually unused types in the TAV. Here is an example: 

```dart
import 'dart:isolate';

class Foo {
  String message = '';
}

void main() async {
  final receivePort = ReceivePort();
  receivePort.listen((message) {
    print(message.runtimeType);
    print(message);
  });

  final message = <String, Foo>{'a': Foo(), 'b': Foo()}.keys.toList();
  final isolate = await Isolate.spawnUri(Uri.parse('isolate.dart.aot'), ['a'],
      message);
}
```

Runtime type of the `message` is `_GrowableList<String>`, but actual TAV is `[String, Foo]` due to prefix sharing.

**Comment by blaugold** [comment] 2022-10-28 20:16
This issue might be the root cause of #49281.

**Comment by a-siva** [comment] 2022-11-04 21:54
https://dart-review.googlesource.com/c/sdk/+/264725 has landed.
// @rmacnak-google can this be closed ?

**Closed** 2022-11-07 17:56 UTC
Labels: area-vm, P2, type-bug, crash, vm-triaged
