### ISSUE TITLE
service/get_vm_timeline_rpc_test flaky timeout on dartk-vm release_ia32 

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#35022] opened 2018-11-01 20:59 UTC
FAILED: dartk-vm release_ia32 service/get_vm_timeline_rpc_test
Expected: Pass
Actual: Timeout

--- Command "vm" (took 01:00.000094s):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --complete_timeline --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/get_vm_timeline_rpc_test.dart

exit code:
0

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseIA32/dart -DDART_SERVICE_USE_AUTH=false --profiler --complete_timeline --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages --enable-vm-service:0 /b/s/w/ir/cache/builder/sdk/runtime/observatory/tests/service/get_vm_timeline_rpc_test.dart
>testee>out> Observatory listening on http://127.0.0.1:36789/
** Signaled to run test queries on http://127.0.0.1:36789/
>testee>out> 
Loading VM...
Done loading VM
Running get_vm_timeline_rpc_test.dart [1/1]
All service tests completed successfully.
** Killing script
** Process exited

--- Re-run this test:
python tools/test.py -m release -a ia32 -n dartk-optcounter-linux-release-ia32 service/get_vm_timeline_rpc_test

**Comment by sjindel-google** [comment] 2018-11-08 16:12
I can't see this failure on LUCI as far back as Oct. 10 (https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-linux-release-ia32?limit=1000). I also can't reproduce it locally. Can you provide a link to the buildbot where it timed out?

**Comment by sjindel-google** [comment] 2018-11-08 16:18
I see, it was on the `optcounter` bot.

**Comment by sjindel-google** [comment] 2018-11-08 19:12
I'm not seeing the same output as you posted though in the logs above. Was there a different Timeout that you found?

**Comment by sjindel-google** [comment] 2018-11-08 19:15
Here is the per-thread stacktrace:

```
diagnostics:
Process list including children: [21006, 21140]
Trying to capture stack trace for pid 21006
PID 21006 - process
TID 21006:
#0  0xf77a8cd9 __kernel_vsyscall
#1  0xf7779d0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0126d958 Dart_RunLoop
#5  0x00dcc987 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#6  0x00dcd47f dart::bin::main(int, char**)
#7  0x00dcdd64 main
#8  0xf7482af3 __libc_start_main
#9  0x00dcc021 _start
TID 21007:
#0  0xf77a8cd9 __kernel_vsyscall
#1  0xf7557ee6 epoll_wait
#2  0x00dd4a71 dart::bin::EventHandlerImplementation::Poll(unsigned int)
#3  0x00df5204 dart::bin::ThreadStart(void*)
#4  0xf7775f72 start_thread
#5  0xf755743e __clone
TID 21010:
#0  0xf77a8cd9 __kernel_vsyscall
#1  0xf7779d0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0123a608 dart::BackgroundCompiler::Run()
#5  0x0123ab77 dart::BackgroundCompilerTask::Run()
#6  0x0111e8da dart::ThreadPool::Worker::Loop()
#7  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#8  0x0108c0d3 dart::ThreadStart(void*)
#9  0xf7775f72 start_thread
#10 0xf755743e __clone
TID 21011:
#0  0xf77a8cd9 __kernel_vsyscall
#1  0xf7779d0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0123a608 dart::BackgroundCompiler::Run()
#5  0x0123ab77 dart::BackgroundCompilerTask::Run()
#6  0x0111e8da dart::ThreadPool::Worker::Loop()
#7  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#8  0x0108c0d3 dart::ThreadStart(void*)
#9  0xf7775f72 start_thread
#10 0xf755743e __clone
TID 21012:
#0  0xf77a8cd9 __kernel_vsyscall
#1  0xf7779d0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0123a608 dart::BackgroundCompiler::Run()
#5  0x0123ab77 dart::BackgroundCompilerTask::Run()
#6  0x0111e8da dart::ThreadPool::Worker::Loop()
#7  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#8  0x0108c0d3 dart::ThreadStart(void*)
#9  0xf7775f72 start_thread
#10 0xf755743e __clone
TID 21141:
#0  0xf77a8cd9 __kernel_vsyscall
#1  0xf777dc07 wait
#2  0x00ddc128 dart::bin::ExitCodeHandler::ExitCodeHandlerEntry(unsigned int)
#3  0x00df5204 dart::bin::ThreadStart(void*)
#4  0xf7775f72 start_thread
#5  0xf755743e __clone
TID 21352:
#0  0xf77a8cd9 __kernel_vsyscall
#1  0xf7779d0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x01252268 dart::GCMarker::MarkObjects(dart::PageSpace*, bool)
#5  0x01256b2c dart::PageSpace::CollectGarbageAtSafepoint(bool, bool, long long, long long)
#6  0x01256850 dart::PageSpace::CollectGarbage(bool, bool)
#7  0x0124e749 dart::Heap::CollectOldSpaceGarbage(dart::Thread*, dart::Heap::GCType, dart::Heap::GCReason)
#8  0x0124f127 dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::GCReason)
#9  0x0124da4e dart::Heap::AllocateNew(int)
#10 0x01001dfb dart::Object::Allocate(int, int, dart::Heap::Space)
#11 0x0100526d dart::Array::New(int, dart::Heap::Space)
#12 0x010d82b6 dart::DRT_AllocateArray(dart::NativeArguments)
#13 0xf73005af
TID 21354:
#0  0x01252c00 dart::MarkingVisitorBase<true>::DrainMarkingStack()
#1  0x01252f7e dart::MarkTask::Run()
#2  0x0111e8da dart::ThreadPool::Worker::Loop()
#3  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#4  0x0108c0d3 dart::ThreadStart(void*)
#5  0xf7775f72 start_thread
#6  0xf755743e __clone
TID 21362:
#0  0x01252bf4 dart::MarkingVisitorBase<true>::DrainMarkingStack()
#1  0x01252f7e dart::MarkTask::Run()
#2  0x0111e8da dart::ThreadPool::Worker::Loop()
#3  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#4  0x0108c0d3 dart::ThreadStart(void*)
#5  0xf7775f72 start_thread
#6  0xf755743e __clone

eu-stack: dwfl_thread_getframes tid 21006 at 0xdcc020 in /b/s/w/ir/cache/builder/sdk/out/ReleaseIA32/dart: no matching address range
eu-stack: dwfl_thread_getframes tid 21352 at 0xf73005ae in <unknown>: No DWARF information found

Trying to capture stack trace for pid 21140
PID 21140 - process
TID 21140:
#0  0xf77accd9 __kernel_vsyscall
#1  0xf777dd0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0126d958 Dart_RunLoop
#5  0x00dcc987 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
#6  0x00dcd47f dart::bin::main(int, char**)
#7  0x00dcdd64 main
#8  0xf7486af3 __libc_start_main
#9  0x00dcc021 _start
TID 21142:
#0  0xf77accd9 __kernel_vsyscall
#1  0xf755bee6 epoll_wait
#2  0x00dd4a71 dart::bin::EventHandlerImplementation::Poll(unsigned int)
#3  0x00df5204 dart::bin::ThreadStart(void*)
#4  0xf7779f72 start_thread
#5  0xf755b43e __clone
TID 21143:
#0  0xf77accd9 __kernel_vsyscall
#1  0xf777dd0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0111d9fa dart::ThreadInterrupter::ThreadMain(unsigned int)
#4  0x0108c0d3 dart::ThreadStart(void*)
#5  0xf7779f72 start_thread
#6  0xf755b43e __clone
TID 21144:
#0  0xf77accd9 __kernel_vsyscall
#1  0xf777dd0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0123a608 dart::BackgroundCompiler::Run()
#5  0x0123ab77 dart::BackgroundCompilerTask::Run()
#6  0x0111e8da dart::ThreadPool::Worker::Loop()
#7  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#8  0x0108c0d3 dart::ThreadStart(void*)
#9  0xf7779f72 start_thread
#10 0xf755b43e __clone
TID 21146:
#0  0xf77accd9 __kernel_vsyscall
#1  0xf777dd0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0123a608 dart::BackgroundCompiler::Run()
#5  0x0123ab77 dart::BackgroundCompilerTask::Run()
#6  0x0111e8da dart::ThreadPool::Worker::Loop()
#7  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#8  0x0108c0d3 dart::ThreadStart(void*)
#9  0xf7779f72 start_thread
#10 0xf755b43e __clone
TID 21149:
#0  0xf77accd9 __kernel_vsyscall
#1  0xf777dd0b pthread_cond_wait@@GLIBC_2.3.2
#2  0x0108c775 dart::Monitor::WaitMicros(long long)
#3  0x0108c6c7 dart::Monitor::Wait(long long)
#4  0x0123a608 dart::BackgroundCompiler::Run()
#5  0x0123ab77 dart::BackgroundCompilerTask::Run()
#6  0x0111e8da dart::ThreadPool::Worker::Loop()
#7  0x0111e79e dart::ThreadPool::Worker::Main(unsigned int)
#8  0x0108c0d3 dart::ThreadStart(void*)
#9  0xf7779f72 start_thread
#10 0xf755b43e __clone

eu-stack: dwfl_thread_getframes tid 21140 at 0xdcc020 in /b/s/w/ir/cache/builder/sdk/out/ReleaseIA32/dart: no matching address range
```

@rmacnak-google Does this look potentially like a deadlock in concurrent marking?

**Comment by a-siva** [comment] 2021-04-22 16:44
Seems like the timeout was more because of slowness rather than a deadlock so closing this issue.

**Closed by a-siva** 2021-04-22 16:44 UTC
Labels: area-vm, gardening
