### ISSUE TITLE
fasta crash with typedef with generic function types

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30694] opened 2017-09-13 23:10 UTC
Repro by calling `fasta compile` in the program 

```dart
typedef MyFunction<T> = R Function<R>(T);
MyFunction<int> f;
```

fasta crashes when trying to apply the substitution of `<T>` for `<int>` in the declaration of `f`:
```
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of '_InnerTypeSubstitutor')
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      _TypeSubstitutor.visit (package:kernel/type_algebra.dart:370:41)
#3      _InnerTypeSubstitutor.freshTypeParameter (package:kernel/type_algebra.dart:324:19)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#5      ListIterable.toList (dart:_internal/iterable.dart:218)
#6      _TypeSubstitutor.freshTypeParameters (package:kernel/type_algebra.dart:396:47)
#7      _TypeSubstitutor.visitFunctionType (package:kernel/type_algebra.dart:417:32)
#8      FunctionType.accept (package:kernel/ast.dart:4439:34)
#9      _TypeSubstitutor.visit (package:kernel/type_algebra.dart:370:41)
#10     Substitution.substituteType (package:kernel/type_algebra.dart:235:53)
#11     substitute (package:kernel/type_algebra.dart:19:45)
#12     KernelFunctionTypeAliasBuilder.buildTypesWithBuiltArguments (package:front_end/src/fasta/kernel/kernel_function_type_alias_builder.dart:92:12)
#13     KernelFunctionTypeAliasBuilder.buildType (package:front_end/src/fasta/kernel/kernel_function_type_alias_builder.dart:109:12)
#14     KernelNamedTypeBuilder.build (package:front_end/src/fasta/kernel/kernel_named_type_builder.dart:61:20)
#15     KernelFieldBuilder.build (package:front_end/src/fasta/kernel/kernel_field_builder.dart:69:25)
#16     KernelLibraryBuilder.buildBuilder (package:front_end/src/fasta/kernel/kernel_library_builder.dart:740:33)
#17     SourceLibraryBuilder.build.<anonymous closure> (package:front_end/src/fasta/source/source_library_builder.dart:388:9)
#18     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#19     Scope.forEach (package:front_end/src/fasta/scope.dart:243:11)
#20     LibraryBuilder.forEach (package:front_end/src/fasta/builder/library_builder.dart:190:11)
#21     SourceLibraryBuilder.build (package:front_end/src/fasta/source/source_library_builder.dart:386:5)
#22     KernelLibraryBuilder.build (package:front_end/src/fasta/kernel/kernel_library_builder.dart:759:16)
#23     SourceLoader.buildProgram.<anonymous closure> (package:front_end/src/fasta/source/source_loader.dart:456:31)
#24     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#25     SourceLoader.buildProgram (package:front_end/src/fasta/source/source_loader.dart:454:14)
#26     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:244:14)
```

**Comment by jensjoha** [comment] 2018-01-08 08:55
I cannot reproduce. Can we close this issue?

**Comment by peter-ahe-google** [comment] 2018-01-08 10:41
At a3f6eefdbf175254d9df98884e3e070b201a280e, I get this stack trace:

```
Unhandled exception:
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of 'BinaryPrinter')
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217:10)
#2      BinaryPrinter.visitTypeParameter (package:kernel/binary/ast_to_binary.dart:1542:5)
#3      TypeParameter.accept (package:kernel/ast.dart:5163:30)
#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217:10)
#5      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:209:7)
#6      BinaryPrinter.visitFunctionType (package:kernel/binary/ast_to_binary.dart:1504:7)
#7      FunctionType.accept (package:kernel/ast.dart:4878:34)
#8      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217:10)
#9      BinaryPrinter.visitField (package:kernel/binary/ast_to_binary.dart:774:5)
#10     Field.accept (package:kernel/ast.dart:1189:32)
#11     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217:10)
#12     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:209:7)
#13     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:570:5)
#14     Library.accept (package:kernel/ast.dart:409:30)
#15     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217:10)
#16     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#17     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:407:23)
#18     BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:288:5)
#19     writeProgramToFile (package:front_end/src/fasta/kernel/utils.dart:42:13)
<asynchronous suspension>
#20     CompileTask.compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:164:11)
<asynchronous suspension>
#21     compile.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:98:25)
<asynchronous suspension>
#22     withGlobalOptions.<anonymous closure> (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:364:13)
#23     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96:35)
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96:14)
#28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:107:41)
#29     withGlobalOptions (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/command_line.dart:357:26)
#30     compile (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:91:18)
<asynchronous suspension>
#31     compileEntryPoint (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/entry_points.dart:49:11)
<asynchronous suspension>
#32     main (file:///Users/ahe/w/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

This is from Dec 21, let me check if I can repro at a newer version.

**Comment by jensjoha** [comment] 2018-01-08 11:20
The problem seems to have vanished with de2ce48e1787cea70c1de60d5f2b8c71174749dc.

**Closed** 2018-01-08 11:24 UTC
Labels: area-front-end, front-end-fasta

**Comment by peter-ahe-google** [comment] 2018-01-08 11:39
@askeksa-google fixed a similar issue between Dec 21 and today. So it's reasonable to assume that it is fixed.
