### ISSUE TITLE
Remove duplicate errors when analyzing everything within a directory

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#28779] opened 2017-02-15 16:30 UTC
I should be able to just analyze a whole package with the CLI (just like in IntelliJ) without having to pass in every dart file to the CLI.

**Comment by bwilkerson** [comment] 2017-02-15 16:39
The original plan was to allow the user to specify a directory (in addition to a file) on the command line. Have you tried this? A recent test indicates that this mostly works. In addition to errors in files in the specified directory it printed hints from files in the package that were not in the directory I specified but were imported into several of the files in the directory.

**Comment by kevmoo** [comment] 2017-02-15 16:45
Running it on a directory `dartanalyzer .` *does* work, but with a LOT of duplicates.

```console
> dartanalyzer .
Analyzing [.]...
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 21, col 16)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 23, col 31)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 249, col 21)
[hint] 'OnHijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 265, col 9)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 275, col 12)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 21, col 16)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 23, col 31)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 249, col 21)
[hint] 'OnHijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 265, col 9)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 275, col 12)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 21, col 16)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 23, col 31)
[hint] 'HijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 249, col 21)
[hint] 'OnHijackCallback' is deprecated and shouldn't be used. (/Users/kevmoo/source/github/shelf/lib/src/request.dart, line 265, col 9)
...
```

**Comment by bwilkerson** [comment] 2017-02-16 18:21
There is no "spec" for how dartanalyzer should work, so I have a question. If a user analyzes a single library, is it reasonable for the default behavior to be to report errors in that library (the specified file and any part files that are referenced) without reporting errors in other libraries? There is a flag to enable reporting errors in other packages, which would then report all errors in all files reachable from the specified library via import and export directives.

If the answer is "yes", then I have a fix for this that I can send out for review.

**Comment by bwilkerson** [comment] 2017-02-16 19:55
Sorry, I don't have a fix. Changing the behavior that way causes 180 test failures.

**Comment by kevmoo** [comment] 2017-02-16 19:56
Could the tests be changed? Are the failures bad?

**Comment by bwilkerson** [comment] 2017-02-16 20:01
The tests are expecting errors to be reported that are no longer being reported because analyzer is (appropriately, I think) associating the errors with a different file. I don't see any good way to change the tests.

**Comment by devoncarew** [comment] 2017-04-10 15:32
dupe of https://github.com/dart-lang/sdk/issues/25697

**Closed by devoncarew** 2017-04-10 15:32 UTC
Labels: analyzer-command, area-analyzer, P2 medium, S1 high, Type: enhancement
