### ISSUE TITLE
Exception while parsing with unmatched parentheses

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30363] opened 2017-08-08 15:04 UTC
The following exception was captured. The original code is not available, but it appears that the code had an unmatched parenthesis. This is a non-fatal exception for server.

(Note: the stack frame labeled '#1' is now on line 515.)
```
'(' isn't closed.
#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:76)
#1      Parser.isFunctionExpression (package:analyzer/src/generated/parser.dart:518)
#2      Parser.isFunctionDeclaration (package:analyzer/src/generated/parser.dart:474)
#3      Parser.parseNonLabeledStatement (package:analyzer/src/generated/parser.dart:4263)
#4      Parser.parseStatement2 (package:analyzer/src/generated/parser.dart:4883)
#5      Parser.parseBlock (package:analyzer/src/generated/parser.dart:1000)
#6      Parser.parseFunctionBody (package:analyzer/src/generated/parser.dart:3277)
#7      Parser.parseFunctionDeclaration (package:analyzer/src/generated/parser.dart:3356)
#8      Parser.parseCompilationUnitMember (package:analyzer/src/generated/parser.dart:2200)
#9      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:2004)
#10     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:1896)
#11     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:617)
#12     FileState.parse.\u003canonymous closure\u003e (package:analyzer/src/dart/analysis/file_state.dart:391)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#14     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:390)
#15     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:441)
#16     FileTracker.verifyApiSignature.\u003canonymous closure\u003e (package:analyzer/src/dart/analysis/file_tracker.dart:220)
#17     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#18     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:216)
#19     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:289)
#20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:795)

asynchronous suspension

#21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1609)

asynchronous suspension

#22     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1552)
#23     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#24     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#25     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#26     Driver.start.\u003canonymous closure\u003e (package:analysis_server/src/server/driver.dart:434)
#27     _rootRun (dart:async/zone.dart:1120)
#28     _CustomZone.run (dart:async/zone.dart:1001)
#29     runZoned (dart:async/zone.dart:1467)
#30     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#31     Driver.start (package:analysis_server/src/server/driver.dart:433)
```

**Comment by bwilkerson** [comment] 2017-08-08 15:04
@danrubel Has this already been fixed?

**Comment by danrubel** [comment] 2017-08-08 15:18
Nope. Looking at it today/tomorrow.

**Comment by danrubel** [comment] 2017-10-25 19:52
Duplicate of https://github.com/dart-lang/sdk/issues/31098

**Closed by danrubel** 2017-10-25 19:52 UTC
Labels: area-analyzer, P2 medium, Type: bug
