### ISSUE TITLE
[analysis_server] "Your project contains issues that can be fixed automatically" notification is shown even when I click "don't show again"

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#57081] opened 2024-11-13 12:53 UTC
Every time I restart the IDE I get the "Your project contains issues that can be fixed automatically." notification shown even if I click the "Don't show again" button.
The ".prompts" folder is not updated since August 7th, so for some reason the state of this button is not saved on FS.

Dart SDK version: 3.5.4 (stable) (Wed Oct 16 16:18:51 2024 +0000) on "macos_x64"

@DanTup fyi.

**Comment by devoncarew** [comment] 2024-11-13 21:20
Thanks for the report! I think this issue might be with the vs-code plugin however (https://github.com/Dart-Code/Dart-Code).

**Comment by DanTup** [comment] 2024-11-13 21:30
This prompt actually [comes from the analysis server](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/user_prompts/dart_fix_prompt_manager.dart) (via the `showMessageRequest` API), since it does the check for whether there are any fixable issues.

It's supposed to persist a file to suppress the prompts when you click "Don't show again" though, sounds like this might not be working correctly.

**Comment by devoncarew** [comment] 2024-11-13 21:43
> This prompt actually comes from the analysis server (via the `showMessageRequest` API) ..

Ah, gotcha.

**Comment by DanTup** [comment] 2024-11-14 14:22
@incendial I can reproduce this on stable, but not on bleeding-edge. I recalled looking at it recently, and it turns out it that was after the branch for Dart 2.4. So it has been fixed and will be included in the next main (non-hotfix) release:

- https://github.com/Dart-Code/Dart-Code/issues/5202
- https://github.com/dart-lang/sdk/commit/c18b84d6d22a5537460f8e788ca06609a7c8b9f4

**Closed by DanTup** 2024-11-14 14:22 UTC
Labels: area-analyzer, P2, type-bug

**Comment by HaloWang** [comment] 2024-12-05 16:32
Hi @DanTup , I can reproduce it every on my macOS. Can I ask you for some help? No use for clicking "Don't show again".

```bash
flutter doctor --verbose
```

```log
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.2 24C5089c darwin-arm64, locale en-CN)
    • Flutter version 3.24.5 on channel stable at /Users/wangce/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wangce/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/wangce/Library/Android/sdk
    • Java binary at: /Users/wangce/Library/Java/JavaVirtualMachines/corretto-18.0.2/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-18.0.2.9.1 (build 18.0.2+9-FR)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1

[✓] Connected device (5 available)
    • Halo's iPad (mobile)            • 00008103-001911122160801E • ios            • iOS 18.1.1 22B91
    • Ce’s iPhone (mobile)            • 00008140-000641E02EDB001C • ios            • iOS 18.1.1 22B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.2 24C5089c darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.2 24C5089c darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.108

[✓] Network resources
    • All expected network resources are available.
```

**Comment by DanTup** [comment] 2024-12-05 16:37
@HaloWang see the comment above yours - this issue is fixed but the fix unfortunately has not shipped in a stable release yet. It'll be included in the next Dart/Flutter SDK releases.
