### ISSUE TITLE
analysis server crashes – 2.6.0-dev.1.0

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#38579] opened 2019-09-26 02:35 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6817.14`
- `2.6.0-dev.1.0`
- `IU-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.6.0-dev.1.0, server version 1.27.3, error: Analysis failed: /Users/kevmoo/github/json_serializable/json_serializable/test/config_test.dart context: exception_20190925_193448_150
Bad state: The type parameter K (in dart:core;dart:core/map.dart;Map;K) is out of scope.
#0      _createLinkedType (package:analyzer/src/summary/link.dart:217:7)
#1      _storeTypeArguments (package:analyzer/src/summary/link.dart:408:31)
#2      _createLinkedType (package:analyzer/src/summary/link.dart:199:5)
#3      CompilationUnitElementInBuildUnit._storeLinkedType (package:analyzer/src/summary/link.dart:1687:31)
#4      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5327:25)
#5      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1646:16)
#6      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3986:12)
#7      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3686:15)
#8      LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3626:7)
#9      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2231:13)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2197:24)
#11     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2250:18)
#12     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3659:42)
#13     Linker.link (package:analyzer/src/summary/link.dart:4191:35)
#14     _relink (package:analyzer/src/summary/link.dart:313:74)
#15     link (package:analyzer/src/summary/link.dart:127:3)
#16     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#18     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#19     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#20     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#21     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1246:30)
#22     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#23     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#25     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#26     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#27     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#28     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#29     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#30     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:576:21)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:693:12)
#36     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:574:7)
#37     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:475:9)
#38     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#39     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:470:43)
#40     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#41     new Future.sync (dart:async/future.dart:224:31)
#42     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#48     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#49     Driver.start (package:analysis_server/src/server/driver.dart:470:21)
#50     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#51     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#52     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#53     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/c0/jv6k5x0j57vcwkdx6rcjgj3w0071_k/T/report.txt.

**Comment by keertip** [comment] 2019-11-11 17:24
Duplicate of #36506

**Closed by keertip** 2019-11-11 17:24 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
