### ISSUE TITLE
Implement null safe numbers in the CFE

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42628] opened 2020-07-08 17:34 UTC
This is the CFE implementation issue for https://github.com/dart-lang/language/issues/1078.  See that issue for details.

**Comment by stereotype441** [comment] 2020-07-08 17:35
FYI @johnniwinther.  I've begun prototyping these rules in the analyzer and I'm happy to assist with the CFE implementation if needed.

**Comment by johnniwinther** [comment] 2020-07-13 09:23
Duplicate of #42577

**Closed by johnniwinther** 2020-07-13 09:23 UTC
Labels: NNBD, area-front-end
