### ISSUE TITLE
Dart Analysis error

### ISSUE THREAD

**Issue by sypaguilar** [dart-lang/sdk#41720] opened 2020-04-30 08:24 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.8.0-edge.eea97179386a9ced7d68452cea158345f4019baa`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.eea97179386a9ced7d68452cea158345f4019baa, server version 1.27.4, FATAL error: UnimplementedError: name is an instance of _OperatorName in endClassConstructor
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

For additional log information, please append the contents of
file://C:\Users\sophiaya\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2020-06-12 22:58
Thanks for reporting this issue! This was also caught by our fuzz tester. Please follow along at #39032.

**Comment by srawlins** [comment] 2020-06-12 22:58
Duplicate of #39032

**Closed by srawlins** 2020-06-12 22:58 UTC
Labels: analyzer-crash-report, area-analyzer
