### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by AleksanderKoko** [dart-lang/sdk#34963] opened 2018-10-29 11:12 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4505.22`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IU-182.4505.22, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/5l/z61f0_tn1w55n05_3z9v0qj80000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/<username>/Desktop/projects/<project>/lib/pages/main.dart
RangeError (index): Invalid value: Not in range 0..7, inclusive: 8
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#6      _ParameterElementImpl

**Comment by stereotype441** [comment] 2018-10-29 16:31
Duplicate of #34534

**Closed by stereotype441** 2018-10-29 16:31 UTC
Labels: area-analyzer
