### ISSUE TITLE
NoSuchMethodError.toString crashes in NNBD with --null_safety

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#40998] opened 2020-03-11 15:21 UTC
Repro program:

```
void main() {
  try {
    dynamic x;
    print(x.length);
  } catch (e) {
    print(e);
  }
}
```

Gives the following exception:

```
Unhandled exception:
type 'Null' is not a subtype of type 'String' of 'function result'
#0      NoSuchMethodError._existingMethodSignature (dart:core-patch/errors_patch.dart)
#1      NoSuchMethodError.toString (dart:core-patch/errors_patch.dart:340:9)
#2      print (dart:core/print.dart:9:24)
#3      main (file:///home/jakemac/matcher/bin/repro.dart:6:5)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

**Comment by crelier** [comment] 2020-03-13 23:20
Several bug fixes landed in the last couple of days. I am not sure which one fixed this issue, but I cannot reproduce it.
```
$ out/DebugX64NNBD/dart --null-safety --enable-experiment=non-nullable ~/bug.dart
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
```

Please, reopen if you still experience it.

**Closed by crelier** 2020-03-13 23:20 UTC
Labels: NNBD, area-vm
