### ISSUE TITLE
Improve token position for local variables

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/sdk#25570] opened 2016-01-25 14:44 UTC
I noticed that BoundVariable object has 2 non-documented private fields: _tokenPos and _endTokenPos. _tokenPos is pretty much what I need, except that:

- it is not omitted for 'this' where such thing as 'source location' doesn't make sense to me

- for local var declaration var foo = "bar"; it points to the position of the semicolon, whereas I need a pointer to the variable name

**Comment by mhausner** [comment] 2016-01-25 18:31
The reason why the token position points to the semicolon is because the variable isn't defined until after the initializer expression. Otherwise, the initializer expression could recursively refer to the variable name. Essentially, the token position of a local variable defines the beginning of the range in which it is visible. _endTokenPos is the end of the range.

**Comment by alexander-doroshko** [comment] 2016-01-26 07:59
@mhausner Thanks for the clarification regarding private `_tokenPos` and `_endTokenPos` fields! If it's by design then I guess this issue can be closed without a fix.

What I really need is 'Jump To Source' functionality for local variables and parameters while VM is suspended. This request is tracked as #25569.

**Comment by mhausner** [comment] 2016-06-16 23:30
Closing this. Nothing to fix.

**Closed by mhausner** 2016-06-16 23:30 UTC
Labels: area-observatory, area-vm, Resolution: works as intended
