### ISSUE TITLE
NPE from FixProcessor._addFix_changeArgumentName.getNamedParameterNames (SDK version 2.2.1-edge)

### ISSUE THREAD

**Issue by NguyenSen** [dart-lang/sdk#36751] opened 2019-04-25 15:09 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.2.1-edge.7418238239f885ba92093c44a1768f8ec93b121f`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1440x900`

# Exception

Please append the contents of:
file://C:\Users\Sennd\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.2.1-edge.7418238239f885ba92093c44a1768f8ec93b121f, server version 1.25.0, FATAL error: Failed to handle request: {id: 140, method: edit.getFixes, params: {file: D:\git\OrderPlus\Phase1\src\app\order_plus\lib\main.dart, offset: 943}, clientRequestTime: 1556204952655}
NoSuchMethodError: The getter 'namedNames' was called on null.
Receiver: null
Tried calling: namedNames
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      FixProcessor._addFix_changeArgumentName.getNamedParameterNames (package:analysis_server/src/services/correction/fix_internal.dart:1075:27)
#2      FixProcessor._addFix_changeArgumentName (package:analysis_server/src/services/correction/fix_internal.dart:1091:48)
<asynchronous suspension>
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:476:13)
<asynchronous suspension>
#4      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#5      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:589:46)
<asynchronous suspension>
#6      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:264:32)
<asynchronous suspension>
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:367:9)

**Comment by devoncarew** [comment] 2019-04-30 15:01
closing as a dupe of https://github.com/dart-lang/sdk/issues/36729

**Closed by devoncarew** 2019-04-30 15:01 UTC
Labels: analyzer-crash-report, area-analyzer
