### ISSUE TITLE
dart pub publish --dry-run false positive with null-safe SDK constraints

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/sdk#44711] opened 2021-01-19 13:55 UTC
Consider the following `pubspec.yaml`:

```yaml
name: foo
description: The web implementation of cloud_firestore
version: 0.3.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  firebase_core: ^0.7.0-nullsafety.0
```

Executing `dart pub publish --dry-run` will warn with:

```
* Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 2.12.0-0, consider publishing the package as a pre-release instead.
  See https://dart.dev/tools/pub/publishing#publishing-prereleases For more information on pre-releases.
* This package is opting into null-safety, but a dependency or file is not.
  
  package:firebase_core is not opted into null safety in its pubspec.yaml:
     ╷
  37 │   sdk: ">=2.1.0 <3.0.0"
     │        ^^^^^^^^^^^^^^^^
     ╵  
```

This doesn't make sense as `firebase_core: ^0.7.0-nullsafety.0` has a sdk version constraint of dart >= 2.12.x

My theory is that --dry-run picked up the SDK constraints of the non-null-safe version instead.

**Comment by devoncarew** [comment] 2021-01-19 16:28
cc @mit-mit @jonasfj - should this issue instead be moved to the pub issue tracker?

**Comment by jonasfj** [comment] 2021-01-19 17:04
Problem here is that `firebase_core` have been migrated out-of-order.

 * `0.7.0-nullsafety.0` is migrated to null-safety,
 * `0.7.0` is NOT migrated to null-safety,

However, `0.7.0 > 0.7.0-nullsafety.0` so, `0.7.0` is probably what you have installed, and what a user might get if they depend on your package when you have `^0.7.0-nullsafety.0`.

You could pin `firebase_core: 0.7.0-nullsafety.0`, but it's not ideal... Especially, not if someone else has a dependency like `firebase_core: >=0.6.0 <0.8.0`, because such a package is unlikely to be compatible with `0.7.0-nullsafety.0` (on the flip side you could argue that said author was supposed to know this).

The original issue here is that `0.7.0` has not migrated to null-safety, thus, `0.7.0-nullsafety.0` is migrated out-of-order.

I imagine it's just a mistake, `firebase_core` version `0.7.0-nullsafety.0` should probably have been published as `0.8.0-nullsafety.0` -- I've personally made the same mistake on `package:retry` :see_no_evil: 

Filed https://github.com/dart-lang/sdk/issues/44711 for the upstream issue.

------

For future reference, feel free to file `dart pub` related issues in https://github.com/dart-lang/pub, I'm going to close this as this is working as intended. It's correct that the fault isn't yours (but that of your dependency), but this is too complicated for the tool to automatically guess what has gone wrong (there could be many scenarios).

In either case, you should think hard about publishing because it's likely that your users will experience pain trying to use a null-safety ported version with a downstream dependency that isn't probably migrated.

**Closed by jonasfj** 2021-01-19 17:04 UTC
Labels: area-dart-cli, dart-cli-pub

**Comment by jonasfj** [comment] 2021-01-19 17:07
> My theory is that --dry-run picked up the SDK constraints of the non-null-safe version instead.

Yes, it's sometimes unfortunate that the solver isn't aware that null-safety packages always want null-safety migrated dependencies. But this constraint was not introduced which is why scenarios like this can happen.

However, people rarely migrate backwards, when out-of-order scenarios occur it's often a mistake OR it's a very complicated scenario that someone has spent time considering.

**Comment by mit-mit** [comment] 2021-01-19 19:46
> Filed #44711 for the upstream issue.

Upstream issue is: https://github.com/FirebaseExtended/flutterfire/issues/4728
