### ISSUE TITLE
Opening old project.

### ISSUE THREAD

**Issue by Andrious** [dart-lang/sdk#35727] opened 2019-01-22 17:06 UTC
Analyzer Feedback from IntelliJ

# Version information
[report1.txt](https://github.com/dart-lang/sdk/files/2783814/report1.txt)

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1280x720`

# Exception

Please append the contents of:
file://C:\Users\gtfpe\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Programs\Tools\Projects\Flutter\Challenge\flutter_ui_challenge_egg_timer\lib\main.dart context: exception_20190122_115704_831
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart

**Comment by stereotype441** [comment] 2019-01-23 17:58
Duplicate of #34555

**Closed by stereotype441** 2019-01-23 17:58 UTC
Labels: area-analyzer
