### ISSUE TITLE
UnmodifiableListView object, when set to a List object, does not throw an analysis error

### ISSUE THREAD

**Issue by maryx** [dart-lang/sdk#30519] opened 2017-08-22 22:53 UTC
List is not a subclass of UnmodifiableListView, so we shouldn't be able to set a variable defined with type UnmodifiableListView to a List. When we try to set an UnmodifiableListView to a List, the dart analyzer should throw an error or warning.
E.g. this code is currently allowed and builds fine:
```
import 'dart:collection';

List<String> _list;
UnmodifiableListView<String> get publicList => _list; // should throw error; currently doesn't
```

The above should instead be written as:
```
import 'dart:collection';

List<String> _list;
List<String> get publicList => new UnmodifiableListView<String>(_list);
```

**Comment by matanlurey** [comment] 2017-08-22 23:29
I believe this would be covered by `implicit-casts`:
https://www.dartlang.org/guides/language/analysis-options#specifying-strong-mode

Seems like a duplicate of https://github.com/dart-lang/sdk/issues/30392.

See also: https://github.com/dart-lang/sdk/issues/30397.

**Closed by matanlurey** 2017-08-22 23:29 UTC
Labels: Resolution: duplicate
