### ISSUE TITLE
dart2js crashes in 1.11.0 with "The null object does not have a method 'ensureResolved'."

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#23729] opened 2015-06-26 17:36 UTC
I upgraded to from 1.10.1 to 1.11.0
The error disappears after downgrading to 1.10.1
I tried several of my samples and all crash. If you want to try it - it's on https://github.com/MikeMitterer/dart-material-design-lite but not public at the moment. Seth Ladd has access... repeater2 is the actual branch, mdlx_dialog crashes for example or spa_repeat
 
OSX 10.9.5, DART SDK 1.11.0
With 1.11.0 dart2js crashes with the following stack trace:
```bash
[Error from Dart2JS on mdl_dialog_sample|web/main.dart]:
package:mdl/mdlapplication.dart: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on mdl_dialog_sample|web/main.dart threw error: The null object does not have a method 'ensureResolved'.

NoSuchMethodError: method not found: 'ensureResolved'
Receiver: null
Arguments: [Instance of 'Compiler']
dart:core                                                               Object.noSuchMethod
package:compiler_unsupported/src/js_backend/backend.dart 900            JavaScriptBackend.addInterceptors
package:compiler_unsupported/src/js_backend/backend.dart 1075           JavaScriptBackend.registerInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 268                       Enqueuer.processInstantiatedClass.<fn>.processClass
package:compiler_unsupported/src/enqueue.dart 271                       Enqueuer.processInstantiatedClass.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 249                       Enqueuer.processInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 129                       Enqueuer.registerInstantiatedType.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 124                       Enqueuer.registerInstantiatedType
package:compiler_unsupported/src/js_backend/backend.dart 1385           JavaScriptBackend.enqueueClass
package:compiler_unsupported/src/js_backend/backend.dart 910            JavaScriptBackend.addInterceptors
package:compiler_unsupported/src/js_backend/backend.dart 1074           JavaScriptBackend.registerInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 268                       Enqueuer.processInstantiatedClass.<fn>.processClass
package:compiler_unsupported/src/enqueue.dart 271                       Enqueuer.processInstantiatedClass.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 249                       Enqueuer.processInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 129                       Enqueuer.registerInstantiatedType.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 124                       Enqueuer.registerInstantiatedType
package:compiler_unsupported/src/js_backend/backend.dart 1385           JavaScriptBackend.enqueueClass
package:compiler_unsupported/src/js_backend/backend.dart 910            JavaScriptBackend.addInterceptors
package:compiler_unsupported/src/js_backend/backend.dart 1073           JavaScriptBackend.registerInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 268                       Enqueuer.processInstantiatedClass.<fn>.processClass
package:compiler_unsupported/src/enqueue.dart 271                       Enqueuer.processInstantiatedClass.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 249                       Enqueuer.processInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 129                       Enqueuer.registerInstantiatedType.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 124                       Enqueuer.registerInstantiatedType
package:compiler_unsupported/src/js_backend/backend.dart 1385           JavaScriptBackend.enqueueClass
package:compiler_unsupported/src/js_backend/backend.dart 910            JavaScriptBackend.addInterceptors
package:compiler_unsupported/src/js_backend/backend.dart 1071           JavaScriptBackend.registerInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 268                       Enqueuer.processInstantiatedClass.<fn>.processClass
package:compiler_unsupported/src/enqueue.dart 271                       Enqueuer.processInstantiatedClass.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 249                       Enqueuer.processInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 129                       Enqueuer.registerInstantiatedType.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 124                       Enqueuer.registerInstantiatedType
package:compiler_unsupported/src/resolution/registry.dart 476           ResolutionRegistry.registerInstantiatedType
package:compiler_unsupported/src/resolution/members.dart 2143           ResolverVisitor.visitLiteralList
package:compiler_unsupported/src/tree/nodes.dart 999                    LiteralList.accept
package:compiler_unsupported/src/resolution/resolution_common.dart 976  CommonResolverVisitor.visit
package:compiler_unsupported/src/resolution/members.dart 2394           ResolverVisitor.visitNamedArgument
package:compiler_unsupported/src/tree/nodes.dart 1655                   NamedArgument.accept
package:compiler_unsupported/src/resolution/resolution_common.dart 976  CommonResolverVisitor.visit
package:compiler_unsupported/src/resolution/members.dart 719            ResolverVisitor.resolveArguments
package:compiler_unsupported/src/resolution/members.dart 1933           ResolverVisitor.visitNewExpression
package:compiler_unsupported/src/tree/nodes.dart 526                    NewExpression.accept
package:compiler_unsupported/src/resolution/resolution_common.dart 930  ResolverTask.resolveMetadataAnnotation.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/resolution/resolution_common.dart 913  ResolverTask.resolveMetadataAnnotation.<fn>
package:compiler_unsupported/src/compiler.dart 907                      Compiler.withCurrentElement
package:compiler_unsupported/src/resolution/resolution_common.dart 913  ResolverTask.resolveMetadataAnnotation
package:compiler_unsupported/src/elements/modelx.dart 2833              MetadataAnnotationX.ensureResolved
package:compiler_unsupported/src/mirrors_used.dart 269                  MirrorUsageAnalyzer.mirrorsUsedOnLibraryTag
package:compiler_unsupported/src/mirrors_used.dart 211                  MirrorUsageAnalyzer.collectMirrorsUsedAnnotation.<fn>
package:compiler_unsupported/src/compiler.dart 907                      Compiler.withCurrentElement
package:compiler_unsupported/src/mirrors_used.dart 209                  MirrorUsageAnalyzer.collectMirrorsUsedAnnotation
package:compiler_unsupported/src/mirrors_used.dart 186                  MirrorUsageAnalyzer.run
package:compiler_unsupported/src/compiler.dart 2180                     CompilerTask.measure
package:compiler_unsupported/src/mirrors_used.dart 109                  MirrorUsageAnalyzerTask.analyzeUsage
package:compiler_unsupported/src/compiler.dart 1578                     Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 1510                     Compiler.runCompiler.<fn>
dart:isolate                                                            _RawReceivePortImpl._handleMessage

Build failed.
```

**Comment by sigmundch** [comment] 2015-06-26 19:33
Thanks for the bug report, it might be hard to debug without access to an example. Could you add me temporarily? or is it OK if I ask @sethladd to provide me with a copy?

Alternatively, if you can provide here a small example that produces the failure, that works too.

**Comment by MikeMitterer** [comment] 2015-06-26 20:52
Welcome :-) I've added you as contributor.

**Comment by sigmundch** [comment] 2015-06-26 20:53
Thanks!

**Comment by chalin** [comment] 2015-06-26 20:59
FYI, similar situation for me. I am getting a crash following an upgrade to 1.11.0 when compiling a ["non-null" version of the core lib](https://github.com/chalin/DEP-non-null/blob/master/doc/dep-non-null-AUTOGENERATED-DO-NOT-EDIT.md#ii32-dart-sdk-library).

Should I open a separate issue?

Here is an excerpt from the build log:
```shell
[Info from Dart2JS]:
Compiling observatory|web/index.html.polymer.bootstrap.dart...
[Error from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
file:///Users/chalin/git-nn/sdk/runtime/observatory/web/packages/$sdk/lib/core/core.dart: Could not find asset $sdk|lib/lib/core/core.dart.
[Error from Dart2JS on observatory|web/index.html.polymer.bootstrap.dart]:
dart:core library does not contain required classes: [Object, bool, num, int, double, String, Function, List, Type, Map, Null, StackTrace, Iterable, Symbol]
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on observatory|web/index.html.polymer.bootstrap.dart threw error: Internal Error: dart:core library does not contain required classes: [Object, bool, num, int, double, String, Function, List, Type, Map, Null, StackTrace, Iterable, Symbol]
package:compiler_unsupported/src/compiler.dart 1161:5        Compiler.internalError
package:compiler_unsupported/src/compiler.dart 1465:7        Compiler.initializeCoreClasses
package:compiler_unsupported/src/compiler.dart 1292:7        Compiler.onLibraryScanned
package:compiler_unsupported/src/library_loader.dart 409:23  _LibraryLoaderTask.processLibraryTags.<fn>
dart:isolate                                                 _RawReceivePortImpl._handleMessage
Build failed.
Command /bin/sh failed with exit code 65

** BUILD FAILED **
```

**Comment by sigmundch** [comment] 2015-06-26 21:07
Hey Patrice - I believe your case is a different issue. By any chance are you modifying the location of the system libraries (providing `--library-root`)? When dart2js can't find a library it pretends that they are empty, but with the core libraries it wont get that much further because it at least needs to Object and other core types. If that's the case, I think there is no need to file a new issue because we are tracking that in #23599

**Comment by sigmundch** [comment] 2015-06-26 21:39
Hey Mike - I have not been able to reproduce your issue yet. 

Here is what I tried:
```
  > git clone your-repo
  > git checkout repeater2
  > cd example/mdlx_dialog/  # I also tried spa_repeat
  > pub get
  > pub build
```

What steps are you following to run into this issue?

Unrelated, you may want to rename `example` to something else. The reason is that pub has a convention to treat `example` as part of your package - so it thinks they are meant to share the same package-root. As a result, if you call `pub get` up in your main package, pub may override the packages symlinks inside your nested packages within `example`. You should be safe using other names like `sample`, `samples`, `examples`.

**Comment by chalin** [comment] 2015-06-26 21:53
Thanks for the quick response.

> By any chance are you modifying the location of the system libraries (providing --library-root)?

No, I have made changes to the core lib sources "in place".  I'll keep investigating, Thanks.

**Comment by sigmundch** [comment] 2015-06-26 21:55
looking at the stack trace from Mike, it appears as if [jsUnmodifiableArrayClass](https://github.com/dart-lang/sdk/blob/1.11.0/pkg/compiler/lib/src/js_backend/backend.dart#L1075) was not found. @rakudrama  any guesses for what could make that happen?

If the [findClass('JSUnmodifiableArray')](https://github.com/dart-lang/sdk/blob/1.11.0/pkg/compiler/lib/src/js_backend/backend.dart#L2045) lookup was failing, but the previous lookups are not, maybe we are being provided an old version of the library code?

**Comment by sigmundch** [comment] 2015-06-26 22:14
I just tried this theory by explicitly passing the 1.10.1 sdk libraries to the 1.11.0 compiler:
```sh
dart2js --library-root=path-to-1.10.1-sdk-lib/ build/web/main.dart
```
and was able to reproduce the same stack trace as you have above.

Now I wonder why this is happening. My guess is that `pub` is passing the wrong SDK to us, but I have not been able to verify this or figure out why (@nex3  any ideas?).

@MikeMitterer - maybe you can help us verify that this is the actual issue. If your failure is currently in the context of `pub build` like in my steps above, I wonder if splitting the build step in two gets rid of the problem. In particular, you would need to:

* edit your pubspec to disable dart2js during pub build:
```yaml
- $dart2js:
    $include: [] # this excludes all files from being compiled by dart2js
```

* run `pub build --mode=debug`, this will generate the .dart files in the build folder
* run `dart2js build/web/main.dart`

**Comment by nex3** [comment] 2015-06-26 22:30
Is it possible that the `DART_SDK` environment variable is set? That could confuse pub into trying to load the wrong sources.

**Comment by sigmundch** [comment] 2015-06-26 22:37
Ah - that could be it! I can verify that if I add it, the error happens.

@MikeMitterer let us know if that's the case for you
@nex3 any plans to remove the use of this environment variable from pub in the future?

**Comment by nex3** [comment] 2015-06-26 22:48
@sigmundch Now that `Platform.executable` is more useful, we shouldn't need it any more. Can you file a bug?

**Comment by sigmundch** [comment] 2015-06-26 22:57
sure thing - all set.

**Comment by chalin** [comment] 2015-06-26 23:44
In the meantime, when building the SDK itself, what setting, if any, should `DART_SDK` have? When I unset it, my build attempt fails earlier (so it seems to be reading the env var). Thanks.

**Comment by nex3** [comment] 2015-06-26 23:44
If you're using a recent SDK, you shouldn't ever need to set `DART_SDK`.

**Comment by chalin** [comment] 2015-06-26 23:47
I'm using 1.11.0. If I unset DART_SDK, the error I get is shown below. Notice the "Uncaught Error: FileSystemException: Cannot open file, path = '/Users/chalin/git-nn/sdk/tools/testing/bin/version'".

```shell
=== BUILD AGGREGATE TARGET fetch_observatory_deps OF PROJECT dart-runtime WITH CONFIGURATION ReleaseX64 ===

Check dependencies

/bin/mkdir -p /Users/chalin/git-nn/sdk/xcodebuild/dart-runtime.build/ReleaseX64/fetch_observatory_deps.build
write-file /Users/chalin/git-nn/sdk/xcodebuild/dart-runtime.build/ReleaseX64/fetch_observatory_deps.build/Script-739B5A28A276503E58FBA004.sh
chmod 0755 /Users/chalin/git-nn/sdk/xcodebuild/dart-runtime.build/ReleaseX64/fetch_observatory_deps.build/Script-739B5A28A276503E58FBA004.sh

PhaseScriptExecution Action\ \"get_obsevatory_dependencies\" /Users/chalin/git-nn/sdk/xcodebuild/dart-runtime.build/ReleaseX64/fetch_observatory_deps.build/Script-739B5A28A276503E58FBA004.sh
    cd /Users/chalin/git-nn/sdk/runtime
    /bin/sh -c /Users/chalin/git-nn/sdk/xcodebuild/dart-runtime.build/ReleaseX64/fetch_observatory_deps.build/Script-739B5A28A276503E58FBA004.sh
Unhandled exception:
Uncaught Error: FileSystemException: Cannot open file, path = '/Users/chalin/git-nn/sdk/tools/testing/bin/version' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      _File.throwIfError (dart:io/file_impl.dart:556)
#1      _File.openSync (dart:io/file_impl.dart:408)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:467)
#3      _File.readAsStringSync (dart:io/file_impl.dart:501)
#4      readTextFile (package:pub/src/io.dart:154:20)
#5      _getVersion (package:pub/src/sdk.dart:49:19)
#6      version (package:pub/src/sdk.dart:37:19)
#7      version (package:pub/src/sdk.dart:37:9)
#8      PubCommandRunner.runCommand.<runCommand_async_body> (package:pub/src/command_runner.dart:111:21)
#9      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#11     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#12     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
Command /bin/sh failed with exit code 255

** BUILD FAILED **
```

**Comment by nex3** [comment] 2015-06-26 23:52
Try deleting the `third_party` and `xcodebuild` directories, running `git checkout third_party` and `gclient sync`, then retrying.

**Comment by chalin** [comment] 2015-06-27 01:28
Success! I had not thought about also cleaning out the `third_part`. Thanks. FYI, now that I can build, it helped uncover a bug in `dart2js`, #23736.

**Comment by MikeMitterer** [comment] 2015-06-29 11:24
@sigmundch Thanks! This solved my problem. I installed Dart via brew but the old SDK path was set. After removing the ENVVAR everything works fine!!!

**Comment by sigmundch** [comment] 2015-06-29 16:55
Awesome!

I'm closing this bug as we are now tracking our action items in separate bugs:
* https://github.com/dart-lang/pub/issues/1288 - get rid of using `DART_SDK` in pub
* #23741 - detect version inconsistency in dart2js

**Closed by sigmundch** 2015-06-29 16:55 UTC
Labels: Area-Dart2JS, Triaged, Type-Defect
