### ISSUE TITLE
NPE in InterfaceTypeImpl.isDirectSupertypeOf

### ISSUE THREAD

**Issue by biancashouse** [dart-lang/sdk#35233] opened 2018-11-20 22:58 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1344x840, 1280x800`

# Exception

Please append the contents of:
file:///private/var/folders/pd/5nkbdv0909n1vw71tt31yy900000gn/T/report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Failed to handle completion domain request: {id: 19070, method: completion.getSuggestions, params: {file: /Users/ianw/my/code/flutter/flowcharter/lib/function_picker_page2.dart, offset: 6888}, clientRequestTime: 1542753125940}
NoSuchMethodError: The method 'substitute2' was called on null.
Receiver: null
Tried calling: substitute2(_List len:1, _List len:1)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      InterfaceTypeImpl.isDirectSupertypeOf (package:analyzer/src/dart/element/type.dart:1508:27)
#2      InterfaceTypeImpl.isMoreSpecificThan (package:analyzer/src/dart/element/type.dart:1591:16)
#3      TypeImpl.isSubtypeOf (package:analyzer/src/dart/element/type.dart:2583:12)
#4      OpType._computeRequiredTypeAndFilters.<anonymous closure> (package:analyzer_plugin/src/utilities/completion/optype.dart:217:29)
#5      LibraryElementSuggestionBuilder.visitClassElement (package:analysis_server/src/services/completion/dart/local_library_contributor.dart:58:30)
#6      AbstractClassElementImpl.accept (package:analyzer/src/dart/element/element.dart:126:53)
#7      ImportedReferenceContributor._buildSuggestions (package:analysis_server/src/services/completion/dart/imported_reference_contributor.dart:84:12)

**Comment by srawlins** [comment] 2019-09-09 15:28
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/34563; please follow along there.

**Comment by srawlins** [comment] 2019-09-09 15:28
Duplicate of https://github.com/dart-lang/sdk/issues/34563

**Closed by srawlins** 2019-09-09 15:28 UTC
Labels: P2, analyzer-crash-report, area-analyzer, type-bug
