### ISSUE TITLE
Many dart2js tests failing unrelated to patterns when "records" and "patterns" experiments are enabled

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#51646] opened 2023-03-06 22:53 UTC
In my [in-progress CL to enable records and patterns](https://dart-review.googlesource.com/c/sdk/+/286344?tab=checks), I'm seeing [hundreds of dart2js failures on the bots](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787346541573253313/+/u/test_results/new_test_failures__logs_?format=raw).

The failures are all similar and related to a duplicate label in the generated JS:

```
/===================================================================\
| corelib_2/apply2_test broke (Pass -> RuntimeError, expected Pass) |
\===================================================================/

--- Command "dart2js" (took 04.000204s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart compile js -Dtest_runner.configuration=dart2js-minified-linux-d8 --test-mode --minify --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/corelib_2/apply2_test.dart --no-sound-null-safety --out=/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-minified-linux-d8/tests_corelib_2_apply2_test/apply2_test.js

exit code:
0

stdout:
Info: Compiling without sound null safety!
Dart 3 will only support sound null safety, see https://dart.dev/null-safety
Compiled 9,732,381 characters Dart to 55,347 characters JavaScript in 4.11 seconds using 396.188 MB of memory
Dart file tests/corelib_2/apply2_test.dart compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-minified-linux-d8/tests_corelib_2_apply2_test/apply2_test.js

--- Command "d8" (took 54ms):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/third_party/d8/linux/d8 out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/d8.js /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-minified-linux-d8/tests_corelib_2_apply2_test/apply2_test.js

exit code:
1

stdout:
/b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-minified-linux-d8/tests_corelib_2_apply2_test/apply2_test.js:855: SyntaxError: Label '$label0$0' has already been declared
$label0$0:if(12===m.x){h.push(A.br(p,m,o,a.n))
^^^^^^^^^
SyntaxError: Label '$label0$0' has already been declared

Deobfuscated error and stack:
<no error message found>
    at /b/s/w/ir/out/ReleaseX64/generated_compilations/dart2js-minified-linux-d8/tests_corelib_2_apply2_test/apply2_test.js:855: SyntaxError: Label '$label0$0' has already been declared unparsed
    at $label0$0:if(12===m.x){h.push(A.br(p,m,o,a.n))                                                                                                                                     unparsed
    at ^^^^^^^^^                                                                                                                                                                          unparsed
    at SyntaxError: Label '$label0$0' has already been declared                                                                                                                           unparsed


--- Re-run this test:
python3 tools/test.py -n dart2js-minified-linux-d8 corelib_2/apply2_test
```

cc @rakudrama

**Comment by munificent** [comment] 2023-03-07 18:18
cc @rakudrama

**Comment by sigmundch** [comment] 2023-03-07 21:34
partial update: @rakudrama is investigating. The underlying issue with labels is legit and probably has been there for a long time but not exercised -- heavy use of labels was rare before this new lowering of patterns from the CFE. It also appears like the issue is exacerbated by inlining, when labels in a switch from an inlined function conflicts with labels in a switch in the caller.

Long term, we will need to properly fix this. Short term, we are exploring ways to unblock the flag flip. Ideas include:
* set a language version in an SDK library - the trigger comes indirectly from an SDK library that gets treated as 3.0 after the flag flip.
* disable inlining in a handful of functions from the SDK library

**Comment by rakudrama** [comment] 2023-03-07 22:01
Tracking root cause at https://github.com/dart-lang/sdk/issues/51652.

**Comment by munificent** [comment] 2023-03-07 23:06
Thanks for looking into this!

**Comment by sigmundch** [comment] 2023-03-08 18:22
@munificent - a workaround landed that should unblock you. See https://dart-review.googlesource.com/c/sdk/+/287300

This change disables inlining whenever labels are present, and as a result, we expect it to workaronud the issue in any place where it occurs (whether that is the SDK like it happened in your CL or in user code).

**Comment by munificent** [comment] 2023-03-08 21:17
Awesome, thanks! I'll patch that into the flip CL and see if it pleases The Almighty Bots.

**Comment by munificent** [comment] 2023-03-08 22:23
I'm seeing [some dartj2s failures](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8787157786924699617/+/u/test_results/new_test_failures__logs_), but it looks like the label collision errors are all fixed now.

**Closed** 2023-04-03 16:35 UTC
Labels: web-dart2js, area-web
