### ISSUE TITLE
Internal problem: Unhandled  (response != null)

### ISSUE THREAD

**Issue by alexst07** [dart-lang/sdk#40761] opened 2020-02-25 03:53 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-88-generic, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
Internal problem: Unhandled  (response != null) {' in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1370:22)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4239:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#11     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#13     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5218:12)
#14     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3803:14)
#15     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#16     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5397:13)
#17     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3739:14)
#18     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#19     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#20     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3259:15)
#21     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#22     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#23     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#24     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#25     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#26     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#27     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#28     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#29     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#30     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#31     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#32     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:642:10)
#33     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#34     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#37     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#38     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#39     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#40     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#46     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#47     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#48     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#50     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#51     new Future.sync (dart:async/future.dart:224:31)
#52     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#53     _rootRun (dart:async/zone.dart:1124:13)
#54     _CustomZone.run (dart:async/zone.dart:1021:19)
#55...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment] 2020-06-15 03:34
Thanks for reporting this issue! This was previously reported as https://github.com/dart-lang/sdk/issues/39037 during fuzz testing. Please follow along there. https://github.com/dart-lang/sdk/issues/39037

**Comment by srawlins** [comment] 2020-06-15 03:34
Duplicate of #39037

**Closed by srawlins** 2020-06-15 03:34 UTC
Labels: analyzer-crash-report, area-analyzer
