### ISSUE TITLE
Assertion failure on iso-stress-linux

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/sdk#55687] opened 2024-05-10 17:30 UTC
Looks like it happened when running `vm/dart/heap_snapshot_regress_49710_test.dart`.

```
../../runtime/vm/tagged_pointer.h: 466: error: expected: (value & kSmiTagMask) == kSmiTag
version=3.5.0-edge (main) (Unknown timestamp) on "linux_x64"
pid=145494, thread=145512, isolate_group=main(0x5596d7687b70), isolate=wrapper54(0x7f3120079a80)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=5596d4da8d40, vm_instructions=5596d4da8d40
fp=7f31317f3070, sp=7f31317f2f40, pc=5596d51ab71c
  pc 0x00005596d51ab71c fp 0x00007f31317f3070 dart::Profiler::DumpStackTrace+0x7c
  pc 0x00005596d4da8f34 fp 0x00007f31317f3150 dart::Assert::Fail+0x84
  pc 0x00005596d50d1160 fp 0x00007f31317f3170 dart::Smi::Value+0x40
  pc 0x00005596d5170012 fp 0x00007f31317f3220 dart::Pass2Visitor::VisitObject+0x5a2
  pc 0x00005596d52b47d6 fp 0x00007f31317f3280 dart::Page::VisitObjects+0xd6
  pc 0x00005596d52c4e4b fp 0x00007f31317f32c0 dart::Scavenger::VisitObjects+0x5b
  pc 0x00005596d52a8897 fp 0x00007f31317f32e0 dart::HeapIterationScope::IterateObjects+0x17
  pc 0x00005596d516c0ad fp 0x00007f31317f34e0 dart::HeapSnapshotWriter::Write+0x1a3d
  pc 0x00005596d4f45ce0 fp 0x00007f31317f35c0 dart::BootstrapNatives::DN_Developer_NativeRuntime_writeHeapSnapshotToFile+0x170
  pc 0x00005596d5094a71 fp 0x00007f31317f3ce0 dart::NativeEntry::BootstrapNativeCallWrapper+0xc1
  pc 0x00007f3154c83644 fp 0x00007f31317f3d20 Unknown symbol
  pc 0x00007f31303de3a1 fp 0x00007f31317f3d58 Unknown symbol
  pc 0x00007f3130394eb7 fp 0x00007f31317f3dd0 Unknown symbol
  pc 0x00007f3130382b11 fp 0x00007f31317f3e50 Unknown symbol
  pc 0x00007f3130380e4c fp 0x00007f31317f3e90 Unknown symbol
  pc 0x00007f3147cf5d1f fp 0x00007f31317f3eb8 Unknown symbol
  pc 0x00007f3147cbf8d3 fp 0x00007f31317f3f30 Unknown symbol
  pc 0x00007f3147cbf613 fp 0x00007f31317f3f90 Unknown symbol
  pc 0x00007f3147cbeccb fp 0x00007f31317f4020 Unknown symbol
  pc 0x00007f3147cb6e66 fp 0x00007f31317f4070 Unknown symbol
  pc 0x00007f3147cb68a4 fp 0x00007f31317f40f8 Unknown symbol
  pc 0x00007f3147cf5b4b fp 0x00007f31317f4138 Unknown symbol
  pc 0x00007f3130a7fc79 fp 0x00007f31317f4168 Unknown symbol
  pc 0x00007f3147ca2f13 fp 0x00007f31317f41d0 Unknown symbol
  pc 0x00007f3147ca3234 fp 0x00007f31317f4218 Unknown symbol
  pc 0x00007f3147ca2f13 fp 0x00007f31317f4280 Unknown symbol
  pc 0x00007f3147ca1f39 fp 0x00007f31317f42d8 Unknown symbol
  pc 0x00007f3154c839d4 fp 0x00007f31317f4350 Unknown symbol
  pc 0x00005596d50020df fp 0x00007f31317f43c0 dart::DartEntry::InvokeFunction+0x12f
  pc 0x00005596d5004cc5 fp 0x00007f31317f4420 dart::DartLibraryCalls::HandleMessage+0xf5
  pc 0x00005596d503c3bd fp 0x00007f31317f4bb0 dart::IsolateMessageHandler::HandleMessage+0x37d
  pc 0x00005596d507a725 fp 0x00007f31317f4c40 dart::MessageHandler::HandleMessages+0x1d5
  pc 0x00005596d507b3c7 fp 0x00007f31317f4cc0 dart::MessageHandler::TaskCallback+0x307
  pc 0x00005596d5274298 fp 0x00007f31317f4d50 dart::ThreadPool::WorkerLoop+0x188
  pc 0x00005596d5274bbb fp 0x00007f31317f4da0 dart::ThreadPool::Worker::Main+0x12b
  pc 0x00005596d51a48a3 fp 0x00007f31317f4ef0 dart::ThreadStart+0x103
-- End of DumpStackTrace
  pc 0x0000000000000000 fp 0x00007f31317f3d20 sp 0x0000000000000000 [Stub] CallBootstrapNative
  pc 0x00007f31303de3a1 fp 0x00007f31317f3d58 sp 0x00007f31317f3d30 [Unoptimized] NativeRuntime.writeHeapSnapshotToFile
  pc 0x00007f3130394eb7 fp 0x00007f31317f3dd0 sp 0x00007f31317f3d68 [Unoptimized] main.<anonymous closure>
  pc 0x00007f3130382b11 fp 0x00007f31317f3e50 sp 0x00007f31317f3de0 [Unoptimized] withTempDir
  pc 0x00007f3130380e4c fp 0x00007f31317f3e90 sp 0x00007f31317f3e60 [Unoptimized] main
  pc 0x00007f3147cf5d1f fp 0x00007f31317f3eb8 sp 0x00007f31317f3ea0 [Unoptimized] wrapper54.<anonymous closure>
  pc 0x00007f3147cbf8d3 fp 0x00007f31317f3f30 sp 0x00007f31317f3ec8 [Unoptimized] _rootRun@4048458
  pc 0x00007f3147cbf613 fp 0x00007f31317f3f90 sp 0x00007f31317f3f40 [Unoptimized] _rootRun@4048458
  pc 0x00007f3147cbeccb fp 0x00007f31317f4020 sp 0x00007f31317f3fa0 [Unoptimized] _CustomZone@4048458.run
  pc 0x00007f3147cb6e66 fp 0x00007f31317f4070 sp 0x00007f31317f4030 [Unoptimized] _runZoned@4048458
  pc 0x00007f3147cb68a4 fp 0x00007f31317f40f8 sp 0x00007f31317f4080 [Unoptimized] runZoned
  pc 0x00007f3147cf5b4b fp 0x00007f31317f4138 sp 0x00007f31317f4108 [Unoptimized] wrapper54
  pc 0x00007f3130a7fc79 fp 0x00007f31317f4168 sp 0x00007f31317f4148 [Unoptimized] wrapper54
  pc 0x00007f3147ca2f13 fp 0x00007f31317f41d0 sp 0x00007f31317f4178 [Unoptimized] _Closure@0150898.dyn:call
  pc 0x00007f3147ca3234 fp 0x00007f31317f4218 sp 0x00007f31317f41e0 [Unoptimized] _delayEntrypointInvocation@1026248.<anonymous closure>
  pc 0x00007f3147ca2f13 fp 0x00007f31317f4280 sp 0x00007f31317f4228 [Unoptimized] _Closure@0150898.dyn:call
  pc 0x00007f3147ca1f39 fp 0x00007f31317f42d8 sp 0x00007f31317f4290 [Unoptimized] _RawReceivePort@1026248._handleMessage@1026248
  pc 0x00007f3154c839d4 fp 0x00007f31317f4350 sp 0x00007f31317f42e8 [Stub] InvokeDartCode
=> Running "out/DebugX64/dart --disable-dart-dev --sound-null-safety runtime/tests/concurrency/generated_stress_test.dart.jit.dill" failed with -6
=> Possible crash 0 (pid: 145494)
```

https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/iso-stress-linux/5943/overview

**Comment by aam** [comment] 2024-05-15 20:39
Duplicate of https://github.com/dart-lang/sdk/issues/55689

**Closed by aam** 2024-05-15 20:39 UTC
Labels: area-vm, gardening
