### ISSUE TITLE
Can console.log(...) support multiple params?

### ISSUE THREAD

**Issue by chenenyu** [dart-lang/sdk#44168] opened 2020-11-12 09:19 UTC

**Comment by Silentdoer** [comment] 2020-11-12 10:35
dart has console.log(..) ?

**Comment by chenenyu** [comment] 2020-11-12 10:43
@Silentdoer `dart:html`

**Comment by kevmoo** [comment] 2020-11-12 16:28
We'll likely wait until we have https://github.com/dart-lang/language/issues/1014 – same for `print`

**Comment by sigmundch** [comment] 2020-11-12 22:46
Thanks for filing the issue.

Until this is addressed, note you can use JS-interop to circumvent the problem:
```dart
@JS()
library foo;
import 'package:js/js.dart'
...

@JS('window.console')
external myConsole(arg1, arg2, arg3);

...
main() {
  myConsole(a, b, c);
}
```

or:
```dart
import 'dart:js_util' as js_util;
import 'dart:html';
...
main() {
  js_util.callMethod(window, 'console', [a, b, c]);
}
```
I was able to find a very similar and old request here: https://github.com/dart-lang/sdk/issues/19977, so I'll close this as a duplicate of that.

**Closed by sigmundch** 2020-11-12 22:46 UTC
Labels: area-web
