### ISSUE TITLE
Dart2JS does not allow null-aware ?. in a cascade expression

### ISSUE THREAD

**Issue by mhausner** [dart-lang/sdk#28020] opened 2016-12-07 06:13 UTC
The following code does not compile with dart2js. It is legal.

```dart
void main() {
  var foo = new Foo()
    ..bar?.doThing();
}

class Foo {
  Bar bar;
}

class Bar {
  void doThing() {
    print('thing');
  }
}
```

I get this error:

```
Error: Expected ';' after this.
    ..bar?.doThing();
      ^^^
Error: Compilation failed.
```

The error message is also a bit cryptic.

The VM compiles the program without error.

**Comment by natebosch** [comment] 2018-08-24 00:29
Duplicate of https://github.com/dart-lang/sdk/issues/28367

This is workin in the 2.0 SDK

**Closed by natebosch** 2018-08-24 00:29 UTC
Labels: area-dart2js, type-bug
