### ISSUE TITLE
Patterns, parse nested record type annotation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#51176] opened 2023-01-30 20:08 UTC
```dart
  var (n: (int, {int x}) a10, (int z, {int y}) b10)
      = (n: (x: 42, -1), (y: 1, 0));
```
See `co19/LanguageFeatures/Patterns/record_A02_t08`.

This results in
```
- Line 72, column 22: SYNTACTIC_ERROR.EXPECTED_TOKEN
  Expected to find ':'.

- Line 72, column 26: SYNTACTIC_ERROR.EXPECTED_TOKEN
  Expected to find ')'.
```

**Comment by stereotype441** [comment] 2023-01-30 20:17
Yikes!  I'll look at this ASAP.

**Comment by johnniwinther** [comment] 2023-01-30 20:27
Duplicate of https://github.com/dart-lang/sdk/issues/51169 I think. Will you take this @stereotype441 ? I don't think @jensjoha has started on it yet.

**Comment by scheglov** [comment] 2023-01-30 20:30
BTW, my apologies if assigning these pattern parser issues for @stereotype441 is not correct. I do this because he wrote the original parser code, but if someone else now continues this work, I can re-assign these issues :-)

**Comment by jensjoha** [comment] 2023-01-31 11:11
Suggested fix in https://dart-review.googlesource.com/c/sdk/+/280106.

**Comment by stereotype441** [comment] 2023-01-31 17:15
> BTW, my apologies if assigning these pattern parser issues for @stereotype441 is not correct. I do this because he wrote the original parser code, but if someone else now continues this work, I can re-assign these issues :-)

No problem.  I didn't realize Jens was taking issues like this one either.  It looks like he found and fixed the problem before I got a chance 😄

**Comment by stereotype441** [comment] 2023-01-31 17:15
Duplicate of #51169

**Closed by stereotype441** 2023-01-31 17:15 UTC
Labels: area-front-end
