### ISSUE TITLE
js-interop:  No such a method error when calling a javascript method from dart on flutter web using https://pub.dev/packages/js

### ISSUE THREAD

**Issue by gatanga** [dart-lang/sdk#40102] opened 2020-01-13 21:06 UTC
Hi there, 

I need assistance. 
I am working on a flutter Web project and need to call javascript methods from my class using this package: https://pub.dev/packages/js

Let's say the javascript file name is `test.js` and the contents of the files look like this:

```
class Test {
   test(){
        return "Flutter Web"
   }
}
```

And then I have a dart file named `test.dart` with contents:

```
@JS("Test")
library test.js

@JS()
external String test()
```

When I call the `test` method from dart, I am getting no such a method error `test` (Test.test is not a function)

I cannot figure out what went wrong. Please assist

**Comment by gatanga** [comment] 2020-01-15 15:40
@mit-mit Please assist if you are able to. I have a critical project that depends on this feature working

**Comment by mit-mit** [comment] 2020-01-15 16:41
cc @vsmenon do we have any examples/docs for JS interop with flutter web?

**Comment by vsmenon** [comment] 2020-01-15 17:01
@natebosch 

Your JS and your Dart don't match.  The former declares a class with an instance method.  The latter declares a top-level method.  

I.e., given that JS, your Dart should look something like (see https://pub.dev/packages/js):

```dart
@JS()
library test;

@JS()
class Test {
  external String test();
}
```

**Comment by gatanga** [comment] 2020-01-16 17:01
@vsmenon Thank you so much for your assistance. Much appreciated.

I am now getting this error  `TypeError: dart.global.Test is not a constructor`

**Comment by natebosch** [comment] 2020-02-13 23:07
cc @sigmundch 

This is a really similar problem as https://github.com/dart-lang/sdk/issues/39995

We only see the classes defined on `window`, you could work around this for now with something like:

```js
window.Test = Test;
```

You'd need to do that for every class you want to be able to instantiate that is created at the top level instead of on some namespace. You can also declare the classes directly that way

```js
window.Test = class {
}
```

As a side note, you'll also want to add  an external factory constructor to your Test class. We'd like to make this automatic but it isn't yet. See https://github.com/dart-lang/sdk/issues/40434

```dart
@JS()
class Test {
  external factory Test();
  external String test();
}
```

**Comment by sigmundch** [comment] 2020-06-12 00:32
Closing as a dupe of #39995

**Closed by sigmundch** 2020-06-12 00:32 UTC
Labels: area-web, web-js-interop
