### ISSUE TITLE
implement VM IL serialization and deserialization

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#36882] opened 2019-05-08 08:04 UTC
Currently VM IL can be printed in human readable form - but this form is not machine readable and omits some information.

There are use cases where we would benefit from having a format that is both human and machine readable and writable:

- Writing tests.
- Writing alternative backends for Dart VM.

This bug is to track the design and development of such a form.

**Comment by sstrickl** [comment] 2019-09-03 11:49
After d2e99c4, we started seeing the following failures:

| BOT                                               | TEST                                         | RESULT | EXPECTED | 
| ------------------------------------------------- | -------------------------------------------- | ------ | -------- | 
| vm-kernel-optcounter-threshold-linux-release-ia32 | vm/dart/il_round_trip_deserialization_test/2 | Crash  | Pass     |
| vm-kernel-optcounter-threshold-linux-release-ia32 | vm/dart/il_round_trip_deserialization_test/3 | Crash  | Pass     |
| vm-kernel-precomp-win-release-simarm64            | vm/dart/il_round_trip_deserialization_test/2 | Crash  | Pass     |
| vm-kernel-precomp-win-release-simarm64            | vm/dart/il_round_trip_deserialization_test/3 | Crash  | Pass     |
| vm-kernel-precomp-win-release-simarm64            | vm/dart/il_round_trip_deserialization_test/6 | Crash  | Pass     |
| vm-kernel-precomp-win-release-simarm64            | vm/dart/il_round_trip_deserialization_test/7 | Crash  | Pass     |
| vm-kernel-precomp-win-release-x64                 | vm/dart/il_round_trip_deserialization_test/2 | Crash  | Pass     |
| vm-kernel-precomp-win-release-x64                 | vm/dart/il_round_trip_deserialization_test/3 | Crash  | Pass     |
| vm-kernel-precomp-win-release-x64                 | vm/dart/il_round_trip_deserialization_test/6 | Crash  | Pass     |
| vm-kernel-precomp-win-release-x64                 | vm/dart/il_round_trip_deserialization_test/7 | Crash  | Pass     |

Example logs:

* [vm-kernel-precomp-win-release-simarm64](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8903348657502169696/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0)
* [vm-kernel-precomp-win-release-x64](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8903348653554767408/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0)
* [vm-kernel-optcounter-threshold-linux-release-ia32](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8903348661723607632/+/steps/test_results/0/logs/tests_that_began_failing__logs_/0)

Have approved for now, but will need to figure these out ASAP (or see if they're fixed by work in later CLs, in which case I may need to move that work forward and land separately first).

**Comment by sstrickl** [comment] 2019-09-05 11:15
Couple more issues approved after 7c8c197 ([example log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8903162411962921040/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0)):

| BOT                                              | TEST                                         | RESULT | EXPECTED | 
| ------------------------------------------------ | -------------------------------------------- | ------ | -------- | 
| vm-kernel-optcounter-threshold-linux-release-x64 | vm/dart/il_round_trip_deserialization_test/2 | Crash  | Pass     |
| vm-kernel-optcounter-threshold-linux-release-x64 | vm/dart/il_round_trip_deserialization_test/3 | Crash  | Pass     |

At a good point to stop and look at these today, so doing that now.

**Comment by mkustermann** [comment] 2019-09-05 14:47
A few more from today:

| BOT                                               | TEST                                                                           | RESULT     | EXPECTED | 
| ------------------------------------------------- | ------------------------------------------------------------------------------ | ---------- | -------- | 
| vm-kernel-optcounter-threshold-linux-release-ia32 | vm/dart/il_round_trip_deserialization_test/1                                   | DartkCrash | Pass     |
| vm-kernel-optcounter-threshold-linux-release-ia32 | vm/dart/il_round_trip_deserialization_test/5                                   | DartkCrash | Pass     |
| vm-kernel-optcounter-threshold-linux-release-ia32 | vm/dart/il_round_trip_deserialization_test/6                                   | Crash      | Pass     |
| vm-kernel-optcounter-threshold-linux-release-ia32 | vm/dart/il_round_trip_deserialization_test/7                                   | DartkCrash | Pass     |

**Comment by cskau-g** [comment] 2019-09-10 09:12
FYI: dumping a bit more info on one of the failing tests:

```shell
$ tools/test.py -n dartk-optcounter-linux-debug-ia32 vm/dart/il_round_trip_deserialization_test/2

../../runtime/vm/compiler/backend/il_serializer.cc: 452: error: expected: instance_field_.is_final()
version=2.6.0-edge.b31566b29793247d0fdb2281a435e87fdae77cd5 (Thu Sep 5 12:56:49 2019 +0000) on "linux_ia32"
thread=256741, isolate=kernel-service(0x4184e00)
  pc 0x01ce123c fp 0xf6a3e678 dart::Profiler::DumpStackTrace(void*)
  pc 0x021f00a4 fp 0xf6a3e698 Dart_DumpNativeStackTrace
  pc 0x0194dbeb fp 0xf6a3e6c8 dart::Assert::Fail(char const*, ...)
  pc 0x01e5ac42 fp 0xf6a3e728 dart::FlowGraphSerializer::InstanceToSExp(dart::Instance const&)
  pc 0x01e5bb6e fp 0xf6a3e758 dart::FlowGraphSerializer::ObjectToSExp(dart::Object const&)
  pc 0x01e5949e fp 0xf6a3e7a8 dart::FlowGraphSerializer::ConstantPoolToSExp(dart::GraphEntryInstr*)
  pc 0x01e58017 fp 0xf6a3e7e8 dart::FlowGraphSerializer::FlowGraphToSExp()
  pc 0x01e57af3 fp 0xf6a3e868 dart::FlowGraphSerializer::SerializeToSExp(dart::Zone*, dart::FlowGraph const*)
  pc 0x01e2241a fp 0xf6a3e9c8 dart::FlowGraphDeserializer::RoundTripSerialization(dart::CompilerPassState*)
  pc 0x01ec1206 fp 0xf6a3ea08 out/DebugIA32/dart+0x1ac1206
  pc 0x01ebf625 fp 0xf6a3ea98 dart::CompilerPass::Run(dart::CompilerPassState*) const
  pc 0x01ebfcbc fp 0xf6a3eac8 dart::CompilerPass::RunPipeline(dart::CompilerPass::PipelineMode, dart::CompilerPassState*)
  pc 0x01f3da3a fp 0xf6a3ee38 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x01f3ea0d fp 0xf6a3efc8 out/DebugIA32/dart+0x1b3ea0d
  pc 0x01f3f65f fp 0xf6a3f048 dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, int)
  pc 0x01f407ed fp 0xf6a3f0c8 dart::BackgroundCompiler::Run()
  pc 0x01f418b7 fp 0xf6a3f0e8 out/DebugIA32/dart+0x1b418b7
  pc 0x01d93aaf fp 0xf6a3f138 dart::ThreadPool::Worker::Loop()
  pc 0x01d9364a fp 0xf6a3f188 dart::ThreadPool::Worker::Main(unsigned int)
  pc 0x01cdb4bf fp 0xf6a3f2d8 out/DebugIA32/dart+0x18db4bf
  pc 0xf7eb1982 fp 0xf6a3f3a8 /lib/i386-linux-gnu/libpthread.so.0+0x6982
```

**Comment by sstrickl** [comment] 2019-09-11 12:20
That dump strengthens a hypothesis I had for one possible reason for these failures, which is that we're getting non-canonical values in `ConstantInstr`s on some architectures/runs. Martin and I had seen this while trying to figure out an issue I could reproduce locally which led to 488a8ae6, and looking at the results of CI after 488a8ae6 landed, it looks like some of these failures are indeed now passing.

That's not _all_ the failures, but it's good to see some going Pass after at least.

**Comment by mkustermann** [comment] 2019-10-11 17:25
Just an FFYI: The recent enabling of bytecode has made the two `vm/dart/il_round_trip_deserialization_test/{5,7}` tests pass. Though the underlying bug is probably still there.

(In the meantime bytecode is off by-default again)

**Comment by mehmetf** [comment] 2020-04-03 16:44
Note that https://github.com/dart-lang/sdk/commit/6b44c631ad374ac00186d57595f7efc73939ca6d is causing {1,3,5,7} to crash again.

**Comment by mkustermann** [comment] 2021-11-04 14:58
The S-expression like IR serializer has been discontinued due to our main possible user going away. Closing this issue for now.

**Closed by mkustermann** 2021-11-04 14:58 UTC
Labels: area-vm
