### ISSUE TITLE
Dart does not throw error when analyzer fails with "type_argument_not_matching_bounds" error for mixins

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#33624] opened 2018-06-26 10:48 UTC
Dart SDK Version: 2.0.0-dev.64.1
OS: Windows 10 (64 bit)

The following test example tries to create an object of the mixin with incorrect type parameter. It produces type_argument_not_matching_bound in analyzer and passes with dart:
```
class A {}
class B{}

class M<X extends A> {}
class O<X> extends Object with M<X> {}

main() {
  O o = new O<B>();
}
```
Sample output is:
```
$>dart --version
Dart VM version: 2.0.0-dev.64.1 (Thu Jun 21 08:47:55 2018 +0200) on "windows_x64"

$>dartanalyzer test.dart
Analyzing test.dart...
  error - 'X' doesn't extend 'A' at test.dart:5:34 - type_argument_not_matching_bounds
  hint - The value of the local variable 'o' isn't used at test.dart:8:5 - unused_local_variable
1 error and 1 hint found.

$>dart test.dart

$>
```

I believe dart should throw error here.

Please note that there is a similar issue about incorrect class parameters: #33585.

**Comment by anders-sandholm** [comment] 2018-06-26 12:10
@eernstg

**Comment by eernstg** [comment] 2018-07-04 07:49
Right, the VM should emit a compile-time error, so this is another case where we encounter the missing bounds checks reported in a more general fashion in #33308.

I'm closing this one as a duplicate of #33308, and adding a comment there that we have extra examples here. Also adjusting the area, just for completeness.

**Closed by eernstg** 2018-07-04 07:49 UTC
Labels: Resolution: duplicate, area-front-end
