### ISSUE TITLE
Strong mode runtime semantics in the VM

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#30475] opened 2017-08-17 21:38 UTC
for the tests language_2/function_type/*_test, the VM does not implement the strong mode `is` checks or the correct runtime function type for the tear off

**Comment by a-siva** [comment] 2017-08-31 18:18
This appears to be a duplicate of https://github.com/dart-lang/sdk/issues/30270 marking as such.

**Closed** 2017-08-31 18:24 UTC
Labels: area-vm
