### ISSUE TITLE
ffi/callback_unwind_error_test was flaky, turned Crash on vm-aot-linux-release-arm-qemu

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#56060] opened 2024-06-20 17:16 UTC
from build https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/vm-ffi-qemu-linux-release-arm/2419/overview
 
```
--- Command "vm_compile_to_kernel" (took 01.000504s):
DART_CONFIGURATION=ReleaseXARM /b/s/w/ir/cache/builder/sdk/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseXARM/vm_platform_strong.dill -o /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.dill /b/s/w/ir/cache/builder/sdk/tests/ffi/callback_unwind_error_test.dart -Dtest_runner.configuration=vm-aot-linux-release-arm-qemu --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 01.000968s):
DART_CONFIGURATION=ReleaseXARM out/ReleaseSIMARM_X64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.S --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-arm-qemu --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 45ms):
DART_CONFIGURATION=ReleaseXARM rm /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.dill

exit code:
0

--- Command "assemble" (took 711ms):
DART_CONFIGURATION=ReleaseXARM arm-linux-gnueabihf-gcc -Wl,--no-undefined -shared -o /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.aotsnapshot /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.S

exit code:
0

--- Command "remove_assembly" (took 29ms):
DART_CONFIGURATION=ReleaseXARM rm /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.S

exit code:
0

--- Command "vm" (took 401ms):
DART_CONFIGURATION=ReleaseXARM TEST_COMPILATION_DIR=/b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-arm-qemu --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/vm-aot-linux-release-arm-qemu/tests_ffi_callback_unwind_error_test/out.aotsnapshot

exit code:
-11

stdout:
simpleAddition(10, 20)

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-release-arm-qemu ffi/callback_unwind_error_test
```

**Comment by a-siva** [comment] 2024-06-26 20:40
Seems to be a duplicate of https://github.com/dart-lang/sdk/issues/53581

**Closed** 2024-06-26 20:40 UTC
Labels: area-vm, closed-duplicate, gardening
