### ISSUE TITLE
Unable to build on Mac

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/sdk#24501] opened 2015-10-05 18:51 UTC
I've downloaded the sources with gclient sync and runhooks. 
I have xcode installed. 
While trying to run `./tools/build.py --mode=release --arch=x64`
Everything succeeds until I hit:

```
=== BUILD AGGREGATE TARGET dart2js OF PROJECT compiler WITH CONFIGURATION ReleaseX64 ===

Check dependencies

    cd /Users/matt/src/sdk/utils/compiler
    /bin/sh -c /Users/matt/src/sdk/xcodebuild/compiler.build/ReleaseX64/dart2js.build/Script-798B493C2BAAADFDA6E22C7E.sh
Unhandled exception:
OS Error: Failed to retrieve environment variables.
#0      _Platform.environment (dart:io/platform_impl.dart:97)
#1      Platform.environment (dart:io/platform.dart:128)
#2      _ProcessImpl._ProcessImpl (dart:io-patch/process_patch.dart:243)
#3      Process.start (dart:io-patch/process_patch.dart:26)
#4      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:548)
#5      Process.run (dart:io-patch/process_patch.dart:45)
#6      getVersion (file:///Users/matt/src/sdk/utils/compiler/create_snapshot.dart:10:18)
#7      getSnapshotGenerationFile (file:///Users/matt/src/sdk/utils/compiler/create_snapshot.dart:21:10)
#8      main (file:///Users/matt/src/sdk/utils/compiler/create_snapshot.dart:104:3)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
Command /bin/sh failed with exit code 255

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Action\ \"generate_snapshots\" /Users/matt/src/sdk/xcodebuild/compiler.build/ReleaseX64/dart2js.build/Script-798B493C2BAAADFDA6E22C7E.sh
(1 failure)
BUILD FAILED
```
And thoughts or suggestions why I may be running into this error? I've also tried specifying `--os=host` but to no avail.

**Comment by whesse** [comment] 2015-10-06 11:20
Looking at the code, it seems like the only way this error could be returned is if TARGET_OS_IPHONE or TARGET_OS_IOS is defined.  Can you think of any reason this would be?  If you earlier tried a build with this defined, maybe an executable compiled this way is not being updated.  Try and delete the xcodebuild directory and try again.

If this continues, you could try printf debugging by putting printf statements in the function Platform::Environment in runtime/bin/platform.macos.cc.  It seems to me that the only way to get this error is if the function returns null.

**Comment by butlermatt** [comment] 2015-10-06 12:23
I deleted the xcodebuild directory along with the create_sdk.xcodeproj and dart.xcodeproj directories. Ran gclient sync and runhooks again. I then build with `./tools/build.py -m release -a x64 --os=macos` and it still failed to build at the same location.
Adding in the print statements around Platform::Environment around line 90 of `runtime/bin/platform.cc` the Platform::Environment was returning null.

Adding the printf debug statements to `runtime/bin/platform_macos.cc`, it does seem to show that `TARGET_OS_IOS` is defined, however this is not a flag I passed at any time, and I'm honestly not certain on where one would set that definition.

This is a new system which was formatted, then upgraded to MacOS 10.11 with XCode version 7.0.1

**Comment by butlermatt** [comment] 2015-10-06 12:50
I also wrote an extremely simple program to test the defines locally:

```
#include <stdio.h>
#include <TargetConditionals.h>

int main() {
	printf("%d\n", TARGET_OS_IPHONE);
	printf("%d\n", TARGET_OS_MAC);
	return 0;
}
```
And the output of this is:
```0
1
```

So it appears somewhere in the xcode project files the TARGET_OS_IPHONE is being enabled where it shouldn't be.

**Comment by butlermatt** [comment] 2015-10-06 13:26
I will mention as well, I added something similar to the debug statements in Platform::Environment.
```
printf("%d\n", TARGET_OS_IPHONE);
printf("%d\n", TARGET_OS_IOS);
```
And both are returning 0.

**Comment by whesse** [comment] 2015-10-06 13:41
I think the problem is that we are using #if defined (TARGET_OS_IOS) instead of #if TARGET_OS_IOS.
The macro is defined as 0, which is defined, but not true.

Try changing the line in platform_macos.cc to #if TARGET_OS_IOS
I'll submit a CL with this fix in it.

**Comment by butlermatt** [comment] 2015-10-06 13:51
Thanks. You may also want to do it around line 15 of platform_macos.cc which conditionally includes crt_externs.h with: `#if !defined(TARGET_OS_IOS)`

That appears to have resolved that issue and compilation has proceeded. Thanks!

**Comment by whesse** [comment] 2015-10-06 14:10
Yes.  It is trickier, because we must also handle all cases where the macro is undefined, as well, both on macos, and on other platforms.

But in an #if conditional, undefined macros are treated as defined and equal to 0, so just changing to TARGET_OS_MACOS

Also this issue is mentioned in issue #24453

**Comment by whesse** [comment] 2015-10-06 14:20
Submitted CL https://codereview.chromium.org/1388973002/

**Comment by sethladd** [comment] 2015-10-08 17:13
Thanks for the report @butlermatt !

**Comment by whesse** [comment] 2015-10-12 14:23
Fixed.  This will be in the next dev channel release 1.13.0-dev.7.0, and in the stable release of 1.13.

**Closed by whesse** 2015-10-12 14:23 UTC
Labels: Area-Infrastructure
