### ISSUE TITLE
maybe a error

### ISSUE THREAD

**Issue by Vito915** [dart-lang/sdk#35351] opened 2018-12-07 02:07 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Administrator\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\AndroidStudioProjects\vkonline_app\lib\pages\personcenter\info\UserInfo.dart context: exception_20181207_100504_742
RangeError (index): Invalid value: Not in range 0..12, inclusive: 13
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#6      _ParameterElementImpl

**Comment by stereotype441** [comment] 2018-12-12 17:22
Duplicate of #34534

**Closed by stereotype441** 2018-12-12 17:22 UTC
Labels: area-analyzer
