### ISSUE TITLE
Dart analysis server error: Element not found in summary

### ISSUE THREAD

**Issue by DeveloperInProgress** [dart-lang/sdk#34716] opened 2018-10-08 14:11 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.4eb879133a06c86869dc54cecf904f4b1d46c47b`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\HP\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.4eb879133a06c86869dc54cecf904f4b1d46c47b, server version 1.20.5, error: Analysis failed: C:\Users\HP\AndroidStudioProjects\offlinelocus3\lib\about.dart context: exception_20181008_192349_122
Exception: Element not found in summary: package:flutter/src/widgets/basic.dart

**Comment by bwilkerson** [comment] 2018-10-08 14:33
Thanks for the report! Can you provide us with either a stack trace or a short set of reproduction steps (or both)? Without either of those there's probably nothing we can do to track this down.

**Comment by bwilkerson** [comment] 2018-10-08 20:17
For example, did this happen as a result of doing a `flutter upgrade`?

**Comment by stereotype441** [comment] 2018-10-23 04:05
Duplicate of #34555

**Closed by stereotype441** 2018-10-23 04:05 UTC
Labels: area-analyzer, needs-info, type-bug
