### ISSUE TITLE
DDC expands constants many times with CFE constants flag

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/sdk#36535] opened 2019-04-09 01:05 UTC
Discovered while investigating https://github.com/dart-lang/sdk/issues/36532

DDC's technique for emitting constants in its Analyzer backend ensured that large constants would only be emitted once, typically. It worked because users put large constants (e.g. lists, maps, objects) in a variable and refer to that variable, rather than copy+paste the constant expression into multiple locations.

That breaks down with Kernel with the constants flag on, because it's now inlining these constant nodes everywhere. The original Kernel tree is not kept around. So DDC only gets "InstanceConstant" or "ListConstant" for example. Since DDC is a modular compiler, it cannot do global canonicalization. By inlining constants, CFE removes DDC's primary means of optimizing constants (the fact that developers generally put large constants in variables).

I don't see any reasonable way for DDC to work around this on its own. We'll need some help from CFE/Kernel--some way to control constant inlining. Inlining numbers/bools/small strings is fine, but otherwise we don't want to inline, and need these to remain as StaticGet nodes.

The first step would be to prevent inlining when we're not in a const context, and let DDC perform const evaluation (if desired). For example if I refer to `Zone.root` in my method, that should remain a static get, and not be inlined.

----

EDIT: see [comment below](https://github.com/dart-lang/sdk/issues/36535#issuecomment-481067755), this isn't as bad as I thought, because CFE can't inline constants across modules. So we could do per-module canonicalization. It's not as optimal as preventing the inlining, but it's not quite as bad as I'd feared, assuming we implement per-module canonicalization for constants in DDC. We'll need to override `cacheConst` from shared_compiler to do something different in DDC's Kernel backend.

**Comment by jmesserly** [comment] 2019-04-09 01:08
FYI @jakemac53 @vsmenon @sigmundch ... I'm not sure if this will become a performance/code size issue for Flutter code, once we're running on DDC+Kernel. My hope is that it won't be too bad, but I don't have any evidence one way or the other. We should try out DDC+Kernel+CFE constants flag once it's working.

I'm not sure if this is an easy fix in CFE or not. All we'd need here is a way to control the inlining behavior.

**Comment by jmesserly** [comment] 2019-04-09 01:14
I've tentatively put this into 2.4, in hopes that this doesn't impact perf in 2.3 badly enough.

We'll need to address this before we can remove the DDC Analyzer backend. The constant optimizations in DDC were critical for our large internal apps.

**Comment by jmesserly** [comment] 2019-04-09 01:36
Looking at this more, I found several things:

- I don't think this is a huge problem yet, because CFE won't inline constants across modules currently. So we only need to canonicalize within the module, which DDC could do itself.

- If cross module canonicalization becomes an issue, I think we could address this by adding a flag to ConstantsBackend. And then in constant_evaluator, don't inline constants when that flag is set.

**Comment by sigmundch** [comment] 2019-04-09 03:06
Interesting, thanks for looping me in.

> ... CFE won't inline constants across modules currently.

To clarify, how are references to the other modules' constants represented? Is there anything different in the constant tree (e.g. a node to another constant expression?) or is it because of how constant nodes are canonicalized at the kernel level that that you can tell them apart (e.g. two references to the same constant are represented by the same node in the tree)?

For context - dart2js names constants based on the usage: we may create a  whole tree of constants in a single expression if there are no references to intermediate constants, otherwise we generate a variable for anything that's referenced in the middle. So by identifying constants that are available from other modules, could that be used in DDC to force that those constants are named and those names are available from the corresponding modules?

**Comment by jmesserly** [comment] 2019-04-09 20:15
> This should be fairly easy. How about a method on the ConstantsBackend which is given a StaticGet and returns whether it should be inlined (with a guarantee that the target variable's initializer has already been evaluated so the constant can be inspected, or perhaps with the constant value given as an extra argument)?

That sounds good to me!

> For a StaticGet that is not part of another constant (nor in constant context), it might make more sense to just leave the StaticGet as it is. WDYT?

Yeah, that'd work too.

**Comment by jmesserly** [comment] 2019-04-09 20:17
Moving to 2.3 per discussion offline. We'll just need to verify that there's no perf impact on Flutter. If not, we can move to 2.4.

**Comment by jmesserly** [comment] 2019-04-09 23:46
I sketched an API that would let the backend control things. I'm testing it now: https://dart-review.googlesource.com/c/sdk/+/98875 ... the changes are in constant_evaluator.dart and targets.dart. The API gives DDC the ability to make inlining decisions, using the same heuristic it used previously.

The API is just a sketch to capture the requirements, I'm sure it can be improved.

(As I was looking at the constant evaluator code, I realized it's not just StaticGet: other things like const variables could also get expanded many times. DDC could work around that by doing module-level canonicalization, but it's easier for us if we don't have to. So the API lets us make the decision every time a constant would be transformed.)

**Comment by askeksa-google** [comment] 2019-04-10 12:58
The changes in the constant transformer look reasonable from a quick glance. Let me know when you have something that you think makes sense as a proposed change, and I will review it.

**Comment by vsmenon** [comment] 2019-04-15 15:06
@jmesserly @jakemac53 @natebosch @kevmoo  - have we seen a noticeable perf/size regression in Flutter Gallery debug size since moving to DDK?  If not, we can drop the P1.

**Comment by vsmenon** [comment] 2019-04-15 15:09
(or any other Flutter Web app?)

**Comment by vsmenon** [comment] 2019-04-15 16:27
@jmesserly - assigning to you to re-triage.  Note: we'll likely move to full kernel files for 2.3 ( #36635 ).

**Comment by vsmenon** [comment] 2019-04-23 03:53
@askeksa-google - can you take over Jenny's CL here?  (fyi - @kmillikin )

**Comment by vsmenon** [comment] 2019-05-08 21:19
@kmillikin - the repro here (https://github.com/dart-lang/sdk/issues/36635#issuecomment-490654095) also highlights this problem.

We generate:

```
const2.main = function() {
  core.print(const$35 || (const$35 = dart.constMap(core.String, ListOfnum(), ["data", const$34 || (const$34 = dart.constList([0, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], core.num))])));
  core.print((const$72 || (const$72 = dart.constMap(core.String, ListOfnum(), ["data", const$71 || (const$71 = dart.constList([0, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], core.num))])))[$length]);
};

```

**Comment by Markzipan** [comment] 2019-05-19 18:05
@kmillikin Extending the kernel output with an auxiliary structure that holds constants (that we talked about at the summit) would help this issue - at least within a module.

**Comment by vsmenon** [comment] 2019-05-21 14:27
@aadilmaan - note: this is not marked P1, but is blocking a P1.

**Comment by aadilmaan** [comment] 2019-05-21 15:28
Marked.

**Comment by kmillikin** [comment] 2019-05-22 12:16
This needs an API change in the CFE before we can change anything in DDC.

**Closed** 2019-05-27 11:48 UTC
Labels: area-front-end, p1-high
