### ISSUE TITLE
DartAPI_GlobalTimelineGetTrace_Threaded fails at dart_api_impl_test.cc:8806

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#32856] opened 2018-04-12 09:57 UTC
Cf. this [log](https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8949465722573215376%2F%2B%2Fsteps%2Fstrong_vm_tests_shard_1_on_Windows%2F0%2Fstdout), on [vm-kernel-win-release-x64 build 569](https://ci.chromium.org/p/dart/builders/luci.dart.ci/vm-kernel-win-release-x64/569), the test `vm/cc/DartAPI_GlobalTimelineGetTrace_Threaded` fails with an error that seems to be a C++ level assertion violation:

```
FAILED: dartk-vm release_x64 vm/cc/DartAPI_GlobalTimelineGetTrace_Threaded
Expected: Pass
Actual: Fail
--- Command "run_vm_unittest" (took 15.000024s):
set DART_CONFIGURATION=ReleaseX64 & out\ReleaseX64\run_vm_tests --dfe=out/ReleaseX64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags --use-dart-frontend --strong DartAPI_GlobalTimelineGetTrace_Threaded
exit code:
255
stdout:
Running test: DartAPI_GlobalTimelineGetTrace_Threaded
Done: DartAPI_GlobalTimelineGetTrace_Threaded
stderr:
c:\b\s\w\ir\cache\builder\sdk\runtime\vm\dart_api_impl_test.cc: 8806: error: expected <""name":"TestVMDuration""> to be a substring of <"{"name":"thread_name","ph":"M","pid":10636,"tid":7216,"args":{"name":"Timeline test thread (7216)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":7020,"args":{"name":"Dart ThreadPool Worker (7020)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":316,"args":{"name":"Dart ThreadPool Worker (316)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":2004,"args":{"name":"Dart ThreadPool Worker (2004)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":1988,"args":{"name":"Dart ThreadPool Worker (1988)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":10976,"args":{"name":"Dart_Initialize (10976)","mode":"basic"}},{"name":"CompileFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794802837,"ph":"X","dur":174,"args":{"function":"dart.async_Future_Future.microtask","isolateNumber":"989639228"}},{"name":"ParseFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803024,"ph":"X","dur":75,"args":{"function":"scheduleMicrotask","isolateNumber":"989639228"}},{"name":"BuildFlowGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803101,"ph":"X","dur":19,"args":{"isolateNumber":"989639228"}},{"name":"CompileGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803123,"ph":"X","dur":49,"args":{"isolateNumber":"989639228"}},{"name":"FinalizeCompilation","cat":"Compiler","tid":316,"pid":10636,"ts":55794803172,"ph":"X","dur":18,"args":{"isolateNumber":"989639228"}},{"name":"CompileFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803019,"ph":"X","dur":173,"args":{"function":"dart.async_::_scheduleMicrotask","isolateNumber":"989639228"}},{"name":"ParseFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803199,"ph":"X","dur":75,"args":{"function":"_rootScheduleMicrotask@7048458","isolateNumber":"989639228"}},{"name":"BuildFlowGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803276,"ph":"X","dur":12,"args":{"isolateNumber":"989639228"}},{"name":"CompileGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803291,"ph":"X","dur":31,"args":{"isolateNumber":"989639228"}},{"name":"FinalizeCompilation","cat":"Compiler","tid":316,"pid":10636,"ts":55794803323,"ph":"X","dur":17,"args":{"isolateNumber":"989639228"}},{"name":"CompileFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803194,"ph":"X","dur":148,"args":{"function":"dart.async_::__rootScheduleMicrotask@7048458","isolateNumber":"989639228"}},{"name":"ParseClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803379,"ph":"X","dur":33,"args":{"class":"_AsyncCallbackEntry@7048458","isolateNumber":"989639228"}},{"name":"CompileClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803374,"ph":"X","dur":52,"args":{"class":"Library:'dart:async' Class: _AsyncCallbackEntry@7048458","isolateNumber":"989639228"}},{"name":"ParseClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803471,"ph":"X","dur":21,"args":{"class":"_AsyncRun@7048458","isolateNumber":"989639228"}},{"name":"ParseClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803493,"ph":"X","dur":32,"args":{"class":"_AsyncRun@7048458","isolateNumber":"989639228"}},{"name":"CompileClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803467,"ph":"X","dur":69,"args":{"class":"Library:'dart:async' Class: _AsyncRun@7048458","isolateNumber":"989639228"}},{"name":"ParseFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803348,"ph":"X","dur":203,"args":{"function":"_scheduleAsyncCallback@7048458","isolateNumber":"989639228"}},{"name":"BuildFlowGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803552,"ph":"X","dur":23,"args":{"isolateNumber":"989639228"}},{"name":"CompileGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803578,"ph":"X","dur":68,"args":{"isolateNumber":"989639228"}},{"name":"FinalizeCompilation","cat":"Compiler","tid":316,"pid":10636,"ts":55794803647,"ph":"X","dur":15,"args":{"isolateNumber":"989639228"}},{"name":"CompileFunction","cat":"Com
c:\b\s\w\ir\cache\builder\sdk\runtime\vm\dart_api_impl_test.cc: 8809: error: expected <""function":"::_main""> to be a substring of <"{"name":"thread_name","ph":"M","pid":10636,"tid":7216,"args":{"name":"Timeline test thread (7216)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":7020,"args":{"name":"Dart ThreadPool Worker (7020)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":316,"args":{"name":"Dart ThreadPool Worker (316)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":2004,"args":{"name":"Dart ThreadPool Worker (2004)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":1988,"args":{"name":"Dart ThreadPool Worker (1988)","mode":"basic"}},{"name":"thread_name","ph":"M","pid":10636,"tid":10976,"args":{"name":"Dart_Initialize (10976)","mode":"basic"}},{"name":"CompileFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794802837,"ph":"X","dur":174,"args":{"function":"dart.async_Future_Future.microtask","isolateNumber":"989639228"}},{"name":"ParseFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803024,"ph":"X","dur":75,"args":{"function":"scheduleMicrotask","isolateNumber":"989639228"}},{"name":"BuildFlowGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803101,"ph":"X","dur":19,"args":{"isolateNumber":"989639228"}},{"name":"CompileGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803123,"ph":"X","dur":49,"args":{"isolateNumber":"989639228"}},{"name":"FinalizeCompilation","cat":"Compiler","tid":316,"pid":10636,"ts":55794803172,"ph":"X","dur":18,"args":{"isolateNumber":"989639228"}},{"name":"CompileFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803019,"ph":"X","dur":173,"args":{"function":"dart.async_::_scheduleMicrotask","isolateNumber":"989639228"}},{"name":"ParseFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803199,"ph":"X","dur":75,"args":{"function":"_rootScheduleMicrotask@7048458","isolateNumber":"989639228"}},{"name":"BuildFlowGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803276,"ph":"X","dur":12,"args":{"isolateNumber":"989639228"}},{"name":"CompileGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803291,"ph":"X","dur":31,"args":{"isolateNumber":"989639228"}},{"name":"FinalizeCompilation","cat":"Compiler","tid":316,"pid":10636,"ts":55794803323,"ph":"X","dur":17,"args":{"isolateNumber":"989639228"}},{"name":"CompileFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803194,"ph":"X","dur":148,"args":{"function":"dart.async_::__rootScheduleMicrotask@7048458","isolateNumber":"989639228"}},{"name":"ParseClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803379,"ph":"X","dur":33,"args":{"class":"_AsyncCallbackEntry@7048458","isolateNumber":"989639228"}},{"name":"CompileClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803374,"ph":"X","dur":52,"args":{"class":"Library:'dart:async' Class: _AsyncCallbackEntry@7048458","isolateNumber":"989639228"}},{"name":"ParseClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803471,"ph":"X","dur":21,"args":{"class":"_AsyncRun@7048458","isolateNumber":"989639228"}},{"name":"ParseClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803493,"ph":"X","dur":32,"args":{"class":"_AsyncRun@7048458","isolateNumber":"989639228"}},{"name":"CompileClass","cat":"Compiler","tid":316,"pid":10636,"ts":55794803467,"ph":"X","dur":69,"args":{"class":"Library:'dart:async' Class: _AsyncRun@7048458","isolateNumber":"989639228"}},{"name":"ParseFunction","cat":"Compiler","tid":316,"pid":10636,"ts":55794803348,"ph":"X","dur":203,"args":{"function":"_scheduleAsyncCallback@7048458","isolateNumber":"989639228"}},{"name":"BuildFlowGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803552,"ph":"X","dur":23,"args":{"isolateNumber":"989639228"}},{"name":"CompileGraph","cat":"Compiler","tid":316,"pid":10636,"ts":55794803578,"ph":"X","dur":68,"args":{"isolateNumber":"989639228"}},{"name":"FinalizeCompilation","cat":"Compiler","tid":316,"pid":10636,"ts":55794803647,"ph":"X","dur":15,"args":{"isolateNumber":"989639228"}},{"name":"CompileFunction","cat":"Compil
--- Re-run this test:
python tools/test.py -m release -c dartk --strong --output-directory C:\b\s\w\iohbjmsl vm/cc/DartAPI_GlobalTimelineGetTrace_Threaded
```

**Comment by eernstg** [comment] 2018-04-12 10:12
Note that we have similar failures in earlier builds (C++ level error message, looks identical):

- Build 563: dartk-vm release_x64 vm/cc/DartAPI_GlobalTimelineGetTrace
- Build 545: dartk-vm release_x64 vm/cc/DartAPI_GlobalTimelineGetTrace

**Comment by bkonyi** [comment] 2018-06-15 17:42
Still unable to reproduce on my Linux and Windows machines. Closing for now.

**Closed by bkonyi** 2018-06-15 17:42 UTC
Labels: Type: bug, area-vm, gardening
