### ISSUE TITLE
Fasta doesn't support tear-off invocation with type arguments

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31260] opened 2017-11-01 19:10 UTC
```
$ cat <<EOF >test.dart
class A {}

main() {
  var x = new A();
  (x.foo)<int>();
}
EOF
$ DART_CONFIGURATION=ReleaseX64 ./pkg/front_end/tool/fasta compile test.dart  
test.dart:5:14: Error: Expected ';' before this.
  (x.foo)<int>();
             ^
test.dart:5:14: Error: Expected an identifier, but got '>'.
  (x.foo)<int>();
             ^
test.dart:5:16: Error: Expected an identifier, but got ')'.
  (x.foo)<int>();
               ^
test.dart:5:16: Warning: Getter not found: ''.
  (x.foo)<int>();
               ^
test.dart:5:14: Warning: Getter not found: ''.
  (x.foo)<int>();
             ^
```

**Comment by sjindel-google** [comment] 2017-11-01 19:12
This is preventing us from running `language_2/generic_no_such_method_dispatcher_test`, which in turn prevented us from recognizing bug #31261.

**Comment by sjindel-google** [comment] 2017-11-01 19:15
When is fixed, we can remove the test `language_2/generic_no_such_method_dispatcher_simple_test`.

**Comment by peter-ahe-google** [comment] 2017-11-02 12:24
This is a duplicate of #30208.

**Closed** 2017-11-02 12:29 UTC
Labels: area-front-end, front-end-fasta, Resolution: duplicate
