### ISSUE TITLE
dart2js: null-check on result of package:js's getProperty is compiled to constant

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#28462] opened 2017-01-22 09:06 UTC
`== null` checks performed on the result of the `getProperty` method always evaluate to `false`.

You can see in the dart2js output that this is due to the expression being compiled to `false`. Example:

* test.dart
    ```dart
    @JS()
    library test;

    import 'package:js/js.dart';
    import 'package:js/js_util.dart';

    @JS()
    external getObject();

    main() {
      print('foo check');

      var hasNullFoo = getProperty(getObject(), 'foo') == null;
      print(hasNullFoo);
    }
    ```
* out.js (only the relevant part)
    ```js
      {
        "^": "",
        main: [function() {
          P.print("foo check");
          self.getObject();
          P.print(false);
        }, "call$0", "test__main$closure", 0, 0, 0]
      }
    ```

The inverse happens for `!= null`: the result is assumed to always be `true` in compiled code.

However, other tests, including is-checks and equality-checks with non-null values, work as expected:

* test.dart
    ```dart
    @JS()
    library test;

    import 'package:js/js.dart';
    import 'package:js/js_util.dart';

    @JS()
    external getObject();

    main() {
      print('foo check');

      var hasTwoFoo = getProperty(getObject(), 'foo') == 2;
      print(hasTwoFoo);
    }
    ```
* out.js
    ```js
      {
        "^": "",
        main: [function() {
          P.print("foo check");
          P.print(J.$eq$(self.getObject().foo, 2));
        }, "call$0", "test__main$closure", 0, 0, 0]
      }
    ```

I tested and reproduced this bug in Dart versions: 1.19.1, 1.22.1, and 1.22.0-dev.9.0

**Comment by greglittlefield-wf** [comment] 2017-01-22 19:02
Also, is there a recommended/stable workaround for this issue?

**Comment by daniel-v** [comment] 2017-04-06 18:30
This issue seemed to show up in Angular 2.

**Comment by hterkelsen** [comment] 2017-04-06 20:06
This is a duplicate of https://github.com/dart-lang/sdk/issues/29076

**Closed by hterkelsen** 2017-04-06 20:06 UTC
Labels: area-js_interop
