### ISSUE TITLE
Quick assist: allow inverting terms in conditional (c?x:y) expressions

### ISSUE THREAD

**Issue by ChristianKleineidam** [dart-lang/sdk#45853] opened 2021-04-28 11:10 UTC
If I use the following if/else construct quick assist offers me the option "Invert 'if' statement":
```
if (c!=1){
  return x;
}else{
  return y;
}
```
That option converts it into:
```
if (c==1){
  return y;
}else{
  return x;
}
```
It would be valuable to have the same quick assist for constructs like:
```
return c!=1?x:y;
```
Which would convert it into:
```
return c==1?y:x;
```

**Comment by asashour** [comment] 2021-08-24 13:47
Duplicate of #45669, although this is clearer.

**Comment by Levi-Lesches** [comment] 2021-08-25 02:23
I commented there, but I can try that after I'm done with some other quick-fix improvements. No promises though.

**Closed** 2024-09-30 19:38 UTC
Labels: area-analyzer, P3, analyzer-quick-fix, type-enhancement
