### ISSUE TITLE
case doesn't understand that both if and else end in return

### ISSUE THREAD

**Issue by dskloetg** [dart-lang/sdk#35390] opened 2018-12-12 15:24 UTC
```
switch (foo) {
  case 1:
    if (bar) {
      return 2;
    } else {
      return 3;
    }
}
```

The analyzer gives the following error for this code:
`The last statement of the 'case' should be 'break', 'continue', 'rethrow', 'return' or 'throw'. #case_block_not_terminated`

But I would argue that this case does have return as its last statement in any way that matters.

**Comment by dskloetg** [comment] 2018-12-12 15:37
I use whatever blaze uses on google3.

**Comment by dskloetg** [comment] 2018-12-12 15:40
Sorry, apparently you need a case after the offending case.
This fails on dartpad, although with a different error (`Error: Switch case may fall through to the next case.`)

```
int main()  {
  int foo = 1;
  bool bar = true;
  switch (foo) {
    case 1:
      if (bar) {
        return 2;
      } else {
        return 3;
      }
    case 2:
      return 4;
  }
}
```

**Comment by zoechi** [comment] 2018-12-12 15:41
Ok, now I can reproduce.

**Comment by bwilkerson** [comment] 2018-12-12 16:07
This is behaving as defined in the specification:

> Let _s_ be the last statement of the statement sequence _s_<sub>k</sub>. If _s_ is a non-empty block statement, let _s_ instead be the last statement of the block statement. It is a compile-time error if _s_ is not a `break`, `continue`, `rethrow` or `return` statement or an expression statement where the expression is a `throw` expression.

**Comment by lrhn** [comment] 2018-12-12 16:17
It's working as specified. It's still highly annoying and I hope we can fix it at some point.

**Comment by srawlins** [comment] 2019-10-21 17:36
Duplicate of https://github.com/dart-lang/sdk/issues/28042

**Closed by srawlins** 2019-10-21 17:36 UTC
Labels: area-language, core-a, type-enhancement
