### ISSUE TITLE
Shutdown Race in MallocHooks

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28804] opened 2017-02-17 03:57 UTC
The call to MallocHookScope::DestroyMallocHookFlag() in void MallocHooks::TearDown() races with the creation of MallocHookScopes in MallocHooksState::RecordAllocHook() and MallocHooksState::RecordFreeHook(), resulting in hitting the assert in ~MallocHookScope().

RecordAllocHook() need to find a way to take the lock before doing anything else, and should also first check that MallocHooksState::Active() is true.

**Comment by mraleph** [comment] 2017-02-17 10:31
This is a duplicate of #28746

**Closed** 2017-02-17 10:34 UTC
Labels: area-vm, Type: bug
