### ISSUE TITLE
VM failures on co19/LanguageFeatures/Generic-functions-as-type-args/class_A03_t01

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#45465] opened 2021-03-25 10:05 UTC
The VM fails `co19/LanguageFeatures/Generic-functions-as-type-args/class_A03_t01` in various configurations:
```
dartk-strong-mac-debug-x64
dartk-strong-linux-release-x64
dartk-weak-asserts-mac-release-x64
dartk-weak-asserts-linux-release-ia32
dartk-strong-linux-debug-ia32
dartk-weak-asserts-win-debug-x64
dartk-strong-win-debug-x64
dartk-weak-asserts-linux-debug-ia32
dartk-strong-win-release-x64
dartk-strong-linux-release-simarm
dartk-weak-asserts-linux-release-x64
dartk-weak-asserts-linux-release-simarm64
dartk-weak-asserts-win-release-x64
dartk-weak-asserts-win-release-ia32
dartk-strong-linux-release-simarm64
dartk-strong-win-release-ia32
dartk-weak-asserts-linux-release-simarm
dartk-weak-asserts-linux-debug-x64
dartk-strong-linux-release-ia32
dartk-weak-asserts-mac-debug-x64
dartk-strong-linux-debug-x64
dartk-strong-mac-release-x64
```

The failure logs are odd since they only report an unexpected exit code, for instance `-1073741571` in https://dart-ci.appspot.com/log/any/dartk-weak-asserts-win-release-x64/166/co19/LanguageFeatures/Generic-functions-as-type-args/class_A03_t01 and `-11` in https://dart-ci.appspot.com/log/any/dartk-weak-asserts-linux-debug-ia32/165/co19/LanguageFeatures/Generic-functions-as-type-args/class_A03_t01

**Comment by a-siva** [comment] 2021-03-25 18:14
This is a duplicate of https://github.com/dart-lang/sdk/issues/45443

**Closed by a-siva** 2021-03-25 18:14 UTC
Labels: area-vm, closed-duplicate
