### ISSUE TITLE
[cfe] Extension types with the 'type' keyword unsupported on CFE

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#45850] opened 2021-04-27 23:39 UTC
CFE might be the wrong component here as this needs to be parseable first before the kernel can be formed, but extension types with the 'type' keyword are unsupported.

For example,

```
class Bar {}

extension type Foo on Bar {}

void main() {}
```

```
dart --enable-experiment=extension-types <test_file>

<test_file>:3:11: Error: Expected 'on' after this.
extension type Foo on Bar {}
          ^^^^
<test_file>:3:20: Error: Unexpected token 'on'.
extension type Foo on Bar {}
                   ^^
<test_file>:3:16: Error: Type 'Foo' not found.
extension type Foo on Bar {}
               ^^^
```

Do we have an existing tracking issue for this to be added to the grammar under the experiment flag? Should I be filing this elsewhere?

cc @stefantsov @johnniwinther

**Comment by johnniwinther** [comment] 2021-04-28 05:58
The parser is part of the CFE, so this is the right place for the issue.

**Comment by lrhn** [comment] 2021-04-30 11:24
Remember that the feature is not yet designed or decided on, so any implementation is going to be exploratory.

**Comment by srujzs** [comment] 2021-04-30 23:29
Yeah, good point, that does have me worried if that means I'm asking for double work from the CFE and myself if I were to work on a prototype using this feature.

**Comment by stefantsov** [comment] 2021-05-04 10:49
> Yeah, good point, that does have me worried if that means I'm asking for double work from the CFE and myself if I were to work on a prototype using this feature.

Nope, these kinds of issues are helpful because they show what sub-features of extension types the backends are more interested in at the moment. Please keep them coming, @srujzs!

**Comment by stefantsov** [comment] 2021-05-26 15:38
The issue is being worked on at https://dart-review.googlesource.com/c/sdk/+/201268.

**Comment by stefantsov** [comment] 2021-07-29 13:10
The CL has landed some time ago.

**Closed by stefantsov** 2021-07-29 13:10 UTC
Labels: area-front-end
