### ISSUE TITLE
How to analyze one file?

### ISSUE THREAD

**Issue by fantasy525** [dart-lang/sdk#39999] opened 2020-01-07 02:39 UTC
Hi!

This tracker is for issues related to:

* Analyzerdar

* Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"

I use this:
`dartanalyzer lib/main_t.dart --format --no-hints --no-lints`

But the result shows some other file errors and hints
![image](https://user-images.githubusercontent.com/22516157/71864047-adfa9980-3139-11ea-9e87-8887ec40e356.png)
So what's problem?Thank you!

**Comment by bwilkerson** [comment] 2020-01-07 15:09
That looks like a bug to me. The `dartanalyzer` tool should produce diagnostics for only the files specified on the command-line.

That said, it's possible that this has been fixed. It appears that you're currently using version 2.2; you might want to update to using a later version. Version 2.7 has been released, and there have been a lot of improvements in the last year. If you continue to see a problem after updating, please re-open this issue or create a new one.

**Comment by fantasy525** [comment] 2020-01-08 03:02
@bwilkerson Hi，I have upgraded dart to 2.7.0，but But it still analyzes many other files，Why does it analyze the other files I imported?The file I want to analyze imports some other files

**Comment by bwilkerson** [comment] 2020-01-08 05:32
It has to analyze all of the files that are imported in order to compute all the required type information. But it shouldn't be printing diagnostics from those imported files, only the ones explicitly given on the command line.

**Comment by fantasy525** [comment] 2020-01-08 05:40
> It has to analyze all of the files that are imported in order to compute all the required type information. But it shouldn't be printing diagnostics from those imported files, only the ones explicitly given on the command line.

Yes,It should print  diagnostics only the one  given on the command line.

**Comment by srawlins** [comment] 2020-06-17 04:52
Thanks for reporting this! Please follow along at the duplicate issue.

**Comment by srawlins** [comment] 2020-06-17 04:52
Duplicate of https://github.com/dart-lang/sdk/issues/35284

**Closed by srawlins** 2020-06-17 04:52 UTC
Labels: area-analyzer
