### ISSUE TITLE
dart2native requires libc?

### ISSUE THREAD

**Issue by siegesmund** [dart-lang/sdk#39296] opened 2019-11-08 12:38 UTC
dart2native seems to require the presence of several libraries, including libc, as referenced in this issue: https://github.com/dart-lang/sdk/issues/39253. Dart2native thus doesn't seem to provide the promise of a truly self contained binary as is stated in its' documentation. 

While dart2native offers big advantages (THANK YOU Dart Team!), this prevents dart2native executables from being run in standard alpine linux containers (afaik, a key use case for dart2native). 

It would be helpful if this were clearer in the documentation.

**Comment by agilob** [comment] 2019-11-09 11:37
Simple "hello world" is 7.6Mb and has a few links to libraries. I know a few docker images with go app in them that are that size. Not great, but also not bad considering this is first version of native compilation. 

```
Projects/dart-tut  l                                                                                                                                    ✔  11:33:53
total 7.6M
31 Nov  9 11:18 main.dart
7.6M Nov  9 11:23 main.exe

Projects/dart-tut  cat main.dart                                                           
id main() => print("hello world");

Projects/dart-tut  ldd main.exe                                                            
linux-vdso.so.1 (0x00007ffea25cf000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f0e88f77000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f0e897c9000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f0e88e31000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f0e88e0f000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f0e88e0a000)
```

**Comment by siegesmund** [comment] 2019-11-09 13:17
The issue I am raising is not the size of the Dart executable, but rather the documentation describing the executable as stand alone. 

When you containerize the application, the tiny Alpine Linux container that will happily run a go binary fails with the dart executable because it lacks the Dart executable's dependencies. If you use one of Google's Dart docker containers, the container + executable clock in at ~800 MB. So you have to roll your own image or use a third party image that has manually installed libc on Alpine to get the container + executable size back down to a reasonable size. This is not a big deal and exposing dart2native is a big step forward. I am just suggesting that being clearer about what dart2native outputs will save developer time and help move the ecosystem forward, faster.

**Comment by filipproch** [comment] 2019-11-17 12:36
I agree with this, it should definitely be at least mentioned in the documentation of `dart2native` as I personally spent some time solving this issue.

Looking to the future, it would be amazing if this limitation was removed as it would allow using the `FROM scratch` and getting the Docker image size even smaller.

For those of you solving the same problem here (cc: @siegesmund ), I ended up using the
https://github.com/jeanblanchard/docker-alpine-glibc

**Comment by mkustermann** [comment] 2019-11-21 18:06
/cc @mit-mit 

We have been talking about providing a base docker image containing the minimal requirements for dart2native-created executables (which would include the needed shared libraries)

Something like this:
```Dockerfile
# Make a self-contained executable out of the application.
FROM google/dart AS dart-runtime
WORKDIR /app
ADD pubspec.* /app/
RUN pub get
ADD bin /app/bin/
ADD lib /app/lib/
RUN dart2native /app/bin/server.dart

# Build the bare minimum image.
FROM scratch
COPY --from=dart-runtime /app/bin/server.exe /app/bin/server.exe
COPY --from=dart-runtime /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libm.so.6
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libpthread.so.0
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so.2
ENTRYPOINT ["/app/bin/server.exe"]
```

**Comment by mit-mit** [comment] 2019-11-22 08:27
For an example, see https://github.com/dart-lang/dartbug.com

**Comment by siegesmund** [comment] 2019-11-22 13:41
@mkustermann that is a perfect idea.

**Comment by a14n** [comment] 2019-11-22 14:11
I just try the Dockerfile proposal with the following code:

```dart
import 'dart:io';
import 'dart:convert';

void main() async {
  final request =
      await HttpClient().getUrl(Uri.parse('https://dart.dev'));
  final response = await request.close();
  response.transform(Utf8Decoder()).listen(print);
}
```

but got the error:

```
Unhandled exception:
SocketException: Failed host lookup: 'dart.dev' (OS Error: Name or service not known, errno = -2)
```

Is something missing?

**Comment by mkustermann** [comment] 2019-11-22 14:15
@a14n 

The Dart VM uses normal POSIX apis for network functions. That includes DNS lookups.

The functions are implemented by the standard shared libraries. Those need a few configuration files (e.g. `/etc/resolv.conf`, `/etc/nsswitch.conf`) which can be added to the minimal image the same way as the `so` files. It's probably not very hard to identify which ones exactly.

Once we make a base docker image, these will of course be included.

**Comment by mkustermann** [comment] 2019-11-28 09:06
The more precise runtime dependencies of `libc` for DNS lookups are:

```Dockerfile
FROM scratch

# For name-service order configuration, predefined hostnames like "localhost", dns server IPs
COPY --from=dart-runtime /etc/nsswitch.conf /etc/nsswitch.conf
COPY --from=dart-runtime /etc/hosts /etc/hosts
COPY --from=dart-runtime /etc/resolv.conf /etc/resolv.conf

# For performing the actual DNS queries to DNS servers
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libnss_dns.so.2 /lib/x86_64-linux-gnu/libnss_dns.so.2
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libresolv.so.2 /lib/x86_64-linux-gnu/libresolv.so.2

...
```
(in addition to `Dockerfile` mentioned in https://github.com/dart-lang/sdk/issues/39296#issuecomment-557204865)

**Comment by JSANL** [comment] 2019-12-14 21:10
> The more precise runtime dependencies of `libc` for DNS lookups are:
> 
> ```dockerfile
> FROM scratch
> 
> # For name-service order configuration, predefined hostnames like "localhost", dns server IPs
> COPY --from=dart-runtime /etc/nsswitch.conf /etc/nsswitch.conf
> COPY --from=dart-runtime /etc/hosts /etc/hosts
> COPY --from=dart-runtime /etc/resolv.conf /etc/resolv.conf
> 
> # For performing the actual DNS queries to DNS servers
> COPY --from=dart-runtime /lib/x86_64-linux-gnu/libnss_dns.so.2 /lib/x86_64-linux-gnu/libnss_dns.so.2
> COPY --from=dart-runtime /lib/x86_64-linux-gnu/libresolv.so.2 /lib/x86_64-linux-gnu/libresolv.so.2
> 
> ...
> ```
> 
> (in addition to `Dockerfile` mentioned in [#39296 (comment)](https://github.com/dart-lang/sdk/issues/39296#issuecomment-557204865))

Oh my god, I am new to docker and spent hours on this issue today... And I even glanced over this thread before I hit it🙄.  
At least I got it fixed now with your help, thank you!

**Comment by sebthom** [comment] 2020-05-16 19:20
Dart 2.8 additionally requires:
```dockerfile
COPY --from=dart-runtime /lib/x86_64-linux-gnu/librt.so.1 /lib/x86_64-linux-gnu/librt.so.1
```

This works for me:
```dockerfile
FROM google/dart:2.8 AS dart-runtime

WORKDIR /app

ADD pubspec.* ./
RUN pub get
ADD bin bin
ADD lib lib
RUN pub get --offline
RUN dart2native /app/bin/main.dart -o /app/bin/main

FROM scratch
COPY --from=dart-runtime /app/bin/main /app/bin/main
COPY --from=dart-runtime /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so.2
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libm.so.6
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libpthread.so.0
COPY --from=dart-runtime /lib/x86_64-linux-gnu/librt.so.1 /lib/x86_64-linux-gnu/librt.so.1

# For name-service order configuration, predefined hostnames like "localhost", dns server IPs
COPY --from=dart-runtime /etc/nsswitch.conf /etc/nsswitch.conf
COPY --from=dart-runtime /etc/hosts /etc/hosts
COPY --from=dart-runtime /etc/resolv.conf /etc/resolv.conf

# For performing the actual DNS queries to DNS servers
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libnss_dns.so.2 /lib/x86_64-linux-gnu/libnss_dns.so.2
COPY --from=dart-runtime /lib/x86_64-linux-gnu/libresolv.so.2 /lib/x86_64-linux-gnu/libresolv.so.2

ENTRYPOINT ["/app/bin/main"]

EXPOSE 8080
```

**Comment by subfuzion** [comment] 2020-11-13 13:07
I've consolidated everything into this [repo](https://github.com/subfuzion/dart-docker-slim), and added tests and examples for creating slim images for both JIT- and AOT-compiled servers. The image is published on Docker Hub at [subfuzion/dart:slim](https://hub.docker.com/repository/docker/subfuzion/dart). There's also a Medium blog [post](https://medium.com/google-cloud/build-slim-docker-images-for-dart-apps-ee98ea1d1cf7) that gives a bit more detail.

**Comment by mkustermann** [comment] 2020-12-29 15:46
This issue was filed due to the `dart2native` compiled binary requiring libc and other libraries. This is intentional for a number of reasons (e.g. we want Dart applications to be able to use `dart:ffi` which requires a dynamic linker which implies we cannot statically link everything).

The list of libraries needed is relatively stable across releases and there are some suggestions above on how to build small docker containers with the necessary libs.

To avoid more users running into this problem we could consider publishing a Dart Team supported docker base image which can be used to run `dart2native` applications. I'll defer to @mit-mit to decide whether we want to do that.

Since we don't intend to change the fact that our `dart2native` compiled binaries require libs (which is the topic of the original issue here) I hope it's all right to close this bug as "working as intended".

**Closed by mkustermann** 2020-12-29 15:46 UTC
Labels: area-vm, vm-native
