### ISSUE TITLE
corelib/list_unmodifiable_test is flaky with dart2js

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28712] opened 2017-02-09 21:39 UTC
See [this log](https://build.chromium.org/p/client.dart/builders/dart2js-linux-drt-csp-minified-be/builds/2258/steps/dart2js%20drt%20tests/logs/stdio) for example.

```
FAILED: dart2js-drt release_x64 corelib/list_unmodifiable_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[dart2js]:

stdout:
Dart file (/b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/tests/corelib/list_unmodifiable_test.dart) compiled to JavaScript: out/ReleaseX64/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js

CommandOutput[content_shell]:

stdout:
#READY
CONSOLE MESSAGE: line 78: {
  "type": "debug",
  "value": "test_controller.js started",
  "timestamp": 0
}
CONSOLE MESSAGE: line 78: {
  "type": "print",
  "value": "dart-calling-main",
  "timestamp": 0.132
}
CONSOLE MESSAGE: line 78: {
  "type": "sync_exception",
  "value": "Exception: Expect.equals(expected: <aY>, actual: <cx>) fails.\nStack: Expect.equals(expected: <aY>, actual: <cx>) fails.\n    at dart.b (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:2260:3)\n    at dart.cZ (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:3634:24)\n    at dart.dg (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:3617:52)\n    at cn.dart.cn.$2 (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:3914:3)\n    at M.dart.M.N (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:3770:3)\n    at M.dart.M.W (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:3726:6)\n    at M.dart.M.v (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:3722:6)\n    at dart.eF (http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:3651:3)\n    at dartMainRunner (http://127.0.0.1:35507/root_dart/tools/testing/dart/test_controller.js:311:5)\n    at http://127.0.0.1:35507/root_build/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js:4305:39",
  "timestamp": 0.731
}
Content-Type: text/plain
Running /b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/tests/corelib/list_unmodifiable_test.dart

FAIL
#EOF
#EOF


stderr:
[6154:6154:0209/045549:9189451761636:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[6154:6154:0209/045549:9189451811887:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
Xlib:  extension "RANDR" missing on display ":99".
Xlib:  extension "RANDR" missing on display ":99".
[6207:6207:0209/045549:9189452369454:ERROR:renderer_main.cc(200)] Running without renderer sandbox
#EOF


To retest, run:  /b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/tools/sdks/linux/dart-sdk/bin/dart /b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/tools/testing/dart/http_server.dart -p 35507 -c 54847 --build-directory=/b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/out/ReleaseX64/ --runtime=drt --csp --packages=/b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/.packages

Command[dart2js]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --minify --csp --packages=/b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/.packages --out=/b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/out/ReleaseX64/generated_compilations/dart2js-minified-csp-sdk/tests_corelib_list_unmodifiable_test/test.js /b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/tests/corelib/list_unmodifiable_test.dart
Took 0:00:02.027479

Command[content_shell]: DART_CONFIGURATION=ReleaseX64 /b/build/slave/dart2js-linux-drt-csp-minified-be/build/sdk/client/tests/drt/content_shell --no-timeout --dump-render-tree --disable-gpu http://127.0.0.1:35507/root_build/generated_tests/dart2js-drt-minified-sdk/tests_corelib_list_unmodifiable_test/test.html?crossOriginPort=54847
Took 0:00:02.253682

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rdrt --minified --csp -t240 --use-sdk --dart2js-batch --reset-browser-configuration corelib/list_unmodifiable_test
```

**Comment by whesse** [comment] 2017-02-09 23:37
On which platforms is this test flaky? How many times have we seen it flake?
In which modes?  This would be useful in reproducing the failure, and knowing what platforms to try on.

**Comment by nex3** [comment] 2017-02-09 23:38
So far I've only seen it flake on dart2js-linux-drt-csp-minified-be, but the error doesn't seem likely to be unique to that configuration.

**Comment by sigmundch** [comment] 2017-02-10 22:30
I have slight preference to only disable it where it has been seen (in this case with --minified + --csp), but I understand that in this case it is not clear.

From a quick look the issue appears the test fails when comparing the runtimeType of two exceptions. The rest doesn't report more details of when this happens, so we should first add a detailed reason for the failure to the test before we investigate futher.

**Comment by mraleph** [comment] 2017-11-16 12:05
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by sigmundch** [comment] 2017-11-16 18:35
Once support to look though flaky results come available, we will investigate this further. Meanwhile we are keeping this issue open.

**Closed** 2018-06-22 00:11 UTC
Labels: area-dart2js
