### ISSUE TITLE
File.writeAsBytes doesn't work with UnmodifiableUint8ListView

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/sdk#41029] opened 2020-03-13 09:32 UTC
From signature it seems that `File.writeAsBytes` accepts a `List<int>`, and it seems that `UnmodifiableUint8ListView` implemements `Uint8List`.

However, the following example:
```dart
import 'dart:io';
import 'dart:convert';
import 'dart:typed_data' show UnmodifiableUint8ListView;

void main() async {
  await File('test-file').writeAsBytes(
    UnmodifiableUint8ListView(utf8.encoder.convert('hello world')),
  );
}
```
Throws
```
Unhandled exception:
Invalid argument(s): writeFrom failed: test-file
#0      _RandomAccessFile.writeFrom.<anonymous closure> (dart:io/file_impl.dart:858:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by sortie** [comment] 2020-03-13 10:52
The problem is that UnmodifiableUint8ListView implements Uint8List but is not actually a Uint8List as the VM expects. The problem occurs in `_ensureFastAndSerializableByteData`:

```dart
_BufferAndStart _ensureFastAndSerializableByteData(
    List<int> buffer, int start, int end) {
  if (buffer is Uint8List || buffer is Int8List) {
    return new _BufferAndStart(buffer, start);
  }
  int length = end - start;
  var newBuffer = new Uint8List(length);
  int j = start;
  for (int i = 0; i < length; i++) {
    newBuffer[i] = buffer[j];
    j++;
  }
  return new _BufferAndStart(newBuffer, 0);
}
```

The `Uint8List` path here is taken despite that the VM does not know how to serialize a `UnmodifiableUint8ListView`.

The bug can be fixed by falling back to the slow path if it's not exactly a `Uint8List` or `Int8List`. Is .runtimeType the best way of doing such a strict check?

It does feel a bit surprising in a sense that a `UnmodifiableUint8ListView` would be slower than a `Uint8List`. Optionally we can maybe find a way of handling it efficiently. We could perhaps access the _list getter somehow, although it's in `dart:typed_data`  and this is `dart:io`. Alternatively the VM can learn how to serialize the `UnmodifiableUint8ListView` and `UnmodifiableInt8ListView` classes.

@lrhn Might you have any thoughts here?

**Comment by lrhn** [comment] 2020-03-13 11:03
> Is `.runtimeType` the best way of  ....

No. Using `runtimeType` is never the best way of anything.

In the VM, to check the exact class of an object, you should check the class ID of the object instead. That's actually trustworthy. I found an example at:
https://github.com/dart-lang/sdk/blob/a75ffc89566a1353fb1a0f0c30eb805cc2e8d34c/sdk/lib/_internal/vm/lib/string_patch.dart#L128-L131
(but not for `Uint8List`, that code just does an `is` test for `Uint8List`).

Talk to @mkustermann about the unmodifiable typed data, I believe he's working on making them better.

**Comment by mkustermann** [comment] 2020-03-13 14:08
+1 to what @lrhn  says: If you want code to only work with `_Uint8Array`, `_Uint8ArrayView`, `_ExternalUint8Array` then you have to use `ClassID.getId()`.

**Closed** 2020-05-13 13:50 UTC
Labels: P2, area-library, library-io, type-bug
