### ISSUE TITLE
Running pub get can be very slow on Dart 1.17.1

### ISSUE THREAD

**Issue by regenvanwalbeek-wf** [dart-lang/sdk#26763] opened 2016-06-23 21:48 UTC
Running a `pub get` can be _very_ slow in certain situations using Dart 1.17.1 (at least 30 minutes in our situation). The following repo illustrates the issue: https://github.com/regenvanwalbeek-wf/pub_get_failure. The repo contains a `simple` and `complex` directory that illustrates the issue with varying severity.

**Steps to Reproduce**
`git clone git@github.com:regenvanwalbeek-wf/pub_get_failure.git`
`cd pub_get_failure/simple/pub_get_failing_lib`
`pub get`

This will finish immediately using dart 1.15.0 but will take over a minute using dart 1.17.1

Doing the same inside the `complex` directory will take a _very_ long time using dart 1.17.1 (I gave up after 30 minutes), but it finished after a few seconds using dart 1.15.0.

**Comment by zanderso** [comment] 2016-06-30 22:28
I was able to reproduce this at top-of-tree on Linux. A cursory run through the Observatory indicates that lots of time is being spent in the solver. @nex3

**Comment by floitschG** [comment] 2016-06-30 23:19
I'm assigning the VM-label for now (to mark the issue as triaged), but once Natalie confirms, we should migrate this bug to the pub repository.

**Comment by nex3** [comment] 2016-07-06 19:38
Duplicate of dart-lang/pub#912.

**Closed by nex3** 2016-07-06 19:38 UTC
Labels: area-vm
