### ISSUE TITLE
Dart analyzer has been crashing quite a bit after updating.

### ISSUE THREAD

**Issue by brandondiamond** [dart-lang/sdk#41973] opened 2020-05-19 21:33 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6392135`
- `2.8.2`
- `AI-192.7142.36.36.6392135, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1280x800  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.2, server version 1.27.4, FATAL error: type 'KeywordToken' is not a subtype of type 'List<Annotation>'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

For additional log information, please append the contents of
file:///private/var/folders/d8/x1631dkx41z_8g8dn41hpymh0000gn/T/report.txt.

**Comment by srawlins** [comment] 2020-06-14 18:35
Thanks for reporting this issue! A duplicate of this issue has been filed, which has more discussion. Please follow along there. #41267

**Comment by srawlins** [comment] 2020-06-14 18:35
Duplicate of #41267

**Closed by srawlins** 2020-06-14 18:35 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
