### ISSUE TITLE
npe from dartanalyzer

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25305] opened 2015-12-21 22:55 UTC
Full stack available here: https://travis-ci.org/flutter/flutter/builds/98217872#L284

```
Caused by The null object does not have a getter 'element'.
NoSuchMethodError: method not found: 'element'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      StaticTypeAnalyzer._matchGeneric (package:analyzer/src/generated/static_type_analyzer.dart:1904)
#3      StaticTypeAnalyzer._inferMethodInvocationGeneric (package:analyzer/src/generated/static_type_analyzer.dart:1697)
#4      StaticTypeAnalyzer._inferMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:1688)
#5      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:635)
#6      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12369)
#7      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:11296)
#8      MethodInvocation.accept (package:analyzer/src/generated/ast.dart:12369)
#9      ResolverVisitor.visitConditionalExpression (package:analyzer/src/generated/resolver.dart:10890)
#10     ConditionalExpression.accept (package:analyzer/src/generated/ast.dart:5108)
#11     AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3095)
...
```

**Comment by bwilkerson** [comment] 2015-12-22 16:37
The method in which the exception was being thrown no longer exists, so it's possible this has been fixed in bleeding edge, but it would be good to confirm that.

**Comment by devoncarew** [comment] 2015-12-29 21:39
I see this exception when run against the latest dev (this above one is for stable):

```
Caused by The null object does not have a getter 'bound'.

NoSuchMethodError: method not found: 'bound'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ErrorVerifier._checkForTypeParameterSupertypeOfItsBound (package:analyzer/src/generated/error_verifier.dart:5351)
#3      ErrorVerifier.visitTypeParameter (package:analyzer/src/generated/error_verifier.dart:1072)
#4      TypeParameter.accept (package:analyzer/src/generated/ast.dart:19344)
#5      NodeList.accept (package:analyzer/src/generated/ast.dart:12645)
#6      TypeParameterList.visitChildren (package:analyzer/src/generated/ast.dart:19406)
#7      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/src/generated/ast.dart:15556)
#8      TypeParameterList.accept (package:analyzer/src/generated/ast.dart:19402)
#9      AstNode._safelyVisitChild (package:analyzer/src/generated/ast.dart:3062)
#10     MethodDeclaration.visitChildren (package:analyzer/src/generated/ast.dart:12077)
#11     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/src/generated/ast.dart:15345)
#12     ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:891)
#13     MethodDeclaration.accept (package:analyzer/src/generated/ast.dart:12070)
```

**Comment by bwilkerson** [comment] 2015-12-31 16:45
I'm not sure the two exceptions are related, but the latter is definitely a bug. It appears to be caused by having a type parameter on a method. @devoncarew Do you know whether the parameter is expressed using the parameterized methods syntax (something like "m<E>(...)") or the comment-based equivalent (something like "m/*<E>*/(...)")? I'd guess it's the latter, but confirmation would be good.

**Comment by devoncarew** [comment] 2015-12-31 18:29
It claims to be happening for `analyzer-0.27.1+1/lib/task/model.dart`. Not sure that's really the case, but if so that file doesn't use the comment based syntax.

```
Unhandled exception:
AnalysisException: Cannot compute DART_ERRORS for /Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/analyzer-0.27.1+1/lib/task/model.dart
Caused by Unexpected exception while performing VerifyUnitTask for source /Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/analyzer-0.27.1+1/lib/task/model.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:622)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:570)
#6      AnalyzerImpl.prepareErrors.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:133)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#8      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
#9      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:167)
#10     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#11     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:533)
#12     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:184)
#13     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:127)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#15     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:126)
#16     Driver.start (package:analyzer_cli/src/driver.dart:112)
#17     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:14)
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'bound'.

NoSuchMethodError: method not found: 'bound'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ErrorVerifier._checkForTypeParameterSupertypeOfItsBound (package:analyzer/src/generated/error_verifier.dart:5351)
#3      ErrorVerifier.visitTypeParameter (package:analyzer/src/generated/error_verifier.dart:1072)
#4      TypeParameter.accept (package:analyzer/src/generated/ast.dart:19344)
#5      NodeList.accept (package:analyzer/src/generated/ast.dart:12645)
#6      TypeParameterList.visitChildren (package:analyzer/src/generated/ast.dart:19406)
#7      RecursiveAstVisitor.visitTypeParameterList (package:analyzer/src/generated/ast.dart:15556)
...
```

To repro this, you can clone the flutter repo (https://github.com/flutter/flutter), add flutter/bin to your path, and run `flutter analyze --flutter-repo` (http://flutter.io/getting-started/).

**Comment by bwilkerson** [comment] 2015-12-31 18:33
Actually, it does use the comment form in several places (TaskInput, ListTaskInput and MapTaskInput). Thanks!

**Comment by jmesserly** [comment] 2016-01-04 21:28
thanks, I can take a look at this

**Comment by jmesserly** [comment] 2016-01-04 21:43
It looks like we somehow created a TypeParameter AST node with no corresponding TypeParameterElement, either was never created or was cleared somehow.

DeclarationResolver.visitTypeParameter is suspicious. It doesn't know how to find generic method parameters. Seems like that can't possibly be right. I'll try and write a unit test to confirm.

Speculation: I wonder if this is the root cause of the bug we were seeing trying to use strong mode to edit code in Analyzer, where it seems to hit exceptions as you edit code, even when the initial analysis works. Maybe it's triggered by Flutter because it's a bigger code base and things get evicted from the AST cache.

**Comment by jmesserly** [comment] 2016-01-04 22:50
https://codereview.chromium.org/1555213002/ fixes visitTypeParameter issue.

I'll pull down Flutter and see if that's the only one or if it uncovers other problems.

**Comment by pq** [comment] 2016-01-04 22:52
:metal:

**Closed** 2016-01-04 23:22 UTC
Labels: analyzer-command, area-analyzer, priority-high, Type-Defect

**Comment by jmesserly** [comment] 2016-01-04 23:25
@devoncarew -- it fixes that stack trace but I'm not sure if this fixes all of the problems. I was able to run `flutter analyze --flutter-repo` and it doesn't NPE, but there's a lot of "[error]" messages from dartanalyze that look like packages aren't resolving (seems to happen with or without my change). I might've missed a step in the set up instructions. I'll see if I can figure out what's going on.

**Comment by jmesserly** [comment] 2016-01-04 23:38
I was able to reproduce the NPE on current dev SDK & can confirm it's fixed after the CL above.

Incidentally I see a few strong mode errors:
```
[error] Field declaration RenderObject.parentData cannot be overridden in RenderSector. (flutter/examples/rendering/lib/sector_layout.dart, line 75, col 3)
[error] Field declaration RenderObject.parentData cannot be overridden in RenderSector. (flutter/examples/rendering/lib/sector_layout.dart, line 75, col 3)
[error] Field declaration HitTestEntry.target cannot be overridden in BoxHitTestEntry. (flutter/packages/flutter/lib/src/rendering/box.dart, line 309, col 3)
[hint] The argument type 'List<T>' cannot be assigned to the parameter type 'List<TextSpan>' (flutter/packages/flutter/lib/src/widgets/basic.dart, line 1388, col 40)
[hint] The argument type '(dynamic) → TextSpan' cannot be assigned to the parameter type '(dynamic) → T' (flutter/packages/flutter/lib/src/widgets/basic.dart, line 1388, col 60)
[error] Field declaration Command.usageFooter cannot be overridden in DaemonCommand. (flutter/packages/flutter_tools/lib/src/commands/daemon.dart, line 35, col 3)
[error] Field declaration Simulation.tolerance= cannot be overridden in SimulationGroup. (flutter/packages/newton/lib/src/simulation_group.dart, line 36, col 3)
```

**Comment by jmesserly** [comment] 2016-01-04 23:47
Those hints look bogus, so I filed https://github.com/dart-lang/sdk/issues/25340 about that.

**Comment by devoncarew** [comment] 2016-01-05 00:08
Awesome, thanks for the quick turn-around!
