### ISSUE TITLE
quick fix for `avoid_returning_null_for_void`

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#46074] opened 2021-05-19 17:09 UTC
This is a recommended lint but is missing a fix.

```dart
  void read(ElementImpl element) {
    if (_offset == -1) {
      return null; //<= no fix
    }
   ...
  }
```

**Comment by bwilkerson** [comment] 2021-05-19 17:50
Duplicate of https://github.com/dart-lang/sdk/issues/45920.

**Closed by bwilkerson** 2021-05-19 17:50 UTC
Labels: analyzer-linter, analyzer-quick-fix
