### ISSUE TITLE
rxvt-unicode not recognized as supporting ANSI escapes

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#33955] opened 2018-07-23 23:24 UTC
When `TERM=rxvt-unicode`, `Stdout.supportsAnsiEscapes` returns false, but should return true.

**Comment by natebosch** [comment] 2018-08-29 00:33
Duplicate of https://github.com/dart-lang/sdk/issues/31606

**Closed by natebosch** 2018-08-29 00:33 UTC
Labels: area-library, library-io
