### ISSUE TITLE
Expression evaluation returns an error when trying to use extension inside aliased import

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#56554] opened 2024-08-22 17:53 UTC
Repro:

<details>

<summary> Files </summary>

`main.dart`:

```dart
import 'ext.dart' as ext;
import 'ext2.dart';

void main() {
  final i = 0;
  print(i.foo());
  print(i.bar());
  print(i.baz());
}

extension E2 on int {
  int bar() => this;
}
```

`ext.dart`

```dart
extension E on int {
  int foo() => this;
}
```

`ext2.dart`
```
extension E3 on int {
  int baz() => this;
}
```

</details>

Place a breakpoint under `main.dart` at any line and add all of these to watch:

- `i.foo()`
- `i.bar()`
- `i.baz()`

![image](https://github.com/user-attachments/assets/8986fc9a-9646-41d8-9590-e97c3c694e19)

Even with the code running and the analyzer saying nothing, the expression evaluation for `i.foo()` which is under `import 'ext.dart' as ext;` throws an error.

Related: https://github.com/dart-lang/sdk/issues/56555

---

CC: @DanTup

**Comment by a-siva** [comment] 2024-08-24 00:16
I believe this issue is in the same area as https://github.com/dart-lang/sdk/issues/56555, marking this as a duplicate of that issue.

**Comment by FMorschel** [comment] 2024-08-24 01:10
My point in making them separate was so that this one focuses on solving the error and the other one focuses on the error message. But if you believe that they should be handled together thats alright by me.

**Comment by DanTup** [comment] 2024-08-24 12:17
Unless the reason #56555 shows `_Smi` as the type name is because of the extension/aliased import, these seem like different issues to me. My understanding is:

- this issue is about not being able to evaluate expressions using extension members if they `import`ed with an alias
- that issue is about the message saying "isn't defined for the class `_Smi`" but it's not clear what `_Smi` is one might have expected to see `int` here

**Comment by derekxu16** [comment] 2024-08-26 20:14
@johnniwinther, It seems like frontend changes are needed to fix this. I inspected the arguments passed to `KernelIsolate::CompileExpressionToKernel` [here](https://github.com/dart-lang/sdk/blob/0d368ce290690160d08e0ce256a48669465dc3cb/runtime/vm/service.cc#L3267-L3277) once when running the reproduction example as written, and again after changing the `import 'ext.dart' as ext;` line to just `import 'ext.dart';`. The arguments passed were the same in both cases, the interesting ones being: `expression: "i.foo()"`, `params: ["i"]`, `param_types: ["dart:core", "_Smi", "1", "0"]`, but compilation fails when the prefix is used to import `'ext.dart'` and succeeds when the prefix isn't used. Please let me know if any VM changes are required.

**Closed** 2024-10-09 11:42 UTC
Labels: area-vm, type-bug, triaged, cfe-expression-compilation
