### ISSUE TITLE
[parser/spec] `{sealed, interface, final} mixin` inconsistency.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#55233] opened 2024-03-18 17:45 UTC
Consider:

```dart
sealed mixin id { }
interface mixin id { }
final mixin id { }
```

DSP accepts several types of mixins: `sealed mixin`, `interface mixin` & `final mixin` which are rejected by the analyzer.

Could it be that these modifiers on mixins in DSP are remnants of a feature that was abandoned? It looks like they can be removed?

https://github.com/dart-lang/sdk/blob/87473f8e653f948430ccaf880a4e1e4f4d6a1953/tools/spec_parser/dart_spec_parser/Dart.g4#L440-L444

```
 === pkg:analyzer (https://pub.dev/packages/analyzer) ===
Parsing failed with some errors:
Scan errors: 0
Parse errors: 3
file(0..5): A mixin can't be declared 'sealed'.
file(20..28): A mixin can't be declared 'interface'.
file(43..47): A mixin can't be declared 'final'.
<CompilationUnitImpl> [0-62]
┣━ <MixinDeclarationImpl> [7-19]
┃  ┣━ 'mixin' [7-12]
┃  ┣━ 'id' [13-15]
┃  ┣━ '{' [16-17]
┃  ┗━ '}' [18-19]
┣━ <MixinDeclarationImpl> [30-42]
┃  ┣━ 'mixin' [30-35]
┃  ┣━ 'id' [36-38]
┃  ┣━ '{' [39-40]
┃  ┗━ '}' [41-42]
┗━ <MixinDeclarationImpl> [49-61]
  ┣━ 'mixin' [49-54]
  ┣━ 'id' [55-57]
  ┣━ '{' [58-59]
  ┗━ '}' [60-61]
--------------------------------------------------------------------------------
 === DSP (https://github.com/dart-lang/sdk/blob/master/tools/spec_parser/dart_spec_parser/Dart.g4) dspVersion v0.41 ===
Parsing succeeded with no errors.
Errors of type 1: []
Errors of type 2: []
<startSymbol>
┗━ <libraryDefinition>
  ┣━ <metadata>
  ┣━ <topLevelDefinition>
  ┃  ┗━ <mixinDeclaration>
  ┃    ┣━ <mixinModifier>
  ┃    ┃  ┗━ 'sealed'
  ┃    ┣━ 'mixin'
  ┃    ┣━ <typeIdentifier>
  ┃    ┃  ┗━ <typeIdentifierNotType>
  ┃    ┃    ┗━ 'id'
  ┃    ┣━ '{'
  ┃    ┗━ '}'
  ┣━ <metadata>
  ┣━ <topLevelDefinition>
  ┃  ┗━ <mixinDeclaration>
  ┃    ┣━ <mixinModifier>
  ┃    ┃  ┗━ 'interface'
  ┃    ┣━ 'mixin'
  ┃    ┣━ <typeIdentifier>
  ┃    ┃  ┗━ <typeIdentifierNotType>
  ┃    ┃    ┗━ 'id'
  ┃    ┣━ '{'
  ┃    ┗━ '}'
  ┣━ <metadata>
  ┣━ <topLevelDefinition>
  ┃  ┗━ <mixinDeclaration>
  ┃    ┣━ <mixinModifier>
  ┃    ┃  ┗━ 'final'
  ┃    ┣━ 'mixin'
  ┃    ┣━ <typeIdentifier>
  ┃    ┃  ┗━ <typeIdentifierNotType>
  ┃    ┃    ┗━ 'id'
  ┃    ┣━ '{'
  ┃    ┗━ '}'
  ┗━ '<EOF>'
```

**Comment by lrhn** [comment] 2024-03-18 21:56
Maybe it accepts the modifiers because it's perfectly good grammar, it just need to be accompanied by a non-grammatical rule saying that it's a compile-time error to use those modifiers with a `mixin`. 
(It's easier to give a good error message when one can say "this one thing you did, it's not allowed" instead of "I don't know what you're trying to do, it doesn't parse as anything".)

**Comment by modulovalue** [comment] 2024-03-18 22:52
I mean, that makes sense, but wouldn't it be more economical to have the specification focus on precisely specifying the language and only the language without any error recovery strategies since implementations are free to ignore any error recovery recommendations anyway?

> Maybe it accepts the modifiers because it's perfectly good grammar, it just need to be accompanied by a non-grammatical rule saying that it's a compile-time error to use those modifiers with a mixin.

Why have an extra section saying "you can't do that" if one can just make the grammar say that it's not doable in the first place?

**Comment by eernstg** [comment] 2024-03-19 10:19
Good catch! This is a missing update in Dart.g. It is done in https://dart-review.googlesource.com/c/sdk/+/358460.

**Comment by eernstg** [comment] 2024-03-19 17:36
I'll close this issue because https://dart-review.googlesource.com/c/sdk/+/358460 has landed. I think the remaining discussion topics have a broader nature and won't give rise to concrete changes at this time, so they can continue elsewhere (or here, even though the issue is closed).

**Closed by eernstg** 2024-03-19 17:36 UTC
Labels: area-language, language-spec-parser
