### ISSUE TITLE
VS Code error report UnimplementedError in Analyzer

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31276] opened 2017-11-03 19:38 UTC
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

(please describe what you were doing when this exception occurred)

### Versions

- Dart SDK 1.24.2
- Visual Studio Code 1.17.2
- Dart Code 2.4.3

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=2.4.3
```

### Exception

Analysis failed: /Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart context: exception_20171103_101322_209

```text
UnimplementedError
#0      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1096)
#1      CompilationUnitElementForLink.resolveTypeRef.getTypeArgument (package:analyzer/src/summary/link.dart:1103)
#2      new List.generate (dart:core/list.dart:142)
#3      ClassElementForLink_Class.buildType (package:analyzer/src/summary/link.dart:647)
#4      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1113)
#5      VariableElementForLink.declaredType (package:analyzer/src/summary/link.dart:5196)
#6      VariableElementForLink.type (package:analyzer/src/summary/link.dart:5287)
#7      PropertyAccessorElementForLink_Variable.returnType (package:analyzer/src/summary/link.dart:4548)
#8      PropertyAccessorElementForLink_Variable.asStaticType (package:analyzer/src/summary/link.dart:4501)
#9      ExprTypeComputer._doPushReference (package:analyzer/src/summary/link.dart:2485)
#10     ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2073)
#11     TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:4957)
#12     TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:4808)
#13     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#14     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#15     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5226)
#16     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2700)
#17     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:673)
#18     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1308)
#19     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3672)
#20     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3408)
#21     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3330)
#22     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:147)
#23     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#24     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#25     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#26     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#27     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#28     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:113)
#29     DependencyWalker.walk (package:front_end/src/dependency_walker.dart:166)
#30     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3373)
#31     Linker.link (package:analyzer/src/summary/link.dart:3897)
#32     relink (package:analyzer/src/summary/link.dart:132)
#33     link (package:analyzer/src/summary/link.dart:113)
#34     new LibraryContext.forSingleLibrary.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:116)
#35     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#36     new LibraryContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:115)
#37     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#38     new LibraryContext.forSingleLibrary (package:analyzer/src/dart/analysis/library_context.dart:53)
#39     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1092)
#40     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:989)
#41     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#42     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#43     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:854)
<asynchronous suspension>
#44     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#45     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#46     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#47     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#48     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#50     _rootRun (dart:async/zone.dart:1120)
#51     _CustomZone.run (dart:async/zone.dart:1001)
#52     runZoned (dart:async/zone.dart:1467)
#53     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#54     Driver.start (package:analysis_server/src/server/driver.dart:473)
#55     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#56     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by thosakwe** [comment] 2017-11-04 14:47
Seems to be related to https://github.com/dart-lang/sdk/issues/31283

**Comment by aemino** [comment] 2017-11-05 21:03
I'm using VSCode with Dart Code, and the analysis server is also crashing for me.  However, it actually works fine for me with SDK version `1.24.2`.  I encounter an error on SDK version `2.0.0-dev.6.0`.   I looked into the actual code at `link.dart` and the `UnimplementedError` that was previously thrown is no longer there, so the actual error itself is likely different.  Unfortunately, I'm unable/not sure how to retrieve a stack trace for this issue, so my comment is likely not of much help.

**Comment by bwilkerson** [comment] 2017-11-05 21:08
@scheglov Any ideas?

**Comment by thosakwe** [comment] 2017-11-06 17:33
Not sure what's actually causing the error, but I've found *one* way to reproduce it.

I get the error any time I open this project: https://github.com/thosakwe/combinator

In addition, I created a new project that depends on `combinator`. The analyzer was working fine, but the very moment I added `import package:combinator/combinator.dart`, it crashed. Once I removed it, code completions began to appear again.

Traits of the `combinator` library include:
* Uses `part` and `part of`
* Contains one public class with 20+ private subclasses
* Uses a lot of generics

Hopefully this is helpful.

**Comment by thosakwe** [comment] 2017-11-06 17:40
I've tracked down where the error is thrown, in an old commit:
https://github.com/dart-lang/sdk/blob/03a0ee09436322e2d6609ba61dc88989faa18d60/pkg/analyzer/lib/src/summary/link.dart#L1093-L1100

**Comment by scheglov** [comment] 2017-11-06 17:51
Well, as you noticed, this code has been fixed since then.

As for `combinator`, when I clone https://github.com/thosakwe/combinator I see that there is at least one syntax error. Is this expected, and a part of reproducing?

Anyway, when I open `combinator` using the bleeding edge Analysis Server, I get `43 errors, 1 warning, 3 hints` and no crashes.

**Comment by thosakwe** [comment] 2017-11-06 17:57
I actually had not noticed the syntax error at first, but it's fixed now. The analysis server had been crashing since before that was added, though.

I was playing around with commenting out certain snippets, and once I commented out the following, the crashes ended:

https://github.com/thosakwe/combinator/blob/2e312267a706e8a45a0034c7c58bbab7cb2ae7fc/lib/src/combinator/combinator.dart#L156-L158

Afterwards, I saw that the `_ListMap` type wasn't returning a value of the type it was declared to. Once that was cleaned up, everything started to work again.

Is there any version of the Dart SDK greater than `1.24.2`, but less than `2.0.0`?

**Comment by scheglov** [comment] 2017-11-06 18:10
You can try a `Dev channel` at https://www.dartlang.org/install/archive, maybe the latest not `2.0.0`, i.e. `1.25.0-dev.16.4`.

**Comment by pschiffmann** [comment] 2017-12-21 15:57
Hey!

Same problem here, except that I use `dartanalyzer` from the command line, not an IDE.
The code that causes the problem for me is: https://github.com/pschiffmann/indexed-set.dart (commit dabdfb0c1978433f260b92ae2d1e5f503fe3f728 as I write this)

> Well, as you noticed, this code has been fixed since then.

I'm using version `1.24.3`, which was released 2017/12/04 and still contains that bug. Please don't feel offended, I'm don't want to blame anyone – just letting you know.
I also tried `1.25.0-dev.16.4` as you suggested and the analyzer works in that version – but that isn't a stable release, so ... can you give any information when the fix will be published properly? Do we have to wait for `1.25.0`, or will there be a `1.24.4`? And can you suggest any workaround until then?

Thanks!

If you want to look at my example: The code is strong-mode compliant. When you run the analyzer, you should see no warnings or lints and a single error: _Missing concrete implementation of 'SetBuilder.withBase' at lib/src/superset.dart:192:7_
That method is commented out [here](https://github.com/pschiffmann/indexed-set.dart/blob/dabdfb0c1978433f260b92ae2d1e5f503fe3f728/lib/src/superset.dart#L287) because it crashes the analyzer. Remove the `/**/` to reproduce the error.

**Comment by scheglov** [comment] 2017-12-24 20:38
As far as I know (and I'm not a project manager, so I might be mistaken), we don't plan releasing any new stable version until `2.0.0`. So, `1.24.*` is the only one. We still build unstable `1.25.*` versions to roll SDK internally in Google with new fixes and features.

**Comment by bwilkerson** [comment] 2018-01-30 19:37
I'm closing this because it appears to no longer be an issue in the 2.0-dev builds.

**Closed by bwilkerson** 2018-01-30 19:37 UTC
Labels: analyzer-server, area-analyzer
