### ISSUE TITLE
unable to perform type inference from generic parameter

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#46769] opened 2021-07-31 00:01 UTC
## Seen Behavior
The following code cannot infer that the `value` parameter should be a String.

## Expected Behavior
I expect type inference to work here so that it knows the second parameter is a `String`.

## Code
```dart
//@dart = 2.12

Iterable<U> _intMap<T, U>(Iterable<T> iterable, U Function(int x, T value) func) sync* {
  int count = 0;
  for (final T value in iterable) {
    yield func(count, value);
    count += 1;
  }
}

String _join(int x, String value) => '$value$x';

void main() {
  List<String> items = ['one', 'two', 'three'];
  print(_intMap(items, (x, value) => _join(x, value)).toList());
}
```

## Error
```
foo.dart:16:47: Error: The argument type 'Object?' can't be assigned to the parameter type 'String'.
 - 'Object' is from 'dart:core'.
  print(_intMap(items, (x, value) => _join(x, value)).toList());
                                              ^
```

## Version
Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "macos_x64"

**Comment by gaaclarke** [comment] 2021-08-02 17:27
Workaround, pull your lambda into a named function:

works:
`print(_intMap(items, _join).toList());`

doesn't work:
`print(_intMap(items, (x, value) => _join(x, value)).toList());`

**Comment by leafpetersen** [comment] 2021-08-02 20:46
This is a duplicate of https://github.com/dart-lang/language/issues/731 .  The style of inference we do (so called "colored local type inference") doesn't handle this pattern by default (at the point that need to fix a type for the parameter to the lambda, the type info from the other outer parameters is not available).  The linked issue tracks adding C# style heuristics (or some other approach) to handle this more gracefully.

**Closed by leafpetersen** 2021-08-02 20:47 UTC
