### ISSUE TITLE
No error reported for overriding a method and changing an optional parameter default value

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#34037] opened 2018-07-31 18:01 UTC
From @eernstg on an internal thread discussing default parameter values.

>That shouldn't actually happen, due to the following [snippet](https://github.com/dart-lang/sdk/blob/3dc201e168088d58e92f3d7c623dc3aeca700561/docs/language/dartLangSpec.tex#L1373) in the spec: `It is a compile-time error if an instance method $m_1$ overrides an instance member $m_2$, the signature of $m_2$ explicitly specifies a default value for a formal parameter $p$, and the signature of $m_1$ implies a different default value for $p$.`

Neither the CFE produce an error or warning for this case.

```dart
class A {
  void doStuff([int a = 1]) {
    print(a);
  }
}

class B implements A {
  void doStuff([int a = 2]) {
    print(a);
  }
}

void main() {
  A().doStuff();
  B().doStuff();
}
```

It's likely very breaking to change the tool behavior.

cc @leafpetersen @dgrove

**Comment by leafpetersen** [comment] 2018-07-31 18:04
Duplicate of https://github.com/dart-lang/sdk/issues/27476 .

**Closed by leafpetersen** 2018-07-31 18:04 UTC
