### ISSUE TITLE
Dart2JS fails to accept built-in identifier as variable name

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21154] opened 2014-09-30 08:55 UTC
Dart2JS stops with the compile-time error 'Error: Expected identifier, but got ';'' in the co19 test

Language/12_Expressions/30_Identifier_Reference_A02_t01.

The text on ECMA-408 p86 implies that built-in identifiers should be allowed as names of variables, even though they are not allowed as type names.  The error message could indicate that 'abstract' is parsed as a modifier and never considered as a potential variable name, but in any case it should not be an error.

**Comment by peter-ahe-google** [comment] 2017-05-18 13:41
Duplicate of #6972.

**Closed by peter-ahe-google** 2017-05-18 13:41 UTC
Labels: area-dart2js, Type: bug
