### ISSUE TITLE
dart error

### ISSUE THREAD

**Issue by bashandd** [dart-lang/sdk#34406] opened 2018-09-08 04:56 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\bshaik\AppData\Local\Temp\1\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.7, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Basha\Personal\WeServe\Flutter\flutter_baseapp-master], excluded: [C:\Basha\Personal\WeServe\Flutter\flutter_baseapp-master\.idea, C:\Basha\Personal\WeServe\Flutter\flutter_baseapp-master\.dart_tool, C:\Basha\Personal\WeServe\Flutter\flutter_baseapp-master\.pub, C:\Basha\Personal\WeServe\Flutter\flutter_baseapp-master\build]}, clientRequestTime: 1536382237412}
FileSystemException: Exists failed, path = 'C:\Basha\Personal\WeServe\Flutter\flutter_baseapp-master\build\image_picker\intermediates\classes\debug' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:323)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by devoncarew** [comment] 2018-09-12 15:44
dupe of https://github.com/dart-lang/sdk/issues/33280

**Closed by devoncarew** 2018-09-12 15:44 UTC
Labels: analyzer-server, area-analyzer, crash
