### ISSUE TITLE
Failed to find the declaration of the variable in 

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#26632] opened 2016-06-07 17:40 UTC
```
1.17.0-dev.2.0
Session: 1463033018219.0916.json
Caused by Failed to find the declaration of the variable _______ in _______.dart
#0      InferStaticVariableTask.getDeclaration (package::analyzer/src/task/dart.dart::3116)
#1      ComputePropagableVariableDependenciesTask.internalPerform (package::analyzer/src/task/dart.dart::2179)
#2      AnalysisTask._safelyPerform (package::analyzer/task/model.dart::329)
#3      AnalysisTask.perform (package::analyzer/task/model.dart::229)
#4      AnalysisDriver.performWorkItem (package::analyzer/src/task/driver.dart::276)
#5      AnalysisDriver.performAnalysisTask (package::analyzer/src/task/driver.dart::251)
#6      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1161)
#7      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::212)
#8      AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1159)
#9      PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::371)
#10     AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::876)
#11     Future.Future.<anonymous closure> (dart::async/future.dart::118)
#12     _rootRun (dart::async/zone.dart::946)
#13     _CustomZone.run (dart::async/zone.dart::826)
#14     _CustomZone.runGuarded (dart::async/zone.dart::724)
#15     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#16     _rootRun (dart::async/zone.dart::950)
#17     _CustomZone.run (dart::async/zone.dart::826)
#18     _CustomZone.runGuarded (dart::async/zone.dart::724)
#19     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#20     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#21     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#22     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#23     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)


#0      AnalysisFutureHelper.computeAsync.<anonymous closure> (package::analyzer/src/context/context.dart::2020)
#1      PendingFuture.evaluate (package::analyzer/src/context/context.dart::2125)
#2      AnalysisFutureHelper.computeAsync (package::analyzer/src/context/context.dart::2026)
#3      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package::analysis_server/src/services/completion/dart/completion_manager.dart::437)
#4      Future.Future.microtask.<anonymous closure> (dart::async/future.dart::144)
#5      _rootRun (dart::async/zone.dart::946)
#6      _CustomZone.run (dart::async/zone.dart::826)
#7      _CustomZone.runGuarded (dart::async/zone.dart::724)
#8      _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#9      _rootRun (dart::async/zone.dart::950)
#10     _CustomZone.run (dart::async/zone.dart::826)
#11     _CustomZone.runGuarded (dart::async/zone.dart::724)
#12     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#13     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#14     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#15     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::394)
#16     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#17     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)


#0      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package::analysis_server/src/services/completion/dart/completion_manager.dart::442)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart::async-patch/async_patch.dart::34)
#2      _rootRunBinary (dart::async/zone.dart::970)
#3      _CustomZone.runBinary (dart::async/zone.dart::849)
#4      _FutureListener.handleError (dart::async/future_impl.dart::146)
#5      _Future._propagateToListeners.handleError (dart::async/future_impl.dart::640)
#6      _Future._propagateToListeners (dart::async/future_impl.dart::662)
#7      _Future._completeError (dart::async/future_impl.dart::476)
#8      _Future._asyncCompleteError.<anonymous closure> (dart::async/future_impl.dart::528)
#9      _rootRun (dart::async/zone.dart::950)
#10     _CustomZone.run (dart::async/zone.dart::826)
#11     _CustomZone.runGuarded (dart::async/zone.dart::724)
#12     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#13     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#14     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#15     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::394)
#16     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#17     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart
Original message:
{"event"::"server.error","params"::{"isFatal"::false,"message"::"Failed to handle completion domain request:: {clientRequestTime:: 1463034814809, params:: {file:: _____.dart, offset:: 32114}, method:: completion.getSuggestions, id:: 362}","stackTrace"::"AnalysisException:: failed to resolve expression
Caused by Failed to find the declaration of the variable ________ in _______.dart
#0      InferStaticVariableTask.getDeclaration (package::analyzer/src/task/dart.dart::3116)
#1      ComputePropagableVariableDependenciesTask.internalPerform (package::analyzer/src/task/dart.dart::2179)
#2      AnalysisTask._safelyPerform (package::analyzer/task/model.dart::329)
#3      AnalysisTask.perform (package::analyzer/task/model.dart::229)
#4      AnalysisDriver.performWorkItem (package::analyzer/src/task/driver.dart::276)
#5      AnalysisDriver.performAnalysisTask (package::analyzer/src/task/driver.dart::251)
#6      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1161)
#7      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::212)
#8      AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1159)
#9      PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::371)
#10     AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::876)
#11     Future.Future.<anonymous closure> (dart::async/future.dart::118)
#12     _rootRun (dart::async/zone.dart::946)
#13     _CustomZone.run (dart::async/zone.dart::826)
#14     _CustomZone.runGuarded (dart::async/zone.dart::724)
#15     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#16     _rootRun (dart::async/zone.dart::950)
#17     _CustomZone.run (dart::async/zone.dart::826)
#18     _CustomZone.runGuarded (dart::async/zone.dart::724)
#19     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#20     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#21     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#22     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#23     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)


#0      AnalysisFutureHelper.computeAsync.<anonymous closure> (package::analyzer/src/context/context.dart::2020)
#1      PendingFuture.evaluate (package::analyzer/src/context/context.dart::2125)
#2      AnalysisFutureHelper.computeAsync (package::analyzer/src/context/context.dart::2026)
#3      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package::analysis_server/src/services/completion/dart/completion_manager.dart::437)
#4      Future.Future.microtask.<anonymous closure> (dart::async/future.dart::144)
#5      _rootRun (dart::async/zone.dart::946)
#6      _CustomZone.run (dart::async/zone.dart::826)
#7      _CustomZone.runGuarded (dart::async/zone.dart::724)
#8      _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#9      _rootRun (dart::async/zone.dart::950)
#10     _CustomZone.run (dart::async/zone.dart::826)
#11     _CustomZone.runGuarded (dart::async/zone.dart::724)
#12     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#13     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#14     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#15     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::394)
#16     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#17     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)


#0      DartCompletionRequestImpl._computeAsync.<_computeAsync_async_body> (package::analysis_server/src/services/completion/dart/completion_manager.dart::442)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart::async-patch/async_patch.dart::34)
#2      _rootRunBinary (dart::async/zone.dart::970)
#3      _CustomZone.runBinary (dart::async/zone.dart::849)
#4      _FutureListener.handleError (dart::async/future_impl.dart::146)
#5      _Future._propagateToListeners.handleError (dart::async/future_impl.dart::640)
#6      _Future._propagateToListeners (dart::async/future_impl.dart::662)
#7      _Future._completeError (dart::async/future_impl.dart::476)
#8      _Future._asyncCompleteError.<anonymous closure> (dart::async/future_impl.dart::528)
#9      _rootRun (dart::async/zone.dart::950)
#10     _CustomZone.run (dart::async/zone.dart::826)
#11     _CustomZone.runGuarded (dart::async/zone.dart::724)
#12     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::751)
#13     _microtaskLoop (dart::async/schedule_microtask.dart::41)
#14     _startMicrotaskLoop (dart::async/schedule_microtask.dart::50)
#15     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::394)
#16     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#17     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)
"}}

```

**Comment by bwilkerson** [comment] 2016-06-09 15:37
Without having a reproduction case I can't prove this, but I strongly suspect that this was caused by the same issue fixed by https://codereview.chromium.org/2050573003, so I'm going to close this issue with the expectation that a new issue will be opened if the bug remains after the next build.

**Closed by bwilkerson** 2016-06-09 15:37 UTC
Labels: analyzer-stability, area-analyzer, P1 high
