### ISSUE TITLE
I tried moving my dart files into a folder inside my lib, the 'search for references' was selected. The file was moved but it showed an error.

### ISSUE THREAD

**Issue by abhirham** [dart-lang/sdk#39985] opened 2020-01-04 14:45 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, error: FileSystemException(path=D:\projects\Flutter\bmi-calculator-flutter\lib\input_page.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#55     _SinkTransformerStreamSubscription._...
```

For additional log information, please append the contents of
file://C:\Users\savar\AppData\Local\Temp\report.txt.

**Comment by keertip** [comment] 2020-01-06 17:18
Thanks for the report! This is similar to issue reported in #39941, moving files causes read errors.

**Comment by keertip** [comment] 2020-01-06 17:18
Duplicate of #39941

**Closed by keertip** 2020-01-06 17:18 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
