### ISSUE TITLE
Flaky service/valid_source_locations_test/service turned RuntimeError on vm-win-debug-arm64

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#53469] opened 2023-09-08 15:19 UTC
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8770572234679165089/+/u/test_results/stdout

```
--- Command "vm" (took 56.000224s):
set DART_CONFIGURATION=DebugARM64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=c:\opt\s\w\ir\cache\builder\sdk\out\DebugARM64\crashpad_handler.exe & out\DebugARM64\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\valid_source_locations_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: valid_source_locations_test.dart (VM Service)[0m

** Launching SERVICE_TEST_TESTEE=true out\DebugARM64\dart.exe --disable-dart-dev --write-service-info=file:///c:/opt/s/w/ir/x/t/dart_servicebc5e2257/service_info.json --profiler --sound-null-safety -Dtest_runner.configuration=vm-win-debug-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json --enable-vm-service:0 C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\valid_source_locations_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:61099/FUDQ5d7Wa7k=/

>testee>out> 

** Signaled to run test queries on http://127.0.0.1:61099/FUDQ5d7Wa7k= (VM Service)

Loading VM...

Done loading VM

Running valid_source_locations_test.dart [1/2]

Paused with PauseBreakpoint

Running valid_source_locations_test.dart [2/2]

>testee>err> ../../runtime/vm/profiler.cc: 1068: error: expected: fp_ != nullptr

>testee>err> 

>testee>err> ===== CRASH =====

>testee>err> ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF6B8C9AF3C

>testee>err> Aborting reentrant request for stack trace.

00:42 [32m+0[0m[31m -1[0m: valid_source_locations_test.dart (VM Service) [1m[31m[E][0m[0m

  NetworkRpcException(Canceling request: WebSocket closed(id: 2540 method: getObject params: {objectId: classes/661/functions/moveNext, count: 100, isolateId: isolates/1391700555245759, _includePrivateMembers: true}))

  

** Killing script

00:42 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-arm64 service/valid_source_locations_test/service
```

If we extended unwinding records setup to win arm64 (https://github.com/dart-lang/sdk/issues/52000) we could have had a better stacktrace for the assert/crash.

**Comment by rmacnak-google** [comment] 2023-10-06 03:43
Duplicate of #52969

**Closed by rmacnak-google** 2023-10-06 03:43 UTC
Labels: area-vm, gardening
