### ISSUE TITLE
Analyzer cannot infer a generic type when upper type bound is specified

### ISSUE THREAD

**Issue by bytes7bytes7** [dart-lang/sdk#51470] opened 2023-02-20 18:12 UTC
Analyzer cannot infer a generic type when upper type bound is specified

Dart SDK 2.19.2

```dart
abstract class Child<E extends Exception> {
  void handle(E exception);
}

class Parent<E extends Exception> {
  const Parent(this.children);

  final List<Child<E>> children;
}

class E1 implements Exception {}

class E2 implements Exception {}

class Child1 extends Child<E1> {
  @override
  void handle(E1 exception) {}
}

class Child2 extends Child<E2> {
  @override
  void handle(E2 exception) {}
}

void main() {
  final p = Parent(
    [
      Child1(),
      Child2(),
    ],
  );
}
```

For the code above analyzer says
- ```Couldn't infer type parameter 'E'. Tried to infer 'Object' for 'E' which doesn't work: Return type declared as 'List<E>' used where 'List<Child<_>>' is required. The type 'Object' was inferred from: Parameter 'element' declared as 'E' but argument is 'Child1'. Parameter 'element' declared as 'E' but argument is 'Child2'. Consider passing explicit type argument(s) to the generic.```
- ```The argument type 'List<Object>' can't be assigned to the parameter type 'List<Child<Exception>>'```

Of course, I can explicitly specify generic type like that:
```dart
void main() {
  final p = Parent<Exception>(
    [
      Child1(),
      Child2(),
    ],
  );
}
```

But, is it possible to improve the analyzer, so it can set `E` to `Exception` (as it is defined in Parent and Child) ?

**Comment by lrhn** [comment] 2023-02-20 20:09
Marking as analyzer, but it's more likely to be a language issue, if the current behavior is working as specified.

**Comment by eernstg** [comment] 2023-02-21 01:48
The inference failure occurs because of the old rule which is still used in a particular case for the computation of the standard upper bound of types (also known as the 'least upper bound', except that it isn't least, so we're pushing a more truthful name in recent specification documents).

The case which is used in the given example is specified [here](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#:~:text=least%20upper%20bound%20of%20two%20interfaces%20as%20in%20Dart%201), and the details of that approach is in [the language specification](https://spec.dart.dev/DartLangSpecDraft.pdf), section 'Least Upper Bounds' (still using the old name).

Here is a very simple example:

```dart
class E1 implements Exception {}
class E2 implements Exception {}

abstract class Child<E extends Exception> { void m() {}}
class Child1 extends Child<E1> {}
class Child2 extends Child<E2> {}

void main() {
  final x = b ? Child1() : Child2();
  x.m(); // Error: `Object` has no member named `m`.
}
```

The Dart 1 rule about the standard upper bound avoids recursive invocations (in order to ensure termination). Unfortunately, this means that the computation of the standard upper bound of two interface types with different classes (like `Child1` and `Child2`) will search for a unique common superinterface, and it will not make an attempt to compute an upper bound of the form `Child<T>` for some `T`, because that would be a recursive invocation on the type argument. So the upper bound of `Child1` and `Child2` is `Object`.

This result in turn produces the inference failure in the original example.

So it is actually working as specified.

We did not get rid of this Dart 1 rule when Dart 2 was introduced because of the widespread and subtle breakage that it could cause: any change to the outcome of type inference can change the actual type arguments of various objects created at the location where the type inference changes (or somewhere in a function body called from there). This means that even though it would be really nice to have a more precise upper bound in these cases, there is no known good solution at this point, which means that a few explicit type arguments may be needed here and there.

**Comment by bwilkerson** [comment] 2023-02-21 17:36
I'm not sure where to go from here. Should we move this to the `language` repo for the language team to consider, or should we close it for now?

**Comment by eernstg** [comment] 2023-02-21 23:10
One possible next step could be to say that https://github.com/dart-lang/language/issues/176 covers this topic more broadly, and this issue could be closed as a duplicate of that issue.

See also https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aleast-upper-bound for other issues about upper/lower bounds.

**Closed** 2023-02-22 00:54 UTC
Labels: area-analyzer
