### ISSUE TITLE
Allow control over relative imports

### ISSUE THREAD

**Issue by lookfirst** [dart-lang/sdk#37627] opened 2019-07-25 03:40 UTC
Originally filed here: https://youtrack.jetbrains.com/issue/WEB-40061

Right now, IDEA will default to package imports for local files when doing auto completion. I would love to just use relative imports.

I appreciate relative imports because they are kept separated from the package imports so it is easier to tell what is my package code and external code that I've imported.

In my case, this is a standard flutter project and everything is in a `lib` folder. I understand that the imports work fine both as relative and `package:xxx`, it is just a preference because like I said, the way that they are sorted together is different.

**Comment by alexander-doroshko** [comment] 2019-07-25 13:28
Technical details: it is about a `SourceChange` that Analysis Server returns from `completion_getSuggestionDetails()` wnen user selects not-yet-imported item from a code completion list.

**Comment by bwilkerson** [comment] 2019-07-25 13:34
@scheglov @lambdabaa

**Comment by volmus** [comment] 2020-09-07 11:01
Any news on this? :-)

**Comment by HudsonAfonso** [comment] 2020-10-30 12:47
Effective Dart:
DO use relative paths when importing libraries within your own package’s lib directory.

**Comment by srawlins** [comment] 2021-04-28 08:53
Duplicate of https://github.com/dart-lang/sdk/issues/32916; follow along there.

**Closed by srawlins** 2021-04-28 08:53 UTC
Labels: P3, analyzer-completion, area-analyzer, type-enhancement
