### ISSUE TITLE
Multiline support in Dart is not adequate

### ISSUE THREAD

**Issue by m-zaink** [dart-lang/sdk#45102] opened 2021-02-24 09:12 UTC
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* dev_compiler

# Issue

* Support for multi-line strings in Dart is not adequate.
* Unline in languages like Swift wherein the indentation is not forced to be a part of the string, Dart forces us to write multiline strings from the edge of the file (without indentation for better readability).
* This is very annoying and definitely a very critically needed feature.

**Comment by lrhn** [comment] 2021-02-24 11:55
Closing as duplicate of https://github.com/dart-lang/language/issues/559.
Not an unreasonable request.

**Closed by lrhn** 2021-02-24 11:55 UTC
