### ISSUE TITLE
Android studio suggests to post this issue - and i dont know.!

### ISSUE THREAD

**Issue by linhdkl** [dart-lang/sdk#35089] opened 2018-11-07 02:29 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/jx/f3713_q51vl5kclyc6y_4dzm0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: ...mobile_api_imp.dart context: exception_20181107_092338_489
Element mismatch in mobile_api_imp.dart at class OpesMobileApiImp
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-11-07 16:19
Duplicate of #33930

**Closed by stereotype441** 2018-11-07 16:19 UTC
Labels: area-analyzer
