### ISSUE TITLE
[LSP] Error while trying to define InputDecoration properties

### ISSUE THREAD

**Issue by mo-ah-dawood** [dart-lang/sdk#47203] opened 2021-09-13 10:30 UTC
Error while trying to define InputDecoration properties

the code i trying to write

```dart
   TextFormField(
         decoration: InputDecoration(
               prefixIcon: Icon(Icons.title_rounded),
               border: InputBorder.none,
         ),
   ),
```

```
[Error - 4:51:51 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:51:51 PM] An error occurred while handling textDocument/codeAction request: Bad state: Cannot access an invalid result
#0      InvalidResult.result (package:analysis_server/src/services/correction/fix/data_driven/accessor.dart:83:24)
#1      CodeFragment.writeOn (package:analysis_server/src/services/correction/fix/data_driven/value_generator.dart:62:42)
#2      TemplateVariable.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:154:15)
#3      CodeTemplate.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:41:17)
#4      ModifyParameters.apply.writeArgument (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:108:23)
#5      ModifyParameters.apply.writeInsertionRange (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:131:13)
#6      ModifyParameters.apply.<anonymous closure> (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:202:13)
#7      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1295:41)
#8      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:431:16)
#9      DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1294:13)
#10     ModifyParameters.apply (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:201:19)
#11     DataDrivenFix.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:103:20)
#12     ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:118:20)
<asynchronous suspension>
#13     DataDrivenFix.compute (package:analysis_server/src/services/correction/dart/data_driven.dart:101:5)
<asynchronous suspension>
#14     FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1290:9)
<asynchronous suspension>
#15     FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1316:13)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1245:5)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:191:19)
<asynchronous suspension>
#18     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:357:23)
<asynchronous suspension>
#19     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#20     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:306:21)
<asynchronous suspension>
#21     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:22)
<asynchronous suspension>
#22     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:26)
<asynchronous suspension>

[Error - 4:51:52 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:51:52 PM] An error occurred while handling textDocument/codeAction request: Bad state: Cannot access an invalid result
#0      InvalidResult.result (package:analysis_server/src/services/correction/fix/data_driven/accessor.dart:83:24)
#1      CodeFragment.writeOn (package:analysis_server/src/services/correction/fix/data_driven/value_generator.dart:62:42)
#2      TemplateVariable.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:154:15)
#3      CodeTemplate.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:41:17)
#4      ModifyParameters.apply.writeArgument (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:108:23)
#5      ModifyParameters.apply.writeInsertionRange (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:131:13)
#6      ModifyParameters.apply.<anonymous closure> (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:202:13)
#7      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1295:41)
#8      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:431:16)
#9      DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1294:13)
#10     ModifyParameters.apply (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:201:19)
#11     DataDrivenFix.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:103:20)
#12     ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:118:20)
<asynchronous suspension>
#13     DataDrivenFix.compute (package:analysis_server/src/services/correction/dart/data_driven.dart:101:5)
<asynchronous suspension>
#14     FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1290:9)
<asynchronous suspension>
#15     FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1316:13)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1245:5)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:191:19)
<asynchronous suspension>
#18     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:357:23)
<asynchronous suspension>
#19     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#20     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:306:21)
<asynchronous suspension>
#21     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:22)
<asynchronous suspension>
#22     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:26)
<asynchronous suspension>

[Error - 4:53:15 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:53:15 PM] An error occurred while handling textDocument/codeAction request: Bad state: Cannot access an invalid result
#0      InvalidResult.result (package:analysis_server/src/services/correction/fix/data_driven/accessor.dart:83:24)
#1      CodeFragment.writeOn (package:analysis_server/src/services/correction/fix/data_driven/value_generator.dart:62:42)
#2      TemplateVariable.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:154:15)
#3      CodeTemplate.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:41:17)
#4      ModifyParameters.apply.writeArgument (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:108:23)
#5      ModifyParameters.apply.writeInsertionRange (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:131:13)
#6      ModifyParameters.apply.<anonymous closure> (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:202:13)
#7      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1295:41)
#8      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:431:16)
#9      DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1294:13)
#10     ModifyParameters.apply (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:201:19)
#11     DataDrivenFix.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:103:20)
#12     ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:118:20)
<asynchronous suspension>
#13     DataDrivenFix.compute (package:analysis_server/src/services/correction/dart/data_driven.dart:101:5)
<asynchronous suspension>
#14     FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1290:9)
<asynchronous suspension>
#15     FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1316:13)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1245:5)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:191:19)
<asynchronous suspension>
#18     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:357:23)
<asynchronous suspension>
#19     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#20     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:306:21)
<asynchronous suspension>
#21     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:22)
<asynchronous suspension>
#22     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:26)
<asynchronous suspension>
```

**Versions (please complete the following information):**
 - VS Code version: 1.60.0
 - Operating system : MacOs big sur 11.5.2
 - Dart extension version: 3.26.0
 - Dart/Flutter SDK version:  2.14.0 / 2.5.0

**Comment by DanTup** [comment] 2021-09-13 13:31
@mo-ah-dawood do you have a complete file that triggers this and/or can you confirm where you have the cursor in the code when this happens? I tried with this code in a Flutter app using Flutter 2.5.0 but was unable to trigger it.

@bwilkerson

**Comment by mo-ah-dawood** [comment] 2021-09-14 09:31
https://user-images.githubusercontent.com/31937782/133232872-77f6a101-667f-4ead-9c55-86081f0ae8f6.mov

**Comment by DanTup** [comment] 2021-09-14 10:28
@mo-ah-dawood thanks!

@bwilkerson I don't know how to fix this, but I did manage to find the bits of the Flutter fix_data causing this and managed to make a test that might help (I had this in `test/src/services/correction/fix/data_driven/data_driven_test.dart`):

```dart
  @soloTest
  Future<void> test_danny() async {
    setPackageContent('''
class InputDecorationTheme {
  const InputDecorationTheme({
    this.floatingLabelBehavior = FloatingLabelBehavior.never,
  });

  final FloatingLabelBehavior floatingLabelBehavior;
}

enum FloatingLabelBehavior { never }
''');
    addPackageDataFile('''
version: 1
transforms:
  - title: "Migrate to 'floatingLabelBehavior'"
    date: 2020-01-15
    element:
      uris: [ '$importUri' ]
      constructor: ''
      inClass: 'InputDecorationTheme'
    oneOf:
      - if: "hasFloatingPlaceholder != 'true' && hasFloatingPlaceholder != 'false'"
        changes:
          - kind: 'addParameter'
            index: 0
            name: 'floatingLabelBehavior'
            style: optional_named
            argumentValue:
              expression: '{% hasFloatingPlaceholder %} ? {% FloatingLabelBehavior %}.auto : {% FloatingLabelBehavior %}.never'
              requiredIf: "hasFloatingPlaceholder != 'true' && hasFloatingPlaceholder != 'false'"
              variables:
                FloatingLabelBehavior:
                  kind: 'import'
                  uris: [ '$importUri' ]
                  name: 'FloatingLabelBehavior'
    variables:
      hasFloatingPlaceholder:
        kind: 'fragment'
        value: 'arguments[hasFloatingPlaceholder]'
''');
    await resolveTestCode('''
import '$importUri';
final a = InputDecorationTheme(f: '');
''');
    await assertHasFix('');
  }
```

**Comment by bwilkerson** [comment] 2021-09-16 18:03
@DanTup Thanks, I can reproduce the problem using your test case too.

@Piinks I'm not sure I understand the intent of this portion of the fix-data:

```
argumentValue:
  expression: '{% hasFloatingPlaceholder %} ? {% FloatingLabelBehavior %}.auto : {% FloatingLabelBehavior %}.never'
  requiredIf: "hasFloatingPlaceholder != 'true' && hasFloatingPlaceholder != 'false'"
```

It seems like we shouldn't be referring to `hasFloatingPlaceholder` in the `expression` when we know that it doesn't have a value. I would have expected the expression to just be the default value for the argument.

**Comment by Piinks** [comment] 2021-09-16 18:40
Oh strange, I agree this looks like a case we would not need to have a rule for. I am not sure what I was thinking when I wrote it. 🙃 
I'll confirm and send out a fix for this today to remove it.

**Comment by Piinks** [comment] 2021-09-16 19:52
Fix is on https://github.com/flutter/flutter/pull/90217 :)

**Comment by bwilkerson** [comment] 2021-09-16 20:05
Given that there's a test for a constructor invocation with no arguments, that makes me wonder whether the test framework is somehow masking the exception reported above.

**Comment by Piinks** [comment] 2021-09-16 20:09
I think the error did not present itself for the invocation with no arguments because there was no analysis error/warning in that case.

The `error: ''` parameter I added creates an analysis error, which is when it checks to see if there is a rule available to fix. Is that right @bwilkerson?

**Comment by bwilkerson** [comment] 2021-09-16 20:11
Yes, that looks right to me. I should have looked at your PR before commenting.

**Comment by Piinks** [comment] 2021-09-17 16:20
This can be closed now, the fix has landed. :)
I do not have permission to close.

**Closed** 2021-09-17 16:25 UTC
Labels: area-analyzer, P3, analyzer-server, type-bug
