### ISSUE TITLE
Failures on Pass --force-nnbd-checks whenever NNBD experiment is enabled

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#41033] opened 2020-03-13 14:08 UTC
There are new test failures on [Pass --force-nnbd-checks whenever NNBD experiment is enabled](https://dart-review.googlesource.com/c/sdk/+/139289).

I'm trying to enable --force-nnbd-checks in the build files as the first step towards removing the flag completely.  When I do so, I see the following crashes on the VM.  It is especially interesting because the run time shouldn't be affected by the flag.

The tests
```
ffi/function_test/1 Crash (expected Pass)
ffi/structs_test Crash (expected Pass)
ffi/vmspecific_function_test/1 Crash (expected Pass)
language/async/await_test/02 Crash (expected Pass)
language/async/await_test/03 Crash (expected Pass)
language/async/await_test/none Crash (expected Pass)
lib/mirrors/dynamic_load_test Crash (expected Pass)
```
are failing on configurations
```
dartk-strong-linux-debug-x64
dartk-strong-linux-release-x64
```

**Comment by a-siva** [comment] 2020-03-13 16:56
We are still working through a number of strong mode issues (I approved a set of failures when I first turned on strong mode testing). I would suggest approving these tests and landing your CL to enable --force-nnbd-checks that way we can be sure folks making changes to the libraries will not add more new code that would have errors when this flag is enabled.

**Comment by crelier** [comment] 2020-04-10 21:34
Most of the listed tests are now passing. The remaining failing one is
ffi/structs_test Crash (expected Pass)

**Comment by dcharkes** [comment] 2020-04-14 09:54
We have no support for structs in NNBD yet, see https://github.com/dart-lang/sdk/issues/40247.

> ffi/structs_test Crash (expected Pass)

I do not see any crashes, only compile time failures on master, am I missing something?

```
tools/build.py -m debug -a x64 --nnbd dart ffi_test_functions runtime_kernel && tools/test.py -n dartk-strong-linux-debug-x64 ffi
...
FAILED: dartk-vm debug_x64 ffi/function_structs_test
Expected: Pass
Actual: CompileTimeError
```

I'm assuming you just copy pasted the `Crash` from the top of the issue and that it's just a failure. Closing as duplicate of https://github.com/dart-lang/sdk/issues/40247, please reopen if there is a crash that should be prevented @crelier.

**Closed by dcharkes** 2020-04-14 09:54 UTC
Labels: NNBD, area-vm, library-ffi

**Comment by crelier** [comment] 2020-04-14 16:43
Correct. I just copy pasted from the original list. There is no crash anymore, just CFE errors. Thanks.
