### ISSUE TITLE
Dart Analyzer Error - Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by fauzipadlaw** [dart-lang/sdk#39256] opened 2019-11-06 08:43 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA 192.6817.14.36.5947919`
- `2.7.0-edge.8bdca37e98a59bdb7f52daea9da838b1a60c1cdf`
- `AI-192.6817.14.36.5947919, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.8bdca37e98a59bdb7f52daea9da838b1a60c1cdf, server version 1.27.4, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [E:\elxr\v12\elxr_mobile], excluded: [E:\elxr\v12\elxr_mobile\.idea, E:\elxr\v12\elxr_mobile\.dart_tool, E:\elxr\v12\elxr_mobile\.idea, E:\elxr\v12\elxr_mobile\.pub, E:\elxr\v12\elxr_mobile\build]}, clientRequestTime: 1573018317830}
FileSystemException: Directory watcher closed unexpectedly, path = 'E:\elxr\v12\elxr_mobile'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:309:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, report.txt
```
Dart analysis server, SDK version 2.7.0-edge.8bdca37e98a59bdb7f52daea9da838b1a60c1cdf, server version 1.27.4, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [E:\elxr\v12\elxr_mobile], excluded: [E:\elxr\v12\elxr_mobile\.idea, E:\elxr\v12\elxr_mobile\.dart_tool, E:\elxr\v12\elxr_mobile\.idea, E:\elxr\v12\elxr_mobile\.pub, E:\elxr\v12\elxr_mobile\build]}, clientRequestTime: 1573018317830}
FileSystemException: Directory watcher closed unexpectedly, path = 'E:\elxr\v12\elxr_mobile'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:309:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


1573026631439 => {"id":"40","method":"analysis.setPriorityFiles","params":{"files":["E:\\elxr\\v12\\elxr_mobile\\pubspec.yaml"]},"clientRequestTime":1573026631439}
1573026631439 => {"id":"41","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["E:\\elxr\\v12\\elxr_mobile\\pubspec.yaml"],"CLOSING_LABELS":["E:\\elxr\\v12\\elxr_mobile\\pubs
1573026638519 <= {"id":"40"}
1573026638519 <= {"id":"41"}
1573026707688 => {"id":"42","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1573026707688}
1573026707688 => {"id":"43","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":[],"CLOSING_LABELS":[],"OUTLINE":[],"NAVIGATION":[],"HIGHLIGHTS":[],"IMPLEMENTED":[]}},"clientRe
1573026707689 <= {"id":"42"}
1573026707690 <= {"id":"43"}
1573028649600 => {"id":"44","method":"analysis.setPriorityFiles","params":{"files":["E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml"]},"clientRequestTime":1573028649600}
1573028649600 => {"id":"45","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml"],"CLOSING_LABELS":["
1573028649634 <= {"id":"44"}
1573028649635 <= {"id":"45"}
1573028655393 => {"id":"46","method":"analysis.updateContent","params":{"files":{"E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml":{"type":"add","content":"<manifest xmlns:and
1573028655475 <= {"id":"46","result":{}}
1573028657751 => {"id":"47","method":"analysis.updateContent","params":{"files":{"E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml":{"type":"add","content":"<manifest xmlns:and
1573028657752 <= {"id":"47","result":{}}
1573028664949 => {"id":"48","method":"analysis.updateContent","params":{"files":{"E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml":{"type":"add","content":"<manifest xmlns:and
1573028664957 <= {"id":"48","result":{}}
1573028667118 <= {"event":"analysis.errors","params":{"file":"E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml","errors":[]}}
1573028667120 <= {"event":"analysis.errors","params":{"file":"E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml","errors":[]}}
1573028667278 => {"id":"49","method":"analysis.updateContent","params":{"files":{"E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml":{"type":"add","content":"<manifest xmlns:and
1573028667282 <= {"id":"49","result":{}}
1573028671982 => {"id":"50","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1573028671982}
1573028671982 => {"id":"51","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":[],"CLOSING_LABELS":[],"OUTLINE":[],"NAVIGATION":[],"HIGHLIGHTS":[],"IMPLEMENTED":[]}},"clientRe
1573028671983 <= {"id":"50"}
1573028671984 <= {"id":"51"}
1573028700851 => {"id":"52","method":"analysis.updateContent","params":{"files":{"E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\AndroidManifest.xml":{"type":"remove"}}},"clientRequestTime":1573
1573028700852 <= {"id":"52","result":{}}
1573028701155 <= {"event":"analysis.flushResults","params":{"files":["E:\\elxr\\v12\\elxr_mobile\\android\\app\\src\\main\\java\\com\\the_elxr\\app\\MainActivity.java___jb_tmp___"]}}
1573029356107 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [E:\\elxr\\v12\\elxr_mobile], exclu
```

**Comment by keertip** [comment] 2019-11-06 09:09
Thanks for reporting this issue! This issue was previously reported at #39180,  please follow along there.

**Comment by keertip** [comment] 2019-11-06 09:09
Duplicate of #39180

**Closed by keertip** 2019-11-06 09:09 UTC
Labels: analyzer-crash-report, area-analyzer
