### ISSUE TITLE
Consider making num.clamp generic?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#30403] opened 2017-08-10 23:42 UTC
Currently `num.clamp` is defined as `(num, num) -> num`.  Making this generic would allow better static typing.

cc @floitschG @lrhn

**Comment by leafpetersen** [comment] 2017-08-10 23:43
See https://github.com/dart-lang/sdk/issues/30402 for some context.

**Comment by lrhn** [comment] 2017-08-11 14:00
It won't be easy to do that and preserve the current behavior, or maybe doing it at all.

What signature would you suggest for the method?
```dart
T clamp<T extends num>(T low, T high);  
```
This won't work.
The call `x.clamp(y, z)` can return any of `x`, `y` or `z`. That means that `num x = 42; x.clamp(0.0, 100.0);` will likely infer `T` as `double` and complain that the return value is `int`.

The problem is that the actual constraint is that `T` must be a type that both arguments and the value itself can be assigned to. We cannot express that constraint.

Even if we specialize the method for `int` and `double`, so we basically know the type of `this`, we still need:
```dart
T clamp<T extends ??>(T low, T high);
```
where `??` somehow restricts `T` to `int` and `num`, but avoids `double`

Maybe just add
```dart
int int.clampInt(int low, int high);
double double.clampDouble(double low, double high);
```
?

**Comment by leafpetersen** [comment] 2017-08-15 23:30
Hmm, yeah, unfortunate.  Overloading might help here, if you could use the type of the receiver.

Another option would be:

```
//num
num clamp(covariant num low, covariant num high);

//int
@override
int clamp(int low, int high)
```

**Comment by lrhn** [comment] 2017-08-16 06:21
Using `covariant` wouldn't work very well either.
In practice, it means that you have `int int.clamp(int,int)` and `double double.clamp(double, double)`, but there is no way you can call the `clamp` of `num x;` without testing the type of it first, and then you could just remove the `num.clamp` declaration completely and not be any worse off.

I think the best solution is to remove `clamp` from `num` and put it on `int` and `double`, or to keep it on `num` and put `clampInt` and `clampDouble` on `int` and `double`.

Or remove it from `num` and make it a static function `T clamp<T extends num>(T value, T min, T max)`. Then it can be used with both `int`, `double` and `num`.
(I don't see a good way to get "self" into the type system, short of adding self-types like `This clamp<T extends This>(T min, T max)`).

**Comment by floitschG** [comment] 2017-08-21 11:17
We are dropping `clamp` from `num` and specialize the functions on `int` and `double`.

**Comment by lukepighetti** [comment] 2019-09-07 23:16
Friendly ping for forward movement on this. Spent a few hours debugging an issue with num.clamp() on a double when I was expecting a double out the other side.

**Comment by lrhn** [comment] 2020-10-03 07:54
We will allow better static typing through special casing in the type system.

**Closed by lrhn** 2020-10-03 07:54 UTC
Labels: area-library, core-2, library-core
