### ISSUE TITLE
Enabled LSP preview is not working with the analyzer plugin as expected

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#45678] opened 2021-04-13 19:40 UTC
Hi! We are developing an additional linter for Dart and use analyzer plugin API (like sending `AnalysisErrorsParams`, etc.) to communicate with the analysis server.

If I enable LSP preview in VSCode and have the plugin enabled, VSCode starts display diagnostics a bit crazy. For example,

https://user-images.githubusercontent.com/21116742/114609505-8cc31a00-9ca7-11eb-8ba4-c4ae8d2f2eb6.mov

It works fine when LSP preview is disabled. We have an open issue with [a similar problem for vim](https://github.com/dart-code-checker/dart-code-metrics/issues/262) and after some research I don't think that this problem is on our side of the integration. Or I'm missing something.

Could there be a problem with the analysis server?

* Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
* VSCode version: 1.54.1
* Dart extension version: 3.21.1

**Comment by bwilkerson** [comment] 2021-04-13 19:53
@DanTup

**Comment by DanTup** [comment] 2021-04-13 20:01
@incendial is the plugin public so I could run it myself? If not, could you capture a log:

- Run the **Dart: Capture Analyzer Logs** command from the VS code command palette
- Reproduce the issue (type to trigger the flashing)
- Click **Cancel** on the logging notification to stop logging and open the log file

The log may include parts of your source so it's best to reproduce on a public/sample project.

There have been some fixes since the last stable release that fixed some issues (with errors vanishing and coming back), although I'm not sure they apply here. Still, it may be worth grabbing a bleeding-edge SDK from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/ to test with (see [here](https://dartcode.org/docs/quickly-switching-between-sdk-versions/) for an easy way to swap between SDK versions in VS Code) to see if it still occurs on latest code.

**Comment by incendial** [comment] 2021-04-13 20:26
Sure, here is the log file [Dart-Code-Log-2021-03-02 23-04-57.txt](https://github.com/dart-lang/sdk/files/6306445/Dart-Code-Log-2021-03-02.23-04-57.txt)
And the plugin is public, you can find it here https://github.com/dart-code-checker/dart-code-metrics.

I've tested it with the sdk version you shared and the issue is still reproducible.

**Comment by DanTup** [comment] 2021-04-14 13:57
@incendial thanks! I think I've tracked down the issue. It seems like there'a bug where when the server sends diagnostics to the client, it ignores the plugins errors. When the plugin sends errors, they're merged together. So there's a race - if the plugin produces its errors _before_ the server, they will be lost. If it produces them after the server, then they'll be merged in correctly.

**Closed** 2021-04-14 16:20 UTC
Labels: P2, analyzer-lsp, area-analyzer

**Comment by incendial** [comment] 2021-04-14 17:32
@DanTup oh, that's an interesting problem, I'm really happy that you tracked it down! As I can see you fixed it already, thank you very much! Could you share a version of the extension that will support the fix?

And could you please take a look at the issue we got for vim? Or maybe you know someone who can? https://github.com/dart-code-checker/dart-code-metrics/issues/262
Does it have the same problem underneath or it's a different one?

**Comment by DanTup** [comment] 2021-04-14 17:38
@incendial the fix is in the Dart analysis server, so it you'll need a new Dart SDK release to get it.

If you'd like to try it out before it's in a stable release, you could try a dev release (though it may take a few days to show up there - I'm not certain of the schedule) from https://dart.dev/tools/sdk/archive, or a bleeding-edge build from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/. I wouldn't recommend them for general work, but useful for testing the issue in indeed fixed.

The screenshot in the linked issue looks different - that looks like the servers view of the file does not match the editors, whereas this one was purely an issue with the diagnostics being transmitted to the editor. 

If someone can provide me instructions to repro that in VS Code, I'd definitely like to track that down too. I'll ping on the issue too.

**Comment by incendial** [comment] 2021-04-15 19:37
> the fix is in the Dart analysis server, so it you'll need a new Dart SDK release to get it.

Oh, right... Tested it with the latest version, works like a charm. And awesome that the LSP implementation allows to display multiline errors!

Thank you for taking a look at the vim issue, I hope the author will reply.
