### ISSUE TITLE
Stream.asyncMap() calls [convert] only once per event

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29615] opened 2017-05-15 09:32 UTC
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/asyncMap.html) of method dart:async:Stream.asyncMap() reads:

> Stream&lt;E&gt; asyncMap&lt;E&gt;(
> dynamic convert(
> T event
> )
> )
> Creates a new stream with each data event of this stream asynchronously mapped to a new event.
> 
> This acts like [map](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/map.html), except that convert may return a Future, and in that case, the stream waits for that future to complete before continuing with its result.
> 
> The returned stream is a broadcast stream if this stream is.

The description of Stream.map() reads:
> ...
> The returned stream is a broadcast stream if this stream is. **The convert function is called once per data event per listener.** If a broadcast stream is listened to more than once, each subscription will individually call convert on each data event.

The following sample code counts number of calls to `convert`:
```dart
import "dart:async";

Map<Object,int> convertLog = new Map<Object,int>();

dynamic convert(Object event) {
  convertLog[event] = 1 + convertLog.putIfAbsent(event, () => 0);
  return event;
}

Future<List> subscribe(Stream stream) {
  Completer<List> completer = new Completer<List>();
  List received = [];
  stream.listen(
      (event) {
        received.add(event);
      },
      onDone: () {
        completer.complete(received);
      }
  );
  return completer.future;
}

Future check(Stream<T> stream, List expected) {
  Stream converted = stream.asyncMap(convert);
  Future.wait([
    subscribe(converted),
    subscribe(converted),
    subscribe(converted)
  ]).then(
      (List<List> result) {
        print(convertLog);
      }
  );
}

main() {
  Stream stream = new Stream.fromIterable(['a', 'b', 'c']);
  check(stream.asBroadcastStream(), ['a', 'b', 'c']);
}
```
Output
>dart.exe  --checked test.dart
>{a: 1, b: 1, c: 1}

Expected output:
>dart.exe  --checked test.dart
>{a: 3, b: 3, c: 3}

Dart VM version: 1.23.0 (Fri Apr 21 03:13:00 2017) on "windows_x64"

**Comment by sgrekhov** [comment] 2020-07-01 12:56
The issue is still exists. Retested on `Dart VM version: 2.9.0-19.0.dev (dev) (Thu Jun 25 10:48:31 2020 +0200) on "windows_x64" ` with NNBD enabled

Example adopted to NNBD

```dart
import "dart:async";

Map<Object,int> convertLog = new Map<Object,int>();

dynamic convert(dynamic event) {
  convertLog[event] = 1 + convertLog.putIfAbsent(event, () => 0);
  return event;
}

Future<List> subscribe(Stream stream) {
  Completer<List> completer = new Completer<List>();
  List received = [];
  stream.listen(
      (event) {
    received.add(event);
  },
      onDone: () {
        completer.complete(received);
      }
  );
  return completer.future;
}

Future? check(Stream<dynamic> stream, List expected) {
  Stream converted = stream.asyncMap(convert);
  Future.wait([
    subscribe(converted),
    subscribe(converted),
    subscribe(converted)
  ]).then(
      (List<List> result) {
        print(convertLog);
      }
  );
}

main() {
  Stream stream = new Stream.fromIterable(['a', 'b', 'c']);
  check(stream.asBroadcastStream(), ['a', 'b', 'c']);
}
```

**Comment by lrhn** [comment] 2020-09-29 07:58
This behavior was something we hoped to change with Dart 2.0, but it didn't make the cut. Changing it is potentially a breaking change, but I do hope to get it through eventually.

**Comment by sgrekhov** [comment] 2023-12-07 10:22
> This behavior was something we hoped to change with Dart 2.0, but it didn't make the cut. Changing it is potentially a breaking change, but I do hope to get it through eventually.

@lrhn It's time of Dart 3.0 now but the issue stil exists. May be it makes sense to change  `Stream.asyncMap` documentation according to the current behavior? https://dart-review.googlesource.com/c/sdk/+/340402 does this. Please review

**Comment by lrhn** [comment] 2023-12-07 16:04
Yes. We should update the documentation to document what's going on.

Should we ever manage to change it, we can update the documentation agaiun.

**Comment by sgrekhov** [comment] 2023-12-13 08:31
Documentatin has been updated. Now the current behavior is according to the spec. Closing this issue

**Closed by sgrekhov** 2023-12-13 08:31 UTC
Labels: area-library, library-async, core-a, breaking-change
