### ISSUE TITLE
VM hangs when --enable-vm-service is supplied and there are compile-time errors

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42630] opened 2020-07-08 18:49 UTC
You can reproduce the problem with this program:
```dart
main() {
  oops;
}
```
Running this program in the usual way (`dart <filename>`) produces the expected error message:
```
../../tmp/test.dart:2:3: Error: Getter not found: 'oops'.
  oops;
  ^^^^
```
However, running the program with `dart --enable-vm-service <filename>` causes the VM to hang, producing no output.  If you interrupt the VM using Ctrl-C, only then does the error message appear.

This is particularly problematic when trying to debug under IntelliJ, since it supplies the `--enable-vm-service` flag by default.  I am hitting this a lot during SDK development because if I switch branches and forget to run `gclient sync`, I wind up with DEPS whose migration state doesn't match the allow-list, and so there are compile-time errors.

**Comment by stereotype441** [comment] 2020-07-08 18:49
@a-siva FYI

**Comment by a-siva** [comment] 2020-07-08 23:25
seems to be dart-dev related, if run the program as
dart --enable-vm-service --disable-dart-dev /tmp/oops.dart

it produces the right error:
Observatory listening on http://127.0.0.1:8181/ATbaCdSwJWs=/
/tmp/oops.dart:2:3: Error: Getter not found: 'oops'.
  oops;
  ^^^^

@bkonyi can you take a look at this.

**Comment by a-siva** [comment] 2020-07-08 23:56
seems to be flaky, sometimes it works sometimes it hangs and other times it produces the following stack trace

```
Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:623:24)
#1      _CompleterSink.add (package:web_socket_channel/src/sink_completer.dart:91:19)
#2      DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35:11)
#3      new _BinaryCompatiblePeer.<anonymous closure> (package:dds/src/binary_compatible_peer.dart:32:24)
#4      _HandlerSink.add (package:async/src/stream_sink_transformer/handler_transformer.dart:61:31)
#5      DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35:11)
#6      DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35:11)
#7      _JsonDocument.bind.<anonymous closure> (package:stream_channel/src/json_document_transformer.dart:32:12)
#8      _HandlerSink.add (package:async/src/stream_sink_transformer/handler_transformer.dart:61:31)
#9      DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35:11)
#10     DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35:11)
#11     ChannelManager.add (package:json_rpc_2/src/channel_manager.dart:67:19)
#12     Client._send (package:json_rpc_2/src/client.dart:148:16)
#13     Client.sendRequest (package:json_rpc_2/src/client.dart:107:5)
#14     Peer.sendRequest (package:json_rpc_2/src/peer.dart:99:15)
#15     _DartDevelopmentService._startDDSServer (package:dds/src/dds_impl.dart:64:30)
<asynchronous suspension>
#16     _DartDevelopmentService.startService (package:dds/src/dds_impl.dart:36:11)
<asynchronous suspension>
#17     DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:84:19)
#18     _DebuggingSession._startDDS (package:dartdev/src/commands/run.dart:244:41)
#19     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#26     _DebuggingSession._waitForRemoteServiceUri (package:dartdev/src/commands/run.dart)
<asynchronous suspension>
#27     _DebuggingSession.start (package:dartdev/src/commands/run.dart:218:7)
<asynchronous suspension>
#28     RunCommand.run (package:dartdev/src/commands/run.dart:123:50)
#29     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#30     DartdevRunner.runCommand (package:dartdev/dartdev.dart:218:24)
#31     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#32     new Future.sync (dart:async/future.dart:223:31)
#33     CommandRunner.run (package:args/command_runner.dart:112:14)
#34     runDartdev (package:dartdev/dartdev.dart:92:27)
#35     main (file:///usr/local/google/home/asiva/workspace/dart-ws3/sdk/pkg/dartdev/bin/dartdev.dart:18:9)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by a-siva** [comment] 2020-07-09 00:04
seems like a service isolate shutdown hang whenever the process hangs

```
(gdb) t a a bt

Thread 2 (Thread 0x7f59f1010700 (LWP 3305976)):
#0  0x00007f59f1110616 in epoll_wait (epfd=5, events=0x7f59f100fce0, maxevents=16, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00005601aec7a038 in dart::bin::EventHandlerImplementation::Poll(unsigned long) ()
#2  0x00005601aedbf765 in ?? ()
#3  0x00007f59f1323f27 in start_thread (arg=<optimized out>) at pthread_create.c:479
#4  0x00007f59f11102ef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f59f1012180 (LWP 3305974)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5601b100a110) at ../sysdeps/unix/sysv/linux/futex-internal.h:80
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5601b100a0c0, cond=0x5601b100a0e8) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5601b100a0e8, mutex=0x5601b100a0c0) at pthread_cond_wait.c:638
#3  0x00005601aef12f48 in dart::Monitor::WaitMicros(long) ()
#4  0x00005601aef7db0a in dart::ServiceIsolate::Shutdown() ()
#5  0x00005601aee21ef6 in dart::Dart::Cleanup() ()
#6  0x00005601aec76b76 in dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) ()
#7  0x00005601aec77799 in dart::bin::main(int, char**) ()
#8  0x00005601aec7819d in main ()

```

**Comment by bkonyi** [comment] 2020-07-09 00:10
I'm guessing this is a race caused by DartDev attempting to start DDS as the secondary VM shuts down after encountering a compilation error. I'll take a look.

**Comment by bkonyi** [comment] 2020-07-09 01:15
It looks like we end up in a weird state when the remote VM shuts down. I'm able to get reduce the frequency of the issue by making a few tweaks, but testing against my [WIP CL to bring DartDev into the same process](https://dart-review.googlesource.com/c/sdk/+/152588) seems to resolve the issue. It's almost ready for review, so hopefully I can get that in by EOW as a fix for this issue.

**Comment by bkonyi** [comment] 2020-07-21 18:48
Resolved in https://github.com/dart-lang/sdk/commit/157ebfe50f399c59a20d603acdf5143ceaa4cccf

**Closed by bkonyi** 2020-07-21 18:48 UTC
Labels: P1, area-dart-cli, area-vm, release blocker
