### ISSUE TITLE
type inference gets confused sometimes when variable should be dynamic

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/sdk#32880] opened 2018-04-13 17:17 UTC
* Dart SDK Version (`dart --version`)
$ dart --version
Dart VM version: 2.0.0-dev.48.0 (Fri Apr 13 13:35:30 2018 +0200) on "linux_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
N/A

The following code snippet results in an incorrect looking analyzer warning:

```dart
Map<String, Map> f = {'foo' : {'bar' : 52}};
void main() {
  var q;
  var z = f;
  List<String> keys = ['foo', 'bar'];
  for (String key in keys) {
    if (z.containsKey(key))
      z = z[key];
  }
  if (z is num) {
    q = z.toDouble();
  }
  print(q);
}
```

The warning is on 'z.toDouble()' -- it claims that z is a map of some kind:
```
~/dart/dartdoc
$ dartanalyzer --preview-dart-2 ~/foo.dart
Analyzing /usr/local/google/home/jcollins/foo.dart...
  error • The method 'toDouble' isn't defined for the class 'Map<String, Map>' at /usr/local/google/home/jcollins/foo.dart:11:11 • undefined_method
1 error found.
```

Since it's explicitly in an if block that says `if (z is num)` that seems implausible.

**Comment by bwilkerson** [comment] 2018-04-13 17:38
I believe that this is working as intended.

The static type of `z` is inferred to be `Map<String, Map>` (on line 4). Because `num` is not a subtype of  `Map`, there is no type promotion on line 10. Hence the error.

> I believe that we should never get inside that if block if z really is the type Dart and the analyzer claim it is.

That is true in this particular case because `num` cannot be subclassed outside of `dart:core`. And we could special case the classes that cannot be subclassed when specifying type promotion in the spec. We just don't.

But note that there is an implicit downcast to `Map<String, Map>` on line 8 (where `z` is being assigned to), so in Dart 2 this will fail (at runtime) before it gets to line 10 with a cast exception. To make this Dart 2 clean, you need to explicitly declare the type of `z` to be either `Object` or `dynamic`.

**Closed by bwilkerson** 2018-04-13 17:38 UTC
Labels: analyzer-preview-dart-2, area-analyzer, preview-dart-2

**Comment by jcollins-g** [comment] 2018-04-13 17:52
To document an offline discussion, re: making z dynamic, that's what I did in the real code that this snippet was based on.  But if this is the spec, then yes, this is working as intended.  :-(
