### ISSUE TITLE
spec: `void` arrow functions should allow any rhs type

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28942] opened 2017-03-01 16:05 UTC
This is the spec issue for https://github.com/dart-lang/sdk/issues/28939.

**Comment by mit-mit** [comment] 2017-03-15 09:03
Punting to 1.24 per dart-leads discussion.

**Comment by eernstg** [comment] 2017-05-10 08:39
Punting to 1.25, in agreement with Kasper: The 1.24 release does not depend on the concrete spec change, and the issue is well-understood.

**Comment by lrhn** [comment] 2017-05-22 14:24
Landed as 26d6e3596d034024605ecf9dcfa489b544fa6245.

**Closed by lrhn** 2017-05-22 14:24 UTC
Labels: area-specification
