### ISSUE TITLE
You have hit a bug in build_runner. The user.g.dart file would not get created and the build would fail.

### ISSUE THREAD

**Issue by Pushkar98** [dart-lang/sdk#34120] opened 2018-08-10 12:39 UTC
NoSuchMethodError: Attempted to use type 'FolderBasedDartSdk' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the FolderBasedDartSdk constructor and forget the 'new' operator?
Receiver: FolderBasedDartSdk
Tried calling: FolderBasedDartSdk(Instance of 'PhysicalResourceProvider', Instance of '_PhysicalFolder')
 My Flutter Doctor Looks like this:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.7-pre.52, on Mac OS X 10.13.6 17G65, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
[✓] Connected devices (1 available)

• No issues found!

Pubspec.yaml
dependencies:
  json_annotation: ^0.2.3

dev_dependencies:
  build_runner: ^0.9.0
  json_serializable: ^0.5.4

**Comment by natebosch** [comment] 2018-08-10 22:50
Duplicate of https://github.com/dart-lang/build/issues/1746

Please `pub upgrade` and see if it is resolved.

**Closed by natebosch** 2018-08-10 22:50 UTC
