### ISSUE TITLE
Dart memory leak using Flutter, using 12GB of memory

### ISSUE THREAD

**Issue by HerrNiklasRaab** [dart-lang/sdk#34802] opened 2018-10-15 21:55 UTC
Is it possible that this is a dublicate of this: https://github.com/dart-lang/sdk/issues/34271. But on the linked issue everything came back to normal without couse. But i installed my complete windows new and all required programs for programming flutter.

![unbenannt](https://user-images.githubusercontent.com/28401593/46971551-95c5d700-d0bc-11e8-882a-39d9cc4037fa.PNG)

I am using 16 GB RAM on my Pc.
This started happening while working without any reason as, far as I no.
VS Code Version is: 1.28.1
This always happens if i start VS Code. VS Code shows analysing in the bottom bar. Something like searching or go to definition don't work.

Link to sourcecode of my current project: https://drive.google.com/file/d/1Tk1GEuLKml0MJvFWP916Zszkeo-dpioe/view?usp=sharing

Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (3 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044

**Comment by HerrNiklasRaab** [comment] 2018-10-17 14:56
Just tried also o a complete new computer, this time a Mac, still same problem, but i found out running other flutter projects can be edited by visual studio wihout any memory problems. But we can still don't work, the whole development team is stucking on this. Can you please view this? If you need any further information i will immediatly help you.

Thanks and by the way, great work with flutter. Despite this bug I love to develop with this "library".

Niklas

**Comment by zoechi** [comment] 2018-10-17 14:58
Looks like #23155 and seems to hit more people since very recently.

**Comment by HerrNiklasRaab** [comment] 2018-10-17 15:05
Any idea to fix or workaround, do you really think those two bugs are related? Don't understand me wrong you are as I think way more experienced with flutter.

Something like a warning will not be a problem, but the analyser is not working at all and is using an unpractical amount of memory. But it must be a problem with dart analyser or with my code.

**Comment by zoechi** [comment] 2018-10-17 15:10
@DanTup is investigating there already. 
I don't have much related knowledge, just thought that it might be useful to connect these 2 issues.

**Comment by HerrNiklasRaab** [comment] 2018-10-17 19:11
One of our developers found the problem, but this is still a bug.  He created a new project and copied file by file the files from the old to the new project and looked when the analyser starts to need these excessive amounts of memory. This is the most curious cause for a bug I'v ever had. The cause is follwoing file: 
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_simple_dependency_injection/injector.dart';
import 'package:hapi/services/global_service.dart';
import 'package:scoped_model/scoped_model.dart';

class SearchModel extends Model{
  GlobalService _globalService = Injector.getInjector().get<GlobalService>();

  np //**If we romve this statement, everything seems to happen without any problems**

  Future<Stream<QuerySnapshot>> search(String input) async{
    return _globalService.searchUser(input);
  }
}
```

Only typing a "np" causes this problem, if you delete the "np" and modify the file in any other way, this problem does not come up.

Very curious, hopefully it helped and the error is fixed soon.

Niklas

**Comment by whitfin** [comment] 2018-10-29 06:39
I've seen these leaks often recently when working with Flutter. It *always* seems to be related to `Future`. It happens (sometimes) when a signature is tagged with `Future` as a return type; memory consumption spikes to insane amounts (I've seen up to 26GB so far). 

Dropping the explicit signature (if you can find the one causing the issue) stops the leak. It's a big problem because I'm practically forced to avoid typing in this scenario.

**Comment by zoechi** [comment] 2018-10-29 08:00
Looks like a dup of #34850 and should be fixed. It might take a bit until it lands in `master`, then in `dev`, and later `beta`

**Comment by zoechi** [comment] 2018-11-22 13:37
@mxdpeep please post the output of `flutter doctor -v`

**Comment by DanTup** [comment] 2018-11-22 14:06
> dart.exe is eating memory even if not in use -> just install Flutter/Dart package to VSCode and voilá -> memory running out!

Can you clarify what you mean by "not in use"? The Dart VM runs the language server that provides functionality like the analysis results shown in the Problems view. If you've installed the plugins and opened a non-Dart project and `dart.exe` is running, please open a bug at [Dart-Code/Dart-Code](https://github.com/Dart-Code/Dart-Code).

If you've got a Dart project open, then it's normal for dart.exe to run because it'll be analyzing you project. Of course, it shouldn't consume all your RAM, but if you're not on the latest versions then you might be hitting this bug. Please confirm the version of Flutter or the Dart SDK being used (if a non-Flutter project). You can see these in the status bar of VS Code when you have a `.dart` file open:

<img width="258" alt="screen shot 2018-11-22 at 2 06 22 pm" src="https://user-images.githubusercontent.com/1078012/48907593-d35a1480-ee5f-11e8-8b8e-ba2450982b9e.png">

**Comment by HerrNiklasRaab** [comment] 2018-11-22 15:04
@DanTup I provided you a reproduction of the bug (See issue description), aren't you able to reproduce?

**Comment by DanTup** [comment] 2018-11-22 15:23
@HerrNiklasRaab This issue was believed to be a dupe of https://github.com/dart-lang/sdk/issues/34850 which was reproduced and fixed in the Dart SDK. Are you still seeing it with the latest code?

(my last comments were in response to @mxdpeep who appeared to be hitting this issue).

**Comment by DanTup** [comment] 2018-11-22 15:33
Np! Do let us know if you still see it in latest and we can look again.

**Comment by DanTup** [comment] 2018-11-29 08:45
Since there's been no response, I'll close this on the assumption it's a dupe of #34850. If anybody believes otherwise, please shout!

**Closed by DanTup** 2018-11-29 08:45 UTC
Labels: area-analyzer
