### ISSUE TITLE
co19/Language/Libraries_and_Scripts/Scripts/top_level_main_t01 failed on vm-kernel-precomp-nnbd-win-release-x64, dartkp-weak-asserts-win-release-x64

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#47136] opened 2021-09-07 18:17 UTC
from [logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8836731325868711841/+/u/test_results/new_test_failures__logs_)
```
/==============================================================================================================================================\
| dartkp-strong-win-release-x64:co19/Language/Libraries_and_Scripts/Scripts/top_level_main_t01 is new and failed (RuntimeError, expected Pass) |
\==============================================================================================================================================/

--- Command "vm_compile_to_kernel" (took 02.000940s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & C:\b\s\w\ir\pkg\vm\tool\gen_kernel.bat --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp-strong-win-release-x64\short2464_pts_Scripts_top_level_main_t01\out.dill C:\b\s\w\ir\tests\co19\src\Language\Libraries_and_Scripts\Scripts\top_level_main_t01.dart --packages=C:\b\s\w\ir\.packages -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 04.000815s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\gen_snapshot --snapshot-kind=app-aot-elf --elf=C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-win-release-x64/short2464_pts_Scripts_top_level_main_t01/out.aotsnapshot --loading-unit-manifest=C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-win-release-x64/short2464_pts_Scripts_top_level_main_t01/ignored.json --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp-strong-win-release-x64\short2464_pts_Scripts_top_level_main_t01\out.dill

exit code:
0

--- Command "remove_kernel_file" (took 36ms):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & cmd.exe /c del C:\b\s\w\ir\out\ReleaseX64\generated_compilations\dartkp-strong-win-release-x64\short2464_pts_Scripts_top_level_main_t01\out.dill

exit code:
0

--- Command "vm" (took 01.000545s):
set DART_CONFIGURATION=ReleaseX64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\ReleaseX64\crashpad_handler.exe & out\ReleaseX64\dart_precompiled_runtime.exe --sound-null-safety --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.packages C:/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-win-release-x64/short2464_pts_Scripts_top_level_main_t01/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <0>, actual: <254>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:19)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:29)
#2      run_main.<anonymous closure> (file:///C:/b/s/w/ir/tests/co19/src/Language/Libraries_and_Scripts/Scripts/top_level_main_t01.dart:31)
<asynchronous suspension>
#3      run_main (file:///C:/b/s/w/ir/tests/co19/src/Language/Libraries_and_Scripts/Scripts/top_level_main_t01.dart:29)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartkp-strong-win-release-x64 co19/Language/Libraries_and_Scripts/Scripts/top_level_main_t01
```

**Comment by aam** [comment] 2021-09-07 18:21
cc @sgrekhov per https://dart-review.googlesource.com/c/sdk/+/212563

**Comment by sgrekhov** [comment] 2021-09-08 03:25
@aam I'm unable to reproduce the issue locally on the fresh SDK
```
sgrekhov@SGREKHOV-HP:~/Google/dart-sdk/sdk$ python3 tools/test.py -n dartkp-strong-win-release-x64 co19/Language/Libraries_and_Scripts/Scripts/top_level_main_t01
Test configuration:
    dartkp-strong-win-release-x64(architecture: x64, compiler: dartkp, mode: release, runtime: dart_precompiled, system: win, nnbd: strong, builder-tag: vm_nnbd)
Suites tested: co19
[00:13 | 100% | +    1 | -    0]

=== All 1 test passed ===
sgrekhov@SGREKHOV-HP:~/Google/dart-sdk/sdk$ out/ReleaseX64/dart --version
Dart SDK version: 2.15.0-edge.bc43e97b74c04d623c37716edb786a48b6f49aca (be) (Wed Sep 8 01:16:57 2021 +0000) on "linux_x64"
```

**Comment by sgrekhov** [comment] 2021-09-10 03:17
@aam Just noticed that you use Windows and I Linux. It's starnge that `dartkp-strong-win-release-x64` configuration can be run on Linux without any issues. I'll retest on Windows

**Comment by sgrekhov** [comment] 2021-09-13 09:37
@aam I don't have setup SDK under Windows and therefore unable to check this via test environment. But it looks like `// OtherResources=top_level_main_t01_lib.dart` doesn't work. Could you please check that `top_level_main_t01_lib.dart` file presents in the same directory where the aot.snapshot is (`C:/src/dart-sdk/sdk/out/ReleaseX64/generated_compilations/dartkp-strong-win-release-x64/short1_pts_Scripts_top_level_main_t01/`)? It looks like it doesn't

**Comment by aam** [comment] 2021-09-13 17:48
The root cause for the failure is that pathSeparator on Windows is backslash, but Platform.script is a uri, meaning it has forward slashes as separators even on Windows: https://github.com/dart-lang/co19/blob/master/Language/Libraries_and_Scripts/Scripts/top_level_main_t01.dart#L23

**Comment by sgrekhov** [comment] 2021-09-14 03:46
@aam thank you! Fixed by https://github.com/dart-lang/co19/commit/651e41bbebf6135f60809dd93d81e8680d8b0179

**Closed by sgrekhov** 2021-09-14 03:46 UTC
Labels: area-vm, gardening
