### ISSUE TITLE
NoSuchMethodError: The getter 'iterator' was called on null

### ISSUE THREAD

**Issue by Nipodemos** [dart-lang/sdk#36943] opened 2019-05-12 21:40 UTC
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I was typing `part 'ProductDAO.dart';` and suddenly this error appeared. Don't know if it matters, but the part is to a file that does not exist yet. (but i did other time and never experienced this issue)

### Versions

- Flutter SDK 1.5.9-pre.216
- Visual Studio Code 1.33.1
- Dart Code 3.0.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.0.1
```

### Exception

Captured exception

```text
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:579:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by a-siva** [comment] 2019-08-12 17:11
appears to be a duplicate of https://github.com/dart-lang/sdk/issues/36638

**Closed by a-siva** 2019-08-12 17:11 UTC
Labels: area-analyzer, closed-duplicate
