### ISSUE TITLE
Nullability promotion issue with local variable usages in iterators

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/sdk#51183] opened 2023-01-31 04:25 UTC
This tracker is for issues related to: **Analyzer**.

When I was developing in flutter_tools, I found a weird promotion with the nullability of a local variable.

![image](https://user-images.githubusercontent.com/15884415/215663198-36307705-f331-4c11-9ba3-7256576a7e43.png)

A simple example for this issue:
```dart
void main() {
  final String? test;
  final List<String> testList = [];
  if (1 * 2 == 2) {
    test = 'Yes';
  } else {
    test = null;
  }
  if (test != null) {
    testList.removeWhere((e) => e.contains(test)); // <-- Raises exception.
  }
}
```

I was wondering at this point why the variable cannot be proofed as non-null.

**Comment by eernstg** [comment] 2023-01-31 08:51
The reason why `test` isn't considered non-null in the invocation of `contains` is actually the very fact that `test` occurs in that particular location!

The point is that the function literal `(e) => e.contains(test)` evaluates to a function object, and the flow analysis of Dart does not attempt to keep track of all the locations where that function object might be called. For instance, if we're calling a method (basically any method of any receiver) then we don't know the exact piece of code which is going to run, and that piece of code might then have access to this function object, so it might be called. If that could occur at a point in time where `test` has the value null then it would be unsound to consider `test` non-nullable in this function literal.

We have had requests for an improved analysis of this situation. Perhaps it would be possible to recognize that the function object could not possibly be called at any point in time where `test == null`. However, this is a complex step in the analysis, and it is a well-known fact that there are some situations where the current analysis isn't able to detect some guarantees that a human reader would see rather easily.

In any case, you can help the flow analysis by introducing a new local variable whose value is never nullable:

```dart
void main() {
  final String? test;
  final List<String> testList = [];
  if (1 * 2 == 2) {
    test = 'Yes';
  } else {
    test = null;
  }
  if (test != null) {
    var test1 = test;
    testList.removeWhere((e) => e.contains(test1));
  }
}
```

**Comment by eernstg** [comment] 2023-01-31 08:55
@stereotype441, I searched for an issue which is requesting improvements in the flow analysis of variables whose value is read (not written) in a local function object, but didn't find anything spot on. Are you aware of any such issue? Otherwise, I think we could move this issue to the language repository and make it the go-to issue for this feature request.

**Comment by asashour** [comment] 2023-01-31 09:56
This is a duplicate of https://github.com/dart-lang/language/issues/1536, for which there is CL which make the OP test pass, in [sdk/277880](https://dart-review.googlesource.com/c/sdk/+/277880)

**Comment by eernstg** [comment] 2023-01-31 10:07
@asashour, that was exactly what I was looking for, thanks!

**Closed by eernstg** 2023-01-31 10:07 UTC
