### ISSUE TITLE
DateTime.toLocal() ignores timezone for UNIX timestamps before 1970-01-01T00:00:00.000Z

### ISSUE THREAD

**Issue by enloc-port** [dart-lang/sdk#44656] opened 2021-01-13 07:40 UTC
Using `.toLocal()` on DateTimes before 01.01.1970 (thus with a negative UNIX timestamp) seemingly results in the timezone information getting lost.

```
final DateTime date1 = DateTime.parse('1970-01-01T00:59:59.999+01:00');
final DateTime date2 = DateTime.parse('1970-01-01T01:00:00.000+01:00');
final DateTime date3 = DateTime.parse('1970-01-01T01:00:00.001+01:00');

// executing the following lines on a machine with timezone UTC+01:00

print(date1.toLocal().toIso8601String());
// expected: 1970-01-01T00:59:59.999
// actual:   1969-12-31T23:59:59.999

print(date2.toLocal().toIso8601String());
// expected: 1970-01-01T01:00:00.000
// actual:   1970-01-01T01:00:00.000

print(date3.toLocal().toIso8601String());
// expected: 1970-01-01T01:00:00.001
// actual:   1970-01-01T01:00:00.001
```

Tested on Windows 10 Pro x64 with the following Flutter and Dart version:
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (5 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Comment by lrhn** [comment] 2021-01-13 11:47
It seems to work correctly in the browser and on Linux, so it's a VM-on-Windows specific problem.

**Comment by enloc-port** [comment] 2021-01-13 12:37
> 
> 
> It seems to work correctly in the browser and on Linux, so it's likely a VM-on-Windows specific problem.

Do you mean by that, with the exact same version? Because I could not reproduce this on dartpad.dev, but I figured since dartpad is "Based on Flutter 1.25.0-8.2.pre Dart SDK 2.10.4" (as of when I tested the code in dartpad), it might be version-related as well.

**Comment by lrhn** [comment] 2021-01-13 14:42
I didn't ensure that it was the same version, but this is also not somethin I expect to have changed recently.
The Linux version I tested was built from a very recent tip-of-tree checkout.

**Comment by lrhn** [comment] 2021-03-22 13:39
This appears to be a Windows-only issue, and likely caused by Windows simply not providing the correct time zone information. 
If you run the following program:
```dart
main() {
  var date0 = DateTime(1970, 1, 1);
  var date1 = DateTime.parse('1970-01-01T00:59:59.999+01:00');

  print(date0.timeZoneOffset);
  print(date0);

  print(date1.timeZoneOffset);
  print(date1);

  var local = date1.toLocal();
  print(local.timeZoneOffset);
  print(local);

  var local1 = DateTime(1969, 12, 31, 23, 59, 59);
  print(local1.timeZoneOffset);
  print(local1);
}
```
it goes:
```
$ TZ=GMT-1 dart tz.dart
1:00:00.000000
1970-01-01 00:00:00.000
0:00:00.000000
1969-12-31 23:59:59.999Z
1:00:00.000000
1970-01-01 00:59:59.999
1:00:00.000000
1969-12-31 23:59:59.000
```
on Linux and 
```
λ set TZ=GMT-1 & dart tz.dart
1:00:00.000000
1970-01-01 01:00:00.000
0:00:00.000000
1969-12-31 23:59:59.999Z
0:00:00.000000
1969-12-31 23:59:59.999
0:00:00.000000
1969-12-31 23:59:59.000
```
on Windows. Local times before epoch appears to have no time zone information, *even with an explicit time zone set*.

I can't say whether we're doing something wrong, or it's Windows doing it wrong, but assigning to the VM for the integration logic.

**Comment by pamtbaau** [comment] 2022-04-05 08:24
@lrhn, I'm having two programs using the same sqlite database containing dates in epoch milliseconds.
Both apps run on same platform: Windows 10

Electron/Javascript:
- All goes well

Flutter/Dart:
- Dates < 1970-01-01 are incorrect: No difference between `toLocal()` and `toUtc()`.
- Dates >= 1970-01-01 are correct

If the issue is caused by Windows, Javascripts seems to be able to fix it.

Question:
- Is there a workaround?
- Is this going to be fixed?

**Comment by aam** [comment] 2023-11-16 21:55
> on Windows. Local times before epoch appears to have no time zone information, _even with an explicit time zone set_.

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=msvc-170 doesn't support negative seconds, linux does.
So https://github.com/dart-lang/sdk/blob/272b9d28a8361be1e4a8d5e2d29f0a97554ff8cb/runtime/vm/os_win.cc#L90 fails to get tz offset, defaults to 0.

**Comment by aam** [comment] 2023-11-17 18:10
https://dart-review.git.corp.google.com/c/sdk/+/336803 with proposed fix

**Closed** 2023-11-20 18:52 UTC
Labels: area-vm, P3, library-core, os-windows, type-bug, triaged
