### ISSUE TITLE
Dart analytics fails.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#55248] opened 2024-03-20 15:32 UTC
Does not repro on all computers. Repros on polina-c's computer. Feel free to ping me.

1. Configure [devtools_tool] https://github.com/flutter/devtools/blob/master/CONTRIBUTING.md#set-up-your-devtools-environment
2. Run devtools_tool pub-get in `devtools/packages/devtools_app`

```
polinach-macbookpro3:devtools_app polinach$ flutter --version
Flutter 3.21.0-11.0.pre.48 • channel master • git@github.com:flutter/flutter.git
Framework • revision b96c13d1e9 (4 hours ago) • 2024-03-20 07:49:37 -0400
Engine • revision 883adfe2ef
Tools • Dart 3.4.0 (build 3.4.0-251.0.dev) • DevTools 2.34.0-dev.5
```

```
devtools_app polinach$ devtools_tool fix-goldens --run-id=8354042980
An unexpected error was encountered by the Dart CLI.
Please file an issue at https://github.com/dart-lang/sdk/issues/new with the following details:

Invocation: 'dart run /Users/polinach/_/devtools/tool/bin/devtools_tool.dart fix-goldens --run-id=8354042980'
Exception: 'type 'Null' is not a subtype of type 'int' in type cast'
Stack Trace:
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:97:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:101:7)
#2      Session.initialize (package:unified_analytics/src/session.dart:73:27)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:459:21)
#4      new Analytics (package:unified_analytics/src/analytics.dart:87:12)
#5      createUnifiedAnalytics (package:dartdev/src/unified_analytics.dart:23:10)
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:165:27)
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#8      new Future.sync (dart:async/future.dart:306:31)
#9      CommandRunner.run (package:args/command_runner.dart:122:14)
#10     runDartdev (package:dartdev/dartdev.dart:46:29)
#11     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:33)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by mit-mit** [comment] 2024-03-20 15:52
Duplicate of https://github.com/dart-lang/sdk/issues/55212 (which also contains steps to recover)

**Comment by DanTup** [comment] 2024-03-20 15:52
Existing issues here:

- https://github.com/dart-lang/sdk/issues/55212
- https://github.com/dart-lang/tools/issues/252

The workaround is to delete `~/.dart-tool/dart-flutter-telemetry-session.json` (or `AppData\Roaming\.dart-tool\dart-flutter-telemetry-session.json` on Windows)

**Closed by mit-mit** 2024-03-20 15:52 UTC
