### ISSUE TITLE
Analyzer should warn about uncommented use of commented type parameters

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#26137] opened 2016-03-30 19:05 UTC
The following code:

``` dart
foo/*<T>*/() => <T>[];
```

is clearly invalid; it will fail in any implementation that's not aware of the commented generic syntax, including the Dart VM. The analyzer should warn about it even in strong mode to help users avoid the failures like this.

**Comment by jmesserly** [comment] 2016-03-30 19:13
Related to these closed bugs: https://github.com/dart-lang/sdk/issues/24985#issuecomment-185986526, https://github.com/dart-lang/sdk/issues/25637#issuecomment-185989485

Unfortunately we don't have the capability in the architecture to catch things like this. For better or worse a decision was made early on to invest minimally in the generic method comments, to keep it easy to ditch comments when generic method syntax is implemented in the VM. I think that reasoning still holds.

(By design, the scanner is the only one that knows much about the comments -- even the parser only knows a little bit, only enough to find the comments and insert them in the token stream. The benefit is nothing after that knows about comments, so we can easily transition to the real syntax, because from most of the Analyzer's perspective, there is no comments, only the real syntax. Unfortunately, it means the comments aren't first class, and we can't do semantic analysis on them, for example, to issue errors about incorrect usage of the comment form.)

**Comment by jmesserly** [comment] 2016-03-30 19:15
@vsmenon or @floitschG might have an update on the status of real generic method syntax?

**Comment by eernstg** [comment] 2016-03-31 08:06
I'm working on generic method syntax; currently we can parse most of it, but we also need to integrate the type variables with the static analysis (it might work to consider them to denote `dynamic`, but we haven't explored that yet). So it's coming.

**Comment by bwilkerson** [comment] 2018-01-28 17:42
Given that support for the comment syntax is being removed, I'm going to close this issue.

**Closed by bwilkerson** 2018-01-28 17:42 UTC
Labels: P3 low, Type: enhancement, analyzer-strong-mode, area-analyzer
