### ISSUE TITLE
Uncaught RequestError code: SERVER_ERROR - AnalysisException: Cannot compute RESOLVED_UNIT for /home/robert/tmp/animations/lib/Game.dart in /home/robert/tmp/animations/lib/Game.dart Caused by Unexpected exception while performing ComputeConstantValueTask

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#25156] opened 2015-12-07 19:09 UTC
_From @4stern on December 7, 2015 6:23_

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.4.16
### Stack Trace

```
Uncaught [RequestError code: SERVER_ERROR, message: AnalysisException: Cannot compute RESOLVED_UNIT for /home/robert/tmp/animations/lib/Game.dart in /home/robert/tmp/animations/lib/Game.dart
Caused by Unexpected exception while performing ComputeConstantValueTask for element int keyLeft in source /home/robert/tmp/animations/lib/steering/KeyboardSteering.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

Caused by The null object does not have a getter 'declaredVariables'.

```
NoSuchMethodError: method not found: 'declaredVariables'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ComputeConstantValueTask.internalPerform (package:analyzer/src/task/dart.dart:1705)
#3      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#4      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#5      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#6      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#7      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#9      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#10     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#11     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#12     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#13     _rootRun (dart:async/zone.dart:903)
#14     _CustomZone.run (dart:async/zone.dart:802)
#15     _CustomZone.runGuarded (dart:async/zone.dart:708)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#17     _rootRun (dart:async/zone.dart:907)
#18     _CustomZone.run (dart:async/zone.dart:802)
#19     _CustomZone.runGuarded (dart:async/zone.dart:708)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
]
```

```
At /home/robert/.atom/packages/dartlang/web/entry.dart.js:21314

[RequestError code: SERVER_ERROR, message: AnalysisException: Cannot compute RESOLVED_UNIT for /home/robert/tmp/animations/lib/Game.dart in /home/robert/tmp/animations/lib/Game.dart
Caused by Unexpected exception while performing ComputeConstantValueTask for element int keyLeft in source /home/robert/tmp/animations/lib/steering/KeyboardSteering.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:320)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:903)
#11     _CustomZone.run (dart:async/zone.dart:802)
#12     _CustomZone.runGuarded (dart:async/zone.dart:708)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#14     _rootRun (dart:async/zone.dart:907)
#15     _CustomZone.run (dart:async/zone.dart:802)
#16     _CustomZone.runGuarded (dart:async/zone.dart:708)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

Caused by The null object does not have a getter 'declaredVariables'.

NoSuchMethodError: method not found: 'declaredVariables'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ComputeConstantValueTask.internalPerform (package:analyzer/src/task/dart.dart:1705)
#3      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#4      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#5      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:271)
#6      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:246)
#7      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1098)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:170)
#9      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1096)
#10     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#11     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:798)
#12     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#13     _rootRun (dart:async/zone.dart:903)
#14     _CustomZone.run (dart:async/zone.dart:802)
#15     _CustomZone.runGuarded (dart:async/zone.dart:708)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#17     _rootRun (dart:async/zone.dart:907)
#18     _CustomZone.run (dart:async/zone.dart:802)
#19     _CustomZone.runGuarded (dart:async/zone.dart:708)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)

]
    at [object Object].dart.wrapException (/home/robert/.atom/packages/dartlang/web/entry.dart.js:22336:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:41645:19)
    at _AsyncCallbackEntry.dart._AsyncCallbackEntry.callback$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:40519:30)
    at [object Object].dart._microtaskLoop (/home/robert/.atom/packages/dartlang/web/entry.dart.js:39342:12)
    at [object Object].dart._microtaskLoopEntry (/home/robert/.atom/packages/dartlang/web/entry.dart.js:39348:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:21664:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:23504:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/home/robert/.atom/packages/dartlang/web/entry.dart.js:21305:25)
    at [object Object].dart._callInIsolate (/home/robert/.atom/packages/dartlang/web/entry.dart.js:20949:28)
    at dart.invokeClosure (/home/robert/.atom/packages/dartlang/web/entry.dart.js:22484:18)
```
### Commands

```
     -5:16.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.7.0 tabs:close-all-tabs (li.tab.sortable.active.right-clicked)
```
### Config

``` json
{
  "core": {
    "followSymlinks": false
  },
  "dartlang": {
    "sdkLocation": "/usr/lib/dart",
    "showOutlineView": false
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v7.14.1
dartlang, v0.4.16
linter, v1.11.3

# Dev
No dev packages
```

_Copied from original issue: dart-atom/dartlang#615_

**Comment by stereotype441** [comment] 2015-12-07 19:37
The task model spawned a task to evaluate the value of a constant whose element had a `.context` value of null.  The most likely explanation I can think of for this is that some stale data was somehow left behind in the analysis cache, pointing to elements that have since been recomputed.

I'm not sure how to proceed from here--probably we are not going to be able to track it down further without substantial instrumentation data, and we don't have the infrastructure to collect that data if we can't reproduce it internally.

**Comment by bwilkerson** [comment] 2015-12-07 19:54
There is another issue (closed as of this writing) that resulted from an element that didn't have an enclosing element. (#25063) I wonder whether they might be related.

**Comment by bwilkerson** [comment] 2017-08-25 19:00
I believe that this is now obsolete.

**Closed by bwilkerson** 2017-08-25 19:00 UTC
Labels: analyzer-server, analyzer-stability, area-analyzer, P2 medium, Type: bug
