### ISSUE TITLE
[vm/ffi] Support inline arrays

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37902] opened 2019-08-18 22:53 UTC
Inline arrays have a statically-defined size, e.g. `int[20]`, and can appear inside structs in their unpacked form.

**Comment by dcharkes** [comment] 2019-10-25 12:48
duplicate of https://github.com/dart-lang/sdk/issues/35763.

**Closed by dcharkes** 2019-10-25 12:48 UTC
Labels: area-vm, library-ffi
