### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by ycrack** [dart-lang/sdk#35254] opened 2018-11-26 08:29 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-183.4284.148`
- `2.1.0-dev.9.4`
- `IU-183.4284.148, JRE 1.8.0_152-release-1343-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14, screens 1440x900  Retina`

# Exception

[report.txt](https://github.com/dart-lang/sdk/files/2614590/report.txt)

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: /Users/ycrack/Develop/myspon/lib/models/card.dart context: exception_20181126_172547_002
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
#2      ConstantVisitor.visitSimpleIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1435:12)
#3      _ConstantVerifier_validateInitializerExpression.visitSimpleIdentifier (package:analyzer/src/dart/constant/constant_verifier.dart:660:18)
#4      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9679:49)
#5      ConstantVerifier._validateInitializerExpression (package:analyzer/src/dart/constant/constant_verifier.dart:573:40)
#6      ConstantVerifier._validateInitializerInvocationArguments (package:analyzer/src/dart/constant/constant_verifier.dart:599:7)
#7      ConstantVerifier._validateConstructorInitializers (package:analyzer/src/dart/constant/constant_verifier.dart:487:9)
#8      ConstantVerifier.visitConstructorDeclaration (package:analyzer/src/dart/constant/constant_verifier.dart:108:7)
#9      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2932:15)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)

**Comment by stereotype441** [comment] 2018-11-30 18:07
Duplicate of #35241

**Closed by stereotype441** 2018-11-30 18:07 UTC
Labels: area-analyzer
