### ISSUE TITLE
Analysis Server throws an error when analyzing deferred_load.dart file

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25049] opened 2015-11-26 12:18 UTC
`Dart VM version: 1.14.0-edge.e3457758ed7e2b24263bcbd9831cd764ce9fd110 (Tue Nov 24 16:05:37 2015) on "windows_x64"`
Presence of [this file](https://github.com/dart-lang/sdk/blob/1590970ccc03989923629ad590fd850dd7d85e6d/pkg/compiler/lib/src/deferred_load.dart) in the project (exactly in this revision) makes DAS to throw an error. Errors may be different, 2 examples pasted below:
```
Dart analysis server, SDK version 1.14.0-edge.e3457758ed7e2b24263bcbd9831cd764ce9fd110, server version 1.12.0, error: Task failed: ComputePropagableVariableDependenciesTask for element Map<_DeferredImport, ImportDescription> _deferredImportDescriptions in source C:\dart_projects\untitled1\bin\main.dart
NodeLocator failed to find a variable's declaration
#0      ComputePropagableVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:2064)
#1      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#2      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#3      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#4      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#5      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1116)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#7      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114)
#8      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#9      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#10     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#11     _rootRun (dart:async/zone.dart:903)
#12     _CustomZone.run (dart:async/zone.dart:802)
#13     _CustomZone.runGuarded (dart:async/zone.dart:708)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#15     _rootRun (dart:async/zone.dart:907)
#16     _CustomZone.run (dart:async/zone.dart:802)
#17     _CustomZone.runGuarded (dart:async/zone.dart:708)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      ComputePropagableVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:2064)
#1      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#2      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#3      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#4      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#5      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1116)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#7      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114)
#8      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#9      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#10     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#11     _rootRun (dart:async/zone.dart:903)
#12     _CustomZone.run (dart:async/zone.dart:802)
#13     _CustomZone.runGuarded (dart:async/zone.dart:708)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#15     _rootRun (dart:async/zone.dart:907)
#16     _CustomZone.run (dart:async/zone.dart:802)
#17     _CustomZone.runGuarded (dart:async/zone.dart:708)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:198)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```
```
Dart analysis server, SDK version 1.14.0-edge.e3457758ed7e2b24263bcbd9831cd764ce9fd110, server version 1.12.0, error: Exception from assist contributor: DefaultAssistContributor
Cannot compute RESOLVED_UNIT for C:\dart_projects\untitled1\bin\main.dart in C:\dart_projects\untitled1\bin\main.dart
#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1217)
#2      DartAssistContributor.computeAssists.<computeAssists_async_body> (package:analysis_server/plugin/edit/assist/assist_dart.dart:64)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:903)
#5      _CustomZone.run (dart:async/zone.dart:802)
#6      _CustomZone.runGuarded (dart:async/zone.dart:708)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#8      _rootRun (dart:async/zone.dart:907)
#9      _CustomZone.run (dart:async/zone.dart:802)
#10     _CustomZone.runGuarded (dart:async/zone.dart:708)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#13     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by NodeLocator failed to find a variable's declaration
#0      ComputePropagableVariableDependenciesTask.internalPerform (package:analyzer/src/task/dart.dart:2064)
#1      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:310)
#2      AnalysisTask.perform (package:analyzer/task/model.dart:210)
#3      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:272)
#4      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:247)
#5      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1116)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:188)
#7      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1114)
#8      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:367)
#9      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:797)
#10     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#11     _rootRun (dart:async/zone.dart:903)
#12     _CustomZone.run (dart:async/zone.dart:802)
#13     _CustomZone.runGuarded (dart:async/zone.dart:708)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#15     _rootRun (dart:async/zone.dart:907)
#16     _CustomZone.run (dart:async/zone.dart:802)
#17     _CustomZone.runGuarded (dart:async/zone.dart:708)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:679)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1217)
#2      DartAssistContributor.computeAssists.<computeAssists_async_body> (package:analysis_server/plugin/edit/assist/assist_dart.dart:64)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#4      _rootRun (dart:async/zone.dart:903)
#5      _CustomZone.run (dart:async/zone.dart:802)
#6      _CustomZone.runGuarded (dart:async/zone.dart:708)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#8      _rootRun (dart:async/zone.dart:907)
#9      _CustomZone.run (dart:async/zone.dart:802)
#10     _CustomZone.runGuarded (dart:async/zone.dart:708)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#13     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:198)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:660)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:673)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$100(RemoteAnalysisServerImpl.java:109)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:152)
```

**Comment by scheglov** [comment] 2015-11-30 06:49
Duplicate of: https://github.com/dart-lang/sdk/issues/25030

**Closed by scheglov** 2015-11-30 06:49 UTC
Labels: analyzer-server, area-analyzer, Type-Defect
