### ISSUE TITLE
Analyzer crash

### ISSUE THREAD

**Issue by Pornpunnarai** [dart-lang/sdk#35719] opened 2019-01-21 04:55 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-183.5153.38`
- `2.1.0-dev.9.4`
- `IU-183.5153.38, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14, screens 1440x900`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Found element with null library: WidgetTester
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:734:31)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44:12)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:259:16)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2220:49)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:4580:10)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2220:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2143:17)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5262:10)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:3891:18)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:2988:35)
#11     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:4570:11)
#12     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:2139:49)
#13     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:6228:32)
#14     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:6207:11)
#15     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:4533:13)
#16     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1751:49)
#17     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:4597:25)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
#19     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:596:10)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:112:9)
#21     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:111:13)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#24     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#27     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1050:39)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#41     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#42     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#43     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#44     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#45     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/nj/z5p85srj74lbdzgt4kc59ghr0000gn/T/report.txt.

**Comment by stereotype441** [comment] 2019-01-22 18:48
Duplicate of #34554

**Closed by stereotype441** 2019-01-22 18:48 UTC
Labels: area-analyzer, type-bug
