### ISSUE TITLE
Error.throwWithStackTrace hides type and message of error

### ISSUE THREAD

**Issue by OlehSv** [dart-lang/sdk#55938] opened 2024-06-05 14:53 UTC
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart core libraries (`dart:async`, `dart:io`, etc.)
*  Dart version: 3.3.0

It prints to DEBUG CONSOLE

> Error (Just one hardcoded word)
> Some StackTrace

While I want to see

> Value of ${Error.toString()}
> Some StackTrace

For me it is problem as _RootZone is using this function for print unhandled errors

**Comment by biggs0125** [comment] 2024-06-05 15:13
Duplicate of #55891

**Comment by nshahan** [comment] 2024-06-05 21:15
@OlehSv You can +1 the chrome issue if you want to follow the discussion there.

**Comment by kevmoo** [comment] 2024-06-05 22:37
Yes, please 👍 https://github.com/dart-lang/sdk/issues/55891

Closing as duplicate of https://github.com/dart-lang/sdk/issues/55891

**Closed by kevmoo** 2024-06-05 22:37 UTC
Labels: web-dart2js, area-web
