### ISSUE TITLE
dart analyzer doesn't work

### ISSUE THREAD

**Issue by JoahYau** [dart-lang/sdk#38478] opened 2019-09-19 08:07 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900, 2048x1152  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version , FATAL error: FormatException: Could not find an option named "enable-completion-model".
#0      Parser.validate (package:args/src/parser.dart:261:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:250:7)
#2      Parser.parse (package:args/src/parser.dart:90:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:307:45)
#4      CommandLineParser.parse (package:analysis_server/src/server/driver.dart:103:15)
#5      Driver.start (package:analysis_server/src/server/driver.dart:329:33)
#6      main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/wg/n38r583n5xb8brscmb31l5m00000gn/T/report1.txt.

**Comment by srawlins** [comment] 2019-09-19 15:24
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38173; please follow along there.

**Comment by srawlins** [comment] 2019-09-19 15:25
Duplicate of https://github.com/dart-lang/sdk/issues/38173

**Closed by srawlins** 2019-09-19 15:25 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
