### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by artmelkonyan** [dart-lang/sdk#38891] opened 2019-10-15 08:34 UTC
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I run flutter clean command in cmd

### Versions

- Flutter SDK 1.10.15-pre.121
- Visual Studio Code 1.39.1
- Dart Code 3.5.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\src\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.5.1
```

### Exception (fatal)

Failed to handle request: {id: 6, method: analysis.setAnalysisRoots, params: {excluded: [], included: [D:\flutter\ExpensePlanner\expenseplanner]}, clientRequestTime: 1571127609168}

```text
FileSystemException: Directory watcher closed unexpectedly, path = 'D:\flutter\ExpensePlanner\expenseplanner'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:307:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "D:\\flutter\\ExpensePlanner\\expenseplanner",
        "explicitFileCount": 8,
        "implicitFileCount": -8,
        "workItemQueueLength": 8,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment] 2019-10-16 13:32
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38809; please follow along there.

**Comment by srawlins** [comment] 2019-10-16 13:33
Duplicate of https://github.com/dart-lang/sdk/issues/38809

**Closed by srawlins** 2019-10-16 13:33 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
