### ISSUE TITLE
Exception from analysis server (running from VSCode / Dart Code)

### ISSUE THREAD

**Issue by Malik056** [dart-lang/sdk#39274] opened 2019-11-07 08:14 UTC
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I was changing the code. More precisly I was edditing this line
typedef PopupMenuItemSelected<T> = void Function(T value);
I was using this in my code as 
final PopupMenuItemSelected onSelected;
but when I removed <T> from above line i.e typedef PopupMenuItemSelected<T> = void Function(T value), this error occured

### Versions

- Flutter SDK 1.10.15-pre.424
- Visual Studio Code 1.39.2
- Dart Code 3.6.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/apple/Desktop/Software/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.6.0
```

### Exception

Captured exception

```text
type 'KeywordToken' is not a subtype of type 'List<Annotation>'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:719:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:594:16)
#3      Future._completeError (dart:async/future_impl.dart:530:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by srawlins** [comment] 2020-06-14 18:33
Thanks for reporting this issue! A duplicate of this issue has been filed, which has more discussion. Please follow along there. https://github.com/dart-lang/sdk/issues/41267

**Comment by srawlins** [comment] 2020-06-14 18:33
Duplicate of https://github.com/dart-lang/sdk/issues/41267

**Closed by srawlins** 2020-06-14 18:33 UTC
Labels: area-analyzer, type-bug
