### ISSUE TITLE
NoSuchMethodError: The getter 'isEof' was called on null (SDK version 2.7.0)

### ISSUE THREAD

**Issue by joemaramdocs** [dart-lang/sdk#41215] opened 2020-03-26 06:19 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\joemarr\AppData\Local\Temp\report.txt.

**Comment by mikechari** [comment] 2020-04-27 16:05
I am having the same issue, any update on it?

Thanks in advance

**Comment by kw2019ltd** [comment] 2020-05-16 14:11
17:07	Dart analysis issue: NoSuchMethodError: The getter 'isEof' was called on null. (view details)

**Comment by kw2019ltd** [comment] 2020-05-16 14:11
## Dart analysis issue

NoSuchMethodError: The getter 'isEof' was called on null.

## Version information

- Dart SDK 2.8.2
- Dart IntelliJ 192.8052
- Android Studio 3.6.3
- Windows 10 10.0

## Details

NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof

```
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## Debug log

```
1589638020811 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":447,"uri":"package:sunny_dart/time.dart","items":[{"label":"parseTimeSpans","declaringLibraryUri":"packa...
1589638020811 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":448,"uri":"package:flutter_contact/contact.dart","items":[{"label":"Contact","declaringLibraryUri":"pack...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":449,"uri":"package:logging_config/console_interface.dart","items":[{"label":"logToConsole","declaringLib...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":450,"uri":"package:worker_service/worker_service_interface.dart","items":[{"label":"getErrorsForRunner",...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":451,"uri":"package:isolate/runner.dart","items":[{"label":"Runner","declaringLibraryUri":"package:isolat...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":452,"uri":"package:isolate/load_balancer.dart","items":[{"label":"LoadBalancer","declaringLibraryUri":"p...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":453,"uri":"package:worker_service/common.dart","items":[{"label":"InitializerWithParam","declaringLibrar...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":454,"uri":"package:worker_service/worker_service.dart","items":[{"label":"killRunner","declaringLibraryU...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":455,"uri":"package:logging_config/logging_config.dart","items":[{"label":"onLogConfigured","declaringLib...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":456,"uri":"package:logging/logging.dart","items":[{"label":"hierarchicalLoggingEnabled","declaringLibrar...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":460,"uri":"package:flutter_contact/paging_iterable.dart","items":[{"label":"PagingStream","declaringLibr...
1589638020827 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":461,"uri":"package:equatable/equatable.dart","items":[{"label":"EquatableMixin","declaringLibraryUri":"p...
1589638020842 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":464,"uri":"package:flutter_contact/contacts.dart","items":[{"label":"parseTimeSpans","declaringLibraryUr...
1589638020842 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":465,"uri":"package:firebase_ml_vision/firebase_ml_vision.dart","items":[{"label":"RecognizedLanguage","d...
1589638020842 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":471,"uri":"package:qr_flutter/qr_flutter.dart","items":[{"label":"QrEmbeddedImageException","declaringLi...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":483,"uri":"package:barcodeapp/generated/intl/messages_ru.dart","items":[{"label":"MessageLookup","declar...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":484,"uri":"package:barcodeapp/generated/intl/messages_he.dart","items":[{"label":"MessageLookup","declar...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":485,"uri":"package:barcodeapp/generated/intl/messages_en.dart","items":[{"label":"MessageLookup","declar...
1589638020858 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":486,"uri":"package:barcodeapp/generated/intl/messages_ar.dart","items":[{"label":"MessageLookup","declar...
1589638020864 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":487,"uri":"package:nested/nested.dart","items":[{"label":"Nested","declaringLibraryUri":"package:nested/...
1589638020864 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":488,"uri":"package:provider/provider.dart","items":[{"label":"Selector","declaringLibraryUri":"package:p...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":499,"uri":"package:smooth_star_rating/smooth_star_rating.dart","items":[{"label":"SmoothStarRating","dec...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":500,"uri":"package:shared_preferences_platform_interface/method_channel_shared_preferences.dart","items"...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":501,"uri":"package:shared_preferences_platform_interface/shared_preferences_platform_interface.dart","it...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":502,"uri":"package:shared_preferences/shared_preferences.dart","items":[{"label":"SharedPreferences","de...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":503,"uri":"package:rate_my_app/rate_my_app.dart","items":[{"label":"DialogStyle","declaringLibraryUri":"...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":509,"uri":"package:package_info/package_info.dart","items":[{"label":"PackageInfo","declaringLibraryUri"...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":510,"uri":"package:barcodeapp/utils/package_Info.dart","items":[{"label":"initPackageInfo","declaringLib...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":511,"uri":"package:intl/message_lookup_by_library.dart","items":[{"label":"CompositeMessageLookup","decl...
1589638020880 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":512,"uri":"package:barcodeapp/generated/intl/messages_all.dart","items":[{"label":"LibraryLoader","decla...
```

**Comment by mikechari** [comment] 2020-05-16 16:24
I had the same issue, I resolved it uninstalling then reinstalling Flutter

**Comment by srawlins** [comment] 2020-06-12 22:48
Thanks for reporting this issue! This was previously reported in #40223. Please follow along there.

**Comment by srawlins** [comment] 2020-06-12 22:48
Duplicate of #40223

**Closed by srawlins** 2020-06-12 22:48 UTC
Labels: analyzer-crash-report, area-analyzer
