### ISSUE TITLE
Analyzer crash when opening Flutter with this patch in IntelliJ

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#48417] opened 2022-02-17 02:42 UTC
This issue was reported on discord by chunhtai.

To reproduce, open
https://github.com/flutter/flutter/pull/95226 

in Flutter IntelliJ
You will see the following error.
RangeError (index): Invalid value: Only valid value is 0: 1

```
#0      List.[] (dart:core-patch/growable_array.dart:281:36)
#1      ErrorVerifier._checkForMixinSuperclassConstraints (package:analyzer/src/generated/error_verifier.dart:3383:61)
#2      ErrorVerifier._checkForAllMixinErrorCodes (package:analyzer/src/generated/error_verifier.dart:1446:17)
#3      ErrorVerifier._checkClassInheritance (package:analyzer/src/generated/error_verifier.dart:1352:10)
#4      ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:443:9)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1500:50)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7971:20)
#7      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2116:21)
#8      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:771:10)
#9      ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:506:11)
#10     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2109:50)
#11     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:472:10)
#12     LibraryAnalyzer._computeDiagnostics.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:263:7)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:579:13)
#14     LibraryAnalyzer._computeDiagnostics (package:analyzer/src/dart/analysis/library_analyzer.dart:262:11)
#15     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:106:5)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1411:11)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#18     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1388:20)
#19     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1460:26)
#20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1075:39)
#21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2095:24)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1440:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1388:20)
#3      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1460:26)
#4      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1075:39)
#5      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2095:24)
<asynchronous suspension>
```

**Comment by bwilkerson** [comment] 2022-04-25 17:59
@scheglov

**Comment by scheglov** [comment] 2022-04-25 18:52
I was not able to reproduce this, I can open and analyze code of this PR with the bleeding edge Dart SDK.

There were a few crashes that should be fixed with https://github.com/dart-lang/linter/commit/16169a54c908d19e948b1f244c924d84575104db, but we probably have no pulled it into Dart SDK yet. @pq

**Comment by pq** [comment] 2022-04-25 20:54
I'll start looking at a new roll.

**Comment by pq** [comment] 2022-04-27 14:34
FWIW I've got a new roll cooking but it's taking bit to cleanup new `non_constant_identifier_names` violations.

Roll PR here: https://dart-review.googlesource.com/c/sdk/+/242391

**Comment by pq** [comment] 2022-05-06 16:45
Linter 1.23.0 with the fix just landed in the SDK.  Assuming it doesn't shake out any problems downstream (and need a revert) you should see the fix in a dev build next week. 🤞

**Closed** 2024-04-05 14:32 UTC
Labels: area-analyzer, P2, type-bug, analyzer-package, analyzer-crash-report
