### ISSUE TITLE
Geting Unexpected input. Please report this at dartbug.com from StreamingDartTypeTranslator::BuildTypeParameterType

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32267] opened 2018-02-21 18:49 UTC
running flutter tests in google3 is producing an error
'Unexpected input. Please report this at dartbug.com'
from StreamingDartTypeTranslator::BuildTypeParameterType

We don't have much in terms of logs or repro instructions yet.
FlutterIosAotSnapshot action:
Error: error: Unexpected input. Please report this at dartbug.com.

[REDACTED]

**Comment by mraleph** [comment] 2018-02-22 07:44
Mixins again 🔥  

```dart
class State<T> {}
class A {}
abstract class Mixin<T> extends State<T> {
  factory Mixin._() => null;
}

class AState extends State<A> {}
class AStateImpl extends AState with Mixin {}

void main() { new AStateImpl(); }
```

```
$ pkg/vm/tool/dart2 /tmp/mixin.dart
Unhandled exception:
error: Unexpected input. Please report this at dartbug.com.
#0      _startIsolate.<anonymous closure> (dart:isolate/isolate_patch.dart:279:19)
#1      _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
$ pkg/vm/tool/precompiler2 /tmp/mixin.dart /tmp/mixin.snap
error: Unexpected input. Please report this at dartbug.com.
```

This is caused by factory constructor being copied as-is (with mismatching set of type arguments) into mixin application for some reason - this should not be needed. I think mixin transformation simply forgets to filter them out.

```
   abstract class _AState&Mixin extends mix::AState implements mix::Mixin<mix::A> {
     synthetic constructor •() → void
       : super mix::AState::•()
       ;
     static factory _<T extends core::Object>() → mix::Mixin<mix::_AState&Mixin::_::T>
       return null;
   }
```

**Comment by kmillikin** [comment] 2018-02-22 08:55
Fixed in 52d1b4e96d0a384b08aafc184785d1c74cb74efc.

**Comment by mraleph** [comment] 2018-02-22 11:51
Reopening due to revert @kmillikin

**Comment by kmillikin** [comment] 2018-02-22 11:56
Closing due to reland @mraleph

**Closed by kmillikin** 2018-02-22 11:56 UTC
Labels: Customer-Flutter, I/O Beta 2.0, P0 critical, area-front-end
