### ISSUE TITLE
Incorrect parameter type check in a forwarding stub for a mixed-in method

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34321] opened 2018-08-30 23:44 UTC
Test:

```dart
import 'package:expect/expect.dart';

class A {}
class B extends A {}

class Base<S> {
}

class Mixin<T> {
  void f(T arg) {}
}

abstract class Interface {
  void f(covariant A arg);
}

class C<S> extends Base<S> with Mixin<B> implements Interface {}

main() {
  Interface i = new C<String>();
  i.f(new B());
  Expect.throwsTypeError(() { i.f(new A()); });
}
```

Output:
```
Unhandled exception:
type 'B' is not a subtype of type 'String' of 'arg'
#0      C.f (.../covariant_subtyping_with_mixin_test.dart)
#1      main (.../covariant_subtyping_with_mixin_test.dart:25:5)
#2      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

The argument should be checked against B, but it is checked against unrelated type String.

The problem is that target of a forwarding stub C.f is Mixin.f, but its parameter type 'T' is instantiated using C's type arguments which have type argument 'S' (String) at index 0.

Parameter type checks in forwarding stubs which use parameter types of a stub target were implemented in https://github.com/dart-lang/sdk/commit/28a0706e91cfa264a18f1a988e2f0e9702be65ce

/cc @sjindel-google @mraleph

**Comment by sjindel-google** [comment] 2018-10-25 14:38
The VM behavior is definitely incorrect, since we're checking against the wrong type parameter. However, it looks to me like the forwarding stub isn't even necessary here to two reasons: first, the mixin class (`_C&Base&Mixin`) already has a copy for `f` which checks against the right parameter; second, the target of the forwarding stub has `arg` marked `generic-covariant`, so it will always be checked in the target of the forwarding stub anyway.

```
library;
import self as self;
import "dart:core" as core;
import "package:expect/expect.dart" as exp;

class A extends core::Object {
  synthetic constructor •() → self::A
    : super core::Object::•()
    ;
}
class B extends self::A {
  synthetic constructor •() → self::B
    : super self::A::•()
    ;
}
class Base<S extends core::Object = dynamic> extends core::Object {
  synthetic constructor •() → self::Base<self::Base::S>
    : super core::Object::•()
    ;
}
class Mixin<T extends core::Object = dynamic> extends core::Object {
  synthetic constructor •() → self::Mixin<self::Mixin::T>
    : super core::Object::•()
    ;
  method f(generic-covariant-impl self::Mixin::T arg) → void {}
}
abstract class Interface extends core::Object {
  synthetic constructor •() → self::Interface
    : super core::Object::•()
    ;
  abstract method f(covariant self::A arg) → void;
}
abstract class _C&Base&Mixin<S extends core::Object = dynamic> extends self::Base<self::_C&Base&Mixin::S> implements self::Mixin<self::B> {
  synthetic constructor •() → self::_C&Base&Mixin<self::_C&Base&Mixin::S>
    : super self::Base::•()
    ;
  method f(generic-covariant-impl self::B arg) → void {}
}
class C<S extends core::Object = dynamic> extends self::_C&Base&Mixin<self::C::S> implements self::Interface {
  synthetic constructor •() → self::C<self::C::S>
    : super self::Base::•()
    ;
  forwarding-stub method f(covariant generic-covariant-impl self::A arg) → void
    return super.{self::Mixin::f}(arg);
}
static method main() → dynamic {
  self::Interface i = new self::C::•<core::String>();
  i.{self::Interface::f}(new self::B::•());
  exp::Expect::throwsTypeError(() → core::Null {
    i.{self::Interface::f}(new self::A::•());
  });
}
```

**Comment by sjindel-google** [comment] 2018-10-25 16:44
It looks like this is actually a design issue with the mixin transformation.

Every concrete forwarding stub has a field in `Procedure` named `forwardingStubSuperTarget`, which is supposed to point to the actual (run-time) target of the stub. The forwarding stub is supposed to check against the types of the super-target. The original purpose of this field was to make it easier for the VM's kernel FE to compile the type-checks, however, it is not being updated correctly during mixin transformation. In this example, the `forwardingStubSuperTarget` on `C.f` is supposed to point to `_C&Base&Mixin.f` (the actual runtime target), but instead it points to `Mixin.f`.

Unfortunately the mixin transformation actually can't update the `forwardingStubSuperTarget`, because performing super-call resolution there is incompatible with incremental compilation (a class with resolved super calls could be mixed-in). So the only solution to this bug today is to remove the `forwardingStubSuperTarget` from kernel and dissect the body of the forwarding stub and resolve the inner call in the VM kernel FE.

Alternatively, this problem will probably disappear when the current super-mixin support is replaced with explicit super-mixin declarations. I believe we should wait until then to address this issue if it remains. Also, @stefantsov is currently investigating the scope/necessity of forwarding stubs.

@alexmarkov, how did you address this in the bytecode frontend?

**Comment by alexmarkov** [comment] 2018-10-25 17:02
In order to generate type checks in a forwarding stub, bytecode generator calculates Substitution to translate type parameters of stub's target into type parameters of the enclosing class and function: https://github.com/dart-lang/sdk/blob/3e824d2ecd4ea42c101fb433df561f2e85d9ca27/pkg/vm/lib/bytecode/gen_bytecode.dart#L1019-L1049.

This code uses ClassHierarchy.getClassAsInstanceOf() which works for implemented interfaces, including mixed-in types.

**Comment by sjindel-google** [comment] 2018-10-25 18:59
Got it. Although that works for this test case, it's not strictly implementing the semantics of forwarding stubs, which is to check against the types of the actual (run-time) target.

**Comment by alexmarkov** [comment] 2018-10-25 19:50
> it's not strictly implementing the semantics of forwarding stubs, which is to check against the types of the actual (run-time) target.

Semantics of forwarding stubs described in kernel AST tells about forwarding to forwardingStubSuperTarget, it doesn't tell anything about run-time target:
https://github.com/dart-lang/sdk/blob/59e626e5c9247a51af694f979b3e713833b16044/pkg/kernel/lib/ast.dart#L1651-L1659

If this is not correct, maybe this should be clarified and/or fixed.

For parameter type checking it shouldn't matter if forwardingStubSuperTarget references original method in a mixin, or its copy after mixin transformation - the parameter types are the same.

Changing forwardingStubSuperTarget in mixin transformation might work if mixin applications define all necessary forwarding stubs with correct targets, and not just blindly copy them from a mixed-in class.

**Comment by sjindel-google** [comment] 2018-10-26 09:21
In this case the parameter types are actually not the same (`T` vs `B`) unless substitution is applied. The issue is just that it's difficult to apply this substitution in the VM because we don't have access to the Kernel API.

`forwardingStubSuperTarget` was only ever meant to be a cache of the run-time target; I'm surprised that comment is there. Of course, if it's cached correctly, the comment is correct.

The problem is that the CFE can't commit to either semantics being official right now, because the behavior of forwarding stubs is not fully understood. I'm not sure that patching up the `forwardingStubSuperTarget` will be correct for all cases, I don't think we should be responsible for ensure that it is.

Still, it looks like the bytecode generator is respecting the written semantics for the forwarding stubs, so we should probably keep it as is.

**Comment by a-siva** [comment] 2022-11-04 21:43
Tried the above test with the latest version of Dart and it works as expected.
Closing the issue.

**Closed by a-siva** 2022-11-04 21:43 UTC
Labels: area-vm, closed-as-intended, P2, type-bug, area-front-end
