### ISSUE TITLE
DDC `async*` bug

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#39994] opened 2020-01-06 21:20 UTC
The following test prints:

```
Hello, World!
Hello, World!
Hello, World!
[hello]
```

in the VM and dart2js, but prints nothing DDC.

```dart
import 'dart:async';

  Stream<String> testStream(String test) async* {
    try {
      await testFunction();
      yield test;
    } catch (e) {
      yield test;
      print('Hello, World!');
      print('Hello, World!');
      print('Hello, World!');
    }
  }

  Future<String> testFunction() async {
    await testFunctio2();
    return "";
  }

  Future<String> testFunctio2() async {
    throw Exception("test");
  }

void main() async {
  var stream = testStream("hello");
  print(await stream.toList());
}
```

**Comment by vsmenon** [comment] 2020-01-06 21:21
@Markzipan - can you take a look when you get a chance?

**Comment by Onein** [comment] 2020-02-04 09:13
Any update on this, since the original issue in the flutter repo is already closed?

**Comment by Markzipan** [comment] 2020-02-04 17:22
I haven't had the time to look at this yet, but this issue is still reproducible on DDC. We could escalate if it's blocking.

**Comment by Onein** [comment] 2020-02-06 09:08
Thanks for the response. No, it's not blocking I just wanted to know if there is any progress because the original issue is closed now. It's just an annoying bug, because you can't really use the ddc in case you work a lot with streams, like I do.

**Comment by phamnhuvu-dev** [comment] 2020-04-09 02:56
This bug is very critical when all our business logic is using stream then it is not working on the web platform

**Comment by Markzipan** [comment] 2020-04-09 05:21
We have a fix in the works for this issue that's been toiling behind other priorities. I've revived the fix, so this issue may be resolved soon.

**Comment by phamnhuvu-dev** [comment] 2020-04-09 05:24
@Markzipan But when I run the web with the release option, the problem is gone.

**Comment by Markzipan** [comment] 2020-04-09 05:28
The debug and release compilers are different on the web; this issue only exists for the debug compiler. We plan on resolving async disparities between our various backends soon (tm).

**Comment by vari** [comment] 2020-05-29 17:55
Is there any update on the fix for this issue?

**Comment by Markzipan** [comment] 2020-05-29 18:04
I have a patch for this issue in the works, but it's dredged up a couple other timing-related code issues. I'll try to get the patch in and work on a more holistic fix later.

**Closed** 2020-05-29 21:41 UTC
Labels: P2, area-web, web-dev-compiler
