### ISSUE TITLE
RawSocket connect - different port than specified

### ISSUE THREAD

**Issue by Hexagonale** [dart-lang/sdk#36674] opened 2019-04-19 00:23 UTC
When I connect using `RawSocket.connect("My VPS IP", 3306)`, it throws `SocketException` with a different port than specified:
`SocketException: OS Error: Connection refused, errno = 111, address = <IP>, port = 40048`

Shortest reproduce code:
```
import 'dart:io';

void main () async {
  try {
    await RawSocket.connect("My IP", 3306);
  } catch (e) {
    print(e);
  }
}
```

Dart SDK Version (`dart --version`):
`Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "windows_x64"`

-------
I'm obviously using real IP.

**Comment by natebosch** [comment] 2019-06-19 17:04
Closing as a duplicate of #12693 which has more info.

**Closed by natebosch** 2019-06-19 17:04 UTC
Labels: area-library, closed-duplicate, library-io, p2-medium, type-bug

**Comment by AbeerSul** [comment] 2020-03-18 11:32
none of this actually worked for me :/
this command worked like magic "adb reverse tcp:5000 tcp:5000" 💯
