### ISSUE TITLE
Dartium Crashes on HTML5 Date Input

### ISSUE THREAD

**Issue by rightisleft** [dart-lang/sdk#23602] opened 2015-06-07 19:16 UTC
Dartium will crash when using any html5 date input selector.

This is not related to dart code, only the Dartium browser. 

Here's a repro video: https://vid.me/ZgeL

Dartium Version: Version 39.0.2171.0
Operating System : OS X 10.10

Please let me know if i can provide additional details

This is blocking

**Comment by zoechi** [comment] 2015-06-07 20:02
#23416

**Comment by alan-knight** [comment] 2016-01-13 22:13
Yes, duplicate of #23416 per previous comment.

**Closed by alan-knight** 2016-01-13 22:13 UTC
Labels: area-dartium, Type-Defect
