### ISSUE TITLE
Parsing of a unit with errors throws

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30266] opened 2017-07-26 15:31 UTC
The following program causes an exception to be thrown.
Analyzer does not throw any exceptions for this code.

```dart
const int x = 0x;
```
Exception:
```
  @14: A hex digit (0-9 or A-F) must follow '0x'.
  null
  package:front_end/src/fasta/parser/listener.dart 1064:5            Listener.handleUnrecoverableError
  package:front_end/src/fasta/source/directive_listener.dart 121:42  DirectiveListener.handleUnrecoverableError
  package:front_end/src/fasta/parser/parser.dart 3993:29             Parser.reportErrorToken
  package:front_end/src/fasta/parser/parser.dart 3948:14             Parser.reportUnrecoverableErrorWithToken
  package:front_end/src/fasta/parser/parser.dart 877:17              Parser.parseIdentifier
  package:front_end/src/fasta/parser/parser.dart 1089:17             Parser.parseType.commitType
  package:front_end/src/fasta/parser/parser.dart 1143:26             Parser.parseType
  package:front_end/src/fasta/parser/parser.dart 2031:13             Parser.parseModifiers
  package:front_end/src/fasta/parser/parser.dart 1548:19             Parser.parseFields
  package:front_end/src/fasta/parser/parser.dart 1533:11             Parser.parseTopLevelMember
  package:front_end/src/fasta/parser/parser.dart 265:14              Parser._parseTopLevelDeclaration
  package:front_end/src/fasta/parser/parser.dart 237:13              Parser.parseTopLevelDeclaration
  package:front_end/src/fasta/parser/parser.dart 229:15              Parser.parseUnit
  package:front_end/src/incremental/unlinked_unit.dart 25:32         computeUnlinkedUnit
  package:front_end/src/incremental/file_state.dart 156:23           FileState.refresh
  ===== asynchronous gap ===========================
  package:front_end/src/incremental/file_state.dart 357:18           FileSystemState.getFile
  ===== asynchronous gap ===========================
  package:front_end/src/incremental/kernel_driver.dart 128:31        KernelDriver.getKernel.<fn>.<fn>
```

**Comment by peter-ahe-google** [comment] 2017-08-01 11:45
Thank you, Konstantin. On the surface, this seems like an error that should be relatively easy to make recoverable in Fasta. However, from the stack trace, this looks more complicated (it looks like the parser is trying to parse `0x` as a type annotation).

**Comment by jensjoha** [comment] 2018-01-09 08:16
I cannot reproduce a crash, but instead I get this (with --dump-ir) which looks fine to me:

```
tmp.dart:1:15: Error: A hex digit (0-9 or A-F) must follow '0x'.
const int x = 0x;
              ^
library;
import self as self;
import "dart:core" as core;

static const field core::int x = 0;
static const field dynamic #errors = const <dynamic>["tmp.dart:1:15: Error: A hex digit (0-9 or A-F) must follow '0x'.\nconst int x = 0x;\n              ^"]/* from null */;
```

Any objections to closing this issue?

**Comment by scheglov** [comment] 2018-01-09 17:39
Yes, let's close this issue.

There was still an exception with code like this, but only because we were accessing `ErrorToken.lexeme`. But this is a client error, not a FrontEnd one.

**Comment by peter-ahe-google** [comment] 2018-01-09 19:25
I think this was fixed by @danrubel

**Closed by peter-ahe-google** 2018-01-09 19:25 UTC
Labels: P3 low, area-front-end, front-end-fasta, front-end-fasta-recovery
