### ISSUE TITLE
VM crash in RandomAccessFile.closeSync()

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#29266] opened 2017-04-05 15:43 UTC
On macos, the test runner crashed when closing a file, when reading all the test files during test setup.
This was in run
https://luci-milo.appspot.com/buildbot/client.dart/dart2js-mac10.11-safari-3-3-be/4599
with log at 
 https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fclient.dart%2Fdart2js-mac10.11-safari-3-3-be%2F4599%2F%2B%2Frecipes%2Fsteps%2Fdart2js_safari_co19_fast-startup_tests%2F0%2Fstdout

Dumping native stack trace for thread 1303
  [0x000000010c3310ba] Dart_SetNativeInstanceField
  [0x000000010c3310ba] Dart_SetNativeInstanceField
  [0x000000010c2f850d] dart::bin::Builtin_File_Close(_Dart_NativeArguments*)
  [0x000000010c56ee96] dart::NativeEntry::NativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))
  [0x000000010e2b27a3] [Stub] CallNativeCFunction
  [0x000000010e518c07] _RandomAccessFileOpsImpl.close
  [0x000000010fc452ff] _RandomAccessFile.closeSync
  [0x000000010fbaf53e] StandardTestSuite.enqueueBrowserTestWithOptions
  [0x000000010fd2740f] StandardTestSuite.enqueueTestCaseFromTestInformation
  [0x000000010fd0d53a] StandardTestSuite.makeTestCaseCreator.<anonymous closure>
  [0x00000001100f4422] StandardTestSuite.enqueueFile
  [0x00000001100f9c63] StandardTestSuite.enqueueDirectory.<anonymous closure>
  [0x0000000115890169] Stream.forEach.<anonymous closure>.<anonymous closure>
  [0x000000010fc2453a] _Closure.call
  [0x000000010e50f72c] _runUserCode
  [0x00000001100f9b21] Stream.forEach.<anonymous closure>
  [0x000000010e4ffe62] _RootZone.runUnaryGuarded
  [0x000000010fc72582] _BufferingStreamSubscription._sendData
  [0x000000010e4ff196] _BufferingStreamSubscription._add
  [0x000000010fc0ae22] _WhereStream._handleData
  [0x0000000116e6232d] _ForwardingStreamSubscription._handleData
  [0x000000010e4ffe62] _RootZone.runUnaryGuarded
  [0x000000010fc72582] _BufferingStreamSubscription._sendData
  [0x000000010e4ff196] _BufferingStreamSubscription._add
  [0x00000001100fc750] _StreamController._add
  [0x00000001100d1b8e] _AsyncDirectoryLister.next.<anonymous closure>
  [0x000000010e52eb3d] _Closure.call
  [0x000000010f321ec9] _RootZone.runUnary
  [0x000000010f3219d2] _FutureListener.handleValue
  [0x000000010f3216bd] _Future._propagateToListeners.handleValueCallback
  [0x0000000116e60633] _Future._propagateToListeners
  [0x000000010f31e212] _Future._completeWithValue
  [0x000000010f31dcf5] _Future._asyncComplete.<anonymous closure>
  [0x000000011585c9d9] _microtaskLoop
  [0x000000010f31d520] _startMicrotaskLoop
  [0x000000011573cac0] _startMicrotaskLoop
  [0x000000010fd3ce30] _RawReceivePortImpl._handleMessage
  [0x000000010e2b29d9] [Stub] InvokeDartCode
  [0x000000010c44d73a] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  [0x000000010c450e6d] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x000000010c5348fd] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x000000010c55fbf6] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x000000010c5600eb] dart::MessageHandler::TaskCallback()
-- End of DumpStackTrace

**Comment by mkustermann** [comment] 2017-11-17 10:25
Duplicate of https://github.com/dart-lang/sdk/issues/30990

**Closed by mkustermann** 2017-11-17 10:25 UTC
Labels: area-vm, library-io, P2 medium, Type: bug
