### ISSUE TITLE
Cannot load script if it starts with two slashes //absolute/path/to/file.dart

### ISSUE THREAD

**Issue by akshaydashrath** [dart-lang/sdk#28143] opened 2016-12-16 16:59 UTC
My flutter setup broke and the only change to my system was updating the OS. The problem appears to be in the Dart VM, ref: https://github.com/dart-lang/sdk/blob/master/runtime/bin/vmservice/loader.dart#L407

```
 Akshays-MacBook-Pro-2:~ akshaydashrath$ flutter doctor
    Downloading Dart SDK 1.21.0...
    #################################################################100.0%
    Building flutter tool...
    vm-service: Error: Unhandled exception:
    Unsupported operation: Cannot extract a non-Windows file path from a 
    file URI with an authority
    #0      _SimpleUri._toFilePath (dart:core/uri.dart:4423)
    #1      _SimpleUri.toFilePath (dart:core/uri.dart:4417)
    #2      _loadFile (loader.dart:407:26)
    #3      _handleResourceRequest (loader.dart:510:5)
    #4      _processLoadRequest (loader.dart:941:7)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

My related post on stackoverflow: http://stackoverflow.com/questions/41187802/issue-building-flutter-on-a-mac?noredirect=1#comment69577716_41187802

Dart Version: 1.21.0
OS: Mac OS 10.12.2

Note: using older versions of dart resulted in the same problem

**Comment by sethladd** [comment] 2016-12-16 17:06
Thanks for the report! Trying to repro now.

**Comment by johnmccutchan** [comment] 2016-12-16 18:05
@akshaydashrath 

What directory do you have flutter checked out into?

What directory are you running flutter doctor from?

**Comment by akshaydashrath** [comment] 2016-12-16 18:18
@johnmccutchan flutter is in /Users/akshaydashrath/sdk/flutter and I'm running from /Users/akshaydashrath/, the SDK is added to my PATH.

**Comment by sethladd** [comment] 2016-12-16 18:58
@akshaydashrath can you paste in the contents of `flutter --version` ? Thanks!

**Comment by sethladd** [comment] 2016-12-16 19:00
Should we close this issue in preference of https://github.com/flutter/flutter/issues/7279 ? (until we confirm it's indeed a Dart SDK issue?)

**Comment by johnmccutchan** [comment] 2016-12-19 15:01
Simple reproduction:

```
$ ./out/DebugX64/dart /usr/local/google//home/johnmccutchan/hw.dart 
hello world
```

```
$ ./out/DebugX64/dart //usr/local/google/home/johnmccutchan/hw.dart 
vm-service: Error: Unhandled exception:
Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      _SimpleUri._toFilePath (dart:core/uri.dart:4423)
#1      _SimpleUri.toFilePath (dart:core/uri.dart:4417)
#2      _loadFile (loader.dart:407:26)
#3      _handleResourceRequest (loader.dart:510:5)
#4      _processLoadRequest (loader.dart:941:7)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by johnmccutchan** [comment] 2016-12-19 15:06
The URI specification considers URIs that start with two slashes to be [Relative Reference](https://tools.ietf.org/html/rfc3986#section-4.2). 

@lrhn @turnidge how should we handle this case?

**Comment by lrhn** [comment] 2016-12-19 15:55
The `Uri` class is acting correctly by treating `//something/else/` as a relative URI reference with an authority, so the only problem is that `toFilePath` refuses to handle that case. 

On Windows, a path starting with `//` is a network path. That convention doesn't generalize to other file systems, and treating the authority as just part of a path seems very dangerous.

If I am to make a recommendation, it is to *not* use the `Uri` class on something unless you know that it is a URI or URI reference. Just treating a *path* like a *URI* is not safe, even without the extra fun of Windows drive letters looking like schemes. If the string `//something/else/` is really a path, then round-tripping it through `Uri` is wrong. If it really is a `URI`, then `something` is an authority, and we can't turn that into a file path path in any consistent way.

**Comment by eseidelGoogle** [comment] 2016-12-19 15:59
Thanks for looking. :)  BTW, Chrome has a zillion URL tests for GURL (their url handler) if they might be helpful here: https://chromium.googlesource.com/chromium/src/+/master/url/

**Comment by turnidge** [comment] 2016-12-19 19:10
It doesn't seem like there is a lot we can do about this in the dart vm.  Perhaps we should change the loader to catch this exception and give the user a better error message?

**Comment by jason-simmons** [comment] 2016-12-19 22:03
What format does the Dart command line tool expect for the script file argument?

Is it supposed to be a file system path or a URI?  The code seems to assume that it's a URI.

**Comment by johnmccutchan** [comment] 2016-12-20 00:43
Working as intended.

**Closed by johnmccutchan** 2016-12-20 00:43 UTC
Labels: Customer-Flutter

**Comment by floitschG** [comment] 2016-12-20 14:56
@johnmccutchan or @turnidge : could you please answer @jason-simmons 's question: what does the command line tool expect?
thanks.
