### ISSUE TITLE
Wrong Dead code warning when using break in switch case

### ISSUE THREAD

**Issue by passsy** [dart-lang/sdk#39717] opened 2019-12-09 13:44 UTC
Dead code detection ignores `break` in `switch` `case`. Marks everything after the switch case as dead code although it is called.

```dart
void main() {
  print(nameThing(Thing.One));
  // prints "skipped"
}

String nameThing(Thing thing, [bool skip = true]) {
  switch (thing) {
    case Thing.One:
      if (skip) break;
      return "one";
    case Thing.Two:
      return "two";
    default:
      return "unknown";
  }
  return "skipped"; // Wrong "Dead code" warning
}

enum Thing { One, Two }

```
---
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.3, on Mac OS X 10.15.1 19B2106, locale en-GB)
    • Flutter version 1.12.13+hotfix.3 at .flutter
    • Framework revision 57f2df76d7 (3 days ago), 2019-12-05 21:23:21 -0800
    • Engine revision ac9391978e
    • Dart version 2.7.0
```

**Comment by srawlins** [comment] 2019-12-13 05:43
Ouch good catch. I suspect the analyzer's DEAD_CODE algorithm is to be replaced with the new flow analysis system in the NNBD Dart type system. This should happen in 2020.

**Comment by srawlins** [comment] 2020-05-28 05:10
Duplicate of https://github.com/dart-lang/sdk/issues/35710

**Closed by srawlins** 2020-05-28 05:10 UTC
Labels: area-analyzer, type-bug
