### ISSUE TITLE
`Future.wait` doesn't document that the results are in the same order as the original futures.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#31109] opened 2017-10-16 07:22 UTC
It should.

**Comment by natebosch** [comment] 2018-08-29 01:43
Closing as a duplicate of #34290 - only cause I already have https://dart-review.googlesource.com/c/sdk/+/71885 which mentions it in the commit message.

**Closed by natebosch** 2018-08-29 01:43 UTC
Labels: area-library, library-async, type-documentation
