### ISSUE TITLE
Incorrect Generic Comparison Error

### ISSUE THREAD

**Issue by Pante** [dart-lang/sdk#46471] opened 2021-06-25 13:50 UTC
The following snippet of code is flagged as an error in Dart 2.13.3 even though it was not causing any issues in Dart 2.10.0.

```dart
mixin A<T extends A<T>> implements Comparable<T> {

  bool operator < (T other) => compareTo(other) < 0;

  bool operator > (T other) => other < this; // Flagged as `The argument type 'A<T>' can't be assigned to the parameter type 'T'.`

}
```

Interestingly, if `this` is on the LHS of the `<` comparison, it is not flagged as an error.
```dart
mixin A<T extends A<T>> implements Comparable<T> {

  bool operator > (T other) => compareTo(other) > 0;

  bool operator < (T other) => this > other; // compiles fine

}
```

**Comment by lrhn** [comment] 2021-06-25 18:59
In the first example, the static type of `other` is `T` where `T` has bound `A<T>`. The type of the operator `other.<` is therefore the type of the operator `<` of `A<T>` and expects a `T`.
The type of `this` is `A<T>`, which is a supertype of `T`, not a subtype, so `this` is not a valid argument to `other <` for exactly the reason the compiler gives (`A<T>` cannot be assigned to `T`).

The other example swaps the two, and since `other` has type `T`, it's a valid argument to `this.<` which expects a `T`.

So, this is working as intended.

**Closed by lrhn** 2021-06-25 18:59 UTC
