### ISSUE TITLE
switch with types don't cast when nullable are used

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/sdk#53636] opened 2023-09-27 20:26 UTC
Consider the following code:

```dart
sealed class Result<T> {
  const Result();
}

final class Success<T> extends Result<T> {
  const Success(this.value);
  
  final T value;
}

final class Failure<T> extends Result<T> {
  const Failure(this.exception, this.stackTrace);
  
  final Object exception;
  final StackTrace? stackTrace;
}

Result<bool>? _mockSuccessResultOrNull() {
  // It can return null, success or failure.
  return const Success(true);
}

void main() {
  final result = _mockSuccessResultOrNull();
  
  assert(result != null, "If null here, throw some exception");
  
  switch(result!) {
    case Failure():
      print("Method has failed with ${result.exception}");
      break;
    case Success():
      print("Method was successull: ${result.value}");
      break;
  }
}
```

This code has a `Result` that can be either `Success` or `Failure`.

My specific scenario allows passing this `Result` as a nullable value, but in a specific scenario, a `null` value is impossible/not allowed, so, an assertion is made on this and now we are 100% sure that `result` is not null.

Since Dart don't consider `result` as non-null because of that `assert`, I have to use the `!` operator in the `switch` statement.

The bug is: when using the `!` operator, `result` is never cast to `Failure` or `Success`:

```
lib/main.dart:30:46:
Error: The getter 'exception' isn't defined for the class 'Result<bool>'.
 - 'Result' is from 'package:dartpad_sample/main.dart' ('lib/main.dart').
      print("Method has failed with ${result.exception}");
                                             ^^^^^^^^^
lib/main.dart:33:46:
Error: The getter 'value' isn't defined for the class 'Result<bool>'.
 - 'Result' is from 'package:dartpad_sample/main.dart' ('lib/main.dart').
      print("Method was successull: ${result.value}");
                                             ^^^^^
```

To fix this bug, I need to create a new non-nullable variable and feed it to the `switch`:

```dart
void main() {
  final result = _mockSuccessResultOrNull();
  
  assert(result != null, "If null here, throw some exception");
  
  final resultIsNotNullHere = result!;
  
  switch(resultIsNotNullHere) {
    case Failure():
      print("Method has failed with ${resultIsNotNullHere.exception}");
      break;
    case Success():
      print("Method was successull: ${resultIsNotNullHere.value}");
      break;
  }
}
```

Now it compiles and runs normally.

What to fix:

1) Using `result!` should not be different from `result` being non-nullable.

2) As a plus, `assert(something != null)` should make `something` safe-non-null (whatever this condition is called), so we could avoid using the `!` operator. (if I change the `assert` to an `if`, this works fine, as shown bellow).

```dart
void main() {
  final result = _mockSuccessResultOrNull();
  
  if(result == null) {
    throw Error();
  }
  
  switch(result) {
    case Failure():
      print("Method has failed with ${result.exception}");
      break;
    case Success():
      print("Method was successull: ${result.value}");
      break;
  }
}
```

EDIT: This other `switch` syntax that I was unaware of works fine (now I'm confused about the differences between `case Failure():` and `case Failure f:`)

```dart
void main() {
  final result = _mockSuccessResultOrNull();
  
  assert(result != null, "If null here, throw some exception");
  
  switch(result!) {
    case Failure f:
      print("Method has failed with ${f.exception}");
      break;
    case Success s:
      print("Method was successull: ${s.value}");
      break;
  }
}
```

**Comment by lrhn** [comment] 2023-09-27 22:10
This is all working as intended.

The reason `switch (result!)...` doesn't promote is that the match object expression isn't a variable. The switch can only promote if you are switching on a promotable variable, and nothing else.

The reason `assert(result != null);` doesn't, and cannot, promote is that it's not executed at all in production mode. Therefore it cannot guarantee that the value isn't `null` afterwards.

Creating a new variable, or using an `if` to actually promote `result`, means that you're switching on a variable, which the switch can then promote. Just writing `result!;` as a statement will also promote, like an `if`.

Using the `Success s` pattern creates a new variable with a value that is definitely a `Success`, whether you can promote the original variable or not.

All in all, working as expected.

**Comment by keertip** [comment] 2023-09-29 16:27
Thanks for the detailed explanation! Closing, working as expected.

**Closed by keertip** 2023-09-29 16:27 UTC
Labels: area-analyzer

**Comment by JCKodel** [comment] 2023-09-29 16:38
When "working as intended" makes a bad language, it's not really working, right?
