### ISSUE TITLE
CFE infers dynamic in the return type for some async null contexts

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#37778] opened 2019-08-07 20:56 UTC
```
import 'dart:async';

class A<T> {}

Future<A<S>> foo<S>(FutureOr<S> bar()) {
  print(S);
  return (() async => A<S>())();
}

main() {
  foo(() => null);
}
```

DDC prints `Null`, while CFE-backed backends report `dynamic`. This pattern shows up a couple of times internally. What's the expected behavior?

Kernel dump snippet:
```
  static method foo<S extends core::Object* = dynamic>(() →* asy::FutureOr<nul::foo::S*>* bar) → asy::Future<nul::A<nul::foo::S*>*>* {
    core::print(nul::foo::S*);
    return (() → asy::Future<nul::A<nul::foo::S*>*>* async => new nul::A::•<nul::foo::S*>()).call();
  }
  static method main() → dynamic {
    nul::foo<dynamic>(() → core::Null* => null);
  }
```

**Comment by vsmenon** [comment] 2019-08-08 21:32
@leafpetersen @eernstg - can one of you sanity check what is the correct behavior here?

**Comment by leafpetersen** [comment] 2019-08-08 22:07
Simpler reproduction:

```dart
import 'dart:async';

class A<T> {
}

void foo<S>(FutureOr<S> bar) {
  print(S);
}

main() {
  Null x;
  foo(x);
}
```

There's no "right" answer here, but the analyzer's solution is, I think my preference.  The inference problem hinges on solving for `S` in:

`Null <: FutureOr<S>`

Any choice of `S` works.  The analyzer checks that `Null <: Future<S>`, sees that this succeeds without constraining `S`, and so tries `Null <: S`.  This succeeds and adds a trivial constraint  that `Null <: S`.  Since no other constraints are generated, the analyzer chooses `Null` as the preferred solution.

**Comment by mraleph** [comment] 2019-08-09 08:15
@stefantsov could you take a look at this?

**Comment by stefantsov** [comment] 2019-08-14 13:09
Proposed fix: https://dart-review.googlesource.com/c/sdk/+/113033.

**Comment by stefantsov** [comment] 2019-08-14 18:14
@leafpetersen I think I need some more clarifications about solving the constraint.  I have a few errors in the tests that can be summarized as follows.  Suppose, we have the following Dart program:

```dart
main() {
  new Future<int>.error(42).then((x) {
    throw "foo";
  }, onError: (y) => true);
}
```

Here the first argument to `then` is the closure `(x) { throw "foo"; }` of type `Null Function(int)`.

Method `then` of `Future` is defined as follows:

```dart
Future<R> then<R>(FutureOr<R> onValue(T value), {Function onError});
```

Because of the new rule for solving the constraints we impose the constraint of `Null` on `R` here via the first argument to `then`.  The implementation of `Future` that we have in `sdk/lib/async/future_impl.dart` then [passes](https://github.com/dart-lang/sdk/blob/master/sdk/lib/async/future_impl.dart#L282) `R` as a second argument to the constructor of `_FutureListener`.

Finally, `_FutureListener` handles the error via `handleError` that is defined as follows:

```dart
FutureOr<T> handleError(AsyncError asyncError) {
```

Here `T` is the second parameter to the constructor of `_FutureListener` which was substituted with `Null`.  It means that the type context of the return expressions within `handleError` is `FutureOr<Null>`.  In the example above the error handler returns a `bool`, and it fails the check at run time against `FutureOr<Null>`.

In the [CL](https://dart-review.googlesource.com/c/sdk/+/113033) that I've mentioned above I tried to update the constraint solver, and with those changes in place I get the following when I run the example program:

```
Unhandled exception:
type 'bool' is not a subtype of type 'FutureOr<Null>'
#0      _FutureListener.handleError (dart:async/future_impl.dart:155:7)
#1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#2      Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#3      Future._completeError (dart:async/future_impl.dart:530:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
#5      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#7      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

I also have similar stack traces ([one](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8905145816113326560/+/steps/test_results/0/logs/unapproved_new_test_failures__logs_/0), [two](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8905145816113326512/+/steps/test_results/0/logs/unapproved_new_test_failures__logs_/0)) on the trybots for the CL.

Although, there are no errors while compiling the SDK with the changes from the CL.  I guess it worked before because `dynamic` was inferred instead of `Null`.

**Comment by leafpetersen** [comment] 2019-08-15 17:46
That is the behavior that DDC implements, you can see that DDC is failing the tests you linked to as well.  So either way we change this, it's a breaking change.  I have a mild preference for the DDC/analyzer behavior, but probably not strong enough to override other concerns.  

I believe that @Markzipan has tested the result of changing the inference behavior in DDC from DDC->DDK.

It would be good to quantify the amount of breakage that will happen if we change the behavior in the CFE from DDK->DDC behavior.  @stefantsov can you run an internal global presubmit with your change to see how much breakage will result?

One thing weighing favor of changing the DDC behavior to the DDK behavior is that most external users are using the CFE, and we have no ability to mitigate breaking changes for external code.

**Comment by stefantsov** [comment] 2019-08-16 11:50
@leafpetersen I've used the run_presubmit.sh tool and some help from @davidmorgan to run the tests with my changes patched in, and it looks like it doesn't break anything.

**Comment by stefantsov** [comment] 2019-08-16 12:01
UPDATE: Ok, it looks like I was too optimistic.  It wasn't a global presubmit.  The results from the global presubmit are still pending.

**Comment by johnniwinther** [comment] 2019-08-21 06:21
The CL was reverted and needs to be relanded.

**Comment by vsmenon** [comment] 2019-08-22 21:37
Any update on this?  We have about 8-9 internal tests breaking due to this.

**Comment by leafpetersen** [comment] 2019-08-23 01:11
The fix was landed, but reverted since it caused breakage in our quiet period here.  I will file a breaking change request for the change (our tools are inconsistent, so something needs to change either way).

**Comment by davidmorgan** [comment] 2019-08-23 07:54
The fix broke at least one internal test--there was also an issue filed for external breakage, IIRC a testing package--I believe it should be possible to forward fix then land.

**Comment by leafpetersen** [comment] 2019-08-23 20:25
Breaking change request [filed](https://github.com/dart-lang/sdk/issues/37985).

**Comment by stefantsov** [comment] 2019-09-03 13:10
A heads up on the issue: I'm gong to land [CL 115243](https://dart-review.googlesource.com/c/sdk/+/115243) tomorrow, and then all of the clients will need to fix whatever is broken.

**Comment by stefantsov** [comment] 2019-09-04 13:17
Status update on the issue: It seems that I need to look at the potentially breakages more carefully before landing the fix.  Will post the updates here as well as the note before finally landing the fix.

**Comment by vsmenon** [comment] 2019-09-05 21:07
Any update on this?  Most DDK failures internally are due to this issue.

**Comment by leafpetersen** [comment] 2019-09-05 21:17
The breaking change request was approved.  I believe that @davidmorgan indicated that some fixup is needed internally in order to land the change.  @stefantsov are you on this?

**Comment by stefantsov** [comment] 2019-09-06 13:02
I work together with @davidmorgan currently on the internal code update in order to prevent possible breakages after the CL with the fix lands.  The cause of the breakages is that sometimes CFE now infers `Null` instead of `dynamic`, so the solution is simple — put `dynamic` explicitly after `.then` in all places that break.  This way the code will still work with the existing Dart SDK, because an inferred `dynamic` is replaced with explicitly specified `dynamic`, and will continue work after the SDK update lands.

**Comment by stefantsov** [comment] 2019-09-10 09:25
So, the internal fix is landed, and the breaking change implementation is in the CQ right now (see https://dart-review.googlesource.com/c/sdk/+/115243).  The issue should be closed soon by the bot.

**Closed** 2019-09-10 09:51 UTC
Labels: area-front-end, dev-compiler-kernel-blocker, front-end-fasta
