### ISSUE TITLE
FLUTTER web project don't run 

### ISSUE THREAD

**Issue by Geotechworld** [dart-lang/sdk#37505] opened 2019-07-11 17:09 UTC
```
   dartdevc -k arguments: --dart-sdk-summary=C:\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\pc\AppData\Local\Temp\scratch_space8fa41072-a3fb-11e9-8490-8086f2899440\packages/typed_data/typed_buffers.ddc.js --source-map --packages file:///C:/Users/pc/AppData/Local/Temp/kernel_builder_8fa41076-a3fb-11e9-8490-8086f2899440/.packages --module-name packages/typed_data/typed_buffers --multi-root-scheme org-dartlang-app --multi-root . --track-widget-creation --inline-source-map package:typed_data/typed_buffers.dart
    dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
#4      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by Geotechworld** [comment] 2019-07-11 17:14
new issue

**Comment by mraleph** [comment] 2019-07-11 17:28
Duplicate of #37490

**Closed by mraleph** 2019-07-11 17:28 UTC
