### ISSUE TITLE
Error: The return type of the method 'S0.then' is 'dynamic', which does not match the return type, 'Future<S0>', of the overridden method, 'Future.then'

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#40503] opened 2020-02-06 22:25 UTC
After we opt-in the core libraries we seem to get a number of test failures with the error
The return type of the method 'S0.then' is 'dynamic', which does not match the return type, 'Future<S0>', of the overridden method, 'Future.then'.

Here is one example :

```
/=======================================================================================================================================================\
| co19_2/LanguageFeatures/Subtyping/dynamic/generated/left_FutureOr_fail_arguments_binding_fail_A03_t01 broke (Pass -> CompileTimeError, expected Pass) |
\=======================================================================================================================================================/

--- Command "fasta" (took 883ms):
(cd /b/s/w/ir/ ; DART_CONFIGURATION=ReleaseX64NNBD ./out/ReleaseX64NNBD/dart ./pkg/front_end/tool/_fasta/compile.dart --verify -o ./out/ReleaseX64NNBD/generated_compilations/fasta/tests_co19_2_src_LanguageFeatures_Subtyping_dynamic_generated_left_FutureOr_fail_arguments_binding_fail_A03_t01/out.dill --platform ./out/ReleaseX64NNBD/vm_platform_strong.dill --enable-experiment=non-nullable --packages=./.packages ./tests/co19_2/src/LanguageFeatures/Subtyping/dynamic/generated/left_FutureOr_fail_arguments_binding_fail_A03_t01.dart )

exit code:
1

stdout:
tests/co19_2/src/LanguageFeatures/Subtyping/dynamic/generated/left_FutureOr_fail_arguments_binding_fail_A03_t01.dart:39:3: Error: The return type of the method 'S0.then' is 'dynamic', which does not match the return type, 'Future<S0>', of the overridden method, 'Future.then'.
 - 'Future' is from 'dart:async'.
Change to a subtype of 'Future<S0>'.
  then<S0>(FutureOr<S0> onValue(C1 value), {Function onError}) => null;
  ^
org-dartlang-sdk:///sdk_nnbd/lib/async/future.dart:615:13: Context: This is the overridden method ('then').
  Future<R> then<R>(FutureOr<R> onValue(T value), {Function? onError});
            ^

--- Re-run this test:
python tools/test.py -n cfe-weak-linux co19_2/LanguageFeatures/Subtyping/dynamic/generated/left_FutureOr_fail_arguments_binding_fail_A03_t01

```

**Comment by johnniwinther** [comment] 2020-02-07 07:27
Like caused by the missing normalization as with https://github.com/dart-lang/sdk/issues/40454

**Comment by stefantsov** [comment] 2020-02-10 14:24
CL https://dart-review.googlesource.com/c/sdk/+/135061 intended to fix https://github.com/dart-lang/sdk/issues/40479 seems to resolve this issue as well.

**Comment by stefantsov** [comment] 2020-02-11 13:36
This is fixed by https://github.com/dart-lang/sdk/commit/2145850d4040efb58032dcb3b11b55a02a483602.

**Closed by stefantsov** 2020-02-11 13:36 UTC
Labels: NNBD, area-front-end
