### ISSUE TITLE
Update imports on paste: really broken when copying entire file

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31240] opened 2017-10-27 21:09 UTC
Related to https://github.com/dart-lang/sdk/issues/31238

Dart: 2.0.0-dev.5.0
IntelliJ: IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3302.5, built on October 17, 2017

Start with this code:
```dart
import 'dart:html';

import 'package:angular/angular.dart';

import '../src/repo_report.dart';

@Directive(selector: '[usageCell]')
class UsageDirective implements OnInit {
  final ElementRef _el;

  TableCellElement get _element => _el.nativeElement as TableCellElement;
  // ...
}
```

Paste the entire contents into a new file, at the same spot in the lib hierarchy.

Result:

```dart
import 'package:angular/src/core/metadata.dart';

import 'package:angular/src/core/metadata/lifecycle_hooks.dart';

import 'package:angular/src/core/linker/element_ref.dart';

import 'dart:html';

import 'package:repo_manager/src/repo_report.dart';

import 'dart:html';

import 'package:angular/angular.dart';

import '../src/repo_report.dart';

@Directive(selector: '[usageCell]')
class UsageDirective implements OnInit {
  final ElementRef _el;

  TableCellElement get _element => _el.nativeElement as TableCellElement;
  // ...
}

**Comment by bwilkerson** [comment] 2019-02-18 20:56
https://dart-review.googlesource.com/c/sdk/+/93483

**Comment by asashour** [comment] 2021-10-13 20:13
I believe this is fixed. I can't reproduce when the `disableManageImportsOnPaste` is `false`.

**Comment by srawlins** [comment] 2023-04-30 03:51
Closing for now; re-open if still an issue.

**Closed by srawlins** 2023-04-30 03:51 UTC
Labels: area-analyzer, analyzer-server, P2, type-bug
