### ISSUE TITLE
Same dart code outputs different result on Web and Mobile

### ISSUE THREAD

**Issue by tolotrasam** [dart-lang/sdk#46807] opened 2021-08-04 17:00 UTC
I need to decode some encoded polyline strings to a list of Latitude and longitude

To reproduce this weird behaviour, copy the below code on your IDE and run in Dart VM, the copy the exact same code on Dart Pad (web) and observe the different result

    void main() {
      print(PolyUtil.decodePoly("_p~iF~ps|U_ulLnnqC_mqNvxq`@"));
    }
    
    class LatLng {
      const LatLng(double latitude, double longitude)
          : assert(latitude != null),
            assert(longitude != null),
            latitude =
                (latitude < -90.0 ? -90.0 : (90.0 < latitude ? 90.0 : latitude)),
            longitude = (longitude + 180.0) % 360.0 - 180.0;
    
      @override
      String toString() => '$runtimeType($latitude, $longitude)';
      final double latitude;
      final double longitude;
    }
    
    class PolyUtil {
      static List<LatLng> decodePoly(String encoded) {
        final List<LatLng> poly = <LatLng>[];
        int index = 0;
        final int len = encoded.length;
        int lat = 0, lng = 0;
    
        while (index < len) {
          int b, shift = 0, result = 0;
          do {
            b = encoded.codeUnitAt(index++) - 63;
            result |= (b & 0x1f) << shift;
            shift += 5;
          } while (b >= 0x20);
          int dlat = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
          lat += dlat;
    
          shift = 0;
          result = 0;
          do {
            b = encoded.codeUnitAt(index++) - 63;
            result |= (b & 0x1f) << shift;
            shift += 5;
          } while (b >= 0x20);
          final int dlng = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
          lng += dlng;
    
          final LatLng p = LatLng(lat / 1E5, lng / 1E5);
          poly.add(p);
        }
        return poly;
      }
    }

**Actual:**

On Dart VM: `[LatLng(38.5, -120.2), LatLng(40.7, -120.95), LatLng(43.252, -126.453)]`

On Web: `[LatLng(38.5, -10.527040000000852), LatLng(40.7, 98.39591999999539), LatLng(43.252, -157.43412000000535)]`

On a map coordinate  scale, this discrepancy is huuuuge!

**Expected**

The correct one is the output on Dart VM. I have some ideas on why I could be different (maybe JS floating point ? ) but what I need help is how to fix the code work on both platform.

MacOS, Chrome, 
infrasupports-MacBook-Pro:flit_ride samran$ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.0)
[✓] Connected device (4 available)

**Comment by vsmenon** [comment] 2021-08-04 17:28
This article has background on numbers in Dart (and on the Web in particular):

https://dart.dev/guides/language/numbers

The TL;DR is that `int` only provides 53 bits of precision on the web (due to JS number limitations as you guessed).  Some options:
- Stay within 53 bits if possible.
- Use one of the suggestions at the bottom of the article - e.g., https://pub.dev/packages/fixnum - this will give you precision at the cost of some performance.

**Comment by vsmenon** [comment] 2021-08-05 12:49
Closing this as working as intended.

**Closed by vsmenon** 2021-08-05 12:49 UTC
