### ISSUE TITLE
Strong-mode should fill omitted type parameters with type bound instead of dynamic?

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#26310] opened 2016-04-20 22:41 UTC
Context: I found many usages of ```class Rectangle<T extends num>``` with the non-generic raw type `Rectangle`. Seems like it's treated by strong-mode as `Rectangle<dynamic>`, while it would seem it could / should be `Rectangle<num>`:

```dart
import 'dart:math';

foo(Rectangle r) => bar(r);
//                      ^
// [error] Unsound implicit cast from Rectangle<dynamic> to Rectangle<num>
bar(Rectangle<num> r) => null;
```

(tested with `1.16.0-dev.2.0`)

**Comment by ochafik** [comment] 2016-04-20 22:47
cc/ @leafpetersen

**Comment by leafpetersen** [comment] 2016-04-21 00:40
This might be an instance of https://github.com/dart-lang/sdk/issues/26265 .  Are you seeing this in the IDE or the command line?  If in the IDE, can you wait until analysis stabilizes, edit the file in a way that causes re-analysis (say insert and remove a space from the middle of the word 'Rectangle'), and see if it fixes itself?

**Comment by jmesserly** [comment] 2016-04-21 00:54
yeah and FYI, the original fix was in https://github.com/dart-lang/sdk/issues/25877

**Comment by ochafik** [comment] 2016-04-21 01:52
I'm seeing this in command line (`dartanalyzer --strong math.dart`).

Note: also happens with `1.16.0-dev.5.4`, but that fix (https://github.com/dart-lang/sdk/commit/ce806bf30770bb447d077dd5e396b3a6b1906f51) seems to have made it to all 1.16.0-dev.x versions anyway.

**Comment by ochafik** [comment] 2016-04-21 01:55
If I define my own local `Rectangle`, it works: could it be that it picks up an old `dart:math`?

```dart
class Rectangle<T extends num> {}
// OK
foo(Rectangle r) => bar(r);
bar(Rectangle<num> r) => null;
```

**Comment by mezoni** [comment] 2016-04-21 12:35
@ochafik 
>>  Seems like it's treated by strong-mode as Rectangle<dynamic>, while it would seem it could / should be Rectangle<num>

`Rectangle` is a short form of `Rectangle<dynamic>` 
Q: How (and why) it should be treated asthe other type?

**Comment by jmesserly** [comment] 2016-04-21 16:42
FYI, I'm seeing "no issues found" on your original example. Using a bleeding_edge build.

**Comment by leafpetersen** [comment] 2016-04-21 17:59
@jmesserly can you double check? I see the issue with latest dev release, and with bleeding edge analyzer.

**Comment by jmesserly** [comment] 2016-04-21 18:15
Oh sorry! I was hitting the bug where running from the wrong directory, --strong is ignored :(

**Comment by bwilkerson** [comment] 2016-04-21 21:00
I can reproduce this using the command-line analyzer, but if I open the same file in my IDE (in a project that enables strong mode) I don't get an error. If I hover over either occurrence of `r` in the line

    foo(Rectangle r) => bar(r);

it reports that `r` has the static type of `Rectangle<num>`. (Without strong mode enabled the static type is `Rectangle<dynamic>` as expected.)

To save time running this down, does anyone know where the substitution of the bounds for the missing type argument is happening?

**Comment by jmesserly** [comment] 2016-04-21 21:06
> To save time running this down, does anyone know where the substitution of the bounds for the missing type argument is happening?

TypeSystem.instantiateToBounds is where we handle the difference.

It needs to be called any time we want the "default instantiation behavior". For `foo(Rectangle r)`, IIRC TypeResolverVisitor is the one that resolved parameter types?

**Comment by jmesserly** [comment] 2016-04-21 21:09
IIRC, it should be happening on this line: https://github.com/dart-lang/sdk/blob/fc55cb96a85ba1185b8a7c3966c564a09b8a3105/pkg/analyzer/lib/src/generated/resolver.dart#L9747

**Comment by bwilkerson** [comment] 2016-04-21 21:31
Thanks! That's exactly where it should happen. But for reasons I don't understand yet, the type parameter for Rectangle doesn't have a bound (which explains why it isn't being used).

**Comment by jmesserly** [comment] 2016-04-21 21:51
Oh crazy! Shot in the dark: maybe it fails to deserialize it from the SDK summary or something like that?

**Comment by bwilkerson** [comment] 2016-04-21 22:01
Thought about that. Konstantin says we're not using summaries anywhere yet. Also, I can see in the debugger where we're resolving and setting the bound (though I haven't been able to find where it's being cleared), which tells me we're not using summaries because we're following the old code path to resolve dart:math.

**Comment by bwilkerson** [comment] 2016-04-22 15:13
I believe that this is caused by a bug in the task descriptions: we're not requiring that the bounds for classes in imported libraries be resolved before resolving types in the importing library. But as Konstantin pointed out in #26265, there are also ordering issues even when the types are all defined in the same compilation unit.

**Comment by leafpetersen** [comment] 2016-04-27 20:04
Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/26265 since I think that bug captures the issue here.  If there's something additional about this bug that's not captured there, feel free to reopen.

**Closed by leafpetersen** 2016-04-27 20:04 UTC
Labels: analyzer-strong-mode, area-analyzer, ddc-beta, P1 high
