### ISSUE TITLE
Analyzer fatal crash

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/sdk#26263] opened 2016-04-14 14:22 UTC
I have a project where the analyzer completely fails, this is what I get from the log file
- Webstorm 11.0.3
- Windows 10
- SDK 1.15
- Angular 2 beta 14
(unable to provide sources)

```
AnalysisException: Cannot compute RESOLVED_UNIT for D:\dev\ext\intersentia\frontend\dart\taurus_search\web\main.dart in D:\dev\ext\intersentia\frontend\dart\taurus_search\web\main.dart
Caused by Unexpected exception while performing InferInstanceMembersInUnitTask for source C:\Users\frank\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\async-1.10.0\lib\src\typed\stream.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:249)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1132)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1130)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:864)
#9      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#10     _rootRun (dart:async/zone.dart:891)
#11     _CustomZone.run (dart:async/zone.dart:790)
#12     _CustomZone.runGuarded (dart:async/zone.dart:696)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#14     _rootRun (dart:async/zone.dart:895)
#15     _CustomZone.run (dart:async/zone.dart:790)
#16     _CustomZone.runGuarded (dart:async/zone.dart:696)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by IllegalArgumentException: argumentTypes.length (1) != typeFormals.length (0) null
#0      FunctionTypeImpl.instantiate (package:analyzer/src/dart/element/type.dart:690)
#1      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:291)
#2      List.forEach (dart:core-patch/growable_array.dart:254)
#3      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:235)
#4      InstanceMemberInferrer.inferCompilationUnit.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:98)
#5      List.forEach (dart:core-patch/growable_array.dart:254)
#6      InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:96)
#7      InferInstanceMembersInUnitTask.internalPerform (package:analyzer/src/task/dart.dart:2850)
#8      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#9      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#10     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#11     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:249)
#12     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1132)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#14     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1130)
#15     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#16     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:864)
#17     Future.Future.delayed.<anonymous closure> (dart:async/future.dart:228)
#18     _rootRun (dart:async/zone.dart:891)
#19     _CustomZone.run (dart:async/zone.dart:790)
#20     _CustomZone.runGuarded (dart:async/zone.dart:696)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#22     _rootRun (dart:async/zone.dart:895)
#23     _CustomZone.run (dart:async/zone.dart:790)
#24     _CustomZone.runGuarded (dart:async/zone.dart:696)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#26     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:668)
#1      AnalysisContextImpl.resolveCompilationUnit2 (package:analyzer/src/context/context.dart:1234)
#2      AnalysisServer.getResolvedCompilationUnits.<anonymous closure> (package:analysis_server/src/analysis_server.dart:723)
#3      runWithWorkingCacheSize (package:analysis_server/src/operation/operation_analysis.dart:35)
#4      AnalysisServer.getResolvedCompilationUnits (package:analysis_server/src/analysis_server.dart:718)
#5      AnalysisDomainHandler.getNavigation.<anonymous closure> (package:analysis_server/src/domain_analysis.dart:140)
#6      _rootRunUnary (dart:async/zone.dart:902)
#7      _CustomZone.runUnary (dart:async/zone.dart:798)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:515)
#11     _Future._completeWithValue (dart:async/future_impl.dart:424)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#13     _rootRun (dart:async/zone.dart:895)
#14     _CustomZone.run (dart:async/zone.dart:790)
#15     _CustomZone.runGuarded (dart:async/zone.dart:696)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by frankpepermans** [comment] 2016-04-14 14:32
I've now updated my pubspec file to target async v1.9.0 and everything works again,
seems like async v1.10.0 is causing trouble

@nex3

**Comment by bwilkerson** [comment] 2016-04-14 16:45
I wasn't able to reproduce this with a small example. Was strong mode enabled?

**Comment by frankpepermans** [comment] 2016-04-14 16:46
Yes that is enabled, I've tried without strong mode and it still failed

**Comment by frankpepermans** [comment] 2016-04-15 07:21
I've just been able to reproduce this in a mini-project:

```
import 'package:async/src/typed/stream.dart';

void main() {
  TypeSafeStream stream;
}
```

It may be strong mode after all? I did turn that off, but maybe the analyzer just didn't kick in again?
This is my full .analysis.options file:

```
analyzer:
 strong-mode: true
 exclude:
     - web/orm_init.dart
linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    #- camel_case_types
    #- constant_identifier_names
    - empty_constructor_bodies
    - hash_and_equals
    - library_names
    - library_prefixes
    #- non_constant_identifier_names
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
```

**Comment by frankpepermans** [comment] 2016-04-15 07:24
Retried in the mini-example, it is only occurring with strong-mode true

**Comment by bwilkerson** [comment] 2016-04-15 21:33
I'm not sure why, but I'm still not able to reproduce the problem. I created an empty package, duplicated your `.analysis_options` file (minus the exclusion, because that directory doesn't exist for me), and pasted the text into `test.dart`. I verified that strong mode is enabled and that the lints are running. Here's my pubspec.yaml, in case it might be different in some interesting way:

    name: test_pkg
    version: 0.0.1
    description: A test package.
    dependencies:
      async: 1.10.0

**Comment by frankpepermans** [comment] 2016-04-15 22:09
I've pulled in the async lib from GitHub and loaded it into Webstorm,
same issue so I started digging =>

in the troubled class I started removing methods one by one until the analyzer was happy again,
turns out this one (for example, there's more like it) gave me the problem:

```
Stream/*<S>*/ expand/*<S>*/(Iterable/*<S>*/ convert(T value)) =>
      _stream.expand(_validateType(convert));
```

I proceeded to strip all Type comments from the file and everything works fine again.

Closer inspection,
The file uses the commented type <S>, yet S is not a valid type, only T is defined when you look at the class signature:

`class TypeSafeStream<T> implements Stream<T>`

finally, writing this:

```
Stream/*<T>*/ expand(Iterable/*<T>*/ convert(T value)) =>
      _stream.expand(_validateType(convert));
```

is making the analyzer happy for me, yet adding the extra type after expand makes it crash again:

```
Stream/*<T>*/ expand/*<T>*/(Iterable/*<T>*/ convert(T value)) =>
      _stream.expand(_validateType(convert));
```

**Comment by ThomasLocke** [comment] 2016-04-26 12:11
I can confirm this issue. Using dartanalyzer 1.15.0 and async 1.10.0 = analyzer crash.

Using dartanalyzer 1.15.0 and async 1.9.0 works fine.

Also worth noting is that async 1.10.0 does NOT crash dartanalyzer version 1.14.2. It seems to be specific to dartanalyzer 1.15.0 and async 1.10.0

**Comment by ThomasLocke** [comment] 2016-04-27 06:43
Dartanalyzer 1.16.0 and async 1.10.0 works fine. The bug seems to have been fixed in 1.16.0.

**Comment by frankpepermans** [comment] 2016-04-27 06:49
It is indeed fixed on 1.16, unfortunately there's also a windows webstorm bug that causes dartium to never load.

The async lib for example was updated and released prior to the 1.16 launch, or this webstorm fix, in short my development environment is in limbo until I can update properly to 1.16.

**Comment by zoechi** [comment] 2016-04-27 09:04
@frankpepermans sounds like #26260. The issue in WebStorm only appeared because of this bug in `pub`. This is already workign for me in bleeding edge (Linux).
Can you load the app in Dartium if you load it directly from `pub serve` without the WebStorm proxy?

**Comment by frankpepermans** [comment] 2016-04-27 09:19
Haven't tried yet, sticking with 1.15 for the time being. The 1.16 issue is understandable, and it won't take long to fix I assume, however having updated pub dependecies that cause bugs with previous sdk versions is not. 

I'll test with the 1.16 release later on, again I can work around most issues if needed, but I've just sold Dart internally at a client and it's not pleasant to explain why things are breaking the whole time :)

**Comment by scheglov** [comment] 2016-09-23 19:24
OK, as the analyzer problem is fixed, I'm closing the issue.

**Closed by scheglov** 2016-09-23 19:24 UTC
Labels: area-analyzer, P1 high, Type: bug
