### ISSUE TITLE
Analyzer crash: The getter 'isBottom' was called on null

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#33357] opened 2018-06-06 02:15 UTC
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I was writing a new regression test and was just typing out the line to instantiate `testBed` (note the line was incomplete when the analyzer crashed - while `TestComponent` is also a type, I was actually in the process of writing `TestComponentNgFactory`):

```dart
@TestOn('browser')
import 'package:angular/angular.dart';
import 'package:angular_test/angular_test.dart';
import 'package:test/test.dart';

import '1382_ng_template_outlet_test.template.dart' as ng;

void main() {
  test('', () async {
    final testBed = NgTestBed.forComponent(ng.TestComponent)
  });
}

@Component(
  selector: 'test',
  template: '''
    <template></template>
    <ng-container *ngTemplateOutlet=""></ng-container>
  ''',
  directives: const [NgTemplateOutlet],
)
class TestComponent {
  @ViewChild('')
  TemplateRef templateRef;
}
```

### Versions

- Dart SDK 2.0.0-dev.59.0
- Visual Studio Code 1.23.1
- Dart Code 2.13.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/usr/local/Cellar/dart/2.0.0-dev.59.0/libexec/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.13.1
```

### Exception

Analysis failed: /\<path-to-repo\>/angular/_tests/test/regression/1382_ng_template_outlet_test.dart context: exception_20180605_190641_530

```text
NoSuchMethodError: The getter 'isBottom' was called on null.
Receiver: null
Tried calling: isBottom
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      _isBottom (package:analyzer/src/generated/type_system.dart:52)
#2      GenericInferrer._matchSubtypeOf (package:analyzer/src/generated/type_system.dart:640)
#3      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/generated/type_system.dart:257)
#4      GenericInferrer.constrainArgument (package:analyzer/src/generated/type_system.dart:118)
#5      StrongTypeSystemImpl.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:937)
#6      StaticTypeAnalyzer._inferGenericInvoke (package:analyzer/src/generated/static_type_analyzer.dart:2010)
#7      StaticTypeAnalyzer._inferGenericInvocationExpression (package:analyzer/src/generated/static_type_analyzer.dart:1968)
#8      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:851)
#9      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
#10     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6229)
#11     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
#12     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11346)
#13     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#14     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224)
#15     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7841)
#16     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6385)
#17     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11340)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#19     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11442)
#20     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#21     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#22     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6409)
#23     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11436)
#24     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11497)
#25     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#26     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3232)
#27     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11493)
#28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#29     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#31     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#32     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7276)
#33     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349)
#34     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298)
#35     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#36     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#37     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7288)
#38     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5508)
#39     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294)
#40     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5440)
#41     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#42     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#43     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7616)
#44     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6008)
#45     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434)
#46     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#47     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:432)
#48     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#49     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#50     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:5383)
#51     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:428)
#52     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6228)
#53     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871)
#54     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4325)
#55     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#56     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#57     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4321)
#58     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8263)
#59     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1353)
#60     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#61     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#62     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7276)
#63     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1349)
#64     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1298)
#65     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#66     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#67     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7288)
#68     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5508)
#69     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1294)
#70     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5440)
#71     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#72     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#73     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7591)
#74     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6008)
#75     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5434)
#76     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5284)
#77     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6241)
#78     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#79     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7584)
#80     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5984)
#81     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7576)
#82     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5974)
#83     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5277)
#84     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5613)
#85     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2504)
#86     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:710)
#87     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:129)
#88     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#89     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:128)
#90     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:103)
<asynchronous suspension>
#91     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:220)
<asynchronous suspension>
#92     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:99)
<asynchronous suspension>
#93     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1264)
<asynchronous suspension>
#94     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#95     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1223)
<asynchronous suspension>
#96     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1028)
<asynchronous suspension>
#97     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1974)
<asynchronous suspension>
#98     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1917)
#99     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#100    SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#101    StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#102    Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:435)
#103    _rootRun (dart:async/zone.dart:1126)
#104    _CustomZone.run (dart:async/zone.dart:1023)
#105    runZoned (dart:async/zone.dart:1501)
#106    Driver._captureExceptions (package:analysis_server/src/server/driver.dart:475)
#107    Driver.start (package:analysis_server/src/server/driver.dart:434)
#108    main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#109    _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#110    _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/<path-to-repo>/angular/angular_compiler",
        "explicitFileCount": 35,
        "implicitFileCount": 1060,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/angular_forms",
        "explicitFileCount": 41,
        "implicitFileCount": 570,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/angular",
        "explicitFileCount": 181,
        "implicitFileCount": 1014,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/angular_ast",
        "explicitFileCount": 63,
        "implicitFileCount": 885,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/examples/hello_world",
        "explicitFileCount": 1,
        "implicitFileCount": 283,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/examples/hacker_news_pwa",
        "explicitFileCount": 10,
        "implicitFileCount": 458,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/angular_router",
        "explicitFileCount": 36,
        "implicitFileCount": 567,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/dev",
        "explicitFileCount": 10,
        "implicitFileCount": 428,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/examples/github_issues",
        "explicitFileCount": 6,
        "implicitFileCount": 1258,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/_benchmarks",
        "explicitFileCount": 17,
        "implicitFileCount": 563,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/angular/tools/analyzer_plugin",
        "explicitFileCount": 1,
        "implicitFileCount": 859,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/examples/registration_form",
        "explicitFileCount": 3,
        "implicitFileCount": 504,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/angular_test",
        "explicitFileCount": 17,
        "implicitFileCount": 550,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/_goldens",
        "explicitFileCount": 39,
        "implicitFileCount": 1446,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/<path-to-repo>/angular/_tests",
        "explicitFileCount": 112,
        "implicitFileCount": 2373,
        "workItemQueueLength": 2,
        "cacheEntryExceptions": []
    }
]
```

**Comment by bwilkerson** [comment] 2018-06-06 04:10
@stereotype441 Is this something that you could look at?

**Comment by stereotype441** [comment] 2018-06-06 16:50
@bwilkerson Judging by the stacktrace, it looks like the analzer was trying to perform type inference on `NgTestBed.forComponent(ng.TestComponent)`, in order to infer the proper generic parameter for the call to the static method `NgTestBed.forComponent`, and for some reason the `.staticType` getter of `ng.TestComponent` returned `null`.

note: `NgTestBed.forComponent` is a static generic method defined here: https://github.com/dart-lang/angular/blob/34c31cef2c2e46da63e9bd957757a706bd8a0b4f/angular_test/lib/src/frontend/bed.dart#L147

My plate's rather full at the moment, so I'm not sure when I'll be able to dig further into this.

**Comment by leonsenft** [comment] 2018-06-08 04:37
I just hit this same crash again. Here's the source I was writing:

```dart
import 'package:angular/angular.dart';

// ignore: uri_has_not_been_generated
import 'package:path_to_regexp_demo/app_component.template.dart' as app_template;

void main() {
  runApp(app_template.)
}
```

**Comment by leonsenft** [comment] 2018-06-08 17:29
I seem to hit this every time I start writing a new file that imports generated source via a prefix. The crash occurs right after I type the '.' after the prefix.

**Comment by bwilkerson** [comment] 2018-06-08 21:42
I tried to reproduce the behavior on bleeding edge using the example above, but it did not generate an exception. It's likely that my project is not configured the way your is, but I wouldn't have expected that to be a determining factor. It's possible that the bug has been fixed on the bleeding edge, but I can't know for sure.

**Comment by leonsenft** [comment] 2018-06-08 21:51
Alright, I'll wait until the next SDK update. If this continues to occur after that I'll put together a reproduction that I can share.

**Comment by bwilkerson** [comment] 2018-06-08 21:59
Thanks!

**Comment by devoncarew** [comment] 2018-09-04 20:38
closing as likely stale

**Closed by devoncarew** 2018-09-04 20:38 UTC
Labels: analyzer-untriaged, area-analyzer, p2-medium, type-bug
