### ISSUE TITLE
Fasta allows async methods without Future return type

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#31414] opened 2017-11-20 18:43 UTC
Fasta will translate a method like:
```
int foo5() async {
  return 3;
}
```
to
```
static method foo5() → core::int async {
  return 3;
}
```

The analyzer will report a warning for this, but Fasta does not leave any indication of an issue, and
gives generated code with an async function whose return type is not a subtype of `Future`.

Perhaps Fasta should change the return type to `Future` (no type parameters) in this case.

**Comment by lrhn** [comment] 2017-11-21 09:24
This code is a strong mode error and (hopefully) a Dart 1 warning because no `Future` type can be assigned to `int`. Notice that the return type needs to be a *super*type of a `Future` type (effectively a supertype of `Future<Null>`), not a subtype.

For Dart 1 compilation in unchecked mode, the return type doesn't matter. 

In checked mode, the function should probably throw when called, but the spec doesn't actually say that. It only checks the returned value against the return type in the semantics of `return` statements, there is no explicit check mentioned at the point where the `Future` is first returned. It's similarly unclear whether the asynchronous operation would start or not, but I'd say that if returning a `Future` throws, the operation should probably not be started.

(In practice, frankly, I don't give a damn about this error condition).

**Comment by sjindel-google** [comment] 2017-11-21 12:26
> In either case, Fasta should most certainly not change the input. That would make the error much harder to find.

Fasta needs to produce valid, well-typed Kernel in any case where it does not reject the input program.
It can surface the error by attaching other metadata to the Kernel AST (like Invalid nodes), but it chooses
to accept an input program, it must generate well-typed Kernel from it.

**Comment by peter-ahe-google** [comment] 2017-11-21 13:44
Yes, this a bug in Fasta.

**Comment by peter-ahe-google** [comment] 2017-11-21 13:56
For error recovery, we should probably create a method that looks like this:

```
static method foo5() → Future<core::int> async {
  <<invalid-method-body>>
}
```

This keeps the output well-formed and the async transformer should be able to generate a method that synchronously reports the compile-time error.

**Comment by sigmundch** [comment] 2017-11-21 22:46
Note this also relates to https://github.com/dart-lang/sdk/issues/30629

Fasta does imply the return type for async functions when they are untyped, the logic to do so was mixed with the logic to infer types in strong mode, so we expect that this will regress in legacy mode short term

**Comment by vsmenon** [comment] 2018-03-19 15:36
@kmillikin - I bumped this to Beta 3.  Can you move to [Beta 4 ](https://github.com/dart-lang/sdk/milestone/54)or [Dart 2](https://github.com/dart-lang/sdk/milestone/12) if one of those is more appropriate?

**Comment by kmillikin** [comment] 2018-05-24 09:43
A duplicate of https://github.com/dart-lang/sdk/issues/33068

**Closed by kmillikin** 2018-05-24 09:43 UTC
Labels: P2 medium, area-front-end, front-end-fasta, moved-from-dart2beta3
