### ISSUE TITLE
Test coverage not working for pattern destructuring of `dynamic` typed fields 

### ISSUE THREAD

**Issue by renancaraujo** [dart-lang/sdk#53519] opened 2023-07-12 12:32 UTC
Right now, it is impossible to attain 100% test coverage if you use pattern destructuring in your codebase on structures typed as `dynamic`. 

### To reproduce

`main.dart`
```dart
String thisDoesStuff(Map<String, dynamic> map) {
  final {'hello': world, 'count': count} = map;
  return 'Hello $world, count: $count';
}
```

`main_test.dart`
```dart
void main() {
  test('stuff', () {
    var myJson = <String, dynamic>{
      'hello': 'world',
      'count': [1, 2, 3],
    };
    expect(thisDoesStuff(myJson), 'Hello world, count: [1, 2, 3]');
  });
}
```

In those examples, generated coverages will mark `final {'hello': world, 'count': count} = map;` as an uncovered line.

If we change that line to `var {'hello': String world, 'count': List<int> count} = map;`, it will **mark** as covered.

**Comment by liamappelbe** [comment] 2023-09-13 23:38
@johnniwinther Alex mentioned you'd be willing to take this bug if I give you some more info. The easiest way to repro the issue is to compile this to a dill file then use dump_kernel.dart (with `showOffsets: true`).

```dart
String destructure(Map<String, dynamic> map) {
  final {'hello': world, 'count': count} = map;
  return 'Hello $world, count: $count';
}

main() {
  print(destructure({
    'hello': 'world',
    'count': [1, 2, 3],
  });
}
```

To show the offsets, you'll need to change this line in pkg/vm/bin/dump_kernel.dart to enable `showOffsets`:

```dart
  writeComponentToText(
      component, path: output, showOffsets: true, showMetadata: true);
```

So the full command I run is:

```bash
out/ReleaseX64/dart compile kernel destructure_coverage.dart && out/ReleaseX64/dart run pkg/vm/bin/dump_kernel.dart destructure_coverage.dill destructure_coverage.dill.log && cat destructure_coverage.dill.log
```

I get this output:

```
[0]  static method main() → dynamic {
[-1]    [11] [11] core::print [-1]([17] tup::destructure [-1]([29]<core::String, dynamic>{[-1] [-1] [-1] "hello": [-1] [-1] "world", [-1] [-1] [-1] "count": [66] [66] core::_GrowableList::_literal3 [-1]<core::int>([-1] 1, [-1] 2, [-1] 3)}));
  }
[94]  static method destructure([127] core::Map<core::String, dynamic> map) → core::String {
[152]    [152] final hoisted has-declared-initializer dynamic world;
[168]    [168] final hoisted has-declared-initializer dynamic count;
[136]    {
[177]      [177] final synthesized core::Map<core::String, dynamic> #0#0 = [177] [177] map;
[-1]      function ##0#3#initializer() → dynamic
[-1]        return [150] [150] [177] [177] #0#0.{core::Map::[]}[-1]([143] #C1){(core::Object?) → dynamic};
[-1]      [-1] late final synthesized dynamic #0#3 = [-1] [-1] ##0#3#initializer [-1](){() → dynamic};
[-1]      function ##0#6#initializer() → dynamic
[-1]        return [166] [166] [177] [177] #0#0.{core::Map::[]}[-1]([159] #C2){(core::Object?) → dynamic};
[-1]      [-1] late final synthesized dynamic #0#6 = [-1] [-1] ##0#6#initializer [-1](){() → dynamic};
[136]      if([-1] [-1]![-1]([-1] [-1] [-1] [-1] [-1] [-1]([-1] [-1] [-1]![150]([150] [-1] [-1] #0#3 == null) || [-1] [-1] [150] [150] [-1] [-1] null is dynamic && [150] [150] [177] [177] #0#0.{core::Map::containsKey}[-1]([143] #C1){(core::Object?) → core::bool}) && [152]([152] let [152] final dynamic #t1 = [152] [152] world = [-1] [-1] #0#3 in [-1] [-1] true) && [-1]([-1] [-1] [-1]![166]([166] [-1] [-1] #0#6 == null) || [-1] [-1] [166] [166] [-1] [-1] null is dynamic && [166] [166] [177] [177] #0#0.{core::Map::containsKey}[-1]([159] #C2){(core::Object?) → core::bool}) && [168]([168] let [168] final dynamic #t2 = [168] [168] count = [-1] [-1] #0#6 in [-1] [-1] true)))
[-1]        [136] [136] throw [136] [136] new core::StateError::• [-1]([-1] "Pattern matching error");
    }
[184]    return [220] [220] "Hello ${[199] [199] world}, count: ${[214] [214] count}";
  }
}
constants  {
  #C1 = "hello"
  #C2 = "count"
}
```

The valid file offsets (anything other than -1) on the synthetic if statement and throw towards the end of the `destructure` function are causing the bug. The coverage tool will ignore any AST nodes that don't have a `fileOffset` (and any functions with the `isSynthetic` flag). So the main options for a fix are:

1. Modify the front end to remove the offsets from the desugared if statement and throw. Note that you'll need to remove the offsets from every AST node we want to ignore (this is the part I was having trouble with - it's hard to track down where every last node is created).
2. Add a new flag that tells the coverage tool to ignore these nodes. Eg, maybe add an `isSynthetic` flag to the `Statement` AST node. Once this lands, I'll take care of updating the coverage tool to ignore everything under these nodes. This means we only have to add the flag to the root of the subtree we want to ignore (rather than removing offsets from *every* node we want to ignore), and also avoids the issues of interfering with other systems that rely on those offsets. But it'll be more work to implement.

**Comment by johnniwinther** [comment] 2023-09-19 07:19
@liamappelbe In the example, the if-statement and its then-statement are part of the code generated to handle unmatched values, which is probably the part we don't want to require coverage for. (Part of) the condition, though, is matching code, directly related to the matching. Don't we want to track coverage for that? If so, marking the if-statement as "not-for-coverage" will hide the parts of the condition that we do want coverage for.

**Comment by liamappelbe** [comment] 2023-09-19 21:19
@johnniwinther We generally only track coverage for function calls, so a statement like `final x = 123;` wouldn't be considered coverable. If I'm a user who doesn't know about the details of the desugaring, `final {'hello': world, 'count': count} = map;` looks analogous to that, so I'd expect it to not be coverable.

Also, if we consider this sort of destructuring assignment coverable due to the current desugaring implementation, then in the future the front end could make some change to how the desugaring is implemented that is totally invisible to users, but suddenly that line could become uncoverable. This is exactly what happened in the record destructuring case. It could be a bit confusing to users.

The only exception I can think of would be if we had a non-trivial expression on the right of the assignment: `final {'hello': world, 'count': count} = someFunc();`. I'd expect this line to be considered coverable because of `someFunc()`. But in that case presumably the evaluation of `someFunc()` happens outside of the synthetic if statement, so this would still be coverable even if the if statement is marked as synthetic. Is that true?

**Comment by johnniwinther** [comment] 2024-01-08 14:05
@liamappelbe If we added `Statement.isErrorHandling` and/or `Expression.isErrorHandling` for statements/expressions whose whole evaluation is for correctness/soundness of erroneous cases (like a non-matching pattern variable declaration), would that be sufficient for you to avoid tracking coverage?

For `final {'hello': world, 'count': count} = map;` we would mark the body of the `if` statement as `isErrorHandling`.

**Comment by johnniwinther** [comment] 2024-01-08 14:21
Looking through the cases we have currently, it looks like the `Throw` expression is the common denominator. @liamappelbe would be enough if only the `Throw` node is marked as `isErrorHandling` ?

**Comment by liamappelbe** [comment] 2024-01-08 21:36
> If we added `Statement.isErrorHandling` and/or `Expression.isErrorHandling` for statements/expressions whose whole evaluation is for correctness/soundness of erroneous cases (like a non-matching pattern variable declaration), would that be sufficient for you to avoid tracking coverage?

Yep, that sounds good.

> would be enough if only the `Throw` node is marked as `isErrorHandling` ?

I don't think so. There are function calls in the if's condition expression that would be considered coverable.

**Comment by johnniwinther** [comment] 2024-01-09 07:40
So what call in `final {'hello': world, 'count': count} = map;` is it that causes the missing coverage? As far as I can the whole condition has to be evaluated to match the expression so it should be covered.

**Comment by johnniwinther** [comment] 2024-02-19 13:37
https://dart-review.googlesource.com/c/sdk/+/347900 has now landed which adds a `Throw.forErrorHandling` flag.

**Closed** 2024-02-27 22:00 UTC
Labels: area-front-end, cfe-encodings
