### ISSUE TITLE
Regression on inference for Iterable.fold?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27407] opened 2016-09-21 14:41 UTC
The following tests have stopped inferring closure types for closures passed into `Iterable.fold`.  Not clear when this broke as there was a separate issue yesterday keeping these from running.

@jmesserly @leafpetersen 

```
*** Compiling SDK to JavaScript
01:07 +3810 -3: codegen dartdevc corelib/collection_test                                           
  Expected: true
    Actual: <false>
  test corelib/collection_test failed to compile due to strong mode errors:
  
  [error] The argument type '(dynamic, dynamic) → dynamic' cannot be assigned to the parameter type '(int, dynamic) → int'. (gen/codegen_tests/corelib/collection_test.dart, line 16, col 40)
  [error] The argument type '(dynamic, dynamic) → dynamic' cannot be assigned to the parameter type '(int, dynamic) → int'. (gen/codegen_tests/corelib/collection_test.dart, line 17, col 42).
  
  package:test                  expect
  test/codegen_test.dart 145:9  main.<fn>
  
01:10 +3987 -4: codegen dartdevc corelib/list_map_test                                             
  Expected: true
    Actual: <false>
  test corelib/list_map_test failed to compile due to strong mode errors:
  
  [error] The argument type '(dynamic, dynamic) → dynamic' cannot be assigned to the parameter type '(int, dynamic) → int'. (gen/codegen_tests/corelib/list_map_test.dart, line 118, col 29).
  
  package:test                  expect
  test/codegen_test.dart 145:9  main.<fn>
  
01:10 +3990 -5: codegen dartdevc corelib/list_reversed_test                                        
  Expected: true
    Actual: <false>
  test corelib/list_reversed_test failed to compile due to strong mode errors:
  
  [error] The argument type '(dynamic, dynamic) → dynamic' cannot be assigned to the parameter type '(int, dynamic) → int'. (gen/codegen_tests/corelib/list_reversed_test.dart, line 110, col 29).
  
  package:test                  expect
  test/codegen_test.dart 145:9  main.<fn>
```

**Comment by vsmenon** [comment] 2016-09-21 14:42
This may be unrelated, but these two tests started passing strong mode checking:
```
00:57 +2953 -1: codegen dartdevc language/regress_21998_3_test                                     
  Expected: false
    Actual: <true>
  test language/regress_21998_3_test expected strong mode errors, but compiled.
  
  package:test                  expect
  test/codegen_test.dart 142:9  main.<fn>
  
00:57 +2953 -2: codegen dartdevc language/regress_21998_4_test                                     
  Expected: false
    Actual: <true>
  test language/regress_21998_4_test expected strong mode errors, but compiled.
  
  package:test                  expect
  test/codegen_test.dart 142:9  main.<fn>
```

**Comment by vsmenon** [comment] 2016-09-21 16:07
Here's a small example:

```dart
main() {
  Iterable iter = [1, 2, 3, 4];
  var x = iter.fold(0, (a, b) => a+b);
  print(x);
}
```

**Comment by jmesserly** [comment] 2016-09-21 17:34
it's a dupe of https://github.com/dart-lang/sdk/issues/27408

**Closed by jmesserly** 2016-09-21 17:34 UTC
Labels: analyzer-strong-mode, area-analyzer

**Comment by jmesserly** [comment] 2016-09-21 17:36
FYI too, Leaf and I discussed `fold` in particular here: https://codereview.chromium.org/2343863004

we weren't inferring `fold` correctly before either, FYI. It simply ended up `dynamic` which may trigger a down cast composite failure later.
