### ISSUE TITLE
gzip can't decode concatenated gzip streams

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#47244] opened 2021-09-18 13:07 UTC
SDK: 2.14.1

```dart
final data = [
  ...gzip.encode([0, 0, 0, 0]),
  ...gzip.encode([1, 1, 1, 1]),
];
final decoded = gzip.decode(data); // only [0, 0, 0, 0], expected: [0, 0, 0, 0, 1, 1, 1, 1]
```

In comparison, the command-line `gzip` is just fine with decoding the concatenated stream.

**Comment by lrhn** [comment] 2021-09-20 08:30
It does seem that detecting multiple data streams and extracting them as one is the [default behavior](https://stackoverflow.com/questions/8005114/fast-concatenation-of-multiple-gzip-files).
We may want to copy that, so after decoding one gzip stream, we check whether it's followed by another.

**Comment by isoos** [comment] 2021-09-24 06:44
It has many practical use cases, e.g. `.tar.gz` and `.warc.gz` files compressed by file segments - it makes the overall file seekable to a certain file position (with an outside index), while keeping the overall compression. We could probably use the segmented `.tar.gz` approach in `pub.dev`'s backend to store `dartdoc` content too.

I think the implementation may need to change only a little bit: don't close the processing on the end of the `gzip` frame during chunked encoding, rather close it only at the end of the input stream.

**Comment by brianquinlan** [comment] 2024-04-22 22:14
Duplicate of https://github.com/dart-lang/sdk/issues/55469

**Closed by brianquinlan** 2024-04-22 22:14 UTC
Labels: area-vm, library-io, type-enhancement
