### ISSUE TITLE
Analyzer doesn't catch conflict between static member and constructor names.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#46322] opened 2021-06-10 14:09 UTC
Example:
```dart
class C {
  C.foo();
  static int foo() => 42;
}
```
This class should have an error because you're not allowed to have a named constructors with the same identifier as the basename of a static member.
> ```latex
> \item The identifier of a named constructor cannot be
>  the same as the name of a static member declared in the same class
>  (\ref{classMemberConflicts}).
> ```

(@eernstg, I think it should say "basename" instead of "name", otherwise you could have a `C.foo` constructor and a static `foo=` setter, and nobody wants *that*!)

The analyzer does not give any warning or error.

The front-end provides:
```
badclass.dart:2:3: Error: Conflicts with member 'foo'.
  C.foo();
  ^
badclass.dart:3:14: Error: Conflicts with constructor 'C.foo'.
  static int foo() => 42;
             ^
```

**Comment by eernstg** [comment] 2021-06-10 17:09
I do see an error from the analyzer in dart-pad, which version of the analyzer did you use when there was no error?

> I think it should say "basename" instead of "name", otherwise you could
> have a `C.foo` constructor and a static `foo=` setter, and nobody wants that!

Right, we do have that in the normative text, 'Class Member Conflicts', but the commentary that you mention should be corrected. Cf. https://github.com/dart-lang/language/pull/1676.

**Comment by leafpetersen** [comment] 2021-08-03 15:50
I can't reproduce this either.  Closing, please re-open if I've missed something.

**Closed by leafpetersen** 2021-08-03 15:50 UTC
Labels: P1, analyzer-spec, area-analyzer, type-bug
