### ISSUE TITLE
FATAL error: Failed to handle request

### ISSUE THREAD

**Issue by LucianoSP** [dart-lang/sdk#33280] opened 2018-05-30 21:16 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4720617`
- `2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c`
- `AI-173.4720617, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\82399697120\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.c080951d45e79cd25df98036c4be835b284a269c, server version 1.20.2, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\82399697120\AndroidStudioProjects\colorbrilho], excluded: [C:\Users\82399697120\AndroidStudioProjects\colorbrilho\.idea, C:\Users\82399697120\AndroidStudioProjects\colorbrilho\.dart_tool, C:\Users\82399697120\AndroidStudioProjects\colorbrilho\.idea, C:\Users\82399697120\AndroidStudioProjects\colorbrilho\.pub, C:\Users\82399697120\AndroidStudioProjects\colorbrilho\build]}, clientRequestTime: 1527714827702}
FileSystemException: Exists failed, path = 'C:\Users\82399697120\AndroidStudioProjects\colorbrilho\build\app\intermediates\transforms\dexBuilder\debug\136\com\google\firebase\analytics' (OS Error: Acesso negado.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:323)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166)
#3      _HashVMBase

**Comment by srawlins** [comment] 2019-09-06 15:54
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/33106; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 15:54
Duplicate of https://github.com/dart-lang/sdk/issues/33106

**Closed by srawlins** 2019-09-06 15:54 UTC
Labels: P2, analyzer-crash-report, analyzer-server, area-analyzer, type-bug
