### ISSUE TITLE
Dart analysis server, SDK version 2.1.0, server version 1.21.1, error: Captured exception NoSuchMethodError: The getter 'parameters' was called on null.

### ISSUE THREAD

**Issue by szepeshazi** [dart-lang/sdk#35755] opened 2019-01-25 12:41 UTC
Dart Analyzer Server frequently crashes in IntelliJ (on Windows 10 x64). Let me know if I should keep posting issues for each crash type.

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-181.4203.550`
- `2.1.0`
- `IU-181.4203.550, JRE 1.8.0_152-release-1136-b20x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception
```
Dart analysis server, SDK version 2.1.0, server version 1.21.1, error: Captured exception
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1059:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2932:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:410:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1016:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1751:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:457:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:414:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:413:26)
#12     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#14     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218:20)
#15     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291:9)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:903:22)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#19     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#20     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#21     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#22     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#28     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#29     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analysis_server/bin/server.dart:12:11)
#30     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#31     main (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/analysis_server/bin/server.dart:10:10)
#32     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
1548418801034 <= {"event":"analysis.highlights","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","regi
1548418801035 <= {"event":"analysis.navigation","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","regi
1548418801035 <= {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","l
1548418801036 <= {"event":"analysis.outline","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","kind":"
1548418801036 => {"id":"3116","method":"edit.getAssists","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.da
1548418801036 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","overr
1548418801036 => {"id":"3117","method":"edit.getAssists","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.da
1548418801038 <= {"id":"3115","result":{"assists":[]}}
1548418801039 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548418801039 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","cla
1548418801042 <= {"id":"3116","result":{"assists":[]}}
1548418801042 <= {"id":"3117","result":{"assists":[]}}
1548418801057 => {"id":"3118","method":"analysis.updateContent","params":{"files":{"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nut
1548418801057 => {"id":"3119","method":"completion.getSuggestions","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nu
1548418801059 <= {"id":"3118","result":{}}
1548418801059 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548418801076 <= {"id":"3119","result":{"id":"575"}}
1548418801076 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","errors":
1548418801078 <= {"event":"analysis.highlights","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","regi
1548418801080 <= {"event":"analysis.navigation","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","regi
1548418801080 <= {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","l
1548418801080 <= {"event":"analysis.outline","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","kind":"
1548418801080 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nutrition.dart","overr
1548418801178 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\product_module.dart","errors":[]}}
1548418801221 => {"id":"3120","method":"analysis.updateContent","params":{"files":{"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nut
1548418801221 => {"id":"3121","method":"completion.getSuggestions","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\pages\\products\\nutrition\\nu
1548418801296 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\app_component.dart","errors":[{"severity":"INFO","type":"T
1548418801299 <= {"id":"3120","result":{}}
1548418801301 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\aszepeshazi\\IdeaProjects\\gyerunkanyukam.hu\\krafty\\frontend\\lib\\src\\video\\components\\calendar_components\\program_week_
1548418801319 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'parameters' was called on null.\nReceiver: null\nTried ca
```

```
Dart analysis server, SDK version 2.1.0, server version 1.21.1, error: Captured exception
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1059:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2932:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:410:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1016:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1751:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:457:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:414:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:413:26)
#12     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)

**Comment by stereotype441** [comment] 2019-01-25 20:22
Duplicate of #34610

**Closed by stereotype441** 2019-01-25 20:22 UTC
Labels: area-analyzer
