### ISSUE TITLE
RegExp is very slow in AOT mode

### ISSUE THREAD

**Issue by ethanblake4** [dart-lang/sdk#42366] opened 2020-06-17 00:19 UTC
Matching strings using the RegExp class is incredibly slow in Dart AOT mode, about 15x slower than when using the VM for large numbers of matches. I am building a syntax highlighting engine in Dart for a Flutter-based code editor and this is crippling the performance for release builds.

Test file: 
```dart
import 'dart:io';
main() {
  var matcher = r'''(?:(\w+)|''([^'']+)''|"([^"]+)"|`([^`]+)`)(?=[ \t]*(?:[^\w'"`. \t]|$))''';
  var rg = RegExp(matcher);
  var accumulator = 0;
  var time = DateTime.now().microsecondsSinceEpoch;
  for(var i = 0; i < 1000000; i++) {
    accumulator += rg.firstMatch("Testing string").start;
  }
  print(accumulator);
  print("took ${DateTime.now().microsecondsSinceEpoch - time} microseconds");
}
```

This code takes a typical regex used for highlighting SQL syntax and matches it against a test string 1 million times, measuring the time it takes. The accumulator is there to prevent either compiler from optimizing anything out.

Running using VM (`dart main.dart`) takes ~0.5 sec on my 2016 MacBook Pro:
```
8000000
took 560724 microseconds
```

Running AOT (`dart2native main.dart -o regextest; ./regextest`) takes nearly 8 seconds:
```
8000000
took 7740348 microseconds
```

Platform: macOS, Dart: 2.8.0-dev.0.0

**Comment by mraleph** [comment] 2020-06-17 10:13
Duplicate of #37785

**Closed by mraleph** 2020-06-17 10:13 UTC

**Comment by mraleph** [comment] 2020-06-17 12:42
https://dart-review.googlesource.com/c/sdk/+/151515 should improve regexp performance in AOT mode a bit, but making it really comparable with JIT requires addressing #37785

**Comment by ethanblake4** [comment] 2020-06-17 15:46
@mraleph Interesting... unfortunately, in my actual application, the patterns will *not* be compile-time constants since they will be loaded from a file. I'd be happy with a regexp.compile() method or similar, not sure if you want to leave this open because of that. The dart-review you linked will hopefully help though.

**Comment by mraleph** [comment] 2020-06-18 08:23
> the patterns will not be compile-time constants since they will be loaded from a file. 

Yeah, that's more challenging. The RegExp engine we use relies on compiling regular expressions into machine code through our JIT compilation pipeline - which is naturally not available in AOT builds, bringing that functionality into release builds is challenging and would not work on iOS (only on Android and desktops), so addressing this uniformly is challenging. We should probably evaluate if rewriting interpreter loop in machine code gives any noticeable performance improvement.
