### ISSUE TITLE
Fasta crash: Failed assertion

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29981] opened 2017-06-22 07:20 UTC
@peter-ahe-google
ID: 48fcf3056c026d2f66d40a788918071370191888
```
Unhandled exception:
'package:front_end/src/fasta/kernel/kernel_class_builder.dart': Failed assertion: line 75 pos 12: 'arguments == null || cls.typeParameters.length == arguments.length': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      KernelClassBuilder.buildTypesWithBuiltArguments (package:front_end/src/fasta/kernel/kernel_class_builder.dart:75:12)
#3      TypeDeclarationAccessor.buildType (package:front_end/src/fasta/kernel/fasta_accessors.dart:1017:21)
#4      BodyBuilder.handleType (package:front_end/src/fasta/kernel/body_builder.dart:1702:17)
#5      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1189:16)
#6      Parser.parseTypeArgumentsOpt.<anonymous closure> (package:front_end/src/fasta/parser/parser.dart:1226:16)
#7      Parser.parseStuff (package:front_end/src/fasta/parser/parser.dart:1249:28)
#8      Parser.parseTypeArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:1223:12)
#9      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1188:15)
#10     Parser.parseTypeOpt (package:front_end/src/fasta/parser/parser.dart:844:14)
#11     Parser.parseModifiers (package:front_end/src/fasta/parser/parser.dart:1806:49)
#12     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1347:19)
#13     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2045:11)
#14     DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:565:22)
#15     DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:447:5)
#16     DietListener.endFields (package:front_end/src/fasta/source/diet_listener.dart:199:5)
#17     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:1375:16)
#18     Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2045:11)
#19     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:1939:15)
#20     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1071:13)
#21     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1032:14)
#22     Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:357:14)
#23     Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:344:13)
#24     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#25     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:146:14)
<asynchronous suspension>
#26     Loader.buildBodies (package:front_end/src/fasta/loader.dart:117:13)
<asynchronous suspension>
#27     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:282:20)
<asynchronous suspension>
#28     CompileTask.compile (package:front_end/src/fasta/fasta.dart:164:38)
<asynchronous suspension>
#29     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#30     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#31     _rootRun (dart:async/zone.dart:1120)
#32     _CustomZone.run (dart:async/zone.dart:1001)
#33     runZoned (dart:async/zone.dart:1467)
#34     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#35     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#36     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#37     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#38     main (file:///home/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

**Comment by peter-ahe-google** [comment] 2017-06-22 13:05
Repro:

```
class C<T> {
  C<String, String> field;
}

main() {
  print(new C());
}
```

**Comment by jensjoha** [comment] 2018-01-09 08:23
I cannot reproduce a crash, but do get a warning (non-strong-mode) or an error (strong-mode) when compiling the repro code. Can this issue be closed?

**Comment by stefantsov** [comment] 2018-05-18 14:28
I believe this is fixed in https://github.com/dart-lang/sdk/commit/5af05d407d3d6edd0cc3f75d2f46a6b49ecfb216.

**Closed by stefantsov** 2018-05-18 14:28 UTC
Labels: P3 low, area-front-end, front-end-fasta
