### ISSUE TITLE
Dartium in RAW channel not being updated since September 16.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#24438] opened 2015-09-25 09:33 UTC
http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/dartium/
See also dart-lang/polymer-dart#584

**Comment by ricowind** [comment] 2015-09-25 09:55
That is because we only push these on green, dartium has not been green since then
cc @alan-knight @a-siva

**Comment by zoechi** [comment] 2015-09-25 10:08
This seems only to be the case for `/latest`.
I just found http://gsdview.appspot.com/dart-archive/channels/be/raw/133807/
here the files have the current date (25-Sep-2015).

**Comment by ricowind** [comment] 2015-09-25 10:21
Correct, that is by design, we use dartium from latest for testing (e.g., dart team developers will pull it down when running tests, so we want a working version). You can see that here:
https://github.com/dart-lang/sdk/blob/master/tools/dartium/buildbot_annotated_steps.py#L119

**Comment by ricowind** [comment] 2015-09-25 10:28
If you want a recent build, and you do not care about if it is green or not, you can always go to the bots:
http://build.chromium.org/p/client.dart/console
then click on one of the boxes under dartium, there are download links there for each revision

**Comment by zoechi** [comment] 2015-09-25 10:31
Ok, so I guess I need to check file dates in http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/dartium/ and if they are  not up-to-dart decide if I still want to use it or use from a specific version instead.
Shouldn't your `latest` fail because of the problem I run into with Polymer?
If this is all "as designed" then please just close the issue.

**Comment by alan-knight** [comment] 2015-09-25 16:32
OK, we landed a major change and are cleaning up the bug trail, but it sounds like we'd better just suppress the failing tests and file bugs for them.

**Comment by zoechi** [comment] 2016-03-01 12:07
Is there still any action planned. Otherwise this could be closed.

**Closed** 2017-11-19 12:44 UTC
Labels: area-dartium
