### ISSUE TITLE
Too general type inference in relation to different enums implementing the same interface

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#54301] opened 2023-12-10 21:44 UTC
Consider the following class hierarchy:
```dart
abstract interface class A {}

final class B implements A {}

final class C implements A {}

A fnA(int code) {
  return switch (code) {
    0 => B(),
    _ => C(),
  };
}
```
The analyzer correctly analyzes it without errors.

However, if we rewrite the example to:
```dart
abstract interface class A2 {}

enum B2 implements A2 { b }

enum C2 implements A2 { c }

A2 fnA2(int code) {
  return switch (code) {
    0 => B2.b,
    _ => C2.c,
  };
}
```

The analyzer complains that the return of `fnA2()` is `Object` instead of `A2`. However, this is incorrect as both enums implement `A2`.

Dart version:
`Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"`

**Comment by eernstg** [comment] 2023-12-10 22:20
The reason why the standard upper bound of `B2` and `C2` is `Object` rather than `A2` is that every `enum` declaration corresponds to a class declaration (where the special constructs available in an `enum` declaration are rewritten to regular class member declarations), and that rewriting step introduces some superinterfaces (in particular, a class named `Enum`). The `enum` declaration is specified to work in the same way as that class, which means that those superinterfaces must be taken into account when the standard upper bound is computed for one or more types based on `enum` declarations.

https://github.com/dart-lang/language/issues/3290 contains a discussion with very similar elements.

I'll close this issue is a duplicate of dart-lang/language#3290.

**Closed by eernstg** 2023-12-10 22:20 UTC

**Comment by jellynoone** [comment] 2023-12-11 09:07
Aha, thank you for letting me know. I didn't see those issues earlier.
