### ISSUE TITLE
Could not find summary for dart:core

### ISSUE THREAD

**Issue by AndroidNils** [dart-lang/sdk#34649] opened 2018-10-02 19:30 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.4cf2d3990bac1f1df2f524899e1560a3683f3133`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1200`

# Exception

Please append the contents of:
file://C:\Users\nils\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.4cf2d3990bac1f1df2f524899e1560a3683f3133, server version 1.20.5, error: Failed to handle completion domain request: {id: 2175, method: completion.getSuggestions, params: {file: C:\Users\nils\AndroidStudioProjects\geoapp\lib\pages\overview_route_page.dart, offset: 600}, clientRequestTime: 1538508543926}
Exception: Element not found in summary: dart:core

**Comment by bwilkerson** [comment] 2018-10-03 20:35
Thanks for reporting this! Unfortunately, there isn't enough information here for us to reproduce the problem. One guess is that the Dart SDK might have been deleted (or updated) at the time this happened. Do you know whether that might be the case? If that's not the case, do you know what you were doing at the time?

**Comment by bwilkerson** [comment] 2018-10-03 22:05
Possibly a duplicate of https://github.com/dart-lang/sdk/issues/34544.

**Comment by AndroidNils** [comment] 2018-10-03 22:10
@bwilkerson Yes, that's it! I was editing almost the same code.

**Comment by bwilkerson** [comment] 2018-10-03 22:12
Then I'll close this in favor of the more complete report.

**Closed by bwilkerson** 2018-10-03 22:12 UTC
Labels: area-analyzer, needs-info, p3-low, type-bug
