### ISSUE TITLE
Closure autocompletion does not work on non-first named parameters

### ISSUE THREAD

**Issue by kefasjw** [dart-lang/sdk#48514] opened 2022-03-05 02:05 UTC
## Steps to reproduce

1. Copy this code
    ```dart
    void myFunction({
      required Function() param1,
      required Function() param2,
    }) {}
    
    void main(List<String> arguments) {
      myFunction(
        param1: () {},
        param2: /*CURSOR_HERE*/,
      );
    }
    ```
2. Trigger auto completion

## Actual Result

No closure suggestion

![image](https://user-images.githubusercontent.com/11681703/156863306-1d93bbeb-b6b6-48f7-9f4b-67eac93b4d44.png)

## Expected Result

Suggest closure autocompletion like on the first parameter

![image](https://user-images.githubusercontent.com/11681703/156863340-d23b36c1-15a0-4d1d-9934-37a4999ce119.png)

## Version info

Dart: Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"
Dart Intellij Plugin: 203.8452

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2 21D49 darwin-arm, locale
    en-ID)
    • Flutter version 2.10.2 at /opt/homebrew/Caskroom/flutter/2.8.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/kefasjw/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Users/kefasjw/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111
      /Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/kefasjw/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2020.3.4)
    • IntelliJ at /Users/kefasjw/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-2/203.8084.24/IntelliJ IDEA
      CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Users/kefasjw/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/213.6777.52/IntelliJ IDEA
      CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version EAP IC-221.4165.146)
    • IntelliJ at /Users/kefasjw/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-1/221.4165.146/IntelliJ IDEA
      2022.1 CE EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2 21D49 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</p>

</details>

**Comment by asashour** [comment] 2022-04-23 05:40
https://dart-review.googlesource.com/c/sdk/+/242281

**Comment by asashour** [comment] 2022-04-23 13:04
Duplicate of #48310

**Closed** 2022-04-23 16:07 UTC
Labels: area-analyzer, analyzer-completion, P3, type-bug
