### ISSUE TITLE
catch exception/error with void return method?

### ISSUE THREAD

**Issue by zhengbomo** [dart-lang/sdk#37032] opened 2019-05-21 07:02 UTC
how to catch exception from method with `void` retrurn, here is my code 
```dart
void testCatch() {
  try {
    testRequest();
  } catch (e) {
    print("catch e");
  }
}

void testRequest() async {
  try {
    await Future.delayed(const Duration(seconds: 1));
    throw "404 error";
  } catch (e) {
      throw "cancel error";
  }
}
```

when i run `testCatch`, I get an unhandled exception like this
<img width="921" alt="WX20190521-145948@2x" src="https://user-images.githubusercontent.com/4704147/58075020-2e837e80-7bd9-11e9-993f-6a1c65aa40d4.png">

how can i catch the exception from the async method with void return value

```
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by stoleruedgar** [comment] 2019-05-21 09:39
@zhengbomo The testCatch() returns before testRequest() completes. Either make testCatch() async and write await testRequest() or use a callback in the testRequest().

**Comment by eernstg** [comment] 2019-05-21 10:39
Also note that `void f(...) async {...}` is a rarely used form meaning "don't wait for this".

An `async` function _always_ returns a future, and that future should generally be awaited somewhere, but the return type `void` is used to indicate that the return value should be ignored. So you should only use such a void-async method signature when the associated work is a fire-and-forget job, and in that case you'd also ignore any exceptions thrown during the execution of that job (so your intention here is clearly different). As a rule of thumb, async functions should be called from async functions.

**Comment by eernstg** [comment] 2019-05-21 10:58
I'll close this issue because the reported behavior is as intended.

**Closed by eernstg** 2019-05-21 10:58 UTC
Labels: closed-as-intended
