### ISSUE TITLE
Can't throw an exception with a given stack trace

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#35494] opened 2018-12-25 08:34 UTC
I have a class similar to `Completer`. It has a method similar to `completeError` which takes an exception and stack trace (typically one caught in a try/catch block in user code). There is a situation in which I want to be able to cause this exception to be rethrown at a later point synchronously (similar to how a Future that doesn't have an error handler passes the error to the zone's uncaught error handler).

However, there's no current way to rethrow the exception with a given StackTrace object.

Ideally you'd be able to do something like:

```dart
  throw error at stack;
```

**Comment by kevmoo** [comment] 2018-12-30 01:16
Duplicate of #30741

**Closed by kevmoo** 2018-12-30 01:16 UTC
