### ISSUE TITLE
Poor documentation for native extensions

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/sdk#26940] opened 2016-07-21 22:55 UTC
_From @kevmoo on July 30, 2015 22:34_

_From @austincummings on July 30, 2015 17:34_

The [documentation page for native extensions](https://www.dartlang.org/articles/native-extensions-for-standalone-dart-vm/) is severely lacking in detail. 

There is no mention of why library handler error's happen. There is also no mention of how to tie a C++ object to a Dart object. The example code is out of date with what's in the repo. There is basically no self troubleshooting when it comes to native extensions. 

These are extremely important if you want people to develop for the language. Right now Dart is lacking in database libraries and those are only possible with native extensions.

_Copied from original issue: dart-lang/sdk#23922_

_Copied from original issue: dart-lang/www.dartlang.org#1423_

**Comment by kwalrath** [comment] 2016-07-21 22:55
This should probably be documented in the SDK repo, not in www.dartlang.org.

**Comment by srawlins** [comment] 2018-06-21 13:34
Duplicate of https://github.com/dart-lang/sdk/issues/23289.

**Closed by srawlins** 2018-06-21 13:34 UTC
Labels: area-documentation, area-vm
