### ISSUE TITLE
appeard in android studio

### ISSUE THREAD

**Issue by GitHubStuff** [dart-lang/sdk#38411] opened 2019-09-16 15:21 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1200, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#10     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#11     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5226:12)
#12     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3814:14)
#13     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#14     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#15     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#16     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#17     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#18     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#19     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#20     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#21     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#22     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#23     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#24     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#25     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#26     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#27     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#28     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#29     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#43     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#45     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#46     new Future.sync (dart:async/future.dart:224:31)
#47     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#53     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#54     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#55     main (file:/...
```

For additional log information, please append the contents of
file:///private/var/folders/kq/qd9zc3ld16q0kx6l8l666qt40000gn/T/report.txt.

**Comment by keertip** [comment] 2019-09-16 16:16
Duplicate of #38351

**Closed by keertip** 2019-09-16 16:16 UTC
Labels: analyzer-crash-report, area-analyzer
