### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#36330] opened 2019-03-25 07:58 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-183.5912.21`
- `2.2.0`
- `IU-183.5912.21, JRE 1.8.0_152-release-1343-b28x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 2560x1440, 1200x1920`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, error: Analysis failed: /Users/rayk/critprojects/repo/authN/lib/authN.dart context: exception_20190325_181400_271
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:642:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:360:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:327:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:219:14)
#6      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:114:10)
#7      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1438:63)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#19     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#25     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#26     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#27     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#28     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#29     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#30     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/k3/rpf30xp576gd3b7wdpvvyg2r0000gn/T/report4.txt.

**Comment by kevmoo** [comment] 2019-05-11 00:00
Duplicate of https://github.com/dart-lang/sdk/issues/35790

**Closed by kevmoo** 2019-05-11 00:00 UTC
Labels: area-analyzer
