### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by behinenet** [dart-lang/sdk#38514] opened 2019-09-21 23:08 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6262.58`
- `2.5.0`
- `IU-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0, server version 1.27.2, error: Analysis failed: /Users/pgh/Projects/baio project/baio_libs/baio_stringer/lib/src/builders/code_builders/template_code_builder.dart context: exception_20190922_023718_735
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      VariableMember.type (package:analyzer/src/dart/element/member.dart:1053:61)
#2      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:626:40)
#3      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:134:27)
#4      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#5      LinterContextImpl._hasConstantVerifierError (package:analyzer/src/lint/linter.dart:322:10)
#6      LinterContextImpl.canBeConst (package:analyzer/src/lint/linter.dart:290:15)
#7      BestPracticesVerifier._checkForLiteralConstructorUse (package:analyzer/src/generated/resolver.dart:820:24)
#8      BestPracticesVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:345:5)
#9      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#10     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#11     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1164:10)
#12     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#14     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#15     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#16     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#17     IfStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5773:21)
#18     RecursiveAstVisitor.visitIfStatement (package:analyzer/dart/ast/visitor.dart:971:10)
#19     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5768:49)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#21     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#22     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#23     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#24     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#25     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#28     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#29     BestPracticesVerifier.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:367:13)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#33     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#34     BestPracticesVerifier.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:247:13)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#38     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#40     LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:276:10)
#41     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:195:11)
#42     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#43     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:194:15)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#45     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:180:35)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#49     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#50     PerformanceLog.run (packag...
```

For additional log information, please append the contents of
file:///private/var/folders/y0/qvvflhj13gz_x0xk8xg7dkkw0000gn/T/report.txt.

**Comment by parlough** [comment] 2020-05-20 05:42
Duplicate of https://github.com/dart-lang/sdk/issues/37996

Therefore fixed by https://github.com/dart-lang/sdk/commit/c6b0ae1fdab360f08b7966797506dae6629551fd

**Closed** 2021-02-23 23:48 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
