### ISSUE TITLE
Tests expecting compile-time errors are broken in test.py

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#56660] opened 2024-09-05 20:35 UTC
3ec40e76619844190b640db82fd3af311ba052bd broke local testing with `test.py` when running tests which expect compile-time errors.

@ 093a0f84fae2fd437ed9b311725325f6d2adeaa1
```
$ tools/test.py -n vm-linux-debug-x64 corelib/iterable_element_at_test
No build targets found.
Test configuration:
    vm-linux-debug-x64(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: linux)
Suites tested: corelib
[00:01 | 100% | +    2 | -    0]

=== All 2 tests passed ===
```

@ 3ec40e76619844190b640db82fd3af311ba052bd
```
$ tools/test.py -n vm-linux-debug-x64 corelib/iterable_element_at_test
No build targets found.
Test configuration:
    vm-linux-debug-x64(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: linux)
Suites tested: corelib
[00:01 |  50% | +    1 | -    0]

FAILED: dartk-vm debug_x64 corelib/iterable_element_at_test/static
Expected: Pass
Actual: CompileTimeError
Missing expected compile error.

--- Command "vm" (took 975ms):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --sound-null-safety -Dtest_runner.configuration=vm-linux-debug-x64 --ignore-unrecognized-flags --packages=/.../dart/sdk/.dart_tool/package_config.json /.../dart/sdk/out/DebugX64/generated_tests/corelib/iterable_element_at_test_static.dart

exit code:
254

stderr:
out/DebugX64/generated_tests/corelib/iterable_element_at_test_static.dart:18:19: Error: The argument type 'String' can't be assigned to the parameter type 'int'.
  list1.elementAt("2"); //# static: compile-time error
                  ^
out/DebugX64/generated_tests/corelib/iterable_element_at_test_static.dart:25:19: Error: The argument type 'String' can't be assigned to the parameter type 'int'.
  list2.elementAt("2"); //# static: compile-time error
                  ^
out/DebugX64/generated_tests/corelib/iterable_element_at_test_static.dart:35:18: Error: The argument type 'String' can't be assigned to the parameter type 'int'.
  set2.elementAt("2"); //# static: compile-time error
                 ^

--- Re-run this test:
python3 tools/test.py -n vm-linux-debug-x64 corelib/iterable_element_at_test/static
[00:01 | 100% | +    1 | -    1]

=== 1 test passed, 1 failed ===
```

@mkustermann Could you take a look?

/cc @athomas

**Comment by mkustermann** [comment] 2024-09-06 07:50
Thanks, @alexmarkov !

There was one more thing to align between `tools/test.py` and `tools/test.dart`.
=> [cl/383662](https://dart-review.googlesource.com/c/sdk/+/383662)

**Comment by scheglov** [comment] 2024-09-06 16:37
I still have failures that we were able to suppress previously.

I have a file `sdk/tests/language/language_analyzer.status` with the content
```
# Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

# Sections in this file should contain "$compiler == dart2analyzer".

[ $compiler == dart2analyzer ]
async/derive_future_type_test: Fail
augmentation_libraries/class_augmentation_test: Fail
covariant/override_covariant_interface_test: Fail
least_upper_bound/least_upper_bound_greatest_closure_2_test: Crash
macros/nesting/macro_impl_uses_macro1_test: Fail
macros/nesting/macro_impl_uses_macro2_test: Fail
main/no_main_test/01: Fail
nnbd/static_errors/local_function_inference_test: Fail
test_runner/imported_augmentation_library_failure_test: Fail
wildcard_variables/*: Skip
```

Now, what I run test over `language/async/derive_future_type_test`, it fails

```console
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (master)$ ./tools/test.py --mode release --arch arm64 --compiler dart2analyzer --progress color --report --tasks=4 language/async/derive_future_type_test
No build targets found.
Test configuration:
    custom-configuration-1(architecture: arm64, compiler: dart2analyzer, mode: release, runtime: none, system: mac)
Suites tested: language
Total: 1 tests
 * 0 tests will be skipped (0 skipped by design)
 * 0 tests are expected to be flaky but not crash
 * 0 tests are expected to flaky crash
 * 0 tests are expected to pass
 * 0 tests are expected to fail that we won't fix
 * 1 tests are expected to fail that we should fix
 * 0 tests are expected to crash that we should fix
 * 0 tests are allowed to timeout
 * 0 could not be categorized or are in multiple categories


FAILED: dart2analyzer-none release_arm64 language/async/derive_future_type_test
Expected: Pass
Actual: CompileTimeError

--- Command "dart2analyzer" (took 09.000509s):
DART_CONFIGURATION=ReleaseARM64 sdk/bin/dart --packages=.dart_tool/package_config.json pkg/analyzer_cli/bin/analyzer.dart --use-analysis-driver-memory-byte-store --dart-sdk=/Users/scheglov/Source/Dart/sdk.git/sdk/sdk -Dtest_runner.configuration=custom-configuration-1 --ignore-unrecognized-flags --packages=/Users/scheglov/Source/Dart/sdk.git/sdk/.dart_tool/package_config.json --format=json /Users/scheglov/Source/Dart/sdk.git/sdk/tests/language/async/derive_future_type_test.dart

unexpected analysis errors in derive_future_type_test.dart:
- Line 301, column 32: COMPILE_TIME_ERROR.TYPE_ARGUMENT_NOT_MATCHING_BOUNDS
  'Exactly<Never?>' doesn't conform to the bound 'Exactly<X>' of the type parameter 'R'.

- Line 306, column 32: COMPILE_TIME_ERROR.TYPE_ARGUMENT_NOT_MATCHING_BOUNDS
  'Exactly<Object?>' doesn't conform to the bound 'Exactly<Object>' of the type parameter 'R'.

- Line 317, column 32: COMPILE_TIME_ERROR.TYPE_ARGUMENT_NOT_MATCHING_BOUNDS
  'Exactly<Symbol?>' doesn't conform to the bound 'Exactly<X>' of the type parameter 'R'.

- Line 421, column 34: COMPILE_TIME_ERROR.TYPE_ARGUMENT_NOT_MATCHING_BOUNDS
  'Exactly<Never?>' doesn't conform to the bound 'Exactly<X>' of the type parameter 'R'.

- Line 426, column 34: COMPILE_TIME_ERROR.TYPE_ARGUMENT_NOT_MATCHING_BOUNDS
  'Exactly<Object?>' doesn't conform to the bound 'Exactly<Object>' of the type parameter 'R'.

- Line 437, column 34: COMPILE_TIME_ERROR.TYPE_ARGUMENT_NOT_MATCHING_BOUNDS
  'Exactly<Symbol?>' doesn't conform to the bound 'Exactly<X>' of the type parameter 'R'.

--- Re-run this test:
python3 tools/test.py -m release -c dart2analyzer -a arm64 language/async/derive_future_type_test
[00:09 | 100% | +    0 | -    1]

=== 0 tests passed, 1 failed ===
```

**Comment by mkustermann** [comment] 2024-09-09 07:26
> I have a file sdk/tests/language/language_analyzer.status with the content

We have moved away from the status files for "approving" failures a long time ago.
Nowadays the purpose of status files is being able to: skip tests, mark them as slow and influence how crashing tests are handled (e.g. no collection of crash dumps).

Our test infrastructure on CI uses `tools/test.dart`. If we have any non-approved failure on CI, it will show reproduction instructions that say to use `tools/test.py ... `. So these reproduction instructions should actually work and reproduce the failure on CI. If it took `foo: Fail` in the status file into account then we'd be in a situation where the bots say a test fails, tell how to reproduce it and then it won't reproduce locally. This is super confusing. It also would lead us to maintain a copy of approvals database by manually editing status files, they will get out-of-sync, etc.

There's mainly one gap between the old tooling and the new: We don't run all possible configurations on CI and therefore don't have test results / approvals for all configurations. But our former infra team has AFAIK added a flag to `tools/test.dart` where one can select the configuration to run and another one to get results/approvals from (IIRC `-n` and `-N`)

**Comment by mkustermann** [comment] 2024-09-09 07:27
@athomas Do you agree with this? Then we can close this issue.

**Comment by athomas** [comment] 2024-09-09 08:06
> @athomas Do you agree with this? Then we can close this issue.

We need to get there eventually, the only reason why kept the old logic because it wasn't perceived as a burden. This was a mistake given that the code had drifted over time and consequently produced confusing results. I get this is an inconvenience for everyone still using status files for failure tracking locally. The workaround is using `Skip` instead.

**Comment by scheglov** [comment] 2024-09-09 16:35
Using `Skip` does not let me know that I fixed a group of tests with my current, not yet committed changes. 

When I work on a new language feature, usually there are many failing `co19` tests initially.
So, I update my local copy of `sdk/tests/co19/co19-co19.status`, and **don't commit** it.
It stays just on my machine.

And my normal working scenario:
1. Take one `Fail` test from `co19` in my local copy of `co19-co19.status`, comment it out, so now it is not expected to fail.
2. Run the test, it fails.
3. Analyze why, fix.
4. Run all `co19` tests again.
5. Sometimes see that more tests in the same group started to "fail" by passing instead of expected `Fail`. Rejoice. Comment them out too.
6. Run all the tests again, send to Gerrit.
7. After landing the CL remove commented out status lines.

**Comment by mkustermann** [comment] 2024-09-10 07:52
> And my normal working scenario:

To be honest, that seems very complicated.

When co19 gets rolled, all new failures get approved and issues are filed. Then one can just take this list of failures, and start fixing them, fix one, run `tools/test.dart` which should (?) show tests that are approved to fail but are now passing. One can compare that list to the original failure list and see what remaining tests need fixing.

**Comment by mkustermann** [comment] 2024-09-10 08:06
We really shouldn't have two separate ways to determine what the outcome of a test is and whether that outcome is expected (e.g. pass or approved failure) or not. So I'm going to close this issue.

@scheglov if the workflow with `tools/test.dart` is lacking some things for your use case, I can encourage to just add those things to `tools/test.dart`

**Closed by mkustermann** 2024-09-10 08:06 UTC
Labels: area-infrastructure

**Comment by scheglov** [comment] 2024-09-10 20:25
How do I run analyzer tests on my Mac, locally?
I tried, but I get an error.
```console
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (master)$ dart tools/test.dart -n analyzer-mac co19/
error: The named configuration analyzer-mac isn't tested on any builder
```

Even though there is such configuration
```console
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (master)$ dart tools/test.dart --list-configurations
analyzer-asserts-linux
analyzer-asserts-mac
analyzer-asserts-win
analyzer-linux
analyzer-mac
```

I tried also with `-N`, but still get an error.
```console
scheglov@scheglov-macbookpro4:~/Source/Dart/sdk.git/sdk (master)$ dart tools/test.dart -n analyzer-mac -N analyzer-linux
error: The named configuration analyzer-mac isn't tested on any builder
```

**Comment by mkustermann** [comment] 2024-09-11 07:44
> How do I run analyzer tests on my Mac, locally?

Reading through the code it seems what you need to run is this:
```
% dart tools/test.dart -n analyzer-linux -N analyzer-mac

which is the same as

% dart tools/test.dart --named-configuration analyzer-linux --local-configuration analyzer-mac
```

This will take approval status from the `analyzer-linux` (which we run on the bots) but runs `analyzer-mac` locally.

You can use any configuration with `-n` that's run on the bots, which currently seems to be
```
Builder analyzer-linux-release runs configurations
 - analyzer-unittest-asserts-release-linux
 - analyzer-asserts-linux
 - analyzer-asserts-linux

Builder analyzer-mac-release runs configurations
 - analyzer-unittest-asserts-release-mac
 - analyzer-asserts-mac
 - analyzer-asserts-mac

Builder analyzer-win-release runs configurations
 - analyzer-unittest-asserts-release-win
 - analyzer-unittest-asserts-release-win
 - analyzer-asserts-win
 - analyzer-asserts-win
 - analyzer-unittest-asserts-release-win
 - analyzer-unittest-asserts-release-win

Builder analyzer-analysis-server-linux runs configurations
 - analyzer-linux
 - analyzer-linux
```

This list doesn't have `analyzer-mac` which is why you got `error: The named configuration analyzer-mac isn't tested on any builder`

**Comment by athomas** [comment] 2024-09-11 15:11
I found some issues:
a) configuration overrides don't work with exactly 1 override:
https://dart-review.googlesource.com/c/sdk/+/384744

b) `analyzer-mac` and `analyzer-asserts-mac` are x64 configurations and should probably be arm64 instead (because that's most convenient for local development).

Draft CL: https://dart-review.googlesource.com/c/sdk/+/384761

c) `--detect-host` doesn't work with `test.dart`'s configuration overrides.

With a) and b) fixed, this works:
`tools/sdks/dart-sdk/bin/dart tools/test.dart -Nanalyzer-mac -nanalyzer-asserts-mac -- language`

**Comment by scheglov** [comment] 2024-09-11 19:32
It does not finish running.

```console
$ tools/sdks/dart-sdk/bin/dart tools/test.dart -Nanalyzer-mac -nanalyzer-asserts-mac -- language

<cut>

2024-09-11 12:24:47.922176 Warning: /Users/scheglov/Source/Dart/sdk.git/sdk/tests/language/constructor/name_test.dart is a legacy multi-test file.
[00:33 |  26% | +    0 | - 2131]Error on batch runner input stream stdin
  Previous test's status: null
  Error: SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1252:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:2010:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2487:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2222:28)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2174:11)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#9      _StreamController._add (dart:async/stream_controller.dart:658:7)
#10     _StreamController.add (dart:async/stream_controller.dart:606:5)
#11     _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#12     _IOSinkImpl.write (dart:io/io_sink.dart:287:5)
#13     _Socket.write (dart:io-patch/socket_patch.dart:2320:36)
#14     _StdSink._write (dart:io/stdio.dart:401:13)
#15     _StdSink.write (dart:io/stdio.dart:416:33)
#16     BatchRunnerProcess.doStartTest (package:test_runner/src/process_queue.dart:1074:21)
#17     BatchRunnerProcess.runCommand (package:test_runner/src/process_queue.dart:1036:7)
#18     CommandExecutorImpl._runCommand (package:test_runner/src/process_queue.dart:569:12)
#19     CommandExecutorImpl.runCommand.runCommand (package:test_runner/src/process_queue.dart:544:14)
#20     CommandExecutorImpl.runCommand (package:test_runner/src/process_queue.dart:555:12)
#21     CommandQueue._tryRunNextCommand (package:test_runner/src/process_queue.dart:430:16)
#22     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#25     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Unhandled exception:
Exception: Command exited 255: python3 tools/test.py '--named-configuration=analyzer-mac' '--output-directory=/var/folders/3q/vlsbwmsd32g84nyzbg2mpgb4003ky_/T/test.dart.JkwWCW' --clean-exit --silent-failures --write-results --write-logs language
#0      runProcessInheritStdio (package:test_runner/test_runner.dart:77:5)
<asynchronous suspension>
#1      runTests (package:test_runner/test_runner.dart:484:5)
<asynchronous suspension>
```

**Comment by athomas** [comment] 2024-09-11 20:12
> It does not finish running.

That's probably because you're missing the dartanalyzer snapshot, so the batch runner can't start. That isn't included in the SDK anymore so it needs a separate build target. Yeah, I know, the error message is really unhelpful here...

```
tools/build.py -mrelease create_sdk utils/dartanalyzer
```

**Comment by scheglov** [comment] 2024-09-12 01:02
Thank you.
Indeed, now tests finish.
