### ISSUE TITLE
Base class type inference is wrong

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/sdk#30079] opened 2017-07-05 19:12 UTC
See this reduced test case:

Simple: https://dartpad.dartlang.org/6ee6ea9b7f00bc1b6c7115a891ba88b8

How it was discovered in OverReact components: https://dartpad.dartlang.org/e5e40dd06c6beee77077773bc5880cc6

This issue was found in [OverReact](https://github.com/Workiva/over_react)

I would expect `classInstance` to have a type of `AbstractComponent`

Only an issue is `TypedBase` implement `Interface` or if the generic params are left in.

This is in strong mode.

**Comment by bencampbell-wf** [comment] 2017-07-05 19:39
It appears that simply implementing any class in the example leads to the same analyzer error. They do not need to overlapping symbols or implementations.

I have updated the supplied example to illustrate this https://dartpad.dartlang.org/1c8aff38857a3cb5aa12f142d7b6ce67 .

**Comment by robbecker-wf** [comment] 2017-07-05 20:39
@leafpetersen @kevmoo Is this expected behaviour? This seems to be an analyzer bug.

**Comment by kevmoo** [comment] 2017-07-05 20:51
@bwilkerson @devoncarew ?

**Comment by bwilkerson** [comment] 2017-07-05 20:59
The problem is the definition of LUB, which comes into play with the ternary "?:" operator. I don't know whether inference can / will do better in the future, but for now the only work-around I know of is to explicitly give `classInstance` a type.

**Comment by jacehensley-wf** [comment] 2017-07-05 21:04
@bwilkerson Why would adding an `implements` to `TypedBase` break this? without the `implements` it works correctly.

**Comment by robbecker-wf** [comment] 2017-07-05 21:10
Also, if we have to live with this, can I request a lint rule to remind people to specify a type instead of var when assigning using a ternary?

**Comment by aaronlademann-wf** [comment] 2017-07-05 21:16
Also, seems like a bug - if for no other reason - its not consistent.  

If you remove the generic parameters from [the OverReact example linked above](https://dartpad.dartlang.org/e5e40dd06c6beee77077773bc5880cc6) - the type inference is suddenly correct: https://dartpad.dartlang.org/36c92bfa01f3903606b7aa4328b2dfcd

For the sake of posterity:

__Analyzer Error:__

```dart
main() {  
  // Analyzer thinks this is `Object`, it should be `AbstractComponent`.
  var classInstance = (someCheck() ? new ComponentA() : new ComponentB());

  classInstance.baseMethod();
}

bool someCheck() {
  return false;
}

class AProps {}
class AState {}

class BProps {}
class BState {}

class ComponentA extends AbstractComponent<AProps, AState> {} // DropdownMenuComponent

class ComponentB extends AbstractComponent<BProps, BState> {} // PopoverMenuComponent

class AbstractComponent<T, S> extends HelperTypedStateful<T, S> {} // AbstractDropdownMenuComponent

class HelperTypedStateful<T, S> extends TypedStatefulBase<T, S> with Mixin {} // transformer_helper.UiStatefulComponent

class HelperTypedBased<T> extends TypedBase<T> with Mixin {} // transformer_helper.UiComponent

class TypedStatefulBase<T, S> extends TypedBase<T> {} // component_base.UiStatefulComponent

class TypedBase<T> extends Base implements Interface {} // component_base.UiComponent

class Base { // react.Component
  baseMethod() {}
}

class Interface {} // Disposable

class Mixin {} // GeneratedClass
```

---

__Analyzer Clean:__

```dart
main() {  
  // Correctly inferred as `AbstractComponent`
  var classInstance = (someCheck() ? new ComponentA() : new ComponentB());
  
  classInstance.baseMethod();
}

bool someCheck() {
  return false;
}

class ComponentA extends AbstractComponent {} // DropdownMenuComponent

class ComponentB extends AbstractComponent {} // PopoverMenuComponent

class AbstractComponent extends UiStatefulComponentTransformerHelper {} // AbstractDropdownMenuComponent

class UiStatefulComponentTransformerHelper extends UiStatefulComponent with GeneratedClass {} // transformer_helper.UiStatefulComponent

class UiComponentTransformerHelper extends UiComponent with GeneratedClass {} // transformer_helper.UiComponent

class UiStatefulComponent extends UiComponent {} // component_base.UiStatefulComponent

class UiComponent extends Component implements DisposableManagerV3 {} // component_base.UiComponent

class Component { // react.Component
  baseMethod() {}
}

class DisposableManagerV3 {}

class GeneratedClass {}
```

**Comment by jacehensley-wf** [comment] 2017-07-05 21:36
@bwilkerson Is this related to https://github.com/dart-lang/sdk/issues/27525?

**Comment by jmesserly** [comment] 2017-07-06 02:30
yes this is #27525 and #25821, LUB does not work as expected in Dart for many types, but especially generic types.

**Comment by jacehensley-wf** [comment] 2017-07-06 03:50
Okay, I'm guessing those improvements are not slotted for the near future? Do they have a rough ETA or a hopeful SDK version?

**Comment by jmesserly** [comment] 2017-07-06 20:02
ah, I'm not sure. @leafpetersen might know the status

**Comment by leafpetersen** [comment] 2017-07-10 22:41
As others have said, least upper bound is a disaster in Dart, and it's really hard to fix without substantially changing the language.  The smaller reproduction example above is one of the classic examples: you have a hierarchy that looks like:

```
A -> Sub1 -> Base, Element -> Object
B -> Sub2 -> Base, Element -> Object
```

There simply is no least upper bound for this hierarchy, period: neither `Base` nor `Element` is least.  `Object` is very much not least, but at least it is unique, and that's what the Dart LUB definition chooses.

The more complex examples above fall down in other corners of the LUB definition around generics, but it's a similar situation, with the addition that you run into decidability issues (if you try to compute an upper bound recursively, there are examples which loop around to the original query, or worse to an infinitely expanding series of queries).

I would still like to improve on this, but it is unlikely to happen soon.

**Comment by leafpetersen** [comment] 2017-07-10 22:44
> Also, if we have to live with this, can I request a lint rule to remind people to specify a type instead of var when assigning using a ternary?

I would be very happy to see this.  I would suggest including things like `a ?? b` and `a ??= b` in there as well, since I believe both of those (or maybe just the former) also have the same problem.  Could you maybe file a separate issue for this?

**Comment by leafpetersen** [comment] 2017-07-10 22:45
I'm going to close this, since issues with LUB are well tracked elsewhere.  Feel free to reopen if you feel that there is something particular to track here.

**Closed by leafpetersen** 2017-07-10 22:45 UTC
Labels: area-analyzer

**Comment by jacehensley-wf** [comment] 2017-07-10 22:47
Thanks for the responses everybody 👍

**Comment by leafpetersen** [comment] 2017-07-10 22:48
Some related other issues:

https://github.com/dart-lang/sdk/issues/25368
https://github.com/dart-lang/sdk/issues/25821
https://github.com/dart-lang/sdk/issues/27525

**Comment by robbecker-wf** [comment] 2017-07-11 16:03
@leafpetersen I filed an issue for the requested lint rule here https://github.com/dart-lang/linter/issues/734
