### ISSUE TITLE
Failures on [ddc] Refactor _isSubtype...[dart2js] dart format --fix in serialization/

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#47266] opened 2021-09-21 22:15 UTC
There are new test failures on [[ddc] Refactor _isSubtype...[dart2js] dart format --fix in serialization/](https://github.com/dart-lang/sdk/compare/a666e5a2218c77dd3a06a7ae9cdb4d03e8c65348~...cf7d46097bf7cd2462f2387e2958c22f391fa49b).

The tests
```
pkg/vm/test/incremental_compiler_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
```

**Comment by a-siva** [comment] 2021-09-21 22:16
Here is a log of the failure https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8835535925485368977/+/u/test_results/new_test_failures__logs_

**Comment by a-siva** [comment] 2021-09-21 22:20
//cc @jensjoha could you tell us why the incremental_compiler_test is failing on unrelated changes ?

**Comment by alexmarkov** [comment] 2021-09-22 17:02
Looks similar to https://github.com/dart-lang/sdk/issues/46450.

**Comment by jensjoha** [comment] 2021-09-23 10:37
I have no real insight here --- worth noticing, though, is that it's in `_computeMainId` on line `return isolates.first['id'];` that it fails.

Maybe `_computeMainId` should be updated to (upon failure) wait a little and try again.
It seems to me that the interaction goes something like "launch vm, connect via observatory, execute `getVM`, and that this then doesn't return any isolates, so probably the VM isn't ready yet?

**Comment by whesse** [comment] 2021-09-24 15:02
Duplicate of #46450.  Another problem, besides the test flaking, is that this flakiness is not detected on the CI, because on each CI run, the test either always fails or always passes all the deflaking runs.  I can mark this test as flaky manually, and have been looking at making a tool to do this.  Closing as duplicate.

**Closed** 2022-01-19 16:43 UTC
Labels: area-vm, gardening
