### ISSUE TITLE
ternary expression doesn't handle type info properly

### ISSUE THREAD

**Issue by SteveAlexander** [dart-lang/sdk#44767] opened 2021-01-25 11:36 UTC
This code shows the problem I'm seeing:

```dart
abstract class A {
  A();
  factory A.createTernary(bool x) {
    return x ? AB1() : AB2();
  }
  factory A.createIf(bool x) {
    if (x) return AB1();
    else return AB2();
  }
}

mixin B {}
class AB1 extends A with B {}
class AB2 extends A with B {}
```

The `createTernary` analyzes with an error, whereas the equivalent `createIf` is fine.

![image](https://user-images.githubusercontent.com/4321921/105700917-d3577280-5f09-11eb-92f5-ae2ef06f7feb.png)

The analyzer error is:

```json
{
	"resource": "/Users/steve/code/enfold/afsoc-app/chubsync/lib/sync/filesystem_copy.dart",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "return_of_invalid_type",
	"severity": 8,
	"message": "A value of type 'Object' can't be returned from the constructor 'A.createTernary' because it has a return type of 'A'.",
	"source": "dart",
	"startLineNumber": 4,
	"startColumn": 12,
	"endLineNumber": 4,
	"endColumn": 29
}
```

I'm testing this on Flutter master, which at the time of writing has this version of Dart:

`Dart SDK version: 2.12.0-253.0.dev (dev) (Fri Jan 22 08:36:17 2021 -0800) on "macos_x64"`

**Comment by mraleph** [comment] 2021-01-25 11:59
@eernstg is this working as intended with respect to least upper bound algorithm? Is there an umbrella issue for improvements?

**Comment by SteveAlexander** [comment] 2021-01-25 12:21
I'll also mention, I think this code was working fine on the previous Beta, but when I updated, it started producing the error. 

(Obviously, not this actual code, but the more complex one in my app that has the same kind of shape.)

**Comment by eernstg** [comment] 2021-01-25 13:41
Thanks, @SteveAlexander! I believe this is a bug in the front end as well as in the analyzer.

The current rules about the least upper bound of two types in a library with null safety are [here](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#upper-bounds), and the [example](https://github.com/dart-lang/sdk/issues/44767#issue-793305436) matches the last case:

> ... as in Dart 1, with modifications for handling mixed null safe and legacy code ...

So we end up looking at [the old rule](https://github.com/dart-lang/language/blob/75d7d473c582931c7ccd6c01bc2fedbb0172a568/specification/dartLangSpec.tex#L19107) about the least upper bound of two interface types, both for a library with null safety and for a library without.

The superclass of `AB1` is the class denoted by `A with B`, and that is [specified](https://github.com/dart-lang/language/blob/75d7d473c582931c7ccd6c01bc2fedbb0172a568/specification/dartLangSpec.tex#L4966) to be a class with a fresh name for each occurrence of a mixin application. In particular, `A with B` and `A with B` denote two distinct classes unless it is the same piece of source code (it isn't enough that they are textually identical and that they occur in a binding environment where one `A` means the same thing as the other `A` and the same thing holds for the `B`s). Let's call those two classes `AB1mix` and `AB2mix`.

So when we consider the superinterface hierarchies at each depth we get `[{Object}, {A}, {AB1mix, AB2mix}, {AB1, AB2}]` (so at depth zero we have `Object`, at depth 1 we have `A`, and so on).

This means that the greatest depth with cardinality one is depth 1, and so the least upper bound is `A`. With that, the body of `A.createTernary` should be accepted: It is returning an expression with static type `A`, and that's allowed in a factory constructor of class `A`.

Nevertheless, a fresh `dart` from commit 341213becd8d4dd362e96607710c96a22b578ca6 emits the following compile-time error:

```
n018.dart:4:14: Error: A value of type 'Object' can't be returned from a function with return type 'A'.
 - 'Object' is from 'dart:core'.
 - 'A' is from 'n018.dart'.
    return x ? AB1() : AB2();
             ^
```

which implies that the computation must have skipped depth 1, or it must have considered the superclass of `AB1mix` and/or `AB2mix` to be some other class than `A`. We get the same response from the analyzer:

```
ERROR|COMPILE_TIME_ERROR|RETURN_OF_INVALID_TYPE|/usr/local/google/home/eernst/lang/dart/scratch/202101/n018.dart|4|12|17|A value of type 'Object' can't be returned from the constructor 'A.createTernary' because it has a return type of 'A'.
```

**Comment by eernstg** [comment] 2021-01-25 14:00
@mraleph wrote:
> Is there an umbrella issue for improvements?

I do not think so. We might want to create such an umbrella issue if and when we encounter a clear case where there is a proposal for an improvement. We have avoided updating [this particular rule](https://github.com/dart-lang/language/blob/75d7d473c582931c7ccd6c01bc2fedbb0172a568/specification/dartLangSpec.tex#L19107) because any changes are likely to create a substantial amount of churn and not so much of an improvement, so I'd suggest that we don't create an umbrella issue right now.

**Comment by eernstg** [comment] 2021-01-25 14:58
Note that the CFE has considered `LUB(AB1, AB2)` to be `Object` all the way back to the time where a `mixin` declaration was a syntax error (sdk-2.1.0-dev.0.0). In other words, we've "always" had this behavior in the CFE.

In contrast, the analyzer considered `LUB(AB1, AB2)` to be `Object` for only a short amount of time (from today and back to `sdk-2.12.0-133.0.dev`), and `sdk-2.12.0-96.0.dev` yields `A` as it should.

This means that it should _not_ be a breaking change to make the analyzer take the superclass of a mixin application into account again: It is not a breaking change to fix this issue in the analyzer.

It may be a somewhat more delicate decision whether it should be considered as a breaking change to fix the issue in the CFE. I've asked for some input about the breakage in https://github.com/dart-lang/sdk/issues/44769#issuecomment-766848348.

**Comment by eernstg** [comment] 2021-01-25 15:40
After two iterations we know that the error reported by the CFE and the analyzer in `A.createTernary` are correct, and hence it is already working as intended. So I'll close this issue.

**Closed by eernstg** 2021-01-25 15:40 UTC
Labels: area-meta, closed-as-intended

**Comment by SteveAlexander** [comment] 2021-01-25 16:12
@eernstg Thanks for the detailed explanation. The new information for me is understanding that a synthetic base class is created when a mixin is used.

I can rewrite the code in this way, with no analyzer errors:

```dart
abstract class A {
  A();
  factory A.createTernary(bool x) {
    return x ? AB1() : AB2();
  }
  factory A.createIf(bool x) {
    if (x) return AB1();
    else return AB2();
  }
}

mixin B {}
abstract class X extends A with B {}
class AB1 extends X {}
class AB2 extends X {}

```
