### ISSUE TITLE
Pattern type inference error

### ISSUE THREAD

**Issue by dnys1** [dart-lang/sdk#52373] opened 2023-05-12 16:13 UTC
I'm facing an error with inference of pattern types when using sealed classes.

Here is the full reproduction: https://github.com/dnys1/sealed_repro

Given the following class hierarchy:

```
Legend:
  Open Class (o)
  Sealed Class (*)
  Final Class (x)
```

```mermaid
classDiagram
    class BaseException["BaseException o"]
    class AuthException["AuthException *"]
    class UnknownException["UnknownException o"]
    class AuthServiceException["AuthServiceException o"]
    BaseException <|-- AuthException
    AuthException <|-- UnknownException: implements
    AuthException <|-- AuthServiceException: extends

    class AuthResult["AuthResult *"]
    class AuthSuccessResult["AuthSuccessResult x"]
    class AuthPartialSuccessResult["AuthPartialSuccessResult x"] {
        +step1Exception: Step1Exception
        +step2Exception: Step2Exception
    }
    class AuthFailureResult["AuthFailureResult x"] {
        +exception: AuthException
    }
    class Step1Exception["Step1Exception x"]
    class Step2Exception["Step2Exception x"]
    AuthResult <|-- AuthSuccessResult
    AuthResult <|-- AuthPartialSuccessResult
    AuthResult <|-- AuthFailureResult
    UnknownException <|-- Step1Exception: extends
    AuthServiceException <|-- Step2Exception: extends
```

In `base_exception.dart` we define an exception hiearchy for which all classes inherit `BaseException`. From this, we derive `AuthException` which is sealed and has discrete subtypes, namely `UnknownException` and `AuthServiceException`.

In `auth_result.dart`, we define the result of an Auth operation. The result takes one of three discrete states: a successful result (`AuthSuccessResult`); a partial success (`AuthPartialSuccessResult`) where either the first or second step of the operation failed with an `AuthException`; and a complete failure (`AuthFailureResult`).

---

Given a method which performs an Auth operation:

```dart
Future<AuthResult> performAuthOperation();
```

We expect the following to work:

## 1. Inference on exception type

```dart
final result = await performAuthOperation();
switch (result) {
case AuthSuccessResult _:
    print('Success');
case AuthPartialSuccessResult(step1Exception: final exception?) ||
        AuthPartialSuccessResult(step2Exception: final exception?) ||
        AuthFailureResult(:final exception):
    print('Partially failed: $exception');
// For exhaustiveness; should never happen.
case AuthPartialSuccessResult(step1Exception: null, step2Exception: null):
    print('Unknown error occurred');
}
```

In the second branch, `step1Exception`, `step2Exception`, and `exception` are all subclasses of `AuthException`, yet its type cannot be inferred. The Analyzer presents the error:

```
The variable 'exception' has a different type and/or finality in this branch of the logical-or pattern.
Try declaring the variable pattern with the same type and finality in both branches.dartinconsistent_pattern_variable_logical_or
```

<img width="1324" alt="inferred_type" src="https://github.com/dart-lang/sdk/assets/24740863/a86343d9-9322-4a75-9ad9-431e12691944">

## 2. Explicit exception type

```dart
final result = await performAuthOperation();
switch (result) {
  case AuthSuccessResult _:
    print('Success');
  case AuthPartialSuccessResult(step1Exception: final AuthException exception) ||
        AuthPartialSuccessResult(step2Exception: final AuthException exception) ||
        AuthFailureResult(:final AuthException exception):
    print('Partially failed: $exception');
  // For exhaustiveness; should never happen.
  case AuthPartialSuccessResult(step1Exception: null, step2Exception: null):
    print('Unknown error occurred');
}
```

By explicitly specifying the exception types as `AuthException`, the analyzer stops complaining.

<img width="684" alt="explicit_type_analysis" src="https://github.com/dart-lang/sdk/assets/24740863/212c0c22-2c1e-49d9-bf8b-17faea6fa036">

However, upon compilation, we get a similar error:

```
bin/sealed_repro.dart:28:71: Error: Variable pattern 'exception' doesn't have the same type or finality in all cases.
    case AuthPartialSuccessResult(step1Exception: final AuthException exception) ||
                                                                      ^^^^^^^^^
```

<img width="858" alt="explicit_type_compile" src="https://github.com/dart-lang/sdk/assets/24740863/bde00936-fbab-459e-9e03-6f06141b8e84">

**Comment by dnys1** [comment] 2023-05-12 16:30
Number 1 is reproducible on Dart `3.0.0` and `3.1.0-94.0.dev`.

Number 2 is only reproducible on Dart `3.0.0`. On `3.1.0-94.0.dev`, it compiles fine.

**Comment by stereotype441** [comment] 2023-05-12 19:00
CC @chloestefantsova

**Comment by chloestefantsova** [comment] 2023-05-23 10:05
Here are shorter repros.

**Case 1 Reproduction**

```dart
class A {}
class B extends A {}
class C extends A {
  E1 get foo => new E1();
}
class D extends A {
  E2? get bar => new E2();
  E3? get baz => new E3();
}

class E {}
class E1 extends E {}
class E2 extends E1 {}
class E3 extends E1 {}

test(A x) {
  switch (x) {
    case B _:
      return 1;
    case D(bar: final foo?) ||
            D(baz: final foo?) ||
            C(:final foo):
      return 2;
    case D(bar: null, baz: null):
      return 3;
  }
}
```

**Case 2 Reproduction**

```dart
class A {}
class B extends A {}
class C extends A {
  E1 get foo => new E1();
}
class D extends A {
  E2? get bar => new E2();
  E3? get baz => new E3();
}

class E {}
class E1 extends E {}
class E2 extends E1 {}
class E3 extends E1 {}

test(A x) {
  switch (x) {
    case B _:
      return 1;
    case D(bar: final E1 foo) ||
            D(baz: final E1 foo) ||
            C(:final E1 foo):
      return 2;
    case D(bar: null, baz: null):
      return 3;
  }
}
```

Currently both the CFE and the Analyzer report the mismatching type or finality on the first one and allow the second one. @stereotype441, since the behavior of the tools is similar, could this issue be a part of the shared analysis?

**Comment by stereotype441** [comment] 2023-05-23 18:28
@chloestefantsova thanks for the shorter repros!

In the main development branch, both the analyzer and CFE report an error for case 1 and no error for case 2. This is correct behaviour, because all the declarations of `foo` are required to have the same type, whether the type is inferred or explicit; in case 1, the inferred types are different (`E2`, `E3`, and `E1`), so it's correct to report an error.

In the stable branch, the analyzer behaviour is correct, however the CFE reports an error for both case 1 and case 2. So it looks like the correct behaviour has been implemented in the CFE, but it needs to be cherry-picked to stable.

Bisecting, I found that the correct behaviour was implemented in b9b1fdff76d21012dfe9dad213f3a6aed6adfb61. I will submit a cherry-pick request.

**Comment by stereotype441** [comment] 2023-05-23 18:58
Cherry-pick request is here: https://github.com/dart-lang/sdk/issues/52488

**Comment by chloestefantsova** [comment] 2023-05-24 08:19
> Cherry-pick request is here: #52488

Thank you for finding the root of it, @stereotype441! I've +1'd the cherry pick CL.

**Comment by stereotype441** [comment] 2023-05-24 20:38
As of 10b909a1563c0bbaeb4afab5cf3c3c81a9afadf8, the cherry-pick has landed on the stable branch. Assuming no problems arise, it should go out as part of the next stable release, probably next Wednesday.

**Closed by stereotype441** 2023-05-24 20:38 UTC
Labels: area-front-end

**Comment by dnys1** [comment] 2023-05-24 20:52
Thank you @stereotype441 @chloestefantsova! 🙏
