### ISSUE TITLE
NoMethodFoundError only during 'webdev serve --release' but not in 'webdev serve' for JS Interop

### ISSUE THREAD

**Issue by edyu** [dart-lang/sdk#42194] opened 2020-06-05 05:10 UTC
I'll post the stacktrace later.
The lines in question are:
```
@JS()
external Crypto get crypto;
 
SubtleCrypto get subtle => crypto.subtle;
```
and the error is
```
Exceptions.dart:14 EXCEPTION: NoSuchMethodError: method not found: 'get$subtle' (J.getInterceptor$x(...).get$subtle is not a function)
    STACKTRACE:
    TypeError: J.getInterceptor$x(...).get$subtle is not a function
```
* Dart SDK Version (`dart --version`)
2.8.4

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows WSL2

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Everything except Safari

**Comment by edyu** [comment] 2020-06-05 05:11
<pre>
exceptions.dart:14 EXCEPTION: NoSuchMethodError: method not found: 'get$subtle' (J.getInterceptor$x(...).get$subtle is not a function)
STACKTRACE:
TypeError: J.getInterceptor$x(...).get$subtle is not a function
    at Object.get$subtle$x (http://localhost:9000/main.dart.js:3689:43)
    at ViewAppComponent0.build$0 (http://localhost:9000/main.dart.js:33506:52)
    at ViewAppComponent0.createAndProject$2 (http://localhost:9000/main.dart.js:26368:13)
    at ApplicationRef_bootstrap_closure.call$0 (http://localhost:9000/main.dart.js:25531:30)
    at ChangeDetectionHost_run_closure.call$0 (http://localhost:9000/main.dart.js:26124:33)
    at NgZone__run_closure.call$0 (http://localhost:9000/main.dart.js:27057:26)
    at StaticClosure._rootRun [as call$1$4] (http://localhost:9000/main.dart.js:4515:16)
    at NgZone._run$1$4 (http://localhost:9000/main.dart.js:26949:39)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:9000/main.dart.js:1439:14), <anonymous>:3:47)
    at _CustomZone.run$1$1 (http://localhost:9000/main.dart.js:18675:39)

call$0 @ exceptions.dart:14
call$0 @ ng_zone.dart:143
_rootRun @ zone.dart:1182
_run$1$4 @ zone.dart:763
eval @ VM10769:3
run$1$1 @ zone.dart:1075
run$1$1 @ future_impl.dart:40
bootstrap$1$1 @ application_ref.dart:68
main @ main.dart:4
(anonymous) @ js_helper.dart:3221
(anonymous) @ js_helper.dart:3221
dartProgram @ js_helper.dart:3221
(anonymous) @ js_helper.dart:3221
main.dart.js:3689 Uncaught TypeError: J.getInterceptor$x(...).get$subtle is not a function
    at Object.get$subtle$x (main.dart.js:3689)
    at ViewAppComponent0.build$0 (bindings.dart:26)
    at ViewAppComponent0.createAndProject$2 (component_view.dart:87)
    at ApplicationRef_bootstrap_closure.call$0 (host_view.dart:89)
    at ChangeDetectionHost_run_closure.call$0 (host.dart:185)
    at NgZone__run_closure.call$0 (ng_zone.dart:144)
    at StaticClosure._rootRun [as call$1$4] (zone.dart:1184)
    at NgZone._run$1$4 (zone.dart:764)
    at Object.eval (eval at Closure_forwardCallTo (js_helper.dart:2416), <anonymous>:3:47)
    at _CustomZone.run$1$1 (zone.dart:1076)
</pre>

**Comment by devoncarew** [comment] 2020-06-05 14:43
To clarify, JS interop is working for you for this case w/ DDC, but not for dart2js?

**Comment by sigmundch** [comment] 2020-06-05 16:08
Thanks @edyu , this relates to the issue you mentioned in https://github.com/dart-lang/sdk/issues/42144

Unfortunately there are small differences in how Dart2js and DDC behave with js-interop. One important difference is that if you have a type defined in dart:html, dart2js is not able to shadow that implementation with a different JS-interop implementation.

I provided an example workaround in #42144, hope that helps short term.

Long term we need to fix all these hidden APIs (others have run into similar issues with other APIs such as _USBDevice). We will be tracking progress towards that under #42200

I'm going to close this bug to mark it as a duplicate of that one.

**Closed by sigmundch** 2020-06-05 16:08 UTC
Labels: area-web, web-js-interop
