### ISSUE TITLE
Uri.resolve and Uri.resolveUri return incorrect results for ".." when the base URI is relative

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23809] opened 2015-07-09 00:06 UTC
Currently, `Uri.parse(".").resolve("../foo").path` returns `"foo"`. This is incorrect; `.` refers to the current path, so anything resolved relative to it should return itself. This means that the example above should return `"../foo"`.

**Comment by nex3** [comment] 2015-07-09 00:15
Upon further inspection, this goes beyond just `.`. *Any* single-component relative URI will ignore *any number* of leading `../` components in `resolve()` and `resolveUri()`

**Comment by lrhn** [comment] 2015-07-10 05:44
The problem is that the resolution algorithm in RFC 3986 is only specified to work for an absolut base URI, and for that case, you can't go "above the root", so initial ".." are discarded. 
We conflate URI (always absolute and with a scheme) and URI-reference (may be relative) into one class, so we can't easily make the distinction that you can only resolve a URI reference against a URI base
.
So, resolving againdst a relative URI is really unspecified, but I agree that it would be great if it did something useful instead of this.

**Comment by floitschG** [comment] 2015-07-10 11:47
Let's do that.

**Comment by lrhn** [comment] 2015-07-13 10:11
Another problem is that we don't path-normalize the URI from the beginning, and I think we should do that too.
The effect is that if you start with `scheme://auth/foo/..` and resolve `bar` against it, you get `scheme://auth/foo/bar`. The merge-path algorithm in RFC 3986 makes you drop the last segment of the original path before merging, and it doesn't check if that happens to be "..".

**Comment by floitschG** [comment] 2015-07-13 12:07
Agreed. This is something that could drip users. So let's fix it.

**Comment by sethladd** [comment] 2015-08-17 23:29
@floitschG should we do this for 1.12 ?

**Comment by lrhn** [comment] 2015-08-18 11:42
Thanks for asking :)
This was fixed in 848f6c978c7be89ede9db0 which is part of 1.12.

**Closed by lrhn** 2015-08-18 11:42 UTC
Labels: Accepted, Area-Library, Library-IO, Type-Defect

**Comment by sethladd** [comment] 2015-08-18 16:12
Cool, thanks for the update!
