### ISSUE TITLE
VM crash

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#44741] opened 2021-01-21 23:39 UTC
```
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x1246f0968
version=2.12.0-242.0.dev (dev) (Mon Jan 18 18:26:11 2021 -0800) on "macos_x64"
pid=54539, thread=6663, isolate_group=main(0x7f9f6f009000), isolate=main(0x7f9f6f011600)
isolate_instructions=1047992e0, vm_instructions=1047992e0
  pc 0x0000000104a8cfa7 fp 0x0000700009bf07f0 dart::StackTraceUtils::UnwindAwaiterChain(dart::Zone*, dart::GrowableObjectArray const&, dart::GrowableObjectArray const&, dart::CallerClosureFinder*, dart::ClosurePtr)+0x337
  pc 0x0000000104a8ccb0 fp 0x0000700009bf0870 dart::StackTraceUtils::UnwindAwaiterChain(dart::Zone*, dart::GrowableObjectArray const&, dart::GrowableObjectArray const&, dart::CallerClosureFinder*, dart::ClosurePtr)+0x40
  pc 0x0000000104a8d20f fp 0x0000700009bf0a80 dart::StackTraceUtils::CollectFramesLazy(dart::Thread*, dart::GrowableObjectArray const&, dart::GrowableObjectArray const&, int, std::__2::function<void (dart::StackFrame*)>*, bool*)+0x22f
  pc 0x00000001048bec73 fp 0x0000700009bf0ac0 dart::GetStackTraceForException()+0x93
  pc 0x000000010497efac fp 0x0000700009bf0b30 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))+0xac
  pc 0x0000000106d822f4 fp 0x0000700009bf0b78 Unknown symbol
  pc 0x000000010c5c7070 fp 0x0000700009bf0ba8 Unknown symbol
  pc 0x000000011794ab21 fp 0x0000700009bf0bf0 Unknown symbol
  pc 0x000000011794dd3d fp 0x0000700009bf0c48 Unknown symbol
  pc 0x0000000117ed4e9c fp 0x0000700009bf0cc8 Unknown symbol
  pc 0x000000011719235a fp 0x0000700009bf0d20 Unknown symbol
  pc 0x0000000117191c76 fp 0x0000700009bf0d60 Unknown symbol
  pc 0x000000011718a947 fp 0x0000700009bf0dc8 Unknown symbol
  pc 0x000000011718a030 fp 0x0000700009bf0e08 Unknown symbol
  pc 0x0000000117189b43 fp 0x0000700009bf0e58 Unknown symbol
  pc 0x0000000117efd88e fp 0x0000700009bf0fe8 Unknown symbol
  pc 0x000000011794b01e fp 0x0000700009bf1028 Unknown symbol
  pc 0x000000011795455b fp 0x0000700009bf1128 Unknown symbol
  pc 0x000000011793cd56 fp 0x0000700009bf1190 Unknown symbol
  pc 0x00000001179527b1 fp 0x0000700009bf1218 Unknown symbol
  pc 0x000000011794ba5e fp 0x0000700009bf1270 Unknown symbol
  pc 0x000000011794e531 fp 0x0000700009bf1300 Unknown symbol
  pc 0x0000000117954866 fp 0x0000700009bf1378 Unknown symbol
  pc 0x0000000120981d1e fp 0x0000700009bf13d8 Unknown symbol
  pc 0x000000011794b863 fp 0x0000700009bf1428 Unknown symbol
  pc 0x0000000117973086 fp 0x0000700009bf1460 Unknown symbol
  pc 0x000000011795455b fp 0x0000700009bf1560 Unknown symbol
  pc 0x0000000117946f75 fp 0x0000700009bf15b0 Unknown symbol
  pc 0x00000001179487df fp 0x0000700009bf1640 Unknown symbol
  pc 0x000000011794e86b fp 0x0000700009bf1690 Unknown symbol
  pc 0x0000000117949111 fp 0x0000700009bf1738 Unknown symbol
  pc 0x0000000117954cc6 fp 0x0000700009bf1770 Unknown symbol
  pc 0x0000000117ea5371 fp 0x0000700009bf17d0 Unknown symbol
  pc 0x000000011797c793 fp 0x0000700009bf17f8 Unknown symbol
  pc 0x0000000120991f70 fp 0x0000700009bf18e0 Unknown symbol
  pc 0x0000000117ea2c91 fp 0x0000700009bf1918 Unknown symbol
  pc 0x0000000117ee1356 fp 0x0000700009bf1948 Unknown symbol
  pc 0x000000011567d59b fp 0x0000700009bf19f8 Unknown symbol
  pc 0x000000011795de5c fp 0x0000700009bf1a30 Unknown symbol
  pc 0x0000000106d8265f fp 0x0000700009bf1aa8 Unknown symbol
  pc 0x0000000104922ecf fp 0x0000700009bf1b40 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x11f
  pc 0x0000000104922cf7 fp 0x0000700009bf1ba0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x147
  pc 0x00000001049254a4 fp 0x0000700009bf1bf0 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x1d4
  pc 0x0000000104950058 fp 0x0000700009bf1de0 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x4b8
  pc 0x000000010497d336 fp 0x0000700009bf1e50 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x126
  pc 0x000000010497da1a fp 0x0000700009bf1eb0 dart::MessageHandler::TaskCallback()+0x1da
  pc 0x0000000104a9b8ce fp 0x0000700009bf1f30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14e
  pc 0x0000000104a9bdcd fp 0x0000700009bf1f60 dart::ThreadPool::Worker::Main(unsigned long)+0x5d
  pc 0x0000000104a05a28 fp 0x0000700009bf1fb0 dart::OSThread::GetMaxStackSize()+0xb8
  pc 0x00007fff20384950 fp 0x0000700009bf1fd0 _pthread_start+0xe0
  pc 0x00007fff2038047b fp 0x0000700009bf1ff0 thread_start+0xf
-- End of DumpStackTrace
[exit     : sp(0) fp(0x700009bf0b78) pc(0)]
[dart     : sp(0x700009bf0b88) fp(0x700009bf0ba8) pc(0x10c5c7070) dart:core_StackTrace_get_current ]
[dart     : sp(0x700009bf0bb8) fp(0x700009bf0bf0) pc(0x11794ab21) *package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerCallback@91444339 ]
[dart     : sp(0x700009bf0c00) fp(0x700009bf0c48) pc(0x11794dd3d) *package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerCallback@91444339__registerCallback@91444339 ]
[dart     : sp(0x700009bf0c58) fp(0x700009bf0cc8) pc(0x117ed4e9c) *dart:async__Future@4048458_whenComplete ]
[dart     : sp(0x700009bf0cd8) fp(0x700009bf0d20) pc(0x11719235a) dart:io__StreamSinkImpl@14069316_addStream ]
[dart     : sp(0x700009bf0d30) fp(0x700009bf0d60) pc(0x117191c76) dart:io__Socket@14069316_addStream ]
[dart     : sp(0x700009bf0d70) fp(0x700009bf0dc8) pc(0x11718a947) dart:_http__HttpOutgoing@16463476_addStream ]
[dart     : sp(0x700009bf0dd8) fp(0x700009bf0e08) pc(0x11718a030) dart:_http__StreamSinkImpl@16463476_addStream_targetAddStream ]
[dart     : sp(0x700009bf0e18) fp(0x700009bf0e58) pc(0x117189b43) dart:_http__StreamSinkImpl@16463476_addStream ]
[dart     : sp(0x700009bf0e68) fp(0x700009bf0fe8) pc(0x117efd88e) *package:http/src/io_client.dart_IOClient_send__async_op ]
[dart     : sp(0x700009bf0ff8) fp(0x700009bf1028) pc(0x11794b01e) *package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerUnaryCallback@91444339_<anonymous closure>_<anonymous closure> ]
[dart     : sp(0x700009bf1038) fp(0x700009bf1128) pc(0x11795455b) *package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__run@91444339 ]
[dart     : sp(0x700009bf1138) fp(0x700009bf1190) pc(0x11793cd56) *package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerUnaryCallback@91444339_<anonymous closure> ]
[dart     : sp(0x700009bf11a0) fp(0x700009bf1218) pc(0x1179527b1) *dart:async_::__rootRunUnary@4048458 ]
[dart     : sp(0x700009bf1228) fp(0x700009bf1270) pc(0x11794ba5e) *dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
[dart     : sp(0x700009bf1280) fp(0x700009bf1300) pc(0x11794e531) *dart:async__FutureListener@4048458_handleValue ]
[dart     : sp(0x700009bf1310) fp(0x700009bf1378) pc(0x117954866) *dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
[dart     : sp(0x700009bf1388) fp(0x700009bf13d8) pc(0x120981d1e) *dart:async__Future@4048458__propagateToListeners@4048458 ]
[dart     : sp(0x700009bf13e8) fp(0x700009bf1428) pc(0x11794b863) *dart:async__Future@4048458__completeWithValue@4048458 ]
[dart     : sp(0x700009bf1438) fp(0x700009bf1460) pc(0x117973086) *dart:async__Future@4048458__asyncCompleteWithValue@4048458_<anonymous closure> ]
[dart     : sp(0x700009bf1470) fp(0x700009bf1560) pc(0x11795455b) *package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__run@91444339 ]
[dart     : sp(0x700009bf1570) fp(0x700009bf15b0) pc(0x117946f75) *package:stack_trace/src/stack_zone_specification.dart_StackZoneSpecification__registerCallback@91444339_<anonymous closure> ]
[dart     : sp(0x700009bf15c0) fp(0x700009bf1640) pc(0x1179487df) *dart:async_::__rootRun@4048458 ]
[dart     : sp(0x700009bf1650) fp(0x700009bf1690) pc(0x11794e86b) *dart:async_::__rootRun@4048458__rootRun@4048458 ]
[dart     : sp(0x700009bf16a0) fp(0x700009bf1738) pc(0x117949111) *dart:async__CustomZone@4048458_runGuarded ]
[dart     : sp(0x700009bf1748) fp(0x700009bf1770) pc(0x117954cc6) *dart:async__CustomZone@4048458_bindCallbackGuarded_<anonymous closure> ]
[dart     : sp(0x700009bf1780) fp(0x700009bf17d0) pc(0x117ea5371) *dart:async_::__startMicrotaskLoop@4048458 ]
[dart     : sp(0x700009bf17e0) fp(0x700009bf17f8) pc(0x11797c793) *dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
[dart     : sp(0x700009bf1808) fp(0x700009bf18e0) pc(0x120991f70) *dart:isolate__Timer@1026248__runTimers@1026248 ]
[dart     : sp(0x700009bf18f0) fp(0x700009bf1918) pc(0x117ea2c91) *dart:isolate__Timer@1026248__handleMessage@1026248 ]
[dart     : sp(0x700009bf1928) fp(0x700009bf1948) pc(0x117ee1356) *dart:isolate__Timer@1026248__handleMessage@1026248__handleMessage@1026248 ]
[dart     : sp(0x700009bf1958) fp(0x700009bf19f8) pc(0x11567d59b) *dart:core__Closure@0150898_dyn_call ]
[dart     : sp(0x700009bf1a08) fp(0x700009bf1a30) pc(0x11795de5c) *dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x700009bf1a40) fp(0x700009bf1aa8) pc(0x106d8265f)]
cd repo_manager && dart --enable-asserts bin/repo_manager.dart update-all --sdk-path ~/github/dart/sdk/ $1: line 1: 54539 Abort trap: 6           dart --enable-asserts bin/repo_manager.dart update-all --sdk-path ~/github/dart/sdk/ $1
```

**Comment by a-siva** [comment] 2021-01-21 23:45
@kevmoo which version of Dart were you running? This looks like a duplicate of https://github.com/dart-lang/sdk/issues/44700 and we reverted the CL that was causing the error. Wanted to know if you were running with the latest top of tree or a build from yesterday?

**Comment by kevmoo** [comment] 2021-01-21 23:58
```
version=2.12.0-242.0.dev (dev) (Mon Jan 18 18:26:11 2021 -0800) on "macos_x64"
```

I installed it today

**Comment by a-siva** [comment] 2021-01-22 00:12
That version did have the issue, the CL was reverted yesterday and the next dev build should have the fix. I am going to close this as a duplicate of https://github.com/dart-lang/sdk/issues/44700

**Closed by a-siva** 2021-01-22 00:12 UTC
Labels: area-vm, closed-duplicate, crash
