### ISSUE TITLE
Quick fix for non exhaustive matches in switch statements only adds a single missing case

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#53633] opened 2023-09-27 17:46 UTC
I'm viewing the following in VSCode. There are errors on both switch statements because they are not exhaustive. When I hover over the error with the mouse a quick fix is offered. The quick fix text says "Add missing switch ***cases***" (the emphasis on the plural "cases" is mine). When I click the quick fix only one case is added and I must keep applying the quick fix until all the cases have been added. This can be very tedious when there are many cases to add. It would easier if all the missing cases were added at the same time.

```dart
sealed class A {}
class B implements A {}
class C implements A {}
class D implements A {}

enum E { A, B, C }

void fn(A a) {
  switch (a) {
    case B():
      print('B');
  }
}

void gn(E e) {
  switch (e) {
    case E.A:
      print('A');
  }
}
```

**Comment by bwilkerson** [comment] 2023-09-27 18:03
I believe that this is a duplicate of https://github.com/dart-lang/sdk/issues/52180. Please re-open and let me know if that's not the case.

**Closed** 2023-09-27 18:03 UTC
