### ISSUE TITLE
Kernel Verifier broken on platform.dill

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#30631] opened 2017-09-06 13:16 UTC
Unhandled exception:
patched_sdk/lib/async/stream.dart:93:29: Verification error: StaticGet of 'dart.async::_EmptyStream::' without getter.

**Comment by peter-ahe-google** [comment] 2017-10-02 07:44
I need a command line that reproduces this problem.

**Comment by sjindel-google** [comment] 2017-10-02 13:31
Here's the patch:

```
diff --git a/pkg/kernel/bin/transform.dart b/pkg/kernel/bin/transform.dart
index 544e7aae7b..977ed7174a 100755
--- a/pkg/kernel/bin/transform.dart
+++ b/pkg/kernel/bin/transform.dart
@@ -18,7 +18,7 @@ import 'package:kernel/transformations/empty.dart' as empty;
 import 'package:kernel/transformations/method_call.dart' as method_call;
 import 'package:kernel/transformations/mixin_full_resolution.dart' as mix;
 import 'package:kernel/transformations/treeshaker.dart' as treeshaker;
-// import 'package:kernel/verifier.dart';
+import 'package:kernel/verifier.dart';
 import 'package:kernel/transformations/coq.dart' as coq;
 
 import 'util.dart';
@@ -111,7 +111,7 @@ Future<CompilerOutcome> runTransformation(List<String> arguments) async {
   // TODO(30631): Fix the verifier so we can check that the transform produced
   // valid output.
   //
-  // verifyProgram(program);
+  verifyProgram(program);
 
   if (format == 'text') {
     writeProgramToText(program, path: output);
```

Here are the reproduction commands:
```
DART_CONFIGURATION=ReleaseX64 ./pkg/front_end/tool/fasta compile pkg/kernel/lib/ast.dart
out/ReleaseX64/dart -c ./pkg/kernel/bin/transform.dart -t empty -o /dev/null pkg/kernel/lib/ast.dart.dill
```

**Comment by mkustermann** [comment] 2017-10-17 10:35
This issue is due to the way we handle redirecting constructors, for example:

```
static factory •<T extends core::Object>() → link::LinkBuilder<link::LinkBuilder::•::T>
   let 
     dynamic #redirecting_factory = lin::LinkBuilderImplementation::• 
   in
     invalid-expression;
```

This has been a known issue for a while. If my memory serves, then Peter and Kevin were discussing some possible solutions to this problem.

Right now we have the **kernel verifier disabled**, which I think is a **big red flag** - it catches bugs early on and we should have it enabled.

Precisely because of this, I wanted to land [cl/3002053002](https://codereview.chromium.org/3002053002/), which changes `verifier.dart` to allow this pattern pass verification until the redirecting factory issue has been solved!

@peter-ahe-google  / @kmillikin Can we make the `verifier.dart` change?

**Comment by peter-ahe-google** [comment] 2017-10-17 10:47
Blocked on #29841

**Comment by johnniwinther** [comment] 2023-08-21 11:41
Fixed now.

**Closed by johnniwinther** 2023-08-21 11:41 UTC
Labels: P2, area-front-end, front-end-kernel
