### ISSUE TITLE
`default` is redundant when switch is exhaustive

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#45437] opened 2021-03-23 23:05 UTC
analyzer Hint implementation issue for https://github.com/dart-lang/language/issues/1539

Given:

```dart
enum Level {
  low,
  medium,
  high
}

String myFunction(Level level) {
  switch (level) {
    case Level.low:
      return 'low';
    case Level.medium:
      return 'medium';
    case Level.high:
      return 'high';
    default:
      return 'never be executed';  // 'switch' is exhaustive so 'default' is redundant here
  }
}
```

Show a warning that default is dead code. I suspect this would use our current dead_code mechanisms and/or flow analysis.

**Comment by shilangyu** [comment] 2023-05-28 13:57
I would like to give this a try. Any pointers as to which packages this affects would be appreciated. I can probably figure out the rest.

**Comment by parlough** [comment] 2024-10-08 02:33
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/54575 and resolved by https://github.com/dart-lang/sdk/commit/cda2815bb1f028b4d88f664670865968bc64f847.

https://github.com/dart-lang/sdk/issues/54575 has many more linked commits that worked towards resolving this across the ecosystem.

**Closed by parlough** 2024-10-08 02:33 UTC
Labels: area-analyzer, P3, analyzer-warning, type-enhancement, contributions-welcome
