### ISSUE TITLE
Runtime Type evaluation

### ISSUE THREAD

**Issue by shamblett** [dart-lang/sdk#45820] opened 2021-04-25 11:29 UTC
I'm trying to evaluate a runtime type in a case statement -
```
 for (final dynamic element in value) {
      var valType = element.runtimeType;
      switch (valType) {
        case int:
          _writeInt(element);
          break;
        case String:
          _writeString(element);
          break;
        case double:
          _writeFloat(element);
          break;
        case List: ...........
```
The actual type being passed is List<int>, it could be any any List<T>. In the case statement it lets me specify 'List' but not List<int> or List<T> hence  the switch leg is not invoked.

So how do I just switch on any generic LIst type? Same applies to Map.

Originally I was doing this by toString'ing the runtime type and doing a .contains('List') on it, this works but is hacky and doesn't work in the browser if you minify things. I did it this way as the package I'm working on is several years old and at the time it seemed the only way to do this. Dart has moved on a trice since then so I'm guessing there is a more 'proper' way to do this now.

**Comment by eernstg** [comment] 2021-04-25 20:33
A switch on the run-time type is unlikely to work as intended. For instance `List` means `List<dynamic>`, so that case won't match `List<T>` for _any_ `T` which is different from `dynamic` (OK, it matches `List<FutureOr<dynamic>>` because of a normalization step, but it's different from `List<T>` for almost all other types than `dynamic`). Next, there aren't any instances of `List` because that's an abstract class, so you're always going to have some other class that is actually used as the implementation of that list.

The approach that will actually work is to perform a type test using `is`:

```dart
void main() {
  ... // Set up `value` etc. as needed.
  for (final dynamic element in value) {
    if (element is int) {
      _writeInt(element);
    } else if (element is String) {
      _writeString(element);
    } else if (element is double) {
      _writeFloat(element);
    } else if (element is List) {
      ...
    } else ...
  }
}
```

**Comment by eernstg** [comment] 2021-04-26 07:21
@shamblett, I'll close this issue because it is all working as intended.

**Closed by eernstg** 2021-04-26 07:21 UTC
Labels: closed-as-intended
