### ISSUE TITLE
DateTime constructed incorrectly for 1970-01-01

### ISSUE THREAD

**Issue by mark1010** [dart-lang/sdk#25391] opened 2016-01-09 17:54 UTC
Dart VM version: 1.13.2 (Tue Jan  5 06:36:44 2016) on "macos_x64"
Test machine locale UK / GMT.

code:
```
DateTime dt = new DateTime(1970);
print('dt: $dt');
```
output:
```
1969-12-31 23:00:00.000
```
expect:
```
1970-01-01 00:00:00.000
```

This issue is unique to 1970, within the range tested below:
```
main() {
  DateTime dt1 = new DateTime.now();
  print('now: $dt1, utc: ${dt1.toUtc()}');
  print('timeZoneName: ${dt1.timeZoneName}, timeZoneOffset: ${dt1.timeZoneOffset}\n');

  for(int i=0;i<=30000;i+=1) {
    DateTime dt = new DateTime(i);
    if(dt.year!=i) {
      print('incorrect DateTime year: $i -> $dt');
    }
  }

  DateTime dt2 = new DateTime(1970);
  print('\ndt2: $dt2');
}
```

output:
```
now: 2016-01-09 17:46:15.466, utc: 2016-01-09 17:46:15.466Z
timeZoneName: GMT, timeZoneOffset: 0:00:00.000000

incorrect DateTime year: 1970 -> 1969-12-31 23:00:00.000

dt2: 1969-12-31 23:00:00.000
```

**Comment by mit-mit** [comment] 2016-01-11 14:40
@lrhn, known issue?

**Comment by floitschG** [comment] 2016-01-11 15:47
Yes. this is a dupe of issue 19923.

Unfortunately there isn't a good solution to this... :(

**Closed by floitschG** 2016-01-11 15:47 UTC
Labels: area-library
