### ISSUE TITLE
reduce memory usage in dart2js

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24009] opened 2015-08-06 23:12 UTC
Some low hanging fruit can be to make it possible to GC some datastructures after we don't need them any more. We should be able to do that for the SSA and the type inference graphs.

It would also be good to invest in dropping localized data after we are done with it (possibly in a pipeline manner). unfortunately the global architecture of dart2js prevents a lot of this. For example, even during the code emitting phase,  we need the js_ast for the entire program to be able to use the frequency namer.

**Comment by sigmundch** [comment] 2015-08-06 23:18
Two other aspects that came up in conversations today:

* it's possible that the refactor that splits def and use of local variables in the ssa (used for source-maps purposes) might have increased our memory footprint. It would be good to evaluate the overall effect of this and see if there is anything we can do about it.

* during the transition to the resolver visitor, we have some extra redundancy that we use to validate that the old and new visiting techniques are equivalent. We might want to measure whether this is adding much to the overall memory footprint.

**Comment by srawlins** [comment] 2019-08-15 15:05
This and https://github.com/dart-lang/sdk/issues/27883 are duplicates, and the other may have more up-to-date info at this point.

**Comment by joshualitt** [comment] 2021-11-15 19:47
Duplicate of #27883

**Closed by joshualitt** 2021-11-15 19:47 UTC
Labels: web-dart2js, type-bug, area-web
