### ISSUE TITLE
Analyzer incorrectly rejects type variable bound of `Null`

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#37366] opened 2019-06-25 21:29 UTC
The analyzer currently rejects a use of `Null` as an upper bound on a type parameter:

```dart
void bar<T extends Null>() {
}
```

This is a valid upper bound.  See discussion here: https://github.com/dart-lang/sdk/issues/33709 .

The CFE seems to accept this.

**Comment by srawlins** [comment] 2019-10-15 05:18
Near duplicate of https://github.com/dart-lang/sdk/issues/33701

**Comment by srawlins** [comment] 2020-06-21 03:37
Analyzer no longer reports an error for this code (both with and without null-safety).

**Closed by srawlins** 2020-06-21 03:37 UTC
Labels: analyzer-spec, area-analyzer
