### ISSUE TITLE
True divergence between JIT and AOT

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#34467] opened 2018-09-14 20:30 UTC
Found with fuzz testing.

Exec-Mode 1 : Dart jit-x64
Exec-Mode 2 : Dart aot-x64

To reproduce

$ dart dartfuzz.dart --seed 2810422151 > fuzz.dart

$ dart fuzz.dart > jit.txt
$ precompiler2 fuzz.dart snap
$ dart_precompiled_runtime2 snap > aot.txt

$ diff jit.txt aot.txt
```
1,3d0
< 5e-324
< 5e-324
< throws
9c6
< 1
---
> -97

```

**Comment by l7ssha** [comment] 2018-09-14 20:57
Duplicate of #34466

**Comment by aartbik** [comment] 2018-09-14 21:06
Note that this is not a duplicate of #34466 since it deals with two different fuzz.dart files (seed that generates file is different, also output diff is different).

**Comment by aartbik** [comment] 2018-09-17 23:31
The JIT path throws an exception, and AOT does not. The root cause is not taking a particular if branch. Below a small reproducer. Very similar to the other fuzz bug found!
```dart
main() {
  if (!(((-84).toDouble() <= double.nan))) {
    print('yes');
  } else {
    print('no');
  }
}

```

**Comment by aartbik** [comment] 2018-09-17 23:45
Amazingly, by sheer luck the two bugs actually turned out to be related. This is just another instance of the same problem, but this time around negating it in a strict compare:
```

    CheckStackOverflow:8()
    PushArgument(v15)
    v5 <- StaticCall:16( toDouble<0> v15) T{_Double!}
    v16 <- Unbox(v7) T{_Double!}
    v18 <- Unbox(v5) T{_Double!}
    v8 <- RelationalOp(<=, v18, v16) T{bool!}
    Branch if StrictCompare:22(!==, v8, v10) goto (3, 4)

    CheckStackOverflow:8()
    PushArgument(v15)
    v5 <- StaticCall:16( toDouble<0> v15) T{_Double!}
    v20 <- UnboxedConstant(#NaN)
    v18 <- Unbox(v5) T{_Double!}
    Branch if RelationalOp(>, v18, v20 T{_Double!}) T{bool!} goto (3, 4)

```

**Closed** 2018-09-19 23:40 UTC
