### ISSUE TITLE
Kernel binary format does not identify the root library

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#32618] opened 2018-03-20 22:15 UTC
This prevents Dart_LoadScript/LibraryFromKernel from faithfully implementing Dart_LoadScript/Library.

**Comment by a-siva** [comment] 2018-03-22 04:22
Marking this as a duplicate of https://github.com/dart-lang/sdk/issues/29836

**Closed by a-siva** 2018-03-22 04:22 UTC
Labels: Customer-VM, area-kernel
