### ISSUE TITLE
type bound not respected by code completion

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#31475] opened 2017-11-29 07:22 UTC
If a generic function `f` has a type bound `A` on its generic argument `T`,
then code completion should know that variables of type `T` extend `A`...
yet it doesn't seem to in practice.  For example, enter the following into [dartpad](https://gist.github.com/anonymous/d9a215dbefd135bdb5627459c9dacc0c):

```dart
class A {
  final int x;
  
  A(this.x);
}

// Put the cursor just after the 't.' on the next line and ask for code
// completion.  It will foolishly say "No suggestions", but it should suggest x.
int f<T extends A>(T t) => t.x;

void main() {
  var a = new A(1);
  print(f(a));
}
```

It gets worse:
```dart
int f<T extends A>(T t) {
  T t2 = t;
  t2.x;  // No code completion here either.
  A t3 = t;
  t3.x;  // Perversely, you get code completion here with the _weaker_ type declaration.
  return t.x;
}
```
This sucks because you need to declare weaker types to get maximum help from the IDE.
The weird thing is that when you put your cursor over the `x`,
dartpad still says "int x" in the lower right corner.
So at some level, it understood.

**Comment by anders-sandholm** [comment] 2017-11-29 13:31
@eernstg @lukechurch

**Comment by leafpetersen** [comment] 2017-11-30 00:55
See also https://github.com/dart-lang/sdk/issues/29383

**Comment by srawlins** [comment] 2018-06-27 23:15
Duplicate of https://github.com/dart-lang/sdk/issues/24255.

**Closed by srawlins** 2018-06-27 23:15 UTC
Labels: analyzer-completion, analyzer-strong-mode, area-analyzer
