### ISSUE TITLE
issue-issue

### ISSUE THREAD

**Issue by khan-shahzad** [dart-lang/sdk#37986] opened 2019-08-23 21:09 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version , FATAL error: NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:760:9)
#2      Driver.start (package:analysis_server/src/server/driver.dart:394:28)
#3      main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\skha436\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-09-03 07:18
Thanks for reporting this issue! This was previously reported in https://github.com/dart-lang/sdk/issues/35226; please follow along there.

**Comment by srawlins** [comment] 2019-09-03 07:18
Duplicate of https://github.com/dart-lang/sdk/issues/35226

**Closed by srawlins** 2019-09-03 07:18 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
