### ISSUE TITLE
New issue reported

### ISSUE THREAD

**Issue by BqvXHXoVN6cu** [dart-lang/sdk#38720] opened 2019-10-04 17:36 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.eaf1c308ab85d433512ad3c9de26794288a9da64`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.eaf1c308ab85d433512ad3c9de26794288a9da64, server version 1.27.3, FATAL error: Failed to handle request: {id: 3427, method: edit.getFixes, params: {file: /Users/paulfielder/AndroidStudioProjects/flutter_insurance_manager/lib/Database/CRUD/EditEntry.dart, offset: 619}, clientRequestTime: 1570136807584}
type 'DefaultFormalParameterImpl' is not a subtype of type 'FormalParameterList' in type cast
#0      FixProcessor._addFix_removeUnusedField (package:analysis_server/src/services/correction/fix_internal.dart:3619:34)
#1      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#2      FixProcessor._addFix_removeUnusedField (package:analysis_server/src/services/correction/fix_internal.dart:3578:41)
#3      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:379:13)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:205:28)
#6      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:67:33)
#9      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:656:46)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file:///private/var/folders/16/1nfnr56162jf0swj3sfkzz_00000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-10-16 21:16
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38644; please follow along there.

**Comment by srawlins** [comment] 2019-10-16 21:17
Duplicate of https://github.com/dart-lang/sdk/issues/38644

**Closed by srawlins** 2019-10-16 21:17 UTC
Labels: analyzer-crash-report, area-analyzer
