### ISSUE TITLE
[vm/ffi] `lookupFunction` not working when using Xcode archive.

### ISSUE THREAD

**Issue by yulingtianxia** [dart-lang/sdk#43482] opened 2020-09-18 14:02 UTC
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Dart core libraries ("dart:ffi")
* Dart VM

Env:
* Dart SDK Version 2.9.1
* macOS 10.15.6
* Xcode 11.4 ~ Xcode 12 (Xcode 11.3.1 works well. )

Steps:

0. Create a new Flutter app. Then add some code using dart:ffi.
1. Run `flutter build ios`
2. Select Xcode Product > Archive to produce a build archive.
3. Open Xcode Window > Devices and simulators.
4. Get Runner.app from archive file: RunnerXXX.xcarchive > Products > Applications > Runner.app
5. Drag Runner.app to your device.
6. Open app in your device.

`lookupFunction` throws exception and returns `null`, it can't find symbol. 

**If you debug with your device, it works well.**

Workaround: 

Expose symbols by setting "Strip Style" to "Non-Global Symbols". BUT it will increase the size of release package.

**Comment by yulingtianxia** [comment] 2020-09-21 03:12
@mit-mit Hi, I think this problem is very serious. It will affect the release of iOS Apps.

**Comment by mit-mit** [comment] 2020-09-21 06:50
cc @dcharkes

**Comment by dcharkes** [comment] 2020-09-21 08:20
Duplicate of https://github.com/dart-lang/ffi/issues/41#issuecomment-645550964, with the same workaround documented.

> BUT it will increase the size of release package.

Xcode aggressively strips all code it thinks is dead, which includes the function you're trying to call through `dart:ffi` without the work around. So, it is expected that code size would be different. However, it might be worthwhile to investigate whether Xcode can be instructed to only keep the symbols one wants to call through `dart:ffi` and still remove the rest.

**Comment by yulingtianxia** [comment] 2020-09-21 08:53
@dcharkes I quite agree with you. Should I close this issue?

**Comment by mit-mit** [comment] 2020-09-21 09:01
Yes, closing

**Closed by mit-mit** 2020-09-21 09:01 UTC
Labels: area-vm, library-ffi
