### ISSUE TITLE
ThreadIterator_AddFindRemove test is flaky

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#24700] opened 2015-10-22 19:50 UTC
See, for example (links will go stale):
http://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-be/builds/10678/steps/tests/logs/stdio
http://build.chromium.org/p/client.dart/builders/vm-linux-release-x64-be/builds/10671/steps/checked_tests/logs/stdio
http://build.chromium.org/p/client.dart/builders/vm-arm64-sim-release-be/builds/8169/steps/tests/logs/stdio

**Comment by fsc8000** [comment] 2015-10-23 12:11
Duplicate of #24692 .

**Closed by fsc8000** 2015-10-23 12:11 UTC
Labels: Area-VM
