### ISSUE TITLE
patterns: Missing implementation of visitSwitchExpression

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/sdk#51331] opened 2023-02-08 23:33 UTC
This code causes an exception in the analyzer:
```dart

abstract class Shape {
  double get size;
}
class Square implements Shape {
  final double length;
  const Square(this.length);
  @override
  double get size => length;
}
class Circle implements Shape {
  final double radius;
  Circle(this.radius);
  @override
  double get size => radius;
}

double calculateArea(Shape shape) =>
  // Switch wth object patterns, from algebraic datatype example
  switch (shape) {
    Square(length: var l) => l * l,
    Circle(radius: var r) => math.pi * r * r
  };
```
Stack trace:
```
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - Unhandled exception:
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - Exception: Missing implementation of visitSwitchExpression
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #0      ThrowingAstVisitor._throw (package:analyzer/dart/ast/visitor.dart:2843:5)
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #1      ThrowingAstVisitor.visitSwitchExpression (package:analyzer/dart/ast/visitor.dart:2774:54)
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #2      SwitchExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:12867:50)
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #3      ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:2872:13)
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #4      MethodInvocationImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:9034:14)
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #5      ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:773:16)
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #6      TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:485:9)
2023-02-08 15:28:38,804 [ 325052]   INFO - STDERR - #7      VariableDeclarationResolver.resolve (package:analyzer/src/dart/resolver/variable_declaration_resolver.dart:55:15)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #8      ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:3434:34)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #9      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:13919:50)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9594:20)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #11     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14018:16)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #12     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:3456:10)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #13     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:14012:15)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #14     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14068:19)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #15     ResolverVisitor.visitVariableDeclarationStatement (package:analyzer/src/generated/resolver.dart:3463:10)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #16     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:14064:15)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9594:20)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #18     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1257:17)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #19     ResolverVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:1915:10)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1253:50)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #21     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1208:12)
2023-02-08 15:28:38,805 [ 325053]   INFO - STDERR - #22     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:1925:12)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #23     BlockFunctionBodyImpl.resolve (package:analyzer/src/dart/ast/ast.dart:1204:16)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #24     FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:64:29)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #25     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:2545:33)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #26     FunctionExpressionImpl.resolveExpression (package:analyzer/src/dart/ast/ast.dart:6096:14)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #27     ResolverVisitor.dispatchExpression (package:analyzer/src/generated/resolver.dart:773:16)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #28     TypeAnalyzer.analyzeExpression (package:_fe_analyzer_shared/src/type_inference/type_analyzer.dart:485:9)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #29     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:2508:7)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #30     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5958:50)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #31     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:2033:23)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #32     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2571:50)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #33     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:762:10)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #34     LibraryAnalyzer._parseAndResolve.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:569:7)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #35     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
2023-02-08 15:28:38,806 [ 325054]   INFO - STDERR - #36     LibraryAnalyzer._parseAndResolve (package:analyzer/src/dart/analysis/library_analyzer.dart:568:11)
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - #37     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:91:17)
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - #38     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1347:11)
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - #39     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - #40     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1389:26)
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - #41     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1104:21)
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - #42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2139:7)
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,807 [ 325055]   INFO - STDERR - 
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - #0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1376:9)
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - #1      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - #2      AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1389:26)
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - #3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1104:21)
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - <asynchronous suspension>
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - #4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2139:7)
2023-02-08 15:28:38,808 [ 325056]   INFO - STDERR - <asynchronous suspension>
```
cc @scheglov

**Comment by srawlins** [comment] 2023-02-09 18:35
CC @scheglov

**Comment by scheglov** [comment] 2023-02-09 18:55
This exception looks as duplicate of https://github.com/dart-lang/sdk/issues/51335
But the code itself can be analyzed with or without the fix for the mentioned issue.

**Closed by scheglov** 2023-02-09 18:55 UTC
Labels: P1, area-analyzer, type-bug, analyzer-crash-report
