### ISSUE TITLE
function vs property access results in widening of inferred generic type

### ISSUE THREAD

**Issue by felangel** [dart-lang/sdk#53760] opened 2023-10-15 06:27 UTC
Just wondering if this is working as expected and if so why the type of `d` cannot be inferred to be `Foo<int>` and instead is demoted to `Foo<num>`

```dart
T value<T>(Foo<T> foo) => foo.value;

class Foo<T> {
  Foo(this.value);

  T value;
}

Foo<T> bar<T>(T Function() callback) {
  return Foo<T>(callback());
}

void main() {
  final a = Foo(0);
  final b = Foo(0);

  final c = bar(() => a.value + b.value); // c is inferred to be Foo<int>
  final d = bar(() => value(a) + value(b)); // d is inferred to be Foo<num>
}
```

I can fix this by specifying the generic type on `bar` like:

```dart
final d = bar<int>(() => value(a) + value(b)); // d is inferred to be Foo<int>
```

But I would have expected `d` to also be inferred as `Foo<int>` without having to explicitly specify the type.

```
$ dart --version
Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_arm64"
```

**Comment by eernstg** [comment] 2023-10-16 07:58
Here is a simpler example showing the same behavior:

```dart
X id<X>(X x) => x;

void main() {
  int i1 = 1, i2 = 2;
  num n1 = i1;
  var a = i1 + i2; // Type `int`.
  var b = i1 + id(i2); // Type 'num'.
  var c = n1 + i2; // Type `num`.
}
```

This is actually working as intended. Numeric operators like `+` on built-in types are given [special attention](https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/number-operation-typing.md) because they are used so frequently. In particular, even though operator `+` on `int` has a declared type of `num Function(num)`, the static  analysis recognizes that the result is guaranteed to be an int in the case where the right hand operand is also an `int`.

In this example the important part is the [context type](https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/number-operation-typing.md#improved-context-type) for the right hand operand, and that's `num` when the context type of the whole addition expression is as general as it is in this case.

So `value(b)` is inferred as `value<num>(b)` (and similarly for `id(i2)`), and hence the result of the addition gets type `num`, and that's then also the type of `d`.

**Comment by eernstg** [comment] 2023-10-16 14:39
Just to show that the context type makes the difference, consider this variant:

```dart
T value<T>(Foo<T> foo) => foo.value;

class Foo<T> {
  Foo(this.value);

  T value;
}

Foo<T> bar<T>(T Function() callback) {
  return Foo<T>(callback());
}

void main() {
  final a = Foo(0);
  final b = Foo(0);

  final Foo<int> d = bar(() => value(a) + value(b)); // OK.
}
```

I'll close this issue because it is all working as intended.

**Closed by eernstg** 2023-10-16 14:39 UTC

**Comment by felangel** [comment] 2023-10-16 14:45
Thanks for the explanation!
