### ISSUE TITLE
Dart_SortClasses() hits assertion in ClassFinalizer

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#35690] opened 2019-01-17 14:10 UTC
From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8924082649842068288/+/steps/vm_tests/0/stdout):

```
FAILED: app_jitk-vm debug_x64 language_2/deferred_load_inval_code_test
Expected: Pass
Actual: Crash
Unexpected compile error.

--- Command "app_jit" (took 02.000954s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --snapshot=/b/s/w/ir/cache/builder/sdk/out/DebugX64/generated_compilations/app_jitk/tests_language_2_deferred_load_inval_code_test/out.jitsnapshot --snapshot-kind=app-jit --optimization-counter-threshold=100 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/language_2/deferred_load_inval_code_test.dart

exit code:
-6

stderr:
../../runtime/vm/class_finalizer.cc: 2038: error: expected: !present || typearg.IsRecursive()
thread=24117, isolate=deferred_load_inval_code_test.dart:main()(0x55814858e900)
  [0x00005581458cec2c] dart::Profiler::DumpStackTrace(void*)
  [0x00005581458cec2c] dart::Profiler::DumpStackTrace(void*)
  [0x0000558145b88992] dart::Assert::Fail(char const*, ...)
  [0x0000558145728059] dart::ClassFinalizer::RehashTypes()
  [0x0000558145727552] dart::ClassFinalizer::SortClasses()
  [0x0000558145b8543f] Dart_SortClasses
  [0x00005581455077ee] dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
  [0x0000558145508917] dart::bin::main(int, char**)
  [0x0000558145509319] Unknown symbol
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n app_jitk-linux-debug-x64 language_2/deferred_load_inval_code_test
```

Coredumps should be available at:
```
gs://dart-temp-crash-archive/98f7dd52-d166-4e17-81cf-3aaf0c0dcc16/*
```

**Comment by mkustermann** [comment] 2019-01-17 14:12
Might be related to https://github.com/dart-lang/sdk/issues/34627

**Comment by crelier** [comment] 2019-01-18 18:15
Yes, this is definitely a duplicate of #34627.

**Closed by crelier** 2019-01-18 18:15 UTC
Labels: area-vm, crash, gardening
