### ISSUE TITLE
Code completing from the beginning of a constructor shows incorrect options

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#25268] opened 2015-12-15 22:11 UTC
Consider this case:

`child: new FlatButton(onPressed: () {`

When you place your cursor between `(` and `o` and try to complete...

Expected: show a list of parameters for the constructor.

Actual:

![screen shot 2015-12-15 at 2 09 27 pm](https://cloud.githubusercontent.com/assets/5479/11825738/b47b257c-a335-11e5-9f6c-2d5c2e4ab208.png)

**Comment by sethladd** [comment] 2015-12-15 22:11
If you go to the end of the argument list, add a comma, and then try to code complete, you will see the correct arguments:

![screen shot 2015-12-15 at 2 11 29 pm](https://cloud.githubusercontent.com/assets/5479/11825745/c9c9776c-a335-11e5-917b-004baaaa5129.png)

**Comment by jwren** [comment] 2016-03-28 22:59
@sethladd, I think that this was a duplicate of this one: https://github.com/dart-lang/sdk/issues/25975?

**Comment by jwren** [comment] 2016-04-11 17:52
Confirmed that this is fixed.

![image](https://cloud.githubusercontent.com/assets/1533520/14436863/6d561f58-ffd3-11e5-8119-8700e11146ad.png)

**Closed by jwren** 2016-04-11 17:52 UTC
Labels: analyzer-completion, area-analyzer, Customer-Flutter, P2 medium, Type: bug
