### ISSUE TITLE
Missing hint when incorrectly calling a setter on a dynamic variable that's initialized

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24023] opened 2015-08-07 23:33 UTC
Consider this case:

![screen shot 2015-08-07 at 4 31 38 pm](https://cloud.githubusercontent.com/assets/5479/9147847/dfd40100-3d21-11e5-8b66-50edcdf55be7.png)

I would have expected a warning or at least a hint because I'm trying to call `data.markdown =` but the setter doesn't exist.

Here's the definition of the class:

![screen shot 2015-08-07 at 4 31 44 pm](https://cloud.githubusercontent.com/assets/5479/9147850/f816e2dc-3d21-11e5-8041-a5d3d44600a5.png)

If I add the type annotation to `data` then I get the warning.

**Comment by bwilkerson** [comment] 2015-08-07 23:41
Errors and warnings are generated based on the static type, and the static type of 'data' is 'dynamic', hence, no warning. That said, we should produce a hint corresponding to the warning.

Alternatively, once strong mode is supported we'll be doing type inference that will cause the warning to be generated, and that might be sufficient.

**Comment by sethladd** [comment] 2015-08-07 23:45
Ah, interesting. So does that mean the only way to get full errors and warnings is to use type annotations for every variable?

**Comment by munificent** [comment] 2015-08-07 23:47
> Alternatively, once strong mode is supported we'll be doing type inference that will cause the warning to be generated, and that might be sufficient.

Strong mode FTW!

**Comment by bwilkerson** [comment] 2015-08-07 23:56
> So does that mean the only way to get full errors and warnings is to use type annotations for every variable?

Yes. Dart can be used as an untyped language, in which case you don't get bothered with pesky errors and warnings. It can also be used as a strongly typed language, if you add type annotations everywhere, in which case you'll get most of the errors and warnings you expect (modulo the fact that it has an unsound type system). Or it can be used as a combination of both, which is what the style guide, for example, recommends.

Strong mode does two things. It makes the type system more sound and it infers types in some situations. But these advantages come with a cost: some constructs that are allowed in Dart will produce errors or warnings in strong mode. Personally, I think it's worth the cost, but not everyone will agree.

**Comment by sethladd** [comment] 2015-08-08 00:01
thanks for the explanation. Looking forward to more feedback from analysis of the code. Using var + being told when I did the wrong thing? Sign me up.

**Comment by eernstg** [comment] 2015-08-10 09:07
I still think it would be nice to make a distinction: Treat `var x;` as an
explicit indication that the type of the variable `x` is `dynamic` and we
don't want to hear about it's relation to the type system (as specified).
Some other syntax (maybe `? x;`) could then mean that this variable is
intended to have a type annotation, but we wish to have it inferred.

With that, it makes sense to throw a type error in checked mode if that
inferred type is violated (assuming that the inference mechanism doesn't
prevent that, e.g., because the type is inferred from the initialization
expression rather than from the entire scope of the variable). It would
also make sense for an IDE to give programmers a notification when some
editing operation changes the inferred type of some variable (even though
that's of course potentially "anywhere in the world", we could get notified
of all the known cases).


On Sat, Aug 8, 2015 at 2:01 AM, Seth Ladd <notifications@github.com> wrote:

> thanks for the explanation. Looking forward to more feedback from analysis
> of the code. Using var + being told when I did the wrong thing? Sign me up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24023#issuecomment-128863791>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by bwilkerson** [comment] 2015-08-10 13:49
> It would also make sense for an IDE to give programmers a notification when some editing operation changes the inferred type of some variable ...

Do you have an example of when you'd like to see this? My intuition is that this would be annoying. Consider the following example:

    var found = new List();

I don't want to be told if I change this to:

    var found = new HashSet();

I also don't think I'd want to be told if I initialize a variable with an invocation of a method and then later change the return type of the method.

What problem are you thinking of that this kind of notification would solve?

**Comment by eernstg** [comment] 2015-08-10 15:12
Hello Brian,

On Mon, Aug 10, 2015 at 3:49 PM, Brian Wilkerson <notifications@github.com>
wrote:

> It would also make sense for an IDE to give programmers a notification
> when some editing operation changes the inferred type of some variable ...
>
> Do you have an example of when you'd like to see this? My intuition is
> that this would be annoying.
>
The underlying motivation is that inference may give rise to program
elements which are both significant and invisible, and that's a dangerous
combination. It is especially sinister if changes that are seemingly remote
can may your code invalid, and you never notice that anything has changed.

But you're probably right, my remark above sounds too aggressive. There are
lots of ways to turn up and down the "volume", though.

Worst case, we'd have a modal popup that stops the world until you type
your password twice, backwards. ;) A dimly colored squiggly line under a
word is much less noisy. Even more softly, programmers could have the
option to browse and search the history of such changes (anything showing a
diff could allow programmers to browse other things than just the textual
modifications, including modifications of inferred type annotations).

So we can always discuss what the right "volume level" should be; my point
is just: please allow programmers to notice this kind of phenomenon.

In some cases we get it for free: Assume that we have a rather strictly
typed piece of code containing `var x = foo();` (preferably, but
hypothetically: `? x = foo();`), and assume that inference makes this
declaration work as if we had written `T x = foo();`. If we are using the
expression `x.y` somewhere and `T` declares a `y` then a change (of `foo`,
somewhere else) that makes it work like `S x = foo();` where `S` does not
declare such a member gives rise to a warning.

But if `S` does define a `y` that has an entirely different meaning than in
`T`, or if `S` == `dynamic`, or if there is a warning but it simply takes a
while before we get around to it, so we have no idea that the warning was
caused by the change to the return type of `foo`, then it would be nice to
have the option to keep an eye on the actual set of declarations affected
by this change, that is, including the ones where the change is implicit.

> Consider the following example:
>
> var found = new List();
>
> I don't want to be told if I change this to:
>
> var found = new HashSet();
>
> Right. This isn't actually an implicit change, because the change in
inferred type is correlated with an editing operation in the affected
declaration itself. Having done that, it would be rather natural to look
into warnings in the scope of `found` immediately, and fix them.

However, even in this situation it might be helpful to be able to compare
the "before" and "after" type of `found` in order to understand the
consequences for usages of `found`. That could be an additional level of
information available at those use sites, indicating that `found.add(..)`
is now an entirely different operation, because of the different semantics
of lists and sets (so the example with `T`, `S`, and `y` above is not
totally unrealistic ;-).

> I also don't think I'd want to be told if I initialize a variable with an
> invocation of a method and then later change the return type of the method.
>
Sure? Not even softly?  ;-)

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by floitschG** [comment] 2015-08-10 15:36
I haven't heard about "strong mode" before. Can anyone point me to the docs for it?

I don't think we need another syntax for inferred var (Erik used "?"). We already have a "dynamic" and a "var". Let's just add a "--no-implicit-dynamic" to the analyzer and make it such that the analyzer complains if it cannot infer the type of a "var" variable. Users can simply escape to "dynamic" if the type is really dynamic.

Erik's suggestion that the "?" is replaced with an inferred type is the simplest approach. I think the analyzer can go as far as it wants to make it less restrictive. There should be no reason that a variable can't be reused (with a different type) as long as the analyzer rechecks at every assignment that all subsequent uses are typed correctly.

**Comment by bwilkerson** [comment] 2015-08-10 15:57
> I haven't heard about "strong mode" before. Can anyone point me to the docs for it?

Strong mode is the name of the type system being developed for DDC. It's documented here: https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md.

> There should be no reason that a variable can't be reused (with a different type) as long as the analyzer rechecks at every assignment that all subsequent uses are typed correctly.

Agreed. That's what the analyzer currently does.

But strong mode actually prohibits that use case. The type is inferred at the point of origin and then isn't allowed to change. But note that the user has to opt in to strong mode; it won't be imposed on them.

> But if `S` does define a `y` that has an entirely different meaning than in `T`, or if `S` == `dynamic`, or if there is a warning but it simply takes a while before we get around to it, so we have no idea that the warning was caused by the change to the return type of `foo`, then it would be nice to have the option to keep an eye on the actual set of declarations affected by this change, that is, including the ones where the change is implicit.

Sure, but I don't think that Dart code has enough information in it for us to be able to figure out that the `y` defined in `S` doesn't have the same semantics as the `y` in `T`. For this case, strong mode won't go as far as you might want, but it's better than checked (or production) mode and not worse.

> > I also don't think I'd want to be told if I initialize a variable with an
> > invocation of a method and then later change the return type of the method.
>
> Sure? Not even softly?  ;-)

The example you gave is fairly abstract. I guess what I'm looking for is a "here's the code I had, here's the change I made, and here's the problem it caused without my getting any notification" kind of description.

The reason I want something fairly concrete is because there's a high cost to false positives. People tend to ignore or remove warnings that have a lot of false positives; worst case, they start ignoring all warnings because they can't get rid of only the ones they don't want. Before adding a feature like this I'd want to know that we have a low (or zero :-) probability of false positives. But as it stands, I think there's a fairly high probability of false positives. Understanding concrete use cases helps me formulate the rule in a way that eliminates false positives.

So, yes, I'd rather have no warnings for these cases than false positives.

**Comment by eernstg** [comment] 2015-08-10 16:33
On Mon, Aug 10, 2015 at 5:36 PM, Florian Loitsch <notifications@github.com>
wrote:

> I haven't heard about "strong mode" before. Can anyone point me to the
> docs for it?
>
> I don't think we need another syntax for inferred var (Erik used "?"). We
> already have a "dynamic" and a "var".
>
What worries me is simply that it is a breaking change to say that `var x =
e;` is the same thing as `T x = e;` when `T` is the static type of the
expression `e`. Also, programmers who wish to use a dynamic style wouldn't
want to use the style 'dynamic x = e;` everywhere. But new syntax (e.g., `?
x = e;`) could have the new semantics.

> Let's just add a "--no-implicit-dynamic" to the analyzer and make it such
> that the analyzer complains if it cannot infer the type of a "var"
> variable. Users can simply escape to "dynamic" if the type is really
> dynamic.
>
> Erik's suggestion that the "?" is replaced with an inferred type is the
> simplest approach. I think the analyzer can go as far as it wants to make
> it less restrictive.
>
Inference has the "syntactic sugar" effect in many languages; in Scala, for
instance, `var x = [];` is a `List[Nothing]`, and you will fail if you try
to put anything into it, so this really works as if we had written
`List[Nothing] x = [];`. I guess being less restrictive here means using
the inferred type for IDE completion etc., but not considering the variable
to have the inferred type as its type annotation. As long as we are only
talking about IDE behavior and not program behavior, we can of course do
whatever we want.

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by bwilkerson** [comment] 2015-08-10 16:47
> Also, programmers who wish to use a dynamic style wouldn't want to use the style 'dynamic x = e;` everywhere.

Agreed, but that just means that they don't want to use strong mode.

> But new syntax (e.g., `? x = e;`) could have the new semantics.

Yes, but one of the design goals for DDC was to not require language changes. Of course, you could write a DEP proposal to add the new syntax. :-)

> I guess being less restrictive here means using the inferred type for IDE completion etc., but not considering the variable to have the inferred type as its type annotation.

Actually, no. The inferred type is taken to be the static type for the purpose of generating errors and warnings.

> As long as we are only talking about IDE behavior and not program behavior, we can of course do whatever we want.

Strong mode does not change the run-time behavior of Dart code. It does change the behavior of the command-line analyzer as well as IDE support, and as noted above changes the errors and warnings that are produced by using the inferred type as if it were the static type. But again, if users don't like it they don't have to use it.

**Comment by eernstg** [comment] 2015-08-10 17:09
On Mon, Aug 10, 2015 at 5:57 PM, Brian Wilkerson <notifications@github.com>
wrote:

> I haven't heard about "strong mode" before. Can anyone point me to the
> docs for it?
>
> Strong mode is the name of the type system being developed for DDC. It's
> documented here:
> https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md.
>
> There should be no reason that a variable can't be reused (with a
> different type) as long as the analyzer rechecks at every assignment that
> all subsequent uses are typed correctly.
>
> Agreed. That's what the analyzer currently does.
>
> But strong mode actually prohibits that use case. The type is inferred at
> the point of origin and then isn't allowed to change. But note that the
> user has to opt in to strong mode; it won't be imposed on them.
>
I believe this mixes two different scenarios: (1) The type of variable `x`
declared as `var x = e;` (or `? x = e;`) is `T`, by inference, and some
editing operation changed it to a different type `S`; and (2) The type `T`
of variable `x` declared as `var x = e;` is obtained by inference that
takes the entire scope of `x` into account, even though the declaration
(including an initializing expression) of `x` indicates a different type
`S`. I wouldn't expect strong mode to prohibit (1), it's hard to see how it
could do that. But (2) embeds a different meaning of the phrase "the type
of this variable has changed", so that's a different topic.

The approach where a declared variable is associated with multiple
different types, depending on the location in the code (that is, depending
on flow analysis) is a separate topic. With that approach we cannot hope to
talk about "the type annotation" for a variable, because that concept is
bound to the declaration and it doesn't allow for more than one type (even
a union type is too unspecific: we don't know where each summand applies).

But I tend to think that such an approach is too costly to make explicit:
It's fine that a tool performs the flow analysis and provides type
consistency feedback (as in "I don't think there is a `y` on `x` _here_").
So that's not the kind of inference I want to push into the syntax; it's
only the kind where each variable gets just one type in its entire scope,
we just don't want to bother to use the keyboard (and maybe doing some
busywork looking up declarations) in order to make that single type
explicit.

But I think it's useful to use the keyboard to explicitly indicate that the
type is inferred.

> But if S does define a y that has an entirely different meaning than in T,
> or if S == dynamic, or if there is a warning but it simply takes a while
> before we get around to it, so we have no idea that the warning was caused
> by the change to the return type of foo, then it would be nice to have
> the option to keep an eye on the actual set of declarations affected by
> this change, that is, including the ones where the change is implicit.
>
> Sure, but I don't think that Dart code has enough information in it for us
> to be able to figure out that the y defined in S doesn't have the same
> semantics as the y in T.
>
That's not hard! ;-)

The point is that we (can choose to) take nominal types seriously: If `y`
in `S` and `y` in `T` have no declarations in common (that is, a static
lookup for the two `y` features in `S`, `T` and their supertypes find sets
of declarations that do not overlap). With that there is no need for magic,
we just note that there is no reason to assume that the two `y` features
mean the same thing because no such commonality was ever expressed by the
programmers.

> For this case, strong mode won't go as far as you might want, but it's
> better than checked (or production) mode and not worse.
>
> I also don't think I'd want to be told if I initialize a variable with an
> invocation of a method and then later change the return type of the method.
>
> Sure? Not even softly? ;-)
>
> The example you gave is fairly abstract. I guess what I'm looking for is a
> "here's the code I had, here's the change I made, and here's the problem it
> caused without my getting any notification" kind of description.
>
You gave that example: Changing `found` from a `List` to a `Set` changed
the semantics of `add` anywhere in the scope of `found` (and, by extension,
anywhere that object flows dynamically). Don't you ever want to inspect
that kind of change before you commit to it?

> The reason I want something fairly concrete is because there's a high cost
> to false positives.
>
True, but that's again a matter of "volume". We can make those things very
soft-spoken, yet available if needed.

> People tend to ignore or remove warnings that have a lot of false
> positives; worst case, they start ignoring all warnings because they can't
> get rid of only the ones they don't want.
>
That's a piece of experience that I fully recognize and respect.

> Before adding a feature like this I'd want to know that we have a low (or
> zero :-) probability of false positives. But as it stands, I think there's
> a fairly high probability of false positives. Understanding concrete use
> cases helps me formulate the rule in a way that eliminates false positives.
>
> So, yes, I'd rather have no warnings for these cases than false positives.
>
I believe that this is an entirely new category of diagnostics (it is
concerned with editing operations rather than static entities such as
libraries or programs), and in that sense we don't have so much to compare
with (and there is no way it would be made part of the language spec,
because it is concerned with static entities). So the formal concept of a
'warning' is too heavy.

But just like completion can be used by programmers, even though it relies
on an analysis where type annotations are trusted, "changes in inferred
types" browsing could be used by programmers who are busy refactoring some
code and curious about the correctness of some step in this process. Nobody
forces one or the other upon you.

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by eernstg** [comment] 2015-08-10 17:33
On Mon, Aug 10, 2015 at 6:47 PM, Brian Wilkerson <notifications@github.com>
wrote:

> Also, programmers who wish to use a dynamic style wouldn't want to use the
> style 'dynamic x = e;` everywhere.
>
> Agreed, but that just means that they don't want to use strong mode.
>
But they can't make the choice: If they write code in a reusable library,
and they used `var`, and they want the `dynamic` type treatment at runtime,
then they cannot rely on everybody else to not use strong mode in a context
that includes their library.

> But new syntax (e.g., ? x = e;) could have the new semantics.
>
> Yes, but one of the design goals for DDC was to not require language
> changes. Of course, you could write a DEP proposal to add the new syntax.
> :-)
>
Will do.

> I guess being less restrictive here means using the inferred type for IDE
> completion etc., but not considering the variable to have the inferred type
> as its type annotation.
>
> Actually, no. The inferred type is taken to be the static type for the
> purpose of generating errors and warnings.
>
But errors and warnings are in the spec, and they are associated with the
behavior of programs in checked mode, so I cannot see how those concepts
can be used unless it is implied that an inferred type is _actually_
considered to be the type annotation, in which case my worries about the
need for the `dynamic x = e;` style in dynamic code are reinforced. With `?
x = e;` we can let `?` stand for the inferred type, consistently and
strictly.

> As long as we are only talking about IDE behavior and not program
> behavior, we can of course do whatever we want.
>
> Strong mode does not change the run-time behavior of Dart code.
>
Doesn't it catch things like this?:

  List<int> xs = [1, 2];
  List ys = xs;  // OK statically (by covariance), and of course
dynamically.
  ys[0] = "Hello";  // Fails because [1, 2] is inferred to mean <int>[1, 2].
  xs[0].gcd(42);  // .. or: Fails, because `xs` "shouldn't contain a String"

In the last line, my expectation is that "it's not strong enough" to fail
because "Hello" does not have a `gcd` method, it should fail earlier than
that. This is the reason why I don't write "Fails because of a
`NoSuchMethodError` during the invocation of `gcd`". But standard Dart
semantics _will_ proceed all the way to `NoSuchMethodError`, because `xs`
is allowed to refer to a `List<dynamic>`, and a `List<dynamic>` is allowed
to contain a `String`.

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by bwilkerson** [comment] 2015-08-10 18:07
> Changing `found` from a `List` to a `Set` changed the semantics of `add` anywhere in the scope of `found` (and, by extension, anywhere that object flows dynamically).

Not from my perspective. The only semantic I had in mind for `add` was that after the method `add` was invoked, the method `contains` would return `true`. Granted, the `add` in `List` and the `add` in Set differ in semantics in other ways, but not that way. I don't know how, using static analysis, to know whether the semantics I care about are the same or not.

> Don't you ever want to inspect that kind of change before you commit to it?

Of course! In fact, I want to inspect that kind of change before I make it. I look at uses of `found` to understand whether the semantic change will break the code or not, and only change the type once I'm convinced that it's safe.

> But they can't make the choice: If they write code in a reusable library, and they used `var`, and they want the `dynamic` type treatment at runtime, then they cannot rely on everybody else to not use strong mode in a context that includes their library.

True, but they also can't rely on everybody else to not use checked mode in a context that includes their library. I'm not sure how this is any different.

And if I'm writing code and using strong mode to help catch problems earlier in the dev cycle, then I'd want to know if a library I was using violated strong mode because I'd seriously question whether it was safe for me to use it.

All DDC is doing here is adding another level of checking. Just as checked mode is stronger than production mode, strong mode is stronger than checked mode.

**Comment by eernstg** [comment] 2015-08-11 10:40
On Mon, Aug 10, 2015 at 8:07 PM, Brian Wilkerson <notifications@github.com>
wrote:

> Changing found from a List to a Set changed the semantics of add anywhere
> in the scope of found (and, by extension, anywhere that object flows
> dynamically).
>
> Not from my perspective. The only semantic I had in mind for add was that
> after the method add was invoked, the method contains would return true.
> Granted, the add in List and the add in Set differ in semantics in other
> ways, but not that way. I don't know how, using static analysis, to know
> whether the semantics I care about are the same or not.
>
Of course, we couldn't expect a tool to know which semantic distinctions we
have in mind for any particular purpose, but my point is that we don't need
that kind of magic: The phenomenon that I propose watching for (possibly
giving notifications about, possibly stashing away in a data structure for
the programmer to browse if needed) is when an editing operation causes a

    rebinding of a name

to a declaration which is unrelated to its previous binding according to
the nominal typing structure. It could also be detected relative to a diff
between two versions in a version control system, etc.etc.

If we detect that phenomenon then we can help programmers track down the
_unwanted_ rebindings. This can be useful because the associated semantic
disruptions might otherwise easily sneak under the radar, especially when a
number of links in the dependency chain are invisible due to type
inference, and especially when the affected code is far away from the piece
of code that was actually modified.

> Don't you ever want to inspect that kind of change before you commit to it?
>
> Of course! In fact, I want to inspect that kind of change before I make
> it. I look at uses of found to understand whether the semantic change
> will break the code or not, and only change the type once I'm convinced
> that it's safe.
>
In many situations it might be quicker (and still reasonable) to just make
the change and check whether there are any of those nominal rebindings, and
use that when making the decision: "Should I keep this change, or should I
press 'Undo'?"

> But they can't make the choice: If they write code in a reusable library,
> and they used var, and they want the dynamic type treatment at runtime,
> then they cannot rely on everybody else to not use strong mode in a context
> that includes their library.
>
> True, but they also can't rely on everybody else to not use checked mode
> in a context that includes their library. I'm not sure how this is any
> different.
>
If your code runs in checked mode and no `TypeError`s are thrown then your
code will run identically in production mode.

If your code throws a `TypeError` in checked mode and it is caught and
handled then all bets are off wrt checked/production mode alignment, so we
basically don't want that.

But adding yet another a subtly different semantics doesn't improve on that
situation. In particular, it is a new source of subtle inconsistencies if
`var x = e;` sometimes means `dynamic x = e;` and sometimes means `T x =
e;`, especially when running in checked mode.

(Yes, it's common to say "but nobody does that", but I'm not totally
convinced, and in particular I don't want to push the situation in the
direction of "but nobody does that, because you never know what it will
do").

> And if I'm writing code and using strong mode to help catch problems
> earlier in the dev cycle, then I'd want to know if a library I was using
> violated strong mode because I'd seriously question whether it was safe for
> me to use it.
>
There could very well be cases where code which is unsafe on the surface
happens to be very carefully crafted (following a discipline which cannot
be expressed or recognized by the type system). For instance, a
`_Future<T>` has a field `_resultOrListeners` which will surely have
difficulties passing strong mode compilation, but it wouldn't be easy for a
substantial set of programs to avoid depending on 'dart:async'. So we
probably don't want to force strong mode upon all parts of our programs,
even in an organizational setting where strong mode coding is the standard.

However, I think the important point here is that semantic inconsistencies
among different "kinds of Dart" are dangerous, and interpreting `var` as
`T` in some declarations, or creating an instance of `List<int>` when
evaluating `[1]` (not `<int>[1]`) in some initializing expressions are
examples of this kind of inconsistencies. One Dart is better than three! ;^)

> All DDC is doing here is adding another level of checking. Just as checked
> mode is stronger than production mode, strong mode is stronger than checked
> mode.
>
Stronger checking can be reconciled with an existing language semantics if
there is a very simple story (e.g., "a program P executed in language L
resp. in language L' will proceed in lockstep---that is, the heaps remain
isomorphic and externally visible actions are identical---until they both
terminate identically, or L' at some step terminates with a type error and
L continues", leaving some required fixes in case of non-determinism
implicit). That's what I'm asking for, e.g., via `? x = e;` rather than via
reinterpretation of `var x = e;`.

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by eernstg** [comment] 2015-08-11 11:40
Hello again,

I was [just] answering email, but looking again this is of course an 'Area-Analyzer' issue, which means that the discussion has been spiraling out of scope for a while. Sorry about having contributed generously to that development.  ;-)

I guess the more general topics should be discussed on a mailing list (e.g., core-dev@dartlang.org or dart-discuss@google.com) instead.

**Comment by leafpetersen** [comment] 2015-08-12 18:25
This discussion ranged fairly widely, not sure I have all of the threads in my head at once, but a couple of thoughts.

1) Local variables and top level variables are different, and we may want different inference behavior for them.  In particular, the discussion about inference changing the API is not relevant to local variables.  My general inclination is to be much more conservative about inference for things which have non-local uses.

2)  DDC currently will infer a type for local variables based on the initializer.  As noted, this may cause errors to show up if the variable is used at different types later in the method.  We could be (and may experiment with) doing something a bit smarter here, but we want what we are doing to be predictable and understandable.

3) I believe it is possible to add inference for local variables in an entirely backwards compatible way that would introduce no additional errors or warnings to any code (including dynamic code, and including broken code).  This can be done by simply doing any form of inference you choose, but allowing dynamic to be inferred as the concrete type.  Any code that could be typed before can still be typed, since dynamic is always a choice.  This reduces the error checking benefits, but still provides code completion benefits.  In this way, it's more like the analyzers "propagated type".  I don't advocate this, but mention it as a point in the design space, in part because of the next point.

4) Having syntax to ask for inference would be very nice.  I'd also like to see this for generic parameters (e.g ```List<?>```, or ```List<>```).  It occurs to me that if we go this route, it would be useful to treat "var x" as I describe above (that is, "infer the best type for x that allows the program to be typed, including dynamic as an option"), while treating "var? y" as "infer the best non-dynamic type for y".  The point being that this would allow the inference engine to take advantage of inference results for x when they are available, instead of requiring it to treat x as dynamic for the purposes of inference (even when x has a perfectly consistent and inferable type).

**Comment by askeksa-google** [comment] 2018-06-27 12:46
This issue seems to be outdated with Dart 2 falling into place.

**Closed by askeksa-google** 2018-06-27 12:46 UTC
Labels: P2 medium, Type: bug, area-analyzer
