### ISSUE TITLE
Can't move files to different dir

### ISSUE THREAD

**Issue by sanekyy** [dart-lang/sdk#40819] opened 2020-02-28 17:41 UTC
![image](https://user-images.githubusercontent.com/18647037/75571677-b94bb080-5a6a-11ea-9ae2-699665a2b2a1.png)

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6200805`
- `2.8.0-edge.f5669caec7c377b49bc0b08f1638e026507b0f84`
- `AI-192.7142.36.36.6200805, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.f5669caec7c377b49bc0b08f1638e026507b0f84, server version 1.27.4, error: FileSystemException(path=/Users/sanekyy/Projects/optimist.dev/gohere/client/lib/data/model/server/place.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:247:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:90:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:74:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:73:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:178:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:159:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:147:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:72:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:146:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:989:41)
<asynchronous suspension>
#12     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1502:12)
#17     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:945:5)
#18     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:832:24)
#19     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:379:16)
#20     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:316:45)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#22     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:312:50)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1502:12)
#27     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:311:5)
#28     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#29     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#30     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#31     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#32     _rootRunUnary (dart:async/zone.dart:1134:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#40     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#41     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#42     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#49     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#50     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#51     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#52     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#53     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#54     _Utf8ConversionSink.ad...
```

For additional log information, please append the contents of
file:///private/var/folders/hx/klmbwq7j3wx1kzz491c_dt_00000gp/T/report1.txt.

**Comment by srawlins** [comment] 2020-06-13 03:06
Thanks for reporting this issue! This was previously reported at #40063; please follow along there.

**Comment by srawlins** [comment] 2020-06-13 03:06
Duplicate of #40063

**Closed by srawlins** 2020-06-13 03:06 UTC
Labels: analyzer-crash-report, area-analyzer, area-intellij, type-bug
