### ISSUE TITLE
crashed after changing from git lib to a local library

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#35493] opened 2018-12-24 14:48 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-183.4284.130`
- `2.1.0`
- `WS-183.4284.130, JRE 1.8.0_152-release-1343-b15x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2, screens 1680x1050, 2560x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/d6/0b0y5zls1h9cy4h11vvrgyh00000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0, server version 1.21.1, error: Analysis failed: /Users/jonathanrezende/Projects/guaraci/core/guaraci_models/lib/models/url.dart context: exception_20181222_165211_247
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      _ClassVerifier._checkForMismatchedAccessorTypes (package:analyzer/src/error/inheritance_override.dart:357:45)
#2      _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:173:5)
#3      InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:44:11)
#4      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:332:33)
#5      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#6      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2019-01-02 18:17
Duplicate of #35223

**Closed by stereotype441** 2019-01-02 18:17 UTC
Labels: area-analyzer
