### ISSUE TITLE
Static analyzer is not respecting the null safety check by a common method

### ISSUE THREAD

**Issue by ganeshrvel** [dart-lang/sdk#42723] opened 2020-07-16 13:36 UTC
The static analysis should respect the null check done by a generic method.

Here are two samples, the `isNotNull` method should took care of the null safety check and it should be treated as a valid safety contract.

Typescript has **Type-guard** feature, how about implementing something like that in Dart language?

Sample 1:
```dart
// return true if not null
bool isNotNull(int? x) {
  return x != null;
}

int getA(int? a) {
  if (isNotNull(a)) {
    return a; // a static analysis error in thrown even though the value of 'a' is confirmed to be not null
  }

  if (a != null) {
    return a; // but the flow analysis works flawlessly in this case
  }

  return 1;
}

void main() {
  int? a;

  print(getA(a));
}

```

In the below code snippet the `hasData` getter method evaluates the null safety of the `age` field which should be enough to convey the compiler that it will be always defined.

Sample 2:
```dart
class Person {
  final int? age;

  Person({
    this.age,
  });

  // checks whether data is available
  bool get hasData => age != null;
}

int getData() {
  final _person = Person(age: 1);

  if (_person.hasData) {
    return _person.age; // the static analysis fails here
  }

  if (_person.age != null) {
    return _person.age; // the static analysis fails here; which shouldn't be the case
  }

  return -1;
}
```

Interestingly, the below code block from the above snippet fails and it seems to be a bug:

```
  if (_person.age != null) {
    return _person.age; // the static analysis fails here; which shouldn't be the case
  }
```

**Comment by jodinathan** [comment] 2020-07-16 13:47
this reminds me the bug, or missing feature, where the analyzer sometimes can't relate the type:

```dart
class MyObj {
  Object myProp;
}
if (myObj.myProp is String) { 
  // sometimes myProp is correctly analyzed as String and sometimes I have
  // to cast it like (myObj.myProp as String).isNotEmpty
  var a = myObj.myProp.isNotEmpty; 
  // ...
}
```

**Comment by eernstg** [comment] 2020-07-16 13:54
A couple of things you mention are actually working as intended:

`if (isNotNull(a)) ...` cannot promote `a` as written, because there is no mechanism that keeps track of knowledge about a local variable when its value is passed as an actual argument. If that function is inlined as `a != null` then it is possible to obtain the desired result, but not all functions can be inlined (and if inlining were allowed to have this effect then we would allow the code to be very fragile, because small changes in the invoked function could prevent inlining).

Next, `if (_person.age != null) ...` cannot promote anything, because promotion is for local variables only.

In particular, it wouldn't be sound to promote `_person.age` because the evaluation of that expression may invoke arbitrary code. That's because the run-time type of `_person` might be class which is a subtype of `Person`, and that class could have an overriding implementation of the getter `age`. So it could return different results each time it's invoked, and a test which shows that it has returned a value of type `int` at some point doesn't say anything about the type of the return value from another invocation.

**Comment by ganeshrvel** [comment] 2020-07-16 14:06
Isn't it possible to do any about it? There are a lot of utils libraries out there which checks for null. But after the NNBD is implemented they just become redundant.

```dart

if(isNotNull(a)){ // redundant and useless
  return a ?? -1;
}

return -1
}

```

**Comment by jodinathan** [comment] 2020-07-16 14:11
> @eernstg
> 
> Isn't it possible to do any about it? There are a lot of utils libraries out there which checks for null. But after the NNBD is implemented they just become redundant.
> 
> ```dart
> if(isNotNull(a)){ // redundant and useless
>   return a ?? -1;
> }
> 
> return -1
> }
> ```

```
if (isNotNull(a.b)) {
  return a.b!;
}

return -1;
```

**Comment by ganeshrvel** [comment] 2020-07-16 14:15
@jodinathan is short circuiting the only way to fix this? People can make a mess out it.

**Comment by jodinathan** [comment] 2020-07-16 14:20
> @jodinathan is short circuiting the only way to fix this? People can make a mess out it.
> 
> look at this:
> 
> ```dart
> if (isNotNull(a.b) || (isNotNull(x) && (isNotNull(y) || isNotNull(z) && isNotNull(p)) && isNotNull(abc)) ) {
>   return a.b!;
> }
> ```

can you give more close to real world examples?

**Comment by eernstg** [comment] 2020-07-16 14:24
I think a useful approach is taking a snapshot of the value of a non-trivial expression in the case where it would be a bug anyway if that value is different when it's evaluated more than once:

```dart
class Person {
  final int? age;
  ...
  int getData() {
    ...
    var age = _person.age;
    if (age != null) return age;
    ...
}
```

When you have stored the expression result in a local variable you get promotion as well as a predictable semantics. Also, you may allow for that value to be stored in a register, which means that it's going to be a lot faster than reevaluating a non-trivial expression several times.

You can still do things like `assert(age == _person.age)` just before returning, if it is a serious bug for that value to change from the time where the snapshot was taken, and it doesn't seem likely to me that this kind of situation would actually work _correctly_ if we insist on evaluating the expression several times and using those different values blindly.

So the local variable isn't a bad idea, even if it may at times be a bit more verbose.

**Comment by eernstg** [comment] 2020-07-16 14:29
Anyway, @ganeshrvel, I think we should close this issue because the code behaves as intended. Please create a new issue in case something hasn't been fully resolved.

**Closed by eernstg** 2020-07-16 14:29 UTC

**Comment by jodinathan** [comment] 2020-07-16 14:50
@eernstg 

I guess that in this specific example, where the ```age``` is ```final```, the analyzer and the compiler could see it as a local final if the Person class is marked as ```@sealed```... no?

It would be a good step towards sealed classes.

**Comment by eernstg** [comment] 2020-07-16 14:55
When an instance variable is final there is a getter, but no setter. Nothing prevents you from overriding that getter and making it run arbitrary code, so this makes no difference for the correctness of promotion.

**Comment by eernstg** [comment] 2020-07-16 17:09
Forgot the `@sealed` classes: We don't have support for sealed classes in the language (yet), and the discipline which can be enforced using metadata like `@sealed` depends on mechanisms that aren't part of the language itself, and may not be present in all tools/configurations.

This generally means that the type system cannot rely on `@sealed` to mean anything specific. In particular, promotion cannot be allowed to occur based on the presence of `@sealed` on a class. If we were to make metadata like `@sealed` part of the language (such that all the associated constraints are guaranteed to be satisfied, in all situations) then we actually have a proper language mechanism, and in that case we might as well give it its own syntax.
