### ISSUE TITLE
Dart Analyzer Error: Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by fabriziocacicia** [dart-lang/sdk#38160] opened 2019-09-01 14:41 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
Internal problem: Unhandled ," in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1370:22)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4239:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#11     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#13     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5218:12)
#14     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3803:14)
#15     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#16     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#17     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3259:15)
#18     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#19     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#20     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#21     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#22     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#23     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#24     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#25     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#26     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#27     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#28     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#29     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:642:10)
#30     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#31     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#48     new Future.sync (dart:async/future.dart:224:31)
#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#55     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:...
```

For additional log information, please append the contents of
file:///private/var/folders/0q/jh77wwcx1cs989k89kv79mqr0000gn/T/report.txt.

```
1567348543034 <= {"event":"analysis.overrides","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","overrides":[{"offset":9498,"length":8,"su
1567348543037 <= {"event":"flutter.outline","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","outline":{"kind":"DART_ELEMENT","offset":0,"
1567348543042 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":965,"uri":"package:mobile_app/new_request/main_info/bloc/main_info_state.dart","items":[{"label":"MainIn
1567348543045 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1567348543045 <= {"event":"analysis.implemented","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","classes":[],"members":[]}}
1567348543375 => {"id":"12418","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","offset":9864,"length":24},"cli
1567348543379 <= {"id":"12418","result":{"assists":[]}}
1567348543547 => {"id":"12419","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart":{"type":"add","content
1567348543547 => {"id":"12420","method":"completion.getSuggestions","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","offset":9865},"clien
1567348543547 <= {"id":"12419","result":{}}
1567348543547 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1567348543562 <= {"id":"12420","result":{"id":"1999"}}
1567348543562 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","errors":[{"severity":"ERROR","type":"STATIC_
1567348543563 <= {"event":"completion.existingImports","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","imports":{"elements":{"strings":[
1567348543568 <= {"event":"completion.results","params":{"id":"1999","replacementOffset":9864,"replacementLength":1,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"hashCode","selectionO
1567348543574 <= {"event":"analysis.highlights","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","regions":[{"type":"DIRECTIVE","offset":0
1567348543574 <= {"event":"analysis.navigation","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","regions":[{"offset":7,"length":34,"targe
1567348543574 <= {"event":"analysis.outline","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","kind":"LIBRARY","outline":{"element":{"kind
1567348543574 <= {"event":"analysis.overrides","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","overrides":[{"offset":9498,"length":8,"su
1567348543576 <= {"event":"flutter.outline","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","outline":{"kind":"DART_ELEMENT","offset":0,"
1567348543579 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":965,"uri":"package:mobile_app/new_request/main_info/bloc/main_info_state.dart","items":[{"label":"MainIn
1567348543579 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1567348543580 <= {"event":"analysis.implemented","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","classes":[],"members":[]}}
1567348543614 => {"id":"12421","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart":{"type":"add","content
1567348543614 => {"id":"12422","method":"completion.getSuggestions","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","offset":9866},"clien
1567348543614 <= {"id":"12421","result":{}}
1567348543614 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1567348543626 <= {"id":"12422","result":{"id":"2000"}}
1567348543626 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/new_request/main_info/bloc/main_info_state.dart","errors":[{"severity":"ERROR","type":"SYNTACT
1567348543631 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Internal problem: Unhandled ,\" in analyzeQuote.\n#0      internalProblem (package:front
```

**Comment by srawlins** [comment] 2021-02-22 17:02
Thanks for reporting this issue. This was previously reported in https://github.com/dart-lang/sdk/issues/38156. Please follow along there.

**Comment by srawlins** [comment] 2021-02-22 17:02
Duplicate of https://github.com/dart-lang/sdk/issues/38156

**Closed by srawlins** 2021-02-22 17:02 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
