### ISSUE TITLE
Label package:js as "legacy"

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#54571] opened 2024-01-10 21:20 UTC
Now that we have `dart:js_interop` and `dart:js_interop_unsafe`, we should point users to these libraries instead. This can go as part of the README in `package:js` (or maybe somewhere on pub?). This does not mean this library is deprecated and users need to migrate over. That will be done at some future date that is not yet known.

This also aligns us with some of the changes to mark libraries as `Web (Legacy)` on https://api.dart.dev/stable/3.2.4/index.html.

**Comment by parlough** [comment] 2024-01-10 21:32
As a sort of related note, I've updated DartPad to provide a diagnostic on usages of `dart:js` to suggest users migrate. I'll be doing the same for `package:js` and `dart:js_util` soon, likely alongside the 3.3 release.

**Comment by kevmoo** [comment] 2024-01-10 21:33
@parlough – do we want to do a one-off in dartpad, or just use hint/lints in the analyzer?

**Comment by parlough** [comment] 2024-01-10 21:46
> @parlough – do we want to do a one-off in dartpad, or just use hint/lints in the analyzer?

Well it's not necessarily one-off as I previously added general support for deprecating packages that we want to drop as well as core libraries we don't support. However, if an analyzer warning or lint is added, we can easily switch over to that for versions of the SDK that support it. I'd be happy to help implement the lint if that's the desired direction.

A bit separate of a discussion as it's about the core libraries, but rather than a lint, I personally prefer an opt-in mode that the analyzer and web compilers can use to switch to an SDK outline without these libraries (https://github.com/dart-lang/sdk/issues/54347). That way they don't even show up in completion suggestions.

**Comment by parlough** [comment] 2024-01-31 22:57
Duplicate of https://github.com/dart-lang/sdk/issues/54792

I'm going to close this in favor of https://github.com/dart-lang/sdk/issues/54792 which outlines a specific path for doing this (a pub release with readme update).

Feel free to reopen if you think this issue is different enough. Thanks!

**Closed by parlough** 2024-01-31 22:57 UTC
Labels: web-js-interop, area-web
