### ISSUE TITLE
Create new dir, move files to new dir -> error

### ISSUE THREAD

**Issue by sanekyy** [dart-lang/sdk#38027] opened 2019-08-27 17:50 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6262.58`
- `2.5.0-edge.06d3769ac6d775ede7ca87e6ba2f056db93e2e27`
- `IU-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.06d3769ac6d775ede7ca87e6ba2f056db93e2e27, server version 1.27.2, error: FileSystemException(path=/Users/sanekyy/Projects/terra/admin-flutter/lib/service/client.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1500:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:332:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:328:50)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1500:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:327:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:185:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:175:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:118:26)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#...
```

For additional log information, please append the contents of
file:///private/var/folders/hx/klmbwq7j3wx1kzz491c_dt_00000gp/T/report.txt.

**Comment by srawlins** [comment] 2019-08-30 18:46
Thanks for reporting this issue! It looks like this has been previously reported at #36204; please follow along there.

**Comment by srawlins** [comment] 2019-08-30 18:46
Duplicate of #36204

**Closed by srawlins** 2019-08-30 18:46 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
