### ISSUE TITLE
[cfe] Inline class not yet handled by moretop, causes exception

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#51232] opened 2023-02-02 17:14 UTC
Consider the following program:

```dart
inline class A {
  final Object? value;
  const A.fromList(List<A> this.value);
}

void main() => A.fromList(['' as A, 1.5 as A]);
```

This program is accepted by the analyzer. With the CFE (`dart` from 5afdebf219e9161acd8255f3cda5bdcbee2dafba), the compilation stops with an unhandled exception.

<details><summary>Stack trace</summary>

```
Crash when compiling file:///usr/local/google/home/eernst/lang/dart/scratch/202301/n033.dart at character offset 93:
Unsupported operation: moretop(InlineType(A), InlineType(A))

#0      StandardBounds.moretop (package:kernel/src/standard_bounds.dart:124:5)
#1      StandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:kernel/src/standard_bounds.dart:659:42)
#2      TypeSchemaStandardBounds.getNullabilityAwareStandardUpperBoundInternal (package:front_end/src/fasta/type_inference/standard_bounds.dart:59:18)
#3      StandardBounds._getNullabilityAwareStandardUpperBound (package:kernel/src/standard_bounds.dart:642:12)
#4      StandardBounds.getStandardUpperBound (package:kernel/src/standard_bounds.dart:629:14)
#5      TypeSchemaEnvironment.addLowerBound (package:front_end/src/fasta/type_inference/type_schema_environment.dart:117:24)
#6      TypeSchemaConstraintGatherer.addLowerBound (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:1107:17)
#7      TypeConstraintGatherer.computeConstraints (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:82:9)
#8      TypeSchemaEnvironment._chooseTypes (package:front_end/src/fasta/type_inference/type_schema_environment.dart:524:18)
#9      TypeSchemaEnvironment.upwardsInfer (package:front_end/src/fasta/type_inference/type_schema_environment.dart:511:7)
#10     InferenceVisitorImpl.visitListLiteral (package:front_end/src/fasta/type_inference/inference_visitor.dart:2385:45)
#11     ListLiteral.accept1 (package:kernel/ast.dart:8684:9)
#12     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:261:27)
#13     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:296:40)
#14     InferenceVisitorBase._inferInvocation.inferArgument (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1763:22)
#15     InferenceVisitorBase._inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1827:44)
#16     InferenceVisitorBase.inferInvocation (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1518:12)
#17     InferenceVisitorImpl.visitStaticInvocation (package:front_end/src/fasta/type_inference/inference_visitor.dart:7444:40)
#18     StaticInvocation.accept1 (package:kernel/ast.dart:7013:9)
#19     InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:261:27)
#20     InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:296:40)
#21     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7274:11)
#22     ReturnStatement.accept (package:kernel/ast.dart:10766:43)
#23     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:239:26)
#24     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:196:17)
#25     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:1324:43)
#26     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:1123:19)
#27     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#28     Parser.parseTopLevelMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3682:14)
#29     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3424:14)
#30     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:606:14)
#31     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:403:15)
#32     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:1267:12)
<asynchronous suspension>
#33     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:676:7)
<asynchronous suspension>
#34     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:611:7)
<asynchronous suspension>
#35     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#36     _buildInternal (package:front_end/src/kernel_generator_impl.dart:206:19)
<asynchronous suspension>
#37     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#38     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:48:12)
<asynchronous suspension>
#39     generateKernel (package:front_end/src/kernel_generator_impl.dart:47:10)
<asynchronous suspension>
#40     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:100:11)
<asynchronous suspension>
#41     SingleShotCompilerWrapper.compileInternal (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:407:11)
<asynchronous suspension>
#42     Compiler.compile.<anonymous closure> (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:215:45)
<asynchronous suspension>
#43     _processLoadRequest (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/vm/bin/kernel_service.dart:889:37)
<asynchronous suspension>
```

</details>

**Comment by chloestefantsova** [comment] 2023-10-17 10:26
The syntax of the feature has changed since the issue was published, but the following rewrite of the reproduction example seem to not provoke the exception.

```dart
extension type A(Object? value) {
  const A.fromList(List<A> this.value);
}

void main() => A.fromList(['' as A, 1.5 as A]);
```

So, I'm closing the issue. Please reopen if needed.

**Closed by chloestefantsova** 2023-10-17 10:26 UTC
Labels: type-bug, area-front-end, feature-inline-classes, cfe-feature-extension-types
