### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by Purlible** [dart-lang/sdk#34996] opened 2018-10-31 10:40 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4323.46`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IU-182.4323.46, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.1 unknown, screens 2048x1152  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/ln/7vldwb4j37z_btdp2lp2qhc40000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/metro/Desktop/flutter/cashloan/lib/franchised/franchisedDetail.dart
Exception: Element not found in summary: package:cashloan/franchised/franchisedDetail.dart

**Comment by stereotype441** [comment] 2018-10-31 16:42
Duplicate of #34555

**Closed by stereotype441** 2018-10-31 16:42 UTC
Labels: area-analyzer

**Comment by Purlible** [comment] 2018-11-01 02:10
thanks , resolved
