### ISSUE TITLE
UnmodifiableMapBase documentation is incomplete

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#28917] opened 2017-02-28 11:13 UTC
See https://api.dartlang.org/stable/1.22.1/dart-collection/UnmodifiableMapBase/addAll.html, etc.

UnmodifiableMapBase API Spec reads about addAll method: 

> Adds all key-value pairs of other to this map. If a key of other is already in this map, its value is overwritten.

However, actually UnmodifiableMapBase objects cannot be modified and addAll method throws UnsupportedError("Cannot modify unmodifiable map").

The same is true about clear, putIfAbsent, remove methods.

**Comment by anders-sandholm** [comment] 2017-02-28 11:54
Duplicate of #28917

**Closed by anders-sandholm** 2017-02-28 11:54 UTC
