### ISSUE TITLE
Only a single libraries.{json,yaml} for configuring the SDK

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#31453] opened 2017-11-24 18:18 UTC
(If this is documented somewhere and I missed it, apologies)

I was doing some playing around in the `sdk`, and found the following files:

* [lib][]/dart_{client,server,shared}.platform
* [lib][]/libraries.{json,yaml}
* [lib][]/vmservice_libraries.{json,yaml}
* [lib][]/[_internal][]/[sdk_library_metadata][]/lib/libraries.dart

[lib]: https://github.com/dart-lang/sdk/tree/master/sdk/lib
[_internal]: https://github.com/dart-lang/sdk/tree/master/sdk/lib/_internal
[sdk_library_metadata]: https://github.com/dart-lang/sdk/tree/master/sdk/lib/_internal/sdk_library_metadata

In the final resulting `libexec` in a built-sdk, there are other files too... but maybe start here :)

**Comment by lrhn** [comment] 2017-11-27 06:30
I can only talk about libraries.dart. It was intended as a single repository for library information, sufficient for dart2js and the VM to figure out where their libraries *and* their patches were located. It was introduced around the same time as patch files, and we wanted anyone who needed to introduce or change a patched file to have a way to find the patches.
The format was chosen as a simple Dart structure that the VM could parse easily, and Dart2js could import as data.

It was apparently not sufficient for all tasks, so other tools introduced their own summary files that cover other data. (Or the same, I actually don't know, I'm expecting each of them to be tool specific.)

**Comment by sigmundch** [comment] 2017-11-27 19:17
We are in the process of unifying them with the common front end (CFE). See also https://github.com/dart-lang/sdk/issues/28836.  I have a design doc explaining the new libraries.{json,yaml} format that I can share with you. The idea is that this will become the source of truth. The CFE is now using them.

The `*.platfrom` files were introduced for dart2js a few years ago (before I was on the team). We will be dropping those and use the .json format instead. If we do it now, we'd have to port some code, if we do it after we switch to the CFE, then we just need to delete them and delete some code. We might end up doing so. These files used a custom .ini format, we rather use a format that is supported out of the box, like .json.

Finally `libraries.dart` used to be consumed by dart2js, and it is currently used by analyzer, and a tool that preprocessed sdk lirbaries to merge patch files (initially used by ddc, and later as a stop gap to get the CFE off the ground). After the CFE finishes getting support for patch files and DDC migrates off to use CFE, our plan is to update analyzer to use the .json format and remove the libraries.dart. In the end, this input data will be in a data format, which simplifies how tools can use them for other purposes.

The original goal that @lrhn stays true: we should have a single place to maintain libraries.

**Comment by matanlurey** [comment] 2017-11-27 20:31
Hey, that's really good information, thanks both.

So if I understand correctly, in Dart.next we will only have a single libraries.{json,yaml} file?

**Comment by sigmundch** [comment] 2017-11-27 23:11
exactly :)

That's what I'd like.

**Comment by sigmundch** [comment] 2017-11-29 21:57
Seems to me that we can close it as a duplicate of #28836 - @matanlurey does that seem OK with you?

**Comment by jensjoha** [comment] 2018-01-05 11:52
*ping* on the "can close?" question.

**Closed** 2018-01-05 15:01 UTC
Labels: area-front-end
