### ISSUE TITLE
[CP][stable channel] ec48e8f - DDC: Fix missing nullability from recursive type hierarchies

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#45907] opened 2021-05-04 20:21 UTC
**commit(s) to merge**: ec48e8f323d68717cd3fed94abd85d4f82ea1ce7

**merge instructions**: clean merge

**What is the issue**: DDC uses a different code path when compiling mixins or extends clauses that lead to a circular reference of the class itself. That code path was losing nullability information (nullable, or legacy) of the types when they appear in those positions.

**What is the fix**: Stop ignoring the nullability and emit them properly in those code patterns.

**Why cherrypick**: This is a correctness issue, mostly noticeable when running in sound null safety mode. The bug has been present since we unforked the SDK but it was noticed and reported recently by an external Flutter Web user. 

**Risk**: Low risk because the fix targets a code path that is only used by circular class hierarchies and then the hierarchy must include a nullable type for the change to make any difference.

**Link to original  issue(s)**: https://github.com/dart-lang/sdk/issues/45767

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon @franklinyow @sigmundch

**Comment by sigmundch** [comment] 2021-05-04 21:12
@leafpetersen - we are curious to hear your thoughts on the severity of the issue here.

I'm ambivalent this time around. I agree it's low risk and I'd have gone for it a couple weeks back, but given the higher bar for cherry-picking at this time, I'm inclined to wait for the next release and not cherry-pick.

**Comment by leafpetersen** [comment] 2021-05-04 23:47
I'm still supportive of a cherry pick.  The change is DDC only, so the risk is highly ring-fenced.  The problem is somewhat esoteric, but it was found organically, and if I understand correctly this bug will be more likely to surface as apps turn on sound null safety.

**Comment by franklinyow** [comment] 2021-05-05 19:28
CC: @kf6gpe

**Comment by kf6gpe** [comment] 2021-05-06 15:19
Are we discussing this for Dart 2.13 beta? If so, the window opens again om the week of 5/21. Can we wait that long given the fact that it's an esoteric case? Or hotfix in Dart and pick it up in Flutter when we hotfix Flutter that week?

**Comment by franklinyow** [comment] 2021-05-06 17:26
Discussed in SCURM meeting.  This can wait until 5/12.  We are approving this for **5/21 window**

I will update the label and title in a later date.

**Comment by franklinyow** [comment] 2021-05-18 22:22
Description:
Fix missing nullability from recursive type hierarchies, see #45767 for detail

**Comment by athomas** [comment] 2021-05-21 10:47
Merged to stable 375a2d7c66c8eb5d40872bdb57dd664b5f850d94 (2.13.1).

**Closed by athomas** 2021-05-21 10:47 UTC
Labels: area-infrastructure, cherry-pick-review, cp-approved, merge-to-stable
