### ISSUE TITLE
CFE bug on override inference and field inference combo

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#32412] opened 2018-03-05 11:20 UTC
The following runs correctly on DDC but breaks on DDK.  With `B.foo` on CFE, it appears that the static type is `Iterable<String>` but the runtime type is `List<dynamic>`.  If I add the explicit type on `B.foo` (instead of relying on override inference), the runtime type is `List<String>`.

```
abstract class A {
  Iterable<String> get foo;
}

class B implements A {
  final foo = const [];
}

void main() {
  var b = new B();
  print(b.foo);
  print(b.foo.runtimeType);
  assert(b.foo is Iterable<String>);
}
```

@a-siva is hitting this running `package:test`.

@kmillikin

**Comment by a-siva** [comment] 2018-03-05 11:22
We hit this bug originally on one of flutter's test runs and so bumping the priority as we need the tests to pass.

**Comment by kmillikin** [comment] 2018-03-06 15:19
You are right, we are inferring `Iterable<String>` for the type of the field but inferring `dynamic` for the type argument on the literal:

```dart
class B extends core::Object implements self::A {
  final field core::Iterable<core::String> foo = const <dynamic>[];
  synthetic constructor •() → void
    : super core::Object::•()
    ;
}
```

@stereotype441 can you take a quick look at this?  cc/ @stefantsov

**Comment by stereotype441** [comment] 2018-03-06 16:03
I've reproduced this, and I see the crux of the problem: in BodyBuilder.finishFields, we are passing a type context down when `field.hasImplicitType` is `false`.  This is insufficient--we also need to pass a context down when `field.hasImplicitType` is `true`, but a type was inferred via inheritance.

I'm at the end of my work day in Aarhus--I'll work on a fix tomorrow.

**Comment by dgrove** [comment] 2018-03-07 08:54
Moved milestone since the workaround has been committed.

**Comment by stereotype441** [comment] 2018-03-07 09:53
Fix is out for review: https://dart-review.googlesource.com/c/sdk/+/45520

**Closed** 2018-03-07 11:49 UTC
Labels: P1 high, area-front-end
