### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by fabryx92** [dart-lang/sdk#38604] opened 2019-09-26 23:44 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.6603.19`
- `2.5.0`
- `WS-192.6603.19, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0, server version 1.27.2, error: Analysis failed: /Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/web/main.dart context: exception_20190927_014221_761
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:666:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:384:56)
#3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:351:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:243:14)
#6      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:154:12)
#7      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#19     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#25     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#28     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#29     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#37     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#38     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#39     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#40     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#41     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
1569541309858 => {"id":"254","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml":{"type":"add","content":"name: admin_dashboard_web
1569541309858 <= {"id":"254","result":{}}
1569541309858 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541309861 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1569541311000 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml","errors":[]}}
1569541311134 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541311164 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1569541311323 => {"id":"255","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml":{"type":"remove"}}},"clientRequestTime":1569541311
1569541311324 <= {"id":"255","result":{}}
1569541311324 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541311326 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1569541319843 => {"id":"256","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml":{"type":"add","content":"name: admin_dashboard_web
1569541319844 <= {"id":"256","result":{}}
1569541319845 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541319853 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1569541321305 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml","errors":[]}}
1569541321389 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541321439 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1569541321548 => {"id":"257","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml":{"type":"remove"}}},"clientRequestTime":1569541321
1569541321549 <= {"id":"257","result":{}}
1569541321550 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541321551 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1569541337840 => {"id":"258","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml":{"type":"add","content":"name: dev\ndescription: A
1569541337842 <= {"id":"258","result":{}}
1569541337843 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541337847 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1569541341589 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml","errors":[]}}
1569541341672 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1569541341680 => {"id":"259","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/pubspec.yaml":{"type":"remove"}}},"clientRequestTime":1569541341
1569541341788 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/fabryx/Work/TiAssisto/admin_dashboard_web/dev/web/main.dart context: exception_20190927_014221_761
```

**Comment by srawlins** [comment] 2019-11-04 16:23
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37394; please follow along there.

**Comment by srawlins** [comment] 2019-11-04 16:23
Duplicate of https://github.com/dart-lang/sdk/issues/37394

**Closed by srawlins** 2019-11-04 16:23 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
