### ISSUE TITLE
[ERROR] dartanalyzer unhandled exception 'nullabilitySuffix'

### ISSUE THREAD

**Issue by KohlsAdrian** [dart-lang/sdk#45353] opened 2021-03-17 14:53 UTC
I have migrated 3 of my packages to pub.dev, 2 have succeeded and only 1 has addressed issues and I don't seem to find a fix for it

The package uses only Dart code (0% flutter): https://github.com/KohlsAdrian/google_maps_utils

`Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "macos_x64"`

The error addressed by pub.dev scoring system:
`dartanalyzer exception: NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.`

The error running `dartanalyzer .` locally:

```
$ dartanalyzer .
Analyzing google_maps_utils...
Unhandled exception:
NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.
Receiver: null
Tried calling: nullabilitySuffix
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:51:29)
#2      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1162:27)
#3      TypeSystemImpl.isSubtypeOf (package:analyzer/src/dart/element/type_system.dart:1158:12)
#4      TypeSystemImpl._refineNumericInvocationContextNullSafe (package:analyzer/src/dart/element/type_system.dart:1713:11)
#5      TypeSystemImpl.refineNumericInvocationContext (package:analyzer/src/dart/element/type_system.dart:1402:14)
#6      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:862:24)
#7      InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:326:15)
#8      InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:367:7)
#9      InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:345:7)
#10     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:239:5)
#11     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:811:24)
#12     MethodInvocationResolver._resolveReceiverTypeLiteral (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:712:9)
#13     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:127:9)
#14     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:394:31)
#15     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#16     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1706:10)
#17     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7186:49)
#18     ResolverVisitor.visitConditionalExpression (package:analyzer/src/generated/resolver.dart:1134:22)
#19     ConditionalExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:2265:15)
#20     VariableDeclarationResolver.resolve (package:analyzer/src/dart/resolver/variable_declaration_resolver.dart:58:17)
#21     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:2016:34)
#22     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10555:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#24     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10661:16)
#25     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#26     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3485:7)
#27     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:2048:11)
#28     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10655:15)
#29     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10709:20)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#31     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3489:7)
#32     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10705:15)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#34     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#35     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#36     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#37     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#38     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#39     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#40     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#41     ForResolver._resolveBody (package:analyzer/src/dart/resolver/for_resolver.dart:181:17)
#42     ForResolver._forEachParts (package:analyzer/src/dart/resolver/for_resolver.dart:148:5)
#43     ForResolver.resolveStatement (package:analyzer/src/dart/resolver/for_resolver.dart:45:7)
#44     ResolverVisitor.visitForStatementInScope (package:analyzer/src/generated/resolver.dart:1377:18)
#45     ScopedVisitor.visitForStatement (package:analyzer/src/generated/resolver.dart:2764:7)
#46     ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4707:49)
#47     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#48     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#49     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#50     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#51     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#52     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#53     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#54     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#55     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:1561:7)
#56     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#57     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#58     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#59     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#60     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#61     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#62     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#63     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#64     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#65     ForResolver._resolveBody (package:analyzer/src/dart/resolver/for_resolver.dart:181:17)
#66     ForResolver._forEachParts (package:analyzer/src/dart/resolver/for_resolver.dart:148:5)
#67     ForResolver.resolveStatement (package:analyzer/src/dart/resolver/for_resolver.dart:45:7)
#68     ResolverVisitor.visitForStatementInScope (package:analyzer/src/generated/resolver.dart:1377:18)
#69     ScopedVisitor.visitForStatement (package:analyzer/src/generated/resolver.dart:2764:7)
#70     ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4707:49)
#71     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#72     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#73     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#74     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#75     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#76     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#77     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#78     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2970:7)
#79     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:1576:7)
#80     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5705:49)
#81     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#82     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1087:17)
#83     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#84     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#85     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2480:13)
#86     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3076:8)
#87     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2479:5)
#88     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1083:49)
#89     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1042:13)
#90     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#91     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#92     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2489:13)
#93     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:957:13)
#94     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1038:49)
#95     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7042:12)
#96     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1750:10)
#97     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3351:55)
#98     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:2926:11)
#99     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2919:7)
#100    ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1666:11)
#101    MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7033:49)
#102    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7611:20)
#103    ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:2550:18)
#104    ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2531:7)
#105    ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:1015:13)
#106    ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1536:49)
#107    ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1091:23)
#108    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2134:49)
#109    LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:709:10)
#110    LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:139:7)
#111    _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#112    LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:138:11)
#113    LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:12)
#114    AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1319:63)
#115    PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#116    AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#117    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#118    _rootRun (dart:async/zone.dart:1354:13)
#119    _CustomZone.run (dart:async/zone.dart:1258:19)
#120    _runZoned (dart:async/zone.dart:1788:10)
#121    runZoned (dart:async/zone.dart:1710:10)
#122    NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#123    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#124    AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1374:41)
#125    AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:981:20)
#126    AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1349:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1296:20)
#3      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1249:14)
#4      _rootRun (dart:async/zone.dart:1354:13)
#5      _CustomZone.run (dart:async/zone.dart:1258:19)
#6      _runZoned (dart:async/zone.dart:1788:10)
#7      runZoned (dart:async/zone.dart:1710:10)
#8      NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#9      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1248:40)
#10     AnalysisDriver._computeErrors (package:analyzer/src/dart/analysis/driver.dart:1374:41)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:981:20)
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2018:24)
<asynchronous suspension>```

**Comment by DebkanchanSamadder** [comment] 2021-03-17 15:01
#https://github.com/dart-lang/sdk/issues/45052

**Comment by devoncarew** [comment] 2021-03-17 15:50
Likely dupe of https://github.com/dart-lang/sdk/issues/45052.

**Closed by devoncarew** 2021-03-17 15:50 UTC
Labels: area-analyzer
