### ISSUE TITLE
NNBD: dart throws unexpected _boundsCheckForPartialInstantiation exception when assign generic function typedef variable.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41939] opened 2020-05-18 06:07 UTC
Dart VM version: 2.9.0-9.0.dev (dev) (Wed May 13 09:32:20 2020 +0200) on "windows_x64"

The following source code sample throws unexpected _boundsCheckForPartialInstantiation exception:
``` dart
void checkme<T extends int>(T? t) {}

typedef void Test<T>(T? t);

main() {
  Test<int> t = checkme;
}
```
Sample output is:
> Unhandled exception:
> type 'int?' is not a subtype of type 'int' of 'T'
> #0      _boundsCheckForPartialInstantiation (dart:_internal-patch/internal_patch.dart:114:57)
> #1      main (file:///D:/DART/sdk/tests/co19/src/Language/Generics/test.dart)
> #2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
> #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Please note that the following code throws the same:
``` dart
void checkme<T extends dynamic>(T? t) {}

typedef void Test<T>(T? t);

main() {
  Test<int> t = checkme;
}
```
whereas the following one passes without any errors or warnings:
``` dart
void checkme<T>(T? t) {}

typedef void Test<T>(T? t);

main() {
  Test<int> t = checkme;
  print(t);
}
```
Sample output is:
> Closure: (int?) => void from Function 'checkme': static.

**Comment by mkustermann** [comment] 2020-05-18 15:00
@crelier Maybe you want to take a look at this?

/cc @alexmarkov

**Comment by crelier** [comment] 2020-05-18 23:27
The second example (using `dynamic` as the bound) fails because the VM wrongly maps `dynamic` to non-nullable `Object` rather than to nullable `Object?`. A [CL](https://dart-review.googlesource.com/c/sdk/+/148515) is on its way to fix that issue and to add a regression test.

Now regarding the first example (using `int` as the bound):

In the assignment to `Test<int> t`, CFE infers the type argument `T` in the tearoff of `checkme` to `int?`
Here is the kernel file:

```
  typedef Test<contravariant T extends core::Object? = dynamic> = (T?) → void;
  static method checkme<T extends core::int = core::int>(bug::checkme::T? t) → void {}
  static method main() → dynamic {
    (core::int?) → void t = #C1<core::int?>;
  }
```

This leads to the failed bound check.
Can someone on the CFE team have a look at this inference that does not look correct to me? @johnniwinther or @stefantsov ?

**Comment by johnniwinther** [comment] 2020-05-19 15:12
This is probably related to #41447

**Comment by crelier** [comment] 2020-06-11 18:35
Closing this issue since the VM was fixed earlier and the remaining error is due to #41447.

**Closed by crelier** 2020-06-11 18:35 UTC
Labels: NNBD, area-front-end
