### ISSUE TITLE
ia32 segmentation fault in malbounded_type_cast_test

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35473] opened 2018-12-21 12:54 UTC
([log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8926574613708594544/+/steps/vm_tests_shard_2/0/stdout))

Running a 100 repeats did not reproduce this crash.

```dart
FAILED: dartk-vm release_ia32 language_2/malbounded_type_cast_test/00
Expected: Pass
Actual: Crash
Missing expected compile error.

--- Command "vm" (took 666ms):
DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --optimization-counter-threshold=5 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseIA32/generated_tests/language_2/malbounded_type_cast_test_00.dart

exit code:
-6

stderr:
===== CRASH =====
version=2.2.0-edge.8dea340fdad6ef83c302eef26e3d09e2c812b97b (Fri Dec 21 00:12:01 2018 +0000) on "linux_ia32"
si_signo=Segmentation fault(11), si_code=1, si_addr=0x2b
thread=15596, isolate=vm-service(0x35d8100)
  [0xf541e964] Unknown symbol
  [0xf541e964] Unknown symbol
  [0xf541e6b9] Unknown symbol
  [0xf541e54c] Unknown symbol
  [0xf541e4ac] Unknown symbol
  [0xf541e40c] Unknown symbol
  [0xf541e351] Unknown symbol
  [0xf541e1b0] Unknown symbol
  [0xf541189d] Unknown symbol
  [0xf63d368f] Unknown symbol
  [0xf5410daf] Unknown symbol
  [0xf5410424] Unknown symbol
  [0xf540fb42] Unknown symbol
  [0xf540cb2f] Unknown symbol
  [0xf63f09a0] Unknown symbol
  [0xf63ee832] Unknown symbol
  [0xf63ede5f] Unknown symbol
  [0xf63d6b12] Unknown symbol
  [0xf63d6a52] Unknown symbol
  [0xf7240b33] Unknown symbol
  [0x013cba21] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
  [0x013cb5f7] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  [0x013ce71d] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x013f53fd] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x01420912] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x01420f41] dart::MessageHandler::TaskCallback()
  [0x014216d7] Unknown symbol
  [0x01534321] dart::ThreadPool::Worker::Loop()
  [0x015341ee] dart::ThreadPool::Worker::Main(unsigned int)
  [0x014a9c63] Unknown symbol
  [0xf7791f72] Unknown symbol
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -n dartk-optcounter-linux-release-ia32 language_2/malbounded_type_cast_test/00
```

**Comment by crelier** [comment] 2018-12-21 20:05
I am not able to reproduce this issue either. Note that the problem is most probably not related to the tested feature (type cast of malbounded types), since the reported crash occurred in multitest '00', which does not even run, since it correctly ends in a compile time error. The 'none' variant runs the tested code, and embedding main in a loop so that the optimizing compiler kicks in makes no difference. No assertion faults in debug mode either.
Note also that the sig fault is reported in the vm-service isolate.
My guts feeling tells me this has something to do with error reporting (compile-time error) in the test harness.

**Comment by crelier** [comment] 2019-01-07 20:40
Closing this issue, since it is not reproducible and has not reoccurred on the bots.

**Closed by crelier** 2019-01-07 20:40 UTC
Labels: area-vm, crash, gardening
