### ISSUE TITLE
Dart Compiler Crash

### ISSUE THREAD

**Issue by alkebuware** [dart-lang/sdk#30557] opened 2017-08-26 13:14 UTC
OS Version: Windows 10 Pro 1703

Dart VM Version: Dart VM version: 1.24.2 (Thu Jun 22 08:55:56 2017) on "windows_x64"

uild completed successfully
[web] GET Served 11 cached assets.
[Info from Dart2JS]:
Compiling blog_title_generator|web/main.dart...
[Error from Dart2JS]:
web\main.dart:
The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on blog_title_generator|web/main.dart threw error: The getter 'isStatic' was called on null.
Receiver: null
Tried calling: isStatic
dart:core                                                         Object.noSuchMethod
package:compiler_unsupported/src/universe/world_builder.dart 744  ResolutionWorldBuilderImpl.registerStaticUse.<fn>
dart:collection                                                   _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent
package:compiler_unsupported/src/universe/world_builder.dart 743  ResolutionWorldBuilderImpl.registerStaticUse
package:compiler_unsupported/src/enqueue.dart 254                 ResolutionEnqueuer.processStaticUse
package:compiler_unsupported/src/enqueue.dart 467                 TreeShakingEnqueuerStrategy.processStaticUse
package:compiler_unsupported/src/enqueue.dart 509                 EnqueuerImplImpactVisitor.visitStaticUse
dart:collection                                                   _HashFieldBase&_HashBase&_OperatorEqualsAndHashCode&SetMixin.forEach
package:compiler_unsupported/src/util/setlet.dart 224             Setlet.forEach
package:compiler_unsupported/src/universe/world_impact.dart 39    WorldImpact.apply
package:compiler_unsupported/src/universe/world_impact.dart 268   ImpactStrategy.visitImpact
package:compiler_unsupported/src/enqueue.dart 180                 ResolutionEnqueuer.applyImpact
package:compiler_unsupported/src/compiler.dart 649                Compiler.compileLoadedLibraries.<fn>
package:compiler_unsupported/src/common/tasks.dart 176            CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 603                Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 511                Compiler.runInternal.<fn>
Build completed with 2 errors.
[web] GET main.dart.js => (cached) blog_title_generator|web/index.html

**Comment by sigmundch** [comment] 2017-08-29 00:04
@alkebuware - thanks for filing the bug!

We might need some help to figure out where this issue is coming from. By any chance do you some code we can use to reproduce the problem? (a small example would be best, but if you have an app that is available open source that is showing this issue, that would help too).  Thanks!

**Comment by natebosch** [comment] 2018-09-06 01:32
Closing since we haven't had a repro case and dart2js is using a different frontend now.

**Closed by natebosch** 2018-09-06 01:32 UTC
Labels: area-dart2js, needs-info
