### ISSUE TITLE
Generic type doesn't work

### ISSUE THREAD

**Issue by devteam-tchs** [dart-lang/sdk#44943] opened 2021-02-10 13:48 UTC
I'm using `Dart SDK version: 2.10.5 (stable)` (Mac)

I'm trying to specify a function parameter as a generic type T:

```
enum MyEnum {
  Foo,
  Bar
}

class DbColumn {
  final Function<T>(T value) serializer;
  const DbColumn({this.serializer});
}

class MyClass {

  static final DbColumn rating = DbColumn(
    serializer: <MyEnum>(v) {
      var i = v.index;
    }
  );
}
```

However when trying to access `v.index` I get this error message:

`The getter 'index' isn't defined for the type 'Object'. Try importing the library that defines 'index', correcting the name to the name of an existing getter, or defining a getter or field named 'index'.`

When I hover over `v` in VSC it says that it's of type `MyEnum`.

If I instead remove the generic type and do a cast like this it works as expected:

```
class DbColumn {
  final Function(dynamic value) serializer;
  const DbColumn({this.serializer});
}

class MyClass {
  static final DbColumn rating = DbColumn(
    serializer: (v) {
      var casted = v as MyEnum;
      var i = casted.index;
    }
  );
}
```

The same scenario using generic type works if I do it this way:

```
class MyClass {

  x<T>(Function(T) c) {}

  y() {
    x<MyEnum>((v) {
      print(v.index); // No error given and type of v is MyEnum
    });
  }
}
```

I suspect this is a bug that has something to do with the analyzer, but I could be wrong.

**Comment by eernstg** [comment] 2021-02-10 14:21
(I can see that the code is running without null safety, because the error message says `Object` rather than `Object?`. So let's go from there.)

In your first example, `<MyEnum>(v) { var i = v.index; }` is a function literal of type `dynamic Function<X>(X)`. `X` is a type parameter with no bound, so the assumed bound is `Object` (it would be `Object?` with null safety), and hence `v.index` is an error because `Object` doesn't have a member named `index` (and that's still an error with null safety).

You shouldn't use the name `MyEnum` when you declare a type parameter, because it's likely that a reader of the code will think that it is somehow connected to `enum MyEnum`.

You probably meant something like this:

```dart
enum MyEnum {
  Foo,
  Bar
}

class DbColumn<F extends Function(Never)> {
  final F serializer;
  const DbColumn({this.serializer});
}

class MyClass {

  static final DbColumn rating = DbColumn<Function(MyEnum)>(
    serializer: (v) {
      var i = v.index;
    }
  );
}
```

Note that we don't just make `T` a type argument of `DbColumn`: It would then be used contravariantly, and that's only supported in a statically checked manner when we introduce sound variance (cf. https://github.com/dart-lang/language/issues/524).

**Comment by eernstg** [comment] 2021-02-10 14:28
@devteam-tchs, I'll close this issue because I don't see anything that doesn't work as intended, but please create new issues as needed if you encounter any bugs.

**Closed by eernstg** 2021-02-10 14:28 UTC
