### ISSUE TITLE
Implement additional lint fixes in dart fix.

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#47886] opened 2021-12-09 22:09 UTC
As a user of dart-code in vscode I love the new feature that automatically fixes lints when you save a file.
This is a real timesaver.

I would like to see the fixes applied to a larger set of lints.
Essentially all lints that are enabled for which an unambiguous fix is available.

I would also like to see cascading of fixes.
I common one is: (at this point is the only one I can think of).
* prefer final
* prefer const

Here is a list of the lints that I think are unambiguous:

* Unnecessary {} in string.
* sort constructors.
* use raw string to avoid escapes.
* Type annotate public APIs.
* Separate the control structure expression from its statement.
* Cascade consecutive method invocations on the same reference.
* unnecessary_import
* sort dependencies in pubspec.yaml
* Use => for short members whose body is a single return statement.
* Prefer relative imports for files in lib/.

**Comment by bwilkerson** [comment] 2021-12-09 22:51
> Essentially all lints that are enabled for which an unambiguous fix is available.

That's our goal. Thanks for the list; I'll take a look at them to assess which ones we can add.

> I would also like to see cascading of fixes.

I think what you mean by that is that additional fixes should be applied after the first round of fixes have been applied. If so, we now have that capability in the `dart fix` command. I'm not sure how the fix-on-save feature is implemented, but we ought to be able to provide the same support there. @DanTup for visibility.

**Comment by DanTup** [comment] 2021-12-09 23:10
The Fix All command in LSP [calls the BulkFixProcessor for a single file](https://github.com/dart-lang/sdk/blob/1777f769abc9ea7f2a7e2c70c3e1635a838bc199/pkg/analysis_server/lib/src/lsp/handlers/commands/fix_all.dart#L55) (running is on-save is just generic VS Code functionality that lets you run any Source Code-Action on-save, like Sort Members etc).

What is required to run it iteratively? I can't find anything obvious. Can it be done without applying the first round of changes to the files (eg. produce a single set of edits that applies all iterations)?

**Comment by bsutton** [comment] 2021-12-09 23:38
Some more

Avoid async functions that return void.
The import of 'package:dcli/dcli.dart' is unnecessary because all of the used elements are also provided by the import of 'package:dcli/dcli.dart'.


Could strings that cause a line to break the 80 rule be broken up.
This point of break would be a little more arbitrary than if a human did it. But the reality is when I do it the point is fairly arbitrary anyway. I do try to break after a space, a period or before a nested quote.
For comments then just break at a space.

**Comment by bsutton** [comment] 2021-12-10 04:52
Another one:
leading_newlines_in_multiline_strings

**Comment by bwilkerson** [comment] 2021-12-10 16:17
> What is required to run it iteratively?

Sorry, I had forgotten about the Fix All command. The iteration is currently in the [implementation of the `dart fix` command](https://github.com/dart-lang/sdk/blob/main/pkg/dartdev/lib/src/commands/fix.dart#L117-L131).

We might want to look into moving that code into the analysis_server package so that it can be shared. I'm not sure it's feasible because the FixAll command is implemented inside a running server while the `dart fix` command is communicating with a server running in a separate process. We might need to change the `dart fix` command to start the server in-process before the code can be shared, and that sounds like a significant change.

**Comment by DanTup** [comment] 2021-12-10 16:49
Ah, I see. It looks like that works by applying the changes to the servers overlays (calling `server.updateContent`) and then doing the next iteration. I'm not sure that's reasonable in the main server process (because the overlays must match what's in the client, and there's no guarantee if or when the computed edits would be applied).

Is there any existing mechanism we could use to create another layer of overlays while computing the fixes and then run them again over that?

Do you have an idea of how common it is to need to apply multiple layers like this?

**Comment by bwilkerson** [comment] 2021-12-10 17:25
Based on an examination of the code, I found the following. The tl;dr is that several of these appear to already be bulk fixable, but there's definitely some opportunity to provide fixes for many of these lints. Again, thanks for letting us know which are most important to you; we can use that to help prioritize the work.

Note that I looked at the code on `main`, not the code for the most recent stable or even dev release, so if the code says that a fix can be applied in bulk but the tool doesn't currently apply it, then it could either be because of a bug, because the change to enable it hasn't yet made it though the pipeline, or because the fix doesn't (or can't) handle a specific use case. It's probably worth opening specific issues for these cases so that we can get specifics about the code pattern that isn't being fixed.

Also, if a lint doesn't have a fix I have included any information I have about what it would take to implement a fix. That sometimes includes problems that need to be solved. The description of a problem should not be taken to mean that we can't or won't implement a fix. It's just information for future use.

- prefer final

There are three lints that I found that you might be referring to: `prefer_final_in_for_each`, `prefer_final_locals`, and `prefer_final_parameters`. All three have the same fix associated with them, and that fix is already enabled for use in bulk fixes.

- prefer const

There are four lints that I found that you might be referring to: `prefer_const_constructors`, `prefer_const_constructors_in_immutables`, `prefer_const_declarations`, and `prefer_const_literals_to_create_immutables`. All three have at least one fix associated with them, and those fixes are already enabled for use in bulk fixes.

- Unnecessary {} in string.

I think you mean `unnecessary_brace_in_string_interps`, which can already be bulk fixed.

- sort constructors.

There are two lints that I found that you might be referring to: `sort_constructors_first` and `sort_unnamed_constructors_first`. Neither of these currently has a fix associated with it. The server does support a "Sort Members in File" operation, but that sorts more than constructors, so we'd need to have a more limited version of the code if we want to only sort constructors.

- use raw string to avoid escapes.

I think you mean `use_raw_strings`, which does not currently have a fix.

- Type annotate public APIs.

I think you mean `type_annotate_public_apis`, which can already be bulk fixed.

- Separate the control structure expression from its statement.

I think you mean `always_put_control_body_on_new_line`, which does not currently have a fix.

- Cascade consecutive method invocations on the same reference.

I think you mean `cascade_invocations`, which does not currently have a fix.

- unnecessary_import

This is supported for bulk fixes, but only when there are no other fixes to be applied. I can go into the reason for this, but it was one of the primary reasons for the recent change to make `dart fix` be iterative. After all of the other fixes are applied we now run a final phase that can clean up unnecessary imports. From the IDE, at the moment, you'd currently need to manually run Fix All multiple times in order to get the same results.

- sort dependencies in pubspec.yaml

I think you mean `sort_pub_dependencies`, which does not currently have a fix.

- Use => for short members whose body is a single return statement.

I think you mean `prefer_expression_function_bodies`, which can already be bulk fixed.

- Prefer relative imports for files in lib/.

I think you mean `prefer_relative_imports`, which can already be bulk fixed.

- Avoid async functions that return void.

I think you mean `avoid_void_async`, which does not currently have a fix.

- The import of 'package:dcli/dcli.dart' is unnecessary because all of the used elements are also provided by the import of 'package:dcli/dcli.dart'.

I think you mean `unnecessary_import`, which is discussed above.

- leading_newlines_in_multiline_strings

This does not currently have a fix.

> Could strings that cause a line to break the 80 rule be broken up.
> ...
> For comments then just break at a space.

That's an interesting one, and one we've talked about several times in the past.

The biggest problem with breaking string literals is that doing so can interact with the way the formatter formats the code such that the string needs to be broken up differently than what we might have first guessed. Getting a single stable fix would require iterating between breaking the string and running the formatter, but only for users that use the formatter. We don't currently have a signal to tell us when a user uses the formatter on their code, which makes defining the behavior of such a fix problematic.

The formatter doesn't currently format comments (though we've had discussions about adding such functionality either in the formatter or elsewhere), but in comments we have additional possible issues. Because doc comments are written in markdown we'd need to understand how to correctly break the text without changing the interpretation of the markdown. While it isn't impossible to do, it looks like it wouldn't be a trivial amount of work in order to do it well.

**Comment by bwilkerson** [comment] 2021-12-10 18:54
> It looks like that works by applying the changes to the servers overlays ...

Yep, that's exactly how it works.

> I'm not sure that's reasonable in the main server process ...

I agree. We'd need to make sure that we could back-out any overlays and that we wouldn't conflict with changes coming in from the client.

> Is there any existing mechanism we could use to create another layer of overlays while computing the fixes and then run them again over that?

The overlays are handled by an `OverlayResourceProvider` that wraps another `ResourceProvider`. In theory we could wrap one overlay provider in another, but it's never been tested. But if we do that (which is probably the best approach) then we'd also have to create our own `AnalysisContextCollection` so that analysis would consistently use the temporary overlay provider. The one nice piece of this architecture is that the temporary overlays would be isolated in a way that would negate the need to revert those changes; we'd just drop the temporary resource provider.

> Do you have an idea of how common it is to need to apply multiple layers like this?

As far as I know we've never needed to do it before.

**Comment by srawlins** [comment] 2021-12-14 22:53
@bwilkerson or @pq, I'm triaging issues this week, and this one's a toughy. 😛 . Can we... break this up or something? If the issue is useful to people as a conversation thread, then maybe nothing needs to be done.

My 2c is that I cannot conceive of a priority for such a broad issue. And as the issue is framed now, I don't think there is any possible exit criteria.

**Comment by pq** [comment] 2021-12-14 23:27
I'm in favor of breaking out sub-issues for all the concrete fixes and then either keeping this open as a meta tracking issue or just closing it (w/ backlinks where there's context that's useful in the new issues).

**Comment by bwilkerson** [comment] 2021-12-15 16:32
I was planning to break it up into one issue per lint, but have been otherwise occupied for the past couple of days. If nobody else gets to it first I'll move the discussion into separate issues to make it easier to track the work.

**Comment by bwilkerson** [comment] 2021-12-16 23:38
Issues created:
- https://github.com/dart-lang/sdk/issues/47953
- https://github.com/dart-lang/sdk/issues/47954
- https://github.com/dart-lang/sdk/issues/47955
- https://github.com/dart-lang/sdk/issues/47956
- https://github.com/dart-lang/sdk/issues/47957
- https://github.com/dart-lang/sdk/issues/47958
- https://github.com/dart-lang/sdk/issues/47959
- https://github.com/dart-lang/sdk/issues/47960

I'm going to close this in favor of the newly opened issues.

**Closed by bwilkerson** 2021-12-16 23:38 UTC
Labels: area-analyzer, analyzer-linter, analyzer-quick-fix

**Comment by bsutton** [comment] 2021-12-16 23:50
thanks.

S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by DanTup** [comment] 2021-12-19 13:13
I also opened #47968 about updating Fix All to be able to apply multiple rounds of fixes like `dart fix` does.
