### ISSUE TITLE
NoSuchMethodError: The getter 'kind' was called on null.

### ISSUE THREAD

**Issue by longd3** [dart-lang/sdk#38704] opened 2019-10-03 04:49 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/long/axlehire/axlehire_flutter_model/lib/src/aws_s3_policy.dart
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:475:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#13     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#14     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#15     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#16     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#20     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#22     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:669:24)
#23     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#24     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10523:19)
#25     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#26     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#27     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#28     GeneralizingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:578:7)
#29     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10517:49)
#30     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#31     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10619:16)
#32     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#33     GeneralizingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:582:7)
#34     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10613:15)
#35     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10666:20)
#36     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#37     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#38     GeneralizingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:586:7)
#39     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10662:15)
#40     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#41     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#42     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#43     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#44     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:162:31)
#45     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#46     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#47     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#48     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#49     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:165:55)
#50     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#51     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2634:12)
#52     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor....
```

For additional log information, please append the contents of
file:///private/var/folders/10/x1w0j7lj23s77dpv45lmg7_h0000gp/T/report.txt.

**Comment by srawlins** [comment] 2019-10-15 04:40
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38488; please follow along there.

**Comment by srawlins** [comment] 2019-10-15 04:40
Duplicate of https://github.com/dart-lang/sdk/issues/38488

**Closed by srawlins** 2019-10-15 04:40 UTC
Labels: area-analyzer, type-bug
