### ISSUE TITLE
Analyzer stacktrace

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#25755] opened 2016-02-10 20:41 UTC
This is a stacktrace I got from the console (repeated).
I don't remember if it had any impact. (I had to shut down intellij because of no completion, but that was in another window).
```
[98618696]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.15.0-edge.032f0f470b9a88b5e89bb9a62e8eeedc6332b780, server version 1.14.0, error: Failed to handle completion domain request: {clientRequestTime: 1455112207603, params: {file: /usr/local/google/home/floitsch/code/mojo-pkg/sdk_ext/internal.dart, offset: 294}, method: completion.getSuggestions, id: 1172}
Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package:analyzer/src/context/context.dart:2069)
#1      AnalysisContextImpl.dispose (package:analyzer/src/context/context.dart:737)
#2      ServerContextManagerCallbacks.removeContext (package:analysis_server/src/analysis_server.dart:1516)
#3      ContextManagerImpl._destroyContext (package:analysis_server/src/context_manager.dart:1049)
#4      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:696)
#5      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:971)
#6      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:264)
#7      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:203)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:692)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:688)
#11     _rootRun (dart:async/zone.dart:895)
#12     _CustomZone.run (dart:async/zone.dart:790)
#13     _CustomZone.runGuarded (dart:async/zone.dart:696)
#14     runZoned (dart:async/zone.dart:1231)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:687)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#20     _rootRunUnary (dart:async/zone.dart:902)
#21     _CustomZone.runUnary (dart:async/zone.dart:798)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#31     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#33     _rootRunUnary (dart:async/zone.dart:902)
#34     _CustomZone.runUnary (dart:async/zone.dart:798)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#46     _rootRunUnary (dart:async/zone.dart:902)
#47     _CustomZone.runUnary (dart:async/zone.dart:798)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#52     _StreamController._add (dart:async/stream_controller.dart:632)
#53     _StreamController.add (dart:async/stream_controller.dart:578)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#55     _rootRunUnary (dart:async/zone.dart:906)
#56     _CustomZone.runUnary (dart:async/zone.dart:798)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#61     _StreamController._add (dart:async/stream_controller.dart:632)
#62     _StreamController.add (dart:async/stream_controller.dart:578)
#63     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
 
java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
        at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:204)
        at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
        at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
[98618697]  ERROR - yzer.DartAnalysisServerService - IntelliJ IDEA (Community Edition) IC-144.2925.2  Build #IC-144.2925.2 
[98618698]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0-google-v7 
[98618698]  ERROR - yzer.DartAnalysisServerService - VM: OpenJDK 64-Bit Server VM 
[98618698]  ERROR - yzer.DartAnalysisServerService - Vendor: Google Inc. 
[98618698]  ERROR - yzer.DartAnalysisServerService - OS: Linux 
[98618698]  ERROR - yzer.DartAnalysisServerService - Last Action: Exit 
[98618698]  ERROR - yzer.DartAnalysisServerService - Current Command: Exit 
[98618698]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.15.0-edge.032f0f470b9a88b5e89bb9a62e8eeedc6332b780, server version 1.14.0, error: Failed to handle completion domain request: {clientRequestTime: 1455112207762, params: {file: /usr/local/google/home/floitsch/code/mojo-pkg/sdk_ext/internal.dart, offset: 295}, method: completion.getSuggestions, id: 1174}
Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package:analyzer/src/context/context.dart:2069)
#1      AnalysisContextImpl.dispose (package:analyzer/src/context/context.dart:737)
#2      ServerContextManagerCallbacks.removeContext (package:analysis_server/src/analysis_server.dart:1516)
#3      ContextManagerImpl._destroyContext (package:analysis_server/src/context_manager.dart:1049)
#4      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:696)
#5      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:971)
#6      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:264)
#7      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:203)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:692)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:688)
#11     _rootRun (dart:async/zone.dart:895)
#12     _CustomZone.run (dart:async/zone.dart:790)
#13     _CustomZone.runGuarded (dart:async/zone.dart:696)
#14     runZoned (dart:async/zone.dart:1231)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:687)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:194)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#20     _rootRunUnary (dart:async/zone.dart:902)
#21     _CustomZone.runUnary (dart:async/zone.dart:798)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:127)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:102)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#31     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#33     _rootRunUnary (dart:async/zone.dart:902)
#34     _CustomZone.runUnary (dart:async/zone.dart:798)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:80)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#46     _rootRunUnary (dart:async/zone.dart:902)
#47     _CustomZone.runUnary (dart:async/zone.dart:798)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#52     _StreamController._add (dart:async/stream_controller.dart:632)
#53     _StreamController.add (dart:async/stream_controller.dart:578)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:1646)
#55     _rootRunUnary (dart:async/zone.dart:906)
#56     _CustomZone.runUnary (dart:async/zone.dart:798)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:760)
#61     _StreamController._add (dart:async/stream_controller.dart:632)
#62     _StreamController.add (dart:async/stream_controller.dart:578)
#63     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1215)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:749)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment] 2016-02-10 23:02
@danrubel Is this a duplicate of #24271? (I ask because it seems similar to #25689, which was marked as being a duplicate.)

**Comment by danrubel** [comment] 2016-02-10 23:10
Yes, I believe so. We should know better with the next build now that I've wrapped calls to computeAsync as part of [abort completion request ](https://github.com/dart-lang/sdk/commit/3fc06a4aa7c506a260aee1d91d5b14c5726662d0).

**Comment by danrubel** [comment] 2016-03-29 12:43
I believe this is fixed as part of [abort completion request ](https://github.com/dart-lang/sdk/commit/3fc06a4aa7c506a260aee1d91d5b14c5726662d0).
Please reopen if you see this happen again.

**Closed by danrubel** 2016-03-29 12:43 UTC
Labels: analyzer-completion, area-analyzer, P1 high, Type: bug
