### ISSUE TITLE
Simple code yields different results on native vs dart2js

### ISSUE THREAD

**Issue by theniceboy** [dart-lang/sdk#49920] opened 2022-09-07 23:20 UTC
This tracker is for issues related to:
Dart core libraries ("dart:async", "dart:io", etc.)
dart2js

When running this snippet of code,
```dart
void main() {
  final nums = [1, 2, 3];
  var len = 0;
  
  final iter = nums.map((x) {
    len += 1;
    return x + 1;
  });
  final list = iter.toList();
  print("$iter has length $len");
}
```
The len variable is `6` if you run it on the Dartpad. If you run it on native, it'll be `3`.

* Dart SDK Version (`dart --version`)
```
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "macos_arm64"
```

**Comment by sigmundch** [comment] 2022-09-08 00:32
Reading through the documentation of `List.map`, I believe the expected behavior is for both `iter.toList` and the `iter.toString` (from the `$iter` in the `print`) to trigger iterating over the original list and execute the closure.  As a result I believe the output in dartpad/dart2js matches this expectation, but the VM doesn't.

**Comment by julemand101** [comment] 2022-09-08 04:53
I think it is more a matter of the order which String's are being built and the side effects of building parts of the String. See the following two example executed in Dart VM:
```dart
print("$iter has length $len"); // (2, 3, 4) has length 3
```
```dart
print("$iter has length " + len.toString()); // (2, 3, 4) has length 6
```

**Comment by mraleph** [comment] 2022-09-08 07:22
This is caused by the difference between how dart2js and VM evaluate string interpolations. For `"${a} ${b}"` dart2js does equivalent of:

```dart
var str0 = a.toString();
var str1 = b.toString();
str0 + "  " + str1
```

while VM does

```dart
var expr0 = a;
var expr1 = b;
expr0.toString() + " " + expr1.toString()
```

So on VM you get 3 because `iter.toString()` (which reiterates the mapped iterable and increments `len`) is evaluated after the current value of `len` is saved in a temporary. On `dart2js` you don't save `len` in a temporary so `iter.toString()` updates it and then `len` is printed.

**Comment by mraleph** [comment] 2022-09-08 07:22
Duplicate of https://github.com/dart-lang/sdk/issues/34223

**Closed by mraleph** 2022-09-08 07:22 UTC
Labels: area-vm
