### ISSUE TITLE
Dart official web server framework and ORM

### ISSUE THREAD

**Issue by ansarizafar** [dart-lang/sdk#39504] opened 2019-11-24 07:23 UTC
Dart is amazing and becoming very popular because of huge success of Flutter. Dart can be used to develop mobile, web and desktop applications the only missing piece is an official Asp.net core like framework and and Entity framework like official ORM. 

Developers would love to use Dart for full stack development without a need to use any other language for server side development. This will make Dart and Flutter even more popular. I request Dart core team to please seriously consider this proposal.

**Comment by manhluong** [comment] 2019-11-24 12:32
@ansarizafar you mean something like this?

https://pub.dev/packages/shelf

If you want something more complex, then:

https://angel-dart.dev/

And

https://aqueduct.io/

**Comment by ansarizafar** [comment] 2019-11-24 13:19
I have tried them all. They all have missing features. I am talking about a feature complete, officially supported, professionally developed and maintained framework like Asp.net core and Entity framework.

**Comment by manhluong** [comment] 2019-11-24 15:10
@ansarizafar what are the features you are missing in the frameworks above?

**Comment by mraleph** [comment] 2019-11-24 20:55
Dart team currently thinks that third party developers are better positioned to provide great server side framework, ORM(s) etc.

**Comment by mraleph** [comment] 2019-11-24 20:55
Duplicate of #37076

**Closed by mraleph** 2019-11-24 20:55 UTC
