### ISSUE TITLE
woud love to write annotations with less `const` noise

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/sdk#24620] opened 2015-10-18 20:59 UTC
When porting angular2 typescript examples, I feel like that in many cases the dart syntax is sweeter, except for the `const` noise you sometimes have with annotations.

I was just trying to make myself a library with annotations, but in this case, it becomes even worse:
```dart
  @Test(parameters: const[
    const[1, 1], const[2, 4], const[3, 9], const[4, 16], const[5, 25]
  ])
  math_pow_squares_an_integer(int number, int squared) {
    expect(math.pow(number, 2), squared);
  }
```

I would love that in future dart version, all those const annotations wouldn't be necessary anymore. Can I have any hope for this?

In my naive point of view, I would say that if the variable must be constant, dart kind of automatic marks the list constant(behind the scenes). And if that is not possible, warn the user? Isn't that also what happens with strings and integers?

**Comment by sethladd** [comment] 2015-10-19 00:10
cc @lrhn for fyi

**Comment by zoechi** [comment] 2015-10-19 04:53
I guess it's a dupe of #4046

**Comment by lrhn** [comment] 2015-10-19 06:37
It certainly is a dupe. 

I wholeheartedly concur with the request. See: https://github.com/lrhn/dep-const/blob/master/proposal.md

**Closed by lrhn** 2015-10-19 06:37 UTC
Labels: Area-Language, Resolution-Duplicate

**Comment by kasperpeulen** [comment] 2015-10-19 22:27
@lrhn Nice to see a proposal! What is the status? Is it accepted?
