### ISSUE TITLE
Dart Analyzer Error 			Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by chenxi1381** [dart-lang/sdk#36329] opened 2019-03-25 06:30 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\xxxxxx], excluded: [D:\xxxxxx\.idea, D:\xxxxxx\.dart_tool, D:\xxxxxx\.pub, D:\xxxxxx\build]}, clientRequestTime: 1553485203738}
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _DartNavigationComputerVisitor._addUriDirectiveRegion (package:analysis_server/src/domains/analysis/navigation_dart.dart:361:47)
#2      _DartNavigationComputerVisitor.visitPartDirective (package:analysis_server/src/domains/analysis/navigation_dart.dart:232:5)
#3      PartDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:9573:49)
#4      _DartNavigationComputerVisitor.visitCompilationUnit (package:analysis_server/src/domains/analysis/navigation_dart.dart:149:12)
#5      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2558:49)
#6      computeDartNavigation (package:analysis_server/src/domains/analysis/navigation_dart.dart:28:10)
#7      ServerContextManagerCallbacks._computeNavigationParams (package:analysis_server/src/analysis_server.dart:1034:5)
#8      ServerContextManagerCallbacks.addAnalysisDriver.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:843:19)
#9      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#10     _rootRun (dart:async/zone.dart:1120:38)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\----\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-04-08 16:34
Duplicate of #36328.

**Closed** 2019-08-29 04:27 UTC
Labels: area-analyzer
