### ISSUE TITLE
Failures on Simplify `asyncExpectThrows` and enhance `Expect.throws`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#48087] opened 2022-01-06 15:50 UTC
There are new test failures on [Simplify `asyncExpectThrows` and enhance `Expect.throws`.](https://dart-review.googlesource.com/c/sdk/+/226102).

The tests
```
pkg/compiler/test/rti/rti_emission1_test RuntimeError (expected Pass)
pkg/compiler/test/rti/rti_need1_test RuntimeError (expected Pass)
pkg/compiler/test/rti/rti_need2_test RuntimeError (expected Pass)
```
are failing on configurations
```
web-unittest-asserts-linux
```

The test failures do not appear to be due to bugs in the change, so the tests appear fragile against unrelated changes.
The test failure message does not provide a script to update expectations.

**Comment by sigmundch** [comment] 2022-01-06 16:43
Here is a sample [log failure](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8825793295977796001/+/u/test_results/new_test_failures__logs_)

```
Test: file:///b/s/w/ir/pkg/compiler/test/rti/emission/local_function_list_literal.dart
--from (compliance mode)-------------
memory:sdk/tests/web/native/main.dart:11:10:
Error: UNEXPECTED compliance mode DATA for offset 322 (IdKind.node):
 detail  : Expected checks=[],instance, found checks=[$signature],instance
 object  : object `FunctionExpression(List<T*>* () => <T*>[])` (FunctionExpression)
 expected: checks=[],instance
 actual  : checks=[$signature],instance
  return () => <T>[];
         ^
--annotations diff [main.dart]-------------
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// @dart = 2.7

import 'package:expect/expect.dart';

@pragma('dart2js:noInline')
method<T>() {
  return /*checks=[],instance | checks=[$signature],instance*/ () => <T>[];
}

@pragma('dart2js:noInline')
test(o) => o is List<int>;

main() {
  Expect.isTrue(test(method<int>().call()));
  Expect.isFalse(test(method<String>().call()));
}
```

@fishythefish - is it possible that the global deduction that the closure needs or not a `$signature`  is being obfuscated by code elsewhere in the program (like closures in package:expect)?

**Comment by fishythefish** [comment] 2022-01-12 21:37
In a sense, this is working as intended, but the overall result is unintuitive.

https://dart-review.googlesource.com/c/sdk/+/227903 updates the expectations; explanation below.

---

Some functions now need a signature in `spec` mode:

The `ExpectException` class has a `_getTestName` static member which was previously typed `dynamic` and is now typed `String Function()`. We therefore have a parameter check `TypeUse` for the type `String Function()`. This is treated as an `is`-check against the type `String Function()`. (This is for `spec` mode; in `prod`, the check would be omitted.)

In the RTI-need computation, when we see a check against a function type `F`, we check the type of each local function and closurized member - from anywhere in the program - to see if it is a potential subtype of `F`. If it is, then that local function is marked as needing a signature so that we can do the type test at runtime.

In this case, the local function is `() => <T>[]`, which has type `List<T> Function()`. There is no instantiation which would yield `List<T> Function() <: String Function()`, so ordinarily, we would not consider this a potential subtype. However, we currently consider any type to be a potential subtype of any other type (see https://dart-review.googlesource.com/c/sdk/+/155544): https://github.com/dart-lang/sdk/blob/0a3d896274c30e7f9c89d2cbe63b8403b65c63ce/pkg/compiler/lib/src/elements/types.dart#L1898-L1899

Consequently, we now emit a signature for all local functions. The local functions which didn't need signatures previously just happened to be in tests/programs which didn't have any type tests against function types.

---

Some functions no longer require a signature in `prod` mode:

This is essentially the same reasoning as above. The code for `Expect.throws` no longer contains an explicit `is`-test against the type `Function()`. In programs where that was the only explicit `is`-check against a function type, we now no longer need signatures in `prod` mode.

**Closed** 2022-02-01 23:43 UTC
Labels: web-dart2js, area-web
