### ISSUE TITLE
Dart Issue

### ISSUE THREAD

**Issue by agoeden12** [dart-lang/sdk#35629] opened 2019-01-11 04:18 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\andre\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\andre\AndroidStudioProjects\LetsAct-Flutter], excluded: [C:\Users\andre\AndroidStudioProjects\LetsAct-Flutter\.idea, C:\Users\andre\AndroidStudioProjects\LetsAct-Flutter\.dart_tool, C:\Users\andre\AndroidStudioProjects\LetsAct-Flutter\.pub, C:\Users\andre\AndroidStudioProjects\LetsAct-Flutter\build]}, clientRequestTime: 1547178563206}
FileSystemException: Exists failed, path = 'C:\Users\andre\AndroidStudioProjects\LetsAct-Flutter\build\firebase_core\generated\not_namespaced_r_class_sources\debug\generateDebugRFile\out\com\google\android\gms\ads_identifier' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2019-01-11 17:00
Duplicate of #34294

**Closed by stereotype441** 2019-01-11 17:00 UTC
Labels: area-analyzer
