### ISSUE TITLE
Please add ProcessSignal member with ProcessSignal._(0, "AF_UNSPEC") or add a public constructor

### ISSUE THREAD

**Issue by bpilot** [dart-lang/sdk#37386] opened 2019-06-27 16:41 UTC
I would be happy with a public constructor as an escape hatch.

Motivation:
Being able to send a signal of 0 on Linux in order to check if a process is alive without affecting said process.

I know this is platform specific use case, but think it is silly that this isn't possible as it is so trivial and when it is in Go (and Node):
https://golang.org/pkg/syscall/#AF_UNSPEC

If the contributors don't think this is a good idea, I would be interested in the rationale

Thanks!

**Comment by natebosch** [comment] 2019-07-22 20:58
Note that signal 0 is not _sent_ - it's a special case in `kill` that does not send any signal.

As far as I can tell `AF_UNSPEC` is unrelated to signals.

Closing as a duplicate of https://github.com/dart-lang/sdk/issues/21478

**Closed by natebosch** 2019-07-22 20:58 UTC
Labels: area-library, library-io
