### ISSUE TITLE
Confusing "Invalid const" compilation error message

### ISSUE THREAD

**Issue by the-ginger-geek** [dart-lang/sdk#50519] opened 2022-11-20 20:16 UTC
### Issue
When passing an object to a widget that is defined as `const` the below `Error Message` is displayed. In the code example posted below I found it took me a moment to realise that the error was pointing to the `const` constructor of the `Center` widget rather than the constructor of `Foo`, I had to troubleshoot to realise that this was what it was pointing to. 

### Error Message
>A value of type 'Null' can't be assigned to a parameter of type 'Size' in a const constructor. (Documentation)  Try using a subtype, or removing the keyword 'const'.
Invalid constant value.

### Snippet to reproduce

```
class Foo extends StatelessWidget {
  final Size size;

  const Foo({Key? key, this.size = const Size(30, 30)})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: Bar(size: size), // <--- Compilation fails here
    );
  }
}

class Bar extends StatelessWidget {
  final Size size;

  const Bar({super.key, required this.size});

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: size.width,
      height: size.height,
    );
  }
}
```

**Comment by asashour** [comment] 2022-11-20 20:38
Duplicate of #49389

**Closed** 2022-11-21 09:19 UTC
Labels: closed-duplicate
