### ISSUE TITLE
Errors crossing error zone boundaries stop Future propagation

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#24506] opened 2015-10-06 07:06 UTC
```
    runZoned(() => new Future.error('error'),
        zoneSpecification: new ZoneSpecification(handleUncaughtError: (_, __, ___, ____, _____) {
        print('Uncaught error');
      }))
        .whenComplete(() => print('Complete'));
```

`Complete` is never printed.

Is this intended?

This was a rather big surprise for me and might well be for others, too. I have not been able to find information about this anywhere in the documentation.

Example as dartpad: https://dartpad.dartlang.org/25145545b74d32c5bdc8

**Comment by kevmoo** [comment] 2015-10-07 00:30
CC @floitschG (who wrote a bunch of this) and @nex3 (who uses a lot of this)

**Comment by lrhn** [comment] 2015-10-07 08:05
I'm not sure whether it's intentional (as in: this is what we designed for), but it is a direct consequence of the design of error propagation across zone boundaries. As such, it is working as intended.

If you run an asynchronous computation in a zone with an error handler, then the result of that computation is either a value or it's nothing. There is no value we can introduce to replace the error that the zone captured. 
The future returned by runZoned can't complete with the error, because that error was captured by the zone - the zone is there to prevent errors from leaking. The future can't complete with a value since that would suggest that the code run in the zone did complete normally with that value, and that could be very confusing to the code receiving the value (even if it's always `null`). The only possible thing left to do is to not complete at all, which is what it does.

Could we actually make the future complete with `null` when an error was captured by the zone?
I expect a lot of things would break because they receive `null` unexpectedly, but maybe those futures aren't actually being used for anything in most cases - exactly because you can't trust them to complete anyway.

**Comment by nex3** [comment] 2015-10-07 17:49
> Could we actually make the future complete with `null` when an error was captured by the zone?
I expect a lot of things would break because they receive `null` unexpectedly, but maybe those futures aren't actually being used for anything in most cases - exactly because you can't trust them to complete anyway.

I'm reasonably confident that this change would break a bunch of my existing code.

**Comment by BlackHC** [comment] 2015-10-07 18:20
The most important point first: I think the current behavior violates the principle of locality because you cannot know the `Zone` of a `Future` (that is passed in as a parameter) before chaining onto it. So it is impossible to be certain that eg `whenComplete` is executed reliably. (In this case `whenComplete` also behaves differently than `finally`, which will always execute eventually.)
I think this is a big problem. Moreover, there is no way to fix this problem once you have such a Future because you'd have to change `handleUncaughtError` to do this. This makes me think that having different error zones (by overriding `handleUncaughtError`) is a bad idea in general and should avoided at all costs right now.

Ideas:

1. Why do we even need to prevent errors from leaking from one Zone to another in this case?
`handleUncaughtError` would seem like a good thing to be called when eg the Future that has no `catchError` at all, but when there is one further down the chain, the error could be passed on. More importantly, `whenComplete` should always be executed for a `Future`. **In general, `whenComplete` and `catchError` should match `catch` and `finally` in behavior and have similar guarantees.** Right now, the behavior in the sync and async case is not consistent when crossing error zones.

2. For me, it was a very big surprise that `whenComplete` did not trigger in the example. Is this behavior explicitly mentioned in the documentation? If we cannot change the behavior, we could at least make it more obvious in the documentation.

Thanks,
 Andreas

**Comment by nex3** [comment] 2015-10-07 18:44
> The most important point first: I think the current behavior violates the principle of locality because you cannot know the `Zone` of a `Future` (that is passed in as a parameter) before chaining onto it. So it is impossible to be certain that eg `whenComplete` is executed reliably. (In this case `whenComplete` also behaves differently than `finally`, which will always execute eventually.)

You can never be certain that `whenComplete` will be executed. It's always possible that a Future will never fire, even if no Zone shenanigans are involved. It's reasonable to want to ensure that your API's Futures always complete, but it's certainly not the case in the core libraries—the simplest example being `new Completer().future`.

> I think this is a big problem. Moreover, there is no way to fix this problem once you have such a Future because you'd have to change `handleUncaughtError` to do this. This makes me think that having different error zones (by overriding `handleUncaughtError`) is a bad idea in general and should avoided at all costs right now.

It's definitely possible to use error zones in a way that doesn't swallow errors. For example, a pattern I use occasionally is:

```dart
var completer = new Completer();
runZoned(() {
  new Future.sync(() async {
    // ...
  }).then((value) {
    if (!completer.isCompleted) completer.complete(value);
  });
}, handleError: (error, stackTrace) {
  if (!completer.isCompleted) completer.completeError(error, stackTrace);
});
```

Other times, I know that `handleError` will make the value of the future irrelevant, or the code that uses the future is resilient to it never completing.

> Why do we even need to prevent errors from leaking from one Zone to another in this case?
`handleUncaughtError` would seem like a good thing to be called when eg the Future that has no `catchError` at all, but when there is one further down the chain, the error could be passed on.

It provides the invariant that async errors never leave zones except through `handleError` or being passed out as values. Invariants like this make complex code easier to reason about, and this one in particular is useful for e.g. the `test` package where we want to be absolutely sure we handle all possible errors.

If we could guarantee that `whenComplete` always fired, that would also be a useful invariant, but as I mentioned above we can't.

**Comment by jakemac53** [comment] 2016-06-16 14:48
This recently bit me as well, one thing which surprised me is the difference between how the return value of `onError` is handled for synchronous vs asynchronous errors. See https://dartpad.dartlang.org/19b7fb519819f16476c7bc337be928ef (try it with and without the `throw`).

In the synchronous error case, the return value of `onError` is returned from `runZoned`, but in the asynchronous case the `Future` that is returned is not completed with the return value from `onError`. My intuition would have been that these would behave roughly the same, meaning the future would complete with the return value from `onError` (and null if there was no return value).

As far as I can tell, the current behavior means its pretty much never valid to `await` a call to `runZoned`, as that could easily never complete, which is not desirable behavior imo.

**Comment by jakemac53** [comment] 2018-06-27 13:58
Closing this issue as working as intended.

Yes this is a very common source of bugs, but it doesn't seem like there is anything to really be done about it.

**Closed by jakemac53** 2018-06-27 13:58 UTC
Labels: area-library, library-async
