### ISSUE TITLE
Migration: need to insert ! null checks on type parameter types with nullable bound

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40355] opened 2020-01-28 21:20 UTC
The migration for package:collection currently results in

```
 error • The expression is nullable and must be null-checked before it can be used. • lib/src/equality.dart:237:23 • unchecked_use_of_nullable_value
```

The issue is

```dart
for (E element in elements) {
```

where elements is of type `T extends Iterable<E>?`

So we need to insert a `!` in this case.

Note: in my diagnosis, I found that the type was "correct." Test code was passing in nulls, so `Iterable<E>?` is correct. Happy to have someone double check me before working on this.

Refs #40353

**Comment by stereotype441** [comment] 2020-01-30 16:27
It turns out the problem isn't with for-in statements--null checks are inserted for those in general.  The problem is that in this particular case, the type being iterated over is a type parameter:
```dart
abstract class _UnorderedEquality<E, T extends Iterable<E>?>
  int hash(T elements) {
    ...
    for (E element in elements) { // Null check needed here
      ...
    }
    ...
  }
}
```
I'm working on a fix.

**Comment by stereotype441** [comment] 2020-01-30 21:26
Duplicate of https://github.com/dart-lang/sdk/issues/40355

**Comment by stereotype441** [comment] 2020-01-31 21:17
Whoops, an issue can't be a duplicate of itself

**Closed** 2020-02-03 20:00 UTC
Labels: analyzer-nnbd-migration, area-analyzer, nnbd-migration-correctness-example
