### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by chiefmarko** [dart-lang/sdk#32724] opened 2018-03-31 06:39 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4670197`
- `2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0`
- `AI-173.4670197, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\markk\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.0.0-edge.0d5cf900b021bf5c9fa593ffa12b15bcd1cc5fe0, server version 1.18.6, error: Analysis failed: C:\Users\markk\OneDrive\Nyaraka\OneDrive\Nyaraka\AndroidProjects\my_friendlychat\lib\main.dart context: exception_20180331_092807_103
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:873)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:254)
#3      _HashVMBase

**Comment by dgrove** [comment] 2018-04-02 03:31
Tentatively setting to Dart 2-Beta 3 milestone.

**Comment by bwilkerson** [comment] 2018-04-02 16:14
@scheglov

**Comment by scheglov** [comment] 2018-04-02 16:42
I don't understand what happens here. It looks that we got `null` for `librarySource`, i.e. `SourceFactory` returned `null` for the URI that was given to `SummaryResynthesizer.getLibraryElement`. And I don't understand how this could happen.

Maybe the file `exception_20180331_092807_103` that it is `.analysis_driver` folder somewhere in the home directory would give some inside.

**Comment by bwilkerson** [comment] 2018-04-02 22:54
@chiefmarko Would it be possible for you to send us the file mentioned above?

**Comment by chiefmarko** [comment] 2018-04-03 08:18
It was just the default main.dart for android. Tried opening a new project and the exception disappeared

**Comment by dgrove** [comment] 2018-04-03 15:00
So there's nothing actionable here?

**Comment by bwilkerson** [comment] 2018-04-03 15:09
As far as I know, we haven't tried yet to reproduce the error. But if we can't reproduce it, and if we can't get the file from the user, then we have no information to help us find the cause of the issue.

**Comment by dgrove** [comment] 2018-04-03 15:10
Given the lack of info, closing. Please open a new issue if this reoccurs.

**Closed by dgrove** 2018-04-03 15:10 UTC
Labels: area-analyzer
