### ISSUE TITLE
dartanalyzer --version doesn't add newline

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#26365] opened 2016-04-29 04:17 UTC
```
~/Code/firebase[formatting*] $ dartanalyzer --version
dartanalyzer version 1.16.0~/Code/firebase[formatting*] $ 
```

Normally, the output of `--version` adds a newline.

**Comment by srawlins** [comment] 2016-12-22 17:48
Dupe of #25303

**Closed** 2017-01-25 03:03 UTC
Labels: analyzer-command, area-analyzer, P2 medium, Type: bug
