### ISSUE TITLE
DDC fails to compile typed_buffers.ddc.js on Windows

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#37453] opened 2019-07-05 21:12 UTC
Error: Bad state: Expected to get sdk digest at null

```
C:\git\cambridge\spectrum>flutter run -d chrome
Error compiling dartdevc module:spectrum|lib/spectrum/utility.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\git\flutter\bin\cache\flutter_web_sdk/kernel\flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o
    C:\Users\tim\AppData\Local\Temp\scratch_space62f4580c-9f69-11e9-8172-000272bfcddb\packages/spectrum/spectrum/utility
    .ddc.js --source-map
    --packages=file:///C:/Users/tim/AppData/Local/Temp/kernel_builder_62f4580f-9f69-11e9-8172-000272bfcddb/.packages
    --module-name=packages/spectrum/spectrum/utility --multi-root-scheme=org-dartlang-app --multi-root=.
    --track-widget-creation --inline-source-map package:spectrum/spectrum/utility.dart
    dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
#4      _CompilerWorker.performRequest.<anonymous closure>
(file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest
(file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




Error compiling dartdevc module:collection|lib/src/iterable_zip.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\git\flutter\bin\cache\flutter_web_sdk/kernel\flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o
    C:\Users\tim\AppData\Local\Temp\scratch_space62f4580c-9f69-11e9-8172-000272bfcddb\packages/collection/src/iterable_z
    ip.ddc.js --source-map
    --packages=file:///C:/Users/tim/AppData/Local/Temp/kernel_builder_62f45822-9f69-11e9-8172-000272bfcddb/.packages
    --module-name=packages/collection/src/iterable_zip --multi-root-scheme=org-dartlang-app --multi-root=.
    --track-widget-creation --inline-source-map package:collection/src/iterable_zip.dart
    dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
#4      _CompilerWorker.performRequest.<anonymous closure>
(file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest
(file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

`flutter doctor` reports:
```
C:\git\cambridge\spectrum>flutter doctor -v
[√] Flutter (Channel master, v1.8.1-pre.22, on Microsoft Windows [Version 10.0.18362.207], locale en-US)
    • Flutter version 1.8.1-pre.22 at C:\git\flutter
    • Framework revision 93edc014ae (27 hours ago), 2019-07-04 11:26:19 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)
```

**Comment by timsneath** [comment] 2019-07-05 21:16
Probably unrelated, but notice the mismatch of directory delimiters (`\` v. `/`) in the `--dart-sdk-summary` and `-o` parameters. Windows is _somewhat_ tolerant of this, but it would be good to improve consistency here, since it's a potential source of bugs.

**Comment by lexmann** [comment] 2019-07-07 12:53
> Error: Bad state: Expected to get sdk digest at null
> 
> ```
> C:\git\cambridge\spectrum>flutter run -d chrome
> Error compiling dartdevc module:spectrum|lib/spectrum/utility.ddc.js
> 
> We're sorry, you've found a bug in our compiler.
> You can report this bug at:
>     https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
> Please include the information below in your report, along with
> any other information that may help us track it down. Thanks!
> -------------------- %< --------------------
>     dartdevc -k arguments: --dart-sdk-summary=C:\git\flutter\bin\cache\flutter_web_sdk/kernel\flutter_ddc_sdk.dill
>     --modules=amd --no-summarize -o
>     C:\Users\tim\AppData\Local\Temp\scratch_space62f4580c-9f69-11e9-8172-000272bfcddb\packages/spectrum/spectrum/utility
>     .ddc.js --source-map
>     --packages=file:///C:/Users/tim/AppData/Local/Temp/kernel_builder_62f4580f-9f69-11e9-8172-000272bfcddb/.packages
>     --module-name=packages/spectrum/spectrum/utility --multi-root-scheme=org-dartlang-app --multi-root=.
>     --track-widget-creation --inline-source-map package:spectrum/spectrum/utility.dart
>     dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"
> 
> Bad state: Expected to get sdk digest at null
> #0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
> <asynchronous suspension>
> #1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
> <asynchronous suspension>
> #2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
> <asynchronous suspension>
> #3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
> #4      _CompilerWorker.performRequest.<anonymous closure>
> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
> #5      _rootRun (dart:async/zone.dart:1124:13)
> #6      _CustomZone.run (dart:async/zone.dart:1021:19)
> #7      _runZoned (dart:async/zone.dart:1516:10)
> #8      runZoned (dart:async/zone.dart:1463:12)
> #9      _CompilerWorker.performRequest
> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
> <asynchronous suspension>
> #10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
> #11     _rootRun (dart:async/zone.dart:1124:13)
> #12     _CustomZone.run (dart:async/zone.dart:1021:19)
> #13     _runZoned (dart:async/zone.dart:1516:10)
> #14     runZoned (dart:async/zone.dart:1463:12)
> #15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
> <asynchronous suspension>
> #16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
> <asynchronous suspension>
> #17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
> #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> 
> 
> 
> 
> Error compiling dartdevc module:collection|lib/src/iterable_zip.ddc.js
> 
> We're sorry, you've found a bug in our compiler.
> You can report this bug at:
>     https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
> Please include the information below in your report, along with
> any other information that may help us track it down. Thanks!
> -------------------- %< --------------------
>     dartdevc -k arguments: --dart-sdk-summary=C:\git\flutter\bin\cache\flutter_web_sdk/kernel\flutter_ddc_sdk.dill
>     --modules=amd --no-summarize -o
>     C:\Users\tim\AppData\Local\Temp\scratch_space62f4580c-9f69-11e9-8172-000272bfcddb\packages/collection/src/iterable_z
>     ip.ddc.js --source-map
>     --packages=file:///C:/Users/tim/AppData/Local/Temp/kernel_builder_62f45822-9f69-11e9-8172-000272bfcddb/.packages
>     --module-name=packages/collection/src/iterable_zip --multi-root-scheme=org-dartlang-app --multi-root=.
>     --track-widget-creation --inline-source-map package:collection/src/iterable_zip.dart
>     dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"
> 
> Bad state: Expected to get sdk digest at null
> #0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
> <asynchronous suspension>
> #1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
> <asynchronous suspension>
> #2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
> <asynchronous suspension>
> #3      compile (package:dev_compiler/src/compiler/shared_command.dart:408:12)
> #4      _CompilerWorker.performRequest.<anonymous closure>
> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
> #5      _rootRun (dart:async/zone.dart:1124:13)
> #6      _CustomZone.run (dart:async/zone.dart:1021:19)
> #7      _runZoned (dart:async/zone.dart:1516:10)
> #8      runZoned (dart:async/zone.dart:1463:12)
> #9      _CompilerWorker.performRequest
> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
> <asynchronous suspension>
> #10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
> #11     _rootRun (dart:async/zone.dart:1124:13)
> #12     _CustomZone.run (dart:async/zone.dart:1021:19)
> #13     _runZoned (dart:async/zone.dart:1516:10)
> #14     runZoned (dart:async/zone.dart:1463:12)
> #15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
> <asynchronous suspension>
> #16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
> <asynchronous suspension>
> #17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
> #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> ```
> 
> `flutter doctor` reports:
> 
> ```
> C:\git\cambridge\spectrum>flutter doctor -v
> [√] Flutter (Channel master, v1.8.1-pre.22, on Microsoft Windows [Version 10.0.18362.207], locale en-US)
>     • Flutter version 1.8.1-pre.22 at C:\git\flutter
>     • Framework revision 93edc014ae (27 hours ago), 2019-07-04 11:26:19 -0700
>     • Engine revision 3c51a7bfff
>     • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)
> ```

**Comment by mraleph** [comment] 2019-07-11 10:08
Duplicate of #37490

**Closed by mraleph** 2019-07-11 10:08 UTC
Labels: area-dev-compiler, type-bug
