### ISSUE TITLE
Make observatory sources strong-mode clean

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#32503] opened 2018-03-12 18:20 UTC
We need to make observatory strong-mode clean, at the latest when dart2js switches to Dart 2.0.

/cc @rmacnak-google @a-siva

**Comment by sigmundch** [comment] 2018-07-02 18:34
I've just raised the priority: dart2js now defaults to Dart 2.0 for internal and external users. We are about to flip the entire test coverage in the bots to mostly run in Dart 2.0 as well. Once observatory is migrated, we should be able to remove support for Dart1 in dart2js.

**Comment by rmacnak-google** [comment] 2018-07-02 19:05
This is dependent on a Dart 2-capable package:charted. Assigning to Dart4Web.

**Comment by sigmundch** [comment] 2018-07-02 21:45
Mmm - it appears that this package is or almost is Dart-2 capable, but that the latest changes are not published yet. I reached out to the maintainers to get some guidance on how to proceed. @rmacnak-google, I cc'd you on the message as well.

**Comment by dgrove** [comment] 2018-07-03 23:31
Assigning back to @rmacnak-google - please work with whoever is needed to ensure that observatory and its transitive dependencies are Dart 2-compatible.

**Comment by mit-mit** [comment] 2018-07-09 11:31
@rmacnak-google are you looking at this one?

**Comment by natebosch** [comment] 2018-07-09 19:40
I don't understand how https://github.com/dart-lang/observatory_pub_packages works, or why we have yet another approach for importing third_party packages...

Can someone familiar with it please pull in the latest charted from git? I think the problem is likely that it isn't published with Dart 2 compatible code, but is fixed in the repo.

I also filed https://github.com/google/charted/issues/237 to request a publish.

**Comment by natebosch** [comment] 2018-07-09 19:57
apparently there are some required fixes that aren't in the git repo either. This will take some work to get exported.

If possible, could we limit the flag usage to within the SDK and keep support internally for Dart 1 mode in Dart2Js? If we consider it blocking for Dart2Stable I can take a look, but if we can punt on it I think there's likely work that is more impactful for our users.

**Comment by sigmundch** [comment] 2018-07-09 20:41
Just created https://github.com/google/charted/pull/238 to upgrade the charted git repo with more fixes.

@rmacnak-google could you please test if this is enough to unblock you by using a git-dependency on my forked repo?

For example
```yaml
dependencies:
  charted:
    git:
      url: git://github.com/sigmundch/charted
      ref: updates_for_dart2
```

**Comment by mit-mit** [comment] 2018-07-10 15:29
cc @cskau-g

**Comment by sigmundch** [comment] 2018-07-10 18:31
The pull request landed, but has not been uploaded to pub. You can use it if you set the pubspec to:

```
dependencies:
  charted:
    git:
      url: git://github.com/google/charted
      ref: ba00ac4a41f02b7df9d490eae6307fa059fac5b6
```

**Comment by rmacnak-google** [comment] 2018-07-10 19:16
Thanks Siggi! I'm able to make progress locally patching that in.

**Comment by dgrove** [comment] 2018-07-11 22:09
@rmacnak-google is this issue ready be closed now that https://dart-review.googlesource.com/c/sdk/+/64460 has landed, or is there more to do?

**Comment by rmacnak-google** [comment] 2018-07-17 21:11
Dart 2 regresses code size by 25%.

compressed_observatory_archive.tar: 823164 -> 1032166
(fbd9c4e7a6cebe6d6a13bbf8f0190867186d1021 -> 296319d2f00e3f51942f884f8f340f725c598ac8)

**Closed by rmacnak-google** 2018-07-17 21:11 UTC
Labels: area-observatory, p1-high

**Comment by sigmundch** [comment] 2018-07-17 21:13
@rmacnak-google - what flags where used to compile observatory before and after?

We may want to use `--omit-implicit-checks` here (which is similar to what we used to have with `--trust-type-annotations`)

**Comment by sigmundch** [comment] 2018-07-17 21:14
(and woohoo! we can now delete Dart1 support from dart2js!)

**Comment by sigmundch** [comment] 2018-07-17 21:19
Just found the GN rule, I see that no flags were being used before either (other than --minify). Please give the `--omit-implicit-checks` a shot, we are including a lot of reified types by default and we don't have the level of optimizations we want yet without the flag.
