### ISSUE TITLE
Modular kernel compiler fails on valid code requiring inference

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#36498] opened 2019-04-05 19:12 UTC
We're seeing an error on valid code when we compile with the kernel worker.

Full repro here: https://github.com/natebosch/dart_repro/tree/kernel-unsupported-operation

You need to set up a build through `build_runner` with the "invalid" code in a separate module in order to reproduce. The particular pattern is this:

```dart
abstract class Foo {
  int get foo;
}

class Bar implements Foo {
  static int _foo = 0;

  final foo = _foo++; // Error here
}
```

The error points to the `++` and says `Internal problem: Unsupported operation: 'accept'.`

**Comment by natebosch** [comment] 2019-04-05 19:14
Full repro steps and details copied from the commit message: https://github.com/natebosch/dart_repro/commit/ab757ee27ab1ab7cbcadca185f9e4e6a91094696

In this example we:

- Have a library which is built into a separate kernel module.
- Have a class which has a field that:
  - Overrides a get
  - Does _not_ declare the type explicitly
  - Is final
  - Is assigned with `_someStaticField++`.

Compiling with kernel we see:

`Internal problem: Unsupported operation: 'accept'.`

Note that this requires https://dart-review.googlesource.com/c/sdk/+/98740
to see the error message, with the current SDK you get instead:

`Internal problem: Compiler cannot run without a compiler context.`

Repro steps:
- pub get
- pub run build_runner build

**Comment by natebosch** [comment] 2019-04-05 19:52
Here is the real world code we hit using this pattern:

https://github.com/dart-lang/sdk/blob/da4ccd08559c0252312c5f3d5cbb7c8b9460b9e5/pkg/analyzer/lib/src/task/model.dart#L41-L45

We hit this when we added some additional `export`s in the `test_core` package which was causing us to transitively import analyzer from web code in tests.

**Comment by kmillikin** [comment] 2019-04-08 11:17
I can't reproduce it because `pub get` doesn't work.

```
kmillikin@belladonna:/tmp$ git clone https://github.com/natebosch/dart_repro/
Cloning into 'dart_repro'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 45 (delta 0), reused 7 (delta 0), pack-reused 38
Receiving objects: 100% (45/45), 8.66 KiB | 4.33 MiB/s, done.
Resolving deltas: 100% (9/9), done.
kmillikin@belladonna:/tmp$ cd dart_repro/
kmillikin@belladonna:/tmp/dart_repro$ git checkout kernel-unsupported-operation 
Branch 'kernel-unsupported-operation' set up to track remote branch 'kernel-unsupported-operation' from 'origin'.
Switched to a new branch 'kernel-unsupported-operation'
kmillikin@belladonna:/tmp/dart_repro$ ~/dart.git/sdk/tools/sdks/dart-sdk/bin/pub get
Resolving dependencies... 
Git error. Command: git fetch
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by vsmenon** [comment] 2019-04-08 14:38
@natebosch - reassigning to you to look at repro.  Can you please reassign to @kmillikin after addressing his q?

**Comment by jakemac53** [comment] 2019-04-08 15:54
My guess is this is just a bad error message resulting from the ssh style git dependency overrides? You could try changing the pubspec to replace `git@github.com:` with `https://github.com/`. The repro works for me out of the box.

**Comment by natebosch** [comment] 2019-04-08 16:38
Updated the URLs in https://github.com/natebosch/dart_repro/commit/e4dcd1e0be065625e71c4228a9512f5afca8d4fd

A `pub get` should work for you now, regardless of whether you've set up your SSH keys with github.

**Comment by vsmenon** [comment] 2019-04-08 18:10
@natebosch 

I can repro, but if I add:
```
dependency_overrides:
  front_end:
    path: ../../dart/sdk/pkg/front_end
```

It seems to build fine.  Do we just need a new `front_end` published?

**Comment by vsmenon** [comment] 2019-04-08 18:17
Actually - I may have had additional edits.

**Comment by jakemac53** [comment] 2019-04-08 18:24
Fwiw a dependency_override is unlikely to have any effect here - the binaries doing this compilation all come from the sdk you are using, and not your local package dependencies.

**Comment by vsmenon** [comment] 2019-04-08 18:28
Ahh, got it.  Strange.  It's building occasionally for me.

**Comment by vsmenon** [comment] 2019-04-08 22:56
So, the error is thrown here in `SyntheticExpressionJudgment.accept`:

https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/kernel_shadow_ast.dart#L1410

with this comment:
```
    // This is designed to throw an exception during serialization. It can also
    // lead to exceptions during transformations, but we have to accept a
    // [Transformer] as this is used to implement `replaceChild`.
```

Do we need to do some desugaring in kernel worker?

FWIW, if I unconditionally invoke `return super.accept(v)` here, Nate's example builds and runs (with an `index.html`) fine.

**Comment by kmillikin** [comment] 2019-04-09 06:33
It's definitely wrong to serialize these for any reason, and we want to continue to crash with an internal problem because our assumptions have been violated.  Something is clearly going wrong, but I had to be able to reproduce the failure to figure out what.

With Nate's update I can now reproduce this and I'm working on it.

**Comment by jensjoha** [comment] 2019-04-10 08:06
I can reproduce with the following incremental compiler test:
```
# Copyright (c) 2019, the Dart project authors. Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE.md file.

# Compile an application with the option of only getting an outline.
# This is a reproduction of http://dartbug.com/36498.

type: newworld
strong: true
worlds:
  - entry: main.dart
    sources:
      main.dart: |
        abstract class Foo {
          int get foo;
        }

        class Bar implements Foo {
          static int _foo = 0;
          final foo = _foo++;
        }
    outlineOnly: true
```

I'm taking a look now to see when this is replaced when not just doing an outline.

As a note, this does not appear to be a problem introduced by using the incremental compiler --- removing the "--reuse-compiler-result --use-incremental-compiler" flags from what's send to the kernel_worker and the thing still happens.

**Comment by jensjoha** [comment] 2019-04-10 08:37
https://github.com/dart-lang/sdk/blob/66477b9fcfe00a29a35be70914cc6c4d46583550/pkg/front_end/lib/src/fasta/kernel/kernel_field_builder.dart#L87-L90

The field `foo` isn't added to the list of things we process in the outline phase (
https://github.com/dart-lang/sdk/blob/66477b9fcfe00a29a35be70914cc6c4d46583550/pkg/front_end/lib/src/fasta/kernel/kernel_target.dart#L271
) because it's an instance field.

I don't enough about inference to continue --- but maybe the above can help @kmillikin or @stefantsov ?

**Comment by kmillikin** [comment] 2019-04-11 08:03
So we know what's happening.  There is a field that overrides a getter, has an initializer, and does not have a type annotation.  Top-level type inference infers a type for the field based on overrides.  In that case it never looks at the initializer to infer its type.

Inferring types for expressions is what triggers replacing the unserializable shadow AST nodes with real serializable ones, so we can't serialize the field initializer in this state.

We're considering options....

**Comment by kmillikin** [comment] 2019-04-11 09:26
Removing the initializer from the outline works with the normal Fasta compilation flow, but I'm not sure if anything depends on the presence of this initializer in outlines (which is sort of accidental, anyway).

@natebosch [CL 99120](https://dart-review.googlesource.com/c/sdk/+/99120) seems to fix your reproduction.  Is there more extensive testing I can do?

**Comment by natebosch** [comment] 2019-04-11 16:53
@jakemac53 tried the fix and it looks good. Doesn't regress any use cases we know to test.

**Comment by vsmenon** [comment] 2019-04-15 14:19
What's the update here?  Do we just need to land @kmillikin 's CL?

@stefantsov @natebosch @jakemac53

**Comment by vsmenon** [comment] 2019-04-15 14:23
Dima will review Kevin's CL and land if this looks good.

**Closed** 2019-04-15 16:20 UTC
Labels: area-front-end, p1-high
