### ISSUE TITLE
Encountered a Dart Analysis Server error

### ISSUE THREAD

**Issue by xiangxianxiao** [dart-lang/sdk#39252] opened 2019-11-06 03:54 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1280x800  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Found element with null library: WidgetTester
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:418:31)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44:12)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:262:16)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:1965:49)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:3580:10)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:1965:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1904:17)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#9      UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:3152:35)
#10     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:3571:11)
#11     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:1900:49)
#12     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5246:32)
#13     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5226:11)
#14     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3552:13)
#15     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#16     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3594:23)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#18     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:678:10)
#19     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#20     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#21     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#22     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#25     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#26     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#27     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#34     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#40     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#42     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#43     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#44     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#45     new Future.sync (dart:async/future.dart:224:31)
#46     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _runZoned (dart:async/zone.dart:1516:10)
#50     runZoned (dart:async/zone.dart:1463:12)
#51     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#52     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#53     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#54     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_ser...
```

For additional log information, please append the contents of
file:///private/var/folders/hb/m_86d9553k9dyxrrf4tq8pc80000gn/T/report1.txt.

**Comment by thangmam** [comment] 2019-11-06 05:00
same error for me too

**Comment by keertip** [comment] 2019-11-06 09:21
Thanks for reporting the error, previously reported in #37987, please follow along there.

**Comment by keertip** [comment] 2019-11-06 09:21
Duplicate of #37987

**Closed** 2019-11-06 09:22 UTC
Labels: analyzer-crash-report, area-analyzer

**Comment by thangmam** [comment] 2019-11-06 10:32
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.7142.36`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:475:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#13     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#14     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#15     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#16     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#20     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#22     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:669:24)
#23     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#24     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#25     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#26     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#27     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:486:51)
#28     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#29     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#30     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#31     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#32     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#33     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:162:31)
#34     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#35     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#36     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#37     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#38     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:165:55)
#39     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#40     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2634:12)
#41     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#42     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#43     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#44     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:183:43)
#45     GeneralizingAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:213:7)
#46     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2624:15)
#47     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#48     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#49     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#50     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#51     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#52     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:202:7)
#53     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast...
```
