### ISSUE TITLE
WebGL texImage2DTyped broken

### ISSUE THREAD

**Issue by Fox32** [dart-lang/sdk#26267] opened 2016-04-14 19:19 UTC
I'm using texImage2DTyped for quite some time, but it stopped working in the latest Dart version (>=1.16.0-dev.0.0). Here is a minimal example.

 ```
 var canvas = document.getElementById('test') as CanvasElement;
  var gl = canvas.getContext3d();
  
  var t = gl.createTexture();
  gl.bindTexture(webgl.TEXTURE_2D, t);
  gl.texParameteri(webgl.TEXTURE_2D, webgl.TEXTURE_WRAP_S, webgl.REPEAT);
  gl.texParameteri(webgl.TEXTURE_2D, webgl.TEXTURE_WRAP_T, webgl.REPEAT);
  gl.texParameteri(webgl.TEXTURE_2D, webgl.TEXTURE_MAG_FILTER, webgl.NEAREST);
  gl.texParameteri(webgl.TEXTURE_2D, webgl.TEXTURE_MIN_FILTER, webgl.NEAREST);
  gl.texImage2DTyped(webgl.TEXTURE_2D, 0, webgl.RGBA, 128, 128, 0, webgl.RGBA, webgl.UNSIGNED_BYTE, null);

  window.console.log('test');
```

I would expect to run with only the 'test' message in the console, but instead it crashes with:

```
texImage2D$9: function(receiver, target, level, internalformat, format_OR_width, height_OR_type, border_OR_canvas_OR_image_OR_pixels_OR_video, format, type, pixels) {
   throw H.wrapException(new P.ArgumentError(false, null, null, "Incorrect number or type of arguments"));
}
```

It's not important as the generated code is already wrong, but I'm using Chrome on Windows 8.1 64bit. I also attached a full working example and hope you are able to fix it soon.

[blub.zip](https://github.com/dart-lang/sdk/files/219797/blub.zip)

**Comment by lexaknyazev** [comment] 2016-04-15 09:31
Maybe a duplicate of #26047?

**Comment by Fox32** [comment] 2016-04-15 16:07
Good point, looks like something was broken due to these changes.

**Comment by alan-knight** [comment] 2016-04-15 21:46
Yes, this is a duplicate. 1.16.0-dev.0.0 is not nearly latest. There's one pending patch, but other than that try the latest dev version.

**Closed by alan-knight** 2016-04-15 21:47 UTC

**Comment by Fox32** [comment] 2016-04-15 21:57
> Yes, this is a duplicate. 1.16.0-dev.0.0 is not nearly latest. 

@alan-knight With >=1.16.0-dev.0.0 I mean that all 1.16.0 version are broken, I trid them all with no luck.

**Comment by alan-knight** [comment] 2016-04-16 23:29
Well, they are likely to fail in different ways, since we've had a couple of different changes that affect this. Regardless, should be fixed now in bleeding edge.

**Comment by Fox32** [comment] 2016-04-17 08:29
Looking forward to that, thanks!
