### ISSUE TITLE
how to add environment variables to dart run?

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#48750] opened 2022-04-06 11:14 UTC
how to add environment variables to `dart run` to start a VM console app?

this works: `dart -Dconsole=true bin/pagebuilder_api.dart`

this doesn't: `dart -Dconsole=true run -Dconsole=true`

Dart SDK version: 2.17.0-182.2.beta (beta) (Mon Mar 28 14:06:26 2022 +0200) on "macos_x64"

**Comment by devoncarew** [comment] 2022-04-06 18:33
cc @bkonyi

**Comment by bkonyi** [comment] 2022-04-06 22:01
With:

```dart
// ~/test_proj/bin/test_proj.dart
void main(List<String> arguments) {
  print(String.fromEnvironment('foo'));
}
```

Running the following invocations from `~/test_proj` correctly outputs `bar`:

- `dart -Dfoo=bar run bin/test_proj.dart`
- `dart run -Dfoo=bar run bin/test_proj.dart`
- `dart run -Dfoo=bar`
- `dart -Dfoo=bar run`
- `dart -Dfoo=bar bin/test_proj.dart`
- `dart -Dfoo=bar run -Dfoo=bar`

As far as I can tell, this is working as intended. Without reproduction code, there's not much else I can do. I'll close this for now, but please feel free to re-open with some code samples for me to try if you're still having issues.

**Closed by bkonyi** 2022-04-06 22:01 UTC
Labels: area-dart-cli

**Comment by julemand101** [comment] 2022-04-07 05:02
@bkonyi 
I think the confusion comes from the fact that the documentation for `String.fromEnvironment`states the following:

> This constructor is only guaranteed to work when invoked as `const`. It may work as a non-constant invocation on some platforms which have access to compiler options at run-time, but most ahead-of-time compiled platforms will not have this information.

If I change your example to:
```dart
void main(List<String> arguments) {
  print('Without const: ' + String.fromEnvironment('foo'));
  print('With const: ' + const String.fromEnvironment('foo'));
}
```
I get the following result from running your examples:
```
[julemand101@argon test_proj]$ /tmp/dart-sdk/bin/dart --version
Dart SDK version: 2.17.0-266.0.dev (dev) (Fri Apr 1 14:25:07 2022 -0700) on "linux_x64"
[julemand101@argon test_proj]$ /tmp/dart-sdk/bin/dart -Dfoo=bar run bin/test_proj.dart
Without const: bar
With const: bar
[julemand101@argon test_proj]$ /tmp/dart-sdk/bin/dart run -Dfoo=bar
Building package executable... 
Built test_proj:test_proj.
Without const: bar
With const: 
[julemand101@argon test_proj]$ /tmp/dart-sdk/bin/dart -Dfoo=bar run
Building package executable... 
Built test_proj:test_proj.
Without const: bar
With const: 
[julemand101@argon test_proj]$ /tmp/dart-sdk/bin/dart -Dfoo=bar bin/test_proj.dart
Without const: bar
With const: bar
[julemand101@argon test_proj]$ /tmp/dart-sdk/bin/dart -Dfoo=bar run -Dfoo=bar
Building package executable... 
Built test_proj:test_proj.
Without const: bar
With const: 
```
The strange behavior is that when running with just `run` (without specify a dart file to run) it seems like `String.fromEnvironment('foo')` don't work if marked as `const` as recommended in the documentation.

**Comment by jodinathan** [comment] 2022-04-07 12:11
yes, indeed without `const` the `dart run -Dconsole=true` works.  

However, we use `const` not only because it is in the documentation but because it throws an exception when trying to use in a web app.

**Comment by jodinathan** [comment] 2022-04-07 12:11
@bkonyi

**Comment by bkonyi** [comment] 2022-04-07 17:16
It looks like we don't actually pass the environment variables to the compiler when `dart run` performs its pre-compilation step, which is why the `const String.fromEnvironment` fails (`String.fromEnvironment` works since the VM supports dynamically loading environment variables at runtime). This will require some work in `pub` to get this wired up.

**Comment by bkonyi** [comment] 2022-04-07 17:17
In the meantime, your best bet is to run with the script path specified (e.g., `dart run -Dconsole=true bin/script.dart`).
