### ISSUE TITLE
crash in analyzer

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/sdk#31202] opened 2017-10-23 08:08 UTC
Analyzer Feedback from IntelliJ

analyzer version : 0.30.0+2

This line cause troubles to the analyzer : 

    List<X> fromJsonList<X>(Iterable<X> l, Converter<dynamic, X> converter,{List<X> Function(Iterable<X>)  listFactory});

dartanalyzer  stack trace : 

```
Unhandled exception:
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9902)
#3      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
#4      SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9306)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#7      UnifyingAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:3168)
#8      TypeResolverVisitor.visitSimpleFormalParameter (package:analyzer/src/generated/resolver.dart:10068)
#9      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9301)
#10     DefaultFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3494)
#11     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#12     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#13     UnifyingAstVisitor.visitDefaultFormalParameter (package:analyzer/dart/ast/visitor.dart:2974)
#14     DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3490)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#16     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4853)
...
```

**Comment by alorenzen** [comment] 2017-11-01 22:36
Duplicate of #31107?

**Comment by kevmoo** [comment] 2017-11-01 23:17
Yup!

**Closed by kevmoo** 2017-11-01 23:17 UTC
Labels: area-analyzer
