### ISSUE TITLE
`Stream.asyncMap` bug in weak mode + nnbd sdk

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41465] opened 2020-04-13 17:44 UTC
If you return null from the closure passed `Stream.asyncMap` in weak mode (with the nnbd sdk) today you will hit an [`unreachable` error](https://github.com/dart-lang/sdk/blob/286501b0f1fc74efa5a513908b8c864d4a75dddd/sdk_nnbd/lib/async/stream.dart#L527
).

Repro program:

```dart
void main() {
  var stream = Stream.fromIterable([1, 2, 3, 4]);
  var eventsStream =
      stream.asyncMap((i) => i % 2 == 0 ? i : null).where((i) => i != null);
  eventsStream.listen(print);
}
```

**Comment by kevmoo** [comment] 2020-04-13 18:44
CC @lrhn

**Comment by franklinyow** [comment] 2020-04-13 19:43
Can I get an assessment on the bug?  Is it a blocker for unfork?

**Comment by natebosch** [comment] 2020-04-13 19:49
> Is it a blocker for unfork?

Yes. This will break existing code. It should be considered a blocker.

**Comment by vsmenon** [comment] 2020-04-13 21:03
@lrhn @leafpetersen 

What is the right resolution here?  Do we need (and can we) undo the change that triggers the error?

**Comment by vsmenon** [comment] 2020-04-13 21:05
Or is this just a plain bug in the new SDK?

**Comment by leafpetersen** [comment] 2020-04-13 21:19
The issue is the following code:

```dart
   if (newValue is Future<E>) {
          subscription.pause();
          newValue.then(add, onError: addError).whenComplete(resume);
        } else {
          if (newValue is! E) {
            throw "unreachable"; // TODO(lrn): Remove when type promotion works.
          }
          controller.add(newValue);
        }
```

which assumes that given a value `x` of type `FutureOr<E>`, either `x is Future<E>` or `x is E` will be true.  This doesn't hold in pre-nnbd/weak mode Dart because `null is Future<E>` and `null is E` are both false unless `E` is a nullable type (or a top type).

The code above should be changed to something like:

```dart
   if (newValue is Future<E>) {
          subscription.pause();
          newValue.then(add, onError: addError).whenComplete(resume);
        } else {
          if (newValue is! E && newValue != null) {
            throw "unreachable"; // TODO(lrn): Remove when type promotion works.
          }
          controller.add(newValue);
        }
```

We should probably audit the ported core libraries for similar patterns.  Shouldn't be hard to fix.  I can take a look, probably tomorrow.

**Comment by leafpetersen** [comment] 2020-04-14 01:40
https://dart-review.googlesource.com/c/sdk/+/143333

**Comment by leafpetersen** [comment] 2020-04-14 19:33
Fix landed.

**Closed by leafpetersen** 2020-04-14 19:33 UTC
Labels: NNBD, P1, area-library, library-async
