### ISSUE TITLE
Port in SocketException message seems to be local port not remote port

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27899] opened 2016-11-25 09:27 UTC
I am writing some code that connects to port 10002. I am confident this is the value of the port argument I'm passing to `Socket.connect`.

When the connection fails, I get a message such as the following:

```
SocketException: OS Error: Connection reset by peer, errno = 104, address = tv., port = 39895
```

...or:

```
SocketException: OS Error: Broken pipe, errno = 32, address = tv., port = 39897
```

These are from consecutive connection attempts. Notice the ports are two apart. Notice that they are not the specified port. I suspect they are local ports, in fact.

I'm totally fine with us giving the local port, but we should at least label it as such. The current message makes it sound like it's the port used with the given address (i.e. the remote port). The remote port is certainly the more useful port to give.

**Comment by floitschG** [comment] 2016-11-27 17:47
I haven't yet tried to reproduce, but if you have a simple example, it would probably make it easier for us.

(It would also exclude stupid cases where the message is different depending on the OS, and we spend trying to reproduce on an architecture that isn't affected).

**Comment by sgjesse** [comment] 2016-11-28 07:24
This is a duplicate of #12693.

**Closed by sgjesse** 2016-11-28 07:24 UTC
Labels: area-library, library-io, Resolution: duplicate
