### ISSUE TITLE
Performance Considerations for writing Dart code

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/sdk#39006] opened 2019-10-20 22:03 UTC
I found out the hard way that I am unable to write efficient Dart code for image processing.  
Initially I wrote code to modify and compare byte lists composing images in real time in a Flutter application. After tinkering with it for a long time now, I am still not able to do any operations on even medium sized images in real time, i.e. modify and compare lists with more than a million elements multiple times a second at 60 FPS in Flutter.  
The operations I use are `for`-loops for modification (just a few thousand iterations per modification) and `List.from` and the likes for copying and later comparing using `ListEquality`.  See [this issue](https://github.com/flutter/flutter/issues/31598#issuecomment-511510444) for more context.

Additionally, I had to find out that the `image` library is slow in Dart. Specifically, the NeuQuant implementation becomes unusable for HD GIFs with more than a few frames. See e.g. [this](https://github.com/brendan-duncan/image/pull/152#issuecomment-544277927).

To me it seems like there is something wrong with Dart's performance here because the runtimes of mentioned programs quickly scale up exponentially when they potentially should not.  
I can recall from working with Flutter that the garbage collector was constantly collecting in these cases, which seemed to drastically decrease performance.

---

Obviously this is extremely broad, however, my intention is to ask for broad advice, i.e. for performance considerations.  
In other languages, running loops millions of times does not seem to be a problem, but in Dart it seems like a barrier is hit quite fast. Is there anything obvious that should be pointed out or are there any other resources that could potentially help me and others?

I only found https://github.com/dart-lang/sdk/issues/6197, but I could not take anything away from that conversation.

**Comment by mraleph** [comment] 2019-10-21 10:18
The code produced by Dart AOT compiler sometimes has a much worse performance then the code produced by Dart JIT compiler - simply because AOT compiler does not have access to the kind of dynamic type feedback that JIT compiler has, so it sometimes produces slow generic operations and calls where JIT compiler can produce inlined and specialised code. 

The broad advice I could give here is the following: If you stumble upon the code that performs slower than anticipated and profiling it does not make it obvious to you how to optimise it - then maybe Dart compiler is not doing a good job optimising it. In this case try to create a simple self-contained reproduction (e.g. Flutter application that tries to display large GIF) and submit an issue about it. We will take a look and analyse potential ways to address the performance issue - and if any of them bring performance down to acceptable numbers. 

However there is also another angle: these days, given that [dart:ffi allows you to interop with C code](https://flutter.dev/docs/development/platform-integration/c-interop) there is very little reason to write performance sensitive code like this in pure Dart. There is a variety of highly optimised image codec implementations available in lower level languages (some even use handwritten platform specific assembly for performance reasons). You might be in a much better spot if you just bind to one of these implementations via `dart:ffi`.

I will close this issue - but let me know if you have any further questions. Or if you would like us to profile something using image library - just post a benchmark here.

**Closed by mraleph** 2019-10-21 10:18 UTC

**Comment by creativecreatorormaybenot** [comment] 2019-10-21 11:51
> If you stumble upon the code that performs slower than anticipated and profiling it does not make it obvious to you how to optimise it

I suppose that I will read through https://dart-lang.github.io/observatory/. Until now, I have not ever been able to gather any useful information from the observatory. I guess what I am looking for is "what is bad when you see it". Currently, I can look at the CPU profile and only think to myself "interesting, exactly what I expected to see".

I can look into `dart:ffi` as well as it seems to work synchronously, however, I doubt that it will help rendering to the canvas as this can still only be done asynchronously (see https://github.com/flutter/flutter/issues/37180#issue-474139918).

**Comment by creativecreatorormaybenot** [comment] 2019-10-22 14:16
[This talk](https://youtu.be/y39pZCExsOs) is very useful for profiling Dart performance 👍
