### ISSUE TITLE
Guards don't promote in switch expressions

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#52375] opened 2023-05-12 18:37 UTC
I'm looking into the issue reported in [this tweet](https://twitter.com/elias_andualem8/status/1656746615682613248). I can repro it with:

```dart
main() {
  String? s = null;
  var length = switch (0) {
    _ when s != null => s.length,
    _ => 0,
  };

  switch (0) {
    case _ when s != null: s.length;
  };
}
```

The switch statement is fine, but the switch expression yields:

```
temp.dart:5:27: Error: Property 'length' cannot be accessed on 'String?' because it is potentially null.
Try accessing using ?. instead.
    _ when s != null => s.length,
                          ^^^^^^
```

Do we not do type promotion in switch expression guards?

@stereotype441

**Comment by stereotype441** [comment] 2023-05-12 18:41
Yeah, this is a known issue that I discovered just before 3.0 shipped, when there was no longer time to cherry-pick a fix. The fix has been cherry-picked to stable, and will ship in 3.0.1.

Tracking issue is here: https://github.com/dart-lang/sdk/issues/52241

**Comment by stereotype441** [comment] 2023-05-12 18:42
Duplicate of #52241

**Closed by stereotype441** 2023-05-12 18:42 UTC
Labels: area-analyzer, area-fe-analyzer-shared
