### ISSUE TITLE
Introduce intersection types in strong-mode analyzer?

### ISSUE THREAD

**Issue by ochafik** [dart-lang/sdk#26350] opened 2016-04-27 21:34 UTC
This would allow precise analysis of the following (real-world) case:

``` dart
if (entity is Observable && entity is Map) {
  takeMap(entity);
  //      ^
  // [WARNING] The argument type 'Observable' cannot be assigned to the parameter type 'Map'.
}
```

cc/ @leafpetersen 

(of course, the workaround here is to pass `entity as dynamic`, but it just feels wrong)

**Comment by bwilkerson** [comment] 2016-04-27 21:49
Or reverse the order of the test:

    if (entity is Map && entity is Observable) {

**Comment by ochafik** [comment] 2016-04-27 22:11
Sure, that as well (it does feel less wrong :-) ), although the general case would be:
```dart
if (entity is Observable && entity is Map) {
  takeMap(entity);
  takeObservable(entity);
}
```

**Comment by floitschG** [comment] 2016-04-28 09:57
This is something we would like to improve.
Similarly annoying:

``` dart
if (o is! List) return null;
o[x];  // Not inferred to be of type List.
```

or 

``` dart
if (o.x is List) {
  o.x[0];  // Not inferred to be a List.
}
```

**Comment by ochafik** [comment] 2016-04-28 12:32
@floitschG +1, already filed as https://github.com/dart-lang/sdk/issues/26195

**Comment by lrhn** [comment] 2018-06-25 06:08
Closing as duplicate of #25565 (enhanced type promotion).

**Closed by lrhn** 2018-06-25 06:08 UTC
Labels: Type: enhancement, area-language
