### ISSUE TITLE
analysis_server/pubspec.yaml list analyzer: ^0.27.0 as dependency which lacks the field AnalysisOptionsImpl.enableAsync

### ISSUE THREAD

**Issue by AlexanderJohr** [dart-lang/sdk#25628] opened 2016-01-31 18:16 UTC
I'm trying to make my first steps in this project, and maybe it's just me doing something wrong.

When I open the "sub-project" **analysis_server** in _/pkg/analysis_server/_ and run the tests I get an error in the test _test_embedder_options_ in _context_manager_test.dart_ in this line:

`expect(context.analysisOptions.enableAsync, isFalse);`

**Error:**

> NoSuchMethodError: method not found: 'enableAsync'
>   Receiver: Instance of 'AnalysisOptionsImpl'

When I open the referenced file in the package **analyzer** (_.pub-cache/hosted/pub.dartlang.org/analyzer-0.27.1+2/lib/src/generated/engine.dart_) I realized that the method/field really is missing.

But in the same file in the cloned dart-sdk repository which I am working in, I found the field:
`/**`
`* A flag indicating whether analysis is to enable async support.`
`*/`
`bool enableAsync = true;`

The version in the _pubspec.yaml_ is _0.27.2-alpha.1_. When I now use this version in _analysis_server/pubspec.yaml_:  

`
dependencies:
  analyzer: 0.27.2-alpha.1
`

Then the error is gone.

Am I supposed to link the dependencies myself in my project setup, or is there another solution, to use the packages from the dart-sdk in my cloned repository rather than to get them from _/hosted/pub.dartlang.org/_? Is this maybe an error in the _analysis_server/pubspec.yaml_ file?

**Comment by bwilkerson** [comment] 2016-01-31 19:07
> I'm trying to make my first steps in this project, and maybe it's just me doing something wrong.

Welcome!

Thanks for creating this issue. In case you're not aware, there is also a mailing list available for folks looking into either the analysis_server, analyzer, or analyzer_cli packages: analyzer-discuss@dartlang.org.

> Is this maybe an error in the analysis_server/pubspec.yaml file?

Yes, this is an error in the analysis_server's pubspec file that we should fix; it's clearly specifying the wrong version of the analyzer package.

Unfortunately, this kind of error occurs easily because of the way this project is structured. Within the `sdk` repo there are a few packages under `pkg`, analysis_server and analyzer being two of them. When the SDK is built, the version information in the pubspec files for all of these packages is ignored (the SDK is always built from from a single commit in the repo, and it uses the version of these packages that were committed at that commit). As a result, as we're developing these packages we always run with the equivalent of a dependency override for analyzer so that at any given commit the two packages will be in sync.

That doesn't excuse our sloppiness, nor make this less of a bug; it only explains why we get into this state so easily.

**Comment by AlexanderJohr** [comment] 2016-01-31 20:02
Thank you for this detailed explanation!

Is there anything I can do to help address this issue? A suggestion could be to link the dependencies via a relative address like this:

`analyzer:`
&nbsp;&nbsp;`path: ../analyzer`

Although it currently breaks my Pub Get with this error:

> Package dart_style has no versions that match >=0.2.0 <0.3.0 derived from:
> - analysis_server depends on version >=0.2.0 <0.3.0

Which I don't understand, as i didn't change the dart_style dependency. Maybe this is another issue?

**Comment by bwilkerson** [comment] 2016-02-01 15:11
I'm not sure why that would break pub get, but it wouldn't work when we start publishing analysis_server as a separate package because the path would be wrong for people who didn't download the SDK.

We've thought about it a lot, and I think the issue is that we're in an unusual situation by trying to write code that works both inside and outside the SDK. So, while I appreciate the offer for help, I'm not sure there's anything that can reasonably be done.

**Comment by srawlins** [comment] 2023-04-13 00:36
analysis_server is now private API.

**Closed by srawlins** 2023-04-13 00:36 UTC
Labels: area-analyzer, P2, type-bug
