### ISSUE TITLE
Finally clause won't be executed if throwing a future error inside a runZoned with onError handler

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#33097] opened 2018-05-11 04:40 UTC
* Dart SDK Version 1.24.3

For example,
```
import 'dart:async';

main() async {
  try {
    print('start');
    await doTest();
  } finally {
    print('end');
  }
}
doTest() async {
  return runZoned(() {
    return new Future.error(new Error());
  }, onError: (e) {
    print('onError');
    throw e; // if comment out this line, the future won't be completed
  });
}
```

If you run this code, you will see "start" and "onError", the message of "end" won't be shown.
Another issue is that, if we comment out `throw e;` inside the `onError` handler, the future error won't be completed forever, is that a bug?

**Comment by jumperchen** [comment] 2018-05-11 06:07
dart version `2.0.0-dev.49.0` has the same issue.

**Comment by vsmenon** [comment] 2018-05-11 15:55
@lrhn

**Comment by matanlurey** [comment] 2018-05-11 17:40
This is a feature, not a bug. I believe @natebosch and @jakemac53 know it well.

Here is an [example of the code necessary](https://github.com/dart-lang/build/blob/d8bbfbbd48cd5f626725ddfb1352f066811fde3d/build/lib/src/builder/logging.dart#L20-L37) to always complete a `runZoned`:

```dart
Future<T> runZonedAlwaysComplete<T>(Future<T> Function() run) {
  final onDone = new Completer<T>();
  runZoned(
    run,
    onError: (e, s) {
      if (!onDone.isCompleted) {
        onDone.completeError(e, s);
      }
    },
  ).then((result) {
    if (!onDone.isCompleted) {
      onDone.complete(result);
    }
  });
  return onDone.future;
}
```

**Comment by jumperchen** [comment] 2018-05-14 03:51
ok, if that's a feature, is there any document to mention such case that we should handle the complete code by ourself even if use the syntax sugar of `async`?

So the original issue of "Finally clause won't be executed" is a feature as well?

**Comment by tomyeh** [comment] 2018-05-14 10:06
@matanlurey If it is spec, are you telling us the `finally` clause won't be guaranteed to run? Then, does it mean we shall never use try/finally with await?

```
try {
   await foo();
} finally {
  this_statement_may_or_may_not_run(); //spec!?
}
```

I know it is caused by a new error zone, but how do we know it? Dig in every library we ever use? Or, it is the library's job if it starts an error zone? If so, can compiler help to pick up the problem?

**Comment by lrhn** [comment] 2018-05-14 10:32
Yes, the finally block is not guaranteed to run.
The finally block will run *when* the future returned by `foo()` completes. That may never happen, and the program can end before it does.

It's an implementation detail whether your program hangs or it terminates at that point, when it knows that no further progress will ever be made. The VM terminates when no code is running, all event loops, timer queues, and other scheduled task queues are empty, and there are no open receive ports. That's the termination criterion it uses for all programs.

I've [#23797](previously argued) that such a dead-locked await should hang the program, only because it makes this particular case easier to understand for users debugging, not because it makes any other difference - the finally block won't run in either case.

**Comment by emeyex** [comment] 2019-03-07 06:04
Was about to add a new issue about the following situation, but then I found this ticket. I get the feeling I may be wading into a controversial topic, but would just like to add my 2 cents that it seems unintuitive that the following code exits without printing the result (this seems to be at the root of the confusion over the finally block not getting hit in this issue):
```
import 'dart:async';
main() async {
  final result = await runZoned(() {
    // throw 'ERROR'!; // prints result
    return Future.error('ERROR!'); // NEVER prints result
  }, onError: (err) {
    print('Caught error: $err');
  });
  print('result: $result');
}
```
Why is this a ~feature~"feature"? Why should a synchronous error return control to `main` by returning `null`, but an async one (and in particular, one that is awaited) not? There are probably good reasons, they're just not jumping out at me. It seems brittle to require the caller of some API to know so much about the internals of whatever is being called, particularly when your goal is usually just "make sure no errors leak out, and then continue." Maybe some form of `runZonedAlwaysComplete` should be offered at the SDK level as an alternative?

**Comment by lrhn** [comment] 2020-10-02 07:35
The behavior here is inevitable when we have error zones making futures never compete.
Closing this issue in favor of https://github.com/dart-lang/sdk/issues/39825.

**Closed by lrhn** 2020-10-02 07:35 UTC
Labels: area-library, library-async
