### ISSUE TITLE
 Tried to initialize from a previous compilation 

### ISSUE THREAD

**Issue by Andrious** [dart-lang/sdk#36992] opened 2019-05-17 12:09 UTC
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3191393/initialize_from.dill.gz)

**Comment by a-siva** [comment] 2019-05-24 22:51
@Andrious can you provide more details or reproduction instructions for this, the information provided here is not sufficient for us to root cause the issue.

**Comment by Andrious** [comment] 2019-05-24 22:56
At this time, no.  If and when it's encountered again, I will make efforts to provide more details.

**Comment by a-siva** [comment] 2019-05-24 23:13
This appears to be a duplicate of #37043

**Comment by jensjoha** [comment] 2019-06-12 12:52
Thank you for taking the time to report this issue.

This appear to be the same thing as in #36759.
To summarize, everything is fine - the compile that reported this will be slower, but the output will be perfectly fine. It is caused by an updated flutter sdk.

For instance, if you updated from flutter beta to flutter master around the time where you reported this issue (i.e. the file we're trying to initialize from was created on flutter beta, now we're trying to initialize from it on flutter master) - you'll get a warning about not being able to initialize from it (because of a change in the sdk, specifically in flutter/engine@3e47b4b the getter "left" on class "Rect" was removed and became a field instead).
It will ultimately be fixed via https://github.com/dart-lang/sdk/issues/36032 and our initial fix (5eff2a0374cb89e335c138889c5125b48d12894d) would have caught this to (so the error wouldn't have been issued).

**Closed by jensjoha** 2019-06-12 12:52 UTC
Labels: area-front-end, closed-duplicate, p2-medium, type-bug
