### ISSUE TITLE
Mac analysis tests failing on bot, not clear why

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#29960] opened 2017-06-21 00:17 UTC
The Mac analyzer bot analyzer-mac10.11-release-be is having many failing tests. These are similar to problems that were in a previous commit that got reverted, and it fixed the other bots. https://github.com/dart-lang/sdk/commit/9755a98b003a09a0f3aa76b610bcf715e58b0baa

I did a force build on that bot and it was green, but then the next commit after that had the same sorts of failures again. So it seems like this is some kind of problem with the bot, but I don't know what.
@whesse @bwilkerson @bkonyi

**Comment by bkonyi** [comment] 2017-06-21 00:26
It doesn't look like any of the tests that were failing as a result of the change that you reverted are still failing. Maybe the bot is in a bad state and needs to be reset?

**Comment by mraleph** [comment] 2017-06-26 12:29
Is somebody looking into this?

**Comment by mraleph** [comment] 2017-06-27 12:37
I am looking into this. I could not reproduce this issue locally, but I can reproduce this one on the bot (vm663-m3) but spawning 20 instances of the same test in parallel. Most of them pass but few of them fail, which further supports my suspicion that this is a misoptimization issue.

**Comment by mraleph** [comment] 2017-06-27 14:59
My previous comment should be completely disregarded, because I was misreading the output of the test. In reality spawning tests in parallel does not reproduce the problem. Also this is not a VM bug. 

This is a bug in the analyzer batch runner - it seems that it does not clear analysis options between test runs, so once we run a test that has `analysis_options.yaml` lying next to it we pick that up and that causes cascading failures on subsequent tests running in the same batch runner. You can reproduce this like by starting batch mode and then sending `tests/utils/dummy_compiler_test.dart` and `tests/co19/src/Language/Expressions/Identifier_Reference/undeclared_identifier_t08.dart` to it (in this order!):

```
$ out/ReleaseX64/dart-sdk/bin/dartanalyzer --batch
>>> BATCH START
--ignore-unrecognized-flags --packages=.packages --format=machine --no-hints tests/utils/dummy_compiler_test.dart --enable_type_checks
--ignore-unrecognized-flags --packages=.packages --format=machine --no-hints tests/co19/src/Language/Expressions/Identifier_Reference/undeclared_identifier_t08.dart --enable_type_checks
>>> EOF STDERR
>>> TEST PASS 7660ms
ERROR|STATIC_WARNING|UNDEFINED_IDENTIFIER|/usr/local/google/home/vegorov/src/dart/sdk/tests/co19/src/Language/Expressions/Identifier_Reference/undeclared_identifier_t08.dart|18|39|10|Undefined name 'undeclared'.
>>> EOF STDERR
>>> TEST FAIL 7809ms
```
 
As you can see `STATIC_WARNING` got promoted to an `ERROR` severity because batch runner thinks that it is running in the batch mode (most likely because `analysis_options.yaml` next to  `tests/utils/dummy_compiler_test.dart` has `strong-mode: true`). In reality this test should produce just a `WARNING`:

```
$ out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=.packages --format=machine --no-hints tests/co19/src/Language/Expressions/Identifier_Reference/undeclared_identifier_t08.dart --enable_type_checks
WARNING|STATIC_WARNING|UNDEFINED_IDENTIFIER|/usr/local/google/home/vegorov/src/dart/sdk/tests/co19/src/Language/Expressions/Identifier_Reference/undeclared_identifier_t08.dart|18|39|10|Undefined name 'undeclared'.
```

This introduces spurious test failures on buildbots - different tests fail depending on which batch runner gets into this strange state. 

I am not sure who owns this, so I am assigning this to @scheglov for triage.

**Comment by scheglov** [comment] 2017-06-27 16:12
https://codereview.chromium.org/2956093002/

**Comment by scheglov** [comment] 2017-06-27 16:33
https://github.com/dart-lang/sdk/commit/bc345836610725c629e0fc2007ad349e400ec272

**Closed by scheglov** 2017-06-27 16:33 UTC
Labels: gardening
