### ISSUE TITLE
New flutter web project fails to run

### ISSUE THREAD

**Issue by icatalud** [dart-lang/sdk#37496] opened 2019-07-11 03:49 UTC
Cannot run dart server on a fresh new flutter web project, it throws never ending compiler errors. Using vs code on windows 10.

I'm able to enter the web page, however it does not display any widget.
&nbsp;

> [SEVERE]build_web_compilers:ddc on package:collection/src/priority_queue.ddc.module (cached): Error compiling dartdevc module:collection|lib/src/priority_queue.ddc.js
> 
> We're sorry, you've found a bug in our compiler.
> You can report this bug at:
>     https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
> Please include the information below in your report, along with
> any other information that may help us track it down. Thanks!

>    dartdevc -k arguments: --dart-sdk-summary=C:\Users\griff\Downloads\flutter\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\griff\AppData\Local\Temp\scratch_space72bd2522-a38b-11e9-8239-34f64b6c3f5d\packages/collection/src/iterable_zip.ddc.js --source-map --packages=file:///C:/Users/griff/AppData/Local/Temp/kernel_builder_72bd252b-a38b-11e9-8239-34f64b6c3f5d/.packages --module-name=packages/collection/src/iterable_zip --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:collection/src/iterable_zip.dart
>     dart --version: 2.5.0-dev.0.0.flutter-b5aeaa6796 (Thu Jul 4 00:57:23 2019 +0000) on "windows_x64"
> 
> Bad state: Expected to get sdk digest at null
> #0      initializeIncrementalCompiler 
> package:front_end/…/api_unstable/ddc.dart:149
> <asynchronous suspension>
> #1      _compile  (package:dev_compiler/src/kernel/command.dart:252:27)
> <asynchronous suspension>
> #2      compile  (package:dev_compiler/src/kernel/command.dart:43:18)
> <asynchronous suspension>
> #3      compile  (package:dev_compiler/src/compiler/shared_command.dart:408:12)
> #4      _CompilerWorker.performRequest.<anonymous closure>  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
> #5      _rootRun  (dart:async/zone.dart:1124:13)
> #6      _CustomZone.run  (dart:async/zone.dart:1021:19)
> #7      _runZoned  (dart:async/zone.dart:1516:10)
> #8      runZoned  (dart:async/zone.dart:1463:12)
> #9      _CompilerWorker.performRequest  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
> <asynchronous suspension>
> #10     AsyncWorkerLoop.run.<anonymous closure> 
> package:bazel_worker/…/worker/async_worker_loop.dart:33
> #11     _rootRun  (dart:async/zone.dart:1124:13)
> #12     _CustomZone.run  (dart:async/zone.dart:1021:19)
> #13     _runZoned  (dart:async/zone.dart:1516:10)
> #14     runZoned  (dart:async/zone.dart:1463:12)
> #15     AsyncWorkerLoop.run 
> package:bazel_worker/…/worker/async_worker_loop.dart:33
> <asynchronous suspension>
> #16     main  (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
> <asynchronous suspension>
> #17     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:32)
> #18     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by mraleph** [comment] 2019-07-11 10:08
Duplicate of #37490

**Closed by mraleph** 2019-07-11 10:08 UTC

**Comment by smileToWxm** [comment] 2019-07-16 01:50
dark 2.5.0 是测试版，替换成 2.4的版本 就可以了
