### ISSUE TITLE
[vm/tfa] Infer variable non-nullability after a test with null

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#40224] opened 2020-01-18 15:51 UTC
We would like to infer the non-nullability of the result of code like:

```dart
x ?? 1.0
```

or 

```dart
x == null ? 1.0 : x
```

or 

```dart
if (x != null) {
  return x;
}
return 1.0;
```

This will be possible after Alex's work on control-flow sensitivity in TFA: https://dart-review.googlesource.com/c/sdk/+/131740

We would like to implement this support soon to unbox several important fields in Flutter, after https://dart-review.googlesource.com/c/sdk/+/131824 lands (most notably, fields of the `Rect`, `Size` and `Offset` classes). If these fields are unboxed via Victor's work, we will measure significant improvement on Flutter Gallery code size and several Flutter benchmarks.

Alex: are you planning to look at this soon? If not, would you mind letting Victor take a stab at it?

/cc @alexmarkov @victoragnez @mkustermann  @mraleph

**Comment by alexmarkov** [comment] 2020-01-19 14:39
@sjindel-google I'm working on this improvement.

**Comment by alexmarkov** [comment] 2020-01-23 21:52
@sjindel-google I implemented non-nullability inference from comparisons with nulls in https://dart-review.googlesource.com/c/sdk/+/132968, but unfortunately it cannot make those fields in Flutter non-nullable.

`dart.ui::Rect` has nullable fields because those fields could be initialized from parameters of `Rect.fromLTRB` constructor which is an entry point (it can be called from non-Dart code and we don't make any assumptions about values of its arguments, so they could be null).
https://github.com/flutter/engine/blob/29e857ca2c8643416802b01c2600031df94e5f02/lib/ui/geometry.dart#L617-L618

`dart.ui::OffsetBase` has nullable fields for similar reason: entry point `_updateWindowMetrics` from `dart:ui` creates `Size` object, passing arguments to the `Size` constructor which forwards them to `OffsetBase`. Both `Size` and `Offset` extend `OffsetBase`.
https://github.com/flutter/engine/blob/29e857ca2c8643416802b01c2600031df94e5f02/lib/ui/hooks.dart#L19-L41

**Comment by mraleph** [comment] 2020-01-27 09:10
@alexmarkov Do you know why `fromLTRB` is actually marked as entry-point? I don't seem to find any C++ code that directly accesses it. I think it might be a mistake that it is marked as such.

**Comment by mkustermann** [comment] 2020-01-27 13:09
Thanks for investigating, Alex!

> dart.ui::OffsetBase has nullable fields for similar reason: entry point _updateWindowMetrics from

We can just make this method check for null and throw if any arguments are null. Doing so should give the control-flow sensitive TFA the information to infer the field types to be non-nullable, right?

**Comment by alexmarkov** [comment] 2020-01-27 18:22
@mraleph It looks stale - I can't find any uses either. Git blame shows that `Rect.fromLTRB` entry point was migrated from an old `dart_vm_entry_points.txt` file which predates pragmas. We can try to remove it and see if anything breaks.

@mkustermann Yes this should work.

**Closed** 2020-01-27 21:35 UTC
Labels: area-vm, tfa, type-performance, vm-aot-code-size

**Comment by alexmarkov** [comment] 2020-01-28 01:17
I tried changing Flutter to make `OffsetBase` and `Rect` fields non-nullable. These fields are really popular and there are actually multiple reasons why they are nullable.

I did the following changes in the engine:

```patch
diff --git a/lib/ui/geometry.dart b/lib/ui/geometry.dart
index 11849d3a8..0e52c7780 100644
--- a/lib/ui/geometry.dart
+++ b/lib/ui/geometry.dart
@@ -614,7 +614,6 @@ class Size extends OffsetBase {
 /// ```
 class Rect {
   /// Construct a rectangle from its left, top, right, and bottom edges.
-  @pragma('vm:entry-point')
   const Rect.fromLTRB(this.left, this.top, this.right, this.bottom)
     : assert(left != null),
       assert(top != null),
diff --git a/lib/ui/hooks.dart b/lib/ui/hooks.dart
index 7972efc9f..4dd58b2d0 100644
--- a/lib/ui/hooks.dart
+++ b/lib/ui/hooks.dart
@@ -36,6 +36,8 @@ void _updateWindowMetrics(
   double systemGestureInsetBottom,
   double systemGestureInsetLeft,
 ) {
+  if (width == null) throw ArgumentError('width argument should not be null');
+  if (height == null) throw ArgumentError('height argument should not be null');
   window
     .._devicePixelRatio = devicePixelRatio
     .._physicalSize = Size(width, height)
```

and the following changes in flutter:
```patch
diff --git a/packages/flutter/lib/src/rendering/paragraph.dart b/packages/flutter/lib/src/rendering/paragraph.dart
index 5e9d800a9..727efd9f8 100644
--- a/packages/flutter/lib/src/rendering/paragraph.dart
+++ b/packages/flutter/lib/src/rendering/paragraph.dart
@@ -615,6 +615,8 @@ class RenderParagraph extends RenderBox
                 fadeEnd = size.width;
                 fadeStart = fadeEnd - fadeSizePainter.width;
                 break;
+              default:
+                throw 'Unexpected textDirection';
             }
             _overflowShader = ui.Gradient.linear(
               Offset(fadeStart, 0.0),
diff --git a/packages/flutter/lib/src/widgets/image.dart b/packages/flutter/lib/src/widgets/image.dart
index edc5d274c..9066267ec 100644
--- a/packages/flutter/lib/src/widgets/image.dart
+++ b/packages/flutter/lib/src/widgets/image.dart
@@ -1006,10 +1006,12 @@ class _ImageState extends State<Image> with WidgetsBindingObserver {
   }
 
   void _resolveImage() {
+    final width = widget.width;
+    final height = widget.height;
     final ImageStream newStream =
       widget.image.resolve(createLocalImageConfiguration(
         context,
-        size: widget.width != null && widget.height != null ? Size(widget.width, widget.height) : null,
+        size: width != null && height != null ? Size(width, height) : null,
       ));
     assert(newStream != null);
     _updateSourceStream(newStream);
```

However, it was still not enough to make those fields non-nullable.
The last problem I investigated happened in `RenderStack.performLayout` method, where there is a cycle in data flow which was approximated suboptimally, causing `Size` constructor invocation with just a static type (nullable double). I think we need https://github.com/dart-lang/sdk/issues/40256 to fix this case.

Also, this looks very fragile without NNBD - a failure to infer non-nullability at any constructor call site makes fields nullable.

**Comment by rakudrama** [comment] 2020-01-28 02:03
I have found with dart2js (which has narrowing and phis in the type graph to model control flow) that it is necessary to write classes with factory constructors to ensure all initialization paths are inferrable as non-null.

**Comment by mkustermann** [comment] 2020-01-28 12:48
When I suggested throwing if arguments are `null`, I assumed we make a factory constructor.

Though I realize now that the issue is that these classes have a public `const` constructor, which can be also used with `new`.
