### ISSUE TITLE
_getCpuProfileTimeline - Add file path and stack depth

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/sdk#36718] opened 2019-04-23 17:51 UTC
In the response for _getCpuProfileTimeline, each stack frame looks like this: 
```
      "140206380921856-1":{  
         "category":"Dart",
         "name":"thread_start"
      },
```
In order to offer the best CPU profiling experience in DevTools, we need more information.

We need the following to be included in the JSON for each stack frame:
1) the file path for the frame
2) the stack depth of the frame

**Comment by bkonyi** [comment] 2019-04-25 19:57
Just curious, what do you need the stack depth for exactly? The profiler doesn't necessarily capture full stacks for various reasons (e.g., if the stack is too deep, walking the stack takes too long, etc) so we might not be able to provide that information.

**Comment by kenzieschmoll** [comment] 2019-04-25 20:16
I explain the need for stack depth here: https://github.com/flutter/devtools/issues/579. Basically we'd like to have it so the truncated samples don't get lost in the truncation. When they are under the [Truncated] stack frame, it doesn't give an accurate depiction of the flame graph because, in reality, some of the events should be combined with the non-truncated stack frames in the UI. There are pictures to explain this on the linked issue.

**Comment by bkonyi** [comment] 2019-04-25 21:06
> I explain the need for stack depth here: [flutter/devtools#579](https://github.com/flutter/devtools/issues/579). Basically we'd like to have it so the truncated samples don't get lost in the truncation. When they are under the [Truncated] stack frame, it doesn't give an accurate depiction of the flame graph because, in reality, some of the events should be combined with the non-truncated stack frames in the UI. There are pictures to explain this on the linked issue.

If I understand correctly, you don't exactly need the actual stack depth, just IDs for frames? For example, in the case of a truncated stack we would never be able to provide an accurate depth since we don't know how deep the true stack goes.

@rmacnak-google, do you mind sharing your thoughts on this?

**Comment by kenzieschmoll** [comment] 2019-04-25 21:40
IIRC, there are cases where a frame can appear multiple times in the same stack. In this case, would each frame have a unique id? Otherwise, we will have the same issue we'd have now if we tried to match on name equality.

**Comment by bkonyi** [comment] 2019-04-25 21:58
> IIRC, there are cases where a frame can appear multiple times in the same stack. In this case, would each frame have a unique id? Otherwise, we will have the same issue we'd have now if we tried to match on name equality.

When `_getCpuProfileTimeline` is invoked in the VM, it assigns an ID as part of the key which takes the form of "isolateId-frameID". This ID should be unique for each frame as the ID is incremented as we traverse each frame and their children (to be clear, the ID counter has nothing to do with the current stack depth). If you're just requiring that each frame has a unique identifier, I think the existing key should be good enough for that purpose.

**Comment by kenzieschmoll** [comment] 2019-04-25 22:07
I don't think that will work because I need to match frames across samples. This seems to be handled automatically by the way we get the stackFrames response **except** when the stack is truncated. When sample A and sample B have identical roots (lets say levels 1-5), we do not get multiple stack frames of level 1, 2, 3, 4, 5. We get one stack frame for each and at the point that stack frame 5 has two different children, the tree will separate there. 

Now imagine the scenario where sample A contains stack frames 1-5 but sample B was truncated and so it contains frames 3-5. We need a way to match stack frame 3 from sample B with stack frame 3 from sample A, but as it has a different root (the [Truncated] event), we don't know the level at which to match the stack frames.

**Comment by rmacnak-google** [comment] 2019-04-25 22:21
It is not possible to match frames across samples. Just because two adjacent samples have a common sequence of functions at their tops of stack does not mean the frames in those samples come from the same function invocations. Chrome's DevTools does this sort of merging, but it is speculative and may misrepresent the program's execution.

**Comment by kenzieschmoll** [comment] 2019-04-25 22:47
I see. Is it possible to increase the stack depth we track? Are there consequences to doing so?

**Comment by bkonyi** [comment] 2019-04-26 16:50
Although I'm sure we can increase the stack depth (can't remember specific implementation details) it will likely cause a performance hit proportional to the increased depth as walking the stack isn't a cheap operation. We can't ever predict how deep the stack will actually get and eventually we'll run into a stack that we'll have to truncate, so we'll always have to worry about this case.

**Comment by kenzieschmoll** [comment] 2019-04-26 23:11
Makes sense. Well in that case, lets just have this issue track adding the file path to the stackFrames.

**Comment by jacob314** [comment] 2019-04-30 19:30
> It is not possible to match frames across samples. Just because two adjacent samples have a common sequence of functions at their tops of stack does not mean the frames in those samples come from the same function invocations. Chrome's DevTools does this sort of merging, but it is speculative and may misrepresent the program's execution.

We can always give power users the option of turning off speculative merging.
I expect that like in the case of Chrome DevTools, performing the speculative merging will give a better user experience even though it will not always accurate. This is because not doing the merging is also inaccurate as far as non expert users are concerned as too few CPU samples are attributed to to frames near the top of the stack trace because of the truncation.

**Comment by jacob314** [comment] 2019-05-17 22:34
Let me try rephrasing this in terms of our problem rather than a proposed solution as we aren't trying to propose a solution just explain the problem we have that we need the VM team's help this.
The problem is we have stack traces that are very deep for Flutter applications. Typically 256+ frames even for relatively simple applications such as the Flutter Gallery application.
What we would like is a way to generate profiles that are understandable to users even with these deep stack traces.
What is not an option is simple truncating like we are doing now: The truncated time is confusing and distracting to even advanced users.
The deep stack traces in Flutter typically have many repeated blocks of the same 3 or 4 source locations repeated over and over again in the same order. A solution that dealt with these repetitive stack frames better would be very valuable as the users are not getting value out of seeing the repeated frames and the repeated frames are starving us from seeing more useful frames.

The chrome team worked around the issue by setting the stack trace depth to 256 but that does not appear sufficient for us based on tests with Flutter Gallery.

**Comment by bkonyi** [comment] 2019-05-20 17:43
After doing some testing locally, it appears that a max stack depth of 512 resolves the truncation issues for Flutter Gallery's Material -> Backdrop page. However, I'm concerned that we're reaching the limit of what the profiler can handle effectively given the current size of the sample buffer. 

For context, the profiler currently allocates a buffer of 60,000 samples upon initialization, each of which can store stacks up to 8 frames deep. For stacks deeper than 8 frames, the profiler chains samples from the buffer to allow for deep stacks. In its current configuration using the default sample rate of 1000Hz, the sample buffer has enough space for _up to_ 60s worth of unique samples. If stacks are generally deep, there is a much smaller number of unique samples that can be collected before the buffer fills and the oldest samples are overwritten.

Given the DevTools sample rate of 50us (which will be problematic on Fuchsia and Windows as those systems don't utilize signals and rely on some sort of polling mechanism for profiling), our sample buffer can hold _up to_ 3s worth of unique samples with _**stack depths of 8 or less**_. As we've seen, Flutter frequently has very deep stacks, so I wouldn't be surprised if sampling at this rate causes the buffer to fill in less than a second. Increasing the stack depth will only worsen this problem.

Assuming reducing the sample rate is off the table, the only option here is to increase the size of the sample buffer significantly which I'm not sure is something we want to do. Each sample is currently ~100 bytes and the existing buffer uses about 6MB of memory, so any increase in the sample buffer size will result in a noticeable increase in the memory footprint of the VM in debug and profile builds.

The profiler is meant to provide insights to where time is roughly being spent during execution, but it seems that we're trying to use it to provide an extremely fine profile. We might want to reconsider this approach and move towards something more accurate that doesn't rely on collecting samples at given intervals (e.g., instrumenting kernel to perform tracing).

**Comment by bkonyi** [comment] 2019-07-31 18:13
Closing as adding a stack depth is not something we'd be able to do with the existing profiler and file paths have been added to the stack frames in a prior CL.

**Closed by bkonyi** 2019-07-31 18:13 UTC
Labels: area-vm, vm-debugger
