### ISSUE TITLE
Invalid Isolate arguments throw uncatchable errors

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28041] opened 2016-12-08 22:20 UTC
When you try to send an illegal object across isolate boundaries, Dart currently top-levels an exception. I'd expect it to throw synchronously on the call to `SendPort.add()`. The current behavior makes it extremely difficult to tell where the illegal object is coming from or to gracefully handle the error.

For example:

```dart
import 'dart:async';
import 'dart:isolate';

main() {
  Isolate.spawnUri(new Uri.dataFromString(r"""
    import "dart:isolate";

    void main(_, SendPort port) {
      runZoned(() {
        try {
          port.send([].iterator);
        } catch (error) {
          print("caught sync $error");
        }
      }, onError: (error) {
        print("caught async $error");
      });
    }
  """), [], new ReceivePort());
}
```

See also #18593.

**Comment by floitschG** [comment] 2016-12-09 12:48
Why was this marked as S1?

I can't reproduce.
Once I fixed the code to not fail in the main isolate (by sending `new ReceivePort().sendPort`), and after I fixed the spawned isolate to also import `dart:async` (for the `runZoned`) I correctly get:

`caught sync Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)`.

Uncaught errors in non-main isolates are not printed in the VM: https://github.com/dart-lang/sdk/issues/26626

Note that the `onError` argument correctly prints the error.

``` dart
import 'dart:async';
import 'dart:isolate';

main() {
  var rp = new ReceivePort();
  rp.listen(print);
  Isolate.spawnUri(new Uri.dataFromString(r"""
    import "dart:isolate";
    import "dart:async";

    void main(_, SendPort port) {
      runZoned(() {
        try {
          port.send([].iterator);
        } catch (error) {
          print("caught sync $error");
        }
      }, onError: (error) {
        print("caught async $error");
      });
    }
  """), [], rp.sendPort, onError: rp.sendPort);
}
```

**Closed by floitschG** 2016-12-09 12:48 UTC
Labels: area-library, library-isolate, S1 high, Type: bug

**Comment by kevmoo** [comment] 2016-12-09 17:13
I marked it `S1` because I was told it would be difficult to impossible to debug/diagnose

**Comment by nex3** [comment] 2016-12-12 23:39
Sorry, my mistake!
