### ISSUE TITLE
Analyzer Feedback

### ISSUE THREAD

**Issue by SerdarDemirbas** [dart-lang/sdk#39974] opened 2020-01-03 07:06 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version , FATAL error: NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:848:9)
#2      Driver.start (package:analysis_server/src/server/driver.dart:463:28)
#3      main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\Serdar\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment] 2020-01-07 21:20
Thanks for reporting this issue! This was previously reported in #35226; please follow along there.

**Comment by srawlins** [comment] 2020-01-07 21:20
Duplicate of #35226

**Closed by srawlins** 2020-01-07 21:20 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
