### ISSUE TITLE
Invalid mixin application error when using constant constructors and required named parameters

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#53281] opened 2023-08-18 21:26 UTC
Consider the following:
```dart
class A {
  final String value;
  final String value2;
  const A(
    this.value, {
    required this.value2,
  });
}

mixin B on A {}

class C = A with B;

void main(List<String> args) {
  print(const C("abc", value2: "abc").value2);
}
```

The analyzer reports an error at: `const C`, but `dart run` works as expected.

Further more, the error: `error • _.dart:15:3 • Evaluation of this constant expression throws an exception. • const_eval_throws_exception` is only reported when using a required named parameter.

Removing `required this.value2` or rewriting the constructor as:
```dart
const A(
    this.value, {
    this.value2 = "",
  });
```
reports no errors.

**dart --version**
`Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_x64"`

**Comment by lrhn** [comment] 2023-08-18 21:34
May already have been fixed. I don't see the error in DartPad when changing to master channel.

**Comment by pq** [comment] 2023-08-23 21:58
Thanks for the report!  I'm not able to reproduce this at the tip of tree so I'll go ahead and close it (thinking @lrhn is correct).

**Closed by pq** 2023-08-23 21:58 UTC
Labels: area-analyzer, type-bug
