### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Alias111** [dart-lang/sdk#36507] opened 2019-04-06 22:36 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.6183.63`
- `2.2.0`
- `WS-191.6183.63, JRE 1.8.0_202-release-1483-b39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.2.0, server version 1.23.0, error: Captured exception
RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:387:7)
#1      unescapeLastStringPart (package:front_end/src/fasta/quote.dart:132:24)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:257:17)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4797:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4722:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3997:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:4912:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4884:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4865:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4844:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4580:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:3991:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:3930:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3742:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3714:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3679:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5191:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3513:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3503:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3408:15)
#23     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2338:13)
#24     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2241:14)
#25     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:489:14)
#26     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#27     ParserAdapter.parseCompilationUnit2 (file:///b/s/w/ir/cache/builder/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:189:32)
#28     ParserAdapter.parseCompilationUnit (file:///b/s/w/ir/cache/builder/sdk/pkg/analyzer/lib/src/generated/parser_fasta.dart:184:12)
#29     _File._parse (package:analyzer/src/services/available_declarations.dart:1368:23)
#30     _File.refresh (package:analyzer/src/services/available_declarations.dart:998:30)
#31     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:618:12)
#32     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:483:7)
#33     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:171:13)
<asynchronous suspension>
#34     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#35     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#36     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#37     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#38     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#39     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#45     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#46     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#47     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#48     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#49     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#50     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/lc/g3dvys114dzc21c530drx4nc0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-04-08 16:30
Duplicate of #36497.

**Closed** 2019-08-29 05:32 UTC
Labels: area-analyzer
