### ISSUE TITLE
Dart Crash on Android Studio

### ISSUE THREAD

**Issue by blackmenthor** [dart-lang/sdk#36185] opened 2019-03-13 09:19 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1366x768, 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b, server version 1.21.1, error: Analysis failed: /Users/anggadwiarifandi/Documents/dev/KG/myvalue/kgvalue-mobile/lib/campaign/repo/models.dart context: exception_20190313_161915_477
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1461:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#4      ClassElementImpl.interfaces (package:analyzer/src/dart/element/element.dart:697:28)
#5      ClassElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:1005:9)
#6      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:3164:5)
#7      _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:836:19)
#8      new _ElementMismatchException (package:analyzer/src/generated/declaration_resolver.dart:971:65)
#9      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52:17)
#10     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:597:31)
#11     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#13     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#14     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#16     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#17     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#18     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#19     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#20     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#21     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#22     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#23     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#24     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#25     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#26     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#32     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#33     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#34     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#35     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#36     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/l6/w6xjmy255mbdjvkpznnlqbw40000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-06 16:06
Thanks for reporting this issue! This was previously reported at #35551; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 16:06
Duplicate of #35551

**Closed by srawlins** 2019-09-06 16:06 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
