### ISSUE TITLE
NPE in Driver._readUuid

### ISSUE THREAD

**Issue by hdhhdhd** [dart-lang/sdk#34433] opened 2018-09-11 05:54 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Windows\System32\config\systemprofile\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version , FATAL error: NoSuchMethodError: The method 'getChild' was called on null.
Receiver: null
Tried calling: getChild("uuid.txt")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Driver._readUuid (package:analysis_server/src/server/driver.dart:579)
#2      Driver.start (package:analysis_server/src/server/driver.dart:403)
#3      main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)

**Comment by hdhhdhd** [comment] 2018-09-11 05:56
from Android Studio

**Comment by srawlins** [comment] 2019-09-10 16:50
Thanks for reporting this issue. This should be fixed as part of https://github.com/dart-lang/sdk/issues/34616.

**Comment by srawlins** [comment] 2019-09-10 16:50
Duplicate of https://github.com/dart-lang/sdk/issues/34616

**Closed by srawlins** 2019-09-10 16:50 UTC
Labels: analyzer-crash-report, analyzer-server, area-analyzer, type-bug
