### ISSUE TITLE
Destructuring nested records with named fields

### ISSUE THREAD

**Issue by Mike278** [dart-lang/sdk#53329] opened 2023-08-24 03:50 UTC
These examples are from dartpad.dev using Dart 3.1.0.

This fails to parse:
```dart
final (id, (:firstName, :lastName)) =
    (1, (firstName: 'Bob', lastName: 'Vance'));
```

even though this works:
```dart
final (id, (firstName, lastName)) =
    (1, ('Bob', 'Vance'));
```

and this works:
```dart
final (id, (firstName: firstName, lastName: lastName)) =
    (1, (firstName: 'Bob', lastName: 'Vance'));
```

Is this expected?

**Comment by lrhn** [comment] 2023-08-24 10:06
I don't think it's expected.
If you change it to:
```dart
  final (id, (x, :firstName, :lastName)) =
    (1, (1, firstName: 'Bob', lastName: 'Vance'));
```
it also works, and a stand-alone
```dart
final (:firstName, :lastName) = (firstName: 'Bob', lastName: 'Vance');
```
also works. Even making the second pattern named:
```dart
final (id, sub:(:firstName, :lastName)) =
    (1, sub:(firstName: 'Bob', lastName: 'Vance'));
```
works.

It seems the parser fails to recognize the `(:firstName` as starting a record pattern at a positional position of another record pattern.

The error message:
````
The matched value of type '(int, ({String firstName, String lastName}))' isn't assignable to the required type '(Object?, {Object? , Object? lastName})'.[ (view docs)](https://dart.dev/diagnostics/pattern_type_mismatch_in_irrefutable_context)
```
suggests that it somehow embeds the `(:firstName, :lastName)` pattern into the original pattern, as named fields of that, except that it throws away the `firstName` identifier too.

So, bug.

**Comment by johnniwinther** [comment] 2023-08-25 11:21
cc @stereotype441

**Comment by stereotype441** [comment] 2023-08-25 14:48
This is a duplicate of https://github.com/dart-lang/sdk/issues/52954, which was addressed in a445fae68158275f5cda46e9b26e065200bc9dc2. I will open a cherry-pick request to see if we can get the fix into the stable release.

**Comment by stereotype441** [comment] 2023-08-25 17:49
Cherry-pick request is here: https://github.com/dart-lang/sdk/issues/53352. I'm going to close out this issue, and track the remaining work in the cherry-pick request.

**Comment by stereotype441** [comment] 2023-08-25 17:49
Duplicate of #52954

**Closed by stereotype441** 2023-08-25 17:49 UTC
Labels: type-bug, front-end-fasta, area-front-end
