### ISSUE TITLE
Tests of non-utf8 filenames break infrastructure if they don't clean up their temp files

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#33519] opened 2018-06-20 11:59 UTC
The tests 

standalone_2/io/non_utf8_directory_test
standalone_2/io/non_utf8_file_test
standalone_2/io/non_utf8_link_test
standalone_2/io/non_utf8_output_test (possibly)

will leave behind a temporary file system object with a non-utf8 name (starting with 0xb6, decimal 182)
if they time out or crash.
The swarming infrastructure used for builders then crashes when trying to delete these files, as part of cleaning up after a build.
This is happening on the hot_reload and hot_reload_rollback builders right now.

Skipping these tests on the reload and reload rollback builders for now, filing an issue with Chrome infrastructure to make the swarming bots stop crashing on this case.

These are tests related to issue "Cannot walk a list of files and pass them to a subprocess (if any are non-UTF8) #33368"

**Comment by whesse** [comment] 2018-06-20 12:09
These tests should also be improved to make a temp directory with the name of the test in it, like
systemTemp.createTemp("non_utf8_directory_test"), and do all further work inside this directory.  Deleting this directory should be in a "finally" block, so that we are almost certain to delete it.

**Comment by athomas** [comment] 2018-06-25 07:44
The issue is not solved, the builders are purple again since efd36d4cdf5f72668837fb07bc6e0a24c2d61872 landed: https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-reload-linux-debug-x64

**Comment by bkonyi** [comment] 2019-04-29 22:08
@whesse do you happen to know if the Chrome infrastructure got around to fixing this case? Looking at the tests again, I'm not sure why those files weren't being deleted in the first place...

**Comment by whesse** [comment] 2019-04-30 15:55
No the problem is still there. I don't think they intend to fix it - I think they closed the issue as working as intended.  I ran the tests again, modified to leave the file behind, and got a purple build, with the following error: 

INFO: Core dump archiving is activated
INFO: No unexpected crashes recorded
2169 2019-04-30 14:44:15.430 E: Leaking out_dir /b/s/w/iojk689o: 'utf8' codec can't decode byte 0xb6 in position 1: invalid start byte
Traceback (most recent call last):
  File "/b/s/swarming_bot.1.zip/client/run_isolated.py", line 786, in map_and_run
    success = file_path.rmtree(run_dir)
  File "/b/s/swarming_bot.1.zip/utils/file_path.py", line 1178, in rmtree
    make_tree_deleteable(root)
  File "/b/s/swarming_bot.1.zip/utils/file_path.py", line 1152, in make_tree_deleteable
    p = os.path.join(dirpath, dirname)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 1: invalid start byte
 
Error is at https://ci.chromium.org/p/dart/builders/try/vm-kernel-reload-linux-release-x64-try/309

**Comment by bkonyi** [comment] 2019-04-30 19:58
Thanks for checking Bill. Do you think it's worth enabling these tests
as-is given the risk of them taking down the infrastructure? It looks like
there's an issue deep in the posixpath join implementation expecting UTF8
strings, so I doubt there's anything we can do directly. If it's not worth
enabling them, we should probably just close this issue.

**Comment by bkonyi** [comment] 2019-05-03 20:13
Closing for now as there's no clear path to fix this and we likely won't ever be able to.

**Closed by bkonyi** 2019-05-03 20:13 UTC
Labels: area-test, library-io
