### ISSUE TITLE
NoSuchMethodError from package:build_runner_core/src/package_graph/package_graph.dart 74:15   PackageGraph.forPath

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#41913] opened 2020-05-06 21:47 UTC
We're seeing this failure on the DevTools bots:

NoSuchMethodError from package:build_runner_core/src/package_graph/package_graph.dart 74:15   PackageGraph.forPath

With the possible root cause being in `package:package_config`?

https://travis-ci.org/github/flutter/devtools/jobs/684021378#L591

```
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
dart:core                                                              _SyncIterable.iterator
package:package_config/src/package_config_impl.dart 26:36              new SimplePackageConfig
package:package_config/src/package_config_json.dart 213:10             parsePackageConfigJson
package:package_config/src/package_config_json.dart 45:10              parsePackageConfigBytes
package:package_config/src/package_config_io.dart 117:10               readPackageConfigJsonFile
package:package_config/src/discovery.dart 109:18                       findPackagConfigInDirectory
package:package_config/src/discovery.dart 44:31                        findPackageConfig
package:package_config/package_config.dart 114:5                       findPackageConfig
package:build_runner_core/src/package_graph/package_graph.dart 74:15   PackageGraph.forPath
package:build_runner_core/src/package_graph/package_graph.dart 110:20  PackageGraph.forThisPackage
package:build_runner/src/entrypoint/run.dart 22:64                     run
.dart_tool/build/entrypoint/build.dart 96:22                           main
```

**Comment by devoncarew** [comment] 2020-05-15 14:38
Moved to dart-lang/sdk. If we continue to see this we should investigate.

It sounds like we may need to:
- ensure that kernel version needs to be rev'd when there are breaking changes?
- embedding SDK version strings into Kernel files to prevent version skew from happening?
- ensure we throw an `IsolateSpawnException` when trying to run a kernel file with an out-of-date snapshot?

**Comment by devoncarew** [comment] 2020-05-15 18:29
We see this on the stagehand CI as well: https://travis-ci.org/github/dart-lang/stagehand/jobs/687544226

**Comment by srawlins** [comment] 2020-05-19 16:33
@johnniwinther suggested this may be a VM issue, w.r.t. the version skew of package_config.

**Comment by a-siva** [comment] 2020-05-19 17:01
@devoncarew do you have reproduction instructions for the above? the link you have doesn't seem to show any errors.

**Comment by devoncarew** [comment] 2020-05-19 18:04
No repro instructions, but we have seen this on three separate CIs now. The link in the 1st comment does still show the issue.

**Comment by a-siva** [comment] 2020-05-19 18:19
The first link shows the  "Closure call with mismatched arguments" error which @cskau-g says was expected because of mismatched kernel files being used.
The final comment from @srawlins indicates this is a VM issue in response to your comment about stagehand CI, I am trying to understand what is the VM issue and how to reproduce it.

**Comment by mkustermann** [comment] 2020-05-20 09:07
@jakemac53 @natebosch Does `package:build_runner_core` or any other package involved in running tests cache kernel / .dill files?
@sigurdm @jonasfj Does pub cache kernel / .dill files?

> We see this on the stagehand CI as well: https://travis-ci.org/github/dart-lang/stagehand/jobs/687544226

That link points to a green build. 

> It sounds like we may need to:
> ensure that kernel version needs to be rev'd when there are breaking changes?
> embedding SDK version strings into Kernel files to prevent version skew from happening?
> ensure we throw an IsolateSpawnException when trying to run a kernel file with an out-of-date 
> snapshot?.

See https://github.com/dart-lang/sdk/issues/41802 . @cskau-g is drafting a design for this atm.

We maintain currently no compatibility between SDK versions. The kernel binary version is just a version for the AST encoding. Though the VM does requires stronger guarantees than to just be able to parse the files, it also expects e.g. certain transformers to be run, etc.

**Comment by jonasfj** [comment] 2020-05-20 10:08
`pub run ...` creates _source snapshots_, but we don't track which SDK version created. We just rebuild the snapshot if using it fails.

**Comment by jakemac53** [comment] 2020-05-20 13:50
> `pub run ...` creates _source snapshots_, but we don't track which SDK version created. We just rebuild the snapshot if using it fails.

This is exactly what build_runner does as well. We rely on the IsolateSpawnException.

**Comment by mkustermann** [comment] 2020-05-20 13:57
> This is exactly what build_runner does as well. We rely on the IsolateSpawnException.

That is unsafe atm. If we do lock-step changes to VM and kernel transformers they have to match. This is not validated at runtime until https://github.com/dart-lang/sdk/issues/41802 is addressed.

(/cc @mraleph Proofs the point we should really embed the SDK hash in the kernel files.)

**Comment by jakemac53** [comment] 2020-05-20 14:04
If running a snapshot from a different sdk version has potentially undefined semantics then I would argue that it should detect this itself and throw before attempting to run? This has been the behavior for many years, and existing tools do rely on it.

**Comment by a-siva** [comment] 2020-05-20 16:41
The title of the bug does not match the issue being reported, looks like this issue is a duplicate of
https://github.com/dart-lang/sdk/issues/38969 and
https://github.com/dart-lang/sdk/issues/41802
Marking as such.

**Closed by a-siva** 2020-05-20 16:41 UTC
Labels: area-vm, closed-duplicate

**Comment by devoncarew** [comment] 2020-05-20 17:09
I think we should bump the priorities of those other issues, given that we've seen more problems related to this recently. Sounds like those two issues are the best way to make progress here; I'll bump them to P1s.
