### ISSUE TITLE
HttpRequest.requestedUri throws FormatException if request URI is absolute

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#26188] opened 2016-04-04 22:04 UTC
To reproduce:
1. Create an HttpServer.
2. Send it a request whose URI is absolute (i.e. `http://example.com/path.html`, not `/path.html`).
3. In the request handler, call `requestedUri` on the HttpRequest.

On http_impl.dart:145:

``` dart
_requestedUri = Uri.parse("$scheme://$host$uri");
```

This assumes `uri` is just a path, not a full absolute URI. That's generally true, but I can point you to at least one real-world example (a proxying server) where requests come in with absolute URIs. The fix is probably just:

```
_requestedUri = Uri.parse("$scheme://$host${uri.path}");
```

**Comment by brianquinlan** [comment] 2023-01-10 21:41
This is a duplicate of https://github.com/dart-lang/sdk/issues/50704, which was fixed.

**Closed by brianquinlan** 2023-01-10 21:41 UTC
Labels: area-library, library-io
