### ISSUE TITLE
exception out of `dart analyze -v`

### ISSUE THREAD

**Issue by jwren** [dart-lang/sdk#43240] opened 2020-08-28 17:03 UTC
```
Analyzing dartdev...                   1.9s

   info • Prefer relative imports for files in `lib/` at lib/dartdev.dart:13:8 • (prefer_relative_imports)
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<DiagnosticMessage>(Closure: (dynamic) => DiagnosticMessage)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AnalysisError.contextMessages (package:dartdev/src/commands/analyze_impl.dart:242:21)
#2      AnalyzeCommand.run (package:dartdev/src/commands/analyze.dart:108:37)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      DartdevRunner.runCommand (package:dartdev/dartdev.dart:287:24)
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#6      new Future.sync (dart:async/future.dart:223:31)
#7      CommandRunner.run (package:args/command_runner.dart:112:14)
#8      runDartdev (package:dartdev/dartdev.dart:132:27)
#9      main (file:///Users/jwren/src/github/dart-sdk/sdk/pkg/dartdev/bin/dartdev.dart:12:9)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by bwilkerson** [comment] 2020-08-28 17:08
Duplicate of https://github.com/dart-lang/sdk/issues/43239

**Closed by bwilkerson** 2020-08-28 17:08 UTC
Labels: P1, area-dart-cli
