### ISSUE TITLE
yield* ignores exception handlers in sync* functions 

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#42466] opened 2020-06-24 13:41 UTC
Dart VM version: 2.9.0-18.0.dev (dev) (Mon Jun 22 16:07:30 2020 +0200) on "windows_x64"

It looks like a regression of the Issue #26262, please take a look at the issues #25662, #25634, #26262 for more details.

Dart Lang Specification reads:

> Execution of a statement s of the form yield* e; proceeds as follows:
> First, the expression e is evaluated to an object o.
> If the immediately enclosing function m is marked sync* (9), then:
> 1. It is a dynamic type error if the class of o does not implement Iterable. Otherwise
> 2. The method iterator is invoked upon o returning an object i.
> 3. The moveNext method of i is invoked on it with no arguments. If moveNext returns false execution of s is complete. Otherwise
> 4. The getter current is invoked on i. If the invocation throws (16.1), execution of s throws the same exception object and stack trace (17.0.1).
> Otherwise, the result x of the getter invocation is added to the iterable associated with m. Execution of the function m immediately enclosing s is
> suspended until the nullary method moveNext() is invoked upon the iterator used to initiate the current invocation of m, at which point execution of s continues at 3.
> 5. The current call to moveNext() returns true.

Here is a #26262 source code example:
``` dart
import 'dart:collection';

class AlwaysThrowingIterator implements Iterator {
  bool moveNext() => throw 'moveNext';
  get current => throw 'current';
}

class AlwaysThrowing extends IterableBase {
  Iterator get iterator => new AlwaysThrowingIterator();
}

f() sync* {
  try {
    yield* new AlwaysThrowing();
  } catch (e) {
    print('caught $e in f');
  }
}

main() {
  try {
    for (var x in f()) {
      print(x);
    }
  } catch (e) {
    print('caught $e in main');
  }
}
```
According to the Spec, it should print `caught moveNext in f` but prints `caught moveNext in main` instead.

**Comment by mkustermann** [comment] 2020-06-25 03:02
This might be due to a recently introduced optimization for optimizing `yield*` to avoid non-linear behavior in nested `yield*` situations, see 674af7e93f56bbd88b59444022f0b35c2a29258d

@lrhn Can you comment on what the expected behavior is?

/cc @mraleph @cskau-g

**Comment by lrhn** [comment] 2020-06-25 07:44
If the call to either `iterator` on the iterable object, or `moveNext` or `current` on the iterator throws, then the `yield*` throws the same exception and stack trace.

The spec is fairly clear (it explicitly says so for the `current`, but the general rule is that if any part of the semantics of a construct throws, then so does that construct itself unless otherwise stated).

**Comment by cskau-g** [comment] 2020-08-25 12:47
I've submitted a fix for the exception handling case above, but as per Slava's comments on the change, there is some follow-up work to fix this regression for stack traces.
That is, for cases of nested `sync*` functions we currently do not correctly unwind the in-between frames.

**Comment by lzhuor** [comment] 2020-09-09 09:00
Encountering it too.

**Comment by cskau-g** [comment] 2020-10-29 11:25
Alright, the change to fix exception handling has landed and stuck.
There's some tangential work that is still TODO, but the main issue is fixed, so we'll track the rest separately.
Marking fixed.

**Closed by cskau-g** 2020-10-29 11:25 UTC
Labels: area-vm
