### ISSUE TITLE
Red squiggly line appearing under wrong thing and freezing

### ISSUE THREAD

**Issue by shabikar** [dart-lang/sdk#34858] opened 2018-10-19 00:49 UTC
Sometimes when I put a custom data type inside the angular brackets of Future, like (Future<CustomDataType>), without first importing it, the red squiggly line appears under Future instead of the custom data type and the IDE freezes.

I am on Ubuntu 16.04

Analyzer Feedback from IntelliJ

**Comment by alexander-doroshko** [comment] 2019-01-24 08:47
@shabikar, IntelliJ-specific issues (like freezes) are tracked in JetBrains issue tracker: https://youtrack.jetbrains.com/issues/WEB (Subsystem: Dart). Is the problem is still actual, please file an issue there and attach the whole folder with logs and thread dumps zipped (Help | Compress Logs...)

**Comment by srawlins** [comment] 2019-09-10 16:29
Closing with @alexander-doroshko 's comment.

**Closed by srawlins** 2019-09-10 16:29 UTC
Labels: analyzer-crash-report, area-intellij, type-bug
