### ISSUE TITLE
Analysis failed:  The getter 'element' was called on null

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#31386] opened 2017-11-16 02:42 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA WS-172.4343.25`
- `1.24.2`
- `WS-172.4343.25, JRE 1.8.0_152-release-915-b12x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1920x1200, 1920x1200`

# Exception

Please append the contents of:
file:///private/var/folders/p_/8567k9tn6cg7_f1bhzhhvh8c0028jd/T/report.txt

```
Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: /Users/filiph/dev/edgehead/lib/ecs/pubsub.dart context: exception_20171115_184038_455
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9902)
#3      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
#4      DeclaredIdentifierImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3372)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#7      UnifyingAstVisitor.visitDeclaredIdentifier (package:analyzer/dart/ast/visitor.dart:2971)
#8      ScopedVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:7411)
#9      TypeResolverVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:9816)
#10     DeclaredIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:3367)
#11     ScopedVisitor.visitForEachStatementInScope (package:analyzer/src/generated/resolver.dart:7490)
#12     ScopedVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:7468)


Contents of report.txt

Dart analysis server, SDK version 1.24.2, server version 1.18.0, error: Analysis failed: /Users/filiph/dev/edgehead/lib/ecs/pubsub.dart context: exception_20171115_184038_455
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9902)
#3      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
#4      DeclaredIdentifierImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3372)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#7      UnifyingAstVisitor.visitDeclaredIdentifier (package:analyzer/dart/ast/visitor.dart:2971)
#8      ScopedVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:7411)
#9      TypeResolverVisitor.visitDeclaredIdentifier (package:analyzer/src/generated/resolver.dart:9816)
#10     DeclaredIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:3367)
#11     ScopedVisitor.visitForEachStatementInScope (package:analyzer/src/generated/resolver.dart:7490)
#12     ScopedVisitor.visitForEachStatement (package:analyzer/src/generated/resolver.dart:7468)
#13     ForEachStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4706)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#15     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#16     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#17     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#18     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#19     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7258)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#21     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#22     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#23     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#24     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#25     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7270)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7544)
#28     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#29     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#30     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3106)
#31     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:7728)
#32     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:7720)
#33     TypeResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:9911)
#34     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7535)
#35     TypeResolverVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:9764)
#36     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7317)
#37     TypeResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:9710)
#38     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#39     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#40     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#41     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#42     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#43     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#44     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#45     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:536)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#47     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#49     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#50     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#51     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#52     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:834)
<asynchronous suspension>
#53     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#54     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#55     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#56     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#57     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#58     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#59     _rootRun (dart:async/zone.dart:1120)
#60     _CustomZone.run (dart:async/zone.dart:1001)
#61     runZoned (dart:async/zone.dart:1467)
#62     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#63     Driver.start (package:analysis_server/src/server/driver.dart:473)
#64     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#65     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1510800036042 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","errors":[]}}
1510800036042 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","regions":[]}}
1510800036043 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","regions":[],"targets":[],"files":[]}}
1510800036043 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","overrides":[]}}
1510800036043 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1510800036134 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1510800036137 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","errors":[]}}
1510800036137 <= {"event":"analysis.highlights","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","regions":[]}}
1510800036137 <= {"event":"analysis.navigation","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","regions":[],"targets":[],"files":[]}}
1510800036138 <= {"event":"analysis.overrides","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","overrides":[]}}
1510800036138 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1510800036286 => {"id":"26","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","offset":0,"length":0},"clientRequestTime":1510800036286}
1510800036286 => {"id":"24","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","offset":0,"length":0},"clientRequestTime":1510800036286}
1510800036286 => {"id":"25","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","offset":0,"length":0},"clientRequestTime":1510800036286}
1510800036289 <= {"id":"26","result":{"assists":[]}}
1510800036289 <= {"id":"24","result":{"assists":[]}}
1510800036289 <= {"id":"25","result":{"assists":[]}}
1510800036791 => {"id":"27","method":"analysis.updateContent","params":{"files":{"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart":{"type":"add","content":"class Pubsub<C, T> {\n  Map<C, List<void Func
1510800036791 => {"id":"28","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","offset":1374,"length":0},"clientRequestTime":1510800036791}
1510800036791 => {"id":"29","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","offset":1374,"length":0},"clientRequestTime":1510800036791}
1510800036791 => {"id":"30","method":"edit.getAssists","params":{"file":"/Users/filiph/dev/edgehead/lib/ecs/pubsub.dart","offset":1374,"length":0},"clientRequestTime":1510800036791}
1510800036809 <= {"id":"27","result":{}}
1510800036809 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1510800036916 <= {"id":"28","result":{"assists":[]}}
1510800036916 <= {"id":"29","result":{"assists":[]}}
1510800036916 <= {"id":"30","result":{"assists":[]}}
1510800036918 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/edgehead/lib/fractal_stories/world.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/filiph/de
1510800036924 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1510800038436 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1510800038534 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/filiph/dev/edgehead/lib/ecs/pubsub.dart context: exception_20171115_184038_455","stackTrace":"NoSu
```

**Comment by MichaelRFairhurst** [comment] 2017-11-16 16:55
Hey @filiph can you include the code you were working on?

This seems to be a duplicate of -- or something really similar to -- https://github.com/dart-lang/sdk/issues/31107.

I may also ask you to try it again with a newer SDK, if you could!

**Comment by filiph** [comment] 2017-11-16 17:52
Sorry, I don't think I have it anymore. But I do know what the issue with the code was.

I tried to use the new `typedef` function syntax inline, such as:

```
class A<T, S> {
  Map<T, void Function<S>> map;

  foo(T a, void Function<S> b) {
    // ...
  }
}
```

**Comment by devoncarew** [comment] 2017-11-16 19:50
(DBC - the SDK version - `1.24.2` - is pretty old at this point)

**Comment by MichaelRFairhurst** [comment] 2017-11-30 17:30
Will close. This seems to be a resolved issue in newer SDKs.

If you hit it again please file again; without having the code to repro there's a chance this is not actually the same as previously fixed issues (the stack trace isn't actually the source of the problem in this case but a symptom).

**Closed by MichaelRFairhurst** 2017-11-30 17:30 UTC
Labels: area-analyzer, area-intellij
