### ISSUE TITLE
static final String EVENT_NAME = "ConnectionEvent".toLowerCase(); produces Uncaught in js_helper

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25714] opened 2016-02-08 07:39 UTC
The following class produces an uncaught JS exception but if I remove the "toLowerCase" it works! (`static final String EVENT_NAME = "connectionevent";`)

Dart VM version: 1.14.1 (Wed Feb  3 11:49:51 2016) on "macos_x64"

```dart
class ConnectionEvent extends JsonDataEvent<ConnectionEventData> {
    static final String EVENT_NAME = "ConnectionEvent".toLowerCase();

    factory ConnectionEvent(final ConnectionType connectiontype) {
        Validate.notNull(connectiontype);
        return new ConnectionEvent._internal(new ConnectionEventData(connectiontype));
    }

    ...
    ConnectionEvent._internal(final ConnectionEventData data) : super(EVENT_NAME, data);
}
```

produces:
```

dart.wrapException	@	js_helper.dart:1699
dart._rootHandleUncaughtError_closure.call$0	@	async_patch.dart:522
dart._microtaskLoop	@	schedule_microtask.dart:41
dart._startMicrotaskLoop	@	schedule_microtask.dart:50
dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1	@	async_patch.dart:54
dart.invokeClosure_closure0.call$0	@	js_helper.dart:2375
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart._callInIsolate	@	isolate_helper.dart:54
dart.invokeClosure	@	js_helper.dart:2375
(anonymous function)	@	js_helper.dart:2395
Mutation (async)		
dart._AsyncRun__initializeScheduleImmediate_closure.call$1	@	async_patch.dart:69
dart._scheduleAsyncCallback	@	async_patch.dart:31
dart._rootScheduleMicrotask	@	zone.dart:961
dart._RootZone.scheduleMicrotask$1	@	zone.dart:1167
dart._Future._addListener$1	@	future_impl.dart:292
dart._Future._thenNoZoneRegistration$2	@	future_impl.dart:206
dart._awaitOnObject	@	async_patch.dart:192
dart._asyncHelper	@	async_patch.dart:160
dart.main	@	date_format.dart:228
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart.startRootIsolate	@	isolate_helper.dart:120
(anonymous function)	@	ConnectionEvent.dart:12
(anonymous function)	@	ConnectionEvent.dart:12
init.currentScript	@	ConnectionEvent.dart:12
(anonymous function)	@	ConnectionEvent.dart:12
(anonymous function)	@	ConnectionEvent.dart:12
﻿
```

**Comment by floitschG** [comment] 2016-02-08 15:25
I was unable to reproduce.
Unless you think that issue #25715 is the same error, please provide code that we can reproduce.
thanks.

**Comment by floitschG** [comment] 2016-02-08 15:33
I expect this to have the same root-cause as #25715, so closing for now. Feel free to reopen.

**Closed by floitschG** 2016-02-08 15:33 UTC
Labels: area-dart2js
