### ISSUE TITLE
RangeError in ExtractLocalRefactoringImpl.isAvailable

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#33471] opened 2018-06-15 22:50 UTC
Just opened VS Code to test something and hit this. It was after I selected an entire file and then shift-tab (unindented) it; though I don't know if that's relevant.

### Versions

- Flutter SDK 0.5.5-pre.40
- Visual Studio Code 1.24.1
- Dart Code 2.14.0-beta.2

### Analyzer Info

The analyzer was launched using the arguments:

```text
M:\Coding\Applications\Google\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.14.0-beta.2
```

### Exception (fatal)

Failed to handle request: {id: 34, method: edit.getAvailableRefactorings, params: {file: M:\Coding\Applications\Google\flutter\packages\flutter_tools\lib\src\android\android_emulator.dart, length: 4065, offset: 0}}

```text
RangeError: Value not in range: 4065
#0      _StringBase.substring (dart:core-patch/dart:core/string_patch.dart:369)
#1      CorrectionUtils.getText (package:analysis_server/src/services/correction/util.dart:949)
#2      CorrectionUtils.getRangeText (package:analysis_server/src/services/correction/util.dart:942)
#3      ExtractLocalRefactoringImpl._checkSelection (package:analysis_server/src/services/refactoring/extract_local.dart:230)
#4      ExtractLocalRefactoringImpl.isAvailable (package:analysis_server/src/services/refactoring/extract_local.dart:216)
#5      EditDomainHandler._getAvailableRefactoringsImpl (package:analysis_server/src/edit/edit_domain.dart:578)
<asynchronous suspension>
#6      EditDomainHandler._getAvailableRefactorings (package:analysis_server/src/edit/edit_domain.dart:560)
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:337)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:739)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:735)
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     _runZoned (dart:async/zone.dart:1518)
#14     runZoned (dart:async/zone.dart:1502)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:734)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#20     _rootRunUnary (dart:async/zone.dart:1134)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#32     _rootRunUnary (dart:async/zone.dart:1134)
#33     _CustomZone.runUnary (dart:async/zone.dart:1031)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#45     _rootRunUnary (dart:async/zone.dart:1134)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#50     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#51     _StreamController._add (dart:async/stream_controller.dart:639)
#52     _StreamController.add (dart:async/stream_controller.dart:585)
#53     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#54     _rootRunUnary (dart:async/zone.dart:1138)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)
#59     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#60     _StreamController._add (dart:async/stream_controller.dart:639)
#61     _StreamController.add (dart:async/stream_controller.dart:585)
#62     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#63     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#64     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#65     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#66     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\syntax_error",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_path",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_test\\test\\test_config\\project_root",
        "explicitFileCount": 1,
        "implicitFileCount": -1,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\main",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\asset_test\\font",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\changed_sdk_location",
        "explicitFileCount": 1,
        "implicitFileCount": -1,
        "workItemQueueLength": 1,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\good",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_package",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_test",
        "explicitFileCount": 31,
        "implicitFileCount": -31,
        "workItemQueueLength": 31,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\asci_casing",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools\\test\\data\\dart_dependencies_test\\bad_import",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "M:\\Coding\\Applications\\Google\\flutter\\packages\\flutter_tools",
        "explicitFileCount": 207,
        "implicitFileCount": 407,
        "workItemQueueLength": 206,
        "cacheEntryExceptions": []
    }
]
```

(cc @bwilkerson @scheglov)

**Comment by scheglov** [comment] 2018-06-18 17:37
https://dart-review.googlesource.com/c/sdk/+/60701

**Comment by DanTup** [comment] 2018-06-19 09:02
I didn't have a reliable repro for this; if you know what might have triggered it and want me to test (otherwise, feel free to close if you expect it's resolved).

**Comment by scheglov** [comment] 2018-06-19 18:53
I don't know how to reproduce this reliably.

This is a race condition problem - use resolved unit for one version of code, and read another version of code from the file. This landed CL so far fixed the problem in Analysis Server, but currently there is no way for the client to know that the returned source changes are not compatible with the current file states, because one or more files were changed.

**Comment by DanTup** [comment] 2018-06-19 20:36
In VS Code we have a "document version" which I use in some places for this. Eg. I capture the document version client-side as I sent the request to the server, and then at the time the change would be applied (it may be much later if we show a non-modal dialog showing the user a warning and letting them "Refactor anyway") we check it hasn't changed first. I don't know if it's bullet-proof, but it has some automated tests around it, so I'm reasonably sure this is covered.

**Comment by DanTup** [comment] 2018-06-20 18:17
Right now, I seem to have a reliable repro for this by just running my tests on dev-62 for my `complete statement` tests.

[complete_statement_completes_an_if_statement.txt](https://github.com/dart-lang/sdk/files/2120544/complete_statement_completes_an_if_statement.txt)

I've put the code on a branch so I can easily re-test the same thing with the fix later.

https://github.com/Dart-Code/Dart-Code/tree/server-crash-repro

**Comment by scheglov** [comment] 2018-06-25 21:57
Thank you for the repro.

Judging by line numbers, it seems to be an older version.
Could you please check with this change?
https://github.com/dart-lang/sdk/commit/7d947558360ebfa3e39a4242ae98c7a6086750a3

It might be better to avoid waiting, and just fix potential inconsistencies in Analysis Server.
The change above should do this, at least for the server side.

**Comment by DanTup** [comment] 2018-06-26 06:38
I can't repro this one in `v2.0.0-dev.64.1` however I did hit #33623. I don't know if it's related or not so I opened as a new issue.

> It might be better to avoid waiting, and just fix potential inconsistencies in Analysis Server.

Yeah, that's kinda my preference. Although it might mean flaky tests until we discover all the cases like this, it does mean the server will end up much more bullet-proof :-)

**Comment by DanTup** [comment] 2018-06-27 06:42
Ugh, that issue I opened is just the same error as this - not sure why I thought it was different. Strangely some of the stack trace is different though, like `dart:core-patch/dart:core/string_patch.dart:369` has become `dart:core/runtime/libstring_patch.dart:366:7` - not sure why that is!

**Comment by DanTup** [comment] 2018-06-27 06:43
(I've closed the other issue, so we can keep this one open to figure out why the fix didn't work)

**Comment by scheglov** [comment] 2019-01-03 19:32
I believe race conditions like this, where we worked with AST and then attempted to read the file content from the file, and the file might have been changed, are fixed in a series of CLs, like https://github.com/dart-lang/sdk/commit/142641e596865bd3702431cb25687e14c5cfc3f2 or 7d947558360ebfa3e39a4242ae98c7a6086750a3.

**Closed by scheglov** 2019-01-03 19:32 UTC
Labels: analyzer-server, area-analyzer, type-bug
