### ISSUE TITLE
nnbd migration tool UI suggestion: annotate a declaration with "late" or "late final"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#43124] opened 2020-08-20 06:09 UTC
It would be nice if the migration tool had one-click ways to add "/\*late\*/" or "/\*late final\*/", the same way it has ways to add "/\*?\*/".

**Comment by srawlins** [comment] 2020-09-08 22:45
Duplicate of #41389, #41655, #41874

**Closed by srawlins** 2020-09-08 22:45 UTC
Labels: analyzer-nnbd-migration, area-analyzer
