### ISSUE TITLE
Front-end errors are double reported by the VM

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#32976] opened 2018-04-25 17:31 UTC
Front-end errors from Fasta (e.g., the code in https://github.com/dart-lang/sdk/issues/32871) are double reported when run on the Dart VM.

This does not occur when using the Fasta tool or dart2js, so it seems like an issue in the VM's Fasta API or its use.

**Comment by jensjoha** [comment] 2018-04-30 13:34
This was fixed with cd0c4e4fe1e5b69ac15c0a670f9dde2ee9733fc7 right?
I at least cannot reproduce so I'm closing it for now. Reopen if it's still a problem.

**Closed by jensjoha** 2018-04-30 13:34 UTC
Labels: P2 medium, area-front-end, area-vm
