### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by amrdesign** [dart-lang/sdk#34903] opened 2018-10-23 15:56 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4892.20`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.4892.20, JRE 1.8.0_152-release-1248-b19x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

Please append the contents of:
file://C:\Users\amr\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [F:\lab\flutter\thunders], excluded: [F:\lab\flutter\thunders\.idea, F:\lab\flutter\thunders\.dart_tool, F:\lab\flutter\thunders\.idea, F:\lab\flutter\thunders\.pub, F:\lab\flutter\thunders\build]}, clientRequestTime: 1540298582867}
FileSystemException: Exists failed, path = 'F:\lab\flutter\thunders\build\app\intermediates\transforms\dexBuilder\debug\6\io' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-25 13:16
Duplicate of #34294.

**Closed by stereotype441** 2018-10-25 13:16 UTC
Labels: area-analyzer
