### ISSUE TITLE
@required seemingly ignored in default constructors

### ISSUE THREAD

**Issue by duzenko** [dart-lang/sdk#37266] opened 2019-06-14 14:46 UTC
* Dart SDK Version (`dart --version`)
`Dart VM version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "windows_x64"`
* Whether you are using Windows, MacOSX, or Linux (if applicable)
`Windows 10 x64`
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
`Flutter`

```
class BasePage extends StatelessWidget {
  final String title;

  BasePage({@required this.title});
...
}

class OpportunitiesPage extends BasePage {
// default (no) constructor
...
}
...
OpportunitiesPage();
```

This seems to compile just fine to me. When debugger stops in BasePage() due to a breakpoint I can see title be null.
Is this the expected behavior?

**Comment by srawlins** [comment] 2019-06-14 15:34
Ooh interesting catch. I've filed this as an enhancement request rather than a bug, because the [specification of @required](https://pub.dev/documentation/meta/latest/meta/required-constant.html) does not spell out that implicit no-arg super constructor calls should be included... if this is a valid request, it would probably be a new analyzer Hint, with specific text about the implicit call.

CC @bwilkerson

**Comment by srawlins** [comment] 2019-06-14 15:41
CC @stereotype441 as well; I think this brings up Non-nullable type implications. It's interesting that `BasePage({@required this.title})` is a valid "zero-arg constructor," when it accepts a named argument tied to a final field. I suppose it's okie dokey because the value of `this.title` will be assigned a default value of `null` if the constructor is called implicitly. NNBD features truly required named parameters, right?

The message on a new Hint regarding this implicit super call of a constructor with a `@required` parameter would say something like "You think you have a zero-arg super constructor, but as per the rules of @required, you don't. You must explicitly call the super constructor, or make all parameters of the default super constructor truly optional."

**Comment by bwilkerson** [comment] 2019-06-14 15:55
Yes, NNBD defines truly required named parameters. In that world (assuming the annotation is replaced by the real syntax), the constructor in `BasePage` will no longer be a zero argument constructor.

I don't know whether it's worth adding a new hint (or enhancing the existing hint) to cover this case given that NNBD will define explicit support for this, but I'm happy to see it added if we think there's enough value.

**Comment by srawlins** [comment] 2019-12-11 04:00
I just checked in tests for the `@required` filed formal parameter.

I'd like to close this feature request in favor of the same feature around the `required` keyword in the forthcoming non-nullable type system.

**Comment by srawlins** [comment] 2020-06-20 17:57
This was previously reported at https://github.com/dart-lang/sdk/issues/30117; please follow along there.

**Comment by srawlins** [comment] 2020-06-20 17:57
Duplicate of #30117

**Closed by srawlins** 2020-06-20 17:57 UTC
Labels: analyzer-hint, area-analyzer, type-enhancement
