### ISSUE TITLE
double big bug

### ISSUE THREAD

**Issue by MinuteReversal** [dart-lang/sdk#42586] opened 2020-07-06 09:39 UTC
```dart
void main(List<String> args) {
  print(0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 == 1);//false
}
```

**Comment by eernstg** [comment] 2020-07-06 10:19
First, you're comparing a `double` and an `int`, so they aren't equal.

Second, the failure to get an equality even with two `double`s is a property of computerized representations of real numbers. The problem is that there is no finite precise representation of decimal 0.1 using binary (in IEEE 754 or any other format), so what you get is not precisely 0.1 and hence the sum isn't precisely 1.0.

This is working as intended, so I'll close the issue.

**Closed by eernstg** 2020-07-06 10:19 UTC

**Comment by MinuteReversal** [comment] 2020-07-07 01:52
#Very confusing

```dart
void main(List<String> args) {
  print(0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 == 1.0); //false
  print(0.1 * 10 == 1.0); //true
  print(0.5 + 0.5 == 1); //different type compare value are true
}
```

**Comment by eernstg** [comment] 2020-07-07 07:57
True, floating point arithmetic is confusing. ;-)

`0.1 * 10 == 1.0` must be true because the rounding error happens to disappear in this particular case. `0.5 + 0.5 == 1.0` is true because `0.5` has a precise representation in binary, so there is no rounding error.

For the comparison of different types, I forgot one thing: The `num` class actually [declares](https://api.dart.dev/stable/2.8.4/dart-core/num/operator_equals.html) an `operator ==` which will convert an `int` receiver to a `double` if the argument is a `double`, and vice versa, so even `0.5 + 0.5 == 1` yields true. The case where we do get false is `identical`, for instance `identical(1.0, 1)` is false.
