### ISSUE TITLE
int += int results in num cannot be assigned to int

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26912] opened 2016-07-19 07:45 UTC
![image](https://cloud.githubusercontent.com/assets/405837/16942250/63e3b6a0-4d95-11e6-89a5-0d2dcf3ccb3f.png)

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
  - lib/remote_model/**

linter:
  rules:
    - always_declare_return_types
#    - always_specify_types
    - annotate_overrides
#    - avoid_as
    - avoid_init_to_null
    - avoid_empty_else
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - one_member_abstracts
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
#    - public_member_api_docs
    - slash_for_doc_comments
#    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
#    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters # https://groups.google.com/a/dartlang.org/forum/#!topic/reviews/Q8D-mKoUVQA
    - unrelated_type_equality_checks
    - package_names
```

**Comment by bwilkerson** [comment] 2016-07-19 15:21
This is either `StaticTypeWarningCode.INVALID_ASSIGNMENT` or `HintCode.INVALID_ASSIGNMENT`. My guess is the latter and that the code isn't correctly handling the special cases around numerics.

**Comment by leafpetersen** [comment] 2016-07-19 23:39
Yeah, I think this is likely another propagated type issue like the one that @jmesserly ran into recently.

**Comment by jmesserly** [comment] 2016-07-20 17:22
So this only happens with `implicit-casts: false` ... I was wondering otherwise why we didn't hit it before :).

I think y'all are right. What is going on is propagated type here is 'num'. We were getting by before via implicit cast. When implicit-cast is turned off, it changes StrongTypeSystemImpl.isAssignableTo and it no longer allows `num` assigned to `int`

**Comment by bwilkerson** [comment] 2016-07-20 18:19
I checked the code and we're handling type propagation in exactly the same way as static types for compound assignments. Furthermore, looking at the code I can't see why we would be ending up with propagated type information at all: everything is statically typed.

Also, I am unable to reproduce this behavior on bleeding edge. I tried the following test case:

```
List<Column> columns = [];

int getHeaderWidth() {
  int headerWidth = 0;
  int ii = columns != null ? columns.length : 0;
  for (int i = 0; i < ii; i++) {
    int width = columns[i].width;
    headerWidth += width;
  }
  return headerWidth;
}

class Column {
  int get width => 2;
}
```

**Comment by jmesserly** [comment] 2016-07-20 18:35
@bwilkerson -- ah yeah, good catch. I can't reproduce either with your example and no-implicit-casts. I wonder if one of the lints could've been interacting in a weird way?

**Comment by bwilkerson** [comment] 2016-07-20 18:46
I tried it with the same lints enabled. The only difference in the files was the removal of the `exclude:` list because my disk isn't laid out the same. The lints have no effect.

**Comment by jmesserly** [comment] 2016-07-20 18:54
oops. I made the mistake of running without strong. I can reproduce it with your example code and these options:
```dart
$ dartanalyzer --strong --no-implicit-casts ~/scratch/test.dart
Analyzing [test.dart]...
[error] A value of type 'num' cannot be assigned to a variable of type 'int' (test.dart, line 8, col 20)
1 error found.
```

**Comment by jmesserly** [comment] 2016-07-20 18:56
simplified repro:
```dart
void f() {
  int headerWidth = 0;
  int width = 0;
  headerWidth += width;
}
```

**Comment by jmesserly** [comment] 2016-07-20 19:01
huh, it looks like refineBinaryExpressionType is supposed to be handling this. I wonder if we don't make it there for op assign, or some other strange thing is going on.

**Comment by jmesserly** [comment] 2016-07-20 22:25
Oh shoot. Op assign is an AssignmentExpression, and visitAssignmentExpression (in static_type_analyzer.dart) doesn't have any of the logic visitBinaryExpression has. Doh.

**Comment by jmesserly** [comment] 2016-07-20 22:26
BTW, dropping from P1->P2 as this (mainly, but not exclusively) affects our experimental no-implicit-casts flag. I'm still working on a fix though.

**Comment by jmesserly** [comment] 2016-07-20 22:59
https://codereview.chromium.org/2166133002

**Closed** 2016-07-21 00:37 UTC
Labels: analyzer-strong-mode, area-analyzer, P2 medium, Type: bug
