### ISSUE TITLE
_nativeGetRemotePeer() throws or returns an exception whenever remoteAddress Socket's property getter is called!

### ISSUE THREAD

**Issue by ahmadSaeedGoda** [dart-lang/sdk#48456] opened 2022-02-22 22:52 UTC
* Dart SDK Version (`dart --version`): Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "linux_x64"
* Operating System is Linux UBUNTU.

_nativeGetRemotePeer() throws or returns an exception whenever `remoteAddress` Socket's property getter is called!

This _nativeGetRemotePeer() function appears to be a C native function called by Dart code. I have no access to debug the native code since debugger just reads or steps over the Dart code. So I would love to figure out how to debug the C native code or simply overcome such an issue!

I have no idea where this function's implementation resides. However, it's called or referenced in `sync_socket_patch.dart` file that lives in `/home/$USER/snap/flutter/common/flutter/bin/cache/dart-sdk/lib/_internal/vm/bin/sync_socket_patch.dart`.

Would you kindly advise?

**Comment by a-siva** [comment] 2022-02-24 21:48
@ahmadSaeedGoda the code for _nativeGetRemotePeer lives in `sdk/bin/sync_socket.cc` under SynchronousSocket_GetRemotePeer
If you want to debug the C native code yourself you would have to build a version of the Dart VM using instructions here https://github.com/dart-lang/sdk/wiki/Building and then run the build under a debugger, set a breakpoint at SynchronousSocket_GetRemotePeer and step through that code.

What kind of error do you get back when remoteAddress is called? Could it be that the socket is not connected and there is no remote when you are making this call ?

**Comment by ahmadSaeedGoda** [comment] 2022-02-26 21:58
couldn't find the code for `_nativeGetRemotePeer` under that path `sdk/bin/sync_socket.cc` though!

**Comment by a-siva** [comment] 2022-02-27 02:38
see `sdk/sdk/lib/_internal/vm/bin)/sync_socket_patch.dart`

It will have this code which links the Dart method to the corresponding native implementation

```
@pragma("vm:external-name", "SynchronousSocket_GetRemotePeer")
external List _nativeGetRemotePeer();
```
You should look for the method `SynchronousSocket_GetRemotePeer` in `sdk/bin/sync_socket.cc`

**Comment by ahmadSaeedGoda** [comment] 2022-02-27 18:44
Simply there is no `C` files at all inside the SDK folders. @a-siva

**Comment by a-siva** [comment] 2022-03-01 06:48
This CL [https://dart-review.googlesource.com/c/sdk/+/234662](https://dart-review.googlesource.com/c/sdk/+/234662) should fix the type error mismatch that is currently showing up.
It looks like an error is happening and the native method is throwing an exception. It should be possible to figure out the actual error with the above change.

Do you have a mechanism for building the VM and trying your test ?
If not if you could provide a reproduction we could investigate it here.

**Comment by a-siva** [comment] 2023-11-10 22:57
Closing this issue as a CL to fix the type error mismatch has been submitted and the above reproduction steps works just fine with the latest version of Dart.

**Closed by a-siva** 2023-11-10 22:57 UTC
Labels: area-vm
