### ISSUE TITLE
Potential null check issue in code compiled for the web

### ISSUE THREAD

**Issue by maxluchterhand1** [dart-lang/sdk#55334] opened 2024-03-29 13:20 UTC
It looks like there is something weird going on with using null check patterns on nullable strings in Dart 3.3.1 (compiled for web).

I'm running a Flutter 3.19.3 web app in Google Chrome Canary 125.0.6386.0.

```
      print('query: $query');
      if (query case final query?) {
        print('$query is not null');
      } else {
        print('$query is null');
      }
```

Output

```
query: mystring
null is null
```

The code behaves as expected when compiled for MacOS.

```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.3.1 23D60 darwin-arm64, locale en-DE)
    • Flutter version 3.19.3 on channel stable at /Users/max/fvm/versions/3.19.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (3 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/max/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Users/max/Applications/Android Studio Hedgehog 2023.1.1.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/max/Applications/Android Studio Hedgehog 2023.1.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • Max’iPad (mobile)               • 00008101-001264C02690801E • ios            • iOS 17.3.1 21D61
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 125.0.6386.0 canary

[✓] Network resources
    • All expected network resources are available.
```

```
#### General info

- Dart 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"
- on macos / Version 14.3.1 (Build 23D60)
- locale is en-DE

#### Project info

- sdk constraint: '>=3.3.1 <4.0.0'
- dependencies: auto_size_text, bloc, collection, cupertino_icons, dynamic_color, equatable, firebase_core, floating_action_bubble, flutter, flutter_bloc, flutter_svg, flutter_vector_icons, google_fonts, google_geocoding_api, google_maps_flutter, hydrated_bloc, oauth2, reorderable_grid_view, swipeable_page_route, uuid, very_good_analysis
- dev_dependencies: flutter_lints, flutter_test
- elided dependencies: 2
```

**Comment by sigmundch** [comment] 2024-03-29 23:55
Thank you so much for reporting the issue @maxluchterhand1! 

I believe this is a duplicate of https://github.com/dart-lang/sdk/issues/54559. Which was fixed recently. The fix landed in 70d3adade20205a073b30967f1018e6fcf8de17e, which is already in the main, dev, and beta releases of 3.4.0.

**Closed by sigmundch** 2024-03-29 23:55 UTC
Labels: area-web

**Comment by sigmundch** [comment] 2024-03-30 00:00
Note that while the fix rolls out, you can workaround the problem by introducing a new variable name and not shadowing the outer variable. For example:

```dart
void main() {
  final query = "myquery";
  print('query: $query');
  if (query case final query?) {
    print('A $query is not null');
  } else {
    print('B $query is null');
  }

  if (query case final query2?) {
    print('C $query2 is not null');
  } else {
    print('D $query is null');
  }
}
```

Prints:
```
query: myquery
B null is null
C myquery is not null
```
