### ISSUE TITLE
Flaky assertion failure "virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)" on vm-win-debug-x64c

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#51882] opened 2023-03-28 16:14 UTC
From `ignored_flaky_test_failure_logs` on the latest build on `vm-win-debug-x64c`:

```
/===================================================================================================\
| co19/Language/Types/Function_Types/subtype_optional_args_t06 broke (Pass -> Crash, expected Pass) |
\===================================================================================================/

--- Command "vm" (took 02.000718s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\co19\src\Language\Types\Function_Types\subtype_optional_args_t06.dart

exit code:
1073741845

stderr:
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c co19/Language/Types/Function_Types/subtype_optional_args_t06

/===============================================================================================\
| co19/LanguageFeatures/Patterns/switch_expression_A03_t13 broke (Pass -> Crash, expected Pass) |
\===============================================================================================/

--- Command "vm" (took 03.000054s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64c --enable-experiment=patterns --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\co19\src\LanguageFeatures\Patterns\switch_expression_A03_t13.dart

exit code:
1073741845

stderr:
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c co19/LanguageFeatures/Patterns/switch_expression_A03_t13

/=================================================================================================\
| co19/LibTest/typed_data/Uint8ClampedList/takeWhile_A01_t01 broke (Pass -> Crash, expected Pass) |
\=================================================================================================/

--- Command "vm" (took 03.000081s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\co19\src\LibTest\typed_data\Uint8ClampedList\takeWhile_A01_t01.dart

exit code:
1073741845

stderr:
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c co19/LibTest/typed_data/Uint8ClampedList/takeWhile_A01_t01

/=====================================================================================\
| language/override/inheritance_method2_test/083 broke (Pass -> Crash, expected Pass) |
\=====================================================================================/

--- Command "vm" (took 02.000610s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\out\DebugX64C\generated_tests\language\override\inheritance_method2_test_083.dart

exit code:
1073741845

stderr:
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c language/override/inheritance_method2_test/083

/====================================================================================================\
| language/super/operator_index_test/04 broke (CompileTimeError -> Crash, expected CompileTimeError) |
\====================================================================================================/

--- Command "vm" (took 02.000730s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\out\DebugX64C\generated_tests\language\super\operator_index_test_04.dart

exit code:
1073741845

stderr:
out/DebugX64C/generated_tests/language/super/operator_index_test_04.dart:26:10: Error: Superclass has no method named '[]='.
    super[4] += 5; //# 04: compile-time error
         ^
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c language/super/operator_index_test/04

/======================================================================\
| lib/collection/queue_first_test broke (Pass -> Crash, expected Pass) |
\======================================================================/

--- Command "vm" (took 02.000889s):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-x64c --ignore-unrecognized-flags --packages=C:\b\s\w\ir\.dart_tool\package_config.json C:\b\s\w\ir\tests\lib\collection\queue_first_test.dart

exit code:
1073741845

stderr:
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c lib/collection/queue_first_test

/================================================================\
| vm/cc/MallocGrowableArray broke (Pass -> Crash, expected Pass) |
\================================================================/

--- Command "run_vm_unittest" (took 338ms):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\run_vm_tests.exe --dfe=C:\b\s\w\ir\out\DebugX64C\gen\kernel-service.dart.snapshot --enable-experiment=records --sound-null-safety --ignore-unrecognized-flags MallocGrowableArray

exit code:
1073741845

stdout:
Running test: MallocGrowableArray
Done: MallocGrowableArray

stderr:
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c vm/cc/MallocGrowableArray

/=========================================================================\
| vm/cc/NativeFinalizer_CrossGen_149 broke (Pass -> Crash, expected Pass) |
\=========================================================================/

--- Command "run_vm_unittest" (took 371ms):
set DART_CONFIGURATION=DebugX64C & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=C:\b\s\w\ir\out\DebugX64C\crashpad_handler.exe & out\DebugX64C\run_vm_tests.exe --dfe=C:\b\s\w\ir\out\DebugX64C\gen\kernel-service.dart.snapshot --enable-experiment=records --sound-null-safety --ignore-unrecognized-flags NativeFinalizer_CrossGen_149

exit code:
1073741845

stdout:
Running test: NativeFinalizer_CrossGen_149
Done: NativeFinalizer_CrossGen_149

stderr:
collect_new_space: true evacuate_new_space_and_collect_old_space: true
entry1 space: new
entry2 space: old
value1 space: new
value2 space: old
CollectOldSpace
Marker 00000258802F2ED0 Processing Entry 00000259003888A0
Marker 00000258802F2ED0 Value collected entry 00000259003888A0 finalizer 0000025900388870
Marker 00000258802F2ED0 Running native finalizer 0000025900388870 callback 00007FF6419EC4D7 with token 0000005F5ED8ECE8
Marker 00000258802F2ED0 Clearing external size 2048 bytes in old space
Marker 00000258802F2ED0 Scheduling finalizer 0000025900388870 callback on isolate 0000025880304E30
CollectNewSpace
Scavenger::ProcessOldFinalizerEntry 00000259003888A0
Scavenger 00000258800B54E0 Processing Entry 0000025900100128
Scavenger 00000258800B54E0 Value collected entry 0000025900100128 finalizer 0000025900388870
Scavenger 00000258800B54E0 Running native finalizer 0000025900388870 callback 00007FF6419EC4D7 with token 0000005F5ED8ECF0
Scavenger 00000258800B54E0 Clearing external size 1024 bytes in new space
CollectAllGarbage
Scavenger::ProcessOldFinalizerEntry 00000259003888A0
Scavenger::ProcessOldFinalizerEntry 0000025900379230
Marker 00000258802F2ED0 Processing Entry 0000025900379230
Marker 00000258802F2ED0 Processing Entry 00000259003888A0
collect_new_space: false evacuate_new_space_and_collect_old_space: true
entry1 space: new
entry2 space: old
value1 space: new
value2 space: old
CollectOldSpace
Marker 0000025880303120 Processing Entry 00000259003888F0
Marker 0000025880303120 Value collected entry 00000259003888F0 finalizer 00000259002B7840
Marker 0000025880303120 Running native finalizer 00000259002B7840 callback 00007FF6419EC4D7 with token 0000005F5ED8ECE8
Marker 0000025880303120 Clearing external size 2048 bytes in old space
Marker 0000025880303120 Scheduling finalizer 00000259002B7840 callback on isolate 0000025880304E30
Marker 00000258802F2ED0 Processing Entry 0000025900379230
Marker 00000258802F2ED0 Processing Entry 00000259003888A0
CollectAllGarbage
Scavenger::ProcessOldFinalizerEntry 00000259003888F0
Scavenger::ProcessOldFinalizerEntry 00000259003793E0
Scavenger 00000258800B4710, promoting external size 1024 bytes from new to old space
Marker 00000258802F2ED0 Processing Entry 0000025900379230
Marker 00000258802F2ED0 Processing Entry 00000259003888A0
Marker 00000258802F2ED0 Processing Entry 00000259003793E0
Marker 00000258802F2ED0 Value collected entry 00000259003793E0 finalizer 00000259002B7840
Marker 00000258802F2ED0 Running native finalizer 00000259002B7840 callback 00007FF6419EC4D7 with token 0000005F5ED8ECF0
Marker 00000258802F2ED0 Clearing external size 1024 bytes in old space
Marker 00000258802F2ED0 Processing Entry 00000259003888F0
../../runtime/vm/virtual_memory_compressed.cc: 130: error: expected: Utils::IsAligned(size, kCompressedPageSize)
../../runtime/vm/profiler.cc: 452: error: expected: os_thread != nullptr
Aborting reentrant request for stack trace.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-x64c vm/cc/NativeFinalizer_CrossGen_149
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8785407414562737505/+/u/test_results/ignored_flaky_test_failure_logs

The assertion failure is not tied to particular tests, but every build there are multiple tests which fail with this assertion.

Previous builds:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8785498013174267681/+/u/test_results/ignored_flaky_test_failure_logs

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8785588610786128833/+/u/test_results/ignored_flaky_test_failure_logs

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8785679205143804481/+/u/test_results/ignored_flaky_test_failure_logs

/cc @liamappelbe @rmacnak-google

**Comment by rmacnak-google** [comment] 2023-03-29 16:56
Duplicate of https://github.com/dart-lang/sdk/issues/51170

**Closed by rmacnak-google** 2023-03-29 16:56 UTC
Labels: area-vm
