### ISSUE TITLE
Element not found in summary: Future

### ISSUE THREAD

**Issue by dmjones** [dart-lang/sdk#34954] opened 2018-10-28 06:48 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4892.20`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IU-182.4892.20, JRE 1.8.0_152-release-1248-b19x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1280x800  Retina`

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/duncan/git/groupsnap2/lib/guest/guest_presenter.dart
Exception: Element not found in summary: package:groupsnap2/guest/guest_presenter.dart;package:groupsnap2/guest/guest_presenter.dart;Future
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:983:24)
#5      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:929:15)
#6      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:954:15)
#7      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:28)
#8      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#9      ExecutableElementImpl.returnType (package:analyzer/src/dart/element/element.dart:4008:64)
#10     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/declaration_resolver.dart:364:54)
#11     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#13     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#14     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#15     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#16     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#17     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#20     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#21     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#22     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#23     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#24     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#25     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#26     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#27     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#28     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#29     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#30     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#31     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#32     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#33     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#34     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#37     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#38     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#39     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#40     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#46     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#47     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#48     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#49     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#50     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1540709168784 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/join.dart","errors":[]}}
1540709168835 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/home.dart","errors":[]}}
1540709168870 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/main.dart","errors":[]}}
1540709168879 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/duncan/git/groupsnap2/lib/guest/guest_presenter.dart","stackTrace":"Exception: Element not found i
1540709168882 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540709168982 => {"id":"217","method":"edit.getAssists","params":{"file":"/Users/duncan/git/groupsnap2/lib/guest/guest.dart","offset":514,"length":0},"clientRequestTime":1540709168982}
1540709168993 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540709169016 <= {"id":"217","result":{"assists":[]}}
1540709169021 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540709169458 => {"id":"218","method":"analysis.updateContent","params":{"files":{"/Users/duncan/git/groupsnap2/lib/guest/guest.dart":{"type":"add","content":"import 'package:flutter/material.dart';\n
1540709169458 => {"id":"219","method":"completion.getSuggestions","params":{"file":"/Users/duncan/git/groupsnap2/lib/guest/guest.dart","offset":515},"clientRequestTime":1540709169458}
1540709169459 <= {"id":"218","result":{}}
1540709169461 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540709169502 <= {"id":"219","result":{"id":"35"}}
1540709169502 <= {"event":"completion.results","params":{"id":"35","replacementOffset":515,"replacementLength":0,"results":[],"isLast":true}}
1540709169543 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/join.dart","errors":[]}}
1540709169581 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/home.dart","errors":[]}}
1540709169615 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/main.dart","errors":[]}}
1540709169623 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/duncan/git/groupsnap2/lib/guest/guest_presenter.dart","stackTrace":"Exception: Element not found i
1540709169628 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540709169712 => {"id":"220","method":"analysis.updateContent","params":{"files":{"/Users/duncan/git/groupsnap2/lib/guest/guest.dart":{"type":"add","content":"import 'package:flutter/material.dart';\n
1540709169712 => {"id":"221","method":"completion.getSuggestions","params":{"file":"/Users/duncan/git/groupsnap2/lib/guest/guest.dart","offset":516},"clientRequestTime":1540709169712}
1540709169721 <= {"id":"220","result":{}}
1540709169722 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540709169775 <= {"id":"221","result":{"id":"36"}}
1540709169776 <= {"event":"completion.results","params":{"id":"36","replacementOffset":516,"replacementLength":0,"results":[],"isLast":true}}
1540709169817 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/join.dart","errors":[]}}
1540709169920 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/home.dart","errors":[]}}
1540709169953 <= {"event":"analysis.errors","params":{"file":"/Users/duncan/git/groupsnap2/lib/main.dart","errors":[]}}
1540709169966 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/duncan/git/groupsnap2/lib/guest/guest_presenter.dart","stackTrace":"Exception: Element not found i
```

**Comment by dmjones** [comment] 2018-10-28 06:53
AFAICT, this analyzer error was fixed by importing `package:flutter/material.dart` into a file that referenced the `Widget` class.

**Comment by stereotype441** [comment] 2018-10-29 16:30
Duplicate of #34555

**Closed by stereotype441** 2018-10-29 16:30 UTC
Labels: area-analyzer
