### ISSUE TITLE
Dart analysis server fails when working with rxdart

### ISSUE THREAD

**Issue by Mantelijo** [dart-lang/sdk#35779] opened 2019-01-26 20:35 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1536x864`

# Exception
```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\Apps\flutter\flutter_app\lib\bloc.dart
Exception: Element not found in summary: dart:async;dart:async/stream_controller.dart;Stream
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ElementHandle.name (package:analyzer/src/dart/element/handle.dart:448:22)
#4      InterfaceTypeImpl.isDartAsyncFutureOr (package:analyzer/src/dart/element/type.dart:1320:20)
#5      _isTop (package:analyzer/src/generated/type_system.dart:56:9)
#6      StrongTypeSystemImpl.isSubtypeOf (package:analyzer/src/generated/type_system.dart:1225:9)
#7      InferenceContext.popReturnContext (package:analyzer/src/generated/resolver.dart:4296:23)
#8      ResolverVisitor.visitExpressionFunctionBody (package:analyzer/src/generated/resolver.dart:5538:24)
#9      ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:4051:15)
#10     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7695:12)
#11     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5968:10)
#12     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3153:55)
#13     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:7333:11)
#14     ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:5916:11)
#15     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:7325:7)
#16     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:5906:13)
#17     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7686:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#19     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:6936:18)
#20     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:6913:11)
#21     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5253:13)
#22     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#23     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5317:25)
#24     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#25     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:592:10)
#26     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#27     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#28     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#29     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#30     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#31     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1046:39)
<asynchronous suspension>
#36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#38     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#39     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#40     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#47     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#48     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#50     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1548534739011 <= {"event":"analysis.closingLabels","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","labels":[{"offset":701,"length":128,"label":"Injector"},{"offset":730,"length":88,
1548534739012 <= {"event":"analysis.outline","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","locatio
1548534739013 <= {"event":"analysis.overrides","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","overrides":[{"offset":373,"length":18,"superclassMember":{"element":{"kind":"METHOD","
1548534739015 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548534739015 <= {"event":"analysis.implemented","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","classes":[],"members":[]}}
1548534740320 => {"id":"106","method":"analysis.updateContent","params":{"files":{"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart":{"type":"add","content":"import 'package:flutter/material.dart';\nimp
1548534740322 <= {"id":"106","result":{}}
1548534740323 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548534740349 => {"id":"107","method":"edit.getAssists","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","offset":1681,"length":0},"clientRequestTime":1548534740349}
1548534740612 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: D:\\Apps\\flutter\\flutter_app\\lib\\main.dart context: exception_20190126_223220_539","stackTrace":"Exce
1548534740967 <= {"id":"107","result":{"assists":[]}}
1548534740977 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548534751630 => {"id":"108","method":"edit.getAssists","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","offset":1960,"length":160},"clientRequestTime":1548534751630}
1548534751631 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548534751724 => {"id":"109","method":"edit.getAssists","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","offset":1957,"length":163},"clientRequestTime":1548534751724}
1548534751724 => {"id":"110","method":"edit.getAssists","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","offset":1957,"length":163},"clientRequestTime":1548534751724}
1548534751891 <= {"id":"108","result":{"assists":[]}}
1548534752258 <= {"id":"109","result":{"assists":[]}}
1548534752258 <= {"id":"110","result":{"assists":[]}}
1548534752270 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548534752628 => {"id":"111","method":"edit.getAssists","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","offset":1957,"length":163},"clientRequestTime":1548534752628}
1548534752631 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548534752680 <= {"id":"111","result":{"assists":[]}}
1548534752681 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1548534754698 => {"id":"112","method":"analysis.updateContent","params":{"files":{"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart":{"type":"add","content":"import 'package:flutter/material.dart';\nimp
1548534754701 <= {"id":"112","result":{}}
1548534754701 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1548534754702 => {"id":"113","method":"edit.getAssists","params":{"file":"D:\\Apps\\flutter\\flutter_app\\lib\\main.dart","offset":1823,"length":0},"clientRequestTime":1548534754702}
1548534754795 <= {"id":"113","result":{"assists":[]}}
1548534754805 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: D:\\Apps\\flutter\\flutter_app\\lib\\bloc.dart","stackTrace":"Exception: Element not found in summary: da
```

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: D:\Apps\flutter\flutter_app\lib\bloc.dart
Exception: Element not found in summary: dart:async

**Comment by stereotype441** [comment] 2019-01-28 18:11
Duplicate of #34555

**Closed by stereotype441** 2019-01-28 18:11 UTC
Labels: area-analyzer, type-bug
