### ISSUE TITLE
Dart formatter crashes on program that seems to be valid Dart

### ISSUE THREAD

**Issue by maks** [dart-lang/sdk#48664] opened 2022-03-25 07:29 UTC
@bwilkerson  this seems to be same as #47020 except for this input:
```dart
class MyItem {
  const MyItem();
}

class MyCollection{
  final List<MyItem> items;
  MyCollection({required this.items});
}

void atest() {
  MyCollection? foo = MyCollection(items: 
  const [
    MyItem()
    MyItem()
  ]);
}
```

TBH I didnt know that not having commas separating the list items was valid but both my local Dart and Dartpad seem to agree its valid Dart code, yet it causes the formatter (run via VSCode) to crash with:
```
[Error - 6:23:15 pm] Request textDocument/formatting failed.
  Message: An error occurred while handling textDocument/formatting request
  Code: -32001 
[Error - 6:23:15 pm] An error occurred while handling textDocument/formatting request: The formatter produced unexpected output. Input was:
class MyItem {
  const MyItem();
}

class MyCollection{
  final List<MyItem> items;
  MyCollection({required this.items});
}

void atest() {
  MyCollection? foo = MyCollection(items: 
  const [
    MyItem()
    MyItem()
    MyItem()
  ]);
  
}
Which formatted to:
class MyItem {
  const MyItem();
}

class MyCollection {
  final List<MyItem> items;
  MyCollection({required this.items});
}

void atest() {
  MyCollection? foo = MyCollection(items: const [MyItem(), MyItem(), MyItem()]);
}

#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:178:7)
#1      generateEditsForFormatting (package:analysis_server/src/lsp/source_edits.dart:94:33)
#2      FormattingHandler.formatFile (package:analysis_server/src/lsp/handlers/handler_formatting.dart:35:12)
#3      FormattingHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_formatting.dart:52:14)
#4      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:249:12)
#5      FormattingHandler.handle (package:analysis_server/src/lsp/handlers/handler_formatting.dart:46:17)
#6      MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:137:12)
#7      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:171:36)
#8      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:341:47)
#9      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:336:21)
#10     _rootRun (dart:async/zone.dart:1426:13)
#11     _CustomZone.run (dart:async/zone.dart:1328:19)
#12     _runZoned (dart:async/zone.dart:1861:10)
#13     runZonedGuarded (dart:async/zone.dart:1849:12)
#14     LspAnalysisServer.handleMessage (package:analysis_server/src/lsp/lsp_analysis_server.dart:336:5)
#15     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:85:16)
#16     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:54:24)
#17     _rootRunUnary (dart:async/zone.dart:1434:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#24     _rootRun (dart:async/zone.dart:1418:47)
#25     _CustomZone.run (dart:async/zone.dart:1328:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#28     _rootRun (dart:async/zone.dart:1426:13)
#29     _CustomZone.run (dart:async/zone.dart:1328:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)

```

**Comment by maks** [comment] 2022-03-25 07:31
Apologies forgot to add this is with Flutter stable channel, so:
```
flutter --version
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Comment by bwilkerson** [comment] 2022-03-25 14:24
> TBH I didnt know that not having commas separating the list items was valid ...

It isn't. That appears to be a bug in the analyzer. I have confirmed that it isn't being reported from the version of the SDK that's being used by DartPad.

I've also confirmed that the bug has been fixed on HEAD, where the analyzer reports the following:
```
error: Expected to find ','. (expected_token at [test_package] lib/test.dart:14)
```
The reason for the formatter's crash was that the parser recovers from this error by inserting a synthetic comma where it was required. (It's supposed to produce a diagnostic when it recovers, but that appears to have been the bug.) The formatter doesn't notice that the comma is synthetic, so when it validates that there are only whitespace changes to the input it discovers that a comma was added, and it fails.

**Comment by vsmenon** [comment] 2022-03-25 18:31
@bwilkerson - should this be filed on dart-style?

**Comment by bwilkerson** [comment] 2022-03-25 19:26
> Is the purpose of this exception to get people to file bugs?

@munificent ?

> If so, I think changing the text here might prevent that ...

I wasn't necessarily trying to prevent users from reporting the exception (I'm glad we found out that a valid diagnostic wasn't being produced), I was more interested in providing actionable information (try fixing the syntax errors and then retry the format).

> Right now, we can't tell in LSP whether a format request was explicit ...

That does complicate things. With auto-save and format-on-save both enabled, the probability of attempting to format when there are syntax errors is probably fairly high. I don't know what percentage of users have both enabled, though.

**Comment by DanTup** [comment] 2022-03-25 20:21
> With auto-save and format-on-save both enabled, the probability of attempting to format when there are syntax errors is probably fairly high. I don't know what percentage of users have both enabled, though.

I don't know about both, but of those sending analytics, ~60% have format-on-save enabled. I'm one of those, and I do recall it was quite annoying in that case too - although off the top of my head I couldn't say how often I saw it (it doesn't seem like I should save with syntax errors very often, but I believe it was enough to want to change it).

I just remembered that in VS Code's API (not LSP), we are able to capture a save reason. That means we can probably capture it and inject the value into the format requests so that we could access it in the server. It would be slightly non-standard (although optional/compatible), but I wonder if it's worth doing for the improved UX. It would allows us to silence all errors for any automatic errors (as we mostly do today - besides this type of error), but surface them for explicit saves so that if a user finds we're not formatting their code, it's a bit clearer why.

**Comment by maks** [comment] 2022-03-26 02:53
@bwilkerson thanks for looking into this so quickly!

Just as a point of reference, the only reason I came across this was because I do normally have format-on-save turned on in VScode and was editing a largish Flutter Widget src file that was originally authored by someone else, so tracking down the lines causing the issue turned out to be non-trivial.

I used to have auto-save turned on as well, though I turned that off a while ago due to some other problems I ran into, but I would think there would be a fair few people who would have that combination enabled.

And I am in the habit of using `cntrl-s` to format a file often when there may still be syntax errors present in the file as before this that wouldn't affect my workflow.

**Comment by maks** [comment] 2022-03-28 21:27
Thanks @DanTup using the new indicator UI sounds like it would work well for this particular problem.
If the existing Dart LSP has support for that, should I open a new issue on DartCode repo for this and close this one?

**Comment by munificent** [comment] 2022-03-28 22:51
Yeah, so what's going on here is:

1. The formatter is given some input code.
2. It sends it to the analyzer to parse it. Analyzer gives it back an AST.
3. The formatter formats that AST to a formatted string.
4. Then it runs an internal sanity check to make sure that the only differences between the text at step 1 and 3 are whitespace.

The *intent* of that sanity check is to catch dart_style bugs in step 3 and make sure that if there is a bug in the formatter, that it doesn't overwrite the user's code. But it also effectively catches bugs in step 2 as well. In particular, every now and then we find a bug in the parser where invalid Dart code is parsed without reporting a syntax error. Since no error was reported, dart_style thinks the resulting AST is valid and goes ahead and formats it.

There's no easy way for the sanity check to tell whether the bug is in the parser or the formatter. (If we knew that, we'd just fix the bug in the first place.) So the error message the formatter reports when the sanity check fails is probably about as precise as we can be.

In practice, bugs in the parser like this where it fails to report a syntax error are fairly rare.

The fix for this particular bug is in the parser in the analyzer package and not in dart_style itself, so I'm going to go ahead and close this issue.

**Comment by munificent** [comment] 2022-03-28 22:52
Oops, sorry, thought this was in the dart_style repo. Reopening. :)

**Comment by DanTup** [comment] 2022-03-29 09:05
Based on [@bwilkerson's comment above](https://github.com/dart-lang/sdk/issues/48664#issuecomment-1079078810) I think the bug has already been fixed, although there's an open question about whether to change how the LSP server handles this type of error. I think the options are:

1. Do nothing. When this issue occurs, the user will see "An LSP request failed" and the Output pane will include the error/call stack above. It sounds like this will be pretty rare, and it will probably lead to users raising issues.
2. Catch the error and provide a different error (stating that formatting failed and this may be due to invalid code, "correct your code and try again"). Users probably won't raise issues in this case (unless we suggest to do so in the error) as it seems like normal behaviour.
3. Catch the error and just silently return an empty edit set (this is what we do for other types of formatting failures, - there is currently no feedback to avoid format-on-save etc. being spammy, although I'm hopeful in future LSP may have better ways for us to report this in a non-spammy way).

I think whether to do 1 depends on how important it is to get bug reports from this behaviour. If these tend to be found and fixed quickly without reports from most stable users, perhaps additional reports are unnecessary. If bug reports are preferred, perhaps it's best to leave as-is (1).

If more bug reports are not required, I'd have a slight preference for 3 over 2, since it seems odd to show an error when trying to format bad code only for some tiny fraction of format requests (and if LSP gets better APIs to avoid the error being completely silent, they could be consistent there).

@munificent @bwilkerson I don't know how often these issues occur or how quickly they're usually found/fixed, perhaps you have opinions on the options above (or other options)?

**Comment by munificent** [comment] 2022-03-29 17:52
I definitely do want to get bug reports for this. I'm happy to be the one to triage whether the bug is actually in the formatter or in the parser. (In practice, most of these bugs encountered in the wild tend to be in the parser, but that's because I always run the formatter on a huge corpus before shipping significant changes. On *my machine*, that sanity check catches bugs in my new formatting code all the time.)

I think leaving the current behavior is OK.

**Comment by munificent** [comment] 2022-04-07 00:08
Great idea. Filed: https://github.com/dart-lang/dart_style/issues/1105

**Comment by DanTup** [comment] 2022-04-07 10:32
Great - sounds like there's nothing to do in the LSP server then, it'll show any updated message from dart_style. Thanks!

**Closed by DanTup** 2022-04-07 10:32 UTC
Labels: area-analyzer
