### ISSUE TITLE
Exception when extracting local variable

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#39211] opened 2019-11-02 22:05 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.5.1`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.1, server version 1.27.2, error: NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of '_OccurrencesVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ExtractLocalRefactoringImpl._prepareOccurrences (package:analysis_server/src/services/refactoring/extract_local.dart:520:23)
#2      ExtractLocalRefactoringImpl.checkInitialConditions (package:analysis_server/src/services/refactoring/extract_local.dart:96:5)
#3      _RefactoringManager._init (package:analysis_server/src/edit/edit_domain.dart:1196:36)
<asynchronous suspension>
#4      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:982:13)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1500:12)
#9      _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:979:5)
#10     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:857:24)
#11     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:389:16)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#55     _StreamController._add (dart:async/stream_controller.dart:640:7)
#56     _StreamController.add (dart:async/stream_controller.dart:586:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59     _CustomZone.runUnary (dart:async/zone.dart...
```

For additional log information, please append the contents of
file:///private/var/folders/kl/3phq4z511m73wzrq966q3z5w0000gn/T/report.txt.

**Comment by danrubel** [comment] 2019-11-02 22:23
I was trying to extract the return value as a variable in `return datetime2.compareTo(datetime1);`

**Comment by srawlins** [comment] 2019-11-08 05:43
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38883; please follow along there.

**Comment by srawlins** [comment] 2019-11-08 05:43
Duplicate of https://github.com/dart-lang/sdk/issues/38883

**Closed by srawlins** 2019-11-08 05:43 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
