### ISSUE TITLE
Dart Analyzer Error 

### ISSUE THREAD

**Issue by LittleLeah** [dart-lang/sdk#39560] opened 2019-11-28 09:49 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.7.0-edge.fa4379946109467c8a48f20f19d83d7c72968a3e`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.fa4379946109467c8a48f20f19d83d7c72968a3e, server version 1.27.4, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\Users\nguld\AndroidStudioProjects\canitrack], excluded: [C:\Users\nguld\AndroidStudioProjects\canitrack\.idea, C:\Users\nguld\AndroidStudioProjects\canitrack\.dart_tool, C:\Users\nguld\AndroidStudioProjects\canitrack\.idea, C:\Users\nguld\AndroidStudioProjects\canitrack\.pub, C:\Users\nguld\AndroidStudioProjects\canitrack\build]}, clientRequestTime: 1574770681158}
FileSystemException: Directory watcher closed unexpectedly, path = 'C:\Users\nguld\AndroidStudioProjects\canitrack'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:309:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file://C:\Users\nguld\AppData\Local\Temp\report1.txt.

Dart analysis server, SDK version 2.7.0-edge.fa4379946109467c8a48f20f19d83d7c72968a3e, server version 1.27.4, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\Users\nguld\AndroidStudioProjects\canitrack], excluded: [C:\Users\nguld\AndroidStudioProjects\canitrack\.idea, C:\Users\nguld\AndroidStudioProjects\canitrack\.dart_tool, C:\Users\nguld\AndroidStudioProjects\canitrack\.idea, C:\Users\nguld\AndroidStudioProjects\canitrack\.pub, C:\Users\nguld\AndroidStudioProjects\canitrack\build]}, clientRequestTime: 1574770681158}
FileSystemException: Directory watcher closed unexpectedly, path = 'C:\Users\nguld\AndroidStudioProjects\canitrack'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:309:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```
1574770691611 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1213,"uri":"package:flare_dart/actor.dart","items":[{"label":"Actor","declaringLibraryUri":"package:flar
1574770691613 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1214,"uri":"package:flare_dart/actor_artboard.dart","items":[{"label":"ActorArtboard","declaringLibraryU
1574770691615 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1215,"uri":"package:flare_dart/actor_skin.dart","items":[{"label":"ActorSkin","declaringLibraryUri":"pac
1574770691616 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1216,"uri":"package:flare_dart/actor_skinnable.dart","items":[{"label":"ActorSkinnable","declaringLibrar
1574770691617 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1217,"uri":"package:flare_dart/actor_image.dart","items":[{"label":"ActorImage","declaringLibraryUri":"p
1574770691619 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1218,"uri":"package:flare_dart/actor_flags.dart","items":[{"label":"ActorFlags","declaringLibraryUri":"p
1574770691621 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1219,"uri":"package:flare_dart/math/transform_components.dart","items":[{"label":"TransformComponents","
1574770691622 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1220,"uri":"package:flare_dart/math/mat2d.dart","items":[{"label":"Mat2D","declaringLibraryUri":"package
1574770691625 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1221,"uri":"package:flare_dart/math/vec2d.dart","items":[{"label":"Vec2D","declaringLibraryUri":"package
1574770691626 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1222,"uri":"package:flare_dart/math/aabb.dart","items":[{"label":"AABB","declaringLibraryUri":"package:f
1574770691633 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1223,"uri":"package:stack_trace/stack_trace.dart","items":[{"label":"ChainHandler","declaringLibraryUri"
1574770691638 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1228,"uri":"package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart","items":[{
1574770691640 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1231,"uri":"package:typed_data/typed_data.dart","items":[{"label":"Int64Buffer","declaringLibraryUri":"p
1574770691646 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1233,"uri":"package:charcode/html_entity.dart","items":[{"label":"$sup","declaringLibraryUri":"package:c
1574770691649 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1234,"uri":"package:charcode/ascii.dart","items":[{"label":"$b","declaringLibraryUri":"package:charcode/
1574770691659 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1235,"uri":"package:charcode/charcode.dart","items":[{"label":"$sup","declaringLibraryUri":"package:char
1574770691666 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1236,"uri":"package:term_glyph/term_glyph.dart","items":[{"label":"rightEnd","declaringLibraryUri":"pack
1574770691675 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1239,"uri":"package:source_span/source_span.dart","items":[{"label":"SourceSpanFormatException","declari
1574770691680 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1247,"uri":"package:string_scanner/string_scanner.dart","items":[{"label":"StringScanner","declaringLibr
1574770691687 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1252,"uri":"package:http_parser/http_parser.dart","items":[{"label":"MediaType","declaringLibraryUri":"p
1574770691689 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1260,"uri":"package:vector_math/hash.dart","items":[{"label":"hashObjects","declaringLibraryUri":"packag
1574770691727 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":109,"uri":"package:vector_math/vector_math_64.dart","items":[{"label":"cross2A","declaringLibraryUri":"p
1574770691728 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1232,"uri":"package:typed_data/typed_buffers.dart","items":[{"label":"Int8Buffer","declaringLibraryUri":
1574770691731 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1261,"uri":"package:quiver_hashcode/hashcode.dart","items":[{"label":"hashObjects","declaringLibraryUri"
1574770691731 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":80,"uri":"package:meta/meta.dart","items":[{"label":"Immutable","declaringLibraryUri":"package:meta/meta
1574770691732 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":370,"uri":"package:firebase_core_platform_interface/firebase_core_platform_interface.dart","items":[{"la
1574770691753 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1262,"uri":"package:collection/collection.dart","items":[{"label":"maxBy","declaringLibraryUri":"package
1574770691758 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":693,"uri":"dart:_http","items":[{"label":"HttpOverrides","declaringLibraryUri":"dart:_http","element":{"
1574770691765 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":703,"uri":"dart:_internal","items":[{"label":"UnmodifiableListMixin","declaringLibraryUri":"dart:_intern
1574927236170 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\\Users\\nguld\\AndroidStudioPro
```

**Comment by srawlins** [comment] 2019-12-01 03:40
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38853; please follow along there.

**Comment by srawlins** [comment] 2019-12-01 03:40
Duplicate of https://github.com/dart-lang/sdk/issues/38853

**Closed by srawlins** 2019-12-01 03:40 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
