### ISSUE TITLE
`For-In` loops are super inefficient compared to other loops

### ISSUE THREAD

**Issue by maRci002** [dart-lang/sdk#50967] opened 2023-01-10 11:56 UTC
Compile the example benchmark code below: `dart compile exe .\loop_benchmark.dart`

Output:

> For-each Loop(RunTime): 4920026.0 us.
> For-each Cached Loop(RunTime): 3158748.0 us.
> For-in Loop(RunTime): 7487263.0 us.
> Iterator Loop(RunTime): 8304755.5 us.
> While Loop(RunTime): 2582027.5 us.
> While Cached Loop(RunTime): 2121169.0 us.
> For Loop(RunTime): 2582432.0 us.
> For Cached Loop(RunTime): 2120963.5 us.
> Press any key to continue

I don't know how can a non cached `For-each Loop ~4.9 sec` outperform a `For-in Loop ~7.5 sec`, maybe zero-overhead principle might be able to explain it, but it's still a big deal.

**Example benchmark `loop_benchmark.dart`:**

```dart
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:benchmark_harness/benchmark_harness.dart';

const iterations = 1000000;
final data = List.generate(100, (i) => Random().nextInt(100));

abstract class LoopBenchmarkBase extends BenchmarkBase {
  LoopBenchmarkBase(super.name);

  var sum = 0;

  @override
  void run() {
    for (var i = 0; i < iterations; i++) {
      sum = 0;
      loopFunction();
    }
  }

  void loopFunction();
}

class ForEachLoopBenchmark extends LoopBenchmarkBase {
  ForEachLoopBenchmark() : super('For-each Loop');

  @override
  void loopFunction() {
    data.forEach((item) => sum += item);
  }
}

class ForEachCachedLoopBenchmark extends LoopBenchmarkBase {
  ForEachCachedLoopBenchmark() : super('For-each Cached Loop');

  @override
  void loopFunction() {
    data.forEach(_forEach);
  }

  void _forEach(int item) => sum += item;
}

class ForInLoopBenchmark extends LoopBenchmarkBase {
  ForInLoopBenchmark() : super('For-in Loop');

  @override
  void loopFunction() {
    for (final item in data) {
      sum += item;
    }
  }
}

class IteratorLoopBenchmark extends LoopBenchmarkBase {
  IteratorLoopBenchmark() : super('Iterator Loop');

  @override
  void loopFunction() {
    final iterator = data.iterator;
    while (iterator.moveNext()) {
      sum += iterator.current;
    }
  }
}

class WhileLoopBenchmark extends LoopBenchmarkBase {
  WhileLoopBenchmark() : super('While Loop');

  @override
  void loopFunction() {
    var i = 0;
    while (i < data.length) {
      sum += data[i];
      i++;
    }
  }
}

class WhileCachedLoopBenchmark extends LoopBenchmarkBase {
  WhileCachedLoopBenchmark() : super('While Cached Loop');

  @override
  void loopFunction() {
    final len = data.length;
    var i = 0;

    while (i < len) {
      sum += data[i];
      ++i;
    }
  }
}

class ForLoopBenchmark extends LoopBenchmarkBase {
  ForLoopBenchmark() : super('For Loop');

  @override
  void loopFunction() {
    for (var i = 0; i < data.length; i++) {
      sum += data[i];
    }
  }
}

class ForCachedLoopBenchmark extends LoopBenchmarkBase {
  ForCachedLoopBenchmark() : super('For Cached Loop');

  @override
  void loopFunction() {
    for (var i = 0, len = data.length; i < len; ++i) {
      sum += data[i];
    }
  }
}

void main() {
  ForEachLoopBenchmark().report();
  ForEachCachedLoopBenchmark().report();

  ForInLoopBenchmark().report();
  IteratorLoopBenchmark().report();

  WhileLoopBenchmark().report();
  WhileCachedLoopBenchmark().report();

  ForLoopBenchmark().report();
  ForCachedLoopBenchmark().report();

  stdout.writeln('Press any key to continue');
  stdin.readLineSync(encoding: utf8);
}
```

`dart --version`:

> Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"

**Comment by mraleph** [comment] 2023-01-10 11:59
Duplicate of #48433

**Closed by mraleph** 2023-01-10 11:59 UTC
