### ISSUE TITLE
strong mode: T op int (with T extends num) should yield a T

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26427] opened 2016-05-09 14:47 UTC
`T op int` (with `T extends num`) should yield a `T`.

Example:
```
$ cat /tmp/t.dart
/*=T*/ foo/*<T extends num>*/(/*=T*/ x) => x * 0;

main() {
  print(foo(50));
}

$ out/ReleaseX64/dart-sdk/bin/dart --package-root=$PWD/out/ReleaseX64/packages /mnt/ssd/floitsch/code/dart/sdk/pkg/analyzer_cli/bin/analyzer.dart --no-hints --strong /tmp/t.dart
Analyzing [/tmp/t.dart]...
[warning] Unsound implicit cast from num to T (/tmp/t.dart, line 1, col 44)
1 warning found.
```

Probably as easy as adding an `|| rightType == typeProvider.intType` in `type_system.dart:359`.

**Comment by leafpetersen** [comment] 2016-05-09 15:59
It this not a duplicate of https://github.com/dart-lang/sdk/issues/25914?

**Comment by floitschG** [comment] 2016-05-09 16:00
Issue #25914 didn't specifically ask for this use case and was closed.
We can reopen and mark this one as dupe. No preference.

**Comment by leafpetersen** [comment] 2016-05-09 16:16
Ah, I see the difference now.  No, I'm fine with leaving it one this bug.

**Comment by scheglov** [comment] 2016-05-09 21:43
https://codereview.chromium.org/1957953004

**Comment by scheglov** [comment] 2016-05-10 16:51
https://github.com/dart-lang/sdk/commit/431e1b5e8030c1b3c6f9ba6d148d50e35eafa896

**Closed by scheglov** 2016-05-10 16:51 UTC
Labels: analyzer-strong-mode, area-analyzer
