### ISSUE TITLE
[dart:ffi] Default initial struct values are uninitialised on allocation

### ISSUE THREAD

**Issue by jld3103** [dart-lang/sdk#43596] opened 2020-09-29 09:02 UTC
When allocating a struct the default value for all pointer fields is `null`, but that is really counter intuitive, because in they should be `nullptr` like in C/C++.
This code demonstrates it:
```dart
import 'dart:ffi';

class Test extends Struct {
    ffi.Pointer<ffi.Int8> test;
}

void main() {
    final test = allocate<Test>().ref;
    assert(test.test == null); // This should fail
    assert(test.test == nullptr); // This shouldn't fail
}
```

**Comment by mit-mit** [comment] 2020-09-30 13:51
cc @dcharkes

**Comment by dcharkes** [comment] 2020-09-30 16:49
Actually, the memory is undefined. So, I would expect a `Pointer<Int8>` with an `address` with whatever was in the memory.

```dart
  final test = allocate<Test>().ref;
  print(test.test);
  print(test.test == null);
```

```
Pointer<Int8>: address=0x7fb6138b5e80
false
```

Which is exactly what I see locally (MacOS).

Can you give more details on how to reproduce this? Is this the full Dart program? How are you running it (asserts are disabled by default)? What platform?

**Comment by jld3103** [comment] 2020-09-30 16:55
So I'm writing a flutter embedder in dart and I created the bindings using `ffigen`. It works quite well, but when I allocate `FlutterProjectArgs` (https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h#L1165) I don't specify fields like `custom_dart_entrypoint`, but the flutter engine checks if it's not a `nullptr` and then uses it (and crashes due to wrong pointers). If I would do the same in C/C++ it would work by just not specifying these fields, because the would be `nullptr`'s.

**Comment by dcharkes** [comment] 2020-09-30 17:15
> If I would do the same in C/C++ it would work by just not specifying these fields, because the would be nullptr's.

The equivalent of what you're doing in Dart (`allocate` + `ref`) in C would be:

```c
MyStruct* ptr = malloc(sizeof(MyStruct)); // Allocates memory, does not initialise.
MyStruct test = *ptr; // Uses uninitialised memory.
```

Which is not the same as what you'd be normally doing in C:

```c
MyStruct test;
```

When adding support for passing struct by value(https://github.com/dart-lang/sdk/issues/36730), we're adding support for structs backed by TypedData instead of Pointer. TypedData is initialised to 0 and automatically garbage collected.

For now, you should manually initialise the backing memory. (You could open an issue on the ffigen repository to provide a static method on all generated Structs that initialises the backing memory, and use those instead of `allocate`+`ref`.)

**Comment by mkustermann** [comment] 2020-12-16 15:55
@jld3103 As explained above, allocating memory using `package:ffi`s `allocate<>()` leaves the memory uninitialized. This works just as if one calls `malloc()` in C code and is intentional. It makes memory allocation faster. If a user wants to 0-initialize the memory he can always use `<ptr>.asTypedList(...).setRange(0, <ptr>.length, 0)` (or something along those lines).

Closing this issue since this is working as intended.

**Closed by mkustermann** 2020-12-16 15:55 UTC
Labels: area-vm, library-ffi
