### ISSUE TITLE
Inconsistent errors for implicit Function-interface upcasts

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#36868] opened 2019-05-06 23:14 UTC
Snippet:
```
class C implements Function {}

main() {
  Function f = C();
}
```

Analyzer throws an error:
```
[error] A value of type 'C' can't be assigned to a variable of type 'Function'.
```

But CFE lets this pass.

Both frontends let this pattern pass if Function is substituted with some user-defined class. The spec states that `function objects are instances of some class that implement
Function`, so I'm led to believe this error is misplaced.

**Comment by eernstg** [comment] 2019-05-07 09:31
Note that `class C implements Function {}` literally has the same meaning as `class C {}`, cf. section ['Type Function'](https://github.com/dart-lang/language/blob/87bd63679a8233776f559d7ab4ed45a49456f5bb/specification/dartLangSpec.tex#L15195) in the spec.

This explains the behavior that you are reporting for the analyzer. The CFE may not detect this error, and this is an instance of the general principle that error reporting with the CFE is allowed to be implemented a bit later than that of the analyzer: We assume that all programs are checked using the analyzer.

This means that the analyzer is working as intended.

---

A few words about the background, considering the fact that it's a very unusual behavior to ignore `implements T` for any `T`:

A major reason for treating the class `Function` in this way (rather than making `implements Function` a compile-time error, and similarly for `extends Function` and `with Function`) was that it would be a significantly breaking change to introduce these errors. Moreover, `implements Function` was generally used in situations in a Dart 1 context where it had no effect (that is, when it was used on a class declaring a method named `call`).

However, classes implementing a method named `call` in Dart 2 do _not_ yield function objects, they just yield objects that have a method named `call`, and there are a few pieces of syntactic sugar (based on the static type) that will allow for such objects to be converted into actual function objects (by performing an implicit tear-off on that `call` method).

One important reason for doing this is that we avoid having recursive (infinite) function types in Dart 2. Another one is that a function object in Dart 2 can use a specialized mechanism for invocation (look up the address of the code, jump to that location) rather than using a regular instance method invocation (which could have one indirection to get to a vtable and then another one to jump to the code).

So it is a rather twisted corner of Dart, but still a mechanism which was intentionally made like that.

**Comment by eernstg** [comment] 2019-05-07 09:35
Found #35573 which is concerned with the missing error in the CFE. Closing this as a duplicate of that issue.

**Closed by eernstg** 2019-05-07 09:35 UTC
Labels: area-front-end, closed-duplicate
