### ISSUE TITLE
Code completion not working with Colors

### ISSUE THREAD

**Issue by harshvardhan** [dart-lang/sdk#35353] opened 2018-12-07 04:46 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1152x720`

# Exception

Please append the contents of:
file:///private/var/folders/md/21yws1r92fs8rh6gp9jjpz9m0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: /Users/harshvardhan/Documents/work/test/hello_rectangle/lib/main.dart context: exception_20181207_124457_442
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
#2      ConstantVisitor.visitSimpleIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1435:12)
#3      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9679:49)
#4      ConstantVisitor.visitPrefixedIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1381:49)
#5      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9033:49)
#6      ConstantEvaluationEngine.computeConstantValue (package:analyzer/src/dart/constant/evaluation.dart:203:14)
#7      _ConstantWalker.evaluate (package:analyzer/src/dart/analysis/library_analyzer.dart:761:22)
#8      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2199:13)
#9      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2218:18)
#10     LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:193:47)
#11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:7)

**Comment by stereotype441** [comment] 2018-12-12 17:21
Duplicate of #35241

**Closed by stereotype441** 2018-12-12 17:21 UTC
Labels: area-analyzer
