### ISSUE TITLE
Should migration update the language version in pubspec.yaml?

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40527] opened 2020-02-07 19:49 UTC
If I have a package, and I run the migration, I would _expect_ that once I apply the migration, NNBD is enabled for my package.

In reality, to enable NNBD for my package I need to

- update my pubspec constraint
- run pub

where running pub is a potentially destructive action.

Can we improve this experience for users?

Alternative options:
- update pubspec constraint
- update package_config.json
- _tell users_ to run pub

Or:
- detect if running pub will be destructive _before_ migrating, and abort

Part of the problem here is that changing the sdk constraint will change the package solve. So this may be the better solution, to make sure we migrate against the correct libs etc.:

- update pubspec constraint & run pub _before_ migrating (prompt confirmation?)
- reintroduce language_version to pre-nnbd state in package_config.json
- migrate
- revert package_config.json to NNBD version

Not sure if anyone has any brilliant magic wand solutions to the problem

**Comment by stereotype441** [comment] 2020-04-03 12:22
Duplicate of #38347

**Closed by stereotype441** 2020-04-03 12:22 UTC
Labels: NNBD, analyzer-nnbd-migration, area-analyzer
