### ISSUE TITLE
[DevCompiler] Optional named parameter ignored?

### ISSUE THREAD

**Issue by cedx** [dart-lang/sdk#34088] opened 2018-08-07 18:14 UTC
* Dart SDK Version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"
* `build_runner`: 0.10.0, `build_test`: 0.10.3, `build_web_compilers`: 0.4.1, `test`: 1.3.0
* OS: Windows 10 (64-bit)
* Test browser: Chrome 68
* Any other packages or constraints: `json_annotation`: 1.0.0, `json_serializable`: 1.0.1.

I have a project (https://github.com/cedx/lcov.dart) whose tests give different results when run by `dart2js` and the dev compiler:
https://github.com/dart-lang/build/issues/1724

A `FunctionData#toString({bool asDefinition = false})` method is called two times: with `asDefinition = true` and `asDefinition = false` (see: https://github.com/cedx/lcov.dart/blob/master/lib/src/function.dart#L33).

When the tests use the dev compiler, it looks like the optional named parameter `asDefinition` is ignored: its value always seems to be `false`.

**Comment by matanlurey** [comment] 2018-08-07 18:15
Duplicate of https://github.com/dart-lang/sdk/issues/33876

I believe it is fixed at HEAD but not in a release yet.

**Closed by matanlurey** 2018-08-07 18:15 UTC
Labels: closed-duplicate
