### ISSUE TITLE
Error 1001 received from application: File system already exists

### ISSUE THREAD

**Issue by dearlancer** [dart-lang/sdk#36063] opened 2019-02-28 08:57 UTC
Compiler message:
Warning: Tried to initialize from a previous compilation (build/app.dill), but couldn't.
Error message was 'RangeError (index): Index out of range: no indices are valid: 0'.
Stacktrace included '#0      Uint8List.[] (dart:typed_data/runtime/libtyped_data_patch.dart:2177:7)
#4      IncrementalCompiler.initializeFromDill 
package:front_end/…/fasta/incremental_compiler.dart:499
#8      CompilerContext.runInContext.<anonymous closure> 
package:front_end/…/fasta/compiler_context.dart:122
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:116:20)
<asynchronous suspension>
#15     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
<asynchronous suspension>
#16     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:339:67)
#17     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#18     _rootRun (dart:async/zone.dart:1120:38)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#26     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#27     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by a-siva** [comment] 2019-02-28 18:26
Can you add some comments about what you were doing when this error happened, in other words some instructions on how to reproduce this scenario.

**Comment by jensjoha** [comment] 2019-05-01 09:37
Thank you for reporting this.
This is caused by the file we try to initialize from being empty. This can happen if for instance launching several instances working on the same file (e.g. one instance is overwriting the file while the other is reading it). As long as it doesn't happen all the time it's nothing to worry about.
I recently landed d8739b5 to make sure we don't even try to load when the file is empty, and this warning will thus be avoided.

**Closed by jensjoha** 2019-05-01 09:37 UTC
Labels: area-front-end, area-vm
