### ISSUE TITLE
`type '(String?) => void' is not a subtype of type '((dynamic) => void)?'`

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/sdk#51461] opened 2023-02-19 02:25 UTC
Using the [`getwidget` library](https://pub.dev/packages/getwidget) v3.0.1, the following code compiles fine but causes a red screen exception at runtime:

```dart
GFDropdown(
  hint: const Text('Choose an item'),
  items: dropdownItems,
  onChanged: (newValue) {
    setState(() {
    });
  },
),
```

The exception is:

```
The following _TypeError was thrown building GFDropdown<String>(dirty, state: _GFDropdownState#948b2):
type '(String?) => void' is not a subtype of type '((dynamic) => void)?'
```

You have to add `dynamic` to prevent this exception:

```dart
GFDropdown(
  hint: const Text('Choose an item'),
  items: dropdownItems,
  onChanged: (dynamic newValue) {
    setState(() {
    });
  },
),
```

However, the compiler infers the type correctly as `String?`.

GFDropdown's `onChanged` parameter is declared as:

```dart
final ValueChanged<T?>? onChanged;
```

and `ValueChanged` is declared as:

```dart
typedef ValueChanged<T> = void Function(T value);
```

VSCode shows the inferred type of `onChanged` as: 

```dart
{required void Function(String?)? onChanged}
```

i.e. `(String?) => void`. The compiler is unable to reconcile this with `((dynamic) => void)?` at runtime, for some reason.

* Dart SDK Version (`dart --version`): Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "linux_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable): Linux
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable): Android emulator

**Comment by asashour** [comment] 2023-02-19 09:46
There is no runtime exception with me with the below (which is not a complete case I guess). It if works with you, then please send a complete case to reproduce.

`Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "windows_x64"`

```dart
import 'package:flutter/material.dart';
import 'package:getwidget/components/dropdown/gf_dropdown.dart';

void main() {
  GFDropdown(
    hint: const Text('Choose an item'),
    items: const [],
    onChanged: (newValue) {},
  );
}
```

**Comment by lukehutch** [comment] 2023-02-19 10:14
Looks like you need a little more to repro, sorry!

```dart
import 'package:flutter/material.dart';
import 'package:getwidget/components/dropdown/gf_dropdown.dart';

void main() async {
  runApp(
    MaterialApp(
      home: SafeArea(
        child: GFDropdown(
          items: const [
            DropdownMenuItem(
              value: 'x',
              child: Text('X'),
            )
          ],
          onChanged: (newValue) {},  // add `dynamic` here to fix 
        ),
      ),
    ),
  );
```

**Comment by lukehutch** [comment] 2023-02-19 10:20
The type of `DropdownMenuItem<T>` is apparently inferred from the type of `value: 'x'` to be `T = String`, and that is supposed to constrain the type of `onChanged` to `(String?) => void`.

**Comment by lrhn** [comment] 2023-02-19 11:42
I'm not able to reproduce this easily. 
Copying the  current version of GFDropdown from the repo (https://github.com/ionicfirebaseapp/getwidget/blob/master/lib/components/dropdown/gf_dropdown.dart) and putting it together with your code in DartPad, infers `Object?` as argument type for the `onChange` callback.

I modified the code to print the runtime and static type:
```dart
void main() async {
  runApp(
    MaterialApp(
      home: SafeArea(
        child: GFDropdown(
          items: const [
            DropdownMenuItem(
              value: 'x',
              child: Text('X'),
            )
          ]..log,
          onChanged: (newValue){  // add `dynamic` here to fix
            print(newValue);
          }
            ..log,
        )..log,
      ),
    ),
  );
}

extension<T> on T {
  T get log {
    print("$this:$runtimeType @ $T");
    return this;
  }
}
```

Could you be using an older version of `getwidget` which has a bug?

**Comment by asashour** [comment] 2023-02-19 11:56
I am able to reproduce it with `master` and `stable` Flutter, using a project with getwidget: `3.0.1` dependency.

**Comment by lrhn** [comment] 2023-02-19 12:05
Seems to be a known issue to be fixed in the next release:
https://github.com/ionicfirebaseapp/getwidget/issues/304#issuecomment-1331751453

**Comment by lukehutch** [comment] 2023-02-19 15:34
It may be an issue with GFDropdown, yes, because the other widgets in the library do not have this issue. But I'm more concerned about whether this illustrates a Dart issue that has to be avoided. The error does not make any sense, especially at runtime only. Where is the assertion failing?

**Comment by lukehutch** [comment] 2023-02-19 16:57
Weirdly I can't replicate this with your `log` extension, only without it, making this a Heisenbug...

**Comment by lukehutch** [comment] 2023-02-19 17:49
The line that throws the assertion error is marked with `// (*)` below. The assertion is happening at the language level at runtime, on assignment -- it's not an assertion in the library.

```dart
class _GFDropdownState extends State<GFDropdown> {
  @override
  Widget build(BuildContext context) => Material(
        color: widget.dropdownButtonColor,
        shape: RoundedRectangleBorder(
          side: widget.border,
          borderRadius: widget.borderRadius,
        ),
        child: Container(
          height: widget.itemHeight,
          padding: widget.padding,
          child: DropdownButton(
            items: widget.items,
            selectedItemBuilder: widget.selectedItemBuilder,
            value: widget.value,
            hint: widget.hint,
            disabledHint: widget.disabledHint,
            onChanged: widget.onChanged,         // (*)
            onTap: widget.onTap,
            elevation: widget.elevation,
            style: widget.style,
            icon: widget.icon,
            iconDisabledColor: widget.iconDisabledColor,
            iconEnabledColor: widget.iconEnabledColor,
            iconSize: widget.iconSize,
            isDense: widget.isDense,
            isExpanded: widget.isExpanded,
            // itemHeight: widget.itemHeight,
            focusColor: widget.focusColor,
            focusNode: widget.focusNode,
            autofocus: widget.autofocus,
            dropdownColor: widget.dropdownColor,
          ),
        ),
      );
}
```

Adding `value: 'x',` to the `GFDropdown` constructor params in `main` (so that `value` is not null) does not solve the problem.

For `widget`, the debugger gives the following types before this line is hit (these are the only two fields of `GFDropdown<T>` that have a type based on the generic type `T`, specifically `T? value` and `ValueChanged<T?>? onChanged`, which resolves to `void Function(T? value)? onChanged`):

```
widget: GFDropdown<String>
widget.value: String
widget.onChanged: Closure: (String?) => void
```

All the types of `widget` and its field look correct in the debugger. 

However, the type of `DropdownButton` is resolved as `DropdownButton<dynamic>`.

Interestingly if you simply add type parameter `<T>` in three places as follows:

```
class _GFDropdownState<T> extends State<GFDropdown<T>> {
  // ...
        child: DropdownButton<T>(
```

then the assertion failure is triggered in the construction of `GFDropdown`, not the construction of `DropdownButton`!

Here is a complete minimal reproducer:

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    MaterialApp(
      home: SafeArea(
        child: GFDropdown(
          value: 'x',
          items: const [
            DropdownMenuItem(
              value: 'x',
              child: Text('X'),
            )
          ],
          onChanged: (newValue) {}, // add `dynamic` here to fix
        ),
      ),
    ),
  );
}

class GFDropdown<T> extends StatefulWidget {
  const GFDropdown(
      {Key? key, required this.items, this.value, required this.onChanged})
      : super(key: key);
  final List<DropdownMenuItem<T>>? items;
  final T? value;
  final ValueChanged<T?>? onChanged;

  @override
  State<GFDropdown> createState() => _GFDropdownState();
}

class _GFDropdownState extends State<GFDropdown> {
  @override
  Widget build(BuildContext context) => Material(
        child: DropdownButton(
          value: widget.value,
          onChanged: widget.onChanged,
          items: widget.items,
        ),
      );
}

class DropdownButton<T> extends StatefulWidget {
  const DropdownButton({
    super.key,
    required this.items,
    this.value,
    required this.onChanged,
  });
  final List<DropdownMenuItem<T>>? items;
  final T? value;
  final ValueChanged<T?>? onChanged;

  @override
  State<DropdownButton<T>> createState() => _DropdownButtonState<T>();
}

class _DropdownButtonState<T> extends State<DropdownButton<T>> {
  @override
  Widget build(BuildContext context) {
        return const Text('Success');
  }
}
```

The solution is to change

```dart
class GFDropdown<T> extends StatefulWidget {
  // ...
  _GFDropdownState createState() => _GFDropdownState();
}

class _GFDropdownState extends State<GFDropdown> {
  // ...
}
```

to

```dart
class GFDropdown<T> extends StatefulWidget {
   // ...
  State<GFDropdown<T>> createState() => _GFDropdownState();   // Specify type parameter
}

class _GFDropdownState<T> extends State<GFDropdown<T>> {   // Specify type parameter twice
  // ...
}
```

This is definitely a language issue, not a library issue:
* The type inference engine is giving up too early and defaulting to `dynamic`, forcing a runtime typecheck.
* The runtime type checker doesn't seem to be able to agree that `String` is assignable to `dynamic` as a type parameter, in this scenario (although I don't have a good understanding of how `dynamic` is handled in general).

**Comment by lukehutch** [comment] 2023-02-19 17:58
Actually based on the fix, I can see how `_GFDropdownState` has no compiletime type information whatsoever made available to it by the call `_GFDropdownState createState() => _GFDropdownState();`, so I see how type resolution has to be punted to runtime.

So obviously `T1 == dynamic` for `value` can't necessarily be matched with `T2 == dynamic` for `void Function(dynamic?)? onChanged`, if compile-time types alone are used. However, at runtime, which are `T1` and `T2` not found to be the same type? Or am I misunderstanding the problem?

**Comment by mraleph** [comment] 2023-02-20 09:02
> However, at runtime, which are `T1` and `T2` not found to be the same type? Or am I misunderstanding the problem?

I am not sure what exactly you mean by this. Ultimately the code in question is trying to do the following:

```dart
void Function(dynamic) foo = (String? bar) { };
``` 

Which does not work for obvious reasons: a function that expects specifically a `String?` can't be used in the places where a function which can handle anything (`dynamic`) is expected.

The type on the left hand side arises because `T` is not properly passed down through the state object so types are instantiated to their bounds, meaning that `State<GFDropdown>` means `State<GFDropdown<dynamic>>` and `DropdownButton(...)` means `DropdownButton<dynamic>(...)`. There is simply no context in any of these to infer a better 
`T` from. 

Note: there is also some subtlety around covariance of generics and function types, but it does not really come into play here. Imagine you have a class:

```dart
class Foo<T> {
  void Function(T?) cb;

  Foo(this.cb);
}
```

The following code is correct in compile time due to covariance:

```dart
Foo<dynamic> foo = Foo((String v) { });
// ...
foo.cb(1);
```

However it would be unsound to allow calling `cb` with an integer value. So compiler will actually compile this code with an additional check:

```
(foo.cb as void Function(dynamic))(1);
```

which would throw if `cb` does not take `dynamic`.

**Closed by mraleph** 2023-02-20 09:02 UTC

**Comment by lukehutch** [comment] 2023-02-20 16:42
OK, thanks for explaining, that's very helpful. I see that the problem is in the code and not in the compiler. But it leaves me wondering why this situation is not being caught statically. Is there any additional check that could be put in place to catch this issue at compiletime?

**Comment by mraleph** [comment] 2023-02-21 08:19
I think [`strict-raw-types`](https://github.com/dart-lang/language/blob/master/resources/type-system/strict-raw-types.md) would have caught it - but that requires `getwidget` developers to enable it.
