### ISSUE TITLE
dart fix only applying partial fixes

### ISSUE THREAD

**Issue by Piinks** [dart-lang/sdk#45439] opened 2021-03-23 23:53 UTC
Reference:
https://github.com/flutter/flutter/pull/78897

There is a large conditional rule written in that PR, and it does not fully work as expected. 
If I take away the `removeParameter` of `useTextSelectionTheme`, then the rule performs a bit better, which is.. perplexing.
That PR has the before and after code snippets that the rule is not transforming correctly, the failing tests should show what the result currently is.

Already chatting with @bwilkerson, filing this issue for reference and follow-up. :)

**Comment by bwilkerson** [comment] 2021-03-24 18:25
Status update: The good news is that I have been able to reproduce the failure by applying the PR to the latest version of the flutter repo. I have not yet reproduced it in an environment where I can debug it, but I am actively working on doing so.

I have to say that the output from running the tests leaves something to be desired. :-(

**Comment by Piinks** [comment] 2021-03-24 18:40
Thank you! 🎉 

> I have to say that the output from running the tests leaves something to be desired. :-(

Yeah, I don't mind it terribly, I know a lot of folks have different style preferences. Is it possible the run dartfmt at the end of applying a fix? Would that improve the output?

**Comment by bwilkerson** [comment] 2021-03-24 18:46
I was referring to the dump of expected vs actual (without a diff) and the dump of the edits passed back from server. They aren't very helpful in terms of figuring out why the edits weren't generated in the first place (the bug we're currently looking at).

The resulting code is also not always as well formatted as it should be, but that's a harder problem for the reason you pointed out: everyone has their own formatting preferences.

**Comment by bwilkerson** [comment] 2021-03-24 22:38
I have figured out the cause of at least one failure, and I expect the others are similar in nature. The code is attempting to insert the new argument into the argument list, then attempting to delete everything between the parentheses (because we're deleting all of the existing arguments and don't want to leave unnecessary whitespace around). Because these two ranges overlap it then throws away both of the edits in order to prevent any corruption of the user's code. I have a fix for that case, but it doesn't fix the other cases so I need to do more digging.

**Comment by bwilkerson** [comment] 2021-03-30 04:17
I believe that this should now be fixed by https://dart-review.googlesource.com/c/sdk/+/193444.

**Closed by bwilkerson** 2021-03-30 04:17 UTC
Labels: P2, analyzer-dartfix, area-analyzer
