### ISSUE TITLE
Comparing enums sent through redirecting const constructors marked as throwing

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#37171] opened 2019-06-05 22:13 UTC
Reproduced in both 2.3.0 and 2.3.1. Only affects the Analyzer, CFE runs this fine.

```dart
enum Bar {
  qux,
}

class Foo {
  final int bar;
  const Foo._(int bar, Bar b) : bar = bar | (b == Bar.qux ? 2 : 1);
  const Foo({int bar: 8, Bar b: Bar.qux}) : this._(bar, b);
}

const foo = const Foo(bar: 5); // Error here, "Evaluation of this constant expression throws an exception."
```

**Comment by ds84182** [comment] 2019-06-05 22:14
Using `identical` instead of `operator==` seems to fix the issue in the analyzer.

**Comment by lrhn** [comment] 2019-06-06 08:46
This is the current expected behavior: `==` in constant expressions is restricted to basic types, and enums are not included in those. 
You have to use `identical`.

**Comment by devoncarew** [comment] 2019-06-06 20:32
Thanks for the report! Closing as working as intended. @stereotype441 to confirm and re-open if we believe this is an issue

**Closed by devoncarew** 2019-06-06 20:32 UTC
