### ISSUE TITLE
fasta converts CR LF to LF in file dominated by LF line endings

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#30909] opened 2017-09-27 19:43 UTC
This test fails because CR LF handling in fasta is different to dart2js/ast:

tools/test.py -m release -c dart2js -r d8 --host-checked --dart2js-batch --dart2js-options "--library-root=out/ReleaseX64/dart-sdk/ --use-kernel" dart2js_extra/string_interpolation_dynamic_test

I'm not sure what the right behaviour is, but it feels wrong to change the contents of string literals.

**Comment by peter-ahe-google** [comment] 2017-09-28 10:39
Duplicate of #23562.

**Comment by peter-ahe-google** [comment] 2017-09-28 10:40
Notice that dart2js fails tests/language/multiline_newline_test.dart and that Fasta has been shooting for parity with the Dart VM.

**Comment by jensjoha** [comment] 2018-01-11 14:01
https://github.com/dart-lang/sdk/blob/38dcb10543c1446c3b4c710d4eadef2e4c002e69/tests/compiler/dart2js_extra/string_interpolation_dynamic_test.dart#L64

From how I read https://github.com/dart-lang/sdk/issues/23562#issuecomment-332811222 it seems that the test is wrong and that fasta does the right thing.

Any objections to closing this issue?

**Comment by lrhn** [comment] 2018-01-11 15:44
Jens is correct, and so is Fasta.

The specification was updated in ef31637857d03adc302c821 to say what newlines mean in multiline strings - and what *lines* are, for that matter. 

With that change, a CR+LF sequence in a multiline string literal only introduces one LF (U+000A) character in the resulting string, and so does a single CR. That makes the semantics of Dart programs independent of, e.g., your git `autocrlf` or `eol` settings.

**Comment by peter-ahe-google** [comment] 2018-01-11 15:56
\o/

**Closed by peter-ahe-google** 2018-01-11 15:56 UTC
Labels: Resolution: duplicate, area-front-end, front-end-fasta
