### ISSUE TITLE
El codigo se ofusco 

### ISSUE THREAD

**Issue by jrsantur** [dart-lang/sdk#38262] opened 2019-09-09 03:44 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768, 1360x768`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: NoSuchMethodError: The setter 'previous=' was called on null.
Receiver: null
Tried calling: previous=Instance of 'StringToken'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:615:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\Junior\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment] 2019-09-19 15:36
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37096; please follow along there.

**Comment by srawlins** [comment] 2019-09-19 15:36
Duplicate of https://github.com/dart-lang/sdk/issues/37096

**Closed by srawlins** 2019-09-19 15:36 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
