### ISSUE TITLE
[cfe] Malbounded type involving type alias with invariant type parameter not reported

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#44786] opened 2021-01-27 09:35 UTC
Dart SDK version: 2.12.0-242.0.dev (dev) (Mon Jan 18 18:26:11 2021 -0800) on "windows_x64"
This is a regression which is not reproducible with the previous dev release.

Here is a source code example:
``` dart
typedef G<X> = X Function(X);
class A<X extends G<A<X>>> {}

Type typeOf<X>() => X;

main() {
  typeOf<A<G<A<dynamic>>>>();
}
```

Analyzer passes OK here whereas Dart throws a compile time error.

Seems like both tools should pass.

Sample output is:
> $> dartanalyzer test.dart
> Analyzing test.dart...
> No issues found!
> 
> $> dart test.dart
> test.dart:7:3: Error: Type argument 'A<dynamic> Function(A<dynamic>)' doesn't conform to the bound 'A<X> Function(A<X>)' of the type variable 'X' on 'A'.
>  - 'A' is from 'test.dart'.
> Try changing type arguments so that they conform to the bounds.
>   typeOf<A<G<A<dynamic>>>>();
>   ^
> test.dart:2:9: Context: This is the type variable whose bound isn't conformed to.
> class A<X extends G<A<X>>> {}
>         ^
> test.dart:7:3: Context: If you want 'A<A<dynamic> Function(A<dynamic>)>' to be a super-bounded type, note that the inverted type 'A<G<A<Never>>>' must then satisfy its bounds, which it does not.
>  - 'A' is from 'test.dart'.
>   typeOf<A<G<A<dynamic>>>>();
>   ^

**Comment by iarkh** [comment] 2021-01-27 10:00
Here is a similar example which also passes with analyzer and fails with dart:
``` dart
typedef G<X> = X Function(X);
class A<X extends G<A<X>>> {}

main() {
  A? source;
}
```
Seems like the reason of the failure is the same as in the original Description above.
Is this OK or I should file another issue here?

**Comment by keertip** [comment] 2021-01-27 14:49
@iarkh , in the previous dev release the above above did not cause a compile error, is that right?

**Comment by johnniwinther** [comment] 2021-01-27 14:59
cc @eernstg @stefantsov

**Comment by iarkh** [comment] 2021-01-27 17:21
> @iarkh , in the previous dev release the above above did not cause a compile error, is that right?
I tried the following and it passes for me:
Dart SDK version: 2.12.0-198.0.dev (dev) (Wed Jan 6 19:35:49 2021 -0800) on "windows_x64"

**Comment by eernstg** [comment] 2021-01-27 18:44
The common front end is right.

The error message looks confusing, but that is because github markdown processing removes type argument lists and turns `A<dynamic> Function(A<dynamic>)` as well as `A<X> Function(A<X>)` into `A Function(A)`. It's better to use code (backquoted or triple-backquoted text) to show error messages like this.

The point is exactly as stated by the error message:

```
n021.dart:7:3: Error: Type argument 'A<dynamic> Function(A<dynamic>)' doesn't conform to the bound 'A<X> Function(A<X>)' of the type variable 'X' on 'A'.
 - 'A' is from 'n021.dart'.
Try changing type arguments so that they conform to the bounds.
  typeOf<A<G<A<dynamic>>>>();
  ^
n021.dart:2:9: Context: This is the type variable whose bound isn't conformed to.
class A<X extends G<A<X>>> {}
        ^
n021.dart:7:3: Context: If you want 'A<A<dynamic> Function(A<dynamic>)>' to be a super-bounded type, note that the inverted type 'A<G<A<Never>>>' must then satisfy its bounds, which it does not.
 - 'A' is from 'n021.dart'.
  typeOf<A<G<A<dynamic>>>>();
  ^
```

The reason why `A<G<A<Never>>>` isn't regular-bunded (where `<:>` means that we must have both `<:` and `:>`):

```dart
A<G<A<Never>>> // is regular-bounded if
G<A<Never>> <: G<A<G<A<Never>>>> // which requires
A<Never> <:> A<G<A<Never>>> // which requires
Never <:> G<A<Never>> == A<Never> Function(A<Never>) // which isn't true.
```

So we should adjust this to be an analyzer issue, because the error is not reported. Adjusting the labels and title accordingly.

**Comment by iarkh** [comment] 2021-02-20 08:37
In the recent dev release (Dart SDK version: 2.13.0-48.0.dev (dev) (Wed Feb 17 19:36:03 2021 -0800) on "windows_x64") I am observing opposite result: now analyzer throws a compile error with the test example above whereas dart passes without errors or warnings.

So which behavior is correct?

**Comment by eernstg** [comment] 2021-02-20 10:03
Nothing changed in the analysis of the situation: The correct behavior is to emit an error because `A<G<A<dynamic>>>` is a malbounded type.

But I can also reproduce the response: The analyzer reports this error, but the CFE fails to report it, with tools from d10d17cca28fe0968d2ba645a08f3d2832272385. So we'll need to re-label the issue again. ;)

@stefantsov, does this ring a bell, how could the CFE error message disappear between 2.12.0-237.0.dev and 2.13.0-48.0.dev?

**Comment by iarkh** [comment] 2021-09-15 15:10
Seems like it will be fixed after  https://dart-review.googlesource.com/c/sdk/+/212290 implementation. 

See also https://github.com/dart-lang/co19/issues/1189

In current dev release (2.15.0-101.0.dev) dart correctly throws 3 compile errors (lines 4, 7 and 8) for the following test example:
``` dart
class A<X> {}
typedef G<X extends A<X>, Y extends A<Y>> = X Function(Y);

test(G g) {}

main() {
  G? source;
  print(G == int);
}
```
At the same time, analyzer throws only 2 (for lines 4, 7) and does not throw a error for the line 8.

**Comment by eernstg** [comment] 2021-09-24 23:33
The current behavior indicates that the analyzer fails to detect that `G` in line 8 is not well-bounded, but the CFE does detect all three errors. I adjusted the labels accordingly.

@scheglov, it looks like the analyzer checks the well-boundedness of the type annotations, but it forgets to check the type literal in line 8?

**Comment by eernstg** [comment] 2021-09-28 09:14
I'm closing this: I just noticed that the remaining issue with the analyzer is exactly the issue which has been reported as https://github.com/dart-lang/sdk/issues/47276. #47276 addresses the situation directly, and it was reported for `area-analyzer` originally, so I believe it's best to consider this issue as a duplicate of #47276 even though this issue is older.

**Closed by eernstg** 2021-09-28 09:14 UTC
Labels: area-analyzer, closed-duplicate, analyzer-spec
