### ISSUE TITLE
encoding error 

### ISSUE THREAD

**Issue by omaramin9696** [dart-lang/sdk#40890] opened 2020-03-05 14:32 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6200805`
- `2.7.0-dev.2.1`
- `AI-192.7142.36.36.6200805, JRE 1.8.0_212-release-1586-b04x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, FATAL error: UnimplementedError: Encoding "null"
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\omar\AppData\Local\Temp\report.txt.

**Comment by omaramin9696** [comment] 2020-03-06 20:51
flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.10240],
    locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\omar\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23)
      (emulator)

• No issues found!

**Comment by srawlins** [comment] 2020-06-14 22:20
Thanks for opening this issue! It looks like this was previously reported at https://github.com/dart-lang/sdk/issues/37641; please follow along there.

**Comment by srawlins** [comment] 2020-06-14 22:20
Duplicate of #37641

**Closed by srawlins** 2020-06-14 22:20 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
