### ISSUE TITLE
Dart analyzer misses compile time type error

### ISSUE THREAD

**Issue by ristiisa** [dart-lang/sdk#43045] opened 2020-08-14 07:31 UTC
The following code should produce compile time error but still fails at run time:
```
void main() {
  int i = true ? "1.0" : 0;
  print(i);
}
```

this is not a duplicate of #25368 since no strong mode is used.

`Dart SDK version: 2.9.0-21.0.dev.flutter-20bf2fcf56 (be) (Tue Jul 14 09:46:23 2020 +0000) on "macos_x64"`

**Comment by eernstg** [comment] 2020-08-14 07:39
It is actually a duplicate of #25368. I'm not quite sure what you mean by strong mode. Before Dart 2 it was a way to enable Dart2-ish type checking, which is more strict than Dart 1 type checking; recently, it has been used to denote the execution of programs with null safety in the sound (and strict) mode where no legacy code can occur in the whole program.

In any case, the issue is that there is an upcast for `"1.0"` and for `0` because the type of the conditional expression `true ? "1.0" : 0` is `Object`, and then there's an implicit downcast to `int`. With null safety (and with '--no-implicit-casts`), you will get the compile-time error.

**Closed by eernstg** 2020-08-14 07:39 UTC
Labels: closed-duplicate
