### ISSUE TITLE
Dart Analyzer Error: Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by yumi0629** [dart-lang/sdk#34786] opened 2018-10-15 01:17 UTC
I have restarted my Mac, but it still doesn't work.
Here is the log: 

Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.2 unknown, screens 1680x1050, 2560x1440  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/fq/wx3zkflx7bz36fz3f3bpx5wh0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/yumi/Documents/yumi/demo/flutter/flutter_slide_drawer/lib/main.dart
Exception: Element not found in summary: package:flutter/src/material/scaffold.dart

**Comment by MichaelRFairhurst** [comment] 2018-10-17 17:09
Possible duplicate of #34716 

> I have restarted my Mac, but it still doesn't work

Hmm, this may be a bigger issue than we realized if its the same one we've seen before.

You should be able to fix your workspace with `rm -rf ~/.dartServer/.analysis-driver/` and then restarting analysis inside intelliJ.

Can you give us any details about what caused this, for instance, maybe a `flutter upgrade`?

@scheglov

**Comment by scheglov** [comment] 2018-10-17 17:14
Probably https://github.com/dart-lang/sdk/issues/34823
Mike is right, removing `.analysis-driver/` should help.

**Closed by scheglov** 2018-10-17 17:14 UTC
Labels: area-analyzer, crash, needs-info

**Comment by ashokbasnet** [comment] 2019-04-01 16:33
> Possible duplicate of #34716
> 
> > I have restarted my Mac, but it still doesn't work
> 
> Hmm, this may be a bigger issue than we realized if its the same one we've seen before.
> 
> You should be able to fix your workspace with `rm -rf ~/.dartServer/.analysis-driver/` and then restarting analysis inside intelliJ.
> 
> Can you give us any details about what caused this, for instance, maybe a `flutter upgrade`?
> 
> @scheglov



> Possible duplicate of #34716
> 
> > I have restarted my Mac, but it still doesn't work
> 
> Hmm, this may be a bigger issue than we realized if its the same one we've seen before.
> 
> You should be able to fix your workspace with `rm -rf ~/.dartServer/.analysis-driver/` and then restarting analysis inside intelliJ.
> 
> Can you give us any details about what caused this, for instance, maybe a `flutter upgrade`?
> 
> @scheglov

This made my day. Thank you @MichaelRFairhurs.

**Comment by gisborne** [comment] 2021-03-27 23:50
I tried the rm -rf ~/.dartServer/.analysis-driver/ advice above and it has made no difference.
