### ISSUE TITLE
buildtools/clang_format not python3 compatible. Breaks git cl format and offsets_extractor

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#41317] opened 2020-04-03 08:32 UTC
The script `buildtools/clang_format/script/clang-format-diff.py` is not python 3 compatible, causing issues like:
```
  File "/.../src/dart/sdk/buildtools/clang_format/script/clang-format-diff.py", line 94
    print 'Formatting', filename
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Formatting', filename)?
```

This in turn affects both `git cl format` and `./tools/run_offsets_extractor.sh`, causing them to crash.

Either we need run this script with python2, or it needs to be updated.

**Comment by athomas** [comment] 2020-04-03 08:39
Duplicate of: https://crbug.com/1066187

**Closed by athomas** 2020-04-03 08:39 UTC
Labels: area-build, crash, type-bug
