### ISSUE TITLE
Unhandled &&= in handleAssignment

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31153] opened 2017-10-19 10:48 UTC
Crash in fasta
@peter-ahe-google
id: 041230e710e1a90385547bc429d4e653d26770a6

```
org-dartlang-bulkcompile:///main.dart:7:11: Internal problem: Unhandled &&= in handleAssignment.
  isValid &&= false;
          ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      DelayedAssignment.handleAssignment (package:front_end/src/fasta/kernel/body_builder.dart:3638:14)
#3      DelayedAssignment.buildForEffect (package:front_end/src/fasta/kernel/body_builder.dart:3590:12)
#4      BodyBuilder.toEffect (package:front_end/src/fasta/kernel/body_builder.dart:239:44)
#5      BodyBuilder.popForEffect (package:front_end/src/fasta/kernel/body_builder.dart:216:32)
#6      BodyBuilder.endExpressionStatement (package:front_end/src/fasta/kernel/body_builder.dart:687:40)
#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3487:14)
#8      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1924:16)
#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:3447:12)
#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3346:14)
#11     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3338:20)
#12     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3262:15)
#13     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:621:14)
#14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:493:5)
#15     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:231:5)
#16     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2348:14)
#17     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2256:11)
#18     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:335:14)
#19     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:282:15)
#20     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:176:14)
<asynchronous suspension>
#21     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#22     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:290:20)
<asynchronous suspension>
#23     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#24     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:51:37)
<asynchronous suspension>
#25     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#26     _rootRun (dart:async/zone.dart:1124)
#27     _CustomZone.run (dart:async/zone.dart:1021)
#28     runZoned (dart:async/zone.dart:1499)
#29     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#30     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#31     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#32     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:60:27)
<asynchronous suspension>
#33     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:39:9)
<asynchronous suspension>
#34     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:112:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment] 2017-10-19 11:27
Duplicate of #30340.

**Closed by peter-ahe-google** 2017-10-19 11:27 UTC
Labels: area-front-end, front-end-fasta, Resolution: duplicate
