### ISSUE TITLE
dart error

### ISSUE THREAD

**Issue by weatherfish** [dart-lang/sdk#36322] opened 2019-03-23 12:33 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5314842`
- `2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec`
- `AI-182.5107.16.33.5314842, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3 unknown, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.571ea80e1101e706980ea8aefa7fc18a0c8ba2ec, server version 1.24.0, error: Analysis failed: /Users/weatherfish/OtherWork/live/live_app/test/widget_test.dart context: exception_20190323_203242_704
Bad state: Too many elements
#0      List.single (dart:core/runtime/lib/growable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2532:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5292:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5142:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5568:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5127:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1646:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3816:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3522:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3462:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2223:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2189:24)
#19     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2242:18)
#20     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3495:42)
#21     Linker.link (package:analyzer/src/summary/link.dart:4018:35)
#22     _relink (package:analyzer/src/summary/link.dart:305:57)
#23     link (package:analyzer/src/summary/link.dart:123:3)
#24     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#26     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#27     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#28     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#29     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#30     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#31     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#32     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#33     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#34     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#35     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#36     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#37     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#38     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:511:21)
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:594:12)
#44     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:509:7)
#45     Driver.start (package:analysis_server/src/server/driver.dart:412:7)
#46     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#47     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#48     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#49     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/26/bxvyy0q52wbggpksb6w5xtyh0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-04-08 16:44
Duplicate of #36273.

**Comment by devoncarew** [comment] 2019-04-30 15:09
dupe of https://github.com/dart-lang/sdk/issues/36767

**Closed by devoncarew** 2019-04-30 15:09 UTC
Labels: area-analyzer
