### ISSUE TITLE
Range error in FixContributor

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#25677] opened 2016-02-04 12:17 UTC
v 1.14.0-dev.7.2
```
2016-02-04T11:51:32.919: Common stack: Count: 187
Session: 1453931717921.1638
Exception from fix contributor:: DefaultFixContributor
RangeError:: Index:: 2, Size:: 2
#0      NodeList.[] (package::analyzer/src/generated/ast.dart::12758)
#1      FixProcessor._addFix_addMissingParameter (package::analysis_server/src/services/correction/fix_internal.dart::372)
#2      FixProcessor.compute (package::analysis_server/src/services/correction/fix_internal.dart::212)
#3      DefaultFixContributor.internalComputeFixes (package::analysis_server/src/services/correction/fix_internal.dart::52)
#4      DartFixContributor.computeFixes (package::analysis_server/plugin/edit/fix/fix_dart.dart::37)
#5      computeFixes (package::analysis_server/src/services/correction/fix.dart::27)
#6      EditDomainHandler.getFixes (package::analysis_server/src/edit/edit_domain.dart::164)
#7      EditDomainHandler.handleRequest (package::analysis_server/src/edit/edit_domain.dart::195)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package::analysis_server/src/analysis_server.dart::685)
#9      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#10     AnalysisServer.handleRequest.<anonymous closure> (package::analysis_server/src/analysis_server.dart::681)
#11     _rootRun (dart::async/zone.dart::907)
#12     _CustomZone.run (dart::async/zone.dart::802)
#13     _CustomZone.runGuarded (dart::async/zone.dart::708)
#14     runZoned (dart::async/zone.dart::1243)
#15     AnalysisServer.handleRequest (package::analysis_server/src/analysis_server.dart::680)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::169)
#17     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#18     ByteStreamServerChannel._readRequest (package::analysis_server/src/channel/byte_stream_channel.dart::160)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::109)
#20     _rootRunUnary (dart::async/zone.dart::914)
#21     _CustomZone.runUnary (dart::async/zone.dart::810)
#22     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#23     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#24     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#25     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#26     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#27     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#28     _LineSplitterSink._addLines (dart::convert/line_splitter.dart::127)
#29     _LineSplitterSink.addSlice (dart::convert/line_splitter.dart::102)
#30     StringConversionSinkMixin.add (dart::convert/string_conversion.dart::180)
#31     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#32     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#33     _rootRunUnary (dart::async/zone.dart::914)
#34     _CustomZone.runUnary (dart::async/zone.dart::810)
#35     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#36     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#37     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#38     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#39     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#40     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#41     _StringAdapterSink.addSlice (dart::convert/string_conversion.dart::260)
#42     _Utf8ConversionSink.addSlice (dart::convert/string_conversion.dart::336)
#43     _Utf8ConversionSink.add (dart::convert/string_conversion.dart::329)
#44     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#45     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#46     _rootRunUnary (dart::async/zone.dart::914)
#47     _CustomZone.runUnary (dart::async/zone.dart::810)
#48     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#49     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#50     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#52     _StreamController._add (dart::async/stream_controller.dart::616)
#53     _StreamController.add (dart::async/stream_controller.dart::562)
#54     _Socket._onData (dart::io-patch/socket_patch.dart::1646)
#55     _rootRunUnary (dart::async/zone.dart::918)
#56     _CustomZone.runUnary (dart::async/zone.dart::810)
#57     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#58     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#59     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#61     _StreamController._add (dart::async/stream_controller.dart::616)
#62     _StreamController.add (dart::async/stream_controller.dart::562)
#63     _RawSocket._RawSocket.<anonymous closure> (dart::io-patch/socket_patch.dart::1215)
#64     _NativeSocket.issueReadEvent.issue (dart::io-patch/socket_patch.dart::749)
#65     _microtaskLoop (dart::async/schedule_microtask.dart::43)
#66     _microtaskLoopEntry (dart::async/schedule_microtask.dart::52)
#67     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::96)
#68     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::149)

","stackTrace"::"#0      NodeList.[] (package::analyzer/src/generated/ast.dart::12758)
#1      FixProcessor._addFix_addMissingParameter (package::analysis_server/src/services/correction/fix_internal.dart::372)
#2      FixProcessor.compute (package::analysis_server/src/services/correction/fix_internal.dart::212)
#3      DefaultFixContributor.internalComputeFixes (package::analysis_server/src/services/correction/fix_internal.dart::52)
#4      DartFixContributor.computeFixes (package::analysis_server/plugin/edit/fix/fix_dart.dart::37)
#5      computeFixes (package::analysis_server/src/services/correction/fix.dart::27)
#6      EditDomainHandler.getFixes (package::analysis_server/src/edit/edit_domain.dart::164)
#7      EditDomainHandler.handleRequest (package::analysis_server/src/edit/edit_domain.dart::195)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package::analysis_server/src/analysis_server.dart::685)
#9      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#10     AnalysisServer.handleRequest.<anonymous closure> (package::analysis_server/src/analysis_server.dart::681)
#11     _rootRun (dart::async/zone.dart::907)
#12     _CustomZone.run (dart::async/zone.dart::802)
#13     _CustomZone.runGuarded (dart::async/zone.dart::708)
#14     runZoned (dart::async/zone.dart::1243)
#15     AnalysisServer.handleRequest (package::analysis_server/src/analysis_server.dart::680)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::169)
#17     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#18     ByteStreamServerChannel._readRequest (package::analysis_server/src/channel/byte_stream_channel.dart::160)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::109)
#20     _rootRunUnary (dart::async/zone.dart::914)
#21     _CustomZone.runUnary (dart::async/zone.dart::810)
#22     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#23     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#24     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#25     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#26     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#27     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#28     _LineSplitterSink._addLines (dart::convert/line_splitter.dart::127)
#29     _LineSplitterSink.addSlice (dart::convert/line_splitter.dart::102)
#30     StringConversionSinkMixin.add (dart::convert/string_conversion.dart::180)
#31     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#32     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#33     _rootRunUnary (dart::async/zone.dart::914)
#34     _CustomZone.runUnary (dart::async/zone.dart::810)
#35     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#36     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#37     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#38     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#39     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#40     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#41     _StringAdapterSink.addSlice (dart::convert/string_conversion.dart::260)
#42     _Utf8ConversionSink.addSlice (dart::convert/string_conversion.dart::336)
#43     _Utf8ConversionSink.add (dart::convert/string_conversion.dart::329)
#44     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#45     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#46     _rootRunUnary (dart::async/zone.dart::914)
#47     _CustomZone.runUnary (dart::async/zone.dart::810)
#48     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#49     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#50     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#52     _StreamController._add (dart::async/stream_controller.dart::616)
#53     _StreamController.add (dart::async/stream_controller.dart::562)
#54     _Socket._onData (dart::io-patch/socket_patch.dart::1646)
#55     _rootRunUnary (dart::async/zone.dart::918)
#56     _CustomZone.runUnary (dart::async/zone.dart::810)
#57     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#58     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#59     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#61     _StreamController._add (dart::async/stream_controller.dart::616)
#62     _StreamController.add (dart::async/stream_controller.dart::562)
#63     _RawSocket._RawSocket.<anonymous closure> (dart::io-patch/socket_patch.dart::1215)
#64     _NativeSocket.issueReadEvent.issue (dart::io-patch/socket_patch.dart::749)
#65     _microtaskLoop (dart::async/schedule_microtask.dart::43)
#66     _microtaskLoopEntry (dart::async/schedule_microtask.dart::52)
#67     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::96)
#68     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart
Original message:
{"event"::"server.error","params"::{"isFatal"::false,"message"::"Exception from fix contributor:: DefaultFixContributor
RangeError:: Index:: 2, Size:: 2
#0      NodeList.[] (package::analyzer/src/generated/ast.dart::12758)
#1      FixProcessor._addFix_addMissingParameter (package::analysis_server/src/services/correction/fix_internal.dart::372)
#2      FixProcessor.compute (package::analysis_server/src/services/correction/fix_internal.dart::212)
#3      DefaultFixContributor.internalComputeFixes (package::analysis_server/src/services/correction/fix_internal.dart::52)
#4      DartFixContributor.computeFixes (package::analysis_server/plugin/edit/fix/fix_dart.dart::37)
#5      computeFixes (package::analysis_server/src/services/correction/fix.dart::27)
#6      EditDomainHandler.getFixes (package::analysis_server/src/edit/edit_domain.dart::164)
#7      EditDomainHandler.handleRequest (package::analysis_server/src/edit/edit_domain.dart::195)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package::analysis_server/src/analysis_server.dart::685)
#9      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#10     AnalysisServer.handleRequest.<anonymous closure> (package::analysis_server/src/analysis_server.dart::681)
#11     _rootRun (dart::async/zone.dart::907)
#12     _CustomZone.run (dart::async/zone.dart::802)
#13     _CustomZone.runGuarded (dart::async/zone.dart::708)
#14     runZoned (dart::async/zone.dart::1243)
#15     AnalysisServer.handleRequest (package::analysis_server/src/analysis_server.dart::680)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::169)
#17     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#18     ByteStreamServerChannel._readRequest (package::analysis_server/src/channel/byte_stream_channel.dart::160)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::109)
#20     _rootRunUnary (dart::async/zone.dart::914)
#21     _CustomZone.runUnary (dart::async/zone.dart::810)
#22     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#23     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#24     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#25     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#26     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#27     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#28     _LineSplitterSink._addLines (dart::convert/line_splitter.dart::127)
#29     _LineSplitterSink.addSlice (dart::convert/line_splitter.dart::102)
#30     StringConversionSinkMixin.add (dart::convert/string_conversion.dart::180)
#31     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#32     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#33     _rootRunUnary (dart::async/zone.dart::914)
#34     _CustomZone.runUnary (dart::async/zone.dart::810)
#35     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#36     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#37     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#38     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#39     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#40     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#41     _StringAdapterSink.addSlice (dart::convert/string_conversion.dart::260)
#42     _Utf8ConversionSink.addSlice (dart::convert/string_conversion.dart::336)
#43     _Utf8ConversionSink.add (dart::convert/string_conversion.dart::329)
#44     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#45     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#46     _rootRunUnary (dart::async/zone.dart::914)
#47     _CustomZone.runUnary (dart::async/zone.dart::810)
#48     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#49     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#50     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#52     _StreamController._add (dart::async/stream_controller.dart::616)
#53     _StreamController.add (dart::async/stream_controller.dart::562)
#54     _Socket._onData (dart::io-patch/socket_patch.dart::1646)
#55     _rootRunUnary (dart::async/zone.dart::918)
#56     _CustomZone.runUnary (dart::async/zone.dart::810)
#57     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#58     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#59     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#61     _StreamController._add (dart::async/stream_controller.dart::616)
#62     _StreamController.add (dart::async/stream_controller.dart::562)
#63     _RawSocket._RawSocket.<anonymous closure> (dart::io-patch/socket_patch.dart::1215)
#64     _NativeSocket.issueReadEvent.issue (dart::io-patch/socket_patch.dart::749)
#65     _microtaskLoop (dart::async/schedule_microtask.dart::43)
#66     _microtaskLoopEntry (dart::async/schedule_microtask.dart::52)
#67     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::96)
#68     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::149)

","stackTrace"::"#0      NodeList.[] (package::analyzer/src/generated/ast.dart::12758)
#1      FixProcessor._addFix_addMissingParameter (package::analysis_server/src/services/correction/fix_internal.dart::372)
#2      FixProcessor.compute (package::analysis_server/src/services/correction/fix_internal.dart::212)
#3      DefaultFixContributor.internalComputeFixes (package::analysis_server/src/services/correction/fix_internal.dart::52)
#4      DartFixContributor.computeFixes (package::analysis_server/plugin/edit/fix/fix_dart.dart::37)
#5      computeFixes (package::analysis_server/src/services/correction/fix.dart::27)
#6      EditDomainHandler.getFixes (package::analysis_server/src/edit/edit_domain.dart::164)
#7      EditDomainHandler.handleRequest (package::analysis_server/src/edit/edit_domain.dart::195)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package::analysis_server/src/analysis_server.dart::685)
#9      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#10     AnalysisServer.handleRequest.<anonymous closure> (package::analysis_server/src/analysis_server.dart::681)
#11     _rootRun (dart::async/zone.dart::907)
#12     _CustomZone.run (dart::async/zone.dart::802)
#13     _CustomZone.runGuarded (dart::async/zone.dart::708)
#14     runZoned (dart::async/zone.dart::1243)
#15     AnalysisServer.handleRequest (package::analysis_server/src/analysis_server.dart::680)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::169)
#17     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::188)
#18     ByteStreamServerChannel._readRequest (package::analysis_server/src/channel/byte_stream_channel.dart::160)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package::analysis_server/src/channel/byte_stream_channel.dart::109)
#20     _rootRunUnary (dart::async/zone.dart::914)
#21     _CustomZone.runUnary (dart::async/zone.dart::810)
#22     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#23     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#24     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#25     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#26     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#27     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#28     _LineSplitterSink._addLines (dart::convert/line_splitter.dart::127)
#29     _LineSplitterSink.addSlice (dart::convert/line_splitter.dart::102)
#30     StringConversionSinkMixin.add (dart::convert/string_conversion.dart::180)
#31     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#32     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#33     _rootRunUnary (dart::async/zone.dart::914)
#34     _CustomZone.runUnary (dart::async/zone.dart::810)
#35     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#36     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#37     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#38     _SinkTransformerStreamSubscription._add (dart::async/stream_transformers.dart::67)
#39     _EventSinkWrapper.add (dart::async/stream_transformers.dart::14)
#40     _StringAdapterSink.add (dart::convert/string_conversion.dart::256)
#41     _StringAdapterSink.addSlice (dart::convert/string_conversion.dart::260)
#42     _Utf8ConversionSink.addSlice (dart::convert/string_conversion.dart::336)
#43     _Utf8ConversionSink.add (dart::convert/string_conversion.dart::329)
#44     _ConverterStreamEventSink.add (dart::convert/chunked_conversion.dart::80)
#45     _SinkTransformerStreamSubscription._handleData (dart::async/stream_transformers.dart::119)
#46     _rootRunUnary (dart::async/zone.dart::914)
#47     _CustomZone.runUnary (dart::async/zone.dart::810)
#48     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#49     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#50     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#51     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#52     _StreamController._add (dart::async/stream_controller.dart::616)
#53     _StreamController.add (dart::async/stream_controller.dart::562)
#54     _Socket._onData (dart::io-patch/socket_patch.dart::1646)
#55     _rootRunUnary (dart::async/zone.dart::918)
#56     _CustomZone.runUnary (dart::async/zone.dart::810)
#57     _CustomZone.runUnaryGuarded (dart::async/zone.dart::716)
#58     _BufferingStreamSubscription._sendData (dart::async/stream_impl.dart::341)
#59     _BufferingStreamSubscription._add (dart::async/stream_impl.dart::270)
#60     _StreamController&&_SyncStreamControllerDispatch._sendData (dart::async/stream_controller.dart::744)
#61     _StreamController._add (dart::async/stream_controller.dart::616)
#62     _StreamController.add (dart::async/stream_controller.dart::562)
#63     _RawSocket._RawSocket.<anonymous closure> (dart::io-patch/socket_patch.dart::1215)
#64     _NativeSocket.issueReadEvent.issue (dart::io-patch/socket_patch.dart::749)
#65     _microtaskLoop (dart::async/schedule_microtask.dart::43)
#66     _microtaskLoopEntry (dart::async/schedule_microtask.dart::52)
#67     _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::96)
#68     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::149)
"}}
```

**Comment by lukechurch** [comment] 2016-02-04 12:20
+another 500 occurances

**Comment by scheglov** [comment] 2016-02-04 21:31
Duplicate of https://github.com/dart-lang/sdk/issues/25021

Fixed in https://codereview.chromium.org/1468913004

**Comment by bwilkerson** [comment] 2016-02-04 21:55
@scheglov Are you sure? The CL you referenced was from last November (over 2 months ago). It looks like the change went in to version 1.14.0-dev.2.0. Assuming we got the right version number, this is being reported against 1.14.0-dev.7.2. Could this be a regression?

@lukechurch Could the version number be wrong?

**Comment by lukechurch** [comment] 2016-02-04 21:58
@bwilkerson I'm looking into that

**Comment by lukechurch** [comment] 2016-02-04 22:12
@bwilkerson This looks like it was victim of the memory bug I chatted with you about so it was falsely reporting the versions. I'll recycle all the issues.

**Comment by scheglov** [comment] 2016-02-04 22:12
NP

**Closed** 2016-02-04 22:15 UTC
Labels: analyzer-stability, area-analyzer, priority-high, Type-Defect
