### ISSUE TITLE
Crash during GC

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29258] opened 2017-04-05 11:04 UTC
Buildbot showed a crash during GC.
This is on the safaric bot. while running dart2js tests.
This is before the async debugger support was disabled (https://github.com/dart-lang/sdk/commit/e33e09a23c61afac0827336c27b0d99789119b8c)

Log file (will go stale soon): https://build.chromium.org/p/client.dart/builders/dart2js-mac10.11-safari-3-3-be/builds/4583/steps/dart2js%20safari%20co19%20fast-startup%20tests/logs/stdio

Relevant output:
```
Running "dart2js" command: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --fast-startup --packages=/b/build/slave/10.11-3-be/build/sdk/.packages --out=/b/build/slave/10.11-3-be/build/sdk/xcodebuild/ReleaseX64/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Assignment_Compound_Assignment_indexed_expression_assignment_t04/test.js /b/build/slave/10.11-3-be/build/sdk/tests/co19/src/Language/Expressions/Assignment/Compound_Assignment/indexed_expression_assignment_t04.dart
Running "dart2js" command: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --fast-startup --packages=/b/build/slave/10.11-3-be/build/sdk/.packages --out=/b/build/slave/10.11-3-be/build/sdk/xcodebuild/ReleaseX64/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Assignment_Compound_Assignment_indexed_expression_assignment_t11/test.js /b/build/slave/10.11-3-be/build/sdk/tests/co19/src/Language/Expressions/Assignment/Compound_Assignment/indexed_expression_assignment_t11.dart
../../runtime/vm/raw_object.cc: 283: error: unreachable code
Dumping native stack trace for thread 1303
Class Id: 1
  [0x000000010cacead3] dart::Profiler::DumpStackTrace()
  [0x000000010cacead3] dart::Profiler::DumpStackTrace()
  [0x000000010c74780e] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x000000010cad2615] dart::RawObject::VisitPointers(dart::ObjectPointerVisitor*)
  [0x000000010cb24be8] dart::Scavenger::ProcessToSpace(dart::ScavengerVisitor*)
  [0x000000010cb2525d] dart::Scavenger::Scavenge(bool)
  [0x000000010c8eede9] dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::Heap::ApiCallbacks, dart::Heap::GCReason)
  [0x000000010c8edebe] dart::Heap::AllocateOld(long, dart::HeapPage::PageType)
  [0x000000010c97a995] dart::Object::Allocate(long, long, dart::Heap::Space)
  [0x000000010c9d0139] dart::ICData::NewDescriptor(dart::Zone*, dart::Function const&, dart::String const&, dart::Array const&, long, long, bool)
  [0x000000010c9d03b6] dart::ICData::New(dart::Function const&, dart::String const&, dart::Array const&, long, long, bool)
  [0x000000010c9cec5b] dart::ICData::NewFrom(dart::ICData const&, long)
  [0x000000010c9ced49] dart::ICData::AsUnaryClassChecksForArgNr(long) const
  [0x000000010c95d034] dart::JitOptimizer::VisitInstanceCall(dart::InstanceCallInstr*)
  [0x000000010c9548d4] dart::JitOptimizer::ApplyClassIds()
  [0x000000010c83fd4e] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x000000010c8410f8] dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)
  [0x000000010c84211a] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  [0x000000010c843ca8] dart::BackgroundCompiler::Run()
-- End of DumpStackTrace
Command: /b/build/slave/10.11-3-be/build/sdk/tools/sdks/mac/dart-sdk/bin/dart --checked /b/build/slave/10.11-3-be/build/sdk/tools/test.dart --mode=release --arch=x64 --use-sdk --compiler=dart2js --dart2js-batch --runtime=safari --progress=buildbot -v --reset-browser-configuration --report --time --failure-summary --write-debug-log --write-test-outcome-log --shards=3 --shard=3 --fast-startup --append_logs co19
CRASHED with exit code -6 (0xfffffffa)
step returned non-zero exit code: 250
@@@STEP_FAILURE@@@

```

**Comment by mraleph** [comment] 2017-04-05 11:42
I think we should consider this a duplicate of #28858

**Closed by mraleph** 2017-04-05 11:42 UTC
Labels: area-vm, gardening
