### ISSUE TITLE
This is the latest of the messages from dart analyser. (IntelliJ)

### ISSUE THREAD

**Issue by jackokring** [dart-lang/sdk#35845] opened 2019-02-04 12:17 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-183.5429.30`
- `2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b`
- `IC-183.5429.30, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b, server version 1.21.1, error: Analysis failed: C:\Users\user\IdeaProjects\vt303\lib\display.dart context: exception_20190204_121418_798
Exception: Element not found in summary: package:flutter/src/painting/image_provider.dart;package:flutter/src/painting/image_provider.dart;AtlasProvider
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:314:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:353:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:113:29)
#4      _ReferenceInfo._buildType.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:1019:48)
#5      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1439:26)
#6      DeclarationResolver._setGenericFunctionType (package:analyzer/src/generated/declaration_resolver.dart:521:37)
#7      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:474:7)
#8      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11610:15)
#9      TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10793:20)
#10     RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1214:10)
#11     DeclarationResolver.visitTopLevelVariableDeclaration (package:analyzer/src/generated/declaration_resolver.dart:430:11)
#12     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10788:15)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8366:20)
#14     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#15     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:715:10)
#16     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#17     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:12)
#18     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:597:31)
#19     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#20     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#21     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#22     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#25     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#26     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#27     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#34     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#40     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#41     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#42     main (file:///E:/b/rr/tmpqlvyqu/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#43     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#44     main (file:///E:/b/rr/tmpqlvyqu/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#45     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\user\AppData\Local\Temp\report.txt.

**Comment by stereotype441** [comment] 2019-02-05 16:01
Duplicate of #35620

**Closed by stereotype441** 2019-02-05 16:01 UTC
Labels: area-analyzer
