### ISSUE TITLE
Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained.

### ISSUE THREAD

**Issue by truongsinh** [dart-lang/sdk#37371] opened 2019-06-26 11:50 UTC
I got this message

> Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), but the file was not self-contained. This might be a bug.
> 
> The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///var/folders/hc/0mr21jxs11z7zfs92kz3g83h0000gp/T/initialize_from.dillgPrucj/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.

[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3329833/initialize_from.dill.gz)

**Comment by a-siva** [comment] 2019-07-02 16:39
This is a duplicate of https://github.com/dart-lang/sdk/issues/36032

**Closed by a-siva** 2019-07-02 16:39 UTC
Labels: area-front-end, area-vm
