### ISSUE TITLE
VM: external methods that fail to reify type information on returned objects

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#32607] opened 2018-03-20 15:46 UTC
I am attempting to get all of the unit tests in pkg/analyzer to pass when run on a VM with the `--preview-dart-2` flag. I have run into a couple of failures that appear to be caused by external methods returning objects that do not have reified type arguments.

To reproduce the failures, in the root of the sdk repo run
```
$ dart --preview-dart-2 pkg/analyzer/test/file_system/physical_resource_provider_test.dart
```

The first is a failure of the form:
```
00:06 +91 -1: file system | PhysicalResourceProviderTest | test_getModificationTimes [E]
  type '_Future' is not a subtype of type 'Future<List<int>>' where
    _Future is from dart:async
    Future is from dart:async
    List is from dart:core
    int is from dart:core
  
  package:isolate/isolate_runner.dart 189:12                         IsolateRunner.run
  package:analyzer/file_system/physical_file_system.dart 107:19      PhysicalResourceProvider.getModificationTimes
```
which appears to indicate that `IsolateRunner.run` is returning a `_Future` with no type argument.

The second is a failure of the form:
```
00:07 +92 -2: file system | PhysicalResourceProviderTest | test_watchFile_delete [E]
  type '_BroadcastStream' is not a subtype of type 'Stream<FileSystemEvent>' where
    _BroadcastStream is from dart:async
    Stream is from dart:async
    FileSystemEvent is from dart:io
  
  dart:io/runtime/binfile_patch.dart 119:12                          _FileSystemWatcher._watch
  dart:io/file_system_entity.dart 489:33                             FileSystemEntity.watch
  package:watcher/src/file_watcher/native.dart 46:10                 _NativeFileWatcher._listen
  package:watcher/src/file_watcher/native.dart 36:5                  new _NativeFileWatcher
  package:watcher/src/file_watcher/native.dart 19:31                 new NativeFileWatcher.<fn>
  package:watcher/src/resubscribable.dart 47:21                      new ResubscribableWatcher.<fn>
```
which appears to indicate that `_FileSystemWatcher._watch` is returning a `_BroadcastStream` with no type argument.

(There is a third set of failures currently being reported by running the tests, but I have no reason at this point to believe that they indicate a bug in the VM.)

**Comment by bwilkerson** [comment] 2018-03-22 18:59
This is blocking me from getting the analyzer tests to pass when passing `--preview-dart-2` to the VM.

**Comment by bwilkerson** [comment] 2018-05-11 16:12
@scheglov We might want to set a priority on this issue (assuming it hasn't yet been fixed)

**Comment by bwilkerson** [comment] 2018-05-11 16:12
@scheglov We might want to set a priority on this issue (assuming it hasn't yet been fixed)

**Comment by keertip** [comment] 2018-05-14 20:58
@a-siva, we are seeing this internally too.

**Comment by scheglov** [comment] 2018-05-15 14:33
Hm... Yes, I see it too.
Apparently I missed `PhysicalResourceProvider` tests while running test of Analyzer.

**Comment by scheglov** [comment] 2018-05-15 16:32
1. We stopped using `package:isolate`.
2. I don't see a failure in `test_watchFile_delete`.
3. There are failures related to the `watcher` package, on Mac and Windows, I will fix them and upload PR.

**Comment by scheglov** [comment] 2018-05-15 17:07
2. I saw `type '_BroadcastStream' is not a subtype of type 'Stream<FileSystemEvent>' where` on older Dart SDK on Windows. It went away after SDK update.

**Comment by keertip** [comment] 2018-05-15 17:12
@scheglov,  see [watcher/issue 53](https://github.com/dart-lang/watcher/issues/53)

**Comment by scheglov** [comment] 2018-05-15 17:15
https://github.com/dart-lang/watcher/pull/54 will fix Dart2 type problems, if landed.

**Comment by scheglov** [comment] 2018-05-15 19:43
The PR has been landed, we need to publish `watcher` (I cannot do this @kevmoo ) and pull into the repo.

**Comment by kevmoo** [comment] 2018-05-15 19:51
I think we need to patch the 0.9.7+x branch – 0.9.8 is not ready yet...

**Comment by crelier** [comment] 2018-05-16 01:40
@scheglov, I am unclear about the steps to reproduce.
With a [week old build](https://dart.googlesource.com/sdk/+/e62dd0157e2b0725cb464c34b4622a02aaa954fd), I do not see any test failure:

```
$ out/DebugX64/dart --preview-dart-2 pkg/analyzer/test/file_system/physical_resource_provider_test.dart
00:00 +0: PhysicalResourceProviderTest | test_getFolder_trailingSeparator
00:00 +1: PhysicalResourceProviderTest | test_getModificationTimes
[...]
00:19 +58: FolderTest | test_toUri
00:19 +59: All tests passed!

```

With [today's build](https://dart.googlesource.com/sdk/+/b51f4b7956145edef8e22818e3e3f0f4958993f2), I see a different error than the one reported:

```
00:18 +11 -1: FileTest | test_delete [E]
  type 'List<int>' is not a subtype of type 'Uint8List'
  dart:io/file_impl.dart 301:48                                             _File._deleteSync
  dart:io/file_system_entity.dart 465:47                                    FileSystemEntity.deleteSync
  package:analyzer/file_system/physical_file_system.dart 381:14             _PhysicalResource.delete
  pkg/analyzer/test/file_system/physical_resource_provider_test.dart 71:10  FileTest.test_delete
  dart:mirrors/runtime/libmirrors_impl.dart 316:37                          _LocalInstanceMirror._invoke
  dart:mirrors/runtime/libmirrors_impl.dart 312:25                          _LocalInstanceMirror.invoke
[...]

```
Is the failure above the one you are currently seeing? Thanks.

**Comment by scheglov** [comment] 2018-05-16 16:03
There are two problems.

1. When I run `FileTest::test_delete()` from `physical_resource_provider_test.dart` on Mac, I see the exception `type 'List<int>' is not a subtype of type 'Uint8List'`. This seems a `dart:io` issue.

2. When I run a subset of `package:watcher` tests on Windows I see
```
00:01 +10 -1: moves notifies when a file is moved from outside the watched directory [E]                                                                       
  FileSystemException: Deletion failed, path = 'C:\Users\scheglov\AppData\Local\Temp\dart_test_46d62e17-5862-11e8-84c0-9801a7934df4' (OS Error: Папка не пуста.
  , errno = 145)                                                                                                                                               
  dart:io/directory_impl.dart 165:9                             _Directory._delete.<fn>                                                                        
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>                                        
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run                                                                    
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>                                             
  dart:async/zone.dart 1134:38                                  _rootRunUnary                                                                                  
  dart:async/zone.dart 1031:19                                  _CustomZone.runUnary                                                                           
  dart:async/future_impl.dart 129:18                            _FutureListener.handleValue                                                                    ```
This is probably an issue with `package:watcher` tests and Windows way to handle files.

**Comment by crelier** [comment] 2018-05-16 18:19
I do not see problem 1) on Linux anymore this morning, which I could reproduce yesterday. So something must have been fixed overnight. Do you still see this issue?
Also, I do not have either a Mac nor a Windows machine to investigate problem 2).

**Comment by scheglov** [comment] 2018-05-17 16:14
Yes, thanks, I can also see that (1) is fixed on Mac now.

With the fix to `package:watcher` Mac resource provider tests run cleanly on Mac, which never had (2).

On Windows these failing tests are disabled altogether by the author, so I guess we don't need to solve (2) there.

**Comment by crelier** [comment] 2018-05-17 16:40
OK, great!
I am assigning this bug to you, since I have nothing to fix on my side.
Feel free to close or reassign.
Thanks!

**Closed** 2018-05-19 02:53 UTC
Labels: area-vm
