### ISSUE TITLE
0.0 and -0.0 identical in dart2js and not identical in cfe

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42223] opened 2020-06-08 05:29 UTC
The following code works in CFE but fails in dart2js and dartdevk
```dart
import "../../../Utils/expect.dart";

double pnil = 0.0;
double nnil = -0.0;

main() {
  Expect.isFalse(identical(pnil, nnil));
}
```
I'm not sure which behavior is correct but in any way all of the tools must behave in a same way
`SDK version 2.9.0-13.0.dev`

**Comment by sigmundch** [comment] 2020-06-08 15:28
Many of these number inconsistencies is by design, so other than tests trying to cover the number behavior explicitly, we should not rely on it for any tests that is expected to behave the same on all tools.

For context, Dart on the web and elsewhere purposely have different number semantics. This is a result of a tradeoff we made between consistency and performance: to perform reasonably well, we must use the underlying JavaScript numbers when compiling to JavaScript. To make this work well, the CFE is configurable to track two kinds of number semantics. When used out of the box or within the VM it uses the Dart number semantics. On an compiler that targets JavaScript (ddc and dart2js) it uses JS number semantics when evaluating constants as well. You also get static errors if you write number literals that cannot be represented with the JavaScript semantics (for instance, a 64-bit number that is not possible to encode with JS's 53-bit representation).

Some common differences are `identical(0.0, 0.0)`, also `identical(1.0, 1)`, `(3.0).runtimeType == "int"`.

**Comment by sigmundch** [comment] 2021-11-02 18:46
Closing as intended, here is a longer article with more details: https://dart.dev/guides/language/numbers

**Closed by sigmundch** 2021-11-02 18:46 UTC
Labels: web-dart2js, area-web
