### ISSUE TITLE
Dart analysis exception - NoSuchMethodError: The getter 'type' was called on null.

### ISSUE THREAD

**Issue by elliottmb** [dart-lang/sdk#39396] opened 2019-11-15 15:12 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v5.0.0-36-generic, screens 3440x1440, 3440x1440`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a PreferConstConstructors to visit a InstanceCreationExpressionImpl in VariableDeclarationImpl in VariableDeclarationListImpl in VariableDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      VariableMember.type (package:analyzer/src/dart/element/member.dart:1053:61)
#2      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:626:40)
#3      ConstantEvaluationEngine.evaluateSuperConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:757:41)
#4      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:737:9)
#5      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:134:27)
#6      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#7      LinterContextImpl._hasConstantVerifierError (package:analyzer/src/lint/linter.dart:322:10)
#8      LinterContextImpl.canBeConst (package:analyzer/src/lint/linter.dart:290:15)
#9      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/prefer_const_constructors.dart:95:19)
#10     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#11     LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#12     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#13     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#14     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10523:19)
#15     RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1302:10)
#16     LinterVisitor.visitVariableDeclaration (package:analyzer/src/lint/linter_visitor.dart:673:11)
#17     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10517:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#19     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10619:16)
#20     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1308:10)
#21     LinterVisitor.visitVariableDeclarationList (package:analyzer/src/lint/linter_visitor.dart:679:11)
#22     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10613:15)
#23     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10666:20)
#24     RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1314:10)
#25     LinterVisitor.visitVariableDeclarationStatement (package:analyzer/src/lint/linter_visitor.dart:685:11)
#26     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10662:15)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#28     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#29     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#30     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#31     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#32     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#33     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#34     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#35     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#36     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#37     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#38     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:450:11)
#39     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#40     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#41     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#42     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#43     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#44     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#45     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#46     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#47     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#48     LinterVisitor.v...
```

## /tmp/report.txt
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Exception while using a PreferConstConstructors to visit a InstanceCreationExpressionImpl in VariableDeclarationImpl in VariableDeclarationListImpl in VariableDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      VariableMember.type (package:analyzer/src/dart/element/member.dart:1053:61)
#2      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:626:40)
#3      ConstantEvaluationEngine.evaluateSuperConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:757:41)
#4      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:737:9)
#5      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:134:27)
#6      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#7      LinterContextImpl._hasConstantVerifierError (package:analyzer/src/lint/linter.dart:322:10)
#8      LinterContextImpl.canBeConst (package:analyzer/src/lint/linter.dart:290:15)
#9      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/prefer_const_constructors.dart:95:19)
#10     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#11     LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#12     LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#13     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#14     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10523:19)
#15     RecursiveAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1302:10)
#16     LinterVisitor.visitVariableDeclaration (package:analyzer/src/lint/linter_visitor.dart:673:11)
#17     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10517:49)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#19     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10619:16)
#20     RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1308:10)
#21     LinterVisitor.visitVariableDeclarationList (package:analyzer/src/lint/linter_visitor.dart:679:11)
#22     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10613:15)
#23     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10666:20)
#24     RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1314:10)
#25     LinterVisitor.visitVariableDeclarationStatement (package:analyzer/src/lint/linter_visitor.dart:685:11)
#26     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:10662:15)
#27     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#28     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#29     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#30     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#31     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#32     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#33     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#34     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#35     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#36     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#37     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#38     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:450:11)
#39     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#40     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#41     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#42     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#43     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#44     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#45     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#46     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#47     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#48     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#49     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#50     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:353:10)
#51     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:206:11)
#52     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#53     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:201:35)
#54     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#55     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#56     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#57     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#58     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#59     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#60     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#61     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#62     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#63     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#64     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#65     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#66     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#67     _rootRun (dart:async/zone.dart:1124:13)
#68     _CustomZone.run (dart:async/zone.dart:1021:19)
#69     _runZoned (dart:async/zone.dart:1516:10)
#70     runZoned (dart:async/zone.dart:1463:12)
#71     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#72     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#73     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#74     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#75     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#76     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#77     new Future.sync (dart:async/future.dart:224:31)
#78     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#79     _rootRun (dart:async/zone.dart:1124:13)
#80     _CustomZone.run (dart:async/zone.dart:1021:19)
#81     _runZoned (dart:async/zone.dart:1516:10)
#82     runZoned (dart:async/zone.dart:1463:12)
#83     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#84     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#85     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#86     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#87     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#88     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#89     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#90     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
```
1573830211114 <= {"event":"completion.existingImports","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","imports":{"elements":{"strings":["dart:async","ControllerCan
1573830211118 <= {"event":"completion.results","params":{"id":"465","replacementOffset":547,"replacementLength":3,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"AbstractFilestoreProvid
1573830211119 <= {"event":"analysis.highlights","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUIL
1573830211120 <= {"event":"analysis.navigation","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"leng
1573830211120 <= {"event":"analysis.closingLabels","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","labels":[]}}
1573830211120 <= {"event":"analysis.outline","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name"
1573830211120 <= {"event":"analysis.overrides","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","overrides":[{"offset":768,"length":6,"superclassMember":{"element":{
1573830211121 <= {"event":"flutter.outline","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":4625,"codeOffset":0
1573830211123 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1187,"uri":"package:hammer/resources/filestore_provider.dart","items":[{"label":"AbstractFilestoreProvid
1573830211124 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1187,"uri":"package:hammer/resources/filestore_provider.dart","items":[{"label":"AbstractFilestoreProvid
1573830211149 => {"id":"2658","method":"edit.getFixes","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","offset":547},"clientRequestTime":1573830211149}
1573830211150 => {"id":"2659","method":"edit.getFixes","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","offset":537},"clientRequestTime":1573830211150}
1573830211227 => {"id":"2660","method":"analysis.updateContent","params":{"files":{"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart":{"type":"add","content":"import 'dart:async';\nimp
1573830211227 => {"id":"2661","method":"completion.getSuggestions","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","offset":551},"clientRequestTime":1573830211227}
1573830211241 <= {"event":"analysis.errors","params":{"file":"/home/elliott/repos/hammer/lib/blocs/tract_addedit_screen/tract_addedit_screen_bloc.dart","errors":[]}}
1573830211241 <= {"id":"2660","result":{}}
1573830211252 <= {"id":"2661","result":{"id":"466"}}
1573830211252 <= {"event":"analysis.errors","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"f
1573830211253 <= {"id":"2658","result":{"fixes":[{"error":{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","offset":510
1573830211253 <= {"id":"2659","result":{"fixes":[{"error":{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","offset":510
1573830211254 <= {"event":"completion.existingImports","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","imports":{"elements":{"strings":["dart:async","ControllerCan
1573830211258 <= {"event":"completion.results","params":{"id":"466","replacementOffset":547,"replacementLength":4,"results":[{"kind":"INVOCATION","relevance":1058,"completion":"userId","selectionOffse
1573830211259 <= {"event":"analysis.highlights","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUIL
1573830211260 <= {"event":"analysis.navigation","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"leng
1573830211260 <= {"event":"analysis.closingLabels","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","labels":[]}}
1573830211260 <= {"event":"analysis.outline","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name"
1573830211261 <= {"event":"analysis.overrides","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","overrides":[{"offset":769,"length":6,"superclassMember":{"element":{
1573830211267 <= {"event":"flutter.outline","params":{"file":"/home/elliott/repos/hammer/lib/resources/filestore_provider.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":4626,"codeOffset":0
1573830211269 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1187,"uri":"package:hammer/resources/filestore_provider.dart","items":[{"label":"AbstractFilestoreProvid
1573830211377 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a PreferConstConstructors to visit a InstanceCreationExpressionImpl in VariableDeclarationImpl in Va
```

**Comment by srawlins** [comment] 2019-11-20 18:58
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38514; please follow along there.

**Comment by srawlins** [comment] 2019-11-20 18:58
Duplicate of https://github.com/dart-lang/sdk/issues/38514

**Closed by srawlins** 2019-11-20 18:58 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
