### ISSUE TITLE
Better support for "re-typing" collections

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27489] opened 2016-10-04 23:54 UTC
With strong mode, it is more important that the reified type of a collection more precisely describe its contents, since you can't as easily just pass around, say, `List<dynamic>` and have everything be happy.

There are a few different, not necessarily mutually exclusive ways we can improve this:
- Make `List.from()` et al. takes arguments that use `T`. See: #26383.
- Add an `Iterable.cast<T>()` method that produces a new iterable of the given type and throws an exception if you access an element that happens to not be of that type.
- Add an `Iterable.ofType<T>()` method that produces a new iterable of the given type by lazily skipping any elements not of that type.

Both names are, of course, subject to change.

**Comment by lrhn** [comment] 2016-12-15 10:13
The most promising is the `cast` method on `Iterable`. A rough specification for that would be: https://gist.github.com/lrhn/e61c30c68cd6a4c307b62e25ecf156ee

(That would be enough for me to implement the feature in the platform libraries and corresponding packages).

**Comment by mit-mit** [comment] 2016-12-15 10:19
Moving to 1.22 for implementation

**Comment by munificent** [comment] 2016-12-15 20:26
Should we file a separate bug for *just* `.cast<T>()`, or retarget this one to only include that, or extend the proposal to support `ofType<T>()` or whatever else we want to call it?

**Comment by eernstg** [comment] 2016-12-16 12:41
I think it's slightly misleading that `new List<num>().cast<int>()` will be an `Iterable<int>` rather than an `int`. Maybe `.castTypeArgument<>()` would be less confusing? I suppose we will only see this rarely, because most occurrences will be compiler generated invocations based on the Picard operator, which makes readability more important when this method is actually specified explicitly. Maybe the IDE would show the method name on hover at the Picard operator, in which case readability is again more important than writeability.

**Comment by lrhn** [comment] 2016-12-16 12:43
Precision isn't everything, sometimes brevity takes precedence :)
I'm picking this name exactly because the similar functionality already exists in at least one other language with the same name (C#, `IEnumerable.Cast`: https://msdn.microsoft.com/en-us/library/bb341406(v=vs.110).aspx).

**Comment by eernstg** [comment] 2016-12-16 12:57
You could say that you are less likely to have `var y = x.cast<int>()` which looks like a cast to `int`, and more likely to have `Iterable ys = myList.cast<int>()` which is more likely to make developers think about `Iterable<int>`.

**Comment by munificent** [comment] 2016-12-16 18:31
> I think it's slightly misleading that `new List<num>().cast<int>()` will be an `Iterable<int>` rather than an `int`.

I don't think this will be confusing. Like Lasse notes, it's what the method is called in C#. I think users get that they are casting the collection. Certainly, they will get feedback in their IDE that makes this clear.

> You could say that you are less likely to have `var y = x.cast<int>()` which looks like a cast to int,

Actually, I think this will be the common case. Except that users hopefully use better names!

```dart
if (<we establish that every employee is a manager>) {
  managers = employees.cast<Manager>();
  // ...
}
```

>  and more likely to have Iterable ys = myList.cast<int>()

That would rely on us having inference fill in "partial annotations" like `Iterable` to `Iterable<int>`. I'm not sure if we even decided that inference should do that, but, either way, I think people will just use `var` most of the time.

**Comment by mit-mit** [comment] 2017-01-03 12:27
@lrhn did https://codereview.chromium.org/2529393002 resolve this issue, or is there more work?

**Comment by lrhn** [comment] 2017-01-03 12:42
No, not at all, that CL just changed comment syntax to real syntax, it didn't add anything.

**Comment by munificent** [comment] 2017-01-13 22:32
This is listed as part of 1.22. Is anything going on with it?

**Comment by lrhn** [comment] 2017-01-14 11:08
Nothing so far. It's really a change that *only* makes sense for strong mode, because the methods rely on type parameters. That means that any use of the method in non-strong mode is meaningless (or wrong). Are we absolutely sure we want to add these methods to Dart 1.0 libraries?

**Comment by munificent** [comment] 2017-01-17 20:53
> Are we absolutely sure we want to add these methods to Dart 1.0 libraries?

I don't know, but if not, it shouldn't be in milestone-1.22. I'm personally fine with kicking it out to 1.50.

**Comment by lrhn** [comment] 2017-01-17 20:59
I have a CL (not uploaded yet) that adds `cast` to `Iterable`, `List`, `Set`, `Queue` and `Map`. Core libraries only, not packages.
We probably also want it on `Future` and `Stream`.

**Comment by matanlurey** [comment] 2017-01-17 21:01
Just a QQ - does `cast` or `ofType` have a runtime cost? Will teams be aware of this? Where do you expect either to be used, and what will be the guidelines about using them in performance sensitive code? Specifically in dart2js?

We've seen noticeable latency regressions when teams go and add `x as T` throughout their codebase to try and satisfy strong mode requirements - most of the need has gone away as the specification solidified and generic method support came in - but still worth mentioning.

**Comment by munificent** [comment] 2017-01-17 21:29
> Just a QQ - does `cast()` or `ofType()` have a runtime cost? 

Yes. `cast()` will produce a wrapped object that asserts the type on use. I'm not sure if it does it eagerly or lazily. `ofType()` would lazily filter out non-matching elements, so it has the same performance characteristics as `where()`.

> Will teams be aware of this?

I hope so! It should be our job to explain this well.

> Where do you expect either to be used, and what will be the guidelines about using them in performance sensitive code?

Neither should be super common. When possible, it's better to narrow the type "upstream" when you first create the collection. `cast()` is useful when you know out of band at some point that the collection does not contain any non-matching elements and you want the freedom of assuming that.

`ofType()` is a (very important) convenience method for filtering by type. You'd use it anywhere you would do `.where((t) => t is ___)` today, except that `ofType()` correctly produces a sequence with the right generic type.

> We've seen noticeable latency regressions when teams go and add `x as T` throughout their codebase to try and satisfy strong mode requirements

Right now, dart2js is in the worst of both worlds. As users migrate to strong mode, they add explicit `as` which get checked at runtime. But dart2js doesn't implement strong mode yet, so it can't take advantage of the type system to eliminate check that *aren't* needed.

My hope is that once dart2js implements strong mode and can rely on types, the performance will get better. It's hard to be too prescriptive to users based on how our compilers currently work because they are very much a moving target right now.

**Comment by matanlurey** [comment] 2017-01-17 21:39
Thanks for the quick and detailed response @munificent.

When we release this feature I hope we can make sure to make theses point so users aren't tripped up, a lot of "hope" of the Dart team ending up concluding in latency regressions, confusing implementations for internal clients so I want to make sure this is rolled out smoothly :)

(Happy to help with messaging once it gets close to landing)

**Comment by munificent** [comment] 2017-01-18 20:52
> (Happy to help with messaging once it gets close to landing)

That would be great. I totally agree it's really important we give clear guidance when we ship language and API changes.

**Comment by lrhn** [comment] 2017-01-19 07:43
Moving to 1.50. This implementation is useless for Dart 1 users since it depends on functioning type parameters on methods.

**Comment by leafpetersen** [comment] 2017-01-19 21:28
> Moving to 1.50.

1.22 is 1.50 (or 1.23 will be at the latest).  

What's happening with this?

**Comment by mit-mit** [comment] 2017-01-20 08:12
Yes, should either move to 1.23 or to 2.0

**Comment by lrhn** [comment] 2017-01-20 08:30
Done.

**Comment by leafpetersen** [comment] 2017-01-20 18:09
Why the slip to 2.0?  I thought we'd made good progress on this.

**Comment by munificent** [comment] 2017-01-20 18:32
> Why the slip to 2.0?

It's a breaking change. :( User classes that implement `Iterable<T>` will have static warnings (errors in strong mode) if we add a new method to Iterable.

(Aside: This is why in C#-land, their library design guidelines encourage exposing concrete base classes instead of interfaces. In C#, you can add a method to a base class without it being a breaking change. Sadly, even that is a breaking change in Dart too, because the user's subclass could already define a method with the same name but a different signature. C# can handle that, but we can't. :sad:)

**Comment by matanlurey** [comment] 2017-08-11 03:14
> Sadly, even that is a breaking change in Dart too, because the user's subclass could already define a method with the same name but a different signature. C# can handle that, but we can't. 😭 

Silly question, any reason we can't at least slightly modify Dart to make it easier to land new APIs in a non-breaking manner (similar to C#)?

**Comment by munificent** [comment] 2017-08-25 18:16
> Silly question, any reason we can't at least slightly modify Dart to make it easier to land new APIs in a non-breaking manner (similar to C#)?

I don't know how do this in a way that would be a "slight" modification. C# handles this by supporting both overloading and nonvirtual methods. Either of those would be fundamental and highly contentious changes to Dart.

**Comment by matanlurey** [comment] 2017-08-25 18:19
What about an annotation like @mayNotImplement that adds a default method
that throws not implemented on subtypes?

**Comment by munificent** [comment] 2017-08-25 19:52
Even that gets complicated once you start thinking about classes that could or could not be used as mixins, classes that are treated like superinterfaces, etc.

**Comment by nex3** [comment] 2017-09-19 20:34
I'm strongly in favor of the `cast()` option for collections as well as a number of `dart:async` types (`Stream`, `Future`, `StreamSubscription`, `StreamTransformer`, `StreamConsumer`), as well as for the `Sink` type in `dart:core`. We currently work around this using `Delegating*.typed()` static functions from the `collection` and `async` packages, but this is very unwieldy.

**Comment by lrhn** [comment] 2017-09-20 10:41
We currently plan to go with `cast`. It'll likely mean having the equivalent of the typed delegating classes internally in the SDK (and possibly exposing them in dart:collection/dart:async so others can implement `cast` the same way), but it should be easier to use when it's on the object itself.

**Comment by matanlurey** [comment] 2018-04-25 04:05
Can this be closed @leafpetersen or is there more work planned?

**Comment by munificent** [comment] 2018-04-25 20:25
I get the joy of closing it! As far as I know, we're good here. We now have a surfeit of ways to re-type collections.

**Closed** 2018-04-25 20:24 UTC
Labels: area-library, core-2, library-core
