### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by xuexin** [dart-lang/sdk#34879] opened 2018-10-22 02:57 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900, 2560x1440  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/r_/_9bs4t6n7wd680stmrm0yk8m0000gn/T/report2.txt
```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/liaoyuhao/learn_widget/lib/drag_playground.dart
Exception: Element not found in summary: package:flutter/src/gestures/multidrag.dart;package:flutter/src/gestures/multidrag.dart;bool
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:996:48)
#5      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1389:26)
#6      DeclarationResolver._setGenericFunctionType (package:analyzer/src/generated/declaration_resolver.dart:523:37)
#7      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:476:7)
#8      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11481:15)
#9      FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4387:17)
#10     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:834:10)
#11     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:197:11)
#12     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#16     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#17     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#18     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
#19     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#21     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#22     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#24     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#25     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#26     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#27     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#28     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#29     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#30     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#31     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1025:23)
<asynchronous suspension>
#36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#38     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#39     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#40     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#47     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#48     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#50     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1540176945045 => {"id":"23","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/learn_widget/lib/main.dart","offset":1141,"length":0},"clientRequestTime":1540176945045}
1540176945048 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540176945062 <= {"id":"23","result":{"assists":[]}}
1540176945066 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540176945890 => {"id":"24","method":"analysis.setPriorityFiles","params":{"files":["/Users/liaoyuhao/learn_widget/lib/drag_playground.dart"]},"clientRequestTime":1540176945890}
1540176945890 => {"id":"25","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/liaoyuhao/learn_widget/lib/drag_playground.dart"],"CLOSING_LABELS":["/Users/liaoyuhao/l
1540176945891 <= {"id":"24"}
1540176945891 => {"id":"26","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":[]}}}
1540176945891 <= {"id":"25"}
1540176945892 <= {"id":"26"}
1540176945895 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540176945895 => {"id":"27","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["/Users/liaoyuhao/learn_widget/lib/drag_playground.dart"]}}}
1540176945927 <= {"id":"27"}
1540176945966 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540176946108 => {"id":"28","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/learn_widget/lib/drag_playground.dart","offset":7038,"length":0},"clientRequestTime":1540176946108}
1540176946109 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540176946119 <= {"id":"28","result":{"assists":[]}}
1540176946123 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540176952451 => {"id":"29","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/learn_widget/lib/drag_playground.dart","offset":6990,"length":0},"clientRequestTime":1540176952451}
1540176952455 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540176952477 <= {"id":"29","result":{"assists":[]}}
1540176952489 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540176955846 => {"id":"30","method":"edit.getAssists","params":{"file":"/Users/liaoyuhao/learn_widget/lib/drag_playground.dart","offset":6849,"length":0},"clientRequestTime":1540176955845}
1540176955848 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540176955860 <= {"id":"30","result":{"assists":[]}}
1540176955869 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540176956876 => {"id":"31","method":"analysis.updateContent","params":{"files":{"/Users/liaoyuhao/learn_widget/lib/drag_playground.dart":{"type":"add","content":"import 'dart:collection';\n\nimport '
1540176956887 <= {"id":"31","result":{}}
1540176956887 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1540176956913 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/liaoyuhao/learn_widget/lib/drag_playground.dart","stackTrace":"Exception: Element not found in sum
```
```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/liaoyuhao/learn_widget/lib/drag_playground.dart
Exception: Element not found in summary: package:flutter/src/gestures/multidrag.dart

**Comment by stereotype441** [comment] 2018-10-25 13:28
Duplicate of #34555

**Closed by stereotype441** 2018-10-25 13:28 UTC
Labels: area-analyzer
