### ISSUE TITLE
Analysis server crash: "Cannot open file" while moving file

### ISSUE THREAD

**Issue by iLeafSolutionsPvtLtd** [dart-lang/sdk#44706] opened 2021-01-19 08:44 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.10.4`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-101-generic, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.10.4, server version 1.29.0, error: FileSystemException(path=/home/ileaf/YHOH.git/lib/modules/tenant/tenant_property_details/building_tab.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:193:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:213:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:68:46)
#3      FileSource.contents (package:analyzer/src/source/source_resource.dart:55:12)
#4      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:175:34)
#5      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:156:9)
#6      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:144:22)
#7      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:100:20)
<asynchronous suspension>
#8      MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:143:27)
<asynchronous suspension>
#9      _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1008:41)
<asynchronous suspension>
#10     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZonedGuarded (dart:async/zone.dart:1618:12)
#15     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:966:5)
#16     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:853:24)
#17     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:402:16)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:239:38)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
#22     runZonedGuarded (dart:async/zone.dart:1618:12)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:235:5)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163:14)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:103:26)
#26     _rootRunUnary (dart:async/zone.dart:1198:47)
#27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#38     _rootRunUnary (dart:async/zone.dart:1198:47)
#39     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#51     _rootRunUnary (dart:async/zone.dart:1198:47)
#52     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#57     _StreamController._add (dart:async/stream_controller.da...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment] 2021-01-26 22:52
Duplicate of https://github.com/dart-lang/sdk/issues/40063

**Comment by srawlins** [comment] 2021-01-26 22:53
This has been previously reported at https://github.com/dart-lang/sdk/issues/40063; please follow along there.

**Closed by srawlins** 2021-01-26 22:53 UTC
Labels: P3, analyzer-crash-report, area-analyzer
