### ISSUE TITLE
Analyzer >= 0.26.1+15 breaks reflectable

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24890] opened 2015-11-12 00:17 UTC
See https://github.com/dart-lang/source_gen/issues/67

**Comment by eernstg** [comment] 2015-11-12 09:29
Reflectable too, see https://github.com/dart-lang/code_transformers/issues/29, and Polymer, see https://github.com/dart-lang/sdk/issues/24735.

**Comment by kevmoo** [comment] 2015-12-10 20:57
@bwilkerson Any updates on this?

I have a work-around – should that be what @eernstg is using, too?

**Comment by bwilkerson** [comment] 2015-12-10 21:19
I'm confused. Does this bug still manifest after moving to analyzer version 0.27.0? I thought that fixed the problem.

**Comment by kevmoo** [comment] 2015-12-10 21:23
@bwilkerson See this branch of source_gen

https://github.com/dart-lang/source_gen/tree/brian_weird_fix

Removed the work around – many tests start to fail

**Comment by eernstg** [comment] 2015-12-10 23:50
Hi,

I've made several attempts to use a newer version of the analyzer (the
newest one that I could get pub to select without overrides was 0.26.4, but
I guess version 0.3.something-really-fresh will allow me to try out
0.27.*), and I do _not_ see the infinite loop that made us insert the
'<=0.26.1+14' constraint a while ago. So there's a lot of hope! On the
other hand, I keep getting `null` in a number of situations where we didn't
get them before; it's possible that a hint from Brian that I just noticed
in my inbox will help with that. I'll experiment some more with this
tomorrow.

On Thu, Dec 10, 2015 at 10:23 PM, Kevin Moore <notifications@github.com>
wrote:

> @bwilkerson <https://github.com/bwilkerson> See this branch of source_gen
>
> https://github.com/dart-lang/source_gen/tree/brian_weird_fix
>
> Removed the work around – many tests start to fail
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24890#issuecomment-163753395>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by bwilkerson** [comment] 2015-12-11 20:22
https://codereview.chromium.org/1486663003/

**Comment by kevmoo** [comment] 2015-12-16 23:17
I've validated the fix with `0.27.1` in `source_gen` – can close as fixed?

**Comment by eernstg** [comment] 2015-12-17 16:27
In support of this: `0.27.1` works with `reflectable` version 0.5.0 as well.

**Comment by donny-dont** [comment] 2015-12-22 06:25
I've been having problems in dogma_codegen with 0.27.1+1 where `evaluationResult` is null.

https://github.com/dogma-dart/dogma-codegen/blob/features/refactor-library-metadata/lib/src/analyzer/annotation.dart#L58

Putting the pubspec at 0.27.1 works but 0.27.1+1 fails.

**Comment by eernstg** [comment] 2015-12-22 08:18
Yes, 0.27.1+1 also breaks reflectable (the nulls from `evaluationResult` are indeed the main problem, again). We have notified the analyzer folks.

**Comment by kevmoo** [comment] 2015-12-22 17:57
`source_gen` tests pass with the latest analyzer – perhaps my tests don't push the API in the same way.

**Comment by donny-dont** [comment] 2015-12-22 17:59
@eernstg is there a separate bug? Seemed similar to this issue.

**Comment by eernstg** [comment] 2015-12-22 20:37
The issue https://github.com/dart-lang/reflectable/issues/54 tracks the `evaluationResult == null` analyzer issue as seen from reflectable. We just published 0.5.1 today which insists on analyzer 0.27.1 (because 0.27.0 and 0.27.1+1 both have this null issue).

**Comment by eernstg** [comment] 2016-01-04 16:59
Yes, https://github.com/dart-lang/reflectable/issues/54 tracks the `evaluationResult == null` issue as seen from reflectable.

**Comment by kevmoo** [comment] 2016-01-13 22:59
@donny-dont @eernstg have you tried analyzer 0.27.1+2 +

**Comment by eernstg** [comment] 2016-01-14 10:36
Hi,

yes, we tried that, and it has the same issue (constants not resolved,
reported as null). 'Messages' in https://codereview.chromium.org/1531393002/
contains more details about how it fails.

On Wed, Jan 13, 2016 at 11:59 PM, Kevin Moore <notifications@github.com>
wrote:

> @donny-dont <https://github.com/donny-dont> @eernstg
> <https://github.com/eernstg> have you tried analyzer 0.27.1+2 +
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/sdk/issues/24890#issuecomment-171464807>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by kevmoo** [comment] 2016-01-14 17:17
Updated the title to "reflect" reflectable

**Comment by mit-mit** [comment] 2016-03-01 09:15
@bwilkerson this is tagged P1 but I don't see any updates for more than a month. What is the status here!?

**Comment by eernstg** [comment] 2016-03-01 12:10
To be precise the title should indicate that there is one recent version that does not break reflectable, namely 0.27.1 (which is the one that we have been using ). E.g., 'Analyzer >0.27.1 breaks reflectable' might do. But I'm not sure it makes sense to change the title of an existing issue several times (it's difficult to understand the history when it does not match the title any more). There is also the issue https://github.com/dart-lang/reflectable/issues/54 which is directly concerned with the situation as seen from reflectable.

I just confirmed that we still get null when evaluating many constants. The symptom as of today is that we get a message in the following format for every entry point being transformed:

```[Info from Reflectable on <my-entry-point>.dart]:
Ignoring entry point <my-entry-point> that does not include the class Reflectable.```

Given that resolution is no longer completed on the `LibraryElement`s we obtain from the analyzer via `code_transformers`, we need APIs that will allow us to reliably detect when a `null` valued constant is unresolved, and to request the resolution of that unresolved constant.

**Comment by eernstg** [comment] 2016-03-02 08:46
The changes could affect `code_transformers` and/or `analyzer`. Reflectable has no access to the relevant `AnalysisContext` so in reflectable we cannot directly make calls like `context.computeLibraryElement(source)`, but `code_transformer` presumably has no access to `Source` values for libraries which are not given as assets (and neither does reflectable), so there is a need for getting those source values out of the analyzer, or being able to ask the analyzer to complete the resolution of any given `LibraryElement`.

**Comment by bwilkerson** [comment] 2016-03-02 14:59
Actually, every element knows the context in which it was created, so, given the `classElement` that has the annotation you're interested in, you could write:

    classElement.context.computeLibraryElement(classElement.library.definingCompilationUnit.source);

**Comment by mit-mit** [comment] 2016-03-02 16:32
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by eernstg** [comment] 2016-03-03 13:50
Wow, I've got something that works now!  \\o//
Testing, double-checking, etc.

**Comment by eernstg** [comment] 2016-03-04 17:41
https://codereview.chromium.org/1761423002/ uses lazy and fine-grained constant resolution based on `Resolver.computeLibraryElement`, and allows reflectable to depend on 'analyzer' ^0.27.2 rather than the single version 0.27.1. When landed, that should resolve this issue.

**Comment by eernstg** [comment] 2016-03-07 17:57
Addressed by https://github.com/dart-lang/reflectable/commit/543ad76b62681b9cb2a49c163cbefa34d4b521bd.

**Closed by eernstg** 2016-03-07 17:57 UTC
Labels: area-analyzer, P1 high, Type: bug
