### ISSUE TITLE
Fasta parser can't parse edge integer values:

### ISSUE THREAD

**Issue by nickclmb** [dart-lang/sdk#33272] opened 2018-05-30 08:47 UTC
The code like this:
```dart
class MathUtils {
  static const int MIN_VALUE = -9223372036854775808;
  static const int MAX_VALUE = 9223372036854775807;
```

with fasta parser enabled:

```dart
 _context.analysisOptions = new AnalysisOptionsImpl()
      ..useFastaParser = true;
```

produces error:
```
Caused by FormatException: Invalid radix-10 number
9223372036854775808
#0      int._throwFormatException (dart:core-patch/dart:core/integers_patch.dart:131)
#1      int._parse (dart:core-patch/dart:core/integers_patch.dart:105)
#2      int.parse (dart:core-patch/dart:core/integers_patch.dart:62)
#3      AstBuilder.handleLiteralInt (package:analyzer/src/fasta/ast_builder.dart:496:40)
#4      Parser.parseLiteralInt (package:front_end/src/fasta/parser/parser.dart:4769:14)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4342:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4295:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4107:13)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4265:15)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4107:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:4079:11)
#11     Parser.parseFieldInitializerOpt (package:front_end/src/fasta/parser/parser.dart:2740:15)
#12     Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2668:9)
#13     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3303:15)
#14     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3101:15)
#15     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1700:13)
#16     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1660:14)
#17     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:544:14)
#18     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:450:14)
#19     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:330:15)
#20     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:134:32)
#21     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:129:12)
#22     ParseDartTask.internalPerform (package:analyzer/src/task/dart.dart:3767:35)
#23     AnalysisTask._safelyPerform (package:analyzer/src/task/api/model.dart:323:9)
#24     AnalysisTask.perform (package:analyzer/src/task/api/model.dart:222:7)
#25     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:285:10)
#26     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:110:22)
#27     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:722:14)
#28     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:690:12)
```

Dart VM version: 2.0.0-dev.59.0 (Unknown timestamp) on "linux_x64"
analyzer 0.32.1
front_end 0.1.1

**Comment by askeksa-google** [comment] 2018-08-14 09:51
Duplicate of https://github.com/dart-lang/sdk/issues/33351

**Closed by askeksa-google** 2018-08-14 09:51 UTC
Labels: area-front-end
