### ISSUE TITLE
Compiled app crashes after adding an .ico as resource

### ISSUE THREAD

**Issue by normaliok** [dart-lang/sdk#46445] opened 2021-06-23 11:17 UTC
I've compiled my dart-created application with dart2compile to .exe file, but I need to change a default icon of exe file.
I'm using Resource Hacker for that, but after a new resource (icon) being added, the apllication starts to crash with error:

Loading failed: Expected little-endian ELF object.

Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "windows_x64"

**Comment by mraleph** [comment] 2021-06-24 11:53
Duplicate of #39106

**Closed by mraleph** 2021-06-24 11:53 UTC
Labels: area-vm

**Comment by mraleph** [comment] 2021-06-24 11:55
This is essentially the same problem as #39106 - executables produced by `dart2native` are not _exactly_ adhering to OS standard executable format (PE on Windows, Mach-O on Mac OS X or ELF on Linux). So editing them through any native tools is going to break them. We hope we eventually can fix this - but I can't promise any timeline here. It is not really at the top priority for us right now.
