### ISSUE TITLE
Ternary on inheritance with generic parameter cant compile

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/sdk#49553] opened 2022-07-28 16:11 UTC
Take the following setup:
```dart
/// Generic Parameters "ID"
class BaseID {}
class Xid extends BaseID {}
class Yid extends BaseID {}

/// Classes generic on the "ID"
class Base<ID extends BaseID> {
  final ID id;
  Base(this.id);
}
class X extends Base<Xid> {  X(super.id);  }
class Y extends Base<Yid> {  Y(super.id);  }

// -----------------------------------

/// This wont compile:
Base bTernary(BaseID b) => (b is Xid) ? X(b) : Y(b as Yid);
//                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// A value of type 'Object' can't be returned from the function 'bTernary' because
//   it has a return type of 'Base<BaseID>'.
//   dart[return_of_invalid_type](https://dart.dev/diagnostics/return_of_invalid_type)"

/// While this works fine:
Base bIf(BaseID b) {
  if (b is Xid) return X(b);
  return Y(b as Yid);
}
```

Found in
`Dart SDK version: 2.18.0-232.0.dev (dev) (Mon Jun 27 08:30:11 2022 -0700) on "macos_arm64"`
`Dart SDK version: 2.19.0-43.0.dev (dev) (Wed Jul 27 16:58:55 2022 -0700) on "macos_arm64"`

Might be related to https://github.com/dart-lang/sdk/issues/43759

**Comment by lrhn** [comment] 2022-07-28 19:32
This is probably working as intended.

The types of the two branches are `X`\<:`Base<Xid>`\<:`Object` and `Y`\<:`Base<Yid>`\<:`Object`. The only shared superinterface is `Object`.

That is not the nearest super-type, which is `Base<BaseID>`, but neither type has that in its superinterface hierarchy, which is what is used by the **UP**/least-upper-bound computation.

That's doubly incompetent of our type system when the context type of the conditional expression is `Base<BaseID>` already, but I think that's how it's currently specified.

**Comment by ltOgt** [comment] 2022-07-29 07:22
Is the issue that the `bTernary` is a single expression that has to agree on one type, and the `bIf` are two separate expressions, so it's fine?

But then i am still wondering why the two branches in `bIf` can still be matched with the return type `Base<BaseID>`.

Why is it not `X`<:`Base<Xid>`<:`Base<BaseID>`<:`Object`?


To me `bIf` and `bTernary` are conceptually equivalent, so its quite unexpected that the one does not work.

**Comment by eernstg** [comment] 2022-07-29 09:26
This is indeed working as specified, and `bIf` works differently from `bTernary` because the former checks two subtype relationships separately, and the latter computes the least upper bound (OK, it's not "least", so we call it the 'standard upper bound' now, I'll just say 'upper bound' here), and then checks the subtype relationship. And the upper bound isn't tight enough to succeed.

The standard upper bound algorithm uses structural rules whenever they can be applied directly. For instance, the upper bound of `Base<Xid>` and `Base<Yid>` is `Base<BaseId>`, and that's computed by noting that we have two types of the form `Base<...>`, and then using recursion to find the upper bound of the type arguments.

However, the original algorithm does not use recursion into the structure of the type. I believe it was because it had been shown at the time that the Java algorithm for the same thing had termination problems. That old algorithm is specified [here](https://github.com/dart-lang/language/blob/cbca2be5e10d64b23cadaeb3acd489d3b3e1d994/specification/dartLangSpec.tex#L22129), and the [new algorithm](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#upper-bounds) uses the old algorithm as a catch-all rule at the very end. In particular, when the operands are _subtypes_ of `Base<Xid>` and `Base<Yid>`, the recursive rule doesn't apply directly, and in that case the old rule kicks in (and the old rule does not know about the new rules, it relies exclusively on the superinterface graph).

It would have been very, very nice to have more optimal results from this algorithm in cases like this, but it is a breaking change, and it is likely to have very subtle effects in a large number of situations. So it wasn't done at Dart 2.0 when the new rules were introduced (that is, the old rule is still used as the last case in the new rules).

We've had many proposals about how to tweak the treatment of upper bounds, and about the typing (and inference) of the conditional operator, but there is no good solution on the table.

Yet. ;-)

**Comment by lrhn** [comment] 2022-07-30 10:54
I'll close this issue, and defer to the language repo issues for improving LUB and conditional expressions.

**Closed** 2022-07-30 10:55 UTC
Labels: closed-as-intended
