### ISSUE TITLE
http: on redirect, headers are copied to new request

### ISSUE THREAD

**Issue by fdietze** [dart-lang/sdk#45410] opened 2021-03-22 13:33 UTC
On a HTTP 302 redirect, the headers of the original request are copied over to the new request.
AFAIK, copying headers in this case is wrong.

https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/http_impl.dart#L2493-L2498

This is causing problems in my application. My url works well with `curl -L` but does not with `dart http`.

**Comment by aam** [comment] 2021-03-22 15:32
Thanks for the report.
What kind of request is being redirected (GET/HEAD/...)?
My understanding is that new request should point to new URL but otherwise be identical to the original one.
Can you provide a little more details as to why you think copying headers is wrong?

**Comment by fdietze** [comment] 2021-03-22 15:51
In my case, it's a GET request.

The first http server checks my `Authorization` header and generates a pre-signed url to download a file from another host. When the `Authorization` header is also attached to the second request, the second request fails, because two auth mechanisms are provided at the same time.

It works fine with `curl` and `http`, but not with the dart http client. I tested it with 303 and 302 HTTP status codes.
```
$ http -v GET https://myfirsthost/file.mp3 "Authorization:Bearer $TOKEN" --follow
GET /file.mp3 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Bearer TOKEN
Connection: keep-alive
Host: myfirsthost
User-Agent: HTTPie/2.4.0



HTTP/1.1 303 See Other
Apigw-Requestid: xxxxxxxxxxx
Connection: keep-alive
Content-Length: 0
Date: Mon, 22 Mar 2021 15:43:30 GMT
location: https://mysecondhost/file.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[.......]&X-Amz-SignedHeaders=host



GET /file.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[......]&X-Amz-SignedHeaders=host HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: mysecondhost
User-Agent: HTTPie/2.4.0



HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 9088353
Content-Type: audio/mp3
Date: Mon, 22 Mar 2021 15:43:31 GMT
ETag: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Last-Modified: Fri, 19 Mar 2021 12:25:30 GMT
Server: AmazonS3
x-amz-id-2: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
x-amz-request-id: xxxxxxxxxxxxxxxx
x-amz-server-side-encryption: aws:kms
x-amz-server-side-encryption-aws-kms-key-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
```

**Comment by aam** [comment] 2021-03-22 16:32
Aha, thanks for the details. It looks like "Authorization" header is a special case that is handled differently by different runtimes/languages(for example see https://developers.nest.com/guides/api/how-to-handle-redirects).
Perhaps we should consider doing the same in Dart.

Meanwhile, Dart developers have a control over whether redirect are automatically followed via https://api.flutter.dev/flutter/dart-io/HttpClientRequest/followRedirects.html, if redirects are followed manually developer can strip out headers as needed.

**Comment by fdietze** [comment] 2021-03-23 10:43
Alright, the special case for 'Authorization' explains it.
Yes, following the redirect manually works if you have control over the http requests. But with libraries that use http internally, like [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager), it becomes a bit more tricky.

**Comment by RCSandberg** [comment] 2021-05-21 11:20
Hi, I'd like to follow up on this as well. I seems to have run into the same(?) issue, but with a 307.

Can you confirm whether or not this **seems** to be the case?

I'm making a GET request to an endpoint that requires Authentication header to be set.
From that endpoint, I get a 307 which should redirect me to a new uri , which should give me a 200.
This has been verified with Postman and works as intended.

The uri I'm getting redirected to does not required an authentication header to be set and is on a new hostname. I have been able to figure out that the issue seems to have to do with that.

There is a setting in Postman (that is found under the Settings tab) that is disabled by default:

> Follow Authorization header
> Retain authorization header when a redirect happens to a different hostname.

When I enable that feature in Postman, I get the same problem as I do with HttpClient when running `httpClient.send()`

**Comment by brianquinlan** [comment] 2022-01-27 22:35
Fixed in https://dart-review.googlesource.com/c/sdk/+/229947

**Closed by brianquinlan** 2022-01-27 22:35 UTC
Labels: area-vm, library-_http

**Comment by Hixie** [comment] 2022-01-27 23:55
https://github.com/dart-lang/sdk/issues/47246 also seems to be a duplicate of this?

**Comment by kevmoo** [comment] 2022-01-28 00:00
Fixed in https://github.com/dart-lang/sdk/commit/57db739be0ad4629079bfa94840064f615d35abc

**Comment by AlexanderFarkas** [comment] 2022-02-04 06:51
For some reason, Authorization header gets erased even on the same domain 307 redirect.
