### ISSUE TITLE
Analyzer should warn when A<void> is assign to A<?>

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#34680] opened 2018-10-04 20:01 UTC
On sdk>=2.0 there should be a hint/error for things like:

```dart
void main() {
  List<String> l1 = List<void>(); // should be an error because it's an error at runtime
  List<String> l2 = <void>[]; // strangely there's already an error today
  List<dynamic> l3 = List<void>(); // OK for dynamic
}
```

**Comment by matanlurey** [comment] 2018-10-04 20:04
These are downcasts, and are legal in the language.

Otherwise, this is duplicate of https://github.com/dart-lang/sdk/issues/33372.

**Closed by matanlurey** 2018-10-04 20:04 UTC
Labels: closed-duplicate

**Comment by MichaelRFairhurst** [comment] 2018-10-04 21:09
Also will drop in to say that this was intended to be illegal by dart 2 with "voidness preservation" (basically a form of illegal implicit downcasts that was on by default but limited to this case). Unfortunately we didn't have time to land it, but it may get a [lint](https://github.com/dart-lang/linter/issues/1124) or be in dart 3.
