### ISSUE TITLE
 Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception RangeError: Value not in range: 1

### ISSUE THREAD

**Issue by ericstephen** [dart-lang/sdk#38190] opened 2019-09-04 12:38 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 3440x1440, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:389:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1370:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4239:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3715:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#23     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3259:15)
#24     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#25     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#26     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#27     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#28     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#29     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#30     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#31     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#32     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#33     _File._parse (package:analyzer/src/services/available_declarations.dart:1656:23)
#34     _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#35     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:642:10)
#36     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:508:7)
#37     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#40     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#41     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#42     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#43     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _runZoned (dart:async/zone.dart:1516:10)
#47     runZoned (dart:async/zone.dart:1463:12)
#48     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#49     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#50     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#51     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#52     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#53     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#54     new F...
```

For additional log information, please append the contents of
file:///private/var/folders/09/h4pxrgld0d960kbvdj0tbwkr160kvq/T/report.txt.

**Comment by srawlins** [comment] 2019-09-05 03:54
Thanks for reporting this issue! It's been previously reported at #37114, so please follow along there.

**Comment by srawlins** [comment] 2019-09-05 03:54
Duplicate of #37114

**Closed by srawlins** 2019-09-05 03:54 UTC
Labels: area-analyzer
