### ISSUE TITLE
Dartium is not at feature-parity with Chrome for ES6 Harmony

### ISSUE THREAD

**Issue by akdor1154** [dart-lang/sdk#25299] opened 2015-12-21 01:11 UTC
Hi,
I'm writing an extension to use with a dart app, so that it can communicate with a native application. I want to use ES6 classes in the extension, as they are now available in stable Chrome. However, this seems to not be implemented in Dartium (even with Enable Harmony in about:flags). Test case:

    eval('
        "use strict"; \
        class Test { constructor() { console.log("hello"); } }; \
        new Test(); \
    ');

It would be great if Dartium could be brought up to speed; as I said, this is entirely supported in stable Chrome.

EDIT: looks like Dartium stable is based on Chrome 39, can I assume this bug will disappear when a new enough Dartium lands?

Cheers
Jarrad

**Comment by zoechi** [comment] 2015-12-21 08:42
An updated Dartium was announced for 1.14. 
Some recent activity https://groups.google.com/a/dartlang.org/forum/?nomobile=true#!topic/reviews/z4bsChAG5yA

**Comment by alan-knight** [comment] 2015-12-21 18:12
Duplicate of 24218

**Closed by alan-knight** 2015-12-21 18:12 UTC
