### ISSUE TITLE
As of dart SDK 2.12, "double" type doesn't append “0” at tenths place

### ISSUE THREAD

**Issue by Tapaswi846580** [dart-lang/sdk#45580] opened 2021-04-03 04:34 UTC
After upgrading to flutter 2.0 my application suddenly crashes, after debugging I found that issue is with ```double``` type.

### Description of the issue: 
Apparently after upgrading to flutter 2.0 (which also upgrades dart SDK) ```double``` type doesn't append ```0``` at **_tenths_** place , if there is only ```0``` to the right of the decimal point.  _Also its **runtime type changes to ```int```**._
It works perfectly fine if there is nonzero number to the right of the decimal point.

### ```double``` type with dart SDK 2.12.2 (working unexpectedly):

<img width="700" alt="dart_2 12 2" src="https://user-images.githubusercontent.com/35557794/113442458-b6f61b80-940d-11eb-989b-115d8623af5d.png">

As seen in the above snapshot (dart SDK: 2.12.2 & flutter 2.0.3) variable ```x``` is of ```double``` type but it changes to ```int```, while variable ```y``` is working properly.

### ```double``` type with dart SDK 2.10.5  (working as expected):

<img width="700" alt="dart_2 10 5" src="https://user-images.githubusercontent.com/35557794/113442646-0c322d00-940e-11eb-9283-d508fd5432fd.png">

### I have already tried using double.parse() method, but in the end it gives me the same output (integer). If this is a genuine issue please assign me to fix this issue, otherwise if there's any work around please suggest one.

__Originally posted by @Tapaswi846580 in https://github.com/flutter/flutter/issues/79660__

**Comment by rakudrama** [comment] 2021-04-03 04:59
This is one of the differences between numbers on the web and numbers on the native VM.
On the VM (your SDK 2.10.5 results), `3` and `3.0` are objects with different types.
On the web (dartpad), compiled to JavaScript, Dart uses JavaScript numbers or both `int` and `double`.
In JavaScript `3` and `3.0` are the same JavaScript `Number`, so the result of `$x` is the same.

It is best not to expect a double has any particular number of fractional decimal digits. Sometimes there are many more than you might expect, e.g. `print(3.08 - 0.07)` prints as `3.0100000000000002` due to floating-point arithmetic.
It is not the same value as `3.01`. See https://floating-point-gui.de/ for more detailed explanations.

**Comment by Tapaswi846580** [comment] 2021-04-03 16:14
Thanks for the clarification. As you said, problem lies with javascript, I wrote a code in flutter and executed on both mobile and web platform. 

### Works perfectly fine on mobile platform: 

<img width="700" alt="mobile" src="https://user-images.githubusercontent.com/35557794/113484086-2c242800-94c4-11eb-8b04-33ad2976b743.png">


### But on web, due to javascript problem persists

<img width="700" alt="web" src="https://user-images.githubusercontent.com/35557794/113484139-5d9cf380-94c4-11eb-8090-ef5c9b24556b.png">

If there is any solution to this, please provide one or else I have to make a workaround by using ```toStringAsFixed(1)``` method.
Thanks for the clarification.

**Comment by mraleph** [comment] 2021-04-05 13:54
I am going to close this as intended (but feel free to continue discussion on the issue). 

@rakudrama @sigmundch have we ever considered using static type to produce more consistent results for `toString` between VM and native (so that `doubleValue.toString` actually returns something with a `.`)?

**Closed** 2021-04-05 13:54 UTC
Labels: area-web, closed-as-intended, type-question

**Comment by Tapaswi846580** [comment] 2021-04-05 15:34
Thanks for the reply, please do continue the discussion, if there's any update on this. Thanks again.

**Comment by rakudrama** [comment] 2021-04-06 22:32
@mraleph I have thought about using the static type more, but I think it is a bad idea to introduce an inconsistency _within_ an implementation _in addition to_ the inconsistency _between_ implementations. The original inconsistency is not removed if the static type is, e.g. `num`. If `toString()` is sensitive to the static type, then so should interpolation (as in the initial example). This implies it is not possible to implement interpolation as an instance of a general mechanism (like back-tick in JavaScript).

My thoughts on using `double` values in the UI is as follows:

One should not rely on the default `toString()` of a double when presenting the value to a user.
The UI should always choose the format suitable for the context.

Consider
```dart
double d1 = 3.1;
double d2 = 3.8 - 0.7;  //  3.0999999999999996
double d3 = d2 - d1;    //  -4.440892098500626e-16
```
`d1` and `d2` do not have the same value due to how floating point arithmetic works.
`3.0999999999999996` might be confusing to the user, and `-4.440892098500626e-16` might be even more confusing.
The difference between `3.0` and `3` is less of a problem than the general problem of working with floating point (`double`) numbers.

The [documentation for `double.toString()`](https://api.dart.dev/stable/2.12.0/dart-core/double/toString.html) makes no guarantees as whether the result contains a '`.`'). `double.toString()` is good for is the documented invariant: `d == double.parse(d.toString())`. This allows you to store `double` numbers in a text format without additional rounding errors.

When presenting numbers to the user, there are additional concerns. Should the number be formatted with separators? What are the appropriate separator and their positions? What are the digits of the language of the user?
These can be addressed by using [`NumberFormat`](https://pub.dev/documentation/intl/latest/intl/NumberFormat-class.html).

If the rounding and truncation errors built into `double` arithmetic are a problem, one might use a data type that allows these errors to be better controlled, e.g. a[`Decimal`](https://pub.dev/documentation/decimal/latest/decimal/Decimal-class.html) package.
