### ISSUE TITLE
Spuriously disappearing extension

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#39264] opened 2019-11-06 15:04 UTC
Cf. #39262. The common front end seems to consider the existence of an extension as a conflict when it is both declared in the current library and also imported, and the extension is then considered as non-existing (not duplicated).

**Comment by johnniwinther** [comment] 2019-11-08 20:15
Duplicate of #39160. Fix in https://dart-review.googlesource.com/c/sdk/+/123523

**Closed by johnniwinther** 2019-11-08 20:15 UTC
Labels: area-front-end, type-bug
