### ISSUE TITLE
Partial application to type arguments needs to be specified

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#32533] opened 2018-03-14 16:01 UTC
Issue #31665 contains some discussion on the feature and some restrictions about where the partial application/specialization will be used.

However, the CFE, the VM and DDC have different interpretations of the feature and expect different sets of restrictions.

We need an informal specification at the very least to proceed with #32534.

**Comment by kmillikin** [comment] 2018-03-15 12:51
Duplicate of #31665.

**Closed by kmillikin** 2018-03-15 12:51 UTC
