### ISSUE TITLE
NNBD Migration tool detect unmigrated libraries within my package

### ISSUE THREAD

**Issue by letsar** [dart-lang/sdk#45478] opened 2021-03-25 21:51 UTC
I'm trying to migrate the feature/revival branch of flutter_slidable (available [here](https://github.com/letsar/flutter_slidable/tree/feature/revival)).

When I run `dart migrate`, I have this error, but I don't understand why:

```text
Bad state: Error: package has unmigrated dependencies.

Before migrating your package, we recommend ensuring that every library it
imports (either directly or indirectly) has been migrated to null safety, so
that you will be able to run your unit tests in sound null checking mode.  You
are currently importing the following non-null-safe libraries:

  package:flutter_slidable/src/controller.dart
  package:flutter_slidable/src/dismissal.dart
  package:flutter_slidable/src/dismissible_pane.dart
  package:flutter_slidable/src/dismissible_pane_motions.dart
  package:flutter_slidable/src/flex_entrance_transition.dart
  package:flutter_slidable/src/flex_exit_transition.dart
  package:flutter_slidable/src/gesture_detector.dart
  package:flutter_slidable/src/notifications.dart
  package:flutter_slidable/src/scrolling_behavior.dart
  package:flutter_slidable/src/slidable.dart

Please upgrade the packages containing these libraries to null safe versions
before continuing.  To see what null safe package versions are available, run
the following command: `dart pub outdated --mode=null-safety`.
```

All these libraries are the ones I'm trying to migrate, so I'm very confused.

**Comment by devoncarew** [comment] 2021-03-28 23:55
cc @stereotype441

**Comment by stereotype441** [comment] 2021-03-30 13:20
Hi @letsar, thanks for the bug report!  I cloned flutter_slidable, checked out https://github.com/letsar/flutter_slidable/commit/c7ea39bf7fb2ded416f05b79472da7eb35d489b9, and tried running the following commands from the root directory of the project using Flutter 2.0.0:
```
flutter pub get
dart migrate
```
I wasn't able to reproduce the errors you were seeing.  I can think of a few things that might be helpful in figuring out what's going on:
- Which operating system are you using?
- What's the output when you run `flutter --version`?
- What are the contents of your `.dart_tool/package_config.json` file?
- What's the precise set of commands you executed to try to perform the migration?
- Which commit of `flutter_slidable` did you start with?

Thanks!

**Comment by letsar** [comment] 2021-03-30 20:05
Hi @stereotype441, thank you for taking a look at this.

You'll find here the information you asked for:

<details>
  <summary>Which operating system are you using?</summary>

```
Microsoft Windows [version 10.0.19041.867], locale fr-FR)
```


</details>

<details>
  <summary>What's the output when you run flutter --version?</summary>

```
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (3 weeks ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1
```

</details>

<details>
  <summary>What are the contents of your .dart_tool/package_config.json file?</summary>

```json
{
  "configVersion": 2,
  "packages": [
    {
      "name": "_fe_analyzer_shared",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-19.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "analyzer",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-1.3.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "args",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/args-2.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "async",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/async-2.5.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "boolean_selector",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "characters",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "charcode",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/charcode-1.2.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "cli_util",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/cli_util-0.3.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "clock",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/clock-1.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "collection",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "convert",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/convert-3.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "coverage",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/coverage-1.0.2",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "crypto",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/crypto-3.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "fake_async",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/fake_async-1.2.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "file",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/file-6.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "flutter",
      "rootUri": "file:///D:/Dev/flutter/packages/flutter",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "flutter_test",
      "rootUri": "file:///D:/Dev/flutter/packages/flutter_test",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "glob",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/glob-2.0.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "http_multi_server",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/http_multi_server-3.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "http_parser",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/http_parser-4.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "io",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/io-1.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "js",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.3",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "logging",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/logging-1.0.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "matcher",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.10",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "meta",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "mime",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/mime-1.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "mocktail",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/mocktail-0.1.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "node_preamble",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/node_preamble-1.4.13",
      "packageUri": "lib/",
      "languageVersion": "1.24"
    },
    {
      "name": "package_config",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/package_config-2.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "path",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/path-1.8.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "pedantic",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/pedantic-1.11.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "pool",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/pool-1.5.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "pub_semver",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/pub_semver-2.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "shelf",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/shelf-1.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "shelf_packages_handler",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/shelf_packages_handler-3.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "shelf_static",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/shelf_static-1.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "shelf_web_socket",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/shelf_web_socket-1.0.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "sky_engine",
      "rootUri": "file:///D:/Dev/flutter/bin/cache/pkg/sky_engine",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "source_map_stack_trace",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/source_map_stack_trace-2.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "source_maps",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/source_maps-0.10.10",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "source_span",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "stack_trace",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.10.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "stream_channel",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "string_scanner",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "term_glyph",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.2.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "test",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/test-1.16.5",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "test_api",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/test_api-0.2.19",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "test_core",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/test_core-0.3.15",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "typed_data",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "vector_math",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "vm_service",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/vm_service-6.1.0+1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "watcher",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/watcher-1.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "web_socket_channel",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/web_socket_channel-2.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "webkit_inspection_protocol",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/webkit_inspection_protocol-1.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "yaml",
      "rootUri": "file:///D:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/yaml-3.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "flutter_slidable",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.7"
    }
  ],
  "generated": "2021-03-30T19:52:26.715241Z",
  "generator": "pub",
  "generatorVersion": "2.12.1"
}
```

</details>

<details>
  <summary>What's the precise set of commands you executed to try to perform the migration?</summary>

```
flutter pub get
dart migrate
```

</details>

<details>
  <summary>Which commit of flutter_slidable did you start with?</summary>

```
The same you mentioned: https://github.com/letsar/flutter_slidable/commit/c7ea39bf7fb2ded416f05b79472da7eb35d489b9
```

</details>

I hope this will help you to understand where is the issue

**Comment by stereotype441** [comment] 2021-03-31 16:34
Hi @letsar, I'm very sorry, but I've tried reproducing your issue on a Windows computer and I'm still having no luck.  I think your best bet would be to try running migration with the flag `--skip-import-check`.  This will suppress the error messages you're seeing and hopefully allow migration to proceed.

I'll leave this issue open in case others run into the same problem, and hopefully we can gather more clues about what might be going wrong.

**Comment by letsar** [comment] 2021-04-05 09:32
Hi @stereotype441, I tried with --skip-import check, but I have the following errors:
```text
  error • Future isn't a type at lib\src\controller.dart:200:3 • (not_a_type)
  error • Future isn't a type at lib\src\controller.dart:214:3 • (not_a_type)
  error • Future isn't a type at lib\src\controller.dart:229:3 • (not_a_type)
  error • Future isn't a type at lib\src\controller.dart:248:3 • (not_a_type)
  error • Future isn't a type at lib\src\controller.dart:267:3 • (not_a_type)
  error • Future isn't a type at lib\src\controller.dart:292:3 • (not_a_type)
  error • Future isn't a type at lib\src\dismissible_pane.dart:15:34 • (not_a_type)
  error • Future isn't a type at lib\src\dismissible_pane.dart:130:3 • (not_a_type)
  error • A value of type 'dynamic' can't be assigned to a variable of type 'bool' at lib\src\dismissible_pane.dart:138:22 • (invalid_assignment)
  error • Future isn't a type at test\action_pane_motions_test.dart:69:1 • (not_a_type)
  error • Future isn't a type at test\dismissible_pane_test.dart:187:7 • (not_a_type)
  error • Future isn't a type at test\dismissible_pane_test.dart:243:7 • (not_a_type)
  error • Missing type arguments for calling generic function type 'VerificationResult Function<T>(T Function())' at test\scrolling_behavior_test.dart:65:7 • (implicit_dynamic_invoke)
  error • Missing type arguments for calling generic function type 'VerificationResult Function<T>(T Function())' at test\scrolling_behavior_test.dart:74:7 • (implicit_dynamic_invoke)
  error • Missing type arguments for calling generic function type 'VerificationResult Function<T>(T Function())' at test\scrolling_behavior_test.dart:105:7 • (implicit_dynamic_invoke)
  error • Missing type arguments for calling generic function type 'VerificationResult Function<T>(T Function())' at test\scrolling_behavior_test.dart:114:7 • (implicit_dynamic_invoke)
  error • Missing type arguments for calling generic function type 'VerificationResult Function<T>(T Function())' at test\scrolling_behavior_test.dart:144:7 • (implicit_dynamic_invoke)
  error • Missing type arguments for calling generic function type 'VerificationResult Function<T>(T Function())' at test\scrolling_behavior_test.dart:153:7 • (implicit_dynamic_invoke)
  error • Missing type arguments for calling generic function type 'VerificationResult Function<T>(T Function())' at test\scrolling_behavior_test.dart:184:7 • (implicit_dynamic_invoke)
```

Looks like I will have to migrate manually :/

**Comment by sperochon** [comment] 2021-04-23 19:47
Hello @stereotype441 (and @letsar )

Just to let you know that I've got the same issue (Android Studio, Mac OS) on a private package of my own. But I found the problem and the fix ;-) so I post it here if it can help others...

```
...
You are currently importing the following non-null-safe libraries:

  package:private_package/src/widgets/BackgroundWidget.dart
...
```

I have checked that I have no "/lib/" in path imports.

The strange thing is that even if I remove all the content of the BackgroundWidget.dart file (cmd-a,cmd-x), the issue is still here!?
It works fine when I comment the line
`export 'src/widgets/BackgroundWidget.dart';`
in the main file of my package.

Flutter cleans, close/reopen Android Studio does not help.

After trying lots of things, I have found the problem:
the filename is
`Back**G**roundWidget.dart`
and the class name is
`Back**g**roundWidget`

If I change it to
`Back**g**roundWidget.dart`
it's working fine.

My file system is NOT case-sensitive.

I already know that I have to rename my files to follow the rule:
https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores
That's what I'm doing on others projects but there are still some files waiting for renaming in this one... I know what I'm going to do right now ;-)


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)


Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (7 days ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

**Comment by perojas3** [comment] 2021-11-12 20:23
Yeah, same issue here.

**Comment by tonytang0114** [comment] 2021-12-10 15:47
same issue here on flutter 2.8.0 version

**Comment by d3xt3r2909** [comment] 2022-01-09 23:18
same thing

**Comment by devmgs** [comment] 2022-01-13 04:16
Same here. It is pointing to the dart files within my app.  (Android Studio + Mac OS)

Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

**Comment by devmgs** [comment] 2022-01-13 04:30
Found issue for me.

1) File names which are in camelcase : starts with lowercase the there is a Uppercase for every word was crearting problem. Once i followed standards it started to work.

example : refractored `appTheme.dart` to `app_theme.dart`

**Comment by mshenawy22** [comment] 2022-01-18 10:38
Same issue here

**Comment by dcoleyoung** [comment] 2023-09-06 00:35
I've come to this now - at a loss to figure it out so far.  I've checked the imports and my modules, even main.dart are listed as an imported non-null safe library.  (I know it's not null safe, which is why I'm running the dang migration tool :/)

**Comment by dcoleyoung** [comment] 2023-09-06 16:09
I've tried this on the basic counter flutter app created in android studio and this error comes up trying to migrate main.dart

**Comment by stereotype441** [comment] 2023-11-21 21:56
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.

**Closed by stereotype441** 2023-11-21 21:56 UTC
Labels: P2, area-migration, nnbd-migration-not-affecting-google3
