### ISSUE TITLE
Dart analyzer crashes reliably working with macros.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#55596] opened 2024-04-29 17:07 UTC
Commit: https://github.com/polina-c/disposable_macro/commit/becf1a162f46e6f1dca84b9d390b69a536a82aaf

```
Flutter 3.22.0-18.0.pre.54 • channel [user-branch] • unknown source
Framework • revision 257df5ebfc (9 hours ago) • 2024-04-29 11:26:19 +0300
Engine • revision 752b146df7
Tools • Dart 3.5.0 (build 3.5.0-109.0.dev) • DevTools 2.35.0-dev.16
```

Add these settings to your user settings of vs_code:
```
    "dart.analyzerLogFile": "logs/dart.analyzer.log",
    "dart.analyzerInstrumentationLogFile": "logs/dart.analyzerInstrumentation.log",
```

Steps to repro:
1. Clone the repo
2. Run `flutter pub get` in both folders: `disposable_macro` and `usage_example`
3. Open the repo folder in vs_code
4. Find analyzer crashing and logs.
5. Remove logs and select command `Developer: Reload Window` to see the crash repeated

**Comment by polina-c** [comment] 2024-04-29 17:08
[Archive.zip](https://github.com/dart-lang/sdk/files/15152435/Archive.zip)

**Comment by bwilkerson** [comment] 2024-04-29 18:02
@scheglov

**Comment by jakemac53** [comment] 2024-04-29 18:19
Note that for me I wasn't able to reproduce the analyzer crash - I got a different error related to us not currently allowing you to augment constructor bodies if there was one previously (related to https://github.com/dart-lang/language/issues/3554).

I am going to prioritize resolving that issue so that we can allow augmenting constructor bodies without error.

**Comment by scheglov** [comment] 2024-04-30 17:28
I'd like to know a few more details. Do you have to have both the macro implementation package, and the package where it is used - as directories in IDE? But not open the macro implementation file? Or macro implementation in an external directory, not included in IDE, and open only the package where the macro is used?

**Comment by jakemac53** [comment] 2024-04-30 17:39
In my case, the macro package and package using it were in sibling directories, and I had the shared root directory open. 

You can reproduce this by cloning the example repo @polina-c shared above, opening up the entire repo in VsCode (or probably intellij), and then opening up `disposable_macro/test/disposable_test.dart`.

If you then open up `disposable_macro/lib/src/disposable_macro.dart`, and restart the analysis server, it will work.

**Comment by scheglov** [comment] 2024-04-30 18:15
I can reproduce this without using any IDE.
Which is always much better :-)
```
scheglov@scheglov-macbookpro4:~/dart/2024-04-30/disposable_macro/usage_example (main)$
scheglov@scheglov-macbookpro4:~/dart/2024-04-30/disposable_macro (main)$ dart analyze .
Analyzing ....
Unhandled exception:
Invalid argument(s): Attempted to register a macro executor factory for library package:disposable_macro/src/disposable_macro.dart which already has one assigned.
#0      MultiMacroExecutor.registerExecutorFactory (package:_macros/src/executor/multi_executor.dart:44:9)
#1      new KernelBundleMacroExecutor (package:analyzer/src/summary2/macro.dart:101:46)
#2      KernelMacroSupport.add (package:analyzer/src/summary2/macro.dart:147:26)
#3      LinkedElementFactory.addKernelMacroBundle (package:analyzer/src/summary2/linked_element_factory.dart:89:18)
#4      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:254:24)
<asynchronous suspension>
#5      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:154:9)
<asynchronous suspension>
#6      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:264:7)
<asynchronous suspension>
#7      PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:50:14)
<asynchronous suspension>
#8      LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:262:5)
<asynchronous suspension>
#9      AnalysisDriver._produceErrors (package:analyzer/src/dart/analysis/driver.dart:1953:5)
<asynchronous suspension>
#10     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:7)
<asynchronous suspension>
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2433:7)
<asynchronous suspension>
Bad state: The analysis server crashed unexpectedly

The analysis server shut down unexpectedly.
Please report this at dartbug.com.
```

**Comment by scheglov** [comment] 2024-04-30 18:26
The issue is that we have single `MultiMacroExecutor` instance, and every time when we load a summary bundle with macros, we try to register corresponding macros with kernel bytes. Which raises the question - should we have separate `MultiMacroExecutor` instances? @jakemac53

**Comment by jakemac53** [comment] 2024-04-30 21:03
It does seem to me like each analysis context should have its own MultiMacroExecutor instance? They can have different sources right?

**Comment by scheglov** [comment] 2024-04-30 21:15
Yes, this seems right to me.
I was checking if you know a reason why this would be wrong, e.g. fixed ports, or any other unique resources.
If no obvious reasons for this to fail, I will continue pushing the implementation :-)

**Comment by jakemac53** [comment] 2024-04-30 21:28
> If no obvious reasons for this to fail, I will continue pushing the implementation :-)

SGTM, the downside is that we will run macros multiple times on the same code potentially, but this is no different really than re-analyzing the same sources, which I think we are also doing in this case?

**Comment by scheglov** [comment] 2024-04-30 22:12
Not so much re-analyzing, because we can reuse summaries and kernels between analysis context via `ByteStore`, but we have separate copies of `LibraryElement`s for the same URIs. For the reasons that you described - potentially different set of dependencies.

We don't load elements form summaries if we don't have to. Similarly we `registerExecutorFactory()`, but I think we don't start macro implementation if we don't have to, e.g. if we already have corresponding libraries built.

**Comment by scheglov** [comment] 2024-04-30 22:20
"All problems in computer science can be solved by another level of indirection"
Instead of a single `MacroSupport` argument for `AnalysisContextCollection` we will have `MacroSupportFactory` that creates `MacroSupport` instances :-)

**Comment by scheglov** [comment] 2024-04-30 22:40
```console
/Users/scheglov/dart/2024-04-30/disposable_macro
/Users/scheglov/dart/2024-04-30/disposable_macro/usage_example
[libraries: {package:disposable_macro/src/disposable_macro.dart}]
/Users/scheglov/dart/2024-04-30/disposable_macro/disposable_macro
[libraries: {package:disposable_macro/src/disposable_macro.dart}]
[time: 8819 ms]
```

**Comment by scheglov** [comment] 2024-04-30 23:04
```console
scheglov@scheglov-macbookpro4:~/dart/2024-04-30/disposable_macro (main)$ /Users/scheglov/Source/Dart/sdk.git/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart analyze .
Analyzing ....                         2.1s

  error • disposable_macro/test/disposable_test.dart:5:1 • Macro application failed due to a bug in the macro. Try reporting the failure to the macro author. • macro_error
           - Unsupported operation: Augmenting existing constructor bodies is not allowed.
#0      ConstructorDefinitionBuilderImpl.augment (package:_macros/src/executor/builder_impls.dart:421:7)
#1      Disposable.buildDefinitionForClass (package:disposable_macro/src/disposable_macro.dart:21:15)
<asynchronous suspension>
#2      executeDefinitionMacro (package:_macros/src/executor/execute_macro.dart:181:9)
<asynchronous suspension>
#3      MacroExpansionClient._executeDefinitionsPhase (package:_macros/src/executor/client.dart:276:11)
<asynchronous suspension>
#4      MacroExpansionClient._handleMessage.<anonymous closure> (package:_macros/src/executor/client.dart:140:12)
<asynchronous suspension>
#5      MacroExpansionClient._handleMessage (package:_macros/src/executor/client.dart:118:5)
<asynchronous suspension>
 at disposable_macro/test/disposable_test.dart:5:1.
warning • disposable_macro/lib/src/disposable_macro.dart:17:11 • The value of the local variable 'library' isn't used. Try removing the variable or using it. • unused_local_variable
warning • disposable_macro/lib/src/disposable_macro.dart:18:11 • The value of the local variable 'className' isn't used. Try removing the variable or using it. • unused_local_variable
warning • usage_example/test/disposable_test.dart:2:8 • Unused import: 'package:flutter/foundation.dart'. Try removing the import directive. • unused_import
warning • usage_example/test/disposable_test.dart:4:8 • Unused import: 'package:disposable_macro/disposable_macro.dart'. Try removing the import directive. • unused_import

5 issues found.
```

**Closed** 2024-05-01 16:41 UTC
Labels: area-analyzer
