### ISSUE TITLE
dartanalyzer seems to ignore `exclude` entry

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#34053] opened 2018-08-01 15:52 UTC
Dart VM version: 2.0.0-dev.69.5 (Tue Jul 31 15:05:14 2018 +0200) on "macos_x64"

Even with the following `exclude` entry in the `analysis_options.yaml` file, the CLI analyzer still reports issues over `*.g.dart` files. No such errors are reported in WebStorm.

```yaml
analyzer:
  exclude: [build/**, test/*.g.dart]
```

```console
> dartanalyzer --fatal-warnings . # cwd: examples/ng/doc/toh-6
[11:38:36] Analyzing toh-6...
  lint • Unnecessary new keyword at test/app_po.g.dart:117:22 • unnecessary_new
  lint • Unnecessary new keyword at test/dashboard_po.g.dart:106:22 • unnecessary_new
  lint • Unnecessary new keyword at test/dashboard_po.g.dart:119:22 • unnecessary_new
  lint • Unnecessary new keyword at test/hero_search_po.g.dart:82:22 • unnecessary_new
  lint • Unnecessary new keyword at test/heroes_po.g.dart:200:22 • unnecessary_new
  lint • Unnecessary new keyword at test/heroes_po.g.dart:213:22 • unnecessary_new
  hint • The value of the field '__mouse__' isn't used at test/app_po.g.dart:73:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/dashboard_po.g.dart:63:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/hero_po.g.dart:74:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/hero_search_po.g.dart:52:19 • unused_field
  hint • The value of the field '__mouse__' isn't used at test/heroes_po.g.dart:118:19 • unused_field
6 lints and 5 hints found.
```

This is run over the following example code: https://github.com/angular-examples/toh-6

cc @kwalrath @kevmoo

**Comment by chalin** [comment] 2018-08-02 09:34
Thanks @zoechi!

Btw, using `exclude: [build/**, '**/*.g.dart']` also doesn't help (the CLI analyzer still processes `*.g.dart` files).

**Comment by zoechi** [comment] 2018-08-02 09:40
There was a mention in one of the linked issues that imported packages still are analyzed even when excluded and that `// ignore_for_package: ...` is the best way.

I have for example in `build.yaml`
```yml
      built_value_generator|built_value:
        generate_for:
          include: ["lib/src/model/**.dart", "lib/src/client/state/**.dart"]
        options:
          header: |+
            // GENERATED CODE - DO NOT MODIFY BY HAND

            // ignore_for_file: avoid_catches_without_on_clauses
            // ignore_for_file: lines_longer_than_80_chars
```

**Comment by chalin** [comment] 2018-08-02 09:42
Great idea, thanks.

**Comment by zoechi** [comment] 2018-08-02 13:11
Not sure if that affects you https://github.com/google/built_value.dart/pull/464 (initial comment) 

> because the "header" can no longer be supported.

^6.0.0

**Comment by zoechi** [comment] 2018-08-03 07:57
Related #34069

**Comment by MichaelRFairhurst** [comment] 2018-09-18 17:12
This is indeed a duplicate of #25551

@gspencergoog You need to import via a package uri instead of a relative one: https://github.com/dart-lang/dartdoc/blob/5e63ba86f8a032f40ddec88f9df4eed2e3d58a2f/lib/src/html/templates.dart#L11

> Is this just because the exclude rules are not relative to the options file, but to the package root(s)

**Closed by MichaelRFairhurst** 2018-09-18 17:12 UTC
Labels: area-analyzer, type-bug
