### ISSUE TITLE
Require that main is a method that optionally takes List<String> arguments

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#27824] opened 2016-11-15 16:42 UTC
The DartVM supports cases such as

```dart
var main = () {
  return () => print('hello');
}();
```
but there is no advantage of writing that code instead of the simpler
```dart
main() {
  print('hello');
}
```
Worse, defining main as a variable instead of a method is broken in Dart2JS.
We should statically require that 
main()
be a function that returns void and that only accepts an optional List<String> parameter as arguments.

**Comment by zoechi** [comment] 2016-11-15 18:56
That means `async` can't be used on `main()` anymore because it returns `Future`?

**Comment by floitschG** [comment] 2016-11-18 16:49
I believe the request is to disallow `main` to be a variable containing a closure. For multiple reasons we want to support different signatures of `main` but we can enforce that it must be a top-level *function* (and not just a variable).

If that's the request, then I agree.

**Comment by munificent** [comment] 2016-12-14 00:28
Duplicate of #27824.

**Closed by munificent** 2016-12-14 00:28 UTC
Labels: area-language
