### ISSUE TITLE
Dart analysis server: FATAL error: Failed to handle request: type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'

### ISSUE THREAD

**Issue by hiloliddinj** [dart-lang/sdk#37474] opened 2019-07-09 17:22 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5522156`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-183.6156.11.34.5522156, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, FATAL error: Failed to handle request: {id: 1794, method: edit.getFixes, params: {file: D:\WorkSpaces\Flutter\0_smart_home_modules\5_wifi_smart_home\wifi_smart_home\lib\model\wifi_device.dart, offset: 21}, clientRequestTime: 1562692934920}
type 'MixinDeclarationImpl' is not a subtype of type 'ClassDeclaration'
#0      FixProcessor._addFix_updateConstructor_forUninitializedFinalFields (package:analysis_server/src/services/correction/fix_internal.dart:3880:22)
<asynchronous suspension>
#1      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:468:13)
<asynchronous suspension>
#2      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#3      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:639:46)
<asynchronous suspension>
#4      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:741:14)
<asynchronous suspension>
#5      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:277:32)
<asynchronous suspension>
#6      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:380:9)
#7      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:337:45)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1500:12)
#14     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#15     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#17     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#18     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#49     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#50     _StreamController._add (dart:async/stream_controller.dart:640:7)
#51     _StreamController.add (dart:async/stream_controller.dart:586:5)
#52     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#53     _rootRunUnary (dart:async/zone.dart:1136:13)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#62     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#65     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

For additional log information, please append the contents of
file://C:\Users\User\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-09-05 13:34
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/35857, and has been fixed. Please upgrade Dart (or Flutter) to a more recent version (this bug should not occur in Dart 2.4.0 or later).

**Comment by srawlins** [comment] 2019-09-05 13:34
Duplicate of https://github.com/dart-lang/sdk/issues/35857

**Closed by srawlins** 2019-09-05 13:34 UTC
Labels: P1-High, analyzer-crash-report, area-analyzer, type-bug
