### ISSUE TITLE
dart2js crash @ a5e41681e55d1e74684

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#33332] opened 2018-06-05 05:18 UTC
Same repro as https://github.com/dart-lang/sdk/issues/33328, @efortuna 

```
[SEVERE] build_web_compilers|entrypoint on web/main.dart:
Dart2Js finished with:

web/main.dart:15:1:
Internal Error: The compiler crashed when compiling this element.
main() async {
^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.0.0-edge.a5e41681e55d1e74684bfff530218db556d77ee8), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: type 'ShadowStaticInvocation' is not a subtype of type 'Null' of 'receiver'
#0      SourceInformationBuilder.buildCall (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/io/source_information.dart)
#1      KernelSsaGraphBuilder.visitStaticInvocation (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3255:35)
#2      StaticInvocation.accept (package:kernel/ast.dart:2838:36)
#3      KernelSsaGraphBuilder.visitAwaitExpression (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:4743:18)
#4      AwaitExpression.accept (package:kernel/ast.dart:3395:36)
#5      KernelSsaGraphBuilder.visitVariableDeclaration (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:3023:24)
#6      VariableDeclaration.accept (package:kernel/ast.dart:4464:35)
#7      KernelSsaGraphBuilder.visitBlock (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1376:17)
#8      Block.accept (package:kernel/ast.dart:3758:35)
#9      KernelSsaGraphBuilder.buildGenerator (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:1076:27)
#10     KernelSsaGraphBuilder.buildFunctionNode (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:975:7)
#11     KernelSsaGraphBuilder.build.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:200:15)
#12     CompilerDiagnosticReporter.withCurrentElement (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:793:15)
#13     KernelSsaGraphBuilder.build (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/builder_kernel.dart:185:21)
#14     KernelSsaBuilder.build.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:110:22)
#15     CompilerTask.measure (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:63:44)
#16     KernelSsaBuilder.build (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:96:17)
#17     SsaBuilderTask.build (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/ssa.dart:92:21)
#18     SsaFunctionCompiler.compile (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/ssa/ssa.dart:42:29)
#19     JavaScriptBackend.codegen (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/js_backend/backend.dart:705:43)
#20     KernelCodegenWorkItem.run (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/kernel/kernel_backend_strategy.dart:80:21)
#21     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:467:70)
#22     CompilerTask.measureSubtask (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#23     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:467:32)
#24     CompilerTask.measureSubtask (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:465:28)
#26     CompilerDiagnosticReporter.withCurrentElement (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:793:15)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:463:18)
#28     EnqueuerStrategy.processWorkItem (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/enqueue.dart:495:6)
#29     CodegenEnqueuer._forEach (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:241:20)
#30     CodegenEnqueuer.forEach (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/js_backend/enqueuer.dart:256:5)
#31     Compiler.emptyQueue.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:459:16)
#32     CompilerTask.measureSubtask (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#33     Compiler.emptyQueue (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:458:14)
#34     Compiler.processQueue.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:480:7)
#35     CompilerTask.measureSubtask (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#36     Compiler.processQueue (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:477:14)
#37     Compiler.compileLoadedLibraries.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:393:9)
#38     CompilerTask.measureSubtask (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#39     Compiler.compileLoadedLibraries (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:316:16)
#40     Compiler.runInternal (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:295:5)
<asynchronous suspension>
#41     Compiler.run.<anonymous closure>.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:221:38)
#42     new Future.sync (dart:async/future.dart:222:31)
#43     Compiler.run.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:221:20)
#44     CompilerTask.measureSubtask (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#45     Compiler.run (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/compiler.dart:218:41)
#46     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///Users/kevmoo/source/github/dart/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#47     _RootZone.runUnary (dart:async/zone.dart:1381:54)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#51     Future._completeWithValue (dart:async/future_impl.dart:482:5)
#52     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:512:7)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#55     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#56     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

**Comment by vsmenon** [comment] 2018-06-05 15:02
@efortuna - can you take a look?

**Comment by efortuna** [comment] 2018-06-05 15:08
weird. I saw this error, but then it seemed to go away when I finished fixing #33328.

ohhh I remember now. Stephen talked me into a smaller change and I bet it didn't fix this part. 

Yes I will take a look. I'm 85% sure if you just apply this version of the patchset: https://dart-review.googlesource.com/c/sdk/+/58423/4 it should work. But I'll address when I get in

**Comment by vsmenon** [comment] 2018-06-05 15:16
thanks!

**Comment by jakemac53** [comment] 2018-06-05 16:44
Fwiw, this appears to be triggered by passing `--no-source-maps` as well, not sure if that is somehow defaulting to dart 2 mode by accident?

**Comment by efortuna** [comment] 2018-06-05 18:07
dart2js now runs on dart2 vm by default. as of b667be48 this should be fixed (with the CL mentioned above). 

@jakemac53 what command are you running (with --no-source-maps) where you see this error? (I just want to make sure that I've fixed the issue in all cases)

**Closed by efortuna** 2018-06-05 18:07 UTC
Labels: P1 high, area-dart2js

**Comment by jakemac53** [comment] 2018-06-05 18:20
thanks! It looks like you resolved the issue but it could be reproduced with a normal dart2js invocation that included `--no-source-maps`.
