### ISSUE TITLE
Edge VM segfaults on certain snapshots

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#23756] opened 2015-06-30 20:07 UTC
Running a VM built from d676b3fbd1c94b79344f01c1e950d979beba46ee on Linux on [this snapshot](https://gist.github.com/nex3/66e78a83068e99310423/raw/4af39973458cbc24ce203ef59f57944b8bbd9677/test.dart.snapshot) will cause it to segfault.

**Comment by fsc8000** [comment] 2015-07-01 09:17
How did you create this snapshot? Did you run with the same VM version that was used to create it?

**Comment by fsc8000** [comment] 2015-07-01 09:18
The following assertion is hit:

runtime/vm/snapshot.cc:472: error: expected: index >= max_vm_isolate_object_id_

It looks like a snapshot version mismatch.

**Comment by nex3** [comment] 2015-07-01 18:53
> How did you create this snapshot?

With pub. `pub get` automatically creates snapshots for dependencies' executables.

> Did you run with the same VM version that was used to create it?

Almost certainly not. However, the expected behavior for a snapshot mismatch is to exit with code 253 rather than to segfault.

**Comment by fsc8000** [comment] 2015-07-02 10:26
Yes, maybe the detection of the snapshot version is broken. @zanderso Can you take a look?

**Comment by zanderso** [comment] 2015-07-03 16:54
I'll be out for the next two weeks. @a-siva has been looking at the snapshot code recently.

**Comment by a-siva** [comment] 2015-07-16 15:38
This is a duplicate of https://github.com/dart-lang/sdk/issues/23834

**Closed by a-siva** 2015-07-16 15:38 UTC
Labels: Area-VM, Priority-Critical, Type-Defect
