### ISSUE TITLE
Fasta stack trace during compilation from DietListener 

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29938] opened 2017-06-20 06:54 UTC
@peter-ahe-google 
ID: 3066e78849413091718a9b42b864cdb686b22fe2
```
Unhandled exception:
type 'KernelFieldBuilder' is not a subtype of type 'ProcedureBuilder' of 'builder' where
  KernelFieldBuilder is from package:front_end/src/fasta/kernel/kernel_field_builder.dart
  Expression is from package:kernel/ast.dart
  ProcedureBuilder is from package:front_end/src/fasta/builder/procedure_builder.dart

#0      DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:400:32)
#1      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:2154:14)
#2      Parser.parseMember (package:front_end/src/fasta/parser/parser.dart:2046:11)
#3      Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:1939:15)
#4      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1071:13)
#5      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1032:14)
#6      Parser._parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:357:14)
#7      Parser.parseTopLevelDeclaration (package:front_end/src/fasta/parser/parser.dart:344:13)
#8      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:336:15)
#9      SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:146:14)
<asynchronous suspension>
#10     Loader.buildBodies (package:front_end/src/fasta/loader.dart:117:13)
<asynchronous suspension>
#11     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:282:20)
<asynchronous suspension>
#12     CompileTask.compile (package:front_end/src/fasta/fasta.dart:164:38)
<asynchronous suspension>
#13     compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#14     CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#15     _rootRun (dart:async/zone.dart:1120)
#16     _CustomZone.run (dart:async/zone.dart:1001)
#17     runZoned (dart:async/zone.dart:1467)
#18     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#19     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#20     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#21     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#22     main (file:///home/lukechurch/GitRepos/sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by peter-ahe-google** [comment] 2017-06-22 13:43
@lukechurch ID missing.

**Comment by lukechurch** [comment] 2017-06-22 13:51
@peter-ahe-google PTAL

**Comment by peter-ahe-google** [comment] 2017-06-23 12:02
This is a duplicate of #29944.

**Closed by peter-ahe-google** 2017-06-23 12:02 UTC
Labels: area-fasta
