### ISSUE TITLE
Implement semantic support for generic functions (was Generic function type arguments should be reified)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#28517] opened 2017-01-26 00:08 UTC
```dart
void test<T>() {
  print(T);
}

void main() {
  test<double>(); // prints "dynamic", should print "double".
}
```

**Comment by kevmoo** [comment] 2017-01-26 00:21
This is a known limitation of the current VM.

See notes in our announcement: http://news.dartlang.org/2016/12/dart-121-generic-method-syntax.html

**Comment by Hixie** [comment] 2017-01-26 00:30
Is there another bug tracking this? Or are you saying this will never be fixed?

We have a customer that just ran into this problem, and it was highly confusing behavior which took a while to track down.

**Comment by kevmoo** [comment] 2017-01-26 00:31
Hrm...well. It's a v2 issue. Can put it there. Sorry...

**Comment by eernstg** [comment] 2017-01-26 16:14
I just verified that the analyzer does not report a compile-time error for `print(T)`, which is a bug. In contrast, the vm is allowed to run it and use the value `dynamic`, because this is a compile-time error, and hence the runtime behavior is in principle unrestricted. You could say that this program shouldn't be executed anyway. With the compile-time error from the analyzer the potential for confusion should be significantly lower.

The relevant sentence in the [informal spec](https://gist.github.com/eernstg/4353d7b4f669745bed3a5423e04a453c) of this feature is the following (where `X` as a formal type parameter of an enclosing generic method): 'It is a compile-time error if `X` is used as a type literal (e.g., `foo(X)`), or in an expression on the form `e is X` or `e is! X`.'

I think we should change this to have area-analyzer because it is currently a bug in the analyzer, whereas the vm is actually behaving in a way which is explicitly allowed in the spec.

Come Dart 2.0 it is true that the vm will change, but that's yet another semantics: It will then have full support for generic methods, which means that the actual type arguments will be verified and should be printed, as described in the [original issue](https://github.com/dart-lang/sdk/issues/28517#issue-203260029).

I'll change the label to area-analyzer. @kevmoo, please speak up if you think we should handle it differently.

**Comment by leafpetersen** [comment] 2017-01-26 17:53
It would be good to have this warning in the analyzer, but I think the point of this issue (correct me if I'm wrong) is that we do, in fact, need to fix the fact that generic method arguments are not reified.  Do we have a separate tracking bug for that?

**Comment by kevmoo** [comment] 2017-01-26 17:57
To follow the bug intent, I believe this should stay a v2 VM bug.

We should open a separate bug for the desired spec-compliant behavior on analyzer.

**Comment by eernstg** [comment] 2017-01-27 23:22
I created a separate issue (#28543) for the analyzer.

**Comment by a-siva** [comment] 2017-03-21 21:59
We will use this issue to track implementation of generic functions semantics in the VM

**Comment by crelier** [comment] 2017-09-27 18:42
Reification of generic functions is controlled by the VM flag --reify-generic-functions.
The list of changes below implemented the feature, so I am considering this done and closing this issue.

Note however that Kernel running with the VM backend is not yet able to reify generic functions. As part of the CLs below, I have started supporting proper generation of the flow graph from the Kernel IR for reified generic functions and left many TODOs in Kernel sources. I'll help the Kernel folks to complete this work.

For documentation purpose, here are the relevant change lists:
commit db15f5d73b75b36df96ba9896813d63943b74149
Author: Régis Crelier <regis@google.com>
Date:   Wed Sep 27 17:57:41 2017 +0000

    Dart Core Lib change to support generic functions in class NoSuchMethodError.
    
    Change-Id: If7d1a8c07e4bee7ec68fede80a9d17cae0044d31
    Reviewed-on: https://dart-review.googlesource.com/5329
    Reviewed-by: Florian Loitsch <floitsch@google.com>

commit 6614090f44931922aeeb7025e9d7c6f6dab32384
Author: Régis Crelier <regis@google.com>
Date:   Tue Sep 12 16:31:23 2017 +0000

    [VM generic functions reification] Emit code checking that the correct number of
    type arguments are passed to generic functions, when this could not be checked
    as part of the function resolution.
    The error message printed from a thrown noSuchMethodError does not yet properly
    reflect this kind of mismatch. It will be improved in a later cl.
    The Invocation class has previously been updated so that noSuchMethod is already
    able to process such mismatch.
    
    Change-Id: I81a2966195593dc0d158a322f2a2a2219d225e78
    Reviewed-on: https://dart-review.googlesource.com/5080
    Reviewed-by: Siva Annamalai <asiva@google.com>
    Reviewed-by: Zach Anderson <zra@google.com>

commit e0300086d1e4a437c949777ecf5aa1087b94a50d
Author: Régis Crelier <regis@google.com>
Date:   Wed Sep 6 14:39:00 2017 -0700

    [VM precompiler generic functions] Fix previous bad commit.
    Generic functions cannot be called via monomorphic checked entries, because
    the argument descriptor is lost. This limitation was removed by error and not
    properly tested. It is reintroduced in runtime_entry.cc.
    Changes in other sources are merely clean up and non-critical.
    
    Change-Id: I7967950c1ad008b50e8691d59f4a9d5cd1c9f885
    Reviewed-on: https://dart-review.googlesource.com/3761
    Reviewed-by: Ryan Macnak <rmacnak@google.com>

commit beedd2e1039775ae7b490e887778305afcab4f99
Author: Régis Crelier <regis@google.com>
Date:   Tue Sep 5 14:40:19 2017 -0700

    [VM generic function reification] Fix megamorphic cache lookup when calling
    reified generic function.
    Clean up code to avoid similar issue in the future, i.e. make it clear whether
    the passed type argument vector is counted or not by using better names.
    
    Change-Id: I60fd6f6acb302235d8c1ae4f2bc4bf459724421e
    Reviewed-on: https://dart-review.googlesource.com/3400
    Reviewed-by: Ryan Macnak <rmacnak@google.com>

commit df70bd64ae81510455efb7fe5aa18d138426ec77
Author: Régis Crelier <regis@google.com>
Date:   Wed Aug 30 09:19:44 2017 -0700

    [VM generic functions reification] Support generic async* and sync* functions.
    
    R=bkonyi@google.com
    
    Review-Url: https://codereview.chromium.org/3004033002 .

commit b3a7dd6e9dfab327a2ef4bb3ef729b4ba8661471
Author: Régis Crelier <regis@google.com>
Date:   Mon Aug 28 17:00:35 2017 -0700

    [VM generic function reification] Support generic functions in Invocation class.
    Make VM object TypeArguments a Dart instance.
    Add a test verifying that noSuchMethod works with generic functions.
    
    R=floitsch@google.com, rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/3007603002 .

commit b8bce019b3e4a344d22ac3c0f805b619565a1f8e
Author: Régis Crelier <regis@google.com>
Date:   Fri Aug 18 15:25:16 2017 -0700

    [VM generic functions] Support generic async calls.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/3001213002 .

commit 1829af87e9328dab203ed0a95c25ae6ae1bc59ae
Author: Régis Crelier <regis@google.com>
Date:   Thu Aug 17 11:11:01 2017 -0700

    [VM mirrors and reified generic functions] Mirrors do not (and will probably
    never) support reification of generic functions. However, instead of crashing
    with an UNIMPLEMENTED, reify function type parameters to dynamic.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2997083002 .

commit c29f5dd4f538fb1005f193d012028229a523de4c
Author: Régis Crelier <regis@google.com>
Date:   Wed Aug 16 10:48:02 2017 -0700

    [VM DBC compiler and simulator] Support reified generic functions.
    
    R=vegorov@google.com
    
    Review-Url: https://codereview.chromium.org/2987323003 .

commit 434f2e186c4ca85bda22dc27a99d883045f8c7bb
Author: Régis Crelier <regis@google.com>
Date:   Wed Jul 26 13:37:38 2017 -0700

    [VM aot compiler] Support reified generic functions in aot optimizer.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2991673003 .

commit cc81f38519b530f8dba6e46d82bc3c9554f5ce3d
Author: Régis Crelier <regis@google.com>
Date:   Fri Jul 21 15:07:56 2017 -0700

    [VM generic functions] Disallow generic function types as type arguments or bounds.
    Adjust existing test and status file.
    
    R=asiva@google.com
    
    Review-Url: https://codereview.chromium.org/2989513002 .

commit c98989f0d7cc8c1d1520b3202e18476cc33b5691
Author: Régis Crelier <regis@google.com>
Date:   Wed Jul 19 13:32:21 2017 -0700

    [VM generic function types] Properly set the scope function after parsing a
    result type that may contain a generic function type.
    Add a regression test demonstrating the fixed problem.
    Rename ResolveType to ResolveTypeParameters in the parser to clarify that only
    type parameters get resolved.
    Rename ResolveSignature to ResolveSignatureTypeParameters for the same reason.
    Correctly propagate the finalization mode when finalizing signatures.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2979763002 .

commit ec8a6cec72757f6faf6c8221873a33faefe38461
Author: Régis Crelier <regis@google.com>
Date:   Fri Jul 7 09:58:30 2017 -0700

    [VM inliner for generic functions] Address a review comment suggesting some
    refactoring of https://codereview.chromium.org/2894953002/
    
    R=vegorov@google.com
    
    Review-Url: https://codereview.chromium.org/2968083003 .

commit b5170a8b250a367e15f4903638eb87cdbc208273
Author: Régis Crelier <regis@google.com>
Date:   Thu Jul 6 12:13:16 2017 -0700

    Support inlining of calls where type arguments are passed to generic functions.
    
    R=vegorov@google.com
    
    Review-Url: https://codereview.chromium.org/2894953002 .

commit 2252d0dcc5cdb446116049634c3e9e0c48b4270a
Author: Régis Crelier <regis@google.com>
Date:   Fri Jun 30 15:04:13 2017 -0700

    [VM, generic functions reification, work in progress]
    Do not consider a generic function type as uninstantiated if all the function
    type parameters appearing in its signature are declared by the type itself.
    The generic function type is uninstantiated if it refers to function type
    parameters of parent generic functions, or to class type parameters.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2965743002 .


commit 9a65805689a249ef5fe8c913ce04a8b3f3ff8163
Author: Régis Crelier <regis@google.com>
Date:   Fri Jun 30 13:18:12 2017 -0700

    [VM, generic functions reification, work in progress]
    Support passing type arguments in a generic instance call.
    Note that kernel is always used for compiling InvokeFieldDispatcher functions.
    
    R=zra@google.com
    
    Review-Url: https://codereview.chromium.org/2969723002 .

commit 164a602a809d53cea75a8899f7ed861ec6e684d7
Author: Régis Crelier <regis@google.com>
Date:   Thu Jun 29 14:33:32 2017 -0700

    [VM parser] Mark class as typedef class before parsing its function type when
    using the new function type syntax.
    This issue prevents committing of https://codereview.chromium.org/2893893002
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2966583002 .

commit d9cc3b0e67c907f5ab4f08b8c1da84288f06e1a8
Author: Régis Crelier <regis@google.com>
Date:   Tue Jun 27 15:19:34 2017 -0700

    Allocate local variable holding type arguments in generic functions in Kernel.
    Capture instantiators when calling generic functions with uninstantiated type
    arguments.
    Add VM flag to generic functions tests that do not expect reification.
    
    R=asiva@google.com
    
    Review-Url: https://codereview.chromium.org/2958833003 .

commit bb527cb89e554388ae986fa754705c5b7710a561
Author: Régis Crelier <regis@google.com>
Date:   Fri Jun 23 14:18:10 2017 -0700

    Avoid an assert fault in snapshot writer by making sure that the parent of a
    signature function is also a signature function (fixes #29994).
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2949383003 .

commit 1f5f3ed79f4c152a7ba7f3f68367196763da15de
Author: Régis Crelier <regis@google.com>
Date:   Wed Jun 21 13:16:20 2017 -0700

    Set and keep parent function of signature functions.
    Fix function type parameter comparison in type tests.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2951803005 .

commit a62107cfaf8442a54ca7a87b096244cff992965f
Author: Régis Crelier <regis@google.com>
Date:   Wed Jun 21 09:02:12 2017 -0700

    Check for a passed-in type argument vector in the prolog of generic functions.
    Do this in unoptimized code only, when --reify-generic-functions is specified.
    This is still work in progress, and support in optimizer, in inliner, in DBC,
    in kernel to ir, and other areas, will follow.
    Many small fixes and added todos.
    
    R=rmacnak@google.com, vegorov@google.com
    
    Review-Url: https://codereview.chromium.org/2941643002 .

commit 9aafded095a820faa99df451e8e1ae0ab6f85f29
Author: Régis Crelier <regis@google.com>
Date:   Thu May 18 14:03:43 2017 -0700

    Pass type argument vector to generic functions (if --reify-generic-functions is
    true, still false per default).
    Work in progress, not functional yet (passed vector is still ignored in callee).
    
    R=vegorov@google.com, zra@google.com
    
    Review-Url: https://codereview.chromium.org/2859673002 .

commit e4ff8df6e6875d1788c7e0e20fef61c17a26a7fb
Author: Régis Crelier <regis@google.com>
Date:   Tue Apr 25 13:35:16 2017 -0700

    Properly handle implicit closure function when a generic function.
    The parent function of an implicit closure function is not the enclosing
    function, but the function being closurised. This requires special handling in a
    few places.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2835363002 .

commit 1b68c0d0a1546313b2aebc9f833222838a3a94c2
Author: Régis Crelier <regis@google.com>
Date:   Thu Apr 20 14:20:14 2017 -0700

    Process generic function type arguments in more places (function type tests,
    function cloning for mixins, signature building, etc...).
    Rename --generic-method-semantics flag to --reify-generic-functions (still not
    working and disabled by default).
    
    R=asiva@google.com
    
    Review-Url: https://codereview.chromium.org/2835513002 .

commit f0622c0567bc194b874675ea8b91e415cc73edaf
Author: Régis Crelier <regis@google.com>
Date:   Wed Apr 19 10:10:41 2017 -0700

    Allow signature functions to be allocated in new space.
    Types generated via instantiation during run time type tests are allocated in
    new space and it makes sense (in the case of function types) to also allocate
    instantiated signatures in new space.
    
    R=asiva@google.com
    
    Review-Url: https://codereview.chromium.org/2821233005 .

commit fd5089c9e81f865b1151ae3184421845f5635a86
Author: Régis Crelier <regis@google.com>
Date:   Mon Apr 17 08:58:20 2017 -0700

    Remove parent_level field of function type parameters.
    Add function_type_arguments field in closure instances.
    Lots of other smaller changes, also related to generic function semantics.
    This is still work in progress, with a change of direction in the design:
    The type argument vector of a generic function will be prepended with the type
    arguments of enclosing generic functions. The re-allocation and concatenation
    will be done in nested generic function's prolog. This will greatly simplify
    instantiation of types at run time without having to search the context for
    parent function's type arguments. However, a closure instance now requires an
    additional field. On the other hand, type parameters do not require a
    parent_level field anymore.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2818273002 .

commit d0a7bad1210b79a32d96c2d5954430da24bdd741
Author: Regis Crelier <regis@google.com>
Date:   Mon Apr 10 21:25:28 2017 -0700

    Pass a second type argument vector to all type instantiation calls in the VM.
    With generic methods, uninstantiated types will require 2 instantiators, one
    reflecting the class type arguments (as of today) and one reflecting the
    function type arguments (new).
    This is work in progress and the second instantiator is always null for now.
    
    R=asiva@google.com
    
    Review-Url: https://codereview.chromium.org/2799373002 .

commit b87f7ece723644c136c94ba32b1a089aa1150792
Author: Regis Crelier <regis@google.com>
Date:   Thu Apr 6 18:04:08 2017 -0700

    Mark 2 tests as crashing in dartk debug mode.
    
    Review-Url: https://codereview.chromium.org/2800043002 .

commit 5f5a698100be7b145168490dfb81cd436ce1b8ff
Author: Regis Crelier <regis@google.com>
Date:   Thu Apr 6 12:28:48 2017 -0700

    Keep types in signatures of function types properly instantiated as the function
    type itself gets instantiated.
    Until now, the signature was kept unchanged and the instantiation was reflected
    by the type arguments of the function type only. This delayed instantiation
    would complicate the implementation of generic functions.
    This cl actually removes type arguments for (non-typedef) function types. The
    function type is now fully represented by the signature. When the function type
    is instantiated, a new signature is allocated (instead of a new type argument
    vector) to hold instantiated result type and formal parameter types.
    The same applies in the case of typedef function types, however, the type
    arguments of the typedef are kept as before. This allows for better printing
    of typedef function types and for finalization of recursive type involving
    typedefs as type arguments.
    
    R=asiva@google.com
    
    Review-Url: https://codereview.chromium.org/2793033005 .

commit 9c9a14a29ae6b458022aa4ce69790cddd0ab502d
Author: Regis Crelier <regis@google.com>
Date:   Tue Mar 21 10:20:05 2017 -0700

    Add Genericity enum in VM to distinguish how a type is uninstantiated.
    Make flow graph builder aware of function type arguments.
    This is work in progress toward supporting generic method semantics in the VM.
    
    R=rmacnak@google.com
    
    Review-Url: https://codereview.chromium.org/2761933002 .

commit 09b5d6f619c415fcf885bffd868c1f09c1cd9989
Author: Regis Crelier <regis@google.com>
Date:   Wed Mar 8 08:55:30 2017 -0800

    Manage and capture class and function instantiators in the parser.
    This is work in progress towards supporting generic function semantics.
    
    R=hausner@google.com
    
    Review-Url: https://codereview.chromium.org/2736733005 .

commit 269aaf03054d4e3fcd722a2b4912130e70ad0f79
Author: Regis Crelier <regis@google.com>
Date:   Mon Feb 27 14:51:27 2017 -0800

    Properly handle instantiator when allocating or cloning closure instance.
    This should fix the vm-kernel bots.
    
    Review-Url: https://codereview.chromium.org/2723643002 .

commit 3633c5bd5ec0b6b876433b204d6c94bbfa118351
Author: Regis Crelier <regis@google.com>
Date:   Mon Feb 27 11:14:04 2017 -0800

    Rename Closure instance field type_arguments_ to instantiator_.
    Simplify handling of closures as deferred objects.
    The name "type_arguments_" is confusing, because class Closure is not generic.
    Class Closure was forcefully made (kinda) generic by setting its
    type_arguments_field_offset_in_words_ field to a valid value, so that the
    type_arguments_ field in closure instances could be accessed similarly as in
    generic instances. With generic functions, closures will potentially have more
    than one instantiator and the name type_arguments_ becomes nonsensical.
    
    R=johnmccutchan@google.com
    
    Review-Url: https://codereview.chromium.org/2719603002 .

commit 339d16fbc5d611fbbcf46235c290c615589ecc87
Author: Regis Crelier <regis@google.com>
Date:   Tue Feb 14 01:54:58 2017 -0800

    Only capture function instantiator when compiling local function (fixes #28757).
    Note that this code has no effect yet, because generic functions are not yet
    fully supported (no regression test added).
    
    R=hausner@google.com
    
    Review-Url: https://codereview.chromium.org/2690923004 .

commit 2037e7e88468ceb286f184b469a7781061c4e4f5
Author: Regis Crelier <regis@google.com>
Date:   Tue Feb 14 01:50:02 2017 -0800

    Properly resolve upper bounds of generic function's type parameters.
    Various minor cleanup related to generic functions.
    Add flag in preparation of future work to fully support generic methods.
    
    R=hausner@google.com
    
    Review-Url: https://codereview.chromium.org/2696783002 .

commit f3080b8803d683d374b97b1b23a9ba42332bdc7b
Author: Regis Crelier <regis@google.com>
Date:   Fri Feb 3 12:38:31 2017 -0800

    Refactor type finalization in VM so that the parser only resolves type
    parameters, whereas the class finalizer resolves all other type names and
    performs finalization and canonicalization. This allows to remove a lot of
    duplicated code between parser and class finalizer.
    
    R=hausner@google.com
    
    Review-Url: https://codereview.chromium.org/2673093003 .

commit 97f968de1c54db99b5f567d3fd6379756e2416f7
Author: Regis Crelier <regis@google.com>
Date:   Fri Jan 27 08:45:03 2017 -0800

    Implement generic function type syntax in the VM (fixes #27966).
    The new function type syntax is allowed everywhere and not just in typedef.
    
    R=hausner@google.com
    
    Review-Url: https://codereview.chromium.org/2643523002 .

**Closed by crelier** 2017-09-27 18:42 UTC
Labels: area-vm

**Comment by Hixie** [comment] 2017-09-27 20:02
Can this be turned on by default? Or should we turn it on manually? We've generally found that having to turn things on manually leads to annoying bugs for us to track down (where different parts of our system have different flags set, etc).

**Comment by crelier** [comment] 2017-09-27 20:09
As far as I know, this is a Dart 2.0 feature that cannot be turned on by default at this time.
The existing test suite does not expect this flag to be turned on either.
But feel free to try it on your side and report problems.

**Comment by Hixie** [comment] 2017-09-27 21:58
Apparently this isn't going to be turned on by default for now because the fix here is only a partial fix, it doesn't yet implement reification in the case where the type is going to be inferred.

e.g.:

```dart
void printTypeOf<T>(T foo) {
  print(T);
}

void main() {
  printTypeOf<bool>(null); // prints "bool" with this turned on, "dynamic" with it turned off
  printTypeOf(true); // always prints "dynamic", not "bool", even with this turned on
}
```

...and this is considered more unfriendly than the current behaviour (where the type is never reified).

**Comment by matanlurey** [comment] 2017-09-27 22:00
I think implementing type inference for the VM might be tracked separately?

**Comment by crelier** [comment] 2017-09-27 22:06
There is no current plan to implement type inference in the VM (with its own front-end). Type inference will be provided by the common front-end.

**Comment by matanlurey** [comment] 2017-09-27 22:13
Sorry, meant that @Hixie obviously doesn't care about the differentiation - he just might not want to enable reified generic method types until the VM runtime has inference (whether provided by the frontend or not, implementation detail for Flutter).
