### ISSUE TITLE
webgl/context-lost-restored_t01 sometimes times out

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28640] opened 2017-02-06 16:20 UTC
`co19/LayoutTests/fast/canvas/webgl/context-lost-restored_t01` test sometimes times out.

For example:
https://build.chromium.org/p/client.dart/builders/dart2js-mac10.11-safari-1-3-be/builds/3665/steps/dart2js%20safari%20co19%20tests/logs/stdio
https://build.chromium.org/p/client.dart/builders/dart2js-mac10.11-safari-1-3-be/builds/3664/steps/dart2js%20safari%20co19%20tests/logs/stdio

but also in build 3647

Marking as Skip (similar to the other context test).

**Comment by mraleph** [comment] 2017-11-16 12:05
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by sigmundch** [comment] 2017-11-16 18:30
Not meaningful for dart2js.

@alan-knight @terrylucas feel free to reopen if it is meaningful for the libraries area.

**Closed by sigmundch** 2017-11-16 18:30 UTC
Labels: area-library, gardening, library-webgl
