### ISSUE TITLE
i have switched stable to beta channel but still facing this issue

### ISSUE THREAD

**Issue by junaidhashmi** [dart-lang/sdk#41932] opened 2020-05-16 10:46 UTC
Compiler message:
/Users/qasimali/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;****

**Comment by srawlins** [comment] 2020-05-16 14:00
Duplicate of #41931

**Closed by srawlins** 2020-05-16 14:00 UTC
