### ISSUE TITLE
Switching to generic function type syntax for parameters may cause type inference to fail?

### ISSUE THREAD

**Issue by msbit** [dart-lang/sdk#48802] opened 2022-04-13 14:48 UTC
Starting with the following:

```
T tap<T>(T value, void sideEffect(T)) {
  sideEffect(value);
  return value;
}

void main(List<String> arguments) {
  arguments.map((x) => tap(x, (s) => print(int.parse(s))));
}
```

and running `dart analyze` I get the following:

```
Analyzing app...                       1.9s

   info • bin/app.dart:1:19 • Use generic function type syntax for parameters. • use_function_type_syntax_for_parameters

1 issue found.
```

Updating the definition of `tap` to:

```
T tap<T>(T value, void Function(T) sideEffect) {
  sideEffect(value);
  return value;
}
```

and running `dart analyze` again, I get the following error:

```
Analyzing app...                       1.8s

  error • bin/app.dart:7:54 • The argument type 'Object?' can't be assigned to the parameter type 'String'. •
          argument_type_not_assignable

1 issue found.
```

Similarly, `dart run` fails with the same error:

```
Building package executable... 
Failed to build app:app:
bin/app.dart:7:54: Error: The argument type 'Object?' can't be assigned to the parameter type 'String'.
 - 'Object' is from 'dart:core'.
  arguments.map((x) => tap(x, (s) => print(int.parse(s))));
                                                     ^
Failed to build app:app:
bin/app.dart:7:54: Error: The argument type 'Object?' can't be assigned to the parameter type 'String'.
 - 'Object' is from 'dart:core'.
  arguments.map((x) => tap(x, (s) => print(int.parse(s))));
                                                     ^
```

Changing the second argument to `tap` to `(String s) => print(int.parse(s)` works as expected, so I'm wondering if this is a regression in the type inference used to determine the type of `s`?

### Dart version

```
$ dart --version
Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"
```

**Comment by scheglov** [comment] 2022-04-14 16:23
Yes, it is unexpected that we get different inference results here.

I expected that with the work @stereotype441 does for https://github.com/dart-lang/language/issues/731 this will get better, but it looks that we still infer `Object?` here, even with the experiment enabled.

**Comment by stereotype441** [comment] 2022-04-14 18:00
The reason we get different inference results between
```dart
T tap<T>(T value, void sideEffect(T)) { ... }
```
and
```dart
T tap<T>(T value, void Function(T) sideEffect) { ... }
```
is because of an unfortunate piece of legacy in the Dart language spec.  Back when the Dart spec was first written, it said that any time a parameter was a single identifier, that identifier was the _name_ of the parameter, and the type was implicitly `dynamic`.  Which means that the original code was actually equivalent to:
```dart
T tap<T>(T value, void sideEffect(dynamic T)) { ... }
```
At some point we realized that this was confusing for most people, because they assumed that they were getting a specific type, and the only obviuos effect of getting the type `dynamic` instead was that their code was less efficient and some error conditions wouldn't get caught until runtime.  But we couldn't change it without breaking too much code that was already out in the wild.  So when we added the syntax to support inline function types (like `void Function(T)`) we specified it so that in that situation, a parameter that's a single identifier is interpreted as a type.

So that's the reason why you're seeing different inference results when you switch the declaration of `tap` to
```dart
T tap<T>(T value, void Function(T) sideEffect) { ... }
```
It's unfortunate, and not something we're proud of, but it's not something we're really able to fix without causing trouble for a lot of users.

As for how my work on https://github.com/dart-lang/language/issues/731 affects this, I just ran a test and with the `inference-update-1` flag enabled, I don't get any errors.  @scheglov, maybe I should come look over your shoulder later today and try to figure out why this wasn't working for you.

**Comment by scheglov** [comment] 2022-04-14 18:33
The reason it did not work for me, is that my test package was using Dart SDK `2.17`, but we recently switched to `2.18` as the current version, and any not yet released experiments are only applicable to the latest SDK version. With this in my `pubspec.yaml` file, the code infers better, and has no errors.
```yaml
environment:
  sdk: '>=2.18.0-edge <3.0.0'
```

**Comment by stereotype441** [comment] 2022-04-14 20:33
Duplicate of https://github.com/dart-lang/language/issues/731

**Closed by stereotype441** 2022-04-14 20:33 UTC
Labels: area-analyzer, P3

**Comment by msbit** [comment] 2022-04-15 00:46
Thanks for taking a look @scheglov, @stereotype441. Sounds like it's in hand ✌️
