### ISSUE TITLE
standalone/io/secure_unauthorized_test fails flakily on SIMDBC

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28719] opened 2017-02-10 01:19 UTC
I saw this on the `vm-mac-release-simdbc64-be` builder; see [this log](https://build.chromium.org/p/client.dart/builders/vm-mac-release-simdbc64-be/builds/1623/steps/vm%20tests/logs/stdio).

```
FAILED: none-vm release_simdbc64 standalone/io/secure_unauthorized_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
Client failed
  stdout:

  stderr:



stderr:
Unhandled exception:
Expect.fail('Client subprocess exit code: -6')
#0      Expect._fail (package:expect/expect.dart:435:5)
#1      Expect.fail (package:expect/expect.dart:154:5)
#2      main.clientProcess.<anonymous closure> (file:///b/build/slave/vm-mac-release-simdbc64-be/build/sdk/tests/standalone/io/secure_unauthorized_test.dart:53:16)
#3      _RootZone.runUnary (dart:async/zone.dart:1404)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._completeWithValue (dart:async/future_impl.dart:477)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:340)
#9      _RootZone.runUnary (dart:async/zone.dart:1404)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#13     _Future._completeWithValue (dart:async/future_impl.dart:477)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-release-simdbc64-be/build/sdk/.packages /b/build/slave/vm-mac-release-simdbc64-be/build/sdk/tests/standalone/io/secure_unauthorized_test.dart
Took 0:00:01.275992

Short reproduction command (experimental):
    python tools/test.py -mrelease -asimdbc64 -t240 standalone/io/secure_unauthorized_test
```

**Comment by mraleph** [comment] 2017-11-16 12:01
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by alexmarkov** [comment] 2021-01-08 00:23
SIMDBC mode was removed a while ago, so closing the issue.

**Closed by alexmarkov** 2021-01-08 00:23 UTC
Labels: area-vm, gardening
