### ISSUE TITLE
Add field isFieldInitializer to dart:mirrors:ParameterMirror

### ISSUE THREAD

**Issue by llamadonica** [dart-lang/sdk#24219] opened 2015-08-26 22:38 UTC
For whatever reason,  is_field_initializer is not passed back along with other  parameter info from runtime/vm/parser.cc (Parser::ParseFunctionParameters) -> runtime/lib/mirrors.cc

Is there any reason it shouldn't be exposed in dart?

**Comment by seaneagan** [comment] 2015-08-27 16:17
dupe of #16094 ?

**Comment by llamadonica** [comment] 2015-08-27 19:52
Yep, my mistake. Didn't know what I was looking for until I started diving into the code.

**Comment by dgrove** [comment] 2015-09-02 22:20
Duplicate of #16094 .

**Closed by dgrove** 2015-09-02 22:20 UTC
