### ISSUE TITLE
dart -h should show help from the dartdev snapshot

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#40953] opened 2020-03-10 16:57 UTC
`dart -h` (and `dart -h -v`) should show the help from the dartdev snapshot.

`dart help` currently does do this.

We'll want to ensure that it's still possible to see the Dart VM's verbose flags (`abort_on_oom`, `array_bounds_check_elimination`, ...) through some mechanism.

cc @mit-mit @jwren @a-siva @bkonyi

**Comment by bkonyi** [comment] 2020-03-10 19:38
What we really need to do is update dartdev to also include all of the standard VM flags like `--observe`, `--enable-asserts`, etc in the help output. The VM verbose flags might be a bit more difficult to deal with since they're not defined in a single location in the VM and are pulled into a single list of flags using a macro.

**Comment by mit-mit** [comment] 2020-03-12 16:29
Can we consider only including all those flags in `-h -v`?

**Comment by jwren** [comment] 2020-03-31 20:50
@bkonyi @mit-mit, I just created this PR: https://dart-review.googlesource.com/c/sdk/+/141920, that generates the output below.  All the output for `observe` and `write-service-info` felt too verbose, especially given that with dart commands, the commands go after the flags and options.

One issue:

`dart --enable-asserts analyze`

has the output:

```
Snapshot not compatible with the current VM configuration: the snapshot...
```


`dartdev help` output, with the PR mentioned above:

```
A command-line utility for Dart development.

Usage: dart [<vm-flags>] <command|dart-script-file> [<arguments>]

Global options:
-h, --help              Print this usage information.
-v, --verbose           Show verbose output.

Common VM flags:
    --enable-asserts    Enable assert statements.
-p, --package-root      Where to find packages, that is, "package:..." imports.
    --packages          Where to find a package spec file.
    --version           Print the VM version.

Available commands:
  analyze   Analyze the project's Dart code.
  create    Create a new project.
  format    Format Dart source code.
  pub       Work with packages.
  run       Run a Dart app or package.
  test      Runs tests in this project.

Run "dart help <command>" for more information about a command.
```

**Comment by bkonyi** [comment] 2020-04-01 00:39
I'd be hesitant to drop `--observe` from the list as that's necessary to allow for debugging. That flag, along with other important VM flags, should be listed under the `run` command (`--observe` should also be valid for the `test` command).

**Comment by mit-mit** [comment] 2020-04-01 10:07
@jwren can you also show what `dart help run` shows?

**Comment by devoncarew** [comment] 2020-04-01 15:36
Fot this:

```
dart --enable-asserts analyze

has the output:

Snapshot not compatible with the current VM configuration: the snapshot...
```

We should track that on another bug; here, the args the user intends to send to the app to run are instead affecting the dartdev snapshot.

**Comment by devoncarew** [comment] 2020-04-01 15:37
@jwren - would it be easier to iterate on a doc - list the likely VM flags we'd expose, and then categorize them into 'expose by default' / 'expose when run with -h -v' / 'expose a renamed variant?'?

**Comment by jwren** [comment] 2020-04-01 21:31
@devoncarew  -- Good idea, I'll create a doc.

**Comment by mit-mit** [comment] 2020-06-26 06:16
@jwren it looks like this was fixed?

**Comment by jwren** [comment] 2020-06-26 20:33
Yes, just confirmed.  Closing this issue.

**Closed by jwren** 2020-06-26 20:33 UTC
Labels: area-dart-cli
