### ISSUE TITLE
Unexpected commas on the end of argument completion for GestureDetector

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#29909] opened 2017-06-16 12:45 UTC
Bit a strange one... I had [an issue](https://github.com/Dart-Code/Dart-Code/issues/319) raised where the completion items where showing trailing commas:

![GestureDetector](https://user-images.githubusercontent.com/1078012/27227043-a0e6c272-5299-11e7-9101-93910b90b1d3.png)

I can repro, but when I try to reproduce it on my own class (which as far as I can tell is effectively the same as the `GestureDetector` defintion in `flutter/flutter`) I do not see it:

![My class](https://user-images.githubusercontent.com/1078012/27227062-b9623ee4-5299-11e7-83c0-839fbec4a038.png)

The comma seems to be included in the completion result from the analyzer:

![Free commas!](https://user-images.githubusercontent.com/1078012/27227067-c5a3f51c-5299-11e7-9dcd-68d71392528e.png)

This raises two questions:

1. Should the comma be there? (I think it looks weird)
2. Why does it appear to behave differently for these two similar (as far as I can tell) classes?

The source for `GestureDetector` is [here](https://github.com/flutter/flutter/blob/1f4f75bb503a8fd844fea382fb4b7c5ad0ce99dd/packages/flutter/lib/src/widgets/gesture_detector.dart) and my version is like this:

```dart
class Danny {
  Danny({
    int key,
    this.onTap,
    this.excludeFromSemantics: false
  }) {}
  final DannyCallback onTap;
  final bool excludeFromSemantics;
}

typedef void DannyCallback(Object details);
```

**Comment by bwilkerson** [comment] 2017-06-16 15:00
@pq

**Comment by pq** [comment] 2017-06-18 21:07
Right.  This is scoped to `Widget` subclasses which explains why you don't always see it.  As for motivation, see https://github.com/flutter/flutter-intellij/issues/551 for some background.   Sorry for the confusion!

**Comment by DanTup** [comment] 2017-06-19 05:59
This feels really wonky for me for a few reasons:

1. It looks bad in the completion list
2. It's inconsistent - why does it only apply to these classes?
3. It seems more complicated to me having the cursor inserted because after typing the argument value I know how to move the cursor past the comma (it's more awkward to use the cursor keys while typing than it is to type the comma)

After reading that thread I'm still not really clear on the motivation - what's the advantage to having the comma inserted?

**Comment by bwilkerson** [comment] 2017-06-19 13:44
The comma is a (imo, really ugly) way of telling the formatter to use a different formatting style. It is the formatting style preferred for Flutter development in which each argument is on a separate line, even when some arguments could be on the same line.

**Comment by DanTup** [comment] 2017-06-19 16:49
Oh, I understand the original case now, I was confused about the mention of commas and also indenting.

I agree this is an ugly way to achieve this... if it's confusing to @sethladd it's only going to be more confusing for people outside Google! The experience is weird (with the comma inserted, it's now more effort to move on to the next argument than if the comma was not inserted) and it also seems bizzare to be formatting code differently just because it's a subclass of Widget! I won't turn this into a complaint about `dartfmt` but it kinda feels like another thing it doesn't handle how people would like :-(

I'm happy to strip the comma off in Dart Code if you don't want to change it (I really don't want to ship this for all the reasons above; plus it's already cost me a bug report and some time and it's not even out the door yet!) but I really think it could be handled better centrally (eg. can't dartfmt handle this better (in a non-flutter-specific way) and then the IDE can just format as the user is typing to fix indenting?).

**Comment by bwilkerson** [comment] 2017-06-19 16:51
@munificent For the formatter questions.

**Comment by munificent** [comment] 2017-06-19 23:16
> it also seems bizzare to be formatting code differently just because it's a subclass of Widget! I

The formatter doesn't know it's a subclass of Widget. It only knows syntax. It has different rules for formatting argument lists that contain trailing commas and those that don't. The logic for argument lists without a trailing comma is the original logic. It's how all Dart users inside Google formatted their code, as well as most other users. It was designed to be similar to the official styles used by Google for JS and Java, and similar to how users at the time were hand-formatting their code. This style puts the closing `)` right after the final argument, even if it splits:

```dart
function(argument, argument,
    argument); // <--
```

The Flutter team has their own preferred formatting style. They requested that the language team add support for trailing commas in argument lists. The formatter's normal formatting rules don't make a lot of sense with that. The only point in having a trailing comma is that it makes it easier to reorganize arguments when each is on its own line — you can cut and paste the entire line. That benefit is lost if the `)` is put on the same line as in:

```dart
function(argument, argument,
    argument,); // <--
```

So, grudgingly, I added separate formatting logic that kicks in when the argument list has a trailing comma. Now you basically get to pick your preferred formatting style on a case by case basis by deciding whether or not to put a trailing comma in your argument list. This undermines the entire point of dartfmt — having a single consistent style and free users from thinking about formatting — but dartfmt had to do *something* with those trailing commas since they are now valid syntax.

**Comment by DanTup** [comment] 2017-06-20 06:03
I guess it's not really what dartfmt is doing here that I object to (though it does frustrate me that the number of places in which it doesn't meet its goal is growing, yet it still isn't configurable), it's the comma-insertion.

> Now you basically get to pick your preferred formatting style on a case by case basis by deciding whether or not to put a trailing comma in your argument list.

This doesn't seem completely bad, but in this case it feels like the formatting is being decided for us by the analyzer with the comma and the rules for it are not logical - I might prefer this formatting for my own classes, but I have to do it manually. It just seems weird that the analyzer has special behaviour for Widgets, Additionally, it feels like it's become *harder* to write code this way - when the comma is inserted it's now much clumsier to insert the next argument because you need to jump over the comma (which is more awkward than just typing the comma no matter whether you do it with cursor keys, tabstops, whatever), and because it's inconsistent the user needs to pay attention to this to not insert additional commas when typing quickly (I'm guessing IDEs don't "swallow" the comma if you type one with the cursor in front of it, but maybe they do).

I don't feel too strongly about changing the analyzer, but I probably will strip them out client-side to avoid more confusion. I also wonder if dartfmt could detect when a user appears to have formatted the args over multiple lines and preserve them, trailing comma or not? I appreciate that's both difficult and yet another thing going against the goal of a consistent style (though IMO I think it's kinda failing to deliver that anyway and it may be time to give up on that bit ;-))

**Comment by bwilkerson** [comment] 2017-06-20 17:25
@lukechurch Do we have any evidence to show whether this is a UX win or loss?

**Comment by DanTup** [comment] 2017-06-20 17:42
For the people that do like this behaviour, I'm curious - does your IDE do anything special to handle the comma (like overtyping it if you press a comma to avoid you having to use cursor keys to skip over it after typing a value)? And if not, are you happy with it or is this an annoyance you're living with in order to get the better formatting?

**Comment by DanTup** [comment] 2017-06-20 18:16
Ok, so I just noticed that when there's already a comma after the cursor, the completion does *not* include another one. This partially addresses my concern - it's fine for you to type another comma and then an argument, because you don't end up with multiple commas building up after the cursor.

![Comma not inserted](https://user-images.githubusercontent.com/1078012/27348321-86121d2a-55eb-11e7-933a-919f2486df26.png)

So I guess my issues are just (and these are somewhat minor):

1. It's inconsistent; it's not clear to the user why it sometimes happens (Widget sub-classes?) and sometimes does not
2. The display of the autocomplete looks wonky when commas are included (see Seth's original issue in Dart Code - when I saw his screenshot I thought I'd messed something up)

I could fix (2) by stripping the trailing comma from the display value (but leaving it for the completion), though it would be inconsistent with other IDEs and I'm not sure how users would feel when the completion doesn't (quite) match up with what they see. It's already the case for snippets so maybe that's not a big deal; though I'm interesting in other opinions.

I can't fix (1) though; this is a decision for you guys. It feels wonky to me but I'm currently writing the least Dart of anyone here so my opinion is based on very little real experience. I don't want to keep bashing on `dartfmt` (even I'm getting bored of hearing me!) but it does seem to me like this issue is a result of it not allowing people to format arguments as they'd really like - maybe there's some better way of deciding to format this way (that is more easily explainable than "is a widget class") and then comma wouldn't be needed?

**Comment by munificent** [comment] 2017-06-20 20:35
>  I also wonder if dartfmt could detect when a user appears to have formatted the args over multiple lines and preserve them, trailing comma or not?

That defeats the point of dartfmt. If you want a formatter that preserves your hand-formatting, `cat` works pretty well. :)

>though IMO I think it's kinda failing to deliver that anyway and it may be time to give up on that bit ;-)

I think it's doing that better than might be apparent. I review tons of random Dart code internally, and it's a huge relief to never ever ever have to make comments about the formatting style.

**Comment by pq** [comment] 2017-06-21 23:44
On vacation so a bit late to the party...  Thanks for the thoughtful conversation!

@DanTup: you make some great points and to be clear these changes were settled on after a fair amount deliberation but not without some reservations.  That said, I still think it's not a terrible compromise _assuming_ Flutter folks find the trailing comma generation valuable and that in practice the inconsistency isn't otherwise confusing.  My sense is that it's not that likely to be but I expect we'll get more feedback from @InMatrix and @lukechurch as they continue to study users.

Cheers everyone for the thoughtful back and forth! 🍻

**Comment by bwilkerson** [comment] 2017-07-05 16:20
@DanTup @pq Should we leave this open until we hear results from the user studies, or should we close this and open a new issue if the user studies reveal a problem?

**Comment by pq** [comment] 2017-07-05 16:39
I'm inclined to close and follow-up with an issue driven by user feedback but am open either way.

**Comment by DanTup** [comment] 2017-07-05 17:26
Now I understand it, I've no objection to closing this. I am interested in @sethladd's opinion on my question [here on the Dart Code issue](https://github.com/Dart-Code/Dart-Code/issues/319#issuecomment-310622711) though. I'm tempted to hide the comma from the completion list (if it looked like a bug to both Seth and I, I presume many other users will think so too).

**Closed** 2017-07-05 17:27 UTC
Labels: analyzer-completion, analyzer-ux, area-analyzer, P2 medium

**Comment by DanTup** [comment] 2017-07-07 10:17
FWIW - due to no real opinions, I made a call on how to behave here in Dart Code.. I've trimmed the commas from the *display text* so everything looks normal:

![Trimmed](https://user-images.githubusercontent.com/1078012/27953918-8e8d6c08-6305-11e7-8c2b-16b3e2b49483.png)

But when you insert, you still get the original text including the comma (and the placeholder I injected):

![Inserted](https://user-images.githubusercontent.com/1078012/27953956-af0cb600-6305-11e7-94f8-8ca26d20c7e2.png)

I haven't used it much, but in a quick test this looks and feels really natural :-)
