### ISSUE TITLE
Analyzer regression

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#26037] opened 2016-03-18 11:09 UTC
With 1.16.0-dev.1.0 all code issues are reported as errors when strong mode is on. Checked on IntelliJ & Atom.

**Comment by alexander-doroshko** [comment] 2016-03-18 12:39
Related to (or duplicate of) #26026

**Comment by bwilkerson** [comment] 2016-03-18 13:16
Yes, I suspect that it's a duplicate. Please re-open if I've misunderstood.

**Closed by bwilkerson** 2016-03-18 13:16 UTC
