### ISSUE TITLE
Dartium crashes on some types of input elements

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#25418] opened 2016-01-12 22:31 UTC
Date elements (`<input type="date">`) cause an aw snap when you select a date (tried with dart sdk 1.13.2 and 1.14.0-dev.4.0).

Color elements (`<input type="color">`) cause dartium to completely crash on mac only, if you click the button circled in the screenshot below (tested with dart sdk 1.13.2):
![screenshot](https://cloud.githubusercontent.com/assets/984921/12278967/11c4aa78-b939-11e5-9249-21e6d445d104.jpg)

**Comment by Sfshaza** [comment] 2016-01-12 22:33
I can provide the entire example, if you need it. thx

**Comment by alan-knight** [comment] 2016-01-12 22:48
Duplicate of #23602, it's an old Chrome bug, will be fixed with the Dartium roll.

**Closed by alan-knight** 2016-01-12 22:48 UTC
Labels: area-dartium
