### ISSUE TITLE
NPE in _SummarizeAstVisitor.visitConstructorDeclaration

### ISSUE THREAD

**Issue by SupLuo** [dart-lang/sdk#36009] opened 2019-02-22 12:55 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.4 unknown, screens 1280x800  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b, server version 1.21.1, error: Captured exception
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1059:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2950:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:410:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1016:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8366:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:457:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:463:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:462:26)
#12     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:229:32)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#14     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:225:20)
#15     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:298:9)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1067:22)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#19     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#20     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#21     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#22     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#28     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#29     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#30     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#31     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#32     main (file:///b/rr/tmpFYAHZv/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#33     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/v4/0zgfq47d7c53k6xl21mwyhpm0000gn/T/report.txt.

**Comment by stereotype441** [comment] 2019-03-01 23:19
@danrubel this looks like a regression of #34610.  Would you mind having a look?

Classifying as P1 for now on the assumption that it's a regression.  If it's not a regression we can consider dropping to P2.

**Comment by danrubel** [comment] 2019-03-05 14:06
I dug into this and it does not appear to be a regression. I added [more tests](https://dart-review.googlesource.com/c/sdk/+/95420) to be sure.

@scheglov Do these tests assert the correct things? Any ideas on what parser output is incorrect?

**Comment by scheglov** [comment] 2019-03-06 17:03
The tests look good for me.

**Comment by stereotype441** [comment] 2019-03-06 17:09
@danrubel when you say "it does not appear to be a regression", do you mean that you can't reproduce the failure, or that you can reproduce it but it seems to be unrelated to #34610?

**Comment by danrubel** [comment] 2019-03-07 12:14
@stereotype441 I cannot reproduce the failure

**Comment by DanTup** [comment] 2019-06-14 15:13
Is this a dupe of https://github.com/dart-lang/sdk/issues/36961?

**Comment by stereotype441** [comment] 2019-06-14 15:26
@DanTup seems likely.  Thanks for noticing that!

**Comment by stereotype441** [comment] 2019-06-14 15:26
Duplicate of #36961

**Closed by stereotype441** 2019-06-14 15:26 UTC
Labels: analyzer-server, area-analyzer, p1-high, type-bug
