### ISSUE TITLE
"The null object does not have a method 'substitute2'."

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#27352] opened 2016-09-14 17:33 UTC
I was editing files while the analyzer was doing its first run. Not sure exactly what I changed, but it crashed with this:

```
$ flutter analyze --watch --flutter-repo --write /tmp/analyzer-watch-output --dartdocs
Analyzing Flutter repository...                          
Error from the analysis server: Task failed: InferInstanceMembersInUnitTask for source /usr/local/google/home/ianh/dev/flutter/examples/layers/rendering/src/sector_layout.dart
Unexpected exception while performing InferInstanceMembersInUnitTask for source /usr/local/google/home/ianh/dev/flutter/examples/layers/rendering/src/sector_layout.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1234)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1232)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:374)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:887)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a method 'substitute2'.

NoSuchMethodError: method not found: 'substitute2'
Receiver: null
Arguments: [_List len:2, _List len:2]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      MethodMember.from (package:analyzer/src/dart/element/member.dart:642)
#3      InterfaceTypeImpl.methods (package:analyzer/src/dart/element/type.dart:1346)
#4      InheritanceManager._recordMapWithClassMembers (package:analyzer/src/dart/resolver/inheritance_manager.dart:627)
#5      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:525)
#6      InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:193)
#7      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:261)
#8      List.forEach (dart:core-patch/growable_array.dart:258)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:230)
#10     InstanceMemberInferrer.inferCompilationUnit.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:93)
#11     List.forEach (dart:core-patch/growable_array.dart:258)
#12     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:91)
#13     InferInstanceMembersInUnitTask.internalPerform (package:analyzer/src/task/dart.dart:3407)
#14     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#15     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#16     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#17     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#18     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1234)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#20     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1232)
#21     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:374)
#22     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:887)
#23     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#24     _rootRun (dart:async/zone.dart:1146)
#25     _CustomZone.run (dart:async/zone.dart:1026)
#26     _CustomZone.runGuarded (dart:async/zone.dart:924)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#28     _rootRun (dart:async/zone.dart:1150)
#29     _CustomZone.run (dart:async/zone.dart:1026)
#30     _CustomZone.runGuarded (dart:async/zone.dart:924)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bwilkerson** [comment] 2016-09-14 17:50
I believe this is a duplicate of https://github.com/dart-lang/sdk/issues/27102.

**Closed by bwilkerson** 2016-09-14 17:50 UTC
