### ISSUE TITLE
Memory leak when creating many `HttpClient`s

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#52541] opened 2023-05-28 12:36 UTC
Observed on:
```
Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_arm64"
Dart SDK version: 3.0.2 (stable) (Tue May 23 08:26:58 2023 +0000) on "macos_arm64
```

The following program has a memory leak:

```dart
import 'dart:io';

void main() async {
  final pendingWork = <Future<void>>[];
  while (true) {
    if (pendingWork.length >= Platform.numberOfProcessors) {
      await Future.any(pendingWork);
    } else {
      final work = asyncWork();
      pendingWork.add(work);
      work.then((_) => pendingWork.remove(work));
    }
  }
}

Future<void> asyncWork() async {
  final client = HttpClient();
  try {
    final request =
        await client.openUrl('GET', Uri.parse('https://google.com'));
    final response = await request.close();
    await response.drain();
  } finally {
    client.close();
  }
}
```

Why do I create a new `HttpClient` for each request? I noticed the memory leak when using `Isolate.run` to parallelize work, where each `Isolate` needs its own `HttpClient`. But the multiple `Isolate`s don't seem to be the problem, as the code above shows.

In the actual app I'm using `package:http`, which has the same issue, but I tried to make the repro as minimal as possible.

**Comment by a-siva** [comment] 2023-06-06 22:00
@blaugold are you running your app connected under devtools when you observe the memory leak?

**Comment by blaugold** [comment] 2023-06-07 06:12
@a-siva I noticed the issue in production where we use an AOT build and replicated it running the repro locally with JIT but never using devtools, so I don't think its a duplicate.

**Comment by a-siva** [comment] 2023-06-20 16:57
@blaugold could you give us some information on what tools you are using to observe the memory leak. I tried your test application above by running it for a long time and I did not observe any leaks while monitoring the the Dart heap size or the native RSS.

```
[ GC isolate   | space (reason)           | GC# | start | time | used (MB)   | capacity MB | external| used (MB)     | capacity (MB) | external MB |  buffer | new  | old   ]
[              |                          |     |  (s)  | (ms) |before| after|before| after| b4 |aftr| before| after | before| after |before| after| b4 |aftr| (MB) | (MB)  ]
[ main         ,    Scavenge(   new space), 27201, 9836.36,   5.1,  32.0,   1.2,  32.0,  32.0, 15.8, 1.5,   10.3,   10.3,   30.8,   30.8,   0.7,   0.7,   1,   1, -30.8,    0.0, ]
[ main         ,    Scavenge(   new space), 27202, 9837.03,   5.3,  32.0,   1.3,  32.0,  32.0, 16.0, 1.6,   10.3,   10.3,   30.8,   30.8,   0.7,   0.7,   1,   1, -30.7,    0.0, ]
[ main         ,    Scavenge(   new space), 27203, 9837.73,   5.5,  32.0,   1.3,  32.0,  32.0, 15.8, 1.6,   10.3,   10.3,   30.8,   30.8,   0.7,   0.7,   1,   1, -30.7,    0.0, ]

```

![image](https://github.com/dart-lang/sdk/assets/8633293/f1a5da31-1f6f-4691-9d3c-7063ad905881)

**Comment by blaugold** [comment] 2023-06-20 17:40
That's interesting. We first noticed the memory issue in our Cloud Run deployment, which started to run out of memory after a certain amount of time, after we started creating many more `HttpClient`s than before. Then I tried to replicate the issue locally on my MacBook using Activity Monitor:

<img width="852" alt="Screenshot 2023-06-20 at 19 30 43" src="https://github.com/dart-lang/sdk/assets/5929595/2f0e73d3-7193-499c-acb8-92162c042ae4">

The highlighted process starts at around ~50 MB and slowly accumulates more memory use.

**Comment by blaugold** [comment] 2023-06-20 17:51
Here are a few more infos for the process:

<img width="671" alt="Screenshot 2023-06-20 at 19 47 13" src="https://github.com/dart-lang/sdk/assets/5929595/a509c370-57ee-45e0-8b1f-8054cde9901f">

**Comment by blaugold** [comment] 2023-08-09 10:55
Seems like this is the same issue as https://github.com/dart-lang/sdk/issues/53113. When I replace `https://google.com` with `http://google.com` the code above does not exhibit the described leak.

**Comment by a-siva** [comment] 2023-08-09 17:11
> Seems like this is the same issue as #53113. When I replace `https://google.com` with `http://google.com` the code above does not exhibit the described leak.

Thanks for that clarification, I will dup this issue into that one.

**Comment by a-siva** [comment] 2023-08-09 17:11
Marking as a duplicate of https://github.com/dart-lang/sdk/issues/53113 and closing.

**Closed by a-siva** 2023-08-09 17:11 UTC
Labels: area-library, closed-duplicate, library-io
