### ISSUE TITLE
[dart:io] In windows, root directory's stat() method failed

### ISSUE THREAD

**Issue by glanium** [dart-lang/sdk#54386] opened 2023-12-16 07:37 UTC
In windows, root directory's FileStat failed.

```dart
  final dir = Directory(r'C:\'); <-- Root directory
  final stat = await dir.stat();
  print(stat.type); // <-- FileSystemEntityType.notFound!
```

for example, using  C#, 
```csharp
  var dirInfo = new DirectoryInfo(@"C:\");  // <-- No error and this retrun correct attirubte values
  dirInfo.Refresh();  // <-- No error and this retrun correct attirubte values
```

This is by design or bug?

**Comment by brianquinlan** [comment] 2023-12-18 18:52
That seems like a bug, not WAI.

**Comment by codesculpture** [comment] 2024-01-01 18:45
It seems the problem is with windows sys/stat.h, somehow it just throws static info for root level dirs (which are drives).
```cpp
#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <errno.h>

int main( void )
{
   struct _stat buf;
   int result;
   char timebuf[26];
   // char* filename = "C:/Users/"; // This Would Work
   char* filename = "C:/"; // This Would Not Work
   errno_t err;

   // Get data associated with "crt_stat.c":
   result = _stat( filename, &buf );

   // Check if statistics are valid:
   if( result != 0 )
   {
      perror( "Problem getting information" );
      switch (errno)
      {
         case ENOENT:
           printf("File %s not found.\n", filename);
           break;
         case EINVAL:
           printf("Invalid parameter to _stat.\n");
           break;
         default:
           /* Should never be reached. */
           printf("Unexpected error in _stat.\n");
      }
   }
   else
   {
      // Output some of the statistics:
      printf( "File size     : %ld\n", buf.st_size );
      printf( "Drive         : %c:\n", buf.st_dev + 'A' );
      err = ctime_s(timebuf, 26, &buf.st_mtime);
      if (err)
      {
         printf("Invalid arguments to ctime_s.");
         return 1;
      }
      printf( "Time modified : %s", timebuf );
   }
}
```

The output for C:/
```
File size     : 0
Drive         : C:
Time modified : Tue Jan 01 00:00:00 1980
```
The output for C:/Users/
```
File size     : 0
Drive         : C:
Time modified : Fri Oct 21 20:16:49 2022
```

This is the same case for other root level dirs which are drives (ex: D:\, F:\ )

**Comment by codesculpture** [comment] 2024-01-02 07:05
I guess the triming seperator is the problem especially for this particular case C:\ to C: , and meanwhile i looked for c sharp internal impl (as @glanium said its working fine there) they handled this case seperately. Btw this is a naive thought, will look deeply this.

**Comment by brianquinlan** [comment] 2024-01-02 19:03
Thanks for investigating this @codesculpture

**Comment by codesculpture** [comment] 2024-01-02 20:25
I sense the issue is with sys/stat.h
Let me say what i looked online,

First node js is doing fine stat for C: and D: drives and they are using mingw64's headers instead of sys/stat.h
And Deno is doing fine for stat, since its powered by rust and rust is fine with C: for stat.
And C - Sharp (still am not sure it using sys/stat.h but i believe it use that) but as @glanium said its working fine with c-sharp, i think c-sharp is actually giving current directory stat for C: , D: drives,  below the source where they added comment and its super weird why they doing that 🫡 

https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/directoryinfo.cs#L89-L93

**Comment by codesculpture** [comment] 2024-01-03 05:42
Here https://github.com/dart-lang/sdk/blob/main/runtime/bin/file_win.cc#L947-L965 Here's the dart impl for stat (using sys/stat.h)

**Comment by codesculpture** [comment] 2024-01-03 07:23
Looking through GetFileAttributes does returning Invalid_Attributes for C:

**Comment by codesculpture** [comment] 2024-01-03 12:16
Another Weird things is happening from dart, adding space (C:\<space> )in @glanium code make it work  
  ```dart
final dir = Directory(r'C:\ '); <-- Space Here
final stat = await dir.stat();
print(stat.type)
```

This output proper information, but still had no choice how its working

**Comment by codesculpture** [comment] 2024-01-04 08:43
So it would transform C:\ to C: right, but not for C:\(space) since it would be false in the while condition  @glanium

**Comment by codesculpture** [comment] 2024-01-05 14:47
Still looking on how this working even without the seperator but having space
For ex:
 "C:" would not work
"C: " would work 


Also this is not related to this,

the windows own stat, stat64, wstat64... are returning ctime of Jan 1 1980 for root drives such as C:// or D://

Dart also using wstat64 but somehow returning correct ctime for "C: " or "C:// "

🤔

**Comment by codesculpture** [comment] 2024-01-05 17:41
Got the root problem that "wstat64" return successfully when the input is "C: " or "C: \\" or "C:/". But only throw errors for "C:" i suspect internally it just throwing when there is less than 3 chars or something like that (cant find the implementation of that). 

From dart, as long as there is a space at end of path, it would successfully return since wstat dint care the extra space we provide.

But as long as we not having space at the end, we end up having "path seperator" which get trims internally the slashes _trimTrailingPathSeperators (you can see the impl of that). 

Summary,
 wstat wont accept "C:", so passing this would result in error. 

Dart would trim, these (having path seperator at the end) "C://" or "C:\" to "C:", thus would wstat wont accept as above.

But dart wouldn't trim these (having space at the end) "C:// " or "C:\ " or "C: " (this accepted by wstat), so these all are return successfully.

**Comment by codesculpture** [comment] 2024-01-05 17:48
So are we planning to allow "C:" as a valid path from the user since its not accepted by wstat for some reason @brianquinlan @glanium 

If yes, we need to handle this case exclusively.

**Comment by codesculpture** [comment] 2024-01-06 19:18
Created PR here https://github.com/dart-lang/sdk/pull/54536 , need to know the output of test cases (since i wrote it naively)

**Comment by codesculpture** [comment] 2024-01-11 11:01
Fix PR merged, can be closed. Thanks @glanium @brianquinlan @mraleph

**Comment by mraleph** [comment] 2024-01-11 11:08
@codesculpture it will close automatically when Copybara syncs Gerrit to GitHub.

Thanks for the contribution!

**Comment by mraleph** [comment] 2024-01-11 11:09
Nevermind. This is an issue not a PR. 

Fixed by https://github.com/dart-lang/sdk/commit/8945d1be75684c63b08d74bfbb52b56fb626ce6c

**Closed by mraleph** 2024-01-11 11:09 UTC
Labels: area-vm, P3, library-io, triaged
