### ISSUE TITLE
The Dart Analyzer has terminated.

### ISSUE THREAD

**Issue by ghost** [dart-lang/sdk#38636] opened 2019-09-29 07:53 UTC
![屏幕快照 2019-09-29 下午3 50 48](https://user-images.githubusercontent.com/49218931/65828770-192e0780-e2d1-11e9-9cd4-dad7d8a9998d.png)

```
Sun Sep 29 2019 [15:39:59 GMT+0800 (China Standard Time)] Log file started
[3:39:59 PM] [General] [Info] Searching for SDKs...
[3:39:59 PM] [General] [Info] Environment PATH:
[3:39:59 PM] [General] [Info]     /Users/yifan/flutter/bin
[3:39:59 PM] [General] [Info]     /usr/local/bin
[3:39:59 PM] [General] [Info]     /usr/bin
[3:39:59 PM] [General] [Info]     /bin
[3:39:59 PM] [General] [Info]     /usr/sbin
[3:39:59 PM] [General] [Info]     /sbin
[3:39:59 PM] [General] [Info]     /Users/yifan/GitReview/arcanist/bin/
[3:39:59 PM] [General] [Info] Found Flutter project at /Users/yifan/rongcloud-im-flutter-sdk:
			Mobile? true
			Web? false
			Create Trigger? false
			Stagehand Trigger? false
			Flutter Repo? false
[3:39:59 PM] [General] [Info] Found Flutter project at /Users/yifan/rongcloud-im-flutter-sdk/example:
			Mobile? true
			Web? false
			Create Trigger? false
			Stagehand Trigger? false
			Flutter Repo? false
[3:39:59 PM] [General] [Info] Searching for flutter
[3:39:59 PM] [General] [Info]     Looking for flutter in:
[3:39:59 PM] [General] [Info]         /Users/yifan/rongcloud-im-flutter-sdk
[3:39:59 PM] [General] [Info]         /Users/yifan/rongcloud-im-flutter-sdk/bin
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin
[3:39:59 PM] [General] [Info]         /usr/local/bin
[3:39:59 PM] [General] [Info]         /usr/bin
[3:39:59 PM] [General] [Info]         /bin
[3:39:59 PM] [General] [Info]         /usr/sbin
[3:39:59 PM] [General] [Info]         /sbin
[3:39:59 PM] [General] [Info]         /Users/yifan/GitReview/arcanist/bin/
[3:39:59 PM] [General] [Info]     Found at:
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin
[3:39:59 PM] [General] [Info]     Candidate paths to be post-filtered:
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter
[3:39:59 PM] [General] [Info]     Found at /Users/yifan/flutter
[3:39:59 PM] [General] [Info]     Returning SDK path /Users/yifan/flutter for flutter
[3:39:59 PM] [General] [Info] Searching for dart
[3:39:59 PM] [General] [Info]     Looking for dart in:
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk/bin
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin
[3:39:59 PM] [General] [Info]         /usr/local/bin
[3:39:59 PM] [General] [Info]         /usr/bin
[3:39:59 PM] [General] [Info]         /bin
[3:39:59 PM] [General] [Info]         /usr/sbin
[3:39:59 PM] [General] [Info]         /sbin
[3:39:59 PM] [General] [Info]         /Users/yifan/GitReview/arcanist/bin/
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk/bin
[3:39:59 PM] [General] [Info]     Found at:
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk/bin
[3:39:59 PM] [General] [Info]         /usr/local/bin
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk/bin
[3:39:59 PM] [General] [Info] Following symlink: /usr/local/bin/dart ==> /usr/local/Cellar/dart/2.4.1/libexec/bin/dart
[3:39:59 PM] [General] [Info]     Candidate paths to be post-filtered:
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk
[3:39:59 PM] [General] [Info]         /usr/local/Cellar/dart/2.4.1/libexec
[3:39:59 PM] [General] [Info]         /Users/yifan/flutter/bin/cache/dart-sdk
[3:39:59 PM] [General] [Info]     Found at /Users/yifan/flutter/bin/cache/dart-sdk
[3:39:59 PM] [General] [Info]     Returning SDK path /Users/yifan/flutter/bin/cache/dart-sdk for dart
[3:40:00 PM] [General] [Info] Activating Flutter extension for Flutter project...
[3:40:00 PM] [General] [Info] Extension:Startup timing: 126ms
[3:40:02 PM] [General] [Info] Analyzer:Startup timing: 2655ms
[3:40:05 PM] [General] [Info] Checking 2 projects for supported platforms
[3:40:05 PM] [General] [Info] Supported platforms for the workspace are ios, android
[3:40:08 PM] [Analyzer] [Error] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
[3:40:09 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
```

![屏幕快照 2019-09-29 下午3 52 51](https://user-images.githubusercontent.com/49218931/65828785-382c9980-e2d1-11e9-93fe-1a04df2d632d.png)

**Comment by rc-ZhangYifan** [comment] 2019-09-29 07:55
I'm trying to delete flutter/bin/cache ， But it didn't solve the problem

**Comment by yuezhilunhui2009** [comment] 2019-11-21 14:29
I have the same problem.

**Comment by yuezhilunhui2009** [comment] 2019-11-21 15:13
```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.6.0
Flutter extension: 3.6.0 (activated)
VS Code: 1.40.1
Platform: mac
HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Nov 21 2019 [02:01:14 GMT+0800 (China Standard Time)] Log file started
[2:01:14 AM] [General] [Info] Searching for SDKs...
[2:01:14 AM] [General] [Info] Environment PATH:
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/gems/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/gems/ruby-2.6.3@global/bin
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/rubies/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]     /usr/local/bin
[2:01:14 AM] [General] [Info]     /usr/bin
[2:01:14 AM] [General] [Info]     /bin
[2:01:14 AM] [General] [Info]     /usr/sbin
[2:01:14 AM] [General] [Info]     /sbin
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info] Done!
[2:01:14 AM] [General] [Info] Found Flutter project at /Users/cc/github/nautilus/example:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[2:01:14 AM] [General] [Info] Searching for flutter
[2:01:14 AM] [General] [Info]     Looking for flutter in:
[2:01:14 AM] [General] [Info]         /Users/cc/github/nautilus/example
[2:01:14 AM] [General] [Info]         /Users/cc/github/nautilus/example/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3@global/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/rubies/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /usr/local/bin
[2:01:14 AM] [General] [Info]         /usr/bin
[2:01:14 AM] [General] [Info]         /bin
[2:01:14 AM] [General] [Info]         /usr/sbin
[2:01:14 AM] [General] [Info]         /sbin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]     Found at:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]     Candidate paths to be post-filtered:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]     Found at /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]     Returning SDK path /Users/cc/Downloads/flutter for flutter
[2:01:14 AM] [General] [Info] Searching for dart
[2:01:14 AM] [General] [Info]     Looking for dart in:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3@global/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/rubies/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /usr/local/bin
[2:01:14 AM] [General] [Info]         /usr/bin
[2:01:14 AM] [General] [Info]         /bin
[2:01:14 AM] [General] [Info]         /usr/sbin
[2:01:14 AM] [General] [Info]         /sbin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]     Found at:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]     Candidate paths to be post-filtered:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]     Found at /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]     Returning SDK path /Users/cc/Downloads/flutter/bin/cache/dart-sdk for dart
[2:01:14 AM] [General] [Info] Activating Flutter extension for Flutter project...
[2:01:14 AM] [General] [Info] Extension:Startup timing: 32ms
[2:01:14 AM] [General] [Info] Analyzer:Startup timing: 396ms
[2:01:15 AM] [General] [Info] Checking 1 projects for supported platforms
[2:01:15 AM] [General] [Info] Supported platforms for the workspace are ios, android
[2:01:17 AM] [Analyzer] [Error] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
[2:01:18 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43601)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:38875)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43409
	at new Promise (<anonymous>)
	at l.sendRequest (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43221)
	at l.analysisSetSubscriptions (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:283639)
	at g.<anonymous> (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:32675)
	at Generator.next (<anonymous>)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:31221
	at new Promise (<anonymous>)
	at r (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:30966)
	at g.updateSubscriptions (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:32528)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:31525
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:545:768
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
	at p.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/ser…
[2:01:18 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43601)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:38875)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43409
	at new Promise (<anonymous>)
	at l.sendRequest (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43221)
	at l.editGetFixes (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:285177)
	at t.FixCodeActionProvider.<anonymous> (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:428072)
	at Generator.next (<anonymous>)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:427606
	at new Promise (<anonymous>)
	at r (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:427351)
	at t.FixCodeActionProvider.provideCodeActions (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:427912)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:433211
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:433202)
	at Generator.next (<anonymous>)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:432651
	at new Promise (<anonymous>)
	at r (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:432396)
	at t.RankingCodeActionProvider.provideCodeActions (/Users/cc/.vscode/exte…
```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
...
```

```

**Comment by yuezhilunhui2009** [comment] 2019-11-23 07:17
I deleted the whole flitter project and downloaded it from GitHub again. There was no error.

**Comment by amittttt** [comment] 2019-12-25 21:17
I am also facing the same problem :(

**Comment by srawlins** [comment] 2019-12-29 04:01
Looks like a duplicate of https://github.com/Dart-Code/Dart-Code/issues/1649.

**Closed** 2021-11-16 17:15 UTC
Labels: area-analyzer, type-bug, analyzer-crash-report
