### ISSUE TITLE
Analyzer issue

### ISSUE THREAD

**Issue by BugsBunnyBR** [dart-lang/sdk#38151] opened 2019-08-31 03:47 UTC
AS just told me to open this bug. I hope it helps.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1280x800  Retina`

## Exception
```
Dart analysis server, SDK version 2.3.0-edge.a1668566e563aef64025d0af88a099cbbe847b7e, server version 1.26.0, error: FileSystemException(path=/Users/juliocotta/git/plugins/packages/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/.symlinks/plugins/battery/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcwork; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#17     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#18     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#19     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#20     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#21     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#22     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#23     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#24     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#25     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#26     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#27     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#28     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#29     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#30     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#31     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#32     ContextManagerImpl._createContext.checkManifestFil...
```

For additional log information, please append the contents of
file:///private/var/folders/8n/dt6g202d30n3wp4ybzd_wtfc0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-05 22:26
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38101; please follow along there.

**Comment by srawlins** [comment] 2019-09-05 22:27
Duplicate of https://github.com/dart-lang/sdk/issues/38101

**Closed by srawlins** 2019-09-05 22:27 UTC
Labels: area-analyzer
