### ISSUE TITLE
Several simple tests randomly timeout on vm-precomp-win-simarm64-2-4-be

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#31083] opened 2017-10-12 09:24 UTC
Several different tests that should be quick to run timeout on vm-precomp-win-simarm64-2-4-be randomly. Here are some instances of this issue:

* Build [2874](https://uberchromegw.corp.google.com/i/client.dart/builders/vm-precomp-win-simarm64-2-4-be/builds/2874/steps/test%20vm/logs/stdio). The test is `co19/LibTest/typed_data/Int16List/buffer_A01_t01`.
* Build [2871](https://uberchromegw.corp.google.com/i/client.dart/builders/vm-precomp-win-simarm64-2-4-be/builds/2871/steps/test%20vm/logs/stdio). The test is `co19/Utils/tests/Expect/isFalse_A01_t01`.
* Build [2870](https://uberchromegw.corp.google.com/i/client.dart/builders/vm-precomp-win-simarm64-2-4-be/builds/2870/steps/test%20vm/logs/stdio). The test is `co19/LibTest/typed_data/Int64List/firstWhere_A03_t01`.

These tests don't show up in the Top 10 of slowest tests on the bot for other builds. Also, there are no other timeouts on these tests in the last ~50 builds.

**Comment by mraleph** [comment] 2017-11-03 06:17
Duplicate of #29261

**Closed** 2017-11-03 06:17 UTC
Labels: area-infrastructure, area-vm, Type: code health
