### ISSUE TITLE
[dart2js] - Generating (possibly unnecessary) partfile for FormData

### ISSUE THREAD

**Issue by hamsbrar** [dart-lang/sdk#53013] opened 2023-07-22 10:31 UTC
```js
// Generated by dart2js (NullSafetyMode.sound, trust primitives, omit checks, lax runtime type, csp, deferred-serialization, intern-composite-values), the Dart to JavaScript compiler version: 3.0.5.
self.$__dart_deferred_initializers__ = self.$__dart_deferred_initializers__ || Object.create(null);
$__dart_deferred_initializers__.current = function(hunkHelpers, init, holdersList, $) {
  var A = {
    FormData_FormData() {
      return new FormData();
    }
  };
  A = hunkHelpers.updateHolder(holdersList[55], A);
  var typesOffset = hunkHelpers.updateTypes([]);
};

$__dart_deferred_initializers__["IXojYeIX9u0fBaIagj3UrGzeQyA="] = $__dart_deferred_initializers__.current
```
```sh
> dart --version
Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "linux_x64"
```
Above are the contents of common partfile generated by dart2js. From what I can understand(using map file) this file is required by every partifile in which I've used `FormData()` and it appears to be doing nothing other than creating and returning `FormData` object, something that could be inlined?

**Comment by sigmundch** [comment] 2023-07-24 19:01
This seems closely related to https://github.com/dart-lang/sdk/issues/52870, so we may want to deduplicate as a single issue. cc @rakudrama

**Comment by rakudrama** [comment] 2023-07-25 06:12
I agree this is effectively a duplicate of #52870.
We also have a log-standing issue #9757 to improve inlining.

I am closing this as a duplicate of these two issues.

---
Notes

dart2js did not inline the `FormData` constructor because it looked too large or too difficult at the time the inlining decision was made.
```dart
  factory FormData([FormElement? form]) {
    if (form != null) {
      return FormData._create_1(form);
    }
    return FormData._create_2();
  }
```
Because the call was not inlined, the constructor method is referenced, so the definition is emitted.  Even if dart2js had enough information to decide to inline, it is not clear that inlining is the right choice for this constructor. The inlined code `new FormData()` is bigger than a minified call site like `A.xy()`. If there are enough call sites, declining to inline makes the program smaller.

**Closed by rakudrama** 2023-07-25 06:12 UTC
Labels: web-dart2js, area-web
