### ISSUE TITLE
Migration tool produces unnecessarily invalid overrides 

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#40320] opened 2020-01-24 19:20 UTC
I've tried to narrow this down to a smaller repro, but the obvious attempts don't work, and I can't track down why the tool is making the choices it is.  So currently, the only repro is to:

1) Download package:collection from github
2) Run the migration tool on it
3) Look at the analyzer errors for lib/src/wrappers.dart

The tool is choosing to make a number of overrides where the overridden parameter has type `Object?` take a non-nullable `Object` parameter, even though this is invalid. e.g.:

 
![image](https://user-images.githubusercontent.com/8484504/73096985-f71d4e00-3e9a-11ea-8e2f-cb29e4b813e6.png)

The reasoning it gives is not helpful:

![image](https://user-images.githubusercontent.com/8484504/73097039-1320ef80-3e9b-11ea-95f9-9f742c9ae089.png)

There are a number of other examples like this in the file. 

As best I can tell, I am correctly analyzing/migrating against the opted in SDK.  I am running the migration tool as:

```
~/src/dart-repo/sdk/xcodebuild/ReleaseX64/dart ~/src/dart-repo/sdk/pkg/dartfix/bin/dartfix.dart  upgrade sdk --sdk=/Users/leafp/src/dart-repo/sdk/xcodebuild/ReleaseX64NNBD/dart-sdk/ .
```

Going to the definition of `Iterable<E>` within the migration preview correctly shows me the migrated version of `Iterable`.

cc @stereotype441 @MichaelRFairhurst

**Comment by MichaelRFairhurst** [comment] 2020-01-24 19:38
Duplicate of #38699

**Comment by stereotype441** [comment] 2020-01-26 14:23
Actually upon closer inspection this looks unrelated to #38699 (I have prototyped a fix for #38699, which does address the repros documented there, but AFAICT it has no effect on the manifestation of this bug).

Interestingly, if I follow what I believe to be the correct steps for running the migration tool, I can't reproduce this bug.  However, there's one crucial step in running the migration tool today that people often miss (myself included, up until a few days ago): prior to running migration, you need to enable the `non-nullable` experiment for the package you're migrating by adding the following lines to the `analyzer` section of `analysis_options.yaml`:
```
  enable-experiment:
    - non-nullable
```
If you don't do this step, the bug manifests.

What I believe is happening is that if you don't add these lines to `analysis_options.yaml`, the migration tool ignores any `?`s present in the SDK sources, so it believes that (1) the method being overridden has signature `bool contains(Object element)` (hence it thinks that adding a `?` is not necessary to make the override valid), and (2) the method being called by `_base.contains(element)` has signature `bool contains(Object element)` (hence it thinks that adding a `?` would require adding an unconditional null check - hence the message "This value is unconditionally used in a non-nullable context").

If I'm right about what's happening, then this problem will go away when we ship NNBD (because the experiment will be turned on by default), so it won't be seen by end users.  But it's still a pretty big user trap for us while we're developing and using the migration tool on core libraries, so it may still be worth addressing.  I've filed #40329 to track it.

@leafpetersen, is it possible that you didn't add the necessary lines to `analysis_options.yaml` prior to running migration?  Note that due to #38347, the migration tool "helpfully" tries to do this step for you, but it does it too late, so if you look at your checkout of the collections package and see the necessary lines in `analysis_options.yaml` now, that doesn't necessarily mean that they were present before you ran the migration tool.

**Comment by leafpetersen** [comment] 2020-01-27 17:13
@stereotype441 Yes, I think that's essentially what happened (I did remember to edit it, but not to re-edit it after resetting the git repo).  I commented in more detail [here](https://github.com/dart-lang/sdk/issues/38699#issuecomment-578851177), including what I think is the correct workflow for me for now.  I'll give this a go again if I get some time this week, thanks for helping to debug!

**Comment by stereotype441** [comment] 2023-11-21 22:00
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.

**Closed by stereotype441** 2023-11-21 22:00 UTC
Labels: P2, NNBD, area-migration
