### ISSUE TITLE
Unix socket hanging issue in Cloud Run

### ISSUE THREAD

**Issue by davidmartos96** [dart-lang/sdk#47899] opened 2021-12-11 10:29 UTC
Hello, we have been migrating our infra to Cloud Run with Dart + Cloud SQL Postgres + Shelf, and while everything worked great with HTTP handlers, once we've added Cloud SQL, we've encountered a roadblock.
It seems like when the Cloud SQL database is opened via the Unix socket on Cloud Run, the HTTP server hangs, and connections afterwards don't work.
Locally, if the app uses connects to the Cloud SQL proxy with Unix sockets, it works ok. It's just in the Cloud Run environment where we are experiencing this issue.

We are also unsure where this issue belongs, because Dart Unix socket connections work with the Postgres library locally. Could it be possible that is an issue in the Dart io socket implementation?

What's interesting about it, it's that it connects and queries the database just fine one time, sending the HTTP response, but connecting again will make the Dart application unresponsive and the server hangs.

Here is a very simple demo that deploys a Cloud Run function that uses a Cloud SQL instance. To test the issue one only needs to connect to the root of the host and then refresh the page.

https://github.com/davidmartos96/cloud-run-dart-pg-issue

More information and discussion can be found here: https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/302

* Dart SDK Version: 2.15.0
* Cloud Run environment (Linux x64)

Forgive me if this doesn't fit here or if the issue is not that detailed. I hope someone in the team may know more about how the machines at Cloud Run are configured and how that could be conflicting with Dart. I've also tried a similar app with Node, using the same connection path as the Dart app and it works correctly on Cloud Run, so I believe it has to be an issue internally. At the same time, it works just fine locally. There is a docker compose in the shared repo that runs the app locally in the port 8080 with a local Postgres via Unix sockets.

**Comment by a-siva** [comment] 2021-12-13 15:57
//cc @brianquinlan

**Comment by marcusmonteirodesouza** [comment] 2022-02-22 22:11
I think I might be experiencing the same problem. When I deploy [this app](https://github.com/marcusmonteirodesouza/dart-shelf-realworld-example-app) to Cloud Run (via [terraform](https://github.com/marcusmonteirodesouza/dart-shelf-realworld-example-app/blob/master/deploy/gcp/terraform/main.tf)) and then make a HTTP request to it, in the majority of times the request hangs on indefinitely until it returns `504`, and sometimes it returns OK. I even opened an  [issue](https://issuetracker.google.com/issues/220618415) for that because it is puzzling.

**Comment by brianquinlan** [comment] 2022-03-17 22:10
I modified the example to use Isolates because I thought it would facilitate debugging.

The weird part is that, when I run the connection code in an isolate, it works! But if I run the non-isolate version, it hangs and it makes subsequent invocations of the isolate version hang too!

```dart
@CloudFunction()
Future<Response> function(Request request) async {
  late String message;
  if (request.url.queryParameters["isolate"]!.toLowerCase() == "y") {
    message = await isolateConnect();
  } else {
    message = await noIsolateConnect();
  }
  return Response.ok(message);
}

Future<String> noIsolateConnect() async {
  doConnection(null);
  return "Success!";
}

Future<String> isolateConnect() async {
  final Completer done = new Completer();
  late Timer timer;

  final rp = ReceivePort();
  var message = "This is unexpected";
  rp.listen((m) {
    print("Message is: $m");
    message = m;
    rp.close();
  }, onDone: () {
    print("Subscription is done");
    timer.cancel();
    done.complete(null);
  });
  final i = await Isolate.spawn(doConnection, rp.sendPort);
  i.addErrorListener(rp.sendPort);
  timer = Timer(Duration(seconds: 6), () {
    print("Cancelling the subscription");
    message = "Cancelled :-(";
    i.kill();
  });
  await done.future;
  return message;
}

void doConnection(SendPort? port) async {
  print("I'm the isolate");
  final dbConnection = getDbConnection();

  await dbConnection.open();
  print("DB connection opened");
  final rows = await dbConnection.query("SELECT 1");
  await dbConnection.close();
  print("DB connection closed");

  final res = rows.first.first as int;
  final now = DateTime.now();
  print('Response from database: $res\n\nDate: $now');

  port!.send('Response from database: $res\n\nDate: $now');
}
```

At one point I got an exception that looks like this but I'm not sure if it is related to the issue:
```
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193)
--
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#30     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322)
#29     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839)
#28     _StreamController.add (dart:async/stream_controller.dart:596)
#27     _StreamController._add (dart:async/stream_controller.dart:648)
#26     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
#22     _Socket._onData (dart:io-patch/socket_patch.dart:2314)
#21     _StreamController.add (dart:async/stream_controller.dart:596)
#20     _StreamController._add (dart:async/stream_controller.dart:648)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
#15     PostgreSQLConnection._readData (package:postgres/src/connection.dart:286)
#14     _PostgreSQLConnectionStateAuthenticating.onMessage (package:postgres/src/connection_fsm.dart:130)
#13     PostgresSaslAuthenticator.onMessage (package:postgres/src/auth/sasl_authenticator.dart:47)
#12     _Socket.add (dart:io-patch/socket_patch.dart:2193)
#11     _StreamSinkImpl.add (dart:io/io_sink.dart:136)
#10     _StreamController.add (dart:async/stream_controller.dart:596)
#9      _StreamController._add (dart:async/stream_controller.dart:648)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2068)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2094)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2346)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1906)
#0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1190)
SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = /cloudsql/dart-cloud-run-343123:us-central1:postgres-db/.s.PGSQL.5432, port = 0
```

**Comment by davidmartos96** [comment] 2022-03-17 23:32
@brianquinlan That's interesting! I wonder if it also fails with subsquent calls to a different long running isolate, instead of spawning a new one on each request.

**Comment by brianquinlan** [comment] 2022-03-18 01:12
OK, this is the code that hangs for me in the isolate test case:

```dart
        _socket = await Socket.connect(
                InternetAddress(host, type: InternetAddressType.unix), port)
            .timeout(Duration(seconds: timeoutInSeconds));
```

the `timeout` is *not* being honored.

**Comment by brianquinlan** [comment] 2022-03-18 23:07
Here is what I'm observing:
1. connecting to and closing the UNIX domain socket many times: works
2. connecting to the UNIX domain socket hangs after the Postgres connection has been created (even if closed)

**Comment by brianquinlan** [comment] 2022-03-23 17:19
My current hypothesis is that the gVisor containerization used in the gen1 Cloud Run execution environment implements a syscall differently than Dart expects.

You can work around that by using the gen2 execution environment, see [selecting an execution environment](https://cloud.google.com/run/docs/configuring/execution-environments).

I can no longer reproduce the issue if I change this repo:
https://github.com/davidmartos96/cloud-run-dart-pg-issue

with:
```diff
diff --git a/Makefile b/Makefile
		--add-cloudsql-instances=$(CLOUD_SQL_CONNECTION_NAME) \
		--set-env-vars=DB_USER=$(DB_USER),DB_PASS=$(DB_PASS),DB_NAME=$(DB_NAME),CLOUD_SQL_CONNECTION_NAME=$(CLOUD_SQL_CONNECTION_NAME) \
+		--execution-environment=gen2
```

My next step is to try to reproduce this using gVisor directly to see if this is a bug in Dart or gVisor.

**Comment by brianquinlan** [comment] 2022-03-25 22:12
I'm pretty sure that this is a gVisor issue.

I've filed a bug with the gVisor team: https://github.com/google/gvisor/issues/7331

Some follow up at https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/302

**Comment by brianquinlan** [comment] 2022-05-23 15:58
The docs for Cloud Run now say that docker is used as the execution environment:
https://cloud.google.com/run/docs/about-execution-environments

So is this still an issue?

**Comment by brianquinlan** [comment] 2022-05-31 15:41
If anyone hits this issue again, please reopen this bug.

**Closed by brianquinlan** 2022-05-31 15:41 UTC
Labels: area-library, library-io

**Comment by ryzizub** [comment] 2023-11-09 23:17
Its still an issue and only fix for that is changing env to gen2

**Comment by ryzizub** [comment] 2023-11-09 23:17
I would consider reopen this bug, cause it took me a while found out what's happening

**Comment by brianquinlan** [comment] 2023-12-06 19:40
That's right, you need to use gen2.

[Our documentation for Cloud Run](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/docs/quickstarts/03-quickstart-cloudrun.md#get-a-copy-of-the-hello-example) says that you should use gen2:
![image](https://github.com/dart-lang/sdk/assets/8851008/2d304136-319d-419e-aea2-386d2d6b89f3)

Is there another place that we should add this?

**Comment by ryzizub** [comment] 2023-12-12 21:07
I think mentioning it on google cloud run documentation is just fine. I was using dart frog backend where it's not mentioned. Created PR there to fix it
