### ISSUE TITLE
num.compareTo() incorrectly compares integers and doubles

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#31917] opened 2018-01-16 21:02 UTC
With fixed-size integers,

```dart
(-9223372036854775808).compareTo(-1.7976931348623157e+308)
```

results in 0, but should be 1.

**Comment by alexmarkov** [comment] 2018-01-16 21:12
The following case doesn't work both with arbitrary-size integers and with fixed-size integers:

(-9223372036854776000.0).compareTo(-9223372036854775807) = 0
(-9223372036854775807).compareTo(-9223372036854776000.0) = 1

**Comment by lrhn** [comment] 2018-01-17 06:54
Duplicate of #4018.

**Comment by alexmarkov** [comment] 2018-01-17 15:57
@lrhn, is it really a duplicate? #4018 says about number comparisons in general, which probably includes comparison operators. If #4018 is only about num.compareTo(), then please clarify it in that issue and I'll close it altogether with this one.

This issue is about num.compareTo(), which already has more precise logic when doing int.compareTo(double) but not when double.compareTo(int), and has new problems due to clamping of doubles while they are converted to integers with new fixed-size integers.

**Comment by alexmarkov** [comment] 2018-01-18 17:14
> The compareTo method should be compatible with the comparison operators on all normal numbers (it's more fine-grained for 0.0 vs -0.0 and giving NaN a position in the order).

Currently, it's not the case. num.compareTo() is more fine-grained when comparing int with double than comparison operators. This behavior makes it non-symmetric as reverse comparison of double with int is not precise:

```
(-9223372036854775807).compareTo(-9223372036854776000.0) = 1
-9223372036854775807 <  -9223372036854776000.0 = false
-9223372036854775807 <= -9223372036854776000.0 = true
-9223372036854775807 == -9223372036854776000.0 = true
-9223372036854775807 >= -9223372036854776000.0 = true
-9223372036854775807 >  -9223372036854776000.0 = false
(-9223372036854776000.0).compareTo(-9223372036854775807) = 0
-9223372036854776000.0 <  -9223372036854775807 = false
-9223372036854776000.0 <= -9223372036854775807 = true
-9223372036854776000.0 == -9223372036854775807 = true
-9223372036854776000.0 >= -9223372036854775807 = true
-9223372036854776000.0 >  -9223372036854775807 = false
```

So, the question is: how we should fix num.compareTo()?
What is more preferable -

* Make num.compareTo consistent with comparison operators by reducing precision of int.compareTo(double).

OR

* Keep more precise behavior of int.compareTo(double) and make double.compareTo(int) consistent with int.compareTo(double) by improving its precision too?

/cc @lrhn @leafpetersen

**Comment by lrhn** [comment] 2018-01-19 08:30
We should make both correct. That means comparing the actual numerical values of integers and doubles, not converting one to the other before comparing. 
The documentation and intent is clear, the VM just haven't implemented it correctly yet. Doing the right thing will make `num` comparisons correct and transitive.

It's not a simple library code change since some comparisons are compiled directly to native code, and those need to be changed to behave the same as the library code.

**Closed** 2018-01-22 18:24 UTC
Labels: Type: bug, area-vm
