### ISSUE TITLE
DDC throws type error instead of noSuchMethod when number of arguments is wrong

### ISSUE THREAD

**Issue by ErikCorryGoogle** [dart-lang/sdk#32088] opened 2018-02-08 13:38 UTC
See the test corelib_2/null_nosuchmethod_test/01

This invocation of noSuchMethod has the wrong number of arguments (2, should be 1) and so should call the noSuchMethod method on the function (the function happens to be the standard noSuchMethod function).  Instead if throws a type error because the first argument is a string, where it should be an invocation.

**Comment by vsmenon** [comment] 2018-02-23 15:18
@jmesserly 

We should cleanup the treatment of these `dcall` errors & improve the error messages and stack traces.  All these are supposed to be NSM (could be different implementations of that type I suppose):

- Wrong # of arguments
- Wrong parameter type (we throw a type error, but don't tell you the function and param slot that failed)
- Method doesn't exist

**Comment by eernstg** [comment] 2018-02-23 15:24
Wrong parameter type is tricky. I think the following would then be an infinite loop:
```dart
class MyInvocation extends Invocation {}
class A { noSuchMethod(covariant MyInvocation) => print("Arrived!"); }

main() => (new A() as dynamic).foo();
```

**Comment by jmesserly** [comment] 2018-02-23 21:07
> Wrong parameter type is tricky. I think the following would then be an infinite loop:

slight correction to the program (needs parameter name `i`, otherwise `MyInvocation` is the param name instead of the type)
```dart
abstract class MyInvocation extends Invocation {}
class A { noSuchMethod(covariant MyInvocation i) => print("Arrived!"); }

main() => (new A() as dynamic).foo();
```
... but yeah we need to keep that as a TypeError. We could certainly add more information to TypeErrors however, and we can fix this bug (wrong number of arguments is handled before type checking, and calls nSM)

**Comment by eernstg** [comment] 2018-02-26 09:16
> .. slight correction to the program

Right, thanks!

**Comment by jmesserly** [comment] 2018-03-28 17:33
As @matanlurey mentioned in https://github.com/dart-lang/sdk/issues/32564#issuecomment-376664813, we should make similar improvements to DDC's TypeError message.

**Comment by jmesserly** [comment] 2018-03-30 20:33
https://github.com/dart-lang/sdk/issues/32653 is possibly a dupe of this

**Comment by jmesserly** [comment] 2018-03-30 23:43
https://dart-review.googlesource.com/c/sdk/+/48940

**Closed** 2018-04-12 00:33 UTC
Labels: Type: bug, area-dev-compiler
