### ISSUE TITLE
[Sealed class] Analysis server / IDE support work

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#51291] opened 2023-02-06 23:28 UTC

**Comment by srawlins** [comment] 2023-02-06 23:38
CC @kallentu @bwilkerson

**Comment by mit-mit** [comment] 2023-02-23 14:16
@srawlins @bwilkerson @kallentu what remains here? 

It seems to work:

<img width="1047" alt="Screenshot 2023-02-23 at 15 16 19" src="https://user-images.githubusercontent.com/13644170/220933005-68071397-0a1e-4682-b94c-b5242c957b34.png">

**Comment by bwilkerson** [comment] 2023-02-23 15:40
Sorry for the confusion. We've been tracking this work on https://github.com/dart-lang/sdk/issues/50737 because we'd already started using the other issue before this one was created and just never took the time to tease the work apart. We probably should have done that.

To summarize, though, there's some work to do in code completion (CL is in progress) to not propose sealed classes in places where they shouldn't be proposed. There's also some work to do to make sure that our quick fixes and quick assists have been updated where necessary to work with `sealed` and other class modifiers. I'm hoping that the former can land before beta 2, but the other will be less noticeable if if slips to beta 3.

**Comment by srawlins** [comment] 2023-03-02 18:03
We can 100% close this issue as duplicate of #50737 if that is how we're functionally tackling this work. No downside to that from a tracking perspective.

**Closed** 2023-04-04 04:47 UTC
Labels: area-analyzer, analyzer-server, P2, type-enhancement
