### ISSUE TITLE
add CI fuchsia builder

### ISSUE THREAD

**Issue by gaaclarke** [dart-lang/sdk#41255] opened 2020-03-30 18:31 UTC
Dart doesn't have CI that is building against Fuchsia.  This can cause build failures downstream like so: https://github.com/flutter/flutter/issues/53590

**Comment by a-siva** [comment] 2020-03-30 18:35
I believe this is a duplicate of https://github.com/dart-lang/sdk/issues/41076

**Closed by a-siva** 2020-03-30 18:35 UTC
Labels: closed-duplicate
