### ISSUE TITLE
BigInt.modPow returns: !remainder._isNegative': is not true

### ISSUE THREAD

**Issue by dbarzdys** [dart-lang/sdk#33405] opened 2018-06-10 01:50 UTC
I'm trying to use BigInt.modPow, but I always get this error:
```
'dart:core/runtime/libbigint_patch.dart': Failed assertion: line 2743 pos 14: '!remainder._isNegative': is not true.
  dart:core             _BigIntImpl.modPow
```
Example:
```dart

void main() {
  const A = '-7003a3cac2bac4e494d749ae101f7ede8f11dac594fea5f51e15826021d734df6ecb6f67d74e2bb0f47ee39cb79fae059734c95d1eacb0340af64c05b83a4f70a737363c3799d38c23b7833622d89036b4649bcc7b749037f4954dac6abe5566c97cb6ac81ff8a09f8c71c7f08061720483b592517a608088ddb4c2e460ad1a73abbadbda0779221751cf22f1191e3be531505c833fede908a17581a9ae96f3c0258edcfe71786b7cf307f67eb9ecd8656d0fd397b0215bfb79efb314299d3e9db70b31a34f5f67e6c5e166cfa3e0bf45837c5d64fa3930a91a06b94840b4773d81280ed2af141747a6ac99d882a59f47b15ce8c1d716ead646b139b928869902225c85ea220b90e290181f271ed087bb6972dfe7d674b09e44c268128340d9172182732990a70af51d589c89f39d8f5dac659161aa0a32774728e15e25bad2960b4eacb8b670581b1c431201192c8bdbcc9256ef9e863b589f22813158050cdaf5da69f83819639f5a183c7ffe61ba1582d6ace35c8318dfdc597d016e70b7bb115fc1a7a3481c3a6296f1504e5ccd9b14e641acb2aa329c3d69b5e8f1609eec8b5b5a2b0192e9f21e7e3960c52975a70cf934c32e67799c40863b23c9579a551df4b179e6e2094f86c9fffa4bb5634202e094d380565b44cec833db25721010dd5df766204ae8d1e8680075f261801aee047d0ac576b9b10710de54e6eaa94648a7fba1576e66ea44f4bb7f6b941268a8d920bfc2727f82457f92cc2a016cb';
  const B = '73ac14b30fe9cb8275a7410a06ce5de8a60fe0a02e236197182996ca5886fd4e6937555f1f02ed4183ff7f097f76051f286dbb1b24751795cb793b1b81ac259';
  const C = 'ffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3404ddef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c245e485b576625e7ec6f44c42e9a637ed6b0bff5cb6f406b7edee386bfb5a899fa5ae9f24117c4b1fe649286651ece45b3dc2007cb8a163bf0598da48361c55d39a69163fa8fd24cf5f83655d23dca3ad961c62f356208552bb9ed529077096966d670c354e4abc9804f1746c08ca18217c32905e462e36ce3be39e772c180e86039b2783a2ec07a28fb5c55df06f4c52c9de2bcbf6955817183995497cea956ae515d2261898fa051015728e5a8aaac42dad33170d04507a33a85521abdf1cba64ecfb850458dbef0a8aea71575d060c7db3970f85a6e1e4c7abf5ae8cdb0933d71e8c94e04a25619dcee3d2261ad2ee6bf12ffa06d98a0864d87602733ec86a64521f2b18177b200cbbe117577a615d6c770988c0bad946e208e24fa074e5ab3143db5bfce0fd108e4b82d120a92108011a723c12a787e6d788719a10bdba5b2699c327186af4e23c1a946834b6150bda2583e9ca2ad44ce8dbbbc2db04de8ef92e8efc141fbecaa6287c59474e6bc05d99b2964fa090c3a2233ba186515be7ed1f612970cee2d7afb81bdd762170481cd0069127d5b05aa993b4ea988d8fddc186ffb7dc90a6c08f4df435c934063199ffffffffffffffff';
  final aInt = BigInt.parse(A, radix: 16);
  final bInt = BigInt.parse(B, radix: 16);
  final cInt = BigInt.parse(C, radix: 16);
  final res = aInt.modPow(bInt, cInt);
}
```
Dart version: 2.0.0
OS: ArchLinux

**Comment by dbarzdys** [comment] 2018-06-10 12:08
Update:

Found a function that does modPow correctly:

```dart
BigInt _modPow(BigInt b, BigInt e, BigInt m) {
    if (e < BigInt.one) {
      return BigInt.one;
    }
    if (b < BigInt.zero || b > m) {
      b = b % m;
    }
    var r = BigInt.one;
    while (e > BigInt.zero) {
      if ((e & BigInt.one) > BigInt.zero) {
        r = (r * b) % m;
      }
      e >>= 1;
      b = (b * b) % m;
    }
    return r;
  }
```

**Comment by crelier** [comment] 2018-06-11 17:16
I am not able to reproduce this issue.
Can you be more specific about your platform and the version of the dart SDK you are using?

Note that a bigint issue on arm64 was fixed on May 25 and may not have made it to you yet.

On both x64 and arm64 architectures, with the current Dart SDK head of tree, I get the following decimal result:
999079179839390885244951896544645571604661439602974563222757988243780407645037336669993387990884857394370622461196808219193869920756876729156535615802774490482211290990835935686004732734275387761052477236346513555061605138244925165384662337810134171292569778285662506367560959802037498939145542122908343331686094960161648453747010492819921436989343108839552199758484836990461296808986301072982810839537730384999346573369520208187912041730224468360637618196187029374894937834112101624665077513954915054315349953731207233056731647711784747372899690606940550686793251053822283959364534363547839312282938798621705388145026636603944138268674903809469667455477719950876982606468458579359970017006118868382859890413782495359790213375696765183481285798145896120424837957139593905433961704589583405131219742206501516141102279875239113938156842567741399693912543055274366872835403251084941414820110476284172936007548995279445079370877769150044054283949410367135854525984479508722289649840440595123346092793566466705127361093982086715269440571476035828272109256654353043046532037374715869003015170183088344605516723416206626240909089834269080670455118995481648312353382544456976232827392681107058718876713674043328119091406582382941713104628030

**Comment by crelier** [comment] 2018-06-11 19:44
Never mind. I was reminded to enable asserts and I do indeed get the assert fault.

**Comment by dbarzdys** [comment] 2018-06-12 06:14
Result should be:

45309701573761621434650823301883974226607621389160445799830768200557764377285354040450658678924926535740963276693554472666257158513618725360683057214153936976934710876049844076977496586916980542293757968021537455247550535910772294962514608583942363864715216609622315266139962009679240033306292856547553678620238508429102904618128289430450832128625876354770244777202578531545854829651840383195609781740092289995681416909153250441632350006695297938367893309259148293259508400770564337015719062948284061773997681215980545849796360292971945198767232357182015487789525653510168411636737800229001917035386104504035325429114368520617827645213995943992067892492291742379334145192220371470057493249685977722723574641664119730654096207354010625028011241893783937010504296786972335464234159042005483805144387713557792314567174158771277540081941622147194978423699708520771303517819594439702625274148486149440418028555648602480159118346241044149034627716755217093570142180962180205500810767824269080891624208488277632861580880679127984420265950066970434332426634343772709229410571397458507104299047566144703612388220993629611994863216915605316090008257484733485148980095851225770375415192452846825163350072443986855909045349387662443821653825217

**Closed** 2018-06-12 15:14 UTC
Labels: area-vm

**Comment by crelier** [comment] 2018-06-12 15:52
Yes, that is the result you should be getting now. Thanks for the report.

**Comment by cardmaker99** [comment] 2019-11-03 23:55
> 
> 
> Update:
> 
> Found a function that does modPow correctly:
> 
> ```dart
> BigInt _modPow(BigInt b, BigInt e, BigInt m) {
>     if (e < BigInt.one) {
>       return BigInt.one;
>     }
>     if (b < BigInt.zero || b > m) {
>       b = b % m;
>     }
>     var r = BigInt.one;
>     while (e > BigInt.zero) {
>       if ((e & BigInt.one) > BigInt.zero) {
>         r = (r * b) % m;
>       }
>       e >>= 1;
>       b = (b * b) % m;
>     }
>     return r;
>   }
> ```

can you show the struct BigInt ? what is the type of BigInt.one and BigInt.zero ?
