### ISSUE TITLE
dart:io HttpClient's request force-transforms the header names to lowercase

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#33501] opened 2018-06-19 16:10 UTC
The toLowerCase() transformation may be useful when processing the response headers, but when sending, the server could be checking the cased version and fail if it doesn't find it that way. (Yeah, bad server.)

**Comment by zoechi** [comment] 2018-06-20 07:31
Sounds like #25120

**Comment by isoos** [comment] 2018-06-20 07:40
Yeah, very similar problem.

**Comment by isoos** [comment] 2019-08-26 17:03
I think the reason for the lowercase transform is HTTP/2: it standardizes all header names to be lowercase, and with that it makes somewhat sense to do the same here.

**Comment by shaxxx** [comment] 2019-09-06 12:27
I've spent half a day debugging to find out http client forces headers as lowercase.
Guess what, I'm stuck with 10 year old client devices with HTTP server's using case sensitive headers.
Why force anything? Let me decide what I want to send with **MY** request

**Comment by HoLLy-HaCKeR** [comment] 2019-09-06 13:34
Same here, I ended up copying over a bunch of code from the SDK after debugging a broken WebSocket connection for a few days. I get the rationale but this isn't documented anywhere which is really annoying.

**Comment by shaxxx** [comment] 2019-09-09 07:25
Since I can't say to thousands of users to update their receivers or fix their HTTP server implementation, and I don't expect Dart team to change this behavior, I had no other choice but to change default HTTP client. 

I took current HttpClient from master branch (requires Dart 2.5, Flutter 1.8+), changed it to leave headers alone and packed in the package. Hopefully it will save someone someone from crying and pulling up their hair. Just use it as a drop in replacement for HttpClient.  Tested and works with Dio.

You can find package [HERE](https://pub.dev/packages/alt_http/).

**Comment by a-siva** [comment] 2019-09-17 21:51
There seems to be a suggestion that we should add an option to not change the case.

**Comment by ZichangG** [comment] 2019-09-18 17:22
@lrhn Any idea? This would be a breaking change if adding one more flag.

**Comment by ZichangG** [comment] 2019-09-18 18:13
To be more specific, A flag is probably needed to be passed from httpclient all the way down to httpheader.
https://github.com/dart-lang/sdk/blob/a1fdfb8fc8abb758f17c070cebfea3026ca53973/sdk/lib/_http/http_impl.dart#L2071
https://github.com/dart-lang/sdk/blob/a1fdfb8fc8abb758f17c070cebfea3026ca53973/sdk/lib/_http/http_impl.dart#L770
https://github.com/dart-lang/sdk/blob/a1fdfb8fc8abb758f17c070cebfea3026ca53973/sdk/lib/_http/http_impl.dart#L1078


Inside headers, 
https://github.com/dart-lang/sdk/blob/4102e63f378ea585c6c6e02107e60017912aadde/sdk/lib/_http/http_headers.dart#L41

https://github.com/dart-lang/sdk/blob/4102e63f378ea585c6c6e02107e60017912aadde/sdk/lib/_http/http_headers.dart#L44

https://github.com/dart-lang/sdk/blob/4102e63f378ea585c6c6e02107e60017912aadde/sdk/lib/_http/http_headers.dart#L44

**Comment by shaxxx** [comment] 2019-09-18 22:14
Thats the one way to look at it.
Why would HttpClient assume anything?
You have bunch of Abstract classes in HTTP client that are used only as internal implementations. Take HttpHeaders for instance. It's abstract, and HttpClient uses one single concrete implementation, which is internal, and has no way to use some other implementation.
Why making abstract class in a first place if you're forcing it to be used in a single way?
Good and probably non breaking start would be to 
- move internal implementations to separate public classes/files
- refactor existing calls to new classes
- add a way for user to provide specific implementation of abstract class
- if no specific implementation is provided use default one
Last two can be done as optional class constructor with default value params (better) or as public properties (less transparent IMHO).
I'm speaking from top of my head now, but this shouldn't breake anything.
Dart has no reflection, and internal calls can be easily refactored.
And once you're there, in default HttpHeaders expose map of all headers as public property, leave current behaviour, as is, but let user modify the map directly however he/she wants. That's extra, I'd be fine if I could make HttpClient use my HttpHeaders instead default ones.

Just my 2 cents.

**Comment by songfei** [comment] 2019-11-25 07:01
any update?

**Comment by ZichangG** [comment] 2019-11-25 19:40
Still in progress. I expect [this cl](https://dart-review.googlesource.com/c/sdk/+/119100) to be landed within next few weeks.

**Comment by shaxxx** [comment] 2019-12-27 19:00
Is there any ETA when this will land in a Dart release?

**Comment by ZichangG** [comment] 2019-12-28 02:00
The cl is pretty much done. But it has to wait for breaking change request getting approved.

**Comment by cdm2012** [comment] 2019-12-29 09:36
Creating an API Client using HTTPClient with the following request headers:
```
I/flutter (32611): headers: {
I/flutter (32611):   "Content-type": "application/json",
I/flutter (32611):   "Accept": "application/json",
I/flutter (32611):   "Authorization": "Bearer: E7HlYmfiXwhLQT1nYApOAE4wqhvCZZXndrT7kiRv8tUBycj3npVnYwnQnH34"
I/flutter (32611): }
I/flutter (32611): 
I/flutter (32611): 
I/flutter (32611): 
I/flutter (32611): request.headers: 
I/flutter (32611): content-type: application/json
I/flutter (32611): accept: application/json
I/flutter (32611): authorization: Bearer: E7HlYmfiXwhLQT1nYApOAE4wqhvCZZXndrT7kiRv8tUBycj3npVnYwnQnH34
```
And the server (nginx/1.15.8) is returning a 400 error:
```
I/flutter (32611): <html>
I/flutter (32611): <head><title>400 Bad Request</title></head>
I/flutter (32611): <body>
I/flutter (32611): <center><h1>400 Bad Request</h1></center>
I/flutter (32611): <hr><center>nginx/1.15.8</center>
I/flutter (32611): </body>
I/flutter (32611): </html>
```
Using the same headers in android with the following request headers:
```
E: Called doInBackground w/ headers: [Accept: application/json, Content-type: application/json, Authorization: Bearer E7HlYmfiXwhLQT1nYApOAE4wqhvCZZXndrT7kiRv8tUBycj3npVnYwnQnH34]
```
And the same server is returning a 200 response, so I'm really looking forward to integrating the change by @ZichangG : https://github.com/dart-lang/sdk/issues/39657#issue-533108500

**Comment by accek** [comment] 2019-12-29 11:07
> ```
> I/flutter (32611):   "Authorization": "Bearer: E7HlYmfiXwhLQT1nYApOAE4wqhvCZZXndrT7kiRv8tUBycj3npVnYwnQnH34"
> ```
It looks like the colon ```:``` after ```Bearer``` should not be there.

**Comment by cdm2012** [comment] 2019-12-29 17:36
Thanks @accek, that was definitely an oversight. I just tried it again with these headers:

```
I/flutter ( 3473): headers: {
I/flutter ( 3473):   "Content-type": "application/json",
I/flutter ( 3473):   "Accept": "application/json",
I/flutter ( 3473):   "Authorization": "Bearer E7HlYmfiXwhLQT1nYApOAE4wqhvCZZXndrT7kiRv8tUBycj3npVnYwnQnH34"
I/flutter ( 3473): }
I/flutter ( 3473): 
I/flutter ( 3473): 
I/flutter ( 3473): 
I/flutter ( 3473): request.headers: 
I/flutter ( 3473): content-type: application/json
I/flutter ( 3473): accept: application/json
I/flutter ( 3473): authorization: Bearer E7HlYmfiXwhLQT1nYApOAE4wqhvCZZXndrT7kiRv8tUBycj3npVnYwnQnH34
```

But the result was still the same:
```
I/flutter ( 3473): responseString: <html>
I/flutter ( 3473): <head><title>400 Bad Request</title></head>
I/flutter ( 3473): <body>
I/flutter ( 3473): <center><h1>400 Bad Request</h1></center>
I/flutter ( 3473): <hr><center>nginx/1.15.8</center>
I/flutter ( 3473): </body>
I/flutter ( 3473): </html>
```
I didn't think to add the nginx logs before, but here are all the nginx logging from last night:
```
2019/12/29 03:15:05 [error] 3653#3653: *65 open() "/var/www/reely-api/testing/public/api/version" failed (2: No such file or directory), client: 10.0.0.5, server: reely.the-mac.local, request: "POST /api/version HTTP/1.1", host: "reely.the-mac.local"
```
Currently there are no logs showing, but I think that error was from using the wrong url protocol.

**Comment by sortie** [comment] 2020-01-06 12:59
@accek We're working to make the breaking change, but it's a workaround for bad servers. The standard requires the protocol headers are case insensitive and you get the server fixed instead of debugging the issue here. I assume those bearer tokens are for debugging and have no actual access.

**Comment by cdm2012** [comment] 2020-01-06 14:07
Yes the token is not usable @accek , it only worked for a private internal server. Could the solution be to use the HTTP/2 standard optionally @isoos , similar to @ZichangG 's solution (but an opt in solution)?

@sortie I looked into the Server side, and according to the creator of Laravel, [Laravel literally does not touch request headers in any form or fashion](https://github.com/laravel/framework/issues/1639#issuecomment-19438700).

**Comment by DartMen** [comment] 2020-02-13 22:55
Issues are to be expected when forcing things like these..

Same as dictating the multipart_request boundary to "dart-http-boundary-xxxx" in https://github.com/dart-lang/http/issues/295

**Comment by mit-mit** [comment] 2020-02-20 08:22
Landed in https://github.com/dart-lang/sdk/commit/d39cdf03f83a4b76d0bda122b3745109fcd03299

**Comment by MiriDevAndro** [comment] 2020-03-19 11:00
anyone has find an solution ?

**Comment by isoos** [comment] 2020-03-19 11:07
@MiriDevAndro: If I understand correctly, the fix has been landed, it may be in the 2.8.0-dev branch already, and it will be in 2.8.0 stable.

**Comment by MiriDevAndro** [comment] 2020-03-19 11:11
@isoos  yes i have see but i dont have this path/file sdk_nnbd/lib/_http/http.dart in my sdk , i use windows andoid studio and i have download sdk from official page

**Comment by MiriDevAndro** [comment] 2020-03-19 14:24
> Landed in [d39cdf0](https://github.com/dart-lang/sdk/commit/d39cdf03f83a4b76d0bda122b3745109fcd03299)

there is no such dir like sdk_nnbd/lib/_http/http.dart on my sdk

**Comment by a-siva** [comment] 2020-03-19 16:09
@MiriDevAndro the fix has landed in sdk/lib/_http/http.dart the other path (sdk_nnbd) that you refer to is an internal branch of the libraries that we are using for the null safety feature.

**Comment by MiriDevAndro** [comment] 2020-03-19 16:19
> @MiriDevAndro the fix has landed in sdk/lib/_http/http.dart the other path (sdk_nnbd) that you refer to is an internal branch of the libraries that we are using for the null safety feature.

why then is not working , i have modify all like thi d39cdf0

**Comment by a-siva** [comment] 2020-03-19 16:24
What is not working, can you send us a test case that still exhibits the problem,
It looks like you are not using the sdk as is and instead have your own version of the build into
which you are applying this patch, it is possible there is some inconsistency there.

**Comment by MiriDevAndro** [comment] 2020-03-19 17:06
@a-siva im using flutter in android studio ,how can i fix lowercase headers?

**Comment by mit-mit** [comment] 2020-03-19 17:15
@MiriDevAndro you might have an older version of the Dart SDK that doesn't have this change. If you run `flutter --version`, the Dart SDK needs to be ` 2.8.0-dev.10.0` or later.

**Comment by MiriDevAndro** [comment] 2020-03-19 17:20
@mit-mit thnx for answers , can i use dart sdk 2.8.0-dev.10.0 +  in android studio manually or not will work?

**Comment by mit-mit** [comment] 2020-03-20 09:15
If you are doing Flutter development, you need to upgrade your Flutter SDK. That contains an embedded Dart SDK inside it (as reported by `flutter --version`).

**Comment by MiriDevAndro** [comment] 2020-03-20 09:21
The flutter channel dev  dart sdk 2.8.0-dev.15.0 has  to much bug and stable has ver dart sdk 2.7.0 max

**Comment by mit-mit** [comment] 2020-03-20 09:25
Sorry, you will have to wait for the dev channel to stabilize then.

**Comment by MiriDevAndro** [comment] 2020-03-20 09:27
ok thnx for explanation

**Comment by eirikb** [comment] 2020-03-31 07:29
I'm also struggling with a server only accepting cased headers.  
How can I use the above solution? 
 
Tried:
```dart
final body = '{"hello":"world"}';
final client = new HttpClient();
final req = await client.put('localhost', 8000, '/');
req.headers.add('Content-Type', 'application/json', preserveHeaderCase: true);
req.headers.add('Content-Length', body.length, preserveHeaderCase: true);
req.write(body);
await req.close();
```
Versions:
```bash
> flutter --version
Flutter 1.15.21 • channel master • /home/eirikb/.cache/yay/flutter-git/flutter
Framework • revision e2b4edd286 (3 weeks ago) • 2020-03-13 02:46:02 -0400
Engine • revision d7a00b8b09
Tools • Dart 2.8.0 (build 2.8.0-dev.14.0 eb9c26bd37)
```
But headers are still lower-cased.  
Tested by running Flutter in Android Emulator and `dart` in terminal:
```bash
> /opt/flutter/bin/cache/dart-sdk/bin/dart --version
Dart VM version: 2.8.0-dev.14.0.flutter-eb9c26bd37 (Fri Mar 13 01:41:41 2020 +0000) on "linux_x64"
> /opt/flutter/bin/cache/dart-sdk/bin/dart api_test.dart
```
Output from `nc` (also see same result in Wireshark):
```bash
> nc -l -p 8000
PUT / HTTP/1.1
user-agent: Dart/2.8 (dart:io)
content-type: application/json
accept-encoding: gzip
content-length: 17
host: localhost:8000

{"hello":"world"}
```

**Comment by shaxxx** [comment] 2020-05-19 13:30
@mit-mit I'm having exactly the same issue as @eirikb . 
`preserveHeaderCase` as far as I can see is currently not working.
Using 
> Dart VM version: 2.8.2 (stable) (Mon May 11 15:06:42 2020 +0200) on "windows_x64"

Can someone please explain what's current status on this, is it working, if yes how, if not what's happening with it? Should this be re-opened?

**Comment by zichangg** [comment] 2020-05-19 18:12
@shaxxx Sorry for the delayed reply. Code reviews for my fix took some time, I'll land the fix today.

**Comment by shaxxx** [comment] 2020-05-19 18:21
@zichangg Thanks for the update, as far I can understand preserveHeaderCase should work in the next flutter stable?
It wasn't really clear from this thread if this is currently working or not since no one confirmed this is still an issue and this bug is closed. Is there another bug tracking progress on this?

**Comment by a-siva** [comment] 2020-05-19 18:24
reopening issue so that we can track when the bug fix CL lands and update on when it gets rolled into Flutter. You will probably see it in the dev channel first.

**Closed** 2020-08-24 20:49 UTC
Labels: P2, area-library, library-io, type-enhancement

**Comment by talregev** [comment] 2021-07-01 03:58
reopening this issue because force lowercase http header make it breakable from legacy server that don't check for small letter. and http1 header is sensitive case. 
Please make by default non force lowercase http header, and add an option to people to want to force it. 
It break my communication with the server. 
Also http in web, doing as http should. it non force lower case and adding automatically content-length in the header. 
But, http in dart-io force you lowercase http header and not adding automatically content-length. 
This is bad inconsistency. http request should be the same across all the platform. and doing the same as http in web.

**Comment by MiriDevAndro** [comment] 2021-07-01 06:50
im okay with you , they should insert support for http 1.1

**Comment by cesuper** [comment] 2021-09-04 20:18
Hey, 

I also miss the case sensitive version of the headers. Any update in this topic?

**Comment by talregev** [comment] 2021-09-04 23:00
@zichangg Why you hurt the community?

**Comment by cesuper** [comment] 2021-09-04 23:02
How u mean I hurt? I am not inted to...

**Comment by talregev** [comment] 2021-09-05 17:43
@camsteffen my last message  I was write to @zichangg

**Comment by mraleph** [comment] 2021-09-06 08:53
@cesuper @talregev this issue was closed because [`HttpHeaders`](https://api.dart.dev/dev/2.15.0-82.0.dev/dart-io/HttpHeaders-class.html) [`add`](https://api.dart.dev/dev/2.15.0-82.0.dev/dart-io/HttpHeaders/add.html) and [`set`](https://api.dart.dev/dev/2.15.0-82.0.dev/dart-io/HttpHeaders/set.html) methods were expanded with explicit support for case-sensitive header via `preserveHeaderCase: true` named argument.

If this does not work for you (meaning: you set `preserveHeaderCase: true` but headers are sent in forced lowercase) then you should file a separate issue and provide a minimal reproduction of the issue. 

There are no plans to switch to case-sensitive headers by default.

**Comment by MiriDevAndro** [comment] 2021-11-08 11:11
Any update on this?
I think that this bug is on native compiled library, any idea ?

**Comment by mraleph** [comment] 2021-11-08 11:24
@MiriDevAndro https://github.com/dart-lang/sdk/issues/33501#issuecomment-913470214

**Comment by MiriDevAndro** [comment] 2021-11-08 11:45
@mraleph  why dev of flutter just use rules like java does , is very simple just copy java dude.

**Comment by mraleph** [comment] 2021-11-08 11:51
@MiriDevAndro I don't understand your question and in any case your question is off-topic for this bug.

**Comment by MiriDevAndro** [comment] 2021-11-08 11:59
@mraleph im saying that java is perfect but can be modify simply bytecode in other way flutter it compiles code in native so this is good but is not portable as java in implementation.
