### ISSUE TITLE
import statement pathname can cause incorrect Type resolution

### ISSUE THREAD

**Issue by speby** [dart-lang/sdk#37245] opened 2019-06-13 03:03 UTC
Using Dart version: 2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "macos_x64"

Attached .ZIP contains a tiny set of Dart files and a main() method to print stuff to the console. Basically, if you have 2 different Dart files reference a class and you add 2 slashes in the pathname in the import statement, it will throw off the ability to correctly type-check the class in the other file.

_Notice the 2 slashes in the import statement below (this is what causes the issue):_
**bin/main.dart**
```
// To test this, leave 2 slashes in the import statement below to see the type fail to recognize in the call to compareInstance.
// Change it to a single-slash and it will work as intended.
import 'some_classes//some_classes.dart';
import 'another_class.dart';

main(List<String> arguments) {
  MyClass my_cls = MyClass();
  AnotherClass another_cls = AnotherClass();

  another_cls.compareInstance(my_cls);

}
```

**bin/another_class.dart**
```
import 'some_classes/some_classes.dart';

class AnotherClass {
  void compareInstance(Object my_class) {
    if (my_class is MyClass) {
      print("Yes it is an instance of MyClass");
    } else {
      print("No it is not an instance of MyClass");
    }
  }
}
```

**bin/some_classes/some_classes.dart**
```
class MyClass {
  final String text = "Hi!";
}
```

I am not certain but this may be related to [this issue](https://github.com/dart-lang/sdk/issues/33149).

[classname_clash.zip](https://github.com/dart-lang/sdk/files/3284009/classname_clash.zip)

**Comment by srawlins** [comment] 2023-05-01 03:32
Duplicate of https://github.com/dart-lang/sdk/issues/36337

**Closed by srawlins** 2023-05-01 03:32 UTC
Labels: area-analyzer, type-bug, P4
