### ISSUE TITLE
Web workers don't work for webdev serve or webdev build --no-release

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#34928] opened 2018-10-25 14:32 UTC
* Dart SDK Version 2.1.0-dev.8.0
* MacOS Mojave
* Chrome 70

`main.dart`
```dart
import 'dart:html';

void main() {
  if (Worker.supported) {
    final worker = Worker('test.dart.js');
    worker.postMessage('hi from main');
    worker.onMessage.listen((e) {
      print('message from worker: ${e.data}');
    });
  }
}
```

`test.dart`
```dart
import 'dart:html';

main() {
  print('worker main()');
  final self = WorkerGlobalScope.instance;

  self.on['message'].listen((e) {
    final MessageEvent event = e;
    print('message from main: ${event.data}');
  });
}
```

Output (`webdev serve`): 
```
```

Output (`webdev build`): 
```
worker main()
message from main: hi from main
```

Output (`webdev build --no-release`)
```
```

I'll file a separate issue for it not working in `webdev serve` or `webdev build --no-release`

**Comment by kevmoo** [comment] 2018-10-26 22:45
Duplicate of #34228

**Closed by kevmoo** 2018-10-26 22:45 UTC
Labels: area-library, library-html
