### ISSUE TITLE
IntelliJ Analyzer - FATAL error: Failed to handle request in Dart 2

### ISSUE THREAD

**Issue by erfanjazebnikoo** [dart-lang/sdk#34871] opened 2018-10-19 18:42 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\erfan\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\Project\MobileDevelopment\2018\koozeh_flutter], excluded: [D:\Project\MobileDevelopment\2018\koozeh_flutter\.idea, D:\Project\MobileDevelopment\2018\koozeh_flutter\.dart_tool, D:\Project\MobileDevelopment\2018\koozeh_flutter\.pub, D:\Project\MobileDevelopment\2018\koozeh_flutter\build]}, clientRequestTime: 1539952626803}
FileSystemException: Exists failed, path = 'D:\Project\MobileDevelopment\2018\koozeh_flutter\build\connectivity\generated\source\buildConfig\debug\io\flutter\plugins\connectivity' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-25 13:32
Duplicate of #34294

**Closed by stereotype441** 2018-10-25 13:32 UTC
Labels: area-analyzer
