### ISSUE TITLE
[CP][beta channel] Please merge bebf9054214b97b59be80dda4635dd24dea03479

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#46928] opened 2021-08-16 19:33 UTC
**commit(s) to merge**: bebf9054214b97b59be80dda4635dd24dea03479

**merge instructions**: merges cleanly into origin/beta

**What is the issue**: Pub will fail to compile executables if the destination path contains any spaces.

**What is the fix**: Update to the latest frontend_server_client dependency which contains the fix.

**Why cherrypick**: `pub run`, `pub global run`, etc will fail for users if the output path for the compiled program contains any spaces. This can break running tests with `dart test`, running `webdev` (a globally activated package), or any other pub executable. It is expected to primarily impact windows users.

**Risk**: Should be low - no issues expected.

- [x] ~TODO: Run the pub repo tests with this update as well~ Done, all passed.

**Link to original  issue(s)**: https://github.com/dart-lang/webdev/issues/1380

/cc @kevmoo @mit-mit @whesse @athomas @vsmenon

**Comment by vsmenon** [comment] 2021-08-17 15:39
@jakemac53 - do we know if this was a regression?

**Comment by vsmenon** [comment] 2021-08-17 15:48
It looks like this pulls in a handful of changes (since May 20):

https://github.com/dart-lang/webdev/commits/master/frontend_server_client

Are we comfortable taking all of them?

**Comment by jakemac53** [comment] 2021-08-17 15:49
@vsmenon yes this is a regression - pub migrated to incremental compilation for executables in https://github.com/dart-lang/pub/pull/2968. This introduced the dependency on frontend_server_client which had this bug.

**Comment by vsmenon** [comment] 2021-08-17 15:52
@jakemac53 - could you do a quick check on the changes since May 20 (inclusive)?

https://github.com/dart-lang/webdev/commits/master/frontend_server_client

Do you see any risks taking those in?

**Comment by jakemac53** [comment] 2021-08-17 15:55
I don't see any other code changes to the public files in `frontend_server_client` outside of the bug fix, so those LGTM. I don't see any risk associated.

Note that only the `fronted_server_client` package from this repo is used in the SDK, so anything else is safe.

**Comment by vsmenon** [comment] 2021-08-17 15:56
Thanks!

Approved.

**Comment by athomas** [comment] 2021-08-18 06:21
Merged to beta in 9a1827339c8e4e55a9b214d033aeba7d30daa28f (2.14.0-377.7.beta).

**Closed by athomas** 2021-08-18 06:21 UTC
Labels: merge-to-beta, cherry-pick-review, cp-approved, area-tools
