### ISSUE TITLE
Dart analysis issue (Dart SDK Dev channel)

### ISSUE THREAD

**Issue by cool-lei** [dart-lang/sdk#38933] opened 2019-10-17 05:08 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 2560x1440, 2560x1440`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35, server version 1.27.3, FATAL error: Failed to handle request: {id: 1153, method: edit.getFixes, params: {file: D:\SmartEnergyClubApp\csp\lib\src\screens\login_page.dart, offset: 115}, clientRequestTime: 1571288773407}
FileSystemException: Exists failed, path = 'D:\SmartEnergyClubApp\csp\lib\src\:csp\styles\theme.dart\.dart_tool\build' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _Directory.existsSync (dart:io/directory_impl.dart:99:7)
#1      _PhysicalResource.exists (package:analyzer/file_system/physical_file_system.dart:370:29)
#2      _OverlayFolder.exists (package:analyzer/file_system/overlay_file_system.dart:295:65)
#3      PackageBuildWorkspace.find (package:analyzer/src/workspace/package_build.dart:320:28)
#4      ContextBuilder.createWorkspace (package:analyzer/src/context/builder.dart:671:36)
#5      new BestPracticesVerifier (package:analyzer/src/generated/resolver.dart:125:24)
#6      LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:265:21)
#7      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:184:11)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:183:15)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:169:35)
#12     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:113:14)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:112:43)
#15     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1261:63)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#17     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#18     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:929:33)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1297:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:929:33)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file://C:\Users\LLi\AppData\Local\Temp\report.txt.
[report.txt](https://github.com/dart-lang/sdk/files/3737465/report.txt)

**Comment by srawlins** [comment] 2019-10-17 05:12
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37403; please follow along there.

**Comment by srawlins** [comment] 2019-10-17 05:13
Duplicate of https://github.com/dart-lang/sdk/issues/37403

**Closed by srawlins** 2019-10-17 05:13 UTC
