### ISSUE TITLE
Weird error with set literals

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#39556] opened 2019-11-27 23:05 UTC
When you try to auto complete an set literal, it shows no options when done without declaring it first:

![image](https://user-images.githubusercontent.com/1146982/69765024-1cb70100-1151-11ea-893b-f65f254e6f71.png)
---or on dartpad---
![image](https://user-images.githubusercontent.com/1146982/69765111-6c95c800-1151-11ea-9460-b3fd8bd8f303.png)

But works if you declare it on a variable:

![image](https://user-images.githubusercontent.com/1146982/69765056-38220c00-1151-11ea-8e10-bfecc6bb8fcf.png)
---or on dartpad---
![image](https://user-images.githubusercontent.com/1146982/69765142-859e7900-1151-11ea-9617-9e83bc801806.png)

**Comment by bwilkerson** [comment] 2019-11-27 23:59
This is actually working as intended. There is an ambiguity in the Dart grammar. Given
```
void main() {
  {}
}
```
The first line of the function could be interpreted as either a set literal (with a missing semicolon) or an empty block statement. The spec resolves the ambiguity by saying that it will be interpreted as a block statement no matter what's between the braces.

You can fix the ambiguity by not starting a statement with an opening brace `{`. Adding a variable declaration is one way; adding explicit type arguments is another:
```
<int>{1, 2, 3};
```

**Closed by bwilkerson** 2019-11-27 23:59 UTC
