### ISSUE TITLE
package:front_end imports unpublishable package:testing

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#32952] opened 2018-04-23 21:18 UTC
Probably the testing files inside front_end should be changed to another unpublishable package, like front_end_testing.

Causes analysis issues elsewhere that source files in package:front_end reference a nonexist package (outside of the sdk repo).

**Comment by MichaelRFairhurst** [comment] 2018-04-23 21:45
Just to be clear, the problems are kinda twofold:

* package:testing is not listed in even the dev_dependencies of package:front_end even though its used
* package:testing is imported & used inside sources (not just tests) even though it should be considered at best a dev dependency

The analysis issues are in g3, though if anyone were to navigate in their IDE to package:front_end they may start seeing these errors in some potentially contrived circumstance. Specific internal examples will be provided hopefully by EOD

**Comment by grouma** [comment] 2018-06-13 17:01
cc @DanTup 

This is blocking Danny from using `pub run test` in this package. An easy work around to the issue is to provide a path override to the problematic package.

**Comment by DanTup** [comment] 2018-06-13 17:10
For the analysis server, the package that prevents running `pub get` is `telemetry`:

> Because analysis_server depends on telemetry any which doesn't exist (could not find package telemetry at https://pub.dartlang.org), version solving failed.

If I skip running `pub get` and just try running `pub run test` then it fails to locate the test package (because the `.packages` file is two levels higher) and reports:

> Could not find **bin/test.dart** in package **test**.

I'd really like to get the analysis server tests running via `pub run test` so they'll work in the test runner I'm working on for VS Code (not just for selfish reasons but to also to ensure it gets good testing/dog-fooding :-))

**Comment by bwilkerson** [comment] 2018-06-13 17:14
> If I skip running `pub get` ...

Which you should always do for any package inside the sdk :-)

> ... and just try running `pub run test` then it fails to locate the test package (because the `.packages` file is two levels higher)

If that's really the reason, then that sounds like a bug in `pub`. All Dart tools are suppose to look up the directory hierarchy until the root of the file system to search for a `.packages` file. If `pub test` doesn't do that, then that's a bug.

**Comment by DanTup** [comment] 2018-06-13 17:22
> All Dart tools are suppose to look up the directory hierarchy until the root of the file system to search for a `.packages` file

I've had conflicting info about this today, so I'm a little confused now :( Is this written anywhere (I did try searching earlier but didn't turn up anything) so we can make sure we're fixing this in the right place?

**Comment by DanTup** [comment] 2018-06-13 17:41
I found this:

https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md#resolving-package-uris

which says:

> If the entry point was `file:` URI and a packages directory was not found in the previous step, then the tool checks for the presence of a `.packages` file in the parent directory of the entry point, and recursively check each parent directory up to the root directory until a `.packages` file is found. That `.packages` file is used to resolve package URIs.

@jakemac53 @grouma This suggests maybe we should fix in pub? (assuming the issue is actually this; I can do some digging and confirm if we're happy to go that route).

**Comment by natebosch** [comment] 2018-06-13 18:03
@bwilkerson - `pub get` and `pub run` operation a a stricter subset of the `.packages` spec. We do not have any intentions of supporting `pub run` where we are unable to `pub get`. We probably _can_ add path overrides in the pubspec and make `pub get` work which would solve the other issues.

**Comment by DanTup** [comment] 2018-06-13 20:04
Maintaining path overrides in all the pubspecs in the SDK repo seems like a lot of effort (esp. given the setup isn't "wrong" and it's only to satisfy my desire to have the tests work in editors).

Does `package:test` have an API I could use from a Dart script that might allow me to run the "VM way" but using the JSON reporter? (or can we re-discuss something like an env variable to change the reporter in this mode?)

**Comment by natebosch** [comment] 2018-06-13 20:07
You could maybe use the full test frontend by manually finding the path to an entrypoint (or a snapshot of it) and executing it yourself.

`dart $SDK_ROOT/third_party/pkg/test/bin/test.dart path/to/file_test.dart`

**Comment by jakemac53** [comment] 2018-06-13 20:09
Note that you can actually invoke the dart vm with a `package:` uri, so you can do:

```
dart --packages=path/to/.packages package:test/src/executable.dart
```

**Comment by DanTup** [comment] 2018-06-13 20:20
> You could maybe use the full test frontend by manually finding the path to an entrypoint

> `dart --packages=path/to/.packages package:test/src/executable.dart`

Oooh, that seems like it might work. I could walk up the tree and find the `.packages` myself and then invoke it this way. I will do some more testing tomorrow, thanks both! 👍 

(I think we kinda derailed this thread, sorry @MichaelRFairhurst!)

**Comment by DanTup** [comment] 2018-06-13 20:29
Yeah, I wasn't advocating abandoning this issue; but it might not be blocking for me if the above works (I really want to merge and ship my test stuff; not having a visual test list is a common complaint) :-)

**Comment by DanTup** [comment] 2018-06-14 06:52
Bah, that didn't work either. I guess because test's dependencies aren't in the SDK's packages file:

```
dantup-macbookpro:analysis_server dantup$ dart --packages=../../.packages package:test/src/executable.dart
Unhandled exception:
Could not import "package:multi_server_socket/multi_server_socket.dart" from "package:test/src/runner/node/platform.dart": No mapping for 'multi_server_socket' package when resolving 'package:multi_server_socket/multi_server_socket.dart'.
null
```

I guess when running directly via dart (bypassing the runner) it doesn't have these dependencies (if it does, I don't see how it's resolving them).

**Comment by jakemac53** [comment] 2018-06-14 14:21
> I guess when running directly via dart (bypassing the runner) it doesn't have these dependencies (if it does, I don't see how it's resolving them).

Ya, that makes sense. I don't know that its worth pulling these dependencies into the sdk just for this use case either (then we have to keep them up to date etc)....

**Comment by DanTup** [comment] 2018-06-14 14:38
Yeah, that doesn't seem like a great solution. There are things I could try (like writing a pubspec with the same version of test as is in the users `.packages`, `pub get`ing and then running it from there) but it's getting messy. Given the SDKs layout seems like it's generally supported (just not for `pub`) I'd really like to support it, even if users have to opt-in to it running in a specific way.

@grouma What's the concern over allowing an env variable to switch the reporter when running via `dart`? It seemed to work fine in my testing, and any caveats with runner functionality not working are already issues for anyone hitting `F5` in VS Code since we're already running through `dart`.

**Comment by jakemac53** [comment] 2018-06-14 15:13
@DanTup 

One issue is that the json reporter isn't even imported by the default package:test import, so its not available at all when running the test directly. We could import it - but that would actually hurt compilation times and output sizes for all users to at least some degree and might introduce similar dependency issues, just to support a very narrow use case.

Another issue is that running tests directly that way will still give weird behavior because it doesn't respect the annotations in the file, or other command line arguments, and could be missing any number of other features.

We don't want to end up supporting environment variables for every single command line option just because the sdk uses pub packages without actually using pub, and having to import all the required imports to make that happen from the main `test.dart` entrypoint.

**Comment by DanTup** [comment] 2018-06-14 15:44
@jakemac53 Thanks for the extra info; it doesn't sound unreasonable. Since it doesn't seem like there's an easy solution here, I might ship my test stuff as flutter-only for now while I think more about this. I don't want it to rot and the vast majority of users are flutter app devs.

I might ping you for your opinion on any ideas I come up with in the near future though!

**Comment by jakemac53** [comment] 2018-06-14 15:50
It shouldn't be necessary to block completely - this will still work for typical users.

You could for instance just check for a `pubspec.lock` or something and only enable the feature if that exists?

This is very similar to the pub get on save feature which also wouldn't do the right thing for the sdk or similar use case.

**Comment by grouma** [comment] 2018-06-14 15:52
One other issue is that if you use a regular platform variable then you will need to import from `dart:io`. This code does not only run on the VM but also runs in the browser. That will cause issues, especially with our internal platform work. Of course one alternative is to use `bool.fromEnvironment`.

**Comment by jakemac53** [comment] 2018-06-14 15:54
> One other issue is that if you use a regular platform variable then you will need to import from dart:io

Oh right!! I hadn't even though about that aspect, ya we definitely can't do this.

**Comment by grouma** [comment] 2018-06-14 15:55
I'm not opposed to copying in the `pubspec.yaml` whenever we pull in a package. The `pubspec.yaml` will not be used besides for testing. Doesn't seem like much of an issue in my opinion.

**Comment by jakemac53** [comment] 2018-06-14 15:56
> I'm not opposed to copying in the pubspec.yaml whenever we pull in a package. The pubspec.yaml will not be used besides for testing. Doesn't seem like much of an issue in my opinion.

We still have the missing dependencies issue though.

**Comment by grouma** [comment] 2018-06-14 16:00
We need to just author the `pubspec.yaml` once with dependency overrides. It will be a little bit of a pain to write but should be easy to keep up to date. @DanTup I'm also in favor of releasing the feature even though it doesn't work in the SDK. As @jakemac53 mentioned it should work for everybody else.

**Comment by natebosch** [comment] 2018-06-14 22:33
>`Could not import "package:multi_server_socket/multi_server_socket.dart" from "package:test/src/runner/node/platform.dart": No mapping for 'multi_server_socket' package when resolving 'package:multi_server_socket/multi_server_socket.dart'.
null`

Looks like we _don't_ have a valid `.packages` for `package:test` so the premise of searching up for `.packages` is invalid anyway. Either that `.packages` file will need to be made valid for `package:test` (which could mean pulling in new deps) and we'll can run with one of the strategies listed above (not `pub run test`), or we'll need a different `.packages` specifically for the test runner - which leads us back to making it possible to `pub get` so that we can get such a valid `.packages`.

**Comment by jakemac53** [comment] 2018-06-15 13:54
Note also that the `pub run` use case is not covered by the spec anyways, the `.packages` file is only supposed to be used to resolve `package:` uris - which `pub run` is explicitly not doing. It is running binaries from the `bin` directory of a package which are only accessible via absolute/relative uri.

**Comment by bwilkerson** [comment] 2018-06-15 14:47
Then why is the `.packages` file in a parent directory not being found when `pub run` is being used?

**Comment by DanTup** [comment] 2018-06-15 15:49
>  @DanTup I'm also in favor of releasing the feature even though it doesn't work in the SDK

My concern isn't just about the test tree not working (although I really would like to support it), it's also making sure that the ability to actually debug tests we have today doesn't break. Today you can press F5 in any test script and it just works (because we run via `dart`) - I can't just send them all through `pub run test` if some won't work (based on comments above, it seems like it's valid, even if uncommon, to have a `.packages` at higher levels, so this *may* affect non-SDK users).Not having the results in the tree is one thing, but not being able to press `F5` and debug them is another.

I just need to be sure I can reliably detect this scenario and know when to fall back to `dart` (I think finding a `pubspec.yaml` without a sibling `.packages` file *might* be good enough though.. it might upset people using `--packages-dir` but I'm ok with that, their tests will still run, just not into the tree). Possibly I could also detect the failure so if I do run `pub run test` I can at least prompt the user to open an issue on GH and offer to retry using `dart`. I'm somewhat on the fence about providing an override - nobody has complained about current detection of which debugger we pick, but if you want to run a script inside a Flutter project's `test` folder via `dart` for ex, that's not currently possible).

> I'm not opposed to copying in the `pubspec.yaml` whenever we pull in a package.

I'm not entirely sure what this means?

**Comment by jakemac53** [comment] 2018-06-15 15:49
I am going to close this issue as it got derailed from the original issue, @MichaelRFairhurst can you please re-open?

@DanTup please open a new issue about how to run tests in the SDK repo.

**Closed by jakemac53** 2018-06-15 15:49 UTC
Labels: area-front-end, front-end-cleanup

**Comment by jakemac53** [comment] 2018-06-15 15:56
I went ahead and re-opened the issue, https://github.com/dart-lang/sdk/issues/33465

**Comment by DanTup** [comment] 2018-06-15 16:13
Yeah, sorry about that :(

I've opened #33466 to describe my issue. I don't think there's really a good solution, but it makes sense to have documented all the same. I'll try out some of the ideas above for detecting this scenario and falling back to dart (with basic text output) next week.

Thanks for all the comments and insight, it's been helpful even if we didn't find a good solution!
