### ISSUE TITLE
Downwards inference to FutureOr causes unexpected errors

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#29164] opened 2017-03-24 18:29 UTC
Upgrading to the latest dev SDK I started seeing errors that I did not expect and had a non-obvious solution.

Given the following 2 equivalent functions, the one that returns directly has an error because of the inference of the generic method type from the return value:

``` dart
Future<List<int>> unsafe() async {
  var values = [[1,2], [3,4]];
  return values.fold([], (List<int> r, e) {
    r.addAll(e);
    return r;
  });
}

Future<List<int>> safe() async {
  var values = [[1,2], [3,4]];
  var result = values.fold([], (List<int> r, e) {
    r.addAll(e);
    return r;
  });
  return result;
}
```

Depending on whether `r` is given an explicit type the error is either:

```
[error] The argument type '(List<int>, List<int>) → List<int>' can't be assigned to the parameter type '(FutureOr<List<int>>, List<int>) → FutureOr<List<int>>'
```
or
```
[error] The method 'addAll' isn't defined for the class 'FutureOr<List<int>>'
```

**Comment by leafpetersen** [comment] 2017-03-24 19:12
As discussed offline, this is currently working as intended, but worth discussing as a language issue where we're not doing as nice a job with inference as would be desired.

cc @floitschG @eernstg @lrhn @munificent 

We (the language team) discussed this at some point and agreed that downwards inference should go ahead and instantiate with FutureOr just as it would with any other type (rather than trying to choose one or the other).

**Comment by lrhn** [comment] 2017-03-28 13:07
I'm not sure `FutureOr` is the culprit here. We have a contravariant occurrence of the inferred type parameter in the signature `T fold<T>(T, T combine(T, E))`. That means that pushing down the upper bound from the context isn't necessarily the best we can do.

Consider:
```dart
num result = <int>[1, 2, 3].fold(0, (int a, int b) => a + b);
```
Here, pushing down the result type `num` as `T` means that the argument function isn't valid, whereas bubbling up the `int` type from the arguments is safe.

If we are pushing down the `FutureOr<List<int>>` type in the example above, we should also be pushing down `num` here.

**Comment by leafpetersen** [comment] 2017-03-31 22:54
> Is there any way we can find that (without digging a hole for ourselves by promising something undecidable)?

Maybe.  There are certainly things we could play around with.  For example, currently we try to fix as many type arguments as we can using only downwards info, and then fix the rest after we've analyzed the sub-expressions using upwards info.  We could incorporate into the first phase information that is invariant under downwards inference.  So in your example, `0` has (at least right now) the type `int` no matter what context it is analyzed in, and `(int a, int b) => a + b` has the type `? Function(int, int)` no matter what context it is analyzed in (that is, it's argument types are invariant, but its return type isn't known until you've analyzed it).  So we could incorporate that information earlier. 

Another thing that we could consider doing is ordering the upwards inference per argument by analyzing the types of the arguments.  C# does this, but it's clearer what to do there since they  use equality constraints rather than subtype constraints.

Another thing that we could consider doing is trying to work out what assignability constraints would look like, rather than relying on subtype constraints.

I don't really know exactly where any of this would leave us, but it's something we could look into.

**Comment by leafpetersen** [comment] 2017-05-12 22:47
Closing this as currently working as intended.   We'd like to improve inference for things like fold.  I think that's sufficiently tracked elsewhere.

**Closed by leafpetersen** 2017-05-12 22:47 UTC
Labels: area-language
