### ISSUE TITLE
Flaky ffi/function_struct_by_value_out_of_bounds_test crash on linux-x64-aot

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#53897] opened 2023-10-30 07:59 UTC
See [log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8766063564016249425/+/u/test_results/ignored_flaky_test_failure_logs):
```

/======================================================================================\
| ffi/function_struct_by_value_out_of_bounds_test broke (Pass -> Crash, expected Pass) |
\======================================================================================/

--- Command "vm_compile_to_kernel" (took 03.000766s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.dill /b/s/w/ir/tests/ffi/function_struct_by_value_out_of_bounds_test.dart -Dtest_runner.configuration=vm-aot-linux-release-x64 --packages=/b/s/w/ir/.dart_tool/package_config.json -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 04.000440s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.S --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 25ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.dill

exit code:
0

--- Command "assemble" (took 01.000038s):
DART_CONFIGURATION=ReleaseX64 gcc -Wl,--no-undefined -shared -o /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.S

exit code:
0

--- Command "remove_assembly" (took 50ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.S

exit code:
0

--- Command "vm" (took 114ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test out/ReleaseX64/dart_precompiled_runtime --sound-null-safety -Dtest_runner.configuration=vm-aot-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/vm-aot-linux-release-x64/tests_ffi_function_struct_by_value_out_of_bounds_test/out.aotsnapshot

exit code:
-6

stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0x7fc8efeff000
version=3.3.0-edge.6a464c9dee693f92c8d752680da65aea15b88132 (be) (Fri Oct 27 16:50:09 2023 +0000) on "linux_x64"
pid=58575, thread=58581, isolate_group=main(0x564d7929bf50), isolate=main(0x564d792a3bc0)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=7fc8f56cbe40, vm_instructions=7fc8f56c5100
fp=7fc8f48fe468, sp=7fc8f48fe468, pc=7fc8f577f347
  pc 0x00007fc8f577f347 fp 0x00007fc8f48fe468 _kDartIsolateSnapshotInstructions+0xb3507
  pc 0x00007fc8f577f195 fp 0x00007fc8f48fe4b0 _kDartIsolateSnapshotInstructions+0xb3355
  pc 0x00007fc8f577f5af fp 0x00007fc8f48fe4c0 _kDartIsolateSnapshotInstructions+0xb376f
  pc 0x00007fc8f578026e fp 0x00007fc8f48fe538 _kDartIsolateSnapshotInstructions+0xb442e
  pc 0x00007fc8f56f7e0f fp 0x00007fc8f48fe570 _kDartIsolateSnapshotInstructions+0x2bfcf
  pc 0x00007fc8f578057c fp 0x00007fc8f48fe5f0 _kDartIsolateSnapshotInstructions+0xb473c
  pc 0x00007fc8f5725648 fp 0x00007fc8f48fe618 _kDartIsolateSnapshotInstructions+0x59808
  pc 0x00007fc8f56c9761 fp 0x00007fc8f48fe690 _kDartVmSnapshotInstructions+0x4661
  pc 0x0000564d784d7d33 fp 0x00007fc8f48fe6f0 dart::DartEntry::InvokeFunction+0xf3
  pc 0x0000564d784d9726 fp 0x00007fc8f48fe730 dart::DartLibraryCalls::HandleMessage+0x126
  pc 0x0000564d784ea0af fp 0x00007fc8f48fecc0 dart::IsolateMessageHandler::HandleMessage+0x2bf
  pc 0x0000564d784f3a67 fp 0x00007fc8f48fed30 dart::MessageHandler::HandleMessages+0x127
  pc 0x0000564d784f4058 fp 0x00007fc8f48fed80 dart::MessageHandler::TaskCallback+0x1e8
  pc 0x0000564d785b175b fp 0x00007fc8f48fee00 dart::ThreadPool::WorkerLoop+0x14b
  pc 0x0000564d785b19f8 fp 0x00007fc8f48fee30 dart::ThreadPool::Worker::Main+0x78
  pc 0x0000564d7855ec86 fp 0x00007fc8f48feef0 dart::ThreadStart+0xd6
-- End of DumpStackTrace

--- Re-run this test:
python3 tools/test.py -n vm-aot-linux-release-x64 ffi/function_struct_by_value_out_of_bounds_test
```

**Comment by dcharkes** [comment] 2023-10-30 09:42
Duplicate of:

* https://github.com/dart-lang/sdk/issues/53829

**Closed by dcharkes** 2023-10-30 09:42 UTC
Labels: area-vm, gardening
