### ISSUE TITLE
VM fails on `language/nnbd/syntax/late_modifier_final_field_test` 

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40204] opened 2020-01-17 08:24 UTC
VM fails on `language/nnbd/syntax/late_modifier_final_field_test` after update.

The spec was updated to _not_ require a throwing setter on override in https://github.com/dart-lang/language/pull/720 but this test wasn't updated accordingly.

```
--- Command "vm" (took 522ms):
DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart --enable_asserts --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/language/nnbd/syntax/late_modifier_final_field_test.dart

exit code:
255

stderr:
Unhandled exception:
LateInitializationError: fieldWithInit
#0      _LateInitializationError._throwNew (dart:core-patch/errors_patch.dart:600:5)
#1      A.fieldWithInit= (file:///b/s/w/ir/cache/builder/sdk/tests/language/nnbd/syntax/late_modifier_final_field_test.dart:22:18)
#2      main (file:///b/s/w/ir/cache/builder/sdk/tests/language/nnbd/syntax/late_modifier_final_field_test.dart:37:5)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)

--- Re-run this test:
python tools/test.py -n dartk-weak-asserts-linux-release-x64 language/nnbd/syntax/late_modifier_final_field_test
```

**Comment by liamappelbe** [comment] 2020-01-17 18:10
I think you've misread the spec a bit. The part that was removed was special casing field overrides that don't introduce a setter. This doesn't mean that late final fields with initializers are now settable. From earlier in the spec: "The late final variable declaration with no initializer is special in that it is the only final variable which can be the target of an assignment".

The test isn't testing the behavior that was removed. It's just trying to test that assigning to a late final field with an initializer throws a runtime exception. The only reason `class Base` exists is to bypass the compile time error so the runtime error can be tested.

I think we should just remove [these new lines](https://dart-review.googlesource.com/c/sdk/+/131829/2/tests/language/nnbd/syntax/late_modifier_final_field_test.dart) from the test. I think both diffs are incorrect, but the first diff in particular would be impossible to implement in the VM under the current uninitialized sentinel approach (we'd need to redesign the whole approach and introduce an extra bool flag).

**Comment by johnniwinther** [comment] 2020-01-17 19:07
I might be misreading the spec - or the test - or both (it's not a first for this issue...).

I'm reading the code as assigning to field in the superclass. Like in this case:
```Dart
class A {
   int field;
}
class B extends A {
  final int field;
  B(this.field);
  int get superField => super.field;
}
main() {
  B b = new B(42);
  print(b.field); // prints "42"
  print(b.superField); // prints "null"
  b.field = 87;
  print(b.field); // prints "42"
  print(b.superField); // prints "87"
}
```

So in the test the line `a.fieldWithInit = 456;` is not accessing `A.fieldWithInit` which has (or introduces) no setter, but instead `Base.fieldWithInit`.

@eernstg: What is your take on this?

**Comment by liamappelbe** [comment] 2020-01-17 20:14
Ah, I see what you mean. It didn't occur to me that the set might go to the member on the base class. Seems like unexpected behavior to me, but if the spec says that's what should happen then ok.

@eernstg @leafpetersen The basic question is should the [new lines added to late_modifier_final_field_test](https://dart-review.googlesource.com/c/sdk/+/131829/2/tests/language/nnbd/syntax/late_modifier_final_field_test.dart) try to set A.fieldWithInit and throw an exception, or set Base.fieldWithInit and succeed.

In the latter case, as well as updating the VM to remove the setter, I'll need to rewrite this test a bit because the structure and comments are misleading.

**Comment by leafpetersen** [comment] 2020-01-17 22:35
Yes, the intended interpretation is the latter (the write goes to the setter inherited from Base.fieldWithInit).  My original specification provided for a throwing setter to be implicitly added in `A` to shadow the inherited setter from Base.fieldWithInit, but we removed that.  As a result the setter which was added in `Base` is inherited by `A`.

**Comment by leafpetersen** [comment] 2020-01-17 22:36
cc @lrhn

**Closed** 2020-01-17 23:52 UTC
Labels: NNBD, area-vm

**Comment by eernstg** [comment] 2020-01-20 13:41
> @eernstg: What is your take on this?

Agreeing with @leafpetersen, just adding a small remark about the background: The semantics based directly on having an implicitly induced getter and possibly a setter is simpler to explain, especially when mixins are taken into account, which is the reason why we dropped the special cased throwing setter.
