### ISSUE TITLE
[dart:js_interop] Cannot specify signatures of functions passed as arguments to js_interop extension types

### ISSUE THREAD

**Issue by felix-ht** [dart-lang/sdk#55375] opened 2024-04-04 11:58 UTC
With the old `js` interop one could define function arguments with strong typing:

```dart
@JS()
class FooOld{
  external void bar(void Function(String e) callback);
}

```

With the new `js_interop` this doens't seem to be possible

```dart
@JS()
extension type Foo._(JSObject _) implements JSObject {
  // compile error:
  //  Type 'void Function(String)' is not a valid type in the signature of
  // 'dart:js_interop' external APIs or APIs converted via 'toJS'.
  external void bar(void Function(String e) callback);
  // fine but not type safe 
  external void baz(JSFunction callback);
}
```

How can i still specify function signatures for function arguments? Or do i just have to live without?

**Comment by felix-ht** [comment] 2024-04-04 12:30
One options seems to be to just warp the external function in a normal one. With this the unsound part is contained (but still exposed to the user via the original function name).

```dart
@JS()
extension type Foo._(JSObject _) implements JSObject {
  // compile error:
  //  Type 'void Function(String)' is not a valid type in the signature of
  // 'dart:js_interop' external APIs or APIs converted via 'toJS'.
  external void bar(void Function(String e) callback);
  // fine but not type safe
  external void baz(JSFunction callback);

  void bazDart(void Function(String e) callback) {
    baz(callback.toJS);
  }
}

```

**Comment by srujzs** [comment] 2024-04-04 16:06
Duplicate of https://github.com/dart-lang/sdk/issues/54557.

The best answer with the current library is indeed a forwarding function like you have, but it isn't ideal.

**Comment by srujzs** [comment] 2024-04-04 16:08
Duplicate of https://github.com/dart-lang/sdk/issues/54557.

**Comment by srujzs** [comment] 2024-04-04 16:09
Duplicate of #54557

**Closed by srujzs** 2024-04-04 16:08 UTC
Labels: web-js-interop, area-web
