### ISSUE TITLE
Dart-analyzer: Excessive static warning while getter access

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#24342] opened 2015-09-14 08:50 UTC
According Dart specification "16.18.1 Getter Access and Method Extraction":
"Evaluation of a property extraction i of the form e.m proceeds as follows:
...
Let T be the static type of e. It is a static type warning if T does not have
a method or getter named m unless either:
• T or a superinterface of T is annotated with an annotation denoting a
constant identical to the constant @proxy defined in dart:core."

```dart
const myProxy = proxy;

@myProxy class C {
}

main() {
  C c = new C();
  print(identical(myProxy, proxy)); // prints true
  c.m; // static warning
}
```
Dart analyzer produces [warning] The getter 'm' is not defined for the class 'C'. According the spec (see above) it should not

dartanalyzer version 1.12.0-dev.5.10

**Comment by bwilkerson** [comment] 2015-09-14 14:52
This is a duplicate of https://github.com/dart-lang/sdk/issues/15467.

**Closed by bwilkerson** 2015-09-14 14:52 UTC
Labels: Area-Analyzer
