### ISSUE TITLE
Android Studio Asked Me Send You This

### ISSUE THREAD

**Issue by pyetti** [dart-lang/sdk#35479] opened 2018-12-21 23:21 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2 unknown, screens 1440x900, 1920x1080, 1920x1080  Retina`

# Exception

Contents of:
file:///private/var/folders/ns/d5lq25m56311xn591nz3rk_c0000gn/T/report.txt

Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2 unknown, screens 1440x900, 1920x1080, 1920x1080  Retina`

# Exception

Contents of:
file:///private/var/folders/ns/d5lq25m56311xn591nz3rk_c0000gn/T/report.txt

NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
2      ConstantVisitor.visitPrefixedIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1395:12)
3      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9033:49)
4      ConstantVisitor.visitPropertyAccess (package:analyzer/src/dart/constant/evaluation.dart:1421:49)
5      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:9224:49)
6      ConstantVerifier._validate (package:analyzer/src/dart/constant/constant_verifier.dart:449:10)
7      ConstantVerifier._validateDefaultValues (package:analyzer/src/dart/constant/constant_verifier.dart:509:20)
8      ConstantVerifier.visitFunctionExpression (package:analyzer/src/dart/constant/constant_verifier.dart:118:5)
9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5360:49)
10     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5204:26)
11     RecursiveAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:862:10)
12     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197:49)
13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
14     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2423:21)
15     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:712:10)
16     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
17     LibraryAnalyzer._computeConstantErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:172:10)
18     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:325:5)
19     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
20     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
21     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:15)
22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
23     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:36)
24     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
25     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
26     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
27     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
28     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
29     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
30     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1050:39)
<asynchronous suspension>
31     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
32     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
33     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
34     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
35     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
36     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
37     _rootRun (dart:async/zone.dart:1124:13)
38     _CustomZone.run (dart:async/zone.dart:1021:19)
39     _runZoned (dart:async/zone.dart:1516:10)
40     runZoned (dart:async/zone.dart:1463:12)
41     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
42     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
43     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
44     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
45     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
46     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
1545434123618 => {"id":"23","method":"edit.getAssists","params":{"file":"/Users/{hidden}}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","offset":471,"length":0},"client
1545434123632 <= {"id":"23","result":{"assists":[]}}
1545434138046 => {"id":"24","method":"edit.getAssists","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","offset":543,"length":0},"client
1545434138050 <= {"id":"24","result":{"assists":[]}}
1545434139265 => {"id":"25","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","offset":543
1545434139281 <= {"id":"25","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":536,"length":9,"elementKindName":"parameter","oldName":"timeOfday"}}}
1545434141434 => {"id":"26","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","offset":543
1545434141438 <= {"id":"26","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":536,"length":9,"elementKindName":"parameter","oldName":"timeOfday"}}}
1545434141702 => {"id":"27","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","offset":543
1545434141703 <= {"id":"27","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":536,"length":9,"elementKindName":"parameter","oldName":"timeOfday"}}}
1545434141917 => {"id":"28","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","offset":543
1545434141940 <= {"id":"28","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":536,"length":9,"elementKindName":"parameter","oldName":"timeOfday"},"change":{"m
1545434142219 => {"id":"29","method":"analysis.updateContent","params":{"files":{"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart":{"type":"add","content"
1545434142219 => {"id":"30","method":"edit.getAssists","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","offset":543,"length":0},"client
1545434142232 <= {"id":"29","result":{}}
1545434142233 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1545434142343 <= {"event":"analysis.errors","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","errors":[]}}
1545434142345 <= {"id":"30","result":{"assists":[]}}
1545434142346 <= {"event":"analysis.highlights","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","regions":[{"type":"DIRECTIVE","offset"
1545434142348 <= {"event":"analysis.navigation","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","regions":[{"offset":7,"length":31,"tar
1545434142349 <= {"event":"analysis.closingLabels","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","labels":[]}}
1545434142350 <= {"event":"analysis.outline","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","kind":"LIBRARY","outline":{"element":{"ki
1545434142350 <= {"event":"analysis.overrides","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/date_time_utils.dart","overrides":[]}}
1545434142504 <= {"event":"analysis.errors","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/pages/create_event/CreateUtils.dart","errors":[{"severity":"INFO","type
1545434142605 <= {"event":"analysis.errors","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/pages/create_event/DateTimePage.dart","errors":[]}}
1545434142699 <= {"event":"analysis.errors","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/domain/Event.dart","errors":[]}}
1545434142920 <= {"event":"analysis.errors","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/test/EmailValidationTest.dart","errors":[]}}
1545434142966 <= {"event":"analysis.errors","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/test/widget_test.dart","errors":[]}}
1545434142985 <= {"event":"analysis.errors","params":{"file":"/Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/test/PasswordValidationTest.dart","errors":[]}}
1545434143006 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/{hidden}/development/deyvoo/flutter/deyvoo-app/deyvoo/lib/utils/ui_utils.dart","stackTrace":"NoS
```

**Comment by stereotype441** [comment] 2018-12-28 17:36
Duplicate of #35241

**Closed by stereotype441** 2018-12-28 17:36 UTC
Labels: area-analyzer
