### ISSUE TITLE
Make constant-update-2018 work for split-kernel apps

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#36639] opened 2019-04-15 20:40 UTC
Currently, through a mechanism that I have not investigated, the Dart VM crashes with allocations of unreasonable size in the dart_runner running tests on Fuchsia when constant-update-2018 is enabled.

To reproduce:
1. Remove the flag --enable-experiment=no-constant-update-2018 from //topaz/runtime/dart/dart_kernel.gni
2. Configure a build with e.g.:
```
$ fx --dir out/topaz-arm64-debug set core.frank --with-base //topaz/bundles:buildbot
```
3. Run tests with:
```
$ fx shell runtests
```
4. Note that tests fail. They fail due to failing to map unreasonably large vmos. To see these enable logging in runtime/vm/virtual_memory_fuchsia.cc

@alexmarkov @a-siva @rmacnak-google @aartbik

**Comment by a-siva** [comment] 2019-04-15 21:45
This is a duplicate of https://github.com/dart-lang/sdk/issues/36584

**Closed** 2019-04-15 21:46 UTC
Labels: area-vm, closed-duplicate, customer-fuchsia, type-bug
