### ISSUE TITLE
error: Not a constant expression running flutter in google3 codebase

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32269] opened 2018-02-21 18:54 UTC
Getting the following error running flutter in the google3 codebase

'[REDACTED]/cache_config.dart': error: Not a constant expression.

**Comment by mraleph** [comment] 2018-02-21 18:55
Duplicate of #32268

**Comment by matanlurey** [comment] 2018-02-21 18:55
Hi @a-siva please do not post internal code-base paths in GitHub.

**Closed** 2018-02-21 18:55 UTC
Labels: Customer-Flutter, P0 critical, area-vm
