### ISSUE TITLE
Inferring the return type of a top-level function

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51570] opened 2023-02-28 17:03 UTC
Is it possible to implement type inference for top-level functions for both syntaxes? It seems unlikely to me that one would want to always infer the top-level type of a function as a dynamic type.

```dart
// The analyzer infers the string type.
// This function is not a compile-time constant.
var func1 = () {
  return "string";
};

// the analyzer infers the dynamic type.
// This function is a compile-time constant.
func2() {
  return 'string';
}

void main() {
  print(func1.runtimeType); // () => String
  print(func2.runtimeType); // () => dynamic
}
```

**Comment by eernstg** [comment] 2023-02-28 18:54
Inference on function literals, including their return type, is specified [here](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference). It's quite involved. This is the rule that gives rise to the typing of `func1` in your example.

Inference of the return type of a top-level function is not supported, it just uses `dynamic` if no return type is declared.

The main reason for this is probably that top-level functions _should_ have an explicitly declared return type (because it's a commitment to a specific API for your clients). Also, mutually dependent top-level declarations (including recursion, including the case where a function just calls itself) give rise to tractability/decidability issues.

Consider the special case where a function literal is the initializing expression for a top-level variable, and that connection is used to enable a recursive invocation: In that case a compile-time error occurs, because there's a circular dependency.

```dart
// Error: Cyclic dependency.
var func1 = (int i) {
  if (i <= 1) return 1;
  return func1(i - 1);
}
```

**Comment by eernstg** [comment] 2023-02-28 19:08
You can use an `analysis_options.yaml` with the following contents to flag the missing return types:

```yaml
analyzer:
  language:
    strict-inference: true
```

I'll close the issue because it is working as intended.

**Closed by eernstg** 2023-02-28 19:08 UTC

**Comment by gmb119943** [comment] 2023-02-28 19:32
The fact that it is not supported, I understand that. Just wondering what is the fundamental difference between top-level function type inference and local function type inference? Those. my question can be rephrased as why not implement type inference for top-level functions?

**Comment by eernstg** [comment] 2023-02-28 19:39
The really big difference is that local functions are ordered, and you can never call a later function (textually) from an earlier one. So you will always be able to perform the analysis of local function number `k` based on completed inference results about the local functions number `1 .. k-1`. That's a lot simpler than the case where the dependency graph can have an arbitrary structure.

It's not really "intended" to not work, it's just hard (.. as in requiring fixed point iteration, or as in being undecidable/intractable ;-).
