### ISSUE TITLE
lost generic T in super class method causing error "doesn't conform to the bound 'T'"

### ISSUE THREAD

**Issue by cyliale** [dart-lang/sdk#48131] opened 2022-01-12 12:11 UTC
Hello, i have a strange error with DART when i use the following example.

Console error is

      Failed to load "test/codable/dart_bug_test.dart":
      test/codable/dart_bug_test.dart:23:26: Error: Type argument 'int' doesn't conform to the bound 'T' of the type variable 'F' on 'ChildClass<Object>.baseFn'.
       - 'ChildClass' is from 'test/codable/dart_bug_test.dart'.
       - 'Object' is from 'dart:core'.
      Try changing type arguments so that they conform to the bounds.
          ChildClass<Object>().baseFn<int>();

Source code is

    import 'package:test/test.dart';
    abstract class BaseClass<T> {
      BaseClass();
      void baseFn<F extends T>() {}
    }
    class ChildClass<T> extends BaseClass<T> {
      ChildClass();
      // Adding this override does not triggers error
      /*
      @override
      void baseFn<F extends T>() {
        super.baseFn<F>();
      }
      */
    }
    void main() {
      test('DART bug : info about generic T is lost in super class', () {
        ChildClass<Object>().baseFn<int>();
        fail('If DART bug is still here, this file should not compile.');
      });
    }

If i uncomment the code "@override..." to activate the sub class method "baseFn", the error disappears. As expected, it triggers my "fail" error showing console output

    00:00 +0 -1: test/codable/dart_bug_test.dart: DART bug : info about generic T is lost in super class [E]
      If DART bug is still here, this file should not compile.
      package:test_api                      fail
      test/codable/dart_bug_test.dart 22:5  main.<fn>

This sub class method "baseFn" should be useless. Why must i add it ?

It seems that generic T information is lost by super class if i do not force any override.

My "dart --version" output is

    Dart SDK version: 2.15.1 (stable) (Unknown timestamp) on "linux_x64"

**Comment by vsmenon** [comment] 2022-01-12 13:40
@johnniwinther @eernstg - I'm tentatively marking this as CFE.  I can replicate on compilation, but I don't see the static error with the analyzer.

Is this a bug?

**Comment by cyliale** [comment] 2022-01-12 13:46
The analyzer shows no error, as expected, but the compiler fails... so i think it is a compiler bug !

**Comment by johnniwinther** [comment] 2022-01-12 13:53
@chloestefantsova This looks like something you worked on recently.

**Comment by eernstg** [comment] 2022-01-18 09:04
@vsmenon wrote:
> Is this a bug?

I think it's implied at this point, but just to make it explicit: Yes, I think it's a bug. Could it be caused by the CFE considering the type argument of `ChildClass` to be unrelated to the type argument of the same object at `BaseClass`? I see this behavior in several much older versions, so it seems to have existed for a long time (and nobody noticed&mdash;how on earth is that possible? ;-):

```
Yes: dart-sdk-2.15.0-208.0.dev
Yes: dart-sdk-2.12.0-237.0.dev
Yes: dart-sdk-2.9.0-21.0.dev
Yes: dart-sdk-2.2.1-dev.3.0
No!: dart-sdk-2.0.0-dev.69.5
```

**Closed** 2022-01-20 08:39 UTC
Labels: area-front-end
