### ISSUE TITLE
Android: `Unable to Enter Isolate : Multiple mutators entering an isolate / Dart VM is shutting down`

### ISSUE THREAD

**Issue by derolf** [dart-lang/sdk#44447] opened 2020-12-10 17:03 UTC
I am decoding two MJPEG-streams in parallel and make heavy usage of `MemoryImage` (Flutter), decoding about 10-20 images per seconds.

After a few seconds, the app crashes with

```
/Dart    (14933): ../../third_party/dart/runtime/vm/dart_api_impl.cc: 1662: error: Unable to Enter Isolate : Multiple mutators entering an isolate / Dart VM is shutting down
E/DartVM  (14933): version=2.12.0-29.7.beta (beta) (Fri Nov 13 11:35:21 2020 +0100) on "android_arm"
E/DartVM  (14933): pid=14933, thread=14961, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
E/DartVM  (14933): isolate_instructions=0, vm_instructions=a41c7240
E/DartVM  (14933):   pc 0xa427b025 fp 0xa2b7dab0 libflutter.so+0x13fd025
E/DartVM  (14933): -- End of DumpStackTrace
F/libc    (14933): Fatal signal 6 (SIGABRT), code -6 in tid 14961 (1.io)
```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-10.1.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
• No issues found!
```

Same crash at the same location also with

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-DE)
```

**Comment by derolf** [comment] 2020-12-10 17:21
Related to https://github.com/flutter/flutter/issues/52576

**Comment by ravenblackx** [comment] 2020-12-10 18:03
We have also observed this kind of crash, not even doing anything particularly demanding.

I'm only observing it from logs so I don't have a lot of details, but the crash occurred moments after downloading a 67kb png image (download completed at 01:39:26.507, and "Multiple mutators" error was the next line in the log at 01:39:27.133) so it seems very likely to be the same kind of image decoding error.

**Comment by derolf** [comment] 2020-12-11 16:26
Dart team (@franklinyow). Anything we can do to help finding the root cause? Any small example to try on the target tablet?

**Comment by franklinyow** [comment] 2020-12-11 18:07
@a-siva Can you make sure I have the right area label?  Thx

**Comment by ravenblackx** [comment] 2020-12-11 21:27
I now think the problem may be in the network handling rather than the image decoding.

https://github.com/flutter/flutter/issues/72144 is related.

(derolf may be able to confirm or deny this suspicion by trying their code with the downloading but without the decoding?)

**Comment by derolf** [comment] 2020-12-11 22:11
If I remove decoding and substitute it with just waiting (to generate pressure), it doesn't crash.

**Comment by derolf** [comment] 2020-12-11 22:12
@franklinyow @a-siva How can I get a full backtrace?

```
    #00 pc 000380c4  /system/lib/libc.so (tgkill+12)
    #01 pc 000148f1  /system/lib/libc.so (pthread_kill+52)
    #02 pc 0001564b  /system/lib/libc.so (raise+10)
    #03 pc 00011cc5  /system/lib/libc.so (__libc_android_abort+36)
    #04 pc 0001005c  /system/lib/libc.so (abort+4)
    #05 pc 002c92c5  /data/app/com.example.home-2/lib/arm/libflutter.so
```

**Comment by a-siva** [comment] 2020-12-11 23:40
@derolf is it possible to share your app code (just the decoding in parallel part) so we can have a reproduction of the crash and investigate.

**Comment by mkustermann** [comment] 2020-12-18 13:00
This is very likely the same bug as https://github.com/flutter/flutter/issues/72144  (the bug was introduced in https://github.com/flutter/engine/pull/19843). It happens due to refcounted engine objects where destructor will try to delete persistent handle. This can only happen on mutator thread but due to refcounted object in C++ the last drop in refcount can happen on non-mutator thread, which leads to this bug.

Closing this issue, since it's almost surely the same.`

**Closed by mkustermann** 2020-12-18 13:00 UTC
Labels: area-vm
