### ISSUE TITLE
`Event.preventDefault()` not working in asynchronous callback when submitting form in IE11

### ISSUE THREAD

**Issue by stwupton** [dart-lang/sdk#27884] opened 2016-11-23 22:16 UTC
`Event.preventDefault()` does not prevent the browser from refreshing when using an `async` callback in IE.

HTML:

    <form id="login">
      <input type="email" id="email" placeholder="Email">
      <input type="password" id="password" placeholder="Password">
      <input type="submit" value="SUBMIT">
    </form>

Dart:

    void main() {
      FormElement form = querySelector('form#login');
      form.onSubmit.listen((Event e) async {
        e.preventDefault();
        // send login request
      });
    }

If I remove the `async` keyword however, it does prevent the browser from refreshing. In Chrome it works with and without `async`.

**Comment by floitschG** [comment] 2016-11-27 17:41
I'm not an expert in the HTML library, but my guess is, that this is expected behavior.

The `async` keyword on a function implies a `scheduleMicrotask`, which is (when available) implemented using a MutationObserver (at least for the first microtask).
This means, that the `e.preventDefault()` is only invoked after an MutationObserver-trigger. I'm guessing that invoking the function at that point is just too late.

I'm more surprised that this isn't a problem for Chrome.

**Comment by stwupton** [comment] 2016-11-30 22:01
Yeah that makes sense. It's a shame that I will have to change all my callbacks for form submissions to synchronous functions just for IE. I much prefer using `await` than I do `.then()`.

**Comment by zoechi** [comment] 2016-12-01 07:25
You can call an async function after `preventDefault()` where you do your async code (could also be an inline function).

**Comment by Markzipan** [comment] 2021-11-16 23:05
Closing this since IE11 is no longer supported by our web targets.

**Closed by Markzipan** 2021-11-16 23:05 UTC
Labels: web-libraries, area-library, closed-obsolete, library-html, area-web
