### ISSUE TITLE
Failures on [test/ffi] Beef up `@Native` testing

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#51544] opened 2023-02-27 09:02 UTC
There are new test failures on [[test/ffi] Beef up `@Native` testing](https://github.com/dart-lang/sdk/commit/579d964406b6386c4a5ef835c2535791e220e477).

The tests
```
ffi/function_structs_by_value_generated_args_native_leaf_test/0 Crash (expected Pass)
ffi/function_structs_by_value_generated_args_native_leaf_test/1 Crash (expected Pass)
ffi/function_structs_by_value_generated_args_native_leaf_test/2 Crash (expected Pass)
ffi/function_structs_by_value_generated_args_native_leaf_test/3 Crash (expected Pass)
ffi/function_structs_by_value_generated_args_native_test/0 Crash (expected Pass)
ffi/function_structs_by_value_generated_args_native_test/1 Crash (expected Pass)
ffi/function_structs_by_value_generated_args_native_test/2 Crash (expected Pass)
ffi/function_structs_by_value_generated_args_native_test/3 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_leaf_test/0 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_leaf_test/1 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_leaf_test/2 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_leaf_test/3 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_test/0 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_test/1 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_test/2 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_arg_native_test/3 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_leaf_test/0 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_leaf_test/1 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_leaf_test/2 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_leaf_test/3 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_test/0 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_test/1 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_test/2 Crash (expected Pass)
ffi/function_structs_by_value_generated_ret_native_test/3 Crash (expected Pass)
```
are failing on configurations
```
vm-msan-linux-release-x64
```

**Comment by askeksa-google** [comment] 2023-02-27 09:06
[Example log](https://dart-ci.appspot.com/log/vm-msan-linux-release-x64/vm-msan-linux-release-x64/26/ffi/function_structs_by_value_generated_args_native_leaf_test/0)

**Comment by dcharkes** [comment] 2023-02-27 09:37
Duplicate of

* https://github.com/dart-lang/sdk/issues/50271

**Closed by dcharkes** 2023-02-27 09:37 UTC
Labels: area-vm, gardening
