### ISSUE TITLE
Request to improve dartdoc: show the list of extension of a class/enum in its documentation.

### ISSUE THREAD

**Issue by gmpassos** [dart-lang/sdk#47231] opened 2021-09-16 09:52 UTC
Since an extension can introduce methods that won't be listed in a class/enum documentation, it will be very interesting to know that some extra methods, from extension X, exist in the same package of the documentation.

This can be easily implemented by showing the list of extensions that a class/enum has. This won't increase documentation size or duplicate content.

This will help the navigation through documentation and explain the real scenario and context that a developer has in the actual code.

**Comment by mraleph** [comment] 2021-09-16 10:48
This is duplicate of https://github.com/dart-lang/dartdoc/issues/2021

**Closed by mraleph** 2021-09-16 10:48 UTC
