### ISSUE TITLE
StrongMode fails to report warning List.where() assignable to a list

### ISSUE THREAD

**Issue by jtmcdole** [dart-lang/sdk#27490] opened 2016-10-05 00:35 UTC
using List.where, I noticed StrongMode isn't warning me about assignments to Lists.

Repro: Copy to dartpad and see:

```dart
main() {
  var items = stringItems([1234, "hello", {}]);
  print(items);
  items.clear();
}

List<String> stringItems(List list) =>
  (list as List<String>).where((e) => e is String);
```

```console
(hello)
Uncaught TypeError: items.clear$0 is not a function
```

**Comment by jtmcdole** [comment] 2016-10-05 00:36
@cbracken said I should ping @leafpetersen @bwilkerson

**Comment by leafpetersen** [comment] 2016-10-05 03:59
If I understand the issue correctly, this is working as intended.  Strong mode allows implicit downcasts.  The call to `.where` returns `Iterable<String>`, which is a supertype of `List<String>`, and so we silently allow it.  In DDC (and eventually other platforms that implement the runtime side of Strong Mode, there would be a cast failure (actually the code would fail when you try to cast `list` to `List<String>`, since it ain't one).

There is a recently added experimental `--no-implicit-cast` flag in the analyzer which will disable this behavior if you prefer not to have explicit downcasts - if you try it out please send feedback, since we're very interested in its usability on real code.

Closing this bug - please reopen if I've misunderstood the issue.

**Closed by leafpetersen** 2016-10-05 03:59 UTC
Labels: analyzer-strong-mode, area-analyzer, P2 medium, Type: bug

**Comment by jtmcdole** [comment] 2016-10-05 05:41
So even:

```dart
List<String> foo = stringItems([1234, "hello", {}]);
```

Is considered `correct`, but I get plenty of warnings about:
Map foo = functionReturnsMapStringString();

Something feels broken about that.

**Comment by jtmcdole** [comment] 2016-10-05 05:42
Sorry, missed the last comment (was reading from email) - I'll give the `--no-implicit-cast` flag a try.

**Comment by jmesserly** [comment] 2016-10-05 16:23
> Map foo = functionReturnsMapStringString();

@jtmcdole I can't reproduce this, can you help? This says "no issues found" if I analyze in strong mode:
```dart
Map<String, String> functionReturnsMapStringString() => null;
main() {
  Map m = functionReturnsMapStringString();
  print(m);
}
```

**Comment by jtmcdole** [comment] 2016-10-05 17:00
@jmesserly: I'll have to look through our code base. I'm currently finished a "clean sweep" of the errors and now looking at warnings.

**Comment by jtmcdole** [comment] 2016-10-05 17:05
I think this one might be my bad and I'm conflating the two. This is the common example I was seeing in our codebase:
```dart
main() {
  Map foo = getFoo();
  doFoo(foo);
}

Map<String, String> getFoo() => <String, String>{};
doFoo(Map<String, String>foo) => print(foo);
```
```
doFoo(foo)
      ^^^
Unsound implicit cast from Map<dynamic, dynamic> to Map<String, String>
```

I just changed the `Map foo` to a `var foo` in those cases and the warning went away, as expected.

**Comment by leafpetersen** [comment] 2016-10-05 17:21
The "unsound implicit cast" is somewhat less relevant for non-DDC users.  It does point out places where you may be letting a dynamically typed list (or other datastructure) flow to a typed location though.  There is a way to globally suppress that warning using a .analysis_options file if you don't find it useful.
