### ISSUE TITLE
[NNBD Migration Tool] Add implicit downcasts

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37969] opened 2019-08-22 21:06 UTC
Note: also affected by new promotion algorithm
Open question: how do we approach this (part of the NNBD migration pass?  Separate pass?)

**Comment by MichaelRFairhurst** [comment] 2020-01-21 21:45
Duplicate of #38480

**Closed by MichaelRFairhurst** 2020-01-21 21:45 UTC
Labels: NNBD, area-analyzer
