### ISSUE TITLE
Submission Form for Analyzer error is empty

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#31379] opened 2017-11-15 14:45 UTC
Apparently, my intellij error just encountered an error:

```
6:26 AM	Dart Analyzer Error
				Encountered a Dart Analysis Server error.
				Open issue submission form?
```

When I click on "Open issue submission form", a new Issue is opened with nothing filled in:

```
Analyzer Feedback from IntelliJ

```

**Comment by floitschG** [comment] 2017-11-15 15:47
It could be that the error was because of an old SDK (but the "Open issue submission form" should always contain more data).

**Comment by devoncarew** [comment] 2017-11-18 23:22
What browser was it with? I've seen the data in the url before, but not displayed in the github page. We may need to encode better / differently / send less data.

/cc @stevemessick

**Comment by natebosch** [comment] 2018-08-31 23:08
Duplicate of #32496

**Closed by natebosch** 2018-08-31 23:08 UTC
Labels: area-intellij
