### ISSUE TITLE
Importing files from lib itself through 'package:' causes mismatching types

### ISSUE THREAD

**Issue by kaetemi** [dart-lang/sdk#34092] opened 2018-08-08 01:53 UTC
Issue occurs when the app is launched through a main() which is resident in the /lib/ directory, *which is the case with the default blank Flutter project*.

When a file in the library imports a class from the library itself through package, and another file in the same library imports it through a relative path, it will result in two distinct types being imported.

***

Test case: https://github.com/nbspou/darttest/tree/master/type_mismatch

c:\source\darttest\type_mismatch>dart bin/main.dart
776166849
278110852
a.runtimeType: **AwesomeClass**
a.runtimeType.hashCode: *333187867*
b.runtimeType: **AwesomeClass**
b.runtimeType.hashCode: *333187867*

c:\source\darttest\type_mismatch>**dart lib/type_mismatch.dart**
258920452
37514116
a.runtimeType: **AwesomeClass**
a.runtimeType.hashCode: **253396202**
b.runtimeType: **AwesomeClass**
b.runtimeType.hashCode: **1032280833**

***
Dart VM version: 2.0.0-dev.58.0.flutter-f981f09760 (Sat May 26 03:16:14 2018 +0000) on "windows_x64"

***

I propose that files under /lib/ should simply *not* be allowed to import files from the library or app itself through package: syntax, since there's no purpose and no consistency in mixing relative and package paths. Enforcing relative paths within /lib/ enforces a more consistent coding style.

**Comment by matanlurey** [comment] 2018-08-08 03:56
Duplicate of https://github.com/dart-lang/sdk/issues/33076.

**Closed by matanlurey** 2018-08-08 03:56 UTC
Labels: closed-duplicate
