### ISSUE TITLE
[vm/ffi] Provide a way to get offset of a field to its struct

### ISSUE THREAD

**Issue by safasofuoglu** [dart-lang/sdk#46563] opened 2021-07-04 07:22 UTC
Experimenting with a scenario where struct definitions are not replicated on the native side and general purpose functions are called, say, `simd_mul_f32_f32(ptr1, stride, ptr2, stride, count)`.  ptr1 and ptr2 would point to the exact f32 members.

A workaround could be to sum the `sizeOf`s of all the fields that come before, but with packing, padding and platform considerations it could be a nightmare.

Please advise @dcharkes .

**Comment by dcharkes** [comment] 2021-07-05 08:22
Duplicate of https://github.com/dart-lang/sdk/issues/41237.

**Closed by dcharkes** 2021-07-05 08:22 UTC
