### ISSUE TITLE
TypeError when computing Element.borderEdge/etc with fractional CSS values

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#37707] opened 2019-07-31 23:34 UTC
If there are fractional CSS values involved in computing `Element.paddingEdge`/`Element.borderEdge`/`Element.marginEdge`, then the getters throw with the following error:
```
Uncaught exception:
TypeError: 0.1: type 'JSDouble' is not a subtype of type 'int'
```

Reduced test case:
```dart
import 'dart:html';

main() {
  var element = new Element.div();
  document.body.append(element);
  element.style.marginTop = '0.1px';
  element.style.borderTop = '0.2px';
  element.style.paddingTop = '0.3px';
  print(element.marginEdge);
}
```

Dart version: 2.4.0 (Dartpad)
Tested in dart2js

**Comment by mit-mit** [comment] 2019-08-01 09:33
cc @eernstg

**Comment by eernstg** [comment] 2019-08-01 12:17
I don't really see any language level issue here, but there might be an issue caused by the choice of a new type (because Dart of today infers the type of a variable declared as `var x = e;` as the type of `e`, whereas `x` in Dart 1 had type `dynamic`).

The `dart:html` documentation says that the methods `Element.paddingEdge`, `Element.borderEdge`, `Element.marginEdge` all return a `CssRect` which implements `Rectangle<num>`. The code that actually runs would be something like the following:

```dart
@Native("Element")
class Element extends Node
    implements
        NonDocumentTypeChildNode,
        GlobalEventHandlers,
        ParentNode,
        ChildNode { ...
  CssRect get marginEdge => new _MarginCssRect(this);
}
...

abstract class CssRect implements Rectangle<num> { ...
    num _addOrSubtractToBoxModel(
      List<String> dimensions, String augmentingMeasurement) { ...
    var val = 0;

    for (String measurement in dimensions) {
      // The border-box and default box model both exclude margin in the regular
      // height/width calculation, so add it if we want it for this measurement.
      if (augmentingMeasurement == _MARGIN) {
        val += new Dimension.css(
                styles.getPropertyValue('$augmentingMeasurement-$measurement'))
            .value;
      }
   ...
    return val;
  }
}
```

The problem might be that the above code hasn't been tested with non-integral numbers for a long time, and `val` is now inferred as `int val` because of the initializer, so `val += ...` makes an attempt to add a `double` (typed as `num`) to `val`, which causes the run-time failure as reported. In that case using `double val = 0;` should fix the issue.

@terrylucas, you have been working on this file recently&mdash;WDYT?

**Comment by vsmenon** [comment] 2019-08-07 22:53
@terrylucas 

Looks like this code in dart:html:

```dart
  num _addOrSubtractToBoxModel(
      List<String> dimensions, String augmentingMeasurement) {
    // getComputedStyle always returns pixel values (hence, computed), so we're
    // always dealing with pixels in this method.
    var styles = _element.getComputedStyle();

    var val = 0;
```

should be (see type on last line):

```dart
  num _addOrSubtractToBoxModel(
      List<String> dimensions, String augmentingMeasurement) {
    // getComputedStyle always returns pixel values (hence, computed), so we're
    // always dealing with pixels in this method.
    var styles = _element.getComputedStyle();

    double val = 0;
```

Or, alternately: `var val = 0.0`

**Comment by rileyporter** [comment] 2021-12-28 23:18
Fixed by @Markzipan in https://dart-review.googlesource.com/c/sdk/+/118240

**Closed by rileyporter** 2021-12-28 23:18 UTC
Labels: web-libraries, library-html, P2, type-bug, area-web
