### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by boskokg** [dart-lang/sdk#35707] opened 2019-01-19 20:44 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.2.0-edge.d1817ddc91fd3aea061647b2e21860c47a5a5180`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2 unknown, screens 1280x1024, 1920x1080`

# Exception

Please append the contents of:
file:///private/var/folders/tw/q_d813091tq398jcjd9twky00000gn/T/report.txt

```
Dart analysis server, SDK version 2.2.0-edge.d1817ddc91fd3aea061647b2e21860c47a5a5180, server version 1.21.1, error: Failed to handle completion domain request: {id: 2695, method: completion.getSuggestions, params: {file: /Users/boskopopovic/Desktop/work/Flutter/Seve/seve/lib/models/RequiredDocument.dart, offset: 972}, clientRequestTime: 1547930245075}
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:199:7)
#1      AnalysisSessionImpl.getResolvedUnit (package:analyzer/src/dart/analysis/session.dart:164:5)
#2      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:67:47)
<asynchronous suspension>
#3      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:68:41)
<asynchronous suspension>
#4      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:50:18)
#5      OverrideContributor._buildReplacementText (package:analysis_server/src/services/completion/dart/override_contributor.dart:80:19)
<asynchronous suspension>
#6      OverrideContributor._buildSuggestion (package:analysis_server/src/services/completion/dart/override_contributor.dart:102:39)
<asynchronous suspension>

**Comment by boskokg** [comment] 2019-01-19 20:46
[report.txt](https://github.com/dart-lang/sdk/files/2775945/report.txt)

**Comment by stereotype441** [comment] 2019-01-23 18:07
Duplicate of #35456

**Closed by stereotype441** 2019-01-23 18:07 UTC
Labels: area-analyzer
