### ISSUE TITLE
Analysis server crash - 2.3.0-dev.0.5 ErrorToken.lexeme 

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36840] opened 2019-05-03 17:30 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6707.61`
- `2.3.0-dev.0.5`
- `IU-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 3840x2160`

## Exception
```
Dart analysis server, SDK version 2.3.0-dev.0.5, server version 1.26.0, error: Captured exception
Can't find ')' to match '('.
#0      ErrorToken.lexeme (package:front_end/src/fasta/scanner/error_token.dart:75:24)
#1      _withArgumentsExpectedFunctionBody (package:front_end/src/fasta/fasta_codes_generated.dart:3087:25)
#2      Parser.ensureBlock (package:front_end/src/fasta/parser/parser.dart:2696:20)
#3      Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3508:17)
#4      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3172:15)
#5      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3042:15)
#6      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2844:15)
#7      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1828:13)
#8      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1788:14)
#9      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:640:14)
#10     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:532:14)
#11     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:347:15)
#12     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:194:32)
#13     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:189:12)
#14     _File._parse (package:analyzer/src/services/available_declarations.dart:1595:23)
#15     _File.refresh (package:analyzer/src/services/available_declarations.dart:1044:30)
#16     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:634:12)
#17     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:498:7)
#18     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:219:13)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#24     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#30     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#31     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#32     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#33     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#34     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/c0/jv6k5x0j57vcwkdx6rcjgj3w0071_k/T/report.txt.

**Comment by stereotype441** [comment] 2019-05-03 17:34
@danrubel maintains the parser--reassigning to him.

**Comment by danrubel** [comment] 2019-05-06 17:19
I walked through the code specified by the stack trace and error tokens should not be leaking into the parser... but obviously they are. Do you have code which I can use to reproduce this issue?

**Comment by kevmoo** [comment] 2019-05-06 18:28
> I walked through the code specified by the stack trace and error tokens should not be leaking into the parser... but obviously they are. Do you have code which I can use to reproduce this issue?

I don't sadly. It was a transient error while doing a bunch of code generation, changing branches, etc.

**Comment by danrubel** [comment] 2019-05-06 20:02
I have some ideas to better prevent this from happening, but will take a while to implement.

**Comment by srawlins** [comment] 2019-08-10 23:17
Looks like a duplicate of https://github.com/dart-lang/sdk/issues/36241, which has a repro.

**Closed by srawlins** 2019-08-10 23:17 UTC
Labels: area-analyzer
