### ISSUE TITLE
@required doesn't catch missing `super` calls

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#44983] opened 2021-02-12 00:14 UTC
This does not give a `missing_required_param` lint:

```dart
import 'package:meta/meta.dart';

class A {
  A({ @required int test }) {
    print(test == null ? 'fail' : 'pass');
  }
}

class B extends A { }

void main() { B(); }
```

**Comment by srawlins** [comment] 2021-02-12 00:22
Duplicate of https://github.com/dart-lang/sdk/issues/30117

**Closed by srawlins** 2021-02-12 00:22 UTC
