### ISSUE TITLE
Failures on Bump linter to 655de5d0dc30cdd1df9ce4cd16bd7489106d987f...Remove duplicate getters from ClassDeclaration and MixinDeclaration.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#52912] opened 2023-07-12 11:45 UTC
There are new test failures on [Bump linter to 655de5d0dc30cdd1df9ce4cd16bd7489106d987f...Remove duplicate getters from ClassDeclaration and MixinDeclaration.](https://github.com/dart-lang/sdk/compare/2c97bd7801724dc9b95f39f3a88a9112f0287e5a~...23f414520647df3719da1a94f19237955a0f5fc2).

The tests
```
co19_2/LibTest/core/String/codeUnitAt_A03_t01 RuntimeError (expected Pass)
```
are failing on configurations
```
dartkp-linux-release-x64
```

Log: https://dart-ci.appspot.com/log/vm-kernel-precomp-linux-release-x64/dartkp-linux-release-x64/15730/co19_2/LibTest/core/String/codeUnitAt_A03_t01

```

--- Command "vm" (took 44ms):
DART_CONFIGURATION=ReleaseX64 TEST_COMPILATION_DIR=/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_LibTest_core_String_codeUnitAt_A03_t01 out/ReleaseX64/dart_precompiled_runtime --no-sound-null-safety -Dtest_runner.configuration=dartkp-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-linux-release-x64/tests_co19_2_src_LibTest_core_String_codeUnitAt_A03_t01/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.throws() fails
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:22)
#1      Expect.throws (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:290)
#2      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/core/String/codeUnitAt_A03_t01.dart:15)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:291)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)

--- Re-run this test:
python3 tools/test.py -n dartkp-linux-release-x64 co19_2/LibTest/core/String/codeUnitAt_A03_t01
```

Bisecting locally.

**Comment by dcharkes** [comment] 2023-07-12 12:06
Commit 23f414520647df3719da1a94f19237955a0f5fc2, reproduces failure.
Commit 7a258fa43b0, does not reproduce failure.
Bisecting 23f41452064...e1c12b3ab2e (25 commits). Trying 453fce9e77f.
Commit 453fce9e77f, reproduces failure.
Bisecting 453fce9e77f...e1c12b3ab2e (13 commits). Trying 0d47ba68902.
Commit 0d47ba68902, reproduces failure.
Bisecting 0d47ba68902...e1c12b3ab2e (7 commits). Trying 2f63acea22a.
Commit 2f63acea22a, reproduces failure.
Bisecting 2f63acea22a...e1c12b3ab2e (4 commits). Trying 81df36216fe.
Commit 81df36216fe, does not reproduce failure.
Bisecting 2f63acea22a...a0392698bf7 (2 commits). Trying a0392698bf7.
Commit a0392698bf7, does not reproduce failure.
Bisected to 2f63acea22a.

**Comment by sstrickl** [comment] 2023-07-13 08:32
Closing this in favor of the other bug, since they both have the same root cause.

**Closed by sstrickl** 2023-07-13 08:32 UTC
Labels: area-vm, gardening
