### ISSUE TITLE
New mixin syntax types are missing from code completion

### ISSUE THREAD

**Issue by weenzeel** [dart-lang/sdk#35529] opened 2018-12-31 14:21 UTC
* Dart SDK Version
Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "macos_x64"

* Whether you are using Windows, MacOSX, or Linux
Mac OSX 10.14.

Consider the following sample code:

```Dart
class ConstructA {
    String stringA = 'STRING_A';
 }

mixin ConstructB {
    String stringB = 'STRING_B';
}

class CompositionA extends Object with ConstructA {}
class CompositionB extends Object with ConstructB {}
```

When adding the mixin ConstructB to the class CompositionB ...

```Dart
class CompositionB extends Object with Construct...
```

<img width="728" alt="skarmavbild 2018-12-30 kl 21 27 15" src="https://user-images.githubusercontent.com/9976890/50561833-ed183280-0d0e-11e9-9a23-8361f5bd4fc1.png">

... the Dart Analysis Server provides code completion for ConstructA as a viable type that can be mixed in to the class, but fails to provide code completion for ConstructB.

ConstructB is however recognized as a valid mixable type, once the declaration of the composing class is completed.

(I've also noted that code completion for types using the new mixin syntax fails when trying to reference the types in a [Type] statement in a doc comment.)

**Comment by rivasdiaz** [comment] 2018-12-31 15:32
Just found another issue that seems to be related: importing a dart file with a mixin is not suggested by the IDE

To reproduce:
1. create a dart file that only contains a mixin declaration
2. create a dart file with a class that references the mixin created on step 1, the IDE will mark the mixin reference as an error.
3. Cmd+Click on the error will suggest creating a new class/mixin with the existing mixin name but will not suggest importing the dart file with the existing mixin declaration

**Comment by pq** [comment] 2020-02-14 19:32
This should be fixed.

![image](https://user-images.githubusercontent.com/67586/74560183-dd5fab80-4f1a-11ea-9b73-5e45a62446d2.png)


Test case in flight: https://dart-review.googlesource.com/c/sdk/+/135967

**Closed by pq** 2020-02-14 19:32 UTC
Labels: P2, analyzer-completion, area-analyzer, type-bug
