### ISSUE TITLE
TSAN reports data race in GC

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#53417] opened 2023-09-04 07:53 UTC
See [this log](https://dart-ci.appspot.com/log/vm-tsan-linux-release-x64/vm-tsan-linux-release-x64/204/vm/dart/isolates/reload_many_isolates_live_and_die_test)
```
--- Command "vm" (took 45.000999s):
DART_CONFIGURATION=ReleaseTSANX64 out/ReleaseTSANX64/dart --sound-null-safety -Dtest_runner.configuration=vm-tsan-linux-release-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/runtime/tests/vm/dart/isolates/reload_many_isolates_live_and_die_test.dart

exit code:
255

stdout:
Launching out/ReleaseTSANX64/dart --packages=.dart_tool/package_config.json --snapshot-kind=kernel --snapshot=/b/s/w/it68wmlv9i/KDROHP/test.dart.0.dill /b/s/w/it68wmlv9i/KDROHP/test.dart
Launching out/ReleaseTSANX64/dart --packages=.dart_tool/package_config.json --snapshot-kind=kernel --snapshot=/b/s/w/it68wmlv9i/KDROHP/test.dart.1.dill /b/s/w/it68wmlv9i/KDROHP/test.dart
Launching out/ReleaseTSANX64/dart --enable-vm-service:0 --disable-dart-dev --disable-service-auth-codes file:///b/s/w/it68wmlv9i/KDROHP/test.dart.0.dill
stdout: Initial child isolates launched
stdout: Waiting for reload to happen ...
stdout:  -> Still waiting ...
stdout:  -> Still waiting ...

stdout:  -> Still waiting ...
stdout:  -> Still waiting ...
stdout:  -> Still waiting ...
stdout:  -> Still waiting ...
stderr: /b/s/w/ir/buildtools/linux-x64/clang/bin/llvm-symbolizer: error: '/memfd:dart-code (deleted)': No such file or directory
stderr: ==================
stderr: WARNING: ThreadSanitizer: data race (pid=151611)
stderr:   Write of size 8 at 0x7b7c000afe48 by thread T20:
stderr:     #0 dart::Thread::set_top(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread.h:698:34 (dart+0x2622906)
stderr:     #1 dart::Scavenger::TryAllocateFromTLAB(dart::Thread*, long) out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:256:13 (dart+0x2622906)
stderr:     #2 dart::Scavenger::TryAllocate(dart::Thread*, long) out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:134:18 (dart+0x2622906)
stderr:     #3 dart::Heap::AllocateNew(dart::Thread*, long) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:84:27 (dart+0x2622906)
stderr:     #4 dart::Heap::Allocate(dart::Thread*, long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/heap/heap.h:87:16 (dart+0x2414fdb)
stderr:     #5 dart::Object::Allocate(long, long, dart::Heap::Space, bool, unsigned long, unsigned long) out/ReleaseTSANX64/../../runtime/vm/object.cc:2839:25 (dart+0x24392a8)
stderr:     #6 dart::Array::ObjectPtrType dart::Object::AllocateVariant<dart::Array>(long, dart::Heap::Space, long) out/ReleaseTSANX64/../../runtime/vm/object.h:749:9 (dart+0x24ad457)
stderr:     #7 dart::Array::NewUninitialized(long, long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/object.cc:25130:14 (dart+0x24ad457)
stderr:     #8 dart::Array::New(long, long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/object.cc:25142:12 (dart+0x24ad457)
stderr:     #9 dart::Array::New(long, dart::Heap::Space) out/ReleaseTSANX64/../../runtime/vm/object.h:11042:12 (dart+0x22e0f20)
stderr:     #10 dart::SpawnIsolateTask::EnqueueEntrypointInvocationAndNotifySpawner(dart::Thread*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:816:45 (dart+0x22e0f20)
stderr:     #11 dart::SpawnIsolateTask::Run(dart::Isolate*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:736:17 (dart+0x22e08f9)
stderr:     #12 dart::SpawnIsolateTask::RunLightweight(char const*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:712:5 (dart+0x22e0494)
stderr:     #13 dart::SpawnIsolateTask::Run() out/ReleaseTSANX64/../../runtime/lib/isolate.cc:645:7 (dart+0x22e01ac)
stderr:     #14 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x25efe29)
stderr:     #15 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x25f0357)
stderr:     #16 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x25134f3)
stderr: 
stderr:   Previous read of size 8 at 0x7b7c000afe48 by thread T22 (mutexes: write M0):
stderr:     #0 dart::Page::object_end() const out/ReleaseTSANX64/../../runtime/vm/heap/page.h (dart+0x25ae8a3)
stderr:     #1 dart::Page::used() const out/ReleaseTSANX64/../../runtime/vm/heap/page.h:107:34 (dart+0x25ae8a3)
stderr:     #2 dart::SemiSpace::used_in_words() const out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:46:18 (dart+0x25ae8a3)
stderr:     #3 dart::Scavenger::UsedInWords() const out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.h:157:17 (dart+0x25ae8a3)
stderr:     #4 dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0::operator()(dart::IsolateGroup*) const out/ReleaseTSANX64/../../runtime/vm/service.cc:4716:50 (dart+0x25ae8a3)
stderr:     #5 decltype(std::declval<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&>()(std::declval<dart::IsolateGroup*>())) std::_LIBCPP_ABI_NAMESPACE::__invoke[abi:v15000]<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*>(dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/invoke.h:403:23 (dart+0x25ae8a3)
stderr:     #6 void std::_LIBCPP_ABI_NAMESPACE::__invoke_void_return_wrapper<void, true>::__call<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*>(dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0&, dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/invoke.h:488:9 (dart+0x25ae8a3)
stderr:     #7 std::_LIBCPP_ABI_NAMESPACE::__function::__alloc_func<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0, std::_LIBCPP_ABI_NAMESPACE::allocator<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0>, void (dart::IsolateGroup*)>::operator()[abi:v15000](dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:185:16 (dart+0x25ae8a3)
stderr:     #8 std::_LIBCPP_ABI_NAMESPACE::__function::__func<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0, std::_LIBCPP_ABI_NAMESPACE::allocator<dart::GetProcessMemoryUsageHelper(dart::JSONStream*)::$_0>, void (dart::IsolateGroup*)>::operator()(dart::IsolateGroup*&&) out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:359:12 (dart+0x25ae8a3)
stderr:     #9 std::_LIBCPP_ABI_NAMESPACE::__function::__value_func<void (dart::IsolateGroup*)>::operator()[abi:v15000](dart::IsolateGroup*&&) const out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:512:16 (dart+0x23b10e3)
stderr:     #10 std::_LIBCPP_ABI_NAMESPACE::function<void (dart::IsolateGroup*)>::operator()(dart::IsolateGroup*) const out/ReleaseTSANX64/../../third_party/libcxx/include/__functional/function.h:1187:12 (dart+0x23b10e3)
stderr:     #11 dart::IsolateGroup::ForEach(std::_LIBCPP_ABI_NAMESPACE::function<void (dart::IsolateGroup*)>) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:673:5 (dart+0x23b10e3)
stderr:     #12 dart::GetProcessMemoryUsageHelper(dart::JSONStream*) out/ReleaseTSANX64/../../runtime/vm/service.cc:4711:7 (dart+0x25ad141)
stderr:     #13 dart::Service::PrintJSONForVM(dart::JSONStream*, bool) out/ReleaseTSANX64/../../runtime/vm/service.cc:5273:26 (dart+0x25ac873)
stderr:     #14 dart::GetVM(dart::Thread*, dart::JSONStream*) out/ReleaseTSANX64/../../runtime/vm/service.cc:5279:3 (dart+0x25b754b)
stderr:     #15 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool) out/ReleaseTSANX64/../../runtime/vm/service.cc:1036:7 (dart+0x25aa3db)
stderr:     #16 dart::Service::HandleRootMessage(dart::Array const&) out/ReleaseTSANX64/../../runtime/vm/service.cc:1070:10 (dart+0x25aabba)
stderr:     #17 dart::DN_HelperVMService_SendRootServiceMessage(dart::Isolate*, dart::Thread*, dart::Zone*, dart::NativeArguments*) out/ReleaseTSANX64/../../runtime/lib/vmservice.cc:76:10 (dart+0x2301a4b)
stderr:     #18 dart::BootstrapNatives::DN_VMService_SendRootServiceMessage(dart::Thread*, dart::Zone*, dart::NativeArguments*) out/ReleaseTSANX64/../../runtime/lib/vmservice.cc:73:1 (dart+0x2301a4b)
stderr:     #19 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) out/ReleaseTSANX64/../../runtime/vm/native_entry.cc:140:37 (dart+0x2412094)
stderr:     #20 <null> <null> (memfd:dart-code (deleted)+0x2bda)
stderr:     #21 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&) out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:37:10 (dart+0x2381411)
stderr:     #22 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&) out/ReleaseTSANX64/../../runtime/vm/dart_entry.cc:718:28 (dart+0x2381411)
stderr:     #23 dart::IsolateMessageHandler::HandleMessage(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message>>) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:1393:15 (dart+0x23b6680)
stderr:     #24 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool) out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:238:16 (dart+0x23f6d66)
stderr:     #25 dart::MessageHandler::TaskCallback() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:457:18 (dart+0x23f79a4)
stderr:     #26 dart::MessageHandlerTask::Run() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:31:15 (dart+0x23f7f13)
stderr:     #27 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x25efe29)
stderr:     #28 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x25f0357)
stderr:     #29 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x25134f3)
stderr: 
stderr:   Location is heap block of size 3360 at 0x7b7c000afe00 allocated by thread T11:
stderr:     #0 operator new(unsigned long) ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp:64:3 (dart+0x207cd37)
stderr:     #1 dart::ThreadRegistry::GetFromFreelistLocked(bool) out/ReleaseTSANX64/../../runtime/vm/thread_registry.cc:141:14 (dart+0x25f0519)
stderr:     #2 dart::ThreadRegistry::GetFreeThreadLocked(bool) out/ReleaseTSANX64/../../runtime/vm/thread_registry.cc:30:20 (dart+0x25f0519)
stderr:     #3 dart::Thread::AddActiveThread(dart::IsolateGroup*, dart::Isolate*, bool, bool) out/ReleaseTSANX64/../../runtime/vm/thread.cc:607:37 (dart+0x25e8cf1)
stderr:     #4 dart::Thread::EnterIsolate(dart::Isolate*) out/ReleaseTSANX64/../../runtime/vm/thread.cc:396:14 (dart+0x25e89c4)
stderr:     #5 dart::Isolate::InitIsolate(char const*, dart::IsolateGroup*, Dart_IsolateFlags const&, bool) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:1790:3 (dart+0x23b23c1)
stderr:     #6 dart::Dart::CreateIsolate(char const*, Dart_IsolateFlags const&, dart::IsolateGroup*) out/ReleaseTSANX64/../../runtime/vm/dart.cc:815:7 (dart+0x237913b)
stderr:     #7 dart::CreateIsolate(dart::IsolateGroup*, bool, char const*, void*, char**) out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1243:16 (dart+0x296f413)
stderr:     #8 dart::CreateWithinExistingIsolateGroup(dart::IsolateGroup*, char const*, char**) out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1331:7 (dart+0x296f31e)
stderr:     #9 dart::SpawnIsolateTask::RunLightweight(char const*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:692:24 (dart+0x22e0417)
stderr:     #10 dart::SpawnIsolateTask::Run() out/ReleaseTSANX64/../../runtime/lib/isolate.cc:645:7 (dart+0x22e01ac)
stderr:     #11 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x25efe29)
stderr:     #12 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x25f0357)
stderr:     #13 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x25134f3)
stderr: 
stderr:   Mutex M0 (0x7b6800000858) created at:
stderr:     #0 pthread_mutex_init ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1341:3 (dart+0x1ff8ea0)
stderr:     #1 dart::Mutex::Mutex(char const*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:308:12 (dart+0x25138b7)
stderr:     #2 dart::Scavenger::Scavenger(dart::Heap*, long) out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.cc:798:12 (dart+0x263df77)
stderr:     #3 dart::Heap::Heap(dart::IsolateGroup*, bool, long, long) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:49:7 (dart+0x262210f)
stderr:     #4 dart::Heap::Init(dart::IsolateGroup*, bool, long, long) out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:716:34 (dart+0x2625f73)
stderr:     #5 dart::IsolateGroup::CreateHeap(bool, bool) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:472:3 (dart+0x23b002f)
stderr:     #6 Dart_CreateIsolateGroup out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1367:10 (dart+0x296f9cd)
stderr:     #7 dart::bin::CreateIsolateGroupAndSetupHelper(bool, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**, int*, bool) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:814:15 (dart+0x208808d)
stderr:     #8 dart::bin::RunMainIsolate(char const*, char const*, bool, dart::bin::CommandLineOptions*) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1030:26 (dart+0x2087822)
stderr:     #9 dart::bin::main(int, char**) out/ReleaseTSANX64/../../runtime/bin/main_impl.cc:1421:9 (dart+0x2088dab)
stderr:     #10 main out/ReleaseTSANX64/../../runtime/bin/main.cc:9:3 (dart+0x20876d4)
stderr: 
stderr:   Thread T20 'DartWorker' (tid=151659, running) created by thread T7 at:
stderr:     #0 pthread_create ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1048:3 (dart+0x1ff752b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:173:12 (dart+0x25133b3)
stderr:     #2 dart::ThreadPool::Worker::StartThread() out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296:16 (dart+0x25ef581)
stderr:     #3 dart::ThreadPool::RunImpl(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::ThreadPool::Task, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::ThreadPool::Task>>) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94:17 (dart+0x25ef581)
stderr:     #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46:12 (dart+0x23f6a28)
stderr:     #5 dart::MessageHandler::PostMessage(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message>>, bool) out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:170:49 (dart+0x23f6a28)
stderr:     #6 dart::PortMap::PostMessage(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message>>, bool) out/ReleaseTSANX64/../../runtime/vm/port.cc:166:12 (dart+0x25179ab)
stderr:     #7 dart::Isolate::NotifyExitListeners() out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2232:7 (dart+0x23b9e5a)
stderr:     #8 dart::Isolate::LowLevelShutdown() out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2402:7 (dart+0x23b80f5)
stderr:     #9 dart::Isolate::Shutdown() out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2521:3 (dart+0x23ba99c)
stderr:     #10 dart::Dart::ShutdownIsolate(dart::Thread*) out/ReleaseTSANX64/../../runtime/vm/dart.cc:1170:17 (dart+0x2379009)
stderr:     #11 Dart_ShutdownIsolate out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1468:3 (dart+0x297007a)
stderr:     #12 dart::ShutdownIsolate(unsigned long) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2320:3 (dart+0x23b9f7e)
stderr:     #13 dart::MessageHandler::TaskCallback() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:524:5 (dart+0x23f78f3)
stderr:     #14 dart::MessageHandlerTask::Run() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:31:15 (dart+0x23f7f13)
stderr:     #15 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x25efe29)
stderr:     #16 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x25f0357)
stderr:     #17 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x25134f3)
stderr: 
stderr:   Thread T22 'DartWorker' (tid=151675, running) created by thread T10 at:
stderr:     #0 pthread_create ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1048:3 (dart+0x1ff752b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:173:12 (dart+0x25133b3)
stderr:     #2 dart::ThreadPool::Worker::StartThread() out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296:16 (dart+0x25ef581)
stderr:     #3 dart::ThreadPool::RunImpl(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::ThreadPool::Task, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::ThreadPool::Task>>) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94:17 (dart+0x25ef581)
stderr:     #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46:12 (dart+0x23f6a28)
stderr:     #5 dart::MessageHandler::PostMessage(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message>>, bool) out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:170:49 (dart+0x23f6a28)
stderr:     #6 dart::PortMap::PostMessage(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::Message, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::Message>>, bool) out/ReleaseTSANX64/../../runtime/vm/port.cc:166:12 (dart+0x25179ab)
stderr:     #7 dart::ServiceIsolate::SendServiceControlMessage(dart::Thread*, long, long, char const*) out/ReleaseTSANX64/../../runtime/vm/service_isolate.cc:84:10 (dart+0x25c845d)
stderr:     #8 dart::ServiceIsolate::SendIsolateShutdownMessage() out/ReleaseTSANX64/../../runtime/vm/service_isolate.cc:271:10 (dart+0x25c8efe)
stderr:     #9 dart::Isolate::Shutdown() out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2485:5 (dart+0x23ba7e0)
stderr:     #10 dart::Dart::ShutdownIsolate(dart::Thread*) out/ReleaseTSANX64/../../runtime/vm/dart.cc:1170:17 (dart+0x2379009)
stderr:     #11 Dart_ShutdownIsolate out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1468:3 (dart+0x297007a)
stderr:     #12 dart::ShutdownIsolate(unsigned long) out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2320:3 (dart+0x23b9f7e)
stderr:     #13 dart::MessageHandler::TaskCallback() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:524:5 (dart+0x23f78f3)
stderr:     #14 dart::MessageHandlerTask::Run() out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:31:15 (dart+0x23f7f13)
stderr:     #15 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x25efe29)
stderr:     #16 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x25f0357)
stderr:     #17 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x25134f3)
stderr: 
stderr:   Thread T11 'DartWorker' (tid=151647, running) created by thread T5 at:
stderr:     #0 pthread_create ../staging/llvm_build/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1048:3 (dart+0x1ff752b)
stderr:     #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:173:12 (dart+0x25133b3)
stderr:     #2 dart::ThreadPool::Worker::StartThread() out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296:16 (dart+0x25ef581)
stderr:     #3 dart::ThreadPool::RunImpl(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::ThreadPool::Task, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::ThreadPool::Task>>) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94:17 (dart+0x25ef581)
stderr:     #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46:12 (dart+0x23f67e6)
stderr:     #5 dart::MessageHandler::Run(dart::ThreadPool*, dart::MessageHandler::MessageStatus (*)(unsigned long), void (*)(unsigned long), unsigned long) out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:119:24 (dart+0x23f67e6)
stderr:     #6 dart::Isolate::Run() out/ReleaseTSANX64/../../runtime/vm/isolate.cc:2331:22 (dart+0x23b9f4c)
stderr:     #7 Dart_RunLoopAsync out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:2095:12 (dart+0x297447d)
stderr:     #8 dart::SpawnIsolateTask::Run(dart::Isolate*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:747:10 (dart+0x22e0a3d)
stderr:     #9 dart::SpawnIsolateTask::RunLightweight(char const*) out/ReleaseTSANX64/../../runtime/lib/isolate.cc:712:5 (dart+0x22e0494)
stderr:     #10 dart::SpawnIsolateTask::Run() out/ReleaseTSANX64/../../runtime/lib/isolate.cc:645:7 (dart+0x22e01ac)
stderr:     #11 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:158:15 (dart+0x25efe29)
stderr:     #12 dart::ThreadPool::Worker::Main(unsigned long) out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:330:9 (dart+0x25f0357)
stderr:     #13 dart::ThreadStart(void*) out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:154:5 (dart+0x25134f3)
stderr: 
stderr: SUMMARY: ThreadSanitizer: data race out/ReleaseTSANX64/../../runtime/vm/thread.h:698:34 in dart::Thread::set_top(unsigned long)
stderr: ==================

stderr:
Unhandled exception:
Bad state: The client closed with pending request "getVM".

--- Re-run this test:
python3 tools/test.py -n vm-tsan-linux-release-x64 vm/dart/isolates/reload_many_isolates_live_and_die_test
```

/cc @rmacnak-google

**Comment by rmacnak-google** [comment] 2023-09-05 17:59
Duplicate of https://github.com/dart-lang/sdk/issues/52862

**Closed by rmacnak-google** 2023-09-05 17:59 UTC
Labels: area-vm, gardening
