### ISSUE TITLE
kernel_binary_flowgraph.cc: 4485: error: expected: procedure_helper.forwarding_stub_super_target_ != -1

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#33029] opened 2018-05-03 00:43 UTC
The precompiler is failing on two tests
corelib_2/growable_list_test
language_2/extract_type_arguments_test

The backtrace from these tests

```
DART_CONFIGURATION=DebugX64 DART_VM_FLAGS=--limit-ints-to-64-bits /b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/pkg/vm/tool/gen_kernel --aot --strong-mode --sync-async --platform=out/DebugX64/vm_platform_strong.dill -o /b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/out/DebugX64/generated_compilations/dartkp-strong/tests_corelib_2_growable_list_test/out.dill --entry-points out/DebugX64/gen/runtime/bin/precompiler_entry_points.json --entry-points /b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/pkg/vm/lib/transformations/type_flow/entry_points_extra.json --entry-points /b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/pkg/vm/lib/transformations/type_flow/entry_points_extra_standalone.json /b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/tests/corelib_2/growable_list_test.dart
exit code:
0
--- Command "precompiler" (took 35.000505s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart_bootstrap --snapshot-kind=app-aot --snapshot=/b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/out/DebugX64/generated_compilations/dartkp-strong/tests_corelib_2_growable_list_test/out.S --strong --preview-dart-2 --no-enable-malloc-hooks --reify-generic-functions --limit-ints-to-64-bits --sync-async --ignore-unrecognized-flags --packages=/b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/.packages /b/build/slave/vm-kernel-precomp-linux-debug-x64-6-8-be/build/sdk/out/DebugX64/generated_compilations/dartkp-strong/tests_corelib_2_growable_list_test/out.dill
exit code:
-6
stderr:
../../runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc: 4485: error: expected: procedure_helper.forwarding_stub_super_target_ != -1
Dumping native stack trace for thread 6fef
  [0x0000000000e519df] dart::Profiler::DumpStackTrace(void*)
  [0x0000000000e519df] dart::Profiler::DumpStackTrace(void*)
  [0x00000000011639c6] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x000000000108bf7f] dart::kernel::StreamingFlowGraphBuilder::ReadUntilFunctionNode(dart::ParsedFunction*)
  [0x00000000010a0fa0] dart::kernel::StreamingFlowGraphBuilder::BuildGraph(long)
  [0x00000000010c62de] dart::kernel::FlowGraphBuilder::BuildGraph()
  [0x00000000010fe344] dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*> const&, long, bool)
  [0x0000000000f5c672] dart::PrecompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x0000000000f607d5] Unknown symbol
  [0x0000000000f59bd9] dart::Precompiler::CompileFunction(dart::Precompiler*, dart::Thread*, dart::Zone*, dart::Function const&, dart::DirectChainedHashMap<dart::FieldTypePair>*)
  [0x0000000000f58885] dart::Precompiler::ProcessFunction(dart::Function const&)
  [0x0000000000f51c21] dart::Precompiler::Iterate()
  [0x0000000000f4e000] dart::Precompiler::DoCompileAll(Dart_QualifiedFunctionName*)
  [0x0000000000f4dd2d] dart::Precompiler::CompileAll(Dart_QualifiedFunctionName*)
  [0x00000000011574e5] Dart_Precompile
  [0x0000000000a17597] dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)
  [0x0000000000a1854b] dart::bin::main(int, char**)
  [0x0000000000a18e09] Unknown symbol
-- End of DumpStackTrace
```

**Comment by mkustermann** [comment] 2018-05-03 08:04
I think this crash started happening after 7d5025e814fa4716fb8c6a4c104ea1c28d578911 landed. I recommended to Samir to revert the change until the cause has been identified. The revert landed in 24dd9b4176ec9d8694ba89cfa07e503f9c53a35d . Though during US time this got re-landed (for some reason) via 2765fcf2aecd3841d082fedaeafc00a73a965f8c .

Maybe @sjindel-google is a better owner for this?

**Comment by sjindel-google** [comment] 2018-05-04 11:37
I don't believe this is caused by my code, because these tests are still crashing after my revision which appeared to cause it was reverted.

**Comment by whesse** [comment] 2018-05-04 11:49
I don't see this.  I see them failing after the original commit, stopping after it is reverted, the crashes resuming after the revert is reverted, the crashes continuing but being green after the status file is modified, the crashes stopping (and the builder turning red) after the revert of the revert is reverted.

Which build has the code reverted, but still has the crashes?

**Comment by sjindel-google** [comment] 2018-05-04 11:51
The crashes are still reproducing on the tip of master.

**Comment by whesse** [comment] 2018-05-04 11:55
The crashes aren't happening on the builder at tip-of-tree.  It is red because it is expecting a crash and not seeing it.  Which configuration reproduces the crashes? The builder is at https://ci.chromium.org/buildbot/client.dart/vm-kernel-precomp-linux-debug-x64-5-8-be/

**Comment by sjindel-google** [comment] 2018-05-04 12:25
This is not a priority right now because we can't re-land the broken code which implements behavior that breaks Mockito. However, the crash suggests that there may be a deeper issue which could be reproduced without that change. We should investigate this further at some point.

**Comment by sjindel-google** [comment] 2019-01-23 14:56
The bug has been fixed and these tests don't crash anymore.

**Closed** 2019-01-23 14:57 UTC
Labels: area-front-end, area-vm, customer-vm, p3-low
