### ISSUE TITLE
Error while using IntelliJ/Analyzer

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29824] opened 2017-06-08 19:42 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.23`
- `1.23.0`
- `IU-171.4694.23, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.4 unknown, screens 1680x1050  Retina`

# Exception

```
Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Analysis failed: /Users/matanl/git/glob/test/list_test.dart context: exception_20170608_124225_726
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:448)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:413)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:683)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9413)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6938)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:386)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6934)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7768)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#12     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#13     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:419)
```

## Full Logs

```
Dart analysis server, SDK version 1.23.0, server version 1.18.0, error: Analysis failed: /Users/matanl/git/glob/test/list_test.dart context: exception_20170608_124225_726
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:448)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:413)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:683)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9413)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6938)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:386)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6934)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7768)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#12     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#13     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:419)
#14     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7764)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#16     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#17     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#18     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#19     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#20     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#21     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#23     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#24     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#25     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#26     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#27     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#28     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#29     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#30     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#31     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#32     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#33     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#35     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#36     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#37     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#38     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#39     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#40     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#41     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#42     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#43     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#44     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#45     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#46     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#47     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#48     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#49     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#50     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#51     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#52     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#53     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#54     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#55     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#56     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#57     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#58     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#59     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#60     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#61     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#62     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#63     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#64     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#65     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#66     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#67     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#68     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#69     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#70     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#71     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#72     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#73     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#74     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#75     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#76     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#77     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#78     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#79     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#80     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#81     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#82     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#83     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#84     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#85     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#86     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#87     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#88     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#89     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#90     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#91     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#92     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#93     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#94     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#95     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#96     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#97     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#98     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#99     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#100    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#101    FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#102    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#103    GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#104    GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#105    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#106    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#107    ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#108    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#109    GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#110    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#111    _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#112    MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#113    ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#114    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#115    GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#116    GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#117    ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#118    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#119    BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#120    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#121    GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#122    GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#123    BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#124    BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#125    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#126    GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#127    GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#128    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#129    FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#130    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#131    GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#132    GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#133    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#134    FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5204)
#135    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#136    GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:156)
#137    GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:247)
#138    GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:222)
#139    GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:416)
#140    GeneralizingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:318)
#141    FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#142    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#143    CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#144    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#145    GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:219)
#146    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#147    _IndexAssembler.assemble (package:analyzer/src/dart/analysis/index.dart:240)
#148    indexUnit (package:analyzer/src/dart/analysis/index.dart:37)
#149    AnalysisDriver._serializeResolvedUnit (package:analyzer/src/dart/analysis/driver.dart:1171)
#150    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:958)
#151    PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#152    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#153    AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:788)
<asynchronous suspension>
#154    AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1403)
<asynchronous suspension>
#155    AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1337)
#156    AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:421)
#157    SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#158    StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#159    Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:489)
#160    _rootRun (dart:async/zone.dart:1120)
#161    _CustomZone.run (dart:async/zone.dart:1001)
#162    runZoned (dart:async/zone.dart:1465)
#163    Driver._captureExceptions (package:analysis_server/src/server/driver.dart:528)
#164    Driver.start (package:analysis_server/src/server/driver.dart:488)
#165    main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analysis_server/bin/server.dart:12)
#166    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#167    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1496950938132 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/lib/glob.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/matanl/git/glob
1496950938588 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/lib/src/ast.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/matanl/git/g
1496950939022 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/lib/src/list_tree.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/matanl/git/glob/lib/s
1496950939092 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/lib/src/parser.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/matanl/gi
1496950939157 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/lib/src/stream_pool.dart","errors":[]}}
1496950939192 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/lib/src/utils.dart","errors":[{"severity":"ERROR","type":"COMPILE_TIME_ERROR","location":{"file":"/Users/matanl/git
1496950939416 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/matanl/git/glob/test/list_test.dart context: exception_20170608_124219_388","stackTrace":"NoSuchMe
1496950939575 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/test/match_test.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/Users/matanl/git/g
1496950939638 <= {"event":"analysis.errors","params":{"file":"/Users/matanl/git/glob/test/parse_test.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/Users/matanl/git/g
1496950939645 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1496950940643 => {"id":"7","method":"analysis.setPriorityFiles","params":{"files":["/Users/matanl/git/glob/test/list_test.dart"]},"clientRequestTime":1496950940643}
1496950940643 => {"id":"8","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/matanl/git/glob/test/list_test.dart"],"OVERRIDES":["/Users/matanl/git/glob/test/list_te
1496950940645 <= {"id":"7"}
1496950940647 <= {"id":"8"}
1496950940662 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1496950940894 => {"id":"9","method":"edit.getAssists","params":{"file":"/Users/matanl/git/glob/test/list_test.dart","offset":0,"length":0},"clientRequestTime":1496950940894}
1496950940897 => {"id":"10","method":"edit.getAssists","params":{"file":"/Users/matanl/git/glob/test/list_test.dart","offset":0,"length":0},"clientRequestTime":1496950940897}
1496950941243 <= {"id":"9","result":{"assists":[]}}
1496950941243 <= {"id":"10","result":{"assists":[]}}
1496950941247 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1496950942878 => {"id":"11","method":"edit.getAssists","params":{"file":"/Users/matanl/git/glob/test/list_test.dart","offset":217,"length":0},"clientRequestTime":1496950942878}
1496950942878 => {"id":"12","method":"edit.getAssists","params":{"file":"/Users/matanl/git/glob/test/list_test.dart","offset":217,"length":0},"clientRequestTime":1496950942878}
1496950942879 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1496950942949 <= {"id":"11","result":{"assists":[]}}
1496950943006 <= {"id":"12","result":{"assists":[]}}
1496950943008 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1496950944141 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1496950944683 => {"id":"13","method":"edit.getAssists","params":{"file":"/Users/matanl/git/glob/test/list_test.dart","offset":217,"length":0},"clientRequestTime":1496950944683}
1496950944698 => {"id":"14","method":"edit.getAssists","params":{"file":"/Users/matanl/git/glob/test/list_test.dart","offset":217,"length":0},"clientRequestTime":1496950944698}
1496950945739 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/matanl/git/glob/test/list_test.dart context: exception_20170608_124225_726","stackTrace":"NoSuchMe
```

**Comment by bwilkerson** [comment] 2017-06-08 20:37
I believe that this is a duplicate of https://github.com/dart-lang/sdk/issues/29812. Please re-open if I'm mistaken.

**Closed by bwilkerson** 2017-06-08 20:37 UTC
