### ISSUE TITLE
The compiler is broken.

### ISSUE THREAD

**Issue by ajlai** [dart-lang/sdk#24484] opened 2015-10-02 00:53 UTC
Operating System: OS X Yosemite (10.10.5)
dart --version: Dart VM version: 1.12.1 (Tue Sep  8 04:10:39 2015) on "macos_x64"
Output:
```
[Error from Dart2JS on photo_prints_web|web/main.dart]:
packages/photo_prints_web/views/preview/view.dart:32:81:
String must end with ".
      span({}, "YOU SELECTED ${_state.project.get().intendedProduct.displayName}),
                                                                                ^^
[Error from Dart2JS on photo_prints_web|web/main.dart]:
packages/photo_prints_web/views/preview/view.dart:29:3:
The compiler crashed when compiling this element.
  _renderHeader() {
  ^^^^^^^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on photo_prints_web|web/main.dart threw error: Class 'Send' has no instance getter 'token'.

NoSuchMethodError: method not found: 'token'
Receiver: Instance of 'Send'
Arguments: []
dart:core                                                               Object.noSuchMethod
package:compiler_unsupported/src/scanner/listener.dart 1398             ElementListener.endLiteralString
package:compiler_unsupported/src/scanner/parser.dart 2209               Parser.parseSingleLiteralString
package:compiler_unsupported/src/scanner/parser.dart 2149               Parser.parseLiteralString
package:compiler_unsupported/src/scanner/parser.dart 1924               Parser.parsePrimary
package:compiler_unsupported/src/scanner/parser.dart 1889               Parser.parseUnaryExpression
package:compiler_unsupported/src/scanner/parser.dart 1768               Parser.parsePrecedenceExpression
package:compiler_unsupported/src/scanner/parser.dart 1744               Parser.parseExpression
package:compiler_unsupported/src/scanner/parser.dart 2257               Parser.parseArguments
package:compiler_unsupported/src/scanner/parser.dart 2236               Parser.parseArgumentsOpt
package:compiler_unsupported/src/scanner/parser.dart 2226               Parser.parseSend
package:compiler_unsupported/src/scanner/parser.dart 2083               Parser.parseSendOrFunctionLiteral
package:compiler_unsupported/src/scanner/parser.dart 1917               Parser.parsePrimary
package:compiler_unsupported/src/scanner/parser.dart 1889               Parser.parseUnaryExpression
package:compiler_unsupported/src/scanner/parser.dart 1768               Parser.parsePrecedenceExpression
package:compiler_unsupported/src/scanner/parser.dart 1744               Parser.parseExpression
package:compiler_unsupported/src/scanner/parser.dart 2047               Parser.parseLiteralListOrMap
package:compiler_unsupported/src/scanner/parser.dart 1954               Parser.parsePrimary
package:compiler_unsupported/src/scanner/parser.dart 1889               Parser.parseUnaryExpression
package:compiler_unsupported/src/scanner/parser.dart 1768               Parser.parsePrecedenceExpression
package:compiler_unsupported/src/scanner/parser.dart 1744               Parser.parseExpression
package:compiler_unsupported/src/scanner/parser.dart 2257               Parser.parseArguments
package:compiler_unsupported/src/scanner/parser.dart 2236               Parser.parseArgumentsOpt
package:compiler_unsupported/src/scanner/parser.dart 2226               Parser.parseSend
package:compiler_unsupported/src/scanner/parser.dart 2083               Parser.parseSendOrFunctionLiteral
package:compiler_unsupported/src/scanner/parser.dart 1917               Parser.parsePrimary
package:compiler_unsupported/src/scanner/parser.dart 1889               Parser.parseUnaryExpression
package:compiler_unsupported/src/scanner/parser.dart 1768               Parser.parsePrecedenceExpression
package:compiler_unsupported/src/scanner/parser.dart 1744               Parser.parseExpression
package:compiler_unsupported/src/scanner/parser.dart 1618               Parser.parseReturnStatement
package:compiler_unsupported/src/scanner/parser.dart 1547               Parser.parseStatement
package:compiler_unsupported/src/scanner/parser.dart 1502               Parser.parseFunctionBody
package:compiler_unsupported/src/scanner/parser.dart 1400               Parser.parseFunction
package:compiler_unsupported/src/scanner/listener.dart 2314             MethodElementX&PartialElement&PartialFunctionMixin.parseNode.parseFunction
package:compiler_unsupported/src/scanner/listener.dart 2602             parse
package:compiler_unsupported/src/scanner/listener.dart 2317             MethodElementX&PartialElement&PartialFunctionMixin.parseNode
package:compiler_unsupported/src/resolution/resolution_common.dart 888  ResolverTask.resolveSignature.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 2213                     CompilerTask.measure
package:compiler_unsupported/src/resolution/resolution_common.dart 888  ResolverTask.resolveSignature.<fn>
package:compiler_unsupported/src/compiler.dart 920                      Compiler.withCurrentElement
package:compiler_unsupported/src/resolution/resolution_common.dart 886  ResolverTask.resolveSignature
package:compiler_unsupported/src/elements/modelx.dart 1786              BaseFunctionElementX.computeSignature.<fn>
package:compiler_unsupported/src/compiler.dart 920                      Compiler.withCurrentElement
package:compiler_unsupported/src/elements/modelx.dart 1785              BaseFunctionElementX.computeSignature
package:compiler_unsupported/src/elements/modelx.dart 1807              BaseFunctionElementX.computeType
package:compiler_unsupported/src/enqueue.dart 192                       Enqueuer.processInstantiatedClassMember
package:compiler_unsupported/src/elements/common.dart 317               ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember.<fn>
package:compiler_unsupported/src/util/link_implementation.dart 119      LinkEntry.forEach
package:compiler_unsupported/src/elements/modelx.dart 2472              ClassElementX.forEachLocalMember
package:compiler_unsupported/src/elements/common.dart 317               ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember
package:compiler_unsupported/src/enqueue.dart 261                       Enqueuer.processInstantiatedClass.<fn>.processClass
package:compiler_unsupported/src/enqueue.dart 271                       Enqueuer.processInstantiatedClass.<fn>
package:compiler_unsupported/src/compiler.dart 2213                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 249                       Enqueuer.processInstantiatedClass
package:compiler_unsupported/src/enqueue.dart 130                       Enqueuer.registerInstantiatedType.<fn>
package:compiler_unsupported/src/compiler.dart 2213                     CompilerTask.measure
package:compiler_unsupported/src/enqueue.dart 125                       Enqueuer.registerInstantiatedType
package:compiler_unsupported/src/resolution/registry.dart 484           ResolutionRegistry.registerInstantiatedType
package:compiler_unsupported/src/resolution/members.dart 3375           ResolverVisitor.visitNewExpression
package:compiler_unsupported/src/tree/nodes.dart 526                    NewExpression.accept
package:compiler_unsupported/src/resolution/resolution_common.dart 982  CommonResolverVisitor.visit
package:compiler_unsupported/src/resolution/members.dart 3134           ResolverVisitor.visitReturn
package:compiler_unsupported/src/tree/nodes.dart 1089                   Return.accept
package:compiler_unsupported/src/resolution/resolution_common.dart 982  CommonResolverVisitor.visit
package:compiler_unsupported/src/resolution/members.dart 558            ResolverVisitor.visitFunctionExpression
package:compiler_unsupported/src/tree/nodes.dart 789                    FunctionExpression.accept
package:compiler_unsupported/src/resolution/resolution_common.dart 982  CommonResolverVisitor.visit
package:compiler_unsupported/src/resolution/members.dart 804            ResolverVisitor.resolveArguments
package:compiler_unsupported/src/resolution/members.dart 2440           ResolverVisitor.handleStaticOrTopLevelAccess
package:compiler_unsupported/src/resolution/members.dart 2580           ResolverVisitor.handleResolvedSend
package:compiler_unsupported/src/resolution/members.dart 2618           ResolverVisitor.handleUnqualifiedSend
package:compiler_unsupported/src/resolution/members.dart 2631           ResolverVisitor.visitSend
package:compiler_unsupported/src/tree/nodes.dart 381                    Send.accept
package:compiler_unsupported/src/resolution/resolution_common.dart 982  CommonResolverVisitor.visit
package:compiler_unsupported/src/resolution/resolution_common.dart 288  ResolverTask.resolveField
package:compiler_unsupported/src/resolution/resolution_common.dart 40   ResolverTask.resolve.<fn>
package:compiler_unsupported/src/compiler.dart 2213                     CompilerTask.measure
package:compiler_unsupported/src/resolution/resolution_common.dart 15   ResolverTask.resolve
package:compiler_unsupported/src/compiler.dart 1815                     Compiler.analyzeElement
package:compiler_unsupported/src/compiler.dart 1841                     Compiler.analyze
package:compiler_unsupported/src/compiler.dart 45                       ResolutionWorkItem.run
package:compiler_unsupported/src/compiler.dart 1749                     Compiler.processQueue.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 920                      Compiler.withCurrentElement
package:compiler_unsupported/src/compiler.dart 1748                     Compiler.processQueue.<fn>
package:compiler_unsupported/src/enqueue.dart 953                       QueueFilter.processWorkItem
package:compiler_unsupported/src/enqueue.dart 639                       Enqueuer.forEach
package:compiler_unsupported/src/compiler.dart 1747                     Compiler.processQueue
package:compiler_unsupported/src/compiler.dart 1615                     Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 1524                     Compiler.runCompiler.<fn>

```

**Comment by sigmundch** [comment] 2015-10-02 17:24
Thanks for reporting!

We should definitely fix this. I'm only "closing" this to indicate that it is a duplicate of https://github.com/dart-lang/sdk/issues/18945.

**Closed by sigmundch** 2015-10-02 17:24 UTC
Labels: Area-Dart2JS, Type-Defect
