### ISSUE TITLE
Extend String.substring to accept negative arguments

### ISSUE THREAD

**Issue by smanilov** [dart-lang/sdk#28199] opened 2016-12-23 15:07 UTC
Currently, if I want to trim the last element of a String, I need to do this:

    String trim(String str) {
        return str.substring(0, str.length - 1);
    }

I would prefer if I can directly use -1 here to simplify the use of substring, as in:

    String trim(String str) {
        return str.substring(0, -1);
    }

Currently, this throws an exception (value out of range or something of the sort).

If you're not convinced this is useful, consider this:

    return funkyFunctionCall(many, arguments, are, passed).split(' ')[0].substring(0, -1);

Surely, no one would want to write that anyway ( ; ), but I think this is a simple non-breaking change that increases the dexterity of the substring tool considerably.

**Comment by kulshekhar** [comment] 2016-12-23 15:19
This may be a duplicate of #1217 and/or #27695

**Comment by lrhn** [comment] 2016-12-25 12:18
It is a duplicate of both.

Personally, I'd prefer to add a slice operator and let that be fancy, and keep `substring` as the plain base operation that other things are defined in terms of. No actual plans of that, though.

**Closed by lrhn** 2016-12-25 12:18 UTC
