### ISSUE TITLE
Can not open project

### ISSUE THREAD

**Issue by dunno7** [dart-lang/sdk#40671] opened 2020-02-19 08:19 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.7.1`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.1, server version 1.27.4, error: Bad state: No dart:core, sdk: {
  "runtimeType": "FolderBasedDartSdk",
  "libraryMap": {},
  "directory": "/Users/dungnart/Workspace/Flutter/sdk"
}
#0      PluginWatcher._getSdkPath (package:analysis_server/src/plugin/plugin_watcher.dart:111:9)
#1      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:56:49)
#2      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1846:22)
#3      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:297:16)
#4      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:167:33)
#5      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:775:48)
#6      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1189:19)
#7      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1251:16)
#8      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:791:9)
#9      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:496:22)
#10     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#11     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:319:16)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1502:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#23     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#36     _rootRunUnary (dart:async/zone.dart:1134:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#49     _rootRunUnary (dart:async/zone.dart:1134:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#55     _StreamController._add (dart:async/stream_controller.dart:642:7)
#56     _StreamController.add (dart:async/stream_controller.dart:588:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#58     _rootRunUnary (dar...
```

For additional log information, please append the contents of
file:///private/var/folders/cz/cft078v1411gdl7m5kx36wbc0000gn/T/report1.txt.

**Comment by farheen21** [comment] 2020-02-22 07:27
are you using Vscode or intelij ?

**Comment by dungnart** [comment] 2020-02-22 09:09
I am using Android Studio.

**Comment by srawlins** [comment] 2020-06-13 03:22
Thanks for reporting this issue! This was also reported at https://github.com/dart-lang/sdk/issues/41620; please follow along there.

**Comment by srawlins** [comment] 2020-06-13 03:23
Duplicate of #41620

**Closed by srawlins** 2020-06-13 03:23 UTC
Labels: analyzer-crash-report, area-analyzer
