### ISSUE TITLE
Error after executing "flutter pub global run webdev serve --auto restart"

### ISSUE THREAD

**Issue by Relz** [dart-lang/sdk#37444] opened 2019-07-04 07:16 UTC
### Environment
Flutter 1.8.1-pre.14 • channel unknown • unknown source
Framework • revision d41eeeb50d (15 hours ago) • 2019-07-03 09:13:37 -0700
Engine • revision 7d3e722349
Tools • Dart 2.5.0 (build 2.5.0-dev.0.0 67ab3be10d)

I installed Flutter SDK through git clone (master channel)

### Error after executing "flutter pub global run webdev serve --auto restart"
dartdevc -k arguments: --dart-sdk-summary=C:\Users\alexey.starovoitov\flutter_sdk\bin\cache\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\alexey.starovoitov\AppData\Local\Temp\scratch_spaceacb679c8-9e2a-11e9-94de-1c1b0dcf78a5\packages/flutter_web/physics.ddc.js --source-map --summary=C:\Users\alexey.starovoitov\AppData\Local\Temp\scratch_spaceacb679c8-9e2a-11e9-94de-1c1b0dcf78a5\packages/flutter_web/src/physics/clamped_simulation.ddc.dill=packages/flutter_web/src/physics/clamped_simulation --packages=file:///C:/Users/ALEXEY~1.STA/AppData/Local/Temp/kernel_builder_acb679f7-9e2a-11e9-94de-1c1b0dcf78a5/.packages --module-name=packages/flutter_web/physics --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map package:flutter_web/physics.dart
    dart --version: 2.5.0-dev.0.0.flutter-67ab3be10d (Sat Jun 29 18:45:11 2019 +0000) on "windows_x64"

Bad state: Expected to get sdk digest at null
#0      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:149:5)
<asynchronous suspension>
#1      _compile (package:dev_compiler/src/kernel/command.dart:252:27)
<asynchronous suspension>
#2      compile (package:dev_compiler/src/kernel/command.dart:43:18)
<asynchronous suspension>
#3      compile (package:dev_compiler/src/compiler/shared_command.dart:409:12)
#4      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:68:13)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:66:24)
<asynchronous suspension>
#10     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#16     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

[SEVERE]build_web_compilers:ddc on package:flutter_web/src/physics/clamped_simulation.ddc.module (cached): Error compiling dartdevc module:flutter_web|lib/src/physics/clamped_simulation.ddc.js

**Comment by mraleph** [comment] 2019-07-11 10:09
Duplicate of #37490

**Closed by mraleph** 2019-07-11 10:09 UTC
Labels: area-dev-compiler, type-bug
