### ISSUE TITLE
When performing floating-point calculations, precision may be lost在进行浮点数计算时精度会丢失

### ISSUE THREAD

**Issue by zhou26192619** [dart-lang/sdk#56317] opened 2024-07-25 02:12 UTC
Problem description：
When performing floating-point calculations, precision may be lost. like this:
![image](https://github.com/user-attachments/assets/9f7d46ef-e513-41b8-9eec-07765bd55616)
一般的解决方案是集成第三方，但是第三方都是千奇百怪的。

The general solution is to integrate a third party, but third parties are all strange and varied.
我想的是解决方案能不能直接集成到基础类double上，这样也用户可以无感知。
What I am thinking about is whether the solution can be directly integrated into the base class double, so that users can be unaware.
好比这样
like this:
```
class Double {
  num value = 0;

  int offset = 1;

  Double(this.value) {
    offset = decimalDigit(value);
  }

  @override
  String toString() {
    return value.toString();
  }
}

extension DoubleCalculate on Double {
  Double operator -(dynamic other) {
    Double behind = typeConvert(other);
    int maxOffset = max(offset, behind.offset);
    double intResult = ((value * pow(10, maxOffset)).round() - (behind.value * pow(10, maxOffset)).round()) / pow(10, maxOffset);
    debugPrint('${value} - $behind = $intResult  ${maxOffset}');
    return Double(intResult);
  }

  Double operator +(dynamic other) {
    Double behind = typeConvert(other);
    int maxOffset = max(offset, behind.offset);
    double intResult = ((value * pow(10, maxOffset)).round() + (behind.value * pow(10, maxOffset)).round()) / pow(10, maxOffset);
    debugPrint('${value} + $behind = $intResult  ${maxOffset}');
    return Double(intResult);
  }

  Double operator *(dynamic other) {
    Double behind = typeConvert(other);
    double intResult = ((value * pow(10, offset)).round() * (behind.value * pow(10, behind.offset)).round()) / pow(10, offset + behind.offset);
    debugPrint('${value} * $behind = $intResult  ${offset + behind.offset}');
    return Double(intResult);
  }

  Double operator /(dynamic other) {
    Double behind = typeConvert(other);
    double intResult = ((value * pow(10, offset)).round() / (behind.value * pow(10, behind.offset)).round()) / pow(10, offset - behind.offset);
    debugPrint('${value} / $behind = $intResult  ${offset - behind.offset}');
    return Double(intResult);
  }
}

///类型转换
Double typeConvert(dynamic other) {
  if (other is num) {
    return Double(other);
  } else if (other is Double) {
    return other;
  } else {
    throw Exception('计算类型不支持！');
  }
}

/// 计算小数的位数
int decimalDigit(num n) {
  String nStr = n.toString();
  if (!nStr.contains('.')) {
    return 0;
  }
  List<String> list = nStr.split('.');
  String list1 = list[1];
  if (!list1.contains('e')) {
    return list1.length;
  }
  List<String> es = list1.split('e');
  return max(es[0].length - int.parse(es[1]), 0);
}

```
![image](https://github.com/user-attachments/assets/3ee768cd-11f8-4220-a4b1-957dd15095d1)
把Double的解决方法直接集成到double。
Integrate the solution for Double directly into double.
不知道可行性怎么样？
I don't know how feasible it is?

**Comment by julemand101** [comment] 2024-07-25 07:56
This is how the `double` type works in most programming languages. See this issue which I think this is a duplicate of: https://github.com/dart-lang/sdk/issues/47081

**Comment by zhou26192619** [comment] 2024-07-25 08:12
> This is how the `double` type works in most programming languages. See this issue which I think this is a duplicate of: #47081
> 
> If you need to deal with double numbers and do it with precision, you can use a package like https://pub.dev/packages/decimal but it does come with the cost of some performance.
我知道其他语言也有这个问题。使用第三方库比如decimal，可以解决精度问题。但是第三方使用很麻烦而且没有标准，各不相同。所以是不是可以直接在double类上集成处理方法；或者像java一样把double自动装箱成Double类型，这样用户使用的时候是无感知的，也不用做额外的处理。
I know that this precision issue also exists in other programming languages. Using third-party libraries like decimal can resolve the precision problem. However, the use of third-party libraries is cumbersome and lacks standardization, varying widely from one to another. So, is it possible to directly integrate processing methods on the double class itself; or automatically box double into Double type like in Java, so that users can be unaware of it during usage and don't need to do any additional processing?

**Comment by lrhn** [comment] 2024-07-25 10:43
> So, is it possible to directly integrate processing methods on the double class itself

No.

The behavior of doubles is what the CPU does. Doing anything else will require an extra overhead, which is something you should opt in to by using a different type. In this case, maybe use `int` for the numbers, multiplied by 100, and divide by 100 at the end.

If you want exact fixed-precision fractional decimal numbers, `double` is not the type for that. It can't even represent `0.01` precisely, which is one of the causes of this problem. (The exact value of the `double` literal `0.01` is 0.01000000000000000020816681711721685132943093776702880859375, so adding it multiple times gives something that differs from zero on the 18th decimal digit, making `1.1 + 3 * 0.01 != 1.13`)

**Comment by zhou26192619** [comment] 2024-07-26 01:54
> > So, is it possible to directly integrate processing methods on the double class itself
> 
> No.
> 
> The behavior of doubles is what the CPU does. Doing anything else will require an extra overhead, which is something you should opt in to by using a different type. In this case, maybe use `int` for the numbers, multiplied by 100, and divide by 100 at the end.
> 
> If you want exact fixed-precision fractional decimal numbers, `double` is not the type for that. It can't even represent `0.01` precisely, which is one of the causes of this problem. (The exact value of the `double` literal `0.01` is 0.01000000000000000020816681711721685132943093776702880859375, so adding it multiple times gives something that differs from zero on the 18th decimal digit, making `1.1 + 3 * 0.01 != 1.13`)

![image](https://github.com/user-attachments/assets/0ad60dbd-621e-4c97-bcc4-69b66ca57197)

所以我能想到的解决方案就像java自动装箱一样：
`Integer i=10;` 会被编译成 `Integer i = Integer.valueOf(10);`

dart在进行浮点数运算时，类似的，将`1.1 + 3 * 0.01 != 1.13 ` 编译成 `Double(Double(1.1) + 3 * Double(0.01) == Double(1.13)`。
这样会不会好点（因为底层比较难改动）。

So the solution I can think of is like JAVA auto boxing:
`Integer i=10;`  It will be compiled into ` Integer i=Integer. valueOf (10)`

When performing floating-point operations on dart, similarly, ` 1.1+3 * 0.01= Compile 1.13 into Double (Double (1.1)+3 * Double (0.01)==Double (1.13)).
Would this be better (because it's difficult to make changes at the Lower-layer).

**Comment by julemand101** [comment] 2024-07-26 04:12
@zhou26192619 
Just want to be sure that you do understand that the boxed `Double` in Java have the same issues as the non-boxed `double` type which have the same problem as Dart have here. Making it boxed does not solve any of this.

Java also have a custom type if you want to deal with arbitrary precision, called `BigDecimal`, which you don't get any auto-boxing for. You can argue that Jave have this as part of standard JDK but this is more a matter of where different programming languages draw the line for what should be in the SDK and what should come from external packages.

**Comment by zhou26192619** [comment] 2024-07-26 08:36
> @zhou26192619 Just want to be sure that you do understand that the boxed `Double` in Java have the same issues as the non-boxed `double` type which have the same problem as Dart have here. Making it boxed does not solve any of this.
> 
> Java also have a custom type if you want to deal with arbitrary precision, called `BigDecimal`, which you don't get any auto-boxing for. You can argue that Jave have this as part of standard JDK but this is more a matter of where different programming languages draw the line for what should be in the SDK and what should come from external packages.

我说明下我的目的：
当使用`decimal`这个库的时候，`0.1+0.2` 得写成 `Decimal.parse('0.2') + Decimal.parse('0.1')`，当公式比较长时，写起来相当麻烦，还必须是字符类型。其实上面我自定义的Double已经基本满足了要求，只是`Dart`只支持` + - * / `的重载，不支持 `==` 重载，所以比较的时候有点问题，只能再定义一个比较方法。如果能在sdk中实现这些就更好了。主要目的就是为了简化书写而已。

现成的例子的话，可以和Haskell类比：
![2 E7PFYKFPE POI0HRZBM@Q](https://github.com/user-attachments/assets/e23a392d-0c5f-4bc6-9d81-687b09dfb30b)
![R16GXO$L71F~IK5O0@%~ AA](https://github.com/user-attachments/assets/583d2437-f1b1-42e8-b211-38cc2129ce45)
Haskell中，当碰到有理数运算时，自动就转成了有理数，很方便。

当然每个语言有自己的特性，也不是一定行的。好了，其他也没什么事了。

Let me explain my purpose:
When using the 'decimal' library, `0.1+0.2` needs to be written as ` Decimal. parse ('0.2')+Decimal. parse ('0.1') `. When the formula is relatively long, it can be quite cumbersome to write and must be of character type. In fact, the Double I customized above basically meets the requirements, but Dart only supports overloading of `+- */` and does not support overloading of `==`. Therefore, there is a problem when comparing, and we can only define another comparison method. It would be even better if these could be implemented in the SDK. The main purpose is just to simplify writing.

If there are ready-made examples, they can be compared to Haskell:
![2 E7PFYKFPE POI0HRZBM@Q](https://github.com/user-attachments/assets/e23a392d-0c5f-4bc6-9d81-687b09dfb30b)
![R16GXO$L71F~IK5O0@%~ AA](https://github.com/user-attachments/assets/583d2437-f1b1-42e8-b211-38cc2129ce45)
In Haskell, when encountering rational number operations, it automatically converts to rational numbers, which is very convenient.

Of course, each language has its own characteristics and is not necessarily feasible. Alright, there's nothing else to worry about.

**Closed** 2024-07-26 08:42 UTC
Labels: closed-not-planned, area-core-library, library-core, type-enhancement
