### ISSUE TITLE
Dart analyzer crashes

### ISSUE THREAD

**Issue by Timmmm** [dart-lang/sdk#39448] opened 2019-11-19 14:52 UTC
- Dart SDK 2.7.0-dev.0.0
- Visual Studio Code 1.40.0
- Dart Code 3.6.0

I pasted some Typescript code in my Dart file. Obviously I don't expect DartAnalyzer to actually analyze this, but it shouldn't crash. It does:

```text
UnimplementedError: name is an instance of _OperatorName in endClassConstructor
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:716:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:594:16)
#3      Future._completeError (dart:async/future_impl.dart:530:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Unfortunately the code is quite long and not open source. Sorry :-/ Hopefully it is obvious what needs to be implemented.

**Comment by srawlins** [comment] 2019-11-20 18:32
Thanks for reporting this issue! This is likely a duplicate of https://github.com/dart-lang/sdk/issues/39338; please follow along there.

**Comment by srawlins** [comment] 2019-11-20 18:32
Duplicate of https://github.com/dart-lang/sdk/issues/39338

**Closed by srawlins** 2019-11-20 18:32 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
