### ISSUE TITLE
Bad type inference with generic function argument

### ISSUE THREAD

**Issue by cubuspl42** [dart-lang/sdk#36489] opened 2019-04-05 10:06 UTC
```
$ dart --version
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
```
`a.dart`:
```dart
List<T> list<T>(T a) => List()..add(a);

R map<T, R>(T a, R b(T a)) => b(a);

void main() {
  final x = map(1, list);
  if (x is List<dynamic>) print("List<dynamic>");
  if (x is List<int>) print("List<int>");
}
```
```
$ dart a.dart
List<dynamic>
```

Expected:
```
List<int>
```

**Comment by eernstg** [comment] 2019-04-05 10:20
This behavior arises because there is no mechanism in Dart type inference which allows information to flow from some arguments of a generic function invocation to another one. Cf. #25490.

We may get this (C# has some heuristics in this area, and they might be applicable, but we haven't explored the details), but currently you'll need to help the inference engine a bit more, for instance like this:

```dart
List<T> list<T>(T a) => List()..add(a);

R map<T, R>(T a, R b(T a)) => b(a);

void main() {
  final List<int> x = map(1, list);
  if (x is List<int>) print("List<int>"); // Prints.
}
```

**Comment by eernstg** [comment] 2019-04-05 10:21
Closing this as a duplicate of #25490.

**Comment by cubuspl42** [comment] 2019-04-05 10:24
Thank you, sorry for duplicating.

**Comment by eernstg** [comment] 2019-04-05 10:25
No problem, it's not always easy to spot duplication! ;-)

**Closed** 2019-04-05 11:04 UTC
Labels: closed-duplicate
