### ISSUE TITLE
Analyzer CLI ignores `.analysis_options` when analyzing dirs.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#26959] opened 2016-07-25 16:56 UTC
Running `dartanalyzer` on a directory should pickup a contained analysis options file (if present).  Currently it is ignored.

**Comment by devoncarew** [comment] 2017-04-10 15:28
closing, dupe of https://github.com/dart-lang/sdk/issues/26212

**Closed by devoncarew** 2017-04-10 15:28 UTC
Labels: analyzer-command, analyzer-ux, area-analyzer, P2 medium, Type: bug
