### ISSUE TITLE
Flaky failures on co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05 on Mac

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#39248] opened 2019-11-05 23:15 UTC
From time to time tests from `co19_2/LibTest/io/FileSystemCreateEvent` group fail on vm-kernel-mac-product-x64 bot:

```
/=========================================================================================================\
 | co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05 broke (Pass -> RuntimeError, expected Pass) |
 \=========================================================================================================/
 --- Command "vm" (took 825ms):
 DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart
 exit code:
 255
 stdout:
 unittest-suite-wait-for-done
 stderr:
 Unhandled exception:
 Expect.isFalse(true) fails.
 #0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
 #1      Expect.isFalse (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:48:5)
 #2      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart:33:16)
 #3      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:53:7)
 #4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
 #5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
 #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
 #7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
 #8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
 #9      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:776:16)
 #10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
 #11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
 #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
 #13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
 #14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
 #15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
 #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
 #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
 #18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
 #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
 --- Re-run this test:
 python tools/test.py -n dartk-mac-product-x64 co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05
```

[log1](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8897602881212935136/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0), [log2](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8898044571808941680/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0), [log3](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8898183719485764112/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0).

This failure is easy to reproduce on Mac (failure rate > 50%).
Could be related to https://github.com/dart-lang/sdk/issues/37342.

/cc @ZichangG

**Comment by alexmarkov** [comment] 2019-12-09 18:56
Still failing:
```
/=========================================================================================================\
 | co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05 broke (Pass -> RuntimeError, expected Pass) |
 \=========================================================================================================/
 --- Command "vm" (took 855ms):
 DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart
 exit code:
 255
 stdout:
 unittest-suite-wait-for-done
 stderr:
 Unhandled exception:
 Expect.isFalse(true) fails.
 #0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
 #1      Expect.isFalse (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:48:5)
 #2      _main.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart:33:16)
 #3      testFileSystemEvent (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:53:7)
 <asynchronous suspension>
 #4      _main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart:29:9)
 #5      inSandbox (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:24:22)
 #6      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05.dart:21:9)
 #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
 #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
 --- Re-run this test:
 python tools/test.py -n dartk-mac-release-x64 co19_2/LibTest/io/FileSystemCreateEvent/isDirectory_A01_t05
```
[Log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8894529021391424512/+/steps/test_results/0/logs/ignored_flaky_test_failure_logs/0).

**Comment by ZichangG** [comment] 2019-12-20 14:05
@alexmarkov 
Did you approve this flaky? I looked at the issue. This is not our VM issue.
So we need to either modify the test or skip this as flaky test. Wdyt?
I'm also not sure how to modify the test in co19_2.

**Comment by alexmarkov** [comment] 2019-12-20 18:03
@ZichangG we currently don't have an ability to "approve" flaky tests. Such tests don't turn bots red, but they are shown on a separate flakiness dashboard.

If you believe that the test is incorrect, you can file an issue in https://github.com/dart-lang/co19/issues.

See also https://github.com/dart-lang/co19/issues/186 and https://github.com/dart-lang/sdk/issues/37342.

**Comment by brianquinlan** [comment] 2023-10-17 00:11
I can't reproduce this and think that it was fixed by https://github.com/dart-lang/co19/issues/672

**Closed** 2023-10-17 00:11 UTC
Labels: area-library, library-io, gardening
