### ISSUE TITLE
IntelliJ dart analyzer failure

### ISSUE THREAD

**Issue by buhhy** [dart-lang/sdk#30549] opened 2017-08-25 18:41 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4694.70`
- `1.25.0-dev.9.0`
- `IU-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-83-generic unknown, screens 1920x1200, 2560x1600`

# Exception

Please append the contents of:
file:///tmp/report1.txt

```
Dart analysis server, SDK version 1.25.0-dev.9.0, server version 1.18.3, error: Analysis failed: .../examples/web/index.dart context: exception_20170824_192531_536
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/array.dart:128)
#1      _LibraryResynthesizer.createUnitResynthesizer (package:analyzer/src/summary/resynthesize.dart:1054)
#2      _LibraryResynthesizer.buildLibrary (package:analyzer/src/summary/resynthesize.dart:992)
#3      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:256)
#4      _HashVMBase

**Comment by bwilkerson** [comment] 2017-08-25 18:50
@scheglov Has this been fixed?

**Comment by scheglov** [comment] 2017-08-25 19:38
No, I was not able to reproduce it.

Could you please look into your `~/.dartServer/analysis-driver` folder for the file `exception_20170824_192531_536` and send it to scheglov@google.com (me). Please note that this file contains contents of all the files that transitively used by `web/index.dart`. But I guess it is OK, because we work for the same company ;-)

**Comment by natebosch** [comment] 2018-09-01 01:07
Closing since this hasn't had an update in a while and we can't reproduce.

**Closed by natebosch** 2018-09-01 01:07 UTC
Labels: area-analyzer, needs-info, p1-high, type-bug
