### ISSUE TITLE
Pub Serve stopped working after upgrade to dart 1.22.0-dev.6.0

### ISSUE THREAD

**Issue by kzhdev** [dart-lang/sdk#28346] opened 2017-01-11 20:18 UTC
After update dart to 1.22.0-dev.6.0, pub serve stopped working. Here is the output:

```
/usr/local/opt/dart/libexec/bin/pub serve web --port=52503
Loading source assets...
Loading adl_client/transformers/js_transformer, dart_to_js_script_rewriter and toolkit transformers...
Pub is a package manager for Dart.

Usage: pub <command> [arguments]

Global options:
-h, --help             Print this usage information.
    --version          Print pub version.
    --[no-]trace       Print debugging information when an error occurs.
    --verbosity        Control output verbosity.

          [all]        Show all output including internal tracing messages.
          [error]      Show only errors.
          [io]         Also show IO operations.
          [normal]     Show errors, warnings, and user messages.
          [solver]     Show steps during version resolution.
          [warning]    Show only errors and warnings.

-v, --verbose          Shortcut for "--verbosity=all".

Available commands:
  build       Apply transformers to build a package.
  cache       Work with the system cache.
  deps        Print package dependencies.
  downgrade   Downgrade the current package's dependencies to oldest versions.
  get         Get the current package's dependencies.
  global      Work with global packages.
  help        Display help information for pub.
  publish     Publish the current package to pub.dartlang.org.
  run         Run an executable from a package.
  serve       Run a local web development server.
  upgrade     Upgrade the current package's dependencies to latest versions.
  uploader    Manage uploaders for a package on pub.dartlang.org.
  version     Print pub version.

Run "pub help <command>" for more information about a command.
See http://dartlang.org/tools/pub for detailed documentation.
```

Pub Serve terminated

**Comment by kzhdev** [comment] 2017-01-11 20:22
With --verbose --trace:

kzhao@MacBook-Pro-K:client (master) $ pub serve --verbose --trace
FINE: Pub 1.22.0-dev.6.0
FINE: Loading asset environment...
FINE: Initializing barback...
FINE: Serving packages on localhost:0.
MSG : Loading source assets...
FINE: Providing sources for canvas_lib|lib.
FINE: Providing sources for toolkit|lib.
FINE: Providing sources for adl_lib|lib.
FINE: Providing sources for adl_client|lib.
FINE: Loading source assets finished (0.810s).
FINE: Provided sources.
FINE: Loading transformers...
FINE: Transformer dependencies:
    | adl_client/transformers/js_transformer: -
    | adl_client/transformers/copy_transformer: adl_client/transformers/js_transformer, adl_lib and toolkit
    | adl_client/transformers/grunt_build_transformer: adl_client/transformers/js_transformer, adl_client/transformers/copy_transformer, adl_lib and toolkit
    | adl_client/transformers/vendor_js_build_transformer: adl_client/transformers/js_transformer, adl_client/transformers/copy_transformer, adl_client/transformers/grunt_build_transformer, adl_lib and toolkit
    | adl_client/transformers/local_setting_transformer: adl_client/transformers/js_transformer, adl_client/transformers/copy_transformer, adl_client/transformers/grunt_build_transformer, adl_client/transformers/vendor_js_build_transformer, adl_lib and toolkit
    | adl_client/transformers/deploy_build_transformer: adl_client/transformers/js_transformer, adl_client/transformers/copy_transformer, adl_client/transformers/grunt_build_transformer, adl_client/transformers/vendor_js_build_transformer, adl_client/transformers/local_setting_transformer, adl_lib and toolkit
    | dart_to_js_script_rewriter: -
    | adl_lib: toolkit
    | toolkit: -
FINE: Not caching mutable transformers.
MSG : Loading adl_client/transformers/js_transformer, dart_to_js_script_rewriter and toolkit transformers...
FINE: Loading transformers from [adl_client/transformers/js_transformer, dart_to_js_script_rewriter, toolkit]
IO  : Created temp directory /var/folders/5t/fp5w6px551q3c_49n06h2d8cq9trqh/T/pub_tDUn2q
IO  : Writing 315 characters to text file /private/var/folders/5t/fp5w6px551q3c_49n06h2d8cq9trqh/T/pub_tDUn2q/runInIsolate.dart.
IO  : Deleting directory /private/var/folders/5t/fp5w6px551q3c_49n06h2d8cq9trqh/T/pub_tDUn2q.
Pub is a package manager for Dart.

Usage: pub <command> [arguments]

Global options:
-h, --help             Print this usage information.
    --version          Print pub version.
    --[no-]trace       Print debugging information when an error occurs.
    --verbosity        Control output verbosity.

          [all]        Show all output including internal tracing messages.
          [error]      Show only errors.
          [io]         Also show IO operations.
          [normal]     Show errors, warnings, and user messages.
          [solver]     Show steps during version resolution.
          [warning]    Show only errors and warnings.

-v, --verbose          Shortcut for "--verbosity=all".

Available commands:
  build       Apply transformers to build a package.
  cache       Work with the system cache.
  deps        Print package dependencies.
  downgrade   Downgrade the current package's dependencies to oldest versions.
  get         Get the current package's dependencies.
  global      Work with global packages.
  help        Display help information for pub.
  publish     Publish the current package to pub.dartlang.org.
  run         Run an executable from a package.
  serve       Run a local web development server.
  upgrade     Upgrade the current package's dependencies to latest versions.
  uploader    Manage uploaders for a package on pub.dartlang.org.
  version     Print pub version.

Run "pub help <command>" for more information about a command.
See http://dartlang.org/tools/pub for detailed documentation.

**Comment by munificent** [comment] 2017-01-11 21:09
Duplicate of: https://github.com/dart-lang/pub/issues/1497

**Comment by munificent** [comment] 2017-01-12 00:40
Resurrecting this one instead of the pub one (https://github.com/dart-lang/pub/issues/1497) since the issue isn't in pub.

**Comment by munificent** [comment] 2017-01-12 00:55
I'm quite confident this is not a bug in pub. However, it is a severe bug that manifests in pub. I believe any user of `pub build` or `pub serve` on a package that has any transformers is currently completely broken.

Here's what I've been able to figure out:

* By doing a git bisect, the commit that breaks pub is commit 632b74404626ff81fe8678f139b5b3b78a59dc51, which makes GN the default.
* The issue only manifests when running pub from a snapshot. Running from source is fine.
* If you run `pub build` or `pub serve`, pub eventually gets to:

    ```dart
    // dart/sdk/third_party/pkg/pub/lib/src/barback/transformer_isolate.dart:78
    await dart.runInIsolate(code.toString(), port.sendPort,
        packageRoot: transformerServer.url.resolve('packages'),
        snapshot: snapshot);
    return new TransformerIsolate._(
        await port.first, environment.mode, idsToUrls);
    ```

    The first statement succeeds and, I presume queues up a new isolate to be spawned at some point. That isolate is spawned using `Isolate.spawnUri()` pointing to a synthesized file in the user's temp directory. This code has been around for a while and hasn't had any problems.

    When this code reaches the `await port.first` it stops executing the main isolate and goes to load the new one. However, instead of loading the code from the temp file, **it re-executes pub's own entrypoint bin/pub.dart.**

    This is why you see the usage text. It thinks you ran pub *again*, with no arguments. Then, after pub prints the usage text, it explicitly exits the process which is why we don't get back to the main isolate.

As far as I can tell, we're passing a legitimate URI to `Isolate.spawnUri()`, so I have no idea why it's reloading pub's entrypoint for the isolate instead.

At this point, I think it's out of my hands. If you'd like to repro:

1. Clone this repo: https://github.com/munificent/transformer_test
2. Run `pub build` or `pub serve` from its root directory, using pub from the bleeding edge repo. If you want to skip the pub shell script and run the snapshot directly, it's:

```sh
dart <repo>/<build>/<config>/dart-sdk/bin/snapshots/pub.dart.snapshot (build|serve)
```

**Comment by zanderso** [comment] 2017-01-12 19:22
The change to GN switched pub to use app snapshots. @rmacnak-google @a-siva

**Closed** 2017-01-12 21:07 UTC
Labels: area-vm, P0 critical, pub-serve, S0 critical

**Comment by munificent** [comment] 2017-01-12 21:25
Confirmed this is working on my Mac now. Thanks for the quick turnaround!
