### ISSUE TITLE
Allow user-defined debug names when spawning isolates

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#19258] opened 2014-06-05 22:02 UTC
Isolate.spawn/spawnUri should take a debug name as an optional parameter to make it easier to distinguish isolates when debugging or using the Observatory.

**Comment by natebosch** [comment] 2018-09-04 22:03
Closing as a duplicate of #34059 since it has more discussion.

**Closed by natebosch** 2018-09-04 22:03 UTC
Labels: area-library, core-l, library-isolate, type-enhancement
