### ISSUE TITLE
CFE missing compile time errors on invalid bounds in mixins

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#33071] opened 2018-05-08 11:50 UTC
Tests:
`language_2/mixin_invalid_bound_test` and `language_2/mixin_invalid_bound2_test`

**Comment by stefantsov** [comment] 2018-06-01 13:27
I think this issue is an instance of https://github.com/dart-lang/sdk/issues/33308.  It affects not only mixins, but all other class kinds as well.

**Comment by askeksa-google** [comment] 2018-08-14 08:47
Closing as duplicate of https://github.com/dart-lang/sdk/issues/33308

**Closed by askeksa-google** 2018-08-14 08:47 UTC
Labels: area-front-end, front-end-missing-error
