### ISSUE TITLE
Bug                                                                                 

### ISSUE THREAD

**Issue by davidcorneto** [dart-lang/sdk#40264] opened 2020-01-22 02:43 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.8.0-edge.c547f5d933e5a10e18b1b26b54a6249e88fa0f1c`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.c547f5d933e5a10e18b1b26b54a6249e88fa0f1c, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:707:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file:///private/var/folders/ns/z4kqltqd1h7c18jk6f3hzv_r0000gn/T/report.txt.

**Comment by srawlins** [comment] 2020-06-12 22:43
Thanks for reporting this issue! This was previously reported in #40223. Please follow along there.

**Comment by srawlins** [comment] 2020-06-12 22:43
Duplicate of #40223

**Closed by srawlins** 2020-06-12 22:43 UTC
Labels: analyzer-crash-report, area-analyzer
