### ISSUE TITLE
Use operator methods in JS interop

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#46359] opened 2021-06-15 02:36 UTC
I have built a JS bindings package that read WebIDLs and MDN to generate JS wrappers with package:js: https://pub.dev/packages/js_bindings

When I try to use the package, it throws this error while compiling:   
```JS interop classes do not support [] and []= operator methods.```

Will you support operator methods in JS?  
How can I work this around?

This tracker is for issues related to:
* dart2js
Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"

**Comment by sigmundch** [comment] 2021-06-17 16:17
Thanks @jodinathan for filing this issue. I'll mark this as a duplicate of the general bug #35084 where we are tracking the general effort of revamping JS-interop using a static approach.

Many of our historical limitations (like renaming members, using operators, processing inputs and outputs) are an unfortuante result of our current implementation strategy. As I hinted in https://github.com/dart-lang/sdk/issues/46248, we do allow to use index operators with static extension methods. For example:

```dart
@JS()
class A { external A(); }
extension AExtension on A {
   String operator[](String y) => js_util.getProperty(this, y);
}
```

**Closed by sigmundch** 2021-06-17 16:17 UTC
Labels: area-web, web-js-interop
