### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by gmjgh** [dart-lang/sdk#42257] opened 2020-06-10 09:01 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6308749`
- `2.9.0-8.2.beta`
- `AI-192.7142.36.36.6308749, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.9.0-8.2.beta, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'typeArguments' was called on null.
Receiver: null
Tried calling: typeArguments
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ErrorVerifier._checkForListElementTypeNotAssignable (package:analyzer/src/generated/error_verifier.dart:3194:41)
#2      ErrorVerifier.visitListLiteral (package:analyzer/src/generated/error_verifier.dart:862:5)
#3      ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6720:49)
#4      BinaryExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:972:20)
#5      RecursiveAstVisitor.visitBinaryExpression (package:analyzer/dart/ast/visitor.dart:659:10)
#6      ErrorVerifier.visitBinaryExpression (package:analyzer/src/generated/error_verifier.dart:362:11)
#7      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#8      BinaryExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:971:19)
#9      RecursiveAstVisitor.visitBinaryExpression (package:analyzer/dart/ast/visitor.dart:659:10)
#10     ErrorVerifier.visitBinaryExpression (package:analyzer/src/generated/error_verifier.dart:362:11)
#11     BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:967:49)
#12     AssignmentExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:729:20)
#13     RecursiveAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:647:10)
#14     ErrorVerifier.visitAssignmentExpression (package:analyzer/src/generated/error_verifier.dart:324:11)
#15     AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:725:49)
#16     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3708:18)
#17     RecursiveAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:833:10)
#18     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3704:49)
#19     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#20     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1085:17)
#21     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#22     ErrorVerifier.visitBlock (package:analyzer/src/generated/error_verifier.dart:370:13)
#23     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1081:49)
#24     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1040:13)
#25     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1036:49)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7004:12)
#28     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#29     ErrorVerifier.visitMethodDeclaration.<anonymous closure> (package:analyzer/src/generated/error_verifier.dart:893:13)
#30     ErrorVerifier._withEnclosingExecutable (package:analyzer/src/generated/error_verifier.dart:5482:16)
#31     ErrorVerifier.visitMethodDeclaration (package:analyzer/src/generated/error_verifier.dart:869:5)
#32     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6995:49)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#34     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1563:13)
#35     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#36     ErrorVerifier.visitClassDeclaration (package:analyzer/src/generated/error_verifier.dart:429:13)
#37     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1533:49)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7588:20)
#39     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2134:21)
#40     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#41     ErrorVerifier.visitCompilationUnit (package:analyzer/src/generated/error_verifier.dart:468:11)
#42     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2127:49)
#43     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:391:10)
#44     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:160:9)
#45     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#46     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:159:13)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#48     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:158:34)
#49     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:116:14)
#50     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#51     Libra...
```

For additional log information, please append the contents of
file:///private/var/folders/59/hp8vjc8955333pzs6_swrz5c0000gn/T/report.txt.

**Comment by srawlins** [comment] 2020-06-12 22:36
Thank you for opening this issue! This was previously found by fuzz-testing. Please follow along at https://github.com/dart-lang/sdk/issues/38043.

**Comment by srawlins** [comment] 2020-06-12 22:36
Duplicate of https://github.com/dart-lang/sdk/issues/38043

**Closed by srawlins** 2020-06-12 22:36 UTC
Labels: analyzer-crash-report, area-analyzer
