### ISSUE TITLE
RangeError: Value not in range: 1

### ISSUE THREAD

**Issue by ManojMM026** [dart-lang/sdk#38000] opened 2019-08-26 13:21 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:389:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1370:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4239:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3715:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#23     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3441:13)
#24     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3373:13)
#25     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4315:16)
#26     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4274:14)
#27     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#28     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#29     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#30     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#31     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#32     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#33     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#34     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#35     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#36     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4005:21)
#37     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#38     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#39     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#40     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3715:14)
#41     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#42     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#43     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3259:15)
#44     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3122:15)
#45     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2898:15)
#46     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1783:13)
#47     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1743:14)
#48     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:570:14)
#49     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:466:14)
#50     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#51     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:202:32)
#52     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:197:12)
#53     _File._parse (package:analyzer/src/services/available_declarations.dart:...
```

For additional log information, please append the contents of
file:///private/var/folders/pg/d7s6xc2s321gg65qxmlzbjj40000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-08-29 05:37
Duplicate of https://github.com/dart-lang/sdk/issues/37114

Thanks for reporting this issue! It's been previously reported at #37114, so please follow along there.

**Closed by srawlins** 2019-08-29 05:37 UTC
Labels: area-analyzer
