### ISSUE TITLE
Debugger stops at `sync*` methods rather than at breakpoints

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#46802] opened 2021-08-04 00:45 UTC
I rebuilt my SDK earlier today and now I'm trying to debug an issue in IntelliJ. If I add a breakpoint to `pkg/analyzer_plugin/lib/src/utilities/change_builder/change_builder_dart.dart` it doesn't matter where I put the breakpoint, it always pauses on line [1640](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer_plugin/lib/src/utilities/change_builder/change_builder_dart.dart#L1640) rather than on the line containing the breakpoint. That line is the definition of a `sync*` method.

@srawlins wrote in a chat:
> I actually had an almost identical issue yesterday:
>
> I was putting breakpoints in `analyzer/lib/src/dart/element/element.dart` and as long as I had one or more active breakpoints in that file, it would break at line 3955, also the first line of a sync* function.

There appears to be a bug in the debugger.

**Comment by a-siva** [comment] 2021-08-04 15:35
//cc @bkonyi

**Comment by scheglov** [comment] 2021-08-05 13:13
I think I already saw something like this a couple of years ago.
Not sure if it was solved and re-appeared, or I just worked around it.

**Comment by srawlins** [comment] 2021-08-22 05:14
Perhaps a duplicate of https://github.com/dart-lang/sdk/issues/45309

**Comment by a-siva** [comment] 2021-08-23 15:29
Marked as duplicate of #45309

**Closed by a-siva** 2021-08-23 15:29 UTC
Labels: area-vm, closed-duplicate, vm-debugger
