### ISSUE TITLE
FFI benchmark seems to have flaky? crash on ia32

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#37669] opened 2019-07-30 14:03 UTC
From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8906516951083433760/+/steps/try_linux-ia32_benchmarking/0/stdout):
```
# Command: out/ReleaseIA32/dart benchmarks/FfiCall/dart/FfiCall.dart
FfiCall.Uint8x01(RunTime): 280.2234519473242 us.
FfiCall.Uint16x01(RunTime): 281.7319340752219 us.
FfiCall.Uint32x01(RunTime): 275.43527953731757 us.
FfiCall.Uint64x01(RunTime): 291.05675203725264 us.
FfiCall.Int8x01(RunTime): 287.0841108080953 us.
FfiCall.Int16x01(RunTime): 280.043265191823 us.
FfiCall.Int32x01(RunTime): 275.9369568216306 us.
FfiCall.Int32x02(RunTime): 302.5031760435572 us.
FfiCall.Int32x04(RunTime): 337.48911759743544 us.
FfiCall.Int32x10(RunTime): 447.38850369044957 us.
FfiCall.Int32x20(RunTime): 640.06368 us.
FfiCall.Int64x01(RunTime): 295.7644536448322 us.
FfiCall.Int64x02(RunTime): 317.1525289361027 us.
FfiCall.Int64x04(RunTime): 372.1631931522144 us.
FfiCall.Int64x10(RunTime): 521.0567856212556 us.

===== CRASH =====
si_signo=Segmentation fault(11), si_code=2, si_addr=0xf5ca141f
version=2.5.0-edge.d6e9e15cf1ba8a2a87d7fda00faa1704285c76c3 (Tue Jul 30 09:13:37 2019 +0000) on "linux_ia32"
thread=26488, isolate=main(0x2ef8700)
  pc 0xf5ca141f fp 0xf7a3ec04 Unknown symbol
  pc 0xf5ca13f8 fp 0xf7a3ecb4 Unknown symbol
  pc 0xf5ca1796 fp 0xf7a3ed20 Unknown symbol
  pc 0xf5ca18e5 fp 0xf7a3ed38 Unknown symbol
  pc 0xf5c8c67a fp 0xf7a3ed50 Unknown symbol
  pc 0xf5c8c505 fp 0xf7a3ed6c Unknown symbol
  pc 0xf5c8ecc0 fp 0xf7a3ed8c Unknown symbol
  pc 0xf6fe73d4 fp 0xf7a3eda8 Unknown symbol
  pc 0xf6fe7147 fp 0xf7a3edc4 Unknown symbol
  pc 0xf6fe69ae fp 0xf7a3ede0 Unknown symbol
  pc 0xf6fe66cc fp 0xf7a3ee04 Unknown symbol
  pc 0xf6fe64fa fp 0xf7a3ee20 Unknown symbol
  pc 0xf6fe563b fp 0xf7a3ee38 Unknown symbol
  pc 0xf6fe5535 fp 0xf7a3ee4c Unknown symbol
  pc 0xf6fe49ed fp 0xf7a3ee68 Unknown symbol
  pc 0xf6fc85b8 fp 0xf7a3ee80 Unknown symbol
  pc 0xf6fe473b fp 0xf7a3ee98 Unknown symbol
  pc 0xf7a40c4d fp 0xf7a3eec4 Unknown symbol
  pc 0x0190c487 fp 0xf7a3ef38 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned int)
  pc 0x0190c0b4 fp 0xf7a3ef78 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&)
  pc 0x0190f1ba fp 0xf7a3efb8 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x01942f73 fp 0xf7a3f0e8 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)
  pc 0x0196ff35 fp 0xf7a3f138 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x019707a1 fp 0xf7a3f198 dart::MessageHandler::TaskCallback()
  pc 0x01970ef7 fp 0xf7a3f1b8 out/ReleaseIA32/dart+0x1570ef7
  pc 0x01a8ad81 fp 0xf7a3f1f8 dart::ThreadPool::Worker::Loop()
  pc 0x01a8ac27 fp 0xf7a3f228 dart::ThreadPool::Worker::Main(unsigned int)
  pc 0x019fd6b4 fp 0xf7a3f2e8 out/ReleaseIA32/dart+0x15fd6b4
  pc 0xf7f99295 fp 0xf7a3f3a8 /lib/i386-linux-gnu/libpthread.so.0+0x6295
-- End of DumpStackTrace
```

@sjindel-google Could you take a look?

**Comment by sjindel-google** [comment] 2019-08-21 15:30
I can't reproduce this issue, but it's very likely caused by https://github.com/dart-lang/sdk/issues/37629, since it showed up on IA32, where write-protection is enabled by default but dual-mapping is not supported.

I'm going to close the issue optimistically, since we can't easily query Golem to find out whether the flakes have stopped entirely. It hasn't failed in the last 6 hours (> 500 runs).

**Closed by sjindel-google** 2019-08-21 15:30 UTC
Labels: area-vm, crash, library-ffi
