### ISSUE TITLE
代码不提示

### ISSUE THREAD

**Issue by lijunen2009** [dart-lang/sdk#36364] opened 2019-03-28 01:24 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-183.6156.11`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-183.6156.11, JRE 1.8.0_152-release-1343-b28x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14, screens 1920x1080`

# Exception

Please append the contents of:
file:///private/var/folders/9q/hsl3yn2s6fvbcvxx62jgb86w0000gn/T/report.txt

```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: /Users/lijunen/Code/fitness_app/lib/views/appraise.dart
Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)

**Comment by devoncarew** [comment] 2019-04-30 15:33
dupe of https://github.com/dart-lang/sdk/issues/36767

**Closed by devoncarew** 2019-04-30 15:33 UTC
Labels: area-analyzer, type-bug
