### ISSUE TITLE
Error generating JsonSerializable

### ISSUE THREAD

**Issue by manymore** [dart-lang/sdk#36061] opened 2019-02-28 07:49 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-33-generic unknown, screens 1920x1080, 1920x1080`

## Exception

```
Dart analysis server, SDK version 2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b, server version 1.21.1, error: Analysis failed: /data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart context: exception_20190228_084412_994
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1461:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#4      ExecutableElementImpl.returnType (package:analyzer/src/dart/element/element.dart:3806:64)
#5      _FunctionTypeImplLazy.baseReturnType (package:analyzer/src/dart/element/type.dart:3162:57)
#6      _FunctionTypeImplLazy.returnType (package:analyzer/src/dart/element/type.dart:3250:36)
#7      MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:585:42)
#8      MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:389:16)
#9      MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:70:7)
#10     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:516:31)
#11     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871:49)
#12     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:5275:10)
#13     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7871:49)
#14     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4059:18)
#15     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:5313:10)
#16     UnifyingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:3070:65)
#17     ResolverVisitor.visitExpressionFunctionBody (package:analyzer/src/generated/resolver.dart:4867:13)
#18     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:4055:15)
#19     ScopedVisitor.visitConstructorDeclarationInScope (package:analyzer/src/generated/resolver.dart:6350:16)
#20     ResolverVisitor.visitConstructorDeclarationInScope (package:analyzer/src/generated/resolver.dart:4746:11)
#21     ScopedVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:6343:7)
#22     ResolverVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:4734:13)
#23     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2950:15)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8366:20)
#25     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:6290:18)
#26     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:6268:11)
#27     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:4605:13)
#28     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#29     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:4666:25)
#30     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#31     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:623:10)
#32     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#33     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#34     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#35     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#36     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#37     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#38     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#39     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#40     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#41     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#42     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#43     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#44     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#45     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#46     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#47     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#53     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#54     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#55     main (file:///b/rr/tmpPrOqy_/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#56     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#57     main (file:///b/rr/tmpPrOqy_/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#58     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by manymore** [comment] 2019-02-28 07:50
```
1551339787454 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/mainMessagesWidget.dart","errors":[]}}
1551339787458 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/komensChooseRecipientScreen.dart","errors":[{"severity":"INFO","typ
1551339787461 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/messagesBloc.dart","errors":[]}}
1551339787461 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/utils/komentsGetters.dart","errors":[]}}
1551339787465 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/messageTypePickerController.dart","errors":[{"severity":"INFO","typ
1551339787468 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/komensScreenBloc.dart","errors":[]}}
1551339787477 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/selectionType.dart","errors":[]}}
1551339787477 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/komensComposeMessageBloc.dart","errors":[{"severity":"INFO","type":
1551339787477 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/komens/komensComposeMessageScreen.dart","errors":[{"severity":"INFO","type
1551339787477 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/home/homeScreenBloc.dart","errors":[]}}
1551339787477 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/home/homeScreen.dart","errors":[]}}
1551339787477 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/screens/home/homeScreenDrawer.dart","errors":[]}}
1551339787562 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/test/widget_test.dart","errors":[]}}
1551339787565 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/test/utils/stringHelper.dart","errors":[]}}
1551339787566 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1551339789205 <= {"event":"analysis.implemented","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","classes":[],"members":[]}}
1551339833735 <= {"event":"analysis.flushResults","params":{"files":["/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.g.dart"]}}
1551339833735 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1551339833833 <= {"event":"analysis.errors","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","errors":[{"severity":"ERROR","type":"STATIC_TYPE_W
1551339833837 <= {"event":"analysis.highlights","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","regions":[{"type":"DIRECTIVE","offset":0,"leng
1551339833841 <= {"event":"analysis.navigation","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","regions":[{"offset":7,"length":46,"targets":[0
1551339833843 <= {"event":"analysis.closingLabels","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","labels":[]}}
1551339833845 <= {"event":"analysis.outline","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","kind":"LIBRARY","outline":{"element":{"kind":"COM
1551339833846 <= {"event":"analysis.overrides","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","overrides":[]}}
1551339833975 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1551339833975 <= {"event":"analysis.implemented","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","classes":[],"members":[]}}
1551339835094 => {"id":"7","method":"edit.getAssists","params":{"file":"/data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart","offset":759,"length":0},"clientRequestTi
1551339835186 <= {"id":"7","result":{"assists":[]}}
1551339852953 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1551339853003 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /data-ssd/AndroidStudioProjects/Quichesoft/bakalari/lib/model/pedagogicalMeasure.dart context: exception_
```

**Comment by stereotype441** [comment] 2019-03-01 23:01
Duplicate of #35551

**Closed by stereotype441** 2019-03-01 23:01 UTC
Labels: area-analyzer
