### ISSUE TITLE
checking a `getter` with `as` doesn't promote it to be not-nullable

### ISSUE THREAD

**Issue by asashour** [dart-lang/sdk#50913] opened 2023-01-05 23:08 UTC
```dart
class A {
  B? get getter => null;
}

class B extends C {}

class C {}

void f(A a) {
  var g = a.getter;
  if (g is C) {
    Object o = g!; // 🔥  why the null check is needed
  }
}

void main() {
  f(A());
}
```

This happens with both the analyzer and CFE, I assume it is related to the flow analysis.

Detected in https://github.com/dart-lang/linter/pull/2841/files/65437113aebc8b1035c1daead646f65b41ae32d0#r1062955363

**Comment by srawlins** [comment] 2023-01-05 23:15
CC @pq @stereotype441 

I think it is because `C` is not a subtype of `B?`. We only promote in `is` in subtype relationships.

I thought changing that line to `if ((g as C?) is C) {` might fix it but that doesn't promote either. I don't super understand that one because I thought the static type of `x as T` is always exactly `T`...

**Comment by lrhn** [comment] 2023-01-05 23:29
Correct, `g` is not promoted from `B?` to `C` because `C` is not a subtype of `B?` (so it wouldn't be *promoting*).
Trying `(g as C?) is C` doesn't help, because we are not testing the type of the value of a local variable, but of the expression `(g as C?)`, which is not the same.

I think it's working as intended.

If instead we'd typed `g` itself at `C?` from the beginning, `C? g = a.getter; if (g is C) ..`, then the promotion would work, because we are testing a local variable against a type which is a subtype of its current/declared type. 


There _is_ something here that we could do better, without moving too far outside of the current constraints.

The test `g is C` cannot promote from `B?` to `C`, but its success does imply that `g` is not `null`, so it could potentially promote `g` to `B`, which is a "type of interest" for `g`.

Generally, any `is` test against a non-nullable type should be able to work at least as well as an `!= null` test. If we can promote further, that's great, but we could at least use that one bit of information that we could also get from `!= null`.

**Closed** 2023-01-09 12:18 UTC
