### ISSUE TITLE
Analyzer Feedback: Failed to handle completion domain request

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28914] opened 2017-02-28 07:45 UTC
Report.txt: [report.txt](https://github.com/dart-lang/sdk/files/805994/report.txt)

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.3566.24`
- `1.22.1`
- `IU-171.3566.24, JRE 1.8.0_112-release-724-b5x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.11.6 unknown, screens 1920x1080, 1920x1080, 2560x1440`

## Exception

Please append the contents of:
file:///private/var/folders/m4/9rg16xhd2rlbln753n9zk1540000gn/T/report.txt

```
Dart analysis server, SDK version 1.22.1, server version 1.17.0, error: Failed to handle completion domain request
: {clientRequestTime: 1488267602191, params: {file: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLiteSite/samples/gh_test/web/main.dart, offset: 724}, method: completion.getSuggestions, id: 126}
AnalysisException: failed to resolve expression
Caused by Unexpected exception while performing ResolveUnitTask for source /Volumes/Daten/DevLocal/DevDart/MaterialDesignLiteSite/samples/gh_test/web/main.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1199)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1197)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find MaterialButton button in [MaterialButton button, MaterialAlertDialog alertDialog]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      LocalVariableElementImpl.identifier (package:analyzer/src/dart/element/element.dart:6110)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashMap.[] (dart:collection-patch/collection_patch.dart:87)
#6      TypeOverrideManager_TypeOverrideScope.getType (package:analyzer/src/generated/resolver.dart:8795)
#7      TypeOverrideManager.getType (package:analyzer/src/generated/resolver.dart:8683)
#8      StaticTypeAnalyzer.visitSimpleIdentifier (package:analyzer/src/generated/static_type_analyzer.dart:1315)
#9      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9397)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6376)
#11     UnifyingAstVisitor.visitSimpleIdentifier (package:analyzer/dart/ast/visitor.dart:3171)
#12     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9397)

**Comment by zoechi** [comment] 2017-02-28 07:53
similar to #28891, 28686, 26634, 27793

**Comment by rajmaniar** [comment] 2017-04-03 18:17
Any idea when we might see a fix for this? Thanks!

**Comment by bwilkerson** [comment] 2017-04-03 18:34
It's difficult to say because we have not been able to reproduce any of the many similar reports, but we've made some significant changes in 1.23, which we expect will reduce, if not eliminate, issues of this kind.

**Comment by natebosch** [comment] 2018-08-24 21:44
Unfortunately we won't be able to reproduce very old analyzer stack traces. Please file a new issue if you are seeing analysis server crashes with a recent SDK.

**Closed by natebosch** 2018-08-24 21:44 UTC
Labels: analyzer-server, area-analyzer, closed-obsolete, p2-medium, type-bug
