### ISSUE TITLE
Offer a list of potential overridable methods when typing @override 

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32677] opened 2018-03-27 06:51 UTC
Raised by @escamoteur at https://github.com/Dart-Code/Dart-Code/issues/736:

It would be very comfortable if when overriding a method in an extended class if DartCode could offer a list of potential candidates via intellisense and completes after selection of one of them the whole method.

**Comment by DanTup** [comment] 2018-03-27 06:54
One way of implementing this might be to prefix all override items with `@override` in their displayLabel so that if you're typing `@override` the completion list might look like this:

- @override myMethod1
- @override myMethod2

I think the displayName property was added specifically to remove `@override` but now I'm thinking that it's actually useful (as long as it's not on its own line).

If there are concerns over ordering or filtering, it could also be added to the end.

Actually, it also just occurred to me that I have metadata for this so I might be able to set the `filterText` for these options to include `@override` without changing the display. I'll test it out and report back!

**Comment by DanTup** [comment] 2018-03-27 07:02
I tried this:

```ts
if (suggestion.kind === "OVERRIDE") {
	completion.filterText = "@override " + completion.label;
}
```

However, it doesn't seem to work because given this code:

```dart
abstract class Person {
  getName() {}
}

class Danny extends Person {
    // Cursor here
}
```

`getName` doesn't appear in the completion list unless I've already typed `@override\n`. I think it probably should (@pq?), and that would allow the user to see a filtered list of all overridable methods as they start typing `@override`?

**Comment by bwilkerson** [comment] 2018-03-27 13:58
The current implementation in server appears to be missing a couple of triggers. If you type part of a method name (with nothing else; even something as short as `g`) you should get back suggestions for all of the inherited methods. This is because server explicitly looks for the AST structure that is produced in those cases to determine that this is what the user is likely trying to do.

But if there is nothing in the body of a class, or between two methods, then server will get a different AST structure and we haven't written the code to recognize it. The same is probably true of the AST we get when the user has typed `@override`. We just need to add the code to recognize the additional AST structures that should cause these suggestions to be produced.

I agree that it would be nice to have these suggestions displayed in more cases.

If you'd like to take a stab at adding this support I'd be happy to walk you through the process.

A less ambitious first step might be to add some failing tests for these cases (they would go in https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/test/services/completion/dart/override_contributor_test.dart).

Neither is required, of course. :-)

**Comment by DanTup** [comment] 2018-03-27 15:05
Sure, I can take a stab at adding some failing tests :-)

**Comment by DanTup** [comment] 2018-04-24 12:05
I've opened https://dart-review.googlesource.com/c/sdk/+/52442 to get things started.

**Comment by bwilkerson** [comment] 2018-08-31 20:47
@DanTup Did that CL (which has been merged) cover all the cases? If so, we can probably close this issue.

**Comment by DanTup** [comment] 2018-09-03 06:48
I believe it covers the case I spotted - though it was only failing tests, no implementation.

**Comment by bwilkerson** [comment] 2018-09-03 15:36
Ok. Then I'll close this issue and we can open a new one if we discover other work that needs to be done.

**Comment by DanTup** [comment] 2019-04-08 08:56
This came up again - I think there was a misunderstanding in this issue - my change above only added some tests that failed because of this issue, no implementation. I think there should be an open issue tracking adding an implementation/fixing the tests.

@bwilkerson if you can provide some pointers, I don't mind having a look at it (at least, when othe priorities are done!).

**Comment by bwilkerson** [comment] 2019-04-08 14:01
These kind of completions are added by the class in https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/completion/dart/override_contributor.dart.

**Comment by DanTup** [comment] 2019-05-13 10:59
I did some digging into this, but it seems non-trivial to fix. There override completion code expects to find an existing partial identifier (`targetId`) in order to provide completions, however there are situations where we don't have one:

```dart
class Foo {
  @override^
}
```

Here, the nodes we have are simple string tokens for `"@"`, `"override"` and `"}"`, and:

```dart
class Foo {
  @override^

  existingMethod() {
  }
}
```

Here, the override annotation is parsed as being on `existingMethod` but in this case we wanted to override an additional method.

I think to support these we might have to add some special cases (to cover the string tokens when the existing code doesn't parse into a valid annotation, and to cover the case where there's an override annotation attached to a method but completion was invoke at least one newline before the method name) but I don't know whether we'd end up doing the wrong thing in some cases (or that the code would be fragile).

WDYT?

**Comment by bwilkerson** [comment] 2019-05-13 14:48
I'm happy to have override completions suggested in more situations, as long as we're careful to not produce them in cases where it's clearly not appropriate. We want to make sure the list of suggestions contains the most likely completions and not just every possible completion. It's kind of a fine line to walk.

@jwren @lambdabaa have been thinking about this recently and might have thoughts.

**Comment by DanTup** [comment] 2019-09-17 11:44
I had a little dig around here again when https://github.com/Dart-Code/Dart-Code/issues/1955 came up, but solving that case is difficult because of the parsed AST.

I do think there are some improvements that can be made (some mentioned above) handling some more special cases, but I haven't had chance to properly try to implement or test them.

**Comment by miguelpruivo** [comment] 2019-12-03 00:22
This would be great, it seems to work inconsistently on VS Code.

**Comment by minhluuquang** [comment] 2021-06-03 09:06
any luck? This is the only reason for me using Intellij instead of Vscode

**Comment by DanTup** [comment] 2022-08-23 10:36
It appears this has been fixed at some point. Using the example from above, the super classes methods show up:

<img width="574" alt="Screenshot 2022-08-23 at 11 34 36" src="https://user-images.githubusercontent.com/1078012/186137197-eedaeb54-050d-4be0-a25d-dc9c7c3bbcf2.png">

**Comment by ookami-kb** [comment] 2022-08-23 11:30
@DanTup I believe this issue was about a different behavior. The one that you mention does really work for quite a long time, but it only works when you write the name of the method you want to override.

But there's no way to get the list of all the methods you can override, e.g. by typing `@overr...`:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/853356/186146656-c78f864e-2d63-4931-ba8c-c311bc6984c8.png">

So when you don't remember the name of the method, you have to actually go to the class implementation and check all the methods.

E.g., in Android Studio I can just press `⌘+O` and it will show me the list of all the overridable methods:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/853356/186147048-02fab0e2-887f-421c-a833-7d90af7480c7.png">

**Comment by DanTup** [comment] 2022-08-23 12:17
You're right, I was mislead by my example and failing test from above. It seems there have been a few issues:

- No way to see a list of overridable methods (this issue)
- Unable to complete the name of an overridable method to insert a stub at the end of a class (this was mentioned above as a possibly blocker for the first issue, and this has been fixed)
- Unable to complete an annotation like `@override` at the end of a class (I've re-opened https://github.com/Dart-Code/Dart-Code/issues/3182 about this, which I'd previously closed as a dupe of this one)

**Comment by Number-3434** [comment] 2024-01-14 19:38
# 2024 - Any Updates?

**Comment by Number-3434** [comment] 2024-01-14 19:38
# 2024 - Any Updates?

**Comment by bwilkerson** [comment] 2024-01-16 16:54
Not really, no.

We're in the process of re-working the implementation of code completion, and I'm hoping that we can address this issue more easily after that's done, but I don't have a firm date for either the completion of that work or the start of working on this issue.

**Comment by FMorschel** [comment] 2024-01-16 16:57
> We're in the process of re-working the implementation of code completion

Is there some project or something we can look at to keep ourselves updated with it?

**Comment by jacob314** [comment] 2024-02-12 21:21
Raising this to P2. I'd also be open to raising it to P1 given how much more time consuming this makes the toothbrush task of overriding a method.
I expect we should be able to hit the same quality bar as Java in IntelliJ where as soon as you have typed `@Ov` you get a completion list that only shows the method overrides that exist in the file (plus a couple other completions for annotations). I think that is principled as those are the only valid lines in Java that you can type that begin with `@Ov`. 
<img width="531" alt="Screenshot 2024-02-12 at 1 03 12 PM" src="https://github.com/dart-lang/sdk/assets/1226812/775a68fd-7760-43a6-b938-075d5bdee5d4">

To simplify the problem, if you happen to type `@Override ` in Java and then manually trigger completions you don't get any special handling for `Override` so we should not feel we need to handle that case either unless it is straightforward to handle. We just need to handle the case while you are have typed part of `@override` and are trying to quickly pick a method to override.
<img width="437" alt="Screenshot 2024-02-12 at 1 07 50 PM" src="https://github.com/dart-lang/sdk/assets/1226812/a36ac5a0-9dd1-410e-a6db-7447498c9156">

**Comment by scheglov** [comment] 2024-03-09 20:28
https://dart-review.googlesource.com/c/sdk/+/356640

**Comment by scheglov** [comment] 2024-03-11 23:10
<img width="640" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/a0f21400-2f97-4b40-9996-11aa4d1935a4">

**Comment by DanTup** [comment] 2024-03-11 23:21
I suspect in VS Code, these might get filtered out because they don't include the typed prefix in the `filterText`. We might need to prefix it with `@override` or something (I actually wonder if that would also be useful in the display text so it's much easier to identify them?).

I'll do some testing to see.

**Comment by DanTup** [comment] 2024-03-12 09:42
Yeah, in VS Code this is currently filtered out both on the server and the client. The server we filter it out here:

https://github.com/dart-lang/sdk/blob/c2e9ceeb6b97329f75a84bd41e40b540dd40e7a4/pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart#L519

And with that removed, VS Code removes it because of the `filterText`. We'll need to fix both for this to show up. The question is whether we should show "override" somewhere to the user. Here are some possibilities:

### 1. Don't show "override"

![Screenshot 2024-03-12 093524](https://github.com/dart-lang/sdk/assets/1078012/e1d355ab-d56d-4c18-8bb5-5b92760b745f)

My slight concern here is that it's unclear why some of these things are being suggested - it almost feels like a bug (especially given the highlighting of matches like "r" in "runtimeType").

### 2. Show "override" at start of completion

![Screenshot 2024-03-12 093357](https://github.com/dart-lang/sdk/assets/1078012/f1c5fcc5-43b0-497c-a771-66340d927f51)

This feels noisy, although I think it does make it the clearest what's happening.


### 3. Show "override" in details (when new labels are supported)

![Screenshot 2024-03-12 093740](https://github.com/dart-lang/sdk/assets/1078012/7f7abf44-8fb6-4fa9-89f5-03cc01276a12)

I thought this might be the best of both, but it still has the weird highlighting issue where characters from "override" are highlighted as a match, but most of the characters aren't visible ("runtimeType").


I'm interested in other peoples thoughts.

**Comment by Number-3434** [comment] 2024-03-12 11:46
I would prefer option 3, since we already use inline to show imports, so that would make sense.

Also, maybe the documentation could be shown in the override?

@scheglov Could you attach a video please?

I've had trouble with this because it selects the `super.` statement, instead of the `// TODO` statement, and I have to manually unselect the super and select and delete the TODO statement.

**Comment by DanTup** [comment] 2024-03-12 12:57
> But I have a more general question: how will these suggestions work with existing declaration members? Can we treat a newline between the cursor and an existing declaration as a sign to suggest an overridden member, but otherwise suggest the annotation itself?

I don't think whitespace is currently used as a signal anywhere, but I agree the results here might be awkward without it. Interesting in @scheglov and @bwilkerson's thoughts.

As an example:

```dart
class A {
  @overr^

  void foo() {}
}
```

Here, I'm probably trying to override a new method and want the new results shown above. However if there was no blank line maybe I'm more likely to be trying to add `@override` to `foo()` and if the other methods show up above the completion for `@override`, it could be quite annoying.

My screenshot for **2** above shows that VS Code doesn't put `override` at the top (all of the matches are `startsWith`s and none are exact matches). It's possible it's ranking them the same and we could improve this by ensuring `override` is always ranked highest on our side, but it might not be guaranteed to work.

**Comment by rrousselGit** [comment] 2024-03-12 13:21
What about option 4: show the suggested code in the tooltip on the right

Currently in the screenshots shared, the right panel only offers `(Object other) => bool`.
I assume it could be updated to show more info.

**Comment by rrousselGit** [comment] 2024-03-12 13:24
Another approach is to do something similar to what Copilot does: Show a preview in the code of what's about to be inserted.


<img width="501" alt="Screenshot 2024-03-12 at 14 23 27" src="https://github.com/dart-lang/sdk/assets/20165741/2ce7887e-db2a-4fb7-bd39-c1394c80fa0e">

Of course the suggestion would be different (nothing inside the body), and we'd have to keep showing the tooltips.
But users would visually see what happens when they accept a change. So they'd know if it adds an override or not.

**Comment by scheglov** [comment] 2024-03-12 14:05
I like option 2, with `override` at start.
It is more prominent, and closer to what code will will generate.

Yes, `@override` before an existing member will suggest overrides when there is an empty line between partial `@override` and the next member. See [this](https://github.com/dart-lang/sdk/commit/6ac3ba647bb8534fa94b79a33ba5d9535a7f9244#diff-6a316a34b93c3628729545b873bf2c6a16b8c0ded61ef15164d55145506dfaf4R801), and previous tests.

It looks that selecting `super.foo()` is not a bug, but a feature.
At least as decided when override was implemented initially.

**Comment by DanTup** [comment] 2024-03-12 14:12
@rrousselGit 

> What about option 4: show that this is an override in the tooltip on the right

Yeah, we can probably include that there (there are some interactions between what you see there and what you see in the list depending on client capabilities). It does suffer from the same problem as 1/3 though, that there is "odd" highlighting because you can't see the text being filtered on (`filterText`).

> Another approach is to do something similar to what Copilot does: Show a preview in the code of what's about to be inserted.

I think this might work if you're typing a specific method name, but if you're only typing `override` I think the experience of "selecting the right override" would be much worse (it's not very obvious how to cycle through suggestions). (It's also a bigger job to implement "inline completions".. something we should think about where it makes sense, but probably doesn't replace this).

@scheglov 

> I like option 2, with override at start.
> It is more prominent, and closer to what code will will generate.

Yeah, I feel like the three values we send to the client (the display label, the text to be inserted, and the text that is filtered on) should be as similar as possible. We do tweak them slightly (for example to shorten arguments to "..." and to keep arguments and parens out of the filter) but having `filterText` that isn't in the display label at all does feel a bit odd (the ranking is also done on `filterText`, so you could get a top match that isn't clear why it's even there).

> Yes, @override before an existing member will suggest overrides when there is an empty line between partial @override and the next member. See [this](https://github.com/dart-lang/sdk/commit/6ac3ba647bb8534fa94b79a33ba5d9535a7f9244#diff-6a316a34b93c3628729545b873bf2c6a16b8c0ded61ef15164d55145506dfaf4R801), and previous tests.

Oh, perfect - I didn't notice that :)


> It looks that selecting `super.foo()` is not a bug, but a feature.
> At least as decided when override was implemented initially.

It's probably hard to know if the super call is needed or not generally, but I wonder if we should avoid selecting it at least when `@mustCallSuper` is on the super method? 🤔

**Comment by Number-3434** [comment] 2024-03-12 14:39
In VSCode, you can already preview the suggest (like in copilot) using the `editor.suggest.preview` setting.

However, this doesn't appear to work yet with the overrides.

@rrousselGit To clarify, are you proposing that the extension should automatically show the inline preview, or only provide it if `editor.suggest.preview` is set to <samp><kbd>true</kbd></samp>

**Comment by DanTup** [comment] 2024-03-12 14:47
> In VSCode, you can already preview the suggest (like in copilot) using the `editor.suggest.preview` setting.

I think there are two different (but similar) things here:

The `editor.suggest.preview` setting seems to show a preview of the current (standard) completion item in the editor (which is probably useful here, but something we should leave for the user to enable because it's not per-completion item).

The screenshots Remi showed I think are showing _inline completion_, which appears in the editor like this but without the normal completion list visible. This is better suited for things like AI completion where the user is likely just choosing to either use it or not  (and not selecting from a bigger list).

> Maybe there could be a setting to enable the // TODO comment?

There's a related issue about this at https://github.com/dart-lang/sdk/issues/49331

**Comment by Number-3434** [comment] 2024-03-12 14:51
@DanTup Thanks!

By the way, maybe we could consider implementing the [type hierarchy provider](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareTypeHierarchy)?

**Comment by DanTup** [comment] 2024-03-12 14:54
@Number-3434 we already do :)

![image](https://github.com/dart-lang/sdk/assets/1078012/d8a483ce-c7c9-403c-a258-fa446597ff7f)

If it's not working for you, please file a new issue with details and CC me.

**Comment by Number-3434** [comment] 2024-03-12 14:57
@DanTup Oops, sorry, I didn't realize.

Do you need to manually show the "Go to Super Implementation" button, or is it already done by implementing the type hierarchy provider?

**Comment by DanTup** [comment] 2024-03-12 14:58
@Number-3434 sorry, I initially missed that part of your comment and edited in my response after submitting.

**Comment by bwilkerson** [comment] 2024-03-12 16:06
I also prefer the second option in which 'override' is included in the label. I think it has the least potential for confusing users.

**Comment by scheglov** [comment] 2024-03-12 21:43
Update for `displayText`.
https://dart-review.googlesource.com/c/sdk/+/357203

<img width="561" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/329be2e5-855b-4167-96d5-ad3ad1b9d235">

**Comment by DanTup** [comment] 2024-03-13 10:33
Because of the way we manipulate the display label in LSP (to split it into different kinds of labels so things like arguments are formatted slightly differently) this isn't showing up right:

![image](https://github.com/dart-lang/sdk/assets/1078012/f9eab834-e97b-4dbe-81bc-1ec667a5424c)

I'm taking a look (and will add more tests!).

**Comment by Number-3434** [comment] 2024-03-13 10:34
Okay thanks 🙏!

**Comment by Number-3434** [comment] 2024-03-13 10:38
@scheglov Btw, what extension are you using that changes the suggest widget icons?

**Comment by DanTup** [comment] 2024-03-13 10:58
Got a fix for LSP here: https://dart-review.googlesource.com/c/sdk/+/357320

Now looks like this:

![image](https://github.com/dart-lang/sdk/assets/1078012/7debcc27-1b74-44e0-9273-17892c603071)

@Number-3434 

> @scheglov Btw, what extension are you using that changes the suggest widget icons?

I believe that's IntelliJ, not VS Code.

**Closed** 2024-03-13 16:45 UTC
Labels: area-analyzer, analyzer-completion, P2, type-enhancement, contributions-welcome, analyzer-completion-correctness
