### ISSUE TITLE
NNBD: Dart does not throw a compile error for Future<T>(() => null) when T is non-nullable type

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#41340] opened 2020-04-04 18:17 UTC
Dart VM version: 2.8.0-dev.20.0 (dev) (Fri Apr 3 10:19:55 2020 +0200) on "windows_x64"

The following source code example throws a compile error for the line 4 and does not throw error for the line 5 when dart runs it:

``` dart
import "dart:async";

main() {
  Future<int>(() => "");
  Future<int>(() => null);
}
```
Seems like a compile error should be thrown for the line 5 too.

Sample output is:

```
$> dart --enable-experiment=non-nullable --null-safety test.dart
test.dart:4:21: Error: A value of type 'String' can't be assigned to a variable of type 'FutureOr<int>'.
 - 'FutureOr' is from 'dart:async'.
  Future<int>(() => "");
                               ^
$>
```

**Comment by a-siva** [comment] 2020-04-05 01:17
This seems like a duplicate of https://github.com/dart-lang/sdk/issues/41339

**Closed by a-siva** 2020-04-05 01:17 UTC
Labels: closed-duplicate

**Comment by iarkh** [comment] 2020-04-05 01:21
#41339 is against analyzer and this one is against runtime, I thought there should be different bus against the different categories

**Comment by a-siva** [comment] 2020-04-05 01:58
Got it, both issues are fixed in the unfork CL.

**Comment by crelier** [comment] 2020-04-29 23:51
The type error is correctly thrown, but asynchronously.
The co19 tests wrongly expect a synchronous throw.
See https://github.com/dart-lang/co19/issues/627
