### ISSUE TITLE
extend Resource API to return the resolved uri

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#24241] opened 2015-08-31 18:16 UTC
Right now the `Resource` uri returns the uri that was passing into the constructor (https://api.dartlang.org/1.12.0/dart-core/Resource-class.html). It would be nice if it could also return the uri that the resource resolves to. I.e. the ctor takes a `package:` uri, which likely resolves to a `file:` or an `http:` uri.

This information can be useful for tools that do need to know a bit more context about where the resources actually live. An example is an osgi / bundle loader for dart. It might want to try and locate the pubspec.yaml files for the installed packages. Right now only code and resources in `lib/` are available to tools.

**Comment by devoncarew** [comment] 2015-08-31 18:16
cc @sethladd

**Comment by sethladd** [comment] 2015-08-31 18:20
Thanks! Dupe of https://github.com/dart-lang/sdk/issues/23990

**Closed by sethladd** 2015-08-31 18:20 UTC
