### ISSUE TITLE
Dart2js dart:mirrors does not include abstract members in declarations

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#23627] opened 2015-06-12 08:15 UTC
import "dart:mirrors";
     
    abstract class A {
      int foo();
    }
    main() {
      print(reflectType(A).declarations);
    }
Prints `{Symbol("A"): MethodMirror on 'A'}` in dart2js and `{Symbol("foo"): MethodMirror on 'foo', Symbol("A"): MethodMirror on 'A'}` on the VM.
Not sure what is right, but it should be consistent at least.

**Comment by karlklose** [comment] 2015-06-12 08:40
Duplicate of #18721.

**Closed by karlklose** 2015-06-12 08:40 UTC
Labels: Area-Dart2JS, Library-Mirrors
