### ISSUE TITLE
unused_element reports on unused parameters whose presence is idiomatic

### ISSUE THREAD

**Issue by maxlapides** [dart-lang/sdk#49025] opened 2022-05-12 22:34 UTC
Assumptions:
- Flutter 3.0
- `user_super_parameters` lint rule is enabled
- `unused_element` analyzer rule is enabled

This code chunk produces an analyzer issue:

```dart
class _MyWidget extends StatelessWidget {
  const _MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

"A value for optional parameter 'key' isn't ever given. Try removing the unused parameter."

But, when the same widget is not private, there is no issue:

```dart
class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

I would like to keep the `super.key` on the private widgets, but I also want to keep the `unused_element` rule enabled. Is there any way to achieve this?

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/maxlapides/fvm/versions/3.0.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 8A362B17-9737-4B87-B0E4-77BF160D0A50 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by srawlins** [comment] 2022-05-16 16:58
> I would like to keep the `super.key` on the private widgets, but I also want to keep the `unused_element` rule enabled. Is there any way to achieve this?

No I don't think so. If you want to keep an unused parameter on your private widget, you will keep getting an `unused_element` report.

**Comment by srawlins** [comment] 2022-05-16 17:00
How does this relate to `user_super_parameters`? If you remove the named parameter (and pass `null` directly) do you get a `user_super_parameters` report?

**Comment by maxlapides** [comment] 2022-05-16 17:15
@srawlins It's related to the super parameters because this breaks `unused_element`:

```dart
class _MyWidget extends StatelessWidget {
  const _MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

But this does not:

```dart
class _MyWidget extends StatelessWidget {
  const _MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

But, this doesn't really have much to do with the lint rule `use_super_parameters`, but rather just the new Dart 2.17 super parameters syntax.

**Comment by srawlins** [comment] 2022-05-16 17:17
Oops, that second example should also have an `unused_element` report, since no argument is ever given.

**Comment by maxlapides** [comment] 2022-05-16 17:21
It's super common in Flutter to have this `key` parameter on all widgets, regardless of whether the `key` parameter is ever used. It would be great to be able to disable `unused_element` just for the `key`s in Flutter.

**Comment by srawlins** [comment] 2022-05-16 17:38
I can update the title of this issue to make that the ask.

**Comment by maxlapides** [comment] 2022-05-16 17:51
@srawlins That would be great, thanks!

**Comment by goderbauer** [comment] 2022-05-17 23:08
I agree with the previous comment. There's no reason to have the `key` parameter on a private widget if nobody is using it. If you need to pass the key, you can always add it to the private widget since you're in full control of the code.

For a public widget (that may get exported from a library you don't have control over) you want to make sure it can always take a key. If the key parameter is omitted, you'd have to ask the library author to release a new version with the key parameter added.

**Comment by maxlapides** [comment] 2022-05-17 23:32
I'm not strongly opposed to removing the `key` parameters on the private widgets, but I do think there's a reasonable argument to be made that it is _less_ work to have the `super.key` on all the private widgets because it's generated by a code snippet. Then, it's always available when you need it later, you don't need to go add it manually by editing a file that you may not have otherwise needed to touch.

**Comment by khobotin-elopage** [comment] 2022-05-19 14:32
I agree with Max. It's common for widgets to have key parameter whether they are public or private. 
And it seems there have been an exception for the key parameter in `unused_element` rule because this
```dart
const _MyWidget({Key? key}) : super(key: key);
````
looks legit for it.

Also it's more likely to forget to add the key whenever I want to make my private widget a public.

**Comment by orevial** [comment] 2022-05-19 15:05
I understand your point of view although I disagree : 

- IDE's snippets adding the key automatically when generating widgets is not a good reason IMO to implement an exception to this rule, the IDE snippet should follow language conventions and not the opposite
- I understand the argument about the risk of forgetting to add `key` on public widgets but there is a linter rule specifically designed for this case : `use_key_in_widget_constructors` which will make sure you never forget a key on public widgets 😉

**Comment by srawlins** [comment] 2022-05-19 15:09
Generally speaking, the `unused_*` and `unnecessary_*` rules come from a policy of rejecting the "but I might need it later" argument in favor of highlighting unused and unnecessary code. I think these rules will always report as much unused and unnecessary code as is technically correct.

If a dev or a team firmly believes some code should remain, however unused, they can disable the rules or suppress them [by various means](https://dart.dev/guides/language/analysis-options). If disabling "unused_element" across a codebase is too big a hammer, we may split a diagnostic out, as per https://github.com/dart-lang/sdk/issues/48401, for unused parameters, as this argument has come up a few times, "but I might need it later."

**Comment by rrousselGit** [comment] 2022-10-27 14:54
Clearly, this behavior is controversial. The reactions speak for themselves I think. There's a decent amount of upvotes on both sides of the argument.

That's the issue.   
This feature is controversial, yet it got added to one of the most used lints. As such, disabling the lint globally is unreasonable. Adding `// ignore` for all cases is unreasonable too.

This ends up negatively impacting a large number of people with no real solution.

Extracting this behavior into a new lint rule would lead to a happy ending for everyone. Those who like this can keep it. Those who don't can disable it.

**Comment by dnfield** [comment] 2022-11-10 00:11
In https://github.com/flutter/tests/pull/172, I believe this is the cause of `dart fix` removing a parameter that never gets set, which results in compilation errors since the program is depending on the parameter to initialize a default value fo ra final variable.

**Comment by s0nerik** [comment] 2023-03-21 22:01
Any updates?

The IntelliJ IDEA plugin generates a widget with `super.key` for extracted widgets (Cmd + Ctrl + W), which I need to manually adjust each time now to `Key? key` just to bypass the lint.

I'd love to have either a separate lint that ignores this specific case, as mentioned above, or at the very least have an option for the IDEA plugin to generate `Key? key` in the widget constructors.

**Comment by srawlins** [comment] 2023-03-21 23:22
No updates.

> I'd love to have either a separate lint that ignores this specific case, as mentioned above

That's probably the direction we'll go.

**Comment by srawlins** [comment] 2023-03-22 21:57
Oops, I think we implemented that. You can now `// ignore_for_file: unused_element_parameter` or ignore `unused_element_parameter` in your `analysis_options.yaml`, and you're good to go... I don't think there is anything else to do here.


@dnfield the `dart fix` issue would be a separate issue.

**Comment by maxlapides** [comment] 2023-03-23 02:17
@srawlins Great, `unused_element_parameter` is exactly what I'm looking for! Could you please show how I can use it in `analysis_options.yaml` to ignore this for the entire project? I can't seem to figure out the syntax :)

**Comment by srawlins** [comment] 2023-03-23 03:54
No worries, I always forget it too :)

Here's the syntax: https://dart.dev/guides/language/analysis-options#ignoring-rules

**Comment by maxlapides** [comment] 2023-03-23 04:21
@srawlins Strangely, I am getting this warning `'unused_element_parameter' isn't a recognized error code. dart(unrecognized_error_code)`:

```yaml
analyzer:
  errors:
    unused_element_parameter: ignore
```

**Comment by srawlins** [comment] 2023-03-23 15:23
Ah ok if that doesn't work then there is remaining work. I have an idea.

**Comment by xVemu** [comment] 2023-07-12 10:12
Any news?

**Comment by srawlins** [comment] 2023-07-12 14:14
No news.

**Comment by srawlins** [comment] 2023-07-24 16:42
Had to revert the fix; broke various flutter things. See https://github.com/flutter/flutter/issues/131096#issuecomment-1646368103

**Comment by antonxandre** [comment] 2023-08-04 17:57
> @srawlins Strangely, I am getting this warning `'unused_element_parameter' isn't a recognized error code. dart(unrecognized_error_code)`:
> 
> ```yaml
> analyzer:
>   errors:
>     unused_element_parameter: ignore
> ```


Works to me with:
 
```
analyzer:
  errors:
    unused_element: ignore
 ```

**Comment by iska9der** [comment] 2023-11-23 21:52
*Don't worry, I'm just a reminder: we still need a solution to this problem*

**Comment by kuyazee** [comment] 2024-03-27 02:36
> > @srawlins Strangely, I am getting this warning `'unused_element_parameter' isn't a recognized error code. dart(unrecognized_error_code)`:
> > ```yaml
> > analyzer:
> >   errors:
> >     unused_element_parameter: ignore
> > ```
> 
> Works to me with:
> 
> ```
> analyzer:
>   errors:
>     unused_element: ignore
> ```

This worked for me on flutter version 3.19.4

**Comment by lore-co** [comment] 2024-08-01 14:33
Any news?

**Comment by srawlins** [comment] 2024-08-14 14:07
The splitting CL is reverted; re-opening.

**Comment by athomas** [comment] 2024-08-16 11:49
3.6.0-149.0.dev includes the fix, in case someone wants to try it. However, it's still reverted on `main` so the next dev release will likely not contain the fix anymore.

**Comment by srawlins** [comment] 2024-08-21 14:19
@iinozemtsev this is still reverted on main, right? re-open?

**Comment by iinozemtsev** [comment] 2024-08-22 07:29
oh, I didn't expect that pushing into a _fork_ can close the issue, sorry!

**Comment by srawlins** [comment] 2024-08-22 14:16
Oh, I see, haha! Thanks much!

**Closed** 2024-08-23 20:49 UTC
Labels: area-analyzer, P3, analyzer-warning, type-enhancement
