### ISSUE TITLE
NPE in scannerRecovery, DeclarationsTracker._getFileByPath, 2.5.0-edge.1ef83b86ae63

### ISSUE THREAD

**Issue by Memotets** [dart-lang/sdk#39132] opened 2019-10-27 02:53 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-11-amd64, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      scannerRecovery (package:front_end/src/fasta/scanner/recover.dart:31:17)
#2      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:103:14)
#3      scanString (package:front_end/src/fasta/scanner.dart:95:10)
#4      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:146:34)
#5      _File._parse (package:analyzer/src/services/available_declarations.dart:1835:25)
#6      _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#7      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:660:14)
#8      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:573:18)
#9      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#10     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#11     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#12     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#13     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#14     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#15     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#21     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#22     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#23     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#24     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#25     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#33     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#34     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#35     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#36     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#37     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by devoncarew** [comment] 2019-10-28 03:57
cc @scheglov

**Comment by scheglov** [comment] 2019-10-29 01:54
Scanner is a part of CFE, so even though we called it from analyzer, it is still an issue to fix in CFE.

**Comment by devoncarew** [comment] 2019-10-29 04:43
cc @jensjoha

**Comment by srawlins** [comment] 2019-11-04 16:15
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38405; please follow along there.

**Comment by srawlins** [comment] 2019-11-04 16:15
Duplicate of https://github.com/dart-lang/sdk/issues/38405

**Closed by srawlins** 2019-11-04 16:15 UTC
Labels: analyzer-crash-report, area-analyzer, area-front-end
