### ISSUE TITLE
Dart team ask me report this error

### ISSUE THREAD

**Issue by tuken80** [dart-lang/sdk#36629] opened 2019-04-15 09:21 UTC
* Dart SDK Version (`dart --version`)
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
macOS Mojave 10.14.4

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
flutter run --enable-software-rendering
in Nexus 5X avd with Android 9.0 x86

Missing some or all of the above might make the issue take longer or be
impossible to act on.

----

I don't know if it's really an issue.

------

Compiler message:                                                       
Warning: Tried to initialize from a previous compilation (build/app.dill), but couldn't.
Error message was 'RangeError (index): Index out of range: no indices are valid: 0'.
Stacktrace included '#0      Uint8List.[] (dart:typed_data/runtime/libtyped_data_patch.dart:2177:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:426:17)
#4      IncrementalCompiler.initializeFromDill (package:front_end/src/fasta/incremental_compiler.dart:499:14)
<asynchronous suspension>                                               
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:133:34)
<asynchronous suspension>                                               
#6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#7      new Future.sync (dart:async/future.dart:224:31)                 
#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#9      _rootRun (dart:async/zone.dart:1124:13)                         
#10     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#11     _runZoned (dart:async/zone.dart:1516:10)                        
#12     runZoned (dart:async/zone.dart:1463:12)                         
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:116:20)
<asynchronous suspension>                                               
#15     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
<asynchronous suspension>                                               
#16     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:339:67)
#17     new Future.<anonymous closure> (dart:async/future.dart:176:37)  
#18     _rootRun (dart:async/zone.dart:1120:38)                         
#19     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)             
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _rootRun (dart:async/zone.dart:1124:13)                         
#23     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#26     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#27     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
'.                                                                      
This might be a bug.                                                    
                                                                        
The Dart team would greatly appreciate it if you would take a moment to report this problem at http://dartbug.com/new.
If you are comfortable with it, it would improve the chances of fixing any bug if you included the file file:///var/folders/zb/jmv5h59n4tg_r6lb56yf1w480000gn/T/initialize_from.dillm9NSTX/initialize_from.dill.gz in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary disk space.

-----

[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3079384/initialize_from.dill.gz)

**Comment by jensjoha** [comment] 2019-05-01 09:35
Thank you for reporting this.
This is caused by the file we try to initialize from being empty. This can happen if for instance launching several instances working on the same file (e.g. one instance is overwriting the file while the other is reading it). As long as it doesn't happen all the time it's nothing to worry about.
I recently landed d8739b582b5e7bcc84747cf37e925c3c79f29642 to make sure we don't even try to load when the file is empty, and this warning will thus be avoided.

**Closed by jensjoha** 2019-05-01 09:35 UTC
Labels: area-front-end
