### ISSUE TITLE
[cfe/ffi] Cascading error on wrong types when using `.address`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#56462] opened 2024-08-13 17:13 UTC
There is 2 errors being thrown for this snippet

```dart
@Native<Void Function(Pointer<Void>)>(isLeaf: true)
external void myNative(Pointer<Void> buffer);

void main() {
  final typedData = Int8List.fromList([1, 2]);
  myNative(typedData.address);
}
```

Output of  `dart <thisfile.dart>`:
```bash
tests/ffi/static_checks/address_of_cast_test.dart:50:22: Error: The argument type 'Pointer<Int8>' can't be assigned to the parameter type 'Pointer<Void>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Int8' is from 'dart:ffi'.
 - 'Void' is from 'dart:ffi'.
  myNative(typedData.address);
                     ^
tests/ffi/static_checks/address_of_cast_test.dart:50:22: Error: The '.address' expression can only be used as argument to a leaf native external call.
  myNative(typedData.address);
```

The second error is not supposed to be thrown, and its not reported by analyzer (confirmed that by running `dart analyze` and got only one error which is the first one)

I tested this on 3.5.0-292.0.dev, seems this is a existing behavior.

_Originally posted by @codesculpture in https://github.com/dart-lang/sdk/issues/55971#issuecomment-2284593422_

**Comment by codesculpture** [comment] 2024-08-13 17:14
I can take this up, if its okay. @dcharkes

**Comment by codesculpture** [comment] 2024-08-28 17:28
@dcharkes i found the root cause of this issue which from above code
`myNative(typedData.address)` where the `typedData.address` is not transformed 
due to the expression type is `InvalidExpression` which is skipped for transformation due to this `https://github.com/dart-lang/sdk/blob/8fa0f56f453a1e22406f0e057be27787bf49b3be/pkg/vm/lib/modular/transformations/ffi/use_sites.dart#L1526`

Do you think transforming `typedData.address` even its not the right type make sense ?
am just thinking loud

**Comment by codesculpture** [comment] 2024-08-28 17:32
Actually it seems, we don't need to perform the transformation if it isn't the right type, that's just unnecessary

**Comment by codesculpture** [comment] 2024-08-28 18:26
Or is it viable to store the context that the given `StaticInvocation` was part of native leaf call if so we can simply ignore the error reporting
```
else if (addressOfMethods.contains(target) && !isPartOfNativeLeafCall) {
        diagnosticReporter.report(
            messageFfiAddressPosition, node.fileOffset, 1, node.location?.file);
      }
```

but storing such `isPartOfNativeLeafCall` would be overhead it seems.

So i guess all i can think is 2 options:
1. Storing `isPartOfNativeLeafCall`, but i have no idea how to store and maintain it (which seems complex).
2. We can just transform the .address (even if it is passed for wrong type) which may simple.

Wdyt @dcharkes

**Comment by dcharkes** [comment] 2024-08-28 18:30
> We can just transform the .address (even if it is passed for wrong type) which may simple.

If we transform, but still report the original error so that the compilation fails, I think that is fine. 👍 

Alternatively, we could transform it to a `throw 'Invalid code'` instead.

**Comment by codesculpture** [comment] 2024-08-28 19:51
https://github.com/dart-lang/sdk/pull/56594, this is what you are saying ?

**Comment by codesculpture** [comment] 2024-08-31 02:13
This been landed here can be closed https://dart-review.googlesource.com/c/sdk/+/382681

**Closed** 2024-09-02 06:28 UTC
Labels: P3, contributions-welcome, library-ffi, area-native-interop
