### ISSUE TITLE
Analyzer should warn when a constructor has unused parameters

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#25405] opened 2016-01-11 22:51 UTC
The following code gives no warnings:

```dart
class Foo {
  Foo(bool test);
}
void main() {
  new Foo(true);
}
```

**Comment by jmesserly** [comment] 2016-01-11 23:14
I think this is a dupe of https://github.com/dart-lang/sdk/issues/18946

**Closed** 2016-01-11 23:14 UTC
Labels: analyzer-hint, analyzer-ux, area-analyzer, resolution-duplicate
