### ISSUE TITLE
NPE from  _OpTypeAstVisitor.visitSimpleFormalParameter, 2.5.0-edge.1ef83b86ae

### ISSUE THREAD

**Issue by pedro-culque-ifood** [dart-lang/sdk#39096] opened 2019-10-24 17:56 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1680x1050, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 2565, method: completion.getSuggestions, params: {file: /Users/pedroculque/Documents/FlutterProjects/ifood-partner-app-flutter/lib/src/ui/profile/settings/manage_alerts_screen.dart, offset: 4861}, clientRequestTime: 1571934091207}
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _OpTypeAstVisitor.visitSimpleFormalParameter (package:analyzer_plugin/src/utilities/completion/optype.dart:1059:30)
#2      _OpTypeAstVisitor.visitFormalParameterList (package:analyzer_plugin/src/utilities/completion/optype.dart:713:7)
#3      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4551:49)
#4      new OpType.forCompletion (package:analyzer_plugin/src/utilities/completion/optype.dart:152:16)
#5      DartCompletionRequestImpl.opType (package:analysis_server/src/services/completion/dart/completion_manager.dart:377:21)
#6      DartCompletionManager._addIncludedElementKinds (package:analysis_server/src/services/completion/dart/completion_manager.dart:198:26)
#7      DartCompletionManager.computeSuggestions (package:analysis_server/src/services/completion/dart/completion_manager.dart:133:7)
<asynchronous suspension>
#8      CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart:122:42)
<asynchronous suspension>
#9      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#10     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1500:12)
#15     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#16     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1500:12)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#52     _SinkTransformerStreamSub...
```

For additional log information, please append the contents of
file:///private/var/folders/dm/ztm18d3x1ll1pb2h3hm0jdxh0000gp/T/report.txt.

**Comment by srawlins** [comment] 2019-11-04 16:30
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38513; please follow along there.

**Comment by srawlins** [comment] 2019-11-04 16:30
Duplicate of https://github.com/dart-lang/sdk/issues/38513

**Closed by srawlins** 2019-11-04 16:30 UTC
Labels: analyzer-completion, analyzer-crash-report, area-analyzer
