### ISSUE TITLE
relative `lib` imports are not resolving correctly in tests

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#44673] opened 2021-01-14 23:02 UTC
Noted in https://github.com/dart-lang/sdk/blob/7f95c18812945ffab70418583e3b19c3a77cd06f/pkg/analysis_server/test/src/services/correction/fix/convert_to_package_import_test.dart#L29-L31

And has come up again when testing bulk-fixes.

**Comment by bwilkerson** [comment] 2021-01-14 23:10
@scheglov

**Comment by scheglov** [comment] 2021-01-15 00:57
Seems for work as intended.
Resolving such relative URI in a package `lib/` makes us to leave the package.
The fact that there is some file system where it could bring us back does not matter IMHO.

**Comment by bwilkerson** [comment] 2021-01-15 23:07
If we don't support URIs of that form, then I have to question the value of the lint (as currently defined and implemented).

**Comment by srawlins** [comment] 2023-04-19 15:59
Maybe working as intended.

**Closed** 2023-05-03 16:09 UTC
Labels: area-analyzer, P3, needs-info, type-code-health, type-bug
