### ISSUE TITLE
Error from IntelliJ when I move files into directory.

### ISSUE THREAD

**Issue by zaralockheart** [dart-lang/sdk#39941] opened 2019-12-28 06:12 UTC
Analyzer Feedback from IntelliJ

## Steps:
1. Create 2 files in lib/
example: `file1.dart` and `file2.dart`
2. Add import between each other
in `file1.dart`

```
import 'file2.dart`
```

in `file2.dart`

```
import 'file1.dart`
```

3. Create a directory
4. Move these 2 files into the newly created directory.

* After moving the files.
import  in `file1.dart` becomes `../file2.dart` and import in `file2.dart` becomes `newdir/file1.dart`

## Version information

- `IDEA IU-193.5233.102`
- `2.7.0-dev.2.1`
- `IU-193.5233.102, JRE 11.0.4+10-b520.11x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, error: FileSystemException(path=C:\Users\yuzuriha\IdeaProjects\core\lib\injector.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#55     _SinkTransformerStreamSubscription._handleDat...
```

For additional log information, please append the contents of
file://C:\Users\yuzuriha\AppData\Local\Temp\report.txt.

**Comment by zaralockheart** [comment] 2019-12-28 06:19
`report.txt`

```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, error: FileSystemException(path=C:\Users\yuzuriha\IdeaProjects\core\lib\injector.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1029:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:985:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:863:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:393:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#55     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#56     _rootRunUnary (dart:async/zone.dart:1134:38)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#61     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#62     _StreamController._add (dart:async/stream_controller.dart:642:7)
#63     _StreamController.add (dart:async/stream_controller.dart:588:5)
#64     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#65     _rootRunUnary (dart:async/zone.dart:1138:13)
#66     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#67     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#70     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#71     _StreamController._add (dart:async/stream_controller.dart:642:7)
#72     _StreamController.add (dart:async/stream_controller.dart:588:5)
#73     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
#74     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#75     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#76     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#77     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```
1577513459496 => {"id":"4695","method":"edit.getAssists","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","offset":574,"length":0},"clientRequestTime":1577513459496}
1577513459499 <= {"id":"4695","result":{"assists":[]}}
1577513479330 => {"id":"4696","method":"analysis.getNavigation","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart","offset":40,"length":22},"clientRequestTime":157751347933
1577513479337 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart","errors":[]}}
1577513479338 <= {"id":"4696","result":{"files":["C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":0,"length":0,"startLine":1,"startColu
1577513479338 <= {"event":"flutter.outline","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":433,"codeOffset":0,"code
1577513479339 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","classes":[{"offset":647,"length":7}],"members":[]}}
1577513479400 => {"id":"4697","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart","offset":0,"length":0,"validateOnly":true
1577513479413 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart","errors":[]}}
1577513479415 <= {"id":"4697","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[]}}
1577513479415 <= {"event":"flutter.outline","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":433,"codeOffset":0,"code
1577513479416 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","classes":[{"offset":647,"length":7}],"members":[]}}
1577513479431 => {"id":"4698","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart","offset":0,"length":0,"validateOnly":fals
1577513479447 <= {"id":"4698","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"change":{"message":"","edits":[{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dar
1577513479474 => {"id":"4699","method":"analysis.updateContent","params":{"files":{"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\utils\\injector.dart":{"type":"add","content":"import 'package:get_it/
1577513479474 => {"id":"4700","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","offset":0,"length":0,"validateOnly":true,
1577513479474 <= {"id":"4699","result":{}}
1577513479487 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","errors":[]}}
1577513479487 <= {"id":"4700","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[]}}
1577513479488 => {"id":"4701","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","offset":0,"length":0,"validateOnly":false
1577513479488 <= {"event":"analysis.highlights","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":30},{"type":"BUILT_IN",
1577513479489 <= {"event":"analysis.navigation","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","regions":[{"offset":7,"length":22,"targets":[0]},{"offset":38,"length":30
1577513479489 <= {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","labels":[]}}
1577513479489 <= {"event":"analysis.outline","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<uni
1577513479489 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","overrides":[]}}
1577513479490 <= {"event":"flutter.outline","params":{"file":"C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\network.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":1437,"codeOffset":0,"code
1577513479496 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":350,"uri":"package:core/core.dart","items":[{"label":"Network","declaringLibraryUri":"package:core/netwo
1577513479500 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1245,"uri":"package:core/network.dart","items":[{"label":"Network","declaringLibraryUri":"package:core/n
1577513479515 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1263,"uri":"package:core/utils/injector.dart","items":[{"label":"locator","declaringLibraryUri":"package
1577513479521 <= {"id":"4701","error":{"code":"SERVER_ERROR","message":"FileSystemException(path=C:\\Users\\yuzuriha\\IdeaProjects\\core\\lib\\injector.dart; message=Cannot open file)","stackTrace":"#
```

**Comment by devoncarew** [comment] 2019-12-30 22:56
Thanks for the detailed report!

**Comment by keertip** [comment] 2020-01-06 17:20
Duplicate of #38157

**Closed by keertip** 2020-01-06 17:20 UTC
Labels: analyzer-crash-report, area-analyzer
