### ISSUE TITLE
dart/ffi: automatic release of pointers

### ISSUE THREAD

**Issue by derolf** [dart-lang/sdk#39748] opened 2019-12-11 19:08 UTC
Right how, pointers returned from FFI functions require manual reference counting on the dart level.

Provide a way to automatically clean up native references once they are not referenced anymore.

**Comment by dcharkes** [comment] 2019-12-13 15:38
That can potentially be achieved in two ways:

* pool allocation: clean up when end of scope (like try-with-resources in Java or using in C#)
* finalizers: clean up when garbage collector collects pointer object

Pool allocation is tracked in https://github.com/dart-lang/ffi/issues/30. We would like to add the pool to package:ffi soon, please leave your feedback on that issue.

Finalizers is tracked in https://github.com/dart-lang/sdk/issues/35770. This will take longer to implement.

I'll close this issue as a duplicate of either one of the above two. Feel free to reopen if you have questions related which are not pool or finalizer related.

**Closed by dcharkes** 2019-12-13 15:38 UTC
Labels: area-library, library-ffi
