### ISSUE TITLE
Crash on corelib/big_integer_parsed_mul_div_vm_test on debug_simdbc64

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#29259] opened 2017-04-05 11:16 UTC
The Dart VM crashed on debug_simdbc64:

Link (will go stale): https://build.chromium.org/p/client.dart/builders/vm-mac-debug-simdbc64-reload-be/builds/683/steps/vm%20tests/logs/stdio

Unfortunately no core dump.

Relevant output:
```
FAILED: none-vm debug_simdbc64 corelib/big_integer_parsed_mul_div_vm_test
Expected: Pass Slow 
Actual: Crash
CommandOutput[vm]:

stderr:
../../runtime/vm/object.cc: 13544: error: expected: Object::Handle(Array::Handle(ic_data()).At(data_pos)).IsFunction()
Dumping native stack trace for thread 1203
  [0x000000010a4fcd63] dart::Profiler::DumpStackTrace()
  [0x000000010a4fcd63] dart::Profiler::DumpStackTrace()
  [0x000000010a60a450] dart::ZoneTextBuffer::AddString(char const*)
-- End of DumpStackTrace


Command[vm]: DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-debug-simdbc64-reload-be/build/sdk/.packages /b/build/slave/vm-mac-debug-simdbc64-reload-be/build/sdk/tests/corelib/big_integer_parsed_mul_div_vm_test.dart
Took 0:00:23.415049

Short reproduction command (experimental):
    python tools/test.py -asimdbc64 --hot-reload -t960 corelib/big_integer_parsed_mul_div_vm_test
```

**Comment by mraleph** [comment] 2018-11-26 17:41
Duplicated of #35010

**Comment by mraleph** [comment] 2018-11-26 17:42
Duplicate of #35010

**Closed by mraleph** 2018-11-26 17:41 UTC
Labels: area-vm, gardening
