### ISSUE TITLE
exception_20190627_214256_074

### ISSUE THREAD

**Issue by hpoit** [dart-lang/sdk#37393] opened 2019-06-28 00:46 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.7479.14`
- `2.3.2`
- `WS-191.7479.14, JRE 1.8.0_202-release-1483-b53x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1280x800`

## Exception
```
Dart analysis server, SDK version 2.3.2, server version 1.26.0, error: Analysis failed: /Users/kevinliu/WebstormProjects/quickstart/web/main.dart context: exception_20190627_214256_074
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:642:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:360:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:327:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:219:14)
#6      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:123:10)
#7      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:99:14)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:98:43)
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1438:63)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:210:29)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#19     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:21)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:591:12)
#25     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:506:7)
#26     Driver.start (package:analysis_server/src/server/driver.dart:411:7)
#27     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#28     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#29     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#30     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/d2/fvp3pdj96h55gg8wsc99vmrc0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-05 04:10
Thanks for reporting this issue! This was also reported at #37394; please follow along there.

**Comment by srawlins** [comment] 2019-09-05 04:10
Duplicate of #37394

**Closed by srawlins** 2019-09-05 04:10 UTC
Labels: P1-High, analyzer-crash-report, area-analyzer, type-bug
