### ISSUE TITLE
Not sure how to compile a binary with null safety on

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#43594] opened 2020-09-29 03:03 UTC
I'm trying to compile a null safe executable using `dart compile exe` on the latest `dev` channel but it looks like the flag is ignored wherever I put it:

```
~/dev/html_unescape$ history                                            9:20:40
 9258  dart help compile
 9259  dart compile exe benchmark/benchmark.dart
 9260  dart --enable-experiment=non-nullable compile exe benchmark/benchmark.dart
 9261  dart compile exe --enable-experiment=non-nullable  benchmark/benchmark.dart
 9262  dart compile --enable-experiment=non-nullable exe benchmark/benchmark.dart
 9263  dart compile exe benchmark/benchmark.dart --enable-experiment=non-nullable
```
 
The tool never complains about a misplaced flag, but the result is always the same: 

```
Error: This requires the null safety language feature, which is experimental.
You can enable the experiment using the '--enable-experiment=non-nullable' command line option.

[ ... ]
```

* Dart SDK Version (`dart --version`)

  `Dart SDK version: 2.10.0-110.0.dev (dev) (Wed Sep 9 17:51:43 2020 -0700) on "macos_x64"`

* Whether you are using Windows, MacOSX, or Linux (if applicable)

  MacOSX

cc @mit-mit

**Comment by mit-mit** [comment] 2020-09-30 13:51
@filiph given we're close to beta, I don't think we're going to add flags support to the `dart compile` command. But I think you mentioned you saw the same behavoir for some of our main commands?

**Comment by filiph** [comment] 2020-09-30 17:09
Ok, good point, these are separate issues. I'll file the other one.

So, just to be clear, there is currently no way to compile a null-safety-enabled Dart program into a binary? Just checking.

**Comment by mit-mit** [comment] 2020-09-30 20:28
> there is currently no way to compile a null-safety-enabled Dart program into a binary?

No, sorry, there is not

**Comment by mit-mit** [comment] 2020-10-01 07:36
Closing as intended; we hope to have a beta build in the not to distant future

**Closed by mit-mit** 2020-10-01 07:36 UTC

**Comment by dragonfax** [comment] 2020-10-21 02:36
`--enable-experiment=null-nullable` was added to `dart2native` back in august. Is this something just won't be included in its replacement `dart compile exe`?

**Comment by mit-mit** [comment] 2020-10-21 08:30
Sorry, yes we're not going to prioritize adding it right now. We're spending all our time on getting to beta, where there is no experiment flag at all.
