### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)

### ISSUE THREAD

**Issue by FaterYU** [dart-lang/sdk#55316] opened 2024-03-27 17:54 UTC
I got some errors:
```bash
E/flutter (22754): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _Future@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)
E/flutter (22754):  <- Instance of 'CameraController' (from package:camera/src/camera_controller.dart)
E/flutter (22754):  <- Instance of '_CameraAppState' (from package:wearwizard/wear_wizard/components/camera_page.dart)
E/flutter (22754):  <- field this in _CameraAppState._processImageIsolate (from package:wearwizard/wear_wizard/components/camera_page.dart)
E/flutter (22754):
E/flutter (22754): #0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:398:25)
E/flutter (22754): #1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:378:7)
E/flutter (22754): #2      _CameraAppState._processImage (package:wearwizard/wear_wizard/components/camera_page.dart:70:19)
E/flutter (22754): #3      _CameraAppState.initState.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:wearwizard/wear_wizard/components/camera_page.dart:43:31)
E/flutter (22754): #4      CameraController.startImageStream.<anonymous closure> (package:camera/src/camera_controller.dart:481:20)
E/flutter (22754): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (22754): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (22754): #7      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (22754): #8      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (22754): #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (22754): #10     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (22754): #11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
My environment is:
- Windows 11 Beta
- Flutter 3.19.3 • channel stable
- Dart 3.3.1 • DevTools 2.31.1

This is part of my code:
```dart
  Future<int> _processImage(CameraImage cameraImage) async {
    final imglib.Image imgRGBA = convertYUV420ToImage(cameraImage);

    final Uint8List u8Bytes = imgRGBA.getBytes(format: imglib.Format.rgba);
    final resultPort = ReceivePort();
    await Isolate.spawn(_processImageIsolate,
        [resultPort.sendPort, u8Bytes, imgRGBA.width, imgRGBA.height]);

    final count = await resultPort.first;
    return count;
  }

  Future<void> _processImageIsolate(List<dynamic> args) async {
    final SendPort resultPort = args[0];
    final Uint8List u8Bytes = args[1];
    final int width = args[2];
    final int height = args[3];

    final pixelsPtr = calloc<Uint8>(u8Bytes.length);
    final Uint8List bytes = pixelsPtr.asTypedList(u8Bytes.length);
    bytes.setAll(0, u8Bytes);

    final result = yolo8.processImage(pixelsPtr, width, height);
    calloc.free(pixelsPtr);
    Isolate.exit(resultPort, result);
  }
```

I checked many times with [send abstract method](https://api.dart.dev/stable/3.0.0/dart-isolate/SendPort/send.html) but I can not find the illegal type. 

Could anyone help me? Thanks!

If you need more detail, please let me know!

**Comment by rmacnak-google** [comment] 2024-03-27 20:39
`_processImageIsolate` looks like an instance method, so the tear-off of  `_processImageIsolate` passed to Isolate.spawn references the the receiver (`this`) of _processImage which eventually references a future. You might try making `_processImageIsolate` a static or top-level method.

**Comment by a-siva** [comment] 2024-03-28 12:54
@FaterYU please see comment above.

Closing issue as 'working as intended', please reopen if you think otherwise.

**Closed by a-siva** 2024-03-28 12:54 UTC
Labels: closed-as-intended
