### ISSUE TITLE
Analyzer warns about function that always returns

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/sdk#28069] opened 2016-12-11 20:24 UTC
When a function returns from a switch statement on an enum and covers all enum values but does not have a return statement at the end, the analyzer show a warning, gist at https://gist.github.com/anonymous/31caf98143f8d25c7e06f6647b0c03a2, snippet below:

```dart
enum FancyEnum {
  first,
  second,
  third
}

int fancyFunction(FancyEnum param) {
  switch(param) {
    case FancyEnum.first:
      return 1;
    case FancyEnum.second:
      return 2;
    case FancyEnum.third:
      return 3;
  }
}
```

This might be correct given the language specification, is just confusing as a user, specially since the analyzer warns for each missing value in the switch statement itself.

**Comment by bwilkerson** [comment] 2016-12-11 23:23
Yep. This is a known issue, and one that will probably get better if we get non-nullable types in the language.

The problem is that `param` can have the value `null`, which isn't covered by any of the cases, in which case the method will return `null`, which might not be the intended behavior.

It would be great, though, to improve the error message to explain this to users, because it's not obvious to most users.

**Comment by bwilkerson** [comment] 2018-01-27 19:13
Duplicate of https://github.com/dart-lang/sdk/issues/27473

**Closed by bwilkerson** 2018-01-27 19:13 UTC
Labels: P2 medium, Type: enhancement, analyzer-ux, area-analyzer
