### ISSUE TITLE
Exception on DartAnalysis only on Windows 10 Pro

### ISSUE THREAD

**Issue by charlenopires** [dart-lang/sdk#35251] opened 2018-11-24 16:03 UTC
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I get this Error when AutoComplete code

### Versions

- Flutter SDK 0.11.10-pre.2
- Visual Studio Code 1.29.1
- Dart Code 2.20.0
- Operating System Windows 10 Pro 

### Analyzer Info

The analyzer was launched using the arguments:

```text
D:\Dart\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.20.0
```

### Exception

Could not initialize the library map from [D:\Dart\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart, D:\Dart\sdk\lib\_internal\libraries.dart]

```text
FileSystemException(path=D:\Dart\sdk\lib\_internal\libraries.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:613:41)
#2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:493:18)
#3      ContextBuilder.findSdk.<anonymous closure> (package:analyzer/src/context/builder.dart:393:36)
#4      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:137:29)
#5      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:146:19)
#6      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:392:23)
#7      ContextBuilder.createSourceFactory (package:analyzer/src/context/builder.dart:260:19)
#8      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:175:16)
#9      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1124:48)
#10     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1107:19)
#11     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1147:16)
#12     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:737:9)
#13     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:816:22)
#14     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#15     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:299:16)
#16     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:642:45)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:638:50)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1500:12)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:637:5)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#53     _rootRunUnary (dart:async/zone.dart:1132:38)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#62     _rootRunUnary (dart:async/zone.dart:1136:13)
#63     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#67     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#68     _StreamController._add (dart:async/stream_controller.dart:640:7)
#69     _StreamController.add (dart:async/stream_controller.dart:586:5)
#70     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#71     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#74     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#75     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

Diagnostics requested after the error occurred are:

```js
[]
```

**Comment by stereotype441** [comment] 2018-11-26 22:49
Duplicate of #34931

**Closed by stereotype441** 2018-11-26 22:49 UTC
Labels: area-analyzer, os-windows
