### ISSUE TITLE
Add Tau constant

### ISSUE THREAD

**Issue by 12people** [dart-lang/sdk#45591] opened 2021-04-05 13:12 UTC
I'd very much appreciate it if the [tau constant](https://tauday.com/) was added to Dart's math library. There is a movement to adopt this constant as a more intuitive alternative to pi, and it's already been adopted by Rust, Python, Julia, Processing, .NET, and others.

While this feature request has been reported twice in the past (as #14 and #21308), it seems that neither reached a conclusion and both seem to have been automatically closed both times due to inactivity.

I'm therefore opening up this issue again in the hopes that the constant might be added.

**Comment by mraleph** [comment] 2021-04-05 13:18
Duplicate of #14

**Closed by mraleph** 2021-04-05 13:18 UTC

**Comment by mraleph** [comment] 2021-04-05 13:20
Please note that both  #14 and #21308 are pretty clearly closed as "will not fix". See

https://github.com/dart-lang/sdk/issues/21308#issuecomment-108452344
https://github.com/dart-lang/sdk/issues/21308#issuecomment-108452346
https://github.com/dart-lang/sdk/issues/14#issuecomment-108301039

There is no real value in adding this constant.

**Comment by 12people** [comment] 2021-04-05 13:27
Ah, sorry, you're right — I missed the "WontFix" label.

I strongly disagree with the "no real value" argument — adoption by programming languages is an important step towards broader adoption of tau, and broader adoption of a more intuitive circle constant would have a plethora of potential benefits. I'm disappointed that it's been decided that it won't be adopted, but I guess there's nothing else I can do about this.
