### ISSUE TITLE
Compiler error compiling Flutter test.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#39851] opened 2019-12-18 19:35 UTC
Hi, I got a compiler error while compiling a flutter test:
```
Warning: Tried to initialize from a previous compilation (file:///usr/local/google/home/gspencer/code/flutter/examples/flutter_gallery/build/testfile.dill.track.dill), but the file was not self-contained. This might be a bug.
```
Here's the log zip file:
[initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3980188/initialize_from.dill.gz)

Dart version:
```
Dart VM version: 2.8.0-dev.0.0.flutter-c9d89d55a6 (Wed Dec 18 05:15:25 2019 +0000) on "linux_x64"
```

Flutter version
```
Flutter 1.13.3-pre.67 • channel gallery_density • git@github.com:gspencergoog/flutter.git
Framework • revision d243e52091 (2 weeks ago) • 2019-12-04 10:56:00 -0800
Engine • revision c327cae7ab
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c9d89d55a6)
```

**Comment by jensjoha** [comment] 2020-01-07 12:42
Thanks!

Will (probably) be fixed with https://dart-review.googlesource.com/c/sdk/+/130371/

PS: This is fantastic: Finally an issue I can point to, where this warning has paid off --- this was caused by an actual real life hard-to-figure-out and hard-to-spot bug!

**Closed** 2020-01-07 13:11 UTC
Labels: area-front-end
