### ISSUE TITLE
`build_resolvers` broken by sdk unfork -  analyzer requires explicit enabling of NNBD

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#41820] opened 2020-05-08 18:37 UTC
`build_resolvers` is broken after the unfork, see https://travis-ci.org/github/dart-lang/build/jobs/684776284#L431.

The reason is that we have to create our own SDK summary that is compatible with the current analyzer package version, but that now fails with `This requires the 'non-nullable' language feature to be enabled.`.

However, the SDK is supposed to be automatically whitelisted to allow NNBD. Obviously though older analyzer versions would not have known to do this either.

We could publish a new version that enables the experiment explicitly, but what SDK constraint should we set? Additionally, how as a package should we know exactly which experiments are required for the current SDK, and how can we prevent similar breakages in the future?

cc @leafpetersen @natebosch @kevmoo

**Comment by leafpetersen** [comment] 2020-05-08 18:44
So build_resolver is consuming the core libraries with a package:analyzer from a (potentially) earlier language version?  That doesn't seem like it's going to work in general - any time we add and start using a feature (e.g. extension methods) in the core libraries, old versions of the analyzer will no longer be able to analyze the new core libraries.

**Comment by jakemac53** [comment] 2020-05-08 18:50
yes which is why the analyzer should pin to sdk versions, or at least the min, but 🤷‍♂️

**Comment by leafpetersen** [comment] 2020-05-08 18:57
Why do it in analyzer and not in build_resolver?

**Comment by jakemac53** [comment] 2020-05-08 19:06
Because build_resolver has no sdk dependency itself. We would have to pin analyzer _and_ the sdk just because they aren't already properly versioned.

**Comment by scheglov** [comment] 2020-05-08 19:10
We could change analyzer to always build SDK summaries with `non-nullable` experiment enabled, for long time we did this when **analyzing** code, but because SDK had opt-out comments like `@dart = 2.7`, before un-fork we immediately downgraded back to opt-out.

Then we would need to publish analyzer and `build_resolver` will need this latest analyzer.

**Comment by sigmundch** [comment] 2020-05-09 02:59
Drive-by question - I may be misunderstanding the constraints, but it sounds like there is some circularity here. What's the reason you can't use the summary (`strong.sum`) that ships with the sdk?

In particular, you said you were building your own sdk summary so that you could support an older analyzer, but if you start pinning analyzer and sdk versions, wouldn't that remove the requirements to build a summary and you could start consuming the exiting summary out of the box?

**Comment by jakemac53** [comment] 2020-05-11 13:59
> but if you start pinning analyzer and sdk versions

We could pin but we shouldn't have to, and it potentially causes a lot of other problems in terms of version solving if we do that. It also means we have to republish for every new sdk and every new analyzer (even dev releases unless we are ok with our product being very unstable for dev users).

We used to use the shipped summary file until the summary format changed and we were broken, at which point we were told we needed to create our own summary.

**Comment by jakemac53** [comment] 2020-05-11 14:05
We talked offline on Friday and I suggested this approach for the future:

- Add a file in the SDK which lists all the experiments that the current SDK libraries require to be enabled.
  - This would be read by all tools in the sdk and they would be enabled by default.

We also realized that the package whitelist which is coming very soon will similarly break us. That hasn't been implemented yet but it should be implemented in a similar fasion:

- A file should ship with the SDK in JSON format, where the keys are whitelisted package names and the values are a list of experiment names that need to be enabled for those packages.

There is some question for the package whitelist though in terms of how we know _what versions_ of those packages to apply the experiments to. We could base it off of the language version potentially (apply the packages if the language version matches the current sdk language version). We would still need to be careful about that though, and ensure that we only ship the whitelist in dev sdks. Otherwise some future stable version of the package could start getting experiments enabled that it doesn't need (and/or potentially break it).

- Similarly for the upcoming package whitelist

**Comment by jakemac53** [comment] 2020-05-11 17:17
@leafpetersen @johnniwinther @scheglov please review above proposal :)

**Comment by jakemac53** [comment] 2020-05-11 20:36
The original issue here has been fixed now, but we might want to keep this open until we reach a consensus on how to make sure we don't break again.

**Comment by leafpetersen** [comment] 2020-05-11 21:21
> There is some question for the package whitelist though in terms of how we know _what versions_ of those packages to apply the experiments to. We could base it off of the language version potentially (apply the packages if the language version matches the current sdk language version).

This is the current plan.  That is, the whitelist unconditionally turns on the experiment for all versions of the package, and the language version of the package determines whether it is opted in or opted out.  Whitelisted packages need to publish with tight sdk constraints.

**Comment by franklinyow** [comment] 2020-05-11 22:54
@jakemac53  If the issue is fixed, it make sense to close this one as this one is labeled for unfork issue and has a due date.  Open a new issue to get consensus, so you won't show up as hot issue.

**Closed** 2020-05-12 13:35 UTC
Labels: P1, area-analyzer, unfork
