### ISSUE TITLE
Facing issue while using dart-lang/json_serializable

### ISSUE THREAD

**Issue by JigneshPatel23** [dart-lang/sdk#35692] opened 2019-01-17 20:26 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.2.0-edge.f701e11756967f10cde8216ecfad92b7b53e44f4`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.2 unknown, screens 1280x800  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/8m/7gx5kp411xdfvxfsxbnr315r0000gn/T/report2.txt

```
Dart analysis server, SDK version 2.2.0-edge.f701e11756967f10cde8216ecfad92b7b53e44f4, server version 1.22.1, error: Analysis failed: /Users/jigneshpatel/projects/github.com/JigneshPatel23/digital_events/digital_events/lib/models/profile.dart
Element mismatch in /Users/jigneshpatel/projects/github.com/JigneshPatel23/digital_events/digital_events/lib/models/profile.g.dart at /Users/jigneshpatel/projects/github.com/JigneshPatel23/digital_events/digital_events/lib/models/profile.g.dart
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:594:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:7)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2019-01-23 18:14
Possible duplicate of #33930

**Comment by scheglov** [comment] 2019-01-23 18:52
It looks like something that might have been fixed as https://github.com/dart-lang/sdk/issues/35551, in https://github.com/mihnita/sdk/commit/4e87a7630fe9a43be44e641e5a2b1a2b3353d174. Please try the bleeding edge Dart SDK.

**Comment by srawlins** [comment] 2019-11-12 22:02
Closing this as stale. Sorry we didn't get a chance to look at this issue. It was reported against a version of Dart that is at least 6 months old; please re-open if you encounter this on the latest version of Dart (or Flutter).

**Closed by srawlins** 2019-11-12 22:02 UTC
Labels: P2, analyzer-crash-report, area-analyzer, needs-info, type-bug
