### ISSUE TITLE
Remove warning when a non-platform library introduces the same name as a platform library

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#31866] opened 2018-01-11 20:54 UTC
Quoting from a comment by @lrhn in https://dart-review.googlesource.com/c/sdk/+/33662:

> In Dart 2 there should not be a warning when a non-platform library (not "dart:...") import introduces the same name as a platform-library. The non-platfrom version should implicitly shadow the platform library version.

**Comment by bwilkerson** [comment] 2018-01-30 00:02
Duplicate of #31836.

**Closed by bwilkerson** 2018-01-30 00:02 UTC
Labels: P1 high, Type: bug, analyzer-strong-mode, area-analyzer
