### ISSUE TITLE
Dart AOT compile is required for the server side

### ISSUE THREAD

**Issue by insinfo** [dart-lang/sdk#36782] opened 2019-04-27 19:44 UTC
when the AOT build for server-side applications is available, I'm developing server-side applications for Flutter and AngularDart with the Aqueduc framework, and I see that the startup and response times of the REST APIs are very high, the latency is very large.

ahead-of-time improve the startup time and reduce the memory footprint of VM-based applications.
Native images load faster because they don't have much startup activities, and require a static amount of fewer memory (the memory required by the JIT compiler);
Native images can share library code, while JIT-compiled images cannot.
If the application requires performance, then AOT is definitely the way to go. Needing to recompile during development is not an issue either, since AOT should be done during deployment, during which interfaces no longer change. Bytecode images generate a lot more code between function calls, so AOT having one additional jump instruction is still faster than regular JIT code.

I saw that there have been significant strides here,
https://medium.com/dartlang/dart-on-llvm-b82e83f99a70
why was not this continued?

Today we have WebAssembly, which can also be a target for AOT compilation in addition to x64 Windows / Linux

The JIT build used during development that is especially fast makes a lot of sense. More so, when an application is ready to be released, the AOT build makes more sense.

The AOT compiler is also needed to protect the source code, since it is not necessary to send the source code, but the compiled program.

* Dart SDK Version 2.2
* Windows / Linux 
* Chrome

**Comment by mraleph** [comment] 2019-04-27 20:54
Duplicate of #34343

**Closed by mraleph** 2019-04-27 20:54 UTC

**Comment by mraleph** [comment] 2019-04-27 20:57
Note: while it is true that AOT has better startup time for many use cases JIT is likely provide better peak performance. 

That said we are working on exposing the very same AOT compilation pipeline that is being used by Flutter as part of the Dart SDK. Stay tuned.

**Comment by insinfo** [comment] 2019-04-27 23:02
@mraleph Many thanks for the feedback, I'm looking forward to an alpha version of this
