### ISSUE TITLE
FFI fails loading dynamic library in 2.5.0

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#38288] opened 2019-09-10 10:29 UTC
Repro steps:

* Install 2.5.0 from https://dart.dev/get-dart
* Clone https://github.com/dart-lang/samples
* cd `samples/ffi/system-command`
* run `pub get`
* run `dart macos.dart`, `dart linux.dart`, or `dart windows.dart` depending on OS

Error:

```
$ dart macos.dart
Unhandled exception:
Invalid argument(s): Failed to load dynamic library (dlopen(libSystem.dylib, 1): image not found)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:10:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:17:12)
#2      system (file:///Users/mit/tmp/samples/ffi/system-command/macos.dart:28:36)
#3      main (file:///Users/mit/tmp/samples/ffi/system-command/macos.dart:9:16)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
| ~/tmp/samples/ffi/system-command @ mit-macbookpro3 (mit)
```

**Comment by sjindel-google** [comment] 2019-09-10 11:02
@mit-mit -- you said it's fixed on master, right?

**Comment by mit-mit** [comment] 2019-09-10 12:27
This is fixed on master, and we're working on publishing a Dart 2.6.0-dev build that should also have a fix.

**Comment by mit-mit** [comment] 2019-09-10 12:27
@sjindel-google can you check if we have an integration test to prevent this from happening again?

**Comment by sjindel-google** [comment] 2019-09-10 17:37
It doesn't appear to be an issue with 2.5.0 vs 2.6.0-dev; the problem is that after `dart` is signed, the system load path is changed. You can use `DynamicLibrary.open('/usr/lib/libSystem.dylib')` instead.

**Comment by mit-mit** [comment] 2019-09-10 17:39
Yes, confirmed that this works as expected on Windows

**Closed** 2019-09-10 17:44 UTC
Labels: area-vm
