### ISSUE TITLE
[feature-request] Improve Extract Variable by including without final and/or without type annotations

### ISSUE THREAD

**Issue by Stargator** [dart-lang/sdk#36196] opened 2019-03-13 20:12 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version: 2.2.0

----

I would like the IntelliJ Dart plugin to improve the extraction of a [variable](https://youtrack.jetbrains.com/issue/WEB-24470). Since the analysis server needs to support it first, then that means I'm asking the Dart team to help improve the tooling for Dart developers.

**Comment by alexander-doroshko** [comment] 2019-04-10 06:53
@vsmenon, I don't think `area-intellij` is the right label here. 'Extract variable' refactoring is implemented on the Analysis Server end, so changes should be done on the server end as well.

**Comment by srawlins** [comment] 2021-07-20 03:57
Duplicate of https://github.com/dart-lang/sdk/issues/31701

**Closed by srawlins** 2021-07-20 03:57 UTC
Labels: P3, analyzer-refactoring, area-analyzer, type-enhancement
