### ISSUE TITLE
Analyzer hang on incomplete code "Future<List<>>"

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44477] opened 2020-12-15 15:19 UTC
This might be the same as #34850, but it seemed like that was believed to be fixed so I'm raising a new issue (feel free to close as a dupe if so). This was reported in https://github.com/Dart-Code/Dart-Code/issues/2865#issuecomment-743125081 and I can reproduce it on the latest nightly and it appears to get the analysis server stuck in an infinite loop.

I'm testing with the code:

```
Future<List<>>
```

I put it into an arbitrary test ('analysis_Server/test/lsp/format_test.dart'):

```
@soloTest
Future<void> test_danny() async {
  const contents = '''
Future<List<>>
''';
  await initialize();
  await openFile(mainFileUri, contents);

  await formatDocument(mainFileUri.toString());
}
```

The test doesn't fail, but this error occurs asynchronously:

<img width="1623" alt="Screenshot 2020-12-15 at 15 13 13" src="https://user-images.githubusercontent.com/1078012/102233353-19232300-3ee8-11eb-9787-fdddef6055c7.png">

It's throwing here because of the assert, but when you reproduce it in a normal release build it appears to get the server stuck in an infinite loop (edit: if I run the same test without asserts from the command, it does indeed get stuck in a loop).

@bwilkerson @scheglov

**Comment by bwilkerson** [comment] 2020-12-15 16:27
@jensjoha This appears to be a parser issue. I suspect that the assert is being thrown because the `endToken` at that point is `>>` rather than `>`. We should also try to understand why there's an infinite loop when asserts are disabled and ensure that there aren't other conditions that would trigger the same behavior.

@scheglov The fact that the test passes and the assertion exception is thrown asynchronously is also concerning. It suggests that we might be missing an `await` somewhere (or perhaps an exception handler on a future).

**Comment by DanTup** [comment] 2020-12-15 16:34
> The fact that the test passes and the assertion exception is thrown asynchronously is also concerning.

I probably described that badly. This is because the code causing the error is not part of the formatting (which I was calling in the test to trigger this), but rather it occurs in the declarations code that runs outside of the format request (as part of the analysis that's running "in the background", triggered by starting the server).

**Comment by jensjoha** [comment] 2020-12-16 11:45
This is basically a duplicate of https://github.com/dart-lang/sdk/issues/42229 which I tried to fix with https://dart-review.googlesource.com/c/sdk/+/150521 back in June --- I'll try to revive that.

**Closed** 2021-01-11 09:55 UTC
Labels: P2, area-analyzer, area-front-end
