### ISSUE TITLE
HttpClient POST does not send body if request contains basic auth

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/sdk#28012] opened 2016-12-06 19:53 UTC
Hi folks,

I'm using Dart:io to connect to a remote server to send SOAP messages. In previous versions of their firmware, I was able to do this without any issues. That firmware used basic authentication through the URL. They have since updated their firmware.

The new Firmware uses Digest authentication and I am able to send a GET request without any issues. However when I issue a post request it times out after about 8 and 1/2 minutes with a Bad request.

Normally I would say this is due to the change in their firmware. However I am able to successfully complete the same request using cUrl from the command line.

Regretfully, I'm unable to provide access to the remote server, as it is on a security camera. However are there any tips or suggestions on how I can help to further diagnose this issue in the Dart SDK, since cUrl does work without any issues.

**Comment by butlermatt** [comment] 2016-12-06 20:23
To follow up, I do know that the remote server seems to be running gSOAP/2.7

**Comment by butlermatt** [comment] 2016-12-06 20:37
From what I can see from captured pcap files (Between curl and the dart posts) it seems like the Dart request never sends more than the headers. The post body doesn't show up in the requests, whereas it does in the curl post requests.

**Comment by a-siva** [comment] 2016-12-07 21:36
Is it possible to also compare the packets received back from the server between curl and the dart client.

We would require some kind of reproduction in order to diagnose the issue.

**Comment by butlermatt** [comment] 2016-12-07 21:41
I could provide the pcap files privately (due to potentially confidential information contained there in). But from my recollection, there was no response from the remote server after the Dart headers were received, as it seemed like the server was still waiting for the content body, whereas the curl example contained the body (plus a follow-up with the remainder of the body) and the server provided ack then the expected http response (eg, headers and the body contents)

**Comment by butlermatt** [comment] 2016-12-08 14:28
HI @a-siva Just to follow up, looking at the pcap again.

Process for curl:
After the initial handshake, curl sends the headers (without the authentication digest), and specifically with content-length 0.
The remote server sends and ack packet for that.
The remote server sends 401 unauthorized response (with body).
Mac sends back an ack for that.
Curl then sends the headers (including digest authentication) and body of the request to the remote server (two packets)
Remote server sends an ack packet.
Remote server sends the Http response (headers and soap body).
They close the connection.

On the dart side:
After initial handshake, Dart sends headers (without authentication digest) to server.
Server sends ack.
Server sends 401 unauthorized response (with body).
Dart sends headers again (without digest authentication and without transfer-encoding header).
Server sends ack and 401 response again (with headers and body)
Mac sends ack for that packet.
Dart sends headers again, with digest authentication headers, content-length 0 still.
Server sends ack packet.
No further communication from Dart.

**Comment by butlermatt** [comment] 2016-12-09 21:04
I managed to create a small reproduction here with Shelf for a server and a very basic client.

https://github.com/butlermatt/basic-error

Start the server running.
Load localhost:8080 in the browser. See that it does stuff (eg basic auth) Credentials are "test" and "test"
Run the client. See that it does authenticate, however it does not post the body (that in writeln) same if you use the add. That data is never posted as the body of the request.

**Comment by HannoOttens** [comment] 2018-08-09 11:17
No fix for this yet?

**Comment by jonasfj** [comment] 2018-08-09 14:22
In your example you are using `HttpClient.authenticate`, this means that the `HttpClient` will attempt the request without an `'authorization'` header resulting in a failure. After which the `HttpClient` will call callback assigned to `HttpClient.authenticate`, which is where you set the `'authorization'` header.

Hence, you are actually doing two requests, but only sending the body once. Since the body is streaming the `HttpClient` can't just blindly assume it's of a size that can be buffered. Thus, the body isn't attached to the second request which does include the `'authorization'` header.

The solution for you is to do as follows:
```dart
var client = HttpClient();
var creds = HttpClientBasicCredentials("username", "password");
var u = Uri("https://example.com/mypath");
client.addCredentials(u, "", creds):

var req = await client.postUrl(u);
req.write("hello-world");

var res = await req.close();
var result = await utf8.decodeStream(res);
print(result):

client.close();
```

In this case you are setting the `'authorization'` header upfront, hence, the `HttpClient` will only making one request. It's also possible that it's better to use the [`http` package](https://pub.dartlang.org/packages/http) from pub, it might be more high-level.


-----

I think this behavior appears slightly surprising. Considering that the [documentation for `HttpClient.authenticate`](https://api.dartlang.org/stable/2.0.0/dart-io/HttpClient/authenticate.html) says:
> If the Future completes with true the request will be retried using the updated credentials. Otherwise response processing will continue normally.

When in practice the request can't be retried, because the body is streaming. It might an idea to remove the `HttpClient.authenticate` property, or forbid it's use for anything other than `HEAD` and `GET` -- similar to how we forbid automatically following redirects for anything other than `HEAD` and `GET`.
But given that this has been stable for a long time, it might be preferable to update the documentation with appropriate warnings and examples.

I'll admit that useful use cases for  `HttpClient.authenticate` alludes me at this moment, but I'm also pretty new to dart, so maybe this is an opportunity to learn something :)

**Comment by jonasfj** [comment] 2018-08-09 15:14
Documentation update: https://dart-review.googlesource.com/c/sdk/+/69161

**Closed** 2018-08-13 12:31 UTC
Labels: area-library, library-io

**Comment by aaulia** [comment] 2019-02-02 09:32
Hello,

Is there any plan to actually fix this? Coming from kotlin with OkHttp, `HttpClient.authenticate` provide similar feature as [Authenticator](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Authenticator.html). It really streamline and simplify (re)authentication process to a single spot.

@jonasfj 

> I'll admit that useful use cases for HttpClient.authenticate alludes me at this moment, but I'm also pretty new to dart, so maybe this is an opportunity to learn something :) 

From the above OkHttp Authenticator documentation  

> Performs either **preemptive authentication** before connecting to a proxy server, or **reactive authentication** after receiving a challenge from either an origin web server or proxy server.  

The later is really useful in handling refresh token grant type authentication.

**Comment by jonasfj** [comment] 2019-02-04 09:54
> The later is really useful in handling refresh token grant type authentication.

If you send a POST request with a body and get an authentication challenge from the server after you started streaming the body (because why wouldn't you start sending body immediately), then you can't send the body again, because the body is a stream, and streams can't be restarted.

You could buffer the body in-memory, but then you run out of memory when someone uploads a large file...

So we would need to use some form of restartable stream... I'm not saying it's a bad idea, just that when the body is a stream, retrying the request is not necessarily an option.
