### ISSUE TITLE
 Failed to handle request: id: 5, method: analysis.setAnalysisRoots

### ISSUE THREAD

**Issue by sahandevs** [dart-lang/sdk#39129] opened 2019-10-26 06:44 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.7.0-edge.6354b0b97dced6c0cdee8f22009b4351f0095d75`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```

Dart analysis server, SDK version 2.7.0-edge.6354b0b97dced6c0cdee8f22009b4351f0095d75, server version 1.27.3, FATAL error: Failed to handle request: {id: 5, method: analysis.setAnalysisRoots, params: {included: [C:\Users\*\Documents\GitHub\OSC\flutter\dev\bots, C:\Users\*\Documents\GitHub\OSC\flutter\examples\catalog, C:\Users\*\Documents\GitHub\OSC\flutter\dev\benchmarks\complex_layout, C:\Users\*\Documents\GitHub\OSC\flutter\dev\devicelab, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_driver, C:\Users\*\Documents\GitHub\OSC\flutter\examples\flutter_gallery, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_localizations, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_test, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools, C:\Users\*\Documents\GitHub\OSC\flutter\examples\flutter_view, C:\Users\*\Documents\GitHub\OSC\flutter\examples\platform_view, C:\Users\*\Documents\GitHub\OSC\flutter\examples\hello_world, C:\Users\*\Documents\GitHub\OSC\flutter\examples\layers, C:\Users\*\Documents\GitHub\OSC\flutter\dev\manual_tests, C:\Users\*\Documents\GitHub\OSC\flutter\examples\platform_channel, C:\Users\*\Documents\GitHub\OSC\flutter\examples\platform_channel_swift, C:\Users\*\Documents\GitHub\OSC\flutter\examples\stocks, C:\Users\*\Documents\GitHub\OSC\flutter\dev\tools], excluded: [C:\Users\*\Documents\GitHub\OSC\flutter\.idea, C:\Users\*\Documents\GitHub\OSC\flutter\dev\bots\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\dev\bots\build, C:\Users\*\Documents\GitHub\OSC\flutter\examples\catalog\.idea, C:\Users\*\Documents\GitHub\OSC\flutter\examples\catalog\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\examples\catalog\build, C:\Users\*\Documents\GitHub\OSC\flutter\dev\benchmarks\complex_layout\.idea, C:\Users\*\Documents\GitHub\OSC\flutter\dev\benchmarks\complex_layout\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\dev\benchmarks\complex_layout\build, C:\Users\*\Documents\GitHub\OSC\flutter\dev\devicelab\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\dev\devicelab\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_driver\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_driver\build, C:\Users\*\Documents\GitHub\OSC\flutter\examples\flutter_gallery\.idea, C:\Users\*\Documents\GitHub\OSC\flutter\examples\flutter_gallery\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\examples\flutter_gallery\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_localizations\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_localizations\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_test\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_test\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_test\test\test_config\project_root\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_test\test\test_config\project_root\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\asset_test\font\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\asset_test\font\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\asset_test\main\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\asset_test\main\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\asci_casing\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\asci_casing\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\bad_import\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\bad_import\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\bad_package\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\bad_package\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\bad_path\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\bad_path\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\changed_sdk_location\.pub, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\data\dart_dependencies_test\changed_sdk_location\build, C:\Users\*\Documents\GitHub\OSC\flutter\packages\flutter_tools\test\da...

```

For additional log information, please append the contents of
file://C:\Users\*\AppData\Local\Temp\report.txt.

**Comment by devoncarew** [comment] 2019-10-28 03:32
dupe of https://github.com/dart-lang/sdk/issues/38853

**Closed by devoncarew** 2019-10-28 03:32 UTC
