### ISSUE TITLE
Analyzer thinks that `Equality.hash` override is renaming a parameter from `Object.hash`

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#46477] opened 2021-06-26 03:24 UTC
Starts after https://github.com/dart-lang/sdk/commit/83376bf1ee81607a182f8558b242f1c9f4883246

More context in https://github.com/flutter/flutter/pull/85364

I tried to reproduce this in a smaller project but could not.

@pq @bwilkerson

**Comment by dnfield** [comment] 2021-06-26 03:26
Possible duplicate of https://github.com/dart-lang/sdk/issues/31201?

**Comment by bwilkerson** [comment] 2021-06-26 16:31
@scheglov

**Comment by scheglov** [comment] 2021-06-28 17:17
@dnfield what was a non-small project on which it can be reproduced? I tried to remove the corresponding `// ignore` in `dev/integration_tests/web/lib/stack_trace.dart:156`, but even then `flutter/dev/integration_tests/web` can be analyzed without diagnostics.

**Comment by scheglov** [comment] 2021-06-28 17:22
@dnfield Actually, I see that the lint is reported when I debug. But for some reason it is not printed by analyzer CLI. So, I don't need anything from you at the moment. Thanks :-)

**Comment by scheglov** [comment] 2021-06-28 17:42
OK, I see that `ClassElement.lookUpInheritedMethod()` uses `ClassElement.getMethod()` and does not check whether the method is static. This is a quite old code. We probably should rewrite it using `InheritanceManager3`, which skips static members.

**Comment by scheglov** [comment] 2021-06-28 19:15
https://dart-review.googlesource.com/c/sdk/+/205180

**Comment by scheglov** [comment] 2021-06-28 20:35
@pq @bwilkerson What is the expected way `avoid_renaming_method_parameters` should work when you implement an interface and so that you strongly speaking don't "override" the method. Should we still report the lint? 

```dart
class A {
  void foo(int a) {}
}
class B implements A {
  void foo(int a2) {}
}
```

What if the method is declared both in the superclass, and an implemented interface, and the name in the override is not the same as in (1) the superclass, (2) the interface?

```dart
class A {
  void foo(int a1) {}
}
class B {
  void foo(int a2) {}
}
class C extends A implements B {
  void foo(int a3) {}
}
```

One issue with `ClassElement.lookUpInheritedMethod()` is that it returns you just one, the most specific element, not all of them. For all overridden elements we need to use `InheritanceManager3.getOverridden2()`. My CL loosely keeps status quo, but I wonder if that status quo is satisfactory.

**Comment by bwilkerson** [comment] 2021-06-28 21:32
> Should we still report the lint?

The rationale for the lint reads (emphasis mine):

> Methods that override another method, but do not have their own documentation
> comment, _will inherit the overridden method's comment when dartdoc produces
> documentation_. If the inherited method contains the name of the parameter (in
> square brackets), then dartdoc cannot link it correctly.

If the issue is doc comments copied from elsewhere, and if `dartdoc` copies comments from interfaces (which I believe that it does), then it should also flag methods that aren't technically overrides but do implement a method inherited from an interface.

> What if the method is declared both in the superclass, and an implemented interface, and the name in the override is not the same as in (1) the superclass, (2) the interface?

Then I suppose it ought to compare against the method from which the doc comment will be copied. I'm guessing that `dartdoc` would copy from (1) before (2).

**Comment by scheglov** [comment] 2021-06-28 22:00
It seems (from my experiment, not from looking into the implementation) that `dartdoc` always copies from the superclass, so if the superclass does not have the doc comment, it is not copied from the interface. Hm... Maybe my change to `InheritanceManager3` was too radical. It changes the behavior of the method.

I guess we could just fix `ClassElement.lookUpInheritedMethod()` to skip static methods.

It still feels somewhat unsatisfactory, because I cannot put a finger on what `lookUpInheritedMethod` should return. It is not the thing that would be invoked with `super.foo()`, because that should be concrete. It is just whatever is the closest in the superclass hierarchy. Or maybe "why" it returns whatever it returns, because it is not in the spec. But we decided that it is something useful for clients.

Anyway, my change it not right, because formally it breaks API. I will rework it to be a fix.

**Comment by bwilkerson** [comment] 2021-06-28 22:15
> ... it is not copied from the interface.

@jcollins-g Is that really the expected behavior? In the analyzer code base we tend to treat implementations of methods from interfaces as overrides (in the sense of not repeating the doc comment).

> ... I cannot put a finger on what `lookUpInheritedMethod` should return.

It was probably intended to return a value that made sense in Dart 1 (or even earlier) that no longer makes sense. It's possible that we should deprecate it in favor of more specific lookup methods, but I'd have to look at where it's being used to have a concrete suggestion for what those would be.

> Or maybe "why" it returns whatever it returns ...

Server might well be using it to copy doc comments for things like hovers. I would expect that doc lookup wouldn't care whether the nearest overridden method were abstract, only whether it has a comment.

**Comment by scheglov** [comment] 2021-06-28 23:54
I landed the fix as https://dart-review.googlesource.com/c/sdk/+/205180.

We seem to use some of these methods for recovery.

`analysis_server` copies documentation from implemented interfaces for hover, not only from superclass.

**Comment by jcollins-g** [comment] 2021-06-29 01:41
> It seems (from my experiment, not from looking into the implementation) that `dartdoc` always copies from the superclass, so if the superclass does not have the doc comment, it is not copied from the interface. Hm... Maybe my change to `InheritanceManager3` was too radical. It changes the behavior of the method.
> 
> I guess we could just fix `ClassElement.lookUpInheritedMethod()` to skip static methods.
> 
> It still feels somewhat unsatisfactory, because I cannot put a finger on what `lookUpInheritedMethod` should return. It is not the thing that would be invoked with `super.foo()`, because that should be concrete. It is just whatever is the closest in the superclass hierarchy. Or maybe "why" it returns whatever it returns, because it is not in the spec. But we decided that it is something useful for clients.
> 
> Anyway, my change it not right, because formally it breaks API. I will rework it to be a fix.

The new lookup code is going to copy documentation like the old one, but

**Comment by jcollins-g** [comment] 2021-06-29 02:05
(clicked the wrong button, sorry for close/reopen)

> > ... it is not copied from the interface.
> 
> @jcollins-g Is that really the expected behavior? In the analyzer code base we tend to treat implementations of methods from interfaces as overrides (in the sense of not repeating the doc comment).

I am not sure I understand the question.  Documentation should be copied from the interface, just as it would be copied from a superclass implementation.  Dartdoc is supposed to follow the inheritance chain and stop at the first supertype that has documentation for a method, e.g.:

```dart
abstract class A {
  /// I have documentation
  void method();
}

class B implements A {
   @override
   void method() {
     // I have an implementation but no doc comment
   }
}

class C extends B {
   /// I have an implementation and a doc comment
   @override
   void method() {}
}
```
Here, `C.method` should have its own documentation, and `B.method` should have `A.method`'s documentation.  If it doesn't, that's a bug.

The old lookup code would render `A.method`'s doc for `B.method` in `B`'s context.   This worked well when referring to member variables, but not to parameters or the defining namespace for A, and so forth.  

The new lookup code is "smarter" in that it looks up in the context documented first, but if it can't find something there, looks up via the defining context.    This lessens the need for a lint slightly, as Dartdoc will now know what you meant instead of emitting an unresolved-doc-reference warning, but it still would look better to the user if they didn't do that.

As an aside, documentation inheritance behavior is another of the ambiguous scoping problems in dartdoc that I'm hoping will be possible to address eventually...

> 
> > ... I cannot put a finger on what `lookUpInheritedMethod` should return.
> 
> It was probably intended to return a value that made sense in Dart 1 (or even earlier) that no longer makes sense. It's possible that we should deprecate it in favor of more specific lookup methods, but I'd have to look at where it's being used to have a concrete suggestion for what those would be.
> 
> > Or maybe "why" it returns whatever it returns ...
> 
> Server might well be using it to copy doc comments for things like hovers. I would expect that doc lookup wouldn't care whether the nearest overridden method were abstract, only whether it has a comment.

+1.

**Comment by scheglov** [comment] 2021-06-29 20:14
Similar fixes for other `ClassElement` methods.
https://dart-review.googlesource.com/c/sdk/+/205360

**Closed** 2021-06-30 21:51 UTC
Labels: P1, area-analyzer
