### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by zeienko-vitalii** [dart-lang/sdk#38103] opened 2019-08-29 16:10 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6262.58`
- `2.4.0`
- `IU-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2560x1080, 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:389:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1370:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4239:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3898:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5307:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3715:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#23     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3441:13)
#24     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3373:13)
#25     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4315:16)
#26     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4274:14)
#27     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#28     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#29     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#30     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#31     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#32     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#33     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#34     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#35     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#36     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#37     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#38     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#39     Parser.parseReturnStatement (package:front_end/src/fasta/parser/parser.dart:3840:13)
#40     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3723:14)
#41     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3705:20)
#42     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3610:15)
#43     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3441:13)
#44     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3373:13)
#45     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4315:16)
#46     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4274:14)
#47     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#48     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#49     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#50     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5007:15)
#51     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4979:12)
#52     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4960:14)
#53     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4939:13)
#54     Parser.parseSendOrFunctionLiteral (package:...
```

For additional log information, please append the contents of
file:///private/var/folders/jh/qysqvh_d0xs9g8k49jfyxpc80000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-08-30 18:36
Thanks for reporting this issue! It's been previously reported at #37114, so please follow along there.

**Comment by srawlins** [comment] 2019-08-30 18:36
Duplicate of #37114

**Closed by srawlins** 2019-08-30 18:36 UTC
Labels: analyzer-crash-report, analyzer-server, area-analyzer, type-bug
