### ISSUE TITLE
Flaky failure of standalone_2/io/named_pipe_script_test

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#31226] opened 2017-10-26 08:10 UTC
Build bot log: https://build.chromium.org/p/client.dart/builders/vm-mac-product-x64-be/builds/9892
```FAILED: none-vm product_x64 standalone_2/io/named_pipe_script_test
Expected: Pass
Actual: RuntimeError
--- Command "vm" (took 380ms):
DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --reify-generic-functions --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-product-x64-be/build/sdk/.packages /b/build/slave/vm-mac-product-x64-be/build/sdk/tests/standalone_2/io/named_pipe_script_test.dart
stdout:
unittest-suite-wait-for-done
stderr:
Unhandled exception:
Expect.fail('Unable to find 'main' in root library '/dev/fd/0'
')
#0      Expect._fail (package:expect/expect.dart:504:5)
#1      Expect.fail (package:expect/expect.dart:183:5)
#2      main.<anonymous closure> (file:///b/build/slave/vm-mac-product-x64-be/build/sdk/tests/standalone_2/io/named_pipe_script_test.dart:38:14)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#6      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#7      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#8      _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#9      _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#10     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#11     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#12     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#13     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#17     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:770)
#18     _StreamController._add (dart:async/stream_controller.dart:641)
#19     _StreamController.add (dart:async/stream_controller.dart:587)
#20     _Socket._onData (dart:io-patch/socket_patch.dart:1647)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#24     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:770)
#25     _StreamController._add (dart:async/stream_controller.dart:641)
#26     _StreamController.add (dart:async/stream_controller.dart:587)
#27     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#28     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#31     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:111)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:164)
--- Re-run this test:
python tools/test.py -m product standalone_2/io/named_pipe_script_test
```

**Comment by karlklose** [comment] 2017-11-23 11:58
This happened again today: https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-mac-product-x64-be%2F10564%2F%2B%2Frecipes%2Fsteps%2Fvm_tests%2F0%2Fstdout

**Comment by mraleph** [comment] 2018-11-27 12:21
Duplicate of #28737

**Closed by mraleph** 2018-11-27 12:21 UTC
Labels: area-infrastructure
