### ISSUE TITLE
dartdoc failure on NNBD unfork CL

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#41470] opened 2020-04-13 22:58 UTC
The unfork CL is here: https://dart-review.googlesource.com/c/sdk/+/138902

The bot that's failing is dart-sdk-linux-try: https://ci.chromium.org/p/dart/builders/try/dart-sdk-linux-try/391?

The step that's failing is "build API docs".

The detailed log from the failure is here: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8883164579862675424/+/steps/build_api_docs/0/stdout

**Comment by stereotype441** [comment] 2020-04-13 23:01
@jcollins-g @srujzs FYI

**Comment by srujzs** [comment] 2020-04-14 01:07
Started looking into this, the build fails repeatedly at metadata.dart. It isn't obvious to me why the dartdoc in there would cause this failure, and removing all dartdoc in that file produces the same failure.

**Comment by jcollins-g** [comment] 2020-04-14 15:51
This is a structural issue; dartdoc is confused about information it is receiving from the analyzer and its parallel data structures can't be built.

**Comment by jcollins-g** [comment] 2020-04-14 16:13
I can reproduce the issue only using the head analyzer; analyzer 0.39.6 works fine.  With asserts enabled dartdoc throws a little earlier.

**Comment by jcollins-g** [comment] 2020-04-14 16:44
Where we throw is while dartdoc is attempting to construct `Field` objects for inherited objects of dart:async's `_SyncStreamControllerDispatch`.  (Yes, this is a private class and not documented, but dartdoc needs to know about it because via inheritance documented objects rely on it).  

An analyzer `PropertyAccessorElementImpl` is returning null when we try to access its' variable.  The element's location is `dart:async;dart:async/stream_controller.dart;_SyncStreamControllerDispatch;done?`

**Comment by jcollins-g** [comment] 2020-04-14 16:55
Very rough reproduction instructions:

1) build and install NNBD sdk (so command line `dart` is the NNBD SDK dart)
2) ```git clone https://github.com/dart-lang/dartdoc.git && cd dartdoc```
3) Add the following to  the end of `pubspec.yaml` (referencing a checked out NNBD SDK)

```
dependency_overrides:
  analyzer:
    path: '../sdk/sdk/pkg/analyzer'
  _fe_analyzer_shared:
    path: '../sdk/sdk/pkg/_fe_analyzer_shared'
```
4) Run `pub get`
5) Run `grind build-sdk-docs`

you will see exception.  The null is most easily visible before the call to `Class.addSingleField`.

**Comment by scheglov** [comment] 2020-04-14 20:08
I think this https://dart-review.googlesource.com/c/sdk/+/143382 will fix the issue.

**Comment by jcollins-g** [comment] 2020-04-14 20:37
Double checking now; will close assuming patching the unfork works for me after the landed CL.

**Comment by jcollins-g** [comment] 2020-04-14 20:50
Confirmed; this eliminates the null variable when running dartdoc with head analyzer on the NNBD unfork.  Closing issue.

**Closed by jcollins-g** 2020-04-14 20:50 UTC
Labels: P1, area-analyzer
