### ISSUE TITLE
Files that apply macros can give spurious errors about non-allowable part-of directives

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#54713] opened 2024-01-23 22:57 UTC
![image](https://github.com/dart-lang/sdk/assets/984921/594fb6db-4a06-44f1-9ae3-e623b58fb2b7)

Continually editing a macro eventually will get you in this state, I have seen it a few times. Once you get in this state, you have to restart the analysis server to get out of it.

I just reproduced this by editing the JSON language test macro to add extra spaces before a semicolon, to see how the performance was. I tried adding spaces, removing them, then adding more.

**Comment by scheglov** [comment] 2024-01-24 01:40
I can reproduce this in VS Code, by typing (spaces) fast in the macro implementation file.

The outside manifestation also was about `part-of directives`.
Looking into logs, there was an exception here.
https://github.com/dart-lang/sdk/blob/7fd8d79e9113220caef60d253bd8067abbfa3ac0/pkg/analyzer/lib/src/summary2/constructor_initializer_resolver.dart#L32

Although this still does not explain me why it happens.
Probably some async race condition.

```log
library augment 'test.dart';

import 'file:///Users/scheglov/dart/test/bin/json_serializable.dart' as prefix0;
import 'dart:core' as prefix1;

augment class User {
  @prefix0.FromJson()
  User.fromJson(prefix1.Map<prefix1.String, prefix1.Object?> json);
  @prefix0.ToJson()
  prefix1.Map<prefix1.String, prefix1.Object?> toJson();
  augment User.fromJson(prefix1.Map<prefix1.String, prefix1.Object?> json, )  : this.age = json["age"] as                  prefix1.int,
this.name = json["name"] as                  prefix1.String{}
  augment prefix1.Map<prefix1.String, prefix1.Object?> toJson()  => {
    'age': this.age,
    'name': this.name,
  };
}
..o...Null check operator used on a null value
#0      ConstructorInitializerResolver.resolve (package:analyzer/src/summary2/constructor_initializer_resolver.dart:32:39)
#1      LibraryBuilder.resolveConstructors (package:analyzer/src/summary2/library_builder.dart:578:50)
#2      Linker._resolveConstructors (package:analyzer/src/summary2/link.dart:386:15)
#3      Linker._buildOutlines (package:analyzer/src/summary2/link.dart:232:5)
<asynchronous suspension>
#4      Linker.link (package:analyzer/src/summary2/link.dart:102:5)
<asynchronous suspension>
#5      link (package:analyzer/src/summary2/link.dart:40:3)
<asynchronous suspension>
#6      LibraryContext.load.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:195:24)
<asynchronous suspension>
#7      LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:255:7)
```

**Comment by scheglov** [comment] 2024-01-24 01:58
And I cannot reproduce it in IntelliJ, where I don't see the generated file.
Maybe the way we ask its content causes something to break?

**Comment by scheglov** [comment] 2024-01-24 02:18
And even in VS Code, if I don't open the generated file, then it does not break.
So, it is either operations that we use to get the content, or the timing changes that happen because of these operations.

**Comment by scheglov** [comment] 2024-01-24 03:10
OK, I probably found it.
We ask for `FileState` for the `*.macro.dart` file while doing some LSP operations.
This creates it with unexpected content.
A solution is to force-refresh the `FileState` with the required content during linking.

**Comment by scheglov** [comment] 2024-01-24 21:02
[Kapture 2024-01-24 at 12.58.38.webm](https://github.com/dart-lang/sdk/assets/384794/e6860b13-c02f-442d-bb9f-e42339a5f6c7)

**Comment by jakemac53** [comment] 2024-01-24 21:15
@scheglov am I seeing cached results mostly there? it seems too fast 🤣

**Comment by scheglov** [comment] 2024-01-24 21:42
Yes, after the first round of spaces, you always get it cached.
https://dart-review.googlesource.com/c/sdk/+/348202 is implementation that fixes the race.

**Comment by bwilkerson** [comment] 2024-01-25 17:32
@DanTup 

> We ask for `FileState` for the `*.macro.dart` file while doing some LSP operations.
> This creates it with unexpected content.

What operations?

I'd like to understand whether this is a bug in the LSP operations, a problem with how we're handling `FileState`s, or an unavoidable aspect of the way macros interact with the analyzer. Fixing the race condition might be the right solution, but I can't tell that without more information.

**Comment by jakemac53** [comment] 2024-01-25 17:48
As far as I can tell for pretty much every character I type in a macro file, it starts immediately trying to re-compile and re-execute that macro where it is applied. Which, isn't surprising really but if we do have some control over it, we may want to slow down a bit the rate at which we do that. Possibly, we can just do some debouncing of these file change requests in macro libraries? Or at least the macro re-compilation aspect.

**Comment by scheglov** [comment] 2024-01-25 17:50
@bwilkerson I invited you to the meeting dedicated to discussing this issue, and the fix.

**Comment by scheglov** [comment] 2024-01-27 02:33
The fix landed.

**Closed by scheglov** 2024-01-27 02:33 UTC
Labels: area-analyzer, P2, feature-macros
