### ISSUE TITLE
Crash in analyzer, access denied exception from package:watcher

### ISSUE THREAD

**Issue by xiongwenzhi** [dart-lang/sdk#36094] opened 2019-03-04 03:45 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-171.4443003`
- `2.1.0-dev.9.4`
- `AI-171.4443003, JRE 1.8.0_152-release-915-b01x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Administrator\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\asDemo\flutter-login-home-animation\nxt_flutter_app], excluded: [D:\asDemo\flutter-login-home-animation\nxt_flutter_app\.idea, D:\asDemo\flutter-login-home-animation\nxt_flutter_app\.dart_tool, D:\asDemo\flutter-login-home-animation\nxt_flutter_app\.idea, D:\asDemo\flutter-login-home-animation\nxt_flutter_app\.pub, D:\asDemo\flutter-login-home-animation\nxt_flutter_app\build]}, clientRequestTime: 1551660683840}
FileSystemException: Exists failed, path = 'D:\asDemo\flutter-login-home-animation\nxt_flutter_app\build\app\intermediates\merged_assets\debug\mergeDebugAssets\out\flutter_assets\packages\cupertino_icons\assets' (OS Error: 拒绝访问。
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by lrhn** [comment] 2019-03-04 06:22
According to Google translate "拒绝访问" means "access denied". We have seen this error before.
The analyzer needs to catch this error, or predict when it will happen, to avoid crashing.

**Comment by srawlins** [comment] 2019-09-06 15:56
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/33106; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 15:56
Duplicate of https://github.com/dart-lang/sdk/issues/33106

**Closed by srawlins** 2019-09-06 15:56 UTC
Labels: analyzer-crash-report, area-analyzer, os-windows, type-bug
