### ISSUE TITLE
No way to restart the DartVM after shutdown

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/sdk#32990] opened 2018-04-26 16:18 UTC
There must be a bug on this.  But I didn't see one.

This makes it so that Flutter can't go back to using 0 memory when the last FlutterView is closed which at least a couple folks have complained about.  See https://github.com/flutter/flutter/issues/16995.

**Comment by mraleph** [comment] 2018-04-26 16:41
Duplicate of #21106

**Closed by mraleph** 2018-04-26 16:41 UTC
Labels: area-vm
