### ISSUE TITLE
FFI regression after Dart 2.14-0.74.0.dev

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#46004] opened 2021-05-13 05:42 UTC
I'm seeing something weird that looks like it might be an FFI regression in recent Dart builds. 

The following code runs fine in Dart 2.14.0-74.0.dev and has done for many releases:
https://github.com/timsneath/win32/blob/ffi-regression/example/wallpaper.dart

It should print out the filename of the current desktop wallpaper on Windows 10, for example:

```
[C:\src\win32] dart example\wallpaper.dart
Wallpaper path is: C:\Users\tim\AppData\Local\Packages\Microsoft.Windows.Photos_8wekyb3d8bbwe\LocalState\PhotosAppBackground\01815_sunsetneedlev2_2560x1600.jpg
```

Somewhere between this build and Dart 2.14.0-90.0.dev, it stopped working, and instead the process just fails with exit code 1.

This can be evidenced by a GitHub Actions job like the following test suite run, which runs successfully on older builds, but not on the latest Dart `main` build:
https://github.com/timsneath/win32/runs/2562872364?check_suite_focus=true

It's _possible_ there's something wrong with my own code, which recent builds of Dart are for the first time exposing, but I can't figure out what is going wrong. 

If I debug the code, it exits while trying to retrieve the `ptr.ref.vtable.elementAt(4).value` property in the line below:

```dart
  int GetWallpaper(
          Pointer<Utf16> monitorID, Pointer<Pointer<Utf16>> wallpaper) =>
      Pointer<NativeFunction<_GetWallpaper_Native>>.fromAddress(
                  ptr.ref.vtable.elementAt(4).value)
              .asFunction<_GetWallpaper_Dart>()(
          ptr.ref.lpVtbl, monitorID, wallpaper);
```

I can't fathom why this would give a different result from different Dart builds, so I'm logging this as a bug in case it rings a bell for you about something that might either have caused a regression, or might point me at something that has changed.

Thanks in advance!

**Comment by dcharkes** [comment] 2021-05-18 13:47
The example program works fine in .85 but not in .90 from the [archive](https://dart.dev/tools/sdk/archive).

I landed 1 FFI commit in [between these versions](https://github.com/dart-lang/sdk/commits/dev?after=86c749398b3ace9707030dbda522e2d02aa90d34+0&branch=dev), so we have [a suspect commit](https://dart-review.googlesource.com/c/sdk/+/198281).

(I need to fix my Windows setup (SDK checkout, Goma, python, ..) in order to verify that this commit is indeed the cause and figure out what is wrong with it.)

**Comment by dcharkes** [comment] 2021-05-19 12:51
### Cause

By adding support for incremental compilation, we inadvertently started considering non-external getters as native fields. This caused them to be transformed and to be included in size calculation.

```dart
class COMObject extends Struct {
  external Pointer<IntPtr> lpVtbl;

  Pointer<IntPtr> get vtable => Pointer.fromAddress(lpVtbl.value);
}
```

`sizeOf<COMObject>()` turned 16 instead of 8.

Accessing `vtable` returned  value as if it was written as `external Pointer<IntPtr> vtable;`.

### Fix

Fix is under way: https://dart-review.googlesource.com/c/sdk/+/200640.

### Workaround

Change the `.vtable` into an extension method (requires imports on use sites) or method (requires adding `()` on use sites). cc @timsneath 

Or patiently wait til the fix lands.

And thanks for thoroughly testing the FFI with patterns that are missing in our own test suite! 😅

**Closed** 2021-05-20 13:13 UTC
Labels: area-library, library-ffi
