### ISSUE TITLE
Inferred type changed from "Null" to "bottom" between 2.3.0-dev.0.1 and 2.3.0-dev.0.3

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#36777] opened 2019-04-26 21:46 UTC
* Dart SDK Version 2.3.0-dev.0.3
* Linux
* Chrome

Between releases 2.3.0-dev.0.1 and 2.3.0-dev.0.3, Dart's inference of bottom changed, but I don't see a corresponding CHANGELOG entry with any explanation of this change.

AngularDart depends on this inference in an assertion here:
https://github.com/dart-lang/angular/blob/87800df91c38470c3b629859429eadd265a62b28/angular/lib/src/core/linker/app_view.dart#L580-L584

Previously when `F` and `E` were incompatible (the handler doesn't accept a type `F` that extends `E`), inference would type `F` as `Null`.

As of some version > 2.3.0-dev.0.1, this type is now inferred as `bottom` as demonstrated by this Travis failure: https://travis-ci.org/dart-lang/angular/jobs/525128959#L2017

Is there any documentation or explanation of this change? Is `bottom` a visible type? For example, can/should we change our assertion to `E == bottom || F != bottom`?

**Comment by kevmoo** [comment] 2019-04-26 21:50
CC @leafpetersen @stereotype441

**Comment by stereotype441** [comment] 2019-04-27 12:54
The only analyzer differences between 2.3.0-dev.0.1 and 2.3.0-dev.0.3 are in the Android manifest validator, so I'm guessing this is a front end issue.

CC @kmillikin

**Comment by alorenzen** [comment] 2019-04-29 21:19
This is blocking an external release of Angular, which was requested to fix https://github.com/dart-lang/sdk/issues/36724

**Comment by kevmoo** [comment] 2019-04-29 21:20
Have we determined this is indeed an FE issue? @kmillikin ?

**Comment by kmillikin** [comment] 2019-04-30 09:33
How do we run this test locally?  I cloned the angular repository with

```
git clone https://github.com/dart-lang/angular.git angular.git
```

I put a locally built 2.3.0-dev.0.3 SDK in my path

```
dart --version
Dart VM version: 2.3.0-dev.0.3 (Tue Apr 23 12:02:59 2019 -0700) on "linux_x64"
```

And I rant the tests with `travis.sh`:

```
PKG=_tests tool/travis.sh test
```
But it doesn't ever run that test from `test/core/linker/integration/outputs_test.dart`

**Comment by kmillikin** [comment] 2019-04-30 10:33
/cc @stefantsov @johnniwinther because there were some recent changes to `Null`, though they should all have been in 2.3.0-dev.0.1.

The commits that I can see that are in 2.3.0-dev.0.3 and not 2.3.0-dev.0.1 are:

04e1b0d976151cc6aa5dcc80667d568c95495c80
d8a0d68bd66b388e4c5f6dc38f4fd940a4cb88bc
1ecedb23416943b13fd3f48a5d398f2cfa6dbee4
2c304d997f08e9ba1d8d1af665522b31d695f19a
1f1592edce7122ff657d9538d58d9cce0cae46e6
cf4444b803a376bb1ad6442e1f09434a4d58167b

and I can't see how any of them indicate a change to handling of `Null`.

**Comment by leonsenft** [comment] 2019-04-30 15:46
@kmillikin

`pub run build_runner test -- test/core/linker/integration/outputs_test.dart`

**Comment by kmillikin** [comment] 2019-05-01 07:55
Thanks @leonsenft.  I still can't reproduce it locally:

```
kmillikin@belladonna:~/angular.git/_tests$ dart --version
Dart VM version: 2.3.0-dev.0.3 (Tue Apr 23 12:02:59 2019 -0700) on "linux_x64"
kmillikin@belladonna:~/angular.git/_tests$ pub run build_runner test -- test/core/linker/integration/outputs_test.dart 
[INFO] Generating build script...
[INFO] Generating build script completed, took 237ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 456ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 680ms

[INFO] Running build...
[INFO] Running build completed, took 317ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 294ms

[INFO] Creating merged output dir `/tmp/build_runner_testUESZHT/`...
[INFO] Creating merged output dir `/tmp/build_runner_testUESZHT/` completed, took 229ms

[INFO] Writing asset manifest...
[INFO] Writing asset manifest completed, took 9ms

[INFO] Succeeded after 918ms with 0 outputs (0 actions)

Running tests...

00:01 +6: All tests passed!                                             
```

**Comment by leonsenft** [comment] 2019-05-01 17:56
Ah sorry, you'll need to checkout out the pull request that's failing.

Clone the repo:
```
$ git clone git@github.com:angular/angular.git
$ cd angular
```

Fetch the pull request:
```
$ git fetch origin pull/1793/head:sync
$ git checkout sync
```

Upgrade the tests dependencies (note this brings in new versions of package:analyzer and package:kernel since master):
```
$ cd _tests/
$ pub upgrade
```
 
Running the test should now exhibit the aforementioned failure:
```
$ pub run build_runner test -- test/core/linker/integration/outputs_test.dart
```

**Comment by alorenzen** [comment] 2019-05-01 20:44
This should now be reproducible @ HEAD. We just merged the PR on red.

**Comment by vsmenon** [comment] 2019-05-02 18:30
Hmm, this could be a difference between analyzer (analyzer-based DDC) and CFE (kernel-based DDC).  We flipped webdev / build_web_compilers to the latter.  Neither are in the SDK - the SDK versions may be a red herring here.

This looks like a runtime test (presumably running on DDC) and an assert (hidden from dart2js, which would have CFE/kernel behavior).

What's the correct behavior here (`Null`, `bottom`)?

**Comment by sigmundch** [comment] 2019-05-02 18:49
> Hmm, this could be a difference between analyzer (analyzer-based DDC) and CFE (kernel-based DDC). We flipped webdev / build_web_compilers to the latter. 

I can confirm this is the case: switching to build_web_compilers to `< 2.0.0` (and overriding the analyzer dependency to be older to allow pub to solve the version constraints), makes the test pass.

**Comment by vsmenon** [comment] 2019-05-02 19:43
Okay, our tools are inconsistent here - I've confirmed.  Let me open a new bug.  This doesn't appear to be related to recent changes.

**Comment by vsmenon** [comment] 2019-05-02 19:48
@leonsenft - at the moment either `Null` or `bottom` can appear depending on which tool.  This isn't a recent regression in the SDK.

**Comment by vsmenon** [comment] 2019-05-02 19:57
Closing in favor of:

#36832

**Comment by leonsenft** [comment] 2019-05-02 19:57
@vsmenon with that in mind, I figured maybe we could change our assertion to check 

```
assert(E == Null || E == bottom || (F != Null && F != bottom));
```

but `bottom` doesn't appear to be a user-visible type.

**Closed by vsmenon** 2019-05-02 19:57 UTC
Labels: area-front-end

**Comment by leafpetersen** [comment] 2019-05-02 20:10
@leonsenft I think you could probably arrange to capture the type to compare against.  e.g.

```dart
Type capture<T>(T Function()) => T;

var bot = capture(() => throw "hello"); // captures whatever the system reifies bottom as
var nul = capture(() => null); // captures whatever the system reifies as Null
assert(E == nul || E == bot);
```
