### ISSUE TITLE
Can we add Not-Nullable types in Dart?

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/sdk#30676] opened 2017-09-12 13:24 UTC
Like in Kotlin or Fantom.
By default there variables can keep not-null value only. If you need var to keep null value, you should describe it like that:

    String? name = params?.name; // nullable
    String name = params?.name ?? "No name"; // must gets String values only
We can do that with @notnull annotation. Let's make variable throws error when gets null.

That would be really handy. Almost everywhere I want to make checks for null-value. It's annoying, makes code dense and verbose.

**Comment by floitschG** [comment] 2017-09-12 13:41
Duplicate of https://github.com/dart-lang/sdk/issues/22

**Comment by a-siva** [comment] 2017-09-13 17:03
Closing as this has been marked as a duplicate.

**Closed by a-siva** 2017-09-13 17:03 UTC
Labels: Resolution: duplicate
