### ISSUE TITLE
package:analyzer's listing in the in-memory file system has terrible performance for large amount of files

### ISSUE THREAD

**Issue by isoos** [dart-lang/sdk#47220] opened 2021-09-15 12:05 UTC
`package:analyzer` version `2.2.0` with Dart SDK `2.14.1`.

We are using the in-memory file system to temporary store the dartdoc-generated files on pub.dev. (The idea was to write a .tar.gz archive directly, instead of individual files). At the end of the process we've iterated over the files using `getChildren()` calls recursively. It turns out this is really inefficient for 100k+ files: takes more than 30 minutes (aborted process after that).

I've created the file list of the directory, attached as `list.txt.gz`. 
[list.txt.gz](https://github.com/dart-lang/sdk/files/7169842/list.txt.gz)

Recreating that with empty content and scanning the files with recursive `getChildren()` call should help to reproduce the issue.

**Comment by isoos** [comment] 2021-09-15 12:05
Related change in pub-dev that improved/fixed the performance issue: https://github.com/dart-lang/pub-dev/pull/5106

**Comment by asashour** [comment] 2021-09-15 14:22
If I may say something. I am unable to reproduce.  By extending [BaseTest](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/test/file_system/memory_file_system_test.dart#L28), the below gives milliseconds for `.getChildren()`

What could be wrong with the test scenario? 

```
Writing in 58 seconds
Getting in 360 millis
```


```dart
main() {
  defineReflectiveSuite(() {
    defineReflectiveTests(MemoryResourceProviderPerformanceTest);
  });
}

abstract class BaseTest extends FileSystemTestSupport {
...
}

@reflectiveTest
class MemoryResourceProviderPerformanceTest extends BaseTest {

  var chars = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
  var rnd = Random();
  String getRandomString(int length) => String.fromCharCodes(Iterable.generate(
      length, (_) => chars.codeUnitAt(rnd.nextInt(chars.length))));

  test_getChildren() {
    var filesCount = 100 * 1000;
    var contentLength = 12 * 1024;
    var stopwatch = Stopwatch()..start();

    var folder = provider.getFolder('C:\\');
    for (int i = 0; i < filesCount; i++) {
      getFile(exists: true, content: getRandomString(contentLength), filePath: 'C:\\$i');
    }
    print('Writing in ${stopwatch.elapsed.inSeconds} seconds');
    stopwatch.reset();

    for (var i in folder.getChildren()) {
      if (i is File) {
        i.path;
        i.readAsStringSync();
      }
    }
    print('Reading in ${stopwatch.elapsed.inMilliseconds} millis');
    stopwatch.stop();
  }
}
```

**Comment by isoos** [comment] 2021-09-16 07:47
@asashour: see the repro code below:

````dart
import 'dart:convert';
import 'dart:io';

import 'package:analyzer/file_system/file_system.dart';
import 'package:analyzer/file_system/memory_file_system.dart';
import 'package:http/http.dart' as http;

Future<void> main() async {
  final rs = await http.get(
      Uri.parse('https://github.com/dart-lang/sdk/files/7169842/list.txt.gz'));
  final lines = utf8.decode(gzip.decode(rs.bodyBytes)).split('\n');
  final provider = MemoryResourceProvider();
  for (final line in lines) {
    if (line.isEmpty) continue;
    final path = '/tmp/${line.substring(2)}';
    final f = provider.getFile(path);
    f.parent2.create();
    f.writeAsBytesSync([0, 1, 2]);
  }

  final sw = Stopwatch()..start();
  var count = 0;
  void scanFolder(Folder rs) {
    for (final c in rs.getChildren()) {
      if (c is Folder) {
        scanFolder(c);
      } else if (c is File) {
        count++;
        if (count % 100 == 0) {
          print('[${sw.elapsed}] $count');
        }
      }
    }
  }

  scanFolder(provider.getFolder('/tmp'));
  print(count);
  print(sw.elapsed);
}
````

**Comment by asashour** [comment] 2021-09-16 10:31
Thanks for your response.

The reason seem to come from the below loop, in which the logic iterates over all paths, and for each one if its parent is the current `path`, then add it as a child.

https://github.com/dart-lang/sdk/blob/4aa6373724302f852639af58fa53b541cef99a94/pkg/analyzer/lib/file_system/memory_file_system.dart#L605-L609

This would make recursive `.getChildren()` very heavy, as shown by your example.

One way to improve the performance, is by having a map of `String path, List<String> children`, however there could be better solutions.

**Comment by isoos** [comment] 2021-09-16 11:15
Also, as a low-hanging fruit, maybe `resource` could cache the lazily evaluated `dirname()` of its path?

**Comment by bwilkerson** [comment] 2021-09-16 14:33
@scheglov

**Comment by scheglov** [comment] 2021-09-16 15:12
Thank you, I see the problem.

**Comment by scheglov** [comment] 2021-09-16 20:22
https://dart-review.googlesource.com/c/sdk/+/213682

**Comment by scheglov** [comment] 2021-09-19 20:47
The fix was landed, I see about 200-300 ms to process the list.

**Closed by scheglov** 2021-09-19 20:47 UTC
Labels: area-analyzer, P3

**Comment by isoos** [comment] 2021-09-19 21:23
awesome, thanks!
