### ISSUE TITLE
dart2js crashes

### ISSUE THREAD

**Issue by pfif** [dart-lang/sdk#25329] opened 2016-01-02 12:38 UTC
I am trying to compile code and the following error message appears :

```
void main(){
     ^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (1.13.1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: bad position #246 in file video/static/video/video_bootstrap.dart with length 185.
#0      SourceFile.getLine (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/io/source_file.dart:91)
#1      SourceFile.getLocationMessage (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/io/source_file.dart:140)
#2      FormattingDiagnosticHandler.report (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/source_file_provider.dart:222)
#3      FormattingDiagnosticHandler.call (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/source_file_provider.dart:239)
#4      LegacyCompilerDiagnostics.report (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/old_to_new_api.dart:36)
#5      Compiler.callUserHandler.<anonymous closure> (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/apiimpl.dart:534)
#6      CompilerTask.measure (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/common/tasks.dart:55)
#7      Compiler.callUserHandler (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/apiimpl.dart:533)
#8      Compiler._reportDiagnosticMessage (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/apiimpl.dart:520)
#9      Compiler.reportDiagnostic (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/apiimpl.dart:505)
#10     _CompilerDiagnosticReporter.reportDiagnostic (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1679)
#11     _CompilerDiagnosticReporter.reportDiagnosticInternal (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1673)
#12     _CompilerDiagnosticReporter.reportWarning (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1625)
#13     TypeResolver.resolveTypeAnnotation.reportFailureAndCreateType (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/type_resolver.dart:140)
#14     TypeResolver.resolveTypeAnnotation (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/type_resolver.dart:158)
#15     ResolverVisitor.resolveTypeAnnotation (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/members.dart:3993)
#16     ResolverTask.resolveReturnType (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/resolution.dart:405)
#17     ResolverTask.resolveTypeAnnotation (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/resolution.dart:395)
#18     _CompilerResolution.resolveTypeAnnotation (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1974)
#19     PartialFieldList.computeType (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/parser/partial_elements.dart:298)
#20     VariableElementX.computeType (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/elements/modelx.dart:1598)
#21     MembersCreator.computeClassMembers.createMember (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/class_members.dart:198)
#22     LinkEntry.forEach (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/util/link_implementation.dart:120)
#23     ClassElementX.forEachLocalMember (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/elements/modelx.dart:2751)
#24     MembersCreator.computeClassMembers (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/class_members.dart:227)
#25     ClassMembersCreator.computeMembers (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/class_members.dart:552)
#26     MembersCreator.computeAllMembers (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/class_members.dart:79)
#27     ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon&TypeDeclarationElementX&PatchMixin&ClassMemberMixin.computeAllClassMembers (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/class_members.dart:903)
#28     MembersCreator.computeAllClassMembers (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/class_members.dart:537)
#29     ResolverTask.computeClassMembers (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/resolution.dart:655)
#30     ResolverTask.checkClass (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/resolution/resolution.dart:663)
#31     Enqueuer.processInstantiatedClass.<anonymous closure>.processClass (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:384)
#32     Enqueuer.processInstantiatedClass.<anonymous closure> (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:394)
#33     CompilerTask.measure (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/common/tasks.dart:55)
#34     Enqueuer.processInstantiatedClass (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:361)
#35     Enqueuer.registerInstantiatedType.<anonymous closure> (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:244)
#36     CompilerTask.measure (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/common/tasks.dart:55)
#37     Enqueuer.registerInstantiatedType (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:234)
#38     Setlet.forEach (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/util/setlet.dart:227)
#39     Enqueuer.applyImpact (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:221)
#40     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1102)
#41     _CompilerDiagnosticReporter.withCurrentElement (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1691)
#42     Compiler.emptyQueue.<anonymous closure> (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1101)
#43     QueueFilter.processWorkItem (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:1072)
#44     Enqueuer.forEach (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/enqueue.dart:769)
#45     Compiler.emptyQueue (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1100)
#46     Compiler.processQueue (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:1128)
#47     Compiler.compileLoadedLibraries (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:998)
#48     Compiler.runCompiler.<anonymous closure> (file:///tmp/tmpPzxpif/dart-1.13.1/dart/pkg/compiler/lib/src/compiler.dart:871)
#49     _RootZone.runUnary (dart:async/zone.dart:1149)
#50     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#51     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#52     _Future._completeWithValue (dart:async/future_impl.dart:376)
#53     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#55     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

Cheers,
Pfif

**Comment by pfif** [comment] 2016-01-02 12:45
I found why : 
In my code, I defined one attribute in my class this way : ```JSObject yt_player;``` instead of this way ```JsObject yt_player;```. It does work fine in Dartium.

**Comment by sigmundch** [comment] 2016-01-04 20:35
@pfif - by any chance is your code open source or can you share it with us so we can reproduce the error locally?

@johnniwinther - could you take a closer look?

It sounds like dart2js identified the typo but crashed trying to report the error message. I wonder why our internal invariant was broken, since it appears as if the file was shorter than what we thought. Some ideas:
 - we reported the error in the wrong file by mistake, or
 - we didn't recognize that the file uses a special encoding

If you can't share the code with us, one thing that could help us is to try to compile the app again (with the typo), but run dart2js with assertions enabled. You can do this by running in checked mode the dart vm that executes dart2js. For example, in linux you can do this by overriding the environment variable `DART_VM_OPTIONS` before calling dart2js:

```
DART_VM_OPTIONS=--checked dart2js main.dart
```

**Comment by johnniwinther** [comment] 2016-01-05 08:41
This is probably fixed by https://codereview.chromium.org/1513263002/ which is part of 1.14.0-dev.5.0

**Closed by johnniwinther** 2016-01-05 08:41 UTC
Labels: area-dart2js, dart2js-crash, priority-low
