### ISSUE TITLE
Issue with compiling a program to Windows exe from Linux

### ISSUE THREAD

**Issue by Inplex-sys** [dart-lang/sdk#52604] opened 2023-06-03 19:51 UTC
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* Compiler

* Dart SDK Version 
`Dart SDK version: 3.0.3 (stable) (None) on "linux_x64"`

I'm trying to compile a dart program from **Debian 11 x64** with **Windows** as `--target-os` 
Command: `dart compile exe dart_loader.dart --target-os windows`

The problem is that the input binary is not a **Windows** binary but a **Linux** binary 
Command: `dart_loader.exe: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped`

How can i do ?

**Comment by julemand101** [comment] 2023-06-03 21:12
Sounds like a duplicate of: https://github.com/dart-lang/sdk/issues/28617

**Comment by lrhn** [comment] 2023-06-03 21:14
It is a duplicate of #28617, if it's a request. If it's a question, the answer is that [you cannot](https://dart.dev/tools/dart-compile#:~:text=some%20known%20limitations%3A-,No%20cross%2Dcompilation%20support).

**Closed by lrhn** 2023-06-03 21:14 UTC
