### ISSUE TITLE
Dart analyer has terminated 

### ISSUE THREAD

**Issue by MJAN123** [dart-lang/sdk#40712] opened 2020-02-20 18:30 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version , FATAL error: FileSystemException: Exists failed, path = 'C:\Users\Muhammad Jan\AppData\Local\.dartServer\.instrumentation' (OS Error: The file or directory is corrupted and unreadable.
, errno = 1392)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:133:11)
#2      PhysicalResourceProvider.getStateLocation (package:analyzer/file_system/physical_file_system.dart:123:17)
#3      Driver._readUuid (package:analysis_server/src/server/driver.dart:879:43)
#4      Driver.start (package:analysis_server/src/server/driver.dart:491:15)
#5      main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\MUHAMM~1\AppData\Local\Temp\report4.txt.

**Comment by farheen21** [comment] 2020-02-22 06:29
Go to your setting.json file  and remove "_ _enable-completion-model"  I hope by doing this the error will remove

**Comment by srawlins** [comment] 2020-06-12 23:21
Thanks for reporting this issue! This has been previously reported at #37059.

**Comment by srawlins** [comment] 2020-06-12 23:21
Duplicate of #37059

**Closed by srawlins** 2020-06-12 23:21 UTC
Labels: analyzer-crash-report, area-analyzer
