### ISSUE TITLE
Stdin throws a StdInException after listening when re-enabling raw mode

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#49961] opened 2022-09-14 00:13 UTC
I.e. the following pattern:

```dart
import 'dart:io';

void main() async {
  try {
    // Enable "raw mode".
    stdin
      ..echoMode = false
      ..lineMode = false;
    stdout.writeln('Press any key to exit');
    await for (final keys in stdin) {
      return;
    }
  } finally {
    // Disable "raw mode".
    stdin
      ..echoMode = true
      ..lineMode = true;
  }
}
```

Produces:

```
Unhandled exception:
StdinException: Error setting terminal echo mode, OS Error: Bad file descriptor, errno = 9
#0      Stdin.echoMode= (dart:io-patch/stdio_patch.dart:85:7)
```

I could use FFI to work around this (?), but it seems like a bug.

(I can recreate this without using `await for` and without using `try { ... } finally { ... }` so I think it's unrelated)

**Comment by mraleph** [comment] 2022-09-14 06:58
I think this is working as intended. By the end of `await for (final keys in stdin) {` `stdin` is closed, so naturally you can't set any attributes on it anymore. Cancelling subscription (and closing) happens before `finally` is executed. 

I can think of two workarounds. One is to do `asBroadcastStream` on `stdin` or just do the mode restoration before `return`.

**Closed by mraleph** 2022-09-14 06:58 UTC
