### ISSUE TITLE
The getter 'iterator' was called on null in _protocolAvailableSuggestionSet

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#37728] opened 2019-08-04 02:44 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-191.7479.14`
- `2.4.0`
- `WS-191.7479.14, JRE 1.8.0_202-release-1483-b53x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Captured exception
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:227:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:78:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:79:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:497:11)
#7      new DeclarationsTrackerData.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:300:9)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#15     _rootRun (dart:async/zone.dart:1120:38)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/np/gmysjh1j2159hv7wssjzrw440028jd/T/report.txt.

Attached:

```
1564886535135 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/off_balance_opportunity/off_balance_opportunity_situation.g.dart"]}}
1564886535135 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/actor.g.dart"]}}
1564886535136 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/edgehead_serializers.g.dart"]}}
1564886535136 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/world_state.g.dart"]}}
1564886535136 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/common/attacker_situation.g.dart"]}}
1564886535136 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/history/custom_event_history.g.dart"]}}
1564886535136 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/writers_input.compiled.g.dart"]}}
1564886535136 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/history/visit_history.g.dart"]}}
1564886535140 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":408,"uri":"package:edgehead/src/fight/counter_attack/counter_attack_situation.dart","items":[{"label":"C
1564886535140 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":509,"uri":"package:edgehead/fractal_stories/history/visit_history.dart","items":[{"label":"VisitRecord",
1564886535141 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":559,"uri":"package:edgehead/writers_input.compiled.dart","items":[{"label":"undergroundChurchFromCaveWit
1564886535141 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":512,"uri":"package:edgehead/fractal_stories/history/custom_event_history.dart","items":[{"label":"Custom
1564886535142 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":393,"uri":"package:edgehead/src/fight/common/attacker_situation.dart","items":[{"label":"MoveEntity","de
1564886535142 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":536,"uri":"package:edgehead/fractal_stories/world_state.dart","items":[{"label":"WorldStateFlags","decla
1564886535142 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":546,"uri":"package:edgehead/edgehead_serializers.dart","items":[{"label":"serializers","declaringLibrary
1564886535144 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":514,"uri":"package:edgehead/fractal_stories/actor.dart","items":[{"label":"Actor","declaringLibraryUri":
1564886535146 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":426,"uri":"package:edgehead/src/fight/off_balance_opportunity/off_balance_opportunity_situation.dart","i
1564886535146 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":557,"uri":"package:edgehead/edgehead_global.dart","items":[{"label":"EdgeheadGlobalState","declaringLibr
1564886535147 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":499,"uri":"package:edgehead/fractal_stories/items/inventory.dart","items":[{"label":"WeaponEquipResult",
1564886535147 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":422,"uri":"package:edgehead/src/fight/loot/loot_situation.dart","items":[{"label":"LootSituation","decla
1564886535147 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":513,"uri":"package:edgehead/fractal_stories/history/action_history.dart","items":[{"label":"ActionRecord
1564886535148 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":450,"uri":"package:edgehead/src/room_roaming/room_roaming_situation.dart","items":[{"label":"RoomRoaming
1564886535148 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":328,"uri":"package:edgehead/src/fight/fight_situation.dart","items":[{"label":"getGroundMaterial","decla
1564886535231 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/egamebook/edgehead/lib/src/fight/counter_attack/counter_attack_situation.g.dart","errors":[]}}
1564886535231 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1564886535236 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1564886535236 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":328,"uri":"package:edgehead/src/fight/fight_situation.dart","items":[{"label":"getGroundMaterial","decla
1564886535237 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/edgehead_action_builders_gather.gathered.dart"]}}
1564886535241 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":552,"uri":"package:edgehead/edgehead_event_callbacks_gather.dart","items":[{"label":"youre_dead_slave","
1564886535248 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'iterator' was called on null.\nReceiver: null\nTried call
```

**Comment by a-siva** [comment] 2019-08-12 17:10
appears to be a duplicate of https://github.com/dart-lang/sdk/issues/36638

**Closed by a-siva** 2019-08-12 17:10 UTC
Labels: area-analyzer, closed-duplicate
