### ISSUE TITLE
new js interop and commonjs

### ISSUE THREAD

**Issue by Aetet** [dart-lang/sdk#24722] opened 2015-10-24 21:28 UTC
Currently with new js interop we can load only objects that exists in global. But what about commonjs and es6 module system support? Is it planned to load them?

**Comment by zoechi** [comment] 2015-10-25 09:01
Can you please be more specific about  what you want. You can load the modules in JS script tags and instantiate classes from Dart. A concrete example that shows what you try to accomplish would be helpful.

**Comment by Aetet** [comment] 2015-10-25 17:27
We have library Awesome.
We can load module with js interop if module in global `window.Awesome = Awesome;`

If module from commonjs-like modules:
```js
var npmModule = require('some-npm-module');

function Awesome() {
   this.obj = npmModule();
}

module.exports = Awesome;
```
We cannot load it with global require just now. Can js interop support this format of loading modules.

**Comment by Aetet** [comment] 2015-10-28 08:23
@zoechi Does this example clearify situation?

**Comment by zoechi** [comment] 2015-10-28 09:11
Actually no, not for me, hopefully for the project members.
Why don't you just load it in a JS script tag or using old-style JS-interop?
After it is loaded new JS-interop should work fine.

**Comment by Aetet** [comment] 2015-10-28 10:41
Because I don't want global variables. I want that all my vars stays local, and not affect global window object.

**Comment by jacob314** [comment] 2015-10-28 23:02
We don't have any support currently but this is something we will work on supporting in the future.
It is dirty but for now you can work around the lack of support by importing your libraries all under some unlikely to conflict name. For example in JavaScript:
'''
$JS_MODULES_WORKAROUND_931 = {'Awesome': Awesome};
'''
then in dart
''''
@JS('$JS_MODULES_WORKAROUND_931.Awesome')
library awesome;

@JS('SomeAwesomeClass')
class .... {
}
'''

**Comment by jacob314** [comment] 2016-07-08 21:20
Duplicate of #25059

**Closed by jacob314** 2016-07-08 21:20 UTC
Labels: area-js_interop
