### ISSUE TITLE
ClipboardEvent has no instance getter 'type' error with Dart 1.15.0 and Dartium (Chrome 45)

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#26019] opened 2016-03-17 02:33 UTC
```
 input.addEventListener("paste", (Event e) => print(e.type));
```

```
Uncaught Unhandled exception:
Class 'JSObjectImpl' has no instance getter 'type'.

NoSuchMethodError: method not found: 'type'
Receiver: Instance of 'JSObjectImpl'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      JSObject.noSuchMethod.throwError (dart:js:1108)
#3      JSObject.noSuchMethod (dart:js:1119)
#4      _EventUtil.add.<anonymous closure>.<anonymous closure> (package:dquery/src/event.dart:33:51)
#5      Function._apply (dart:core-patch/function_patch.dart:7)
#6      Function.apply (dart:core-patch/function_patch.dart:28)
#7      _CreateDartFunctionForInteropIgnoreThis.call (dart:js:1453)
```

**Comment by tomyeh** [comment] 2016-03-17 10:16
Note: it works fine on Chrome, but fails on Dartium.

**Comment by jimmyshiau** [comment] 2016-03-28 01:57
The same issue: #26084

**Comment by alan-knight** [comment] 2016-03-28 20:05
Agreed, closing as duplicate of #26084

**Closed by alan-knight** 2016-03-28 20:05 UTC
