### ISSUE TITLE
Strong mode allows Object to be inserted into List<String>

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#26437] opened 2016-05-10 19:41 UTC
a.dart:
```dart
Object dummy() => new Object();
main() {
  var l = new List<String>();
  l.add(dummy());
}
```

```shell
$ dartanalyzer --strong a.dart
Analyzing [a.dart]...
No issues found
```

@leafpetersen @vsmenon @jmesserly

**Comment by vsmenon** [comment] 2016-05-10 19:51
Yeah, that's probably because we allow implicit casting.  Can you try running in DDC?  You should get a runtime error.

**Comment by jmesserly** [comment] 2016-05-10 19:53
another way to see the implicit downcast is to use a composite type:
```dart
Object dummy() => new Object();
main() {
  var l = new List<List<String>>();
  l.add(dummy());
}
```
```
[warning] Unsound implicit cast from Object to List<String> (test.dart, line 4, col 9)
```

Right now this behavior is By Design. Whether it will be that way in the future, not sure :)

**Comment by hterkelsen** [comment] 2016-05-10 20:06
I think there should be a warning for any code that would crash in checked mode

**Comment by jmesserly** [comment] 2016-05-10 20:13
> I think there should be a warning for any code that would crash in checked mode

Ironically, the current warning heuristics are the exact opposite of that.

We assume that no one has existing Dart1 code like above, because it would crash in VM/dart2js checked mode. That's why we allow it in Strong Mode.

We warn for composite types, because that *could* be passing Dart1 checked mode but will fail at runtime in Strong Mode.

It was a useful distinction to get code ported over to Strong Mode with minimal changes, but I agree in the long term I would love to see this changed and require explicit casts.

**Comment by leafpetersen** [comment] 2016-06-06 22:53
I'm going to close this as a duplicate and make https://github.com/dart-lang/sdk/issues/26583 the canonical issue for this.

**Closed by leafpetersen** 2016-06-06 22:53 UTC
Labels: analyzer-strong-mode, area-analyzer, P2 medium, Type: bug
