### ISSUE TITLE
Socket error: FileSystemException: Directory watcher closed unexpectedly, path = 'c:\Users\This pc\OneDrive\Desktop\loundery_and_housecleaning_service'

### ISSUE THREAD

**Issue by like-github1** [dart-lang/sdk#49291] opened 2022-06-20 04:17 UTC
Socket error: FileSystemException: Directory watcher closed unexpectedly, path = 'c:\Users\This pc\OneDrive\Desktop\loundery_and_housecleaning_service'

I try to run my flutter project and I face this issue, I search on google but I can't find any answer. this issue is already  posted [here ](https://github.com/dart-lang/sdk/issues/39180  ) but it is not answered yet

![e5](https://user-images.githubusercontent.com/92579234/174524316-07f3399d-43d8-4401-9250-c4d90e31bb56.PNG)

**Comment by keertip** [comment] 2022-06-23 17:30
Duplicate of #38853

**Closed by keertip** 2022-06-23 17:30 UTC
Labels: area-analyzer
