### ISSUE TITLE
Wrong diagnostic of infos (missing_return)

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/sdk#33117] opened 2018-05-14 21:26 UTC
![image](https://user-images.githubusercontent.com/1907844/40024159-caba2e94-57a3-11e8-920a-09d051c94a62.png)
```
$ dart --version
Dart VM version: 2.0.0-dev.54.0 (Unknown timestamp) on "linux_x64"
```

Seems the analyzer doesn't handle well that infos (those return statements ends up with true or false values)

**Comment by zoechi** [comment] 2018-05-15 08:13
It's not guaranteed that one of these returns will ever be hit.

I think you should add `return false;` before the end of the method.

**Comment by Rodsevich** [comment] 2018-05-15 13:26
@zoechi's suggestion solves the info but it means adding dead code for solving an info issue. Shouldn't it be better to have analyzer satisfied by reading a return statement in loops, delegating the responsibility of writing terminating loops to the programmer that writes them?

**Comment by Rodsevich** [comment] 2018-05-15 21:01
Tried adapting the code to @zoechi comment :arrow_up: 
![image](https://user-images.githubusercontent.com/1907844/40083211-d12201aa-5869-11e8-84fc-97d71efec72b.png)
But seems that it still have the issue when trying with `continue`

![image](https://user-images.githubusercontent.com/1907844/40083044-64b3fa1e-5869-11e8-937c-792b2266dca2.png)
I remembered this code and don't get why here it doesn't complain

**Comment by zoechi** [comment] 2018-05-16 03:07
My guess: `while(true)` can never be passed. So the only possible return has to be inside the loop.

**Comment by bwilkerson** [comment] 2018-08-29 00:59
I'm guessing that this was working as intended, so I'm closing it. Please let me know if it's still an issue for you.

**Closed by bwilkerson** 2018-08-29 00:59 UTC
Labels: area-analyzer
