### ISSUE TITLE
Migration of path package incorrectly makes a field nullable

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#38627] opened 2019-09-27 20:04 UTC
In the path package (the version vended into the SDK), in the file , the migration engine marks a field as nullable that I believe will never be null. All of the constructors will initialize the field to a non-null value. The definition of the constructors is included below for easy reference (and in case the DEPS are updated after this issue is filed in a way that makes the problem go away).

I suspect that the problem is that the parameter `style`, in the unnamed constructor, is not known to be non-null after the if-else where it's explicitly checked against `null`, but I don't have the graph available yet so I don't know why that would be.

```
class Context {
  /// Creates a new path context for the given style and current directory.
  ///
  /// If [style] is omitted, it uses the host operating system's path style. If
  /// only [current] is omitted, it defaults ".". If *both* [style] and
  /// [current] are omitted, [current] defaults to the real current working
  /// directory.
  ///
  /// On the browser, [style] defaults to [Style.url] and [current] defaults to
  /// the current URL.
  factory Context({Style? style, String? current}) {
    if (current == null) {
      if (style == null) {
        current = p.current;
      } else {
        current = ".";
      }
    }

    if (style == null) {
      style = Style.platform;
    } else if (style is! InternalStyle) {
      throw new ArgumentError("Only styles defined by the path package are "
          "allowed.");
    }

    return new Context._(style as InternalStyle?, current);
  }

  /// Create a [Context] to be used internally within path.
  Context._internal()
      : style = Style.platform as InternalStyle,
        _current = null;

  Context._(this.style, this._current);
```

**Comment by bwilkerson** [comment] 2019-09-28 18:37
I have a little more information. I don't know anything more yet about the invocation of `Context._` at the end of the unnamed constructor, but one of the reasons given for making the field `style` nullable is that the assignment to the field in `Context._internal` is thought to be the assignment of a nullable value. `Style.platform` is (correctly) non-nullable, and the reference to `InternalStyle` is non-nullable, so I don't understand why the engine thought that expression has a nullable type. It's possible that `as` isn't handled correctly. It's also possible that I'm misinterpreting the graph.

**Comment by stereotype441** [comment] 2019-10-04 20:49
I believe this is happening due to #38725.  In short, flow analysis is not yet smart enough to understand that this code:
```dart
if (style == null) {
  style = Style.platform;
}
```
promotes the type of `style` to a non-nullable type.

However it would be good to verify this once we have more instrumentation data from the migration engine.

**Comment by srawlins** [comment] 2020-06-14 18:22
Note that this is still occurring. Bug may still be in flow analysis. In context.dart, the style field is still being marked nullable.

**Comment by srawlins** [comment] 2020-09-10 19:53
The path package has now been migrated and there is a closed root cause for this issue, so I'm going to close it. If it shows up in a different migration, we'll track it with a new bug.

**Closed by srawlins** 2020-09-10 19:53 UTC
Labels: P2, analyzer-nnbd-migration, area-analyzer
