### ISSUE TITLE
CFE reserves null-safety-specific keywords in opted-out contexts.

### ISSUE THREAD

**Issue by Markzipan** [dart-lang/sdk#40377] opened 2020-01-29 17:44 UTC
Snippet:
```
// @dart = 2.6

class late {
  int get g => 1;
}

class required {
  int get g => 2;
}

class C {
  late l = late();
  required r = required();
}

main() {
  Expect.equals(C().l.g, 1);
  Expect.equals(C().r.g, 2);
}
```

emits the following compile-time error (with the non-nullable experiment enabled):
```
Error: Can't use 'late' as a name here.
class late {
      ^^^^
Error: Can't use 'required' as a name here.
class required {
      ^^^^^^^^
Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
  late l = late();
       ^
Error: Null safety features are disabled for this library.
Try removing the `@dart=` annotation or setting the language version to at least `@dart=2.7`.
  late l = late();
  ^^^^
Context: This is the annotation that opts out this library from null safety features.
// @dart = 2.6
^^^^^^^^^^^^^^
```

**Comment by franklinyow** [comment] 2020-02-25 17:06
Any update on this?

**Comment by jensjoha** [comment] 2020-02-27 12:26
This no longer reproduces, probably a duplicate of #40288.

**Closed by jensjoha** 2020-02-27 12:26 UTC
Labels: NNBD, area-front-end, front-end-fasta
