### ISSUE TITLE
dart anqlyzer issue

### ISSUE THREAD

**Issue by sittinprettyingeorgia** [dart-lang/sdk#34898] opened 2018-10-23 02:42 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1093x614`

# Exception

Please append the contents of:
file://C:\Users\Mitchell\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\Mitchell\AndroidStudioProjects\geo_worker\lib\main.dart
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:4878:5)
#1      TypeProviderForLink.objectType (package:analyzer/src/summary/link.dart:4847:23)
#2      ClassElementForLink_Class._computeInterfaceType (package:analyzer/src/summary/link.dart:868:67)
#3      ClassElementForLink_Class.supertype (package:analyzer/src/summary/link.dart:779:27)
#4      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:300:33)
#5      InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:331:9)
#6      InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:82:5)
#7      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1557:10)
#8      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3505:12)
#9      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3205:15)
#10     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3145:7)
#11     DependencyWalker.walk.strongConnect (package:front_end/src/dependency_walker.dart:149:13)

**Comment by stereotype441** [comment] 2018-10-23 21:17
Duplicate of #34576

**Closed by stereotype441** 2018-10-23 21:17 UTC
Labels: area-analyzer
