### ISSUE TITLE
bad_constructor_test/06 crashes fasta

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31299] opened 2017-11-07 16:17 UTC
(I am marking this test as DartkCrash)

```
python tools/test.py -m release -c dartkp -r dart_precompiled language/bad_constructor_test/06
```

```
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ProcedureBuilder.getFormal (package:front_end/src/fasta/builder/procedure_builder.dart:120)
#2      BodyBuilder.endFormalParameter (package:front_end/src/fasta/kernel/body_builder.dart:1983)
#3      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:2418)
#4      Parser.parseModifiers (package:front_end/src/fasta/parser/parser.dart:3075)
#5      Parser.parseFormalParameter (package:front_end/src/fasta/parser/parser.dart:1095)
#6      Parser.parseFormalParameters (package:front_end/src/fasta/parser/parser.dart:1051)
#7      Parser.parseFormalParametersOpt (package:front_end/src/fasta/parser/parser.dart:987)
#8      DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:681)
#9      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:540)
#10     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:506)
#11     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3389)
#12     Parser.parseClassMember (package:front_end/src/fasta/parser/parser.dart:3264)
#13     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3132)
#14     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1390)
#15     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1349)
#16     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:434)
#17     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:365)
#18     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:308)
#19     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:181)
<asynchronous suspension>
#20     Loader.buildBodies (package:front_end/src/fasta/loader.dart:136)
<asynchronous suspension>
#21     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:291)
<asynchronous suspension>
#22     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:129)
<asynchronous suspension>
#23     kernelForProgram.<anonymous closure> (package:front_end/kernel_generator.dart:43)
<asynchronous suspension>
#24     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89)
#25     _rootRun (dart:async/zone.dart:1124)
#26     _CustomZone.run (dart:async/zone.dart:1021)
#27     runZoned (dart:async/zone.dart:1499)
#28     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89)
#29     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96)
#30     kernelForProgram (package:front_end/kernel_generator.dart:42)
<asynchronous suspension>
#31     SingleShotCompiler.compile (file:///usr/local/google/home/vegorov/src/dart/sdk/utils/kernel-service/kernel-service.dart:116)
<asynchronous suspension>
#32     _processLoadRequest (file:///usr/local/google/home/vegorov/src/dart/sdk/utils/kernel-service/kernel-service.dart:198)
<asynchronous suspension>
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by askeksa-google** [comment] 2017-11-09 09:34
Probably a duplicate of https://github.com/dart-lang/sdk/issues/31196

**Comment by jensjoha** [comment] 2018-01-05 08:55
I cannot reproduce this issue. @mraleph can you or should we close?

**Comment by askeksa-google** [comment] 2018-01-11 12:38
It still crashes if you try to compile the generated file for the 06 subtest. Reduced test case:

```dart
class A {
  // Named constructor may not conflict with names of methods and fields.
  A.foo() : m = 0;
  int foo(int a, int b) => a + b * m;
}

main() {
  new A();
}
```

**Comment by peter-ahe-google** [comment] 2018-02-02 18:57
See also #30981

**Closed** 2018-02-05 15:40 UTC
Labels: P2 medium, area-front-end, crash
