### ISSUE TITLE
[Analyzer] referring to extension method from another extension causes error

### ISSUE THREAD

**Issue by jifalops** [dart-lang/sdk#41458] opened 2020-04-13 01:47 UTC
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (6 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

Reproduce: 
```dart
class A {}

extension AList on Iterable<A> {
  get foo => null;
}

extension AMap on Map<String, A> {
  get bar => values.foo; // <-- foo is underlined red
}
```
`values.foo` error:
>A member named 'foo' is defined in extensions 'AList' and 'AList' and neither is more specific.
Try using an extension override to specify the extension you want to to be chosen.dart(ambiguous_extension_member_access)

Removing the name, `AList`, works around it.

**Comment by srawlins** [comment] 2020-04-13 21:45
I am unable to reproduce this, with `dartanalyzer` 2.8.0-dev.9.0, or at HEAD (23a8788f6a9c453f3786c4330c4876e9d14608ef).

Perhaps you imported another library which also declared this extension?

**Comment by jifalops** [comment] 2020-04-15 01:59
No but it stopped happening for me now. I'm pretty sure I had reloaded the VS Code window before when trying to fix it.

**Comment by jifalops** [comment] 2020-05-07 02:13
Reopening because it is still happening. The code will compile but I have to choose to ignore errors. This is in VS Code. 

Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (4 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

**Comment by ThinkDigitalSoftware** [comment] 2020-08-21 00:34
This is still present in Dart SDK version: 2.9.1 (stable) (Wed Aug 12 12:37:19 2020 +0200) on "macos_x64"

**Comment by srawlins** [comment] 2021-01-28 05:16
The original example, and the last example from @eernstg both analyze with no errors at HEAD. I think this can be closed.

**Comment by eernstg** [comment] 2021-01-29 09:34
Agreed, closing.

@scheglov, just to make sure I'm not causing trouble for you: Could you take a brief look and reopen this issue if you believe there's more to do?

**Closed by eernstg** 2021-01-29 09:34 UTC
Labels: analyzer-spec, area-analyzer
