### ISSUE TITLE
Stop automatically excluding non-existent packages directories

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#28846] opened 2017-02-21 15:14 UTC
Pub no longer generates a `packages` directory (by default) and users should be deleting those directories and using `.packages` files instead. Automatically excluding these directories forces the analysis server to pattern match against a long list of exclusions for every file that might be analyzed.

For bonus points, you could offer to delete any existing `packages` directories (unless they contain non-sym-link directories) and, if there isn't already a `.packages` file, run pub to generate it. This would help users transition away from `packages` directories.

**Comment by alexander-doroshko** [comment] 2017-02-21 15:21
@bwilkerson Dart plugin doesn't include numerous excluded `packages` folders in the `analysis_setAnalysisRoots` request, does it?

**Comment by bwilkerson** [comment] 2017-02-21 16:08
Yes, it does.

It is possible, however, that the behavior I've been seeing is an artifact of my having had these modules defined for a very long time and that they were not automatically cleaned up from changes made by earlier versions. So perhaps if users start with a fresh project they won't see this behavior.

**Comment by alexander-doroshko** [comment] 2017-02-21 16:30
If `pubspec.yaml` file is in its place then paths to the `packages` folders should not be sent to the server. Otherwise it is a bug, but I can't reproduce it.

I guess related log that you have in mind is something like [this one](https://youtrack.jetbrains.com/issue/WEB-25474#comment=27-1916065). In that case, note that `dev_compiler` folder doesn't contain pubspec. So probably 
- pubspec has been there at some moment, 
- IDE auto-excluded dozens of corresponding `packages` folders but has not been sending these paths to server,
- pubspec file has been removed but excluded  `packages` paths remained in IntelliJ's project model,
- so IDE started to send these paths to the server as they are not associated with any pubspec anymore.

This case has to be addressed manually: open Project Structure dialog and remove unneeded excluded paths. If you have any other questionable case, let's discuss. So far I do not see what should be fixed at the IDE end.

P.S. At some moment we need to forget about those old `packages` folders and stop auto-excluding them. We do not want to do it now because otherwise 1% of users who still have these symlinks will have to wait while IntelliJ indexes the Universe multiple times. We are safe to make this change when:
- Dart SDK drops support of `--generate-symlinks` flag (do not remember exact option name)
- IntelliJ declares that the minimal supported Dart SDK is the one from the above item

This is tracked as [WEB-25293](https://youtrack.jetbrains.com/issue/WEB-25293)

**Comment by alexander-doroshko** [comment] 2018-03-13 14:15
This has been fixed quite a while ago, feel free to close.

**Closed** 2018-03-13 14:28 UTC
Labels: area-intellij
