### ISSUE TITLE
An overriding method can't specify a different default value

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#34190] opened 2018-08-20 10:12 UTC
From `co19_2/Language/Classes/Abstract_Instance_Members/override_default_value_t01`:
```dart
class A {
  foo([x = 1]) {}
}

class C extends A {
  foo([x = '']);
}
```
The spec says (in 10.1):

"It is a compile-time error if an instance method m1 overrides an instance member m2, the signature of m2 explicitly specifies a default value for a formal parameter p, and the signature of m1 implies a different default value for p."

**Comment by a-siva** [comment] 2018-10-11 19:52
The Dart VM running the sample code above does not report any errors.

**Comment by sigmundch** [comment] 2018-10-16 16:04
Johnni tried implementing this in dart2js, and he noticed that it brings up errors in the SDK, so we'll likely see this surface as a breaking change on users code as well (I have no notion at the moment for how often this would happen, though, but it could be measured).

I'm reassigning this bug to the language team to get some clarity about this spec issue: is this actually a soundness problem? If not, could we change the spec?

I believe that at this time, all implementations ignore this and allow users to provide different default values. And note that we are however still validating that overrides have a proper subtyping relation, so this is only about the default value that the target method gets.

**Comment by eernstg** [comment] 2018-10-16 16:29
>  is this actually a soundness problem?

I do not expect the specification of a different default value for a given parameter in an overriding declaration of a method to be a soundness problem. After all, the different value is statically known for the code to which it will be passed.

The problem is at the software engineering level: If a default value is part of the interface of a method _m_ (just like, say, its return type) then it serves as machine checked documentation of the semantics of omitting a specific parameter _p_ (and the DartDoc and similar info would then clarify what it means to pass that particular value).

An overriding declaration of _m_ should live up to this documentation, i.e., it should not behave in a way that violates the expectations (as seen from a caller who has the supertype as the static view on the receiver), and it seems reasonable that the same semantics should be represented by the same value as the actual argument for _p_.

If the default value is _not_ considered to be part of the interface (more like: "dear caller, it's none of your business what value we will give this parameter if you don't pass anything") then I'd consider the design where the parameter is initialized with some value in the body of the method more natural. This would fit the situation where the value of the parameter is part of the implementation rather than a specification of a desired semantics.

We can certainly say that we don't care, go ahead and override default values any way you like, but in that case I think the default value is a disturbing and potentially misleading part of the method header (which ought to contain things that are significant for callers, and not a bunch of messy implementation details).

**Comment by leafpetersen** [comment] 2018-10-18 17:07
dup of https://github.com/dart-lang/sdk/issues/34437

**Comment by kmillikin** [comment] 2018-10-22 12:02
#34437 is the Analyzer counterpart of this one, but since we are only assigning issues to exactly one "area" label we should keep both of them open.

**Comment by leafpetersen** [comment] 2018-10-23 05:06
We discussed this today in the language meeting. We will demote this to a warning for the time being, and consider changing it to an error (breaking change) in the future. So the resolution of this bug is to add this back in as a warning.

**Comment by kmillikin** [comment] 2019-04-08 10:04
This was changed to a warning.  Fasta does not issue the warning.

**Comment by kmillikin** [comment] 2019-05-22 12:08
This depends on CFE constant evaluation, and doesn't block landing it (constant evaluation).

**Comment by leafpetersen** [comment] 2022-05-25 17:40
This has been resolved in the null safety release.

**Closed by leafpetersen** 2022-05-25 17:40 UTC
Labels: P2, area-front-end, front-end-missing-error, front-end-requires-constant-evaluation
