### ISSUE TITLE
Release build gets stuck on device

### ISSUE THREAD

**Issue by MariaMelnik** [dart-lang/sdk#34915] opened 2018-10-24 15:44 UTC
I made release build (android) according to this docs: https://flutter.io/android-release/
But it gets stuck when I run it on device (everything is ok on emulator).

Debug build works ok for both emulator and device.

Code sample: https://gist.github.com/MariaMelnik/9faa74b34dce2930399059b8d15acb29

Android version on device 8.0.0

Flutter doctor:
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)

There is another issue with this code example (not sure if it is related to this): https://github.com/dart-lang/sdk/issues/34473

**Comment by vsmenon** [comment] 2018-10-24 15:47
@a-siva - not sure if this should be filed on vm or moved to flutter.

**Comment by aartbik** [comment] 2018-10-24 18:08
Note that https://github.com/dart-lang/sdk/issues/34473 deals with 5x "slowness" of AOT compared to JIT.  Does "stuck" mean it takes a long time, or does it really never terminate?

**Comment by MariaMelnik** [comment] 2018-10-25 07:10
> Note that #34473 deals with 5x "slowness" of AOT compared to JIT. Does "stuck" mean it takes a long time, or does it really never terminate?

Yes, it is not slower 5x or 10x (even 100x) it just gets stuck.
Release build slower then debug build (but works) on emulators. 
But release build gets stuck on devices. It doesn't work at all.

**Comment by mraleph** [comment] 2018-11-20 11:57
I have finally had a change to try this on the real device (I have Nexus 5x). 

I added a print to see if the loop inside `convert` was making any progress like so:

```dart
    for (int i = 1; i <= l; i++) {
      final sw = Stopwatch()..start();
      for (int i = 0; i < c; i++) {
        U_i = hmac.convert(U_i).bytes;
      }
      print('took ${sw.elapsedMilliseconds} ms');
    }
```

and I have gotten the following:

```
─ ~/src/flutter/flutter/examples/hello_world ‹master*›
╰─$ flutter run --release -t lib/main.dart --target-platform android-arm
Initializing gradle...                                       0.8s
Resolving dependencies...                                    1.7s
Launching lib/main.dart on Nexus 5X in release mode...
Gradle task 'assembleRelease'...                                 
Gradle task 'assembleRelease'... Done                       23.7s
Built build/app/outputs/apk/release/app-release.apk (5.0MB).
Installing build/app/outputs/apk/app.apk...                  3.8s

To quit, press "q".
I/flutter ( 6733): took 18834 ms

I/flutter ( 6733): took 37019 ms
I/flutter ( 6733): took 44640 ms
I/flutter ( 6733): took 20295 ms
I/flutter ( 6733): took 38270 ms
I/flutter ( 6733): took 42919 ms
```

So I think nothing really gets stuck - it's just we are really-really bad on ARM32 which is #34473

**Comment by mraleph** [comment] 2018-11-20 11:57
Duplicate of #34473

**Closed by mraleph** 2018-11-20 11:57 UTC
Labels: area-vm
