### ISSUE TITLE
CFE is missing compile time errors for partial instantiation with statically-known bounds

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#34327] opened 2018-08-31 14:18 UTC
When the CFE injects a partial instantiation operator, it needs to check that the type arguments applied match the bounds of the target when the target is statically known (tearoffs against `super`, local functions, and toplevel functions). The Analyzer currently has the right behavior. This is tested by `language_2/partial_instantiation_static_bounds_check_test` and there are corresponding status entries in `language_2.status`. For reference, the test is:

```dart
topFn<T extends num>(T x) {
  print(T);
}

class C<T> {
  instanceFn<S extends T>(S x) {
    print(S);
  }
}

class D<T> extends C<T> {
  void foo() {
    void Function(int) k = instanceFn;  //# 03: compile-time error
  }
}

void main() {
  localFn<T extends num>(T x) {
    print(T);
  }
  void Function(String) k0 = localFn;  //# 01: compile-time error
  void Function(String) k1 = topFn;  //# 02: compile-time error
}
```

Note that the VM is currently applying optimizations under the assumption that the CFE does perform this check correctly.

**Comment by kmillikin** [comment] 2018-08-31 14:54
This is a duplicate of #33308.

**Closed by kmillikin** 2018-08-31 14:54 UTC
Labels: area-front-end
