### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by PrigovorO** [dart-lang/sdk#39292] opened 2019-11-08 10:02 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.7142.36`
- `2.6.0`
- `IU-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.0, server version 1.27.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [D:\Dart\Projects\dart-angular-demo], excluded: [D:\Dart\Projects\dart-angular-demo\.idea, D:\Dart\Projects\dart-angular-demo\.dart_tool, D:\Dart\Projects\dart-angular-demo\.pub, D:\Dart\Projects\dart-angular-demo\build, D:\Dart\Projects\dart-angular-demo\out]}, clientRequestTime: 1573207173418}
FileSystemException: Directory watcher closed unexpectedly, path = 'D:\Dart\Projects\dart-angular-demo'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:307:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file://C:\Users\Serhey\AppData\Local\Temp\report.txt.

**Comment by keertip** [comment] 2019-11-08 12:52
This issue was previously reported #39180 , please follow along there.

**Comment by keertip** [comment] 2019-11-08 12:53
Duplicate of #39180

**Comment by keertip** [comment] 2019-11-08 12:54
@scheglov, seen this exception a few times in the last couple of days.

**Closed by keertip** 2019-11-08 12:53 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
