### ISSUE TITLE
Bug: DateTime 1970-01-01 issue. Windows only!

### ISSUE THREAD

**Issue by inselberg** [dart-lang/sdk#53079] opened 2023-07-31 17:45 UTC
```
void main(List<String> arguments) {
  print(DateTime.parse("1968-12-31T00:00").add(Duration(days: 1)));
  print(DateTime.parse("1969-12-31T00:00").add(Duration(days: 1)));
  print(DateTime.parse("1970-12-31T00:00").add(Duration(days: 1)));
}
```

leads to:
```
1969-01-01 00:00:00.000
1970-01-01 01:00:00.000
1971-01-01 00:00:00.000
```
using Dart SDK version: 3.1.0-348.0.dev (dev) (Tue Jul 25 09:03:15 2023 -0700) on "windows_x64"

and to:
```
1969-01-01 00:00:00.000
1970-01-01 00:00:00.000
1971-01-01 00:00:00.000
```
using Dart SDK version: 3.1.0-348.0.dev (dev) (None) on "linux_x64"

**Comment by julemand101** [comment] 2023-08-01 08:03
Can you specify what exact timezone you use on your systems? (both Windows and Linux).

**Comment by lrhn** [comment] 2023-08-01 08:38
If we check the time zone offset, e.g.,:
```dart
void main(List<String> arguments) {
  pdtz(DateTime.parse("1968-12-31T00:00"));
  pdtz(DateTime.parse("1969-12-31T00:00"));
  pdtz(DateTime.parse("1970-12-31T00:00"));
}
void pdtz(DateTime dt) {
  var dt2 = dt.add(Duration(days: 1));
  print("$dt (+${dt.timeZoneOffset}) -> $dt2: (+${dt2.timeZoneOffset})");
}
```
it shows
```
1968-12-31 00:00:00.000 (+0:00:00.000000) -> 1969-01-01 00:00:00.000: (+0:00:00.000000)
1969-12-31 00:00:00.000 (+0:00:00.000000) -> 1970-01-01 01:00:00.000: (+1:00:00.000000)
1970-12-31 00:00:00.000 (+1:00:00.000000) -> 1971-01-01 00:00:00.000: (+1:00:00.000000)
```
That means that Windows reports a different (missing) time zone before 1970.

The VM [uses `localtime_s`](https://github.com/dart-lang/sdk/blob/6dfcd40684f49e325f4bc92aec012aeafe8f18d0/runtime/vm/os_win.cc#L37C24-L37C35). The `localtime_s` is documented as a version of `localtime` with extra security features, and `localtime` states:
> Return a pointer to the structure result, or `NULL` if the date passed to the function is:
> * Before midnight, January 1, 1970.
> * ....

So it's not unpredictable that localtime doesn't work on Windows before 1970.

Is there some other Windows function we could use, or does Windows just not have time zone information prior to 1970?

**Comment by a-siva** [comment] 2023-11-16 17:39
//cc @brianquinlan

**Comment by aam** [comment] 2023-11-16 21:57
Duplicate of https://github.com/dart-lang/sdk/issues/44656

**Closed by aam** 2023-11-16 21:57 UTC
Labels: area-vm, P3, os-windows, triaged
