### ISSUE TITLE
MSAN is saying std::cout is uninitialized

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#43316] opened 2020-09-03 10:50 UTC
[vm-kernel-msan-linux-release-x64](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-msan-linux-release-x64/1131) is currently failing with:
```
==11039==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fa9b26ae04c in std::__2::basic_ostream<char, std::__2::char_traits<char> >& std::__2::__put_character_sequence<char, std::__2::char_traits<char> >(std::__2::basic_ostream<char, std::__2::char_traits<char> >&, char const*, unsigned long) ../../out/ReleaseMSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/ostream:727:13
    #1 0x7fa9b26a55ae in std::__2::basic_ostream<char, std::__2::char_traits<char> >& std::__2::operator<<<std::__2::char_traits<char> >(std::__2::basic_ostream<char, std::__2::char_traits<char> >&, char const*) ../../out/ReleaseMSANX64/../../buildtools/linux-x64/clang/bin/../include/c++/v1/ostream:869:12
    #2 0x7fa9b26a55ae in SumVeryManySmallInts ../../out/ReleaseMSANX64/../../runtime/bin/ffi_test/ffi_test_functions.cc:348:13
```

Which AFAICT points to `std::cout`: https://github.com/google/sanitizers/issues/712.

The suggested fix is that libc++ needs to be built with MSan.

I do however not know if this is an issue with Dart, FFI, or something else.

**Comment by cskau-g** [comment] 2020-09-03 10:52
[@dcharkes for FFI]

**Comment by dcharkes** [comment] 2020-09-03 17:23
Thanks for reporting.

Duplicate of https://github.com/dart-lang/sdk/issues/43075.

**Closed by dcharkes** 2020-09-03 17:23 UTC
Labels: area-build, gardening, library-ffi, type-bug
