### ISSUE TITLE
Autocomplete of names not in scope gets confused by re-exported libraries

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#36790] opened 2019-04-28 17:46 UTC
Being able to automatically import symbols that aren't yet in scope is great but I'm having trouble with it being a bit too aggressive.

On a bleeding edge Dart SDK from Friday:
Repro steps:
```dart
import 'package:flutter/material.dart';
```
Now autocompleting a name from `package:flutter/widgets.dart` leads to problems as the symbols are available both through widgets.dart and the material.dart library that reexports them. You see duplicate entries for the same class in the autocomplete lists and the autocomplete functionality sometimes defaults to trying to make the import with a autogen prefix which causes me to have to undo and delete the prefix every time it gets suggested.

Example showing a prefix being generated without me doing anything to try to accept it even though the name is already in scope. In general it would be nice if some acceptance action was required to ever trigger importing with a prefix.
![autocomplete](https://user-images.githubusercontent.com/1226812/56868059-46812d00-69a2-11e9-84e5-03166163d753.gif)

FYI @scheglov

**Comment by scheglov** [comment] 2019-04-28 22:23
Please send the complete code of the file.

When I try something like your field in an almost empty file, it does NOT cause an import prefix, because it should it, it is the same class.  So, it must be some other name in the library that gets shadowed when both package:flutter/widget.dart is imported without a prefix.

**Comment by canewsin** [comment] 2019-05-20 22:48
same thing happens in vscode

**Comment by scheglov** [comment] 2019-05-20 23:32
If there is a standalone example how this could be reproduced, it would be faster to fix.
Animated images are less useful :-(

**Comment by canewsin** [comment] 2019-05-21 11:37
https://github.com/flutter/flutter/issues/33077#issuecomment-494222359

Opened Issue at same time yesterday 

I think this is simailar to 
https://github.com/dart-lang/sdk/issues/36890
above issue but with vscode

My problem is not appeared after uninstalling both flutter and plugins 
But I expected that it could happen because 
see this 
![2019-05-21_16-53-35](https://user-images.githubusercontent.com/26790557/58092251-3b0fd300-7be9-11e9-9fb3-0e3c2c0a266f.gif)
But it less annoying than before uninstalling because prefix0 is shown straight in first column now it is much better because it happens now less frequently
but it still showning widgets from multiple packages this is not an expected behaviour since i already imported material package why i need cupertino or widgets packages to be imported

**Comment by canewsin** [comment] 2019-05-21 11:39
>If there is a standalone example how this could be reproduced, it would be faster to fix.
Animated images are less useful :-(

Instead of Gif Image How can i post vscode plugin related logs

**Comment by scheglov** [comment] 2019-05-21 18:58
@canewsin So, it seems that you are referencing another problem - that multiple possible imports are suggested for a name, even though the file where completion is requested already imports a library that exports this name. (Saying "name" is not quite correct - it should be "element" - name with URI). Yeah, this leads to some overload, although DAS always puts the variants from already imported libraries on the top.

We could compute and send additional data to the client to suppress suggestions for not yet imported libraries, that are already available from already imported libraries.

**Comment by canewsin** [comment] 2019-05-22 04:52
@scheglov and what about that preix0 tag appears before suggesions those sometimes appears as first suggesion and when selected as [ package: uri as prefix0 ]

**Comment by canewsin** [comment] 2019-05-22 04:54
I mean like this
![57382534-6b994b00-71ad-11e9-90eb-e7b7831d2b89](https://user-images.githubusercontent.com/26790557/58148290-c33eb880-7c7b-11e9-977a-e1f96e83656e.gif)

**Comment by scheglov** [comment] 2019-05-22 16:01
Yes, the scenario you show is exactly what was fixed in https://github.com/dart-lang/sdk/issues/36890.

**Comment by DanTup** [comment] 2019-06-10 08:10
Is this a dupe of #36890 and fixed, or something else?

**Comment by scheglov** [comment] 2019-06-16 05:37
It seems that this issue is a mix of two separate issues.
1. Filtering duplicates of elements already available via existing imports. This is implemented with `existingImports` notification in DAS. @lambdabaa is adding support in IntelliJ.
2. Unnecessary import prefix. This was fixed.

**Closed by scheglov** 2019-06-16 05:37 UTC
Labels: analyzer-completion, area-analyzer, customer-flutter
