### ISSUE TITLE
Failures on vm-linux-release-riscv64-qemu

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#53182] opened 2023-08-10 23:22 UTC
The tests
```
ffi/function_structs_by_value_generated_args_test/2 RuntimeError (expected Pass)
ffi/function_structs_by_value_generated_args_test/3 RuntimeError (expected Pass)
vm/cc/IsolateReload_PendingUnqualifiedCall_StaticToInstance   (flaky -> Fail, expected Pass)
service/valid_source_locations_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
vm-linux-release-riscv64-qemu
vm-win-debug-arm64
```
[https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-ffi-qemu-linux-release-riscv64/576](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-ffi-qemu-linux-release-riscv64/576)

[https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-win-debug-arm64/135](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-win-debug-arm64/135)

**Comment by a-siva** [comment] 2023-08-10 23:27
//cc @rmacnak-google

**Comment by rmacnak-google** [comment] 2023-08-18 17:43
Duplicate of #48645

**Closed by rmacnak-google** 2023-08-18 17:43 UTC
Labels: area-vm, gardening, library-ffi, vm-service
