### ISSUE TITLE
Analyzer treats ~ with higher precedence than []

### ISSUE THREAD

**Issue by jtlapp** [dart-lang/sdk#40556] opened 2020-02-09 21:48 UTC
In strong mode with implicit casts and implicit casts off, bitwise complement `~` is treated as if it has higher precedence than index lookup `[]`. The code builds with the correct precedence, however.

```dart
final q = [1, 2, 3];
int x = ~q[0]; // ERROR - A value of type 'dynamic' can't be assigned to a variable of type 'int'.
int y = ~(q[0]); // ok
```
Dart SDK 2.7.1 on macOS 10.15.3.

**Comment by lrhn** [comment] 2020-02-10 09:33
The error requires the `--no-implicit-casts` flag. 
That suggests that `~q[0]` has static type `dynamic`, which is ... odd.

If the expression was parsed as `(~q)[0]`, the error would be different (something like "There is no ~ operator on List<int>"). So, my guess is that it's a more subtle bug in the analyzer.

**Comment by srawlins** [comment] 2020-06-03 20:35
Thanks for opening this issue! Please follow https://github.com/dart-lang/sdk/issues/36055.

**Comment by srawlins** [comment] 2020-06-03 20:35
Duplicate of https://github.com/dart-lang/sdk/issues/36055

**Closed by srawlins** 2020-06-03 20:35 UTC
Labels: area-analyzer, type-bug
