### ISSUE TITLE
consider solving in dart 3.x or 4.0 the async callbacks  ffi

### ISSUE THREAD

**Issue by insinfo** [dart-lang/sdk#51993] opened 2023-04-07 23:36 UTC
consider introducing in dart 3.x a solution to be able to make bindings via ffi with dynamic libraries that make use of asynchronous callbacks, such as dynamic audio libraries, database libraries, among many others, today dart has this great limitation that ends up forcing the programmer modifying and recompiling a library or having to make wrappers this ends up becoming workarouds or spaghetti code. The ideal is a solution on the dart side so that the programmer can pass up to lambda functions as callbacks, as many other languages allow, such as go, c#, PHP, among others.

perhaps a solution to this is a keyword in the language to mark a function to be of type asynchronous callback, along with some code generation in the compiler to turn the function into a separate isolate and some rules for the scope of the function so that the no body of the function only be passed data as copy. I'm not sure which is the best way.

maybe introducing native multi threads and a memory model in dart is a way to solve this

**Comment by blaugold** [comment] 2023-04-09 17:13
This is already being worked on: https://github.com/dart-lang/sdk/issues/37022#issuecomment-1342774581

**Comment by a-siva** [comment] 2023-04-10 14:58
marking as a duplicate of issue  https://github.com/dart-lang/sdk/issues/37022 which is currently being worked on.

**Closed by a-siva** 2023-04-10 14:58 UTC
Labels: area-vm, closed-duplicate, type-enhancement, library-ffi
