### ISSUE TITLE
Found a bug in compiler

### ISSUE THREAD

**Issue by johanalkstal** [dart-lang/sdk#38161] opened 2019-09-01 17:04 UTC
```
We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/area-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=C:\tools\dart-sdk/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\web/main.ddc.js --source-map --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/meta/meta.ddc.dill=packages/meta/meta --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/logging/logging.ddc.dill=packages/logging/logging --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/collection/collection.ddc.dill=packages/collection/collection --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/path/path.ddc.dill=packages/path/path --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/stack_trace/src/chain.ddc.dill=packages/stack_trace/src/chain --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/meta/dart2js.ddc.dill=packages/meta/dart2js --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/src/core/change_detection/change_detection.ddc.dill=packages/angular/src/core/change_detection/change_detection --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/src/core/application_tokens.ddc.dill=packages/angular/src/core/application_tokens --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/core.ddc.dill=packages/angular/core --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/di.ddc.dill=packages/angular/di --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/src/core/change_detection/change_detection.template.ddc.dill=packages/angular/src/core/change_detection/change_detection.template --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/di.template.ddc.dill=packages/angular/di.template --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/intl/intl.ddc.dill=packages/intl/intl --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/src/core/application_tokens.template.ddc.dill=packages/angular/src/core/application_tokens.template --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/core.template.ddc.dill=packages/angular/core.template --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/js/js_util.ddc.dill=packages/js/js_util --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/js/js.ddc.dill=packages/js/js --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/src/bootstrap/modules.ddc.dill=packages/angular/src/bootstrap/modules --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/angular.ddc.dill=packages/angular/angular --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/src/bootstrap/run.template.ddc.dill=packages/angular/src/bootstrap/run.template --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/angular/angular.template.ddc.dill=packages/angular/angular.template --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/petitparser/src/core/actions/action.ddc.dill=packages/petitparser/src/core/actions/action --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/petitparser/petitparser.ddc.dill=packages/petitparser/petitparser --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/xml/src/xml/builder.ddc.dill=packages/xml/src/xml/builder --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/xml/xml.ddc.dill=packages/xml/xml --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/stagexl/src/animation.ddc.dill=packages/stagexl/src/animation --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/rink/src/entity/game_entity.ddc.dill=packages/rink/src/entity/game_entity --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/equipment/equipment.ddc.dill=packages/equipment/equipment --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/rink/rink.ddc.dill=packages/rink/rink --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/broadcaster/src/cartographer.ddc.dill=packages/broadcaster/src/cartographer --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/broadcaster/app_component.ddc.dill=packages/broadcaster/app_component --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/broadcaster/app_component.css.shim.ddc.dill=packages/broadcaster/app_component.css.shim --summary=C:\Users\Johan\AppData\Local\Temp\scratch_spaceeaf345e1-ccd9-11e9-a547-9cb6d0ba0f02\packages/broadcaster/app_component.template.ddc.dill=packages/broadcaster/app_component.template --packages=file:///C:/Users/Johan/AppData/Local/Temp/kernel_builder_16d8021c-ccda-11e9-a547-9cb6d0ba0f02/.packages --module-name=web/main --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///C:/tools/dart-sdk/lib/libraries.json web/main.dart
    dart --version: 2.4.1 (Wed Aug 7 13:15:56 2019 +0200) on "windows_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:391:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:233:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:246:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:401:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:55:24) <asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by vsmenon** [comment] 2019-10-08 03:36
Duplicate of https://github.com/dart-lang/sdk/issues/38102

**Closed by vsmenon** 2019-10-08 03:36 UTC
Labels: area-front-end
