### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by mohamedabdelmoaty1** [dart-lang/sdk#39314] opened 2019-11-09 10:03 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.7142.36`
- `2.6.0`
- `IU-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.6.0, server version 1.27.3, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\Users\3bmo36y\IdeaProjects\dart-intermediate-course], excluded: [C:\Users\3bmo36y\IdeaProjects\dart-intermediate-course\.idea, C:\Users\3bmo36y\IdeaProjects\dart-intermediate-course\.dart_tool, C:\Users\3bmo36y\IdeaProjects\dart-intermediate-course\.pub, C:\Users\3bmo36y\IdeaProjects\dart-intermediate-course\build, C:\Users\3bmo36y\IdeaProjects\dart-intermediate-course\out]}, clientRequestTime: 1573293695620}
NoSuchMethodError: The method 'removeFile' was called on null.
Receiver: null
Tried calling: removeFile("C:\\Users\\3bmo36y\\IdeaProjects\\dart-intermediate-course\\lib\\dart_intermediate_course.dart~")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ServerContextManagerCallbacks.applyFileRemoved (package:analysis_server/src/analysis_server.dart:931:12)
#2      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:1518:19)
#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1406:5)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#10     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#17     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#18     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#24     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#25     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#26     _rootRun (dart:async/zone.dart:1120:38)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\3bmo36y\AppData\Local\Temp\report1.txt.

**Comment by keertip** [comment] 2019-11-11 17:58
Thanks for reporting this issue! This was previously reported in #33600, please follow along there.

**Comment by keertip** [comment] 2019-11-11 17:58
Duplicate of #33600

**Closed by keertip** 2019-11-11 17:58 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
