### ISSUE TITLE
Can methods of a class be compiled as extension methods in dart2js?

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#47309] opened 2021-09-28 19:31 UTC
dart2js
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"

Consider the code: 

```dart
import 'dart:html';
import 'dart:math';

class Foo {
  final int bit;

  const Foo(this.bit);
}

extension Ff on Foo {
  bool isSet(Foo flag) {
    return (bit & flag.bit) == flag.bit;
  }
}

void main() {
  final rnd = Random();
  final bit = rnd.nextInt(1);
  final foo = Foo(bit | 2 | 8);

  querySelector('#output').text = 'FooHasBFlag: ${foo.isSet(Foo(1))}, FooHasDFlag: ${foo.isSet(Foo(8))}';
}
```

Dart2JS transpiles all main() to:

```
var t=C.m.p(1)|2|8
document.querySelector("#output").textContent="FooHasBFlag: "+((t&1)===1)+", FooHasDFlag: "+((t&8)===8)
``` 

Foo doesn't even exist in the built code.  
However, this does not happen when the method ```isSet``` is a method of the ```Foo``` class. The result is that ```Foo``` exists and all its stuff.  

Is it possible to make a class be optimized like when used as extension?

**Comment by rakudrama** [comment] 2021-10-07 22:47
Hi @jodinathan, when you get the desired effect it is due to a lot of optimizations happening. It is hard to predict looking at the source code whether any of these optimizations will happen, and there is no reliable way of guaranteeing that the optimization will always happen.

The optimization chain is as follows. First, the `isSet` method in the extension is _inlined_. After the body of the method is copied into `main` by inlining, some simplifications can happen. The compiler can see that `this.bit` and `flag.bit` are from objects created immediately before, so it can do _load elimination_ to replace these field accesses with arguments to `new Foo`. This leaves the constructor calls unused, so they can be removed by _dead code elimination_.

When I tried to reproduce you finding, I actually get the same optimizations for static extensions methods and regular instance methods! I am using the latest dart2js (which will be in 2.15).
```
var t=B.m.q(1)|10
document.querySelector("#output").textContent="FooHasBFlag: "+((t&1)===1)+", FooHasDFlag: "+((t&8)===8)
```
(You can see dart2js is now doing a better job of simplifying bitwise-or operations, with `(x|2)|8` --> `x|10`.)

Inlining of `isSet` is a prerequisite for the sequence of optimizations, and you can encourage this by putting a `@pragma('dart2js:tryInline')` annotation on the method.

In real code, there are often factors that prevent the other optimizations from happening. Most likely the compiler can't see directly where the `Foo` objects were created, making it impossible to remove them or determine what is in their `bit` fields. This would happen if they are passed as parameters or are on a field of an object. Without these subsequent optimizations, inlining turns out to have be a less obvious choice - the code will be larger, thus slower to download, and now the operations are smeared all over the code, which means that the JavaScript engine can no longer boost performance by JIT-compiling the original method.

I'm going to close this issue as a odd combination of 'infeasible' and 'already implemented'.

I'm saying 'infeasible' because the small sample program (with all the Foo objects created within a single method) gives a best-case view of what is possible, and in 'real code' the optimizations are unlikely to be as good.

I'm saying 'already implemented' because dart2js has always compiled instance methods and extension methods essentially the same way. The different forms of methods just look slightly different in the internal representation, and this, in dart2js 2.10.5, was enough that the extension method was seen as 'only just small enough' to risk inlining and the instance method was seen as 'only just large enough' to avoid the risks of inlining. It appears that the line has shifted a little (and will likely shift again) but methods of a class _are_ already compiled with no fundamental prejudice over extension methods.

**Closed by rakudrama** 2021-10-07 22:47 UTC
Labels: web-dart2js, type-question, area-web, web-triage-0
