### ISSUE TITLE
Compiler cannot determine default value for super parameter correctly

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#48769] opened 2022-04-08 17:03 UTC
The following file is analyzer-clean, but when compiling it via `dart compile kernel` using Dart 2.17.0-282.0.dev I am getting the error indicated in the comment below. I believe, the code is correct and it should compile without error. I expect `showName` to copy the default value of "true" from the `DiagnosticsNode` constructor.

```dart
class NumProperty extends DiagnosticsProperty {
  NumProperty({
    super.showName,
  });

  NumProperty.lazy({
    // 🔥 Error: Type 'bool' of the optional super-initializer parameter 'showName' doesn't allow 'null',
    //    but the parameter doesn't have a default value, and the default value can't be copied
    //    from the corresponding parameter of the super constructor.
    super.showName,
  }) : super.lazy();
}

class DiagnosticsProperty extends DiagnosticsNode {
  DiagnosticsProperty({
    super.showName,
  });

  DiagnosticsProperty.lazy({
    super.showName,
  });
}

abstract class DiagnosticsNode {
  DiagnosticsNode({
    this.showName = true,
  });

  final bool showName;
}

void main() {
  print('hello');
}
```

This is blocking for enabling super parameters in Flutter.

**Comment by goderbauer** [comment] 2022-04-08 17:04
@pq could you route this to the right person?

**Comment by pq** [comment] 2022-04-08 17:07
Maybe @johnniwinther or @stereotype441 have ideas?

**Comment by goderbauer** [comment] 2022-04-08 17:10
Not sure if this is related, but I was seeing a similar issue when rolling some super-parameter enabled code into google3 the other day. The error message was slightly different, though (and thus far I have been unable to reproduce this outside of google3): https://github.com/flutter/flutter/issues/101455

**Comment by johnniwinther** [comment] 2022-04-11 11:19
A fix is in progress https://dart-review.googlesource.com/c/sdk/+/240844

It is likely the root cause of https://github.com/flutter/flutter/issues/101455

**Closed** 2022-04-12 20:33 UTC
Labels: type-bug, area-front-end

**Comment by goderbauer** [comment] 2022-04-14 17:59
> It is likely the root cause of https://github.com/flutter/flutter/issues/101455

Confirmed that this issue is fixed as well. Thanks @johnniwinther!
