### ISSUE TITLE
Dart can not infer type with sealed class and Mixin

### ISSUE THREAD

**Issue by eximius313** [dart-lang/sdk#53588] opened 2023-09-21 18:14 UTC
This code:
```dart
enum MyEnum {
  x,y
}
class MyClass {
}
mixin MyMixin {
}
sealed class MySealed<T> with MyMixin {
  final T payload;
  const MySealed(this.payload);
}

final class X extends MySealed<String> {
  const X(super.payload);
}
final class Y extends MySealed<MyClass> {
  const Y(super.payload);
}

void main() {
  final MyEnum myEnum = MyEnum.x;
  final MySealed<dynamic> s = switch(myEnum) {
    MyEnum.x => X('foo'),
    MyEnum.y => Y(MyClass())
  };
}
```
does not compile while it should. It display:
```
A value of type 'MyMixin' can't be assigned to a variable of type 'MySealed<dynamic>'.
Try changing the type of the variable, or casting the right-hand type to 'MySealed<dynamic>'.dart[invalid_assignment](https://dart.dev/diagnostics/invalid_assignment)
```
But when I add casting as suggested:
```dart
    MyEnum.y => Y(MyClass()) as MySealed<dynamic>
```
it works, but displays:
```
Unnecessary cast.
Try removing the cast.dart[unnecessary_cast](https://dart.dev/diagnostics/unnecessary_cast)
```

----
In your issue, please include:
* Dart version and tooling diagnostic info (`dart info`) -> `- Dart 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "windows_x64"`
* Whether you are using Windows, macOS, or Linux (if applicable) -> Windows 10
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) -> N/A
*

**Comment by eernstg** [comment] 2023-09-21 18:23
The error is reported because the least upper bound algorithm does not find the type `MySealed<dynamic>` in spite of the fact that this is a common supertype.

This has been discussed for a long time, and several approaches to improve on this situation are being considered. Here is the relevant set of issues in the language repository: https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aleast-upper-bound.

In particular, this one would resolve the issue you describe: https://github.com/dart-lang/language/issues/1618.

I'll close this one as a duplicate of the latter one.

**Closed by eernstg** 2023-09-21 18:23 UTC
Labels: closed-duplicate

**Comment by eximius313** [comment] 2023-09-21 18:25
But when I add the cast, the linter shows "Unnecessary cast."
Is it correct behaviour?

**Comment by eernstg** [comment] 2023-09-22 09:38
The `unnecessary_cast` lint isn't smart enough to detect that some upcasts do make a difference, it will just flag every upcast which isn't a cast to `dynamic`.

So you can do `// ignore: unnecessary_cast` or use `(e as dynamic) as SomeType` to eliminate the lint message. I'm afraid there is no better solution at this time. Also, if we adopt the proposal in https://github.com/dart-lang/language/issues/1618 then there would probably be significantly fewer upcasts.

**Comment by eximius313** [comment] 2023-09-24 21:07
thank you @eernstg
