### ISSUE TITLE
s

### ISSUE THREAD

**Issue by mrokey1997** [dart-lang/sdk#34621] opened 2018-09-30 08:00 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4505.22`
- `2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a`
- `IU-182.4505.22, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\baron\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.760a9690c22ec3f3d163173737f9949f97e6e02a, server version 1.20.5, error: Analysis failed: C:\Users\baron\Desktop\#Flutter\building_layouts_gridview\test\widget_test.dart
FormatException: Invalid character (at character 24)
C:/Users/baron/Desktop/#Flutter/building_layouts_gridview/test/widget_test....
                       ^

#0      _Uri._fail (dart:core/uri.dart:1614:5)
#1      _Uri._normalize (dart:core/uri.dart:2309:11)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2265:12)
#3      _Uri._makePath (dart:core/uri.dart:2113:16)
#4      new _Uri (dart:core/uri.dart:1514:12)
#5      FileSystemState._absolutePathToFileUri (package:analyzer/src/dart/analysis/file_state.dart:944:18)
#6      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:821:28)
#7      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1206:31)
<asynchronous suspension>
#8      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:39)
<asynchronous suspension>
#9      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#10     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#11     new AnalysisServer (package:analysis_server/src/analysis_server.dart:391:29)
#12     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:78:26)

**Comment by bwilkerson** [comment] 2018-09-30 15:35
@scheglov @DanTup I'm guessing that we need to encode any characters that are valid in a Windows file path that are not valid in a URI. I'm not sure, though, whether we need to do that in `FileSystemState` or whether `Uri` should be updated to handle this case, though I'm leaning toward the latter. Thoughts?

**Comment by DanTup** [comment] 2018-09-30 20:49
I guess this is a dupe of https://github.com/dart-lang/sdk/issues/32532 and it repros on macOS too.

From the stack it looks like this code is calling `new Uri` and not `new Uri.file` - maybe it'd encode correctly if we changed it?

**Comment by DanTup** [comment] 2018-09-30 20:52
Looks like the code is this:

https://github.com/dart-lang/sdk/blob/fa3d8fa5679c0bb14c9abead9705a0dfbeb16166/pkg/analyzer/lib/src/dart/analysis/file_state.dart#L980

Looks a bit suspect?

In DartPad:

```dart
  print(new Uri.file("C:\\test\\#flutter").toFilePath());
  print(new Uri(scheme: "file", path: "C:/test/#flutter").toFilePath());
```

Outputs:

```
C:\test\#flutter
Uncaught exception:
FormatException: Invalid character (at character 9)
C:/test/#flutter
```

**Comment by bwilkerson** [comment] 2018-10-01 00:58
I looked at the code, but missed that. Good catch! Do you want to make the change?

**Comment by scheglov** [comment] 2018-10-01 01:00
We don't need `fileUri` anymore - it was for CFE integration.
I will remove it.

**Comment by scheglov** [comment] 2018-10-01 01:05
https://dart-review.googlesource.com/c/sdk/+/77268

**Closed** 2018-10-01 01:36 UTC
Labels: area-analyzer, os-windows, type-bug

**Comment by DanTup** [comment] 2018-10-01 06:38
Great, thanks! I've made a note to test #32532 with all the characters in my original test when next on Windows to see if it whether there are still any issues there (call stack looks slightly different).

**Comment by DanTup** [comment] 2018-10-01 10:57
I realise the other issue I linked was about the SDK location, not project. I'll test that next. But FWIW, I just opened a project in a folder named `#Dart-Test-!£$%^&()_+-=,.@~;'#[]{}` and in a quick test, everything seems good 👍
