### ISSUE TITLE
Dart analysis server Error

### ISSUE THREAD

**Issue by kaushiksamanta** [dart-lang/sdk#36054] opened 2019-02-27 23:33 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-183.5429.30`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IC-183.5429.30, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3, screens 1440x900, 2560x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Failed to send notification
NoSuchMethodError: The getter 'returnType' was called on null.
Receiver: null
Tried calling: returnType
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      DartUnitOutlineComputer._newGenericTypeAliasOutline (package:analysis_server/src/computer/computer_outline.dart:232:46)
#2      DartUnitOutlineComputer.compute (package:analysis_server/src/computer/computer_outline.dart:68:26)
#3      sendAnalysisNotificationOutline.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:134:41)
#4      _sendNotification.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:171:8)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#6      _sendNotification (package:analysis_server/src/operation/operation_analysis.dart:169:39)
#7      sendAnalysisNotificationOutline (package:analysis_server/src/operation/operation_analysis.dart:121:3)
#8      ServerContextManagerCallbacks.addAnalysisDriver.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:905:13)
#9      new Future.<anonymous closure> (dart:async/future.dart:176:37)
#10     _rootRun (dart:async/zone.dart:1120:38)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/my/lqgvw_xj0dd8p6lzxcj_jy7w0000gn/T/report.txt.

**Comment by stereotype441** [comment] 2019-03-01 23:06
Duplicate of #36059

**Closed by stereotype441** 2019-03-01 23:06 UTC
Labels: analyzer-server, area-analyzer
