### ISSUE TITLE
add OpenBSD support

### ISSUE THREAD

**Issue by meciks** [dart-lang/sdk#48200] opened 2022-01-23 20:27 UTC
Please add OpenBSD support

**Comment by bernaferrari** [comment] 2022-01-23 20:55
Duplicate of https://github.com/dart-lang/sdk/issues/10260

**Closed** 2022-01-24 09:24 UTC

**Comment by mraleph** [comment] 2022-01-24 09:28
Unfortunately we don't have resources to build *BSD support. We could be open to merging a *BSD support into mainline under the assumption that the port is going to be maintained by somebody else e.g. this somebody else will have to fix build issues, maintain CI, provide prebuilt binaries etc.
