### ISSUE TITLE
Patterns parser assert failure

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/sdk#52462] opened 2023-05-22 10:47 UTC
The following (invalid as I understand it) code crashes the parser with an assert error (it seems to "work fine" without asserts):

```dart
var ((a1,)?,)? = null;
```

/cc @stereotype441

**Comment by jensjoha** [comment] 2023-05-22 12:20
Hmm. It crashes the same way on `var ((a1,)?,) = ((-1,),);` when parsing without pattern support, so not really pattern-related anyway. I think we should just remove the assert, and I'll go ahead and do that. Sorry for the noise.

**Comment by stereotype441** [comment] 2023-05-22 13:32
Let's go ahead and keep the issue open until the problem is fixed, and then when the fix lands we can close it with a pointer to the commit that fixes it.

**Comment by stereotype441** [comment] 2023-05-25 18:32
Fixed in 284296f8628a56d22ec44f75a7220e6cbd5b466e.

**Closed by stereotype441** 2023-05-25 18:32 UTC
Labels: front-end-fasta, area-front-end
