### ISSUE TITLE
Failures on Front end: fix type inference for object patterns that refer to typedefs.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51834] opened 2023-03-23 15:46 UTC
There are new test failures on [Front end: fix type inference for object patterns that refer to typedefs.](https://dart-review.googlesource.com/c/sdk/+/290900).

The tests
```
language/patterns/object_pattern_inference_test RuntimeError (expected Pass)
```
are failing on configurations
```
dart2wasm-hostasserts-linux-x64-d8
```

Since this test isn't failing on other configurations, I suspect this is a problem specific to the dart2wasm back-end.

**Comment by osa1** [comment] 2023-04-03 07:16
Smaller repro:

```dart
class H1<T> {}

typedef H2<S extends num> = H1<S>;

bool test(Object o) {
  return o is H2;
}

void main() {
  print(test(H1<Object>()));
}
```

This should print `false`, with dart2wasm it prints `true`.

Looks like a runtime type checker bug.

**Comment by osa1** [comment] 2023-04-03 07:25
Duplicate of #51187. We have a fix but we can't merge it yet as it breaks demo apps because of an issue in JS interop libs. Tracked in #51200.

**Closed by osa1** 2023-04-03 07:25 UTC
Labels: area-dart2wasm
