### ISSUE TITLE
corelib/date_time7_test.dart confused about transition from winter time to summer time

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#55157] opened 2024-03-11 14:09 UTC
`corelib/date_time7_test` seems to fail during the period of time where the US uses summer time and EMEA has not yet switched to summer time (as shown, for example, [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8753762285964058689/+/u/test_results/new_test_failures__logs_)).

**Comment by aam** [comment] 2024-03-11 15:31
Duplicate of https://github.com/dart-lang/sdk/issues/55159

**Closed by aam** 2024-03-11 15:31 UTC
Labels: library-core, area-test
