### ISSUE TITLE
Calling some getters on some DOM types returns null

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#27578] opened 2016-10-12 21:40 UTC
A number of HTML tests fail because they call `.supported`, usually a static method on some type to do feature detection. Examples:

```dart
// audiobuffersourcenode_test.dart
expect(AudioContext.supported, isTrue);

// crypto_test.dart
expect(Crypto.supported, true);
```

These calls are returning `null` instead of a boolean value.

**Comment by munificent** [comment] 2016-10-12 21:41
I'm seeing this with some other properties too, so I'm just going to make this a catch-all bug. Once I check in, you can look for this issue number in https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/test/browser/language_tests.js to see the affected tests.

**Comment by jmesserly** [comment] 2016-10-17 19:30
Yeah we probably don't support statics defined on native types at all (e.g. HTML types). dart:core wouldn't have needed that so I doubt it was considered.

Brainstorming a bit:
* we could copy these properties over. But we'd have to change the calling convention to symbolize them, so we don't conflict with existing statics on the native JS object.
* probably better, we should just generate the call using the Dart extension class name. 

I wonder if we have a similar problem with constructors (factory or not). I guess those must be working (e.g. `new Element.div()`), but I'm not sure why they would be.

**Comment by jmesserly** [comment] 2016-10-21 00:11
dupe of #27642

**Closed by jmesserly** 2016-10-21 00:11 UTC
Labels: area-dev-compiler, library-html
