### ISSUE TITLE
Analysis server failure: "Only absolute paths are supported"

### ISSUE THREAD

**Issue by vlehung** [dart-lang/sdk#35436] opened 2018-12-18 03:26 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-183.4588.61`
- `2.1.0`
- `IU-183.4588.61, JRE 1.8.0_152-release-1343-b16x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1440x900, 1440x900`

# Exception

Please append the contents of:
file://C:\Users\hella\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0, server version 1.21.1, FATAL error: Failed to handle request: {id: 614, method: edit.getAssists, params: {file: localhost:53322\packages\DemoDart\app_component.template.dart, offset: 0, length: 0}, clientRequestTime: 1545103556189}
Invalid argument(s): Only absolute paths are supported: localhost:53322\packages\DemoDart\app_component.template.dart
#0      AnalysisDriver._throwIfNotAbsolutePath (package:analyzer/src/dart/analysis/driver.dart:1641:7)
#1      AnalysisDriver.getResult (package:analyzer/src/dart/analysis/driver.dart:757:5)
#2      AnalysisServer.getAnalysisResult (package:analysis_server/src/analysis_server.dart:529:10)
#3      EditDomainHandler.getAssists (package:analysis_server/src/edit/edit_domain.dart:188:42)
<asynchronous suspension>
#4      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:355:9)
#5      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:645:45)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:641:50)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1500:12)

**Comment by stereotype441** [comment] 2018-12-18 16:00
Duplicate of #34152

**Closed** 2018-12-18 16:00 UTC
Labels: area-analyzer, os-windows, type-bug
