### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by cgdzin** [dart-lang/sdk#39424] opened 2019-11-18 09:23 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050, 1920x1080  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/peter.chinzorig/projects/ard.digitalbank/Flutter/digitalbank/lib/plugin/mp_chart/lib/mp/core/data_set/scatter_data_set.dart context: exception_20191118_172033_948
NoSuchMethodError: The method 'withNullability' was called on null.
Receiver: null
Tried calling: withNullability(Instance of 'NullabilitySuffix')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      InterfaceLeastUpperBoundHelper.compute (package:analyzer/src/generated/type_system.dart:2066:19)
#2      Dart2TypeSystem._interfaceLeastUpperBound (package:analyzer/src/generated/type_system.dart:987:19)
#3      TypeSystem.getLeastUpperBound (package:analyzer/src/generated/type_system.dart:2405:14)
#4      InferenceContext.addReturnOrYieldType (package:analyzer/src/generated/resolver.dart:2549:28)
#5      ResolverVisitor.visitReturnStatement (package:analyzer/src/generated/resolver.dart:4334:24)
#6      ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#8      ScopedVisitor.visitSwitchCase (package:analyzer/src/generated/resolver.dart:5732:23)
#9      ResolverVisitor.visitSwitchCase (package:analyzer/src/generated/resolver.dart:4431:11)
#10     SwitchCaseImpl.accept (package:analyzer/src/dart/ast/ast.dart:9548:49)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#12     ResolverVisitor.visitSwitchStatementInScope (package:analyzer/src/generated/resolver.dart:4469:22)
#13     ScopedVisitor.visitSwitchStatement (package:analyzer/src/generated/resolver.dart:5763:7)
#14     SwitchStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9704:49)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#16     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#17     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#18     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3128:31)
#19     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5171:13)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#21     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#22     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#23     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3131:55)
#24     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5182:13)
#25     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:3508:13)
#26     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#28     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4258:10)
#29     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3336:55)
#30     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:5669:11)
#31     ResolverVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:4207:11)
#32     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:5662:7)
#33     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:4198:13)
#34     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#36     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5248:18)
#37     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5226:11)
#38     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3552:13)
#39     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#40     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3594:23)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#42     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:698:10)
#43     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#44     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#45     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#46     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#47     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#48     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#49     AnalysisDriver._computeAnalysisResult.<anonymous closur...
```

For additional log information, please append the contents of
file:///private/var/folders/8q/82ck4q856j7dnq1syvp563_40000gp/T/report1.txt.

**Comment by srawlins** [comment] 2019-11-20 18:53
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38589; please follow along there.

**Comment by srawlins** [comment] 2019-11-20 18:53
Duplicate of https://github.com/dart-lang/sdk/issues/38589

**Closed by srawlins** 2019-11-20 18:53 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
