### ISSUE TITLE
Analysis duration increases when using an `include` in the analysis_options.yaml

### ISSUE THREAD

**Issue by joshprzybyszewski-wf** [dart-lang/sdk#46652] opened 2021-07-19 15:28 UTC
# Problem 

In a private repo (where we still use dart 2.7.2), our analysis takes a long time. On my local machine (`MacBook Pro (16-inch, 2019)`, `2.6 GHz 6-Core Intel Core i7`, `64 GB 2667 MHz DDR4`), a full `ddev analyze` (`alias ddev='pub run dart_dev'`)  takes upwards of 10 minutes for more than 4300 source files. Since we _are_ behind in dart versions, we hoped newer versions of dart would improve analysis, so we also collected results in 2.13.x (where our repo won't build, but we can still analyze). We _did_ see an improvement in durations from 2.7.2, but the workaround also produces the same improvement. Continue reading for all dart version results.

## What is the poblem?

In our analysis_options.yaml, we include the [default recommended lints from Workiva](https://github.com/Workiva/workiva_analysis_options):

```yaml
include: package:workiva_analysis_options/v1.recommended.yaml
```

As a public example, Workiva/over_react uses [a similar pattern](https://github.com/Workiva/over_react/blob/cc6f181ec06cdb06a5f3e478452fc39513102a16/analysis_options.yaml#L1):

```yaml
include: package:pedantic/analysis_options.1.8.0.yaml
```

# Workaround

We have noticed that manually defining the lints/rules that the `include`d yaml defines reduces the duration of both `ddev analyze` and `dart analyze` significantly. For an example, see [this public Draft PR](https://github.com/Workiva/over_react/pull/694).

## Private results

In our private repo, we gathered a bunch of data for times of `ddev analyze` and `dart analyze` in different dart versions. I've included them below to show the data we're using

### `ddev analyze` reported duration

| dart version | using the `include` | redefining all rules/lints | % change |
| - | -: | -: | -: |
| 2.7.2 | 700.0s | 256.5s | -63% |
| 2.13.1 | 441.4s | 445.9s | +1% |
| 2.13.4 | 353.5s | 100.9s | -71% |

### `dart analyze` reported duration

| dart version | using the `include` | redefining all rules/lints | % change |
| - | -: | -: | -: |
| 2.7.2 | N/A | N/A | N/A |
| 2.13.1 | 261.6s | 111.0s | -57.6% |
| 2.13.4 | 109.7s | 23.9s | -78% |

## Public results

In an effort to provide a publicly viewable diff of the workaround, I've [drafted up a change in over_react](https://github.com/Workiva/over_react/pull/694) (where I'm less familiar). In CI, we can see a 26% improvement in `ddev analyze` duration (in dart 2.7.2).

| config | using the `include` | redefining all rules/lints | % change |
| - | -: | -: | -: |
| example source (12 files) | 10.0s | 7.4s | -26% |
| project source (598 files) | 32.6s | 23.9s | -26% |

**Comment by patkujawa-wf** [comment] 2021-07-19 15:41
@joshprzybyszewski-wf this was also tested in later dart versions, right? So not just something about 2.7.2?

**Comment by devoncarew** [comment] 2021-07-19 16:13
Interesting - thanks for the detailed bug report!

Can you briefly say how `ddev analyze` is written / what it does? I see that we see similar perf changes in `dart analyze`, so knowing how `ddev analyze` works isn't critical, but could be useful info.

cc @scheglov - some profiling here may show the reasons for the perf difference. @joshprzybyszewski-wf - I see that the above repro is for a private repository. Is there another reproduction you're aware of - something we could clone?

**Comment by devoncarew** [comment] 2021-07-19 16:13
Ah, the over_react repo, above.

**Comment by joshprzybyszewski-wf** [comment] 2021-07-19 16:14
@devoncarew thanks for the call out! I've updated the description: `alias ddev='pub run dart_dev'`.

**Comment by dustyholmes-wf** [comment] 2021-07-19 16:17
dart_dev is available publicly [here](https://github.com/Workiva/dart_dev). 

In the repository we've been testing in, we are using the [tuneup tool](https://github.com/Workiva/dart_dev/blob/master/lib/src/tools/tuneup_check_tool.dart).

**Comment by scheglov** [comment] 2021-07-19 17:42
I'm not able to reproduce the changes in timings.

Here is what I did:
1. Cloned `https://github.com/Workiva/over_react`, run `dart pub get`.
2. Have two copies of `analysis_options.yaml` in its root - one is original, and another is from https://github.com/Workiva/over_react/pull/694.
3. I remove `/Users/scheglov/.dartServer/.analysis-driver` where `dart analyze` keeps results between invocations, and reuse when possible.
4. I tried more or less latest `Dart SDK` build `Dart SDK version: 2.14.0-edge.6a87d049acafbf4d8e251b9ab15b5c3623bcad61`, and run `time dart analyze .`. With any version of `analysis_options.yaml` time is similar - about `34` or `35` seconds (from `time`, the tool itself shows about `25` seconds).
5. `time pub run dart_dev analyze` gives comparable results - `37` or `38` seconds, regardless of which options file is used.

I also tried `dart-sdk-2.9.1` and while timings were higher, there were no difference between the version of `analysis_options.yaml` file.

**Comment by joshprzybyszewski-wf** [comment] 2021-07-22 15:21
@scheglov I'm sorry that over_react isn't reproing on your local machine. We see a consistent improvement in our private repo analyze performance; I wish I could share it. I did some digging, and it seems that the flutter repo intentionally doesn't use `include:` because they encountered the same problem.

https://github.com/flutter/flutter/pull/26244#issuecomment-453643222

Additionally, it looks like they've already filed an issue for this. Now that we have two separate reports of this issue, could we get it re-prioritized?

https://github.com/dart-lang/sdk/issues/35637

**Comment by devoncarew** [comment] 2021-07-22 15:45
@joshprzybyszewski-wf - the flutter reported bug was 2 1/2 years ago and we've made some significant changes to the codebase, so it's likely obsolete.

I see for the 'Public results' section in your first comment, you've run tests against your public repo and ddev. That's using dartanalyzer; do you mind adding a row(s) for `dart analyze`? That uses the analysis server, and would match up with what @scheglov tried to repro.

For context, we're much more interested in addressing performance issues with the analysis server (at head) rather than in `dartanalyzer`, as we do plan to deprecate that tool in the near term (in favor of `dart analyze`).

**Comment by jcollins-g** [comment] 2021-08-31 22:23
IIUC, the problem is that in an old version of analyzer, importing analysis_options.yaml files greatly degrades performance.  However, when tested at or near head, this problem is not reproducible.  Given that it is not reproducible at head, closing.

If my understanding is not correct, please reopen/refile as appropriate.

**Closed by jcollins-g** 2021-08-31 22:23 UTC
Labels: area-analyzer
