### ISSUE TITLE
dart2js: rejects annotations on local variables

### ISSUE THREAD

**Issue by chalin** [dart-lang/sdk#23736] opened 2015-06-27 01:16 UTC
According to the language spec (2nd ed.), Section 15:

> Metadata can appear before a ... variable declaration ...

E.g.

```dart
const a = 0;
main() {
  @a int i = 0;
  return i;
}
```

results in

```shell
dart2js dart2js-2016-06-26.dart
dart2js-2016-06-26.dart:3:3:
Error: Expected an expression, but got '@'.
  @a int i = 0;
  ^
Error: Compilation failed.
```

but the same code is fine according to the analyzer

```shell
dartanalyzer dart2js-2016-06-26.dart
Analyzing [dart2js-2016-06-26.dart]...
No issues found
```

**Comment by floitschG** [comment] 2015-06-29 16:49
On my machine 1.11.0 still aborts the compilation.
From what I remember "ensureResolved" should only be called in the lazy emitter which isn't on, unless with special flags. If you can reproduce, please let me know and I will have a look to see how `ensureResolved` made it into the output... (and why it even finished compliing).

This issue is a duplicate of #19061.

**Closed by floitschG** 2015-06-29 16:49 UTC
Labels: Area-Dart2JS
