### ISSUE TITLE
[dart:jsinterop] Allow function types in function declarations.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#59672] opened 2024-12-06 09:27 UTC
Current: 
```dart
import 'dart:js_interop';

typedef EventDispatcher<T> = bool Function(
  String type,
  T detail, {
  bool cancelable,
});

@anonymous
extension type _EventDispatcherOptions._(JSObject _) implements JSObject {
  external factory _EventDispatcherOptions({bool cancelable});
}

@JS('createEventDispatcher')
external JSFunction _createEventDispatcher();

EventDispatcher<T> createEventDispatcher<T>() {
  var jsFunction = _createEventDispatcher();

  return (
    String type,
    T detail, {
    bool cancelable = false,
  }) {
    var jsResult = jsFunction.callAsFunction(
      null,
      type.toJS,
      // ignore: invalid_runtime_check_with_js_interop_types
      ref(detail) as JSAny?,
      _EventDispatcherOptions(cancelable: cancelable),
    ) as JSBoolean;

    return jsResult.toDart;
  };
}
```
Expected:
```dart
import 'dart:js_interop';

typedef EventDispatcher<T> = bool Function(
  String type,
  T detail, {
  bool cancelable,
});

@anonymous
extension type _EventDispatcherOptions._(JSObject _) implements JSObject {
  external factory _EventDispatcherOptions({bool cancelable});
}

typedef _JSEventDispatcher<T> = bool Function(
  String type,
  ExternalDartReference<T> detail, [
  _EventDispatcherOptions options,
]);

@JS('createEventDispatcher')
external _JSEventDispatcher _createEventDispatcher();

EventDispatcher<T> createEventDispatcher<T>() {
  var jsFunction = _createEventDispatcher();

  return (
    String type,
    T detail, {
    bool cancelable = false,
  }) {
    return jsFunction(
      type,
      // ignore: invalid_runtime_check_with_js_interop_types
      ref(detail),
      _EventDispatcherOptions(cancelable: cancelable),
    );
  };
}
```

_PS: I miss and pressed `Enter` while editing._

**Comment by srujzs** [comment] 2024-12-06 21:39
Duplicate of https://github.com/dart-lang/sdk/issues/54557

**Closed** 2024-12-06 21:39 UTC
Labels: web-js-interop, type-enhancement, area-web, triage-automation
