### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Could not load dart file /D:/flutter/machineweb/machineweb/lib/main.dart

### ISSUE THREAD

**Issue by Sarthak-source** [dart-lang/sdk#45796] opened 2021-04-22 06:43 UTC
Could not load dart file /D:/flutter/machineweb/machineweb/lib/main.dart

Error: Error reaching migration preview server.

Please fill in the following:

**Name of package being migrated (if public)**:
**What I was doing when this issue occurred**:
**Is it possible to work around this issue**:
**Has this issue happened before, and if so, how often**:
**Dart SDK version**: 2.13.0-116.0.dev
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
Error reaching migration preview server.
    at Object.b (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:311:3)
    at http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:3126:9
    at Gs.a (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:1572:72)
    at Gs.$2 (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:4664:23)
    at SX.$2 (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:4659:25)
    at Ji.rp (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:4935:25)
    at Fe.Kw (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:4721:27)
    at RW.$0 (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:4869:42)
    at Object.HZ (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:1620:76)
    at vs.ZL (http://127.0.0.1:55433/D:/flutter/machineweb/machineweb?authToken=c_Z397Xokl8%3D:4782:3)
```

**Comment by stereotype441** [comment] 2021-04-22 12:19
This error occurs if the preview server has already exited.  Please try restarting the preview server on the command line and clicking on the new link it creates.

In more recent dev and beta versions (2.13.0-165.0.dev and 2.13.0-211.1.beta) the error message has been fixed so that it no longer looks like a crash, and instead explains that a restart of the preview server is needed.

**Comment by stereotype441** [comment] 2021-04-22 12:19
Duplicate of #45202.

**Closed by stereotype441** 2021-04-22 12:19 UTC
Labels: area-migration, type-bug
