### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by HackSoul** [dart-lang/sdk#34785] opened 2018-10-14 02:22 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5014246`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5014246, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/64/fswhg6s107g5jwr4fn04pwwc0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/jiyouxu/StudioProjects/community_app/lib/page/home/tag/zone/write_blog_page.dart context: exception_20181014_102200_324
Exception: Element not found in summary: package:flutter/src/widgets/editable_text.dart

**Comment by MichaelRFairhurst** [comment] 2018-10-17 17:07
Thanks for filing!

Possible duplicate of #34716 

Can you provide us with either a stack trace or a short set of reproduction steps (or both)? Without either of those there's probably nothing we can do to track this down.

For example, did this happen as a result of doing a flutter upgrade?

@scheglov

**Comment by scheglov** [comment] 2018-10-17 17:13
Probably https://github.com/dart-lang/sdk/issues/34823

**Closed by scheglov** 2018-10-17 17:13 UTC
Labels: area-analyzer, needs-info, type-bug
