### ISSUE TITLE
Is there a way to hot reload certificate with SecureServerSocket?

### ISSUE THREAD

**Issue by busslina** [dart-lang/sdk#53547] opened 2023-09-17 21:32 UTC
When the certificate is expired or close to expire, I generate a new certificate with exactly the same path. My desired behaviour is that yet established connections continue to work and new connections use the new certificate.

I tested it and it is still being used the previous certificate version.

Thank you

**Comment by devoncarew** [comment] 2023-09-18 16:59
I suspect no, and that you'd have to restart the server itself.

cc @brianquinlan

**Comment by brianquinlan** [comment] 2023-09-18 17:34
Hey @busslina, 

I suspect that you will have to restart your server.

If you are using a `SecurityContext` to set your certificates then you could try to load them again but I don't think that that will actually work.

**Comment by busslina** [comment] 2023-09-18 23:12
And is it feasible to implement my own custom server on top of SecureServerSocket in order to check SSL changes before every incoming connection?

I'm only interested in Linux at this moment.

**Comment by busslina** [comment] 2023-09-19 21:12
@brianquinlan The idea is to check if SSL files are changed before every incoming requets, by checking its last update timestamp. Also, I am using SecurityContext. I just wonder if extending SecureServerSocket would be diffiicult.

Also, this hot reload feature could be a future objective of Dart SDK (if you consider positive).

Thanks

**Comment by a-siva** [comment] 2023-10-12 16:47
Is there anything more to be done on this issue? I am going to close it as 'works as intended'.

**Closed** 2023-10-12 16:47 UTC
Labels: area-vm, closed-as-intended, library-io, type-question

**Comment by busslina** [comment] 2023-10-12 21:22
> Is there anything more to be done on this issue? I am going to close it as 'works as intended'.

I have another question. A `SecureSocket` can check the certificate content on `onBadCertificate`. Is there a way to check the client certificate in`SecureServerSocket` on success or bad certificate. I think Dart Api should allow to see both sides certificates on success and on error.

**Comment by brianquinlan** [comment] 2023-10-13 23:32
No, there is no way to 

> > Is there anything more to be done on this issue? I am going to close it as 'works as intended'.
> 
> I have another question. A `SecureSocket` can check the certificate content on `onBadCertificate`. Is there a way to check the client certificate in`SecureServerSocket` on success or bad certificate. I think Dart Api should allow to see both sides certificates on success and on error.

Can you simulate the behavior that you want by setting an empty `SecurityContext`?

**Comment by busslina** [comment] 2023-10-14 00:49
@brianquinlan 

When I say "to check" certificates I mean to be able to read/decode the other side certificate that is being used. I don't want to accept/deny by myself a certificate, just read it's information (subject, country, ...)
