### ISSUE TITLE
regression in the snapshot format?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#28510] opened 2017-01-25 18:11 UTC
When running the pub snapshot in checked mode (which we do when running unit tests from IntelliJ), we're now seeing this issue:

```
Wrong features in snapshot, expected 'release asserts type-checks x64-sysv' found 'release no-asserts no-type-checks x64-sysv'
```

You can repo in the latest dev sdk (`1.22.0-dev.9.1`) by:

```
./bin/dart --checked ./bin/snapshots/pub.dart.snapshot 
```

@rmacnak-google I'm assuming you're the right person to look at this, but please re-assign if not.

/cc @a-siva

**Comment by rmacnak-google** [comment] 2017-01-25 18:32
Duplicate of dart-lang/pub#1504.

**Closed by rmacnak-google** 2017-01-25 18:32 UTC
Labels: area-vm, P1 high
