### ISSUE TITLE
Dart compiler crash

### ISSUE THREAD

**Issue by Clay3981** [dart-lang/sdk#25607] opened 2016-01-28 18:10 UTC
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04

Dart VM version: 1.14.0-dev.7.2

web/packages/$sdk/lib/_internal/js_runtime/lib/constant_map.dart:74:13:
Compiler has unexpected field _length for ConstantStringMap.
  final int _length;
            ^^^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Internal Error: Compiler has unexpected field _len$th for ConstantStringMap.
package:compiler/src/compiler.dart 1846                         _CompilerDiagnosticReporter.internalError
package:compiler/src/js_backend/constant_emitter.dart 225       ConstantEmitter.visitMap.<fn>
package:compiler/src/elements/common.dart 362                   ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachIns$anceField.fieldFilter
package:compiler/src/elements/common.dart 329                   ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMem$er.<fn>
package:compiler/src/util/link_implementation.dart 120          LinkEntry.forEach
package:compiler/src/elements/modelx.dart 2758                  ClassElementX.forEachLocalMember
package:compiler/src/elements/common.dart 329                   ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMemb
er
package:compiler/src/elements/common.dart 366                   ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachInst
anceField
package:compiler/src/js_backend/constant_emitter.dart 210       ConstantEmitter.visitMap
package:compiler/src/constants/values.dart 539                  MapConstantValue.accept
package:compiler/src/js_backend/constant_emitter.dart 54        ConstantEmitter._visit
package:compiler/src/js_backend/constant_emitter.dart 50        ConstantEmitter.generate
package:compiler/src/js_emitter/full_emitter/emitter.dart 279   Emitter.constantInitializerExpression
package:compiler/src/js_emitter/full_emitter/emitter.dart 818   Emitter.buildConstantInitializer
package:compiler/src/js_emitter/full_emitter/emitter.dart 808   Emitter.buildCompileTimeConstants
package:compiler/src/js_emitter/full_emitter/emitter.dart 1564  Emitter.buildOutputAstForMain
package:compiler/src/js_emitter/full_emitter/emitter.dart 1802  Emitter.emitProgram
package:compiler/src/js_emitter/code_emitter_task.dart 146      CodeEmitterTask.assembleProgram.<fn>
package:compiler/src/common/tasks.dart 55                       CompilerTask.measure
package:compiler/src/js_emitter/code_emitter_task.dart 140      CodeEmitterTask.assembleProgram
package:compiler/src/js_backend/backend.dart 1636               JavaScriptBackend.assembleProgram
package:compiler/src/compiler.dart 1059                         Compiler.compileLoadedLibraries
package:compiler/src/compiler.dart 876                          Compiler.runInternal.<fn>
Build completed with 2 errors.

**Comment by sigmundch** [comment] 2016-02-04 23:07
Hi @Clay3981, thanks for reporting the bug. Do you have an example program that we can use to reproduce this crash ourselves?

I'm not sure yet what can be causing this. The error seems to be reported from a place where we do something on each field of the ConstantStringMap and we seem to find a field that is unexpected ([constant_emitter.dart L211](https://github.com/dart-lang/sdk/blob/61eb81b9d6f7100b91c39a5997a9dd696e116584/pkg/compiler/lib/src/js_backend/constant_emitter.dart#L211)). We actually expect to see `_length`, which is why the error is a bit surprising. Curiously, the second error message says `_len$th` instead of `_length`.

**Comment by Clay3981** [comment] 2016-02-11 15:28
Sorry I don't have an example program since I am not able to reproduce the issue. I have only encountered it that one time.

**Comment by sigmundch** [comment] 2016-02-11 22:47
I see - thanks again. If you happen to see it again, please let us know/reopen. For now I'm closing the bug since we haven't figured out yet a way to reproduce it.

**Closed by sigmundch** 2016-02-11 22:47 UTC
Labels: area-dart2js, dart2js-crash, Priority-Medium, Type-Defect
