### ISSUE TITLE
Source spans for errors from Frontend don't look right

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30762] opened 2017-09-15 22:40 UTC
It looks like error messages coming from Frontend don't have correct source code spans(line 1, column 11235 doesn't look right):

```
[  +13 ms] Compiling dart to kernel with 609 updated files
[+7245 ms] compile debug message: Warning: line 1, column 11235 of ../../packages/flutter/lib/src/rendering/binding.dart: Superclass has no method named 'hitTest'.
[+12731 ms] compile debug message: Nit: line 1, column 229 of lib/demo/material/date_and_time_picker_demo.dart: Import of 'TextDirection' (from 'package:intl/intl.dart') hides import from 'dart:ui'.
[  +79 ms] compile debug message: Nit: line 1, column 271 of lib/demo/material/full_screen_dialog_demo.dart: Import of 'TextDirection' (from 'package:intl/intl.dart') hides import from 'dart:ui'.
[+2567 ms] compile debug message: Nit: line 1, column 235 of lib/gallery/item.dart: Import of 'Flow' (from 'package:flutter/src/widgets/basic.dart') hides import from 'dart:developer'.
```

This is on Flutter source code.

@scheglov

**Comment by jensjoha** [comment] 2018-01-09 08:09
While it's the other way around, this is a duplicate of #31652. Closing.

**Closed by jensjoha** 2018-01-09 08:09 UTC
Labels: area-front-end
