### ISSUE TITLE
Call to runtimeType raises exception in generated js, checking type with IS or == misbehaves

### ISSUE THREAD

**Issue by snitko** [dart-lang/sdk#28255] opened 2017-01-04 15:25 UTC
After upgrading to version 1.21.0, dart2js started misbehaving in a weird manner. I'll try to explain the situation, but it's still unclear to me what's happening. The only thing I can claim for sure is that reverting back to 1.20.1 fixes the issue.

I have a class with `noSuchMethod` which I make use of to create dynamic getters and setters. When an object of any type is returned from such a getter (in reality, from `noSuchMethod`) it misbehaves. For example if a `null` is returned and, say, is assigned to an `x` variable then:

1. `x == null` evaluates to false
2. while `x is Null` evaluates to `true`.

If a `String` is returned, then

1. `x is String` and `x is Null` would both be `true`
2. while `x == null` would be `false`.

Additionally, calling `x.runtimeType` causes an exception.

It seems the issue only manifests itself when the value is returned from `noSuchMethod`, regular variables, methods and literals are unaffected. And **this is only in compiled js**. Dart code works fine. Once again, reverting to 1.20.1 solves the issue.

**Comment by lrhn** [comment] 2017-01-04 15:50
It doesn't reproduce for me in in a simple example (https://dartpad.dartlang.org/a003a1828aecd3886973c0cbf3091b00).

Are you using the "trust type annotations" option?
Do you have a small example that shows the problem?

**Comment by snitko** [comment] 2017-01-04 16:02
> Are you using the "trust type annotations" option?
Do you mean the `-c` option from https://webdev.dartlang.org/tools/dart2js#options? If that's the one you mean, then yes, I tried both with it and without. Same result.

> Do you have a small example that shows the problem?
Not at the moment. I'm not surprised you cannot reproduce it, I'm not sure myself this misbehavior is due to `noSuchMethod`. I was trying to isolate the issue, but haven't managed to do so. I'll be happy to provide a simple example that reproduces the problem, but it'd be nice if you or someone else could maybe come up with some ideas as to what might possibly be the cause of that.

I have a rather big (but relatively well written) lib code in which the problem manifests itself, let me know if it'd be helpful for you to look at it, I'll point you in all the right places.

**Comment by floitschG** [comment] 2017-01-04 16:19
Any repro would currently help, even if it's big. Ideally, we would prefer working from sources, but if necessary, we could also try to debug the (unminified) dart2js output. It's not clear if that would give us enough information to diagnose the problem, but I/we could give it a shot.

**Comment by snitko** [comment] 2017-01-04 16:26
Thank you Florian.

Here's where you should be looking: https://github.com/snitko/nest_ui/blob/master/lib/component.dart#L389
https://github.com/snitko/dart-attributable/blob/master/lib/attributable.dart#L114

I tried testing the Null/String values inside both of those methods, they work fine. Only when they are returned from `noSuchMethod` it seems that there's a problem. Additionally, I made sure that the values returned from `prvt_noSuchGetterOrSetter` are the ones that I get a problem with - they are. That is, nothing in between seems to be interfering.

I'll be working on isolating the problem tonight and will let you know if I can reproduce the issue with a simpler piece of code outside of the library. Please let me know if you get any ideas yourself. Thanks a lot for your help, I hope we can narrow this bug down.

**Comment by floitschG** [comment] 2017-01-04 17:52
Do you have a way to trigger the problem?
I tried to run `test/behaviors_test.dart` and that one worked for me (with trunk).

**Comment by floitschG** [comment] 2017-01-04 18:35
I still can't reproduce.

My latest attempt looks as follows:

``` dart
import 'package:attributable/attributable.dart';

class T extends Attributable {

  final List attribute_names = ['caption', 'color', 'enabled'];

  final Map attribute_callbacks = {
    'default' : (attr_name, self) => print("Attribute $attr_name now has a new value: ${self.attributes[attr_name]}"),
    'caption' : (attr_name, self) => print("Caption is now '${self.caption}'"),
    'enabled' : (attr_name, self) => print("Enabled is now set to '${self.enabled}'")
  };

  noSuchMethod(Invocation i) {
    try {
      return prvt_noSuchGetterOrSetter(i);
    } on NoSuchAttributeException {
      super.noSuchMethod(i);
    }
  }
}

main() {
  var o = new T();
  o.caption = "New caption";
  o.enabled = true;
  o.color = 'green';
  o.enabled = null;
  print(o.enabled == null);
  print(o.enabled is Null);
  print(o.color is String);
  print(o.color is Null);
  print(o.color == null);
```

Which (compiled with dart2js 1.21) results in:
```
Caption is now 'New caption'
Enabled is now set to 'true'
Attribute color now has a new value: green
Enabled is now set to 'null'
true
true
true
false
false
```

This looks like the expected output.

**Comment by snitko** [comment] 2017-01-04 19:51
I was able to create a more or less isolated example (attached). The problem seems to be within `nest_ui` lib and not `attributable`. In the attachment you'll find files compiled with both 1.20.1 and 1.21.0. The latter clearly evaluates incorrectly and then an exception is raised when `runtimeType` is called. I hope having two compiled javascript files will help, although running `diff` on them wasn't useful to me, it just spewed complete nonsense.

To make the Dart version work, make sure you run `pub get --packages-dir` first.
[dart_test.zip](https://github.com/dart-lang/sdk/files/685732/dart_test.zip)

Below is the dart code from which the files were compiled:

```
library myapp;
import 'package:nest_ui/nest_ui.dart';
import 'package:attributable/attributable.dart';

class MyComponent extends Component {

  List attribute_names = ["name", "login", "email"];

  noSuchMethod(i) {
    try {
      return prvt_noSuchGetterOrSetter(i);
    } on NoSuchAttributeException {
      super.noSuchMethod(i);
    }
  }

  MyComponent() {
    print(!(this.name is Null));
    print(this.name != null);
    print(this.name.runtimeType);
  }

}

main() {
  var app = new NestUIApp(app_library: 'myapp');
}
```

**Comment by floitschG** [comment] 2017-01-04 20:13
Thanks. I can reproduce now.

Interestingly the dart 1.21 from here doesn't exhibit the problem. This must have been added shortly after the first 1.21 dev release.

https://storage.googleapis.com/dart-archive/channels/dev/release/1.21.0-dev.0.0/sdk/dartsdk-linux-ia32-release.zip

**Comment by snitko** [comment] 2017-01-04 20:26
My installation of Dart is done with `apt-get`, the exact version is `1.21.0-1`.

**Comment by floitschG** [comment] 2017-01-04 20:27
I continued to investigate:
The 1.20 code produces:
```
      MyComponent$0: function() {
        P.print(!J.getInterceptor(this.get$name(this)).$isNull);
        P.print(this.get$name(this) != null);
        P.print(J.get$runtimeType$(this.get$name(this)));
      },
```

The 1.21 code produces:
```
      MyComponent$0: function() {
        this.get$name(this);
        P.print(false);
        this.get$name(this);
        P.print(true);
        var t1 = this.get$name(this);
        P.print(t1.get$runtimeType(t1));
      },
```

Somehow the compiler infers a non-null type for `name`...
I will continue to investigate (and then pass it on to someone on the dart2js team).

**Comment by snitko** [comment] 2017-01-04 20:31
You should also try assigning non-null types to the attribute, then printing it. As stated in the original post, even `String` values react inadequately to `is Null` returning `true` instead of `false`.

**Comment by floitschG** [comment] 2017-01-04 20:58
This bug was introduced with bdeb6023afc02c15e6a660823c3308c977022c26

@johnniwinther : could you have a look?

Also: this, seems to be unrelated to #28220.

**Comment by johnniwinther** [comment] 2017-01-05 08:35
I'll take a look.

**Comment by johnniwinther** [comment] 2017-01-05 15:58
I have committed a fix in https://github.com/dart-lang/sdk/commit/12491d4ab869b903870b0783c5fd715e8307b47d

This will be part of 1.22. Until then you can use this work-around: The compiler needs to see a direct instantiation of the class in question, that is, not only through mirrors. In the repo this can be done by adding:

    class MyComponent {
      MyComponent() {
        if (false) new MyComponent();
        ...
      }
    }

The call will be recognized as dead code and not be part of the output, but it will trigger a registration of a direct instantiation of the class, bypassing the erroneous code.

**Closed by johnniwinther** 2017-01-05 15:58 UTC
Labels: area-dart2js, Type: bug
