### ISSUE TITLE
The argument type 'SomeEnum/*1*/' can't be assigned to the parameter type 'SomeEnum/*2*/'

### ISSUE THREAD

**Issue by adrianvintu** [dart-lang/sdk#46177] opened 2021-05-28 09:10 UTC
I got a really strange message today:

lib/main.dart:9:16: Error: The argument type 'SomeEnum/*1*/' can't be assigned to the parameter type 'SomeEnum/*2*/'.    
 - 'SomeEnum/*1*/' is from 'package:test_path/test_path_folder/some_enum.dart' ('lib/test_path_folder/some_enum.dart').  
 - 'SomeEnum/*2*/' is from 'package:test_path/test_path_folder//some_enum.dart' ('lib/test_path_folder//some_enum.dart').
  p.someMethod(s);

It took me at least 10 minutes to find out the issue.

It seems I entered an invalid(?) path as import ```import '../test_path_folder//some_enum.dart';``` - notice the 2 slashes.

**Request:**
Can Dart/Flutter handle this situation with a more helpful message? Or treat the paths as identical?

**How to reproduce:**
1. flutter create new application
2.  create 2 sibling folders
```
C:\FLUTTER_TEMP\TEST_PATH\LIB
│   main.dart
│
├───test_path_folder
│       some_enum.dart
│
└───test_path_sibling_folder
        test_path_sibling.dart
```
3. create file **some_enum.dart**

```enum SomeEnum { a, b, c }```

4. create file **test_path_sibling.dart** - notice the double slash

```
import '../test_path_folder//some_enum.dart';

class TestPathSibling {
  someMethod(SomeEnum a) {
    print(a);
  }
}
```

5. main.dart contains:
```
void main() {
  SomeEnum someEnum = SomeEnum.b;
  print(someEnum);
  TestPathSibling p = TestPathSibling();
  p.someMethod(someEnum);

  runApp(MyApp());
}
```

![issue](https://user-images.githubusercontent.com/33379688/119855876-f6774a80-bf1a-11eb-9774-9a94cbe5b9b1.png)

**Comment by adrianvintu** [comment] 2021-05-28 09:11
Another variation I found is when test_path_sibling.dart contains ```import '../test_path_folder//some_enum.dart';```
but main.dart contains ```import 'test_path_sibling_folder//test_path_sibling.dart';``` the message is

```lib/test_path_sibling_folder//test_path_sibling.dart:1:8: Error: Error when reading 'lib/test_path_sibling_folder/test_path_folder/some_enum.dart': The system cannot find the path specified.```





![issue 2](https://user-images.githubusercontent.com/33379688/119856923-c67c7700-bf1b-11eb-91f9-4c32831985f6.jpg)

**Comment by lrhn** [comment] 2021-05-28 15:16
This is currently working as intended. 

It's another example of why using URIs to identify libraries, regardless of local path resolution, is not necessarily user friendly.

**Comment by adrianvintu** [comment] 2021-05-28 17:40
Oh, sorry to hear that. Thank you for your support.

**Comment by vsmenon** [comment] 2021-05-30 23:17
Closing in favor of lang issue.

**Closed by vsmenon** 2021-05-30 23:17 UTC
