### ISSUE TITLE
Warn if factory constructor does not contain a return <expr> statement

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#25612] opened 2016-01-29 01:02 UTC
I just accidentally defined a factory constructor that created but failed to return an object:

```dart
  factory ParameterElementImpl.synthetic(String name, DartType type,
      ParameterKind kind) {
    ParameterElementImpl element = new ParameterElementImpl(name, -1);
    element.type = type;
    element.synthetic = true;
    element.parameterKind = kind;
  }
```

It would be great to get a warning if there is no `return`, or if the `return` doesn't have a value.

**Comment by srawlins** [comment] 2016-04-20 23:01
Dupe of #17121.

**Closed** 2016-04-20 23:21 UTC
Labels: analyzer-hint, area-analyzer, P2 medium, Type: enhancement
