### ISSUE TITLE
Platform.executable does not return the '.exe' on Windows

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#23613] opened 2015-06-09 06:44 UTC
See https://github.com/dart-lang/test/issues/133 
and https://codereview.chromium.org/1165313002/

**Comment by bkonyi** [comment] 2018-06-29 22:41
It looks like this just has to do with how the script is invoked:

```
C:\Users\bkonyi\dart-sdk-2\sdk>out\DebugX64\dart tmp.dart
out\DebugX64\dart

C:\Users\bkonyi\dart-sdk-2\sdk>out\DebugX64\dart.exe tmp.dart
out\DebugX64\dart.exe
```
Should we be appending `.exe` to `Platform.executable` on Windows? From what I can tell, that wouldn't be a good solution since Windows doesn't require that executables have a `.exe` extension. I'm going to close this as working as intended for now.

cc/ @zanderso for potential input.

**Closed by bkonyi** 2018-06-29 22:41 UTC
Labels: Resolution: works as intended, area-library, library-io
