### ISSUE TITLE
[Analyzer] Weird typing issue

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/sdk#50399] opened 2022-11-07 12:20 UTC
This tracker is for issues related to:

* Analyzer

![image](https://user-images.githubusercontent.com/298850/200307856-16b52df0-f95e-48da-a5ed-5ade54fdbfad.png)

```
The element type 'DateTime?' can't be assigned to the list type 'Object'.
dart [list_element_type_not_assignable]
(https://dart.dev/diagnostics/list_element_type_not_assignable)
```

Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_arm64"

I came across this weird typing glitch. I realise I've not provided much information of worth here so if there is anything else I can provide let me know (although this is not appearing in a a minimal reproducible example - it's in large production app). There are no other analzyer errors in the project at time of getting this.

**Comment by eernstg** [comment] 2022-11-07 13:12
Looks like `profileLastLoaded` has static type `DateTime?`, which is not a subtype of `Object`, which makes the type error correct.

If you know for sure that `profileLastLoaded` is non-null then you can use `profileLastLoaded!` whose type is `DateTime` (but if it is null after all then it will throw). Otherwise you could use an if-element to provide this list element conditionally, similar to this example:

```dart
int? whatever() => 4;

void main() {
  int? maybeInt = whatever();
  List<int> xs = [1, 2, 3, if (maybeInt != null) maybeInt, 5, 6];
}
```

I'll close this issue because the given information seems to be consistent with the assumption that it's all working as intended. Please create a new issue if there is more information available to change this situation.

**Closed by eernstg** 2022-11-07 13:12 UTC

**Comment by jimmyff** [comment] 2022-11-08 12:54
Apologies @eernstg -I had assumed null was of type Object (it makes sense that it isn't). I will need to use `List<Object?>` 

Thanks

**Comment by eernstg** [comment] 2022-11-08 16:25
> Apologies

No need for that, thanks for contributing when you saw something unexpected!
