### ISSUE TITLE
regressed flutter_gallery_ios__transition_perf regression

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#30786] opened 2017-09-18 15:56 UTC
regressed flutter_gallery_ios__transition_perf missed_frame_build_budget_count regressed after https://github.com/flutter/flutter/pull/12087.

cc @aam @a-siva

**Comment by aam** [comment] 2017-09-18 17:13
The chart is rather noisy, so potentially regression came from https://github.com/flutter/flutter/pull/12058, which whitelisted more timeline events.

**Comment by a-siva** [comment] 2017-09-18 19:00
Is this a duplicate of https://github.com/dart-lang/sdk/issues/30787

**Comment by Hixie** [comment] 2017-09-18 20:18
I don't think so, but maybe. The Android version (#30787) started definitely after the https://github.com/flutter/flutter/pull/12058 PR. The iOS version looks like it started two builds earlier.

Looks like flutter_gallery_ios__transition_perf missed_frame_build_budget_count had a similar problem.

**Comment by aam** [comment] 2017-09-19 22:17
The missed_frame_build_budget_count test seems to be hard to use because of high variance between the runs. Having said that,  average for 10 runs points to https://github.com/flutter/engine/pull/4103. @xster, what do you think?

  | 2d530daec | f808426ef
-- | -- | --
  | 26 | 33
  | 22 | 32
  | 34 | 30
  | 40 | 28
  | 37 | 31
  | 33 | 30
  | 42 | 27
  | 32 | 31
  | 33 | 25
  | 32 | 29
average | 33.1 | 29.6

This is how I run the test against locally build flutter engine:
```
$FH/flutter/examples/flutter_gallery$  $FH/flutter/dev/devicelab/../../bin/flutter drive --profile --local-engine ios_profile --trace-startup -t test_driver/transitions_perf.dart > nul 2>&1  && grep missed_frame_build_budget_count build/transitions.timeline_summary.json` 
```

**Comment by Hixie** [comment] 2017-09-21 19:18
Definitely not a duplicate of #30787, since that one is now fixed but this one persists.

**Comment by Hixie** [comment] 2017-09-21 19:18
@xster is not going to be able to look at this for the next few weeks, can we revert the likely culprit in the meantime?

**Comment by aam** [comment] 2017-09-21 19:37
@Hixie we can certainly try - https://github.com/flutter/engine/pull/4133

**Comment by aam** [comment] 2017-09-21 19:52
Thanks @xster. And now https://github.com/flutter/flutter/pull/12205

**Comment by aam** [comment] 2017-09-21 21:14
Seems to have fixed regression.

**Closed by aam** 2017-09-21 21:14 UTC
Labels: area-vm
