### ISSUE TITLE
Exception: 'type 'Null' is not a subtype of type 'int' in type cast'

### ISSUE THREAD

**Issue by pri-ai** [dart-lang/sdk#55217] opened 2024-03-17 19:04 UTC
![Screenshot (709)](https://github.com/dart-lang/sdk/assets/64066509/f5100473-3a1b-4420-add6-2fd0cdf282cb)

**Comment by pri-ai** [comment] 2024-03-17 19:08
I'm trying to run my flutter web app but its not showing any devices. If I try to run any comments like flutter upgrade or flutter doctor its throwing this error. Any solution for this ?

**Comment by mraleph** [comment] 2024-03-18 12:34
Duplicate of #55212

**Closed by mraleph** 2024-03-18 12:34 UTC
