### ISSUE TITLE
dart:ffi will pass non-Instances to Dart code

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#45869] opened 2021-04-29 22:18 UTC
I noticed that `ffi/regress_jump_to_frame_test` fails when using the incremental kernel compiler (such as when running with --observe). This is because the incremental kernel compiler is missing metadata that normally causes some type checks to be skipped. These type checks run against an UnhandledException, which is not an Instance. More generally, I can from Dart try to `print` or otherwise interact with the result of `alwaysThrow` and crash in various places in the runtime. In the compiler, I notice that code for marshaling from C to Dart will unwrap any Dart_Handle, but only Instances can be handled by Dart.

The Dart code implementing mirrors has a similar issue in referencing Libraries, Classes, Functions, etc, which are all non-Instances. In these cases, the mirrors implement keeps these references in an opaque MirrorReference, which is an Instance but whose referent can only be accessed by the C++ part of the mirrors implementation. This might be useful for marshaling non-Instances to Dart in the FFI.

For the special case of Error, it might make sense to throw/Dart_PropogateError when an Error is returned from C to Dart.

@dcharkes

**Comment by mraleph** [comment] 2021-04-30 13:40
Duplicate of #44315

**Closed by mraleph** 2021-04-30 13:40 UTC
Labels: area-vm, crash, library-ffi

**Comment by mraleph** [comment] 2021-04-30 13:41
I should have referenced the bug from the test, sorry.
