### ISSUE TITLE
[NNBD] No error in Analyzer when non-nullable function may return null

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42568] opened 2020-07-03 07:28 UTC
The following code produces no issues in Analyzer but a compile error in CFE
```dart
import "dart:async";
main() {
  Future<int> f = new Future.value(42);
  f.then((_) {
    bool b = true;
    if (b) {
      return 42;
    }
  });
}
```
CFE output is
```
Error: A non-null value must be returned since the return type 'int' doesn't allow null.
f.then((_) {
       ^
```
There must be a compile error in Analyzer as well

`Dart VM version: 2.9.0-20.0.dev (dev) (Wed Jul 1 11:29:16 2020 +0200) on "windows_x64" `

**Comment by lrhn** [comment] 2020-07-03 08:20
The result of `f.then(...)` does seem to be `Future<int>` in the analyzer too, so it's not because it deduces that the function return type is `int?`.

**Comment by eernstg** [comment] 2020-07-03 08:27
I believe this is concerned with [function literal return type inference](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference): If the invocation of `then` gets an explicit type argument `<int>` then the CFE and the analyzer agree that it is an error, because the function literal may return null. With type argument `<int?>`, only the CFE reports an error (and it's the same error), which would be consistent with the following difference:

- The CFE computes `int` as the inferred return type of the function literal, and
- the analyzer computes `int?`

The rules [here](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#function-literal-return-type-inference) for the computation of the 'actual returned type' do not take the normal completion (that is: we reach the end of the function) into account, so I believe the CFE is correct and the analyzer takes an extra step which is not specified (in adding `Null` to the actual returned type).

I also think it would make sense to do as the analyzer says, in which case we should add an extra case to the rules about computing the actual return type.

**Comment by eernstg** [comment] 2020-07-03 09:11
Second thought: We should stick to the current rules. ;-)

The local function `f` is a compile time error:

```dart
void main() {
  var b = true;
  f() {
    if (b) return 1;
  }
  g() {
    if (b) return 1;
    if (!b) return null;
  }
}
```

The point is that we _do_ allow an explicit `return null` to make the inferred return type nullable, but reaching the end of the function is not given the same powers: That situation is just noted (so we know that the semantics of the function allows for returning `null`), and the return type is inferred (ignoring that we may reach the end), and then it's an error to reach the end if and because the inferred return type is non-nullable.

The current rules are giving the same treatment to the function literal as we're giving local functions (and no other functions are subject to return type inference based on the body). So the CFE behavior is the consistent behavior.

Cf. https://github.com/dart-lang/language/issues/1063.

**Comment by scheglov** [comment] 2020-07-07 21:32
It seems that this is a moving target, as discussion is continues in https://github.com/dart-lang/language/issues/1063.
FWIW, I like the idea of making returning `Null` explicit, so updating the spec for inference rules and analyzer.

**Comment by eernstg** [comment] 2020-07-17 14:04
@scheglov, @sgrekhov, with dart-lang/language#1063 closed I believe we can conclude that the analyzer works as intended: The normal completion gives rise to a nullable inferred return type for the function literal, and there is no error when the return statement is checked. So I'll close this.

**Closed by eernstg** 2020-07-17 14:04 UTC
Labels: NNBD, area-analyzer, type-bug
