### ISSUE TITLE
Flutter tests hit seg fault at dart::MarkingVisitorBase<true>::VisitPointers(dart::ObjectPtr*, dart::ObjectPtr*)

### ISSUE THREAD

**Issue by jmagman** [dart-lang/sdk#42541] opened 2020-07-01 00:17 UTC
On 22da8934ac8b
```
5 packages have newer versions incompatible with dependency constraints.
Try `pub outdated` for more information.
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x40010ad00040
version=2.9.0-19.0.dev.flutter-22da8934ac (be) (Tue Jun 30 16:00:47 2020 +0000) on "macos_x64"
pid=75394, thread=5379, isolate_group=kernel-service(0x7fe92e84bc00), isolate=(nil)(0x0)
isolate_instructions=10d39e000, vm_instructions=108ac2ea0
  pc 0x0000000108e42957 fp 0x000070000f14bdb0 dart::MarkingVisitorBase<true>::VisitPointers(dart::ObjectPtr*, dart::ObjectPtr*)+0x77
  pc 0x0000000108d883de fp 0x000070000f14bde0 dart::ObjectLayout::VisitPointersPredefined(dart::ObjectPointerVisitor*, long)+0x15e
  pc 0x0000000108e422f0 fp 0x000070000f14be20 dart::MarkingVisitorBase<true>::DrainMarkingStack()+0x110
  pc 0x0000000108e42d4c fp 0x000070000f14be90 dart::ConcurrentMarkTask::Run()+0x6c
  pc 0x0000000108e0ca52 fp 0x000070000f14bf20 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x152
  pc 0x0000000108e0cd1f fp 0x000070000f14bf50 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x0000000108d6ef1a fp 0x000070000f14bfb0 dart::ThreadStart(void*)+0xba
  pc 0x00007fff6ab6ee65 fp 0x000070000f14bfd0 _pthread_start+0x94
  pc 0x00007fff6ab6a83b fp 0x000070000f14bff0 thread_start+0xf
-- End of DumpStackTrace
/private/tmp/flutter sdk/bin/internal/shared.sh: line 89: 75394 Abort trap: 6           "$DART" --disable-dart-dev $FLUTTER_TOOL_ARGS --snapshot="$SNAPSHOT_PATH" --packages="$FLUTTER_TOOLS_DIR/.packages" --no-enable-mirrors "$SCRIPT_PATH"
Exit status: 134
```
https://cirrus-ci.com/task/5902081691222016?command=setup#L608

[setup_segfault.txt](https://github.com/dart-lang/sdk/files/4854949/setup_segfault.txt)

macos_x64

**Comment by alexmarkov** [comment] 2020-07-01 16:51
@rmacnak-google

**Comment by a-siva** [comment] 2021-04-22 17:35
Marking this class of crashes as duplicates (We seem to have at least 5 of these). 
Duplicate of https://github.com/dart-lang/sdk/issues/45792

**Closed** 2021-04-22 17:35 UTC
Labels: area-vm, closed-duplicate, type-bug
