### ISSUE TITLE
Unexpected behavior when setting a breakpoint at a library variable assignment

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#27287] opened 2016-09-09 11:20 UTC
**Summary**
In WebStorm, when setting a breakpoint at a library variable assignment inside a function, the breakpoint will trigger at an expected location. Specifically the breakpoint will behave as if it was set at program location following the assignment.

**What steps will reproduce the problem?**
1 . In WebStorm create a new 'Simple commandline application'
2 . Replace the contents of main.dart with the following
```
var f = 42;

main(List<String> args) {
  print('hello world');
  f = 1337;
  print(f);
  print('goodbye');
}
```
3 . Insert a breakpoint at the assignment `f = 1337`
4 . Launch the application in debug mode

*Expected:*
Webstorm pauses execution at the line where the breakpoint was set

*Actual:*
WebStorm pause execution at the line following the line where the breakpoint was set.
![breakpoints](https://cloud.githubusercontent.com/assets/12271154/18385312/157d9a8e-7690-11e6-8d63-da0384581a98.png)

**What version of the product are you using?**
Webstorm: 2016.2.3
Dart-sdk: 1.20-dev.3.0

**Please provide any additional information below.**
If a breakpoint is set at both the assignment, and the line following the assignment it is possible to cancel the second breakpoint by removing the first. However this only works if the breakpoint is removed during when the program has already been launched.

E.g. the following steps can produce a similar error:
1. Insert a breakpoint a the first 3 lines in the main method
2. Launch the application in debug mode and wait for the first breakpoint to trigger
3. Remove the breakpoint at the second line inside the main method, and resume execution
*Expected:*
The program pauses at the third line inside the main method

*Actual:*
The program runs to completion

**Comment by anders-sandholm** [comment] 2016-09-14 11:16
Might be an issue with the debugger in IntelliJ @jwren - not sure what label to use for that, so made it a VM issue for now. Please reassign.

**Comment by johnmccutchan** [comment] 2016-09-14 15:03
We need to see the VM service log chatter to be able to determine if this is a VM issue or not.

**Comment by jwren** [comment] 2016-09-14 22:41
@devoncarew who has been looking at issues like this in IJ

**Comment by alexander-doroshko** [comment] 2016-09-15 13:29
@johnmccutchan The issue is reproducible with the sample code provided. Here's the log:
```
Sent: {"id":"7","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/140688471","scriptUri":"file:///C:/dart_projects/dart-lang/usage/tool/foo.dart","line":5}} 
VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointAdded","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/140688471","name":"foo.dart$main","number":"140688471"},"timestamp":1473945644908,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/15\/scripts\/file%3A%2F%2F%2FC%3A%2Fdart_projects%2Fdart-lang%2Fusage%2Ftool%2Ffoo.dart\/1572e01ad89","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart","_kind":"script"},"line":5}}}}} 
VM message: {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/15\/scripts\/file%3A%2F%2F%2FC%3A%2Fdart_projects%2Fdart-lang%2Fusage%2Ftool%2Ffoo.dart\/1572e01ad89","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart","_kind":"script"},"line":5}},"id":"7"} 
Sent: {"id":"8","method":"resume","params":{"isolateId":"isolates/140688471"}} 
VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/140688471","name":"foo.dart$main","number":"140688471"},"timestamp":1473945644910}}} 
VM message: {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"8"} 
VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointResolved","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/140688471","name":"foo.dart$main","number":"140688471"},"timestamp":1473945644911,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/15\/scripts\/file%3A%2F%2F%2FC%3A%2Fdart_projects%2Fdart-lang%2Fusage%2Ftool%2Ffoo.dart\/1572e01ad89","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart","_kind":"script"},"tokenPos":29}}}}} 
VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/140688471","name":"foo.dart$main","number":"140688471"},"timestamp":1473945644911,"pauseBreakpoints":[{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/15\/scripts\/file%3A%2F%2F%2FC%3A%2Fdart_projects%2Fdart-lang%2Fusage%2Ftool%2Ffoo.dart\/1572e01ad89","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart","_kind":"script"},"tokenPos":29}}],"topFrame":{"type":"Frame","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/15\/scripts\/file%3A%2F%2F%2FC%3A%2Fdart_projects%2Fdart-lang%2Fusage%2Ftool%2Ffoo.dart\/1572e01ad89","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart","_kind":"script"},"tokenPos":29},"function":{"type":"@Function","fixedId":true,"id":"classes\/1023\/functions\/main","name":"main","owner":{"type":"@Library","fixedId":true,"id":"libraries\/15","name":"","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart"},"_kind":"RegularFunction","static":true,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/3e81a0743d3-29c27531a80","name":"main","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"args","value":{"type":"@Instance","_vmType":"Array","class":{"type":"@Class","fixedId":true,"id":"classes\/67","name":"_List","_vmName":"_List@0150898"},"kind":"List","id":"objects\/0","length":0},"_tokenPos":13,"_endTokenPos":43}],"index":0}}}} 
Sent: {"id":"9","method":"getObject","params":{"isolateId":"isolates/140688471","objectId":"libraries/15/scripts/file%3A%2F%2F%2FC%3A%2Fdart_projects%2Fdart-lang%2Fusage%2Ftool%2Ffoo.dart/1572e01ad89"}} 
VM message: {"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/14","name":"Script"},"size":80,"fixedId":true,"id":"libraries\/15\/scripts\/file%3A%2F%2F%2FC%3A%2Fdart_projects%2Fdart-lang%2Fusage%2Ftool%2Ffoo.dart\/1572e01ad89","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart","_kind":"script","_loadTime":1473945644425,"library":{"type":"@Library","fixedId":true,"id":"libraries\/15","name":"","uri":"file:\/\/\/C:\/dart_projects\/dart-lang\/usage\/tool\/foo.dart"},"lineOffset":0,"columnOffset":0,"source":"var f = 42;\r\n\r\nmain(List<String> args) {\r\n  print('hello world');\r\n  f = 1337;\r\n  print(f);\r\n  print('goodbye');\r\n}","tokenPosTable":[[1,0,1,1,5,2,7,3,9,4,11],[3,7,1,8,5,9,6,10,10,11,11,12,17,13,19,14,23,15,25],[4,17,3,18,8,19,9,20,22,21,23],[5,23,3,24,5,25,7,27,11],[6,29,3,30,8,31,9,32,10,33,11],[7,35,3,36,8,37,9,39,18,40,19],[8,42,1]]},"id":"9"} 
```
IDE asks to set breakpoint at line 5.
VM says that breakpoint is set and resolved at tokenPos=29.
VM stops at this breakpoint at tokenPos=29.
But according to the Script object token=29 is at the line number 6 (`[6,29,3,30,8,31,9,32,10,33,11]`).
That's why IDE stops at line 6, I do not see IDE bug here.

**Comment by alexander-doroshko** [comment] 2016-09-15 13:37
As for the 2nd scenario (set 3 breakpoints, stop at first, remove 2nd, resume, 3rd is not hit), the following happens:
Breakpoint set at line 5 resolves to tokenPos=29 (that is at line 6).
Breakpoint set at line 6 also resolves to tokenPos=29.
Breakpoint at line 5 is removed.
User expects that breakpoint at line 6 remains enabled, but since 2 breakpoints are resolved to the same tokenPos both seem to be removed in one shot.

**Comment by johnmccutchan** [comment] 2016-09-15 13:48
@turnidge @mhausner

**Comment by mhausner** [comment] 2016-09-26 17:58
This is fixed.

**Closed by mhausner** 2016-09-26 17:58 UTC
Labels: area-vm, vm-debugger
