### ISSUE TITLE
AbstractConstExprSerializer cannot serialize an instance of GenericFunctionTypeImpl

### ISSUE THREAD

**Issue by 1SouravGhosh** [dart-lang/sdk#35711] opened 2019-01-20 07:59 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `1.24.3`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:

```
Dart analysis server, SDK version 1.24.3, server version 1.18.0, error: Analysis failed: D:\PROJECTS\softwareProjects\AndroidProjects\storyboard\storyboard\test\widget_test.dart
Invalid argument(s): Cannot serialize an instance of GenericFunctionTypeImpl
#0      AbstractConstExprSerializer.serializeTypeName (package:analyzer/src/summary/summarize_const_expr.dart:211)
#1      AbstractConstExprSerializer._serializeListLiteral (package:analyzer/src/summary/summarize_const_expr.dart:550)
#2      AbstractConstExprSerializer._serialize (package:analyzer/src/summary/summarize_const_expr.dart:356)
#3      AbstractConstExprSerializer.serialize (package:analyzer/src/summary/summarize_const_expr.dart:139)
#4      _SummarizeAstVisitor.serializeConstExpr (package:analyzer/src/summary/summarize_ast.dart:557)
#5      _SummarizeAstVisitor.serializeFunctionBody (package:analyzer/src/summary/summarize_ast.dart:755)
#6      _SummarizeAstVisitor.serializeInitializerFunction (package:analyzer/src/summary/summarize_ast.dart:828)
#7      _SummarizeAstVisitor.serializeVariables (package:analyzer/src/summary/summarize_ast.dart:1029)
#8      _SummarizeAstVisitor.visitFieldDeclaration (package:analyzer/src/summary/summarize_ast.dart:1210)
#9      FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4399)
#10     _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:472)

**Comment by srawlins** [comment] 2019-09-03 07:41
This was also reported at https://github.com/dart-lang/sdk/issues/37703; while this issue was reported first, the other has a longer stacktrace; please follow along there.

**Comment by srawlins** [comment] 2019-09-03 07:42
Duplicate of https://github.com/dart-lang/sdk/issues/37703

**Closed** 2019-09-04 03:32 UTC
Labels: P2, analyzer-crash-report, area-analyzer, type-bug
