### ISSUE TITLE
Add support for different analyzer behaviour based on path/filename

### ISSUE THREAD

**Issue by tjarvstrand** [dart-lang/sdk#50031] opened 2022-09-22 07:51 UTC
Currently, the only two global options for analyzing a file is to either apply all the rules in analysis_options or to exclude the file from analysis entirely. This does not work very well for generated files. These are often created by 3rd party libraries beyond our control so we often want to disable linting, but the analyzer should still be able to report actual errors in those files.

I can think of two solutions off the top of my head:
* Add a second exclude option to analysis_options.yml that only excludes files from linting, and not from analysis entirely
* Add the ability for analyzer to apply different analysis options for different files, either by extending the current format or by using separate .yml files.

**Comment by srawlins** [comment] 2022-09-26 01:39
This is more-or-less a duplicate of https://github.com/dart-lang/linter/issues/320. In any case, the discussion at https://github.com/dart-lang/linter/issues/320 circles around different solutions for the problem you describe.

**Closed by srawlins** 2022-09-26 01:39 UTC
Labels: area-analyzer
