### ISSUE TITLE
Error on application launch when debugging on MacOS

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#27286] opened 2016-09-09 10:57 UTC
**Summary**
In WebStorm on MacOS, launching a command line application in debug mode will often yield the following error: 'No consumer associated with id:'.
Furthermore the process never completes, though the program appears to execute as normal.
The incident does not always occur, but could be reproduced locally approximately half the time.

**What steps will reproduce the problem?**
1. In WebStorm create a new 'Simple commandline application'
2. Execute the application in debug mode.
*Expected:*
No errors should occur.

*Actual:*
The console will often output 'Error: No consumer associated with id:', and the process never completes.
![screen shot 2016-09-09 at 11 38 51](https://cloud.githubusercontent.com/assets/12271154/18384777/d9afacb6-768c-11e6-95b3-152be25500d5.png)

**What version of the product are you using?**
Webstorm: 2016.2.3
Dart-sdk: 1.20-dev.3.0

**On what operating system?**
OS X: 10.10.5

**Please provide any additional information below.**
The error was reproduced using both 32bit and 64bit version.

**Comment by alexander-doroshko** [comment] 2016-09-09 11:18
@boasjls Can you please add `com.jetbrains.lang.dart.ide.runner.server.vmService` to Help | Debug Log Settings, reproduce the problem and attach idea.log file after that (Help | Show Log)?

**Comment by boasjls** [comment] 2016-09-09 11:39
Here you go
[idea.zip](https://github.com/dart-lang/sdk/files/463856/idea.zip)

**Comment by alexander-doroshko** [comment] 2016-09-09 14:06
Thanks! Here's extracted useful info for convenience.
Logs of successful debug session:
```
[95331] VM connection open: ws://localhost:49282/ws 
[95331] Sent: {"id":"1","method":"getVersion","params":{}} 
[95393] VM message: {"jsonrpc":"2.0", "result":{"type":"Version","major":3,"minor":5,"_privateMajor":0,"_privateMinor":0},"id":"1"} 
[95393] Difference in protocol version: client=3.0 vm=3.5 
[95393] Sent: {"id":"2","method":"streamListen","params":{"streamId":"Debug"}} 
[95406] VM message: {"jsonrpc":"2.0","id":"2","result":{"type":"Success"}} 
[95406] Sent: {"id":"3","method":"streamListen","params":{"streamId":"Isolate"}} 
[95407] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseStart","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/441537983","name":"main.dart$main","number":"441537983"},"timestamp":1473420873604}}} 
[95408] Sent: {"id":"4","method":"setExceptionPauseMode","params":{"isolateId":"isolates/441537983","mode":"Unhandled"}} 
[95408] VM message: {"jsonrpc":"2.0","id":"3","result":{"type":"Success"}} 
[95408] Sent: {"id":"5","method":"getVM","params":{}} 
[95411] VM message: {"jsonrpc":"2.0", "result":{"type":"VM","name":"vm","architectureBits":32,"targetCPU":"ia32","hostCPU":"Intel(R) Core(TM)2 Duo CPU     E8335  @ 2.66GHz","version":"1.20.0-dev.3.0 (Tue Sep  6 08:30:24 2016) on \"macos_ia32\"","_profilerMode":"Dart","pid":61134,"_maxRSS":14966784,"startTime":1473420873262,"isolates":[{"type":"@Isolate","fixedId":true,"id":"isolates\/441537983","name":"main.dart$main","number":"441537983"}]},"id":"5"} 
[95411] Sent: {"id":"6","method":"getIsolate","params":{"isolateId":"isolates/441537983"}} 
[95412] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"_DebuggerSettingsUpdate","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/441537983","name":"main.dart$main","number":"441537983"},"timestamp":1473420873612,"_debuggerSettings":{"_exceptions":"unhandled"}}}} 
[95413] VM message: {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"4"} 
[95413] Sent: {"id":"7","method":"resume","params":{"isolateId":"isolates/441537983"}} 
[95423] VM message: {"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/441537983","name":"main.dart$main","number":"441537983","_originNumber":"441537983","startTime":1473420873266,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":0,"avgCollectionPe...15","name":"","uri":"file:\/\/\/Users\/jls\/WebstormProjects\/untitled60\/bin\/main.dart"}],"breakpoints":[],"exceptionPauseMode":"Unhandled","_debuggerSettings":{"_exceptions":"unhandled"}},"id":"6"} 
[95424] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/441537983","name":"main.dart$main","number":"441537983"},"timestamp":1473420873616}}} 
[95424] VM message: {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"7"} 
[95425] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Isolate","event":{"type":"Event","kind":"IsolateExit","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/441537983","name":"main.dart$main","number":"441537983"},"timestamp":1473420873620}}} 
[95428] VM message:  
[95433] VM connection closed: ws://localhost:49282/ws 
```

Logs of failed debug session:
```
[96418] VM connection open: ws://localhost:49286/ws
[96418] Sent: {"id":"1","method":"getVersion","params":{}}
[96454] VM message: {"jsonrpc":"2.0", "result":{"type":"Version","major":3,"minor":5,"_privateMajor":0,"_privateMinor":0},"id":"1"}
[96455] Difference in protocol version: client=3.0 vm=3.5
[96455] Sent: {"id":"2","method":"streamListen","params":{"streamId":"Debug"}}
[96463] VM message: {"jsonrpc":"2.0","id":"2","result":{"type":"Success"}}
[96463] Sent: {"id":"3","method":"streamListen","params":{"streamId":"Isolate"}}
[96465] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseStart","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/384070424","name":"main.dart$main","number":"384070424"},"timestamp":1473420874663}}}
[96465] Sent: {"id":"4","method":"setExceptionPauseMode","params":{"isolateId":"isolates/384070424","mode":"Unhandled"}}
[96465] VM message: {"jsonrpc":"2.0","id":"3","result":{"type":"Success"}}
[96465] Sent: {"id":"5","method":"getVM","params":{}}
[96468] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"_DebuggerSettingsUpdate","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/384070424","name":"main.dart$main","number":"384070424"},"timestamp":1473420874668,"_debuggerSettings":{"_exceptions":"unhandled"}}}}
[96468] VM message: {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"4"}
[96468] Sent: {"id":"6","method":"resume","params":{"isolateId":"isolates/384070424"}}
[96470] VM message: {"jsonrpc":"2.0", "result":{"type":"VM","name":"vm","architectureBits":32,"targetCPU":"ia32","hostCPU":"Intel(R) Core(TM)2 Duo CPU     E8335  @ 2.66GHz","version":"1.20.0-dev.3.0 (Tue Sep  6 08:30:24 2016) on \"macos_ia32\"","_profilerMode":"Dart","pid":61135,"_maxRSS":15183872,"startTime":1473420874371,"isolates":[{"type":"@Isolate","fixedId":true,"id":"isolates\/384070424","name":"main.dart$main","number":"384070424"}]},"id":"5"}
[96470] Sent: {"id":"7","method":"getIsolate","params":{"isolateId":"isolates/384070424"}}
[96473] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/384070424","name":"main.dart$main","number":"384070424"},"timestamp":1473420874671}}}
[96474] VM message: {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"6"}
[96474] VM message: {"type":"ServiceError","id":"","kind":"InternalError","message":"could not send message [7] to isolate"}
[96474] No consumer associated with id:
[96475] VM message: {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Isolate","event":{"type":"Event","kind":"IsolateExit","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/384070424","name":"main.dart$main","number":"384070424"},"timestamp":1473420874673}}}
[96482] VM message:
[96486] VM connection closed: ws://localhost:49286/ws
```

**Comment by anders-sandholm** [comment] 2016-09-14 11:19
Not sure if IntelliJ/WebStorm issue, @jwren - or VM issue.

**Comment by johnmccutchan** [comment] 2016-09-14 15:03
Based on the VM service log it looks like this is not a VM issue.

**Comment by alexander-doroshko** [comment] 2016-09-14 15:11
@johnmccutchan Does it look like a race not properly handled by the IDE (`getIsolate` called later than `resume`, isolate is dead at this moment, so `ServiceError` is reported)?

**Comment by johnmccutchan** [comment] 2016-09-14 15:50
@alexander-doroshko I do not know the internals of the IDE's usage of the service protocol. It does look like the isolate exits before the resume can be sent. This would indicate that the isolate is not being launched in 'pause on start' mode. All IDEs must launch programs with 'pause on start' mode enabled so that they can setup the isolates in a race-free manner.

**Comment by alexander-doroshko** [comment] 2016-09-14 16:05
'pause on start' mode is ON of course. Resume command seem to work correctly. It is `getIsolate` that fails. I guess it is because `getIsolate` is sent later than `resume`. I moved it to our issue tracker (https://youtrack.jetbrains.com/issue/WEB-23278), closing here.

**Closed by alexander-doroshko** 2016-09-14 16:05 UTC
Labels: area-vm, vm-debugger
