### ISSUE TITLE
`dart --enable-experiment=invalid run` does not complain about the bad argument

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#51300] opened 2023-02-07 00:22 UTC
When you omit the explicit path to execute, as in:

* `dart --enable-experiment=invalid --run`
* `dart run --enable-experiment=invalid`

There is no checking of the validity of "invalid".

Also it seems the experiment isn't enabled at all. If I use records, and say `dart run --enable-experiment=records`, it complains about the records (twice?!) telling me to use the `--enable-experiment=records` flag, even though it's already enabled.

**Comment by devoncarew** [comment] 2023-02-07 00:49
cc @bkonyi

**Comment by bkonyi** [comment] 2023-02-07 15:12
This seems to work fine if you explicitly provide the target to execute:

```
$ dart run records.dart 
records.dart:2:9: Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
  print((1,2));
        ^
$ dart run --enable-experiment=records records.dart 
(1, 2)
$ dart run --enable-experiment=records --enable-experiment=invalid records.dart 
Unknown experiment: invalid
```

**Comment by bkonyi** [comment] 2023-02-07 15:14
I can reproduce when not providing an explicit target:

```
$ dart run --enable-experiment=records
Building package executable... 
Failed to build records_test:records_test:
bin/records_test.dart:4:9: Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
  print((1,2));
        ^
Failed to build records_test:records_test:
bin/records_test.dart:4:9: Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
  print((1,2));
```

**Comment by bkonyi** [comment] 2023-02-07 15:34
This doesn't seem to cause issues if I disable snapshot generation when calling `getExecutableForCommand`. We probably need a way to pass experiments to this method @jonasfj @sigurdm.

I've filed an issue to track the issue with the resident compilation server: https://github.com/dart-lang/sdk/issues/51303.

**Comment by mit-mit** [comment] 2023-02-08 08:31
Wouldn't it be fairly easy to print a friendly message when passing a non-existing flag?

**Comment by sigurdm** [comment] 2023-02-09 16:06
Looked a bit into this, seems to me that we should never use a snapshot in pub if we have experiments.

I think perhaps the --resident mode is not working because https://dart.googlesource.com/sdk/+/9e4dc755cb654faf8b76625f86eb29b85323a66c/pkg/dartdev/lib/src/resident_frontend_utils.dart#108 passes the experiments as names, but https://dart.googlesource.com/sdk/+/897acba77f58fb2cdaae6e9cd92699fe22b55daf/pkg/frontend_server/lib/src/resident_frontend_server.dart#342 expects them as ready argument ('--enable-experiment=<experiment>').

Will try to validate and  make a fix tomorrow.

Looking ahead I think the snapshotting should be moved out of pub. But that is probably a bit off still.

**Comment by sigurdm** [comment] 2023-02-10 14:34
Made a fix: https://dart-review.googlesource.com/c/sdk/+/282281

**Comment by sigurdm** [comment] 2023-02-13 10:12
Fix has landed at dart sdk main.

**Closed by sigurdm** 2023-02-13 10:12 UTC
Labels: area-dart-cli, dart-cli-run
