### ISSUE TITLE
Dart Analyzer: Simple Repro -> Freeze

### ISSUE THREAD

**Issue by mwalkerwells** [dart-lang/sdk#34822] opened 2018-10-16 19:22 UTC
The following code causes the analyzer to freeze...

MacOS / Dart 2.1.0-dev.7.1.flutter-ac6d4f7e65

Also repro'd with the Dart SDK packaged with Flutter v0.9.4.

```dart
class Foo<T> {}

class Bar {
  Foo<NotDeclared<>>;
}
```

**Comment by bwilkerson** [comment] 2018-10-18 17:41
@danrubel @scheglov I'm guessing that this is related to #34850

**Comment by scheglov** [comment] 2018-10-19 01:15
Yes, I agree that this is duplicate of #34850

**Closed by scheglov** 2018-10-19 01:15 UTC
Labels: area-analyzer, type-bug
