### ISSUE TITLE
Allow usage of constructor field parameters in constructor initializer list

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/sdk#26210] opened 2016-04-07 14:41 UTC
```
class A {
 final x;
 final y;

 A(this.x) : y = x;
}
```

does not work (with "Only static members can be accessed in initializers"). It should...

**Comment by lrhn** [comment] 2016-04-07 16:59
Effectively a duplicate of #15346.

I personally agree that `this.x` should also introduce `x` as a variable in the initializer list.

**Comment by filiph** [comment] 2016-04-22 21:45
I agree. This has been bothering me for some time. 

A more real-life example:

```
class Student {
  final String fullName, firstName, middleInitial, lastName;
  Student(this.firstName, this.middleInitial, this.lastName)
      : fullName = "$firstName $middleInitial $lastName";  // Error
}
```

This currently needs to be rewritten to the code below:

```
class Student {
  final String fullName, firstName, middleInitial, lastName;
  Student(String firstName, String middleInitial, String lastName)
      : firstName = firstName,
        middleInitial = middleInitial,
        lastName = lastName,
        fullName = "$firstName $middleInitial $lastName";
}
```

...  or one needs to a) make `fullName` not final or b) use a getter.

**Comment by floitschG** [comment] 2016-04-25 14:43
Closing as duplicate.

**Closed by floitschG** 2016-04-25 14:43 UTC
Labels: area-language, Type: enhancement

**Comment by patelkrunal78** [comment] 2019-10-07 15:11
Very Similar To [Error: Only static members can be accessed in initializers what does this mean](https://icetutor.com/question/error-only-static-members-can-be-accessed-in-initializers-what-does-this-mean)

**Comment by milanpatel18** [comment] 2019-10-12 16:35
For Example You can Do This

class AppHomeState extends State<AppHome> with SingleTickerProviderStateMixin {

TabController _tabController;
final filterController = new TextEditingController(text: "Search");
TextFormField email = ...
... is an initializer and there is no way to access this at this point. Initializers are executed before the constructor, but this is only allowed to be accessed after the call to the super constructor (implicit in your example) was completed. Therefore only in the constructor body (or later) access to this is allowed

sorry Code is not in formate........Please Check [here](https://icetutor.com/question/error-only-static-members-can-be-accessed-in-initializers-what-does-this-mean/)

**Comment by ManojShirahatti** [comment] 2020-08-09 05:22
g

**Comment by flutterq** [comment] 2021-02-02 02:20
[[Solved] Error: Only static members can be accessed in initializers](https://fluttercorner.com/solved-error-only-static-members-can-be-accessed-in-initializers/)
