### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by estevez-dev** [dart-lang/sdk#35966] opened 2019-02-16 17:38 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.ec86471ccc47a62df8b4009e1fb37c66ff9dc91b, server version 1.21.1, error: Analysis failed: D:\src\hass_client\lib\entity_widgets\common\mode_swicth.dart
RangeError (index): Invalid value: Not in range 0..11, inclusive: 12
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1461:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1367:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:472:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7162:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7059:5)
#6      _ParameterElementImpl&VariableElementImpl&ParameterElementMixin.appendToWithoutDelimiters (package:analyzer/src/dart/element/element.dart:7263:18)
#7      ExecutableElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:3885:19)
#8      MethodElementImpl.appendTo (package:analyzer/src/dart/element/element.dart:6079:11)
#9      ElementImpl.toString (package:analyzer/src/dart/element/element.dart:3164:5)
#10     _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:836:19)
#11     new _ElementMismatchException (package:analyzer/src/generated/declaration_resolver.dart:971:65)
#12     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52:17)
#13     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:597:31)
#14     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:118:7)
#15     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#16     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:117:11)
#17     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#20     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1431:63)
#21     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#23     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#24     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2116:24)
<asynchronous suspension>
#25     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2057:5)
#26     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#27     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#28     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#29     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#35     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#36     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#37     main (file:///E:/b/rr/tmpqlvyqu/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#38     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#39     main (file:///E:/b/rr/tmpqlvyqu/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#40     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by stereotype441** [comment] 2019-02-19 18:34
Duplicate of #35551

**Closed by stereotype441** 2019-02-19 18:34 UTC
Labels: area-analyzer
