### ISSUE TITLE
Analyzer crashes if you run "git clean".

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31918] opened 2018-01-16 22:51 UTC
In one window:
```
flutter update-packages; flutter analyze --watch --flutter-repo
```
Once that's started, in another, at the root of the flutter repo (careful, this deletes files):
```
git clean -xffd
```
The analyzer then crashes.

**Comment by Hixie** [comment] 2018-01-16 22:51
cc @pq @devoncarew

**Comment by bwilkerson** [comment] 2018-01-29 23:44
Duplicate of #31961.

**Closed by bwilkerson** 2018-01-29 23:44 UTC
Labels: P1 high, Type: bug, area-analyzer
