### ISSUE TITLE
NPE from Parser.parseLiteralFunctionSuffix, 2.5.0-edge.1ef83b86ae63

### ISSUE THREAD

**Issue by bbakewaikhom** [dart-lang/sdk#39151] opened 2019-10-28 19:11 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4576:38)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4608:14)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4295:14)
#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#8      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5226:12)
#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3814:14)
#11     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#12     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#13     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#14     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#15     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#16     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#17     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#18     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#19     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#20     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#21     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#22     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#23     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#24     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#25     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#26     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#27     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#28     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#29     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#30     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#31     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#32     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#33     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#39     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#40     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#41     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#51     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#52     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#53     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#54     _A...
```

For additional log information, please append the contents of
file://C:\Users\bbake\AppData\Local\Temp\report1.txt.

**Comment by keertip** [comment] 2019-11-12 17:25
Duplicate of #38738

**Closed by keertip** 2019-11-12 17:26 UTC
Labels: analyzer-crash-report, area-analyzer
