### ISSUE TITLE
Self-referential type annotation crashes Dart 2 when run through the test runner

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#33100] opened 2018-05-11 20:57 UTC
### The error

The following code:

```dart
class Table<T extends Table<T>> {}

void main() {
  var map = new Map<Table, String>();
}
```

when run in Dart 2 mode on the VM, _only through the test runner_, results in this error:

```none
00:01 +0 -1: loading a.dart [E]
  Failed to load "a.dart":
  'file:///tmp/a-package/a.dart': malbounded type: type parameter 'T' of class 'Table' must extend bound 'Table<T>', but type argument 'Table<dynamic>' is
not a subtype of 'Table<Table<dynamic>>' where
    Table is from file:///tmp/a-package/a.dart
    Table is from file:///tmp/a-package/a.dart
    Table is from file:///tmp/a-package/a.dart
  'file:///tmp/a-package/a.dart': malbounded type: type 'Table<Table<dynamic>>' has an out of bound type argument
  type '_InternalLinkedHashMap<Table<Table<dynamic>>, String>' is not a subtype of type 'LinkedHashMap<Table<Table<dynamic>>, String>' of 'function result' where
    _InternalLinkedHashMap is from dart:collection
    Table is from file:///tmp/a-package/a.dart
    Table is from file:///tmp/a-package/a.dart
    String is from dart:core
    LinkedHashMap is from dart:collection
    Table is from file:///tmp/a-package/a.dart
    Table is from file:///tmp/a-package/a.dart
    String is from dart:core

  dart:core       new Map
  a.dart 6:17     main
  ===== asynchronous gap ===========================
  package:test    serializeSuite
  data:... 0:391  main

00:01 +0 -1: Some tests failed.
```

### Reproduction steps

This was very tricky to reproduce, which... maybe will help in identifying the issue? OK steps to reproduce:

1. Use Dart 2.0.0-dev.52.0, maybe latest too.
2. Make a package that depends on the **test** package, and the latest **analyzer** package. Here's my pubspec:

   ```yaml
   name: apackage                                                                                                                                                                                                 
   version: 0.0.1
   environment:
     sdk: '>=2.0.0-dev.16.0 <2.0.0'

   dependencies:
     test: '^0.12.0'
   dependency_overrides:
     analyzer: '0.31.2-alpha.2'
   ```

   The **test** package is needed because this problem is not reproducible with `dart --preview-dart-2 a.dart`. The **analyzer** override is needed for strong mode fixes in front_end 0.1.0-alpha.12.
3. Write out `a.dart` like so:

   ```dart
   class Table<T extends Table<T>> {}

   void main() {
     var map = new Map<Table, String>();
   }
   ```
4. Execute the code through the **test** package's runner:

   ```shell
   dart \
       --preview-dart-2 \
       --packages=`pwd`/.packages /usr/local/google/home/srawlins/.pub-cache/hosted/pub.dartlang.org/test-0.12.37/bin/test.dart \
       a.dart
   ```

   I got the path to the **test** packages runner by looking in `.packages`.

## Twists

Now for some twists:

* This bug does not reproduce when running `dart a.dart`.
* This bug does not reproduce when running `dart --preview-dart-2 a.dart`.
* This bug does not reproduce in DDC.

CC @natebosch @grouma who might know why the test runner plays a part. Isolates?
CC @leafpetersen @keertip working on Dart 2
CC @joshua-i who brought this to our attention

**Comment by natebosch** [comment] 2018-05-11 21:02
The most likely reason for package:test playing a role is the way it uses Isolates.

**Comment by keertip** [comment] 2018-05-11 21:54
CC @a-siva

**Comment by vsmenon** [comment] 2018-05-14 22:34
@a-siva - tentatively assigning to VM per suggestion this is an isolate issue.

**Comment by srawlins** [comment] 2018-05-15 21:56
I've tried reproducing this without the test package runner, to no avail. I've tried `Isolate.spawn` and `Isolate.spawnUri`, but I'm guessing something like... `packageRoot` or... `automaticPackageResolution` comes into play...

**Comment by mraleph** [comment] 2018-05-16 11:58
@jensjoha discovered the reason: it is because `checked: true` enables "legacy" checked mode inside a spawned isolate, which conflicts with strong mode.

Reproduction

```dart
import 'dart:io';
import 'dart:isolate';

class Table<T extends Table<T>> {}

main(List<String> args) async {

  if (args.isEmpty) {
    await spawnAndListen();
  } else {
    var map = new Map<Table, String>();
  }
}

void spawnAndListen() async {
  Isolate isolate =
      await Isolate.spawnUri(Platform.script, ["spawned!"], "", checked: true);
  RawReceivePort port;
  void handler(message) {
    if (message != null) {
      print(message[0]);
    }
    port.close();
  }

  port = new RawReceivePort(handler);
  isolate.addErrorListener(port.sendPort);
  isolate.addOnExitListener(port.sendPort);
}
```

**Comment by mraleph** [comment] 2018-05-16 11:58
Duplicate of #33120

**Closed by mraleph** 2018-05-16 11:58 UTC
Labels: P1 high, area-vm

**Comment by srawlins** [comment] 2018-05-16 13:16
Excellent, thanks @mraleph and @jensjoha !

**Comment by a-siva** [comment] 2018-05-16 17:56
Good catch, I will change spawnURI to not turn on checked mode when running in dart2 mode.
