### ISSUE TITLE
[Infra] Provide a way to reset flakiness status of a test

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41821] opened 2020-05-08 22:08 UTC
After submitting a fix for a certain test, we shouldn't hide any future failures only because the test was marked as flaky before it was fixed - it may start failing soon enough due to unrelated bug and the new failure will be hidden. Also, it would be useful to see the test among 'tests started passing'. Previously, we even had cases when bot remained red after the test was fixed but its passing status was not taken into account for certain number of build because it was flaky.

To solve these problems it would be useful to have an ability to manually override (reset) the flakiness status of particular test(s). This could be an annotation on the CL, or we could keep these "flakiness reset" commands along with approvals and integrate such ability to the test results feed, both for CI and per CL in Gerrit.

@athomas @whesse What do you think? Is there a workaround or maybe a command-line tool for that?

**Comment by whesse** [comment] 2020-05-10 08:56
This is something we really see the need for.  I'll make an issue in the dart_ci repo, and see if we can make a quick-and-dirty interface quickly.  I'm right now building the service that has current status of tests, and want to add the flaky status to it.

The implementation is a little sensitive, because right now, the current flaky tests on a configuration are just the flaky.json file in the latest build.  So removing the flaky marker from a test  would be to delete a line from that file, which is touchy - we like having these files read-only, once they are written by a build.  We could add a second "modified_flaky.json" file that has the changes, and use that in the next build if it is present.

**Comment by whesse** [comment] 2020-05-10 09:06
Feature addition tracked in https://github.com/dart-lang/dart_ci/issues/90

**Comment by athomas** [comment] 2020-05-11 07:54
Closing this as a duplicate of the dart_ci issue.

**Closed by athomas** 2020-05-11 07:54 UTC
Labels: area-infrastructure, type-enhancement
