### ISSUE TITLE
Field marked as nullable when it should be marked as late

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#39873] opened 2019-12-19 19:31 UTC
In the `async` package, in `lib/src/restartable_timer.dart`, on line 22, the following field is marked as being nullable:
```
Timer? _timer;
```
The explanation is that it isn't assigned a value in the initializer list of the only constructor. The observation is true, but the field is initialized in the body of the constructor:
```
RestartableTimer(this._duration, this._callback) {
  _timer = new Timer(_duration, _callback);
}
```
I think it would be better to add `late` to the declaration.

**Comment by lrhn** [comment] 2019-12-20 07:08
It should just be initialized in the initializer list anyway. 

Any chance you can recognize that and move the initialization there instead? That's a more involved fix, moving code around rather than just adding modifiers, so it's probably outside the scope of the migration tool

**Comment by bwilkerson** [comment] 2019-12-20 17:35
Yes, we could analyze the constructor body to determine whether it's possible to move the initialization into the initializer list. Would moving it potentially change the semantics in any subtle way?

I suspect that we don't want to make that big of a change to the code, but if we don't then this is another example of a place that we should bring to the user's attention as a pre-migration change that they might want to make in order to improve the migration.

**Comment by stereotype441** [comment] 2020-01-16 15:23
Duplicate of #38747

**Closed by stereotype441** 2020-01-16 15:23 UTC
Labels: area-analyzer, nnbd-migration-correctness-example
