### ISSUE TITLE
ffi/structs_test crashing with segfault on reload bots

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#54150] opened 2023-11-24 12:00 UTC
There are new test failures on [Remove `Utf8Decoder._convertIntercepted` hook](https://github.com/dart-lang/sdk/commit/cba120dbac7bfd0696e78e8561408c9562713c94).

The tests
```
ffi/structs_test Crash (expected Pass)
```
are failing on configurations
```
vm-reload-rollback-linux-debug-x64
vm-reload-rollback-linux-release-x64
```

Example [log](https://dart-ci.appspot.com/log/vm-reload-rollback-linux-debug-x64/vm-reload-rollback-linux-debug-x64/257/ffi/structs_test):
```
--- Command "vm" (took 16.000947s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-rollback-test-mode --deterministic --optimization-counter-threshold=50 --sound-null-safety -Dtest_runner.configuration=vm-reload-rollback-linux-debug-x64 --ignore-unrecognized-flags --packages=/b/s/w/ir/.dart_tool/package_config.json /b/s/w/ir/tests/ffi/structs_test.dart

exit code:
-6

stderr:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=?(128), si_addr=(nil)
version=3.3.0-edge.84aa0207cfe778e1f1a204bfac02e3a01146fd1d (main) (Thu Nov 23 20:03:22 2023 +0000) on "linux_x64"
pid=15172, thread=15249, isolate_group=main(0x55e06f89e870), isolate=main(0x55e06f8a8700)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=55e06e7567e0, vm_instructions=55e06e7567e0
fp=7fcaff97e070, sp=7fcaff97e060, pc=7fcb1e1b1252
  pc 0x00007fcb1e1b1252 fp 0x00007fcaff97e070 [Optimized] _loadInt64@8050071+0x32
  pc 0x00007fcb1e1b11b9 fp 0x00007fcaff97e0b8 [Unoptimized] Coordinate.get:next+0xc9
  pc 0x00007fcb1e1b1dad fp 0x00007fcaff97e120 [Unoptimized] testStructFromAddress+0x4fd
  pc 0x00007fcb1e1addb4 fp 0x00007fcaff97e150 [Unoptimized] main+0xe4
  pc 0x00007fcb1e1adc88 fp 0x00007fcaff97e178 [Unoptimized] main+0x68
  pc 0x00007fcb1e1adba5 fp 0x00007fcaff97e1d8 [Unoptimized] _Closure@0150898.dyn:call+0x6c5
  pc 0x00007fcb1e1ac995 fp 0x00007fcaff97e218 [Unoptimized] _delayEntrypointInvocation@1026248.<anonymous closure>+0x255
  pc 0x00007fcb1e1ac6c8 fp 0x00007fcaff97e280 [Unoptimized] _Closure@0150898.dyn:call+0x6f8
  pc 0x00007fcb1e1ab6fb fp 0x00007fcaff97e2d8 [Unoptimized] _RawReceivePort@1026248._handleMessage@1026248+0x15b
  pc 0x00007fcb1f083474 fp 0x00007fcaff97e350 [Stub] InvokeDartCode+0xa4
  pc 0x000055e06e99ac0f fp 0x00007fcaff97e3c0 dart::DartEntry::InvokeFunction+0x12f
  pc 0x000055e06e99d7e5 fp 0x00007fcaff97e420 dart::DartLibraryCalls::HandleMessage+0xf5
  pc 0x000055e06e9d2c5d fp 0x00007fcaff97ebb0 dart::IsolateMessageHandler::HandleMessage+0x37d
  pc 0x000055e06ea10c05 fp 0x00007fcaff97ec40 dart::MessageHandler::HandleMessages+0x1d5
  pc 0x000055e06ea118a7 fp 0x00007fcaff97ecc0 dart::MessageHandler::TaskCallback+0x307
  pc 0x000055e06ec09b20 fp 0x00007fcaff97ed50 dart::ThreadPool::WorkerLoop+0x180
  pc 0x000055e06ec0a44b fp 0x00007fcaff97eda0 dart::ThreadPool::Worker::Main+0x12b
  pc 0x000055e06eb3b3a3 fp 0x00007fcaff97eef0 dart::ThreadStart+0x103
-- End of DumpStackTrace

--- Re-run this test:
python3 tools/test.py -n vm-reload-rollback-linux-debug-x64 ffi/structs_test
```

/cc @dcharkes

**Comment by dcharkes** [comment] 2023-11-29 17:21
```
  pc 0x00007fcb1e1b1252 fp 0x00007fcaff97e070 [Optimized] _loadInt64@8050071+0x32
```

Nothing suspicious here, it's force-optimized.

All the last changes are from @sstrickl but they were all green on the CI (and made things better)!

https://github.com/dart-lang/sdk/blame/4bb3b979963d107a9dd97ce964067fa57b06d777/runtime/vm/compiler/frontend/kernel_to_il.cc#L1329-L1396

* https://github.com/dart-lang/sdk/commit/4d1bdaaca9f600545e8517349714f6bf683ebbe3
* https://github.com/dart-lang/sdk/commit/0dc86856cad68edec516d14d1853e2aa78632718
* https://github.com/dart-lang/sdk/commit/4d1bdaaca9f600545e8517349714f6bf683ebbe3

And before that

* 554cc8c0027a97670dd3f9f8b3bb9ebe9a37cc8d

But since the parent is unoptimized, I don't believe any inlining is going on.

I don't see anything obviously wrong here. So I'll need an actual local repro of this crash to address it.

Maybe there is something racy between the hot reload and the typed data backing the struct being moved or something.

**Comment by dcharkes** [comment] 2023-12-21 09:30
The bots have cycled green again: https://dart-ci.web.app/#showLatestFailures=false&test=ffi/structs_test

Also in the commit range of the cycling green I don't see anything relevant.

I'll close this as not reproducible for now, we can reopen it if it reoccurs.

**Closed by dcharkes** 2023-12-21 09:30 UTC
Labels: area-vm, P2, gardening, crash, library-ffi, triaged
