### ISSUE TITLE
Dart analysis server / FATAL error: Failed to handle request

### ISSUE THREAD

**Issue by rabihmb** [dart-lang/sdk#39316] opened 2019-11-09 20:39 UTC
### Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.6.0-edge.70a7ef3f589ec525c2a3b14fa7d47f44d09a29f3`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.70a7ef3f589ec525c2a3b14fa7d47f44d09a29f3, server version 1.27.3, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\Users\user1\Development\Android\Projects\pda], excluded: [C:\Users\user1\Development\Android\Projects\pda\.idea, C:\Users\user1\Development\Android\Projects\pda\.dart_tool, C:\Users\user1\Development\Android\Projects\pda\.pub, C:\Users\user1\Development\Android\Projects\pda\build]}, clientRequestTime: 1573330127530}
FileSystemException: Directory watcher closed unexpectedly, path = 'C:\Users\user1\Development\Android\Projects\pda'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:307:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information,
Dart analysis server, SDK version 2.6.0-edge.70a7ef3f589ec525c2a3b14fa7d47f44d09a29f3, server version 1.27.3, FATAL error: Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\Users\user1\Development\Android\Projects\pda], excluded: [C:\Users\user1\Development\Android\Projects\pda\.idea, C:\Users\user1\Development\Android\Projects\pda\.dart_tool, C:\Users\user1\Development\Android\Projects\pda\.pub, C:\Users\user1\Development\Android\Projects\pda\build]}, clientRequestTime: 1573330127530}
FileSystemException: Directory watcher closed unexpectedly, path = 'C:\Users\user1\Development\Android\Projects\pda'
#0      _FileSystemWatcher._listenOnSocket.<anonymous closure> (dart:io-patch/file_patch.dart:307:11)
#1      _ExpandStream._handleData (dart:async/stream_pipe.dart:248:23)
#2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#3      _rootRunUnary (dart:async/zone.dart:1136:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#9      _StreamController._add (dart:async/stream_controller.dart:640:7)
#10     _StreamController.add (dart:async/stream_controller.dart:586:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```
1573330499718 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[57]}}
1573330500546 => {"id":"18","method":"analysis.updateContent","params":{"files":{"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\pubspec.yaml":{"type":"add","content":"name: pda\nde
1573330500552 <= {"id":"18","result":{}}
1573330500939 => {"id":"19","method":"analysis.updateContent","params":{"files":{"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\pubspec.yaml":{"type":"remove"}}},"clientRequestTime
1573330500950 <= {"id":"19","result":{}}
1573330543024 => {"id":"20","method":"analysis.updateContent","params":{"files":{"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\pubspec.yaml":{"type":"add","content":"name: pda\nde
1573330543024 <= {"id":"20","result":{}}
1573330545433 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\pubspec.yaml","errors":[]}}
1573330545798 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\pubspec.yaml","errors":[]}}
1573330581836 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":150,"uri":"package:pda/models/_mat_images.dart","items":[{"label":"MaterialImages","declaringLibraryUri"
1573330581858 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\models\\_mat_images.dart","errors":[]}}
1573330583563 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":116,"uri":"package:pda/screens/home.dart","items":[{"label":"HomeScreen","declaringLibraryUri":"package:
1573330583710 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\screens\\home.dart","errors":[{"severity":"INFO","type":"HINT","loc
1573330583719 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":13,"uri":"package:pda/screens/listCart.dart","items":[{"label":"ShoppingCartScreen","declaringLibraryUri
1573330583928 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\screens\\listCart.dart","errors":[{"severity":"INFO","type":"LINT",
1573330583931 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":15,"uri":"package:pda/screens/listCategories.dart","items":[{"label":"CategoriesScreen","declaringLibrar
1573330584207 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\screens\\listCategories.dart","errors":[{"severity":"INFO","type":"
1573330584214 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3,"uri":"package:pda/screens/listItems.dart","items":[{"label":"AllProducts","declaringLibraryUri":"pack
1573330584428 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\screens\\listItems.dart","errors":[{"severity":"INFO","type":"HINT"
1573330584535 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":12,"uri":"package:pda/screens/viewInvoice.dart","items":[{"label":"ViewInvoice","declaringLibraryUri":"p
1573330584541 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":67,"uri":"package:pda/utils/drawer_homescreen.dart","items":[{"label":"HomeDrawer","declaringLibraryUri"
1573330584555 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":151,"uri":"package:pda/SqliteDB/PalmProvider.dart","items":[{"label":"DatabaseHelper","declaringLibraryU
1573330584766 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\screens\\viewInvoice.dart","errors":[{"severity":"INFO","type":"LIN
1573330584857 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\SqliteDB\\PalmProvider.dart","errors":[{"severity":"INFO","type":"L
1573330584914 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\utils\\drawer_homescreen.dart","errors":[{"severity":"INFO","type":
1573330586328 => {"id":"21","method":"analysis.updateContent","params":{"files":{"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\utils\\drawer_homescreen.dart":{"type":"add","c
1573330586481 <= {"id":"21","result":{}}
1573330586587 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":67,"uri":"package:pda/utils/drawer_homescreen.dart","items":[{"label":"HomeDrawer","declaringLibraryUri"
1573330586773 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\user1\\Development\\Android\\Projects\\pda\\lib\\utils\\drawer_homescreen.dart","errors":[{"severity":"INFO","type":
1573330586914 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 4, method: analysis.setAnalysisRoots, params: {included: [C:\\Users\\user1\\Devel
```

**Comment by keertip** [comment] 2019-11-11 17:56
Thanks for reporting the issue. This was previously reported in #38853, please follow along there.

**Comment by keertip** [comment] 2019-11-11 17:56
Duplicate of #38853

**Closed by keertip** 2019-11-11 17:56 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
