### ISSUE TITLE
Incorrect behavior of return in async function.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#39204] opened 2019-11-01 14:57 UTC
The Dart 2 behavior for returns in async functions is to await a future if it's a future of the flattened return type.

That is:
```dart
Future<int> foo() { 
   return someExpression;
}
```
will evaluate `someExpression` with context type `FutureOr<int>`, and if it is a `Future<int>`, it is awaited before returning its value.

That it's awaited and not passed directly to a completer (an implementation detail) is important in the case where the return is inside a `try`/`catch` an you try to return a future containing an error.

Example:
```dart
Future<int> foo() {
   try {
     return compute();
   } catch (e) {
     return -1;
   }
}
Future<int> compute() async { 
  throw "No";
}
main() {
 foo().then(print);  // should print -1
}
```

See #22730 for history of the spec change.

**Comment by lrhn** [comment] 2020-04-29 14:52
Another reason awaiting is important is code like:
```dart
Future<int> foo() async {
  try {
    return Future<int>.error("gotcha");
  } finally {
    return 0;
  }
}
```
The issue here is that if the returned future is not awaited *at the return statement*, it will be silently discarded and the error becomes uncaught instead of thrown.

**Comment by natebosch** [comment] 2020-08-14 04:58
It's not clear to me what the concrete actions are to resolve this. Can we describe the specific change we are hoping for in the implementations?

Should we consider pushing on https://github.com/dart-lang/language/issues/870 to fix the ambiguity?

**Comment by stereotype441** [comment] 2021-02-03 16:25
@lrhn @eernstg Is this a duplicate of #44395?

**Comment by eernstg** [comment] 2021-02-03 16:54
Yes, they are very similar, so #44395 is essentially a duplicate of this one. I didn't find this one when I created #44395.

**Comment by stereotype441** [comment] 2021-02-04 16:54
Duplicate of #44395

**Closed by stereotype441** 2021-02-04 16:54 UTC
Labels: area-front-end
