### ISSUE TITLE
CRC library doesn't work for Javascript

### ISSUE THREAD

**Issue by shinayser** [dart-lang/sdk#37705] opened 2019-07-31 22:25 UTC
Hello!

I am using this Google's library for calculating CRC32: https://github.com/google/crclib.dart

But when trying to compile my project to javascript it gives the following error:
```
../../../flutter/.pub-cache/hosted/pub.dartlang.org/crclib-1.0.1/lib/crclib.dart:144:28:
Error: The integer literal 0xFFFFFFFFFFFFFFFF can't be represented exactly in JavaScript.
          ((_value << 8) & 0xFFFFFFFFFFFFFFFF);
                           ^^^^^^^^^^^^^^^^^^
```

This is basically because of the inclusion of CRC64 on the package, wich breaks compatibility with Javascript due to 64 bits numbers. If I edit the library code removing the CRC64, it works nicely.

But if you see on the "pub" page it says that this package is available to web:

![image](https://user-images.githubusercontent.com/1146982/62252270-bdc2c480-b3c8-11e9-822b-2818d955f50f.png)

Is this a Pub bug?

_I'm sorry is this is the wrong place to post it, but since the package's github page has'nt the issues tab and this is a Google library, i thought you guys could to take a look._

**Comment by mit-mit** [comment] 2019-08-01 09:32
Pub.dev classifications are based on the dependencies in `pubspec.yaml`.

But maybe @davidmorgan known why this is failing, and if it actually doesn't support web?

**Comment by davidmorgan** [comment] 2019-08-05 10:15
No idea, sorry--I did touch that package, but only for trivial cleanup.

**Comment by mit-mit** [comment] 2019-08-05 11:17
Got it. @shinayser in any case, the 'WEB' tag as mentioned is based on dependencies, so that is not a bug. But if you wanted to make a PR to the package, I could try to find someone to review it.

**Comment by shinayser** [comment] 2019-08-05 19:28
@mit-mit Yeah I could definetly make a PR. But that pull request would basically remove all the CRC64 code reference and elaving only the 32. Thats because javascript can't understand huge numbers with 64 bits long.

That would be a breaking change. If you guys desire, I can do that.

**Comment by mit-mit** [comment] 2019-08-05 19:37
@vsmenon WDYT?

**Comment by vsmenon** [comment] 2019-08-06 00:31
I don't see any internal use of this at all (@srawlins / @davidmorgan for sanity check).  It appears the original author deleted the internal mirror.

It's not an officially supported package.   

Breaking the 64-bit part out into a different library / file seems reasonable to me.

**Comment by mit-mit** [comment] 2019-08-07 13:06
Closing the present bug as this really isn't an SDK issue

**Closed by mit-mit** 2019-08-07 13:06 UTC
