### ISSUE TITLE
NPE in LspNotificationManager.sendAnalysisErrors

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#48092] opened 2022-01-07 00:28 UTC
It seems that `getLineInfo` does return `null`.
In general, it is unsafe to use null check like this.

```
Thread 0 main thread_CastError: Null check operator used on a null value
at LspNotificationManager.sendAnalysisErrors.<fn>.<fn>(notification_manager.dart:35)
at pluginToDiagnostic(mapping.dart:803)
at LspNotificationManager.sendAnalysisErrors.<fn>(notification_manager.dart:32)
at ListIterable.toList(dart:_internal)
at LspNotificationManager.sendAnalysisErrors(notification_manager.dart:41)
at AbstractNotificationManager.recordAnalysisErrors(notification_manager.dart:128)
at LspServerContextManagerCallbacks.recordAnalysisErrors(lsp_analysis_server.dart:887)
at LspServerContextManagerCallbacks._handleFileResult(lsp_analysis_server.dart:897)
at LspServerContextManagerCallbacks.listenAnalysisDriver.<fn>(lsp_analysis_server.dart:863)
```

I see this crash fairly often internally.
@DanTup

**Comment by DanTup** [comment] 2022-01-07 10:26
@scheglov do you know if the crashing versions include https://github.com/dart-lang/sdk/commit/295aea1eda54a328ff68fe1c38c74fb0a9028c52#diff-0694d50a5039a8413e91c146f29a1f09505e99e062baf6ca215b31a69c154dc6?

If not, I think that should _mostly_ resolve this. If there are any left, it means we're generating diagnostics for files that the resource provide cannot read. I'm not sure what we should do in that situation - if we can't get a `LineInfo` we cannot map the `offset` to line/column (which is required for the LSP protocol).

Perhaps we'd have to drop them in this case, and write a warning to instrumentation log? It would be good to understand in what situation this is happening in the wild (one option would be to change the `!` for a real null check that throws an exception including the file name?).

**Comment by scheglov** [comment] 2022-01-07 20:00
I believe that it has this change. But it does not matter, the method still can return `null`.

It is wrong to get errors generated with one version of a file content, and then some time later try to read this file again and try to match this potentially different file content with the errors. `ErrorsResult` created by the analyzer has `lineInfo`, which should correspond to errors. I think any reads should be done by the analyzer, in `AnalysisDriver`.

**Comment by DanTup** [comment] 2022-01-10 12:00
I had a look through where this method is being used and found that `convertAnalysisError` already has an optional `LineInfo` and I think maybe we should make this required, and then line/cols will already be provided for some of this:

https://github.com/dart-lang/sdk/blob/9826867fd0a9b6f0940e7c169fdb36d7dc189413/pkg/analyzer_plugin/lib/utilities/analyzer_converter.dart#L24-L25

However, I also reviewed the rest of the code calling this method and the fix for those seem less obvious to me, as there are places that need to get `LineInfo`s for other files. For example:

- The `contextMessages` on diagnostics (@bwilkerson is the code [here](https://github.com/dart-lang/sdk/blob/9826867fd0a9b6f0940e7c169fdb36d7dc189413/pkg/analyzer_plugin/lib/utilities/analyzer_converter.dart#L45) incorrectly using the `lineInfo` from the source file, but `contextMessages` locations could be in other files?)
- Plugin diagnostics (I'm not sure if we know what version of the content a plugin is using when it provides diagnostics?)
- Some other LSP requests that need to translate positions in files other than the one the initial request is for (for example when you Go-to-Definition in fileA, the results may include a location in fileB that we need to translate to line/col)

I'm not sure how to handle plugins, but for the others would it make sense to construct the `LineInfo`s for the other files via the session (eg. `unit.result.session.resourceProvider.getFile(otherFilePath)`)? If `session` throws if it's not longer current (which I think it was intended to, but might not be currently?) we could fail those LSP requests as being invalid. It means more requests would fail, but the results should be consistent when they do not?

**Comment by scheglov** [comment] 2022-01-10 17:30
Plugin diagnostics and their locations probably don't have to be _always_ consistent with analyzer diagnostics. But they have to become consistent _eventually_. This means that only a plugin knows for sure which version of code it uses, and how to get any other data from it. Any consumer may only hope that it is the same as the file one disk, but never can be sure.

For navigation - yes, we never know if the file might have changed since the analyzer read it, built the element model, and resolved some file to point at these elements. And even if we check now in DAS, by the time IDE will do navigation, the file might change again.

Any data returned from the analyzer should be consistent to the state when it was generated, that should be a single state - we should not read the same file twice for a single result. And we should not read unless `changeFile(path)` was invoked.

Yes, `session.resourceProvider.getFile(otherFilePath)` will not work by two reasons. (1) The consistency check is broken for sessions. (2) Access to `resourceProvider` was never checked. And (1) is somewhat hard to fix without sacrificing performance. And still, it will not help, because the session is invalidated when you tell `AnalysisDriver.changeFile()`, while the file changed independently, so when you read it, it might be just anything, you don't control this. To handle this, we keep `FileState` objects in the `AnalysisDriver` - our view of the file system.

**Comment by DanTup** [comment] 2022-01-12 15:57
Do I understand correctly then, that for the diagnostics we should use the `LineInfo` we already have, and for plugins or "other files" (such as in results in Go-to-Definition) we can use `result.session.getFile()` on the main result we have, which will get the content from the `AnalysisDriver` (which matches the state when our request got its main resolved unit)?

**Comment by scheglov** [comment] 2022-01-12 17:54
I think for plugins this will not work. Plugins have their own `AnalysisDriver` instances, with their own view on the file system. And this view is not synchronized with the one in the "main" isolate.

As you might have noticed, invalidation for sessions is also broken currently. We keep the same `AnalysisSession` instance, so it never get invalidated, so we will never fail `getFile()`, and will never know that `LineInfo` we get is not consistent with the previous state of the session.

But there is `CompilationUnitElement.lineInfo`, and element models are consistent with the analysis result, regardless if this is the file where the diagnostics is reported, or a context message attachment to the diagnostics. OTOH, if you don't have the element model, and have only `ErrorsResult`, I still don't see any existing way to get consistent information about other files.

**Comment by DanTup** [comment] 2022-01-13 16:25
I think for the Diagnostics themselves we have a `LineInfo` we can use:

https://github.com/dart-lang/sdk/blob/9826867fd0a9b6f0940e7c169fdb36d7dc189413/pkg/analyzer_plugin/lib/utilities/analyzer_converter.dart#L24-L25

It's currently optional but probably could be made required (or at least provided where possible). I don't think it works for context messages that are from different files though (it currently does use the same `LineInfo` but I think that's a bug). 

To address the others, my only thoughts are that we update all the places that compute offsets to also compute line/col while they have access to the file content and pass that around too. I don't know the scale of this, though for the original crash above we could at least switch the diagnostics over which may solve some portion of these issues.

For plugins, I think we'd need to allow plugins to provide line/col too, but I'm not sure what we do if they don't - we could use the current view of the file as a fallback, but ofc it's not guaranteed to be correct.

Any thoughts? (cc @bwilkerson)

**Comment by scheglov** [comment] 2022-01-13 17:11
Yes, it seems to me that the provider of errors should compute all necessary pieces (line and column) when it has access to full consistent data. Because the client will not able to do this consistently.

Or we need to ensure that we keep such consistent state, for example by making state immutable, and making (must be cheap) copies as we "apply" changes. This way theoretically any result will bring the full state with the corresponding state of files that does not change even if there are more changes applied later. Not easy to implement though.

**Comment by DanTup** [comment] 2022-01-14 12:12
I've opened https://dart-review.googlesource.com/c/sdk/+/228201/ which removes _some_ use of `LineInfo` for the call stack above. Diagnostics may already have line/col info, we now use that if it's available.

To me, the first option above (making sure we always carry line/col info around when we compute offsets) seems most straightforward, but I'm less familiar with the code affected by the second. If the first seems better to you, I could try to make some progress on that (with the goal of ultimately removing `server.getLineInfo()` - although we'll need a solution for plugins to completely do that).

**Comment by bwilkerson** [comment] 2022-01-14 18:07
> I don't think it works for context messages that are from different files though (it currently does use the same `LineInfo` but I think that's a bug).

I agree, that's a bug.

> For plugins, I think we'd need to allow plugins to provide line/col too, but I'm not sure what we do if they don't ...

Yes, we'd need to add the line/column info to the plugin protocol and make them required fields. This would be a breaking change to the plugin protocol, and I don't know how many plugins would be broken by it, but I don't see any other solution. If we're going to do that, then we would also have plugins pass the line/column data for the primary message, thus negating the need to pass in a `LineInfo` when converting the primary message. (Which technically is also a bug in the current implementation because the `LineInfo` on the main isolate might not match the `LineInfo` from the content that the plugin uses.)

**Comment by scheglov** [comment] 2022-01-18 16:33
It looks that `NavigationCollectorImpl.addRegion` does not use `offset` and `length` to compute lines, but accepts `Location targetLocation` which already has line/column.

**Comment by DanTup** [comment] 2022-01-19 14:31
If I understand correctly, it uses the offset/length to store a `SouceRange` in `regionMap` which is used for the range on `NavigationRegions` (not targets):

https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/pkg/analyzer_plugin/lib/src/utilities/navigation/navigation.dart#L80-L83

I was trying to add line/cols to both `NavigationTarget` and `NavigationRegion` to get their mapping off using the bad `LineInfo`.

If there's not a reasonable way to handle this here, I could do most of the work on the main branch (eg. have both classes have line/cols and update the mapping to use them - but for now they will not be supplied), then in the breaking change branch we change the signature so they're used. (I suspect we may need to do similar for other related class to).

Out of interest, how frequently are breaking changes merged/shipped? Do they require major SDK releases, or just bumping the major version on the analyzer (and related) packages?

**Comment by DanTup** [comment] 2022-01-19 15:19
@scheglov I found another instance I'm not sure how to handle. When resolving completion items, we compute edits to add the imports like this:

```dart
        final builder = ChangeBuilder(session: session);
        await builder.addDartFileEdit(file, (builder) {
          final result = builder.importLibraryElement(library.uri);
          if (result.prefix != null) {
            newInsertText = '${result.prefix}.$newInsertText';
          }
        });
```

We need to then map these edits to use line/cols instead of offsets. Since the code above includes an `await`, what's the best way to ensure we get a `LineInfo` consistent with the source the `ChangeBuilder` is using?

**Comment by bwilkerson** [comment] 2022-01-19 16:33
> Out of interest, how frequently are breaking changes merged/shipped? Do they require major SDK releases, or just bumping the major version on the analyzer (and related) packages?

They don't require an SDK release, either major or minor, they just require bumping the major version of the analyzer package. They tend to get merged when there are enough changes that they're hard to manage or when there's a need to have a published version containing the changes.

> ... what's the best way to ensure we get a LineInfo consistent with the source the ChangeBuilder is using?

The instance of `DartFileEditBuilderImpl` has a `ResolvedUnitResult` associated with it that contains the line info consistent with the content that was read when the edits were being computed.

**Comment by scheglov** [comment] 2022-01-19 17:30
Ah, I see, you do this mapping in `navigationTargetToLocationLink` for LSP. We don't need this for DAS. And `NavigationTarget` already has `startLine` and `startColumn`. It looks that `regionLineInfo` is already used to convert regions. So, I don't understand why we need to change anything.

Yes, theoretically `ChangeBuilderImpl` uses `AnalysisSession` with which it was created to access any data, and you should get an exception when the session becomes inconsistent. But this is broken now.

**Comment by DanTup** [comment] 2022-01-19 18:26
> It looks that `regionLineInfo` is already used to convert regions. So, I don't understand why we need to change anything.

Currently there are many places in that file (including `regionLineInfo`) that come from calling `server.getLineInfo()`:

https://github.com/dart-lang/sdk/blob/a1e2432679f4d68cfb629c17d42d5018be6f370b/pkg/analysis_server/lib/src/lsp/handlers/handler_definition.dart#L187

My understanding is that this method is problematic because it's not guaranteed to get a `LineInfo` that is consistent with the source used to compute the offsets. So my goal is to remove all code using `server.getLineInfo()` and ensure `LineInfo`s are used that is consistent with the source. In some places, it seems like this will mean extended the classes that carry the offsets around (like `NavigationTarget` and `NavigationRegion`) to also hold line/col information, and compute them as we build the results.

Perhaps I've misunderstood though - do you think there's a simpler way for us to resolve this?

**Comment by scheglov** [comment] 2022-01-19 18:57
We probably should fix `AnalysisSession` promise to throw an exception when it is invalidated by a change to a file. After this, `AnalysisSession.getFile()` could be used to ask `LineInfo`. But this not an easy change to restore `AnalysisSession`, it seems that we need to remove `Element.session` for this and this is a breaking change, and probably many clients to update.

**Comment by bwilkerson** [comment] 2022-01-19 19:03
> We probably should fix `AnalysisSession` ...

+100

> ... it seems that we need to remove `Element.session` for this ...

I don't understand why. The session returned should be the session that created the element, and if the session has been invalidated and it is then used to access information, then throwing an exception is the currently designed way to communicate that the element might no longer be valid.

Is the real issue that we're now back to caching elements across sessions? If so, then the perhaps what we need is for `Element.session` to return the current session when the element is still consistent with that session.

**Comment by DanTup** [comment] 2022-01-25 11:25
Assuming the session issue is fixed, I presume I still need to remove the current implementation of `server.getLineInfo()`, and instead have all requests for `LineInfo` go through a session (which I should capture at the same point as the initial resolved result at the start of each LSP handler)?

**Comment by scheglov** [comment] 2022-01-26 16:10
> Is the real issue that we're now back to caching elements across sessions? If so, then the perhaps what we need is for `Element.session` to return the current session when the element is still consistent with that session.

This is a very good idea, thank you. I implemented it in https://dart-review.googlesource.com/c/sdk/+/230040

Yes, I think going through the session that is captured before asking for an analysis result is conservative and should work.

**Comment by DanTup** [comment] 2022-02-07 16:09
I hit this issue while testing folder renaming today. I'm not sure if it's the same cause as what triggered it here, but for reference:

I did this:
- opened `packages/flutter_tools` from the Flutter repo (at 13b8f5aa8f)
- renamed `lib/src/android` to `lib/src/android2`
- error: "Null check operator used on null value"

The issue seems to be that during a folder rename, the analyzer produces some diagnostics that are a result of some files being renamed and others not. But by the time it tries to send the diagnostics, some of the files in the diagnostics/context messages those have also been renamed, so we fail to get the `LineInfo` through the old flawed function this issue was about.

The change I made in https://dart-review.googlesource.com/c/sdk/+/228201/ reduces the chance of this because it won't try to get a `LineInfo` if the startLine/startCol/endLine/endCol are populated, however in this case there was a `ContextMessage` and for those we _always_ currently use a `LineInfo` because of the bug mentioned above (https://github.com/dart-lang/sdk/blob/9826867fd0a9b6f0940e7c169fdb36d7dc189413/pkg/analyzer_plugin/lib/utilities/analyzer_converter.dart#L45).

There's actually code that tries to drop context message when we can't get a `LineInfo` already (better to miss a context message than throw), but the `!` in the method above applies and prevents it from working.

I'm going to "fix" the above by moving where the `!` is (so it affects less code, and allows the original handling of context messages to work), although fixing the context message location bug above would be much better (because we wouldn't drop context messages as much), however it's certainly much more effort and I'm not sure the best way to do it - there are a lot of places calling `AnalyzerConverter.convertAnalysisError` with a `LineInfo` that isn't sufficient for mapping the context messages. @bwilkerson - do you have any thoughts on the best way to change this?

**Comment by DanTup** [comment] 2022-02-07 16:27
It occurred to me that given the other changes discussed above, perhaps we could also use the session here to get content for `LineInfo`s. Although, that would mean getting the session from within `LspNotificationManager.sendAnalysisErrors` and some of the notifications may be from plugins and I'm not sure if the session consistent makes sense for plugins?

**Comment by bwilkerson** [comment] 2022-02-07 16:33
Without looking at the code, my first impression is that we probably need to
- have protocol-agnostic objects for the diagnostic and the context messages, and those objects need to have either the `LineInfo` or the information derived from it, and
- update the plugin protocol to allow that information to be returned by plugins so that it's consistent with the code the plugin analyzed.

The easiest way to achieve both of those might well be to add the fields needed by LSP to the `common_types_spec.html` in `analyzer_plugin`.

**Comment by DanTup** [comment] 2022-02-07 18:41
@bwilkerson @scheglov I started having a go at adding line/col information to `DiagnosticMessage` which I think would help fix the issues mentioned above (first, the wrong LineInfo mapping context message, which in turn would allow the LSP mapping to avoid fetching LineInfos when mapping DiagnosticMessages).

I pushed the changes to Gerrit in case it's easier to comment directly on the code:

https://dart-review.googlesource.com/c/sdk/+/231661/

It doesn't compile yet, but I wanted to check the approach before I go too far. I ended up having to make changes to `idl.dart` (which if I understand correctly, is a format used to serialise the - data into `.dartServer`?). Without any changes there, my simple test seemed to go through deserialising the data and the new `range` I added was lost.

However, after running the generation scrip, the update `format.dart` file seems to treat the new classes fields as nullable, which causes lots of compile errors I wasn't expected. If this seems like a reasonable approach, I might need some pointers on that.

Thanks!

**Comment by DanTup** [comment] 2022-02-08 10:49
Since the ultimate fix is likely to take longer, I've made a small fix to reduce the scope of the `!` here, which prevents the issue when renaming the large `android` folder noted above, because the `!` no longer applies to mappings of context messages:

https://dart-review.googlesource.com/c/sdk/+/232082/

I'm not sure it's enough for me to be comfortable shipping the work to rename folders in LSP without some other changes, but it should at least reduce the frequency of this error further.

**Closed** 2022-04-07 14:41 UTC
Labels: area-analyzer, P3, analyzer-lsp
