### ISSUE TITLE
IntelliJ issue

### ISSUE THREAD

**Issue by burhanrashid52** [dart-lang/sdk#34878] opened 2018-10-21 09:49 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.4cf2d3990bac1f1df2f524899e1560a3683f3133`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/4y/zvm0gpg5483821qbsxpqnj1c0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.4cf2d3990bac1f1df2f524899e1560a3683f3133, server version 1.20.5, error: Analysis failed: /Users/burhanuddinrashid/Downloads/WhatTodo/lib/pages/tasks/task_complted.dart context: exception_20181021_151830_397
Element mismatch in /Users/burhanuddinrashid/Downloads/WhatTodo/lib/pages/tasks/task_complted.dart at class _TaskCompletedScreenState extends State<TaskCompletedScreen>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-25 13:29
Duplicate of #33930

**Closed by stereotype441** 2018-10-25 13:29 UTC
Labels: area-analyzer
