### ISSUE TITLE
Move vm-kernel group of tests from fyi to main dart buildbot

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30569] opened 2017-08-29 20:47 UTC
I think there is a value in having vm-kernel tests to run on main dart buildbot page so that if tests fails, the team can see it immediately.

I'm not sure what was the reason to run those on https://build.chromium.org/p/client.dart.fyi, but perhaps we can consider moving them to https://build.chromium.org/p/client.dart ? 
cc @mkustermann , @whesse , who might have more information on this.

**Comment by whesse** [comment] 2017-08-30 10:25
@peter-ahe-google @kmillikin @mraleph

**Comment by peter-ahe-google** [comment] 2017-08-30 11:04
I prefer that we keep them on FYI. It's not feasible to run tests on all these configurations before committing.

**Comment by mkustermann** [comment] 2017-08-30 13:49
@aam Does any of our customers use kernel-jit/kernel-aot already?

@whesse Would it be possible to get all kernel-jit/kernel-aot coverage on client.dart and the new try bots?

Ideally if we have very good coverage on try bots **and** good cycle times on them, we could avoid doing extensive testing locally and instead just always use try bots. Given enough, sharded, slaves this should be possible, I guess?

wdyat?

**Comment by peter-ahe-google** [comment] 2017-08-30 14:06
It's currently hard to test that you've made the correct changes to status files locally. I've had some conversations with Bill's team about ideas for solving that, but until those features are in place, I'd prefer to favor local testing over buildbots.

**Comment by whesse** [comment] 2017-08-30 14:14
We just need to know the total amount of time needed by the builder, to see how much it would burden the try bots.  We will be starting with only 30 linux, 10 mac, 10 windows machines, so we can't add much more testing without asking for more machines.  If it is worth it, we could ask for as much as we want, though.

**Comment by aam** [comment] 2017-08-30 14:51
@mkustermann , not that I know of at this point, but they will be used by Flutter (under a flag) as soon as https://github.com/flutter/flutter/pull/11741 lands.

**Comment by peter-ahe-google** [comment] 2017-08-30 14:59
FWIW, I think we have a test coverage issue wrt to Flutter. It uses the incremental kernel driver, but we test the non-incremental version on our build bots.

I think it is important that we address testing of incremental kernel driver before anything else.

@mraleph @sigmundch

**Comment by aam** [comment] 2017-08-30 20:41
@a-siva

**Comment by a-siva** [comment] 2017-08-30 21:32
I think it is critical to move these to the main page, we are moving towards getting kernel-jit and kernel-aot to be the default modes of operation and having these tests which exercise the kernel-aot path hidden does not help (breakages go unnoticed for days and by the time we discover that things are broken lots of CLs have landed on top of an already broken state).

Testing the incremental kernel driver is orthogonal to this and yes we need tests for that which we will get once the command line Dart VM is also changed to use the incremental kernel driver for all the reload tests.

**Comment by peter-ahe-google** [comment] 2017-08-31 11:42
I agree that it is critical to monitor those bots for Siva's team. Unfortunately, the cost of adding these bots isn't paid for by Siva's team if we move the to the main waterfall. Instead, the shared front-end team will have to pay the bill: each time we fix a language test, those other targets may start passing, or go from crashing to failing.

In reality, this means that the shared front-end team has to run all possible VM configurations before commiting a change. That's simply not possible. It takes several hours to test all these configurations.

What we need is a solution where both of our concerns can be addressed, and I don't actually think that's too hard. However, it need to be clear to everyone that:

* That the front-end team isn't expected to run several hours of tests before committing.

* That the front-end team is only responsible for maintaining a limited set of configuration: one for the VM, one for dart2js, and one for ddc.

* That a gardener shouldn't contact the front-end team about status file changes in obscure configurations that the front-end team has no earthly chance of keeping up-to-date on. The bill needs to be paid by the team that decided to add a new configuration, not the front-end team.

**Comment by a-siva** [comment] 2017-09-01 01:00
We decided to move all tools to a common front end with the notion that this would increase productivity and make things easier, if this is making things harder for the front-end team it may mean we do not have the right framework here. The notion that the front end team is responsible for maintaining only a limited set of configurations and yet expect to be used everywhere seems counter to each other.

I don't think it is a reasonable argument to state that important configurations should not be listed in the main waterfall and that teams adding a new configuration are some how responsible for maintaining the front end failure status.

**Comment by peter-ahe-google** [comment] 2017-09-01 11:50
It is correct that we don't have the right framework here. The problem is with our build bots, and who is responsible for maintaining them. We have the same issue with shared tests: if you write a new shared test, it may expose a problem in a component that you have no chance of realizing needed to be tested before committing.

This is the reason that your predecessor actively told his reports to ignore the right side of the build bot waterfall. I don't want to do the same, but at the same time I realize that he had a point. Let's take this opportunity to fix it instead of having unrealistic expectations about how many test configurations individuals can test before committing.

**Comment by lrhn** [comment] 2017-09-01 12:22
I have to concur with Peter that having all configurations on the waterfall makes it hard to make cross-cutting changes, in my case to platform libraries.

It makes sense to have *stable* configurations on the main waterfall. If a configuration isn't stable enough that hitting bugs is rare, it adds a measurable overhead to any change that affects all configurations. 
If an otherwise innocuous change hits a crash in dartkp+dart_precompiled, then there is nothing to do about that except to mark it as such in the status file. Crashes are *expected* for that configuration because it's not stable (and I say that based entirely on experience, it fails a lot for me).  

In the perfect world, we would just check the list of all the errors that a CL caused, then see if any of them are likely caused by a bug in the CL. If not, we update the status files to match the new result, and we are done.
In practice, that usually takes about a day of work for me to do, getting the status file just right that it matches every configuration, and getting the expectation right for that configuration.
I have made a script that can locally run a test in of 22 different configurations, and that's not including debug builds of the VM or platforms other than Linux X64. That helps me, but it doesn't solve the problem.


Imagine having a new platform, `something+whatever` that fails every test. We know it fails every test, we haven't started developing it yet. It's unreasonable to have everybody else update the status file every time they add a new test that also fails. At the other end, we have the VM on Linux which is rock stable. If a test fails on that, it's not unreasonable to assume that the bug is in the test, so in the rare case where it isn't, it's OK to have the test writer update the VM status file.
Where to make the cut between those two isn't trivial, but I do believe we have some configurations on the "stable" waterfall that belongs on the other side of that cut-off point.

A criterion could be whether a test failing on that platform is (much?) more likely to be a because of a bug in the platform or a bug in the test.

It's exceedingly rare that an unstable platform is the *only* one to catch an actual error in a test or library change. If an unstable configuration is red, it can easily be assumed to mean that something has hit a bug in that configuration. The team(s) that are actively working on that configuration are the most qualified to triage those bugs. That's extra work for them, but it is extra work that needs to be done anyway by someone.

**Comment by a-siva** [comment] 2017-10-04 00:13
Did we have a resolution on this ?

**Comment by peter-ahe-google** [comment] 2017-10-04 15:22
There was a particular column you wanted to add, I'm fine with that. I still concerned that we shouldn't add all of the builders.

**Comment by whesse** [comment] 2017-10-04 15:30
There are 15 vm-kernel builders on Dart.FYI.  Only one is not vm-kernel-precomp, vm-kernel-linux-release-x64-checked-be.  Is that the one we are talking about?  The others are vm-kernel-precomp-release sharded 6 ways and vm-kernel-precomp-debug sharded 8 ways.

**Comment by aam** [comment] 2017-10-04 17:17
IIUC vm-kernel-precomp-release(sharded 6 ways) is closest to track preview-dart-2 aot generation employed by Flutter release and profile at this point(well, modulo difference in using "fasta+gen_snapshot+flutter engine" vs "dart_bootstrap+gcc+dart_precompiled_runtime"), so it sounds like that would be most valuable.

**Comment by athomas** [comment] 2017-11-10 19:06
Closing, vm-kernel-precomp-release was moved to the main console.

**Closed by athomas** 2017-11-10 19:06 UTC
Labels: area-infrastructure
