### ISSUE TITLE
[DDS] Subscribing to 'Service' stream throws 'Stream already subscribed' with two clients

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#45569] opened 2021-04-02 18:03 UTC
I have a test in flutter_tools that connects two clients to the vmService on web that runs with DDS enabled. The first client can subscribe to 'Service' stream successfully. but the second cannot - subscribing to 'Service' causes 'Stream already subscribed'  to be thrown.

See the following PR for example:
https://github.com/flutter/flutter/pull/79479

**Comment by bkonyi** [comment] 2021-04-02 18:17
It seems like this is caused by a data race that this test just happened to hit. In particular, this code:

```dart
await Future.wait(<Future<void>>[
  validateFlutterVersion(client1),
  validateFlutterVersion(client2)]
);
```

has two separate clients subscribing to the `Service` stream in `validateFlutterVersion`. These clients issue their `streamListen` requests simultaneously, and `StreamManager` processes them both at roughly the same time, allowing for both requests to bypass the checks we do to avoid having DDS try to subscribe to an existing stream.

We need some form of locking mechanism to ensure `streamListen` requests are processed atomically or refactor subscribed streams checks in such a way that streams are marked as subscribed by DDS before issuing the `streamListen` to the VM service.

**Comment by annagrin** [comment] 2021-07-22 01:09
@bkonyi looks like this is still failing after re-enabling the flutter test: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20web_tool_tests/7333/overview

**Comment by bkonyi** [comment] 2021-07-22 17:59
@annagrin that isn't the same error. Can you please file another issue and assign it to me?

**Closed by bkonyi** 2021-07-22 17:59 UTC
Labels: area-pkg, pkg-dds
