### ISSUE TITLE
"Missing concrete implementation" should also imply an implementation

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29106] opened 2017-03-17 23:10 UTC
Consider this file:

```dart
abstract class A {
  void test();
}

class B extends A { }

class B1 extends B { }
class B2 extends B { }
class B3 extends B { }
class B4 extends B { }

void main() { }
```

It has one error, B doesn't implement `test()`. Even if B1-B4 all implemented `test()`, B would still have to implement it (since it's not abstract). If B implemented it, then B1-B4 would not need to implement it.

The analyzer, however, complains 5 times:

```
[warning] Missing concrete implementation of 'A.test'. (test.dart, line 10, col 7)
[warning] Missing concrete implementation of 'A.test'. (test.dart, line 8, col 7)
[warning] Missing concrete implementation of 'A.test'. (test.dart, line 9, col 7)
[warning] Missing concrete implementation of 'A.test'. (test.dart, line 5, col 7)
[warning] Missing concrete implementation of 'A.test'. (test.dart, line 7, col 7)
```

IMHO the warning on B should imply an implementation of `test`, thus silencing the other warnings (since they would then assume that B would take care of it).

**Comment by srawlins** [comment] 2018-12-05 22:13
Ouch still an issue. Duplicate of #26224.

**Comment by scheglov** [comment] 2024-06-10 20:56
https://dart-review.googlesource.com/c/sdk/+/370662

**Comment by stereotype441** [comment] 2024-06-12 00:12
I have some concerns about usability here. It makes a lot of sense in @Hixie's short example that the errors for `B1` through `B4` are distracting and seemingly irrelevant, because they're so close to `B`.

But is there a danger that the user might get confused if `B1` is in a different package than `B`? If the analyzer is being used in the context of an IDE (using analysis server), and the package containing `B1` is in the user's analysis roots, but the package containing `B` isn't, will the user even see an error at all? It seems like it would be bad if this change caused a circumstance to arise where the user's code didn't run but it appeared to pass analysis with no errors.

I'm not necessarily trying to block implementation of the feature request; I just wanted to make sure this issue was thought about.

**Comment by scheglov** [comment] 2024-06-12 00:42
True, the user will not get any error on `B1`, and if `B` is not open in IDE, no error at all.

I think this us our usual approach - we report the first error, and recover from it. A somewhat similar situation is when some type is unresolved in an external package - we recover with `InvalidType`, and happily allow `unresolved.doesNotExist` in our package.

Me view is that we expect that only code in IDE has errors, because we are still working on it, and external libraries are good.

**Closed by scheglov** 2024-06-12 00:42 UTC
Labels: area-analyzer, analyzer-ux, P2, type-enhancement

**Comment by Hixie** [comment] 2024-06-12 04:15
If an IDE doesn't report that `B` is broken, that seems like a bug in the IDE, because that's the first thing the compiler will be complaining about, and even adding the implementation to all of B1-B4 will not stop that. The only thing that will make that code compile is implementing the member in `B` or making `B` abstract.
