### ISSUE TITLE
Flow analysis issues after continue statement

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#42045] opened 2020-05-26 04:06 UTC
The following code samples doesn't work (produce no compile-time error).

```dart
main() {
  late int i;
  int j = 0;
  outerLoop:
  while (j++ < 3) {
    for (;;) {
      continue outerLoop;
      i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
    }
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
```dart
main() {
  late int i;
  int j = 0;
  while (j++ < 3) {
    continue;
    i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
```dart
main() {
  late int i;
  int j = 0;
  outerLoop:
  while (j++ < 3) {
    int k = 0;
    while (k++ < 3) {
      continue outerLoop;
      i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
    }
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
```dart
main() {
  late int i;
  int j = 0;
  outerLoop:
  while (j++ < 3) {
    do {
      continue outerLoop;
      i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
    } while (false);
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
All of these examples produce only hint about dead code in analyzer and runtime `LateInitializationError` in CFE. Expected result is a compile-time error

Please note that other combinations of loops work as expected (do produce a compile-time error). For example the following code samples WORK
```dart
main() {
  late int i;
  outerLoop:
  for (int j = 0; j < 3; j++) {
    do {
      continue outerLoop;
      i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
    } while (false);
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
```dart
main() {
  late int i;
  var collection = [3, 1, 4, 1, 5];
  for (var j in collection) {
    continue;
    i = 42; // Variable is initialized in a dead code. This leaves it definitely unassigned
  }
  i; // It is an error to read a local late variable when it is definitely unassigned.
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
`Dart VM version: 2.9.0-10.0.dev (dev) (Tue May 19 15:16:48 2020 +0200) on "windows_x64"`

**Comment by leafpetersen** [comment] 2020-09-03 18:13
@stereotype441 @eernstg is this working as intended?

**Comment by eernstg** [comment] 2020-09-04 11:07
The conclusion from https://github.com/dart-lang/sdk/issues/42232 would be that when an assignment to `i` occurs in a while loop `while (E) S` (in dead code or not, this is a quick step that allows us to avoid fixed point iteration), `i` is not 'definitely unassigned' in `before(E)`, hence also not in the body `S` and also not after the loop.

This means that the [examples](https://github.com/dart-lang/sdk/issues/42045#issue-624587087) where an error is expected at `i`, but no error is emitted, are treated correctly. So **the first tests should be adjusted** such that they do not expect that error.

> the following code samples WORK

A do-while statement `do S while (E)` is specified to have the same property (it has `before(S) = conservativeJoin(before(N), assignedIn(N), capturedIn(N))`), so I would expect the **second last test example** (with a do-while inside a for statement) to _not_ consider `i` definitely unassigned, that is, I would expect no error at `i;`, and the test **should be adjusted**.

For the **last test example**, a for-in statement is specified to be desugared to a while statement, and that would imply that it is treated like that while statement which would call for the same behavior as with the first examples: `i` is _not_ considered definitely unassigned at `i;`, so no error should be reported, and the test **should be adjusted**.

But in this case the errors _are_ reported, so that would make the tests fail, and hence **the CFE implementation should be adjusted** such that it stops considering `i` definitely unassigned.

@stereotype441, do you agree on this analysis? Is the analysis which is actually performed preferable? It seems to be more precise, and we don't have any cases where it's unsound. In that case we may need to adjust the flow analysis spec in order to say what it actually does.

**Comment by stereotype441** [comment] 2020-09-07 15:51
@eernstg I agree with your analysis.  I'm not sure why "do while" and "for each" loops are behaving differently.  If no one manages to figure out what's happening there by the time I return from vacation on Wednesday, I'll have a look then.

**Comment by stereotype441** [comment] 2020-09-10 19:02
The reason "for each" loops are behaving differently is because they are analyzed in a weird way.  The "conservative join" operation (which is reponsible for flow analysis deciding that `i` might be assigned to) happens after the control flow split, so it doesn't influence the code after the loop in the way it does for other loops.  It should be pretty trivial to modify "for each" loops so that their analysis is consistent with their desugaring.  I'll work on this as soon as I can.

**Comment by stereotype441** [comment] 2020-09-12 19:11
> The reason "for each" loops are behaving differently is because they are analyzed in a weird way. The "conservative join" operation (which is reponsible for flow analysis deciding that `i` might be assigned to) happens after the control flow split, so it doesn't influence the code after the loop in the way it does for other loops. It should be pretty trivial to modify "for each" loops so that their analysis is consistent with their desugaring. I'll work on this as soon as I can.

As of 337dd5d35592d5a94454f705a910b60c832b8212, the conservative join now happens before the control flow split, making "for each" loops handled more similarly to their desugared equivalents.

**Comment by leafpetersen** [comment] 2020-09-28 18:38
@eernstg what's the status on this?  Is this resolved?

**Comment by eernstg** [comment] 2020-09-29 10:28
Yes, https://github.com/dart-lang/sdk/commit/337dd5d35592d5a94454f705a910b60c832b8212 introduces the for-in related change to `_fe_analyzer_shared`, covering both the CFE and the analyzer. Also, I've asked @sgrekhov to create co19 issues for tests where the situations illustrated [here](https://github.com/dart-lang/sdk/issues/42045#issue-624587087) occur, so I believe it is resolved.

**Closed by eernstg** 2020-09-29 10:28 UTC
Labels: area-front-end, type-bug
