### ISSUE TITLE
 Regression in analyzer messages/behavior when using extension methods without adequate SDK bounds

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#42148] opened 2020-06-01 23:09 UTC
In my IDE, when using an extension methods in a project with SDK bounds that are too low, I used to get a helpful error message, and now I don't in newer versions of the SDK.

##### Using Dart 2.7.2:
<img width="717" alt="Screen Shot 2020-06-01 at 3 36 54 PM" src="https://user-images.githubusercontent.com/1713967/83462770-eb313200-a420-11ea-8f98-1ca7ceb124a1.png">

##### Using Dart 2.8.1 (also reproduces in 2.8.3):
- On the first extension in the class
    <img width="707" alt="Screen Shot 2020-06-01 at 3 59 35 PM" src="https://user-images.githubusercontent.com/1713967/83462835-11ef6880-a421-11ea-909b-359500fec0bb.png">
- On another extension (additional error message)
    <img width="696" alt="Screen Shot 2020-06-01 at 4 02 20 PM" src="https://user-images.githubusercontent.com/1713967/83462914-482ce800-a421-11ea-84cd-0094e24fd371.png">

I also get a bunch of other errors, creating a bunch of noise when trying to figure out the issue.
<img width="441" alt="Screen Shot 2020-06-01 at 4 04 02 PM" src="https://user-images.githubusercontent.com/1713967/83462988-83c7b200-a421-11ea-92c1-89a847f3a0bc.png">

It took me quite a while to determine the cause of the issue, and I only did after finding https://github.com/dart-lang/sdk/issues/40164 

(For reference, the fix is to raise the lower SDK bound to 2.7.0)

I'm not sure if this is a duplicate of that issue, since the description made it seem like it was a new improvement vs a regression, so feel free to close this one if needed.

**Comment by greglittlefield-wf** [comment] 2020-06-01 23:21
Oh yeah, and for searchability of this issue, here are some of the error messages you might encounter:

>error: Undefined class 'extension'. (undefined_class at ...)

> error: This requires the 'extension-methods' experiment to be enabled. (experiment_not_enabled at ...)

> Invalid reference to 'this' expression.

> error: Iterable isn't a type.

> error: Future isn't a type.

**Comment by srawlins** [comment] 2020-06-16 21:22
Thanks for reporting this issue! This was previously opened as https://github.com/dart-lang/sdk/issues/40164; please follow along there.

**Comment by srawlins** [comment] 2020-06-16 21:22
Duplicate of #40164

**Closed by srawlins** 2020-06-16 21:22 UTC
Labels: area-analyzer
