### ISSUE TITLE
Socket.connect Future will not time out when sourceAddress is provided

### ISSUE THREAD

**Issue by butlermatt** [dart-lang/sdk#26790] opened 2016-06-29 14:06 UTC
Dart version: Dart VM version: 1.17.1 (Fri Jun 10 04:46:03 2016) on "macos_x64" (Mac OS 10.11.5)

Following code will time out after 2 seconds as expected (note the address is intentionally NOT accessible)
```dart
import "dart:io";
import "dart:async";

Future main() async {
        Socket sock;
        try {
                sock = await Socket.connect("192.168.168.168", 3001)
                    .timeout(new Duration(seconds: 2), onTimeout: () {
                        throw new TimeoutException("Socket timed out");
                });
        } on TimeoutException catch (e) {
                print('Timed out');
                rethrow;
        } catch (e) {
                print('Other Caught');
                rethrow;
        } finally {
                sock?.close();
        }
}
```

However change the socket to accept a source address and it does not respect the 2 second limit.

```dart
 sock = await Socket.connect("192.168.168.168", 3001, sourceAddress: "192.168.168.20")
    .timeout(new Duration(seconds: 2), onTimeout: () {
// ...
```

Expected Behaviour: Times out after 2 seconds, executing the onTimeout method.
Actual Behaviour: onTimeout is never called. Fails instead with `SocketException`. It also appears that the operation is in fact blocking as certain other events on the event loop do not resume until after the SocketException is thrown.

This is a big blocker for me as I need to be able to bind the socket to a specific IP particularly when working on machines with multiple network interfaces.

**Comment by floitschG** [comment] 2016-07-29 19:56
I just tried to reproduce on Linux, but failed so far. I don't have access to a Mac at the moment (maybe next week), so I'm not sure if this is platform dependent.

If you have easy access to a Linux machine, it would be great if you could try to reproduce on Linux.

Also: could you please provide the SocketException you get? On Linux, I get a SocketException, when Dart can't bind to the source-address:
`SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = 192.168.168.168, port = 3001`.

Fwiw: the SocketException should contain the source-address, since that's the one that made troubles. I tried to fix this, but it would take a bit of work: Windows does the binding at the same time as connecting, and the library's architecture thus merges those two operations.

**Comment by butlermatt** [comment] 2016-08-02 16:02
Yes, you're correct it seems to be platform dependent. I tried this on a Pi2 (Raspbian with the ARM dart version) and the timeout happens as expected after 2 seconds.

On the Mac machine I'm currently running dart 1.18 and continue to see the same issue.
More on the mac:
If I do not have the interface active that I'm trying to use as the sourceAddress, it fails immediately with the same error you specified.
If I omit the `sourceAddress: ..` named parameter then after a couple of seconds I receive the expected TimeoutException that I generate.
Otherwise, after a fairly long period of time, I receive the following error:

```Unhandled exception:
SocketException: Connection failed (OS Error: Operation timed out, errno = 60), address = 192.168.168.168, port = 3001```

Which is expected as the destination address isn't available, I'd simply prefer that the `.timeout()` executed simply due the the operating system's default connection time out.

**Comment by floitschG** [comment] 2016-08-02 16:55
Hmm. I just noticed that `CreateBindConnect` in the `socket_macos.cc` does not call `SetNonBlocking`, whereas `CreateConnect` does call it. I'm now guessing that this was just forgotten, and that this issue could be fixed by adding one line:

```diff
diff --git a/runtime/bin/socket_macos.cc b/runtime/bin/socket_macos.cc
index 708cd3c..b6b0e50 100644
--- a/runtime/bin/socket_macos.cc
+++ b/runtime/bin/socket_macos.cc
@@ -99,6 +99,8 @@ intptr_t Socket::CreateBindConnect(const RawAddr& addr,
     return -1;
   }
 
+  FDUtils::SetNonBlocking(fd);
+
   return Connect(fd, addr);
 }
 ```

I will try to find a mac tomorrow and see if that solves the issue, and if all tests still work with that line.

**Comment by floitschG** [comment] 2016-08-04 14:00
This should be fixed. (Untested since I don't have a mac closeby, but the fix was pretty obvious).

**Closed by floitschG** 2016-08-04 14:00 UTC
Labels: area-library, library-io
