### ISSUE TITLE
tsan: Scavenger heap_ data race between IdleTimeHandler and something else(that tsan failed to restore the stack for)

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#42866] opened 2020-07-29 02:02 UTC
from [tsan buildbot logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8873482113211815504/+/steps/build_dart/0/stdout):

```
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/b/s/w/ir/cache/builder/sdk/.packages --snapshot=gen/dds.dart.snapshot --snapshot-depfile=/b/s/w/ir/cache/builder/sdk/out/ReleaseTSANX64/gen/dds.dart.snapshot.d --snapshot-kind=app-jit /b/s/w/ir/cache/builder/sdk/out/ReleaseTSANX64/gen/utils/dds/generate_dds_snapshot.dart.dill
Command failed: ./dart --deterministic --packages=/b/s/w/ir/cache/builder/sdk/.packages --snapshot=gen/dds.dart.snapshot --snapshot-depfile=/b/s/w/ir/cache/builder/sdk/out/ReleaseTSANX64/gen/dds.dart.snapshot.d --snapshot-kind=app-jit /b/s/w/ir/cache/builder/sdk/out/ReleaseTSANX64/gen/utils/dds/generate_dds_snapshot.dart.dill
output: ==================
WARNING: ThreadSanitizer: data race (pid=5148)
  Read of size 1 at 0x7b6c00001452 by thread T4:
    #0 dart::Scavenger::ShouldPerformIdleScavenge(long) ../../out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.cc:1000 (dart+0x1f77ffe)
    #1 dart::Heap::NotifyIdle(long) ../../out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:414 (dart+0x1f614de)
    #2 dart::IdleTimeHandler::NotifyIdle(long) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:249 (dart+0x1ce614f)
    #3 dart::IdleTimeHandler::NotifyIdleUsingDefaultDeadline() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:260 (dart+0x1ce614f)
    #4 dart::MutatorThreadPool::NotifyIdle() ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:337 (dart+0x1ce614f)
    #5 dart::MutatorThreadPool::OnEnterIdleLocked(dart::MonitorLocker*) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:326 (dart+0x1ce606d)
    #6 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:167 (dart+0x1f1ce58)
    #7 dart::ThreadPool::Worker::Main(unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:323 (dart+0x1f1d655)
    #8 dart::ThreadStart(void*) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:153 (dart+0x1e23e52)

  Previous write of size 1 at 0x7b6c00001452 by main thread:
    [failed to restore the stack]

  Location is heap block of size 1632 at 0x7b6c00000e00 allocated by main thread:
    #0 operator new(unsigned long) ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_new_delete.cpp:64 (dart+0x1a21447)
    #1 dart::Heap::Init(dart::IsolateGroup*, long, long) ../../out/ReleaseTSANX64/../../runtime/vm/heap/heap.cc:720 (dart+0x1f633ea)
    #2 dart::IsolateGroup::CreateHeap(bool, bool) ../../out/ReleaseTSANX64/../../runtime/vm/isolate.cc:446 (dart+0x1ce7d02)
    #3 Dart_CreateIsolateGroup ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:1516 (dart+0x260300d)
    #4 dart::bin::CreateIsolateGroupAndSetupHelper(bool, char const*, char const*, char const*, Dart_IsolateFlags*, void*, char**, int*) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:684 (dart+0x1a2bdc6)
    #5 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:844 (dart+0x1a2b1d3)
    #6 dart::bin::main(int, char**) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:1231 (dart+0x1a2ca0c)
    #7 main ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:1271 (dart+0x1a2d8b2)

  Thread T4 'DartWorker' (tid=5153, running) created by main thread at:
    #0 pthread_create ../recipe_cleanup/clangshYTOG/llvm_build_dir/tools/clang/stage2-bins/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:962 (dart+0x19b3f5b)
    #1 dart::OSThread::Start(char const*, void (*)(unsigned long), unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/os_thread_linux.cc:172 (dart+0x1e23cdc)
    #2 dart::ThreadPool::Worker::StartThread() ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:296 (dart+0x1f1c329)
    #3 dart::ThreadPool::RunImpl(std::__2::unique_ptr<dart::ThreadPool::Task, std::__2::default_delete<dart::ThreadPool::Task> >) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.cc:94 (dart+0x1f1c329)
    #4 bool dart::ThreadPool::Run<dart::MessageHandlerTask, dart::MessageHandler*>(dart::MessageHandler*&&) ../../out/ReleaseTSANX64/../../runtime/vm/thread_pool.h:46 (dart+0x1d39fbd)
    #5 dart::MessageHandler::Run(dart::ThreadPool*, dart::MessageHandler::MessageStatus (*)(unsigned long), void (*)(unsigned long), unsigned long) ../../out/ReleaseTSANX64/../../runtime/vm/message_handler.cc:121 (dart+0x1d39fbd)
    #6 Dart_RunLoop ../../out/ReleaseTSANX64/../../runtime/vm/dart_api_impl.cc:2065 (dart+0x2605bc6)
    #7 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:941 (dart+0x1a2b50a)
    #8 dart::bin::main(int, char**) ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:1231 (dart+0x1a2ca0c)
    #9 main ../../out/ReleaseTSANX64/../../runtime/bin/main.cc:1271 (dart+0x1a2d8b2)

SUMMARY: ThreadSanitizer: data race ../../out/ReleaseTSANX64/../../runtime/vm/heap/scavenger.cc:1000 in dart::Scavenger::ShouldPerformIdleScavenge(long)
==================
ThreadSanitizer: reported 1 warnings
```

**Comment by rmacnak-google** [comment] 2020-08-03 23:47
Duplicate of https://github.com/dart-lang/sdk/issues/42812

**Closed by rmacnak-google** 2020-08-03 23:47 UTC
Labels: area-vm
