### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by fabryx92** [dart-lang/sdk#38351] opened 2019-09-12 01:42 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
Internal problem: Unhandled  " in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:45:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:58:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#11     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#12     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#13     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5226:12)
#14     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3814:14)
#15     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#16     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#17     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#18     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#19     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#20     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#21     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#22     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#23     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#24     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#25     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#26     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#27     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#28     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#29     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#30     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#31     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#48     new Future.sync (dart:async/future.dart:224:31)
#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#55     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#56     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#57     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#58     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#59     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#60     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
1568252232469 => {"id":"7959","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","offset":7688,"length":0},"clientReque
1568252232473 <= {"id":"7958","result":{"fixes":[{"error":{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_mod
1568252232478 <= {"id":"7959","result":{"assists":[]}}
1568252235400 => {"id":"7960","method":"edit.getAssists","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","offset":7673,"length":15},"clientRequ
1568252235404 <= {"id":"7960","result":{"assists":[]}}
1568252235565 => {"id":"7961","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart":{"type":"add","content":"impo
1568252235565 => {"id":"7962","method":"completion.getSuggestions","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","offset":7674},"clientReques
1568252235565 <= {"id":"7961","result":{}}
1568252235566 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1568252235583 <= {"id":"7962","result":{"id":"986"}}
1568252235583 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNIN
1568252235585 <= {"event":"completion.existingImports","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","imports":{"elements":{"strings":["packa
1568252235590 <= {"event":"completion.results","params":{"id":"986","replacementOffset":7673,"replacementLength":1,"results":[{"kind":"INVOCATION","relevance":1000,"completion":"hashCode","selectionOf
1568252235591 <= {"event":"analysis.highlights","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","regions":[{"type":"DIRECTIVE","offset":0,"leng
1568252235594 <= {"event":"analysis.navigation","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","regions":[{"offset":7,"length":24,"targets":[0
1568252235595 <= {"event":"analysis.outline","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","kind":"LIBRARY","outline":{"element":{"kind":"COM
1568252235595 <= {"event":"analysis.overrides","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","overrides":[{"offset":6756,"length":8,"supercla
1568252235596 <= {"event":"flutter.outline","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length
1568252235602 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":956,"uri":"package:mobile_app/requests/requests_request_view_model.dart","items":[{"label":"RequestsRequ
1568252235603 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1568252235603 <= {"event":"analysis.implemented","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","classes":[],"members":[]}}
1568252235606 => {"id":"7963","method":"analysis.updateContent","params":{"files":{"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart":{"type":"add","content":"impo
1568252235606 => {"id":"7964","method":"completion.getSuggestions","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","offset":7675},"clientReques
1568252235607 <= {"id":"7963","result":{}}
1568252235607 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1568252235643 <= {"id":"7964","result":{"id":"987"}}
1568252235643 <= {"event":"analysis.errors","params":{"file":"/Users/fabryx/Work/TiAssisto/mobile_app/lib/requests/requests_request_view_model.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERR
1568252235651 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Internal problem: Unhandled  \" in analyzeQuote.\n#0      internalProblem (package:front
1568252235663 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Internal problem: Unhandled  \" in analyzeQuote.\n#0      internalProblem (package:front
1568252235663 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"Internal problem: Unhandled  \" in analyzeQuote.\n#0      Driver._captureExceptions.erro
```

**Comment by srawlins** [comment] 2019-11-30 00:58
Duplicate of https://github.com/dart-lang/sdk/issues/38160

**Closed by srawlins** 2019-11-30 00:58 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
