### ISSUE TITLE
If part directive's URI is invalid, the corresponding LibraryPart is missing

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#31004] opened 2017-10-04 19:56 UTC
```dart
library lib;
part 'ht:';
```

![image](https://user-images.githubusercontent.com/384794/31196647-5664788c-a903-11e7-960f-81a0cbe7f31e.png)

Might be related to https://github.com/dart-lang/sdk/issues/30997 and https://github.com/dart-lang/sdk/issues/30959

**Comment by peter-ahe-google** [comment] 2017-10-05 08:55
I think this is a duplicate of #30997.

**Comment by peter-ahe-google** [comment] 2017-10-05 08:56
Actually, I'm not sure this is a duplicate after all. I'll let @askeksa-google make that call.

**Closed** 2017-11-03 12:56 UTC
Labels: area-front-end, front-end-fasta, front-end-fasta-recovery
