### ISSUE TITLE
Dart Analyzer Error + lost ctrl-click goto declaration etc.

### ISSUE THREAD

**Issue by biancashouse** [dart-lang/sdk#35208] opened 2018-11-18 23:50 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1344x840`

# Exception

Please append the contents of:
file:///private/var/folders/pd/5nkbdv0909n1vw71tt31yy900000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/ianw/my/code/flutter/flowcharter/lib/edit_function_page.dart context: exception_20181119_104644_045
Exception: Element not found in summary: dart:async

**Comment by biancashouse** [comment] 2018-11-18 23:53
I tried deleting my .idea and .iml files.
I still see the Dart Analyzer Error message in the Event Log, but now ctrl-click works, although it is not quite right: it takes you to the declaration, but also pops up a context menu.

Using mac pro and Eclipse keys maping.

**Comment by biancashouse** [comment] 2018-11-18 23:59
Shift-Command-G, which is the eclipse key combination for 'find usages', no longer working.
Really don't want to have to use vscode; i'm comfortable with studio. Hope there's a simple answer to this. I guess it's the Dart Analyzer playing up ? Perhaps I'd get the same issue in vscode anyway. Will try it out...

**Comment by biancashouse** [comment] 2018-11-19 00:04
"no results" when i do the same in vscode. Dart Analyzer gone awol.
Is it this related to the old issue regarding the ommssion of the 'new' keyword ?

**Comment by biancashouse** [comment] 2018-11-19 01:10
Whoa. "Usages of" suddenly working.

**Comment by stereotype441** [comment] 2018-11-29 17:44
Duplicate of #34555

**Closed by stereotype441** 2018-11-29 17:44 UTC
Labels: area-analyzer
