### ISSUE TITLE
override issue

### ISSUE THREAD

**Issue by dafinoer** [dart-lang/sdk#43670] opened 2020-10-05 05:23 UTC
Hi dart team, when i created abstract class with dynamic type Map parameter, and then i used at my MemberClass (for example) but after override i have issue with dynamic type Map parameter. They not automatically create `Map<String, dynamic> params`.

```
abstract class  Person {
  String getItem(Map<String, dynamic> params);
}
```

```
class Member with Person {
@override
  String getItem(Map<String, > params) {
    // TODO: implement getMap
    throw UnimplementedError();
  }
}
```

**Comment by eernstg** [comment] 2020-10-05 10:29
You can specify the parameter types and return type for a method explicitly, or you can leave them out and obtain them implicitly from your superclass (or a class that your class implements), as long as they agree.

```dart
abstract class  Person {
  String getItem(Map<String, dynamic> params);
}

class Member implements Person {
  @override
  getItem(params) {
    // TODO: implement getMap
    throw UnimplementedError();
  }
}
```

Your example had `Map<String, >` as the type, but I guess that's a typo because it is a syntax error. I changed `with` to `implements`; it is not an error to use `Person` as a mixin, but given that it doesn't provide any method implementations it seems pointless to have `Person` as a mixin. Similarly, you could use `extends`, but using `implements` is more flexible and would generally be preferred when no implementation is inherited.

I'll close this issue because I don't see anything here that isn't working as intended, but don't hesitate to create a new issue if you encounter something that looks like a bug.

**Closed by eernstg** 2020-10-05 10:29 UTC
Labels: closed-as-intended
