### ISSUE TITLE
Pattern guard condition type promotion

### ISSUE THREAD

**Issue by rich-j** [dart-lang/sdk#52393] opened 2023-05-14 05:11 UTC
Dart 3 introduces patterns with guard conditions that can be used with the new `switch` expression - nice. However, local variable types checked in the guard condition don't get promoted by the compiler even though the `dart analyzer` doesn't complain.

In the following example, the string `s` is checked to be not null in the guard condition and the analyzer doesn't complain:

```dart
String f(int x, {String? s}) => switch (x) {
  _ when s != null => s,
  _ => "is null"
};
```

However compilation fails with:
```
Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.
```

The compile error can be fixed with a non-null assertion `_ when s != null => s!,`. Now we get an analyzer warning `The '!' will have no effect because the receiver can't be null`. This warning can then be silenced with `// ignore_for_file: unnecessary_non_null_assertion`.

The resulting code works. The compiler does correctly promote the type if the same local variable null-check is used in an `if` condition or ternary expression and we expected the guard condition to behave similarly.

**Comment by lrhn** [comment] 2023-05-15 21:37
No analyzer warning, but front end gives the error above.

**Comment by stereotype441** [comment] 2023-05-16 17:34
This is a known issue that I discovered just before 3.0 shipped, when there was no longer time to cherry-pick a fix. The fix has been cherry-picked to stable, and will ship in 3.0.1.

Tracking issue is here: https://github.com/dart-lang/sdk/issues/52241

**Comment by stereotype441** [comment] 2023-05-16 17:34
Duplicate of #52241

**Closed by stereotype441** 2023-05-16 17:34 UTC
Labels: area-front-end
