### ISSUE TITLE
Android Studio Error Report Suggestion

### ISSUE THREAD

**Issue by KarakayaFSM** [dart-lang/sdk#39403] opened 2019-11-15 21:42 UTC
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
type 'FunctionExpressionInvocationImpl' is not a subtype of type 'SuperExpression'
#0      AstBuilder.buildInitializer (package:analyzer/src/fasta/ast_builder.dart:401:25)
#1      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1369:44)
#2      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2586:14)
#3      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2523:14)
#4      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3250:13)
#5      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#6      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#7      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#8      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#9      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#10     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#11     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#12     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#13     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#14     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#15     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#16     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#17     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#18     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#24     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#30     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#31     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#33     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#34     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#35     new Future.sync (dart:async/future.dart:224:31)
#36     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#42     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#43     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#44     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
1573853167019 => {"id":"7011","method":"edit.getFixes","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","offset":3858},"clientRequestTime":1573853167019}
1573853167021 <= {"id":"7011","result":{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","offset":3858,"length":4,"s
1573853167022 => {"id":"7012","method":"edit.getFixes","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","offset":3858},"clientRequestTime":1573853167022}
1573853167025 <= {"id":"7012","result":{"fixes":[{"error":{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","offset":3858,"length":4,"s
1573853167036 => {"id":"7013","method":"edit.getAssists","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","offset":3862,"length":0},"clientRequestTime":1573853167036}
1573853167048 <= {"id":"7013","result":{"assists":[{"message":"Add padding","edits":[{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","fileStamp":0,"edits":[{"offset":3858,"length":4,"replac
1573853167612 => {"id":"7014","method":"analysis.updateContent","params":{"files":{"D:\\FlutterProjects\\flutter_app\\lib\\main.dart":{"type":"add","content":"import 'package:flutter/cupertino.dart';\
1573853167635 <= {"id":"7014","result":{}}
1573853167659 => {"id":"7015","method":"edit.getAssists","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","offset":3861,"length":0},"clientRequestTime":1573853167659}
1573853167690 <= {"event":"analysis.errors","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","errors":[{"severity":"ERROR","type":"STATIC_WARNING","location":{"file":"D:\\FlutterPro
1573853167692 <= {"id":"7015","result":{"assists":[]}}
1573853167693 <= {"event":"analysis.highlights","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":40},{"type":"BUILT_IN","offset":0
1573853167695 <= {"event":"analysis.navigation","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","regions":[{"offset":7,"length":32,"targets":[0]},{"offset":48,"length":31,"targets"
1573853167695 <= {"event":"analysis.closingLabels","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","labels":[{"offset":309,"length":162,"label":"MaterialApp"},{"offset":998,"length
1573853167696 <= {"event":"analysis.outline","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","locat
1573853167697 <= {"event":"analysis.overrides","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","overrides":[{"offset":268,"length":5,"superclassMember":{"element":{"kind":"METHOD",
1573853167699 <= {"event":"flutter.outline","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":3866,"codeOffset":0,"codeLength":38
1573853167702 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":710,"uri":"package:flutter_app/main.dart","items":[{"label":"Page2","declaringLibraryUri":"package:flutt
1573853167702 <= {"event":"analysis.implemented","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","classes":[],"members":[]}}
1573853167997 => {"id":"7016","method":"analysis.updateContent","params":{"files":{"D:\\FlutterProjects\\flutter_app\\lib\\main.dart":{"type":"add","content":"import 'package:flutter/cupertino.dart';\
1573853168009 <= {"id":"7016","result":{}}
1573853168020 => {"id":"7017","method":"edit.getAssists","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","offset":3856,"length":0},"clientRequestTime":1573853168020}
1573853168031 <= {"event":"analysis.errors","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"D:\\FlutterPr
1573853168031 <= {"event":"analysis.highlights","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","regions":[]}}
1573853168032 <= {"event":"analysis.navigation","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","regions":[],"targets":[],"files":[]}}
1573853168032 <= {"event":"analysis.closingLabels","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","labels":[]}}
1573853168032 <= {"event":"analysis.outline","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","locat
1573853168033 <= {"event":"analysis.overrides","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","overrides":[]}}
1573853168033 <= {"event":"flutter.outline","params":{"file":"D:\\FlutterProjects\\flutter_app\\lib\\main.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":0,"codeOffset":0,"codeLength":0,"da
1573853168043 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"type 'FunctionExpressionInvocationImpl' is not a subtype of type 'SuperExpression'\n#0  
```

**Comment by srawlins** [comment] 2019-11-18 04:27
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37992; please follow along there.

**Comment by srawlins** [comment] 2019-11-18 04:27
Duplicate of https://github.com/dart-lang/sdk/issues/37992

**Closed by srawlins** 2019-11-18 04:27 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
