### ISSUE TITLE
Analysis Server Crash: RangeError (index): Invalid value: Not in inclusive range

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/sdk#44040] opened 2020-11-03 14:23 UTC
## Dart analysis issue

I left Intellij up over night, and when I came back, the analysis server had crashed with the following stack.

RangeError (index): Invalid value: Not in inclusive range 0..401: 402

## Version information

- Dart SDK 2.12.0-3.0.dev
- Dart IntelliJ 202.7319.5
- IntelliJ IDEA 2020.2.2
- Linux 5.7.17-1rodete4-amd64

## Details

RangeError (index): Invalid value: Not in inclusive range 0..401: 402

```
#0      List.[] (dart:core-patch/array.dart:37:52)
#1      _FbGenericList.[] (package:analyzer/src/summary/flat_buffers.dart:741:20)
#2      LinkedUnitContext.getInformativeData (package:analyzer/src/summary2/linked_unit_context.dart:428:27)
#3      AstBinaryReader._declaredIdentifier (package:analyzer/src/summary2/ast_binary_reader.dart:82:40)
#4      AstBinaryReader._read_methodDeclaration (package:analyzer/src/summary2/ast_binary_reader.dart:1183:7)
#5      AstBinaryReader._readNode (package:analyzer/src/summary2/ast_binary_reader.dart:1845:16)
#6      AstBinaryReader.readNode (package:analyzer/src/summary2/ast_binary_reader.dart:62:14)
#7      LazyClassDeclaration.readMembers (package:analyzer/src/summary2/lazy_ast.dart:214:34)
#8      LinkedUnitContext._getClassOrExtensionOrMixinMembers (package:analyzer/src/summary2/linked_unit_context.dart:1123:28)
#9      LinkedUnitContext.getConstructors.sync_op (package:analyzer/src/summary2/linked_unit_context.dart:230:21)
#10     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:184:26)
#11     MappedIterator.moveNext (dart:_internal/iterable.dart:391:19)
#12     new List.from (dart:core-patch/array_patch.dart:50:19)
#13     new List.of (dart:core-patch/array_patch.dart:68:17)
#14     Iterable.toList (dart:core/iterable.dart:404:12)
#15     ClassElementImpl.constructors (package:analyzer/src/dart/element/element.dart:544:10)
#16     ClassElementImpl.unnamedConstructor (package:analyzer/src/dart/element/element.dart:885:40)
#17     InterfaceTypeImpl.lookUpConstructor (package:analyzer/src/dart/element/type.dart:877:36)
#18     ElementResolver.visitConstructorName (package:analyzer/src/generated/element_resolver.dart:254:28)
#19     ConstructorNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:2709:49)
#20     ResolverVisitor.visitConstructorName (package:analyzer/src/generated/resolver.dart:1169:10)
#21     ConstructorNameImpl.accept (package:analyzer/src/dart/ast/ast.dart:2709:49)
#22     ResolverVisitor.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1563:27)
#23     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6070:15)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7544:20)
#25     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6697:15)
#26     TypedLiteralResolver.resolveListLiteral (package:analyzer/src/dart/resolver/typed_literal_resolver.dart:97:10)
#27     ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:1592:27)
#28     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6692:49)
#29     AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:85:10)
#30     DefaultValueResolver._parameter (package:analyzer/src/summary2/default_value_resolver.dart:107:18)
#31     DefaultValueResolver._parameters (package:analyzer/src/summary2/default_value_resolver.dart:121:7)
#32     DefaultValueResolver._constructor (package:analyzer/src/summary2/default_value_resolver.dart:74:5)
#33     DefaultValueResolver._class (package:analyzer/src/summary2/default_value_resolver.dart:56:7)
#34     DefaultValueResolver.resolve (package:analyzer/src/summary2/default_value_resolver.dart:43:9)
#35     LibraryBuilder.resolveDefaultValues (package:analyzer/src/summary2/library_builder.dart:244:43)
#36     Linker._resolveDefaultValues (package:analyzer/src/summary2/link.dart:216:15)
#37     Linker._buildOutlines (package:analyzer/src/summary2/link.dart:97:5)
#38     Linker.link (package:analyzer/src/summary2/link.dart:76:5)
#39     link (package:analyzer/src/summary2/link.dart:32:10)
#40     LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:215:24)
#41     LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17)
#42     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#43     LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12)
#44     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:77:5)
#45     AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1538:27)
#46     _rootRun (dart:async/zone.dart:1190:13)
#47     _CustomZone.run (dart:async/zone.dart:1093:19)
#48     _runZoned (dart:async/zone.dart:1630:10)
#49     runZoned (dart:async/zone.dart:1550:10)
#50     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#51     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33)
#52     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1305:30)
#53     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#54     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1294:20)
#55     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1247:14)
#56     _rootRun (dart:async/zone.dart:1190:13)
#57     _CustomZone.run (dart:async/zone.dart:1093:19)
#58     _runZoned (dart:async/zone.dart:1630:10)
#59     runZoned (dart:async/zone.dart:1550:10)
#60     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#61     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1246:40)
#62     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1384:37)
#63     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:993:39)
<asynchronous suspension>
#64     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>
#65     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1936:5)
#66     new AnalysisServer (package:analysis_server/src/analysis_server.dart:151:29)
#67     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:82:22)
#68     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:32:18)
#69     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:623:37)
#70     _rootRun (dart:async/zone.dart:1190:13)
#71     _CustomZone.run (dart:async/zone.dart:1093:19)
#72     _runZoned (dart:async/zone.dart:1630:10)
#73     runZoned (dart:async/zone.dart:1550:10)
#74     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:742:12)
#75     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:619:14)
#76     Driver.start (package:analysis_server/src/server/driver.dart:507:7)
#77     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:11)
#78     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:309:32)
#79     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


#0      LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:329:5)
#1      LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:220:11)
#2      LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17)
#3      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#4      LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12)
#5      new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:77:5)
#6      AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1538:27)
#7      _rootRun (dart:async/zone.dart:1190:13)
#8      _CustomZone.run (dart:async/zone.dart:1093:19)
#9      _runZoned (dart:async/zone.dart:1630:10)
#10     runZoned (dart:async/zone.dart:1550:10)
#11     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#12     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33)
#13     AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1305:30)
#14     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#15     AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1294:20)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1247:14)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _runZoned (dart:async/zone.dart:1630:10)
#20     runZoned (dart:async/zone.dart:1550:10)
#21     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#22     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1246:40)
#23     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1384:37)
#24     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:993:39)
<asynchronous suspension>
#25     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>
#26     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1936:5)
#27     new AnalysisServer (package:analysis_server/src/analysis_server.dart:151:29)
#28     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:82:22)
#29     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:32:18)
#30     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:623:37)
#31     _rootRun (dart:async/zone.dart:1190:13)
#32     _CustomZone.run (dart:async/zone.dart:1093:19)
#33     _runZoned (dart:async/zone.dart:1630:10)
#34     runZoned (dart:async/zone.dart:1550:10)
#35     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:742:12)
#36     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:619:14)
#37     Driver.start (package:analysis_server/src/server/driver.dart:507:7)
#38     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:11)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:309:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:730:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:999:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

## Debug log

```
1604365539864 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/scrollbar.dart","errors":[]}}
1604365544544 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/widgets/scroll_metrics.dart","errors":[]}}
1604365568468 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/placeholder_span.dart","errors":[]}}
1604365568489 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/shape_decoration.dart","errors":[]}}
1604365568524 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/_network_image_web.dart","errors":[]}}
1604365568531 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/decoration.dart","errors":[]}}
1604365568549 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/text_span.dart","errors":[]}}
1604365568574 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/binding.dart","errors":[]}}
1604365568593 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/image_cache.dart","errors":[]}}
1604365568606 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/image_resolution.dart","errors":[]}}
1604365568627 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/decoration_image.dart","errors":[]}}
1604365568636 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/inline_span.dart","errors":[]}}
1604365568670 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/_network_image_io.dart","errors":[]}}
1604365568690 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/image_decoder.dart","errors":[]}}
1604365568718 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/box_decoration.dart","errors":[]}}
1604365568742 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/image_stream.dart","errors":[]}}
1604365568762 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/src/painting/flutter_logo.dart","errors":[]}}
1604365569033 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/rendering.dart","errors":[]}}
1604365569036 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/semantics.dart","errors":[]}}
1604365569038 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/animation.dart","errors":[]}}
1604365569041 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/scheduler.dart","errors":[]}}
1604365569706 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/services.dart","errors":[]}}
1604365569711 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter/lib/gestures.dart","errors":[]}}
1604365580321 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter_test/lib/src/test_vsync.dart","errors":[]}}
1604365580331 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter_test/lib/src/restoration.dart","errors":[]}}
1604365581483 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter_test/lib/src/event_simulation.dart","errors":[]}}
1604365581744 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter_test/lib/src/image.dart","errors":[]}}
1604365582072 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter_test/lib/src/test_pointer.dart","errors":[]}}
1604365583442 <= {"event":"analysis.errors","params":{"file":"/home/gspencer/code/flutter/packages/flutter_test/lib/src/platform_dispatcher.dart","errors":[]}}
1604365583444 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
```

**Comment by devoncarew** [comment] 2020-11-03 15:56
Thanks for the report! It looks like an issue restoring the information from a summary file. cc @scheglov

**Comment by srawlins** [comment] 2021-02-26 17:13
Thanks for reporting this. This was previously reported at https://github.com/dart-lang/sdk/issues/40128. Please follow along there.

**Comment by srawlins** [comment] 2021-02-26 17:13
Duplicate of https://github.com/dart-lang/sdk/issues/40128

**Closed by srawlins** 2021-02-26 17:13 UTC
Labels: P2, analyzer-crash-report, area-analyzer, type-bug
