### ISSUE TITLE
UTF-8 json data in IE (internet explorer) 

### ISSUE THREAD

**Issue by SadovovAlex** [dart-lang/sdk#29494] opened 2017-04-27 08:11 UTC
dart web app, i have a problem in IE 

**html code, header, charset=UTF-8, html file in UTF-8**

```
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Реестр участников - Копилка</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Cache-Control" content="max-age=300, must-revalidate" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
```

**dart code get from external json data string.
in header i set Content-Type: application/json; charset=utf-8**

**Network data send** 
`GET http://xxxxxxxx:8081/API/View?Stat=1 HTTP/1.1
Host: xxxxxxxxxxxxx:8081
Connection: keep-alive
Origin: http://localhost:63342
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.104 (Dart) Safari/537.36
Content-Type: application/json; charset=utf-8
Accept: */*
Referer: http://localhost:63342/KopilkaNextFE/DemoDart/web/index.html/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
`

**Get**
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: Kestrel
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:63342
X-Powered-By: ASP.NET
Date: Thu, 27 Apr 2017 06:30:41 GMT
Content-Length: 8943

[{"identity":8580,"fio":"Даренских Татья"}]
```

in Chrome and Firefox all ok
![image](https://cloud.githubusercontent.com/assets/14030285/25473671/079830e2-2b39-11e7-8544-146df67c5bb3.png)

But Internet explorer 11.0.9600 incorrectly show this text
![image](https://cloud.githubusercontent.com/assets/14030285/25472443/f142dd06-2b33-11e7-81d7-360181b493c1.png)

why is that?

PS sorry for my english

**Comment by rakudrama** [comment] 2017-05-11 04:51
This looks like an issue with the browser rather than the Dart libraries.
It looks like you are doing everything correctly.
Does the initial html page response also have charset=utf-8 ?

**Comment by SadovovAlex** [comment] 2017-05-17 09:42
only external json data incorrect char
![default](https://cloud.githubusercontent.com/assets/14030285/26148076/314f4b58-3afe-11e7-9732-b402c0cb31ec.png)

**Comment by stefantsov** [comment] 2017-05-17 12:18
I can't reproduce the issue right now, but a quick search shows some answers for similar issues. Namely, there are problems that some people are experiencing with string encodings in JSON responses in IE or Edge, but not with Firefox or Chrome. Here is an example: https://ru.stackoverflow.com/q/539875.

So, I guess it's not a Dart issue, but something with webserver / browser settings.

**Comment by Markzipan** [comment] 2021-11-16 23:07
Closing this since IE11 is no longer supported by our web targets.

**Closed by Markzipan** 2021-11-16 23:07 UTC
Labels: web-libraries, closed-obsolete, area-web
