### ISSUE TITLE
runtimeType is too expensive

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#49115] opened 2022-05-26 00:42 UTC
In https://github.com/dart-lang/sdk/issues/49113, @lrhn says:
> I'm strongly against comparing runtimeType in equals. It's expensive and it's too restrictive.
> You may actually want to have multiple subclasses that agree on equality. (Say CarthesianPoint and PolarPoint which are still equal if they point to the same position.) You may want to use mocks (which have a different runtimeType).
> Using runtimeType is a hack that works for some classes, but it's not general solution, and it's not a good solution.

Flutter currently uses `runtimeType` in `operator ==`s heavily in performance-critical code, since there appears to be no other option to get correctness currently when the class hierarchy is intended to be extended. If it is expensive, we should either make it less expensive or provide a better way to implement equality.

**Comment by rakudrama** [comment] 2022-05-26 06:08
AOT has an optimization that makes `a.runtimeType == b.runtimeType` more efficient: https://github.com/dart-lang/sdk/issues/48896#issuecomment-1110979841
AOT-VM is 8x-11x faster than JIT-VM according to the [`RuntimeType` benchmarks](https://github.com/dart-lang/sdk/blob/main/benchmarks/RuntimeType/dart/RuntimeType.dart) based on the use of `.runtimeType` in `Widget.canUpdate`two years ago when the benchmark was created.

Although the type representation in dart2js is completely different to the VM, dart2js could do something similar in spirit to the AOT optimization if necessary.

@Hixie Do the current optimizations of `.runtimeType` that target Flutter use patterns miss the mark? Can you provide concrete examples of where `.runtimeType` is materially too expensive?

**Comment by Hixie** [comment] 2022-05-26 06:20
I have no data here, I am basing this just on @lrhn's comments in #49113.

**Comment by lrhn** [comment] 2022-05-26 09:42
Optimizing away the allocations when comparing a `runtimeType` to another or to a type literal is a good trick. I'm sure it works best when no-one overrides `runtimeType`, and when the class is not generic.
I wouldn't *trust* it to be efficient, since we make no such promises anywhere, and do not state which things can make it deoptimize into allocating a `Type` object and calling `==` on it.

Maybe it is efficient, but I'm not sure how I'd know that, so I'd have to assume it's not. (Which I do. Please prove me wrong.)

**Comment by a-siva** [comment] 2022-05-27 17:13
//cc @alexmarkov

**Comment by mraleph** [comment] 2022-05-30 14:25
@Hixie we have optimized `a.runtimeType == b.runtimeType` for Flutter several years ago. (I did original optimization for back in Dart 1 times and Regis has expanded some of it few years ago). To the best of my knowledge `runtimeType` does not actually appear much on Flutter profiles anymore. 

@lrhn you should do the same benchmark in AOT mode. `a.runtimeType == b.runtimeType` pattern is not optimized in JIT ATM.

**Comment by mraleph** [comment] 2022-05-30 14:26
Duplicate of #48896

**Closed by mraleph** 2022-05-30 14:26 UTC
Labels: area-vm

**Comment by lrhn** [comment] 2022-05-30 15:35
Checked the benchmark in AoT mode:


| Name                    | this.runtimeType | Test                                                         |    JIT |    AOT |
| :---------------------- | :--------------- | :----------------------------------------------------------- | -----: | -----: |
| Plain                   | A                | <code>o is ThisType</code>                                   | 404790 | 355978 |
| Plain\<int\>            | G\<int\>         | <code>o is ThisType\<int\></code>                            | 138141 | 171199 |
| Plain\<BigType\>        | G\<BigType\>     | <code>o is ThisType\<BigType\></code>                        | 128196 | 160387 |
| Plain\<\>               | G\<int\>         | <code>o is ThisType\<dynamic\></code>                        | 440871 | 320151 |
| Rtt                     | A                | <code>ThisType = o.runtimeType &&<br> o is ThisType</code>   | 192016 | 219695 |
| Rtt\<int\>              | G\<int\>         | <code>ThisType\<int\> = o.runtimeType &&<br> o is ThisType\<int\></code> |   2188 |   2032 |
| Rtt\<BigType\>          | G\<BigType\>     | <code>ThisType\<BigType\> = o.runtimeType &&<br> o is ThisType\<BigType\></code> |   2144 |   1988 |
| Rtt\<\[int\]\>          | G\<int\>         | <code>ThisType\<int\> = o.runtimeType &&<br> o is ThisType\<dynamic\></code> |   2169 |   1762 |
| Rtt\<\[BigType\]\>      | G\<BigType\>     | <code>ThisType\<BigType\> = o.runtimeType &&<br> o is ThisType\<dynamic\></code> |   2077 |   2076 |
| this.Rtt                | A                | <code>this.runtimeType = o.runtimeType &&<br> o is ThisType</code> | 186338 | 207850 |
| this.Rtt\<int\>         | G\<int\>         | <code>this.runtimeType = o.runtimeType &&<br> o is ThisType\<int\></code> | 103529 |   1491 |
| this.Rtt\<BigType\>     | G\<BigType\>     | <code>this.runtimeType = o.runtimeType &&<br> o is ThisType\<BigType\></code> |  98785 |   1694 |
| this.Rtt\<\[int\]\>     | G\<int\>         | <code>this.runtimeType = o.runtimeType &&<br> o is ThisType\<dynamic\></code> | 144031 |   1408 |
| this.Rtt\<\[BigType\]\> | G\<BigType\>     | <code>this.runtimeType = o.runtimeType &&<br> o is ThisType\<dynamic\></code> | 145051 |   1681 |

It is much faster at doing `this.runtimeType == other.runtimeType` than it is at doing `TheType<T> == other.runtimeType`. That's good to know, but not something I'd ever have guessed myself. If anything, comparing to a constant seems like the more optimizable thing to do.
(I guess you could represent a comparison to a type literal in a way that hooks into the faster comparison of type arguments after checking the outer type's class-ID, and get faster at that too?)

**Comment by mraleph** [comment] 2022-05-31 06:37
> I guess you could represent a comparison to a type literal in a way that hooks into the faster comparison of type arguments after checking the outer type's class-ID, and get faster at that too?

Yep, we can do that.
