### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by vladimirdjokic76** [dart-lang/sdk#38714] opened 2019-10-04 07:30 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/vladimirdjokic/Documents/projects/Android/sports_betting_app/lib/data/dto.g.dart context: exception_20191004_091750_314
NoSuchMethodError: The getter 'kind' was called on null.
Receiver: null
Tried calling: kind
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member.kind (package:analyzer/src/dart/element/member.dart:475:40)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:466:40)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:452:7)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:752:7)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8969:49)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6629:13)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:396:31)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6625:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7428:12)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#12     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#13     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#14     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:618:11)
#15     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#16     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7424:49)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#19     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#20     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#21     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#22     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:669:24)
#23     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7233:49)
#24     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3585:18)
#25     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#26     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#27     GeneralizingAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:268:7)
#28     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:3581:15)
#29     ConstructorDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2634:12)
#30     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#31     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#32     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#33     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:183:43)
#34     GeneralizingAstVisitor.visitConstructorDeclaration (package:analyzer/dart/ast/visitor.dart:213:7)
#35     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2624:15)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#37     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#38     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#39     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:134:47)
#40     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:227:43)
#41     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:202:7)
#42     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:427:7)
#43     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:181:7)
#44     _IndexContributor.visitClassDeclaration (package:analyzer/src/dart/analysis/index.dart:566:11)
#45     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#46     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#47     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#48     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#49     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:199:51)
#50     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#51     _IndexAssembler.assemble (package:analyzer/src/dart/analysis/index...
```

For additional log information, please append the contents of
file:///private/var/folders/bp/70836ksx70704lzkfsp_w9g00000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-10-15 04:41
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38488; please follow along there.

**Comment by srawlins** [comment] 2019-10-15 04:41
Duplicate of https://github.com/dart-lang/sdk/issues/38488

**Closed by srawlins** 2019-10-15 04:41 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
