### ISSUE TITLE
VM crash on angular analyzer when using --observe

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#29163] opened 2017-03-24 18:00 UTC
Just built the latest internal sdk with my analysis added, and got this crash. Confirmed it didn't crash without my code, and I have a theory what the difference there is.

But also turned of debugging, since that's where the failure lies, and then got no further issues.

Is it possible this is related to having a lot of pending async operations? One of the reasons I was firing it up was to check if it created a lot of async ops in the queue.

```
Dumping native stack trace for thread 6f99
  [0x00000000006f9ef0] dart::ActivationFrame::GetContextVar(long, long)
  [0x00000000006f9ef0] dart::ActivationFrame::GetContextVar(long, long)
  [0x00000000006f9d58] dart::ActivationFrame::GetAsyncContextVariable(dart::String const&)
  [0x00000000006fa5f4] dart::ActivationFrame::GetAsyncAwaiter()
  [0x00000000006fefa7] dart::Debugger::CollectAwaiterReturnStackTrace()
  [0x00000000006ff7a2] dart::Debugger::PauseException(dart::Instance const&)
  [0x0000000000713caa] dart::Exceptions::Throw(dart::Thread*, dart::Instance const&)
  [0x00000000006cfc06] dart::DRT_Throw(dart::NativeArguments)
  [0x00007fef61d4061b] [Stub] CallToRuntime
  [0x00007fef2c959c42] _File.openSync
  [0x00007fef2c960796] _File.readAsBytesSync
  [0x00007fef271747ba] _PhysicalFile.readAsStringSync
  [0x00007fef27167a7d] FileState.refresh
  [0x00007fef2716c1e7] FileSystemState.getFileForUri
  [0x00007fef2716d68e] FileState._fileForRelativeUri
  [0x00007fef2716972f] FileState.refresh
  [0x00007fef2716c1e7] FileSystemState.getFileForUri
  [0x00007fef2716d68e] FileState._fileForRelativeUri
  [0x00007fef2716a581] FileState.refresh
  [0x00007fef2716c1e7] FileSystemState.getFileForUri
  [0x00007fef2716d68e] FileState._fileForRelativeUri
  [0x00007fef2716a581] FileState.refresh
  [0x00007fef2716c1e7] FileSystemState.getFileForUri
  [0x00007fef2716d68e] FileState._fileForRelativeUri
  [0x00007fef2716a581] FileState.refresh
  [0x00007fef2716c1e7] FileSystemState.getFileForUri
  [0x00007fef2716d68e] FileState._fileForRelativeUri
  [0x00007fef2716a581] FileState.refresh
  [0x00007fef2716c1e7] FileSystemState.getFileForUri
  [0x00007fef2716d68e] FileState._fileForRelativeUri
  [0x00007fef2716a581] FileState.refresh
  [0x00007fef5e9b1009] FileSystemState.getFileForPath
  [0x00007fef5e9b05cd] AnalysisDriver._computeAnalysisResult
  [0x00007fef2717d6e2] AnalysisDriver.performWork
  [0x00007fef5fa1f29a] _Closure.call
  [0x00007fef5f3137dd] Future.Future.microtask.<anonymous closure>
  [0x00007fef5e990d50] _rootRun
  [0x00007fef5e990acc] _rootRun
  [0x00007fef5e9924fd] _CustomZone.runGuarded
  [0x00007fef5e990ba2] _CustomZone.bindCallback.<anonymous closure>
  [0x00007fef5e990cdd] _rootRun
  [0x00007fef5e990acc] _rootRun
  [0x00007fef5e9924fd] _CustomZone.runGuarded
  [0x00007fef5e990ba2] _CustomZone.bindCallback.<anonymous closure>
  [0x00007fef27176672] _microtaskLoop
  [0x00007fef5f3130a0] _startMicrotaskLoop
  [0x00007fef5f312f74] _startMicrotaskLoop
  [0x00007fef2716dcae] _Timer._runTimers
  [0x00007fef27170d76] _Timer._handleMessage
  [0x00007fef2716f2f8] _RawReceivePortImpl._handleMessage
  [0x00007fef61d409d9] [Stub] InvokeDartCode
  [0x00000000006f26ff] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  [0x00000000006f5bed] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x00000000007c9e54] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x00000000008347bd] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x0000000000834bfd] dart::MessageHandler::TaskCallback()
```

Can provide the busted build as well in .deb format upon request

**Comment by mraleph** [comment] 2017-03-24 19:54
This is a duplicate of #29080. Essentially it's a bug in the debugger which did not properly account for optimized frames when collecting async stack trace.

**Closed by mraleph** 2017-03-24 19:54 UTC

**Comment by MichaelRFairhurst** [comment] 2017-03-24 20:15
Thanks Slava!
