### ISSUE TITLE
dartanalyzer does not honor generic methods in strong mode without seemingly superfluous 'await'

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/sdk#26931] opened 2016-07-21 00:20 UTC
Use `dartanalyzer --strong` on the following

```dart
var confuse;
Future/*<T>*/ genericMethod/*<T>*/() async => confuse as dynamic/*=T*/;

Future<int> hasNoError() async => await genericMethod();  // Apparently this is ok.
Future<int> hasError() async => genericMethod();  // "Unsound implicit
  // cast from Future<dynamic> to Future<int>"
  // Wtf?  Just because I didn't add the superfluous 'await'?
```

**Comment by bwilkerson** [comment] 2016-07-21 13:17
@leafpetersen @jmesserly

**Comment by jmesserly** [comment] 2016-07-21 13:25
Hi @trinarytree -- what is going on here is type inference couldn't figure this one out. Type inference is not perfect for Future because Future often implies a `Future<T> | T` union type, and we have no way of writing that in Dart. So the current inference system makes an arbitrary choice.

You can fix your code like this:
```dart
Future<int> hasError() async => genericMethod/*<int>*/();
```

in other words, explicitly pass the type argument, that way you don't have to rely on type inference.

There's two bugs currently assigned to me to fix inference: https://github.com/dart-lang/sdk/issues/25322 and https://github.com/dart-lang/sdk/issues/25944. I have a CL that actually does fix them, by introducing that union type as part of the type inference system. Unfortunately I haven't finished the CL yet. It needs a lot of care to make sure those union types don't escape outside the inference, as the boundary is not very clear right now in Analyzer.

I will try to get to this soon, but to keep our tracking simple, I'm going to mark this duplicate of #25322. I'll CC you over there.

**Closed by jmesserly** 2016-07-21 13:25 UTC
Labels: analyzer-strong-mode, area-analyzer, P1 high, Type: bug
