### ISSUE TITLE
NPE on iterator in _protocolAvailableSuggestionSet

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#38149] opened 2019-08-30 21:25 UTC
Analyzer Feedback from IntelliJ

Possibly a dupe of a previous one. Just dumping it here before I forget. This happened when a source_gen builder was building some source _while_ the analyzer was probably trying to analyze it.

## Version information

- `IDEA WS-192.6262.59`
- `2.4.1`
- `WS-192.6262.59, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2048x1152, 1680x1050`

## Exception
```
Dart analysis server, SDK version 2.4.1, server version 1.27.1, error: Captured exception
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:227:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:78:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:79:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:497:11)
#7      new DeclarationsTrackerData.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:300:9)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#15     _rootRun (dart:async/zone.dart:1120:38)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/np/gmysjh1j2159hv7wssjzrw440028jd/T/report.txt.

Dart analysis server, SDK version 2.4.1, server version 1.27.1, error: Captured exception
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _protocolAvailableSuggestionSet (package:analysis_server/src/domains/completion/available_suggestions.dart:227:35)
#2      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:78:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:79:8)
#6      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:497:11)
#7      new DeclarationsTrackerData.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:300:9)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#15     _rootRun (dart:async/zone.dart:1120:38)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
1567200182954 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/history/visit_history.g.dart","errors":[]}}
1567200182954 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/egamebook/edgehead/lib/src/fight/fight_situation.g.dart","errors":[]}}
1567200182954 <= {"event":"analysis.errors","params":{"file":"/Users/filiph/dev/egamebook/edgehead/lib/src/fight/common/attacker_situation.g.dart","errors":[]}}
1567200182954 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1567200184600 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/edgehead_global.g.dart"]}}
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/world_state.g.dart"]}}
1567200184602 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1567200184602 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":583,"uri":"package:edgehead/edgehead_global.dart","items":[{"label":"EdgeheadGlobalState","declaringLibr
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/edgehead_serializers.g.dart"]}}
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/actor.g.dart"]}}
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/history/action_history.g.dart"]}}
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/items/inventory.g.dart"]}}
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/room_roaming/room_roaming_situation.g.dart"]}}
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/off_balance_opportunity/off_balance_opportunity_situation.g.dart"]}}
1567200184602 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/loot/loot_situation.g.dart"]}}
1567200184603 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/history/custom_event_history.g.dart"]}}
1567200184603 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/common/defense_situation.g.dart"]}}
1567200184603 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/counter_attack/counter_attack_situation.g.dart"]}}
1567200184603 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/fight_situation.g.dart"]}}
1567200184603 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/fractal_stories/history/visit_history.g.dart"]}}
1567200184603 <= {"event":"analysis.flushResults","params":{"files":["/Users/filiph/dev/egamebook/edgehead/lib/src/fight/common/attacker_situation.g.dart"]}}
1567200184607 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":397,"uri":"package:edgehead/src/fight/common/attacker_situation.dart","items":[{"label":"MoveEntity","de
1567200184607 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":524,"uri":"package:edgehead/fractal_stories/history/visit_history.dart","items":[{"label":"VisitRecord",
1567200184607 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":329,"uri":"package:edgehead/src/fight/fight_situation.dart","items":[{"label":"getGroundMaterial","decla
1567200184607 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":413,"uri":"package:edgehead/src/fight/counter_attack/counter_attack_situation.dart","items":[{"label":"C
1567200184607 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":401,"uri":"package:edgehead/src/fight/common/defense_situation.dart","items":[{"label":"DefenseSituation
1567200184608 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":527,"uri":"package:edgehead/fractal_stories/history/custom_event_history.dart","items":[{"label":"Custom
1567200184608 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":427,"uri":"package:edgehead/src/fight/loot/loot_situation.dart","items":[{"label":"LootSituation","decla
1567200184608 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":431,"uri":"package:edgehead/src/fight/off_balance_opportunity/off_balance_opportunity_situation.dart","i
1567200184616 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The getter 'iterator' was called on null.\nReceiver: null\nTried call
```

**Comment by srawlins** [comment] 2019-11-04 16:09
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38014; please follow along there.

**Comment by srawlins** [comment] 2019-11-04 16:10
Duplicate of https://github.com/dart-lang/sdk/issues/38014

**Closed by srawlins** 2019-11-04 16:10 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
