### ISSUE TITLE
Double slashes in a relative paths are not canonicalized  correctly

### ISSUE THREAD

**Issue by grouma** [dart-lang/sdk#36422] opened 2019-04-01 22:02 UTC
I had a typo in my relative import in which I had a double slash, e.g.:

`import '../serve//data/run_request.dart';`

This caused a very cryptic runtime (VM) error:

``` 
type '_$RunRequest' is not a subtype of type 'RunRequest' of 'object'
#0      _$RunRequestSerializer.serialize (file:///usr/local/google/home/grouma/Projects/webdev/webdev/lib/src/serve/data/run_request.g.dart)
```

There were no errors in my IDE as the analysis plugin correctly recognized that `_$RunRequest` imported with a double slash was indeed a `RunRequest`.

The fix was to remove the double slash but that was a massive pain to track down given that this code is partly generated.

I thought relative import paths are canonicalized to prevent this issue. Is this not the case, or is this a bug with that code?

**Comment by kevmoo** [comment] 2019-04-03 21:22
Not sure who would handle this.

@mraleph @a-siva @kmillikin ?

**Comment by mraleph** [comment] 2019-04-04 08:49
Duplicate of #36337

**Closed by mraleph** 2019-04-04 08:49 UTC
Labels: area-front-end, area-vm
