### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#43749] opened 2020-10-09 23:12 UTC
Could not load edit details

Error: FormatException: SyntaxError: Unexpected token < in JSON at position 0

Please fill in the following:

**Name of package being migrated (if public)**: win32
**What I was doing when this issue occurred**: updating entries after migrate tool had inserted @required into my code
**Is it possible to work around this issue**:
**Has this issue happened before, and if so, how often**: no
**Dart SDK version**: 2.11.0-203.0.dev
**Additional details**:
Clicked on `required` here:
![image](https://user-images.githubusercontent.com/2319867/95638709-744d1b00-0a4a-11eb-86d0-34b71fdd8fd0.png)

Stacktrace: _auto populated by migration preview tool._

```
FormatException: SyntaxError: Unexpected token < in JSON at position 0
    at Object.b (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:303:3)
    at Object.BS (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:1877:9)
    at by.pW (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:5102:5)
    at http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:3144:15
    at Gs.a (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:1550:72)
    at Gs.$2 (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:4516:23)
    at WM.$1 (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:4508:30)
    at Ji.bv (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:4781:25)
    at rq.$0 (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:4709:11)
    at Object.HZ (http://127.0.0.1:59406/Users/timsneath/git/me/win32/test/wincreds_test.dart?offset=258&line=12&authToken=2IriOlO32p0%3D:1598:39)
```

**Comment by srawlins** [comment] 2020-10-30 16:35
I'll do my darn'dest to mail something today.

**Comment by srawlins** [comment] 2020-10-30 16:53
I cannot reproduce this after fixing https://github.com/dart-lang/sdk/issues/43751. I'll close this for now, and if we can reproduce another way, then it would still be a high priority bug.

**Closed by srawlins** 2020-10-30 16:53 UTC
Labels: P1, analyzer-nnbd-migration, area-analyzer, type-bug

**Comment by mzdm** [comment] 2021-03-11 18:08
I forked this package https://github.com/DirectMyFile/console.dart and got the same warning.

![image](https://user-images.githubusercontent.com/67197047/110833725-0b89f900-829d-11eb-9979-17b0d34f5177.png)

**Comment by srawlins** [comment] 2021-03-11 18:14
@mzdm can you give some details?

* What did you click on?
* What commit of console.dart are you looking at?
* What version of Dart are you running?

**Comment by mzdm** [comment] 2021-03-11 18:17
1) I changed the version in pubspec.yaml from 2.12.0 to 2.10.0) and ran `dart migrate` command. Then this pop-up appeared, however does not block from looking at migration changes (can be just closed)
2) It's the latest master branch so https://github.com/DirectMyFile/console.dart/commit/9d75fd4457831075c746c27bc3a2bbbc504ef4db
3) Dart version: 2.13.0-77.0.dev
```
FormatException: SyntaxError: Unexpected token < in JSON at position 0
    at Object.b (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:311:3)
    at Object.BS (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:1898:9)
    at by.pW (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:5247:5)
    at http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:3138:15
    at Gs.a (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:1572:72)
    at Gs.$2 (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:4670:23)
    at WM.$1 (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:4662:30)
    at Ji.bv (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:4937:25)
    at rq.$0 (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:4865:11)
    at Object.HZ (http://127.0.0.1:54981/C:/Users/matej/FlutterProjects/forked/console.dart?authToken=rWGfanTo2-0%3D:1620:39)
```

**Comment by srawlins** [comment] 2021-03-11 18:24
Sorry I cannot reproduce this. :(

1. checkout DirectMyFile/console.dart@9d75fd4.
2. `pub get`
3. change `sdk: '>=2.12.0 <3.0.0'` to `sdk: '>=2.10.0 <3.0.0'` (By the way this is not a good idea.)
4. (do not run pub get again?)
5. dart migrate
6. load the URL printed in Chrome.
7. The website loads OK.

**Comment by mzdm** [comment] 2021-03-11 18:42
Just tried it again and it shows every time on my machine 😃. But I guess it is not a big deal because it seems like it is just a warning (or?)

**Comment by dutsky** [comment] 2022-03-19 21:35
I have same issue. This will happen every time if you have package name(and project directory name) like `something.dart`(with `.dart` in name).
If you rename(or clone) it to `something_dart` this error will not appear.

**Comment by srawlins** [comment] 2022-03-19 22:55
Since this issue has been closed for 18 months, please open a new issue, @dutsky if you are seeing this bug on a recent version of Dart, like 2.16.0, with steps to reproduce. (Maybe having a directory named `foo.dart` is all you need, just make sure to include that).
