### ISSUE TITLE
Checked exceptions

### ISSUE THREAD

**Issue by yichaosun** [dart-lang/sdk#52545] opened 2023-05-29 04:33 UTC
### Change Intent

CheckException can force engineer to handle exception,

### Justification

I worked with C++, Java, and finally, found that check Exception is necessary and more engineering

### Impact

to make programs more strong，no exception throw without handle

### Mitigation

likee no empty check, the programmer must  handle exist exception ,and even use throws key word

**Comment by lrhn** [comment] 2023-05-29 17:04
This is a duplicate of https://github.com/dart-lang/language/issues/984
There are currently no plans to add checked exceptions to Dart, and not current plans to change that.

**Closed by lrhn** 2023-05-29 17:04 UTC
