### ISSUE TITLE
dart2js cannot compile method named `get` with generics

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#31091] opened 2017-10-12 18:56 UTC
dart2js can compile a method named `get` with _comment-based_ generics but **cannot** with real generics:

```dart
class A {
  Future/*<T>*/ get/*<T>*/(var /*=T*/ arg) {
    return new Future.value(arg);
  }
}

class B {
  // Analyzer doesn't complain about this method named `get` that
  // uses generics. But just try to run this with dart2js!
  Future<T> get<T>(T arg) {
    return new Future.value(arg);
  }
}
```

([dartpad](https://dartpad.dartlang.org/8d84342d92245e0e60c31060e64deb91))

**Comment by kevmoo** [comment] 2017-10-12 20:49
CC @sigmundch

**Comment by sigmundch** [comment] 2017-10-12 22:09
marking as duplicate of https://github.com/dart-lang/sdk/issues/29349

**Closed by sigmundch** 2017-10-12 22:09 UTC
Labels: area-dart2js, S1 high, Type: bug
