### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by Arefalhaj** [dart-lang/sdk#38399] opened 2019-09-15 08:10 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA WS-192.6603.19`
- `2.5.0`
- `WS-192.6603.19, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0, server version 1.27.2, error: Could not initialize the library map from [E:\android\sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart, E:\android\sdk\lib\_internal\libraries.dart]

FileSystemException(path=E:\android\sdk\lib\_internal\libraries.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:623:41)
#3      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:493:18)
#4      ContextBuilder.findSdk.<anonymous closure> (package:analyzer/src/context/builder.dart:411:36)
#5      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
#6      DartSdkManager.getSdk (package:analyzer/src/generated/sdk.dart:146:19)
#7      ContextBuilder.findSdk (package:analyzer/src/context/builder.dart:410:23)
#8      ContextBuilder.createSourceFactory (package:analyzer/src/context/builder.dart:288:19)
#9      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:185:16)
#10     ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:776:48)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1154:19)

**Comment by srawlins** [comment] 2019-09-16 17:31
Thanks for reporting this issue! This was previously reported at #38157; please follow along there.

**Comment by srawlins** [comment] 2019-09-16 17:31
Duplicate of #38157

**Closed by srawlins** 2019-09-16 17:31 UTC
