### ISSUE TITLE
Debugger Crash : Invalid argument(s): Iterables do not have same length.

### ISSUE THREAD

**Issue by bahadirarslan** [dart-lang/sdk#53960] opened 2023-11-05 14:44 UTC
I am having an interesting issue with debugger. 
When I want to evaluate a value of a variable, debugger and application crash.

Here is the stack trace
```
Unhandled exception:
Invalid argument(s): Iterables do not have same length.
#0      MapBase._fillMapWithIterables (dart:collection/maps.dart:178:7)
#1      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:246:13)
#2      Substitution.fromPairs (package:kernel/type_algebra.dart:263:13)
#3      InferenceVisitorBase.getGetterTypeForMemberTarget (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1465:35)
#4      InstanceAccessTarget.getGetterType (package:front_end/src/fasta/type_inference/object_access_target.dart:489:30)
#5      InferenceVisitorImpl._computePropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:6663:36)
#6      InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7672:61)
#7      PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:2984:20)
#8      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:257:27)
#9      InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:291:40)
#10     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7894:11)
#11     ReturnStatement.accept (package:kernel/ast.dart:10127:43)
#12     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:242:26)
#13     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:198:17)
#14     BodyBuilder.parseSingleExpression (package:front_end/src/fasta/kernel/body_builder.dart:1780:62)
#15     SourceLoader.buildExpression (package:front_end/src/fasta/source/source_loader.dart:1320:21)
<asynchronous suspension>
#16     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2033:39)
<asynchronous suspension>
#17     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1853:12)
<asynchronous suspension>
#18     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:981:28)
<asynchronous suspension>
#19     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1452:11)
<asynchronous suspension>

2
the Dart compiler exited unexpectedly.
```

I couldn't provide a sample for now because I couldn't see the data cause this problem.

```dart info``` result
```

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.1.4 (stable) (Tue Oct 17 14:55:53 2023 +0000) on "macos_arm64"
- on macos / Version 14.0 (Build 23A344)
- locale is en-TR

#### Project info

- sdk constraint: '>=3.0.0 <3.13.1'
- dependencies: about, advanced_in_app_review, appinio_video_player, appmetrica_plugin, avatar_glow, awesome_dialog, badges, bulleted_list, cached_network_image, collection, countup, crypto, cupertino_icons, currency_text_input_formatter, desktop_window, device_info_plus, dio, dynamic_color, easy_image_viewer, email_validator, encrypt, event, eventsubscriber, excel, external_app_launcher, facebook_app_events, feature_notifier, file_picker, firebase_analytics, firebase_core, firebase_crashlytics, firebase_messaging, fl_chart, flutter, flutter_app_badger, flutter_font_icons, flutter_hooks, flutter_initicon, flutter_local_notifications, flutter_localizations, flutter_map, flutter_pw_validator, flutter_secure_storage, flutter_spinkit, flutter_svg, flutter_typeahead, font_awesome_flutter, freezed_annotation, get_it, getwidget, go_router, google_maps_flutter, google_mlkit_text_recognition, google_sign_in, googleapis, grouped_list, http, image_gallery_saver, image_picker, in_app_purchase, internet_connection_checker, intl, introduction_screen, jeodezi, json_annotation, just_the_tooltip, keyboard_actions, label_marker, latlong2, line_animator, loader_overlay, logging, map_launcher, mask_text_input_formatter, material_color_utilities, network_info_plus, objectbox, objectbox_flutter_libs, open_filex, package_info_plus, page_view_indicators, path, path_provider, pretty_dio_logger, provider, reflectable, settings_ui, share_plus, shared_preferences, shimmer, sign_in_button, sign_in_with_apple, smooth_page_indicator, solar_calculator, stop_watch_timer, store_redirect, swipe_refresh, syncfusion_flutter_charts, syncfusion_flutter_datagrid, syncfusion_flutter_datagrid_export, syncfusion_flutter_gauges, syncfusion_flutter_xlsio, tab_container, tuple, url_launcher, uuid
- dev_dependencies: build_runner, build_test, dependency_validator, flutter_launcher_icons, flutter_lints, flutter_native_splash, flutter_test, icons_launcher, json_serializable, objectbox_generator, test
- elided dependencies: 2

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|   9 MB | 0.0% |  02-16:58:12 | dart devtools --machine --try-ports 10 --allow-embedding                        |
|  13 MB | 0.0% |  02-16:58:12 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.76.1 |
|  25 MB | 0.1% |  02-16:58:12 | flutter_tools.snapshot daemon                                                   |
```

**Comment by johnniwinther** [comment] 2023-11-06 11:20
Duplicate of https://github.com/dart-lang/sdk/issues/53453.  The fix will be available in 3.2.

**Closed by johnniwinther** 2023-11-06 11:20 UTC
Labels: type-bug, front-end-fasta, area-front-end
