### ISSUE TITLE
TFA metadata for `_Closure.get:call` indicates there might be no dynamic callers even though there are

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#42719] opened 2020-07-16 09:23 UTC
For this example:
```dart
final dynamic closure = () => print('Closure called');

class Callable {
  void call() => print('Callable called');
}

final value = int.parse('1') == 1 ? closure : Callable();

// Either one of those:
main() => value();
main() => (value.call)();
```
TFA emits:
```dart
class Callable extends core::Object {
  [@vm.procedure-attributes.metadata=getterCalledDynamically:false,hasTearOffUses:false,...]
  method call() → void { return core::print("Callable called"); }
}

class _Closure extends core::Object implements core::Function { // from org-dartlang-sdk:///sdk/lib/_internal/vm/lib/function.dart
  [@vm.procedure-attributes.metadata=getterCalledDynamically:false,hasTearOffUses:false,...]
  get call() → core::_Closure { return this; }
}

static method main() → dynamic
  return [@vm.call-site-attributes.metadata=receiverType:dynamic] fo::value.call();
```

This indicates that there are no dynamic callers or tear off usages, but there are. (Also if we don't generate the right invocation dispatchers, calls will go to runtime which will then invoke getter + closure call)

/cc @alexmarkov

**Comment by alexmarkov** [comment] 2020-07-22 19:04
Procedure attributes metadata has separate bits for method/setter and for getter calls.
When procedure attributes metadata is printed, only useful bits are included (like `getterCalledDynamically:false` which means analysis inferred that getter is not called dynamically). If particular bit is not printed, it means that particular information was not inferred (printing all bits is too verbose). 

The first variant of this example

```dart
main() => value();
```

is desugared to `value.call()`. There is a dynamic _method_ call, but no tear-off usages or dynamic _getter_ calls, so `getterCalledDynamically:false` attribute is correctly inferred and printed.

The second variant

```dart
main() => (value.call)();
```

is desugared to `value.call.call()`, so there is a dynamic getter call and there are no `getterCalledDynamically:false` attributes inferred.

In both variants of this example, `methodOrSetterCalledDynamically:false` was not printed, which means that it was inferred that there are dynamic calls of these members as methods.

I think this is working as intended, so I'm tentatively closing this issue. Please reopen it and explain in more details what's wrong if I'm missing something.

**Closed by alexmarkov** 2020-07-22 19:04 UTC
Labels: area-vm, tfa
