### ISSUE TITLE
Exception in angular plugin

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#30366] opened 2017-08-08 15:44 UTC
```
NoSuchMethodError: The getter 'typeParameters' was called on null.
Receiver: null
Tried calling: typeParameters
#0      Driver._captureExceptions.anonymous closure (package:analysis_server/src/server/driver.dart:462)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#2      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#3      _Future._completeError (dart:async/future_impl.dart:486)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
#5      _Completer.completeError (dart:async/future_impl.dart:27)
#6      DirectiveLinker.resynthesizeDirectives (package:angular_analyzer_plugin/src/directive_linking.dart:143)
#7      _asyncThenWrapperHelper.anonymous closure (dart:async-patch/async_patch.dart:30)
#8      _rootRunUnary (dart:async/zone.dart:1128)
#9      _CustomZone.runUnary (dart:async/zone.dart:1012)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#13     _Future._complete (dart:async/future_impl.dart:468)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#16     AngularDriver.getUnit (package:angular_analyzer_plugin/src/angular_driver.dart:696)
#17     _asyncThenWrapperHelper.anonymous closure (dart:async-patch/async_patch.dart:30)
#18     _rootRunUnary (dart:async/zone.dart:1128)
#19     _CustomZone.runUnary (dart:async/zone.dart:1012)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#21     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#22     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#23     _Future._completeWithValue (dart:async/future_impl.dart:478)
#24     _Future._asyncComplete.anonymous closure (dart:async/future_impl.dart:510)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     _CustomZone.runGuarded (dart:async/zone.dart:901)
#28     _CustomZone.bindCallback.\u003canonymous closure\u003e (dart:async/zone.dart:926)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

asynchronous suspension

#34     AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:237)

asynchronous suspension

#35     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1609)

asynchronous suspension

#36     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1552)
#37     new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#38     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#39     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#40     Driver.start.anonymous closure
 (package:analysis_server/src/server/driver.dart:434)
#41     _rootRun (dart:async/zone.dart:1120)
#42     _CustomZone.run (dart:async/zone.dart:1001)
#43     runZoned (dart:async/zone.dart:1467)
#44     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#45     Driver.start (package:analysis_server/src/server/driver.dart:433)

asynchronous suspension

#47     _startIsolate.\u003canonymous closure\u003e (dart:isolate-patch/isolate_patch.dart:263)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by MichaelRFairhurst** [comment] 2017-08-08 16:28
Duplicate of #30364

**Closed by MichaelRFairhurst** 2017-08-08 16:28 UTC
Labels: area-analyzer, P2 medium, Type: bug
