### ISSUE TITLE
Strong mode analyzer incorrectly infers return type of ??=

### ISSUE THREAD

**Issue by charliereams** [dart-lang/sdk#26023] opened 2016-03-17 12:30 UTC
The following code should be strong-mode compliant:

```dart
class X {}

UnmodifiableListView<X> a = new UnmodifiableListView<X>([]);
Iterable<X> b = null;
Iterable<X> c = (b ??= a);
```

but the analyzer actually produces the error:

`#Unsound implicit cast from Object to Iterable<X> [STRONG_MODE_DOWN_CAST_COMPOSITE]`

Note that this very similar (and functionally equivalent) code works fine:
```dart
class X {}

List<X> a = new UnmodifiableListView<X>([]);
Iterable<X> b = null;
Iterable<X> c = (b ??= a);
```

so it seems it's specifically having trouble working out the common subtype of Iterable<X> and UnmodifiableListView<X>. Maybe mix-in related?

**Comment by leafpetersen** [comment] 2016-03-17 16:39
I believe that this is an instance of this:

https://github.com/dart-lang/sdk/issues/25821

We are currently using the spec mode LUB, which is not very useful:

**Comment by leafpetersen** [comment] 2016-03-17 16:40
For discussion of spec mode LUB see:

https://github.com/dart-lang/sdk/issues/19282
https://github.com/dart-lang/sdk/issues/19425

**Comment by leafpetersen** [comment] 2016-03-17 16:41
Closing as duplicate of #25821 and https://github.com/dart-lang/sdk/issues/25802 , please re-open if you think something else is going on.

**Closed by leafpetersen** 2016-03-17 16:41 UTC
Labels: analyzer-strong-mode, area-analyzer
