### ISSUE TITLE
Endless Loop when overriding getters and setters

### ISSUE THREAD

**Issue by jomasoares** [dart-lang/sdk#50809] opened 2022-12-21 02:49 UTC
**Dart SDK Version:** 2.18.5

Overriding getters and setters from either public or private fields generate endless loop. 

```dart
class ParentClass {
  String name;

  ParentClass({
    required this.name,
  });
}

class ChildClass extends ParentClass {
  ChildClass({required super.name});

  @override
  set name(String name) {
    this.name = name;
  }

  @override
  get name => name;
}

main() {
  ChildClass s = ChildClass(name: "str");

  print(s.name); //endless loop here

  s.name = "new str"; //endless loop here too
}
```

**Comment by water-mizuu** [comment] 2022-12-21 05:31
Yes, you're overriding the property of `ParentClass` with the getter and setters. If you want to explicitly call the `name` property of `ParentClass`, you should invoke `super.name` in both the getter and setter.

```dart

class ParentClass {
  String name;

  ParentClass({
    required this.name,
  });
}

class ChildClass extends ParentClass {
  ChildClass({required super.name});

  @override
  void set name(String name) {
    super.name = name;
  }

  @override
  String get name => super.name;
}

void main() {
  var child = ChildClass(name: "name");
  child.name = "John";
  print(child.name); // John
}
```

**Comment by eernstg** [comment] 2022-12-21 10:24
Yes, exactly!

I'll close this issue because it is all working as intended.

**Closed by eernstg** 2022-12-21 10:24 UTC

**Comment by jomasoares** [comment] 2022-12-21 16:33
wow, nice. Thanks!
