### ISSUE TITLE
Internal Error: The compiler crashed when compiling this element

### ISSUE THREAD

**Issue by Bluenuance** [dart-lang/sdk#34622] opened 2018-09-30 17:17 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include:

* Dart SDK Version (`dart --version`)
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "windows_x64"
* Whether you are using Windows, MacOSX, or Linux (if applicable)
Windows
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
-

```
The compiler crashed: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libgrowable_array.dart:141:60)
#1      TypeVariableType.subst (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/elements/types.dart:399:23)
#2      _substTypes.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/elements/types.dart:872:30)
#3      new List.generate (dart:core/list.dart:162:28)
#4      _substTypes (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/elements/types.dart:870:11)
#5      InterfaceType.subst (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/elements/types.dart:200:9)
#6      KernelToElementMapBase._substByContext (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:506:17)
#7      KernelEvaluationEnvironment.substByContext (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1978:24)
#8      GenerativeConstantConstructor.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/constants/constructors.dart:81:24)
#9      ConstructedConstantExpression.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:575:10)
#10     RedirectingGenerativeConstantConstructor.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/constants/constructors.dart:191:35)
#11     ConstructedConstantExpression.computeInstanceType (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:575:10)
#12     ConstructedConstantExpression.evaluate (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/constants/expressions.dart:586:34)
#13     KernelConstantEnvironment._getConstantValue.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1951:25)
#14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
#15     KernelConstantEnvironment._getConstantValue (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:1950:22)
#16     KernelToElementMapBase.computeConstantValue (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:501:33)
#17     KernelToElementMapBaseMixin.getConstantValue (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_mixins.dart:329:27)
#18     FieldDataImpl.getFieldConstantValue (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/env.dart:982:35)
#19     JsKernelToElementMap.getFieldConstantValue (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/kernel/element_map_impl.dart:2518:17)
#20     KernelInferrerEngine.getFieldConstant (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/kernel_inferrer_engine.dart:101:24)
#21     InferrerEngineImpl.analyze (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:704:35)
#22     InferrerEngineImpl.analyzeAllElements.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:667:38)
#23     TypeSystem.withMember (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/type_system.dart:120:11)
#24     InferrerEngineImpl.analyzeAllElements.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:667:13)
#25     List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#26     InferrerEngineImpl.analyzeAllElements (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:662:13)
#27     InferrerEngineImpl.runOverAllElements (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/inferrer_engine.dart:482:5)
#28     TypeGraphInferrer.analyzeMain (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/inferrer/type_graph_inferrer.dart:67:14)
#29     GlobalTypeInferenceTask.runGlobalTypeInference.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/types/types.dart:233:29)
#30     CompilerTask.measure (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:63:51)
#31     GlobalTypeInferenceTask.runGlobalTypeInference (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/types/types.dart:229:12)
#32     Compiler.performGlobalTypeInference (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:345:28)
#33     Compiler.compileLoadedLibraries.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:383:15)
#34     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#35     Compiler.compileLoadedLibraries (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:379:16)
#36     Compiler.runInternal (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:277:5)
<asynchronous suspension>
#37     Compiler.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:38)
#38     new Future.sync (dart:async/future.dart:224:31)
#39     Compiler.run.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:216:20)
#40     CompilerTask.measureSubtask (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/common/tasks.dart:178:35)
#41     Compiler.run (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/compiler.dart:213:41)
#42     CompilerImpl.run.<anonymous closure>.<anonymous closure> (file:///E:/b/build/slave/dart-sdk-windows-stable/build/sdk/pkg/compiler/lib/src/apiimpl.dart:148:22)
#43     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#44     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#45     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#46     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#47     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#48     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#49     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#50     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#51     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

```

**Comment by sigmundch** [comment] 2018-10-03 17:10
@Bluenuance - to help us investigate, could you provide with some code sample or something that would let us reproduce the issue?

The exception looks very similar to that in #34479, which was recently fixed in master (it hasn't been released on the dev or stable channel yet). Do you think your issue is for a similar reason of redirection in generic constructors? (for example:
```dart
class C<T> {
  const C.generative();
  const C.redirect() : this.generative();
}
```
?

Thanks!

**Comment by Bluenuance** [comment] 2018-10-29 18:38
@sigmundch
after fixing about ~200 type errors, this is no longer reproducible for me. 
All I can say regarding this is, that the example you posted DID occur in my code, but I cannot tell for sure that this exception was because of it.

**Comment by sigmundch** [comment] 2018-10-29 19:14
@Bluenuance thanks for following up!

I'm glad to hear that the issue is now resolved for you. Please feel free to reopen or file a new bug if you run into it again in the future.

**Closed by sigmundch** 2018-10-29 19:14 UTC
Labels: area-dart2js, crash, needs-info
