### ISSUE TITLE
dart:mirrors does not yet work with --preview-dart-2

### ISSUE THREAD

**Issue by joeconwaystk** [dart-lang/sdk#32345] opened 2018-02-28 01:38 UTC
This code prints false when running with --preview-dart-2.

```dart
import 'dart:mirrors';

enum Enum {
  option1, option2
}

void main() {
  final isEnum = reflectClass(Enum).isEnum;
  print("${isEnum}");
}
```

**Comment by kmillikin** [comment] 2018-02-28 07:38
Support for `dart:mirrors` is currently unimplemented with --preview-dart-2.  Some things will happen to work, but nothing is guaranteed to work.  The things that happen to work today might randomly break tomorrow.

As far as I know, we have not made any official decision about supporting `dart:mirrors` on the Dart VM.  It is not supported one the Web in Dart 2.0 (#30538) and it's also not supported in the Flutter mobile development framework (https://github.com/flutter/flutter/issues/1150).

**Comment by kmillikin** [comment] 2018-02-28 08:27
And now I do know: we _have_ made an official announcement that `dart:mirrors` _will_ continue to be fully supported on the Dart VM in Dart 2.0.  It is here: https://groups.google.com/a/dartlang.org/d/msg/misc/djfFMNCWmkE/F7WE8a0JAwAJ

**Comment by joeconwaystk** [comment] 2018-02-28 14:05
Thanks very much for the info, will continue to track issue

**Comment by a-siva** [comment] 2018-03-01 01:23
The root cause of the enum not being report as 'isEnum' might be the same one as in #32365

**Comment by bergwerf** [comment] 2018-03-08 11:30
Phew, I'm glad dart:mirrors will continue to be supported, without it my code generation would be come a bit cumbersome...
Also walked into the isEnum bug, but I see it is already fixed in the other thread (so will have to wait for a new dev release now)

**Comment by manuelF** [comment] 2018-05-02 23:30
Also running into issues with preview Dart 2. Package unscripted [0] requires dart mirrors fetching method parameters and it fails with a runtime type issue:

  type 'List<dynamic>' is not a subtype of type 'List<ParameterMirror>' of 'function result' where
    List is from dart:core
    List is from dart:core
    ParameterMirror is from dart:mirrors
  
  dart:mirrors                                                                _LocalMethodMirror.parameters


[0] https://github.com/seaneagan/unscripted/blob/master/lib/src/util.dart#L38

**Comment by dgrove** [comment] 2018-05-04 16:13
@vsmenon do you have any needs here?

**Comment by vsmenon** [comment] 2018-05-04 17:30
@jmesserly 

Not that we're aware of at this point.  The CFE recently added support for parameter annotations (which we needed for temporary pageloader support).

**Comment by jmesserly** [comment] 2018-05-04 17:33
As far as I know, mirrors has enough support for DDC+Kernel. We have limited test coverage though, outside of the internal use of pageloader. (When I've regressed something in DDC+Analyzer mirrors, I don't find out until we roll the SDK.)

**Comment by a-siva** [comment] 2018-05-16 01:09
It appears that there are a number of VM mirrors tests that are marked as failing in the status files which indicates we still have a number of issues with dart:mirrors functionality in --preview-dart-2 mode.

**Comment by kmillikin** [comment] 2018-05-22 13:11
I started to try to fix the failing mirrors tests.  At least some of them are incorrect tests.  We could argue about them on a case-by-case basis, because the current VM behavior is "incorrect" by that standard and changing the VM's behavior is a breaking change.

For example, in Dart 2 the classes defined by anonymous mixin applications should always be abstract, otherwise you will get Dart 2 static errors for any abstract members of the mixed-in class.  One of the lib_2/mirrors tests tests that they are *not* abstract.

**Comment by kmillikin** [comment] 2018-05-22 13:16
Another example: if an object that is not a Function is passed as the first argument to Function.apply, we will tear off the object's call method and pass that.  If it is invoked with an  incorrect number of arguments, that will not invoke the original object's noSuchMethod.  lib_2/mirrors/apply3_test is broken for this reason.

So far, every test I've looked at is a test that was incorrectly ported from Dart 1.  We'll need to fix them eventually but it isn't a high priority right now.

**Comment by jmesserly** [comment] 2018-05-22 19:17
> So far, every test I've looked at is a test that was incorrectly ported from Dart 1. We'll need to fix them eventually but it isn't a high priority right now.

yeah, I saw that when I moved these tests to lib_2/mirrors :\ ... a lot of tests in lib_2/corelib_2/language_2 still don't expect correct runtime behavior for Dart 2. I think the function call tearoff thing happened after the Dart 2 test migration, though. My guess is: we didn't update the tests after the call tearoff change, because many Dart 2 impls lack mirrors support, so it was hard to notice the test problem.

**Comment by joeconwaystk** [comment] 2018-05-22 19:42
If there is any way to contribute here as an outsider, please let me know. The issues with mirrors and --preview-dart-2 flag are blocking many of Aqueduct tests. I am anxious that this issue may get deferred until after Dart 2 release or late enough in the process that will delay us releasing with Dart 2. I recognize that there are many other priorities and y'all are killing it, but I did want to express that concern.

**Comment by dgrove** [comment] 2018-05-23 05:18
We're definitely aware of this concern. A prioritized list of APIs that you
need would be very helpful.

**Comment by kmillikin** [comment] 2018-05-23 07:44
To echo what @dgrove said, we could definitely use help identifying the high priority issues that affect you and your tests.  You can file separate issues for them and just tag me for triage.

Eventually we will fix all those bugs (and probably modernize the API for Dart 2 features), but for now we want to prioritize fixing bugs "on demand" when we know that they are affecting customers.

**Comment by joeconwaystk** [comment] 2018-05-23 13:34
Very much appreciated. I've added #33207 and will tag you shortly.

**Comment by natebosch** [comment] 2019-06-27 23:28
@kmillikin - can we close this? I think mirrors are working now in the VM?

**Comment by a-siva** [comment] 2019-06-27 23:31
all reported issues against dart:mirrors has been fixed after the switch to Dart 2.

**Closed by a-siva** 2019-06-27 23:31 UTC
Labels: area-front-end, area-vm, front-end-kernel, p2-medium
