### ISSUE TITLE
Map value for uninitialized key is different in DDC output vs Dart2js output

### ISSUE THREAD

**Issue by corwinsheahan-wf** [dart-lang/sdk#36052] opened 2019-02-27 19:45 UTC
```
dart --version
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
```

Hi There!

We're seeing in issue where the default value for a map lookup with a key that has not been initialized behaves differently in DDC output vs dart2js output. Here's a test which will pass when compiled via dart2js, but will fail when when compiled via DDC:
```
import 'package:test/test.dart';

main() {
  test('default param', () {
    // passes in dart2js and ddc
    expect(someFunc(null), null);

    final emptyMap = {};
    // fails in ddc, passes in dart2js
    expect(someFunc(emptyMap['should_be_null']), null);
  });
}

dynamic someFunc([c1 = 'some_default_value']) {
  return c1;
}
```

If you print out the value of `emptyMap['should_be_null']`, it is `null` on both DDC compiled output and dart2js compiled output. However, the return value in DDC from `someFunc` is actually `some_default_value`, and not `null`. One workaround is to pass the expression `emptyMap['should_be_null'] ?? null` to `someFunc`.

Could it be that `emptyMap['should_be_null']` is `undefined` in the DDC output, but is explicitly null in the dart2js output?

**Comment by jakemac53** [comment] 2019-02-27 20:17
cc @jmesserly

**Comment by jmesserly** [comment] 2019-02-27 22:55
This is a known issue. This should be addressed in DDC's map implementations, which may or may not have a measurable performance impact on access times (I suspect it will not make much difference).

**Comment by jmesserly** [comment] 2019-02-28 21:58
https://dart-review.googlesource.com/c/sdk/+/94920

**Comment by rakudrama** [comment] 2019-03-05 01:39
I believe the issue is not that map returns `null` or `undefined`, but how DDC and dart2js differ in the defaulting of optional arguments.
There are many ways of getting a JavaScript `undefined` value, consider  `new List(100000)[2]`.

**Comment by jmesserly** [comment] 2019-03-05 09:50
Would you mind opening another issue about that, if you'd like to discuss further? I'd rather keep this issue focused on the report, and discuss bigger design questions about calling conventions elsewhere.

(In general, DDC tries to avoid common pitfalls related to undefined, by using `null` where it is practical to do so. There are indeed cases where it breaks down, though these seem rare in practice. I don't think changing the calling convention in DDC is practical, but if you'd like to discuss further, we can certainly revisit it.)

**Closed by jmesserly** 2019-03-05 09:50 UTC
Labels: area-dev-compiler

**Comment by rakudrama** [comment] 2019-03-05 18:42
@jmesserly Done: #36116
