### ISSUE TITLE
Report warning/error on field/getter invocations on nullable function types

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#40309] opened 2020-01-24 11:34 UTC

**Comment by stefantsov** [comment] 2020-02-05 10:33
@johnniwinther I tried to reproduce the issue with the following program:

```dart
foo(int Function()? f) => f.call;
```

It looks like the expected warnings and errors are emitted.  I think we can close the issue.  WDYT?

<details>
<summary>Click to expand</summary>

```
$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks /tmp/asdf.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/tool/_fasta/compile.dart --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks /tmp/asdf.dart
/tmp/asdf.dart:1:29: Warning: Property 'call' is accessed on 'int Function()?' which is potentially null.
Try accessing using ?. instead.
foo(int Function()? f) => f.call;
                            ^^^^
library;
//
// Problems in library:
//
// /tmp/asdf.dart:1:29: Warning: Property 'call' is accessed on 'int Function()?' which is potentially null.
// Try accessing using ?. instead.
// foo(int Function()? f) => f.call;
//                             ^^^^
//
import self as self;
import "dart:core" as core;

static method foo(() →? core::int f) → dynamic
  return f.call;


$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/tool/_fasta/compile.dart --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
/tmp/asdf.dart:1:29: Error: Property 'call' cannot be accessed on 'int Function()?' because it is potentially null.
Try accessing using ?. instead.
foo(int Function()? f) => f.call;
                            ^^^^
library;
//
// Problems in library:
//
// /tmp/asdf.dart:1:29: Error: Property 'call' cannot be accessed on 'int Function()?' because it is potentially null.
// Try accessing using ?. instead.
// foo(int Function()? f) => f.call;
//                             ^^^^
//
import self as self;
import "dart:core" as core;

static method foo(() →? core::int f) → dynamic
  return let final<BottomType> #t1 = invalid-expression "/tmp/asdf.dart:1:29: \u0027[31mError: Property 'call' cannot be accessed on 'int Function()?' because it is potentially null.\nTry accessing using ?. instead.\u0027[39;49m\nfoo(int Function()? f) => f.call;\n
                   ^^^^" in f.call;
```
</details>

**Closed** 2020-02-05 10:44 UTC
Labels: NNBD, area-front-end
