### ISSUE TITLE
analyzer: @required named parameter on constructor needs error for 0-arg ctor override

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#36297] opened 2019-03-21 20:04 UTC
Given

```
class Foo {
  final int id;
  Foo({@required this.id});
}

class FooSub extends Foo {}
```

class FooSub gets a default 0-arg constructor which does not include the param `@required this.id`.

```
new FooSub(); // ok, no @required error
new FooSub(id: 0); // error: no parameter id
```

I think the solution here is to warn at the definition of FooSub:

```
Error: default 0-arg constructor for class Foo has required named parameter id
```

Wording here will be tricky to make intuitive.

**Comment by bwilkerson** [comment] 2019-03-21 20:53
Just to be clear, the problem _isn't_ the fact that the constructor in the subclass doesn't have a parameter. That's perfectly valid because constructors don't override constructors from the superclass.

The problem is that the code is implicitly invoking the superclass' constructor without providing a required named argument. In other words, the following is a perfectly valid subclass of `Foo` for which there should be no hint:
```
class ValidFooSub {
  ValueFooSub() : super(id: 42);
}
```

**Comment by srawlins** [comment] 2020-06-20 17:58
Thanks for reporting this issue. This was previously reported at https://github.com/dart-lang/sdk/issues/30117; please follow along there.

**Comment by srawlins** [comment] 2020-06-20 17:58
Duplicate of #30117

**Closed by srawlins** 2020-06-20 17:58 UTC
Labels: analyzer-hint, area-analyzer, type-bug
