### ISSUE TITLE
Support compiling vmservice with an external outline of the sdk

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30111] opened 2017-07-08 04:24 UTC
When building the vmservice we practically embed the entire SDK with it.

We would like to build vmservice using only an outline of the SDK, and only link this outline as external libraries.

When I tried to do so, my change works without a problem in release mode, but hits two assertions in debug mode when loading the kernel code:
  * the first assertion is related to support for external references:
```
../../runtime/vm/kernel_binary_flowgraph.h: 1370: error: expected: flags == 0
Dumping native stack trace for thread 2a38
  [0x0000000000c7b6e7] dart::Profiler::DumpStackTrace(bool)
  [0x0000000000c7b6e7] dart::Profiler::DumpStackTrace(bool)
  [0x0000000000d9d726] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x0000000000c50097] Unknown symbol
  [0x0000000000c69b38] dart::kernel::KernelReader::ReadLibrary(long)
  [0x0000000000c69946] dart::kernel::KernelReader::ReadProgram()
  [0x0000000000d94206] Dart_LoadKernel
  [0x00000000006fe1d1] Unknown symbol
  [0x0000000000d1c4b2] Unknown symbol
  [0x0000000000d4eb3c] dart::ThreadPool::Worker::Loop()
  [0x0000000000d4e991] dart::ThreadPool::Worker::Main(unsigned long)
  [0x0000000000bc94b1] Unknown symbol
-- End of DumpStackTrace
```

  * I'm not sure what the second issue is about, the exception is shown below:
```
./../runtime/vm/object.h: 7970: error: expected: (byte_offset == 0) || ((byte_offset > 0) && (byte_offset < LengthInBytes()))
Dumping native stack trace for thread 2e1
  [0x0000000002df56f7] dart::Profiler::DumpStackTrace(bool)
  [0x0000000002df56f7] dart::Profiler::DumpStackTrace(bool)
  [0x0000000002f25c36] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x0000000002dd0e23] dart::kernel::TranslationHelper::DartSymbol(dart::kernel::StringIndex) const
  [0x0000000002de3fb8] dart::kernel::KernelReader::ReadLibrary(long)
  [0x0000000002de3d86] dart::kernel::KernelReader::ReadProgram()
  [0x0000000002f0de86] Dart_LoadKernel
  [0x000000000287f15a] dart::TestCase::LoadTestScript(char const*, void (*(*)(_Dart_Handle*, int, bool*))(_Dart_NativeArguments*), char const*, bool)
  [0x0000000002863e9e] Unknown symbol
  [0x0000000002863951] dart::Dart_TestSourceReport_MultipleReports()
  [0x000000000267efbc] dart::TestCase::Run()
  [0x000000000267f06b] dart::TestCaseBase::RunTest()
  [0x000000000287eaa7] dart::TestCaseBase::RunAll()
  [0x000000000267f2f5] main
-- End of DumpStackTrace
```

Marking the outline as non-external fixes the first kind of failure, but for the second kind of failure I had to use the full sources of the platform libraries, and using outlines was not sufficient.

To repro:
* change two lines in ./tools/patch_sdk.dart marked with this issue:
   * replace `platform` with `outline` as an input summary for building vmservice ([here](https://github.com/dart-lang/sdk/blob/d844dc8226aafac52531b33d1c78de6ab140432c/tools/patch_sdk.dart#L146))
   * comment out the line that marks external libraries as if they weren't external ([here](https://github.com/dart-lang/sdk/blob/d844dc8226aafac52531b33d1c78de6ab140432c/tools/patch_sdk.dart#L156))
* rebuild the patch_sdk
* run these tests:

```
# illustrates the first issue:
python tools/test.py -c dartk --builder-tag no_ipv6 --vm-options --no-enable-malloc-hooks vm/dart/error_stacktrace_test

#illustrates the second issue:
python tools/test.py -c dartk --builder-tag no_ipv6 --vm-options --no-enable-malloc-hooks vm/cc/SourceReport_MultipleReports
```

/cc @kmillikin @a-siva

**Comment by sigmundch** [comment] 2017-07-08 17:37
I found another instance of the second issue.

If kernel-service.dart sends down to the VM a truncated .dill file (where the sdk is not serialized entirely), then I hit the 2nd failure above in about 26 tests (surprisingly most other tests are fine). To repro:

revert the change to kernel_service.dart in https://github.com/dart-lang/sdk/commit/cc567226a823d41311eb5c09cf7e894afc1fc4c6#diff-b46dd167b09a412f1fdda4c1f2148627

Then run a test like: 
```
python tools/test.py -c dartk --builder-tag no_ipv6 --vm-options --no-enable-malloc-hooks language/try_catch_syntax_test/none
```

Other test failures for this reason are here:  https://uberchromegw.corp.google.com/i/client.dart/builders/vm-kernel-mac-debug-x64-be/builds/142/steps/vm%20tests/logs/stdio

**Comment by kmillikin** [comment] 2017-08-15 17:52
I'll try to reproduce this so I can investigate it.

**Comment by kmillikin** [comment] 2017-08-16 12:41
The second issue appears to be #30420, where we attempt to take the address that is one past the end of the (backing store of the) string table.  This is legal C++ and it is convenient to use it as a termination condition, for instance, but there is an assertion that we don't do it.  I say it appears to be the same issue because I have not verified this one yet, but the fact that it works in release mode seems to indicate that it is the same issue.

The issue is triggered by the empty string appearing as the last string in the string table.  The fix is either to adjust the assertion or else handle this case specially.

**Comment by kmillikin** [comment] 2017-08-22 15:41
There is still a (new?) failure in the front end hot reload end-to-end tests.  Reproduce with

```
python tools/test.py -mrelease --checked pkg/front_end/test/src/incremental/hot_reload_e2e_test
```

I've reverted the changes to patch_sdk.

**Comment by sigmundch** [comment] 2017-08-22 18:58
It appears that when vmservice was loaded in the vm it was not linked against the existing platform.dill code. 
Here is the exception from that test:
```
Expected: empty
    Actual: [
    'vm-service: Error: Unhandled exception:',
    'NoSuchMethodError: The getter \'iterator\' was called on null.',
    'Receiver: null',
    'Tried calling: iterator',
    '#0      Object._noSuchMethod (patched_sdk/lib/core/object.dart)',
    '#1      Object.noSuchMethod (patched_sdk/lib/core/object.dart:108:12)',
    '#2      VMService._exit (dart:_vmservice:303:24)',
    '<asynchronous suspension>',
    '#3      VMService.messageHandler (dart:_vmservice:326:9)',
    '#4      _RawReceivePortImpl._handleMessage (dart:isolate:1132:12)',
    ''
  ]
```

The exception seems to be because `clients.toList()` returns a null value, which would make sense if we use as implementation of `toList()` from the outline file.

@a-siva - could it be that by any chance we are loading vmservice before platform.dill?

**Comment by jensjoha** [comment] 2017-08-31 11:01
I think the problem is with mixins:

 method _exit() contains the following code (when compiled with the outline):
```
            core::List<_vm::Client> clientsList = this.{_vm::VMService::clients}.{col::IterableMixin::toList}();
            for (_vm::Client client in clientsList) {
              client.{_vm::Client::disconnect}();
            }
```

VMService has the field 
```
final field _vm::NamedLookup<_vm::Client> clients = new _vm::NamedLookup::•<_vm::Client>(prologue: _vm::VMService::serviceNamespace);
```

NamedLookup looks like this (and doesn't contain a toList method):
```
class NamedLookup<E extends core::Object> extends _vm::Object&IterableMixin^^#T0<_vm::NamedLookup::E> { 
[...]
}
```

and finally Object&IterableMixin^^#T0 looks like this (when compiled with outline):
```
  abstract class Object&IterableMixin^^#T0<#T0 extends core::Object> extends core::Object implements col::IterableMixin<_vm::Object&IterableMixin^^#T0::#T0> { // from file://[...]/lib/vmservice/named_lookup.dart
    [...]
    method /* from  */ toList({core::bool growable}) → core::List<_vm::Object&IterableMixin^^#T0::#T0>
      ;
    [...]
  }
```

whereas it looks like this when compiled with platform:
```
  abstract class Object&IterableMixin^^#T0<#T0 extends core::Object> extends core::Object implements col::IterableMixin<_vm::Object&IterableMixin^^#T0::#T0> { // from file://[...]/lib/vmservice/named_lookup.dart
    [...]
    method /* from patched_sdk/lib/collection/iterable.dart */ toList({core::bool growable = true}) → core::List<_vm::Object&IterableMixin^^#T0::#T0>
      return core::List::from<_vm::Object&IterableMixin^^#T0::#T0>(this, growable: growable);
    [...]
  }
```

Also "mixin_full_resolution.dart" says
```
/// Replaces all mixin applications with regular classes, cloning all fields
/// and procedures from the mixed-in class, [...]
```

so it seems to me that it has cloned the outline which will obviously cause problems.

**Comment by sigmundch** [comment] 2017-08-31 21:01
Thanks for investigating @jensjoha  - so it sounds like this boils down to making mixin applications modular as discussed in #29881, correct?

**Comment by jensjoha** [comment] 2017-09-01 06:00
I think you're right.

**Comment by kmillikin** [comment] 2017-09-01 07:28
We won't be able to perform mixin elimination against an outline of the platform, as it's currently designed.  Instead, we will have to have method bodies for the mixed-in class.

It does seem like there might be a bug somewhere.  Kernel classes should be loaded at a particular `ClassLevel` and the mixin elimination transformation will fail if classes aren't at `Mixin` level or higher (which implies that all their members including method bodies are present).  Somehow when using the outline the class level is not correct for mixed-in classes.

**Comment by sigmundch** [comment] 2017-09-01 16:52
> We won't be able to perform mixin elimination against an outline of the platform, as it's currently designed. Instead, we will have to have method bodies for the mixed-in class.

Do I understand correctly that it is a goal to change this? (we will mention the forwarding reference, but let the VM clone the body while deserializing?

> ... Somehow when using the outline the class level is not correct for mixed-in classes.

Good point @kmillikin, we are not correctly marking the level in fasta, I filed #30603 to fix that.

**Comment by kmillikin** [comment] 2017-10-02 11:08
I don't think it's explicitly a goal to be able to translate away mixins without knowing the bodies of platform class members.  The front end for the VM should always be able to know these bodies.

We should make sure that it is the case that the platform libraries are external libraries and are serialized without including method bodies in a compiled .dill file.

**Comment by a-siva** [comment] 2017-11-09 23:49
We don't have a separate vmservice.dill file anymore after
https://github.com/dart-lang/sdk/commit/c29b19fb34d545caa227f6c16fa06bddc6da1114

So closing this issue.

**Closed by a-siva** 2017-11-09 23:49 UTC
Labels: area-vm
