### ISSUE TITLE
Has 3.5.1 sdk been submitted to Docker?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#56553] opened 2024-08-22 15:01 UTC
Still not showing up at https://hub.docker.com/_/dart

**Comment by devoncarew** [comment] 2024-08-22 16:35
cc @athomas

**Comment by athomas** [comment] 2024-08-22 19:01
It was delayed by should appear soon, the official images PR was already merged.

Dupe of https://github.com/dart-lang/dart-docker/issues/204.

**Closed by athomas** 2024-08-22 19:01 UTC
Labels: area-sdk, type-question
