### ISSUE TITLE
Bug in web dev compiler

### ISSUE THREAD

**Issue by OroshiX** [dart-lang/sdk#39157] opened 2019-10-29 10:53 UTC
I just inserted a new dependency: flutter_map (a leaflet plugin using mapbox), and a minimal example of a map in my project (which was compiling correctly for chrome before). And I got an error when compiling for chrome:

```
 Error compiling dartdevc module:flutter_app|lib/screen/chat_screen.ddc.js
           
           We're sorry, you've found a bug in our compiler.
           You can report this bug at:
               https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
           Please include the information below in your report, along with
           any other information that may help us track it down. Thanks!

               dartdevc -k arguments: --dart-sdk-summary=/Data/Applis/Linux/FlutterSDK/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--modules=amd
               --no-summarize -o packages/flutter_app/screen/chat_screen.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta
               --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
               --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
               --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
--summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
               --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
               --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
               --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics
--summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
               --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
               --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
               --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
               --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
               --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
               --summary=packages/collection/collection.ddc.dill=packages/collection/collection
               --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
               --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
               --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
               --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
               --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding
               --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
               --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation
               --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
               --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
               --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
               --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions
               --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
               --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet
               --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino
--summary=packages/flutter/material.ddc.dill=packages/flutter/material
               --packages=file:///tmp/kernel_builder_OAOWMC/.packages --module-name=packages/flutter_app/screen/chat_screen
--multi-root-scheme=org-dartlang-app
               --multi-root=. --track-widget-creation --inline-source-map
               --libraries-file=file:///Data/Applis/Linux/FlutterSDK/flutter/bin/cache/flutter_web_sdk/libraries.json
               --used-inputs-file=/tmp/ddk_builder_KVESAJ/used_inputs.txt package:flutter_app/screen/chat_screen.dart
               dart --version: 2.6.0-dev.8.2.flutter-1bd6e20d76 (Thu Oct 24 13:00:50 2019 +0000) on "linux_x64"
           
           Bad state: Empty input given.
           #0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:458:29)
           #1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:475:7)
           #2      Timeline.timeSync (dart:developer/timeline.dart:161:22)
           #3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:473:21)
           #4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:410:10)
           #5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:207:29)
           <asynchronous suspension>
           #6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:153:10)
           <asynchronous suspension>
           #7      _compile (package:dev_compiler/src/kernel/command.dart:277:27)
           <asynchronous suspension>
           #8      compile (package:dev_compiler/src/kernel/command.dart:42:18)
           <asynchronous suspension>
           #9      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
           #10     _CompilerWorker.performRequest.<anonymous closure>
(file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
           #11     _rootRun (dart:async/zone.dart:1124:13)
           #12     _CustomZone.run (dart:async/zone.dart:1021:19)
           #13     _runZoned (dart:async/zone.dart:1516:10)
           #14     runZoned (dart:async/zone.dart:1463:12)
           #15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
           <asynchronous suspension>
           #16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
           #17     _rootRun (dart:async/zone.dart:1124:13)
           #18     _CustomZone.run (dart:async/zone.dart:1021:19)
           #19     _runZoned (dart:async/zone.dart:1516:10)
           #20     runZoned (dart:async/zone.dart:1463:12)
           #21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
           <asynchronous suspension>
           #22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
           <asynchronous suspension>
           #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
           #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
           
```

- I use dart version: Dart VM version: 2.6.0-dev.8.2.flutter-1bd6e20d76 (Thu Oct 24 13:00:50 2019 +0000) on "linux_x64"
- I am on Linux
- Compiling for Chrome

**Comment by sigmundch** [comment] 2019-11-01 17:16
Thanks for reporting the issue. There appears to be a transient bug, so you may find that the issue disappears after trying again. We are still investigating and will be making changes to reduce the changes of this happening.

Merging as duplicate of #38102

**Closed by sigmundch** 2019-11-01 17:16 UTC
Labels: area-web
