### ISSUE TITLE
`dart format -n` hangs indefinitely

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#42118] opened 2020-05-29 16:58 UTC
When running `dart format -n`, the process hangs indefinitely. I believe that's its passing the `-n` param directly to `dartfmt`, but dartfmt has different behavior than we want for `dart format`. dartfmt wants to act on stdin (which it's likely waiting for above), but `dart format` should operate on the current directory if no files are provided.

cc @jwren 

Somewhat related, I believe that when passed the 'dry run' flag (`-n`), we should automatically set the `--set-exit-if-changed` flag if it wasn't explicitly set for the user. This is to facilitate the use of `dart format -n` on a CI to ensure that all code in a particular PR is formatted.

**Comment by devoncarew** [comment] 2020-05-29 19:29
and, cc @munificent

**Comment by munificent** [comment] 2020-06-01 18:39
> dartfmt wants to act on stdin (which it's likely waiting for above)

That's the behavior of the old `dartfmt` command, but the interface `dart` uses to run the formatter is different.

> but `dart format` should operate on the current directory if no files are provided.

Right now, it exits with an error if you don't pass any files. That's how `flutter format` behaves and is, I thought, how we wanted `dart format` to behave. Where did the idea of formatting the cwd come from?

I'm not sure what's going on with `-n` and no other arguments. I'll take a look.

**Comment by devoncarew** [comment] 2020-06-01 18:44
Ah, ok, I'd have been happy for `dart format` to fail w/ a usage message, and for me to have to run `dart format .`.

I think the main issue here is the hang -

**Comment by munificent** [comment] 2020-06-30 21:34
I finally looked into this. The issue is not in dartfmt itself. It's that dartdev is still using the old dartfmt CLI and not the new Command API that it exposes. I took a look at rolling that into dartdev myself but I got a bunch of test failures like "Unsupported operation: Cannot extract a file path from a data URI" and some version lock because the version of analyzer dartdev uses is not compatible with the latest dart_style.

I'm going to bounce this to @jwren to look at. Jaime, to fix this, you'll want to use the FormatCommand class that dart_style declares in "package:dart_style/src/cli/format_command.dart". If you run into any problems or would like me to take a look, let me know. :)

**Comment by franklinyow** [comment] 2020-07-27 23:25
@jwren Are we fixing this in the next few day?

**Comment by devoncarew** [comment] 2020-07-28 17:25
Jaime, can you verify the current behavior here?

**Comment by devoncarew** [comment] 2020-08-04 17:28
@jwren - ping

**Comment by jwren** [comment] 2020-08-04 17:41
Thanks Devon, I keep meaning to close this out:

```
dart format -n .
Could not find an option or flag "-n".

...
```

`-n` is not an option on `dart format *` with the new implementation.

**Closed by jwren** 2020-08-04 17:41 UTC
Labels: area-dart-cli
