### ISSUE TITLE
Dart analysis server error: Element not found in summary

### ISSUE THREAD

**Issue by Cavdy** [dart-lang/sdk#34790] opened 2018-10-15 08:46 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768, 1680x1050`

# Exception

Please append the contents of:
file://C:\Users\Cavdy\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: A:\Projects\Flutter\aware_cryptocurrency\lib\home_page.dart
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart

**Comment by stereotype441** [comment] 2018-10-23 04:05
Duplicate of #34555

**Closed by stereotype441** 2018-10-23 04:05 UTC
Labels: area-analyzer
