### ISSUE TITLE
`Pointer.fromFunction`'s exceptional return const detection doesn't work very well

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#57115] opened 2024-11-17 23:54 UTC
A user reported some bugs with `Pointer.fromFunction`'s exceptional return param: https://github.com/dart-lang/native/issues/1724

There are a few different bugs here, but they're all to do with the const detection. The following all erroneously produce a "Exceptional return value must be a constant" error when passed to exceptional return:

- Negative int literals. These should just work.
- Simple enums values. These should also just work.
- An enhanced enum. This should produce a type mismatch error, but is reported as the same constness error, so the user didn't know that they were supposed to pass `dc_status_t.DC_STATUS_TIMEOUT.value`.
- The enhanced enum's `.value` field doesn't work anyway.

**Comment by dcharkes** [comment] 2024-11-18 09:40
Duplicate of:

* https://github.com/dart-lang/sdk/issues/54417

**Closed** 2024-11-18 21:46 UTC
Labels: closed-duplicate, type-bug, library-ffi, triage-automation, area-native-interop
