### ISSUE TITLE
Promotion for private final fields and separation of super and this.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#50350] opened 2022-10-31 17:51 UTC
This code promotes, but I think it should not.
```dart
class A {
  final int? _x;
  A(this._x);
}

class C extends A {
  final int? _x;
  C(this._x) : super(_x);

  void testC() {
    if (_x != null) {
      super._x.isOdd;
    }
  }
}
```
And similarly when we check `super._x`, we cannot treat `this._x` as promoted.

@stereotype441 

https://github.com/dart-lang/language/issues/2020

**Comment by stereotype441** [comment] 2022-11-02 22:36
Duplicate of https://github.com/dart-lang/sdk/issues/50138

**Closed by stereotype441** 2022-11-02 22:36 UTC
Labels: area-front-end
