### ISSUE TITLE
Failures on [vm/ffi] Closure callbacks for sync callbacks

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53346] opened 2023-08-25 06:54 UTC
There are new test failures on [[vm/ffi] Closure callbacks for sync callbacks](https://github.com/dart-lang/sdk/commit/e8d7425c4ea8765c1e349db9197563dcb45b9638).

The tests
```
ffi/function_callbacks_structs_by_value_native_callable_generated_test/0 RuntimeError (expected Pass)
ffi/function_callbacks_structs_by_value_native_callable_generated_test/0 Crash (expected Pass)
ffi/function_callbacks_structs_by_value_native_callable_generated_test/1 RuntimeError (expected Pass)
ffi/function_callbacks_structs_by_value_native_callable_generated_test/1 Crash (expected Pass)
ffi/function_callbacks_structs_by_value_native_callable_generated_test/2 RuntimeError (expected Pass)
ffi/function_callbacks_structs_by_value_native_callable_generated_test/2 Crash (expected Pass)
ffi/function_callbacks_structs_by_value_native_callable_generated_test/3 RuntimeError (expected Pass)
ffi/function_callbacks_structs_by_value_native_callable_generated_test/3 Crash (expected Pass)
ffi/function_callbacks_varargs_native_callable_generated_test/0 RuntimeError (expected Pass)
ffi/function_callbacks_varargs_native_callable_generated_test/1 RuntimeError (expected Pass)
ffi/function_callbacks_varargs_native_callable_generated_test/2 RuntimeError (expected Pass)
ffi/function_callbacks_varargs_native_callable_generated_test/3 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-linux-release-riscv64-qemu
vm-aot-win-debug-arm64
vm-aot-win-release-arm64
vm-linux-release-riscv64-qemu
vm-msan-linux-release-x64
vm-win-debug-arm64
vm-win-release-arm64
```

**Comment by dcharkes** [comment] 2023-08-25 06:58
risc-v log: https://dart-ci.appspot.com/log/vm-ffi-qemu-linux-release-riscv64/vm-aot-linux-release-riscv64-qemu/661/ffi/function_callbacks_structs_by_value_native_callable_generated_test/1

windows log: https://dart-ci.appspot.com/log/vm-win-debug-arm64/vm-win-debug-arm64/221/ffi/function_callbacks_varargs_native_callable_generated_test/0

msan log: https://dart-ci.appspot.com/log/vm-msan-linux-release-x64/vm-msan-linux-release-x64/220/ffi/function_callbacks_structs_by_value_native_callable_generated_test/0

**Comment by liamappelbe** [comment] 2023-08-27 22:23
The riscv failures are just https://github.com/dart-lang/sdk/issues/48645 again. I preapproved them, but I guess it didn't work.

**Comment by liamappelbe** [comment] 2023-08-27 22:34
The windows failures are another instance of https://github.com/dart-lang/sdk/issues/52644

**Comment by liamappelbe** [comment] 2023-08-27 23:28
@dcharkes Could the msan failures be an instance of #52399? The failure point looks like this:

```C++
  Struct17BytesInt result = f(a0, a1, a2);

  std::cout << "result = "
            << "(" << result.a0 << ", " << result.a1 << ", "    // <- msan failure here
            << static_cast<int>(result.a2) << ")"
            << "\n";
```

I don't think I modified the return value marshalling at all, so my guess is it's an existing issue.

**Comment by dcharkes** [comment] 2023-08-28 11:50
Thanks for triaging @liamappelbe!

> @dcharkes Could the msan failures be an instance of #52399?

It looks like it. The struct by value is likely returned as a pointer to space on the stack. Those slots on the stack are populated but the code that stores into those slots is not MSAN instrumented. (I have a reminder on my todolist to address #52399...)

**Comment by liamappelbe** [comment] 2023-08-28 22:45
Ok, so I'll close this bug, since it's effectively a dupe of #48645, #52644, and #52399.

**Closed by liamappelbe** 2023-08-28 22:45 UTC
Labels: area-vm, library-ffi
