### ISSUE TITLE
Error running 'main.dart': not implemented

### ISSUE THREAD

**Issue by chenkangcrack** [dart-lang/sdk#34866] opened 2018-10-19 15:10 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4129.33`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IU-182.4129.33, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/s1/64ny9rwx4bl2drlkz6yj7k900000gp/T/report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/kang.chen/DEV/atn_wallet_app/lib/views/mainPage.dart context: exception_20181019_230623_070
Exception: Element not found in summary: package:atn_wallet_app/views/mainPage.dart

**Comment by stereotype441** [comment] 2018-10-23 21:20
Duplicate of #34555

**Closed by stereotype441** 2018-10-23 21:20 UTC
Labels: area-analyzer, type-bug
