### ISSUE TITLE
[Analyzer] Dart Analyzer stop working after input < and > twice

### ISSUE THREAD

**Issue by azliR** [dart-lang/sdk#43841] opened 2020-10-19 00:07 UTC
![Screenshot (56)](https://user-images.githubusercontent.com/43084763/96389037-4c428200-11d7-11eb-9566-e731565fdd65.png)

### Problem
Every time I enter '<' and '>', then I enter it again, the Dart Analyzer stops immediately and the CPU goes up drastically, for example, see the code below:

`Future<Option<${thisIsBlinkingVerticalLine}>>`

Right after I input that code, the Dart Analyzer will immediately stop. The analyzer doesn't say that it stops, but it just stops analyzing the code and the CPU goes up right away (in my case it's between 30-40%, but it's definitely different on other devices). This situation has existed since several previous versions of Flutter, but because I use VSCode and there is no automatic '>' addition in VSCode, I ignore it and use the new coding method, which is to add '>' later after all the previous code is finished. But now I'm using Android Studio where it adds a '>' at the end automatically, so I accidentally pass my code and this bug always shows up.

### Solution (for now):
The solution, for now, is to avoid entering '>' before you've finished writing the previous code. For example:
Enter this code:

`Future<Option<${thisIsBlinkingVerticalLine}`

After that, enter '>' at the end to prevent the Dart Analyzer from stopping.

**Comment by Jairolaya12x** [comment] 2020-10-25 02:43
I have the same issue, in windows 10 and MacOS for example if I write

`Future<List>`
`Future<List<String>>`

Break the Dart analyzer and show a error like this,
![image](https://user-images.githubusercontent.com/12990103/97097643-f3dd0b80-1640-11eb-9276-7eadca383d41.png)
And if I change the code don't works the only solution is restart the analyzer but is frustrating.
And same like you a temporal but bad solutions is write the line of code without autocomplete and separing every section and later moving everyone to the right position

I hope any fix. Thanks

**Comment by srawlins** [comment] 2021-07-20 05:39
Duplicate of https://github.com/dart-lang/sdk/issues/43572

**Closed by srawlins** 2021-07-20 05:39 UTC
Labels: P3, analyzer-crash-report, area-analyzer
