### ISSUE TITLE
Support unicode property in RegExp

### ISSUE THREAD

**Issue by trK54Ylmz** [dart-lang/sdk#33108] opened 2018-05-13 19:04 UTC
Is there any plans to add unicode properties support on `RegExp`,

For instance,
```dart
String pattern = r"^\p{Lu}{1}\p{Ll}{1,}$";
RegExp regex = new RegExp(pattern);
print(regex.hasMatch("Tarık"));
```

Reference;
https://github.com/tc39/proposal-regexp-unicode-property-escapes

## Version

`Dart 2.0.0-dev.54.0.flutter-46ab040e58`

**Comment by lrhn** [comment] 2018-05-13 20:11
The functionality is in the JS Irregexp engine, so it should be trivial to support it when compiling to JavaScript. 
Not sure how much it will cost to migrate that functionality to the VM.

It's not on the immediate horizon, but it's something that would be nice to do, if possible.

**Comment by trK54Ylmz** [comment] 2018-05-13 22:56
Probably this is not the right way but, I use https://gist.github.com/trK54Ylmz/f1ba9026412dc90e5f8bc1d4f541f1a5

seen from,
https://difnet.com.br/opensource/unicode_hack.js

**Comment by sstrickl** [comment] 2019-03-12 11:04
Duplicate of #34935. (I'm currently working on this now.)

**Closed by sstrickl** 2019-03-12 11:04 UTC
Labels: area-vm, type-enhancement
