### ISSUE TITLE
compiler failed while running tests

### ISSUE THREAD

**Issue by benhalverson** [dart-lang/sdk#36510] opened 2019-04-07 02:17 UTC
Hello I'm following the ToH testing guide and seem to have run into a compiler bug.

Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
OSX 10.14.2

Here is the log I saw in my console.

  dartdevc arguments: --dart-sdk=/usr/local/Cellar/dart/2.2.0/libexec --dart-sdk-summary=/usr/local/Cellar/dart/2.2.0/libexec/lib/_internal/ddc_sdk.sum --modules=amd -o test/app_po.ddc.js --module-root=. --library-root=/test --summary-extension=dartdevc.linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/path/path.dartdevc.linked.sum -s packages/stack_trace/stack_trace.dartdevc.linked.sum -s packages/webdriver/src/async/alert.dartdevc.linked.sum -s packages/webdriver/src/async/stepper.dartdevc.linked.sum -s packages/webdriver/async_core.dartdevc.linked.sum -s packages/pageloader/src/api/annotation_interfaces.dartdevc.linked.sum -s packages/pageloader/src/api/page_object_annotation.dartdevc.linked.sum -s packages/pageloader/src/api/annotations.dartdevc.linked.sum -s packages/pageloader/pageloader.dartdevc.linked.sum --url-mapping=file:///test/app_po.dart,test/app_po.dart --url-mapping=file:///test/app_po.g.dart,test/app_po.g.dart file:///test/app_po.dart file:///test/app_po.g.dart
    dart --version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data/runtime/libtyped_data_patch.dart:4251:7)
#1      BufferContext._getUint32 (package:analyzer/src/summary/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:analyzer/src/summary/flat_buffers.dart:54:21)
#3      TableReader.read (package:analyzer/src/summary/flat_buffers.dart:694:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:5121:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:845:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:508:32)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:411:43)
#8      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:411:18)
#10     new CompilerAnalysisDriver (package:dev_compiler/src/analyzer/driver.dart:94:21)
#11     _compile (package:dev_compiler/src/analyzer/command.dart:135:22)
#12     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#13     compile (package:dev_compiler/src/compiler/shared_command.dart:385:18)
#14     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:49:39)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:49:24)
<asynchronous suspension>
#20     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#26     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#27     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:296:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
The repo and commit can be found here.
https://github.com/benhalverson/ToH-Dart/commit/bf0c60c932d2e52d10bda63e8212931feb81b415

When I did a `webdev serve` it blew up on me with the above message but also still is able to serve the page on http://localhost:8080

**Comment by srawlins** [comment] 2019-09-06 04:59
This was previously reported at https://github.com/dart-lang/sdk/issues/35968 and has been marked as fixed.

**Comment by srawlins** [comment] 2019-09-06 04:59
Duplicate of https://github.com/dart-lang/sdk/issues/35968

**Closed by srawlins** 2019-09-06 04:59 UTC
Labels: area-web, web-dev-compiler
