### ISSUE TITLE
Dart2JS rejects metadata on type parameters

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#21203] opened 2014-10-01 16:11 UTC
Dart2JS fails to compile the following co19 test with 'Error: Expected identifier, but got '@'':

Language/10_Generics/09_Generics_A01_t17.

This should be allowed according to the grammar.

**Comment by sigmundch** [comment] 2015-12-11 00:46
dupe of #5841

**Closed by sigmundch** 2015-12-11 00:46 UTC
Labels: area-dart2js, priority-unassigned, triaged, Type-Defect
