### ISSUE TITLE
fontend crash: A visitor method seems to be unimplemented!

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#45003] opened 2021-02-13 17:16 UTC
```
Crash when compiling null,
at character offset null:
A visitor method seems to be unimplemented!
#0      IsInstantiatedVisitor.defaultDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3421:5)
#1      UnknownType.accept (package:front_end/src/fasta/type_inference/type_schema.dart:84:14)
#2      IsInstantiatedVisitor.isInstantiated (package:front_end/src/fasta/kernel/constant_evaluator.dart:3415:17)
#3      ConstantEvaluator._evaluateDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3004:24)
#4      ConstantEvaluator._evaluateDartTypes (package:front_end/src/fasta/kernel/constant_evaluator.dart:2988:23)
#5      ConstantEvaluator._evaluateTypeArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:2964:12)
#6      ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1376:28)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:5261:44)
#8      ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#9      _ListOrSetConstantBuilder.add (package:front_end/src/fasta/kernel/constant_collection_builders.dart:27:35)
#10     ConstantEvaluator.visitSetLiteral (package:front_end/src/fasta/kernel/constant_evaluator.dart:1259:37)
#11     SetLiteral.accept (package:kernel/ast.dart:6549:44)
#12     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#13     ConstantEvaluator.evaluate (package:front_end/src/fasta/kernel/constant_evaluator.dart:924:23)
#14     ConstantsTransformer.evaluateWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:773:30)
#15     ConstantsTransformer.evaluateAndTransformWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:765:35)
#16     ConstantsTransformer.visitStaticGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:619:11)
#17     StaticGet.accept (package:kernel/ast.dart:4094:44)
#18     transformList (package:kernel/ast.dart:11071:32)
#19     Arguments.transformChildren (package:kernel/ast.dart:4252:5)
#20     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#21     TreeVisitor.visitArguments (package:kernel/visitor.dart:284:39)
#22     Arguments.accept (package:kernel/ast.dart:4242:38)
#23     StaticInvocation.transformChildren (package:kernel/ast.dart:5202:29)
#24     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#25     TreeVisitor.defaultExpression (package:kernel/visitor.dart:157:43)
#26     TreeVisitor.visitStaticInvocation (package:kernel/visitor.dart:185:53)
#27     ConstantsTransformer.visitStaticInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:748:18)
#28     StaticInvocation.accept (package:kernel/ast.dart:5191:44)
#29     AwaitExpression.transformChildren (package:kernel/ast.dart:6713:25)
#30     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#31     TreeVisitor.defaultExpression (package:kernel/visitor.dart:157:43)
#32     TreeVisitor.visitAwaitExpression (package:kernel/visitor.dart:210:51)
#33     AwaitExpression.accept (package:kernel/ast.dart:6703:44)
#34     ExpressionStatement.transformChildren (package:kernel/ast.dart:7028:31)
#35     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#36     TreeVisitor.defaultStatement (package:kernel/visitor.dart:226:41)
#37     TreeVisitor.visitExpressionStatement (package:kernel/visitor.dart:228:7)
#38     ExpressionStatement.accept (package:kernel/ast.dart:7018:43)
#39     transformList (package:kernel/ast.dart:11071:32)
#40     Block.transformChildren (package:kernel/ast.dart:7070:5)
#41     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#42     TreeVisitor.defaultStatement (package:kernel/visitor.dart:226:41)
#43     TreeVisitor.visitBlock (package:kernel/visitor.dart:229:31)
#44     Block.accept (package:kernel/ast.dart:7062:43)
#45     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:521:29)
#46     FunctionNode.accept (package:kernel/ast.dart:3095:38)
#47     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:428:37)
#48     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#49     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:426:23)
#50     Procedure.accept (package:kernel/ast.dart:2560:40)
#51     transformList (package:kernel/ast.dart:11071:32)
#52     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:376:5)
#53     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:133:26)
#54     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1232:43)
#55     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:400:7)
<asynchronous suspension>
#56     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#57     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#58     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#59     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#60     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#61     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#62     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:396:11)
<asynchronous suspension>
#63     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:212:45)
<asynchronous suspension>
#64     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:872:37)
<asynchronous suspension>


#0      IsInstantiatedVisitor.defaultDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3421:5)
#1      UnknownType.accept (package:front_end/src/fasta/type_inference/type_schema.dart:84:14)
#2      IsInstantiatedVisitor.isInstantiated (package:front_end/src/fasta/kernel/constant_evaluator.dart:3415:17)
#3      ConstantEvaluator._evaluateDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3004:24)
#4      ConstantEvaluator._evaluateDartTypes (package:front_end/src/fasta/kernel/constant_evaluator.dart:2988:23)
#5      ConstantEvaluator._evaluateTypeArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:2964:12)
#6      ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1376:28)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:5261:44)
#8      ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#9      _ListOrSetConstantBuilder.add (package:front_end/src/fasta/kernel/constant_collection_builders.dart:27:35)
#10     ConstantEvaluator.visitSetLiteral (package:front_end/src/fasta/kernel/constant_evaluator.dart:1259:37)
#11     SetLiteral.accept (package:kernel/ast.dart:6549:44)
#12     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#13     ConstantEvaluator.evaluate (package:front_end/src/fasta/kernel/constant_evaluator.dart:924:23)
#14     ConstantsTransformer.evaluateWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:773:30)
#15     ConstantsTransformer.evaluateAndTransformWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:765:35)
#16     ConstantsTransformer.visitStaticGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:619:11)
#17     StaticGet.accept (package:kernel/ast.dart:4094:44)
#18     transformList (package:kernel/ast.dart:11071:32)
#19     Arguments.transformChildren (package:kernel/ast.dart:4252:5)
#20     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#21     TreeVisitor.visitArguments (package:kernel/visitor.dart:284:39)
#22     Arguments.accept (package:kernel/ast.dart:4242:38)
#23     StaticInvocation.transformChildren (package:kernel/ast.dart:5202:29)
#24     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#25     TreeVisitor.defaultExpression (package:kernel/visitor.dart:157:43)
#26     TreeVisitor.visitStaticInvocation (package:kernel/visitor.dart:185:53)
#27     ConstantsTransformer.visitStaticInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:748:18)
#28     StaticInvocation.accept (package:kernel/ast.dart:5191:44)
#29     AwaitExpression.transformChildren (package:kernel/ast.dart:6713:25)
#30     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#31     TreeVisitor.defaultExpression (package:kernel/visitor.dart:157:43)
#32     TreeVisitor.visitAwaitExpression (package:kernel/visitor.dart:210:51)
#33     AwaitExpression.accept (package:kernel/ast.dart:6703:44)
#34     ExpressionStatement.transformChildren (package:kernel/ast.dart:7028:31)
#35     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#36     TreeVisitor.defaultStatement (package:kernel/visitor.dart:226:41)
#37     TreeVisitor.visitExpressionStatement (package:kernel/visitor.dart:228:7)
#38     ExpressionStatement.accept (package:kernel/ast.dart:7018:43)
#39     transformList (package:kernel/ast.dart:11071:32)
#40     Block.transformChildren (package:kernel/ast.dart:7070:5)
#41     Transformer.defaultTreeNode (package:kernel/visitor.dart:680:10)
#42     TreeVisitor.defaultStatement (package:kernel/visitor.dart:226:41)
#43     TreeVisitor.visitBlock (package:kernel/visitor.dart:229:31)
#44     Block.accept (package:kernel/ast.dart:7062:43)
#45     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:521:29)
#46     FunctionNode.accept (package:kernel/ast.dart:3095:38)
#47     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:428:37)
#48     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#49     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:426:23)
#50     Procedure.accept (package:kernel/ast.dart:2560:40)
#51     transformList (package:kernel/ast.dart:11071:32)
#52     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:376:5)
#53     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:133:26)
#54     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1232:43)
#55     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:400:7)
<asynchronous suspension>
#56     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#57     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:164:19)
<asynchronous suspension>
#58     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#59     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:12)
<asynchronous suspension>
#60     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:10)
<asynchronous suspension>
#61     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:11)
<asynchronous suspension>
#62     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:396:11)
<asynchronous suspension>
#63     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:212:45)
<asynchronous suspension>
#64     _processLoadRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:872:37)
<asynchronous suspension>
```

**Comment by kevmoo** [comment] 2021-02-13 17:19
To reproduce:

* checkout this repo at this branch https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/dart_sdk_issue_45003
* run go to the `functions_framework` directory
* run `dart test.dart`

Dart SDK version: 2.13.0-21.0.dev (dev) (Tue Feb 9 15:05:31 2021 -0800) on "macos_x64"

**Comment by johnniwinther** [comment] 2021-02-13 17:32
cc @stefantsov

An `UnknownType` seems to have slipped through type inference unreplaced.

**Comment by kevmoo** [comment] 2021-02-13 19:14
look at my recent history on this repo. I added type params to a constant class. My guess is that's what's causing this.

**Comment by stefantsov** [comment] 2021-02-16 17:37
I think I know how to fix this.  As a workaround for this particular crash, I can suggest the following.  [Line](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/ca0dee893245f384fbe5aec6235b75d70c16e995/functions_framework/test.dart#L25) 25 in `test.dart` should be updated from `const _functionTargets = <FunctionTarget>{` to `var _functionTargets = const <FunctionTarget>{`.  This will redirect const evaluator to another path that doesn't lead to an `UnknownType`.  Once I resolve the underlying type inference issue, it should not matter what path the evaluator takes, so the line can be reverted back to what it was.

**Comment by kevmoo** [comment] 2021-02-16 17:41
I ended up refactoring the whole thing to ditch the const map.

...but I figured it'd be good to have this logged!

**Comment by hacker1024** [comment] 2021-04-17 11:47
I'm getting following compilation error after after updating to Flutter 2.0.5 with Dart 2.12.3. It looks like the same crash, if not a very similar one:

```
Unhandled exception:
Crash when compiling null,
at character offset null:
A visitor method seems to be unimplemented!
#0      IsInstantiatedVisitor.defaultDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3421:5)
#1      UnknownType.accept (package:front_end/src/fasta/type_inference/type_schema.dart:84:14)
#2      IsInstantiatedVisitor.isInstantiated (package:front_end/src/fasta/kernel/constant_evaluator.dart:3415:17)
#3      ConstantEvaluator._evaluateDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3004:24)
#4      ConstantEvaluator._evaluateDartTypes (package:front_end/src/fasta/kernel/constant_evaluator.dart:2988:23)
#5      ConstantEvaluator._evaluateTypeArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:2964:12)
#6      ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1376:28)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:5247:44)
#8      ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#9      ConstantEvaluator._evaluateNamedArguments.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:3040:27)
#10     List.forEach (dart:core-patch/growable_array.dart:403:8)
#11     ConstantEvaluator._evaluateNamedArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:3038:21)
#12     ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1344:41)
#13     ConstructorInvocation.accept (package:kernel/ast.dart:5247:44)
#14     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#15     ConstantEvaluator._evaluateExpressionInContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:2391:25)
#16     ConstantEvaluator.visitStaticGet.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:2409:18)
#17     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#18     ConstantEvaluator.visitStaticGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:2405:12)
#19     StaticGet.accept (package:kernel/ast.dart:4080:44)
#20     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#21     ConstantEvaluator._evaluateNamedArguments.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:3040:27)
#22     List.forEach (dart:core-patch/growable_array.dart:403:8)
#23     ConstantEvaluator._evaluateNamedArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:3038:21)
#24     ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1344:41)
#25     ConstructorInvocation.accept (package:kernel/ast.dart:5247:44)
#26     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#27     ConstantEvaluator.evaluate (package:front_end/src/fasta/kernel/constant_evaluator.dart:924:23)
#28     ConstantsTransformer.evaluateWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:773:30)
#29     ConstantsTransformer.evaluateAndTransformWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:765:35)
#30     ConstantsTransformer.visitField.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:562:13)
#31     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#32     ConstantsTransformer.visitField (package:front_end/src/fasta/kernel/constant_evaluator.dart:558:37)
#33     Field.accept (package:kernel/ast.dart:1844:40)
#34     transformList (package:kernel/ast.dart:11035:32)
#35     ConstantsTransformer.visitClass.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:412:7)
#36     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#37     ConstantsTransformer.visitClass (package:front_end/src/fasta/kernel/constant_evaluator.dart:410:23)
#38     Class.accept (package:kernel/ast.dart:1347:38)
#39     transformList (package:kernel/ast.dart:11035:32)
#40     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:375:5)
#41     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:133:26)
#42     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1241:43)
#43     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:406:7)
<asynchronous suspension>
#44     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#45     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:300:13)
<asynchronous suspension>
#46     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#47     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:509:11)
<asynchronous suspension>
#48     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1105:11)
<asynchronous suspension>


#0      IsInstantiatedVisitor.defaultDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3421:5)
#1      UnknownType.accept (package:front_end/src/fasta/type_inference/type_schema.dart:84:14)
#2      IsInstantiatedVisitor.isInstantiated (package:front_end/src/fasta/kernel/constant_evaluator.dart:3415:17)
#3      ConstantEvaluator._evaluateDartType (package:front_end/src/fasta/kernel/constant_evaluator.dart:3004:24)
#4      ConstantEvaluator._evaluateDartTypes (package:front_end/src/fasta/kernel/constant_evaluator.dart:2988:23)
#5      ConstantEvaluator._evaluateTypeArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:2964:12)
#6      ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1376:28)
#7      ConstructorInvocation.accept (package:kernel/ast.dart:5247:44)
#8      ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#9      ConstantEvaluator._evaluateNamedArguments.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:3040:27)
#10     List.forEach (dart:core-patch/growable_array.dart:403:8)
#11     ConstantEvaluator._evaluateNamedArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:3038:21)
#12     ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1344:41)
#13     ConstructorInvocation.accept (package:kernel/ast.dart:5247:44)
#14     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#15     ConstantEvaluator._evaluateExpressionInContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:2391:25)
#16     ConstantEvaluator.visitStaticGet.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:2409:18)
#17     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#18     ConstantEvaluator.visitStaticGet (package:front_end/src/fasta/kernel/constant_evaluator.dart:2405:12)
#19     StaticGet.accept (package:kernel/ast.dart:4080:44)
#20     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#21     ConstantEvaluator._evaluateNamedArguments.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:3040:27)
#22     List.forEach (dart:core-patch/growable_array.dart:403:8)
#23     ConstantEvaluator._evaluateNamedArguments (package:front_end/src/fasta/kernel/constant_evaluator.dart:3038:21)
#24     ConstantEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constant_evaluator.dart:1344:41)
#25     ConstructorInvocation.accept (package:kernel/ast.dart:5247:44)
#26     ConstantEvaluator._evaluateSubexpression (package:front_end/src/fasta/kernel/constant_evaluator.dart:1099:23)
#27     ConstantEvaluator.evaluate (package:front_end/src/fasta/kernel/constant_evaluator.dart:924:23)
#28     ConstantsTransformer.evaluateWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:773:30)
#29     ConstantsTransformer.evaluateAndTransformWithContext (package:front_end/src/fasta/kernel/constant_evaluator.dart:765:35)
#30     ConstantsTransformer.visitField.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:562:13)
#31     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#32     ConstantsTransformer.visitField (package:front_end/src/fasta/kernel/constant_evaluator.dart:558:37)
#33     Field.accept (package:kernel/ast.dart:1844:40)
#34     transformList (package:kernel/ast.dart:11035:32)
#35     ConstantsTransformer.visitClass.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:412:7)
#36     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:3083:18)
#37     ConstantsTransformer.visitClass (package:front_end/src/fasta/kernel/constant_evaluator.dart:410:23)
#38     Class.accept (package:kernel/ast.dart:1347:38)
#39     transformList (package:kernel/ast.dart:11035:32)
#40     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:375:5)
#41     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:133:26)
#42     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1241:43)
#43     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:406:7)
<asynchronous suspension>
#44     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#45     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:300:13)
<asynchronous suspension>
#46     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#47     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:509:11)
<asynchronous suspension>
#48     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1105:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
```

**Comment by johnniwinther** [comment] 2021-04-19 04:46
@stefantsov can you have a look at this? I looks like an `UnknownType` was left in a const constructor invocation.

@hacker1024 Do you have a (small) repro for this?

**Comment by hacker1024** [comment] 2021-04-19 05:53
I have no idea what's causing this and my project's quite large, so I'm having trouble narrowing it down.

**Comment by johnniwinther** [comment] 2021-04-19 07:14
Given the stack trace the problematic constant has a structure like
```Dart
  const foo = Foo(..., bar: Bar(...), ...)
```
where `Bar` is a generic class whose type arguments are inferred.

**Comment by hacker1024** [comment] 2021-04-19 07:31
Thanks, that should be enough to work out what to extract to reproduce the bug.

**Comment by hacker1024** [comment] 2021-04-19 08:47
Done: https://github.com/hacker1024/dart_sdk_issue_45003_reproduction
Something about using [`package:freezed`](https://pub.dev/packages/freezed) and constant constructors with type arguments is causing the issue.

**Comment by hacker1024** [comment] 2021-07-02 03:25
Any news on this?

**Comment by johnniwinther** [comment] 2021-07-02 07:47
I cannot reproduce the error on the bleeding edge. Can you still reproduce it, and if so, what version are you on?

**Comment by hacker1024** [comment] 2021-07-05 02:01
I can't either on Dart 2.14.0-188.5.beta. Should the issue be closed?

**Comment by johnniwinther** [comment] 2021-07-05 05:48
Let's close it. It seem to have been fixed, and if it reoccurs, we'll reopen.

**Closed by johnniwinther** 2021-07-05 05:48 UTC
Labels: area-front-end, crash
