### ISSUE TITLE
Misleading error "Conditions must have a static type of 'bool'"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26913] opened 2016-07-19 13:03 UTC
![image](https://cloud.githubusercontent.com/assets/405837/16950693/d45b7496-4dc1-11e6-94db-2b4d5a809412.png)

If I change it to

``` dart
} else if ((value as num) < 50) {
```

`.analysis_options` like in #26912

**Comment by bwilkerson** [comment] 2016-07-19 15:11
@leafpetersen Should this be an error in strong mode? (Analyzer is reporting this error because `TypeSystem.isAssignableTo(dynamic, bool)` is returning `false`.)

**Comment by leafpetersen** [comment] 2016-07-19 20:18
This should be an error if `implicit-casts` is set to false, as it is here.  Since `value` is dynamic, the result of the comparison is `dynamic`, so there is an implicit cast implied by the conditional from `dynamic` to `bool`, which is disallowed by the flag.  The error message could perhaps be more helpful.

**Comment by zoechi** [comment] 2016-07-20 08:54
To me it seems the problem is that there is an implicit dynamic value `value` but the error indicating this is hidden by the "Condition must have a static type of 'bool'" error, which is only a downstream error. Either both errors should be shown or the "implicit dynamic" error should have higher prio and be shown instead.

**Comment by leafpetersen** [comment] 2016-07-20 16:22
Why do you say that `value` is implicitly dynamic?  In that screenshot it is explicitly typed as dynamic.

**Comment by zoechi** [comment] 2016-07-21 12:02
@leafpetersen Sorry, didn't pay enough attention. If I use `String` for example I would expect an error like "The operator '>' is not defined for the class 'String'."
https://dartpad.dartlang.org/3f31c2a4558ff42383ea59a20e7c30dc 

I think "Conditions must have a static type of 'bool'" should not hide the operator error message.

I disabled all linter rules to be sure but the behavior is the same.

**Comment by leafpetersen** [comment] 2016-07-21 17:05
Ah, interesting.  So what I see is that actually both error messages are there in the analysis error window.  They are actually also both present in the hover, but only if you put the mouse exactly over the `>`.  Otherwise you only see the single error about the static type of the condition.  The little squiggle underline gives no indication that there is a second error buried in there.

![image](https://cloud.githubusercontent.com/assets/8484504/17031658/1d5858b2-4f2a-11e6-9dc8-4f7f645fa026.png)

vs

![image](https://cloud.githubusercontent.com/assets/8484504/17031674/2f4e24fc-4f2a-11e6-986d-e8a00799a389.png)

@jwren @bwilkerson Is there any way the UI could give better feedback here?  It seems to me that if a squiggle incorporates multiple errors, you might want to show all of them in the hover?  

To reproduce:

```dart

main() {
  String s = 'xxx';
  if(s > 50) {
    print('s');
  }
}
```

with .analysis_options:

```
analyzer:
  strong-mode:
    implicit-casts: false
```

**Comment by bwilkerson** [comment] 2016-07-21 17:28
That seems reasonable to me. I think the work needs to happen on the client side to notice that two ranges overlap.

**Comment by jwren** [comment] 2016-09-27 17:32
Setting priority to P2.  I don't think that the IJ framework will let us represent them any better from within the Dart Plugin.

Note that the Analysis View (problems view) would have in theory made the above situation a bit more clear.

**Comment by srawlins** [comment] 2018-06-28 20:13
The original error does not show up any longer. Closing.

```
$ dartanalyzer --version
dartanalyzer version 2.0.0-dev.65.0
$ cat 26913.dart 
void fn(dynamic value) {
  if (value < 7) {
    print('yay');
  }
}
$ dartanalyzer --strong --preview-dart-2 26913.dart 
Analyzing 26913.dart...
No issues found!
```

**Closed by srawlins** 2018-06-28 20:13 UTC
Labels: P2 medium, Type: bug, area-intellij

**Comment by Masterhacker12345** [comment] 2023-02-21 15:34
I am having the same problem with my flutter app:  if(globals.itemcount1 = 1;)

**Comment by mraleph** [comment] 2023-02-21 15:36
@Masterhacker12345 That's illegal syntax. You should get other errors as well. You can't have neither assignment nor `;` inside condition.

**Comment by Masterhacker12345** [comment] 2023-02-21 15:38
I needed to place an another = it is fixed now. Should i delete the comments?
