### ISSUE TITLE
Iterable.where should return an empty List or have an orElse parameter

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#41471] opened 2020-04-14 04:18 UTC
otherwise, we need to check to see if a list contains at least one variable that satisfies the where condition before iterating through it.
I would expect an empty list or at the very least null, but throwing an error, requires a pointless try catch method, when we can avoid that with an orElse method.

**Comment by eernstg** [comment] 2020-04-14 07:44
You already have the guarantee that you mention (`Iterable.where` returns an empty iterable when no elements satisfy the test), but the returned object is an `Iterable<T>` with the same `T` as the source, and it is not guaranteed to be a list:

```dart
void main() {
  var xs = [1];
  var ys = xs.where((i) => i.isEven);
  print("$ys, ${ys.runtimeType}");
  // Prints '(), WhereIterable<int>'.
}
```

So maybe you got the exception because you used `List<Something> ys = xs.where(...);`? In that case it throws when `ys` is initialized to a value whose type isn't `List`.

I'll close this issue because the reported behavior is as expected. But do report any other issues that you encounter!

**Closed by eernstg** 2020-04-14 07:44 UTC

**Comment by ThinkDigitalSoftware** [comment] 2020-04-14 08:10
I attempted to filter a List<int> by returning only the positive values.

**Comment by eernstg** [comment] 2020-04-14 08:29
That shouldn't be different from the example that I showed [here](https://github.com/dart-lang/sdk/issues/41471#issuecomment-613280376): It filtered a list to get all the even elements, but the list contained only odd elements.

To clarify what's going on, could you create a short example program similar to mine, but showing what you did, and how it fails? It still sounds like you might be assigning the returned value to a variable of type `List<T>` for some `T`, and that will fail because it isn't a list.

**Comment by ThinkDigitalSoftware** [comment] 2020-04-14 08:44
The error I got was bad state no element.

**Comment by ThinkDigitalSoftware** [comment] 2020-04-14 08:44
That's not a type error

**Comment by eernstg** [comment] 2020-04-14 08:50
Sounds like `StateError("No elements")`, which could be caused by calling `first` or `last` on an empty iterable. You can't show the code that does this?
