### ISSUE TITLE
Error while processing the analysis.setAnalysisRoots request

### ISSUE THREAD

**Issue by lucasjinreal** [dart-lang/sdk#56429] opened 2024-08-10 16:23 UTC
```
Analyzing neso_flutter...
An unexpected error was encountered by the Analysis Server.
Please file an issue at https://github.com/dart-lang/sdk/issues/new/choose with the following details:

Internal error: Failed to handle request: analysis.setAnalysisRoots
type 'Null' is not a subtype of type 'Object' in type cast
#0      YamlNodeExtension.valueOrThrow (package:analyzer/src/util/yaml.dart:147:36)
#1      _LintConfig.asString (package:analyzer/src/lint/config.dart:93:47)
#2      _LintConfig._parseYaml.<anonymous closure> (package:analyzer/src/lint/config.dart:136:29)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#4      MapView.forEach (dart:collection/maps.dart:347:10)
#5      _LintConfig._parseYaml (package:analyzer/src/lint/config.dart:117:16)
#6      new LintConfig.parseMap (package:analyzer/src/lint/config.dart:38:62)
#7      parseConfig (package:analyzer/src/lint/config.dart:15:25)
#8      AnalysisOptionsImplExtensions.applyOptions (package:analyzer/src/analysis_options/apply_options.dart:229:18)
#9      ContextBuilderImpl._createOptionsMap (package:analyzer/src/dart/analysis/context_builder.dart:210:15)
#10     ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:135:15)
#11     new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:108:36)
#12     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:549:40)
<asynchronous suspension>
#13     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded (package:analysis_server/src/context_manager.dart:694:11)
<asynchronous suspension>
#14     _CancellingTaskQueue.queue.<anonymous closure> (package:analysis_server/src/context_manager.dart:978:15)
<asynchronous suspension>
#15     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:364:5)
<asynchronous suspension>
#16     LegacyAnalysisServer.setAnalysisRoots (package:analysis_server/src/legacy_analysis_server.dart:792:9)
<asynchronous suspension>
#17     AnalysisSetAnalysisRootsHandler.handle (package:analysis_server/src/handler/legacy/analysis_set_analysis_roots.dart:46:7)
<asynchronous suspension>
#18     LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:576:11)
<asynchronous suspension>
#19     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#20     LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:557:7)
<asynchronous suspension>


null
[RequestError code: SERVER_ERROR, message: type 'Null' is not a subtype of type 'Object' in type cast]
```

**Comment by DanTup** [comment] 2024-08-27 16:10
Closing this as a dupe of https://github.com/dart-lang/sdk/issues/55594 which has the same error/stack.

**Closed by DanTup** 2024-08-27 16:10 UTC
Labels: area-analyzer, P3, analyzer-server, type-bug, crash

**Comment by lucasjinreal** [comment] 2024-09-06 15:18
@DanTup

Hello. my I ask when will flutter have this patch update?

Currently using flutter latest 3.24.1 suffering from this issue for a long time....
Without dart LSP, i can not code flutter.....

**Comment by DanTup** [comment] 2024-09-06 15:36
@lucasjinreal this issue has only recently been fixed and will be included in the next non-hotfix release of Dart/Flutter (which are usually approximately quarterly).

The issue is caused by invalid YAML in your `analysis_options.yaml` file, so the best fix is to correct the file. Please check the file for something like a blank entry in the lint list:

```
linter:
  rules:
    - camel_case_types
    - file_names
    - non_constant_identifier_names
    - comment_references
    -                  # this blank line triggered the error
```

If you cannot find a line that looks like this, please provide a copy of your `analysis_options.yaml` file (you may have multiple) and I can try to help spot the error.

**Comment by lucasjinreal** [comment] 2024-09-06 15:47
thanks, problem were solved!!

**Comment by MLDenzzl** [comment] 2024-10-28 08:28
PS D:\beelabapp> dart analyze
Analyzing beelabapp...
An unexpected error was encountered by the Analysis Server.
Please file an issue at https://github.com/dart-lang/sdk/issues/new/choose with the following details:

Internal error: Failed to handle request: analysis.setAnalysisRoots
type 'Null' is not a subtype of type 'Object' in type cast
#0      YamlNodeExtension.valueOrThrow (package:analyzer/src/util/yaml.dart:147:36)
#1      _LintConfig.asString (package:analyzer/src/lint/config.dart:93:47)
#2      _LintConfig._parseYaml.<anonymous closure> (package:analyzer/src/lint/config.dart:136:29)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#4      MapView.forEach (dart:collection/maps.dart:347:10)
#5      _LintConfig._parseYaml (package:analyzer/src/lint/config.dart:117:16)
#6      new LintConfig.parseMap (package:analyzer/src/lint/config.dart:38:62)
#7      parseConfig (package:analyzer/src/lint/config.dart:15:25)
#8      AnalysisOptionsImplExtensions.applyOptions (package:analyzer/src/analysis_options/apply_options.dart:229:18)
#9      ContextBuilderImpl._createOptionsMap (package:analyzer/src/dart/analysis/context_builder.dart:210:15)
#10     ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:135:15)
#11     new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:108:36)
#12     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded.performContextRebuild (package:analysis_server/src/context_manager.dart:549:40)
<asynchronous suspension>
#13     ContextManagerImpl._createAnalysisContexts.performContextRebuildGuarded (package:analysis_server/src/context_manager.dart:694:11)
<asynchronous suspension>
#14     _CancellingTaskQueue.queue.<anonymous closure> (package:analysis_server/src/context_manager.dart:978:15)
<asynchronous suspension>
#15     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:364:5)
<asynchronous suspension>
#16     LegacyAnalysisServer.setAnalysisRoots (package:analysis_server/src/legacy_analysis_server.dart:793:9)
<asynchronous suspension>
#17     AnalysisSetAnalysisRootsHandler.handle (package:analysis_server/src/handler/legacy/analysis_set_analysis_roots.dart:46:7)
<asynchronous suspension>
#18     LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:577:11)
<asynchronous suspension>
#19     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:174:14)
<asynchronous suspension>
#20     LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:558:7)
<asynchronous suspension>


null
[RequestError code: SERVER_ERROR, message: type 'Null' is not a subtype of type 'Object' in type cast]

what can i do?

**Comment by DanTup** [comment] 2024-10-28 10:27
@MLDenzzl it appears you may have invalid YAML in your `analysis_options.yaml` file. There's a fix to prevent the crash that will be included in the next stable release, but for now the best thing is to review your `analysis_options.yaml` for anything that looks invalid (see the comments above for some examples of the kinds of invalid data that triggered this previously).
