### ISSUE TITLE
type 'KeywordToken' is not a subtype of type 'List<Annotation>' at AstBuilder.endFunctionTypeAlias, SDK 2.7.0

### ISSUE THREAD

**Issue by himeshp** [dart-lang/sdk#41267] opened 2020-03-31 09:56 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-192.7142.36.36.6241897`
- `2.7.0`
- `AI-192.7142.36.36.6241897, JRE 1.8.0_212-release-1586-b4-5784211x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.4, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, error: type 'KeywordToken' is not a subtype of type 'List<Annotation>'
#0      AstBuilder.endFunctionTypeAlias (package:analyzer/src/fasta/ast_builder.dart:1454:24)
#1      Parser.parseTypedef (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1126:14)
#2      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:610:18)
#3      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#4      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#5      ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:159:32)
#6      ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:154:12)
#7      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:131:21)
#8      EditDomainHandler.format (package:analysis_server/src/edit/edit_domain.dart:149:35)
#9      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:378:16)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:45)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:329:50)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1502:12)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:328:5)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#47     _rootRunUnary (dart:async/zone.dart:1134:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#53     _StreamController._add (dart:async/stream_controller.dart:642:7)
#54     _StreamController.add (dart:async/stream_controller.dart:588:5)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#56     _rootRunUnary (dart:async/zone.dart:1138:13)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#60     _BufferingStreamSubscription._a...
```

For additional log information, please append the contents of
file:///private/var/folders/g3/2dqykdh53r9d3rfwxgn30wzm0000gn/T/report1.txt.

**Comment by devoncarew** [comment] 2020-03-31 17:48
It looks like this is driven by the analysis server, when running the formatter, and crashes in front end code.

**Comment by scheglov** [comment] 2020-03-31 17:55
@himeshp If this is something that happens persistently, and you by any chance have code on which it happens, I'd love to see this code (send it to `scheglov@google.com`). Obviously once I can reproduce , I will remove everything unrelated and leave just a synthetic / minimal version of the example.

**Comment by himeshp** [comment] 2020-04-01 04:40
sure thing, I will try to reproduce it and post the code here if I get the issue again. as of now things are working fine.
thanks

**Comment by srawlins** [comment] 2021-01-27 00:01
I have a good repro of this over at https://github.com/dart-lang/sdk/issues/43090.

**Comment by srawlins** [comment] 2021-01-27 00:01
Duplicate of https://github.com/dart-lang/sdk/issues/43090

**Closed by srawlins** 2021-01-27 00:01 UTC
Labels: analyzer-crash-report, area-analyzer
