### ISSUE TITLE
The "exclude" list in .analysis_options is ignored by the dartanalyzer cli

### ISSUE THREAD

**Issue by enyo** [dart-lang/sdk#25551] opened 2016-01-21 15:42 UTC
When I define excludes in my `.analysis_options` file like this:

``` yaml
analyzer:
  strong-mode: true
  exclude:
    - test/**
    - lib/generated_library/**
```

files in `lib/generated_library` are still analyzed, when they are imported by other libraries in my project.

I would expect _not_ to get strong-mode warnings or lint errors in any files excluded in the `exclude:` list

**Comment by bwilkerson** [comment] 2016-01-21 16:10
Analyzer has to analyze every file that is imported in order to know which names are and are not defined in the importing library, but you're right that errors and warnings should not be reported for explicitly excluded files.

**Comment by enyo** [comment] 2016-01-21 16:47
Exactly. The rules defined in my `.analysis_options` should not apply to excluded files, event though they need analysing.

**Comment by MikeMitterer** [comment] 2016-12-07 11:20
All my tests are red!!! I've excluded test because generic functions are not available and expectAsync produces all those "Unsound..." errors

![capturfiles-20161207_121922](https://cloud.githubusercontent.com/assets/116654/20965749/7a19c760-bc77-11e6-9458-c047a4ddb31e.png)

![capturfiles-20161207_121643](https://cloud.githubusercontent.com/assets/116654/20965662/1047aa00-bc77-11e6-9386-255910881bda.png)

**Comment by enyo** [comment] 2018-08-23 10:02
Is there an update for this? I know that there are more exciting things to do than fixing the exclude flag, but it is really annoying and there is no real solution to work around it.
This issue is now more than 2 years old, it would be great to see some work done on this.

**Comment by devoncarew** [comment] 2018-08-23 14:27
@enyo, can you attach a small project that repros this issue? We use `exclude`s ourselves in our own work, and don't see issues, but it's likely that you're hitting some problem in the implementation that we're not aware of.

**Comment by enyo** [comment] 2018-08-23 15:05
@devoncarew yes! Glad to help, I'll do it ASAP.

**Comment by enyo** [comment] 2018-08-27 11:56
@devoncarew https://github.com/exitlive/exclude_demo

**Comment by enyo** [comment] 2018-08-28 18:45
That would be great :)

**Comment by enyo** [comment] 2018-09-04 10:53
I'd like to give additional feedback on this, but it is probably a completely separate issue.

Although normally excluded files are properly excluded in IDEs (which, if I understood correctly use the server — tested on both IntelliJ and VSCode), *sometimes* excluded files reappear.
I think it's related to which file is currently open. So if you open an excluded file in your IDE, suddenly the excludes for this file are ignored.

**Comment by scheglov** [comment] 2018-09-04 16:43
When you open a file, it gets analyzed, and Analysis Server sends errors, semantic highlighting, etc to the IDE. When you close the file (so, it stops being a priority file), you should stop getting more data about this file. What is missing now is sending the empty list of errors so that IDE removed red squiggles.

**Comment by enyo** [comment] 2018-09-05 10:46
@scheglov Ah! That makes sense. Thanks

**Comment by MichaelRFairhurst** [comment] 2018-10-08 20:26
Leaving a note that this affects part files as well.

**Comment by jaumard** [comment] 2019-02-21 14:43
Is there any news on this ? 3 years it's a bit long ^^ :( 
For example if you want to force single quote with `prefer_single_quotes: error` and you're using `intl` for localization, it will generate everything with double quote and your CI will fail because it take excluded files into consideration where IDE is not :/ 

@MichaelRFairhurst didn't quite understand your message, did you have a hack around this issue ?

**Comment by jaumard** [comment] 2019-02-22 08:37
The title can be more generic as it's not just imports but all rules `The "exclude" list in .analysis_options is ignored in cli`

**Comment by Nazacheres** [comment] 2019-06-06 12:57
Any progress on that? That is actually a huge issue that cuts out half of the cases where you can use the tool. I would like to add it to CI flow, however, I can't because there are some warnings in generated files.

**Comment by jamesderlin** [comment] 2019-06-18 16:54
> It's surprisingly nontrivial to fix, but it's only an issue in analyzer_cli. So if we make the switch to use server as the backend for that, this will go away.

Could you elaborate on what the obstacles are?

**Comment by Kiruel** [comment] 2019-08-02 12:47
For me is exactly this problem https://github.com/dart-lang/sdk/issues/28754

**Comment by dnfield** [comment] 2019-09-06 22:56
Based on tips from https://github.com/dart-lang/sdk/issues/34098, I found `pub global activate tuneup`, which doesn't suffer from this (`tuneup check`).

**Comment by dnfield** [comment] 2019-09-06 23:11
Seems like this would be fixed by fixing the same underlying issue of #34098 (using the analysis server in whatever way the CLI isn't currently), and probably should just be clsoed as a duplicate.

**Comment by rowild** [comment] 2019-09-10 08:32
I tune in to those, who cannot exclude files - I have the same problem...

**Comment by creativecreatorormaybenot** [comment] 2019-09-15 20:24
In my case, the `exclude` list is not ignored in `dartanalyzer .` but in Android Studio.

**Comment by johnpryan** [comment] 2019-10-09 16:36
Here's another small project to reproduce: https://github.com/johnpryan/analyzer_exclude_bug

**Comment by PiN73** [comment] 2019-10-24 12:07
Same for Android Studio. I have `analysis_options.yaml` with
```yaml
analyzer:
  exclude:
    - lib/net.dart
    - lib/network_error.dart
    - lib/search_net.dart
    - lib/orders_net.dart
  strong-mode:
    implicit-casts: false
```
but analyzer randomly stops excluding some files
![Dart Analysis in Android Studio screenshot](https://user-images.githubusercontent.com/18294052/67483984-c0535400-f66f-11e9-8083-1b9ab4dfd1fb.png)

**Comment by bakua** [comment] 2020-01-06 14:18
> I fixed this by adding a analysis_options.yaml and relaunched the android studio.
> ![analysis_options.yaml](https://user-images.githubusercontent.com/32789220/67869533-da88a880-fb2d-11e9-8f8d-4a8eaca3fbec.png)

That actually helped me too... I got strict errors reported from json_serializable generated files and after AS restart those reports are gone.

**Comment by miguelpruivo** [comment] 2020-01-28 23:46
This should have more attention. I can't work around the rules just to not have them reporting errors on generated files. Adding linter suppressors on the file don't seem to help as well.

**Comment by orestesgaolin** [comment] 2020-03-03 10:58
Is there any update on this issue? When using code generation the analyzer often gets unusable :/

**Comment by szotp** [comment] 2020-03-27 07:58
One workaround is having two packages, and two analysis_options.yaml, one for generated code, one for manual.

**Comment by bakua** [comment] 2020-03-27 08:53
It looks like the issue is when you add exclude path that is not in quotation marks. I have config below and it works just right. Feel free to try it.

```
include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
  errors:
    missing_return: error
    missing_required_param: error
```

**Comment by orestesgaolin** [comment] 2020-03-27 09:44
> It looks like the issue is when you add exclude path that is not in quotation marks. I have config below and it works just right. Feel free to try it.
> 
> ```
> include: package:pedantic/analysis_options.yaml
> 
> analyzer:
>   strong-mode:
>     implicit-casts: false
>     implicit-dynamic: false
>   exclude:
>     - "**/*.g.dart"
>   errors:
>     missing_return: error
>     missing_required_param: error
> ```

Are you sure that it works? I've just tried and it completely ignores it and shows hundreds of errors e.g.:

```
analyzer:
  exclude:
    - "build/**"
    - "lib/generated/*"
    - "lib/icons/*"
    - "**/*.freezed.dart"
    - "**/*g.dart"
    - "*.g.dart"
    - "test/**"
    - "**/*_test.dart"
```


```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.15.3 19D76, locale pl-PL)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by rrousselGit** [comment] 2020-04-03 11:58
@bwilkerson @devoncarew 
Do we have any news on this? Is there any specific blocking point that was not communicated?

This put unnecessary stress on code-generators maintainers. Because of such an issue, we receive many requests for generating `// ignore_for_file`.

**Comment by devoncarew** [comment] 2020-04-03 15:19
cc @stereotype441 for visibility into this dartanalyzer cli issue

@rrousselGit - in an upcoming release of the Dart sdk (likely the first Dart 2.9-dev release), we'll have a new `dart analyze` command. The implementation of that is currently based on the analysis server, so won't have this issue.

**Comment by arctouch-matheusromao** [comment] 2020-06-12 05:50
`dart analyze` is working nicely 💙  Thanks guys!

```yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
```

```
 Flutter (Channel master, 1.20.0-1.0.pre.29)
 Dart version 2.9.0 (build 2.9.0-15.0.dev f043f9e5f6)
```

(AS 3.6.3, Flutter plugin 46.0.1 is still complaining about `**/*.g.dart` though)

**Comment by creativecreatorormaybenot** [comment] 2020-06-12 06:18
@arctouch-matheusromao This was also the case before, i.e. `analyze` did consider the `exclude` list but the IDE did not.

**Comment by rrousselGit** [comment] 2020-06-12 06:21
We still have the issue on Dart 2.9
The IDEs still report warnings on excluded files.

**Comment by LouisMT** [comment] 2020-07-21 18:19
It was working perfectly for me, until the latest beta. It seems to be completely removed now.

**Comment by devoncarew** [comment] 2020-07-21 18:42
Yes, sorry. The combined `dart` UI was pulled from the upcoming dart 2.9 stable (and beta) release. It's still in master and dev, and will be in the next beta, and the following stable.

There were a few issues running dart apps in some corner case use cases. These were deemed blocking in terms of shipping it in upcoming current stable release given how widespread use of the `dart` CLI tool is.

**Comment by boukeversteegh** [comment] 2020-08-02 10:47
In my case, **restarting** my IDE solved the issue.

- dart sdk `2.8.4`
- intellij `2020.1.4` (Ultimate Edition)
- intellij dart plugin `201.8538.45`

**Comment by long1eu** [comment] 2020-08-10 08:54
@arctouch-matheusromao what version of dart are you using. `dart analyze` doesn't work for me.

```
long1eu@Razvans-Mac-Pro mobile % dart --version
Dart SDK version: 2.9.0 (stable) (Fri Jul 31 10:59:48 2020 +0200) on "macos_x64"
long1eu@Razvans-Mac-Pro mobile % dart analyze  
Error: Error when reading 'analyze': No such file or directory
```

**Comment by amebrahimi** [comment] 2020-08-11 10:24
Vs-code doesn't show the excluded files but when I run the `dartanalyzer` in powershell it shows me the excluded files.

```
analyzer:

  exclude:
    - "**/*.chopper.dart"
    - "**/injection.config.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
```

**Comment by shilangyu** [comment] 2020-08-21 08:27
So:
- no feasible workaround available
- `dart analyze` doesn't exist (yet)

Am I supposed to give up on running lints in a CI? I don't see `dartanalyzer` being marked as deprecated and this is a pretty serious 3.5 year old bug :/

**Comment by adamsmaka** [comment] 2020-09-01 06:07
Seems like this code actually removes some warning from excluded files, but not all of them:

```
analyzer:
  exclude:
    - **/*.g.dart
    - **/*.freezed.dart
```
but we got a `Undefined alias` error on the first line no matter what is there 🙈

**Comment by zoechi** [comment] 2020-09-17 10:55
I still get `avoid_equals_and_hash_code_on_mutable_classes` violations from `built_value` generated files with 
```yml
analyzer:
  exclude:
    - "**/*.g.dart"
```
and `dartanalyzer.bat --options .\analysis_options.yaml .`

**Comment by shilangyu** [comment] 2020-10-02 05:46
`dart analyze` was officially released with dart 2.10. I can finally run lints in my CI 🎉🎉🎉

**Comment by dnfield** [comment] 2020-11-09 23:01
Can this be closed now that `dart analyze` is a thing?

**Comment by dnfield** [comment] 2020-11-10 00:29
I guess I have permission to close this, so I will. If someone is still having this issue, please comment to re-open, or file a more up to date bug for the current tooling.

**Comment by fzyzcjy** [comment] 2020-12-31 03:55
I also see this problem with dart 2.10.4 and latest flutter. Restarting IDE (Intellij IDEA 2020.3) solved my problem.

**Comment by sensuikan1973** [comment] 2021-02-05 01:08
on https://pub.dev, dartanalyzer is used for now.
Is this going to be changed to `dart analyze` ?

**Comment by devoncarew** [comment] 2021-02-05 15:58
> on https://pub.dev, dartanalyzer is used for now.
> Is this going to be changed to `dart analyze` ?

Good question! @jonasfj - is it feasible to switch pub.dev over to using `dart analyze`?

**Comment by jonasfj** [comment] 2021-02-05 16:06
Filed https://github.com/dart-lang/pana/issues/828, I don't know if there is any issues.. We might want to pass custom options from a different folder.

**Comment by devoncarew** [comment] 2021-02-05 16:17
Gotcha; let me know if you hit any blockers.

Passing custom options isn't currently supported and might not be a super common case. It should be possible to pre-process a project's analysis options file to reference the preferred options settings. You'd probably want to do things like preserve the excludes from an existing options file.

**Comment by jonasfj** [comment] 2021-02-05 17:18
Or we might just have to use `package:analyzer` :see_no_evil:, ideally we don't modify files in disk.

Let me know if there is any pressure to migrate soon.

**Comment by Skycoder42** [comment] 2021-02-05 19:06
As far as I know, dart analyze does currently not support machine readble output.

**Comment by PiN73** [comment] 2021-04-23 15:52
`exclude` still not works on Windows.

## Reproduction steps
- Create new Flutter application
- Create file lib/test.g.dart with contents:
```dart
int _tmp = 0;
```
- Create file analysis_options.yaml with contents:
```yaml
analyzer:
  exclude:
    - "lib/**/*.g.dart"
```

## Expected results
Dart Analysis tab reports no problems

## Actual results
Dart Analysis tab reports problem in test.g.dart file:

![](https://user-images.githubusercontent.com/18294052/115896133-c3492380-a463-11eb-86f8-a63f29f5dabf.png)

## Environment

I face this bug on **Windows**. On macOS `exclude` works properly.

<details>
<summary>flutter doctor & versions</summary>

```
>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.867], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (2 available)

• No issues found!

>flutter --version
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (7 days ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

Android Studio with Flutter plugin 55.1.1, Dart plugin 201.9335

Same in VSCode with FLutter plugin v3.17.0, Dart plugin v3.17.1
</details>

**Comment by llucax** [comment] 2021-05-06 21:07
> Can this be closed now that dart analyze is a thing?

This is not fixed in `dartanalyzer` and there is still tooling using that. `dart analyze` is not always an option either, because it doesn't provide the `--format=machine` option for example.

**Comment by enyo** [comment] 2021-06-20 09:47
Everything was working fine, until I upgraded To dart 2.13. Now all excludes in my `analysis_options.yaml` file are being ignored again :(

**Comment by enyo** [comment] 2021-06-20 09:50
@dnfield I'm afraid this needs to be reopened

**Comment by lejard-h** [comment] 2021-06-23 07:28
Same issue after upgrading to 2.13

**Comment by spkersten** [comment] 2021-06-24 15:07
We're also seeing this issue after upgrading to Dart 2.13. We have three/four layers of `analysis_options.yaml` which each include the next one. I could work around this issue by add
```
exclude:
    - "**/*.g.dart"
```
in a different layer.

**Comment by enyo** [comment] 2021-06-25 18:40
> We're also seeing this issue after upgrading to Dart 2.13. We have three/four layers of `analysis_options.yaml` which each include the next one. I could work around this issue by add
> 
> ```
> 
> exclude:
> 
>     - "**/*.g.dart"
> 
> ```
> 
> in a different layer.

Could you be a bit more specific? Where did you add the exclude for it to work?

**Comment by enyo** [comment] 2021-06-26 15:29
Ok, so I was able to find a solution to, thanks to @spkersten .

I too was using multiple `analysis_options.yaml` files, and I was excluding a specific directory as well (instead of only `**/*.g.dart`). To make sure that the directory was properly excluded I needed to also adapt the path to the excluded directory, relative to the different `analysis_options.yaml` files.

**Comment by pruthvi145** [comment] 2021-07-03 06:40
@enyo can you explain the solution? I am using the [lint](https://pub.dev/packages/lint) package (Thus, I am also using the layers of `analysis_options.yaml`). I have excluded the file from my project but it is not working!

**Comment by spkersten** [comment] 2021-07-03 06:59
@pruthvi145 I think the issue @enyo and I encountered is that excludes that start with path (e.g., `lib/*.g.dart`) are only matched against paths in the same directory as the analysis_options.yaml that declares them. So if you include such an analysis_options.yaml from another directory, those excludes don't do anything. A workaround for that is to not use that kind of exclude but instead something like `"**/*.g.dart"`; or to move the excludes to the top-level analysis_options.yaml. 

I don't see any excludes in the lint packages, so I'm not sure you're experiencing the same problem.

**Comment by pruthvi145** [comment] 2021-07-03 08:08
@spkersten Right! can you help me to figure out my issue?

**Here is my `analysis_options.yaml` rules:**

![image](https://user-images.githubusercontent.com/43115036/124347461-969f4e00-dc02-11eb-84e6-f107aa96eba1.png)

According the rules, the file `lib/common/pulse_icons.dart` should be excluded but dart analyzer is not ignoring that file.
**Here is my VSCode's output**:

![image](https://user-images.githubusercontent.com/43115036/124347545-e41bbb00-dc02-11eb-8687-c17e6cdd6cf1.png)

**Here is the output of the `dart analyze`:**

![image](https://user-images.githubusercontent.com/43115036/124347634-4bd20600-dc03-11eb-8661-245ec8df162f.png)

At both the places, it seems like `exclude` is not affecting to the `analyzer` can anyone explain the behaviour of it? why it is happening? Am I missing something?

**Comment by 2shrestha22** [comment] 2021-08-07 08:22
`flutter analyze` and `dart analyze` is the most useless things. It makes no sense if we can't control which files we to include or exclude. There are dozens of issues about this and all closed without proper solution.

**Comment by lejard-h** [comment] 2021-08-31 12:45
Thanks @scheglov It fix my issue !

Don't know if it the same for everyone

**Comment by RyosukeOK** [comment] 2021-09-04 12:04
In my case, it was due to brackets `( )`in parent folder name.
When I removed it, `exclude` worked.

**Comment by mit-mit** [comment] 2021-10-11 14:55
`dart analyze` is the current workaround for this issue. If anyone has any things they are missing in `dart analyze` which is causing them to still use `dartanalyzer` and hit the present issue, please let us know as `dartanalyzer` is scheduled for eventual deprecation.

**Comment by srawlins** [comment] 2022-03-29 01:03
Closing this for now, as `dartanalyzer` is now scheduled for removal soon.

**Closed by srawlins** 2022-03-29 01:03 UTC
Labels: area-analyzer, P2, type-bug

**Comment by thipokch** [comment] 2023-01-29 05:11
I'm using `dart analyze` and it's still not working for me. Is this issue reproducible by anyone else?
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale
    en-US)
    • Flutter version 3.3.10 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.3.10/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
```

**Comment by ptheofan** [comment] 2023-03-20 00:46
Would be great to fix the `excluded` option as my `README.md` gets errors on every commit when it's touched.
