### ISSUE TITLE
Trailing comma in assert statement doesn't work

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#29959] opened 2017-06-21 00:09 UTC
Asserts look like regular function calls, so this is a natural way to express them:

```dart
  assert(
    condition,
    'message',
  );
```

Unfortunately, this isn't valid, because of the final comma.

**Comment by rmacnak-google** [comment] 2017-06-21 00:53
VM: https://codereview.chromium.org/2946173002/

**Comment by lrhn** [comment] 2017-06-21 07:44
The language specification doesn't allow a comma there. It is not a function call, it's a separate syntactic construct that looks like a function call (much to my personal annoyance).

We should probably allow a trailing comma for consistency, but it's not specified as that (yet).

**Comment by lrhn** [comment] 2017-06-23 09:53
Duplicate of #28786

**Comment by lrhn** [comment] 2017-06-28 10:38
We've decided to allow trailing commas in asserts, like we do for function declarations and calls.
The specification has been updated (it just allows `,` grammatically and says that it's equivalent to an assert without the comma, so the change is really minor).

**Comment by bwilkerson** [comment] 2017-06-28 15:05
https://codereview.chromium.org/2961063002/ for analyzer support

**Comment by bwilkerson** [comment] 2017-09-15 17:49
Added support in front_end in https://dart-review.googlesource.com/c/sdk/+/3320.

**Comment by eernstg** [comment] 2017-11-14 08:58
The language specification has had this feature ("allow trailing comma in assert") as of c68e5cc67d4b3aefc4e287884b35f90a2550602b, so we can close this issue considered as an 'area-language'.

Along the way the analyzer got this feature, as mentioned above, so there's an implicit 'area-analyzer' in this issue as well. But both CLs mentioned above have been committed. So I'll close this issue.

One remaining issue is that the analyzer doesn't support trailing commas in asserts _in initializer lists_, which is reported separately, as issue #31320.

**Closed by eernstg** 2017-11-14 08:58 UTC
Labels: area-language, Type: enhancement
