### ISSUE TITLE
analysis_options.yaml interacts weirdly with DDC

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/sdk#30421] opened 2017-08-11 13:15 UTC
I notice that if I have this in my analysis_options.yaml:

```
analyzer:
  strong-mode:
    implicit-casts: false
```

then suddenly I can't compile with DDC because some of my _dependencies_ don't meet this requirement:

```
$ pub serve
...
Error compiling dartdevc module:quiver|lib/lib__collection.js

[error] The initializer type 'dynamic' can't be assigned to the field type 'int'. (package:quiver/src/collection/lru_map.dart, line 67, col 24)
<lots more>
Please fix all errors before compiling (warnings are okay).
```

This is 1) very surprising, 2) a problem for switching from Dartium to DDC -- it means I can't set 'implicit-casts: false' for my code without fixing e.g. package:quiver and package:collection first.

Any suggestions please? I guess the right fix would be to make DDC fail on a consistent set of errors, irrespective of analysis_options.yaml?

Edit: was trying this on https://github.com/google/built_value.dart/tree/master/chat_example

**Comment by anders-sandholm** [comment] 2017-08-11 13:59
Seems to be a duplicate of #29713

**Closed by anders-sandholm** 2017-08-11 13:59 UTC
Labels: Resolution: duplicate
