### ISSUE TITLE
Dart analyser error

### ISSUE THREAD

**Issue by BalaCandy** [dart-lang/sdk#35835] opened 2019-02-02 12:30 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.1.0-dev.9.4`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\andro\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: E:\Projects\flutter\flutter_redux_projects\farm_mojo_new\lib\localization.dart
NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      FileState.isPart (package:analyzer/src/dart/analysis/file_state.dart:220:32)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1192:30)
<asynchronous suspension>
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1050:39)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#6      new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#7      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#8      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#9      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)

**Comment by stereotype441** [comment] 2019-02-05 16:05
Duplicate of #35606

**Closed by stereotype441** 2019-02-05 16:05 UTC
Labels: area-analyzer
