### ISSUE TITLE
Running Flutter Gallery from Kernel fails unless disable causal-async-stacks

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30178] opened 2017-07-17 16:31 UTC
Unless disable causal-async-stacks, running Flutter dill files on the devices fails again because https://codereview.chromium.org/2936793003/ for original dartbug.com/30058 got reverted.

Running flutter app dill in debug mode with '--causal-async-stacks' results in the following error produced during runtime:
```
I/flutter (19066): The following assertion was thrown building Title("Flutter Galllery"; color: MaterialColor(primary
I/flutter (19066): value: Color(0xff9e9e9e)); dirty):
I/flutter (19066): type 'int' is not a subtype of type 'Function' of 'async_op' where
I/flutter (19066):   int is from dart:core
I/flutter (19066):   Function is from dart:core
I/flutter (19066): 
I/flutter (19066): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (19066): more information in this error message to help you determine and fix the underlying cause.
I/flutter (19066): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (19066):   https://github.com/flutter/flutter/issues/new
I/flutter (19066): 
I/flutter (19066): When the exception was thrown, this was the stack:
I/flutter (19066): #0      _asyncStackTraceHelper (dart:async)
I/flutter (19066): #1      SystemChrome.setApplicationSwitcherDescription (package:flutter/src/services/system_chrome.dart)
I/flutter (19066): #2      Title.build (package:flutter/src/widgets/title.dart:33:18)
I/flutter (19066): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3489:28)
...
```

**Comment by mraleph** [comment] 2017-07-17 16:53
Isn't this a duplicate of #30058?

**Closed** 2017-07-17 18:58 UTC
Labels: area-kernel
