### ISSUE TITLE
[Feature] Support enum methods

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [dart-lang/sdk#45880] opened 2021-05-01 13:54 UTC
The title may be misleading but not sure what this is called 🙈.

For example, if I want to use an enum as part of my data classes I have to create global methods to convert the enum value to a string and then a string to an enum value.

I believe this will make using enums a lot easier.

Now:
```dart
enum FlutterChannel {
  dev,
  beta,
  stable,
}

String convertFlutterChannelEnumToString(FlutterChannel flutterChannel) {
  switch (flutterChannel) {
    case FlutterChannel.dev:
      return "dev";
    case FlutterChannel.beta:
      return "beta";
    case FlutterChannel.stable:
      return "stable";
    default:
      return "stable";
  }
}

FlutterChannel convertStringToFlutterChannelEnum(String flutterChannelString) {
  switch (flutterChannelString) {
    case "dev":
      return FlutterChannel.dev;
    case "beta":
      return FlutterChannel.beta;
    case "stable":
      return FlutterChannel.stable;
    default:
      return FlutterChannel.stable;
  }
}
```

Proposed:
```dart
enum FlutterChannel {
  @override
  List<dynamic> get values => <dynamic>[
    dev,
    beta,
    stable,
  ];

  factory FlutterChannel.fromString(String flutterChannelString) {
    switch (flutterChannelString) {
      case "dev":
        return FlutterChannel.dev;
      case "beta":
        return FlutterChannel.beta;
      case "stable":
        return FlutterChannel.stable;
      default:
        return FlutterChannel.stable;
    }
  }

  String toString(FlutterChannel flutterChannel) {
    switch (flutterChannel) {
      case FlutterChannel.dev:
        return "dev";
      case FlutterChannel.beta:
        return "beta";
      case FlutterChannel.stable:
        return "stable";
      default:
        return "stable";
    }
  }
}
```

**Comment by DevNico** [comment] 2021-05-03 05:58
The proposed code feels really ugly to me and I don't really see the benefits of adding such a feature. You can just write functions like:
```dart
T? enumFromString<T>(List<T> values, String value) {
  return values.firstWhereOrNull((v) => v.toString().split('.')[1] == value);
}

String enumToString(Object e) => e.toString().split('.')[1];
```
Usage:
```dart
enum Test { a }

void main() {
  final a = enumFromString(Test.values, enumToString(Test.a));
}
```

**Comment by lrhn** [comment] 2021-05-03 07:48
Duplicate of https://github.com/dart-lang/language/issues/1570
This is a language feature, so keeping the request in the language repo.

**Closed by lrhn** 2021-05-03 07:48 UTC
