### ISSUE TITLE
Implement mixin declarations in CFE

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#34580] opened 2018-09-25 18:02 UTC
Consider the following code:
```dart
abstract class I {}
mixin M on I {
  void g() {
    print('m.g() called');
  }
}
class B {}
class C = B with M;
main() {
  new C().g();
}
```

The front end accepts this code without complaint:
```
$ sdk/bin/dart ~/tmp/test.dart
m.g() called
```
Whereas the analyzer rejects it:
```
$ sdk/bin/dartanalyzer ~/tmp/test.dart
Analyzing /usr/local/google/home/paulberry/tmp/test.dart...
  error • The class doesn't implement the required class 'I' at /usr/local/google/home/paulberry/tmp/test.dart:8:18 • mixin_application_not_implemented_interface
1 error found.
```

The mixin informal specification (https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) says (emphasis in original):

> Mixin application semantics is mostly unchanged, except that it's a compile-time error to apply a mixin to a class that doesn't implement *all* the `on` type requirements of the mixin declaration...

So I believe it is correct to issue a compile-time error, since class `C` applies the mixin `M` to the class `B`, but `B` does not implement `I`, which is one of the `on` type requirements of `M`.

@lrhn can you confirm that my reading of the spec is correct?

**Comment by lrhn** [comment] 2018-09-26 08:42
Agree. The `M` mixin must only be applied to super-classes that implements `I`.

**Comment by kmillikin** [comment] 2018-09-26 11:07
It's a known issue because we haven't implemented it yet.  In the implementation plan at https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md, we are working on Phase 1.

You can't expect things to work before they're implemented!

**Comment by kmillikin** [comment] 2018-09-27 10:01
Status: there are some bugs in mixin type inference.  Super calls are not yet allowed in mixin declarations except for the VM target.  There are no static checks on mixin applications.

https://dart-review.googlesource.com/c/sdk/+/76141 will allow super calls in mixin declarations for all targets and fix some of the issues with mixin type inference.

**Comment by kmillikin** [comment] 2018-10-02 15:27
Duplicate of #34165.

**Comment by stereotype441** [comment] 2018-10-02 17:56
Reopening since the code snippet at the top of the bug report still produces the wrong behavior in the front end as of 097e8d86b85af03ba59d966d46a1010f9c40fdf5:
```
paulberry@paulberry-linux-2:~/dart-new/sdk$ sdk/bin/dartanalyzer ~/tmp/test.dart
Analyzing /usr/local/google/home/paulberry/tmp/test.dart...
  error • The class doesn't implement the required class 'I' at /usr/local/google/home/paulberry/tmp/test.dart:8:18 • mixin_application_not_implemented_interface
1 error found.
paulberry@paulberry-linux-2:~/dart-new/sdk$ sdk/bin/dart ~/tmp/test.dart
m.g() called
```

@kmillikin, if this is being tracked elsewhere, feel free to re-close this bug and point me to the relevant issue

**Closed** 2018-10-02 18:17 UTC
Labels: area-front-end, p2-medium, type-enhancement
