### ISSUE TITLE
pkg/dartdev/test/commands/info_macos_test fails with RuntimeError on pkg-mac-release-arm64

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#52402] opened 2023-05-15 15:38 UTC
There are new test failures on [[flow analysis] clean up public methods that call other public methods.](https://github.com/dart-lang/sdk/commit/214a98e1dd29c2a3aeef2b9b2d6bb2f053df24bf).

The tests
```
pkg/dartdev/test/commands/info_macos_test RuntimeError (expected Pass)
```
are failing on configurations
```
unittest-asserts-release-mac-arm64
```

Although the blamelist indicates that the test started failing at 214a98e1dd29c2a3aeef2b9b2d6bb2f053df24bf, it's very difficult to imagine a way this commit could have provoked the failure, since the commit is a small refactor to flow analysis, and the failure is related to dartdev's `ProcessInfo.commandLine` getter returning an unexpectedly trimmed string.

If I had to guess, I suspect some change was made to the configuration of the trybot (e.g. an OS upgrade perhaps) that changed the way the process information appears when querying for processes on a mac.

CC @devoncarew

**Comment by devoncarew** [comment] 2023-05-15 15:55
Test failure output:

```
00:00 [32m+0[0m: process listing macos[0m

00:00 [32m+0[0m[31m -1[0m: process listing macos [1m[31m[E][0m[0m

  Expected: a string starting with 'dart'
    Actual: 'analysis_server.dart.snapshot --suppress-analytics --client-id=dart-fix --disable-server-feature-completion --disable-server-feature-search --sdk <path>/dart-sdk'
  

  package:matcher/src/expect/expect.dart 149:31        fail
  package:matcher/src/expect/expect.dart 144:3         _expect
  package:matcher/src/expect/expect.dart 56:3          expect
  pkg/dartdev/test/commands/info_macos_test.dart 24:9  main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 215:19    Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7     Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9      Invoker._waitForOutstandingCallbacks.<fn>
  

00:00 [32m+0[0m[31m -1[0m: process listing parseMacos[0m

00:00 [32m+1[0m[31m -1[0m: info macos shows process info[0m
```

**Comment by sstrickl** [comment] 2023-05-30 08:16
Same test failure as above ([log](https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/8261/pkg/dartdev/test/commands/info_macos_test)):
```
stdout:
00:00 [32m+0[0m: process listing macos[0m

00:00 [32m+0[0m[31m -1[0m: process listing macos [1m[31m[E][0m[0m

  Expected: a string starting with 'dart'
    Actual: 'analysis_server.dart.snapshot --suppress-analytics --client-id=dart-fix --disable-server-feature-completion --disable-server-feature-search --sdk <path>/dart-sdk'
  

  package:matcher/src/expect/expect.dart 149:31        fail
  package:matcher/src/expect/expect.dart 144:3         _expect
  package:matcher/src/expect/expect.dart 56:3          expect
  pkg/dartdev/test/commands/info_macos_test.dart 24:9  main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 215:19    Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7     Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9      Invoker._waitForOutstandingCallbacks.<fn>
  

00:00 [32m+0[0m[31m -1[0m: process listing parseMacos[0m

00:00 [32m+1[0m[31m -1[0m: info macos shows process info[0m

00:00 [32m+2[0m[31m -1[0m: [31mSome tests failed.[0m
```

**Comment by devoncarew** [comment] 2023-06-13 16:10
Looking at this now -

**Comment by joshualitt** [comment] 2023-06-26 18:08
I think I may have also triggered this on a recent commit(https://dart-review.googlesource.com/c/sdk/+/307961). Approving the failure for now.

**Comment by nshahan** [comment] 2023-07-06 17:27
This test just started failing again on one of my unrelated changes with the same ` process listing macos` failure shown above.

**Comment by aam** [comment] 2023-07-06 22:01
Duplicate of https://github.com/dart-lang/sdk/issues/52658

**Closed by aam** 2023-07-06 22:01 UTC
Labels: area-pkg, area-dart-cli, pkg-dartdev
