### ISSUE TITLE
Analyzer doesn't warn when `rethrow` is used in a closure in a catch clause

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/sdk#48502] opened 2022-03-03 08:39 UTC
Consider the below (contrived) example.

If a closure is used in the catch clause and uses `rethrow`, no analyzer error is presented while the program fails.

What adds to the confusion is that if you use `throw e` instead the linter presents a message to change it to `rethrow`. _(Should this be reported somewhere else?)_

```dart
void main() {
  try {
    try {
      throw Error();
    } catch (e) {
      (() {
        // false analyzer info message with 'use_rethrow_when_possible'
        throw e;
      })();
    }
  } catch (e) {
    (() {
      // no analyzer warning
      rethrow;
    })();
  }
}
```

`Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"`

**Comment by lrhn** [comment] 2022-03-03 13:31
The specification is actually not very precise here. It says:
```latex
It is a compile-time error if a \code{\RETHROW} statement is not
enclosed within an \ON-\CATCH{} clause.
```

We have so far interpreted that to mean *inside the same function*. That's not a given.
We could allow the code above to work (it'd capture the caught error and stack in the closure, and rethrow them when called, even if the closure escapes the `catch` clause.)

The spec also says about the `rethrow`:
```latex
Let $f$ be the immediately enclosing function,
and let \code{\ON{} $T$ \CATCH{} ($p_1$, $p_2$)}
be the immediately enclosing catch clause (\ref{try}).
```
and then goes on to never refer to *f* again (that's probably my own fault).

Anyway, the spec is ambiguous, the implementations assumes it works in one way, the analyzer assumes another way, I'm probably the closest to knowing the intent since I reviewed the original spec on throwing and `rethrow`, and later rewrote it to use the newer "complete/throws" phrasing, and I'm fairly sure the `rethrow` was intended to be a statement inside the `catch` block, not inside a nested function. (The original text referenced the "most recently caught value", rather than doing it by name, which means it would not be safe for the closure to escape the `catch` clause. Q.v. https://codereview.chromium.org/498873003/patch/100001/110001)

Changing the analyzer does sound easier than changing the other implementations into something which is likely more complicated, so I'm tentatively marking as an analyzer bug.

@eernstg

**Comment by scheglov** [comment] 2022-03-03 20:12
https://dart-review.googlesource.com/c/sdk/+/235170

**Closed** 2022-03-03 21:51 UTC
Labels: area-analyzer, type-bug

**Comment by eernstg** [comment] 2022-03-04 10:38
Agreed, that spec section should be clarified; it's one of those sections that we haven't updated for a long, long time. Cf. https://github.com/dart-lang/language/pull/2139.
