### ISSUE TITLE
Autocomplete needs to be triggered multiple times to (sometimes) work

### ISSUE THREAD

**Issue by benjamincombes** [dart-lang/sdk#50388] opened 2022-11-04 16:10 UTC
## Steps to Reproduce

Since a few versions, autocomplete is not reliable at all, extremely slow, and makes using Android Studio extremely complicated. To reproduce it :
- for example, type the beginning of the name of a widget that is in the project. I will have "No suggestions" many times, and sometimes it ends up proposing to complete the term, sometimes no, and I have to type it manually...
- when the name of the widget has been fully entered, I need to trigger autocomplete shortcut many times before the IDE proposes to import it. It can be up to 10 seconds per import, but sometimes it never works

This behavior happens nearly all the time and getting worse and worse, making it really hard to work with Android studio. You can check it in the enclosed video.

## Version info

[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-FR)
    • Flutter version 3.3.6 on channel stable at /Users/benjamincombes-work/Library/Google/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (3 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/benjamincombes-work/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = ~/Library/Android/sdk/
    • Java binary at: /Users/benjamincombes-work/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-14.0.0-Release.Candidate.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/benjamincombes-work/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 12 mini (mobile) • D1C3CF8E-048A-4D77-8E99-61859CA478D0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

https://user-images.githubusercontent.com/138637/198558386-24843964-e448-4a00-b798-3e4c6b2a8d02.mov

**Comment by stevemessick** [comment] 2022-11-04 16:51
@srawlins This is a duplicate of one of the issues I linked to in #50372. Prior to creating that issue I had asked people to create new issues here.

**Closed** 2022-11-08 16:54 UTC
Labels: area-analyzer, analyzer-completion, type-performance, P2
