### ISSUE TITLE
Dart Analyzer Crashing in VsCode and Android Studio

### ISSUE THREAD

**Issue by AppleEducate** [dart-lang/sdk#35536] opened 2019-01-02 13:25 UTC
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

(please describe what you were doing when this exception occurred)

### Versions

- Flutter SDK 1.1.5-pre.37
- Visual Studio Code 1.30.1
- Dart Code 2.21.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/developer/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.21.1
```

### Exception

Analysis failed: /Users/developer/Github/plugins/packages/native_widgets/lib/layout/device_class.dart context: exception_20190102_082356_344

```text
Element mismatch in /Users/developer/Github/plugins/packages/native_widgets/lib/layout/device_class.dart at class NativeLayout extends StatelessWidget
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:594:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:7)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:114:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:88:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:87:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1430:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#12     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2114:24)
<asynchronous suspension>
#13     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2055:5)
#14     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#15     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#16     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#17     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#23     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#24     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#25     main (file:///b/rr/tmpMrgsBn/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#26     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#27     main (file:///b/rr/tmpMrgsBn/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#28     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Caused by RangeError (index): Invalid value: Not in range 0..7, inclusive: 8
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1461:43)
#2      ExprBuilder._createReference (package:analyzer/src/summary/expr_builder.dart:536:40)
#3      ExprBuilder._pushReference (package:analyzer/src/summary/expr_builder.dart:799:11)
#4      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:213:11)
#5      _UnitResynthesizer._buildConstExpression (package:analyzer/src/summary/resynthesize.dart:1594:47)
#6      _UnitResynthesizer.buildAnnotation (package:analyzer/src/summary/resynthesize.dart:1248:28)
#7      SummaryResynthesizerContext.buildAnnotation (package:analyzer/src/summary/resynthesize.dart:417:30)
#8      ElementImpl._buildAnnotations (package:analyzer/src/dart/element/element.dart:3182:34)
#9      ExecutableElementImpl.metadata (package:analyzer/src/dart/element/element.dart:3755:11)
#10     DeclarationResolver.resolveMetadata (package:analyzer/src/generated/declaration_resolver.dart:733:49)
#11     DeclarationResolver.visitMethodDeclaration (package:analyzer/src/generated/declaration_resolver.dart:366:5)
#12     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7724:49)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8351:20)
#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:691:10)
#16     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:87:13)
#17     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:541:13)
#18     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:86:5)
#19     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8351:20)
#21     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#22     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:715:10)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#24     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:12)
#25     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:594:31)
#26     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:7)
#27     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#28     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:114:11)
#29     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:88:14)
#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#31     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:87:43)
#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1430:63)
#33     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1409:20)
#35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1203:17)
<asynchronous suspension>
#36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2114:24)
<asynchronous suspension>
#37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2055:5)
#38     new AnalysisServer (package:analysis_server/src/analysis_server.dart:236:29)
#39     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#40     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#41     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:519:21)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:585:12)
#47     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:517:7)
#48     Driver.start (package:analysis_server/src/server/driver.dart:414:7)
#49     main (file:///b/rr/tmpMrgsBn/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#50     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#51     main (file:///b/rr/tmpMrgsBn/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#52     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#53     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/developer/Github/plugins/packages/native_widgets/example",
        "explicitFileCount": 8,
        "implicitFileCount": 704,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "/Users/developer/Github/plugins/packages/native_widgets",
        "explicitFileCount": 41,
        "implicitFileCount": 646,
        "workItemQueueLength": 40,
        "cacheEntryExceptions": []
    }
]
```

**Comment by stereotype441** [comment] 2019-01-04 17:09
Duplicate of #35535

**Closed by stereotype441** 2019-01-04 17:09 UTC
Labels: area-analyzer
