### ISSUE TITLE
Type inference: error-causing replacement node doesn't become invalid

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#35630] opened 2019-01-11 10:56 UTC
When a node is replaced by a different node during type inference, and the replacement node is then involved in an error condition (such as a type error), the erroneous node is kept in the tree, rather than being replaced by an invalid node, as it should.

For example, consider this program (with set literals enabled):
```dart
List<int> top = {};

main() {
  List<int> local = {};
  top = {};
  local = {};
  print(top);
  print(local);
}
```
The initializer of the local variable gets correctly replaced by an invalid node, but all of the other three assignments keep the set literal.

This issue causes the front-end test `strong/inference/infer_from_complex_expressions_if_outer_most_value_is_precise` to fail, as it is expecting the invalid node.

**Comment by kmillikin** [comment] 2019-01-11 11:52
This is a basic flaw in the Kernel shadow nodes.  They have apparent "children" that are not really children of the shadow node in the sense the the child's parent pointer is the shadow node.  Once we begin doing parent-based rewriting of the tree during type inference, we cannot safely use these shadow node "children" because they are stale.

A while ago I added a [comment](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/kernel_shadow_ast.dart#L413):

```dart
        // Do not use rhs after this point because it may be a Shadow node
        // that has been replaced in the tree with its desugaring.
```
There should be an identical comment just before [this line](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/src/fasta/kernel/kernel_shadow_ast.dart#L445):

```dart
      // Do not use rhs after this point because it may be a Shadow node
      // that has been replaced in the tree with its desugaring.
      var replacedRhs = inferrer.ensureAssignable(
          writeContext, rhsType, rhs, writeOffset,
          isVoidAllowed: writeContext is VoidType);
      _storeLetType(inferrer, replacedRhs ?? rhs, rhsType);
```
where the problem is that there are two occurrences of `rhs` after that.

**Comment by kmillikin** [comment] 2019-01-11 12:55
(I should add that that comment is misleading.  It is not only shadow nodes that are rewritten as part of type inference.)

**Comment by johnniwinther** [comment] 2019-10-25 10:44
Seems to be fixed now.

**Closed by johnniwinther** 2019-10-25 10:44 UTC
Labels: area-front-end
