### ISSUE TITLE
Flaky crash in test.py

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#31601] opened 2017-12-11 10:40 UTC
Error message:
```SetNativeInstanceField in SetFile() failed
Dart_SetNativeInstanceField: invalid index 0 passed in to set native instance field
step returned non-zero exit code: 255
```

Failing Bot: `https://build.chromium.org/p/client.dart/builders/analyzer-mac10.11-release-strong-be/builds/5347`

**Comment by mraleph** [comment] 2017-12-11 11:17
Duplicate of #30990

**Closed by mraleph** 2017-12-11 11:17 UTC
Labels: area-infrastructure
