### ISSUE TITLE
[Extension Type] Redeclared operator returns representation type instead of extension type.

### ISSUE THREAD

**Issue by chris-NR** [dart-lang/sdk#55129] opened 2024-03-07 11:16 UTC
Dart Version 3.3.0
```
extension type Foo(double d) implements double {
  Foo operator +(Foo other) => Foo(d + other.d); //<-- redeclaration
  Foo get clipped => d <= 3.0 ? this : Foo(3.0);
}

void main() {
  final bar1 = Foo(1.0);
  final bar2 = bar1.clipped;
  final bar3 = bar2.clipped;
  final bar4 = bar1 + bar2 + bar3; //<-- bar4 is a double!

  final bar5 = bar4.clipped; //error
  final bar6 = (bar1 + bar2).clipped; //error
}
```
The redeclared operator is defined as producing type Foo but in fact returns type double.

**Comment by eernstg** [comment] 2024-03-07 12:53
Good catch! It's a known issue, though: https://github.com/dart-lang/language/issues/3203.

The surprising typing as `double` comes up because there is a special case rule about the type of number related operators that relies on being a subtype of `num` or `double` or `int`, specifying that the type of an expression like `a + b` is `double` or `int` in a way which is more precise (for plain number types!) than the typing that we would get by looking at the operator signature alone. For example, `2 + 2` has the type `int`, even though operator `+` of `int` has return type `num`.

The problem is that we shouldn't use those exceptional typing rules when the receiver is an extension type that declares its own signature for `+`, even though that extension type may be a subtype of `int` or `double`.

Here is a version that doesn't use `+`, which allows us to get the straightforward typing that one might expect:

```dart
// ignore_for_file: unused_local_variable

extension type Foo(double d) implements double {
  Foo operator <<(Foo other) => Foo(d + other.d); //<-- redeclaration
  Foo get clipped => d <= 3.0 ? this : Foo(3.0);
}

void main() {
  final bar1 = Foo(1.0);
  final bar2 = bar1.clipped;
  final bar3 = bar2.clipped;
  final bar4 = bar1 << bar2 << bar3; // `bar4` is a `Foo`.

  final bar5 = bar4.clipped; //error
  final bar6 = (bar1 << bar2).clipped; // OK.
}
```

This will be corrected, you can follow https://github.com/dart-lang/language/issues/3203 in order to know when and how. You could also vote for that issue!

For now, I'd recommend that you consider omitting `implements double` and introduce declarations of all the operators that you need (they would then just be forwarding declarations that invoke the `double` members of the representation object). This is more verbose, but it has the right semantics (because it is no longer true that your extension type is a subtype of `double` or any other number type).

**Comment by lrhn** [comment] 2024-03-07 14:24
It seems this bug in the analyzer has been fixed, it's not reported when using the beta or main channels on dartpad.dev.
(I can't find the CL that changed it, at least not just by trying to guess keywords to grep the `git log` for.)

**Comment by scheglov** [comment] 2024-03-07 17:40
Probably this one f620836be20d42ee7a5979a31489df612fa5134e.

**Comment by lrhn** [comment] 2024-03-08 14:43
Ack. Then I'll expect it to be in the next release, which is 3.4.

(Let's consider if we can get it into a patch release if possible, since users are already tripping over it. I don't know where we are in the release schedule right now.
 @itsjustkevin )

**Comment by itsjustkevin** [comment] 2024-03-08 17:51
Thanks for calling this out @lrhn. This fix is present in the beta channel, if we want to get it into a hotfix, we would need someone to request it to be cherry-picked into stable to get it on the next train out.

**Comment by bwilkerson** [comment] 2024-03-13 16:36
It sounds like the bug has been fixed, so I'm going to close this issue. If I'm misunderstanding the situation, please re-open the issue.

**Closed by bwilkerson** 2024-03-13 16:36 UTC
Labels: area-analyzer
