### ISSUE TITLE
我也不知道这是什么错误，，，IDEA自动弹窗然后我点击跳到这里的，里面的错误也是自动填上去的，有空的就看看吧。我也不知道严不严重

### ISSUE THREAD

**Issue by RoryHyman** [dart-lang/sdk#38851] opened 2019-10-12 03:18 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#22     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5695:15)
#23     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3732:14)
#24     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#25     Parser.parseIfStatement (package:front_end/src/fasta/parser/parser.dart:5405:13)
#26     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3750:14)
#27     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#28     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#29     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#30     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#31     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#32     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#33     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#34     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#35     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#36     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#37     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#38     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#39     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#40     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#41     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#42     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#43     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#44     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#45     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#46     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#47     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#48     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#49     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _runZoned (dart:async/zone.dart:1516:10)
#53     runZoned (dart:async/zone.dart:1463:12)
#54     Driver._captureExcepti...
```

For additional log information, please append the contents of
file:///private/var/folders/ml/bm5knbcx7xd9z3ff8vrh_3mm0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-10-22 04:47
This has now been reproduced in fuzz testing; please follow https://github.com/dart-lang/sdk/issues/39035.

**Comment by srawlins** [comment] 2019-10-22 04:47
Duplicate of https://github.com/dart-lang/sdk/issues/39035

**Closed by srawlins** 2019-10-22 04:47 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
