### ISSUE TITLE
dart2js breaks in recent 1.24 stable build

### ISSUE THREAD

**Issue by sircco** [dart-lang/sdk#29905] opened 2017-06-16 05:47 UTC
works fine in latest stable dartium 

ubunutu 16.10 x64
Dart VM version: 1.24.1 (Wed Jun 14 14:48:10 2017) on "linux_x64"

web/packages/listshine/dragula/dragula_raw.dart:54:1:
The compiler crashed when compiling this element.
class Drake {
^^^^^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on listshine|web/main.dart threw error: RangeError (index): Invalid value: Valid value range is empty: 0
dart:core                                                                 List.[]
package:compiler_unsupported/src/ssa/optimize.dart 2537                   SsaLoadElimination.visitCreate.<fn>
package:compiler_unsupported/src/elements/common.dart 388                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachInstanceField.fieldFilter
package:compiler_unsupported/src/elements/common.dart 356                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember.<fn>
package:front_end/src/fasta/util/link_implementation.dart 124             LinkEntry.forEach
package:compiler_unsupported/src/elements/modelx.dart 2872                ClassElementX.forEachLocalMember
package:compiler_unsupported/src/elements/common.dart 356                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachMember
package:compiler_unsupported/src/elements/common.dart 392                 ElementX&AstElementMixin&AnalyzableElementX&ClassElementCommon.forEachInstanceField
package:compiler_unsupported/src/universe/codegen_world_builder.dart 502  ElementCodegenWorldBuilderImpl.forEachInstanceField
package:compiler_unsupported/src/ssa/optimize.dart 2531                   SsaLoadElimination.visitCreate
package:compiler_unsupported/src/ssa/nodes.dart 1649                      HCreate.accept
package:compiler_unsupported/src/ssa/optimize.dart 2481                   SsaLoadElimination.visitBasicBlock
package:compiler_unsupported/src/ssa/optimize.dart 2440                   SsaLoadElimination.visitGraph
package:compiler_unsupported/src/ssa/optimize.dart 58                     SsaOptimizerTask.optimize.runPhase.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/common/tasks.dart 183                    CompilerTask.measureSubtask
package:compiler_unsupported/src/ssa/optimize.dart 58                     SsaOptimizerTask.optimize.runPhase
dart:core                                                                 List.forEach
package:compiler_unsupported/src/ssa/optimize.dart 114                    SsaOptimizerTask.optimize.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run

dart:async                                                                _ZoneDelegate.run                                                                                                                [90/1466]
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/ssa/optimize.dart 68                     SsaOptimizerTask.optimize
package:compiler_unsupported/src/ssa/ssa.dart 39                          SsaFunctionCompiler.compile
package:compiler_unsupported/src/js_backend/backend.dart 932              JavaScriptBackend.codegen
package:compiler_unsupported/src/js_backend/element_strategy.dart 125     ElementCodegenWorkItem.run
package:compiler_unsupported/src/compiler.dart 737                        Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/common/tasks.dart 183                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 737                        Compiler.emptyQueue.<fn>.<fn>.<fn>.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/common/tasks.dart 183                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 735                        Compiler.emptyQueue.<fn>.<fn>.<fn>
package:compiler_unsupported/src/compiler.dart 1098                       CompilerDiagnosticReporter.withCurrentElement
package:compiler_unsupported/src/compiler.dart 733                        Compiler.emptyQueue.<fn>.<fn>
package:compiler_unsupported/src/enqueue.dart 507                         EnqueuerStrategy.processWorkItem
package:compiler_unsupported/src/js_backend/enqueuer.dart 227             CodegenEnqueuer.forEach
package:compiler_unsupported/src/compiler.dart 729                        Compiler.emptyQueue.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/common/tasks.dart 183                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 728                        Compiler.emptyQueue
package:compiler_unsupported/src/compiler.dart 752                        Compiler.processQueue.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/common/tasks.dart 183                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 747                        Compiler.processQueue
package:compiler_unsupported/src/compiler.dart 621                        Compiler.compileLoadedLibraries.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/common/tasks.dart 183                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 518                        Compiler.compileLoadedLibraries
package:compiler_unsupported/src/compiler.dart 473                        Compiler.runInternal
===== asynchronous gap ===========================
package:compiler_unsupported/src/compiler.dart 308                        Compiler.run.<fn>.<fn>
dart:async                                                                new Future.sync
package:compiler_unsupported/src/compiler.dart 308                        Compiler.run.<fn>
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 119                    CompilerTask._run
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run
dart:async                                                                runZoned
package:compiler_unsupported/src/common/tasks.dart 105                    CompilerTask._measureZoned
package:compiler_unsupported/src/common/tasks.dart 63                     CompilerTask.measure
package:compiler_unsupported/src/common/tasks.dart 183                    CompilerTask.measureSubtask
package:compiler_unsupported/src/compiler.dart 305                        Compiler.run
package:compiler_unsupported/src/apiimpl.dart 263                         CompilerImpl.run.<fn>.<fn>
dart:async                                                                _ZoneDelegate.runUnary
package:compiler_unsupported/src/common/tasks.dart 133                    CompilerTask._runUnary
dart:async                                                                _ZoneDelegate.run
package:compiler_unsupported/src/common/tasks.dart 122                    CompilerTask._run

**Comment by sigmundch** [comment] 2017-06-16 16:26
@sircco is this a recent failure? It appears that this issue occurs on old versions of the sdk as well (1.23, 1.22, etc)

How are you creating an instance of `Drake`? Looking at the code in package:dragula/dragula_raw.dart (I assume this is where the issue comes from), it appears that the problem is related to how this class is declared and how it is supposed to be created.

Should it have an external constructor? Should the `containers` field be a field or something else?

I can reproduce the exception with this very simple example:
```dart
ibrary foo;

import 'package:js/js.dart' show JS;

@JS()
class X {
  List containers;
}

main() => new X();
```

@jacob314  - does this ring a bell? Is there a pattern here that is invalid and what should we check for in dart2js to prevent this crash?

**Comment by sircco** [comment] 2017-06-16 16:35
@sigmundch 
on production we have 1.23 and it compiles just fine, as i remember we did this code maybe 12months ago and it has been working fine in meantime.

I took 1.24 on my desktop to try it and it explodes on this part.
We are using dragula package from pub

i instantiate it like this:
`var drakke = dragula([],  copy: dragulaCopy, copySortSource: false, accepts: dragulaAccepts, invalid: dragulaInvalid);`

from the look of exception it looks like that [] is the problem but i can copypaste dragula params if needed.

**Comment by sigmundch** [comment] 2017-06-16 16:50
Thanks @sircco, if you can share with us a repro with a simple program that imports package:dragula, that would really help us narrow this down. I tried:

```dart
import 'package:dragula/dragula_raw.dart';
main() {
  var drakke = dragula([], new DragulaOptions(
        copy: () => true,
        copySortSource: false,
        accepts: (e, t, s, r) => null,
        invalid: (e, t) => null));
}
```

but that compiles without a problem. If I instead do the allocation directly like `new Drake()`, I can see an exception. I'm guessing I'm not doing it quite the same way you are in the example above.

As for 1.24 vs 1.23 - has dragula changed also in the last year? (I mean, could it be that the bug in the SDK has been there for a while, but that only a recent version of dragula is hitting the bug on our end?)

**Comment by sircco** [comment] 2017-06-17 14:18
it took me a while to find the problem because its quite complicated to get to it.

Problem is not in dart 1.24 but in combination of mustache 2.0.0 and dragula

here is temporary repo with bug 
https://github.com/sircco/dart-bugreport-29905

comment out mustache print to get project to build
note that if you leave only mustache part (including import) then it will pass also so it is some combination of those two packages.

**Comment by sircco** [comment] 2018-01-22 12:58
i am still hitting this bug, any news regarding this?

**Comment by matanlurey** [comment] 2018-01-23 08:55
There isn't any further work on Dart 1.24, so I'm closing at this time.

You could try a dev release of Dart2 (2.0.0-dev) to see if it helps. Sorry about that.

**Closed by matanlurey** 2018-01-23 08:55 UTC
Labels: Resolution: not planned, area-dart2js, area-js_interop

**Comment by sigmundch** [comment] 2018-01-23 18:54
@sircco - sorry this fell through the cracks on my end, I was meaning to investigate this a bit further to make sure the issue doesn't persist in the latest version of the SDK.

I tried this on 2.0.0-dev.19.0 and I wasn't able to repro. I get a warning and a build error, but I don't see the compiler crashing:

```
Loading source assets... 
Loading dart_to_js_script_rewriter transformers... (1.2s)
Building buggy... 
[Info from Dart2JS]:
Compiling buggy|web/main.dart...
[Error from Dart2JS]:
web/main.dart:5:1:
Can't read 'package:dragula/dragula.dart' (Could not find asset dragula|lib/dragula.dart.).
import 'package:dragula/dragula.dart';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Dart2JS on buggy|web/main.dart]:

****************************************************************
* WARNING: dart:mirrors support in dart2js is experimental,
*          and not recommended.
*          This implementation of mirrors is incomplete,
*          and often greatly increases the size of the generated
*          JavaScript code.
*
* Your app imports dart:mirrors via:
*   main.dart => package:mustache4dart => dart:mirrors
*
* You can disable this message by using the --enable-experimental-mirrors
* command-line flag.
*
* To learn what to do next, please visit:
*    http://dartlang.org/dart2js-reflection
****************************************************************
[Warning from Dart2JS]:
web/main.dart:13:11:
Cannot resolve 'dragula'.
        drakke = dragula([], copy: dragulaCopy, copySortSource: false, 
                        accepts: dragulaAccepts, invalid: dragulaInvalid);
[Warning from Dart2JS on buggy|web/main.dart]:
2 hint(s) suppressed in package:mustache4dart.
[Info from Dart2JS]:
Took 0:00:07.212656 to compile buggy|web/main.dart.
Build failed.
```

Does this match what you see?
