### ISSUE TITLE
[CP] [Stable] Cherry-pick request for updating dartdoc to fix sidebar generation

### ISSUE THREAD

**Issue by parlough** [dart-lang/sdk#54073] opened 2023-11-16 19:25 UTC
### Commit(s) to merge

https://dart.googlesource.com/sdk/+/279f6d77aed890abfdd0d93341d8b94239dca610

### Target

stable

### Prepared changelist for beta/stable

https://dart-review.googlesource.com/c/sdk/+/336780

### Issue Description

https://github.com/dart-lang/sdk/issues/54067

There are two primary issues:

- As seen in the api.dart.dev 3.2.0 API docs ([Example](https://api.dart.dev/stable/3.2.0/dart-ffi/NativeCallable/NativeCallable.isolateLocal.html)), the sidenavs are not inserted on non-class pages.
- Even if the sidebars were added correctly, the links were incorrect in the sidebar if not using base-href, preventing from them adjusted by the JS that adds in the sidebar. (https://github.com/dart-lang/pub-dev/issues/7058).

### What is the fix

Update to the earliest dartdoc commit that includes the necessary fixes. 279f6d77aed890abfdd0d93341d8b94239dca610 updates to https://github.com/dart-lang/dartdoc/commit/8c103397734f4dba75915e40c734a88e29a35f26 which includes all three fixes:

- https://github.com/dart-lang/dartdoc/commit/c147aa19a2a655a2cf9af7a8e6a0f104e6116137
- https://github.com/dart-lang/dartdoc/commit/5156398c17ff7ab8defd87c7a5b9de1ee7e4564a
- https://github.com/dart-lang/dartdoc/commit/4283dbc60f40539d7d8aca4b29e6e14b7607dd0d

These fixes are however not isolated and are mixed with a few other minor changes in the range https://github.com/dart-lang/dartdoc/compare/a3cfdc40a94d169bd7b559dc6f83ceb7f79de4e2...8c103397734f4dba75915e40c734a88e29a35f26. 

@srawlins outlined the other commits as:

> - 4 commits that affect the dart doc command for users (but would not affect what we see at api.dart.dev) (https://github.com/dart-lang/dartdoc/commit/59947b1495f6fc30fb106ae1a0a8d60d86c82f14, https://github.com/dart-lang/dartdoc/commit/affc5b44f192a7c278d6286617310e9eca135625, https://github.com/dart-lang/dartdoc/commit/e30bece8d172f99e7cd246b74811a7784660f956, https://github.com/dart-lang/dartdoc/commit/6bcf07f5a54873467674e812ac47fdcf96dd4723)
> - the rest are non-generation, non-UI commits (changes to development tools, tests, no-op refactors)

As part of those 4 commits, support for the `hideSdkText` option [was dropped](https://github.com/dart-lang/dartdoc/commit/affc5b44f192a7c278d6286617310e9eca135625#diff-fdc209b46dd8b5b22cb7326390e2b78b33fc469471258e55b5cf5a2cd6764f91L1421), but it was already hidden and not exposed by the `dart doc` CLI.

### Why cherry-pick

The 3.2 API docs will be Dart developer's view into the SDK's public APIs for the next several months. Having a missing sidebar makes navigation across the site quite difficult and less accessible, and will be especially jarring for users who expect it to be there.

Without these fixes, user's own docs generated with `dart doc` will also be affected. Pub updates dartdoc separately so it does not need this cherry-pick.

### Risk

low/medium

### Issue link(s)

https://github.com/dart-lang/sdk/issues/54067, https://github.com/dart-lang/pub-dev/issues/7058

### Extra Info

Flutter has been using a version with these commits/fixes to generate their `main-api` docs since https://github.com/flutter/flutter/commit/997a94fd1f022492b6c955013eeec7e4c4e67c62.

**Comment by itsjustkevin** [comment] 2023-11-16 19:55
@mit-mit I see this as a P0 and would like to get it cherry-picked in.  

CC: @MaryaBelanger

**Comment by vsmenon** [comment] 2023-11-17 03:15
@srawlins - what is your take on benefit / risk?

**Comment by srawlins** [comment] 2023-11-17 03:34
I support this cherry-pick. Here are some details about the dartdoc commits being added:

* 3 fixes to the sidebars (https://github.com/dart-lang/dartdoc/commit/c147aa19a2a655a2cf9af7a8e6a0f104e6116137, https://github.com/dart-lang/dartdoc/commit/5156398c17ff7ab8defd87c7a5b9de1ee7e4564a, https://github.com/dart-lang/dartdoc/commit/4283dbc60f40539d7d8aca4b29e6e14b7607dd0d)
* 4 commits that affect the dart doc command for users (but would not affect what we see at api.dart.dev) (https://github.com/dart-lang/dartdoc/commit/59947b1495f6fc30fb106ae1a0a8d60d86c82f14, https://github.com/dart-lang/dartdoc/commit/affc5b44f192a7c278d6286617310e9eca135625, https://github.com/dart-lang/dartdoc/commit/e30bece8d172f99e7cd246b74811a7784660f956, https://github.com/dart-lang/dartdoc/commit/6bcf07f5a54873467674e812ac47fdcf96dd4723)
* the rest are non-generation, non-UI commits (changes to development tools, tests, no-op refactors)


I'll also note that Flutter bumped to dartdoc 7.0.1, for generation of api.flutter.dev, with https://github.com/flutter/flutter/commit/997a94fd1f022492b6c955013eeec7e4c4e67c62, on Oct 20. They have not reported any regressions since running with that bump.

So this cherry-pick would contain 3 commits that fix the issue at hand, and 4 unrelated changes that may affect the output of a developer locally running `dart doc`.

Any unknown regressions would only affect the rendered docs at api.dart.dev (until we could land fixes), and output from a developer running `dart doc` locally; any unknown regressions would _not_ affect docs at pub.dev or at api.flutter.dev. Therefore I think the risk is very very low of this cherry-pick causing anything more than a minor issue that could be corrected in a short time.

**Comment by vsmenon** [comment] 2023-11-17 03:35
Thanks - lgtm

**Comment by parlough** [comment] 2023-11-17 16:31
Thanks all!

I've updated the changelog in the CL as requested as well.

@sortie Does the release team submit the CL when ready or should I get someone else to submit it for me?

**Comment by sortie** [comment] 2023-11-17 16:33
The normal workflow applies here once the cherry-pick-approved label is granted. Since you can't submit AFAIK, yeah, get someone to help you. I can do that for you if you want just let me know :)

**Comment by parlough** [comment] 2023-11-17 16:34
> I can do that for you if you want just let me know :)

That would be great! Thank you 😄

**Comment by athomas** [comment] 2023-11-22 17:12
Released in 3.2.1.

**Closed** 2023-11-22 17:11 UTC
Labels: merge-to-stable, area-dart-cli, cherry-pick-review, cherry-pick-approved, dart-cli-doc
