### ISSUE TITLE
Fasta stack trace from compilation, NonAsciiIdentifierToken.assertionMessage

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#29939] opened 2017-06-20 06:58 UTC
@peter-ahe-google 
ID: d7d1556681434da367404988ac396fe3f991b1ae

```
Unhandled exception:
RangeError: Value not in range: 5
#0      _StringBase.substring (dart:core-patch/string_patch.dart:360)
#1      NonAsciiIdentifierToken.assertionMessage (package:front_end/src/fasta/scanner/error_token.dart:118:29)
#2      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:111:61)
<asynchronous suspension>
#3      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:131:26)
<asynchronous suspension>
#4      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:137:13)
<asynchronous suspension>
#5      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:230:20)
<asynchronous suspension>
#6      CompileTask.buildOutline (package:front_end/src/fasta/fasta.dart:149:38)
<asynchronous suspension>
#7      CompileTask.compile (package:front_end/src/fasta/fasta.dart:161:39)
<asynchronous suspension>
#8      compile.<anonymous closure> (package:front_end/src/fasta/fasta.dart:101:25)
<asynchronous suspension>
#9      CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#10     _rootRun (dart:async/zone.dart:1120)
#11     _CustomZone.run (dart:async/zone.dart:1001)
#12     runZoned (dart:async/zone.dart:1467)
#13     CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#14     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#15     compile (package:front_end/src/fasta/fasta.dart:94:38)
<asynchronous suspension>
#16     compileEntryPoint (package:front_end/src/fasta/fasta.dart:53:11)
<asynchronous suspension>
#17     main (file:///home/lukechurch/GitRepos/sdk/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by peter-ahe-google** [comment] 2017-06-22 13:42
@lukechurch ID missing.

**Comment by lukechurch** [comment] 2017-06-22 13:51
@peter-ahe-google PTAL

**Comment by peter-ahe-google** [comment] 2017-06-23 11:58
This is a duplicate of #29985.

**Closed by peter-ahe-google** 2017-06-23 11:58 UTC
Labels: area-fasta
