### ISSUE TITLE
Dart analysis server crash

### ISSUE THREAD

**Issue by Butzlabben** [dart-lang/sdk#35304] opened 2018-12-01 15:10 UTC
[report1.txt](https://github.com/dart-lang/sdk/files/2635976/report1.txt)
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.5107.41`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.5107.41, JRE 1.8.0_152-release-1248-b22x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Daniel\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\Daniel\IdeaProjects\pretendr\lib\register.dart context: exception_20181201_160658_693
RangeError (index): Invalid value: Not in range 0..7, inclusive: 8
#0      List.[] (dart:core/runtime/libarray.dart:12:52)
#1      _UnitResynthesizer.getReferenceInfo (package:analyzer/src/summary/resynthesize.dart:1456:43)
#2      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1362:38)
#3      SummaryResynthesizerContext.resolveTypeRef (package:analyzer/src/summary/resynthesize.dart:459:30)
#4      ParameterElementImpl._resynthesizeTypeAndParameters (package:analyzer/src/dart/element/element.dart:7707:14)
#5      ParameterElementImpl.type (package:analyzer/src/dart/element/element.dart:7599:5)
#6      _ParameterElementImpl

**Comment by stereotype441** [comment] 2018-12-03 18:56
Duplicate of #34534

**Closed by stereotype441** 2018-12-03 18:56 UTC
Labels: area-analyzer
