### ISSUE TITLE
IncrementalKernelGenerator is treating some errors as warnings

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#31976] opened 2018-01-25 22:11 UTC
Many language tests which expect compile-time or runtime errors are failing when the incremental compiler is enabled for the VM, which is currently blocking #31146. It looks like at least some invalid code that is marked as an error by the single shot compiler is marked as a warning when using the incremental compiler. Output for ```language_2/final_super_field_set_test.dart``` is attached as an example.

Without incremental compiler enabled:

```
Strong: true                                                                                                                                                                                [495/47422]
Target: null (provided: vm)
throwOnErrorsForDebugging: false
throwOnWarningsForDebugging: false
throwOnNitsForDebugging: false
exit on problem: false
Embed sources: true
debugDump: false
verbose: true
verify: false

0:00:00.002944: Validated arguments in 2ms.
0:00:00.003082: Started building UriTranslator in 0ms.
0:00:00.003195: Read libraries file in 0ms.
0:00:00.005048: Read packages file in 1ms.
0:00:00.264673: Indexed 18 libraries (0 bytes) in 259.540ms, that is,
       0.000 bytes/ms, and
      14.419 ms/libraries.
0:00:00.266147: Built outlines for 1 compilation units (414 bytes) in 1.313ms, that is,
     315.308 bytes/ms, and
       1.313 ms/compilation unit.
0:00:00.266267: Resolved parts in 0ms.
0:00:00.266335: Applied patches in 0ms.
0:00:00.266425: Computed library scopes in 0ms.
0:00:00.266500: Resolved 1 types in 0ms.
0:00:00.269344: Instantiated 0 type variables to their bounds in 2ms.
0:00:00.269452: Found cycles in 0ms.
0:00:00.269547: Checked restricted supertypes in 0ms.
0:00:00.269618: Resolved 0 type-variable bounds in 0ms.
0:00:00.269890: Built program in 0ms.
0:00:00.269973: Installed Object as implicit superclass in 0ms.
0:00:00.270049: Installed default constructors in 0ms.
0:00:00.270120: Resolved 0 constructors in 0ms.
0:00:00.270237: Linked program in 0ms.
0:00:00.270315: Computed core types in 0ms.
0:00:00.288747: Computed class hierarchy in 18ms.
0:00:00.297723: Prepared top level inference in 8ms.
0:00:00.317984: Performed top level inference in 20ms.
0:00:00.318202: Checked overrides in 0ms.
0:00:00.318326: Building program in 0ms.
Not enabling colors, stdout does not support ANSI colors.
tests/language_2/final_super_field_set_test.dart:12:11: Error: Superclass has no setter named 'field'.
    super.field = 87; /*@compile-error=unspecified*/
          ^
0:00:00.323421: Built bodies for 1 compilation units (414 bytes) in 5.031ms, that is,
      82.290 bytes/ms, and
       5.031 ms/compilation unit.
0:00:00.323552: Finished deferred load tearoffs 0 in 0ms.
0:00:00.323663: Finished constructors in 0ms.
0:00:00.323740: Finished 0 native methods in 0ms.
0:00:00.323812: Finished 0 patch methods in 0ms.
0:00:00.323885: Transformed mixin applications in 0ms.
0:00:00.324184: Transformed async methods in 0ms.
0:00:00.324534: Generated program in 0ms.
DFE:> _CompilationError(tests/language_2/final_super_field_set_test.dart:12:11: Error: Superclass has no setter named 'field'.
    super.field = 87; /*@compile-error=unspecified*/
```

With incremental compiler enabled ([relevant CL](https://dart-review.googlesource.com/c/sdk/+/361260)):
```
DFE: request: [0, SendPort, /usr/local/google/home/bkonyi/sdk/tests/language_2/final_super_field_set_test.dart, /usr/local/google/home/bkonyi/sdk/pkg/vm/tool/../../../out/DebugX64/vm_platform_strong.
dill, true, true, 847693033, null, false]
DFE: Platform.packageConfig: file:///usr/local/google/home/bkonyi/sdk/.packages
DFE: packagesUri: file:///usr/local/google/home/bkonyi/sdk/.packages
DFE: Platform.resolvedExecutable: /usr/local/google/home/bkonyi/sdk/out/DebugX64/dart
DFE: platformKernel: file:///usr/local/google/home/bkonyi/sdk/out/DebugX64/vm_platform_strong.dill
DFE: strongMode: false
DFE: scriptUri: file:///usr/local/google/home/bkonyi/sdk/tests/language_2/final_super_field_set_test.dart
0:00:00.003982: Started building UriTranslator in 3ms.
0:00:00.005008: Read libraries file in 0ms.
0:00:00.007791: Read packages file in 2ms.
0:00:00.007920: Read packages file in 0ms.
0:00:00.012665: Read file:///usr/local/google/home/bkonyi/sdk/out/DebugX64/vm_platform_strong.dill in 4ms.
0:00:00.222992: Deserialized file:///usr/local/google/home/bkonyi/sdk/out/DebugX64/vm_platform_strong.dill in 210ms.
0:00:00.223335: Appended libraries in 0ms.
0:00:00.256273: Indexed 18 libraries (4981667 bytes) in 32.853ms, that is,
  151635.071 bytes/ms, and
       1.825 ms/libraries.
0:00:00.259765: Built outlines for 1 compilation units (414 bytes) in 3.317ms, that is,
     124.812 bytes/ms, and
       3.317 ms/compilation unit.
0:00:00.259892: Resolved parts in 0ms.
0:00:00.259959: Applied patches in 0ms.
0:00:00.260052: Computed library scopes in 0ms.
0:00:00.260128: Resolved 1 types in 0ms.
0:00:00.260215: Found cycles in 0ms.
0:00:00.260305: Checked restricted supertypes in 0ms.
0:00:00.260374: Resolved 0 type-variable bounds in 0ms.
0:00:00.260480: Built program in 0ms.
0:00:00.260552: Installed Object as implicit superclass in 0ms.
0:00:00.260625: Installed default constructors in 0ms.
0:00:00.260690: Resolved 0 constructors in 0ms.
0:00:00.261363: Linked program in 0ms.
0:00:00.261460: Computed core types in 0ms.
0:00:00.280675: Computed class hierarchy in 19ms.
0:00:00.281097: Prepared top level inference in 0ms.
0:00:00.299481: Performed top level inference in 18ms.
0:00:00.299670: Checked overrides in 0ms.
0:00:00.299829: Building program in 0ms.
Not enabling colors, stdout does not support ANSI colors.
tests/language_2/final_super_field_set_test.dart:12:11: Warning: Superclass has no setter named 'field'.
    super.field = 87; /*@compile-error=unspecified*/
          ^
0:00:00.304115: Built bodies for 1 compilation units (414 bytes) in 4.219ms, that is,
      98.128 bytes/ms, and
       4.219 ms/compilation unit.
0:00:00.304234: Finished deferred load tearoffs 0 in 0ms.
0:00:00.304335: Finished constructors in 0ms.
0:00:00.304406: Finished 0 native methods in 0ms.
0:00:00.304467: Finished 0 patch methods in 0ms.
0:00:00.304536: Transformed mixin applications in 0ms.
0:00:00.304849: Transformed async methods in 0ms.
No errors!
DFE:> _CompilationOk(1125 bytes)```

**Comment by peter-ahe-google** [comment] 2018-01-26 06:04
The relevant CL link above doesn't work. But I found this CL: https://dart-review.googlesource.com/c/sdk/+/36126 which looks about right.

It looks to me like strongMode isn't passed to the method lookupOrBuildNewIncrementalCompiler. We can see that the compiler is reading the correct platform file, so hopefully passing in that extra parameter should fix the problem.

**Comment by jensjoha** [comment] 2018-01-26 08:58
Peter is correct, add `strongMode: strong,` and the problem goes away.
Closing the issue. Please reopen if the linked CL wasn't the right one, and the problem is something else.

**Closed by jensjoha** 2018-01-26 08:58 UTC
Labels: front-end-fasta
