### ISSUE TITLE
Observatory timeline broken

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#37419] opened 2019-07-01 20:16 UTC
I haven't used it for a few months, but the timeline in the observatory seems broken. I used Chromium.

* Dart SDK Version: `2.5.0-dev.0.0`
* Debian 9.9
* Chromium 73

I get the following error when trying to refresh (fetching timeline from Dart VM)

```
timeline.js:657 Uncaught TypeError: Cannot read property 'timeOriginMicros' of undefined
    at XMLHttpRequest.<anonymous> (timeline.js:657)
```

**Comment by a-siva** [comment] 2019-07-03 17:15
This looks like a duplicate of a prior issue that was fixed here
https://dart-review.googlesource.com/c/sdk/+/107926

**Closed by a-siva** 2019-07-03 17:15 UTC
Labels: area-observatory
