### ISSUE TITLE
dart analyzer

### ISSUE THREAD

**Issue by makkasbed** [dart-lang/sdk#34868] opened 2018-10-19 18:22 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\adu\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\adu\StudioProjects\nhomafie\lib\screens\home.dart context: exception_20181019_182200_888
Element mismatch in C:\Users\adu\StudioProjects\nhomafie\lib\screens\home.dart at class HomeState extends State<HomeScreen>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-25 13:37
Duplicate of #33930

**Closed by stereotype441** 2018-10-25 13:37 UTC
Labels: area-analyzer
