### ISSUE TITLE
Dart analyzer could not infere from class properties

### ISSUE THREAD

**Issue by miguelpruivo** [dart-lang/sdk#40232] opened 2020-01-20 10:30 UTC
## Issue related with:

* Analyzer
* Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

## Description

Just noticed it with Flutter, but should be happening with Dart classes in general. If you have an abstract class as a property of a class, for example:

```
class Base {}

class Sub extends Base {
  final String property;
  Sub(this.property);
}
```

And then you try to:
```
class Foo {
  final Base base;
  Foo(this.base);

  void someMethod() {
   if(base is Sub && base.property){
        // This doesn't work as it can't infer property
   }
}
```

whereas:
```
class Foo {
  final Base base;
  Foo(this.base);

  void someMethod() {
   Base b;
   if(b is Sub && base.property){
        // This will do, because b is within the same scope
   }
 }
}
```

Anyhow, this seems like bug because Dart analyzer should infer it anyway and display the available methods/properties for the given class.

Thank you.

**Comment by eernstg** [comment] 2020-01-20 12:51
This comes up frequently. Promotion cannot be applied to an instance variable, because the corresponding getter could be overridden (whether or not the variable is final), and there's nothing preventing that overriding getter from returning a different object on different invocations. So a type test applied to a previously returned result says nothing about the actual type of the result returned from a result return later.

So I'll close this with 'working as intended'.

**Closed by eernstg** 2020-01-20 12:51 UTC
Labels: closed-as-intended
