### ISSUE TITLE
Missing covariant check on type param

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#27269] opened 2016-09-06 21:04 UTC
The following gives no strong mode errors and prints 'hello1' in DDC - adding a string and int without error.  

Where is the missing runtime check?  :-)  @leafpetersen @jmesserly 

```dart
typedef T Callback<T>(T val);

class Foo<T> {
  T x;

  Callback<T> _callback;

  Callback<T> get callback => _callback;
  void set callback(Callback<T> f) { _callback = f; }
}

void main() {
  Foo<int> f = new Foo<int>();
  f.callback = (x) => x + 1;

  Foo<Object> f2 = f;
  var result = f2.callback('hello');
  print(result);
}
```

**Comment by jmesserly** [comment] 2016-09-14 18:07
I believe this is a dupe of https://github.com/dart-lang/sdk/issues/27259

**Closed by jmesserly** 2016-09-14 18:07 UTC
Labels: area-dev-compiler, soundness
