### ISSUE TITLE
"Interpreting this as package URI" message is confusing

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#37978] opened 2019-08-23 03:05 UTC
I ran `dart --enable-asserts lib/temp.dart` and the output said (in addition to trying to run the program):

```
lib/temp.dart: Warning: Interpreting this as package URI, 'package:plexiglass/temp.dart'.
```

I have no idea what this means or why it says it.

**Comment by lrhn** [comment] 2019-08-23 08:53
You are running `lib/temp.dart`. The full URI of that, based on current working directory, is `file:///$cwd/lib/temp.dart`. That is a *file* URI.
However, the library is inside a `lib` directory, so it can *also* be addressed as `package:plexiglass/temp.dart`. Since Dart uses the URI used to load a library as the identity of the libraries, those two ways to address the same file would become two different libraries.

More importantly, if the `temp.dart` file performs any import of a library in the same package using a relative URI reference, then it is resolved against the importing library's URI. So, if `temp.dart` has an `import "plexiglass.dart";`, then that would import that library as `file:///$cwd/lib/plexiglass.dart`, and *not* `package:plexiglass/plexiglass.dart`.

What would often happen is that some other library, perhaps even in a different package, would import `package:plexiglass/plexiglass.dart` using a `package:`-URI, and then you would have two different libraries. The types defined by those two libraries have no relation to each other, they just have the same name, and you will get odd type errors like `Glass is not assignable to Glass`. Yey. (This problem was smaller when all libraries had names, and you couldn't import two libraries with the same name into the same program. Alas, that was all library names were good for.)

In general, as a rule of thumb, you should *never* address a file inside a package's `lib` directory through a path containing `lib`. When you do that, you should instead use the `package:` URI. This includes when specifying a file on the *command line*.

Since nobody followed that rule, we made the parser recognize the issue and convert entry file `file:` URI to a `package:` URI when possible. We still warn you that we are changing your input.

To avoid the warning, do `dart --packages=.packages --enable-asserts package:plexiglass/temp.dart` instead.

**Comment by Hixie** [comment] 2019-08-23 15:20
I don't think anyone cares about this though? I agree that interpreting the relative URL so as to avoid this problem is right, but it's not something the developer wants to even think about.

The current warning is entirely unactionable and uninteresting. If we really want people to jump through hoops and explicitly list the --packages even though it should be implicit, than we should say so in the warning. But that would make it even more obvious that the warning is pointless, IMHO.

Running relative paths is something we should support out of the box without fanfare.

**Comment by yjbanov** [comment] 2019-09-18 16:38
I think Dart should stop relying on import URLs for library identity. I don't think we have a use-case for it any more. This is probably a leftover from the days when the VM was expected to be able to load and run libraries from the network. But that use-case is gone.

This is not the first time I'm encountering this:

* [The first time I got confused](https://github.com/dart-lang/sdk/issues/24942)
* [An early Flutter issue](https://github.com/flutter/flutter/issues/419)
* [Code in flutter_tools attempting to suppress it](https://github.com/flutter/flutter/blob/69a296463e54dd12e96f361c136d54fea7a438d9/packages/flutter_tools/lib/src/build_runner/web_fs.dart#L345)

**Comment by pedromassango** [comment] 2020-04-07 14:58
Ok. I though there is something bad in my code. Any update on this?

**Comment by kwight** [comment] 2020-04-18 21:02
I found this rather confusing too, trying to run a simple filewatcher on a test file – but it _did_ sort of explain why the CLI template from Stagehand runs its `main` from within `bin` (something else I didn't understand).

So basically, to get rid of the output while using the `dart` executable, run your `main` entry from anywhere _other_ than within the `lib` folder.

**Comment by Hixie** [comment] 2020-04-24 06:28
I ran into this again (having forgotten about this bug), but this time I thought "oh, I guess what this means is that I should run `dart package:foo/main.dart` instead of `dart lib/main.dart`" but when I tried that Dart itself crashed with two 37-line stack traces:

```
Crash when compiling package:house_of_rooves_daemon/main.dart,
at character offset null:
FileSystemException(uri=package:house_of_rooves_daemon/.packages; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      HttpAwareFileSystem.entityForUri (package:vm/http_filesystem.dart:16:23)
#2      HybridFileSystemEntity.delegate (package:front_end/src/fasta/hybrid_file_system.dart:47:37)
<asynchronous suspension>
#3      HybridFileSystemEntity.exists (package:front_end/src/fasta/hybrid_file_system.dart:51:41)
#4      ProcessedOptions._findPackages.checkInDir (package:front_end/src/base/processed_options.dart:563:52)
#5      ProcessedOptions._findPackages (package:front_end/src/base/processed_options.dart:568:37)
#6      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:498:30)
#7      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:428:33)
<asynchronous suspension>
#8      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:71:49)
#9      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#10     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#11     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:18)
#12     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#13     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#14     new Future.sync (dart:async/future.dart:224:31)
#15     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1465:12)
#20     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#21     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#22     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:32)
#23     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#24     SingleShotCompilerWrapper.compileInternal (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:359:17)
#25     Compiler.compile.<anonymous closure> (org-dartlang-kernel-service:///pkg/vm/bin/kernel_service.dart:163:45)
#26     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#27     _rootRun (dart:async/zone.dart:1122:38)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Then I found this bug again and read the comment above about `bin/main.dart` so I tried that... and it didn't work either, because now relative paths don't work in a sane way.

I really don't see any value in this error message. Can we remove it?

**Comment by lrhn** [comment] 2020-04-24 06:40
The reason `dart package:foo/main.dart` doesn't work is that it can't find `.dart_tool/package_config.json` relative to a `package:` URI, so you actually have to write 
```text
dart --packages=.dart_tool/package_config.json package:foo/main.dart
```
I'm perfectly aware that this is not something we can make people do. That's why we recommend not having "main" files inside `lib/`. The `bin/` directory is the traditional place to put entry points.
If you all it `foo.dart` instead of `main.dart` and put it in `bin/`, you can even do `pub run foo`.

**Comment by Hixie** [comment] 2020-04-24 19:03
@lrhn Can you explain to me the value of the warning here? Why does it matter if someone runs `dart lib/foo.dart`? Why do we want to encourage running Dart programs through the `pub` tool instead of the `dart` tool? Why do we care if they have a `bin/` directory and split their code across multiple directories instead of just having a single place? Why do we care what it's called? (I'm not saying we shouldn't, I just don't have any answers to any of these questions.)

**Comment by shinriyo** [comment] 2020-05-05 01:08
Android Studio?
I upgrade Android Studio, it happened...

**Comment by tjx666** [comment] 2021-03-27 16:16
any update? Why not provide an option to ignore this?

**Comment by tjx666** [comment] 2021-04-17 08:44
Any update?

**Comment by allenbrunson** [comment] 2021-05-21 00:33
i just spent 30 minutes trying to get android studio to launch a command-line dart app in such a way that would remove this warning. as far as i can tell, it can't be done.

consider this another vote for giving us a way to turn off this distracting, unnecessary warning.

**Comment by lrhn** [comment] 2021-05-21 08:23
The issue is that your "main" entry file is located inside `lib/`. If you put it in `bin/` instead, you wouldn't have the problem.
Or have a default launcher in `bin/`, something like 
```dart
import "package:mypackage/main.dart" as p; 
void main(List<String> args) { 
  p.main(args); 
}
```
Then you can run `bin/main.dart` without getting any warnings.

You can launch a `lib/` file without getting the warning, you just have to specify it as a `package:` URI (the warning is there to tell you that you are referring to a file in `lib/` using a `file` URI, not the recommended `package:` URI, and telling you that the compile is fixing that for you). It does mean you have to explicitly point to the package resolution, which is otherwise found using path lookup. Something like:
```bash
dart --packages=.dart_tool/package_config.json package:package_name/main.dart
```

On the other hand, we might just want to consider dropping the warning now.

**Comment by lrhn** [comment] 2021-12-16 12:24
I think this warning has lost its meaning by now.

We are more flexible about recognizing files as "belonging to a package" through the `package_config.json` configurations, including finding the `package:` URI for file paths, and recognizing that a path provided on the command line is actually denoting a file that has a `package:` URI is just using that general functionality.

I still recommend putting the `main` file in `bin/` like the Pub layout recommends, but the warning alone isn't going to change what people do (otherwise it would have by now), so it's just noise.

Let's remove it.

**Comment by mit-mit** [comment] 2021-12-16 12:26
@johnniwinther this is in the CFE, right? I'd really like to remove this!

**Comment by johnniwinther** [comment] 2021-12-16 13:24
I'll remove it.

**Comment by mit-mit** [comment] 2022-01-13 10:25
Fix has landed

**Closed by mit-mit** 2022-01-13 10:25 UTC
Labels: type-enhancement, area-front-end

**Comment by dgaedcke** [comment] 2022-02-08 18:34
I built a Dart CLI that's been running fine.

Then I began adding a Web UI on it and moved my "lib" directory into a new flutter project

As soon as I did this, my CLI stopped running with this error.

I've tried moving both main.dart (flutter entry point) and evCfg.dart (my CLI entry point) OUT of the lib directory with no luck

Can someone tell me how to have a CLI client app and Flutter project all in the same directory???

**Comment by mit-mit** [comment] 2022-02-08 18:43
That's a fairly broad question, and probably something that is better served on a support-specific forum (e.g. the dart misc group (https://groups.google.com/a/dartlang.org/g/misc?pli=1) or stackoverflow).

However at a high-level I'd structure that with the shared code in one package (`dart create -t package-simple`) and the web app and CLI app then both depending on that package.

**Comment by johnniwinther** [comment] 2022-03-29 20:38
@rrousselGit at version of Dart are you seeing this?

**Comment by rrousselGit** [comment] 2022-03-29 20:54
```
Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"
```

**Comment by rrousselGit** [comment] 2022-03-29 20:58
Switching channel seems to make it disappear, so ignore me 🙈
