### ISSUE TITLE
Analyzer crash.

### ISSUE THREAD

**Issue by whitewalkerking** [dart-lang/sdk#38563] opened 2019-09-25 08:48 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 286, method: edit.getFixes, params: {file: G:\projet\lib\App_Screens\Welcome_Screen.dart, offset: 7}, clientRequestTime: 1569401106520}
FileSystemException: Exists failed, path = 'G:\projet\lib\App_Screens\package\:command_it_deliver_eatApp_Screens\form.dart\.dart_tool\build' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _Directory.existsSync (dart:io/directory_impl.dart:99:7)
#1      _PhysicalResource.exists (package:analyzer/file_system/physical_file_system.dart:370:29)
#2      _OverlayFolder.exists (package:analyzer/file_system/overlay_file_system.dart:295:65)
#3      PackageBuildWorkspace.find (package:analyzer/src/workspace/package_build.dart:320:28)
#4      ContextBuilder.createWorkspace (package:analyzer/src/context/builder.dart:673:36)
#5      new BestPracticesVerifier (package:analyzer/src/generated/resolver.dart:122:24)
#6      LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:276:21)
#7      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:195:11)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:194:15)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:180:35)
#12     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#15     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#17     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#18     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:927:33)
<asynchronous suspension>
#19     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#20     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#21     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#22     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#23     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#24     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#30     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#31     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#32     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#33     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#34     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#35     new Future.sync (dart:async/future.dart:224:31)
#36     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#42     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#43     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#44     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1295:9)
#1      PerformanceLo...
```

For additional log information, please append the contents of
file://C:\Users\ASUS\AppData\Local\Temp\report.txt.

**Comment by parlough** [comment] 2020-05-20 04:28
Duplicate of https://github.com/dart-lang/sdk/issues/37403

**Closed** 2021-02-23 03:10 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
