### ISSUE TITLE
frontend_server process is consuming a lot of memory after Flutter 1.17 upgrade

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#41862] opened 2020-05-12 07:08 UTC
Reports are in https://github.com/dart-lang/sdk/issues/40243

/cc @pcsosinsky for visibility

**Comment by defemz** [comment] 2020-05-12 13:59
Just thought i should add the Task manager for dart process eating up the RAM resource. My experience after updating to flutter 1.17.0 has been horrible compared to previous releases
![image](https://user-images.githubusercontent.com/42694544/81700639-d7696000-9460-11ea-8f09-05fcf1fd4270.png)
The highlighted entry shows the process consuming almost 99% of my RAM. Any solution yet?

**Comment by jensjoha** [comment] 2020-05-12 15:11
Unfortunatley we don't know what's going on yet. But if you can provide a reproduction it could certainly help.

**Comment by Maleesh** [comment] 2020-05-12 16:13
For me, the following two scenarios caused eating memory, 
1. Run, add a new package and run
2. Run, stop and debug

Spec:
Flutter 1.17.0 
Windows 10 Pro

NOTE: Neither flutter clean nor deleting build directory solved the issue permanently. 

And I am sorry that I can't help with memory dump as it happens so quickly and within a few seconds machine freezes.

**Comment by jensjoha** [comment] 2020-05-13 10:29
Unfortunatley I still cannot reproduce.
What is the target? Android? IOS? Web?
Can anyone reproduce with an open source project, or is anyone comfortable sharing code that reproduces this?

**Comment by jensjoha** [comment] 2020-05-13 13:00
I have an experiment, if anyone is willing to perform it.

Apply this patch in flutter:
```
diff --git a/packages/flutter_tools/lib/src/compile.dart b/packages/flutter_tools/lib/src/compile.dart
index cdfa2fc37f..ba7491f091 100644
--- a/packages/flutter_tools/lib/src/compile.dart
+++ b/packages/flutter_tools/lib/src/compile.dart
@@ -107,6 +107,9 @@ class StdoutHandler {
     if (_badState) {
       return;
     }
+    if (message.startsWith('Observatory listening on')) {
+      return;
+    }
     const String kResultPrefix = 'result ';
     if (boundaryKey == null && message.startsWith(kResultPrefix)) {
       boundaryKey = message.substring(kResultPrefix.length);
@@ -706,6 +709,9 @@ class DefaultResidentCompiler implements ResidentCompiler {
     );
     final List<String> command = <String>[
       globals.artifacts.getArtifactPath(Artifact.engineDartBinary),
+      '--old_gen_heap_size=1000',
+      '--enable-vm-service=12345',
+      '--disable-service-auth-codes',
       frontendServer,
       '--sdk-root',
       sdkRoot,
```

Remove the files
* bin/cache/flutter_tools.snapshot
* bin/cache/flutter_tools.stamp

and try again (i.e. `flutter run` etc).

This does a few things:
* It limits the amount of memory that the dart vm "frontend_sever" should be able to use so it hopefully won't crash any computers because of low ram
* it enables observatory for the dart vm "frontend_sever" without the so called 'auth codes' (on port 12345)
* By removing the files it forces a new snapshot to be created (meaning the changes will take effect).

There is some risk that this will simply just not be enought memory (given that you are experiencing huge memory consumptions) and that `flutter run` will fail saying something like

```
Exhausted heap space, trying to allocate 16464 bytes.           
../../third_party/dart/runtime/vm/object.cc: 2583: error: Out of memory.
[...]
```

-- in which case (and if you're computer doesn't crash by doing so) you could update the `-old_gen_heap_size=1000` line to give it more memory.

Now assuming the process doesn't crash and you still get high memory usage, you can open up your browser to http://localhost:12345 --- the so called "dart observatory" where you can do a `heap snapshot` as discusseed in https://github.com/dart-lang/sdk/issues/40243#issuecomment-621558656.
The `allocation profile` could also be interesting (`allocation profile` and click `Download` at the top).

If anyone could share such things with me at `jensj@google.com` that would be great. (It might not be enough to actually get to the root of this (a reproduction would be better), but it certainly won't hurt).

**Comment by jensjoha** [comment] 2020-05-15 13:07
An update: I've found a memory leak (fix in the pipeline at https://dart-review.googlesource.com/c/sdk/+/148240).

I'm not sure it's the memory leak causing these problems though, as the identified memory leak would build over time (for every reload it would use a little more ram) --- whereas (at least some users here) seem to have an issue where memory consumption explodes basically by itself within seconds.

**Comment by Maleesh** [comment] 2020-05-15 15:28
> Unfortunatley I still cannot reproduce.
> What is the target? Android? IOS? Web?
> Can anyone reproduce with an open source project, or is anyone comfortable sharing code that reproduces this?

It is Android for me. 
Update: I have upgraded to 1.17.1 and the issue is still there. I will try to get it recreated with an open source project.

**Comment by mohamed-portalv** [comment] 2020-05-19 04:49
I was using the following version when this issue started happening

> Flutter 1.17.0-3.3.pre • channel beta • https://github.com/flutter/flutter.git
> Framework • revision 0da1ab0922 (3 weeks ago) • 2020-04-28 11:02:34 -0700
> Engine • revision 376ad6a64b
> Tools • Dart 2.8.0

And for now I just downgraded by running `flutter version v1.15.22`

**Comment by jensjoha** [comment] 2020-05-28 12:03
I think that the issue where the frontend_server is slowly using more and more memory is fixed with 86f3fde23fac9684f99200841f95db60bab79d20 (https://dart-review.googlesource.com/c/sdk/+/149280).

There's probably another issue in play for those who are experiencing it using "infinite ram" right away. That issue has probably been fixed with 857fca710fd7b75e5595e198d5fb723f077b4563 (although there's still a question of why it happens in the first place).

As far as I know, none of this has been put on stable though, and therefore hasn't landed in flutter (stable) either. (it will probably also take a while before it lands in flutter master).

**Comment by defemz** [comment] 2020-06-07 08:43
If anyone is still having this problem, flutter 1.17.3 was released a couple of days ago and to the best of my knowledge has totally fixed this memory issue.

**Comment by mohanadshaban** [comment] 2020-06-08 11:08
> If anyone is still having this problem, flutter 1.17.3 was released a couple of days ago and to the best of my knowledge has totally fixed this memory issue. An upgrade to this version should totally solve this issue.

Still the same issue on flutter **1.17.3**

**Comment by jensjoha** [comment] 2020-06-08 11:11
@mohanadshaban sorry to hear that. Could you try to describe exactly what you are experiencing? There's been several different issues mixed up and it would be good to get a handle on exactly what you are running in to. Thanks!

**Comment by mohanadshaban** [comment] 2020-06-08 13:34
> > If anyone is still having this problem, flutter 1.17.3 was released a couple of days ago and to the best of my knowledge has totally fixed this memory issue. An upgrade to this version should totally solve this issue.
> 
> Still the same issue on flutter **1.17.3**

Sorry for false info.
Evreything working fine again after upgrade and doing  **Flutter clean**
Hope it continue to work fine and this issue don't pop out again

**Comment by jensjoha** [comment] 2020-08-03 08:22
@mraleph I think we can close this issue, don't you?

**Closed** 2020-08-03 08:28 UTC
Labels: P1, area-front-end
