### ISSUE TITLE
js-interop: can not use cascade operator on external setter field

### ISSUE THREAD

**Issue by cjkao** [dart-lang/sdk#25163] opened 2015-12-08 14:57 UTC
**Describe the issue you're seeing**

## Chromium
Exception: Class '_Type' has no instance setter 'animation='.  
NoSuchMethodError: method not found: 'animation='  
Receiver: Type: class 'ChartGlobal'  
Arguments: [true]  
## dart2js
Transform Dart2JS on chartjs|web/example.dart threw error: Internal Error: No structure for ChartGlobal  
package:compiler_unsupported/src/compiler.dart 1827                            _CompilerDiagnosticReporter.internalError

**Does it happen in Dartium or when compiled to JavaScript?**
Yes
* Dart SDK version: 1.13.0
* pkg/js version: 0.6.0

Failing code:
```dart
@JS("Chart.defaults.global")
@anonymous
class ChartGlobal {
  external static set animation(bool val); 
}
main(){
  ChartGlobal
    ..animation = true
    ..animation = true;
}
```

**Comment by sigmundch** [comment] 2015-12-08 18:05
Thanks for filing the bug!

Turns out that cascades on statics doesn't do what you expected in Dart. For example, this code will give you the same error in the Dart VM as what you saw in Dartium:
```dart
class A {
  static int x = 0;
}

main() {
  A..x = 2;
}
```
The error is:
```dart
Unhandled exception:
Class '_Type' has no instance setter 'x='.

NoSuchMethodError: method not found: 'x='
Receiver: Type: class 'A'
Arguments: [3]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      main (file:///usr/local/google/home/sigmund/dart/git_all/sdk/_bug2.dart:6:6)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

What happens here is that cascades evaluate the receiver as an expression, then they try to call an instance method on the value of that expression.

That is basically equivalent to write:
```dart
var t = A;
t.x = 2;
```

This is not the same as a static setter call of the form `A.x = 2`. Because when you evaluate `A` as an expression, you get a value that is an instance of `Type`. Types have almost nothing in there: they have .hashCode and ==, but they don't have instance methods that correspond to your static declarations (`t.x` is not there).

The `Internal Error: No structure for ChartGlobal` error is a problem that we should fix though - dart2js should never crash. Turns out this crashes also in the simple example without js-interop, so I have opened this separate bug to track it: https://github.com/dart-lang/sdk/issues/25172

I'm closing this bug because I believe besides #25172, things are working as intended, but feel free to comment/reopen if I missed something.
Cheers!

**Closed by sigmundch** 2015-12-08 18:05 UTC
