### ISSUE TITLE
Allow for typedef a typedef

### ISSUE THREAD

**Issue by feinstein** [dart-lang/sdk#39924] opened 2019-12-25 15:13 UTC
If I try to `typedef` a `typedef` to make it more readable, I get this error:

```dart
typedef ValueSetter<T> = void Function(T value);
typedef GenericCallback<T> = ValueSetter<T>;

```

> Error: Can't create typedef from non-function type.

This should be allowed, as we are just renaming a function alias.

**Comment by eernstg** [comment] 2019-12-27 22:18
The current `typedef` syntax does not admit the `GenericCallback<T>`, so the error is correct. However, it will be allowed with dart-lang/language#65, which is being implemented.

**Comment by eernstg** [comment] 2019-12-27 22:19
I'll close this as a duplicate of the issue about non-function type aliases mentioned above.

**Closed by eernstg** 2019-12-27 22:19 UTC
Labels: closed-duplicate

**Comment by feinstein** [comment] 2019-12-28 22:47
@eernstg but even non generic functions have this:

```dart
typedef MyFunc = int Function();
typedef MyFunc2 = MyFunc;
```

> Error: Can't create typedef from non-function type

**Comment by eernstg** [comment] 2020-01-04 15:09
That error message is misleading, it is an error to have a type on the right hand side of a `typedef` unless it is _syntactically_ a function type, with the current rules. But there is no need to bother making any changes here, because it will all be fixed with the upcoming feature dart-lang/language#65.

**Comment by feinstein** [comment] 2020-01-04 22:48
That's great to know, thanks @eernstg.
