### ISSUE TITLE
dart-sdk 3.1.1 build failure

### ISSUE THREAD

**Issue by chenrui333** [dart-lang/sdk#53464] opened 2023-09-07 22:04 UTC
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
[3576/3760] STAMP obj/runtime/bin/standalone_dart_io.stamp
[3577/3760] LINK ./gen_snapshot_product
[3578/3760] STAMP obj/runtime/bin/standalone_dart_io_product.stamp
[3579/3760] LINK ./dart_precompiled_runtime
ld64.lld: warning: cannot export hidden symbol Dart_LoadELF
>>> defined in obj/runtime/bin/elf_loader.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_LoadELF_Memory
>>> defined in obj/runtime/bin/elf_loader.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_UnloadELF
>>> defined in obj/runtime/bin/elf_loader.elf_loader.o
[3580/3760] STAMP obj/runtime_precompiled.stamp
[3581/3760] COPY exe.stripped/gen_snapshot_product dart-sdk/bin/utils/gen_snapshot
[3582/3760] STAMP obj/sdk/copy_gen_snapshot_exe.stamp
[3583/3760] LINK ./gen_snapshot
[3584/3760] COPY gen_snapshot_product.sym dart-sdk/bin/utils/gen_snapshot.sym
[3585/3760] STAMP obj/sdk/copy_gen_snapshot_sym.stamp
[3586/3760] STAMP obj/sdk/copy_gen_snapshot.stamp
[3587/3760] STAMP obj/utils/compiler/dart2js_create_snapshot_entry.stamp
[3588/3760] ACTION //runtime/bin:generate_snapshot_bin(//build/toolchain/mac:clang_arm64)
[3589/3760] STAMP obj/runtime/bin/generate_snapshot_bin.stamp
[3590/3760] LINK ./dart_precompiled_runtime_product
ld64.lld: warning: cannot export hidden symbol Dart_LoadELF
>>> defined in obj/runtime/bin/elf_loader_product.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_LoadELF_Memory
>>> defined in obj/runtime/bin/elf_loader_product.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_UnloadELF
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6114028210/job/16594795291
relates to Homebrew/homebrew-core#141730

**Comment by ntkme** [comment] 2023-09-08 21:56
Homebrew's own `dart-sdk` formula is completely wrong. Although it did download the source code of 3.1.1 at the beginning, it immediately re-fetched the sdk repo at HEAD (latest main) and then compiling the HEAD instead of 3.1.1. 

It's this line here: https://github.com/Homebrew/homebrew-core/blob/63b16a87ec47595b83f0a0b6c02235f2cd2caed2/Formula/d/dart-sdk.rb#L34

So, it ended up compiling the main branch instead of 3.1.1.

In fact, you can easily see the mistake by installing the current 3.1.0 bottle, that you will find the 3.1.0 bottle is actually 3.2.0-edge compiled from main branch:

```
$ brew install dart-sdk
==> Downloading https://ghcr.io/v2/homebrew/core/dart-sdk/manifests/3.1.0
############################################################################################################################################################################################################### 100.0%
==> Fetching dart-sdk
==> Downloading https://ghcr.io/v2/homebrew/core/dart-sdk/blobs/sha256:c3599284ef1a799432d22967e0ba7c5c05fb6d2495593e6c6128c96918567413
############################################################################################################################################################################################################### 100.0%
==> Pouring dart-sdk--3.1.0.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/dart-sdk/3.1.0: 1,002 files, 580.9MB
==> Running `brew cleanup dart-sdk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ readlink -f $(which dart)
/opt/homebrew/Cellar/dart-sdk/3.1.0/libexec/bin/dart

$ dart --version
Dart SDK version: 3.2.0-edge.f6bc011b37bcef94b53d8c28e3e7ed2ffb33a62e (be) (Wed Aug 16 15:13:47 2023 +0000) on "macos_arm64"
```

---

If you need to install dart from homebrew, you can use this tap maintained by dart team:

``` sh
brew install dart-lang/dart/dart
```

**Comment by a-siva** [comment] 2023-09-08 22:02
Thanks for the investigation @ntkme , closing this issue as 'works as intended'

**Closed by a-siva** 2023-09-08 22:02 UTC
Labels: closed-as-intended
