### ISSUE TITLE
C99 defines bool type which we might want to support in dart:ffi

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#38545] opened 2019-09-24 16:04 UTC
Since C99, the C language has a bool type which we might want to support in `dart:ffi`.

/cc @sjindel-google @dcharkes

**Comment by dcharkes** [comment] 2019-09-24 16:08
Duplicate of https://github.com/dart-lang/sdk/issues/36855.

**Closed by dcharkes** 2019-09-24 16:08 UTC
Labels: area-vm, library-ffi
