### ISSUE TITLE
"warning - The include file cannot be found" when using pedantic with a nested module

### ISSUE THREAD

**Issue by MisterJimson** [dart-lang/sdk#42910] opened 2020-04-16 15:31 UTC
Not sure if the root cause is pedantic but I figured I would start here.

**Issue**
The following warning is returned by `flutter analyze` despite correctly adding `pedantic` as a dependency.
`warning • The include file package:pedantic/analysis_options.yaml in /Users/jrai/git/pedantic_bug/analysis_options.yaml cannot be found • analysis_options.yaml:1:11 • include_file_not_found
`

**Flutter Version**
This is reproducible on Flutter Beta 1.17.0 but not on Flutter Stable v1.12.13+hotfix.9.

**Reproduction Steps**
1. Create a Flutter project.
2. Create a Dart package within the project from step 1's directory.
3. Add the Dart package as a dependency of the Flutter project. 
4. Use the Dart package in the Flutter project.
5. Add pedantic in the Flutter project and create the `analysis_options.yaml` file.
6. `flutter pub get` in both projects
7. `flutter analyze`

Sample repo here: https://github.com/MisterJimson/pedantic-bug
This single commit introduces the issue: https://github.com/MisterJimson/pedantic-bug/commit/5ad95596cf4730398f42a07fba42013baff08de3

**Notes**
Step 4 is required, you need to use some code from the package
Able to reproduce with either pedantic 1.8.0+1 or 1.9.0
If you add pedantic to the Dart package, the issue goes away.

```
jrai@Jasons-MacBook-Pro pedantic_bug % flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-CA)
    • Flutter version 1.17.0 at /Users/jrai/dev/flutter
    • Framework revision d3ed9ec945 (10 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/jrai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 3.5)
    • Android Studio at /Users/jrai/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Users/jrai/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • iPhone 11 Pro • 592B3AFC-563B-4C91-AE69-E57A7F3E0C5C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome        • chrome                               • web-javascript • Google Chrome 81.0.4044.113
    • Web Server    • web-server                           • web-javascript • Flutter Tools


```

**Comment by passsy** [comment] 2020-08-03 19:21
As maintainer of the [`lint`](https://github.com/passsy/dart-lint/) package, I receive this error report almost every week. It's by far the most reported issue.

I'm also facing this issue in all of my multi-module Flutter projects. I'm currently using `Dart version 2.9.0 (build 2.9.0-21.2.beta), Flutter version 1.20.0-7.2.pre`

```
flutterProject/
- analysis_options.yaml
- pubspec.yaml
- pkg/
  someFlutterPackage/
  - analysis_options.yaml
  - pubspec.yaml
  someDartPackage/
  - analysis_options.yaml
  - pubspec.yaml
  ...
```

All packages contain a `pubspec.yaml` with `lint: ^1.1.1` in `dev_dependencies` and `include: package:lint/analysis_options.yaml` in `analysis_options.yaml`.

Analyzer always reports `warning: The include file package:lint/analysis_options.yaml in flutterProject/analysis_options.yaml cannot be found. (include_file_not_found at analysis_options.yaml:1)` for my top-level flutter project via IntelliJ (macOS).

When run via CLI on macOS the error is shown twice 👯 

```
warning • The include file package:lint/analysis_options.yaml in flutterProject/analysis_options.yaml cannot be found • analysis_options.yaml:1:11 • include_file_not_found
warning • The include file package:lint/analysis_options.yaml in flutterProject/analysis_options.yaml cannot be found • analysis_options.yaml:1:11 • include_file_not_found
```

The problem can be fixed temporarily in IDEs by deleting the `include` line, hit save, and add the line again. The error is gone for the current analyzer session and shows up again after restarting the server.

Interestingly, the error doesn't show up on CI (Github Actions, linux). This leads me to believe that it's caused by a timing issue, some form of race condition.

The error exists for quite some time. I remember first seeing it in 2018 in IntelliJ and VSCode. It never showed up in CLI and restarting the analysis server usually resolved it. Not anymore.
Since mid 2020 it is a permanent issue. The behaviour change must be introduced after Dart 2.7

It is now breaking my workflow. I can't use `flutter analyze` as pre-commit hook anymore because it always fails with this annoying warning.

@bwilkerson @matanlurey This issue misses the `analyzer` label

**Comment by maks** [comment] 2020-09-23 06:41
Its not just on macOS, I'm seeing exactly the same thing on Linux as reported by @passsy , including the warning being shown twice! Likewise in VSCode, just editing and saving the `analysis_options.yaml` causes the warning to go away only in VSC until you use the palette `Dart: Restart Analysis Server` command,

But for me that made me suspicious as I happened to have 2 sub directories with dart packages in them while another Flutter app project with no packages inside it did *not* show the warning.

So... I've done some experimenting and seems that it's enough simply to just have a sub-dir in your top-level Flutter package with nothing but a minimal pubspec.yaml:
```
name:  test
description: just a test 
version: 0.0.1
```
to cause running `flutter analyze` at the top level package to show the warning line, once for *every* subdir containing a `pubspec.yaml` 😞 

The good news is that at least I've been able to make `flutter analyze` usable for me in CI and make the warnings go away by adding my package sub-directories to the `exclude:` clause in my `analysis_options.yaml`.

**Comment by kuhnroyal** [comment] 2020-09-30 15:37
I can confirm @maks findings.
This is not a problem in Flutter app projects or libraries/packages that don't contain any sub projects (example).

What always leads to this error is creating a new plugin project and adding any of `lint/pedantic/effective_dart` as the plugin template generates an example folder.
Same thing happens with the package template as soon as one adds an example or other sub project.

**Comment by vysotsky** [comment] 2020-12-28 14:15
Any updates?
I can confirm that the issue still persists. What's weird is that IDEA can read the file and CI works fine as well... But when running `flutter analyze` locally, it will display `include_file_not_found`.

**Comment by AlmogRnD** [comment] 2021-01-08 14:44
Following I'm also having this issue, is there a workaround for now?

**Comment by nerd0geek1** [comment] 2021-01-30 13:46
I also encounter the same issue.
And I noticed that when I add `intl_translation: any` on `dev_dependencies:`, that error message looks suppressed, but I don’t know why.

**Comment by rttolipas** [comment] 2021-02-03 06:28
any workaround here?

**Comment by asartalo** [comment] 2021-02-16 08:49
@rttolipas I know of 2 at the moment:

1. Exclude the nested packages from the analyzer and then re-include them in the nested packages' analysis_options.yaml.
2. Manually copying the contents of the analysis `package:pedantic/analysis_options.yaml` locally into the your analysis_options.yaml. You can put the contents on a separate file and point to it on your analysis_options.yaml like what I do:

```yaml

# include: package:lint/analysis_options.yaml
# Copy the contents of package:lint/analysis_options.yaml into lint_analysis_options.yaml
include: lint_analysis_options.yaml
...
```
I'm tracking this issue for now and will undo the workaround when this gets fixed.

**Comment by minhqdao** [comment] 2021-03-13 01:29
I'm using the lint package and the problem appeared when packages were manually imported to the project. The workaround for me was to add the lint package as dev_dependency to all manually imported packages as well as a completely empty analysis_options.yaml file to each package folder. The empty file prevents lint to show up warnings that are inherent to the packages.

And analysis issues were no more.

**Comment by minhqdao** [comment] 2021-03-13 01:48
I'm using the lint package and the problem appeared when packages were manually imported to the project (not as pub dependencies). The workaround for me was to make sure that every package import has at least an empty analysis_options.yaml file in its folder. You don't even have to import linter dependencies, but simply the presence of an analysis_options.yaml file (completely empty, even without include) sufficed to suppress all analyzer errors for me. Seems like the analyzer looks for the analysis_options.yaml file in all package subdirectories, although it is certainly not supposed to.

Let me know, if this helped for you, too.

**Comment by makstheimba** [comment] 2021-04-30 13:34
@minhqdao, Thanks! Your solution worked for me

**Comment by bsutton** [comment] 2021-06-01 04:31
The attached project demonstrates the problem (or at least one variant) on Ubuntu 21.04 using dart 2.13.

I've tried moving the project into /tmp so it has no parent directory and encounter the same error.

```bash
dart analyze
Analyzing isolate_exec...              1.5s

warning • analysis_options.yaml:2:10 • The include file package:lint/analysis_options.yaml in
          .../isolate_exec/analysis_options.yaml cannot be found. • include_file_not_found

1 issue found.
```

This problem occurs every time.

It would appear that the nested package test_package cause the problem because if I rename the directory (.test_package) then the problem goes away.

Adding an analysis_options.yaml to the test_package project and a dev dependency on lint in the pubspec for the test_package did not fix the problem.

I also tried moving the test_package into the project root but no change.

The only way I found to fix the problem was to move the test_package out of the isolate_exe package.



[isolate_exe.zip](https://github.com/dart-lang/sdk/files/6573303/isolate_exe.zip)

**Comment by minhqdao** [comment] 2021-06-01 08:39
@bsutton I had a look at your project. Adding an empty analysis_options.yaml file to the `isolate_exec/test_package` folder fixes your problem. Just do so with `touch anaylysis_options.yaml` inside `isolate_exec/test_package`.

**Comment by MisterJimson** [comment] 2021-06-01 11:58
@minhqdao I believe thats why this issue is still open, to resolve the need for that workaround. (Treat no analysis_options file as an empty one.)

**Comment by minhqdao** [comment] 2021-06-01 12:23
@MisterJimson Yes, that would certainly be the most desirable solution. But as long this problem exists, adding an empty file is a rather small workaround as compared to revamping your entire folder structure.

**Comment by DarkMikey** [comment] 2021-06-01 12:34
I'm not quite sure if the workaround is working for this kind of structure:

```.
├── app
│   ├── pubspec.yaml
│   ├── lib
│   └── analysis_options.yaml (contains "include: package:lint/analysis_options.yaml")
└── repository (pure dart)
    ├── pubspec.yaml
    ├── lib
    └── analysis_options.yaml (contains "include: ../app/analysis_options.yaml" or "include: package: app/analysis_options.yaml")
```

Any experiences?

**Comment by bsutton** [comment] 2021-06-01 22:36
I tried this structure and still got the same error.

**Comment by bsutton** [comment] 2021-06-01 22:48
Ok I didn't try an empty on.

Given the repeatability of the error I'm confused as to why we don't have a
good for this?
I gather there may be a couple of different issue here but can we not get a
fix for the reproducible ones?

**Comment by bsutton** [comment] 2021-06-01 22:50
I assume the will fix the error message to report the correct sub directory
path.

**Comment by lukepighetti** [comment] 2021-06-03 15:22
Interestingly I got this error when we had a sub-project where all checked in files were removed, but there were dangling generated files and I believe a `.packages` file

**Comment by cyc2303** [comment] 2021-06-17 08:44
Any updates?

**Comment by nickmeinhold** [comment] 2021-06-25 01:33
> Interestingly I got this error when we had a sub-folder project where all checked in files were removed, but there were dangling generated files and I believe a .packages file

This turned out to be the problem for me, thanks @lukepighetti

**Comment by MaZzenGamal** [comment] 2021-09-27 11:13
> I think the directory structure we're looking at looks like the following:
> 
> ```
> flutterProject
>   analysis_options.yaml
>   pubspec.haml
>   dartPackage
>     pubspec.yaml
> ```
> 
> Is that correct? And is it the case that the dependency on pedantic was added to the `pubspec.yaml` file in `flutterProject` but not the `pubspec.yaml` file in `dartPackage`?
> 
> If so, then the problem is the missing dependency in the `pubspec.yaml` file in `dartPackage`. The `pubspec.yaml` file determines how to resolve `package:` URIs, and the code in the `dartPackage` will "inherit" the `analysis_options.yaml` file from the parent directory, but will use it's local resolution of URIs to try to resolve the reference to `package:pedantic` and fail because there is no binding for it.

i couldnt reach this directory

**Comment by rubgithub** [comment] 2022-04-25 16:11
![image](https://user-images.githubusercontent.com/3399476/165128696-c4a26110-74a8-490a-b7bf-b10724b45ee5.png)

I've solved this problem by adding `flutter_lints` to my dependencies

It's not the perfect (duplicating imports in both libs) solution but the annoying message disappears.

**Comment by srawlins** [comment] 2024-07-26 18:57
A long and old ticket that may be solved by the new "workspaces" work; @keertip @pq

**Comment by pq** [comment] 2024-07-30 16:22
Yeah. I think this is fixed w/ @keertip's work. Closing optimistically.

**Closed by pq** 2024-07-30 16:22 UTC
Labels: area-analyzer, P2, type-bug, analyzer-analysis-options

**Comment by stan-at-work** [comment] 2025-12-17 16:18
This is still an issue in dart: 

```
Dart 3.9.2 (stable) (Wed Aug 27 03:49:40 2025 -0700) on "windows_x64"
- on windows / "Windows 11 Pro" 10.0 (Build 26200)
```
