### ISSUE TITLE
flaky underlying VM issue?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#26618] opened 2016-06-03 20:54 UTC
Not sure yet how to interpret this failure. 

See [this log](https://build.chromium.org/p/client.dart/builders/dart2js-linux-jsshell-1-4-be/builds/1310/steps/steps/logs/stdio/text) and the failed test: "library_juxtaposition_test"

I get an error of this form:
```
NoSuchMethodError: method not found: 'slowToString'
Receiver: Instance of 'StringJuxtaposition'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _LibraryLoaderTask.processLibraryTags.<anonymous closure>.<anonymous closure> (file:///b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/pkg/compiler/lib/src/library_loader.dart:531:57)
#3      CompilerDiagnosticReporter.withCurrentElement (file:///b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/pkg/compiler/lib/src/compiler.dart:1570:15)
#4      _LibraryLoaderTask.processLibraryTags.<anonymous closure> (file:///b/build/slave/dart2js-linux-jsshell-1-4-be/build/sdk/pkg/compiler/lib/src/library_loader.dart:468:23)
#5      Future.forEach.<anonymous closure>.<anonymous closure> (dart:async/future.dart:361)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      Future.forEach.<anonymous closure> (dart:async/future.dart:361)
#8      Future.Future.sync (dart:async/future.dart:168)
#9      Future.doWhile.<anonymous closure> (dart:async/future.dart:387)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#11     _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1170)
#12     _RootZone.runUnary (dart:async/zone.dart:1204)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#16     _Future._completeWithValue (dart:async/future_impl.dart:477)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

This is flaky and I am not able to reproduce locally.

The class StringJuxtaposition indeed doesn't have that method, but it contains a `DartString` object that does. The code in LibraryLoaderTask  @ line 531 is actually accessing the `DartString` object. Could it be that background compilation is doing something invalid here?

**Comment by fsc8000** [comment] 2016-06-05 12:57
Possibly a dupliate of #26558. @mraleph Have you seen this one locally before?

**Comment by mraleph** [comment] 2016-06-06 04:16
Yes, I think it is the same issue. It happens to me locally but it is even more rare then another one. And I could not precisely pinpoint the misoptimization there - even though I have a core of this. I think it's a duplicate. I am still looking into #26558

**Comment by eernstg** [comment] 2016-06-06 07:25
I had a similar error locally in the same test, with this stack trace (essentially the same):

```
The compiler crashed: Class 'StringJuxtaposition' has no instance method 'slowToString'.

NoSuchMethodError: method not found: 'slowToString'
Receiver: Instance of 'StringJuxtaposition'
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _LibraryLoaderTask.processLibraryTags.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/compiler/lib/src/library_loader.dart:531:57)
#3      CompilerDiagnosticReporter.withCurrentElement (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/compiler/lib/src/compiler.dart:1570:15)
#4      _LibraryLoaderTask.processLibraryTags.<anonymous closure> (file:///usr/local/google/home/eernst/devel/dart/test/sdk/pkg/compiler/lib/src/library_loader.dart:468:23)
#5      Future.forEach.<anonymous closure>.<anonymous closure> (dart:async/future.dart:361)
#6      Future.Future.sync (dart:async/future.dart:168)
#7      Future.forEach.<anonymous closure> (dart:async/future.dart:361)
#8      Future.Future.sync (dart:async/future.dart:168)
#9      Future.doWhile.<anonymous closure> (dart:async/future.dart:387)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#11     _RootZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1170)
#12     _RootZone.runUnary (dart:async/zone.dart:1204)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#16     _Future._completeWithValue (dart:async/future_impl.dart:477)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by mraleph** [comment] 2016-06-06 14:47
I am going to close this as Duplicate of Issue #26558. 

Please report new crashes there.

**Closed by mraleph** 2016-06-06 14:47 UTC
Labels: area-vm, Resolution: duplicate
