### ISSUE TITLE
Add right shift operator for int64

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32838] opened 2018-04-10 23:46 UTC
Non-breaking missing addition to int64:

"We will need front-end support to add `>>>` as an operator (probably even a constant operator), and I don't believe it is there yet."

**Comment by lrhn** [comment] 2018-04-11 07:53
The `>>>` operator is already in defined in the specification.

**Comment by lrhn** [comment] 2018-04-11 07:58
Duplicate of #30888 (and related) issues.

**Comment by lrhn** [comment] 2018-11-20 11:43
This covers the actual use of the operator on the `int` class. It is blocked on #30886.

**Closed** 2020-10-02 08:07 UTC
Labels: area-library, closed-duplicate, library-core, type-task
