### ISSUE TITLE
Do not report dead-code hint for unreachable return in case block

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#34598] opened 2018-09-27 01:17 UTC
Dart VM version: 2.0.0-dev.61.0 (Mon Jun 11 15:46:09 2018 +0200) on "macos_x64"

> Error: Switch case may fall through to the next case.
error: The last statement of the 'case' should be 'break', 'continue', 'rethrow', 'return' or 'throw'. (case_block_not_terminated at [sms_and_contacts_db_importer] lib/ui/preview_list_view.dart:35)
<img width="809" alt="screen shot 2018-09-26 at 6 17 07 pm" src="https://user-images.githubusercontent.com/23037821/46117866-6f490600-c1b8-11e8-959c-17d4181c60aa.png">
<img width="655" alt="screen shot 2018-09-26 at 6 16 39 pm" src="https://user-images.githubusercontent.com/23037821/46117867-6f490600-c1b8-11e8-957e-0e082b7889c5.png">

Code:
```
               switch (selectedOption) {
                    case Option.SMS:
                      {
                        return SmsListViewBuilder(data: snapshot.data);
                      }
                    case Option.CONTACTS: //<----- Error shows up here
                      {
                        if (snapshot.data[0] is Contact) {
                          return new ContactListViewBuilder();
                        } else {
                          return Container();
                        }
                        //<---- because there's no break here. But if I add a break here, 
                        // the linter says it's dead code.
                      }
                    default:
                      return Container();
                  }
```

**Comment by lrhn** [comment] 2018-09-27 07:45
Sadly this is how the language is currently specified.

The Dart specification does not have any notion of reachability, so the way it specifies that code must not reach the end of a switch case is that:
 * if the code is a sequence of statements, the last statement must be a control-flow statement (return/break/continue/throw/rethrow), or
 * the last statement must be single block statement, and then the last statement of that block must be a control-flow statement.

Otherwise it's a compile-time error.

Your return is nested inside an `if` statement inside a block, so it doesn't satisfy the language requirement.

The dead-code removal warning is wrong. It's not that it's not dead code, it's just that removing it will make the program not compile.

Another way to rewrite the code is:
```dart
  case Option.CONTACTS:
    if (snapshot.data[0] is Contact) {
      return new ContactListViewBuilder();
    }
    return Container();
```
(and you can add a surrounding block if you prefer that).

It's an annoying rule, and we hope to be able to remove it eventually. A proper in-specification definition of reachability would allow better type promotion as well.

**Comment by ThinkDigitalRepair** [comment] 2018-09-27 08:13
Thanks again!

**Comment by srawlins** [comment] 2019-10-21 17:44
Duplicate of https://github.com/dart-lang/sdk/issues/28042

**Closed by srawlins** 2019-10-21 17:44 UTC
Labels: P2, analyzer-hint, area-analyzer, type-enhancement
