### ISSUE TITLE
Found element with null library

### ISSUE THREAD

**Issue by yolkhovyy** [dart-lang/sdk#35895] opened 2019-02-10 06:13 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.0.0`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-45-generic unknown, screens 2560x1080`

## Exception
```
Dart analysis server, SDK version 2.0.0, server version 1.20.3, error: Found element with null library: State
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:849:31)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44:12)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:292:16)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2319:49)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:5715:10)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2319:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8219:20)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2242:17)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6361:10)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4901:18)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:2943:35)
#11     ResolverVisitor.safelyVisitComment (package:analyzer/src/generated/resolver.dart:5431:13)
#12     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:6105:5)
#13     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7693:7)
#14     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:6094:13)
#15     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5279:49)
#16     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:5732:25)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2506:49)
#18     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:711:10)
#19     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:130:9)
#20     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#21     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:129:13)
#22     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:104:16)
<asynchronous suspension>
#23     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#24     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:98:43)
<asynchronous suspension>
#25     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1283:71)
<asynchronous suspension>
#26     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#27     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1240:20)
<asynchronous suspension>
#28     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1331:43)
<asynchronous suspension>
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:958:45)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2005:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1946:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:402:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:441:19)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:483:12)
#41     Driver.start (package:analysis_server/src/server/driver.dart:440:5)
#42     main (file:///b/build/slave/dart-sdk-linux-stable/build/sdk/pkg/analysis_server/bin/server.dart:12:11)
#43     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by DanTup** [comment] 2019-10-09 14:48
Not sure if it's the same thing (since this one says `WidgetTester`), but I just had this in the logs for Dart-Code's integration tests running on GitHub Actions (macOS).

```
[Analyzer] Found element with null library: WidgetTester

[Analyzer] null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:428:31)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44:12)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:263:16)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:1965:49)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:3600:10)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:1965:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1904:17)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4296:10)
#9      UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:3152:35)
#10     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:3591:11)
#11     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:1900:49)
#12     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5279:32)
#13     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5259:11)
#14     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3572:13)
#15     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#16     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3614:23)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#18     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:660:10)
#19     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:151:7)
#20     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
```

Only recently started setting up on GH Actions, so not sure if it'll reproduce.

**Comment by srawlins** [comment] 2019-11-27 05:23
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37987; please follow along there.

**Comment by srawlins** [comment] 2019-11-27 05:23
Duplicate of https://github.com/dart-lang/sdk/issues/37987

**Closed by srawlins** 2019-11-27 05:23 UTC
Labels: P2, analyzer-crash-report, area-analyzer, type-bug
