### ISSUE TITLE
Dart incorrectly infers type as `dynamic` when a generic function is given a value

### ISSUE THREAD

**Issue by skreborn** [dart-lang/sdk#36749] opened 2019-04-25 14:29 UTC
The following example showcases the issue (also available on [DartPad](https://dartpad.dartlang.org/d23cb9a855078d3757e77f6f358d726e)).

```dart
abstract class Provider<T> {
  T get bar;
}

class StringProvider extends Provider<String> {
  String get bar => 'bar';
}

class NumberProvider extends Provider<int> {
  int get bar => 42;
}

class Foo {
  final T Function<T>(Provider<T> provider) provide;

  const Foo({ this.provide });
}

void main() {
  final foo = Foo(provide: (provider) => provider.bar);

  String strValue = foo.provide(StringProvider()); // should be 'bar'
  int numValue = foo.provide(NumberProvider()); // should be 42
}
```

The following line:

```dart
final foo = Foo(provide: (provider) => provider.bar);
```

Raises the following error:

```text
Error: The argument type 'dynamic Function(Provider<dynamic>)' can't be assigned to the parameter type 'T Function<T>(Provider<T>)'.
```

I believe that this behavior is incorrect, since Dart can actually infer the correct types on the calling site, meaning that `foo.provide(StringProvider())` does indeed return a `String` and using `NumberProvider` returns an integer as expected.

The type system can be helped out with adding just a tiny bit of extra information when defining the value, but this should probably be done automatically and not require suck a "hack".

```dart
final foo = Foo(provide: <int>(provider) => provider.bar);
```

Any type except `dynamic` is allowed here in the place of `int`, but something _has_ to be given for Dart to stop complaining.

The fixed version is also available on [DartPad](https://dartpad.dartlang.org/204d6e17193e48bf850a67b85d7bf062).

My Dart SDK version is **2.3.0-dev.0.1**.

---

For the StackOverflow question that originated this issue report, please click [here](https://stackoverflow.com/questions/55848042/callback-with-generic-type-parameter-in-dart/).

Apologies if this is a duplicate issue. I've read through a couple of (possibly) related reports, but none seemed to match my exact case. In case I've missed something, please feel free to consolidate.

**Comment by eernstg** [comment] 2019-04-25 14:49
Try [this](https://dartpad.dartlang.org/d23cb9a855078d3757e77f6f358d726e): `final foo = Foo(provide: <T>(Provider<T> provider) => provider.bar);`!

The problem is that you're passing a non-generic function to the `Foo` constructor, and you should pass a generic function. There is no subtype relationship between a generic function type and a non-generic function type, so according to the type checker you might as well pass a `String`, and that's the reason for the 'can't be assigned to' message.

**Comment by skreborn** [comment] 2019-04-25 15:03
@eernstg Thank you for the quick response! It turns out that simply adding <T> before the parameter list solved the issue.

```dart
final foo = Foo(provide: <T>(provider) => provider.bar);
```

This forces Dart to understand that `provider` is of type `Provider<T>`.

Should I close the issue?

**Comment by eernstg** [comment] 2019-04-25 16:08
The story is slightly longer. The original fix you mentioned was using `<int>(provider) => provider.bar`. That denotes a generic function accepting a type argument named `int` (not a good choice of name, but also not an error!). The argument type and return type are subject to inference, and the resulting type is `int Function<int>(Provider<int>)`, which, of course, ought to be written like `T Function<T>(Provider<T>)`.

So the fact that you declare a type parameter makes the function generic, and the fact that you're passing that function literal to a receiver that wants a function of type `S Function<S>(Provider<S>)` helps type inference to fill in the blanks. So "it just works" as soon as you add `<SomeName>`. ;-)

However, you rely on inference for that, so it won't work if you don't have that context:

```dart
main() {
  var f = <T>(provider) => provider.bar;
  print(f.runtimeType); // Prints '<T1>(dynamic) => dynamic'.
}
```

It would _not_ work to pass a function of that type to the constructor of a new `Foo`, so it's crucial that you're passing the function literal directly as a constructor argument, such that it's subject to type inference relative to the type `T Function<T>(Provider<T>)`.

In any case, it's all working as intended, so we should close the issue.

**Closed by eernstg** 2019-04-25 16:08 UTC
