### ISSUE TITLE
Lost connection to device

### ISSUE THREAD

**Issue by kevinxxq** [dart-lang/sdk#47925] opened 2021-12-14 16:41 UTC
Hi All,
This tracker is for issues related to:
* Dart VM

If you aren't sure, file the issue here and we'll find the right home for it.
In your issue, please include:

* Dart SDK Version (`dart --version`)  ----**Dart SDK version: 2.15.0**
* Whether you are using Windows, MacOSX, or Linux (if applicable)   --- **Windows**
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)  ---Debug for For Windows device on itself

The IDE is VS Code.

The error is:
[+209619 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.

Log file:
[log.txt](https://github.com/dart-lang/sdk/files/7713252/log.txt)
[Dart-Code-Log-2021-11-02 11-53-44.txt](https://github.com/dart-lang/sdk/files/7713399/Dart-Code-Log-2021-11-02.11-53-44.txt)

Looks like there was a breaking point hit then block the communication(between debugger and VM service), I turned on exceptions catching as below:
![image](https://user-images.githubusercontent.com/55800697/146040789-96792e15-5584-4cc2-bdd9-04566678f5d8.png)

Thank you.

**Comment by stevemessick** [comment] 2021-12-14 22:26
@DanTup Does this look like a VS Code issue, or something in the service protocol, do you think?

**Comment by kevinxxq** [comment] 2021-12-15 02:52
Thank you. As I suspect, there may be some exceptions are not handled by VS code and block the communication.

When I run it on Android Studio, it hits an exception as below:
======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1284:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1308:6)
#2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1223:14)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:815:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:749:5)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
#7      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:494:12)

Just fixed it and no "Lost Connection to device" took place. But I saw the very short time screen to show my app hit another exception and crashed for the same error(Lost connection to device).

So would you please check the timeout threshold for exception(two possible reasons: 1). it can't hit some exceptions or not all exceptions are logged 2). the timeout threshold is too short).

My additional question is whether the VM service is the same on Android Studio/VS code?

Thank you.
Thank you.

**Comment by DanTup** [comment] 2021-12-15 11:26
> @DanTup Does this look like a VS Code issue, or something in the service protocol, do you think?

From the log it seems like the Flutter app is terminating (perhaps crashing)? I don't think the issue is in VS Code (although perhaps some timing or behaviour differences are triggering it).

@kevinxxq when you tested in Android Studio, were you running _with debugging_, or without? The VM Service is the same for both editors, although there may be some small differences in the calls (or timing of the calls) each editor makes to the VM Service.

When this occurs, does the (Windows desktop) app vanish? Does it show any message? If not, is there anything in your Windows Event Viewer that might give more information of the application crashed?

(I think this issue may be better at https://github.com/flutter/flutter/ than here)

**Comment by kevinxxq** [comment] 2021-12-15 14:57
> 

Thank you, Danny. 
1. I am running Android Studio with debugging. Thank you for conformation they are working with the same VM Service.
2. The (Windows desktop) app can be running like a release one if there is no obvious exceptions, otherwise it will show no response. No other message. I checked Event Log and no logs related of the App, may be in a different name, I am not sure and not good at it, perhaps to produce one or two lines of log to system's event log.
3. Yesterday I tried to get a minimum reproduce project with just one exception on the counter project but failed(The exception can be hit) may be my project is too heavy(large) to respond to some exceptions then lead to the timeout(lost connection).

I can reproduce the error if I set it back to "The provided ScrollController is currently attached to more than one ScrollPosition." on my heavy project.
Here is a new log on VS code, hope luck to find something.
[log.txt](https://github.com/dart-lang/sdk/files/7720343/log.txt)
[Dart-Code-Log-2021-11-03 09-39-44.txt](https://github.com/dart-lang/sdk/files/7720360/Dart-Code-Log-2021-11-03.09-39-44.txt)

The result: Debugging on VS code and Android Studio can hit the exception, VS code will crash but Android Studio just show exception without crash.

Sorry for my additional question, vs code/Android Studio use the same debugging tools or configuration?

I found a message on VS code shows timeout is 2000ms, is it the threshold? where can I change it? It may be not enough for user to click F5 when there is exception(the lost connection takes place when I finished clicking F5 .

Thank you.

p.s.: I tried to move this to Flutter issues but it is too difficult to get a reproduce example.

**Comment by DanTup** [comment] 2021-12-15 15:36
There's nothing obvious in the logs. I see the same error is reported at 9:45:25

```
[上午9:42:25] [DAP] [Info] ==> {"seq":5598,"type":"event","event":"output","body":{"category":"stderr","output":"════════ Exception caught by animation library ═════════════════════════════════\n"}}
[上午9:42:25] [DAP] [Info] ==> {"seq":5599,"type":"event","event":"output","body":{"category":"stderr","output":"The provided ScrollController is currently attached to more than one ScrollPosition.\n"}}
[上午9:42:25] [DAP] [Info] ==> {"seq":5600,"type":"event","event":"output","body":{"category":"stderr","output":"════════════════════════════════════════════════════════════════════════════════\n"}}
```

Then there are a few frame events, then nothing happens for 11 seconds and then:

```
[上午9:42:36] [DAP] [Info] ==> {"seq":5620,"type":"event","event":"dart.log","body":{"message":"VM service connection closed: 1005 ()","severity":0,"category":10}}
```

> vs code/Android Studio use the same debugging tools or configuration?

Generally, yes. Though the code that interacts with the VM Service is separate, so there are likely some differences between them.

> I found a message on VS code shows timeout is 2000ms, is it the threshold? 

I'm not aware of any 2s timeouts here - where did you see this?

Are you able to make a copy of your project and remove anything sensitive, to get to a point where you have a project you could share that still reproduces the issue?

**Comment by kevinxxq** [comment] 2021-12-15 18:40
I searched the original log I posted but no errors or exception, so they may be not the same reason. It is a good start for me to know the exceptions can be logged.

OK I will try to simplify my project to reproduce the error "Lost Connection to Device".

> I'm not aware of any 2s timeouts here - where did you see this?
I saw it only once on the right-bottom corner, it is one line floating message bar without cancel button, it is only about 5s,too short to take a screen snapshot.

Right now, I can produce(Not sure it can be reproduced many times) the error with a small project:
[Dart-Code-Log-2021-11-03 13-17-18.txt](https://github.com/dart-lang/sdk/files/7721859/Dart-Code-Log-2021-11-03.13-17-18.txt)
[Dart-Code-Log-2021-11-03 13-25-27.txt](https://github.com/dart-lang/sdk/files/7721884/Dart-Code-Log-2021-11-03.13-25-27.txt)

the error on debug console is the same as before:
[   +5 ms] Connected to _flutterView/0x29761756220.
Connecting to VM Service at ws://127.0.0.1:59123/qOcWxnd13Bg=/ws
[+67316 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.

The screen snapshot on Widget Inspector page:
![image](https://user-images.githubusercontent.com/55800697/146244140-3baac887-5ea1-4c25-b2bb-f52e4a2165fa.png)

I just uploaded the simple project, you can try it, just debug it and try to open the end drawer and click the + button. Hope you can reproduce it.
[test_lost_connection.zip](https://github.com/dart-lang/sdk/files/7721918/test_lost_connection.zip)

Oh my god, it can disconnect with device without any clicking/touching.
![image](https://user-images.githubusercontent.com/55800697/146245860-3b97f5fb-a928-44e4-86e3-e62d07797537.png)

Thank you.

**Comment by a-siva** [comment] 2021-12-16 19:01
@kevinxxq can you attach the output from adb here so we can see if the flutter engine crashed resulting in this lost connection

**Comment by kevinxxq** [comment] 2021-12-16 20:07
> @kevinxxq can you attach the output from adb here so we can see if the flutter engine crashed resulting in this lost connection

Hi, @a-siva Thank you involved in this issue. Sorry I don't know what it is. Do you mean https://developer.android.com/studio/command-line/adb? How can I get the output from adb?
I am working on Win10 for Windows desktop. 
The problem looks like more frequently on vs code than Android Studio. 

Sorry I just run Flutter clean to make the zip file small enough. If you tell me how can I get it, I will run it again.

Thank you.

**Comment by a-siva** [comment] 2021-12-16 20:39
I presume you are using an Android device to run your app
'adb logcat' would give you the device logs and it would have info if the engine process crashed on the device.

**Comment by a-siva** [comment] 2022-01-12 21:16
@kevinxxq  Any updates on getting the log files from 'adb logcat' when this happens?

**Comment by kevinxxq** [comment] 2022-01-12 23:29
@a-siva  Thank you still remember this issue. I am working on Windows desktop and have no chance to run it with Android, Do you think it possible to get log files from 'adb logcat'? I am sorry I don't know that kind of setting.

> 

I uploaded a counter app last time and it has this issue too.
Would you please have a try with that app? Thank you.

Currently, the issue is still on my project, I should run it via Android Studio which works well.

**Comment by AndreLuizNogueira** [comment] 2023-08-23 19:14
> it

Did you find a solution? I have this problem too, running on Windows 11 in vscode, it mainly occurs when I change something in the code and hot reload it. Using Android Studio slows down the events, but it still happens. I've been ignoring this problem in my project for a few months now... I spend a lot of time restarting the app to where it was.

**Comment by a-siva** [comment] 2023-11-10 22:40
Closing issue as not much progress can be made without more information, if you are encountering a 'lost connection to device' error please upload the output from 'adb logcat' on the device. This will help is figure out if the Flutter engine process on the device crashed or not (please reopen the issue with log if available).

**Closed by a-siva** 2023-11-10 22:40 UTC
Labels: area-vm
