### ISSUE TITLE
dart2js should inline code checking for assertions

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#24355] opened 2015-09-15 02:11 UTC
This function is currently not inlined because `dart2js` considers it too long for inlining:

``` dart
bool assertionsEnabled() {
  bool k = false;
  assert(() => k = true);
  return k;
}
```

As this is the shortest way, that I know of, to check if assertions are enabled I think it would be reasonable for dart2js to special-case this pattern and inline it. This would be very useful to support development-time only code, such as long error messages, long stack traces, and debug info.

Currently this prevents Angular 2 from tree shaking the `stack_trace` library in production output despite the fact that assertions are disabled in production mode.

**Comment by rakudrama** [comment] 2015-09-15 02:34
Are you mostly interested in getting better tree shaking when assertions are disabled?
If the inliner heuristics were taught to ignore the size of asserts in production mode, the following would be small enough to inline.

This should be easy to implement as asserts were recently given their own Ast node.

```dart
bool assertionsEnabled() {
  bool k = false;
  assert((k = true));
  return k;
}
```

**Comment by rakudrama** [comment] 2015-09-15 02:43
Minor correction: the Assert Ast node CL has not yet landed: https://codereview.chromium.org/1325843003/

**Comment by yjbanov** [comment] 2015-09-15 03:47
Yes, tree shaking is what I'm going for.

Also, related to my problem is https://github.com/dart-lang/sdk/issues/24354

**Comment by rakudrama** [comment] 2015-09-15 04:19
Sorry, I didn't state my question clearly enough.
Would you be interested in better tree shaking, but only in production mode, and no improvement in checked mode?  This is what could be achieved in a 'quick fix' when the new assert syntax CL lands.

**Comment by yjbanov** [comment] 2015-09-15 16:50
That's correct. Better tree shaking in production mode is the goal. The pattern we're going for is:

```dart
if (assertionsEnabled()) {
  // do things and use libraries that only matter during development
}
```

When compiling for production everything inside the above `if` block would go away along with its dependencies. For example, in development mode (when assertions are enabled) Angular 2 uses the `stack_strace` package to print long exception stack traces. In production mode assertions are disabled and we want to tree shake off everything related to long stack trace logic as well as the `stack_trace` library itself.

**Comment by sethladd** [comment] 2015-09-15 16:51
Could it help to use something like http://blog.sethladd.com/2013/12/compile-time-dead-code-elimination-with.html ?

**Comment by yjbanov** [comment] 2015-09-15 17:00
@sethladd This is an interesting idea. We rely on pub's `--mode=(debug|release)`. It would be weird to have multiple flags to specify debug/prod mode. Do you happen to know if `--mode` is passed via `String.fromEnvironment`? We could also make compiler-specific `const` options available to the Dart program via something like `CompilerOptions`. Then:

```dart
if (CompilerOptions.inDebugMode) {
  // ... debug code ...
}
```

It would be more explicit compared to relying on a hidden tree shaking optimization, but it requires standard library change.

**Comment by sethladd** [comment] 2015-09-15 17:14
> It would be weird to have multiple flags to specify debug/prod mode

Yeah, maybe, but small price to pay IMO. :)

**Comment by yjbanov** [comment] 2015-09-15 17:20
If it were only the Angular team paying the price, I'd be ok with that. But it's the users who will have to pay the price, and they will have to pay it repeatedly ("How do I enable debug mode again? Was it `pub --mode=debug`? Hmm, that only worked partially. Let me go read Angular docs/ask stackoverflow/etc.").

**Comment by rakudrama** [comment] 2015-09-15 17:33
We will make the assert trick work better when the CL it depends on has landed.

**Comment by sethladd** [comment] 2015-09-15 17:35
Part of the issue is, "debug mode" is a pub only thing. The rest of the platform doesn't know what that means. Heck, I don't even know what debug mode's definition/semantics are. :) I just know that I want it if I'm developing a web app with pub.

**Comment by yjbanov** [comment] 2015-09-15 17:40
@sethladd, that's true, but in the end it translates to assertions being enabled or not, so just checking for assertions gives you simultaneous access to `dart --checked`, `dart2js --checked`, _and_ `pub build --mode=debug`. That's too tempting to pass the assertions-based solution in favor of something custom.

**Comment by lrhn** [comment] 2015-09-16 07:48
Would it make sense to add a static `Isolate.checkedMode` getter, so you don't have to do the `bool isChecked = false; assert((isChecked = true));` dance.

I do it myself, at least in tests. If the feature is possible and it's being used, why not make it accessible as well.

(I believe the VM can enable type checks and assertions individually, not corresponding to any official mode, and you might get incorrect results if that happens. Since it's already incorrect behavior from the compiler, I can live with that).

**Comment by yjbanov** [comment] 2015-09-16 18:28
@lrhn: Having a getter would be ideal, but it will mean changing library APIs and us having to wait for the next stable release. An optimization could be pushed to stable as a non-breaking patch.

I'd be concerned about adding the getter to `Isolate`. Dart for Web is moving away from the isolate API and terminology in favor of standard browser concepts (web workers, etc). [Platform](https://api.dartlang.org/1.12.1/dart-io/Platform-class.html) might be a better host for such a getter.

**Comment by sethladd** [comment] 2015-09-16 18:36
+1 for Platform. There's a Platform in dart:html and dart:io.

**Comment by rakudrama** [comment] 2015-09-17 02:52
CL under preparation: https://codereview.chromium.org/1345413002/

**Comment by zoechi** [comment] 2015-09-17 05:05
Checked mode is per isolate, is Platform also per isolate?

**Comment by rakudrama** [comment] 2015-09-19 03:08
I have landed all the changes for the assert trick to work reliably.

If we decide to support some kind of getter, the simplest implementation would be one like __assertionsEnabled()__.

@kmillikin I'm going to leave the issue with you until cps_ir is known to recognize __assertionsEnabled()__.

**Comment by rakudrama** [comment] 2017-02-08 02:03
Closing since the changes are landed for SSA.

**Closed by rakudrama** 2017-02-08 02:03 UTC
Labels: area-dart2js, dart2js-cpsir, dart2js-optimization, Type: enhancement
