### ISSUE TITLE
analysis options feature to exclude specific files with specific lint rules

### ISSUE THREAD

**Issue by ivanesi** [dart-lang/sdk#51054] opened 2023-01-18 15:22 UTC
Recently I joined project with low quality codebase and I want to set analyzer to strong-mode and set a bunch of strict linter rules. But when I did that, I get more than 3K errors.

I can't rewrite all codebase at once.

Is there is a way to set new strict analyzer options only for new code and code that was edited?

Maybe something like second `analyzer_options_strict.yaml` file with `applyOnlyTo/exclude: [filenames]` option.

How to migrate all codebase to strict mode gradually in the right way?

**Comment by a-siva** [comment] 2023-01-18 18:37
//cc @srawlins

**Comment by ivanesi** [comment] 2023-01-19 05:01
> Questions like this are best asked on a user forum like StackOverflow, with many more eyes looking, and with people who may have experience doing this work.

You can consider this question as a feature request because it seems that there is no convenient way to do it. Your answer is not the solution because enabling one rule can lead to hundreds of errors, or even thousands in my case, if I talk about  analyzer's strong mode.

**Comment by srawlins** [comment] 2023-01-19 06:12
What feature are you requesting?

**Comment by ivanesi** [comment] 2023-01-19 06:58
The feature that will allow to migrate codebase to new analyzer rules gradually in a convenient way.

**Comment by srawlins** [comment] 2023-01-19 07:40
Apologies @ivanesi, without a clear description of what feature you have in mind, we can't really help. Asking on a user forum might yield some answers from other users about how they have complied with more static analysis rules in an incremental fashion.

**Comment by ivanesi** [comment] 2023-01-19 08:00
Ok. Let it be this:

The second `analyzer_options.yaml` file with strict rules and  `applyOnlyTo: [filenames]` option as I mentioned in the first message.

Or possibility to create several `analyzer:` and `linter:` options in one file with `exclude`, `applyTo` options for each.

The question on StackOverflow is [here](https://stackoverflow.com/questions/75160452/how-to-migrate-codebase-to-strict-mode-gradually)

**Comment by srawlins** [comment] 2023-01-19 08:08
I like those ideas. Similar to https://github.com/dart-lang/linter/issues/320. We can keep this open for future development.

**Comment by srawlins** [comment] 2023-11-20 15:51
Duplicate of https://github.com/dart-lang/sdk/issues/34069

**Closed by srawlins** 2023-11-20 15:51 UTC
Labels: area-analyzer, P3, type-enhancement, analyzer-analysis-options
