### ISSUE TITLE
Random Error in flutter

### ISSUE THREAD

**Issue by hexolabs** [dart-lang/sdk#35287] opened 2018-11-29 13:38 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-dev.9.4`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.1 unknown, screens 1280x800, 1920x1080  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/ls/f2f38v7x1k1f__bj0mwc6wgc0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: /Users/venkat/flutterProjects/atrak/lib/repository/data/key_value_storage.dart context: exception_20181129_145130_445
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      _ClassVerifier._checkForMismatchedAccessorTypes (package:analyzer/src/error/inheritance_override.dart:357:45)
#2      _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:173:5)
#3      InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:44:11)
#4      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:332:33)
#5      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#6      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-12-03 18:58
Duplicate of #35223

**Closed by stereotype441** 2018-12-03 18:58 UTC
Labels: area-analyzer
