### ISSUE TITLE
co19/LayoutTests/fast/css/fontfaceset-download-error_t01 flakily times out

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28722] opened 2017-02-10 01:45 UTC
I've seen this multiple times on `dart2js-mac10.11-chrome-be`. See [this log](https://build.chromium.org/p/client.dart/builders/dart2js-mac10.11-chrome-be/builds/2771/steps/dart2js%20chrome%20co19%20fast-startup%20tests/logs/stdio).

```
FAILED: dart2js-chrome release_x64 co19/LayoutTests/fast/css/fontfaceset-download-error_t01
Expected: RuntimeError 
Actual: Timeout
CommandOutput[dart2js]:

stdout:
Dart file (/b/build/slave/10.11-c-be/build/sdk/tests/co19/src/LayoutTests/fast/css/fontfaceset-download-error_t01.dart) compiled to JavaScript: xcodebuild/ReleaseX64/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_css_fontfaceset-download-error_t01/test.js

CommandOutput[chrome]:

stdout:
message:
  [{"type":"debug","value":"test_controller.js started","timestamp":0},{"type":"debug","value":"Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)","timestamp":0.001},{"type":"print","value":"dart-calling-main","timestamp":0.034},{"type":"print","value":"unittest-suite-wait-for-done","timestamp":0.086},{"type":"print","value":"dart-main-done","timestamp":0.089},{"type":"message_received","value":"dart-calling-main","timestamp":0.979},{"type":"message_received","value":"unittest-suite-wait-for-done","timestamp":0.98},{"type":"message_received","value":"dart-main-done","timestamp":0.98},{"type":"debug","value":"Sending events to driver page (isFirstMessage = false, isStatusUpdate = true, isDone = false)","timestamp":10.981},{"type":"debug","value":"Sending events to driver page (isFirstMessage = false, isStatusUpdate = true, isDone = false)","timestamp":21.981},{"type":"debug","value":"Sending events to driver page (isFirstMessage = false, isStatusUpdate = true, isDone = false)","timestamp":32.981},{"type":"debug","value":"Sending events to driver page (isFirstMessage = false, isStatusUpdate = true, isDone = false)","timestamp":43.975},{"type":"debug","value":"Sending events to driver page (isFirstMessage = false, isStatusUpdate = true, isDone = false)","timestamp":54.98},{"type":"dom","value":"<head>\n  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n  <meta name=\"dart.unittest\" content=\"full-stack-traces\">\n  <title> Test /b/build/slave/10.11-c-be/build/sdk/tests/co19/src/LayoutTests/fast/css/fontfaceset-download-error_t01.dart </title>\n  <style>\n     .unittest-table { font-family:monospace; border:1px; }\n     .unittest-pass { background: #6b3;}\n     .unittest-fail { background: #d55;}\n     .unittest-error { background: #a11;}\n  </style>\n<style>\n      /* Test 1: Invalid font data */\n      @font-face {\n          font-family: myfont1;\n          src: url('/root_dart/tests/co19/src/LayoutTests/fast/css/resources/invalidfont.png') format(opentype);\n      }\n\n      /* Test 2: Download error */\n      @font-face {\n          font-family: myfont2;\n          src: url('resources/IntentionallyMissingFile.otf');\n      }\n\n      /* Test 3: Empty data url */\n      @font-face {\n          font-family: myfont3;\n          src: url(data:application/x-truetype-font,) format(truetype);\n      }\n\n      /* Test 4: Download error followed by existing local font */\n      @font-face {\n          font-family: myfont4;\n          src: url('resources/IntentionallyMissingFile.otf'), local('Courier New');\n      }\n\n      /* Test 5: Multiple errors */\n      @font-face {\n          font-family: myfont5;\n          src: url('resources/IntentionallyMissingFile.otf'), url(data:application/x-truetype-font,) format(truetype);\n      }\n      </style></head>\n<body>      <div style=\"font-family: myfont1\">font1</div>\n      <div style=\"font-family: myfont2\">font2</div>\n      <div style=\"font-family: myfont3\">font3</div>\n      <div style=\"font-family: myfont4\">font4</div>\n      <div style=\"font-family: myfont5\">font5</div>\n      </body>","timestamp":54.98}]
  Previous test was http://127.0.0.1:57149/root_build/generated_tests/dart2js-chrome-sdk/tests_co19_src_Language_Libraries_and_Scripts_Imports_same_name_t14/test.html?crossOriginPort=57150



stderr:
This test timed out. The delay until the test actually started was: 0:00:01.000873.

BrowserOutput while running the test (* EXPERIMENTAL *):
BrowserOutput.stdout:
  
BrowserOutput.stderr:
  



To retest, run:  /b/build/slave/10.11-c-be/build/sdk/tools/sdks/mac/dart-sdk/bin/dart /b/build/slave/10.11-c-be/build/sdk/tools/testing/dart/http_server.dart -p 57149 -c 57150 --build-directory=/b/build/slave/10.11-c-be/build/sdk/xcodebuild/ReleaseX64/ --runtime=chrome --packages=/b/build/slave/10.11-c-be/build/sdk/.packages

Command[dart2js]: DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --fast-startup --packages=/b/build/slave/10.11-c-be/build/sdk/.packages --out=/b/build/slave/10.11-c-be/build/sdk/xcodebuild/ReleaseX64/generated_compilations/dart2js-sdk/tests_co19_src_LayoutTests_fast_css_fontfaceset-download-error_t01/test.js /b/build/slave/10.11-c-be/build/sdk/tests/co19/src/LayoutTests/fast/css/fontfaceset-download-error_t01.dart
Took 0:00:03.516779

Command[chrome]: /b/build/slave/10.11-c-be/build/sdk/tools/sdks/mac/dart-sdk/bin/dart tools/testing/dart/launch_browser.dart chrome http://127.0.0.1:57149/root_build/generated_tests/dart2js-chrome-sdk/tests_co19_src_LayoutTests_fast_css_fontfaceset-download-error_t01/test.html?crossOriginPort=57150
Took 0:01:01.003689

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rchrome --fast-startup -t60 --use-sdk --dart2js-batch --reset-browser-configuration co19/LayoutTests/fast/css/fontfaceset-download-error_t01
```

**Comment by nex3** [comment] 2017-02-10 01:51
It looks like this normally doesn't take much time but occasionally takes a long time, so I'm marking it as flaky rather than just slow.

**Comment by mraleph** [comment] 2017-11-16 12:02
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Closed** 2018-06-22 00:11 UTC
Labels: area-dart2js, gardening
