### ISSUE TITLE
How to strip build-id and embeded path from the artifact?

### ISSUE THREAD

**Issue by linsui** [dart-lang/sdk#52506] opened 2023-05-24 14:08 UTC
Thank you for taking the time to file an issue!

This tracker is for issues related to:

* dev_compiler

The .so files produced by flutter (libapp.so) embed some paths of the build environment and the build-id. Some other languages provide options to remove them so that we can make the artifacts reproducible. If there any methed to strip the path and the build-id? How can I pass an argument to the linker so that it doesn't add the build-id (e.g. `-Wl,--build-id=none`)?

Thanks!

**Comment by mkustermann** [comment] 2023-05-25 07:52
We intentionally want to embed a `build-id` in order to allow stripping symbolic information from the `libapp.so`. The `build-id` is then used to identify which separate symbol file to use for symbolization of stack traces. Though the calculation of `build-id` is based on hashing of certain other parts of the ELF file - so if other parts haven't changed, the `build-id` shouldn't change.

> Some other languages provide options to remove them so that we can make the artifacts reproducible. 

@linsui could you elaborate what makes your builds non-reproducible?

/cc @sstrickl @mraleph

**Comment by linsui** [comment] 2023-05-25 08:01
(Background: [F-Droid](https://f-droid.org/) builds apks on a buildserver and compares them with the apks published by upstream devs.) We need to make the apk built on different machines/environments reproducible. When the Android NDK is installed in different path, the build-id is different. The path of the source code is also embeded leading to different apks.

**Comment by mkustermann** [comment] 2023-05-25 09:28
AFAIK by default the paths that are used to identify dart code should use import uris (e.g. `package:flutter/.../foo.dart`). Only if one is opting into resolving those paths to absolute paths via `--extra-gen-snapshot-options=resolve-dwarf-paths` would one get the paths on disc.

@linsui Could you provide us with the paths that you see in the `libapp.so` file?

**Comment by linsui** [comment] 2023-05-25 09:44
[This](https://gitlab.com/fdroid/fdroiddata/uploads/21a482ec1fc1d76362d95a67e5cee33a/diffoscope.html) is the diffoscope output of one of the apps. You can see something like

`file:///builds/bleonard252/fdroiddata/build/xyz.u1024256.bodacious.fdroid/.dart_tool/flutter_build/dart_plugin_registrant.dart` and `file:///src/bleonard252/bodacious/.dart_tool/flutter_build/dart_plugin_registrant.dart` in the diff.

**Comment by mkustermann** [comment] 2023-05-25 12:17
Thanks, that's very helpful!

That's a very special file. It's neither included in the Dart app nor any dependent packages. Rather it's an artificially created file by the `flutter` tools. It contains logic to run plugin registration logic.

A `flutter build` will eventually compile the Dart application where it will add `<dir>/.dart_tool/flutter_build/dart_plugin_registrant.dart` as an extra source file ([see here](https://github.com/flutter/flutter/blob/20e164e60cb2b3bd96be84e1dcb1a9a9cf877ea3/packages/flutter_tools/lib/src/compile.dart#L327)). Additionally it will also inject that uri as a constant into Dart source code via a `-Dflutter.dart_plugin_registrant=<uri>` - see [here](https://github.com/flutter/flutter/blob/20e164e60cb2b3b/packages/flutter/lib/src/dart_plugin_registrant.dart#LL10C68-L10C98).

=> So we'll have that string twice in the app - once as the name of the Dart VM `Library` object representing the Dart file and once the Dart constant.

Once the app runs it will access that `package:flutter/src/dart_plugin_registrant.dart:dartPluginRegistrantLibrary` constant and use it to look up the library object and then invoke the plugin registration logic - see [engine code](https://github.com/flutter/engine/blob/a74d9d1f4776ccaf371c/runtime/dart_plugin_registrant.cc#L42).

There's several ways one could fix this:
* to use a relative path (e.g. `.dart_tool/flutter_build/dart_plugin_registrant.dart`) instead of an absolute one
* use custom scheme to refer to generated dart code

/cc @zanderso  is that something the flutter tools team could look into?

**Comment by linsui** [comment] 2023-05-25 13:06
Thanks!

[This](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12398#note_1239595427) is an example of the build id problem. We finally solved it by using the same NDK path.

**Comment by christopherfujino** [comment] 2023-05-25 19:13
> cc @christopherfujino and @chingjun may have the most recent context on the `dart_plugin_registrant.dart` import path.

I don't have recent context, making hte import path relative SGTM

**Comment by linsui** [comment] 2023-05-26 05:51
> Although, would that even solve your problem @linsui, if I'm reading your diff correctly, it seems like there are still a lot of other differences.

I'm not sure. When we used the same path to build the apk, other differences are also fixed.

**Comment by mraleph** [comment] 2023-10-25 21:15
@linsui shaders are not a thing Dart knows about, it's Flutter tooling related stuff, so yeah please do file another issue

**Comment by a-siva** [comment] 2023-12-07 17:23
This seems like a Flutter issue and so closing this here,

**Closed by a-siva** 2023-12-07 17:23 UTC
Labels: area-vm

**Comment by linsui** [comment] 2023-12-23 05:10
I opened an issue in flutter issue tracker for the embeded path. I thought the build-id problem is still a dart issue?

**Comment by a-siva** [comment] 2024-04-17 22:25
> I opened an issue in flutter issue tracker for the embeded path. [flutter/flutter#140558](https://github.com/flutter/flutter/issues/140558) I thought the build-id problem is still a dart issue?

build ids are different because of the differing paths which the flutter issue is tracking.

**Comment by linsui** [comment] 2024-04-18 03:43
> build ids are different because of the differing paths which the flutter issue is tracking.

In https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14837 the libflutter.so files have different ndk build-id. This shouldn't be related to the embeded path which is in libapp.so. Any idea why the ndk build-id is different?
