### ISSUE TITLE
'Uncaught' exception in js_helper / Different behavior between VM an dart2js version

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#25715] opened 2016-02-08 08:08 UTC
There must be a problem with static methods of members. I filed a similar issue under #25714

This version works:
```dart
abstract class SignalService {

    static String removeSignalPrefix(final String name) {
        String cleanName = name.replaceAll(SignalService.BROADCAST_SIGNAL, "")
            .replaceAll(SignalService.POLYMER_SIGNAL, "")
            .replaceAll(SignalService.CHILD_SIGNAL, "");

        return cleanName.replaceFirst(new RegExp("^-*"),"");
    }
    ...
}
```

The following class 
```dart
abstract class SignalService {

    static final RegExp _dash = new RegExp("^-*");

    static String removeSignalPrefix(final String name) {
        String cleanName = name.replaceAll(SignalService.BROADCAST_SIGNAL, "")
            .replaceAll(SignalService.POLYMER_SIGNAL, "")
            .replaceAll(SignalService.CHILD_SIGNAL, "");

        return cleanName.replaceFirst(_dash,"");
    }
   ...
}
```
produces:
```
dart.wrapException	@	js_helper.dart:1699
dart._rootHandleUncaughtError_closure.call$0	@	async_patch.dart:522
dart._microtaskLoop	@	schedule_microtask.dart:41
dart._startMicrotaskLoop	@	schedule_microtask.dart:50
dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1	@	async_patch.dart:54
dart.invokeClosure_closure0.call$0	@	js_helper.dart:2375
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart._callInIsolate	@	isolate_helper.dart:54
dart.invokeClosure	@	js_helper.dart:2375
(anonymous function)	@	js_helper.dart:2395
Mutation (async)		
dart._AsyncRun__initializeScheduleImmediate_closure.call$1	@	async_patch.dart:69
dart._scheduleAsyncCallback	@	async_patch.dart:31
dart._rootScheduleMicrotask	@	zone.dart:961
dart._RootZone.scheduleMicrotask$1	@	zone.dart:1167
dart._Future._addListener$1	@	future_impl.dart:292
dart._Future._thenNoZoneRegistration$2	@	future_impl.dart:206
dart._awaitOnObject	@	async_patch.dart:192
dart._asyncHelper	@	async_patch.dart:160
dart.main	@	date_format.dart:228
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart.startRootIsolate	@	isolate_helper.dart:120
(anonymous function)	@	interfaces.dart:93
(anonymous function)	@	interfaces.dart:93
init.currentScript	@	interfaces.dart:93
(anonymous function)	@	interfaces.dart:93
(anonymous function)	@	interfaces.dart:93
```

**Comment by MikeMitterer** [comment] 2016-02-08 08:18
Here is another one:

This version works:

```
typedef void DataSigner(final RequestBuilderImpl requestbuilder);

void _dummyDataSigner(final RequestBuilderImpl requestbuilder) {

}
```

This one fails:
```dart
typedef void DataSigner(final RequestBuilderImpl requestbuilder);

final DataSigner _dummyDataSigner = (final RequestBuilderImpl requestbuilder) {
};

abstract class RequestSigner {
    final DataSigner _datasigner;

    ...
    RequestSigner() : _datasigner = _dummyDataSigner;
    RequestSigner.withDataSigner(this._datasigner);
    ...
}
```

```
dart.wrapException	@	js_helper.dart:1699
dart._rootHandleUncaughtError_closure.call$0	@	async_patch.dart:522
dart._microtaskLoop	@	schedule_microtask.dart:41
dart._startMicrotaskLoop	@	schedule_microtask.dart:50
dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1	@	async_patch.dart:54
dart.invokeClosure_closure0.call$0	@	js_helper.dart:2375
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart._callInIsolate	@	isolate_helper.dart:54
dart.invokeClosure	@	js_helper.dart:2375
(anonymous function)	@	js_helper.dart:2395
Mutation (async)		
dart._AsyncRun__initializeScheduleImmediate_closure.call$1	@	async_patch.dart:69
dart._scheduleAsyncCallback	@	async_patch.dart:31
dart._rootScheduleMicrotask	@	zone.dart:961
dart._RootZone.scheduleMicrotask$1	@	zone.dart:1167
dart._Future._addListener$1	@	future_impl.dart:292
dart._Future._thenNoZoneRegistration$2	@	future_impl.dart:206
dart._awaitOnObject	@	async_patch.dart:192
dart._asyncHelper	@	async_patch.dart:160
dart.main	@	date_format.dart:228
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart.startRootIsolate	@	isolate_helper.dart:120
(anonymous function)	@	RequestSigner.dart:20
(anonymous function)	@	RequestSigner.dart:20
init.currentScript	@	RequestSigner.dart:20
(anonymous function)	@	RequestSigner.dart:20
(anonymous function)	@	RequestSigner.dart:20
```

**Comment by MikeMitterer** [comment] 2016-02-08 08:31
The worst one:

trace.dart line 55 + 56
```dart
/// A RegExp to match this package's stack traces.
final _friendlyTrace = new RegExp(r"^[^\s]+( \d+(:\d+)?)?[ \t]+[^\s]+$",
    multiLine: true);
```

```
dart.wrapException	@	js_helper.dart:1699
dart._rootHandleUncaughtError_closure.call$0	@	async_patch.dart:522
dart._microtaskLoop	@	schedule_microtask.dart:41
dart._startMicrotaskLoop	@	schedule_microtask.dart:50
dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1	@	async_patch.dart:54
dart.invokeClosure_closure0.call$0	@	js_helper.dart:2375
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart._callInIsolate	@	isolate_helper.dart:54
dart.invokeClosure	@	js_helper.dart:2375
(anonymous function)	@	js_helper.dart:2395
Mutation (async)		
dart._AsyncRun__initializeScheduleImmediate_closure.call$1	@	async_patch.dart:69
dart._scheduleAsyncCallback	@	async_patch.dart:31
dart._rootScheduleMicrotask	@	zone.dart:961
dart._RootZone.scheduleMicrotask$1	@	zone.dart:1167
dart._Future._addListener$1	@	future_impl.dart:292
dart._Future._thenNoZoneRegistration$2	@	future_impl.dart:206
dart._awaitOnObject	@	async_patch.dart:192
dart._asyncHelper	@	async_patch.dart:160
dart.main	@	date_format.dart:228
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart.startRootIsolate	@	isolate_helper.dart:120
(anonymous function)	@	trace.dart:56
(anonymous function)	@	trace.dart:56
init.currentScript	@	trace.dart:56
(anonymous function)	@	trace.dart:56
(anonymous function)	@	trace.dart:56
﻿```

Now???? I'm stuck in code nirvana with no idea how to solve it!

**Comment by MikeMitterer** [comment] 2016-02-08 12:10
I nailed down one of these "Uncaught" problems:

This sample: https://github.com/MikeMitterer/dart-dice-test produces an Uncaugth exception in js_helper. Base exception comes from logging.dart!!!! but only if I **implement** the base class
https://goo.gl/hN8Lxz

If I **extend** from Name it works!!!!

I'm not sure if this is a "dice" problem - have to investigate but however, the stacktrace is completely wrong!!!

```
dart.wrapException	@	js_helper.dart:1699
dart._rootHandleUncaughtError_closure.call$0	@	async_patch.dart:522
dart._microtaskLoop	@	schedule_microtask.dart:41
dart._startMicrotaskLoop	@	schedule_microtask.dart:50
dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1	@	async_patch.dart:54
dart.invokeClosure_closure0.call$0	@	js_helper.dart:2375
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart._callInIsolate	@	isolate_helper.dart:54
dart.invokeClosure	@	js_helper.dart:2375
(anonymous function)	@	js_helper.dart:2395
Mutation (async)		
dart._AsyncRun__initializeScheduleImmediate_closure.call$1	@	async_patch.dart:69
dart._scheduleAsyncCallback	@	async_patch.dart:31
dart._rootScheduleMicrotask	@	zone.dart:961
dart._Future._addListener$1	@	zone.dart:1167
dart._Future._thenNoZoneRegistration$2	@	future_impl.dart:206
dart._awaitOnObject	@	async_patch.dart:192
dart._asyncHelper	@	async_patch.dart:160
dart.main	@	date_format.dart:228
dart._IsolateContext.eval$1	@	isolate_helper.dart:462
dart.startRootIsolate	@	isolate_helper.dart:120
(anonymous function)	@	logging.dart:248
(anonymous function)	@	logging.dart:248
init.currentScript	@	logging.dart:248
(anonymous function)	@	logging.dart:248
(anonymous function)	@	logging.dart:248
```

**Comment by floitschG** [comment] 2016-02-08 16:07
I was able to reproduce.
The actual error message is:
```
Error: Unsupported operation: Cannot find class for: Name
    at dart.wrapException (http://localhost:8080/main.dart.js:2652:17)
    at dart.reflectClassByName (http://localhost:8080/main.dart.js:5373:17)
    at dart.reflectClassByMangledName (http://localhost:8080/main.dart.js:5349:16)
    at dart.reflectType (http://localhost:8080/main.dart.js:13259:16)
    at ExampleModule.dart.Module.register$2 (http://localhost:8080/main.dart.js:13860:68)
    at ExampleModule.dart.Module.register$1 (http://localhost:8080/main.dart.js:13864:21)
    at http://localhost:8080/main.dart.js:14545:39
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:7198:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:7484:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (http://localhost:8080/main.dart.js:7472:34)
```
I'm not sure yet, why the error-message is not printed. Every 'throw' in the code has an error/exception object that has a nice 'toString'.
I will open a new issue for that.

From what I can see, dice has a `MirrorsUsed` annotation that says that it only needs the symbols `inject` and `Named`): @MirrorsUsed(symbols: const ['inject', 'Named'])

This doesn't include `Name`, and trying to run `reflectType` (transitively through `register`) thus fails.

On Dartium, 'MirrorsUsed' is ignored, which explains why it works on Dartium.

Given the 'MirrorsUsed' annotation I would say this is WAI.

**Comment by MikeMitterer** [comment] 2016-02-08 17:16
Cool - thanks for your help! How did you get the above error message??????

**Comment by MikeMitterer** [comment] 2016-02-08 17:29
Getting the error message is cool but there is another problem: Please try to switch between implements and extends as explained above. There is a different behavior between the VM and the dart2js version which is a bit scary!

**Comment by floitschG** [comment] 2016-02-09 14:29
The different behavior is because the VM ignores the `MirrorsUsed` annotation. If you remove it from dice's sources, the behavior is the same.

I got the error message by breaking at every exception (both Chrome and Firefox have an option to do that) and looking at the object that is thrown. (Fwiw you can skip the first throw, where it is hard to inspect. The object is caught and rethrown later).

**Comment by floitschG** [comment] 2016-02-10 20:31
Closing this issue, since the MirrorsUsed annotation won't be supported by the VM.
The bad error-reporting is tracked in #25719.

**Closed by floitschG** 2016-02-10 20:31 UTC
Labels: area-dart2js
