### ISSUE TITLE
pkg/front_end/test/fasta/bootstrap_test.dart seems to not test the entire frontend

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#30454] opened 2017-08-16 12:29 UTC
The `pkg/front_end/test/fasta/bootstrap_test.dart` test is passing at the moment, even though compiling `fasta.dart` with itself seems to fail:

```
sdk $ pkg/front_end/tool/fasta compile -o pkg/front_end/lib/src/fasta/fasta.dart.dill --platform=out/ReleaseX64/patched_sdk/platform.dill pkg/front_end/lib/src/fasta/fasta.dart
pkg/front_end/lib/src/fasta/compiler_context.dart:18:1: Warning: 'LocatedMessage' is imported from both 'package:front_end/src/fasta/fasta_codes.dart' and 'pkg/front_end/lib/src/fasta/fasta_codes.dart'.
import 'fasta_codes.dart' show LocatedMessage, Message;
^
pkg/front_end/lib/src/fasta/compiler_context.dart:18:1: Warning: 'Message' is imported from both 'package:front_end/src/fasta/fasta_codes.dart' and 'pkg/front_end/lib/src/fasta/fasta_codes.dart'.
import 'fasta_codes.dart' show LocatedMessage, Message;
^
pkg/front_end/lib/src/fasta/compiler_context.dart:18:1: Warning: 'LocatedMessage' is imported from both 'package:front_end/src/fasta/fasta_codes.dart' and 'pkg/front_end/lib/src/fasta/fasta_codes.dart'.
import 'fasta_codes.dart' show LocatedMessage, Message;
^
pkg/front_end/lib/src/fasta/compiler_context.dart:18:1: Warning: 'Message' is imported from both 'package:front_end/src/fasta/fasta_codes.dart' and 'pkg/front_end/lib/src/fasta/fasta_codes.dart'.
import 'fasta_codes.dart' show LocatedMessage, Message;
^
pkg/front_end/lib/src/fasta/util/link.dart:40:15: Warning: Declared type variables of 'Link::map' doesn't match those on overridden method 'Iterable::map'.
  Iterable<K> map<K>(K fn(T item)) {
              ^
pkg/front_end/lib/src/fasta/util/link.dart:133:5: Warning: Declared type variables of 'Link::fold' doesn't match those on overridden method 'Iterable::fold'.
  K fold<K>(K initialValue, K combine(K value, T element)) {
    ^
pkg/front_end/lib/src/fasta/util/link.dart:131:15: Warning: Declared type variables of 'Link::expand' doesn't match those on overridden method 'Iterable::expand'.
  Iterable<K> expand<K>(Iterable<K> f(T e)) => _unsupported('expand');
              ^
pkg/front_end/lib/src/fasta/util/link.dart:40:15: Warning: Declared type variables of 'Link::map' doesn't match those on overridden method 'Iterable::map'.
  Iterable<K> map<K>(K fn(T item)) {
              ^
pkg/front_end/lib/src/fasta/util/link.dart:133:5: Warning: Declared type variables of 'Link::fold' doesn't match those on overridden method 'Iterable::fold'.
  K fold<K>(K initialValue, K combine(K value, T element)) {
    ^
pkg/front_end/lib/src/fasta/util/link.dart:131:15: Warning: Declared type variables of 'Link::expand' doesn't match those on overridden method 'Iterable::expand'.
  Iterable<K> expand<K>(Iterable<K> f(T e)) => _unsupported('expand');
              ^
sdk $ echo $?
1
```

@peter-ahe-google Do you think the bootstrap test is incomplete or might it be because I invoke the fasta compiler incorrectly?

**Comment by peter-ahe-google** [comment] 2017-08-16 13:18
Thank you for reporting this. I will close this, but before I do so, I want to file two related issues:

1. We should be better at diagnosing that the input file is from a package and this problem can occur.

2. We currently crash if I leave out the --packages option below.

Try compiling `pkg/front_end/tool/_fasta/compile.dart` instead, that is the file that the bootstrap test compiles.

Alternatively, you can compile the other file via `package:front_end/`, like this:

```
$ ./pkg/front_end/tool/fasta compile -o pkg/front_end/lib/src/fasta/fasta.dart.dill --platform=xcodebuild/ReleaseX64/patched_sdk/platform.dill package:front_end/src/fasta/fasta.dart --packages=.packages 
pkg/front_end/lib/src/fasta/util/link.dart:40:15: Warning: Declared type variables of 'Link::map' doesn't match those on overridden method 'Iterable::map'.
  Iterable<K> map<K>(K fn(T item)) {
              ^
pkg/front_end/lib/src/fasta/util/link.dart:133:5: Warning: Declared type variables of 'Link::fold' doesn't match those on overridden method 'Iterable::fold'.
  K fold<K>(K initialValue, K combine(K value, T element)) {
    ^
pkg/front_end/lib/src/fasta/util/link.dart:131:15: Warning: Declared type variables of 'Link::expand' doesn't match those on overridden method 'Iterable::expand'.
  Iterable<K> expand<K>(Iterable<K> f(T e)) => _unsupported('expand');
              ^
$ 
```

**Comment by mkustermann** [comment] 2017-08-16 17:44
@peter-ahe-google 

The alternative you suggested still doesn't compile (though less warnings due to the package uri):

```
$ pkg/front_end/tool/fasta compile -o pkg/front_end/lib/src/fasta/fasta.dart.dill --platform=out/ReleaseX64/patched_sdk/platform.dill package:front_end/src/fasta/fasta.dart --packages=.packages 
pkg/front_end/lib/src/fasta/util/link.dart:40:15: Warning: Declared type variables of 'Link::map' doesn't match those on overridden method 'Iterable::map'.
  Iterable<K> map<K>(K fn(T item)) {
              ^
pkg/front_end/lib/src/fasta/util/link.dart:133:5: Warning: Declared type variables of 'Link::fold' doesn't match those on overridden method 'Iterable::fold'.
  K fold<K>(K initialValue, K combine(K value, T element)) {
    ^
pkg/front_end/lib/src/fasta/util/link.dart:131:15: Warning: Declared type variables of 'Link::expand' doesn't match those on overridden method 'Iterable::expand'.
  Iterable<K> expand<K>(Iterable<K> f(T e)) => _unsupported('expand');
              ^
$ echo $?
1
$ ls pkg/front_end/lib/src/fasta/fasta.dart.dill
ls: cannot access pkg/front_end/lib/src/fasta/fasta.dart.dill: No such file or directory
```

I am quite confident that this used to work some time ago. Presumably the warnings cause the compilation to be aborted with exitcode 1 (though I would expect these to be errors instead of warnings if they cause a nonzero exitcode).

The question is why are these warnings here?

**Comment by peter-ahe-google** [comment] 2017-08-16 18:12
We've made a lot of changes to the main compiler pipeline, and it is possible that something got lost in translation. We need to investigate further. @sigmundch

**Comment by peter-ahe-google** [comment] 2017-08-16 18:17
@sigmundch I think we have an async issue here, remember the stuff we talked about with keeping a port open. When I turn on verbose, it looks like the compiler just stops after initializer inference, but before the BodyBuilder.

**Comment by peter-ahe-google** [comment] 2017-08-17 13:32
The problem is introduced by [CL 2982093003](https://codereview.chromium.org/2982093003) where `setExitCodeOnProblem` is enabled by default, and not only in patch_sdk.

**Comment by sigmundch** [comment] 2017-08-17 15:35
Thanks for investigating Peter -I thought we wanted to have it on by default on the command-line tools and not just in patch_sdk?

**Comment by sigmundch** [comment] 2017-08-17 16:01
turns out that there is also a different set of warnings if you run with `--platform` and with `--compile-sdk`. Bootstrap_test is doing the latter, so it does't get any warnings, the former seems to be running into issues with erasure: platform.dill no longer has the type-parameters and this is causing the warnings to show up. We believe the discrepancy is coming from that.

After talking with Peter - I agree now that we need to adjust our defaults for `setExitCodeOnProblem` and do some follow up in how we deal with `exitCode` in fasta.dart

**Comment by jensjoha** [comment] 2018-01-08 14:29
This seems to have been fixed. Any objections to closing this issue?

**Closed** 2018-01-18 15:10 UTC
Labels: area-front-end, front-end-fasta
