### ISSUE TITLE
Whole world compilation of large apps take really long

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/sdk#43466] opened 2020-09-17 16:51 UTC
We are hitting internal limits on AOT compilation with several large apps reporting > 15 minute compilation times. This is despite splitting the compilation to two steps. 

See: b/154155290 for internal details.

**Comment by mraleph** [comment] 2020-09-17 18:59
Duplicate of #43299

**Closed by mraleph** 2020-09-17 18:59 UTC
Labels: customer-google3
