### ISSUE TITLE
Dart2js - DataTransferItem.getAsEntry returns javascript object 'FileSystemEntry' instead of dart object 'Entry' in firefox

### ISSUE THREAD

**Issue by synopsisdevs** [dart-lang/sdk#44969] opened 2021-02-11 10:47 UTC
Method  `DataTransferItem.getAsEntry()` of `MouseEvent` fired while dropping folder/file returns javascript object [FileSystemDirectoryEntry](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryEntry) (or `FileSystemFileEntry`) instead of dart object [DirectoryEntry](https://api.dart.dev/stable/2.8.1/dart-html/DirectoryEntry-class.html) (or `FileEntry`) when compiled with dart2js and opened in firefox.

**Enviroment**
- Dart SDK version: **2.8.1 (stable) | 2.10.5. (stable)**
- OS: **Linux** (probably n/a)
- Browser: **Firefox 85.0.1**

**Example code**
dart
```dart
import 'dart:html';

void main() {
  Element el = document.querySelector('.dropdown');
  el
    ..onDragOver.listen((MouseEvent e) {
    e.stopPropagation();
    e.preventDefault();
  })
    ..onDrop.listen((MouseEvent e) async {
      e.stopPropagation();
      e.preventDefault();
      DataTransfer dataTransfer = e.dataTransfer;
      for (int i = 0; i < dataTransfer.items.length; i++)  {
        if (dataTransfer.items[i] is DataTransferItem) {
          Entry entry = dataTransfer.items[i].getAsEntry();
          window.console.log(entry); // logs FileSystemDirectoryEntry or FileSystemFileEntry
        }
      }
    });
}
```
html/css
```html
<style>
  .dropdown {
  width: 500px;
  height: 500px;
  border: 1px solid red;
}
</style>
<div class="dropdown"></div>
```

**Comment by xfoldvar** [comment] 2021-02-16 13:08
I can confirm that this is happening in FF when compiled via dart2js.

Perhaps dart2js is missing some type casting of FF FileSystemEntry objects to Dart Entry.

This can be hotfixed via dartNativeDispatchHooksTransformer like this:

```javascript
<script>
        if (typeof dartNativeDispatchHooksTransformer == "undefined") dartNativeDispatchHooksTransformer=[];
        dartNativeDispatchHooksTransformer.push(
            function(hooks) {
                var getTag = hooks.getTag;
                var quickMap = {
                    "FileSystemDirectoryEntry": "DirectoryEntry",
                    "FileSystemFileEntry": "FileEntry",
                };
                function getTagFixed(o) {
                    var tag = getTag(o);
                    return quickMap[tag] || tag;
                }
                hooks.getTag = getTagFixed;
            });
</script>
```

**Comment by srujzs** [comment] 2021-02-19 21:28
Yup, this is identical, with the issue being that the `DirectoryEntry` class not being renamed to `FileSystemEntry`/`FileSystemDirectoryEntry`. This can be probably be directly handled via changing the API names in dart:html.

**Comment by srujzs** [comment] 2021-02-19 21:29
Duplicate of #45036

**Closed by srujzs** 2021-02-19 21:29 UTC
Labels: area-web, web-libraries

**Comment by weekitmo** [comment] 2021-12-20 14:09
> I can confirm that this is happening in FF when compiled via dart2js.
> 
> Perhaps dart2js is missing some type casting of FF FileSystemEntry objects to Dart Entry.
> 
> This can be hotfixed via dartNativeDispatchHooksTransformer like this:
> 
> ```js
> <script>
>         if (typeof dartNativeDispatchHooksTransformer == "undefined") dartNativeDispatchHooksTransformer=[];
>         dartNativeDispatchHooksTransformer.push(
>             function(hooks) {
>                 var getTag = hooks.getTag;
>                 var quickMap = {
>                     "FileSystemDirectoryEntry": "DirectoryEntry",
>                     "FileSystemFileEntry": "FileEntry",
>                 };
>                 function getTagFixed(o) {
>                     var tag = getTag(o);
>                     return quickMap[tag] || tag;
>                 }
>                 hooks.getTag = getTagFixed;
>             });
> </script>
> ```

This looks like a solution, but i added this code and the same problem still occurs, or is my wrong way?

**Comment by xfoldvar** [comment] 2021-12-20 17:12
> > I can confirm that this is happening in FF when compiled via dart2js.
> > Perhaps dart2js is missing some type casting of FF FileSystemEntry objects to Dart Entry.
> > This can be hotfixed via dartNativeDispatchHooksTransformer like this:
> > ```js
> > <script>
> >         if (typeof dartNativeDispatchHooksTransformer == "undefined") dartNativeDispatchHooksTransformer=[];
> >         dartNativeDispatchHooksTransformer.push(
> >             function(hooks) {
> >                 var getTag = hooks.getTag;
> >                 var quickMap = {
> >                     "FileSystemDirectoryEntry": "DirectoryEntry",
> >                     "FileSystemFileEntry": "FileEntry",
> >                 };
> >                 function getTagFixed(o) {
> >                     var tag = getTag(o);
> >                     return quickMap[tag] || tag;
> >                 }
> >                 hooks.getTag = getTagFixed;
> >             });
> > </script>
> > ```
> 
> This looks like a solution, but i added this code and the same problem still occurs, or is my wrong way?

Thats weird, I just checked and this hotfix script is still working as expected. Script must be executed before the dart application is loaded. Its sad that this issue was not resolved yet though.

**Comment by weekitmo** [comment] 2021-12-21 02:41
> Thats weird, I just checked and this hotfix script is still working as expected. Script must be executed before the dart application is loaded. Its sad that this issue was not resolved yet though.

@xfoldvar if declare `Entry` it will throw error `Expected a value of type 'Entry', but got one of type 'JavaScriptObject'`, use `dynamic ` it will work fine

[Entry_Test.zip](https://github.com/dart-lang/sdk/files/7749152/EntryTest.zip)

**Comment by srujzs** [comment] 2021-12-23 00:14
Bindings have been changed to reflect the change in API names and other browsers. Trying this locally with the fix resolves the issue. Closing for now, feel free to reopen if it's not fixed.
