### ISSUE TITLE
Not sure what this error is.

### ISSUE THREAD

**Issue by spaw03** [dart-lang/sdk#36696] opened 2019-04-22 13:00 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.5429.30.34.5452501`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-183.5429.30.34.5452501, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Found element with null library: WidgetTester
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:442:31)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44:12)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:252:16)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2356:49)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:4209:10)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:2356:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9166:20)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2279:17)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4947:10)
#9      PartialResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:3542:11)
#10     UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:3333:35)
#11     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:4200:11)
#12     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:2275:49)
#13     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5760:32)
#14     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5740:11)
#15     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:4086:13)
#16     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#17     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:4223:23)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2558:49)
#19     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:617:10)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:7)
#21     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:11)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:91:14)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:90:43)
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1438:63)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1236:33)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#42     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#43     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#45     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\mmcenerney\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-09-06 04:50
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/34554; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 04:51
Duplicate of https://github.com/dart-lang/sdk/issues/34554

**Closed by srawlins** 2019-09-06 04:51 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
