### ISSUE TITLE
No name completion after `in`

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#55186] opened 2024-03-13 16:58 UTC
```dart
class InputValue {}

class A {
  final InputValue in^;
}
```
By some reason I get `int` here, but for `inp` I get `inputValue`.
Apparently we parse `in` (a keyword) specially, and this does not work well for completion.

**Comment by scheglov** [comment] 2024-03-13 16:58
Similarly for
```dart
    required this.in,
```

**Comment by DanTup** [comment] 2024-03-14 21:35
Maybe dupe of https://github.com/dart-lang/sdk/issues/48883?

**Comment by scheglov** [comment] 2024-03-15 20:58
https://dart-review.googlesource.com/c/sdk/+/358020

**Comment by scheglov** [comment] 2024-03-17 23:13
https://dart-review.googlesource.com/c/sdk/+/357943

**Closed** 2024-03-18 18:09 UTC
Labels: area-analyzer, analyzer-completion, P3, type-bug, analyzer-completion-correctness
