### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by KOGI** [dart-lang/sdk#38335] opened 2019-09-11 19:44 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.6603.28`
- `2.5.0`
- `IU-192.6603.28, JRE 11.0.3+12-b304.56x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1680x1050, 1680x1050`

## Exception
```
Dart analysis server, SDK version 2.5.0, server version 1.27.2, error: Analysis failed: D:\code\cstep\dart-nats-ffi\lib\src\NATSClient.dart
NoSuchMethodError: The getter 'arguments' was called on null.
Receiver: null
Tried calling: arguments
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ResolverVisitor.resolveArgumentsToParameters (package:analyzer/src/generated/resolver.dart:4989:44)
#2      ElementResolver._resolveArgumentsToParameters (package:analyzer/src/generated/element_resolver.dart:1572:28)
#3      ElementResolver._resolveArgumentsToFunction (package:analyzer/src/generated/element_resolver.dart:1557:12)
#4      ElementResolver.visitSuperConstructorInvocation (package:analyzer/src/generated/element_resolver.dart:942:41)
#5      SuperConstructorInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9473:15)
#6      ResolverVisitor.visitSuperConstructorInvocation (package:analyzer/src/generated/resolver.dart:4421:10)
#7      SuperConstructorInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:9473:15)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#9      ScopedVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:5296:27)
#10     ResolverVisitor.visitConstructorDeclaration (package:analyzer/src/generated/resolver.dart:3651:13)
#11     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2624:15)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#13     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5248:18)
#14     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5226:11)
#15     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3552:13)
#16     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#17     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3594:23)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#19     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:678:10)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#42     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#43     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#45     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#46     new Future.sync (dart:async/future.dart:224:31)
#47     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _runZoned (dart:async/zone.dart:1516:10)
#51     runZoned (dart:async/zone.dart:1463:12)
#52     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context...
```

For additional log information, please append the contents of
file://C:\Users\bob.jackman\AppData\Local\Temp\report.txt.

**Comment by keertip** [comment] 2019-09-11 20:39
Thanks for the report.

**Comment by keertip** [comment] 2019-09-11 20:39
Duplicate of #38041

**Closed** 2019-09-11 20:40 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
