### ISSUE TITLE
fasta crashes when parsing "||=" (invalid operators)

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#31060] opened 2017-10-10 19:17 UTC
The following program makes fasta crash:

```dart
var x = false;
main() {
  x ||= true;
}
```

When running: `./pkg/front_end/tool/fasta compile input.dart` you get:
```
Unhandled exception:
foo/oror.dart:3:5: Internal problem: Unhandled ||= in handleAssignment.
  x ||= true;
    ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      DelayedAssignment.handleAssignment (package:front_end/src/fasta/kernel/body_builder.dart:3599:14)
#3      DelayedAssignment.buildForEffect (package:front_end/src/fasta/kernel/body_builder.dart:3551:12)
#4      BodyBuilder.toEffect (package:front_end/src/fasta/kernel/body_builder.dart:243:44)
#5      BodyBuilder.popForEffect (package:front_end/src/fasta/kernel/body_builder.dart:218:32)
#6      BodyBuilder.endExpressionStatement (package:front_end/src/fasta/kernel/body_builder.dart:691:40)
#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3463:14)
#8      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1845:16)
#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:3427:12)
#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3330:14)
#11     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3322:20)
#12     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3252:15)
#13     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:611:14)
#14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:483:5)
#15     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:230:5)
#16     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2278:14)
#17     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2183:11)
#18     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:333:14)
#19     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:280:15)
#20     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:176:14)
<asynchronous suspension>
#21     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#22     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:281:20)
...
```

**Comment by lrhn** [comment] 2017-10-11 13:11
The `||=` and `&&=` syntaxes are part of Dart 2, they are not allowed in Dart 1.
I wouldn't expect Fasta to support it *yet* (but it shuldn't crash, obviously).

**Comment by peter-ahe-google** [comment] 2017-10-12 15:17
Duplicate of #30340.

**Closed by peter-ahe-google** 2017-10-12 15:17 UTC
Labels: area-front-end, front-end-fasta, front-end-fasta-recovery
