### ISSUE TITLE
Generated by Andriod

### ISSUE THREAD

**Issue by kbeg** [dart-lang/sdk#37987] opened 2019-08-23 21:43 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2, server version 1.27.1, error: Found element with null library: ThemeData
null exception
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:418:31)
#1      AnalysisLogger.logError (package:analysis_server/src/analysis_logger.dart:44:12)
#2      ElementResolver.visitCommentReference (package:analyzer/src/generated/element_resolver.dart:257:16)
#3      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:1965:49)
#4      ResolverVisitor.visitCommentReference (package:analyzer/src/generated/resolver.dart:4227:10)
#5      CommentReferenceImpl.accept (package:analyzer/src/dart/ast/ast.dart:1965:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
#7      CommentImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1904:17)
#8      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4896:10)
#9      UnifyingAstVisitor.visitComment (package:analyzer/dart/ast/visitor.dart:3152:35)
#10     ResolverVisitor.visitComment (package:analyzer/src/generated/resolver.dart:4218:11)
#11     CommentImpl.accept (package:analyzer/src/dart/ast/ast.dart:1900:49)
#12     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5880:32)
#13     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5860:11)
#14     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:4199:13)
#15     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#16     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:4241:23)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#18     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:692:10)
#19     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:159:7)
#20     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#21     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:158:11)
#22     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:112:14)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:111:43)
#25     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1451:63)
#26     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#27     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1228:17)
<asynchronous suspension>
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)
<asynchronous suspension>
#30     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#31     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#32     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#33     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#34     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:550:21)
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:635:12)
#40     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:548:7)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:452:9)
#42     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#43     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:447:43)
#44     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#45     new Future.sync (dart:async/future.dart:224:31)
#46     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _runZoned (dart:async/zone.dart:1516:10)
#50     runZoned (dart:async/zone.dart:1463:12)
#51     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#52     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#53     Driver.start (package:analysis_server/src/server/driver.dart:447:21)
#54     main (file:///C:/b/s...
```

For additional log information, please append the contents of
file://C:\Users\KHALID~1\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-11-27 05:24
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37987; please follow along there.

**Comment by srawlins** [comment] 2019-11-27 05:24
Duplicate of https://github.com/dart-lang/sdk/issues/37987

**Comment by srawlins** [comment] 2021-02-22 16:57
This crash hasn't been reported since Dart 2.5.0. Please re-open if you see this crash again.

**Closed by srawlins** 2021-02-22 16:57 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
