### ISSUE TITLE
Why map function does not throw any exception inside?

### ISSUE THREAD

**Issue by softronaut** [dart-lang/sdk#41549] opened 2020-04-17 10:02 UTC
I encountered this behavior during developing Flutter app: https://github.com/flutter/flutter/issues/54606

Later I noticed Dart is really behaving like this. Example is self-explanatory:
```
const nums = [1, 2, 3];

void main() {
  nums.map((i) => increment(i)); // does not throw anything
  nums.forEach((i) => increment(i)); // throws
}

void increment(int i) {
  throw Exception('test');
}
```

Dart version:
`Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "macos_x64"`

**Comment by eernstg** [comment] 2020-04-17 10:08
This is working as intended, and the reason why you don't get the exception(s) is that from the first line in the body of `main` is that you are not traversing the returned iterable. If you add `.toList()` before the semicolon then you'll force the delayed operations to take place, and they will throw.

I'll close this issue because it does not seem to report any problems, but don't hesitate to create new issues if something comes up!

**Closed by eernstg** 2020-04-17 10:08 UTC

**Comment by softronaut** [comment] 2020-04-17 10:43
@eernstg I'm sorry to bother but I still don't get it because I'm using `toList` method in my real example.

This is the minified real example:

```
final fetchList = dealIds.where((di) => !_browseBox.upToDate(di)).toList();
```
and `upToDate` method:
```
  bool upToDate(DealId dealId) {
    final data = _box.get(dealId.id);
    if (data != null) {
      final update = data['update'];
      assert(update is DateTime);
      assert(update != null, '${dealId.id} date is null');
      ......
  }
```

I never get this `AssertionError` thrown or any other thing...

**Comment by softronaut** [comment] 2020-04-17 10:49
@eernstg In my real example, actually I use `toList` method:
```
final fetchList = dealIds.where((di) => !_browseBox.upToDate(di)).toList();
```
Inside `upToDate` method I do couple of assertions but none of them logged unless I wrap the operation up above with `try/catch`. But as far as I know, it's not mandatory to make errors logged.
