### ISSUE TITLE
Parts do not resolve the imports from the library file

### ISSUE THREAD

**Issue by michaelspiss** [dart-lang/sdk#33123] opened 2018-05-15 02:11 UTC
It seems like #17268 occurs again with version 2.0.0, but this time it can't be fixed by restarting the editor or reanalyzing sources.

> **What steps will reproduce the problem?**
> 1. create a new library and use a part in it
>  2. create a new part file (use part of annotation)
>  3. Use a namespace/class imported in the main file of the library with import
>
> **What is the expected output? What do you see instead?**
> The names / classes should be resolved with the imports from the main library file
> Instead an error is shown that the class could not be found.

Additionally, imported classes in the main library file (e.g. from dart:io) also show up as undefined names in part files.

Tested versions:
* 2.0.0-dev.54.0 (Dart VM)
* 2.0.0-edge (Flutter dart-sdk)

both on windows x64

**Comment by vsmenon** [comment] 2018-05-15 23:37
fyi - @bwilkerson

**Comment by michaelspiss** [comment] 2018-05-30 19:38
I just figured out that this only occurs if the used capitalization differs from the filename's.

So assuming there's a file named `src/SampleOptions.dart`, `part 'src/SampleOptions.dart';` will work fine, whereas `part 'src/Sampleoptions.dart';` or even `part 'src/SampleOptions.Dart';` wont.
A "Target URI doesn't exist" error is never being indicated by the analyzer.

The program runs fine, the analyzer only flags the part's lines. Not quite sure what the intended behaviour is, it might not only be an analyzer issue.

Tested versions:

- 2.0.0-dev.59.0 (Dart VM)
- 2.0.0-edge (Flutter dart-sdk)

both on windows x64

**Comment by zoechi** [comment] 2018-06-08 14:00
According to the Dart style guide only lowercase+underscore file names should be used.
If you get the casing wrong the code won't run on non-Windows machines.

**Comment by michaelspiss** [comment] 2018-06-08 18:43
Thanks for the tip @zoechi, I must have missed that one!
(https://www.dartlang.org/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores)

**Comment by bwilkerson** [comment] 2018-08-29 00:57
It looks like this was working as intended, so I'm going to close it. Please let me know if you're still seeing a problem.

**Closed by bwilkerson** 2018-08-29 00:57 UTC
Labels: area-analyzer
