### ISSUE TITLE
Quick fix not shown for 'prefer_relative_imports'

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/sdk#51319] opened 2023-02-08 16:24 UTC
![image](https://user-images.githubusercontent.com/63228361/217589491-ae3912fb-b7c6-44ce-9c02-1ce1b1c25ce4.png)

Quick fix is not shown for prefer relative imports.

![image](https://user-images.githubusercontent.com/63228361/217589638-043a2448-c10a-4de4-829d-0a6bafcc13e8.png)
![image](https://user-images.githubusercontent.com/63228361/217589755-c304cdf9-ec90-4b9d-9424-6a78c10264af.png)

**Comment by kirill-21** [comment] 2023-02-08 20:28
> Please provide a minimal reproducible case for the `prefer_relative_imports`, with the code as text, so others can quickly be able to reproduce it.
> 
> Also, please provide a case for the duplicate warnings, along with the Dart version used.

It is already provided on screenshot. Import is not relative, analyzer says that it should be converted to a relative one. When you press alt + enter there is no such button for this convertion. First time issue appeared maybe a few weeks ago.

As for dublicate warning:
![image](https://user-images.githubusercontent.com/63228361/217643691-d94b0ce9-18e0-4dde-b9bc-18acc55363e9.png)

**Comment by srawlins** [comment] 2023-02-09 18:44
Thanks for the report. We do believe that there is a quick fix for 'prefer_relative_imports', and have tests for the 'ConvertToRelativeImport' quick fix. So we will need a minimal reproduction in order to investigate. Thanks!

**Comment by srawlins** [comment] 2023-02-09 18:44
> Also warnings are shown twice

Please file separate bugs for separate issues.

**Comment by kirill-21** [comment] 2023-02-09 21:37
> Thanks for the report. We do believe that there is a quick fix for 'prefer_relative_imports', and have tests for the 'ConvertToRelativeImport' quick fix. So we will need a minimal reproduction in order to investigate. Thanks!

I am using lint: ^2.0.1 package with with prefer_relative_imports rule. Analyzer stopped suggesting quick fixed for this rule ~2-3 weeks ago

**Comment by kirill-21** [comment] 2023-02-12 21:11
![studio64_yHhR43Q8BP](https://user-images.githubusercontent.com/63228361/218337332-41d841a1-d016-4061-b57e-4ee7246128a0.gif)

**Comment by asashour** [comment] 2023-02-12 22:14
Thanks for the reply.

I have to say, it is not reproducible by me with `stable` (Dart `2.19.2`)  and `dev` channels (Dart `3.0.0-218.0.dev`).

Steps:

- Create a new project
- Add `prefer_relative_imports` to the `linter`/`rules` to `analysis_options.yaml`
- Have a file named `c.dart` in `/lib/a/b`, which reference a class with `import 'package:someflutter/logic/windows/windows.dart';` 

The screenshot shows the error you have, but it doesn't let others reproduce the issue, to be fixed. And it would be really hard to fix a non-reproducible issue. As the root cause may be something related to the dependencies, or the code, or something else.

To move forward, please:
1. Try the latest `stable` and/or `dev`/`master` channels.
2. Specify your Dart and Flutter versions.
3. If this is still reproducible with latest versions, then try to provide a minimal case, possibly an open source sample project, which others can clone it to see the same error, so that everyone on the same page.

**Comment by kirill-21** [comment] 2023-02-13 04:05
> Thanks for the reply.
> 
> I have to say, it is not reproducible by me with `stable` (Dart `2.19.2`) and `dev` channels (Dart `3.0.0-218.0.dev`).
> 
> Steps:
> 
> * Create a new project
> * Add `prefer_relative_imports` to the `linter`/`rules` to `analysis_options.yaml`
> * Have a file named `c.dart` in `/lib/a/b`, which reference a class with `import 'package:someflutter/logic/windows/windows.dart';`
> 
> The screenshot shows the error you have, but it doesn't let others reproduce the issue, to be fixed. And it would be really hard to fix a non-reproducible issue. As the root cause may be something related to the dependencies, or the code, or something else.
> 
> To move forward, please:
> 
> 1. Try the latest `stable` and/or `dev`/`master` channels.
> 2. Specify your Dart and Flutter versions.
> 3. If this is still reproducible with latest versions, then try to provide a minimal case, possibly an open source sample project, which others can clone it to see the same error, so that everyone on the same page.

Do you have the same ide version & plugin versions as mentioned here: 
https://github.com/dart-lang/sdk/issues/51319#issue-1576428181 ?

**Comment by asashour** [comment] 2023-02-13 07:09
Please see the output of `flutter doctor -v`.

The IDE and plugin versions are not relevant, even with Dart plugin `223.8617.8`, the analysis server which is part of the Dart SDK is the component where the fixes are done.

Regarding the `dev_dependencies` mentioned in https://github.com/dart-lang/sdk/issues/51319#issuecomment-1427133898, they don't affect the local result.

<details>

<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel master, 3.8.0-10.0.pre.1, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)  
    • Flutter version 3.8.0-10.0.pre.1 on channel master at c:\use\flutter
    ! Upstream repository https://github.com/asashour/flutter is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/asashour/flutter to dismiss this error.
    • Framework revision 001c4951b6 (3 days ago), 2023-02-09 20:14:10 -0500
    • Engine revision e1d0032029
    • Dart version 3.0.0 (build 3.0.0-218.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform
      update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK vers
ion 33.0.0)
    • Android SDK at C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Users\ahmed_ashour\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.6008.17

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Users\ahmed_ashour\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\223.8617.56
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\ahmed_ashour\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.78
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by kirill-21** [comment] 2023-02-13 08:46
> Please see the output of `flutter doctor -v`.
> 
> The IDE and plugin versions are not relevant, even with Dart plugin `223.8617.8`, the analysis server which is part of the Dart SDK is the component where the fixes are done.
> 
> Regarding the `dev_dependencies` mentioned in [#51319 (comment)](https://github.com/dart-lang/sdk/issues/51319#issuecomment-1427133898), they don't affect the local result.
> 
> flutter doctor -v

I guess it's some kind of an Android Studio issue, i've tried to install beta version, then rolledback to the stable one and issue appeared. I deleted the studio and installed it again and issue disappeared

**Comment by bwilkerson** [comment] 2023-02-13 19:48
If you're no longer seeing the problem, then I'm going to agree with your conclusion that it was an AS configuration issue and close this.

@stevemessick In case this is of interest.

**Closed by bwilkerson** 2023-02-13 19:48 UTC
Labels: area-analyzer
