### ISSUE TITLE
Error message could be improved when referencing a closure

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#30473] opened 2017-08-17 19:10 UTC
I see the following error message (correctly) in my code:

```
The return type 'List' isn't a 'FutureOr<List<Script>>', as defined by the method ''.
```

Note the name of the method above is `''`. This is for a return value from a closure. The error message could probably just omit the `as defined by the method ''.`.

@bwilkerson @lukechurch

**Comment by devoncarew** [comment] 2017-08-17 19:10
> The error message could probably just omit the as defined by the method ''..

Perhaps generally, or perhaps just for the closure case?

**Comment by bwilkerson** [comment] 2017-08-17 19:30
There are three potential cases here: a method, a function, and a closure. They might potentially all want different messages.

The reason for including that information in the message was to provide more context for users. Given local functions and nested closures, it isn't necessarily obvious which function (in the generic sense) a given return statement is returning from.

Ironically, I think this might be more important for closures than for methods because the return type of a closure is more likely to be inferred, making it even harder for users to understand what's wrong with their code and/or how to fix it.

(For my own future reference, this is a `StaticTypeWarningCode`.)

**Comment by srawlins** [comment] 2017-12-18 06:27
Sort of a duplicate of #26056, until @bwilkerson brought up the function case 😁 .

**Comment by srawlins** [comment] 2017-12-18 22:16
Closing with b50319c (I suppose open a new option with the function case, if we wish, but b50319c fixes the original issue)

**Closed by srawlins** 2017-12-18 22:16 UTC
Labels: analyzer-ux, area-analyzer, P2 medium, Type: enhancement
