### ISSUE TITLE
Wrong translation of `sync*` functions?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#42347] opened 2020-06-15 14:38 UTC
The following issue seems to indicate an incorrect translation of a `sync*` method. Unfortunately, I don't have a minimal example at this point, but the issue can be reproduced reliably as follows (some output omitted):

```
> git clone 'https://github.com/dart-lang/reflectable.git'
> cd reflectable
> git co 64eee3241062b5eb9babf1cb372a9bdc6ca2a4d7
> pub get
> pub run build_runner build test
[SEVERE] reflectable:reflectable on example/example.dart:

type '() => (_SyncIterator<PropertyAccessorElement>) => bool' is not a subtype of type '() => (_SyncIterator<ExecutableElement>) => bool'
```

The error occurs with `dart` version 2.9.0-15.0.dev, but not with 2.8.0-dev.2.0.

The dynamic type error arises during the execution of `moveNext()` on an `Iterable` returned by a `sync*` getter [here](https://github.com/dart-lang/reflectable/blob/64eee3241062b5eb9babf1cb372a9bdc6ca2a4d7/lib/src/builder_implementation.dart#L815). This can be verified by adding the following immediately before the line that throws):

```dart
      var iter = libraryDomain._declarations.iterator;
      iter.moveNext();
      throw "Not reached";
```

This gives rise to the same dynamic error, and if `iter.moveNext();` is commented out then the `"Not reached"` exception occurs. Hence, it is `iter.moveNext()` that throws.

This should not occur with an iterator which is obtained as the return value from a `sync*` function.

The dynamic error does _not_ occur if [line 5047](https://github.com/dart-lang/reflectable/blob/64eee3241062b5eb9babf1cb372a9bdc6ca2a4d7/lib/src/builder_implementation.dart#L5047) is changed from `accessorsOfLibrary,` to the following:

```dart
      accessorsOfLibrary.toList(),
```

which has the effect that a the sync iterator returned by the `sync*` function `extractLibraryAccessors` [here](https://github.com/dart-lang/reflectable/blob/64eee3241062b5eb9babf1cb372a9bdc6ca2a4d7/lib/src/builder_implementation.dart#L4954) is replaced by a `List`, which is then used in a `yield*` of another `sync*` function [here](https://github.com/dart-lang/reflectable/blob/64eee3241062b5eb9babf1cb372a9bdc6ca2a4d7/lib/src/builder_implementation.dart#L2660).

Unfortunately, the failure does not occur with a small snippet of code that has a similar structure, but this does seem to imply that code generation for a "`sync*` that yields a `sync*`" went wrong somewhere between 2.8.0-dev.2.0 and 2.9.0-15.0.dev.

Cf. https://github.com/dart-lang/reflectable/issues/210#issue-636796260, the issue seems to have arisen between Flutter SDK versions 1.19.0-1.0.pre and 1.19.0-2.0.pre.

Trying area-front-end, which seems at least likely. @johnniwinther, does this dynamic error in `moveNext()` from a `sync*` ring a bell?

**Comment by mraleph** [comment] 2020-06-15 21:01
Duplicate of #42234

**Closed by mraleph** 2020-06-15 21:01 UTC
Labels: area-front-end
