### ISSUE TITLE
Build time increased since Dart 2.14.x

### ISSUE THREAD

**Issue by agacemi** [dart-lang/sdk#47546] opened 2021-10-25 14:33 UTC
We suspect a regression in loading scripts step in dart tools since Dart 2.14.x. We can't reproduce the issue with a sample perhaps this issue appear with a large project, like ours, with larges files (our project has 1688 dart files).

# Context

We use dart via flutter. Since upgrading flutter from  flutter 2.2.3 that use **Dart 2.13.4** to flutter 2.5.1 that use  **Dart 2.14.2**, the build time increased by 3 to 5 times:
 - Whatever OS: Linux, Mac, we don't tested Windows
 - In locale machine and in CI
 - With the SAME code base. 

 The issue is also present in 2.14.2,  2.14.3, 2.14.4 and even 2.15.0 (build 2.15.0-82.2.beta (I experiment the beta channel)

# Some measurements

By enabling verbose log, we obtained the fellowing mesures in my local machine during dart compilation:

## With 2.13.4
With 2.13.4, the build duration is around 3.76 minutes. 

[ +100 ms] [  +74 ms] /Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies
 -Ddart.vm.profile=false -Ddart.vm.product=true
--aot --tfa --packages /Users/abdelaziz_gacemi/Devhome/GitProjects/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/.dart_tool/package_config.json --output-dill
/Users/abdelaziz_gacemi/Devhome/GitProjects/ixxxxxxxxxxxxxxxxxxxxxxxxxxxxx/.dart_tool/flutter_build/bab628d30fedb7c56ca7028e195a0365/app.dill --depfile
/Users/abdelaziz_gacemi/Devhome/GitProjects/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/.dart_tool/flutter_build/bab628d30fedb7c56ca7028e195a0365/kernel_snapshot.d package:xxxxxxxxx/main.dart
**[+224803 ms]** [+224779 ms] kernel_snapshot: Complete

## With 2.14.2
With 2.14.2, the build duration is around 13.47 minutes. 

[+25 ms] /Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies
 -Ddart.vm.profile=false -Ddart.vm.product=true
--aot --tfa --packages /Users/abdelaziz_gacemi/Devhome/GitProjects//xxxxxxxxxxxxxxxxxxxxxxxxxxxxx//.dart_tool/package_config.json --output-dill
/Users/abdelaziz_gacemi/Devhome/GitProjects//xxxxxxxxxxxxxxxxxxxxxxxxxxxxx//.dart_tool/flutter_build/37514545f4a531678c9cc2bc3d433ead/app.dill --depfile
/Users/abdelaziz_gacemi/Devhome/GitProjects/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx//.dart_tool/flutter_build/37514545f4a531678c9cc2bc3d433ead/kernel_snapshot.d package:xxxxxxxxx/main.dart
**[+808399 ms]** [+809032 ms] kernel_snapshot: Complete 

## In CI

Build time takes 17 minutes when using dart 2.13.x. It takes 48 minutes when using 2.14.X

# Additionnel observations 

## Some screenshots with dart --observe

We add --observe option to the above dart command lines, we noticed a big difference in the cpu profile view. More particularly, LoadScripts and FindLibrary that takes a long times in Dart 2.14.x compared to CPU profile in 2.13.X. 

## CPU profil in dart 2.13.x 
<img width="894" alt="Capture d’écran 2021-10-20 à 23 48 01" src="https://user-images.githubusercontent.com/5896654/138711190-0ab3cb5f-e820-4a96-a36f-563f66476801.png">

## CPU profil in dart 2.14.x 
<img width="897" alt="Capture d’écran 2021-10-21 à 17 27 09" src="https://user-images.githubusercontent.com/5896654/138710772-5dc9194d-ac73-4746-9626-c4f1d41ae1d6.png">

**Comment by agacemi** [comment] 2021-10-29 20:13
@alexmarkov  Please find the result of git bisect [bisect-log-1.txt](https://github.com/dart-lang/sdk/files/7444656/bisect-log-1.txt). It seem related to the dart version  (build 2.14.0-341.0.dev).  The compilation for this version tooks 17 minutes instead of 3 minutes and 45 secondes.

`
**flutter --version**: 

Flutter 2.4.0-5.0.pre.136 • channel unknown • unknown source
Framework • revision c2c920ae78 (3 months ago) • 2021-07-21 20:36:04 -0400
Engine • revision 9970b94793
Tools • Dart 2.14.0 (build 2.14.0-341.0.dev)
[+949919 ms] [+949828 ms] kernel_snapshot: Complete


c2c920ae78d91ea4d4c5c6c2410f94db7f54af84 is the first bad commit
commit c2c920ae78d91ea4d4c5c6c2410f94db7f54af84
Author: engine-flutter-autoroll <engine-flutter-autoroll@skia.org>
Date:   Wed Jul 21 20:36:04 2021 -0400

    Roll Engine from 0c943571acc5 to 9970b947935d (4 revisions) (#86825)

 bin/internal/engine.version | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

`

**Comment by alexmarkov** [comment] 2021-10-29 20:40
@agacemi Could you please double check that there's no regression at flutter becd5ec8b188c76b9bfd6e492952fe5d00f92f8c and there is a regression at c2c920ae78d91ea4d4c5c6c2410f94db7f54af84.

That's different from what I see on the sample @jyardin provided.

**Comment by agacemi** [comment] 2021-10-29 21:10
@alexmarkov I just checked for c2c920ae78d91ea4d4c5c6c2410f94db7f54af84. I Obtained:
```
[+258898 ms] [+258902 ms] kernel_snapshot: Complete
```

For c2c920ae78d91ea4d4c5c6c2410f94db7f54af84, I checked many times and bellow the measurements I do before. 

```

######################## BAD >>> 200000 ms ################

Building flutter tool...
Flutter 2.5.0-5.1.pre • channel unknown • unknown source
Framework • revision 65cf7de5f4 (3 months ago) • 2021-08-11 15:48:01 -0700
Engine • revision fbeb7e22bd
Tools • Dart 2.14.0 (build 2.14.0-377.4.beta)

[+1128274 ms] [+1128066 ms] kernel_snapshot: Complete


Flutter 2.4.0-5.0.pre.180 • channel unknown • unknown source
Framework • revision 41497f9587 (3 months ago) • 2021-07-24 03:13:03 -0400
Engine • revision 4a1bc7329e
Tools • Dart 2.14.0 (build 2.14.0-349.0.dev)

[+1076479 ms] [+1076330 ms] kernel_snapshot: Complete


Flutter 2.4.0-5.0.pre.157 • channel unknown • unknown source
Framework • revision 9492e13c45 (3 months ago) • 2021-07-22 22:41:03 +0200
Engine • revision a6c4cdd0ff
Tools • Dart 2.14.0 (build 2.14.0-342.0.dev)

[+1080488 ms] [+1080374 ms] kernel_snapshot: Complete


Flutter 2.4.0-5.0.pre.146 • channel unknown • unknown source
Framework • revision c2f09e0638 (3 months ago) • 2021-07-22 04:06:03 -0400
Engine • revision 0507a37934
Tools • Dart 2.14.0 (build 2.14.0-341.0.dev)
[+1001170 ms] [+1001051 ms] kernel_snapshot: Complete


Flutter 2.4.0-5.0.pre.140 • channel unknown • unknown source
Framework • revision 0073b8cb02 (3 months ago) • 2021-07-21 21:41:03 -0400
Engine • revision 5475b49606
Tools • Dart 2.14.0 (build 2.14.0-341.0.dev)

[+929325 ms] [+929252 ms] kernel_snapshot: Complete


Flutter 2.4.0-5.0.pre.137 • channel unknown • unknown source
Framework • revision ae851a730d (3 months ago) • 2021-07-21 17:41:03 -0700
Engine • revision 9970b94793
Tools • Dart 2.14.0 (build 2.14.0-341.0.dev)
[+934608 ms] [+934583 ms] kernel_snapshot: Complete


Flutter 2.4.0-5.0.pre.136 • channel unknown • unknown source
Framework • revision c2c920ae78 (3 months ago) • 2021-07-21 20:36:04 -0400
Engine • revision 9970b94793
Tools • Dart 2.14.0 (build 2.14.0-341.0.dev)
[+949919 ms] [+949828 ms] kernel_snapshot: Complete


`

```

**Comment by agacemi** [comment] 2021-10-29 21:35
@alexmarkov  I try to get the time as you requested in https://github.com/dart-lang/sdk/issues/47546#issuecomment-954042231  but I get the fellowing error:
```
ERROR: FormatException: Could not find an option named "intermediate-dill".
```

**Comment by alexmarkov** [comment] 2021-10-29 22:16
Thank you for confirming the flutter revision which caused the regression on your app. In the range of commits between 2.14.0-340.0.dev and 2.14.0-341.0.dev there's only one suspect: 939b7defa8158618a55765c6523a4c8854e9a23e. It's still not clear why it regressed compilation time. Is there an auto-generated code involving huge conditions with `is` tests in your app?

Re: timing compilation in 2 steps:
- the first step shouldn't have `--aot` option and should have `--output-dill intermediate.dill` (or `--output-dill=intermediate.dill`, both variants are allowed).
- the 2nd step should have `--aot` and `--from-dill=intermediate.dill`.

The options should be specified after frontend_server.dart.snapshot and before the main library (`package:xxxxxxxxx/main.dart`). Note that there's no `intermediate-dill` option.

Also, could you please do the following experiment:
- get Dart SDK sources (as explained at https://github.com/dart-lang/sdk/wiki/Building#getting-the-source)
- `git checkout 2.14.0-341.0.dev`
- run the build command in the following way (where $DART is the path to Dart SDK sources):
```
dart -Dglobal.type.flow.print.stats=true --disable-dart-dev --packages=$DART/.packages $DART/pkg/frontend_server/bin/frontend_server_starter.dart
```
(and append all options passed after frontend_server.dart.snapshot)
This should print some high-level statistics which may be useful.

**Comment by agacemi** [comment] 2021-11-03 07:31
@alexmarkov : 

## About usage of "is"

Concerning "is", it is used mainly by two ways via auto_router.gr.dart:

1. via direct usage ( ~160 usages) of a generic function [argsAs<T>](https://github.com/Milad-Akarie/auto_route_library/blob/5a1f1cc752801037cd00907cd6de4e9587f18788/auto_route/lib/src/route/route_data.dart#L33)  in the generated code of auto_route.gr.dart (like  `routeData.argsAs<MainScreenRouteArgs>(..,` , `routeData.argsAs<SplashScreenRouteArgs>(` ...). 
I comment the` is` by replacing it by always true expression, I didn't observe a signifiant impact. 
2. via transitive usage (~ 600 usages): Screens uses generated models via Open API generator. Each class override the == operator and uses `is `operator.  like this:
```
 bool operator ==(Object other) {
    if (identical(other, this)) return true;
    return other is Address &&
        building == other.building &&
        city == other.city &&
        companyName == other.companyName &&
        complement == other.complement &&
        countryId == other.countryId &&
        mainAddress == other.mainAddress &&
        zipCode == other.zipCode;
  }
```
By replacing the 600 usages of `is` usage by == operator (and having `dynamic other` instead of `Object other` to allow compilation),  I observed a light impact but still long.

```
Tools • Dart 2.14.0 (build 2.14.0-341.0.dev)

With is Operator
[+976749 ms] [+976654 ms] kernel_snapshot: Complete

With == instead of is
[+882000 ms] [+881996 ms] kernel_snapshot: Complete
```

## Requested measurements

I realized measurements with 4 versions:

- Flutter 2.4.0-5.0.pre.46 that uses Dart 2.14.0 **(build 2.14.0-310.0.dev)**: last version without any regression
- Flutter 2.4.0-5.0.pre.47  that uses  Dart 2.14.0 **(build 2.14.0-312.0.dev)** and also **(build 2.14.0-311.0.dev)**: Via `git bisect` in our project, this version have the first regression. In https://github.com/dart-lang/sdk/issues/47546#issuecomment-955000680, you seems identify the suspect commit  (reproductible on the sample project provided by @jyardin )
- Flutter 2.4.0-5.0.pre.135 that uses Dart 2.14.0 **(build 2.14.0-340.0.dev)**: last version before the second regression
- Flutter 2.4.0-5.0.pre.136 that uses Dart 2.14.0 **(build 2.14.0-341.0.dev)**: the version that introduced the second regression (the most important one)

### Dart 2.14.0 (build 2.14.0-310.0.dev)  

```
Flutter 2.4.0-5.0.pre.46 • channel unknown • unknown source
Framework • revision a0e5fe84ac (4 months ago) • 2021-07-13 22:04:03 -0700
Engine • revision bde2f52888
Tools • Dart 2.14.0 (build 2.14.0-310.0.dev)

Step 1 (without aot):

/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            34.88s user 2.12s system 149% cpu 24.737 total
-rw-r--r-- 1 abdelaziz_gacemi 81809912 Nov  1 23:19 intermediate.dill


Step 2: (with aot and from intermediate.dill)

/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            255.79s user 3.79s system 110% cpu 3:55.27 total

```
### Dart 2.14.0 (build 2.14.0-312.0.dev)  

```
Flutter 2.4.0-5.0.pre.47 • channel unknown • unknown source
Framework • revision e990f4b912 (4 months ago) • 2021-07-14 01:26:04 -0400
Engine • revision 093c4ed1a3
Tools • Dart 2.14.0 (build 2.14.0-312.0.dev)

Step 1 (without aot):


/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            34.49s user 2.10s system 145% cpu 25.227 total
-rw-r--r-- 1 abdelaziz_gacemi 81810008 Nov  1 23:40 intermediate.dill

Step 2: (with aot and from intermediate.dill)


/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            302.96s user 3.54s system 107% cpu 4:46.29 total


```

### Dart 2.14.0 (build 2.14.0-340.0.dev)

```
Flutter 2.4.0-5.0.pre.135 • channel unknown • unknown source
Framework • revision becd5ec8b1 (3 months ago) • 2021-07-21 17:16:06 -0700
Engine • revision 0c943571ac
Tools • Dart 2.14.0 (build 2.14.0-340.0.dev)

Step 1 (without aot):


/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            43.09s user 2.76s system 122% cpu 37.510 total
-rw-r--r-- 1 abdelaziz_gacemi 81841392 Nov  1 22:38 intermediate.dill


Step 2: (with aot and from intermediate.dill)


/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            298.58s user 4.36s system 104% cpu 4:50.03 total

```


### Dart 2.14.0 (build 2.14.0-341.0.dev)

```
Flutter 2.4.0-5.0.pre.136 • channel unknown • unknown source
Framework • revision c2c920ae78 (3 months ago) • 2021-07-21 20:36:04 -0400
Engine • revision 9970b94793
Tools • Dart 2.14.0 (build 2.14.0-341.0.dev)

Step 1 (without aot):


/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            36.33s user 2.46s system 147% cpu 26.284 total
-rw-r--r-- 1 abdelaziz_gacemi 81841392 Nov  1 23:56 intermediate.dill


Step 2: (with aot and from intermediate.dill)


/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart            1077.92s user 7.57s system 103% cpu 17:24.81 total
```


## About verbose mode

I fellow all steps as explained in https://github.com/dart-lang/sdk/issues/47546#issuecomment-955078084. When launching command, I obtained an error as below. Have you an explanation ?  Could you suggest me a solution please..

```
/Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/dart-sdk/bin/dart -Dglobal.type.flow.print.stats=true  --disable-dart-dev --packages=/Users/abdelaziz_gacemi/Devhome/dart-sdk2/sdk/.packages /Users/abdelaziz_gacemi/Devhome/dart-sdk2/sdk/pkg/frontend_server/bin/frontend_server_starter.dart --sdk-root /Users/abdelaziz_gacemi/Devhome/dart-sdk2/sdk/xcodebuild/ReleaseX64 --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages /Users/abdelaziz_gacemi/Devhome/GitProjects/xxxxxxx/.dart_tool/package_config.json --output-dill /Users/abdelaziz_gacemi/Devhome/GitProjects/xxxxxx/.dart_tool/flutter_build/f904574e7de55dfa0cad170293dc4c56/app.dill --depfile /Users/abdelaziz_gacemi/Devhome/GitProjects/xxxxxx/.dart_tool/flutter_build/f904574e7de55dfa0cad170293dc4c56/kernel_snapshot.d package:invictus/main.dart
```

```
Unexpected Kernel Format Version 68 (expected 74) when reading file:///Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/platform_strong.dill.
#0      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:640:9)

```


Thanks

**Comment by alexmarkov** [comment] 2021-11-03 17:30
@agacemi Thank you for the measurements. Now it's clear that there're 2 different regressions. Let's focus on the 2nd regression (from 2.14.0-340.0.dev to 2.14.0-341.0.dev) as it's much more severe.

> Unexpected Kernel Format Version 68 (expected 74) when reading file:///Users/abdelaziz_gacemi/Devhome/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/platform_strong.dill.


It looks like you ran the most recent version of compiler from Dart SDK which uses the most recent version of kernel format (74). Please make sure that you check out Dart at `2.14.0-341.0.dev` (which uses version 68) by running `git checkout 2.14.0-341.0.dev` in `/Users/abdelaziz_gacemi/Devhome/dart-sdk2/sdk`. Also, make sure that `--sdk-root` still points to the Flutter artifacts, and Flutter is checked out at the compatible version (`c2c920ae78d91ea4d4c5c6c2410f94db7f54af84`) and `flutter doctor` (or flutter build) was executed to download flutter artifacts corresponding to that version.

Please run the build with `-Dglobal.type.flow.print.stats=true` for `2.14.0-341.0.dev` and `2.14.0-340.0.dev` and post the output here. If printed `TF analysis` time regressed, then please also add `-Dglobal.type.flow.print.timings=true` (expect a lot of output) and check the top methods where analysis spent the most time.

**Comment by agacemi** [comment] 2021-11-04 04:55
@alexmarkov Please find below the requested analysis  (stats and timing). Hope this helping the investigation. 

- [tfa-stats-timing-2.14.0.340.0.dev.txt](https://github.com/dart-lang/sdk/files/7472398/tfa-stats-timing-2.14.0.340.0.dev.txt)
- [tfa-stats-timing-2.14.0.341.0.dev.txt](https://github.com/dart-lang/sdk/files/7472399/tfa-stats-timing-2.14.0.341.0.dev.txt)

Thanks

**Comment by alexmarkov** [comment] 2021-11-04 05:49
Thank you, that was useful.

It looks like compiler is analyzing `_$FooSerializer.deserialize` methods 6x-7x more times, and there're many of them (at least several hundreds). I suspect some kind of combinatorial explosion of argument types, but not sure why existing safeguards didn't work. Also, it's still not clear how more precise handling of `is` tests in the analysis caused this.

Could you show the sources for these (probably auto-generated) classes such as `_$ShortItineraryLegSerializer`, `_$DisplayUpdateCompanionPageSerializer`, `_$CartSerializer`, or at least their `deserialize` methods?

Could you try to create a sample using the same generators?

**Comment by agacemi** [comment] 2021-11-04 09:34
@alexmarkov I added these classes to the sample (@jyardin  could you add this to the repo, I haven't pushh authorization yet) . Unfortunately, I can't reproduire the behavior of our project
[build_time_app.zip](https://github.com/dart-lang/sdk/files/7473711/build_time_app.zip)

**Comment by jyardin** [comment] 2021-11-04 10:33
I think I reproduced the problem in the small app.
You can checkout the [build-time-regression-2](https://github.com/jyardin/build_time_app/tree/build-time-regression-2) branch in the build_time_app repo to reproduce it.
Here are the TF stats for this branch:
### dart 2.14.0-340.0.dev
[build_time_app_tf_stats_340.txt](https://github.com/dart-lang/sdk/files/7474101/build_time_app_tf_stats_340.txt)
### dart 2.14.0-341.0.dev
[build_time_app_tf_stats_341.txt](https://github.com/dart-lang/sdk/files/7474102/build_time_app_tf_stats_341.txt)

**Comment by alexmarkov** [comment] 2021-11-08 20:11
@jyardin Thank you for the reproduction. Here is what happens in that example:

- There are 100 generated _$Model{0..99}Serializer classes with `deserialize` methods. Summary of each methods has more than 300 operations, which is very large.
- Analysis tracks ~60 invocations of each `deserialize` method with different combinations of argument types (mostly coming from different constant values of `specifiedType` argument). This is not an extremely large number (per method), so number of different invocations is not capped yet. That gives about 60*100 = 6000 invocations of `deserialize` methods to analyze.
- Each `deserialize` method has 50 type checks `as Model{0..49}`. Since 939b7defa8158618a55765c6523a4c8854e9a23e analysis detects type checks which always fail, and for this reason it checks if there are allocated subtypes of Model{0..49}. That check establishes dependency between each `deserialize` method and hierarchy of all Model{0..49} classes.
- Each time analysis discovers a new allocated subtype of Model{0..49} class, it needs to invalidate all invocations of `deserialize` methods which were analyzed so far and re-analyze them. So `deserialize` methods are analyzed roughly 50*6000 = 300 000 extra times after 939b7defa8158618a55765c6523a4c8854e9a23e.
- As I already mentioned, `deserialize` methods are pretty big and their analysis takes some time (roughly 0.2ms per summary on my machine), which results in extra ~60s of analysis time.

I don't see anything wrong in depending on the hierarchy of a type used in a type check (`is` or `as`), which was added in 939b7defa8158618a55765c6523a4c8854e9a23e. In order to fix this regression, I'd like to explore the possibility to limit number of different invocations to analyze for huge methods: for example we can always use just 1 approximate invocation for a method if its summary exceeds N operations.

**Comment by jyardin** [comment] 2021-11-09 10:48
Thank you for sharing your findings @alexmarkov 

As a workaround, we tried removing `const` values affected to the `specifiedType` argument from the generation of the `built_value` library, and we noticed a big decrease of build time in our project. Does it makes sense?
I'm not sure about the performance impact at runtime though.

**Comment by alexmarkov** [comment] 2021-11-11 19:23
@jyardin That sounds like a reasonable workaround.

I landed the change 1f3e5ed0078fbb096c61c06a9c9c1158a09dd5d6 which should bound the time spent in compiler on analyzing huge methods. Could you check if it helps for your application? I don't expect it to eliminate the regression entirely, but it should be much smaller after this change. In order to try this change you might need to wait several days for the change to roll into Flutter and then use bleeding edge (master) channel of Flutter. Thanks!

**Comment by chgibb** [comment] 2021-11-11 19:48
Could there be an opportunity to cache some of these sub-operations and allow consumers to save and restore these caches when compiling in release mode in the future?

**Comment by agacemi** [comment] 2021-11-11 20:44
Thank you for @alexmarkov for the solution. We can test the solution on our project using Flutter Dev channel. Do you know in which Dart dev version, this commit will be available ?

**Comment by alexmarkov** [comment] 2021-11-15 21:20
The change was rolled to Flutter in https://github.com/flutter/flutter/commit/dbd2b9316c61f9b111a6558468d92ac384231534. It's probably hasn't reached `dev` branch yet.

**Comment by alexmarkov** [comment] 2021-12-16 18:41
Now both `dev` and `beta` branches in Flutter should have the fix. @agacemi Could you test if it helps for your app?

**Comment by agacemi** [comment] 2021-12-27 13:46
@alexmarkov I tested the fix using flutter via beta and dev channel and I was surprised that, even the fix works well on the provided sample, doesn't unfortunately work on our project.  Most surprisingly, the time increase when using the dart version that contains the fix (2.16.0-80.1.beta )

To help analysis, I made some measurements  to provide tfa stats and timing for each case:
- Using **dart 2.15.1** via flutter stable VS **dart 2.16.0.80.1** via flutter beta and flutter dev
- Applying the workaround (explained in https://github.com/dart-lang/sdk/issues/47546#issuecomment-964031695) VS without the workaround

|   |   With Workaround (by removing const in the models)  |  Without Workaround      |
|---    |---    |---    |
|   Dart 2.15.1   (via flutter stable)  |  Time: **144082 ms**  [tfa-sta-timing-2.15.1-stable-with-workaround.txt](https://github.com/dart-lang/sdk/files/7780322/tfa-sta-timing-2.15.1-stable-with-workaround.txt)    |  Time:  **1224884 ms**  [tfa-sta-timing-2.15.1-stable-without-workaround.txt](https://github.com/dart-lang/sdk/files/7780328/tfa-sta-timing-2.15.1-stable-without-workaround.txt)  |     
|  Dart  2.16.0-80.1.beta    (via flutter beta and dev) | Time:  **180683 ms** [tfa-sta-timing-2.16.0-80.1.beta-with-workaround.txt](https://github.com/dart-lang/sdk/files/7780333/tfa-sta-timing-2.16.0-80.1.beta-with-workaround.txt)   |   Time: **1785082 ms**  [tfa-sta-timing-2.16.0-80.1.beta-without-workaround.txt](https://github.com/dart-lang/sdk/files/7780326/tfa-sta-timing-2.16.0-80.1.beta-without-workaround.txt)  |    

I note that I didn't make a git bisect to confirm that these changes come from the fix. Our current project code base dont't compile with flutter 2.6 and bisecting become quite difficult ..

**Comment by agacemi** [comment] 2022-01-24 09:46
Hi @alexmarkov , any update for this issue? Thanks

**Comment by alexmarkov** [comment] 2022-01-24 15:30
At this point I can suggest you the following:

1. Try out the latest (recently branched) Flutter `beta`. The latest `beta` includes https://github.com/dart-lang/sdk/commit/e698500693603374ecc409e158f36c25bff45b12 which might help.
2. Run compilation using the local Dart SDK checkout (but without `-Dglobal.type.flow...` flags) and experiment with different (lower) values of the following constants:
https://github.com/dart-lang/sdk/blob/e2acafdf800dcd0d5cc2eeed32c85ec9ddfe0db8/pkg/vm/lib/transformations/type_flow/analysis.dart#L767-L775
You can try to lower values of these constants (especially `largeSummarySize`) and figure out values suitable for your application. If this proves useful, we can probably expose these constants as configurable command-line flags (or maybe we can consider just changing values of the constants if desired values are still large enough and don't cause any regressions).

**Comment by agacemi** [comment] 2022-02-03 10:02
@alexmarkov I made several measurements with the fellowing flutter beta version:

```
Building flutter tool...
Flutter 2.10.0-1.0.pre.1 • channel unknown • unknown source
Framework • revision 0c211191b0 (26 hours ago) • 2022-01-31 13:03:46 +0100
Engine • revision 5ac30ef0c7
Tools • Dart 2.16.0 (build 2.16.0-134.5.beta) • DevTools 2.9.2
```
The results are clearly betters and we obtain very good performances.


-  **On CI using AWS Runner without the workaround https://github.com/dart-lang/sdk/issues/47546#issuecomment-964031695:** dart --tfa --aot  .. task takes **282 599 ms** ms using **Dart 2.16.0-134.5.beta**  instead of **2 443 499 ms** using **Dart 2.15.1** (via stable channel)..That is great job

- **In my local machine, also without workaround**, dart task takes **254403 ms**  instead of  **1 111 759 ms** 

I also made on my local machine some measurements to experiment different values of **(maxInvocationsPerSelector, maxDirectInvocationsPerSelector)**. I obtain the fellowing results:


- (50, 5):  +279 207 ms
- (100, 5): +248 394 ms
- (200, 5): +264 000 ms
- (300, 5): 316 299 ms
- (300, 10): 254 403 ms
- (100, 10): 319 306 ms

I think that current values (300, 10) give an acceptable performance. I don't think that we need to expose this constants via command line configuration. 

Thank you for this great job. I think we can close this issue.

**Closed** 2022-02-03 15:42 UTC
Labels: area-vm
