### ISSUE TITLE
Dart VM rejects a generic method named "get" (but analyzer accepts it)

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#29063] opened 2017-03-14 01:27 UTC
Example, 

```
class A {
  get<T extends List>(T foo) {} //Rejected by Dart VM, but OK in dartanalyzer
}

class B {
  get(List foo) {}
}

void main() {
  new B().get([]); //OK
  new A().get([]); //Failed
}
```

I'm using 1.22.1

**Comment by lrhn** [comment] 2017-03-14 09:50
Grammar allows it, so it's a VM parser bug.

**Comment by lrhn** [comment] 2017-03-14 14:13
I think I'll leave the fix of this to someone who actually knows the VM parser.

**Comment by aam** [comment] 2017-04-12 16:28
I think vm parser accepts it if you enable  --generic_method_semantics flag, but it fails later since support of generic methods is work in progress(https://github.com/dart-lang/sdk/commit/09b5d6f619c415fcf885bffd868c1f09c1cd9989).
===
../../runtime/vm/flow_graph_builder.cc: 2718: error: unimplemented code
Dumping native stack trace for thread 3366
  [0x08651ed3] dart::Profiler::DumpStackTrace()
  [0x08651ed3] dart::Profiler::DumpStackTrace()
  [0x082bb75e] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x083bd87f] dart::EffectGraphVisitor::BuildInstantiatedTypeArguments(dart::TokenPosition, dart::TypeArguments const&)
  [0x083bda6e] dart::EffectGraphVisitor::BuildObjectAllocation(dart::ConstructorCallNode*)
  [0x083bdf15] dart::ValueGraphVisitor::VisitConstructorCallNode(dart::ConstructorCallNode*)
===

**Comment by a-siva** [comment] 2017-09-19 00:38
Regis, is this still an issue?

**Comment by crelier** [comment] 2017-09-19 02:08
According to the spec (https://gist.github.com/eernstg/4353d7b4f669745bed3a5423e04a453c), getters cannot be declared as generic:
"With the syntax in place, it is obvious that certain potential extensions have not been included. 
For instance, constructors, setters, getters, and operators cannot be declared as generic."

Unless I am looking at the wrong spec, the bug is actually with the analyzer, which should not allow it.

**Comment by crelier** [comment] 2017-09-19 02:14
I take back my comment. I should have read the report more carefully. I see now that it is not a getter, but a method called "get". The question is whether a method is allowed to be called "get". I cannot remember. Let me look at it tomorrow.

**Comment by lrhn** [comment] 2017-09-19 05:35
Just for the record: Methods can be called `get`.

The word `get` is a *built-in identifier* in Dart, which only prevents it from being used as the name of a type (class, typedef, type parameter) or a library prefix. It's allowed everywhere else.

**Comment by eernstg** [comment] 2017-09-19 06:40
(Note that the current version of the informal spec that Regis mentioned is https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generic-method-syntax.md. The differences between the old and current version don't matter for this issue: The generic method named `get` in `A` is OK).

**Comment by crelier** [comment] 2017-09-19 16:23
This is a duplicate of #29746, which I fixed in May: 
https://codereview.chromium.org/2911333002/
No, I have no memory.

**Closed by crelier** 2017-09-19 16:23 UTC
Labels: area-vm, Type: bug
