### ISSUE TITLE
compile_platform.dart fails when running in strong mode

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#31974] opened 2018-01-25 15:29 UTC
(because of this failure we still have to use `patch-sdk` infrastructure).

@peter-ahe-google wrote:

>You can produce the problem without a CL, but I've created this CL for your convenience: https://dart-review.googlesource.com/36641
>
>With this CL patched in, attempt to build "kernel_platform_files", that is:
>
>ninja -C xcodebuild/ReleaseX64/ kernel_platform_files
>
>You should see a lot of errors and eventually a crash during serialization.
>
>Without patching in the CL, the problem can be reproduced running this command:
>
>./tools/sdks/mac/dart-sdk/bin/dart pkg/front_end/tool/_fasta/compile_platform.dart --strong-mode dart:core sdk/lib/libraries.json vm_platform_strong.dill >vm_outline_strong.dill
>
>This is essentially the command that fails during the build, except that I've relativized the file names to the SDK repository root directory.
>
>Now I start guessing and hypothesizing, so take the following with a healthy dose of skepticism.
>
>I haven't looked into this, but I do have a suspicion about what the problem is: my guess is that top-level inference isn't aware of patching and sometimes records type >variables of patch elements.
>
>This is the first compile-time error I see:
>
>runtime/lib/collection_patch.dart:29:22: Error: A value of type 'dart.collection::_HashMap<<No Library>::•::K, <No Library>::•::V>' can't be assigned to a variable of >type 'dart.collection::HashMap<dart.collection::HashMap::•::K, dart.collection::HashMap::•::V>'.
>Try changing the type of the left hand side, or casting the right hand side to 'dart.collection::HashMap<dart.collection::HashMap::•::K, dart.collection::HashMap::•::V>'.
>          return new _HashMap<K, V>();
>                     ^
>
>This is the top of the stack trace that happen much later during serialization:
>
>NoSuchMethodError: The method '<' was called on null.
>Receiver: null
>Tried calling: <(128)
>#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
>#1      BinaryPrinter.writeUInt30 (package:kernel/binary/ast_to_binary.dart:79:15)
>#2      BinaryPrinter.visitTypeParameterType (package:kernel/binary/ast_to_binary.dart:1539:5)
>#3      TypeParameterType.accept (package:kernel/ast.dart:5076:34)
>#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:220:10)
>#5      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:20)
>#6      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:212:7)
>#7      BinaryPrinter.visitInterfaceType (package:kernel/binary/ast_to_binary.dart:1492:7)
>#8      InterfaceType.accept (package:kernel/ast.dart:4779:34)
>#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:220:10)
>#10     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:20)
>#11     BinaryPrinter.visitAsExpression (package:kernel/binary/ast_to_binary.dart:1096:5)
>#12     AsExpression.accept (package:kernel/ast.dart:3157:36)
>#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:220:10)
>#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55:20)
>#15     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:228:7)
>#16     BinaryPrinter.visitReturnStatement (package:kernel/binary/ast_to_binary.dart:1387:5)
>#17     ReturnStatement.accept (package:kernel/ast.dart:4150:35)
>
>This indicates to me that we're holding on to a type variable that isn't serialized. This could be a type variable from a patch method or class.
>
>Looking more at the error message above, it comes from this code:
>
>@patch
>class HashMap<K, V> {
>  @patch
>  factory HashMap(
>      {bool equals(K key1, K key2),
>      int hashCode(K key),
>      bool isValidKey(potentialKey)}) {
>    if (isValidKey == null) {
>      if (hashCode == null) {
>        if (equals == null) {
>          return new _HashMap<K, V>();
>
>Initially, the OutlineBuilder creates a ShadowClass representing this patch class. There will be two ShadowClass objects representing HashMap:
>
>1. The origin class declaration (the one from sdk/lib/collection/hash_map.dart)
>2. The patch class declaration (the one from runtime/lib/collection_patch.dart).
>
>The latter is supposed to be unreachable after KernelClassBuilder.applyPatch. I think "<No Library>::•::K" is a type variable from the patch class, but I don't >>>>understand how.

@stereotype441 wrote:

> I took a look into the first error and I think you're right - we're holding on to a type variable that isn't serialized.  It looks like it's coming from > ProcedureBuilder.computeTypeParameterScope--if I add some debugging code to that method, I see that just prior to the error being issued, computeTypeParameterScope is > called, and each of the variables in typeVariables has a .parent of LibraryBuilder(<library 'file:///usr/local/google/home/paulberry/dart1/sdk/runtime/lib/> collection_patch.dart'>).
> 
> I suspect that what's happening here is that we're hitting a corner case related to factory constructors.  Since factory constructors are represented in kernel as static > methods, the front end has to generate synthetic type parameters for them, e.g. this code:
> 
> class C<T> {
>   factory C.foo() { ... }
> }
> 
> gets compiled to something roughly like:
> 
> class C<T> {
>   static C<T> foo<T>() { ... } 
> }
> 
> It looks like the logic to create the synthetic type variables is in DeclarationBuilder.resolveTypes(), (see the statement starting "factoryDeclarations.forEach" in the > "else" block).  At the time this runs, the type variables being copied appear to be pointing to the patch file.
> 
> I'm guessing that in KernelProcedureBuilder.applyPatch we need to check if the ProcedureKind is ProcedureKind.Factory, and if it is, replace the type variables in the > procedure with copies from the parent class.  If there are any references to the type parameters in the factory method's formal parameters, they might need to be fixed > up too.
> 
> Does this make sense?  I'm not terribly familiar with this code, so I'm hoping this is enough information for one of you to pick it up from here.  Let me know if you'd > like me to dig further.

**Comment by aam** [comment] 2018-01-25 15:31
cc @mraleph

**Comment by sigmundch** [comment] 2018-01-26 18:14
cc @keertip (since this is the same that is being tracked in #28822)

**Comment by kmillikin** [comment] 2018-01-31 15:06
Closing this as a duplicate of #28822.

**Closed by kmillikin** 2018-01-31 15:06 UTC
Labels: P2 medium, area-front-end, front-end-fasta
