### ISSUE TITLE
codesigning errors on mac m1 bots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#49275] opened 2022-06-16 16:43 UTC
pkg/_fe_analyzer_shared/test/macros/executor/executor_test
pkg/dartdev/test/commands/compile_test
pkg/vm_snapshot_analysis/test/precompiler_trace_test

fail with codesigning errors on mac m1 bots

From [log](https://dart-ci.appspot.com/log/pkg-mac-release-arm64/unittest-asserts-release-mac-arm64/3820/pkg/vm_snapshot_analysis/test/precompiler_trace_test):
```
--- Command "vm" (took 08.000258s):
DART_CONFIGURATION=ReleaseARM64 CHROME_PATH="/opt/s/w/ir/cache/builder/sdk/third_party/browsers/chrome/Google Chrome.app/Contents/MacOS/Google Chrome" xcodebuild/ReleaseARM64/dart-sdk/bin/dart --enable_asserts -Dtest_runner.configuration=unittest-asserts-release-mac-arm64 --ignore-unrecognized-flags --packages=/opt/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /opt/s/w/ir/cache/builder/sdk/pkg/vm_snapshot_analysis/test/precompiler_trace_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: precompiler-trace basic-parsing[0m

00:01 [32m+0[0m[31m -1[0m: precompiler-trace basic-parsing [1m[31m[E][0m[0m

  Expected: <0>
    Actual: <64>
  Compilation completed with exit code 64.
  
  Command line: /opt/s/w/ir/cache/builder/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/dart compile exe -o /opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/output.exe --packages=/opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/.packages --extra-gen-snapshot-options=--dwarf-stack-traces,--trace_precompiler_to=/opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/sizes.json /opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/main.dart
  
  stdout: Info: Compiling without sound null safety
  Failed to add a linker signed signature, adding a regular signature instead.
  Failed to replace the dartaotruntime signature, 
  subcommand terminated with exit code 1.
  Subcommand stderr:
  /opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/output.exe: replacing existing signature
  /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/output.exe malformed object (offset field of section 0 in LC_SEGMENT command 1 not past the headers of the file)
  /opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/output.exe: the codesign_allocate helper tool cannot be found or used
  
  
  stderr: Error: AOT compilation failed
  Could not sign the new executable
 ```

**Comment by athomas** [comment] 2022-06-16 17:11
I see this message saying that output.exe is malformed? Isn't that a VM issue?
```
  /opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/output.exe: replacing existing signature
  /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /opt/s/w/ir/x/t/instruction-sizes-test-lG5VgV/output.exe malformed object (offset field of section 0 in LC_SEGMENT command 1 not past the headers of the file)
```

**Comment by aam** [comment] 2022-06-16 17:15
> I see this message saying that output.exe is malformed? Isn't that a VM issue?

It seems unlikely as it started to fail on seemingly unrelated change.
Were there any changes to xcode toolchain on the bots done recently?

**Comment by aam** [comment] 2022-06-16 17:25
cc @sstrickl who might have more context for codesigning potential source of failures.

**Comment by athomas** [comment] 2022-06-16 17:27
No, same version of xcode installed on failing and passing builds. Also, it recovered on a later commit.

**Comment by aam** [comment] 2022-06-16 17:29
> No, same version of xcode installed on failing and passing builds. Also, it recovered on a later commit.

I don't think it did - _fe_analyzer_shared/test/macros/executor/executor_test is still RuntimeError according to [results.json](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8811184651806829057/+/u/add_fields_to_result_records/results.json). I just approved those failure, which turned the bot green.

**Comment by athomas** [comment] 2022-06-16 17:33
Ah sorry.

**Comment by aam** [comment] 2022-06-16 18:09
another failure on different m1 bot https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8811182848651754113/+/u/test_results/new_test_failures__logs_

**Comment by sstrickl** [comment] 2022-07-01 11:03
So unfortunately the log output is nearly useless for figuring out why there was a failure (going to make a small CL to make that better), but on my local M1 laptop these seem to be working a-ok, so I'm going to have to try things out on the trybots themselves.

**Comment by sstrickl** [comment] 2022-07-01 12:16
(Just realized that the first log in the issue _does_ have the extra info I'm interested in, so yeah, will have to dig into why it's thinking the Mach-O file is malformed on the trybots, especially since I'm not getting this error locally 🤔)

**Comment by a-siva** [comment] 2022-08-24 20:09
Marking this as a duplicate of https://github.com/dart-lang/sdk/issues/49783

**Closed by a-siva** 2022-08-24 20:09 UTC
Labels: area-vm, closed-duplicate, gardening
