### ISSUE TITLE
analysis server stacktrace - Invalid argument(s): Wrong number of type arguments supplied

### ISSUE THREAD

**Issue by VincentHu76** [dart-lang/sdk#36213] opened 2019-03-14 17:47 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-183.5153.38`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IU-183.5153.38, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: D:\work\project\lianqun\src\cacart\1.0\08-cacart_flutter\lib\sureshare\framework\core\action.dart
Invalid argument(s): Wrong number of type arguments supplied
#0      GenericTypeAliasElementImpl.doInstantiate (package:analyzer/src/dart/element/element.dart:4824:7)
#1      GenericTypeAliasElementForLink.buildType (package:analyzer/src/summary/link.dart:3410:44)
#2      CompilationUnitElementForLink.resolveTypeRef (package:analyzer/src/summary/link.dart:1471:26)
#3      VariableElementForLink.declaredType (package:analyzer/src/summary/link.dart:5533:27)
#4      FieldElementForLink_ClassField.type (package:analyzer/src/summary/link.dart:2580:9)
#5      PropertyAccessorElementForLink_Variable.returnType (package:analyzer/src/summary/link.dart:4682:23)
#6      _FunctionTypeImplLazy.baseReturnType (package:analyzer/src/dart/element/type.dart:3461:57)
#7      _FunctionTypeImplLazy.returnType (package:analyzer/src/dart/element/type.dart:3549:36)
#8      InstanceMemberInferrer._computeFieldOverrideType (package:analyzer/src/task/strong_mode.dart:118:31)
#9      InstanceMemberInferrer._inferAccessor (package:analyzer/src/task/strong_mode.dart:252:9)
#10     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:306:11)
#11     InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:326:9)
#12     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:55:5)
#13     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1638:7)
#14     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#15     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#16     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#20     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#21     _relink (package:analyzer/src/summary/link.dart:305:57)
#22     link (package:analyzer/src/summary/link.dart:123:3)
#23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#44     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#45     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#46     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#47     main (file:///E:/b/rr/tmpxc66kk/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#48     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\user\AppData\Local\Temp\report1.txt.

**Comment by srawlins** [comment] 2019-09-06 16:05
Thanks for reporting this issue! The analyzer team has a minimal reproduction at https://github.com/dart-lang/sdk/issues/38072; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 16:05
Duplicate of https://github.com/dart-lang/sdk/issues/38072

**Closed by srawlins** 2019-09-06 16:05 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
