### ISSUE TITLE
build_web_compilers:ddc on lib/app_component.template.ddc.module: Error compiling dartdevc module:project_bug|lib/app_component.template.ddc.js

### ISSUE THREAD

**Issue by Urfoex** [dart-lang/sdk#37588] opened 2019-07-20 07:54 UTC
Installed Dart on Debian.
Set up a fresh web-angular project and run webdev serve.
Changed lib/app_component.dart by adding a String field to the component:
```
class AppComponent {
  // Nothing here yet. All logic is in TodoListComponent.
    String name = "Hello World!";
}
```
Saved and then it threw an error and crashed:
[creation.log](https://github.com/dart-lang/sdk/files/3413332/creation.log)

When I remove that line again, it just throws the error. A few times taking the line back in and out it even errors and crashes without the line.

dart --version
Dart VM version: 2.4.0 (Unknown timestamp) on "linux_x64"

chromium --version
Chromium 76.0.3809.62 built on Debian bullseye/sid, running on Debian bullseye/sid

**Comment by vsmenon** [comment] 2019-08-08 19:16
@jakemac53 - from the log, this is the first error.  Any ideas?  Is this a build issue?

```
[INFO] Updating asset graph completed, took 16ms
[SEVERE]build_web_compilers:ddc on web/main.ddc.module: Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:project_bug/app_component.template.dart' as ng;` from project_bug|web/main.dart at 2:1

[SEVERE]build_web_compilers:entrypoint on web/main.dart: Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:project_bug/app_component.template.dart' as ng;` from project_bug|web/main.dart at 2:1
```

**Comment by jakemac53** [comment] 2019-08-08 19:28
I haven't been able to reproduce this, I tried with 2.4.0 specifically as well.

**Comment by jakemac53** [comment] 2019-08-08 19:29
It looks though like angular did not generate the component template file properly, so there could be something relating to the analyzer here?

**Comment by Urfoex** [comment] 2019-08-08 19:48
Friend and I saw it after saving in vim.
It seems to not have happened when saving in VSCode.

**Comment by jakemac53** [comment] 2019-08-08 19:51
Ah, likely a bad race condition of some sort then that we aren't recovering from (caused by the swap files).

**Comment by jakemac53** [comment] 2019-08-08 20:10
Confirmed I can repro this :cry:

**Comment by vsmenon** [comment] 2019-08-08 20:10
Hmm, I may have seen similar in emacs from editor-generated backup files -
e.g., #foo.dart.

**Comment by jakemac53** [comment] 2019-08-08 20:16
In my case actually it was followed up by a successful build which is the intended recovery case for this type of error, @Urfoex did you see a successful build immediately after the failed one?

**Comment by jakemac53** [comment] 2019-08-08 20:25
Also it looks like this only happens in daemon mode, so regular `pub run build_runner serve` should work.

**Comment by jakemac53** [comment] 2019-08-08 20:28
Closing as a duplicate of https://github.com/dart-lang/build/issues/2403 which I just opened

**Closed by jakemac53** 2019-08-08 20:28 UTC
Labels: area-web
