### ISSUE TITLE
Error during compilation in flutter: 'dart2js' entrypoint script is deprecated

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#52414] opened 2023-05-16 18:41 UTC
See https://github.com/flutter/flutter/issues/126534 for details.

**Comment by biggs0125** [comment] 2023-05-16 20:08
We believe this `'dart2js' entrypoint script is deprecated...` is a red herring and not the true source of the Flutter error. Closing this out until we get a better root cause from the Flutter issue.

**Closed by biggs0125** 2023-05-16 20:08 UTC
Labels: web-dart2js
