### ISSUE TITLE
[dev_compiler] Not found dev_compiler in the sdk for Linux arm64

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [dart-lang/sdk#44614] opened 2021-01-08 06:28 UTC
We are trying to work to support the Flutter Linux desktop for Linux Arm64 hosts (https://github.com/flutter/flutter/pull/61221). But I got the following error.

```
$ export CHROME_EXECUTABLE=/usr/bin/chromium-browser
$ flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...                 ⣽
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file, path =
'/home/hidenori/workspace/flutter/bin/cache/dart-sdk/lib/dev_compiler/kernel/amd/require.js' (OS Error:
No such file or directory, errno = 2)".
```

Currently, `dartsdk-linux-arm64-release.zip` doesn't contain dev_compiler.
https://storage.googleapis.com/dart-archive/channels/stable/release/2.10.4/sdk/dartsdk-linux-arm64-release.zip

## Related issues
- https://github.com/dart-lang/sdk/issues/39312

**Comment by vsmenon** [comment] 2021-01-08 14:14
@athomas @sigmundch - this is basically the same issue as https://github.com/dart-lang/sdk/issues/43776 right?  Should we merge?

**Comment by sigmundch** [comment] 2021-01-08 16:28
I agree. Marking this as a duplicate of #43776

**Closed by sigmundch** 2021-01-08 16:28 UTC
Labels: area-infrastructure, closed-duplicate
