### ISSUE TITLE
Analyzer issue

### ISSUE THREAD

**Issue by amitjangid80** [dart-lang/sdk#38670] opened 2019-10-01 09:08 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#10     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#11     Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:5226:12)
#12     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3814:14)
#13     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#14     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:5695:15)
#15     Parser.parseTryStatement (package:front_end/src/fasta/parser/parser.dart:5838:26)
#16     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3762:14)
#17     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#18     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#19     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#20     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#21     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#22     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#23     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#24     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#25     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#26     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#27     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#28     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#29     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#30     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#31     DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:701:10)
#32     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#33     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#34     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#35     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#36     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#37     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#38     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#39     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#45     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#47     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#48     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#49     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#50     new Future.sync (dart:async/future.dart:224:31)
#51     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#52     _rootRun (dart:async/zone.dart:1124:13)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _runZoned (dart:async/zone.dart:1516:10...
```

**Comment by srawlins** [comment] 2019-10-22 04:46
This has been reproduced in fuzz testing; please follow https://github.com/dart-lang/sdk/issues/39035.

**Comment by srawlins** [comment] 2019-10-22 04:46
Duplicate of https://github.com/dart-lang/sdk/issues/39035

**Closed by srawlins** 2019-10-22 04:46 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
