### ISSUE TITLE
Emulator crawshed

### ISSUE THREAD

**Issue by arjun069** [dart-lang/sdk#40517] opened 2020-02-07 11:12 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-edge.bbe2ac28c9ab5bfec4e13d5df9360e7aa691cfe6`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.7.0-edge.bbe2ac28c9ab5bfec4e13d5df9360e7aa691cfe6, server version 1.27.4, error: Analysis failed: D:\Documents\Projects\code\rento\test\widget_test.dart context: exception_20200207_164004_524
RangeError (index): Invalid value: Not in range 0..3, inclusive: 4
#0      List.[] (dart:core-patch/array.dart:13:52)
#1      _FbGenericList.[] (package:analyzer/src/summary/flat_buffers.dart:857:20)
#2      LinkedUnitContext.getInformativeData (package:analyzer/src/summary2/linked_unit_context.dart:430:27)
#3      AstBinaryReader._declaredIdentifier (package:analyzer/src/summary2/ast_binary_reader.dart:79:40)
#4      AstBinaryReader._read_functionDeclaration (package:analyzer/src/summary2/ast_binary_reader.dart:777:9)
#5      AstBinaryReader._readNode (package:analyzer/src/summary2/ast_binary_reader.dart:1764:16)
#6      AstBinaryReader._readNodeList (package:analyzer/src/summary2/ast_binary_reader.dart:1917:19)
#7      AstBinaryReader._read_compilationUnit (package:analyzer/src/summary2/ast_binary_reader.dart:358:23)
#8      AstBinaryReader._readNode (package:analyzer/src/summary2/ast_binary_reader.dart:1702:16)
#9      AstBinaryReader.readNode (package:analyzer/src/summary2/ast_binary_reader.dart:59:14)
#10     LinkedUnitContext._ensureUnitWithDeclarations (package:analyzer/src/summary2/linked_unit_context.dart:1053:26)
#11     LinkedUnitContext.unit_withDeclarations (package:analyzer/src/summary2/linked_unit_context.dart:92:5)
#12     _ElementRequest._createLibraryElement (package:analyzer/src/summary2/linked_element_factory.dart:310:27)
#13     _ElementRequest.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:147:14)
#14     LinkedElementFactory.elementOfReference (package:analyzer/src/summary2/linked_element_factory.dart:72:45)
#15     LinkedElementFactory.libraryOfUri (package:analyzer/src/summary2/linked_element_factory.dart:104:12)
#16     LinkedUnitContext.directiveLibrary (package:analyzer/src/summary2/linked_unit_context.dart:137:41)
#17     ImportElementImpl.importedLibrary (package:analyzer/src/dart/element/element.dart:5055:47)
#18     LibraryElementImpl.imports.<anonymous closure> (package:analyzer/src/dart/element/element.dart:5487:23)
#19     ListMixin.any (dart:collection/list.dart:130:15)
#20     LibraryElementImpl.imports (package:analyzer/src/dart/element/element.dart:5486:30)
#21     LibraryImportScope._createImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:509:52)
#22     new LibraryImportScope (package:analyzer/src/dart/resolver/scope.dart:403:5)
#23     new LibraryScope (package:analyzer/src/dart/resolver/scope.dart:619:19)
#24     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:148:25)
#25     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:116:14)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#27     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:115:43)
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1261:63)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1237:20)
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1047:17)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1926:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1860:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:223:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:609:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:728:12)
#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:607:7)
#44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:508:9)
#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:503:43)
#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#48     new Future.sync (dart:async/future.dart:222:31)
#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#50     _rootRun (dart:...
```

For additional log information, please append the contents of
file://C:\Users\arjun\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2021-02-26 17:14
Thanks for reporting this issue. This was previously reported at https://github.com/dart-lang/sdk/issues/40128; please follow along there.

**Comment by srawlins** [comment] 2021-02-26 17:14
Duplicate of https://github.com/dart-lang/sdk/issues/40128

**Closed by srawlins** 2021-02-26 17:14 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
