### ISSUE TITLE
error occured in dart analysis server

### ISSUE THREAD

**Issue by k-zeta** [dart-lang/sdk#34800] opened 2018-10-15 21:38 UTC
Analyzer Feedback ,

```
Unhandled exception:
FormatException: Invalid character (at character 11)
/home/p-c/[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin/cache/flutter_tools.s...
          ^

#0      _Uri._fail (dart:core/uri.dart:1614)
#1      _Uri._normalize (dart:core/uri.dart:2309)
#2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2265)
#3      _Uri._makePath (dart:core/uri.dart:2113)
#4      new _Uri.notSimple (dart:core/uri.dart:1477)
#5      Uri.parse (dart:core/uri.dart:1012)
#6      _resolveScriptUri (dart:_builtin:223)
```

**Comment by devoncarew** [comment] 2018-10-18 00:29
@karan7701, were there anymore lines in the stacktrace? Somebody is trying to parse the file path and having issues. Can you also append the first ~20 chars or so of the file path? It looks like you've elided some of it above. Thanks!

**Comment by karan7701** [comment] 2018-10-18 06:35
After changing the path name the problem did not occur more, but I am not sure why it occurred though. The error was showed as I have given in Android studio.

**Comment by devoncarew** [comment] 2018-10-18 14:18
I wonder if this might be a front-end issue? cc @kmillikin 

The error above:

```
Unhandled exception:
FormatException: Invalid character (at character 11)
/home/p-c/[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin/cache/flutter_tools.s...
          ^
```

looks like it ones generated by the FE. @karan7701, `[PATH_TO_FLUTTER_GIT_DIRECTORY]` was explicitly in your path?

**Comment by srawlins** [comment] 2019-09-09 20:24
Thanks for reporting this error! This was previously reported at https://github.com/dart-lang/sdk/issues/32532; please follow along there.

**Comment by srawlins** [comment] 2019-09-09 20:24
Duplicate of https://github.com/dart-lang/sdk/issues/32532

**Closed by srawlins** 2019-09-09 20:24 UTC
Labels: P2, analyzer-crash-report, area-analyzer, type-bug
