### ISSUE TITLE
Regression in aot_snapshot_compile_millis

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#31668] opened 2017-12-16 02:16 UTC
The time it takes to compile the AOT snapshot regressed across the board with https://github.com/flutter/flutter/pull/13570:

![aot_snapshot_compile_regression](https://user-images.githubusercontent.com/551196/34066472-fb3c9148-e1c3-11e7-9dc6-a7b48e6f3270.png)

**Comment by Hixie** [comment] 2017-12-16 02:18
It's also visible in some of the debug and release compile numbers, but not as dramatically.

**Comment by mraleph** [comment] 2017-12-17 19:25
This is caused by cf1de7d46cd88e204380e8f96a993439be56b24c - which changes how we generate functions prologues by offloading this from hand written assembly into IL and letting compiler optimize it. This significantly improves architecture (no more complicated handwritten assembly on 4 different platforms) but increases load on the compiler. 

This should however only have affected functions with optional/named arguments, so overall 8% compilation time hit might not be within our projections. 

@mkustermann Martin could you take a look and see if we something is going south?

**Comment by Hixie** [comment] 2017-12-17 19:31
Flutter has a huge number of named arguments, FWIW.

**Comment by mkustermann** [comment] 2017-12-18 14:14
Preliminary findings:

First I've looked a bit into it by first profiling the AOT compiler, namely `gen_snapshot`, on the flutter gallery. The profile I got looks like this:

```
Samples: 65K of event 'cycles', Event count (approx.): 57963469777
  Overhead  Command          Shared Object        Symbol
+    8.16%  gen_snapshot  gen_snapshot     [.] dart::Simulator::InstructionDecode
+    4.35%  gen_snapshot  gen_snapshot     [.] dart::Simulator::DecodeType01
+    3.77%  gen_snapshot  gen_snapshot     [.] dart::Simulator::ConditionallyExecute
+    3.25%  gen_snapshot  gen_snapshot     [.] dart::Simulator::DecodeType2
+    2.22%  gen_snapshot  libpthread-2.19.so   [.] pthread_getspecific
+    2.06%  gen_snapshot  gen_snapshot     [.] dart::VMHandles::AllocateHandle
+    1.90%  gen_snapshot  gen_snapshot     [.] dart::Simulator::Execute
+    1.07%  gen_snapshot  gen_snapshot     [.] dart::FlowGraphTypePropagator::PropagateRecursive
+    0.97%  gen_snapshot  gen_snapshot     [.] dart::ZoneAllocated::operator new
+    0.91%  gen_snapshot  gen_snapshot     [.] dart::Simulator::GetShiftRm
+    0.76%  gen_snapshot  gen_snapshot     [.] dart::HashTable<dart::SymbolTraits, 0, 0>::FindKey<dart::ConcatString>
+    0.75%  gen_snapshot  gen_snapshot     [.] dart::ZoneAllocated::operator new
+    0.75%  gen_snapshot  gen_snapshot     [.] dart::BaseDirectChainedHashMap<dart::ArrayKeyValueTrait, dart::ValueObject, dart::Zone>::LookupValue
+    0.71%  gen_snapshot  gen_snapshot     [.] dart::OneByteString::CharAt
+    0.69%  gen_snapshot  gen_snapshot     [.] dart::FlowGraph::RenameRecursive
+    0.61%  gen_snapshot  gen_snapshot     [.] dart::FlowGraphTypePropagator::FlowGraphTypePropagator
+    0.56%  gen_snapshot  gen_snapshot     [.] dart::TokenStream::Iterator::Advance
+    0.55%  gen_snapshot  gen_snapshot     [.] dart::Simulator::HandleRList
+    0.55%  gen_snapshot  gen_snapshot     [.] dart::Class::LookupFunction
+    0.52%  gen_snapshot  gen_snapshot     [.] dart::Environment::DeepCopy
+    0.49%  gen_snapshot  gen_snapshot     [.] dart::FlowGraphAllocator::AllocateFreeRegister
```

As it seems, we spend currently **21.43 %** (`8.16 + 4.35 + 3.77 + 3.25 + 1.90`) running our ARM simulator. We suspect that almost all of this is due to the fact that the VM reads in the dart sources of the application by sending the service isolate loading requests which then runs dart code to read the sources from disc. Since the way the precompilation pipeline is setup, we run the service isolate in the same mode as the AOT compilation, namely in ARM mode, which is why the simulator is run.
  ==> By just mmap()ing the input source files instead of doing what we do now, should reduce this to almost 0 overhead.

Of course this (slow source loading) has been like this for a long time. So the regression introduced by https://github.com/dart-lang/sdk/commit/cf1de7d46cd88e204380e8f96a993439be56b24c came certainly from somewhere else.

To remove the simulator from the results, I've done a similar profile on x64 using the standalone precompiler on a large application. There was nothing which directly sticked out -- it appears that the slowdown is spread out across the compiler code, e.g. I've noticed the following changes in relative % of total time:

```
0.77 -> 0.86%  dart::ZoneAllocated::operator new
0.66 -> 0.71%  dart::FlowGraphTypePropagator::PropagateRecursive
0.60 -> 0.69%  dart::ZoneAllocated::operator new
0.55 -> 0.65%  dart::FlowGraphTypePropagator::VisitValue
0.52 -> 0.56%  dart::AbstractType::TypeTest
0.50 -> 0.53%  __strchrnul
0.36 -> 0.40%  dart::Instruction::HasUnmatchedInputRepresentations
0.30 -> 0.40%  dart::FlowGraph::ComputeDominators
```

The increase in Intermediate Language (which replaced the 1000+ lines of handwritten assembly) causes more work for IR building, SSA construction & optimization. Though the output of the AOT compiler should have equal or better code.

**Comment by Hixie** [comment] 2017-12-18 20:00
Can we revert the patch in the meantime, so that we will more easily be able to catch additional regressions if they come in before we've resolved this?

**Comment by a-siva** [comment] 2017-12-18 20:45
@mkustermann if we don't have a fix for this before the next dart roll into flutter can we revert the patch as suggested by @Hixie so that the next dart roll will turn these back to green.

**Comment by mraleph** [comment] 2017-12-18 21:48
I am very strongly against reverting this patch: we were aware of the compilation time hit and we opted to take it for the sake of clear architecture, maintainability and ability to make a forward progress.

We already have changes in pipeline which strongly depend on this change (e.g. Dart 2 strong mode checks). 

The summary here is that:

* we want/need this change to happen;
* it will cost compilation time

I will look at this tomorrow to see if we can reduce the impact, but I don't think we can get it down to zero.

**Comment by Hixie** [comment] 2017-12-18 22:19
Flutter didn't opt to take this performance hit. We consider compilation performance to already be slower than it should be. I understand that this is a prerequisite for Dart 2.0 work. From Flutter's perspective, however, compilation performance is a higher priority.

**Comment by Hixie** [comment] 2017-12-18 22:33
Actually, I apologise profusely, I hadn't realised that this only affected AOT compilation performance. We do not consider performance of AOT builds a priority, since those only happen occasionally. It's debug compilation performance (e.g. JIT) that matters.

Please feel free to close this bug if the performance hit was indeed intentional.

**Comment by Hixie** [comment] 2017-12-18 22:37
(I filed https://github.com/dart-lang/sdk/issues/31684 for the debug-mode issue that I had confused with this one.)

**Comment by a-siva** [comment] 2018-01-03 05:20
while debug build times are more critical, I still believe AOT compile times can also be an issue when profiling apps. I would keep tabs on the aot compile times and make sure they don't regress by a huge
factor.

Having said that @mkustermann feel free to close the bug if you think the current times are inline with
your expectations.

**Comment by mkustermann** [comment] 2018-01-09 10:20
There have been a few changes made which increase the compilation performance. The flutter dashboard shows that our compilation is back below the green threshold (and I am not aware of any modifications to the threshold value).

Closing this issue therfore.

**Closed by mkustermann** 2018-01-09 10:20 UTC
Labels: area-vm
