### ISSUE TITLE
dummy_compiler_test crashes in host-checked mode

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/sdk#22809] opened 2015-03-12 15:20 UTC
python tools/test.py -mrelease --host-checked -cdart2js -rd8 -t960 utils/dummy_compiler_test

stacktrace:

The compiler crashed: 'file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/types/union_type_mask.dart': Failed assertion: line 234 pos 16: 'contained || !union.slowContainsCheck(disjointMask, classWorld)' is not true.
#­0      \_AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#­1      UnionTypeMask.isInMask.&lt;anonymous closure&gt; (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/types/union_type_mask.dart:234:16)
#­2      Object&amp;ListMixin.every (dart:collection/list.dart:104)
#­3      UnionTypeMask.isInMask (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/types/union_type_mask.dart:232:33)
#­4      SsaInstructionSimplifier.removeIfCheckAlwaysSucceeds (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:689:30)
#­5      SsaInstructionSimplifier.visitTypeKnown (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:681:39)
#­6      HTypeKnown.accept (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/nodes.dart:2647:53)
#­7      SsaInstructionSimplifier.visitBasicBlock (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:146:52)
#­8      HGraphVisitor.visitDominatorTree.visitBasicBlockAndSuccessors (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/nodes.dart:86:22)
#­9      HGraphVisitor.visitDominatorTree.visitBasicBlockAndSuccessors (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/nodes.dart:89:37)
#­10     HGraphVisitor.visitDominatorTree.visitBasicBlockAndSuccessors (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/nodes.dart:89:37)
#­11     HGraphVisitor.visitDominatorTree (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/nodes.dart:93:33)
#­12     SsaInstructionSimplifier.visitGraph (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:139:23)
#­13     SsaOptimizerTask.runPhase (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:28:21)
#­14     SsaOptimizerTask.runPhases (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:23:15)
#­15     SsaOptimizerTask.optimize.&lt;anonymous closure&gt; (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:76:16)
#­16     CompilerTask.measure (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:2143:37)
#­17     SsaOptimizerTask.optimize (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/optimize.dart:37:12)
#­18     SsaFunctionCompiler.compile (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/ssa/builder.dart:21:23)
#­19     JavaScriptBackend.codegen (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/js_backend/backend.dart:1367:54)
#­20     Compiler.codegen (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:1803:20)
#­21     CodegenWorkItem.run (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:203:21)
#­22     Compiler.processQueue.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:1700:54)
#­23     Compiler.withCurrentElement (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:875:15)
#­24     Compiler.processQueue.&lt;anonymous closure&gt; (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:1700:25)
#­25     QueueFilter.processWorkItem (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/enqueue.dart:900:6)
#­26     Enqueuer.forEach (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/enqueue.dart:604:31)
#­27     Compiler.processQueue (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:1699:18)
#­28     Compiler.compileLoadedLibraries (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:1637:17)
#­29     Compiler.runCompiler.&lt;anonymous closure&gt; (file:///usr/local/google/home/sigurdm/projects/next-repo/dart/pkg/compiler/lib/src/compiler.dart:1470:29)
#­30     \_RootZone.runUnary (dart:async/zone.dart:1155)
#­31     \_Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#­32     \_Future._propagateToListeners (dart:async/future_impl.dart:567)
#­33     \_Future._completeWithValue (dart:async/future_impl.dart:358)
#­34     \_Future._asyncComplete.&lt;anonymous closure&gt; (dart:async/future_impl.dart:412)
#­35     \_asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#­36     \_asyncRunCallback (dart:async/schedule_microtask.dart:48)
#­37     \_runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#­38     \_RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)

**Comment by sigmundch** [comment] 2015-09-18 21:12
It seems that the test is now working correctly, or at least I was not able to reproduce the error locally. I'm closing this issue tentatively, but please let me know if this was a mistake.

**Closed by sigmundch** 2015-09-18 21:12 UTC
Labels: Area-Dart2JS, Priority-Unassigned, Triaged, Type-Defect

**Comment by hterkelsen** [comment] 2015-09-18 21:23
I can confirm that `./sdk/bin/dart2js_developer -v --categories=all --package-root=out/ReleaseIA32/packages/ tests/utils/dummy_compiler_test.dart` used to crash for me with the same AssertionError and now it doesn't.

**Comment by whesse** [comment] 2016-03-03 15:52
Removing the crash notation from the status file.
