### ISSUE TITLE
analyzer doesn't warn about deprecated fields

### ISSUE THREAD

**Issue by skybrian** [dart-lang/sdk#25295] opened 2015-12-18 22:55 UTC
To reproduce, paste into DartPad:

class Foo {
  @deprecated
  String someField;
  
  @deprecated
  someMethod() {}
}

main() {
  Foo f = new Foo();
  print(f.someField);
  f.someMethod();
}

I expected two deprecation warnings (for someField and someMethod) but only got one, for someMethod.

**Comment by bwilkerson** [comment] 2016-03-13 22:56
Duplicate of #22963

**Closed by bwilkerson** 2016-03-13 22:56 UTC
Labels: area-analyzer, P2 medium, Type: bug
