### ISSUE TITLE
Syntactic (only) support for generic methods in the analyzer

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#25868] opened 2016-02-26 12:59 UTC
The analyzer already supports (most or all) of the generic method syntax, but it should have a flag `--generic-method-syntax` flag that doesn't emit warnings.

**Comment by eernstg** [comment] 2016-11-02 15:49
Closing this one as a duplicate of #27641 even though that one is newer: It contains additional elements.

**Closed by eernstg** 2016-11-02 15:49 UTC
Labels: area-analyzer, P2 medium, Type: enhancement
