### ISSUE TITLE
High cpu usage when edit dart code using macvim on mac os. 

### ISSUE THREAD

**Issue by fftyjw** [dart-lang/sdk#39967] opened 2020-01-02 12:39 UTC
* Dart SDK Version: 2.7.0-dev.2.1
* System: MacOSX
I profiled the dart process with instruments. It looks like there is an endless loop.
![image](https://user-images.githubusercontent.com/14770930/71667381-d6803d80-2d9f-11ea-89d2-e1938489551f.png)
![image](https://user-images.githubusercontent.com/14770930/71667400-e861e080-2d9f-11ea-8f5e-aa2465c3c123.png)

**Comment by DanTup** [comment] 2020-01-02 14:01
I presume this process is the analysis server VM and not your own application? Can you reliably reproduce it? Does the server crash when this happens or just sit busy?

It might be possible to pass `--observe --dump-service-info=service.json` in the VM arguments when starting the server (before the snapshot path) and then get the Observatory URI from the generated `service.json` file to open in your browser and examine the call stack with any Dart function names in-tact.

**Comment by fftyjw** [comment] 2020-01-03 07:07
Yes, the process is "dart", not my own application. It's not happening every time, but very frequently when I use vim(with coc-flutter plugin. github.com/iamcco/coc-flutter) to edit dart code. When it happen, the dart process did not crash, but use at least 80 percent of the cpu.  Unfortunately, it's "coc-flutter" started the dart process, and I do not know how to pass the arguments you said to dart using "coc-flutter", so I can't provide the service.json file.

**Comment by DanTup** [comment] 2020-01-03 08:51
Are you able to (temporarily) modify the source of coc-flutter on your local machine? If so, I think you could add the arguments here:

https://github.com/iamcco/coc-flutter/blob/74a50475e37a5178aa01f55f16bb7603279105fa/src/server/lsp/index.ts#L46

The instrumentation file might be useful too:

```
 args: ['--observe', '--dump-service-info=/some/path/service.json', flutterSDK.analyzerSnapshotPath, '--lsp', '--instrumentation-log-file=/some/path/instrumentation.txt'],
```

**Comment by fftyjw** [comment] 2020-01-03 09:38
I tried, but it's not working.  After I changed the "coc-flutter" source code, vim can't start "dart" process.

**Comment by DanTup** [comment] 2020-01-03 10:06
Sorry, the flag is named `--write-service-info`. However I discovered that it doesn't suppress the old VM service banner, which means even with the correct flag it will break (due to writing non-LSP output). I've opened https://github.com/dart-lang/sdk/issues/39975 for that.

It might be useful to still add the last flag (`'--instrumentation-log-file=/some/path/instrumentation.txt'`) as that might give some indication of what the server is analyzing (or request it's processing) when this happens.

@bwilkerson @bkonyi do you know if there's a way to get a more useful call stack (without the VM service) to see what's happening here?

**Comment by fftyjw** [comment] 2020-01-03 11:12
I add the last flag, and got the instrumentation file. It looks like "dart" process was trying to analyze all dart files on my disk. 
![image](https://user-images.githubusercontent.com/14770930/71720446-bc586500-2e5c-11ea-9b80-3b2f3658cdd6.png)

**Comment by DanTup** [comment] 2020-01-03 11:16
@fftyjw can you share the first few lines of the log, specifically those containing "initialize" and "initialized"?

**Comment by fftyjw** [comment] 2020-01-03 11:17
initialize1578048966588:Ver:1549516933475134752561:unknown:unknown:1.27.4:2.8.0-edge.a4d799c402efc36327cad2f42186bb48ea9cf18a
1578048966681:Req:{"jsonrpc"::"2.0","id"::0,"method"::"initialize","params"::{"processId"::6039,"rootPath"::"/Users/dh/code/dart/test_f","rootUri"::"file::///Users/dh/code/dart/test_f","capabilities"::{"workspace"::{"applyEdit"::true,"workspaceEdit"::{"documentChanges"::true,"resourceOperations"::["create","rename","delete"],"failureHandling"::"textOnlyTransactional"},"didChangeConfiguration"::{"dynamicRegistration"::true},"didChangeWatchedFiles"::{"dynamicRegistration"::true},"symbol"::{"dynamicRegistration"::true,"symbolKind"::{"valueSet"::[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand"::{"dynamicRegistration"::true},"configuration"::true,"workspaceFolders"::true},"textDocument"::{"publishDiagnostics"::{"relatedInformation"::true},"synchronization"::{"dynamicRegistration"::true,"willSave"::true,"willSaveWaitUntil"::true,"didSave"::true},"completion"::{"dynamicRegistration"::true,"contextSupport"::true,"completionItem"::{"snippetSupport"::true,"commitCharactersSupport"::true,"documentationFormat"::["markdown","plaintext"],"deprecatedSupport"::true,"preselectSupport"::true},"completionItemKind"::{"valueSet"::[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover"::{"dynamicRegistration"::true,"contentFormat"::["markdown","plaintext"]},"signatureHelp"::{"dynamicRegistration"::true,"signatureInformation"::{"documentationFormat"::["markdown","plaintext"],"parameterInformation"::{"labelOffsetSupport"::true}}},"definition"::{"dynamicRegistration"::true},"references"::{"dynamicRegistration"::true},"documentHighlight"::{"dynamicRegistration"::true},"documentSymbol"::{"dynamicRegistration"::true,"symbolKind"::{"valueSet"::[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"codeAction"::{"dynamicRegistration"::true,"codeActionLiteralSupport"::{"codeActionKind"::{"valueSet"::["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens"::{"dynamicRegistration"::true},"formatting"::{"dynamicRegistration"::true},"rangeFormatting"::{"dynamicRegistration"::true},"onTypeFormatting"::{"dynamicRegistration"::true},"rename"::{"dynamicRegistration"::true,"prepareSupport"::true},"documentLink"::{"dynamicRegistration"::true},"typeDefinition"::{"dynamicRegistration"::true},"implementation"::{"dynamicRegistration"::true},"declaration"::{"dynamicRegistration"::true},"colorProvider"::{"dynamicRegistration"::true},"foldingRange"::{"dynamicRegistration"::true,"rangeLimit"::5000,"lineFoldingOnly"::true}}},"initializationOptions"::{"onlyAnalyzeProjectsWithOpenFiles"::false,"suggestFromUnimportedLibraries"::true,"closingLabels"::true},"trace"::"off","workspaceFolders"::[{"uri"::"file::///Users/dh/code/dart/test_f","name"::"test_f"}]}}
1578048966741:Res:{"id"::0,"jsonrpc"::"2.0","result"::{"capabilities"::{"textDocumentSync"::{"openClose"::false,"change"::0,"willSave"::false,"willSaveWaitUntil"::false},"hoverProvider"::true,"completionProvider"::{"resolveProvider"::true,"triggerCharacters"::[".","=","(","$"]},"signatureHelpProvider"::{"triggerCharacters"::[]},"definitionProvider"::true,"implementationProvider"::true,"referencesProvider"::true,"documentHighlightProvider"::true,"documentSymbolProvider"::true,"workspaceSymbolProvider"::true,"codeActionProvider"::{"codeActionKinds"::["source","source.organizeImports","source.sortMembers","quickfix"]},"documentFormattingProvider"::true,"documentRangeFormattingProvider"::false,"documentOnTypeFormattingProvider"::{"firstTriggerCharacter"::"}","moreTriggerCharacter"::[";"]},"renameProvider"::{"prepareProvider"::true},"foldingRangeProvider"::true,"executeCommandProvider"::{"commands"::["edit.sortMembers","edit.organizeImports","edit.sendWorkspaceEdit","refactor.perform"]},"workspace"::{"workspaceFolders"::{"supported"::true,"changeNotifications"::true}}}}}
1578048966746:Req:{"jsonrpc"::"2.0","method"::"initialized","params"::{}}
1578048966763:Res:{"id"::1,"method"::"client/registerCapability","params"::{"registrations"::[{"id"::"1","method"::"textDocument/didOpen","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"},{"language"::"yaml","scheme"::"file","pattern"::"**/pubspec.yaml"},{"language"::"yaml","scheme"::"file","pattern"::"**/analysis_options.yaml"}]}},{"id"::"2","method"::"textDocument/didClose","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"},{"language"::"yaml","scheme"::"file","pattern"::"**/pubspec.yaml"},{"language"::"yaml","scheme"::"file","pattern"::"**/analysis_options.yaml"}]}},{"id"::"3","method"::"textDocument/didChange","registerOptions"::{"syncKind"::2,"documentSelector"::[{"language"::"dart","scheme"::"file"},{"language"::"yaml","scheme"::"file","pattern"::"**/pubspec.yaml"},{"language"::"yaml","scheme"::"file","pattern"::"**/analysis_options.yaml"}]}},{"id"::"4","method"::"textDocument/completion","registerOptions"::{"triggerCharacters"::[".","=","(","$"],"resolveProvider"::true,"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"5","method"::"textDocument/hover","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"6","method"::"textDocument/signatureHelp","registerOptions"::{"triggerCharacters"::[],"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"7","method"::"textDocument/references","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"8","method"::"textDocument/documentHighlight","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"9","method"::"textDocument/documentSymbol","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"10","method"::"textDocument/formatting","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"11","method"::"textDocument/onTypeFormatting","registerOptions"::{"firstTriggerCharacter"::"}","moreTriggerCharacter"::[";"],"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"12","method"::"textDocument/definition","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"13","method"::"textDocument/implementation","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"14","method"::"textDocument/codeAction","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}],"codeActionKinds"::["source","source.organizeImports","source.sortMembers","quickfix"]}},{"id"::"15","method"::"textDocument/rename","registerOptions"::{"prepareProvider"::true,"documentSelector"::[{"language"::"dart","scheme"::"file"}]}},{"id"::"16","method"::"textDocument/foldingRange","registerOptions"::{"documentSelector"::[{"language"::"dart","scheme"::"file"}]}}]},"jsonrpc"::"2.0"}
1578048967422:Res:{"method"::"$/analyzerStatus","params"::{"isAnalyzing"::true},"jsonrpc"::"2.0"}
1578048967433:Req:{"jsonrpc"::"2.0","method"::"textDocument/didOpen","params"::{"textDocument"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/inheritedWidget/shareData.dart","languageId"::"dart","version"::1,"text"::"import 'package::flutter/material.dart';\n\nclass ShareDataWidget extends InheritedWidget {\n  ShareDataWidget({\n    @required this.data,\n    Widget child\n  }) ::super(child:: child);\n\n  final int data; //需要在子树中共享的数据，保存点击次数\n\n  //定义一个便捷方法，方便子树中的widget获取共享数据  \n  static ShareDataWidget of(BuildContext context) {\n    return context.inheritFromWidgetOfExactType(ShareDataWidget);\n  }\n\n  //该回调决定当data发生变化时，是否通知子树中依赖data的Widget  \n  @override\n  bool updateShouldNotify(ShareDataWidget old) {\n    //如果返回true，则子树中依赖(build函数中有调用)本widget\n    //的子widget的`state.didChangeDependencies`会被调用\n    print('should ntf ${old.data}, ${data}');\n    return old.data != data;\n  }\n}\n"}}}
1578048967443:Req:{"jsonrpc"::"2.0","id"::1,"result"::null}
1578048968794:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/inheritedWidget/shareData.dart","diagnostics"::[{"range"::{"start"::{"line"::20,"character"::35},"end"::{"line"::20,"character"::42}},"severity"::3,"code"::"unnecessary_brace_in_string_interps","source"::"dart","message"::"Avoid using braces in interpolation when not needed."},{"range"::{"start"::{"line"::12,"character"::19},"end"::{"line"::12,"character"::47}},"severity"::3,"code"::"deprecated_member_use","source"::"dart","message"::"'inheritFromWidgetOfExactType' is deprecated and shouldn't be used. Use dependOnInheritedWidgetOfExactType instead. This feature was deprecated after v1.12.1..\nTry replacing the use of the deprecated member with the replacement."}]},"jsonrpc"::"2.0"}
1578048968795:Res:{"method"::"dart/textDocument/publishClosingLabels","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/inheritedWidget/shareData.dart","labels"::[]},"jsonrpc"::"2.0"}
1578048969210:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/test/widget_test.dart","diagnostics"::[{"range"::{"start"::{"line"::10,"character"::7},"end"::{"line"::10,"character"::33}},"severity"::3,"code"::"unused_import","source"::"dart","message"::"Unused import:: 'package::test_f/main.dart'.\nTry removing the import directive."},{"range"::{"start"::{"line"::15,"character"::28},"end"::{"line"::15,"character"::33}},"severity"::1,"code"::"undefined_function","source"::"dart","message"::"The function 'MyApp' isn't defined.\nTry importing the library that defines 'MyApp', correcting the name to the name of an existing function, or defining a function named 'MyApp'."}]},"jsonrpc"::"2.0"}
1578048969352:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/inheritedWidget/home.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1578048969354:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/inheritedWidget/test.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1578048969355:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/provider/cartModel.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1578048969356:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/provider/home.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1578048969357:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/provider/provider.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1578048969360:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/provider/notifierProvider.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1578048969360:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/dh/code/dart/test_f/lib/main.dart","diagnostics"::[]},"jsonrpc"::"2.0"}

**Comment by DanTup** [comment] 2020-01-03 11:20
Actually, your screenshot looks corect - your editor sent a request opening "dh/02-code" and then that was analyzed.

![Screenshot 2020-01-03 at 11 17 52](https://user-images.githubusercontent.com/1078012/71720771-bcd00c00-2e1a-11ea-8b2e-e1ad285a94fc.png)

Are you seeing analysis in files/folders that you did *not* open?

You may also be interested in the [flutter.lsp.initialization.onlyAnalyzeProjectsWithOpenFiles setting](https://github.com/iamcco/coc-flutter#settings) which will only analyze projects that have files open specifically, rather than the whole "workspace".

**Comment by fftyjw** [comment] 2020-01-03 11:21
Yes, these files I did not open.
![image](https://user-images.githubusercontent.com/14770930/71720888-28879880-2e5e-11ea-885a-3700acc014bb.png)

**Comment by DanTup** [comment] 2020-01-03 11:23
@fftyjw although you didn't open those files, your editor has sent a request to the server to add the folder "/Users/dh/02-code/flutter" to the workspace. This results in that whole folder being analyzed.

I don't know what caused the editor to send this, it may be a bug in coc-flutter. Otherwise, the setting above may help (this narrows the folders that will be analyzed to only the projects with explicit files open and ignores the workspace sent by the client).

**Comment by fftyjw** [comment] 2020-01-03 11:36
I think the editor sent the didChangeWorkspaceFolders  request, because I run the jump to definition command of "coc-flutter" which will auto open the source file in flutter project. It would be wonderful if dart can make some cache of files that have been analyzed, and do not reanalyze those files on next request, especially for commonly used sdks like flutter.

**Comment by DanTup** [comment] 2020-01-03 11:47
> I think the editor sent the didChangeWorkspaceFolders request, because I run the jump to definition command of "coc-flutter" which will auto open the source file in flutter project

That makes sense, but in this case it seems to be adding the entire Flutter SDK folder, but the file you jumped to is in `flutter/packages/flutter`. I think if it was to add only that folder, this wouldn't happen (since a lot of time is being spent analyzing things like example projects). This feels like a bug in coc-flutter in my opinion.

That said, the setting mentioned above would probably also resolve this, since we would ignore the workspace root and then only analyze the `flutter` package that you opened the file in.

> It would be wonderful if dart can make some cache of files that have been analyzed, and do not reanalyze those files on next request, especially for commonly used sdks like flutter.

@bwilkerson or @scheglov may be able to confirm how this works, but I think there is already some caching and the SDKs may also ship with (summary?) files to reduce work for SDK libraries (in your log it looks like all of the example projects are being analysed though which may no be included).

My suggestion is to try the [flutter.lsp.initialization.onlyAnalyzeProjectsWithOpenFiles setting](https://github.com/iamcco/coc-flutter#settings) and/or file an issue with coc-flutter to find out why the whole Flutter SDK project is being added as a workspace folder when you jumped into a file in flutter/packages/flutter which is its own package [with a pubspec](https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml).

**Comment by fftyjw** [comment] 2020-01-03 11:56
@DanTup, thanks, I modify the  "flutter.lsp.initialization.onlyAnalyzeProjectsWithOpenFiles" setting. And now it got much better, it's only analyze files in  flutter/packages/flutter now.

**Comment by DanTup** [comment] 2020-01-03 11:59
Glad to hear - I'll close this since I don't think there's anything to do here in the SDK. I do think it's worth opening an issue with coc-flutter with some info on this and questioning why it adds the whole SDK instead of just that folder (it feels like a bug and may affect many other users).

**Closed by DanTup** 2020-01-03 11:59 UTC
Labels: area-analyzer

**Comment by fftyjw** [comment] 2020-01-03 12:03
Ok, I will open an new issue with coc-flutter.
