### ISSUE TITLE
Type inference crashes on certain incorrect input programs

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/sdk#35339] opened 2018-12-06 12:24 UTC
The following two programs make CFE crash.  The stack trace shows that the place where the crash happens is type inference.

Program 1:
```dart
main() {
  for (super.a in [a]) {}
}
```

Top of stack trace for Program 1:
```
Unhandled exception:                                                                                                 
Crash when compiling file:///tmp/bar.dart,
at character offset 5:                                                                                                                 
'package:front_end/src/fasta/type_inference/type_inferrer.dart': Failed assertion: line 746 pos 12: 'receiverType != null && isKnown(receiverType)': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)                                 
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      TypeInferrerImpl.findInterfaceMember (package:front_end/src/fasta/type_inference/type_inferrer.dart:746:12)
#3      TypeInferrerImpl.findPropertySetMember (package:front_end/src/fasta/type_inference/type_inferrer.dart:890:29)
#4      InferenceVistor.handleForInStatementWithoutVariable (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:331:20)
#5      InferenceVistor.visitForInStatement (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:374:7)
#6      ForInStatement.accept1 (package:kernel/ast.dart:3956:42)                                 
#7      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1564:24)                 
#8      InferenceVistor.visitBlockJudgment (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:76:16)
#9      BlockJudgment.acceptInference (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:188:20)
#10     ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1562:24)                     
#11     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1189:5)
#12     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:734:20)                    
#13     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:795:14)
#14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:829:7)                         
#15     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:303:5)
#16     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2303:14)               
#17     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2204:14)
#18     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#19     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#20     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:254:14)
<asynchronous suspension>
#21     Loader.buildBodies (package:front_end/src/fasta/loader.dart:182:15)
<asynchronous suspension>
#22     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:309:20)
<asynchronous suspension>
#23     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>
#24     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:307:12)
```

The VM seems to suppress the crash:
```
$ out/ReleaseX64/dart /tmp/bar.dart
file:///tmp/bar.dart:2:8: Error: Expected identifier, but got 'super'.
  for (super.a in [a]) {}
       ^^^^^
file:///tmp/bar.dart:2:8: Error: Expected an identifier, but got 'super'.
  for (super.a in [a]) {}
       ^^^^^
file:///tmp/bar.dart:2:20: Error: Getter not found: 'a'.
  for (super.a in [a]) {}
                   ^
file:///tmp/bar.dart:2:14: Error: The setter 'a' isn't defined for the class 'null-type'.
Try correcting the name to the name of an existing setter, or defining a setter or field named 'a'.
  for (super.a in [a]) {}
```

Program 2:
```dart
typedef A = Function();

main() {
  for (A.unresolved in <num>[]) {}
}
```

Top of stack trace for Program 2:
```
Unhandled exception:                                                                                                 
Crash when compiling file:///tmp/bar2.dart,
at character offset 30:                                                                                                                
'package:front_end/src/fasta/type_inference/type_inferrer.dart': Failed assertion: line 746 pos 12: 'receiverType != null && isKnown(receiverType)': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)                                 
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      TypeInferrerImpl.findInterfaceMember (package:front_end/src/fasta/type_inference/type_inferrer.dart:746:12)
#3      TypeInferrerImpl.findPropertySetMember (package:front_end/src/fasta/type_inference/type_inferrer.dart:890:29)
#4      InferenceVistor.handleForInStatementWithoutVariable (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:331:20)
#5      InferenceVistor.visitForInStatement (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:374:7)
#6      ForInStatement.accept1 (package:kernel/ast.dart:3956:42)                                 
#7      ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1564:24)                 
#8      InferenceVistor.visitBlockJudgment (file:///usr/local/google/home/dmitryas/dart/sdk/pkg/front_end/lib/src/fasta/kernel/inference_visitor.dart:76:16)
#9      BlockJudgment.acceptInference (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:188:20)
#10     ShadowTypeInferrer.inferStatement (package:front_end/src/fasta/kernel/kernel_shadow_ast.dart:1562:24)                     
#11     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1189:5)
#12     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:734:20)                    
#13     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:795:14)
#14     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:829:7)                         
#15     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:303:5)
#16     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2303:14)               
#17     Parser.parseTopLevelMemberImpl (package:front_end/src/fasta/parser/parser.dart:2204:14)
#18     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:493:14)
#19     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:348:15)
#20     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:254:14)
```

The VM seems to suppress the crash:
```
$ out/ReleaseX64/dart /tmp/bar2.dart
file:///tmp/bar2.dart:4:9: Error: Unexpected token '.'.
  for (A.unresolved in <num>[]) {}
        ^
file:///tmp/bar2.dart:4:10: Error: The setter 'unresolved' isn't defined for the class 'null-type'.
Try correcting the name to the name of an existing setter, or defining a setter or field named 'unresolved'.
  for (A.unresolved in <num>[]) {}
         ^^^^^^^^^^
```

**Comment by peter-ahe-google** [comment] 2018-12-06 12:30
This is a duplicate of #35337.

**Closed by peter-ahe-google** 2018-12-06 12:30 UTC
Labels: area-front-end, crash
