### ISSUE TITLE
Process.run wrongfully returns stdout as stderr

### ISSUE THREAD

**Issue by frencojobs** [dart-lang/sdk#42168] opened 2020-06-03 10:49 UTC
# Environment

- `dart version`: 2.8.1 (stable)
- OS version: Windows 10

# Problem

`Process.run` is wrongfully returning `stdout` as `stderr`. This could be an issue of dart cli or issue of `dart:io`.

# Steps to Reproduce
The code
```dart
var pr = await Process.run('echo', ['ok'], runInShell: true);
print('exit-code: ${pr.exitCode}');
print('stdout: ${pr.stdout}');
print('stderr: ${pr.stderr}');
```
yields the output, which is expected.
```bash
exit-code: 0
stdout: ok

stderr:
```
But running `dart --version` yields an unexpected result.
```dart
var pr = await Process.run('dart', ['--version'], runInShell: true);
```
```bash
exit-code: 0
stdout:
stderr: Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "windows_x64"

```
I'm not sure if this is a problem of dart cli or of `dart:io`. But that definitely is a problem.

**Comment by sortie** [comment] 2020-06-03 12:41
This is not a problem in dart:io. `dart --version` writes the information to stderr and that's why you see it in stderr when you use `Process.run`.

Closing this issue as working as intended since there's no dart:io issue. As for whether `dart --version` should write to stderr or stdout, that is debatable. I suppose it's more useful to write it to stdout although things like `foo --help` writing to stderr isn't unusual.

We can open another issue to debate whether `dart --version` should write to stdout instead of stderr if you'd like?

**Closed by sortie** 2020-06-03 12:41 UTC
Labels: area-library, closed-as-intended, library-io
