### ISSUE TITLE
dart analyzer error

### ISSUE THREAD

**Issue by Jimmysonblack** [dart-lang/sdk#37804] opened 2019-08-11 10:18 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-192.5728.98`
- `2.4.1`
- `IU-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.1, server version 1.27.1, error: Captured exception
NoSuchMethodError: The setter 'previous=' was called on null.
Receiver: null
Tried calling: previous=Instance of 'SimpleToken'
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      SimpleToken.setNext (package:front_end/src/scanner/token.dart:599:11)
#2      scannerRecovery (package:front_end/src/fasta/scanner/recover.dart:205:16)
#3      _tokenizeAndRecover (package:front_end/src/fasta/scanner.dart:103:14)
#4      scanString (package:front_end/src/fasta/scanner.dart:95:10)
#5      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:146:34)
#6      _File._parse (package:analyzer/src/services/available_declarations.dart:1652:25)
#7      _File.refresh (package:analyzer/src/services/available_declarations.dart:1074:30)
#8      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:601:14)
#9      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:514:18)
#10     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:277:13)
<asynchronous suspension>
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2112:35)
<asynchronous suspension>
#12     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#13     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#14     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#15     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#16     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#22     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#23     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#25     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#26     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#34     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#35     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#36     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#37     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#38     main (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\Jimmyson\AppData\Local\Temp\report7.txt.

**Comment by srawlins** [comment] 2019-08-11 21:41
Looks related to https://github.com/dart-lang/sdk/issues/37096, but not necessarily a duplicate

**Comment by srawlins** [comment] 2019-09-19 15:39
Recently reported at https://github.com/dart-lang/sdk/issues/38447; user reports that the problem may be fixed by upgrading Flutter, so that the Dart version is at 2.5.0. Please re-open if you encounter this crash on Dart 2.5.0 or later.

**Comment by srawlins** [comment] 2019-09-19 15:39
Duplicate of https://github.com/dart-lang/sdk/issues/38447

**Closed** 2019-09-19 17:26 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
