### ISSUE TITLE
pkg/meta: Add @experimental annotation

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#29213] opened 2017-03-31 15:58 UTC
We're considering a range of automated tests/checks when the public API of a pub package changes in a statically detectable way. For example, you add a function, remove a function, add an optional functional parameter, etc.

However, there are sometimes APIs that you'd like users to try, but are not to be relied on as part of sem-ver. For example, you might introduce a new named constructor for users to try in a release:

```dart
abstract class StableThing {
  factory StableThing() => ...

  @experimental
  factory StableThing.tryMe() => ...
}
```

Introducing the `@experimental` annotation:

> Used to annotate a method, optional positional parameter, optional named parameter, class, or
> field x. Indicates that the API may be removed or changed at any-time without updating the
> pubspec version field, despite the fact that it would be a breaking change.

Initially this could do nothing but be a convention, but it could be highlighted in `dartdoc`, could also be part of version checking or `pub`, and the `analyzer` could help teams lint and avoid `@experimental` APIs if they wish.

**Comment by bwilkerson** [comment] 2017-03-31 16:47
Duplicate of #27124.

**Closed by bwilkerson** 2017-03-31 16:47 UTC
