### ISSUE TITLE
Fasta does not handle generic function types correctly

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30837] opened 2017-09-20 21:54 UTC
```dart
typedef Foo<S> = S Function<T>(T x);

main(Object p) {
  (p as Foo)<int>(3);
  if (p is Foo) {
    p<int>(3);
  }
  (p as Foo<String>)<int>(3);
  if (p is Foo<String>) {
    p<int>(3);
  }
}
```

Similar code works find in both Analyze and VM.

```dart
typedef Foo<S> = S Function<T>(T x);

foo(Object p) {
  var result = (p as Foo)<int>(3);
  print(result);
}

double bar(int p) {
  return p * 1.5;
}

main() {
  foo(bar);
}
```

But Fasta produces invalid Kernel.
```kernel
library;
import self as self;

static method #main() → dynamic {
  throw "file:///test.dart:4:17: Error: Expected ';' before this.\n  (p as Foo)<int>(3);\n                ^";
}
```

**Comment by peter-ahe-google** [comment] 2017-09-21 14:17
Duplicate of #30208.

**Closed** 2017-09-21 14:18 UTC
Labels: area-front-end, Resolution: duplicate
