### ISSUE TITLE
Crash while running dart migrate on flutter_test

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#43541] opened 2020-09-24 19:14 UTC
When running `dart migrate` on the `flutter_test` package I encountered the following error:

```
NoSuchMethodError: The getter 'typeProvider' was called on null.
Receiver: null
Tried calling: typeProvider

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Member._toLegacyType (package:analyzer/src/dart/element/member.dart:602:46)
#2      VariableMember.type (package:analyzer/src/dart/element/member.dart:1030:13)
#3      PropertyElementResolver._computeIndexContextType (package:analyzer/src/dart/resolver/property_element_resolver.dart:235:28)
#4      PropertyElementResolver._toIndexResult (package:analyzer/src/dart/resolver/property_element_resolver.dart:624:25)
#5      PropertyElementResolver.resolveIndexExpression (package:analyzer/src/dart/resolver/property_element_resolver.dart:121:12)
#6      ElementResolver.visitIndexExpression (package:analyzer/src/generated/element_resolver.dart:383:27)
#7      IndexExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5925:49)
#8      ResolverVisitor.visitIndexExpression (package:analyzer/src/generated/resolver.dart:1475:10)
#9      IndexExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5925:49)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7310:18)
#11     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#12     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3360:51)
#13     ResolverVisitor.visitNamedExpression (package:analyzer/src/generated/resolver.dart:1604:11)
#14     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7305:49)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#16     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:360:16)
#17     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#18     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3122:45)
#19     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:785:11)
#20     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:356:49)
#21     InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:333:18)
#22     InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:373:7)
#23     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:351:7)
#24     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
#25     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:788:24)
#26     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:492:16)
#27     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#28     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:428:31)
#29     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#30     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1566:10)
#31     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#32     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#33     ListLiteralImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6689:15)
#34     TypedLiteralResolver.resolveListLiteral (package:analyzer/src/dart/resolver/typed_literal_resolver.dart:97:10)
#35     ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:1511:27)
#36     ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6684:49)
#37     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#38     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:360:16)
#39     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#40     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3122:45)
#41     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:785:11)
#42     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:356:49)
#43     InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:333:18)
#44     InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:373:7)
#45     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:351:7)
#46     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
#47     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:788:24)
#48     MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:492:16)
#49     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#50     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:428:31)
#51     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#52     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1566:10)
#53     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#54     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#55     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:360:16)
#56     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#57     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3122:45)
#58     ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:785:11)
#59     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:356:49)
#60     InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:333:18)
#61     InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:373:7)
#62     InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:351:7)
#63     InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
#64     MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:788:24)
#65     MethodInvocationResolver._resolveReceiverType (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:649:14)
#66     MethodInvocationResolver._resolveReceiverInterfaceType (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:417:5)
#67     MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:147:7)
#68     ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:428:31)
#69     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#70     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1566:10)
#71     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#72     AwaitExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:897:18)
#73     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#74     UnifyingAstVisitor.visitAwaitExpression (package:analyzer/dart/ast/visitor.dart:3137:51)
#75     ResolverVisitor.visitAwaitExpression (package:analyzer/src/generated/resolver.dart:834:11)
#76     AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:893:49)
#77     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3661:18)
#78     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#79     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3229:59)
#80     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3657:49)
#81     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#82     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1080:17)
#83     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#84     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#85     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2304:13)
#86     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:2901:8)
#87     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2303:5)
#88     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1076:49)
#89     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1035:13)
#90     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#91     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#92     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2313:13)
#93     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:847:13)
#94     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1031:49)
#95     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4969:12)
#96     FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:65:10)
#97     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1349:37)
#98     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4963:49)
#99     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#100    ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:360:16)
#101    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#102    UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3122:45)
#103    ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:785:11)
#104    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:356:49)
#105    InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:333:18)
#106    InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:373:7)
#107    InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:351:7)
#108    InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
#109    MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:788:24)
#110    MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:492:16)
#111    MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#112    ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:428:31)
#113    MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#114    ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1566:10)
#115    MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#116    ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3661:18)
#117    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#118    UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3229:59)
#119    ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3657:49)
#120    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#121    BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1080:17)
#122    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#123    UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#124    ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2304:13)
#125    ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:2901:8)
#126    ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2303:5)
#127    BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1076:49)
#128    BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1035:13)
#129    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#130    UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#131    ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2313:13)
#132    ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:847:13)
#133    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1031:49)
#134    FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4969:12)
#135    FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:65:10)
#136    ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1349:37)
#137    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4963:49)
#138    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#139    ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:360:16)
#140    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#141    UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:3122:45)
#142    ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:785:11)
#143    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:356:49)
#144    InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:333:18)
#145    InvocationInferenceHelper._resolveInvocationWithoutTypeArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:373:7)
#146    InvocationInferenceHelper._resolveInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:351:7)
#147    InvocationInferenceHelper.resolveMethodInvocation (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:256:5)
#148    MethodInvocationResolver._setResolution (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:788:24)
#149    MethodInvocationResolver._resolveReceiverNull (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:492:16)
#150    MethodInvocationResolver.resolve (package:analyzer/src/dart/resolver/method_invocation_resolver.dart:93:7)
#151    ElementResolver.visitMethodInvocation (package:analyzer/src/generated/element_resolver.dart:428:31)
#152    MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#153    ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:1566:10)
#154    MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7112:49)
#155    ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3661:18)
#156    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#157    UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3229:59)
#158    ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3657:49)
#159    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7536:20)
#160    BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1080:17)
#161    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#162    UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#163    ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2304:13)
#164    ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:2901:8)
#165    ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2303:5)
#166    BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1076:49)
#167    BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1035:13)
#168    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#169    UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#170    ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2313:13)
#171    ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:847:13)
#172    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1031:49)
#173    FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4969:12)
#174    FunctionExpressionResolver.resolve (package:analyzer/src/dart/resolver/function_expression_resolver.dart:65:10)
#175    ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:1340:35)
#176    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:4963:49)
#177    FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4832:26)
#178    ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1610:10)
#179    UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3271:59)
#180    ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:2619:11)
#181    ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:1330:11)
#182    ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:2612:7)
#183    ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:1299:11)
#184    FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4825:49)
#185    ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:981:23)
#186    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2119:49)
#187    FixBuilder.visitAll.<anonymous closure> (package:nnbd_migration/src/fix_builder.dart:191:14)
#188    _rootRun (dart:async/zone.dart:1190:13)
#189    _CustomZone.run (dart:async/zone.dart:1093:19)
#190    _runZoned (dart:async/zone.dart:1630:10)
#191    runZoned (dart:async/zone.dart:1550:10)
#192    NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#193    FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:188:35)
#194    NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:132:18)
#195    NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:104:15)
#196    _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1060:21)
#197    _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:998:30)
<asynchronous suspension>
#198    _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1057:11)
<asynchronous suspension>
#199    MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:615:48)
<asynchronous suspension>
#200    MigrateCommand.run (package:nnbd_migration/migration_cli.dart:205:72)
#201    CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#202    DartdevRunner.runCommand (package:dartdev/dartdev.dart:299:24)
#203    CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#204    new Future.sync (dart:async/future.dart:223:31)
#205    CommandRunner.run (package:args/command_runner.dart:112:14)
#206    runDartdev (package:dartdev/dartdev.dart:123:27)
#207    main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:9)
#208    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#209    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by goderbauer** [comment] 2020-09-24 19:15
In order to run `dart migrate` I had to modify the package slightly since some files were already migrated and the tool refused to run: https://github.com/flutter/flutter/commit/36f5b3db588e66f50c916974a3d9dfd00f5366a0

**Comment by leafpetersen** [comment] 2020-09-24 19:20
cc @stereotype441

**Comment by srawlins** [comment] 2020-09-24 22:08
CC @scheglov this seems to be deep in analyzer, resolving elements...

**Comment by scheglov** [comment] 2020-09-24 22:55
I can reproduce the issue running `dart migrate packages/flutter_test` in the Flutter repository.
Now I will try to reproduce it by running something under debugger.

**Comment by scheglov** [comment] 2020-09-24 23:03
I can reproduce it in IntelliJ under debugger.

**Comment by scheglov** [comment] 2020-09-25 00:10
https://dart-review.googlesource.com/c/sdk/+/164462

**Closed** 2020-09-25 16:21 UTC
Labels: NNBD, P1, analyzer-nnbd-migration, area-analyzer, crash
