### ISSUE TITLE
[extension types] Extension type does not get a highlight in DartDoc

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#53592] opened 2023-09-22 10:42 UTC
Any symbol references for an extension type symbol do not get the right highlight color in DartDoc:

Tooltips in VSCode do work though, so it's just the highlight color.

Example:

```
import 'dart:js_interop';

@JS()
@anonymous
@staticInterop
extension type BasicParameters._(JSObject _) {
  /// Create a [BasicParameters] instance using the given [callback].
  external factory BasicParameters({JSFunction callback});
}
```

Here the `[BasicParameters]` reference is not in light green (as it is for classes).

```
- Dart 3.2.0-189.0.dev (dev) (Thu Sep 21 21:03:12 2023 -0700) on "macos_x64"
- on macos / Version 13.5.2 (Build 22G91)
- locale is en-BE

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  59 MB | 0.0% |     02:10:41 | dart devtools --machine --try-ports 10 --allow-embedding                        |
| 688 MB | 0.0% |     02:10:41 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.72.2 |
```
![Screenshot 2023-09-22 at 12 57 15](https://github.com/dart-lang/sdk/assets/23480364/79870f00-1fec-4ca2-981a-47a9d452e4f9)

**Comment by srawlins** [comment] 2023-11-15 18:52
Forgive the seemingly nitpicky question, but the issue is with how _doc comments_ are highlighted in the IDE, yes? This is different from Dartdoc, which is a tool that uses doc comments to generate HTML documentation.

**Comment by bwilkerson** [comment] 2023-11-15 19:15
Interesting. Navigation also works, so we appear to be resolving the reference correctly.

My guess, without looking at the code, is that there's a test somewhere that checks what kind of element (declaration) the identifier resolved to and it doesn't correctly handle the element kind for extension types.

**Comment by navaronbracke** [comment] 2023-11-15 20:58
> Forgive the seemingly nitpicky question, but the issue is with how _doc comments_ are highlighted in the IDE, yes? This is different from Dartdoc, which is a tool that uses doc comments to generate HTML documentation.

Yes, the issue is about doc comments. Forgive me if I had the notion of "Dartdoc" wrong (which I assumed is a doc comment with `///` for Dart code)

**Comment by srawlins** [comment] 2023-11-15 20:59
No worries; I have to make sure that dartdoc, the tool, is doing the right thing too, so just making sure 😁

**Comment by bwilkerson** [comment] 2023-11-15 23:04
https://dart-review.git.corp.google.com/c/sdk/+/336601

**Closed by bwilkerson** 2023-11-15 23:04 UTC
Labels: area-analyzer, P2
