### ISSUE TITLE
Dart Analyzer Error 	Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by 8155220** [dart-lang/sdk#38406] opened 2019-09-16 03:22 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1097x617, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 12, method: completion.getSuggestions, params: {file: Z:\Flutter\flutterProject3\reserva_app\lib\ui\ComplejoDeportivoDetailUI.dart, offset: 900}, clientRequestTime: 1568603683758}
Exception: Element not found in summary: dart:core;dart:core;Never
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:338:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:359:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ElementHandle.librarySource (package:analyzer/src/dart/element/handle.dart:462:31)
#4      createExistingImportsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:101:19)
#5      CompletionDomainHandler.processRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:403:11)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#14     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart)
<asynchronous suspension>
#15     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#16     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#22     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#30     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#32     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#33     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#42     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#43     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#44     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#52     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#53     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#54     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#55     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#56     _...
```

Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Failed to handle completion domain request: {id: 12, method: completion.getSuggestions, params: {file: Z:\Flutter\flutterProject3\reserva_app\lib\ui\ComplejoDeportivoDetailUI.dart, offset: 900}, clientRequestTime: 1568603683758}
Exception: Element not found in summary: dart:core;dart:core;Never
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:338:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:359:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:34:43)
#3      ElementHandle.librarySource (package:analyzer/src/dart/element/handle.dart:462:31)
#4      createExistingImportsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:101:19)
#5      CompletionDomainHandler.processRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:403:11)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#14     CompletionDomainHandler.computeSuggestions (package:analysis_server/src/domain_completion.dart)
<asynchronous suspension>
#15     CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:392:5)
<asynchronous suspension>
#16     CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:282:9)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1500:12)
#21     CompletionDomainHandler.handleRequest (package:analysis_server/src/domain_completion.dart:275:12)
#22     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:325:45)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:50)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:320:5)
#30     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#31     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#32     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#33     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#42     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#43     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#44     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#52     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#53     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#54     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#55     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#56     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#57     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#58     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#59     _rootRunUnary (dart:async/zone.dart:1132:38)
#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#65     _StreamController._add (dart:async/stream_controller.dart:640:7)
#66     _StreamController.add (dart:async/stream_controller.dart:586:5)
#67     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#68     _rootRunUnary (dart:async/zone.dart:1136:13)
#69     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#70     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#71     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#72     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#73     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#74     _StreamController._add (dart:async/stream_controller.dart:640:7)
#75     _StreamController.add (dart:async/stream_controller.dart:586:5)
#76     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1339:33)
#77     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:860:14)
#78     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#79     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#80     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#81     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```
1568603646000 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1362,"uri":"package:analyzer/dart/ast/ast.dart","items":[{"label":"FunctionTypeAlias","declaringLibraryU
1568603646005 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1363,"uri":"package:yaml/yaml.dart","items":[{"label":"YamlWarningCallback","declaringLibraryUri":"packa
1568603646011 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1369,"uri":"package:pub_semver/pub_semver.dart","items":[{"label":"VersionConstraint","declaringLibraryU
1568603646020 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1374,"uri":"package:analyzer/dart/analysis/features.dart","items":[{"label":"FeatureSet","declaringLibra
1568603646203 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1375,"uri":"package:analyzer/analyzer.dart","items":[{"label":"Assertion","declaringLibraryUri":"package
1568603646237 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1387,"uri":"package:quiver/time.dart","items":[{"label":"daysInMonth","declaringLibraryUri":"package:qui
1568603646239 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1391,"uri":"package:quiver/testing/async.dart","items":[{"label":"FakeAsync","declaringLibraryUri":"pack
1568603646241 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1392,"uri":"package:boolean_selector/boolean_selector.dart","items":[{"label":"BooleanSelector","declari
1568603646248 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1393,"uri":"package:stream_channel/stream_channel.dart","items":[{"label":"VirtualChannel","declaringLib
1568603646284 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1401,"uri":"package:async/async.dart","items":[{"label":"DelegatingFuture","declaringLibraryUri":"packag
1568603646287 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":849,"uri":"package:matcher/matcher.dart","items":[{"label":"isPositive","declaringLibraryUri":"package:m
1568603646288 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1432,"uri":"package:pedantic/pedantic.dart","items":[{"label":"unawaited","declaringLibraryUri":"package
1568603646297 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1433,"uri":"package:charcode/html_entity.dart","items":[{"label":"$sup","declaringLibraryUri":"package:c
1568603646301 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1434,"uri":"package:charcode/ascii.dart","items":[{"label":"$b","declaringLibraryUri":"package:charcode/
1568603646317 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1435,"uri":"package:charcode/charcode.dart","items":[{"label":"$sup","declaringLibraryUri":"package:char
1568603646323 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1436,"uri":"package:term_glyph/term_glyph.dart","items":[{"label":"rightEnd","declaringLibraryUri":"pack
1568603646330 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1439,"uri":"package:source_span/source_span.dart","items":[{"label":"SourceSpanFormatException","declari
1568603646335 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1447,"uri":"package:string_scanner/string_scanner.dart","items":[{"label":"StringScanner","declaringLibr
1568603646349 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1452,"uri":"package:path/path.dart","items":[{"label":"PathException","declaringLibraryUri":"package:pat
1568603646355 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1458,"uri":"package:stack_trace/stack_trace.dart","items":[{"label":"ChainHandler","declaringLibraryUri"
1568603646361 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":848,"uri":"package:test_api/test_api.dart","items":[{"label":"expectAsyncUntil6","declaringLibraryUri":"
1568603659533 => {"id":"9","method":"edit.getFixes","params":{"file":"Z:\\Flutter\\flutterProject3\\reserva_app\\lib\\ui\\ComplejoDeportivoDetailUI.dart","offset":890},"clientRequestTime":156860365953
1568603659617 <= {"id":"9","result":{"fixes":[]}}
1568603659956 => {"id":"10","method":"edit.getFixes","params":{"file":"Z:\\Flutter\\flutterProject3\\reserva_app\\lib\\ui\\ComplejoDeportivoDetailUI.dart","offset":890},"clientRequestTime":15686036599
1568603659965 <= {"id":"10","result":{"fixes":[]}}
1568603660080 => {"id":"11","method":"edit.getAssists","params":{"file":"Z:\\Flutter\\flutterProject3\\reserva_app\\lib\\ui\\ComplejoDeportivoDetailUI.dart","offset":900,"length":0},"clientRequestTime
1568603660157 <= {"id":"11","result":{"assists":[]}}
1568603683758 => {"id":"12","method":"completion.getSuggestions","params":{"file":"Z:\\Flutter\\flutterProject3\\reserva_app\\lib\\ui\\ComplejoDeportivoDetailUI.dart","offset":900},"clientRequestTime"
1568603683762 <= {"id":"12","result":{"id":"0"}}
1568603683820 <= {"event":"server.error","params":{"isFatal":false,"message":"Failed to handle completion domain request: {id: 12, method: completion.getSuggestions, params: {file: Z:\\Flutter\\flutte
```

**Comment by keertip** [comment] 2019-09-16 16:28
Thanks for the report.

**Comment by keertip** [comment] 2019-09-16 16:28
Duplicate of #38367

**Closed by keertip** 2019-09-16 16:28 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
