### ISSUE TITLE
[dart.async] Calling Future.wait with empty List return unexpected Null type

### ISSUE THREAD

**Issue by kawin-aur** [dart-lang/sdk#43526] opened 2020-09-22 19:11 UTC
### Problem
Let's say if we have some empty List of Future, then apply Future.wait() to it.

**eg.** 

```
void main() async {
    List<Future<CustomClass>> futureList = List<Future<CustomClass>>();

    List<CustomClass> result = await Future.wait(futureList);
}
```

When trying to call Future.wait with empty value, Future.wait() return type is `Future<List<Null>>` instead of `Future<List<T>>` which is `List<CustomClass>` in this case.

I've looked into the Future.wait() implementation and found that if an empty List is used as input, the result will be cast into `<Never>` type. Shouldn't this be `<T>` so it returns the expected T type? Not sure if this is intended or not.
I've provided the simple reproducible example URL below. Thanks!

**Implementation from api.dart.dev**
```
..
..
    if (remaining == 0) {
      return new Future<List<T>>.value(const <Never>[]); << why <Never> though ? shouldn't it be <T> ?
    }
..
..
```
Implementation Reference: https://api.dart.dev/stable/2.9.3/dart-async/Future/wait.html

**Edit-1:** I've updated the reproducible gist to show why `List<Null>` will cause the problem in our use case. Empty `const List<Never>` won't allow us to add `<T>` data to List.

### Reproducible steps
*Updated Reproducible gist can be found here: https://dartpad.dev/a416ee80b32e4d9fac2333c8fe5dbc60

* Dart SDK Version (`dart --version`): Dart SDK version: 2.9.2 (stable) 
* Whether you are using Windows, MacOSX, or Linux (if applicable): on "macos_x64" macOS Catalina 10.15.6

**Comment by mkustermann** [comment] 2020-09-23 14:27
The `Never` type is our new bottom type, which means a `List<Never>` can be assigned to a `List<CustomClass>`. So if the only guarantee of `Future.wait` is to return a unmodifiable list, returning a `const <Never>[]` for an empty `List<Future>` seems ok.

/cc @lrhn

**Comment by lrhn** [comment] 2020-09-24 10:27
It's type-wise valid to return an empty `List<Never>`, but it can cause issues with operations on lists which are contravariant.
There are a few of those which are even allowed on an unmodifiable list, for example `firstWhere(bool test(T value), {T orElse()})`. 
 (That was a [bad idea](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+firstWhere) to begin with, and I do feel bad about it).

If we have a `List<Never>` instance with static type `List<T>`, then calling `list.firstWhere(test, () => someTValue)` will *fail at run-time* because `() => someTValue` is not assignable to `void Function()`. That's unsound covariance, which means no static warning and run-time errors.

(This is also a duplicate of https://github.com/dart-lang/sdk/issues/43445, so closing in favor of that issue).

**Closed by lrhn** 2020-09-24 10:27 UTC
Labels: area-library
