### ISSUE TITLE
Dart Analyzer becomes unresponsive

### ISSUE THREAD

**Issue by the-ginger-geek** [dart-lang/sdk#46330] opened 2021-06-11 06:58 UTC
This tracker is for issues related to:

* Analyzer
* Dart version 2.13.1
* MacOSX

I have searched for a bug on the issues list but couldn't find anything, sorry if there's already an issue for this.

I can recreate the bug when running commands in this order, in the IDE terminal, sometimes it happens when only running the build_runner command. This occurs on all IDE's that supports flutter when following the below steps.

## Steps to reproduce

1. `run flutter pub run build_runner build --delete-conflicting-outputs`
2. `run flutter clean`
3. `run flutter pub get`

https://user-images.githubusercontent.com/2182638/121373356-486a9800-c93f-11eb-8fae-1b19f4883fae.mov

When restarting the `dart analyzer` using the refresh arrows on the IDE the problem is resolved.

**Please see [this](https://github.com/flutter/flutter-intellij/issues/5558) thread for more information.**

### IntelliJ version info

```
IntelliJ IDEA 2021.1.2 (Community Edition)
Build #IC-211.7442.40, built on June 1, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), com.xinkun.theme.md (1.7.12), Dart (211.7233), org.toml.lang (0.2.148.3911-211), io.flutter (57.0.5), Docker (211.7442.9), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), pl.pszklarska.pubversionchecker (1.2.5), com.chrisrm.idea.MaterialThemeUI (6.6.0)
Kotlin: 211-1.5.10-release-891-IJ7142.45
```

### VS Code version info

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (4 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.5.0
```

**Comment by mraleph** [comment] 2021-06-11 11:17
Most likely duplicate of #45996. Please try reproducing on master channel.

**Closed by mraleph** 2021-06-11 11:17 UTC
