### ISSUE TITLE
DateTime. Bug with winter/summer time

### ISSUE THREAD

**Issue by Aqitaniya** [dart-lang/sdk#51963] opened 2023-04-05 15:27 UTC
This tracker is for issues related to:

* Dart core libraries: DateTime

* Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_arm64"

Example:
```
  final DateTime date = DateTime(2023, 03, 27);
  print(date);  // 2023-03-27 00:00:00.000
  print(date.subtract(const Duration(days: 1)));  //2023-03-25 23:00:00.000
  print(date.subtract(const Duration(hours: 24)));  //2023-03-25 23:00:00.000
```
The same issue with date.add and others

**Comment by julemand101** [comment] 2023-04-05 15:39
Works as intended if you read the documentation.

Duplicate of https://github.com/dart-lang/sdk/issues/37449

**Comment by lrhn** [comment] 2023-04-05 16:29
Correct. The difference between two local-time `DateTime` objects is the actual time between the two, and adding `Durations` to `DateTime` objects gives the local time after that duration has passed. 
`Duration` doesn't actually understand "days", it just thinks converts them to 24 hours.

**Closed by lrhn** 2023-04-05 16:29 UTC
