### ISSUE TITLE
Type of resulting List from List.unmodifiable() is not inferred

### ISSUE THREAD

**Issue by komapeb** [dart-lang/sdk#37198] opened 2019-06-07 17:00 UTC
Behavior:

```dart
List<int> list1 = [0];
var list2 = List.unmodifiable(list1);
// list2.first is treated as dynamic, no code suggestions
```

Expected behavior is that `list2` infers the type of `list1`.

I guess this also applies to other `Iterable`s that have an `unmodifiable` constructor.

**Comment by eernstg** [comment] 2019-06-07 17:51
Type inference in Dart gives a high priority to the context type (that's the type of the "target" of an expression, e.g., the variable that it is initializing or the parameter that it's passed to, etc), which means that you get a `List<dynamic>` when you invoke the constructor `List.unmodifiable`, because you haven't given any hints about what you want.

You can use `List<int> list2 = List.unmodifiable(list1);` or `var list2 = List<int>.unmodifiable(list1);` to force the type argument `int`.

The reason for giving the context type so much weight is that the type argument is significant for the user of the given object (a fresh one for a constructor call, or some computed result if you are calling a generic function). In particular, if you write `List<num> xs = [0];` then you can proceed with `xs.add(3.51)` because it's a `List<num>`, but if it had been created ("optimally") as a `List<int>` then that addition would be an error.

This is again a consequence of having mutable state and having covariance by default, which is a choice that offers more flexibility in return for less static type safety. We're gradually introducing more strict typing so you will surely be able to choose different trade-offs in the future, but at this point the best advice is to notice that the context type matters.

**Comment by eernstg** [comment] 2019-06-07 17:52
This is all working as intended, so I'll close the issue.

**Closed by eernstg** 2019-06-07 17:52 UTC
Labels: closed-as-intended

**Comment by komapeb** [comment] 2019-06-07 18:28
`List<SomeType>.unmodifiable(...)` makes so much sense, how could've I missed that. Thanks for the explanation.
