### ISSUE TITLE
Having true cancelable future

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/sdk#56095] opened 2024-06-27 10:17 UTC
```
Future<Data> foo() async {
    ...
    var f1 = await DownloadLargeFile(url1);
    ...
    var f2 = await DownloadLargeFile(url2);
    ...
}
```
No matter what I tried, one you `await foo()` the two files will be downloaded, there is no way to abandon all async task link to a particular Future.

from my own testing, `CancelableOperation` from the `async` package is just a wrapper on a `Future` that pretend to make things cancelable but the actual function continue to run, the only thing is that the returned value will be discarded if the operation was cancel by the user.
So I think this is quite misleading and hide a missing feature with Future in Dart

**Comment by mraleph** [comment] 2024-06-27 10:46
Duplicate of https://github.com/dart-lang/sdk/issues/42855

(I think we got a reasonable idea what we could implement, see https://github.com/dart-lang/sdk/issues/42855#issuecomment-1621803392 - but did not have time to actually implement it yet)

**Closed by mraleph** 2024-06-27 10:46 UTC
Labels: area-language, type-enhancement, triage-automation
