### ISSUE TITLE
webdev with Dart 2.0.0-dev.64.1 crashes on Mac 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#33558] opened 2018-06-21 16:01 UTC
I'm on: Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G21013
Darwin Kernel Version 15.6.0: Wed May  2 21:04:22 PDT 2018; root:xnu-3248.73.10~1/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

After installing Dart 2.0.0-dev.64.1 `webdev serve` crashes with:
(Switching back to `brew switch dart 2.0.0-dev.63.0 --devel` solved the problem)

```bash
Crash when compiling file:///Users/mikemitterer/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot,
at character offset null:
Internal problem: Unhandled �' in analyzeQuote.
#0      internalProblem (package:front_end/src/fasta/problems.dart:30:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:43:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      OutlineBuilder.endLiteralString (package:front_end/src/fasta/source/outline_builder.dart:329:12)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4656:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4581:13)
#7      Parser.ensureLiteralString (package:front_end/src/fasta/parser/parser.dart:2753:12)
#8      Parser.parsePart (package:front_end/src/fasta/parser/parser.dart:949:13)
#9      Parser.parsePartOrPartOf (package:front_end/src/fasta/parser/parser.dart:936:14)
#10     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:581:16)
#11     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:449:14)
#12     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:329:15)
#13     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:195:37)
<asynchronous suspension>
#14     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#16     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#17     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#18     new Future.sync (dart:async/future.dart:222:31)
#19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _runZoned (dart:async/zone.dart:1518:10)
#23     runZoned (dart:async/zone.dart:1465:12)
#24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#25     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#26     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#27     IncrementalCompilerWrapper.compileInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#28     Compiler.compile.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:132:39)
#29     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#30     _rootRun (dart:async/zone.dart:1122:38)
#31     _CustomZone.run (dart:async/zone.dart:1023:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#34     _rootRun (dart:async/zone.dart:1126:13)
#35     _CustomZone.run (dart:async/zone.dart:1023:19)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#37     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#38     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#39     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


#0      internalProblem (package:front_end/src/fasta/problems.dart:30:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:43:10)
#2      analyzeQuote (package:front_end/src/fasta/quote.dart:54:10)
#3      unescapeString (package:front_end/src/fasta/quote.dart:138:17)
#4      OutlineBuilder.endLiteralString (package:front_end/src/fasta/source/outline_builder.dart:329:12)
#5      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4656:14)
#6      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4581:13)
#7      Parser.ensureLiteralString (package:front_end/src/fasta/parser/parser.dart:2753:12)
#8      Parser.parsePart (package:front_end/src/fasta/parser/parser.dart:949:13)
#9      Parser.parsePartOrPartOf (package:front_end/src/fasta/parser/parser.dart:936:14)
#10     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:581:16)
#11     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:449:14)
#12     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:329:15)
#13     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:195:37)
<asynchronous suspension>
#14     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#15     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#16     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#17     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#18     new Future.sync (dart:async/future.dart:222:31)
#19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _runZoned (dart:async/zone.dart:1518:10)
#23     runZoned (dart:async/zone.dart:1465:12)
#24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#25     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#26     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#27     IncrementalCompilerWrapper.compileInternal (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#28     Compiler.compile.<anonymous closure> (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/vm/bin/kernel_service.dart:132:39)
#29     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#30     _rootRun (dart:async/zone.dart:1122:38)
#31     _CustomZone.run (dart:async/zone.dart:1023:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#34     _rootRun (dart:async/zone.dart:1126:13)
#35     _CustomZone.run (dart:async/zone.dart:1023:19)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#37     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#38     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#39     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by chalin** [comment] 2018-06-21 19:11
Mike, this should be moved to https://github.com/dart-lang/webdev/issues.

If you want to continue using 2-dev.64, you can build using the build_runner directly (that works for me).

cc @kevmoo @kwalrath

**Comment by chalin** [comment] 2018-06-21 19:16
FYI, the related issue I was having is this one: https://github.com/dart-lang/webdev/issues/63

**Comment by natebosch** [comment] 2018-06-22 00:12
Duplicate of https://github.com/dart-lang/pub/issues/1932

Workaround is `pub global run webdev`

**Closed** 2018-06-22 12:08 UTC
Labels: Resolution: duplicate
