### ISSUE TITLE
fasta crashes when const constructor has type parameters and strong mode is enabled

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#30678] opened 2017-09-12 15:09 UTC
```dart
class Bar<T> {
  const Bar<E>();
}
```

causes this (note: only happens with `--strong-mode`)

```
╭─ ~/src/dart/sdk ‹master›
╰─$ ./pkg/front_end/tool/fasta compile -o t/z.dart.dill --strong-mode --platform=./out/ReleaseX64/patched_sdk/platform.dill t/z.dart                                                                          255 ↵
Note: strong mode support is preliminary and may not work.
Unhandled exception:
'package:kernel/binary/ast_to_binary.dart': Failed assertion: line 477 pos 12: 'node.function.typeParameters.isEmpty': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:35)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:31)
#2      BinaryPrinter.visitConstructor (package:kernel/binary/ast_to_binary.dart:477:12)
#3      Constructor.accept (package:kernel/ast.dart:1211:32)
#4      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:132:10)
#5      List.forEach (dart:core-patch/growable_array.dart:267)
#6      BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:124:11)
#7      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:128:5)
#8      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:457:5)
#9      Class.accept (package:kernel/ast.dart:830:30)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:132:10)
#11     List.forEach (dart:core-patch/growable_array.dart:267)
#12     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:124:11)
#13     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:128:5)
#14     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:353:5)
#15     Library.accept (package:kernel/ast.dart:381:30)
#16     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:132:10)
#17     List.forEach (dart:core-patch/growable_array.dart:267)
#18     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:124:11)
#19     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:201:5)
#20     BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:190:5)
#21     writeProgramToFile (package:front_end/src/fasta/kernel/utils.dart:37:29)
<asynchronous suspension>
#22     CompileTask.compile (file:///usr/local/google/home/vegorov/src/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:164:11)
<asynchronous suspension>
#23     compile.<anonymous closure> (file:///usr/local/google/home/vegorov/src/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:98:25)
<asynchronous suspension>
#24     withGlobalOptions.<anonymous closure> (file:///usr/local/google/home/vegorov/src/dart/sdk/pkg/front_end/tool/_fasta/command_line.dart:328:13)
#25     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#26     _rootRun (dart:async/zone.dart:1120)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     runZoned (dart:async/zone.dart:1467)
#29     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#30     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#31     withGlobalOptions (file:///usr/local/google/home/vegorov/src/dart/sdk/pkg/front_end/tool/_fasta/command_line.dart:321:26)
#32     compile (file:///usr/local/google/home/vegorov/src/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:91:18)
<asynchronous suspension>
#33     compileEntryPoint (file:///usr/local/google/home/vegorov/src/dart/sdk/pkg/front_end/tool/_fasta/entry_points.dart:49:11)
<asynchronous suspension>
#34     main (file:///usr/local/google/home/vegorov/src/dart/sdk/pkg/front_end/tool/_fasta/compile.dart:7:33)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

I would expect this to report some sort of nice error.

**Comment by peter-ahe-google** [comment] 2017-09-12 15:49
Hey, didn't it say: "Note: strong mode support is preliminary and may not work." ;-)

Just kidding, thank you for reporting this, and I think you assigned it correctly as well.

**Comment by peter-ahe-google** [comment] 2017-09-12 15:52
Well, I guess it could as well be me that fixes this. This could be found in body_builder.dart.

**Comment by stereotype441** [comment] 2017-09-12 19:59
Yeah, this should probably be fixed in body_builder.dart; constructors aren't allowed to be generic.

**Comment by askeksa-google** [comment] 2018-05-24 14:49
Possibly a duplicate of https://github.com/dart-lang/sdk/issues/31196

**Closed** 2018-06-01 12:50 UTC
Labels: P2 medium, area-front-end, crash, front-end-fasta
