### ISSUE TITLE
Selectable try bots

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#32062] opened 2018-02-06 16:49 UTC
Would it be possible to select (per CL) which try bots to include on the CQ (even if it's in addition to a core set)? When I'm working on a change to the analyzer, for example, it would be nice to have all of the analyzer bots run (and sometimes some of the ddc bots depending on what I'm changing), but I rarely need to have the dart2js or vm bots run because they aren't impacted by analyzer changes (mostly what I get there is passes or false positives).

**Comment by athomas** [comment] 2018-02-27 23:23
Duplicate of #31609.

**Closed by athomas** 2018-02-27 23:23 UTC
Labels: Type: enhancement, area-infrastructure
