### ISSUE TITLE
No quick fix for `non_exhaustive_switch` and `non_exhaustive_switch_expression`

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#51985] opened 2023-04-07 19:31 UTC
Consider the following code:
```dart
f(num x) => switch (x) {};
```
With pattern support enabled, this has the error message `The type 'num' is not exhaustively matched by the switch cases since it doesn't match 'double()'.` and the correction suggestion `Try adding a wildcard pattern or cases that match 'double()'.`

It would be nice if there were a quick fix that added the text `double() => ` to the end of the switch, leaving the cursor positioned after the `=>`.

Similarly, for this code:
```dart
f(num x) {
  switch (x) {}
}
```
the error message is `The type 'num' is not exhaustively matched by the switch cases since it doesn't match 'double()'.`, again with the correction suggestion `Try adding a default case or cases that match 'double()'.`

Again, it would be nice if there were a quick fix that added the text `case double():` to the end of the switch, leaving the cursor positioned after the `:`.

I believe @johnniwinther has done some work to try to format the string in the correction message so that it's appropriate for use in a quick fix, so it should hopefully be fairly simple to extract the appropriate pattern from the correction message text.

**Comment by johnniwinther** [comment] 2023-04-11 07:23
The message contains two patterns. The first has more restrictions than necessary to match the non-exhaustive case, whereas the second is a reduced version which a more likely candidate for a fix. For instance
```
m(num n) => switch (n) {
    int(hashCode: 5) => 0,
    double() => 1,
};
```
reports, as the first pattern, that `int(hashCode: int())` is not matched, to indicated that the problem is with the restriction on `hashCode`, but as the second pattern it suggests `int()` because it is a more compact way of matching the same values.

**Comment by scheglov** [comment] 2023-04-14 21:20
https://dart-review.googlesource.com/c/sdk/+/295391

**Comment by scheglov** [comment] 2023-04-17 21:20
The change landed, but I will not close it yet, pending possible improvements.

**Comment by scheglov** [comment] 2024-06-12 22:34
I think 726f9f1a68b4307bd6090f892189dc68bd0d5175 fixes the last remaining problems here.

**Closed by scheglov** 2024-06-12 22:34 UTC
Labels: area-analyzer, analyzer-quick-fix, P2, type-enhancement, analyzer-language-patterns
