### ISSUE TITLE
HashMap/LinkedHashMap functions containsKey and putIfAbsent don't recognise 2 same List<int> keys as similar 

### ISSUE THREAD

**Issue by hrithikm2** [dart-lang/sdk#54867] opened 2024-02-09 09:37 UTC
I was solving a leet code problem groupAnagrams where I saw a solution in Python and tried to recreate it in Dart.
However, using map methods to identify whether the map contains a key fails since it cannot identify a list containing certain values in a fixed order to be the same as another list which is the same.
Here is the code I am using 

1. Using *containsKey* method
```
import 'dart:collection';

class Solution {
  List<List<String>> groupAnagrams(List<String> strs) {
    var res = LinkedHashMap<List<int>,
        List<String>>(); // mapping charCount to List of Anagrams
    for (var s in strs) {
      var count = List<int>.filled(
          26, 0); // a 26-length array to store character counts
      for (var c in s.runes) {
        print(c);
        count[c - 'a'.codeUnitAt(0)]++;
      }
      print(count);
      var key = List<int>.from(count);
      if (res.containsKey(key)) {
        res[key]!.add(s);
      } else {
        res.addEntries({
          key: [s]
        }.entries);
      }
    }
    return res.values.toList();
  }
}

void main() {
  var result =
      Solution().groupAnagrams(["eat", "tea", "tan", "ate", "nat", "bat"]);
  print(result); // Output: [[eat, tea, ate], [tan, nat], [bat]]
}
```

Using *putIfAbsent* method

```
import 'dart:collection';

class Solution {
  List<List<String>> groupAnagrams(List<String> strs) {
    var res = LinkedHashMap<List<int>,
        List<String>>(); // mapping charCount to List of Anagrams
    for (var s in strs) {
      var count = List<int>.filled(
          26, 0); // a 26-length array to store character counts
      for (var c in s.runes) {
        print(c);
        count[c - 'a'.codeUnitAt(0)]++;
      }
      print(count);
      var key = List<int>.from(count);
      res.putIfAbsent(key, () => []).add(s);
    }
    return res.values.toList();
  }
}

void main() {
  var result =
      Solution().groupAnagrams(["eat", "tea", "tan", "ate", "nat", "bat"]);
   print(result);
}

```

**Comment by eernstg** [comment] 2024-02-09 10:26
Try this:

```dart
import 'package:collection/collection.dart';

class Solution {
  List<List<String>> groupAnagrams(List<String> strs) {
    var res = EqualityMap<List<int>, List<String>>(
        const ListEquality(DefaultEquality()));
    for (var s in strs) {
      var count = List<int>.filled(
          26, 0); // a 26-length array to store character counts
      for (var c in s.runes) {
        print(c);
        count[c - 'a'.codeUnitAt(0)]++;
      }
      print(count);
      var key = List<int>.from(count);
      if (res.containsKey(key)) {
        res[key]!.add(s);
      } else {
        res.addEntries({
          key: [s]
        }.entries);
      }
    }
    return res.values.toList();
  }
}

void main() {
  var result =
      Solution().groupAnagrams(["eat", "tea", "tan", "ate", "nat", "bat"]);
  print(result); // Output: [[eat, tea, ate], [tan, nat], [bat]]
}
```

The point is that you're using a plain `Map`, and their key equality is the equality of the key type (here: `List<int>`), and equality of lists is based on identity. (Lists use identity as equality because they are, in general, mutable, which means that it _does_ matter whether two lists are two distinct objects or not, you can't assume that they will have the same elements just because they happen to have the same elements at the time where you are testing them).

If you switch to use an `EqualityMap` then you can specify the kind of equality that you want to use. In this case we probably want to use element-by-element equality for the `List<int>` objects that are used as keys.

**Comment by eernstg** [comment] 2024-02-09 10:30
I'll close this issue because it's all working as intended.

**Closed by eernstg** 2024-02-09 10:30 UTC

**Comment by hrithikm2** [comment] 2024-02-09 11:14
Thanks for the code @eernstg. I am aware that packages can help but it should also be possible using only dart.
