### ISSUE TITLE
Flaky QEMU crashes on "ffi tests" step of vm-precomp-ffi-qemu-linux-release-arm bot

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46357] opened 2021-06-14 21:26 UTC
This crash happens from time to time, making the bot purple.

Crash 1:
```
INFO: Core dump archiving is activated
Test configuration:
    dartkp-linux-release-arm-qemu(architecture: arm, compiler: dartkp, mode: release, runtime: dart_precompiled, system: linux, use-qemu)
Suites tested: ffi_2
Total: 289 tests
 * 0 tests will be skipped (0 skipped by design)
 * 0 tests are expected to be flaky but not crash
 * 0 tests are expected to flaky crash
 * 288 tests are expected to pass
 * 0 tests are expected to fail that we won't fix
 * 0 tests are expected to fail that we should fix
 * 0 tests are expected to crash that we should fix
 * 0 tests are allowed to timeout
 * 1 could not be categorized or are in multiple categories

Unexpected exit code 127
DART_CONFIGURATION=ReleaseXARM qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/multitest_ffi_2_vmspecific_function_callbacks_exit_test_02/out.aotsnapshot

**
ERROR:/build/qemu-jNW88T/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached

INFO: No unexpected crashes recorded
```
Log: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8844420182354177776/+/u/ffi_tests/stdout

Crash 2:
```
INFO: Core dump archiving is activated
Test configuration:
    dartkp-linux-release-arm-qemu(architecture: arm, compiler: dartkp, mode: release, runtime: dart_precompiled, system: linux, use-qemu)
Suites tested: ffi_2
Total: 289 tests
 * 0 tests will be skipped (0 skipped by design)
 * 0 tests are expected to be flaky but not crash
 * 0 tests are expected to flaky crash
 * 288 tests are expected to pass
 * 0 tests are expected to fail that we won't fix
 * 0 tests are expected to fail that we should fix
 * 0 tests are expected to crash that we should fix
 * 0 tests are allowed to timeout
 * 1 could not be categorized or are in multiple categories

Unexpected exit code 127
DART_CONFIGURATION=ReleaseXARM qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_regress_45507_test/out.aotsnapshot

**
ERROR:/build/qemu-jNW88T/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached

INFO: No unexpected crashes recorded
```
Log: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8844434190864443056/+/u/ffi_tests/stdout

Could be a bug in QEMU or something bad happening in our FFI tests.

/cc @dcharkes

**Comment by alexmarkov** [comment] 2021-07-12 19:47
Still happens:

```
Unexpected exit code 127
DART_CONFIGURATION=ReleaseXARM qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime --deterministic --optimization-counter-threshold=10 --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_variance_function_test.dart_1/out.aotsnapshot

**
ERROR:/build/qemu-jNW88T/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached

INFO: No unexpected crashes recorded
```

**Comment by alexmarkov** [comment] 2022-05-19 13:59
Happened once again:
```
INFO: Core dump archiving is activated
No build targets found.
Test configuration:
    dartkp-linux-release-arm-qemu(architecture: arm, compiler: dartkp, mode: release, runtime: dart_precompiled, system: linux, use-qemu)
Suites tested: ffi_2
Total: 316 tests
 * 1 tests will be skipped (1 skipped by design)
 * 0 tests are expected to be flaky but not crash
 * 0 tests are expected to flaky crash
 * 315 tests are expected to pass
 * 0 tests are expected to fail that we won't fix
 * 0 tests are expected to fail that we should fix
 * 0 tests are expected to crash that we should fix
 * 0 tests are allowed to timeout
 * 0 could not be categorized or are in multiple categories

Unexpected exit code 127
DART_CONFIGURATION=ReleaseXARM qemu-arm -L /usr/arm-linux-gnueabihf/ out/ReleaseXARM/dart_precompiled_runtime -Dtest_runner.configuration=dartkp-linux-release-arm-qemu --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.dart_tool/package_config.json /b/s/w/ir/cache/builder/sdk/out/ReleaseXARM/generated_compilations/dartkp-linux-release-arm-qemu/tests_ffi_2_expando_test/out.aotsnapshot

**
ERROR:/build/qemu-CsbAwl/qemu-2.11+dfsg/qom/object.c:1645:object_get_canonical_path_component: code should not be reached

INFO: No unexpected crashes recorded
```
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8813736398130248945/+/u/ffi_tests/stdout

**Comment by dcharkes** [comment] 2022-08-22 11:31
Duplicate of https://github.com/dart-lang/sdk/issues/46775.

**Closed by dcharkes** 2022-08-22 11:31 UTC
Labels: area-vm, gardening
