### ISSUE TITLE
Dart core libraries - WebSocket not found in dart:html

### ISSUE THREAD

**Issue by bozzaccio** [dart-lang/sdk#48102] opened 2022-01-07 22:11 UTC
Hi,

when i use web socket i get this runtime error.
i have try with a simple code, but it doesen't change, it is probably a bad configuration? i cannot find anything in the official docs

here is the code snippet

```
import 'dart:html';

void main(List<String> arguments) async {

  var ws = WebSocket('ws://localhost:3000');

  ws.send("hello world!");
}

```

![image](https://user-images.githubusercontent.com/74464364/148613264-82c27de3-4ff7-48a5-9378-4782dca79a6b.png)

This tracker is for issues related to:
* Dart core libraries: dart:html

* Dart SDK Version: 2.15.1
* Linux (Debian)
* Dart VM and Flutter(Android)

**Comment by julemand101** [comment] 2022-01-07 23:21
`dart:html` is only for Dart code generated to JavaScript. If your target platform is Dart VM and/or Flutter running on mobile devices, you should look at the `WebSocket` class in `dart:io`.

**Comment by vsmenon** [comment] 2022-01-08 01:02
Right, see : https://api.dart.dev/stable/2.15.1/index.html for what libraries are Web-only or VM/Native-only.

Closing this as working as intended.

**Closed by vsmenon** 2022-01-08 01:02 UTC
Labels: closed-as-intended
