### ISSUE TITLE
CFE: provide a better representation for redirecting factories in kernel AST

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#34277] opened 2018-08-27 18:05 UTC
Currently, front-end records information about redirecting factories in kernel using synthetic static field "_redirecting#": https://github.com/dart-lang/sdk/blob/1b89c785e11ec7ad2a0b5d73457a821444c5babf/pkg/front_end/lib/src/fasta/kernel/kernel_class_builder.dart#L325-L353

There are several problems with this approach:

* AST of the initializers of these synthetic fields is not quite correct: it has a tear-off (StaticGet) of a constructor.

* Some of the clients need to distinguish these synthetic static fields and have its name hardcoded.

Analyzer:
https://github.com/dart-lang/sdk/blob/1b89c785e11ec7ad2a0b5d73457a821444c5babf/pkg/analyzer/lib/src/dart/element/element.dart#L1323

DDC:
https://github.com/dart-lang/sdk/blob/1b89c785e11ec7ad2a0b5d73457a821444c5babf/pkg/dev_compiler/lib/src/kernel/kernel_helpers.dart#L210

Consider adding a first-class representation for redirecting factories into kernel AST.

**Comment by kmillikin** [comment] 2018-09-06 17:03
It's a known issue, duplicate of #28421 (related to #28424).

**Closed by kmillikin** 2018-09-06 17:03 UTC
Labels: area-front-end
