### ISSUE TITLE
vm/dart/isolates/reload_many_isolates_live_and_die_test flips between flaky, pass, and timeout

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#52253] opened 2023-05-03 15:54 UTC
This was accidentally triggered by an unrelated [dart2js change"](https://github.com/dart-lang/sdk/compare/ab4fbf128e5f291592afb70f662ed99bb84f8ce8~...485633b50fc577fbcbe73bebc67e7a38a2762287).

Test:
```
vm/dart/isolates/reload_many_isolates_live_and_die_test Timeout (expected Pass)
```

Configuration:
```
vm-mac-release-x64
```

**Comment by a-siva** [comment] 2023-05-04 21:55
//cc @aam

**Comment by aam** [comment] 2023-05-04 21:56
Duplicate of https://github.com/dart-lang/sdk/issues/51347

**Closed by aam** 2023-05-04 21:56 UTC
Labels: area-vm, gardening
