### ISSUE TITLE
Function object does not implement function interface as indicated by is operator

### ISSUE THREAD

**Issue by gmb119943** [dart-lang/sdk#51616] opened 2023-03-03 09:07 UTC
I assumed that the implementation inside the call function class leads to the fact that this class will implicitly implement the function interface. But as the following example shows, this is not the case and the behavior is a little strange in terms of the type hierarchy. Is this an error with the is operator, or is this by design?

```dart
class Example {
  void call() {}
}

void main() {
  var example = Example();

  // No errors, because the class has a function "call".
  Function function = example;

  // false
  if (function is! Function) {
    print('Error: the function is not really a function.');
  } else {
    print('A function is actually a function.');
  }
  
  // true
  if (Example is! Function) {
    print('Error: example does not implement interface functions.');
  } else {
    print('Example implements Interface Functions.');
  }
}
```

**Comment by lrhn** [comment] 2023-03-03 09:20
It's by design.

No `class` implements the `Function` interface except `Function` itself.

It used to be the case, in Dart 1, that a class with a `call` method implemented the function type of the `call` method, and thereby `Function`.

That was incompatible with the sound type system of Dart 2, so callable classes no longer implemented function types.
We could have let them still implement `Function`, but preferred to not do that either, so that `is Function` now distinguishes between function objects and class instance objects.
In Dart 2, function objects really are a different *kind* of object than class instances, and the only kind of objects which has a function type. Being able to distinguish these using `is Function` was considered useful.

The reason the `Example()` object is assignable to `Function` is that an implicit coercion happens at the assignment.
The behavior of `Function function = example;` is really that of `Function function = example.call;`, performing an "implicit `call` tear-off".

So, callable objects are not functions. They can be *assignable* to function types, and always to `Function`, but are not *subtypes*. Being assignable when not being a subtype means that there is an implicit coercion inserted to create a value which *is* a subtype, before being assigned to a variable expecting that type.

Callable objects can also be called like functions, and again an implicit `.call` is inserted, to `example()` really means `example.call()`.

**Closed by lrhn** 2023-03-03 09:20 UTC
