### ISSUE TITLE
dart analysis and compiler dosen't check type when using ?? operator

### ISSUE THREAD

**Issue by rafalbednarczuk** [dart-lang/sdk#36294] opened 2019-03-21 17:50 UTC
Dart 2.2.1 (build 2.2.1-dev.1.0 674fd0e060) (flutter 1.3.10)
Linux - ubuntu 18.04 or nexus 5 device android 8.1.0

    final anythingNull = null;
    String someString = anythingNull ?? 10;

Dart analysis and Compiler don't show any errors.

**Comment by eernstg** [comment] 2019-03-22 09:38
It turns out that the inferred type of `anythingNull` is `dynamic`:

```dart
final anythingNull = null;
String someString = anythingNull ?? 10;

void printType<X>(X x) => print(X);

main() {
  printType(anythingNull);
}
```

So in this situation you get an expression whose type is the least upper bound of `dynamic` and `int`, and that's `dynamic`, and that is assignable to `String`.

You can use `--no-implicit-casts` on the command line to require that all casts are shown explicitly (or put it into your ['analysis_options.yaml'](https://www.dartlang.org/guides/language/analysis-options)). You could also give the type `Null` explicitly in the declaration of `anythingNull` (if that matches the actual situation where you encountered this).

**Comment by rafalbednarczuk** [comment] 2019-03-22 12:11
List<int> listOfInts = [10,20];
    List<int> nullListOfInts = null;
    List<String> listOfStrings1 = listOfInts; //Compiler & analysis error
    List<String> listOfString2 = listOfInts ?? 10; //No compiler & analysis error
    List<String> listOfString3 = nullListOfInts ?? 10; //No compiler & analysis error
  
It is the actual situation I encounter such a behaviour. It a little bit different because there is `List`

**Comment by kevmoo** [comment] 2019-04-03 21:48
Should this issue be transferred to the language repo?

**Comment by eernstg** [comment] 2019-04-05 09:28
We have two issues here:

- Should type inference on `final v = null;` equip `v` with the type annotation `dynamic`?
- Errors reported [here](https://github.com/dart-lang/sdk/issues/36294#issuecomment-475597721).

I've created dart-lang/language#300 in order to resolve the former.

If such variables will actually have the type `dynamic` then the other symptoms reported [here](https://github.com/dart-lang/sdk/issues/36294#issue-423863618) are just unavoidable consequences, i.e., the whole issue can be closed with "working as intended".

Otherwise (where such variables get some other type than `dynamic`), the reported symptoms will disappear when the required changes have been made in all tools. That would make this issue blocked on dart-lang/language#300, but I'd suggest that we just close this one anyway, because the implementation of dart-lang/language#300 will surely be associated with new tests where such things are tested anyway.

For [bullet two](https://github.com/dart-lang/sdk/issues/36294#issuecomment-475597721), the reported symptoms are a consequence of an extreme upcast followed by a downcast (`LeastUpperBound(List<int>, int) == Object`, then implicitly downcast to `List<String>`). This issue will go away when implicit downcasts are eliminated as part of the non-null-by-default transition (check [label `nnbd` on the language repository](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Annbd)).

For earlier reports on the same kind of situation, check out, e.g., https://github.com/dart-lang/sdk/issues/34058#issuecomment-409904758.

With that, I'll close this issue.

**Closed by eernstg** 2019-04-05 09:28 UTC
Labels: needs-info
