### ISSUE TITLE
With 'dart run', some arguments intended for the app are handled by the dart command

### ISSUE THREAD

**Issue by jsroest** [dart-lang/sdk#45173] opened 2021-03-03 11:47 UTC
`Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"`

I'm writing a command line interface (cli) app with dart. 

Command line options that the dart VM recognizes, like -h are not passed to the app.

The -i is passed to the app:
`dart run main.dart -i`
 
 The -h is handled by the dart command:
`dart run main.dart -h`

Output:
```
Run a Dart program.

Usage: dart run [arguments] <dart file | package target>
-h, --help                                             Print this usage information.
...
```
I would like that the arguments passed after "maint.dart" are passed to the app or a proxy parameter that proxies its contents as parameters to the app.

`dart run -app-args "-h -i" main.dart`

**Comment by jsroest** [comment] 2021-03-05 09:14
I would like to add the observation that the behavior of `dart run main.dart -h` is different from `dart main.dart -h`.
The old notation without 'run' **does** pass the -h to the app.

Passing the -h from Android Studio (Run/Debug configuration) is always catched by the dart vm, although it seems to use the old notation. It's really confusing.

**Comment by bkonyi** [comment] 2021-03-12 17:14
This is a duplicate of https://github.com/dart-lang/sdk/issues/43487 which has been resolved. @jsroest, can you upgrade to 2.12 and reopen if this is still an issue? Thanks!

**Closed by bkonyi** 2021-03-12 17:14 UTC
Labels: area-dart-cli
