### ISSUE TITLE
DDC Throws Error When Js Library Calls .constructor() on Dart Object

### ISSUE THREAD

**Issue by todbachman-wf** [dart-lang/sdk#36372] opened 2019-03-28 16:15 UTC
While updating an existing project to be compatible with Dart 2, I encountered an issue in DDC that I don't see in Dart2Js. The project I'm updating interoperates with a package written in Go that is transpiled to Javascript using gopherjs. In at least one situation, the core gopherjs code calls `.constructor()` on an array originating in Dart. In response, unfortunately, DDC throws: "Error: use `new List<int>.new(...)` to create a Dart object".

Running the same code using Dart2Js under Dart 2 it doesn't throw this error and behaves as it currently does in Dart 1 with Dart2Js and the Dart VM.

I am assuming this is the source of the error I'm seeing: [compiler.dart](https://github.com/dart-lang/sdk/blob/f0027dfea3a633d0d5d02cb01561452deb11bbb8/pkg/dev_compiler/lib/src/kernel/compiler.dart#L1579-L1587)

#### My Environment:
* Dart SDK Version: 2.2.0
* OS: MacOSX
* Browser: Chrome

**Comment by robbecker-wf** [comment] 2019-04-17 22:19
FYI @kevmoo this is a blocker to Workiva being able to use DDC.

**Comment by kevmoo** [comment] 2019-04-17 22:26
CC @jmesserly – we're going through a big refactor for how we run DDC.

Have you tried a recent dev build to see if it still happens?

**Comment by jmesserly** [comment] 2019-04-17 22:46
Could you share more details? It sounds like gopherjs is trying to use unsupported JS interop, but I'm not sure. In particular, this part:

> In at least one situation, the core gopherjs code calls .constructor() on an array originating in Dart.

Whether the code was working previously or not, calling `.constructor` on a Dart object is not supported; neither DDC or dart2js will work like a JS object in this case (because Dart objects do not have the same constructor semantics as JS objects). The only difference is that DDC throws an error about this invalid use. 

If the only type where gopherjs is calling `.constructor` is `List<T>`, we can fix that one.

For the Array specifically, you should be able to work around this by creating `List<dynamic>` and passing that to gopherjs. `List<dynamic>` is currently a raw JavaScript array (i.e. its prototype is `Array.prototype`), unlike other reified generics.

Regardless, we can fix `List<T>` in DDC to not use the dart:core Object `constructor` property. That was not intended behavior. Should be a 1-line fix to setExtensionBaseClass in DDC's runtime code.

**Comment by todbachman-wf** [comment] 2019-04-18 14:50
@jmesserly this is the code I was alluding to in gopherjs that calls `.constructor` on an array that originated in Dart:

https://github.com/gopherjs/gopherjs/blob/89baedc74dd74098df0c4ba8792e3cf6d722d4d0/compiler/prelude/prelude.go#L38-L44

When you say that dart2js also won't work in this situation, what is the result we can expect? We've been using gopherjs with Dart interop code in this way for at least a couple years and haven't run into any issues with this until now. Maybe we've just been lucky! 🤷‍♂️

**Comment by jmesserly** [comment] 2019-04-18 20:52
> When you say that dart2js also won't work in this situation, what is the result we can expect? 

The issue would be if gopherjs is using .constructor for Dart objects; dart2js/DDC don't use constructors the way JS expects. Looking at the code you linked, it appears that gopherjs only calls .constructor on Arrays, so that's okay.

**Comment by robbecker-wf** [comment] 2019-04-18 23:14
Is it possible to get a fix for this into dart 2.3? I'm concerned that we don't have a workaround except to use dart2js for running tests and developing.

**Comment by jmesserly** [comment] 2019-04-19 18:46
> Is it possible to get a fix for this into dart 2.3? I'm concerned that we don't have a workaround except to use dart2js for running tests and developing.

you should be able to workaround it by passing `List<dynamic>` instead of `List<int>` to Go. Will that work for you?

**Comment by jmesserly** [comment] 2019-04-19 22:20
I'm testing a fix: https://dart-review.googlesource.com/c/sdk/+/99940

@kevmoo would know whether this can be cherry picked into 2.3; I'm not sure if it's too late or not. (it's a very low risk fix, so that helps)

**Comment by kevmoo** [comment] 2019-04-19 22:33
I'm a fan of low-risk fixes that fix customer issues..

Thoughts? @vsmenon @aadilmaan @dgrove

**Comment by vsmenon** [comment] 2019-04-19 23:01
sgtm

We can cherry-pick to 2.3.  It may not make it into Flutter's version, but I think that's okay.

**Comment by aadilmaan** [comment] 2019-04-19 23:08
Agree with Vijay.

**Closed** 2019-04-22 22:45 UTC
Labels: area-dev-compiler

**Comment by todbachman-wf** [comment] 2019-04-22 22:51
🎉 Thank you!

**Comment by jmesserly** [comment] 2019-04-22 22:53
fyi, requested a cherry pick at https://github.com/dart-lang/sdk/issues/36701

**Comment by aadilmaan** [comment] 2019-04-22 22:56
Added to Dart 2.3 milestone.
