### ISSUE TITLE
meta package: @debug annotation

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#28113] opened 2016-12-14 22:59 UTC
I'd like a `@debug` annotation that would produce an analysis warning anywhere the annotated API was referred to. This would be useful for APIs that are only intended to aid in debugging but should never appear in production code—for example, [this `debug()` method](https://github.com/sass/dart-sass/blob/master/lib/src/parse/parser.dart#L500-L510) that prints the current location in the document being parsed.

**Comment by zoechi** [comment] 2017-02-17 07:14
Seems to me quite similar to `@visibleForTesting`. Is it really worth an additional annotation?

**Comment by nex3** [comment] 2017-02-17 21:27
What are the circumstances under which the analyzer will warn for `@visibleForTesting`?

**Comment by zoechi** [comment] 2017-02-17 21:51
AFAIK when it's referenced by code outside the `test` directory.

**Comment by nex3** [comment] 2017-02-17 21:54
Does that include code within the same package?

**Comment by zoechi** [comment] 2017-02-18 13:00
https://github.com/dart-lang/linter/issues/311#issuecomment-254636696

**Comment by nex3** [comment] 2017-02-21 22:20
According to that comment thread, `@visibleForTesting` *doesn't* produce a warning when the member is used within the current library. I want a warning any time the member is used anywhere.

**Comment by matanlurey** [comment] 2017-02-22 00:20
+1 for this. This is meaningfully different from `@visibleForTesting`, and I'd use it a lot when writing framework-level code - i.e. here is a function to dump the state of a component - don't use it in production or even check-it in though.

**Comment by zoechi** [comment] 2017-02-22 07:33
@nex3 the comment I linked to above says that the analyzer doesn't yet produce a warning at all.

@matanlurey the only difference to `@visibleForTesting` I see is, that `@debug` should also not be used in tests. Do you see others?

**Comment by IchordeDionysos** [comment] 2020-02-26 23:04
@zoechi `@visibleForTesting` won't warn the user if he uses the function inside the same file/class 🤔 
Which I understand is also expected.

**Comment by yjbanov** [comment] 2024-03-27 18:05
This would be quite useful in Flutter. Flutter uses, re-exports, and defines a number of APIs that are only meant to be used while manually debugging you code, but should not be submitted. A few examples:

- `solo` (from `package:test`, both used and re-exported through Flutter Driver tests).
- A number of `debugDump*` [functions](https://api.flutter.dev/flutter/search.html?q=debugDump).
- A number of `debugPrint*` [functions](https://api.flutter.dev/flutter/search.html?q=debugPrint).

Some of these are OK to use in tests, so one small enhancement I'd like to make to this proposal is to support `@Debug(allowedInTests: true)`, although many are not appropriate even for tests (`solo`, `debugDumpLayerTree`, etc). If someone really insists on using those in tests, then opting out using `// ignore:` is a fine workaround.

Note that `solo` today uses the `@Deprecated` annotation. This causes issues. "Deprecation" is the wrong semantic for `solo`. Typically deprecation permits a period of time during which it is OK to use deprecated APIs. However, leaving a `solo: true` in your tests is almost certainly a bug (which [did happen in Flutter](https://github.com/flutter/engine/pull/51695/files#diff-d1c49969c46cc8f90769762bb9b5cf01615246ec8670202a174326db9069b555) recently).

**Comment by natebosch** [comment] 2024-03-27 18:21
I think it sounds like a good idea to have an alternative to`@deprecated`. I'm in favor of making it easier to treat deprecated API use as less severe than checking in debug API use.

Do we have a concrete proposal for which use locations (same library, same package, same package tests, different package tests...) would be flagged or ignored?

There is a mention about these API being OK to use, but not check in to source control. Do we plan to always surface the diagnostic, including in the IDE, or do we need to invent non-transient diagnostics to get value out of this?

How often do we expect this diagnostic to need to be suppressed? If we expect many false positives I'd be worried if an `// ignore` is the only way to silence it.

**Comment by matanlurey** [comment] 2024-03-27 18:26
I'd love to start with something simple, i.e. `@doNotSubmit`. It is unambiguous, it should never be submitted (and can fail analysis 100% of the time). In fact, we could even say it is impossible to ignore (but I don't know if that is necessary).

I suspect that's what we'd use on `solo: ...`.

**Comment by yjbanov** [comment] 2024-03-27 18:31
I don't see much value in same library/package/package tests use-cases. The biggest and clearest value is in marking public API to be used widely outside the package where the API is defined. The only dimension along which I see some value is production vs test code. This is because test code can be viewed as a kind of "debug" code. However, to keep things simple we could start with just an annotation that forbids any kind of submitting during CI (i.e. enforced by the analyzer but not compiler). Later we can expand it with scoping parameters, such as `allowedInTests`, based on user feedback (e.g. users find that they need to suppress it too often).

I vote to always surface it like a normal lint (IDE, `dart analyze`).

**Comment by natebosch** [comment] 2024-03-27 18:31
> In fact, we could even say it is impossible to ignore

I think we'd want an escape hatch, otherwise we need an extra step if we want to run a solo test on CI for an issue we can't repro locally. Our typical external CI setup runs analysis as a precondition to running tests.

**Comment by yjbanov** [comment] 2024-03-27 18:32
To be usable widely it should be ignorable, and the existing `//ignore` directive is a fine well-understood method.

**Comment by matanlurey** [comment] 2024-03-27 18:33
Works for me

**Comment by yjbanov** [comment] 2024-03-27 18:35
> I'd love to start with something simple, i.e. @doNotSubmit.

I do like the `@DoNotSubmit` naming. That's ultimately the effect we're looking for. Just because an API is meant for debugging does not automatically imply that it should not be submitted. We write and submit plenty of debug code.

**Comment by mdebbar** [comment] 2024-03-27 18:43
The way I see it is there is a difference between `Debug` and `DoNotSubmit` (they are not mutually exclusive though).

`Debug` basically means this piece of code shouldn't make it into a release build. It can be submitted. It can only be referenced from other `Debug` code.

`DoNotSubmit` is simpler. No references allowed at all (maybe with an escape hatch like @natebosch suggested, but I worry that the escape hatch will defeat the purpose; and such code may end up being submitted).

**Comment by natebosch** [comment] 2024-03-27 18:46
What about using a debug API within a debug API?

I strongly prefer not to rely on `// ignore` unless we are confident the false positive rate is very low. For CI escape hatch etc I'm happy with `// ignore`.

If it's common for authors to write their own debugging tools which wrap these API, I would prefer for them to not need permanent `// ignore` comments.

**Comment by eyebrowsoffire** [comment] 2024-03-27 19:32
> Our typical external CI setup runs analysis as a precondition to running tests.
That seems wrong to me, particularly for analysis warnings. There's no reason they should prevent tests from running. After all, if one test fails you still run the remaining tests, right? CI should give as much rich failure information as possible on a given run.

**Comment by natebosch** [comment] 2024-03-27 20:35
> no reason

IIRC the primary historical reason was saving CI resources. I'm not sure if we've had a concrete discussion since then about whether CI time is still scarce enough to gate tests on analysis.

In bazel tests are gated on analysis because analysis is part of the library target, which is a dependency of the test target. Internally though I think we have other easier ways to run tests in exactly the CI environment while allowing analysis errors. Externally it's always source edit and a push to run tests in CI environment.

**Comment by natebosch** [comment] 2024-03-27 20:45
Would debug API usage be better checked at compile time depending on whether it's outputting a production vs development binary? There are already some notions of dev vs production compiles in various tools, but we might need a large effort to unify them if we wanted to define this type of behavior. This wouldn't solve the `solo` case well, but would it work for `debug*()` methods?

**Comment by yjbanov** [comment] 2024-03-29 21:10
@mdebbar 

Debug meaning not in production vs DoNotSubmit meaning not in the source repository makes sense. I'm now even more convinced that DoNotSubmit is the better naming option.

@natebosch 

Debug-within-debug: I think I would not take it this far. This can be partially addressed by having the reusable debug functionality be private, such that the public debug function can freely call the private debug function and not need an escape hatch. But if a public debug function absolutely must call another public debug function, I think `//ignore` is acceptable. This can be improved over time based on real world feedback. I don't think we'd be painting ourselves into a corner by starting simple.

> analysis as a precondition to running tests

I agree with @eyebrowsoffire that this is a strange choice. After all, debug APIs should be usable for debugging tests on CI. Frequently issues are only reproducible on CI, not locally. The CI should allow running code with all sorts of lints, hints, and warnings.

> Would debug API usage be better checked at compile time depending on whether the compiler is outputting a production vs development binary?

It should always be checked, in IDEs, in `dart analyze`, and may even by the compiler for extra bonus points (but _not crash_ the compiler! See the CI discussion above). The reason to always surface it is to make sure the developer is constantly aware that they are using an API that's not meant to be submitted. Otherwise, you may spend a full day on a feature accidentally designed around an API, just to find out last minute that you cannot actually use it.

And yes, if the solution doesn't work for `solo`, then it defeats the purpose.

**Comment by matanlurey** [comment] 2024-03-29 21:29
I am going to try adding the `@doNotSubmit` annotation :)

**Comment by bwilkerson** [comment] 2024-03-29 22:00
If we want compilers to handle this, then we ought to ping the CFE team (@johnniwinther ) to see what input they might have. For example, they might prefer to use a `@pragma` over an annotation declared in `package:meta`.

**Comment by matanlurey** [comment] 2024-03-29 23:05
@yjbanov Humor me, how is `@doNotSubmit` meaningfully different than `@visibleForTesting`?

Imagine you had an API like so:

```dart
void test(
  String name,
  void Function() testFunction, {
  @doNotSubmit bool skip = false,
}) { /* ... */ }
```

Of course, you want this annotation to do _something_, so you can't lint this:

```dart
void test(
  String name,
  void Function() testFunction, {
  @doNotSubmit bool skip = false,
}) {
  // No lint, otherwise it's impossible for "skip" to do anything!
  if (skip) return;
}
```

It might also be reasonable to access `@doNotSubmit`-annotated elements elsewhere (i.e. in the same library), really what you're trying to do is say "this is public, but don't check this in, ok?". If so, it's (basically) the same as `@visibleForTesting`, except perhaps you want a different diagnostic text.

LMK!

**Comment by eyebrowsoffire** [comment] 2024-03-29 23:14
@matanlurey I think in your example, the expectation is that no clients pass `skip` into the function, not that the function itself doesn't use the argument. At least that's what I would want out of the API.

**Comment by matanlurey** [comment] 2024-03-29 23:35
Yeah and Sam also mentioned `visibleForTesting` has other allowances. Ok sold me!

**Comment by srawlins** [comment] 2024-03-30 00:24
Regarding calling a `@doNotSubmit` API from within a `@doNotSubmit` API, I vote that it be allowed.

This is the model behind `@deprecated`. If you have two APIs, and you're deprecating them, like this:

```dart
@deprecated
List<User> getUsers => ...;

@deprecated
User getBestUser => getUsers.sort( /* complicated internal sorting method */ ).first;
```

We don't complain that deprecated APIs are called from within deprecated APIs.

I suggest we do the same for `@doNotSubmit`:

```dart
test(callback, {@doNotSubmit solo = false}) { ... }

testTwice(callback, count, {@doNotSubmit solo = false}) =>
  // Hmm... trickier than I was thinking, but somehow detect that `solo` is already `@doNotSubmit`?
  for (i = 0; i < count; i++) test(callback, solo: solo);
```

If this adds a lot of complexity, and bugs, then we can keep it simple.

**Comment by matanlurey** [comment] 2024-03-30 00:31
I might need a pointer on how to implement that (https://dart-review.googlesource.com/c/sdk/+/360481) but makes sense to me.

**Comment by matanlurey** [comment] 2024-04-01 17:52
Coming back to this, I am going to make the following changes to the definition of `@doNotSubmit` based on feedback and ease of initial implementation:

1. Members annotated with `@doNotSubmit` can freely access other `@doNotSubmit` members.
2. Classes and types in general _cannot_ be annotated (this opens a can of worms, is not useful)
3. It's valid to access a parameter annotated with `@doNotSubmit` from the method itself.

**Comment by johnniwinther** [comment] 2024-04-02 07:01
@bwilkerson If the CFE wants to support this (which it might not, given that this is for warnings only) it doesn't make a huge difference where the annotation is declared. We evaluate the constants as the last part of the compilation so we might also be limited in how well we can use this given that the AST at this point is not tightly coupled to the source syntax.

**Comment by yjbanov** [comment] 2024-04-03 17:35
@matanlurey Should this be closed? Your CL has landed.

**Comment by yjbanov** [comment] 2024-04-03 17:44
I'd say that your fix it good enough to close this issue. For extra nuances we could file new issues that would be more focused. I'm skeptical that this issue would be effective at helping figure out any extra features. But it's up to you.

**Comment by matanlurey** [comment] 2024-04-03 18:48
Ditto. I'm closing for now.

**Closed by matanlurey** 2024-04-03 18:48 UTC
Labels: area-analyzer, P2, type-enhancement, analyzer-pkg-meta
