### ISSUE TITLE
Timeouts on simarm64 on Windows

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30850] opened 2017-09-21 09:01 UTC
The language/positional_parameters_type_test/none test flaked on simarm64 with a timeout.
Previous runs didn't show the test as slow.

https://build.chromium.org/p/client.dart/builders/vm-precomp-win-simarm64-2-4-be/builds/2649/steps/test%20vm/logs/stdio

```
FAILED: precompiler-dart_precompiled release_simarm64 language/positional_parameters_type_test/none
Expected: Pass 
Actual: Timeout
CommandOutput[precompiler]:
diagnostics: Using E:\b\depot_tools\win_toolchain\vs_files\d5dc33b15d1b2c086f2f6632e2fd15882f80dbd3\win_sdk\Debuggers\x64\cdb.exe to print stack traces
    Process list including children: [2268]
    Trying to capture stack trace for pid 2268
    
    Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
    Copyright (c) Microsoft Corporation. All rights reserved.
    
    *** wait with pending attach
    Symbol search path is: srv*
    Executable search path is: 
    ModLoad: 00000001`3f3e0000 00000001`3fde1000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
    ModLoad: 00000000`76da0000 00000000`76f48000   C:\Windows\SYSTEM32\ntdll.dll
    ModLoad: 00000000`76c80000 00000000`76d9f000   C:\Windows\system32\kernel32.dll
    ModLoad: 000007fe`fce80000 000007fe`fceec000   C:\Windows\system32\KERNELBASE.dll
    ModLoad: 000007fe`fa3c0000 000007fe`fa3e7000   C:\Windows\system32\IPHLPAPI.DLL
    ModLoad: 000007fe`fdc90000 000007fe`fdd2f000   C:\Windows\system32\msvcrt.dll
    ModLoad: 000007fe`fd4b0000 000007fe`fd4b8000   C:\Windows\system32\NSI.dll
    ModLoad: 000007fe`fa3a0000 000007fe`fa3ab000   C:\Windows\system32\WINNSI.DLL
    ModLoad: 000007fe`fee80000 000007fe`fefad000   C:\Windows\system32\RPCRT4.dll
    ModLoad: 00000000`76f60000 00000000`76f67000   C:\Windows\system32\PSAPI.DLL
    ModLoad: 000007fe`fdc40000 000007fe`fdc8d000   C:\Windows\system32\WS2_32.dll
    ModLoad: 000007fe`fefb0000 000007fe`ff08b000   C:\Windows\system32\ADVAPI32.dll
    ModLoad: 000007fe`ff090000 000007fe`ff0af000   C:\Windows\SYSTEM32\sechost.dll
    ModLoad: 000007fe`fdfb0000 000007fe`fed39000   C:\Windows\system32\SHELL32.dll
    ModLoad: 000007fe`fddf0000 000007fe`fde61000   C:\Windows\system32\SHLWAPI.dll
    ModLoad: 000007fe`fee10000 000007fe`fee77000   C:\Windows\system32\GDI32.dll
    ModLoad: 00000000`76b80000 00000000`76c7a000   C:\Windows\system32\USER32.dll
    ModLoad: 000007fe`fd4a0000 000007fe`fd4ae000   C:\Windows\system32\LPK.dll
    ModLoad: 000007fe`fed40000 000007fe`fee09000   C:\Windows\system32\USP10.dll
    ModLoad: 000007fe`f54a0000 000007fe`f55c5000   C:\Windows\system32\dbghelp.dll
    ModLoad: 000007fe`fd170000 000007fe`fd19e000   C:\Windows\system32\IMM32.DLL
    ModLoad: 000007fe`fdb30000 000007fe`fdc39000   C:\Windows\system32\MSCTF.dll
    ModLoad: 000007fe`f8800000 000007fe`f8803000   C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
    ModLoad: 000007fe`fca00000 000007fe`fca0f000   C:\Windows\system32\cryptbase.dll
    (8dc.b04): Break instruction exception - code 80000003 (first chance)
    ntdll!DbgBreakPoint:
    00000000`76dece10 cc              int     3
    0:004> cdb: Reading initial command '!uniqstack;qd'
    Processing 5 threads, please wait
    *** WARNING: Unable to verify checksum for E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
    
    .  0  Id: 8dc.e50 Suspend: 1 Teb: 000007ff`fffde000 Unfrozen
          Start: dart_bootstrap!mainCRTStartup (00000001`3f79386c)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`001edc88 000007fe`fce810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`001edc90 00000001`3f5a6daf KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`001edd30 00000001`3f51dbda dart_bootstrap!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
    (Inline Function) --------`-------- dart_bootstrap!dart::ThreadBarrier::Sync+0x31
    00000000`001edd70 00000001`3f5a8f42 dart_bootstrap!dart::GCMarker::MarkObjects+0x46a
    00000000`001ee850 00000001`3f5200aa dart_bootstrap!dart::PageSpace::MarkSweep+0x252
    00000000`001ee980 00000001`3f654e57 dart_bootstrap!dart::Heap::CollectOldSpaceGarbage+0xaa
    00000000`001eea20 00000001`3f671558 dart_bootstrap!dart::Symbols::Compact+0x57
    00000000`001eeb10 00000001`3f6708e6 dart_bootstrap!dart::Precompiler::DoCompileAll+0x408
    00000000`001ef480 00000001`3f783a53 dart_bootstrap!dart::Precompiler::CompileAll+0xa6
    00000000`001ef980 00000001`3f3ea6fc dart_bootstrap!Dart_Precompile+0x1f3
    00000000`001efa70 00000001`3f3eb344 dart_bootstrap!dart::bin::RunMainIsolate+0x2dc
    00000000`001efb60 00000001`3f3eb509 dart_bootstrap!dart::bin::main+0x424
    00000000`001efc90 00000001`3f793811 dart_bootstrap!main+0x9
    (Inline Function) --------`-------- dart_bootstrap!invoke_main+0x22
    00000000`001efcc0 00000000`76c959cd dart_bootstrap!__scrt_common_main_seh+0x11d
    00000000`001efd00 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`001efd30 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  1  Id: 8dc.960 Suspend: 1 Teb: 000007ff`fffdc000 Unfrozen
          Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f79c9fc)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`01f1f9e8 000007fe`fce816ad ntdll!NtRemoveIoCompletion+0xa
    00000000`01f1f9f0 00000000`76c89981 KERNELBASE!GetQueuedCompletionStatus+0x39
    00000000`01f1fa50 00000001`3f3f17bc kernel32!GetQueuedCompletionStatusStub+0x11
    00000000`01f1fa90 00000001`3f40eba5 dart_bootstrap!dart::bin::EventHandlerImplementation::EventHandlerEntry+0xcc
    00000000`01f1fb10 00000001`3f79ca59 dart_bootstrap!dart::bin::ThreadEntry+0x25
    (Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xe
    00000000`01f1fb40 00000000`76c959cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`01f1fb70 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`01f1fba0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  2  Id: 8dc.fcc Suspend: 1 Teb: 000007ff`fffda000 Unfrozen
          Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f79c9fc)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`024eec68 000007fe`fce810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`024eec70 00000001`3f5a6daf KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`024eed10 00000001`3f51e2ca dart_bootstrap!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
    (Inline Function) --------`-------- dart_bootstrap!dart::ThreadBarrier::Sync+0x27
    00000000`024eed50 00000001`3f65a789 dart_bootstrap!dart::MarkTask::Run+0x2ba
    00000000`024ef710 00000001`3f65a8c2 dart_bootstrap!dart::ThreadPool::Worker::Loop+0x39
    00000000`024ef740 00000001`3f5a6bc4 dart_bootstrap!dart::ThreadPool::Worker::Main+0x72
    00000000`024ef770 00000001`3f79ca59 dart_bootstrap!dart::ThreadEntry+0x54
    (Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xe
    00000000`024ef7a0 00000000`76c959cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`024ef7d0 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`024ef800 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  3  Id: 8dc.e6c Suspend: 1 Teb: 000007ff`fffd8000 Unfrozen
          Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f79c9fc)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`0579edb8 000007fe`fce810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`0579edc0 00000001`3f5a6daf KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`0579ee60 00000001`3f51e47a dart_bootstrap!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
    00000000`0579eea0 00000001`3f51e305 dart_bootstrap!dart::ThreadBarrier::Sync+0x3a
    00000000`0579eed0 00000001`3f65a789 dart_bootstrap!dart::MarkTask::Run+0x2f5
    00000000`0579f890 00000001`3f65a8c2 dart_bootstrap!dart::ThreadPool::Worker::Loop+0x39
    00000000`0579f8c0 00000001`3f5a6bc4 dart_bootstrap!dart::ThreadPool::Worker::Main+0x72
    00000000`0579f8f0 00000001`3f79ca59 dart_bootstrap!dart::ThreadEntry+0x54
    (Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xe
    00000000`0579f920 00000000`76c959cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`0579f950 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`0579f980 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  4  Id: 8dc.b04 Suspend: 1 Teb: 000007ff`fffd6000 Unfrozen
          Start: ntdll!DbgUiRemoteBreakin (00000000`76e93760)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`0ec0faa8 00000000`76e93798 ntdll!DbgBreakPoint
    00000000`0ec0fab0 00000000`76c959cd ntdll!DbgUiRemoteBreakin+0x38
    00000000`0ec0fae0 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`0ec0fb10 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    Total threads: 5
    quit:
    
    

Command[precompiler]: set DART_CONFIGURATION=ReleaseSIMARM64 & out\ReleaseSIMARM64\dart_bootstrap --snapshot-kind=app-aot --snapshot=E:/b/build/slave/vm-precomp-win-simarm64-2-4-be/build/sdk/out/ReleaseSIMARM64/generated_compilations/precompiler/multitest_language_positional_parameters_type_test_none/out.aotsnapshot --use-blobs --checked --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\.packages E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\generated_tests\language\positional_parameters_type_test_none.dart
Took 0:08:09.855000

Command[vm]: set DART_CONFIGURATION=ReleaseSIMARM64 & out\ReleaseSIMARM64\dart_precompiled_runtime.exe --checked --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\.packages E:/b/build/slave/vm-precomp-win-simarm64-2-4-be/build/sdk/out/ReleaseSIMARM64/generated_compilations/precompiler/multitest_language_positional_parameters_type_test_none/out.aotsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -m release -c precompiler -r dart_precompiled -a simarm64 --use-blobs language/positional_parameters_type_test/none
```

**Comment by floitschG** [comment] 2017-09-21 09:05
Same for co19/Language/Statements/Continue/async_loops_t05.

https://build.chromium.org/p/client.dart/builders/vm-precomp-win-simarm64-2-4-be/builds/2650/steps/test%20vm/logs/stdio

```
FAILED: precompiler-dart_precompiled release_simarm64 co19/Language/Statements/Continue/async_loops_t05
Expected: Pass 
Actual: Timeout
CommandOutput[precompiler]:
diagnostics: Using E:\b\depot_tools\win_toolchain\vs_files\d5dc33b15d1b2c086f2f6632e2fd15882f80dbd3\win_sdk\Debuggers\x64\cdb.exe to print stack traces
    Process list including children: [196]
    Trying to capture stack trace for pid 196
    
    Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
    Copyright (c) Microsoft Corporation. All rights reserved.
    
    *** wait with pending attach
    Symbol search path is: srv*
    Executable search path is: 
    ModLoad: 00000001`3f410000 00000001`3fe11000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
    ModLoad: 00000000`76da0000 00000000`76f48000   C:\Windows\SYSTEM32\ntdll.dll
    ModLoad: 00000000`76c80000 00000000`76d9f000   C:\Windows\system32\kernel32.dll
    ModLoad: 000007fe`fce80000 000007fe`fceec000   C:\Windows\system32\KERNELBASE.dll
    ModLoad: 000007fe`fa3c0000 000007fe`fa3e7000   C:\Windows\system32\IPHLPAPI.DLL
    ModLoad: 000007fe`fdc90000 000007fe`fdd2f000   C:\Windows\system32\msvcrt.dll
    ModLoad: 000007fe`fd4b0000 000007fe`fd4b8000   C:\Windows\system32\NSI.dll
    ModLoad: 000007fe`fa3a0000 000007fe`fa3ab000   C:\Windows\system32\WINNSI.DLL
    ModLoad: 000007fe`fee80000 000007fe`fefad000   C:\Windows\system32\RPCRT4.dll
    ModLoad: 00000000`76f60000 00000000`76f67000   C:\Windows\system32\PSAPI.DLL
    ModLoad: 000007fe`fdc40000 000007fe`fdc8d000   C:\Windows\system32\WS2_32.dll
    ModLoad: 000007fe`fefb0000 000007fe`ff08b000   C:\Windows\system32\ADVAPI32.dll
    ModLoad: 000007fe`ff090000 000007fe`ff0af000   C:\Windows\SYSTEM32\sechost.dll
    ModLoad: 000007fe`fdfb0000 000007fe`fed39000   C:\Windows\system32\SHELL32.dll
    ModLoad: 000007fe`fddf0000 000007fe`fde61000   C:\Windows\system32\SHLWAPI.dll
    ModLoad: 000007fe`fee10000 000007fe`fee77000   C:\Windows\system32\GDI32.dll
    ModLoad: 00000000`76b80000 00000000`76c7a000   C:\Windows\system32\USER32.dll
    ModLoad: 000007fe`fd4a0000 000007fe`fd4ae000   C:\Windows\system32\LPK.dll
    ModLoad: 000007fe`fed40000 000007fe`fee09000   C:\Windows\system32\USP10.dll
    ModLoad: 000007fe`f54a0000 000007fe`f55c5000   C:\Windows\system32\dbghelp.dll
    ModLoad: 000007fe`fd170000 000007fe`fd19e000   C:\Windows\system32\IMM32.DLL
    ModLoad: 000007fe`fdb30000 000007fe`fdc39000   C:\Windows\system32\MSCTF.dll
    ModLoad: 000007fe`f8840000 000007fe`f8843000   C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
    ModLoad: 000007fe`fca00000 000007fe`fca0f000   C:\Windows\system32\cryptbase.dll
    (c4.d84): Break instruction exception - code 80000003 (first chance)
    ntdll!DbgBreakPoint:
    00000000`76dece10 cc              int     3
    0:003> cdb: Reading initial command '!uniqstack;qd'
    Processing 4 threads, please wait
    *** WARNING: Unable to verify checksum for E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
    
    .  0  Id: c4.124c Suspend: 1 Teb: 000007ff`fffdd000 Unfrozen
          Start: dart_bootstrap!mainCRTStartup (00000001`3f7c386c)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`0031de48 000007fe`fce810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`0031de50 00000001`3f5d6daf KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`0031def0 00000001`3f54dc6e dart_bootstrap!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
    (Inline Function) --------`-------- dart_bootstrap!dart::ThreadBarrier::{dtor}+0x1e
    00000000`0031df30 00000001`3f5d8f42 dart_bootstrap!dart::GCMarker::MarkObjects+0x4fe
    00000000`0031ea10 00000001`3f5500aa dart_bootstrap!dart::PageSpace::MarkSweep+0x252
    00000000`0031eb40 00000001`3f684e57 dart_bootstrap!dart::Heap::CollectOldSpaceGarbage+0xaa
    00000000`0031ebe0 00000001`3f6a1558 dart_bootstrap!dart::Symbols::Compact+0x57
    00000000`0031ecd0 00000001`3f6a08e6 dart_bootstrap!dart::Precompiler::DoCompileAll+0x408
    00000000`0031f640 00000001`3f7b3a53 dart_bootstrap!dart::Precompiler::CompileAll+0xa6
    00000000`0031fb40 00000001`3f41a6fc dart_bootstrap!Dart_Precompile+0x1f3
    00000000`0031fc30 00000001`3f41b344 dart_bootstrap!dart::bin::RunMainIsolate+0x2dc
    00000000`0031fd20 00000001`3f41b509 dart_bootstrap!dart::bin::main+0x424
    00000000`0031fe50 00000001`3f7c3811 dart_bootstrap!main+0x9
    (Inline Function) --------`-------- dart_bootstrap!invoke_main+0x22
    00000000`0031fe80 00000000`76c959cd dart_bootstrap!__scrt_common_main_seh+0x11d
    00000000`0031fec0 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`0031fef0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  1  Id: c4.5b0 Suspend: 1 Teb: 000007ff`fffdb000 Unfrozen
          Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f7cc9fc)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`020cf7c8 000007fe`fce816ad ntdll!NtRemoveIoCompletion+0xa
    00000000`020cf7d0 00000000`76c89981 KERNELBASE!GetQueuedCompletionStatus+0x39
    00000000`020cf830 00000001`3f4217bc kernel32!GetQueuedCompletionStatusStub+0x11
    00000000`020cf870 00000001`3f43eba5 dart_bootstrap!dart::bin::EventHandlerImplementation::EventHandlerEntry+0xcc
    00000000`020cf8f0 00000001`3f7cca59 dart_bootstrap!dart::bin::ThreadEntry+0x25
    (Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xe
    00000000`020cf920 00000000`76c959cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`020cf950 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`020cf980 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  2  Id: c4.10a0 Suspend: 1 Teb: 000007ff`fffd9000 Unfrozen
          Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f7cc9fc)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`0c93f0d8 000007fe`fce810dc ntdll!ZwWaitForSingleObject+0xa
    00000000`0c93f0e0 00000001`3f5d6daf KERNELBASE!WaitForSingleObjectEx+0x79
    00000000`0c93f180 00000001`3f54e47a dart_bootstrap!dart::Monitor::Wait+0x6f
    (Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
    00000000`0c93f1c0 00000001`3f54e305 dart_bootstrap!dart::ThreadBarrier::Sync+0x3a
    00000000`0c93f1f0 00000001`3f68a789 dart_bootstrap!dart::MarkTask::Run+0x2f5
    00000000`0c93fbb0 00000001`3f68a8c2 dart_bootstrap!dart::ThreadPool::Worker::Loop+0x39
    00000000`0c93fbe0 00000001`3f5d6bc4 dart_bootstrap!dart::ThreadPool::Worker::Main+0x72
    00000000`0c93fc10 00000001`3f7cca59 dart_bootstrap!dart::ThreadEntry+0x54
    (Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xe
    00000000`0c93fc40 00000000`76c959cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x5d
    00000000`0c93fc70 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`0c93fca0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    .  3  Id: c4.d84 Suspend: 1 Teb: 000007ff`fffd7000 Unfrozen
          Start: ntdll!DbgUiRemoteBreakin (00000000`76e93760)
          Priority: 0  Priority class: 32  Affinity: ff
    Child-SP          RetAddr           Call Site
    00000000`0c7afcf8 00000000`76e93798 ntdll!DbgBreakPoint
    00000000`0c7afd00 00000000`76c959cd ntdll!DbgUiRemoteBreakin+0x38
    00000000`0c7afd30 00000000`76dcb891 kernel32!BaseThreadInitThunk+0xd
    00000000`0c7afd60 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
    
    Total threads: 4
    quit:
    
    

Command[precompiler]: set DART_CONFIGURATION=ReleaseSIMARM64 & out\ReleaseSIMARM64\dart_bootstrap --snapshot-kind=app-aot --snapshot=E:/b/build/slave/vm-precomp-win-simarm64-2-4-be/build/sdk/out/ReleaseSIMARM64/generated_compilations/precompiler/short4088_ments_Continue_async_loops_t05/out.aotsnapshot --use-blobs --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\.packages E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\tests\co19\src\Language\Statements\Continue\async_loops_t05.dart
Took 0:08:01.060101

Command[vm]: set DART_CONFIGURATION=ReleaseSIMARM64 & out\ReleaseSIMARM64\dart_precompiled_runtime.exe --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\.packages E:/b/build/slave/vm-precomp-win-simarm64-2-4-be/build/sdk/out/ReleaseSIMARM64/generated_compilations/precompiler/short4088_ments_Continue_async_loops_t05/out.aotsnapshot
Did not run

Short reproduction command (experimental):
    python tools/test.py -m release -c precompiler -r dart_precompiled -a simarm64 --use-blobs co19/Language/Statements/Continue/async_loops_t05
```

**Comment by floitschG** [comment] 2017-09-21 09:06
Another timeout on simarm64: language_2/mixin_with_two_implicit_constructors_test

https://build.chromium.org/p/client.dart/builders/vm-precomp-win-simarm64-1-4-be/builds/2890/steps/test%20vm/logs/stdio

```
FAILED: precompiler-dart_precompiled release_simarm64 language_2/mixin_with_two_implicit_constructors_test
Expected: MissingCompileTimeError 
Actual: Timeout
CommandOutput[precompiler]:
diagnostics: Using E:\b\depot_tools\win_toolchain\vs_files\d5dc33b15d1b2c086f2f6632e2fd15882f80dbd3\win_sdk\Debuggers\x64\cdb.exe to print stack traces
    Process list including children: [4696]
    Trying to capture stack trace for pid 4696
    
    

Command[precompiler]: set DART_CONFIGURATION=ReleaseSIMARM64 & out\ReleaseSIMARM64\dart_bootstrap --snapshot-kind=app-aot --snapshot=E:/b/build/slave/vm-precomp-win-simarm64-1-4-be/build/sdk/out/ReleaseSIMARM64/generated_compilations/precompiler/tests_language_2_mixin_with_two_implicit_constructors_test/out.aotsnapshot --use-blobs --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-precomp-win-simarm64-1-4-be\build\sdk\.packages E:\b\build\slave\vm-precomp-win-simarm64-1-4-be\build\sdk\tests\language_2\mixin_with_two_implicit_constructors_test.dart
Took 0:08:01.265122

Short reproduction command (experimental):
    python tools/test.py -m release -c precompiler -r dart_precompiled -a simarm64 --use-blobs language_2/mixin_with_two_implicit_constructors_test
```

**Comment by zanderso** [comment] 2017-09-21 14:49
This looks like it might be a real crash that is being hidden by a misconfiguration of crash reporting, or something along those lines. I'll try to find out more.

**Comment by mraleph** [comment] 2017-11-14 15:48
Duplicate of #29261

**Closed** 2017-11-14 15:48 UTC
Labels: area-vm, gardening, os-windows
