### ISSUE TITLE
Deferred Loading support with kernel

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#28335] opened 2017-01-11 13:43 UTC
/cc @kmillikin & #28263

**Comment by nex3** [comment] 2017-03-10 00:01
@kmillikin I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by mraleph** [comment] 2017-03-27 10:42
Removing the gardening issue because this is not gardening related.

**Comment by sigmundch** [comment] 2018-01-18 17:55
closing as a dupe of #30273

**Closed by sigmundch** 2018-01-18 17:55 UTC
Labels: area-kernel
