### ISSUE TITLE
Add debug support for ffi

### ISSUE THREAD

**Issue by bsutton** [dart-lang/sdk#46266] opened 2021-06-04 22:08 UTC
I originally raised this issue against the dart-code project:
https://github.com/Dart-Code/Dart-Code/issues/3360

@DanTup suggested I raise this issue here and mention @dcharkes 

I'm writing dart code which calls into the windows registry. via calls such as RegGetValue. using ffi.

In order to do this I need to calloc memory and copy values into that memory.

When debugging the code vscode only shows the address of the calloc memory.

It would be really useful if you could examine the memory so that I can check that I've correctly copied values
into memory or the contents of memory after an ffi call returns.

Ideally this would use the type of the variable to determine how to display the memory (e.g. utf16 vs int16)
It would also be useful if the debugger recognized declared structs so memory could be examined through the lens of the struct.
It would also be useful to be able to select the type used to decode the memory.
An example is that you often calloc memory as utf16 but then convert it to Uint16.
So ideally you want to be able to switch the memory decoder used.

**Comment by dcharkes** [comment] 2021-06-07 07:13
Hi @bsutton!

My setup so far has been to add `toString` implementations to structs and invoke those from the Dart debugger when executing Dart code and manipulating memory. But mostly, I run the native C/C++ debugger on the Dart executable, that way I can step through executing C/C++ functions.

>It would be really useful if you could examine the memory so that I can check that I've correctly copied values
into memory or the contents of memory after an ffi call returns.

I would typically set a breaking in the native C/C++ debugger at the end of the native function being called. (Or use `toString` in Dart.)

> Ideally this would use the type of the variable to determine how to display the memory (e.g. utf16 vs int16).

A `Pointer` does not define the "length". Some might be zero-terimated, but some not. So how would we decide how many units to display? When displaying memory in GDB (the LInux native C/C++ debugger) you always have to pass the length. Maybe we should opt for displaying length=1 by default and then have some UI element that allows you to see more.

**Comment by bsutton** [comment] 2021-06-07 08:06
Typically I'm not using a c debugger as I'm calling into existing c
libraries. My current use case is a dart wrapper for the posix libraries.
I would prefer to not have to set up a c debugger as that increases the
complexity of my development environment. It becomes a significant issue
when I'm testing across multiple platforms (linux/windows/mac os) as I then
potentially have to set up a debugger on each platform.

Ideally I want the debugger to interpret the structs without having to
implement tostring methods.  I hadn't thought of this as a solution so I'm
guessing others won't (although now it's obvious) and it reduces the
fluidity of the process (I have to keep remembering to update the tostring
if I update the struct) and having to drop to the debugger line to
execute the toString method which just slows the process down.

It's been a good many years since I debugged a C app but my recollection is
that the debuggers dealt with strings just fine. I assume that it must have
had some 'upper limit' on the string to avoid missing null terminators.
If we put a limit of say 1K by default with some way of modifying the max
value that would suit most use cases.

As to other types such as an int16 then I would like to see an array of
ints up to some default limit, maybe 64, this would handle a single value
and a reasonably sized array.

The classic split display (hex | unicode)  should also be an option on any
pointer.

Finally it would be nice to add a cast to any pointer. Maybe this is a
watch type operation or something you have to do on the debug cli.
Discoverability is my major concern on how this would be done.

So yes, I want the whole enchilada :D



S. Brett Sutton
Noojee Contact Solutions
03 8320 8100

**Comment by dcharkes** [comment] 2021-06-07 08:10
> I have to keep remembering to update the `toString` if I update the struct.

@bsutton are you using `package:ffigen` to generate the Structs? If so, we could add a toString method generation.

**Comment by bsutton** [comment] 2021-06-07 11:46
It's a mix of generated and hand written.

**Comment by dcharkes** [comment] 2023-12-12 18:33
Duplicate of

* https://github.com/dart-lang/sdk/issues/48882

**Closed by dcharkes** 2023-12-12 18:33 UTC
Labels: area-vm, vm-debugger, library-ffi
