### ISSUE TITLE
SDK 1.20.1 has a regression in Code Completion in WebStorm

### ISSUE THREAD

**Issue by tomas-rokos** [dart-lang/sdk#27721] opened 2016-11-01 19:27 UTC
for more details please see https://intellij-support.jetbrains.com/hc/requests/797430

If you are unable to view mentioned request, feel free to contact me. This is serious usability issue with the SDK.

Thank you,
Tomáš

**Comment by alexander-doroshko** [comment] 2016-11-03 16:07
@anders-sandholm Code completion is powered by the Dart Analysis Server, I'm changing area to analyzer.

@tomas-rokos Your private conversation with JetBrains support is definitely not visible to others. Please write issue details / steps to reproduce right here.

**Comment by tomas-rokos** [comment] 2016-11-04 20:37
[das_log.txt](https://github.com/dart-lang/sdk/files/572590/das_log.txt)

**Comment by b-strauss** [comment] 2016-11-05 18:06
I use IntelliJ IDEA and I have the same problem. Dart analysis is horribly slow, barely unusable.

**Comment by anders-sandholm** [comment] 2016-11-07 09:18
@mit-mit 
@bwilkerson

**Comment by bwilkerson** [comment] 2016-11-07 15:02
@scheglov Can you take a look at this?

**Comment by scheglov** [comment] 2016-11-07 16:35
I was not able to reproduce the problem.
When I import `part of myslenkar;` into the corresponding library with the code
```dart
library myslenkar;
import 'dart:html';
part 'test.dart';
```
...and I continue typing `Eleme`, I get completion with `Element` suggestion.

**Comment by b-strauss** [comment] 2016-11-08 09:54
My issue is related to #25109, I use a forked version of flutter. If I exclude all flutter code and use a simple dummy dart file it works.

**Comment by tomas-rokos** [comment] 2016-11-08 15:50
I also cannot easily reproduce it in small sample. It probably requires some larger project, also as I mentioned in my JetBrains support chat it works fine in declaring variable in the class context, but doesn't work in method context.

**Comment by bwilkerson** [comment] 2021-01-22 16:25
I suspect that this has been addressed by now. If not, please reply and I'll re-open the issue.

**Closed by bwilkerson** 2021-01-22 16:25 UTC
Labels: P2, analyzer-completion, area-analyzer, type-bug
