### ISSUE TITLE
Attempt to execute code removed by dart aot compiler

### ISSUE THREAD

**Issue by milindgoel15** [dart-lang/sdk#52874] opened 2023-07-07 11:27 UTC
When running a release build of the Flutter application, an exception is thrown leading to a blank white screen. 

Log:
https://katb.in/ijasupezuwa

realm_services file mentioned in logs:

```dart
import 'package:realm/realm.dart';

import '../screens/home/models/note_model.dart';
import '../screens/home/models/todo_model.dart';

class RealmServices {
  late Realm realm;

  RealmServices() {
    realm = getRealm();
  }

  Realm getRealm() {
    final Configuration config;
    config = Configuration.local(
      [
        TodoModel.schema,
        NoteModel.schema,
      ],
      schemaVersion: 2,
    );

    realm = Realm(config);

    return realm;
  }
}
```

* Dart SDK Version (`dart --version`) 
Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "windows_x64"

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Android

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
n/a

**Comment by vsmenon** [comment] 2023-07-07 16:09
fyi - @alexmarkov - per the log:
```
Attempt to execute code removed by Dart AOT compiler (TFA)
```

**Comment by milindgoel15** [comment] 2023-07-08 09:27
Is there any temporary workaround for this issue? Or I should wait for a fix?

I'm not in a rush or anything but if I wanted to build a release build for testing.

**Comment by mraleph** [comment] 2023-07-10 12:33
Duplicate of https://github.com/dart-lang/sdk/issues/52596

**Comment by mraleph** [comment] 2023-07-10 12:34
@milindgoel15 rewrite your code as:

```
  Realm getRealm() {
    final Configuration config = Configuration.local(
      [/* ... */],
      schemaVersion: 2,
    );

    return Realm(config);
  }
```

This should fix it.

**Closed by mraleph** 2023-07-10 12:34 UTC
Labels: area-vm

**Comment by milindgoel15** [comment] 2023-07-10 13:01
> This should fix it.

That fixed it. Thanks
