### ISSUE TITLE
Error during building

### ISSUE THREAD

**Issue by Pradeep-ShareChat** [dart-lang/sdk#39384] opened 2019-11-14 10:06 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6817.14`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.6817.14, JRE 11.0.4+10-b304.69x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
RangeError: Value not in range: 1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:392:7)
#1      unescapeString (package:front_end/src/fasta/quote.dart:140:14)
#2      AstBuilder.endLiteralString (package:analyzer/src/fasta/ast_builder.dart:1415:22)
#3      Parser.parseSingleLiteralString (package:front_end/src/fasta/parser/parser.dart:4892:14)
#4      Parser.parseLiteralString (package:front_end/src/fasta/parser/parser.dart:4817:13)
#5      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4251:14)
#6      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#7      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#8      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#9      Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#10     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#11     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#12     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#13     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#14     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#15     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#16     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#17     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#18     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#19     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#20     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#21     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#22     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#23     Parser.parseAsyncOptBody (package:front_end/src/fasta/parser/parser.dart:3452:13)
#24     Parser.parseFunctionExpression (package:front_end/src/fasta/parser/parser.dart:3384:13)
#25     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4314:16)
#26     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4286:14)
#27     Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#28     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#29     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#30     Parser.parseArgumentsRest (package:front_end/src/fasta/parser/parser.dart:5015:15)
#31     Parser.parseArguments (package:front_end/src/fasta/parser/parser.dart:4987:12)
#32     Parser.parseArgumentsOpt (package:front_end/src/fasta/parser/parser.dart:4968:14)
#33     Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4947:13)
#34     Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4674:12)
#35     Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4245:14)
#36     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:4016:21)
#37     Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3997:17)
#38     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#39     Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3909:13)
#40     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:front_end/src/fasta/parser/parser.dart:5315:16)
#41     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3726:14)
#42     Parser.parseStatement (package:front_end/src/fasta/parser/parser.dart:3716:20)
#43     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3621:15)
#44     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3269:15)
#45     Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#46     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#47     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#48     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#49     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#50     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#51     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#52     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#53     ParserAdapter.parseCompilatio...
```

For additional log information, please append the contents of
file:///private/var/folders/bx/6svfznh55f90ncq819dzzbk80000gn/T/report.txt.

**Comment by keertip** [comment] 2019-11-15 16:52
Thanks for the report! This was previously reported in #39092 and has been fixed. Please upgrade to the latest version, reopen if you still see the failure.

**Comment by keertip** [comment] 2019-11-15 16:53
Duplicate of #39092

**Closed by keertip** 2019-11-15 16:53 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
