### ISSUE TITLE
What is the expected behaviour of setLibraryDebuggable=false?

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#36914] opened 2019-05-09 15:54 UTC
My understanding of setting a library to be not-debuggable was that when debug stepping, you would not enter non-debuggable code. However, if you explicitly added breakpoints inside it, they would work - and if you were already paused inside the library, then stepping would continue to step inside the library.

However, while investigating https://github.com/Dart-Code/Dart-Code/issues/1697 I discovered that in the VM Service spec it says:

> The setLibraryDebuggable RPC is used to enable or disable whether breakpoints and stepping work for a given library.

Which suggests breakpoints shouldn't work at all and you shouldn't be able to get into it.

However neither of those is what seems to be happening. Given the following code:

```dart
import 'package:path/path.dart';

main() {
  print(join('test', 'test'));
}
```

Invoke Go-to-Definition on `join` and then add a breakpoint, then run the app with all libraries being marked as non-debuggable, and you will still hit the breakpoint.

So, is it possible to clarify what the *intended* behaviour is (so it's clear what is/isn't a bug). Is it as the spec says, and this breakpoint should not be hit? It should also be clarified what happens in the case of an exception occurring in non-debuggable code, since that's not mentioned (only breakpoints and stepping). It's also not clear what "disabling whether they work" exactly means.

@a-siva @bkonyi

**Comment by ZichangG** [comment] 2019-09-18 22:36
> then run the app with all libraries being marked as non-debuggable

@DanTup I try to test it locally, but I don't know how to set libraries to non-debuggable inside VScode. I set both `debugSdkLibraries` and `debugExternalLibraries` to false. Neither sets `package:path/path.dart` to non-debuggable. Did I miss something?

**Comment by DanTup** [comment] 2019-09-19 07:50
Seems to work for me - those settings are default and show enable this. Here's what I did:

- Create a file:
  ```dart
  import 'package:path/path.dart' as path;

  main() {
    print(path.join('a', 'b'));
  }
  ```
- Run the **Dart: Capture Logs**  command and tick only **Debugger**
- Press F5 to run the app
- Click **Cancel** on the logging dialog

In the logs I find this in the libraries list:

> {"type":"@Library","fixedId":true,"id":"libraries\/@20232984","name":"","uri":"package:path\/path.dart"}

And a request like this:

> ==> {"id":"29","method":"setLibraryDebuggable","params":{"isolateId":"isolates/675480685795091","libraryId":"libraries/@20232984","isDebuggable":false}}
> <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"29"}

(Note: I had to set `"dart.maxLogLineLength": 99999999` temporarily so the response with the libraries was not truncated in order to get the ID for `package:path`).

**Comment by ZichangG** [comment] 2019-09-19 17:01
This is what I get for path/path.dart.
`
{"id":"27","method":"setLibraryDebuggable","params":{"isolateId":"isolates/2195922367712387","libraryId":"libraries/@20232984","isDebuggable":true}}
{"jsonrpc":"2.0", "result":{"type":"Success"},"id":"27"}
`

`
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
`

**Comment by ZichangG** [comment] 2019-09-23 21:56
This CL fixing the breakpoint setting and pausing. With cl landed, setting breakpoint to non-debuggable libraries is not allowed. In cases that libraries are set to non-debuggable later, breakpoints won't be hit.

`if you were already paused inside the library, then stepping would continue to step inside the library.`
After some testing, I believe stepping works as expected. It will skip all non-debuggable libraries. I can't reproduce it.

As for exception pausing, I tend to not roll into this flag. Clearly, definition of this flag says only breakpoint and stepping. It will affect all existing users if changing the definition. It is better to handle it separately.

**Comment by ZichangG** [comment] 2019-10-01 14:54
Thanks for reminder. I forget the close the issue :)

**Closed by ZichangG** 2019-10-01 14:54 UTC
Labels: area-observatory

**Comment by ZichangG** [comment] 2019-10-03 02:07
Missed one of your question. Sorry!
> Did you get to the bottom of this? (or do you still need it)? I can't see any obvious reason we'd send true here - though the settings only apply at the start of the session, so you can't change them while the debug session is active.

I used observatory to reproduce. I didn't dig into the setting stuff. Perhaps I didn't set my VScode right. Since it works now, I don't think this affect my daily work. Thanks!
