### ISSUE TITLE
Analyzer fuzz assertion failure: parent is PartOfDirective is not true

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#38124] opened 2019-08-29 20:38 UTC
`class{const T o=u(<.(-(@){`

Note: this only failse in summary 2 @scheglov 

Not adding type-bug yet as it's not 100% clear if this would result in a bug. Disabling assertions produces the bug #38047 for this case, but I don't think they're necessarily inherently related.

```
'package:analyzer/src/generated/resolver.dart': Failed assertion: line 3316 pos 14: 'parent is PartOfDirective': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)    
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)       
#2      ResolverVisitor.visitAnnotation (package:analyzer/src/generated/resolver.dart:3316:14)
#3      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:285:49)    
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)     
#5      NormalFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7844:17)
#6      SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8877:11)
#7      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4249:10)
#8      UnifyingAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:3407:63)
#9      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:8873:15)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
```

**Comment by scheglov** [comment] 2019-08-29 21:59
I cannot reproduce this with the bleeding edge analyzer.

I believe this was fixed with https://dart-review.googlesource.com/c/sdk/+/113963, landed as 9aa48c2e91a3a341a7add970fe0406f26f4e81da.

I also was not able to reproduce it, probably because of parser changes, with https://dart-review.googlesource.com/c/sdk/+/113860, landed as 3e696277522154e2df9e04b5c602daf212883482.

**Closed by scheglov** 2019-08-29 21:59 UTC
Labels: area-analyzer
