### ISSUE TITLE
Analyzer doesn't accept covariant implementations of covariant interfaces

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#34330] opened 2018-08-31 19:25 UTC
Revealed by test cascaded_forwarding_stubs_test.

```
class A {}                                                                       
                                                                                 
class B extends A {}                                                             
                                                                                 
class C {                                                                        
  void f(B x, B y) {}                                                            
}                                                                                
                                                                                 
abstract class I1 {                                                              
  void f(covariant A x, B y);                                                    
}                                                                                
                                                                                 
// D contains a forwarding stub for f which ensures that `x` is type checked.    
class D extends C implements I1 {}    
```

**Comment by MichaelRFairhurst** [comment] 2018-08-31 19:26
Rating this P2 because it's a false negative v the CFE. However, given that its an edgecase around `covariant`, not a P1.

**Comment by MichaelRFairhurst** [comment] 2018-08-31 21:11
also affects: forwarding_stub_tearoff_test, which has almost the exact same case.

**Comment by leafpetersen** [comment] 2018-09-01 01:36
duplicate of https://github.com/dart-lang/sdk/issues/34329 ?

**Closed** 2018-09-05 16:57 UTC
Labels: area-analyzer, closed-duplicate, p2-medium, type-bug
