### ISSUE TITLE
Add shorthand for null-aware method execution

### ISSUE THREAD

**Issue by enloc-port** [dart-lang/sdk#44698] opened 2021-01-18 14:14 UTC
Say a class had a nullable method, i.e. an optional callback.

```
class Foo {
  Foo([this.doSomething]);
  final int Function() doSomething;
}
```

In order to avoid an error, I have to do a null-check on the method before executing it:

```
void main() {
  Foo foo = Foo();
  if (foo.doSomething != null) {
    foo.doSomething();
  }
}
```

But it would make the code look a lot cleaner, if this were possible:
```
void main() {
  Foo().doSomething?(); // null-aware execution
}
```

**Comment by eernstg** [comment] 2021-01-18 14:23
The syntax for that feature is as follows:

```dart
void main() {
  Foo().doSomething?.call(); // null-aware execution
}
```

**Comment by enloc-port** [comment] 2021-01-18 14:40
I see. Well, `f?(args)` would be sweet, but I guess I could live with `f?.call(args)`.

**Comment by eernstg** [comment] 2021-01-18 14:44
Thanks! I think we should close this issue because the code is working as intended. Please create a new issue as needed, for instance, if you wish to make it a language proposal (in the language repository).

**Closed by eernstg** 2021-01-18 14:44 UTC
Labels: closed-as-intended
