### ISSUE TITLE
NPE in analyzer verification of FfiNative annotations for getters

### ISSUE THREAD

**Issue by jason-simmons** [dart-lang/sdk#48962] opened 2022-05-04 23:00 UTC
In the Flutter engine we saw an NPE in the analyzer package when running Dartdoc on the FFI native function bindings
(example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20docs_test/10279/overview)

This happens when the analyzer checks an `FfiNative` annotation applied to a getter.

`FfiVerifier._checkFfiNative` assumes that every `MethodDeclaration` has parameters and needs a special case for methods with the `isGetter` flag.

@cskau-g

**Comment by jacob314** [comment] 2022-05-06 15:49
Fyi @srawlins

**Comment by keertip** [comment] 2022-05-06 16:50
This is not an issue with dartdoc, but with the implementation of the verifier. Assigning to @cskau-g , as the author of this code.

The issue is as stated by jason.

**Comment by keertip** [comment] 2022-05-06 16:51
@cskau-g, PTAL

**Comment by cskau-g** [comment] 2022-05-09 06:45
Konstantin's fix LGTM, so unless you're hitting additional issues, it looks like this was fixed.

Thanks for hopping in and fixing this after EMEA was out for the weekend, Konstantin!

**Closed by cskau-g** 2022-05-09 06:45 UTC
Labels: P1, area-analyzer, library-ffi, bug
