### ISSUE TITLE
Unsupported operation: Undetermined Nullability

### ISSUE THREAD

**Issue by hamishjohnson** [dart-lang/sdk#48752] opened 2022-04-06 14:22 UTC
**Describe the bug**
This code crashes when you build for web, but not for mobile.

I'm able to reproduce with the Riverpod package, but I don't know enough about the problem to reproduce without riverpod. I [opened an issue](https://github.com/rrousselGit/river_pod/issues/1339) there but maintainer Remi Rousselet believes it's a dart issue, so I'm reposting here.

**To Reproduce**
```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(stringProvider);

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(body: Text(value.value ?? '')),
    );
  }
}

const condition = false;

final stringProvider = FutureProvider<String>((ref) {
  if (condition) return 'child'; // <==== This line is what causes the bug

  return future();
});

Future<String> future() async {
  await Future.delayed(const Duration(seconds: 1));

  return 'done';
}
```

**Expected behavior**
Run on mobile, works fine. Run on web, compile crashes.

When adding 'async' to the provided create function, it works fine.

<details>
<summary>Error</summary>

```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
Unhandled exception:
Unsupported operation: Undetermined Nullability
#0      ProgramCompiler._emitFutureOrType (package:dev_compiler[/src/kernel/compiler.dart:3057:7]())
#1      ProgramCompiler.visitFutureOrType (package:dev_compiler[/src/kernel/compiler.dart:2948:11]())
#2      FutureOrType.accept (package:kernel[/ast.dart:11519:42]())
#3      ProgramCompiler._emitType (package:dev_compiler[/src/kernel/compiler.dart:2847:54]())
#4      ProgramCompiler.visitFunctionType (package:dev_compiler[/src/kernel/compiler.dart:3138:22]())
#5      ProgramCompiler._emitFunctionTagged (package:dev_compiler[/src/kernel/compiler.dart:2803:19]())
#6      ProgramCompiler.visitFunctionExpression (package:dev_compiler[/src/kernel/compiler.dart:6186:12]())
#7      FunctionExpression.accept (package:kernel[/ast.dart:8292:44]())
#8      ProgramCompiler._visitExpression (package:dev_compiler[/src/kernel/compiler.dart:3870:20]())
#9      ProgramCompiler._emitArgumentList (package:dev_compiler[/src/kernel/compiler.dart:5614:11]())

#10     ProgramCompiler.visitConstructorInvocation (package:dev_compiler[/src/kernel/compiler.dart:5761:9]())
#11     ConstructorInvocation.accept (package:kernel[/ast.dart:6392:44]())
#12     ProgramCompiler._visitExpression (package:dev_compiler[/src/kernel/compiler.dart:3870:20]())
#13     ProgramCompiler._visitInitializer (package:dev_compiler[/src/kernel/compiler.dart:1786:11]())
#14     ProgramCompiler._emitStaticFieldInitializer.<anonymous closure> (package:dev_compiler[/src/kernel/compiler.dart:2366:23]())
#15     ProgramCompiler._withLetScope (package:dev_compiler[/src/kernel/compiler.dart:2376:25]())
#16     ProgramCompiler._emitStaticFieldInitializer (package:dev_compiler[/src/kernel/compiler.dart:2364:40]())
#17     ProgramCompiler._emitLazyFields (package:dev_compiler[/src/kernel/compiler.dart:2339:43]())
#18     ProgramCompiler._emitTopLevelFields (package:dev_compiler[/src/kernel/compiler.dart:2323:21]())
#19     ProgramCompiler._emitLibrary (package:dev_compiler[/src/kernel/compiler.dart:573:7]())
#20     List.forEach (dart:core-patch[/growable_array.dart:433:8]())
#21     ProgramCompiler.emitModule (package:dev_compiler[/src/kernel/compiler.dart:431:15]())
#22     JavaScriptBundler.compile (package:frontend_server[/src/javascript_bundle.dart:152:33]())
<asynchronous suspension>
#23     FrontendCompiler.writeJavascriptBundle (package:frontend_server[/frontend_server.dart:665:32]())

<asynchronous suspension>
#24     FrontendCompiler.compile (package:frontend_server[/frontend_server.dart:573:9]())
<asynchronous suspension>
#25     listenAndCompile.<anonymous closure> (package:frontend_server[/frontend_server.dart:1154:11]())
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)
Failed to compile application.
```

</details>

### Edit:

I forgot to add that I was able to fix the issue in the meantime by wrapping the value in a future, like so

Replace
`if (condition) return 'child'; // <==== This line is what causes the bug`

With
`if (condition) return Future.value('child');`

In case that helps anybody

**Comment by caleb654** [comment] 2022-04-06 14:43
Also using Riverpod and getting this issue. I am able to build a release build, but in debug, it crashes every time.

**Comment by caleb654** [comment] 2022-04-06 14:59
@hamishjohnson How did you figure out which line was causing the issue? I'm not able to get any details about that in the stack trace?

**Comment by hamishjohnson** [comment] 2022-04-06 18:19
I was just trial and errored it. By the way, I updated the post with a fix (wrapping in a Future) in case that helps you.

But the bug still exists

**Comment by devoncarew** [comment] 2022-04-06 18:34
Highlighting the stack trace from above:

```
Launching lib[/main.dart]() on Chrome in debug mode...
lib/main.dart:1
Unhandled exception:
Unsupported operation: Undetermined Nullability
#0      ProgramCompiler._emitFutureOrType (package:dev_compiler[/src/kernel/compiler.dart:3057:7]())
#1      ProgramCompiler.visitFutureOrType (package:dev_compiler[/src/kernel/compiler.dart:2948:11]())
#2      FutureOrType.accept (package:kernel[/ast.dart:11519:42]())
#3      ProgramCompiler._emitType (package:dev_compiler[/src/kernel/compiler.dart:2847:54]())
#4      ProgramCompiler.visitFunctionType (package:dev_compiler[/src/kernel/compiler.dart:3138:22]())
#5      ProgramCompiler._emitFunctionTagged (package:dev_compiler[/src/kernel/compiler.dart:2803:19]())
#6      ProgramCompiler.visitFunctionExpression (package:dev_compiler[/src/kernel/compiler.dart:6186:12]())
#7      FunctionExpression.accept (package:kernel[/ast.dart:8292:44]())
#8      ProgramCompiler._visitExpression (package:dev_compiler[/src/kernel/compiler.dart:3870:20]())
#9      ProgramCompiler._emitArgumentList (package:dev_compiler[/src/kernel/compiler.dart:5614:11]())

#10     ProgramCompiler.visitConstructorInvocation (package:dev_compiler[/src/kernel/compiler.dart:5761:9]())
#11     ConstructorInvocation.accept (package:kernel[/ast.dart:6392:44]())
#12     ProgramCompiler._visitExpression (package:dev_compiler[/src/kernel/compiler.dart:3870:20]())
#13     ProgramCompiler._visitInitializer (package:dev_compiler[/src/kernel/compiler.dart:1786:11]())
#14     ProgramCompiler._emitStaticFieldInitializer.<anonymous closure> (package:dev_compiler[/src/kernel/compiler.dart:2366:23]())
#15     ProgramCompiler._withLetScope (package:dev_compiler[/src/kernel/compiler.dart:2376:25]())
#16     ProgramCompiler._emitStaticFieldInitializer (package:dev_compiler[/src/kernel/compiler.dart:2364:40]())
#17     ProgramCompiler._emitLazyFields (package:dev_compiler[/src/kernel/compiler.dart:2339:43]())
#18     ProgramCompiler._emitTopLevelFields (package:dev_compiler[/src/kernel/compiler.dart:2323:21]())
#19     ProgramCompiler._emitLibrary (package:dev_compiler[/src/kernel/compiler.dart:573:7]())
#20     List.forEach (dart:core-patch[/growable_array.dart:433:8]())
#21     ProgramCompiler.emitModule (package:dev_compiler[/src/kernel/compiler.dart:431:15]())
#22     JavaScriptBundler.compile (package:frontend_server[/src/javascript_bundle.dart:152:33]())
<asynchronous suspension>
#23     FrontendCompiler.writeJavascriptBundle (package:frontend_server[/frontend_server.dart:665:32]())

<asynchronous suspension>
#24     FrontendCompiler.compile (package:frontend_server[/frontend_server.dart:573:9]())
<asynchronous suspension>
#25     listenAndCompile.<anonymous closure> (package:frontend_server[/frontend_server.dart:1154:11]())
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)
Failed to compile application.
```

**Comment by gmpassos** [comment] 2022-04-06 20:10
Maybe related to:
https://github.com/dart-lang/sdk/issues/48631#issuecomment-1088731905

FYI: @chloestefantsova

**Comment by nshahan** [comment] 2022-04-06 20:18
@chloestefantsova recently fixed two similar issues. One has already rolled into flutter main, but the second hasn't yet. The second fix was for an issue reported by another user with a RiverPod dependency https://github.com/dart-lang/sdk/issues/48631#issuecomment-1086388877. I suspect this will be fixed by one of those changes and I'd like to verify if the issue is still present at flutter master after the second fix has rolled in.

**Comment by chloestefantsova** [comment] 2022-04-07 13:50
I think so too, that my recent fix should resolve this issue. I try to locally verify that.

**Comment by chloestefantsova** [comment] 2022-04-07 15:15
Ok, @whesse checked the fix that's already in the Dart SDK, and it seems to work.

**Closed by chloestefantsova** 2022-04-07 15:15 UTC
Labels: web-dev-compiler, area-web
