### ISSUE TITLE
apt-get dart on Ubuntu fails / No command 'pub' found, did you mean... 

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/sdk#28133] opened 2016-12-16 11:14 UTC
The Debian installer fails to install (or symlink) pub and company.

dart works but e.g. pub fails

I had to
```bash
/usr/bin $

ln -s /usr/lib/dart/bin/pub 
ln -s /usr/lib/dart/bin/dart2js 
ln -s /usr/lib/dart/bin/dartanalyzer 
ln -s /usr/lib/dart/bin/dartdoc 
ln -s /usr/lib/dart/bin/dartfmt
```

**Comment by mit-mit** [comment] 2016-12-16 14:21
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/19926

**Closed by mit-mit** 2016-12-16 14:21 UTC
