### ISSUE TITLE
'DynamicTypeImpl' is not a subtype of type 'InterfaceType' in TypeProviderForLink._buildInterfaceType (SDK 2.4.0)

### ISSUE THREAD

**Issue by somaria** [dart-lang/sdk#37556] opened 2019-07-17 22:35 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-183.6156.11.34.5692245`
- `2.4.0`
- `AI-183.6156.11.34.5692245, JRE 1.8.0_152-release-1343-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /Users/daryl/Desktop/Try/flutter_http_fetch_try/test/widget_test.dart context: exception_20190718_063415_875
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5535:5)
#1      TypeProviderForLink.iterableType (package:analyzer/src/summary/link.dart:5470:25)
#2      ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:4691:24)
#3      ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6826:49)
#4      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2551:16)
#5      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5357:36)
#6      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5200:7)
#7      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
#8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
#9      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5633:47)
#10     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2617:22)
#11     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:907:20)
#12     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1632:20)
#13     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3840:12)
#14     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3540:15)
#15     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3480:7)
#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
#17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
#18     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
#19     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
#20     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3513:42)
#21     Linker.link (package:analyzer/src/summary/link.dart:4045:35)
#22     _relink (package:analyzer/src/summary/link.dart:311:74)
#23     link (package:analyzer/src/summary/link.dart:125:3)
#24     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:217:25)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#26     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:216:12)
#27     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#28     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1594:29)
#29     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1405:30)
#30     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#31     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#32     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#33     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#34     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#35     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#36     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#37     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#38     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#44     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#45     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#46     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#47     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#48     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#49     new Future.sync (dart:async/future.dart:224:31)
#50     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#51     _rootRun (dart:async/zone.dart:1124:13)
#52     _CustomZone.run (dart:async/zone.dart:1021:19)
#53     _runZoned (dart:async/zone.dart:1516:10)
#54     runZoned (dart:async/zone.dart:1463:12)
#55     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#56     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#57     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#58     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#59     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#60     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#61     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/5z/tttr8sr52jjgd37q2b2x916m0000gq/T/report.txt.

**Comment by srawlins** [comment] 2019-08-29 05:52
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/35437; please follow along there.

**Comment by srawlins** [comment] 2019-08-29 05:53
Duplicate of https://github.com/dart-lang/sdk/issues/35437

**Closed by srawlins** 2019-08-29 05:53 UTC
Labels: analyzer-crash-report, area-analyzer
