### ISSUE TITLE
Compiling Dart for Android without Flutter?

### ISSUE THREAD

**Issue by ingridwang** [dart-lang/sdk#47225] opened 2021-09-15 17:37 UTC
Hi, is it possible to run a plain Dart program on Android? According to https://dart.dev/tools/dart-compile, only MacOS, Windows, and Linux are supported and there's no cross-compilation support. I'm just trying to get a hello world running on an Android device in adb shell.

From the [Flutter FAQs](https://flutter.dev/docs/resources/faq#run-android) I see that:

> The engine’s C and C++ code are compiled with Android’s NDK. **The Dart code (both the SDK’s and yours) are ahead-of-time (AOT) compiled into native, ARM, and x86 libraries.** Those libraries are included in a “runner” Android project, and the whole thing is built into an .apk.

Is this possible without Flutter?

**Comment by mraleph** [comment] 2021-09-16 08:07
This is possible, but not through our prebuilt tooling - we currently don't ship enough pieces necessary to achieve this in the Dart SDK releases. You can build necessary pieces manually - most specifically you need to build `clang_{x86,x64}/gen_snapshot` and `dart_precompiled_runtime` from `ReleaseAndroidXARM` or `ReleaseAndroidXARM64` configurations. I could give you more precise instructions if you feel that it's something you want to do. 

I am a bit curious about your use-case - could you share some details on how you intend to use this? That would help us to prioritise this feature going forward - because this is something that we really want to enable eventually but so far found no place to slot it into in our roadmaps. 

/cc @mit-mit

**Comment by mraleph** [comment] 2021-09-16 08:07
Duplicate of #28617

**Closed by mraleph** 2021-09-16 08:07 UTC

**Comment by YukiAttano** [comment] 2026-07-02 11:43
Hi, sorry for bothering you mraleph. 
I would like to ask for more precise instructions on this.
From all Issues that I've read through on this topic, your answer some years ago is the first trace to a solution.

My use case is, that I have a terminal application which I want to run on my Android phone with Termux.
Until today I thought it would be possible to run any linux exe on my Android phone (well, most seem to be made with python nowadays). 

I am on vacation the next week, so please don't feel rushed.

> This is possible, but not through our prebuilt tooling - we currently don't ship enough pieces necessary to achieve this in the Dart SDK releases. You can build necessary pieces manually - most specifically you need to build `clang_{x86,x64}/gen_snapshot` and `dart_precompiled_runtime` from `ReleaseAndroidXARM` or `ReleaseAndroidXARM64` configurations. I could give you more precise instructions if you feel that it's something you want to do.
> 
> I am a bit curious about your use-case - could you share some details on how you intend to use this? That would help us to prioritise this feature going forward - because this is something that we really want to enable eventually but so far found no place to slot it into in our roadmaps.
> 
> /cc [@mit-mit](https://github.com/mit-mit)
