### ISSUE TITLE
got this

### ISSUE THREAD

**Issue by devholy** [dart-lang/sdk#39922] opened 2019-12-25 10:36 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.0-edge.8b8894648f0dbe53b046133caab11fbe8e14dc3f`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.8b8894648f0dbe53b046133caab11fbe8e14dc3f, server version 1.27.4, FATAL error: FileSystemException: Directory listing failed, path = 'C:\Users\user\AppData\Local\.dartServer\.analysis-driver\08\' (OS Error: The file or directory is corrupted and unreadable.
, errno = 1392)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:39:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:251:5)
#2      EvictingFileByteStore._cleanUpFolder (package:analyzer/src/dart/analysis/file_byte_store.dart:114:30)
#3      EvictingFileByteStore._cacheCleanUpFunction.<anonymous closure> (package:analyzer/src/dart/analysis/file_byte_store.dart:101:9)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#8      _StreamController._add (dart:async/stream_controller.dart:649:7)
#9      _StreamController.add (dart:async/stream_controller.dart:595:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\user\AppData\Local\Temp\report.txt.

**Comment by keertip** [comment] 2020-01-06 16:48
Thanks for the report. Previously reported in #37059.

**Comment by keertip** [comment] 2020-01-06 16:48
Duplicate of #37059

**Closed by keertip** 2020-01-06 16:48 UTC
Labels: analyzer-crash-report, area-analyzer
