### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by StevAlberts** [dart-lang/sdk#34994] opened 2018-10-31 09:15 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1600x900`

# Exception

Please append the contents of:
file://C:\Users\stevo\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version , error: Analysis failed: C:\Flutter\repo\mi_app\lib\pages\auth.dart context: exception_20181030_203908_487
Exception: Element not found in summary: package:flutter/src/widgets/framework.dart

**Comment by stereotype441** [comment] 2018-10-31 16:43
Duplicate of #34555

**Closed by stereotype441** 2018-10-31 16:43 UTC
Labels: area-analyzer
