### ISSUE TITLE
Builder dart2js-win7-ie11ff-1-4-be has many timeouts

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#28662] opened 2017-02-07 10:28 UTC
During the period Fri Feb 03 17:36 - Mon Feb 06 21:07 (according to the buildbot time stamps), the builder dart2js-win7-ie11ff-1-4-be has had test failures on and off 5 times. The failures are always (there is just one exception) timeouts, and the timeouts always follow this pattern:

  First test, stderr: This test has not notified test.py that it started running.
  Subsequent tests, stderr: This test timed out. The delay until the test actually started was: ... 

The timeout always occurs in a 'start_browser.dart' command, e.g.:
```
E:\b\build\slave\ie11_1-be\build\sdk\tools\sdks\win\dart-sdk\bin\dart.exe tools/testing/dart/launch_browser.dart ie11 http://127.0.0.1:62786/root_build/generated_tests/dart2js-ie11-sdk/tests_html_custom_tags_test/test.html?crossOriginPort=62787
Took 0:01:00.002165
...
E:\b\build\slave\ie11_1-be\build\sdk\tools\sdks\win\dart-sdk\bin\dart.exe tools/testing/dart/launch_browser.dart ie11 http://127.0.0.1:62786/root_build/generated_tests/dart2js-ie11-sdk/tests_html_element_animate_test/test.html?crossOriginPort=62787&group=animate_supported
Took 0:01:00.158153
```

Here is the list of tests that were affected by this problem, spanning builds 3627-3643; only two of the tests failed twice, otherwise it seems to be random tests that fail with a timeout, always following the pattern described above. They are all `dart2js-ie11 release_x64`, and they are all in `html`:
```
    ./custom_tags_test
    ./element_constructor_1_test
    ./element_types_constructors1_test
    ./events_test
    ./typed_arrays_range_checks_test
    audiobuffersourcenode_test/supported
    cache_test/ApplicationCache
    custom/document_register_template_test
    element_animate_test/animate_supported
    js_type_test/dynamic-type
    js_type_test/static
    media_stream_test/supported_MediaStreamTrackEvent
    transition_event_test/supported
```
Rather than marking all these tests `Slow` in status files, I suspect that we need to systematically give tests (html tests only?) longer time to run in this setup, or once and for all find the reason why ie11 causes so many timeouts. Hence this issue rather than a large number of status file changes.

**Comment by johnniwinther** [comment] 2017-02-22 15:36
These timeouts occur on multiple `dart2js-win` bots. While gardening I've observed timeouts on `dart2js-win7-ie10chrome-2-4-be`, `dart2js-win7-ie10chrome-4-4-be`, `dart2js-win7-ie11ff-1-4-be`, `dart2js-win7-ie11ff-2-4-be`, `dart2js-win7-ie11ff-3-4-be`, and `dart2js-win7-ie11ff-4-4-be`. The timeouts are most frequent on `html` tests but also occurred on these `pkg` tests:
```
pkg/front_end/test/scanner_roundtrip_test
pkg/front_end/test/scanner_test
pkg/kernel/testcases/closures/for_variable_capture_test
pkg/microlytics/test/dart_microlytics_test
pkg/testing/test/hello_test
```

**Comment by peter-ahe-google** [comment] 2017-02-23 11:17
I've noticed double reporting test on [dart2js-win7-ie10chrome](https://uberchromegw.corp.google.com/i/client.dart/builders/dart2js-win7-ie10chrome-4-4-be/builds/3338).

```
  http://127.0.0.1:63527/root_build/generated_tests/dart2js-ie10-sdk/short7318_oad-stylesheet-with-import_t01/test.html?crossOriginPort=63528
  http://127.0.0.1:63527/root_build/generated_tests/dart2js-ie10-sdk/tests_co19_src_LibTest_html_Window_postMessage_A01_t01/test.html?crossOriginPort=63528
  http://127.0.0.1:63527/root_build/generated_tests/dart2js-ie10-sdk/short8616_ll-with-borders-right-edge_t01/test.html?crossOriginPort=63528
  http://127.0.0.1:63527/root_build/generated_tests/dart2js-ie10-sdk/short8760_-characters-complex-script_t01/test.html?crossOriginPort=63528
  http://127.0.0.1:63527/root_build/generated_tests/dart2js-ie10-sdk/short1735_n_Invocation_async_cleanup_t03/test.html?crossOriginPort=63528
  http://127.0.0.1:63527/root_build/generated_tests/dart2js-ie10-sdk/short1741_n_Invocation_async_cleanup_t06/test.html?crossOriginPort=63528
```

I've skipped them all on dart2js configurations and filed #28873 for further investigation by the dart2js team.

Double reporting tests can mess with other tests and make them timeout out or flake.

**Comment by nex3** [comment] 2017-03-10 01:21
@sigmundch I'm working on getting more gardening issues assigned. If you're not the right person to assign this to, please reassign to that person.

**Comment by sigmundch** [comment] 2017-11-16 23:41
marking as duplicate of #28955

**Closed by sigmundch** 2017-11-16 23:41 UTC
Labels: area-infrastructure, gardening
