### ISSUE TITLE
Process.stdout is always empty in a weak mode on precompiled enviromnent

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#44243] opened 2020-11-18 15:29 UTC
The following code produces different results on weak and strong NNBD modes on precompiled environment
```dart
import "dart:io";

runMain() {
  String executable = Platform.resolvedExecutable;
  String eScript = Platform.script.toString();

  Process.start(executable, [eScript, "run"]).then((Process process) {
    process.stdout.toList().then((List outList) {
      print(outList);
    });
  });
}

runProcess() {
  stdout.write("Lily was here");
}

main(List<String> args) {
  if(args.length > 0)
    runProcess();
  else {
    runMain();
  }
}
```
If to run this code on `dartkp-weak-asserts-linux-release-x64` configuration ( tools/test.py -v -n dartkp-weak-asserts-linux-release-x64  test-name) then it prints `[]`
If to run it on `dartkp-strong-linux-release-x64` configuration (`tools/test.py -v -n dartkp-strong-linux-release-x64 test-name`) then it prints `[[76, 105, 108, 121, 32, 119, 97, 115, 32, 104, 101, 114, 101]]`

If to run this test on `dartk-weak-asserts-linux-release-x64` and  `dartk-strong-linux-release-x64`  the result is the same as on `dartkp-strong-linux-release-x64`. Prints  `[[76, 105, 108, 121, 32, 119, 97, 115, 32, 104, 101, 114, 101]]`

So, I believe, this is an issue for `dartkp-weak-asserts-linux-release-x64` configuration only

Tested on `Dart SDK version: 2.12.0-edge.546fdf55bccaa02105c3cb0645f2325f5145f5ef (be) (Thu Nov 12 00:14:52 2020 +0000) on "linux_x64"`

**Comment by alexmarkov** [comment] 2020-11-18 19:19
Failure in `dartkp-weak-asserts-linux-release-x64` configuration happens because of incompatible VM options when creating an AOT snapshot and running it as a sub-process.

If you modify the test to print stderr of the sub-process:

```dart
    process.stderr.toList().then((List<List<int>> outLists) {
      for (var list in outLists) {
        print('stderr: ' + utf8.decoder.convert(list));
      }
    });
```

and run it with `tools/test.py -v --print-passing-stdout -n dartkp-weak-asserts-linux-release-x64 test-name`, then you can see the following error:

```
VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-dwarf_stack_traces_mode no-causal_async_stacks lazy_async_stacks no-lazy_dispatchers use_bare_instructions no-dedup_instructions "asserts" no-code-comments x64-sysv no-null-safety' but the VM has 'release no-dwarf_stack_traces_mode no-causal_async_stacks lazy_async_stacks no-lazy_dispatchers use_bare_instructions no-dedup_instructions no-"asserts" no-code-comments x64-sysv no-null-safety'
```

The difference is that snapshot was built with assertions enabled, but test tries to run a sub-process without passing `--enable_asserts` flag. In general, I would recommend passing all `Platform.executableArguments` into sub-processes in the tests. Passing all VM options would also ensure that sub-process runs in the same testing mode, and would prevent surprises when flipping default values of flags (if flag is not passed, then certain tests may start failing after changing the default as launched sub-process was not tested with the flag before).

Something along the lines:
```dart
  Process.start(executable, [...Platform.executableArguments, eScript, "run"]).then((Process process) {
```

**Comment by alexmarkov** [comment] 2020-11-18 19:21
Tentatively closing this issue as this is not a bug in Dart SDK.

**Closed by alexmarkov** 2020-11-18 19:21 UTC
Labels: area-vm
