### ISSUE TITLE
Update dart autocomplete action

### ISSUE THREAD

**Issue by tieorange** [dart-lang/sdk#39191] opened 2019-10-31 16:16 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d6c6d12ebf71a918279e1bdb420fedbc1d560a35, server version 1.27.3, FATAL error: Failed to handle request: {id: 19823, method: edit.getFixes, params: {file: /Users/tieorange/Documents/FlutterProjects/tecash/lib/ui/pages/person_selector/reqest_money_type_selector.dart, offset: 455}, clientRequestTime: 1572538529739}
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<void>(Instance of '_ElementReferenceCollector')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      findLocalElementReferences (package:analysis_server/src/services/correction/util.dart:150:8)
#2      FixProcessor._addFix_removeUnusedLocalVariable (package:analysis_server/src/services/correction/fix_internal.dart:3681:24)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#4      FixProcessor._addFix_removeUnusedLocalVariable (package:analysis_server/src/services/correction/fix_internal.dart:3668:49)
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:388:13)
#6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#7      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:205:28)
#8      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
#9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#10     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:67:33)
#11     EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:656:46)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#21     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart)
#22     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#31     DartFixContributor._computeFixAllFixes (package:analysis_server/src/services/correction/fix_internal.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#39     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#40     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#41     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart)
#42     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#47     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#48     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#49     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#53     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#56     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#57     _Timer....
```

For additional log information, please append the contents of
file:///private/var/folders/h9/pxr_mp395_jdg964xrdx8jlw0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-11-04 16:27
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/39095; please follow along there.

**Comment by srawlins** [comment] 2019-11-04 16:27
Duplicate of https://github.com/dart-lang/sdk/issues/39095

**Closed by srawlins** 2019-11-04 16:27 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
