### ISSUE TITLE
dart format support for records

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#50798] opened 2022-12-20 16:56 UTC
```
$ dart analyze --enable-experiment=records record.dart
Analyzing record.dart...               0.4s
No issues found!

$ dart format --enable-experiment=records record.dart
Could not find an option named "enable-experiment".

$ dart --enable-experiment=records format record.dart
# and
$ dart format record.dart
# choke on record types.
```

Snippet that causes issues:

```dart
final returnStruct3BytesHomogeneousUint8VariadicLeaf =
    ffiTestFunctions.lookupFunction<
        Struct3BytesHomogeneousUint8 Function(Uint8, VarArgs<(Uint8, Uint8)>),
        Struct3BytesHomogeneousUint8 Function(int, int,
              int)>("ReturnStruct3BytesHomogeneousUint8Variadic", isLeaf: true);
```

@munificent

**Comment by munificent** [comment] 2023-01-06 01:28
Duplicate of https://github.com/dart-lang/dart_style/issues/1128.

**Closed by munificent** 2023-01-06 01:28 UTC
Labels: area-dart-cli, dart-cli-format
