### ISSUE TITLE
`dart compile js` fails with the newest SDK

### ISSUE THREAD

**Issue by srujzs** [dart-lang/sdk#56087] opened 2024-06-26 17:41 UTC
Dart SDK version: `3.5.0-edge.21ee651cc4ed07e5729d727dfbd5f15498bc31fd (main) (Wed Jun 26 10:35:50 2024 -0700) on "macos_arm64"`

Compiling any Dart file with `dart compile js` leads to:

```
vm-service: Error: Unhandled exception:
ProcessException: No such file or directory
  Command: ./dart development-service --vm-service-uri=http://127.0.0.1:58929/_EgWJOd0pEo=/ --bind-address=localhost --bind-port=0 --serve-devtools
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _DebuggingSession.start (dart:vmservice_io:104:30)
#3      _toggleWebServer.<anonymous closure> (dart:vmservice_io:324:28)
<asynchronous suspension>
#4      _toggleWebServer (dart:vmservice_io:321:5)
<asynchronous suspension>
#5      webServerControlCallback (dart:vmservice_io:341:5)
<asynchronous suspension>
#6      VMService._serverMessageHandler (dart:_vmservice:410:21)
<asynchronous suspension>
```

Reverting https://dart-review.googlesource.com/c/sdk/+/366560 fixes the issue. cc @bkonyi

**Comment by bkonyi** [comment] 2024-06-26 18:09
@srujzs I'm unable to reproduce at HEAD and can't find `21ee651cc4ed07e5729d727dfbd5f15498bc31fd`. Can you please confirm the revision you're seeing this on?

**Comment by derekxu16** [comment] 2024-06-26 18:33
I downloaded the latest main channel release from https://storage.googleapis.com/dart-archive/channels/main/raw/latest/sdk/dartsdk-macos-arm64-release.zip with `--version` output `Dart SDK version: 3.5.0-edge.4abd615d3279573ad4711995a545ed156da8a315 (main) (Wed Jun 26 17:18:17 2024 +0000) on "macos_arm64"` and `dart compile js` works using it for me.

**Comment by derekxu16** [comment] 2024-06-26 18:36
Actually, it looks `Wed Jun 26 10:35:50 2024 -0700` is a bit newer than `Wed Jun 26 17:18:17 2024 +0000`, so let me try building the SDK locally.

**Comment by srujzs** [comment] 2024-06-26 19:03
Ah apologies, that was with a local revert CL. I can repro with `Dart SDK version: 3.5.0-edge.3180d9545360cfb176a90d45db48009cf1beb842 (main) (Tue Jun 25 21:12:28 2024 +0000) on "macos_arm64"`.

**Comment by bkonyi** [comment] 2024-06-26 19:19
> Ah apologies, that was with a local revert CL. I can repro with `Dart SDK version: 3.5.0-edge.3180d9545360cfb176a90d45db48009cf1beb842 (main) (Tue Jun 25 21:12:28 2024 +0000) on "macos_arm64"`.

@derekxu16 and I are both unable to reproduce with `3180d9545360cfb176a90d45db48009cf1beb842`. This is from a locally built SDK?

**Comment by srujzs** [comment] 2024-06-26 19:21
Yes. It looks like this is the cause (for me at least), which makes sense with the error: https://github.com/dart-lang/sdk/blob/4abd615d3279573ad4711995a545ed156da8a315/sdk/lib/_internal/vm/bin/vmservice_io.dart#L99

Reverting that to `resolvedExecutable` fixes the issue. It's possible that `executable` gives us different values here.

**Comment by bkonyi** [comment] 2024-06-26 19:34
> Yes. It looks like this is the cause (for me at least), which makes sense with the error:
> 
> https://github.com/dart-lang/sdk/blob/4abd615d3279573ad4711995a545ed156da8a315/sdk/lib/_internal/vm/bin/vmservice_io.dart#L99
> 
> Reverting that to `resolvedExecutable` fixes the issue. It's possible that `executable` gives us different behavior here.

Are you using symlinks anywhere by any chance?

**Comment by srujzs** [comment] 2024-06-26 20:04
Not that I'm aware of. Does `Platform.executable` give you a full path instead of just `dart` on your machine?

**Comment by bkonyi** [comment] 2024-06-26 20:11
Hm, good question... do you have `dart` on your path at all? Maybe that's why I'm unable to reproduce.

**Comment by srujzs** [comment] 2024-06-26 20:15
Yup, I have this in my `.bashrc`:

`export PATH=$PATH:~/dart-sdk/sdk/xcodebuild/ReleaseARM64/dart-sdk/bin/`

**Comment by bkonyi** [comment] 2024-06-26 20:19
`Platform.executable` definitely doesn't do what I thought (I assumed it returned the path to the executable _without_ resolving symlinks), so I'm going to revert this for now. See https://dart-review.googlesource.com/c/sdk/+/373381.

**Comment by a-siva** [comment] 2024-06-26 22:43
https://dart-review.googlesource.com/c/sdk/+/373381 has landed, closing this issue.

**Closed by a-siva** 2024-06-26 22:43 UTC
Labels: area-vm, P0, area-dart-cli, dart-cli-compile

**Comment by bkonyi** [comment] 2024-06-27 19:36
I've managed to track down the cause of the issue.

If the user has `dart` on their `PATH` and invokes `dart compile js` (which spawns the VM service after compilation completes), the VM service would attempt to spawn DDS using `./dart` as the executable path instead of `dart`. This would result in DDS failing to start since `./dart` didn't exist, causing the VM to print an error and hang.
    
The fix here is to check to see if the parent directory of `Platform.executable` is `.` and then verify if `./dart` exists or not. If it doesn't, `dart` is likely on the user's `PATH` and should be used directly as the executable path.

I have a CL almost ready for review that should resolve this issue and allow for relanding the reverted commit ([see CL here](https://dart-review.googlesource.com/c/sdk/+/373561)).

**Comment by a-siva** [comment] 2024-06-27 21:49
> If the user has `dart` on their `PATH` and invokes `dart compile js` (which spawns the VM service after compilation completes), the VM service would attempt to spawn DDS using `./dart` as the executable path instead of `dart`. This would result in DDS failing to start since `./dart` didn't exist, causing the VM to print an error and hang.

Does this spawning of VM service after compilation is done need to also attempt to spawn DDS ?

**Comment by bkonyi** [comment] 2024-06-27 22:25
DDS is responsible for serving DevTools, so we probably want to spawn DDS when we can.

**Comment by a-siva** [comment] 2024-06-27 23:08
> DDS is responsible for serving DevTools, so we probably want to spawn DDS when we can.

I agree but the command line 'dart compile js' does not imply start vm service for debugging, shouldn't 'dart --enable-vm-service compile js' be needed for that ?

**Comment by bkonyi** [comment] 2024-06-27 23:33
> > DDS is responsible for serving DevTools, so we probably want to spawn DDS when we can.
> 
> I agree but the command line 'dart compile js' does not imply start vm service for debugging, shouldn't 'dart --enable-vm-service compile js' be needed for that ?

While that's true, there's currently no way to only enable the VM service without enabling DDS, and there could be functionality provided by DDS that developers want to utilize. If we want to provide a way to not start DDS, we'd need to add a named parameter to this API which I'm not sure we'd want to do.
