### ISSUE TITLE
DDC: RangeError (byteOffset): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by dan-conachi** [dart-lang/sdk#34446] opened 2018-09-12 08:16 UTC
* Dart SDK Version (`dart --version`) -  2.0.0
* Whether you are using Windows, MacOSX, or Linux (if applicable) - linux_x64
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) - Chrome Version 67.0.3396.62 (Official Build) (64-bit)

RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data/runtime/libtyped_data_patch.dart:4228:7)
#1      BufferContext._getUint32 (package:front_end/src/base/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:front_end/src/base/flat_buffers.dart:54:21)
#3      TableReader.read (package:front_end/src/base/flat_buffers.dart:694:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:4174:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:939:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:502:32)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:405:43)
#8      List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:405:18)
#10     new ModuleCompiler (package:dev_compiler/src/analyzer/module_compiler.dart:92:21)
#11     _compile (package:dev_compiler/src/analyzer/command.dart:131:18)
#12     compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#13     _CompilerWorker.performRequest (file:///tmp/tmpIOgzpj/dart-2.0.0/dart/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#14     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#20     main (file:///tmp/tmpIOgzpj/dart-2.0.0/dart/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#21     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

```
}

**Comment by vsmenon** [comment] 2018-09-20 19:35
This looks like an invalid summary input.  The error should be more nicely reported.

**Comment by srawlins** [comment] 2019-09-06 05:00
This was also reported at https://github.com/dart-lang/sdk/issues/35968, and marked as fixed.

**Comment by srawlins** [comment] 2019-09-06 05:00
Duplicate of https://github.com/dart-lang/sdk/issues/35968

**Closed by srawlins** 2019-09-06 05:00 UTC
Labels: area-web, web-dev-compiler
