### ISSUE TITLE
Find reason for a stricter type check in the Expando<Function> in the NNBD SDK

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#39971] opened 2020-01-02 18:27 UTC
In https://dart-review.googlesource.com/c/sdk/+/128462 I need to change an `Expando<Function>` to an `Expando<dynamic>` to avoid this error:

```
Runtime error:
 Error: Expected a value of type 'Function*', but got one of type 'NativeJavaScriptObject'
 at Object.throw_ [as throw] (http://127.0.0.1:33341/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:931:11)
     at Object.castError (http://127.0.0.1:33341/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:891:15)
     at Object.cast [as as] (http://127.0.0.1:33341/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:1217:17)
     at dart.LegacyType.new._check (http://127.0.0.1:33341/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:2261:19)
     at Expando.new._set (http://127.0.0.1:33341/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:43175:11)
     at Object.allowInterop (http://127.0.0.1:33341/root_build/gen/utils/dartdevc/kernel/amd/dart_sdk.js:37840:26)
     at Object.main (http://127.0.0.1:33341/root_dart/out/ReleaseX64NNBD/generated_compilations/dartdevk-checked-sdk/tests_compiler_dartdevc_native_js_interop_test/js_interop_test.js:34:38)
     at testMainWrapper (http://127.0.0.1:33341/root_build/generated_tests/dartdevk-chrome-checked-sdk/tests_compiler_dartdevc_native_js_interop_test/test.html?crossOriginPort=42871:103:84)
```

We should find the root cause of the behavior difference since this is impacting the behavior of non-migrated legacy code.

**Comment by vsmenon** [comment] 2020-01-16 17:49
This test will work as of https://dart-review.googlesource.com/c/sdk/+/131300.  I don't think my CL fixes the root issue above - it's a separate fix the gets `js_interop_test` running.

I suspect the root cause to this was fixed by either @Markzipan or @nshahan recently.

**Closed by vsmenon** 2020-01-16 17:49 UTC
Labels: area-web, web-dev-compiler
