### ISSUE TITLE
vm: dissasembler test seems flaky

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#33089] opened 2018-05-09 16:45 UTC
My CL failed on the CQ 3 times in a row because of language_2/dissasemble_test, is it flaky?

My CL in question: https://dart-review.googlesource.com/c/sdk/+/54160

Failure logs:
https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8947051184298338464%2F%2B%2Fsteps%2Fstrong_vm_tests_shard_5%2F0%2Fstdout
https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8947049372713714400%2F%2B%2Fsteps%2Fstrong_vm_tests_shard_5%2F0%2Fstdout
https://logs.chromium.org/v/?s=dart%2Fbuildbucket%2Fcr-buildbucket.appspot.com%2F8947029512464508352%2F%2B%2Fsteps%2Fstrong_vm_tests_shard_5%2F0%2Fstdout

**Comment by kmillikin** [comment] 2018-05-09 16:56
I've observed this recently too.

**Comment by a-siva** [comment] 2022-07-07 17:29
Tried reproducing this on the latest builds but am unable to get it to crash, anumber of fixes in the compiler have gone in since this issue was filed.
Closing this issue, please file a new issue if you run into it again.

**Closed by a-siva** 2022-07-07 17:29 UTC
Labels: area-vm
