### ISSUE TITLE
FATAL error: NoSuchMethodError: The getter 'length' was called on null.

### ISSUE THREAD

**Issue by redwolf0302** [dart-lang/sdk#36060] opened 2019-02-28 06:38 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `<NO SDK>`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.3 unknown, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0f9a5198bd644e908adcf8061e6a9722a40a2f93, server version , FATAL error: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core/runtime/lib/object_patch.dart:50:5)
#1      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:687:14)
#2      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:674:26)
#3      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:710:33)
#4      Driver.start (package:analysis_server/src/server/driver.dart:363:28)
#5      main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///private/var/folders/g0/47hvs5zd6dg5_sv12gqfc97c0000gq/T/report.txt.

**Comment by stereotype441** [comment] 2019-03-01 23:01
Duplicate of #33875

**Closed by stereotype441** 2019-03-01 23:01 UTC
Labels: area-analyzer
