### ISSUE TITLE
hashCode of a double is very trivial

### ISSUE THREAD

**Issue by filiph** [dart-lang/sdk#26273] opened 2016-04-15 07:17 UTC
Not sure if this is intended but calling `number.hashCode` is equivalent to `number.toInt()`.

```
class _Double extends _Num implements double {
  // ...

  int get _identityHashCode {
    if (isNaN || isInfinite) return 0;
    return toInt();
  }
}
```

This of course means that `3.14`, `3.14159` and `3.9` all have the same hashCode. It gets even more confusing when you're trying to do hashCodes of numbers that are close to zero because `0` suggests some kind of other problem.

It would be useful to have something like Java's [Double.hashCode()](http://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#hashCode%28%29).

**Comment by Fox32** [comment] 2016-04-15 07:31
Duplicate of #2884

**Closed** 2016-04-17 01:05 UTC
Labels: Resolution: duplicate
