### ISSUE TITLE
"Socket error: Null check operator used on a null value" during analysis

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#47973] opened 2021-12-20 19:19 UTC
```
[Error - 11:12:27 AM] Socket error: Null check operator used on a null value: Null check operator used on a null value
#0      LspNotificationManager.sendAnalysisErrors.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/notification_manager.dart:35:49)
#1      pluginToDiagnostic (package:analysis_server/src/lsp/mapping.dart:803:29)
#2      LspNotificationManager.sendAnalysisErrors.<anonymous closure> (package:analysis_server/src/lsp/notification_manager.dart:32:25)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#5      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#7      new List.of (dart:core-patch/array_patch.dart:51:28)
#8      ListIterable.toList (dart:_internal/iterable.dart:213:44)
#9      LspNotificationManager.sendAnalysisErrors (package:analysis_server/src/lsp/notification_manager.dart:41:10)
#10     AbstractNotificationManager.recordAnalysisErrors (package:analysis_server/src/plugin/notification_manager.dart:128:7)
#11     LspServerContextManagerCallbacks.recordAnalysisErrors (package:analysis_server/src/lsp/lsp_analysis_server.dart:887:10)
#12     LspServerContextManagerCallbacks._handleFileResult (package:analysis_server/src/lsp/lsp_analysis_server.dart:897:9)
#13     LspServerContextManagerCallbacks.listenAnalysisDriver.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:863:9)
#14     _rootRunUnary (dart:async/zone.dart:1434:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#20     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#21     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
#22     _rootRunUnary (dart:async/zone.dart:1442:13)
#23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#26     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#27     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#28     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#29     _rootRun (dart:async/zone.dart:1418:47)
#30     _CustomZone.run (dart:async/zone.dart:1328:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#33     _rootRun (dart:async/zone.dart:1426:13)
#34     _CustomZone.run (dart:async/zone.dart:1328:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#40     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Dart version: Dart SDK version: 2.16.0-118.0.dev (dev) (Thu Dec 16 14:23:20 2021 -0800) on "windows_x64"

**Comment by Ilya-Korolev** [comment] 2022-02-09 10:14
I have the same problem with this project in vs code: https://github.com/chatsen/chatsen

<details>
  <summary>flutter doctor</summary>
  
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-arm, locale ru-RU)
    • Flutter version 2.10.0 at /Users/ikorolev/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (8 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/ikorolev/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available
  
</details>

**Comment by DanTup** [comment] 2022-12-15 16:14
I believe this was fixed by https://github.com/dart-lang/sdk/commit/afe70b743282e5aa6947b47bca06d9cb5a8ac9eb. There  were some cases where during renames we could try to obtain line information for a file as it was renamed, and fail.

If you can still reproduce this on a reasonable recent SDK, please let me know and provide an updated stack trace (since the `!` in the original stack above no longer exists).

Thanks!

**Closed by DanTup** 2022-12-15 16:14 UTC
Labels: area-analyzer, P2, type-bug, analyzer-crash-report
