### ISSUE TITLE
VM Service asyncCausalFrames contains many more frames than expected

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#44138] opened 2020-11-10 14:23 UTC
Given the following script:

```dart
import 'dart:async';

Future<void> main() async {
  await func1();
}

Future func1() async => await func2();
Future func2() async => await func3();
Future func3() async => await func4();
Future func4() async => await func5();
Future func5() async => await func6();
Future func6() async => await func7();
Future func7() async => await func8();
Future func8() async => await func9();
Future func9() async => await func10();
Future func10() async {
  print("Hello, world!"); // BREAKPOINT1
}
```

Stopping on the line marked `BREAKPOINT1` using Dart SDK v2.10.3 and fetching the call stack and printing `asyncCausualFrames` like this:

```ts
const t1 = await vmService.getStack(thread.ref.id);
console.log(`${(t1.result as VMStack).asyncCausalFrames?.map((f) => f.code!.name).join("\n")}`);
```

Results in the following frames:

```
[Unoptimized] func10
[Unoptimized] func9
[Unoptimized] func8
[Unoptimized] func7
[Unoptimized] func6
[Unoptimized] func5
[Unoptimized] func4
[Unoptimized] func3
[Unoptimized] func2
[Unoptimized] func1
[Unoptimized] main
[Unoptimized] main
[Unoptimized] _Closure.call
[Unoptimized] _startIsolate.<anonymous closure>
[Unoptimized] _Closure.call
[Unoptimized] _RawReceivePortImpl._handleMessage
```

However running the same thing on 2.12.0-29.0.dev, it looks like this:

```
[Unoptimized] func10
[Unoptimized] func9
[Unoptimized] func8
[Unoptimized] func7
[Unoptimized] func6
[Unoptimized] func5
[Unoptimized] func4
[Unoptimized] func3
[Unoptimized] func2
[Unoptimized] func1
[Unoptimized] main
[Unoptimized] _startIsolate.<anonymous closure>
[Unoptimized] _RawReceivePortImpl._handleMessage
[Unoptimized] _Closure.call
[Unoptimized] func6
[Unoptimized] func5
[Unoptimized] _Closure.call
[Unoptimized] func5
[Unoptimized] func4
[Unoptimized] _Closure.call
[Unoptimized] func4
[Unoptimized] func3
[Unoptimized] _Closure.call
[Unoptimized] func3
[Unoptimized] func2
[Unoptimized] _Closure.call
[Unoptimized] func2
[Unoptimized] func1
[Unoptimized] _Closure.call
[Unoptimized] func1
[Unoptimized] main
[Unoptimized] _Closure.call
[Unoptimized] main
[Unoptimized] main
[Unoptimized] _Closure.call
[Unoptimized] _startIsolate.<anonymous closure>
[Unoptimized] _Closure.call
[Unoptimized] _RawReceivePortImpl._handleMessage
```

I wonder if it might be including some results from `frames` (like it's reusing the list and not clearing out those that aren't overwritten?).

@bkonyi

**Comment by bkonyi** [comment] 2020-11-10 18:00
That's definitely not right, and my first inclination would be to blame 89de1e82d9073d3f3a96145ad24940e8c311b493 but looking at the code there I don't see any obvious issues... Let me see if I can bisect this.

**Comment by bkonyi** [comment] 2020-11-10 18:30
So it looks like we've switched from running with `--causal-async-stacks` by default to `--lazy-async-stacks` in e90967f29de77f58512499acae471a60f9e42761 which seems to be the issue. I'm not sure why this would return a garbage stack for `asyncCausalFrames` but passing `--causal-async-stacks --no-lazy-async-stacks` restores the previous behavior.

@cskau-g @mkustermann can you provide insight on this?

**Comment by mkustermann** [comment] 2020-11-10 18:56
@DanTup If you replace the print in your example with `print(StackTrace.current)` then you will get the right answer. For me it prints:
```
#0      func10 (file:///.../test.dart:17:20)
#1      func9 (file:///.../test.dart:15:31)
#2      func8 (file:///.../test.dart:14:31)
#3      func7 (file:///.../test.dart:13:31)
#4      func6 (file:///.../test.dart:12:31)
#5      func5 (file:///.../test.dart:11:31)
#6      func4 (file:///.../test.dart:10:31)
#7      func3 (file:///.../test.dart:9:31)
#8      func2 (file:///.../test.dart:8:31)
#9      func1 (file:///.../test.dart:7:31)
#10     main (file:///.../test.dart:4:9)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:311:19)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
If the debugger is behaving differently, then it's a bug and we have to fix it.

This is most likely caused by the lazy async stack support, so I'll re-assign @cskau-g

**Comment by rmacnak-google** [comment] 2020-11-11 00:01
If `_Closure.call` is appearing, I suspect that lazy async stacks are not respecting the visible bit on functions.

**Comment by cskau-g** [comment] 2020-11-11 15:53
Quick update: this is indeed a bug in the Debugger code, and, as speculated above, it is (partially) overwriting a good trace with one that doesn't take function visibility into account, resulting in corrupted output.

I've got a fix going, but I'd like to add some test coverage for this API as well, so I'm hoping to land something tomorrow.

**Comment by cskau-g** [comment] 2020-11-13 07:09
Resolving this issue since [171584](https://dart-review.googlesource.com/c/sdk/+/171584) landed last night, fixing the bug.

**Closed by cskau-g** 2020-11-13 07:09 UTC
Labels: P2, area-vm

**Comment by DanTup** [comment] 2020-11-17 13:28
Works for me, thanks!
