### ISSUE TITLE
FileSystemException in _WindowsDirectoryWatcher when running analysis server

### ISSUE THREAD

**Issue by ZhiPengTu** [dart-lang/sdk#34485] opened 2018-09-17 08:40 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-182.4323.46`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `IU-182.4323.46, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\Administrator\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Administrator\IdeaProjects\newflutter], excluded: [C:\Users\Administrator\IdeaProjects\newflutter\.idea, C:\Users\Administrator\IdeaProjects\newflutter\.dart_tool, C:\Users\Administrator\IdeaProjects\newflutter\.pub, C:\Users\Administrator\IdeaProjects\newflutter\build, C:\Users\Administrator\IdeaProjects\newflutter\out]}, clientRequestTime: 1537171606382}
FileSystemException: Exists failed, path = 'C:\Users\Administrator\IdeaProjects\newflutter\build\app\intermediates\transforms\dexBuilder\debug\10\android' (OS Error: 拒绝访问。
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by lrhn** [comment] 2018-09-17 09:29
The " 拒绝访问。" text stands out as something being wrong, but it's probably not related to the actual error - I have seen similar bad UTF-8 strings in other error messages, just not reproducibly.

**Comment by natebosch** [comment] 2018-09-17 23:45
>I have seen similar bad UTF-8 strings in other error messages

I don't think it's a bad string (unless you're referring to the newline?). Translates to "access denied" and is probably an expected exception caused by a bug in analyzer. I think I've seen a few similar reports with the error both in english and chinese.

**Comment by stereotype441** [comment] 2018-10-23 03:49
Duplicate of #34294

**Closed by stereotype441** 2018-10-23 03:49 UTC
Labels: area-analyzer, type-bug
