### ISSUE TITLE
Fuzzy arrow inconsistency 

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31119] opened 2017-10-17 05:08 UTC
Reproduced on 2.0.0-dev.3.0

```dart
void func<T>(List<T> list, int compare(T a, T b), List<T> target) {
  func(list, compare, target);
  //         ^ uses_dynamic_as_bottom

  func(list, compare, <T>[]);
  //         ^ fine

  func(list, compare, target as List<T>);
  //         ^ fine   ^ unnecessary_cast

  func(list, compare, list);
  //         ^ fine
}
```

**Comment by leafpetersen** [comment] 2017-10-17 15:56
Duplicate of https://github.com/dart-lang/sdk/issues/30980 .

**Closed by leafpetersen** 2017-10-17 15:56 UTC
Labels: analyzer-strong-mode, area-analyzer, strong-mode-polish

**Comment by kevmoo** [comment] 2017-10-17 16:46
Ha! Same code! I cleaned up my example

From mobile. Sorry for brevity and/or spelling.
