### ISSUE TITLE
Test Failures on ffi/callback_unwind_error_test 

### ISSUE THREAD

**Issue by jyameo** [dart-lang/sdk#57088] opened 2024-11-14 16:09 UTC
There are new test failures on [Elements. Migrate GetterSetterTypesVerifier....Add the formatter changes to the CHANGELOG.](https://github.com/dart-lang/sdk/compare/1640ca79955cc8d8ab5c3fe0c50c6b4885e09c8b~...91db72c3944c23c27c89427b1608cb7f4ba0ed6e).

The tests
```
ffi/callback_unwind_error_test Crash (expected Pass)
```
are failing on configurations
```
vm-eager-optimization-linux-release-ia32
```
LOGS:
https://dart-ci.appspot.com/log/vm-eager-optimization-linux-release-ia32/vm-eager-optimization-linux-release-ia32/629/ffi/callback_unwind_error_test

**Comment by a-siva** [comment] 2024-12-04 22:07
Duplicate of https://github.com/dart-lang/sdk/issues/53581

**Closed by a-siva** 2024-12-04 22:07 UTC
Labels: area-vm, type-bug, gardening
