### ISSUE TITLE
Error when subtracting with floating number

### ISSUE THREAD

**Issue by ivsaneesh** [dart-lang/sdk#45018] opened 2021-02-16 07:50 UTC
https://stackoverflow.com/questions/66220369/flutter-error-when-subtracting-with-floating-number

issue when two floating number are subtracted

print('result ${200.83 - 100.12}');

output -> result 100.71000000000001

**Comment by mraleph** [comment] 2021-02-16 08:38
Duplicate of #45019

**Comment by mraleph** [comment] 2021-02-16 08:39
That's simply how floating point arithmetic works. (And that's why for example you should never use floating point to perform operations with monetary values)

**Closed by mraleph** 2021-02-16 08:38 UTC
