### ISSUE TITLE
Internal problem: Unhandled field with more than one declaration in address.

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31194] opened 2017-10-20 22:51 UTC
Crash in fasta
@peter-ahe-google
id: 2da85733f5e923a57cc5614f53ef329e0967b578

```
Internal problem: Unhandled field with more than one declaration in address.
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:449:11)
#3      DietListener.listenerFinishFields (package:front_end/src/fasta/source/diet_listener.dart:615:14)
#4      DietListener.parseFields (package:front_end/src/fasta/source/diet_listener.dart:660:5)
#5      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:522:5)
#6      DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:245:5)
#7      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2356:16)
#8      Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2316:11)
#9      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:322:14)
#10     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:271:15)
#11     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:178:14)
<asynchronous suspension>
#12     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#13     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:289:20)
<asynchronous suspension>
#14     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#15     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:52:37)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#17     _rootRun (dart:async/zone.dart:1124)
#18     _CustomZone.run (dart:async/zone.dart:1021)
#19     runZoned (dart:async/zone.dart:1499)
#20     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#21     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#22     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:49:28)
#23     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:69:27)
<asynchronous suspension>
#24     testDirectory (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:42:9)
<asynchronous suspension>
#25     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:137:7)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by askeksa-google** [comment] 2017-11-07 10:28
Seems to have been fixed by https://github.com/dart-lang/sdk/commit/c8e51ef92267b5dbe5ce2dd2a038aa310c9762dd though the changes in that commit seem unrelated.

**Comment by askeksa-google** [comment] 2017-11-07 12:10
Could not reproduce the crash, even with revisions going back to the beginning of October.

**Comment by jensjoha** [comment] 2018-01-09 09:12
Does that mean we can close this issue?

**Comment by peter-ahe-google** [comment] 2018-01-09 09:29
We can't close this yet. The code that produces this exception is still there, but we don't get there currently because of a deprecated_InputError when duplicated fields exists.

**Closed** 2023-08-31 08:05 UTC
Labels: P3, needs-info, front-end-fasta, area-front-end
