### ISSUE TITLE
Notify users  when running dart fix could cleanup diagnostics.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#51655] opened 2023-03-08 00:10 UTC
Most users do not know to run `dart fix` after migrating to use new versions of Flutter or the Dart SDK when their project has diagnostics that `dart fix` could automatically fix.

Prior art:
We show notifications in the IDEs to suggest running `pub upgrade` but this logic is tightly coupled to specific IDE plugins.

Any time a user opens a Dart project in VSCode they should see a notification if the project has diagnostics that `dart fix` may be able to resolve. 

The notification should include a MessageActionItem to run `dart fix` using the 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#showMessageRequestParams
API.

To avoid annoying users, we should show the notification at most once per time a project is opened and only immediately after the project is opened or their package dependencies have changed.

The first time after switching to Dart 3.0 the toast could be customized to say something like “Welcome to 3.0. The dart fix tool is here to help you with a migration. You have 3 issues with your project that dart fix may be able to cleanup.” [run dart fix | close]. 

It would be nice to show the notifications in IntelliJ as well but we should start with VSCode as LSP already supports an API for exactly this case.

**Comment by DanTup** [comment] 2023-03-08 17:53
@pq you were asking some questions about this recently - were you already looking at some of this (detection of when to prompt)?

I have a PoC of using annotated edits to let the user see a preview of the edits and choose which to make that I think would work well here (and it avoids problems with unsaved files/no undo that we'd have shelling out to `dart fix`). My plan was to add a command that can be run from the palette any time (essentially an interactive way of running `dart fix` across the workspace). Once that exists, the prompt would just be able to call that same code.

Assuming we want to go that route (using annotated edits) I can tidy that up to get it into server.

One current drawback is that doing it this way does not support iterative fixes (see #47968).

**Comment by pq** [comment] 2023-03-08 17:59
I've thought about it a bit but haven't done any implementation.  I'd be more than happy if you wanted to pick this up and run with it!

**Comment by DanTup** [comment] 2023-03-08 18:27
> Assuming we want to go that route (using annotated edits)

@jacob314 @bwilkerson do you have any opinions on whether to go this route or spawn the CLI `dart fix`? Using annotated edits is what I showed a while back that shows a tree of edits letting you see diffs and choosing which to apply.

Some pros/cons:

- Doing it via VS Code annotated edits doesn't support iterative fixes (#47968)
- Previewing a huge number of edits might not be a great UX
- VS Code doesn't default to grouping the edits by fix, so the list is flat unless the user changes the view from the context menu (I will file an issue about this, since it feels like a bad default if the server has gone to the lengths of providing groupings)
- CLI `dart fix` is all-or-nothing
- CLI `dart fix` won't produce undo steps
- If there are unsaved files, `dart fix` may run on old content and trigger "Content on disk modified" messages that the user has to reconcile (although this prompt will be early on, VS Code restores unsaved files from the previous session and I find it quite common that I open projects and find I had unsaved changes 🙃)

**Comment by bwilkerson** [comment] 2023-03-08 21:14
Another advantage to not using the CLI tool is that it will be more performant. The CLI tool would need to re-analyze everything in order to compute diagnostics.

My opinion is that it would be much better if we could use the existing server. The strongest factor, for me, is that it would work with any unsaved changes.

In a brief glance at the issue you referenced, I didn't see any discussion of creating a temporary OverlayResourceProvider around the existing instance. In theory that should work and should allow the existing dart fix support to run the multiple iterations that we'd like to support.

**Comment by DanTup** [comment] 2023-03-08 21:35
@bwilkerson 

> I didn't see any discussion of creating a temporary OverlayResourceProvider around the existing instance

That's what I was trying when I wrote https://github.com/dart-lang/sdk/issues/47968#issuecomment-1342918348. The problem is that we end up with multiple sets of edits that need applying _sequentially_ (that is, round 2 of edits relies on round 1 having been already applied because a) it may make changes on top of those changes and b) the offsets will assume those edits have been applied). For LSP API, we need a single/flat/merged set of edits.

For example if "dart fix" produced:

- round 1: insert "var" at x
- round 2: replace "var" at x with "final"

For LSP, we need to produce a single edit that says:

- insert "final" at x

It also means all offsets of edits in round 2 that come after insertions/deletes in round 1 need to be adjusted "back" to correspond to their _original_ offsets (prior to round 1).

**Comment by bwilkerson** [comment] 2023-03-08 21:46
Got it, thanks. It isn't the ability to have temporary overlays, it's the merging of edits.

How bad would it be if all of the edits were of the form "replace the contents of this file with this other contents"? If we're trying to use the refactoring support (that shows individual edits) that might be really bad, but if we didn't would it be reasonable?

**Comment by DanTup** [comment] 2023-03-08 21:57
> How bad would it be if all of the edits were of the form "replace the contents of this file with this other contents"?

In addition to losing the previews, this would potentially remove all the users breakpoints and other things that are attached to document positions (test gutter icons, etc.) because VS Code wouldn't track where they've moved to. There are some cases where it tries to compute minimal edits but that might only be for formatting, and even that is only smaller files which led us to computing minimal edits in the server (https://github.com/Dart-Code/Dart-Code/issues/1626 / https://github.com/dart-lang/sdk/commit/a36f85b5e6e2b609a4878e9b2e844c5f5da9a7a9).

**Comment by InMatrix** [comment] 2023-03-14 17:40
> Most users do not know to run dart fix after migrating to use new versions of Flutter or the Dart SDK when their project has diagnostics that dart fix could automatically fix.

Do those diagnostics suggest users try `dart fix`?

**Comment by bwilkerson** [comment] 2023-03-14 18:16
No, they don't.

**Comment by InMatrix** [comment] 2023-03-14 18:35
@bwilkerson Is there an opportunity to suggest `dart fix` in relevant diagnostics?

**Comment by bwilkerson** [comment] 2023-03-14 21:44
At the point at which we publish the diagnostics to the client we haven't done the extra work of associating a fix with the diagnostic, so we can't know whether a fix exists, let alone whether `dart fix` could apply the fix. The best we could do would be a message of the form "dart fix might be able to fix this". But some unknown percentage of the time `dart fix` wouldn't be able to do anything. If the percentage is high enough (and I suspect that it would be) then it would be a bit like ["The Boy Who Cried Wolf"](https://en.wikipedia.org/wiki/The_Boy_Who_Cried_Wolf).

**Comment by InMatrix** [comment] 2023-03-14 23:11
Thanks for the clarification. Since diagnostics do not carry information about how applicable `dart fix` is, the proposal in the original post seems to rely on the assumption that if a bunch of diagnostics show up right after upgrading to Dart 3, `dart fix` is likely to be helpful. Is that understanding correct? This approach, if true, seems to be reasonable, but will the analyzer be able to tell if a diagnostic shows up _before_ or _after_ upgrading to Dart 3? Do we need some sort of analysis history for a project to establish the casual relationship between upgrading to Dart 3 and diagnostics?

**Comment by pq** [comment] 2023-03-14 23:18
> will the analyzer be able to tell if a diagnostic shows up before or after upgrading to Dart 3?

For newly introduced diagnostics, for sure.  Otherwise, not precisely though we could maybe apply some heuristics.

The idea of an analysis history is interesting.

**Comment by DanTup** [comment] 2023-03-15 11:01
> the proposal in the original post seems to rely on the assumption that if a bunch of diagnostics show up right after upgrading to Dart 3, `dart fix` is likely to be helpful.

If I understand correctly, we don't _need_ to make assumptions here if we just want to trigger a prompt (and not include info in the diagnostic text). I think Brian's point was that as part of normal analysis and sending diagnostics to a client, we don't do the extra work to know if `dart fix` would fix (if we did, this would significantly slow down analysis).

However, we could run a task at particular times (such as after initial analysis has completed) to check whether any diagnostics are _actually_ fixable by `dart fix` before showing a prompt. This may not be cheap, but would be accurate. We could abort the check on the first fixable error to save some computation in the case where there are fixable diagnostics.

I also wonder if there are diagnostics where we _know_ `dart fix` _will_ work. For example if an error is that you have a `!` on a non-nullable variable and the fix is "Remove the !" - are there any cases where this would _not_ be available? If not, could we use this information when producing the diagnostic without needing to compute any fixes?

**Comment by InMatrix** [comment] 2023-03-15 15:49
> However, we could run a task at particular times (such as after initial analysis has completed) to check whether any diagnostics are actually fixable by dart fix before showing a prompt. 

Oh, that would be helpful.

**Comment by bwilkerson** [comment] 2023-03-15 19:35
> For example if an error is that you have a ! on a non-nullable variable and the fix is "Remove the !" - are there any cases where this would not be available?

I'd need to check the implementation to be sure, but I think the answer is no.

> If not, could we use this information when producing the diagnostic without needing to compute any fixes?

Yes, but the number of fixes that are unconditional might be fairly small.

**Comment by DanTup** [comment] 2023-03-30 11:35
I believe the VS Code and server work (for both protocols) for this is all done. If you're using the pre-release version of the Dart extension (and as of the release next week, the stable version) and a recent Dart 3 build, you should see these prompts in VS Code. Once IntelliJ has support for the new protocol requests, it should also work there.

**Comment by leafpetersen** [comment] 2023-04-06 17:57
Can we close this out, or shall I move it to the stable milestone?

**Comment by vsmenon** [comment] 2023-04-17 18:23
Any updates here?

**Comment by DanTup** [comment] 2023-04-17 18:59
I think all the remaining work is in the IntelliJ extension (server + VS Code are done). I don't know if we want/need to keep this issue open to track that or not - @bwilkerson?

**Comment by bwilkerson** [comment] 2023-04-17 20:48
My understanding is that Alex is currently wiring up the protocol on the IntelliJ side. If we have done the work on the server side to use the new protocol when it's supported, then I believe that we can close this issue.

**Closed** 2023-04-17 21:47 UTC
Labels: area-analyzer, analyzer-server, P2
