### ISSUE TITLE
Encountered a Dart Analysis Server error

### ISSUE THREAD

**Issue by hema-developer** [dart-lang/sdk#36920] opened 2019-05-10 02:41 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5160847`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `AI-182.5107.16.33.5160847, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Analysis failed: D:\android\projects\oroad_offer\lib\main.dart context: exception_20190510_043904_873
NoSuchMethodError: Class 'LibraryElementInBuildUnit' has no instance getter 'session'.
Receiver: Instance of 'LibraryElementInBuildUnit'
Tried calling: session
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      LibraryElementForLink.noSuchMethod (package:analyzer/src/summary/link.dart:3736:48)
#2      LibraryElementInBuildUnit.session (package:analyzer/src/dart/element/element.dart:5206:25)
#3      LibraryImportScope._lookupInImportedNamespaces (package:analyzer/src/dart/resolver/scope.dart:542:30)
#4      LibraryImportScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:397:15)
#5      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#6      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#7      EnclosedScope.internalLookup (package:analyzer/src/dart/resolver/scope.dart:137:27)
#8      Scope.lookup (package:analyzer/src/dart/resolver/scope.dart:1063:12)
#9      ElementResolver._resolveSimpleIdentifier (package:analyzer/src/generated/element_resolver.dart:1681:43)
#10     ElementResolver.visitSimpleIdentifier (package:analyzer/src/generated/elem

**Comment by parlough** [comment] 2019-05-27 00:32
Seems to be a duplicate of https://github.com/dart-lang/sdk/issues/36872

Likely fixed by https://github.com/dart-lang/sdk/commit/7418238239f885ba92093c44a1768f8ec93b121f

**Closed** 2019-08-08 14:36 UTC
Labels: area-analyzer, type-bug
