### ISSUE TITLE
Missing nullability on some inferred type arguments for collection literals

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#43455] opened 2020-09-16 21:00 UTC
When the type parameter of the collection literal is inferred as the least upper bound of a type argument and another value, the nullability is undetermined.

This is true for list, set, and map literals. 

Here is an example based on the test `co19/LanguageFeatures/Set-literals/type_inference_A20_t01`.

```dart
class C<X> {
  test(X x) {
    var v = {x, 1, 2};
    print(v is Set<Object?>); // should be true
    print(v is Set<int?>); // should be false
  }
}

main() {
  C<int?>().test(42);
  C<int?>().test(null);
}
```

You can see the undetermined nullability of the inferred type: `core::Object%` 
```
class C<X extends core::Object? = dynamic> extends core::Object {
  synthetic constructor •() → tes::C<tes::C::X%>
    : super core::Object::•()
    ;
  method test(generic-covariant-impl tes::C::X% x) → dynamic {
    core::Set<core::Object%> v = <core::Object%>{x, 1, 2};
    core::print(v is{ForNonNullableByDefault} core::Set<core::Object?>);
    core::print(v is{ForNonNullableByDefault} core::Set<core::int?>);
  }
}
static method main() → dynamic {
  new tes::C::•<core::int?>().{tes::C::test}(42);
  new tes::C::•<core::int?>().{tes::C::test}(null);
}
```

@johnniwinther

**Comment by johnniwinther** [comment] 2020-09-17 06:29
@stefantsov can you take a look at this?

**Comment by eernstg** [comment] 2020-09-17 10:18
Note that this could very well be caused by the issue that is targeted in the spec update https://github.com/dart-lang/language/pull/1195 (which is about least upper bounds).

**Comment by franklinyow** [comment] 2020-09-17 18:45
@leafpetersen Please triage

**Comment by nshahan** [comment] 2020-09-17 20:11
I believe this issue is the cause of these new test failures https://github.com/dart-lang/co19/issues/938.

**Comment by eernstg** [comment] 2020-09-18 09:27
The spec change has been landed, and there is an implementation issue: https://github.com/dart-lang/sdk/issues/43479.

**Closed** 2020-09-24 11:55 UTC
Labels: NNBD, area-front-end, type-bug
