### ISSUE TITLE
stacktrace_message_test broke

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#36022] opened 2019-02-25 19:05 UTC
[stacktrace_message_test broke](https://ci.chromium.org/p/dart/builders/luci.dart.ci.sandbox/vm-kernel-reload-linux-debug-x64/3333), [logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8920539055259650736/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0). Break is specific to vm-kernel-reload-linux-debug-x64 bot.

It started failing after [this change](https://dart-review.googlesource.com/c/sdk/+/94262), but it looks like that's some sort of aggregate CL.

**Comment by sstrickl** [comment] 2019-02-26 13:07
I haven't been able to reproduce this failing at all on my local workstation using thousands of test runs, so I'll take a look at reproducing the bot environment and trying it in there since it seemed to be consistently happening on the bot.

**Comment by liamappelbe** [comment] 2019-02-26 17:20
I did approve the failure to get the bot to go green again, so local test runs will pass now. So you'll need to look at the actual test output, and not just check whether it passes or fails.

**Comment by sstrickl** [comment] 2019-02-27 09:29
Ah, right, thanks, I'm still used to the old status file workflow and went back to the old revision thinking that of course I'd see it then. :)

Trying to find a point in the past where this test _did_ work, so I can bisect and find the issue, since it's consistently failing. Not sure why it started on that commit, though, since so far I haven't found an older commit (haven't gone back _too_ far yet) where it _did_ succeed.

**Comment by sstrickl** [comment] 2019-02-27 09:51
Checking the old status files, this test has been marked as a RTE for a long time, so this is what we'd expect. And yes, if I run on the previous revision (the one marked green before mine), it indeed fails with a RTE.

Current hypothesis is that something happened on the approval database to suddenly cause the RTE to not be approved, and I'm checking into this now. Unassigning myself since this is something outside my doing, but will either reassign or update/close when I have more.

**Comment by sstrickl** [comment] 2019-02-27 11:55
Yep, after checking with Jonas, turns out that there were some approval issues at the time that were rolled back, but apparently somehow this one got lost in the shuffle. So RTE is the expected behavior and everything should be sorted now.

**Closed by sstrickl** 2019-02-27 11:56 UTC
