### ISSUE TITLE
[dart:js_interop] Add an option to ignore rest arguments when passing Dart functions to methods like Array.map.

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#55245] opened 2024-03-20 09:39 UTC
For example ([`Array.map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#callbackfn)):
```dart
import 'dart:js_interop';

@JS('eval')
external void eval(String code);

@JS('do_work')
external void doWork(JSFunction callback);

void main() {
  eval('''
const array = [1, 2, 3, 4];
window.do_work = (callback) => {
  array.map(callback);
};
''');

  doWork(((JSAny? item, /* index, array */) => print(item)).toJS);
}
```
Throws with `Dynamic call with too many positional arguments. Expected: 1 Actual:... (NativeError)`.

**Comment by srujzs** [comment] 2024-03-21 16:12
Duplicate of https://github.com/dart-lang/sdk/issues/48186.

**Closed by srujzs** 2024-03-21 16:12 UTC
Labels: web-js-interop, area-web
