### ISSUE TITLE
CFE allows extension setters with conflicting names on record types

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#50512] opened 2022-11-18 15:26 UTC
The following code should be rejected with a compile-time error.

```dart
typedef R = ({int foo});

extension on R {
  void set foo(int value) {}
}

test(R r) {
  r.foo = 0;
}
```

**Comment by johnniwinther** [comment] 2022-11-18 15:37
Duplicate of #50157

**Closed by johnniwinther** 2022-11-18 15:37 UTC
Labels: area-front-end
