### ISSUE TITLE
Add lint for dynamic checks are made against a subtype of the declared type

### ISSUE THREAD

**Issue by plammens** [dart-lang/sdk#56624] opened 2024-09-01 07:40 UTC
Proposal: add a new lint that warns you if you are checking the runtime type of an object against a type that is not a subtype of its declared type (downcasting):
```dart
num foo;
foo is int;  // ok
foo is String;  // warning: according to the static type of foo, foo can never be a String

// also with case statements
if (foo case String string); // warning

// and switch statements/expressions
switch (foo) {
  case String _:  // warning
}
switch (foo) {
  String _ =>  ... // warning
}
```

Use case: to prevent some kinds of type bugs that are not detected at compile time.
For example, in my codebase I made a refactoring that changed the type of a variable `foo` from `T` to `Wrapper<T>`.
I was doing a check like `foo is Completable`, which was now invalid and should have been `foo.data is Completable`.
However, this wasn't detected at compile time, instead at runtime that part would just never run.

**Comment by eernstg** [comment] 2024-09-02 08:00
It is definitely possible to encounter situations where a dynamic type test (`is`) or type cast (`as`) legitimately has a target type which isn't a subtype of the current static type of the scrutinee.

```dart
class A {}
class B1 implements A {}
class B2 implements A {}
class C implements B1, B2 {}

void main() {
  B1 b1 = C();
  ...
  if (b1 is B2) ...
}
```

We've had this discussion a few times, "shouldn't we have a safer type test/cast?", where "safer" could mean "the target type must be a subtype" or even "the target type must be a supertype". We do have the special case `e!` which can roughly serve a cast to the non-nullable version of the current static type. It is also possible to support the other concepts in a way that has no additional run-time cost (because it's using small functions that are resolved statically, which means that they can be inlined):

```dart
extension AsExtension on Object? {
  X as<X>() => this as X;
  X? asOrNull<X>() {
    var self = this; // Enable promotion.
    return self is X ? self : null;
  }
}

extension AsSubtypeExtension<X> on X {
  Y asSubtype<Y extends X>() => this as Y;
}

void main() {
  num? n = 1 as dynamic;
  n.as<int>().isEven;
  n.asSubtype<int>().isEven;
  n.asOrNull<int>()?.isEven;
}
```

It may or may not be considered as an improvement that these methods allow for subsequent method invocations (with `as` you need to say things like `(e as int).isEven`). Also, we could extend the language with generic getters in order to get a slightly less verbose syntax (https://github.com/dart-lang/language/issues/1622).

**Comment by plammens** [comment] 2024-09-02 10:42
> It is definitely possible to encounter situations where a dynamic type test (`is`) or type cast (`as`) legitimately has a target type which isn't a subtype of the current static type of the scrutinee.

Agreed, which is why I suggest adding it as an optional lint rule (which, when enabled, can be `// ignore`d where necessary) rather than a language feature.

**Comment by eernstg** [comment] 2024-09-02 11:50
We have had some discussions about this kind of feature before, but I don't think it was ever spelled out as a proposal in an issue. I created https://github.com/dart-lang/language/issues/4074 in order to have it on the table. This is a language mechanism proposal (that is, strict), but it accommodates both downcasts, upcasts, and "other" casts.

**Comment by srawlins** [comment] 2024-09-03 15:13
Thanks for the request; duplicate of https://github.com/dart-lang/sdk/issues/46170

**Closed by srawlins** 2024-09-03 15:13 UTC
Labels: area-analyzer, P3, analyzer-linter, type-enhancement
