### ISSUE TITLE
 NoSuchMethodError: The getter 'isEof' was called on null

### ISSUE THREAD

**Issue by zgliny** [dart-lang/sdk#41864] opened 2020-05-12 09:23 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.8.1`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.8.1, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
```

For additional log information, please append the contents of
file://C:\Users\Administrator\AppData\Local\Temp\report.txt.

And my flutter doctor -v is:

[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)
    • Flutter version 1.17.0 at E:\flutter
    • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.122
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by srawlins** [comment] 2020-06-12 22:53
Thanks for reporting this issue! This was previously reported at #41658; please follow along there.

**Comment by srawlins** [comment] 2020-06-12 22:53
Duplicate of #41658

**Closed by srawlins** 2020-06-12 22:53 UTC
Labels: area-analyzer
