### ISSUE TITLE
Need a way to import libraries by name without polluting the global JS namespace.

### ISSUE THREAD

**Issue by PaulAnnekov** [dart-lang/sdk#25318] opened 2015-12-27 23:09 UTC
**Describe the issue you're seeing**
I'm porting [Leaflet](http://leafletjs.com/) library to Dart for my own needs.
The code in [gist](https://gist.github.com/PaulAnnekov/df319b5d58926a196eb5) works fine for Chrome, but not for Dartium. In Dartium I get the following exception:
```
Exception: TypeError: undefined is not a function 
map package:my/leaflet/leaflet.dart_js_interop_patch.dart:35
main app.dart:4 
```

I tried to add `@JS('L')` before `library ...;` and remove direct names of functions in JS annotations from `map`, `latLng` and `tileLayer`. But when I did it, the page stopped working in both browsers %). I start to get the following exception in Chrome:
```
Uncaught TypeError: L.tileLayer is not a function
dart.main @ app.dart:5
(anonymous function) @ iterable.dart:275
init.currentScript @ iterable.dart:275
(anonymous function) @ iterable.dart:275
(anonymous function) @ iterable.dart:275
```

P.S. Porting procedure is a pain. No docs, ugly stack trace on exceptions...

**Does it happen in Dartium or when compiled to JavaScript?**
Only in Dartium

* Dart SDK version:
Dart VM version: `1.13.1 (Thu Dec 17 14:42:19 2015) on "linux_x64"`
* pkg/js version: `0.6.0`

Failing code: https://gist.github.com/PaulAnnekov/df319b5d58926a196eb5

**Comment by PaulAnnekov** [comment] 2015-12-28 18:04
I think I have found why I can't use this code:
```
@JS('L')
library L;

import 'package:js/js.dart';

@JS()
external map(String id);
``` 
It's because dart2js creates some global variable `L`:
```
// The global objects start as so-called "slow objects". For V8, this
// means that it won't try to make map transitions as we add properties
// to these objects. Later on, we attempt to turn these objects into
// fast objects by calling "convertToFastObject" (see
// [emitConvertToFastObjectFunction]).
...
var K = map();
var L = map();
var M = map();
...
```
 so when my generated code tries to call `L.map()` it fails because `L` is empty.

**Comment by jacob314** [comment] 2015-12-28 18:46
You are correct. For now use somewhat long names for the imported JS libraries to avoid collisions with minified dart2js names. In the future we'll give Dart2JS a list of names to avoid minifying to so this isn't an issue.

**Comment by PaulAnnekov** [comment] 2015-12-28 19:24
@jacob314 I have added `window.Leaflet = L;` to JS code and changed `JS('L')` to `JS('Leaflet')` ([my leaflet dart api](https://github.com/PaulAnnekov/nova_poshta_osm_sync/blob/master/lib/leaflet/leaflet.dart)). Now everything is working good in Chrome, but it still fails in Dartium:
```
Uncaught Unhandled exception:
TypeError: undefined is not a function
#0      JsFunction._apply (dart:js:1178)
#1      JsFunction.apply (dart:js:1176)
#2      map (package:nova_poshta_osm_sync/leaflet/leaflet.dart_js_interop_patch.dart:19:81)
#3      main.<main_async_body> (http://localhost:8080/app.dart:167:9)
#4      _RootZone.runUnary (dart:async/zone.dart:1149)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#7      _Future._completeWithValue (dart:async/future_impl.dart:376)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#10     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#11     _ScheduleImmediateHelper._handleMutation (dart:html:49298)
#12     MutationObserver._create.<anonymous closure> (dart:html:27545)
```

it fails on this line:
```
patch map(p0, [p1=_UNDEFINED_JS_CONST]) => js_library.context['Leaflet']['map'].apply([p0,p1].takeWhile((i) => i != _UNDEFINED_JS_CONST).toList());
```

**Comment by jacob314** [comment] 2015-12-28 19:34
When I try to repro I get blocked running pub get. Is the pubspec not
configured correctly or do I need to create a separate leaflet pub package
in a sibling directory?

Resolving dependencies...
Could not find package leaflet at "../leaflet.dart".
Depended on by:
- nova_poshta_osm_sync"

**Comment by PaulAnnekov** [comment] 2015-12-28 20:31
@jacob314 I have updated the code to make it work for you. Just run `pub serve web data`.

**Comment by jacob314** [comment] 2015-12-29 00:18
Thanks Paul. Here's a patch that makes the code work in Dartium and Dart2js.
https://codereview.appspot.com/278650043

The issue is the Leaflet library copies
Array.isArray into a local variable and then uses that copy instead of Array.isArray
Dartium then replaces Array.isArray with a polyfill that also accepts Dart List objects to make JS interop work well for Array/List.
Changing the execution order so the Dart application is loaded before Leaflet fixes the issue.
Longer term, I need to tweak the Dartium polyfill for Array so it executes earlier before any Dart code is executed perhaps immediately on page load regardless of whether the page contains Dart scripts.

**Comment by PaulAnnekov** [comment] 2015-12-30 19:43
Thanks for workaround. Will wait for a clean fix. You can rename issue name to something more relevant.

**Comment by jacob314** [comment] 2016-07-08 21:10
Duplicate of #25059

**Closed by jacob314** 2016-07-08 21:10 UTC
Labels: area-js_interop
