### ISSUE TITLE
Missing compile-time error on generics

### ISSUE THREAD

**Issue by Tienisto** [dart-lang/sdk#50390] opened 2022-11-05 00:51 UTC
Here `myFunction` should always return `double?` but the compiler only complains on nullable types `A?` ignoring any non-nullable type.

Tested on `2.18.4` and `2.19.0-255.2.beta`.

```dart
class MyClass<A> {
  A getValue() => throw UnimplementedError();
}

A? myFunction<A, B extends MyClass<A>>(B instance) {
  return instance.getValue();
}

void main() {
  // correct: compile error
  final String? a = myFunction(MyClass<double>());

  // incorrect: should be a compile error but is not
  final String b = myFunction(MyClass<double>());

  // correct
  final double? c = myFunction(MyClass<double>());
}
```

**Comment by eernstg** [comment] 2022-11-05 12:02
I believe this is working as intended. The inferred actual type arguments to `myFunction` are shown below:

```dart
class MyClass<A> {
  A getValue() => throw UnimplementedError();
}

A? myFunction<A, B extends MyClass<A>>(B instance) {
  return instance.getValue();
}

void main() {
  // Compile-time error: Cannot infer 2nd type argument.
  final String? a = myFunction(MyClass<double>());

  // Return type `dynamic` enables a dynamic cast to `String`.
  final String b = myFunction<dynamic, MyClass<double>>(MyClass<double>());

  final double? c = myFunction<double, MyClass<double>>(MyClass<double>());
}
```

In the first declaration (of `a`), type inference cannot find a value for `B`. Try it and look at the error message to get more information.

In the declaration of `b`, the inferred type arguments are `dynamic` and `MyClass<double>`. They do satisfy the given bounds (`MyClass<double> <: MyClass<dynamic>`), and the declaration as a whole is accepted during static analysis because it initializes a variable of type `String` with an expression of type `dynamic`. That is allowed, and it gives rise to a type check at run time.

You should be able to use `strict-inference` to modify the type inference such that it never infers `dynamic` in this kind of situation (see https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks for more information).

**Comment by eernstg** [comment] 2022-11-05 12:05
I'll close this issue because inference seems to work as intended, even in the case where it infers `dynamic` because nothing else works. `strict-inference` might well be the default behavior at some point in the future, but it is a breaking change, and it always takes a lot of time and work to make such things happen.

**Closed by eernstg** 2022-11-05 12:05 UTC

**Comment by Tienisto** [comment] 2022-11-05 13:38
Thanks for your quick response and the `strict-inference` hint.

I tried the same code with the `strict-inference` flag. And dart could not infer the correct type.

```dart
// a is inferred as dynamic although it should be double?
final a = myFunction(MyClass<double>());
```

I think the compiler should be able to infer the type based on the given parameters.
Here is a working Kotlin example:

```kotlin
class MyClass<A> {
    fun getValue(): A = throw Exception()
}

fun<A, B : MyClass<A>> myFunction(instance: B): A? {
    return instance.getValue()
}

fun main() {
    // [a] is correctly inferred as Double?
    val a = myFunction(MyClass<Double>())
}
```

**Comment by eernstg** [comment] 2022-11-06 22:34
The situation in Kotlin is different, because Kotlin type parameters are invariant unless declared covariant (`out`) or contravariant (`in`). You might wish to vote for https://github.com/dart-lang/language/issues/524 in order to obtain support for a similar treatment of variance in Dart.

Currently (and since the very beginning), Dart type parameters have been treated as covariant, and soundness of the heap is maintained by performing type checks at run time whenever needed. For instance, you are allowed to let a variable of type `List<num>` refer to an object of type `List<int>`, but in return for the extra flexibility there will be a dynamic type check each time you add an object to said list.

In the given example, this means that `MyClass<S>` is a subtype of `MyClass<Object?>` for all `S` (and a subtype of `MyClass<dynamic>`, and in general a subtype of `MyClass<T>` whenever `T` is a supertype of `S`).

This again means that `myFunction<dynamic, MyClass<double>>(MyClass<double>())` is type correct, so you should not get a compile-time error on that outcome, and it is indeed true that the returned object has a type which is a subtype of `dynamic` (which is the inferred type of `a`).

Dart type inference gives priority to the context type, so you could guide the chosen type argument by declaring the type of `a`:

```dart
final double? a = myFunction(MyClass<double>()); // No errors.
```

I guess you're not looking for a solution &mdash; this issue is reporting an unexpected behavior, and that's useful to know about in its own right.

However, if you are interested in a workaround, you could simplify the whole situation by dropping the type parameter `B`:

```dart
class MyClass<A> {
  A? getValue() => null;
}

A? myFunction<A>(MyClass<A> instance) {
  return instance.getValue();
}

void main() {
  final double? a = myFunction(MyClass());
}
```

The type parameter `B` has no other effect than making type inference harder, so you might want to use a more direct style whenever possible, as in this last example.

**Comment by eernstg** [comment] 2022-11-06 22:55
I was surprised that the hint doesn't go away when the inference succeeds. Cf. https://github.com/dart-lang/sdk/issues/50397.
