### ISSUE TITLE
Observatory: Timeline is not loading in Android device

### ISSUE THREAD

**Issue by utkarsh-UK** [dart-lang/sdk#41257] opened 2020-03-30 18:58 UTC
Observatory Feedback
I was running my app in profile mode but in obsrvatory, the timeline is not at all showing for any of the stream profile.

**Comment by devoncarew** [comment] 2020-03-31 17:45
@utkarsh-UK - what version of Flutter and the Dart SDK are you using?

**Comment by utkarsh-UK** [comment] 2020-03-31 17:54
Flutter version - 1.12.12+hotfix.8 and Dart sdk version - 2.1.0

**Comment by devoncarew** [comment] 2020-03-31 18:06
@utkarsh-UK, thanks!

I looks like that's the current flutter stable version, but `1.16.4-pre.34` is available in flutter master. That's quite a bit newer. Perhaps see if your issue reproduces with the flutter `beta` channel?

**Comment by utkarsh-UK** [comment] 2020-03-31 18:09
Okay will check that, Thanks!

**Comment by andromeda911** [comment] 2020-04-06 18:10
Hi! My current versions:

Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (7 days ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

and timeline does not work. In browser console logs i see that error: 

```
Uncaught ReferenceError: tr is not defined
    at updateTimeline (timeline.js:538)
    at populateTimeline (timeline.js:562)
    at onMessage (timeline_message_handler.js:29)
```
What can I do except change the Flutter branch?
Thanks.

**Comment by CountPablo** [comment] 2020-04-06 20:54
I just ran into the same issue on the stable branch

Latest version of stable (1.12.13+hotfix.9): no timeline (this issue)
Latest version of beta (1.15.17): I get issue [#31284](url)
Latest version of dev (1.18.0): I get issue [#31284](url)
Latest version of master (1.18.1-pre.19): I get issue [#31284](url)

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.18.1-pre.19, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.43.2)
[√] Connected device (1 available)

• No issues found!

**Comment by bkonyi** [comment] 2020-04-11 00:03
I've just tested this on stable and can reproduce, but this is fixed on the other channels. The timeline viewer uses an API that was deprecated by the Chrome team and broke the viewer in newer versions of Chrome (see [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1036492)). We've since rolled in a newer version of the viewer (see [here](https://github.com/dart-lang/sdk/commit/82e2d4cabcdf4076ca27e22e3d277c09dc8903cb)) which will resolve the issue once the next Flutter stable version is released.

In the meantime, if you need to examine the timeline please either switch to a non-stable branch of Flutter or use the DevTools timeline viewer instead.

**Closed by bkonyi** 2020-04-11 00:03 UTC
Labels: area-observatory
