### ISSUE TITLE
Analyzer: Inconsistent "A value of type 'T' can't be assigned to a variable of type 'Bar'" error

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#37200] opened 2019-06-07 19:31 UTC
I believe the analyzer is incorrectly complaining about the `Bar bar = foo;` in the following example:

```dart
void main() {
  Foo foo = Foo();
  
  if (foo.foo is Bar) {
    Bar bar = foo.foo; // This is OK.
    print(bar);
  }
}

class Foo<T> {  
  T foo;
   
  void bar() {
    if (foo is Bar) {
      Bar bar = foo; // Here the analyzer complains: "A value of type 'T' can't be assigned to a variable of type 'Bar'/"
      print(bar);
    }
  }
}

class Bar {
  
}
```

Run this code in DartPad: https://dartpad.dartlang.org/f592851238ef5d648100d1b97bf4b9d1

**Comment by eernstg** [comment] 2019-06-10 14:49
This is working as intended: The type of `foo` is not promoted in `if (foo is Bar) ...` because `foo` is an instance variable (and they are never promoted, that only applies to local variables, which includes formal parameters).

This means that the type check on the initialization of `bar` is whether `T` is assignable to `Bar`. It isn't, because `T` and `Bar` are simply unrelated types (we only know that `T` is some type such that `T <: Object`).

`Bar bar = foo.foo` is actually somewhat misleading: There's no promotion for `foo.foo` (that's also not a local variable), but since you've used the raw type `Foo` in the declaration of `foo` (which means `Foo<dynamic>`), the expression `foo.foo` actually has type `dynamic`, so you can assign it to a variable of type `Bar`.

I'd recommend that you use whole types (like `Foo<Something> foo;`) or no types (like `var foo = e;`, where you may get a suitable type from the initializing expression `e`), and not "half" types like `Foo`.

I'll close this issue because the reported behavior is as intended.

**Closed by eernstg** 2019-06-10 14:49 UTC
Labels: area-analyzer, closed-as-intended
