### ISSUE TITLE
language/vm/optimized_stacktrace_test crashed on windows release ia32

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#28276] opened 2017-01-05 17:44 UTC
Will mark Pass, Crash in the status file.

**Comment by mraleph** [comment] 2017-11-16 12:05
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by mkustermann** [comment] 2019-02-07 14:30
There's been no entry in the flakiness database. Assuming stale.

**Closed by mkustermann** 2019-02-07 14:30 UTC
Labels: area-vm, gardening, type-bug
