### ISSUE TITLE
numeric programming issue

### ISSUE THREAD

**Issue by BillChan96** [dart-lang/sdk#36128] opened 2019-03-06 16:20 UTC
When i try to calculate by a number with a number and i get the result is not very reasonable (i think).

i test with two cases:
Case 1: `0.179 * 100 = 17.9` (right)
Case 2: `0.169 * 100 = 16.900000000000002` (??? i think result equal is 16.9)

How do fix this issue?

Thanks.

**Comment by eernstg** [comment] 2019-03-06 17:20
This is not a Dart specific issue, it is a property of IEEE 754 floating point numbers, and of _any_ computer based representation of real numbers (actually, we can just represent a small set of rational numbers, of course).

Try, e.g., to enter '0.169' on [this page](https://www.h-schmidt.net/FloatConverter/IEEE754.html) in the field 'You entered' and press ENTER. Then you'll see that the IEEE 754 representation of that number is an approximation, because none of the bit patterns that you have available is _exactly_ 0.169.

The IEEE 754 standard defines how to represent various kinds of floating point numbers, and how to compute various values (like adding or multiplying two numbers, taking overflow into account, etc), but I'm not quite sure how tight the standard is on the transformation from a given text to the IEEE 754 bit pattern. So maybe there is more than one correct bit pattern for '0.169'. In any case, the resulting pattern won't be representation of 0.169, it will just be in the vicinity.

**Comment by eernstg** [comment] 2019-03-06 17:22
I'll close this issue with 'working as intended'.

**Closed by eernstg** 2019-03-06 17:22 UTC
Labels: closed-as-intended
