### ISSUE TITLE
Inexplicable errors from VM

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#26853] opened 2016-07-10 20:10 UTC
This has been happening at random places and times over the last 2-3 days.

```
Dart analysis server, SDK version 1.19.0-edge.ab14b12962262bbfb8c5e28ce1ceb0a879e6492c, server version 1.15.0, FATAL error: Failed to perform operation: Instance of 'PerformAnalysisOperation'
Class 'int' has no instance method '_sendNotices'.

NoSuchMethodError: method not found: '_sendNotices'
Receiver: 0
Arguments: [Type: class 'dynamic', _ImmutableList len:0]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      PerformAnalysisOperation.perform.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:383:7)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#4      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:382:41)
#5      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:879:17)
#6      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#7      Timer._runSingleShotCallback (dart:async/timer.dart:189)
#8      _rootRunTask (dart:async/zone.dart:1279)
#9      _CustomZone.runTask (dart:async/zone.dart:1157)
#10     Timer._createSingleShotTimerTask.<anonymous closure> (dart:async/timer.dart:181)
#11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

  This just cannot be `true`.
  We call `_sendNotices` on `this`.

![image](https://cloud.githubusercontent.com/assets/384794/16715806/4b95575e-469f-11e6-814c-f65b88ba09f3.png)

**Comment by mraleph** [comment] 2016-07-11 13:28
@scheglov is there a repro? (e.g. does did it happen while running some tests?) It's ok if it fails very rarely - we just need to reproduce it locally to be able to diagnose what is happening.

**Comment by scheglov** [comment] 2016-07-11 16:01
I see it on Analysis Server restarts, when I use it from IDEA to analyze `pkg/analyzer` and `pkg/analysis_server`. I run Analysis Server from sources, not the snapshot.

**Comment by a-siva** [comment] 2016-07-11 16:09
Can you post a command line of how you analyze pkg/analyzer and pkg/analysis_server it would help us narrow down the problem.

**Comment by scheglov** [comment] 2016-07-11 16:12
Sorry, it's not a purely CLI application.
After it starts, it uses stdin and stdout to talk to the client that started it.

```
debugStream: 1468252757086 started analysis server:
debugStream:   /Users/scheglov/Applications/dart-sdk/bin/dart --observe --max_profile_depth=128 --collect_code=false --code_comments=true --old_gen_growth_rate=2800 /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/bin/server.dart --client-id=IntelliJ_IDEA --client-version=IC-163.SNAPSHOT --useAnalysisHighlight2 --file-read-mode=normalize-eol-always --port=4000 --internal-print-to-console --finer-grained-invalidation --incremental-resolution-log=console --instrumentation-log-file2=/Users/scheglov/tmp/server-logs/log.txt
debugStream: 1468252758454 <= {"event":"server.connected","params":{"version":"1.15.0","pid":59848}}
debugStream: 1468252758534 <= {"id":"0","result":{"version":"1.15.0"}}
debugStream: 1468252758538 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1468252757132}
debugStream: 1468252758538 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins":true,"generateDart2jsHints":false,"generateHints":true,"generateLints":false}},"clientRequestTime":1468252757144}
debugStream: 1468252758538 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server","/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer","/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer_cli","/Users/scheglov/dart/test"],"excluded":["/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/.idea","/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/.pub","/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer_cli/.pub","/Users/scheglov/dart/test/.pub"],"packageRoots":{}},"clientRequestTime":1468252757161}
debugStream: 1468252758538 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/lib/src/services/correction/util.dart"]},"clientRequestTime":1468252757162}
debugStream: 1468252758539 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/lib/src/services/correction/util.dart"],"OVERRIDES":["/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/lib/src/services/correction/util.dart"],"NAVIGATION":["/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/lib/src/services/correction/util.dart"],"IMPLEMENTED":["/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/lib/src/services/correction/util.dart"]}},"clientRequestTime":1468252757162}
debugStream: 1468252758545 <= {"id":"1"}
debugStream: 1468252758553 <= {"id":"2"}
```

  I believe the crash happens as a result of the work performed after (much after) `analysis.setAnalysisRoots`.

**Comment by bwilkerson** [comment] 2016-07-11 16:14
I can't offer a reproduction case, but I just saw an exception that appears likely to be related. (If not, I'll be happy to move it to a new issue.)

```
The null object does not have a method '_subFromInteger'.

NoSuchMethodError: method not found: '_subFromInteger'
Receiver: null
Arguments: [16456]

#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      int.- (dart:core-patch/integers.dart:17)
#3      _UpdateElementOffsetsVisitor.visitElement (package:analyzer/src/task/incremental_element_builder.dart:669)
#4      GeneralizingElementVisitor.visitExecutableElement (package:analyzer/dart/element/visitor.dart:104)
#5      GeneralizingElementVisitor.visitPropertyAccessorElement (package:analyzer/dart/element/visitor.dart:165)
#6      PropertyAccessorElementImpl.accept (package:analyzer/src/dart/element/element.dart:7643)
#7      ElementImpl.safelyVisitChildren (package:analyzer/src/dart/element/element.dart:3099)
#8      AbstractClassElementImpl.visitChildren (package:analyzer/src/dart/element/element.dart:226)
#9      ClassElementImpl.visitChildren (package:analyzer/src/dart/element/element.dart:1057)
#10     GeneralizingElementVisitor.visitElement (package:analyzer/dart/element/visitor.dart:100)
#11     _UpdateElementOffsetsVisitor.visitElement (package:analyzer/src/task/incremental_element_builder.dart:697)
#12     GeneralizingElementVisitor.visitClassElement (package:analyzer/dart/element/visitor.dart:89)
#13     AbstractClassElementImpl.accept (package:analyzer/src/dart/element/element.dart:108)
#14     IncrementalCompilationUnitElementBuilder._replaceNode (package:analyzer/src/task/incremental_element_builder.dart:466)
#15     IncrementalCompilationUnitElementBuilder._processUnitMembers (package:analyzer/src/task/incremental_element_builder.dart:429)
#16     IncrementalCompilationUnitElementBuilder.build (package:analyzer/src/task/incremental_element_builder.dart:130)
#17     AnalysisContextImpl._sourceChanged (package:analyzer/src/context/context.dart:1864)
#18     AnalysisContextImpl.handleContentsChanged (package:analyzer/src/context/context.dart:1101)
#19     AnalysisServer.updateContent.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1345)
#20     List.forEach (dart:core-patch/growable_array.dart:254)
#21     AnalysisServer.updateContent.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1338)
#22     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:345)
#23     AnalysisServer.updateContent (package:analysis_server/src/analysis_server.dart:1283)
#24     AnalysisDomainHandler.updateContent (package:analysis_server/src/domain_analysis.dart:302)
#25     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:208)
#26     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:758)
#27     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#28     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:754)
#29     _rootRun (dart:async/zone.dart:1404)
#30     _CustomZone.run (dart:async/zone.dart:1256)
#31     _CustomZone.runGuarded (dart:async/zone.dart:1154)
#32     runZoned (dart:async/zone.dart:1790)
#33     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:753)
#34     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169)
#35     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#36     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:160)
#37     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:109)
#38     _rootRunUnary (dart:async/zone.dart:1412)
#39     _CustomZone.runUnary (dart:async/zone.dart:1267)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1162)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#46     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#47     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#48     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#50     _rootRunUnary (dart:async/zone.dart:1412)
#51     _CustomZone.runUnary (dart:async/zone.dart:1267)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1162)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#55     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#56     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#57     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#58     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#59     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#60     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#61     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#62     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#63     _rootRunUnary (dart:async/zone.dart:1412)
#64     _CustomZone.runUnary (dart:async/zone.dart:1267)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1162)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#68     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#69     _StreamController._add (dart:async/stream_controller.dart:635)
#70     _StreamController.add (dart:async/stream_controller.dart:581)
#71     _Socket._onData (dart:io-patch/socket_patch.dart:1659)
#72     _rootRunUnary (dart:async/zone.dart:1416)
#73     _CustomZone.runUnary (dart:async/zone.dart:1267)
#74     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1162)
#75     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#76     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#77     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#78     _StreamController._add (dart:async/stream_controller.dart:635)
#79     _StreamController.add (dart:async/stream_controller.dart:581)
#80     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1226)
#81     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
#82     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#83     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#84     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#85     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment] 2016-07-11 16:18
On closer examination, I think the trace I just posted is our's.

**Comment by scheglov** [comment] 2016-07-11 18:43
Another exception.

```
Dart analysis server, SDK version 1.19.0-edge.ab14b12962262bbfb8c5e28ce1ceb0a879e6492c, server version 1.15.0, FATAL error: Failed to perform operation: Instance of 'PerformAnalysisOperation'
The null object does not have a getter 'resultProvider'.

NoSuchMethodError: method not found: 'resultProvider'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:556:11)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#4      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:554:42)
#5      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:565:29)
```

![image](https://cloud.githubusercontent.com/assets/384794/16742453/98ffe744-475c-11e6-9434-57ca0f75e55c.png)

**Comment by scheglov** [comment] 2016-07-11 18:44
Another crash after restart.

```
./vm/object.h: 5331: error: Handle check failed: saw TypeArguments: (0) [TypeParameter: name E; index: 2; class: _ListToCollectionTaskInput@205507815; bound: Object] expected Instance
debugStream: 1468262608135 => {"id":"12","method":"server.shutdown","clientRequestTime":1468262608135}
```

**Comment by scheglov** [comment] 2016-07-11 18:47
Another stack trace.

```
Caused by Class '_Type' has no instance method '_becomeParentOf'.

NoSuchMethodError: method not found: '_becomeParentOf'
Receiver:  Function Type: (dynamic, dynamic, dynamic) => void (class: TaskRun, args: TypeArguments: (0) [Type: class 'dynamic'] [Type: class 'dynamic'])
Arguments: [Instance of 'TypeNameImpl']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      NodeListImpl.addAll (package:analyzer/src/dart/ast/ast.dart:7705:18)
#3      NodeListImpl.NodeListImpl (package:analyzer/src/dart/ast/ast.dart:7633:5)
```

![image](https://cloud.githubusercontent.com/assets/384794/16742582/16fca4c0-475d-11e6-9cb7-9784ffd481e4.png)

**Comment by scheglov** [comment] 2016-07-11 18:50
Another one.

```
Dart analysis server, SDK version 1.19.0-edge.ab14b12962262bbfb8c5e28ce1ceb0a879e6492c, server version 1.15.0, FATAL error: Failed to perform operation: Instance of 'PerformAnalysisOperation'
Class '_TypeParameter' has no instance method '_noSuchMethod' with matching arguments.

NoSuchMethodError: incorrect number of arguments passed to method named '_noSuchMethod'
Receiver: TypeParameter: name E; index: 2; class: _ListToCollectionTaskInput@205507815; bound: Object
Tried calling: _noSuchMethod(true, "_noSuchMethod@0150898", 0, _ImmutableList len:5, _LinkedHashMap len:0)
Found: _noSuchMethod(isMethod, memberName, type, arguments, namedArguments)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#3      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#4      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#5      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#6      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#7      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#8      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#9      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
```

**Comment by scheglov** [comment] 2016-07-11 19:01
This fallout of crashes happens with the bleeding edge, `1.18.0-dev.4.0`, `1.18.0-dev.3.0` and `1.18.0-dev.2.0`. I had to rollback to `1.17.1` to make Analysis Server to work. It might be easier to reproduce with `--checked` flag.

**Comment by scheglov** [comment] 2016-07-18 17:40
```
[136972019]  ERROR - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.19.0-edge.3305201211dc55f21ae8ad052fdd2a9ad7d06d31, server version 1.15.0, error: Task failed: ParseDartTask for source /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/dart/ast/ast.dart
Unexpected exception while performing ParseDartTask for source /Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/dart/ast/ast.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350:7)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1221:27)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1219:50)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371:37)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:879:17)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     Timer._runSingleShotCallback (dart:async/timer.dart:189)
#11     _rootRunTask (dart:async/zone.dart:1479)
#12     _CustomZone.runTask (dart:async/zone.dart:1357)
#13     Timer._createSingleShotTimerTask.<anonymous closure> (dart:async/timer.dart:181)
#14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Class 'int' has no instance method 'call'.

NoSuchMethodError: method not found: 'call'
Receiver: 1
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _GeneratedStreamImpl._createSubscription (dart:async/stream_impl.dart:512)
#3      _StreamImpl.listen (dart:async/stream_impl.dart:470)
#4      Stream.isEmpty (dart:async/stream.dart:837)
#5      NodeListImpl.addAll (package:analyzer/src/dart/ast/ast.dart:7699:33)
#6      NodeListImpl.NodeListImpl (package:analyzer/src/dart/ast/ast.dart:7633:5)
#7      ArgumentListImpl.ArgumentListImpl (package:analyzer/src/dart/ast/ast.dart:379:22)
#8      Parser.parseArgumentList (package:analyzer/src/generated/parser.dart:2357:18)
#9      Parser._parseAssignableExpressionNotStartingWithSuper (package:analyzer/src/generated/parser.dart:4415:37)
#10     Parser._parseAssignableExpression (package:analyzer/src/generated/parser.dart:4394:12)
#11     Parser._parsePostfixExpression (package:analyzer/src/generated/parser.dart:7667:26)
#12     Parser._parseUnaryExpression (package:analyzer/src/generated/parser.dart:8567:12)
#13     Parser._parseMultiplicativeExpression (package:analyzer/src/generated/parser.dart:7242:20)
#14     Parser._parseAdditiveExpression (package:analyzer/src/generated/parser.dart:4329:20)
#15     Parser._parseShiftExpression (package:analyzer/src/generated/parser.dart:8026:20)
#16     Parser._parseBitwiseAndExpression (package:analyzer/src/generated/parser.dart:4536:20)
#17     Parser._parseBitwiseXorExpression (package:analyzer/src/generated/parser.dart:4559:20)
#18     Parser.parseBitwiseOrExpression (package:analyzer/src/generated/parser.dart:2377:20)
#19     Parser._parseRelationalExpression (package:analyzer/src/generated/parser.dart:7920:29)
#20     Parser._parseEqualityExpression (package:analyzer/src/generated/parser.dart:5877:20)
#21     Parser._parseLogicalAndExpression (package:analyzer/src/generated/parser.dart:7003:29)
#22     Parser.parseLogicalOrExpression (package:analyzer/src/generated/parser.dart:3210:29)
#23     Parser.parseIfNullExpression (package:analyzer/src/generated/parser.dart:3145:29)
#24     Parser.parseConditionalExpression (package:analyzer/src/generated/parser.dart:2947:28)
#25     Parser.parseExpression2 (package:analyzer/src/generated/parser.dart:3022:29)
#26     Parser.parseExpression2 (package:analyzer/src/generated/parser.dart:3036:61)
#27     Parser._parseNonLabeledStatement (package:analyzer/src/generated/parser.dart:7453:11)
#28     Parser.parseStatement2 (package:analyzer/src/generated/parser.dart:3391:27)
#29     Parser.parseBlock (package:analyzer/src/generated/parser.dart:2405:29)
#30     Parser._parseFunctionBody (package:analyzer/src/generated/parser.dart:6436:53)
#31     Parser._parseConstructor (package:analyzer/src/generated/parser.dart:5496:14)
#32     Parser.parseClassMember (package:analyzer/src/generated/parser.dart:2613:16)
#33     Parser._parseClassMembers (package:analyzer/src/generated/parser.dart:4864:30)
#34     Parser._parseClassDeclaration (package:analyzer/src/generated/parser.dart:4815:17)
#35     Parser._parseCompilationUnitMember (package:analyzer/src/generated/parser.dart:5183:14)
#36     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:2887:13)
#37     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:2781:12)
#38     ParseDartTask.internalPerform (package:analyzer/src/task/dart.dart:4015:35)
#39     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338:9)
#40     AnalysisTask.perform (package:analyzer/task/model.dart:238:7)
#41     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284:10)
#42     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255:11)
#43     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1221:27)
#44     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212:15)
#45     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1219:50)
#46     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371:37)
#47     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:879:17)
#48     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#49     Timer._runSingleShotCallback (dart:async/timer.dart:189)
#50     _rootRunTask (dart:async/zone.dart:1479)
#51     _CustomZone.runTask (dart:async/zone.dart:1357)
#52     Timer._createSingleShotTimerTask.<anonymous closure> (dart:async/timer.dart:181)
#53     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#54     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#55     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:210)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
[136972019]  ERROR - yzer.DartAnalysisServerService - IntelliJ IDEA (Community Edition) 2016.3 EAP  Build #IC-163.SNAPSHOT 
[136972019]  ERROR - yzer.DartAnalysisServerService - JDK: 1.8.0_72 
[136972019]  ERROR - yzer.DartAnalysisServerService - VM: Java HotSpot(TM) 64-Bit Server VM 
[136972019]  ERROR - yzer.DartAnalysisServerService - Vendor: Oracle Corporation 
[136972019]  ERROR - yzer.DartAnalysisServerService - OS: Mac OS X 
[136972019]  ERROR - yzer.DartAnalysisServerService - Last Action: EditorBackSpace 
```

**Comment by mit-mit** [comment] 2016-07-18 19:37
@scheglov @kevmoo does this block 1.18? I don't see any updates over the past week,  I don't see any comments on how this might impact customers, and the bug appear not to be assigned to anyone?

**Comment by scheglov** [comment] 2016-07-18 19:54
I played some more with Dart VM options and it seems that the problem happens only with `--code_comments=true`.

**Comment by mit-mit** [comment] 2016-07-18 20:00
OK, if that is the case, then this should not block the 1.18 release to stable, right?

**Comment by scheglov** [comment] 2016-07-18 20:01
I'd say - no, it does not block 1.18 release.
But maybe VM developers should confirm this.

**Comment by mit-mit** [comment] 2016-07-18 20:02
@a-siva, do you agree?

**Comment by mraleph** [comment] 2016-07-19 11:13
Code comments don't affect the generated code - these are just strings collected in an array on the side, they are used to annotate generated code when disassembling it... However emitting code comments obvious affects GC - which in turn affects all kinds of things. 

I think this indicates that we are seeing some sort of a flaky code generation / GC issue, might be another issue with a background compiler. 

We definitely need someone to look into this, otherwise we potentially will have issues with the internal roll again. 

If @a-siva can't find anybody available on the VM team, I can volunteer to take a look due to my experience with debugging flaky crashes.

**Comment by mit-mit** [comment] 2016-07-19 12:02
@scheglov any chance you can work on getting a simplified repro? Then @mraleph has promised to take a look at what might cause it.

**Comment by mraleph** [comment] 2016-07-19 12:04
Just removing IDE from the equation could already simplify things a bit. 

Is it possible to record a log of requests IDE asks analysis server and then replay that again and again?

**Comment by scheglov** [comment] 2016-07-19 15:42
I cannot reproduce it today.
Usually several Analysis Server restarts was enough to trigger the problem.
I've tried about `20` times now, with the same VM flags and VM is still alive.

Was able to do this yesterday.
Maybe something was fixed in VM?

**Comment by mit-mit** [comment] 2016-07-21 11:46
Closing, please re-open if this starts reproing again.

**Closed by mit-mit** 2016-07-21 11:46 UTC
Labels: area-vm, Type: bug
