### ISSUE TITLE
causal_stacks/async_throws_stack_no_causal_test breaks on dartk-optcounter-linux-release-x64 and dartk-optcounter-linux-release-ia32

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#41251] opened 2020-03-29 03:51 UTC
With the NNBD unfork CL at [https://dart-review.googlesource.com/c/sdk/+/138902](https://dart-review.googlesource.com/c/sdk/+/138902/) we see failures in
causal_stacks/async_throws_stack_no_causal_test
python tools/test.py -n dartk-optcounter-linux-release-x64 service/step_through_mixin_from_sdk_test

```
/=====================================================================================================\
| vm/dart/causal_stacks/async_throws_stack_no_causal_test broke (Pass -> RuntimeError, expected Pass) |
\=====================================================================================================/

--- Command "vm" (took 10.000555s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --no-causal-async-stacks --no-lazy-async-stacks --optimization-counter-threshold=5 --random-seed=421142442 --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/runtime/tests/vm/dart/causal_stacks/async_throws_stack_no_causal_test.dart

exit code:
255

stdout:
Actual stack:
#0      throwSync (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:16:3)
#1      allYield3 (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:39:3)
#2      _rootRunUnary (dart:async/zone.dart:1162:47)
#3      _RootZone.runUnary (dart:async/zone.dart:1415:12)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#7      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:117:13)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:5)

Expected line 3 to be `^#2      _RootZone.runUnary ` but was `#2      _rootRunUnary (dart:async/zone.dart:1162:47)`

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      Expect._fail (package:expect/expect.dart:677:5)
#1      Expect.isTrue (package:expect/expect.dart:135:5)
#2      assertStack (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:163:14)
#3      doTestAwaitCatchError (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart:204:3)
#4      _rootRunUnary (dart:async/zone.dart:1162:47)
#5      _RootZone.runUnary (dart:async/zone.dart:1415:12)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#9      Future._completeError (dart:async/future_impl.dart:534:5)
#10     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:39:15)
#11     allYield (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart)
#12     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:81:61)
#13     _RootZone.runBinary (dart:async/zone.dart:1419:54)
#14     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#15     Future._propagateToListeners.handleError (dart:async/future_impl.dart:698:47)
#16     Future._propagateToListeners (dart:async/future_impl.dart:719:24)
#17     Future._completeError (dart:async/future_impl.dart:534:5)
#18     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:39:15)
#19     allYield2 (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart)
#20     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:81:61)
#21     _RootZone.runBinary (dart:async/zone.dart:1419:54)
#22     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#23     Future._propagateToListeners.handleError (dart:async/future_impl.dart:698:47)
#24     Future._propagateToListeners (dart:async/future_impl.dart:719:24)
#25     Future._completeError (dart:async/future_impl.dart:534:5)
#26     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:39:15)
#27     allYield3 (file:///b/s/w/ir/runtime/tests/vm/dart/causal_stacks/utils.dart)
#28     _rootRunUnary (dart:async/zone.dart:1162:47)
#29     _RootZone.runUnary (dart:async/zone.dart:1415:12)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#33     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:117:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:5)

```

**Comment by mkustermann** [comment] 2020-03-30 08:44
Side note: This test is testing something none of our users are using (afaik) - (with causal/lazy async stacks disabled).

**Comment by cskau-g** [comment] 2020-04-01 07:19
I'm not entirely sure what I need to do for this one.
The test is passing at HEAD. And if a CL changes the stacks it needs to update the tests accordingly.
Is there anything I can do to help?

**Comment by mkustermann** [comment] 2020-04-01 11:59
@cskau-g As Siva points out this happens with the unforking CL. Here's the exact reproduction instructions:

```
% git cl patch https://dart-review.googlesource.com/c/sdk/+/138902/
% tools/build.py -mrelease -ax64 runtime_kernel
% out/ReleaseX64/dart --deterministic --no-causal-async-stacks --no-lazy-async-stacks --optimization-counter-threshold=5 --random-seed=421142442 runtime/tests/vm/dart/causal_stacks/async_throws_stack_no_causal_test.dart
Actual stack:                                                                                 
#0      throwSync
...                                
```

**Comment by a-siva** [comment] 2020-05-08 00:49
Any updates on this? we would like to close all unfork related issues.

**Comment by mkustermann** [comment] 2020-05-08 07:32
@a-siva I think it's safe to just remove the NNBD unfork labels from this github issue. There were already differences in behavior on optcounter bots before unfork (see e.g. https://github.com/dart-lang/sdk/issues/39525#issuecomment-580725029)

**Comment by lrhn** [comment] 2020-07-02 20:12
I just broke the same test with https://dart-review.googlesource.com/c/sdk/+/152853
It failed because a line number in the stack trace changed, which it did because I added more documentation to a file.

Please, please do not have this kind of tests which requires exact match against implementation details of things that are completely unrelated to the thing being tested.
The test failing is not catching any bugs, it's just detecting *change*.

(If you do have tests which fail on unrelated changes, at least make sure that the test failure output gives the path of a script which can update the expectation. Otherwise you'll just see people accept the failure and file bugs about it so you can fix it. You can consider this comment an example of that :imp:.)

**Comment by mkustermann** [comment] 2020-12-03 14:53
@cskau-g Could you ensure the stack trace tests are running (i.e. not skipped) as well as passing in the above mentioned configurations? Then we can close the issue.

**Closed** 2021-02-02 09:52 UTC
Labels: area-vm, vm-nnbd-unfork-sdk
