### ISSUE TITLE
[analyzer] Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by navaronbracke** [dart-lang/sdk#48657] opened 2022-03-24 09:26 UTC
I noticed that when switching git branches outside of VSCode, the analyzer doesn't re-analyze the code at times.

I did use an external tool (Sourcetree) to do git commands (pull, rebase, checkout, etc.)

Example:
- I open Sourcetree, checkout dev
- I open the project code in VSCode
- I open the file foo.dart which has a class Foo and realize it needs a new method
- I go back to Sourcetree (while leaving VSCode open in the background)
- checkout new branch feature
- I go back to VScode
- I implement the new method, use it elsewhere and commit my changes
- I switch back over to Sourcetree (while leaving VSCode open in the background)
- I checkout dev (doesn't matter if I actually did any git commands)
- I checkout feature again
- I switch back over to VScode
- The analyzer reports an error about the new method not existing
- I go to the implementation file
- The analyzer catches up and error goes away

I did get the following error while doing the above steps.

```
[Error - 9:59:40 AM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 9:59:40 AM] An error occurred while handling textDocument/codeAction request: RangeError (index): Invalid value: Not in inclusive range 0..3: 4
#0      List.[] (dart:core-patch/growable_array.dart:281:36)
#1      ElementWalker.getFunction (package:analyzer/src/generated/declaration_resolver.dart:171:18)
#2      ResolutionVisitor.visitMethodDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:827:27)
#3      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7177:50)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#5      ResolutionVisitor.visitClassDeclaration.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:246:22)
#6      ResolutionVisitor._withNameScope (package:analyzer/src/dart/resolver/resolution_visitor.dart:1409:8)
#7      ResolutionVisitor.visitClassDeclaration.<anonymous closure> (package:analyzer/src/dart/resolver/resolution_visitor.dart:227:7)
#8      ResolutionVisitor._withElementWalker (package:analyzer/src/dart/resolver/resolution_visitor.dart:1398:8)
#9      ResolutionVisitor.visitClassDeclaration (package:analyzer/src/dart/resolver/resolution_visitor.dart:226:5)
#10     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1494:50)
#11     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7813:20)
#12     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2105:21)
#13     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:765:10)
#14     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2098:50)
#15     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:742:10)
#16     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:138:7)
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#18     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:137:11)
#19     AnalysisDriver._computeResolvedLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1527:65)
#20     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#21     AnalysisDriver._computeResolvedLibrary (package:analyzer/src/dart/analysis/driver.dart:1514:20)
#22     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1085:22)
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2137:24)
<asynchronous suspension>
```

Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"
Dart Code `v3.36.0`

**Comment by asashour** [comment] 2022-03-24 15:19
I assume the IDE controls the analyzer server, not the other way around.

**Comment by bwilkerson** [comment] 2022-04-25 20:12
@scheglov @DanTup

**Comment by scheglov** [comment] 2022-04-25 22:06
I was not able to reproduce this issue with IntelliJ.

I was changing a class in a file, and its test in another file.
There were no changes to any configuration files, such as `pubspec.yaml`, only 2 Dart files.
IntelliJ was in background, I switched git branches from command line.
The server was reporting `Watch` events in the instrumentation log instantly, for both files.

**Comment by navaronbracke** [comment] 2022-04-26 06:44
@scheglov A colleague of mine uses IntelliJ and we work on the same codebase. I could ask if he experienced the same issue. If he can't reproduce it, it's probably a VSCode bug? (DartCode or IDE related)

**Comment by scheglov** [comment] 2022-04-26 07:14
I cannot say that this is a Dart Code or VS Code bug, because whatever commands they send, this should not result in such exception in the server. But it might be that a way Dart Code talks to the server that happens in a way that we failed to anticipate and make it right.

**Comment by navaronbracke** [comment] 2022-04-26 07:15
According to my colleague he never had any issues switching branches and such on IntelliJ. So either this is a VSCode bug _or_ a Sourcetree bug. I think it's the latter, as it's not the first time Sourcetree gave me issues. I'll try switching over to a different external program. If the issue persists when I switched, then we might need to take a deeper look at it.

**Comment by DanTup** [comment] 2022-04-26 09:41
@navaronbracke can you reliably reproduce this? If you can make an example project and exact steps it might be easier to track down. Whatever VS Code and/or SourceTree or doing shouldn't really lead to this sort of exception, so even if it seems to only occur with one specific tool, it would be good to track down.

**Comment by navaronbracke** [comment] 2022-08-16 09:04
@DanTup I haven't had issues with switching branches for a long while. I never managed to reproduce it back-to-back.
I did get the occasional `textDocument` failure on other things, but those were nearly not as disruptive. Usually just a warning pop-up in VSCode and the analyzer recovers without any problems.

Honestly, I forgot about it after the issue seemed to vanish on my end.

Currently running with Version: 1.70.0 (Universal) | DartCode v3.46.1

**Comment by DanTup** [comment] 2022-08-22 17:50
Thanks. I'll close this if the original issue is gone, although I am still interested in errors/stack traces/logs if you still see these types of errors for other actions. Most types of failed requests generally shouldn't break the server, although it would be useful to know about them to see if they can be handled better.

**Closed by DanTup** 2022-08-22 17:50 UTC
Labels: area-analyzer, P2
