### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by wuyuancai** [dart-lang/sdk#36924] opened 2019-05-10 14:23 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.7141.44`
- `2.2.1-edge.f6768b6fb3e58bb704aca1e22a7ffd11e7ff07cb`
- `IC-191.7141.44, JRE 1.8.0_202-release-1483-b49x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.2.1-edge.f6768b6fb3e58bb704aca1e22a7ffd11e7ff07cb, server version 1.25.0, error: Failed to handle completion domain request: {id: 2, method: completion.setSubscriptions, params: {subscriptions: [AVAILABLE_SUGGESTION_SETS]}, clientRequestTime: 1557497268151}
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<AvailableSuggestion>(Closure: (Declaration) => AvailableSuggestion)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      createCompletionAvailableSuggestionsNotification.<anonymous closure> (package:analysis_server/src/domains/completion/available_suggestions.dart:78:30)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      createCompletionAvailableSuggestionsNotification (package:analysis_server/src/domains/completion/available_suggestions.dart:82:8)
#5      CompletionDomainHandler.setSubscriptions.<anonymous closure> (package:analysis_server/src/domain_completion.dart:470:11)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#13     _rootRun (dart:async/zone.dart:1120:38)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:report.txt.

**Comment by srawlins** [comment] 2019-09-06 04:47
Thanks for filing this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/36623; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 04:47
Duplicate of https://github.com/dart-lang/sdk/issues/36623

**Closed by srawlins** 2019-09-06 04:47 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
