### ISSUE TITLE
Implicit generics fail on the call function of callable classes 

### ISSUE THREAD

**Issue by azilvl** [dart-lang/sdk#40006] opened 2020-01-07 18:05 UTC
```dart
class Foo {
  T call<T>() {
    T variable;
    return variable;
  }
}

void main(List<String> args) {
  var foo = Foo();
  int number = foo(); // invalid_assignment: A value of type 'dynamic' can't be assigned to a variable of type 'int'.
  int number2 = foo.call(); // is fine
  int number3 = foo<int>(); // is fine
}
```
This behaviour is not consistent with normal function calls.

You'd have to turn off implicit-casts to notice this.

**Comment by lrhn** [comment] 2020-01-08 10:33
This looks like a duplicate of https://github.com/dart-lang/sdk/issues/37122

**Closed by lrhn** 2020-01-08 10:33 UTC
Labels: area-library
