### ISSUE TITLE
Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by emadsoliman25** [dart-lang/sdk#41850] opened 2020-05-11 19:15 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.1, server version 1.27.4, FATAL error: NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:720:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:981:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

For additional log information, please append the contents of
file:///private/var/folders/dg/h27vn2012lqgztrr9vp10pcw0000gn/T/report.txt.

**Comment by srawlins** [comment] 2020-06-12 22:52
Thanks for reporting this issue! This was previously reported at #41658; please follow along there.

**Comment by srawlins** [comment] 2020-06-12 22:53
Duplicate of #41658

**Closed by srawlins** 2020-06-12 22:53 UTC
Labels: area-analyzer
