### ISSUE TITLE
Analyzer crash when ":" used in getter name

### ISSUE THREAD

**Issue by melvinsalas** [dart-lang/sdk#35634] opened 2019-01-11 15:35 UTC
# Enviroment
* Dart: 2.1.0 f9ebf21297
* SO: macOS Mojave
* IDE: VSCode 1.30.2 / Flutter extension 2.21.1
* Flutter version: 1.0.0
# Issue
### The Dart Analyzer has terminated
<img width="480" alt="screen shot 2019-01-11 at 9 29 11 am" src="https://user-images.githubusercontent.com/708747/51043072-64f22280-1583-11e9-9ff7-460b2ace4ec7.png">

```

[09:29:14 GMT-0600 (CST)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/melvinsalas/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/services/stdio_service.js:65:28)
	at Analyzer.sendMessage (/Users/melvinsalas/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/analyzer.js:110:19)
	at __dirname.sendRequest.Promise (/Users/melvinsalas/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/services/stdio_service.js:60:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/melvinsalas/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/services/stdio_service.js:49:16)
	at Analyzer.analysisSetSubscriptions (/Users/melvinsalas/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/analyzer_gen.js:427:21)
	at OpenFileTracker.updatePriorityFiles (/Users/melvinsalas/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/open_file_tracker.js:55:23)
	at __dirname.constructor.analyzer.disposables.push.vscode_1.window.onDidChangeActiveTextEditor (/Users/melvinsalas/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/open_file_tracker.js:22:87)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:634:804
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at e.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:541:823)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostP…

```

I found my error, it was this:
<img width="1050" alt="screen shot 2019-01-11 at 9 08 29 am" src="https://user-images.githubusercontent.com/708747/51043228-d29e4e80-1583-11e9-8a52-dcd61d31c423.png">
My error was write `isWhatever:ist` instead `isWhateverList`, but the IDE don't show a code error. It only stop the dart analyzer. Why?

**Comment by stereotype441** [comment] 2019-01-14 19:09
@DanTup Is it possible to find out whether the analyzer printed out an exception and a stacktrace when it terminated?  Without a stacktrace it will be hard to track down this bug.

**Comment by lrhn** [comment] 2019-01-16 08:39
Trying 
```dart
class C {
  String get foo:bar => 42;
}
main() {
  C().foo;
}
```
in a file by itself and running the analyzer on it gives:
```
Unhandled exception:                                                            
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1059:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2950:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:410:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1016:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8366:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:457:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:463:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:462:26)
#12     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:869:12)
#13     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:394:45)
#14     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```
That's not the analysis server, though. 

In DartPad, adding the colon means no more analyzer updates, but no visible crashes (although I did get some sporadic XmlHTTPRequest errors).

I see the same crash in VSCode on Linux. The "Show Log" button contains the same trace (or same error multiple stacktraces):
```
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] Captured exception
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1059:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2937:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:410:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1016:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1756:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8329:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:457:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:435:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:434:26)
#12     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#14     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218:20)
#15     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291:9)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1013:22)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2072:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2013:…
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] Captured exception
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1059:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2937:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:410:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1016:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1756:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8329:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:457:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
#9      FileState.refresh.<anonymous closure> (package:analyzer/src/dart/analysis/file_state.dart:435:46)
#10     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#11     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:434:26)
#12     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:222:32)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#14     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:218:20)
#15     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:291:9)
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1013:22)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2072:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2013:…
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] Captured exception
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:541:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:555:16)
#3      Future._completeError (dart:async/future_impl.dart:491:5)
#4      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#5      _Completer.completeError (dart:async/future_impl.dart:27:5)
#6      _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#22     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] Captured exception
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:541:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:555:16)
#3      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
#4      _rootRun (dart:async/zone.dart:1124:13)
#5      _CustomZone.run (dart:async/zone.dart:1021:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[09:34:56 GMT+0100 (CET)] [General] [Error] [Analyzer] Unhandled exception:
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:541:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[09:35:06 GMT+0100 (CET)] [General] [Error] This socket is closed
Error: This socket is closed
	at Socket._writeGeneric (net.js:726:18)
	at Socket._write (net.js:786:8)
	at doWrite (_stream_writable.js:387:12)
	at writeOrBuffer (_stream_writable.js:373:5)
	at Socket.Writable.write (_stream_writable.js:290:11)
	at Socket.write (net.js:704:40)
	at Analyzer.sendMessage (/usr/local/google/home/lrn/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/services/stdio_service.js:65:28)
	at Analyzer.sendMessage (/usr/local/google/home/lrn/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/analyzer.js:110:19)
	at __dirname.sendRequest.Promise (/usr/local/google/home/lrn/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/services/stdio_service.js:60:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/usr/local/google/home/lrn/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/services/stdio_service.js:49:16)
	at Analyzer.analysisSetPriorityFiles (/usr/local/google/home/lrn/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/analyzer_gen.js:409:21)
	at OpenFileTracker.updatePriorityFiles (/usr/local/google/home/lrn/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/open_file_tracker.js:51:23)
	at __dirname.constructor.analyzer.disposables.push.vscode_1.window.onDidChangeActiveTextEditor (/usr/local/google/home/lrn/.vscode/extensions/dart-code.dart-code-2.21.1/out/src/analysis/open_file_tracker.js:22:87)
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:634:804
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
	at e.$acceptDocumentsAndEditorsDelta (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:541:823)
	at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
	at t._invokeHandler (/usr/share/code/resources/app/out/vs/work…
```

**Comment by DanTup** [comment] 2019-01-29 09:54
@melvinsalas Thanks! Turns out this is easily reproducible and the stack in your log matches what was posted above.

```
NoSuchMethodError: The getter 'parameters' was called on null.
Receiver: null
Tried calling: parameters
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _SummarizeAstVisitor.visitConstructorDeclaration (package:analyzer/src/summary/summarize_ast.dart:1059:36)
#2      ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2932:15)
#3      _SummarizeAstVisitor.serializeClass (package:analyzer/src/summary/summarize_ast.dart:410:16)
#4      _SummarizeAstVisitor.visitClassDeclaration (package:analyzer/src/summary/summarize_ast.dart:1016:5)
#5      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1751:49)
#6      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#7      _SummarizeAstVisitor.serializeCompilationUnit (package:analyzer/src/summary/summarize_ast.dart:457:34)
#8      serializeAstUnlinked (package:analyzer/src/summary/summarize_ast.dart:22:8)
```

**Comment by stereotype441** [comment] 2019-01-29 17:00
Thanks for following up, @melvinsalas and @DanTup.  From the stack trace, this is a duplicate of #34610, which was present in 2.1.0 but has since been fixed.

**Comment by stereotype441** [comment] 2019-01-29 17:00
Duplicate of #34610

**Closed by stereotype441** 2019-01-29 17:00 UTC
Labels: analyzer-stability, area-analyzer, p2-medium, type-bug
