### ISSUE TITLE
[gardening] service/vm_timeline_events_test flaky

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#53644] opened 2023-09-28 13:20 UTC
The tests
```
service/vm_timeline_events_test/service RuntimeError (expected Pass)
```
are failing on configurations
```
vm-win-debug-arm64
```

Was already flaking before: https://dart-ci.web.app/#showLatestFailures=false&test=service/vm_timeline_events_test/service&configurations=vm-win-debug-arm64

Also flaking on other archs: https://dart-ci.web.app/#showLatestFailures=false&test=service/vm_timeline_events_test/service

```
--- Command "vm" (took 31.000355s):
set DART_CONFIGURATION=DebugARM64 & set DART_SUPPRESS_WER=1 & set DART_CRASHPAD_HANDLER=c:\opt\s\w\ir\cache\builder\sdk\out\DebugARM64\crashpad_handler.exe & out\DebugARM64\dart.exe --sound-null-safety -Dtest_runner.configuration=vm-win-debug-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\vm_timeline_events_test.dart

exit code:
255

stdout:
00:00 [32m+0[0m: vm_timeline_events_test.dart (VM Service)[0m

** Launching SERVICE_TEST_TESTEE=true out\DebugARM64\dart.exe --disable-dart-dev --write-service-info=file:///c:/opt/s/w/ir/x/t/dart_serviced1110e14/service_info.json --profiler --sound-null-safety -Dtest_runner.configuration=vm-win-debug-arm64 --ignore-unrecognized-flags --packages=C:\opt\s\w\ir\cache\builder\sdk\.dart_tool\package_config.json --enable-vm-service:0 C:\opt\s\w\ir\cache\builder\sdk\runtime\observatory\tests\service\vm_timeline_events_test.dart

>testee>out> The Dart VM service is listening on http://127.0.0.1:52671/YikbpPF1BUo=/

>testee>out> 

** Signaled to run test queries on http://127.0.0.1:52671/YikbpPF1BUo= (VM Service)

Loading VM...

Done loading VM

Running vm_timeline_events_test.dart [1/6]

Running vm_timeline_events_test.dart [2/6]

Running vm_timeline_events_test.dart [3/6]

>testee>err> ../../runtime/vm/profiler.cc: 1068: error: expected: fp_ != nullptr

>testee>err> 

>testee>err> ===== CRASH =====

>testee>err> ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF7BB81F7DC

>testee>err> Aborting reentrant request for stack trace.

00:19 [32m+0[0m[31m -1[0m: vm_timeline_events_test.dart (VM Service) [1m[31m[E][0m[0m

  Testee exited with 3

  runtime\observatory\tests\service\test_helper.dart 296:11  _ServiceTesteeLauncher.launch.<fn>.<fn>
  

Running vm_timeline_events_test.dart [4/6]

  NetworkRpcException(WebSocket closed)

  

** Killing script

00:20 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m



Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

stderr:
Unhandled exception:
Dummy exception to set exit code.

--- Re-run this test:
python3 tools/test.py -n vm-win-debug-arm64 service/vm_timeline_events_test/service
```

**Comment by dcharkes** [comment] 2023-09-28 13:21
cc @bkonyi

**Comment by brianquinlan** [comment] 2023-09-28 17:05
A lot of other tests are also broken. See attached logs.
[logs.txt](https://github.com/dart-lang/sdk/files/12752122/logs.txt)

**Comment by brianquinlan** [comment] 2023-09-28 17:14
I'm approving:
- service/vm_timeline_events_test/service
- service/valid_source_locations_test/service
- service/evaluate_activation_test/scope/dds
- service/valid_source_locations_test/dds

**Comment by rmacnak-google** [comment] 2023-10-06 03:43
Duplicate of #52969

**Closed by rmacnak-google** 2023-10-06 03:43 UTC
Labels: area-vm, gardening, vm-service
