### ISSUE TITLE
service tests need to be migrated to dart2 configuration

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#31587] opened 2017-12-08 16:18 UTC
When I try running service tests with `--strong` a lot of them are failing. I have updated the status files.

**Comment by jensjoha** [comment] 2018-01-12 12:31
Most of the remaining issues seems to be caused by https://github.com/dart-lang/sdk/issues/31876 - i.e. Something is just a `List` where it's expected to be a `List<something>`. For instance this fixes most remaining RuntimeErrors:

```
diff --git a/runtime/observatory/lib/src/service/object.dart b/runtime/observatory/lib/src/service/object.dart
index 1b9159bfd0..5cdbb0089d 100644
--- a/runtime/observatory/lib/src/service/object.dart
+++ b/runtime/observatory/lib/src/service/object.dart
@@ -3582,7 +3582,14 @@ class Script extends HeapObject implements M.Script {
     loadTime = new DateTime.fromMillisecondsSinceEpoch(loadTimeMillis);
     lineOffset = map['lineOffset'];
     columnOffset = map['columnOffset'];
-    _parseTokenPosTable(map['tokenPosTable']);
+    List tokenPosTable = map['tokenPosTable'];
+    _parseTokenPosTable(
+      new List<List<int>>.from(
+        tokenPosTable.map(
+          (sublist) => new List<int>.from(sublist),
+        ),
+      ),
+    );
     source = map['source'];
     _processSource(map['source']);
     library = map['library'];
```

leaving only the CompileTimeErrors and 
```
causal_async_star_stack_contents_test: RuntimeError
code_test: RuntimeError
debugger_location_second_test: RuntimeError
dev_fs_spawn_test: RuntimeError
```
(at least 2 of which  are seemingly caused by basically the same issue:

* causal_async_star_stack_contents_test: Unexpected exception in service tests: type 'List' is not a subtype of type 'List<Frame>' 
* code_test: Unexpected exception in service tests: type 'List' is not a subtype of type 'List<Map>' where
* debugger_location_second_test: type '_Future<ServiceObject>' is not a subtype of type 'Future<ServiceMap>' where
* dev_fs_spawn_test: Unexpected exception in service tests: ServerRpcException(_spawnUri: invalid 'args' parameter: [one, two, three])

)

**Comment by rmacnak-google** [comment] 2018-01-12 18:06
Nevermind, I've read my mail out of order.

**Comment by a-siva** [comment] 2018-02-21 23:12
@rmacnak-google landed a number of changes to make the tests strong mode clean, we have only one issue pending which is being tracked in https://github.com/dart-lang/sdk/issues/31696
Closing this issue.

**Closed by a-siva** 2018-02-21 23:12 UTC
Labels: I/O Beta 2.0, area-vm
