### ISSUE TITLE
Adding an argument packing/unpacking synthax

### ISSUE THREAD

**Issue by aelayeb** [dart-lang/sdk#29087] opened 2017-03-16 11:14 UTC
It would be nice to be able to pack/unpack arguments in Dart.

For **packing** example, being able to declare a function like this :
```
packArguments(*listOfArguments, **mapOfArguments) {
    listOfArguments.forEach((arg) => print(arg));
    mapOfArguments.forEach((key, val) => print("$key => $val"));
}
```
And then doing this :
`packArguments("I", "Put", "whatever", "I", "want, arg1: "A", arg2: 1);`
Would display :
```
I
Put
whatever
I
want
arg1 => A
arg2 => 1

```
As for **unpacking**, being able to do something like that :

```
functionWithLotOfArgument(a, b, c, d, e, {aa, bb = null, cc = null}) {
  // do stuff
}
var argList = [1, 2, 3, 4, 5];
var argMap = {"aa": "haha", bb: "baby"};

functionWithLotOfArgument(*argList, **argMap);
```

This feature would be especially useful in flutter when methods can have a lot of paramters sometimes.

**Comment by lrhn** [comment] 2017-03-16 21:23
This is effectively varargs/rest parameters (so a duplicate of #16253).

The most likely approach in Dart would be rest parameters for "packing" and perhaps a spread operator for "unpacking".

**Closed by lrhn** 2017-03-16 21:23 UTC
