### ISSUE TITLE
list tests failing in jsshell 50

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#28014] opened 2016-12-07 00:18 UTC
The following tests fail with jsshell 50:
```
python tools/test.py -mrelease -cdart2js -rjsshell -t60 --use-sdk corelib/list_test/none
python tools/test.py -mrelease -cdart2js -rjsshell -t60 --use-sdk corelib/list_test/01
```

**Comment by nex3** [comment] 2017-03-09 22:10
As of 7df5930aba7f, it looks like [corelib/list_test/none is partially passing](https://build.chromium.org/p/client.dart/builders/dart2js-linux-jsshell-1-4-be/builds/4903/steps/dart2js%20jsshell%20fast-startup%20tests/logs/stdio) on jsshell. I say "partially" because when I run the reproduction command

```
python tools/test.py -mrelease -cdart2js -rjsshell --fast-startup -t60 --use-sdk --dart2js-batch --reset-browser-configuration corelib/list_test/none
```

I get

```
Test configuration: dart2js_jsshell_release_x64

FAILED: dart2js-jsshell release_x64 corelib/list_test/none
Expected: Fail 
Actual: Pass
CommandOutput[dart2js]:
CommandOutput[jsshell]:

stdout:
computeCurrentScript@out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js:23:13
get currentScript@out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js:55:37
@/usr/local/google/home/nweiz/goog/dart/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/out.js:6233:9
dartProgram@/usr/local/google/home/nweiz/goog/dart/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/out.js:6228:4
@/usr/local/google/home/nweiz/goog/dart/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/out.js:23:11



Command[dart2js]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart2js --generate-code-with-compile-time-errors --test-mode --allow-mock-compilation --categories=all --packages=/usr/local/google/home/nweiz/goog/dart/sdk/.packages /usr/local/google/home/nweiz/goog/dart/sdk/out/ReleaseX64/generated_tests/corelib/list_test_none.dart --out=/usr/local/google/home/nweiz/goog/dart/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/out.js
Took 0:00:00.017483

Command[jsshell]: DART_CONFIGURATION=ReleaseX64 /usr/local/google/home/nweiz/goog/dart/sdk/tools/testing/bin/jsshell -f out/ReleaseX64/dart-sdk/lib/_internal/js_runtime/lib/preambles/jsshell.js -f /usr/local/google/home/nweiz/goog/dart/sdk/out/ReleaseX64/generated_compilations/dart2js-sdk/multitest_corelib_list_test_none/out.js
Took 0:00:00.342846

Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rjsshell -t60 --use-sdk corelib/list_test/none

[00:00 | 100% | +    1 | -    1]
```

Note the final line, which indicates that one test passed and one failed. I'm not sure why two different tests are running here, or why only one passed. This doesn't look like a flake, so it would be good to get it resolved soon.

Assigning to @rakudrama whose commit triggered this, and tagging @whesse for bot insight.

**Comment by nex3** [comment] 2017-03-09 22:17
Looks like this is also an issue on [Firefox proper](https://build.chromium.org/p/client.dart/builders/dart2js-linux-chromeff-1-4-be/builds/4107/steps/dart2js%20ff%20fast-startup%20tests/logs/stdio).

**Comment by whesse** [comment] 2017-07-03 09:35
This issue is still open, and is high priority. See also #27871.  @johnniwinther @sigmundch

**Comment by rakudrama** [comment] 2017-07-10 21:20
Fixed by rolling jsshell to C54.0.1

https://github.com/dart-lang/sdk/commit/1561247dfdaba051d7aa5c1510054d9376d124b3
https://github.com/dart-lang/sdk/commit/46d030d4ca3cf0fb622df4866368b3360adde7d3

**Closed by rakudrama** 2017-07-10 21:20 UTC
Labels: area-dart2js, browser-firefox, gardening, Type: bug
