### ISSUE TITLE
VM isolate may report being resumed prior to entering "paused on start"

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#25902] opened 2016-03-02 23:53 UTC
A VM isolate's "pauseEvent" field is temporarily set to "Resume" prior to going "PauseStart" as reported by the Observatory's "getIsolate" API call. This situation makes it ambiguous for some tools, such as `flutter drive`, to tell if they should wait for the isolate to enter "PauseStart" and then resume it, or whether the isolate is resumed for good and there's nothing to wait for.

**Comment by johnmccutchan** [comment] 2016-03-02 23:54
https://codereview.chromium.org/1756393002/

**Comment by alexander-doroshko** [comment] 2016-03-03 07:52
Dupe of #24550

**Closed** 2016-03-03 19:30 UTC
Labels: area-vm
