### ISSUE TITLE
Dartdevk. co19/LanguageFeatures/Named-arguments-anywhere/constructor_t02 test fails 

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#51079] opened 2023-01-20 09:33 UTC
[Error log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8791466050832969873/+/u/test_results/new_test_failures__logs_) is the following:
```
/===============================================================================================================================================\
| dartdevk-weak-linux-release-chrome:co19/LanguageFeatures/Named-arguments-anywhere/constructor_t02 broke (Pass -> RuntimeError, expected Pass) |
\===============================================================================================================================================/

--- Command "dartdevc" (took 98ms):
DART_CONFIGURATION=ReleaseX64 CHROME_PATH=/b/s/w/ir/third_party/browsers/chrome/chrome/google-chrome out/ReleaseX64/dart-sdk/bin/dart out/ReleaseX64/dart-sdk/bin/snapshots/dartdevc.dart.snapshot -Dtest_runner.configuration=dartdevk-weak-linux-release-chrome --no-sound-null-safety -Dtest_runner.configuration=dartdevk-weak-linux-release-chrome --ignore-unrecognized-flags --no-summarize -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartdevk-weak-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_constructor_t02/constructor_t02.js /b/s/w/ir/tests/co19/src/LanguageFeatures/Named-arguments-anywhere/constructor_t02.dart -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/async_helper.dill=async_helper -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/expect.dill=expect -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/js.dill=js -s /b/s/w/ir/out/ReleaseX64/gen/utils/dartdevc/pkg_kernel/meta.dill=meta

exit code:
0

--- Command "chrome" (took 01.000059s):
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart pkg/test_runner/bin/launch_browser.dart chrome http://127.0.0.1:43449/root_build/generated_tests/dartdevk-weak-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_constructor_t02/test.html?crossOriginPort=44759

Runtime error:
ReferenceError: t0 is not defined
    at Object.main (http://127.0.0.1:43449/root_dart/out/ReleaseX64/generated_compilations/dartdevk-weak-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_constructor_t02/constructor_t02.js:115:75)
    at testMainWrapper (http://127.0.0.1:43449/root_build/generated_tests/dartdevk-weak-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_constructor_t02/test.html?crossOriginPort=44759:86:112)

Deobfuscated error and stack:
ReferenceError: t0 is not defined
    at Object.main     ../../../../../tests/co19/src/LanguageFeatures/Named-arguments-anywhere/constructor_t02.dart 29:50
    at testMainWrapper out/ReleaseX64/generated_tests/dartdevk-weak-linux-release-chrome/tests_co19_src_LanguageFeatures_Named-arguments-anywhere_constructor_t02/test.html 86:112


exit code:
0

--- To debug locally, run:
/b/s/w/ir/tools/sdks/dart-sdk/bin/dart /b/s/w/ir/pkg/test_runner/bin/http_server.dart -p 43449 -c 44759 --network 127.0.0.1 --build-directory=/b/s/w/ir/out/ReleaseX64/ --runtime=chrome --packages=/b/s/w/ir/.dart_tool/package_config.json

--- Re-run this test:
python3 tools/test.py -n dartdevk-weak-linux-release-chrome co19/LanguageFeatures/Named-arguments-anywhere/constructor_t02
```
Test `co19/LanguageFeatures/Named-arguments-anywhere/constructor_t02` doesn't define `t0` variable. So, I guess, the compiler generates wrong JS

**Comment by athomas** [comment] 2023-01-23 13:00
DDC seems to be flaky on Named-arguments-anywhere in general:
https://dart-ci.firebaseapp.com/current_results/#/filter=co19/LanguageFeatures/Named-arguments-anywhere/,dartdevk&flaky

**Comment by athomas** [comment] 2023-01-23 13:01
This is causing frequent flakes on the CQ. /cc @nshahan

**Comment by nshahan** [comment] 2023-01-24 22:22
@athomas
My understanding is that when a test fails it gets deflaked by running it some number of times and checking if the results of each run are the same. Does that process recompile the test every time or use the same compiled output, just running it again?

**Comment by athomas** [comment] 2023-01-25 08:13
> @athomas My understanding is that when a test fails it gets deflaked by running it some number of times and checking if the results of each run are the same. Does that process recompile the test every time or use the same compiled output, just running it again?

It's meant to do everything again, but there could be a bug that prevents that from happening.

**Comment by nshahan** [comment] 2023-02-02 00:34
I still have not been able to reproduce any of these failures. According to the flakiness data it looks like the last failure was seen on Jan 25th and these tests will probably be marked as passing again soon. 

My only theory is that some combination of the new language feature tests with a partial implementation was crashing the compiler and causing failures in later tests when running on batch compiler. There could be some state in the compiler in a top level static that is leaking between runs causing incorrect compilations. I've seen this before but it was only triggered by a compiler crash. When running normally the values get cleared correctly.

**Comment by nshahan** [comment] 2023-09-11 23:48
Since the test has been consistently passing everywhere, I'm going to close the issue. We can open/reopen if needed.

**Closed by nshahan** 2023-09-11 23:48 UTC
Labels: web-dev-compiler, dev-compiler-errors, area-web
