### ISSUE TITLE
NNBD. No error if late, final variable with initializing expression initialized twice

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#40391] opened 2020-01-30 05:19 UTC
NNBD [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables) reads

> A non-local late variable declaration D implicitly induces a getter into the enclosing scope. It also induces an implicit setter iff one of the following conditions is satisfied:
> 
> D is non-final.
> D is late, final, and has no initializing expression.

In fact, if D is late, final and does have initializinf expression and initialized once again no error occurs

```dart
import "../../Utils/expect.dart";

class A {
  late final int x;
}
class B extends A {
  int x = 3;
}
class C extends A {
  late final int x = 3;
}

void main() {
  B b = new B();
  b.x = 3;
  b.x = 14;

  A a = new B();
  a.x = 42;
  a.x = 41;
  Expect.throws(() => new C().x = 3); // no error occurs
}
```
Tested on Dart VM version: 2.8.0-edge.cb2d91c9838b7e5adb18bf7b43da0b47da45a4d1 (Wed Jan 29 06:00:22 2020 +0000) on "linux_x64"

**Comment by eernstg** [comment] 2020-01-31 19:45
The declaration `A.x` gives rise to storage allocation in instances of `A` and it induces a getter and a setter. The setter will throw if called 2 times, and the getter will throw is the setter hasn't yet been called.

`B.x` allocates some more space and overrides both the getter and the setter, and causes instance creation to initialize that storage location to `3`. In this case both the getter and setter can be called any number of times. There is no super-invocation of any of them, so the getter/setter from `A` cannot be accessed with an instance of `B`.

`C.x` also allocates space, but here it is only the getter which is overridden. The getter needs to evaluate the initializing expression when called for the first time, but otherwise it's just a getter that we can call as often as we want.

So in `main` we invoke the setter from `B` twice with `b.x = ...`: No problem. And we also invoke the same setter twice with `a.x = ...`, because the dynamic type is `B` and there's nothing special about the override relationship.

Finally, `new C().x = 3` calls the setter induced by `A.x`, and that's no problem as long as we don't do it twice.

I think it would be easier to keep track of exactly how each kind of induced getter/setter behaves and should behave if we had declarations where there is no overriding at all (basically, no subclassing). And then the overriding and subclassing extras can be tested separately, to the extent that it brings out anything new (it should basically be the same as any other setter/getter override relationship, all the interesting things happen in the code generation for each setter/getter on its own).

**Comment by liamappelbe** [comment] 2020-01-31 20:42
Closing this as working as intended. The spec was updated to this behavior [here](https://github.com/dart-lang/language/pull/720/files), and I updated the VM to match [here](https://dart-review.googlesource.com/c/sdk/+/132408). You can find some more discussion about the decision [here](https://github.com/dart-lang/language/issues/705).

**Closed by liamappelbe** 2020-01-31 20:42 UTC
Labels: area-vm
