### ISSUE TITLE
checked mode not checking return type of async function

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#26584] opened 2016-05-31 22:15 UTC
``` dart
import 'dart:async';

var r = 'a';

Future<int> foo() async {
  return r;
}

main() {
  foo().then((_) {
    print("no error");
  });
}
```

This should error when compiled with dart2js in checked mode, but it prints "no error"

**Comment by floitschG** [comment] 2016-06-01 13:27
This is working as intended. The dynamic return-type of any `async` function is `Future<dynamic>`, which is assignable to `Future<int>`.

**Comment by hterkelsen** [comment] 2016-06-01 17:45
I still think this is a bug. Section 17.12 of the spec contains:
```
Let S be the runtime type of o [the returned object]. In checked mode:
• If the body of f is marked async (9) it is a dynamic type error if o is
not null (16.2) and Future<S> is not a subtype of the actual return type
(19.8.1) of f.
```

The "actual return type of f" is defined to be the declared return type of f as it appears in the program source code, in this case `Future<int>`. So I believe the spec is saying this should be a dynamic type error in checked mode.

**Comment by floitschG** [comment] 2016-06-01 17:52
Interesting. I didn't remember that this was part of the spec.

**Comment by rakudrama** [comment] 2018-04-20 23:39
I'm closing this since strong mode will check the types once https://github.com/dart-lang/sdk/issues/32830 is implemented.

**Closed by rakudrama** 2018-04-20 23:39 UTC
Labels: Type: bug, area-dart2js
