### ISSUE TITLE
pub package manager support create new application or library

### ISSUE THREAD

**Issue by netroby** [dart-lang/sdk#35364] opened 2018-12-10 01:21 UTC
The pub package manager should have the ability to create new application or library.
If you using maven, gradle, or even dotnet core cli, you may know their tools can create new application or library via cli command.

```
mvn -B archetype:generate \
  -DarchetypeGroupId=org.apache.maven.archetypes \
  -DgroupId=com.mycompany.app \
  -DartifactId=my-app
```

```
gradle init --type java-library

```

```
dotnet new console
```

**Comment by zoechi** [comment] 2018-12-10 08:38
Duplicate of dart-lang/pub#1847

**Comment by mraleph** [comment] 2018-12-10 08:50
@netroby you can use https://pub.dartlang.org/packages/stagehand for this.

**Closed by mraleph** 2018-12-10 08:50 UTC

**Comment by 89z** [comment] 2021-03-29 15:46
https://github.com/dart-lang/pub/issues/1847
https://github.com/dart-lang/pub/issues/2938

https://github.com/dart-lang/sdk/issues/35364
https://github.com/dart-lang/stagehand/issues/610
