### ISSUE TITLE
dart:math hyperbolic trigonometric functions

### ISSUE THREAD

**Issue by MattConflitti** [dart-lang/sdk#40664] opened 2020-02-15 13:11 UTC
It is very upsetting to see that the core math lib does not support these functions (cosh, sinh, tanh, etc). Is there a plan to add these soon?

https://github.com/dart-lang/sdk/issues/29623

**Comment by lrhn** [comment] 2020-02-18 09:34
This is a duplicate of #29623.

I agree that it's something we should add. 

It will need some back-end support (the JavaScript implementation is easy, the VM might need to do something to make it efficient), which is why it's not something we can just do without having VM resources to spend.

**Closed by lrhn** 2020-02-18 09:34 UTC
