### ISSUE TITLE
language/library/env_test/has_mirror_support is broken on dartkp-strong-linux-release-x64, precomp bots

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#48125] opened 2022-01-11 17:20 UTC
https://dart.googlesource.com/sdk/+/8510f27d37ee8ea58fb80183c181b833474a09e1 broke has_mirror_support test

[logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8825322273633741697/+/u/test_results/new_test_failures__logs_)
```
==========================================================================================================================\
| dartkp-strong-linux-release-x64:language/library/env_test/has_mirror_support broke (Pass -> RuntimeError, expected Pass) |
\==========================================================================================================================/

--- Command "vm_compile_to_kernel" (took 02.000661s):
DART_CONFIGURATION=ReleaseX64 /b/s/w/ir/pkg/vm/tool/gen_kernel --aot --platform=out/ReleaseX64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.dill /b/s/w/ir/out/ReleaseX64/generated_tests/language/library/env_test_has_mirror_support.dart --packages=/b/s/w/ir/.packages -Ddart.vm.product=false --sound-null-safety

exit code:
0

--- Command "precompiler" (took 04.000192s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/gen_snapshot --snapshot-kind=app-aot-assembly --assembly=/b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.S --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.dill

exit code:
0

--- Command "remove_kernel_file" (took 5ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.dill

exit code:
0

--- Command "assemble" (took 01.000319s):
DART_CONFIGURATION=ReleaseX64 gcc -m64 -shared -nostdlib -o /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.aotsnapshot /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.S

exit code:
0

--- Command "remove_assembly" (took 13ms):
DART_CONFIGURATION=ReleaseX64 rm /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.S

exit code:
0

--- Command "vm" (took 01.000072s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart_precompiled_runtime --sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseX64/generated_compilations/dartkp-strong-linux-release-x64/multitest_language_library_env_test_has_mirror_support/out.aotsnapshot

exit code:
255

stderr:
Unhandled exception:
Expect.equals(expected: <true>, actual: <false>) fails.
#0      Expect._fail (package:expect/expect.dart:742)
#1      Expect.equals (package:expect/expect.dart:132)
#2      main (file:///b/s/w/ir/out/ReleaseX64/generated_tests/language/library/env_test_has_mirror_support.dart:71)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

--- Re-run this test:
python3 tools/test.py -n dartkp-strong-linux-release-x64 language/library/env_test/has_mirror_support
```

cc @johnniwinther

**Comment by johnniwinther** [comment] 2022-01-11 17:41
This is as intended. `dart:mirrors` is not support on dartkp.

**Comment by aam** [comment] 2022-01-11 17:45
I guess we need to fix the test so it confirms new expectations.

**Comment by johnniwinther** [comment] 2022-01-11 22:22
The tricky part here is that `dart:mirrors` should only be supported in JIT. dart2js, ddc, and aot shouldn't.

**Comment by sigmundch** [comment] 2022-01-11 23:48
Note that this test is written to have different multitests depending on whether mirrors are supported or not: https://github.com/dart-lang/sdk/blob/master/tests/language/library/env_test.dart#L65

The test is not marked as skipped in configurations where it is not supported, but rather we use the accepted/approved status in our test infrastructure when runtime failures are expected.

It only works to detect regressions because we test both "has_mirrors_support" and "has_no_mirrors_support". The test infrastructure won't warn you if one case turns from runtime error to passing, but because the opposite configuration is tested too, the test infrastructure will catch that the other test switched as well and detect a regression.

You can see that for dart2js we've accepted the has_mirros_support failures (see https://dart-ci.firebaseapp.com/current_results/#/filter=language/library/env_test)

I assume that dartkp is AOT vs dartk is JIT, in that case, I think it's OK to accept the failures in AOT and keep the test as is.

**Comment by aam** [comment] 2022-01-12 04:49
The way how that test is a multi-test is indeed confusing.
Still, does the test have to be written such that failures have to be accepted?
Couldn't we codify dart2js, ddc, aot constraints for mirror library to be present into the test?
Something along the lines of https://dart-review.googlesource.com/c/sdk/+/227582 ?

**Comment by sigmundch** [comment] 2022-01-12 05:11
/cc @lrhn 

That's an interesting thought.

Unfortunately using dart:io/package:path feels brittle (we may one day not allow importing dart:io altogether from web targets). However, your idea using the `// ..Options=` lines could work if, for example, we also add to the test runner the ability of passing options specific to the AOT/JIT binaries (e.g.  `// VMAOTOptions = ` separate from `// VMJITOptions`).

Another thought, could we change the test runner to always provide the name of the configuration using an environment variable. Then that could be used within the test to express expectations by backend:

```dart
   // config will be a string like `dart2js-minified-d8-linux` or `dartkp-strong-linux-release-x64`
   final config = const String.fromEnvironment('test_runner.configuration');
   bool hasMirrorsSupport = !(['dart2js', 'dartdevc', 'dartkp'].any(config.contains));
```

In fact, the configuration details could be exposed in a test helper library, similar to `package:expect`.

**Comment by lrhn** [comment] 2022-01-12 09:30
It's always better to make the test succeed, rather than accept its failure, if at all possible. (Accepting a failure can more easily hide another bug).

Here, I'm not sure how we'd do that efficiently and correctly. The only real and decisive signal we have about whether `dart:mirrors` is supported, is the thing we are actually testing.

We don't provide the information that would allow us to predict whether mirrors are available (which would be is `isJitVM`).
We can approximate that, but only from other information that would need testing just as much, like `bool.fromEnvironment('dart.library.js')` implying it's on the web &mdash; but we need to test that just as much.

Allowing flags/options that only trigger in some compilation modes is one way to inject that kind of information. I worry that it's always going to be just too little information, and we'll be expanding the flags forever.

I think always setting the configuration as an environment variable would be better. Preferably with the helper library (maybe in the `expect` package itself[1]) which parses the string for you, so that you can say `isVMJit` in your test, or even `hasDartMirrors`, and if we add more configurations, we only need to update the one helper function, not every test which tries to parse the string itself.
That also allows us to change the format of the environment string completely, as long as we update the helper library along with it.

So, completely agree: Set a `-Dtest_runner.configuration=....` when compiling/running each test, and add a helper library/class to `package:expect` to read it.

[1]: I've become really annoyed that `async_helper` isn't part of `package:expect` lately. Let's not have at third (fourth?) test helper package.

**Comment by aam** [comment] 2022-01-12 18:29
> So, completely agree: Set a `-Dtest_runner.configuration=....` when compiling/running each test, and add a helper library/class to `package:expect` to read it.

We could do that. We could pass https://github.com/dart-lang/sdk/blob/main/pkg/smith/lib/configuration.dart name in env variable, have test use that package to reconstruct that Configuration from given name and use Configuration to determine what to test.

Another thought - to prevent Configuration leaking out, would it be simpler to split env_test.dart into mirrors_env_test, io_env_test, html_env_test etc and have those marked as skipped in appropriate status file configuration sections?

**Comment by sigmundch** [comment] 2022-01-13 21:00
Cool, thanks for pushing on this Alex!

DDC only precompiles files explicitly listed in
https://github.com/dart-lang/sdk/blob/bd04424cda9dba632c0db1c1a1096d1a122ea69a/utils/dartdevc/BUILD.gn#L222 for package:expect. Today that is `expect.dart` and `minitest.dart`. Another possible workaround for DDC with package:expect is to have it as an extra library in the package (say `pkg/expect/lib/config.dart`) that is purposely excluded and not precompiled with the rest of the package. As a result, DDC will compile it with the test code. Note that this requires that we don't exported it by default from `expect.dart` either.

**Comment by aam** [comment] 2022-01-13 22:28
Okay, thanks for the tip @sigmundch ! I updated the cl.

**Closed** 2022-01-14 23:34 UTC
Labels: area-vm, gardening, area-front-end
