### ISSUE TITLE
Documentation points to old website structure

### ISSUE THREAD

**Issue by smanilov** [dart-lang/sdk#27360] opened 2016-09-15 14:30 UTC
Some of the links in api.dartlang.org follow the structure of the website (www.dartlang.org) from before the latest revamp.

In particular, in "If you've never written a web app before, try our tutorials—A Game of Darts." the link for "A Game of Darts" is https://www.dartlang.org/docs/tutorials which has actually moved to https://www.dartlang.org/tutorials.

Also, the link for "Dart Editor" on the same page seems to point to https://www.dartlang.org/#get-started, while the "Get Started" button on the home page points to https://www.dartlang.org/guides/get-started.

Others might be out of date too.

**Comment by mit-mit** [comment] 2016-09-16 11:58
@smanilov do you have a link to the page that has these old links? All the links on https://api.dartlang.org/stable/1.19.1/index.html seem to work for me...

**Comment by kevmoo** [comment] 2018-03-26 20:36
Duplicate of https://github.com/dart-lang/sdk/issues/32304

**Closed by kevmoo** 2018-03-26 20:36 UTC
Labels: area-documentation
