### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by KhaledAlramam** [dart-lang/sdk#39065] opened 2019-10-23 12:45 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 8.1(amd64) v6.3 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, error: Failed to handle completion domain request: {id: 5579, method: completion.getSuggestionDetails, params: {file: C:\Users\Khaled\AndroidStudioProjects\shopping_app\lib\providers\products_provider.dart, id: 0, label: ChangeNotifier, offset: 32}, clientRequestTime: 1571867021082}
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DartFileEditBuilderImpl.importLibraryElement (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1298:34)
#2      CompletionDomainHandler.getSuggestionDetails.<anonymous closure> (package:analysis_server/src/domain_completion.dart:204:32)
#3      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:54:20)
#4      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.hand

**Comment by srawlins** [comment] 2019-11-05 05:22
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38476; please follow along there.

**Comment by srawlins** [comment] 2019-11-05 05:22
Duplicate of https://github.com/dart-lang/sdk/issues/38476

**Closed by srawlins** 2019-11-05 05:22 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
