### ISSUE TITLE
Request to delete packages flutter_exoplayer and exoplayer

### ISSUE THREAD

**Issue by danielR2001** [dart-lang/sdk#37722] opened 2019-08-02 17:38 UTC
hi, I'm new to flutter and it's my first package uploaded and by mistake I opened two packages flutter_exoplayer and exoplayer (with author name luan, not my name) that I want to be removed because I made some mistakes in the package name and the author name, I know that you recommend not doing that but I uploaded these packages just right now and don't think someone is depending on it.
please help me.

**Comment by mit-mit** [comment] 2019-08-05 12:30
Direct links; both published on Aug. 2nd, and with popularity 0
https://pub.dev/packages/flutter_exoplayer
https://pub.dev/packages/exoplayer

@danielR2001 I have sent an email to the email account listed on the uploaded packages. Please confirm the request there.

**Comment by jonasfj** [comment] 2019-08-05 13:05
Duplicate of https://github.com/dart-lang/pub-dev/issues/2620.

**Closed by jonasfj** 2019-08-05 13:05 UTC
Labels: pub-delete-request
