### ISSUE TITLE
Do not suggest constructors for non-instantiable classes

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#32549] opened 2018-03-15 18:12 UTC
Under preview-dart-2, we are now getting suggestions for the constructor `bool()`. See `ImportedReferenceContributorTest.test_MethodDeclaration_members` for a test case.

**Comment by pq** [comment] 2020-01-15 00:07
I think this is fixed.  (Or I can no longer reproduce 🤔...)

@bwilkerson: are you still seeing the issue?

**Comment by bwilkerson** [comment] 2020-01-15 00:21
I'm not seeing `bool()` any more, but I don't think the problem is fixed. Create a file containing:
```
class A {
  @deprecated X f;
  Z _a() {
   // complete here.
  }
  var _g;
}
class X {}
class Z {}
```
I see `double()` in the list, which is equally invalid.

**Comment by pq** [comment] 2020-01-15 00:23
Ok.  Thanks for confirming!

**Comment by DanTup** [comment] 2021-02-10 12:22
It looks like this might only occur when suggestion sets are enabled, otherwise it's filtered out (I think [here](https://github.com/dart-lang/sdk/blob/216b9d65d82b1058b4518d1f34668b370a9ae020/pkg/analysis_server/lib/src/services/completion/dart/local_library_contributor.dart#L142).

I'm not sure if the suggestion sets API currently supports being able to conditionally include a subset of constructors (eg. only the non-abstract ones when not in an initialiser) as it only sends over a list of `includedSuggestionSets` and `includedElementKinds`, but the `ElementKind` for the abstract classes constructors is the same as those for non-abstract classes?

**Comment by bwilkerson** [comment] 2021-02-10 16:08
I think you're right that the current support can't do that. I can think of two possible solutions.

1. We could extend the available suggestions support to allow the additional information to be passed over, whether by adding a new element kind or by some other means. This would require updating clients to use the additional information.

2. We could omit constructors from abstract classes when we initially send the data. I suppose it's possible that this would degrade completion in some places where we need those constructors to be available, but we could make up for that by creating the suggestions on each request (which is what I suspect that we're already doing). If this doesn't degrade the experience, then I think this is the better approach. It has the advantage that we're also sending a little less data with the available suggestions notifications.

Either way, we need to continue to suggest factory constructors on abstract classes as those are still valid to invoke.

**Comment by scheglov** [comment] 2024-03-08 03:40
I believe this is fixed now.
We replaced using available declarations with actual elements.
So, now we know exactly that the class is abstract, and which constructors are factory or generative.
`test_instanceCreationExpression_abstractClass` demonstrates that we skip generative constructors of abstract classes.

**Closed by scheglov** 2024-03-08 03:40 UTC
Labels: P1, area-analyzer, analyzer-completion, type-bug, analyzer-completion-correctness
