### ISSUE TITLE
Dart is not printing errors in console

### ISSUE THREAD

**Issue by josancamon19** [dart-lang/sdk#36103] opened 2019-03-04 20:58 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.1.0-dev.9.4`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: C:\Users\josancamon19\Downloads\My Medical Agenda\my_med_agenda\lib\ui\create\add_revision.dart context: exception_20190304_125524_658
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
#2      ConstantVisitor.visitPrefixedIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1395:12)
#3      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9033:49)
#4      ConstantVisitor.visitPropertyAccess (package:analyzer/src/dart/constant/evaluation.dart:1421:49)
#5      PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:9224:49)
#6      ConstantVerifier._validate (package:analyzer/src/dart/constant/constant_verifier.dart:449:10)
#7      ConstantVerifier._validateDefaultValues (package:analyzer/src/dart/constant/constant_verifier.dart:509:20)
#8      ConstantVerifier.visitMethodDeclaration (package:analyzer/src/dart/constant/constant_verifier.dart:236:5)
#9      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7706:49)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#11     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1781:13)
#12     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:688:10)
#13     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1751:49)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#15     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2423:21)
#16     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:712:10)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
#18     LibraryAnalyzer._computeConstantErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:172:10)
#19     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:325:5)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#21     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#22     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:15)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#24     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:36)
#25     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#26     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#27     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#29     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1029:23)
<asynchronous suspension>
#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#37     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#43     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#44     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#45     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#46     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#47     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\josancamon19\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2019-09-06 16:48
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/35241 and has been fixed. Upgrading Dart (or Flutter) should prevent the issue from re-occurring.

**Comment by srawlins** [comment] 2019-09-06 16:48
Duplicate of https://github.com/dart-lang/sdk/issues/35241

**Closed by srawlins** 2019-09-06 16:48 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
