### ISSUE TITLE
Dart debugging in Visual Code throws handled exceptions as uncaught

### ISSUE THREAD

**Issue by cosinus84** [dart-lang/sdk#37953] opened 2019-08-22 19:00 UTC
I think this a serious problem when working with dart/flutter.
https://github.com/flutter/flutter/issues/33427

**Comment by Kenji-K** [comment] 2020-05-26 23:58
I know it's in poor taste to add a "me too" comment, but this seriously needs attention. I found my issue with flutter, but apparently it's not an [isolated issue](https://stackoverflow.com/questions/57879455/flutter-catching-all-unhandled-exceptions).

**Comment by bwilkerson** [comment] 2020-06-24 20:35
@DanTup

**Comment by DanTup** [comment] 2020-06-24 20:47
Just to be sure - in the Debug side bar in VS Code, you only have "uncaught exceptions" ticked, and not "all exceptions"?

(cc @zichangg)

**Comment by Kenji-K** [comment] 2020-06-24 20:49
In my case, I have double checked that I have only uncaught exceptions ticked.

**Comment by DanTup** [comment] 2020-06-25 09:53
@Kenji-K thanks!

@zichangg I can repro this using a clean `flutter create` project and replacing `main.dart` with the following (and adding `google_sign_in:` to the pubspec dependencies):

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() {
  runApp(MyApp());
  _silentSignIn();
}

GoogleSignIn _googleSignIn = GoogleSignIn(scopes: <String>['email']);

Future<void> _silentSignIn() async {
  try {
    await _googleSignIn.signInSilently(suppressErrors: false).catchError(print);
  } catch (error) {
    print(error);
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Demo', home: Text('test'));
  }
}
```

It repros in both VS Code and Android Studio (though in Android Studio the editor goes to the source of the exception, whereas VS Code walks up the stack to the first frame that's user code). The source of the exception is here:

<img width="1192" alt="Screenshot 2020-06-25 at 10 49 09" src="https://user-images.githubusercontent.com/1078012/85697270-8b514280-b6d1-11ea-8b83-66e2cfc4eb4c.png">

As I understood it, the VM should see the `catch` block in the stack and know that it's handled. I don't know if it's related, but it looks like the exception is caught and rethrown in the frame above the user code:

<img width="1043" alt="Screenshot 2020-06-25 at 10 52 43" src="https://user-images.githubusercontent.com/1078012/85697791-04509a00-b6d2-11ea-974d-68b9f85e3ac6.png">

**Comment by DanTup** [comment] 2020-06-25 09:54
(I can't edit labels, but this might be `area-vm` rather than `area-analyzer`?)

**Comment by mehdiRezzagHebla** [comment] 2020-09-06 00:24
This problem still persists until now, I don't know if the Flutter team is aware of it, but it seems to me that it should be a priority issue.

**Comment by mehdiRezzagHebla** [comment] 2020-09-06 00:33
From what I could gather, the dartlang team said that it is "impossible" for them to fix this, I am not an experienced dev and I don't need to be in order to know that that is not true, since other modern languages don't have this problem.

**Comment by mraleph** [comment] 2020-11-30 09:37
I would agree that this is indeed an unpleasant usability issue for the debugger. I don't see any reason though why we would not be able to make this work in common situations given that we should be able to peek through future chains.

In the code below:
 
```dart
import 'dart:async';

Future<void> baz() async {
  await null;
  throw 'A';
}

Future<int> bar() => baz().then((value) => 10);

Future<int> foo() async {
  try {
    await bar();
  } catch (e) {}
  return 0;
}

void main(List<String> arguments) async {
  await foo();
}
```

Debugger stops at `throw` as if it is uncaught. 

We also get a really weird truncated lazy async stack trace with no position information in the last frame (/cc @mkustermann @cskau-g): 

```dart
$ out/ReleaseX64/dart /tmp/uncaught.dart
#0      baz (file:///tmp/uncaught.dart:5:3)
<asynchronous suspension>
#1      bar.<anonymous closure> (file:///tmp/uncaught.dart)
<asynchronous suspension>
```

**Comment by mkustermann** [comment] 2020-11-30 09:47
Reason for truncation is probably usage of legacy `baz().then((value) => 10` instead of `value = await baz(); return 10`. @cskau-g has recently added support for `whenComplete()` we could possibly extend that to `then()` as well.

Though generally speaking I think we should encourage users to use `await` and `try/await/catch/finally` instead of the pre-async/await `then()/catchError()/whenComplete()`.

Also for certain cases it's not possible to select the right way to unwind, because a future can have multiple listeners, which would yield a back trace tree instead of a stack. We could possibly print an the tree, but that would bring in a whole lot of new issues (e.g. figure out nice way to print such a backtrace tree, making `package:stack_trace` understand it, ...)

**Comment by mraleph** [comment] 2020-11-30 10:16
@mkustermann If I replace `then` with `timeout` I get correct lazy async stack, but debugger still thinks exception is uncaught. I looked briefly at the code and it seems to attempt to make things work by looking for handler in the "awaiter stack trace" however this code is written in terms of causal stacks and has not been updated to use lazy async stacks at all.

There is a consideration here that there is a lot of legacy code (written without async/await) and code written in mixed style - sometimes hidden inside SDK libraries and packages which user did not author. I think we should definitely make things work for `Future` helper methods whenever we can (e.g. it is a bit puzzling that it would work for `timeout` but not `catchError` (BTW, replacing `then` with `catchError` produces somewhat garbled stack as well).

**Comment by DanTup** [comment] 2020-11-30 10:29
Slightly related - this comes up quite a bit in the Dart-Code issue tracker, and I've generally been encouraging people to use `try`/`catch` where possible to avoid it (although often they're calling libraries that they can't easily modify), though some examples came up where this isn't possible, for example:

```dart
return FutureBuilder<Widget>(
  future: f,
  builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
    if (snapshot.hasData) {
      return SuccessfulWidget();
    } else if (snapshot.hasError) {
      return ErrorMessageWidget(snapshot.error);
    }

    return LoadingSpinnerWidget();
  }
);
```

Here, the code that's handling the error is in `FutureBuilder` so it can't easily be converted to use `try`/`catch`. If I understand the suggestion above of "peeking through future chains", I think that would also handle this (as it's likely the error handler has been attached before the code in the Future throws)?

**Comment by cskau-g** [comment] 2020-12-03 14:03
There a bit of back-and-forth here, but we have no assignee and no clear action items, AFAICT.
@mraleph and/or @mkustermann, can you clarify what we'd like to do on this issue, and whether it's something I need to look into?

**Comment by mkustermann** [comment] 2020-12-03 15:10
Regarding the truncated stack: We can investigate adding support for the legacy `Future.then()` and `Future.catchError()` APIs as part of the existing open issue here: https://github.com/dart-lang/sdk/issues/40815

**Comment by mkustermann** [comment] 2020-12-03 15:19
@cskau-g Could you investigate the uncaught error reporting functionality - both when it is actually caught (as this issue) as well as reporting exceptions as uncaught if the handler was specially marked (see https://github.com/flutter/flutter/issues/17007)

**Comment by franklinyow** [comment] 2021-01-12 01:24
@cskau-g @mkustermann Any update?

**Comment by mraleph** [comment] 2021-01-12 06:28
@cskau-g has landed changes on our side. The ball is now in Flutter court.

**Comment by DanTup** [comment] 2021-01-12 10:04
@mraleph are the changes different to the ones in #17007? Although this sounds like the same issue, I believe it's actually the opposite problem.

#17007 is about exceptions that Flutter is catching, but are logically uncaught (eg. expected behaviour is for the debugger to break).

This issue is about exceptions that are being caught (eg. with `.catchError()`) but the debugger considers uncaught (because there's no `catch` in the stack?) and therefore result in the debugger breaking (making the user believe there is an unhandled error they need to do something about), but clicking Continue results in the app continuing to work as expected.

**Comment by mraleph** [comment] 2021-01-12 10:12
My mistake, yeah it is a separate issue. I got confused.

**Comment by franklinyow** [comment] 2021-01-12 16:53
@mraleph I am assigning P2 for this.  Please change if you think it has a different priority.

**Comment by cskau-g** [comment] 2021-01-13 08:29
Update on the various issues that have been discussed above:

- `Future.then()` and `Future.catchError()` support has been added in 8f2c47f (see #40815).
- VM annotation (`@pragma('vm:notify-debugger-on-exception')`) has been added to pause the debugger on otherwise caught exceptions (see #17007).
- With support for `Future.then()` and `Future.catchError()`, the debugger pausing mechanism now correctly identifies the cases for which this issue was originally created. This means 8f2c47f indirectly fixes this issue.

**Comment by DanTup** [comment] 2021-01-14 15:08
@cskau-g should these changes consider the following as caught?

```dart
Future<void> main() async {
  await throwAsync().catchError((e) => print('Caught the error!'));
}

Future<void> throwAsync() async {
  await Future.delayed(const Duration(milliseconds: 100));
  throw 'a';
}
```

I tested this with the latest nightly built from 990b03290f0b889c33668d91c8043abb55555476 but the debugger still pauses on the `throw`.

**Comment by cskau-g** [comment] 2021-01-18 12:22
@DanTup The fix unfortunately got reverted since it happened to trigger an unrelated issue in internal tests.
I've just landed a fix for the second issue and relanded the original fix, so we should be back to it all working again.
I'll close this issue now, but if you continue experiencing issues even after this fix has re-rolled, please do reopen.

**Comment by DanTup** [comment] 2021-01-19 17:32
@cskau-g using the latest nightly I'm still seeing the debugger break on the exception in the code sample above.

The SDK version is:

Dart SDK version: 2.12.0-edge.073f792b599b00a088f640e5dfa658ab3f5c90e4 (be) (Tue Jan 19 16:47:32 2021 +0000) on "macos_x64"

from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/

**Comment by cskau-g** [comment] 2021-01-22 11:43
I've verified that there is indeed an issue with debug breaking on `.catchError`, which is unrelated to the CL for stack unwinding.
Looks like we'll need some additional logic in `Debugger::ShouldPauseOnException` to handle when the catchError isn't part of the stack but rather the future being awaited.

**Comment by franklinyow** [comment] 2021-01-25 18:26
@cskau-g What is the status on this?  
If we can land this in tomorrow (your time), it is likely to make the January milestone.
Otherwise, please comment if this need to be cherrypick for January or we should move to a later milestone.

**Comment by cskau-g** [comment] 2021-01-26 06:47
@franklinyow The plan was to land this yesterday, but the change is unfortunately still in review.
I'll try get it pushed through today.

**Comment by cskau-g** [comment] 2021-01-26 08:06
mraleph and I agreed to push this off this milestone to avoid rushing the change in, seeing how it's already gotten reverted twice.

The follow-up fix for the `.catchError` will likewise not be in this milestone.

**Comment by cskau-g** [comment] 2021-02-02 07:06
With dfd5413 the last piece of the puzzle should now be in place.

Closing this issue here. But as always, feel free to reopen if you encounter any further issues with the above cases.

Thank you.

**Comment by DanTup** [comment] 2021-02-11 12:51
@cskau-g seems to work great, thank you!

**Comment by edvinasgestautas** [comment] 2021-02-15 19:52
hey sorry for a newbie question but do you have any idea when will flutter be built with this fix ? or how can I check it ?

**Comment by kevinmarrec** [comment] 2021-02-24 20:55
@DanTup I tried with `dev` channel of Flutter but it seems the issue is still here.

Maybe last flutter `dev` build doesn't use last dart sdk `dev` which includes the fix ?

**Comment by mraleph** [comment] 2021-02-25 10:07
@kevinmarrec `dev` contains dfd5413. Could you describe the issue you are seeing in more details? We added support for `.then` and `.catchError` for futures, but it might be that we are still missing support for some other pattern (we are playing a bit of whack-a-mole here).

**Comment by kevinmarrec** [comment] 2021-02-25 10:32
When debugging this code on VS Code (F5) with only `Uncaught Exceptions` checked :
```dart
import 'package:http/http.dart' as http;

Future<void> main() async {
  try {
    await http.get(Uri.parse('www.fail.com'));
  } catch (err) {
    debugPrint('Error caught');
  }
}
```

VS Code still breaks (breakpoint) in third party (`http` here) cause it thinks the error hasn't been caught, but I do (`catch`) :

![image](https://user-images.githubusercontent.com/25272043/109140461-e81f6400-775c-11eb-866a-f273d307a6de.png)

Using `catchError` doesn't work as well :

```dart
import 'package:http/http.dart' as http;

Future<void> main() async {
  http.get(Uri.parse('www.fail.com')).catchError((error) {
    debugPrint('Error caught');
  });
}
```

**Comment by mraleph** [comment] 2021-02-25 10:47
Yeah, I can see it does not work. It seems if you have more than one `Future` in the chain things break. 

```
import 'package:http/http.dart' as http;

Future<void> throwAsync() async {
  await Future.delayed(const Duration(milliseconds: 100));
  throw 'Throw from throwAsync!';
}

Future<void> foo() async {
  await Future.delayed(const Duration(milliseconds: 100));
  await throwAsync();
}

Future<void> main() async {
  try {
    await throwAsync();  // Ok.
  } catch (err) {
    print('Error caught');
  }
  try {
    await foo();  // Not okay.
  } catch (err) {
    print('Error caught');
  }
}
```

**Comment by kevinmarrec** [comment] 2021-02-25 11:10
@mraleph Good catch ! 

I can indeed confirm it breaks when there's more than one `Future` in the chain.

It will be my pleasure to try again when there's a fix coming up :)

And it would be awesome if it got fixed before next Dart release lands :)

**Comment by cskau-g** [comment] 2021-02-25 11:12
I'll have a look.

**Closed** 2021-02-26 06:47 UTC
Labels: P2, area-vm, type-bug

**Comment by namchuai** [comment] 2021-03-07 14:49
Sorry for asking an obvious question here. When can we get this fix included in dart sdk for fluttter?
AFAIK, we cannot specify a dart sdk version with flutter sdk (https://stackoverflow.com/a/51514523/4700001).

**Comment by kevinmarrec** [comment] 2021-03-07 16:26
@namchuai I think we need to wait **Dart 2.13** release and then most probably **Flutter 2.1** will feature **Dart 2.13**

**Comment by mraleph** [comment] 2021-03-08 09:07
@namchuai to expand on @kevinmarrec response. Dart's master branch is automatically continuously being rolled into Flutter's master branch. So if you are using master channel then you should already have a fix included (unfortunately at the moment that is the only channel of Flutter that includes the fix). All other branches are entirely aligned as well (e.g. beta channel of Flutter uses beta channel of Dart and the same for stable channel). Except for very serious bugs (e.g. crashes) there is no way to expedite this process - it happens at a fixed cadence.

**Comment by ramsestom** [comment] 2021-06-01 19:01
Still getting this issue
I have some code like this:

```dart
try {
      await calculator.connectToServer().timeout(Duration(milliseconds: 15000));
} on TimeoutException catch (_) {
     print("Timeout of 15000 ms exceeded trying to connect to server");
     return ServerOffScreen(_login);
}
```

and everytime a TimeoutException is thrown, VSCode is blocking on the TimeoutException

I use
Flutter 2.2.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b22742018b (3 weeks ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

**Comment by a7md0** [comment] 2021-11-12 18:44
Still having this issue with 3rd party package (flutterchina/dio)

```
$ flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (4 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by mraleph** [comment] 2021-11-13 09:19
@a7md0 please file a new issue and provide a reproduction. just saying "Still having this issue" is unactionable for us.

**Comment by a7md0** [comment] 2021-11-13 10:43
> @a7md0 please file a new issue and provide a reproduction. just saying "Still having this issue" is unactionable for us, because we have fixed all cases we could reproduce - so your issue is likely something else.

#47692
