### ISSUE TITLE
`Extension 'cannot act on auto derived type' var '

### ISSUE THREAD

**Issue by rhymelph** [dart-lang/sdk#44599] opened 2021-01-06 15:51 UTC
dart sdk version: Dart SDK version: 2.12.0-29.10.beta (beta) (Tue Nov 17 10:50:22 2020 +0100) on "macos_x64"

Is is my code
```dart
void main(){
    var a;
    a = "Test";
    print(a.sayHello());
}

extension HelloString on String {
  String sayHello() {
    return 'Hello World';
  }
}
```
output
```
NoSuchMethodError: Class 'String' has no instance method 'sayHello'.
```

**Comment by a-siva** [comment] 2021-01-07 18:17
I believe it is working as intended, the type inferencing for local variables works by intefering types from the initializer, if any. Subsequent assignments are not taken into account, see https://dart.dev/guides/language/type-system#local-variable-inference.

Your code written as

```
void main(){
    var a = "Test";
    print(a.sayHello());
}

extension HelloString on String {
  String sayHello() {
    return 'Hello World';
  }
}
```

should work.

**Comment by eernstg** [comment] 2021-01-07 21:22
Type promotion has been enhanced substantially in Dart with null safety (a new feature bundle which is enabled in Dart 2.12), and that's the mechanism that _could_ have given `a` a different type than `dynamic` (which is what it gets by default when there is no information at all in the declaration, as in `var a;`).

So you can move the initialization into the declaration, as @a-siva mentioned. But with null safety you can also get a promotion (in this case: from `dynamic` to `String`) if the target type `String` is 'a type of interest' for the given variable. One way to achieve that a type is 'of interest' for a variable is to test for it:

```dart
// Requires that null safety is enabled.

void main() {
  var a;
  if (a is! String) { // `String` now of interest for `a`.
    a = "Test"; // This will promote `a` to have type `String`.
  }
  // At this point it is known that `a` was already a `String`, 
  // or a `String` was assigned to it, so it is a `String`.
  print(a.sayHello()); // .. and then we can invoke an extension method `on String`.
}

extension HelloString on String {
  String sayHello() {
    return 'Hello World';
  }
}
```

The situation is tricky, because the type of `a` is `dynamic` if no promotion has occurred, and then `a.sayHello()` will be accepted at compile-time, because we can invoke _any_ method on a `dynamic` receiver. But it will still fail at run time (a receiver of type `dynamic` never gets an invocation of an extension method).

So it's a good habit to use an initializer in the declaration when possible. You may still want, and get, type promotions for a variable like `var a = "Test";`, but when the type at the declaration is `String` (or any other type `T` different from `dynamic`), you know that it will _always_ have a type which is a subtype of `String` (resp. `T`), and then it will never give rise to a dynamic method invocation, that is, all method invocations on that variable are type checked statically.

@rhymelph - I'll close the issue, because the example is working as intended.

**Closed by eernstg** 2021-01-07 21:22 UTC
