### ISSUE TITLE
ffi/vmspecific_function_callbacks_test crashing on reload bots

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#39763] opened 2019-12-12 17:34 UTC
ffi/vmspecific_function_callbacks_test is crashing on the reload bots as of https://dart-review.googlesource.com/c/sdk/+/124328

Log:
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8894260373216247056/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0

**Comment by dcharkes** [comment] 2019-12-13 10:11
```c++
bool IsolateGroup::ReloadSources(JSONStream* js,
                                 bool force_reload,
                                 const char* root_script_url,
                                 const char* packages_url,
                                 bool dont_delete_reload_context) {
  ASSERT(!IsReloading());

  // TODO(dartbug.com/36097): Support multiple isolates within an isolate group.
  RELEASE_ASSERT(!FLAG_enable_isolate_groups);
```

This is a duplicate of #36097, cc @mkustermann.

**Closed by dcharkes** 2019-12-13 10:11 UTC
Labels: area-vm
