### ISSUE TITLE
Feature idea: enum paramters shouldn't require enum name prefix.

### ISSUE THREAD

**Issue by yahel-ck** [dart-lang/sdk#39790] opened 2019-12-13 19:19 UTC
* Dart SDK Version 2.7.0

### Rationale
Since the expected type of function parameters is already clearly defined and known (especially with named parameters), having to specify it when passing an enum identifier (`EnumType.identifier`) is quite redunant. This feature can further optimize Dart for UI by making passing widget attributes shorter and more readable.

### Examle

Instead of:

```
Column(
  mainAxisAlignment: MainAxisAlignment.center,
  ...
)
```

You'd write:

```
Column(
  mainAxisAlignment: center,
  ...
)
```

**_To emphasize:_** all of the enum's instances will be available in the 'scope' of that one parameter, as if the current piece of code is contained inside the actual defenition of the enum class. This design also resolves possible name shadowing issues created by this feature; i.e. if a variable with the same name as one of the enum identifiers exists in the current scope, you could only access that identifier by refrencing the enum's name the normal way.

**Comment by simolus3** [comment] 2019-12-13 22:07
I think this is a duplicate of https://github.com/dart-lang/language/issues/357

**Closed** 2019-12-14 07:19 UTC
