### ISSUE TITLE
Transpiler JS -> Dart 

### ISSUE THREAD

**Issue by truepatch** [dart-lang/sdk#32405] opened 2018-03-03 13:20 UTC
Good day.

Many people would like to use the JS translation tool in Dart.
Basically for frameworks the standard ЕS5, ЕS6 is used. This tool will convert the code of the fresh libraries to Dart. Doubtful parts of the code that do not make it possible to uniquely identify a strict type, mark as "ToDo:" or "Warnings:", for manual editing. This will automatically convert 90-95% of the written code.
Fresh library will be published in the repository pub. The version with the original version will also be preserved. For example: vue v2.5.13 = vue2: "2.5.13"

This will definitely help to increase the audience of Dart! Since most developers have problems with the usual libraries in everyday life.

**Comment by mraleph** [comment] 2018-03-03 13:56
Duplicate of #1405

**Closed by mraleph** 2018-03-03 13:56 UTC

**Comment by mraleph** [comment] 2018-03-03 14:03
General practice shows that in browser you can successfully use JavaScript libraries and Dart together via JS interop, see examples like [over_react](https://github.com/Workiva/over_react). Translation is not the right solution because it essentially forks the library. 

Also while it is certainly possible to run JavaScript on top of Dart, a high-level translation from arbitrary JavaScript to Dart is a very hard task due to semantic chasm that separates these languages. Producing a readable and maintainable close to idiomatic Dart from an arbitrary JavaScript library is non-trivial.

I however don't want to discourage anybody from trying it out! As #1402 states: it would be a very interesting community project.
