### ISSUE TITLE
[Analyzer]Add Support for Auto Import + Smart Completion for extension methods.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dart-lang/sdk#40731] opened 2020-02-21 18:51 UTC
Since I'm used to all my methods getting Smart Completed and auto imported if they are in the same project, however we don't get this option with extension methods.

**Comment by bwilkerson** [comment] 2020-02-21 19:06
Thanks for the report. We've recently become aware of the issue and are working to support that case.

@pq

**Comment by srawlins** [comment] 2020-03-03 16:59
Looks like a duplicate of #38894

**Comment by ThinkDigitalSoftware** [comment] 2020-03-03 17:24
@srawlins ah, yes it is

**Closed** 2020-03-03 17:24 UTC
Labels: analyzer-completion, area-analyzer
