### ISSUE TITLE
Flaky: async/timer_regress22626_test appears flaky by design

### ISSUE THREAD

**Issue by kasperl** [dart-lang/sdk#28254] opened 2017-01-04 08:12 UTC
The test case looks flaky and it is (very rarely) causing issues on the build bots. Contrary to the original status file update by @whesse this doesn't appear to happen only on MIPS.

**Comment by kasperl** [comment] 2017-01-04 08:13
Added area-vm because the regression test case was added as part of fixing a VM issue.

**Comment by mraleph** [comment] 2017-11-16 11:57
This issue has been open for 315 days. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by mraleph** [comment] 2018-04-24 19:39
Should we delete the test and close this issue?

**Comment by whesse** [comment] 2018-12-04 20:36
Looking at the original issue, that this is a regression test for (https://github.com/dart-lang/sdk/issues/22626), the issue was diagnosed and fixed, and this regression seems so specific that we don't lose much coverage by dropping this test.  On the other hand, if the timeout of 200ms in "test(200, 2)" is increased to 2s or more, it should be a passing, never flaky test and could be run everywhere.  So a CL dropping it seems ok to me.

**Closed** 2018-12-07 12:20 UTC
Labels: area-vm, gardening
