### ISSUE TITLE
SourceFileProvider performance issue

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#20699] opened 2014-08-26 13:24 UTC
I've found that each message reported by SourceFileProvider results in UTF8 decoding, which is rather slow.

Caching the decoded String is problematic as it leads to excessive memory overhead.

Not sure how to fix this best.

**Comment by joshualitt** [comment] 2021-11-15 19:32
I'm going to close this one because I suspect it is too difficult to find a fix that won't be a regression in some cases.

**Closed by joshualitt** 2021-11-15 19:32 UTC
Labels: web-dart2js, type-bug, area-web
