### ISSUE TITLE
can't use Dart 

### ISSUE THREAD

**Issue by joezhangss** [dart-lang/sdk#35145] opened 2018-11-13 01:42 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6 unknown, screens 1920x1080`

# Exception

Please append the contents of:
file:///private/var/folders/47/t4sjvjj56cl6bnm0svsnf9y40000gp/T/report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68, server version 1.20.5, error: Analysis failed: /Users/dengxiao/ReactC/HelloWorld/TestCaseFolder/ujksaas_master/lib/src/registerComponent_util.dart
Element mismatch in /Users/dengxiao/ReactC/HelloWorld/TestCaseFolder/ujksaas_master/lib/src/registerComponent_util.dart at registerComponent_util(Key key, String name, String value_placeholder, TextStyle textStyle, String separateIcon) → registerComponent_util
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:576:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:107:9)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-11-15 18:46
Duplicate of #33930

**Closed by stereotype441** 2018-11-15 18:46 UTC
Labels: area-analyzer
