### ISSUE TITLE
Adding generics to a method change its signature and equality behavior

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#46761] opened 2021-07-29 20:08 UTC
Talking to @jakemac53 on Gitter we found out that a generic method is not the same for the simpler version of it:  

```dart
void main() {
  print(y is int Function());
}
T y<T extends int>() => 1 as T;
```

The above prints ```false```.  
Is this expected?  
I thought that adding generics to a function would only constrain the types and be added to the metadata of the function when reified.  

My use case is:  

```dart

class Model {}
class Content extends Model {}
class Event extends Content {}

abstract class Domain<T extends Model> {
  T bar();
}
class DomainContent extends Domain<Content> {
  // 'DomainContent.bar' ('S Function<S extends Content>()') isn't a
  // valid override of 'Domain.bar' ('Content Function()')
  S bar<S extends Content>() {
    return Event() as S; 
  }
}
```

**Comment by a-siva** [comment] 2021-07-29 21:54
//cc @leaf @lrhn

**Comment by gmpassos** [comment] 2021-07-30 00:40
Note that 'int', 'double', 'num', 'bool' and 'String' are special types and can't be extended. Maybe you need an example using normal classes.

**Comment by jodinathan** [comment] 2021-07-30 01:07
> Note that 'int', 'double', 'num', 'bool' and 'String' are special types and can't be extended. Maybe you need an example using normal classes.

```dart
class Model {}

T foo<T extends Model>() => Model() as T;

void main() {
  print(foo is Model Function()); // false
}
```

**Comment by lrhn** [comment] 2021-07-30 08:25
> Is this expected?

Yes. 
The type of `y`, declared as `T y<T extends int>() => 1 as T;` is `T Function<T extends int>()`. That type is different from `int Function()`.
When you call `y`, you *must* supply a type argument, something you *cannot* do for `int Function()`, so the two types are incompatible at the language level.

In practice people tend to forget this because the language often infers the required type argument for you, so you don't have to write it, which is why you can write `y(1)`, but it really means `y<int>(1)`, the `<int>` is just inferred for you.
Also, you can instantiate the type argument when tearing off the function, so `int Function() f = y;` works by implicitly making it `int Function() f = y<int>;` (something you can't yet write explicitly, but we're working on that). That `f` is a different function than `y`, more like a conversion to `(int x) => y<int>(x);`.

This still only works where implicit type arguments are added by the language. Code like:
```dart
dynamic f = y;
int Function() g = f;
g(2);
```
will fail at the `g = f` assignment because `f` has type `T Function<T extends int>()`, and we don't do any inference at that point.
If it hadn't failed, the `g(2)` invocation would then try to call the generic function without a type argument, which is something we cannot allow to happen.


For your use-case, you can't do it that way. A generic methods cannot override a non-generic one.
Instead you could perhaps write it as:
```dart
abstract class Domain<T extends Model> {
  T bar();
}
class DomainContent extends Domain<Content> {
  Event bar() {
    return Event(); 
  }
}
```
The cast of `Event` to `S` looks very dangerous. If there are any other subtypes of `Content` than `Event`, then the cast would fail if `S` was set to one of those. Unless there are some important details missing, I don't see the advantage in having the `<S>` type parameter at all.

**Comment by jodinathan** [comment] 2021-07-30 13:14
> The cast of Event to S looks very dangerous. If there are any other subtypes of Content than Event, then the cast would fail if S was set to one of those. Unless there are some important details missing, I don't see the advantage in having the <S> type parameter at all.

The ```bar``` method is a factory of a sealed class. In the example, ```bar``` could return few options and all are direct descendant of ```Content```.  
```bar``` can work if it returns ```Content```:  

```dart
abstract class Domain<T extends Model> {
  T bar();
}
class DomainContent extends Domain<Content> {
  Content bar() {
    return Event(); 
  }
}
```

and the consumer:  

```dart
class Foo {
  Event event;
  final d = DomainContent();
}

final foo = Foo();

foo.event = d.bar() as Event;
```

The idea is to remove the consumers from using ```as Event``` by letting the type be inferred through the generic method.

**Comment by jakemac53** [comment] 2021-08-02 16:42
> When you call `y`, you _must_ supply a type argument, something you _cannot_ do for `int Function()`, so the two types are incompatible at the language level.

I am curious why we can't just treat type arguments as having default values equal to the lower bound constraint for the type parameter? Would that be worse from a performance perspective than normal default values for optional arguments in some way?

**Comment by vsmenon** [comment] 2021-08-05 12:52
Shall we close this as working as intended?  Or move to the language tracker as a change to consider?

**Comment by vsmenon** [comment] 2021-08-09 14:09
Closing as working as intended.

**Closed by vsmenon** 2021-08-09 14:09 UTC
Labels: type-question

**Comment by lrhn** [comment] 2021-08-09 14:24
(@jakemac53 Treating generic function types as being subtypes of non-generic function types is non-trivial. If we treat `... Function<T extends Object>(...)` as a subtype of `... Function(...)` with `T` replaced by `Object`, then we don't actually get very much. The type variable can occur both co- and contra-variantly. We'd probably likely like `T id<T>(T value) => value;` to be a subtype of `int Function(int)` as well, not just `dynamic Function(dynamic)`, but that means we can't just use the instantiate to bound type as the "non-generic equivalent type". And if it *is* a subtype, then we'd assume `int Function(int) intId = id;` would be a plain assignment with no coercion and instantiation, which means that the invocation would now have to recognize that a type argument must be inserted, and that it must be `int`. So, does not seem like something we can easily do and get good results.)

**Comment by jakemac53** [comment] 2021-08-09 16:48
> And if it _is_ a subtype, then we'd assume `int Function(int) intId = id;` would be a plain assignment with no coercion and instantiation, which means that the invocation would now have to recognize that a type argument must be inserted, and that it must be `int`.

Ah yes interesting. I could see allowing inference to fill this in, and otherwise only allowing type variables to occur covariantly? It still wouldn't cover all use cases that you might expect to work though you are right.
