### ISSUE TITLE
Marking an FFI function as leaf call blocks other Isolates

### ISSUE THREAD

**Issue by simc** [dart-lang/sdk#53030] opened 2023-07-24 21:49 UTC
Under certain conditions calling a leaf function can ~~deadlock the app~~ block other Isolates even though it does not call back into the Dart VM. Changing it to a non-leaf call works as expected.

#### Steps to reproduce:
- create a blocking native function using `sleep()` for example
- mark it as leaf function in Dart
- call it from multiple Isolates simultaneously

I tested this on macOS M1 but it does not seem to be platform dependent.

> Dart SDK version: 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_arm64"

**Comment by mraleph** [comment] 2023-07-25 20:54
Could you provide a full repro? 

I would suspect that this is a duplicate of https://github.com/dart-lang/sdk/issues/51254 and https://github.com/dart-lang/sdk/issues/51261 - though leaf vs non-leaf should not matter in this particular case AFAIK. 

Note that you should not mark potentially blocking functions as leaf (we should probably update documentation to mention that @dcharkes). VM can't do GCs while one of the threads are in the leaf call - so any attempt to trigger GC would block until blocking function returns.

**Comment by simc** [comment] 2023-07-25 22:37
It's a separate issue from the 16 Isolate maximum. It even happens with two Isolates. I'll create a full example.

**Closed** 2023-07-31 11:18 UTC
Labels: area-vm, library-ffi
