### ISSUE TITLE
Out-of-Memory manifesting as SIGBUS instead of meaningful error

### ISSUE THREAD

**Issue by ikarelin** [dart-lang/sdk#43131] opened 2020-08-20 19:40 UTC
Dart is crashing on Debian Linux. The same code is working perfectly on Mac.

===== CRASH =====
si_signo=Bus error(7), si_code=2, si_addr=0x7f6b008bcfe0
version=2.9.1 (stable) (Unknown timestamp) on "linux_x64"
pid=15947, thread=15969, isolate_group=main(0x55ac0ec90500), isolate=main(0x55ac0ec7a900)
isolate_instructions=55ac0c39cf80, vm_instructions=55ac0c39cf80
  pc 0x00007f6b17893a3e fp 0x00007f6b1712daa0 /lib/x86_64-linux-gnu/libc.so.6+0x15ca3e
  pc 0x000055ac0c5a1120 fp 0x00007f6b1712db10 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))+0xa0
  pc 0x00007f6b17181384 fp 0x00007f6b1712db50 Unknown symbol
  pc 0x00007f6b1672dcb5 fp 0x00007f6b1712dbc0 Unknown symbol
  pc 0x00007f6b04c035f7 fp 0x00007f6b1712dc68 Unknown symbol
  pc 0x00007f6b1672c1c4 fp 0x00007f6b1712dd00 Unknown symbol
  pc 0x00007f6b1672a907 fp 0x00007f6b1712dda0 Unknown symbol
  pc 0x00007f6b1672a10e fp 0x00007f6b1712dde0 Unknown symbol
  pc 0x00007f6b04c295bd fp 0x00007f6b1712de80 Unknown symbol
  pc 0x00007f6b16726e7c fp 0x00007f6b1712df20 Unknown symbol
  pc 0x00007f6b04c0761a fp 0x00007f6b1712df80 Unknown symbol
  pc 0x00007f6b04c0c281 fp 0x00007f6b1712e010 Unknown symbol
  pc 0x00007f6b04c04e72 fp 0x00007f6b1712e080 Unknown symbol
  pc 0x00007f6b04c0bb33 fp 0x00007f6b1712e0c8 Unknown symbol
  pc 0x00007f6b05177ec8 fp 0x00007f6b1712e128 Unknown symbol
  pc 0x00007f6b051778e5 fp 0x00007f6b1712e160 Unknown symbol
  pc 0x00007f6b1673fa22 fp 0x00007f6b1712e200 Unknown symbol
  pc 0x00007f6b04c0761a fp 0x00007f6b1712e260 Unknown symbol
  pc 0x00007f6b04c0c281 fp 0x00007f6b1712e2f0 Unknown symbol
  pc 0x00007f6b04c04e72 fp 0x00007f6b1712e360 Unknown symbol
  pc 0x00007f6b04c0bb33 fp 0x00007f6b1712e3a8 Unknown symbol
  pc 0x00007f6b05177ec8 fp 0x00007f6b1712e408 Unknown symbol
  pc 0x00007f6b051778e5 fp 0x00007f6b1712e440 Unknown symbol
  pc 0x00007f6b05178a34 fp 0x00007f6b1712e4d8 Unknown symbol
  pc 0x00007f6b04c0761a fp 0x00007f6b1712e538 Unknown symbol
  pc 0x00007f6b04c0c281 fp 0x00007f6b1712e5c8 Unknown symbol
  pc 0x00007f6b04c04e72 fp 0x00007f6b1712e638 Unknown symbol
  pc 0x00007f6b04c131a9 fp 0x00007f6b1712e688 Unknown symbol
  pc 0x00007f6b04c0f5b2 fp 0x00007f6b1712e6e8 Unknown symbol
  pc 0x00007f6b04c0f7c6 fp 0x00007f6b1712e708 Unknown symbol
  pc 0x00007f6b04c0a489 fp 0x00007f6b1712e7f0 Unknown symbol
  pc 0x00007f6b04c13e1f fp 0x00007f6b1712e818 Unknown symbol
  pc 0x00007f6b04c070c8 fp 0x00007f6b1712e850 Unknown symbol
  pc 0x00007f6b171816ef fp 0x00007f6b1712e8c8 Unknown symbol
  pc 0x000055ac0c539392 fp 0x00007f6b1712e960 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x112
  pc 0x000055ac0c5390f4 fp 0x00007f6b1712e9f0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x2d4
  pc 0x000055ac0c53b576 fp 0x00007f6b1712ea40 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x1f6
  pc 0x000055ac0c572614 fp 0x00007f6b1712ec30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x4a4
  pc 0x000055ac0c59f836 fp 0x00007f6b1712eca0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x146
  pc 0x000055ac0c59feea fp 0x00007f6b1712ed00 dart::MessageHandler::TaskCallback()+0x1da
  pc 0x000055ac0c6aa8c8 fp 0x00007f6b1712ed80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x000055ac0c6aad9c fp 0x00007f6b1712edb0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
  pc 0x000055ac0c62305d fp 0x00007f6b1712ee70 dart+0x1bb405d
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f6b1712db50) pc(0)]
[dart     : sp(0x7f6b1712db60) fp(0x7f6b1712dbc0) pc(0x7f6b1672dcb5) dart:typed_data__TypedListBase@7027147__setRange@7027147 ]
[dart     : sp(0x7f6b1712dbd0) fp(0x7f6b1712dc68) pc(0x7f6b04c035f7) *dart:typed_data___Uint8List&_TypedList&_IntListMixin&_TypedIntListMixin@7027147_setRange ]
[dart     : sp(0x7f6b1712dc78) fp(0x7f6b1712dd00) pc(0x7f6b1672c1c4) dart:typed_data___Uint8List&_TypedList&_IntListMixin&_TypedIntListMixin@7027147_sublist ]
[dart     : sp(0x7f6b1712dd10) fp(0x7f6b1712dda0) pc(0x7f6b1672a907) dart:convert_Utf8Encoder_convert ]
[dart     : sp(0x7f6b1712ddb0) fp(0x7f6b1712dde0) pc(0x7f6b1672a10e) dart:convert_Codec_encode ]
[dart     : sp(0x7f6b1712ddf0) fp(0x7f6b1712de80) pc(0x7f6b04c295bd) dart:io__File@15069316_writeAsString ]
[dart     : sp(0x7f6b1712de90) fp(0x7f6b1712df20) pc(0x7f6b16726e7c) package:getbook24_cli/getbook24_cli.dart_::_getLitresBooks__async_op ]
[dart     : sp(0x7f6b1712df30) fp(0x7f6b1712df80) pc(0x7f6b04c0761a) *dart:async__FutureListener@4048458_handleValue ]
[dart     : sp(0x7f6b1712df90) fp(0x7f6b1712e010) pc(0x7f6b04c0c281) *dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
[dart     : sp(0x7f6b1712e020) fp(0x7f6b1712e080) pc(0x7f6b04c04e72) *dart:async__Future@4048458__propagateToListeners@4048458 ]
[dart     : sp(0x7f6b1712e090) fp(0x7f6b1712e0c8) pc(0x7f6b04c0bb33) *dart:async__Future@4048458__completeWithValue@4048458 ]
[dart     : sp(0x7f6b1712e0d8) fp(0x7f6b1712e128) pc(0x7f6b05177ec8) dart:async__AsyncAwaitCompleter@4048458_complete ]
[dart     : sp(0x7f6b1712e138) fp(0x7f6b1712e160) pc(0x7f6b051778e5) dart:async_::__completeOnAsyncReturn@4048458 ]
[dart     : sp(0x7f6b1712e170) fp(0x7f6b1712e200) pc(0x7f6b1673fa22) package:http/http.dart_::__withClient@24447473__async_op ]
[dart     : sp(0x7f6b1712e210) fp(0x7f6b1712e260) pc(0x7f6b04c0761a) *dart:async__FutureListener@4048458_handleValue ]
[dart     : sp(0x7f6b1712e270) fp(0x7f6b1712e2f0) pc(0x7f6b04c0c281) *dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
[dart     : sp(0x7f6b1712e300) fp(0x7f6b1712e360) pc(0x7f6b04c04e72) *dart:async__Future@4048458__propagateToListeners@4048458 ]
[dart     : sp(0x7f6b1712e370) fp(0x7f6b1712e3a8) pc(0x7f6b04c0bb33) *dart:async__Future@4048458__completeWithValue@4048458 ]
[dart     : sp(0x7f6b1712e3b8) fp(0x7f6b1712e408) pc(0x7f6b05177ec8) dart:async__AsyncAwaitCompleter@4048458_complete ]
[dart     : sp(0x7f6b1712e418) fp(0x7f6b1712e440) pc(0x7f6b051778e5) dart:async_::__completeOnAsyncReturn@4048458 ]
[dart     : sp(0x7f6b1712e450) fp(0x7f6b1712e4d8) pc(0x7f6b05178a34) package:http/src/response.dart_Response_fromStream__async_op ]
[dart     : sp(0x7f6b1712e4e8) fp(0x7f6b1712e538) pc(0x7f6b04c0761a) *dart:async__FutureListener@4048458_handleValue ]
[dart     : sp(0x7f6b1712e548) fp(0x7f6b1712e5c8) pc(0x7f6b04c0c281) *dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]
[dart     : sp(0x7f6b1712e5d8) fp(0x7f6b1712e638) pc(0x7f6b04c04e72) *dart:async__Future@4048458__propagateToListeners@4048458 ]
[dart     : sp(0x7f6b1712e648) fp(0x7f6b1712e688) pc(0x7f6b04c131a9) *dart:async__Future@4048458__asyncCompleteWithValue@4048458_<anonymous closure> ]
[dart     : sp(0x7f6b1712e698) fp(0x7f6b1712e6e8) pc(0x7f6b04c0f5b2) *dart:async_::__startMicrotaskLoop@4048458 ]
[dart     : sp(0x7f6b1712e6f8) fp(0x7f6b1712e708) pc(0x7f6b04c0f7c6) *dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
[dart     : sp(0x7f6b1712e718) fp(0x7f6b1712e7f0) pc(0x7f6b04c0a489) *dart:isolate__Timer@1026248__runTimers@1026248 ]
[dart     : sp(0x7f6b1712e800) fp(0x7f6b1712e818) pc(0x7f6b04c13e1f) *dart:isolate__Timer@1026248__handleMessage@1026248__handleMessage@1026248 ]
[dart     : sp(0x7f6b1712e828) fp(0x7f6b1712e850) pc(0x7f6b04c070c8) *dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x7f6b1712e860) fp(0x7f6b1712e8c8) pc(0x7f6b171816ef)]
Aborted

**Comment by devoncarew** [comment] 2020-08-20 21:19
Thanks for the report! Can you include a bit more information about what you were doing - what app you were running, and the version of the Dart SDK?

**Comment by ikarelin** [comment] 2020-08-21 07:16
Dart version in the crash log. But I've found what happens - I'm getting out of memory. When I made a native dart file, it showing out of memory error.

**Comment by rmacnak-google** [comment] 2020-08-24 18:03
Duplicate of https://github.com/dart-lang/sdk/issues/41169

**Closed by rmacnak-google** 2020-08-24 18:03 UTC
Labels: area-vm
