### ISSUE TITLE
pub run and "termcaps"

### ISSUE THREAD

**Issue by tristancaron** [dart-lang/sdk#24018] opened 2015-08-07 17:47 UTC
Hello,

I use the package `console` which one allow to use "termcaps". It works well when run from `dart` like `dart bin/main.dart`. But when it's run from `pub run` like `pub run my_package:main` it throws an error:

```
Unhandled exception:
Uncaught Error: StdoutException: Could not get terminal size, OS Error: Inappropriate ioctl for device, errno = 25
Stack Trace:
#0      Stdout._terminalSize (dart:io-patch/stdio_patch.dart:74)
#1      Stdout._terminalColumns (dart:io-patch/stdio_patch.dart:68)
#2      Stdout.terminalColumns (dart:io/stdio.dart:182)
#3      StdioConsoleAdapter.columns (package:console/src/adapter.dart:21:29)
#4      Console.columns (package:console/src/base.dart:181:38)
#5      Window.draw (package:console/src/curses/window.dart:28:25)
#6      UserInterface.draw (package:db_init/src/user_interface.dart:21:15)
#7      Window.display (package:console/src/curses/window.dart:42:5)
#8      main.<main_async_body> (http://localhost:52545/db_init.dart:17:6)
#9      _RootZone.runUnary (dart:async/zone.dart:1166)
#10     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#11     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#12     _Future._propagateToListeners.handleWhenCompleteCallback.<anonymous closure> (dart:async/future_impl.dart:560)
#13     _RootZone.runUnary (dart:async/zone.dart:1166)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#16     _Future._completeWithValue (dart:async/future_impl.dart:368)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#19     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by nex3** [comment] 2015-08-07 20:16
Duplicate of dart-lang/pub#1204.

**Closed by nex3** 2015-08-07 20:16 UTC
Labels: Area-Pub
