### ISSUE TITLE
Front end raises compile-time error for nnbd/legacy member signature difference

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#40268] opened 2020-01-22 17:03 UTC
Consider the following program:

```dart
// Main entry point, file 'scratch_test.dart'.
import 'lib1.dart';
import 'lib2.dart';

void main() {}
```
```dart
// File 'lib1.dart'.

abstract class A { 
  void f<X extends num?>(X x);
}
```
```dart
// File 'lib2.dart'.
// @dart = 2.6

import 'lib1.dart';

class B extends A {
  void f<X extends num>(X x) {}
}
```

We can check this program by putting all files into `tests/language` and running:

<details><summary>Analyzer run (click to expand)</summary>

```
> tools/build.py -m release --nnbd create_sdk
> tools/test.py -n analyzer-asserts-strong-linux --enable-experiment=non-nullable --nnbd=strong  language/scratch_test
Test configuration:
    analyzer-asserts-strong-linux(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: linux, nnbd: strong, enable-experiment: [non-nullable], enable-asserts, use-sdk)
Suites tested: language
[00:03 | 100% | +    1 | -    0]
```
</details>

which shows (as of a9ea9365ad8a3e3b59115bd889a55b6aa2c5a5fa) that the program is accepted by the analyzer. However, we get the following errors from the front end:

<details><summary>Front end run (click to expand)</summary>

```
> tools/test.py -n cfe-weak-linux --enable-experiment=non-nullable --nnbd=strong  tests/language/scratch_test
Test configuration:
    cfe-weak-linux(architecture: x64, compiler: fasta, mode: release, runtime: none, system: linux, nnbd: weak, enable-experiment: [non-nullable])
Suites tested: language

FAILED: fasta-none release_x64 language/scratch_test
Expected: Pass
Actual: CompileTimeError

--- Command "fasta" (took 06.000827s):
(cd /usr/local/google/home/eernst/devel/dart/work/sdk/ ; DART_CONFIGURATION=ReleaseX64NNBD ./out/ReleaseX64NNBD/dart ./pkg/front_end/tool/_fasta/compile.dart --verify -o ./out/ReleaseX64NNBD/generated_compilations/fasta/tests_language_scratch_test/out.dill --platform ./out/ReleaseX64NNBD/vm_platform_strong.dill --enable-experiment=non-nullable --packages=./.packages ./tests/language/scratch_test.dart )

exit code:
1

stdout:
tests/language/lib2.dart:3:26: Error: Declared type variables of 'B.f' doesn't match those on overridden method 'A.f'.
class B extends A { void f<X extends num>(X x) {} }
                         ^
tests/language/lib1.dart:1:25: Context: This is the overridden method ('f').
abstract class A { void f<X extends num?>(X x); }
                        ^

--- Re-run this test:
python tools/test.py -n cfe-weak-linux --nnbd strong --enable-experiment non-nullable language/scratch_test

[00:07 | 100% | +    0 | -    1]
```
</details>

The front end needs to tolerate the discrepancies between member signatures that arise because an opted-out library cannot specify things like a type variable bound which is `num?` (otherwise opting in a widely used library would break a lot of existing importers that haven't yet been migrated).

The library 'scratch_test.dart' can be opted in or out, that makes no difference.

**Comment by johnniwinther** [comment] 2020-01-23 07:52
Duplicate of https://github.com/dart-lang/sdk/issues/40220

**Closed by johnniwinther** 2020-01-23 07:52 UTC
Labels: area-front-end, type-bug
