### ISSUE TITLE
Recently replaced files in project folder then ran the project.

### ISSUE THREAD

**Issue by tpackard1** [dart-lang/sdk#35837] opened 2019-02-03 03:33 UTC
Recently replaced files in project folder then ran the project. Error occurred but app still ran...

Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-182.5107.16.33.5199772`
- `2.1.0-dev.9.4`
- `AI-182.5107.16.33.5199772, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

# Exception

Please append the contents of:
file://C:\Users\Taylor\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Taylor\Documents\music_player], excluded: [C:\Users\Taylor\Documents\music_player\.idea, C:\Users\Taylor\Documents\music_player\.dart_tool, C:\Users\Taylor\Documents\music_player\.idea, C:\Users\Taylor\Documents\music_player\.pub, C:\Users\Taylor\Documents\music_player\build, C:\Users\Taylor\Documents\music_player\fluttery-master\.dart_tool, C:\Users\Taylor\Documents\music_player\fluttery-master\.pub, C:\Users\Taylor\Documents\music_player\fluttery-master\build, C:\Users\Taylor\Documents\music_player\fluttery-master\example\.dart_tool, C:\Users\Taylor\Documents\music_player\fluttery-master\example\.pub, C:\Users\Taylor\Documents\music_player\fluttery-master\example\build]}, clientRequestTime: 1549163757476}
FileSystemException: Exists failed, path = 'C:\Users\Taylor\Documents\music_player\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-sw' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)

**Comment by stereotype441** [comment] 2019-02-05 16:03
Duplicate of #34294

**Closed by stereotype441** 2019-02-05 16:03 UTC
Labels: area-analyzer
