### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by amitjangid80** [dart-lang/sdk#38266] opened 2019-09-09 11:40 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /Users/marutitathe/Desktop/MobileApps/FlutterApps/study_circle_counselor_faculty/lib/faculty/facultyDashboardPage.dart context: exception_20190909_170934_787
Bad state: Element not contained in compilation unit: Never
#0      getUnitElement (package:analyzer/src/dart/analysis/index.dart:28:3)
#1      _IndexAssembler._getElementInfo.<anonymous closure> (package:analyzer/src/dart/analysis/index.dart:346:44)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#3      _IndexAssembler._getElementInfo (package:analyzer/src/dart/analysis/index.dart:345:23)
#4      _IndexAssembler.addElementRelation (package:analyzer/src/dart/analysis/index.dart:235:32)
#5      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:499:15)
#6      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:451:7)
#7      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:759:5)
#8      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8976:49)
#9      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7435:18)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#11     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55)
#12     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:267:41)
#13     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:617:11)
#14     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#15     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7430:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#17     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:378:16)
#18     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#19     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:143:45)
#20     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:374:49)
#21     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6188:20)
#22     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#23     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:55)
#24     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:267:41)
#25     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:617:11)
#26     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:374:7)
#27     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6100:15)
#28     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8644:18)
#29     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#30     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#31     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:486:51)
#32     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8640:49)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7676:20)
#34     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1121:17)
#35     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#36     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:514:39)
#37     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:31)
#38     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#39     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#40     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#41     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:321:45)
#42     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:55)
#43     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#44     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7116:12)
#45     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#46     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:47)
#47     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:230:43)
#48     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:186:43)
#49     GeneralizingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:416:55)
#50     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7107:49)
#51     NodeListImpl.accept (package:ana...
```

For additional log information, please append the contents of
file:///private/var/folders/1h/1x37y0c96z50b3hpzcg8sgj80000gn/T/report.txt.

**Comment by MichaelRFairhurst** [comment] 2019-09-09 20:23
duplicate of #38268

**Closed by MichaelRFairhurst** 2019-09-09 20:23 UTC
Labels: area-analyzer
