### ISSUE TITLE
Analyzer feedback from Intellij: exception in parser

### ISSUE THREAD

**Issue by adeolaex** [dart-lang/sdk#39347] opened 2019-11-12 13:46 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
NoSuchMethodError: The getter 'next' was called on null.
Receiver: null
Tried calling: next
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Parser.parseLiteralFunctionSuffix (package:front_end/src/fasta/parser/parser.dart:4576:38)
#2      Parser.parseLiteralListSetMapOrFunction (package:front_end/src/fasta/parser/parser.dart:4608:14)
#3      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4295:14)
#4      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4184:12)
#5      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3972:13)
#6      Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3944:13)
#7      Parser.parseFieldInitializerOpt (package:front_end/src/fasta/parser/parser.dart:2486:15)
#8      Parser.parseFields (package:front_end/src/fasta/parser/parser.dart:2391:13)
#9      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3146:15)
#10     Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#11     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#12     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#13     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#14     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#15     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#16     ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:157:32)
#17     ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:152:12)
#18     _File._parse (package:analyzer/src/services/available_declarations.dart:1839:23)
#19     _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#20     DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:660:14)
#21     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:573:18)
#22     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#23     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#24     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#25     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#26     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#27     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#28     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#34     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#36     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#37     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#38     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#39     new Future.sync (dart:async/future.dart:224:31)
#40     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#46     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#47     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#48     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#50     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/j7/67nj_kjn2gnbd1vh001px3vw0000gn/T/report.txt.

**Comment by keertip** [comment] 2019-11-12 17:25
Thanks for the report! This was previously reported in #38738, please follow along there.

**Comment by keertip** [comment] 2019-11-12 17:25
Duplicate of #38738

**Closed by keertip** 2019-11-12 17:25 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug

**Comment by adeolaex** [comment] 2019-12-03 21:56
Thank you very much. Was able to get it all fixed.
