### ISSUE TITLE
Dart analyzer fails on flutter website include after upgrade to 1.23.0-dev.11.5

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#29281] opened 2017-04-06 09:14 UTC
Repro steps:
```
git clone https://github.com/flutter/website.git
cd website/_includes/_code/stack
flutter packages get
flutter analyze
```

Errors with:
```
Analyzing /Users/mit/dev/github/flutter-website/_includes/_code/stack...
    error • Invalid constant value at main.dart:1:1 • invalid_constant
1 error found.
(Ran in 3.3s)
```

**Comment by mit-mit** [comment] 2017-04-06 09:15
Flutter bug is https://github.com/flutter/flutter/issues/9248

This was working when we were on 1.23.0-dev.10.0, but failing now after the roll in https://github.com/flutter/flutter/pull/9151/files to 1.23.0-dev.11.5.

**Comment by mit-mit** [comment] 2017-04-06 09:15
cc @bwilkerson any idea what is going on here?

**Comment by bwilkerson** [comment] 2017-04-06 16:04
No. I followed the repro steps above but the result was "No errors". I expect that's because I don't have the same version of flutter that you're using, so I ran the bleeding-edge version of the command-line analyzer over the code and it also returned no errors. It would be interesting to run the dev.11.5 version of the command-line analyzer and see what result we get (I don't have that easily available).

It seems like the two most likely causes are (a) there was a bug in the dev.11.5 version of analyzer or (b) flutter's integration of analyzer is causing a problem (probably related to resolution of symbols). Running the dev.11.5 version of analyzer could help narrow it down.

**Comment by mit-mit** [comment] 2017-04-06 18:25
Can you try to run `flutter upgrade` first, and then run the repro steps again?

`flutter doctor` after that should say that you are running  a flutter based on 11.5

**Comment by bwilkerson** [comment] 2017-04-06 19:02
When I do a `flutter upgrade` I see the error. Of course, that doesn't tell me whether it's been fixed in bleeding edge or whether flutter's wrapping of dartanalyzer is causing the bug to be exhibited.

**Comment by mit-mit** [comment] 2017-04-07 11:25
You can also repro like this using the regular `dartanalyzer`:

```
git clone https://github.com/flutter/website.git
cd website/_includes/_code/stack
flutter packages get
dartanalyzer .
```

**Comment by bwilkerson** [comment] 2017-04-07 15:47
The problem appears to be in the way we are serializing and deserializing assertions in the initializer list. The file flutter/packages/flutter/lib/src/painting/fractional_offset.dart contains a constructor of the form:
```
const FractionalOffset(this.dx, this.dy)
  : assert(dx != null),
    assert(dy != null);
```
But when we deserialize it the ConstructorElement contains a single constant initializer (an instance of ConstructorFieldInitializerImpl) of the form
```
assert = assert
```
which then cannot be evaluated when we find a constructor invocation.

**Comment by pq** [comment] 2017-04-07 16:28
After reproducing and a little digging, bouncing back to @bwilkerson since this is summary-related and I lack context.  Or maybe @scheglov could take a look?

Needless to say, happy to pitch in here or elsewhere if/when it makes sense.

**Comment by scheglov** [comment] 2017-04-07 16:37
Summarization of assert initializers works fine when I try it in unit tests.

But it seems that this (experimental) language feature is disabled when we analyze `website/_includes/_code/stack`, so `fractional_offset.dart` is parsed incorrectly.

**Comment by pq** [comment] 2017-04-07 16:40
Interesting!

How do we enable assert initializers?

**Comment by scheglov** [comment] 2017-04-07 16:40
When I update `website/.analysis_options` to include
```
analyzer:
  language:
    enableStrictCallChecks: true
    enableSuperMixins: true
    enableAssertInitializer: true
```

...then analysis does not produce errors.

How `website` is expected to get analysis options? Should it mix in some flutter options?

**Comment by pq** [comment] 2017-04-07 16:41
Fantastic!

> How website is expected to get analysis options? Should it mix in some flutter options?

@danrubel?

**Comment by devoncarew** [comment] 2017-04-07 16:49
There's a file here:

    https://github.com/flutter/website/blob/master/.analysis_options

which we should just update :)

**Closed** 2017-04-07 17:12 UTC
Labels: area-analyzer, Customer-Flutter
