### ISSUE TITLE
get_allocation_traces_test failing on dartk-linux-release-arm64

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#51495] opened 2023-02-22 19:21 UTC
The tests
```
service_2/get_allocation_traces_test/dds RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-linux-release-arm64
```

```
Expected: <2>
    Actual: <1>
  

  package:test_api/src/expect/expect.dart 134:31                               fail
  package:test_api/src/expect/expect.dart 129:3                                _expect
  package:test_api/src/expect/expect.dart 46:3                                 expect
  runtime/observatory_2/tests/service_2/get_allocation_traces_test.dart 127:5  tests.<fn>
  ===== asynchronous gap ===========================
  runtime/observatory_2/tests/service_2/test_helper.dart 495:17                _ServiceTesterRunner.run.runTest.<fn>.<fn>
  ===== asynchronous gap ===========================
  runtime/observatory_2/tests/service_2/test_helper.dart 374:9                 _ServiceTesterRunner.run.ignoreLateException
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 215:9                             Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7                             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 258:9                              Invoker._waitForOutstandingCallbacks.<fn>
```

Commit range is large, but possibly started with 347c49354e93e2aac93de95f1295db9bfb9254e7.

**Comment by a-siva** [comment] 2023-02-24 00:40
This appears to be a duplicate of https://github.com/dart-lang/sdk/issues/51487

**Closed by a-siva** 2023-02-24 00:40 UTC
Labels: area-vm, closed-duplicate
