### ISSUE TITLE
Wrong calculation for subtracting days for April 1st of 2021 for en_US

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [dart-lang/sdk#45405] opened 2021-03-22 04:19 UTC
**Describe the bug**
The straightforward calculation yields wrong data.
The same case is for Flutter's DateTime class.
The culprit is **subract days** method.

**To Reproduce**

1. Run the app on **en_US** locale.
2. Use the code with DateTime:
```
    final DateTime thisDateTime =
        DateTime(2021,4,1)
            .toLocal()
            .subtract(Duration(days: days));
```
3. Call it with: `DateTime(2021,4,1).subtract(Duration(days: 4))`
4. Observe **March 27th**, not **March 28th**.

**Expected behavior**
Subtracting should yield correct date.

**Additional context**
Looks related with DateTime internals.

**Comment by lrhn** [comment] 2021-03-22 09:25
This is working as intended. You should never do *calendar* arithmetic using local time.

You are not subtracting calendar days here, you are subtracting multiples of 24 hours, 96 hours in this case.
If you subtract 96 hours from local time 2021-04-01T00:00:00, you get 2021-03-27T23:00:00 if *daylight saving* started at 2021-03-28T02:00:00. Using local time means that you can change time zones, which is why your should avoid local time when dealing with calendar dates.
```dart
void main() {
  var d= DateTime.utc(2021, 4, 1); // Calendar date in UTC
  print(d); // 2021-04-01 00:00:00.000Z
  d =d.subtract(Duration(hours: 24 * 4)); // Day-arithmetic in UTC.
  print(d); // 2021-03-28 00:00:00.000Z
  d = DateTime(d.year, d.month, d.day) // Convert to same date in local time.
  print(d); // 2021-03-28 00:00:00.000  -- local time
}
```

It's slightly curious that you change on the 28th with a en_US locale, but I guess en_US is not specific enough to actually specify a time zone (there are at least three time zones in the continental US, and at least one state which doesn't do daylight saving), and the code is picking up a different daylight saving schedule.

**Comment by vsmenon** [comment] 2021-03-22 15:10
Lasse - do you want to keep this open?

**Comment by lrhn** [comment] 2021-03-22 17:14
Let's close it. If there is some aggravating information we're missing, we can reopen.

**Closed by lrhn** 2021-03-22 17:14 UTC
Labels: area-library, library-core
