### ISSUE TITLE
remove " ; " end of line like kotlin

### ISSUE THREAD

**Issue by hieuseesaa** [dart-lang/sdk#38429] opened 2019-09-17 03:12 UTC
Hello admin
in kotlin
`var title = ""`
in dart
`var title = "";`
- I think not use " ; " at the end of that line is amazing. So think about it
 Thanks team.

**Comment by lrhn** [comment] 2019-09-17 05:36
We have been, and still are, thinking about it. However, since Dart's syntax is not designed for omitting semicolons, simply dropping them is not an option.
We have not yet been able to find an approach which allows omitting semicolons and which also gives a good user experience in both the common and the tricky cases.

See https://github.com/dart-lang/sdk/issues/30347 for more discussion (closing as duplicate of that thread)

**Closed by lrhn** 2019-09-17 05:36 UTC

**Comment by hieuseesaa** [comment] 2019-09-17 05:40
@lrhn I hope that comes true. thank you very much.
