### ISSUE TITLE
Analyzer From IntelliJ

### ISSUE THREAD

**Issue by hadongz** [dart-lang/sdk#35030] opened 2018-11-02 10:18 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-182.4892.20`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `IC-182.4892.20, JRE 1.8.0_152-release-1248-b19x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\MUHAMM~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\Muhammad Hadi\IdeaProjects\trial_number18\lib\src\login_page.dart
Exception: Element not found in summary: dart:async

**Comment by srawlins** [comment] 2018-11-03 22:35
Duplicate of #35023.

**Closed by srawlins** 2018-11-03 22:35 UTC
