### ISSUE TITLE
lamdba in initializer list is not accepted without parens

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#35673] opened 2019-01-16 08:14 UTC
The following code triggers error but it looks fine to me:

```dart
class A {
  A(void Function(Object) f) : _f = (p) => f(p);
  final void Function(Object) _f;
}
```

To avoid the errors I have to wrap the lambda with parens:

```dart
class A {
  A(void Function(Object) f) : _f = ((p) => f(p));
  final void Function(Object) _f;
}
```

The issue exists on 2.1.0 (tested in dartpad) and 2.1.1-dev.1.0 f81dd1da9f

**Comment by eernstg** [comment] 2019-01-16 10:36
This is working as intended. It is a parsing ambiguity with unlimited lookahead to accept a function literal at that point, because we could have the following:

```dart
class A {
  final x;
  A(p): x = (p) { /*lots of code*/ }
}
```
If we add a semicolon at the end of the constructor then we would consider `(p) { /*lots of code*/ }` to be a function literal which is used to initialize `x`; if we do not have the semicolon then `x` is initialized to `(p)`, and the 'lots of code' is the body of the constructor.

So disambiguation was done by preventing function literals in initializer lists.

**Comment by eernstg** [comment] 2019-01-16 10:50
(Looking into the spec, I suspect that this particular syntactic rule may not be specified; the grammar Dart.g does not enforce it, but tools do)...

**Comment by a14n** [comment] 2019-01-16 13:52
Thanks for the explanation.

**Comment by eernstg** [comment] 2019-01-16 17:20
I'll close this because there is no plan to change the tools, and issue #35674 has been created to ensure that the specification will describe this constraint.

**Closed by eernstg** 2019-01-16 17:20 UTC
Labels: closed-as-intended
