### ISSUE TITLE
Some relative paths are allowed for native extensions - but don't resolve as expected

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/sdk#27015] opened 2016-08-03 12:50 UTC
If i change

```
import "dart-ext:test_extension";
```

to

```
import "dart-ext:../test_extension";
```

in `tests/standalone/io/test_extension.dart`.
the test still run

```
tools/test.py standalone/io/test_extension
```

and the `.so` file is _not_ loaded in the parent directory.

/cc @johnmccutchan

**Comment by zanderso** [comment] 2016-08-26 22:36
When a scheme is present, initial dot segments are removed. See: https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/uri.dart#L2330

Should we add a special case for 'dart-ext'?

**Comment by sgjesse** [comment] 2016-08-29 06:48
I would say that dart-ext: URIs are somewhat special, and you should be able to locate the native library in a parent directory. @lrhn what do you think?

**Comment by lrhn** [comment] 2016-08-29 07:22
The problem is that we have what is logically a URI relative reference, but with a scheme. Which means it's not a relative reference, it is an absolute URI. 
The ".." is intended only for use at the beginning of a relative reference, so we remove it when we do path normalization on a URI that isn't a relative reference.

We could change the `Uri` class (again) to keep leading `..` segments even for absolute URIs. The problem is that it changes equivalence of URIs (unless we do path normalization before all equality checks, and nobody got time for that). You can have `file:../windows` and `file:/windows` that are effectively the same when used, but which compare differently.

We do have a problem, but I think the problem is that the `dart-ext` scheme is more broken than the `package` scheme. You want to have a path that is *relative* to a different *scheme*. That's just not something URIs are built for.

I don't have a good solution. "Don't use URIs" isn't really workable. How about changing the syntax to:

```dart
@dartext import "../test_extension";
```
with `dartext` being an annotation defined in `dart:io` (since I assume this is server-side only anyway).

**Comment by zanderso** [comment] 2016-08-30 17:04
Tagging this as a language issue since it sounds like there isn't a spec for dart-ext, and since I don't want to make a breaking change to the VM's behavior by accident by adding special cases.

**Comment by MikeMitterer** [comment] 2016-12-16 14:26
I've just filed another, path related, issue: #28138

**Comment by lrhn** [comment] 2018-06-25 06:11
This is not a language issue. The `dart-ext` scheme is not part of the language, it's a pure VM extension.

It might be a library issue (the `Uri` class is normalizing a URI with an unknown scheme, that could be seen as wrong).

**Comment by mit-mit** [comment] 2021-07-26 13:00
Closing: native extensions are deprecated are expected to be removed, see https://github.com/dart-lang/sdk/issues/45451.

**Closed by mit-mit** 2021-07-26 13:00 UTC
Labels: area-library, library-core, type-enhancement
