### ISSUE TITLE
Customer-reported issue with NNBD migration tool: Could not load dart file /Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart

### ISSUE THREAD

**Issue by sobrienpdx** [dart-lang/sdk#45648] opened 2021-04-10 00:03 UTC
Could not load dart file /Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart

Error: NoSuchMethodError: method not found: 'length' on null

Please fill in the following:

**Name of package being migrated (if public)**:
**What I was doing when this issue occurred**: I clicked "rerun"
**Is it possible to work around this issue**: probably
**Has this issue happened before, and if so, how often**: no
**Dart SDK version**: 2.12.2
**Additional details**: @stereotype441  was helping when this error occurred

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
TypeError: Cannot read property 'length' of null
    at Object.mH (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:3637:9)
    at Object.BX (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:3459:5)
    at http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:3265:3
    at Gs.a (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:1572:72)
    at Gs.$2 (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:4670:23)
    at WM.$1 (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:4662:30)
    at Ji.bv (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:4937:25)
    at rq.$0 (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:4865:11)
    at Object.HZ (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:1620:39)
    at vs.X2 (http://127.0.0.1:61939/Users/shaunnaobrien/data_flashcards/tablet_app/lib/widget/kid_button.dart?offset=287&line=11&authToken=EwJkaKPYi1c%3D:4781:3)
```

**Comment by stereotype441** [comment] 2021-04-14 15:45
Duplicate of #45163.

**Closed by stereotype441** 2021-04-14 15:45 UTC
Labels: P1, area-migration
