### ISSUE TITLE
Dart ignores non-nullability of variables and function parameters.

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#39678] opened 2019-12-06 06:27 UTC
Dart VM version: 2.7.0-dev.2.1 (Mon Dec 2 20:10:59 2019 +0100) on "windows_x64"

The following test example tries to assign `null` values to non-nullable variables (if nnbd is enabled):
``` dart
class A {
  void test(int i) { print(i); }
}

main() {
  int i;
  i = null;
  print(i);
  A().test(1);
  A().test(null);
}
```
It throws a compile error with analyzer and prints `null` variable values with dart.

As `i` is non-nullable, it seems like dart should throw compile errors for the lines 7 and 10 too.

Sample output is:
> $> dartanalyzer --enable-experiment=non-nullable test.dart 
> Analyzing test.dart...
>   error - A value of type 'Null' can't be assigned to a variable of type 'int'. - test.dart:7:7 - invalid_assignment
>   error - The argument type 'Null' can't be assigned to the parameter type 'int'. - test.dart:10:12 - argument_type_not_assignable
> 2 errors found.
> 
> $> dart --enable-experiment=non-nullable test.dart 
> null
> 1
> null

**Comment by a-siva** [comment] 2019-12-07 00:48
Thanks for your feedback, the non nullability language feature is still being implemented in the Dart VM and is not fully functional yet.

**Comment by stefantsov** [comment] 2019-12-16 15:07
Quick status update on the CFE.

As of https://github.com/dart-lang/sdk/commit/c85979a28099c021b901772c2d7c715b2f9423ae the CFE emits compile-time errors (or warnings, depending on the mode) for lines `i = null;` and `A().test(null);`.  Here's how to test it:

<details><summary>Click to expand</summary>

```bash
$ cat /tmp/asdf.dart
class A {
  void test(int i) { print(i); }
}

main() {
  int i;
  i = null;
  print(i);
  A().test(1);
  A().test(null);
}

$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/tool/_fasta/compile.dart --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks --nnbd-strong /tmp/asdf.dart
/tmp/asdf.dart:7:7: Error: A value of type 'Null?' can't be assigned to a variable of type 'int'.
  i = null;
      ^
/tmp/asdf.dart:10:12: Error: The argument type 'Null?' can't be assigned to the parameter type 'int'.
  A().test(null);
           ^
library;
//
// Problems in library:
//
// /tmp/asdf.dart:7:7: Error: A value of type 'Null?' can't be assigned to a variable of type 'int'.
//   i = null;
//       ^
//
// /tmp/asdf.dart:10:12: Error: The argument type 'Null?' can't be assigned to the parameter type 'int'.
//   A().test(null);
//            ^
//
import self as self;
import "dart:core" as core;

class A extends core::Object {
  synthetic constructor •() → self::A
    : super core::Object::•()
    ;
  method test(core::int i) → void {
    core::print(i);
  }
}
static method main() → dynamic {
  core::int i;
  i = let final<BottomType> #t1 = invalid-expression "/tmp/asdf.dart:7:7: Error: A value of type 'Null?' can't be assigned to a variable of type 'int'.\n  i = null;\n      ^" in null as{TypeError} core::int;
  core::print(i);
  new self::A::•().{self::A::test}(1);
  new self::A::•().{self::A::test}(let final<BottomType> #t2 = invalid-expression "/tmp/asdf.dart:10:12: Error: The argument type 'Null?' can't be assigned to the parameter type 'int'.\n  A().test(null);\n           ^" in null as{TypeError} core::int);
}
```
</details>

To compile in weak mode, remove flag `--nnbd-strong`:

<details><summary>Click to expand</summary>

```bash
$ sdk/bin/dart pkg/front_end/tool/fasta.dart compile --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks /tmp/asdf.dart
Running: .../sdk/bin/dart --enable-asserts .../pkg/front_end/tool/_fasta/compile.dart --dump-ir -o /dev/null --enable-experiment=non-nullable --force-nnbd-checks /tmp/asdf.dart
/tmp/asdf.dart:7:3: Warning: Assigning value of type 'Null?' to a variable of type 'int'.
  i = null;
  ^
/tmp/asdf.dart:10:12: Warning: Assigning value of type 'Null?' to a variable of type 'int'.
  A().test(null);
           ^
library;
//
// Problems in library:
//
// /tmp/asdf.dart:7:3: Warning: Assigning value of type 'Null?' to a variable of type 'int'.
//   i = null;
//   ^
//
// /tmp/asdf.dart:10:12: Warning: Assigning value of type 'Null?' to a variable of type 'int'.
//   A().test(null);
//            ^
//
import self as self;
import "dart:core" as core;

class A extends core::Object {
  synthetic constructor •() → self::A
    : super core::Object::•()
    ;
  method test(core::int i) → void {
    core::print(i);
  }
}
static method main() → dynamic {
  core::int i;
  i = null;
  core::print(i);
  new self::A::•().{self::A::test}(1);
  new self::A::•().{self::A::test}(null);
}
```
</details>

**Comment by johnniwinther** [comment] 2020-01-13 12:33
Removing the front-end label as this should be considered a vm issue now.

**Comment by a-siva** [comment] 2020-02-06 00:31
@stefantsov Is the flag `--force-nnbd-checks` required to get these errors, because I checked and the VM does pass the `--enable-experiment=non-nullable flag `to the front end and it does not seem to report any errors.

**Comment by johnniwinther** [comment] 2020-02-06 07:17
NNBD specific warnings and errors still require the `--force-nnbd-checks`. We plan to remove this flag once VM and DDC can build the nnbd sdk cleanly with warnings/errors enabled.

**Comment by franklinyow** [comment] 2020-03-02 19:32
Is this still blocking unfork?  Can we move this under #40106 ?

**Comment by a-siva** [comment] 2020-03-02 21:20
Yes this is not blocking the unfork, I have moved into the Dart VM support for Null safe feature project.

**Comment by a-siva** [comment] 2020-03-11 22:51
This requires the --force-nnbd-checks  guard to be removed from the front end (please see issue https://github.com/dart-lang/sdk/issues/40980).
Closing as a duplicate of that issue.

**Closed by a-siva** 2020-03-11 22:51 UTC
Labels: NNBD, area-vm, closed-duplicate
