### ISSUE TITLE
Element mismatch in DeclarationResolver.resolve

### ISSUE THREAD

**Issue by rayk** [dart-lang/sdk#34519] opened 2018-09-20 06:45 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 183.2635.17`
- `2.1.0-dev.5.0`
- `WS-183.2635.17, JRE 1.8.0_152-release-1293-b10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 2560x1440, 1200x1920`

# Exception

Please append the contents of:
file:///private/var/folders/k3/rpf30xp576gd3b7wdpvvyg2r0000gn/T/report.txt

```
Dart analysis server, SDK version 2.1.0-dev.5.0, server version 1.20.5, error: Analysis failed: /Users/rayk/Projects/app/lib/src/services/identity_service.dart context: exception_20180920_164453_746
Element mismatch in /Users/rayk/Projects/app/lib/src/services/identity_service.dart at class IdentityService
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:62:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-23 04:13
Duplicate of #33930

**Closed by stereotype441** 2018-10-23 04:13 UTC
Labels: area-analyzer, type-bug
