### ISSUE TITLE
Null-dereference in analyzer

### ISSUE THREAD

**Issue by ihady** [dart-lang/sdk#37935] opened 2019-08-21 09:16 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.4.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1280x800  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, FATAL error: Failed to handle request: {id: 10, method: edit.getFixes, params: {file: /Users/HadyPro/AndroidStudioProjects/flutter_app1/lib/main.dart, offset: 0}, clientRequestTime: 1566378881485}
NoSuchMethodError: The getter 'declaredElement' was called on null.
Receiver: null
Tried calling: declaredElement
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AnalysisResult.typeProvider (package:analyzer/src/dart/analysis/driver.dart:2223:41)
#2      new FixProcessor (package:analysis_server/src/services/correction/fix_internal.dart:197:46)
#3      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:69:36)
<asynchronous suspension>
#4      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:649:46)
<asynchronous suspension>
#5      EditDomainHandler._computeServerErrorFixes (package:analysis_server/src/edit/edit_domain.dart:751:14)
<asynchronous suspension>
#6      EditDomainHandler.getFixes (package:analysis_server/src/edit/edit_domain.dart:278:32)
<asynchronous suspension>
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:381:9)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:321:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:317:50)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1500:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:316:5)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#50     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#51     _StreamController._add (dart:async/stream_controller.dart:640:7)
#52     _StreamController.add (dart:async/stream_controller.dart:586:5)
#53     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#54     _rootRunUnary (dart:async/zone.dart:1136:13)
#55     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zon...
```

For additional log information, please append the contents of
file:///private/var/folders/_v/fpp_ty153kq7d0nzsk572d9r0000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-03 07:30
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/36350; please follow along there.

**Comment by srawlins** [comment] 2019-09-03 07:30
Duplicate of https://github.com/dart-lang/sdk/issues/36350

**Closed by srawlins** 2019-09-03 07:30 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
