### ISSUE TITLE
Custom exceptions in other isolate are not caught in main isolat

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/sdk#47331] opened 2021-09-30 10:07 UTC
```
try {
  await compute(testForExceptions, '');
} on ApplicationException catch (error) {
  print("not here");
} catch (_) {
  print("here");
}

Future<void> testForExceptions(String test) async {
  throw const ApplicationException('test');
}

class ApplicationException {
  final String errorMessage;

  const ApplicationException(this.errorMessage);

  @override
  String toString() {
    return errorMessage.trim();
  }
}
```

Is it a bug that ApplicationException thrown in isolate is not caught by
```
try {
} on ApplicationException catch (_) {
}
```
in main isolate or it works as intended? 

Flutter version: 2.5.1 from stable channel

**Comment by lrhn** [comment] 2021-09-30 10:55
Duplicate of https://github.com/dart-lang/sdk/issues/47318
It's a Flutter `compute` issue, but not one which can easily be fixed until stack traces can be serialized.

**Closed by lrhn** 2021-09-30 10:55 UTC
