### ISSUE TITLE
Sporadic pthread error while running analysis server integration tests

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26880] opened 2016-07-13 20:06 UTC
Recently I have been seeing the following output from analysis server integration tests:

    9.017893958: ERR:  runtime/bin/thread_linux.cc: 208: error: pthread error: 16 (Device or resource busy)
    9.166931962: BAD DATA FROM SERVER: server terminated with exit code -6

(Note that the analysis server integration tests run an instance of the analysis server as a subprocess and collect stdout/stderr output from it.  The message above indicates that the integration test received the message `runtime/bin/thread_linux.cc: 208: error: pthread error: 16 (Device or resource busy)` from the subprocess after 9 seconds of execution, and then the subprocess exited with exit code -6.)

(Note that I found this problem using a 32-bit build.  I don't know whether it happens with a 64-bit build.)

To reproduce, run the following command:

    python tools/test.py -aia32 --checked -mrelease -t60 pkg/analysis_server/test/integration

Note that this runs 23 integration tests.  When I run this command on my Linux workstation, it only produces a failure about 40% of the time, and the failure does not always come from the same integration test.  So it seems that this is a fairly uncommon flaky behavior.

The failure started happening with the following commit: ed887c09d1d1b3c99bf56f6b9fc719808442c0be, which modified the analysis server to do vaidation of its cache consistency on a separate isolate.  However, I believe the root cause of the bug is not due to that commit, since that commit only affects Dart code (Dart code, even if it is buggy, should not cause the VM to crach).  Note that we may consider reverting that CL to restore analysis server reliability while this bug is being worked on.

**Comment by fsc8000** [comment] 2016-07-13 20:12
Duplicate of #26846.

**Closed by fsc8000** 2016-07-13 20:12 UTC
Labels: area-vm, Resolution: duplicate

**Comment by stereotype441** [comment] 2016-07-13 20:29
Confirmed that this is fixed by 63e3f4dc8b53cf2707412e473462988e2b8269b0.  Thanks!
