### ISSUE TITLE
Null checks are incorrectly optimized out for Flutter Border lerp function

### ISSUE THREAD

**Issue by ferhatb** [dart-lang/sdk#43366] opened 2020-09-09 17:40 UTC
Original customer issue: https://github.com/flutter/flutter/issues/63740

Code that reproduces problem:
https://gist.github.com/rydmike/2e8e6a4cc9126dbe6f95e81e674f6d6b

The following BoxBorder.lerp/Border.lerp function is compiled from:
```
static Border? lerp(Border? a, Border? b, double t) {
    assert(t != null);
    if (a == null && b == null)
      return null;
    if (a == null)
      return b!.scale(t);
    if (b == null)
      return a.scale(1.0 - t);
    return Border(
      top: BorderSide.lerp(a.top, b.top, t),
      right: BorderSide.lerp(a.right, b.right, t),
      bottom: BorderSide.lerp(a.bottom, b.bottom, t),
      left: BorderSide.lerp(a.left, b.left, t),
    );
  }

// The caller
 static BoxBorder? lerp(BoxBorder? a, BoxBorder? b, double t) {
    assert(t != null);
    if ((a is Border?) && (b is Border?))
      return Border.lerp(a, b, t);
.......
```
to:

```
Border_lerp: function(a, b, t) {
  ///!!!!! NO null checks
      return new F.Border(Y.BorderSide_lerp(a.top, b.top, t), Y.BorderSide_lerp(a.right, b.right, t), Y.BorderSide_lerp(a.bottom, b.bottom, t), Y.BorderSide_lerp(a.left, b.left, t));
    },


BoxBorder_lerp: function(a, b, t) {
      var t0, t2,
        t1 = type$.nullable_Border;
      if (t1._is(a) && t1._is(b))
        return F.Border_lerp(a, b, t);
      t1 = type$.nullable_BorderDirectional;
```

**Comment by rakudrama** [comment] 2020-09-09 18:52
It seems that global type analysis is incorrectly strengthening nullable type tests.
Smaller example:
```dart
String upcase(String? s) {
  if (s == null) return '';
  return s.toUpperCase();
}

String format(dynamic thing) {
  if (thing is String?) return upcase(thing);
  if (thing is num) return '$thing';
  return '?';
}

main() {
  print(format(null));
  print(format('hello'));
  print(format([]));
}
```

```js
  Z = {
    upcase: function(s) {
      return s.toUpperCase();
    },
    format: function(thing) {
      if (type$.nullable_String._is(thing))
        return Z.upcase(thing);
      return "?";
    },
```

**Comment by rydmike** [comment] 2020-09-09 19:58
Like I mentioned in https://github.com/flutter/flutter/issues/65358, I think it is possible that this issue is having an impact in more areas than what has yet been reported or fully detected with Flutter master/dev channel Web release builds. At least this particular case seems to be related: https://github.com/flutter/flutter/issues/64960.

I have also seen similar issues with other Flutter's implicit animated widgets (e.g. AnimatedSwitcher) and also with Animated theme, that all use a lot of lerps and the Themes + Sub themes that all depend on null for default values, so it is a possibility that this might be the cause of those issues as well. Pleased to see it is getting looked into. 

In current state I think it will break a lot more for Flutter Web Beta channel builds if this issue regresses into next beta release. I suspect I have just scratch the surface with these findings.

**Comment by pcsosinski** [comment] 2020-09-09 20:47
@franklinyow FYI this is likely a blocker for 2.10

**Comment by franklinyow** [comment] 2020-09-11 01:52
https://dart-review.googlesource.com/c/sdk/+/162247

**Comment by rakudrama** [comment] 2020-09-11 20:29
@franklinyow The fix has landed in the Dart sdk main branch.
@ferhatb which branches does this need to be back-ported into?

**Comment by ferhatb** [comment] 2020-09-14 15:57
The related NNBD code change in framework that surfaced this is box_border.dart which was updated Aug11.

**Comment by pcsosinski** [comment] 2020-09-14 16:01
the next branch is being coordinated today, we are going to probably cut it a day earlier than this landed.  adding the merge-to-beta tag and will coordinate with @athomas

**Comment by franklinyow** [comment] 2020-09-14 17:45
@rakudrama Please fill out cherrypick request form [link](https://github.com/dart-lang/sdk/issues/new?title=%5BCP%5D%5Bstable+channel%5D%20Please%20add%20descriptive%20title%20for%20the%20pick%20here%20&labels=merge-to-stable,cherry-pick-review&body=%2A%2Acommit%28s%29+to+merge%2A%2A%3A+COMMIT-HASH%0A%0A%2A%2Amerge+instructions%2A%2A%3A+clean+merge+or+patch+CL%0A%0A%2A%2AWhat%20is%20the%20issue%2A%2A%3A+Brief+description+of+the+problem%0A%0A%2A%2AWhat%20is%20the%20fix%2A%2A%3A+Brief+description+of+the+fix%0A%0A%2A%2AWhy%20cherrypick%2A%2A%3A+Describe+the+reasons,+like+many+users+impacted,+or+serious+functional+issues,+for+example%0A%0A%2A%2ARisk%2A%2A%3A%0A%0A%2A%2ALink%20to%20original%20+issue(s)%2A%2A%3A%0A%0A%2Fcc+%40kevmoo+%40mit-mit+%40whesse+%40athomas+%40vsmenon+%40franklinyow%0A%0A--------%0AThank+you+for+filing+a+cherrypick+request%2C+please%3A%0A++%2A+fill+in+the+data+above%0A++%2A+set+a+milestone,+and+area+label+%28e.g.+area-dart2js+for+a+dart2js+fix%29,+and+%E2%80%9Dmerge-to-stable%E2%80%9D+label+%0A++%2A+attempt+to+do+the+merge+%28%60git+checkout+origin%2Fstable%3B+git+cherry-pick+HASH%60%29+to+ensure+the+merge+instructions+are+accurate.%0A++%2A+delete+this+comment+and+examples+%3A%29%0A%0AEXAMPLE+1%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f+%28Should+match+the+hash+in+the+title.+It%27s+OK+to+have+more+than+one+commit%2C+but+please+explain.%29%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+merges+cleanly+in+%60origin%2Fstable%60%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+customers+unit+tests+that+use+mockito.%0A%0AEXAMPLE+2%3A%0A%3E+%2A%2Acommit+to+merge%2A%2A%3A+a7e511f%0A%3E%0A%3E+%2A%2Amerge+instructions%2A%2A%3A+patch+%5BCL%2Fxyz%5D%28link%29+%28merge+had+conflicts%2C+CL+resolves+them%29.%0A%3E%0A%3E+%2A%2Areason%2A%2A%3A+fixes+bug+with+nsm-forwarders+with+named+arguments.+Affects+%3E+customers+unit+tests+that+use+mockito.)

**Comment by franklinyow** [comment] 2020-09-14 18:32
@sigmundch for cherrypick request because Stephen maybe on vacation

**Comment by sigmundch** [comment] 2020-09-14 18:55
Thanks, filed under https://github.com/dart-lang/sdk/issues/43413

**Comment by franklinyow** [comment] 2020-09-14 21:45
Seems like it landed.  Anything else before we can close this?

**Closed** 2020-09-14 23:35 UTC
Labels: NNBD, P1, area-web, customer-flutter, merge-to-beta, type-bug, web-dart2js

**Comment by rydmike** [comment] 2020-09-15 01:47
Seems like the fix also landed in Flutter channel master. 

I just upgraded to latest Flutter master (Channel master, 1.22.0-10.0.pre.172) and rebuilt my two example cases in issues https://github.com/flutter/flutter/issues/63740 and https://github.com/flutter/flutter/issues/64960 where the first broken visual behavior impact in the Flutter framework due to this issue were detected.

I could no longer reproduce the observed behavior regression on implicit Flutter animations with the latest master on web release builds. This fix was observed to fix both above reported example issues and two other cases I did not bother to report, since I figured that even if their visual impacts were different, that their root cause was this same issue.
 
I'm making a note on the two Flutter issues that it they are solved by this and closing them. 

Thanks for this fix! 👍
