### ISSUE TITLE
appendHtml not work for table element with dart 1.11

### ISSUE THREAD

**Issue by jimmyshiau** [dart-lang/sdk#23737] opened 2015-06-29 04:11 UTC
```dart
Element t = new Element.html('<table></table>');
document.body.append(t);
t.appendHtml('<tr></tr>');//fail
t.appendHtml('<tr></tr>', treeSanitizer: const NullTreeSanitizer());//fail

Element row = t.createFragment('<table><tr></tr></table>').children[0];
t.append(row);// works
t.append(new TableRowElement());// works

TableElement t2 = new Element.html('<table><tbody></tbody></table>');
document.body.append(t2);
t2.tBodies[0].appendHtml('<tr></tr>');// fail
```

and I cannot create `tr` by
```dart
Element row = new Element.html('<tr></tr>');
or
Element Element cell = new Element.html('<tr><td></td></tr>');
```

**Comment by jimmyshiau** [comment] 2015-06-29 04:23
Does table element only allow add row by `table.insertRow(0);`?

http://stackoverflow.com/questions/14011361/add-table-rows-in-dart

**Comment by zoechi** [comment] 2015-06-30 14:24
What does "fail" mean exactly in these lines? 
```
t.appendHtml('<tr></tr>');//fail
t.appendHtml('<tr></tr>', treeSanitizer: const NullTreeSanitizer());//fail
```
Do you get an error message?

**Comment by jimmyshiau** [comment] 2015-07-01 01:41
No error message, but the `tr` element doesn't append to `table`.

**Comment by alan-knight** [comment] 2015-07-01 22:20
In Dart 1.11 there is an announced breaking change that appendHtml now uses sanitization by default, the same as innerHtml or other APIs that modify an element based on html text.

**Comment by tomyeh** [comment] 2015-07-02 02:47
@alan-knight I don't think it is about sanitization at all. It is about `appendHtml` can't create TR successfully -- no matter what `treeSanitizer` is.

On the other hand, there is no issue at all in JavaScript. For example, in jQuery, it is easy to add a row by using `$('#myTable').append('<tr>foo</tr>')`

In Dart, `document.querySelector('#myTable').appendHtml('<tr>foo</tr>', treeSanitizer: const NullTreeSanitizer())` **doesn't work** at all! (In fact, it worked before 1.11).

Sure, we can have a utility to work around (and we already did). However, as a framework, Dart is, IMO, better to make API more consistent and less surprise.

**Comment by alan-knight** [comment] 2015-07-07 17:56
OK, the issue is sanitization, but in particular a bug in the way it's doing it. Even with a null sanitizer, it's creating a document fragment and running the sanitizer over it. It's doing that by calling new DocumentFragment.html, rather than this.createFragment. So it is doing it with no context, so it uses the body context, and can't create <tr> because it's not doing it in the context of a table.

Note that In 1.12 there is also the ability to use NodeTreeSanitizer.trusted, which will avoid this step, which is also faster.

**Comment by alan-knight** [comment] 2015-07-07 20:57
https://codereview.chromium.org/1221043003

**Comment by tomyeh** [comment] 2015-07-08 02:12
Thanks.

**Comment by alan-knight** [comment] 2015-07-21 23:05
Trickier than I thought, but committed now.

**Closed by alan-knight** 2015-07-21 23:05 UTC
Labels: Area-Library, Library-Html
