### ISSUE TITLE
failure to recognize callable function if argument is complex

### ISSUE THREAD

**Issue by aoatmon** [dart-lang/sdk#47787] opened 2021-11-26 13:07 UTC
please look at the code below or on [gist](https://gist.github.com/aoatmon/183657e43106f18cfbbdec2d36c88e12)
(do not use `dartpad`!)

<details>
<summary>sample</summary>

```dart
import 'package:flutter/foundation.dart' show kReleaseMode, kDebugMode;
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';

typedef LogString = void Function(String);
typedef LogError = Future<void> Function(
  dynamic exception,
  StackTrace? stackTrace, {
  bool fatal,
  Iterable<DiagnosticsNode> information,
  bool? printDetails,
  dynamic reason,
});

mixin LoggerMixin {
  LogString get verbose;

  LogString get debug;

  LogString get information;

  LogString get warning;

  LogError get error;

  LogString get wtf;
}

/// ...

class DoNothing {
  const DoNothing();
  void call(String s) {}
}

class DoNothingError {
  const DoNothingError();
  Future<void> call(
    dynamic exception,
    StackTrace? stackTrace, {
    bool fatal = false,
    Iterable<DiagnosticsNode> information = const [],
    bool? printDetails = kDebugMode,
    dynamic reason,
  }) async {}
}

class Print {
  final String description;
  const Print(this.description);
  void call(String s) => debugPrint('$description: $s');
}

class PrintError {
  const PrintError();
  Future<void> call(
    dynamic exception,
    StackTrace? stackTrace, {
    bool fatal = false,
    Iterable<DiagnosticsNode> information = const [],
    bool? printDetails = kDebugMode,
    dynamic reason,
  }) async =>
      debugPrint('Error:\n'
          'exception=$exception\n'
          'stacktrace=$stackTrace\n'
          'fatal=$fatal\n'
          'information=$information\n'
          'printDetails=$printDetails\n'
          'reason=$reason\n');
}

class ProductionLogger with LoggerMixin {
  ProductionLogger();
  @override
  final debug = const DoNothing();
  // Debug level logging is disabled in production
  @override
  final information = const DoNothing();
  // Information level logging is disabled in production
  @override
  final verbose = const DoNothing();
  // Verbose level logging is disabled in production
  @override
  final warning = const DoNothing();
  // Warning level logging is disabled in production
  @override
  final wtf = const DoNothing();
  // WTF level logging is disabled in production
  @override
  final LogError error = kReleaseMode
      ? FirebaseCrashlytics.instance.recordError
      : const DoNothingError().call;
}

class QaLogger with LoggerMixin {
  QaLogger();
  @override
  final debug = const Print('Debug');
  @override
  final information = const Print('Information');
  @override
  final verbose = const Print('Verbose');
  @override
  final warning = const Print('Warning');
  @override
  final wtf = const Print('WTF');
  @override
  final error = kReleaseMode
      ? FirebaseCrashlytics.instance.recordError
      : const PrintError().call;
}

```

</details>

if you remove `call` from `const DoNothingError().call` or  `const PrintError().call`
I get the error
```
A value of type 'Object' can't be assigned to a variable of type 'Future<void> Function(dynamic, StackTrace?, {bool fatal, Iterable<DiagnosticsNode> information, bool? printDetails, dynamic reason})'.
Try changing the type of the variable, or casting the right-hand type to 'Future<void> Function(dynamic, StackTrace?, {bool fatal, Iterable<DiagnosticsNode> information, bool? printDetails, dynamic reason})'.
```
but this does not occur for `Print` and `DoNothing`

it would be nice if the behavior would be more consistent, possibly aligning at the latter
<details>
<summary>doctor</summary>

```bash
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-EE)
    • Flutter version 2.5.3 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>

**Comment by eernstg** [comment] 2021-11-26 17:53
Here is a minimal example:

```dart
class A {
  void call() {}
}

bool b = true;

void main() {
  // The error is eliminated if we change `A()` to `A().call`.
  Function f = b ? (){} : A(); // "A value of type 'Object' can't be assigned to a variable of type 'Function'."
}
```

**Comment by eernstg** [comment] 2021-11-26 18:04
The underlying discussion about how to propagate `.call` insertion into subexpressions (starting with cascades, but bringing in conditionals and other constructs along the way) is ongoing, with https://github.com/dart-lang/language/issues/1873 as a core issue.

I'll close this issue because it is a duplicate of https://github.com/dart-lang/language/issues/1873, and we won't change any tools to do anything in particular until we have resolved the discussion at the language level (so the right place to take this discussion is in the language repository).

**Closed by eernstg** 2021-11-26 18:04 UTC
