### ISSUE TITLE
Definite assignment failure

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#39482] opened 2019-11-21 17:31 UTC
In the logging package, in lib/logging.dart lines 166-172 are migrated as
```
      String? msg;
      if (message is String) {
        msg = message;
      } else {
        msg = message.toString();
        object = message;
      }
```
Definite assignment should have been able to figure out that `msg` is always being assigned a non-null value and therefore does not need to make it nullable.

**Comment by stereotype441** [comment] 2019-11-21 18:11
After further analysis it turns out this is not a problem with definite assignment analysis per se, because `message` is a field.  So according to the strict rules of definite assignment analysis, the test `if (message is String)` does *not* promote `message` to non-nullable (because for all we know, `message` might be overridden by a getter that doesn't return the same value each time).  Therefore, as far as definite assignment analysis knows, the statement `msg = message;` might assign a nullable value to `msg`.

Of course, what we really want the migration engine to do here is recognize that after `if (message is String)`, the user has a reasonable expectation that `message` is non-nullable, and therefore we shouldn't use `msg = message;` as evidence that `msg` should be marked as nullable.  What we should do instead is migrate the code like so:

```dart
String msg;
if (message is String) {
  msg = message!;
} else {
  msg = message.toString();
  object = message;
}
```
...which is the subject of https://github.com/dart-lang/sdk/issues/38470, so I'm marking this bug as a duplicate of that one.

**Closed by stereotype441** 2019-11-21 18:11 UTC
Labels: area-analyzer, nnbd-migration-correctness-example

**Comment by stereotype441** [comment] 2019-11-21 18:13
Duplicate of #38470
