### ISSUE TITLE
Stack traces in precompilation mode do not show frames in case of inlining

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#26921] opened 2016-07-20 10:44 UTC
It seems that stack traces in precompilation mode do not show frames for functions which have been inlined.

This example:

```
bar() => throw 'throw in bar()';
foo() => bar();
main() => foo();
```

Will produce with the precompiler:

```
Unhandled exception:
throw in bar()
#0      bar (inlining_stack_test.dart)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart)
```

`main` and `foo` have probably been inlined. 

This is probably a known limitation, but it might make sense to have a bug to track it (in case we plan on fixing it at some point).

/cc @fsc8000 @rmacnak-google @mraleph

**Comment by fsc8000** [comment] 2016-07-20 16:23
Yes, we decided to drop information about inlined frames to make snapshots smaller. We could consider it non-product mode only.

**Comment by fsc8000** [comment] 2017-02-02 22:38
Duplicate of #24783.

**Closed by fsc8000** 2017-02-02 22:38 UTC
Labels: area-vm, Type: enhancement
