### ISSUE TITLE
Confused about conflicting_instance_getter_and_superclass_member

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#32968] opened 2018-04-25 03:04 UTC
[Edit Apr 27 2018 eernstg: This issue is now a request for implementation of #31201 on the analyzer, i.e., it should no more issue a diagnostic message when a class _C_ declares a setter/getter named _n_ and an accessible static member named _n_ is declared in a superclass of _C_.]

---

Apologies if this is pre-logged somewhere or I am missing something very trivial.

/cc @eernstg and @leafpetersen 

```dart
abstract class A {
  static A instance;
}

class APrime extends A {
  // ERROR: Superclass 'A' declares static member with the same name.
  // conflicting_instance_getter_and_superclass_member
  APrime get instance => null;
}
```

I don't understand this restriction. I would _sort of_ understand if if static members were inherited (or there were plans for this, but it wasn't yet implemented) but as far as I can tell that is neither the case now nor was it ever (i.e. https://github.com/dart-lang/sdk/issues/5320).

The problem I'm running into here is AngularDart now allows static-level fields to define how a DOM element should be decorated at time of being built. For example, here is a declarative way of saying to build the following DOM element:

```html
<user-component role="list"></user-component>
```

```dart
import 'package:angular/angular.dart';

@Component(
  selector: 'user-component',
  template: '',
)
class UserComponent {
  @HostBinding('role')
  static const hostRole = 'list';
}
```

The problem we are running into is someone could write the following:

```dart
abstract class SomeBase {
  static const hostRole = 'blah';
}
```

... and this now fails at compile-time:

```dart
class UserComponent extends SomeInterface {
  @HostBinding('role')
  String get hostRole => 'list';
}
```

.... I can't figure out _why_ we prevent this, though.

**Comment by matanlurey** [comment] 2018-04-25 03:42
Further complicating this for me, is that `factory` method seem fine:

```dart
class A {
  factory A.fromJson() => null;
}

class B implements A {
  factory B.fromJson() => null;
}
```

... which, with optional new, means this works, but `static A fromJson` doesn't. For some reason.

**Comment by matanlurey** [comment] 2018-04-25 03:50
**EDIT**: I made some mistakes in my examples. It is all updated now.

**Comment by leafpetersen** [comment] 2018-04-25 18:29
The second example doesn't reproduce, `implements` seems to work.  The first example emits an error on the analyzer but not on the CFE.

For the first example (with `extends`), it seems to me this should be allowed.  We explicitly allowed this for instance methods here: https://github.com/dart-lang/sdk/issues/31165 , and I don't immediately see why we would not want to allow it for other kinds of members.  And my read of the spec update that closed that bug is that this isn't disallowed.  @eernstg @lrhn is this just an analyzer bug, or is it WAI, or do we need another spec fix?

**Comment by matanlurey** [comment] 2018-04-25 19:19
Ah apologies @leafpetersen I meant to say `extends` not `implements`. Updated.

**Comment by eernstg** [comment] 2018-04-26 10:46
This error was never very clearly motivated, and it has been removed from the language specification as of 1c4358d459c75a429dceae61ef8e948e43b8378c.

Issue #31201 is concerned with the implementation of that change. It's not obvious to me where you've noticed that it isn't yet implemented, but #31201 refers to sub-issues for the analyzer and for dart2js. Maybe we ought to add a sub-issue for the CFE?

**Comment by leafpetersen** [comment] 2018-04-26 14:45
@eernstg This is with the analyzer.  The fix was made for instance *methods*, but it looks like not for other kinds of instance members (getters, setters).  I think that we intended to apply the fix to all instance members, but wanted to verify that I wasn't missing something.

**Comment by matanlurey** [comment] 2018-04-26 16:45
Just to clarify so this doesn't get lost, is there action items here?

(I also realize this could be done in Dart 2.1 cleanly, so not a P0/P1)

**Comment by eernstg** [comment] 2018-04-27 13:25
The original action item would still apply:
```
> dartanalyzer --version
dartanalyzer version 2.0.0-dev.50.0
> dartanalyzer --preview-dart-2 n000.dart
Analyzing n000.dart...
  error • Superclass 'A' declares static member with the same name at n000.dart:10:14 • conflicting_instance_getter_and_superclass_member
1 error found.
```
Namely: The analyzer claims conflicting_instance_getter_and_superclass_member for
```dart
// Initial example from this issue, plus `main`.

abstract class A {
  static A instance;
}

class APrime extends A {
  // ERROR: Superclass 'A' declares static member with the same name.
  // conflicting_instance_getter_and_superclass_member
  APrime get instance => null;
}

main() => new APrime();
```
and there is no such conflict according to the language specification today, not for methods, not for getters, and not for setters. Issue #31351 seems to have been closed in response to an update regarding methods (which matches the title, but not the text in the associated meta issue #31201: 'The change is to delete this sentence and similar ones for setters and getters, and adjust tools and tests accordingly'), so we could reopen #31351 and request a fix for getters and setters, or we could decide that this issue is concerned with the fix for getters and setters.

I don't care which one we choose, but it seems appropriate to have exactly one open issue on this task until it's done.

So, just to take one step forward I'll adjust the label on this issue to say that it is area-analyzer, and I'll add a note at the top saying what the task is.

By the way, checking `dart --preview-dart-2` there is no error, so (apparently) there is no need to file a similar issue for the CFE.

**Comment by matanlurey** [comment] 2018-08-08 17:58
Is there a hotlist for issues that are present in the analyzer but not CFE? /cc @devoncarew

**Comment by devoncarew** [comment] 2018-08-10 20:10
No, no bug list for that as such. The best point of comparison would likely be the language_2 status files:

https://github.com/dart-lang/sdk/blob/master/tests/language_2/language_2_analyzer.status
https://github.com/dart-lang/sdk/blob/master/tests/language_2/language_2_kernel.status

The more severe issues we've tracked on the release milestones - https://github.com/dart-lang/sdk/milestone/57 and such.

**Comment by srawlins** [comment] 2023-04-16 23:31
This is now fixed. Analyzer reports nothing on the example, updated for Dart 3:

```dart
abstract class A {
  external static A instance;
}

abstract class APrime extends A {
  APrime get instance;
}
```

**Closed by srawlins** 2023-04-16 23:31 UTC
Labels: area-analyzer, P2, type-bug, analyzer-spec
