### ISSUE TITLE
ReachabilityError in switch with nullable Enum in weak mode

### ISSUE THREAD

**Issue by blaugold** [dart-lang/sdk#49697] opened 2022-08-18 17:03 UTC
The following code throws an error only when executed with `--no-sound-null-safety`:

```dart
enum A { a, b }

int? a(A? a) {
  switch (a) {
    case A.a:
      return 0;
  }
}

int? b(A? a) {
  switch (a) {
    case null:
      return null;
    case A.a:
      return 0;
  }
}

void main() {
  a(A.b);
  b(A.b);
}
```

```
Unhandled exception:
ReachabilityError: `null` encountered as case in a switch expression with a non-nullable enum type.
#0      b (file:///Users/gabriel/Dev/dart/sdk/debug.dart:11:3)
#1      main (file:///Users/gabriel/Dev/dart/sdk/debug.dart:21:3)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Maybe I'm missing something, but isn't the parameter `a` of the function `b` nullable and therefore the switch expression also nullable?

**Comment by aam** [comment] 2022-08-18 21:51
duplicate of https://github.com/dart-lang/sdk/issues/35065

**Comment by blaugold** [comment] 2022-08-18 22:16
Is this really the same issue? This [comment](https://github.com/dart-lang/sdk/issues/35065#issuecomment-720792968) says that with null-safety, it "allows `case null` if the value's type is nullable." The code above is opted into null-safety. But it behaves differently when executed with non-sound null-safety.

When I change `main` to this:

```dart
void main() {
  a(A.b);
  b(null);
}
```

no exception is thrown and `b` returns `null`. 

The issue is that when `b` is passed an enum value for which there is no case, a `ReachabilityError` is thrown instead of continuing after the switch statement.

**Comment by aam** [comment] 2022-08-18 22:31
For the original program I believe value type is inferred as non-nullable, therefore `case null` is flagged.

Changing `main` to
```
void main(List<String> args) {
  a(A.b);
  b(args.length > 0 ? A.b: null);
}
```
(forcing value type become nullable) results in no errors.

**Comment by blaugold** [comment] 2022-08-18 22:45
I'm not sure that I follow. Running `dart --no-sound-null-safety main.dart foo` with the code you suggested causes the mentioned error. Analysis of the switch value type is [static](https://github.com/dart-lang/sdk/issues/35065#issuecomment-720792968), so I don't see how the argument at the call site could make a difference.

**Comment by aam** [comment] 2022-08-18 23:10
Oh, yeah. I see it looks like compiler inserts a `default:` case branch for the switch.

```
  static method b([@vm.inferred-type.metadata=library file:///usr/local/google/home/aam/p/d/dart-sdk/sdk/enum-null.dart::A?] enu::A? a) → core::int? {
    switch(a) /*isExplicitlyExhaustive*/ {
      #L2:
      case #C7:
        {
          return null;
        }
      #L3:
      case #C6:
        {
          return 0;
        }
      #L4:
      default:
        throw new _in::ReachabilityError::•("`null` encountered as case in a switch expression with a non-nullable enum type.");
    }
  }
```
cc @johnniwinther who might comment on the reasons(based https://github.com/dart-lang/sdk/blob/main/pkg/front_end/lib/src/fasta/type_inference/inference_visitor.dart#L6490)

**Comment by johnniwinther** [comment] 2022-08-19 05:20
The throwing default should only be inserted when the switch is exhaustive (to catch `null` in unsound mode), but in this case the switch _isn't_ exhaustive, lacking a case for `A.b`, so there seems to be an error in the computation of exhaustiveness.

**Closed** 2022-08-22 05:45 UTC
Labels: P2, area-front-end
