### ISSUE TITLE
Can not detect dart file

### ISSUE THREAD

**Issue by ChauNTM** [dart-lang/sdk#39382] opened 2019-11-14 05:53 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080, 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: /Users/cmnguyen/Documents/aria/aria/test_driver/app.dart context: exception_20191114_125150_766
Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:230:22)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:385:18)
#2      ExprBuilder._pushLocalFunctionReference (package:analyzer/src/summary/expr_builder.dart:938:12)
#3      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:277:11)
#4      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2546:29)
#5      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5387:36)
#6      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5230:7)
#7      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#9      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5666:47)
#10     FunctionElementForLink_Initializer.returnType (package:analyzer/src/summary/link.dart:2897:24)
#11     InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:444:33)
#12     InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:312:11)
#13     InstanceMemberInferrer._inferClasses (package:analyzer/src/task/strong_mode.dart:335:9)
#14     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:56:5)
#15     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:7)
#16     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3870:12)
#17     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3570:15)
#18     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3510:7)
#19     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2226:13)
#20     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#21     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#23     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#24     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#25     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2192:24)
#26     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2245:18)
#27     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3543:42)
#28     Linker.link (package:analyzer/src/summary/link.dart:4075:35)
#29     _relink (package:analyzer/src/summary/link.dart:312:74)
#30     link (package:analyzer/src/summary/link.dart:126:3)
#31     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#32     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#33     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#34     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1444:23)
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1245:30)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#39     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#40     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#41     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#42     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#43     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#44     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#50     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#52     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#53     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#54     CompilerContext.runInContext.<anonymous c...
```

For additional log information, please append the contents of
file:///private/var/folders/wh/__fdj76d0qj1zbrrm71q5zpc0000gn/T/report1.txt.

**Comment by srawlins** [comment] 2019-12-24 05:00
Thanks for reporting this issue! This was previously found in fuzz testing, in https://github.com/dart-lang/sdk/issues/38084; please follow along there.

**Comment by srawlins** [comment] 2019-12-24 05:00
Duplicate of https://github.com/dart-lang/sdk/issues/38084

**Closed by srawlins** 2019-12-24 05:00 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
