### ISSUE TITLE
Meta issue for speed of coverage for Flutter

### ISSUE THREAD

**Issue by dgrove** [dart-lang/sdk#32562] opened 2018-03-17 15:12 UTC
The root cause for https://github.com/flutter/flutter/pull/15635 should be addressed.

**Comment by mkustermann** [comment] 2018-03-19 11:58
Slava asked me to take a look at this, so I'll self-assign.

**Comment by mkustermann** [comment] 2018-03-26 08:41
To give an update on this. The change in 521846c832e2788da6750f0e84946303c47b4009 should have gotten rid of most of the performance regression when generating coverage reports. 

Though v2 is still slower than v1. The reason why this happens is due to the very different way we find all token positions in a script: Instead of simply tokenizing the script - as we do in v1 - the v2 version:
  * has a O(n^2) algorithm for finding all classes/functions/fields which correspond to a script by scanning whole-program datastructures
  * is doing abstract interpretation over bodies to collect token positions
Changing how this is done would probably require a redesign.

**Comment by mkustermann** [comment] 2018-03-26 09:17
@aam @JekCharlsonYu I've made https://github.com/flutter/flutter/pull/15932 for flutter to enable the coverage collection in dart-2 mode again. If that lands successfully we can either close this issue - or remove the beta milestone, since it shouldn't block anything anymore.

**Comment by dgrove** [comment] 2018-04-05 03:57
@mkustermann Any updates on landing flutter/flutter#15932 ?

**Comment by mkustermann** [comment] 2018-04-05 09:03
Thanks for the ping, I've merged the change now!

**Closed** 2018-04-05 09:03 UTC
Labels: Flutter-Beta, area-vm
