### ISSUE TITLE
Could not start worker thread

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#26018] opened 2016-03-17 00:44 UTC
1. Checkout revision 74c609c265ce6399e9619e11bae02c62eae9e911 of the sdk and build it.
2. Copy the attached file to `sdk/pkg/analyzer/test/performance` (renaming it to '.dart').
3. Run the command

    /Users/brianwilkerson/Dev/dart/dart-sdk/bin/dart --ignore-unrecognized-flags --pause_isolates_on_exit --checked --enable-vm-service:53213 --trace_service_pause_events /Users/brianwilkerson/src/dart/sdk/sdk/pkg/analyzer/test/performance/time_build_scopes.dart

I get the following output:
    Observatory listening on http://127.0.0.1:53213
    Analyzing 8922 files
    Exhausted heap space, trying to allocate 549760 bytes.
    /Users/brianwilkerson/src/dart/sdk/sdk/runtime/vm/thread_pool.cc:346: error: Could not start worker thread: result = 35.

    Process finished with exit code 134

[time_build_scopes.txt](https://github.com/dart-lang/sdk/files/177100/time_build_scopes.txt)

**Comment by zanderso** [comment] 2016-03-18 16:48
I followed these instructions, and could not reproduce on my desktop Linux machine. The program uses up to 7GB of memory, though. Error 35 from pthread_create() is EAGAIN meaning "Insufficient  resources to create another thread". It looks like what happened in your run is that memory was exhausted. Following that, the ways in which the VM will fail to make progress aren't entirely predictable, especially in the presence of multiple threads/isolates. I don't think there's a whole lot we can do better here, so I'm going to go ahead and close this out.

**Closed by zanderso** 2016-03-18 16:48 UTC
Labels: area-vm

**Comment by bwilkerson** [comment] 2016-03-18 17:29
In case it matters, this was running on my MacBook Pro.

**Comment by iposva-google** [comment] 2016-03-18 23:41
@zanderso, I am pretty certain @bwilkerson ran with a ia32 (as in similar related recent bug reports) build so that would explain why he ran out of address space. Brian, can you please confirm?

**Comment by bwilkerson** [comment] 2016-03-19 00:02
Yes:

    $ dart --version
    Dart VM version: 1.16.0-edge.ceec063f27b6bde552cf22193aa2ba4e3d310c15 (Thu Mar 17 14:51:59 2016) on "macos_ia32"

Is there anything I can do to work around this? Having the VM crash on me is making it difficult for me to improve the performance of analyzer.

**Comment by iposva-google** [comment] 2016-03-19 00:08
At this point you have essentially two options: Run a x64 build or use less memory in the analyzer.

**Comment by bubnenkoff** [comment] 2022-06-08 07:35
```
../../runtime/vm/thread_pool.cc: 315: error: Could not start worker thread: result = 22.
version=2.17.0-112.0.dev (dev) (Tue Feb 15 21:18:47 2022 -0800) on "windows_x64"
pid=2080, thread=13136, isolate_group=main(000000CBD6121950), isolate=(nil)(0000000000000000)
isolate_instructions=7ff6ed1d5760, vm_instructions=7ff6ed1d5770
  pc 0x00007ff6ed3dfdd2 fp 0x000000cbebc1e5e0 Unknown symbol
-- End of DumpStackTrace
  pc 0x0000000000000000 fp 0x000000cbebc1ed00 sp 0x0000000000000000 [Stub] CallToRuntime
  pc 0x000000cbd6181c5d fp 0x000000cbebc1ed38 sp 0x000000cbebc1ed10 [Stub] AllocateClosure
  pc 0x000000cbe502389e fp 0x000000cbebc1ee20 sp 0x000000cbebc1ed48 [Optimized] Query.sendExtended
  pc 0x000000cbe502e5ae fp 0x000000cbebc1eea8 sp 0x000000cbebc1ee30 [Optimized] _PostgreSQLConnectionStateIdle@280299794.processQuery
  pc 0x000000cbe502b871 fp 0x000000cbebc1f020 sp 0x000000cbebc1eeb8 [Optimized] _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin@280299794._enqueue@280299794
  pc 0x000000cbe502ed51 fp 0x000000cbebc1f078 sp 0x000000cbebc1f030 [Optimized] _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin@280299794._enqueue@280299794
  pc 0x000000cbe5026e76 fp 0x000000cbebc1f198 sp 0x000000cbebc1f088 [Optimized] _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin@280299794._query@280299794
  pc 0x000000cbe503054c fp 0x000000cbebc1f1f0 sp 0x000000cbebc1f1a8 [Optimized] _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin@280299794._query@280299794
  pc 0x000000cbe502d677 fp 0x000000cbebc1f300 sp 0x000000cbebc1f200 [Optimized] saveArchivesToDB
  pc 0x000000cbe5014e9d fp 0x000000cbebc1f358 sp 0x000000cbebc1f310 [Optimized] _FutureListener@4048458.handleValue
  pc 0x000000cbe5018c26 fp 0x000000cbebc1f3d0 sp 0x000000cbebc1f368 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000cbe5013938 fp 0x000000cbebc1f438 sp 0x000000cbebc1f3e0 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000cbe5029824 fp 0x000000cbebc1f480 sp 0x000000cbebc1f448 [Optimized] _completeWithNoFutureOnAsyncReturn@4048458
  pc 0x000000cbe5027141 fp 0x000000cbebc1f598 sp 0x000000cbebc1f490 [Optimized] _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin@280299794._query@280299794
  pc 0x000000cbe5014e9d fp 0x000000cbebc1f5f0 sp 0x000000cbebc1f5a8 [Optimized] _FutureListener@4048458.handleValue
  pc 0x000000cbe5018c26 fp 0x000000cbebc1f668 sp 0x000000cbebc1f600 [Optimized] _Future@4048458._propagateToListeners@4048458.handleValueCallback
  pc 0x000000cbe5013938 fp 0x000000cbebc1f6d0 sp 0x000000cbebc1f678 [Optimized] _Future@4048458._propagateToListeners@4048458
  pc 0x000000cbe5031301 fp 0x000000cbebc1f720 sp 0x000000cbebc1f6e0 [Optimized] _Future@4048458._asyncCompleteWithValue@4048458.<anonymous closure>
  pc 0x000000cbe5031ae6 fp 0x000000cbebc1f788 sp 0x000000cbebc1f730 [Optimized] _startMicrotaskLoop@4048458
  pc 0x000000cbe5028be3 fp 0x000000cbebc1f7b0 sp 0x000000cbebc1f798 [Optimized] _startMicrotaskLoop@4048458
  pc 0x000000cbe501c87e fp 0x000000cbebc1f7f0 sp 0x000000cbebc1f7c0 [Optimized] _RawReceivePortImpl@1026248._handleMessage@1026248
  pc 0x000000cbd6182668 fp 0x000000cbebc1f918 sp 0x000000cbebc1f800 [Stub] InvokeDartCode
```
