### ISSUE TITLE
Devtools benchmarks fail with dart2wasm on highest optimization level

### ISSUE THREAD

**Issue by eyebrowsoffire** [dart-lang/sdk#56664] opened 2024-09-06 21:32 UTC
The devtools benchmarks run with the newest version of flutter causes dart2wasm to emit code that results in a typecasting failure, but only at the highest optimization levels.

Steps to Reproduce:
* Check out @kenzieschmoll 's branch here: https://github.com/flutter/devtools/pull/8306
* Change to the `packages/devtools_app` directory
* Run the following script: `dart ./benchmark/devtools_benchmarks_test.dart`

Results:
Tests output the following exception:
```
  Caught browser-side error: Type '(minified:Class2107) => minified:Class4570<void>' is not a subtype of type '(Object) => minified:Class4570<void>' in type cast
      at _TypeError._throwAsCheckError (http://localhost:9999/main.dart.wasm:wasm-function[1117]:0x1aa4a2)
      at _RouterState.restoreState closure at file:///home/runner/work/devtools/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:623:72 (http://localhost:9999/main.dart.wasm:wasm-function[33056]:0x4ade86)
      at closure wrapper at file:///home/runner/work/devtools/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:623:72 trampoline (http://localhost:9999/main.dart.wasm:wasm-function[33060]:0x4adeb4)
      at _RouterState._processParsedRouteInformation closure at file:///home/runner/work/devtools/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:759:12 inner (http://localhost:9999/main.dart.wasm:wasm-function[32757]:0x4a80cf)
      at _RouterState._processParsedRouteInformation closure at file:///home/runner/work/devtools/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:759:12 (http://localhost:9999/main.dart.wasm:wasm-function[32754]:0x4a7fce)
      at closure wrapper at file:///home/runner/work/devtools/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:759:12 trampoline (http://localhost:9999/main.dart.wasm:wasm-function[32756]:0x4a7ff8)
      at _rootRunUnary (http://localhost:9999/main.dart.wasm:wasm-function[1550]:0x1bfa56)
      at _CustomZone.runUnary (http://localhost:9999/main.dart.wasm:wasm-function[33328]:0x4b5988)
```

This only appears to occur at the full optimization level. Changing the web benchmarking code to compile at `-O1`, `-O1` or `-O2` does not emit this error. Unfortunately, it's difficult to tell what exactly is being cast due to the minified types.

**Comment by mkustermann** [comment] 2024-09-09 14:11
I can confirm that this is happening iff `--omit-implicit-type-checks` is enabled.

The error being thrown looks like this:
```
Caught browser-side error:
   Type
       '(DevToolsRouteConfiguration) => Future<void>' is not a subtype of type
       '(Object) => Future<void>'
   in type cast
```

The code looks like this:
```dart

  @override
  void restoreState(RestorationBucket? oldBucket, bool initialRestore) {
    registerForRestoration(_routeInformation, 'route');
    if (_routeInformation.value != null) {
      assert(widget.routeInformationParser != null);
      _processRouteInformation(_routeInformation.value!, () => widget.routerDelegate.setRestoredRoutePath);
    } else if (widget.routeInformationProvider != null) {
      _processRouteInformation(widget.routeInformationProvider!.value, () => widget.routerDelegate.setInitialRoutePath);
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    }
  }
```
The inner closure returns a function. That function is a tear-off of `RouterDelegate<T>.setInitialRoutePath`.

The `widget.routerDelegate` is a `DevToolsRouterDelegate`:
```dart
class DevToolsRouterDelegate extends RouterDelegate<DevToolsRouteConfiguration> ... {
  ...
}
abstract class RouterDelegate<T> extends Listenable {
  Future<void> setInitialRoutePath(T configuration) { ...  }
  ...
}
```

=> So at runtime this `widget.routerDelegate.setInitialRoutePath` will be `(DevToolsRouteConfiguration) -> Future<void>`

So the closure we give to `_processRouteInformation`s 2nd argument is `() -> ((DevToolsRouteConfiguration) -> Future<void>)`.

That function looks like this:
```dart
class _RouterState<T> 
  void _processRouteInformation(RouteInformation information, ValueGetter<_RouteSetter<T>> delegateRouteSetter) {
    ....
  }
}
typedef ValueGetter<T> = T Function();
typedef _RouteSetter<T> = Future<void> Function(T);

```

=> We seemingly have `T == Object`
=> We expect `ValueGetter<_RouteSetter<T>>`
=> We expect `ValueGetter<_RouteSetter<Object>>`
=> We expect `ValueGetter<Future<void> Function(Object)>`
=> We expect `Future<void> Function(Object) Function()`

So we're trying to assign `() -> ((DevToolsRouteConfiguration) -> Future<void>` where `() -> ((Object) -> Future<void>)` is expected.

Not quite clear yet why this happens precisely iff `--omit-implicit-checks` is enabled.

**Comment by mkustermann** [comment] 2024-09-09 19:07
Turns out that because the tear-off is of a method with covariant parameters the parameter of the closure should be `Object`. Though in `--omit-implicit-checks` it was rather `DevToolsRouteConfiguration`.

=> [cl/384285](https://dart-review.googlesource.com/c/sdk/+/384285)

**Comment by kenzieschmoll** [comment] 2024-09-11 17:57
I am still seeing this issue even with the attempted fix (which was first included in Dart 3.6.0-235.0.dev - see [commit](https://github.com/dart-lang/sdk/commit/7ebc3f7f31025c838478b510fb85cacbb3deebd3)).
```
Flutter 3.26.0-1.0.pre.76 • channel [user-branch] • unknown source
Framework • revision 9108b6d0cf (9 hours ago) • 2024-09-11 05:11:17 -0400
Engine • revision 0a14c519ea
Tools • Dart 3.6.0 (build 3.6.0-238.0.dev) • DevTools 2.39.0
```

Repro steps:
1) patch https://github.com/flutter/devtools/pull/8270/
2) run `devtools_tool serve --wasm --no-strip-wasm`

Exception:
```
Type '(minified:Class2376) => minified:Class4651<void>' is not a subtype of type '(Object) => minified:Class4651<void>' in type cast
main.dart.mjs:69     at _TypeError._throwAsCheckError (http://127.0.0.1:9103/main.dart.wasm:wasm-function[1106]:0x1b3fb0)
    at _RouterState.restoreState closure at file:///Users/kenzieschmoll/develop/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:623:72 (http://127.0.0.1:9103/main.dart.wasm:wasm-function[13887]:0x2e9b21)
    at closure wrapper at file:///Users/kenzieschmoll/develop/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:623:72 trampoline (http://127.0.0.1:9103/main.dart.wasm:wasm-function[13891]:0x2e9b4c)
    at _RouterState._processParsedRouteInformation closure at file:///Users/kenzieschmoll/develop/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:759:12 inner (http://127.0.0.1:9103/main.dart.wasm:wasm-function[13880]:0x2e96b5)
    at _RouterState._processParsedRouteInformation closure at file:///Users/kenzieschmoll/develop/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:759:12 (http://127.0.0.1:9103/main.dart.wasm:wasm-function[13877]:0x2e95b7)
    at closure wrapper at file:///Users/kenzieschmoll/develop/devtools/tool/flutter-sdk/packages/flutter/lib/src/widgets/router.dart:759:12 trampoline (http://127.0.0.1:9103/main.dart.wasm:wasm-function[13879]:0x2e95df)
    at _rootRunUnary (http://127.0.0.1:9103/main.dart.wasm:wasm-function[1539]:0x1c99ac)
    at _CustomZone.runUnary (http://127.0.0.1:9103/main.dart.wasm:wasm-function[34744]:0x4e3593)
```

**Comment by mkustermann** [comment] 2024-09-11 19:05
From my testing it seems very clear that this error occurs with 
```
% <flutter> g reset --hard '2fb154f8203cbb021003b9cd9bf7661e8de6d473^'
```
but no longer with
```
% <flutter> g reset --hard '2fb154f8203cbb021003b9cd9bf7661e8de6d473'
```

@kenzieschmoll Are you sure you're on the right flutter/flutter commits? Have you run `flutter clean & flutter packages get` afterwords?

**Comment by kenzieschmoll** [comment] 2024-09-11 19:18
When you run `devtools_tool serve --wasm --no-strip-wasm`, do you see the error? I ran `flutter clean` and `flutter packages get` and I still see the error when I build and serve DevTools with wasm.
```
Flutter 3.26.0-1.0.pre.76 • channel [user-branch] • unknown source
Framework • revision 9108b6d0cf (10 hours ago) • 2024-09-11 05:11:17 -0400
Engine • revision 0a14c519ea
Tools • Dart 3.6.0 (build 3.6.0-238.0.dev) • DevTools 2.39.0
```

You no longer need to patch any code locally, just pull the latest from the Devtools master branch and run the serve command above. When Devtools loads in the browser, be sure to do a hard refresh (just clicking in the URL and hitting enter) to ensure that the browser is not caching an old version of DevTools.

**Comment by mkustermann** [comment] 2024-09-11 19:32
> You no longer need to patch any code locally, just pull the latest from the Devtools master branch and run the serve command above. When Devtools loads in the browser, be sure to do a hard refresh (just clicking in the URL and hitting enter) to ensure that the browser is not caching an old version of DevTools.

I still used the original instructions to reproduce (and cannot reproduce anymore after the rolled fix).

Will try with new instructions from https://github.com/dart-lang/sdk/issues/56664#issuecomment-2344333628 and report back.

**Comment by mkustermann** [comment] 2024-09-11 20:09
> When you run devtools_tool serve --wasm --no-strip-wasm, do you see the error? I ran flutter clean and flutter packages get and I still see the error when I build and serve DevTools with wasm.

So the instructions would be
```
% git clone https://github.com/flutter/devtools; cd devtools
devtools % export LOCAL_DART_SDK=<path-to-real-dart-lang/sdk-gclient-checkout>
devtools % tool/bin/devtools_tool serve --wasm --no-strip-wasm
...
```

If I follow these instructions it seems to only serve dart2js (i.e. `main.dart.js`)

**Comment by kenzieschmoll** [comment] 2024-09-11 21:02
Are you on the tip of flutter/devtools master and the tip of the Dart SDK? there was a commit to each that landed this morning that you would need.

**Comment by kenzieschmoll** [comment] 2024-09-11 23:10
One potential difference between running `devtools serve --wasm --no-strip-wasm` and running the benchmark tests is that the former builds DevTools [in release mode](https://github.com/flutter/devtools/blob/master/tool/lib/commands/build.dart/#L112) by [default](https://github.com/flutter/devtools/blob/master/tool/lib/commands/shared.dart/#L19), and web_benchmarks builds Devtools [in profile mode](https://github.com/flutter/packages/blob/main/packages/web_benchmarks/lib/src/runner.dart#L127).

**Comment by mkustermann** [comment] 2024-09-12 10:25
> Are you on the tip of flutter/devtools master and the tip of the Dart SDK? there was a commit to each that landed this morning that you would need.

Yes.

> If I follow these instructions it seems to only serve dart2js (i.e. main.dart.js)

After debugging the JS a bit it turns out the [packages/devtools_app/web/flutter_bootstrap.js](https://github.com/flutter/devtools/blob/2b3bed912146c800ac7b8ec34a5ea4ae1bb6dcf6/packages/devtools_app/web/flutter_bootstrap.js#L51)'s `shouldUseSkwasm()` returns false
```js
async function shouldUseSkwasm() {
  const searchParams = new URLSearchParams(window.location.search);
  const wasmEnabledFromQueryParameter = searchParams.get(wasmQueryParameterKey) === 'true';
  const wasmEnabledFromDevToolsPreference = await getDevToolsWasmPreference();
  return wasmEnabledFromQueryParameter === true || wasmEnabledFromDevToolsPreference === true;
}
```

Though I can manually serve via 
```
<devtools>/packages/devtools_app/build/web % dhttpd  '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'
```
and put `?wasm=true` in the `http://localhost:8080?wasm=true` URL. Then it uses the `main.dart.wasm` and it works just fine (e.g. cpu profiler).

=> I see no sign in the console of the bug mentioned here.

The error this issue is about makes entirely sense given the bug I've found and fixed - I would be very surprised if another bug manifests in the same way.

=> Without clear, detailed instructions on how to reproduce this with newest flutter master there's nothing I can do.

**Comment by mkustermann** [comment] 2024-09-20 13:33
@kenzieschmoll Do you still experience this issue and have reproduction instructions? Or is the issue fixed for you as well (as I would expect)?

**Comment by kenzieschmoll** [comment] 2024-09-26 16:19
I tried to reproduce this morning and could not, so it appears this issue is fixed. Thanks!

**Closed by kenzieschmoll** 2024-09-26 16:19 UTC
Labels: type-bug, area-dart2wasm
