### ISSUE TITLE
[vm/aot] No guarded list length for final fields

### ISSUE THREAD

**Issue by ds84182** [dart-lang/sdk#50215] opened 2022-10-15 22:42 UTC
For AOT compilation, constant list lengths from initializers are not known at compile time, resulting in bounds checks being generated where they could be elided. Additionally, while putting together an example I also found that IntConverter does not propagate range information.

Godbolt Link: https://dart.godbolt.org/z/Y7a7efPf1

cc: @mraleph

**Comment by mraleph** [comment] 2022-10-17 06:56
Duplicate of https://github.com/dart-lang/sdk/issues/37710

**Closed by mraleph** 2022-10-17 06:56 UTC
Labels: area-vm, vm-aot-code-size
