### ISSUE TITLE
VM loses generic function type after an `await`

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#33025] opened 2018-05-02 19:43 UTC
```dart
void main() {
  doStuff<String>();
}

doStuff<T>() async {
  print(T);
  await null;
  print(T);
}
```

prints:

```
String
dynamic
```

**Comment by kevmoo** [comment] 2018-05-02 19:47
This is with `--preview-dart-2`

**Comment by crelier** [comment] 2018-05-02 22:10
out/DebugX64/dart --preview-dart-2 ~/bug.dart
String
dynamic

out/DebugX64/dart --reify-generic-functions ~/bug.dart
String
String

So this is an issue when using fasta/kernel, and not an issue in the VM runtime.
I suspect that the local variable holding the type arguments in the async closure of function doStuff is not captured as it should.
I am reassigning this issue to area-kernel.

**Comment by kmillikin** [comment] 2018-05-03 10:51
It feels to me that there's something wrong in the VM.  The compiled Kernel for `doStuff` looks as I expected:

```dart
static method doStuff<T extends core::Object>() → dynamic /* originally async */ {
  final asy::Completer<dynamic> :completer = asy::Completer::sync<dynamic>();
  asy::FutureOr<dynamic> :return_value;
  dynamic :async_stack_trace;
  dynamic :async_op_then;
  dynamic :async_op_error;
  dynamic :await_jump_var = 0;
  dynamic :await_ctx_var;
  dynamic :saved_try_context_var0;
  function :async_op([dynamic :result, dynamic :exception, dynamic :stack_trace]) → dynamic yielding 
    try {
      #L1:
      {
        core::print(self::doStuff::T);
        [yield] let dynamic #t1 = asy::_awaitHelper(null, :async_op_then, :async_op_error, :async_op) in null;
        :result;
        core::print(self::doStuff::T);
      }
      :completer.{asy::Completer::complete}(:return_value);
      return;
    }
    on dynamic catch(dynamic :exception, dynamic :stack_trace) {
      :completer.{asy::Completer::completeError}(:exception, :stack_trace);
    }
  :async_stack_trace = asy::_asyncStackTraceHelper(:async_op);
  :async_op_then = asy::_asyncThenWrapperHelper(:async_op);
  :async_op_error = asy::_asyncErrorWrapperHelper(:async_op);
  asy::Future::microtask<dynamic>(:async_op);
  return :completer.{asy::Completer::future};
}
```
Note two occurrences of `self::doStuff::T`.  However, the VM's compiler is generating code like this for the second call to `print`:

```
0x7f9a0dff3887    415b                   pop r11
        ;; t0 <- Constant(#null)
0x7f9a0dff3889    41ff7660               push [thr+0x60]   null
        ;; t1 <- LoadLocal(:function_type_arguments_var @-7)
0x7f9a0dff388d    ff75c8                 push [rbp-0x38]
        ;; t0 <- InstantiateType:136(T, instantiator_type_args(t0), function_type_args(t1))
0x7f9a0dff3890    5a                     pop rdx
0x7f9a0dff3891    58                     pop rax
0x7f9a0dff3892    41ff7660               push [thr+0x60]   null
0x7f9a0dff3896    4d8b9f3f000000         movq r11,[pp+0x3f]   TypeParameter: name T; index: 0; function: doStuff; bound: Object
0x7f9a0dff389d    4153                   push r11
0x7f9a0dff389f    50                     push rax
0x7f9a0dff38a0    52                     push rdx
0x7f9a0dff38a1    498b9eb8010000         movq rbx,[thr+0x1b8]
0x7f9a0dff38a8    41ba03000000           movl r10,3
0x7f9a0dff38ae    4d8b9ed0000000         movq r11,[thr+0xd0]
0x7f9a0dff38b5    4d8ba698000000         movq r12,[thr+0x98]   Code([Stub] CallToRuntime)
0x7f9a0dff38bc    41ffd3                 call r11
0x7f9a0dff38bf    415b                   pop r11
0x7f9a0dff38c1    415b                   pop r11
0x7f9a0dff38c3    415b                   pop r11
0x7f9a0dff38c5    58                     pop rax
0x7f9a0dff38c6    50                     push rax
        ;; PushArgument(t0)
        ;; StaticCall:138( print<0> t0)
0x7f9a0dff38c7    498b9f77000000         movq rbx,[pp+0x77]   ICData target:'print' num-args: 0 num-checks: 1 type-args-len: 0
0x7f9a0dff38ce    4d8ba77f000000         movq r12,[pp+0x7f]   Code([Stub] ZeroArgsUnoptimizedStaticCall)
0x7f9a0dff38d5    4d8b5c2407             movq r11,[r12+0x7]
0x7f9a0dff38da    41ffd3                 call r11
0x7f9a0dff38dd    59                     pop rcx
```
You can see that `:function_type_arguments_var` was stack-allocated.  I suspect that it just needs to be added to the list of variables that are always captured in `StreamingScopeBuilder::VisitFunctionNode`` in `runtime/vm/compiler/frontend/kernel_binary_flowgraph.cc`.

**Comment by crelier** [comment] 2018-05-03 19:03
By not being an issue in the VM runtime, I meant that everything works if you do not use kernel.
But since flow graph building from kernel is now part of the VM (not runtime per se), yes, it is a VM bug.

However, I am not familiar at all with how kernel scopes are being processed and how variables referred to by local functions get marked as captured. Note that the reference to function_type_arguments_var in this case is somewhat hidden, because it is accessed to instantiate the type parameter. This case is handled in the non-CFE parser by the call `CaptureAllInstantiators()` or sometimes just `CaptureFunctionTypeArguments()`.

I see code in `StreamingScopeBuilder::BuildScopes()` creating the `:function_type_arguments_var` variable. The question is how does this variable get marked as captured when accessed from a local function (from the async closure of doStuff)?

```
  // Add function type arguments variable before current context variable.
  if (I->reify_generic_functions() &&
      (function.IsGeneric() || function.HasGenericParent())) {
    LocalVariable* type_args_var = MakeVariable(
        TokenPosition::kNoSource, TokenPosition::kNoSource,
        Symbols::FunctionTypeArgumentsVar(), AbstractType::dynamic_type());
    scope_->AddVariable(type_args_var);
    parsed_function_->set_function_type_arguments(type_args_var);
  }

```

The hacky function `LocalScope::CaptureLocalVariables` mentioned by Slava is probably irrelevant here, since it is only called in particular cases (this should be cleaned up) and the variable should get captured by a call to `LocalScope::CaptureVariable`.

If I understand correctly, `StreamingScopeBuilder::BuildScopes()` visits all nodes of the graph, but fails to notice that the `:function_type_arguments_var` is accessed to instantiate a type.

I can continue digging, but once again, this code is totally new to me. Let me know.

**Comment by mraleph** [comment] 2018-05-03 19:10
@crelier sorry, I should have mentioned explicitly that I have reassigned the bug to myself and I have a fix.

https://dart-review.googlesource.com/c/sdk/+/53664

**Comment by crelier** [comment] 2018-05-03 19:17
Ah, I see. It is not that visiting the graph failed to capture the variable, but the graph was just wrong.
Thanks for fixing.

**Comment by mraleph** [comment] 2018-05-03 19:25
@crelier there are two ways to fix it - I actually first implemented a different approach with capturing it, but it seems wasteful because the only case when it can be captured is the case where it can be simply reloaded from the closure field.

**Closed** 2018-05-04 11:14 UTC
Labels: P1 high, area-vm, preview-dart-2

**Comment by radzish** [comment] 2018-05-07 09:17
it looks like in more complicated case error is still happening, at least in dev 53 version:
```dart
import 'dart:async';
import 'dart:convert';

void main() async {
  ServerResponse<SigninResult> result = await post<SigninResult>(
    "/signin",
    SigninResult.fromJson,
  );
  print(result);
}

typedef Converter<S> = S Function(Map<String, dynamic>);

class SigninResult {
  SigninResult();

  static SigninResult fromJson(Map<String, dynamic> json) {
    return null;
  }
}

class ServerResponse<S> {
  final S result;
  final dynamic exception;

  ServerResponse.success(this.result) : exception = null;

  ServerResponse.fromException(this.exception) : result = null;
}

Future<ServerResponse<S>> post<S>(
  String url,
  Converter<S> converter,
) async {
  ServerResponse<S> response;
  try {
    //when this line is inlined (comment this out and uncomment two following lines)
    //everything works fine
    String body = await doServerCall();

//    await openUrl();
//    String body = "some response";

    response = ServerResponse.success(
      converter != null ? converter(jsonDecode(body)) : null,
    );
  } catch (e) {
    response = ServerResponse.fromException(e);
  }
  return response;
}

Future<String> doServerCall() async {
  await openUrl();
  return "some response";
}

Future<Null> openUrl() {
  throw Error();
}
```

**Comment by keertip** [comment] 2018-05-07 23:59
The fix is not in dev 53.

**Comment by kevmoo** [comment] 2018-05-08 00:00
Nope. You can open the commit (
https://github.com/dart-lang/sdk/commit/f35bb0379d249e197c45b94fbbf52c5d5e8bf019)
and look at the top – you'll see the tags the commit is in...

**Comment by radzish** [comment] 2018-05-08 05:51
if the fix is in dev 53, then what I have is different issue, right?

**Comment by kevmoo** [comment] 2018-05-08 06:04
@radzish – the fix is not in -dev.53. Likely in -dev.54

**Comment by mraleph** [comment] 2018-05-08 06:06
@radzish could you also describe what you think is a bug? I run your code and I get `Instance of 'ServerResponse<SigninResult>` in both cases. Is this what you expect or not?

**Comment by mraleph** [comment] 2018-05-08 06:35
@radzish perfect. that means that the issue is fixed on master. the fix should reach Flutter next time we roll Dart into it, which usually happens pretty regularly. the schedule is not tied to Dart SDK dev releases at the moment.
