### ISSUE TITLE
When using Dart FFI to call Rust, Rust fails to unwind or capture backtrace, when upgrading Dart 3.0.7 to 3.1.0

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#53545] opened 2023-09-17 07:16 UTC
Hi thanks for the great Dart language (and Flutter framework)! 

The context is that, in https://github.com/fzyzcjy/flutter_rust_bridge, Dart calls Rust functions via Dart FFI and Rust FFI (indeed using C-like ABI). It worked perfectly, until one day it fails to panic, and shows "fatal runtime error: failed to initiate panic, error 3".

I have already created an issue at Rust side (since it is directly related to Rust's panic) - https://github.com/rust-lang/rust/issues/115906, but I am not sure whether this is possible a bug of Dart, so I also create one here in case it is. For example, I am not sure whether it is possible because Dart stack frames somehow makes the C `_Unwind_RaiseException` confused (https://github.com/rust-lang/rust/blob/a09c1f85f1bc5be9a85e1395e7482caff91260cc/library/panic_unwind/src/gcc.rs#L61).

### Minimal reproducible sample

<details>

`/dart/main.dart`

```dart
import 'dart:ffi' as ffi;
import 'dart:ffi';

typedef NativeRustHelloFunction = ffi.Void Function();
typedef NativeHelloFunction = void Function();

void main() {
  final dl = ffi.DynamicLibrary.open("../rust/target/debug/libhello_rust.so");
  final f = dl.lookupFunction<NativeRustHelloFunction, NativeHelloFunction>("hello_rust_function");
  f();
}
```

`/rust/lib.rs`

```rs
#[no_mangle]
pub extern "C" fn hello_rust_function() {
    // or, test backtrace capture
    // println!("hi backtrace {:?}", std::backtrace::Backtrace::force_capture());

    // either test panic
    println!("hello_rust_function start");
    let result = std::panic::catch_unwind(move || {
        println!("call panic");
        panic!("hi this is panic");
    });
    println!("hello_rust_function end {:?}", result);
}
```

`/rust/Cargo.toml`

```
[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "hello_rust"
crate-type = ["cdylib"]
```

`/run.sh`

```
#!/bin/bash
set -eux

(cd rust && cargo build)

(cd dart && dart main.dart)
```

Then just `./run.sh` and see what happens.

The bug is confirmed on multiple Linux machines.

Error logs:

```
hello_rust_function start
call panic
thread '<unnamed>' panicked at 'hi this is panic', src/lib.rs:6:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 3
./run.sh: line 6: 17361 Aborted                 (core dumped) dart main.dart
```

Or, if uncomment the backtrace capture line of code:

```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x10
version=3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "linux_x64"
pid=18054, thread=18062, isolate_group=main(0x5573964a15f0), isolate=main(0x5573964a3e50)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=5573943f0360, vm_instructions=5573943f0360
fp=ffffffff, sp=7f31dc3fdf10, pc=557394ac12f2
Stack dump aborted because GetAndValidateThreadStackBounds failed.
  pc 0x0000557394ac12f2 fp 0x00000000ffffffff unw_get_reg+0x72
./run.sh: line 6: 18054 Aborted                 (core dumped) dart main.dart
```

**Comment by blaugold** [comment] 2023-09-17 08:13
This might be the same issue as https://github.com/dart-lang/sdk/issues/53267.

**Comment by fzyzcjy** [comment] 2023-09-17 08:39
That looks similar (especially since my bug happens in Dart 3.1.0). Thanks!

**Comment by a-siva** [comment] 2023-10-12 16:51
https://github.com/dart-lang/sdk/issues/53267 has been fixed, this is probably a duplicate of the same issue, so closing.

**Closed by a-siva** 2023-10-12 16:51 UTC
Labels: area-vm, library-ffi
