### ISSUE TITLE
Can't do a plain "return" in a Future<void> function (but can in Future<Null>)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/sdk#32548] opened 2018-03-15 17:16 UTC
I believe the warning below is wrong.

```
import 'dart:async';

void foo1() {
  return;
}

Null foo2() {
  return;
}

Future<void> foo3() async {
  return; // warning • Missing return value after 'return' at test.dart:12:3 • return_without_value                                                                                                                                                            
}

Future<Null> foo4() async {
  return;
}

void main() { }
```

**Comment by matanlurey** [comment] 2018-03-15 17:18
Duplicate of #32443.

**Closed by matanlurey** 2018-03-15 17:18 UTC
Labels: Resolution: duplicate
