### ISSUE TITLE
`vm:prefer-inline` seems not to work, so even simple closures are slower

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/sdk#50359] opened 2022-11-02 08:34 UTC
This issue happens when I examine the `Timeline.timeSync`. I realize that `timeSync` is quite convenient to use, while Flutter uses `startSync`/`finishSync` a lot. Thus I was wondering whether it is a performance issue. Then I did some experiment and realized the closure does generate more assembly code.

Thus the question is: Why putting prefer-inline does not make it really inline? Am I using the pragma wrong, or Dart just does not want to inline it due to some reasons? If it is inlined IMHO the closure performance will be as fast as the non-closure version.

Sample code (simplified from dart Timeline class):

<details>

```dart
class Flow {}

typedef TimelineSyncFunction<T> = T Function();

class Timeline {
  static void startSync(String name, {Map? arguments, Flow? flow}) => print(name);

  static void finishSync() => print('dummy');

  static T timeSync<T>(String name, TimelineSyncFunction<T> function, {Map? arguments, Flow? flow}) {
    startSync(name, arguments: arguments, flow: flow);
    try {
      return function();
    } finally {
      finishSync();
    }
  }

  @pragma('vm:prefer-inline')
  static T timeSyncInline<T>(String name, TimelineSyncFunction<T> function, {Map? arguments, Flow? flow}) {
    startSync(name, arguments: arguments, flow: flow);
    try {
      return function();
    } finally {
      finishSync();
    }
  }
}

void f1() {
  Timeline.startSync('name');
  print('inside callback');
  Timeline.finishSync();
}

void f2() {
  Timeline.timeSync('name', () {
    print('inside callback');
  });
}

void f3() {
  Timeline.timeSyncInline('name', () {
    print('inside callback');
  });
}

void main() {
  f1();
}
```

</details>

https://godbolt.org/z/rd7hschsv

![image](https://user-images.githubusercontent.com/5236035/199439444-d4845d5c-00c2-454d-b513-87ca5fe504ff.png)

**Comment by mraleph** [comment] 2022-11-02 10:29
Duplicate of https://github.com/dart-lang/sdk/issues/43233

**Closed by mraleph** 2022-11-02 10:29 UTC

**Comment by fzyzcjy** [comment] 2022-11-02 11:10
I see... Weird to know try/catch cannot be inlined, since humans can easily inline it and IDE refactor tool also can
