### ISSUE TITLE
Dart extension methods are not autocompleted

### ISSUE THREAD

**Issue by vanlooverenkoen** [dart-lang/sdk#40365] opened 2020-01-29 08:22 UTC
I have to import the file manualy every time I want to use one of my extensions from my extensionsfile

I use android studio.
```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-BE)
    • Flutter version 1.12.13+hotfix.5 at /Users/vanlooverenkoen/flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanlooverenkoen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • AOSP on IA Emulator • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • F2704E51-185C-4E5F-BC54-8FB1BA3C43BE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS               • macOS                                • darwin-x64     • Mac OS X 10.15.1 19B88
    • Chrome              • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server          • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```
https://github.com/flutter/flutter/issues/49617

**Comment by bwilkerson** [comment] 2020-01-29 15:18
@jwren @pq

**Comment by atreeon** [comment] 2020-04-17 10:01
Possible Intellij workaround:
type the name of the extension 

so, for `extension String_Extension on String {`

you would type `String_Extension`, intellisense should recognise the extension name and selecting it will import the reference

**Comment by vanlooverenkoen** [comment] 2020-04-17 11:09
Just tried it with a DateTime_Extension. It did not work

**Comment by atreeon** [comment] 2020-04-17 22:34
I've using this technique for about 3 weeks now in IntelliJ.  Maybe it only works in Intellij??  Worth another go as this was really really annoying beforehand!

![Screenshot 2020-04-17 at 23 33 36](https://user-images.githubusercontent.com/4139336/79619124-e419c300-8103-11ea-9829-5c65a1a8077c.png)

**Comment by jimmy-robert** [comment] 2020-04-23 16:31
> Possible Intellij workaround:
> type the name of the extension 
> 
> so, for `extension String_Extension on String {`
> 
> you would type `String_Extension`, intellisense should recognise the extension name and selecting it will import the reference

Yes, this works but it's kind of annoying... In intelliJ Kotlin extensions are well autocompleted as you type the method name on your variable, I hope this problem will be fixed soon

**Comment by vanlooverenkoen** [comment] 2020-04-24 07:12
> I've using this technique for about 3 weeks now in IntelliJ. Maybe it only works in Intellij?? Worth another go as this was really really annoying beforehand!
> 
> ![Screenshot 2020-04-17 at 23 33 36](https://user-images.githubusercontent.com/4139336/79619124-e419c300-8103-11ea-9829-5c65a1a8077c.png)

Can't get it to work in Android Studio

**Comment by DanTup** [comment] 2020-05-14 07:19
@bwilkerson possibly a dupe of https://github.com/dart-lang/sdk/issues/38894?

**Comment by bwilkerson** [comment] 2020-05-14 13:52
That seems likely, so I'll close it for now under the assumption that it is.

**Closed by bwilkerson** 2020-05-14 13:52 UTC
Labels: analyzer-completion, area-analyzer
