### ISSUE TITLE
idea dart server report

### ISSUE THREAD

**Issue by BearLesnick** [dart-lang/sdk#39477] opened 2019-11-21 11:50 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.7142.36`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IC-192.7142.36, JRE 11.0.4+10-b304.77x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: type 'MethodInvocationImpl' is not a subtype of type 'ThisExpression' in type cast
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:677:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/hg/7pv7bhwd4_10gl5bks012nk80000gn/T/report1.txt.

**Comment by srawlins** [comment] 2019-11-27 05:20
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38327; please upgrade to the latest Dart, and reopen if you encounter this issue again.

**Comment by srawlins** [comment] 2019-11-27 05:20
Duplicate of https://github.com/dart-lang/sdk/issues/38327

**Closed by srawlins** 2019-11-27 05:20 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
