### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by antixirus** [dart-lang/sdk#41044] opened 2020-03-13 23:54 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.7.0`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.7.0, server version 1.27.4, FATAL error: FileSystemException: writeFrom failed, path = '' (OS Error: Insufficient system resources exist to complete the requested service.
, errno = 1450)
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file://C:\Users\Lambo\AppData\Local\Temp\report.txt.

**Comment by srawlins** [comment] 2020-06-14 18:40
Thanks for reporting this issue! This was previously reported at #38914. Please follow along there.

**Comment by srawlins** [comment] 2020-06-14 18:41
Duplicate of #38914

**Closed by srawlins** 2020-06-14 18:41 UTC
Labels: analyzer-crash-report, area-analyzer
