### ISSUE TITLE
SecureSocket handshake can stall the main thread for long time

### ISSUE THREAD

**Issue by besthyhy** [dart-lang/sdk#41519] opened 2020-02-06 07:17 UTC
In my application, the SDK used before was 1.9 and everything worked fine. After upgrading to 1.12, android still works well, but ios will get stuck on the splash screen.

### Detailed questions:
1. Sometimes the first time you start it will get stuck on the splash screen.
2. Manually kill the process and then enter the app, there is a high possibility that it will get stuck on the splash screen page.

### Code situation
1. pubspec.yaml
http: 0.12.0+4
2. lib/SplashPage.dart
```dart
class SplashPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _StdPageState();
  }
}

class _StdPageState extends State<SplashPage> {
  @override
  void initState() {
    super.initState();
    
    // send Http here
  }
}
```
3. lib/util/HttpsUtils.dart
```dart
import 'dart:convert' show utf8;
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:inlan_flutter/Config.dart';
import 'package:inlan_flutter/util/DataUtils.dart';
import 'package:inlan_flutter/util/I18nUtils.dart';
import 'package:inlan_flutter/util/JsonUtils.dart';
import 'package:inlan_flutter/util/LogUtils.dart';
import 'package:inlan_flutter/util/ToastUtils.dart';
import 'package:inlan_flutter/util/UpgradeUtils.dart';
import 'package:inlan_flutter/util/UuidUtils.dart';

class HttpsUtils {
  static void apiPostWithUrl(
      String url,
      Map<String, dynamic> body,
      BuildContext context,
      StackTrace callPositionStackTrace,
      State state,
      callback(json)) async {
    body["version"] = Config.apiVersion;
    body["httpId"] = UuidUtils.v4();
    body["lang"] = I18nUtils.languageCode();
    body["path"] = url;

    String fullUrl = Config.apiUrl + url;

    final apiClient = http.Client();

    try {
      await apiClient
          .post(fullUrl,
              headers: {"Content-Type": "application/json"},
              body: JsonUtils.encode(body))
          .then((response) {
        LogUtils.log(response.statusCode, StackTrace.current,
            tag: "statusCode");

        LogUtils.devLog(Config.apiUrl + url, callPositionStackTrace,
            tag: "apiUrl " + url);

        LogUtils.devLog(JsonUtils.prettyJson(body), callPositionStackTrace,
            tag: "req");

        LogUtils.devLog(
            JsonUtils.prettyStr(response.body), callPositionStackTrace,
            tag: "resp ${response.statusCode}");

        switch (response.statusCode) {
          case 200:
            callback(JsonUtils.parse(response.body));
            break;
          case 400:
            Map<String, dynamic> jsonObj = JsonUtils.parse(response.body);
            state.setState(() {
              ToastUtils.short(jsonObj["message"]);
            });
            break;
          case 401:
            Map<String, dynamic> jsonObj = JsonUtils.parse(response.body);
            state.setState(() {
              ToastUtils.withCallback(jsonObj["message"], () {
                DataUtils.setByService('login_data', '-1');
                DataUtils.setByService('isLogined', '-1');
                Navigator.pushNamedAndRemoveUntil(
                    context, '/account', (Route<dynamic> route) => false);
              });
            });
            break;
          case 403:
            break;
          case 406:
            UpgradeUtils().doForceUpgrade(context);
            break;
          case 422:
            Map<String, dynamic> jsonObj = JsonUtils.parse(response.body);
            state.setState(() {
              ToastUtils.short(jsonObj["message"]);
            });
            break;
        }
      });
    } finally {
      apiClient.close();
    }
  }
}
```

### My temporary solution
```dart
  void initState() {
    super.initState();
    Timer timer = new Timer(new Duration(milliseconds: 1200), () {
      // send Http here
    });
    
  }
```

### Expected solution
1. What causes the freeze?
2. A better solution?

**Comment by beiger** [comment] 2020-04-16 02:03
I'm using HttpClient from dart:io. I tried  to set the badCertificateCallback, the program did not enter callback.

I've only had this kind of stuck situation since last month, and there are some people who have met earlier than me. It used to run well with the same code. This is only on IOS, Android is good.

**Comment by mraleph** [comment] 2020-04-23 08:22
I don't think there is enough information here for us to diagnose problem. 

HTTP processing is done asynchronously so it can't just block your UI thread. 

I would start by looking for exceptions in the logs.

**Comment by beiger** [comment] 2020-04-23 09:45
Many people have encountered this situation.
Maybe this is the problem of iOS, I don't know.

**Comment by CyrilHu** [comment] 2020-04-23 10:28
> this

I also have this problem, I tried the same request in Safari, It's also slow,

Server ENV:
- Nginx + HTTPS(Let's Encrypt)
Client ENV:
- Device: iPhone XR , iOS 13.4
- Flutter 1.12.13+hotfix.9 • Tools • Dart 2.7.2

TEST:
My Flutter App: 
- http: response in 200ms,
- https: about 6 - 10 seconds and the UI frozen, it freeze about 30 seconds when I send 5 request at the same time 
Safari: 
- http: response in 200ms,
- https: about 5 - 8 seconds, safari is not freeze

This is the stack trace,  I pause debug when the UI frozen 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1403754/80088812-95e74280-858f-11ea-9095-577513d74139.png">

**Comment by mraleph** [comment] 2020-04-23 13:52
@CyrilHu could you try running the following code on your iOS device (replace url to point to your https server)

```dart
import 'dart:async';
import 'dart:developer' as developer;
import 'dart:io';

void log(String s) {
  print(s);
  developer.log(s);
}

Timer stallDetector() {
  final sw = Stopwatch()..start();
  return Timer.periodic(Duration(milliseconds: 5), (_) {
    if (sw.elapsedMilliseconds > 10) {
      log('EVENT LOOP WAS STALLED FOR ${sw.elapsedMilliseconds} ms');
    }
    sw.reset();
  });
}

void main() async {
  final url = 'https://gank.io';
  final timer = stallDetector();
  var sw = Stopwatch()..start();
  var httpClient = HttpClient();
  try {
    var request = await httpClient.getUrl(Uri.parse(url));
    var response = await request.close();
    log('REQUEST COMPLETE IN ${sw.elapsedMilliseconds} ms');
  } finally {
    httpClient.close(force: true);
    timer.cancel();
  }
}
```

what does it print back?

**Comment by CyrilHu** [comment] 2020-04-23 15:22
> @CyrilHu could you try running the following code on your iOS device (replace url to point to your https server)
> 
> what does it print back?

https test 1:
flutter: EVENT LOOP WAS STALLED FOR 48 ms
[log] EVENT LOOP WAS STALLED FOR 48 ms
flutter: EVENT LOOP WAS STALLED FOR 24 ms
[log] EVENT LOOP WAS STALLED FOR 24 ms
flutter: EVENT LOOP WAS STALLED FOR 30 ms
[log] EVENT LOOP WAS STALLED FOR 30 ms
[log] EVENT LOOP WAS STALLED FOR 3274 ms
flutter: EVENT LOOP WAS STALLED FOR 3274 ms
[log] EVENT LOOP WAS STALLED FOR 62 ms
flutter: EVENT LOOP WAS STALLED FOR 62 ms
flutter: REQUEST COMPLETE IN 3967 ms
[log] REQUEST COMPLETE IN 3967 ms

https test 2:
flutter: EVENT LOOP WAS STALLED FOR 124 ms
[log] EVENT LOOP WAS STALLED FOR 124 ms
flutter: EVENT LOOP WAS STALLED FOR 29 ms
[log] EVENT LOOP WAS STALLED FOR 29 ms
[log] EVENT LOOP WAS STALLED FOR 34 ms
flutter: EVENT LOOP WAS STALLED FOR 34 ms
flutter: EVENT LOOP WAS STALLED FOR 2744 ms
[log] EVENT LOOP WAS STALLED FOR 2744 ms
[log] EVENT LOOP WAS STALLED FOR 39 ms
flutter: EVENT LOOP WAS STALLED FOR 39 ms
flutter: REQUEST COMPLETE IN 3079 ms
[log] REQUEST COMPLETE IN 3079 ms

http test 1:
flutter: EVENT LOOP WAS STALLED FOR 70 ms
[log] EVENT LOOP WAS STALLED FOR 70 ms
[log] EVENT LOOP WAS STALLED FOR 30 ms
flutter: EVENT LOOP WAS STALLED FOR 30 ms
[log] EVENT LOOP WAS STALLED FOR 90 ms
flutter: EVENT LOOP WAS STALLED FOR 90 ms
flutter: REQUEST COMPLETE IN 245 ms
[log] REQUEST COMPLETE IN 245 ms

http test 2:
flutter: EVENT LOOP WAS STALLED FOR 67 ms
[log] EVENT LOOP WAS STALLED FOR 67 ms
[log] EVENT LOOP WAS STALLED FOR 32 ms
flutter: EVENT LOOP WAS STALLED FOR 32 ms
[log] EVENT LOOP WAS STALLED FOR 68 ms
flutter: EVENT LOOP WAS STALLED FOR 68 ms
[log] REQUEST COMPLETE IN 227 ms
flutter: REQUEST COMPLETE IN 227 ms

**Comment by ghostgzt** [comment] 2020-04-23 20:10
@mraleph 
Is there a temporary solution? This is a very urgent problem!

**Comment by mraleph** [comment] 2020-04-23 20:23
Yeah, this seems pretty bad. Based on my cursory analysis of the code most likely cause of the the problem is the fact that we install a certificate verification callback (via `SSL_CTX_set_cert_verify_callback`) which uses `SecTrustEvaluateWithError`. 

However `SecTrustEvaluateWithError` comes with the following warning:

> Don’t call `SecTrustEvaluateWithError` from your app’s main run loop because it might require network access to fetch intermediate certificates, or to perform revocation checking. To perform evaluation asynchronously, use `SecTrustEvaluateAsyncWithError` instead.

Which seems to match the situation we are experiencing here - I think the stall occurs when `SecTrustEvaluateWithError` is attempting to check revocation status of the certificate. I suspect that you should be able to speed things up by configuring OCSP stapling. 

I am extremely unfamiliar with this code (e.g. it is unclear to me why we use `SSL_CTX_set_cert_verify_callback` to verify the whole certificate chain, rather than using `SSL_CTX_set_verify` to verify individual certificates in the chain - the latter API supports asynchronous verification, while `SSL_CTX_set_cert_verify_callback` API is completely synchronous. If we must use `SSL_CTX_set_cert_verify_callback` - then we have to offload handshaking into a thread pool to make it asynchronous, otherwise we will stall UI thread too much.

@bkonyi @zanderso @dnfield you are the ones changing this code most. Can you take a look at this?

/cc @zichangg @sortie

**Comment by mraleph** [comment] 2020-04-23 20:26
@ghostgzt I think the only client side workaround I can offer is to use a separate isolate to handle networking and then send results back into the main isolate. This would prevent UI from stalling - but hand shake would still take very long time.

**Comment by bkonyi** [comment] 2020-04-23 20:50
It looks like there's a [SecTrustEvaluateAsyncWithError](https://developer.apple.com/documentation/security/3235761-sectrustevaluateasyncwitherror?language=objc) that we might be able to use here instead.

We were using `SSL_CTX_set_cert_verify_callback` as we needed to be able to access the `SSLCertContext` associated with the connection from the verification callback but `SSL_CTX_set_verify` doesn't allow for passing an argument to the callback. Can you point me to where in the documentation it says `SSL_CTX_set_cert_verify_callback` is synchronous whereas `SSL_CTX_set_verify` is not? Open/BoringSSL documentation is abysmal, so maybe I just missed that somewhere.

**Comment by mraleph** [comment] 2020-04-24 07:44
> Can you point me to where in the documentation it says SSL_CTX_set_cert_verify_callback is synchronous whereas SSL_CTX_set_verify is not?

It turns out that I actually meant `SSL_CTX_set_custom_verify` rather than `SSL_CTX_set_verify` (this library is amazing 🙄).

```cpp
// SSL_CTX_set_cert_verify_callback sets a custom callback to be called on
// certificate verification rather than |X509_verify_cert|. |store_ctx| contains
// the verification parameters. The callback should return one on success and
// zero on fatal error. It may use |X509_STORE_CTX_set_error| to set a
// verification result.
//
// The callback may use |SSL_get_ex_data_X509_STORE_CTX_idx| to recover the
// |SSL| object from |store_ctx|.
OPENSSL_EXPORT void SSL_CTX_set_cert_verify_callback(
    SSL_CTX *ctx, int (*callback)(X509_STORE_CTX *store_ctx, void *arg),
    void *arg);
```

```cpp
enum ssl_verify_result_t BORINGSSL_ENUM_INT {
  ssl_verify_ok,
  ssl_verify_invalid,
  ssl_verify_retry,
};

// SSL_CTX_set_custom_verify configures certificate verification. |mode| is one
// of the |SSL_VERIFY_*| values defined above. |callback| performs the
// certificate verification.
//
// The callback may call |SSL_get0_peer_certificates| for the certificate chain
// to validate. The callback should return |ssl_verify_ok| if the certificate is
// valid. If the certificate is invalid, the callback should return
// |ssl_verify_invalid| and optionally set |*out_alert| to an alert to send to
// the peer. Some useful alerts include |SSL_AD_CERTIFICATE_EXPIRED|,
// |SSL_AD_CERTIFICATE_REVOKED|, |SSL_AD_UNKNOWN_CA|, |SSL_AD_BAD_CERTIFICATE|,
// |SSL_AD_CERTIFICATE_UNKNOWN|, and |SSL_AD_INTERNAL_ERROR|. See RFC 5246
// section 7.2.2 for their precise meanings. If unspecified,
// |SSL_AD_CERTIFICATE_UNKNOWN| will be sent by default.
//
// To verify a certificate asynchronously, the callback may return
// |ssl_verify_retry|. The handshake will then pause with |SSL_get_error|
// returning |SSL_ERROR_WANT_CERTIFICATE_VERIFY|.
OPENSSL_EXPORT void SSL_CTX_set_custom_verify(
    SSL_CTX *ctx, int mode,
    enum ssl_verify_result_t (*callback)(SSL *ssl, uint8_t *out_alert));
```

In `SSL_CTX_set_cert_verify_callback` case callback can return either success or failure, but in `SSL_CTX_set_custom_verify` it can return `ssl_verify_retry` which means verification is in progress asynchronously. 

> We were using SSL_CTX_set_cert_verify_callback as we needed to be able to access the SSLCertContext associated with the connection from the verification callback but SSL_CTX_set_verify doesn't allow for passing an argument to the callback.

Apparently there is an `ex_data` mechanism that allows you to associate arbitrary data with `SSL` object, see e.g. `SSL_set_ex_data`. This should allow us to use `SSL_CTX_set_custom_verify`.

**Comment by mraleph** [comment] 2020-04-24 20:54
We now have confirmation that my speculation about the source of the delay is correct, see screenshots in flutter/flutter#55586. 

@bkonyi Ben, I am tentatively assigning to you because you have written the current version of the code, so you might be able to fix it faster than others.

**Comment by ivanryndyuk** [comment] 2020-04-24 21:26
I've found kinda temporary work around to increase the response speed with platform channel methods
https://github.com/dart-lang/sdk/issues/41451#issuecomment-619243422

**Comment by rxwen** [comment] 2020-04-24 23:19
I noticed similar behavior too with lets encrypt cert too. Haven't investigated deep into the issue yet.
I suspect if it's related to some kind of network blocking in China. The reasoning comes from that we didn't receive report from users out of China.

**Comment by peablog** [comment] 2020-04-25 08:54
The OCSP server for lets encrypt (ocsp.int-x3.letsencrypt.org)  is blocked from China.
And in our business, our SLB service provider (ALIYUN) not support OCSP stapling.
We have change the https cert to solve this problem.

**Comment by rxwen** [comment] 2020-04-25 09:01
> The OCSP server for lets encrypt (ocsp.int-x3.letsencrypt.org) is blocked from China.
> And in our business, our SLB service provider (ALIYUN) not support OCSP stapling.
> We have change the https cert to solve this problem.

But I also suspect the network is part of the problem. Looks like only some users using iOS flutter app have the problem. Other users on android or H5 platforms in similar network environment didn't report issue too.

**Comment by peablog** [comment] 2020-04-25 09:10
> But I also suspect the network is part of the problem. Looks like only some users using iOS flutter app have the problem. Other users on android or H5 platforms in similar network environment didn't report issue too.
> If it's the network blocking to be blamed, why it doesn't happen to all users.

@rxwen  We also notice that Android users not affected by this issue. I guess there may some different default setting between iOS and Android. I am not sure.

**Comment by mraleph** [comment] 2020-04-25 10:53
@rxwen the code that causes stall is iOS specific, we don't have similar code on Android. That would explain why Android uses are unaffected.

(The code was added in 644862bf966e6c079460258807ab3364b7e3759a to make sure that BoringSSL uses system level root certificates)

**Comment by bkonyi** [comment] 2020-04-27 16:51
@mraleph thanks for linking the docs for those methods. I'll take a look this week and see what I can do.

**Comment by nivekz** [comment] 2020-04-28 01:52
We first reported the same issue in https://github.com/flutter/flutter/issues/55586.

We found that there have been reports earlier this month that letsencrypt OCSP is experiencing troubles in China.

The problem severely affects app usability, so getting rid of the stall would definitely help a lot. Nonetheless, the delay of the overall request would still exist. So is there any way we can help devs notice such problems that certain step of communication is unreasonably slow? (so that they wouldn't mistakenly think flutter/dart networking is slow or unreliable :))

**Comment by virushuo** [comment] 2020-04-29 23:15
The OCSP server of letsencrypt (ocsp.int-x3.letsencrypt.org) has been DNS poisoned in China. So your server OCSP Stapling will not work, and the browser will send a request to OCSP server and lead to a lag.

You can run a [OCSP proxy](https://github.com/virushuo/ocsp-proxy) on your server to solve this problem.

**Comment by vifird** [comment] 2020-05-10 08:28
I'm true it's a problem of certificate of https, most of the cases occured whiling using Let's Encrypt certificates. We can find the resolution in a issue: (https://github.com/flutterchina/dio/issues/703)
In letsencrypt's compatibility list, there is no flutter-platform: [letsencrypt certificate compatibility](https://letsencrypt.org/docs/certificate-compatibility/).

**Comment by 100cm** [comment] 2020-05-14 06:02
#https://github.com/flutterchina/dio/issues/786

**Comment by ghostgzt** [comment] 2020-05-21 07:53
any news?

**Comment by zichangg** [comment] 2020-05-21 17:55
@ghostgzt Checkout previous posts. I don't think this is a problem for Dart.

> The OCSP server of letsencrypt (ocsp.int-x3.letsencrypt.org) has been DNS poisoned in China. So your server OCSP Stapling will not work, and the browser will send a request to OCSP server and lead to a lag.
> 
> You can run a [OCSP proxy](https://github.com/virushuo/ocsp-proxy) on your server to solve this problem.

**Comment by dnfield** [comment] 2020-05-21 18:28
@zichangg I believe @mraleph and @bkonyi were looking at using some async methods to do the certificate resolution rather than the current sync ones. It wouldn't fix the underlying DNS poising issue, but it would avoid blocking UI for a Flutter application.

**Comment by mraleph** [comment] 2020-05-26 08:44
@zichangg while it is correct that certificate validation delay is indeed not Dart problem by itself (Safari has the same issue), `dart:io` should not be performing this verification on the main thread and stall UI by doing so. So this needs to be fixed. 

I don't think either me or @bkonyi are actively working on this issue - so it falls on @zichangg's plate.

**Comment by fallenlord** [comment] 2020-07-17 05:14
any new?

is there any plan to fix this on `dart:io`?

**Comment by vsmenon** [comment] 2020-08-05 20:27
@a-siva @franklinyow - is this a candidate for the Sept milestone?

**Comment by franklinyow** [comment] 2020-08-25 23:14
Team need more time for the fix, moved to Oct

**Comment by franklinyow** [comment] 2020-09-21 17:56
@a-siva Who's working on this now?

**Comment by a-siva** [comment] 2020-09-21 22:20
@aam has picked this up.

**Comment by aam** [comment] 2020-09-22 23:12
Per discussion with @rmacnak-google the plan is to leave existing synchronous openssl/boringssl API in place, but have SSLFilter::Handshake() run on dart worker thread using IOService infrastructure that is used for similar synchronous os api calls(file, socket, etc)

**Comment by aam** [comment] 2020-09-23 00:10
One problem with running SSLFilter::Handshake on separate worker thread is its inability to invoke dart's [`onBadCertificate` ](https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/secure_socket.dart#L26) synchronously during handshake.

**Comment by zanderso** [comment] 2020-09-23 16:03
> One problem with running SSLFilter::Handshake on separate worker thread is its inability to invoke dart's [`onBadCertificate` ](https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/secure_socket.dart#L26) synchronously during handshake.

[`SSLCertContext::CertificateCallback()`](https://github.com/dart-lang/sdk/blob/master/runtime/bin/security_context.cc#L38) running on an IOService thread can send a message to the isolate telling it to run the `onBadCertificate`, then block to wait for the result.

**Comment by aam** [comment] 2020-09-24 00:11
Thanks @zanderso . Yeah, that is a possibility, concern would be clean up of blocked IOService thread in case `onBadCertificate` isolate exits.

As a temporary solution I thought of having async handshake only in case when there is no `onBadCertificate` provided. 

Yet another possibility is to use `ssl_verify_retry` return code Slava mentioned above with only [`SecTrustEvaluate`](https://github.com/dart-lang/sdk/blob/master/runtime/bin/security_context_macos.cc#L203) part of `CertificateVerificationCallback` running on a separate thread(spawned via Dart_NewNativePort). This callback will check if it got a response from that thread for that certificate and if so it will synchronously call `onBadCertificate` (if provided), then return the response to continue ssl's handshake, otherwise it will send a request to that thread and return `ssl_verify_retry` to suspend ssl's handshake.

**Comment by aam** [comment] 2020-10-01 13:19
https://dart-review.googlesource.com/c/sdk/+/165520 with proposed fix.

**Comment by a-siva** [comment] 2020-10-05 04:59
Can we close this issue not that the CL has landed ?

**Comment by mraleph** [comment] 2020-10-05 10:37
> [dart-review.googlesource.com/c/sdk/+/165520](https://dart-review.googlesource.com/c/sdk/+/165520) with proposed fix.

The fix landed without tests. Is it possible to add some to prevent regressions in the future?

**Comment by aam** [comment] 2020-10-05 15:36
https://github.com/dart-lang/sdk/issues/43674 to track adding a test.

**Closed by aam** 2020-10-05 15:36 UTC
Labels: P1, area-vm, customer-flutter, library-io, type-bug

**Comment by ghostgzt** [comment] 2020-10-10 11:41
which version fixed this problem?

**Comment by aam** [comment] 2020-10-10 20:04
So far this landed as 63852d2073c776d6d849e306b2e36274f2143eb3 in flutter
master channel(
https://github.com/flutter/flutter/commit/63852d2073c776d6d849e306b2e36274f2143eb3
).

**Comment by winterdl** [comment] 2020-12-06 10:55
I've got the same issue, with the above update,  I will have to test with what dart version, flutter version and what channel, thank you.

**Comment by virskor** [comment] 2021-04-20 04:58
For anyone who is using 1.22.6 but not full prepared migrate into Flutter 2.0 still facing about this problem. My workaround below might help you.  
Get  the current Flutter version path by using this command.
```
which flutter
```

open the path printed.  
delete path ./cache  

cd ./internal   
then you need modify three file to change the flutter verison.
engine: 1d12d82d9cb54876f58044aa52198d53ec841c3d   
fuchsia-linux: h-DeV4tgEk6jHzUlsoZri9lklKQJDEAk7UVXOEpNKFMC  
fuchsia-mac: FFpTJfmj1EGxY5dJDoGNmZ4dwub3GsxHTJHDtKGmQcMC  

now you can still using Flutter 1.22.6 but migrate flutter engine to flutter 1.23.0-18.1pre  

If you can not compile the IOS app after mofications, try modify ./ios/PodFile
```PodFile
# Uncomment this line to define a global platform for your project
platform :ios, '10.0' 
```
and add 
```PodFile
 target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
end
```

then run
```
flutter clean \
&& rm ios/Podfile.lock pubspec.lock \
&& rm -rf ios/Pods ios/Runner.xcworkspace
```
now you can flutter run --release

**Comment by mraleph** [comment] 2021-04-20 07:20
I would strongly advise against just manually rolling engine like that because you might end up some bizarre issues due to ABI skew between Flutter Framework and Flutter engine. Instead you should always just switch to a newer version of Flutter (e.g. if you want to use engine from 1.23.0-18.1pre you should better use Flutter at 1.23.0-18.1pre as well).

**Comment by virskor** [comment] 2021-04-20 08:13
Using 1.23.0-18.1pre might cause Android GestureDetector not working.  we do not have any choice because migrate into Flutter 2.0 is not possible for us at present.  But Flutter team might not know this issue is A BIG TROUBLE for Flutter users in China!
