### ISSUE TITLE
RawSocket listener blocks UI thread

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/sdk#46702] opened 2021-07-23 13:54 UTC
When i setup a listener for a RawSocket and a very big package comes from the server, UI freezes for a few seconds(until the package is fully arrived), however, documentation says that it's non-blocking 

To reproduce the issue you'll have to create a simple server and send about 30-40Mb package of data to the client. When your internet connection is not super fast, package will be divided on a large amount of small packages and client will wait for all the parts of it to arrive, to, for example, decrypt it, the UI won't be available 
```
class PacketHeader {
  late int id;
  late int timestamp;
  late int version;
  late int length;

  Uint8List? payload;
  Uint8List? decrypted;
}

PacketHeader? packageHeader;
Uint8List buffer = Uint8List(0);
  
_client.listen((RawSocketEvent event) async {
    if (event == RawSocketEvent.read) {
      // get package header
     
      if (packetHeader != null) {
          final id = packetHeader.id;
          final length = packetHeader.length;

          final Uint8List? clientBuffer = _client.read();

          if (clientBuffer != null) {
            buffer = Uint8List.fromList(buffer + clientBuffer);
          }

          if (buffer.length < length) {
            // Freeze happens here, when client waits for all parts of the package to arrive by checking already retrieved length of data
            return;
          }
          
          // Decrypt package or do something else
       }
    }
}
```

**Comment by a-siva** [comment] 2021-07-27 00:41
when you say
// freeze happens here
do you mean the 'return' statement is not executed?

**Comment by lrhn** [comment] 2021-07-27 09:03
It's a weird place to freeze since nothing happens there.

I'm more worried about the `buffer + clientBuffer` above which seems to do repeated concatenation of lists. That's something which is known to be potentially quadratic in the size of the result, if you get lots of small parts of the larger package, because it copies everything in `buffer` on each operation. If you get extra slowdown on a large package, that's a potential culprit.

Try something like:
```dart
var buffer = BytesBuilder(copy: false);
_client.forEach((RawSocketEvent event) async {
    if (event == RawSocketEvent.read) {
      // get package header
     
      if (packetHeader != null) {
          final id = packetHeader.id;
          final length = packetHeader.length;

          final Uint8List? clientBuffer = _client.read();

          if (clientBuffer != null) {
            buffer.add(clientBuffer);
          }

          if (buffer.length < length) {
            return;
          }

          var bytes = buffer.takeBytes();          
          // Decrypt package or do something else
       }
    }
});
```
That could avoid some extra copying of the data, and ensure that each incoming byte is only copied once.

**Comment by kirill-21** [comment] 2021-07-27 10:36
> It's a weird place to freeze since nothing happens there.
> 
> I'm more worried about the `buffer + clientBuffer` above which seems to do repeated concatenation of lists. That's something which is known to be potentially quadratic in the size of the result, if you get lots of small parts of the larger package, because it copies everything in `buffer` on each operation. If you get extra slowdown on a large package, that's a potential culprit.
> 
> Try something like:
> 
> ```dart
> var buffer = BytesBuilder(copy: false);
> _client.forEach((RawSocketEvent event) async {
>     if (event == RawSocketEvent.read) {
>       // get package header
>      
>       if (packetHeader != null) {
>           final id = packetHeader.id;
>           final length = packetHeader.length;
> 
>           final Uint8List? clientBuffer = _client.read();
> 
>           if (clientBuffer != null) {
>             buffer.add(clientBuffer);
>           }
> 
>           if (buffer.length < length) {
>             return;
>           }
> 
>           var bytes = buffer.takeBytes();          
>           // Decrypt package or do something else
>        }
>     }
> });
> ```
> 
> That could avoid some extra copying of the data, and ensure that each incoming byte is only copied once.

Thank you very much, it seems that BytesBuilder solved the UI freeze problem, but i don't fully understand how. Because when i removed if (buffer.length < length) statement in the previous code, the problem also disappeared, even though there was a lot of operations with repeated concatenation of lists (but it lead to the problem of not uniting divided packages).

However, why did listener froze the UI because of such heave things if it's non-blocking in the first place?

**Comment by lrhn** [comment] 2021-07-27 10:55
If your code was executing, which it seems like if the freeze was inside your code, then most likely it was your code that froze the UI. Your code is running in the UI isolate, so if any computation takes too long before returning to the event loop, the UI is frozen.
Waiting for the incoming package might be non-blocking, but handling it isn't.

You can also get UI freezing even if your code is asynchronous, if it does a lot of computation using only microtasks, because the UI is running on the main event loop, which you won't get back to before you've emptied the microtask loop.

I can't say precisely which code takes too long. Copying even a big list *by itself* shouldn't be that bad, but if you do a lot of increasingly larger allocations, you might end up triggering a forced garbage collection as well. I'm not enough of an expert on VM internals to say if that could be the case.

**Comment by kirill-21** [comment] 2021-07-27 11:14
> If your code was executing, which it seems like if the freeze was inside your code, then most likely it was your code that froze the UI. Your code is running in the UI isolate, so if any computation takes too long before returning to the event loop, the UI is frozen.
> Waiting for the incoming package might be non-blocking, but handling it isn't.
> 
> You can also get UI freezing even if your code is asynchronous, if it does a lot of computation using only microtasks, because the UI is running on the main event loop, which you won't get back to before you've emptied the microtask loop.
> 
> I can't say precisely which code takes too long. Copying even a big list _by itself_ shouldn't be that bad, but if you do a lot of increasingly larger allocations, you might end up triggering a forced garbage collection as well. I'm not enough of an expert on VM internals to say if that could be the case.

Thank you for explaining

**Comment by a-siva** [comment] 2021-07-27 15:22
Working as intended, closing the issue.

**Closed by a-siva** 2021-07-27 15:22 UTC
Labels: area-library, closed-as-intended, library-io
