### ISSUE TITLE
Adding `set` and `get` to classes that implement List causes weirdness

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#27630] opened 2016-10-20 17:47 UTC
```dart
import 'dart:collection';

void main() {
  var impl = new MyList();
  print(impl.length);
  print(impl[0]);
  print(impl.get(1));

  print(impl[0] = 5);
  print(impl.set(0, 6));
  print(impl[0]);
}

class MyList extends ListBase<int> {
  final _stuff = [1,2,3,4,5];

  int operator [](int index) => _stuff[index];

  /**
   * Sets the value at the given [index] in the list to [value]
   * or throws a [RangeError] if [index] is out of bounds.
   */
  void operator []=(int index, int value) { _stuff[index] = value; }

  /**
   * Returns the number of objects in this list.
   *
   * The valid indices for a list are `0` through `length - 1`.
   */
  int get length => _stuff.length;

  /**
   * Changes the length of this list.
   *
   * If [newLength] is greater than
   * the current length, entries are initialized to [:null:].
   *
   * Throws an [UnsupportedError] if the list is fixed-length.
   */
  set length(int newLength) => _stuff.length =newLength;

  int get(int count) => 42;

  set(int location, int value) {
    return location + value;
  }
}
```

Output w/ dart2js
```
5
1
42
5
6
5
```

Output with DDC
```
5
42
42
5
6
42
```

The added get/set methods are called instead of the indexer

**Comment by jmesserly** [comment] 2016-10-20 18:00
dupe of https://github.com/dart-lang/sdk/issues/27631

**Closed** 2016-10-20 19:33 UTC
Labels: area-dev-compiler, Resolution: duplicate, S1 high, Type: bug
