### ISSUE TITLE
Lack in RawDatagramSocket.bind() documentation

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#35147] opened 2018-11-13 05:40 UTC
Please see https://api.dartlang.org/stable/2.0.0/dart-io/RawDatagramSocket/bind.html
Please, add something like this

`If port has the value 0 an ephemeral port will be chosen by the system. The actual port used can be retrieved using the port getter.`

Also add description ot other parameters. 
`bool reuseAddress: true, bool reusePort: false, int ttl: 1`

**Comment by EPNW** [comment] 2020-04-24 18:20
Please also document what the dynamic `host` may be, and how `InternetAddress.anyIPv4 ` and `InternetAddress.anyIPv6` influence the behaviour.

**Comment by sortie** [comment] 2020-05-05 13:32
Duplicate of https://github.com/dart-lang/sdk/issues/33721

**Closed by sortie** 2020-05-05 13:32 UTC
Labels: P2, area-library, closed-duplicate, library-io, type-documentation
