### ISSUE TITLE
Analyzer gets confused when class name collides with "dart:ui" class

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#35938] opened 2019-02-14 00:06 UTC
This issue: https://github.com/flutter/flutter/issues/27428

I think is a bug in analyzer, so migrating it here.

**Comment by stereotype441** [comment] 2019-02-14 20:53
Possible duplicate of #35709

**Comment by srawlins** [comment] 2020-06-17 04:31
Yes! This is the same issue I had.

**Comment by srawlins** [comment] 2020-06-17 04:31
Duplicate of #35709

**Closed by srawlins** 2020-06-17 04:31 UTC
Labels: P2, area-analyzer, type-bug
