### ISSUE TITLE
Customer-reported issue with NNBD migration tool: couldn't load dart file /C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart

### ISSUE THREAD

**Issue by eseidel** [dart-lang/sdk#45979] opened 2021-05-10 23:47 UTC
couldn't load dart file /C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart

Attempting to do a null safety migration of:
https://github.com/eseidel/flutter-github-scripts.dart/commit/ec94aa7235defcb6b9089107ddc288f7a3c5c484

With a local diff:
```
diff --git a/pubspec.yaml b/pubspec.yaml
index 1d21a2d..c612396 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -8,7 +8,7 @@ environment:
   sdk: '>=2.7.0 <3.0.0'
 
 dependencies:
-  args: ^1.5.0
+  args: ^2.1.0
   csv: ^5.0.0
   quiver: ^3.0.1
   glob: ^2.0.1
@@ -16,8 +16,8 @@ dependencies:
   intl: ^0.17.0
   graphql: ^5.0.0-nullsafety.4
   columnar_output:
-    git: https://github.com/kf6gpe/columnar-output.dart.git
+    git: https://github.com/eseidel/columnar-output.dart.git

 dev_dependencies:
-  test: ^1.0.0
+  test: ^1.17.3
   pedantic: ^1.11.0
```

Error: FormatException: SyntaxError: Unexpected token < in JSON at position 0

Please fill in the following:

**Name of package being migrated (if public)**:
**What I was doing when this issue occurred**:
**Is it possible to work around this issue**:
**Has this issue happened before, and if so, how often**:

Happened earlier today also attempting to migrate another package (columnar_output).

**Dart SDK version**: 2.14.0-74.0.dev
**Additional details**:

Thanks for filing!

Stacktrace: _auto populated by migration preview tool._

```
FormatException: SyntaxError: Unexpected token < in JSON at position 0
    at Object.b (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:309:3)
    at Object.BS (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:1900:9)
    at by.pW (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:5253:5)
    at http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:3140:8
    at Gs.a (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:1579:72)
    at Gs.$2 (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:4680:23)
    at WM.$1 (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:4672:30)
    at Ji.bv (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:4946:25)
    at rq.$0 (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:4875:11)
    at Object.HZ (http://127.0.0.1:56033/C:/Users/micro/Documents/GitHub/flutter-github-scripts.dart?authToken=06nNZv0HfkY%3D:1627:39)
```

**Comment by stereotype441** [comment] 2021-05-11 21:39
Judging by the exception message (`FormatException: SyntaxError: Unexpected token < in JSON at position 0`) my bet is that the migration preview server is encountering an error while processing a request for JSON data, and for some reason instead of responding with an error appropriately formatted in JSON, it's trying to respond with an HTML error page.  Unforunately, looking at the code for the migration preview server itself I'm having trouble figuring exactly how this could happen.

@eseidel are you by any chance able to reproduce this with Chrome DevTools open?  If so, can you look at the response in the "Network" tab to see if it's in any way human-readable?  That could give us a quick route to diagnosing and fixing this problem.

Failing that I think we would need to add some logging to the preview server to figure out which request it is responding badly to, and what it's trying to send.

Regarding your question on https://github.com/dart-lang/sdk/issues/45202 about whether we have analytics for how common this error is, I'm not sure what analytics we have but I'm pretty certain we don't have that level of detail.  However, all of the other bugs I've marked as duplicates of https://github.com/dart-lang/sdk/issues/45202 have the same error message text (`Error reaching migration preview server.`), which is different from what you saw.  So whatever problem you're experiencing, it doesn't appear to be widespread enough to generate multiple bug reports.

**Comment by eseidel** [comment] 2021-05-11 22:36
http://127.0.0.1:59868/C:/Users/micro/Documents/GitHub/columnar-output.dart?authToken=Ki5VQmAhAtE%3D does point to HTML (it seems to be serving the migration wizard itself).  Not sure if that's expected?

**Comment by eseidel** [comment] 2021-05-11 22:37
http://127.0.0.1:59868/C:/Users/micro/Documents/GitHub/columnar-output.dart?inline=true&authToken=Ki5VQmAhAtE%3D is also the wizard itself.

**Comment by eseidel** [comment] 2021-05-11 22:40
```
[√] Flutter (Channel master, 2.3.0-2.0.pre.90, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.3.0-2.0.pre.90 at C:\Users\micro\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f82dedd5b9 (24 hours ago), 2021-05-10 15:22:50 -0700
    • Engine revision f5b97d0b23
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)
```

**Comment by stereotype441** [comment] 2021-05-11 23:10
@eseidel Oh, interesting.  I didn't realize the error showed up immediately (I was hoping it happened in response to some particular user action in the migration tool).  This will make it more difficult to troubleshoot the problem using Chrome DevTools, since we won't be able to zero in on the particular request that led to the bad response.

Let me spend some time thinking about how to debug this effectively.

**Comment by eseidel** [comment] 2021-05-11 23:14
Refreshing the page shows the error immediately, so should be possible to
debug with tools open during refresh?

**Comment by stereotype441** [comment] 2023-11-21 21:56
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.

**Closed by stereotype441** 2023-11-21 21:56 UTC
Labels: P2, area-migration
