### ISSUE TITLE
Atom editor, dartlang plugin, null coalescing operator: type mismatch

### ISSUE THREAD

**Issue by gchumillas** [dart-lang/sdk#26876] opened 2016-07-13 14:54 UTC
I'm using the Atom IDE in combination with the [dartlang](https://github.com/dart-atom/dartlang) plugin, and the following code doesn't throw any alert:

``` dart
String test = 100 ?? 'another string';
```

Related issue:
https://github.com/dart-atom/dartlang/issues/1065

**Comment by bwilkerson** [comment] 2016-07-13 15:02
Unfortunately, that's the behavior currently defined by the language specification. The static type of `100 ?? 'string'` is the least-upper-bound of `int` and `String`, which is `Object`, and `Object` is assignable to `String` because `String` is a subtype of `Object`.

In either checked mode or strong mode this will produce an exception at runtime, but no warning at analysis time.

**Comment by leafpetersen** [comment] 2016-07-13 16:34
I'd like to fix this in strong mode.  Bug here:  https://github.com/dart-lang/sdk/issues/25368 .

**Comment by munificent** [comment] 2016-12-13 22:51
I'm going to close this as a duplicate of the bug Leaf linked too, since I don't think we will solve this differently outside of strong mode.

**Closed by munificent** 2016-12-13 22:51 UTC
Labels: area-language
