### ISSUE TITLE
Don't report RETURN_OF_INVALID_TYPE when already reported ILLEGAL_ASYNC_RETURN_TYPE

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#41439] opened 2020-04-10 15:52 UTC
Probably also `ILLEGAL_ASYNC_GENERATOR_RETURN_TYPE`, or `ILLEGAL_SYNC_GENERATOR_RETURN_TYPE` - check if we report `RETURN_OF_INVALID_TYPE` in these cases.

**Comment by srawlins** [comment] 2020-04-12 05:04
Looks like a duplicate of #38188. I also don't think we report duplicate errors in generators, since they're just not supposed to return anything.

**Comment by scheglov** [comment] 2020-04-12 05:44
Seems different than https://github.com/dart-lang/sdk/issues/38188, even if in the same are.
The other issue is about saying a wrong type, and this one - about reporting an error at all.

**Closed** 2020-04-13 03:43 UTC
Labels: analyzer-ux, area-analyzer
