### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by MJAN123** [dart-lang/sdk#40693] opened 2020-02-19 19:12 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version , FATAL error: FileSystemException: Exists failed, path = 'C:\Users\Muhammad Jan\AppData\Local\.dartServer\.instrumentation' (OS Error: The file or directory is corrupted and unreadable.
, errno = 1392)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
```

For additional log information, please append the contents of
file://C:\Users\MUHAMM~1\AppData\Local\Temp\report6.txt.

**Comment by srawlins** [comment] 2020-06-12 23:20
Thanks for reporting this issue! This has been previously reported at #37059.

**Comment by srawlins** [comment] 2020-06-12 23:20
Duplicate of #37059

**Closed by srawlins** 2020-06-12 23:20 UTC
Labels: analyzer-crash-report, area-analyzer
