### ISSUE TITLE
@mustCallSuper does not trigger warning with mixins

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/sdk#31458] opened 2017-11-27 22:01 UTC
It might be the intended behavior but still confusing and sad...

```dart
import 'package:meta/meta.dart';

abstract class Base {}

abstract class Mixin {
  @mustCallSuper
  void sideEffect() {
    print('hola mundo!');
  }
}

class Concrete extends Base with Mixin {
  @override
  void sideEffect() {
    print('hello world!'); // No "hola mundo!" in console! no warning from analyzer :(
  }
}
```

**Comment by alexeieleusis** [comment] 2017-11-27 22:12
It is noteworthy mentioning that if from `Concrete.sideEffect`  `super.sideEffect()` is added then the method in the mixin is invoked which means a super class method treatment and therefore the annotation should honor the contract.

**Comment by lrhn** [comment] 2017-11-28 13:55
The ability to call super methods in mixins was never implemented in dart2js, and is removed again in Dart 2, so a mixin won't be able to call a super method.
A different syntax is planned for declaring mixins that can call super methods, but that won't land in Dart 2.0.
(Flutter may get an extension on the removal of the existing feature, until the replacement is ready, since it only uses the VM which did implement the original feature).

**Comment by alexeieleusis** [comment] 2017-11-29 17:28
I think I am not understanding what you say, but what I want seems to work in the VM, DDC and dart2js: if the `sideEffect` method invokes `super.sideEffect()` the one in `Mixin` is invoked and the warning I wanted to have.

**Comment by lrhn** [comment] 2017-11-29 18:22
My bad, I was thinking the override was in the mixin, not in the class extending the mixin application. Do carry on!
(If that *had* been that case, you should still get your warning, but you wouldn't be able to fix it because the mixin method cannot call a super method).

**Comment by alexeieleusis** [comment] 2017-11-29 20:46
Perfect, I was starting to think how to catch it in tests.

My request then I think is legitimate and there is indeed a bug, I want the analyzer to warn on `Concrete.sideEffect` for not invoking the method in the mixin.

**Comment by srawlins** [comment] 2020-09-24 20:23
Duplicate of https://github.com/dart-lang/sdk/issues/29861

**Closed by srawlins** 2020-09-24 20:23 UTC
Labels: analyzer-linter, area-analyzer, type-bug
