### ISSUE TITLE
[vm][flake] Hot reload tries to do API call for kernel compilation after shutdown

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#46949] opened 2021-08-19 16:49 UTC
```
$ for i in `seq 20`; do out/DebugX64/dart --hot-reload-test-mode --no-enable-isolate-groups --ignore-unrecognized-flags --packages=/usr/local/google/home/dacoharkes/dart-sdk/sdk/.packages /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/generated_tests/lib_2/isolate/message3_test_fun.dart &
> done

...

../../runtime/vm/kernel_isolate.cc: 439: error: expected: port_ != ILLEGAL_PORT
version=2.15.0-edge.19d12d18d66ea8e6208a920dd0e257cf8d4a0f64 (be) (Wed Aug 18 02:30:23 2021 +0000) on "linux_x64"
pid=1847550, thread=1847750, isolate_group=echoMain(0x55aa490b1800), isolate=(nil)((nil))
isolate_instructions=55aa469cefe0, vm_instructions=55aa469cefe0
  pc 0x000055aa46dc6aec fp 0x00007f16db67de50 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x000055aa469cf194 fp 0x00007f16db67df30 dart::Assert::Fail(char const*, ...)+0x84
  pc 0x000055aa46c85162 fp 0x00007f16db67e060 out/DebugX64/dart+0x2137162
  pc 0x000055aa46c65469 fp 0x00007f16db67e310 dart::IsolateGroupReloadContext::Reload(bool, char const*, char const*, unsigned char const*, long)+0xd79
  pc 0x000055aa46c5b4d0 fp 0x00007f16db67e390 dart::IsolateGroup::ReloadSources(dart::JSONStream*, bool, char const*, char const*, bool)+0x1c0
  pc 0x000055aa46e36d7c fp 0x00007f16db67e560 dart::DRT_StackOverflow(dart::NativeArguments)+0x39c
  pc 0x00007f16e7702812 fp 0x00007f16db67e5a0 Unknown symbol
  pc 0x00007f16dd32b03d fp 0x00007f16db67e5d0 Unknown symbol
  pc 0x00007f16dd3258ce fp 0x00007f16db67e620 Unknown symbol
  pc 0x00007f16dd3271d1 fp 0x00007f16db67e668 Unknown symbol
  pc 0x00007f16dd326d35 fp 0x00007f16db67e6a8 Unknown symbol
  pc 0x00007f16dd326853 fp 0x00007f16db67e6e8 Unknown symbol
  pc 0x00007f16dd32644e fp 0x00007f16db67e728 Unknown symbol
  pc 0x00007f16dd32610f fp 0x00007f16db67e768 Unknown symbol
  pc 0x00007f16dd325ee2 fp 0x00007f16db67e7a8 Unknown symbol
  pc 0x00007f16dd31f891 fp 0x00007f16db67e810 Unknown symbol
  pc 0x00007f16dd31f130 fp 0x00007f16db67e850 Unknown symbol
  pc 0x00007f16e7702c9d fp 0x00007f16db67e8c8 Unknown symbol
  pc 0x000055aa46c1e534 fp 0x00007f16db67e960 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x134
  pc 0x000055aa46c1e0fe fp 0x00007f16db67e9d0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x16e
  pc 0x000055aa46c212f7 fp 0x00007f16db67ea30 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x117
  pc 0x000055aa46c57f52 fp 0x00007f16db67eb20 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x492
  pc 0x000055aa46c9b248 fp 0x00007f16db67ebb0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x218
  pc 0x000055aa46c9c024 fp 0x00007f16db67ec30 dart::MessageHandler::TaskCallback()+0x344
  pc 0x000055aa46e7e3cb fp 0x00007f16db67ecd0 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1fb
  pc 0x000055aa46e7ed67 fp 0x00007f16db67ed20 dart::ThreadPool::Worker::Main(unsigned long)+0x147
  pc 0x000055aa46dbe004 fp 0x00007f16db67ee70 out/DebugX64/dart+0x2270004
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f16db67e5a0) pc(0)]
[dart     : sp(0x7f16db67e5b0) fp(0x7f16db67e5d0) pc(0x7f16dd32b03d) dart:async__PendingEvents@4048458_schedule ]
[dart     : sp(0x7f16db67e5e0) fp(0x7f16db67e620) pc(0x7f16dd3258ce) dart:async__BufferingStreamSubscription@4048458__checkState@4048458 ]
[dart     : sp(0x7f16db67e630) fp(0x7f16db67e668) pc(0x7f16dd3271d1) dart:async__BufferingStreamSubscription@4048458__sendData@4048458 ]
[dart     : sp(0x7f16db67e678) fp(0x7f16db67e6a8) pc(0x7f16dd326d35) dart:async__BufferingStreamSubscription@4048458__add@4048458 ]
[dart     : sp(0x7f16db67e6b8) fp(0x7f16db67e6e8) pc(0x7f16dd326853) dart:async__SyncStreamController@4048458__sendData@4048458 ]
[dart     : sp(0x7f16db67e6f8) fp(0x7f16db67e728) pc(0x7f16dd32644e) dart:async__StreamController@4048458__add@4048458 ]
[dart     : sp(0x7f16db67e738) fp(0x7f16db67e768) pc(0x7f16dd32610f) dart:async__StreamController@4048458_add ]
[dart     : sp(0x7f16db67e778) fp(0x7f16db67e7a8) pc(0x7f16dd325ee2) dart:async__StreamController@4048458_add_add ]
[dart     : sp(0x7f16db67e7b8) fp(0x7f16db67e810) pc(0x7f16dd31f891) dart:core__Closure@0150898_dyn_call ]
[dart     : sp(0x7f16db67e820) fp(0x7f16db67e850) pc(0x7f16dd31f130) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x7f16db67e860) fp(0x7f16db67e8c8) pc(0x7f16e7702c9d)]
unittest-suite-success
1
unittest-suite-success
unittest-suite-success
unittest-suite-success
unittest-suite-success
unittest-suite-success
```

Started after check was added in 1f405bf163c64ec732c3a6d604033da0b439628b, reproduced on 19d12d18d66ea8e6208a920dd0e257cf8d4a0f64.

Thread 2 trying to do a `Dart_NewNativePort` API call:

`Dart::SetActiveApiCall()` fails because `state_ != InitializationState::kInitialized`.

```
dart::DartInitializationState::ResetInUse(dart::DartInitializationState * this) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/dart.cc:168)
Dart_NewNativePort(const char * name, Dart_NativeMessageHandler handler) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/native_api_impl.cc:97)
dart::KernelCompilationRequest::KernelCompilationRequest(dart::KernelCompilationRequest * this) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/kernel_isolate.cc:434)
dart::KernelIsolate::CompileToKernel(const char * script_uri, const uint8_t * platform_kernel, intptr_t platform_kernel_size, int source_file_count, Dart_SourceFile * source_files, const char * package_config, const char * multiroot_filepaths, const char * multiroot_scheme, Dart_KernelCompilationVerbosityLevel verbosity) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/kernel_isolate.cc:1050)
dart::IsolateGroupReloadContext::CompileToKernel(dart::IsolateGroupReloadContext * this, bool force_reload, const char * packages_url, const uint8_t ** kernel_buffer, intptr_t * kernel_buffer_size) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/isolate_reload.cc:1010)
dart::IsolateGroupReloadContext::Reload(dart::IsolateGroupReloadContext * this, bool force_reload, const char * root_script_url, const char * packages_url, const uint8_t * kernel_buffer, intptr_t kernel_buffer_size) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/isolate_reload.cc:588)
dart::IsolateGroup::ReloadSources(dart::IsolateGroup * this, dart::JSONStream * js, bool force_reload, const char * root_script_url, const char * packages_url, bool dont_delete_reload_context) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/isolate.cc:2044)
dart::HandleStackOverflowTestCases(dart::Thread * thread) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/runtime_entry.cc:2739)
dart::DRT_HelperStackOverflow(dart::Isolate * isolate, dart::Thread * thread) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/runtime_entry.cc:2881)
dart::DRT_StackOverflow(dart::NativeArguments arguments) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/runtime_entry.cc:2832)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
```

After thread 1 has started sutting down the VM:

And has set `state_ = InitializationState::kCleaningup;`.

```
dart::DartInitializationState::SetCleaningup(dart::DartInitializationState * this) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/dart.cc:141)
dart::Dart::Cleanup() (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/vm/dart.cc:627)
dart::bin::main(int argc, char ** argv) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/bin/main.cc:1321)
main(int argc, char ** argv) (/usr/local/google/home/dacoharkes/dart-sdk/sdk/runtime/bin/main.cc:1352)
```

Reproducable in RR:

```
for i in `seq 20`; do rr record -- out/DebugX64/dart --hot-reload-test-mode --no-enable-isolate-groups --ignore-unrecognized-flags --packages=/usr/local/google/home/dacoharkes/dart-sdk/sdk/.packages /usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/generated_tests/lib_2/isolate/message3_test_fun.dart &
> done
```

**Comment by a-siva** [comment] 2021-08-19 20:44
This is a duplicate of https://github.com/dart-lang/sdk/issues/46944 and https://github.com/dart-lang/sdk/issues/46931

**Closed by a-siva** 2021-08-19 20:44 UTC
Labels: area-vm, closed-duplicate, crash
