### ISSUE TITLE
Dart Analyzer Error 	Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by JohanLeDong** [dart-lang/sdk#35099] opened 2018-11-08 00:55 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 182.3208.16.33.4924367`
- `2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68`
- `AI-182.3208.16.33.4924367, JRE 1.8.0_152-release-1136-b05x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\dongln\AppData\Local\Temp\report1.txt

```
Dart analysis server, SDK version 2.1.0-edge.b99bcfd3099f0d32e39287160a9539e878cb0b68, server version 1.20.5, error: Analysis failed: C:\Users\dongln\servey\lib\widgets\grid.dart
Element mismatch in C:\Users\dongln\servey\lib\widgets\grid.dart at {(List<Item>, int) → dynamic saveItems}
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:54:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:576:31)
#2      LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:107:9)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-11-13 23:55
Duplicate of #33930

**Closed by stereotype441** 2018-11-13 23:55 UTC
Labels: analyzer-crash-report, analyzer-server, area-analyzer, crash
