### ISSUE TITLE
Migrator should handle extensions

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#40023] opened 2020-01-08 20:17 UTC
The NNBD migrator should handle extensions. This means, for example:

* change the `on` type of an extension declaration to be nullable if
  * [x] an extension method is called on a nullable value
  * [ ] an extension application is applied to a nullable value
* [ ] add runtime null checks to `this` where needed

**Comment by stereotype441** [comment] 2020-01-16 15:16
Duplicate of #39387

**Closed by stereotype441** 2020-01-16 15:16 UTC
Labels: NNBD, analyzer-nnbd-migration, area-analyzer
