### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by vishnuTelco** [dart-lang/sdk#38165] opened 2019-09-02 05:25 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.6262.58`
- `2.4.0`
- `IC-192.6262.58, JRE 11.0.3+12-b304.39x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-58-generic, screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.4.0, server version 1.27.1, error: Analysis failed: /home/vinu/Documents/project/test/widget_test.dart context: exception_20190902_105152_747
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5535:5)
#1      TypeProviderForLink.stringType (package:analyzer/src/summary/link.dart:5523:23)
#2      StaticTypeAnalyzer.visitSimpleStringLiteral (package:analyzer/src/generated/static_type_analyzer.dart:1069:56)
#3      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9148:49)
#4      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4772:10)
#5      UnifyingAstVisitor.visitSimpleStringLiteral (package:analyzer/dart/ast/visitor.dart:3398:59)
#6      SimpleStringLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:9148:49)
#7      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2551:16)
#8      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5357:36)
#9      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5200:7)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
#11     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
#12     VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5633:47)
#13     FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2617:22)
#14     ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:907:20)
#15     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1632:20)
#16     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3840:12)
#17     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3540:15)
#18     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3480:7)
#19     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
#20     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
#21     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
#22     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
#23     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
#24     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3513:42)
#25     Linker.link (package:analyzer/src/summary/link.dart:4045:35)
#26     _relink (package:analyzer/src/summary/link.dart:311:74)
#27     link (package:analyzer/src/summary/link.dart:125:3)
#28     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:217:25)
#29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#30     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:216:12)
#31     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#32     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1594:29)
#33     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1405:30)
#34     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#35     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#36     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#37     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#38     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#39     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#40     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#41     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#42     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#48     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#50     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#51     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#52     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#53     new Future.sync (dart:async/future.dart:224:31)
#54...
```

For additional log information, please append the contents of
file:///tmp/report1.txt.

**Comment by srawlins** [comment] 2019-09-05 03:53
Thanks for reporting this issue! This was previously reported at #35437; please follow along there.

**Comment by srawlins** [comment] 2019-09-05 03:53
Duplicate of #35437

**Closed by srawlins** 2019-09-05 03:53 UTC
Labels: area-analyzer
