### ISSUE TITLE
CFE: crash on recursive const constructor

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#36216] opened 2019-03-14 17:59 UTC
```
class C {
  Object inner;
  const C() : inner = const C();
```

This simply crashes.

According to @lrhn it is not allowed because const expressions cannot depend on themselves. So this crash is not preventing a valid pattern but its also not very user friendly.

**Comment by srawlins** [comment] 2019-09-12 00:47
This no longer crashes, in Dart 2.6.0-dev.0.0, not in `dart`, nor in `dartanalyzer`:

```none
$ dartanalyzer 36216.dart 
Analyzing 36216.dart...
  error • Can't define a const constructor for a class with non-final fields. • 36216.dart:3:3 • const_constructor_with_non_final_field
1 error found.
```

```none
$ dart 36216.dart 
36216.dart:3:9: Error: Constructor is marked 'const' so all fields must be final.
  const C() : inner = const C();
        ^
36216.dart:2:10: Context: Field isn't final, but constructor is 'const'.
  Object inner;
         ^
36216.dart:3:29: Error: Constant evaluation error:
  const C() : inner = const C();
                            ^
36216.dart:3:29: Context: Constant expression depends on itself.
  const C() : inner = const C();
                            ^
```

Fixed?

**Comment by munificent** [comment] 2019-09-27 22:22
> Fixed?

Nope. You can address that error by changing the example program to:

```dart
class C {
  final Object inner;
  const C() : inner = const C();
}
```

If I run that on the VM, I get:

```
Illegal instruction: 4
```

**Comment by eernstg** [comment] 2019-09-30 08:31
I think the 'illegal instruction' behavior may have been fixed recently (at least, I don't get that response). Here's what I get with [the corrected program](https://github.com/dart-lang/sdk/issues/36216#issuecomment-536114572) with `dart` from commit 942af5bd62496330ab24720333cab08a2e8e5e07:

```
n026.dart:3:29: Error: Constant evaluation error:
  const C() : inner = const C();
                            ^
n026.dart:3:29: Context: Constant expression depends on itself.
  const C() : inner = const C();
                            ^
```

@jensjoha, it looks like we could close this. Do you think there are any known issues with cyclic constant detection today?

**Comment by jensjoha** [comment] 2019-09-30 08:42
Constant evaluation is actually @askeksa-google so I'll refer to him.

**Comment by askeksa-google** [comment] 2019-09-30 09:12
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/34189

**Closed by askeksa-google** 2019-09-30 09:12 UTC
Labels: area-front-end, type-bug

**Comment by askeksa-google** [comment] 2019-09-30 09:13
I think @munificent might have hit some other issue. The example is rejected by the FE.
