### ISSUE TITLE
Migration tool complaining that SDK does not enable NNBD when trying to migrate flutter

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#42171] opened 2020-06-03 12:56 UTC
Following a tip from @a14n, I tried to migrate flutter using the following steps:
```
cd ~/tmp
mkdir flutter
cd flutter
wget https://storage.googleapis.com/flutter_infra/releases/dev/linux/flutter_linux_1.19.0-3.0.pre-dev.tar.xz
tar xvJf flutter_linux_1.19.0-3.0.pre-dev.tar.xz
cd flutter
export PATH="`pwd`/flutter/bin:$PATH"
cd ../flutter/packages/flutter
flutter pub get
dart migrate --skip-pub-outdated
```
This produced the error message:
```
Bad state: Analysis seems to have an SDK without NNBD enabled.
```
This shouldn't be possible, since the SDK unfork has already happened, so Flutter's SDK should have NNBD enabled.

**Comment by a14n** [comment] 2020-06-05 12:31
Looks unrelated to Flutter. As soon I try `dart migrate` on a package with at least 1 dart file I get the error above. It only work in empty dir (which is quite easy to migrate :D)

**Comment by MichaelRFairhurst** [comment] 2020-06-05 18:54
@a14n what SDK version are you using? What command?

We can migrate non-flutter packages well.

I haven't updated the ticket, but there are two issues for flutter. One is that sky_engine was not unforked. The other is that the package allow list is not working for sky_engine.

Aside from those issues, we currently know of nothing preventing migration of non-flutter packages, and that would be a P0 for us!

**Comment by scheglov** [comment] 2020-06-05 19:04
BTW, https://dart-review.googlesource.com/c/sdk/+/150169 added support to analyzer for `allowed_experiments.json` in `sky_engine`.

**Comment by a14n** [comment] 2020-06-05 19:26
@MichaelRFairhurst I also tested on master branch of the dartSDK on `flutter_goldens_client` that has only _simple_ dependencies:

```
flutter/packages/flutter_goldens_client$ dart --version
Dart VM version: 2.9.0-edge.249cb9c974e13177fe5f76b390e2569ece79185f (be) (Fri Jun 5 01:41:23 2020 +0000) on "linux_x64"
flutter/packages/flutter_goldens_client$ dart migrate --skip-pub-outdated
Migrating /home/aar-dw/perso/dev/dart/flutter/flutter/packages/flutter_goldens_client

Generating migration suggestions... /[                                                                                                                            [-----------------------------------------------------                                                                                                           ]
Bad state: Analysis seems to have an SDK without NNBD enabled.
```

**Comment by MichaelRFairhurst** [comment] 2020-06-05 21:41
Do you have any local changes to flutter_goldens_client etc?

I could not reproduce. I checked out that exact revision of the SDK. My flutter repo is at `ab68721a5da013dff6a08854bdba5e1f3206f9cf`.

```dart
~/projects/dart/flutter/packages/flutter_goldens_client λ ~/projects/dart/sdk/out/ReleaseX64/dart-sdk/bin/dart migrate --skip-pub-outdated
Migrating /home/mfairhurst/projects/dart/flutter/packages/flutter_goldens_client

Generating migration suggestions... /[                                                                                                                                                                                                                                                                                                                                                                                                                            
No analysis issues found.
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]

View the migration suggestions by visiting:

  http://localhost:43839/home/mfairhurst/projects/dart/flutter/packages/flutter_goldens_client?authToken=HCn5fd3OUww%3D

Use this interactive web view to review, improve, or apply the results.

When finished with the preview, hit ctrl-c to terminate this process.
^C
~/projects/dart/flutter/packages/flutter_goldens_client ~/projects/dart/sdk/out/ReleaseX64/dart-sdk/bin/dart --version
Dart VM version: 2.9.0-edge.249cb9c974e13177fe5f76b390e2569ece79185f (be) (Fri Jun 5 01:41:23 2020 +0000) on "linux_x64"
```

**Comment by a14n** [comment] 2020-06-06 17:12
I really don't know what is going on. I don't have any local changes in `flutter_goldens_client`.

Didn't you see the error with the following commands:

```
git clone https://github.com/flutter/flutter.git
cd flutter
export PATH="$PWD/bin:$PATH"
flutter update-packages
cd packages/flutter_goldens_client/
dart migrate --skip-pub-outdated
```

I get:

```
$ dart migrate --skip-pub-outdated
Migrating /home/a14n/tmp/flutter/flutter/packages/flutter_goldens_client

Generating migration suggestions... /[                                                                                                                                                                                    [------------------------------------------------------------------------                                                                                                                                                ]
Bad state: Analysis seems to have an SDK without NNBD enabled.
```

In a empty dir the migration starts correctly:

```
#in flutter/ with the same $PATH
mkdir mydir
cd mydir
dart migrate --skip-pub-outdated
```

outputs:

```
Migrating /home/a14n/tmp/flutter/flutter/mydir

Generating migration suggestions... /[                                                                                                                                                                                                                                                                                                                                                                                                              
No analysis issues found.
[------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]

View the migration suggestions by visiting:

  http://localhost:45625/home/a14n/tmp/flutter/flutter/mydir?authToken=T5QBdShtluk%3D

Use this interactive web view to review, improve, or apply the results.

When finished with the preview, hit ctrl-c to terminate this process.
```

Once the link opened I tried to add an empty `lib/a.dart` file and click on _Rerun from sources_ . I get the following error:


```
#0      NullabilityMigrationImpl._sanityCheck (package:nnbd_migration/src/nullability_migration_impl.dart:196:7)
#1      NullabilityMigrationImpl.prepareInput (package:nnbd_migration/src/nullability_migration_impl.dart:143:5)
#2      NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:225:19)
#3      _FixCodeProcessor.runFirstPhase.<anonymous closure> (package:nnbd_migration/migration_cli.dart:807:21)
#4      _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:764:30)
<asynchronous suspension>
#5      _FixCodeProcessor.runFirstPhase (package:nnbd_migration/migration_cli.dart:796:11)
<asynchronous suspension>
#6      MigrationCli._rerunFunction (package:nnbd_migration/migration_cli.dart:588:29)
#7      NonNullableFix.rerun (package:nnbd_migration/src/front_end/non_nullable_fix.dart:254:24)
#8      PreviewSite.rerunMigration (package:nnbd_migration/src/preview/preview_site.dart:326:41)
#9      PreviewSite.handlePostRequest (package:nnbd_migration/src/preview/preview_site.dart:185:15)
#10     HttpPreviewServer._handlePostRequest (package:nnbd_migration/src/preview/http_preview_server.dart:94:23)
#11     HttpPreviewServer._handleServer.<anonymous closure> (package:nnbd_migration/src/preview/http_preview_server.dart:104:15)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#16     _StreamController._add (dart:async/stream_controller.dart:655:7)
#17     _StreamController.add (dart:async/stream_controller.dart:597:5)
#18     _HttpServer._handleRequest (dart:_http/http_impl.dart:2874:19)
#19     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2629:19)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#23     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#24     _StreamController._add (dart:async/stream_controller.dart:655:7)
#25     _StreamController.add (dart:async/stream_controller.dart:597:5)
#26     _HttpParser._headersEnd (dart:_http/http_parser.dart:393:19)
#27     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#28     _HttpParser._parse (dart:_http/http_parser.dart:323:7)
#29     _HttpParser._onData (dart:_http/http_parser.dart:852:5)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#34     _StreamController._add (dart:async/stream_controller.dart:655:7)
#35     _StreamController.add (dart:async/stream_controller.dart:597:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#37     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#41     _StreamController._add (dart:async/stream_controller.dart:655:7)
#42     _StreamController.add (dart:async/stream_controller.dart:597:5)
#43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by a14n** [comment] 2020-06-08 08:43
I just tried in a Docker container the same commands I tried in my previous comment  and it seems to work. So it looks like I have something on my host that completely mess up the migrate command. :-(

**Comment by a14n** [comment] 2020-06-08 11:46
I think I found the cause of this issue.

On my machine I have several Dart versions (particullarly the last stable release and another one packaged with flutter). In don't remember why I needed it but I have a `DART_SDK` environment variable that was pointing to the last stable version (2.8.x). It looks like this env var causes the issue. Removing it make the migration tool start.

It is disturbing because I used a `dart` executable from flutter and I didn't expect those interaction with the var env `DART_SDK`.

**Comment by stereotype441** [comment] 2020-06-08 14:55
> I think I found the cause of this issue.
> 
> On my machine I have several Dart versions (particullarly the last stable release and another one packaged with flutter). In don't remember why I needed it but I have a `DART_SDK` environment variable that was pointing to the last stable version (2.8.x). It looks like this env var causes the issue. Removing it make the migration tool start.
> 
> It is disturbing because I used a `dart` executable from flutter and I didn't expect those interaction with the var env `DART_SDK`.

Ok, the explanation with the `DART_SDK` environment variable makes sense.  When the analyzer (and hence the migration tool) sees this environment variable, it assumes that its usual mechanism for locating the SDK won't work, so it just blindly uses the SDK from the environment variable :)

**Comment by a14n** [comment] 2020-06-08 15:01
It could have helped to see a log (in verbose mode) indicating the use of this `DART_SDK`.

I think you can close this issue.

Thanks for your help.

**Comment by stereotype441** [comment] 2020-06-08 15:03
Yeah, a log entry would be nice.  I'm not going to close it yet, because I still want to verify that the repro I initially found (at the top of the bug report) has been fixed.  I'll follow up hopefully later today.

**Comment by stereotype441** [comment] 2020-06-08 17:37
After discussion with @MichaelRFairhurst we believe this is all fixed now; leaving open for a bit as a reminder to create a log entry.

**Comment by MichaelRFairhurst** [comment] 2020-06-11 17:20
The warning is now submitted, closing

**Closed by MichaelRFairhurst** 2020-06-11 17:20 UTC
Labels: NNBD, analyzer-nnbd-migration, area-analyzer
