### ISSUE TITLE
App hangs on unhandled exception like it is in debug mode

### ISSUE THREAD

**Issue by JFixby** [dart-lang/sdk#30369] opened 2017-08-08 16:13 UTC
Developing in IDEA.
Run app in normal mode.

When there is an unhandled exception the app hangs and waits for user click the "continue execution"-button like it is in debug mode. After clicking the button the program continues until it bumps into the unhandled exception again.

Possibly Flutter-related issue.

![image](https://user-images.githubusercontent.com/1580663/29084879-b293bc20-7c6d-11e7-9ec2-9292080ecf7b.png)

**Comment by alexander-doroshko** [comment] 2017-08-08 16:22
Hm, there's no "continue execution" button when you run in normal mode, is there? 
On unhandled exception, the app simply prints trace and exits. Looks like you simply rerun it from the start.

**Comment by JFixby** [comment] 2017-08-08 16:24
It is the ```Resume program```-button.
Also it highlights the code line with the exception, which may look like 
```Dart
throw e;
```

**Comment by JFixby** [comment] 2017-08-08 16:31
@alexander-doroshko yes the button is not present and that is also the problem, since it basically stops the execution and there is no way to resume, unless by chance the Debug view is open.

**Comment by alexander-doroshko** [comment] 2017-08-08 16:55
@JFixby According to your screenshots you do Debug the app, not Run :). When you **Run** there's no Debug tool window at all, there's Run tool window.
The default (and currently the only) behavior is to suspend on unhandled exceptions. Since version 2017.2.2 there will be an option: suspend on unhandled exceptions, suspend on all exceptions or never suspend on exceptions.

So far all you describe is an expected behavior.

**Comment by JFixby** [comment] 2017-08-08 17:07
Here is the Run panel:

![image](https://user-images.githubusercontent.com/1580663/29084262-b7b3346c-7c6b-11e7-9fd2-a0d0e65be0ec.png)

Debug mode is disabled the yet app is suspended.

I can't resume it because the debug tool view is not av after the IDEA was restarted. However it is possible to activate the Debug tool view by running the app in debug mode. Running normal mode after that will not disable the debug view.

This is what the panel would look like in debug mode:

![image](https://user-images.githubusercontent.com/1580663/29084547-a142b2ba-7c6c-11e7-865f-26e3854989dd.png)

**Comment by alexander-doroshko** [comment] 2017-08-08 17:24
Originally there was neither 'Flutter' word nor a screenshot with Flutter icon in the description, so I implicitly decided that this issue is about running an app in the Dart VM (Dart Command Line App configuration in the IDE). I can speak about the Dart plugin only, it runs the app on Run button and debugs on Debug button.
Indeed this seems to be a [Flutter plugin](https://github.com/flutter/flutter-intellij) related question. Sorry for the noise.
// cc @devoncarew @pq

**Comment by pq** [comment] 2017-08-08 17:29
@JFixby : what version of the Flutter Plugin do you have installed?

Also, could you include the output of running `flutter doctor`?  (From the command-line or `Tools > Flutter > Flutter Doctor`.)

Thanks!

**Comment by JFixby** [comment] 2017-08-08 17:33
```
C:\Program Files (x86)\Far Manager>flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.3.9600], locale en-US, channel master)
    • Flutter at D:\AndroidDev\flutter
    • Framework revision 1d353f6dcb (3 hours ago), 2017-08-08 16:38:47 +0200
    • Engine revision ff50334587
    • Tools Dart version 1.25.0-dev.7.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at D:\AndroidSDK
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Java\jdk1.8.0_131\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

[-] Android Studio (version 2.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3317.48
```

**Comment by devoncarew** [comment] 2017-08-08 17:39
closing (moved to https://github.com/flutter/flutter-intellij/issues/1271)

**Closed by devoncarew** 2017-08-08 17:39 UTC
