### ISSUE TITLE
Analyzer with non-nullable experiment enabled disallows implicit cast from dynamic

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#39054] opened 2019-10-22 17:21 UTC
When I analyze this code with `--enable-experiment=non-nullable`:

```dart
foo() {
  dynamic d;
  int i = d;
}
```

I get:

```
3:11: A value of type 'dynamic' can't be assigned to a variable of type 'int'.
```

My understanding is that we're removing implicit downcasts with NNBD but that implicit casts from dynamic are still allowed so there should be no error here.

cc @leafpetersen @lrhn

**Comment by lrhn** [comment] 2019-10-23 07:35
Agree.

**Comment by scheglov** [comment] 2019-10-27 23:15
I cannot reproduce this.
```
scheglov@scheglov-macbookpro2:~/tmp/000$ dartanalyzer --enable-experiment=non-nullable test.dart
Analyzing test.dart...
  hint • The value of the local variable 'i' isn't used. • test.dart:3:7 • unused_local_variable
1 hint found.
```

Could you try with newer SDK?

**Comment by leafpetersen** [comment] 2019-10-29 20:44
I also can't reproduce.  Closing, thanks for taking a look!

**Comment by munificent** [comment] 2019-11-01 20:33
I can't repro either. Looks like we're good now. :)

**Closed** 2019-11-01 20:48 UTC
Labels: NNBD, area-analyzer, type-bug
