### ISSUE TITLE
Improve async stack traces.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#28175] opened 2016-12-21 18:11 UTC
Run the following code on the VM:

```dart
import 'dart:async';
import 'dart:io';

void main() async {
  await new File('doesntexist').readAsString();
}
```

```none
$ dart x.dart
Unhandled exception:
FileSystemException: Cannot open file, path = 'doesntexist' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

It takes the developer some time to walk through the stack trace and see that he has been rickrolled. Instead of this stack trace, the Dart VM should helpfully inform the developer that it has no idea where the attempt was made to open the file, and that the developer is on his/her own.

**Comment by kevmoo** [comment] 2016-12-21 19:32
...or recommend `pkg/stack_trace`.

This is something we've heard a number of times – it'd be nice if this was something the VM could offer directly.

**Comment by zanderso** [comment] 2016-12-21 22:27
@kevmoo, @johnmccutchan is working on this. I assume he can mark this as a dupe of some other issue, but I'll go ahead and edit the title to make it clear that this isn't specific to FileSystemExceptions.

**Comment by srawlins** [comment] 2016-12-22 01:42
Thanks @zanderso , I figured this was a broader issue but wasn't sure how to categorize it.

Isn't there somethings particularly bad about uncatchable errors? For example, here's an async error that at least tells me `x.dart` is involved (even if it can't give me a line number 😦 :

```none
$ cat x.dart
import 'dart:async';
import 'dart:io';

void main() async {
  await new Future.error('boo');
  //await new File('doesntexist').readAsString();
}
$ dart x.dart
Unhandled exception:
boo
#0      main.<main_async_body> (file:///Users/srawlins/code/dart-markdown/x.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1410)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by mit-mit** [comment] 2017-01-03 16:14
Closing this as a dupe of https://github.com/dart-lang/sdk/issues/27661

**Closed by mit-mit** 2017-01-03 16:14 UTC
Labels: area-vm, paramount-17q1
