### ISSUE TITLE
Analyzer Error 

### ISSUE THREAD

**Issue by kostaa** [dart-lang/sdk#33247] opened 2018-05-26 17:55 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-181.5087.20`
- `2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822`
- `IC-181.5087.20, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1680x1050`

# Exception

```
Dart analysis server, SDK version 2.0.0-edge.46ab040e589adc5200370dec7952ce5150850822, server version 1.20.3, error: NoSuchMethodError: Class 'DynamicElementImpl' has no instance getter 'supertype'.
Receiver: Instance of 'DynamicElementImpl'
Tried calling: supertype
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:478:40)
#2      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:450:9)
#3      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:496:15)
#4      InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205:9)
#5      InstanceMemberInferrer._computeFieldOverrideType (package:analyzer/src/task/strong_mode.dart:114:28)
#6      InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:414:9)
#7      InstanceMemberInferrer._inferClass.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:319:11)
#8      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:318:29)
#10     InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:88:9)

**Comment by bwilkerson** [comment] 2018-05-27 15:18
Duplicate of #32037.

**Closed by bwilkerson** 2018-05-27 15:18 UTC
Labels: analyzer-server, area-analyzer
