### ISSUE TITLE
co19/LibTest/io/Link/create_A06{_t01,_t03} failing on Windows

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#53777] opened 2023-10-17 10:44 UTC
There are new test failures on [[co19] Roll co19 to 9d347fdf209cc343ca7fdf94a40deea88fa28896](https://github.com/dart-lang/sdk/commit/bb285978106c8b1bb515871bc1cc0f6dbd811163).

The tests
```
co19/LibTest/io/Link/create_A06_t01 RuntimeError (expected Pass)
co19/LibTest/io/Link/create_A06_t03 RuntimeError (expected Pass)
```
are failing on configurations
```
vm-aot-win-debug-x64c
vm-aot-win-product-x64
vm-aot-win-release-x64
vm-win-debug-x64
vm-win-debug-x64c
vm-win-release-ia32
vm-win-release-x64
```

Error from the logs ([`co19/LibTest/io/Link/create_A06_t01`](https://dart-ci.appspot.com/log/vm-win-release-x64/vm-win-release-x64/2734/co19/LibTest/io/Link/create_A06_t01), [`co19/LibTest/io/Link/create_A06_t03`](https://dart-ci.appspot.com/log/vm-win-release-x64/vm-win-release-x64/2734/co19/LibTest/io/Link/create_A06_t03)) is similar for both:
```
stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <directory>, actual: <link>) fails.
#0      _fail (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect.dart:18:5)
#1      Expect.equals (file:///C:/b/s/w/ir/tests/co19/src/Utils/expect_common.dart:15:7)
#2      _main.<anonymous closure> (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/create_A06_t01.dart:61:12)
<asynchronous suspension>
#3      _main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/create_A06_t01.dart:59:3)
<asynchronous suspension>
#4      inSandbox (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/file_utils.dart:23:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/tests/co19/src/LibTest/io/Link/create_A06_t01.dart:48:3)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n vm-win-release-x64 co19/LibTest/io/Link/create_A06_t01
```

See https://github.com/dart-lang/co19/pull/2299 for PR that changed/added these tests.

/cc @sgrekhov

**Comment by sgrekhov** [comment] 2023-10-17 11:11
I don't see anything wrong with the tests.  There is some issue with relative links to a directories on Windows. See https://github.com/dart-lang/sdk/issues/53689. So, I'm closing it as a duplicate of #53689. Feel free to reopen

**Closed by sgrekhov** 2023-10-17 11:11 UTC
Labels: area-test, os-windows, gardening
