### ISSUE TITLE
Enums are not passed to isolates correctly in dart2js

### ISSUE THREAD

**Issue by hermanbergwerf** [dart-lang/sdk#26825] opened 2016-07-04 10:48 UTC
This issue has been bothering me for a while now while working with isolates. To reproduce run:

```dart
import 'dart:async';
import 'dart:isolate';

enum MyEnum { foo, bar }

void checkEnum(MyEnum value) {
  print(value); // Prints MyEnum.foo
  print(value == MyEnum.foo); // Prints false
  print(value.index == MyEnum.foo.index); // Prints true
  print(MyEnum.values[value.index] == MyEnum.foo); // Prints true
}

Future main() async {
  await Isolate.spawn(checkEnum, MyEnum.foo);
}
```

(unfortunately it doesn't run in DartPad, but it does with dart2js)

**Comment by lrhn** [comment] 2016-07-04 10:59
This is inarguably bad. Dart2js should enforce that new instances of an enum class isn't created.

The VM generally canonicalizes const values sent through a `SendPort`. You can only send an enum to an isolate created using `Isolate.spawn`, so it's guaranteed that the same constant was declared in the receiving isolate. While I'm not completely convinced that it's always a good idea, it definitely is for enums where the class should prevent creation of new instances not identical to the original enum values.

(Cloning object without going through a constructor gives these problems, but it's all our current serialization/deserialization can do).

This looks like a duplicate of #23244.

**Comment by floitschG** [comment] 2016-08-17 14:17
Yes. duplicate.

**Closed by floitschG** 2016-08-17 14:17 UTC
Labels: area-dart2js, Type: bug
