### ISSUE TITLE
ICData::NumberOfChecks() unreachable code on arm

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#34997] opened 2018-10-31 11:06 UTC
```dart
FAILED: dartk-vm release_arm64 service/evaluate_function_type_parameters_test
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 01:03.000527s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --ignore-unrecognized-flags --packages=/b/build/slave/target-arm64-vm-linux-release-be/build/sdk/.packages /b/build/slave/target-arm64-vm-linux-release-be/build/sdk/runtime/observatory/tests/service/evaluate_function_type_parameters_test.dart

exit code:
255

stdout:
** Launching SERVICE_TEST_TESTEE=true out/ReleaseXARM64/dart -DDART_SERVICE_USE_AUTH=false --profiler --ignore-unrecognized-flags --packages=/b/build/slave/target-arm64-vm-linux-release-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/target-arm64-vm-linux-release-be/build/sdk/runtime/observatory/tests/service/evaluate_function_type_parameters_test.dart
>testee>out> Observatory listening on http://127.0.0.1:38713/
** Signaled to run test queries on http://127.0.0.1:38713/
>testee>out> 
Loading VM...
Done loading VM
Running evaluate_function_type_parameters_test.dart [1/14]
Paused with PauseBreakpoint
Running evaluate_function_type_parameters_test.dart [2/14]
>testee>err> ../../runtime/vm/object.cc: 13472: error: unreachable code
>testee>err> Dumping native stack trace for thread 2ef7
>testee>err>   [0x0000aaaae2c161d8] dart::Profiler::DumpStackTrace(void*)
>testee>err> -- End of DumpStackTrace

...

--- Re-run this test:
python tools/test.py -m release -c dartk -a arm64 service/evaluate_function_type_parameters_test
```

I was not able to try to reproduce this, at the moment I cannot access an arm machine.

**Comment by mraleph** [comment] 2018-10-31 16:37
Duplicate of #34999

**Closed by mraleph** 2018-10-31 16:37 UTC
Labels: area-vm, gardening
