### ISSUE TITLE
VM dies sometimes

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#26102] opened 2016-03-28 16:14 UTC
...and takes Analysis Server with it.
IDEA restarts Analysis Server, but then it takes again some time to reanalyze everything.

```
debugStream: 1459181397068 <= {"event":"analysis.errors","params":{"file":"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analyzer/lib/src/task/dart.dart","errors":[]}}
/b/build/slave/dart-sdk-mac-be/build/sdk/runtime/vm/thread_pool.cc:347: error: Could not start worker thread: result = 35.
```

![image](https://cloud.githubusercontent.com/assets/384794/14082527/5a19b846-f4c5-11e5-9ec4-5b531a17c5b5.png)

**Comment by iposva-google** [comment] 2016-03-28 18:19
@scheglov Can you please confirm that you are running on a x64 based Dart SDK?

**Comment by scheglov** [comment] 2016-03-28 18:24
It seems that I use the i32 version: `Dart VM version: 1.16.0-edge.83e73400dba98fc21c4ea58da1869a385efa669f (Mon Mar 28 07:46:27 2016) on "macos_ia32"`.

Does it run out of memory?

**Comment by iposva-google** [comment] 2016-03-28 18:26
Seems to be a duplicate of #26018

**Closed by iposva-google** 2016-03-28 18:26 UTC
Labels: area-vm
