### ISSUE TITLE
[dart:io] Broken sockets on multiple http connections

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#46647] opened 2021-07-17 03:32 UTC
We observed an increased number of flakes in webdev, especially in CI, due to broken sockets and other OS errors.

After some (actually, a lot) of experimentation and adding logs, I came up with a relatively small example where reading a few hundred files over http causes broken sockets on my local machine as well, but setting  a `maxConnectionsPerHost` limit to `200` on the http client seems to fix it.

There are a few questions related to this issue:
- Is it a bug or expected behavior when the resources run out?
- Is it a good solution to set the `maxConnectionsPerHost` limit?
- Should we have `maxConnectionsPerHost` in HttpClient set to some default value to prevent the errors?
- Is it possible to add more information to the error - for example, a full stack trace, reason, and a possible fix?

Related: https://github.com/dart-lang/webdev/issues/1345

**main.dart**

```
// @dart=2.9

import 'dart:async';
import 'dart:convert';
import 'dart:io' show HttpClient, HttpClientResponse, HttpServer, HttpStatus;

import 'package:async/async.dart';
import 'package:browser_launcher/browser_launcher.dart';
import 'package:http_multi_server/http_multi_server.dart';
import 'package:shelf/shelf.dart';
import 'package:shelf/shelf_io.dart';
import 'package:test/test.dart';

const _existingFile = 'existingFile';
const _contents = 'hello';

String _fileContents() => List.filled(10000, _contents).join('\n');
List<int> _fileBytes() => utf8.encode(_fileContents());

FutureOr<Response> handler(Request request) {
  final uri = request.requestedUri;
  var contents = _fileContents();
  final headers = {
    'content-length': '${_fileBytes().length}',
    ...request.headers,
  };
  if (request.method == 'GET') {
    return uri.pathSegments.last == _existingFile
        ? Response.ok(contents, headers: headers)
        : Response.notFound(uri.toString());
  }
  return Response.internalServerError();
}

void main() async {
  HttpServer server;
  HttpClient client;
  String hostname;
  int port;

  group('Http server', () {
    setUpAll(() async {
      hostname = 'localhost';
      port = await findUnusedPort();
      client = HttpClient()
        // Uncomment this line to make the code work.
        // Different machine configurations might require
        // making this number smaller in order to succeed
        // ..maxConnectionsPerHost = 200
      ;
      server = await HttpMultiServer.bind(hostname, port);
      serveRequests(server, handler);
    });

    tearDownAll(() async {
      client.close();
      await (server.close(force:true));
    });

    test('can download a lot of files concurrently', () async {
      Future<void> read(Uri uri) async {
        var result = await readAsBytes(uri, client);
        expect(utf8.decode(result), _fileContents());
      }

      var n = 1000;
      var uri = Uri.parse('http://$hostname:$port/$_existingFile');
      var futures = [
        for (var i = 0; i < n; i++) read(uri),
      ];
      await expectLater(Future.wait(futures), completes);
    }, timeout: const Timeout.factor(2));
  });
}

Future<List<int>> readAsBytes(Uri uri, HttpClient client) async {
    var request = await client.getUrl(uri);
    var response = await request.close();
    if (response.statusCode != HttpStatus.ok) {
      unawaited(_ignore(response));
      throw Exception(
            'Error loading $uri: server returned ${response.statusCode}');
    }
    return await collectBytes(response);
  }

/// Make sure the response stream is listened to so that we don't leave
/// dangling connections, suppress errors.
Future<void> _ignore(HttpClientResponse response) {
  return response
      .listen((_) {}, cancelOnError: true)
      .cancel()
      .catchError((_) {});
}
```

**pubspec.yaml**

```
name: repro

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  async: ^2.3.0
  http_multi_server: ^3.0.0
  shelf: '>=0.7.0 <2.0.0'

dev_dependencies:
  test: ^1.6.0
  webdriver: '>=2.0.0 <4.0.0'
  devtools_server: ^2.0.0
```

**Repro**

`dart test main.dart`

**Actual**

```
00:04 +0 -1: Http server can download a lot of files concurrently [E]
  SocketException: OS Error: Connection reset by peer, errno = 54, address = localhost, port = 63304
  dart:_http       _HttpClient.getUrl
  main.dart 79:32  readAsBytes
  main.dart 64:28  main.<fn>.<fn>.read
  main.dart 63:24  main.<fn>.<fn>.read
  main.dart 71:37  main.<fn>.<fn>
  main.dart 62:54  main.<fn>.<fn>
```

**Comment by a-siva** [comment] 2021-07-23 00:21
I was unable to reproduce this on my linux workstation.
Per @annagrin I changed the test to use larger files i.e changed to List.filled(100000, _contents).join('\n'); and run with a larger timeout then I get
SocketException: OS Error: Connection reset by peer, errno = 104, address = localhost, port = 44620

I tried the same test on my macbook and it runs into an error 'OS Error" Too many open files, errno = 24)', I am unable to increase the shell 'descriptors' limit to more than 1024.

The errno = 24 is clearly because the process is running out of descriptors.
The errno = 104 (connection reset by peer) indicates that the server has sent a TCP RST packet causing the client connection to reset, this usually happens when there is too much load on the server.

I feel the test is pushing the resouce limits on the system, resulting in these errors and the fix of limiting the maximum number of connections at the same time would make it more reliable.

**Comment by annagrin** [comment] 2021-07-23 23:51
@a-siva thanks for looking into that! I think you are right -  I tried to create a .js app to do the same (and rule out a dart library or VM bug), to see if the behavior would be different. I can repro the same errors but cannot fix them this the max sockets limit. So at least it fails the same way as dart. I'll keep my max connection limit as a solution for now, will see I the issues appear in the future. 

Here is my example:
```
const http = require('http');

let fileContents = new Array(10000).fill('hello').join();

let server = http.createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.write(fileContents);
    res.end();

}).listen(80);

console.log('server running on port 80');

let N = 1000;
const results = [];
const requestErrors = [];
const responseErrors = [];

var agent = new http.Agent({opts: {
 }});

// Uncommenting the following line does not seem to have any effect on my mac. 
// agent.maxSockets = 200;

var options = {
    agent: agent
};


async function getFile() {
    var complete;
    var completer = new Promise(resolve => complete = resolve);

    const req = http.get({url: 'http://localhost:80/file', options: options}, (res) => {
        
        // Continuously update stream with data
        let content = '';

        res.on('data', (chunk) => {
            content += chunk;
        });

        res.on('error', (err) => {
            responseErrors.push(err);
            complete(false);
        });

        res.on('end', () => {
            results.push(content.substr(0, 10));
            complete(true);
        });
    });

    req.on('error', (err) => {
        requestErrors.push(err);
        complete(false);
    });
    req.end();

   await completer;
}

const promiseArray = [];
for (var i = 0; i < N; i++) {
    promiseArray.push(getFile());
}

(async () => {
    const bar = await Promise.all(promiseArray).then(
        () => {
            console.log('client received files: ' + results.length);
            console.log('client received request errors: ' + requestErrors.length);
            console.log('client received response errors: ' + responseErrors.length);
            server.close();
        }
    );
})();
```

**Comment by a-siva** [comment] 2021-07-29 00:51
Thanks @annagrin , I think we can close this issue as 'works as intended' and if anything else shows up we can reopen it.

**Closed by a-siva** 2021-07-29 00:51 UTC
Labels: area-vm, closed-as-intended, library-io
