### ISSUE TITLE
IntelliJ

### ISSUE THREAD

**Issue by wuhuaqing** [dart-lang/sdk#37795] opened 2019-08-09 02:34 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4819257`
- `2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e`
- `AI-173.4819257, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 2400x1350`

# Exception

Please append the contents of:
file://C:\Users\23398\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.3.2-edge.e3edfd36b2aa7ff4e98fe541ef5666ef2e70d17e, server version 1.26.1, error: Analysis failed: D:\flutter_workspace\toiletclientmanage\manager_v1.0\lib\main.dart context: exception_20190809_101931_943
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:666:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:384:56)
#3      __InternalLinkedHashMap

**Comment by a-siva** [comment] 2019-08-09 15:55
This is a duplicate of https://github.com/dart-lang/sdk/issues/37394

**Closed by a-siva** 2019-08-09 15:55 UTC
Labels: closed-duplicate

**Comment by asarkar1990** [comment] 2019-09-11 21:07
it should not be closed! it still exist.
