### ISSUE TITLE
Import Method causing types to mismatch

### ISSUE THREAD

**Issue by tensor-programming** [dart-lang/sdk#33149] opened 2018-05-17 07:06 UTC
* Dart 2.0.0-dev.54.0.flutter-46ab040e58 (the current version with the master flutter build)
* Windows

----

Steps to recreate issue:

1. Create three files, each with a custom class inside of it.  I.E. `a.dart` with `class A`, `b.dart` with `class B` and `c.dart` with `class C`  
2. Have one of these classes constructors (class B for instance) take in one of the other classes.   `B(A())` for example. 
3. In class C, import class A from path `import A.dart` and import b from package: `import package:test/B.,dart`
3. In class C, make new instances of Class A and B and try to pass A into B's constructor. 

```
import 'A.dart';
import 'package:bug_test/B.dart';

class C {
  final A a;
  final B b = B(a);
}
```

```
Error: [dart] The argument type 'A (<project-path>)' can't be assigned to the parameter type 'A (<project-path>)'.
A value of type '#lib1::A' can't be assigned to a variable of type '#lib2::A'.
Try changing the type of the left hand side, or casting the right hand side to '#lib2::A'.

```

If you change the Imports to all be from Path or all be from Package then the error goes away.  

-----

**Comment by zoechi** [comment] 2018-05-17 08:10
What is the location of the file that contains the `main(){}` and how do you run it?

**Comment by tensor-programming** [comment] 2018-05-17 08:59
This is a flutter application so the main function sits in the main.dart file in the lib folder.

**Comment by zoechi** [comment] 2018-05-17 09:04
Currently you must not use relative imports in `lib/main.dart`. 
#33076 is about what to change in language and tools for that to not cause issues.

**Comment by tensor-programming** [comment] 2018-05-17 09:06
The problem is not in `main.dart` however. As mentioned in the original post, I was able to recreate the problem in a `c.dart` file which does not contain a main function. (I did originally come across this bug in main.dart but was later able to recreate it using independent files).

**Comment by tensor-programming** [comment] 2018-05-17 10:32
Right [here](https://gist.github.com/tensor-programming/ecb2030a914a71eca979816661a8d932) is a gist of the file structure and the code that was used in the pure dart example which yielded this bug.

As you can see, there are no imports in main as mention multiple times before.  I never mentioned anything about the names of these files (these names were made just to test the error).  I personally already know that you should not import from a file path, I am not talking about best practices, I am talking about a problem with mixed imports though.   

Even if I delete the bin folder that has the main.dart file in it, the problem persists (no entry points).

**Comment by zoechi** [comment] 2018-05-17 11:13
> As you can see, there are no imports in main as mentioned multiple times before.

> What is the location of the file that contains the main(){} and how do you run it?

`c.dart` doesn't contain `main()`, please show the content of the file that contains `main()` and how you run it.

**Comment by lrhn** [comment] 2018-05-17 13:48
According to the gist, the `main` file is in the `bin` folder and doesn't import anything.
The code in `lib` is not imported by `main`, so the analyzer seems to be giving warnings as if it doesn't recognize that `c` is a package file.

**Comment by tensor-programming** [comment] 2018-05-17 17:32
Exactly.  Even if I delete the entire Bin folder and remove Main.dart from the equation, the analyzer still kicks the error back. If I rebuild the entire thing as a library, the same thing also occurs.

**Comment by tensor-programming** [comment] 2018-05-17 18:19
@zoechi it's not a problem.  Just trying to do my part for the community.

**Comment by matanlurey** [comment] 2018-07-18 16:12
Duplicate of https://github.com/dart-lang/sdk/issues/33076.

**Closed by matanlurey** 2018-07-18 16:12 UTC
Labels: area-analyzer
