### ISSUE TITLE
flutter build web crashed

### ISSUE THREAD

**Issue by Miiite** [dart-lang/sdk#48491] opened 2022-03-01 15:37 UTC
Hello,

I am working on a pretty large mobile app project that might need migration to the web.
So as a starting point I just added the web platform to my flutter project, and then tried to build it using `flutter build web`.

This is what I got as the output:

```
flutter build web

💪 Building with sound null safety 💪

Target dart2js failed: Exception:
.dart_tool/flutter_build/1d9acf778e9c75e8a73a21287c3e4a82/app.dill:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.16.1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'boxedVariables' was called on null.
Receiver: null
Tried calling: boxedVariables
#0      JsKernelToElementMap.makeRecordContainer
(package:compiler/src/js_model/element_map_impl.dart:1769:14)
#1      ClosureDataBuilder.createClosureEntities.<anonymous closure>
(package:compiler/src/js_model/closure.dart:328:23)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#3      ClosureDataBuilder.createClosureEntities
(package:compiler/src/js_model/closure.dart:326:19)
#4      JsClosedWorldBuilder.convertClosedWorld
(package:compiler/src/js_model/js_world_builder.dart:161:41)
#5      JsBackendStrategy.createJClosedWorld
(package:compiler/src/js_model/js_strategy.dart:175:52)
#6      Compiler.closeResolution (package:compiler/src/compiler.dart:594:25)
#7      Compiler.computeClosedWorld (package:compiler/src/compiler.dart:464:9)
#8      Compiler.compileFromKernel.<anonymous closure>.<anonymous closure>
(package:compiler/src/compiler.dart:561:17)
#9      CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#10     Compiler.compileFromKernel.<anonymous closure>
(package:compiler/src/compiler.dart:560:44)
#11     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#12     Compiler.compileFromKernel (package:compiler/src/compiler.dart:559:14)
#13     Compiler.runInternal (package:compiler/src/compiler.dart:363:17)
<asynchronous suspension>
#14     main (package:compiler/src/dart2js.dart:1373:3)
<asynchronous suspension>
```

My environment is the following:

MacOS Monterey 12.1 (21C52)
MacBook M1 pro (2021)

```
Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "macos_x64"
```

**Comment by sigmundch** [comment] 2022-03-01 16:21
@Miiite thank you so much for your report.

It is very likely that this is the same issue as https://github.com/dart-lang/sdk/issues/47916, so I'll tentatively close this issue as a duplicate of the other.

Some details worth highlighting from the other bug:
* @rakudrama added some extra diagnostics to help include in the error message which method was being compiled when this invariant was broken in the compiler. His change is not in the stable channel yet (Dart 2.16.1), but in the current dev and beta channels. If you try to build your application with a more recent version of flutter (like beta or main), you may be able to identify what part of the program is triggering this issue.
* Once you do, it would be great to confirm that indeed it is the same problem. You may also find it easier to workaround the issue. For example, other people mentioned they were able to move forward by removing a constructor tear-off (e.g. `X.new`) from their app.

**Closed by sigmundch** 2022-03-01 16:21 UTC

**Comment by Miiite** [comment] 2022-03-01 17:29
Thank you @sigmundch for the lightning fast reponse.
Unfortunately the issue does not seem related, as I'm still facing it even after upgrading my flutter installation to the beta channel, and therefore using dart 2.16.1.

```
super_app git:(chore/super_app_web) flutter doctor -v
[✓] Flutter (Channel beta, 2.11.0-0.1.pre, on macOS 12.1 21C52 darwin-arm, locale en-FR)
    • Flutter version 2.11.0-0.1.pre at /Users/adrien.padol/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b101bfe32f (13 days ago), 2022-02-16 07:36:54 -0800
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/adrien.padol/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 01FB688F-C492-46BE-B50D-625063182646 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
➜  super_app git:(chore/super_app_web) flutter build web

💪 Building with sound null safety 💪

Target dart2js failed: Exception: .dart_tool/flutter_build/1187e4f89ebf41e3d97f304764d0c904/app.dill:
Internal Error: The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.16.1), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'boxedVariables' was called on null.
Receiver: null
Tried calling: boxedVariables
#0      JsKernelToElementMap.makeRecordContainer (package:compiler/src/js_model/element_map_impl.dart:1769:14)
#1      ClosureDataBuilder.createClosureEntities.<anonymous closure> (package:compiler/src/js_model/closure.dart:328:23)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#3      ClosureDataBuilder.createClosureEntities (package:compiler/src/js_model/closure.dart:326:19)
#4      JsClosedWorldBuilder.convertClosedWorld (package:compiler/src/js_model/js_world_builder.dart:161:41)
#5      JsBackendStrategy.createJClosedWorld (package:compiler/src/js_model/js_strategy.dart:175:52)
#6      Compiler.closeResolution (package:compiler/src/compiler.dart:594:25)
#7      Compiler.computeClosedWorld (package:compiler/src/compiler.dart:464:9)
#8      Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:561:17)
#9      CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#10     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:560:44)
#11     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#12     Compiler.compileFromKernel (package:compiler/src/compiler.dart:559:14)
#13     Compiler.runInternal (package:compiler/src/compiler.dart:363:17)
<asynchronous suspension>
#14     main (package:compiler/src/dart2js.dart:1373:3)
<asynchronous suspension>



Compiling lib/main.dart for the Web...                             21.7s
Exception: Failed to compile application for the Web.

```

**Comment by sigmundch** [comment] 2022-03-01 17:51
Thank you so much for checking. Sorry for the confusion on my part. I saw that our change (https://github.com/dart-lang/sdk/commit/b053f2c355cb0a186aabf09e8cf603557e99f535) made it to the Dart beta channel and I didn't double check whether it was in the Flutter beta channel. It appears that it is not there yet (at least based on the version printed by `flutter doctor` above). So the extra diagnostic hint is only available in the main/master channel for a while longer until the next beta is out.

**Comment by Miiite** [comment] 2022-03-02 09:11
Oh you're right, I should have tested the `master` channel also.
I do get rid of the compilator error, and get more analysis hints, when on the `master` channel. Thank you for the feedback !

**Comment by Miiite** [comment] 2022-03-02 10:17
While I do get more precise errors, it does not seem very usable atm.

Here is what I end up with:


Here are my logs:

```
flutter build web

💪 Building with sound null safety 💪

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../super_app_core/lib/src/sources/result.freezed.dart:352:17:
Internal Error: The compiler crashed when compiling this element.
  **const factory Failure(F failure) = _$Failure<S, F>;**
                ^
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (2.17.0-156.0.dev), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'boxedVariables' was called on null.
Receiver: null
Tried calling: boxedVariables
#0      JsKernelToElementMap.makeRecordContainer (package:compiler/src/js_model/element_map_impl.dart:1770:14)
#1      ClosureDataBuilder.createClosureEntities.processModel (package:compiler/src/js_model/closure.dart:329:23)
#2      ClosureDataBuilder.createClosureEntities.<anonymous closure>.<anonymous closure>
(package:compiler/src/js_model/closure.dart:389:9)
#3      CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:1025:15)
#4      ClosureDataBuilder.createClosureEntities.<anonymous closure> (package:compiler/src/js_model/closure.dart:388:17)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:579:13)
#6      ClosureDataBuilder.createClosureEntities (package:compiler/src/js_model/closure.dart:387:19)
#7      JsClosedWorldBuilder.convertClosedWorld (package:compiler/src/js_model/js_world_builder.dart:161:41)
#8      JsBackendStrategy.createJClosedWorld (package:compiler/src/js_model/js_strategy.dart:174:52)
#9      Compiler.closeResolution (package:compiler/src/compiler.dart:610:25)
#10     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:470:9)
#11     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:572:17)
#12     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#13     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:571:44)
#14     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:181:35)
#15     Compiler.compileFromKernel (package:compiler/src/compiler.dart:570:14)
#16     Compiler.runInternal (package:compiler/src/compiler.dart:372:17)
<asynchronous suspension>
#17     main (package:compiler/src/dart2js.dart:1392:3)
<asynchronous suspension>



Compiling lib/main.dart for the Web...                             13.9s
Exception: Failed to compile application for the Web.
➜  super_app git:(chore/super_app_web) ✗ flutter doctor -v
[✓] Flutter (Channel master, 2.11.0-0.0.pre.731, on macOS 12.1 21C52 darwin-arm, locale en-FR)
    • Flutter version 2.11.0-0.0.pre.731 at /Users/adrien.padol/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f360c977a (10 hours ago), 2022-03-01 16:26:11 -0800
    • Engine revision a5718ab3c3
    • Dart version 2.17.0 (build 2.17.0-156.0.dev)
    • DevTools version 2.11.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/adrien.padol/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 5AECF4C1-FE1B-4B35-929C-50BBD9F7D229 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

So the compiler does not like the `Failure` class declaration which is this:

```
abstract class Failure<S, F> implements Result<S, F> {
  const factory Failure(F failure) = _$Failure<S, F>;

  F get failure;
  @JsonKey(ignore: true)
  $FailureCopyWith<S, F, Failure<S, F>> get copyWith =>
      throw _privateConstructorUsedError;
}
```

This is some code automatically generated by the `freezed` package.
Would you have any idea why this particular piece of code is crashing the compiler ?

**Comment by sigmundch** [comment] 2022-03-02 17:40
Thanks for the details! - The issues in the other bug were also caused by code generated by the freezed package, so this confirms my suspicion that it's the same problem.

They initially thought it was related to the use of optional parameters, but your example shows that it is unrelated to that and only related to the indirection from factory constructors. I'll add more details in the other bug.
