### ISSUE TITLE
Instantiate-to-bound seems to ignore variance in some situations

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#34663] opened 2018-10-03 15:22 UTC
The variance of a formal type parameter of a parameterized type alias must be taken into account when computing the result of an instantiate-to-bound operation and when checking whether a given type is super-bounded. In particular, the following should not have any compile-time errors:

```dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

typedef G<X, Y extends Function(X)> = X Function(Function(Y));

main() {
  G source;
  var fsource = toF(source);
  F<G<dynamic, Function(Null)>> target = fsource;
}
```

This is basically asserting that the meaning of the raw `G` in the first line in the body of `main` is `G<dynamic, Function(Null)>`. Call that type _T_. That result is achieved in a couple of steps as follows:

```
  X           Y                     Reason
  ----------------------------------------------------------------------------
  dynamic     Function(X)           Initial configuration: declared bounds.
  dynamic     Function(Null)        By rule 2 in instantiate-to-bound.md
```

All type variables are now gone, so that's the result: I2b on `G` is _T_.

Noting that both `X` and `Y` are covariant, _T_ is a correct super-bounded type and the right hand side of the type alias is well-bounded with these arguments applied, so there are no errors.

However, `dartanalyzer` from 6c5326ae809746e3f78da186d29d0b3a386fb1f9 emits the following:

```
ERROR|STATIC_TYPE_WARNING|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/devel/dart/work/sdk/tests/language_2/scratch_test.dart|13|16|14|'(Null) → dynamic' doesn't extend '(dynamic) → dynamic'.
ERROR|STATIC_TYPE_WARNING|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/devel/dart/work/sdk/tests/language_2/scratch_test.dart|13|42|7|A value of type '<Y extends (((dynamic) → dynamic) → dynamic) → dynamic>() → void' can't be assigned to a variable of type '<Y extends (((Null) → dynamic) → dynamic) → dynamic>() → void'.
```

This behavior seems to indicate that the analyzer does not consider the occurrence of `Null` in _T_ to be contravariant, because the check for being a super-bounded type requires contravariant occurrences of `Null` to be replaced by `dynamic` (section 'Super-Bounded Types'):

```latex
  For each $j \in 1 .. n$, let $S'_j$ be the result of replacing
  every occurrence of a top type
  in a covariant position in $S_j$ by \code{Null},
  and every occurrence of \code{Null}
  in a contravariant position in $S_j$ by \code{Object}.
  It is then required that
  \code{$G$<$S'_1, \ldots,\ S'_n$>}
  is regular-bounded.
```

So in order to verify that _T_ is a correct super-bounded type we ought to check that `G<Null, Function(Object)>` is regular-bounded, i.e., that `Null <: dynamic` and `Function(Object) <: Function(Null)`, which is true for both. That's one bug, in the area of verifying super-bounded types.

The other error message is another bug (but it's again likely to be caused by ignored contravariance): The result of instantiate-to-bound applied to `G` is `G<dynamic, Function(dynamic)>`, but it should be _T_.

Double-checking, we actually get the same results for a class:

```dart
typedef F<X> = void Function<Y extends X>();
F<X> toF<X>(X x) => null;

class C<X, Y extends Function(X)> {}

main() {
  C source;
  var fsource = toF(source);
  F<C<dynamic, Function(Null)>> target = fsource;
}
```

which causes `dartanalyzer` to emit this:

```
ERROR|STATIC_TYPE_WARNING|INVALID_ASSIGNMENT|/usr/local/google/home/eernst/devel/dart/work/sdk/tests/language_2/scratch_test.dart|13|42|7|A value of type '<Y extends C<dynamic, (dynamic) → dynamic>>() → void' can't be assigned to a variable of type '<Y extends C<dynamic, (Null) → dynamic>>() → void'.
ERROR|STATIC_TYPE_WARNING|TYPE_ARGUMENT_NOT_MATCHING_BOUNDS|/usr/local/google/home/eernst/devel/dart/work/sdk/tests/language_2/scratch_test.dart|13|16|14|'(Null) → dynamic' doesn't extend '(dynamic) → dynamic'.
```

Again, this program should not incur any compile-time errors, and the culprit again seems to be ignored contravariance.

**Comment by bwilkerson** [comment] 2018-10-03 15:42
@stereotype441

**Comment by eernstg** [comment] 2018-10-03 15:49
PS: Thanks to @lrhn for doubting that it would work to use `X` in a contravariant position in the bound of `Y`. ;-)

**Comment by stereotype441** [comment] 2018-10-03 15:53
I'd like to see us fix this for Dart 2.1, but I don't think we would need to block the release for it.  Accordingly, setting the priority to P2.

**Comment by MichaelRFairhurst** [comment] 2018-10-09 16:58
Correct, it seems that the analyzer implementation of instantiate to bounds never included contravariance checks.

**Comment by leafpetersen** [comment] 2018-11-07 02:18
There seem to be some issues with the original specification of this, and we're working out what the specification should say.  Please hold off landing further changes on this in the meantime.

**Comment by eernstg** [comment] 2018-11-15 11:32
Right, CL 80140 addresses the fact that variance in the existing specification (of i2b and of the super-boundedness check) is ignored at the top level. In the example here (where `Y` has bound `Function(X)`) we have contravariance in a nested position (`X` occurs contravariantly in `Function(X)`). 80140 makes no difference here (`X` also occurs contravariantly in `G<_, Function(X)>`), and it never makes a difference as long as all type parameters of the top level type operator are covariant (in particular, it never makes a difference for a raw type denoting a generic class). So the need to take variance into account for nested type terms like has been specified at least since January 2018 (af430f37a82).

**Comment by stereotype441** [comment] 2019-01-23 18:53
Since @MichaelRFairhurst closed #34663 (which was P1) as a duplicate of this bug, I'm escalating this bug to P1.

**Comment by eernstg** [comment] 2019-01-24 10:04
Note that the example in #34663 as well as the example given [here](https://github.com/dart-lang/sdk/issues/34663#issue-366394664) cover two different situations, so both of them should be considered as a test case when it is verified that this issue has been resolved.

**Comment by stereotype441** [comment] 2020-01-30 18:48
The two repros in the bug report no longer produce analyzer errors, so I believe this issue has been fixed.

**Closed by stereotype441** 2020-01-30 18:48 UTC
Labels: P1, area-analyzer, type-bug
