### ISSUE TITLE
Failures on [package:js] Added checks for external non-JS members....[VM] Adds Debugger break for Future.catchError

### ISSUE THREAD

**Issue by sstrickl** [dart-lang/sdk#44845] opened 2021-02-03 10:46 UTC
There are new test failures on [[package:js] Added checks for external non-JS members....[VM] Adds Debugger break for Future.catchError](https://github.com/dart-lang/sdk/compare/dfd5413952ee5232235adf460575a1a7c2674874~...cfa35be6f03d7bca902d66f1497cc7f71edb3c3f).

The tests
```
ffi/sizeof_test RuntimeError (expected Pass)
```
are failing on configurations
```
dartk-strong-win-release-ia32
dartk-weak-asserts-win-release-ia32
```

**Comment by dcharkes** [comment] 2021-02-03 10:49
@sstrickl is this a duplicate of https://github.com/dart-lang/sdk/issues/44835? A fix for the sizeOf tests already landed.

**Comment by sstrickl** [comment] 2021-02-03 10:50
Ah, the commit mentioned arm32 specifically, so I wasn't sure that it also covered IA32 (and didn't dig to check).

**Comment by dcharkes** [comment] 2021-02-03 10:50
Yeah, I did not realize this touched win ia32 as well. But the test makes all 32bit expectations more general.

**Closed by dcharkes** 2021-02-03 10:50 UTC
Labels: area-vm, library-ffi
