### ISSUE TITLE
poorly documented mixin case

### ISSUE THREAD

**Issue by sircco** [dart-lang/sdk#26461] opened 2016-05-16 13:29 UTC
dart 1.16, problem where both mixins need to access same parent variable.
Case 1 works, but throws error in strong mode.
Case 2 fixes this but is case that could use better documentation.

**Case 1**

```
abstract class A2 {
  int  a;

  p2() {
        print("A2 - $a");  
  } 
}

abstract class A3 {  
  int  a;

  p3() {
    print("a3 - $a");
  }
}

class A extends Object with A2, A3 {
  int a;

  A() {
     a = 11;
  }

  void p() {
    print("A - $a");
  }
}

main() {
  A a = new A();
  a.p();
  a.p2();
  a.p3();
}
```

**Case 2**

```
abstract class A2 {
  int get a;

  p2() {
        print("A2 - $a");  
  } 
}

abstract class A3 {  
  int get a;

  p3() {
    print("a3 - $a");
  }
}

class A extends Object with A2, A3 {
  int a;

  A() {
     a = 11;
  }

  void p() {
    print("A - $a");
  }
}

main() {
  A a = new A();
  a.p();
  a.p2();
  a.p3();
}
```

**Comment by lrhn** [comment] 2016-05-17 12:53
Mixins can be tricky, but they are not different from other classes. You just get to write the class body somewhere else than at the declaration.

In case 1 you have the class `A` with super-classes `Object-with-A2-with-A3`, `Object-with-A2`, and `Object`.
Three of these classes declare an "a" field, so you have three "a" fields on the resulting class with the one in `A` overriding and shadowing the other two, and those two are just a waste of memory.
This is no different from what happens if you declare:
```dart
class A2 extends Object {
  int  a;
  p2() {
    print("A2 - $a");  
  } 
}
class A3 extends A2 {
  int a;
  p3() {
    print("A3 - $a");
  }
}
class A extends A3 {
  int a;
  p() {
    print("A - $a");
  }
}
main() {
  A a = new A();
  a.p();
  a.p2();
  a.p3();
}
```
It is basically the exact same program, just without complicating it with mixins. Here it's more clear that you declare three `a` fields, and why that's probably not what you intended.

So, all in all, I don't think it's a problem with mixins as such, mixins just makes it easier to not see the actual class inheritance structure because they allow you to put the class body further away.

**Comment by munificent** [comment] 2016-12-19 20:54
I'm going to close this because it looks like the language is working as intended. I totally agree that this is a footgun. It is too easy to override a field, which is almost never what you want.

See also: #26461

**Closed by munificent** 2016-12-19 20:54 UTC
Labels: area-language
