### ISSUE TITLE
Faced this issue while doing hot reload

### ISSUE THREAD

**Issue by techypanther** [dart-lang/sdk#39381] opened 2019-11-14 04:58 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 1440x900`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.1103600280676ea169a30d7a503e836671cdc553, server version 1.27.3, FATAL error: Failed to handle request: {id: 790, method: analysis.getHover, params: {file: /Users/sameerdonga/flutter/packages/flutter/lib/src/widgets/image.dart, offset: 9396}, clientRequestTime: 1573707462195}
FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files in system, errno = 23)
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:64:5)
#1      Uri.base (dart:core-patch/uri_patch.dart:21:41)
#2      current (package:path/path.dart:84:17)
#3      Context.current (package:path/src/context.dart:62:57)
#4      Context.toUri (package:path/src/context.dart:1008:43)
#5      _OverlayFile.createSource (package:analyzer/file_system/overlay_file_system.dart:222:57)
#6      FileSystemState.hasUri (package:analyzer/src/dart/analysis/file_state.dart:902:36)
#7      AnalysisDriver.getResult (package:analyzer/src/dart/analysis/driver.dart:781:19)
#8      AbstractAnalysisServer.getResolvedUnit (package:analysis_server/src/analysis_server_abstract.dart:284:10)
#9      AnalysisDomainHandler.getHover (package:analysis_server/src/domain_analysis.dart:80:46)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

For additional log information, please append the contents of
file:///private/var/folders/4s/v76wtkxj0b791tn35g35bf7c0000gn/T/report.txt.

**Comment by srawlins** [comment] 2020-06-13 03:19
Thanks for reporting this issue! This was reported earlier at https://github.com/dart-lang/sdk/issues/37598; please follow along there.

**Comment by srawlins** [comment] 2020-06-13 03:19
Duplicate of #37598

**Closed by srawlins** 2020-06-13 03:19 UTC
Labels: analyzer-crash-report, area-analyzer
