### ISSUE TITLE
Flaky: vm/cc/GuardFieldFinalListTest

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#28257] opened 2017-01-04 15:51 UTC
This test failed in a debug build on Windows, by hitting the following ASSERT in SafepointHandler::ExitSafepointUsingLock in safepoint.cc:

```c++
void SafepointHandler::ExitSafepointUsingLock(Thread* T) {
  MonitorLocker tl(T->thread_lock());
  ASSERT(T->IsAtSafepoint());
  while (T->IsSafepointRequested()) {
    T->SetBlockedForSafepoint(true);
    tl.Wait();
    T->SetBlockedForSafepoint(false);
  }
  T->SetAtSafepoint(false);
}
```

This looks like it could be a bug in the VM and not just a flaky test.

**Comment by johnmccutchan** [comment] 2017-01-04 16:40
@kmillikin do you have the stack trace that was printed?

**Comment by kmillikin** [comment] 2017-01-09 11:01
Yeah, it wasn't helpful:

```
FAILED: none-vm debug_ia32 vm/cc/GuardFieldFinalListTest
Expected: Pass 
Actual: Crash
CommandOutput[run_vm_unittest]:

stderr:
e:\b\build\slave\vm-win-debug-ia32-be\build\sdk\runtime\vm\safepoint.cc: 171: error: expected: T->IsAtSafepoint()
Dumping native stack trace for thread 904
  [0x00a3293a] Unknown symbol
  [0x00a3293a] Unknown symbol
  [0x00798ea9] Unknown symbol
  [0x00ab221b] Unknown symbol
-- End of DumpStackTrace


Command[run_vm_unittest]: set DART_CONFIGURATION=DebugIA32 & out\DebugIA32\run_vm_tests --ignore-unrecognized-flags GuardFieldFinalListTest
Took 0:00:00.116011

Short reproduction command (experimental):
    python tools/test.py -aia32 -t120 vm/cc/GuardFieldFinalListTest
```

**Comment by mraleph** [comment] 2017-11-16 11:58
This issue has been last updated for 311 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by mraleph** [comment] 2018-04-24 19:40
Assuming stale. The test was not suppressed and does not seem to be currently failing. Please reopen if it occurs again.

**Closed by mraleph** 2018-04-24 19:40 UTC
Labels: area-vm, gardening
