### ISSUE TITLE
Failures on [VM] Minor cleanup

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#54458] opened 2023-12-27 06:47 UTC
There are new test failures on [[VM] Minor cleanup](https://github.com/dart-lang/sdk/commit/a0c9333ff32ff2761fd797847bcde3b7ef23dc94).

The tests
```
pkg/analyzer/test/src/summary/macro_test Timeout (expected Pass)
standalone/io/http_big_header_test Timeout (expected Pass)
```
are failing on configurations
```
analyzer-unittest-asserts-release-win
vm-aot-linux-release-simarm_x64
```

[log](https://dart-ci.appspot.com/log/vm-aot-linux-release-simarm_x64/vm-aot-linux-release-simarm_x64/1895/standalone/io/http_big_header_test)

**Comment by a-siva** [comment] 2024-01-02 17:49
Strange, unclear how deleting some dead code is leading to timeouts

**Comment by a-siva** [comment] 2024-01-02 18:26
The test `standalone/io/http_big_header_test`
passes for me locally on top of tree but it does take a while. I think the test needs to be marked as slow on the simulator architectures.

With respect to `pkg/analyzer/test/src/summary/macro_test Timeout` looks like the test was flaking and turned to a Failure after this CL.

**Comment by a-siva** [comment] 2024-01-17 23:25
standalone/io/http_big_header_test failure is a duplicate of https://github.com/dart-lang/sdk/issues/52110

The macro test failure is not related to the above CL and is an unrelated failure (new test).

**Closed by a-siva** 2024-01-17 23:25 UTC
Labels: area-vm, gardening
