### ISSUE TITLE
FileSystemException in _WindowsDirectoryWatcher when running analysis server

### ISSUE THREAD

**Issue by geogradient** [dart-lang/sdk#34476] opened 2018-09-16 05:57 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-173.4907809`
- `2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab`
- `AI-173.4907809, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\bitbucket\havapp], excluded: [C:\bitbucket\havapp\.idea, C:\bitbucket\havapp\.dart_tool, C:\bitbucket\havapp\.pub, C:\bitbucket\havapp\build]}, clientRequestTime: 1537075299674}
FileSystemException: Exists failed, path = 'C:\bitbucket\havapp\build\firebase_database\generated\source\r\debug\io' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
#4      _WindowsDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/windows.dart:163:24)
#5      _WindowsDirectoryWatcher._onEvent.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:157:7)
#6      _rootRun (dart:async/zone.dart:1120:38)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#13     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#14     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#15     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
1537076832446 <= {"event":"analysis.outline","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file
1537076832446 <= {"event":"analysis.overrides","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","overrides":[]}}
1537076832524 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1537076832524 <= {"event":"analysis.implemented","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","classes":[],"members":[]}}
1537077032216 => {"id":"17","method":"analysis.setPriorityFiles","params":{"files":["C:\\bitbucket\\havapp\\pubspec.yaml"]},"clientRequestTime":1537077032216}
1537077032216 => {"id":"18","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["C:\\bitbucket\\havapp\\pubspec.yaml"],"CLOSING_LABELS":["C:\\bitbucket\\havapp\\pubspec.yaml"]
1537077032404 <= {"id":"17"}
1537077032404 <= {"id":"18"}
1537077046044 <= {"event":"analysis.flushResults","params":{"files":["C:\\bitbucket\\havapp\\pubspec.lock"]}}
1537077046044 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1537077046153 <= {"event":"analysis.errors","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","errors":[]}}
1537077046263 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1537077077917 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1537077078167 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1537077086139 => {"id":"19","method":"analysis.setPriorityFiles","params":{"files":["C:\\bitbucket\\havapp\\lib\\main.dart"]},"clientRequestTime":1537077086139}
1537077086139 => {"id":"20","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["C:\\bitbucket\\havapp\\lib\\main.dart"],"CLOSING_LABELS":["C:\\bitbucket\\havapp\\lib\\main.da
1537077086139 <= {"id":"19"}
1537077086139 <= {"id":"20"}
1537077086155 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1537077086342 <= {"event":"analysis.errors","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","errors":[]}}
1537077086342 <= {"event":"analysis.highlights","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUILT_IN","offset":0,"length":6
1537077086342 <= {"event":"analysis.navigation","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":29,"length":31,"targets":[1]},{"off
1537077086342 <= {"event":"analysis.closingLabels","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","labels":[{"offset":3088,"length":709,"label":"MaterialApp"},{"offset":3188,"length":199,"la
1537077086358 <= {"event":"analysis.outline","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file
1537077086358 <= {"event":"analysis.overrides","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","overrides":[]}}
1537077086358 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1537077086358 <= {"event":"analysis.implemented","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","classes":[],"members":[]}}
1537077086373 => {"id":"21","method":"edit.getAssists","params":{"file":"C:\\bitbucket\\havapp\\lib\\main.dart","offset":3388,"length":0},"clientRequestTime":1537077086373}
1537077086389 <= {"id":"21","result":{"assists":[]}}
1537077125232 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\\bitbucket\\havapp], excluded: 
```

```
Dart analysis server, SDK version 2.1.0-edge.ccb16f72824374163562364bf19dd18e8a882fab, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\bitbucket\havapp], excluded: [C:\bitbucket\havapp\.idea, C:\bitbucket\havapp\.dart_tool, C:\bitbucket\havapp\.pub, C:\bitbucket\havapp\build]}, clientRequestTime: 1537075299674}
FileSystemException: Exists failed, path = 'C:\bitbucket\havapp\build\firebase_database\generated\source\r\debug\io' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap

**Comment by stereotype441** [comment] 2018-10-23 03:47
Duplicate of #34294

**Closed by stereotype441** 2018-10-23 03:47 UTC
Labels: analyzer-server, area-analyzer, type-bug
