### ISSUE TITLE
dart2js: _SyncStarIterable has no type parameter

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32829] opened 2018-04-10 00:52 UTC
`_SyncStarIterable` needs a type parameter `T` so it can implement `Iterable<T>`.
With Dart 1 semantics, it was fine to simply implement `Iterable<dynamic>`, but that does not work in Dart 2.

What is difficult here is that _SyncStarIterable is injected into the program by a JavaScript-level late rewrite. We don't know that the type variables are needed, and at the late-rewrite stage we don't have the ability to generate all type expressions.

```dart
class C<T> {
  foo<U>() {
    return () sync* {
      yield <T,U>{};
    };
  }
}
```
In this example, the returned closure must return a subtype of `Iterable<Map<T, U>>` (inferred by the front-end).
The code for the body of the closure can't be used to generate the type.
One option would be for the closure to have a $signature-like method to generate the type parameters of `_SyncStarIterable`.  Then the construction could be changed from

```js
return _SyncStarIterable(function);
```
to:
```js
return _SyncStarIterable(function, this._f());
```
where `_f` is the method that returns the type parameters.
There would have to be a `_f` for each method that returns a sync* Iterable (in the closure case, there is a single method is 'call').

**Comment by sigmundch** [comment] 2018-05-03 20:28
closing as a likely duplicate of #32830

**Closed by sigmundch** 2018-05-03 20:28 UTC
Labels: P1 high, State: started, area-dart2js
