### ISSUE TITLE
crash on Raspberry Pi

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#37279] opened 2019-06-16 14:38 UTC
My Dart based service runs fine on the Raspberry pi, but when I signal it to stop, I get the following. Any pointers to help me track this down would be most appreciated.

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x24
version=2.3.1 (Tue May 21 19:28:38 2019 +0200) on "linux_arm"
thread=612, isolate=(null)((nil))
  pc 0x01967460 fp 0x6e63e798 unw_get_proc_info
  pc 0x01966174 fp 0x6e63e7e0 __aeabi_unwind_cpp_pr0
  pc 0x7666ce40 fp 0x6e63ed98 /lib/arm-linux-gnueabihf/libgcc_s.so.1+0x19e40
-- End of DumpStackTrace

**Comment by rmacnak-google** [comment] 2019-06-18 17:37
This looks like an error attempting to produce a stack trace on a non-VM thread.

Can you get a full stack trace from gdb or provide instructions for reproducing?

**Comment by danrubel** [comment] 2019-06-18 18:05
I'll see what I can discover using gdb.

**Comment by a-siva** [comment] 2019-07-02 16:48
no updates received, closing issue as obsolete.

**Closed by a-siva** 2019-07-02 16:48 UTC
Labels: area-vm

**Comment by danrubel** [comment] 2019-07-02 16:55
Sorry for the slow response. I recently tracked it down to some native code where I'm calling `pthread_create`... which apparently works fine until the thread exits. I'm planning to rework it to push that native thread's work in native code that is run in an isolate so that I don't have to call `pthread_create` at all. If there is a better way to approach this, please let me know.
