### ISSUE TITLE
VM initialization state causes shutdown races in `--hot-reload-test-mode`

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#46931] opened 2021-08-17 12:09 UTC
The commit 1f405bf163c64ec732c3a6d604033da0b439628b has added VM initialization state. This seemingly leads to shutdown assertions in debug mode when running with `--hot-reload-test-mode `.

For example the following test (from [tests/lib/isolate/isolate_import_test.dart](https://github.com/dart-lang/sdk/blob/master/tests/lib/isolate/isolate_import_test.dart)):
```dart
import 'dart:isolate';
import 'package:async_helper/async_helper.dart';

void entry(msg) {}

main() {
  asyncStart();
  Isolate.spawn(entry, null).whenComplete(asyncEnd);
}
```

can hit the following assertion in [runtime/vm/kernel_isolate.cc](https://github.com/dart-lang/sdk/blob/master/runtime/vm/kernel_isolate.cc#L439) :
```c++
class KernelCompilationRequest : public ValueObject {
 public:
  KernelCompilationRequest()
      : monitor_(),
        port_(Dart_NewNativePort("kernel-compilation-port",
                                 &HandleResponse,
                                 false)),  // <-- This will return ILLEGAL_PORT
        next_(NULL),
        prev_(NULL) {
    ASSERT(port_ != ILLEGAL_PORT);  // <-- Which makes us hit this ASSERT.
    RegisterRequest(this);
    result_.status = Dart_KernelCompilationStatus_Unknown;
    result_.error = NULL;
    result_.kernel = NULL;
    result_.kernel_size = 0;
  }
```

The main isolate triggers an isolate spawn and then finishes, which will end up calling `Dart_Cleanup()`. Concurrently the helper isolate is going to call the CFE for a hot-reload request.

Maybe we should not disable Dart API calls until actually all isolates are dead.

/cc @a-siva Could you take a look?

**Comment by a-siva** [comment] 2021-08-17 16:26
This appears to be a duplicate of https://github.com/dart-lang/sdk/issues/46922, please see https://dart-review.googlesource.com/c/sdk/+/210302 for a potential fix.

**Comment by a-siva** [comment] 2021-08-18 18:21
Closed as duplicate.

**Closed by a-siva** 2021-08-18 18:21 UTC
Labels: area-vm, closed-duplicate
