### ISSUE TITLE
[CFE] co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06  crashes compiler

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#53232] opened 2023-08-16 09:59 UTC
Test https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Extension-types/static_analysis_extension_types_A26_t01.dart crashes the compiler. [Log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8772621200645911537/+/u/test_results/new_test_failures__logs_)
```
/========================================================================================================================\
| co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06 is new and failed (Crash, expected Pass) |
\========================================================================================================================/

--- Command "fasta" (took 107ms):
(cd /b/s/w/ir/ ; DART_CONFIGURATION=ReleaseX64 ./out/ReleaseX64/dart ./pkg/front_end/tool/_fasta/compile.dart --verify --skip-platform-verification -o ./out/ReleaseX64/generated_compilations/cfe-strong-linux/tests_co19_src_LanguageFeatures_Extension-types_static_analysis_extension_types_A21_t06/out.dill --platform ./out/ReleaseX64/vm_platform_strong.dill -Dtest_runner.configuration=cfe-strong-linux --enable-experiment=inline-class --nnbd-strong --packages=./.dart_tool/package_config.json ./tests/co19/src/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06.dart )

exit code:
253

stdout:
tests/co19/src/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06.dart:26:16: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: StaticInvocation with incompatible arguments for 'ET1|c'.
  factory ET1.f(int id) = ET1.c;
               ^
tests/co19/src/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06.dart:26:11: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: StaticInvocation with incompatible arguments for 'ET1|c'.
  factory ET1.f(int id) = ET1.c;
          ^
tests/co19/src/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06.dart:34:16: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: StaticInvocation with incompatible arguments for 'ET2|n'.
  factory ET2.f(int id) = ET2.n;
               ^
tests/co19/src/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06.dart:34:11: Error: Verification of the generated program failed:
Target=vm, VerificationStage.afterModularTransformations: StaticInvocation with incompatible arguments for 'ET2|n'.
  factory ET2.f(int id) = ET2.n;
          ^

stderr:
Unhandled exception:
  Crash when compiling:
'package:front_end/src/fasta/kernel/kernel_target.dart': Failed assertion: line 1619 pos 12: 'allowVerificationErrorForTesting || errors.isEmpty': Verification errors found.

#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      KernelTarget._verify (package:front_end/src/fasta/kernel/kernel_target.dart:1619:12)
#3      KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:635:9)
<asynchronous suspension>
#4      withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#5      KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:576:12)
<asynchronous suspension>
#6      CompileTask.compile (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:436:19)
<asynchronous suspension>
#7      BatchCompiler.batchCompileImpl (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:221:5)
<asynchronous suspension>
#8      CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139:3)
<asynchronous suspension>
#9      runProtectedFromAbort (file:///b/s/w/ir/pkg/front_end/tool/_fasta/command_line.dart:416:12)
<asynchronous suspension>
#10     BatchCompiler.run (file:///b/s/w/ir/pkg/front_end/tool/_fasta/entry_points.dart:173:13)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n cfe-strong-linux co19/LanguageFeatures/Extension-types/static_analysis_extension_types_A21_t06
```

**Comment by chloestefantsova** [comment] 2023-10-17 10:10
Closing this as a duplicate of https://github.com/dart-lang/sdk/issues/53140.

**Closed by chloestefantsova** 2023-10-17 10:10 UTC
Labels: area-front-end, crash, feature-inline-classes, cfe-feature-extension-types
