### ISSUE TITLE
Hitting "unreachable code" in the VM.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#26314] opened 2016-04-21 13:22 UTC
I just encountered a build-failure (link will go stale at some point in the future):
https://build.chromium.org/p/client.dart/builders/vm-linux-release-ia32-optcounter-threshold-be/builds/433/steps/checked%20vm%20tests/logs/stdio

Relevant section:
```
FAILED: none-vm-checked release_ia32 language/flatten_test/01
Expected: Pass 
Actual: Crash
Runtime error expected.
CommandOutput[vm]:

stderr:
runtime/vm/object.cc:15518: error: unreachable code


Command[vm]: DART_CONFIGURATION=ReleaseIA32 out/ReleaseIA32/dart --enable_asserts --enable_type_checks --optimization-counter-threshold=5 --ignore-unrecognized-flags --package-root=out/ReleaseIA32/packages/ /mnt/data/b/build/slave/vm-linux-release-ia32-optcounter-threshold-be/build/sdk/out/ReleaseIA32/generated_tests/language/flatten_test_01.dart
Took 0:00:00.322339

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 --write-debug-log --write-test-outcome-log --copy-coredumps --vm-options --optimization-counter-threshold=5 --exclude-suite pkg --checked -t60 language/flatten_test/01
```

This happened with revision 84ec63e9fc404a6caafc53dbdf75e45907301818

**Comment by rmacnak-google** [comment] 2016-04-21 16:38
@crelier 
https://github.com/dart-lang/sdk/blob/84ec63e9fc404a6caafc53dbdf75e45907301818/runtime/vm/object.cc#L15518

**Comment by crelier** [comment] 2016-05-04 21:26
Duplicate of #26101.

**Closed by crelier** 2016-05-04 21:26 UTC
Labels: area-vm, Resolution: duplicate
