### ISSUE TITLE
Missing type arguments in inference test

### ISSUE THREAD

**Issue by aartbik** [dart-lang/sdk#36284] opened 2019-03-20 20:29 UTC
Just looking at

```dart
void testTopDownInference() {
  // Maps.
  Map<K, V> expectIntStringMap<K, V>() {
    Expect.identical(int, K);
    Expect.identical(String, V);
    return {};
  }

  // The context element type is pushed into the spread expression if it is
  // Map<K, V>.
  Expect.mapEquals(<int, String>{}, <int, String>{...expectIntStringMap()});
}
```

We get the incorrect IR:

```
    t0 <- Constant(#TypeArguments: (@0x7f06c0b0bac1 H19efd8c1) 
                               [Type: class 'int'] 
                               [Type: class 'String'])
    PushArgument(t0)
    t0 <- Constant(#_ImmutableList len:0)
    PushArgument(t0)
    t0 <- StaticCall:14( Map._fromLiteral@0150898<0> t0, t0)
    ....
    t0 <- Constant(#TypeArguments: null)
    t1 <- LoadLocal(expectIntStringMap @-2)      // should be int/String
```

The omission is already at kernel level, see below (expectIntStringMap.call<dynamic, dynamic>).

```
   exp::Expect::mapEquals(<core::int, core::String>{}, block {
       final core::Map<core::int, core::String> #t1 = <core::int, core::String>{};
       for (final core::MapEntry<core::int, core::String> #t2 in [@vm.call-site-attributes.metadata=receiverType:<K extends dart.core::Object = dynamic, V extends dart.core::Object = dynamic>() → dart.core::Map<K, V>] expectIntStringMap.call<dynamic, dynamic>().{core::Map::entries})
         [@vm.call-site-attributes.metadata=receiverType:dart.core::Map<dart.core::int, dart.core::String>] #t1.{core::Map::[]=}(#t2.{core::MapEntry::key}, #t2.{core::MapEntry::value});
     } =>#t1);
```

**Comment by kmillikin** [comment] 2019-03-21 04:45
Closing as a duplicate of https://github.com/dart-lang/sdk/issues/36223.

**Closed by kmillikin** 2019-03-21 04:45 UTC
Labels: area-front-end
