### ISSUE TITLE
Please merge 4789a442d36522e4517b74b291488611c960c264 into dev channel

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/sdk#38977] opened 2019-10-18 15:01 UTC
**commit(s) to merge**: 4789a442d36522e4517b74b291488611c960c264

**merge instructions**: https://dart-review.googlesource.com/c/sdk/+/122146

**reason**: Fixes https://github.com/dart-lang/sdk/issues/38912 which affects dart2native which releases with this Dart release.

/cc @dgrove @kevmoo @mit-mit @whesse @athomas

Note: The test added in this CL unfortunately fails on Windows, but this is being addressed in https://dart-review.googlesource.com/c/sdk/+/122145.

**Comment by athomas** [comment] 2019-10-21 10:30
FYI, the test fix for Windows is mentioned in a separate cherry-pick request:
https://github.com/dart-lang/sdk/issues/38983

**Comment by athomas** [comment] 2019-10-21 11:49
I'm assuming this is actually a request to merge 8d8faa7dea152cce83681bad4467dac87a30f7de into dev so then it's a duplicate of #38983.

`git cherry-pick 8d8faa7dea152cce83681bad4467dac87a30f7de` has no conflicts, so we don't actually need merge instructions here.

The diffs for 4789a442d36522e4517b74b291488611c960c264 and 8d8faa7dea152cce83681bad4467dac87a30f7de are identical as well.

@mkustermann FYI

**Closed by athomas** 2019-10-21 11:49 UTC
Labels: merge-to-dev
