### ISSUE TITLE
No error in CFE for not regular-bounded type

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#46288] opened 2021-06-08 07:54 UTC
The following `co19_2` (legacy, dart 2.9) [test](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/Instantiate-to-bound/typedef/static/typedef_l2_06_t04.dart) fails on CFE. There is an expected error in analyzer but no such error on CFE
The test is 
```dart
// @dart = 2.9

class A<X> {}
typedef G<X extends A<Y>, Y extends A<X>> = Y Function(X, Y);

main() {
  G source;
//^
// [analyzer] unspecified
// [cfe] unspecified
}
```
Tested on edge version of SDK

**Comment by stefantsov** [comment] 2021-06-08 09:00
I think it's because in the pre-NNBD Dart the variance of the type parameters of typedefs is ignored during checks, that is, the checks are performed as if the variance was **covariant**. So I think it works as intended. @eernstg WDYT about my evaluation?

**Comment by eernstg** [comment] 2021-06-08 13:10
The language specification says (since bfa8be887a980cba385fbfad2b9a129a4c7e3eb4, Jun 5 2018) that the type parameters of a type alias have a variance which is determined by the occurrences of that type variable in the body, but there was a long period of time where this wasn't implemented (nor tested) fully, and the analyzer and the CFE disagreed. 

We should close this issue with 'closed-not-planned' because we value stability over smaller fixes for legacy code. The test should then be marked `SkipByDesign` in the relevant status file (it should actually be something like `SkipNotPlanned`, but we don't have that), with a comment that mentions this issue. It's probably a good idea to mention in the status file that there are no plans to make changes such that this test will succeed in the given configuration.

**Closed by eernstg** 2021-06-08 13:10 UTC
Labels: area-front-end, closed-not-planned, front-end-missing-error
