### ISSUE TITLE
Directory watcher access denied error

### ISSUE THREAD

**Issue by JimHume** [dart-lang/sdk#34970] opened 2018-10-29 19:26 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

# Exception

Please append the contents of:
file://C:\Users\JIMHUM~1\AppData\Local\Temp\report.txt

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Jim Hume\source\repos\[redacted]], excluded: [C:\Users\Jim Hume\source\repos\[redacted]\.idea, C:\Users\Jim Hume\source\repos\[redacted]\.dart_tool, C:\Users\Jim Hume\source\repos\[redacted]\.pub, C:\Users\Jim Hume\source\repos\[redacted]\build, C:\Users\Jim Hume\source\repos\[redacted]\[redacted]\.dart_tool, C:\Users\Jim Hume\source\repos\[redacted]\[redacted]\.pub, C:\Users\Jim Hume\source\repos\[redacted]\[redacted]\build]}, clientRequestTime: 1540828120630}
FileSystemException: Exists failed, path = 'C:\Users\Jim Hume\source\repos\[redacted]\build\connectivity\intermediates\transforms\mergeJniLibs\debug' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap


The appended report.txt (the lines are cut off for some reason) with some lines removed.
```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\Users\Jim Hume\source\repos\[redacted]], excluded: [C:\Users\Jim Hume\source\repos\[redacted]\.idea, C:\Users\Jim Hume\source\repos\[redacted]\.dart_tool, C:\Users\Jim Hume\source\repos\[redacted]\.pub, C:\Users\Jim Hume\source\repos\[redacted]\build, C:\Users\Jim Hume\source\repos\[redacted]\[redacted]\.dart_tool, C:\Users\Jim Hume\source\repos\[redacted]\[redacted]\.pub, C:\Users\Jim Hume\source\repos\[redacted]\[redacted]\build]}, clientRequestTime: 1540828120630}
FileSystemException: Exists failed, path = 'C:\Users\Jim Hume\source\repos\[redacted]\build\connectivity\intermediates\transforms\mergeJniLibs\debug' (OS Error: Access is denied.
, errno = 5)
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _WindowsDirectoryWatcher._eventsBasedOnFileSystem (package:watcher/src/directory_watcher/windows.dart:324:41)
#2      _WindowsDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:166:13)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#4      _WindowsDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/windows.dart:163:24)
#5      _WindowsDirectoryWatcher._onEvent.<anonymous closure> (package:watcher/src/directory_watcher/windows.dart:157:7)
#6      _rootRun (dart:async/zone.dart:1120:38)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#13     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#14     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#15     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#16     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
1540840791199 <= {"event":"analysis.overrides","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\env\\jim.dart","overrides":[{"offset":151,"length":11,"superclassMember":
1540840791911 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\screens\\notifications\\notification_list_builder.dart","errors":[{"severity":"INFO"
1540840791998 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\screens\\notifications\\notifications_screen.dart","errors":[{"severity":"INFO","typ
1540840792118 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\app.dart","errors":[]}}
1540840792139 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\env\\person1.dart","errors":[]}}
1540840792156 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\env\\person2.dart","errors":[]}}
1540840792175 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\env\\person3.dart","errors":[]}}
1540840792195 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\env\\person4.dart","errors":[]}}
1540840792213 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\env\\staging.dart","errors":[]}}
1540840792245 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\routes.dart","errors":[]}}
1540840792305 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\route_handlers.dart","errors":[{"severity":"INFO","type":"HINT","location":{
1540840792394 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\main.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\Users\
1540840793401 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\screens\\settings_screen.dart","errors":[{"severity":"INFO","type":"HINT","location"
1540840793907 <= {"event":"analysis.errors","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\widgets\\common\\app_search_bar.dart","errors":[]}}
1540840793944 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1540840793945 <= {"event":"analysis.implemented","params":{"file":"C:\\Users\\Jim Hume\\source\\repos\\[redacted]\\lib\\config\\env\\jim.dart","classes":[],"members":[]}}
1540840802953 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\\Users\\Jim Hume\\source\\repos
```

**Comment by stereotype441** [comment] 2018-10-30 23:18
Duplicate of #34294

**Closed by stereotype441** 2018-10-30 23:18 UTC
Labels: area-analyzer
