### ISSUE TITLE
MyWebsocket need handle ping pong

### ISSUE THREAD

**Issue by 1AlexFix1** [dart-lang/sdk#36728] opened 2019-04-24 11:03 UTC
Hello, We need to know when was ping and pong.
I also looked at the WebSocket class from the dart.io package and could not send where pingInterval is used. The _WebSocketImpl implementation is closed.
The problem is that the connection often disappears in GoingAway if the ping interval is below 10 seconds

**Comment by devoncarew** [comment] 2019-04-24 16:09
It looks like this is a request to open up more of the websocket implementation as API.

**Comment by devoncarew** [comment] 2019-04-24 16:10
@a-siva, which engineer maintains `dart:io` now?

**Comment by athomas** [comment] 2019-04-24 16:16
That's @sortie now.

**Comment by 1AlexFix1** [comment] 2019-04-25 13:43
> It looks like this is a request to open up more of the websocket implementation as API.

We checked how ping-pong works, and from the documentation it was not very clear, at the moment when pintInterval works as follows, sends ping requests waiting for pong, and when pong arrives, ping will be sent only after the remaining period of time. As far as I know, the usual ping-pong behavior is ping once a second, and if the pong does not return during pingInterval, the socket closes

**Comment by StanevDev** [comment] 2020-04-13 10:34
I'm develop mobile flutter app witch use websocket, and have issue with long-live connections,  before 20 minutes connection socket don't send messages to backend & don't receive them.
pingInterval setting did not help and I can't debug private implementation of ping-pong.

**Comment by sortie** [comment] 2020-05-05 13:48
@zichangg Can you confirm if this is a duplicate of the issue you recently fixed?

**Comment by zichangg** [comment] 2020-05-06 02:47
@StanevDev Could you please verify what version of dart you are using?

**Comment by sortie** [comment] 2020-05-06 08:31
@zichangg Note this is an old issue from long before your fixes. I'm trying to determine whether it is a duplicate issue and whether it can be closed as such. If you don't think we have enough information to diagnose it, then you can add the needs-info label and the issue will be auto-closed if no-one responds for a while.

**Comment by zichangg** [comment] 2020-05-06 16:24
@sortie From the description, I think this is a duplicate.
My fix went in about 2 months ago, but @StanevDev 's comment is very recent, it is probably a different issue.

**Comment by StanevDev** [comment] 2020-05-15 11:19
@zichangg Dart version is 2.8.1. I found out that problem is in background app state.

**Comment by zichangg** [comment] 2020-05-15 16:49
@StanevDev Sounds good. I'll close the issue.

**Closed by zichangg** 2020-05-15 16:49 UTC
Labels: area-library, library-io, needs-info, type-enhancement

**Comment by sportmachine** [comment] 2023-02-26 07:07
can someone give an example? the example in test are just the basic. while so many difference code are so diverse. I have tried many, most don't work as what Tomcat did.
