### ISSUE TITLE
Dart analysis server Error

### ISSUE THREAD

**Issue by AiHMin** [dart-lang/sdk#34977] opened 2018-10-30 07:12 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14 unknown, screens 1440x900  Retina`

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/am/dev/projects/flutter/learn/smart_qfnu/lib/bloc/notification_bloc.dart context: exception_20181030_150930_322
Exception: Element not found in summary: package:rxdart/src/subjects/publish_subject.dart;package:rxdart/src/subjects/publish_subject.dart;Observable
#0      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:308:9)
#1      ElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:345:42)
#2      ClassElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:35:43)
#3      ClassElementHandle.type (package:analyzer/src/dart/element/handle.dart:111:29)
#4      _ReferenceInfo._buildType.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:996:48)
#5      InterfaceTypeImpl.typeArguments (package:analyzer/src/dart/element/type.dart:1389:26)
#6      DeclarationResolver._setGenericFunctionType (package:analyzer/src/generated/declaration_resolver.dart:523:37)
#7      DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:476:7)
#8      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11481:15)
#9      FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4387:17)
#10     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:834:10)
#11     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:197:11)
#12     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4382:49)
#13     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#14     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1795:13)
#15     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:690:10)
#16     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:89:13)
#17     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:543:13)
#18     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:88:5)
#19     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1765:49)
#20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8304:20)
#21     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2437:21)
#22     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:714:10)
#23     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2430:49)
#24     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:51:12)
#25     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:566:31)
#26     LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:102:9)
#27     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#28     LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:101:13)
#29     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:78:14)
<asynchronous suspension>
#30     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:222:21)
<asynchronous suspension>
#31     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:77:43)
<asynchronous suspension>
#32     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1244:71)
<asynchronous suspension>
#33     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52:21)
<asynchronous suspension>
#34     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1220:20)
<asynchronous suspension>
#35     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1025:23)
<asynchronous suspension>
#36     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1916:24)
<asynchronous suspension>
#37     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1857:5)
#38     new AnalysisServer (package:analysis_server/src/analysis_server.dart:397:29)
#39     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:81:26)
#40     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:504:21)
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:550:12)
#47     Driver.start (package:analysis_server/src/server/driver.dart:502:7)
#48     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#49     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#50     main (file:///b/build/slave/Mac_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#51     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
1540883369963 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/models/upload_photo_model.dart","errors":[]}}
1540883369964 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/models/login_model.dart","errors":[]}}
1540883369964 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/models/response_model.dart","errors":[]}}
1540883370088 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/main.dart","errors":[]}}
1540883370094 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/service/news_service.dart","errors":[]}}
1540883370095 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/service/notification_service.dart","errors":[]}}
1540883370097 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/demo/clip_test.dart","errors":[]}}
1540883370100 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/photo_view_page.dart","errors":[]}}
1540883370101 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/every_day/address_book_page.dart","errors":[]}}
1540883370102 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/home/notification_page.dart","errors":[]}}
1540883370103 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/home/news_page.dart","errors":[]}}
1540883370107 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/home/every_day_page.dart","errors":[]}}
1540883370109 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/home/my_info_page.dart","errors":[]}}
1540883370110 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/webview_page.dart","errors":[]}}
1540883370113 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/splash_page.dart","errors":[]}}
1540883370114 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/login_page.dart","errors":[]}}
1540883370115 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/home_page.dart","errors":[]}}
1540883370116 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/skill_details_page.dart","errors":[]}}
1540883370120 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/award_details_page.dart","errors":[]}}
1540883370121 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/part_time_page.dart","errors":[]}}
1540883370122 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/award_edit.dart","errors":[]}}
1540883370128 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/skill_page.dart","errors":[]}}
1540883370129 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/my_details_page.dart","errors":[]}}
1540883370130 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/award_page.dart","errors":[]}}
1540883370131 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/change_password_page.dart","errors":[]}}
1540883370136 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/pages/my/skill_edit.dart","errors":[]}}
1540883370137 => {"id":"6","method":"analysis.updateContent","params":{"files":{"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/bloc/notification_bloc.dart":{"type":"add","content":"import 'base_
1540883370139 <= {"event":"analysis.errors","params":{"file":"/Users/am/dev/projects/flutter/learn/smart_qfnu/lib/widgets/image_swiper.dart","errors":[]}}
1540883370148 <= {"id":"6","result":{}}
1540883370382 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/am/dev/projects/flutter/learn/smart_qfnu/lib/bloc/notification_bloc.dart context: exception_201810
```

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: /Users/am/dev/projects/flutter/learn/smart_qfnu/lib/bloc/notification_bloc.dart context: exception_20181030_150930_322
Exception: Element not found in summary: package:rxdart/src/subjects/publish_subject.dart

**Comment by stereotype441** [comment] 2018-10-30 23:03
Duplicate of #34555

**Closed by stereotype441** 2018-10-30 23:03 UTC
Labels: area-analyzer
