### ISSUE TITLE
Runtime error on buildbot

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27758] opened 2016-11-04 11:13 UTC
Fyi: https://build.chromium.org/p/client.dart/builders/vm-mac-debug-simdbc64-be/builds/28/steps/checked%20vm%20tests/logs/stdio

Copying the relevant parts (in case the link goes stale):
```
FAILED: none-vm-checked debug_simdbc64 service/debugging_inlined_finally_test
Expected: Pass 
Actual: RuntimeError
CommandOutput[vm]:

stdout:
** Launching SERVICE_TEST_TESTEE=true xcodebuild/DebugSIMDBC64/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/.packages --enable-vm-service:0 /b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/runtime/observatory/tests/service/debugging_inlined_finally_test.dart
>testee>out> Observatory listening on http://127.0.0.1:51812/
** Signaled to run test queries on http://127.0.0.1:51812/
>testee>out> 
Loading VM...
Done loading VM
Running debugging_inlined_finally_test.dart [1/12]
Paused with PauseBreakpoint
Running debugging_inlined_finally_test.dart [2/12]
Running debugging_inlined_finally_test.dart [3/12]
Running debugging_inlined_finally_test.dart [4/12]
Paused with PauseBreakpoint
Running debugging_inlined_finally_test.dart [5/12]
Running debugging_inlined_finally_test.dart [6/12]
>testee>err> /b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/runtime/vm/object.cc: 14582: error: expected: !is_optimized() || (pc_offset == UncheckedEntryPoint() - PayloadStart())
>testee>err> Dumping native stack trace for thread 1203
>testee>err>   [0x0000000102176288] dart::Profiler::DumpStackTrace(bool)
>testee>err>   [0x0000000102176288] dart::Profiler::DumpStackTrace(bool)
>testee>err>   [0x000000010228661c] double_conversion::Vector<char const>::SubVector(int, int)
>testee>err>   [0x000070000060cd80] Unknown symbol
>testee>err> -- End of DumpStackTrace


stderr:
Unhandled exception:
Testee exited with -6
#0      _ServiceTesteeLauncher.launch.<anonymous closure>.<anonymous closure> (file:///b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/runtime/observatory/tests/service/test_helper.dart:248:11)
#1      _RootZone.runUnary (dart:async/zone.dart:1404)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#5      _Future._completeWithValue (dart:async/future_impl.dart:477)
#6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


Command[vm]: DART_CONFIGURATION=DebugSIMDBC64 xcodebuild/DebugSIMDBC64/dart --enable_asserts --enable_type_checks --error_on_bad_type --error_on_bad_override --ignore-unrecognized-flags --packages=/b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/.packages /b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/runtime/observatory/tests/service/debugging_inlined_finally_test.dart
Took 0:00:07.806782

Short reproduction command (experimental):
    python tools/test.py -asimdbc64 --write-debug-log --write-test-outcome-log --copy-coredumps --exclude-suite pkg --checked -t480 --packages /b/build/slave/vm-mac-debug-simdbc64-be/build/sdk/.packages service/debugging_inlined_finally_test
```

**Comment by fsc8000** [comment] 2016-11-04 11:41
Duplicate of #27746. I tried skipping some, but the crashes are flaky. @rmacnak-google has a fix for this.

**Closed by fsc8000** 2016-11-04 11:41 UTC
Labels: area-vm, Resolution: duplicate
