### ISSUE TITLE
Analyzer Feedback from IntelliJ - Nested List

### ISSUE THREAD

**Issue by mu10** [dart-lang/sdk#43933] opened 2020-10-27 00:47 UTC
When I write nested list like `List<List<String>> nested;`, the analyzer seems stop responding. The `List` word get red underlined saying "List isn't a type", and dart app shows high power usage on Task Manager. It seems doing infinite loop, my CPU fan goes buzzing.
Am I the only one who has this?
I can't write any nested list.

## Version information

- `IDEA AI-201.8743.12.41.6858069`
- `2.10.2`
- `AI-201.8743.12.41.6858069, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

**Comment by srawlins** [comment] 2020-11-25 17:46
@mu10 That is pretty wild behavior. Thanks for the report. Does this happen even in an otherwise empty file?

**Comment by bwilkerson** [comment] 2020-11-25 18:04
I saw another report recently that was similar. IIRC it was about code completing in a case like `A<B<^>>`. It's possible that they might have a common root cause. I haven't looked into the other issue, so I have no additional information.

**Comment by mu10** [comment] 2020-11-26 01:22
Finally got respond.

> @mu10 That is pretty wild behavior. Thanks for the report. Does this happen even in an otherwise empty file?

Yes, it happens even on a new Flutter project. Every time I wrote nested list, lint just stop working (I still can write, but all text are white -the first `List` word are red underlined) and then cpu buzzing, and I have to close it.

Anyway, I've been working with Android Studio for years, but this thing makes me have to try VSCode. The performance for Flutter project in it is staggering, it's way way way feels better and faster. Somehow this misfortune makes me really happy, I highly recommended doing Flutter project on VSCode. Though, I still wants this get fixed.

**Comment by srawlins** [comment] 2021-07-20 05:38
Looks like https://github.com/dart-lang/sdk/issues/43572 as well.

**Comment by srawlins** [comment] 2024-04-05 14:31
#43572 has been closed; I'm closing this for now; please let us know if this is encountered again.

**Closed by srawlins** 2024-04-05 14:31 UTC
Labels: area-analyzer, P2, type-bug, analyzer-crash-report
