### ISSUE TITLE
Flutter code assist issues

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#32135] opened 2018-02-13 09:54 UTC
Couple of assist issues:

1. Don't show 'Center widget' if invoked on a `Center widget`
1. Show all the Wrap ones next to each other
1. `Replace with children` is confusing; it has a `child`. Should this just be `Delete widget`?

<img width="478" alt="screen shot 2018-02-13 at 10 52 25" src="https://user-images.githubusercontent.com/13644170/36143681-0c2c9e14-10ac-11e8-9c3a-aa5ba65899d4.png">

**Comment by mit-mit** [comment] 2018-02-13 09:54
This was tested with sdk-dev.24

**Comment by bwilkerson** [comment] 2018-02-13 15:14
@devoncarew

**Comment by DanTup** [comment] 2018-02-13 15:55
Maybe related: https://github.com/Dart-Code/Dart-Code/issues/558

I have a screenshot there showing the quickfixes in the wrong order. I checked the log and it seemed like the server returned them in the correct order. However, I have not been able to reproduce. I believe the order is supposed to be "by severity of the related diagnostic" and then the order they were given. None of these have diagnostics so I'd expect them to appear in the order the server provides them.

Ofc it's possible the order shown here is the order from the server; that could be checked by [enabling logging](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging).

**Comment by devoncarew** [comment] 2018-02-13 15:57
1. sgtm
2. perhaps we should just lexically sort the assist on the server before returning them, so the order to predictable (and stable) for the user?
3. I'm comfortable with this continuing to be called `Replace with children` - changing the name significantly based on the arity may make it harder to locate for users.

/cc @scheglov

**Comment by bwilkerson** [comment] 2018-02-13 16:21
> perhaps we should just lexically sort the assist on the server before returning them, so the order to predictable (and stable) for the user?

We currently have a priority associated with assists so that we can sort them by relevance. I'm not sure whether that's better than alphabetic, but it isn't arbitrary and ought to be stable. (That's not to say that the current priorities are correct.)

**Comment by scheglov** [comment] 2018-02-13 18:06
1. https://dart-review.googlesource.com/c/sdk/+/40920
2. https://dart-review.googlesource.com/c/sdk/+/40880
3. no-op

**Comment by mit-mit** [comment] 2018-02-13 18:40
@devoncarew 

> I'm comfortable with this continuing to be called Replace with children - changing the name significantly based on the arity may make it harder to locate for users.

Why not avoid the arity entirely, and just call it 'Delete widget'?

**Comment by bwilkerson** [comment] 2018-02-13 18:43
FWIW, 'Delete widget' sounds to me like "delete this widget and all of its children"; similar to delete directory, I wouldn't expect the children to still be there.

**Comment by mit-mit** [comment] 2018-02-13 18:47
@bwilkerson yes, I agree that is probably what some might think, but I think it's pretty learneable once you try it. I certainly think that the confusion over the differences between 'Convert to children' and 'Replace with children' is worse.

**Comment by scheglov** [comment] 2018-02-13 18:56
Ah, I see a possible problem.

`Convert to children:` does not belong to `new Center`.
We should show it only when the caret is on the `child:` name of the named argument.
So, it will not be displayed at the same time as `Replace with children`.

**Comment by DanTup** [comment] 2018-02-13 19:23
> FWIW, 'Delete widget' sounds to me like "delete this widget and all of its children"

Would "Remove widget" be any better? Seems a little less destructive? "Replace with children" does seem a bit weird to me.

Or, can we not put the name of the widget that's being removed in there? "Remove Center" or similar might be a bit more obvious? That seems more like what you'd tell someone to do if you were pointing at their screen wanting them to make that change.

**Comment by scheglov** [comment] 2018-02-13 19:47
OK, I will rename it in Analysis Server and Flutter plugin.
https://dart-review.googlesource.com/c/sdk/+/40961

**Comment by scheglov** [comment] 2018-02-13 21:52
OK, I think these issues are fixed now.

**Closed by scheglov** 2018-02-13 21:52 UTC
Labels: analyzer-quick-fix, area-analyzer

**Comment by DanTup** [comment] 2018-02-19 08:49
@mit-mit 

> 2. Show all the Wrap ones next to each other

FWIW, looks like there was a bug introduced in Code with the CodeAction changes that did break the sort (https://github.com/Microsoft/vscode/issues/43617). Should be fixed in next release.
