### ISSUE TITLE
migration tool should not suggest Set<V?>

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#49824] opened 2022-08-26 14:10 UTC
Migration tool should avoid suggesting `Set<V?>` and probably `Map<K, V?>` when generating migrations. 

It is *highly* unlikely that such types make sense as a migration result. 

I can see that in a large scale migration people blindly accept `Set<V?>` suggestion which leads to meaningless code and potentially unnecessary bang operators down the line. Such migration actively makes code worse.

/cc @davidmorgan @stereotype441 @srawlins

**Comment by stereotype441** [comment] 2022-08-26 14:24
@mraleph do you have examples of problematic cases of `Set<V?>` and `Map<K, V?>` that you've seen?  It would be helpful to look at specific examples in order to try to figure out where the migration tool's heuristics are going wrong.

**Comment by mraleph** [comment] 2022-08-26 15:10
I have not seen `Map<K, V?>` but we have `Set<V?>` in our own migrated code in dartdoc, Flutter and even CFE. 

Here are some examples:

https://cs.opensource.google/search?q=Set%3CString%5C%3F%3E%20language:dart

I have also encountered this in the internal migration, but I now lost the precise file in which this occured.

**Comment by davidmorgan** [comment] 2022-08-29 07:06
I discussed with Slava a bit.

My experience with the migration tool suggesting any generics with `?` is that it will be technically correct, but that usually it is worth investing manual effort to get rid of the `?`. This means figuring out where nulls should be impossible and adding a runtime check at that point. I don't recall seeing cases where the tool should have done that automatically.

Slava suggested that it would be better to have the tool suggest without `?`, because that is likely to be the end goal for the human driving the tool. My impression is that this would not be an improvement. The problem is that if the tool starts without `?`, then the first step the human needs to do is to make the code compile so that the tests can run, and that's likely to involve adding the `?`. It's quicker to iterate on the code to correctly get rid of the `?` in collaboration with tests, because that's where you get evidence for whether _at runtime_ there can be null.

So, I think this is working about as well as it can today. Of course, if there are examples of where the tool should have done better then it'd be good to share them. Thanks.

**Comment by mraleph** [comment] 2022-08-29 07:50
My assumption here (based on the code search) is that some people overlook `?` and do not change it, that's why I think it is better to go with non-nullable option first and allow users to put `?` if it is semantically correct (and it almost never is).

I think just changing the tool to treat all sets as `Set<K/*!*/>` is a fine heuristic which would lead to better code in the end.

What I did when I encountered this `Set<...?>` is asked the tool to put `/*!*/` there through UI and run the migration again - after which the result was actually better than with the default choice of `?`.

**Comment by davidmorgan** [comment] 2022-08-29 10:18
Adding `/*!*/` to the Set causes the migration tool to insert `!` in places where values are added to the set, where there were no implicit null checks before. So then your job as the person migrating the code is to verify that these new runtime checks "make sense"; and usually from context + test coverage that's reasonably easy.

With the tool as it is today, you see the generics with `?` then make the change yourself to remove them, and you know that any new `!` that result are new runtime checks you need to be careful about.

The alternative that comes to mind if we want the tool to start with `/*!*/` is that it would visually distinguish behavior preserving `!` from new ones.

But, this seems like a large change, and it's not clear if the end workflow is any better. The "worst case" in the current migration flow is loose static typing; with tighter proposals from the migration tool the worst case is a new runtime error. In both cases we would strongly prefer that the migrator/reviewer spot the issue and do a better migration, but the static looseness is maybe preferable over the runtime exception.

**Comment by mraleph** [comment] 2022-08-29 10:30
Conversely: adding `?` to set key causes migration too to insert `!` when reading from the set (e.g. when iterating) or worse cascade this null-ness further into some other signatures. So no matter the choice there are some `!` appearing and there is something for the user to verify. 

Given this it is better prefer more sensible choice: again I am approaching this from the perspective that in absolute dominating majority of cases sets don't contain `null` as an element.

**Comment by davidmorgan** [comment] 2022-08-29 11:36
> Conversely: adding `?` to set key causes migration too to insert `!` when reading from the set (e.g. when iterating) or worse cascade this null-ness further into some other signatures. So no matter the choice there are some `!` appearing and there is something for the user to verify.

It will cascade the null-ness; at least that's my understanding of how the tool behaves: it won't ever decide "this looks like a bad place from a style point of view to allow nulls".

So the `!` that appear in the tool output were there implicitly before, and that's a good starting point to work from.

This is not 100% true; as with many things in this migration it is more complicated: new runtime checks can arise because static reasoning based on migrated code says they must be there; and the correctness of migrations is not verified until _all_ the code is migrated and sound null safety is turned on. So a too-restrictive earlier migration might cause a failure at runtime by causing a `!` to be inserted.

Collections seem to be usually easy to manage in practice; they are usually created and used in a small scope where it's easy to see what should happen. Streams and non-SDK generic classes present a harder version of the same problem. In the limit, nullability in generics flows through multiple different types which might have inconsistent ideas about nullability. Migrating these can be very hard; but the task is the same: prove as far as possible that the generics do not need `?`.

I wonder if a good way forward would be to have the migration tool insert comments in cases of suspicious changes like nullable generics. Something like "TODO: verify nullability of generics." might work well as it does not match the required TODO format in google3 and so (I think, can check) you will not be able to submit it.

Other known suspicious behavior that could be handled the same includes any cast that changes the generic type, e.g. `Future<T?>` cast to `Future<T>`.

**Comment by stereotype441** [comment] 2023-11-21 21:54
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.

**Closed by stereotype441** 2023-11-21 21:54 UTC
Labels: area-migration
