### ISSUE TITLE
Compiler error.

### ISSUE THREAD

**Issue by MichalMisiaszek** [dart-lang/sdk#39928] opened 2019-12-26 19:10 UTC
MacOS, Chrome. Converting existing app into web app fails.

   dartdevc -k arguments: --kernel --dart-sdk-summary=/Users/michal/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o packages/geolocator/geolocator.ddc.js --source-map --summary=packages/meta/meta.ddc.dill=packages/meta/meta
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/google_api_availability/google_api_availability.ddc.dill=packages/google_api_availability/google_api_availability
    --summary=packages/vector_math/vector_math.ddc.dill=packages/vector_math/vector_math
    --summary=packages/location_permissions/location_permissions.ddc.dill=packages/location_permissions/location_permissions
    --packages=file:///var/folders/v2/pnzcxw9x1kzgmd01x6n_54cc0000gn/T/kernel_builder_WPbvqE/.packages --module-name=packages/geolocator/geolocator
    --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map
    --libraries-file=file:///Users/michal/Development/flutter/bin/cache/flutter_web_sdk/libraries.json
    --used-inputs-file=/var/folders/v2/pnzcxw9x1kzgmd01x6n_54cc0000gn/T/ddk_builder_Tp7EEI/used_inputs.txt package:geolocator/utils/codec.dart
    package:geolocator/models/location_accuracy.dart package:geolocator/models/location_options.dart package:geolocator/geolocator.dart
    package:geolocator/models/position.dart package:geolocator/models/placemark.dart package:geolocator/models/geolocation_enums.dart
    dart --version: 2.8.0-dev.0.0.flutter-75fc15c7e1 (Tue Dec 24 01:29:30 2019 +0000) on "macos_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:164:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:295:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:46:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Error compiling dartdevc module:archive|lib/src/archive.ddc.js

Failed to initialize incremental compiler, throwing away old state.

This is likely a result of https://github.com/dart-lang/sdk/issues/38102, if
you are consistently seeing this problem please see that issue.

The specific exception that was encountered was:

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:164:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:295:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:46:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --kernel --dart-sdk-summary=/Users/michal/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o packages/archive/src/archive.ddc.js --source-map
    --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii
    --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto
    --packages=file:///var/folders/v2/pnzcxw9x1kzgmd01x6n_54cc0000gn/T/kernel_builder_HsmrNZ/.packages --module-name=packages/archive/src/archive
    --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map
    --libraries-file=file:///Users/michal/Development/flutter/bin/cache/flutter_web_sdk/libraries.json
    --used-inputs-file=/var/folders/v2/pnzcxw9x1kzgmd01x6n_54cc0000gn/T/ddk_builder_m6xFXZ/used_inputs.txt package:archive/src/zlib_encoder.dart
    package:archive/src/bzip2/bzip2.dart package:archive/src/zlib/_zlib_decoder_js.dart package:archive/src/bzip2_encoder.dart
    package:archive/src/util/mem_ptr.dart package:archive/src/zlib/huffman_table.dart package:archive/src/tar/tar_file.dart
    package:archive/src/bzip2/bz2_bit_writer.dart package:archive/src/util/output_stream.dart package:archive/src/util/input_stream.dart
    package:archive/src/zip_decoder.dart package:archive/src/zlib/zlib_decoder_stub.dart package:archive/src/bzip2/bz2_bit_reader.dart
    package:archive/src/bzip2_decoder.dart package:archive/src/zlib_decoder.dart package:archive/src/util/archive_exception.dart
    package:archive/src/gzip_decoder.dart package:archive/src/util/adler32.dart package:archive/src/tar_encoder.dart package:archive/src/archive_file.dart
    package:archive/src/zip/zip_file.dart package:archive/src/util/crc32.dart package:archive/src/zlib/zlib_decoder_base.dart
    package:archive/src/tar_decoder.dart package:archive/src/zip_encoder.dart package:archive/src/gzip_encoder.dart
    package:archive/src/util/byte_order.dart package:archive/src/zip/zip_file_header.dart package:archive/src/zlib/inflate.dart
    package:archive/src/zlib/deflate.dart package:archive/src/zip/zip_directory.dart package:archive/src/archive.dart
    dart --version: 2.8.0-dev.0.0.flutter-75fc15c7e1 (Tue Dec 24 01:29:30 2019 +0000) on "macos_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:164:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:295:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:46:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed

BuildStepCompletedException: Attempt to use a BuildStep after is has completed
Error compiling dartdevc module:pest_scope|lib/classes/pest_scope_config.ddc.js

Failed to initialize incremental compiler, throwing away old state.

This is likely a result of https://github.com/dart-lang/sdk/issues/38102, if
you are consistently seeing this problem please see that issue.

The specific exception that was encountered was:

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:164:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:295:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:46:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --kernel --dart-sdk-summary=/Users/michal/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
    --modules=amd --no-summarize -o packages/pest_scope/classes/pest_scope_config.ddc.js --source-map
    --summary=packages/meta/meta.ddc.dill=packages/meta/meta --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers
    --summary=packages/flutter/src/foundation/_bitfield_web.ddc.dill=packages/flutter/src/foundation/_bitfield_web
    --summary=packages/flutter/foundation.ddc.dill=packages/flutter/foundation --summary=packages/vector_math/hash.ddc.dill=packages/vector_math/hash
    --summary=packages/vector_math/vector_math_64.ddc.dill=packages/vector_math/vector_math_64
    --summary=packages/flutter/src/physics/clamped_simulation.ddc.dill=packages/flutter/src/physics/clamped_simulation
    --summary=packages/flutter/physics.ddc.dill=packages/flutter/physics --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils
    --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms
    --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip
    --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators
    --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue
    --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map
    --summary=packages/collection/collection.ddc.dill=packages/collection/collection
    --summary=packages/flutter/src/gestures/arena.ddc.dill=packages/flutter/src/gestures/arena
    --summary=packages/flutter/gestures.ddc.dill=packages/flutter/gestures
    --summary=packages/flutter/src/painting/_network_image_web.ddc.dill=packages/flutter/src/painting/_network_image_web
    --summary=packages/flutter/painting.ddc.dill=packages/flutter/painting
    --summary=packages/flutter/src/semantics/binding.ddc.dill=packages/flutter/src/semantics/binding
    --summary=packages/flutter/semantics.ddc.dill=packages/flutter/semantics
    --summary=packages/flutter/src/animation/animation.ddc.dill=packages/flutter/src/animation/animation
    --summary=packages/flutter/animation.ddc.dill=packages/flutter/animation
    --summary=packages/flutter/src/rendering/animated_size.ddc.dill=packages/flutter/src/rendering/animated_size
    --summary=packages/flutter/rendering.ddc.dill=packages/flutter/rendering
    --summary=packages/flutter/src/widgets/actions.ddc.dill=packages/flutter/src/widgets/actions
    --summary=packages/flutter/widgets.ddc.dill=packages/flutter/widgets
    --summary=packages/flutter/src/cupertino/action_sheet.ddc.dill=packages/flutter/src/cupertino/action_sheet
    --summary=packages/flutter/cupertino.ddc.dill=packages/flutter/cupertino --summary=packages/flutter/material.ddc.dill=packages/flutter/material
    --summary=packages/shared_preferences/shared_preferences.ddc.dill=packages/shared_preferences/shared_preferences
    --packages=file:///var/folders/v2/pnzcxw9x1kzgmd01x6n_54cc0000gn/T/kernel_builder_5Qk9lr/.packages
    --module-name=packages/pest_scope/classes/pest_scope_config --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation
    --inline-source-map --libraries-file=file:///Users/michal/Development/flutter/bin/cache/flutter_web_sdk/libraries.json
    --used-inputs-file=/var/folders/v2/pnzcxw9x1kzgmd01x6n_54cc0000gn/T/ddk_builder_UdYquN/used_inputs.txt
    package:pest_scope/classes/pest_scope_config.dart
    dart --version: 2.8.0-dev.0.0.flutter-75fc15c7e1 (Tue Dec 24 01:29:30 2019 +0000) on "macos_x64"

Bad state: Empty input given.
#0      BinaryBuilder._checkEmptyInput (package:kernel/binary/ast_from_binary.dart:434:29)
#1      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:451:7)
#2      Timeline.timeSync (dart:developer/timeline.dart:164:22)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:449:21)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:414:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/modular_incremental_compilation.dart:206:33)
<asynchronous suspension>
#6      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:163:10)
#7      _compile (package:dev_compiler/src/kernel/command.dart:295:27)
#8      compile (package:dev_compiler/src/kernel/command.dart:46:18)
#9      compile (package:dev_compiler/src/compiler/shared_command.dart:410:10)
#10     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
#16     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#22     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by devoncarew** [comment] 2019-12-30 22:53
Thanks for the report; tentatively closing as a dupe of https://github.com/dart-lang/sdk/issues/38102.

**Closed by devoncarew** 2019-12-30 22:53 UTC
Labels: area-web, web-dev-compiler
