### ISSUE TITLE
Assert in initializer shouldn't be allowed to access parent fields

### ISSUE THREAD

**Issue by a14n** [dart-lang/sdk#31223] opened 2017-10-25 20:05 UTC
With the following code and with SDK _1.25.0-dev.11.0_ : 
- there's no analyzer error
- the VM executes without error

```dart
class A {
  int a;
}

class B extends A {
  B() : assert(a == null);
}

main(){
  print(new B());
}
```

**Comment by rmacnak-google** [comment] 2017-10-25 22:28
@crelier recently fixed a related issue in the VM.

**Comment by crelier** [comment] 2017-10-25 23:29
This is a duplicate of #29784, which was fixed about 2 weeks ago by https://github.com/dart-lang/sdk/commit/98a253186c651e945f56f52b8e6b29f928b5e01c

I do not know how old is SDK 1.25.0-dev.11.0 and if contains the fix.
Also, make sure you pass --enable-asserts (or --checked) to the VM, since asserts are ignored by default.

I leave the bug open, since the issue was reported for the analyzer as well, but removing area-vm.

**Comment by a14n** [comment] 2017-10-26 06:02
Shame on me to not have found my previous issue :)

Indeed it's fixed in VM on the last dev build but not in the analyzer (cc @bwilkerson).

```dart
dart/2.0.0-dev.4.0$ dart-sdk/bin/dart --checked test.dart 
Unhandled exception:
'file:///home/a14n/test.dart': error: line 6 pos 16: illegal implicit access to receiver 'this'
  B() : assert(a == null);
               ^

#0      main (file:///home/aar-dw/softwares/dart/2.0.0-dev.4.0/test.dart:10:13)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

dart/2.0.0-dev.4.0$ dart-sdk/bin/dartanalyzer test.dart 
Analyzing test.dart...
No issues found!

```

**Comment by stereotype441** [comment] 2019-05-04 14:22
Duplicate of #36779

**Closed by stereotype441** 2019-05-04 14:22 UTC
Labels: area-analyzer, p2-medium, type-bug
