### ISSUE TITLE
Expecption: type 'MixinElementImpl' is not a subtype of type 'ClassElement' in type cast

### ISSUE THREAD

**Issue by nitheesh-aot** [dart-lang/sdk#51337] opened 2023-02-09 03:05 UTC
Please include the SDK version (2.19.2) in your bug report.

To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

type 'MixinElementImpl' is not a subtype of type 'ClassElement' in type cast at offset 220 in /Users/nitheeshtganesh/Documents/WORK/TAFT/TAFT_POS/lib/utils/routers/taft_custom_route.dart (@override Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {return SlideTransition(position: Tween<Offset>(begin: const Offset(1.0, 0.0), end: Offset.zero).animate(animation), child: child);})

#0      EdgeBuilder._handleExecutableOverriddenDeclaration (package:nnbd_migration/src/edge_builder.dart:2774:62)
#1      EdgeBuilder._handleExecutableDeclaration (package:nnbd_migration/src/edge_builder.dart:2694:13)
#2      EdgeBuilder.visitMethodDeclaration (package:nnbd_migration/src/edge_builder.dart:1393:5)
#3      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8533:50)
#4      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2375:24)
#5      EdgeBuilder._dispatchList (package:nnbd_migration/src/edge_builder.dart:2393:7)
#6      EdgeBuilder.visitClassOrMixinOrExtensionDeclaration (package:nnbd_migration/src/edge_builder.dart:717:7)
#7      EdgeBuilder.visitClassDeclaration (package:nnbd_migration/src/edge_builder.dart:676:5)
#8      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2000:50)
#9      EdgeBuilder._dispatch (package:nnbd_migration/src/edge_builder.dart:2375:24)
#10     EdgeBuilder.visitNode (package:nnbd_migration/src/edge_builder.dart:1567:9)
#11     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:216:52)
#12     CompletenessTracker.visitCompilationUnit.<anonymous closure> (package:nnbd_migration/src/utilities/completeness_tracker.dart:52:24)
#13     PermissiveModeVisitor.reportExceptionsIfPermissive (package:nnbd_migration/src/utilities/permissive_mode.dart:26:24)
#14     CompletenessTracker.visitCompilationUnit (package:nnbd_migration/src/utilities/completeness_tracker.dart:43:5)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2501:50)
#16     NullabilityMigrationImpl.processInput (package:nnbd_migration/src/nullability_migration_impl.dart:224:12)
#17     NonNullableFix.processUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:162:16)
#18     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1088:19)
#19     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1020:26)
<asynchronous suspension>
#20     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1086:5)
<asynchronous suspension>
#21     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:695:24)
<asynchronous suspension>
#22     MigrateCommand.run (package:dartdev/src/commands/migrate.dart:37:7)
<asynchronous suspension>
#23     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#24     DartdevRunner.runCommand (package:dartdev/dartdev.dart:241:18)
<asynchronous suspension>
#25     runDartdev (package:dartdev/dartdev.dart:65:18)
<asynchronous suspension>
#26     main (file:///opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>

**Comment by asashour** [comment] 2023-02-10 10:07
A duplicate of #51239

**Comment by stereotype441** [comment] 2023-11-21 21:54
As of 1c7fe7196dd7a542f7f91cd6ea2ac81e1a13146c, the null safety migration tool has been removed from active development and retired. No further work on the tool is planned.

If you still need help, or you believe this issue has been closed in error, please feel free to reopen.

**Closed by stereotype441** 2023-11-21 21:54 UTC
Labels: area-migration
