### ISSUE TITLE
SdkExtUriResolver.restoreAbsolute() has incorrect semantics.

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#24090] opened 2015-08-14 19:53 UTC
The intended behavior of UriResolver.restoreAbsolute() is to be the inverse of UriResolver.resolveAbsolute(), with the caveat that it should behave this way without examining any aspects of the incoming Source object other than Source.fullName.

The reason this is necessary is because the clients of UriResolver.restoreAbsolute() do not necessarily pass in a Source object that originally came from UriResolver.resolveAbsolute().  They may pass in a Source object that was created afresh based on a path in the filesystem, in which case the only property of the Source which is guaranteed to have a meaningful value is Source.fullName.  For example, this happens when the analysis server is using UriResolver.restoreAbsolute() to figure out the appropriate URI to use for an import statement it is generating.

SdkExtUriResolver.restoreAbsolute() makes use of Source.uri, so as a result it does the wrong thing if it is passed a Source whose only meaningful property is Source.fullName.  The consequence of this is that the analysis server will generate incorrect import statements when referring to SDK extensions.  (E.g. if there is a package which declares 'dart:foo' as an SDK extension, and the user tries to use an import fixup to add an appropriate import to their file, rather than getting the correct `import 'dart:foo';` statement, they will get some nonsense like `import '../../../../.pub-cache/....dart';`).

I am currently putting together a CL which fixes the semantics of all of the other implementations of UriResolver.restoreAbsolute().  However fixing SdkExtUriResolver looks like it's going to be more involved so I'm filing this issue as a reminder.

**Comment by stereotype441** [comment] 2015-08-14 19:54
Cc @johnmccutchan in case you have time to look into this before I do.

**Comment by johnmccutchan** [comment] 2015-08-14 21:55
@stereotype441 Could you give me some *correct* inputs (fullName) and outputs to restoreAbsolute?

**Comment by stereotype441** [comment] 2015-08-14 22:02
Sure.  Assuming that _urlMappings is `{ 'dart:foo': 'file:///bar/baz.dart' }`, then I believe restoreAbsolute() should map:

`/bar/baz.dart` -> `dart:foo`
`/bar/x.dart` -> `dart:foo/x.dart`
`/bar/x/y.dart` -> `dart:foo/x/y.dart`
`/unrelated/path.dart` -> null

(assuming the OS is Linux or Mac.  On Windows the paths on the LHS would of course contain drive letters and backslashes.)

**Comment by johnmccutchan** [comment] 2015-08-14 22:17
Part of a solution: https://codereview.chromium.org/1294473009

**Comment by johnmccutchan** [comment] 2015-08-14 22:18
I could fix parts as well if I could ask the analyzer for a list of parts in the dart:foo library. The analyzer probably can do that, but I need a point in the right direction.

**Comment by bwilkerson** [comment] 2015-08-17 15:29
> I could fix parts as well if I could ask the analyzer for a list of parts in the dart:foo library.

The method should work on all file paths without reference to whether they are referencing a library or part. If you are given a file path, P, that is contained in the path that a dart: URI maps to, then you should be able to replace the common prefix to produce a URI that the resolver would correctly resolve to P.

**Comment by stereotype441** [comment] 2015-08-17 16:16
> The method should work on all file paths without reference to whether they are referencing a library or part. If you are given a file path, P, that is contained in the path that a dart: URI maps to, then you should be able to replace the common prefix to produce a URI that the resolver would correctly resolve to P.

Agreed.  Reading between the lines, I'm guessing that the reason the existing code for SdkExtUriResolver uses the terminology "part" for referring to resolutions like `dart:foo/x.dart` is because the intended *conventional* usage is for `dart:foo` to refer to a library which may include parts, and `dart:foo/x.dart` may be one of those parts.  (Once again I'm presuming _urlMappings of `{ 'dart:foo': 'file:///bar/baz.dart' }`).  Is that correct?

If so, I think we should be careful to distinguish between conventional usage and what is allowed, and where possible, the analyzer should analyze the source files in terms of what is allowed.

From the point of view of what is allowed, with the aforementioned _urlMappings, resolveAbsolute() maps `dart:foo/x.dart` to `/bar/x.dart`, regardless of whether the URI refers to a part file or an ordinary library.  So restoreAbsolute() should map `/bar/x.dart` back to `dart:foo/x.dart` in all cases, regardless of whether we are referring to a part file or not.

Note, however, there is one circumstance in which this might not be feasible, and that is if we expect people to use _urlMappings that make the reverse mapping ambiguous.  If, for example, we expect users to set up a _urlMappings of `{ 'dart:foo': 'file:///bar/baz.dart', 'dart:foo2': 'file:///bar/baz2.dart' }, then it is not clear whether restoreAbsolute() should reverse map `/bar/x.dart` back to `dart:foo/x.dart` or `dart:foo2/x.dart`.  I'm hoping that this simply isn't a use case that we're concerned about; if it is, we should probably talk in more detail and come up with a better solution.

**Comment by johnmccutchan** [comment] 2015-08-17 17:05
The important case (script entry) is fixed.

**Comment by johnmccutchan** [comment] 2015-08-17 17:10
@stereotype441 

Yes, `_urlMappings` is a mapping from dart:foo to script entry .dart file. For example, `{ 'dart:foo': 'file:///bar/baz.dart' }`, `/bar/baz.dart` is a library which may contain part statements.

`resolveAbsolute()` maps `dart:foo/x.dart` to something relative to the script entry `/bar/baz.dart`. In that case it would resolve to `/bar/x.dart`. However, it is possible that a part statement contains `..` which would end up in `/x.dart`.

**Comment by stereotype441** [comment] 2015-08-17 17:40
@johnmccutchan Has that functionality been tested?  Because I'm pretty sure it doesn't work that way.  My understanding is that the way relative URI references work in the VM is that they act on the URI that was used to reach the file, not the file path that the URI resolved to.  (This is a security feature; it prevents someone from being able to do `import '../../../...';` in their package and access files outside the package).  So for instance if we have:

test.dart:

    import 'dart:foo';

/bar/baz.dart:

    part '../x.dart';

Then the VM will analyze the file `/bar/baz.dart` in the context of the URI `dart:foo`, so it will resolve `part '../x.dart';` to `dart:x.dart`, and then it will try to convert that to a file path using the URL mappings.  So there is no way to escape from the `/bar` directory and get to `/x.dart` using `..` alone.

**Comment by johnmccutchan** [comment] 2015-08-17 19:20
@stereotype441 The VM never loads these scripts except at snapshot generation time via --url_mapping command line arguments.

**Comment by mit-mit** [comment] 2015-08-19 17:45
Punting this to 1.13 per release meeting discussion, This is not a regression, so does not warrant the risk this late for 1.12.

**Comment by bwilkerson** [comment] 2016-01-19 20:39
@pq because you're working in a related area.

**Comment by srawlins** [comment] 2023-04-13 14:17
I don't think we've seen this issue in a long while, closing.

**Closed by srawlins** 2023-04-13 14:17 UTC
Labels: area-analyzer, P2, type-bug
