### ISSUE TITLE
dart analyzer error

### ISSUE THREAD

**Issue by godlessturtle** [dart-lang/sdk#38409] opened 2019-09-16 10:53 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-192.5728.98`
- `2.6.0-edge.d0052c1b31a3a2bb31514c9c4a6e1900c56d069f`
- `IC-192.5728.98, JRE 11.0.3+12-b304.10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 2560x1440  Retina`

## Exception
```
Dart analysis server, SDK version 2.6.0-edge.d0052c1b31a3a2bb31514c9c4a6e1900c56d069f, server version 1.27.3, error: Analysis failed: /Users/ikra/Desktop/dijital-acentem-latest/test/widget_test.dart context: exception_20190916_135256_587
Bad state: The type parameter T (in dart:async;dart:async/stream_controller.dart;StreamController;T) is out of scope.
#0      _createLinkedType (package:analyzer/src/summary/link.dart:217:7)
#1      _storeTypeArguments (package:analyzer/src/summary/link.dart:408:31)
#2      _createLinkedType (package:analyzer/src/summary/link.dart:199:5)
#3      CompilationUnitElementInBuildUnit._storeLinkedType (package:analyzer/src/summary/link.dart:1687:31)
#4      FieldElementForLink_ClassField.link (package:analyzer/src/summary/link.dart:2761:23)
#5      ClassElementForLink_Class.link (package:analyzer/src/summary/link.dart:909:20)
#6      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1649:20)
#7      LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3986:12)
#8      LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3686:15)
#9      LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3626:7)
#10     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2231:13)
#11     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2197:24)
#12     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2197:24)
#13     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2250:18)
#14     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3659:42)
#15     Linker.link (package:analyzer/src/summary/link.dart:4191:35)
#16     _relink (package:analyzer/src/summary/link.dart:313:74)
#17     link (package:analyzer/src/summary/link.dart:127:3)
#18     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:220:25)
#19     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#20     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:219:12)
#21     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
#22     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1439:29)
#23     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1246:30)
#24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#25     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#26     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#27     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1931:24)
<asynchronous suspension>
#28     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1865:5)
#29     new AnalysisServer (package:analysis_server/src/analysis_server.dart:222:29)
#30     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89:26)
#31     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:41:18)
#32     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:576:21)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:693:12)
#38     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:574:7)
#39     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:475:9)
#40     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#41     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:470:43)
#42     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:46)
#43     new Future.sync (dart:async/future.dart:224:31)
#44     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:124:19)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:123:12)
#50     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:142:56)
#51     Driver.start (package:analysis_server/src/server/driver.dart:470:21)
#52     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#53     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#54     main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/serve...
```

For additional log information, please append the contents of
file:///private/var/folders/kg/0pbfvm290d30vtsm5p3k8s7h0000gn/T/report.txt.

**Comment by godlessturtle** [comment] 2019-09-16 11:02
i downgraded my flutter version to 1.9.1 and now its working well
to downgrade
`flutter version -f v1.9.1+hotfix.2`

**Comment by keertip** [comment] 2019-09-16 16:21
Thanks for the report.

**Comment by keertip** [comment] 2019-09-16 16:21
Duplicate of #36506

**Closed by keertip** 2019-09-16 16:21 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
