### ISSUE TITLE
NPE in FunctionTypeImpl.forEachParameterType

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#26016] opened 2016-03-16 18:47 UTC
```
1.15.0-dev.5.0
1457726756770.9368.json
Caused by The null object does not have a method 'pruned'.

NoSuchMethodError:: method not found:: 'pruned'
Receiver:: null
Arguments:: [null]
#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::42)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::45)
#2      FunctionTypeImpl._forEachParameterType (package::analyzer/src/dart/element/type.dart::811)
#3      FunctionTypeImpl.normalParameterTypes (package::analyzer/src/dart/element/type.dart::410)
#4      ResolverVisitor.visitArgumentList (package::analyzer/src/generated/resolver.dart::7672)
#5      ArgumentListImpl.accept (package::analyzer/src/dart/ast/ast.dart::412)
#6      ScopedVisitor.safelyVisit (package::analyzer/src/generated/resolver.dart::9686)
#7      ResolverVisitor.visitSuperConstructorInvocation (package::analyzer/src/generated/resolver.dart::8627)
#8      SuperConstructorInvocationImpl.accept (package::analyzer/src/dart/ast/ast.dart::9460)
#9      NodeListImpl.accept (package::analyzer/src/dart/ast/ast.dart::7582)
#10     ConstructorDeclarationImpl.visitChildren (package::analyzer/src/dart/ast/ast.dart::2864)
#11     ResolverVisitor.visitNode (package::analyzer/src/generated/resolver.dart::8548)
#12     PartialResolverVisitor.visitNode (package::analyzer/src/generated/resolver.dart::6942)
#13     UnifyingAstVisitor.visitConstructorDeclaration (package::analyzer/dart/ast/visitor.dart::2406)
#14     ScopedVisitor.visitConstructorDeclarationInScope (package::analyzer/src/generated/resolver.dart::9823)
#15     ResolverVisitor.visitConstructorDeclarationInScope (package::analyzer/src/generated/resolver.dart::8027)
#16     ScopedVisitor.visitConstructorDeclaration (package::analyzer/src/generated/resolver.dart::9815)
#17     ResolverVisitor.visitConstructorDeclaration (package::analyzer/src/generated/resolver.dart::8014)
#18     ConstructorDeclarationImpl.accept (package::analyzer/src/dart/ast/ast.dart::2856)
#19     NodeListImpl.accept (package::analyzer/src/dart/ast/ast.dart::7582)
#20     ScopedVisitor.visitClassMembersInScope (package::analyzer/src/generated/resolver.dart::9778)
#21     ScopedVisitor.visitClassDeclaration (package::analyzer/src/generated/resolver.dart::9755)
#22     ResolverVisitor.visitClassDeclaration (package::analyzer/src/generated/resolver.dart::7857)
#23     ClassDeclarationImpl.accept (package::analyzer/src/dart/ast/ast.dart::1833)
#24     ResolverVisitor.visitCompilationUnit (package::analyzer/src/generated/resolver.dart::7943)
#25     CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::2414)
#26     PartiallyResolveUnitReferencesTask.internalPerform (package::analyzer/src/task/dart.dart::3608)
#27     AnalysisTask._safelyPerform (package::analyzer/task/model.dart::329)
#28     AnalysisTask.perform (package::analyzer/task/model.dart::229)
#29     AnalysisDriver.performWorkItem (package::analyzer/src/task/driver.dart::274)
#30     AnalysisDriver.performAnalysisTask (package::analyzer/src/task/driver.dart::249)
#31     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1132)
#32     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::212)
#33     AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1130)
#34     PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::371)
#35     AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::864)
#36     Future.Future.<anonymous closure> (dart::async/future.dart::118)
#37     _rootRun (dart::async/zone.dart::891)
#38     _CustomZone.run (dart::async/zone.dart::790)
#39     _CustomZone.runGuarded (dart::async/zone.dart::696)
#40     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#41     _rootRun (dart::async/zone.dart::895)
#42     _CustomZone.run (dart::async/zone.dart::790)
#43     _CustomZone.runGuarded (dart::async/zone.dart::696)
#44     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#45     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#46     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#47     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#48     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart
Original message:
{"event"::"server.error","params"::{"isFatal"::false,"message"::"Task failed:: PartiallyResolveUnitReferencesTask for source ______","stackTrace"::"Unexpected exception while performing PartiallyResolveUnitReferencesTask for source _______
#0      AnalysisTask._safelyPerform (package::analyzer/task/model.dart::339)
#1      AnalysisTask.perform (package::analyzer/task/model.dart::229)
#2      AnalysisDriver.performWorkItem (package::analyzer/src/task/driver.dart::274)
#3      AnalysisDriver.performAnalysisTask (package::analyzer/src/task/driver.dart::249)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1132)
#5      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::212)
#6      AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1130)
#7      PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::371)
#8      AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::864)
#9      Future.Future.<anonymous closure> (dart::async/future.dart::118)
#10     _rootRun (dart::async/zone.dart::891)
#11     _CustomZone.run (dart::async/zone.dart::790)
#12     _CustomZone.runGuarded (dart::async/zone.dart::696)
#13     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#14     _rootRun (dart::async/zone.dart::895)
#15     _CustomZone.run (dart::async/zone.dart::790)
#16     _CustomZone.runGuarded (dart::async/zone.dart::696)
#17     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#18     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#19     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#20     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#21     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)

Caused by The null object does not have a method 'pruned'.

NoSuchMethodError:: method not found:: 'pruned'
Receiver:: null
Arguments:: [null]
#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::42)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::45)
#2      FunctionTypeImpl._forEachParameterType (package::analyzer/src/dart/element/type.dart::811)
#3      FunctionTypeImpl.normalParameterTypes (package::analyzer/src/dart/element/type.dart::410)
#4      ResolverVisitor.visitArgumentList (package::analyzer/src/generated/resolver.dart::7672)
#5      ArgumentListImpl.accept (package::analyzer/src/dart/ast/ast.dart::412)
#6      ScopedVisitor.safelyVisit (package::analyzer/src/generated/resolver.dart::9686)
#7      ResolverVisitor.visitSuperConstructorInvocation (package::analyzer/src/generated/resolver.dart::8627)
#8      SuperConstructorInvocationImpl.accept (package::analyzer/src/dart/ast/ast.dart::9460)
#9      NodeListImpl.accept (package::analyzer/src/dart/ast/ast.dart::7582)
#10     ConstructorDeclarationImpl.visitChildren (package::analyzer/src/dart/ast/ast.dart::2864)
#11     ResolverVisitor.visitNode (package::analyzer/src/generated/resolver.dart::8548)
#12     PartialResolverVisitor.visitNode (package::analyzer/src/generated/resolver.dart::6942)
#13     UnifyingAstVisitor.visitConstructorDeclaration (package::analyzer/dart/ast/visitor.dart::2406)
#14     ScopedVisitor.visitConstructorDeclarationInScope (package::analyzer/src/generated/resolver.dart::9823)
#15     ResolverVisitor.visitConstructorDeclarationInScope (package::analyzer/src/generated/resolver.dart::8027)
#16     ScopedVisitor.visitConstructorDeclaration (package::analyzer/src/generated/resolver.dart::9815)
#17     ResolverVisitor.visitConstructorDeclaration (package::analyzer/src/generated/resolver.dart::8014)
#18     ConstructorDeclarationImpl.accept (package::analyzer/src/dart/ast/ast.dart::2856)
#19     NodeListImpl.accept (package::analyzer/src/dart/ast/ast.dart::7582)
#20     ScopedVisitor.visitClassMembersInScope (package::analyzer/src/generated/resolver.dart::9778)
#21     ScopedVisitor.visitClassDeclaration (package::analyzer/src/generated/resolver.dart::9755)
#22     ResolverVisitor.visitClassDeclaration (package::analyzer/src/generated/resolver.dart::7857)
#23     ClassDeclarationImpl.accept (package::analyzer/src/dart/ast/ast.dart::1833)
#24     ResolverVisitor.visitCompilationUnit (package::analyzer/src/generated/resolver.dart::7943)
#25     CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::2414)
#26     PartiallyResolveUnitReferencesTask.internalPerform (package::analyzer/src/task/dart.dart::3608)
#27     AnalysisTask._safelyPerform (package::analyzer/task/model.dart::329)
#28     AnalysisTask.perform (package::analyzer/task/model.dart::229)
#29     AnalysisDriver.performWorkItem (package::analyzer/src/task/driver.dart::274)
#30     AnalysisDriver.performAnalysisTask (package::analyzer/src/task/driver.dart::249)
#31     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1132)
#32     _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::212)
#33     AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1130)
#34     PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::371)
#35     AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::864)
#36     Future.Future.<anonymous closure> (dart::async/future.dart::118)
#37     _rootRun (dart::async/zone.dart::891)
#38     _CustomZone.run (dart::async/zone.dart::790)
#39     _CustomZone.runGuarded (dart::async/zone.dart::696)
#40     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#41     _rootRun (dart::async/zone.dart::895)
#42     _CustomZone.run (dart::async/zone.dart::790)
#43     _CustomZone.runGuarded (dart::async/zone.dart::696)
#44     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::721)
#45     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#46     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#47     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#48     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)
```

**Comment by bwilkerson** [comment] 2016-03-16 20:29
Duplicate of #25692

**Closed by bwilkerson** 2016-03-16 20:29 UTC
Labels: analyzer-stability, area-analyzer, P1 high, Type: bug
