### ISSUE TITLE
dart2js sometimes outputs redundant code for fields w/ duplicate JS function parameters

### ISSUE THREAD

**Issue by greglittlefield-wf** [dart-lang/sdk#28771] opened 2017-02-15 01:16 UTC
This was found while verifying the fix for https://github.com/dart-lang/sdk/issues/28727. Seems to be unrelated, though.

The generated code does not seem to have any issues or potential issues, and is just redundant.

The following code excerpts were outputted by `pub build` in a `.dart.js_xxx.part.js` file, with `csp: true` and `minify: false`, with a Dart SDK of 1.22.0. I've annotated the output with line breaks and comments to show the issue:
```js
    function AttachmentsStore(
        moduleActions, attachmentsActions, attachmentsEvents, attachmentsService, extensionContext, dispatchKey, commonId, zipSelection, label, _attachments_store$_attachments, _groups, _enableMenuUpload, _primarySelection, _attachments_store$_filters, _filtersByName, currentlySelected, currentlyDisplayedSingle, _showingHeaderlessGroup, enableZipDownload,
        Disposable__didDispose, // * * * ORIGINAL * * * *
        Disposable__isDisposing, // * * * ORIGINAL * * * *
        Disposable__internalDisposables, // * * * ORIGINAL * * * *
        _streamController, _store$_stream,
        Disposable__didDispose, // * * * DUPLICATE * * *
        Disposable__isDisposing, // * * * DUPLICATE * * *
        Disposable__internalDisposables // * * * DUPLICATE * * *
    ) {
      this.moduleActions = moduleActions;
      this.attachmentsActions = attachmentsActions;
      this.attachmentsEvents = attachmentsEvents;
      this.attachmentsService = attachmentsService;
      this.extensionContext = extensionContext;
      this.dispatchKey = dispatchKey;
      this.commonId = commonId;
      this.zipSelection = zipSelection;
      this.label = label;
      this._attachments_store$_attachments = _attachments_store$_attachments;
      this._groups = _groups;
      this._enableMenuUpload = _enableMenuUpload;
      this._primarySelection = _primarySelection;
      this._attachments_store$_filters = _attachments_store$_filters;
      this._filtersByName = _filtersByName;
      this.currentlySelected = currentlySelected;
      this.currentlyDisplayedSingle = currentlyDisplayedSingle;
      this._showingHeaderlessGroup = _showingHeaderlessGroup;
      this.enableZipDownload = enableZipDownload;
      this.Disposable__didDispose = Disposable__didDispose; // * * * ORIGINAL * * * *
      this.Disposable__isDisposing = Disposable__isDisposing; // * * * ORIGINAL * * * *
      this.Disposable__internalDisposables = Disposable__internalDisposables; // * * * ORIGINAL * * * *
      this._streamController = _streamController;
      this._store$_stream = _store$_stream;
      this.Disposable__didDispose = Disposable__didDispose; // * * * DUPLICATE * * *
      this.Disposable__isDisposing = Disposable__isDisposing; // * * * DUPLICATE * * *
      this.Disposable__internalDisposables = Disposable__internalDisposables; // * * * DUPLICATE * * *
      this.$deferredAction();
    }
    AttachmentsStore.builtin$cls = "AttachmentsStore";
    if (!("name" in AttachmentsStore))
      AttachmentsStore.name = "AttachmentsStore";
    $desc = $collectedClasses$.AttachmentsStore[1];
    AttachmentsStore.prototype = $desc;
    AttachmentsStore.$__fields__ = ["moduleActions", "attachmentsActions", "attachmentsEvents", "attachmentsService", "extensionContext", "dispatchKey", "commonId", "zipSelection", "label", "_attachments_store$_attachments", "_groups", "_enableMenuUpload", "_primarySelection", "_attachments_store$_filters", "_filtersByName", "currentlySelected", "currentlyDisplayedSingle", "_showingHeaderlessGroup", "enableZipDownload",
        "Disposable__didDispose", // * * * ORIGINAL * * * *
        "Disposable__isDisposing", // * * * ORIGINAL * * * *
        "Disposable__internalDisposables", // * * * ORIGINAL * * * *
        "_streamController", "_store$_stream",
        "Disposable__didDispose", // * * * DUPLICATE * * *
        "Disposable__isDisposing", // * * * DUPLICATE * * *
        "Disposable__internalDisposables" // * * * DUPLICATE * * *
    ];
```

```js
      static: {
        AttachmentsStore$: function(attachments, attachmentsActions, attachmentsEvents, attachmentsService, commonId, dispatchKey, enableMenuUpload, enableZipDownload, extensionContext, groups, initialFilters, label, moduleActions, primarySelection, zipSelection) {
          var t1, t2, t3, t4;
          t1 = P.LinkedHashMap__makeEmpty();
          t2 = P.StreamController_StreamController$broadcast(null, null, false, A.Store);
          t3 = P.Null;
          t3 = new P._AsyncCompleter(new P._Future(0, $.Zone__current, null, [t3]), [t3]);
          t4 = [];
          t4 = new B.AttachmentsStore(moduleActions, attachmentsActions, attachmentsEvents, attachmentsService, extensionContext, dispatchKey, commonId, zipSelection, label, attachments, groups, enableMenuUpload, primarySelection, [], t1, null, null, false, true,
              t3, false, t4, // * * * ORIGINAL * * *
              t2, null,
              t3, false, t4, // * * * DUPLICATES * * *
          );
```

The class in question, `AttachmentsStore` mixes in w_common's `Disposable`:
```dart
class AttachmentsStore extends Store with Disposable {
```
and the duplicated fields are declared [here](https://github.com/Workiva/w_common/blob/1.2.0/lib/disposable.dart#L147-L149).

Other classes that mix in `Disposable` do not exhibit the same issue.

**Comment by rakudrama** [comment] 2017-02-15 03:49
I think you might be mixing in __Disposable__ twice.
There are many problems with mixing in a class twice and we might make it an error.

It is hard to implement, since a Dart field can no longer map to a JavaScript property. One way to do this would be to clone the mixed-in class, but that kind of defeats the code size benefits of using mixins, and is a lot of implementation work. It will be easier to do after we finish the Kernel IR and moving to a common front end, so if we do make it work, it will be a *long* time before it is done.

Why we might make it an error: mixin classes usually communicate with the 'host' via some abstract methods (DisposableManager). When you use a mixin twice, which versions of these 'host' methods should you call? The mixin will will call the overridden version, so that one must be written to do the appropriate thing, e.g. maybe call the super-method explicitly. This also applies to any code in the 'host' code that calls a mixin method - just calling a mixin method without 'super.' will capture the code from the second 'host'.

Even if it worked, multiple uses of the same mixin is pretty mind-bending to think through, so I would recommend avoiding it. We should make it an error for now.

I think in you case, you could probably replace the second mixin application (__with Disposable__) by __implements Disposable__ (to ensure a warning if you ever remove the mixin from the superclass chain). If your application currently works properly, that would be evidence that the second mixin completely shadows the first, and you could remove the second one. You might need to make some explicit super.calls to make sure all the code is used.

I'd like to close this as a duplicate of https://github.com/dart-lang/sdk/issues/26775.

**Comment by robbecker-wf** [comment] 2017-02-15 05:17
@rakudrama You're right! There was one last place where Disposable was in the class hierarchy as well as mixed in. Removing the `with Disposable` fixed the duplicate params in the JS output.

As a side note, it would be very handy to detect and warn if you've double mixed in. Perhaps this could be a lint rule if not an error.

**Comment by kevmoo** [comment] 2017-02-15 15:11
I'm going to close this issue – since it wasn't an issue.

Please open a separate issue about warning/error for duplicate minixs.

**Closed by kevmoo** 2017-02-15 15:11 UTC
