### ISSUE TITLE
gzip decodes only first line of the file

### ISSUE THREAD

**Issue by meowofficial** [dart-lang/sdk#55469] opened 2024-04-14 17:55 UTC
`GZipCodec` can't decode attached file. It decodes only the first line of the file. I could decode it with `gzip` shell comand. I have also tried other libraries from pub.dev but with no luck.

```
void main(List<String> arguments) async {
  final file =  File('test.csv.gz');
  final bytes = file.readAsBytesSync();
  print(bytes.length); // prints 3796
  print(gzip.decode(bytes).length); // prints 65
}
```

[test.csv.gz](https://github.com/dart-lang/sdk/files/14974288/test.csv.gz)

**Comment by devoncarew** [comment] 2024-04-15 04:51
I suspect the archive itself is corrupt or somehow non-standard. On macos, I see:

<img width="490" alt="Screenshot 2024-04-14 at 9 44 08 PM" src="https://github.com/dart-lang/sdk/assets/1269969/23c16e72-7fcc-4f2d-b041-a9767e2a9994">

Closing as I think the issue is with the archive and not the `GZipCodec` class. If on further investigation of the archive you believe its well-formed / something GZipCodec should parse, please re-open.

**Comment by meowofficial** [comment] 2024-04-15 05:31
@devoncarew I updated the file. Now it opens with the standard macos archive utility. Could you check it again?

**Comment by a-siva** [comment] 2024-04-17 20:35
//cc @brianquinlan

**Comment by brianquinlan** [comment] 2024-04-17 21:43
I can repro. Python is able to decompress this file:

```python
>>> s = open('test.csv.gz', 'rb').read()
>>> import gzip
>>> t = gzip.decompress(s)
>>> len(t)
68541
```

The bytes that Dart actually decodes are:
```python
>>> x = [105, 100, 83, 117, 98, 67, 97, 109, 112, 97, 105, 103, 110, 84, 105, 116, 108, 101, 44, 105, 100, 83, 117, 98, 65, 100, 83, 101, 116, 84, 105, 116, 108, 101, 44, 105, 100, 83, 117, 98, 67, 97, 109, 112, 97, 105, 103, 110, 44, 105, 100, 67, 97, 109, 112, 97, 105, 103, 110, 84, 105, 116, 108, 101, 10]
>>> bytes(x)
b'idSubCampaignTitle,idSubAdSetTitle,idSubCampaign,idCampaignTitle\n'
```

Which is the first line of the file. If I understand correctly, the GZIP file format consists of concatenated compressed data sets. So maybe we are only decoding the first data set?

**Comment by brianquinlan** [comment] 2024-04-19 00:16
I get the same output as Dart when use the [zpipe example](https://github.com/madler/zlib/blob/master/examples/zpipe.c) after changing:

```
-    ret = inflateInit(&strm);
+    ret = inflateInit2(&strm, 32 + 15);
```

The [Python implementation](https://github.com/python/cpython/blob/8f25cc992021d6ffc62bb110545b97a92f7cb295/Modules/zlibmodule.c#L488) looks very similar to ours.

**Comment by brianquinlan** [comment] 2024-04-19 18:08
If I extract the file and recompress it with gzip, both Dart and zpipe and decompress the file. How did you generate this archive?

**Comment by meowofficial** [comment] 2024-04-19 18:18
@brianquinlan This archive is from raw data export API response of https://docs.tracker.my.com/api/export-api/raw/about

**Comment by lrhn** [comment] 2024-04-22 00:34
Seems related to https://github.com/dart-lang/sdk/issues/47244

**Comment by brianquinlan** [comment] 2024-04-22 22:13
Yep. OK, I missed that Python deals with gzip data starting in Python code:
https://github.com/python/cpython/blob/fc21c7f7a731d64f7e4f0e82469f78fa9c104bbd/Lib/gzip.py#L622

I also found an example on how to handle concatenated gzip streams in C from Mark Adler himself:
https://stackoverflow.com/questions/17820664/is-this-a-bug-in-this-gzip-inflate-method/17822217#17822217

**Comment by brianquinlan** [comment] 2024-04-22 23:25
I have a straightforward fix for this but it will take a while for me to convince myself that it always works.

**Closed** 2024-05-31 20:35 UTC
Labels: area-vm, library-io, P2, triaged
