### ISSUE TITLE
Analyzer performance benchmark on Flutter has regressed when Dart was rolled to 52afcba357ad398e8c24f3e3363ac6ff5293df63

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#32769] opened 2018-04-04 20:12 UTC
Please see flutter analyzer benchmarks here 

https://flutter-dashboard.appspot.com/benchmarks.html

They have all regressed after the roll of Dart to 52afcba357ad398e8c24f3e3363ac6ff5293df63

The commit which rolled dart was https://github.com/flutter/engine/commit/c903c217a1a8206cdebdab1703b52ec6180edf37

**Comment by aam** [comment] 2018-04-04 21:16
This seems to have been introduced in 6fecb1e263 'fix analysis_server for callable function change in Analyzer' https://dart-review.googlesource.com/48887

**Comment by devoncarew** [comment] 2018-04-04 21:27
Thanks for the investigation here! I do see a drop in golem, on or around https://github.com/dart-lang/sdk/commit/bed5debbeb25b8ae12192d9dda325dc48756e5ba.

**Comment by scheglov** [comment] 2018-04-04 21:40
It looks to me too that a jump in cold analysis time happened at https://github.com/dart-lang/sdk/commit/bed5debbeb25b8ae12192d9dda325dc48756e5ba .
I don't have any numbers yet, will benchmark it locally before and after.

**Comment by scheglov** [comment] 2018-04-04 21:49
No, I don't see any difference in time running analyzer with and without this change.
This must be something else.

**Comment by jmesserly** [comment] 2018-04-04 21:54
> Please see flutter analyzer benchmarks here https://flutter-dashboard.appspot.com/benchmarks.html
> Thanks for the investigation here! I do see a drop in golem, on or around bed5deb.

It looks like a 2-4% drop, is that what you're seeing?

Hmm, some guesses. It could be that making StrongTypeSystemImpl._guard a generic method caused problems. It would be easy to undo that change and see if it helps. Or it could be that subtyping does more work with the new Dart 2 rules for callable classes. That's harder to fix. Or it could be caused by something else in the CL that isn't jumping out at me.

**Comment by scheglov** [comment] 2018-04-05 00:59
OK, I can reproduce the performance drop on bed5debbeb when run `flutter analyze repo`.
With the version immediately before it, the average time is `39.0s`, on it `40.7s`.
I was replacing just two packages: `analyzer` and `front_end`, no Dart VM changes.

**Comment by a-siva** [comment] 2018-04-05 21:11
any updates on when this will be fixed?

**Comment by devoncarew** [comment] 2018-04-05 22:06
> I'm not sure I have the time or expertise for tracking down Analyzer performance issues

Gotcha, but this isn't general analyzer perf issues, but issues from this specific commit. The change shows up on both the flutter and golem analyzer benchmarks, so is definitely worth investigating. I would assume that you'd be most familiar with the work here. If it was mostly @stereotype441's work, I'd be happy to ask him to investigate instead.

**Comment by dgrove** [comment] 2018-04-06 03:50
Moving this to Beta 4.

**Comment by jmesserly** [comment] 2018-04-06 19:55
I think I found the problem. It was from Paul(/Leaf)'s original CL: https://dart-review.googlesource.com/c/sdk/+/43482/4/pkg/analyzer/lib/src/generated/type_system.dart#424

It seems like isAssignableTo is called a bunch, and anything that slows it down (or speeds it up) has a big impact. The fix is to not call `getCallMethodType(fromType)` until we check if the other side expects a function type.

(`getCallMethodType` is slow because it searches the full class hierarchy and does a linear scan through all of the method tables. I wonder if TypeSystem should use a cache or something to make that lookup cheaper. Analyzer CodeChecker has similar issues with its override checking. Member lookups are always linear scans...)

**Comment by jmesserly** [comment] 2018-04-06 22:15
sent out a CL: https://dart-review.googlesource.com/c/sdk/+/49962

I found a bunch of unrelated performance/correctness problems, will try and get some bugs filed. Aside from method lookups being really slow, Analyzer also suffers from duplicate work in various visitors, which causes it to do the same assignability check 3 times (and subtype check 4 times) for one line of code.

**Comment by a-siva** [comment] 2018-04-13 01:03
We still see some regression in the Flutter benchmark after this CL landed. Please see the mega_gallery_watch and mega_gallery_batch benchmarks in https://flutter-dashboard.appspot.com/benchmarks.html

**Comment by dgrove** [comment] 2018-04-13 01:18
Reassigning to Devon to figure out where this regressed. Perhaps we should open a new issue for these other regressions?

**Comment by devoncarew** [comment] 2018-04-13 17:30
I'll create a new issue. @jmesserly's fix did address the bulk of the regression. @scheglov is looking at other performance improvements, and we're in the process of adding a analyze-flutter-repo-at-head benchmark to golem.

**Closed by devoncarew** 2018-04-13 17:30 UTC
Labels: Customer-Flutter, P1 high, area-analyzer
