### ISSUE TITLE
Incremental compiler fails to compile flutter hello_world example app

### ISSUE THREAD

**Issue by aam** [dart-lang/sdk#30491] opened 2017-08-18 16:21 UTC
IKG compiler for flutter hello_world fails to resolve dart:ui class references, produces warnings and errors to in that regard. It's behavior is different from batch compiler `kernelFromProgram`, which compiles flutter examples correctly.

Snippet of the errors:
```
file:///flutter/flutter/packages/flutter/lib/src/painting/box_painter.dart:67:5: Warning: 'Radius' isn't a type.
    Radius right: Radius.zero
    ^
file:///flutter/flutter/packages/flutter/lib/src/painting/box_painter.dart:85:59: Error: Getter not found: 'Radius'.
  static const BorderRadius zero = const BorderRadius.all(Radius.zero);
                                                          ^
file:///flutter/flutter/packages/flutter/lib/src/painting/box_painter.dart:85:59: Error: Compilation aborted due to fatal error.
  static const BorderRadius zero = const BorderRadius.all(Radius.zero);
                                                          ^
[+22086 ms] "flutter run" took 75,045ms.
```

**Comment by aam** [comment] 2017-08-18 16:45
This is needed for https://github.com/dart-lang/sdk/issues/28051

**Comment by sigmundch** [comment] 2017-08-18 23:26
I looked a bit into this with `run.dart` and found a few problems:
* If I run run.dart and give it a path to the sdk root with a Uri that is missing a scheme, we fail to find the sdk libraries. This is because of the extra check we do in source_loader.dart. I believe we don't need to do that anymore and have a fix for this issue.
* Then IKG fails when compiling the library cycle that contains `dart:core` because `target.extraLibraryDependencies` lists `dart:ui`. Fasta loads all those extra dependencies when compiling `dart:core` and IKG is not aware of these implicit dependencies.

I believe the right fix for the latter is to update how we deal with extraLibraryDependencies, I'll follow up on that. Most likely I'll remove `dart:ui` from the extra deps, and add it explicitly in the patch_sdk script.

Finally the issue reported above I believe is due to the re-exports, so they should also be covered once we fix #30448

**Comment by aam** [comment] 2017-08-23 17:51
@a-siva

**Comment by sigmundch** [comment] 2017-08-23 23:26
sent https://codereview.chromium.org/3006483002 to address the issue in source loader, and https://codereview.chromium.org/3007503002/ to address the issue with `dart:ui`.

For the latter, turns out IKG already had some of the logic for the implicit imports, but it was hardcoded to consider the VmTarget only, rather than the target that was being used during compilation.

I started an email discussion to change how we use "extraRequiredLibraries" long term, but those 2 CLs should address your issues here. One issue remains about exports, which is tracked in #30448

**Comment by aam** [comment] 2017-08-23 23:29
Awesome, thanks @sigmundch !

**Comment by sigmundch** [comment] 2017-08-24 23:27
I landed the fix for `dart:ui`, but partially addresses the source loader issue. There is still one more change to make to accept a URI without a scheme in the public API. That however should not block you.

**Comment by aam** [comment] 2017-08-24 23:49
Thanks @sigmundch , but somehow, on eed3b5e0bbe9ebaa54524f0beca1954eaed6c125 I'm still getting many warnings when compiling with IKG:
```
[+4181 ms] compile debug message: Type 'VoidCallback' not found.
[        ] compile debug message: 'PointerDeviceKind' isn't a type.
[        ] compile debug message: 'Offset' isn't a type.
```
Not sure if submitted CLs intended to get rid of those in IKG.

**Comment by sigmundch** [comment] 2017-08-25 00:09
Unfortunately no - I believe all those errors are a consequence of a reexport, so they will only be addressed after a fix for #30448 lands.

The changes above fix the other minor issues we found in the process of reproducing your error:
 * f539785e038351d94973ec5aa8b9b546e63287b9 addresses the problem that `dart:ui` was not found in IKG if it was also listed in the `extraRequiredLibraries` in FlutterTarget when compiling from sources
  * d9ae60e14fdec52bda977ed114f6ad70dc2f0bc4 is a first step to address the errors you saw when passing an sdk-root without a scheme. For now I'm improving the error message, later I plan to make it unnecessary to specify the scheme.

**Comment by sigmundch** [comment] 2017-08-25 14:33
@aam - the final solution is not in, but @peter-ahe-google just landed a workaround for #30448 in https://github.com/dart-lang/sdk/commit/aff5d768d79d8b3059feae250a58769dd473f5d3. Can you give it a try?

**Comment by aam** [comment] 2017-08-25 15:32
Thanks folks. Just sync'ed to aff5d76 and tried flutter gallery build - there are no warning messages, but now there is an error produced:
```
[+3618 ms] compile debug message: 'Animation&AnimationEagerListenerMixin^#U0^' is exported from both 'package:flutter/src/animation/animation_controller.dart' and 'package:flutter/src/animation/animations.dart'.
[        ] compile debug message: 'Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin^#U0^^' is exported from both 'package:flutter/src/animation/animation_controller.dart' and 'package:flutter/src/animation/animations.dart'.
[        ] compile debug message: 'Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin^#U0^^^' is exported from both 'package:flutter/src/animation/animation_controller.dart' and 'package:flutter/src/animation/animations.dart'.
[  +25 ms] stderr:>Unhandled exception:
[        ] stderr:>NoSuchMethodError: The getter 'length' was called on null.
[        ] stderr:>Receiver: null
[        ] stderr:>Tried calling: length
[        ] stderr:>#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
[        ] stderr:>#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
[        ] stderr:>#2      Uri.parse (dart:core/uri.dart:788)
[        ] stderr:>#3      DillLibraryBuilder.finalizeExports (package:front_end/src/fasta/dill/dill_library_builder.dart:150)
[        ] stderr:>#4      DillLoader.finalizeExports.<anonymous closure> (package:front_end/src/fasta/dill/dill_loader.dart:64)
[        ] stderr:>#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
[        ] stderr:>#6      DillLoader.finalizeExports (package:front_end/src/fasta/dill/dill_loader.dart:62)
[        ] stderr:>#7      DillTarget.buildOutlines (package:front_end/src/fasta/dill/dill_target.dart:54)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#8      KernelDriver._compileCycle.<anonymous closure>.appendNewDillLibraries (package:front_end/src/incremental/kernel_driver.dart:233)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#9      KernelDriver._compileCycle.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:269)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#10     PerformanceLog.runAsync (package:front_end/src/base/performace_logger.dart:52)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#11     KernelDriver._compileCycle (package:front_end/src/incremental/kernel_driver.dart:213)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#12     KernelDriver.getKernel.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:166)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#13     PerformanceLog.runAsync (package:front_end/src/base/performace_logger.dart:52)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#14     KernelDriver.getKernel.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:163)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#15     PerformanceLog.runAsync (package:front_end/src/base/performace_logger.dart:52)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#16     KernelDriver.runWithFrontEndContext.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:195)
[        ] stderr:>#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89)
[        ] stderr:>#18     _rootRun (dart:async/zone.dart:1120)
[        ] stderr:>#19     _CustomZone.run (dart:async/zone.dart:1001)
[        ] stderr:>#20     runZoned (dart:async/zone.dart:1467)
[        ] stderr:>#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89)
[        ] stderr:>#22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96)
[        ] stderr:>#23     KernelDriver.runWithFrontEndContext (package:front_end/src/incremental/kernel_driver.dart:194)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#24     KernelDriver.getKernel (package:front_end/src/incremental/kernel_driver.dart:131)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#25     IncrementalKernelGeneratorImpl.computeDelta.<anonymous closure> (package:front_end/src/incremental_kernel_generator_impl.dart:102)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#26     PerformanceLog.runAsync (package:front_end/src/base/performace_logger.dart:52)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#27     IncrementalKernelGeneratorImpl.computeDelta (package:front_end/src/incremental_kernel_generator_impl.dart:100)
[        ] stderr:>#28     _FrontendCompiler.compile (package:frontend_server/server.dart:128)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#29     starter.<anonymous closure> (package:frontend_server/server.dart:217)
[        ] stderr:><asynchronous suspension>
[        ] stderr:>#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
[        ] stderr:>#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] stderr:>#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] stderr:>#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
[        ] stderr:>#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
[        ] stderr:>#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
[        ] stderr:>#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
[        ] stderr:>#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
[        ] stderr:>#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
[        ] stderr:>#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
[        ] stderr:>#40     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
[        ] stderr:>#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] stderr:>#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] stderr:>#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
[        ] stderr:>#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
[        ] stderr:>#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
[        ] stderr:>#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
[        ] stderr:>#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
[        ] stderr:>#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
[        ] stderr:>#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
[        ] stderr:>#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
[        ] stderr:>#51     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
[        ] stderr:>#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] stderr:>#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] stderr:>#54     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
[        ] stderr:>#55     _StreamController._add (dart:async/stream_controller.dart:667)
[        ] stderr:>#56     _StreamController.add (dart:async/stream_controller.dart:613)
[        ] stderr:>#57     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
[        ] stderr:>#58     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
[        ] stderr:>#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
[        ] stderr:>#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
[        ] stderr:>#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
[        ] stderr:>#62     _StreamController._add (dart:async/stream_controller.dart:667)
[        ] stderr:>#63     _StreamController.add (dart:async/stream_controller.dart:613)
[        ] stderr:>#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
[        ] stderr:>#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
[        ] stderr:>#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] stderr:>#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] stderr:>#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
[        ] stderr:>#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by scheglov** [comment] 2017-08-25 15:36
Do you use FileByteStore, or MemoryByteStore?

This commit changes our expectations about libraries, so old entries in persistent ByteStore are not valid. Try to remove the results in the file system cache, or increment `KernelDriver.DATA_VERSION`.

**Comment by aam** [comment] 2017-08-25 16:00
@scheglov , if I understand correctly, I didn't explicitly set which byte store to use(https://github.com/flutter/engine/blob/master/frontend_server/lib/server.dart#L114), so it defaulted to NullByteStore.
I tried using MemoryByteStore (`..byteStore = new MemoryByteStore()`), that didn't change the way it failed.

**Comment by scheglov** [comment] 2017-08-25 16:03
You're correct.
I just wanted to make sure that this is not a peculiarity of `KernelDriver` here.
Then it must be a corner case the new exports handling core.

**Comment by sigmundch** [comment] 2017-08-25 18:54
Hey Alex - this looks like a bug in the implementation with the exports. We actually noticed that the line you are hitting could cause a crash, but I thought it could only arise from erroneous code, we'll investigate and keep you posted.

Thanks for giving it a shot!

**Comment by sigmundch** [comment] 2017-08-25 23:20
I took a brief look, and it seems the way fasta is declaring shared mixins is creating a conflict where there shouldn't be one (basically the "nits" you saw above the error). I filed #30553 to track that issue.

The situation described in that bug comes up in the flutter package, and as a result, you are hitting the bugs in the implementation that follow up from that.

It might be possible that the program will run if we ignore those nits, as long as we fix the bugs in the implementation.

I created https://codereview.chromium.org/3004643002/ to address the bugs, if you have a chance and can patch it in, let me know if that addresses the issues. You'll likely continue to see the nits until #30553

**Comment by peter-ahe-google** [comment] 2017-08-28 12:26
I have a fix for #30553, please see that bug for a link to the code review if you'd like to patch it in.

**Comment by sigmundch** [comment] 2017-08-28 16:06
Thanks Peter!

Alex - Peter also landed fixes for the null error, so the CL I sent out is now unnecessary and you can ignore it.

**Comment by aam** [comment] 2017-08-28 16:32
Thank you folks! Both fixes(including Peter's 30553) seem to work nicely.

Only diagnostics that is reported for flutter gallery app points to identifiers exported from two libraries and overridden methods not having matching signatures(see below). Not sure if it is as expected. (last one about super class mixin method reference is as expected).
```
[+7516 ms] compile debug message: '$tilde' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
[   +9 ms] compile debug message: '$minus' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
[        ] compile debug message: '$sub' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
[+1609 ms] compile debug message: Declared type variables of 'CachingIterable::map' doesn't match those on overridden method 'Iterable::map'.
[        ] compile debug message: Declared type variables of 'CachingIterable::expand' doesn't match those on overridden method 'Iterable::expand'.
[   +2 ms] compile debug message: Declared type variables of 'SynchronousFuture::then' doesn't match those on overridden method 'Future::then'.
[  +35 ms] compile debug message: Declared type variables of '_DelegatingIterableBase::map' doesn't match those on overridden method 'Iterable::map'.
[        ] compile debug message: Declared type variables of '_DelegatingIterableBase::fold' doesn't match those on overridden method 'Iterable::fold'.
[        ] compile debug message: Declared type variables of '_DelegatingIterableBase::expand' doesn't match those on overridden method 'Iterable::expand'.
[   +6 ms] compile debug message: Declared type variables of 'TickerFuture::then' doesn't match those on overridden method 'Future::then'.
[ +145 ms] compile debug message: Declared type variables of '_TypeSafeIterableBase::map' doesn't match those on overridden method 'Iterable::map'.
[        ] compile debug message: Declared type variables of '_TypeSafeIterableBase::fold' doesn't match those on overridden method 'Iterable::fold'.
[        ] compile debug message: Declared type variables of '_TypeSafeIterableBase::expand' doesn't match those on overridden method 'Iterable::expand'.
[   +5 ms] compile debug message: Declared type variables of 'DelegatingFuture::then' doesn't match those on overridden method 'Future::then'.
[        ] compile debug message: Declared type variables of 'DelegatingStreamSubscription::asFuture' doesn't match those on overridden method 'StreamSubscription::asFuture'.
[   +2 ms] compile debug message: Declared type variables of '_TransformedSubscription::asFuture' doesn't match those on overridden method 'StreamSubscription::asFuture'.
[        ] compile debug message: Declared type variables of 'TypeSafeFuture::then' doesn't match those on overridden method 'Future::then'.
[        ] compile debug message: Declared type variables of 'TypeSafeStream::asyncExpand' doesn't match those on overridden method 'Stream::asyncExpand'.
[        ] compile debug message: Declared type variables of 'TypeSafeStream::map' doesn't match those on overridden method 'Stream::map'.
[        ] compile debug message: Declared type variables of 'TypeSafeStream::asyncMap' doesn't match those on overridden method 'Stream::asyncMap'.
[        ] compile debug message: Declared type variables of 'TypeSafeStream::transform' doesn't match those on overridden method 'Stream::transform'.
[        ] compile debug message: Declared type variables of 'TypeSafeStream::fold' doesn't match those on overridden method 'Stream::fold'.
[        ] compile debug message: Declared type variables of 'TypeSafeStream::drain' doesn't match those on overridden method 'Stream::drain'.
[        ] compile debug message: Declared type variables of 'TypeSafeStream::expand' doesn't match those on overridden method 'Stream::expand'.
[   +1 ms] compile debug message: Declared type variables of 'TypeSafeStreamSubscription::asFuture' doesn't match those on overridden method 'StreamSubscription::asFuture'.
[+2497 ms] compile debug message: Superclass has no method named 'hitTest'.
```

**Comment by lrhn** [comment] 2017-08-28 17:24
On Mon, Aug 28, 2017 at 6:33 PM, Alexander Aprelev <notifications@github.com
> wrote:

> Thank you folks! Both fixes(including Peter's 30553) seem to work nicely.
>
> Only diagnostics that is reported for flutter gallery app points to
> identifiers exported from two libraries and overridden methods not having
> matching signatures(see below). Not sure if it is as expected. (last one
> about super class mixin method reference is as expected).
>
> [+7516 ms] compile debug message: '$tilde' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
> [   +9 ms] compile debug message: '$minus' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
> [        ] compile debug message: '$sub' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
>
> This suggests updating charcode to version 1.10, which fixed those
conflicts.


> [+1609 ms] compile debug message: Declared type variables of 'CachingIterable::map' doesn't match those on overridden method 'Iterable::map'.
> [        ] compile debug message: Declared type variables of 'CachingIterable::expand' doesn't match those on overridden method 'Iterable::expand'.
> [   +2 ms] compile debug message: Declared type variables of 'SynchronousFuture::then' doesn't match those on overridden method 'Future::then'.
> [  +35 ms] compile debug message: Declared type variables of '_DelegatingIterableBase::map' doesn't match those on overridden method 'Iterable::map'.
> [        ] compile debug message: Declared type variables of '_DelegatingIterableBase::fold' doesn't match those on overridden method 'Iterable::fold'.
> [        ] compile debug message: Declared type variables of '_DelegatingIterableBase::expand' doesn't match those on overridden method 'Iterable::expand'.
> [   +6 ms] compile debug message: Declared type variables of 'TickerFuture::then' doesn't match those on overridden method 'Future::then'.
> [ +145 ms] compile debug message: Declared type variables of '_TypeSafeIterableBase::map' doesn't match those on overridden method 'Iterable::map'.
> [        ] compile debug message: Declared type variables of '_TypeSafeIterableBase::fold' doesn't match those on overridden method 'Iterable::fold'.
> [        ] compile debug message: Declared type variables of '_TypeSafeIterableBase::expand' doesn't match those on overridden method 'Iterable::expand'.
> [   +5 ms] compile debug message: Declared type variables of 'DelegatingFuture::then' doesn't match those on overridden method 'Future::then'.
> [        ] compile debug message: Declared type variables of 'DelegatingStreamSubscription::asFuture' doesn't match those on overridden method 'StreamSubscription::asFuture'.
> [   +2 ms] compile debug message: Declared type variables of '_TransformedSubscription::asFuture' doesn't match those on overridden method 'StreamSubscription::asFuture'.
> [        ] compile debug message: Declared type variables of 'TypeSafeFuture::then' doesn't match those on overridden method 'Future::then'.
> [        ] compile debug message: Declared type variables of 'TypeSafeStream::asyncExpand' doesn't match those on overridden method 'Stream::asyncExpand'.
> [        ] compile debug message: Declared type variables of 'TypeSafeStream::map' doesn't match those on overridden method 'Stream::map'.
> [        ] compile debug message: Declared type variables of 'TypeSafeStream::asyncMap' doesn't match those on overridden method 'Stream::asyncMap'.
> [        ] compile debug message: Declared type variables of 'TypeSafeStream::transform' doesn't match those on overridden method 'Stream::transform'.
> [        ] compile debug message: Declared type variables of 'TypeSafeStream::fold' doesn't match those on overridden method 'Stream::fold'.
> [        ] compile debug message: Declared type variables of 'TypeSafeStream::drain' doesn't match those on overridden method 'Stream::drain'.
> [        ] compile debug message: Declared type variables of 'TypeSafeStream::expand' doesn't match those on overridden method 'Stream::expand'.
> [   +1 ms] compile debug message: Declared type variables of 'TypeSafeStreamSubscription::asFuture' doesn't match those on overridden method 'StreamSubscription::asFuture'.
>
>
Looks like it's all methods that have become generic, so perhaps some
implementation is not be up-to-date with that.


>
> [+2497 ms] compile debug message: Superclass has no method named 'hitTest'.
>
>
/L
-- 
Lasse R.H. Nielsen - lrn@google.com
'Faith without judgement merely degrades the spirit divine'
Google Denmark ApS - Frederiksborggade 20B, 1 sal - 1360 København K
- Denmark - CVR nr. 28 86 69 84

**Comment by sigmundch** [comment] 2017-08-28 17:42
> Looks like it's all methods that have become generic, so perhaps some
implementation is not be up-to-date with that.

I'm guessing this relates to erasure: the compiler is applying an erasure transformation. We normally do this whenever we build a program, so IKG does it more than when you do batch compilation (so you are more likely to see it). 

This is being tracked at: https://github.com/dart-lang/sdk/issues/30455

**Comment by aam** [comment] 2017-08-28 18:23
> >  [+7516 ms] compile debug message: '$tilde' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
> >  [   +9 ms] compile debug message: '$minus' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
> >  [        ] compile debug message: '$sub' is exported from both 'package:charcode/ascii.dart' and 'package:charcode/html_entity.dart'.
> > 
> 
>  This suggests updating charcode to version 1.10, which fixed those conflicts.

Thank you, @lrhn , for taking a look at the warnings. Are you talking about https://github.com/dart-lang/charcode ? Latest version that seems to be available is 1.1.1.

**Comment by lrhn** [comment] 2017-08-28 19:26
Yes, that is `package:charcode`. It seems that some library exports both `package:charcode/ascii.dart` and `package:charcode/html.dart` without hiding the conflicts. The most reasonable guess is that that library is `package:charcode/charcode.html` prior to version 1.1.0 which added that hide clause (https://github.com/dart-lang/charcode/commit/925b04222df29d96772783e08a91f644ac2245f3)

**Comment by aam** [comment] 2017-08-28 21:06
Something else seems to be going on. The code does use 1.1.1 only, nobody refers to 1.1.0 of `charcode` as far as I can tell.
The problem seems to be that `kernelForProgram` https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/kernel_generator.dart#L40 somehow ignores 'hide' part of export statement https://github.com/dart-lang/charcode/blob/master/lib/charcode.dart#L17.
Commenting out just the 'hide'-part doesn't change the diagnostic, but if I comment whole `export "html_entity.dart"` line out, then warnings about `$minus`, `$tilde`, `$sub` disappear.

**Comment by lrhn** [comment] 2017-08-30 07:52
That was *not* a bug I was expecting, but it does indeed explain the symptoms. I guess hides in exports are rare enough that it hasn't been caught before.

**Comment by peter-ahe-google** [comment] 2017-08-30 14:56
@scheglov I can't reproduce the problem with hides in exports in non-incremental. Could this be an issue with `NamespaceExport.isExposed`?

**Comment by scheglov** [comment] 2017-08-30 17:39
I don't think so, but it occurred to me that we don't need rebuilding export scopes any more, so I [removed it](https://github.com/dart-lang/sdk/commit/288b203b6cf500ee84e6ee5873b8192b4863f272).

**Comment by aam** [comment] 2017-08-30 20:36
Here is repro for the problem with `export`:
```
import 'package:front_end/src/testing/compiler_common.dart';
import 'package:front_end/front_end.dart';

main() async {
  var sources = <String, dynamic>{
    'a.dart': 'import "charcode.dart";',
    'charcode.dart': 'export "ascii.dart"; export "html_entity.dart" hide tilde;',
    'html_entity.dart': 'export "ascii.dart" show quot; const int tilde=1;',
    'ascii.dart': 'const int tilde=2; const int quot=3;',
  };
  await compileUnit(sources.keys.toList(), sources, options: new
      CompilerOptions()..onError = (e) => print('${e.severity}: ${e.message}'));
}
```

```
╰─➤  DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart hide.dart
Severity.nit: 'tilde' is exported from both 'file:///a/b/c/ascii.dart' and 'file:///a/b/c/html_entity.dart'.
```

**Comment by peter-ahe-google** [comment] 2017-08-31 11:19
@scheglov thank you for checking, and removing the redundant export scope building.

@aam thank you for the repro. I have a fix for it.

**Comment by peter-ahe-google** [comment] 2017-08-31 11:57
Fix here in [CL 3004123002](https://codereview.chromium.org/3004123002/).

**Comment by aam** [comment] 2017-08-31 16:06
Thank you @peter-ahe-google !

**Comment by sigmundch** [comment] 2017-11-29 23:02
I believe this issue is now obsolete, but please reopen if I was mistaken.

**Closed by sigmundch** 2017-11-29 23:02 UTC
Labels: area-front-end, Type: bug
