### ISSUE TITLE
ERRRO

### ISSUE THREAD

**Issue by chengxushi** [dart-lang/sdk#40074] opened 2020-01-13 04:39 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.79e6c743371a319cfc58bcec76f4ffb3114ef9a9`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x864, 1536x864`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.79e6c743371a319cfc58bcec76f4ffb3114ef9a9, server version 1.27.2, error: Captured exception
UnimplementedError: Encoding "null"
#0      translateErrorToken (package:front_end/src/scanner/errors.dart:172:7)
#1      Scanner.tokenize (package:analyzer/src/dart/scanner/scanner.dart:171:9)
#2      _File._parse (package:analyzer/src/services/available_declarations.dart:1835:25)
#3      _File.refresh (package:analyzer/src/services/available_declarations.dart:1160:30)
#4      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:660:14)
#5      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:695:16)
#6      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:567:7)
#7      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:283:13)
<asynchronous suspension>
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
<asynchronous suspension>
#9      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#10     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#11     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#12     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#13     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#19     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#20     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#22     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#23     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#31     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#32     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#33     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#34     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#35     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file://C:\Users\huang\AppData\Local\Temp\report1.txt.

**Comment by parlough** [comment] 2020-05-26 07:12
Duplicate of https://github.com/dart-lang/sdk/issues/37641

**Closed** 2020-06-14 22:20 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
