### ISSUE TITLE
DebugSIMARM64 (no bot) failing vm/cc/Int8ListLengthMaxElements and vm/cc/LargeMap

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#24079] opened 2015-08-13 21:29 UTC
Simulator hit unaligned read

**Comment by fsc8000** [comment] 2015-08-18 11:24
@zanderso: Is this a duplicate of #23953 or #22151?

**Comment by zanderso** [comment] 2015-08-18 16:04
This appears to be a different bug. At least with Int8ListLengthMaxElements, an argument descriptor array is missing a heap object tag, and applying a field offset results in an unaligned read. So, nothing to do with typed data. I'll investigate more.

**Closed** 2015-08-18 21:46 UTC
Labels: Area-VM

**Comment by fsc8000** [comment] 2015-08-19 08:03
@whesse, @zanderso  Maybe we should run debug-arm64 tests on the buildbot to catch things like this early. What was the reason for not running this configuration?
