### ISSUE TITLE
Cancelable operation is not working

### ISSUE THREAD

**Issue by Renesanse** [dart-lang/sdk#37817] opened 2019-08-12 16:50 UTC
```import 'dart:async';

import 'package:async/async.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyHomePage());

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool isStarted = false;
  CancelableOperation animation;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              isStarted = !isStarted;
              if (isStarted) {
                animation = CancelableOperation.fromFuture(Future.delayed(Duration(seconds: 5), () {
                  print('hello');
                }));
              } else {
                animation.cancel();
              }
            });
          },
        ),
        body: Container());
  }
}```

**Comment by Renesanse** [comment] 2019-08-12 16:51
sorry about flutter example, I cant cancel future.delayer here.

**Comment by a-siva** [comment] 2019-08-12 17:30
@Renesanse should this issue be filed in the Flutter issue tracker at https://github.com/flutter/flutter/issues

**Comment by lrhn** [comment] 2019-08-13 11:55
What do you expect to happen, and what actually happens?

I can't see you using `animation.value` anywhere. That is the future that the cancelable operation cancels. 

Do you see `animation.value` complete after calling `animation.cancel`? That is what the cancelable operation should be preventing.

**Comment by Renesanse** [comment] 2019-08-13 13:28
I see print message after calling cancel();

**Comment by lrhn** [comment] 2019-08-13 13:41
The print is expected. 
You create a future as `Future.delayed(duration, action)`.
There is *no way* to cancel that future. Eventually the duration will expire and the action is executed (which performs the print) and then the created future completes with the result (`null`).

You then wrap that future in a `CancelableOperation`. This creates a *new* future, accessible as `animation.value`. That future completes with the same result as the first future if you don't cancel the cancelable operation first. If you do cancel, then the second future never completes. This does not affect the first future at all.

If you want to cancel a *computation*, then you need to be able to send messages to the computation, so that the computation can stop itself.
In this case, you could do:

```dart
animation = CancelableOperation.fromFuture(Future.delayed(const Duration(seconds: 5), () {
  if (animation.isCanceled) return;
  print("hello");
}));
```
or do the scheduling yourself:
```dart
var done = Completer();
animation = CancelableOperation.fromFuture(done.future);
Timer(const Duration(seconds: 5), () { 
  if (animation.isCanceled) return;
  print("hello");
  done.complete(null);
});
```

**Comment by a-siva** [comment] 2019-08-14 18:11
closing issue as 'works as intended'

**Closed by a-siva** 2019-08-14 18:11 UTC
Labels: closed-as-intended

**Comment by Renesanse** [comment] 2019-08-23 08:18
> The print is expected.
> You create a future as `Future.delayed(duration, action)`.
> There is _no way_ to cancel that future. Eventually the duration will expire and the action is executed (which performs the print) and then the created future completes with the result (`null`).
> 
> You then wrap that future in a `CancelableOperation`. This creates a _new_ future, accessible as `animation.value`. That future completes with the same result as the first future if you don't cancel the cancelable operation first. If you do cancel, then the second future never completes. This does not affect the first future at all.
> 
> If you want to cancel a _computation_, then you need to be able to send messages to the computation, so that the computation can stop itself.
> In this case, you could do:
> 
> ```dart
> animation = CancelableOperation.fromFuture(Future.delayed(const Duration(seconds: 5), () {
>   if (animation.isCanceled) return;
>   print("hello");
> }));
> ```
> 
> or do the scheduling yourself:
> 
> ```dart
> var done = Completer();
> animation = CancelableOperation.fromFuture(done.future);
> Timer(const Duration(seconds: 5), () { 
>   if (animation.isCanceled) return;
>   print("hello");
>   done.complete(null);
> });
> ```

thanks for you answer

**Comment by SteveBraich** [comment] 2023-08-11 10:41
I'm trying to implement this Cancelable operation solution.  However, even though I have imported the dart:async library, CancelableOperation is undefined for me.  I am on dart 2.18.6.  Is it apart of that dart version?

I would think I should be able to answer that question myself, however, I see no version number when I look at the documentation on pub.dev for the CancelableOperation<T> class.

https://pub.dev/documentation/async/latest/async/CancelableCompleter-class.html

Thanks in advance.

**Comment by lrhn** [comment] 2023-08-11 14:04
The `CancelableCompleter` is in `package:async/async.dart`, not `dart:async`.
