### ISSUE TITLE
Null safety for containers

### ISSUE THREAD

**Issue by Fnalsk** [dart-lang/sdk#47350] opened 2021-10-01 11:07 UTC
Dart version 2.14.2 on MacOS.

I ran into this today:

`The argument type 'Future<Uint8List?>' can't be assigned to the parameter type 'Future<Uint8List>'.`

This is because a function was returning `Future<Uint8List?>`, but assigned to a variable marked `Future<Uint8List>`.

However, I know that in this particular instance of the function call, the return value will in fact be `Future<Uint8List>`. But I don't have a way to add a null check `!` to tell the compiler that this is okay, since `functionCall()!` will only assert that the outer `Future` object is not null, not the inner `Uint8List`.

It seems to me that there should be a way to add a null check to the inner type. This isn't just limited to futures; really any container will experience this same problem (such as List)

I'm wondering if this is something the dart team would consider adding.

**Comment by eernstg** [comment] 2021-10-01 11:56
I think you might need to make an extra distinction here: If the future is _actually_ a `Future<Uint8List>` rather than the statically known `Future<Uint8List?>`, then you're able to use a cast, and there should not be a problem:

```dart
Future<int?> f() => Future<int>.value(42);

Future<int> g() async {
  var fut = f();
  if (fut is Future<int>) return fut;

  // `fut` is a subtype of `Future<int?>` which is not a subtype of `Future<int>`,
  // e.g., it could be a `Future<int?>` or a `Future<Null>`.
  var value = await fut; // Could throw, but let's ignore that.
  if (value != null) {
    return value;
  } else {
     // Failing, do whatever is appropriate.
    throw "Encountered null in g!"
  }
}
```

So you may have the kind of future that you need (`Future<Uint8List>`), or you may actually have the nullable-element variant (`Future<Uint8List?>`), in which case you may still have the right kind of value (`Uint8List`), and you would then be able to build the required future. Finally, you could have null, which would presumably give rise to some error handling.

The feature you mention wouldn't be possible:

> there should be a way to add a null check to the inner type

You _can_ do that today, if it is actually concerned with the type argument of the future (or whatever type you're working on). But I suspect that you're actually looking at the middle scenario where the enclosing container _does_ have the nullable type argument, but the value that you obtain (by awaiting the future, or iterating over the collection object, or whatever it is) turns out to be non-null. But there is no way you can detect that the "inner object" isn't null without running all the code which is there to compute that inner object (e.g., you have to await the future).

**Comment by eernstg** [comment] 2021-10-01 12:06
I'll close this issue because I don't see anything which is not working as intended. @Fnalsk, please create a new issue if you still see something that you think is not working!

**Closed by eernstg** 2021-10-01 12:06 UTC
