### ISSUE TITLE
[windows][FFI] ffi retrieve value without initialized cause error

### ISSUE THREAD

**Issue by herehere** [dart-lang/sdk#44186] opened 2020-11-13 01:56 UTC
Dart SDK Version : Dart SDK version: 2.10.0-107.0.dev (dev) (Wed Sep 9 05:37:05 2020 -0700) on "windows_x64"
Using Windows
dart:ffi

As no response for the #44147 , I create a new request here.

test func in native:

	bool GetWH(int* w, int* h){
		if (w==nullptr || h==nullptr){
			return false;
		}
		*w = 0;
		*h = 0;
		return true;
	}

	bool GetpWH(int** w, int** h){
		if (w == nullptr || h == nullptr){
			return false;
		}
		*w = 0;
		*h = 0;
		return true;
	}

test code at dart:

    typedef cffi_GetWH = ffi.Void Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    typedef dffi_GetWH = void Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    dffi_GetWH gGetWHFunc;

    typedef cffi_GetpWH = ffi.Void Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    typedef dffi_GetpWH = void Function(Pointer<ffi.Uint32>, Pointer<ffi.Uint32>);
    dffi_GetpWH gGetpWHFunc;

    gGetWHFunc = myDylib.lookupFunction<cffi_GetWH, dffi_GetWH>('GetWH');
    gGetpWHFunc = myDylib.lookupFunction<cffi_GetpWH, dffi_GetpWH>('GetpWH');

    Pointer<ffi.Uint32> getW = allocate();
    Pointer<ffi.Uint32> getH = allocate();

    print("\n getWH: ${getW.value} x ${getH.value}");
    gGetWHFunc(getW, getH);
    print("\n getWH: ${getW.value} x ${getH.value}");

    free(getW);
    free(getH);

    Pointer<ffi.Uint32> getWIni = allocate();
    Pointer<ffi.Uint32> getHIni = allocate();

    getWIni.value = 100;
    getHIni.value = 100;
    print("\n getWHIni: ${getWIni.value} x ${getHIni.value}");
    gGetWHFunc(getWIni, getHIni);
    print("\n getWHIni: ${getWIni.value} x ${getHIni.value}");

    free(getWIni);
    free(getHIni);

    Pointer<ffi.Uint32> getpW = allocate();
    Pointer<ffi.Uint32> getpH = allocate();

    print("\n getpWH: ${getpW.value} x ${getpH.value}");
    gGetpWHFunc(getpW, getpH);
    print("\n getpWH: ${getpW.value} x ${getpH.value}");

    free(getpW);
    free(getpH);

    Pointer<ffi.Uint32> getpWIni = allocate();
    Pointer<ffi.Uint32> getpHIni = allocate();

    getpWIni.value = 100;
    getpHIni.value = 100;
    print("\n getpWHIni: ${getpWIni.value} x ${getpHIni.value}");
    gGetpWHFunc(getWIni, getHIni);
    print("\n getpWHIni: ${getpWIni.value} x ${getpHIni.value}");

    free(getpWIni);
    free(getpHIni);

and i got the output like this:

    flutter:
     getWH: 2390724684320 x 2390724687408
    flutter:
     getWH: 2388001816576 x 2388001816576
    flutter:
     getWHIni: 100 x 100
    flutter:
     getWHIni: 0 x 0
    flutter:
     getpWH: 2390724684272 x 5567
    flutter:
     getpWH: 0 x 0
    flutter:
     getpWHIni: 100 x 100
    flutter:
     getpWHIni: 100 x 100

obviously difference on the value is initialized or not.

**Comment by mraleph** [comment] 2020-11-13 08:21
duplicate of #44147

**Closed by mraleph** 2020-11-13 08:21 UTC
Labels: area-vm, library-ffi
