### ISSUE TITLE
Confusing error with constructors and optional parameters

### ISSUE THREAD

**Issue by eukreign** [dart-lang/sdk#27754] opened 2016-11-03 23:10 UTC
I have the following code:

```dart
abstract class Row {}

abstract class TotalRow implements Row {}

class TestRow extends Row {
  TestRow(String first, [String second = ""]) {}
}

class TestTotalRow extends TestRow with TotalRow {
  TestTotalRow(String first, [String second = ""]): super(first, second);
}
```
https://dartpad.dartlang.org/d03416b40588306be9722f72b55fae2a

It produces a strange analyzer error related to optional parameters in constructor:

`This mixin application is invalid because all of the constructors in the base class 'TestRow' have optional parameters.`

Is this expected behavior? Is it not possible to forward to a constructor with optional parameters?

**Comment by Scorpiion** [comment] 2016-11-03 23:15
Here is an even simpler code example based on @eukreign code, I tried to figure it out on a Dartpad after being posted on slack:

```dart
class MyParent { 
  MyParent(String firstName, [String lastName = ""]) {}
}

class MyMixin { }

class MyChildClass1 extends MyParent {
  MyChildClass1(String firstName, String lastName): super(firstName, lastName);
}

class MyChildClass2 extends MyParent with MyMixin {
  MyChildClass2(String firstName, String lastName): super(firstName, lastName);
}
```

MyChildClass1 works as expected, MyChildClass2 gets the error.

**Comment by eukreign** [comment] 2016-11-03 23:16
Related:
https://github.com/dart-lang/sdk/issues/17610
https://github.com/dart-lang/sdk/issues/15101

**Comment by munificent** [comment] 2016-12-13 22:23
Dupe of #15101.

**Closed** 2016-12-13 22:23 UTC
Labels: area-language, Resolution: duplicate
