### ISSUE TITLE
type 'Null' is not a subtype of type 'Procedure' in type cast

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/sdk#53693] opened 2023-10-05 20:01 UTC
When I try to execute [Typings](https://pub.dev/packages/typings) builder I am having this error with SDK 3.1.3 but works ok with 3.0.7:

```
[INFO] Generating build script completed, took 466ms
[INFO] Precompiling build script......Unhandled exception:
Crash when compiling:
type 'Null' is not a subtype of type 'Procedure' in type cast

#0      MatchingExpressionVisitor.visitObjectPattern (package:front_end/src/fasta/type_inference/matching_expressions.dart:427:68)
#1      ObjectPattern.accept1 (package:kernel/src/ast/patterns.dart:622:15)
#2      MatchingExpressionVisitor.visitPattern (package:front_end/src/fasta/type_inference/matching_expressions.dart:27:17)
#3      ConstantsTransformer.visitPatternVariableDeclaration (package:front_end/src/fasta/kernel/constant_evaluator.dart:1652:35)
#4      PatternVariableDeclaration.accept1 (package:kernel/src/ast/patterns.dart:2016:14)
#5      RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1920:21)
#6      ConstantsTransformer.visitBlock (package:front_end/src/fasta/kernel/constant_evaluator.dart:779:27)
#7      Block.accept1 (package:kernel/ast.dart:9176:58)
#8      RemovingTransformer.transform (package:kernel/visitor.dart:1884:17)
#9      IfStatement.transformOrRemoveChildren (package:kernel/ast.dart:10093:14)
#10     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2166:10)
#11     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:770:48)
#12     TreeVisitor1.visitIfStatement (package:kernel/visitor.dart:810:50)
#13     IfStatement.accept1 (package:kernel/ast.dart:10068:9)
#14     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1920:21)
#15     ConstantsTransformer.visitBlock (package:front_end/src/fasta/kernel/constant_evaluator.dart:779:27)
#16     Block.accept1 (package:kernel/ast.dart:9176:58)
#17     RemovingTransformer.transform (package:kernel/visitor.dart:1884:17)
#18     IfStatement.transformOrRemoveChildren (package:kernel/ast.dart:10093:14)
#19     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2166:10)
#20     TreeVisitor1.defaultStatement (package:kernel/visitor.dart:770:48)
#21     TreeVisitor1.visitIfStatement (package:kernel/visitor.dart:810:50)
#22     IfStatement.accept1 (package:kernel/ast.dart:10068:9)
#23     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1920:21)
#24     ConstantsTransformer.visitBlock (package:front_end/src/fasta/kernel/constant_evaluator.dart:779:27)
#25     Block.accept1 (package:kernel/ast.dart:9176:58)
#26     RemovingTransformer.transform (package:kernel/visitor.dart:1884:17)
#27     ConstantsTransformer.visitFunctionNode (package:front_end/src/fasta/kernel/constant_evaluator.dart:602:19)
#28     FunctionNode.accept1 (package:kernel/ast.dart:3912:9)
#29     RemovingTransformer.transform (package:kernel/visitor.dart:1884:17)
#30     ConstantsTransformer.visitProcedure.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:519:23)
#31     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:5266:18)
#32     ConstantsTransformer.visitProcedure (package:front_end/src/fasta/kernel/constant_evaluator.dart:517:23)
#33     Procedure.accept1 (package:kernel/ast.dart:3314:55)
#34     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1920:21)
#35     RemovingTransformer.transformList (package:kernel/visitor.dart:2143:19)
#36     RemovingTransformer.transformProcedureList (package:kernel/visitor.dart:2035:5)
#37     ConstantsTransformer.visitClass.<anonymous closure> (package:front_end/src/fasta/kernel/constant_evaluator.dart:473:7)
#38     ConstantEvaluator.withNewEnvironment (package:front_end/src/fasta/kernel/constant_evaluator.dart:5266:18)
#39     ConstantsTransformer.visitClass (package:front_end/src/fasta/kernel/constant_evaluator.dart:468:23)
#40     Class.accept1 (package:kernel/ast.dart:1425:53)
#41     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1920:21)
#42     RemovingTransformer.transformList (package:kernel/visitor.dart:2143:19)
#43     RemovingTransformer.transformClassList (package:kernel/visitor.dart:1999:5)
#44     ConstantsTransformer.convertLibrary (package:front_end/src/fasta/kernel/constant_evaluator.dart:429:5)
#45     transformLibraries (package:front_end/src/fasta/kernel/constant_evaluator.dart:111:26)
#46     KernelTarget.runBuildTransformations (package:front_end/src/fasta/kernel/kernel_target.dart:1535:19)
#47     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:637:7)
<asynchronous suspension>
#48     withCrashReporting (package:front_end/src/fasta/crash.dart:133:12)
<asynchronous suspension>
#49     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:588:12)
<asynchronous suspension>
#50     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:413:23)
<asynchronous suspension>
#51     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
<asynchronous suspension>
#52     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:604:11)
<asynchronous suspension>
#53     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1316:11)
<asynchronous suspension>
[INFO] Precompiling build script... completed, took 8.8s
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

**Comment by johnniwinther** [comment] 2023-10-13 12:23
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/314060

**Comment by jodinathan** [comment] 2023-12-15 15:19
it is still happening but in a different line:

```
Crash when compiling:
type 'Null' is not a subtype of type 'Procedure' in type cast

#0      MatchingExpressionVisitor.visitObjectPattern (package:front_end/src/fasta/type_inference/matching_expressions.dart:414:68)
```

**Comment by johnniwinther** [comment] 2023-12-20 12:04
@jodinathan Do you know what triggered the crash?

**Comment by jodinathan** [comment] 2023-12-20 12:06
@johnniwinther same in the original post. I am just trying to run the Typings builder.  
Works alright with 3.0.7

**Comment by jodinathan** [comment] 2023-12-20 12:06
@johnniwinther 

Could you please give this some urgency flag because it has been months that I can't upgrade the SDK because of this.

**Comment by johnniwinther** [comment] 2023-12-20 12:14
Thanks, I'll take look into this.

**Comment by johnniwinther** [comment] 2023-12-20 13:26
@jodinathan What version of `package:typings` are you using and how you building this? I tried a simple web-app importing `package:typings` (getting version `0.0.6+1`) and it fails to compile due to `inline class` syntax in `ts2dart-0.0.6`.

**Comment by jodinathan** [comment] 2023-12-20 13:40
when you use recent version of the SDK you need to change `inline class` for `extension types` then you get the mentioned error.

**Comment by jodinathan** [comment] 2023-12-20 13:42
to test the error is easier to run the ts2dart/bin/ts2dart.dart

**Comment by johnniwinther** [comment] 2023-12-20 15:44
I was able to reproduce the error in `3.2.2` and created a CL (https://dart-review.googlesource.com/c/sdk/+/342880) that verifies that this has been fixed on the bleeding edge, likely in https://dart-review.googlesource.com/c/sdk/+/333160

**Closed** 2023-12-21 11:44 UTC
Labels: P1, front-end-fasta, area-front-end

**Comment by jodinathan** [comment] 2023-12-21 12:35
@johnniwinther will this be released in 3.2.4?

**Comment by johnniwinther** [comment] 2023-12-21 13:46
Since this is part of the experimental feature `inline-class` it will not be cherry-picked to `3.2.4`. Experimental features should be tested on the main channel, but the feature, including the fix, is part of the latest beta.

**Comment by jodinathan** [comment] 2023-12-21 14:41
oh I didn't know it was because of `inline-class`.  
I will try the beta and if anything comes up I will stop using the feature for now

**Comment by johnniwinther** [comment] 2023-12-21 14:43
Better yet, if something comes up, let us know - we plan to release the feature!
