### ISSUE TITLE
Analyzer: Incorrect analysis of last switch-case statement

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/sdk#28042] opened 2016-12-08 23:37 UTC
You can see a reproduction on [Dart Pad][dart_pad]:

```dart
String getState(bool option) {
  State state;
  switch (state) {
    case State.idle:
      return 'Idle!';
    case State.working:
    // ^ The last statement of the 'case' should be 'break', 'continue', 'rethrow', 'return' or 'throw'. 
      if (option) {
        return 'Working hard';
      } else {
        return 'Hardly working';
      }
    default:
      return 'Not sure what you are doing';
  }
}

enum State {
  idle,
  working,
}
```

[dart_pad]: https://dartpad.dartlang.org/b193390124a30cc204a7e26591b38c94

I'd imagine this should be fine and should not return an error. I can silence it by:

```dart
if (otion) {
  return 'Working hard';
}
return 'Hardly working';
```

Which is arguably better, but for product excellence we should still fix this error for noobies.

**Comment by bwilkerson** [comment] 2016-12-08 23:45
This behavior is required by the language specification, section 17.9:

> Let s be the last statement of the statement sequence sk. If s is a non-empty block statement, let s instead be the last statement of the block statement. It is a static warning s is not a break, continue, rethrow or return statement or an expression statement where the expression is a throw expression.

That said, this behavior has irritated users from the very beginning. There is work started to extend type promotion that defines the concept of "terminates" much more fully, and it's possible that that definition could be used here to great effect.

**Comment by lrhn** [comment] 2016-12-09 09:51
I'm very sympathetic to fixing this, but it's sadly not topping our list of priorities.

There are two problems. One is that we have a warning at all - it could all be solved by removing the warning and just breaking instead of throwing when you reach the end of a case. 
The other is that while we do have the warning, the specification doesn't have a useful definition of reachability, so it falls back on the rather brain-dead "must end with" requirement.
As Brian says, it's not the only place we can use a better reachability analysis (and the result of lacking it elsewhere is also that it makes the compiler look stupid when it doesn't realize something that is immediately obvious to the programmer).

**Comment by matanlurey** [comment] 2016-12-09 17:25
Happy to keep open and tracked for the time being.

**Comment by srawlins** [comment] 2016-12-14 21:22
Duplicate of [#7537](https://github.com/dart-lang/sdk/issues/7537#issuecomment-108345494)?

**Comment by munificent** [comment] 2016-12-22 22:16
No, that issue is a little different. This one is about doing slightly smarter flow analysis for the bodies of a switch case. In particular, it's asking to treat an `if` statement as definitely exiting if both its then and else arms definitely exit.

**Comment by srawlins** [comment] 2020-06-17 14:03
The spec has changed under the null safety type system, to use flow analysis. The motivating example now passes without analysis errors using `dartanalyzer --enable-experiment=non-nullable`. 🎊

**Closed by srawlins** 2020-06-17 14:03 UTC
Labels: area-language, type-enhancement
