### ISSUE TITLE
ffi/structs_test fails with CompileTimeError in NNBD strong mode

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#41124] opened 2020-03-20 04:37 UTC
After https://dart-review.googlesource.com/c/sdk/+/140240 ffi/structs_test starts failing in NNBD strong mode with a compile-time error instead of crashing:

```
/=========================================================================================================\
| dartk-strong-linux-release-x64:ffi/structs_test failed again (Crash -> CompileTimeError, expected Pass) |
\=========================================================================================================/

--- Command "vm" (took 821ms):
DART_CONFIGURATION=ReleaseX64NNBD out/ReleaseX64NNBD/dart --deterministic --optimization-counter-threshold=50 --null-safety --enable-experiment=non-nullable --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/ffi/structs_test.dart

exit code:
254

stderr:
tests/ffi/coordinate_bare.dart:12:10: Error: Field 'x' should be initialized because its type 'double' doesn't allow null.
  double x;
         ^
tests/ffi/coordinate_bare.dart:15:10: Error: Field 'y' should be initialized because its type 'double' doesn't allow null.
  double y;
         ^
tests/ffi/coordinate_bare.dart:17:23: Error: Field 'next' should be initialized because its type 'Pointer<Coordinate>' doesn't allow null.
 - 'Pointer' is from 'dart:ffi'.
 - 'Coordinate' is from 'tests/ffi/coordinate_bare.dart'.
  Pointer<Coordinate> next;
                      ^^^^

--- Re-run this test:
python tools/test.py -n dartk-strong-linux-release-x64 ffi/structs_test
```

/cc @dcharkes

**Comment by stefantsov** [comment] 2020-03-20 07:51
That may be a problem with opting tests in and out which surfaced after I enabled --force-nnbd-checks by default and turned all NNBD-related warnings into errors in weak mode.  In that case if the test was meant to run in opt-out mode, it'll currently run correctly on non-nnbd modes and will produce compile-time errors on nnbd bots.  We're working on a solution to opt the tests in and out correctly on all bots.

**Comment by mkustermann** [comment] 2020-03-20 09:08
Since these are opted-in tests the actual issue surfaced here is correct.

There is discussions with the language team on how to solve this, for now we discussed making struct fields as `late`. @dcharkes Should we change our migrated tests to do so or approve the failures instead (and wait for language change)?

**Comment by dcharkes** [comment] 2020-03-20 09:47
tests/ffi/* are migrated indeed.

Approve for now. We focus on adding new features to `dart:ffi` in legacy mode (non-NNBD) first. I'll get around to this when we want to enable using `dart:ffi` in NNBD.

**Comment by dcharkes** [comment] 2020-04-14 15:55
Duplicate of https://github.com/dart-lang/sdk/issues/40247.

**Closed by dcharkes** 2020-04-14 15:55 UTC
Labels: NNBD, area-vm, library-ffi
