### ISSUE TITLE
Missing error in infeasible instantiation?

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#32723] opened 2018-03-31 00:39 UTC
@leafpetersen I believe the following should be a compile-time error since `int` can't extend `String`:

```dart
class C<CT> {
  BT bar<BT extends CT>(BT x) => x;
}
main() {
  int Function(int) f3 = new C<String>().bar;
}
```

**Comment by leafpetersen** [comment] 2018-03-31 00:42
Yes, this should be a compile time error.

**Comment by jmesserly** [comment] 2018-03-31 01:18
Analyzer handles this correctly, FWIW:
```
[error] Couldn't infer type parameter 'BT extends String'.

Tried to infer 'int' for 'BT extends String' which doesn't work:
  Type parameter 'BT extends String' declared to extend 'String'.
The type 'int' was inferred from:
  Function type declared as '<BT extends String>(BT) → BT'
                used where  '(int) → int' is required.

Consider passing explicit type argument(s) to the generic.
```

**Comment by askeksa-google** [comment] 2018-08-14 08:57
Closing as duplicate of https://github.com/dart-lang/sdk/issues/33308

**Closed by askeksa-google** 2018-08-14 08:57 UTC
Labels: area-front-end, front-end-missing-error
