### ISSUE TITLE
Could approve_results.dart more gracefully handle lack of permissions?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/sdk#35913] opened 2019-02-11 18:48 UTC
This is the first time I have tried to preapprove some test failures. I ran:

```
$ tools/sdks/dart-sdk/bin/dart tools/approve_results.dart -b ddc-linux-release-chrome -b analyzer-analysis-server-linux -b analyzer-linux-release -p https://dart-review.googlesource.com/c/sdk/+/92480/1
```

The CLI tool crashed. I suspect I might not have the right permissions somewhere but the error isn't actionable enough for me to know what I should do to get the permissions I need:

```
Selected bot: ddc-linux-release-chrome
Selected bot: analyzer-analysis-server-linux
Selected bot: analyzer-linux-release
Unhandled exception:
Exception: Failed to run: python /Users/nshahan/code/dart-sdk/sdk/third_party/gsutil/gsutil.py [-m, cp, -r, -Z, gs://dart-test-results-approved-results/builders/analyzer-analysis-server-linux/approved_results.json, /var/folders/yf/rl2gr0w14cx38nq8bv4r2qlr009rgp/T/approve_results.UCjAL1/approved_results.json]
exitCode: 1
stdout:

stderr:
ServiceException: 401 Anonymous caller does not have storage.objects.get access to dart-test-results-approved-results/builders/analyzer-analysis-server-linux/approved_results.json.
CommandException: 1 file/object could not be transferred.

#0      runGsutil (file:///Users/nshahan/code/dart-sdk/sdk/tools/bots/results.dart:33:5)
<asynchronous suspension>
#1      cpRecursiveGsutil (file:///Users/nshahan/code/dart-sdk/sdk/tools/bots/results.dart:68:5)
#2      loadResultsFromBot (file:///Users/nshahan/code/dart-sdk/sdk/tools/approve_results.dart:120:7)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#9      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#10     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#11     loadLog (file:///Users/nshahan/code/dart-sdk/sdk/tools/approve_results.dart)
#12     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     Stream.toList.<anonymous closure> (dart:async/stream.dart:975:18)
#18     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#19     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#20     _RootZone.run (dart:async/zone.dart:1374:54)
#21     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
#22     Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
#23     Future._propagateToListeners (dart:async/future_impl.dart:665:37)
#24     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:348:9)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#28     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by nshahan** [comment] 2019-02-11 19:22
The issue was user error on my part. I had not authenticated with the `gsutil.py` script yet. I'm updating the issue as a request to handle the error and print a helpful message.

**Comment by sortie** [comment] 2019-02-14 14:13
Thanks for the suggestion! Yeah I was meaning to do this.

**Comment by sortie** [comment] 2019-02-14 14:20
Duplicate of https://github.com/dart-lang/sdk/issues/35377

**Closed by sortie** 2019-02-14 14:20 UTC
Labels: area-infrastructure, closed-duplicate, p2-medium, type-enhancement
