### ISSUE TITLE
Cannot postMessage() with WorkerGlobalScope.instance

### ISSUE THREAD

**Issue by mnordine** [dart-lang/sdk#34926] opened 2018-10-25 14:27 UTC
* Dart SDK Version 2.1.0-dev.8.0
* MacOS Mojave
* Chrome 70

Trying to postMessage back to main from a worker is not possible.

`main.dart`
```dart
import 'dart:html';

void main() {
  if (Worker.supported) {
    final worker = Worker('test.dart.js');
    worker.postMessage('hi from main');
    worker.onMessage.listen((e) => print('message from worker: ${e.data}'));
  }
}
```

`test.dart`
```dart
import 'dart:html';

main() {
  print('worker main()');
  final self = WorkerGlobalScope.instance;

  self.on['message'].listen((e) {
    final MessageEvent event = e;
    print('message from main: ${event.data}');
    // self.postMessage('hi from worker'); // nope
  });
}
```

Output (`webdev serve`): 
```
```

Output (`webdev build`): 
```
worker main()
message from main: hi from main
```

Output (`webdev build --no-release`)
```
```

Separate issue for it not working in `webdev serve` or `webdev build --no-release`: https://github.com/dart-lang/sdk/issues/34928

**Comment by kevmoo** [comment] 2018-10-26 22:48
Duplicate of #34924 

Pretty sure this is all the same core issue

**Closed by kevmoo** 2018-10-26 22:48 UTC
Labels: area-library, library-html
