### ISSUE TITLE
builds on Travis suffer from shutdown races

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#43979] opened 2020-10-29 15:27 UTC
See for example: https://travis-ci.org/github/dart-lang/pub/jobs/739914071

Running `dart --disable-analytics` seemingly deadlocks.

**Comment by devoncarew** [comment] 2020-10-29 16:20
cc @bkonyi

**Comment by devoncarew** [comment] 2020-10-29 16:21
This is for Dart `2.11.0-266.0.dev (dev) (Tue Oct 27 04:42:01 2020 -0700)`.

@mraleph or @sigurdm, do you know how frequent this is? I haven't seen this myself or heard of other reports (otherwise I'd bump to a P1).

**Comment by bkonyi** [comment] 2020-10-29 16:58
Have we been able to reproduce this at all?

**Comment by mraleph** [comment] 2020-10-29 17:14
I have seen multiple builds timeout for this reason - have not tried to repro. @mkustermann was saying that he has some ideas what can cause that

**Comment by devoncarew** [comment] 2020-10-29 18:57
Seeing this here as well: https://travis-ci.org/github/dart-lang/linter/jobs/739980709

(cc @pq )

**Comment by devoncarew** [comment] 2020-10-29 18:58
Possibly from this commit: 5a3e7bf18fe3b7acc20c0f645ce45b50574d3550

cc @sigurdm

**Comment by devoncarew** [comment] 2020-10-29 19:09
And in-lined from that travis job:

```
NoSuchMethodError: The getter 'enabled' was called on null.
Receiver: null
Tried calling: enabled
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      runDartdev (package:dartdev/dartdev.dart:114:19)
#2      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by pq** [comment] 2020-10-29 19:11
A salient detail of the linter failure is that analytics are **not** disabled, with `dart` invoked like this:

```
  dart --disable-service-auth-codes \
    --enable-vm-service=$OBS_PORT \
    --pause-isolates-on-exit \
    test/all.dart &


```

**Comment by bkonyi** [comment] 2020-10-29 19:27
> And in-lined from that travis job:
> 
> ```
> NoSuchMethodError: The getter 'enabled' was called on null.
> Receiver: null
> Tried calling: enabled
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      runDartdev (package:dartdev/dartdev.dart:114:19)
> #2      main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
> #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
> #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> ```

That looks like an older version than 5a3e7bf since the line numbers don't match up.

**Comment by pq** [comment] 2020-10-29 19:53
Ah, you're right!  That landed yesterday while the failing SDK is from the day before...

```
$ dart --version
Dart SDK version: 2.11.0-266.0.dev (dev) (Tue Oct 27 04:42:01 2020 -0700) on "linux_x64"
```

My current thinking is to roll back off `dev` to `beta` but due to travis slowness I haven't seen if that gets me back to green just yet.

**Comment by devoncarew** [comment] 2020-10-29 19:54
> Possibly from this commit: [5a3e7bf](https://github.com/dart-lang/sdk/commit/5a3e7bf18fe3b7acc20c0f645ce45b50574d3550)

Or, perhaps this one: https://github.com/dart-lang/sdk/commit/cef442344571a5442779c5035d6aad3364308283

**Comment by bkonyi** [comment] 2020-10-29 20:13
I'm unable to reproduce this locally, but it looks like something racey is causing the isolates to hang at shutdown.

**Comment by bkonyi** [comment] 2020-10-29 20:26
I think this is actually caused by the call to `exit()` [here](https://github.com/dart-lang/sdk/blob/master/pkg/dartdev/lib/dartdev.dart#L72). We should be calling `VmInteropHandler.exit()` instead so the main thread can get unblocked before we try and shutdown the VM.

**Closed** 2020-10-29 22:13 UTC
Labels: P1, area-dart-cli

**Comment by pq** [comment] 2020-11-02 17:49
Looks like this fix made it into `dev` but we're hitting what looks like a fresh snag....

![image](https://user-images@bkonyi ithubusercontent.com/67586/97901189-ae7ba680-1cf0-11eb-8562-d0312ff151a1.png)


@bkonyi : is this a known issue?
