### ISSUE TITLE
Can't throw AssertionError because in practice it hides the problem.

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/sdk#41466] opened 2020-04-13 18:39 UTC
In practice, as soon as I get an `AssertionError` I have to change it for something else because it just hides the problem. I mean, in tests or logs, when I print an `AssertionError` I should get some useful information.

Suppose I do:

    if (x > 64) throw AssertionError(x);

It just tells me:

    Assertion failed

What's the point of allowing a message in its constructor, if it just throws it away?

Instead, it should say:

    Assertion failed: 78

I propose its `toString()` method should be:

    String toString() => "Assertion failed with message: $message";

**Comment by vsmenon** [comment] 2020-04-14 16:58
What tool are you using?  E.g., web / native?  debug / prod? - I don't think they are consistent here.

**Comment by marcglasberg** [comment] 2020-04-14 17:26
@vsmenon Depending on the tool, since the `toString()` doesn't print the message, the tool could check if the error is of type `AssertionError` and then go fetch the message and print it. But I don't think we should depend on the tool. It could be, for example, some logger in a cloud-function that we have no control of. The only piece of information we are reasonably sure to always get is the `toString()` output.

**Comment by vsmenon** [comment] 2020-04-14 17:33
Sorry, I meant that different compilers / runtimes themselves are implementing the `toString()` differently.  Which are you testing?  The VM (AOT or JIT)?  DDC?  Dart2JS?

I'd expect the debug runtimes to give good messages.  The prod ones may not (as they are typically run in a mode where asserts are disabled anyway).

**Comment by vsmenon** [comment] 2020-04-14 17:34
That said, I'd expect the actual message to be in all of them.

**Comment by marcglasberg** [comment] 2020-04-14 17:36
I'm developing for Flutter, running a test, in Windows desktop, IntelliJ Community.

    class AssertionError extends Error {
      /** Message describing the assertion error. */
      final Object message;
      AssertionError([this.message]);
      String toString() => "Assertion failed";
    }

**Comment by lrhn** [comment] 2020-04-15 12:58
Duplicate of #40245. 
The change has already landed, https://dart-review.googlesource.com/c/sdk/+/132640, so it should show up in your Dart "real soon now".

**Closed** 2020-04-15 12:59 UTC
Labels: area-library, library-core
