### ISSUE TITLE
Production issues with firebase after compiling with dart2js

### ISSUE THREAD

**Issue by samuelsonokoi** [dart-lang/sdk#36081] opened 2019-03-01 15:04 UTC
i've struggled with this firebase issue for some time and i haven't been able to fix it, i noticed that whenever i compile my application for production using `webdev build` it builds successfully but when you host it in production it gives me a console error saying some certain functions couldn't be found thus causing issue with displaying data from firebase etc. 

i think this is a **dart2js** problem because the said application runs well in development using the **dartdevc** and if you include a build.yaml file with the following
`
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dartdevc
`

the app runs well without an issue. i don't know if other packages might have this same issue but i've only noticed it with **firebase plugin**

pubspec.yaml file
`
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  angular: ^5.2.0
  firebase: ^5.0.2
`

index.html file
`
<script src="https://www.gstatic.com/firebasejs/5.8.2/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.8.2/firebase-firestore.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.8.2/firebase-auth.js"></script>
`

**Comment by sigmundch** [comment] 2019-03-01 18:17
@samuelsonokoi would you be able to provide us with a little more details?

In particular, what error do you see? Could you provide us a small example Dart program that reproduces the issues you are seeing? If we can see how you are accessing the firebase APIs from Dart, we can hopefully narrow down what the problem is.

Some things to have in mind that could be the cause of the problem:

* Could the problem be related to name minification in dart2js?

  By default webdev passes `--minify` to dart2js. To know if this is the source of the problem, you can override the command-line arguments for dart2js so that no flags are passed (or if you need to specify something, pass `-O1` which is the default setting without minification).

* Could the problem be because of passing closures as callbacks?

  If I recall correctly, the firebase plugin uses jsinteorp, but I'm not sure if they handle calling `allowInterop` on callbacks or if that's responsibility of the consumer of the plugin. It's a known problem that the devcompiler and dart2js behave differently when callbacks are used in js-interop, especially when they not wrapped with `allowInterop` (for example, issue #33134)

**Comment by samuelsonokoi** [comment] 2019-03-01 23:38
Here is the error i'm getting from the console when using `webdev serve --release`
![console-errors](https://user-images.githubusercontent.com/12806939/53672392-a26d5500-3c82-11e9-84b2-7eb0ca3acc1b.png)

here is how i'm assessing firebase in my main.dart file
`void main() {
  runApp(ng.AppComponentNgFactory, createInjector: injector);

  fb.initializeApp(
    apiKey: "key",
    authDomain: "domain",
    databaseURL: "db_url",
    projectId: "project_id",
    storageBucket: "storage_bucket",
    messagingSenderId: "messaging_id"
  );
  fb.firestore().enablePersistence();
}`

i have also tried to pass the -O2 and -O0 but to no avail 
`targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
          - -O2`

**Comment by sigmundch** [comment] 2019-03-01 23:59
I've seen other teams successful at overriding the flag by using:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
          - -O1
```

Which looks almost identical to what you have (except that this example omits the name of the compiler), so I'm not sure why you had no success with that. Note `-O0` may not always work and `-O2` includes minifcation so you'll still get the obfuscated errors in that case.

@natebosch @jakemac53 - any tips on how to get a debug output of dart2js served properly with webdev?

**Comment by samuelsonokoi** [comment] 2019-03-02 05:11
Yes it still gave me an error too, here is the new error i got.
![console-error1](https://user-images.githubusercontent.com/12806939/53677516-6bfafe80-3cb1-11e9-97b1-a1c9f2eeede9.png)

and you can see that it passes the -O1 options from the `webdev serve --release` terminal output
![console](https://user-images.githubusercontent.com/12806939/53677536-d14eef80-3cb1-11e9-8412-308c34d6c80b.png)

**Comment by sigmundch** [comment] 2019-03-04 19:36
Nothing obvious stands out from the snippet of code or the error message. Unfortunately, I don't know what else we can do right now without having at hand a program that we can debug. If you can send us a small repro (ideally a small program that only uses firebase in isolation, without even using angular), we'd be happy to help take a look.

I hope you find the `-O1` mode helpful. It is often useful to isolate where problems are coming from and narrow things down. I'd recommend you try to look at why accessing the `location` and `fullName` properties is failing - maybe seeing what `t1` and `local_user` is in the debugger before the exception might give clues into why it doesn't have the properties we expect. It looks to me like we believe those are regular calls to Dart objects and not calls to Js-interop objects. If these objects are returned by Firebase via JS-interop, then that feels like a bug on our compiler that we need to track down.

Keep us posted!

**Comment by samuelsonokoi** [comment] 2019-03-07 09:13
@sigmundch permit me to add you as a collaborator so you can clone the project, i wouldn't want to make it public.

**Comment by sigmundch** [comment] 2019-03-07 18:51
Thanks @samuelsonokoi - I totally understand that you want to keep it private, no worries. Unfortunately, I am not allowed to accept your invitation to read your private project. We'll have to continue to try to debug this bit by bit :)

The best thing would probably be to continue to try to create a small tiny program that reproduces the issue. Sometimes I have more luck taking a big program and commenting out portions until I have something tiny. Sometimes I have luck just coping a snippet of the code directly into the main function.

For example, if you move the access to `local_user.fullName` to the main entrypoint of the program, are you able to see the error there?

The ideal would be to find ways to get the error to happen without using angular along the way, but it might be easier to first create an angular program that would show the error. In particular, I'm guessing you may be accessing the location/fullName properties from angular template (given that the error was thrown by the change detection code generated by angular), maybe we can create a tiny angular view that shows the exact same problem?

Besides that, more details on the error might help narrow down ideas. Using the chrome console, set it up to stop when exceptions are thrown and inspect the variables in the stack when you are about to get the error. What is the type of `t1` and `local_user` before the exception? Do they look like plain Javascript objects or Dart-like objects? Does `t1` has a `location` field, similarly, does `local_user` have a `fullName` field?

Hope this helps!

**Comment by joshualitt** [comment] 2021-11-15 21:40
I'm going to close this issue because there isn't much we can do with this bug as is. If this issue is still occurring, please reopen this issue.

**Closed by joshualitt** 2021-11-15 21:40 UTC
Labels: web-dart2js, area-web
