### ISSUE TITLE
Chrome/firefox run-time errors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30027] opened 2017-06-27 11:46 UTC
The buildbot `dart2js-linux-chromeff-2-4-be` has had 5 failing builds recently (5029, 30, 36, 37, 39), all marked with dart2js-{chrome,firefox} release_x64 and all in co19, all RuntimeError. 

In these cases the error is always either a `sync_exception .. Unable to fetch WebGL rendering context for Canvas` or `window.onerror called` with an empty error message.

**Comment by eernstg** [comment] 2017-06-27 12:41
dart2js-linux-chromeff-1-4-be and dart2js-linux-chromeff-4-4-be show very similar symptoms in recent builds, especially `sync_exception` occurs many times (with various different error messages attached).

**Comment by athomas** [comment] 2017-09-19 14:36
Duplicate of #29961.

**Closed by athomas** 2017-09-19 14:36 UTC
Labels: area-dart2js, browser-chrome, browser-firefox, gardening
