### ISSUE TITLE
Dart 2 issue in front_end

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#32867] opened 2018-04-12 20:06 UTC
```
~/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.0-alpha.9/lib/src/fasta/source/outline_builder.dart:736:49: Error: A value of type 'dart.core::List<dynamic>' can't be assigned to a variable of type 'dart.core::Iterable<fasta.formal_parameter_builder::FormalParameterBuilder<fasta.type_builder::TypeBuilder>>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.core::Iterable<fasta.formal_parameter_builder::FormalParameterBuilder<fasta.type_builder::TypeBuilder>>'.
        formals.setRange(count, formals.length, last);
```

This will prevent running any test in Dart 2 mode.

**Comment by peter-ahe-google** [comment] 2018-04-13 07:12
This is a duplicate of #31623.

**Closed by peter-ahe-google** 2018-04-13 07:12 UTC
Labels: Resolution: duplicate, area-front-end, front-end-fasta
