### ISSUE TITLE
Never reach the error in either future.catchError or runZoned.onError if run with completer.completeError()

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#31826] opened 2018-01-10 04:57 UTC
Not quite sure whether it's a spec. or a bug.
Here is a simplified test case, for example, (same result in dart2js or dartium)
```
main() {
  var completer = new Completer();
  var future = completer.future;
//  this works.
//  future.catchError((e) {
//    print("This works");
//  });
  runZoned(() {
    future.catchError((e) {
      print("Never reached!");
    });
    completer.completeError("");
  }, onError: (e) {
    print("Never reached!");
  });
}
```

**Comment by tomyeh** [comment] 2018-01-10 05:06
For reference, this one works. It seems: Completer can't be instantiated outside of `runZoned` where it was used.

```
void main () {
  runZoned(() {
    var completer = new Completer();
    var future = completer.future;
    future.catchError((e) {
      print("Never reached!");
    });
    completer.completeError("");
  }, onError: (e) {
    print("Never reached!");
  });
}
```

**Comment by lrhn** [comment] 2018-01-10 12:15
The second example shows what is going wrong.

The completer was created in the root zone, and the future was listened to (using `catchError`) in the `runZoned` created "error zone" (a zone with a custom error handler).

The completer considers the error to originate in the zone where it was created, its only listener is in a different error zone, and errors cannot transition error zones, so the error is instead handed to the root zone's uncaught error handler.

It's working as designed.

**Comment by vsmenon** [comment] 2018-01-10 13:39
Closing per @lrhn 's comment.

**Closed by vsmenon** 2018-01-10 13:39 UTC
Labels: area-library, library-async

**Comment by tomyeh** [comment] 2018-01-10 15:33
@lrhn Thanks for explanation. It explains the issue of uncaught zone's error handler. However, there is a subtle issue not addressed, and I think it is a bug -- at least, inconsistent. To illustrate:

```
void main () {
  var c1 = new Completer();
  runZoned(() {
    c1.future.catchError((e) {
      print("Caught");
    });
    c1.completeError("e1"); //e1 will be caught
  });

  var c2 = new Completer();
  runZoned(() {
    c2.future.catchError((e) {
      print("Not caught");
    });
    c2.completeError("e2"); //e2 won't
  }, onError: () {});
}
```

In this case, e1 will be caught while e2 won't. That is, specifying a zone's error handler will change the behavior of future's error handler.

**Comment by lrhn** [comment] 2018-01-15 08:45
Yes, that is intended behavior. If a zone does not introduce a new error handler, it is considered to be in the same "error zone" as its parent zone, and errors from one zone can flow into the other unhindered. Or, in different words, if the new zone doesn't introduce new error handling, error handling ignores that it's a new zone, so you don't accidentally change error behavior when you're just using zones for something else.

You can think of Dart zones and errors as if all zones that have the same error handler are one "error zone" (all equivalent wrt. errors). Asynchronous errors cannot flow between different *error zones*, but flows freely between zones in the same "error zone".

**Comment by tomyeh** [comment] 2018-01-16 06:46
Got it. Thanks.
