### ISSUE TITLE
gen_snapshot uses lots of strings for program structure

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#48911] opened 2022-04-28 04:43 UTC
Looking at the output of a release gen_snapshot for customer: money, there are about 12 megabytes of strings.

About 9.6 megabytes of those strings are string literals related to program structure (package/library, class, method names, including stub/generated methods). 

There are almost 120k of these individual strings. Some of them _must_ remain in string form to serve as external symbols. The vast majority of them do not need to look this way, certainly not in release/product mode.

Perhaps gen_snapshot could generate some kind of map for resolving symbols back to their pretty names at debugging time if someone really needs to work with a release binary this way. My understanding is that these shouldn't be needed with dwarf stack traces anyway though.

If we could, for example, convert about 119k of these strings to something smaller like an integer, that would take the snapshot size down by just under 8 megs using 64 bit integers (and just over 9 megs for 32 bit integers). @rmacnak-google mentioned something to me today about this not being a good idea but I can't remember why :)

/cc @a-siva @mkustermann @mraleph 
/cc @jason-simmons @jonahwilliams fyi

**Comment by mraleph** [comment] 2022-04-28 04:52
Duplicate of #38759

**Closed by mraleph** 2022-04-28 04:52 UTC
Labels: area-vm, type-performance, customer-flutter, vm-aot-code-size, vm-aot-memory-footprint
