### ISSUE TITLE
Taking snapshot fails with `RangeError: Offset (1163457) must be a multiple of BYTES_PER_ELEMENT`

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#55475] opened 2024-04-15 21:14 UTC
Tried for macos and for android emulator. I have mac arm64.

```
[ERROR]: [PlatformDispatcher]: RangeError: Offset (1163457) must be a multiple of BYTES_PER_ELEMENT (2)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError: Offset (1163457) must be a multiple of BYTES_PER_ELEMENT (2)
#0      _offsetAlignmentCheck (dart:typed_data-patch/typed_data_patch.dart:5124:5)
#1      _ByteBuffer.asUint16List (dart:typed_data-patch/typed_data_patch.dart:1952:5)
#2      new Uint16List.sublistView (dart:typed_data:1300:24)
#3      ReadStream.readUtf16 (package:vm_service/src/_stream_helpers.dart:311:30)
#4      _getNonReferenceData (package:vm_service/src/snapshot_graph.dart:629:26)
#5      new HeapSnapshotObject._read (package:vm_service/src/snapshot_graph.dart:200:18)
#6      HeapSnapshotGraph._readObjects (package:vm_service/src/snapshot_graph.dart:462:39)
#7      new HeapSnapshotGraph.fromChunks (package:vm_service/src/snapshot_graph.dart:400:5)
#8      HeapSnapshotGraph.getSnapshot.<anonymous closure> (package:vm_service/src/snapshot_graph.dart:352:46)
<asynchronous suspension>
```

```
Flutter 3.22.0-11.0.pre.9 • channel [user-branch] • unknown source
Framework • revision 8c12ba8470 (33 minutes ago) • 2024-04-15 16:09:07 -0400
Engine • revision 07ae93c9b7
Tools • Dart 3.5.0 (build 3.5.0-56.0.dev) • DevTools 2.35.0-dev.8
```

**Comment by polina-c** [comment] 2024-04-15 21:22
Repro:

1. Build DevTools: https://github.com/flutter/devtools/blob/master/BETA_TESTING.md
2. Connect to counter app on macos or android emulator
3. Open Memory > Diff
4. Click recording:
<img width="206" alt="Screenshot 2024-04-15 at 2 21 34 PM" src="https://github.com/dart-lang/sdk/assets/12115586/83bbb3c4-7f34-4aec-88e0-b3bed5268386">
5. Find error printed on DevTools console

**Comment by polina-c** [comment] 2024-04-15 21:24
@bkonyi @derekxu16 @a-siva

**Comment by bkonyi** [comment] 2024-04-16 14:46
I'm not able to reproduce on Flutter master and the latest DevTools:

```
Flutter 3.22.0-11.0.pre.18 • channel main • git@github.com:flutter/flutter.git
Framework • revision cb719db814 (65 minutes ago) • 2024-04-16 09:40:19 -0400
Engine • revision 71ab8854f1
Tools • Dart 3.5.0 (build 3.5.0-65.0.dev) • DevTools 2.35.0-dev.8
```

I have a x64 Mac, so maybe that has something to do with it. @derekxu16, can you give this a try?

**Comment by lrhn** [comment] 2024-04-16 14:55
The error should not depend on the CPU alignment, it's an intrinsic requirement of the typed-data classes that they start at the correct place in a buffer.
I guess OS differences could affect the incoming data being parsed.

Although the current version of `readUtf16` does seem to check for alignment, it relies on the original incombine buffer to be a whole buffer.
The line
```dart
    if (_currentChunkHasBytes(len * 2) && _byteIndex & 1 == 0) {
```
should be
```dart
    if (_currentChunkHasBytes(len * 2) && (_currentChunk.offsetInBytes + _byteIndex) & 1 == 0) {
```

@osa1 Seems to be your code from https://dart-review.googlesource.com/c/sdk/+/340182

**Comment by polina-c** [comment] 2024-04-16 15:18
Thank you!

If it helps, this is exact project for repro: https://github.com/polina-c/spikes/tree/master/counter

It is modified counter. On each click it aggressively allocates memory into array.
But I repro the issue without any clicks, for just started application.

**Comment by osa1** [comment] 2024-04-16 15:38
Thanks for the ping. @lrhn found the bug, we should just make the change @lrhn shows. Let me know if you want me to do it.

**Comment by derekxu16** [comment] 2024-04-16 15:41
I was trying to reproduce the problem first to check if the patch fixes the issue, but I'm also unable to reproduce it. I'm making a CL with the patch now.

**Comment by polina-c** [comment] 2024-04-16 15:43
Thank you @derekxu16!
And then we want to make sure the issue does not squeeze to flutter stable...

**Comment by a-siva** [comment] 2024-04-16 17:05
> Thank you @derekxu16! And then we want to make sure the issue does not squeeze to flutter stable...

Looks like the change made it to the beta branch and so will end up in stable, @derekxu16 we will probably need a cherry pick of your change

**Comment by polina-c** [comment] 2024-04-16 19:07
The failing snapshot, after `fromChanks` with applied patch and then saved with `toChanks`.
We can try to use it to test cover the fix, if the issue reproduces with it: 
[main-1_2024-04-16_12:03:07.927.data.zip](https://github.com/dart-lang/sdk/files/15001532/main-1_2024-04-16_12.03.07.927.data.zip)

**Comment by polina-c** [comment] 2024-04-16 19:14
14.2.1 of vm_service contains the fix
Preparing upgrade of DevTools

@kenzieschmoll , do we need to cherry pick the upgrade to make sure DevTools with the issue does not squeeze into Flutter master?
Or 14.2.1  will be auto picked up by DevTools, because vm_service is cherry picking the change?

**Comment by polina-c** [comment] 2024-04-16 19:25
Upgrade for DevTools: https://github.com/flutter/devtools/pull/7597

**Comment by kenzieschmoll** [comment] 2024-04-16 19:39
What version of Flutter did this first start on? If this breakage is on the beta channel, then we need to cherry-pick the fix to beta. If the breakage is only on master, then no need for a cherry pick.

**Comment by polina-c** [comment] 2024-04-16 19:44
It is introduced by this PR: https://dart-review.googlesource.com/c/sdk/+/340182
@derekxu16 is cherry picking Flutter

**Comment by kenzieschmoll** [comment] 2024-04-16 21:07
If DevTools fails on beta even with @derekxu16's cherry pick, then yes we will need a DevTools [cherry pick](https://github.com/flutter/devtools/blob/master/tool/RELEASE_INSTRUCTIONS.md#cherry-pick-releases) (2.34.3) into the Dart SDK as well, and then into Flutter. @polina-c or @derekxu16 can you drive this?

**Comment by derekxu16** [comment] 2024-04-16 21:23
The fix is `package:vm_service` and not in the Dart SDK, and Flutter has an exact pin of `package:vm_service`, so cherry-picking the fix into Flutter beta would mean updating the version of `package:vm_service` pinned on the beta branch. Has something like this ever been done, @christopherfujino?

**Comment by derekxu16** [comment] 2024-04-16 21:31
Oh, I see https://github.com/flutter/flutter/issues/125231. So when `package:vm_service 14.2.1` rolls into Flutter, the commit performing the roll can just be cherry-picked? I was worried about some weirdness with the pubspec checksum.

**Comment by christopherfujino** [comment] 2024-04-16 23:30
> Oh, I see [flutter/flutter#125231](https://github.com/flutter/flutter/issues/125231). So when `package:vm_service 14.2.1` rolls into Flutter, the commit performing the roll can just be cherry-picked? I was worried about some weirdness with the pubspec checksum.

So we are able to do this, but it is not safe to just roll vm_service forward to pick up the change. What we generally do here is create a special pub patch release with only the bug fix, e.g. vm_service 14.2.0+1 (unless the only diff between 14.2.0 and 14.2.1 is your bugfix, in which case we got lucky).

The mechanics for updating only a single package on a release branch is documented [here](https://github.com/flutter/flutter/wiki/Updating-dependencies-in-Flutter#to-update-a-single-dependency-for-cherrypicks).

**Comment by bkonyi** [comment] 2024-04-17 15:15
> unless the only diff between 14.2.0 and 14.2.1 is your bugfix, in which case we got lucky.

We got lucky :-) 14.2.1 was created specifically for this bug fix.

**Comment by derekxu16** [comment] 2024-04-17 15:18
^ I have just filed a cherry-pick request.

**Comment by kenzieschmoll** [comment] 2024-04-18 14:53
@derekxu16 have you verified that DevTools is WAI with your flutter cherry pick included? The change @polina-c made to bump the DevTools dependency on vm_service to 14.2.1 is not included in the Dart or Flutter SDKs, and won't be in the build your cherry-pick makes it into.

**Comment by polina-c** [comment] 2024-04-18 15:22
What should happen first: cherry pick of fixed DevTools into flutter or cherry pick of fixed vm_service into Flutter? Or it does not matter?

**Comment by polina-c** [comment] 2024-04-18 16:02
> What should happen first: cherry pick of fixed DevTools into Dart SDK or cherry pick of fixed vm_service into Dart SDK? Or it does not matter?

We want to build DevTools with already cherry picked SDK. So we need cherry pick of vm_service to land first.
Please, correct me if I am wrong.

**Comment by derekxu16** [comment] 2024-04-18 16:08
> We want to build fix for DevTools with already cherry picked SDK. So we need cherry pick of vm_service to land first. Please, correct me if I am wrong.

DevTools needs to be built against a version of the Flutter SDK that accepts `package:vm_service 14.2.1`; the version of the Dart SDK that it's built against does not matter. I'm not sure which branch you want to use to build the new version of DevTools. FWIW, this PR has landed: https://github.com/flutter/flutter/pull/146896.

**Comment by polina-c** [comment] 2024-04-18 16:59
started putting together DevTools cherry pick.

**Comment by christopherfujino** [comment] 2024-04-18 17:15
> Since there's a prebuilt copy of DevTools in the Dart SDK, you're right that a new build of DevTools built with `package:vm_service 14.2.1` needs to be cherry-picked into the Dart SDK.

I'm a little confused as to what needed to match here, and it sounds like we're now doing the right thing. However, once we get all the right CPs in, this feels like a tricky situation we could very well mess up next time.

Is the issue that flutter_tools and dev_tools need to have matching vm_service versions? Or just we want to ensure that none of the tools we're shipping in the Flutter SDK have the affected (14.2.0) vm_service version? If it's the former, we could add a flutter/flutter test to verify this. If it's the latter, I've been playing around with a tool to make inspecting the transitive deps of a Flutter SDK more easily inspectable, that would probably help in situations like this.

**Comment by polina-c** [comment] 2024-04-18 17:36
I think we just want every tool not to have 14.2.0.

**Comment by derekxu16** [comment] 2024-04-18 17:36
The prebuilt version of DevTools in the current Dart SDK beta candidate was built with `package:vm_service 14.2.0`. My understanding is that `package:vm_service 14.2.1` had to be rolled into the Flutter SDK beta branch because a new build of DevTools will be built using the Flutter SDK beta branch, and this build will be cherry-picked into the Dart SDK beta branch.

**Comment by polina-c** [comment] 2024-04-18 17:52
> > Since there's a prebuilt copy of DevTools in the Dart SDK, you're right that a new build of DevTools built with `package:vm_service 14.2.1` needs to be cherry-picked into the Dart SDK.
> 
> I'm a little confused as to what needed to match here, and it sounds like we're now doing the right thing. However, once we get all the right CPs in, this feels like a tricky situation we could very well mess up next time.
> 
> Is the issue that flutter_tools and dev_tools need to have matching vm_service versions? Or just we want to ensure that none of the tools we're shipping in the Flutter SDK have the affected (14.2.0) vm_service version? If it's the former, we could add a flutter/flutter test to verify this. If it's the latter, I've been playing around with a tool to make inspecting the transitive deps of a Flutter SDK more easily inspectable, that would probably help in situations like this.

Easy way to understand what is built with what would be very helpful!

**Comment by kenzieschmoll** [comment] 2024-04-19 02:14
> The prebuilt version of DevTools in the current Dart SDK beta candidate was built with package:vm_service 14.2.0. My understanding is that package:vm_service 14.2.1 had to be rolled into the Flutter SDK beta branch because a new build of DevTools will be built using the Flutter SDK beta branch, and this build will be cherry-picked into the Dart SDK beta branch.

Has anyone manually reproduced the failure with DevTools from a Flutter beta branch with Derek's fix included (@polina-c or @derekxu16)? If the bug was caused because of the VM service logic that is running on the device, then it is possible that cherry-picking Derek's change into Flutter is enough. Based on https://github.com/flutter/devtools/pull/7597/, it doesn't look like there are any logic changes in DevTools that came with the vm_service version bump, which would make me think that it's possible no cherry-pick is needed for DevTools. 

Someone should confirm manually that the issue still exists before we move forward with a DevTools cherry-pick.

**Comment by polina-c** [comment] 2024-04-19 02:21
Are you saying DevTools will pickup 14.2.1 from sdk, even if it was built with 14.2.0?

The issue is flaky, so even if it does not repro, it does not mean it is fixed.

How does it sound?

**Comment by kenzieschmoll** [comment] 2024-04-19 02:25
I'm saying that if the crash happened because of the VM service running on the device, then it is possible that Derek's fix may be compatible with the existing DevTools on beta, and there would be no need to rebuild DevTools with 14.2.1. If 14.2.1 has implications that would change DevTools logic, then we'd need to CP DevTools too, but looking at your DevTools PR, it was just a patch version changes with no other changes. Which makes me think that the existing DevTools on beta may be compatible with the vm_service changes that Derek CP'ed into Flutter.

**Comment by derekxu16** [comment] 2024-04-19 13:41
The error did not happen because of the VM Service running on the device, it happened when DevTools called `getHeapSnapshotGraph` [here](https://github.com/flutter/devtools/blob/37cfc80e9ade014b02e5b800f725ef638a6cbc3d/packages/devtools_app/lib/src/screens/memory/shared/primitives/memory_utils.dart#L13).

**Comment by polina-c** [comment] 2024-04-19 17:53
Cherry pick is waiting for Kenzie to decide if we are doing it: https://dart-review.googlesource.com/c/sdk/+/363642

**Comment by kenzieschmoll** [comment] 2024-04-22 16:23
Based on the two previous comments [[1](https://github.com/dart-lang/sdk/issues/55475#issuecomment-2066617694)] and [[2](https://github.com/dart-lang/sdk/issues/55475#issuecomment-2067025656)], it sounds like we do need the cherry pick, yes.

**Comment by polina-c** [comment] 2024-04-24 21:47
Cherry pick is merged. Thanks all for help and catches.

It was a significant and risky effort to sync the fix between 4 products (vm_service, DevTools, DartSDK, Flutter).

IMHO it would be great to prioritize test coverage for [the fix](https://dart-review.googlesource.com/c/sdk/+/363120), to avoid repeating this.
See https://github.com/dart-lang/sdk/issues/55475#issuecomment-2059755028

@bkonyi, @derekxu16, @osa1, @a-siva

**Comment by a-siva** [comment] 2024-04-24 21:52
> IMHO it would be great to prioritize test coverage for [the fix](https://dart-review.googlesource.com/c/sdk/+/363120), to avoid repeating this. See [#55475 (comment)](https://github.com/dart-lang/sdk/issues/55475#issuecomment-2059755028)
> 

I believe Derek has added a test for this at [
https://dart-review.googlesource.com/c/sdk/+/363441

**Closed** 2024-04-24 22:04 UTC
Labels: area-vm, P0, pkg-vm-service, cherry-pick-candidate, triaged
