### ISSUE TITLE
co19/LayoutTests/fast/dom/shadow/shadowroot-keyframes_t01 flakily failing on Dartium

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#29018] opened 2017-03-09 23:47 UTC
See [this log](https://build.chromium.org/p/client.dart/builders/dartium-win-ia32-inc-be/builds/2238/steps/annotated%20steps/logs/stdio) for an example. The failure is:

```
FAILED: none-dartium-checked release_x64 co19/LayoutTests/fast/dom/shadow/shadowroot-keyframes_t01
Expected: Pass 
Actual: RuntimeError
CommandOutput[dartium]:

stdout:
events:
  [
        {
              type: debug
              value: test_controller.js started
              timestamp: 0
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = true, isStatusUpdate = true, isDone = false)
              timestamp: 0.001
        },
        {
              type: print
              value: dart-calling-main
              timestamp: 0.115
        },
        {
              type: print
              value: unittest-suite-wait-for-done
              timestamp: 0.327
        },
        {
              type: print
              value: dart-main-done
              timestamp: 0.334
        },
        {
              type: message_received
              value: dart-calling-main
              timestamp: 0.335
        },
        {
              type: message_received
              value: unittest-suite-wait-for-done
              timestamp: 0.336
        },
        {
              type: message_received
              value: dart-main-done
              timestamp: 0.336
        },
        {
              type: window_onerror
              value: window.onerror called: 
                    
                    http://127.0.0.1:49844/root_build/generated_tests/none-dartium-checked/co19_domshadow_shadowroot-keyframes_t01/test.html?crossOriginPort=49846:1:
                    Uncaught Unhandled exception:
                    Expect.equals(expected: <rgb(0, 0, 255)>, actual: <rgb(42, 0, 213)>) fails.
                    #0      _fail (http://127.0.0.1:49844/root_dart/tests/co19/src/Utils/expect.dart:17:5)
                    #1      Expect.equals (http://127.0.0.1:49844/root_dart/tests/co19/src/Utils/expect_common.dart:27:5)
                    #2      shouldBe (http://127.0.0.1:49844/root_dart/tests/co19/src/LayoutTests/testcommon.dart:82:54)
                    #3      main.<anonymous closure> (http://127.0.0.1:49844/root_dart/tests/co19/src/LayoutTests/fast/dom/shadow/shadowroot-keyframes_t01.dart:53:5)
                    #4      Future.Future.delayed.<anonymous closure> (dart:async/future.dart:268)
                    #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
                    #6      _Timer._Timer.<anonymous closure> (dart:html:49221)
                    
                    
              timestamp: 1.482
        },
        {
              type: debug
              value: Sending events to driver page (isFirstMessage = false, isStatusUpdate = false, isDone = true)
              timestamp: 1.482
        },
        {
              type: dom
              value: <head>
                      <meta http-equiv="X-UA-Compatible" content="IE=edge">
                      <meta name="dart.unittest" content="full-stack-traces">
                      <title> Test /E:/b/build/slave/dartium-win-ia32-inc-be/build/src/dart/tests/co19/src/LayoutTests/fast/dom/shadow/shadowroot-keyframes_t01.dart </title>
                      <style>
                         .unittest-table { font-family:monospace; border:1px; }
                         .unittest-pass { background: #6b3;}
                         .unittest-fail { background: #d55;}
                         .unittest-error { background: #a11;}
                      </style>
                    <style>
                        @-webkit-keyframes anim {
                            from {
                                background-color: red;
                            }
                            to {
                                background-color: green;
                            }
                        }
                        </style></head>
                    <body>    <div id="d1"></div>
                        <div id="d2"></div>
                        <div id="result"></div>
                        </body>
              timestamp: 1.482
        },
  ]
  



stderr:


BrowserOutput while running the test (* EXPERIMENTAL *):
BrowserOutput.stdout:
  
BrowserOutput.stderr:
  



To retest, run:  E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\tools\sdks\win\dart-sdk\bin\dart.exe E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\tools\testing\dart\http_server.dart -p 49844 -c 49846 --build-directory=E:\b\build\slave\dartium-win-ia32-inc-be\build\src\out\Release\ --runtime=dartium --packages=E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\.packages

Command[dartium]: E:\b\build\slave\dartium-win-ia32-inc-be\build\src\dart\tools\sdks\win\dart-sdk\bin\dart.exe tools/testing/dart/launch_browser.dart dartium http://127.0.0.1:49844/root_build/generated_tests/none-dartium-checked/co19_domshadow_shadowroot-keyframes_t01/test.html?crossOriginPort=49846
Took 0:00:01.501917

Short reproduction command (experimental):
    python tools/test.py -mrelease -rdartium --checked -t60 co19/LayoutTests/fast/dom/shadow/shadowroot-keyframes_t01
```

**Comment by mraleph** [comment] 2017-11-16 12:08
This issue has been last updated 251 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by alan-knight** [comment] 2017-11-16 17:56
I think flakes on Dartium count as non-meaningful now. Closing as obsolete.

**Closed by alan-knight** 2017-11-16 17:56 UTC
Labels: area-dartium, gardening
