### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by ArtRog** [dart-lang/sdk#38760] opened 2019-10-08 10:31 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Captured exception
Unsupported operation: unsupported initializer: BinaryExpressionImpl :: super() * ()
#0      AstBuilder.buildInitializer (package:analyzer/src/fasta/ast_builder.dart:422:5)
#1      AstBuilder.endInitializers (package:analyzer/src/fasta/ast_builder.dart:1369:44)
#2      Parser.parseInitializers (package:front_end/src/fasta/parser/parser.dart:2586:14)
#3      Parser.parseInitializersOpt (package:front_end/src/fasta/parser/parser.dart:2523:14)
#4      Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3250:13)
#5      Parser.parseClassOrMixinMemberImpl (package:front_end/src/fasta/parser/parser.dart:3130:15)
#6      Parser.parseClassOrMixinBody (package:front_end/src/fasta/parser/parser.dart:2906:15)
#7      Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1797:13)
#8      Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1757:14)
#9      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:572:14)
#10     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#11     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#12     ParserAdapter.parseCompilationUnit2 (pa

**Comment by parlough** [comment] 2020-05-19 23:01
Duplicate of https://github.com/dart-lang/sdk/issues/37693

Should be fixed by https://github.com/dart-lang/sdk/commit/bb076a20c5760afdbfd29369d9e59656c78b2e78

Update to any SDK stable 2.5 or greater.

**Closed** 2021-02-22 17:14 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
