### ISSUE TITLE
It should be ok to invoke one visibleForTesting method from another one.

### ISSUE THREAD

**Issue by polina-c** [dart-lang/sdk#51914] opened 2023-03-31 17:35 UTC
This lint creates false positives: https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=invalid_use_of_visible_for_testing_member#invalid_use_of_visible_for_testing_member

<img width="695" alt="Screenshot 2023-03-31 at 10 33 09 AM" src="https://user-images.githubusercontent.com/12115586/229190618-1c041267-6aab-440d-be67-f28163a4ff86.png">

**Comment by kevmoo** [comment] 2023-05-02 23:26
Just hit this as well. Would be VERY nice!

**Comment by kevmoo** [comment] 2023-05-02 23:29
Duplicate of #41998

**Closed by kevmoo** 2023-05-02 23:29 UTC
Labels: area-analyzer, P3, analyzer-hint, analyzer-pkg-meta
