### ISSUE TITLE
UNNECESSARY_IMPORT reported even though the export is deprecated

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#52306] opened 2023-05-08 15:17 UTC
```dart
  test_deprecatedExport() async {
    newFile('$testPackageLibPath/a.dart', '''
class A {}
''');

    newFile('$testPackageLibPath/b.dart', '''
library;
@deprecated
export 'a.dart';
class B {}
''');

    await assertNoErrorsInCode('''
import 'a.dart';
import 'b.dart';
void f(A a, B b) {}
''');
  }
```

**Comment by scheglov** [comment] 2023-05-08 18:41
https://dart-review.googlesource.com/c/sdk/+/302080

**Comment by srawlins** [comment] 2023-05-08 19:25
I think duplicate of https://github.com/dart-lang/sdk/issues/51890

**Closed** 2023-05-08 19:51 UTC
Labels: area-analyzer, analyzer-hint, P2
