### ISSUE TITLE
ICData::Clone seg fault on arm

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#34999] opened 2018-10-31 12:06 UTC
```dart
FAILED: dartk-vm release_arm64 corelib_2/queue_test
Expected: Pass
Actual: Crash

--- Command "vm" (took 11.000250s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/dart --sync-async --ignore-unrecognized-flags --packages=/b/build/slave/target-arm64-vm-linux-release-be/build/sdk/.packages /b/build/slave/target-arm64-vm-linux-release-be/build/sdk/tests/corelib_2/queue_test.dart

exit code:
-6

stderr:
===== CRASH =====
version=2.1.0-edge.690c3be02e2d1347e0816ad97d0be695898ea31a (Wed Oct 31 09:01:49 2018 +0000) on "linux_arm64"
si_signo=Segmentation fault(11), si_code=1, si_addr=0xffffabec0000
Dumping native stack trace for thread bb7
  [0x0000aaaabf834cc4] dart::ICData::Clone(dart::ICData const&)
  [0x0000aaaabf834cc4] dart::ICData::Clone(dart::ICData const&)
  [0x0000aaaabf834694] dart::Function::RestoreICDataMap(dart::ZoneGrowableArray<dart::ICData const*>*, bool) const
  [0x0000aaaabfa53da8] dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  [0x0000aaaabfa54c64] Unknown symbol
  [0x0000aaaabfa55c84] dart::Compiler::CompileOptimizedFunction(dart::Thread*, dart::Function const&, long)
  [0x0000aaaabfa579cc] dart::BackgroundCompiler::Run()
  [0x0000aaaabf93c02c] dart::ThreadPool::Worker::Loop()
  [0x0000aaaabf93bee8] dart::ThreadPool::Worker::Main(unsigned long)
  [0x0000aaaabf89a9bc] Unknown symbol
  [0x0000ffffaca02fc4] Unknown symbol
-- End of DumpStackTrace

--- Re-run this test:
python tools/test.py -m release -c dartk -a arm64 corelib_2/queue_test
```

Might be related to https://github.com/dart-lang/sdk/issues/34997, it failed on the same build bot, both on ICData.

**Comment by mraleph** [comment] 2018-10-31 16:37
We have seen a failure like this before with @mkustermann and we arrived to conclusion that this is caused by the weak memory model of ARM. I have written the following test to verify this: 

```cpp
class ICDataTestTask : public ThreadPool::Task {
 public:
  static const intptr_t kTaskCount;

  ICDataTestTask(Isolate* isolate, const Array& ic_datas)
      : isolate_(isolate), ic_datas_(ic_datas), len_(ic_datas.Length()) {}

  virtual void Run() {
    Thread::EnterIsolateAsHelper(isolate_, Thread::kUnknownTask);

    Thread* thread = Thread::Current();

    {
      StackZone stack_zone(thread);
      HANDLESCOPE(thread);

      ICData& ic_data = ICData::Handle();
      Array& arr = Array::Handle();
      while (true) {
        for (intptr_t cnt = 0; cnt < 0x100; cnt++) {
          for (intptr_t i = 0; i < len_; i++) {
            ic_data ^= ic_datas_.At(i);
            arr = ic_data.ic_data();
            intptr_t num_checks = arr.Length() / 3;
            if (num_checks < 0 || num_checks > 5) {
              OS::PrintErr("Failure: %" Pd " checks!\n", num_checks);
              abort();
            }
          }
        }

        TransitionVMToBlocked blocked(thread);
      }
    }

    Thread::ExitIsolateAsHelper();
  }

 private:
  Isolate* isolate_;
  const Array& ic_datas_;
  const intptr_t len_;
};

const intptr_t ICDataTestTask::kTaskCount = 1;

ISOLATE_UNIT_TEST_CASE(ICDataTest) {
  Isolate* isolate = thread->isolate();
  USE(isolate);
  Monitor monitor;

  const intptr_t kNumICData = 0x10;

  const Array& ic_datas = Array::Handle(Array::New(kNumICData));
  ICData& ic_data = ICData::Handle();
  Function& owner = Function::Handle();
  String& name = String::Handle(String::New("foo"));
  const Array& args_desc = Array::Handle(ArgumentsDescriptor::New(0, 0, Object::empty_array()));
  for (intptr_t i = 0; i < kNumICData; i++) {
    ic_data = ICData::New(owner, name, args_desc, /*deopt_id=*/0, /*num_args_tested=*/1, ICData::kInstance, Object::null_abstract_type());
    ic_datas.SetAt(i, ic_data);
  }

  for (int i = 0; i < ICDataTestTask::kTaskCount; i++) {
    Dart::thread_pool()->Run(new ICDataTestTask(
        isolate, ic_datas));
  }

  intptr_t cnt = 0;
  intptr_t cnt2 = 0;
  while (true) {
    for (intptr_t i = 0; i < kNumICData; i++) {
      ic_data ^= ic_datas.At(i);
      if (ic_data.NumberOfChecks() < 4) {
        ic_data.AddReceiverCheck(kInstanceCid + ic_data.NumberOfChecks(), owner, 1);
      } else {
        ic_data = ICData::New(owner, name, args_desc, /*deopt_id=*/0, /*num_args_tested=*/1, ICData::kInstance, Object::null_abstract_type());
        ic_datas.SetAt(i, ic_data);
      }
    }
    cnt++;
    if (cnt > 0x10000) {
      OS::PrintErr("%" Pd ": Did %" Pd " iterations without an issue\n", cnt2++, cnt);
      cnt = 0;
    }
  }
}
```

It's a very simple test that simulates relationship between mutator thread and background compiler:

* mutator is creating and populating `ICData` objects;
* background worker reads `Length` of the `ic_data` objects that mutator mutates.

On Intel this test runs without a failure, but on ARM64 bot it crashes immediately with 

```console
$ ./run_vm_tests ICDataTest
Running test: ICDataTest
Failure: 2396591806393 checks!
```

which matches the sort of a crash we saw in core dumps.

This is caused because methods of ICData assume that memory model of the underlying CPU is strong. The code looks like this:

```cpp
void ICData::AddReceiverCheck(intptr_t receiver_class_id,
                              const Function& target,
                              intptr_t count,
                              StaticTypeExactnessState exactness) const {
  // ...
  // Multithreaded access to ICData requires setting of array to be the last
  // operation.
  set_ic_data_array(data);
}
```

Unfortunately there are no compiler and no hardware barriers in this function - so both compiler *and* CPU are free to reorder stores and another thread might observe the store of `ic_data_array` before observing the store that initialized its length.

I made a change to the runtime to turn `ICData::set_ic_data_array` into atomic release store and `ICData::ic_data` into acquire load:
 
```diff
diff --git a/runtime/vm/object.cc b/runtime/vm/object.cc
index 53e0e4a2ea..897b68491f 100644
--- a/runtime/vm/object.cc
+++ b/runtime/vm/object.cc
@@ -13377,7 +13377,7 @@ void ICData::set_deopt_id(intptr_t value) const {
 
 void ICData::set_ic_data_array(const Array& value) const {
   ASSERT(!value.IsNull());
-  StorePointer(&raw_ptr()->ic_data_, value.raw());
+  StorePointer<RawArray*, true>(&raw_ptr()->ic_data_, value.raw());
 }
 
 #if defined(TAG_IC_DATA)
diff --git a/runtime/vm/object.h b/runtime/vm/object.h
index 85d769df74..2caa8075cf 100644
--- a/runtime/vm/object.h
+++ b/runtime/vm/object.h
@@ -552,9 +552,9 @@ class Object {
   // methods below or their counterparts in RawObject, to ensure that the
   // write barrier is correctly applied.
 
-  template <typename type>
+  template <typename type, bool atomic = false>
   void StorePointer(type const* addr, type value) const {
-    raw()->StorePointer(addr, value);
+    raw()->StorePointer<type, atomic>(addr, value);
   }
 
   // Store a range of pointers [from, from + count) into [to, to + count).
@@ -2099,12 +2099,13 @@ class ICData : public Object {
 #endif
 
   bool is_static_call() const;
+  RawArray* ic_data() const {
+    return __atomic_load_n(&raw_ptr()->ic_data_, __ATOMIC_ACQUIRE);
+  }
 
  private:
   static RawICData* New();
 
-  RawArray* ic_data() const { return raw_ptr()->ic_data_; }
-
   void set_owner(const Function& value) const;
   void set_target_name(const String& value) const;
   void set_arguments_descriptor(const Array& value) const;
diff --git a/runtime/vm/raw_object.h b/runtime/vm/raw_object.h
index 80c94ef49b..d4f55b295e 100644
--- a/runtime/vm/raw_object.h
+++ b/runtime/vm/raw_object.h
@@ -685,9 +685,9 @@ class RawObject {
   // methods below or their counterparts in Object, to ensure that the
   // write barrier is correctly applied.
 
-  template <typename type>
+  template <typename type, bool atomic = false>
   void StorePointer(type const* addr, type value) {
-    *const_cast<type*>(addr) = value;
+    __atomic_store_n(const_cast<type*>(addr), value, atomic ? __ATOMIC_RELEASE : __ATOMIC_RELAXED);
     if (value->IsHeapObject()) {
       CheckHeapPointerStore(value, Thread::Current());
     }
```

With this change my test case does not crash on ARM64 machine:

```console
$ ./run_vm_tests ICDataTest
Running test: ICDataTest
0: Did 65537 iterations without an issue
1: Did 65537 iterations without an issue
2: Did 65537 iterations without an issue
3: Did 65537 iterations without an issue
4: Did 65537 iterations without an issue
5: Did 65537 iterations without an issue
```

/cc @mkustermann @rmacnak-google @a-siva @alexmarkov

**Comment by mraleph** [comment] 2018-10-31 17:13
Assigning to @dcharkes to clean and land the patch.

**Comment by dcharkes** [comment] 2018-11-12 14:38
The test failed once (out of ~200 builds since it landed), so there is still some data race.

```dart
FAILED: dartk-vm release_arm64 vm/cc/ICDataTest
Expected: Pass
Actual: Crash

--- Command "run_vm_unittest" (took 05.000022s):
DART_CONFIGURATION=ReleaseXARM64 out/ReleaseXARM64/run_vm_tests --dfe=/b/build/slave/target-arm64-vm-linux-release-be/build/sdk/out/ReleaseXARM64/gen/kernel-service.dart.snapshot --ignore-unrecognized-flags ICDataTest

exit code:
-6

stdout:
Running test: ICDataTest

stderr:
Failure: 2396591806393 checks!

--- Re-run this test:
python tools/test.py -m release -c dartk -a arm64 vm/cc/ICDataTest
```

**Comment by mkustermann** [comment] 2018-12-13 09:51
This happened again in [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8927285398485395392/+/steps/vm_tests_shard_1/0/stdout) on arm64.

Dumps are available [here](https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=1f046f041d37e7e90d8b7d2aa2aa96b4dc15ba11)

**Comment by sstrickl** [comment] 2018-12-17 10:35
[Another case](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8927117605602703952/+/steps/vm_tests_shard_1/0/stdout) of it happening this weekend. Here are the associated [dumps](https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=a6ad6cce1386d387e5cfcd79296244eedc1d1960).

**Comment by mraleph** [comment] 2018-12-18 08:31
I am going to look at the dump today.

**Closed** 2018-12-18 16:49 UTC
Labels: area-vm, gardening, p0-critical
