### ISSUE TITLE
c919/LayoutTests/fast/canvas/webgl/get-active-test_t01 fails on firefox

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#28593] opened 2017-02-01 11:09 UTC
Short reproduction command (experimental):
    python tools/test.py -mrelease -cdart2js -rff --fast-startup -t60 --use-sdk --dart2js-batch --reset-browser-configuration co19/LayoutTests/fast/canvas/webgl/get-active-test_t01

@floitschG

**Comment by floitschG** [comment] 2017-02-06 15:07
Test fails also without `--fast-startup`.

**Comment by mraleph** [comment] 2017-11-16 12:05
This issue has been last updated 279 days ago. Please consider investigating whether it is still meaningful and if not close it. If the issue is still meaningful please find a relevant owner. Thank you.

**Comment by athomas** [comment] 2020-01-15 12:19
LayoutTests have been deleted.

**Closed by athomas** 2020-01-15 12:19 UTC
Labels: area-library, area-web, closed-obsolete, gardening, library-html
