### ISSUE TITLE
dart allows assign non-constant expressions to constant variables

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#24940] opened 2015-11-16 16:23 UTC
According to specification (3-rd edition, June 2015) "16.1 Constants":
"A constant  expression is an expression whose value can never change, and that can be evaluated entirely at compile time.
A constant expression is one of the following:
. . . 
• An expression of the form e.length where e is a constant expression that evaluates to a string value."

The tests below assign non-constant expression to constant variable.
```dart
String m = "abc";
const l = m.length;

main() {
}
```
```dart
const Object o = "ab" + "cd";
const l = o.toString().length;

main() {
}
```
dart doesn't report errors during compilation, while dartanalyzer reports errors.
```dart
> dartanalyzer test1.dart 
Analyzing [test1.dart]...
[error] 'const' variables must be constant value (test1.dart, line 2, col 11)
1 error found.
> dartanalyzer test2.dart 
Analyzing [test2.dart]...
[error] 'const' variables must be constant value (test2.dart, line 2, col 11)
[error] 'const' variables must be constant value (test2.dart, line 2, col 11)
2 errors found.
```
Tested on Dart VM version: 1.13.0-dev.7.10 (Fri Nov  6 02:03:14 2015) on "linux_x64".

**Comment by iposva-google** [comment] 2015-11-16 19:17
Likely a duplicate of issue 392.

**Comment by mhausner** [comment] 2016-01-06 18:34
The VM compiler does not compile the expressions because the variables are not referenced. That is legal in Dart.

Change the code to this:

```
String m = "abc";
const l = m.length;

main() {
   print(l);
}
```

And you get:

```
dart ~/tmp/s.dart
'file:///Users/hausner/tmp/s.dart': error: line 4 pos 11: initializer is not a valid compile-time constant
const l = m.length;
          ^

```

This is working as intended.

**Closed by mhausner** 2016-01-06 18:34 UTC
Labels: area-language, area-vm
