### ISSUE TITLE
NNBD Analyzer throws unexpected compile error for the dead code with Never variable

### ISSUE THREAD

**Issue by iarkh** [dart-lang/sdk#40126] opened 2020-01-14 11:47 UTC
Dart VM version: 2.8.0-dev.0.0 (Wed Dec 11 10:31:10 2019 +0100) on "windows_x64"

This issue is similar with #40125, except that it against analyzer and #40125 is about runtime problems.

NNBD Spec reads:

It is not an error to call or tear-off a method, setter, or getter, or to read or write a field, on a receiver of static type Never. Implementations that provide feedback about dead or unreachable code are encouraged to indicate that any arguments to the invocation are unreachable.

It is not an error to apply an expression of type Never in the function position of a function call. Implementations that provide feedback about dead or unreachable code are encouraged to indicate that any arguments to the call are unreachable.

The following code sample check this assertion:

void test(var x) {
  if (x is Never) {
    x.toString();
    x.runtimeType;
    x.s = 1;
    x?.toString();
    x?.runtimeType;
    x?.s = 1;
    x?..toString();
    x?..runtimeType;
    x?..s = 1;
    x();
  }
}

main() {
  test(null);
}
According to the Spec, this example should pass, however lines 3-12 cause compile time errors with dart analyzer.

Sample output is:

$> dartanalyzer --enable-experiment=non-nullable test.dart

> Analyzing test.dart...
>   error - This expression is invalid because its target is of type Never and will never complete with a value - test.dart:3:5 - invalid_use_of_never_value
>   error - The getter 'runtimeType' isn't defined for the class 'Never'. - test.dart:4:7 - undefined_getter
>   error - The setter 's' isn't defined for the class 'Never'. - test.dart:5:7 - undefined_setter
>   error - This expression is invalid because its target is of type Never and will never complete with a value - test.dart:6:5 - invalid_use_of_never_value
>   error - The target expression can't be null, and so '?.' isn't necessary. - test.dart:6:6 - unnecessary_null_aware_call
>   error - The target expression can't be null, and so '?.' isn't necessary. - test.dart:7:6 - unnecessary_null_aware_call
>   error - The getter 'runtimeType' isn't defined for the class 'Never'. - test.dart:7:8 - undefined_getter
>   error - The target expression can't be null, and so '?.' isn't necessary. - test.dart:8:6 - unnecessary_null_aware_call
>   error - The setter 's' isn't defined for the class 'Never'. - test.dart:8:8 - undefined_setter
>   error - This expression is invalid because its target is of type Never and will never complete with a value - test.dart:9:5 - invalid_use_of_never_value
>   error - The getter 'runtimeType' isn't defined for the class 'Never'. - test.dart:10:9 - undefined_getter
>   error - The setter 's' isn't defined for the class 'Never'. - test.dart:11:9 - undefined_setter
>   error - This expression is invalid because its target is of type Never and will never complete with a value - test.dart:12:5 - invalid_use_of_never_value
> 13 errors found.

**Comment by eernstg** [comment] 2020-01-14 13:42
Thanks for reporting! However, this turns out to be a duplicate of https://github.com/dart-lang/sdk/issues/40057, so I'll close this one.

**Closed by eernstg** 2020-01-14 13:42 UTC
Labels: area-analyzer, closed-duplicate, type-bug
