### ISSUE TITLE
Type inference error in NNBD SDK

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/sdk#40492] opened 2020-02-06 19:35 UTC
I'm hitting a type inference error in when I run some tests with the NNBD SDK. Minimal example:

```
import 'dart:async';

var events = [];

foo() async {
  return 'in async function';
}

void main() {
  var asyncValueFuture = foo().then(events.add);
  Future.wait(<Future>[asyncValueFuture]).then((_) {
    print(events);
  });
}
```

This outputs "[in async function]" on the old SDK, but in the NNBD SDK it gives this error:

```
Unhandled exception:
type '(Object) => void' is not a subtype of type '(dynamic) => FutureOr<dynamic>' of 'f'
#0      main (file:///usr/local/google/home/liama/dart-sdk/junk/future_bug.dart:10:32)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:167:12)
```

I can work around it by wrapping `events.add` in a lambda: `(x) => events.add(x)`

@a-siva fixed a similar issue in the libs by specifying the arg type in the lambda, and thinks it's a type inference bug in the CFE.

**Comment by johnniwinther** [comment] 2020-02-07 07:26
Like caused by the missing normalization as with https://github.com/dart-lang/sdk/issues/40454

**Comment by johnniwinther** [comment] 2020-02-17 18:44
This seems to have been fixed by https://dart-review.googlesource.com/c/sdk/+/134842

**Closed by johnniwinther** 2020-02-17 18:44 UTC
Labels: NNBD, area-front-end, vm-nnbd-unfork-sdk
