### ISSUE TITLE
Instantiate a Generic Parameter

### ISSUE THREAD

**Issue by jrote1** [dart-lang/sdk#24343] opened 2015-09-14 10:19 UTC
For example

    class GenericClass<T>
    {
         T getInstance()
         {
               //This does not work
               return new T();
         }
    }

You should be able to instantiate a generic, maybe extra syntax should be added to generics for example. 

    class GenericClass<T with new()>

This would mean the generic type should have an empty constructor.

**Comment by floitschG** [comment] 2015-09-14 10:47
Duplicate of issue 3633.

**Closed by floitschG** 2015-09-14 10:47 UTC
