### ISSUE TITLE
Generics in a method can't recognize proper return type

### ISSUE THREAD

**Issue by eximius313** [dart-lang/sdk#53340] opened 2023-08-24 17:39 UTC
```dart
enum Bar {
  x
}
class Foo {
    E doSomething<E extends Enum>() {
      return Bar.x;
    }
}
```

This code doesn't compile. 
It returns error `A value of type 'Bar' can't be returned from the method 'doSomething' because it has a return type of 'E'.`, while clearly `Bar` *is* Enum

----
In your issue, please include:
* Dart version and tooling diagnostic info (`dart info`) -> `- Dart 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "windows_x64"`
* Whether you are using Windows, macOS, or Linux (if applicable) -> Windows 10
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable) -> N/A

**Comment by eximius313** [comment] 2023-08-24 22:14
I'm not sure if this is the same issue, but this code:
```dart
E findEnum<E extends Enum>(
  final List<E> values,
  final String enumStr,
) =>
    values.asNameMap()[enumStr]!;

enum Bar<E extends Enum> {
  foo
}

class Foo {
  Bar<E> doSomething<E extends Enum>() {
    return findEnum(Bar.values, 'foo'); //this does not compile
    //return findEnum(Bar.values as List<Bar<E>>, 'foo'); //this works
  }
}
```
returns error: `The argument type 'List<Bar<Enum>>' can't be assigned to the parameter type 'List<Bar<E>>'.dart[argument_type_not_assignable]`

**Comment by eernstg** [comment] 2023-08-25 07:39
The example in the original posting is working as intended. Consider this variant:

```dart
enum Bar { x }
enum Baz { x }

class Foo {
  E doSomething<E extends Enum>() {
    return Bar.x;
  }
}

void main() {
  Baz value = Foo().doSomething<Baz>();
}
```

If it had _not_ been an error for `doSomething` to return an object of type `Bar` when the return type is `E extends Enum` then we would be able to obtain a reference of type `Baz` to the object `Bar.x`. That would be a soundness violation. This is the basic reason why we can't have a type rule that allows this code.

At the level of concrete type rules, we can't prove that `Bar` is a subtype of `E`. To see why we can't prove that, just note that the value of `E` could be `Baz`, and we don't have a subtype relationship from `Baz` to `Bar`.

**Comment by eernstg** [comment] 2023-08-25 07:55
For the example [here](https://github.com/dart-lang/sdk/issues/53340#issuecomment-1692484114), it is confusing that `Bar` has a type argument `E` (it is never used). Anyway, you can have an unused type variable if you wish.

However, consider this variant of the example:

```dart
E findEnum<E extends Enum>(
  final List<E> values,
  final String enumStr,
) =>
    values.asNameMap()[enumStr]!;

enum Bar<E extends Enum> { foo }

class Foo {
  Bar<E> doSomething<E extends Enum>() {
    return findEnum(Bar.values as List<Bar<E>>, 'foo'); // Throws.
  }
}

void main() {
  var bar = Foo().doSomething<Never>();
}
```

We invoke `doSomething` with the type argument `Never` (we just need to satisfy `E extends Enum`, and any `enum` type will do, and so will `Never`, so we can call it like that). Then, at the type cast `Bar.values as List<Bar<E>>` in `doSomething`, we encounter a run-time error.

This shows that the type cast is necessary, we couldn't have a set of type rules where this would be allowed without a cast.

It follows that the version you're showing (where the type cast has been removed) _must_ be a compile-time error.

This is all working as intended, so I'll close the issue.

**Closed by eernstg** 2023-08-25 07:55 UTC
