### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by liranAtli** [dart-lang/sdk#35977] opened 2019-02-18 20:09 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-183.5429.30`
- `2.1.0-dev.9.4`
- `IU-183.5429.30, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: E:\Hopayacht\byo-application\lib\widgets\range\range_widget.dart
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core/runtime/libarray.dart:137:52)
#1      _ClassVerifier._checkForMismatchedAccessorTypes (package:analyzer/src/error/inheritance_override.dart:357:45)
#2      _ClassVerifier.verify (package:analyzer/src/error/inheritance_override.dart:173:5)
#3      InheritanceOverrideVerifier.verifyUnit (package:analyzer/src/error/inheritance_override.dart:44:11)
#4      LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:332:33)
#5      LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#7      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:15)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:36)
#10     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#11     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#12     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#13     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#14     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#15     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#16     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1029:23)
<asynchronous suspension>
#17     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#18     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#19     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#20     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#21     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#22     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#28     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#29     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#30     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#31     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#32     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file://C:\Users\i5-8600k\AppData\Local\Temp\report1.txt.

**Comment by stereotype441** [comment] 2019-02-20 16:18
Duplicate of #35223

**Closed by stereotype441** 2019-02-20 16:18 UTC
Labels: area-analyzer
