### ISSUE TITLE
co19/Language/Classes/Setters/name_t03 times out on vm-precomp-win-simarm64-2-4-be

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#31227] opened 2017-10-26 09:16 UTC
On `vm-precomp-win-simarm64-2-4-be` some timeouts have occurred that seem to have nothing to do with the test (it's a few lines of code doing "it's a static warning to override .. with .." stuff).

The [logdog log](https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.dart%2Fvm-precomp-win-simarm64-2-4-be%2F3019%2F%2B%2F%2A%2A%2Fstdout&s=chromium%2Fbb%2Fclient.dart%2Fvm-precomp-win-simarm64-2-4-be%2F3019%2F%2B%2F%2A%2A%2Fstderr) contains the following. All threads are blocked, one on `NtRemoveIoCompletion` and the others on `ZwWaitForSingleObject`. Maybe it's the precompiler vm startup sequence that gets stuck on an OS request for a file? Here's the logged text:
```
FAILED: precompiler-dart_precompiled release_simarm64 co19/Language/Classes/Setters/name_t03
Expected: Pass
Actual: Timeout
--- Command "precompiler" (took 08:02.000353s):
set DART_CONFIGURATION=ReleaseSIMARM64 & out\ReleaseSIMARM64\dart_bootstrap --snapshot-kind=app-aot --snapshot=E:/b/build/slave/vm-precomp-win-simarm64-2-4-be/build/sdk/out/ReleaseSIMARM64/generated_compilations/precompiler/tests_co19_src_Language_Classes_Setters_name_t03/out.aotsnapshot --use-blobs --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\.packages E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\tests\co19\src\Language\Classes\Setters\name_t03.dart
diagnostics:
Using E:\b\depot_tools\win_toolchain\vs_files\9bc7ccbf9f4bd50d4a3bd185e8ca94ff1618de0b\win_sdk\Debuggers\x64\cdb.exe to print stack traces
Process list including children: [4252]
Trying to capture stack trace for pid 4252
Microsoft (R) Windows Debugger Version 10.0.15063.468 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.
*** wait with pending attach
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00000001`3f160000 00000001`3fb66000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
ModLoad: 00000000`773c0000 00000000`77568000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 00000000`771a0000 0000000co19/Language/Classes/Setters/name_t030`772bf000   C:\Windows\system32\kernel32.dll
ModLoad: 000007fe`fd4b0000 000007fe`fd51c000   C:\Windows\system32\KERNELBASE.dll
ModLoad: 000007fe`fa9e0000 000007fe`faa07000   C:\Windows\system32\IPHLPAPI.DLL
ModLoad: 000007fe`fda90000 000007fe`fdb2f000   C:\Windows\system32\msvcrt.dll
ModLoad: 000007fe`fd540000 000007fe`fd548000   C:\Windows\system32\NSI.dll
ModLoad: 000007fe`fa9c0000 000007fe`fa9cb000   C:\Windows\system32\WINNSI.DLL
ModLoad: 000007fe`fd550000 000007fe`fd67d000   C:\Windows\system32\RPCRT4.dll
ModLoad: 00000000`77580000 00000000`77587000   C:\Windows\system32\PSAPI.DLL
ModLoad: 000007fe`fd750000 000007fe`fd79d000   C:\Windows\system32\WS2_32.dll
ModLoad: 000007fe`fdf60000 000007fe`fe03b000   C:\Windows\system32\ADVAPI32.dll
ModLoad: 000007fe`fe040000 000007fe`fe05f000   C:\Windows\SYSTEM32\sechost.dll
ModLoad: 000007fe`fe320000 000007fe`ff0a9000   C:\Windows\system32\SHELL32.dll
ModLoad: 000007fe`ff650000 000007fe`ff6c1000   C:\Windows\system32\SHLWAPI.dll
ModLoad: 000007fe`fe2b0000 000007fe`fe317000   C:\Windows\system32\GDI32.dll
ModLoad: 00000000`772c0000 00000000`773ba000   C:\Windows\system32\USER32.dll
ModLoad: 000007fe`fdcc0000 000007fe`fdcce000   C:\Windows\system32\LPK.dll
ModLoad: 000007fe`fd680000 000007fe`fd749000   C:\Windows\system32\USP10.dll
ModLoad: 000007fe`f8ae0000 000007fe`f8c91000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dbghelp.dll
ModLoad: 000007fe`fa700000 000007fe`fa704000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-string-l1-1-0.dll
ModLoad: 000007fe`f2250000 000007fe`f2346000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\ucrtbase.DLL
ModLoad: 000007fe`f8d90000 000007fe`f8d93000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-timezone-l1-1-0.dll
ModLoad: 000007fe`f8da0000 000007fe`f8da3000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-file-l2-1-0.dll
ModLoad: 000007fe`f8d30000 000007fe`f8d33000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-localization-l1-2-0.dll
ModLoad: 000007fe`f8d20000 000007fe`f8d23000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-synch-l1-2-0.dll
ModLoad: 000007fe`f8ad0000 000007fe`f8ad3000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-processthreads-l1-1-1.dll
ModLoad: 000007fe`f8ac0000 000007fe`f8ac3000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-file-l1-2-0.dll
ModLoad: 000007fe`f8ab0000 000007fe`f8ab3000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-time-l1-1-0.dll
ModLoad: 000007fe`f8aa0000 000007fe`f8aa4000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-runtime-l1-1-0.dll
ModLoad: 000007fe`f8a90000 000007fe`f8aa0000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-private-l1-1-0.dll
ModLoad: 000007fe`fe100000 000007fe`fe12e000   C:\Windows\system32\IMM32.DLL
ModLoad: 000007fe`fd7a0000 000007fe`fd8a9000   C:\Windows\system32\MSCTF.dll
ModLoad: 000007fe`fd020000 000007fe`fd02f000   C:\Windows\system32\cryptbase.dll
(109c.11fc): Break instruction exception - code 80000003 (first chance)
ntdll!DbgBreakPoint:
00000000`7740ce10 cc              int     3
0:004> cdb: Reading initial command '!uniqstack;qd'
Processing 5 threads, please wait
*** WARNING: Unable to verify checksum for E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
.  0  Id: 109c.d28 Suspend: 1 Teb: 000007ff`fffde000 Unfrozen
      Start: dart_bootstrap!mainCRTStartup (00000001`3f50d780)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`0024d6d8 000007fe`fd4b10dc ntdll!ZwWaitForSingleObject+0xa
00000000`0024d6e0 00000001`3f32aa4f KERNELBASE!WaitForSingleObjectEx+0x79
00000000`0024d780 00000001`3f2a3ade dart_bootstrap!dart::Monitor::Wait+0x6f
(Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
(Inline Function) --------`-------- dart_bootstrap!dart::ThreadBarrier::Sync+0x2e
00000000`0024d7c0 00000001`3f32cdd3 dart_bootstrap!dart::GCMarker::MarkObjects+0x5fe
00000000`0024e2b0 00000001`3f2a6460 dart_bootstrap!dart::PageSpace::MarkSweep+0x293
00000000`0024e460 00000001`3f3d3c56 dart_bootstrap!dart::Heap::CollectOldSpaceGarbage+0x120
00000000`0024e510 00000001`3f3f07c3 dart_bootstrap!dart::Symbols::Compact+0x56
00000000`0024e5e0 00000001`3f3ef61f dart_bootstrap!dart::Precompiler::DoCompileAll+0x823
00000000`0024ef60 00000001`3f4fde33 dart_bootstrap!dart::Precompiler::CompileAll+0x1cf
00000000`0024f470 00000001`3f16a760 dart_bootstrap!Dart_Precompile+0x1f3
00000000`0024f560 00000001`3f16b3f4 dart_bootstrap!dart::bin::RunMainIsolate+0x310
00000000`0024f660 00000001`3f16b529 dart_bootstrap!dart::bin::main+0x464
00000000`0024f790 00000001`3f50d725 dart_bootstrap!main+0x9
(Inline Function) --------`-------- dart_bootstrap!invoke_main+0x22
00000000`0024f7c0 00000000`771b59cd dart_bootstrap!__scrt_common_main_seh+0x11d
00000000`0024f800 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`0024f830 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  1  Id: 109c.12c8 Suspend: 1 Teb: 000007ff`fffdc000 Unfrozen
      Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f516bdc)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`01e4fad8 000007fe`fd4b16ad ntdll!NtRemoveIoCompletion+0xa
00000000`01e4fae0 00000000`771a9981 KERNELBASE!GetQueuedCompletionStatus+0x39
00000000`01e4fb40 00000001`3f17161c kernel32!GetQueuedCompletionStatusStub+0x11
00000000`01e4fb80 00000001`3f18e685 dart_bootstrap!dart::bin::EventHandlerImplementation::EventHandlerEntry+0xcc
00000000`01e4fc00 00000001`3f516c2c dart_bootstrap!dart::bin::ThreadEntry+0x25
(Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xd
00000000`01e4fc30 00000000`771b59cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50
00000000`01e4fc60 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`01e4fc90 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  2  Id: 109c.738 Suspend: 1 Teb: 000007ff`fffda000 Unfrozen
      Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f516bdc)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`0269ede8 000007fe`fd4b10dc ntdll!ZwWaitForSingleObject+0xa
00000000`0269edf0 00000001`3f32aa4f KERNELBASE!WaitForSingleObjectEx+0x79
00000000`0269ee90 00000001`3f2a47aa dart_bootstrap!dart::Monitor::Wait+0x6f
(Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
00000000`0269eed0 00000001`3f2a45e7 dart_bootstrap!dart::ThreadBarrier::Sync+0x3a
00000000`0269ef00 00000001`3f3d92c9 dart_bootstrap!dart::MarkTask::Run+0x6c7
00000000`0269f8d0 00000001`3f3d94be dart_bootstrap!dart::ThreadPool::Worker::Loop+0x49
00000000`0269f910 00000001`3f32a864 dart_bootstrap!dart::ThreadPool::Worker::Main+0x8e
00000000`0269f940 00000001`3f516c2c dart_bootstrap!dart::ThreadEntry+0x54
(Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xd
00000000`0269f970 00000000`771b59cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50
00000000`0269f9a0 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`0269f9d0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  3  Id: 109c.fe4 Suspend: 1 Teb: 000007ff`fffd8000 Unfrozen
      Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`3f516bdc)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`0577ed78 000007fe`fd4b10dc ntdll!ZwWaitForSingleObject+0xa
00000000`0577ed80 00000001`3f32aa4f KERNELBASE!WaitForSingleObjectEx+0x79
00000000`0577ee20 00000001`3f2a45ac dart_bootstrap!dart::Monitor::Wait+0x6f
(Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
(Inline Function) --------`-------- dart_bootstrap!dart::ThreadBarrier::Sync+0x25
00000000`0577ee60 00000001`3f3d92c9 dart_bootstrap!dart::MarkTask::Run+0x68c
00000000`0577f830 00000001`3f3d94be dart_bootstrap!dart::ThreadPool::Worker::Loop+0x49
00000000`0577f870 00000001`3f32a864 dart_bootstrap!dart::ThreadPool::Worker::Main+0x8e
00000000`0577f8a0 00000001`3f516c2c dart_bootstrap!dart::ThreadEntry+0x54
(Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xd
00000000`0577f8d0 00000000`771b59cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50
00000000`0577f900 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`0577f930 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  4  Id: 109c.11fc Suspend: 1 Teb: 000007ff`fffd4000 Unfrozen
      Start: ntdll!DbgUiRemoteBreakin (00000000`774b3760)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`0d7ffa88 00000000`774b3798 ntdll!DbgBreakPoint
00000000`0d7ffa90 00000000`771b59cd ntdll!DbgUiRemoteBreakin+0x38
00000000`0d7ffac0 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`0d7ffaf0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
Total threads: 5
quit:
--- Re-run this test:
python tools/test.py -m release -c precompiler -r dart_precompiled -a simarm64 --use-blobs co19/Language/Classes/Setters/name_t03
```

**Comment by eernstg** [comment] 2017-10-26 09:17
I've chosen area-vm for this issue, even though that's a rather loose estimate. ;-)

**Comment by eernstg** [comment] 2017-10-26 12:46
Here's already another one: Different test, same symptoms:
```
FAILED: precompiler-dart_precompiled release_simarm64 language_2/rewrite_logical_test
Expected: Pass
Actual: Timeout
--- Command "precompiler" (took 08:02.000900s):
set DART_CONFIGURATION=ReleaseSIMARM64 & out\ReleaseSIMARM64\dart_bootstrap --snapshot-kind=app-aot --snapshot=E:/b/build/slave/vm-precomp-win-simarm64-2-4-be/build/sdk/out/ReleaseSIMARM64/generated_compilations/precompiler/tests_language_2_rewrite_logical_test/out.aotsnapshot --use-blobs --reify-generic-functions --ignore-unrecognized-flags --packages=E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\.packages E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\tests\language_2\rewrite_logical_test.dart
diagnostics:
Using E:\b\depot_tools\win_toolchain\vs_files\9bc7ccbf9f4bd50d4a3bd185e8ca94ff1618de0b\win_sdk\Debuggers\x64\cdb.exe to print stack traces
Process list including children: [4692]
Trying to capture stack trace for pid 4692
Microsoft (R) Windows Debugger Version 10.0.15063.468 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.
*** wait with pending attach
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00000001`3fd70000 00000001`40776000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
ModLoad: 00000000`773c0000 00000000`77568000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 00000000`771a0000 00000000`772bf000   C:\Windows\system32\kernel32.dll
ModLoad: 000007fe`fd4b0000 000007fe`fd51c000   C:\Windows\system32\KERNELBASE.dll
ModLoad: 000007fe`fa9e0000 000007fe`faa07000   C:\Windows\system32\IPHLPAPI.DLL
ModLoad: 000007fe`fda90000 000007fe`fdb2f000   C:\Windows\system32\msvcrt.dll
ModLoad: 000007fe`fd540000 000007fe`fd548000   C:\Windows\system32\NSI.dll
ModLoad: 000007fe`fa9c0000 000007fe`fa9cb000   C:\Windows\system32\WINNSI.DLL
ModLoad: 000007fe`fd550000 000007fe`fd67d000   C:\Windows\system32\RPCRT4.dll
ModLoad: 00000000`77580000 00000000`77587000   C:\Windows\system32\PSAPI.DLL
ModLoad: 000007fe`fd750000 000007fe`fd79d000   C:\Windows\system32\WS2_32.dll
ModLoad: 000007fe`fdf60000 000007fe`fe03b000   C:\Windows\system32\ADVAPI32.dll
ModLoad: 000007fe`fe040000 000007fe`fe05f000   C:\Windows\SYSTEM32\sechost.dll
ModLoad: 000007fe`fe320000 000007fe`ff0a9000   C:\Windows\system32\SHELL32.dll
ModLoad: 000007fe`ff650000 000007fe`ff6c1000   C:\Windows\system32\SHLWAPI.dll
ModLoad: 000007fe`fe2b0000 000007fe`fe317000   C:\Windows\system32\GDI32.dll
ModLoad: 00000000`772c0000 00000000`773ba000   C:\Windows\system32\USER32.dll
ModLoad: 000007fe`fdcc0000 000007fe`fdcce000   C:\Windows\system32\LPK.dll
ModLoad: 000007fe`fd680000 000007fe`fd749000   C:\Windows\system32\USP10.dll
ModLoad: 000007fe`f8b70000 000007fe`f8d21000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dbghelp.dll
ModLoad: 000007fe`f8db0000 000007fe`f8db4000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-string-l1-1-0.dll
ModLoad: 000007fe`f79b0000 000007fe`f7aa6000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\ucrtbase.DLL
ModLoad: 000007fe`f8e70000 000007fe`f8e73000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-timezone-l1-1-0.dll
ModLoad: 000007fe`f8d90000 000007fe`f8d93000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-file-l2-1-0.dll
ModLoad: 000007fe`f8da0000 000007fe`f8da3000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-localization-l1-2-0.dll
ModLoad: 000007fe`f8d70000 000007fe`f8d73000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-synch-l1-2-0.dll
ModLoad: 000007fe`f8d80000 000007fe`f8d83000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-processthreads-l1-1-1.dll
ModLoad: 000007fe`f8b60000 000007fe`f8b63000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-core-file-l1-2-0.dll
ModLoad: 000007fe`f8b50000 000007fe`f8b53000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-time-l1-1-0.dll
ModLoad: 000007fe`f8b40000 000007fe`f8b44000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-runtime-l1-1-0.dll
ModLoad: 000007fe`f8b30000 000007fe`f8b40000   E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\api-ms-win-crt-private-l1-1-0.dll
ModLoad: 000007fe`fe100000 000007fe`fe12e000   C:\Windows\system32\IMM32.DLL
ModLoad: 000007fe`fd7a0000 000007fe`fd8a9000   C:\Windows\system32\MSCTF.dll
ModLoad: 000007fe`fd020000 000007fe`fd02f000   C:\Windows\system32\cryptbase.dll
(1254.67c): Break instruction exception - code 80000003 (first chance)
ntdll!DbgBreakPoint:
00000000`7740ce10 cc              int     3
0:004> cdb: Reading initial command '!uniqstack;qd'
Processing 5 threads, please wait
*** WARNING: Unable to verify checksum for E:\b\build\slave\vm-precomp-win-simarm64-2-4-be\build\sdk\out\ReleaseSIMARM64\dart_bootstrap.exe
.  0  Id: 1254.12f0 Suspend: 1 Teb: 000007ff`fffde000 Unfrozen
      Start: dart_bootstrap!mainCRTStartup (00000001`4011d780)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`0030d878 000007fe`fd4b10dc ntdll!ZwWaitForSingleObject+0xa
00000000`0030d880 00000001`3ff3aa4f KERNELBASE!WaitForSingleObjectEx+0x79
00000000`0030d920 00000001`3feb3ade dart_bootstrap!dart::Monitor::Wait+0x6f
(Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
(Inline Function) --------`-------- dart_bootstrap!dart::ThreadBarrier::Sync+0x2e
00000000`0030d960 00000001`3ff3cdd3 dart_bootstrap!dart::GCMarker::MarkObjects+0x5fe
00000000`0030e450 00000001`3feb6460 dart_bootstrap!dart::PageSpace::MarkSweep+0x293
00000000`0030e600 00000001`3ffe3c56 dart_bootstrap!dart::Heap::CollectOldSpaceGarbage+0x120
00000000`0030e6b0 00000001`400007c3 dart_bootstrap!dart::Symbols::Compact+0x56
00000000`0030e780 00000001`3ffff61f dart_bootstrap!dart::Precompiler::DoCompileAll+0x823
00000000`0030f100 00000001`4010de33 dart_bootstrap!dart::Precompiler::CompileAll+0x1cf
00000000`0030f610 00000001`3fd7a760 dart_bootstrap!Dart_Precompile+0x1f3
00000000`0030f700 00000001`3fd7b3f4 dart_bootstrap!dart::bin::RunMainIsolate+0x310
00000000`0030f800 00000001`3fd7b529 dart_bootstrap!dart::bin::main+0x464
00000000`0030f930 00000001`4011d725 dart_bootstrap!main+0x9
(Inline Function) --------`-------- dart_bootstrap!invoke_main+0x22
00000000`0030f960 00000000`771b59cd dart_bootstrap!__scrt_common_main_seh+0x11d
00000000`0030f9a0 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`0030f9d0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  1  Id: 1254.9e4 Suspend: 1 Teb: 000007ff`fffdc000 Unfrozen
      Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`40126bdc)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`01eaf5f8 000007fe`fd4b16ad ntdll!NtRemoveIoCompletion+0xa
00000000`01eaf600 00000000`771a9981 KERNELBASE!GetQueuedCompletionStatus+0x39
00000000`01eaf660 00000001`3fd8161c kernel32!GetQueuedCompletionStatusStub+0x11
00000000`01eaf6a0 00000001`3fd9e685 dart_bootstrap!dart::bin::EventHandlerImplementation::EventHandlerEntry+0xcc
00000000`01eaf720 00000001`40126c2c dart_bootstrap!dart::bin::ThreadEntry+0x25
(Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xd
00000000`01eaf750 00000000`771b59cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50
00000000`01eaf780 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`01eaf7b0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  2  Id: 1254.f44 Suspend: 1 Teb: 000007ff`fffda000 Unfrozen
      Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`40126bdc)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`025aefa8 000007fe`fd4b10dc ntdll!ZwWaitForSingleObject+0xa
00000000`025aefb0 00000001`3ff3aa4f KERNELBASE!WaitForSingleObjectEx+0x79
00000000`025af050 00000001`3feb47aa dart_bootstrap!dart::Monitor::Wait+0x6f
(Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
00000000`025af090 00000001`3feb45e7 dart_bootstrap!dart::ThreadBarrier::Sync+0x3a
00000000`025af0c0 00000001`3ffe92c9 dart_bootstrap!dart::MarkTask::Run+0x6c7
00000000`025afa90 00000001`3ffe94be dart_bootstrap!dart::ThreadPool::Worker::Loop+0x49
00000000`025afad0 00000001`3ff3a864 dart_bootstrap!dart::ThreadPool::Worker::Main+0x8e
00000000`025afb00 00000001`40126c2c dart_bootstrap!dart::ThreadEntry+0x54
(Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xd
00000000`025afb30 00000000`771b59cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50
00000000`025afb60 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`025afb90 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  3  Id: 1254.71c Suspend: 1 Teb: 000007ff`fffd8000 Unfrozen
      Start: dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)> (00000001`40126bdc)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`056ff198 000007fe`fd4b10dc ntdll!ZwWaitForSingleObject+0xa
00000000`056ff1a0 00000001`3ff3aa4f KERNELBASE!WaitForSingleObjectEx+0x79
00000000`056ff240 00000001`3feb45ac dart_bootstrap!dart::Monitor::Wait+0x6f
(Inline Function) --------`-------- dart_bootstrap!dart::MonitorLocker::Wait+0xa
(Inline Function) --------`-------- dart_bootstrap!dart::ThreadBarrier::Sync+0x25
00000000`056ff280 00000001`3ffe92c9 dart_bootstrap!dart::MarkTask::Run+0x68c
00000000`056ffc50 00000001`3ffe94be dart_bootstrap!dart::ThreadPool::Worker::Loop+0x49
00000000`056ffc90 00000001`3ff3a864 dart_bootstrap!dart::ThreadPool::Worker::Main+0x8e
00000000`056ffcc0 00000001`40126c2c dart_bootstrap!dart::ThreadEntry+0x54
(Inline Function) --------`-------- dart_bootstrap!invoke_thread_procedure+0xd
00000000`056ffcf0 00000000`771b59cd dart_bootstrap!thread_start<unsigned int (__cdecl*)(void * __ptr64)>+0x50
00000000`056ffd20 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`056ffd50 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
.  4  Id: 1254.67c Suspend: 1 Teb: 000007ff`fffd4000 Unfrozen
      Start: ntdll!DbgUiRemoteBreakin (00000000`774b3760)
      Priority: 0  Priority class: 32  Affinity: ff
Child-SP          RetAddr           Call Site
00000000`0d89fc38 00000000`774b3798 ntdll!DbgBreakPoint
00000000`0d89fc40 00000000`771b59cd ntdll!DbgUiRemoteBreakin+0x38
00000000`0d89fc70 00000000`773eb891 kernel32!BaseThreadInitThunk+0xd
00000000`0d89fca0 00000000`00000000 ntdll!RtlUserThreadStart+0x1d
Total threads: 5
quit:
--- Re-run this test:
python tools/test.py -m release -c precompiler -r dart_precompiled -a simarm64 --use-blobs language_2/rewrite_logical_test
```

**Comment by mraleph** [comment] 2017-11-14 15:48
Duplicate of #29261

**Closed by mraleph** 2017-11-14 15:48 UTC
Labels: area-vm, gardening, os-windows, Type: bug
