### ISSUE TITLE
NPE in ServerContextManagerCallbacks.applyFileRemoved

### ISSUE THREAD

**Issue by k-zeta** [dart-lang/sdk#35877] opened 2019-02-07 10:33 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-182.5107.16.33.5264788`
- `2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120`
- `AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.19.0-1-amd64 unknown, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120, server version 1.20.5, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/home/k-zeta/AndroidStudioProjects/thinker_app, /home/k-zeta/AndroidStudioProjects/thinker_app/android], excluded: [/home/k-zeta/AndroidStudioProjects/thinker_app/.idea, /home/k-zeta/AndroidStudioProjects/thinker_app/.dart_tool, /home/k-zeta/AndroidStudioProjects/thinker_app/.idea, /home/k-zeta/AndroidStudioProjects/thinker_app/.pub, /home/k-zeta/AndroidStudioProjects/thinker_app/build]}, clientRequestTime: 1549534514924}
NoSuchMethodError: The method 'removeFile' was called on null.
Receiver: null
Tried calling: removeFile("/home/k-zeta/AndroidStudioProjects/thinker_app/lib/main.dart___jb_tmp___")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ServerContextManagerCallbacks.applyFileRemoved (package:analysis_server/src/analysis_server.dart:1279:12)
#2      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:1414:19)
#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1302:5)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#10     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#17     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:379:20)
#18     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:254:5)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#24     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#25     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#26     _rootRun (dart:async/zone.dart:1120:38)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

For additional log information, please append the contents of
file:///var/tmp/report.txt.

**Comment by srawlins** [comment] 2019-09-07 13:57
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/33600; please follow along there.

**Comment by srawlins** [comment] 2019-09-07 13:57
Duplicate of https://github.com/dart-lang/sdk/issues/33600

**Closed by srawlins** 2019-09-07 13:57 UTC
Labels: P2, analyzer-crash-report, area-analyzer, type-bug
