### ISSUE TITLE
previous compilation file was not self-contained.

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#36981] opened 2019-05-16 03:39 UTC
Launching lib/main.dart on iPhone Xs in debug mode...

Compiler message:

```
Warning: Tried to initialize from a previous compilation (build/app.dill.track.dill), 
but the file was not self-contained. This might be a bug.

The Dart team would greatly appreciate it if you would take a moment to report 
this problem at http://dartbug.com/new.

If you are comfortable with it, it would improve the chances of fixing any bug 
if you included the file 
/var/folders/31/vhvrysrx1h17pvzhwxsywpn400gq16/T/initialize_from.dill42b4BC/initialize_from.dill.gz 
in your error report, but be aware that this file includes your source code.
Either way, you should probably delete the file so it doesn't use unnecessary 
disk space.
```

File: [initialize_from.dill.gz](https://github.com/dart-lang/sdk/files/3185294/initialize_from.dill.gz)

Another instance of https://github.com/dart-lang/sdk/issues/36032, perhaps?

**Comment by a-siva** [comment] 2019-05-24 23:15
This appears to be a duplicate of #37043

**Comment by jensjoha** [comment] 2019-06-18 09:26
Yes, it's #36032.
With a new sdk (one with 5eff2a0374cb89e335c138889c5125b48d12894d) we'll issue a "CanonicalNameSdkError" and not issue the warning in the incremental compiler.

The underlying issue is - again - a changed sdk (missing `root::dart:ui::Rect::@getters::left` because `left` became a field instead of a getter).

**Closed by jensjoha** 2019-06-18 09:26 UTC
Labels: area-front-end, front-end-kernel
