### ISSUE TITLE
Analyzer complains about super call into a noSuchMethod implementation

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#35434] opened 2018-12-18 00:48 UTC
(Please re-write that title as I don't know the right words 😄)

Take this code:

```dart
class A {
  m1() { print('m1'); }
}

class Mock {
  dynamic noSuchMethod(Invocation i) {
    print('got here');
  }
}

class _MockA1 extends Mock implements A {}

class MockA extends _MockA1 implements A {
  m1() {
    super.m1(); // ERROR
  }
}

void main() {
  MockA().m1();
}
```

You can see that _MockA1 implements A via `noSuchMethod`, and therefore has an `m1()` impl, and MockA extends _MockA1, so should be able to super into it, but the analyzer reports an error on the super call,

> The method 'm1' is always abstract in the supertype.

@leafpetersen has indicated this is probably a bug in the analyzer. The VM, for example, prints "got here".

This may be a variation on https://github.com/dart-lang/sdk/issues/35090? But without any mixins in play...

**Comment by scheglov** [comment] 2019-01-03 20:15
I think this is duplicate of https://github.com/dart-lang/sdk/issues/33553, which was fixed.

**Closed by scheglov** 2019-01-03 20:15 UTC
Labels: area-analyzer, p2-medium, type-bug

**Comment by srawlins** [comment] 2019-01-03 20:34
Woohoo! Thanks!
