### ISSUE TITLE
List<int> Extension

### ISSUE THREAD

**Issue by rvail2** [dart-lang/sdk#39952] opened 2019-12-31 08:29 UTC
I was trying to write a filter extension for list of ints.  AS reported a lint issue, and the extension will not be recognized.  I'm *assuming* they are related.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.7.0-dev.2.1`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.1, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.7.0-dev.2.1, server version 1.27.4, FATAL error: type 'KeywordToken' is not a subtype of type 'List<Annotation>'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:723:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:927:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

For additional log information, please append the contents of
file:///private/var/folders/md/pb7lz7m169z9h7_4l7mscsnc0000gp/T/report.txt.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2018.2.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.41.0)
[✓] Connected device (2 available)

**Comment by srawlins** [comment] 2020-06-14 18:34
Thanks for reporting this issue! A duplicate of this issue has been filed, which has more discussion. Please follow along there. #41267

**Comment by srawlins** [comment] 2020-06-14 18:34
Duplicate of #41267

**Closed by srawlins** 2020-06-14 18:34 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
