### ISSUE TITLE
Migration tool should perhaps propagate non-nullability back further when all usages are non-null

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/sdk#40550] opened 2020-02-09 01:07 UTC
Currently, we say if a variable usage postdominates its declaration, we make that usage a hard edge. If a node has a hard edge to a non-null type, we mark it as non-nullable. For example, in `int f(int x) => x + 1` the parameter `int x` is given non-null intent and not marked nullable except in very special circumstances.

Current behavior is essentially "non-null intent is propagated to elements post-dominated by non-null intent." We should consider exanding this to "non-null intent is propagated to elements _where all usages of that element_ are post-dominated by no-null intent."

Here's an example.

```dart
int/*1*/ f(int/*2*/ x) => x;

void g(bool b, int /*3*/ x) {
  if (b) {
   f(x) + 1;
  }
}

void h() {
  g(true, 1);
  g(false, 1);
  g(false, null);
}
```

Assume this is the whole program.

Currently we migrate this to

```dart
int? f(int? x) => x;

void g(bool b, int? x) {
  if (b) {
   f(x)! + 1;
  }
}
```

This is a fine migration. However, since we are assuming this is a whole program, a better approach would be to migrate it to:

```dart
int f(int x) => x;

void g(bool b, int? x) {
  if (b) {
   f(x!) + 1;
  }
}
```

I wrote up a doc on this and can send it to anyone interested.

**Comment by stereotype441** [comment] 2020-02-21 18:26
Duplicate of https://github.com/dart-lang/sdk/issues/40509.

**Comment by stereotype441** [comment] 2020-02-21 18:26
Duplicate of #40509

**Closed by stereotype441** 2020-02-21 18:26 UTC
Labels: NNBD, analyzer-nnbd-migration, area-analyzer
