### ISSUE TITLE
was adding new page to android studio

### ISSUE THREAD

**Issue by remoteportal** [dart-lang/sdk#39545] opened 2019-11-27 12:17 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1920x1080, 1920x1080, 1080x1920, 1920x1080, 1920x1080, 1080x1920, 1920x1080, 1920x1080`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, FATAL error: Failed to handle request: {id: 2403, method: edit.getFixes, params: {file: E:\gitlab\rec\lib\main.dart, offset: 156}, clientRequestTime: 1574856868518}
AnalysisException: Cannot analyze "E:\gitlab\rec\lib\activ%20ity.dart"

#0      DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:73:7)
<asynchronous suspension>
#1      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:82:23)
<asynchronous suspension>
#2      DartChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:53:18)
#3      FixProcessor._addFix_createImportUri (package:analysis_server/src/services/correction/fix_internal.dart:2062:31)
<asynchronous suspension>
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:281:13)
<asynchronous suspension>
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:70:41)
<asynchronous suspension>
#6      EditDomainHandler._computeDartFixes (package:analysis_server/src/edit/edit_domain.dart:651:46)
<asynchronous su

**Comment by srawlins** [comment] 2019-11-28 04:58
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37058; please follow along there.

**Comment by srawlins** [comment] 2019-11-28 04:59
Duplicate of https://github.com/dart-lang/sdk/issues/37058

**Closed by srawlins** 2019-11-28 04:59 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
