### ISSUE TITLE
Question about Isolates and thread_local

### ISSUE THREAD

**Issue by antonbashir** [dart-lang/sdk#49463] opened 2022-07-17 11:56 UTC
Hello everyone

Is it possible to execute different parts of Isolate in the same thread ? 

For example, I have an isolate function with `await for (final element in transmitter)` where transmitter is ReceivePort. 
And I've noticed that `await for` executed with other (getttid() ID) than first line of code in my isolate.
In my case I communicate with native library through FFI and that library uses thread_local values. 
So when I'm handling messages from my transmitter I'm executing functions in that library. 
But because of different threads my execution is falling. 

I want ask about possibility to bind/pin Isolate to specific thread.

**Comment by blaugold** [comment] 2022-07-17 18:22
This looks like a duplicate of https://github.com/dart-lang/sdk/issues/46943.

**Closed** 2022-07-17 19:16 UTC
