### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by tylerbryto** [dart-lang/sdk#35967] opened 2019-02-16 21:47 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-183.5153.38`
- `2.1.0-dev.9.4`
- `IC-183.5153.38, JRE 1.8.0_152-release-1343-b26x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: C:\projects\best_contacts\lib\ui\contact_page.dart context: exception_20190216_174542_809
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
#2      ConstantVisitor.visitPrefixedIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1395:12)
#3      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9033:49)
#4      ConstantVerifier._validate (package:analyzer/src/dart/constant/constant_verifier.dart:449:10)
#5      ConstantVerifier._validateDefaultValues (package:analyzer/src/dart/constant/constant_verifier.dart:509:20)
#6      ConstantVerifier.visitMethodDeclaration (package:analyzer/src/dart/constant/constant_verifier.dart:236:5)
#7      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7706:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#9      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1781:13)
#10     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:688:10)
#11     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1751:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#13     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2423:21)
#14     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:712:10)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
#16     LibraryAnalyzer._computeConstantErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:172:10)
#17     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:325:5)
#18     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:15)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:36)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#24     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#27     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1029:23)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#41     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#42     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#43     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#44     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#45     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, error: Analysis failed: C:\projects\best_contacts\lib\ui\contact_page.dart context: exception_20190216_174542_809
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      ConstantVisitor._getConstantValue (package:analyzer/src/dart/constant/evaluation.dart:1519:51)
#2      ConstantVisitor.visitPrefixedIdentifier (package:analyzer/src/dart/constant/evaluation.dart:1395:12)
#3      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9033:49)
#4      ConstantVerifier._validate (package:analyzer/src/dart/constant/constant_verifier.dart:449:10)
#5      ConstantVerifier._validateDefaultValues (package:analyzer/src/dart/constant/constant_verifier.dart:509:20)
#6      ConstantVerifier.visitMethodDeclaration (package:analyzer/src/dart/constant/constant_verifier.dart:236:5)
#7      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7706:49)
#8      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#9      ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1781:13)
#10     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:688:10)
#11     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1751:49)
#12     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8324:20)
#13     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2423:21)
#14     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:712:10)
#15     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2416:49)
#16     LibraryAnalyzer._computeConstantErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:172:10)
#17     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:325:5)
#18     LibraryAnalyzer.analyzeSync.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:121:11)
#19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:120:15)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:119:36)
#23     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:84:14)
<asynchronous suspension>
#24     _PerformanceTagImpl.makeCurrentWhileAsync (package:analyzer/src/generated/utilities_general.dart:270:21)
<asynchronous suspension>
#25     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:83:43)
<asynchronous suspension>
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1248:71)
<asynchronous suspension>
#27     PerformanceLog.runAsync (package:analyzer/src/dart/analysis/performance_logger.dart:52:21)
<asynchronous suspension>
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1224:20)
<asynchronous suspension>
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1029:23)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1891:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1832:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:340:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:505:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:551:12)
#41     Driver.start (package:analysis_server/src/server/driver.dart:503:7)
#42     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#43     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#44     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#45     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
1550346338998 <= {"id":"20084","result":{"assists":[]}}
1550346340372 => {"id":"20085","method":"analysis.updateContent","params":{"files":{"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart":{"type":"add","content":"import 'dart:io';\n\nimport 'pack
1550346340387 <= {"id":"20085","result":{}}
1550346340387 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1550346340488 => {"id":"20086","method":"edit.getAssists","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","offset":2320,"length":0},"clientRequestTime":1550346340488}
1550346341136 => {"id":"20087","method":"analysis.updateContent","params":{"files":{"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart":{"type":"add","content":"import 'dart:io';\n\nimport 'pack
1550346341205 => {"id":"20088","method":"edit.getAssists","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","offset":2754,"length":0},"clientRequestTime":1550346341205}
1550346341421 <= {"id":"20086","result":{"assists":[]}}
1550346341421 <= {"id":"20087","result":{}}
1550346341537 <= {"event":"analysis.errors","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"C:\\pr
1550346341553 <= {"id":"20088","result":{"assists":[]}}
1550346341559 <= {"event":"analysis.highlights","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":17},{"type":"BUILT_IN","of
1550346341559 <= {"event":"analysis.navigation","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","regions":[{"offset":7,"length":9,"targets":[0]},{"offset":26,"length":41,"ta
1550346341559 <= {"event":"analysis.closingLabels","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","labels":[{"offset":1695,"length":1448,"label":"Scaffold"},{"offset":1719,
1550346341559 <= {"event":"analysis.outline","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>"
1550346341575 <= {"event":"analysis.overrides","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","overrides":[{"offset":243,"length":11,"superclassMember":{"element":{"kind":"
1550346341575 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1550346341575 <= {"event":"analysis.implemented","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","classes":[],"members":[]}}
1550346341976 => {"id":"20089","method":"edit.getFixes","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","offset":2385},"clientRequestTime":1550346341976}
1550346341991 <= {"id":"20089","result":{"fixes":[]}}
1550346341991 => {"id":"20090","method":"edit.getFixes","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","offset":2590},"clientRequestTime":1550346341991}
1550346342023 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1550346342107 <= {"id":"20090","result":{"fixes":[{"error":{"severity":"WARNING","type":"STATIC_WARNING","location":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","offset":2590,"len
1550346342107 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1550346342107 <= {"event":"analysis.implemented","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","classes":[],"members":[]}}
1550346342440 => {"id":"20091","method":"analysis.updateContent","params":{"files":{"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart":{"type":"add","content":"import 'dart:io';\n\nimport 'pack
1550346342455 <= {"id":"20091","result":{}}
1550346342455 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1550346342562 => {"id":"20092","method":"edit.getAssists","params":{"file":"C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart","offset":2320,"length":0},"clientRequestTime":1550346342562}
1550346342941 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: C:\\projects\\best_contacts\\lib\\ui\\contact_page.dart context: exception_20190216_174542_809","stackTra
```

**Comment by stereotype441** [comment] 2019-02-19 18:17
Duplicate of #35241

**Closed by stereotype441** 2019-02-19 18:17 UTC
Labels: area-analyzer
