### ISSUE TITLE
Unexpected static warnings for abstract members

### ISSUE THREAD

**Issue by ngolovleva** [dart-lang/sdk#24609] opened 2015-10-16 11:58 UTC
According to specification (3-rd edition, June 2015) "10.4 Abstract Instance Members":
"It is a static warning if an abstract member m is declared or inherited in a concrete class C unless:
    • m overrides a concrete member, or
    • C has a noSuchMethod() method distinct from the one declared in class Object."

According to the above there is no static warning if a concrete class contains abstract member (instance method, instance getter, or instance setter) and has method noSuchMethod(). And this is true for abstract instance members inherited from superclass. If abstract members are declared in the class containing declaration of noSuchMethod() method, static warnings are reported.
```dart
class A {
  m();    //static warning reported
  noSuchMethod(Invocation i) {}
}
class B {
  int get g;    //static warning reported
  noSuchMethod(Invocation i) {}
}
class C {
  set s(int v);    //static warning reported
  noSuchMethod(Invocation i) {}
}
main() {
  new A();
  new B();
  new C();
}
```
Tested on Dart VM version: 1.13.0-dev.6.0 (Wed Oct  7 08:09:59 2015) on "linux_x64".

**Comment by bwilkerson** [comment] 2015-10-19 16:32
I believe that this is a duplicate of #24337.

**Closed by bwilkerson** 2015-10-19 16:32 UTC
Labels: Area-Analyzer, Priority-High, Type-Defect
