### ISSUE TITLE
'dart migrate' throws Exception: type '_NullAwareAccessContext<PromotableElement, DartType>' is not a subtype of type '_TryContext<PromotableElement, DartType>' in type cast

### ISSUE THREAD

**Issue by knaeckeKami** [dart-lang/sdk#44349] opened 2020-11-30 19:20 UTC
When I run 'dart migrate' on a small Flutter project, I get this output with an Exception thrown:

```
Migrating /Users/kami/development/getx_benchmark

See https://dart.dev/go/null-safety-migration for a migration guide.

Analyzing project...
[------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]No analysis issues found.

Generating migration suggestions...
[-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\                                    ]Aborting migration due to an exception.  This most likely is due to a
bug in the migration tool.  Please consider filing a bug report at:

https://github.com/dart-lang/sdk/issues/new
To attempt to perform migration anyway, you may re-run with
--ignore-exceptions.

Exception details:

type '_NullAwareAccessContext<PromotableElement, DartType>' is not a subtype of type '_TryContext<PromotableElement, DartType>' in type cast

#0      _FlowAnalysisImpl.tryCatchStatement_bodyEnd (package:_fe_analyzer_shared/src/flow_analysis/flow_analysis.dart:3222:21)
#1      ResolverVisitor.visitTryStatement (package:analyzer/src/generated/resolver.dart:1921:12)
#2      TryStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:9934:49)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7544:20)
#4      BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1073:17)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1691:10)
#6      UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#7      ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2412:13)
#8      ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3009:8)
#9      ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2411:5)
#10     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:2903:7)
#11     ResolverVisitor.visitDoStatementInScope (package:analyzer/src/generated/resolver.dart:1208:5)
#12     ScopedVisitor.visitDoStatement (package:analyzer/src/generated/resolver.dart:2555:7)
#13     DoStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:3095:49)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7544:20)
#15     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1073:17)
#16     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1691:10)
#17     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:3143:31)
#18     ScopedVisitor.visitBlock.<anonymous closure> (package:analyzer/src/generated/resolver.dart:2412:13)
#19     ScopedVisitor._withDeclaredLocals (package:analyzer/src/generated/resolver.dart:3009:8)
#20     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:2411:5)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1069:49)
#22     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1028:13)
#23     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1691:10)
#24     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3146:55)
#25     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:2421:13)
#26     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:903:13)
#27     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1024:49)
#28     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6976:12)
#29     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:1691:10)
#30     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3351:55)
#31     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:2859:11)
#32     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:2852:7)
#33     ResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:1610:11)
#34     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6967:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7544:20)
#36     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:2482:18)
#37     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:2463:7)
#38     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:961:13)
#39     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1521:49)
#40     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:1037:23)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2112:49)
#42     FixBuilder.visitAll.<anonymous closure> (package:nnbd_migration/src/fix_builder.dart:207:14)
#43     _rootRun (dart:async/zone.dart:1190:13)
#44     _CustomZone.run (dart:async/zone.dart:1093:19)
#45     _runZoned (dart:async/zone.dart:1630:10)
#46     runZoned (dart:async/zone.dart:1550:10)
#47     NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#48     FixBuilder.visitAll (package:nnbd_migration/src/fix_builder.dart:204:35)
#49     NullabilityMigrationImpl.finalizeInput (package:nnbd_migration/src/nullability_migration_impl.dart:175:18)
#50     NonNullableFix.finalizeUnit (package:nnbd_migration/src/front_end/non_nullable_fix.dart:112:15)
#51     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1138:21)
#52     _FixCodeProcessor.runLaterPhases.<anonymous closure> (package:nnbd_migration/migration_cli.dart:1135:28)
#53     _FixCodeProcessor.processResources (package:nnbd_migration/migration_cli.dart:1057:30)
<asynchronous suspension>
#54     _FixCodeProcessor.runLaterPhases (package:nnbd_migration/migration_cli.dart:1135:5)
<asynchronous suspension>
#55     MigrationCliRunner.run (package:nnbd_migration/migration_cli.dart:699:24)
<asynchronous suspension>
#56     MigrateCommand.run (package:nnbd_migration/migration_cli.dart:209:7)
<asynchronous suspension>
#57     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#58     DartdevRunner.runCommand (package:dartdev/dartdev.dart:249:24)
<asynchronous suspension>
#59     runDartdev (package:dartdev/dartdev.dart:112:14)
<asynchronous suspension>
#60     main (file:///opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

```
dart --version
Dart SDK version: 2.12.0-29.10.beta (beta) (Tue Nov 17 10:50:22 2020 +0100) on "macos_x64"
```

## How to reproduce

- `git clone -b nullsafety --single-branch https://github.com/knaeckeKami/changenotifier_benchmark.git`
- `cd changenotifier_benchmark/`
-  `dart pub get`
-  `dart migrate`

**Comment by stereotype441** [comment] 2020-12-01 16:05
@knaeckeKami thanks for the bug report!  I was able to reproduce your bug with changenotifier_benchmark as of https://github.com/knaeckeKami/changenotifier_benchmark/commit/4679f8ff9a56502eaa679b35bbfe3cdc9f4b80fb.  To help us prioritize, were you able to make reasonable progress using the `--ignore-exceptions` flag?

**Comment by knaeckeKami** [comment] 2020-12-01 16:27
Yes, with `--ignore-exceptions` it worked almost perfectly (with some small manual corrections needed, not sure if related to the exception).

I had issues with:

migration of 

```
 List<_Listener> _listeners = List<_Listener>();
```
to

```dart
 List<_Listener>? _listeners = List<_Listener>();
```

(`error: The default 'List' constructor isn't available when null safety is enabled. (default_list_constructor at [getx_benchmark] lib/notifiers/clever_value_notifier.dart:17)`)

(Multiple instances of this error, but easily fixed)

________

Migration of

```dart
 bold(resultsByApproach[approach]
                  .map((e) => e.time)
                  .fold(0, (a, b) => a + b)
                  .toString())
```

to

```dart
bold(resultsByApproach[approach]!
                  .map(((e) => e.time) as _ Function(TestResult))
                  .fold(0, ((dynamic a, b) => a + b) as _ Function(_, dynamic))
                  .toString())
```

With `error: Undefined class '_'. (undefined_class at [getx_benchmark] lib/print_table.dart:77)`, seem like type inference failed there

**Comment by stereotype441** [comment] 2020-12-01 17:59
> Yes, with `--ignore-exceptions` it worked almost perfectly (with some small manual corrections needed, not sure if related to the exception).

Ok, good to know, thanks.

> I had issues with:
> 
> migration of
> 
> ```
>  List<_Listener> _listeners = List<_Listener>();
> ```
> 
> to
> 
> ```dart
>  List<_Listener>? _listeners = List<_Listener>();
> ```
> 
> (`error: The default 'List' constructor isn't available when null safety is enabled. (default_list_constructor at [getx_benchmark] lib/notifiers/clever_value_notifier.dart:17)`)
> 
> (Multiple instances of this error, but easily fixed)

Glad this was easily fixed.  FYI, we're hoping to improve the migration tool's handling of the `List` constructor prior to the stable release - see https://github.com/dart-lang/sdk/issues/44198.

> Migration of
> 
> ```dart
>  bold(resultsByApproach[approach]
>                   .map((e) => e.time)
>                   .fold(0, (a, b) => a + b)
>                   .toString())
> ```
> 
> to
> 
> ```dart
> bold(resultsByApproach[approach]!
>                   .map(((e) => e.time) as _ Function(TestResult))
>                   .fold(0, ((dynamic a, b) => a + b) as _ Function(_, dynamic))
>                   .toString())
> ```
> 
> With `error: Undefined class '_'. (undefined_class at [getx_benchmark] lib/print_table.dart:77)`, seem like type inference failed there

Interesting: that's not one I've seen before.  I filed https://github.com/dart-lang/sdk/issues/44357 to track it.

**Comment by knaeckeKami** [comment] 2020-12-02 20:01
Actually, there's another issue :)

The tool migrated

```dart
 results.toMultiMap(keyFunc: (r) => r.approach, valueFunc: (v) => v);
```
to

```dart
 final resultsByApproach =
      results.toMultiMap(keyFunc: ((r) => r.approach) as String Function(TestResult), valueFunc: (v) => v);
```

(print_table.dart, line 12).

This throws an exception at runtime: 
  `type '(dynamic) => dynamic' is not a subtype of type '(TestResult) => String' in type cast`

**Comment by stereotype441** [comment] 2020-12-02 20:13
> Actually, there's another issue :)
> 
> The tool migrated
> 
> ```dart
>  results.toMultiMap(keyFunc: (r) => r.approach, valueFunc: (v) => v);
> ```
> 
> to
> 
> ```dart
>  final resultsByApproach =
>       results.toMultiMap(keyFunc: ((r) => r.approach) as String Function(TestResult), valueFunc: (v) => v);
> ```
> 
> (print_table.dart, line 12).
> https://github.com/knaeckeKami/changenotifier_benchmark/blob/nullsafety2/lib/print_table.dart#L12
> 
> This throws an exception at runtime:
> `type '(dynamic) => dynamic' is not a subtype of type '(TestResult) => String' in type cast`

This looks very similar to the issue discussed in https://github.com/dart-lang/sdk/issues/44345#issuecomment-737278551, which was fixed in e047dd60d6156f8e937dc39f89781e6be603067a.  I believe what's happening is that the presence of `as String Function(TestResult)` is defeating the normal type inference process, so a proper type is no longer being inferred for `((r) => r.approach)`.  You should be able to just drop `as String Function(TestResult)` entirely, and then type inference should assign the proper types at compilation time, so you won't get the runtime exception anymore.

Alternatively, you can try running the migration tool again with a more recent build that contains the bug fix (Dart version 2.12.0-77.0.dev or higher).

**Comment by knaeckeKami** [comment] 2020-12-02 20:17
Yeah, removing the cast works, of course, it just wanted to report the issue, but great to see that it's already fixed on master.

**Comment by leafpetersen** [comment] 2021-01-07 18:22
@stereotype441 @srawlins this is currently marked P1, is this still an issue, and if so do we plan to fix it?

**Comment by stereotype441** [comment] 2021-01-12 23:38
I'm dropping priority to P2 considering that `--ignore-exceptions` was able to work around the problem.

**Comment by franklinyow** [comment] 2021-01-20 23:27
@stereotype441 Are we still targeting this for January?

**Comment by stereotype441** [comment] 2021-01-20 23:56
> @stereotype441 Are we still targeting this for January?

At this point it looks unlikely that we'll be able to get to this in time for the stable release.  Removing from the milestone.

**Comment by stereotype441** [comment] 2023-04-13 17:37
Unassigning myself because I'm not actively working on the migration tool right now.

**Closed** 2023-11-13 18:18 UTC
Labels: P2, type-bug, NNBD, area-migration
