### ISSUE TITLE
dartanalyzer command line tool generates duplicate warnings and errors

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#28616] opened 2017-02-02 20:52 UTC
I've noticed in my project that some errors and warnings are reported multiple times. This could be depending on how many ways there are to reach a specific file in the repo.

For example, consider this small program:
**a.dart**:
```dart
main() {
  int x = '';
  print(x);
}
```

**b.dart**:
```dart
import 'a.dart';

b() => a();
```

**c.dart**:
```dart
import 'b.dart';

c() => b();
```

**d.dart**:
```dart
import 'a.dart';

d() {};
```

Here is the output of dartanalyzer:
```
> dartanalyzer a.dart
Analyzing [a.dart]...
[warning] A value of type 'String' can't be assigned to a variable of type 'int'. (a.dart, line 2, col 11)
1 warning found.
```

When run on the folder or multiple input files, you get duplicates like these:
```
> dartanalyzer .
Analyzing [.]...
[warning] A value of type 'String' can't be assigned to a variable of type 'int'. (a.dart, line 2, col 11)
[warning] A value of type 'String' can't be assigned to a variable of type 'int'. (a.dart, line 2, col 11)
[warning] A value of type 'String' can't be assigned to a variable of type 'int'. (a.dart, line 2, col 11)
[warning] A value of type 'String' can't be assigned to a variable of type 'int'. (a.dart, line 2, col 11)
[hint] Unused import. (d.dart, line 1, col 8)
4 warnings and 1 hint found.
```

if you run it on a single file, say `dartanalyzer c.dart`, then you still get a single warning for a.dart.

**Comment by devoncarew** [comment] 2017-04-10 15:31
dupe of https://github.com/dart-lang/sdk/issues/25697

**Closed by devoncarew** 2017-04-10 15:31 UTC
Labels: analyzer-command, area-analyzer, P2 medium, Type: bug
