### ISSUE TITLE
Isolate.spawnUri() should default to the same language version as the parent isolate

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#44251] opened 2020-11-19 00:10 UTC
Currently, if you run `Isolate.spawnUri()` on Dart 2.12.0-dev, it will always spawn the isolate in null-safety mode, even if the parent isolate is running in an older language version mode. To reproduce:

```dart
import 'dart:isolate';

main() async {
  await Isolate.spawnUri(Uri.dataFromString('int a; main() {}'), [], null);
}
```

This breaks the `test` package's [hybrid testing APIs](https://pub.dev/packages/test#browservm-hybrid-tests), since they're now always spawning in null-safety mode, which in turn breaks [Dart Sass's CI](https://travis-ci.com/github/sass/dart-sass/jobs/439795491). This is a high-severity issue for us, as it prevents us from testing on Dart 2.12.

**Comment by mraleph** [comment] 2020-11-19 08:23
Duplicate of #44181

**Closed by mraleph** 2020-11-19 08:23 UTC
Labels: area-library, customer-dart-sass, library-isolate, type-bug

**Comment by mraleph** [comment] 2020-11-19 08:24
See also https://github.com/dart-lang/test/issues/1363

I thought @jakemac53 has fixed it in test package somehow, but I have not tested it.

**Comment by jakemac53** [comment] 2020-11-19 19:08
You will need to add language comments (`// @dart=2.10`) etc if spawning code from a uri that is not under the current package, which is not opted in. This includes `data` uris as well as uris under some `temp` directory (such as files created with test_descriptor). 

This is a known breaking change with the null safety release. The default language version is the latest sdk, and this behaves identically to `dart <some-uri>`, which is the intention.

**Comment by mraleph** [comment] 2020-11-20 10:44
> You will need to add language comments (// @dart=2.9) etc if spawning non-null-safe code from a uri that is not under the current package. This includes data uris as well as uris under some temp directory (such as files created with test_descriptor).

In gRPC test I am spawning a file from `test/` directory and it does not seem to pick up opt-out even though other files (tests) are considered opted out.

**Comment by jakemac53** [comment] 2020-11-20 15:17
> In gRPC test I am spawning a file from `test/` directory and it does not seem to pick up opt-out even though other files (tests) are considered opted out.

It looks like you are using [Isolate.spawn](https://github.com/grpc/grpc-dart/blob/52bea07000d38878604ebeb1804d6cb2eee55e8c/test/server_handles_broken_connection_test.dart#L85)? I don't know how we intend that to behave. Their is no uri to go off of, so inheriting the current isolates mode does seem reasonable in that case to me.
