### ISSUE TITLE
CFE: Support UI as code constructs in const collections

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#36278] opened 2019-03-20 14:21 UTC
The UI as code constructs need to be supported in const collections.

**Comment by kmillikin** [comment] 2019-03-26 14:36
We are expecting to deliver basic support (enough for backend implementation) by March 29.  Some of the static errors might still need to be implemented in the week after that.

**Comment by askeksa-google** [comment] 2019-03-28 15:40
Basic support for spread and `if` in const lists, sets and maps have landed as of https://dart-review.googlesource.com/c/sdk/+/98141.

There is a known problem with set and map spreads, where it complains that the object is not a set/map. This is caused by interference from set desugaring and map constant lowering. I am working on a fix.

**Comment by askeksa-google** [comment] 2019-03-29 16:20
Remaining issue is covered by https://github.com/dart-lang/sdk/issues/36387.

**Closed by askeksa-google** 2019-03-29 16:20 UTC
Labels: area-front-end, front-end-fasta, p1-high
