### ISSUE TITLE
websocket_impl.dart WebSocket protocol error

### ISSUE THREAD

**Issue by ChrisTitcumb** [dart-lang/sdk#33179] opened 2018-05-20 02:38 UTC
Dart Version 2.0
Client = Windows 10 Pro
Server = Windows Server 2012 R2

The sky_engine/lib/websocket_impl.dart defines the Http header as below (lines 1016 on).   

      // Setup the initial handshake.
      request.headers
        ..set(HttpHeaders.CONNECTION, "Upgrade")
        ..set(HttpHeaders.UPGRADE, "websocket")
        ..set("Sec-WebSocket-Key", nonce)
        ..set("Cache-Control", "no-cache")
        ..set("Sec-WebSocket-Version", "13");

When received at the server, it finals as:

GET /chat HTTP/1.1
user-agent: Dart/2.0 (dart:io)
connection: Upgrade
cache-control: no-cache
accept-encoding: gzip
content-length: 0
sec-websocket-version: 13
host: 192.168.1.110:27416
sec-websocket-extensions: permessage-deflate; client_max_window_bits
sec-websocket-key: FLGd2663xv6xIVSRPZJ/6Q==
upgrade: websocket

The issue (bug) here is the conversion to lower case of the header by the client, thus the server rejects the header as both the [Sec-WebSocket-Version] and the [Sec-WebSocket-Key] lines do not adhere to the RFC 6455 standard.   Some Servers accept the lowercase implementation, but no all.

The flutter app is the WebSocket Demo app on the flutter cookbook site, modified to use a different server.

**Comment by mraleph** [comment] 2018-05-20 11:59
See the note on [Page 20](https://tools.ietf.org/html/rfc6455#page-20) of RFC6455

>  Please note that according to [[RFC2616]](https://tools.ietf.org/html/rfc2616), all header field names in
>    both HTTP requests and HTTP responses *are case-insensitive*.

Meaning that the server you use is non HTTP/1.1 compliant and not the Dart implementation.

**Comment by mraleph** [comment] 2018-05-20 12:01
Duplicate of #25120

**Closed by mraleph** 2018-05-20 12:01 UTC
