### ISSUE TITLE
ConstructorElementImpl is not a subtype of MethodElement in MethodElementHandle.actualElement

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#35468] opened 2018-12-20 22:43 UTC
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-183.4588.61`
- `2.1.0-dev.9.4`
- `IU-183.4588.61, JRE 1.8.0_152-release-1343-b16x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1680x1050  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/pl/5yqcvds916b39jxc_pb66y700025bq/T/report8.txt

```
Dart analysis server, SDK version 2.1.0-dev.9.4, server version 1.21.1, FATAL error: Failed to handle request: {id: 8, method: edit.getFixes, params: {file: /Users/jacobr/git/devtools/lib/inspector/inspector.dart, offset: 17315}, clientRequestTime: 1545345756260}
_ElementMismatchException: Element mismatch in /Users/jacobr/git/devtools/lib/inspector/inspector_tree.dart at class InspectorTreeNode
Caused by type 'ConstructorElementImpl' is not a subtype of type 'MethodElement' in type cast
#0      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:976:58)
#1      MethodElementHandle.isStatic (package:analyzer/src/dart/element/handle.dart:982:24)
#2      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1103:58)
#3      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:942:15)
#4      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:967:15)
#5      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1380:28)
#6      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1333:12)
#7      SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:458:30)
#8      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:6523:12)
#9      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:7415:18)

**Comment by srawlins** [comment] 2019-09-03 07:26
This looks like a duplicate of https://github.com/dart-lang/sdk/issues/37580; while this bug was opened first, the other appears to contain more stacktrace.

**Comment by srawlins** [comment] 2019-09-09 15:26
Duplicate of #37580

**Closed by srawlins** 2019-09-09 15:26 UTC
Labels: P2, analyzer-crash-report, analyzer-server, area-analyzer, type-bug
