### ISSUE TITLE
analyzer reports error in an optional new/const code

### ISSUE THREAD

**Issue by mraleph** [dart-lang/sdk#32342] opened 2018-02-27 14:43 UTC
```dart
class Widget { }

class MaterialPageRoute {
  final Widget Function() builder;
  const MaterialPageRoute({this.builder});
}

void main() {
  print(MaterialPageRoute(
    builder: () { return Widget(); }
  ));
}
```

reports

```console
sdk/bin/dartanalyzer --preview-dart-2 --strong /tmp/reduction.dart
Analyzing /tmp/reduction.dart...
  error • The function expression type '() → dynamic' isn't of type '() → Widget'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s) at /tmp/reduction.dart:11:14 • strong_mode_invalid_cast_function_expr
1 error found.
```

reduced from flutter/flutter#14899

**Comment by bwilkerson** [comment] 2018-02-27 19:46
@leafpetersen @stereotype441 In Dart 2, do we expect the type of `() { return Widget(); }` be `() → Widget`? If so, do either of you know where that should be happening? (There's code in `StaticTypeAnalyzer._inferLocalFunctionReturnType` that appears to expect that the type of the function will have already been inferred, but I don't know where that happens.)

**Comment by leafpetersen** [comment] 2018-02-27 20:26
This seems to be a recent regression.  I don't see this error in dev.23. 

This only happens with optional new: if I add `new` to the constructor call, it works.

@bwilkerson Yes, that function should have type `() -> Widget` both because of the downwards context, and because of the upwards context.  Here's a simpler repro that just captures the upwards part:

```
class Widget { }

void main() {
  var a = () { return Widget(); };
  int x = a;
}
```

The error message here implies that the inferred type of `a` is `() -> dynamic`, which is wrong.

The analyzer doesn't do exactly the right thing in the presence of upwards and downwards inference (this is a known issue  https://github.com/dart-lang/sdk/issues/29606) but ignoring this, here's my recollection of how this should be working:

While traversing the AST in the resolver/static_type_analyzer dance, `InferenceContext.addReturnOrYieldType` is called on every returned expression, and the least upper bound of the types of all of the return values is computed.  

In `Resolver.visitBlockFunctionBody`, `popReturnContext` is called which marks the function body with the computed inferred type from all of the return expressions.

In `StaticTypeAnalyzer._inferLocalFunctionReturnType`, `InferenceContext.getContext` is called to recover the inferred type that was cached on the function body, and this type is marked into the element model at that point.

My guess is that at the point where `addReturnOrYieldType` is called on the returned constructor call, the version without `new` is for some reason not resolved to the appropriate type.

**Comment by bwilkerson** [comment] 2018-02-27 22:54
Thanks! I think I understand what the problem is, and what I'm going to need to do to fix it.

**Comment by dgrove** [comment] 2018-03-03 00:25
any updates here?

**Comment by bwilkerson** [comment] 2018-03-03 17:23
I'm still working on it. It requires refactoring the support we'd added so that it happens as a separate pass rather than being done in the resolver. That necessitated invoking that extra pass in both the Driver and Task model implementations. I think I'm getting close, and hope to land it on Monday.

**Comment by bwilkerson** [comment] 2018-03-05 17:37
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/44384.

**Closed by bwilkerson** 2018-03-05 17:37 UTC
Labels: Customer-Flutter, P1 high, area-analyzer
