### ISSUE TITLE
OOM while running Flutter tests on Windows bot

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/sdk#37465] opened 2019-07-08 16:09 UTC
As seen in https://ci.chromium.org/p/flutter/builders/prod/Windows/6518

```
05:36 +0 -1: loading C:\b\s\w\ir\k\flutter\dev\automated_tests\test_smoke_test\syntax_error_test.broken_dart [E]
  Failed to load "C:\b\s\w\ir\k\flutter\dev\automated_tests\test_smoke_test\syntax_error_test.broken_dart":
  Compilation failed
  Test: C:\b\s\w\ir\k\flutter\dev\automated_tests\test_smoke_test\syntax_error_test.broken_dart
  Shell: C:\b\s\w\ir\k\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe
05:36 +0 -1: Some tests failed.

Exhausted heap space, trying to allocate 68719476752 bytes.
Compiler message:
Warning: Tried to initialize from a previous compilation (file:///C:/b/s/w/ir/k/flutter/dev/automated_tests/build/testfile.dill), but couldn't.
Error message was 'Out of Memory'.
Stacktrace included '#0      List._grow (dart:core-patch/growable_array.dart)
#1      BinaryBuilder._indexComponents (package:kernel/binary/ast_from_binary.dart:169:36)
#2      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:453:36)
#3      IncrementalCompiler.initializeFromDill (package:front_end/src/fasta/incremental_compiler.dart:635:14)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
'.
This might be a bug.
```

**Comment by a-siva** [comment] 2019-07-08 16:40
This looks like a duplicate of https://github.com/dart-lang/sdk/issues/37042

**Comment by a-siva** [comment] 2019-07-08 16:42
Closing as duplicate.

**Closed by a-siva** 2019-07-08 16:42 UTC
