### ISSUE TITLE
Analyzer crash issue

### ISSUE THREAD

**Issue by mostafambestawy** [dart-lang/sdk#39521] opened 2019-11-26 07:02 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5977832`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5977832, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: D:\flutter_projects\infinite_scroll\lib\screens\forum_screen.dart context: exception_20191126_090121_092
Element mismatch in D:\flutter_projects\infinite_scroll\lib\screens\forum_screen.dart at class _ForumScreenState extends State<ForumScreen>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:657:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Caused by type 'ConstructorElementImpl' is not a subtype of type 'MethodElement' in type cast
#0      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:1024:58)
#1      MethodElementHandle.isStatic (package:analyzer/src/dart/element/handle.dart:1030:24)
#2      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1137:58)
#3      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:976:15)
#4      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1001:15)
#5      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1397:30)
#6      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1349:12)
#7      SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:488:30)
#8      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:8591:12)
#9      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:9762:18)
#10     DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:491:56)
#11     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10613:15)
#12     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4097:17)
#13     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:857:10)
#14     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:198:11)
#15     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4092:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#17     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#18     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#19     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:84:13)
#20     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:559:13)
#21     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:83:5)
#22     ClassDeclarationImpl.accept (package:analyzer/src/d...
```

file://C:\Users\my\AppData\Local\Temp\report.txt
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: Analysis failed: D:\flutter_projects\infinite_scroll\lib\screens\forum_screen.dart context: exception_20191126_090121_092
Element mismatch in D:\flutter_projects\infinite_scroll\lib\screens\forum_screen.dart at class _ForumScreenState extends State<ForumScreen>
#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:657:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#11     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Caused by type 'ConstructorElementImpl' is not a subtype of type 'MethodElement' in type cast
#0      MethodElementHandle.actualElement (package:analyzer/src/dart/element/handle.dart:1024:58)
#1      MethodElementHandle.isStatic (package:analyzer/src/dart/element/handle.dart:1030:24)
#2      _ReferenceInfo._buildType (package:analyzer/src/summary/resynthesize.dart:1137:58)
#3      _ReferenceInfo.type (package:analyzer/src/summary/resynthesize.dart:976:15)
#4      _ReferenceInfo.buildType (package:analyzer/src/summary/resynthesize.dart:1001:15)
#5      _UnitResynthesizer.buildType (package:analyzer/src/summary/resynthesize.dart:1397:30)
#6      _UnitResynthesizer.buildLinkedType (package:analyzer/src/summary/resynthesize.dart:1349:12)
#7      SummaryResynthesizerContext.resolveLinkedType (package:analyzer/src/summary/resynthesize.dart:488:30)
#8      NonParameterVariableElementImpl.type (package:analyzer/src/dart/element/element.dart:8591:12)
#9      PropertyInducingElementImpl.type (package:analyzer/src/dart/element/element.dart:9762:18)
#10     DeclarationResolver.visitVariableDeclarationList (package:analyzer/src/generated/declaration_resolver.dart:491:56)
#11     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10613:15)
#12     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4097:17)
#13     RecursiveAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:857:10)
#14     DeclarationResolver.visitFieldDeclaration (package:analyzer/src/generated/declaration_resolver.dart:198:11)
#15     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4092:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#17     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#18     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#19     DeclarationResolver.visitClassDeclaration.<anonymous closure> (package:analyzer/src/generated/declaration_resolver.dart:84:13)
#20     DeclarationResolver._walk (package:analyzer/src/generated/declaration_resolver.dart:559:13)
#21     DeclarationResolver.visitClassDeclaration (package:analyzer/src/generated/declaration_resolver.dart:83:5)
#22     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#24     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#25     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#26     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#27     DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:46:12)
#28     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:657:31)
#29     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:162:7)
#30     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#31     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:161:11)
#32     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#33     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#34     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#35     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#36     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#37     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#38     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
#39     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#45     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#49     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#52     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#53     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
1574751661883 => {"id":"21757","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":1555,"length":0},"clientRequestTime":157475
1574751661960 <= {"id":"21755","result":{"assists":[]}}
1574751662181 => {"id":"21758","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":1090,"length":0},"clientRequestTime":157475
1574751662204 => {"id":"21759","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":1037,"length":0},"clientRequestTime":157475
1574751662204 => {"id":"21760","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":1037,"length":0},"clientRequestTime":157475
1574751662278 <= {"id":"21756","result":{"assists":[]}}
1574751662278 <= {"id":"21757","result":{"assists":[]}}
1574751662510 => {"id":"21761","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":906,"length":0},"clientRequestTime":1574751
1574751662524 <= {"id":"21758","result":{"assists":[]}}
1574751662524 <= {"id":"21759","result":{"assists":[]}}
1574751662524 <= {"id":"21760","result":{"assists":[]}}
1574751662697 => {"id":"21762","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":884,"length":0},"clientRequestTime":1574751
1574751662697 => {"id":"21763","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":884,"length":0},"clientRequestTime":1574751
1574751662808 <= {"id":"21761","result":{"assists":[]}}
1574751663013 => {"id":"21764","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":884,"length":0},"clientRequestTime":1574751
1574751663184 => {"id":"21765","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":850,"length":0},"clientRequestTime":1574751
1574751663184 => {"id":"21766","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":850,"length":0},"clientRequestTime":1574751
1574751663220 <= {"id":"21762","result":{"assists":[]}}
1574751663220 <= {"id":"21763","result":{"assists":[]}}
1574751663491 => {"id":"21767","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":0,"length":0},"clientRequestTime":157475166
1574751665645 <= {"id":"21764","result":{"assists":[]}}
1574751665860 <= {"id":"21765","result":{"assists":[]}}
1574751665860 <= {"id":"21766","result":{"assists":[]}}
1574751665860 <= {"id":"21767","result":{"assists":[]}}
1574751679920 => {"id":"21768","method":"edit.getAssists","params":{"file":"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart","offset":914,"length":0},"clientRequestTime":1574751
1574751680121 <= {"id":"21768","result":{"assists":[]}}
1574751680841 => {"id":"21769","method":"analysis.updateContent","params":{"files":{"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart":{"type":"add","content":"import 'dart:io';\
1574751680856 <= {"id":"21769","result":{}}
1574751681228 => {"id":"21770","method":"analysis.updateContent","params":{"files":{"D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart":{"type":"add","content":"import 'dart:io';\
1574751681248 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: D:\\flutter_projects\\infinite_scroll\\lib\\screens\\forum_screen.dart context: exception_20191126_090121
```

**Comment by srawlins** [comment] 2019-11-27 04:56
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/37979; please follow along there.

**Comment by srawlins** [comment] 2019-11-27 04:56
Duplicate of https://github.com/dart-lang/sdk/issues/37979

**Closed by srawlins** 2019-11-27 04:56 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
