### ISSUE TITLE
Error occurred while writing TextEditingController code in Flutter

### ISSUE THREAD

**Issue by jsawdey** [dart-lang/sdk#34869] opened 2018-10-19 18:37 UTC
DISCLAIMER: This is my first issue in GitHub, so please let me know if there is any other information that I need to add.

I'm writing a Flutter app using the Redux framework, and I was in the middle of typing when an IntelliJ error popped up, which gave me the prompt to submit this issue to the dart project.  I was coding a simple TextEditingController in a StatelessWidget, an IntelliJ error (I'm using Android Studio 3.2.1) popped up.

Here is the line I was typing out (I stopped typing as soon as the error popped up):
`final TextEditingController _controller = TextEdi`

Analyzer Feedback from IntelliJ

# Version information

- `IDEA AI-181.5540.7.32.5056338`
- `2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e`
- `AI-181.5540.7.32.5056338, JRE 1.8.0_152-release-1136-b06x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080`

The report file:
[report1.txt](https://github.com/dart-lang/sdk/files/2496947/report1.txt)

# Exception

```
Dart analysis server, SDK version 2.1.0-edge.a2eb050044eec93f0844667b8b6132e858467e4e, server version 1.20.5, error: Analysis failed: C:\Users\pengu\AndroidStudioProjects\boardgame_manager\lib\redux\containers\home\collectionFilterText.dart
Exception: Element not found in summary: package:boardgame_manager/redux/containers/home/collectionFilterText.dart

**Comment by stereotype441** [comment] 2018-10-25 13:36
Duplicate of #34555

**Closed by stereotype441** 2018-10-25 13:36 UTC
Labels: area-analyzer
