### ISSUE TITLE
autocomplete shows identifiers that are not exported

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#32306] opened 2018-02-24 16:42 UTC
![image](https://user-images.githubusercontent.com/405837/36632704-f11360c2-1989-11e8-9129-4a104a1ed938.png)

![image](https://user-images.githubusercontent.com/405837/36632709-fe401740-1989-11e8-9eeb-a2119715414a.png)

**Comment by bwilkerson** [comment] 2021-01-22 19:05
This is still the case, but now at least it happens as a result of the "available declarations" support (which allows us to suggest items that aren't imported but could be). Selecting one of these suggestions results in the appropriate import being added. I'm going to close this because I think it's now working as intended.

**Closed by bwilkerson** 2021-01-22 19:05 UTC
Labels: P2, analyzer-completion, area-analyzer, type-bug
