### ISSUE TITLE
Exception when combining list spreading, optional chaining, and class extensions

### ISSUE THREAD

**Issue by Rexios80** [dart-lang/sdk#49070] opened 2022-05-20 17:58 UTC
I have found an issue when combining list spreading, optional chaining, and class extensions:

```dart
void main() {
  final List<TestClass>? nullList = null;

  // A list with nothing special going on works as expected
  final list1 = [
    TestClass(),
  ];
  print('list1:');
  print(list1.first.value1);
  print(list1.first.value2);

  // Typing the optional chain value fixes the issue
  final list2 = [
    TestClass(),
    ...nullList ?? <TestClass>[],
  ];
  print('list2:');
  print(list2.first.value1);
  print(list2.first.value2);

  // Typing the list fixes the issue
  final list3 = <TestClass>[
    TestClass(),
    ...nullList ?? [],
  ];
  print('list3:');
  print(list3.first.value1);
  print(list3.first.value2);

  // Adding the lists together works
  final list4 = [
    TestClass(),
  ] + (nullList ?? []);
  print('list4:');
  print(list4.first.value1);
  print(list4.first.value2);

  // The analyzer has no issues with this, but the code throws an exception
  // The analyzer says the list is of type List<TestClass>
  final list5 = [
    TestClass(),
    ...nullList ?? [],
  ];
  print('list5:');
  print(list5.first.value1);
  print(list5.first.value2);
}

class TestClass {
  int get value1 => 0;
}

extension on TestClass {
  int get value2 => 1;
}
```

```console
list1:
0
1
list2:
0
1
list3:
0
1
list4:
0
1
list5:
0
Unhandled exception:
NoSuchMethodError: Class 'TestClass' has no instance getter 'value2'.
Receiver: Instance of 'TestClass'
Tried calling: value2
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
dart-lang/language#1      main
bin/enum_test.dart:46
dart-lang/language#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
dart-lang/language#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

Exited (255)
```

The analyzer has no issues with the given code, but there is an exception when running. Unsure if this is an issue with the analyzer or something else.

**Comment by jakemac53** [comment] 2022-05-20 18:16
cc @leafpetersen could maybe confirm which behavior is the expected behavior, for now I have assigned to the CFE but it could be an analyzer issue too

**Comment by leafpetersen** [comment] 2022-05-20 22:50
Shorter repro:

```dart
void checkType(List<int> x) {
}

void main() {
  {
    final List<int>? nullList = null;

    final list = nullList ?? [];
    checkType(list); // Both implementations infer List<int>
  }

  {
    final List<int>? nullList = null;

    final list = [
      ...(nullList!),
    ];
    checkType(list); // Both implementations infer List<int>
  }

  {
    final List<int>? nullList = null;
    final list = [
      ...(nullList ?? []),
    ];
    checkType(list); // CFE infers List<dynamic>, analyzer List<int>
  }
  
  {
    final List<int>? nullList = null;

    final list = [
      ...nullList ?? [],
    ];
    checkType(list);  // CFE infers List<dynamic>, analyzer List<int>
  }
}
```

Note that when used standalone, both implementations correctly infer the type of `nullList ?? []`, but when this is used as an argument to a spread, the CFE is inferring `List<dynamic>` and the analyzer is inferring `List<int>`.  The latter seems more consistent, and I think matches my recollection of the spec.  cc @johnniwinther @chloestefantsova @stereotype441 @scheglov

**Comment by lrhn** [comment] 2022-05-22 18:28
As I remember the description of how `??` inference works (can't find a spec), it was:
* If `e1 ?? e2` has context type `C`, then `e1` has context type `C?` and `e2` has context type `C`.
* If `e1 ?? e2` has no context type, `e1` has no context type. Let *T* be the static type of `e1`. The context type of `e2` is NON_NULL(*T*).

Inside a `final list [... nulllist ?? []];` the context type of `e1 ?? e2` should be `Iterable<?>`, so the context type of `[]` is `Iterable<?>`. 
I'm not surprised if that gives `List<dynamic>`.

If instead we infer `e1 ?? e2` in context `C` by inferring `e1` in context `C?` to get type `T`, let `T'` be NON_NULL(`T`), and then instantiate any `?` inside `C` wrt. `T'`, then we could get a context type of `List<int>` for `[]` in the example above.
I don't think that's how it's specified, though.

**Comment by chloestefantsova** [comment] 2022-05-25 09:20
So which way we should proceed here, @leafpetersen, @lrhn? As I understand it, the Analyzer follows the specification and the CFE doesn't, but there's also a proposal to change the specification. While that proposal is being discussed, I can bring the CFE in agreement with the spec and the Analyzer, and then we can update all three if that will be decided. WDYT?

**Comment by leafpetersen** [comment] 2022-05-25 20:37
@chloestefantsova , @lrhn will file a language discussion issue for the potential spec change, let's hold off on making any code changes pending that (to avoid any unnecessary hysteresis).

**Comment by leafpetersen** [comment] 2022-05-26 23:02
Language discussion issue is here: https://github.com/dart-lang/language/issues/2262 .

**Comment by eernstg** [comment] 2022-06-02 08:02
The implementation issue https://github.com/dart-lang/sdk/issues/49161 requests a change to the analyzer such that it uses the context type `Iterable<P>` for a list spread element, where `P` is the element context type. This eliminates the discrepancy between the analyzer and the common front end.

The language discussion concluded that the context type should be `Iterable<P>` in this case, cf. dart-lang/language#2262.

The potential language change where the context type of an expression of the form `e1 ?? e2` may be combined with the static type of `e1` after inference to provide a more informative context type for `e2` is handled in https://github.com/dart-lang/language/issues/2259.

I'm closing this issue because the topics it raises have been resolved or are handled in other issues. Please re-open it, or create new issues on subtopics from here, if you think there's a need to do further work specifically for this issue.

**Closed by eernstg** 2022-06-02 08:02 UTC
Labels: area-front-end
