### ISSUE TITLE
Regression in function type checking

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/sdk#25743] opened 2016-02-10 00:00 UTC
The following code used to work fine (no strong mode errors). 

```dart
void foo(x) {
  print(x);
}

void bar(void f(int x), int x) {
  f(x);
}

void main() {
  bar(foo, 42);
}
```

It now gives a static error:
```
error] Type check failed: foo ((dynamic) → void) is not of type (int) → void because foo cannot be typed as (int) → void
```

I believe we used to treat `foo` as `top -> void`?

@leafpetersen

**Comment by vsmenon** [comment] 2016-02-10 00:01
This is with analyzer tip.  I don't see an error in 1.14.0-dev.5.0.

**Comment by jmesserly** [comment] 2016-02-10 00:06
Let me try that as well after https://codereview.chromium.org/1678313002/ ... we were dropping the fuzzy arrows flag in a few places.

**Comment by jmesserly** [comment] 2016-02-10 00:11
Oh, nvm, my CL only affects generic functions.

I thought we interpreted `foo` as ⊥ -> void when we're doing subtype checks between two function types?

**Comment by vsmenon** [comment] 2016-02-10 00:14
I believe @leafpetersen had some logic to handle references to top-level functions - and treat the param type as top.

**Comment by jmesserly** [comment] 2016-02-10 00:42
Oh, hmmmm. I haven't seen any code like that, but that would work.

Vijay, could this regression be caused by our change to get rid of UninferredClosure? We were messing with DownCast.create ... specifically making top level functions fall into an "error" path :)

**Comment by jmesserly** [comment] 2016-02-10 00:42
But whatever it was, none of our checker tests caught it, so I'm not sure...

**Comment by jmesserly** [comment] 2016-02-10 17:27
Actually, isn't this a dupe of https://github.com/dart-lang/sdk/issues/24507?
I'm going to merge it in.

**Closed** 2016-02-10 17:27 UTC
Labels: analyzer-strong-mode, area-analyzer, resolution-duplicate

**Comment by vsmenon** [comment] 2016-02-10 18:52
Yeah, I think it's the same - thanks for merging.  I think the "regression" is really a warning changing to an error - which is exactly what you're saying.  :-)

Note, this is causing a break of sorts when I run ddc presubmit tests against analyzer tip, but only because one of the async tests we explicitly run at the end of browser_tests is no longer generated (due to warning promoted to error and no force compile I believe).

**Comment by jmesserly** [comment] 2016-02-10 19:11
> Note, this is causing a break of sorts when I run ddc presubmit tests against analyzer tip, but only because one of the async tests we explicitly run at the end of browser_tests is no longer generated (due to warning promoted to error and no force compile I believe).

DOH!

In the short term maybe work around it in the test? And I also bumped the priority of #24507. If we do want to special case original function declarations, we can certainly do that in DownCast.create.
