### ISSUE TITLE
Error in Dart Plugin

### ISSUE THREAD

**Issue by Kedar-jirel** [dart-lang/sdk#39052] opened 2019-10-22 15:25 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5900203`
- `2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2`
- `AI-191.8026.42.35.5900203, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Linux(amd64) v4.15.0-55-generic, screens 1366x768`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.0ca1582afdb057e8a701908c1c527e0a56a7b5b2, server version 1.27.1, error: Failed to handle completion domain request: {id: 443, method: completion.getSuggestionDetails, params: {file: /home/acer/HEALTH CONCERN/health_concern/lib/hospital/hospital_details/hospital_details.dart, id: 592, label: NeverScrollableScrollPhysics, offset: 59386}, clientRequestTime: 1571757867875}
Bad state: Element not contained in compilation unit: Never
#0      getUnitElement (package:analyzer/src/dart/analysis/index.dart:28:3)
#1      _IndexAssembler._getElementInfo.<anonymous closure> (package:analyzer/src/dart/analysis/index.dart:346:44)
#2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#3      _IndexAssembler._getElementInfo (package:analyzer/src/dart/analysis/index.dart:345:23)
#4      _IndexAssembler.addElementRelation (package:analyzer/src/dart/analysis/index.dart:235:32)
#5      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:499:15)
#6      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:451:7)
#7      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:758:5)
#8      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8963:49)
#9      NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7426:18)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#11     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#12     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#13     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:616:11)
#14     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#15     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7421:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
#17     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#18     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#19     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#20     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#21     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6183:20)
#22     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#23     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#24     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#25     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:616:11)
#26     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:374:7)
#27     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6177:15)
#28     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7426:18)
#29     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#30     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#31     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#32     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:616:11)
#33     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:430:51)
#34     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7421:49)
#35     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7667:20)
#36     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:377:16)
#37     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#38     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140:45)
#39     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:373:49)
#40     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6183:20)
#41     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#42     GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:188:55)
#43     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:264:41)
#44     _IndexContributor.visitExpression (package:analyzer/src/dart/analysis/index.dart:616:11)
#45     GeneralizingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:374:7)
#46     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6177:15)
#47     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8635:18)
#48     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:442:10)
#...
```

For additional log information, please append the contents of
file:///tmp/report.txt.

**Comment by srawlins** [comment] 2019-10-23 15:01
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38631; please follow along there.

**Comment by srawlins** [comment] 2019-10-23 15:01
Duplicate of https://github.com/dart-lang/sdk/issues/38631

**Closed by srawlins** 2019-10-23 15:01 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
