### ISSUE TITLE
Diagnostic message "missing_return" does not appear for the example code

### ISSUE THREAD

**Issue by chykon** [dart-lang/sdk#50147] opened 2022-10-06 13:37 UTC
The diagnostic message "missing_return" does not appear for the [example code](https://dart.dev/tools/diagnostic-messages#missing_return). It shows "body_might_complete_normally" instead.

Code to reproduce:

```dart
// main.dart
int f(int x) {
  if (x < 0) {
    return 0;
  }
}

void main() {
  print(f(1));
}
```

```yaml
# analysis_options.yaml
analyzer:
  errors:
    missing_return: error
    body_might_complete_normally: ignore
```

About Dart:

```text
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"
```

**Comment by asashour** [comment] 2022-10-06 14:08
This seems to be in purpose. `body_might_complete_normally` is meant for NNBD, while `missing_return` for legacy code.

The related commit is the one for #40396

**Comment by bwilkerson** [comment] 2022-10-06 15:03
Closing as working as intended.

**Closed by bwilkerson** 2022-10-06 15:03 UTC
