### ISSUE TITLE
error: The argument type ‘..’ can't be assigned to the parameter type ‘..’

### ISSUE THREAD

**Issue by kmmraj** [dart-lang/sdk#38966] opened 2019-10-18 10:07 UTC
I am trying to call a function that accepts another function as the argument.

When I try to generalize using Generics, I get the below error

`Error: The argument type ‘..’ can't be assigned to the parameter type ‘..’.`
```dart

class MyType {}
typedef MyFunctionType = void Function(Function <MyValue extends MyType> (MyValue?, MyValue));

class MyClass <MyValue extends MyType> {

  late MyFunctionType myFunc;

  MyClass(this.myFunc) {
    (observer) => this.newValues(observer.oldValue,observer.oldValue);
  }


  MyClass <MyValue> _select(MyValue Function(MyValue) selector)  {
    var observerFunc = (oldValue,newValue) {

    };
    return MyClass((observer) => this.observe(observerFunc));
  }


  void observe(MyFunctionType func){
    this.myFunc = func;
  }

  void newValues(MyValue oldValue, MyValue newValue) {
    // TODO Add functionality
  }
}
```

Error is 

> error: The argument type 'void Function(dynamic Function\<MyValue₀ extends MyType>(MyValue, MyValue))' can't be assigned to the parameter type 'void Function(dynamic Function\<MyValue extends MyType>(MyValue, MyValue))'. (argument_type_not_assignable at [dartTry] test/Params2Arguments.dart:16)

Analyzer Feedback from IntelliJ

## Version information

- `IDEA IU-191.6707.61`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `IU-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.5, screens 1680x1050  Retina`

**Comment by srawlins** [comment] 2019-10-18 13:07
Since you are trying out new NNBD features, it looks like this is a duplicate of https://github.com/dart-lang/sdk/issues/38937. Does that sound right, @kmmraj

**Comment by scheglov** [comment] 2019-10-28 00:43
I think this is a duplicate.

**Closed by scheglov** 2019-10-28 00:43 UTC
Labels: NNBD, area-analyzer, closed-duplicate, type-bug
