### ISSUE TITLE
Dart daemon spinning in exit code handler

### ISSUE THREAD

**Issue by timsneath** [dart-lang/sdk#41978] opened 2020-05-20 03:45 UTC
Dart is currently maxing out my MacBook Pro despite not having any Dart-related windows open any longer. 
```
$ ps -ef | grep dart
515110 11160     1   0  3:34PM ??       159:54.83 /Users/timsneath/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/timsneath/flutter/packages/flutter_tools/.packages /Users/timsneath/flutter/bin/cache/flutter_tools.snapshot daemon

$ dart --version
dart --version
Dart VM version: 2.9.0-9.0.dev.flutter-40f7a11d89 (be) (Mon May 18 12:22:50 2020 +0000) on "macos_x64"
```

This seems to be connected to running `flutter upgrade` -- I've reproduced it twice in that scenario. Once yesterday from VSCode, the other today from the CLI. 

Process info here: https://gist.github.com/timsneath/1ccd19299672103d9414e9323f5aa4aa#file-info-txt
Spindump here: https://gist.github.com/timsneath/1ccd19299672103d9414e9323f5aa4aa#file-spindump-txt

Per @jonahwilliams, this is the Flutter daemon, which "should be killed after the IDE is closed". 

@zanderso suggests "it looks like the Dart VM is spinning in the subprocess exit code handler, which I wouldn't have expected", based on https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_macos.cc#L187

I notice today that kernel_task is also maxed out: 
![image](https://user-images.githubusercontent.com/2319867/82402444-386cd700-9a11-11ea-8460-b2c1d14a0254.png)

Killing dart sent also sent `kernel_task` back to normal.

**Comment by mkustermann** [comment] 2020-05-20 08:40
@bkonyi Could this be related to your changes on dartdev tooling? Can you take a look at this?

**Comment by bkonyi** [comment] 2020-05-20 17:25
Honestly, I'm not sure. However, I'm unable to reproduce myself on my Macbook running `flutter upgrade` from the CLI. @timsneath is this consistently reproducible or does it only happen once in awhile?

**Comment by a-siva** [comment] 2020-05-20 21:15
The ExitCodeHandlerEntry function in process_macos.cc could get into a tight loop if 
the call to wait returns an error for some reason.

**Comment by timsneath** [comment] 2020-05-21 04:33
I've not managed to repro it again today, but will try again tomorrow.

**Comment by bkonyi** [comment] 2020-06-01 19:20
I think this might be related to https://github.com/dart-lang/sdk/issues/42092. TL;DR, if a child process has custom signal handlers for SIGTERM or SIGINT, it's possible that a DartDev VM instance may exit before its child. This could potentially result in the child process not exiting correctly.

**Comment by DanTup** [comment] 2020-06-04 11:16
I've been investigating an issue @mit-mit has that I think may be related to this - I think he has a reliable repro. If he runs a script without `--enable-experiment=non-nullable` from VS Code that requires it, it just gets stuck. From the log file, it seems like there is no output from stdout or stderr, but nor does the process quit.

I'm unable to repro myself, but I noticed that when I run this on a recent SDK, it's calling itself again with `--disable-dart-dev`. I don't know the details of what's going on there, but I was wondering if there's some race when that app terminates quickly (and whether it doesn't drain stdout/stderr correctly when this happens)?

**Comment by DanTup** [comment] 2020-06-04 14:20
Passing `--disable-dart-dev` in the launch config solved the issue for @mit-mit, so it does seem like it may be the same issue.

I can't repro it here (it may be timing-sensitive, since the VM is terminating very quickly due to failing to compile without the experiment flag), but if you want to try (Michael seems to be able to reproduce reliably):

- clone https://github.com/dart-lang/samples
- open null_safety/calculate_lix in VS Code
- comment out the `--enable-experiment` flag in `.vscode/launch.json`
- press `F5` to run

If it repros, it will appear to hang and not do anything. If it works (like it does for me), you'll see red errors spat out to the Debug Console and the debug session will terminate.

You can use **Dart: Capture Logs** to capture logs, but all they really show is that it stopped doing anything (but also that the process does not appear to terminate). Presumably in this state, the Dart process would still be hanging around too.

**Comment by a-siva** [comment] 2020-06-04 17:28
Irrespective of the signal issue, I think we should fix ExitCodeHandlerEntry to not have room to get into a tight loop when any error happens.

**Comment by zanderso** [comment] 2020-06-09 18:07
> Irrespective of the signal issue, I think we should fix ExitCodeHandlerEntry to not have room to get into a tight loop when any error happens.

`wait()` is probably resulting in `ECHILD` which indicates that there are no (unawaited) subprocesses. I haven't read the code closely to try to figure out how the VM can get into that state, but the `ExitCodeHandler` should probably handle the `ECHILD` result even if it seems like it should be impossible. It can handle it by walking the `ProcessInfoList` and sending an exit code to the waiters there that indicates an error---essentially the body of the `if (pid = wait() > 0)`, but with an error exit code hard-coded.

**Comment by bkonyi** [comment] 2020-07-21 18:49
Resolved by https://github.com/dart-lang/sdk/commit/157ebfe50f399c59a20d603acdf5143ceaa4cccf

**Closed by bkonyi** 2020-07-21 18:49 UTC
Labels: area-vm, release blocker, type-bug
