### ISSUE TITLE
AnalysisNotScheduledError in completion

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#25689] opened 2016-02-04 22:21 UTC
1.14.0-dev.7.2.cluster

```
Count: 1185
Medoid: Count: 1
Session: 1454002168041.0403.json
Failed to handle completion domain request:: {clientRequestTime:: 1454006990028, params:: {file:: ..., offset:: 11781}, method:: completion.getSuggestions, id:: 4058}","stackTrace"::"Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package::analyzer/src/context/context.dart::2014)
#1      AnalysisContextImpl._evaluatePendingFutures (package::analyzer/src/context/context.dart::1417)
#2      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1067)
#3      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::194)
#4      AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1066)
#5      PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::371)
#6      AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::807)
#7      Future.Future.delayed.<anonymous closure> (dart::async/future.dart::228)
#8      _rootRun (dart::async/zone.dart::903)
#9      _CustomZone.run (dart::async/zone.dart::802)
#10     _CustomZone.runGuarded (dart::async/zone.dart::708)
#11     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#12     _rootRun (dart::async/zone.dart::907)
#13     _CustomZone.run (dart::async/zone.dart::802)
#14     _CustomZone.runGuarded (dart::async/zone.dart::708)
#15     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#16     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#17     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#18     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#19     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart
Original message:
{"event"::"server.error","params"::{"isFatal"::false,"message"::"Failed to handle completion domain request:: {clientRequestTime:: 1454006990028, params:: {file:: ..., offset:: 11781}, method:: completion.getSuggestions, id:: 4058}","stackTrace"::"Instance of 'AnalysisNotScheduledError'
#0      PendingFuture.forciblyComplete (package::analyzer/src/context/context.dart::2014)
#1      AnalysisContextImpl._evaluatePendingFutures (package::analyzer/src/context/context.dart::1417)
#2      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package::analyzer/src/context/context.dart::1067)
#3      _PerformanceTagImpl.makeCurrentWhile (package::analyzer/src/generated/utilities_general.dart::194)
#4      AnalysisContextImpl.performAnalysisTask (package::analyzer/src/context/context.dart::1066)
#5      PerformAnalysisOperation.perform (package::analysis_server/src/operation/operation_analysis.dart::371)
#6      AnalysisServer.performOperation (package::analysis_server/src/analysis_server.dart::807)
#7      Future.Future.delayed.<anonymous closure> (dart::async/future.dart::228)
#8      _rootRun (dart::async/zone.dart::903)
#9      _CustomZone.run (dart::async/zone.dart::802)
#10     _CustomZone.runGuarded (dart::async/zone.dart::708)
#11     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#12     _rootRun (dart::async/zone.dart::907)
#13     _CustomZone.run (dart::async/zone.dart::802)
#14     _CustomZone.runGuarded (dart::async/zone.dart::708)
#15     _CustomZone.bindCallback.<anonymous closure> (dart::async/zone.dart::733)
#16     Timer._createTimer.<anonymous closure> (dart::async-patch/timer_patch.dart::16)
#17     _Timer._runTimers (dart::isolate-patch/timer_impl.dart::385)
#18     _Timer._handleMessage (dart::isolate-patch/timer_impl.dart::414)
#19     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::148)
"}}
```

**Comment by bwilkerson** [comment] 2016-02-04 22:31
Duplicate of #24271

**Closed by bwilkerson** 2016-02-04 22:31 UTC
Labels: analyzer-completion, analyzer-stability, area-analyzer, priority-high, Type-Defect
