### ISSUE TITLE
Unhandled ||= in handleAssignment

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/sdk#31152] opened 2017-10-19 10:46 UTC
Crash in fasta
@peter-ahe-google
id: 0335a4a0759e3536d4202953a5879c00b7b5edaf

```
org-dartlang-bulkcompile:///main.dart:5:10: Internal problem: Unhandled ||= in handleAssignment.
    done ||= bar();
         ^
#0      internalProblem (package:front_end/src/fasta/problems.dart:29:3)
#1      unhandled (package:front_end/src/fasta/problems.dart:41:10)
#2      DelayedAssignment.handleAssignment (package:front_end/src/fasta/kernel/body_builder.dart:3638:14)
#3      DelayedAssignment.buildForEffect (package:front_end/src/fasta/kernel/body_builder.dart:3590:12)
#4      BodyBuilder.toEffect (package:front_end/src/fasta/kernel/body_builder.dart:239:44)
#5      BodyBuilder.popForEffect (package:front_end/src/fasta/kernel/body_builder.dart:216:32)
#6      BodyBuilder.endExpressionStatement (package:front_end/src/fasta/kernel/body_builder.dart:687:40)
#7      Parser.parseExpressionStatement (package:front_end/src/fasta/parser/parser.dart:3487:14)
#8      Parser.parseType (package:front_end/src/fasta/parser/parser.dart:1924:16)
#9      Parser.parseExpressionStatementOrDeclaration (package:front_end/src/fasta/parser/parser.dart:3447:12)
#10     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3346:14)
#11     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3338:20)
#12     Parser.parseBlock (package:front_end/src/fasta/parser/parser.dart:4439:15)
#13     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3348:14)
#14     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3338:20)
#15     Parser.parseForRest (package:front_end/src/fasta/parser/parser.dart:4381:13)
#16     Parser.parseForStatement (package:front_end/src/fasta/parser/parser.dart:4345:14)
#17     Parser.parseStatementX (package:front_end/src/fasta/parser/parser.dart:3361:14)
#18     Parser.parseStatementOpt (package:front_end/src/fasta/parser/parser.dart:3338:20)
#19     Parser.parseFunctionBody (package:front_end/src/fasta/parser/parser.dart:3262:15)
#20     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:621:14)
#21     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:493:5)
#22     DietListener.endTopLevelMethod (package:front_end/src/fasta/source/diet_listener.dart:231:5)
#23     Parser.parseTopLevelMethod (package:front_end/src/fasta/parser/parser.dart:2348:14)
#24     Parser.parseTopLevelMember (package:front_end/src/fasta/parser/parser.dart:2256:11)
#25     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:335:14)
#26     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:282:15)
#27     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:176:14)
<asynchronous suspension>
#28     Loader.buildBodies (package:front_end/src/fasta/loader.dart:125:13)
<asynchronous suspension>
#29     KernelTarget.buildProgram (package:front_end/src/fasta/kernel/kernel_target.dart:290:20)
<asynchronous suspension>
#30     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:127:36)
<asynchronous suspension>
#31     BulkCompiler.compile.<anonymous closure> (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:51:37)
<asynchronous suspension>
#32     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:89:33)
#33     _rootRun (dart:async/zone.dart:1124)
#34     _CustomZone.run (dart:async/zone.dart:1021)
#35     runZoned (dart:async/zone.dart:1499)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:89:12)
#37     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:96:41)
#38     BulkCompiler.compile (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/bulk_compile.dart:48:28)
#39     runFailedPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:60:27)
<asynchronous suspension>
#40     testPath (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:39:9)
<asynchronous suspension>
#41     main (file:///Users/lukechurch/GitRepos/dart-sdk/sdk/pkg/front_end/tool/_fasta/fuzz_driver.dart:112:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)

```

**Comment by peter-ahe-google** [comment] 2017-10-19 11:24
Duplicate of #30340.

**Closed by peter-ahe-google** 2017-10-19 11:24 UTC
Labels: area-front-end, front-end-fasta, Resolution: duplicate
