### ISSUE TITLE
Feature Request: Bracketless lambda argument

### ISSUE THREAD

**Issue by FiercestT** [dart-lang/sdk#44591] opened 2021-01-06 01:13 UTC
Currently when writing an anonymous function with a lambda, I've noticed that even with only one argument, we are forced to enclose the argument in brackets.

E.g.
```dart
someFuture.then((oneArg) => doSomething(oneArg));
someFuture.then((l) => doSomething(l));
```

It would be simple and nice QOL if we could do it like: 

```dart
someFuture.then(oneArg => doSomething(oneArg));
someFuture.then(l => doSomething(l));
```

Java supports this and makes it a bit less of a brackety mess. 
I'm not sure if there's some other technical feature blocking this feature being added.

Thanks!

**Comment by julemand101** [comment] 2021-01-06 08:29
This sounds more like a change to the language specification which has its own repository: https://github.com/dart-lang/language/issues

**Comment by eernstg** [comment] 2021-01-06 08:52
Also note existing proposals: This one is nearly a duplicate of https://github.com/dart-lang/language/issues/320, and it is related to https://github.com/dart-lang/language/issues/265.

**Comment by mit-mit** [comment] 2021-01-06 13:47
Yes, closing as a duplicate of https://github.com/dart-lang/language/issues/320

**Closed by mit-mit** 2021-01-06 13:47 UTC
