### ISSUE TITLE
Exceptions from analysis server while running Dart code in VSCode

### ISSUE THREAD

**Issue by fgenolini** [dart-lang/sdk#33787] opened 2018-07-09 13:20 UTC
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

- Following steps from the [dart get started page](https://webdev.dartlang.org/guides/get-started)
- Pasted the `thingsTodo` function at the bottom of the file, outside the class (as instructed), then inside the class: problem detected (as expected)
- Cut the function from the class and pasted it back where it belonged (bottom of file): exception

### Versions

- Dart SDK 2.0.0-dev.67.0
- Visual Studio Code 1.25.0
- Dart Code 2.15.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\tools\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.15.0
```

### Exception (fatal)

Failed to handle request: {id: 51, method: edit.getAvailableRefactorings, params: {file: C:\Users\me\source\repos\dart\quickstart\lib\src\todo_list\todo_list_service.dart, length: 270, offset: 281}}

```text
RangeError: Value not in range: 551
#0      _StringBase.substring (dart:core/runtime/libstring_patch.dart:369:7)
#1      CorrectionUtils.getText (package:analysis_server/src/services/correction/util.dart:949:20)
#2      CorrectionUtils.getRangeText (package:analysis_server/src/services/correction/util.dart:942:12)
#3      ExtractLocalRefactoringImpl._checkSelection (package:analysis_server/src/services/refactoring/extract_local.dart:233:28)
#4      ExtractLocalRefactoringImpl.isAvailable (package:analysis_server/src/services/refactoring/extract_local.dart:219:13)
#5      EditDomainHandler._getAvailableRefactoringsImpl (package:analysis_server/src/edit/edit_domain.dart:602:14)
<asynchronous suspension>
#6      EditDomainHandler._getAvailableRefactorings (package:analysis_server/src/edit/edit_domain.dart:580:5)
#7      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:345:16)
#8      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:751:45)
#9      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#10     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:747:50)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1502:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:746:5)
#16     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#17     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#18     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#19     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#20     _rootRunUnary (dart:async/zone.dart:1134:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#26     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#27     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#28     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#29     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#30     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#31     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#32     _rootRunUnary (dart:async/zone.dart:1134:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#38     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#39     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#40     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#41     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#42     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#43     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#44     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#45     _rootRunUnary (dart:async/zone.dart:1134:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#50     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#51     _StreamController._add (dart:async/stream_controller.dart:639:7)
#52     _StreamController.add (dart:async/stream_controller.dart:585:5)
#53     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#54     _rootRunUnary (dart:async/zone.dart:1138:13)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#59     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#60     _StreamController._add (dart:async/stream_controller.dart:639:7)
#61     _StreamController.add (dart:async/stream_controller.dart:585:5)
#62     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#63     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#64     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#65     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#66     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#67     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\Users\\me\\source\\repos\\dart\\quickstart",
        "explicitFileCount": 5,
        "implicitFileCount": 2404,
        "workItemQueueLength": 7,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Users\\me\\source\\repos\\dart",
        "explicitFileCount": 0,
        "implicitFileCount": 0,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment] 2018-08-20 14:42
This is a dupe of #33471.

**Closed by DanTup** 2018-08-20 14:42 UTC
Labels: area-analyzer
