### ISSUE TITLE
suggest identifiers that are not yet imported

### ISSUE THREAD

**Issue by danrubel** [dart-lang/sdk#25820] opened 2016-02-19 18:10 UTC

**Comment by alexander-doroshko** [comment] 2016-02-19 19:35
Will this suggestion have a `SourceEdit` for the IDE to insert import (or to modify `show`/`hide` list)?

**Comment by danrubel** [comment] 2016-02-19 19:55
Yes.

**Comment by danrubel** [comment] 2016-09-14 18:12
When implementing this, we should be sure [not to suggest test classes when completing in lib directory](https://github.com/dart-lang/sdk/issues/22358).

**Comment by danrubel** [comment] 2016-10-10 20:29
To correctly implement this we must only suggest unimported types appropriate for the file being edited. More specifically...

* when editing a file in the `lib/` directory, we should only suggest types in the `lib/` directory or in packages in the `dependencies:` section of the `pubspec.yaml`.
* when editing a file in the `bin/`, `example/`, or `web/` directories, we should only suggest types in that directory or the `lib/` directory or in packages in the `dependencies:` section of the `pubspec.yaml`.
* when editing other files, we can suggest types anywhere in the package or in either the `dependencies:` or `dev_dependencies:` sections of the `pubspec.yaml`.

The blocking issue is that currently, there is no way for the completion service to know which packages are listed in `dependencies:` or `dev_dependencies:` sections of the `pubspec.yaml`.

**Comment by davidmorgan** [comment] 2016-12-01 13:55
Am I right in thinking that this issue covers auto-completing to methods of types I haven't imported yet?

i.e. if I type 'new Foo()..', and 'Foo' is not imported, it will still suggest completions that come from Foo?

This is something I miss from IntelliJ's Java behaviour -- it means you can write a whole line of code before going back to add the import.

Thanks!

**Comment by danrubel** [comment] 2016-12-01 15:48
Yes. Implementing it correctly (see above) means some additional low level functionality in analyzer in addition to the code completion mods.

This is something I'd definitely like to see added, but have not had the cycles to get to it. There's a laundry list of things to do and I don't have a good feel for where this one fits in the priority list.

**Comment by davidmorgan** [comment] 2016-12-01 15:50
Thanks. I will stay subscribed ;)

**Comment by manuelF** [comment] 2016-12-02 09:01
+1, this would be super handy to make the IDE a more seamless experience.

**Comment by hooluupog** [comment] 2017-10-03 03:25
+1, it's one of must-have features i am using everyday in Go( Goimports is automatically ran on every save of file to fix imports and format code).

**Comment by scheglov** [comment] 2018-04-01 00:31
@davidmorgan, answering on your question in https://github.com/dart-lang/sdk/issues/25820#issuecomment-264178623, my understanding is that answer is "no". This issue is about suggesting imports for top-level declarations from not yet imported libraries. What you are asking is kind of "speculative" resolution of some identifiers, even if there is no corresponding import, pretend that there is one. In theory this could be done, but why? If there is a missing import and you get a compilation error, use the Quick Fix and then get further analysis and code completion.

@danrubel is right in https://github.com/dart-lang/sdk/issues/25820#issuecomment-252737209 that we need to suggest only identifiers from libraries that are potentially accessible in the source library. But that's not the same as resolution without imports.

**Comment by davidmorgan** [comment] 2018-04-04 07:36
@scheglov I don't use Java anywhere near as much as I used to, so I don't remember the exact details; but IntelliJ with Java definitely does something along these lines.

e.g. if I type `Thr` then it suggests completions to types that are not imported that start with `Thr`. If I go on to type `ThrowableExtension.`, which is one of them, then it suggests completion to static methods of that class--without it being imported. If I choose one of the completions then as well as completing where I'm working on it adds the import.

This is preferable to a separate step to add the import simply because it's quicker--one quick fix instead of two.

I tried and was not able to repro the behaviour I seem to have been describing with suggesting completions on a variable of a not-imported type. Maybe it doesn't do this any more :) or maybe I was mistaken.

Thanks.

**Comment by DanTup** [comment] 2018-04-04 07:43
What if there are many ThrowableExtension classes in different unimported libraries - does it show the options from all of them, or just a random(?) one?

It sounds like interesting behaviour, but if it's more work, there's great value in implementing the simpler version.

Note: The API for `CompletionSuggestion` would need updating to support this - it currently exposes `importUri` but provides no information on where to insert it (maybe it should have an additional set of edits attached that can just be applied?)

**Comment by davidmorgan** [comment] 2018-04-04 07:47
It shows options from all of them--and of course the import that gets added when you pick one is the one corresponding to the completion you picked.

**Comment by bwilkerson** [comment] 2018-04-04 14:59
> ... maybe it should have an additional set of edits attached that can just be applied?

Yes, that's the plan.

**Comment by patrykpoborca** [comment] 2018-05-05 11:09
This is a very big minus so far in terms of development. I feel like I'm back in the olden days of IDE's where i have to find the imports i need while writing my code. Please let us not have to scroll all the way up or try to remember the casing of a class and then _hoping_ cmd + enter / alt + enter has the import ready to you, but wait was it "SomeClass" or "Someclass".. hope you remembered otherwise back to the top of the document you go to search `import 'package:so...'`

**Comment by sergiandreplace** [comment] 2018-09-06 14:31
@wmleler this will be far from ideal, but it will be an interesting first step. I've found that I'm mainly dealing with my own files/methods, so, saving me the time to import it manually will be a time-saver.

**Comment by GreenTigerEye** [comment] 2018-10-24 09:32
**Any news to this issue?** Manually importing things is just a waste of time which should be fixed for a better developer experience.

**Comment by kandroid29** [comment] 2019-02-26 01:42
Having to move up and down to add the import for a class is a very bad experience, it is waste of time and distraction from what I am doing. So I think auto import suggestion is a required feature for modern IDE.

**Comment by scheglov** [comment] 2019-02-26 02:15
FYI, we implemented this, you probably will get it with the next IntelliJ and Dart SDK build.
https://github.com/JetBrains/intellij-plugins/pull/637

It will show everything available to you, prioritizing libraries that are already imports (because for these you have already made your choice), and adding new imports with or without import prefix depending on whether the new import will introduce ambiguity or will be shadowed at the port of usage.

![image](https://user-images.githubusercontent.com/384794/53382404-0c0afd80-3929-11e9-8026-c26ee32d2389.png)

**Comment by kandroid29** [comment] 2019-02-26 02:45
@scheglov great! will this also be supported in Android Studio?

**Comment by scheglov** [comment] 2019-02-26 16:23
Yes, Android Studio uses the same Dart Analysis Server, and the same Dart plugin for IntelliJ.
When specifically, I don't know, maybe @stevemessick ?

**Closed by scheglov** 2019-02-26 16:23 UTC
Labels: analyzer-completion, area-analyzer, p2-medium

**Comment by 12people** [comment] 2019-03-24 21:46
How about Visual Studio Code? How can I make autoimport work there.

**Comment by DanTup** [comment] 2019-03-25 09:01
@12people VS Code work is being tracked at https://github.com/Dart-Code/Dart-Code/issues/1060. I'd like to have some additional testing before it's included in a release - if you're interested in trying it out with a preview build, please drop a comment on that issue.

**Comment by passsy** [comment] 2019-03-25 09:52
I just tested version `191.6183.41`. Suggestions of `Future` and `List` works but I don't get any suggestions for 3rd party classes, i.e. `ListMultimap` from quiver as shown in the screenshot above. ()


![Screen-Shot-2019-03-25-10-51-17 06](https://user-images.githubusercontent.com/1096485/54910084-efdc8b00-4eeb-11e9-9bc3-5e2b831d1f48.png)

**Comment by alexander-doroshko** [comment] 2019-04-01 09:43
@passsy, try with the latest Dart SDK 2.2.1-dev.x.x release.

**Comment by passsy** [comment] 2019-04-03 12:03
I can confirm it is now working with plugin version `191.6183.88` from `Apr 02, 2019` and `Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"`

**Comment by vrendina** [comment] 2019-05-28 00:20
Android Studio 3.4.1 seems to be pretty far behind IntelliJ IDEA 2019.1.2 with their Dart plugin version and was lacking this functionality even though it has been available for 2 months. Moving from Android Studio to IntelliJ for Flutter development!

**Comment by VishalNehra** [comment] 2019-09-14 21:42
Doesn't work for me InteliiJ IDEA 2019.2.2 Community Dart VM 2.5.0 and Dart plugin 192.6603.23

**Comment by shinayser** [comment] 2019-10-14 22:13
I am having problem with auto completing the new extension functions. I have added a new file called "time.dart" with some extensions, like this:

![image](https://user-images.githubusercontent.com/1146982/66782397-f93f3c00-eeab-11e9-8b8e-80d778631993.png)

My main file just can't auto complete it. If I try to fix the error I get the following:

![image](https://user-images.githubusercontent.com/1146982/66782446-0fe59300-eeac-11e9-9c72-d6170f408416.png)

As soon as I move the extensions to the same file as main, everything works:

![image](https://user-images.githubusercontent.com/1146982/66782486-2855ad80-eeac-11e9-8510-3cb5b424fd3c.png)

If I add the import manually, it also works:

![image](https://user-images.githubusercontent.com/1146982/66782625-7ff41900-eeac-11e9-8280-eba82d565524.png)

My Dart for Intellij plugin version is **192.6817.14**

**Comment by scheglov** [comment] 2019-10-14 23:28
@shinayser Please open a new issue https://github.com/dart-lang/sdk/issues.

Auto-import for extensions probably will not work, because auto-import works syntactically, i.e. we just know top-level names to include. But for extensions we need to match `on` clauses against target expressions.

We might implement quick fix.

**Comment by cyberpwnn** [comment] 2020-11-19 07:28
A core feature of an IDE tool / SDK has still yet to be implemented... or work if it is. Why is this issue closed? Nothing has changed.

**Comment by bwilkerson** [comment] 2020-11-19 15:41
Which IDE / editor are you using? The functionality is working in several editors, so I'm wondering whether the problem is specific to some editors.

Can you provide us with an example of a case in which it fails to work? There are a couple of known exceptions where it doesn't yet work, but the issue was closed because it appears to be working in general and we prefer having finer-grained issues when a piece of a feature is broken.
