### ISSUE TITLE
"We're sorry, you've found a bug in our compiler."

### ISSUE THREAD

**Issue by quetool** [dart-lang/sdk#37017] opened 2019-05-20 17:44 UTC
dartdevc arguments: --dart-sdk=/usr/local/Cellar/dart/2.3.1-dev.0.0/libexec --dart-sdk-summary=/usr/local/Cellar/dart/2.3.1-dev.0.0/libexec/lib/_internal/ddc_sdk.sum --modules=amd -o packages/angular_components/material_datepicker/calendar.ddc.js --module-root=. --library-root=/lib --summary-extension=dartdevc.linked.sum --no-summarize --options=packages/build_modules/src/analysis_options.default.yaml --source-map --source-map-comment --inline-source-map -s packages/intl/date_symbols.dartdevc.linked.sum -s packages/intl/number_symbols.dartdevc.linked.sum -s packages/intl/number_symbols_data.dartdevc.linked.sum -s packages/intl/src/plural_rules.dartdevc.linked.sum -s packages/intl/intl.dartdevc.linked.sum -s packages/quiver/core.dartdevc.linked.sum -s packages/meta/meta.dartdevc.linked.sum -s packages/quiver/time.dartdevc.linked.sum -s packages/angular_components/utils/disposer/disposer.dartdevc.linked.sum -s packages/angular_components/model/observable/observable.dartdevc.linked.sum -s packages/angular_components/utils/comparators/comparators.dartdevc.linked.sum -s packages/angular_components/model/date/date.dartdevc.linked.sum -s packages/collection/src/utils.dartdevc.linked.sum -s packages/collection/src/algorithms.dartdevc.linked.sum -s packages/collection/src/canonicalized_map.dartdevc.linked.sum -s packages/collection/src/comparators.dartdevc.linked.sum -s packages/collection/src/iterable_zip.dartdevc.linked.sum -s packages/collection/src/priority_queue.dartdevc.linked.sum -s packages/collection/collection.dartdevc.linked.sum --url-mapping=package:angular_components/material_datepicker/calendar.dart,packages/angular_components/material_datepicker/calendar.dart --url-mapping=package:angular_components/src/material_datepicker/calendar/day.dart,packages/angular_components/src/material_datepicker/calendar/day.dart --url-mapping=package:angular_components/src/material_datepicker/calendar/highlight.dart,packages/angular_components/src/material_datepicker/calendar/highlight.dart --url-mapping=package:angular_components/src/material_datepicker/calendar/model.dart,packages/angular_components/src/material_datepicker/calendar/model.dart --url-mapping=package:angular_components/src/material_datepicker/calendar/month.dart,packages/angular_components/src/material_datepicker/calendar/month.dart --url-mapping=package:angular_components/src/material_datepicker/calendar/week.dart,packages/angular_components/src/material_datepicker/calendar/week.dart --url-mapping=package:angular_components/src/material_datepicker/calendar/year.dart,packages/angular_components/src/material_datepicker/calendar/year.dart package:angular_components/material_datepicker/calendar.dart package:angular_components/src/material_datepicker/calendar/day.dart package:angular_components/src/material_datepicker/calendar/highlight.dart package:angular_components/src/material_datepicker/calendar/model.dart package:angular_components/src/material_datepicker/calendar/month.dart package:angular_components/src/material_datepicker/calendar/week.dart package:angular_components/src/material_datepicker/calendar/year.dart
    dart --version: 2.3.1-dev.0.0 (Wed May 8 14:36:43 2019 +0200) on "macos_x64"

```
RangeError (byteOffset): Invalid value: Valid value range is empty: 0
#0      _ByteDataView.getUint32 (dart:typed_data-patch/typed_data_patch.dart:4247:7)
#1      BufferContext._getUint32 (package:analyzer/src/summary/flat_buffers.dart:68:41)
#2      BufferContext.derefObject (package:analyzer/src/summary/flat_buffers.dart:54:21)
#3      TableReader.read (package:analyzer/src/summary/flat_buffers.dart:707:27)
#4      readPackageBundle (package:analyzer/src/summary/format.dart:21324:39)
#5      new PackageBundle.fromBuffer (package:analyzer/src/summary/idl.dart:2806:7)
#6      SummaryDataStore._fillMaps (package:analyzer/src/summary/package_bundle_reader.dart:316:32)
#7      new SummaryDataStore.<anonymous closure> (package:analyzer/src/summary/package_bundle_reader.dart:219:43)
#8      List.forEach (dart:core-patch/growable_array.dart:278:8)
#9      new SummaryDataStore (package:analyzer/src/summary/package_bundle_reader.dart:219:18)
#10     new CompilerAnalysisDriver (package:dev_compiler/src/analyzer/driver.dart:92:21)
#11     _compile (package:dev_compiler/src/analyzer/command.dart:135:22)
#12     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#13     compile (package:dev_compiler/src/compiler/shared_command.dart:405:18)
#14     _CompilerWorker.performRequest.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:39)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     _CompilerWorker.performRequest (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:54:24)
<asynchronous suspension>
#20     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#26     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

**Comment by claudioji** [comment] 2019-06-13 04:54
Having a similar issue. Have you found the solution?

**Comment by srawlins** [comment] 2019-09-06 04:57
Thanks for filing this issue! This was previously filed at https://github.com/dart-lang/sdk/issues/36510; please follow along there.

**Comment by srawlins** [comment] 2019-09-06 04:57
Duplicate of https://github.com/dart-lang/sdk/issues/36510

**Closed by srawlins** 2019-09-06 04:57 UTC
Labels: P2, area-web, type-bug, web-dev-compiler
