### ISSUE TITLE
Android Studio error when move files

### ISSUE THREAD

**Issue by anticafe** [dart-lang/sdk#38557] opened 2019-09-25 04:41 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.5791312`
- `2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db`
- `AI-191.8026.42.35.5791312, JRE 1.8.0_202-release-1483-b03x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1, screens 1600x900, 1600x900`

## Exception
```
Dart analysis server, SDK version 2.5.0-edge.1ef83b86ae637ffe7359173804cbc6d3fa25e6db, server version 1.27.2, error: FileSystemException(path=D:\Projects\tabula-mobile\tabulaflutter\lib\repos\models\organization_model.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:249:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:92:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:76:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:75:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
<asynchronous suspension>
#10     MoveFileRefactoringI

**Comment by srawlins** [comment] 2019-11-04 16:19
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38157; please follow along there.

**Comment by srawlins** [comment] 2019-11-04 16:19
Duplicate of https://github.com/dart-lang/sdk/issues/38157

**Closed by srawlins** 2019-11-04 16:19 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
