### ISSUE TITLE
ParameterMirror metadata is empty if method is defined in implemented interface of reflected class.

### ISSUE THREAD

**Issue by rootext** [dart-lang/sdk#34111] opened 2018-08-09 18:54 UTC
After update from Dart SDK 2.0.0-dev.54 to 2.0.0 the following code doesn't work as expected:
```dart
import 'dart:mirrors';
class Param {
  const Param();
}
abstract class A {
  int sum(@Param() int a, @Param() int b);
}
class B implements A {
  dynamic noSuchMethod(Invocation invocation) {
  }
}

void main() {
  ClassMirror classMirror = reflectClass(B); 
  MethodMirror methodMirror = classMirror.declarations[#sum];
  ParameterMirror parameterMirror = methodMirror.parameters[0];
  List<InstanceMirror> meta = parameterMirror.metadata;
  print(meta.length);
}
```
Expected result is 1.
Actual result is 0.

* Dart VM version: 2.0.0 (Unknown timestamp) on "linux_x64"

**Comment by rootext** [comment] 2018-08-15 09:40
In SDK 1.x and 2.x-dev `ClassMirror` of class `B` doesn't contain `#sum` declaration.

**Comment by rootext** [comment] 2018-10-30 09:21
Hi. Is there any update on this?
It is blocker in my library. Dart 2.0 is great but I have to put some "dirty" hacks into my code to use it.

**Comment by eernstg** [comment] 2018-10-30 10:16
I'm not working on 'dart:mirrors' or the `dart` virtual machine, but I can give you a couple of hints about what's going on:

As you can see [here](https://api.dartlang.org/stable/2.0.0/dart-mirrors/ClassMirror/declarations.html), the `declarations` getter of a `ClassMirror` returns a map describing the members actually declared in the given class (not, say, the member signatures in its interface, which includes methods that have no implementation, and not the inherited method implementations, if any).

So, for a quick glance, you shouldn't expect to get any other entries than `noSuchMethod` when you ask for the `declarations` of `B`, and hence you'd have a `methodMirror` with the value null.

However, with Dart 2 `noSuchMethod` is handled in a different way than it was in Dart 1: When the given class _C_ has a non-trivial `noSuchMethod` (that means "_C_ has another implementation than the one in `Object`"), a `noSuchMethod` forwarder (nSM forwarder) is implicitly induced (in practice that means generated) for each method signature in the interface of _C_ for which there is no implementation.

So, because of the declaration of `noSuchMethod` in `B` and because `B` is concrete, `B` will have an nSM forwarder for each unimplemented member of its interface, that is, it will have a generated `sum` method.

However, that forwarder does not "inherit" the metadata from `A.sum`, so it's correctly reported as missing.

There are several reasons why it would not be straightforward and maybe not possible (desirable or not) to let the metadata be "inherited" by the nSM forwarders: A member signature in the interface of a class may originate from several different method declarations in various superinterfaces. So if one of them for the parameter corresponding to `a` of `sum` has metadata `@absolutelyFoo` and another one has `@definitelyNotFoo` and there is some application defined semantics for those two pieces of metadata, how would a language level mechanism know which ones to "inherit", and which ones may coexist versus which ones should give rise to an error if they are associated with the same parameter, etc. etc.?

So metadata is associated with a specific declaration, and it's up to analyzers/linters/other_tools/programs_using_mirrors/etc. to search up through the relevant parts of the supertype graph to find annotations as needed and interpret what they mean.

With that, I believe the only conclusion we can make here is that it is already working as intended, and it is necessary to work a little harder in order to be able to work with metadata of methods that are handled via `noSuchMethod`.

So I'll close this issue. Please create a new issue on matters that are still not resolved, as needed.

**Comment by eernstg** [comment] 2018-10-30 10:16
PS: Sorry that you didn't get an answer earlier, but it does touch on a couple of topics that are a bit tricky. ;-)

**Closed by eernstg** 2018-10-30 10:16 UTC
Labels: area-vm, library-mirrors

**Comment by rootext** [comment] 2018-10-30 11:34
Thank you @eernstg for so detailed answer. I appreciate your time but it doesn't solve the problem.
I don't see any reliable way to get list of methods in specific class. 
I believe it should be a way to differentiate "real" and "generated" methods or declarations map shouldn't contain "generated" methods. 
I'll create a separate issue.

Based on your response I conclude that documentation is incorrect/incomplete:
`
Map<Symbol, DeclarationMirror> declarations

Returns an immutable map of the declarations actually given in the class declaration.
`
This exceptional case with noSuchMethod must be added to the documentation because it is breaking change.

**Comment by eernstg** [comment] 2018-10-30 12:04
> I don't see any reliable way to get list of methods in specific class.

For the 'methods declared by the class', that should be `declarations`. But your example shows that this concept is a little bit more subtle now (where we have nSM forwarders) than it used to be, because it's non-obvious whether these implicitly induced forwarders are "actually declared in the class".

The language specification refers to some members that a class 'declares', and other members that the class 'has', and the latter includes the former plus the inherited members; so "actually declared in the class" is not a precise concept, but it makes sense to say that it should mean the members that the class declares. nSM forwarders are among the methods that the class 'declares'. This matters because otherwise they would never be among the methods that any class 'has', and then it would not be possible to tear off an nSM forwarder (and being able to do that was one of the reasons for introducing them in the first place).

So including these implicitly induced members in `ClassMirror.declarations` is consistent with the language specification.

I also think that it's a useful approach. If you want to filter them out and ignore them in some particular scenario then you should be able to use `MethodMirror.isSynthetic`.

Checking: It actually returns false. Created #34982 in order to request a change in this respect.

**Comment by rootext** [comment] 2018-10-31 08:03
@eernstg, In general, I agree with you and understand why it is implemented in this way. Other languages do the same.
What I really needed is MethodMirror.isSynthetic. Thank you for pointing to this property.

#34982 will completely solve the problem. Thank you again.
