### ISSUE TITLE
Dart Analyzer Error

### ISSUE THREAD

**Issue by kent0ley** [dart-lang/sdk#37289] opened 2019-06-17 23:52 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.7479.19`
- `2.4.0-dev.0.0`
- `IC-191.7479.19, JRE 1.8.0_202-release-1483-b58x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.6, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.4.0-dev.0.0, server version 1.27.1, error: Analysis failed: /Users/ktoley/IdeaProjects/untitled1/web/main.dart context: exception_20190617_164845_954
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      new _LibraryResynthesizer (package:analyzer/src/summary/resynthesize.dart:666:32)
#2      SummaryResynthesizer.getLibraryElement.<anonymous closure> (package:analyzer/src/summary/resynthesize.dart:384:56)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#4      SummaryResynthesizer.getLibraryElement (package:analyzer/src/summary/resynthesize.dart:351:36)
#5      SummaryResynthesizer.getElement (package:analyzer/src/summary/resynthesize.dart:243:14)
#6      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:147:12)
#7      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:108:14)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#9      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:107:43)
#10     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1418:63)
#11     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#12     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
#13     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
<asynchronous suspension>
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
<asynchronous suspension>
#15     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
#16     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
#17     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#18     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#19     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
#25     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
#26     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#28     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
#29     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#37     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#38     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
#39     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#40     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#41     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

For additional log information, please append the contents of
file:///private/var/folders/83/4m4f7wxs6fz38cm4874stl580000gn/T/report.txt.

**Comment by srawlins** [comment] 2019-09-05 04:11
Thanks for reporting this issue! This was also reported at #37394; please follow along there.

**Comment by srawlins** [comment] 2019-09-05 04:12
Duplicate of #37394

**Closed by srawlins** 2019-09-05 04:11 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
