### ISSUE TITLE
X-CONTENT-TYPE-OPTIONS header default value of nosniff causes browser to be strict with script MIME types

### ISSUE THREAD

**Issue by raulferrerdev** [dart-lang/sdk#45366] opened 2020-11-17 17:08 UTC
When use http_server to serve files from a static directory inside app, I'm able to load de index.html. This index html loads MathJax.js in order to function properly, but when it loads the follow message appears on Safari debugger:

[Error] Refused to execute http://0.0.0.0:8034/operations/javascript/MathJax/MathJax.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.

I think that to reconfigure the server so that it serves the .js files with the content-type: text/javascript HTTP header is needed.

How can I achieve it?

**Comment by natebosch** [comment] 2021-03-18 16:57
Updated the title to reflect the root cause:

The `defaultHeaderOptions` has a `X-CONTENT-TYPE-OPTIONS` value of `nosniff` which causes some browser to be strict about MIME types.

The default mime type from `package:mime` for `.js` files is `application/javascript`. Either the script tags need to match this mime type, or the header needs to be manually removed for the server instance.

I don't think there are any actions to take on our side so I will close the issue.

**Closed by natebosch** 2021-03-18 16:57 UTC
