### ISSUE TITLE
Analyzer issue

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#39107] opened 2019-10-25 11:20 UTC
I've been seeing a lot of these recently:

### Versions

- Dart SDK 2.6.0-dev.6.0
- Visual Studio Code 1.39.2
- Dart Code 3.5.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/mit/homebrew/Cellar/dart/2.6.0-dev.6.0/libexec/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.5.1
```

### Exception

Failed to handle completion domain request: {id: 237, method: completion.getSuggestionDetails, params: {file: /Users/mit/dev/characters/example/main.dart, id: 100, label: print, offset: 97}, clientRequestTime: 1572002233213}

```text
NoSuchMethodError: The getter 'source' was called on null.
Receiver: null
Tried calling: source
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DartFileEditBuilderImpl.importLibraryElement (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1298:34)
#2      CompletionDomainHandler.getSuggestionDetails.<anonymous closure> (package:analysis_server/src/domain_completion.dart:204:32)
#3      DartChangeBuilderImpl.addFileEdit.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:54:20)
#4      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:88:20)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#14     DartChangeBuilderImpl.createFileEditBuilder (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#22     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/mit/dev/characters",
        "explicitFileCount": 13,
        "implicitFileCount": 112,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by srawlins** [comment] 2019-11-05 05:20
Thanks for reporting this issue! This was previously reported at https://github.com/dart-lang/sdk/issues/38476; please follow along there.

**Comment by srawlins** [comment] 2019-11-05 05:21
Duplicate of  https://github.com/dart-lang/sdk/issues/38476

**Closed by srawlins** 2019-11-05 05:21 UTC
Labels: analyzer-crash-report, area-analyzer, type-bug
