### ISSUE TITLE
ffi samples on dart-lang/samples are not updated

### ISSUE THREAD

**Issue by keertip** [dart-lang/sdk#39194] opened 2019-10-31 19:40 UTC
The sample code for ffi examples for primitives and struct on [`dart-lang/samples`](https://github.com/dart-lang/samples/tree/master/ffi/primitives) is referenced from the [tutorial docs](https://dart.dev/guides/libraries/c-interop) page.  I updated to the latest SDK 2.6.0-dev.8.2 and this broke the analysis on the samples. 

Looked at the sample code on `dart-lang/samples` to see if they needed to be updated, but no changes. Had to look at the sdk sources to confirm that this is indeed the case, and that the sample code has to be updated.

Maybe the samples should be moved into the SDK to make it easier to update with breaking changes?

**Comment by kwalrath** [comment] 2019-10-31 19:46
Related: https://github.com/dart-lang/samples/issues/16

**Comment by mit-mit** [comment] 2019-11-01 07:55
`dart-lang/samples` is owned by DevRel, not Eng. cc @johnpryan

**Comment by dcharkes** [comment] 2019-11-01 09:46
This is a duplicate of dart-lang/samples#16, closing this one.

**Closed by dcharkes** 2019-11-01 09:46 UTC
Labels: docs-tutorials, library-ffi
