### ISSUE TITLE
Flaky pkg/analyzer_plugin/tool/spec/check_all_test

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#29134] opened 2017-03-22 13:24 UTC
The buildbot has flakes of the following form (from [this build](https://build.chromium.org/p/client.dart/builders/pkg-linux-release-be/builds/3612/steps/package%20unit%20tests/logs/stdio)):

```
FAILED: none-vm-checked release_x64 pkg/analyzer_plugin/tool/spec/check_all_test
Expected: Pass 
Actual: Fail
CommandOutput[vm]:

stdout:
File: '/b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/test/integration/support/integration_test_methods.dart' does not have expected contents.
File: '/b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/test/integration/support/protocol_matchers.dart' does not have expected contents.
Please regenerate using:
  out/ReleaseX64/dart-sdk/bin/dart /b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/tool/spec/generate_all.dart


Command[vm]: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dart --enable_asserts --enable_type_checks --ignore-unrecognized-flags --packages=/b/build/slave/pkg-linux-release-be/build/sdk/.packages /b/build/slave/pkg-linux-release-be/build/sdk/pkg/analyzer_plugin/tool/spec/check_all_test.dart
Took 0:00:07.385730

Short reproduction command (experimental):
    python tools/test.py -mrelease --checked -t60 --use-sdk pkg/analyzer_plugin/tool/spec/check_all_test
```

It is not possible for me to reproduce this locally. Running the regeneration command is a NOP on my machine.

I will disable/skip this test for now.

@bwilkerson Would you mind taking a look?

**Comment by whesse** [comment] 2017-03-22 13:51
Duplicate of https://github.com/dart-lang/sdk/issues/29133 #29133

**Comment by bwilkerson** [comment] 2017-03-22 13:55
@devoncarew I suspect that this is a result of adding formatting to the generation process, though I'm not sure why that would cause problems.

**Comment by bwilkerson** [comment] 2017-03-22 13:56
We need to remember to revert https://codereview.chromium.org/2765273002/ when this is fixed (there won't be a failure).

**Comment by bwilkerson** [comment] 2017-03-22 13:59
We need to also revert https://codereview.chromium.org/2768803002/.

**Comment by whesse** [comment] 2017-03-22 14:00
This is why issue 29133 says "Please update the expectations of these tests, and then re-enable them in pkg/pkg.status." in its second sentence.  All issues that are listed in lines in the status file should have comments in the issue saying which status files were changed, and need to be reverted when the issue is fixed.

Reopening 29133 because it lists the two other tests that are failing.

**Comment by whesse** [comment] 2017-03-22 14:04
Leaving #29133 open and closing #29134 as duplicate

**Comment by bwilkerson** [comment] 2017-03-22 14:10
But this issue has more useful information in it!

**Comment by scheglov** [comment] 2018-11-07 16:11
Tentatively close.

**Closed by scheglov** 2018-11-07 16:11 UTC
Labels: area-analyzer, gardening, p1-high, type-bug
