### ISSUE TITLE
Can't use package:analyzer parseString function in web

### ISSUE THREAD

**Issue by ykmnkmi** [dart-lang/sdk#46639] opened 2021-07-16 11:11 UTC
Because (from pub [score](https://pub.dev/packages/analyzer/score)):
- `package:analyzer/dart/analysis/analysis_context.dart` that imports:
- `package:analyzer/src/workspace/workspace.dart` that imports:
- `package:analyzer/src/workspace/bazel.dart` that imports:
- `package:analyzer/src/workspace/bazel_watcher.dart` that imports:
- `package:watcher/watcher.dart` that imports:
- `package:watcher/src/file_watcher/polling.dart` that imports:
- `package:watcher/src/stat.dart` that imports:
- `dart:io`

**Comment by srawlins** [comment] 2022-05-20 22:39
Duplicate of https://github.com/dart-lang/sdk/issues/25978

**Closed by srawlins** 2022-05-20 22:39 UTC
Labels: area-analyzer, P3, type-enhancement
