### ISSUE TITLE
Dart Analyzer Error Encountered a Dart Analysis Server error.

### ISSUE THREAD

**Issue by tbm98** [dart-lang/sdk#40679] opened 2020-02-19 10:50 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA AI-191.8026.42.35.6010548`
- `2.8.0-edge.514a8d4c841724d3d1a71822ab9dd49bcacb75da`
- `AI-191.8026.42.35.6010548, JRE 1.8.0_202-release-1483-b49-5587405x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.2, screens 1440x900  Retina`

## Exception
```
Dart analysis server, SDK version 2.8.0-edge.514a8d4c841724d3d1a71822ab9dd49bcacb75da, server version 1.27.4, error: FileSystemException(path=/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:247:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:90:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:74:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:73:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:72:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1019:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:975:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:853:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:388:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:313:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:309:50)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:308:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_co...
```

For additional log information, please append the contents of
file:///private/var/folders/p3/yks0s53s34s9pvmqcpy46pmc0000gn/T/report.txt.

**Comment by tbm98** [comment] 2020-02-19 10:51
Dart analysis server, SDK version 2.8.0-edge.514a8d4c841724d3d1a71822ab9dd49bcacb75da, server version 1.27.4, error: FileSystemException(path=/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:212:7)
#1      _OverlayFile.readAsStringSync (package:analyzer/file_system/overlay_file_system.dart:247:18)
#2      FileSource.contentsFromFile (package:analyzer/src/source/source_resource.dart:90:46)
#3      FileSource.contents.<anonymous closure> (package:analyzer/src/source/source_resource.dart:74:14)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#5      FileSource.contents (package:analyzer/src/source/source_resource.dart:73:37)
#6      MoveFileRefactoringImpl._isPackageReference (package:analysis_server/src/services/refactoring/move_file.dart:182:43)
#7      MoveFileRefactoringImpl._computeNewUri (package:analysis_server/src/services/refactoring/move_file.dart:163:9)
#8      MoveFileRefactoringImpl.createChange.<anonymous closure> (package:analysis_server/src/services/refactoring/move_file.dart:149:25)
#9      ChangeBuilderImpl.addFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:72:20)
<asynchronous suspension>
#10     MoveFileRefactoringImpl.createChange (package:analysis_server/src/services/refactoring/move_file.dart:148:27)
<asynchronous suspension>
#11     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:1019:41)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:975:5)
#17     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:853:24)
#18     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:388:16)
#19     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:313:45)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#21     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:309:50)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:308:5)
#27     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#29     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#30     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#40     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#41     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#48     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#49     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#50     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#51     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#52     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#53     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#54     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#55     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#56     _rootRunUnary (dart:async/zone.dart:1134:38)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#61     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#62     _StreamController._add (dart:async/stream_controller.dart:649:7)
#63     _StreamController.add (dart:async/stream_controller.dart:595:5)
#64     _Socket._onData (dart:io-patch/socket_patch.dart:1870:41)
#65     _rootRunUnary (dart:async/zone.dart:1138:13)
#66     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#67     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#70     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#71     _StreamController._add (dart:async/stream_controller.dart:649:7)
#72     _StreamController.add (dart:async/stream_controller.dart:595:5)
#73     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
#74     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#75     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#76     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#77     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```
1582105024483 <= {"id":"121","result":{"files":["/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/models/account.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":0,"length":0
1582105024521 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/home.dart","errors":[{"severity":"INFO","type":"LINT","locati
1582105024521 <= {"id":"122","result":{"files":["/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/providers/account.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":0,"length
1582105024522 => {"id":"124","method":"analysis.getNavigation","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/home.dart","offset":757,"length":22},"clie
1582105024526 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/models/account_response.dart","errors":[{"severity":"INFO","type":"LINT",
1582105024526 <= {"id":"123","result":{"files":["/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/models/account.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":0,"length":0
1582105024552 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/home.dart","errors":[{"severity":"INFO","type":"LINT","locati
1582105024552 <= {"id":"124","result":{"files":["/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":0,"leng
1582105024559 => {"id":"125","method":"analysis.getNavigation","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart","offset":1349,"length":79},"
1582105024629 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart","errors":[{"severity":"INFO","type":"LINT","loc
1582105024629 <= {"id":"125","result":{"files":["/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account_detail.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":
1582105024632 => {"id":"126","method":"analysis.getNavigation","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account_detail.dart","offset":260,"length"
1582105024720 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account_detail.dart","errors":[{"severity":"INFO","type":"LIN
1582105024720 <= {"id":"126","result":{"files":["/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account_edit.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset":0,
1582105024722 => {"id":"127","method":"analysis.getNavigation","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/setting.dart","offset":200,"length":80},"c
1582105024780 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/setting.dart","errors":[{"severity":"INFO","type":"LINT","loc
1582105024780 <= {"id":"127","result":{"files":["/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/change_password.dart"],"targets":[{"kind":"LIBRARY","fileIndex":0,"offset"
1582105024853 => {"id":"128","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart","offset":0,"
1582105024947 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart","errors":[{"severity":"INFO","type":"LINT","loc
1582105024949 <= {"id":"128","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[]}}
1582105024963 => {"id":"129","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart","offset":0,"
1582105025094 <= {"id":"129","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"change":{"message":"","edits":[{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/co
1582105025120 => {"id":"130","method":"analysis.updateContent","params":{"files":{"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/home.dart":{"type":"add","content":"impo
1582105025120 => {"id":"131","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account_detail.dart","offs
1582105025125 <= {"id":"130","result":{}}
1582105025129 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":989,"uri":"package:andes_mobile_user/src/commons/views/pages/home.dart","items":[{"label":"Home","declar
1582105025215 <= {"event":"analysis.errors","params":{"file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account_detail.dart","errors":[{"severity":"INFO","type":"LIN
1582105025215 <= {"id":"131","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[]}}
1582105025216 => {"id":"132","method":"edit.getRefactoring","params":{"kind":"MOVE_FILE","file":"/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account_detail.dart","offs
1582105025278 <= {"id":"132","error":{"code":"SERVER_ERROR","message":"FileSystemException(path=/Users/tbm/dev/mobile_projects/andes_mobile_user/lib/src/commons/views/pages/account.dart; message=Canno
```

**Comment by srawlins** [comment] 2020-06-13 02:55
Thanks for reporting this issue! This was previously reported at #40063; please follow along there.

**Comment by srawlins** [comment] 2020-06-13 02:55
Duplicate of #40063

**Closed by srawlins** 2020-06-13 02:55 UTC
Labels: analyzer-crash-report, area-analyzer
