### ISSUE TITLE
New MSAN failures after Clang-roll to be triaged

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/sdk#49329] opened 2022-06-24 12:08 UTC
The clang roll in 413f60a8b6b2898a5b77a527408f4620ef22b549 has resulted in new msan failures. See e.g. [this log](https://dart-ci.appspot.com/log/vm-kernel-msan-linux-release-x64/dartk-msan-linux-release-x64/1780/vm/cc/Dart_SetFfiNativeResolver_DoesNotResolve):
```
stderr:
==15705==WARNING: MemorySanitizer: use-of-uninitialized-value
LLVMSymbolizer: error reading file: No such file or directory
    #0 0x556712b04445 in dart::ObjectPtr::GetClassIdMayBeSmi() const ../../out/ReleaseMSANX64/../../runtime/vm/tagged_pointer.h:143:12
    #1 0x556712b04445 in dart::Object::SetPtr(dart::ObjectPtr, long) ../../out/ReleaseMSANX64/../../runtime/vm/object.h:12441:25
    #2 0x556712b04445 in dart::Object::initializeHandle(dart::Object*, dart::ObjectPtr) ../../out/ReleaseMSANX64/../../runtime/vm/object.h:817:10
    #3 0x556712b04445 in dart::Object::Handle(dart::Zone*, dart::ObjectPtr) ../../out/ReleaseMSANX64/../../runtime/vm/object.h:375:5
...
--- Re-run this test:
python3 tools/test.py -n dartk-msan-linux-release-x64 vm/cc/Dart_SetFfiNativeResolver_DoesNotResolve
```

The tests
```
vm/cc/DartAPI_NativeFieldAccess Crash (expected Pass)
vm/cc/DartAPI_NativeFieldAccess_Throws Crash (expected Pass)
vm/cc/Dart_SetFfiNativeResolver Crash (expected Pass)
vm/cc/Dart_SetFfiNativeResolver_DoesNotResolve Crash (expected Pass)
vm/cc/Dart_SetFfiNativeResolver_MissingResolver Crash (expected Pass)
```
are failing on configurations
```
dartk-msan-linux-release-x64
```

/cc @aam @rmacnak-google

**Comment by mraleph** [comment] 2022-06-24 12:38
Duplicate of #49298

**Closed by mraleph** 2022-06-24 12:38 UTC
Labels: area-vm, gardening
