### ISSUE TITLE
Analyzer exception: Task failed: GenerateLintsTask for source ...

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#26596] opened 2016-06-02 11:06 UTC
> 02.06.16
12:12	Throwable
			Dart analysis server, SDK version 1.17.0-edge.fa5b98126cd0b03163cf1e985944ef84daffe96b, server version 1.15.0, error: Task failed: GenerateLintsTask for source /home/myuser/dart/bwu_datagrid/example_/test/checkbox_row_select_test.dart
			Unexpected exception while performing GenerateLintsTask for source /home/myuser/dart/bwu_datagrid/example_/test/checkbox_row_select_test.dart
			#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
			#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
			#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
			#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
			#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1182)
			#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
			#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.da... (show balloon)

I see this regularly since I updated to the newest bleeding edge yesterday. (I didn't update since about 3 weeks before that.)

**Comment by mit-mit** [comment] 2016-06-02 12:12
Tagging for 1.17 candidate

**Comment by bwilkerson** [comment] 2016-06-02 14:07
Was there, by any chance, a "Caused by" exception associated with this exception? That would probably help us identify the root cause. If not, could you provide us with a list of the lint rules that are enabled?

Is the version of the code that exposed the bug published to GitHub? If so could you send us a pointer to it? If not, could you send us the code to make it easier to reproduce the behavior?

@pq

**Comment by zoechi** [comment] 2016-06-02 14:13
Sorry, I thought I had copied the whole exception but the WebStorm view where I copied it from only showed a part. 
I hope this is what you are looking for:

```
Dart analysis server, SDK version 1.17.0-edge.fa5b98126cd0b03163cf1e985944ef84daffe96b, server version 1.15.0, error: Task failed: GenerateLintsTask for source /home/myuser/dart/bwu_datagrid/example_/test/checkbox_row_select_test.dart
Unexpected exception while performing GenerateLintsTask for source /home/myuser/dart/bwu_datagrid/example_/test/checkbox_row_select_test.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1182)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1180)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'element'.

NoSuchMethodError: method not found: 'element'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _Visitor.visitMethodInvocation (package:linter/src/rules/iterable_contains_unrelated_type.dart:155)
#3      DelegatingAstVisitor.visitMethodInvocation.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:604)
#4      List.forEach (dart:core-patch/growable_array.dart:254)
#5      DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:604)
#6      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7309)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#8      ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:429)
#9      DelegatingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140)
#10     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:425)
#11     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7316)
#12     DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:605)
#13     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7309)
#14     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4156)
#15     DelegatingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:383)
#16     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4152)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#18     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#19     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#20     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#21     ForStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4895)
#22     DelegatingAstVisitor.visitForStatement (package:analyzer/dart/ast/visitor.dart:425)
#23     ForStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4887)
#24     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#25     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#26     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#27     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#28     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1228)
#29     DelegatingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:189)
#30     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1224)
#31     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5234)
#32     DelegatingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:447)
#33     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5228)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#35     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:429)
#36     DelegatingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140)
#37     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:425)
#38     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7316)
#39     DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:605)
#40     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7309)
#41     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4156)
#42     DelegatingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:383)
#43     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4152)
#44     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#45     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#46     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#47     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#48     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1228)
#49     DelegatingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:189)
#50     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1224)
#51     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5234)
#52     DelegatingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:447)
#53     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5228)
#54     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#55     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:429)
#56     DelegatingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:140)
#57     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:425)
#58     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7316)
#59     DelegatingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:605)
#60     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7309)
#61     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4156)
#62     DelegatingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:383)
#63     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4152)
#64     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#65     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284)
#66     DelegatingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:182)
#67     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1280)
#68     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1228)
#69     DelegatingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:189)
#70     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1224)
#71     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5234)
#72     DelegatingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:447)
#73     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5228)
#74     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5080)
#75     DelegatingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:432)
#76     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5073)
#77     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#78     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2446)
#79     DelegatingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:252)
#80     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#81     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:3035)
#82     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#83     AnalysisTask.perform (package:analyzer/task/model.dart:229)
#84     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#85     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#86     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1182)
#87     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#88     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1180)
#89     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#90     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#91     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#92     _rootRun (dart:async/zone.dart:946)
#93     _CustomZone.run (dart:async/zone.dart:826)
#94     _CustomZone.runGuarded (dart:async/zone.dart:724)
#95     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#96     _rootRun (dart:async/zone.dart:950)
#97     _CustomZone.run (dart:async/zone.dart:826)
#98     _CustomZone.runGuarded (dart:async/zone.dart:724)
#99     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#100    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#101    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#102    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:207)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:207)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
	at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:868)
```

**Comment by bwilkerson** [comment] 2016-06-02 14:25
Yes, thanks! That should be enough to track down and fix the bug.

**Comment by pq** [comment] 2016-06-02 14:28
Thanks!

I see what's up and will have a fix shortly.  FWIW @bwilkerson : unless you think element being null in this case is symptomatic of a deeper issue I think this is limited to a bug in the newly added `iterable_contains_unrelated_type` lint.  Since this lint is opt-in, I'm not sure it's a `1.17` blocker.

**Comment by pq** [comment] 2016-06-02 14:31
I believe this was actually fixed in https://github.com/dart-lang/linter/commit/54ba86588034dc16982633e5e3551f32a0da64da.  We're not seeing that fix in the SDK because DEPS are pointing to an older rev of the linter...

**Comment by zoechi** [comment] 2016-06-02 14:31
That could be. I added these rules recently.

**Comment by bwilkerson** [comment] 2016-06-02 14:45
@pq Sounds like we need to update the DEPS to pull a newer version of the linter into the SDK, but other than that I think this bug is fixed, so I'm going to close it.

**Closed by bwilkerson** 2016-06-02 14:45 UTC
Labels: analyzer-linter, area-analyzer, P1 high, Type: bug

**Comment by pq** [comment] 2016-06-02 16:55
PS: thanks for catching this @zoechi!  Would have been unfortunate if this version of the rule had made it's way into the stable SDK. 

Cheers! 🍻
