### ISSUE TITLE
Invalid extension crashes the CFE

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44844] opened 2021-02-03 05:03 UTC
The following (invalid) program crashes the CFE:

```dart
extension on int {
  static int foo = 2;
  void foo() {}
}

void main() {
  3.foo();
}
```

with the following stack trace:

```
Invalid argument(s): Missing canonical name for Reference to _extension#0|foo
#0      BinaryPrinter.writeNonNullReference (package:kernel/binary/ast_to_binary.dart:896:9)
#1      BinaryPrinter.visitStaticInvocation (package:kernel/binary/ast_to_binary.dart:1632:5)
#2      StaticInvocation.accept (package:kernel/ast.dart:5177:44)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:394:10)
#4      BinaryPrinter.visitExpressionStatement (package:kernel/binary/ast_to_binary.dart:1949:5)
#5      ExpressionStatement.accept (package:kernel/ast.dart:7004:43)
#6      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:394:10)
#7      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:304:7)
#8      BinaryPrinter.visitBlock (package:kernel/binary/ast_to_binary.dart:1959:5)
#9      Block.accept (package:kernel/ast.dart:7048:43)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:394:10)
#11     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:487:7)
#12     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:1387:5)
#13     FunctionNode.accept (package:kernel/ast.dart:3081:38)
#14     BinaryPrinter.writeFunctionNode (package:kernel/binary/ast_to_binary.dart:401:10)
#15     BinaryPrinter.writeOptionalFunctionNode (package:kernel/binary/ast_to_binary.dart:496:7)
#16     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1253:5)
#17     Procedure.accept (package:kernel/ast.dart:2560:40)
#18     BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:422:10)
#19     BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:313:7)
#20     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1013:5)
#21     Library.accept (package:kernel/ast.dart:610:38)
#22     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:415:10)
#23     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:723:9)
#24     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:566:7)
#25     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#26     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:548:14)
#27     serializeComponent (package:front_end/src/fasta/kernel/utils.dart:69:11)
#28     _processLoadRequest (file:///Users/leafp/src/dart-repo/sdk/pkg/vm/bin/kernel_service.dart:879:13)
<asynchronous suspension>
```

**Comment by simolus3** [comment] 2021-02-06 13:19
Duplicate of #44003

**Closed** 2021-02-09 15:57 UTC
Labels: area-front-end
