### ISSUE TITLE
Parse getter with the same name of the enclosing class

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30981] opened 2017-10-03 21:46 UTC
```dart
class A {
  get A => 0;
}
```

```kernel
library;
import self as self;
import "dart:core" as core;

class A extends core::Object {
  constructor •() → void
    : super core::Object::•()
    const core::_ConstantExpressionError::•()._throw(new core::_CompileTimeError::•("file:///test.dart:2:12: Error: Can't return from a constructor.\n  get A => 0;\n           ^"));
}
```

The produced Kernel does not correspond to the original Dart code.

**Comment by peter-ahe-google** [comment] 2017-10-04 16:10
Interesting. Fasta doesn't even report an error if I change it to this:

```
class A {
  get A {
    print("Actually, I'm a getter, not a constructor.");
  }
}

main() {
  new A();
}
```

```
library;
import self as self;
import "dart:core" as core;

class A extends core::Object {
  constructor •() → void
    : super core::Object::•() {
    core::print("Actually, I'm a getter, not a constructor.");
  }
}
static method main() → dynamic {
  new self::A::•();
}
```

**Comment by peter-ahe-google** [comment] 2017-10-04 16:11
Let me know if this is blocking you.

**Comment by bwilkerson** [comment] 2017-12-01 19:10
I believe that this fixes the AstBuilder (https://dart-review.googlesource.com/c/sdk/+/25580). I've started looking at kernel, but don't know whether I'll have any success and don't mind having someone else look at it.

**Comment by bwilkerson** [comment] 2017-12-02 16:41
@peter-ahe-google I made some changes (https://dart-review.googlesource.com/c/sdk/+/25600) but there was no change in the test status, which either means that my changes didn't have the intended effect or that there are no tests for this case. Advice would be appreciated.

**Comment by peter-ahe-google** [comment] 2018-02-02 18:54
@bwilkerson I would add the above examples to pkg/front_end/testcases.

Also, @askeksa-google is working on a similar bug. See #30834 and https://dart-review.googlesource.com/c/sdk/+/34120

**Comment by peter-ahe-google** [comment] 2018-02-02 18:57
Also #31299

**Comment by askeksa-google** [comment] 2018-02-06 11:12
After https://dart-review.googlesource.com/c/sdk/+/34120 the code now produces a getter properly, plus a synthetic constructor. Can this issue be closed?

**Comment by peter-ahe-google** [comment] 2018-02-06 11:35
I'd be most comfortable closing this bug after we've added a regression test corresponding to the getter from my example.

**Closed** 2018-02-21 11:13 UTC
Labels: P2 medium, area-front-end, front-end-fasta
