### ISSUE TITLE
Dart analysis server: NoSuchMethodError: The method 'refresh' was called on null.

### ISSUE THREAD

**Issue by matthewlloyd** [dart-lang/sdk#36680] opened 2019-04-19 18:20 UTC
Analyzer Feedback from IntelliJ

## Version information

- `IDEA IC-191.6707.61`
- `2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36`
- `IC-191.6707.61, JRE 1.8.0_202-release-1483-b44x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.4, screens 1680x1050  Retina`

## Exception
```
Dart analysis server, SDK version 2.2.0-edge.0a7dcf17eb5f2450480527d6ad1e201fb47f1e36, server version 1.23.0, error: Captured exception
NoSuchMethodError: The method 'refresh' was called on null.
Receiver: null
Tried calling: refresh(Instance of 'DeclarationsContext')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      DeclarationsTracker._performChangeFile (package:analyzer/src/services/available_declarations.dart:611:15)
#2      DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:473:7)
#3      CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:177:13)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2125:35)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#6      new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#7      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#8      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#9      Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#15     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#16     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#17     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#18     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#19     main (file:///b/rr/tmpgY2JrN/w/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

1555697608554 => {"id":"43187","method":"analysis.updateContent","params":{"files":{"/Users/<redacted>/flutter_app/lib/settings.dart":{"type":"remove"}}},"clientRequestTime":155569760
1555697608555 <= {"id":"43187","result":{}}
1555697608556 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1555697608588 <= {"event":"analysis.errors","params":{"file":"/Users/<redacted>/flutter_app/lib/settings.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/Users/mi
1555697608594 <= {"event":"analysis.highlights","params":{"file":"/Users/<redacted>/flutter_app/lib/settings.dart","regions":[{"type":"DIRECTIVE","offset":0,"length":20},{"type":"BUIL
1555697608602 <= {"event":"analysis.navigation","params":{"file":"/Users/<redacted>/flutter_app/lib/settings.dart","regions":[{"offset":7,"length":12,"targets":[0]},{"offset":28,"leng
1555697608602 <= {"event":"analysis.closingLabels","params":{"file":"/Users/<redacted>/flutter_app/lib/settings.dart","labels":[{"offset":25144,"length":717,"label":"Timer"}]}}
1555697608603 <= {"event":"analysis.outline","params":{"file":"/Users/<redacted>/flutter_app/lib/settings.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name"
1555697608603 <= {"event":"analysis.overrides","params":{"file":"/Users/<redacted>/flutter_app/lib/settings.dart","overrides":[]}}
1555697608605 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":1282,"uri":"package:flutter_app/settings.dart","items":[{"label":"Settings","element":{"kind":"CLASS","n
1555697608605 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1555697608605 <= {"event":"analysis.implemented","params":{"file":"/Users/<redacted>/flutter_app/lib/settings.dart","classes":[],"members":[]}}
1555697609526 => {"id":"43188","method":"analysis.setPriorityFiles","params":{"files":["/Users/<redacted>/flutter_app/lib/main.dart"]},"clientRequestTime":1555697609526}
1555697609526 => {"id":"43189","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/<redacted>/flutter_app/lib/main.dart"],"CLOSING_LABELS":["/Users/mi
1555697609528 <= {"id":"43188"}
1555697609530 <= {"id":"43189"}
1555697609530 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1555697609553 <= {"event":"analysis.errors","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"/Users/mil/De
1555697609561 <= {"event":"analysis.highlights","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","regions":[{"type":"DIRECTIVE","offset":245,"length":71},{"type":"BUILT_
1555697609564 <= {"event":"analysis.navigation","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","regions":[{"offset":252,"length":31,"targets":[0]},{"offset":289,"lengt
1555697609565 <= {"event":"analysis.closingLabels","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","labels":[{"offset":1332,"length":167,"label":"MaterialApp"},{"offset
1555697609566 <= {"event":"analysis.outline","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<u
1555697609567 <= {"event":"analysis.overrides","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","overrides":[{"offset":1291,"length":5,"superclassMember":{"element":{"ki
1555697609570 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1555697609570 <= {"event":"analysis.implemented","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","classes":[],"members":[]}}
1555697609783 => {"id":"43190","method":"edit.getAssists","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","offset":1123,"length":0},"clientRequestTime":1555697609783}
1555697609785 <= {"id":"43190","result":{"assists":[]}}
1555697611103 => {"id":"43191","method":"edit.getAssists","params":{"file":"/Users/<redacted>/flutter_app/lib/main.dart","offset":1171,"length":0},"clientRequestTime":1555697611103}
1555697611109 <= {"id":"43191","result":{"assists":[]}}
1555697806462 <= {"event":"server.error","params":{"isFatal":false,"message":"Captured exception","stackTrace":"NoSuchMethodError: The method 'refresh' was called on null.\nReceiver: null\nTried calli
```

**Comment by kevmoo** [comment] 2019-04-20 01:22
Duplicate of #36522

**Closed by kevmoo** 2019-04-20 01:22 UTC
Labels: area-analyzer
